### PR TITLE
Updated google.visualization with OrgChart. Closes #3687

### LINKED ISSUE #3687: the Google Visualization definition is missing the OrgChart
See https://developers.google.com/chart/interactive/docs/gallery/orgchart for the doc of this chart

### PR DESCRIPTION
**Pull request by danmana**
Please fill in this template.
- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: [OrgChart](https://google-developers.appspot.com/chart/interactive/docs/gallery/orgchart)
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by gmoore-sjcorg** [comment]
@danmana I believe you need to uncomment the draw method accepting a DataView.
Also I would recommend a JSDoc comment if you indent to help the user determine sizing of the chart.
/** @type {string('small'|'medium'|'large')} ['medium'] Size of Chart */

**Comment by danmana** [comment]
@gmoore-sjcorg thanks for spotting the commented line, I was testing something and forgot to add it back.
I added the jsdoc comment as well, but I couldn't get the `@type {string('small'|'medium'|'large')}` to work using the string keyword - see https://github.com/jsdoc3/jsdoc/issues/629

**Comment by vvakame** [comment]
:eyes:

**Comment by gmoore-sjcorg** [comment]
👍

**Comment by danmana** [comment]
@vvakame done, rebased & resolved conflicts

**Pull request merged**
