### PR TITLE
Update index.d.ts to reflect actual Parcel API

### PR DESCRIPTION
**Pull request by patreeceeo**
I've found that these are the correct types for Parcel's environment. What's there now appears to be copied from `webpack-env`?

This is based on its [HMR runtime code](https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/hmr/src/loaders/hmr-runtime.js) and checking also what globals are available in an app being built with Parcel (`require` was undefined.)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/parcel-env/index.d.ts
1. types/parcel-env/parcel-env-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7d0a803915d06e3356f67a363ec5255c94308672
</p>

**Comment by patreeceeo** [comment]
Please note: I didn't include all of the properties on `ParcelRequireFunction`, just the ones I understand and that seem potentially useful to Parcel users, and not just Parcel internals.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/parcel-env/index.d.ts
1. types/parcel-env/parcel-env-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e45df628adf79b99117b2077f577a039da9d356f
</p>

**Comment by gabritto** [comment]
It's hard to review those changes as a DT maintainer. I have some questions that might make it easier for a DT reviewer to review this, since no owner has. What are the type definitions here supposed to capture? Is there documentation to verify the changes against? Is there an implementation? What's the relation of https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/hmr/src/loaders/hmr-runtime.js with the types here?

> Please note: I didn't include all of the properties on ParcelRequireFunction, just the ones I understand and that seem potentially useful to Parcel users, not just Parcel's own developers.  

I also can't provide useful judgment here. Ideally everything that's not intended to be private should be in the type definitions.

**Comment by patreeceeo** [comment]
These type definitions are supposed to capture my best guess at the public API for Parcel's runtime API.

[Here is its (in my opinion, incomplete) documentation](https://parceljs.org/features/development/#hot-reloading).

> What's the relation of https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/hmr/src/loaders/hmr-runtime.js with the types here?

These are the type definitions for that module.

Note that the existing DT type defs for Parcel's HMR runtime are incorrect and seem to be copy/pasted from that of Webpack. I thought this was at least a step in the right direction.

**Review by andrewbranch — APPROVED** [review]

**Comment by patreeceeo** [comment]
Ready to merge

**Pull request merged**
