### PR TITLE
Changed expect to var like other globals so it can be overriden for u…

### PR DESCRIPTION
**Pull request by ollie5463**
…se with chai

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by ExE-Boss** [comment]
This should have tests added for this change.

**Comment by rbuckton** [comment]
@ollie5463 can you add a test to ensure someone doesn't come along with a later PR and revert this back to `const`?

**Comment by orta** [comment]
+1-ing to Ron's feedback, would be fine to merge with that

**Comment by ollie5463** [comment]
> @ollie5463 can you add a test to ensure someone doesn't come along with a later PR and revert this back to `const`?

Hey Ron! Just looking into this now. When i am running the tests without my change they seem to be failing. I am getting this error.
Screenshot 2020-12-23 at 09 19 39

I get this when running `npm run test jest` or `yarn test jest` . Not sure if this is an issue locally or whether the tests are genuinely failing?

Thanks! 😁

**Comment by ollie5463** [comment]
> > @ollie5463 can you add a test to ensure someone doesn't come along with a later PR and revert this back to `const`?
> 
> Hey Ron! Just looking into this now. When i am running the tests without my change they seem to be failing. I am getting this error.
> Screenshot 2020-12-23 at 09 19 39
> 
> I get this when running `npm run test jest` or `yarn test jest` . Not sure if this is an issue locally or whether the tests are genuinely failing?
> 
> Thanks! 😁



> > @ollie5463 can you add a test to ensure someone doesn't come along with a later PR and revert this back to `const`?
> 
> Hey Ron! Just looking into this now. When i am running the tests without my change they seem to be failing. I am getting this error.
> Screenshot 2020-12-23 at 09 19 39
> 
> I get this when running `npm run test jest` or `yarn test jest` . Not sure if this is an issue locally or whether the tests are genuinely failing?
> 
> Thanks! 😁

To add to this, it seems like i can run other test suites fine e.g. java, 3box & abs

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
+1 for tests

**Pull request closed without merging**
