### PR TITLE
react: Revert "Fix RefForwardingComponent argument type. (#30373)"

### PR DESCRIPTION
**Pull request by OliverJAsh**
This reverts commit 0d49c9a4c64f865be4b5d5cd5833110c56ca301a.

Partially reverts https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30373

This isn't needed since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30510, as the `Ref` union now includes `null`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

/cc @Luixo @Jessidhia

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Not sure what to advise. I wonder if @jessidhia can help?

**Comment by ferdaber** [comment]
This is a recent change in TS which I think does better checks on allowable `children` types in JSX. It happened in my PR too.

**Comment by ferdaber** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32279/files for the necessary changes. Or wait for my PR to be merged before you do yours, which should fix the tests for the failing dependencies.

**Review by Jessidhia — APPROVED** [review]
Nice, the excess property checks for `children` are working in 3.3 😈

---

I don't actually have anything to add here, just an LGTM.

**Pull request merged**
