### PR TITLE
[@types/google-cloud__storage] Update FileMetadata interface

### PR DESCRIPTION
**Pull request by ogawa0071**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://cloud.google.com/storage/docs/json_api/v1/objects
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by blove** [comment]
Travis vuild appears to be failing.

**Comment by ogawa0071** [comment]
@blove 
Yes, but I can"t fix it.

>>>
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

Why this build to long?

**Comment by ogawa0071** [comment]
Branch `master` when I forked is not pass the test.
Merged latest commits.

**Comment by nbperry** [comment]
@ogawa0071 This looks good and aligns with the docs provided. :+1:

**Review by nbperry — APPROVED** [review]

**Pull request merged**
