### PR TITLE
[lingui/core] Setup params locales and missing

### PR DESCRIPTION
**Pull request by andys8**
Solves #30136

### CODE REVIEW

**Review by huan086 — CHANGES_REQUESTED** [review]
Could you update the test file with

const setupResultWithMissingAsString: I18n = setupI18n({ catalogs, language: 'es',??? });

const setupResultWithMissingAsFunction: I18n = setupI18n({ catalogs, language: 'es',??? });

And

const setupResultWithLocale: I18n = setupI18n({ catalogs, language: 'es',??? });

**Comment by huan086** [comment]
Also, could you update the version number in the index header to reflect the version where these options get introduced?

**Comment by huan086** [comment]
See the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29330/files for the types of changes that are required

**Comment by andys8** [comment]
Thanks for the feedback. I bumped the version and added tests.

**Review by huan086 — APPROVED** [review]

**Comment by huan086** [comment]
Thanks!

**Pull request merged**
