### PR TITLE
Deprecate types for packages that provide their own types

### PR DESCRIPTION
**Pull request by BendingBender**
If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by carnesen — APPROVED** [review]

**Comment by SimonSchick** [comment]
How many packages are left after this omg.

**Review by SimonSchick — APPROVED** [review]

**Review by jay-medina — APPROVED** [review]

**Comment by BendingBender** [comment]
Imagine how many of them were out of date...

**Review by iRoachie — APPROVED** [review]

**Review by plantain-00 — APPROVED** [review]

**Comment by ivangabriele** [comment]
- [anybar](https://github.com/sindresorhus/anybar)
- [auto-bind](https://github.com/sindresorhus/auto-bind)
- [beeper](https://github.com/sindresorhus/beeper)
- [bin-version](https://github.com/sindresorhus/bin-version)
- [builtin-modules](https://github.com/sindresorhus/builtin-modules)
- [callsites](https://github.com/sindresorhus/callsites)
- [camelcase-keys](https://github.com/sindresorhus/camelcase-keys)
- [clean-stack](https://github.com/sindresorhus/clean-stack)
- [clear-require](https://github.com/sindresorhus/clear-require) **DEPRECATED**
- [cli-boxes](https://github.com/sindresorhus/cli-boxes)
- [cli-cursor](https://github.com/sindresorhus/cli-cursor)
- [clipboardy](https://github.com/sindresorhus/clipboardy)
- [condense-whitespace](https://github.com/sindresorhus/condense-whitespace)
- [convert-hrtime](https://github.com/sindresorhus/convert-hrtime)
- [create-html-element](https://github.com/sindresorhus/create-html-element)
- [crypto-hash](https://github.com/sindresorhus/crypto-hash)
- [crypto-random-string](https://github.com/sindresorhus/crypto-random-string)
- [cycled](https://github.com/sindresorhus/cycled)
- [dargs](https://github.com/sindresorhus/dargs)
- [debounce-fn](https://github.com/sindresorhus/debounce-fn)
- [define-lazy-prop](https://github.com/sindresorhus/define-lazy-prop)
- [detect-newline](https://github.com/sindresorhus/detect-newline)
- [devtools-detect](https://github.com/sindresorhus/devtools-detect)
- [dot-prop](https://github.com/sindresorhus/dot-prop)
- [electron-config](https://github.com/sindresorhus/electron-config)
- [electron-debug](https://github.com/sindresorhus/electron-debug)
- [electron-is-dev](https://github.com/sindresorhus/electron-is-dev)
- [electron-store](https://github.com/sindresorhus/electron-store)
- [electron-unhandled](https://github.com/sindresorhus/electron-unhandled)
- [electron-util](https://github.com/sindresorhus/electron-util)
- [elegant-spinner](https://github.com/sindresorhus/elegant-spinner)
- [empty-trash](https://github.com/sindresorhus/empty-trash)
- [file-url](https://github.com/sindresorhus/file-url)
- [filter-console](https://github.com/sindresorhus/filter-console)
- [find-versions](https://github.com/sindresorhus/find-versions)
- [first-run](https://github.com/sindresorhus/first-run)
- [get-emails](https://github.com/sindresorhus/get-emails)
- [get-urls](https://github.com/sindresorhus/get-urls)
- [git-remote-origin-url](https://github.com/sindresorhus/git-remote-origin-url)
- [github-username](https://github.com/sindresorhus/github-username)
- [gravatar-url](https://github.com/sindresorhus/gravatar-url)
- [gzip-size](https://github.com/sindresorhus/gzip-size)
- [has-emoji](https://github.com/sindresorhus/has-emoji)
- [hex-rgb](https://github.com/sindresorhus/hex-rgb)
- [in-range](https://github.com/sindresorhus/in-range)
- [locate-path](https://github.com/sindresorhus/locate-path)
- [pkg-up](https://github.com/sindresorhus/pkg-up)
- [plur](https://github.com/sindresorhus/plur)
- [random-float](https://github.com/sindresorhus/random-float)
- [random-int](https://github.com/sindresorhus/random-int)
- [random-item](https://github.com/sindresorhus/random-item)
- [random-obj-key](https://github.com/sindresorhus/random-obj-key)
- [random-obj-prop](https://github.com/sindresorhus/random-obj-prop)
- [resolve-from](https://github.com/sindresorhus/resolve-from)
- [resolve-global](https://github.com/sindresorhus/resolve-global)
- [unique-random-array](https://github.com/sindresorhus/unique-random-array)
- [unique-random](https://github.com/sindresorhus/unique-random)
- [write-json-file](https://github.com/sindresorhus/write-json-file)

**Review by ivangabriele — APPROVED** [review]

**Review by MrManny — APPROVED** [review]
I don't know if my approval is actually *needed* for this, but I approve regardless. :-)

**Review by jsynowiec — APPROVED** [review]
Can confirm/approve the following packages:
• `electron-config` was renamed to [`electron-store`](https://github.com/sindresorhus/electron-store)
• [`electron-debug`](https://github.com/sindresorhus/electron-debug)
• [`electron-is-dev`](https://github.com/sindresorhus/electron-is-dev)
• [`electron-unhandled`](https://github.com/sindresorhus/electron-unhandled)
• [`electron-util`](https://github.com/sindresorhus/electron-util)

It seems that most packages by @sindresorhus have type definitions now (or there are PRs adding them).

**Comment by BendingBender** [comment]
All the packages I've removed have TS definitions. No packages in the list have definitions pending.

**Comment by forivall** [comment]
Can confirm that pkg-up now provides its own types. (Another one from sindre 😄)

**Comment by jeremejevs** [comment]
IMO, this is a downgrade, even considering that Sindre has quick turnaround on PRs: fewer qualified eyes to review typing changes, trickier cross-module testing, no linting. But oh well, what's done is done.

**Comment by BendingBender** [comment]
Still far better queality due to always up-to-date definitions.

**Comment by sindresorhus** [comment]
> fewer qualified eyes to review typing changes

That's a good point. If anyone wants to volunteer, I would be happy to mention them when I get type-related PRs. Or you could check https://github.com/search?o=desc&q=user%3Asindresorhus+is%3Apr+%22TypeScript%22&s=created&type=Issues once in a while.

> no linting

This will change soon. I plan to add [first-class TypeScript support](https://github.com/xojs/xo/issues/373) to the linter tool I use in all my packages. And we already do some non-style linting with [`tsd`](https://github.com/SamVerschueren/tsd).

---

> Still far better quality due to always up-to-date definitions.

👍 This. No changes are merged in my packages now without also updating the type definitions.

Another benefit is users not having to install `@types/*` packages.

**Comment by jeremejevs** [comment]
> No changes are merged in my packages now without also updating the type definitions.

Presence of a policy like this is a big deal, I've seen way too many typing issues and PRs hanging open for months. Now I agree, this is likely a net positive.

**Comment by BendingBender** [comment]
@jeremejevs This is especially a problem with types on DT. This happens here much more often than with packages that have types bundled with them.

**Comment by jeremejevs** [comment]
Correlation != causation. It's about the commitment to keeping typings up-to-date, not their location. In the meanwhile, it's easy to fix neglected typings in DT, while integrated ones are a lottery (have personally seen PRs rot for multiple months). Doesn't apply to this case, though, so all good.

**Comment by bfred-it** [comment]
> have personally seen PRs rot for multiple months

In that case there should be an easy way to extract those types automatically and push them to DT.

The opposite direction should also be more automatic: instead of having a `notNeededPackages`, whichever tool that looks into that file should instead fetch the package from npm and look for types.

**Comment by jeremejevs** [comment]
@bfred-it I agree, there is plenty of room for improvement, but on TypeScript's part and somewhere in the future, while we're dealing with the current reality here.

**Pull request merged**
