### PR TITLE
(DO NOT MERGE) react-native: Add PlatformColor, DynamicColorIOS, LogBox API

### PR DESCRIPTION
**Pull request by Naturalclar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

Preparing type definition for PlatformColor, DynamicColorIOS, and LogBox for RN 0.63

### CODE REVIEW

**Comment by TheSavior** [comment]
cc @tom-un. I think Tom had some things in mind for the TypeScript types for these functions that enforces a bit more of a constraint so that people don't write these objects by hand.

**Comment by alloy** [comment]
Does the content of `NativeColorValue` even really need to be exposed to user-space, or could it be an opaque type?

**Comment by Naturalclar** [comment]
@alloy I agree that NativeColorValue type does not need to be exposed.
Is there a typescript equivalent of flowtype's `opaque` type?

**Comment by alloy** [comment]
> Is there a typescript equivalent of flowtype's `opaque` type?

There is no direct equivalent. In this case you could perhaps (ab)use a `unique symbol`?

```ts
declare const _NativeColorValue: unique symbol;
type NativeColorValue = typeof _NativeColorValue;
```

**Pull request closed without merging**
