### PR TITLE
[splitting] Add types for splitting

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Related discussion: #63983

Adds types for the npm package `splitting` (<https://www.npmjs.com/package/splitting>)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
This module is just UMD (distributed in `dist` directory), but that does not mandate IMO those additional files. The README stipulates usage:
``ts
import "splitting/dist/splitting.css";
import "splitting/dist/splitting-cells.css";
import Splitting from "splitting";
```
so if anything, I would expect adding support for `.css` fils for 'splitting' module, if anything.
Otherwise it is just an old school, UMD-exported module

**Comment by MysteryBlokHed** [comment]
What's the best way to add types to import CSS files?

**Comment by peterblazejewicz** [comment]
> ```ts
> import "splitting/dist/splitting.css";
> import "splitting/dist/splitting-cells.css";
> ```

try this, it should be enough to just support paths imports in TS files (those are just links for tools like webpack  I assume):
```ts
...
// tslint:disable-next-line:no-declare-current-package
declare module 'splitting/dist/splitting-cells.css';

// tslint:disable-next-line:no-declare-current-package
declare module 'splitting/dist/splitting.css';

export = Splitting;
export as namespace Splitting;
```

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@MysteryBlokHed thanks!

**Comment by MysteryBlokHed** [comment]
Ready to merge

**Pull request merged**
