### PR TITLE
make express.Application compatible with http.createServer

### PR DESCRIPTION
**Pull request by mahald**
change as discussed in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10521#issuecomment-240472624

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Does it fix this? I have doubt about it. If I have time, I will research how to do.

**Comment by mahald** [comment]
Yes it does. Compiles and passes the linter.

**Comment by TonyPythoneer** [comment]
Yes, you're right. :smile:

**Comment by Strate** [comment]
This change made work with express harder if compiler option `strictNullChecks` enabled.
As for now, I should explicitly do:
```ts
app.get("/", function(req, res, next) {
  if (next) {
    next()
  } // what should be in else?
})
```
Also, express documentation says nothing about possible missing `next` argument in any middleware.

**Pull request merged**
