### PR TITLE
Allow `false` for $mdToast hideDelay

### PR DESCRIPTION
**Pull request by DavidSouther**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

https://material.angularjs.org/latest/api/service/$mdToast

and used

https://github.com/angular/material/blob/338710901e7ac1f9d8f0f4b44d75707cf5efb5fb/src/core/services/interimElement/interimElement.js#L665

### CODE REVIEW

**Comment by AlStar01** [comment]
@DavidSouther the parameters for hideDelay should be something like the following to allow for either a number or false (boolean):

`hideDelay(delay: number|boolean): T;`

The checks are likely failing as value `false` isn't a valid type. You can run `npm test` at the base of the project to ensure the tests are passing.

Thanks!

**Comment by DavidSouther** [comment]
Boolean literal types come in 2.1, I should have thought of that first. (Tests did pass because I've hacked the crap out of my local system to only use tsc@head :/) This most certainly should NOT be `number|boolean`, as `true` will give users a very bad time. I'll leave this open, with the note that it requires TypeScript > 2.1 for future reference.

**Comment by andy-ms** [comment]
Please make a new PR targeting `types-2.0`. (By the way, boolean literal type declarations work in TypeScript 2.0; the link refers to the *inference* improving.)

**Comment by DavidSouther** [comment]
Gotcha, I _thought_ I had used that in production code before but had gotten myself confused. Thanks for the clarification.

**Pull request closed without merging**
