### PR TITLE
Create typings for jquery-alertable

### PR DESCRIPTION
**Pull request by stever**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

Library: https://github.com/claviska/jquery-alertable

### CODE REVIEW

**Comment by stever** [comment]
https://www.npmjs.com/package/@claviska/jquery-alertable

**Comment by vvakame** [comment]
umm...
Now, we don't have a good way about npm scoped package handling in this repository.

@andy-ms @RyanCavanaugh @mhegazy do you have any plan to do this in [types-publisher](https://github.com/Microsoft/types-publisher)?

FYI
https://github.com/npm/npm/blob/master/doc/files/package.json.md#name

**Comment by vvakame** [comment]
#11658 related.

**Comment by mhegazy** [comment]
Scoped packages are not supported currently. The issue is a bit complicated and i do not think it will be addressed in the short term. I have created issue https://github.com/Microsoft/types-publisher/issues/155 for that.

**Comment by mhegazy** [comment]
since this is not a module, i.e. not imported using `require("@claviska/jquery-alertable");` adding it under the name of `jquery-alertable` seems benign, though not correct.

**Pull request merged**
