### PR TITLE
Update according to https://github.com/gulpjs/vinyl/releases/tag/v1.1.0

### PR DESCRIPTION
**Pull request by DomiR**

### CODE REVIEW

**Comment by jedmao** [comment]
You should preserver the older version before introducing a new major version. See http://definitelytyped.org/guides/contributing.html#version

Also, you need to write some tests to go along w/ this.

**Comment by DomiR** [comment]
Thanks for the quick reply. I've updated my pull request. Would you please be so kind an review it again?

**Comment by jedmao** [comment]
Cool! Now squash these 2 commits into 1 and you have my :+1:

**Comment by DomiR** [comment]
Done, thanks again

**Comment by jedmao** [comment]
:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
