### PR TITLE
Adding more siblings to Red interface in node-red

### PR DESCRIPTION
**Pull request by tbowmo**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by tbowmo** [comment]
I did not add tests, as there is really nothing to test..
Found that for node-red there was missing entries for Red.httpAdmin and Red.auth

**Comment by tbowmo** [comment]
for reference, the targeted interface in Node-red is this one

https://github.com/node-red/node-red/blob/master/red/red.js

**Comment by andersea** [comment]
You've got a typo on line 22 `htttpAdmin`.

We should work towards having each property documented, instead of using any type. For now if you could fix the typo, I will approve the pr.

**Comment by tbowmo** [comment]
Yes.. copied manually from my test machine, so accidentally made a typo..

Corrected, and pushed..

And yes, a better typed interface instead of any type would be preferred. Will come at a later time, when I get more time for it.

**Review by andersea — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

**Pull request merged**
