### PR TITLE
node: Set "lib" to "es5"

### LINKED ISSUE #15083: TS2304 in @types/node^7.0.7
I tried using the `@types/node^7.0.7` package and had problems when running TSC in a [Travis build](https://travis-ci.org/ryansmith94/rulr/builds/209181447) (see log below).

```
node_modules/@types/node/index.d.ts(1841,45): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/node/index.d.ts(1845,20): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1850,17): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1854,19): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1855,10): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/node/index.d.ts(1855,30): error TS2304: Cannot find name 'Iterator'.
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #15083,

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by rchipman** [comment]
This PR broke our build with the following error message:

```
node_modules/@types/node/index.d.ts(50,14): error TS2687: All declarations of 'iterator' must have identical modifiers.
```

Deleting lines 49 through 51 of `@types/node/index.d.ts` from node_modules folder fixes the issue, also rolling back to `@types/node@7.0.7` fixes the issue.

Our project is an Angular 2 project and contains the following setup:

package.json
```
"dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/compiler-cli": "^2.4.7",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "@angular/upgrade": "~2.4.0",
    "angular2-moment": "^1.0.0-beta.6",
    "angularfire2": "^2.0.0-beta.6",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "^3.6.0",
    "font-awesome": "^4.6.3",
    "highcharts": "^5.0.7",
    "less": "^2.7.1",
    "moment": "^2.15.2",
    "ng2-highcharts": "^0.6.5",
    "reflect-metadata": "^0.1.3",
    "rxjs": "~5.1.0",
    "systemjs": "^0.19.27",
    "systemjs-plugin-css": "^0.1.29",
    "systemjs-plugin-less": "^0.1.1",
    "trianglify": "^1.0.1",
    "weather-icons": "^1.3.2",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.35",
    "@types/highcharts": "^4.2.47",
    "@types/jasmine": "*",
    "@types/node": "7.0.7",
    "concurrently": "^2.0.0",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-cli": "^1.2.2",
    "gulp-concat": "^2.6.1",
    "gulp-flatten": "^0.3.1",
    "gulp-html-replace": "^1.6.1",
    "gulp-less": "^3.1.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-path": "^3.0.3",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-shell": "^0.5.2",
    "gulp-sourcemaps": "^2.1.1",
    "gulp-task-listing": "^1.0.1",
    "gulp-typescript": "^3.0.2",
    "gulp-util": "^3.0.8",
    "gulp-watch": "^4.3.10",
    "replace": "^0.3.0",
    "rollup": "0.36.1",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-uglify": "^1.0.1",
    "run-sequence": "^1.2.2",
    "systemjs-builder": "^0.15.32",
    "typescript": "^2.0.10"
  }
```

tsconfig.json
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    // "lib": [ "es2015", "dom" ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules/*",
    "aot/*",
    "app/*-aot.ts"
  ]
}
```

tsconfig-aot.json
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "files": [
        "app/app.module.ts",
        "app/main-aot.ts"
    ],
    "angularCompilerOptions": {
        "genDir": "aot",
        "skipMetadataEmit" : true
    }
}
```

Thanks!

**Comment by andy-ms** [comment]
@rchipman could you use find-all-references to find the other definition of `iterator`?

**Comment by rchipman** [comment]
@andy-ms None other found that should effect the one that you added.  See the screenshot below.

Could it be related to the TypeScript version?

screen shot 2017-03-10 at 10 12 19 am

**Comment by andy-ms** [comment]
Found the issue for that: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11700
We should fix `chai-enzyme`.

**Pull request merged**
