### PR TITLE
Update styled-system types to 4.1

### PR DESCRIPTION
**Pull request by LavaToaster**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/styled-system/styled-system/blob/master/src/index.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

I did re-arrange a few things since it makes it easer to do side by side diffs.

### CODE REVIEW

**Comment by peduarte** [comment]
@Lavoaster hello there 👋 
Thank you so much for creating this. 
This PR closes #34794 

But anyway, I noticed a few more things that still don't work:
- `fontSizes` scale should accept an array of strings 
- `fontSizes` scale should accept an object literal 
Also, should be able to
```
// aliases
fontSizes.body = fontSizes[2]
fontSizes.display = fontSizes[5]
```
- `scale`  should behave the same as `fontSizes`
- `colors` object should accept a nested array of objects, like this:
```
const theme: Theme = {
  colors: {
    black: 'hsl(0, 0%, 0%)',
    blacks: [
      'hsla(0, 0%, 0%, .9)',
      'hsla(0, 0%, 0%, .7)',
      'hsla(0, 0%, 0%, .5)',
      'hsla(0, 0%, 0%, .3)',
      'hsla(0, 0%, 0%, .1)',
    ],
    white: 'hsl(0, 0%, 100%)',
    whites: [
      'hsla(0, 0%, 100%, .9)',
      'hsla(0, 0%, 100%, .7)',
      'hsla(0, 0%, 100%, .5)',
      'hsla(0, 0%, 100%, .3)',
      'hsla(0, 0%, 100%, .1)',
    ],
  },
};
```

---

I really wanna help contribute to this, I even forked, cloned the repo, but everytime I made a change to the file, prettier was re-formatting everything, and I didn't wanna create a PR with a bunch of formatting changes.

Is it common to not have editor config/prettier in these packages? So the code styles are consistent?

**Comment by peduarte** [comment]
Also just realised that we should be able to read the `propTypes` from Styled System funcitons.

For example:

```jsx
import { space } from 'styled-system';

console.log(space.propTypes);
```

Currently, we're getting the following error:
```
Property 'propTypes' does not exist on type '(...args: any[]) => any'.ts(2339)
```

**Comment by Lavoaster** [comment]
mergeplz

**Review by eduardo-dangelo — APPROVED** [review]

**Comment by peduarte** [comment]
@Lavoaster did you get a chance to read the comments I left

**Comment by Lavoaster** [comment]
@peduarte I have, but I also don't really have the time to respond to them, and they're not related to this PR. 

The changes you want to make to the theme are fairly trivial (if you know your types) and easily doable, but I'm unwilling to make them as I don't use the theme here so I'm not really able to properly test them out in real world code.

Additionally, propTypes are a different thing entirely and I don't believe they should be typed up in here. The fact styled-system offers them is to help with JS consumers that rely on `prop-types`, and if the functions were React Components you'd be able to use them, but they aren't really react components. The only benefit you'd get from them being typed up here is if you are building something that is a library in typescript that isn't going to be consumed by a project in typescript.

**Comment by peduarte** [comment]
@Lavoaster Thank you for the the time to reply.

Some of those changes are crucial to how the library works. I think if the Theme interface is going to be incorrect, you might as well not make one, or just use `any`.

In regards to `propTypes`, they're extremely useful specially when working with TS, as you can't forward any props to any child.

So I use `pick` to only pick System Props so I can spread them onto a Styled System component.

There's a lot of work being done around Styled System and it's only going to get more and more popular, so I think it's a good opportunity to have the types done accurately.

That's one of the reasons I was proposing for Styled System to be [re-written in Typescript](https://github.com/styled-system/styled-system/issues/463) that way we wouldn't need to rely on third-party TS definitions.

@jxnblk FYA

**Comment by peduarte** [comment]
A few more issues:

If you don't want to address these as part of this PR I'll create issues and try to implement them myself, it's not a problem 👍 

The following are missing:
- `GridTemplateColumnsProps`
- `GridTemplateRowsProps`
- `GridTemplateAreasProps`

Looks like they've been misspelt, and are written as `Templates` (in plural)

**Comment by PranavSenthilnathan** [comment]
@peduarte I'll merge this now, but please feel free to contribute your changes in a separate PR.

**Pull request merged**
