### PR TITLE
Pathkit Type Definitions

### PR DESCRIPTION
**Pull request by owo**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

These are type definitions for [Skia Pathkit](https://skia.org/docs/user/modules/pathkit/) which provides two NPM packages with the same exact API, a [WASM version](https://www.npmjs.com/package/pathkit-wasm) and an [asm.js version](https://www.npmjs.com/package/pathkit-asmjs). This type definition package addresses both of them. There's also a related issue I posted that hasn't been addressed yet (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/65686).

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
what's the relation to a `pathkit` package already existing on NPM?
can you split those into a two, and just first deploy, say `asmjs` and next the other one, reusing types exported in first one?

**Comment by owo** [comment]
There's no relation at all. The [pathkit](https://www.npmjs.com/package/pathkit) NPM package seems unused, unmaintained, and looking at the code is just a little syntax sugar over node's `path` (about 100 LOC in total).

I felt it to be redundant to maintain two type definitions that are exact replicas of each other.

I did ask about it in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/65686 about a month ago and got no responses.

If you feel two packages would be a better way to go, I don't mind doing it that way.
In that case would I submit a single PR with both packages?

**Comment by peterblazejewicz** [comment]
> I don't mind doing it that way. In that case, would I submit a single PR with both packages?

Yes, definitely. I believe there are multiple of modules on DT intertangled tightly, just to avoid code duplication. (under the hood both packages are to be installed anyway, but only one would be used directly, the other as a dept container).
You can verify this installing any DT package, that rely on other DT package, let me show:
```console
npm i -D @types/karma-chrome-launcher
...
ls node_modules/@types
karma                 karma-chrome-launcher
```

**Review by andrewbranch — CHANGES_REQUESTED** [review]
@peterblazejewicz has the right advice.

More specifically, you’ll want to

- create one package that has all the types written out, but put actual files at e.g. `types/pathkit-asmjs/bin/pathkit.d.ts` instead of using `declare module 'pathkit-asmjs/bin/pathkit.js'`
- for the other package, you still need to make all the same files, but each one can do something like
  ```ts
  export * from "pathkit-asmjs/bin/pathkit.js";
  export { default } from "pathkit-asmjs/bin/pathkit.js";
  ```

**Review by kjlubick — APPROVED** [review]
The types and comments seem accurate to me.

**Pull request closed without merging**
