### PR TITLE
update(fs-extra): missing aliases

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- added missing aliases:
https://github.com/jprichardson/node-fs-extra/blob/3c3865cad8cae7f3046edf434c2ac76abaec7759/lib/empty/index.js#L43-L48
~~- dropped older v4 version to free resources and cut down tests timed
https://www.npmjs.com/package/fs-extra/v/4.0.3~~~
[edited] removed v4 removal as it is requried for other package compatibiltiy

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by andrewbranch** [comment]
Reopening to test CI fixes. @peterblazejewicz, do you still want to merge this one if it works?

**Comment by peterblazejewicz** [comment]
@andrewbranch rebased with latest master, so we can see this v4 drop passes CI gate.
I'm not to stress the update itself, we can close it after the test. I can re-pick and update at any time in future, when there is more interest in DT package update.

**Comment by andrewbranch** [comment]
Ooooh, I think the issue is that fs-extra-promise and graceful-fs have a path mapping to `fs-extra/v4` in their tsconfigs.

**Comment by peterblazejewicz** [comment]
let me check

**Comment by andrewbranch** [comment]
I added a better error message here: https://github.com/microsoft/DefinitelyTyped-tools/pull/148

**Comment by peterblazejewicz** [comment]
@andrewbranch I've again rebased, ditched that v4 removal (yes, you're correct about that dependency, cannot be recitfied IMO without much work, out-of-scope), I've redacted details and this PR is again valid to be merged,
when accepted.
Thanks for the help and spendign time on CI problem!

**Review by shiftkey — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot ahem...

**Review by ffflorian — APPROVED** [review]

**Comment by shiftkey** [comment]
Ready to merge

**Pull request merged**
