### PR TITLE
[marked] fix `this` parameter typings in Renderer functions

### PR DESCRIPTION
**Pull request by jfcere**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58301
    https://github.com/markedjs/marked/issues/2358

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## marked ([<kbd>unpkg</kbd>](https://unpkg.com/browse/marked@latest/))
was missing the following properties:
1. defaults
1. getDefaults
1. lexer
1. options
1. parse

<details>
<summary>as well as these 5 other properties...</summary>
<p>parseInline, parser, setOptions, use, walkTokens</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 59cb94992a09b7279ef893bec85c6642bf5986f6
</p>

**Review by UziTech — APPROVED** [review]
Looks good! 💯

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by jfcere** [comment]
Ready to merge

**Pull request merged**
