### PR TITLE
Updated Fabric JS Type Definitions for fabricjs v2.6.0

### PR DESCRIPTION
**Pull request by bmkrol823**
Went through and updated many of the type definitions to correspond with the latest version of Fabric JS. Added new definitions where possible.

- [ X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X] Test the change in your own code. (Compile and run.)
- [X ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by BradleyHill** [comment]
Trying to slay the dragon. Applaud the effort @bmkrol823. Love to see this through.

Was never entirely sure how to test definitions for code was not actively using. Anyway, pulling into our app to vet.

The only linting fail was Image.fromUrl had to change from loose `Function` to strongly typed function definition.
`static fromURL(url: string, callback?: (image: Image) => void, imgOptions?: IImageOptions): Image;`

**Comment by BradleyHill** [comment]
Went through full build and smoke tests. Almost all issues were crufty type definitions i.e. fabricjs had changed and definitions not updated. Valuable endeavor, thx.

Did find 2 hopefully can change:
`Text.setSelectionStyles`
Can we update last 2 params to be optional?
`setSelectionStyles(styles: any, startIndex?: number, endIndex?: number): Text;`
Looks like implicitly optional from fabricjs code:
```
if (typeof startIndex === 'undefined') {
  startIndex = this.selectionStart || 0;
}
if (typeof endIndex === 'undefined') {
  endIndex = this.selectionEnd || startIndex;
}
```

Could we add to IPatternOptions interface:
```
/**
 * The source for the pattern
 */
source: string | HTMLImageElement;
```
Think it's missing from the fabricjs definition but it is definitely referenced in the Pattern constructor:
```
initialize: function(options, callback) {
  options || (options = { });
  this.id = fabric.Object.__uid++;
  this.setOptions(options);
  if (!options.source || (options.source && typeof options.source !== 'string')) {
    callback && callback(this);
    return;
  }
  // function string
  if (typeof fabric.util.getFunctionBody(options.source) !== 'undefined') {
    this.source = new Function(fabric.util.getFunctionBody(options.source));
    callback && callback(this);
  }
```

I think with these 2 and previous mentioned change, i'd be comfortable approving. Semper anticus.

**Comment by bmkrol823** [comment]
Thanks @BradleyHill. I'm sure the updates I made haven't accounted for everything that was out of date/incorrect but hopefully covered a good portion. 
The first issue with setSelectionStyles I actually updated last night after I was working with some of my own code (primarily focused on Text boxes and IText currently) and noticed it.
I will add to the IPatternOptions interface as soon as this response is sent and should have it up to date here in a few minutes.
Thanks again.

**Comment by BradleyHill** [comment]
It'd be tough to hit everything given the nature of javascript and size of this library. Not always intuitive what is optional and stuff just accessed but not declared. Anyway, this is huge leap forward. Much appreciated.

If you could update Image.fromUrl to make callback strongly typed, i'll pull latest and run another build/smoke cycle. We are obviously not using every API but do reach a decent swath of it.
`static fromURL(url: string, callback?: (image: Image) => void, imgOptions?: IImageOptions): Image;`

Not that i'm the keeper, but if all that passes, see no glaring reason not to approve and proceed forward. Regards.

**Comment by bmkrol823** [comment]
@BradleyHill I have pushed the update for Image.fromURL as suggested. Thanks again!

**Comment by BradleyHill** [comment]
Alright, very close. Can we make `IPatternOptions.source` non-optional.
`source: string | HTMLImageElement;`

`Object.setPatternFill` is using `Pattern` for `IFillOptions` and `IFillOptions` has:
`source: string | HTMLImageElement;`

so typescript compiler complaining: `Type 'string | HTMLImageElement | undefined' is not assignable to type 'string | HTMLImageElement'`

**Comment by bmkrol823** [comment]
@BradleyHill IPatternOptions.source updated as requested.

**Review by BradleyHill — APPROVED** [review]
Booya. Thanks for bringing up to date. Not a trivial task. Much obliged.

**Pull request merged**
