### PR TITLE
Base classes to inherit from them (step 1 of X)

### PR DESCRIPTION
**Pull request by SergioMorchon**
Add a base class

### CODE REVIEW

**Comment by vvakame** [comment]
@armorik83 could you review this PR?

**Comment by SergioMorchon** [comment]
The only way I know is to commit step by step and, if ti looks fine, merge it.

How can I preview the Pool Request? What does that means? I have it locally working at my own Project.

**Comment by armorik83** [comment]
All right. I had overlooked that the generator implemented EventEmitter.

**Comment by vvakame** [comment]
@armorik83 thanks!
@SergioMorchon thanks mate.

**Pull request merged**
