### PR TITLE
(yargs) Updated to match the command signature as of 4.8.1

### PR DESCRIPTION
**Pull request by jan-molak**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by poelstra** [comment]
Small remarks:
* Would be nice to add a test for the options argument to commandDir() (although the yargs docs also don't seem to have one...)
* Indentation of Argv$help() is now inconsistent

Otherwise, looks good to me.

**Comment by jan-molak** [comment]
Sure, thanks for your feedback. I'll update the PR in a moment, stay tuned ;-)

**Comment by jan-molak** [comment]
@poelstra - updated the PR, please have a look when you have a moment. Thanks!

**Comment by poelstra** [comment]
@jan-molak wow, that's fast! :100: 

:+1: to merge!

**Pull request merged**
