### PR TITLE
dns-packet: Add missing functions/properties

### PR DESCRIPTION
**Pull request by TimWolla**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mafintosh/dns-packet/blob/5aebb85c3221292e994d01b68cadf067e78efabf/index.js#L1505-L1527
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by samarmohan — APPROVED** [review]
Thanks for your work!

**Comment by peterblazejewicz** [comment]
@TimWolla those changes are ok, but those are not tested, mind adding simple tests coverage?
you can just use those symbols and assert types using `// $ExpectType ...` expressions, thx!

**Comment by TimWolla** [comment]
> those changes are ok, but those are not tested, mind adding simple tests coverage?

@peterblazejewicz Can you please clarify for which change you expect to see additional tests? I've used the new streamEncode/streamDecode functions and tested the `.bytes` property for `streamDecode`. Should I test the `.bytes` property for all the 4 functions?

Can you please make a “Suggested Edit” with the tests you expect to see?

Also: Will making a change require me to wait for additional 19 days?

**Comment by peterblazejewicz** [comment]
please stay focused:
https://github.com/DefinitelyTyped/DefinitelyTyped#ive-submitted-a-pull-request-how-long-until-it-is-mergedf
I've just tried to help

**Comment by TimWolla** [comment]
> please stay focused:

My comment consisted of 2 paragraphs seeking clarification for the review comments in your previous comment and a third paragraph seeking clarification with regard to the review process after I make the requested adjustments to the PR. I am not quite sure how my comment is not focused on the issue at hand?

**Pull request merged**
