### PR TITLE
rdflib - Added class Query and improved signatures for methods in Formula and IndexedFormula

### PR DESCRIPTION
**Pull request by megoth**
This is an attempt to fix signatures for some methods that were incomplete, and adding some methods that were missing altogether for class Formula and IndexedFormula.

I've talked with TimBL on this, and in the future we want to automatically generate this based on doc generation in rdflib, but we cannot prioritize that work for now.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by megoth** [comment]
Added a couple of more fixes to classes Literal and Variable and their respective helper methods

**Comment by andrewbranch** [comment]
This looks like a fairly significant change. It all looks reasonable, but on the other hand, I have zero knowledge about this library. One or both of the following would be really helpful:

- A link to documentation to help reviewers verify these changes
- Someone else in the community with knowledge of the library to give a review (pinging @cenotelie again).

Also, for an apparently significant change, does this reflect a new version of rdflib? If so, make sure to update the version number in the header comment in index.d.ts.

**Comment by andrewbranch** [comment]
> Someone else in the community with knowledge of the library to give a review

E.g. perhaps @timbl, since you mentioned him in the PR description?

**Comment by megoth** [comment]
> This looks like a fairly significant change. It all looks reasonable, but on the other hand, I have zero knowledge about this library. One or both of the following would be really helpful:
> 
> * A link to documentation to help reviewers verify these changes

There is some documentation at http://linkeddata.github.io/rdflib.js/doc/, but it is not complete. There is a general problem about missing documentation for the library in general. We hope to get some time to improve that in the near future.

> * Someone else in the community with knowledge of the library to give a review (pinging @cenotelie again).

Yes, I should've pinged @timbl at once, I'll ping him on Gitter as well about this change and ask him to chip in (he's usually very busy though).

> 
> Also, for an apparently significant change, does this reflect a new version of rdflib? If so, make sure to update the version number in the header comment in index.d.ts.

No, this is more of a correction of signatures that were wrong or incomplete, and adding some more types that were missing. There is still more to add, which as mentioned we'll get more time to get to in the near future.

**Comment by sandersn** [comment]
Since rdflib's types are not used much, and we haven't heard from either maintainer, I'm going to assume the types are abandoned. This looks like an improvement to me, so I'm going to merge it.

@megoth if you want to be added as a maintainer, send a separate PR to add yourself to the list.

@timbl if you don't like the changes, please comment on this PR.

**Pull request merged**
