### PR TITLE
Update update-codeowners.js: switch to @definitelytyped

### LINKED ISSUE #45792: `Update CODEOWNERS` workflow is failing
Is something wrong with CI or publishing infrastructure? Yes.

The workflow is failing with `Error: Cannot find module 'types-publisher'`.

PR #45101 removed that package from the package.json.  @sandersn Should it be added back?

Additionally, why is this workflow running on everyone's repo? @orta Can that be managed?  I only know it is running because of the failures.

### PR DESCRIPTION
**Pull request by sandersn**
I forgot to update this when the rest of DT switched from types-publisher to @definitelytyped.

Fixes #45792

### CODE REVIEW

**Comment by sandersn** [comment]
Adding @orta back to sign off on the workflow change

**Comment by weswigham** [comment]
@orta @sandersn: ... ?

**Comment by sandersn** [comment]
Might as well!

**Comment by orta** [comment]
Missed this - looks good!

**Pull request merged**
