### PR TITLE
Type definitions added for promise-state-machine-es6

### PR DESCRIPTION
**Pull request by dmitry-zakablukov**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@dmitry-zakablukov it should support extensiblity:
https://github.com/faleij/promise-state-machine#inheritance
for this one needs to use proper class export, the const won't work IMO

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by dmitry-zakablukov** [comment]
@peterblazejewicz , good point. But classes and interfaces do not support computed fields. `events` argument of the constructor defines methods on a fsm: transition with a name `doSmth` defines a method `doSmth()`. Do you now how to describe such a constructor for a class using TypeScript? Or may be there is an example of such a class I can look at.

**Comment by peterblazejewicz** [comment]
@dmitry-zakablukov that's OK. For time being, the current code is OK (you've got ack already).
The problem here is with nice support for mixin-like constructs, I don't know the nice solution either.

This is not the best code, so it's just an exercise for me, it uses `EventEmitter` as base and supports extensibility and dynamic fields.

```ts
/// <reference types="node" />
import { EventEmitter } from 'events';

declare const PromiseStateMachine: {
    new <S, T extends PromiseStateMachine.Transitions<S>>(payload: {
        initial: S;
        events: {
            [name in keyof T]: { from: S | S[]; to: S };
        };
    }): {
        state: S;
        // tslint:disable:no-redundant-undefined
        // tslint:disable:ban-types
        // tslint:disable:array-type
        // tslint:disable:interface-over-type-literal
        addListener(event: string | symbol, listener: (...args: any[]) => void): any;
        addListener(event: string | symbol, listener: (...args: any[]) => void): any;
        on(event: string | symbol, listener: (...args: any[]) => void): any;
        on(event: string | symbol, listener: (...args: any[]) => void): any;
        once(event: string | symbol, listener: (...args: any[]) => void): any;
        once(event: string | symbol, listener: (...args: any[]) => void): any;
        removeListener(event: string | symbol, listener: (...args: any[]) => void): any;
        removeListener(event: string | symbol, listener: (...args: any[]) => void): any;
        off(event: string | symbol, listener: (...args: any[]) => void): any;
        off(event: string | symbol, listener: (...args: any[]) => void): any;
        removeAllListeners(event?: string | symbol | undefined): any;
        removeAllListeners(event?: string | symbol | undefined): any;
        setMaxListeners(n: number): any;
        setMaxListeners(n: number): any;
        getMaxListeners(): number;
        getMaxListeners(): number;
        listeners(event: string | symbol): Function[];
        listeners(event: string | symbol): Function[];
        rawListeners(event: string | symbol): Function[];
        rawListeners(event: string | symbol): Function[];
        emit(event: string | symbol, ...args: any[]): boolean;
        emit(event: string | symbol, ...args: any[]): boolean;
        listenerCount(event: string | symbol): number;
        listenerCount(event: string | symbol): number;
        prependListener(event: string | symbol, listener: (...args: any[]) => void): any;
        prependListener(event: string | symbol, listener: (...args: any[]) => void): any;
        prependOnceListener(event: string | symbol, listener: (...args: any[]) => void): any;
        prependOnceListener(event: string | symbol, listener: (...args: any[]) => void): any;
        eventNames(): (string | symbol)[];
        eventNames(): (string | symbol)[];
    } & {
        [name in keyof T]: () => Promise<void>;
    };
    prototype: EventEmitter;
};

declare namespace PromiseStateMachine {
    type Transitions<S> = {
        [key: string]: {
            from: S | S[];
            to: S;
        };
    };
    type Payload<S> = { initial: S; events: { [x: string]: { from: S | S[]; to: S } } };
}

export = PromiseStateMachine;
```

tests:

```ts
import PromiseStateMachine = require('promise-state-machine-es6');
import { Payload, Transitions } from 'promise-state-machine-es6';

enum State {
    stopped,
    running,
}

const transitions: Transitions<State> = {
    start: { from: State.stopped, to: State.running },
    stop: { from: [State.running], to: State.stopped },
};

const payload: Payload<State> = {
    initial: State.running,
    events: transitions,
};

class MyStateMachine extends PromiseStateMachine<State, Transitions<State>> {}

const fsm = new MyStateMachine(payload);

// $ExpectType State
fsm.state;

// $ExpectType () => Promise<void>
fsm.stop;

// $ExpectType Promise<void>
fsm.start();

fsm.on('start', (from, to) => {
    return Promise.resolve('Started');
});
```
thx!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by dmitry-zakablukov** [comment]
@peterblazejewicz , thank you for the code. I'll merge this pr and will try to open a new one with your suggested approach.

**Comment by dmitry-zakablukov** [comment]
Ready to merge

**Comment by peterblazejewicz** [comment]
> will try to open a new one with your suggested approach

You don't need to. Let's wait if someone has the use-case

**Pull request merged**
