### PR TITLE
Make SpawnSyncReturns.error optional for node

### PR DESCRIPTION
**Pull request by dcecile**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Review by SimonSchick — APPROVED** [review]

**Review by samuela — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Review by SimonSchick — APPROVED** [review]

**Comment by dcecile** [comment]
The [new build error](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/473414341#L4184) is from jsdom:

```
Error in jsdom
Error: Expected compilerOptions["baseUrl"] === "../"
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
    at <anonymous>
```

I'm not familiar enough with the test system to know what to try next.

Can anyone help out with fixing this?

**Comment by Flarna** [comment]
This seems unrelated.
Maybe an issue regarding splitting for 3.1 and pre 3.1 of jsdom?
@andy-ms do you have any hints in this?

**Comment by dcecile** [comment]
I've updated from master to reset @typescript-bot's timer, see if they issue was fixed by a different commit, and just to run the build again...

**Comment by dcecile** [comment]
(Still the [same](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/475553820#L4237) jsdom build error.)

**Comment by dcecile** [comment]
@Flarna Now that this PR has been automatically closed, what should I do next?

**Comment by Flarna** [comment]
Seems the repo is currently in a bad state and there is not much we can do except keeping the PR alive (by pushing changes) and ping repo maintainers (like I did it here and in the jsdom PR).

**Pull request closed without merging**
