### PR TITLE
Changed react-css-modules to default export

### PR DESCRIPTION
**Pull request by empz**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gajus/react-css-modules/blob/master/src/index.js#L50
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
The [source code](https://github.com/gajus/react-css-modules/blob/master/src/index.js) uses `export default`, but when I install it, the bottom of `node_modules/react-css-modules/dist/index.js` has this line:

```ts
module.exports = exports['default'];
```

(This is the fault of [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports).)

So in the NPM distribution, the module does *not* have a default export, is has `export =`.
It's possible that you are using a different distribution that uses `export default` instead, since the issue you linked to mentions getting an error at runtime. So the runtime behavior of the library depends on what version of the library you happen to have installed...

**Comment by emzero** [comment]
@andy-ms You're right on the `exports['default']`. But I'm using the 4.0.3 of `react-css-modules` installed via  normal npm and the current definition does not work and mine does. 
I'm not an expert on the universe of javascript module loaders, so I don't know in what case my definition would not work as expected.

**Comment by emzero** [comment]
Sorry, that PR doesn't work. Something changed while I reforked the repo and modified the definition.

Previous definition was this one:

```ts
// Type definitions for react-css-modules 3.7.9
// Project: https://github.com/gajus/react-css-modules
// Definitions by: Kostya Esmukov <https://github.com/KostyaEsmukov>, Tadas Dailyda <https://github.com/skirsdeda>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

interface TypeOptions {
    allowMultiple?: boolean;
    errorWhenNotFound?: boolean;
}

type StylesObject = any;

interface CSSModules {
    (defaultStyles: StylesObject, options?: TypeOptions): <C extends Function>(Component: C) => C;
    <C extends Function>(Component: C, defaultStyles: StylesObject, options?: TypeOptions): C;
}

declare module CSSModules {
    // Extend your component's Prop interface with this one to get access to `this.props.styles`
    //
    // interface MyComponentProps extends CSSModules.InjectedCSSModuleProps {}
    interface InjectedCSSModuleProps {
        styles?: StylesObject;
    }
}

declare let CSSModules: CSSModules;

export default CSSModules;

declare module 'react' {
    interface HTMLAttributes<T> {
        styleName?: string;
    }
}
```

Why does it changed? Why did the styleName attribute got removed?

**Comment by emzero** [comment]
I don't know what happened and I'm already lost.

One thing for sure is that I've just completely removed the `node_modules/@types/react-css-modules` from my project, did `npm install @types/react-css-modules` and got a **non-working** definition.

If you read the react-css-module [readme](https://github.com/gajus/react-css-modules) you can clearly see they do `import CSSModules from 'react-css-modules` meaning the package has a default export and that should be the way to import it. 
Not `import * as CSSModules from 'react-css-modules'` which the current definition forces you to and ends up with the actual function being inside a `default` property.

**Comment by andy-ms** [comment]
I ran:

```
npm install react-css-modules@4.0.3
node -p '[require("react-css-modules"), require("react-css-modules").default]'
```

And got: `[ [Function], undefined ]`. So with the node module loader, `import =` is correct. What setup are you using?

It looks like you made your pull request to a `master` branch pre-#13233, so that may explain the problems you're having with your checkout. We've changed the project structure to use `index.d.ts` instead of `react-css-modules.d.ts`. But the [current](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-css-modules/index.d.ts) file on this repository still has `styleName`.

The readme example may be because they assume it's being used with babel, which I believe does some fudging around when importing default exports.

**Comment by emzero** [comment]
Closing this PR in favour of [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13409) which actually works

**Comment by emzero** [comment]
I don't know much about the node module loader, but since this is a TypeScript definitions repository, the only one valid test to me is to actually use it in a typescript project and load it via the typescript module loader, which in this case is either:
```ts
// doesn't work, actual function ends up in a default property. 
// I've seen this behaviour before when trying to import some packages that doesn't use the ES6 export statement.
import * as CSSModules from 'react-css-modules' 

// works great for me and match the example in react-css-modules docs.
import CSSModules from 'react-css-modules' 
```

As I said, I'm lost, so do what you think is best. 
In the meantime I'll use a modified version of the defintion in my project since that's the only one that works.

**Comment by andy-ms** [comment]
The typescript module loader will resolve anything that you've declared to exist. So if you declare that `"react-css-modules"` has a default export, TypeScript will resolve this even if this is not accurate to the package itself. So the test is whether the code works when you run it, not whether it compiles.

**Pull request closed without merging**
