### PR TITLE
twine-sugarcube: Fixes regression in MacroContext.output

### PR DESCRIPTION
**Pull request by cyrusfirheir**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Source.](https://www.motoslave.net/sugarcube/2/docs/#macrocontext-api-prototype-property-output)

### CODE REVIEW

**Review by tmedwards — CHANGES_REQUESTED** [review]
The idea of the previous change, I think, was to better represent the value type by switching to a common ancestor interface—though it should have been `Node` in that case.

For myself, I'd prefer the value type to be more specific, rather than more general.  Something like the following would be best I think:

```js
DocumentFragment | HTMLElement
```

I'm unsure if there's already a named type for that in twine-sugarcube.  If so, it would likely be best to use that.  If not, then doing it locally is fine.

**Comment by cyrusfirheir** [comment]
@tmedwards 
> I'm unsure if there's already a named type for that in twine-sugarcube. If so, it would likely be best to use that. If not, then doing it locally is fine.

There doesn't seem to be a named type. Tests have this though:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/74a8e79b369fa53c91fad5d8bf92b212559fd888/types/twine-sugarcube/test/wiki.ts#L7

**Review by tmedwards — COMMENTED** [review]
What purpose does the jQuery change in the tests serve?

The updated code tends to be the style I use, but the original should work fine as-is.

**Review by tmedwards — APPROVED** [review]

**Comment by tmedwards** [comment]
Ready to merge

**Comment by cyrusfirheir** [comment]
> What purpose does the jQuery change in the tests serve?

`ParentNode` would fail as an argument to `.appendTo()`. It was why I found out about the change in the first place. So changed the test to account for that.

**Comment by tmedwards** [comment]
It's not using `ParentNode` anymore though, so….  😃 

No biggie regardless, I was just curious.

**Pull request merged**
