### PR TITLE
Add: type definitions for fontmin 0.9

### PR DESCRIPTION
**Pull request by AsPulse**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

In one place, I couldn't confirm the exact type of function and typed it as `Function`.
I followed the instructions in the README and took care of it.
> If for some reason some rule needs to be disabled, [disable it for that specific line](https://palantir.github.io/tslint/usage/rule-flags/#comment-flags-in-source-code:~:text=%2F%2F%20tslint%3Adisable%2Dnext%2Dline%3Arule1%20rule2%20rule3...%20%2D%20Disables%20the%20listed%20rules%20for%20the%20next%20line) using // tslint:disable-next-line:[ruleName] — not for the whole package, so that disabling can be reviewed. (There are some legacy lint configs that have additional contents, but these should not happen in new work.)
```ts
// tslint:disable-next-line ban-types
type fontminPlugin = Function | stream.Transform;
```
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## fontmin ([<kbd>unpkg</kbd>](https://unpkg.com/browse/fontmin@latest/))
was missing the following properties:
1. util
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d37cbd3a241ecb24fbe12b6b1a7bc8eed2f0b012
</p>

**Comment by AsPulse** [comment]
I fixed about:
> Config files to check:
[fontmin/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58659/files/d37cbd3a241ecb24fbe12b6b1a7bc8eed2f0b012#diff-4826f5f141f54ccc072d56c47e6e596901c49259437679fafe49089781535e6d): not [the expected form](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-tsconfigjson) (check: compilerOptions.esModuleInterop)

**Review by peterblazejewicz — COMMENTED** [review]
- this is not enforced, but highly recommended to follow common convention here for naming interfaces (CamelCase notation):
https://ts.dev/style/#naming-style
- the `Fontmin` should probably extends event emitter, in case someone was to use this as such:
https://github.com/ecomfe/fontmin/blob/master/index.js#L34

**Comment by AsPulse** [comment]
@peterblazejewicz 
Thanks for reviewing!

> * this is not enforced, but highly recommended to follow common convention here for naming interfaces (CamelCase notation):
>   https://ts.dev/style/#naming-style

I have checked the link!
Am I right in my approach of capitalizing the first? ( at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58659/commits/bcfb9d883b3613ee3ca322eec4f8309dd736fc01 ) 

> * the `Fontmin` should probably extends event emitter, in case someone was to use this as such:
>   https://github.com/ecomfe/fontmin/blob/master/index.js#L34

Sorry, I overlooked that. I fixed it! ( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58659/commits/7f75387d178d828aecc65f856659644bd646b716 )

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@AsPulse thx!

**Comment by AsPulse** [comment]
Ready to merge

**Pull request merged**
