### PR TITLE
Deprecate @types/material-ui

### PR DESCRIPTION
**Pull request by danvk**
@material-ui/core has [bundled types][1] since at least version 1.0.0, which came out in [May 2018][2]. It's easy to add this accidentally if you're used to looking for `foo` + `@types/foo` pairs, and it can cause problems. Unless I'm missing something, there's no reason for these definitions to exist, though they do seem to be actively developed.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

[1]: https://cdn.jsdelivr.net/npm/@material-ui/core@1.0.0/index.d.ts
[2]: https://material-ui.com/blog/material-ui-v1-is-out/

### CODE REVIEW

**Comment by danvk** [comment]
The test failures are because `material-ui-pagination` and `react-material-ui-form-validator` depend on this package.

- `material-ui-pagination` only depends on `@types/material-ui` [for its tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/material-ui-pagination/material-ui-pagination-tests.tsx)
- `react-material-ui-form-validator` [depends on `@types/material-ui`] (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-material-ui-form-validator/index.d.ts) in its implementation as well.

Updating the tests for the first one seems easy enough. I'm not sure what the usual procedure is for the second. I'll hold off on doing anything more until a project owner indicates whether there's a reason to keep these types that I haven't thought of.

**Comment by ngbrown** [comment]
I still use the older version of `material-ui`, thus maintaining these definitions.  I'm fine with a version 1.0 package being published reporting that it's out of date, but move the existing definitions to a legacy versioned sub-directory instead of deleting them.

**Review by ngbrown — CHANGES_REQUESTED** [review]
I still use the older version of `material-ui`, thus maintaining these definitions.  I'm fine with a version 1.0 package being published reporting that it's out of date, but move the existing definitions to a legacy versioned sub-directory instead of deleting them.

**Comment by danvk** [comment]
@ngbrown OK. Do you happen to know of another library following that pattern that I can use as a template?

**Comment by ngbrown** [comment]
@danvk, `react` had/has a `v15` directory with the current directory being v16.  I remember that at one time seemed to be a lot more packages that had multiple back versions.

I don't know of a specific instance where a package is both in `notNeededPackages.json` and currently maintained in definitely typed. However, the readme does specify how to move declarations [into a versioned sub-directory](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package).

The obsolete `material-ui` package still has 131,000 weekly downloads, about a tenth of the replacement `@material-ui/core`. So it's obviously waning, but still being used.

I'd be curious to know what the policy is for maintaining older, but still used definitions such as this one.

**Comment by samwalshnz** [comment]
The organisation I'm working at still relies on these typings, so, like @ngbrown, I'd really like to see the `@types/material-ui` typings remain. If we can resolve this with the versioned sub-directory instead of being removed entirely, that would be much appreciated.

I'm guessing there's many other organisations (and npm packages) still relying on `@types/material-ui`, so we'd need to be careful not to introduce a breaking change.

Re @danvk's comment:
> It's easy to add this accidentally if you're used to looking for foo + @types/foo pairs, and it can cause problems

I understand that this could be a common mistake, however _technically speaking_, the `@types/*` equivalent for `@material-ui/core` would be `@types/material-ui__core` (as per the [README guidelines](https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-scoped-packages)). So there's not really a conflict in package naming.  But I hear where you're coming from, that from a DX point of view, it's still confusing...

I'm sure if people make that mistake, they'll eventually realise `@types/material-ui` isn't required and that `@material-ui/core` already has types. It's probably better preventing packages and organisations from compiling, than to prevent the odd developer accidentally installing the wrong package 🤷‍♂️

If there was a way detect if the project _doesn't_ have `material-ui` installed and warn the user that `@types/material-ui` is for `material-ui`, not `@material-ui/core`, then that could solve the accidental install developer experience issue, but I'm guessing that kind of functionality is probably not possible out-of-the-box in DefinitelyTyped and/or too-hard-basket 😅

**Pull request closed without merging**
