### PR TITLE
redux-saga-routines@3.0

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by StanislavVoronov** [comment]
I have an error when createRoutine 
const fetchMarket = createRoutine(NAMESPACE)
and when I write fetchMarket.request(), it requires for parameters, because of 
export type Routine<
    TTriggerActionCreator = ActionCreator
> = TTriggerActionCreator & {
    TRIGGER: string;
    REQUEST: string;
    SUCCESS: string;
    FAILURE: string;
    FULFILL: string;
} & {
    trigger: TTriggerActionCreator;
    request: **ActionCreator**, but it should be TTriggerActionCreator;
    success: ActionCreator;
    failure: ActionCreator;
    fulfill: ActionCreator;
};

**Comment by alexey-pelykh** [comment]
@StanislavVoronov addressed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34760, yet it should not be `TTriggerActionCreator`, `ActionCreator` needs to be less strict

**Comment by StanislavVoronov** [comment]
@alexey-pelykh How to resolve this situation? Install version two?

**Comment by alexey-pelykh** [comment]
@StanislavVoronov until fix is merged in day or two, you may just apply the change manually

**Comment by StanislavVoronov** [comment]
@alexey-pelykh thanks

**Pull request merged**
