### PR TITLE
[tabulator-tables] Migrate full ESM

### PR DESCRIPTION
**Pull request by Jojoshua**
When Tabulator moved to v5 ESM bundling it caused some issues that were never resolved in our typescript definitions related to naming & type accessibility. Literally all the interfaces & types were not accessible anymore, only the class!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62310 was the initial attempt to resolve this but it only accounted for the Options interface and was more of a workaround than a fix. This PR properly allows users to import any of the interfaces or types they may need now.

In addition, this eliminates the typescript namespace which was confusing and favors modules which is recommended anyway https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html.

Publishing as 5.31 (since DefinitelyTyped wasn't allowing a patch version i.e (5.3.1))

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (http://tabulator.info/docs/5.0/release#install)

### CODE REVIEW

**Review by mike-lischke — COMMENTED** [review]
That's a patch which is pretty hard to review. The diff view shows only a number of large blocks either being removed or added. Not sure how to cope with that...

**Comment by Jojoshua** [comment]
> That's a patch which is pretty hard to review. The diff view shows only a number of large blocks either being removed or added. Not sure how to cope with that...

Sorry about that @mike-lischke. I don't know why the GitHub diff went wacky. This is how I ended up doing the comparison which you can try as well.

1. Go to https://www.diffchecker.com/diff
2. Copy the previous version text into original https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/tabulator-tables/index.d.ts
3. Copy this version text into changed text https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a1baeb895b790486fb62e5b2726a13dabbf9a28d/types/tabulator-tables/index.d.ts
4. On the top right Tools section, and check Trim Whitespace
image


What you should find is basically 2 things:

- The `declare namespace Tabulator` wrapper was removed
- All interfaces & types were prepended with `export`

The remaining issue is how to deal with npm-naming with DefinitelyTyped. I don't want to push this as a "5.4" version because I want it to match Tabulator version and I can't make it "5.3.1" because DefinietlyTyped doesn't allow a "patch" version.  The build errors said you can turn off npm-naming in tslint.json but it's not working...

**Comment by mike-lischke** [comment]
Oh yes, much better. Thanks for the tip @Jojoshua!

**Comment by Jojoshua** [comment]
> Oh yes, much better. Thanks for the tip @Jojoshua! I'll review when you figured out a solution for the build problem (no idea what to do with the version number, DT should definitely support patch version numbers!).

Thanks for your patience @mike-lischke. Finally got the build to succeed.

**Review by mike-lischke — APPROVED** [review]

**Comment by Jojoshua** [comment]
Ready to merge

**Pull request merged**
