### PR TITLE
Add Type definitions for Web NFC

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test w3c-web-nfc`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
@takefumi-yoshii may be able to review this PR.

**Comment by takefumi-yoshii** [comment]
@beaufortfrancois 
This definition is a correct representation of [WebIDL](https://w3c.github.io/web-nfc/#actual-idl-index) and has been validated by some developers. I agree with this PR.

**Review by amcasey — APPROVED** [review]

**Comment by beaufortfrancois** [comment]
Ready to merge

**Comment by beaufortfrancois** [comment]
@amcasey https://www.npmjs.com/package/@types/w3c-web-nfc is live but npm asks me to log in. Any idea why?

**Comment by amcasey** [comment]
@beaufortfrancois Are you still seeing that?  It seems to work for me.  If you are, is it happening when you access the website or when you `npm install`?

**Comment by beaufortfrancois** [comment]
It works great now. I'm not sure what happened earlier

**Pull request merged**
