### PR TITLE
Ember ActionHandlerMixin for send and action

### PR DESCRIPTION
**Pull request by flcdrg**
Define ActionHandlerMixin class (which mirrors Ember's ActionHandler mixin class) and apply this appropriately to match Ember's usage.

### CODE REVIEW

**Comment by vvakame** [comment]
@jedmao could you review this PR?

**Comment by jedmao** [comment]
:+1:

**Comment by flcdrg** [comment]
@jedmao Thanks. 

I've also got some questions around the ember.d.ts file (I'm relatively new to TypeScript). Can I contact you in some convenient way?

**Comment by jedmao** [comment]
My username at outlook dot com. Go for it.

**Comment by vvakame** [comment]
@flcdrg thanks mate!
@jedmao thanks!

**Pull request merged**
