### PR TITLE
replace internal module to namespace

### PR DESCRIPTION
**Pull request by vvakame**
@DefinitelyTyped/contributors

### CODE REVIEW

**Comment by basarat** [comment]
Thanks! 

Since you have everyone here I wanted to share a big change coming : https://github.com/Microsoft/TypeScript/issues/7125#issue-134444635 That is going to allow us to write definitions that do not pollute the global namespace *unless the user explicitly* adds a `library` reference. So we get to write a single definition for both `external module` and `global` users :rose:

**Comment by stephenlautier** [comment]
:+1:

**Comment by mkp05** [comment]
:+1:

**Comment by abreits** [comment]
:+1:

**Comment by AkosLukacs** [comment]
:+1:

**Comment by vvakame** [comment]
good news!

**Comment by vvakame** [comment]
thanks all!

**Comment by horiuchi** [comment]
:+1:

**Comment by Justin-Credible** [comment]
:+1:

**Comment by RReverser** [comment]
People, there are now proper Github reactions, please use them instead of +1 / :+1: comments. Thanks! :)

**Comment by cyrilschumacher** [comment]
:+1:

**Pull request merged**
