### PR TITLE
Updated type definitions to yFiles for HTML 2.0.1.3

### PR DESCRIPTION
**Pull request by martin-y**
[x] Use a meaningful title for the pull request. Include the name of the package modified.

[?] Test the change in your own code. (Compile and run.)
strictFunctionTypes": true compiler option is not recognized by compiler (2.6.rc), but it was introduced just with the last commit. Should we remove this? This is the error that we get here.
tsconfig.json(11,9): error TS5023: Unknown compiler option 'strictFunctionTypes'.

[x ] Follow the advice from the [readme]- [ ] Avoid [common mistakes]
[ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: http://www.yworks.com/products/yfiles-for-html/version-2.0.1.3

[x ] Increase the version number in the header if appropriate.

For the previous versions, we have put a 4 digit version name here. This has probably lead to some confusion - especially the version history in npm is not as we wish. Thus we now provide a mapping of our 4-digit version number to a 3-digit semver number. Please - before accepting this pull request - could you confirm that the 3-digit semver as provided here (20.1.3) will be the version number the package will be available from npm/@types.

### CODE REVIEW

**Comment by andy-ms** [comment]
@martin-y Test with `typescript@next`.
We should publish this as version `20.1.0`. The third digit will be completely ignored; the reason is that we must change the patch version every time the package is published, regardless of whether the header changes. We have a lint rule notifying about this but linting hasn't yet been enabled for this package. (You would need to add a `tsconfig.json` containing `{ "extends": "dtslint/dt.json" }`.)

**Comment by martin-y** [comment]
@andy-ms Thanks for the information. I guess there is no better way of keeping the versions aligned with the 4 digit versions string of the yfiles library? I've been thinking about a good map from which it is possible to derive the library version number from the npm types package version number and vice versa. 

Thanks for the hint on linting - I've been shying away from adding this since the typings are generated from source code and proper linting would probably involve lots of changes. I'll see if we can improve this for the next version.

**Comment by andy-ms** [comment]
Assuming the library doesn't make breaking changes in its low-order digits (`C.D` in `A.B.C.D`), it should be fine to just extract `A.B` and use that as the types version?
If you collapse `2.0` to `20` what will happen when you hit version `2.10`?

**Comment by martin-y** [comment]
@andy-ms 
I agree - keeping the higher order digits will be probably the least confusing and has the advantage as you say. 

Collapsing the higher order digit would have been our choice if all three digits were available in the types version number - one could read the library version number from the types version string. We thought collapsing the higher order digits (A.B) rather than the lower order digits (C.D) because bugfixes (D) are more likely to hit the 10 than the minor version number (B) in our case. 

But since only two digits are available anyway, i agree to do as you say and keep (A.B).

In npm there are already versions starting with 2.0... - so its good to continue there. "2.0.2" is the latest on npm. If I've understood correctly I can change the version in the header to "2.0.13" and the next npm version will be "2.0.3" ?

Thanks for your help!

**Comment by andy-ms** [comment]
Yes, the third digit is completely ignored.

**Comment by martin-y** [comment]
I've changed the version in the header to 2.0.13.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
