### PR TITLE
@types/sparkpost definitions update

### PR DESCRIPTION
**Pull request by bondz**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developers.sparkpost.com>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

Repo: https://github.com/SparkPost/node-sparkpost

Review request?: @aydrian @geoffreak

### CODE REVIEW

**Comment by geoffreak** [comment]
LGTM 👍

**Comment by paulvanbrenk** [comment]
Thanks for the contribution.
Instead of moving the v1 files to a new folder, can you rename them to `sparkpost-v1.3.d.ts` as discussed in the [FAQ
](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#what-do-i-do-about-older-versions-of-typings).

**Comment by bondz** [comment]
Yeah, I guess I was confused reading the [update to a new major version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version) section of the FAQ.

**Comment by paulvanbrenk** [comment]
Oh great conflicting information in the FAQ. What you did looks good based on that.

**Pull request merged**
