### PR TITLE
[react-native-vector-icons] Exposed Icon methods

### PR DESCRIPTION
**Pull request by SudoPlz**
- Exposes methods implemented in: https://github.com/oblador/react-native-vector-icons/pull/762

Please fill in this template.

- ✅  Use a meaningful title for the pull request. Include the name of the package modified.
- ✅ Test the change in your own code. (Compile and run.)
- ✅ Add or edit tests to reflect the change. (Run with `npm test`.)
- ✅ Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- ✅ Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- ✅ Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ✅ Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/oblador/react-native-vector-icons/pull/762>>

### CODE REVIEW

**Review by kyler-hyuna — CHANGES_REQUESTED** [review]
--

**Review by iRoachie — CHANGES_REQUESTED** [review]
@SudoPlz I can't merge this until that PRs been accepted. Just ping me and let me know. You would also need to bump the version when it's released

**Comment by SudoPlz** [comment]
Ok, I'll ping you when the PR get's merged @iRoachie 

Thanks for taking a look

**Comment by SudoPlz** [comment]
Ok, the PR is merged @iRoachie can you merge now?

**Comment by kyler-hyuna** [comment]
Waiting until he cuts a version.

**Comment by iRoachie** [comment]
Waiting until he cuts a version.

**Comment by SudoPlz** [comment]
pff..

**Comment by iRoachie** [comment]
Lol i'll update just so the bot doesn't close

**Review by iRoachie — APPROVED** [review]

**Comment by SudoPlz** [comment]
Aah, cool, thanks @iRoachie

**Review by kyler-hyuna — APPROVED** [review]

**Comment by iRoachie** [comment]
Don't merge: pending version release of react-native-vector-icons

**Review by iRoachie — CHANGES_REQUESTED** [review]
Just make the change here to 5.0  @SudoPlz https://github.com/SudoPlz/DefinitelyTyped/blob/ac3875fd5f6b7d2ef673811c4d47e4ae7df5edcc/types/react-native-vector-icons/index.d.ts#L1

**Pull request closed without merging**
