### PR TITLE
[@types/oracledb] Fix converter type

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://node-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#using-fetch-type-handlers-with-converters>

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/oracledb/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f1a818d95ebea0d3b10236f61a93d344c2803ebb
</p>

**Comment by sla100** [comment]
The converter is allowed to return any type, including mixed types. Ex.
```js
/*
 * Converter which return null as zero and large integers as bigint
 */
const converter = (value: string | null) => {
  if (value === null) {
    return 0; // default
  }
  const i = Number(value);
  if (Number.isSafeInteger( i ) ){
    return i;
  }
  return BigInt( value );
};
```

**Comment by dannyb648** [comment]
If youre happy for this to go in 6.3.x lets do it

**Review by danbeglin — APPROVED** [review]

**Review by gabritto — APPROVED** [review]

**Comment by sla100** [comment]
Ready to merge

**Pull request merged**
