### PR TITLE
chore(node): remove EOL versions

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

I am going to ignore the PR template for once.
I previously said that maintaining types for node versions that are EOL seems unreasonable as it just add more and more churn with each new version.
I don't suggest we un-publish the packages, but I suggest we no longer update them and mark them as deprecated to motivate people to update.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Paging @amcasey @rbuckton as I am not sure if the types publisher will like this kind of removal, and to get some consensus on whether this change is welcome or not.

**Comment by Flarna** [comment]
EOL of Node 6 is April 2019 so I think we should keep this one.

CI is not executed for removal so hard to tell if someone is still referring to these versions.

**Comment by SimonSchick** [comment]
@Flarna I did a regex search for `node/` in all `tsconfig` files there are, found nothing.
Also restored v6, although I don't think there will be many updates coming for it 😛

**Review by Flarna — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by sandersn — CHANGES_REQUESTED** [review]
I appreciate the problem of churn. I don't understand why maintainers have to keep updating old versions, though.

Seems like it would be easier to keep but not update the old versions, except in some emergency -- probably by the very people who would still be stuck on those node versions.

**Comment by SimonSchick** [comment]
@sandersn The mere presence of the typings makes maintainers update them, I personally don't really bother touching old typings, I only ever update latest + LTS.

As for `emergency` updates, I think the consumers would be better off to augment existing typings/vendor typings into their projects at this point rather than doing updates for node versions that are EOL (especially given how long updates to the node typings take at this point).

In case we want to keep the typings, we would still need to come up with a policy that tells people not to touch those.

**Comment by SimonSchick** [comment]
@sandersn you think it would be reasonable to ditch `0.12` through `v4` instead?

**Comment by sandersn** [comment]
I discussed it with the rest of the team. Ditching 0.12 through 4 sound pretty reasonable to us.

**Comment by Flarna** [comment]
By the way, EOL of Node.JS 7 was ~1 year earlier then Node.JS 4 (see https://github.com/nodejs/Release).

I think we should not create subfolders for non LTS (uneven) Node.JS versions at all in future as the difference is usually very small (if existing at all) and most people stay on LTS versions anyway.

**Comment by SimonSchick** [comment]
@flarna I disagree, changes between LTS versions tend to be substantial and are very hard to keep track off, without non LTS versions keeping typings up to take will be extremely tedious.

**Comment by SimonSchick** [comment]
@sandersn @amcasey can we get this in, I have a few I have a few more things in the pipeline 😄

**Pull request closed without merging**
