### PR TITLE
Definitions for Segment's analytics.js library

### PR DESCRIPTION
**Pull request by fongandrew**
Definitions for https://segment.com/docs/libraries/analytics.js/

### CODE REVIEW

**Comment by vvakame** [comment]
*segment-analytics/segment-analytics.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/segment-analytics
  * http://bower.io/search/?q=segment-analytics
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (segment-analytics/segment-analytics-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@fongandrew thanks mate!

**Comment by otobrglez** [comment]
@fongandrew && @vvakame Question. Why does this definition depend on `JQuery` type? And how can we decouple / remove this dependency? Is someone perhaps doesn't want to drag whole jQuery into its codebase? Cheers!

**Comment by fongandrew** [comment]
@otobrglez It depends on the `JQuery` type because the documentation for this library says some functions accept JQuery objects as arguments (https://segment.com/docs/sources/website/analytics.js/). You don't need to include jQuery itself in your own codebase for this to work. It's just the definition.

That said, I do see the problem because maybe you want to use some other library that modifies the `$` variable.

With respect to de-coupling the two, we could try making analytics.js a non-global definition, so that Typings could bring in a namespaced version of the jQuery definition that doesn't pollute the global scope (although the jQuery defintion itself is global, so not sure if that'll work). Also, I'm not sure if DefinitelyTyped is the right place for modular definitions -- Typings sort of encourages folks to just stick these definitions in their own standalone repo.

A simpler alternative would just be to split the definition into jQuery and no jQuery variants.

**Comment by IceCreamYou** [comment]
@fongandrew The problem with including the jQuery type definitions in a project that doesn't use jQuery is that TypeScript will then happily compile invalid code that uses jQuery types, and IDEs will auto-suggest jQuery variables and methods.

I think this is easily resolvable using the little-known fact that declaring an interface multiple times is allowed and actually _merges the declarations_ (at least in TS 1.8 - I'm not sure about other versions). For proof, try this:

```sh
$ echo "declare interface A { b: () => void; }" > a.d.ts
$ echo "declare interface A { c: () => void; }" > b.d.ts
$ echo "let z: A; console.log(z.b, z.c);" > c.ts
$ tsc a.d.ts b.d.ts c.ts
```

This compiles successfully (the output is `var z; console.log(z.b, z.c);`).

Using this approach, the segment-analytics typings could just re-declare the jQuery interface as an empty interface. It wouldn't cause errors or prevent the real jQuery typings from working, and it would remove the requirement to have jQuery typings installed for the Segment typings to work, without maintaining two different versions of the Segment typings.

**Comment by fongandrew** [comment]
Thanks @IceCreamYou. Pending PR does what you suggest.

**Pull request merged**
