### PR TITLE
@types/react: add aria attribute to HTMLAttributes

### PR DESCRIPTION
**Pull request by ESWAT**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react/blame/d7157651f7b72d9888c0123e191f9b88cd8f41e9/docs/docs/reference-dom-elements.md#L101>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ESWAT** [comment]
Waiting for #18071 to be merged since `react-router-redux` tests were already breaking on master.

**Review by vsiao — CHANGES_REQUESTED** [review]
I'm not aware of an `aria` attribute—just `aria-` prefixed attributes.

**Review by Jessidhia — CHANGES_REQUESTED** [review]
There are many `aria-` attributes, but not an `aria` attribute.

https://www.w3.org/TR/wai-aria-1.1/#state_prop_def

It could be useful to have definitions for them (e.g. `'aria-haspopup'?: boolean|'menu'|'listbox'|'tree'|'grid'|'dialog'`), but currently the typescript compiler will accept any unknown attribute that has a `-` in it without raising errors, which includes all `aria` attributes.

**Comment by ESWAT** [comment]
Right, I took the cue from how `data-` attributes already exist here, but only `data` can be found in the actual definition, and just reused the same method.

**Comment by vsiao** [comment]
`data` is an [actual attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object#attr-data); `aria` is not.

**Comment by andy-ms** [comment]
Based on the comments it looks like this change should not be done.

**Pull request closed without merging**
