### PR TITLE
[tar-stream] Extract options

### PR DESCRIPTION
**Pull request by kevin-lindsay-1**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mafintosh/tar-stream/pull/131
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGMT!
@kevin-lindsay-1 thx!

**Comment by kevin-lindsay-1** [comment]
@peterblazejewicz np!

**Comment by elibarzilay** [comment]
I made it possible to self-merge, but this looks like a case of "why not add a test for this?", so maybe add one...?

**Comment by kevin-lindsay-1** [comment]
@elibarzilay I already wrote tests for this in the actual lib. Not really sure what I'd be testing in here, since this is just type definitions, not the actual library.

**Comment by kevin-lindsay-1** [comment]
Ready to merge

**Pull request merged**
