### PR TITLE
update(yup): Add missing locale types

### PR DESCRIPTION
**Pull request by lukaselmer**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup/blob/master/src/locale.js#L23
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by mauricedb — APPROVED** [review]
Looks good to me. Thanks

**Comment by djpremier** [comment]
Hi @lukaselmer, the object key is also missing.

https://github.com/jquense/yup/blob/master/src/object.js#L281
`
"object": {
    "noUnknown": "{{path}} field has unspecified keys: {{unknown}}"
},
`

**Comment by lukaselmer** [comment]
> Hi @lukaselmer, the unknown parameter in object key is also missing.
> 
> https://github.com/jquense/yup/blob/master/src/object.js#L297
> `"object": { "noUnknown": "{{path, unknown}} field has unspecified keys: {{unknown}}" },`

@djpremier Good catch, I also added the `unknown` parameter.

**Review by amcasey — APPROVED** [review]

**Comment by lukaselmer** [comment]
Ready to merge

**Pull request merged**
