### PR TITLE
feat(aws-lambda): use interfaces for proxy event properties to allow merging

### PR DESCRIPTION
**Pull request by G-Rath**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

----

This lets you do declaration merging, like so:

```
declare module 'aws-lambda/trigger/api-gateway-proxy' {
  export interface APIGatewayProxyEventHeaders {
    'X-GitHub-Event': WebhookEvents;
  }
}
```

I've applied it to all four properties that are in this situation.

### CODE REVIEW

**Review by SachinShekhar — CHANGES_REQUESTED** [review]
Please, add tests.

**Comment by G-Rath** [comment]
@SachinShekhar what tests did you have in mind? I didn't think you could test declaration merging here as this is where the base types are, so any test for merging would throw off other tests, or just not work all together since the types are local.

**Review by G-Rath — COMMENTED** [review]
@typescript-bot I can't dismiss reviews :(

**Review by darbio — APPROVED** [review]

**Comment by SachinShekhar** [comment]
@G-Rath I didn't ask to prove declaration merging. Add tests to complete coverage.

**Review by darbio — APPROVED** [review]

**Comment by G-Rath** [comment]
Ready to merge

**Comment by darbio** [comment]
Ready to merge

**Comment by G-Rath** [comment]
Thinking about it, we should probably mark the types as `| undefined` instead of just `string` - keys that will exist can be marked as such using declaration merging, so having them `string | undefined` like `process.env` would be safer.

**Pull request merged**
