### PR TITLE
Update Socket.io type to v2

### PR DESCRIPTION
**Pull request by crutchcorn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

The linter fails with the following errors; however I lack the expertice to solve the issues. Help requested!
```
Error: C:/Users/crutchcorn/git/Rucksack/defFiles/DefinitelyTyped/types/socket.io/index.d.ts:18:5
ERROR: 18:5    expect  TypeScript@next compile error:
Exports and export assignments are not permitted in module augmentations.
ERROR: 386:15  expect  TypeScript@next compile error:
Interface 'Namespace' incorrectly extends interface 'EventEmitter'.
  Types of property 'emit' are incompatible.
    Type '(ev?: string) => Namespace' is not assignable to type '(event: string | symbol, ...args: any[]) => boolean'.
      Type 'Namespace' is not assignable to type 'boolean'.

C:/Users/crutchcorn/git/Rucksack/defFiles/DefinitelyTyped/types/socket.io/socket.io-tests.ts:93:13
ERROR: 93:13   expect  TypeScript@next compile error:
Expected 0-1 arguments, but got 2.

    at C:\Users\crutchcorn\git\Rucksack\defFiles\DefinitelyTyped\node_modules\dtslint\bin\index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\crutchcorn\git\Rucksack\defFiles\DefinitelyTyped\node_modules\dtslint\bin\index.js:5:58)
    at <anonymous>
```

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/socketio/socket.io/releases>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
Hello @crutchcorn, sorry for the delay in responding.
Here's some advice I have regarding the two errors you're seeing for index.d.ts.

ERROR: 18:5
I don't think this file is structured in the correct way. You can get the same API with a cleaner approach by following the template at http://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html . I know that this is somewhat of a big revision, but I think it will be preferable.

Following this template, I think it will look something like this:
```
export SocketIO;

declare function SocketIO(): SocketIO.Server;

declare function SocketIO(srv: any, opts?: SocketIO.ServerOptions): SocketIO.Server;
...
```
and so on for the constructors, followed by:
```
declare namespace SocketIO {
  export interface Server {
    ...
  }
  ...
}
```

and so on.

ERROR: 386:15
Currently, you have `Namespace extends NodeJS.EventEmitter`. However, the `emit()` method on `EventEmitter` returns a boolean, whereas the `emit()` method on `Namespace` does not. Your two options are either to remove the extends clause or to properly match the signature from `NodeJS.EventEmitter`.

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
See prior comment.

**Comment by BorntraegerMarc** [comment]
@crutchcorn is there any way I can help you out?

**Comment by crutchcorn** [comment]
I think I've got a handle on things @BorntraegerMarc . I simply got caught up with other things (actually moved this week, among other things). I'll be trying to fix up the PR now

**Comment by crutchcorn** [comment]
Actually, I'm now realizing that I'm not entirely sure how to recreate `io().listen()` with the new template... :thinking: If someone could assist me with that, I'd greatly appreciate it

**Comment by BorntraegerMarc** [comment]
Not sure if I understand what you mean with: "new template" @crutchcorn . Are you referring to the new way in socket.io how servers are listening to ports?

Regarding the extend idea: one way how to solve it would be to keep for example a `BaseServer` interface. But without exporting it. Then in our `v1` + `v2` folder we just export the real `Server` interface which extends `BaseServer`

Have fun in your new flat 🙂

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by BorntraegerMarc** [comment]
@uniqueiniquity it is indeed a big revision what you suggested in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23776#issuecomment-368598484 and in my opinion not really part of the issue, which this PR is solving.
How about we concentrate on the core issue (to upgrade typings to v2.0) and make a new issue / PR with the cleaner approach?
this way we can still benefit from the new typings but we keep in mind that the code needs to be refactored.

I'm veeeeery busy at the moment but I can see myself tackling the refactoring of the code in the next 1-3 months

**Comment by uniqueiniquity** [comment]
Sorry for taking so long to respond.
I think that is a feasible approach.
Please open a new PR that focuses on upgrading the typings to v2.0 so that it is synced with the `master` branch and reference this issue so we have context for the new PR.
Thank you!

**Pull request closed without merging**
