### PR TITLE
blessed: Fixes search signature and giant linting rabbit hole

### PR DESCRIPTION
**Pull request by skellock**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/chjj/blessed/blob/eab243fc7ad27f1d2932db6134f7382825ee3488/lib/widgets/list.js#L184
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

----

It started out quite innocently.  I wanted to change the `search: () => void;` to `search?(err: any, value?: string): void;` because it wasn't typed correctly.

Then i added on one fancy `tslint.json` things and boom.  My entire Friday night was shot.

Just a few notes on this... I ended up ignoring a few `tslint` errors because I didn't want to break backwards compatibility.

First time contributor here, so if something is wrong or not up to snuff here, lemme know.  I don't mind changing stuff.

### CODE REVIEW

**Comment by BasixKOR** [comment]
+1

**Comment by skellock** [comment]
Dearest @typescript-bot, I have rebased against master to pick up the new `tslint.json`. Hope you're having a great weekend!

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by skellock** [comment]
Thank you kindly for the merge.

**Pull request merged**
