### PR TITLE
[update-notifier] Make options optional for v1, add v2 types

### PR DESCRIPTION
**Pull request by imhoffd**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yeoman/update-notifier#api
- [x] ~~Increase the version number in the header if appropriate.~~
- [x] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by plantain-00** [comment]
Since you are updating the package from v1 to v2, you can follow the advice here: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Review by plantain-00 — CHANGES_REQUESTED** [review]
Since you are updating the package from v1 to v2, you can follow the advice here: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by dwieeb** [comment]
@plantain-00 I believe I've addressed your concerns.

It is pretty confusing to refer to the old major version as both "current version" and "v2". Additionally, the example is outdated and the links link to the wrong files.

**Comment by weswigham** [comment]
:+1: You've got it.

**Pull request merged**
