### PR TITLE
Allow extra properties in when calling `createTag`.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Relates to upcoming changes in https://github.com/microsoft/TypeScript/pull/40311.

See  https://github.com/microsoft/TypeScript/pull/40311#issuecomment-685340412 for details on potential breakage.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## select2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/select2@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'select2'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a9d78745622e01141f420d225281f74cb0f9c93e
</p>

**Comment by elibarzilay** [comment]
@borisyankov @denisname — re-ping

**Comment by denisname** [comment]
@elibarzilay I don't use select2 anymore and have unfortunately no time to check this for the moment.

**Review by amcasey — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Ready to merge

**Pull request merged**
