### PR TITLE
quill: add scroll and getBounds definition

### LINKED ISSUE #21899: Missing content from the quill type spec
Making a tracking issue as I have my hands in the guts of quill right now, but I want to put some content here to keep track of what I need to put in the typing.

* The `BoundsStatic` returned by `getBounds` has a `bottom` and `right` atttribute. They are top + height and left + width respectively, but they're on the returned value.
* The quill object has a `scroll` element that can be addressed to ask questions about the location of a particular range in its layout.

These may well be private implementation details, in which case let me know: I won't write typings for them. I intend to submit a PR for these (and any other things I find, which I'll add as comments here) nex week.

  - Authors: @sumitkm @guillaume-ro-fr 

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by 43081j**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [here](https://github.com/quilljs/quill/blob/07d9597b156ff880e724843f65be3b80d1273159/core/quill.js#L77)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes #21899.

* Added missing properties to the bounds interface.
* Added `scroll` (a parchment blot)

Is this package.json ok? we need `parchment` for the `Blot` definition.

### CODE REVIEW

**Comment by 43081j** [comment]
did not realise there's a whitelist. it would be a shame if we can't just use `Blot` here... should i pretty much copy the interface into here or PR to the whitelist?

**Comment by sumitkm** [comment]
The PR is good. How do we get Parchment into the white list ? Looks like we need another pull request to ```types-publisher```.  @43081j do you want to have a go at it ? Or I can try...

**Comment by 43081j** [comment]
its fine, i went ahead and did a quick PR for it.

will update once that gets merged.

**Comment by sumitkm** [comment]
@43081j I think they may-not accept the PR. Looks like this one is a little complicated. Parchment's definitions though installed with the library from NPM are not registered under @types namespace in npm. So we can't install parchment definitions as ```npm install @types/parchment``` This is why you need the parchment module to be referenced. Not sure if ```types-publisher``` will take on parchment dependency.

 
@mhegazy / @vvakame  what's the best practice here?

**Comment by 43081j** [comment]
It sounds to me like we're ok to add a non-@types dependency. Because quill ship's its own types for parchment, seems the only way we can get at them is by a normal dependency. 

This whole whitelist idea does seem strange... an ever-growing list of dependencies that'll one day be enormous 🤔  heh

**Comment by RyanCavanaugh** [comment]
The allow list is a security measure. Because people frequently run `npm install @types/whatevs` without `--ignore-scripts` (don't get me started on running arbitrary scripts from the internet as NPM's *default* behavior), if we allowed arbitrary non-`@types` dependencies from `@types` packages then we're one bad merge in this repo (which has many maintainers and hundreds of active PRs) away from arbitrary code running on thousands of dev machines.

**Comment by 43081j** [comment]
yup that's a fair point. will see how the PR goes and update if it gets merged 👍

**Comment by 43081j** [comment]
This passes now, parchment got added to the whitelist.

**Comment by sumitkm** [comment]
Awesome! that makes it good to merge, owners 👍

**Pull request merged**
