### PR TITLE
[video.js] Fixed more of optional parameters getter/setter

### PR DESCRIPTION
**Pull request by Akxe**
Also did remove spaces between multiple declarations of same functions

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- Documentation is in code, it was a just wrong way to write getter/setter in typescript definition

### CODE REVIEW

**Comment by Akxe** [comment]
In response to `ERROR: 4322:11  unified-signatures      These overloads can be combined into one signature with an optional parameter.`, they cannot, as they have different output dependant on argument presence.
Is not true, I would like to know hot to do it.

**Comment by Akxe** [comment]
Hey, @gjanblaszczyk @vbortone I need your assistance, as I don't know how to fix these. (I included you, as you reviewed and merged my previous PR for this library)

**Comment by vbortone** [comment]
I'll take a look, but it will be towards the end of the week.

**Comment by Akxe** [comment]
Amazing, @vbortone, will it stop Travis from closing the issue, or will you re-open it afterwards, if needed?

**Pull request closed without merging**
