### PR TITLE
NotificationAlertOptions can have a subtitle

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by Zenorbi** [comment]
👍 Thank you!

**Comment by julien-c** [comment]
@Zenorbi I think you're supposed to thumbs up on the actual issue message (for auto merging)?

**Review by zenorbi — APPROVED** [review]

**Comment by Zenorbi** [comment]
I don't think this auto-merges. It's more like an approval, you still need to wait for someone who can merge.

**Comment by vvakame** [comment]
:eyes:

**Comment by julien-c** [comment]
@Zenorbi Do you plan on updating the typings for apn's new major release (which changes a great many things apparently)? Cheers

**Comment by Zenorbi** [comment]
@julien-c Sadly I don't have time to update the typings, feel free to upgrade it if you want to, or rewrite it completely and having the author field set to julien-c.

**Comment by julien-c** [comment]
@Zenorbi I would love to get your feedback on this: https://github.com/node-apn/node-apn/pull/465

**Pull request merged**
