### PR TITLE
[node] Fix wrong property added to AbortSignal

### PR DESCRIPTION
**Pull request by leahciMic**
Correcting a property name, it should be `AbortSignal.reason` not `AbortSignal.signal`.

I made a mistake in my [recent PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64916/files#diff-ce2cc3a70de422f9ec7e8267ecfbacada85d38beae533e095902ddf912c5cadeR65). I added `signal` to `AbortSignal` instead of `reason` in one of the files.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64916/files#diff-ce2cc3a70de422f9ec7e8267ecfbacada85d38beae533e095902ddf912c5cadeR65
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@leahciMic thanks for fixing this (promptly)!

**Comment by leahciMic** [comment]
Ready to merge

**Comment by leahciMic** [comment]
> LGTM!
> @leahciMic thanks for fixing this (promptly)!

No problems at all!

**Comment by tonivj5** [comment]
fixes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64867

**Pull request merged**
