### PR TITLE
[WIP] [@types/redux-form] fixed definitions of FormErrors and FormWarnings

### PR DESCRIPTION
**Pull request by allista**
According to the current redux-form code:
https://github.com/redux-form/redux-form/blob/master/src/ConnectedField.js#L48
Both `FormErrors` and `FormWarnings` are defined identically and recursively to conform with the dot-and-brackets notation of Field names.

E.g. Field name `users[3].addresses[5].zipcode` produces the following structure of the field value in the store:
```js
{
  users: [
    //...
    {
      addresses: [
        //...
        {
          zipcode: 123123
        }
      ]
    }
  ]
```

And corresponding errors/warnings object should be able to reflect this structure.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/redux-form/redux-form/blob/master/src/ConnectedField.js#L48
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by sandersn** [comment]
I don't want to merge a change to such a widely usage package without some authors signing off. 

@aikoven @LKay @bancek @alsiola @tehbi4 @huwmartin @m-b-davis @ethanresnick @maddijoyce @smifun @mshaaban088 @esetnik @bwlt @mrsekut @abeMedia Can you take a look?

As far as I can tell, this change follows the PR description in making FormWarnings and FormErrors apply recursively, to create a fully navigable tree that mirrors the original Field structure. This can be expensive, so it's a bit surprising that the perf benchmarks didn't show any difference.

**Comment by alsiola** [comment]
Sorry @sandersn I'm really not a frequent enough redux-form user any more to be able to comment intelligently on this.

**Comment by allista** [comment]
This patch needs further work, as currently cannot distinguish between array fields and an array value of a single field.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Requires more changes as per conversation thread

**Comment by allista** [comment]
I'm currently on vacation and do not have the means to (i.e. the computer) to address the issue.
Nevertheless I do know how to fix it, and am planning to do so when I'm back. I can open a new PR then, but it would be more convenient if this one will remain open another until, say, March 15.

**Pull request closed without merging**
