### PR TITLE
[@types/path-complete-extname] init path-complete-extname

### PR DESCRIPTION
**Pull request by nicnic-cc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## path-complete-extname ([<kbd>unpkg</kbd>](https://unpkg.com/browse/path-complete-extname@latest/))
was missing the following properties:
1. win32
1. posix
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d0ab1ccb41a3e487c3d9a42d0ff85006142f1741
</p>

**Comment by melangue** [comment]
> Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files. The check for missing properties isn't always right, so take this list as advice, not a requirement.
> 
> ## path-complete-extname ([unpkg](https://unpkg.com/browse/path-complete-extname@latest/))
> was missing the following properties:
> 
> 1. win32
> 2. posix
> 
> Generated by no_entry_sign [dangerJS](https://danger.systems/js) against [d0ab1cc](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d0ab1ccb41a3e487c3d9a42d0ff85006142f1741)

I don't see how I could fix this, I tried doing something like this, which works only if consuming module has `esModuleInterop` set to `true`:
```ts
/**
 * Takes a file path and returns the complete file extension (multiple dots, like tar.gz)
 * Automatically determines if running under Posix or Win32 environment
 */
declare function pathCompleteExtname(path: string): string;
export default pathCompleteExtname;

/**
* Takes a file path and returns the complete file extension (multiple dots, like tar.gz)
* Uses Win32 logic for extension extraction
*/
export function win32(path: string): string;

/**
* Takes a file path and returns the complete file extension (multiple dots, like tar.gz)
* Uses Posix logic for extension extraction
*/
export function posix(path: string): string;
```

But after running tests I get below message, which also makes sense
```sh
ERROR: 1:1    npm-naming    The declaration doesn't match the JavaScript module 'path-complete-extname'. Reason:
The declaration should use 'export =' syntax because the JavaScript source uses 'module.exports =' syntax and 'module.exports' can be called or constructed.
```

Tried looking around for a solution, found types written for another package of the author of `path-complete-extname` -  package [path-parse](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/path-parse/index.d.ts) where it also has a default export and two named exports, but the types only `export` the default `export` as well.

**Comment by weswigham** [comment]
You want a pattern like

```ts
export = pathCompleteExtname;
declare function pathCompleteExtname(path: string): string;
namespace pathCompleteExtname {
  /**
  * Takes a file path and returns the complete file extension (multiple dots, like tar.gz)
  * Uses Win32 logic for extension extraction
  */
  export function win32(path: string): string;

  /**
  * Takes a file path and returns the complete file extension (multiple dots, like tar.gz)
  * Uses Posix logic for extension extraction
  */
  export function posix(path: string): string;
}
```

**Comment by melangue** [comment]
@weswigham Thanks for your suggestion, that makes sense now. Unfortunately both `typescript` and `dtslint` do not like it.

Current `index.d.ts` file:
```ts
export = pathCompleteExtname;
/**
 * Takes a file path and returns the complete file extension (multiple dots, like .tar.gz)
 * Automatically determines if running under Posix or Win32 environment
 */
declare function pathCompleteExtname(path: string): string;
namespace pathCompleteExtname {
  /**
   * Takes a file path and returns the complete file extension (multiple dots, like .tar.gz)
   * Uses Win32 logic for extension extraction
   */
  export function win32(path: string): string;

  /**
   * Takes a file path and returns the complete file extension (multiple dots, like .tar.gz)
  * Uses Posix logic for extension extraction
   */
  export function posix(path: string): string;
}
```
Test result:
```sh
ERROR: 12:1  expect                           TypeScript@4.9 compile error: 
Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
ERROR: 17:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/strict-export-declare-modifiers.md
ERROR: 23:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/strict-export-declare-modifiers.md
```

**Comment by weswigham** [comment]
Those are just some style lints from dtslint, just fix the modifiers as instructed and it should work the same way.

**Comment by melangue** [comment]
It required a bit of massaging, but it works now. Thanks again @weswigham.

**Pull request merged**
