### PR TITLE
Update slick-carousel definitions

### PR DESCRIPTION
**Pull request by herrquark**
All changed options are converted to `JQuery` object, so there's no reason to limit definitions to `string` or to some ambiguous `Object`

[`asNavFor`](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L334), [`prevArrow, nextArrow`](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L441), [`appendDots`](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L494), [`appendArrows`](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L450)

### CODE REVIEW

**Comment by herrquark** [comment]
Argh, github merged stuff that it was not supposed to. Now how do I cancel this?

**Comment by yuit** [comment]
@herrquark  can you revert the merge commit? or if it easier close this one and open new one jsut cherry-pick your change

**Comment by herrquark** [comment]
If you're asking about jquery-ui draggable, then `connectToSortable` is actually used only [once](https://github.com/jquery/jquery-ui/blob/master/ui/widgets/draggable.js#L779) and is pretty straightforward

**Comment by yuit** [comment]
@herrquark  sound good then. thanks for the PR

**Comment by jessepinuelas** [comment]
@herrquark when I try and utilize this I get the following error TS2339: Property 'slick' does not exist on type 'JQueryStatic'. How exactly are you guys importing it into a component in Angular 2 with TypeScript?

**Comment by herrquark** [comment]
There are no mentions of `JQueryStatic` in definition file. Are you trying to include slick souce directly via `import`?

**Comment by jessepinuelas** [comment]
@herrquark I tried importing directly into one of my components and got this error TS2307: Cannot find module 'slick-carousel'. I then removed the import and am simply trying to log out its instance console.log('slick carousel: ', $.slick()); Thats when I get the error TS2339: Property 'slick' does not exist on type 'JQueryStatic'.

**Comment by herrquark** [comment]
there's no `$.slick()`. You can call `slick` only on jquery elements: `$('.slick-div').slick()`

**Comment by jessepinuelas** [comment]
When I use the selector in this case a class $('.showcase-carousel').slick({autoplay: false}); I get slick is not a **function** error. Maybe this is not the best place for the type of questions I am asking. If there's some documentation on utilizing this plugin specifically with TypeScript that you think might be helpful I can check it out.

**Comment by herrquark** [comment]
`.d.ts` files are just definitions for typescript so it can compile properly. You have to point a web browser to the slick itself via `<script />` tag or your module loader. Basically you're doing the whole thing wrong :)

**Comment by jessepinuelas** [comment]
**#fail** I guess I got confused as I have been importing some modules like lodash like this import * as _ from 'lodash'; and simply utilizing  the lodash methods like _find anywhere in my components controller. Thanks for your time. Pluralsight and Stackoverflow it is

**Pull request merged**
