### PR TITLE
Updates type definitions from sharp 0.26.0 to support animated GIF and WEBP formats.

### PR DESCRIPTION
**Pull request by ShaneSP**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/lovell/sharp/tree/master/lib>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by ShaneSP** [comment]
I'm not sure why the continuous integration testing is failing after I added [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49165/commits/57f0f5092670b308d185d038800b8004611c47ea). This is my first time using typescript-bot / doing open source, so sorry for the amateur mistakes ahead of time!

**Comment by ShaneSP** [comment]
@wooseopkim @BTOdell @JamieWoodbury @Fdebijl Hi all! Just wanted to bump this pull request review notification. Hope you are all doing well!

**Review by fdebijl — APPROVED** [review]
LGTM

**Comment by ShaneSP** [comment]
Ready to merge

**Pull request merged**
