### PR TITLE
react-router: Update path definition in RouteProps

### PR DESCRIPTION
**Pull request by 8enSmith**
This PR updates the path definition in RouteProps. It adds "string[]" as an allowed value to match the PropTypes defined in the React-Router source.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/ReactTraining/react-router/blob/e53af0f4e3ea38ba6be3ac2ed94d886dc0ba20e2/packages/react-router/modules/Route.js#L142>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by 8enSmith** [comment]
@johnnyreilly With regards to "https://blog.johnnyreilly.com/2018/09/ivan-drago-and-definitely-typed.html" and after reading your [post](https://blog.johnnyreilly.com/2018/09/ivan-drago-and-definitely-typed.html), I'm not sure if I should change the versionat the top of index.d.ts to 4.4.0 or 4.0.44, so for now I've left it "as is". Note that the source was changed in version 4.4.0-beta5 as can be seen [here](https://github.com/ReactTraining/react-router/commit/a4d0064a328477b899bb89c58dedb53e28f395a1).

Be easy on me if this should be obvious!

**Review by t49tran — APPROVED** [review]

**Comment by johnnyreilly** [comment]
> Be easy on me if this should be obvious!

Ha!  It's not that obvious TBH. If you could change it to "4.4.0" that'd be great!  Ping me when done and I'll merge

**Comment by 8enSmith** [comment]
@johnnyreilly I've updated the version to 4.4 as requested. I did try specifying 4.4.0 but Travis complained that patch versions should not be specified.

**Comment by johnnyreilly** [comment]
Thanks chap!

**Comment by rachitpsolanki** [comment]
Thanks!!! @8enSmith

**Pull request merged**
