### PR TITLE
Aura Javascript API definition file.

### PR DESCRIPTION
**Pull request by olamothe**
- What is Aura
  From : http://documentation.auraframework.org/auradocs#
  Aura is a UI framework for developing dynamic web apps for mobile and desktop devices. Aura provides a scalable long-lived lifecycle to support building apps engineered for growth.
- Developped by Salesforce in order to create application using the Lightning framework
  https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/intro_overview.htm
- Written in Java, exposes a JavaScript API to be used in the Lightning framework
  https://github.com/forcedotcom/aura

### CODE REVIEW

**Comment by vvakame** [comment]
*aura/aura.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/aura
  * http://bower.io/search/?q=aura
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (aura/aura-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
Is this library same as https://www.npmjs.com/package/aura ?

**Comment by olamothe** [comment]
No, it is not the same thing. In the first comment I added a couple of of links you can check if you want.

Basically, it is a framework used inside [Salesforce] (https://en.wikipedia.org/wiki/Salesforce.com) to build web or mobile application.

**Comment by vvakame** [comment]
okay, `aura` is already taken in npm.
please rename your definitions.

**Pull request closed without merging**
