### PR TITLE
Add busySpinner to Combobox Props

### PR DESCRIPTION
**Pull request by tzarger**
Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [ComboBox Props](http://jquense.github.io/react-widgets/api/Combobox/#busySpinner)
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by r3nya — COMMENTED** [review]
Hey! Can you add tests for it please?

E.g.:
```js
<Combobox 
  busy 
  busySpinner={
    <span className="fas fa-sync fa-spin" />
  }
/>
```

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Please add tests as @r3nya suggested to prevent future regression. Thanks!

**Comment by tzarger** [comment]
@r3nya @uniqueiniquity Hello, I added the test as suggested. Sorry for the delay, have had a death in the family. Please let me know what else I can do. Thanks.

**Review by r3nya — APPROVED** [review]
@tzarger thanks! I'm sorry to hear about your situation. 😞

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
@tzarger I'm so sorry to hear that. Thank you so much for your contribution.

**Comment by tzarger** [comment]
@uniqueiniquity @r3nya Thank you both for your kind words. Thanks also for the merge.

**Pull request merged**
