### PR TITLE
jasmine: moved typescript into peerDependencies

### PR DESCRIPTION
**Pull request by Le0Michine**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/en/blog/npm/peer-dependencies/>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by Le0Michine** [comment]
the purpose is to get such warning in case if user has older version of `TS`

image

**Comment by noomorph** [comment]
@Le0Michine , thank you! To me, it also seems more reasonable to declare `typescript>=2.1.4` as a `peerDependency`. 👍 

@zhengbli, do you think we should consider adding such `package.json` files among other definitions requiring latest versions of TypeScript? Done automatically or manually, it looks like a helpful thingy to warn you about a potential version conflict of a definition and a compiler version.

**Comment by Le0Michine** [comment]
@zhengbli it seems that PR looks good and nobody has objections for merge, could you take a look?

**Comment by noomorph** [comment]
Updates, anyone?

**Comment by zhengbli** [comment]
i do think giving a warning about the version mismatch would make sense. But honestly I'm not sure what the role the package.json plays here as a new package.json will be autogenerated when publishing. @andy-ms @mhegazy @RyanCavanaugh are there other concerns if we allow this? Otherwise the recommendation in the readme should be updated.

**Comment by mhegazy** [comment]
This file should not be there, removed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15113

**Pull request closed without merging**
