### PR TITLE
[underscore] Add generic type for memoize

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

No URL for documentation available, but since classes can be memoized, too, and then the return type should not be `Function`.

### CODE REVIEW

**Comment by ffflorian** [comment]
> @ffflorian The Travis CI build failed! Please [review the logs for more information](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/524538795?utm_source=github_status&utm_medium=notification).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!

https://github.com/Microsoft/types-publisher/pull/609

**Comment by ffflorian** [comment]
ping @borisyankov @jbaldwin @ccurrens @clottman @confususs

**Comment by jessetrinity** [comment]
@borisyankov @jbaldwin @ccurrens @clottman @confususs @rygine any interest in this PR? 
Since this is a popular package, this change will not be merged without owner approval. Thanks!

**Comment by ffflorian** [comment]
@sandersn could you please have a look at this? Thanks!

**Pull request merged**
