### PR TITLE
Added redux-storage-engine-jsurl declaration to redux-storage

### PR DESCRIPTION
**Pull request by screendriver**

### CODE REVIEW

**Comment by minestarks** [comment]
Isn't this a separate npm package than `redux-storage`? Typings for npm packages should go into a folder named after the npm package. Please read the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package).

**Comment by screendriver** [comment]
I know. But if you look at the **complete** type definition (and not only my changes) you can see that there are a lot more definitions. Mine is just an addition to the existing ones. 

I don't know why it was written in this style and why it was published 🤔

**Comment by minestarks** [comment]
That's fair. Sorry I didn't notice that the pattern was preexisting. Still, this would be a good time to switch to doing it the right way. Would you mind creating a new typing? I'll approve then.

**Comment by screendriver** [comment]
Hi @minestarks ,

I changed everything but the Travis build fails with `Error: In /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/redux-storage-engine-jsurl/package.json: Dependency redux-storage not in whitelist; please make a pull request to types-publisher adding it.`

How can I fix that? Should I make a pull request there to whitelist `redux-storage`? I need that as a dependency in my type definition.

**Comment by minestarks** [comment]
@screendriver thank you for making the change. I actually don't think you need the `package.json`. Try deleting it. Right now your `package.json` is declaring a dependency on the actual `redux-storage` package which is unnecessary. You just depend on the `redux-storage` typings that are on right? That's automatically handled by the types publisher.

**Comment by screendriver** [comment]
@minestarks I deleted the `package.json` and the Travis build is finally green ☺️

**Comment by screendriver** [comment]
@minestarks I fixed the merge conflicts 😉

**Comment by screendriver** [comment]
Thanks for merging but it seems that it doesn't get published: https://www.npmjs.com/search?q=@types/redux-storage-engine-jsurl&page=1&ranking=optimal

**Pull request merged**
