### PR TITLE
feat(node): declare URL and URLSearchParams as globals

### LINKED ISSUE #34960: [node] Missing global URL and URLSearchParams typings
This is a follow-up issue of #25342 and #19799.

In #25269 the `URL` and `URLSearchParams` classes have been added as globals because since Node.js 10.0 they are [exposed as globals](https://nodejs.org/api/url.html#url_class_url).

Because `lib.dom.d.ts` also exposes them as globals, projects _which referenced both_, `node` and `lib.dom`, got "Duplicate identifier 'URL'" errors (see #25342). Therefore the global `URL` and `URLSearchParams` has been removed again.

This fix (actually a workaround  for a missing declaration merging feature of TypeScript) now has the drawback that we cannot use the global `URL` class in Node.js-code (instead we need to import it from the `url` module). This is especially bad for universal modules which are supposed to work in the browser + node by just using the global `URL` (which works since Node.js 10).

So I want to discuss solutions for this atm. unsupported scenario here. (Without having local declarations in consuming projects.)

----

One solution would be to support this scenario in TypeScript (allow - exactly same? - global class definitions in multiple declaration files). @weswigham Would this be possible?

A more straight-foward solution would be to create a new DT package (e.g. `node-global-url` or maybe better `whatwg-global-url`) which can be installed additionally and selected by using e.g. `"types": ["node", "node-global-url"]` in a `tsconfig.json` for projects which face the mentioned scenario above.

Any other ideas?

### PR DESCRIPTION
**Pull request by antongolub**
closes: #34960

NodeJS spec:  
* https://nodejs.org/api/url.html#the-whatwg-url-api
* https://nodejs.org/api/url.html#class-urlsearchparams
```
URL v10.0.0 | The class is now available on the global object.
URLSearchParams v10.0.0 | The class is now available on the global object.
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by demurgos** [comment]
Thank you very much for sending a PR.

The `dom` lib defines the global first and then re-exports it through the module. This implementation does the reverse. As long as there are no conflicts I assume it should be fine.

I am really excited for this fix: it will be **very** helpful!

**Comment by antongolub** [comment]
TS `lib.dom.d.ts` "version": "4.6.0-dev.20220119"
```ts
declare var AbortSignal: {
    prototype: AbortSignal;
    new(): AbortSignal;
    abort(reason?: any): AbortSignal;
};

```
"version": "4.6.0-dev.20220119"
```ts
declare var AbortSignal: {
    prototype: AbortSignal;
    new(): AbortSignal;
    // abort(): AbortSignal; - To be re-added in the future
};
```

**Comment by antongolub** [comment]
CC @SimonSchick

**Comment by gabritto** [comment]
Tested this in the playground, and it seems to work alongside the `dom` definitions of url. I'd still like to wait for an owner review. Re-pinging  @jkomyno @alvis @r3nya @btoueg @smac89 @Touffy @DeividasBakanas @eyqs @Hannes-Magnusson-CK @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @galkin @parambirs @eps1lon @westy92 @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @bhongy @chyzwar @trivikr @yoursunny @qwelias @ExE-Boss @peterblazejewicz @addaleax @victorperin @ZYSzys @nodejs @LinusU @wafuwafu13

**Review by peterblazejewicz — APPROVED** [review]

**Comment by antongolub** [comment]
Ready to merge

**Comment by sandersn** [comment]
Note: This breaks configs that have `lib: ["webworker"]` because lib.webworker.d.ts includes both `URL` and `URLSearchParams`. sparql-http-client on DT is one example.

**Comment by peterblazejewicz** [comment]
@sandersn what's the option here we can pick? There are two posts on discussion with same (or similar) problem already

**Comment by antongolub** [comment]
Interesting...
```
createObjectURL(object: any): string;
createObjectURL(obj: Blob | MediaSource): string;
```

**Comment by antongolub** [comment]
Seems hacked:
```ts
        var URL:
          // For compatibility with "dom" and "webworker" URL declarations
          typeof globalThis extends ({ webkitURL: infer URL } | { TransformStreamDefaultController: infer T, URL: infer URL })
          ? URL
          : typeof _URL;
```

**Comment by peterblazejewicz** [comment]
It does not work with use case (from your PR branch):
```
npm test sparql-http-client
``` 
(the DT lib declaring `webworker` lib in tsconfig:
```
Error: Errors in typescript@3.8 for external dependencies:
../node/url.d.ts(872,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'URL' must be of type '{ new (url: string, base?: string | URL | undefined): URL; prototype: URL; createObjectURL(object: any): string; revokeObjectURL(url: string): void; }', but here has type 'typeof URL'.
```

**Comment by antongolub** [comment]
Oops... 3.8 does not provide `TransformStreamDefaultController` var declaration. Сontinue digging.

**Comment by antongolub** [comment]
@peterblazejewicz, how about?
```ts
        var URL:
            // For compatibility with "dom" and "webworker" URL declarations
            typeof globalThis extends { onmessage: infer O, URL: infer URL }
                ? URL
                : typeof _URL;
```

**Comment by peterblazejewicz** [comment]
Yes, this passes the use-case test, but let's have more opinion on what next.

**Comment by antongolub** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58619

**Comment by thw0rted** [comment]
Anybody that's still watching this, maybe you could weigh in on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59905 where I'm trying to do something similar with another Node "DOM-compatible" API?  I'm going to try to use the same pattern you discovered here, if possible.

**Pull request merged**
