### PR TITLE
Fix test argument type for jest-each

### PR DESCRIPTION
**Pull request by nickserv**
In `jest-each`, the each callback args are forced to be strings, but they should be any. This is a bug fix to prevent the types from being too restrictive, so I didn't change the version (assuming it will still republish with the fix).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See parameters of the JestEach function declaration, and note that `any[][]` and `string[]` are not consistent, it should be `any[]`.
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by theutz — APPROVED** [review]
lgtm

**Comment by nickmccurdy** [comment]
Thanks, how can I tell when this will be released?

**Comment by paulvanbrenk** [comment]
Should be in [a couple of hours](https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated), and you should be able to check [here](https://www.npmjs.com/package/@types/jest-each) if there is a new version.

**Comment by aalivehelsinki** [comment]
Thanks for taking care of this, @nickmccurdy ! 😄

**Pull request merged**
