### PR TITLE
[mobx-apollo] data in the query result can potentially be undefined

### PR DESCRIPTION
**Pull request by pselden**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sonaye/mobx-apollo/blob/master/src/index.js#L21
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by pselden** [comment]
Hmm -- it did not tag anyone for review (because I'm the only maintainer) -- is there a way to get it to pass the checks?

**Comment by pselden** [comment]
👍

**Comment by pselden** [comment]
Hey @uniqueiniquity  -- sorry to bother you directly, but tagged you since you reviewed the last one. Is there a step I need to take to get it marked as ready for merge? I'm the only maintainer right now for this package but it did not mark anything for review and/or approval.

**Comment by uniqueiniquity** [comment]
No worries! I'll look into why it didn't tag you.

**Pull request merged**
