### PR TITLE
[three.js] Simplify typings by employing "polymorphic this types" for clone()/copy() methods

### PR DESCRIPTION
**Pull request by ulrichb**
Note: This also solves TS 2.0 --strictNullChecks errors.

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by florentpoujol** [comment]
This makes the definitions dependent of TS 2.0, so I would advise against it at least until it's not officially out.

Or maybe it should be merged in the `types-2.0` branch instead of master.

Otherwise it looks good to me.

**Comment by vvakame** [comment]
don't worry, Travis CI uses TypeScript 1.8.10 and this PR passed tests.

**Comment by ulrichb** [comment]
> This makes the definitions dependent of TS 2.0

The feature I'm using here is called "Polymorphic this type", which is supported since TS 1.7 (see https://github.com/Microsoft/TypeScript/wiki/Roadmap). Is this OK?

**Comment by ulrichb** [comment]
> Otherwise it looks good to me

Thanks for the review!

**Pull request merged**
