### PR TITLE
[splunk-logging] correct name of serializedContextQueue

### PR DESCRIPTION
**Pull request by BoruiGu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L71
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by bricka — APPROVED** [review]
I feel dumb that I typo'd that. Thanks for the fix!

**Comment by BoruiGu** [comment]
CI is failing due to https://github.com/microsoft/DefinitelyTyped-tools/issues/362

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## splunk-logging ([<kbd>unpkg</kbd>](https://unpkg.com/browse/splunk-logging@latest/))
was missing the following properties:
1. utils
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against af12ee0f1ef0f85c6d10054833b7a3e158187d0b
</p>

**Comment by BoruiGu** [comment]
@sandersn @typescript-bot still thinks `❌ Continuous integration tests have failed`.. is there a way to have the bot refresh?

**Comment by sandersn** [comment]
I'm not sure what happened. @elibarzilay you might be interested since the bot doesn't often encounter re-runs from close/re-open sequences.

**Pull request merged**
