### PR TITLE
[Chrome] Adds updateStaticRules/UpdateStaticRulesOptions to the declarativeNetRequest interface

### PR DESCRIPTION
**Pull request by Pteroducktyl**
Adds updateStaticRules function and UpdateStaticRulesOptions type. Defined here:
https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-UpdateStaticRulesOptions https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateStaticRules

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dd71b6c1215af2e73c20c30855b163e3bac90784
</p>

**Review by matcarlson — APPROVED** [review]
Thanks for your contribution!

**Comment by Pteroducktyl** [comment]
thanks for the feedback!

**Comment by Pteroducktyl** [comment]
Ready to merge

**Comment by Pteroducktyl** [comment]
Ready to merge

**Review by matcarlson — APPROVED** [review]

**Pull request merged**
