### PR TITLE
add package qlik-engineapi

### PR DESCRIPTION
**Pull request by konne**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by konne** [comment]
@minestarks please can you merge that second PR for my qlik typedefinition files, thx

**Comment by aozgaa** [comment]
@konne, what should be done with this PR?

**Comment by konne** [comment]
@aozgaa please merge, so that a new package is available

**Comment by konne** [comment]
@aozgaa: sorry, I have seen that all definitions are now under /types do you like to fix that or should I make a PR with a move of that directory

**Comment by konne** [comment]
@aozgaa I made a new PR to fix that: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16650

**Pull request merged**
