### PR TITLE
ramda: add support of applying `chain` to function type argument

### PR DESCRIPTION
**Pull request by jituanlin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://gist.github.com/jituanlin/4f86acae8e3e941358fb6da5e240a917>>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by googol** [comment]
I do not believe this is a supported signature for `chain`. If you have a runnable example of this being used I'd be interested in seeing that

**Comment by jituanlin** [comment]
https://gist.github.com/jituanlin/4f86acae8e3e941358fb6da5e240a917
This is the example.

**Review by googol — APPROVED** [review]
RIght, now that I read the documentation for the function again, it makes sense to me.

This is correct and solves the case described in the documentation as a special case:
```
If second argument is a function, `chain(f, g)(x)` is equivalent to `f(g(x), x)`.
```

It is in fact the standard monad implementation for a functions

**Review by googol — CHANGES_REQUESTED** [review]
Please don't add new unrelated things things to a pull request after it has been approved.

Please make a new pr with the unrelated changes

**Comment by jituanlin** [comment]
> Please don't add new unrelated things things to a pull request after it has been approved.
> 
> Please make a new pr with the unrelated changes

Sorry, I make a mistake about pull request flow, I will fix it lately.

**Comment by googol** [comment]
I think this used to have a test. Anyways, adding for example the test case from the documentation would be good :+1:

**Pull request merged**
