### PR TITLE
types(selenium): update selenium-webdriver to 2.53.1

### PR DESCRIPTION
**Pull request by cnishina**

### CODE REVIEW

**Comment by cnishina** [comment]
Travis builds tests fail because `angular-protractor` and `protractor` on the `types-2.0` branch require `selenium-webdriver` version 2.44. It appears that these are referenced locally.

The current version of `selenium-webdriver` is version 2.53. The API has significantly changed and no longer works for `angular-protractor` / `protractor`.

* Should we remove `angular-protractor` and `protractor` typings to publish `selenium-webdriver` 2.53 typings? If we do remove `angular-protractor` / `protractor`, what happens to `@types`, are they unpublished?
* Since `angular-protractor` and `protractor` appear to require `@types/selenium-webdriver` 2.44, should we download the correct version from `@types` via npm to pass the tests?

**Comment by andy-ms** [comment]
If you those packages don't work with the latest version, you can add a `package.json`:

    {
        "dependencies": {
            "@types/selenium-webdriver": "^2.44.28"
        }
    }

You'll also have to remove `typeRoots` from the tsconfig.

**Comment by cnishina** [comment]
Yes, I understand if a user that wants to use `protractor` typings, they should use `"@types/selenium-webdriver": "^2.44.28"`. The concern is that the DefintielyTyped tests use a relative triple slash reference. The newer version for `selenium-webdriver` is not compatible with the `protractor` ambient typings and `protractor` uses `selenium-webdriver` ambient typings via triple slash relative path. In this PR, we are removing the protractor files from the `types-2.0` branch. This appears to be the only reasonable way to get `selenium-webdriver` published.

So why are we not updating the `protractor`, `protractor-helpers`, and `protractor-http-mocks` ambient typings? Protractor has been recently rewritten in TypeScript and has its own support [declaration type support](https://github.com/angular/protractor/blob/master/package.json#L62). Not having up-to-date typings for selenium-webdriver is a current blocker for the next release.

**Comment by cnishina** [comment]
@andy-ms looks like that worked! 🎉 

The test is failing for react-daterange-picker:
```
----------------- For file:/home/travis/build/DefinitelyTyped/DefinitelyTyped/react-daterange-picker/tsconfig.json
\home\travis\build\DefinitelyTyped\DefinitelyTyped\moment-range\index.d.ts
	 Line 6: Cannot find module 'moment'.
\home\travis\build\DefinitelyTyped\DefinitelyTyped\react-daterange-picker\index.d.ts
	 Line 7: Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/moment-range/index"' resolves to a non-module entity and cannot be imported using this construct.
\home\travis\build\DefinitelyTyped\DefinitelyTyped\react-daterange-picker\react-daterange-picker-tests.tsx
	 Line 4: Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/moment-range/index"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by cnishina** [comment]
It looks like the root cause is https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11271.

**Comment by cnishina** [comment]
@andy-ms since this is passing now, could we get this merged in too?

**Pull request merged**
