### PR TITLE
styled-system: LayoutProps extends OverflowProps

### PR DESCRIPTION
**Pull request by joekrill**
The [implementation of `layout`](https://github.com/styled-system/styled-system/blob/15a4233c085ff14c77ba61508e4737a2ec641081/packages/layout/src/index.js) includes `overflow`, and it's listed in the [API documentation](https://github.com/styled-system/styled-system/blob/c648d2d3ee02feac249ba219341dc79c33e2964f/docs/api.md#layout) as well.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by peduarte** [comment]
Did you add a test for the new addition?

**Comment by joekrill** [comment]
@peduarte I did not _explicitly_ add tests, but there are effectively tests in place already for checking `overflow`. By explicitly removing `OverflowProps` from the `BoxProps` type, we would see a type error if `overflow`, `overflowX`, and `overflowY` were no longer included, in the existing overflow tests on line 408 of `types/styled-system/styled-system-tests.tsx`:

```
        // overflow
        <Box overflow="hidden" />
        <Box overflowX="auto" />
        <Box overflowY="scroll" />
```

I did notice, however, that I left an unused imports. And that `overflow` itself is also no longer needed to explicitly use the `layout` styles in the `Box` type. So I've just added a commit to fix that those. 

I'm happy to add additional tests, but there weren't similar tests for other "lower-level" sets of props, so I didn't do that here because I wasn't sure if it would be desirable. But I could absolutely add aa explicit component to test only overflow, i.e:

```
const Overflower: React.ComponentType<OverflowProps> = styled(overflow);

const test = ( )=> (
        /* snip: lots of other test */

        /* These are existing overflow tests: */
        // overflow
        <Box overflow="hidden" />
        <Box overflowX="auto" />
        <Box overflowY="scroll" />

        /* These woud be new overflow tests: */
        <Overflower overflow="hidden" />
        <Overflower overflowX="auto" />
        <Overflower overflowY="scroll" />
)
```

Let me know if you'd prefer that and I'll go ahead add it.

**Comment by peduarte** [comment]
@joekrill oh I see, yeah that makes perfect sense. Nice one man, thanks for the contribution! <3

**Comment by alloy** [comment]
Sounds like that was a 👍 from @peduarte.

Thanks!

**Pull request merged**
