### PR TITLE
[@types/react] Add JSX.ElementProps<T>

### PR DESCRIPTION
**Pull request by Everspace**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

When your write components that are essentially an extension around `JSX.IntrinsicElement`, your first intuition is to do something like the following

```jsx
interface MyProps extends JSX.IntrinsicElement["div"] {
  color: string
}

export const MyComponent: React.SFC<MyProps> = ({color, style, ...props}) => {
  return (
    <div {...props} style={{...style, color}} />
  )
}

```

Which is not possible.

Instead you must do something like this...

```jsx
interface MyProps {
  color: string
}

export const MyComponent: MyProps & React.SFC<JSX.IntrinsicElement["div"]> = ({color, style, ...props}) => {
  return (
    <div {...props} style={{...style, color}} />
  )
}
```

Which is ugly and explodes the tooltips in editors such as visual studio code.

image

This adds the `JSX.ElementProps<T>` generic to extend off of which results in what I believe is prettier, more intuitive, and also results in better tooltips in visual studio code.

```jsx
interface MyProps extends JSX.ElementProps<"div"> {
  color: string
}

export const MyComponent: React.SFC<MyProps> = ({color, style, ...props}) => {
  return (
    <div {...props} style={{...style, color}} />
  )
}
```

image

### CODE REVIEW

**Review by jgoz — CHANGES_REQUESTED** [review]
Couldn't you just use `interface MyProps extends React.HTMLAttributes<HTMLDivElement>`?

Also, this change was only applied to the v15 typings...

**Comment by Everspace** [comment]
@ferdaber I remember I was unable to do `interface ExtendedProps extends JSX.IntrinsicElements['div']`. I wonder if that was a quirk of babel now. I'll pull up the exact problem it was when I am back at my personal computer.

It is also in part because the type presented is incredibly verbose, making it hard to read.

@jgoz I didn't know about that! I will try that when I get home. This might just be a documentation thing or a recommendation elsewhere. Also whoops on the v15 mistake I'll correct that when I get the chance.

I also do think the ability to "say" the thing you mean (`extends "button"` when using `<button/>`) is good. Being able to go "I am using a `summary`" and not having to know it's exactly an `HTMLElement` is useful, especially if the underlying type can change or have additional types in the future.

**Comment by ferdaber** [comment]
I agree with all those points, but creating a type that only aliases to `JSX.IntrinsicElements` is problematic because (a) it won't actually let you extend it if you weren't able to extend from `JSX.IntrinsicElements` in the first place and (b) you're relying on the current "max type depth" of the language server to eliminate the verbosity, which could change at any point.

As far as using `HTMLAttributes<HTMLDivElement>`, that is technically not completely accurate as it's missing the `ref` prop, which is what `DetailedHTMLAttributes` is for.

**Comment by Everspace** [comment]
@ferdaber  What I encountered was the following which prompted this whole rigmarole:

```
// Babel:     SyntaxError: ${file}: Unexpected token, expected ","
// tsc 3.1.3: error TS2499: An interface can only extend an identifier/qualified-name with optional type arguments.
interface InteractiveGroupProps extends JSX.IntrinsicElements["div"] {
  color?: any
  seperated?: boolean
}
```

where as 

```
interface InteractiveGroupProps extends React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement> {
  color?: any
  seperated?: boolean
}
```

or

```
type JSX_Div = JSX.IntrinsicElements['div']
interface InteractiveGroupProps extends JSX_Div {
  color?: any
  seperated?: boolean
}
```

Are fine.

Since all those definitions were there, I thought it would be simplest to include a general purpose alias. I had started on that second bit (since it seemed easiest at the time) and thought "There must be a better way because redefining all this is dumb".

I didn't know the max verbosity was a thing. That's good to know, but my other point about having to type all that out still stands.

In a perfect world, all those `a/div/summary` things would be exported or in a namespace so it was easier to find.

**Comment by ferdaber** [comment]
Ah I see, the alias itself is a way to convert the indexed property into a generic type parameter, which makes the compiler happy. If that is the case I'm fine with that.

As an NP - I would just remove the other type so that there's less types to maintain (this is all public and exported since it's in a namespace), and rename it to something that is more precise, maybe like `HTMLElementAttributes`? `Props` by convention is the React typings is specific to the concept of JSX `props`, not the "allowable stuff to be passed into a JSX tag"

**Comment by Everspace** [comment]
@ferdaber What do you mean when you say NP? New pull/nitpick?

So the result would be something like

```ts
namespace JSX {
   HTMLElementAttributes<T extends keyof IntrinsicElements>
}
```

**Comment by ferdaber** [comment]
nitpick*, and yes (instead of having another type alias for `keyof IntrinsicElements`)

**Comment by Everspace** [comment]
I've named it `ElementAttributes` because `JSX.IntrinsicElements` includes things like "ellipse" for SVG things.

**Comment by Everspace** [comment]
@ferdaber @johnnyreilly I'm not sure what's going on with those tests.

**Comment by Hotell** [comment]
First of all, thanks for PR @Everspace !

Your example:

```tsx
interface MyProps extends JSX.IntrinsicElement['div'] {
  color: string;
}

export const MyComponent: React.SFC<MyProps> = ({ color, style, ...props }) => {
  return <div {...props} style={{ ...style, color }} />;
};
```

doesn't work, because interface cannot extend from type that was created via union or intersection.
(you can read more about it here https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c)

```tsx
interface IntrinsicElement {
  div: React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLDivElement>,
    HTMLDivElement
  >;
}

// 👉DetailedHTMLProps uses intersection

type DetailedHTMLProps<E extends HTMLAttributes<T>, T> = ClassAttributes<T> & E;
```

So all you need to do is use `type` for declaring props, which is IMHO a better way, as using interface is kinda code smell that you're going expose unnecessary API surface of your component
(check tip no.7 👉 https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680 👀)

**Works:**

```tsx
type MyProps = JSX.IntrinsicElement['div'] & {
  color: string;
};

export const MyComponent: React.SFC<MyProps> = ({ color, style, ...props }) => {
  return <div {...props} style={{ ...style, color }} />;
};
```

Also using global types related to JSX is not very future proof, as TS supports jsx factory scoping now (still isn't implemented within react.d.ts), so by using global references from JSX namespace you may write non future proof code, which will need to get refactored.

What I would like to see instead, is to add a helper within react namespace, instead of clobbering JSX

Something like following:

```tsx
// react.d.ts
namespace React {
  type DomElementAttributes<T extends HTMLElement> = DetailedHTMLProps<HTMLAttributes<T>, T>;
}
//
type MyProps = import('react').DomElementAttributes<HTMLDivElement> & {
  color: string
}

// or not recommended interface ☝️
// also interface cannot use import() 😭
interface MyProps extends React.DomElementAttributes<HTMLDivElement> & {
  color: string
}
```


WDYT ?

**Comment by FredyC** [comment]
The PR ##30331 fixing all React tests failing has been merged so I recommend rebasing and it should be much easier to make tests passing here.

**Pull request closed without merging**
