### PR TITLE
Updated functions to latest ones

### PR DESCRIPTION
**Pull request by AdaskoTheBeAsT**
Updated functions to latest ones

### CODE REVIEW

**Comment by horiuchi** [comment]
@AdaskoTheBeAsT thank you your contributions.
please fix Travis CI failed. https://travis-ci.org/borisyankov/DefinitelyTyped/builds/49847893#L175

**Comment by AdaskoTheBeAsT** [comment]
Hi,

sorry - I will check my tests and fix it.

Best regards

Adam

**Comment by horiuchi** [comment]
@AdaskoTheBeAsT Not work, yet.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
