### PR TITLE
fix: sshpk/createSign hash parameter type

### PR DESCRIPTION
**Pull request by OlivierMartineau**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by OlivierMartineau** [comment]
I've just fixed createSign signature (parameter should be a Hash type, like createVerify, instead of a Key algo type).
I also fixed the tests accordingly, and tested the changes in my own code.

Preventing such error would be easier if types were more explicit IMO:
AlgorithmType -> KeyAlgoType
AlgorithmHashType -> HashType
KeyType -> PrivacyType (or AsymetricType)

**Comment by CoalZombik** [comment]
Thanks for this bug fix. I missed this incorrect type.

Yes, naming of these types are not great (my fault), but I am afraid that renaming of these types will break backwards compatibility and possibly broke some existing code.

**Review by CoalZombik — APPROVED** [review]

**Comment by OlivierMartineau** [comment]
Ready to merge

**Comment by OlivierMartineau** [comment]
Thank you for your quick response 👍 

Yes, I also think changing the types would possibly break things...
Something to keep in mind once node-sshpk switch to another major version I guess...

**Comment by OlivierMartineau** [comment]
@CoalZombik will you update https://www.npmjs.com/package/@types/sshpk ?
Or is it automatic and I just should wait a bit?

**Pull request merged**
