### PR TITLE
D3 contour 1.2.0

### PR DESCRIPTION
**Pull request by Ledragon**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [v1.2.0](https://github.com/d3/d3-contour/releases/tag/v1.2.0)
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by tomwanzek — CHANGES_REQUESTED** [review]
@Ledragon could you kindly add a test? Thx, T

**Comment by Ledragon** [comment]
@tomwanzek not only I can, but I have to, and I did :-)

**Review by tomwanzek — APPROVED** [review]
Looks great to me 👍

**Comment by tomwanzek** [comment]
@armanio123 @andy-ms Could you please nudge the publication pipeline? The merge has not been published to npm. Thx in advance.

**Pull request merged**
