### PR TITLE
[@types/node] ChildProcess `code` and `signal` can be null

### PR DESCRIPTION
**Pull request by samuela**
According to https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L207 and in particular https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L246, it's possible for either the `code` or `signal` values to be null. Note also the docs for the 'exit' event: https://nodejs.org/api/child_process.html#child_process_event_exit.

This occurs often in practice: If a spawn completes without being killed, `signal` will be `null`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L207
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]

**Comment by samuela** [comment]
Travis errors appear to be unrelated:
```
Error: The following packages had errors: business-rules-engine, jsdom, next, react-flag-icon-css, react-helmet/v4, react-native-modalbox, react-native-vector-icons, reactstrap, redux-form
```

**Review by ZaneHannanAU — APPROVED** [review]
Errors are all unrelated

**Review by jeremiergz — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Comment by samuela** [comment]
What do I need to do to make @typescript-bot happy?

**Comment by Flarna** [comment]
Push a commit or close and reopen the PR to retrigger CI. The problems reporter during your last run should be fixed meanwhile.

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
