### PR TITLE
[@ember/routing] Resolve duplicate identifier 'rootURL' error

### PR DESCRIPTION
**Pull request by gitKrystan**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by chancancode — APPROVED** [review]

**Review by chriskrycho — APPROVED** [review]
Thanks so much for fixing this @gitKrystan! :shipit:

**Comment by chriskrycho** [comment]
Ready to merge

**Comment by jamescdavis** [comment]
Thanks for fixing this @gitKrystan! Looks like our PRs crossed each other!

**Comment by gitKrystan** [comment]
No problem. I should have checked the open PRs before I opened the first one. Would have saved myself some trouble. 😅

**Pull request merged**
