### PR TITLE
[range-parser] fix babel7's --isolatedModules recommended option

### PR DESCRIPTION
**Pull request by tlaziuk**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28744>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by 19majkel94** [comment]
@tlaziuk What does `--isolatedModules` have common with the enum?

**Comment by 19majkel94** [comment]
Thanks! I read this article:
https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/

But there was nothing about const enums. Then I read this comment:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23002#issuecomment-359051201

And now I get it but still don't understand why const enum broke the isolated modules 🤔

**Review by MichalLytek — APPROVED** [review]

**Comment by 19majkel94** [comment]
I have no idea why Travis failed - maybe it has been fixed on master already as it doesn't seems to be related to this changes.

**Comment by amcasey** [comment]
Re-opening, per @wyqydsyq.

**Comment by amcasey** [comment]
@tlaziuk, it looks like we have a clean test run, owner approval, and downstream approval.  Good to merge?

**Comment by tlaziuk** [comment]
@amcasey yes, please proceed

**Pull request merged**
