### PR TITLE
graphql: TypeInfo constructor optional argument

### PR DESCRIPTION
**Pull request by jtmthf**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
@jtmthf Would you offer line of source code, as the reference?

**Comment by jtmthf** [comment]
Yes, here is the reference to TypeInfo in the original [source](https://github.com/graphql/graphql-js/blob/914dde29098425df45cee95b6feb81b9fed97edb/src/utilities/TypeInfo.js#L62)

**Comment by intellix** [comment]
👍

(Not sure how the bot expects me to reply)

**Comment by jtmthf** [comment]
Taking a look now at the original source, I'm no expert on flow at all, but the type signature for TypeInfo in the source is

```js
constructor(
    schema: GraphQLSchema,
    // NOTE: this experimental optional second parameter is only needed in order
    // to support non-spec-compliant codebases. You should never need to use it.
    // It may disappear in the future.
    getFieldDefFn?: typeof getFieldDef
  )
```

While the typings here have it referenced as

```typescript
constructor(
            schema: GraphQLSchema,
            // NOTE: this experimental optional second parameter is only needed in order
            // to support non-spec-compliant codebases. You should never need to use it.
            // It may disappear in the future.
            getFieldDefFn?: getFieldDef
        );
```

I'm not sure if we need the typeof in this then?

**Comment by jtmthf** [comment]
Never mind, typeof is not needed in this case as getFieldDef refers to an interface

**Comment by TonyPythoneer** [comment]
@jtmthf It's because `getFieldDef` in `graphql` is a function but it doesn't export. In Typescript, we just make a interface to describe the type. 

Take a look the difference about `getFieldDef`:
* [source code](https://github.com/graphql/graphql-js/blob/914dde29098425df45cee95b6feb81b9fed97edb/src/utilities/TypeInfo.js#L225)
* [tsd](https://github.com/jtmthf/DefinitelyTyped/blob/6feba14fc89dba05cda87b26e5a4311d513b8a41/graphql/index.d.ts#L2842)

Suppose the `getFieldDef` needs to be exported, we can define the function and use `typeof` to get its interface.

**Comment by jtmthf** [comment]
@TonyPythoneer interesting, I wasn't aware that an interface could be used to describe the signature of a function

**Comment by TonyPythoneer** [comment]
@jtmthf In fact, typescript can parse interface(or type) of function by `typeof` but it notices that it's only used on type assert.

**Comment by TonyPythoneer** [comment]
@andy-ms Would you merge this?

**Comment by TonyPythoneer** [comment]
@jtmthf Sorry, I found a fault, so I don't approve this PR. It's because it should merge on `types-2.0`, not `master`. The reason on README. I hope you understand.

**Comment by TonyPythoneer** [comment]
@andy-ms I have a question. Which branch should it offer contributor maintaining? I haven't followed  DefinitelyTyped community too long. I found `types-2.0` has merged on `master`. Now, contributors should send PR on `master`?

**Comment by TonyPythoneer** [comment]
@andy-ms I had read the PR template. It's sure to against the master branch.

Would you merge this? thx.

**Pull request merged**
