### PR TITLE
[@types/node] Fix global crypto types

### PR DESCRIPTION
**Pull request by ghost**
Closes #68351 #68352 #68354 #68357

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by Semigradsky** [comment]
@codershiba The solution is
```diff
    global {
        var crypto: typeof globalThis extends {
+           onmessage: any;
            crypto: infer T;
        } ? T
            : webcrypto.Crypto;
    }
``` 
The idea is that we need use inferred value only when `dom` is used in `tsconfig.json#compilerOptions.lib` (in this case we have `onmessage` in global scope).

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/wasi.d.ts
1. types/node/ts4.8/wasi.d.ts
1. types/node/crypto.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 60b5aa9aceb2fef1ba072e0231b70b0f336f7a76
</p>

**Review by Semigradsky — APPROVED** [review]
Thank you! 👍

**Review by peterblazejewicz — APPROVED** [review]

**Review by Anonymous4078 — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by jakebailey** [comment]
Sent https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68371

**Pull request merged**
