### PR TITLE
Added types for OpenApi 2.0

### PR DESCRIPTION
**Pull request by IulianOctavianPreda**
Added types for [OpenApi 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0)
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by rbuckton** [comment]
Can you clarify how this is intended to be used? There's no `openapi-v2` package on npm, so I assume this defines only types for something intended to adhere to the Open API specification? Also, its not common to include the version in the package name, so I would expect this to be named `openapi`, not `openapi-v2`. Is there a reason to name it in this way?

**Comment by IulianOctavianPreda** [comment]
Hi.

This is intended to be used only for type definitions as the OpenApi specifications are only there to communicate how an object should look like leaving the implementation specifics to different entities. 

With this package I seek to help anyone that wants to create in Typescript an OpenApi compliant parser, code generator or anything that makes a use of it.

The versioning, although not common, is used with a reason.
The specifications are not subject to big changes between minor versions but are subject to breaking changes between major versions.
The minor versions can receive only small adjustments and those should be included in this package. 
The major versions, in my opinion, should be  new npm packages since they can be treated as a completely different entities because of the breaking changes. Also the main versions(v2 and v3) are currently supported and function in parallel as different entities. For example Swagger can emit it's output in both formats. 

Another reason is for development, since the specifications exist in parallel, one might want to make its software compliant with the different versions. 

I hope this explains my reasoning.

**Comment by sandersn** [comment]
If there's no source package to be typed, then Definitely Typed is not the right place for this package.

- If there will *never* be a source package -- if this will only ever exist as types, you should publish this package yourself to npm as `openapi-v2` (or `openapi` at version 2).
- If you expect that somebody else will eventually create a package named `openapi-v2` or `open-api`, then I would create a repo for these types and only publish them as `openapi-types`, if at all.

> With this package I seek to help anyone that wants to create in Typescript an OpenApi compliant parser, code generator or anything that makes a use of it.

I interpret this to mean the first option: somebody will `npm install openapi-v2`, then import types from openapi-v2, and make an implementation that conforms to openapi types. Then they will publish a package named pet-parser or something (for something that parses pet information?).

**Review by sandersn — CHANGES_REQUESTED** [review]
Type-only packages, which is what this appears to be, should just be published straight to npm instead of going through Definitely Typed into the `@types` scope.

**Comment by IulianOctavianPreda** [comment]
Thank you for your feedback. 
I can definitely publish these types from my personal account, I contributed to this repository since it has more credibility than a third-party developer. Also, it integrates seamlessly with typescript, making things easier for the developer.

> I interpret this to mean the first option: somebody will `npm install openapi-v2`, then import types from openapi-v2, and make an implementation that conforms to openapi types. Then they will publish a package named pet-parser or something (for something that parses pet information?).

This indeed covers my reasoning.

>If you expect that somebody else will eventually create a package named openapi-v2 or open-api, then I would create a repo for these types and only publish them as openapi-types, if at all.

About the second argument, there is in fact a [repository](https://github.com/OAI/OpenAPI-Specification), that covers the specifications of this open standard. There are already existing products that output such compliant objects, for example, Swagger, and recently even entities like Github migrated to OpenApi to describe its own public APIs.


Before the pull request is closed, I have an additional question, what should happen with the [OpenAPI-v3](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46400) definitions. Should I remove the package?

**Comment by sandersn** [comment]
Yes, please do remove the v3 types.

The OpenAPI repo doesn't publish npm packages, so I think it's fine for you to take the name `openapi-v2`. Then the only difference in usability is `npm install @types/openapi-v2` vs `npm install openapi-v2`.

**Comment by rbuckton** [comment]
@IulianOctavianPreda It also might be worthwhile to discuss this with the maintainers of OpenAPI as well.

**Comment by IulianOctavianPreda** [comment]
Thank you for your help and feedback.
I removed the OpenApi-v3 package from DefinitelyTyped. This is the [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46819)

The definitions are now hosted in the [TypescriptTypes](https://github.com/TsTypes/TypescriptTypes) repository and can be installed using `npm install @tstypes/openapi-v2`, respectively `npm install @tstypes/openapi-v3`

**Pull request closed without merging**
