### PR TITLE
[@types/color] change Color.hex() to Color.hexString()

### PR DESCRIPTION
**Pull request by RayhanHamada**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7df04df6a1a83df5c73bd4e35f824e09099dfeeb/types/color/index.d.ts#L71>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by RayhanHamada** [comment]
somehow Color.hex() is not working (color_1.default(...).hex is not a function), but when i use Color.hexString() it just works.

**Comment by BeeeQueue** [comment]
When the template says to link to documentation or source code explaining the change it means the package's code. Not the types.

It's so we can check that the changed types represents the actual code.

**Comment by RayhanHamada** [comment]
ah my bad, turns out the color package that i'm using is in old version, so the change that i proposed isn't relevant and should not be merged. i'm really sorry, this actually my first real PR. this PR should be closed.

**Comment by BeeeQueue** [comment]
Don't worry about it. 🙂

**Pull request closed without merging**
