### PR TITLE
[perfect scrollbar] updated perfect scrollbar to v1.1

### PR DESCRIPTION
**Pull request by CarbonAtom**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@CarbonAtom Please fix the failures indicated in the Travis CI log.

**Comment by aicest** [comment]
@CarbonAtom should create your PR on original repository, since typing file has been added to [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar/blob/master/types/perfect-scrollbar.d.ts).

**Comment by CarbonAtom** [comment]
Due to some current tooling support and/or various tsconfigs, package typings are not always discoverable or possible. Recommendation noted, but this repo is still preferred in many cases.

**Comment by sandersn** [comment]
@CarbonAtom can you explain the cases where bundled typings don't work as well as Definitely Typed ones? I think @RyanCavanaugh would be interested in making sure any discrepancies are fixed.

**Comment by sandersn** [comment]
For housekeeping purposes, I'm going to close this PR. There should be a lot more activity and knowledge about perfect-scrollbar at the perfect-scrollbar repo.

**Pull request closed without merging**
