### PR TITLE
[webpack] Fix webpack types: use anymatch.Matcher for watchOptions.ignored

### PR DESCRIPTION
**Pull request by pine**
Hello.

I've found the existed types is not strict.I've fixed that.

Thank you.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://webpack.js.org/configuration/watch/#watchoptions-ignored
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by pine** [comment]
I've fixed the CI error 😄

**Comment by johnnyreilly** [comment]
Looking at the webpack `package.json` it looks like it doesn't depend on `anymatch`. Am I missing something?

https://github.com/webpack/webpack/blob/master/package.json

**Comment by pine** [comment]
@johnnyreilly 

Certainly, I think webpack uses anymatch.

This is webpack's watch code. Webpack delegates watch code for watchpack. 
https://github.com/webpack/webpack/blob/2cdf04e14b2f14f97993f26f45ac337ac55d8d2a/lib/node/NodeWatchFileSystem.js#L16

watchpack uses chokidar.
https://github.com/webpack/watchpack/blob/8d839e8b6edb87f9cd8a1ff97028060c4ecc9bee/package.json#L40

chokidar uses anymatch.
https://github.com/paulmillr/chokidar/blob/3ad1ae8db07e988fcb1f7f74687363f3022e5c57/package.json#L46

---

And, I've tried the code. I think webpack depends anymatch.

```
$ node -v
v10.12.0
$ npm -v
6.4.1

$ mkdir tmp-proj
$ cd tmp-proj
$ npm init
$ npm i webpack --save

$ grep anymatch package-lock.json
    "anymatch": {
      "resolved": "https://registry.npmjs.org/anymatch/-/anymatch-2.0.0.tgz",
        "anymatch": "^2.0.0",
```

---

Further, there is webpack official document here.
https://webpack.js.org/configuration/watch/#watchoptions-ignored

screen_shot_2018-11-13_at_17_07_28

---

Thank you.

**Comment by johnnyreilly** [comment]
Thanks!

**Pull request merged**
