### PR TITLE
[spotify-web-playback-sdk] rename Player class.

### PR DESCRIPTION
**Pull request by y-hiraoka**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.spotify.com/documentation/web-playback-sdk/reference/#api-reference
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by y-hiraoka** [comment]
In the current version, we can write `new Spotify.SpotifyPlayer` without compile error in an editor like VSCode.
```ts
const player = new Spotify.SpotifyPlayer( { /*...*/ } );
```

However, the `Spotify.SpotifyPlayer` class is undefined in the browser that loads the SDK.
image

That's the reason for this pull-request.

I've decided that editing the test code is not necessary. Because the test code already uses "Spotify.Player" instead of "Spotify.SpotifyPlayer".

**Comment by y-hiraoka** [comment]
@mraerino I'm sorry again. Please re-review. (related #52460)

**Review by mraerino — APPROVED** [review]
Thanks!

**Review by mraerino — APPROVED** [review]

**Comment by mraerino** [comment]
this might be stuck because the CI no longer executes for outside contributors

**Pull request merged**
