### PR TITLE
[react] Use PropsWithChildren for ExoticComponent

### PR DESCRIPTION
**Pull request by danielkcz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

Just quick, dirty & small change. I am mostly just curious if it's intended for some reason which I am missing.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
If anything we want to get rid of implicit children. At some point we want to type them correctly<sup>1</sup>. Both these changes will enable strict types for e.g. render props APIs.

Edit: Bit more about implicit children: `children` is no special prop that is treated differently by react. Component authors should be explicit about `children` support since it is not always obvious where these are put. Basically in every component that returns a fragment the position of the children is ambiguous and maybe they aren't even handled.

<sup>1</sup> They are currently too wide for host components. They accept functions and objects that will throw at runtime.

**Comment by FredyC** [comment]
@eps1lon Thanks, that makes total sense. I was mostly curious if it's an oversight or what.

I did type children explicitly in cases where it makes sense, especially `children?: never`. I even made an interface `NoChildren` to extend from. Perhaps couple of these could be introduced directly in typings.

**Comment by eps1lon** [comment]
@FredyC I'm in the process of drafting a RFC to get rid of implicit children. Your `NoChildren` interface might come in handy. I'll try to remember pinging you when I propose the change.

**Comment by FredyC** [comment]
@eps1lon These are aliases we have crafted and seems to work quite nicely :)

```ts
/**
 * Single React element (not a component).
 */
declare type ReactNode = null | React.ReactElement<any>

/**
 * Single or multiple React elements.
 */
declare type ReactNodes = ReactNode | ReactNode[]

/**
 * Extend props with specific type for children, eg. string.
 * Use Required<WithChildren<T>> if children are required.
 */
declare type WithChildren<T> = {
  children?: T
}

/**
 * Extend props to forbid any child to be passed to component.
 *
 * Most components don't do anything with children. It's a good
 * practice to inform consumer about it to avoid confusion of children
 * not rendered.
 */
declare type NoChildren = WithChildren<never>

/**
 * Extend props to allow only single react element as child.
 *
 * On rare occasions only a single child might be relevant and component
 * should inform about it to avoid accidental ignoration of multiple children.
 *
 * Use `Required<SingleChild>` if child is required.
 */
declare type SingleChild = WithChildren<ReactNode>

/**
 * Extend props to allow for single, multiple or none react elements as children.
 *
 * Most common to use when children are utilized and passed down to nested components.
 * For advanced patterns like render prop, the `WithChildren<T>` is more appropriate.
 *
 * Use `Required<SomeChildren>` if children are required.
 */
declare type SomeChildren = WithChildren<ReactNodes>

```

**Pull request closed without merging**
