### PR TITLE
[compare-pdf] Add type definitions for compare-pdf

### PR DESCRIPTION
**Pull request by marcdacz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by dhensby** [comment]
If you're the author of the package, why not include your types in the package itself?

**Comment by marcdacz** [comment]
@dhensby yeah tbh I thought this was the only option based on a guide I saw. I'll look up how I can do this directly on my own package. thanks heaps

**Comment by dhensby** [comment]
You can just include it as a index.d.ts (or whatever name you like) in the repo and then add a "typings" prop to package.json that points to the typing file.

**Comment by marcdacz** [comment]
Thanks for that mate. I did just that and based on my tests they seem to work. Published a new version of my package as well. 
Again, thanks heaps mate and keep being awesome!

**Pull request closed without merging**
