### PR TITLE
[Storybook] Update handler to return any.

### PR DESCRIPTION
**Pull request by milesj**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

--------

Handlers may return a value, for example an `onSubmit` that returns a promise. At the moment, `undefined` causes type issues, so just accept `any`.

to: @joscha

### CODE REVIEW

**Comment by milesj** [comment]
Bump @joscha @jicjjang

**Comment by joscha** [comment]
@milesj can you link the respective doc or code piece in the storybook repo please?

**Comment by milesj** [comment]
@joscha It's for the `action` function: https://github.com/storybooks/storybook/blob/master/addons/actions/src/preview/action.js#L5

**Comment by joscha** [comment]
Thanks, it's referring to this part: https://github.com/storybooks/storybook/tree/master/addons/actions#action-decorators

I don't think we can make the changes exactly as you propose as the `HanderFunction` type is also used for the standard non-decorated action, and that one has a return value of `undefined`. They are probably two distinct types, maybe `HandlerFunction` and `DecoratedHandlerFunction`? Also, do you think they can be generic instead of returning `any`?
The last thing that comes to mind is that we should probably update `decorateAction` to `decorate` in v5, wdyt?

**Comment by milesj** [comment]
@joscha Sounds good. I added a new type that uses generic inference. Verified in the test and it returned `boolean`.

**Comment by joscha** [comment]
Thanks for the changes. I am a bit confused as I expected the types to be swapped. The simple `action('bla')` is the one that would still return `undefined`, so it would be the `HandlerFunction` and the decorated one is the one that would produce the different return value that gets passed on, e.g. the `ActionFunction` - what am I missing?

**Comment by milesj** [comment]
@joscha

If `onFoo` is typed as `() => number` and in your story, if you do `onFoo={action('onFoo')}`, this causes a TS type error as `onFoo` expects a return of `number`, *not* `undefined`.

**Comment by joscha** [comment]
> if you do `onFoo={action('onFoo')}`, this causes a TS type error as `onFoo` expects a return of `number`, _not_ `undefined`.

yes, rightfully so, because a simple `action('onFoo')` would actually return `undefined`, not a number. Just because we update the types wouldn't mean the runtime changes, so if your `onFoo` wanted to use an `action`, you'd need to `onFoo={() => { action('onFoo')(); return 123; }}`. Changing the signature to `=> any` only means that we are lying to the type system?

**Comment by joscha** [comment]
I think I got confused about the intent of this PR, sorry about that. If the idea is to change the signature so TS would (incorrectly) accept an `action` function as any function that is not a handler (onclick, etc.) with a `() => undefined` signature, then I think this PR should not be merged.

**Comment by milesj** [comment]
@joscha You're completely right. It's been a long day, I was thinking about this in reverse, hah. I think a good fix would be upstream in storybook, possible something like `action('onFoo', 123)`, where you can define the expected return.

I'll close this for now.

**Comment by joscha** [comment]
> possible something like `action('onFoo', 123)`, where you can define the expected return.

that would actually be really cool and then we can infer the return from the type passed as second param. It would work more like a mock function with a predetermined return value.

**Comment by milesj** [comment]
@joscha Yeah exactly, was thinking the same. I'll tinker around with it tomorrow.

**Pull request closed without merging**
