### PR TITLE
[HOLD] [relay-runtime] Update fragment reference definitions

### PR DESCRIPTION
**Pull request by alloy**
⚠️ This is a breaking change, but alas there’s no other way around it.

As of TS 3.6 an intersection of multiple unique symbols results in
`never`, which means our fragment reference checking is now unsafe.

Depends on https://github.com/relay-tools/relay-compiler-language-typescript/pull/139

### CODE REVIEW

**Comment by alloy** [comment]
cc @djsheldrick

**Comment by alloy** [comment]
So we tried to add `package.json` file that listed the latest version of the `relay-compiler-language-typescript` plugin as a peer dep, so people updating just the DT typings would get a warning about unmatched versions. Alas that doesn’t appear to be possible,

```
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/relay-runtime/package.json should not include field peerDependencies
```

**Comment by kastermester** [comment]
I'm a bit pressured for time right now, but having taken a quick glance at this I think it looks fine. :)

**Comment by alloy** [comment]
@kastermester Thanks! I’ll go forward and self-merge now then, as we need to sync the release with the plugin.

**Review by renanmav — APPROVED** [review]

**Comment by ds300** [comment]
Here's the relevant update to the plugin https://github.com/relay-tools/relay-compiler-language-typescript/pull/139

**Comment by alloy** [comment]
We’re holding-off merging until we know the https://github.com/relay-tools/relay-compiler-language-typescript release process is in a good place. /cc @zephraph

**Comment by alloy** [comment]
Alright, the new plugin version is released, so going to merge this now too.

**Comment by renanmav** [comment]
Which plugin @alloy?

**Pull request merged**
