### PR TITLE
Upgrade to uuid v8

### PR DESCRIPTION
**Pull request by ctavan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/uuidjs/uuid/pull/426
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

----

We are preparing a new major version release of the `uuid` module which will remove a deprecated way of importing the library. This PR should only be merged *AFTER* the new release is out (due within the next few days).

### CODE REVIEW

**Review by LinusU — APPROVED** [review]

**Comment by ctavan** [comment]
Since v8 of `uuid` has been released this one should be released now as well!

**Comment by peterblazejewicz** [comment]
@ctavan 
As can be seen in redacted test, for someone using v8 of @types/uuid this would break the imports, if they are still at v7.
Let me know if you want me to add backward compatible v7 (this would be just a version of the package before this PR with paths versioned),
thx!

**Comment by ctavan** [comment]
Ooops, I keep forgetting about how the versioning in DefinitelyTyped works. I've added the `v7` types back for compatibility.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@ctavan thx for doing this update!

**Review by LinusU — APPROVED** [review]

**Pull request merged**
