### PR TITLE
Updated 'material-ui' to v0.13.1

### PR DESCRIPTION
**Pull request by herrmanno**

### CODE REVIEW

**Comment by use-strict** [comment]
@herrmanno , please make a copy of the old file in the legacy folder.

**Comment by vvakame** [comment]
*material-ui/material-ui.d.ts*

to author(@ngbrown). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by ngbrown** [comment]
@vvakame Looks good.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
