### PR TITLE
node: Updated signature of ChildProcess#send method

### PR DESCRIPTION
**Pull request by avchugaev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle_options_callback>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by achugaev93** [comment]
It's trivial but important update. I rely on your response.

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by achugaev93** [comment]
@rbuckton Can you please tell me, when npm package `@typings/node` will be updated?

**Comment by lmmfranco** [comment]
This is still not published on npm. Any info on that?

**Pull request merged**
