### PR TITLE
Paper Type Definitions

### PR DESCRIPTION
**Pull request by sqwk**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Can you add some actual tests to the tests file?

**Comment by rbuckton** [comment]
@sqwk, please add a test file for your new type definitions.

**Comment by sqwk** [comment]
@rbuckton @paulvanbrenk Neither the original author of the definitions nor me know how to write tests. I was hoping that an open pull request here might inspire someone to chime in. However, if there is some sort of guide on writing tests for DefinitelyTyped, I am more than happy to give it a try …

**Comment by andy-ms** [comment]
There's some advice [here](http://definitelytyped.org/guides/contributing.html), and you can look around for examples. Tests don't have to be terribly long, just enough to catch compile errors.

As a side note, I saw that your file uses function literal syntax for methods, e.g.:
```ts
onFrame: (event: IFrameEvent) => void;
```
Inside a class/interface, there is a more terse representation:
```ts
onFrame(event: IFrameEvent): void;
```

Also, you don't need to start interface names with `I`.

**Comment by mhegazy** [comment]
@sqwk can you please update the PR based on the comments above?

**Pull request merged**
