### PR TITLE
[react-native-video] Add drm props

### PR DESCRIPTION
**Pull request by FourwingsY**
Please fill in this template.

- [x]  Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [react-native-video/Video.js](https://github.com/react-native-video/react-native-video/blob/1eb11ce7b7619a04e65affedcb1ffff4f82f0af3/Video.js#L404)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by FourwingsY** [comment]
Oops. i ran prettier and some quotes and semicolons are modified unintentionally.
Should I revert this changes?

**Comment by bananer** [comment]
@FourwingsY you should revert those unintended changes.

Also, no need to add yourself to the list of owners, the bot will do that.

**Comment by FourwingsY** [comment]
@bananer thanks! changes are minimized.

**Comment by bananer** [comment]
Looks good, just need to make the linter happy:

```Error:` /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react-native-video/index.d.ts:77:1
ERROR: 77:1  no-consecutive-blank-lines  Consecutive blank lines are forbidden
````

**Review by bananer — APPROVED** [review]
I'm not 100% sure whether all of the DRMSettings shouls really be optional, but it agrees with the PropTypes.

LGTM!

**Comment by FourwingsY** [comment]
Those DRM settings are mostly platform-specific. 
[by document](https://github.com/react-native-video/react-native-video/blob/master/DRM.md), type, licenseServer, and headers are common field. but, if we use `getLicense` function, headers and licenseServer field will be ignored.
so the only non-optional drmSettings is type.

**Comment by FourwingsY** [comment]
Ready to merge

**Pull request merged**
