### PR TITLE
[node] Fix missing callback argument for http2session.settings

### PR DESCRIPTION
**Pull request by rkaw92**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v12.x/api/http2.html#http2_http2session_settings_settings_callback - the callback has been in the API since the beginning, I think; this is a type fix

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
LGTM 👍

**Review by peterblazejewicz — APPROVED** [review]
@rkaw92 thanks!

**Comment by rkaw92** [comment]
Ready to merge

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
