### PR TITLE
update(rails__actioncable): Add new methods into the Subscriptions class

### LINKED ISSUE #56909: Add @types/rails__actioncable Subscriptions class method types
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂 Seriously!

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/rails__actioncable@6.1.5` for the project I'm working on.

The `Subscriptions` class for @types/rails__actioncable has quite a bit of missing method types, but below are the couple that I needed for the project I'm currently working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/rails__actioncable/index.d.ts b/node_modules/@types/rails__actioncable/index.d.ts
index 62f3389..0989ecc 100755
--- a/node_modules/@types/rails__actioncable/index.d.ts
+++ b/node_modules/@types/rails__actioncable/index.d.ts
@@ -181,6 +181,10 @@ export class Subscriptions<C = Consumer> {
     readonly subscriptions: Array<Subscription<C>>;
 
     create<M>(channelName: string | ChannelNameWithParams, mixin?: Mixin & M): Subscription<C> & Mixin & M;
+
+    findAll(identifier: string): Subscription[]
+
+    remove(subscription: Subscription): Subscription
 }
 
 /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #56909

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test rails__actioncable`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/rails/rails/blob/main/actioncable/app/javascript/action_cable/subscriptions.js>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by joshuajeschek — CHANGES_REQUESTED** [review]
Hey, I just had a look at your PR and noticed the following:
In [subscription.js](https://github.com/rails/rails/blob/main/actioncable/app/javascript/action_cable/subscriptions.js), line 5:
```js
// Collection class for creating (and internally managing) channel subscriptions.
// The only method intended to be triggered by the user is ActionCable.Subscriptions#create,
// and it should be called through the consumer like so:
//
//   App = {}
//   App.cable = ActionCable.createConsumer("ws://example.com/accounts/1")
//   App.appearance = App.cable.subscriptions.create("AppearanceChannel")
//
// For more details on how you'd configure an actual channel subscription, see ActionCable.Subscription.
```

All those methods you added are intended to be private. Could you add the `private` keyword to the methods? This would mean though, that you need to revert the tests again, or `// $ExpectError`.

What do you even want to achieve by typing these methods? :)

**Comment by martin-badin** [comment]
@joshuajeschek Thanks for your review. I just follow source issue # 56909. When I think about it, it doesn't make sense to me either.

**Review by joshuajeschek — APPROVED** [review]
perfect. I think this solution is good, as it will let the user know that those methods are private.

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
