### PR TITLE
Adds type definitions for 'franc'

### PR DESCRIPTION
**Pull request by wlegate**
Please fill in this template.

- [done] Use a meaningful title for the pull request. Include the name of the package modified.
- [done] Test the change in your own code. (Compile and run.)
- [done] Add or edit tests to reflect the change. (Run with `npm test`.)
- [done] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [done] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [done] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [done] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [done] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [done] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [done] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by p9gehka** [comment]
Hello. I try to use franc with ts and have issue
image

**Comment by wlegate** [comment]
Hey @p9gehka, `frank` is just a reference to the library in this instance… you need to call frank's .detect() method, passing in the desired string

**Comment by p9gehka** [comment]
image
if i use `({default:detect} => detect(value))`, chrome log `detect is not a function`

**Comment by p9gehka** [comment]
It would be great if there was an interface to use it like `import('franc').then((franc: Franc) => {})`
ESLink ask me add type defintinon for lambda arguments
I need to write something like `interface FrancType { all(text: string): [string, number]; } ..then((franc:  FrancType) => {})`
thx alot for your attention:)

**Pull request closed without merging**
