### PR TITLE
Since node v16.15 'default' is acceptable

### PR DESCRIPTION
**Pull request by air2**
Since node v16.15 'default' is acceptable for X509CheckOptions, see https://nodejs.org/docs/latest-v16.x/api/crypto.html#x509checkhostname-options
Also all members are optional, see the code in: https://github.com/nodejs/node/blob/v16.15.1/lib/internal/crypto/x509.js#L65 where the given object properties overrides the defaults.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Neat! 👍

**Comment by peterblazejewicz** [comment]
isn't that applicabl to current Node types version? (not only v16)

**Comment by air2** [comment]
Yes v17,18 and 19 should also support this. I only use v16 because aws does not support 18 yet. So i cannot easily test thisVerstuurd vanaf mijn iPhoneOp 29 nov. 2022 om 19:09 heeft Piotr Błażejewicz ***@***.***> het volgende geschreven:﻿
isn't that applicabl to current Node types version? (not only v16)

**Review by RyanCavanaugh — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge

**Pull request merged**
