### PR TITLE
fix: fixed optional fields when updating a subscription

### PR DESCRIPTION
**Pull request by fightbulc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.paypal.com/braintree/docs/reference/request/subscription/update
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by fightbulc** [comment]
> unamused Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module.

The test file doesnt include any test regarding updating a subscription

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree@latest/))
was missing the following properties:
1. GraphQL
1. version
1. errorTypes
1. exceptions
1. PaymentInstrumentTypes

<details>
<summary>as well as these 4 other properties...</summary>
<p>WebhookNotification, TestingGateway, UsBankAccountVerification, ValidationErrorCodes</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e9851a4972a8b9df6fe0861651e64886e372daba
</p>

**Comment by fightbulc** [comment]
Hey @sheetalkamat, do I need to do anything or do we need to wait on somebody else?

**Review by fightbulc — COMMENTED** [review]
documentation marks it as an optional field: https://docs-prod-us-east-2.production.braintree-api.com/reference/request/subscription/update/node#options.revert_subscription_on_proration_failure

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by fightbulc** [comment]
Ready to merge

**Pull request merged**
