### PR TITLE
Updated Stremio Addon SDK manifest definitions

### PR DESCRIPTION
**Pull request by hyoretsu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/manifest.md
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/stremio-addon-sdk/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d09121cbe536b048affc16c74760f9922ad7edb9
</p>

**Review by sleeyax — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@hoangvvo thanks!

**Comment by hyoretsu** [comment]
I think I need to bump the package version right?

**Comment by sleeyax** [comment]
> I think I need to bump the package version right?

According to [the docs](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) yes, but I'm not sure what should happen in this case as the definitely typed package is currently published as `v1.6.10` (the latest version) already and somehow missing the types you're adding in this PR. Correct me if I'm wrong. 

Semantically speaking we could bump the patch version but then the package is out of sync with its addon SDK version. And I suppose forcefully overwriting the current version isn't possible. :thinking:

**Comment by hyoretsu** [comment]
Pretty sure it isn't possible, yes. I think you'd need to also bump patch version for the addon sdk even though it's a separate package.

**Comment by peterblazejewicz** [comment]
yes, the patch version is managed by DT when publishing to NPM. Package owners have only control on major.minor versioning:
https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

**Comment by sleeyax** [comment]
Gotcha, the major and minor version is still the same so that means we don't need to bump anything in this case.

**Comment by sleeyax** [comment]
Ready to merge

**Pull request merged**
