### PR TITLE
Export named exports from react-select

### PR DESCRIPTION
**Pull request by wedelgaard**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:

- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by claasahl — COMMENTED** [review]
Hi @wedelgaard 

Thanks for the PR. Are you sure that `react-select` (re-)exports anything in [`Select`](https://github.com/claasahl/react-select/blob/master/src/Select.js)?

I tried accessing `defaultProps` (defined [here](https://github.com/claasahl/react-select/blob/master/src/Select.js#L231)). Am I missing something? [sandbox](https://codesandbox.io/s/k0j8nzrzj5)

**Comment by wedelgaard** [comment]
@claasahl I've figured that I could import Props via `react-select/lib/Select`. Initially I wanted to import it directly from `react-select`. Like this `import {Props} from 'react-select'.` The first methods works fine. I guess its a matter of taste if the second method is useful to have?

**Comment by claasahl** [comment]
Hi @wedelgaard <https://github.com/wedelgaard>

I think, it is best to keep the TS definitions as close as possible to the
original `react-select` sources. As `react-select` only exports `Props`
from `react-select/lib/Select` (and not from `react-select`), I would keep
things as they are.

Am Do., 11. Okt. 2018 um 19:56 Uhr schrieb Michael Falck Wedelgård <
notifications@github.com>:

**Comment by wedelgaard** [comment]
@claasahl alright. Then you can just deny this submission :)

**Review by claasahl — CHANGES_REQUESTED** [review]
... as discussed above.

**Pull request closed without merging**
