### PR TITLE
feat(react-gtm-module-v2): add type

### PR DESCRIPTION
**Pull request by YouennPJ**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
It looks like this is your library: <https://github.com/youennpj/react-gtm>

It's probably a better idea to bundle these type definitions there instead of doing them through DefinitelyTyped. That way, you can more easily make updates to types without having to go through the entire DT review process.

**Comment by YouennPJ** [comment]
> It looks like this is your library: https://github.com/youennpj/react-gtm
> 
> It's probably a better idea to bundle these type definitions there instead of doing them through DefinitelyTyped. That way, you can more easily make updates to types without having to go through the entire DT review process.

Hey @MysteryBlokHed ,

Thanks for reviewing my PR! 
I understand we should bundle the types, but could we get this merged for now ? I don't have time right now to make this change and it would be really nice to have typing for my work. This package is a copy of react-gtm-module with the addition of a fix which is why I'm following their approach for now
I promise I'll include the types in the repo and make a PR to remove it from DefinitelyTyped in the future once I can work on that. 

Thanks a ton!

**Comment by MysteryBlokHed** [comment]
> > It looks like this is your library: https://github.com/youennpj/react-gtm
> 
> > 
> 
> > It's probably a better idea to bundle these type definitions there instead of doing them through DefinitelyTyped. That way, you can more easily make updates to types without having to go through the entire DT review process.
> 
> 
> 
> Hey @MysteryBlokHed ,
> 
> 
> 
> Thanks for reviewing my PR! 
> 
> I understand we should bundle the types, but could we get this merged for now ? I don't have time right now to make this change and it would be really nice to have typing for my work. This package is a copy of react-gtm-module with the addition of a fix which is why I'm following their approach for now
> 
> I promise I'll include the types in the repo and make a PR to remove it from DefinitelyTyped in the future once I can work on that. 
> 
> 
> 
> Thanks a ton!
> 
> 

Thanks for clarifying—but I'm not personally a maintainer for this repository, so you'll unfortunately still need to wait for one of them to approve this.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
I'll approve it, but you really should just have the types in a package you own. All you have to do is copy the index.d.ts.

**Comment by YouennPJ** [comment]
@jakebailey @MysteryBlokHed I didn't know it was that simple of a fix. I fixed it in my package.
Thanks for the help guys

**Pull request closed without merging**
