### PR TITLE
[ol] Update to OpenLayers v6.12.0

### PR DESCRIPTION
**Pull request by hanreev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [OpenLayers](https://github.com/openlayers/openlayers), [types-ol](https://github.com/hanreev/types-ol)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
OpenLayers [appears](https://github.com/openlayers/openlayers#typescript-support) to ship its own .d.ts files - why are these needed?

**Comment by sanak** [comment]
@amcasey (CC: @hanreev)
> OpenLayers [appears](https://github.com/openlayers/openlayers#typescript-support) to ship its own .d.ts files - why are these needed?

Well, I commented the reason in the following issue.
https://github.com/hanreev/types-ol/issues/33#issue-1111909425
> :
> but, at this moment, official OpenLayers type definition seems to need more fixes.
openlayers/openlayers#13258

So, even if official OpenLayers ships its own `.d.ts` files, I hope that this `@types/ol` is still necessary until official side becomes stable.

Best regards,

**Comment by amcasey** [comment]
@sanak Ordinarily, it would be impossible to use your own types (e.g. @types/ol) when the package ships its own, since the package's would always be preferred, but the authors [appear](https://unpkg.com/browse/ol@6.12.0/package.json) to have forgotten to include the `types` property in their package.json.

**Comment by amcasey** [comment]
When I install the packages locally, if `ol` is newer than 6.5, these types don't get picked up.  Are you seeing something different, @sanak?  The correct fix would probably be to delete these types entirely, but it's still possible to service (i.e. improve) the types for `ol` 6.5, if that will improve your editing experience.  Updating to 6.12 doesn't make sense though.

**Comment by sanak** [comment]
@amcasey
Okay, I missed that `ol` type definitions are picked with `@types/ol`...
(I checked from VSCode type link.)

**Comment by amcasey** [comment]
Please feel free to open a new PR improving the 6.5 types.  For newer versions, I think the best approach would be to work with the OpenLayer maintainers to improve their in-box types.  Thanks!

**Pull request closed without merging**
