### PR TITLE
Non-Instantiated highcharts definitions

### PR DESCRIPTION
**Pull request by subash-a**
Improvement to existing type definition of Highcharts
- Using Ghost modules based on discussion in Issue #10597
- Moved all global interfaces into a namespace
- Created a __Highcharts namespace for using in dependent files
- Changed references in dependent files and tests

This PR was created based on the discussion on #11377 and @andy-ms suggestion that since the PR does not contain anything `types-2.0` specific it should be targeted at master.

### CODE REVIEW

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by subash-a** [comment]
@mhegazy done with addressing the merge conflicts

**Comment by mhegazy** [comment]
@scatcher, @mc-suchecki, @damianog, @baltie and @DavidKDeutsch can you please review this change?

**Comment by mc-suchecki** [comment]
LGTM :+1:

**Comment by baltie** [comment]
@vvakame I did the mistake of leaving feedback only in the original discussion, asking @subash-a for details. I though you would hold off merging until you got feedback from at least @damianog and/or me. 

The problem is, I'm not happy with this PR because I really wouldn't like to have the double underscores all over the place. In C/C++, it implies something internal to the compiler. In Python, the "magic names" start with double underscore. In Javascript, it's usually something browser specific. And with legacy typings in TypeScript, there are now going to be __Highcharts everywhere.

So is it possible to revert this until @subash-a has come up with a better solution?

**Comment by baltie** [comment]
I'm happy with the change, after discussing it with @subash-a, though I wish the improvements to documentation and other things (I think?) were in their own PR. :)

**Comment by inad9300** [comment]
Sorry, could someone explain to me a) why the __Highcharts namespace was introduced with that name and b) how the types should be used now, other than (e.g.) __Highcharts.Options, which makes no sense?

**Comment by andy-ms** [comment]
@inad9300 The module form `import { Animation } from "highcharts";` should be preferred. Could you make a PR to change this?

**Comment by myitcv** [comment]
@andy-ms - what needs changing here? 

This PR was introduced off the back of a conversation in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10597

**Comment by andy-ms** [comment]
I'll make a PR to do it after this is merged into `types-2.0`.

**Comment by andy-ms** [comment]
Has anyone tried using the `"highcharts"` module in their code? The global variable is used in the tests instead. It's declared at the bottom of `highcharts/index.d.ts` with `export = __Highcharts;`. When I do `require("highcharts")` in node I get a function object with no enumerable properties.

**Comment by RandScullard** [comment]
@andy-ms I believe I am seeing a similar issue. I'm trying to use Highcharts in a typescript 2.0 project with webpack, and with this new version, webpack doesn't even include the Highcharts library. The result is an undefined reference for Highcharts.

When I reverted back to @types/highcharts@4.2.37, it started working again. The key difference seems to be:

4.2.37:

    declare module "highcharts" {
        export = Highcharts;
    }

4.2.38:

    declare module "highcharts" {
        export = __Highcharts;
    }

By which I mean, if you take 4.2.38 and just change this part back to the way it was if 4.2.37 (keeping all the other 4.2.38 changes), it works. Since `Highcharts` was changed to `__Highcharts` in so many places, I have to wonder if it got changed in one too many places...

**Comment by tedcurrent** [comment]
This is indeed broken. Has anyone figured a workaround for this? I am trying to include Highstock in a project, and I am unable to do so because the new Highcharts definition is broken (which is needed for Highstock..). Any way to get an earlier version of Highstocks definition?

**Comment by RandScullard** [comment]
@subash-a, @mc-suchecki, @baltie: Could someone who is familiar with this change please take a look at the issue described in the previous three comments and weigh in?

**Comment by andy-ms** [comment]
I notice that the `highstock` type declaration consists solely of interface declarations and augmentations to `interface JQuery`. Is this because no importable "highstock" module exists? Is it just a jquery plugin?

**Comment by tedcurrent** [comment]
@andy-ms: highstock is importable via `highcharts/highstock`, however the module declaration has been omitted from the typings. Hoping for someone with familiarity with this change to fix it, but I might add a PR if we get no comment on this.

**Pull request merged**
