### PR TITLE
[Memory-fs] Update for webpack v5 compatibility 

### PR DESCRIPTION
**Pull request by gita-vahdatinia**
Please fill in this template.
Match definition for OutputFileSystem which previously was compatible in webpack v4. 
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/webpack/blob/master/types.d.ts
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by gita-v** [comment]
@peterblazejewicz Whenever you have a chance can you please tal

**Review by peterblazejewicz — COMMENTED** [review]
1) can you please do not rename params from context-aware to arg0, arg1, etc?
2) where some of those methods come from in the package source? (say `dirname`)

**Comment by gita-v** [comment]
Sorry,, I opened issue with webpack and they resolved the issue on their end -- https://github.com/webpack/webpack/issues/12400

**Comment by peterblazejewicz** [comment]
no worries, thx for the head-ups!

**Comment by gita-codaio** [comment]
@peterblazejewicz If you could take a look again please, I had to modify because their fix did not fix the issue -- 
Fixed the argument names and the dirname is inputfilesystem requirement in webpack v5 -- https://github.com/webpack/webpack/blob/a2e326129c65a22f8e3f130680cb00b24504ee14/types.d.ts#L3898

Also, the CI test failed due to javascript heap issue -- do you know what might be the fix to this?

**Comment by peterblazejewicz** [comment]
> Also, the CI test failed due to javascript heap issue -- do you know what might be the fix to this?

MS folks are working on this trying to figure out the rouge package, thx!
It will be fixed soon

**Comment by peterblazejewicz** [comment]
@gita-codaio I believe there is not a single line in the tests that covers those methods usage.
Would you mind adding ones? at least to cover your changes (can be like in the readme-driven-dev)

**Pull request closed without merging**
