### PR TITLE
Added typings and tests for core-js

### PR DESCRIPTION
**Pull request by rbuckton**
Adds typings and tests for [core-js](https://github.com/zloirock/core-js/).

### CODE REVIEW

**Comment by vvakame** [comment]
@rbuckton thank you for your contributions.
please fix travis ci failed. https://travis-ci.org/borisyankov/DefinitelyTyped/builds/61822901

**Comment by rbuckton** [comment]
@vvakame I've updated and the Travis CI build looks to have passed.

**Comment by vvakame** [comment]
*core-js/core-js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/core-js
  * http://bower.io/search/?q=core-js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (core-js/core-js-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@rbuckton thanks mate!

**Pull request merged**
