### PR TITLE
Add type definitions for passport-unique-token

### PR DESCRIPTION
**Pull request by ArcanoxDragon**
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

Because of the similarity of the two packages, these typings were somewhat based off of the already defined `passport-local` types in this repository. Types have been tested in my own project and work correctly.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Can you explain why you don't have lints on?

**Comment by briman0094** [comment]
I couldn't get the module to compile when using the `tslint.json` file generated by `dts-gen`. I was getting errors about undefined options which appeared to have been inherited by the default DTS lint file. I can try again if it's needed; I don't recall seeing any lint files in `passport-local` which `passport-unique-token` is directly based off of (both the module itself and the typings).

**Comment by DanielRosenwasser** [comment]
> I couldn't get the module to compile when using the tslint.json file generated by dts-gen

Could you elaborate on those errors?

**Comment by andy-ms** [comment]
This should definitely have a `dtslint/dt.json` containing `{ "extends": "dtslint/dt.json" }`. Would have caught all of @DanielRosenwasser's comments. Even if there are errors, push it so we can see any errors you're still getting and help out.

**Comment by yuit** [comment]
Thanks for your contribution. This PR has unaddressed comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by briman0094** [comment]
Sorry, I was away from my project for a little while and wasn't keeping up on notifications. I will open a new PR once I fix the lint file.

How did `passport-local` get accepted when it has so many issues? I based my types very closely off of it since the two modules are so similar themselves.

**Pull request closed without merging**
