### PR TITLE
oidc-provider: add args to default resource indicator

### PR DESCRIPTION
**Pull request by slavab89**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/panva/node-oidc-provider/blob/v8.4.5/lib/helpers/defaults.js#L195
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/oidc-provider/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1d7156effc1386191290f57ad133d61a6f676b61
</p>

**Review by panva — APPROVED** [review]

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Need more info - what does the linked line of code have to do with this change?

```ts
return base64url.encodeBuffer(bytes);
```

**Comment by slavab89** [comment]
> Need more info - what does the linked line of code have to do with this change?
> 
> ```ts
> return base64url.encodeBuffer(bytes);
> ```

@RyanCavanaugh Sorry, it seems that was a change in the referenced file so the line moved. I've fixed the [link](https://github.com/panva/node-oidc-provider/blob/v8.4.5/lib/helpers/defaults.js#L195) in the description.
The change is relevant for the `async function defaultResource(ctx, client, oneOf) {` function
```
async function defaultResource(ctx, client, oneOf) {
  // @param ctx - koa request context
  // @param client - client making the request
  // @param oneOf {string[]} - The OP needs to select **one** of the values provided.
  //                           Default is that the array is provided so that the request will fail.
  //                           This argument is only provided when called during
  //                           Authorization Code / Refresh Token / Device Code exchanges.

  if (oneOf) return oneOf;
  return undefined;
}
```

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/oidc-provider/oidc-provider-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d031ef5ceec95db40e22c56b6ed865a08cde0bb0
</p>

**Review by panva — APPROVED** [review]

**Comment by slavab89** [comment]
Ready to merge

**Pull request merged**
