### PR TITLE
add `extraData` prop to FlatList and SectionList

### PR DESCRIPTION
**Pull request by yuche**
see:
https://facebook.github.io/react-native/docs/sectionlist.html#props
https://facebook.github.io/react-native/docs/flatlist.html#props

### CODE REVIEW

**Comment by mhegazy** [comment]
@alloy @systemride @iRoachie @gyzerok @MNBuyskih @evollu @newyankeecodeshop @yuche @ligaz @sarahscott @jasonhealy @DanielRosenwasser @danielearwicker @cailenmusselman can you please review

**Comment by mhegazy** [comment]
@yuche can you address the lint errors please.

**Comment by iRoachie** [comment]
@yuche Extra whitespace on line 3437. Other than that, it's good

**Review by iRoachie — APPROVED** [review]

**Comment by newyankeecodeshop** [comment]
Nice. At some point we should probably create an interface for `VirtualizedListProps` that can be shared by both FlatList and SectionList

**Pull request merged**
