### PR TITLE
Reorganize React definitions

### PR DESCRIPTION
**Pull request by jbrantly**
This is a first pass at implementing #5221. This cuts the number of files from 4 to 2 and reduces the "duplicate" definitions from 3 to 2 (both in the same file, `react.d.ts`).

The number of duplicate definitions can be further reduced once React v0.14 is released.

cc @vsiao @pspeter3 @RyanCavanaugh

### CODE REVIEW

**Comment by jbrantly** [comment]
This PR was originally meant to not make any real changes to the current functionality (no bugfixes, additions, etc). However, there is one issue that came up which I think we should try to go ahead and bandaid.

In fb0b124 an indexer was added to CSSProperties. I believe this was to fix the new strict object literal checking in TS 1.6 which has been causing a lot of PRs lately for missing CSS properties. It did, however, have a side effect of no longer allowing something like this:

```javascript
var style = { whatever: '' };
<div style={style} />
```

The above will throw `Index signature is missing`. Note that `<div style={{ whatever: '' }} />` works fine.

Changing the indexer from `string | number | boolean` to `any` fixes this problem in TS 1.6. However, TS 1.5 is still affected and the workaround is what is used in the tests:

```
var style: React.CSSProperties = { whatever: '' };
```

In any case, I've updated this PR to change the indexer to `any` which at least fixes TS 1.6.

**Comment by RyanCavanaugh** [comment]
Just to clarify the indexer thing: another new behavior in 1.6 is that an indexer of type `any` does not require an indexer on the source type in order to be assignable. In other words:

```ts
let x = { whatever : '' };
let y: { [s: string]: any };
y = x; // OK in 1.6, error in 1.5
```

**Comment by pspeter3** [comment]
Out of curiosity, what is the difference between module and namespace? I'm excited to have fewer files.

**Comment by jbrantly** [comment]
@pspeter3 It's part of the "internal modules => namespaces, external modules => modules" renaming. `namespace` takes the place of `module` for namespaces (and only namespaces). However, for backward compatibility `module` still works for both namespaces and modules.

In other words:

```typescript
declare namespace Foo { } // works, namespace
declare namespace "Foo" { } // doesn't work
declare module Foo { } // works, namespace
declare module "Foo" { } // works, module
```

**Comment by pspeter3** [comment]
That's awesome and makes the distinction clearer.

**Comment by vvakame** [comment]
um? can I merge this PR?

**Comment by pspeter3** [comment]
I feel favorably to it

**Comment by vvakame** [comment]
:+1: 
@vsiao @RyanCavanaugh Is the same opinion?

**Comment by jbrantly** [comment]
I just made some (I think non-controversial) changes.

1. Renamed react-namespace back to react-global.d.ts as it originally was. No real point in changing the name and would just cause issues with people upgrading. Also I messed up the original rename and forgot the `.d`. Whoops.
2. Added some tests for the global version. Basically just a copy-paste of `react-tests.ts` but removing the import statement.

**Comment by johnnyreilly** [comment]
If @vsiao @RyanCavanaugh have no objections shall we look to merge?

**Comment by johnnyreilly** [comment]
Merged.  Thanks for your work @jbrantly

**Pull request merged**
