### PR TITLE
New definition package thunderbird-webext-browser: the Thunderbird WebExtensions API

### PR DESCRIPTION
**Pull request by JimDanner**
Please fill in this template.

- [✅] Use a meaningful title for the pull request. Include the name of the package modified.
- [✅] Test the change in your own code. (Compile and run.)
- [✅] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [✅] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [✅] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [✅] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [✅] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [✅] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [✅] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [✅] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [➡️] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules. **I had to add a rule to deal with functions like `browser.messages.delete()` which use reserved words in JavaScript as their names. The only workaround seems to be to export everything explicitly. See [my search for alternatives](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/master/doc/Reserved%20words.md)**
- [✅] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Please update generator script and remove the line:
https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/master/src/index.ts#L56

```ts
// TypeScript Version: 3.4
```
it's a dead code, the versions used here is now at 4.2 and the declaration files does not depend on anything specific AFAIK from TS features.

**Comment by peterblazejewicz** [comment]
Also we advice to put inline rules excluding tslint/eslint rules, so:
```ts
// tslint:disable:strict-export-declare-modifiers
```

**Comment by JimDanner** [comment]
Hi @peterblazejewicz, thanks for your comments.

Do DefinitelyTyped declaration files work without any TypeScript version indication? The [dtslint docs](https://github.com/Microsoft/DefinitelyTyped-tools/tree/master/packages/dtslint#specify-a-typescript-version) say line 5, with a version indication, is required to test for versions newer than 2.0.

> Also we advice to put inline rules excluding tslint/eslint rules, so:
> 
> ```ts
> // tslint:disable:strict-export-declare-modifiers
> ```
> 
> thus removing the need to change default configuration

Regarding this advice: I agree it's a bad idea to switch off an entire linting rule for one or two statements. But in this case, *every* declaration is an `export` statement. This would mean adding the inline rule about 2000 times, making the file 132 kB (14%) larger.

If possible, in this case I'd prefer to keep a rule in `tslint.json`.

**Comment by jakebailey** [comment]
> Do DefinitelyTyped declaration files work without any TypeScript version indication? The [dtslint docs](https://github.com/Microsoft/DefinitelyTyped-tools/tree/master/packages/dtslint?rgh-link-date=2023-03-12T21%3A15%3A02Z#specify-a-typescript-version) say line 5, with a version indication, is required to test for versions newer than 2.0.

Yes, they work fine. We should update that doc to reflect our actual support window, which is documented in this repo's README: https://github.com/DefinitelyTyped/DefinitelyTyped#support-window

**Comment by jakebailey** [comment]
A final question; this is forked from `firefox-webext-browser`; is there an opportunity to share types?

**Comment by JimDanner** [comment]
There is certainly some overlap; I would guess that around half of `firefox-webext-browser` is functionally equivalent with around one quarter of this package.

If the common parts would have to be split off into a common dependency, some co-ordination may be required, as I also made some improvements and I was forced to do some things differently. A quick overview of differences:

1. _Structure_. `firefox-webext-browser` has namespace declarations next to each other: `declare namespace browser.i18n{...}`, then `declare namespace browser.runtime {...}`. I nested them: `declare namespace browser {namespace i18n {...} ...}`. This is because I'm working around various quirks of IDEs: WebStorm needs namespaces to be declared as variables in order to display their JSDoc comments; VS Code concatenates the JSDoc descriptions of all `browser.` sub-namespaces into the documentation of `browser` if they're not nested.
2. _Root namespace duplication_: Firefox puts everything under `browser`, but Thunderbird also has the alias `messenger` and even [seems to prefer](https://webextension-api.thunderbird.net/en/latest/#thunderbird-webextension-api-documentation) its use.
3. I solved several _style issues_; as you can see, `firefox-webext-browser` has a lot of exclusions in its `tslint.json`: for long lines, problems with function overrides, namespace merges etc.
4. The _reserved-words issue_: in contrast to Firefox, the Thunderbird extension API has items called `delete` and `import`. Try declaring a function by that name in an ambient namespace declaration... So the workaround is declaring it as `_delete` and then `export {_delete as delete}`. But then VS Code fails to pick up all the other items in that namespace... So I have to export *everything*. Not sure the `firefox-webext-browser` developer will be cheering about that.

**Review by jakebailey — APPROVED** [review]
LGTM as much as a 22 thousand line PR can look good.

**Comment by JimDanner** [comment]
Ready to merge

**Pull request merged**
