### PR TITLE
Fix typo: change paramter to parameter.

### PR DESCRIPTION
**Pull request by antonhalim**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Hello, this is my first PR here. I haven't seen an open PR for this issue/typo. While developing on VS Code, I found what I believe as a typo `paramter` coming from this repo as the source of the IntelliSense documentation. Please let me know if its a false alarm. And/or anything I can update to have this to be fixed.

Thanks!

screen shot 2018-10-14 at 9 59 47 pm
`paramter` typo in the second line of the paragraph.

### Packages List

Okay, so I figured my PR is affecting some packages listed here. I am not sure if I need to increase version number, but if I need to, please let me know.
Some folks already approved here, feel free to edit and check here or says its approved, then I'll update the list.

- [x] animejs/index.d.ts
- [x] chrome-apps/index.d.ts
- [ ] commangular/commangular-mock.d.ts
- [ ] dojo/dijit.d.ts
- [ ] dojo/dojox.widget.d.ts
- [ ] durandal/index.d.ts
- [ ] dwt/index.d.ts
- [ ] dwt/v12/index.d.ts
- [ ] fabric/fabric-impl.d.ts
- [ ] gapi.client.dfareporting/index.d.ts
- [ ] i18next-browser-languagedetector/v0/index.d.ts
- [ ] node/index.d.ts
- [ ] node/v0/index.d.ts
- [ ] node/v4/index.d.ts
- [ ] node/v6/index.d.ts
- [ ] node/v7/index.d.ts
- [ ] node/v8/index.d.ts
- [ ] node/v9/index.d.ts
- [ ] p5/lib/addons/p5.sound.d.ts
- [ ] restify-plugins/index.d.ts
- [ ] restify/index.d.ts
- [ ] restify/v5/index.d.ts
- [ ] scroll-into-view/index.d.ts
- [ ] tough-cookie/index.d.ts
- [ ] universal-router/index.d.ts
- [ ] webidl2/index.d.ts

### CODE REVIEW

**Review by A-Babin — APPROVED** [review]
Corrections for animejs are okay.

**Review by fredrikhr — APPROVED** [review]
chrome okay 👍

**Review by bsvensson — CHANGES_REQUESTED** [review]
For types/arcgis-js-api/index.d.ts, the changes to the `paramter` is fine, but there's also a number of other changes (including trailing whitespace). For this reason, I give it 👎 .

We plan to fix both the `paramter` and trailing whitespace issues for `types/arcgis-js-api/` in the original source files (not in this repo), then update DefinitelyTyped. Thank you for bringing this to our attention.

**Comment by antonhalim** [comment]
Thanks all, thanks @bsvensson for the feedback, to that then I will remove my changes on `arcgis-js-api` file. Sorry for the whitespace issue, I was debating whether to leave it there or not since it increases changed file. Now, I know what to do 😄

**Review by niikoo — APPROVED** [review]
Thank you for helping to keep the quality up.
The code looks okay for me.

**Comment by antonhalim** [comment]
@niikoo thanks, are you approving the changes for a specific package?

**Comment by antonhalim** [comment]
@bsvensson Can you approve changes I made? Or can anyone approves and merge this PR?

**Review by eps1lon — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by bsvensson — APPROVED** [review]
"Approved" - since the "arcgis-js-api" changes were removed from this PR.

**Comment by niikoo** [comment]
I've included the chrome-apps change in my latest PR.

**Comment by antonhalim** [comment]
@niikoo I'll remove chrome-apps changes and reopen a PR. if you can approve on the new PR, that will be greatly appreciated.

**Pull request closed without merging**
