### PR TITLE
[@types/react] Resolve https://github.com/microsoft/TypeScript/issues/40511

### LINKED ISSUE #40511: super keyword strikethrough per erroneous deprecated setting in .js files since Aug 10 update
- VSCode Version: 1.49.0
- OS Version: WindowsNT x64 10.0.19041

Steps to Reproduce:

1. Create a .js file with this content:
```
import React from 'react'; // does not matter if this line is here or not

class Test  {
    constructor(props) {
        super(props);
    }
}
```
2. Add extends React.Component to class Test, like so:
`class Test extends React.Component {`

3. The word 'super' then gets striked through and hovering over seems to say it is deprecated for typescript, but this is not a typescript file. It does not affect the code but is confusing many people. Working around it by disabling the "Editor: Show Deprecated" setting, but would prefer to be able to enable that setting. This has only been happening since the VS Code update on August 10, 2020 (yesterday).

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by davegregg**
Resolve https://github.com/microsoft/TypeScript/issues/40511

PROBLEM:

The final overload here marks the second argument ("context") as
optional. This optional Legacy Context argument is deprecated, so
the overload is correctly marked as deprecated.
However, because the deprecated argument is itself optional, even
perfectly acceptable `super(props)` calls in plain JS are flagged
as deprecated.

SOLUTION:

Modify the first overload so that it accepts props simply of P.
The "context" argument of the second overload should no longer
be marked as optional.

After testing in VS Code, this resolves the incorrect behavior,
while preserving the deprecation warning from JSDocs when
providing a second parameter.

```js
constructor(props: Readonly<P> | P);
/**
* @deprecated
* @see https://reactjs.org/docs/legacy-context.html
*/
constructor(props: P, context: any);
```

- [ ✔️ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ✔️ ] Test the change in your own code. (Compile and run.)
- [ ❌ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ✔️ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ✔️ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ✔️ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ✔️ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/microsoft/TypeScript/issues/40511

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## hopscotch ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hopscotch@latest/))
was missing the following properties:
1. getCalloutManager
1. getCurrTarget
1. getSkippedStepsIndexes
1. refreshBubblePosition
1. unregisterHelper

<details>
<summary>as well as these 4 other properties...</summary>
<p>invokeHelper, setCookieName, setRenderer, setEscaper</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b49500d2bd846b3950ab9ac3d3b40f138ff28fe0
</p>

**Review by bsdahl — APPROVED** [review]

**Comment by derwaldgeist** [comment]
I am getting this deprecated warning when editing ES6 React files in VS Code (no Typescript involved). How can I get rid of this?

**Comment by weeix** [comment]
> I am getting this deprecated warning when editing ES6 React files in VS Code (no Typescript involved). How can I get rid of this?

In my case, I upgraded @types/react package to v16.9.51 and didn't get the warning anymore.

**Comment by derwaldgeist** [comment]
@weeix: I don't have this package in my project. Is there a way to upgrade it for VS Code only?

**Comment by weeix** [comment]
@derwaldgeist Another packages might depend on it (e.g. `@material-ui/core`). Maybe try running `npm i @types/react`?

**Comment by davegregg** [comment]
@derwaldgeist It's easy to do this until you get the update organically:

Open VS Code and navigate to a class-based React component. Waiting until the "Initializing JS/TS language features" loading message in the Status Bar at the bottom goes away. Then hold CTRL while hovering over `super`: you'll see the word turn into a link. Clicking this will take you to the type definition file for React.

Find this line: `constructor(props: Readonly<P>);` and change it to: `constructor(props: Readonly<P> | P);`

Find this line: `constructor(props: P, context?: any);` and remove the question mark.

These two changes are what my commit does. Save this file and restart VS Code. Your change is not permanent and will be overwritten with the next update which VS Code installs to @types/react (even if the update does not affect those lines).

**Comment by derwaldgeist** [comment]
@davegregg Thanks!

**Pull request merged**
