### PR TITLE
[@types/chrome] scripting.StyleOrigin and ExecutionWorld are enums

### PR DESCRIPTION
**Pull request by danielhjacobs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/docs/extensions/reference/api/scripting#type-ExecutionWorld and https://developer.chrome.com/docs/extensions/reference/api/scripting#type-StyleOrigin

### CODE REVIEW

**Comment by danielhjacobs** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69776

**Comment by danielhjacobs** [comment]
Perhaps this should also be changed for https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/scripting.d.ts#L157

**Comment by gabritto** [comment]
This is technically a breaking change on a popular package, and I don't see a strong enough reason to make this change.

**Comment by danielhjacobs** [comment]
Okay, will I permanently need to keep the hack at https://github.com/ruffle-rs/ruffle/blob/master/web/packages/extension/src/utils.ts#L22-L29 so TS won't complain about the check at https://github.com/ruffle-rs/ruffle/blob/master/web/packages/extension/src/background.ts#L14 ?

**Comment by danielhjacobs** [comment]
Since FF just added support for ExecutionWorld MAIN in FF beta I can imagine a lot of people adding such a check to not break their Firefox extensions on older versions of Firefox by only adding the scripts on browsers with MAIN ExecutionWorld support.

**Comment by gabritto** [comment]
@danielhjacobs Could you add a test to this PR showing what sort of code can't be written today and that your PR would enable?

**Pull request closed without merging**
