### PR TITLE
Add loadFileConfigs function

### PR DESCRIPTION
**Pull request by jhenaoz**
@RWander
The node-config update and add this library that i required for my project, see the new docs here: https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities

### CODE REVIEW

**Comment by jhenaoz** [comment]
@RyanCavanaugh help me with this PR, thanks

**Comment by vvakame** [comment]
*config/index.d.ts*

to author (@RWander). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by yuit** [comment]
@jhenaoz Thank you for the PR. Just one quick question should the configDir parameter be option  [here](https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#loadfileconfigsdirectory)
Also could you add a test ?

**Comment by jhenaoz** [comment]
@yuit as the config documentation say about this method:
If no directory is given, reads the standard config directory and parses NODE_CONFIG, so the configDir param is optional, and if there is no param take the 'rootPath/config' path by default.

**Pull request merged**
