### PR TITLE
node: add setLocalWindowSize to node/http2

### PR DESCRIPTION
**Pull request by ZYSzys**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/dist/latest-v15.x/docs/api/http2.html#http2_http2session_setlocalwindowsize_windowsize>

A new API [`http2session.setLocalWindowSize(windowSize)`](https://nodejs.org/dist/latest-v15.x/docs/api/http2.html#http2_http2session_setlocalwindowsize_windowsize) was introduced in node `v15.3.0`.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by peterblazejewicz** [comment]
So it fails because upstrema change to Express static core types, that impact `morgan` tests, that impact `node`. (see detailed log), has no relation to that change at all.

**Comment by ZYSzys** [comment]
Look like CI build failed due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50061

**Review by peterblazejewicz — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by ZYSzys** [comment]
Ready to merge

**Pull request merged**
