### PR TITLE
[chart.js] Add return type null to NestedTickOptions callback

### PR DESCRIPTION
**Pull request by lekoaf**
I'm actually having a hard time finding a reference of the `callback` function in the Chart.js documentation but through trial and error I can say that giving the user the ability to return `null`, you can let them have the option to not display that particular tick in the axis.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by adripanico — CHANGES_REQUESTED** [review]
I don't feel comfortable approving this without documentation, code reference or proper demo to test it.

**Comment by lekoaf** [comment]
> I don't feel comfortable approving this without documentation, code reference or proper demo to test it.

You are quite right. I didn't feel really comfortable putting this up as a PR either since I couldn't find any documentation. But I need this change for a project I'm working on. I'll dig trough the source code and see if I can find something.

**Comment by adripanico** [comment]
> > I don't feel comfortable approving this without documentation, code reference or proper demo to test it.
> 
> You are quite right. I didn't feel really comfortable putting this up as a PR either since I couldn't find any documentation. But I need this change for a project I'm working on. I'll dig trough the source code and see if I can find something.

Maybe you can create a demo in codepen or similar to demonstrate your point.

Thanks

**Comment by KentarouTakeda** [comment]
I think we don't need this cahnge.
We can use `""` instead of `null`.

Typescript should be as null-safe as possible.

**Comment by lekoaf** [comment]
@KentarouTakeda @adripanico 
I created a little code sample to show what I mean.
https://codesandbox.io/s/gallant-star-8dyyx?fontsize=14&hidenavigation=1&theme=dark

Returning `""` keeps the line. Returning `null` also removes the line.

**Comment by lekoaf** [comment]
Returning `undefined` does the same thing as `null`.

**Comment by Marcoru97** [comment]
The docs says that null or undefined hides the line.
https://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats
I think it is intended to do it this way.

**Comment by lekoaf** [comment]
> The docs says that null or undefined hides the line.
> https://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats
> I think it is intended to do it this way.

Excellent! You found it. I'll add `undefined` as well when I find some time.

**Comment by adripanico** [comment]
> I think we don't need this cahnge.
> We can use `""` instead of `null`.
> 
> Typescript should be as null-safe as possible.

Why?

**Comment by lekoaf** [comment]
Seems like i will need to update this either way. Since this function can be on both X and Y axis, it can contain both numbers and strings. I’ll fix! :)

**Comment by KentarouTakeda** [comment]
@lekoaf @Marcoru97 
Oh, I didn't know.  Thank you for teaching me. 
In this case, it is necessary.  sorry.

**Review by KentarouTakeda — APPROVED** [review]
LGTM

**Comment by lekoaf** [comment]
@adripanico Could you approve this please?

**Review by adripanico — APPROVED** [review]

**Pull request merged**
