### PR TITLE
[@types/struct] New PR to increase the NPM version

### PR DESCRIPTION
**Pull request by Rechdan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Rechdan** [comment]
@benallfree lets try to merge this one and see if the version increases?

**Comment by benallfree** [comment]
@Rechdan did you really intend to become an owner of this type definition? That's how it will treat you. I don't see any other changes, what is it about adding an owner that would cause it to publish?

**Comment by Rechdan** [comment]
@benallfree not an owner, just contributor hahaha

**Review by benallfree — APPROVED** [review]
Approving for attribution. The package 0.0.2 has already been published without this change though.

**Comment by Rechdan** [comment]
@benallfree I'm closing this PR, thanks!

**Pull request closed without merging**
