### PR TITLE
Rename numeral's language function to locale

### PR DESCRIPTION
**Pull request by vhfmag**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

As of the last Numeral version (2.0.4) the language method has been renamed to locale but the type definitions didn't keep up with it (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/137880).

### CODE REVIEW

**Comment by vbortone** [comment]
👍

**Comment by andy-ms** [comment]
> Increase the version number in the header if appropriate.

First line should now say `// Type definitions for Numeral.js 2.0`.

**Comment by mhegazy** [comment]
@vhfmag can you please update the version.

**Comment by zhengbli** [comment]
@vhfmag gently ping

**Comment by jramsay** [comment]
@DanielRosenwasser:  it looks like you updated the version number with the merge - thanks! There is a build issue (likely just a bad merge) now though as NumeralJSLanguage is still being used but it looks like this has been renamed to NumeralJSLocale in the merge - can you confirm and fix?

**Comment by yuit** [comment]
@vhfmag Thanks for your contribution. This PR has failing CI and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
