### PR TITLE
[New] add types for `gopd`

### PR DESCRIPTION
**Pull request by ljharb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by ljharb** [comment]
cc @exe-boss since this was extracted from your es-abstract types

**Review by sandersn — CHANGES_REQUESTED** [review]
The types look OK, but why not ship them with the package?

**Comment by ljharb** [comment]
@sandersn because that conflates semver of the types with semver of the real code; types shouldn't ever be shipped with the package imo.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
I assumed that a new package that got types created at the same time was written in Typescript. Makes more sense to have the types here if it's not.

Do you have a link to a longer explanation of the types-code semver idea? I don't understand the reasoning.

**Comment by ljharb** [comment]
@sandersn i don't have a longer link. The issue is that there's no guarantee the types are a 1:1 match with the code - especially since TypeScript is incapable of fully describing JavaScript semantics - which means I might have to make a breaking change to the types that is only a patch to the real code, or, a breaking change to the code that is a patch for the types. In either of those scenarios, there's two different types of change being made - and forcing an unnecessary major bump is almost as bad as making a breaking change without a major bump.

When TS gains the capability to be an actual superset of JavaScript, I may reevaluate this stance, but it's got a long list of gaps to close first.

**Comment by ljharb** [comment]
Ready to merge

**Pull request merged**
