### PR TITLE
fix(react): Remove unstable APIs

### LINKED ISSUE #44886: [@types/react] Remove calculateChangedBits from createContext
Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag

----

I've just noticed `createContext` has a second argument in the type definition. This doesn't make sense and is misleading. That second argument is an unstable API that will likely be removed. It's called `unstable_calculateChangedBits` but the definition just calls it `calculateChangedBits`. What's worse, VS Code autocomplete offers to supply it. Could we remove the unstable API from typings or move this overload to the experimental definition?

### PR DESCRIPTION
**Pull request by eps1lon**
If you came here because this broke type-checking for you: You were probably using unstable, undocumented APIs. If you still want to use them without supressing type checking, you can add them back via [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation):

<details>
<summary>unstable APIs of `react`</summary>

```ts
import * as React from 'react';

declare module 'react' {
    // unstable observedBits
    interface ConsumerProps<T> {
        unstable_observedBits?: number;
    }
    function createContext<T>(
        defaultValue: unknown,
        unstable_calculateChangedBits?: (prev: T, next: T) => number
    ): Context<T>;

    // unstable Suspense API
    interface SuspenseProps {
        /**	
         * Tells React whether to “skip” revealing this boundary during the initial load.	
         * This API will likely be removed in a future release.	
         */
        // NOTE: this is unflagged and is respected even in stable builds	
        unstable_avoidThisFallback?: boolean;
    }
}
```
</details>

Closes #44886

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]
I'm fine with this shipping as it will resolve the issues raised by @gaearon in the linked issue. Would appreciate a second pair of eyes on this too.

**Comment by johnnyreilly** [comment]
@eps1lon looks like there's some test failures?

**Comment by eps1lon** [comment]
> @eps1lon looks like there's some test failures?

I can reproduce these on master as well. I can work on a separate PR to fix them. Though we'd loose a bit of confidence since I can't branch `$ExpectType` depending on the TypeScript version, no?

**Review by ferdaber — APPROVED** [review]

**Comment by ferdaber** [comment]
Will there be changes to `react-dom` as well? Which I think has `unstable_batchedUpdates`.

**Comment by eps1lon** [comment]
> Will there be changes to `react-dom` as well? Which I think has `unstable_batchedUpdates`.

I think we should get these in as well.

**Comment by gaearon** [comment]
I would keep `unstable_batchedUpdates` and `unstable_renderSubtreeIntoContainer`. They have a special status because de facto they're widely used, and we can't change their semantics.

**Review by dimitropoulos — APPROVED** [review]

**Comment by eps1lon** [comment]
Only rebased onto `master` to get the PR green.

**Comment by eps1lon** [comment]
@sandersn Could you remove the label? The build is passing and the bot doesn't want to remove the label.   Or someone manually merge this manually.

**Comment by sandersn** [comment]
This is in the correct bucket -- Needs Maintainer Review -- because the new bot ignores the Travis label.
The Needs Maintainer Review bucket is just full right now -- over 100 PRs for the maintainer to review, so I expect it'll take a while to get through all those.

**Comment by paranoidjk** [comment]
@epabst         
```diff
---defaultValue: unknown,
+++defaultValue: T,
```

**Pull request merged**
