### PR TITLE
[@types/yup] Reverting previous changes that cause `any` type

### PR DESCRIPTION
**Pull request by Aerophite**
Updating some of the Yup types back to declarations prior to PR #47367. This change is required for the types to not be considered `all`. Note that this revert does **not** change any functionality that was added as part of PR #47367.

### Example of the problem
image

Evaluates to
image

But should evaluate to
image

### PR template
[ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup

---

Note that I didn't modify any tests because there are tests that should have caught this already using the `$ExpectType` that resolve correctly. I am unsure why this is.

### CODE REVIEW

**Comment by iansan5653** [comment]
@Aerophite Can you explain why this issue was happening? I'm not sure I see the issue with the current types

**Comment by Aerophite** [comment]
@iansan5653 I honestly cannot. However, I haven't been able to get VSCode or eslint (6.8.0) to be able to consider these types to be valid with the current master. The screenshots I provided are the typings that VSCode is considering them to be. The second screenshot showing the "any" types are using the current master version for @types/yup and the second screenshot is after my changes in this PR.

**Comment by mauricedb** [comment]
@Aerophite Can you please share the content of the `tsconfig.json`? The thing I am looking for is the `strict` and/or `strictNullChecks` settings, see: https://github.com/jquense/yup#typescript-setting

**Comment by Aerophite** [comment]
Sure. I have strict set to true but I'm not suing strictNullChecks. The docs indicated that both are not required though so I doubt that is the issue.

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "es6",
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
  ]
}

```

**Comment by mauricedb** [comment]
@Aerophite You are correct, with `strict` enabled you automatically get `strictNullChecks`. So that is set as required.

I can reproduce the problem https://codesandbox.io/s/romantic-tesla-0slki?file=/src/index.ts, as long as you just use `Yup.string()` without anything else it infers to `any`. Unfortunately I don't have the time to investigate now.

**Comment by hjkcai** [comment]
Hi there! How is this PR going on now? I am experiencing the same issue here and really need this fix. Thanks!

**Pull request closed without merging**
