### PR TITLE
[matrix-js-sdk] improve: gerneric event content

### PR DESCRIPTION
**Pull request by hannojg**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

-----

### Abstract:

Events can have _any_ event type. There are just "default" event types from the matrix protocol. These changes enable us to add type support for custom events (while also advancing support for events content in general) with custom event type names and custom event content payloads.

### Changes:

- `EventType` on `Event` is a literal union. This enables us to put any string as an event type, while still having autocompletion/IntelliSense support for the default types
- Changes type name of `EventContentType` to `EventContentTypeMessage` as this "content type" just applies for "m.room.message" events.
  - I added a reexport so this change is not breaking: `export type EventContentType = EventContentTypeMessage;` 
- `MatrixEvent` accepts a generic type which will become the type for the content of the event (thus we can explicitly type the content for an event)
- The default type is for the `MatrixEvent` is `EventContentTypeMessage`. So everything behaves like before these changes (no breaking)
- Added a `EventContentTypeAudioMessage` interface (we can possibly add all m.room.message message content types)
- Added the possibility to explicitly type the type name for an event as second generic argument

### CODE REVIEW

**Comment by hannojg** [comment]
It probably would be better to introduce the following breaking change:

```js
MatrixEvent<IEventContentType = {}, EventName = EventType>
```

why? Currently, the default event content type is set to `EventContentTypeMessage` which can not be _assumed_ as default type for events. Events contents can literally be anything.
Also I mentioned that building type safe guard functions return unexpected results, e.g.

```javascript
const isCustomEvent = (event: MatrixEvent): event is CustomEvent => event.getType() === "m.custom.event";

const matrixEvent = {...} // is type MatrixEvent

if (isCustomEvent(matrixEvent)) {
  // matrixEvent is now type MatrixEvent<EventContentTypeMessage, EventType> & CustomEvent
  // it should just be CustomEvent
}

**Review by andrevmatos — APPROVED** [review]
lgtm. I'm a little afraid of making many breaking changes on this package, since most of the code which was written for the previous would already assume `any` in these contents, but these ones should be safe, we just need to evaluate if type safety increase from any breaking change is worth it. thanks for your contribution

**Comment by hannojg** [comment]
For the codebase on the app, I am working on type safety means everything to us, and I wouldn't have been able to implement large features (in the app) without the type of safety these changes are giving our codebase.

**Comment by hannojg** [comment]
Ready to merge

**Pull request merged**
