### PR TITLE
ember__runloop: timer is optional for cancel

### PR DESCRIPTION
**Pull request by andreyfel**
See https://github.com/BackburnerJS/backburner.js/blob/af77b18f37ec24e89f65bef0ce16bc3c8d1f4bfb/lib/index.ts#L551

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Thanks for this PR, @andreyfel. In line with our usual Typed Ember policy, we won't merge this based on implementation details alone—it needs to be *documented* behavior. The reason: there are a lot of things within Ember and its libraries whose public APIs are narrower than what the internal implementation suggests. @dfreeman and I both looked at this and it isn’t 100% clear to us that the internal implementation is *meant* to have these public semantics, especially given that all the examples in [the existing docs](https://api.emberjs.com/ember/4.1/functions/@ember%2Frunloop/cancel) show using it with a valid timer argument.

Please open an issue against Ember itself clarifying whether the docs should be updated, and then folks with the relevant knowledge of the intent for this API can comment. If calling `cancel` with a nullish argument (or no argument at all) is intended public API, we can then update the docs and then roll out this change.

Thanks again!

**Review by wagenet — APPROVED** [review]

**Comment by wagenet** [comment]
Oops, I missed Chris's comment.

**Comment by andreyfel** [comment]
I've created https://github.com/ember-learn/ember-api-docs/issues/795 but it didn't get any feedback so far.

**Review by chriskrycho — APPROVED** [review]
Per discussion on the related issue, this is good. 👍🏼 Thanks!

**Pull request merged**
