### PR TITLE
[aws-lambda]: Adding definition for lambdaAtEdge event

### PR DESCRIPTION
**Pull request by Scotsoo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html#lambda-event-structure-request>>
However - I believe these docs are incorrect. The definition I've provided is based on responses I've received from my Lambda@edge

### CODE REVIEW

**Comment by simonbuchan** [comment]
I might be confused: Lambda@edge is already included as the `CloudFront*` events though? And your example doesn't match that format at all (we've had some updates to them, so people are using them!)

**Comment by Scotsoo** [comment]
@simonbuchan yeah - I thought this too. My current setup is APIGW -> Lambda@Edge but the format of the event I'm receiving from AWS is not similar to any of the CloudFront events. I'll provide a sample of what I get

**Comment by simonbuchan** [comment]
The event looks like the body you get from APIGW, are you sure you're not doing APIGW -> CloudFront -> lambda as an origin or something?

**Comment by Scotsoo** [comment]
Sorry yeah, It's just APIGW->Lambda

**Comment by Scotsoo** [comment]
Just realised it's not even a lambda@edge, getting APIGW + Cloudfront confused - apologies

**Comment by simonbuchan** [comment]
Fair enough. `APIGatewayProxyEvent` is what you should receive from APIGW if it's configured using the standard lambda proxy integration. Not sure exactly where your format is coming from, but it might be due to using the cognito pool or custom authorizer in APIGW, or maybe a custom request mapping, or using an imported API schema, or any of the million other things APIGW does!

Fortunately, there's nothing stopping you from defining your own handler type, e.g.:

```ts
import { Handler } from "aws-lambda";

type MyHandler = Handler<MyEvent, MyResponse>;

...

export const handler: MyHandler = async (event, context) => {
  ...
  return response;
};
```

or just using `Context` or `Callback` directly in the handler parameter types.

If you do nail down the event / response format source, and it is sufficiently general, e.g. defined by AWS infrastructure, I'd be happy to review it then.

**Comment by andrewbranch** [comment]
@Scotsoo @simonbuchan can you all clarify the state of this PR for me? It sounds like either changes are needed or maybe a different PR may be opened later?

**Comment by simonbuchan** [comment]
@andrewbranch Either nothing appropriate to add to this package or would be a different PR to my understanding.

**Comment by andrewbranch** [comment]
Cool. I’m going to go ahead and close this for housekeeping. @Scotsoo, please feel free to open a new PR when you’re ready. Thanks everyone!

**Pull request closed without merging**
