### PR TITLE
Add the timeout() method to IRunnable in Mocha

### PR DESCRIPTION
**Pull request by ericeslinger**
this allows it().timeout(5000) type calls.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L78

### CODE REVIEW

**Comment by ericeslinger** [comment]
Fixes issue #15485

**Comment by andy-ms** [comment]
Please rebase on top of master once #15489 is in to fix test failures.

**Comment by ericeslinger** [comment]
Hrm, I'm not sure I'm properly interpreting the CI test, but it looks like it's failing elsewhere in the types folder. I think I properly rebased before pushing again.

**Comment by andy-ms** [comment]
Oops, missed one. Rebase when #15494 is in.

**Pull request merged**
