### PR TITLE
Update definitions for connect-mongo 3.0

### PR DESCRIPTION
**Pull request by guyellis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jdesboeufs/connect-mongo/blob/44f1850943eebadd7de3e4dbdc2a513c93e57cf0/src/index.js#L114-L128
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by guyellis** [comment]
@Syati - are you able to review / approve this PR?

**Comment by jessetrinity** [comment]
@guyellis from your links it sounds like connect-mongo ships it's own type now, is that correct?

If so, @Syati do we want to remove these definitions from DT?

**Comment by guyellis** [comment]
@jessetrinity - After I submitted this PR I asked the team at connect-mongo if they would include this file in their repo and just this morning they accepted the PR - so yes - it will be shipped the next time they publish.

It should definitely not live in both places. I don't know how long until they publish. If it's removed from here then the existing versions will remain published won't they?

My suggestion is to merge this PR so that the corrected version can get published here. After that I would suggest we then remove this definition file. I don't mind doing the PR to remove it if you'd like me to.

**Comment by jessetrinity** [comment]
Yes, sounds good. Thanks!

**Pull request merged**
