### PR TITLE
Add missing hgroup element to react.d.ts

### PR DESCRIPTION
**Pull request by tomduncalf**

### CODE REVIEW

**Comment by tomduncalf** [comment]
Never mind, seems that upgrading to `typings` (https://github.com/typings/typings) and the latest defs fixed this

**Comment by vvakame** [comment]
*react/react.d.ts*

to authors (@pspeter3 @vsiao AssureSign (account can't be detected) Microsoft (account can't be detected)). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vsiao** [comment]
Thanks :+1:

**Comment by horiuchi** [comment]
@tomduncalf Thanks mate!
@vsiao Thanks for review!

**Comment by tomduncalf** [comment]
:+1: Cheers!

**Pull request merged**
