### PR TITLE
[rdf-js] Make RDF/JS's NamedNode generic

### PR DESCRIPTION
**Pull request by Vinnl**
This will allow people to use these typings to indicate paramters
whose NamedNodes need to have a specific value. All code that does
not explicitly indicate a generic parameter (i.e. all existing
code) should not be affected.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I'm getting errors running both `npm test` as well as `npm run lint rdf-js` on current `master`, so I couldn't run those on this branch either :/

### CODE REVIEW

**Review by rubensworks — COMMENTED** [review]
I'm neutral about this PR.

On the one hand, I understand that there may be value in this for specific use cases.
On the other hand, this increases complexity and understandability of the typings further.
One could even apply a similar modification to other term types, and even quads, which would make it even more complex.

Is this really a major need for this in your case @Vinnl?

**Comment by Vinnl** [comment]
@rubensworks The primary use case is for a set of constants automatically generated from ontologies, i.e. `NamedNode`s with known values. This update would allow developers to define union types for e.g. function parameters that only accept a limited set of values.

**Review by rubensworks — APPROVED** [review]
Makes sense, so I'm not going to block this PR :-)

**Comment by Vinnl** [comment]
Hmm, darn it. Now that DT's [infra issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317#issuecomment-638298526) have been resolved I can run the tests again, and it turns out that this would have been a breaking change. Specifically, code that is currently written to accept an `rdf-js` DataFactory can no longer just accept any other existing DataFactory (e.g. N3's or rdf-ext's), because that DataFactory can not uphold the contract of the `namedNode` constructor being able to return a constant.

Thus, I took out the constraint on DataFactory's producing these constants by default. I believe this to be fine; the generated constants can just include a cast to the right type or use its own DataFactory, whereas we shouldn't be requiring existing DataFactory types to be updated just for this. That said, that probably does warrant a re-review - sorry :/ 

The change is in 16d29e86cd6fe34e6ac6f53bba6ba1a1988d7401.

**Review by rubensworks — APPROVED** [review]
Looks good. If you want, you could always add a TODO in the typings for changing the `namedNode` method for when we want do a new breaking change.

**Comment by Vinnl** [comment]
@rubensworks Good call - added in 73341d0867f88cc8e2face97f9946c6506435992.

**Comment by Vinnl** [comment]
Ready to merge

**Comment by Vinnl** [comment]
@rubensworks I think the added comment requires renewed approval...

**Review by rubensworks — APPROVED** [review]

**Comment by Vinnl** [comment]
Ready to merge

**Pull request merged**
