### PR TITLE
[@types/ember-data] Support for 'module API' introduced in v2.3.0-beta.*

### PR DESCRIPTION
**Pull request by mike-north**
Re-exporting certain modules to match the [Ember-Data Modules API](https://www.emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules) introduced in ember-data v2.3.0-beta release series.

There's a [new RFC open](https://github.com/emberjs/rfcs/blob/ember-data-modules/text/0000-ember-data-javascript-module-api.md) for making ember-data modules available for consumption from an `@ember-data` namespace, so we'll have to do this again soon™️ (keeping this work in place).

---
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Ember-Data Modules API (released in v2.3)](https://www.emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules)
- [X] Increase the version number in the header if appropriate. **(NOT APPROPRIATE)**
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **(ALREADY DONE)**

### CODE REVIEW

**Comment by dwickern** [comment]
FYI you can also put the all declarations in `index.d.ts` if you structure it like this:
```ts
declare module 'ember-data' {
    import Ember from 'ember';

    namespace DS {
        ...
    }
    export default DS;
}

declare module 'ember-data/adapter' {
    import DS from 'ember-data';
    export default DS.Adapter;
}
```

We'll need to implement it that way for the `@ember-data` naming scheme.

Anyway, LGTM. Although these shims are deprecated, we should at least have typings for them until there's an (automated) migration path.

**Comment by mike-north** [comment]
@dwickern I originally had module declarations set up in one file, with absolute references to `ember-data` as you have there, but the current linting configuration insisted I create new files, with _relative_ references to the main `ember-data` module. Should I change the tslint configuration and go back one-file and absolute internal module references?

I don't believe that referring to e-d modules in this way is deprecated, but I could be wrong.

**Comment by mike-north** [comment]
Ok it's all back in one file now, and I've adjusted tslint config appropriately

Also, I can confirm that this is public API  
screen shot 2017-12-13 at 6 32 58 pm

**Comment by dwickern** [comment]
On second thought I'd like to get @chriskrycho and @locks opinions before we merge this. I noticed there is https://github.com/typed-ember/ember-data-shim-typings. I think the intent here was to offer _opt-in_ typings for the shim imports since they are deprecated (?). If we add them here, the imports might be used accidentally, e.g. via IDE auto-import

**Comment by dwickern** [comment]
OK, there was some confusion on my part about these APIs. I am still willing to merge this but I'll give a chance for other folks to chime in.

**Comment by mike-north** [comment]
No worries, let's make sure we separate two issues though
- [ ] Is this a currently-supported way of using `ember-data`
- [X] Do these type definitions effectively describe the way these modules work

**Comment by chriskrycho** [comment]
I talked with Chris Thoburn (runspired) a few weeks ago about this and confirmed that these are public API, same as Rob’s comment in the screencap above, so I’m also in favor of supporting them until such a time as they’re deprecated officially.

Thank you for writing them up, @mike-north!

**Comment by chriskrycho** [comment]
Oh, and I should add: I have *no idea* if they’re correct, as I’ve never used anything other than `import DS from 'ember-data';`; perhaps @runspired or someone else from the Ember Data team can chim in(if @dwickern isn’t already familiar enough with them to confirm).

**Comment by dwickern** [comment]
> Is this a currently-supported way of using ember-data?

Based on responses here this seems to be the case. 👍 

> Do these type definitions effectively describe the way these modules work?

LGTM. I use this style import in my app so I am familiar. There are some APIs in this PR which are not listed in the [blog post](https://www.emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules) but they seem to match up with the [implementation](https://github.com/emberjs/data/tree/master/addon). 👍 

You've got my 👍 to merge

**Pull request merged**
