### PR TITLE
definitions for moment-range

### PR DESCRIPTION
**Pull request by Burgov**
definitions for moment-range

I'm kinda new to Typescript so please let me know if i need to improve on something

### CODE REVIEW

**Comment by Burgov** [comment]
working on failed travis...

**Comment by Burgov** [comment]
done

**Comment by vvakame** [comment]
*moment-range/moment-range.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/moment-range
  * http://bower.io/search/?q=moment-range
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (moment-range/moment-range-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@Burgov thanks mate!

**Pull request merged**
