### PR TITLE
[dojo] Use gender-neutral pronouns

### PR DESCRIPTION
**Pull request by bensalilijames**
Continuation of #39053 since Dojo types were large enough to make CI run out of memory. This commit fixes up that single remaining package.

### CODE REVIEW

**Review by antoinerousseau — APPROVED** [review]

**Comment by antoinerousseau** [comment]
Looks like the issue remain, even when ran alone...

**Review by Haroenv — APPROVED** [review]

**Comment by benhjames** [comment]
Having a quick experiment, I found that Node 8.16.2 (what CI uses) runs out of memory, but Node 12.12.0 runs ok. When I get some more time I can dig deeper into why this might be.

**Review by michael-vansickle — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
I'm going to bypass CI on this one since it's only 3 files.

Also 👀

> the node is flipped around his center

dojo authors may want to start looking into the OOM.

**Comment by sandersn** [comment]
@benhjames 12.12.0 fails for me locally as well. Where did you get a passing run with it?

@types/dojo is rarely updated and little used these days so I'm not sure it's worth anybody's time to track down the problem. On the other hand, this means that having an updatable types/dojo isn't worth that much either.

**Comment by benhjames** [comment]
I managed to get a passing run locally with 12.2.0 (via `nvm use 12 && node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed`).

I tested with five runs on each of Node 8 and Node 12 switching between them between each run - all five on Node 8 failed with OOM, and all five on Node 12 passed. Perhaps Node 12 makes it less likely to fail (maybe there's some optimisation present?), but maybe there's something else either transient or unrelated.

Anyway, agreed that it sounds like it's not worth the time to track down. Will leave this sitting unless I get a very rainy day soon. 🙂

**Pull request merged**
