### PR TITLE
Removed DataView which has a type which has not been defined.

### PR DESCRIPTION
**Pull request by ghost**
Addresses issue #5513

### CODE REVIEW

**Comment by vvakame** [comment]
um? what version of tsc do you use? this repo supported only latest(1.5.3) tsc.

**Comment by dotnethacker** [comment]
This is using the latest compiler. The pull request removes a reference to a DataView of type DataView which is not defined in the node.d.ts file and causing the typescript compiler to emit a warning. Since there is no reference to a DataView elsewhere the simplest fix is to remove the reference.

**Comment by vvakame** [comment]
```
$ tsc -v
message TS6029: Version 1.5.3
$ tsc --module commonjs --target es5 --noImplicitAny node/node.d.ts
$ echo $?
0
```

I can't reproduce your issue.

**Comment by dotnethacker** [comment]
Can you point me to where the DataView interface or class is defined in node.d.ts file?

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript/blob/v1.5.3/bin/lib.d.ts#L1234

**Pull request closed without merging**
