### PR TITLE
Update ignite-ui typings

### PR DESCRIPTION
**Pull request by dkamburov**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by dkamburov** [comment]
I fixed those, can you merge the pull request now?

**Comment by dkamburov** [comment]
Can somebody take a look and merge it?

**Comment by sandersn** [comment]
Sorry for the delay on this. Unfortunately, for such a large change I really want to get some input from owners of the project. I followed IgniteUI back to its group members:

@damyanpetev @kdinev @Lipata @rkaraivanov @sdanailova @tiliev do you mind taking a look?

**Comment by mpavlinov** [comment]
@sandersn I'm also an Ignite UI member. I'm good with the changes. Just want to clarify that this file is auto-generated from Ignite UI source and API docs. It includes the new functionality in Ignite UI 17.1 as well as a few bug fixes.

**Comment by damyanpetev** [comment]
I'm also okay with the changes.

**Pull request merged**
