### PR TITLE
deep-equal: Use `export as namespace`

### PR DESCRIPTION
**Pull request by bouzuya**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by janslow** [comment]
LGTM

**Comment by janslow** [comment]
Is there a particular reason for this? Defining the function as a type alias seems inconsistent with other similar packages (e.g., [deep-extend](https://github.com/bouzuya/DefinitelyTyped/blob/ab7ca96dcf813e6b5d969420d33fdc0ae646b10e/types/deep-extend/index.d.ts), [deep-assign](https://github.com/bouzuya/DefinitelyTyped/blob/ab7ca96dcf813e6b5d969420d33fdc0ae646b10e/types/deep-assign/index.d.ts)).

**Comment by janslow** [comment]
Also, the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules.html) seem to say that `export as namespace` is for UMD/isomorphic modules, but `deep-equal` isn't one ([`module.exports = function (...) { ... }`](https://github.com/substack/node-deep-equal/blob/master/index.js#L5)).

(However, I've never come across `export as namespace`, so I may have misunderstood)

**Comment by BendingBender** [comment]
From the readme (which you have marked as read):

> #### A package uses `export =`, but I prefer to use default imports. Can I change `export =` to `export default`?
>
> If default imports work in your environment, consider turning on the [`--allowSyntheticDefaultImports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option.
> Do not change the type definition if it is accurate.
> For an NPM package, `export =` is accurate if `node -p 'require("foo")'` is the export, and `export default` is accurate if `node -p 'require("foo").default'` is the export.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
It's not clear why you need an `export as namespace` in the first place. The library doesn't conditionally expose a global.

**Pull request closed without merging**
