### PR TITLE
Add support for Bliss.$() method

### PR DESCRIPTION
**Pull request by osaton**

### CODE REVIEW

**Comment by fskorzec** [comment]
Le 2016-02-10 12:44, Definitely Bot a écrit : 

> _blissfuljs/blissfuljs.d.ts_ 
> 
> to author (@fskorzec [1]). Could you review this PR?
> or ? 
> 
> Checklist 
> 
> * pass the Travis CI test?
> 
> --
> Reply to this email directly or view it on GitHub [2].



Links:
------
[1] https://github.com/fskorzec
[2]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8034#issuecomment-182327690

**Comment by vvakame** [comment]
um?

**Comment by fskorzec** [comment]
Answered to quickly from my phone. The fix is ok.

**Comment by horiuchi** [comment]
@osaton Thanks mate!
@fskorzec Thanks for review!

**Pull request merged**
