### PR TITLE
Sqlite3 fix nullChecks in static test

### PR DESCRIPTION
**Pull request by atd-schubert**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: **This fix just makes this definition fulfilling the new guidelines**
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by atd-schubert** [comment]
I mentioned the `nullCheck` fix in #14094 and make an additional PR for the sqlite3 typing, like @mhegazy write in the other PR.

**Comment by atd-schubert** [comment]
I have not change the type `Function`, because I was not sure about. This is why there is still an error in the automatic checks, I think.

*Output: forbidden-types  Avoid using the Function type. Prefer a specific function type, like `() => void`.*

Does it mean the same? Maybe something like `(a, b) => {}` is not possible anymore when a function is typed as `() => void`?

**Comment by mhegazy** [comment]
> Does it mean the same? Maybe something like (a, b) => {} is not possible anymore when a function is typed as () => void?

depending on where it is, in a read position vs. a write position; i.e. you are passing this property to some other function as a callback, then you want the `()=>void` , if you are calling it directly, you want it to be `(...args:any[])=>any`. Ideally, you would update the arguments based on the behavior of the library; this way users of this declaration file can get correct type checking.

**Comment by atd-schubert** [comment]
In this case it is a "home-brew" Event-Emitter with a `on()` function.

In the typings are several known events registered. But you are able to add your own events on it, so `(...args: any[])` is correct one in this case, I think. But the function should always return nothing / void, so the complete type is: `(...args: any[]) => void`. If you are ok with that, I will commit it that way.

**Comment by TonyPythoneer** [comment]
I don't understand why this PR can't pass CI. It seems not obviously different.

**Comment by atd-schubert** [comment]
It was because of the `Function` Type. I replaced it now with `(...arg: any[]) => void` and it passes... 

Thanks to @mhegazy for your explanation!

**Pull request merged**
