### PR TITLE
Bootstrap v4

### PR DESCRIPTION
**Pull request by denisname**
Add typing for bootstrap v4 (alert, button, carousel, dropdown, modal, tooltip).
Move old code to bootstrap/v3.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by denisname** [comment]
Fixes #23906 and #20646.

**Comment by aluanhaddad** [comment]
@Sebazzz popover is a separate package on which bootstrap 4 depends. Its types should be provided separately.

**Comment by Sebazzz** [comment]
You are talking about Popper.js, I believe. I meant the pop over, the enhanced tooltip: https://getbootstrap.com/docs/4.0/components/popovers/

Met vriendelijke groet,
Sebastiaan Dammann
________________________________

**Comment by aluanhaddad** [comment]
I'm sorry I'm totally brain-dead you're absolutely correct.

**Comment by denisname** [comment]
The reason is it's a [work in progress](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bootstrap/index.d.ts#L7) and I had no time to write all types.
But eventually I found some time and wrote the missing type definitions. I'm waiting for FezVrasta/popper.js#573 to be merged and released on npm, to publish my work.

Groetjes,

**Comment by carlos243** [comment]
hello, how to add my proyect @types/bootstrap v3 ?

**Comment by AlexRiina** [comment]
It looks like the versions of @types/bootstrap track the bootstrap versions, so you should be OK with installing a tag with the bootstrap version you're on. When I run

```
npm install --save-dev @types/bootstrap@3.3
```

for example, the index.d.ts starts with "Type definitions for Bootstrap 3.3.5".

**Pull request merged**
