### PR TITLE
[react] better prop typing for JS users

### PR DESCRIPTION
**Pull request by ferdaber**
## Context
The `LibraryManagedAttributes` feature in JSX was supposed to help with two things:
- For TypeScript users to be able to use `defaultProps` without non-null asserting their own props in component implementations
- For JavaScript users to get richer type intelligence coming from `propTypes` and `defaultProps`

Unfortunately the merging type for `propTypes` did not work very well because most JS users have their props definitions inferred as either `any` or an object of `any`s:
```js
// props is `any` type
function Component(props) {
  return /* ... */
}

// props is { foo: any, bar?: boolean, baz: any } type
function BetterComponent({ foo, bar = false, baz }) {
  return /* ... */
}
```

NB - this problem doesn't affect class components because their props are automatically assumed to be of type `{}` due to the default generic type parameter of `React.Component`, but with hooks becoming more prevalent, we need to give more TLC to function components

So we try to do better for JS users and more intelligently merge the types of prop types.

Also, `ComponentProps` will fail if a component's props type doesn't exactly match its `propTypes` type, which sometimes can happen, so we should be more relaxed with that check since those static properties are not relevant in those conditional types where `ComponentProps` is used.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ferdaber** [comment]
@Kovensky can you take a look and see if there will be unintended problems with modifying `ComponentProps`?

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by Kovensky** [comment]
@ferdaber I tried doing a similar change last month but I got stuck with... something, I forgot what.

I tried doing it by changing the type of `ReactType` itself instead of adding yet another type alias, though.

**Comment by mohsinulhaq** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32198

**Comment by mohsinulhaq** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32198
i think this PR caused the above issue...can we please check this out?

**Pull request merged**
