### PR TITLE
update(luxon): VERSION

### PR DESCRIPTION
**Pull request by peterblazejewicz**
export `VERSION` from DT type

Should silence DT bot on PR reviews.

https://github.com/moment/luxon/blob/master/src/luxon.js#L12

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes

### CODE REVIEW

**Review by kkocel — APPROVED** [review]

**Review by mastermatt — CHANGES_REQUESTED** [review]
Exporting the version was only added recently in 1.26, so first line of `types/luxon/index.d.ts` needs to be updated as part of this change. 
https://github.com/moment/luxon/blob/master/CHANGELOG.md#1260

**Comment by kkocel** [comment]
@mastermatt It's changed to 1.26 by me, however I forgot to add VERSION

**Comment by peterblazejewicz** [comment]
Oh, I've forgotten to mention upstream PR that changed version, sry!

**Review by mastermatt — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💋

**Pull request merged**
