### PR TITLE
[swiper] Update swiper typings to v5.4

### PR DESCRIPTION
**Pull request by john015**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## swiper ([<kbd>unpkg</kbd>](https://unpkg.com/browse/swiper@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'swiper'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. extendDefaults
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fc3fed9dafc640cbe8ed8c5d502134bdf44450b5
</p>

**Review by odahcam — APPROVED** [review]
LGTM

**Review by odahcam — COMMENTED** [review]
How your tests should prove the two new methods you added actually works?

**Comment by john015** [comment]
@odahcam 
I think `DefinitelyTyped` is a repository for TypeScript type definitions so there is no need to test two methods works well.

**Comment by odahcam** [comment]
@john015 I think you misunderstood me. I refer to the tests that prove the methods are really available on Swiper, because I couldn't identify the goal of the test added within the PR. There's no need to add more tests BTW.

**Comment by john015** [comment]
@odahcam I think the tests that I added proved enough. Because I defined `hashChange` and `hashSet` events on the swiper in the tests, but there was no type error. 
If I had defined an undeclared method(e.g. somethingChange) on the swiper, an error would have occurred. Therefore, I think my test proves well enough.

**Comment by odahcam** [comment]
But I'm not questioning your tests quality at all, I just wanted to know **how** would they prove no runtimes error will happen if we use these new definitions, because just reading the code was not clear enough for me.

Just remember only V8 runtime will check if a method does exist or not, typing definitions are only statically analyzed and taken as source of truth by static code analyzers. That means if you declare something that doesn't exist in here and some folk use it, it will throw a runtime error.

I'll let another reviewer follow up anyway.

**Comment by elibarzilay** [comment]
@john015 + @odahcam: what's the status of this?

**Comment by odahcam** [comment]
I did not verify all added declarations, just those until my last aprove.

**Comment by elibarzilay** [comment]
(OK, so I'm assuming that this should wait until you're done.)

**Review by odahcam — APPROVED** [review]
It's ready to merge. I did review one more time, tested and understood that all changes are true to Swiper's API.

**Comment by elibarzilay** [comment]
Thanks!

**Pull request merged**
