### PR TITLE
Hapi auth cookie

### PR DESCRIPTION
**Pull request by O-Mutt**
ref #30416 

The Typescript-bot closed my PR before i could update

### CODE REVIEW

**Comment by lenovouser** [comment]
@Mutmatt I created a PR for this a few days ago at #30873

**Comment by lenovouser** [comment]
Ah I just saw you created another one 20 days ago. My bad.

**Comment by amcasey** [comment]
Owners @AJamesPhillips and @saboya, would you like to take a look?

@uniqueiniquity, do you have any follow up from #30416?

**Comment by lenovouser** [comment]
Shameless plug, but my PR's types at #30873 are much more in-line with the other Hapi-related types and re-use a lot more of the types from the parent Hapi types. (e.g. Cookie options). I added @Mutmatt as a owner in case they get favored instead of these so that more people can review changes in the future.

**Comment by saboya** [comment]
The `hapi-auth-basic` changes are very minor fixes, so no issues from me. About `hapi-auth-cookie`, seems fine, but there's also @lenovouser 's PR, so that's up to you.

**Comment by uniqueiniquity** [comment]
@amcasey I would say that @lenovouser's approach makes more sense to me. In particular, the usage of `export default` is incorrect, whereas merging a namespace with a const gives the desired structure. Beyond that, I can't really distinguish between the two with regards to how correct the provided types are.

**Comment by amcasey** [comment]
I think including @Mutmatt as an owner in #30873 sounds like a good compromise.  Thanks!

**Pull request closed without merging**
