### PR TITLE
Changed Page & Utility from an Object to an Interface

### PR DESCRIPTION
**Pull request by ben-scully**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by daryllabar** [comment]
What's the advantage of changing to an interface, rather than an object?

**Comment by aozgaa** [comment]
One benefit: you now have an alias for the `Page` "shape", so it can more easily referenced elsewhere in the *.d.ts file.

Subjectively, I also find it more readable.

**Comment by minestarks** [comment]
@daryllabar do you have an objection to this? I'm not familiar with the library and I'm indifferent to the change, but I'll merge if no objections. Thanks.

**Comment by daryllabar** [comment]
To be honest I'm not sure if the change is an advantage or disadvantage.  I was hoping the @ben-scully would respond with what the advantage was.

**Comment by paulvanbrenk** [comment]
This PR seems abandoned, please re-opeon when you made the requested changes.

**Pull request closed without merging**
