### PR TITLE
Add definitions for markerclustererplus

### PR DESCRIPTION
**Pull request by enanox**
Hello, I would like to propose a definition file for the library MarkerClustererPlus for Google Maps V3.
Project home: [mahnunchik/markerclustererplus](https://github.com/mahnunchik/markerclustererplus)

This `*.d.ts` file correspond to the `2.1.1` version.

I'm not sure about how to provide a meaningful demo without the heavy JSON data I put in the `-tests` file, so please feel free to correct me if this is wrong.

Cheers!

### CODE REVIEW

**Comment by vvakame** [comment]
*markerclusterer/markerclusterer-2.1.1.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/markerclusterer
  * http://bower.io/search/?q=markerclusterer
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (markerclusterer/markerclusterer-2.1.1-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@enanox thank you for your contributions.
please rename markerclusterer/markerclusterer-2.1.1.d.ts to markerclustererplus/markerclustererplus.d.ts

**Comment by enanox** [comment]
Hi @vvakame, thanks for your feedback! Please find the changes on [fa3b6b5](https://github.com/borisyankov/DefinitelyTyped/commit/fa3b6b5a3422a98c452583ea89bc60d15f9bceb3). 
About the issue about the full dummy data on `markerclustererplus-tests.ts`, don't you think it will be fine to provide an external file named `markerclustererplus-tests.json`? Otherwise, please let me know your thoughts.

Thanks in advance!

**Comment by vvakame** [comment]
@enanox don't mind! thanks mate.

**Comment by enanox** [comment]
(Y)

**Pull request merged**
