### PR TITLE
The FakerStatic interface must have optional parameters in the system.

### PR DESCRIPTION
**Pull request by carvalhoviniciusluiz**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

According #28574, the FakerStatic interface must have optional parameters in the system.

### CODE REVIEW

**Comment by mattbishop** [comment]
Sorry the discussion for this PR has been happening on the issue. We are waiting for a response from the source lib (faker.js) before deciding what change to make here.

**Comment by minestarks** [comment]
This looks fine to me, but... should I wait to merge?

**Comment by RyanCavanaugh** [comment]
I agree `ext` is optional, but the others... updating the .d.ts based on what appears to be a bug in the underlying implementation seems questionable at best?

**Comment by carvalhoviniciusluiz** [comment]
conventional tests do not normally pass these parameters, only tests in typescript require the use of these parameters. Would that be right?

**Comment by mattbishop** [comment]
I have a feeling we are going to wait a long time for faker.js to clarify. I'd say merge it and come back if faker.js releases a new version with different behavior.

**Pull request merged**
