### PR TITLE
material-ui - Also export types in named modules

### PR DESCRIPTION
**Pull request by use-strict**
Had to wait for the 0.12.1 defs to be merged.

@ngbrown , can you review this? Thanks.

### CODE REVIEW

**Comment by use-strict** [comment]
@ngbrown ?

**Comment by ngbrown** [comment]
@use-strict :+1:

**Comment by use-strict** [comment]
@vvakame , bother you again with a merge? :)

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
