### PR TITLE
Fix async.forEachFor signature

### PR DESCRIPTION
**Pull request by vineus**
"key" should not be an array

### CODE REVIEW

**Comment by vvakame** [comment]
*async/async.d.ts*

to authors(@borisyankov @kern0 @Penryn). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by Penryn** [comment]
This is the right idea. I vote :+1: but we need to fix forEachOfLimit too.

What's the best way to do this? Should I...
1) create a new PR referencing this one?
2) fork vineus/DefinitelyTyped and submit a PR there?
3) very kindly ask @vineus to amend or make another commit that modifies line 83 to

    forEachOfLimit(obj: any, limit: number, iterator: (item: any, key: string|number, callback?: ErrorCallback) => void, callback: ErrorCallback): void;

**Comment by vineus** [comment]
Missed the line 83, sorry :-)

do you rather have a new PR with a single commit ?

**Comment by Penryn** [comment]
:+1:
I'm OK with this. No sense opening a new PR. @vvakame @borisyankov @kern0: I vote for a merge, pending your approval as well.

**Comment by vvakame** [comment]
okay, I decided to merge! thanks mate.

**Pull request merged**
