### PR TITLE
pull request: Fixed param for dynatree and added tests

### PR DESCRIPTION
**Pull request by lokeshpeta**
Made includeRoot param optional
changed flag param from string -> boolean
Added test file

### CODE REVIEW

**Comment by lokeshpeta** [comment]
to author @fdecampredon could you please review?

**Comment by lokeshpeta** [comment]
Can any one accept my changes please

**Comment by fdecampredon** [comment]
I did not use dynatree in a while ... so except for checking the doc I don't see how I could review this PR

**Comment by vvakame** [comment]
@lokeshpeta thanks mate!

**Pull request merged**
