### PR TITLE
fetch-mock: update to v5

### PR DESCRIPTION
**Pull request by tamird**
Pretty much a full rewrite guided by https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js.

### CODE REVIEW

**Comment by asvetliakov** [comment]
👍

**Comment by tamird** [comment]
@asvetliakov added a commit to make this non-ambient.

**Comment by asvetliakov** [comment]
@tamird non-ambient probably won't work because tsd doesn't automatically wraps modules as typings does.

**Comment by tamird** [comment]
@asvetliakov what does `tsd` have to do with anything?

**Comment by tamird** [comment]
Can someone take a look at this please?

**Comment by mhegazy** [comment]
this is not going to work with tsd this way. i would say update the APIs but leave it as a module

Alternatively i would recommend making this change in the types-2.0 branch, and using `@types/fetch-mock` to consume it.

**Comment by tamird** [comment]
Done.

**Pull request merged**
