### PR TITLE
[rnmk] Add Indeterminate component to MKProgress

### PR DESCRIPTION
**Pull request by iRoachie**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/xinthink/react-native-material-kit/blob/master/lib/mdl/IndeterminateProgress.js>>

### CODE REVIEW

**Comment by iRoachie** [comment]
Can i get a merge here @sandersn @alloy

**Comment by alloy** [comment]
Sure thing, buddy :+1:

**Comment by iRoachie** [comment]
@alloy Arent you at react native eu lol?

**Comment by alloy** [comment]
I sure am, which is why I now have time to respond immediately! 😜

**Comment by iRoachie** [comment]
Haha enjoy the mini-vacation

**Pull request merged**
