### PR TITLE
wavesurfer.js: Regions plugin improvements

### PR DESCRIPTION
**Pull request by tmladek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions/region.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wavesurfer.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wavesurfer.js@latest/))
was missing the following properties:
1. debounce
1. Observer
1. absMax
1. clamp
1. fetchFile

<details>
<summary>as well as these 10 other properties...</summary>
<p>frame, getId, ignoreSilenceMode, max, min, preventClick, requestAnimationFrame, style, withOrientation, WaveSurfer</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against efa7dd23a66bab45095c5c8619ea5b2f09b56493
</p>

**Comment by thijstriemstra** [comment]
I wouldn't change all the quotes.

**Review by caugner — CHANGES_REQUESTED** [review]
Please revert the quote changes. 🙏 

I'll have another look then.

**Comment by tmladek** [comment]
Alright! What's the preferred formatting scheme, if not the one from this repo?

**Comment by caugner** [comment]
> Alright! What's the preferred formatting scheme, if not the one from this repo?

Unless it's enforced by checks, I would prefer that we don't reformat and have added/changed code follow the de-facto formatting scheme of the wavesurfer.js type definitions.

**Comment by caugner** [comment]
> Or would it be enough to just accept your requested changes?

If you `git revert` the reformatting commit and leave the rest as it, I will gladly approve the changes regarding the regions plugin.

**Comment by caugner** [comment]
Never mind, just learned that prettier should usually be already run as part of `lint-staged`.

Would you mind opening a separate PR for the reformatting of the wavesurfer.js definitions? We'll get that once merged and then you can rebase this one.

**Comment by caugner** [comment]
@tmladek Sorry for the delay, you can now rebase this PR (or merge current main), and I'll approve.

**Comment by tmladek** [comment]
Hi! Apologies for taking this long, had to be offline for a while.

Should be ready to go now.

**Review by caugner — APPROVED** [review]

**Comment by tmladek** [comment]
Ready to merge!

**Pull request merged**
