### PR TITLE
Added support for Calq

### PR DESCRIPTION
**Pull request by eirikhm**
Adds support for CalQ tracking - https://calq.io/docs/client/javascript/reference

### CODE REVIEW

**Comment by vvakame** [comment]
*calq/calq.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/calq
  * http://bower.io/search/?q=calq
  * others?
* [ ] has a test file? (calq/calq-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@eirikhm thank you for your contributions.
please check this document. http://definitelytyped.org/guides/contributing.html#tests
rename calq/calq-test.ts to calq/calq-tests.ts.

**Comment by eirikhm** [comment]
@vvakame Done

**Comment by vvakame** [comment]
@eirikhm thanks mate!

**Pull request merged**
