### PR TITLE
[mapbox-gl] update to mapbox-gl 1.12

### PR DESCRIPTION
**Pull request by dmytro-gokun**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.12.0
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by w3bdesign — APPROVED** [review]

**Comment by dmytro-gokun** [comment]
So, why is not it merged after 15 days?

**Review by w3bdesign — APPROVED** [review]

**Comment by dmytro-gokun** [comment]
@sandersn Can you help?

**Comment by dmytro-gokun** [comment]
Is this thing dead?

**Comment by dmytro-gokun** [comment]
@dobrud @patrickr @macobo @LiamAttClarke @life777 @mklopets @amxfonseca — guys, could plz anyone review this PR? It is crazy how thing works today here and that I have to ask all of you. But plz find 5 minutes and do this.

**Comment by amxfonseca** [comment]
You are right. Took too long for a fairly safe to merge PR

**Review by amxfonseca — APPROVED** [review]

**Comment by dmytro-gokun** [comment]
Ready to merge

**Comment by dmytro-gokun** [comment]
@amxfonseca Thanks a lot!

**Pull request merged**
