### PR TITLE
[d3-drag/d3-zoom] Update minor versions 1.2.1/1.6.0

### LINKED ISSUE #20267: [d3-drag/d3-zoom] Update minor versions 1.2.1/1.6.0
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache 

Self-assigned.

### PR DESCRIPTION
**Pull request by tomwanzek**
* [d3-drag] Added `touchable(...)` support
* [d3-drag] Bumped minor version to 1.2
* [d3-zoom] Added `touchable(...)` support
* [d3-zoom] Bumped minor version to 1.6

Closes #20267.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-drag/releases/tag/v1.2.1>> <<https://github.com/d3/d3-zoom/releases/tag/v1.6.0>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
I just pushed another commit to bump the minor version number for the Standard D3 bundle definitions to the latest: 4.11.

The changes in this PR combined with the already merged #20270 encompass the latest constituent module definitions.

**Comment by tomwanzek** [comment]
@gustavderdrache can you do the honours for this PR when you have a minute? Thx in advance.

**Review by gustavderdrache — APPROVED** [review]
Looks good! Apologies for the delay on this one, I guess it just fell off my to-do list on accident.

**Comment by tomwanzek** [comment]
@gustavderdrache Thx. No worries.

**Pull request merged**
