### PR TITLE
[mapbox-gl-draw] improve type export

### PR DESCRIPTION
**Pull request by tudorgergely**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
It is a small fix because the initial version (which was merged today) didn't allow for importing types from the namespace.

### CODE REVIEW

**Comment by tudorgergely** [comment]
@orta can you please review this one? I just renamed the namespace and exported types from it properly.

**Review by brookjordan — APPROVED** [review]
Cool, this seems to be working better.

**Comment by brookjordan** [comment]
Ready to merge

**Comment by tudorgergely** [comment]
Ready to merge

**Pull request merged**
