### PR TITLE
Fix function name typo on tabulator-tables - refreshFilters to refreshFilter

### PR DESCRIPTION
**Pull request by handipriyono**
This Pull request fix typo on type refreshFilters. the correct name is `refreshFilter`. 
issue from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/65802) 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. 
 
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://tabulator.info/docs/5.5/filter#main-contents>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by Jojoshua — APPROVED** [review]

**Comment by handipriyono** [comment]
thank you @Jojoshua

**Comment by handipriyono** [comment]
Ready to merge

**Comment by Jojoshua** [comment]
@mike-lischke I assumed the formatting came from a some definitelytyped setting, if it wasn't required by that I agree to revert the whitespace changes.

**Comment by handipriyono** [comment]
Hi, @mike-lischke.. Hi @Jojoshua , thanks for clarifying. Yes, I changed in the file that only needs to be changed.
Regarding the change in writing format, it's from their linter settings. it's automatic.

**Comment by handipriyono** [comment]
kindly check https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66249 
Thanks

**Pull request merged**
