### PR TITLE
`config` - improve IntelliSense for methods

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

## Description
This adds an alternative type definition to the `get` method that vastly improves the IntelliSense that it currently offers:
- Dot notation IntelliSense for the `setting` parameter
- Correctly typed return values

Additionally, this adds loosely enforced typing auto complete for the `has` method. Users can still use any string for the argument, but now the paths will be included in the intellisense as well.

Users can opt in by augmenting the `config` module and extending the `IConfig` interface with their config definition. JSDoc notes on how to do this have been added. 

## Backwards Compatible
If a user chooses to not extend the `IConfig` interface, then this type definition will be the exact same as it was before this PR, preserving backwards compatibility.

### Our config
```json
{
  "api": {
    "port": 3000,
  }
}
```

### The `startServer` function
```ts
function startServer(port: number) {}
```

### Previous Dev Experience:
```ts
import config from 'config'

// Scenario 1
// IntelliSense says that this value is `unknown`
// Leaving devs to either manually type it or accept `unknown`/`any`
const unknownValueType = config.get('api.port')
const alsoUnknownValueType = config.api.port

// Scenario 2
// The value returned by the `get` function is incorrectly inferred from the type needed
// to satisfy the type requirement of the `port` argument of the function, 
// even though the argument to `get` is misspelled
startServer(config.get('api.poort'))
```

### New Dev Experience:
```ts
import config from 'config'

// Scenario 1
// IntelliSense now correctly types this as `number`
const knownToBeNumber = config.get('api.port')
const safeNumberType= config.api.port

// Scenario 2
// Now the user's IDE will tell them that `api.poort` is not a valid argument to `get`
startServer(config.get('api.poort'))

// Scenario 3
// IDE is happy now that the proper return value of `api.port` 
// matches the type of the `port` arg for the `startServer` function
startServer(config.get('api.port'))
```

## Tests

Due to augmenting the `IConfig` in the `config-tests.ts` file, I had to remove a couple of the old tests.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/config/paths.d.ts
1. types/config/index.d.ts
1. types/config/config-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1f5a64f2833b44204b376fa298cf2e514ca37c64
</p>

**Comment by TurtIeSocks** [comment]
This PR was originally adding a `UserConfig` interface that was intended to be the target for users to augment but I've since swapped this to just use the existing `IConfig` interface.

The advantages of this is that users will now be given feedback by their IDE in case their custom config that they're trying to extend with `get`, `has`, or `util` keys - which are [reserved](https://github.com/node-config/node-config/wiki/Reserved-Words).

The disadvantage is that there's possibly some scenarios where this becomes a "breaking" change. e.g. where a TypeScript user has already augmented the `IConfig` interface but is using the `get` method in an unsafe way. This seems unlikely to me since a user who cares enough to augment is unlikely to be using the previously untyped `get` method vs just accessing properties directly. 

Open to feedback though if one way or the other is preferred!

**Comment by ParitoshBh** [comment]
Looks good to me.

As for the concern for users that may already are augmenting `IConfig` interface, while I agree with you. However, I prefer to err on side of caution and if possible look into releasing this change as a major version ([ref.](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package))

I'll let others chime in as well.

**Review by ParitoshBh — APPROVED** [review]

**Comment by ParitoshBh** [comment]
Since it has been quite a while and no-one else has responded, I'll go ahead and allow merge.

**Comment by ParitoshBh** [comment]
Ready to merge

**Comment by TurtIeSocks** [comment]
Apologies, been a busy few days for me and haven't had a chance to follow up. Thanks @ParitoshBh !

**Pull request merged**
