### PR TITLE
auth0-lock: add hideMainScreenTitle to Auth0LockThemeOptions

### PR DESCRIPTION
**Pull request by willcaul**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [auth0/lock- source](https://github.com/auth0/lock/blob/c42b2c6cb7fadd60420cf888f912ce475f39c52d/src/core/index.js#L162) and [auth0/lock#745](https://github.com/auth0/lock/commit/430d912e0834d5c5ed00beb2f98d677162b26b70)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by carusology — APPROVED** [review]
Looks good. Thanks for contributing!

**Comment by goldcaddy77** [comment]
:shipit:

**Review by goldcaddy77 — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Comment by willcaul** [comment]
thanks @uniqueiniquity!

**Pull request merged**
