### PR TITLE
[auth0] Add missing parameter for ResetPasswordEmailOptions

### PR DESCRIPTION
**Pull request by martin-badin**
Discussion: #58553

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test auth0`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <[requestChangePasswordEmail](https://auth0.github.io/node-auth0/AuthenticationClient.html#requestChangePasswordEmail)>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by danursin — CHANGES_REQUESTED** [review]
client_id is not required by the reset password call. Omitting it falls back to the tenant values. This would be breaking to merge as is. It should be optional.

**Comment by martin-badin** [comment]
> client_id is not required by the reset password call. Omitting it falls back to the tenant values. This would be breaking to merge as is. It should be optional.

I can set it as optional but are you sure? I don't see in the documentation that is optional.

**Comment by danursin** [comment]
I mean, it hasn't been a parameter of the call all this time and the behavior, whether intentional or not, is currently that the call succeeds without client_id. I'm open to others opinions. I agree the parameter should be supported since it is documented and useful. But any user of the sdk right now is not passing it without some typescript trickery so it would break some apps if it were required.

**Comment by martin-badin** [comment]
> I mean, it hasn't been a parameter of the call all this time and the behavior, whether intentional or not, is currently that the call succeeds without client_id.

it makes a sense

**Comment by danursin** [comment]
I guess my question is: should the types reflect the docs, which don't list it as optional? Or should they reflect what we know the behavior to be, that the API will accept calls without client_id?

**Review by danursin — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Comment by martin-badin** [comment]
@danursin it seems it is optional
https://github.com/auth0/node-auth0/blob/08d23024e4051516bd2fbb8c8ab94d4b8ef42c9a/src/auth/DatabaseAuthenticator.js#L256

**Comment by saewitz** [comment]
Thanks. I think it should be optional, because I was able to run it without it, but adding it provides additional functionality.

**Comment by jketcham** [comment]
> I guess my question is: should the types reflect the docs, which don't list it as optional? Or should they reflect what we know the behavior to be, that the API will accept calls without client_id?

I think it's best to have these types reflect what's actually in the code (auth0's docs are not that great sadly).

Thanks for this change, just ran into the need for it today!

**Pull request merged**
