### PR TITLE
Add graphite module declarations

### PR DESCRIPTION
**Pull request by ctumolosus**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by ctumolosus** [comment]
Initial commit added intentionally to show direction I tried to take prior to switching to using `any` as the type annotation for all parameters and return types. Technically, the [`graphite`](https://www.npmjs.com/package/graphite) module accepts anything but won't report invalid values. For example:

```js
import graphite from 'graphite';
const client = graphite.createClient('...');
client.write({ foo: new Date() }); // reports {}
client.write({ foo: 1 }); // reports { foo: 1 }
client.write({ foo: { bar: { qux: 3 } } }); // reports { 'foo.bar.qux': 3 }
client.write('foo'); // reports { 0: 'f', 1: 'o', 2: 'o' }
// Etc.
```

**Comment by ctumolosus** [comment]
This pull requests introduces type definitions for the [`graphite`](https://www.npmjs.com/package/graphite) package.

P.S.

I intended to use the following types for the `metrics` and `tags` parameters, but apparently I cannot use an index signature to constraint the type for interface properties. So, I decided to use `any` as the type annotation instead.

```ts
type MetricValue = number | MetricObject;
type MetricObject = { [key: string]: MetricValue };

type TagValue = string | TagObject;
type TagObject = { [key: string]: TagValue };

declare class GraphiteClient {
  write(metrics: MetricObject): void;
  writeTagged(metrics: MetricObject, tags: TagObject): void;
}
```

**Comment by jessetrinity** [comment]
>I intended to use the following types for the metrics and tags parameters, but apparently I cannot use an index signature to constraint the type for interface properties. So, I decided to use any as the type annotation instead.

Do you have an example of the usage that wasn't working?

**Comment by ctumolosus** [comment]
You can preview the example below in the [TypeScript Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=58&pc=40#code/C4TwDgpgBAshwCcCWBjAagQwDYFdoF4oA7HAWwCMIEoAfWeZFAeXICsIVgBuAWAChQkeolQt2nKIQDeUANoBrCCABcUAM4iiAcwC6quCPTY8UAL68+-AGY4inJAHsiUAO7JgEABSkGqNft9mNg5gAEpVADcHJAATKClTfn4kIg8EKwwUaDhSBwQQA0Z4-igoYAdgbFUSCioLUpw1CBjqskoEeqgrBAgIVtqO-kTLPhS0jKyoJjVC1GK+Up9c-IB+AOWCwK5SoaS+FCcNKCW8lXoN2ZRJedLu3tUARgAGABoSqEbmx9f38sqsVQAJh+fHMewORCODn8UxmgWuCQs-AA9MioABhDBEIgVKBgBAOCKxaBYqBjKgTElqKAYY7wsAYBAYHxpZR7VFQACCCC0ZAgqSgDisZXA0AA5DlTpcxWTqTjgDS1GokFoiBhyFhoOU8YzmfAqILhYJxZcxCExQA6FFo0oASSIMQgAA91Cq1cAcD1ZcckEqUloyc5jVAJRALoFLZ5AQBmAAsAFZQvw3EgPN4w6dQki+BzOa48vJGQ5bC09sH0Q5SAzgEgNRAADwAFReUAAqgA+BHvWQAaUDUEUICFUEbehHvZ0UGdHgd1NbUBW457k+qEAidV2IxsdhrTlc7ggaEBTfb6cMMIrVYwNbrTZbl0wuAg7fCUCisXiw2TB6P6Y2WagDkiFQCAAEJ2TRAAJBwXDXKgWxcPJgAAC2ICp-TKZDr0w318wQQsCRLKAYgcCA5VxTIsjABUHGoxw1SwPECUgBAazIltrVcZDUFQ3DKIgaj1U1fsUNwlAMCaKBKHEz4oHErBNWoUhGgVCBU2Qg18UJYkaS6LBsLyKBOKIMiPDiBxggkYcanaNQrRGXMeT5AVh2DMVpmlb15UVZVVSErUHB1JkWQNVzRRDS9q1rTV6xkE5VnWKV4ToEsICsFJmm2Ux70CR88HbS1OJHUVqWHLSWNAEN4pAGVGWgFIDivG9NXsjlSmKoRQ3DQxaA+B00oymIZVw7yJN8tU6zKQK3NS9KTKG1qbXajqTQzfJPJGii-T8ybtRm-q5uaSMYwTJM+BTDxf2hLMIK5LA1AcFsULI6BEKIMUFUQ-D7M4xtwq6pLDGG8iFTGt1-KmkVOpM9cEGO6NAUBM6LsPQFPDitaQDMG6HLRP7OsldaIy8rbxohvb-phqh4cR5GfzRmRoVUDGNjMbHs1zBVROpMBogFW1iI4Yk4m1WSsRAC0oCAA):


```ts
type MetricValue = number | MetricObject;
type MetricObject = { [key: string]: MetricValue };

function write(metrics: MetricObject): void {}

interface MemoryMetric {
  total: number;
  used: number;
  free: number;
}

interface OsMetric {
  memory?: MemoryMetric;  
}

const memory: MemoryMetric = {
  free: 10,
  used: 10,
  total: 20,
};

const os: OsMetric = {};

// Cannot provide an interface as a metric parameter:

// Argument of type 'MemoryMetric' is not assignable to parameter of type 'MetricObject'.
//   Index signature is missing in type 'MemoryMetric'.(2345)
write(memory);

// A workaround:

type Compatible<T, U> = {
  [K in keyof T]: T[K] extends U ? T[K] : never;
}

function writeV2<T>(metrics: Compatible<T, MetricValue>): void {}

writeV2(memory); // nice!

// However, worth noting that this workaround does not accept optional properties, 
// which is acceptable in this case because caller must either provide a flat or 
// nested object of numbers.

// Argument of type 'OsMetric' is not assignable to parameter of type 'Compatible<{ memory?: MemoryMetric | undefined; }, MetricValue>'.
//  Types of property 'memory' are incompatible.
//    Type 'MemoryMetric | undefined' is not assignable to type 'undefined'.
//      Type 'MemoryMetric' is not assignable to type 'undefined'.(2345)
writeV2(os);

// Also, these won't work.

// Type 'MemoryMetric' is not assignable to type 'never'.(2322)
writeV2({ memory });

// Type 'MemoryMetric' is not assignable to type 'never'.(2322)
writeV2({ os: { memory } });

// At this point I decided to use any. 
```

**Comment by ctumolosus** [comment]
I believe it's related to this issue: 
https://github.com/microsoft/TypeScript/issues/15300

**Comment by jessetrinity** [comment]
Nice find. Does it makes sense to change those interfaces to [types](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024)?

**Comment by ctumolosus** [comment]
I rather not enforce a preference between interfaces and type aliases. 

If acceptable by the community, I would be happy to introduce the workaround with the caveat that nesting interfaces in object literals will yield compilation errors.

**Pull request merged**
