### PR TITLE
[cache-manager-ioredis] add ambient namespace declaration

### PR DESCRIPTION
**Pull request by hackycy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test cache-manager-ioredis`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: No reference URL.
its declaration uses namespaces to define its CacheManagerIORedis. For the TypeScript compiler to see this CacheManagerIORedis, so add ambient namespace declaration. 

fix after, i can use this, example
``` typescript
import { RedisSingleNodeStore } from "cache-manager-ioredis";

function getStore(): RedisSingleNodeStore {
  return redisCache.store;
}
```

### CODE REVIEW

**Comment by hackycy** [comment]
@hongyiweiwu Hi，Do you have time to take a look at this PR 🙋‍♂️

**Review by hongyiweiwu — COMMENTED** [review]
Thanks for the changes! Is there any reason we’re declaring var instead of const? I don’t have other issues with this.

Also it seems the test is failing. Can you take a look? I will investigate as well tomorrow.

**Comment by hackycy** [comment]
@hongyiweiwu  thanks reply，I think the use of var definition is more open, and the use of const is more rigorous. It has no other meaning.
 I tried to run `npm test cache-manager-ioredis` which is no problem. 
The CI error seems to be caused by other package errors in `npm run test-all`.

**Comment by hongyiweiwu** [comment]
Cool. Do you mind changing it to const? My concern is in the original [code](https://github.com/dabroek/node-cache-manager-ioredis/blob/master/index.js) the object is a const one, so our typing should reflect that. After that we can try to merge it.

**Comment by hackycy** [comment]
@hongyiweiwu No problem, I have already submitted the changes

**Review by hongyiweiwu — APPROVED** [review]

**Comment by hongyiweiwu** [comment]
Thanks so much! Approved.

**Pull request closed without merging**
