### PR TITLE
use union type instead of intersection type

### PR DESCRIPTION
**Pull request by abdulkareemnalband**
item can be one of given type not all at once

### CODE REVIEW

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT or @Zlatkovsky, could you please take a look at this Outlook Item change?

**Comment by ElizabethSamuel-MSFT** [comment]
@abdulkareemnalband Thanks for taking time out to work on this! It's a little unusual to do intersection instead of union but it is our intention to merge all the members of the entire Item object hierarchy as the item property type, hence the [intersection notation](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types).

As such, we won't take this change at this time.

We appreciate your choosing to develop Office Add-ins and if you come across any other discrepancies or want to suggest improvements, do let us know.

Thanks again!

**Review by ElizabethSamuel-MSFT — CHANGES_REQUESTED** [review]
We would like to leave the property type as is with & instead of |. Thanks.

**Comment by abdulkareemnalband** [comment]
@ElizabethSamuel-MSFT AFAIK item can be one of `ItemCompose , ItemRead , MessageRead , MessageCompose , AppointmentRead , AppointmentCompose`, so it will contain properties/methods of only one type, not all at once.

By using union type we can implement [type garuad](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) by checking value of `item.itemType` for example
```ts
function isAppointmentCompose(item: Item | ItemCompose | ItemRead | MessageRead | MessageCompose | AppointmentRead | AppointmentCompose): item is Office.AppointmentCompose {
    return item.itemType === Office.MailboxEnums.ItemType.Appointment && !!item.saveAsync;
}
```

with intersection type we cannot do that.

**Comment by ElizabethSamuel-MSFT** [comment]
@abdulkareemnalband That's a good point you raise. However, for now, we will leave it as is since it'll give us the correct IntelliSense behavior (i.e., showing all members available to the item property).

We're in the process of re-organizing Item and its subclasses and will keep in mind your point about type guard.

Thanks.

**Comment by abdulkareemnalband** [comment]
@ElizabethSamuel-MSFT so i will close this PR for now
we could revisit this later

**Pull request closed without merging**
