### PR TITLE
Add missing angular.bootstrap() typings

### PR DESCRIPTION
**Pull request by bcherny**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/angular/angular.js/blob/1daa4f2231a89ee88345689f001805ffffa9e7de/src/Angular.js#L1818
  - https://github.com/angular/angular.js/blob/1daa4f2231a89ee88345689f001805ffffa9e7de/src/Angular.js#L1858
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by thorn0** [comment]
> We do not support exposing undocumented internal implementation details of libraries in .d.ts files. We follow this more strictly for popular libraries with good documentation e.g. jquery, angular, node etc.

-- http://definitelytyped.org/guides/contributing.html#private-apis

**Comment by bcherny** [comment]
@thorn0 Updated the title. These are part of Angular's external API.

**Comment by thorn0** [comment]
Where are they documented then?

**Comment by bcherny** [comment]
`resumeDeferredBootstrap` is a public method, similar to the existing `resumeBootstrap`.
`debugInfoEnabled` is a flag on a public method, similar to `strictDi`.

They should be in the Angular docs - that they are not there is a doc issue, I think.

**Comment by paulvanbrenk** [comment]
@bcherny can you open an issue on angular to update their docs? I agree with @thorn0 that we shouldn't take this until then.

Closing for now, do feel free to re-open when the docs are updated.

**Pull request closed without merging**
