### PR TITLE
added missing chrome.enterprise.deviceAttributes:

### PR DESCRIPTION
**Pull request by ekinsol**
added missing chrome.enterprise.deviceAttributes:

* getDeviceSerialNumber
* getDeviceAssetId
* getDeviceAnnotatedLocation (with comments based on @types/chrome-apps)

* [x]  Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/extensions/enterprise_deviceAttributes

### CODE REVIEW

**Comment by minestarks** [comment]
Do you have a documentation reference for the remaining changes?

**Comment by ekinsol** [comment]
> Do you have a documentation reference for the remaining changes?

Dear Minestarks,

The changes are based on these API Calls: https://developer.chrome.com/extensions/enterprise_deviceAttributes

Kind Regards

**Comment by minestarks** [comment]
@ekinsol - Thanks, but I meant the big new module `chrome.system.display`, which is the larger part of the change. These seem unrelated to the `deviceAttributes` change - is there a separate documentation for that?

**Comment by ekinsol** [comment]
@minestarks - My apologies, yes there is: https://developer.chrome.com/apps/system_display

**Comment by minestarks** [comment]
@ekinsol Thank you!

**Pull request merged**
