### PR TITLE
[Sequelize] Model association mixins + Tests 

### PR DESCRIPTION
**Pull request by alitaheri**
~~Plus some minor breaking changes. But these are final and production ready~~
Continuation of #6058

Associations:
- [x] belongsTo
- [x] hasOne
- [x] hasMany
- [x] beongsToMany

### CODE REVIEW

**Comment by subjectix** [comment]
@horiuchi I added tests for #6058 too, and made small breaking changes. The names had to be fixed to be consistent with the future additions. If it's all good please merge this too. tnx ^^

**Comment by vvakame** [comment]
*sequelize/sequelize.d.ts*

to authors(@samuelneff @codeanimal @drinchev). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by subjectix** [comment]
P.S. the breaking changes are from my own previous PR, I had to make the naming consistent :grin:

**Comment by drinchev** [comment]
:+1: 

Thanks @subjectix .

**Comment by subjectix** [comment]
@drinchev You're welcome. But don't thank me just yet :D there are 2 more associations left. I need do make sure I fully understand the api they provide before I can write those too.

**Comment by vvakame** [comment]
I'll wait a 2 days. please ping me again.
@drinchev thank you for reviewing!

**Comment by horiuchi** [comment]
LGTM :+1:

**Comment by subjectix** [comment]
@vvakame @drinchev @horiuchi I'm done. Please review. Thank you.

P.S. Should I rebase + squash?

**Comment by drinchev** [comment]
On my side is good :+1: 

I have ~ 20 models NodeJS Sequelize project with big relations between the tables. It compiled with no errors.

I guess we need to figure out some sort of README on how to use the definition file. I was thinking on making one when I was rewriting them for v3. Now the definitions are even more powerful :)

Good work @subjectix !

**Comment by subjectix** [comment]
@drinchev Thank you. I was planing to do that to, or even go further and make a generator like [sequelize-auto-ts](https://github.com/samuelneff/sequelize-auto-ts). Except that mine would generate based on the logical models defined within the code just like `sequelize.sync()`. It's a lot of work :cold_sweat:, I have to find a lot of time to do that.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
