### PR TITLE
ws: add address method to Server

### PR DESCRIPTION
**Pull request by thw0rted**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [method documentation](https://github.com/websockets/ws/blob/master/doc/ws.md#serveraddress)
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. N/A

### CODE REVIEW

**Review by orblazer — APPROVED** [review]

**Comment by mantyz** [comment]
@thw0rted, @orblazer The documentation indicates that the address method can return a string https://github.com/websockets/ws/blob/master/doc/ws.md#serveraddress
Please, see my old [pull reques](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24489) which was not merged due to Travis error https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24489#issuecomment-375755675
I believe that it is necessary to make corrections. 
Thanks.

**Comment by mantyz** [comment]
@thw0rted From [nodejs doc](https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_address)
`For a server listening on a pipe or UNIX domain socket, the name is returned as a string.`
For [example ](https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_address) if you listen socket `/tmp/echo.sock` then server.address() retrun this socket name.
But if we look at the implementation of the  [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e94c84bd5e2136d9e1acd42ee662ac0193abed10/types/node/v8/index.d.ts#L2742) address method, then this is exactly the same (but what if I want to work with string methods).
Let's leave it as it is. Thanks for your time.

**Comment by thw0rted** [comment]
If I have the free time, I was thinking of adding a named interface to Node for the 3-field version (`dgram` already has an `AddressInfo`) then using that named interface for all the various `address()` methods.  It sounds like the signature should actually be `address(): AddressInfo | string`.  Then, the same pattern (exported, named interface) could be carried over to `ws`.  I don't know if DT would accept changes to both types in a single PR, but it makes sense to me.

**Comment by mantyz** [comment]
It sounds good.

**Comment by thw0rted** [comment]
Trackback to #25597

**Pull request merged**
