### PR TITLE
[twitch-ext] Add typings for Twitch Extension helper

### PR DESCRIPTION
**Pull request by beheh**
:wave: Hi there!

I've been using this in our [Twitch Extension](https://github.com/hearthsim/twitch-hdt-frontend) for quite some time, and have now polished the typings for submission here. The typings refer to the [Twitch Extension Javascript Helper](https://dev.twitch.tv/docs/extensions/reference/#javascript-helper
), which is a CDN-provided file that is loaded by every Twitch Extension. Twitch Extensions are small bundles containing some Javascript that are uploaded to [Twitch](https://www.twitch.tv/) that broadcasters can enable on their channel for some interactive features. The helper typed in this PR is used to facilitate some of the interactive features and provide the extension with some contextual details so it can optimize how it displays itself.

I typed based on the official documentation (especially for most of the comments), but to my best knowledge it is correct as it works in our application. The package name here is based on the actual Javascript helper file ([https://extension-files.twitch.tv/helper/v1/twitch-ext.min.js](https://extension-files.twitch.tv/helper/v1/twitch-ext.min.js)), and that's also where the version comes from (the same as reported by `Twitch.ext.version`).

I'm pretty happy with where this is, and I think I've resolved most of the typing uncertainties I had. There's one function in here where I'm not quite sure and the typing could probaby be improved, which is `onContext`: The existance of a property in `changed` guarantees that it exists in `context` - I tried to map that with the generic `<T extends Partial<TwitchContext>>`, but I'm not sure whether there's a more elegant way.

Either way, looking forward to feedback and seeing this released!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks so much for contributing this back to the community! I am somewhat concerned that we may eventually step on the `twitch-ext` package name and that we'll have to rename this one. Maybe it'd be a good idea for you to reserve the `twitch-ext` package first?

While I hate to bother others, I wonder if any developers at Twitch have some thoughts on this. @davecusatis @Tenchumaru are there any approaches Twitch takes for using `Twitch.ext` in TypeScript? Will there ever be an npm package?

**Comment by beheh** [comment]
I haven't reserved the `twitch-ext` package on npm because from what I understand that's a big no-no if one doesn't intend to publish any code there (see the [npm disputes doc](https://docs.npmjs.com/misc/disputes)).

**Comment by DanielRosenwasser** [comment]
I think for now we'll just roll with `@types/twitch-ext`.

**Comment by Tenchumaru** [comment]
Thank you for this contribution. We have no expectation of creating any npm packages.

**Pull request merged**
