### PR TITLE
[node] Fix `events` module so it matches runtime behaviour

### LINKED ISSUE #45469: Missing some 14->12 backports in Events
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @BrunoScheufler @smac89 @tellnes @Touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias @ExE-Boss @Ryan-Willpower @peterblazejewicz

There were several backports from v14 to v12 in Events (versions 12.16 and 12.17). Search for "Added in: v12" in [the docs](https://nodejs.org/docs/latest-v12.x/api/events.html).

List;
* `EventEmitter.errorMonitor`
* `emitter[Symbol.for('nodejs.rejection')](err, eventName[, ...args])`
* `events.captureRejections`
* `events.captureRejectionSymbol`
* `events.on(emitter, eventName)`

Can you please add them to @types/node? Thank you.

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
	- <https://nodejs.org/api/events.html#events_class_eventemitter>
	- <https://github.com/nodejs/node/blob/2c8751cb855af0b93a92286e82c0c1ca4fd3bfdc/lib/events.js#L83-L91>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Fixes <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45469>

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@ExE-Boss merge at your discretion, thx!

**Comment by ExE-Boss** [comment]
Ready to merge

**Comment by vasco-santos** [comment]
This PR created issues while generating typescript declarations from JS. We used to do:

```js
const { EventEmitter } = require('events')

class X extends EventEmitter {}
```

now, I am seeing errors as follows:

```
TS9006: Declaration emit for this file requires using private name 'EventEmitter' from module '"events"'. An explicit type annotation may unblock declaration emit.
```

**Comment by ExE-Boss** [comment]
@vasco-santos That seems like a bug in **TypeScript**.

**Comment by vasco-santos** [comment]
@ExE-Boss I opened an issue in TypeScript for further analysis.

**Comment by SimenB** [comment]
This (I believe) broke

```
import * as events from 'events';

console.log(events.once);
```

Running that in Node prints `[Function: once]`, but TypeScript fails with `TS2339: Property 'once' does not exist on type 'typeof EventEmitter'.`

**Pull request merged**
