### PR TITLE
[webdriverio] Append is* to wdio Client definition

### PR DESCRIPTION
**Pull request by RonanDrouglazet**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webdriverio/webdriverio/blob/master/test/spec/unit/mobileDetector.js#L5

### CODE REVIEW

**Review by timbru31 — CHANGES_REQUESTED** [review]
Please move them to the corresponding mobile part of the Client interface, they seem to make more sense there.
It's in Line 792 (https://github.com/ebuzzing/DefinitelyTyped/blob/c59873dd583b69048b1970e208bd1aafa0dc0cbc/types/webdriverio/index.d.ts#L792-L793)

**Comment by timbru31** [comment]
Thanks @RonanDrouglazet for your addition of these (undocumented) properties. IMO it's more fitting in the `Mobile` section of the Client interface.

**Comment by RonanDrouglazet** [comment]
Ok thanks I will move them to the mobile part 

A little hidden but ... http://webdriver.io/guide/testrunner/browserobject.html#Check-if-capability-is-a-mobile-device ^^

**Comment by RonanDrouglazet** [comment]
It's done @timbru31 ;)

FYI I will make one or two other PR, I don't want to put too much uncorrelated modification in one PR

**Review by timbru31 — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
