### PR TITLE
[@types/node] Types for Node v20.13.1

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/nodejs/node/pull/52793

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test node`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/v8.d.ts
1. types/node/util.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 740160342bd0dde07483c1bf0c634519554fb321
</p>

**Comment by MattIPv4** [comment]
👋 Out of curiosity, what is blocking this being reviewed/landed? Node 20.13 has been out for quite a while now.

**Comment by codershiba** [comment]
> 👋 Out of curiosity, what is blocking this being reviewed/landed? Node 20.13 has been out for quite a while now.

Sorry I got busy with my college entrance exams and lost track of this.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/perf_hooks.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7cbf6a0b8d896092241b4a9a0c20b83845b3a11c
</p>

**Review by sheetalkamat — APPROVED** [review]

**Comment by codershiba** [comment]
Ready to merge

**Comment by codershiba** [comment]
Oops, @sheetalkamat I forgot to bump version in `package.json`, what should I do now?

**Comment by jakebailey** [comment]
Ugh. We will need to revert, republish, then revert the revert with the bump.

**Pull request merged**
