### PR TITLE
[node] make buffer.compare(otherBuffer) return a more narrow type

### PR DESCRIPTION
**Pull request by rikbw**
This is a follow up to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58630

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
👍

**Comment by peterblazejewicz** [comment]
@rikbw pls rebase from master and force push, to pass CI, if it still fails (I'll rerun it now)

**Review by peterblazejewicz — APPROVED** [review]

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ali-oss ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ali-oss@latest/))
was missing the following properties:
1. initOptions
## hellosign-sdk ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hellosign-sdk@latest/))
was missing the following properties:
1. DEFAULT_HOST
1. DEFAULT_PORT
1. DEFAULT_BASE_PATH
1. DEFAULT_API_VERSION
1. DEFAULT_TIMEOUT

<details>
<summary>as well as these 5 other properties...</summary>
<p>PACKAGE_VERSION, USER_AGENT, USER_AGENT_SERIALIZED, HelloSignResource, resources</p>
</details>

## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 868952ceab7e56c355eff66c76c10ca3167905ca
</p>

**Review by peterblazejewicz — APPROVED** [review]

**Comment by rikbw** [comment]
Ready to merge

**Pull request merged**
