### PR TITLE
tape: update to v5.8

### PR DESCRIPTION
**Pull request by ljharb**
Followup to #71428 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: npmjs.com/tape
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/tape/index.d.ts
1. types/tape/tape-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2db25370af381554436d4e24a0e59c63435b0987
</p>

**Comment by ljharb** [comment]
would be great to get this landed :-)

**Comment by ljharb** [comment]
ping @jakebailey, since you approved the precursor PR?

**Review by jakebailey — APPROVED** [review]

**Comment by ljharb** [comment]
Ready to merge

**Pull request merged**
