### PR TITLE
fix(passport): done callback arguments

### PR DESCRIPTION
**Pull request by bodinsamuel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Since this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49723
the type is more strict but it's also not entirely accurate.
For example: You can invalidate a session by passing done(null, false); 
 
https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/authenticator.js#L338-L340
```js
    // a valid user existed when establishing the session, but that user has
    // since been removed
    if (user === null || user === false) { return done(null, false); }
```

### CODE REVIEW

**Comment by smichel17** [comment]
Is there more context on why this was closed? It seems like the correct type to me.

As a workaround for now, you can "fix" this with
```typescript
done(null, null as any)
```

**Comment by bodinsamuel** [comment]
Closed by mistake

**Review by amcasey — APPROVED** [review]

**Comment by bodinsamuel** [comment]
Ready to merge

**Comment by bodinsamuel** [comment]
Thanks @amcasey

**Pull request merged**
