### PR TITLE
fix(pull-stream): `pull` function supports parameters of type Duplex(…

### PR DESCRIPTION
**Pull request by jacobbubu**
…`{source, sink}`).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jacobbubu/DefinitelyTyped/issues/2
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## pull-stream ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pull-stream@latest/))
was missing the following properties:
1. pull
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 69c8c3cb0cec4620863ee3a77a488fae6769edf3
</p>

**Review by jacobbubu — COMMENTED** [review]
It is difficult to cover all boundary use cases, at least the current test code covers most of them.

**Comment by jacobbubu** [comment]
@mjwwit Can you review the pull-request for me?

**Review by mjwwit — APPROVED** [review]
LGTM

**Comment by jacobbubu** [comment]
Ready to merge.

**Pull request merged**
