### PR TITLE
[history]: rename `createBrowserHistory` to `createHistory `

### PR DESCRIPTION
**Pull request by legomushroom**
`createBrowserHistory ` was only introduced in the `history@4.0.0-1`
prior to that the `createHistory` was used. So if you will install
`@types/history@^2.0.0` and `history@^2.0.0`(or even `^3.x.x`) it will
break with the next error:
```
./src/client/history.ts
(1,10): error TS2305: Module ‘”/@types/history/index"' has no exported
member 'createHistory'.
```
This commit brings the `createHistory` back thus solves the issue for
`history@^2.x.x` and `history@^3.x.x`.

-----

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/mjackson/history/blob/v2.x/README.md#installation>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Any idea what [this failure](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/194634222#L1649-L1657) is being caused by @andy-ms?

**Comment by ericanderson** [comment]
It seems react-router-redux on this branch depends on react (as expected) but doesnt have a header `// TypeScript Version: 2.1` Likely a semantic merge issue from my big react change that went into today. I'll put a PR to fix that, then you need to merge in master or rebase.

**Comment by ericanderson** [comment]
There is more to it than that, investigating here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14204

**Comment by ericanderson** [comment]
@legomushroom Rebase onto master.

**Comment by legomushroom** [comment]
@ericanderson I'm a drip confused. I didn't create any branches to `rebase`, am I missing something?

**Comment by ericanderson** [comment]
LGTM

**Pull request merged**
