### PR TITLE
Export `TransitionStatus` from `react-transition-group`

### PR DESCRIPTION
**Pull request by lazytype**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-transition-group ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-transition-group@latest/))
was missing the following properties:
1. ReplaceTransition
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 44094e51106fca6e10220882d3432f5795f92127
</p>

**Comment by tu4mo** [comment]
Correct me if I'm wrong, but I think the `index.d.ts` should reflect the original [`index.js`](https://github.com/reactjs/react-transition-group/blob/master/src/index.js). There's no TransitionStatus variable. You can probably import the type directly from the `@types/react-transition-group` package if you need it.

**Comment by lazytype** [comment]
> Correct me if I'm wrong, but I think the `index.d.ts` should reflect the original [`index.js`](https://github.com/reactjs/react-transition-group/blob/master/src/index.js)

I don't see why that should apply to utility types. Popular libraries such as React and Redux have several of these exported.

**Comment by ybiquitous** [comment]
This change sounds good to me. Could you also change importing `TransitionStatus` in the following test, @lazytype?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7494af05ed0f7fc18636aef9bdd19b34f1958c16/types/react-transition-group/react-transition-group-tests.tsx#L2

**Comment by lazytype** [comment]
@ybiquitous sure

**Comment by ybiquitous** [comment]
Thanks 👍

**Review by ybiquitous — APPROVED** [review]
LGTM 👍

**Comment by tu4mo** [comment]
> I don't see why that should apply to utility types. Popular libraries such as React and Redux have several of these exported.

I stand corrected ☺️ LGTM.

**Comment by orta** [comment]
👍🏻

**Pull request merged**
