### PR TITLE
[zen-observable] Add 'zen-observable/esm' entry point

### PR DESCRIPTION
**Pull request by BenoitZugmeyer**
zen-observable added a `'zen-observable/esm'` entry point, exporting all code (index and extra) as an ES module. This PR add support for it.

Contrary to importing `'zen-observable'`, it doesn't expose the global namespace `ZenObservable`.  Instead, I find it nicer to exports types directly.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/zenparsing/zen-observable/blob/master/esm.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by sandersn** [comment]
This change looks reasonable to me, but I don't like merging changes to such a widely used package without some authors signing off.

@aicest @JounQin @itomtom 
Can you take a look?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Needs experts sign off

**Comment by BenoitZugmeyer** [comment]
What can I do to help this PR moving forward?

**Comment by JounQin** [comment]
Personally I'm not a fan of this, I think that a `module` property should be added instead into `package.json` of `zen-observable`.

There are a lot of packages which contains commonjs/esm entry at the same time, I don't think we should add two types files in favor of `esModuleInterop` option.

**Comment by BenoitZugmeyer** [comment]
A PR is open to add the "module" field https://github.com/zenparsing/zen-observable/pull/74

In the meantime, I don't think that's a discussion we should have here. I just adjusted types to follow the current upstream package API because I wanted to use it.

**Pull request closed without merging**
