### PR TITLE
[papaparse] - add skipFirstNLines config option

### PR DESCRIPTION
**Pull request by joshuaslate**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.papaparse.com/docs#config

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## papaparse ([<kbd>unpkg</kbd>](https://unpkg.com/browse/papaparse@latest/))
was missing the following properties:
1. BYTE_ORDER_MARK
1. ParserHandle
1. NetworkStreamer
1. FileStreamer
1. StringStreamer

<details>
<summary>as well as these 2 other properties...</summary>
<p>ReadableStreamStreamer, DuplexStreamStreamer</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2389d4768f97b357a6797e363e960702aa9aeac5
</p>

**Comment by joshuaslate** [comment]
> [mholt/PapaParse@e2d570e](https://github.com/mholt/PapaParse/commit/e2d570e77cc2720b2c256ec099f3e7e424c39e35)
> 
> this pr seems not published to npm yet

Ah, you're right, sorry. I'll close for now and re-open when it's up.

**Review by OpportunityLiu — CHANGES_REQUESTED** [review]
https://github.com/mholt/PapaParse/commit/e2d570e77cc2720b2c256ec099f3e7e424c39e35

wait for pr release and update dt version to match the lib version

**Comment by Jordan-w-99** [comment]
Can this be reopened? Looks like the PR mentioned above has now been released.

**Pull request closed without merging**
