### PR TITLE
@ember/owner: introduce `Resolver` type

### PR DESCRIPTION
**Pull request by chriskrycho**
Implements the next part of Ember RFC 0821. Compare the PR in the preview types: emberjs/ember.js#20253.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://rfcs.emberjs.com/id/0821-public-types/#resolver>

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember-resolver ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember-resolver@latest/))
was missing the following properties:
1. name
1. emberResolverFeatureFlags
1. init
1. treeForAddon
1. included

<details>
<summary>as well as these 1 other properties...</summary>
<p>monkeyPatchVendorFiles</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e574543eb66e061f649442152f677740a1370e66
</p>

**Review by dfreeman — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by chriskrycho** [comment]
Ready to merge

**Comment by mileszim** [comment]
@chriskrycho I'm getting this on app builds with the new types

```
node_modules/@types/ember-resolver/index.d.ts:11:10 - error TS2614: Module '"@ember/owner"' has no exported member 'Resolver'. Did you mean to use 'import Resolver from "@ember/owner"' instead?

11 import { Resolver } from '@ember/owner';
            ~~~~~~~~
```

**Comment by chriskrycho** [comment]
When you say "with the new types" do you mean `@types/ember__owner` or do you mean the Ember preview types?

**Comment by kiwi-josh** [comment]
@chriskrycho I also just hit this while upgrading our Ember app:
```
node_modules/@types/ember__engine/index.d.ts:15:10 - error TS2614: Module '"@ember/owner"' has no exported member 'Resolver'. Did you mean to use 'import Resolver from "@ember/owner"' instead?

15 import { Resolver } from '@ember/owner';
            ~~~~~~~~

node_modules/@types/ember__application/index.d.ts:17:17 - error TS2614: Module '"@ember/owner"' has no exported member 'Resolver'. Did you mean to use 'import Resolver from "@ember/owner"' instead?

17 import Owner, { Resolver } from '@ember/owner';
                   ~~~~~~~~

node_modules/@types/ember-resolver/index.d.ts:11:10 - error TS2614: Module '"@ember/owner"' has no exported member 'Resolver'. Did you mean to use 'import Resolver from "@ember/owner"' instead?

11 import { Resolver } from '@ember/owner';
            ~~~~~~~~

node_modules/@types/ember__debug/container-debug-adapter.d.ts:1:10 - error TS2614: Module '"@ember/owner"' has no exported member 'Resolver'. Did you mean to use 'import Resolver from "@ember/owner"' instead?

1 import { Resolver } from '@ember/owner';
```

However doing some digging, it looks like you are well aware of this (complex) situation 😄 
https://github.com/emberjs/ember.js/pull/20318

**Pull request merged**
