### PR TITLE
Added objectMode option to simple-peer

### PR DESCRIPTION
**Pull request by Jazcash**

### CODE REVIEW

**Comment by tlaziuk** [comment]
@Jazcash can you provide a reference for that change?
Have you consider version bump?

**Comment by Jazcash** [comment]
No idea what you mean by version bump, sorry, new to Typescript. The definition in DefinitelyTyped for Simple-peer was for version 6.1, Simple-peer is now at 8.1.1.

**Comment by sandersn** [comment]
Was the introduction of `objectMode` for simple-peer 8.1.1? Do you have a link to the PR in https://github.com/feross/simple-peer that introduced `objectMode`? If so, change the first line of `index.d.ts` to `8.1` instead of `6.1`

**Comment by aozgaa** [comment]
Waiting on resolution of versioning from @Jazcash

**Comment by mhegazy** [comment]
No response from other authors for over a week. Merging.

**Pull request merged**
