### PR TITLE
Make renderOrder nullable in VectorTileOptions

### PR DESCRIPTION
**Pull request by peszek90**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://openlayers.org/en/master/apidoc/ol.layer.VectorTile.html>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by iamthechad — COMMENTED** [review]
I'm ok with the changes, but it's probably a good idea to update the tests to reflect this change.

**Review by yairtawil — APPROVED** [review]

**Comment by osechet** [comment]
@yairtawill why did you approved the changes after @iamthechad asked for a test update? The quality of these definitions is already not very good since nobody has the time to improve them. If we don't enforce test update with each change, the situation will just get worse.

**Comment by yairtawil** [comment]
@osechet 
I agree with you, my mistake.

**Review by yairtawil — CHANGES_REQUESTED** [review]
update the tests to reflect this change

**Comment by tschaub** [comment]
@osechet or @yairtawil (or anybody else) - if you have any suggestions on how we could help publish TypeScript definitions for OpenLayers releases, please let me know.  I'll do a bit more reading and then open a ticket asking for help on the OpenLayers repo.

**Pull request merged**
