### PR TITLE
changed export = to export default so that submodules can be typed

### PR DESCRIPTION
**Pull request by evestraw**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14267

### CODE REVIEW

**Comment by Kovensky** [comment]
This is incorrect and will either require that you write code that will miscompile with `--allowSyntheticDefaultImports` or that will miscompile with real modules.

As can be seen in e.g. https://unpkg.com/lodash.add@3.7.0/index.js, the exports are done by assigning the function to `module.exports`, so `export =` is correct.

I am not sure what you mean by "so that submodules can be typed". I don't see why changing this to `export default` makes typing it easier.

**Comment by evestraw** [comment]
under typescript 2.4 and allowSyntheticDefaultImports not set
import assign from "lodash/assign"
reports /assign/index has no default export.
syntheticDefaultImports need to be turned on in order to use lodash
submodules

2017-07-26 11:11 GMT+02:00 Diogo Franco <notifications@github.com>:

**Comment by Kovensky** [comment]
Enabling `syntheticDefaultImports`, however, does not affect the code emit -- the emitted code will still attempt to access `.default` in the imported module, which does not exist. `syntheticDefaultImports` is specifically meant to be used in combination with a bundler or the systemjs runtime; `import assign from 'lodash.assign'` would always be incorrect under typescript's own (current) commonjs output.

**Comment by evestraw** [comment]
then i gues this pull request can be closed. 
and 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14267

might already have been solved?

**Comment by evestraw** [comment]
if you have the problem that this pr is supose to fix, allow synthetic defaults in compiler

**Pull request closed without merging**
