### PR TITLE
Add missing "multiple" prop to SelectField of material-ui

### PR DESCRIPTION
**Pull request by dobogo**
material-ui's SelectField component has a boolean prop named `multiple`.
It enables SelectField select multiple items.
However, current definition lacks it.
This PR adds `multiple` to `SelectFieldProps`.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://www.material-ui.com/#/components/select-field>>

### CODE REVIEW

**Comment by alitaheri** [comment]
@dobogo Would you please add definition for `selectionRenderer` too?

```ts
  selectionRenderer: (values: any[]) => string;
```

would do, thanks 😁

**Comment by dobogo** [comment]
@alitaheri I have added `selectionRenderer`.
It also can be used when multiple is false, and callback function will be passed a non-array value.
The callback can return a ReactNode.

**Comment by alitaheri** [comment]
@dobogo Yes you're right. I checked the implementation too. It passes in the value of the selected when not multiple as well :+1:

**Comment by theigor** [comment]
I just ran into this too. Came here to see if there was already a PR. 👍

**Comment by sheetalkamat** [comment]
@ngbrown @herrmanno @theigor @DaIgeb Can you please review

**Review by theigor — APPROVED** [review]
Looks fine by me. I haven't used selectionRenderer so I can't confirm that React.ReactNode is the right type here but if the tests pass, then I believe it. The only thing I'd say is the name of the PR should probably change to include selectionRenderer so it's a little more "meaningful" (per the first checkbox)

**Pull request merged**
