### PR TITLE
Added type definitions for electron-process

### PR DESCRIPTION
**Pull request by WillStreeter**
Please fill in this template.
- [ x] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by WillStreeter** [comment]
Used for create background ipcRender in Electron from project written in TypeScript

**Comment by vvakame** [comment]
*electron-process/electron-process.d.ts*

Checklist

* [X] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/electron-process - https://github.com/smith-kyle/electron-process#readme
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (electron-process-tests.ts or electron-process-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by WillStreeter** [comment]
thank you.. yes I will do so now... will this enable me to add it as
@types/electron-process in my package.json?

**Comment by vvakame** [comment]
yes. `@types` shipping from `types-2.0` branch.

**Comment by paulvanbrenk** [comment]
This PR seems to be abandoned. Please create a new PR targeting `types-2.0`.

**Pull request closed without merging**
