### PR TITLE
Fixed IReply definition

### PR DESCRIPTION
**Pull request by gedaiu**
Fix borisyankov/DefinitelyTyped#4986

### CODE REVIEW

**Comment by vvakame** [comment]
@jasonswearingen could you review this PR?

**Comment by bherila** [comment]
Anyone??

**Comment by vvakame** [comment]
please resolve conflict. I'll merge this PR.

**Comment by jasonswearingen** [comment]
hi, sorry I didn't see the first message.   yes looks good, except for the merge conflict.

**Comment by bherila** [comment]
Looks like the original author is very out of date. I rebased my own fork and fixed the whitespace in the file which was causing a merge conflict. I also added support for reply.state/unstate which was not in the d.ts file already (defined here: http://hapijs.com/api )

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
