### PR TITLE
update react-native so styles can be arrays

### PR DESCRIPTION
**Pull request by dannycochran**
This PR creates a generic ViewProp for use with all style attributes, so that every React component can be typed to receive an array of styles or just one style.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/view.html#style
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by gyzerok** [comment]
@dannycochran do styles for images need same enhancement?

**Comment by iRoachie** [comment]
I really don't like that implementation, it's very redundant, Why not just make a generic?

`type StyleProp<T> = T | Array<T> | undefined`

Then just pass in whatever.

`style: StyleProp<TextStyle>`

**Comment by dannycochran** [comment]
@iRoachie SGTM.
@gyzerok images are typed correctly but I'll use the generic pattern suggested by @iRoachie.

**Comment by newyankeecodeshop** [comment]
That's a great idea. The undefined needs to be in the array though:
```type StyleProp<T> = T | Array<T | undefined>```

**Comment by pocesar** [comment]
still missing the style for Text (which should be `style?: StyleProp<TextStyle>`)

**Comment by dannycochran** [comment]
@pocesar I think it's in there -- on what line do you think it's missing?

**Review by iRoachie — APPROVED** [review]

**Comment by alloy** [comment]
I feel like we should wait a little for @pocesar to be able to respond.

In the interim, @dannycochran the use of semi-colons is inconsistent, can you remove them everywhere?

**Comment by pocesar** [comment]
@dannycochran it was a module extension from another internal typing, the PR is ok, sorry for disrupting the review

**Review by iRoachie — APPROVED** [review]

**Comment by dannycochran** [comment]
@alloy done.

**Review by orta — APPROVED** [review]

**Comment by alloy** [comment]
Thanks!

**Comment by dannycochran** [comment]
newb question: do these types get automatically deployed to npm through types-publisher every hour or so?

**Comment by iRoachie** [comment]
Yup! You guessed it. Once the CI is operating well. Sometimes it may take longer. Would be awesome to have away to know when it’s live though.

**Pull request merged**
