### PR TITLE
[@types/aws-lambda]: tighten httpMethods; Allow generic APIGatewayProxyEvent

### PR DESCRIPTION
**Pull request by pubkey**
1. tighten httpMethods with all useable methods, [see](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)
2. Added test for APIGatewayProxyEvent, see [aws-docs](https://docs.aws.amazon.com/en_en/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html)
3. Allow generic APIGatewayProxyEvent so I can define a custom, more specific type from the existing APIGatewayProxyEvent-interface.
Please fill in this template.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/en_en/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html

### CODE REVIEW

**Review by simonbuchan — COMMENTED** [review]
I see this is an antipattern and wouldn't want this encouraged: specifically here it's likely that this is called from the public internet, and thus you can't assume anything about the types. Even if you do want to do this, I don't see why this PR is needed: it's about as easy to extend the proxy event type or simply cast the properties, and they at least stand out as something to investigate.

That said, if others here think this is a good idea, I won't argue against this further, as it is only opinion.

**Comment by pubkey** [comment]
@simonbuchan thanks for reviewing.
The problem is that it is not possible to extend an interface and overwrite the type to a more strict one.
For example this does not work:
```typescript
export interface CustomTypedEvent<MyGeneric = { [name: string]: string } | null> extends APIGatewayProxyEvent {
    pathParameters: MyGeneric;
}
```

Also what do you think about tighten the httpMethod?

**Comment by simonbuchan** [comment]
> it is not possible to extend an interface and overwrite the type to a more strict one.

Yes it is:

```ts
interface APIGatewayProxyEvent {
    method: string;
    pathParameters: { [name: string]: string } | null;
}

interface CustomTypedEvent extends APIGatewayProxyEvent {
    pathParameters: { custom: string; };
}
```

(though for some reason the above fails if `pathParameters` gets an interface instead of an (alias to a) object type)

The reason your example fails is that the `MyGeneric` parameter has no `extends` promising that `pathParameters` is going to still be compatible with the base type. This works, for example:

```ts
interface GenericEvent<Path extends { [name: string]: string }> extends APIGatewayProxyEvent {
    pathParameters: Path;
}

type CustomTypedEvent2 = GenericEvent<{ custom: string }>;
```

but there's not much point in my view, even if there wasn't the problem of it encouraging a bad assumption, since there's no obvious ordering for the parameters, so the shorter definition isn't any clearer (maybe if [named generic parameters](https://github.com/Microsoft/TypeScript/pull/23696) was added, but it looks like that's off the roadmap). In fact, the obvious single parameter is the type of body after parsing.

Regarding httpMethod, it has the same issue. There's a list of *defined meanings* for methods, but you can use whatever you want to as a client.

**Comment by pubkey** [comment]
@simonbuchan thank you for that great explanation. So stricting things with typescript is an antipattern if it is not sure that the data behaves the same at runtime. :+1:

Also your example code worked for me :smiley:

I'm closing this PR.

**Pull request closed without merging**
