### PR TITLE
Update N3 interface typings to be classes

### PR DESCRIPTION
**Pull request by joachimvh**
The main reason for the pull request was to change the typings for `StreamParser` and `StreamWriter` more consistent with how they are defined in the JavaScript [code](https://github.com/rdfjs/N3.js/blob/master/src/N3StreamParser.js#L6). Where the code extends a `Transform` stream, this is not exported in the current typings. 

For the `StreamParser` it was necessary to change the typings to a class instead of an interface due to conflicts between interfaces otherwise. More information on this [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45511#issuecomment-645212151) in a previous (cancelled) pull request. For consistency I then also changed the other interfaces to classes, which in my opinion also closer matches what the output would be if the original code was written in TypeScript.

I did not change the version number yet since I'm not sure what the best course of action is there. The only conflict with the previous version is that you no longer have a class `Writer` and a type `N3Writer`, there is simply the class and type `Writer` (similarly for all other classes).

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/rdfjs/N3.js/blob/master/src/N3StreamParser.js#L6
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## n3 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/n3@latest/))
was missing the following properties:
1. Lexer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against df2f347485aeba2c55e9dd14cadb6d4036340a9a
</p>

**Review by rubensworks — APPROVED** [review]
Looks good!
But this definitely should be a breaking change, so we should update the version at the top of the file to `2.0`.

**Comment by joachimvh** [comment]
I've updated the version number in the new push

**Comment by joachimvh** [comment]
Update: apparently the problem is that the typings can't have version 2.0 since that is not a valid version of N3.js? I could change to the latest (1.4), but that would not be a major increase though

**Comment by rubensworks** [comment]
> Update: apparently the problem is that the typings can't have version 2.0 since that is not a valid version of N3.js?

Not sure if the typing versions need to be in sync with the JS version.

If it really has to be, then 1.4 is fine I guess.

**Review by rubensworks — APPROVED** [review]

**Comment by joachimvh** [comment]
Ready to merge

**Pull request merged**
