### PR TITLE
Prefer to directly export values instead of `export =` of a namespace

### PR DESCRIPTION
**Pull request by ghost**
This pattern may exist elsewhere. These are all the *linted* files that triggered under a new lint rule (Microsoft/types-publisher#257).

### CODE REVIEW

**Review by Goldsmith42 — APPROVED** [review]
xsd-schema-validator looks OK.

**Comment by ChadBurggraf** [comment]
👍

**Comment by pe8ter** [comment]
👍

**Review by pe8ter — APPROVED** [review]
👍

**Comment by pocesar** [comment]
if you need to manually extend a declared namespace, how is that possible after this change?

**Comment by grahammendick** [comment]
`navigation-react/index.d.ts` looks good, thanks 👍

**Comment by andy-ms** [comment]
@pocesar you can still [augment](http://www.typescriptlang.org/docs/handbook/declaration-merging.html) the module itself.

**Comment by pocesar** [comment]
@andy-ms so it becomes

```ts
declare module 'react-native-fs' {
   export function someOverloadedDeclaration();
}
```

and it retains the ability to extend it?

**Comment by andy-ms** [comment]
Yep. One thing to watch out for is that the exact same code may be a declaration or augmentation depending on the context. If your declaration file is an external module (contains `import` or `export`), `declare module` is an augmentation. Otherwise, it's a declaration.
We should get around to documenting this. Microsoft/TypeScript-Handbook#250

**Review by pocesar — APPROVED** [review]

**Pull request merged**
