### PR TITLE
[mongoose-aggregate-paginate-v2] Support newer mongoose versions (current 7.x.x, for example)

### PR DESCRIPTION
**Pull request by Jokero**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Automattic/mongoose/tree/7.0.0. New major mongoose version has been released

### CODE REVIEW

**Comment by acrilex1** [comment]
Hi @Jokero can you please confirm you have tested the definitions against the newer versions? I did not have the chance to test it recently.

**Comment by Jokero** [comment]
@acrilex1 Hi. Yeah, I've tested with mongoose `7.0.1`

**Review by cw-alexcroteau — APPROVED** [review]

**Review by acrilex1 — APPROVED** [review]

**Comment by acrilex1** [comment]
Ready to merge

**Comment by Jokero** [comment]
@acrilex1 Thanks)

**Pull request merged**
