### PR TITLE
update bulma-calendar to 6.0.9

### PR DESCRIPTION
**Pull request by superhawk610**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Wikiki/bulma-calendar/blob/82ed4333c56a5861db5b3e948101ee56f710802f/src/js/datePicker/index.js#L259
https://github.com/Wikiki/bulma-calendar/releases
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bulma-calendar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bulma-calendar@latest/))
was missing the following properties:
1. bulmaCalendar
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a3e7af87b3e5ef92a8bdda36e59d8856290581cd
</p>

**Comment by superhawk610** [comment]
Judging from the existing types, I think it's fine that `bulmaCalendar` isn't exported (it's really just the default `export =` that we care about).

**Comment by remcohaszing** [comment]
My pull request to include the types in `bulma-calendar` has been accepted. I should have removed this package from DefinitelyTyped. (See https://github.com/Wikiki/bulma-calendar/blob/master/index.d.ts)

@superhawk610 could you create the pull request in https://github.com/wikiki/bulma-calendar instead?

**Comment by superhawk610** [comment]
Ah, cool. I'll open a PR against the main repo and then open a PR against DefinitelyTyped to get the types here removed, unless you've already done so?

**Pull request closed without merging**
