### PR TITLE
Openlayers v3.13.1 full API

### PR DESCRIPTION
**Pull request by jumpinjackie**
This is a TypeScript definition for OpenLayers v3.13.1 that covers the full API surface

The TypeScript definition is generated automatically by my TypeScript plugin for JsDoc (https://github.com/jumpinjackie/jsdoc-typescript-plugin)

This definition exposed some flaws in the existing tests that have also been corrected here:
- String constant classes like ol.geom.GeometryLayout were being passed to method that were expecting strings.
- Missing required properties in various option classes

### CODE REVIEW

**Comment by jumpinjackie** [comment]
Fixed broken test and squashed commit to one

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/openlayers/openlayers.d.ts#L3
please keep original author's name in definition header. author is main user & reviewer.

**Comment by mhegazy** [comment]
@jumpinjackie can you refresh this PR.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
