### PR TITLE
Remove Nuka Carousel

### PR DESCRIPTION
**Pull request by sarmeyer**
As of FormidableLabs/nuka-carousel#477, Nuka's type definitions are packaged with the library and are no longer needed in DefinitelyTyped.

cc @rawrmonstar

- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by matt-huh — COMMENTED** [review]
When will the version 4.4.6 released?

**Review by matt-huh — APPROVED** [review]
Thank you for making this world a little bit better!

**Comment by RomiC** [comment]
@sarmeyer, nice to hear! Thank you!

**Comment by DanielRosenwasser** [comment]
Thank you!

**Pull request merged**
