### PR TITLE
[google-apps-script] ran dprint fmt

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
👋 Hi! This PR is meant to let you know that we're going to be applying formatting automatically to all DefinitelyTyped packages[^1]. This PR is split out of:

* https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993: the discussion that includes backing context and our planned approach
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66235: onboards the repository to [dprint](https://dprint.dev)

This package is particularly huge (>1MB), so we're tagging you in an individual PR as a heads up. Please post here to let us know if you have any workflow needs that auto-formatting might disrupt[^2].

Cheers! 💖 

```shell
time npx dprint fmt types/google-apps-script/**/*.t*
Formatted 61 files.
npx dprint fmt types/google-apps-script/**/*.t*  1.19s user 0.34s system 177% cpu 0.865 total
```

[^1]: Note that formatting will be applied as a commit to `master` after each PR. PRs won't be blocked on any CI check for proper formatting. See #65993 for more information.
[^2]: For example, if this package is fully auto-generated (rather than manually edited), subsequent PRs might have a lot of noise from formatting differences. We can exclude it from formatting in that case.

### CODE REVIEW

**Comment by mtgto** [comment]
I'm an active maintainer of types/google-apps-script. I understand your detailed explanation.

> Please post here to let us know if you have any workflow needs that auto-formatting might disrupt

This package was originally auto-generated by those tools but hasn't been used for updates.
So you don't have to worry about it.

- https://github.com/motemen/dts-google-apps-script
- https://github.com/mtgto/dts-google-apps-script-advanced
- https://github.com/grant/google-apps-script-dts

Thanks.

**Comment by JoshuaKGoldberg** [comment]
Ah great! In that case I think we can close this out and let it be formatted in the main commit that formats everything. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Actually - instead of closing these individual ones out I'm going to start merging them in individually. That way we can get early testing of formatted packages, and revert individually if we need.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## lodash-es ([<kbd>unpkg</kbd>](https://unpkg.com/browse/lodash-es@latest/))
was missing the following properties:
1. commit
1. lodash
1. next
1. plant
1. thru

<details>
<summary>as well as these 13 other properties...</summary>
<p>toIterator, toJSON, value, valueOf, wrapperAt, wrapperChain, wrapperCommit, wrapperLodash, wrapperNext, wrapperPlant, wrapperReverse, wrapperToIterator, wrapperValue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bf577c2507d2c817c8f768a5210335d489802e28
</p>

**Comment by JoshuaKGoldberg** [comment]
#66528 was merged, so we can close this out. ✅

**Pull request closed without merging**
