### PR TITLE
Update opn typings for version 3.0.2

### PR DESCRIPTION
**Pull request by SomaticIT**
Hello,

This is an update for node module `opn` v3.0.2.

Thanks.

### CODE REVIEW

**Comment by vvakame** [comment]
*opn/opn.d.ts*

to author(@shinnn). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by shinnn** [comment]
Sorry for the late, late response. I'll review this in a few days.

**Comment by vvakame** [comment]
I'll merge this pull request in 2 days. :wink:

**Comment by SomaticIT** [comment]
Any updates ?

**Comment by horiuchi** [comment]
@SomaticIT Thanks mate!

**Pull request merged**
