### PR TITLE
[execa] update to v0.8, refactor definitions, fix issue with intersection types

### PR DESCRIPTION
**Pull request by mickdekkers**
### Changes

- Align types with execa v0.8
- Add JSDoc documentation for everything
- Restructure definitions file based on [chroma-js typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/097d2acf711df3ffb7a3df62554769b216876275/types/chroma-js/index.d.ts) to expose function return types such as `ExecaChildProcess`
- Fix being unable to pass a boolean to `shell` option due to an issue with intersection types

The types of the options objects were previously defined like this:
```ts
import { ExecOptions, SpawnOptions, SpawnSyncOptions } from "child_process";
type Options = SpawnOptions & ExecaOptions & ExecOptions;
type SyncOptions = SpawnSyncOptions & ExecaOptions & ExecOptions;
```

The problem lies in the `SpawnOptions & ExecOptions` part. These objects both have a `shell` property, but slightly different definitions:

`SpawnOptions`
```ts
{
  shell?: boolean | string;
}
```

`ExecOptions`
```ts
{
  shell?: string;
}
```
The intersection type of these properties (with `strictNullChecks` enabled) is
```ts
string | (undefined & string) | (string & undefined) | (true & string) | (false & string) | undefined
```
Which meant [you couldn't pass a `boolean`](https://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7B%0D%0A%20%20shell%3F%3A%20boolean%20%7C%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20B%20%3D%20%7B%0D%0A%20%20shell%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Foo%20%3D%20A%20%26%20B%0D%0A%0D%0Aconst%20value%3A%20Foo%20%3D%20%7B%0D%0A%20%20%20%20shell%3A%20true%0D%0A%7D%0D%0A).

See https://github.com/Microsoft/TypeScript/issues/12435 for more information.

### PR Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [sindresorhus/execa](https://github.com/sindresorhus/execa) with additional documentation from https://nodejs.org/api/child_process.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### Note to reviewers

Running `npm run lint execa` currently fails for `TypeScript@next` at lines [102](https://github.com/mickdekkers/DefinitelyTyped/blob/2ba36f6527124f0d460221e9de1464b520025ad8/types/execa/execa-tests.ts#L102-L105) and [110](https://github.com/mickdekkers/DefinitelyTyped/blob/2ba36f6527124f0d460221e9de1464b520025ad8/types/execa/execa-tests.ts#L110-L113) of `execa-tests.ts` with these errors:
```
ERROR: 102:45  expect  TypeScript@next compile error:
Argument of type '{ input: string; stdio: (string | null)[]; }' is not assignable to parameter of type 'Options | undefined'.
  Type '{ input: string; stdio: (string | null)[]; }' is not assignable to type 'Options'.
    Types of property 'stdio' are incompatible.
      Type '(string | null)[]' is not assignable to type '"pipe" | "ignore" | "inherit" | StdIOOption[] | undefined'.
        Type '(string | null)[]' is not assignable to type 'StdIOOption[]'.
ERROR: 110:34  expect  TypeScript@next compile error:
Argument of type '{ input: string; stdio: (string | null)[]; }' is not assignable to parameter of type 'Options | undefined'.
  Type '{ input: string; stdio: (string | null)[]; }' is not assignable to type 'Options'.
    Types of property 'stdio' are incompatible.
      Type '(string | null)[]' is not assignable to type '"pipe" | "ignore" | "inherit" | StdIOOption[] | undefined'.
        Type '(string | null)[]' is not assignable to type 'StdIOOption[]'.
          Type 'string | null' is not assignable to type 'StdIOOption'.
            Type 'string' is not assignable to type 'StdIOOption'.
```

This is because of [a recent bug in TypeScript](https://github.com/Microsoft/TypeScript/issues/19837) that causes it to incorrectly infer the type of
```ts
[null, 'ignore', null]
```
as
```ts
(string | null)[]
```
which is incompatible with
```ts
type StdIOOption = 'pipe' | 'ipc' | 'ignore' | Stream | number | null | undefined;
```
while other TypeScript versions correctly infer the type as
```ts
('ignore' | null)[]
```

This bug only affects the test code, not the type definitions themselves. The tests also pass for all other covered tsc versions. Because I did not change the definition of `StdIOOption` or the tests file, it is likely that this bug now also affects the previous execa definitions.

### CODE REVIEW

**Comment by mickdekkers** [comment]
Could a human look at this? It looks like the type inference bug has been fixed in TypeScript.

**Comment by douglasduteil** [comment]
Thanks @mickdekkers 
This is looking good to me.
Can't wait to try it :+1:

**Comment by douglasduteil** [comment]
> It looks like the type inference bug has been fixed in TypeScript.

Can you rebase or resolve the merge so the build go green :green_heart: ?

**Comment by mickdekkers** [comment]
@douglasduteil done! 😄

**Pull request merged**
