### PR TITLE
angular2-2.0.0-alpha.38

### PR DESCRIPTION
**Pull request by jimthedev**
Typings for angular2-2.0.0-alpha.38

### CODE REVIEW

**Comment by jimthedev** [comment]
@vvakame @horiuchi @johnnyreilly 

This is all ready. Thanks!

**Comment by vvakame** [comment]
@alexeagle can I merge this PR?

**Comment by alexeagle** [comment]
@jeffbcross was running the alpha.38 release - did you get to the step of generating typings?
@jimthedev thanks for the help! it's hard to review this many new lines, so it would be easier to review what process you followed to generate this?
Note that I'm currently working on a large project of distributing angular typings via NPM, and not using a bundle anymore, see https://github.com/angular/angular/issues/3082 .

**Comment by jimthedev** [comment]
@alexeagle, sure I ripped these right from the published npm release in the bundles/typings directory. I updated the angular-tests.js to use the new syntax for inputs/outputs. That's it.

**Comment by alexeagle** [comment]
Cool, thank you.
Another note: there were some critical bugs found in alpha-38 so a bugfix release is expected in the next couple days.

**Comment by jimthedev** [comment]
Cool, thanks @alexeagle

**Pull request merged**
