### PR TITLE
jasmine-ajax defs

### PR DESCRIPTION
**Pull request by lgrignon**

### CODE REVIEW

**Comment by horiuchi** [comment]
@lgrignon Thank you for your contribution.
Butt please fix the error on Travis CI: https://travis-ci.org/borisyankov/DefinitelyTyped/builds/63379036#L179

----
I propose that you would use `--implicitAny` parameter on the compile of `tsc` command.

**Comment by jpsfs** [comment]
Hi,
I was looking for this!

@horiuchi Something still preventing the merge of this PR?

**Comment by horiuchi** [comment]
@jpsfs No, nothing prevent the merging.

**Comment by jpsfs** [comment]
Hi,
@horiuchi Thank you for your quick reply.

Can you please do it?

Best regards,

**Comment by horiuchi** [comment]
@lgrignon Thanks mate!
@jpsfs Thank you for reviewing!

**Pull request merged**
