### PR TITLE
Update react-simple-tooltip to accept all valid React props

### PR DESCRIPTION
**Pull request by FOREVEREALIZE**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] ~Provide a URL to documentation or source code which provides context for the suggested changes:~ Types used to be invalid
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.~ It does not.

### CODE REVIEW

**Comment by jakebailey** [comment]
The error message looks like a bug in our lint rule; I will try and get a fix out for this.

**Comment by jakebailey** [comment]
Er, no, the lint rule is just breaking because the file doesn't parse. You'd need to write:

```
const component: React.FunctionComponent<SimpleTooltipProps>;
export default component;
```

**Comment by FOREVEREALIZE** [comment]
> Er, no, the lint rule is just breaking because the file doesn't parse. You'd need to write:
> 
> ```
> const component: React.FunctionComponent<SimpleTooltipProps>;
> export default component;
> ```

Using that snippet, testing fails for other reasons.

**Comment by jakebailey** [comment]
I think the only related error to that line was that I forgot `declare`, i.e. `declare const component`. (Or more typically, `declare const _default: ...; export default _default`.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/react-simple-tooltip/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f8ac6b4da3fe1ce0172cd59b84be4ede5296546
</p>

**Review by andrewbranch — APPROVED** [review]

**Comment by FOREVEREALIZE** [comment]
Ready to merge

**Pull request merged**
