### PR TITLE
@types/react-native add SectionList component

### PR DESCRIPTION
**Pull request by newyankeecodeshop**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/sectionlist.html

Ran `tsc` in the /types/react-native folder and no errors are reported.

### CODE REVIEW

**Comment by alloy** [comment]
Looks good to me. The lint failure is legit, though, and while you’re fixing those could you also put the items in the new interface in the same order they appear in the documentation?

**Comment by newyankeecodeshop** [comment]
sure, will re-arrange

**Comment by alloy** [comment]
Sure, that’s fine with me for now, we’re still figuring out the best way to make all of this the most maintainable 👍 

Will merge on 💚 CI.

**Comment by alloy** [comment]
Thanks! 🙏🏽

**Pull request merged**
