### PR TITLE
Update sequelize types in index.d.ts to support using transactions

### PR DESCRIPTION
**Pull request by aldentaylor**
Added Transaction to QueryInterfaceOptions to allow use of Transactions in calls using QueryInterfaceOptions

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.sequelizejs.com/manual/tutorial/transactions.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by todd** [comment]
According to the [docs](http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html), it's not clear to me that a lot of the `QueryInterface` methods accept `transaction` as a member of `options`, though I could be wrong here. Is there a particular method you're trying to patch here or some documentation you can point to to justify patching all `QueryInterface` methods?

**Comment by aldentaylor** [comment]
I can't find any doc to indicate this, but a read through of the methods in QueryInterface shows that they call sequelize.query, which does take transaction as documented here:
  http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-query

source for QueryInterface for reference: https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js

I'll keep looking for doc indicating that this is the case.

**Comment by aldentaylor** [comment]
I wish I could find something more definitive, but the only other thing that I found was on this page
http://docs.sequelizejs.com/class/lib/transaction.js~Transaction.html

Where they indicate: "To run a query under a transaction, you should pass the transaction in the options object."

**Comment by todd** [comment]
Cool, makes sense.

**Review by todd — APPROVED** [review]

**Pull request merged**
