### PR TITLE
[googletag] update doc comments for googletag

### PR DESCRIPTION
**Pull request by atwwei**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by 88v5 — APPROVED** [review]
:+1:

**Review by peterblazejewicz — APPROVED** [review]

**Comment by atwwei** [comment]
Ready to merge

**Comment by rashidul0405** [comment]
@atwwei Should this also expose a global variable like so? `declare var googletag: googletag`

**Comment by atwwei** [comment]
> @atwwei Should this also expose a global variable like so? `declare var googletag: googletag`

@rashidul0405 There is no need to do this unless the typescript version is too low。
If you need help, please describe in detail in a new issue。

**Pull request merged**
