### PR TITLE
[ramda] update ts-toolbelt version

### PR DESCRIPTION
**Pull request by regevbr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by regevbr** [comment]
@millsp I updated the ts-toolbelt version because the currently used version created a namespace collision with the move recent version that I use in my project.
I still can't fix some tests because there is some weird behavior with the way Curry works. Can you please help out with this PR?

**Comment by millsp** [comment]
Hmm, I think that this could be solved by intersecting the curried function type with the type of the function being curried. This should happen in ts-toolbelt of course. Maybe you can try editing the related `.d.ts` from ts-toolbelt in ramda locally, to quickly test that out?

**Comment by regevbr** [comment]
@millsp thanks for the suggestion! it fixes the current issues but creates a new interesting one...

```sh
Error: /types/ramda/test/dropRepeatsWith-tests.ts:5:9
ERROR: 5:9  expect  TypeScript@4.4 compile error: 
Type '(number | x)[]' is not assignable to type 'number[]'.
  Type 'number | x' is not assignable to type 'number'.
    Type 'x' is not assignable to type 'number'.
```

It merges the R.__ type into the return value 
```ts
  const x: number[] = R.dropRepeatsWith(R.eqBy(Math.abs), l); // => [1, 3, 4, -5, 3]
```

Here is what I changed in ts-toolbelt:
```ts
declare type _Curry<F extends Function> = <P extends Gaps<Parameters<F>>, G extends List = GapsOf<P, Parameters<F>>, R extends any = Return<F>>(...p: Gaps<Parameters<F>> | P) => RequiredKeys<G> extends never ? R : _Curry<(...p: G) => R>;
export declare type Curry<F extends Function> = F & _Curry<F>;
```

Your help is still needed :-)

**Comment by regevbr** [comment]
@millsp I solved it! insteading of using intersection, I used overloading:

```ts
export declare type Curry<F extends Function> = {
    <P extends Gaps<Parameters<F>>, G extends List = GapsOf<P, Parameters<F>>, R extends any = Return<F>>(...p: Gaps<Parameters<F>> | P): RequiredKeys<G> extends never? R: Curry<(...p: G) => R>;
    (...p: Parameters<F>): Return<F>;
};
```
I will create a PR in ts-toolbelt and once it is merged, I will update this PR accordingly

**Pull request closed without merging**
