### PR TITLE
react-transition-group: Fixed export syntax in index.d.ts 

### PR DESCRIPTION
**Pull request by TheFullResolution**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by Kovensky** [comment]
No, the `export =` is correct. The index file does a commonjs export, as can be seen in https://github.com/reactjs/react-transition-group/blob/v2.2.0/src/index.js.

**Comment by LKay** [comment]
👎 
As mentioned above. index exports cjs object.

**Comment by TheFullResolution** [comment]
When importing like this:
`import {
  CSSTransition,
  TransitionGroup,
} from 'react-transition-group'`

In current situation TSLint is giving following error: 'react-transition-group resolves to a non-module entity and cannot be imported using this construct.' when the equal sign is removed error disappears.

**Comment by LKay** [comment]
It's exported as common js and should be also imported as such. You have to do:
```typescript
import RTG = require("react-transition-group")
```
Then you can access components as `<RTG.Transition />`. 

There is also some inconsistency with exports in transpired code, so now importing `CSSTransition` and `TransitionGroup` as ES6 modules doesn't work correctly. I created an issue in the original project and will wait for author response. Based on that I will update the typings accordingly.

**Review by Jessidhia — CHANGES_REQUESTED** [review]
This change is incorrect, as the comments above explain

**Pull request closed without merging**
