### PR TITLE
[jquery] Update return type for height function

### PR DESCRIPTION
**Pull request by martin-badin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

according to the documentation, the function always returns only the number 
https://api.jquery.com/height/

### CODE REVIEW

**Review by leonard-thieu — CHANGES_REQUESTED** [review]
`.height()` can return `undefined` when called on an empty set.

https://jsfiddle.net/leonard_thieu/avspk27w/3/

**Comment by martin-badin** [comment]
> `.height()` can return `undefined` when called on an empty set.
> 
> https://jsfiddle.net/leonard_thieu/avspk27w/3/

You are right but I think that the problem is in the missing element, not in the function.

**Comment by leonard-thieu** [comment]
I'm not sure I understand what you mean. With this change, users won't expect `.height()` to potentially return `undefined`. Are you suggesting that users should be using it in a different way?

**Comment by martin-badin** [comment]
The function returns `undefined` if the element doesn't exist, all right? Then the user should inspect if the element exists. 

Example
```
var empty = $('#none');

if(empty.length) {
    console.dir(empty.width());
    console.dir(empty.height());
    console.dir(empty.innerWidth());
    console.dir(empty.innerHeight());
}
```

**Pull request closed without merging**
