### PR TITLE
Papaparse: Fix NODE_STREAM_INPUT for TypeScript/next test

### PR DESCRIPTION
**Pull request by rainshen49**
Basically, a config constant was not type declared in a way that makes the next TypeScript Compiler happy. This PR aims to fix that by separating the type and the value.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mholt/PapaParse/pull/494

### CODE REVIEW

**Comment by rainshen49** [comment]
@dobesv This PR should fix the build failure on your PR #36415, so I would recommend you rebase from master once this PR is merged.

**Comment by dobesv** [comment]
Even with your fix I still get the same error:

```
$ npm run lint papaparse

> definitely-typed@0.0.3 lint /home/ubuntu/DefinitelyTyped
> dtslint types "papaparse"

Error: /home/ubuntu/DefinitelyTyped/types/papaparse/papaparse-tests.ts:46:12
ERROR: 46:12  expect  TypeScript@next compile error: 
Argument of type 'File' is not assignable to parameter of type '1'.

    at /home/ubuntu/DefinitelyTyped/node_modules/dtslint/bin/index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 lint: `dtslint types "papaparse"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.3 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-06-26T18_04_09_043Z-debug.log
$ grep NODE_STREAM index.d.ts 
export function parse(stream: NODE_STREAM_INPUT_TYPE, config?: ParseConfig): NodeJS.ReadWriteStream;
declare type NODE_STREAM_INPUT_TYPE = 1;
export const NODE_STREAM_INPUT = 1;
```

I rebased https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36415 on master and Travis CI still fails with the same error even though your change is included.

**Comment by dobesv** [comment]
Do we need this `stream: NODE_STREAM_INPUT_TYPE` variant?  I can't really figure out what it's supposed to do, it isn't mentioned in the documentation.

**Comment by dobesv** [comment]
I created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36470 which seems to fix the issue for me.

**Comment by rainshen49** [comment]
Nice!

**Pull request merged**
