### PR TITLE
[cloudevents-sdk] Remove package

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

This will also fix CI 
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/660412029#L219

### CODE REVIEW

**Comment by sandersn** [comment]
I updated the CI check that was throwing since cloudevents-sdk uses a valid subdirectory name that happens to conflict with DT's subdirectory scheme. CI now passes and publishing is working again, so I don't think this PR is needed.

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes so the bot understands the status.

**Comment by MichaelDeBoey** [comment]
@sandersn Request is still needed, since the typings are now included in the package

**Comment by sandersn** [comment]
Is that true for 0.3 as well? The version on DT is just 0.3, not 1.0.

**Comment by MichaelDeBoey** [comment]
It's not needed, right? 🤔
People will still be able to download the `0.3` types if I'm correct?

**Comment by sandersn** [comment]
Yes, but not update them. Let's hold off on this for a week or two since new `@types` packages often go through a couple of revisions to get things right.

**Comment by andycmaj** [comment]
@sandersn @MichaelDeBoey anything you need from me? 

the 0.3 PR was open for months and it looks like the actual sdk now [includes types with v1](https://github.com/cloudevents/sdk-javascript/blob/master/v1/index.d.ts).

**Comment by MichaelDeBoey** [comment]
@andycmaj @sandersn I think this can just be merged tbh

**Review by sandersn — APPROVED** [review]

**Pull request merged**
