### PR TITLE
Added completelyDiscard to DisallowedTagsModes

### PR DESCRIPTION
**Pull request by nicolaair**

### CODE REVIEW

**Review by dylanarmstrong — APPROVED** [review]
~Looks good to me~

**Comment by peterblazejewicz** [comment]
@nicolaair thanks for the PR! Unfortunately, that one requires additional change: the version needs to be bumped to '2.13.9999' (please double check on source repo option release version).

**Review by dylanarmstrong — CHANGES_REQUESTED** [review]
Ah, good catch, version has to be updated in package.json.

**Review by paambaati — APPROVED** [review]
LGTM. This new option was included in https://github.com/apostrophecms/sanitize-html/pull/656.

**Review by YuJianrong — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by nicolaair** [comment]
Hi guys! Sorry I'm so late, i see that current master isn't consist this patch. I'm planning to open a new PR with an increase in package.json version.

**Pull request closed without merging**
