### PR TITLE
[graphql] Update to v14.0.0 (WIP)

### PR DESCRIPTION
**Pull request by firede**
> This PR should not be merged until `graphql` releases v14.0.0.

GraphQL.js v14.0.0 has not been released, this commit is sync to https://github.com/graphql/graphql-js/commit/9b7807a8ff20c6f2565577af8d90530acc49230d

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/graphql/graphql-js/issues/1383>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by firede** [comment]
DefinitelyTyped maintainers:
This PR is WIP, it shouldn't be merged yet, thanks.

**Comment by IvanGoncharov** [comment]
@firede Looks great 👍 
Thank you for keeping it up to date with `graphql-js`.
We plan to release `14.0.0` in the next 1-2 weeks.

**Comment by firede** [comment]
@mhegazy 
This PR is WIP, it **should not** be merged until `graphql-js` releases `14.0.0`.

But I noticed that `@types/graphql` has released a new version of `0.13.2`, the version does not match the actual content.
Could you please **deprecate** the version `0.13.2` of `@types/graphql`?

Sorry for the late reply (Timezone: UTC+8).

**Comment by mhegazy** [comment]
Sorry about that. @andy-ms helped me out and reset the latest tag manually. I will also revert the PR. please reopen a new PR with the changes.

**Comment by mhegazy** [comment]
Reverted by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27027

**Comment by IvanGoncharov** [comment]
@firede We finally released `14.0.0` 🎉 
https://github.com/graphql/graphql-js/releases/tag/v14.0.0
Do you have time to update this PR?
How can I help?

**Comment by firede** [comment]
@IvanGoncharov Congratulations! 🎉 
If it goes well, I will create a new PR tonight (UTC+8).

**Pull request merged**
