### PR TITLE
Add type definition for `hapi-auth-jwt2`

### PR DESCRIPTION
**Pull request by wms**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by warrenseymour** [comment]
The travis build appears to be failing due something unrelated to these changes.

**Comment by jucrouzet** [comment]
Fails due to #13831 merged, asked a revert

**Comment by andy-ms** [comment]
Tests fixed by #13943.

**Comment by andy-ms** [comment]
Needs tests. This defines a lot of types, but how are they meant to be used?
Make sure this use case works (from the README):
```ts
import hapiAuthJwt2 = require("hapi-auth-jwt2");
server.register(hapiAuthJwt2, function (err) { ... });
```

Also, see the [note](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default) on default exports.

**Comment by bowdenk7** [comment]
This PR has unaddressed comments (needs tests) and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
