### PR TITLE
[selenium-webdriver] Allow Wait to pass polling duration

### PR DESCRIPTION
**Pull request by pujagani**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: Fixes https://github.com/SeleniumHQ/selenium/issues/10284 to match https://github.com/SeleniumHQ/selenium/blob/f63fb35d84e1283d78303c3f0fa127807955db13/javascript/node/selenium-webdriver/lib/webdriver.js#L460
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by AutomatedTester — APPROVED** [review]

**Review by 1pete — APPROVED** [review]

**Comment by pujagani** [comment]
The build fails with the error: 
```
Error in axe-webdriverjs
Error: Errors in typescript@4.6 for external dependencies:
../node/globals.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```
It goes away if https://github.com/DefinitelyTyped/DefinitelyTyped/blob/072b01461f4ec0621a21e091d6960950d3ac1ba3/types/node/globals.d.ts#L72 the todo is completed. But then a different similar error springs up. After spending some time, I do not think it is related to the code change. It might be due to conflicting versions of typescript. I would really appreciate help on this front, I am unable to figure out a good fix if it is related to the code changes made.

**Comment by SupernaviX** [comment]
@pujagani I dunno what's causing the issue, but it looks like this axe-webdriverjs package has tests which [use node typings and don't need to](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10582ffeecbe11f019b2e9ac29f4b8e6ae9374f5/types/axe-webdriverjs/axe-webdriverjs-tests.ts#L4). If you remove the references to node and fs, is that enough to fix the build?

**Comment by pujagani** [comment]
> @pujagani I dunno what's causing the issue, but it looks like this axe-webdriverjs package has tests which [use node typings and don't need to](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10582ffeecbe11f019b2e9ac29f4b8e6ae9374f5/types/axe-webdriverjs/axe-webdriverjs-tests.ts#L4). If you remove the references to node and fs, is that enough to fix the build?

Thank you for chiming in to help. Appreciate it. However, the node typings are used to get fs, and fs is used in the test. So removing that leads to a compile error.

**Comment by SupernaviX** [comment]
> > @pujagani I dunno what's causing the issue, but it looks like this axe-webdriverjs package has tests which [use node typings and don't need to](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10582ffeecbe11f019b2e9ac29f4b8e6ae9374f5/types/axe-webdriverjs/axe-webdriverjs-tests.ts#L4). If you remove the references to node and fs, is that enough to fix the build?
> 
> Thank you for chiming in to help. Appreciate it. However, the node typings are used to get fs, and fs is used in the test. So removing that leads to a compile error.

I think the usage of fs can be removed as well. The only line that uses fs is
```typescript
const axeSource = fs.readFileSync('./axe-1.0.js', 'utf8');
```

that function returns a string, so this test wouldn't depend on node if that line was just
```typescript
const axeSource = 'some string literal';
```

**Comment by pujagani** [comment]
> > > @pujagani I dunno what's causing the issue, but it looks like this axe-webdriverjs package has tests which [use node typings and don't need to](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10582ffeecbe11f019b2e9ac29f4b8e6ae9374f5/types/axe-webdriverjs/axe-webdriverjs-tests.ts#L4). If you remove the references to node and fs, is that enough to fix the build?
> > 
> > 
> > Thank you for chiming in to help. Appreciate it. However, the node typings are used to get fs, and fs is used in the test. So removing that leads to a compile error.
> 
> I think the usage of fs can be removed as well. The only line that uses fs is
> 
> ```ts
> const axeSource = fs.readFileSync('./axe-1.0.js', 'utf8');
> ```
> 
> that function returns a string, so this test wouldn't depend on node if that line was just
> 
> ```ts
> const axeSource = 'some string literal';
> ```

Thank you so much for your help. It helped fix the build. Appreciate it!

**Review by AutomatedTester — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by pujagani** [comment]
Ready to merge

**Pull request merged**
