### PR TITLE
add types for checkSession method for auth0-lock

### PR DESCRIPTION
**Pull request by scamden**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/lock#checksessionoptions-callback

### CODE REVIEW

**Comment by scamden** [comment]
aaaaand just realized this is a v11 feature. would have been nice to keep those readme changes in a branch until release haha

**Comment by carusology** [comment]
Hey @scamden, thanks for updating the typescript definition. I think it's fine to beat the function definition to the release (preferable, actually, if it's a new function instead of a refactoring of a pre-existing one).

Can you add in a test to [`auth0-lock-tests.ts`](https://github.com/scamden/DefinitelyTyped/blob/master/types/auth0-lock/auth0-lock-tests.ts)? When I originally created the test file, I used examples ripped right from the documentation. The documentation you linked has a fitting one:

```ts
lock.checkSession({}, function (error, authResult) {
  if (error || !authResult) {
    lock.show();
  } else {
    // user has an active session, so we can use the accessToken directly.
    lock.getUserInfo(authResult.accessToken, function (error, profile) {
      console.log(error, profile);
    });
  }
});
```

**Comment by scamden** [comment]
@carusology sounds good! i'm new to definitely typed, is the point of the test not to match any assertion but just to ensure that the code compiles?

**Comment by scamden** [comment]
went ahead and added the code under that assumption

**Comment by carusology** [comment]
@scamden 

You got it. The "tests" are running the compiler and static analysis to make sure your type definitions match expectations. Thanks for doing that.

I believe your build failed because ~the bike shed is the wrong color~ there is a space between the word `function` and the open parenthesis.

Another note: While I copied the example out of the documentation as an example, please explicitly specify the types of the parameters and return types of the "test" you are building to make you are properly verifying assumptions. If you're unsure of the type or it is ambiguous in the Auth0 documentation, using the `any` type is fine. You can see other examples of how I transposed other examples from Auth0 documentation into these "tests" throughout the file.

**Comment by scamden** [comment]
gotcha, alright fixed whitespace and added types to the callback, let me know if you see anything i missed. 

i also noticed a little further down the file the .on('authenticated') calls were using `any` for the authresult instead of the `AuthResult` type but wasn't sure if maybe that was intended and you were testing some other aspect so i left it alone, but thought i'd mention it.

**Comment by carusology** [comment]
@scamden 

Someone else added it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16426/commits/8c2f85ceb910686a231283cf92eeea4c545efd86) and didn't update the test apparently. By all means, make it better if you're up for another commit.

Change looks good.

**Comment by scamden** [comment]
awesome :) done :)

**Comment by carusology** [comment]
🚢 it.

**Pull request merged**
