### PR TITLE
added definitions for named expored lodash functions 

### PR DESCRIPTION
**Pull request by stepancar**
solves this [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8816)
and [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7896)

### CODE REVIEW

**Comment by stepancar** [comment]
@vvakame could you check this PR, please?

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors (@bczengel @chrootsu). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
LGTM. but I'm waiting response from authors.
If we can't get response in 3days. please ping me again. I'll merge this PR.

**Comment by stepancar** [comment]
@vvakame , 3days :)

**Comment by vvakame** [comment]
sorry for late. it merged!

**Pull request merged**
