### PR TITLE
Add support for Highcharts modules: offline exporting and boost

### PR DESCRIPTION
**Pull request by inad9300**
Add a new type definitions for Highcharts' boost and offline-exporting modules.

(Following issue [10540](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10540).)

### CODE REVIEW

**Comment by inad9300** [comment]
Any plans on reviewing this pull request? It should be pretty straightforward.

**Comment by andy-ms** [comment]
Can you provide a documentation link for the "HighchartsOfflineExporting" and "HighchartsBoost" global variables?

**Comment by inad9300** [comment]
There are no such global variables. The closest to a piece of documentation for those is this: [highcharts offline exporting](http://www.highcharts.com/docs/export-module/client-side-export), [highcharts boost](http://www.highcharts.com/news/175-highcharts-performance-boost).

There is only one global object, `Highcharts`, and then there are many functions (modules) that extend it. The functionality added by those modules is typically included in the `Highcharts`/`HighchartsStatic` interface in [highcharts.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts#L6048). However, there is no way from TypeScript to import the modules and make them do their job without getting a `Cannot find module` error. Thus the reason these files are created.

If you have a look at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/highcharts you will see that this is the solution being adopted. My contribution is a mere analogy of the existing work.

**Comment by inad9300** [comment]
I'm sorry to insist, but is there any plan to merge this request?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11030#issuecomment-244755333
please provide test files.

**Comment by mhegazy** [comment]
@inad9300 can you please provide tests for this documentation?

**Comment by inad9300** [comment]
Do you have any idea of how to approach the tests? Here is an example of how the code is later used:

```
import * as HighchartsBoost from 'highcharts/modules/boost.js';

HighchartsBoost(Highcharts);
```

**Pull request merged**
