### PR TITLE
atom/ide-ui types

### PR DESCRIPTION
**Pull request by aminya**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by lierdakil** [comment]
Note that under the terms of license on this code you have to include the license file with the source code, which I don't think you did:

```
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
...
```

**Comment by aminya** [comment]
The license is included in the headers instead.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45366/files#diff-593e130af16b37a707259c794f87f0deR7

**Comment by aminya** [comment]
@lierdakil if you approve this, it will be merged. I addressed your comment about the license here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45366#issuecomment-640913294

**Comment by lierdakil** [comment]
Sadly, not that simple. AFAIK, we need an approval from a DefinitelyTyped maintainer since the config file is changed. Note that generally PRs authored by package owners should be merged automatically.

**Review by lierdakil — APPROVED** [review]

**Comment by aminya** [comment]
Which one is the config file? Is it `types/atom/OTHER_FILES.txt`?

**Comment by lierdakil** [comment]
Broadly speaking, any DT-specific package metadata is in some "config file". In this case, yes, it's `OTHER_FILES.txt`. In any case, one of the DT maintainers should get around to reviewing this eventually.

**Comment by RyanCavanaugh** [comment]
We can't take PRs that add new content to the repo under some arbitrary license. These files get republished to npm and our legal team has only cleared this republishing for the top-level repo license and a handful of others.

**Comment by aminya** [comment]
I don't think we even need to put the license for the original package here. The types are written separately from the original package mostly by @lierdakil and edited by me. So we are just writing the interfaces that describe the original project, and I think including the license for the original work is pointless here.

**Comment by elibarzilay** [comment]
It's a modified bsd license, and it puts restrictions on redistribution.

**Comment by aminya** [comment]
It does not put a restriction on redistribution, it just says include the license and you will be fine:
```
 Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
```

**Comment by RyanCavanaugh** [comment]
>  But considering that the license is basically BSD, and republishing is allowed under BSD, what is preventing you to merge this?

@aminya I cannot go into court and say this is "basically the same" and the differences are *probably* immaterial and the plaintiff therefore has no standing. We can only accept contributions that are licensed according to something our legal team has already signed off on, and I'm not going to bring the lawyers in for a one-off nonstandard license

**Comment by aminya** [comment]
You will not go to court. We have included the license in the files.
https://github.com/facebookarchive/atom-ide-ui/blob/master/LICENSE

```

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
```

**Comment by elibarzilay** [comment]
> It does not put a restriction on redistribution

"*Must retain*" is a restriction.  IANAL, but stuff like that gets them worried.  (What if there is some distribution channel that srtips off comments and that text goes away?)

**Comment by RyanCavanaugh** [comment]
Personal assurances of license substitutability are not sufficient here. I'm not going to keep going back and forth on this.

**Comment by aminya** [comment]
This is a basic issue that DefinitelyTyped should fix. I will publish this under some other organization that has more flexibility.

**Pull request closed without merging**
