### PR TITLE
[newrelic] Remove dropped functions from 7.0 release.

### PR DESCRIPTION
**Pull request by mastermatt**
https://github.com/newrelic/node-newrelic/releases/tag/v7.0.0

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mastermatt thx!

**Comment by mastermatt** [comment]
Looking at https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request, it doesn't specify how long I have to wait before this PR will get moved to the "DT Maintainers Queue". Anyone know? @peterblazejewicz ?

**Comment by mastermatt** [comment]
> AssertionError [ERR_ASSERTION]: Unexpected file deleted: .github/workflows/CodeOwnersSelfMerge.yml

@typescript-bot that is simply not true. please retry.

**Comment by mastermatt** [comment]
@typescript-bot help

**Comment by mastermatt** [comment]
hmmmm, I'm not sure what cmds I can give this bot. I might need @RyanCavanaugh help on this one.

**Comment by peterblazejewicz** [comment]
@mastermatt 
mabye the diff consuses CI tasks. Can you rebase our branch with master and force push changes?
I usually do:
```bash
git checkout master
git pull upstream master
git co my-branch
git rebase master
npm run test-all
git push -f
```

**Review by BrooksPatton — APPROVED** [review]
Don't know if the bot will accept my review, but it looks good to me.

**Comment by mastermatt** [comment]
Ready to merge

**Pull request merged**
