### PR TITLE
[@types/serverless] MSK support for lambda events for package serverless v2.3.0, update types to v1.79.0

### PR DESCRIPTION
**Pull request by gurbaj5124871**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/serverless/serverless/issues/8288>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by gurbaj5124871** [comment]
@hassankhan @JonathanWilbur @a-pavlenko @fredericbarthelet @bryan-hunter @ThomasAribart — please review this pr.

**Review by amcasey — APPROVED** [review]

**Comment by gurbaj5124871** [comment]
Ready to merge

**Comment by gurbaj5124871** [comment]
Ready to merge

**Comment by gurbaj5124871** [comment]
> @gurbaj5124871 Everything looks good here. Great job! I am ready to merge this PR (at [88ca40b](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/88ca40bfaa7c7a31ef32c589ec4b96064e6e1dbb)) on your behalf.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️
> 
> (@hassankhan, @JonathanWilbur, @a-pavlenko, @fredericbarthelet, @bryan-hunter, @ThomasAribart: you can do this too.)

Ready to merge

**Comment by gurbaj5124871** [comment]
> Ready to merge

**Comment by gurbaj5124871** [comment]
Ready to merge

**Pull request merged**
