### PR TITLE
Add index signature to bunyan Logger class

### PR DESCRIPTION
**Pull request by jez9999**
Addresses issue #21079.

### CODE REVIEW

**Comment by amikhalev** [comment]
I'm going to have to :-1: this, based on your issue. There's a better way to do this:

Right now, there are methods on the `Logger` class for each log level, with a bunch of overloads for each one also. Each overload should be extracted into call signatures in a `LogFunction` interface, and then each of the 6 log levels can be implemented on `Logger`, like `info: LogFunction;`

Then, all you should have to do to make the code in your issue work is cask the log level to `LogLevelString`, and indexing that on logger should result in type `LogFunction`.

**Comment by jez9999** [comment]
@amikhalev Your typings should simply reflect how the underlying library can be used, should they not?  If this isn't there, the typings are restricting usage of the library and breaking existing code.

**Comment by amikhalev** [comment]
To some extent, yes, this does "break" existing usage. But the reason that the code in your issue works in javascript is that there is an assumption that `errorLevel` is the name of a valid log function. The typings for the argument in your method does not reflect that, as all that is assumed is that the argument is some string. Now, if you want the code to work and be type safe, these are your options (in order of my preference)
 - If the value of `errorLevel` can be statically verified to be a `LogLevelString` (ie. it is called from Typescript which passes a string like 'info'), you could write the argument as `errorLevel: bunyan.LogLevelString`. If the users of your function are also getting the value from an argument, they would then have to chose one of these options.
 - If the value of `errorLevel` can *not* be statically verified to be a `LogLevelString` (ie. it is loaded from a json file), you could write a function with the signature `isLogLevelString(level: any): level is bunyan.LogLevelString` and use it in your function to verify that `errorCode` is actually a valid log level.
 - If it cannot be statically verified, but it is reasonably safe to assume that it is a `LogLevelString`, and you are willing to assume the risk of having to debug a `TypeError: ... is not a function` error in the future, you could cast the value using `errorLevel as bunyan.LogLevelString`
 - You could just say "screw types" and write the argument as `errorLevel: any`. This would accomplish about the same thing as what you have in your pull request here, and it would work, but it isn't the best usage of Typescript in my opinion

**Comment by jez9999** [comment]
@amikhalev How does `errorLevel: any` fix things?  I still get the TypeScript error "Element implicitly has an 'any' type because type 'Settings' has no index signature.".

**Comment by amikhalev** [comment]
OK, my bad. Then your options are to ignore type and cast `bunyan` to `any`, or to choose one of the other options

**Comment by RyanCavanaugh** [comment]
@jez9999 Please fix the failures indicated in the Travis CI log.

**Comment by jez9999** [comment]
@RyanCavanaugh Looks like this won't get checked in anyway.

**Comment by amikhalev** [comment]
@jez9999 I just checked some of my other solutions above, and it looks like they don't work because of Microsoft/TypeScript#13042 . So I apologize for the misinformation, but I still think the best way to work around this is to cast the logger to `any`

**Pull request closed without merging**
