### PR TITLE
[stripe] Updated create and update invoice

### PR DESCRIPTION
**Pull request by MatthiasKunnen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stripe.com/docs/api/invoices/create?lang=node
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by galtalmor — APPROVED** [review]
This is good, just 1 note that existed previously and can be fixed either here or in a separate PR:
`application_fee` should be `application_fee_amount` (+typo in the desc)

**Comment by MatthiasKunnen** [comment]
> This is good, just 1 note that existed previously and can be fixed either here or in a separate PR:
> `application_fee` should be `application_fee_amount` (+typo in the desc)

This was changed recently https://stripe.com/docs/upgrades#2019-03-14, the types are not for that version yet though.

**Comment by galtalmor** [comment]
👍

**Comment by galtalmor** [comment]
👍

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
