### PR TITLE
d3 extent should take array T, not array U

### PR DESCRIPTION
**Pull request by leon**
The extent function is wrong, it should iterate over the T argument and produce U

### CODE REVIEW

**Comment by gustavderdrache** [comment]
:+1:

**Comment by leon** [comment]
When will this be available in master?

**Comment by mhegazy** [comment]
@leon, can you create a new PR against master?

**Comment by leon** [comment]
@mhegazy https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9852

**Pull request merged**
