### PR TITLE
fix(defaults): Limit function definition to module scope

### PR DESCRIPTION
**Pull request by carmanchris31**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

This fixes an issue where the `defaults` function is declared globally even though it's only available when imported as a module.

Before:
Types and no errors when not imported
defaults-scope-before

After:
Error when module not imported (as expected)
defaults-scope-after-1

Types available when module is imported (as expected)
defaults-scope-after-2

Note: If this is a common issue, perhaps we could consider adding a note about it to the "Common mistakes" documentation.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
@carmanchris31 
I believe it should read:
```ts
// Type definitions for defaults 1.0.3
// Project: https://github.com/tmpvar/defaults/
// Definitions by: Ibtihel CHNAB <https://github.com/IbtihelCHNAB>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare function defaults(options: any, defaultOptions: any): any;

export = defaults;
```
That would correct the CommonJS module imports, remove not needed module definition (file itself is an module), see similar:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12395#issuecomment-257572414
https://github.com/DefinitelyTyped/DefinitelyTyped#should-i-add-an-empty-namespace-to-a-package-that-doesnt-export-a-module-to-use-es6-style-imports
https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

**Comment by carmanchris31** [comment]
Hey @peterblazejewicz that looks promising. I’ll give it a look and update.

What are your thoughts on having an extra test for the scope? Is there any precedent for this on other packages?

**Comment by peterblazejewicz** [comment]
@carmanchris31 
This one is a CommonJS module with single export:
https://github.com/tmpvar/defaults/blob/master/index.js#L3
This extra tests IMO can be usefull when the module under test supports multiple module loaders, like UMD, e.g. see example in DT project here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ejs/test
So that one should just use CommonJS TS syntax I think, thanks!

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
