### PR TITLE
:heavy_minus_sign: remove 'copy-webpack-plugin'

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Ships its own types as of 10.1:
https://github.com/webpack-contrib/copy-webpack-plugin/compare/v10.0.0...v10.1.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
types are published:
https://unpkg.com/browse/copy-webpack-plugin@10.1.0/types/

**Comment by peterblazejewicz** [comment]
package.json is missing entry for tsc, to be updated upstream

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
