### PR TITLE
Add 'setSelections' to CodeMirror

### PR DESCRIPTION
**Pull request by peterbartha**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://codemirror.net/doc/manual.html#setSelections](https://codemirror.net/doc/manual.html#setSelections)
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by mihailik** [comment]
Very neat, thanks also for picking on the stray spaces @peterbartha 

Since you're editing that area, can you please also add the options parameter for both `setSelection` and `setSelections`?

And can you please copy the comments from the User Manual as whole, rather than rewording in simpler form? It may be quite helpful for people who use it later on.

Thanks again, great job!!

**Comment by peterbartha** [comment]
I've added the `options` optional parameter for both `setSelection and `setSelections` and also updated the corresponding head comments.

**Comment by mihailik** [comment]
Fantastic, thanks a lot for going extra mile @peterbartha 

Sorry, one little thing: the options' properties aren't optional — which means if you do provide options you'll have to provide all 3. Do you mind making them optional please?

**Comment by peterbartha** [comment]
I made them optional. 😄

**Comment by mihailik** [comment]
Brilliant, ready to go! :+1: 

LGTM

**Comment by peterbartha** [comment]
Thank you! 👍

**Pull request merged**
