### PR TITLE
[steam-tradeoffer-manager] method fixes + comments

### PR DESCRIPTION
**Pull request by kjsmita6**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by kldzj — APPROVED** [review]
Looks good, thanks a lot for the improvements!

**Comment by kldzj** [comment]
Hey @kjsmita6, would you like to [add yourself as an owner](https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners)?

**Comment by kjsmita6** [comment]
Sure I can, adding myself and merging!

**Comment by kjsmita6** [comment]
Ready to merge

**Review by kldzj — APPROVED** [review]
LGTM, thanks again for your contribution! 🚀

**Comment by kldzj** [comment]
Ready to merge

**Pull request merged**
