### PR TITLE
[graphql-relay] Change toGlobalId ID parameter to be either string or number

### PR DESCRIPTION
**Pull request by intellix**
Related issue: https://github.com/graphql/graphql-relay-js/issues/218
Related pull: https://github.com/graphql/graphql-relay-js/pull/219

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
I'd like to wait until https://github.com/graphql/graphql-relay-js/pull/219 is merged to merge this.

**Comment by uniqueiniquity** [comment]
Feel free to tag me when the `graphql` PR is merged.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Awaiting merge of graphql/graphql-relay-js#219

**Comment by johannesschobel** [comment]
@sheetalkamat i think this was an accident to "request changes" and then the @typescript-bot closed the PR because of inactivity! This should not have happened! Can we please reopen this PR as this is definitely a proper contribution (once the PR mentioned above is merged!)

**Pull request closed without merging**
