### PR TITLE
fix(carbon-components-react): [7.10.x] Denormalized rows only have base interface properties.

### PR DESCRIPTION
**Pull request by kalbert312**
Not sure what's going on the with formatting.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/blob/v10.10.3/packages/react/src/components/DataTable/tools/normalize.js#L33-L39
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by kalbert312** [comment]
This is ready to merge.

**Comment by kalbert312** [comment]
Not sure why this is abandoned. It's ready.

**Comment by kalbert312** [comment]
Not abandoned.

**Review by ghost — APPROVED** [review]
Definitely would love to see these changes! They caught me out this morning.

**Comment by kalbert312** [comment]
Ready to merge

**Pull request merged**
