### PR TITLE
ramda: improve applySpec typing

### PR DESCRIPTION
**Pull request by jituanlin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://gist.github.com/jituanlin/4208b602ecab239b753474ebf7a61aad>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by googol** [comment]
This looks interesting, I'll have to take a look at this tomorrow and test it out for myself

**Comment by jituanlin** [comment]
Still need some work to do about this type definition, I will finish it lately.

**Comment by jituanlin** [comment]
The problem of this type definition is:
>  When use `applySpec` with currying function, it will throw the type error.

However, it 's very hard to fix it.
I am trying to understand the ` GapsOf` type in  `tool.d.ts` which provider 
the way to work with currying function.

**Comment by pirix-gh** [comment]
@jituanlin I wrote the types in tools.d.ts, you can contact me on gitter

**Pull request merged**
