### PR TITLE
[ssh2 ] `EventEmitter` - replace require with import

### PR DESCRIPTION
**Pull request by zronn**
This PR fixes an error related to `@types/node` which got a breaking change on `EventEmitter` type definition :

> error TS2507: Type 'typeof EventEmitter' is not a constructor function type.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42164
https://github.com/slackapi/node-slack-sdk/issues/951#issuecomment-603602844

### CODE REVIEW

**Comment by dhensby** [comment]
Interesting, the actual code is [importing it this way](https://github.com/mscdex/ssh2/blob/v1.11.0/lib/client.js#L14), which is why I changed the import in another PR. But it looks like from the discussion you've linked to that this is some kind of unintended regression.

Is this just a problem on a few versions to `@types/node` or is it systemic to all versions >= 13?

**Comment by zronn** [comment]
@dhensby not sure about that, I couldn't find any other discussions about this situation. On my side, I'm on version 13.

**Comment by skang1004** [comment]
I am still seeing `Type 'typeof EventEmitter' is not a constructor function type.` build errors on my project.
@dhensby @zronn @rbuckton

**Review by dhensby — APPROVED** [review]
The syntax is not wrong, no - but I'll accept this as I don't think it makes any material difference. The reason it's not working at the moment is because of a bug in TS definitions around node types, so we should just work around that.

**Comment by zronn** [comment]
Ready to merge

**Pull request merged**
