### PR TITLE
Add @onflow/flow-js-testing types

### PR DESCRIPTION
**Pull request by adbario**
Adds types for [@onflow/flow-js-testing ](https://github.com/onflow/flow-js-testing)

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## onflow__flow-js-testing ([<kbd>unpkg</kbd>](https://unpkg.com/browse/onflow__flow-js-testing@latest/))
was missing the following properties:
1. builtInMethods
1. extractImports
1. getConfigValue
1. getServiceAddress
1. promise

<details>
<summary>as well as these 4 other properties...</summary>
<p>replaceImportAddresses, resolveImports, set, shallThrow</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6149bca80b4975b3742adfedd3a1877115c39eb2
</p>

**Review by jakebailey — APPROVED** [review]
I did a quick check, and the missing properties listed above appear to be for testing and aren't part of the API.

**Comment by adbario** [comment]
> I did a quick check, and the missing properties listed above appear to be for testing and aren't part of the API.

Thanks 🚀 

Yes, that's correct. They're not part of the API.

Just fixed one argument type and split the code into separate files with the same filenames as in the repo. This is ready for merge now.

**Review by jakebailey — APPROVED** [review]

**Comment by adbario** [comment]
Ready to merge

**Pull request merged**
