### PR TITLE
[d3-brush] Complete v1.1 types

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/d3/d3-brush/releases/tag/v1.1.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38939

### CODE REVIEW

**Comment by Ledragon** [comment]
Thanks for the effort, but as v1.1.0 is not complete, I don't think this should go through as is

**Comment by Methuselah96** [comment]
@Ledragon What do you by "v1.1.0 is not complete"?

**Comment by Ledragon** [comment]
Oh sorry I misread your comment, this PR fixes existing types, which are currently incomplete, right?

**Comment by Methuselah96** [comment]
@Ledragon Correct.

**Comment by Methuselah96** [comment]
@Ledragon I agree that my original comment was confusing when I went back to read it. I've reworded it so that it's hopefully more clear now.

**Review by amcasey — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Pull request merged**
