### PR TITLE
controller field in IComponentOptions

### PR DESCRIPTION
**Pull request by uurien**
Controller field in a component can accept string, function or an array with parameters and function ["service1","service2", ControllerFunction]

I think that controller field in IComponentOptions file has to be of any type, like a controller field in IDirective.

### CODE REVIEW

**Comment by vvakame** [comment]
related #8006

**Comment by uurien** [comment]
Yes, pull requests are related, but any commit of that pull request modify the type of controller to "any" or something like "string | Function | Array".

**Comment by hheexx** [comment]
controller can be Array?

**Comment by uurien** [comment]
Is posible when controller when controller assignation is something like this:
```
angular.module(.....).component("componentName", {
  controller: ["$rootScope",function($rootScope) {
}],
  template: ....
}
```

**Comment by hheexx** [comment]
Ahh.. I hate that notation.

Commited. Thanks!

**Pull request merged**
