### PR TITLE
Added context as Record<string, unknown> to BlockEditProps' interface in @wordpress/blocks

### PR DESCRIPTION
**Pull request by Toberumono**
WordPress added the ability to provide context from the parent to child blocks via a context object passed to the edit method for block types.

I chose Record<string, unknown> for the type of the context object in order to be in line with TypeScript's guidelines on where/how to use unknown; however, it is a divergence from how typing is handled in this package.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [WordPress' Block Context documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-context/)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__blocks ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__blocks@latest/))
was missing the following properties:
1. store
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 585307870fe82d3f32e7b8bb37d63ebe127acac8
</p>

**Comment by Toberumono** [comment]
@weswigham
Sorry if you're the wrong person to ping, but I saw that you merged my last PR, so you're my best guess.
I'm trying to use TypeScript for developing some internal blocks, and I need to work with the context parameter. I also want to submit a few other PRs for missing methods on some of the Stores.

**Review by dmsnell — COMMENTED** [review]
@Toberumono can you double-check that `context` is always there? I want to make sure we don't find cases where it's `undefined` because it isn't passed down and then someone tries to access a property of `undefined` and crashes even though the types checked.

If it's always there, this looks great. If it's possible that it isn't handed down then we should add `?` to make it optional

**Comment by Toberumono** [comment]
@dmsnell
Based on [https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-edit/edit.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-edit/edit.js), context will always be present.

Also, I appear to be having issues with type-checking surrounding useSelect with "built-in" stores. Should I create an issue in the Gutenberg project, or should I try to make a PR for that here, do you think?

**Review by dmsnell — APPROVED** [review]
Thanks for double-checking!

**Comment by dmsnell** [comment]
> Also, I appear to be having issues with type-checking surrounding useSelect with "built-in" stores. Should I create an issue in the Gutenberg project, or should I try to make a PR for that here, do you think?

Creating a PR somewhere is likely to get it fixed earlier. It depends on what the issue is. I've spent a considerable amount of time trying to fully type the data system and it's a kind of Pandora's box. What's the issue?

**Comment by Toberumono** [comment]
There are a few issues, but they all center around useSelect/select/etc loosing track of the types of things.
For example:
```typescript
import {useSelect, select as globalSelect} from "@wordpress/data";

const brokenHasInnerBlocks = useSelect(select => !!select('core/block-editor').getBlock(clientId)?.innerBlocks?.length, [clientId]);
const workingHasInnerBlocks = useSelect(select => !!(select as typeof globalSelect)('core/block-editor').getBlock(clientId)?.innerBlocks?.length, [clientId]);
```
From what I could tell of the underlying code, both lines should be valid.
More recently, I was trying to get taxonomy data for the site, and encountered this:
```typescript
import {useSelect} from "@wordpress/data";

const taxonomies = useSelect(store, []).getEntitiesConfig('taxonomy');
```
getEntitiesConfig is a recognized property, but is typed as "unknown" despite the generics being completely correct (as far as I can tell).
Issues like that.

**Comment by dmsnell** [comment]
> getEntitiesConfig is a recognized property, but is typed as "unknown" despite the generics being completely correct (as far as I can tell).

This is what we ran into when trying to natively type them all. It took me to a dead-end, and I think in some cases we hit limits of what TypeScript can express, needing higher-kinded types of some form to finish the work.

Not sure what to recommend here unless you have the knowledge to help us figure it out, unfortunately.

**Comment by Toberumono** [comment]
The first example is actually pretty "simple" (it only took a couple hours of digging to figure out the source of the error... and another couple before I ran out of ideas) - the type of `select` in `useSelect(select => ...)` is determined when useSelect is declared while the type of `import {select as globalSelect} ...;` is determined after it is declared. More specifically, the `select` in useSelect is from when its type definition was loaded (and thus before the one that declares a special case for `select('core/block-editor')`) while the `select` in `import {select as globalSelect} ...;` is from after all other type definitions are loaded, which is, therefore, able to "see" the special case. The type-cast only works because the two signatures are coincidentally compatible.

The second example baffles me - while TypeScript has a resolution depth limit, I don't think that it should be getting hit (based on what I've found, the depth limit looks to be around 50). One option would be to try flattening out the types, but that would start to result in repeated code relatively quickly.

Fixing the first case likely isn't possible due to the resolution-time restrictions; however, fixing the second case should be _technically_ possible. I'll need to poke around to see if I can flatten the type definitions without breaking too much.
In the meantime, this PR should be mergable. I'll open a new one if I manage to wrangle the compiler into checking the function types.

**Comment by Toberumono** [comment]
@dmsnell are you able to merge this in?

**Review by dmsnell — APPROVED** [review]

**Comment by dmsnell** [comment]
@Toberumono no I think it needs to wait on DT. normally there's a bot that says "type 'Ready to Merge'" but maybe there's something else that triggered a DT review.

**Comment by Toberumono** [comment]
@dmsnell Oh. Yep. I see the flag now. It's the lack of unit tests.
Although, I have no clue how one would write a unit test for this change given that the code isn't executed.

**Comment by dmsnell** [comment]
check out `wordpress__blocks-tests.tsx` in the package directory. basically it's a set of minimal interactions with the packages and then an assertion that a type is how it ought to be

**Comment by Toberumono** [comment]
The problem I was encountering was checking the types passed to the edit method. Do I just assert that the edit method will take an object with the context parameter?

**Comment by dmsnell** [comment]
> Do I just assert that the edit method will take an object with the context parameter?

That's a better question for the DT maintainers, but it's worth a try! I'm no expert on this unfortunately.

**Comment by Toberumono** [comment]
I didn't actually push a new commit yet. I just merged the updated master branch in

**Comment by Toberumono** [comment]
@dmsnell Okay. Now the test has been added.

**Review by dmsnell — APPROVED** [review]

**Comment by Toberumono** [comment]
Ready to merge

**Comment by dmsnell** [comment]
Thanks again @Toberumono!

**Comment by Toberumono** [comment]
No problem!

**Pull request merged**
