### PR TITLE
Decimal js

### PR DESCRIPTION
**Pull request by musicist288**
Adding definition files for decimal.js library. @MikeMcl can you review this? The motivation behind this is to ultimately create a definition file for math.js which depends on your library.

### CODE REVIEW

**Comment by MikeMcl** [comment]
@musicist288 

I've had a quick look and it looks good, although I am not (yet) familiar enough with Typescript or its definition files to be able to review this properly. 

I can see that there was considerable work involved in creating the definiton file, and it looks like you've done a great job.

I may come back to this as time permits.

**Comment by musicist288** [comment]
@MikeMcl 
Thanks. It was considerably easier because of the great documentation and the library's consistent API.  I addressed the issues you pointed out.

@vvakame 
Is there someone who can review this for style and/or correctness with respect to Typescript?

**Comment by vvakame** [comment]
*decimal.js/decimal.js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/decimal.js
  * http://bower.io/search/?q=decimal.js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (decimal.js/decimal.js-tests.ts or others)
* [ ]

**Comment by vvakame** [comment]
@musicist288 thanks mate!
you are 1st author of this definition file. It is OK for the time being if you using.

**Pull request merged**
