### PR TITLE
Add bxslider-4 type definitions

### PR DESCRIPTION
**Pull request by psalkowski**
Add bxslider-4 type definitions with tests.

### CODE REVIEW

**Comment by horiuchi** [comment]
@namerci Thank you for your contribution!
Please rename to `dw-bxslider-4/dw-bxslider-4.d.ts`.
I saw that this library is registered as `dw-bxslider-4` on bower: http://bower.io/search/?q=dw-bxslider-4

**Comment by namerci** [comment]
I never seen before bxslider on bower.io. I was looked on bower.io for search bxslider before commit definitions, but i didnt find anything. He should add it few days ago. I'm always looking on https://github.com/stevenwanderski/bxslider-4/blob/master/bower.json for "name" key and its works.

Anyway I do rename.

**Comment by horiuchi** [comment]
@namerci Thank you for doing rename.
And Please fix the error of Travis CI: https://travis-ci.org/borisyankov/DefinitelyTyped/builds/72963208#L185

**Comment by namerci** [comment]
Sorry for mistake.

**Comment by namerci** [comment]
Sorry for mistake.

**Comment by horiuchi** [comment]
@namerci Thanks mate!

**Pull request merged**
