### PR TITLE
Fix #10919 - Added IterableIterator forward declaration to enable compilation on targets lower than es2015

### LINKED ISSUE #10919: Node Typing Typescript Compile error, TS2304: Cannot find name 'IterableIterator'.
Using the latest Node Definition file `#6.0.0+20160830141956`, the compiler throws a `Typescript Compile error, TS2304: Cannot find name 'IterableIterator'.`  It is coming from a deprecated `NodeBuffer` method (It appears in there 3 times).  Is there another typing file I'm missing, or is this an issue?

### PR DESCRIPTION
**Pull request by alejo90**
case 2. Improvement to existing type definition.
- Added forward declaration for `IterableIterator`

### CODE REVIEW

**Comment by BurtHarris** [comment]
Thanks @alejo90.   I trust this will fix the problem, but suggest your commit message needs to explain the change, rather than just say "fix #10919".

**Comment by alejo90** [comment]
Thanks for the suggestion @BurtHarris

**Comment by BurtHarris** [comment]
Hmm, with this change installed locally I'm getting a different error:

```
c:\code\DefinitelyTyped\node>tsc node-tests.ts
node-tests.ts(273,27): error TS2495: Type 'IterableIterator<[number, number]>' is not an array type or a string type.
node-tests.ts(296,25): error TS2495: Type 'IterableIterator<number>' is not an array type or a string type.
node-tests.ts(305,27): error TS2495: Type 'IterableIterator<number>' is not an array type or a string type.
```

**Comment by alejo90** [comment]
@BurtHarris agreed, but it is meant to be just a forward declaration for people not ready to target es2015.

**Comment by BurtHarris** [comment]
Thanks @alejo90.   The problem I see with adding all those unimplemented methods in the typing is that it will permit coding errors that aren't detected till runtime.   Those potential errors exist no matter if they are exposed no matter what version is being targeted unless `Buffer.values` actually returned an Array.

**Comment by alejo90** [comment]
@BurtHarris, ok, what about we remove the `extends Array<T>` from `IterableIterator` and the tests for `entries`, `values`, and `keys` from `node-tests.ts` and we add a `node-tests-es2015.ts` with an accompanying `tscparams` file that explicitly targets `es2015`. I don't think the best solution is removing the typing definitions for those three methods since they are there people who will need them and that would otherwise be forever stuck extending enriching module declarations locally.

**Comment by BurtHarris** [comment]
Hmm, that's above my pay-grade.   Seems like we should seek input from one of the committers.   @vvakame?  @RyanCavanaugh?

**Comment by vvakame** [comment]
wow, sorry for late. thanks mate!

NOTE
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L4717

**Pull request merged**
