### PR TITLE
added polymer-ts, backbone.localstorage, gulp-jshint, gulp-jade definitions

### PR DESCRIPTION
**Pull request by lgrignon**
Hello. Any update on this? I could split this PR if you prefer.

Thanks.

### CODE REVIEW

**Comment by vvakame** [comment]
*backbone.localStorage/backbone.localStorage.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/backbone.localStorage
  * http://bower.io/search/?q=backbone.localStorage
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (backbone.localStorage/backbone.localStorage-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*polymer-ts/polymer-ts.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/polymer-ts
  * http://bower.io/search/?q=polymer-ts
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (polymer-ts/polymer-ts-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@lgrignon thank you for your contributions.
please rename backbone.localStorage/backbone.localStorage.d.ts to backbone.localstorage/backbone.localstorage.d.ts.
https://www.npmjs.com/package/backbone.localstorage

**Comment by lgrignon** [comment]
Any update on this? Some definitions are ready to be uploaded :)

**Comment by AyaMorisawa** [comment]
Note that gulp-jade.d.ts will make a conflict with #7108 .

**Comment by lgrignon** [comment]
Yes. I noticed that someone wrote the same definition very recently. #7108 's definition of gulp-jade seems more accurate. Could you please integrate my PR, discarding my gulp-jade's definitions?

Thanks again :)

**Comment by lgrignon** [comment]
I added polymer-ts tests because I noticed there wasn't :) Now everything is ready I think. Please tell me if you want me to delete gulp-jade on my side.

**Comment by vvakame** [comment]
umm... please split pull request per library.

**Comment by lgrignon** [comment]
I recreated the PR, please review, merge, and I will send the other 4 :)

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7171

Thanks

*L*ouis* Grignon*

2015-12-12 16:53 GMT+01:00 Masahiro Wakame <notifications@github.com>:

**Pull request closed without merging**
