### PR TITLE
"should" issue with chai

### PR DESCRIPTION
**Pull request by NecroMeekz**
there's the "should" issue with chai

http://chaijs.com/guide/styles/

### CODE REVIEW

**Comment by vvakame** [comment]
@zeethree50 if you want to extend global Object interface, do not place Object interface in chai module.

**Comment by brettle** [comment]
I agree with @vvakame. That's what I've done with #4155.

**Comment by mhegazy** [comment]
Can you please fix the failing Travis CI tests and update the PR!

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
