### PR TITLE
update(webpack-source): v2 update

### PR DESCRIPTION
**Pull request by peterblazejewicz**
v2 update is breaking one:
https://github.com/webpack/webpack-sources/releases/tag/v2.0.0

- add `buffer` method
- add `SizeOnlySource`
- add `CompatSource`
- remove `node` and `listNode` methods from public API
- remove `LineToLineMappedSource`
- v1 created for backward compatible updates
~~- v0 dropped to be on budget~~ (restored as requested during PR review)
- structure rewritten to follow package structure

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
for CI error, see: microsoft/DefinitelyTyped-tools#118

**Comment by valorkin** [comment]
@peterblazejewicz hello, thank you so much for your effort. could you please revert changes in removing v0 in this PR so it get's merged and published?
most webpack@5 packages are waiting for it :D
thanks in advance

**Comment by peterblazejewicz** [comment]
@valorkin done!

**Comment by valorkin** [comment]
@peterblazejewicz thank you!

**Review by amcasey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge :kiss:

**Pull request merged**
