### PR TITLE
[bitcoinjs-lib] fix argument/return types of script templates

### PR DESCRIPTION
**Pull request by kento1218**
* encodeStack should return Buffer[]
* Signatures are assumed as Buffer, not ECSignature

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bitcoinjs/bitcoinjs-lib/tree/master/src/templates
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by youssefgh** [comment]
@kento1218 the changes are good, but after i checked, it seems that multisig, pubKey, pubKeyHash, scriptHash, witnessCommitment, witnessPubKeyHash, witnessScriptHash and nullData, are no longer exported from script starting from Bitcoin-JS 3.2.1 but instead exported from templates. so i think that you're still using an older version Bitcoin-JS (that's not a problem though)

If you can wrap those template elements in a "templates" namespace as part of this PR, that would be perfect. 

If you can't upgrade to the latest version or don't have the time to make the new changes, just let me know, so that i mark is PR as reviewed and i create the "templates" namespace in a future PR

And thanks a lot for your contribution

**Comment by kento1218** [comment]
I tried on 3.2.1 and 3.3.2 but the members of `templates` are still exported under `script` namespace.

```javascript
const bt = require('bitcoinjs-lib')
bt.templates // => undefined
bt.scripts.templates // => undefined
bt.script.multisig // => object
```

Since 3.2.1  re-assignment is done on [index.js on bitcoinjs-lib](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v3.2.1/src/index.js#L3)

**Review by youssefgh — APPROVED** [review]

**Comment by youssefgh** [comment]
Yes, you're right. thanks for digging more into it !
Approved :)

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
