### PR TITLE
[three]: add WebGLUtils missing export in Three.d.ts

### PR DESCRIPTION
**Pull request by DavidPeicho**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url](https://github.com/DavidPeicho/DefinitelyTyped/blob/three/fix-webgutils/types/three/src/Three.d.ts#L212)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. AxisHelper
1. BinaryTextureLoader
1. BoundingBoxHelper
1. CanvasRenderer
1. DynamicBufferAttribute

<details>
<summary>as well as these 26 other properties...</summary>
<p>EdgesHelper, FaceColors, Font, FontLoader, ImmediateRenderObject, JSONLoader, LensFlare, Math, MeshFaceMaterial, MultiMaterial, NoColors, ParametricGeometry, Particle, ParticleBasicMaterial, ParticleSystem, ParticleSystemMaterial, PointCloud, PointCloudMaterial, RGBFormat, SceneUtils, TextGeometry, Vertex, VertexColors, WebGLRenderTargetCube, WireframeHelper, XHRLoader</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4d9c1696ab8ff597dad169bb41657b2428dbd5e6
</p>

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Would you be able to open this on `three-ts-types` please?

**Comment by DavidPeicho** [comment]
@joshuaellis done: https://github.com/three-types/three-ts-types/pull/198

**Comment by DavidPeicho** [comment]
We can close that right? @joshuaellis

**Comment by joshuaellis** [comment]
sure can.

**Pull request closed without merging**
