### PR TITLE
feat (data-api-client) add transactionId for the query() function

### PR DESCRIPTION
**Pull request by idanlo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [URL](https://github.com/jeremydaly/data-api-client#running-a-query)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## css-tree ([<kbd>unpkg</kbd>](https://unpkg.com/browse/css-tree@latest/))
was missing the following properties:
1. SyntaxError
1. TokenStream
1. Lexer
1. vendorPrefix
1. isCustomProperty

<details>
<summary>as well as these 6 other properties...</summary>
<p>lexer, createLexer, tokenize, createSyntax, fork, version</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d142f0f26a5e68a1751c4e8af2c53a93a9d2f17d
</p>

**Comment by idanlo** [comment]
Can anyone approve this please?

**Comment by idanlo** [comment]
?

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by idanlo** [comment]
Ready to merge

**Pull request merged**
