### PR TITLE
lru-cache Add @isaacs as an owner

### PR DESCRIPTION
**Pull request by dhensby**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

The current owners (@BendingBender and @Bartvds) are not particularly active or responsive to PRs that get opened for these typings (no judgement on that note). @isaacs is the actual author of the npm module and has indicated they're happy to review typing contributions and help ensure they are accurate, but also that this remains a community driven initiative. As such, adding @isaacs as an owner gives them the ability to provide that oversight whilst sparing them the obligation of keeping the types up to date.

### CODE REVIEW

**Review by gabritto — APPROVED** [review]

**Comment by dhensby** [comment]
Before I merge this in, @isaacs can you confirm you're happy with this? Thanks

**Comment by dhensby** [comment]
Just waiting on confirmation that @isaacs is ok with this :)

**Comment by isaacs** [comment]
Fine by me.

**Comment by dhensby** [comment]
Ready to merge

**Pull request merged**
