### PR TITLE
Jquery Tooltipster - Updated to version 3.3.0

### PR DESCRIPTION
**Pull request by NejcZdovc**
Updated to the latest version 3.3.0 (http://iamceege.github.io/tooltipster/). Also added all methods specificity (previously it was defined only by string).

Passed Travis CI test.

### CODE REVIEW

**Comment by NejcZdovc** [comment]
Any progress on this? Can you please merge to master or let me know what to fix.

**Comment by vvakame** [comment]
@NejcZdovc sorry for late. please resolve conflict fisrt.
We can't get response from author, I'll merge this PR. please ping me after your work.

**Comment by vvakame** [comment]
ah, author response by emoji reaction.

**Comment by NejcZdovc** [comment]
Conflict resolved.  @vvakame please merge. Thank you

**Pull request merged**
