### PR TITLE
[@types/ref] forwardref should not add children to the incoming props type.

### PR DESCRIPTION
**Pull request by cqh963852**

### CODE REVIEW

**Comment by hellatan** [comment]
@TheBegining can you update your description to include the current output and and what the output would be after this change? It's hard to discern if this is right or wrong without seeing a working example.

**Review by eps1lon — CHANGES_REQUESTED** [review]
This is probably one of those changes that too many projects depend on. We want to get rid of implicit children but, I think, most of the maintainers agree that this should be done in a SemVer major when react 17 is released.

**Comment by TheBegining** [comment]
> @TheBegining can you update your description to include the current output and and what the output would be after this change? It's hard to discern if this is right or wrong without seeing a working example.

Before Update.It has the children attribute by default.But when used, it does not have the children attribute.
image
image
If I want give a children to Test Component.I have to add a PropsWithChildren.
image

After Update. It will tell me, children is not given.
image

**Comment by ferdaber** [comment]
Agreed with @eps1lon. Without a good supported codemod it'll be very difficult to sell this change since DT doesn't follow semver, it follows it versioning of the runtime library that it mirrors.

**Pull request closed without merging**
