### PR TITLE
cytoscape: fix map()

### PR DESCRIPTION
**Pull request by nakagawa424**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

#27146

### CODE REVIEW

**Comment by Cerberuser** [comment]
I'll suggest to check whether it will work for all the cases (general `Collection`, `NodeCollection`, `EdgeCollection`). If it doesn't, it seems that we must use generic parameter to `CollectionBuildingFiltering` here.

**Comment by nakagawa424** [comment]
#27238 ?

**Comment by Cerberuser** [comment]
#27244 seems to fix the Travis error, if you want, we may wait for it to be merged and then rebase your work on new `master` branch. But tests I'm suggesting could be performed without Travis, using just `tsc`. I'll try to look into it today.

**Review by Cerber-Ursi — CHANGES_REQUESTED** [review]
I think this is not yet entirely ready for merging, as stated before.

**Comment by nakagawa424** [comment]
rebased.

**Review by Cerber-Ursi — CHANGES_REQUESTED** [review]
I just added this to the tests:  
`nodes.map(n => n.connectedEdges());`  
`edges.map(e => e.source());`  
Not sure whether it should work or not, but logically it should. You can check yourself and see that with this variant it's not the case.

**Comment by nakagawa424** [comment]
tests might be:
nodes.map(n => n.degree());
edges.map(e => e.source());
eles.map(e => e.id());

**Comment by Cerberuser** [comment]
First two tests you've suggested seem to fail with your version of definitions file, just like my ones do:

```
Property 'degree' does not exist on type 'SingularElementArgument'.
  Property 'degree' does not exist on type 'EdgeSingular'.
```

```
Property 'source' does not exist on type 'SingularElementArgument'.
  Property 'source' does not exist on type 'NodeSingular'.
```

**Review by Cerber-Ursi — APPROVED** [review]
We should check other functions in this interface, but for now it seems to be good.

**Review by Cerber-Ursi — APPROVED** [review]

**Pull request merged**
