### PR TITLE
Formatted types/t* packages with dprint

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
> 👉 Partial implementation of https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993. If you're seeing this and are surprised it's happening, please read the discussion and give feedback! ❤️ 

Implements the dprint formatting changes on packages whose names start with `t`. We're splitting up the changes to make it a bit easier to apply & review them en masse - and, if we need later on, revert / bisect for issues. These changes generated with roughly:

```shell
git checkout dprint-onboarding -- .dprint.jsonc
time npx dprint fmt "types/t*/**/*.t*"
# Formatted 730 files.
# npx dprint fmt "types/t*/**/*.t*"  3.91s user 0.71s system 237% cpu 1.951 total
rm .dprint.jsonc
```

~CI failures are due to [DefinitelyTyped-tools > feat: remove formatting rules rules from dtslint](https://github.com/microsoft/DefinitelyTyped-tools/pull/699) not being ~merged~ included in CI yet.~ ✔️ 

Includes:

* ~#66349~ _(already merged into `master`)_

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by martin-badin — APPROVED** [review]

**Review by mike-lischke — APPROVED** [review]
I cannot review all 732 files, but checked some of them and think the changes are fine, given that this patch only contains formatting differences.

**Review by johnnyreilly — APPROVED** [review]

**Review by waynecraig — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
Ready to merge

**Comment by JoshuaKGoldberg** [comment]
Thanks everyone! I appreciate the reviews, and apologize for all the tagging. 🙂

**Pull request merged**
