### PR TITLE
[yup] Add originalValue to test context

### PR DESCRIPTION
**Pull request by abnersajr**
**DO NOT MERGE**
*This wasn't merged yet on YUP repository* I will keep here updated when there was merged.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup/issues/1007
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by mauricedb** [comment]
Hi @abnersajr,

If I am not mistaken is PR is a little early in adding something that is not even merged, let alone released, with Yup yet. So I think until https://github.com/jquense/yup/pull/1021 is merged and released to NPM this PR should not be merged.

Additionally, there seem to be a lot of white space changes that kind of hide the actual change to the type definition.

**Review by iansan5653 — CHANGES_REQUESTED** [review]
A couple of changes (as well as keeping this on hold until it's actually live in Yup):

* Revert the whitespace changes to make a minimal diff - the changes are subjective and usage in most cases was already consistent throughout the file
* Rename `ctx` to `context` just to make it clearer what it is
* I realize we missed this in the last PR but I believe the value parameter of `AssertingTestFunction` should be `unknown` and so should `originalValue` in `TextContext`

**Review by iansan5653 — CHANGES_REQUESTED** [review]
[deleted]

**Comment by abnersajr** [comment]
@mauricedb thank you so much for take a look on that. First time opening an PR here.
I just opened up to not lose a track on that. But make senses to have this opening after a final and merged version. Avoiding possible refactors.

BTW. There is any NO MERGE label that could be added?

**Comment by abnersajr** [comment]
@iansan5653 definitely something went wrong with my commit missing some files.
But, thanks for the feedback I'm gonna check this too.

**Comment by iansan5653** [comment]
@abnersajr You can convert the PR to a draft and it won't be merged until you say it's ready: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by alexandernst** [comment]
What happened to this?

**Comment by abnersajr** [comment]
I opened a new PR with issues fixed.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49524

**Pull request closed without merging**
