### PR TITLE
[chrome][chrome-apps]: Added missing declaration for restartAfterDelay

### PR DESCRIPTION
**Pull request by carlosarias1992**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://developer.chrome.com/docs/extensions/reference/runtime/#method-restartAfterDelay](https://developer.chrome.com/docs/extensions/reference/runtime/#method-restartAfterDelay)

### CODE REVIEW

**Review by pyle — APPROVED** [review]
LGTM

**Review by pyle — CHANGES_REQUESTED** [review]
Undo-LGTM. Please add the appropriate tests in the tests/ folder.

**Review by nicolas377 — APPROVED** [review]
Looks good on the chrome side!

**Review by peterblazejewicz — APPROVED** [review]
@carlosarias1992 thx!

**Comment by carlosarias1992** [comment]
Ready to merge

**Pull request merged**
