### PR TITLE
react-map-gl: update to 5.2

### PR DESCRIPTION
**Pull request by singingwolfboy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/uber/react-map-gl/blob/master/CHANGELOG.md
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

This makes a few changes to make the `react-map-gl` types compatible with the latest version of the library. I have not _exhaustively_ tested them -- I was mostly relying on the accuracy of the CHANGELOG file (and reviewing the associated pull requests).

### CODE REVIEW

**Comment by Arman92** [comment]
Hi @singingwolfboy, thanks for the contribution, please revert the formatting changes so reviewers could distinguish the changes easily. I read your changes, it seems fine to me.

**Comment by singingwolfboy** [comment]
@Arman92: this pull request has two commits, one that contains content changes only, and one that contains formatting changes only. If reviewers want to review them independently, they can view the individual commits in the pull request. Is that OK?

I only made the formatting changes because I was following the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request), which specifically recommends running `prettier` on the changed files.

**Review by fnberta — APPROVED** [review]
I agree that the prettier changes would have been better in a separate PR. But looking at the individual commits, I think this is fine! Thanks for the contribution!

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
