### PR TITLE
[@types/mathjs] tests only test types, not runtime behaviour

### PR DESCRIPTION
**Pull request by andnp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

These changes remove all of the redundant mathjs tests. Most of the test logic was asserting that the runtime library worked, but did little testing of the actual types. This removes all of the runtime relevant logic, in favor of simply testing the types.

No new tests are added in this PR (follow-up PRs will add tests for all of the untested code), and no valid tests are removed in this PR.

### CODE REVIEW

**Comment by mhegazy** [comment]
These tests seem to be coming from the examples of the library, e.g. http://mathjs.org/examples/basic_usage.js.html

There is value in having the full example added, it allows us to ensure we are not breaking any expected-to-work scenarios. 

what is the impetus for changing the tests?

**Comment by andnp** [comment]
This is a fair point. The major goal was to clean out the duplication so that it is easier to see what things are being tested, and what are not. At the moment, there are many many functions that are currently not being tested at all, which is allowing bugs to get through.

Specifically, the `BigNumber` interface was defined as `{}` which when used in a union for function signatures: `pow(number | BigNumber | ...)` allowed nearly anything to be passed in. This hid some minor bugs in the types previously. There are currently several other interfaces that are defined as `{}` that I would like to fix in future PRs, and I was hoping to have a clearer test file to help keep track of what things were being tested.

Optimally I would like the test file to mirror `index.d.ts` in layout, so that it is clear what methods are being tested and it is easy to skim the tests.

What do you think about continuing to have the examples verbatim from the library as `mathjs-example-tests.ts` (name tbd) and also have `math-tests.ts` which tests all of the remaining untested functions?

**Comment by RyanCavanaugh** [comment]
@andnp makes sense to me. @siavol any thoughts?

If there aren't strong feelings either way I'll merge tomorrow.

**Comment by RyanCavanaugh** [comment]
@andnp good to merge then?

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
