### PR TITLE
[node-red__util] Upgrade `jsonata` to 2.x used by Node-RED v4

### PR DESCRIPTION
**Pull request by GogoVega**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Changes:

- Bump `jsonata` from 1.8.3 to 2.0.5 used by Node-RED v4
- Update the type of the `callback` parameter which is now required for NR v4

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/node-red/node-red/commit/3aeb4bd8680f2ca1805d056523009a5bec4147fd>>  <<https://github.com/node-red/node-red/pull/4590>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by GogoVega** [comment]
Note: the `callback` parameter of `evaluateJSONataExpression` can no longer be undefined. I can add it to this PR if that's ok for you?

**Review by Shaquu — APPROVED** [review]
Looks good to me.

**Comment by Shaquu** [comment]
> Note: the `callback` parameter of `evaluateJSONataExpression` can no longer be undefined. I can add it to this PR if that's ok for you?

Seems like a scope for another PR? or is it related to node-red too?

**Comment by GogoVega** [comment]
The upgrade to JSONata 2.x has resulted in a change to the `evaluateJSONataExpression` function. See https://github.com/node-red/node-red/pull/4590.

For me it's also part of the scope of this PR.

**Review by Shaquu — APPROVED** [review]

**Comment by GogoVega** [comment]
Ready to merge

**Pull request merged**
