### PR TITLE
Set type definition to result param of Callback type

### PR DESCRIPTION
**Pull request by gabrielvincent**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

One of the overloads of the `send` function returns a `Promise<Result[]>`. The non-promise, callback-oriented version of that function should return the same type with the `result` value.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-pushnotifications/index.d.ts#L25

### CODE REVIEW

**Comment by gabrielvincent** [comment]
> Hey @gabrielvincent,
> 
> 😒 Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module.
> 
> _**This can potentially save days of time for you!**_

No new tests are required and no tests need to be changed since no contracts were modified.

**Comment by jakebailey** [comment]
> No new tests are required and no tests need to be changed since no contracts were modified.

The types were made more strict; code that previously worked may not compile anymore. How has the "contract" not been modified?

If the package owner accepts it, then that's fine, but this still constitutes a breaking change without tests.

**Comment by gabrielvincent** [comment]
> > No new tests are required and no tests need to be changed since no contracts were modified.
> 
> The types were made more strict; code that previously worked may not compile anymore. How has the "contract" not been modified?
> 
> If the package owner accepts it, then that's fine, but this still constitutes a breaking change without tests.

I see your point. I'll include the tests.

**Review by jaulz — APPROVED** [review]

**Comment by gabrielvincent** [comment]
Ready to merge

**Pull request merged**
