### PR TITLE
[chromecast-caf-receiver] Update declarations according to SDK docs (2)

### PR DESCRIPTION
**Pull request by marcoreni**
Next step in bringing this package up to date with the [Web Receiver Documentation](https://developers.google.com/cast/docs/reference/web_receiver)

NOTES:

- 95% of the changes are docs cleanup / fixes. I tried adding a link to every class / enum, and fixing JSDoc issues
- This set of PRs is file-based, so that they're easier to review. This PR handles
  - cast.framework.d.ts
  - cast.framework.system.d.ts
- I followed Google Javascript Styleguide for comments.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: _see above_

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
@marcoreni this api seems to be versioned:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d26781e5f46bcc8fd3b87dd8baa7d4f7f2b005e6/types/chromecast-caf-receiver/index.d.ts#L1
Are your changes expected to result in version update?
thx!

**Comment by marcoreni** [comment]
Hey @peterblazejewicz , the API is not versioned. When I was first involved in the updates a few weeks back the version was 5.0.xxx ; I created a PR with some breaking changes and bumped the major version to 6.0.

Chromecast CAF (aka. web) Receiver was last updated on April 29, 2021 and it's currently at 3.0.0096: https://developers.google.com/cast/docs/release-notes#april-29,-2021 , but there is no explicit versioning.
For example, on September 14, 2020, the SDK was updated without providing a specific version: https://developers.google.com/cast/docs/release-notes#september-14,-2020

The SDK is made available from google at //www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js ; there's no way to pinpoint a specific version and  I don't see an easy way to get in line with the Google version.

**Comment by peterblazejewicz** [comment]
@marcoreni thx for the info!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by marcoreni** [comment]
Ready to merge

**Pull request merged**
