### PR TITLE
[openid-client]: fix Issuer constructor; improve object typing and return types

### PR DESCRIPTION
**Pull request by YangusKhan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: The current types are not accurate to the documentation and source code of the package. Specifically, you should be able to instantiate an Issuer with a regular constructor, even if it isn't the preferred method. [https://github.com/panva/node-openid-client/blob/master/docs/README.md](https://github.com/panva/node-openid-client/blob/master/docs/README.md)

### CODE REVIEW

**Review by ulrichb — CHANGES_REQUESTED** [review]
Please don't change the `{} | null | undefined }` output contracts to `any` (reasoning: it's about type safety; the unknown JSON results should be explicitly casted to whatever is expected).

Further: All the reformatting makes it heard to review the changes. Maybe propose an own PR for the reformatting.

**Review by ulrichb — CHANGES_REQUESTED** [review]
See comment above.

**Comment by YangusKhan** [comment]
> Please don't change the `{} | null | undefined }` output contracts to `any` (reasoning: it's about type safety; the unknown JSON results should be explicitly casted to whatever is expected).

Can you give an example of how you would type cast from this interface, then? Because my change was motivated by using the `Client.userinfo` function, which returns strings instead of objects. Here is my example usage:
```
const userinfo = await client.userinfo(token);
const username = snakeCase(userinfo.name || "anonymous") + "-" + randomBytes(2).toString("hex");
```
Explicitly casting my `userinfo` result would be something like this:
```
type UserInfo = {
  [k in "sub" | "name"]: string | null | undefined;
};
const userinfo = (await client.userinfo(token)) as UserInfo;
```
and it seems a little strange to type cast from your `{}` type to a `string`.

> Further: All the reformatting makes it heard to review the changes. Maybe propose an own PR for the reformatting.

I'm only using the `prettier` config that's set up by default in this repository.

**Comment by ulrichb** [comment]
Using you sample:

```ts
interface UserInfo {
  sub?: string;
  name?: string;
};
const userinfo = (await client.userinfo(token)) as UserInfo;
console.log(userinfo.name.toUpperCase(), userinfo.invalid_prop);
```

With the explicit cast to `UserInfo` (which can be defined much easier as simple interface), TSC would correctly warn about a) the missing undefined-check for name and b) warn about using `invalid_prop`.

In contrast, when using `any`, we don't force the cast; and without the cast, TSC would not emit any errors for the erroneous code above (because of the inferred `any` type).

> I'm only using the prettier config that's set up by default in this repository.

Hmm, still it doesn't make reviewing the PR easier :)

**Review by ulrichb — APPROVED** [review]
Nice. 

Many thanks for your PR!

**Pull request merged**
