### PR TITLE
Add documentation for pikaday methods and properties

### PR DESCRIPTION
**Pull request by theodorejb**
Also fixed `yearRange` property to accept a number, and removed invalid `gogoYear` method

### CODE REVIEW

**Comment by vvakame** [comment]
@MidnightDesign could you review this PR?

**Comment by MidnightDesign** [comment]
@vvakame What's the policy on code style? I also like the space between the variable and the type more, but is it a good idea to have changes in all those lines just for the updated style?
@theodorejb Thanks for your contribution!

**Comment by MidnightDesign** [comment]
Just found the answer in the [contribution guide](http://definitelytyped.org/guides/contributing.html):

> When editing an existing file please maintain the existing style as much as possible, this includes indenting, separator whitespace, bracing etc..
> (...)
> It is discouraged to reformat existing code (as it breaks git attribution).
> When preparing a Pull Request please check git diff (locally or on github) for unnecessary changes.

So @theodorejb could you please revert those style changes? Thanks!

**Comment by theodorejb** [comment]
@MidnightDesign It wasn't my intent to change the style, but to make it consistent. Notice that the second half of the file (starting at line 133) is already using a space before the type.

**Comment by MidnightDesign** [comment]
Oh, okay. Well, then thanks for cleaning it up, I guess. :)

@vvakame :+1:

**Pull request merged**
