### PR TITLE
Make upgrade react-dropzone to es2015

### PR DESCRIPTION
**Pull request by alitaheri**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-dropzone/react-dropzone/releases/tag/v4.2.0
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by LKay** [comment]
This is duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20601 By default module exports common js and esnext files are imported depending on environment and compiler flags. You can’t declare both cjs and es6 exports at the same time.

**Comment by alitaheri** [comment]
@LKay It **is** possible to support both. but in a weird way 😅 😅 Take another look please.

**Comment by LKay** [comment]
The hack with namespace export is highly discouraged and new prs containing this are not accepted in DT for quite a while now. If modules after transpiration export cjs then in typescript definitions should reflect that. The culprit here is `babel-add-modules-export` that is still around (event if such behavior was intentionally removed from babel) to keep backwards compability with old nodejs.

**Comment by alitaheri** [comment]
@LKay But we gotta get our code to compile. It's either that or we gotta uninstall the typings for this library. I'm sure a lot of people will encounter this problem after migrating to 4.2.0 as I did.

Until this issue is resolved for good this is a working method.

**Comment by andy-ms** [comment]
@alitaheri Have you tried `--allowSyntheticDefaultImports`?

**Comment by benbayard** [comment]
Can you link to the change on React Dropzone that has the change of behavior?

**Comment by benbayard** [comment]
@alitaheri does the cjs import not work well for you as outlined in the test file?

**Comment by alitaheri** [comment]
@andy-ms It works of course. But it's **not** synthetic [this PR](https://github.com/react-dropzone/react-dropzone/pull/510) adds es2015 support. That means using webpack default import is the  **only** import that works. it took me a while to get to the bottom of why my builds broke after a random npm install (4.2.0 is compatible with 4.1.0 😥) only to find out typescript complains about the **only** way of import that works 😑 😑 

@benbayard The PR I mentioned above. It landed on `4.2.0`.

**Comment by LKay** [comment]
> (...) That means using webpack default import is the only import that works (...)

@alitaheri  The issue here is not with webpack but with how Typescript resolves the module. If you have this declared in your `package.json`:
```
"main": "dist/index.js",
"module": "dist/es/index.js",
```
Typescript tries to resolve `main` and not `module`.

**Comment by alitaheri** [comment]
@LKay Typescript doesn't even look at the main repository, since it doesn't have any sort of typings associated with it. So it only looks at the `@types/react-dropzone/index.d.ts`. It the emit that matters:

```ts
import Dropzone from 'react-dropzone'; // -> require('react-dropzone')['default'];
import * as Dropzone from 'react-dropzone'; // -> require('react-dropzone');
```

And **then** webpack trying to resolve `react-dropzone` sees the `"module": "dist/es/index.js"` and requires a module with `default export ...;` and not `module.exports = ...`.

So... It's all way too entangled. "allowSyntheticDefaultImports" does let you work around it. but it's takes away your type safety 😱

**Comment by andy-ms** [comment]
Is "module" a webpack thing? I would consider that synthetic if it involves a special module loader...
You may also be interested in Microsoft/TypeScript#16093.

**Comment by alitaheri** [comment]
@andy-ms Thanks, That would certainly fix a lot of similar issues. Since it's committed and will be implemented in 2.7 I'll close this and wait for that to be implemented.

**Pull request closed without merging**
