### PR TITLE
[jest] updated toHaveProperty method of Matchers

### PR DESCRIPTION
**Pull request by mariomc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Jest Documentation](https://facebook.github.io/jest/docs/en/expect.html#tohavepropertykeypath-value) and [Flow Annotated Source](https://github.com/facebook/jest/blob/v22.1.0/packages/expect/src/matchers.js#L489)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by wsmd — APPROVED** [review]
:+1:

**Comment by wsmd** [comment]
@mariomc do you mind adding a test case for this?

**Review by wsmd — CHANGES_REQUESTED** [review]
@mariomc do you mind adding a test case for this?

**Comment by mariomc** [comment]
Sure thing. Care to review now @wsmd ?

**Review by wsmd — APPROVED** [review]
Looks great! 👍

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
