### PR TITLE
Update React Native Definition to 0.27

### PR DESCRIPTION
**Pull request by blaesus**
This PR updates React Native definitions to 0.27, based on @bgrieder's 0.19 version.

You can review it in three parts, as it's too huge for Github:
#### RN 0.19->0.25 Components

https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...strikingly:RN-0.25-components
#### RN 0.19->0.25 API

https://github.com/strikingly/DefinitelyTyped/compare/RN-0.25-components...strikingly:RN-0.25-api
#### RN 0.25->0.27

https://github.com/strikingly/DefinitelyTyped/compare/RN-0.25...strikingly:RN-0.27

Note that some commits from upstream is fused into the partial PRs, so some changes are already in the official repo

cc @bgrieder @PublicParadise

### CODE REVIEW

**Comment by vvakame** [comment]
wow, big change!
We can't get response from author. I'll merge this PR in 2 days. please ping me again.

**Comment by bgrieder** [comment]
Sorry this is too huge to review it all.  Given the effort provided,  I
can only trust you :)

Thank you

:+1:  please merge

**Comment by andyshuxin** [comment]
@bgrieder We have been using it internally for a while. If there are issues, please feel free to reach me.

**Comment by andyshuxin** [comment]
Thanks everybody.

**Comment by joewood** [comment]
I'm seeing issues with this merge:

* I'm seeing a duplicate symbol on `SwipeableListView` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0d756ea7f1af31dc927419f5d16a8c5311815e6/react-native/react-native.d.ts#L5621
* Also, seems to be a typo on that data-type (`SwipeableListViewStatci` )
* Some issues around `NavigationContainerStatic` and `NavigationRootContainerStatic` not being defined.
* Line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0d756ea7f1af31dc927419f5d16a8c5311815e6/react-native/react-native.d.ts#L5525 uses `JSX.element` rather than `JSX.Element`.

**Comment by andyshuxin** [comment]
@joewood Oops, my bad. Filed a PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9665

**Pull request merged**
