### PR TITLE
[node] Fix net events

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Improvement to existing type definition.

Add events and tests for `net`
- It refers to [Class: net.Server](https://nodejs.org/api/net.html#net_class_net_server)
- It refers to [Class: net.Socket](https://nodejs.org/api/net.html#net_class_net_socket)

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
I will fix this.

**Comment by TonyPythoneer** [comment]
This changing focus adds type and test for net.Socket and net.Server events.
The other changing is because sublime has typescript auto format.
If this PR has passed by CI, please @andy-ms review it. thx.

**Comment by TonyPythoneer** [comment]
I saw what happened.
Wait for CI.

**Comment by TonyPythoneer** [comment]
Alright. It's okay.
Please @andy-ms review this.

**Review by ghost — APPROVED** [review]

**Pull request merged**
