### PR TITLE
Create ng-device-detector.d.ts

### PR DESCRIPTION
**Pull request by goosefraba**
Added typedef for project: https://github.com/srfrnk/ng-device-detector

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-device-detector/ng-device-detector.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-device-detector
  * http://bower.io/search/?q=angular-device-detector
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-device-detector/ng-device-detector-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@goosefraba thanks you for your contributions.
please rename ng-device-detector/ng-device-detector.d.ts
https://www.npmjs.com/package/ng-device-detector

**Comment by goosefraba** [comment]
@vvakame files renamed!

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
