### PR TITLE
Update encoding-japanese for v2

### PR DESCRIPTION
**Pull request by p-chan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/polygonplanet/encoding.js#replace-to-html-entity-numeric-character-reference-when-cannot-be-represented
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## encoding-japanese ([<kbd>unpkg</kbd>](https://unpkg.com/browse/encoding-japanese@latest/))
was missing the following properties:
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 55da6400b0837136076aac23508d8a01cc00c3ab
</p>

**Review by rhysd — CHANGES_REQUESTED** [review]
Would you also add `Encoding.version`? It was also added at 2.0.0 https://github.com/polygonplanet/encoding.js/commit/bd3d6ef511a17c2d9671453e6c93618dae7ae9db

**Comment by p-chan** [comment]
> Would you also add `Encoding.version`? It was also added at 2.0.0 [polygonplanet/encoding.js@bd3d6ef](https://github.com/polygonplanet/encoding.js/commit/bd3d6ef511a17c2d9671453e6c93618dae7ae9db)

@rhysd 
Thanks for your review.
I forgot to add the version.
I have added it and will ask you to review it again:pray:

**Review by rhysd — APPROVED** [review]
Looks good. Thanks for the update.

**Comment by rhysd** [comment]
Ready to merge

**Pull request merged**
