### PR TITLE
[react-native] feat: add getAll function type to formData

### PR DESCRIPTION
**Pull request by matinzd**
Reference: https://github.com/facebook/react-native/pull/32444

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by eps1lon** [comment]
The react-native PR was just merged 2 days ago. Are you sure it's already released? If so, could you point to the documentation for the changes instead?

**Comment by matinzd** [comment]
> The react-native PR was just merged 2 days ago. Are you sure it's already released? If so, could you point to the documentation for the changes instead?

I will let you know when the changes are in changelog.

**Review by eps1lon — CHANGES_REQUESTED** [review]
For explicit signal to DT maintainers. This change isn't released yet.

**Comment by matinzd** [comment]
Hi there is no issue. We need to wait until next RN major release.

**Comment by eps1lon** [comment]
> Hi there is no issue. We need to wait until next RN major release.

@matinzd I would suggest converting this PR to a draft to avoid automatic closing and needless pings. Once a new RN major is released, you can mark the PR as ready to review.

**Comment by matinzd** [comment]
Landed on [0.69.0-rc0](https://github.com/facebook/react-native/pull/33580).
 
@eps1lon

**Comment by eps1lon** [comment]
> Landed on https://github.com/facebook/react-native/pull/33580.

DefinitelyTyped does not have the infra to provide typings for release candidates. We have to wait for a stable release.

**Comment by matinzd** [comment]
0.69.0 stable is out. @eps1lon

**Comment by kelset** [comment]
just an heasdup, I'm preparing a PR to bump the RN types to 0.69... you might want to wait until after my PR is up & merged before merging this

**Review by kuasha420 — APPROVED** [review]
LGTM !

**Review by peterblazejewicz — APPROVED** [review]

**Comment by matinzd** [comment]
Ready to merge.

**Pull request merged**
