### PR TITLE
Add node/fs.copyFileSync definition

### PR DESCRIPTION
**Pull request by lextiz**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/fs.html#fs_fs_copyfilesync_src_dest_flags
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by lextiz** [comment]
The failures in CI log look similar to failures in the master branch and not related to this change.

**Comment by Flarna** [comment]
Thanks!
Could you please add also the fs constant `COPYFILE_EXCL`.
Besides that it would be nice to add also `fs.copyFile()` for completeness. I think definition should be
```
export function copyFile(src: PathLike, dest: PathLike, callback: (err: NodeJS.ErrnoException | null) => void): void;
export function copyFile(src: PathLike, dest: PathLike, flags: number, callback: (err: NodeJS.ErrnoException | null) => void): void;
```
As usual tests are always welcome :wink:.

**Comment by lextiz** [comment]
I will not have access to computer for next 2 weeks, will complete this PR when back from vacation. In case somebody wants it earlier he is welcome to complete it.

**Comment by Flarna** [comment]
Seems to be completed via #20185

**Comment by lextiz** [comment]
RIght.

**Pull request closed without merging**
