### PR TITLE
[three] add setArray to BufferAttribute

### PR DESCRIPTION
**Pull request by kaktus40**
see [here](https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L50)

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@kaktus40 Please fix the failures indicated in the Travis CI log.

**Comment by kaktus40** [comment]
I corrected the issues

**Comment by efokschaner** [comment]
Hi @kaktus40, thanks for the contribution.

I don't think that `ArrayLike<number>` is the right signature for the parameter to `setArray`. `ArrayLike` is a very general type but the function only wants `TypedArray`s or `undefined`. It won't even accept an actual `Array`, see https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L54

Maybe `ArrayBufferView` would do the trick here. See this comment  https://github.com/Microsoft/TypeScript/issues/15402#issuecomment-299702084 and the surrounding discussion for more thoughts.

Lastly remember to allow `undefined` too as the function explicitly handles that. You can do this by making the parameter optional, by using `array?`

Thanks for fixing up all that linting, I'm not sure why it threw all that at you though...

**Comment by kaktus40** [comment]
That's strange to let undefined as parameter because it will throw an error finally. Nevertheless, I made the change +correct signature of [set](https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L225)

**Comment by efokschaner** [comment]
I made the `undefined` suggestion because of this line which takes care to handle `undefined` https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L58 however if you don't think there's a reason for that support then you can remove the `?`.

**Comment by efokschaner** [comment]
Your latest change to `set()` seems to contradict the docs https://threejs.org/docs/#api/core/BufferAttribute.set and the implementation which would also require a `TypedArray`, so perhaps it should also be `ArrayBufferView`.

**Comment by efokschaner** [comment]
Actually reading this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set , that set method would actually support ArrayLike so it was probably fine as it was.

**Comment by kaktus40** [comment]
Ok I change the signature of set to ```set(value: ArrayLike<number>|ArrayBufferView, offset?: number): BufferAttribute;```

**Comment by efokschaner** [comment]
Great, I'm :+1: Thanks again!

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Pull request merged**
