### PR TITLE
[url-parse] Add missing boolean parameter type and update tests to include this case

### PR DESCRIPTION
**Pull request by wd39**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

**Changing an existing definition**:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: The issue solved is described here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20402 
Original package's tests do not include this case: https://github.com/unshiftio/url-parse/blob/master/test/test.js 
- [-] Increase the version number in the header if appropriate.
- [-] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@ChernenkoPaul can you please take a look

**Comment by wd39** [comment]
Thanks for taking time and reviewing! 

I'll set up a new test project and take a look

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by sandersn** [comment]
@wd39 for housekeeping purposes I'm closing this PR. Feel free to open a fresh one or refresh this one when you have time.

**Pull request closed without merging**
