### PR TITLE
Fix linter errors for react-native FlatList declarations

### PR DESCRIPTION
**Pull request by MNBuyskih**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/flatlist.html

@sarahscott`s PR #15669 has some linter and other errors.  I need this types and tried to fix this erros.

### CODE REVIEW

**Comment by nickcharles** [comment]
Interested in seeing this merge.

**Comment by alloy** [comment]
@RyanCavanaugh Any idea what that comment of the bot is about and I assume that's related to me not getting a mention from the bot?

**Comment by RyanCavanaugh** [comment]
@alloy probably a bug in definition-header parser

**Comment by alloy** [comment]
@RyanCavanaugh Could it be because these maintainer entries are not on the same line? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b00804fc5e06b74e261330f5f2c6044c83dc0e8c/types/react-native/index.d.ts#L3-L4 /cc @gyzerok

**Comment by alloy** [comment]
Yeah that was it. I changed them to be on one line and immediately got a ping for a new PR.

**Pull request merged**
