### PR TITLE
[graphql] Update for v14.2.0 release

### PR DESCRIPTION
**Pull request by martijnwalraven**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/graphql/graphql-js/releases/tag/v14.2.0
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by langpavel** [comment]
Hmm, Error: Unexpected path `.prettierrc`? Why is this happening?

**Review by bradzacher — APPROVED** [review]

**Comment by langpavel** [comment]
@martijnwalraven I think that `.prettierrc` file is not allowed to be commited. You should try delete it

**Comment by martijnwalraven** [comment]
@langpavel Yep, weird, but I'll delete it.

**Review by langpavel — APPROVED** [review]

**Review by IvanGoncharov — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
