### PR TITLE
Mithril: correct generic `Element` type to `HTMLElement`

### PR DESCRIPTION
**Pull request by davwheat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: (none)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by spacejack** [comment]
Sorry, but this change won't won't work for all cases, notably SVGElement.

**Comment by davwheat** [comment]
Ah yes, you're right about that. Are there other examples of where it doesn't work? It's possible we could just add a union type for HTML and SVG element.

The main issue is that some DOM features don't work with the generic `Element` type, such as `.style`

**Comment by spacejack** [comment]
Yes. I think it ended up being the best compromise. If you assume only HTMLElement or SVGElement, you're excluding custom elements or other future standard element types.

**Comment by isiahmeadows** [comment]
> Yes. I think we considered these and Element ended up being the best compromise. If you assume only HTMLElement or SVGElement, you're excluding custom elements or other future standard element types.

@spacejack Couple nits:

1. Custom elements are `instanceof HTMLElement` per spec.
2. MathML uses [`MathMLElement` for all its elements](https://developer.mozilla.org/en-US/docs/Web/API/MathMLElement), and Firefox and Safari both support that even as most other browsers don't. ([And we do explicitly support that](https://github.com/MithrilJS/mithril.js/blob/5f9c635caddc7a9884be034a625f55c9c6c43c54/render/render.js#L11), [complete with tests](https://github.com/MithrilJS/mithril.js/blob/next/render/tests/test-createElement.js#L100-L108).)

@davwheat I *would* be okay with `HTMLElement | SVGElement | MathMLElement`, though, as I personally don't see any new *inline XML* syntaxes being added to HTML anytime remotely soon. [TS does include type support for MathML](https://github.com/microsoft/TypeScript/blob/8894262baccb1d965e71a2d7830236b431e224f7/lib/lib.dom.d.ts#L9649-L9657), but they only just added it in 4.4, so I'm a bit hesitant to do that *quite yet*.

> Side note @spacejack: [I like this](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures), and if we can score https://github.com/microsoft/TypeScript/pull/29317 as well, we could actually redo our types to be fully correct without an explosion of states, and we could even go as far as to validate the selector as well.

**Pull request closed without merging**
