### PR TITLE
fix(node/time-types) Added optional parameter in setTimeou/setInterval

### PR DESCRIPTION
**Pull request by s-pivovarov**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args
https://nodejs.org/api/timers.html#timers_setinterval_callback_delay_args

### CODE REVIEW

**Comment by s-pivovarov** [comment]
UPD: I changed links to documentation. Sorry 😅

**Review by rbuckton — APPROVED** [review]

**Review by ExE-Boss — CHANGES_REQUESTED** [review]
This should also update `types/node/timers.d.ts`: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d3983e4211cd25141b2fb24bcdbbc97b0dd20238/types/node/timers.d.ts#L2-L6><https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d3983e4211cd25141b2fb24bcdbbc97b0dd20238/types/node/timers.d.ts#L8>

**Review by rbuckton — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by s-pivovarov** [comment]
Conflict resolved 👌

**Review by ExE-Boss — APPROVED** [review]
It’d be nice if this also had tests.

**Review by orta — APPROVED** [review]

**Comment by s-pivovarov** [comment]
Ready to merge

**Pull request merged**
