### PR TITLE
[gestalt]: update to version 95.0

### PR DESCRIPTION
**Pull request by zifahm**
See changelog from 85 to 101 https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gestalt ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gestalt@latest/))
was missing the following properties:
1. Fragment
1. jsx
1. jsxs
1. Collection
1. ExperimentProvider

<details>
<summary>as well as these 2 other properties...</summary>
<p>ScrollFetch, useColorScheme</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4efcec59d4cd63b3b2a7e2dcf9542d5e9fca6d4b
</p>

**Review by jakebailey — APPROVED** [review]
I'll approve this but upstream is already at v101.0.8!

**Comment by zifahm** [comment]
Yup updating it now @jakebailey

**Review by jakebailey — APPROVED** [review]

**Comment by zifahm** [comment]
Ready to merge

**Pull request merged**
