### PR TITLE
Adding interfaces to correspond with various options objects

### PR DESCRIPTION
**Pull request by DavidKDeutsch**
For series options, object members that are used vary depending on the type of chart being plotted. While there already existed different options for chart wide types (e.g. options for, say, all line series in a chart), they did not exist for individual series. The only places these interfaces are useful is in casting your own options object, to get autocomplete and type checking. 

Also, replaced the use of <any> with union types in a couple of places.

### CODE REVIEW

**Comment by DavidKDeutsch** [comment]
Also in thie pull request, I have added definitions for highstock

**Comment by vvakame** [comment]
*highcharts/highcharts.d.ts*

to author(@damianog) could you review this PR?

check list

* [ ] pass the Travic-CI test?

---

*highcharts/highstock.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/highcharts
  * http://bower.io/search/?q=highcharts
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (highcharts/highstock-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by damianog** [comment]
@vvakame  changes 1c63705 and bfab162  are fine.

**Comment by vvakame** [comment]
@damianog thanks!
@DavidKDeutsch thanks mate!

**Pull request merged**
