### PR TITLE
[@types/react] Add `onResize` event to video elements

### LINKED ISSUE #63061: Add types definition for resize event on video element.

### PR DESCRIPTION
**Pull request by Semigradsky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react/pull/21973 , https://html.spec.whatwg.org/multipage/media.html#mediaevents
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Closes #63061

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c2c6a52b59ebdfc0fe847bf79c305c57acfb8235
</p>

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by robinmetral** [comment]
It looks like this breaks TS compatibility between our app on React 17 and a library on React 18. Can we make the same change to React 17 types?

Screenshot 2022-11-08 at 15 21 09

☝️ `Body` extends React 18 `HTMLAttributes<HTMLParagraphElement>` and this somehow clashes with React 17 types in the repository

(e.g. #62879 updates the attribute in types for React 16, 17 and 18 and didn't cause issues for us)

**Comment by robinmetral** [comment]
Ah but the problem here is that `onResize` was only added in React 18 (https://github.com/facebook/react/pull/24195), so backporting the change would be inaccurate. Does anyone with better TS skills know how to avoid the conflict I'm describing above? If a reproduction would help I'd be happy to provide one.

**Pull request merged**
