### PR TITLE
[express] replaced deprecated "var" with "let" in index.d.ts

### PR DESCRIPTION
**Pull request by Zulfiqar-Qureshi**
replaced the use of keyword "var" with ES6 "let".
the package that was changed is index.d.ts within express

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by RandinAk** [comment]
Let

**Comment by Zulfiqar-Qureshi** [comment]
> Let

sorry, I didn't understand, what does this mean?

**Review by sandersn — CHANGES_REQUESTED** [review]
`var` merges better than `let` in case somebody wants to extend express types in their own project. I'm not sure this change is worth the risk of breaks.

Is there a lint rule forbidding `let`? I thought `var` was still OK to use on Definitely Typed.

**Comment by Zulfiqar-Qureshi** [comment]
> `var` merges better than `let` in case somebody wants to extend express types in their own project. I'm not sure this change is worth the risk of breaks.
> 
> Is there a lint rule forbidding `let`? I thought `var` was still OK to use on Definitely Typed.

`no-var` lint rule forbids the use of `var` and instead encourages to use `let` or `const`.
but i didn't know that `var` merges better than `let`, i don't think this change would break anything but if you think it would than you are free to reject this change (this is my first open source contribution so apologies if i am doing something out of order)

**Comment by sandersn** [comment]
No problem. Everything's in order, it's just that even minor style changes tend to cause breaks when a package is downloaded 30 million times per month.

**Comment by Zulfiqar-Qureshi** [comment]
> No problem. Everything's in order, it's just that even minor style changes tend to cause breaks when a package is downloaded 30 million times per month.

Totally understandable, should i close this pull request? or is it possible to merge it? Thank you.

**Comment by sandersn** [comment]
I vote to close it. I think it's better to the leave the `var`s where they are.

**Review by RandinAk — COMMENTED** [review]
Change it

**Pull request closed without merging**
