### PR TITLE
Move watchdogs to GHA

### PR DESCRIPTION
**Pull request by jakebailey**
This pulls the code from https://github.com/DefinitelyTyped/types-publisher-watchdog and https://github.com/DefinitelyTyped/typescript-bot-watchdog into workflows in this repo with minimal changes.

### CODE REVIEW

**Comment by jakebailey** [comment]
While here... consolidate some repeated workflow code.

**Review by sandersn — APPROVED** [review]
Seems like a good move. I don't think this centralises too much. At least I hope it doesn't.

**Comment by mustafacryptoafnde-lab** [comment]
# mustafacryptoAfnd

**Review by mustafacryptoafnde-lab — APPROVED** [review]

**Review by mustafacryptoafnde-lab — COMMENTED** [review]
msaleh51130@gmail.com

**Pull request merged**
