### PR TITLE
[React] better typings for flex in CSSProperties

### PR DESCRIPTION
**Pull request by xaviergonz**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://drafts.csswg.org/css-flexbox/
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by vsiao** [comment]
👍

**Comment by paulvanbrenk** [comment]
Thanks, this changed caused a CI failure. Please take a look at those:

```
=== ERRORS ===



Error in material-ui
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.1/node_modules/typescript/lib/tsc.js 

material-ui-tests.tsx(1721,8): error TS2322: Type '{ display: string; flexWrap: string; justifyContent: "space-around"; }' is not assignable to type 'CSSProperties'.
material-ui-tests.tsx(1721,8): error TS2322: Type '{ display: string; flexWrap: string; justifyContent: "space-around"; }' is not assignable to type 'CSSProperties'.
  Types of property 'flexWrap' are incompatible.
    Type 'string' is not assignable to type '"initial" | "inherit" | "unset" | "nowrap" | "wrap" | "wrap-reverse"'.
material-ui-tests.tsx(1742,8): error TS2322: Type '{ display: string; flexWrap: string; justifyContent: "space-around"; }' is not assignable to type 'CSSProperties'.



Error in react-autosuggest
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/node_modules/tslint/lib/index.js/../tslint-cli.js --format stylish index.d.ts react-autosuggest-tests.tsx

react-autosuggest-tests.tsx
136:89   whitespace  missing whitespace
148:71   whitespace  missing whitespace
319:69   whitespace  missing whitespace
418:113  whitespace  missing whitespace



Error in react-bootstrap-daterangepicker
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.1/node_modules/typescript/lib/tsc.js 

../daterangepicker/index.d.ts(7,25): error TS7016: Could not find a declaration file for module 'moment'. '/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/moment/moment.js' implicitly has an 'any' type.



Error in react-daterange-picker
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.1/node_modules/typescript/lib/tsc.js 

../moment-range/index.d.ts(6,25): error TS7016: Could not find a declaration file for module 'moment'. '/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/moment/moment.js' implicitly has an 'any' type.
../moment-range/index.d.ts(10,16): error TS2665: Invalid module name in augmentation. Module 'moment' resolves to an untyped module at '/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/moment/moment.js', which cannot be augmented.
index.d.ts(8,25): error TS2497: Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/moment-range/index"' resolves to a non-module entity and cannot be imported using this construct.
react-daterange-picker-tests.tsx(4,25): error TS2497: Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/moment-range/index"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by xaviergonz** [comment]
I fixed the material-ui problem, but the others seem to be totally unrelated to the commit itself...

**Comment by andy-ms** [comment]
Build's fixed, merging. Thanks!

**Pull request merged**
