### PR TITLE
Adding type definitions for pikaday-time (https://github.com/owenmead/Pikaday, forked from https://github.com/dbushell/Pikaday)

### PR DESCRIPTION
**Pull request by Sayan751**
Adding missing type definitions for pikaday-time, which is forked from pikaday. Copied the existing definitions from pikaday, and added additional (and optional) interface properties for pikaday-time.

### CODE REVIEW

**Comment by Sayan751** [comment]
@sandersn Thank you for the merge. Will this be available on npm `@types`?

**Comment by sandersn** [comment]
Not until a version shows up in the types-2.0 branch. I'm planning an upgrade+merge of today's master merges today or tomorrow, or you can create a new PR yourself. I was going to use `pikaday` in types-2.0 as an example, so that would be a good place to start.

**Comment by Sayan751** [comment]
Yeah I understand now. Actually I noticed the other types-2.0 branch far too late (after submitting this PR), otherwise I would have tried to make a PR against that branch. But at this moment I am little bit tied up :(

**Comment by sandersn** [comment]
No problem. I am about to start the upgrade. It is my full-time job this week. :)

**Pull request merged**
