### PR TITLE
[node] Add https.RequestOptions checkServerIdentity

### PR DESCRIPTION
**Pull request by fgblomqvist**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55949 and https://nodejs.org/dist/latest-v14.x/docs/api/https.html#https_https_request_url_options_callback
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I tried running prettier on the file but looks like it hasn't been done before on the node package, so I skipped it (correct?).

### CODE REVIEW

**Comment by Semigradsky** [comment]
@fgblomqvist you have added `checkServerIdentity` only to typings for node 18.x (ts > 4.8). Also need to add to folders `v14`, `v16`, `ts4.8`, `ts4.8/v14`, `ts4.8/v16`...

**Comment by Semigradsky** [comment]
> Error: Cannot find module '/home/runner/.dts/typescript-installs/4.9/node_modules/typescript'

Looks like it is unrelated to your changes

**Comment by fgblomqvist** [comment]
Yeah couldn't find a way to rerun the CI but let's see if this works now

**Comment by fgblomqvist** [comment]
I have no idea what's going on here 😕

**Comment by fgblomqvist** [comment]
@Semigradsky have I added it to the wrong files? Should I open an issue about this? I'm not familiar with the setup this project uses for testing so I'm not sure what could be wrong here.

**Comment by peterblazejewicz** [comment]
> have I added it to the wrong files? Should I open an issue about this? I'm not familiar with the setup this project uses for testing so I'm not sure what could be wrong here.

Can you update your branch from most recent master and push changes? It looks like someting with dependency resolution causing recent TS to fail:
https://github.com/microsoft/DefinitelyTyped-tools/blob/381f468f6fe4eccd29f3f825127db73edee54532/packages/dtslint/README.md#faq

**Comment by fgblomqvist** [comment]
I already tried that a few times today without success 😕

**Comment by Semigradsky** [comment]
@fgblomqvist The CI was fixed by #63399. Could you please open a new PR?

**Comment by fgblomqvist** [comment]
Looks good now

**Comment by fgblomqvist** [comment]
Done

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@fgblomqvist (and @Semigradsky) thanks!

**Comment by fgblomqvist** [comment]
Ready to merge

**Pull request merged**
