### PR TITLE
[types-2.0] Port pg 6.1.0 types update to types-2.0 branch

### PR DESCRIPTION
**Pull request by aleung**
The same change as in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10839, modified for types-2.0.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Hi @aleung, the CI have failed. Please fix it.

By the way, why reason do you commit with `tsconfig.json`?

**Comment by aleung** [comment]
Strange, the error is in d3-array. But my commit doesn't impact d3-array, and pg has no relationship to d3-array.

Comparing with previous build on types-2.0 branch, looks like the only difference is TypeScript version. My failure test used 2.1.0-dev.20160912 and previous succeed test used 2.1.0-dev.20160910.

Who has privilege can trigger a build on types-2.0 branch to verify it again?

**Comment by aleung** [comment]
@TonyPythoneer I found all other libraries have `tsconfig.json` included. I just follow the way.

**Comment by TonyPythoneer** [comment]
it's wired. I couldn't find d3-array definition.

**Comment by aleung** [comment]
@TonyPythoneer Are you in types-2.0 branch? It doesn't exist in master branch.

**Comment by TonyPythoneer** [comment]
Uhmmm... I don't know what happended.
May you split your changed file in each commit?
Maybe we can easily find problem. :smile:

**Comment by aleung** [comment]
@TonyPythoneer They're a whole. Can't split.

**Comment by aleung** [comment]
@RyanCavanaugh @tomwanzek All PRs on types-2.0 branch failed. They all failed at d3-array definition. Can you have a look?

**Comment by tomwanzek** [comment]
@aleung I am going to look at it from a definitions perspective. Not sure right away, why this error was not flagged on the latest d3-array PR. It did not have any errors before merge.

cc @RyanCavanaugh

**Comment by tomwanzek** [comment]
@aleung @RyanCavanaugh 

I looked into it. The latest typescript@next seems to have changed type inference logic as of yesterday? This might  actually be a regression. But in any case, I have added an explicit type to the test which caused the issue for now, so it does not impact DT/types-2.0 merges in the interim. See PR #11205.

**Comment by tomwanzek** [comment]
PR #11205 passed the tests and is ready to merge as an interim fix.

**Comment by RyanCavanaugh** [comment]
Restarted the CI

**Comment by aleung** [comment]
@zhengbli Your latest commit broke types-2.0 branch CI.

**Comment by andy-ms** [comment]
Needs to merge the latest changes from types-2.0 first.

**Comment by aleung** [comment]
@andy-ms done.

**Review by ghost — APPROVED** [review]

**Pull request merged**
