### PR TITLE
mongoose-simple-random fix results - make them optional

### PR DESCRIPTION
**Pull request by rsxdalv**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
This looks like a common mistake: [Optional Parameters in Callbacks](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)

Does `findRandom` really only pass `res` some of the time? Does any callback you provide have to check whether `res` is present?

**Comment by rsxdalv** [comment]
This adjustment comes directly from debugging a production environment that had issues due to the type turning out to be inaccurate.

It only returns a result if there's any documents found. Which arguably could've been implemented using an empty array, but wasn't.

**Comment by sandersn** [comment]
Ah, was this with the Typescript 2.4 upgrade? If so, I would guess it's because 2.4 checks optionality more strictly than before as well.

**Review by sandersn — APPROVED** [review]

**Comment by rsxdalv** [comment]
I think it was after I enabled strict type predicates (tslint) for the project, and that really puts the pressure on trusting the types, or double checking them for that matter.

I missed this originally because I'm retrofitting these types to a working system, thus some things like the missing results were taken care of (albeit, not always accurately).

**Pull request merged**
