### PR TITLE
react-native-tab-view: Provides its own types

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This will deprecate `@types/react-native-tab-view` in favor of just `react-native-tab-view`. CC @kaoDev, @iRoachie, @timwangdev, @geriux, @kazyk
WARNING: other packages depend on this!

### CODE REVIEW

**Review by kaoDev — APPROVED** [review]
@a-tarasyuk thanks for the update

**Comment by iRoachie** [comment]
This build fails because `react-router-navigation-core` depends on this package. Will need to update `react-router-navigation-core` first.

**Review by iRoachie — CHANGES_REQUESTED** [review]
This build fails because `react-router-navigation-core` depends on this package. Will need to update `react-router-navigation-core` first.

Also this seems to be same PR as #39521. Which is one is the real PR

**Comment by a-tarasyuk** [comment]
cc @sandersn

**Review by iRoachie — APPROVED** [review]

**Pull request merged**
