### PR TITLE
angular: Add currentInstruction to angular-component-router

### PR DESCRIPTION
**Pull request by calebegg**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.angularjs.org/guide/component-router
- [N/A] Increase the version number in the header if appropriate.
- [N/A] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@davidreher can you take a look. I couldn't find this property in the linked docs.

**Comment by davidreher** [comment]
Will take a look tomorrow ... 
CC: @mischi

**Comment by calebegg** [comment]
Oh, sorry, I didn't realize it wasn't documented. [Here are source references](https://github.com/angular/router/search?utf8=%E2%9C%93&q=currentInstruction&type=).

**Comment by davidreher** [comment]
Looks good to me 👍

**Pull request merged**
