### PR TITLE
added types for tunnel-ssh 5.0

### PR DESCRIPTION
**Pull request by noahisapilot**
This PR adds types for [tunnel-ssh 5.0](https://www.npmjs.com/package/tunnel-ssh). 5.0 represented breaking changes from the 4.0 api and I've moved the 4.0 changes to a `/v4` subdirectory. 

---
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [tunnel-ssh npm package](https://www.npmjs.com/package/tunnel-ssh)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by hackerhasid** [comment]
> Config files to check:
> * [`tunnel-ssh/v4/tslint.json`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64852/files/4962e7280e3c1a9927250ae85f5f626a8476e8ea#diff-754450b02c2fbfe94bee8bd7b8e58a2abb79b6a30fd7485ef3046ebb11dc37b6): not [the expected form](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-linter-tslintjson) (check: `defaultSeverity`, `rules`)

Whoops - looks like I missed the requirement around the lint config. Let me see if I can update the PR...

**Comment by cmdshepard** [comment]
@hackerhasid new definitions look good to me.

I'm not sure if the old version should be moved to a subfolder (based on what I see from other libs)

I think it can be discarded since the it'll still be available via an older version tag on NPM

**Review by cmdshepard — CHANGES_REQUESTED** [review]
@hackerhasid new definitions look good to me.

I'm not sure if the old version should be moved to a subfolder (based on what I see from other libs)

I think it can be discarded since it will still be available via the `4.1.1` version tag on NPM

**Review by cmdshepard — APPROVED** [review]

**Comment by cmdshepard** [comment]
Ready to merge

**Pull request merged**
