### PR TITLE
Allow the type of the default value to be different from the type of …

### PR DESCRIPTION
**Pull request by jonas-k**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12436
- [ ] Increase the version number in the header if appropriate.

…the enumerable for all methods that take a default value

### CODE REVIEW

**Comment by Sebazzz** [comment]
Should the type definition not be `T | null` instead of introducing a new type parameter?

**Comment by jonas-k** [comment]
I thought so at first, too. But on the other hand, what if you want to have undefined as default or if you want to have another object as default. Viewing it from the javascript code, this is what happens. The value you provide as default parameter is returned no matter what its type is.

**Comment by Sebazzz** [comment]
The linq.js library always returned null as default, doesn't it?

**Comment by jonas-k** [comment]
linq.js returns null if no default value is provided and no matching element is found in the enumerable. But if a default value is provided that has a different type from the enumerable, this default value is returned if no element from the enumerable was found.
To account for the case where no default value is given, we could add another definition of the function, taking no default value and returning T | null

**Comment by Sebazzz** [comment]
I think the main problem with your change is that type safety is lost entirely. One could have an enumerable of string and return an number as default value. I think it would be best to case the enumerable to the wanted type, then get the correct default value that way. I have a hard time finding a use case where the default value type is different than the type of the enumerable. 

In Javascript, it is possible of course, but I think that from static typing perspective this change is a step backwards.

**Comment by jonas-k** [comment]
Ok then I had the wrong perspective, thinking that typings should represent the behaviour of the underlying javascript code as good as possible.
My real world use case was that I had an enumerable of some type that didn't contain null, but wanted null as the default value of firstOrDefault.
So your suggestion in that case would be casting the enumerable<T> to enumerable<T|null> and using null as default, right?

**Comment by Sebazzz** [comment]
My suggestion is that the return type of should be `T | null`, so the signature would be:

    FirstOrDefault(defaultValue: T, predicate?: ($: T) => boolean): T | null;

**Comment by jonas-k** [comment]
In that case we would always return a value of a type containing null. If I had an enumerable&le;number&gt; and take a number as default the return type would still be number | null, introducing a phantom possibility of the return value being null.

**Comment by Sebazzz** [comment]
It would be added as an additional overload. 

Probably something like this would work:

    FirstOrDefault(defaultValue: T, predicate?: ($: T) => boolean): T;
    FirstOrDefault(defaultValue: null, predicate?: ($: T) => boolean): null;

**Comment by jonas-k** [comment]
The CI tool seems to use TypeScript 1.x, hence it fails recognizing null as type. Is this intended?
My changes were supposed to be compiled with tsc 2.x with strict null checks enabled

**Comment by Sebazzz** [comment]
Yes, that's one of the problems with DT. Not only is a typing dependent on a certain version of a library, but it is dependent on a version of Typescript as well. 

BTW: Could you squash your commits? That allows for easier reviewing.

**Comment by paulvanbrenk** [comment]
@jonas-k can you rebase against `types-2.0` that way `null` will be recognized as a type.

**Comment by jonas-k** [comment]
Rebasing seems to be quite hard because of the big difference between master and types-2.0. Would you mind, if I created a new branch on types-2.0 and committed my changes again?

**Comment by paulvanbrenk** [comment]
@jonas-k sounds good, closing this PR.

**Pull request closed without merging**
