### PR TITLE
[is-number] Added `num is number` user defined type guard as return type

### PR DESCRIPTION
**Pull request by jedster1111**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Hopefully this looks okay, give me a shout if I missed anything or anything needs changing.

### CODE REVIEW

**Review by svens-uk — COMMENTED** [review]
The JSDoc return signature doesn't reflect the added type guard — I'm not an expert at it but I'm reasonably sure that JSDoc supports type guard definitions. Is this something we should add?

**Comment by harryshipton** [comment]
Thanks for adding a type guard though, it seems like a much more sensible way of typing the module! :)

**Comment by jedster1111** [comment]
No problem 😄
I added the type guard to the JSDoc like this:
```js
/**
 * Will test to see if the argument is a valid number, excluding Infinity and NaN.
 * @param num Any value that should be tested for being a number
 * @returns {num is number} true if the parameter is a valid number, otherwise false
 */
declare function is_number(num: any): num is number;
```
but I got an error when I ran the lint tests:
```
ERROR: 12:13  no-redundant-jsdoc-2  Type annotation in JSDoc is redundant in TypeScript code.
```
which I guess makes sense.

**Comment by jedster1111** [comment]
I think I just realised this change isn't quite right as this library checks both string and number inputs. Maybe you could type guard to a string or number though, not sure if that would be helpful though.

**Comment by harryshipton** [comment]
I'll take a closer look this evening 🙂

**Comment by jedster1111** [comment]
Okay, I added string to the type guard, and think it works quite nicely from what I can see.
  - Narrows `any` and `unknown` to `string | number`.
  - Keeps `string` as `string`
  - Keeps `number` as `number`

Wasn't 100% sure how to write a meaningful test for it though 😄

**Comment by harryshipton** [comment]
Okay, I agree that the JSDoc error does make sense and we don't need to add typings to it.

Testing the type when isNumber() returns true should be fine — the type when isNumber() returns false is undetermined so I don't think we need to test it. I'm happy with the changes unless someone else raises any issues. 👍

**Review by svens-uk — APPROVED** [review]

**Pull request merged**
