### PR TITLE
[Estree] Added token property

### PR DESCRIPTION
**Pull request by Robinfr**
Added missing token property to the Program definition.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://esprima.readthedocs.io/en/4.0/syntactic-analysis.html#token-collection
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by RReverser** [comment]
Token definition is not part of the ESTree standard and is implementation detail different between parsers. You seem to assume Esprima in these definitions, so it's best to add this property to esprima's definitions.

**Comment by RReverser** [comment]
As in, you can create a new interface extending `ESTree.Program` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/esprima/index.d.ts and make functions return it instead of the `Program` directly.

**Comment by Robinfr** [comment]
@RReverser neither are comments tho, but they have been included in ESTree.

**Review by RReverser — CHANGES_REQUESTED** [review]
Comments might be a mistake too, but at least they are compatible across estraverse / esprima / acorn / ..., unlike tokens.

**Comment by Robinfr** [comment]
Created a new PR for Esprima instead.

**Pull request closed without merging**
