### PR TITLE
feat(yargs): add types for yargs@v17

### PR DESCRIPTION
**Pull request by bcoe**
yargs@17 is a major overhaul of how asynchronous commands, builders, and middleware are handled (_it's now possible to `await parse()` and `await .argv`_).

This should not be merged until https://github.com/yargs/yargs/pull/1876 is released (_once Node 10 is EOL_).

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yargs/yargs/pull/1876
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by bcoe** [comment]
[this issue](https://github.com/yargs/yargs/issues/1899) is tracking the additional work to be done for yargs@v17.

**Comment by forivall** [comment]
Please mark the PR as "Draft" status in github so that wee ol' typescript-bot knows it's still WIP!

**Comment by bcoe** [comment]
@forivall done 👍

**Comment by bcoe** [comment]
@forivall just released `v17` of yargs, the bulk of the changes relate to handling of asynchronous behavior.

**Pull request merged**
