### PR TITLE
feat: add react-power-tooltip

### PR DESCRIPTION
**Pull request by akkumar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with dts-gen --dt, not by basing it on an existing project.
- [x] Represents shape of module/library correctly
- [x] tslint.json should be present and it shouldn't have any additional or disabling of rules. Just content as { "extends": "dtslint/dt.json" }. If for reason the some rule need to be disabled, disable it for that line using // tslint:disable-next-line [ruleName] and not for whole package so that the need for disabling can be reviewed.
- [x] tsconfig.json should have noImplicitAny, noImplicitThis, strictNullChecks, and strictFunctionTypes set to true

### CODE REVIEW

**Comment by akkumar** [comment]
@justinrhodes1 - I have added the typescript definitions here for https://github.com/justinrhodes1/react-power-tooltip . 

Can you help review the same ?

**Comment by elibarzilay** [comment]
@akkumar: looks like @justinrhodes1 didn't reply -- do you want to still wait for a review?

**Comment by akkumar** [comment]
@elibarzilay I guess quite some time has passed since the request to review. It would be nice to get this checked in to DefinitelyTyped even if the original author did not review it. We can always "change" the definitions if the need be, at a later point of time. 

So - if you can help check this in to the repository - that would be great.

**Comment by justinrhodes1** [comment]
@akkumar @elibarzilay thanks for the great work and apologies for not getting back earlier. I was completely sidelined by another project. I will look at the typescript definitions over the weekend just to double-check but on first glance all seems OK! Thanks again!

**Comment by Hainesy** [comment]
Missing `padding?: string` on the TooltipProps.

**Comment by matigumma** [comment]
Missing alert?: string type on props

**Pull request merged**
