### PR TITLE
Types2.0

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
In this PR:
- Rename a bunch of folders to match their target NPM packages
- Remove some spurious ambient external module declarations
- Deleted the duplicated imap declaration

Targeting the types-2.0 branch since this renaming will presumably break some people's tsd / typings configurations

### CODE REVIEW

**Comment by couven92** [comment]
For chrome.d.ts :+1:

**Comment by vvakame** [comment]
👍 

IMO, We should keep old definitions for backward compatible.
But old definitions include reference comment only.

e.g. `adal-angular/adal.d.ts → adal/adal.d.ts`.

```
$ cat adal-angular/adal.d.ts
// Type definitions for ADAL.JS 1.0.8
// Project: https://github.com/AzureAD/azure-activedirectory-library-for-js
// Definitions by: mmaitre314 <https://github.com/mmaitre314>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// this file will be remove. use adal/adal.d.ts instead of adal-angular/adal.d.ts
/// <reference path="../adal/adal.d.ts" />
```

If we use this method.
We should separate commits that rename commit and `put old definitions` commit.
We can take over the history. (maybe...)

**Comment by vvakame** [comment]
@basarat @horiuchi do you have any opinions?

**Comment by horiuchi** [comment]
good work 👍 

On this occasion, we may rename not only just folder name but file name.
e.g. `amplify/amplifyjs.d.ts` to `amplify/amplify.d.ts`, `auth0-lock/auth0.lock.d.ts` to `auth0-lock/auth0-lock.d.ts`, and others.

**Comment by RyanCavanaugh** [comment]
Superceded

**Pull request closed without merging**
