### PR TITLE
Add chrome.system.display definitions

### PR DESCRIPTION
**Pull request by RReverser**

### CODE REVIEW

**Comment by couven92** [comment]
Looks good! But just out of curiosity, where did you get the API documentation from? I cannot seem to find the system.display module in the API index ( https://developer.chrome.com/extensions/api_index )

:+1:

**Comment by RReverser** [comment]
Argh, you're right, this seems to be app-specific API, so rather belongs to chrome-app.d.ts. https://developer.chrome.com/apps/system_display

**Comment by RReverser** [comment]
@couven92 Moved it.

**Comment by vvakame** [comment]
can I merge this PR?

**Comment by RReverser** [comment]
@vvakame Yes please.

**Pull request merged**
