### PR TITLE
#10342 Added hideNoData/showNoData methods to highcharts

### PR DESCRIPTION
**Pull request by nitoloz**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Added hideNoData/showNoData to highcharts

### CODE REVIEW

**Comment by damianog** [comment]
Hi @nitoloz could you point us a reference from public api?

I cannot see these method in http://api.highcharts.com/highcharts#Chart 

Thanks.

**Comment by nitoloz** [comment]
Hi @damianog 
Its present in a no-data-to-display plugin officially supported by Highcharts.
[Here](http://www.highcharts.com/component/content/article/2-articles/news/125-new-features-drilldown-and-no-data) is highcharts presented plugin and [here](https://code.highcharts.com/modules/no-data-to-display.src.js) is a no-data-to-display plugin source with public methods that I have added.
They extend highcharts Chart object and are really useful

**Comment by damianog** [comment]
@nitoloz maybe it will be better (for me and I think @baltie too) to extend it in a separate definition file like:

highcharts-modules-no-data-to-display.d.ts 

```
/// <reference path="highcharts.d.ts" />
interface HighchartsChartObject {
     /** 
     * Returns true if there are data points within the plot area now 
     * @return {boolean} If chart has any data. 
     * @since 3.0.8 
    */ 
    hasData(): boolean; 
    
    /** 
    * Hide the 'No data to display' message added by the no-data-to-display plugin.  
    * @since 3.0.8 
    */ 
    hideNoData(): void;

     /** 
     * Display a no-data message. 
     * @param {String} message An optional message to show in place of the default one 
     * @since 3.0.8 
     */ 
    showNoData(message?: string): void;          
}
```

and so on for other plugins and modules to reflect http://code.highcharts.com/

Would you consider to pull this solution?

**Comment by nitoloz** [comment]
@damianog yes, I think your solution would be better.
Am I right that it will automatically extend the HighchartsChartObject?

**Comment by damianog** [comment]
@nitoloz yes I have tested, so if you add that file I'll review it for you.

**Comment by damianog** [comment]
Sorry @nitoloz I did not tell you must add the header 

```
// Type definitions for ...
// Project: http://www.highcharts.com/
// Definitions by: 
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
```

**Comment by nitoloz** [comment]
Thank you @damianog 
Added .test.ts file as well

**Comment by nitoloz** [comment]
@damianog could you please check the test file?
I am not quite sure that HighchartsChartObject extension by no-data-to-display works correctly in tests or is there anything I am doing wrong?

**Comment by damianog** [comment]
@dt-bot  👍

**Comment by inad9300** [comment]
This is a very nice solution to extend the typings! (I find it a bit weird that TypeScript merges together the interfaces with the same name, but anyway, it's a good case to take advantage of this.)

Now I'm concerned about how to extend the JavaScript behind those interfaces. The approach taken by other modules is to declare a function that can be called to extend Highcharts, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts-more.d.ts

Otherwise, how are you importing `no-data-to-display` and extending Highcharts with it?

Something similar should be put in place here, I think. In any case, a common approach should be taken for all the modules (`highcharts-more` is not exactly a module, it is a bit of an special case, but it behaves the same way as modules do).

**Comment by baltie** [comment]
@inad9300 I agree. If you have the time, please make it a PR. :)

**Pull request merged**
