### PR TITLE
@types/google-apps-script "December 13, 2018" update

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
@grant here are the @types/google-apps-script .d.ts files to support APIs as of last release (December the 13th)

Some of the changes in the files are only in comments; maybe I should have not included those in the PR.

### CODE REVIEW

**Review by grant — APPROVED** [review]
Thanks. Please address feedback before merging.

**Comment by PopGoesTheWza** [comment]
@grant 
Sorry. This is my first PR ever. I am not sure why CI Travis fails, but I suspect it is because I should have updated (and commit) index.d.ts with the two new .d.ts files.
Am I guessing right?
If so do I need to issue a new PR?

**Comment by grant** [comment]
Thanks for the PR. Press the **Details** to see the issue.
- continuous-integration/travis-ci/pr — The Travis CI build failed

---

This is the issue:

```
Error: Unused file /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/google-apps-script/google-apps-script.card-service.d.ts
```

You should:

- Keep the PR
- Delete `.card.d.ts`
- In the file `index.d.ts`, rename:
  - `/// <reference path="google-apps-script.card.d.ts"/>`
  - `/// <reference path="google-apps-script.card-service.d.ts"/>`

**Review by PopGoesTheWza — COMMENTED** [review]
`google-apps-script.data-studio.d.ts` added
`google-apps-script.card-service.d.ts`fixed
entries reordered as per `https://developers.google.com/apps-script/reference/`

**Comment by grant** [comment]
LGTM.
Please merge DefinitelyTyped maintainer.

**Comment by tombell** [comment]
This PR once again changed `Card` to `Card_Service` as per comment on a previous PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27235#issuecomment-405944260 /cc @grant

**Comment by PopGoesTheWza** [comment]
@tombell Sorry for I was not aware of this prior issue. I will patch my fork of https://github.com/motemen/dts-google-apps-script to integrate the renaming of `Card_Service' into 'Card' in the future.
@grant do you want me to create a new PR once this is done?

**Comment by tombell** [comment]
@PopGoesTheWza awesome, I just noticed when I tried updating today, thanks for future fix 👍

**Comment by grant** [comment]
Well, we need the generator to not do this. We can't manually fix `Card_Service` every time.

I don't think @motemen is maintaining the generator, but the fix should be done there. Adding a PR to find and replace this change should be added to the bash file.

Old PRs:
https://github.com/motemen/dts-google-apps-script/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by PopGoesTheWza** [comment]
@grant you initiated your own generator right?
Meanwhile i’ll Fix my fork and issue a PR

**Comment by grant** [comment]
I started a generator, which would ideally generate Advanced Services as well. But I'm currently working on other things here at Google.
https://github.com/grant/google-apps-script-dts

Can you make `Card` and `Card_Service` aliases?

```ts
type Card_Service = Card;
```

That way you can use either `Card` or `Card_Service`.

**Comment by PopGoesTheWza** [comment]
@grant personally I would favor the alias approach (and document it as up to the end user to integrate)
I gave a quick look at your project in case I could contribute.

**Comment by PopGoesTheWza** [comment]
@tombell to avoid adding kludge to the "maybe not still supported" dts-google-apps-script importer, what do you think of simply adding a namespace alias to your code?
```javascript
import Card = GoogleAppsScript.Card_Service;
```
I had overlooked this TypeScript feature and will start using it myself to shorten/simplify my own code.
@grant depending on your position on this, I can try to patch my fork https://github.com/PopGoesTheWza/dts-google-apps-script to either have `Card_Service` namespace renamed as `Card` automatically or include an alias so that both namespace can be used.

**Comment by tombell** [comment]
@PopGoesTheWza I'll give that a test, as I already have some type defs to add some missing stuff.

**Comment by PopGoesTheWza** [comment]
@tombell is that some type default relevant with some google-apps-script? If so and if you feel the community could benefit from it, those could be added to the package.

**Comment by tombell** [comment]
@PopGoesTheWza I think it's just this, which was part of the definitions but got removed:

```declare namespace GoogleAppsScript {
  export module Card {
    // XXX: this was removed in the type definitions update. It's the parameter of callback functions.
    export interface ActionEvent {
      messageMetadata: {
        /**
        * An access token. You can use this to enable access to user data using temporary Gmail add-on scopes.
        */
        accessToken: string;
        /**
        * The message ID of the thread open in the Gmail UI.
        */
        messageId: string;
      }
      /**
      * Indicates where the event originates (web, iOS, or Android).
      */
      clientPlatform: string;
      /**
      * The current values of all form widgets in the card, restricted to one value per widget. The keys are the string IDs associated with the widgets.
      *
      * The event object provides `formInput` as a convenience for when you need to read data from multiple widgets with expected singular values, such as text inputs and switches.
      *
      * For multi-valued widgets such as checkboxes, you can read each value from `formInputs` instead.
      */
      formInput: { [key: string]: string };
      /**
      * The current values of widgets in the card, presented in arrays. The keys are the string IDs associated with the widget.
      *
      * For single-valued widgets, the value is presented in a single-element array. For multi-valued widgets such as checkboxes, all the values are presented in an array.
      */
      formInputs: { [key: string]: string[] };
      /**
      * Any additional parameters you supply to the `Action` using `Action.setParameters()`.
      */
      parameters: { [key: string]: string };
    }
  }
}```

**Pull request merged**
