### PR TITLE
[4.0.0] React-Select: update NonceProvider's Props types

### PR DESCRIPTION
**Pull request by Nokel81**
See the current flow type in https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/NonceProvider.js

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by kylemh — APPROVED** [review]
lgtm

**Review by Methuselah96 — CHANGES_REQUESTED** [review]
Can you update the version number?

**Comment by Nokel81** [comment]
@Methuselah96 Which version number? The only one I can find is in the `index.d.ts` file but this change should apply to v4.0.0 as well (as mentioned in the commit I referenced).

**Review by Methuselah96 — APPROVED** [review]
Sorry, my bad, I didn't realize that I had already updated the version number to 4.0 (oops).

**Review by andrewbranch — APPROVED** [review]

**Comment by Nokel81** [comment]
Ready to merge

**Pull request merged**
