### PR TITLE
Add recent react-native-tvos types to react-native

### PR DESCRIPTION
**Pull request by adbl**
TV support for react-native has moved to a separate react-native-tvos. The current (and foreseeable) implementation is a fork of react-native, it supports the mobile platforms and TV additions. As such it's imported as `react-native` in TypeScript.  An attempt was made to keep the new TV specific types in the separate repo, but it didn't seem to work. See https://github.com/react-native-community/react-native-tvos/pull/102

The only viable option I could think of was to add the new types to `@types/react-native` too, there are already TV specific types there and it should be the least annoying/confusing way to get your react-native + TV typescript working properly. I have documented the types with **react-native-tvos** to indicate the dependency, and updated the old TV specific ones.

Credit for the types should be attributed to @Krisztiaan

- [✔] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.63.1/index.js

- [❓] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
How/where?

- [ ❌] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

I didn't 🤥

I am seeing the following unrelated errors in master present in this PR as well:

```
test/index.tsx:267:62 - error TS2345: Argument of type 'TextStyle' is not assignable to parameter of type 'false | ImageStyle | RegisteredStyle<ImageStyle> | RecursiveArray<false | ImageStyle | RegisteredStyle<ImageStyle> | null | undefined> | StyleProp<...>[] | null | undefined'.
  Type 'TextStyle' is not assignable to type 'ImageStyle'.
    Types of property 'overflow' are incompatible.
      Type '"hidden" | "visible" | "scroll" | undefined' is not assignable to type '"hidden" | "visible" | undefined'.
        Type '"scroll"' is not assignable to type '"hidden" | "visible" | undefined'.

267 const combinedStyle7 = StyleSheet.compose(composeImageStyle, composeTextStyle); // $ExpectError
                                                                 ~~~~~~~~~~~~~~~~

test/index.tsx:269:7 - error TS2322: Type 'StyleProp<TextStyle>' is not assignable to type 'StyleProp<ImageStyle>'.
  Type 'TextStyle' is not assignable to type 'StyleProp<ImageStyle>'.
    Type 'TextStyle' is not assignable to type 'ImageStyle'.

269 const combinedStyle8: StyleProp<ImageStyle> = StyleSheet.compose(composeTextStyle, composeTextStyle); // $ExpectError
          ~~~~~~~~~~~~~~

test/index.tsx:271:7 - error TS2322: Type 'StyleProp<TextStyle>' is not assignable to type 'StyleProp<ImageStyle>'.
  Type 'TextStyle' is not assignable to type 'StyleProp<ImageStyle>'.
    Type 'TextStyle' is not assignable to type 'ImageStyle'.

271 const combinedStyle9: StyleProp<ImageStyle> = StyleSheet.compose([composeTextStyle], null); // $ExpectError
          ~~~~~~~~~~~~~~

test/index.tsx:273:7 - error TS2322: Type 'StyleProp<TextStyle>' is not assignable to type 'StyleProp<ImageStyle>'.
  Type 'TextStyle' is not assignable to type 'StyleProp<ImageStyle>'.
    Type 'TextStyle' is not assignable to type 'ImageStyle'.

273 const combinedStyle10: StyleProp<ImageStyle> = StyleSheet.compose(Math.random() < 0.5 ? composeTextStyle : null, null); // $ExpectError
          ~~~~~~~~~~~~~~~

test/index.tsx:1286:9 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ViewProps | Readonly<ViewProps>): View', gave the following error.
    Type '{ backgroundColor: { resource_paths: string[]; }; }' is not assignable to type 'StyleProp<ViewStyle>'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ resource_paths: string[]; }' is not assignable to type 'string | unique symbol | undefined'.
          Type '{ resource_paths: string[]; }' is not assignable to type 'unique symbol'.
  Overload 2 of 2, '(props: ViewProps, context: any): View', gave the following error.
    Type '{ backgroundColor: { resource_paths: string[]; }; }' is not assignable to type 'StyleProp<ViewStyle>'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ resource_paths: string[]; }' is not assignable to type 'string | unique symbol | undefined'.
          Type '{ resource_paths: string[]; }' is not assignable to type 'unique symbol'.

1286         style={{
             ~~~~~

  index.d.ts:2522:5
    2522     style?: StyleProp<ViewStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps> & Readonly<{ children?: ReactNode; }>'
  index.d.ts:2522:5
    2522     style?: StyleProp<ViewStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps> & Readonly<{ children?: ReactNode; }>'

test/index.tsx:1297:9 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ViewProps | Readonly<ViewProps>): View', gave the following error.
    Type '{ backgroundColor: { semantic: string; dynamic: { light: string; dark: string; }; }; }' is not assignable to type 'StyleProp<ViewStyle>'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ semantic: string; dynamic: { light: string; dark: string; }; }' is not assignable to type 'string | unique symbol | undefined'.
          Type '{ semantic: string; dynamic: { light: string; dark: string; }; }' is not assignable to type 'unique symbol'.
  Overload 2 of 2, '(props: ViewProps, context: any): View', gave the following error.
    Type '{ backgroundColor: { semantic: string; dynamic: { light: string; dark: string; }; }; }' is not assignable to type 'StyleProp<ViewStyle>'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ semantic: string; dynamic: { light: string; dark: string; }; }' is not assignable to type 'string | unique symbol | undefined'.
          Type '{ semantic: string; dynamic: { light: string; dark: string; }; }' is not assignable to type 'unique symbol'.

1297         style={{
             ~~~~~

  index.d.ts:2522:5
    2522     style?: StyleProp<ViewStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps> & Readonly<{ children?: ReactNode; }>'
  index.d.ts:2522:5
    2522     style?: StyleProp<ViewStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps> & Readonly<{ children?: ReactNode; }>'

test/index.tsx:1310:43 - error TS2339: Property 'resource_paths' does not exist on type 'unique symbol'.

1310 PlatformColor('?attr/colorControlNormal').resource_paths.push('foo'); // $ExpectError
                                               ~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by Krisztiaan** [comment]
When I added these types to the `react-native-tvos` repo for the same reason it's a fork. I think a matching way to handle this would be to create a `@types/react-native-tvos` (copy snapshotted `@types/react-native`) and install it the same way the `-tvos` fork is installed. I wanted to do that here as well, but `DefinitelyTyped` is definitely slow to move, as far as I've seen.

**Comment by alloy** [comment]
Thanks for taking the time!

However, if anything, I think the existing TV types should be _removed_ from these typings, rather than extended. For instance, we’re also not adding types for the macOS fork to these typings.

Looking at the original PR, it sounds like @Krisztiaan feels like he can fix it in the TV repo, which would have my preference.

**Comment by alloy** [comment]
> I am seeing the following unrelated errors in master present in this PR as well:

Btw, regarding these type errors; they are expected, which is tested with the trailing `// $ExpectError` comment.

**Comment by adbl** [comment]
Let's await and see if we can find a way to make it work in the tvos repo. I have my doubts.

@Krisztiaan how would it work in practice if we do it with `@types/react-native-tvos`. Does that mean everywhere I import react native I'll need to change to `import ... from 'react-native-tvos'` to get the type information? Would that mean we also have to reexport the actual JS implementation under `react-native-tvos`?

**Comment by adbl** [comment]
> Thanks for taking the time!
> 
> However, if anything, I think the existing TV types should be _removed_ from these typings, rather than extended. For instance, we’re also not adding types for the macOS fork to these typings.
> 
> Looking at the original PR, it sounds like @Krisztiaan feels like he can fix it in the TV repo, which would have my preference.

It's a different situation when tvos since we import it the same way as RN:`import ... from 'react-native'`. This has implications on how to extend/include the additional types. I agree though that having them in the tvos repo is preferred so let's see if we manage.

**Comment by adbl** [comment]
@alloy I was adviced by @Krisztiaan and tried to following but it's still doesn't augment the RN types correctly, the namespace gets cleared out and only the additional types are present:

in `react-native-tvos/index.d.ts` I have:

```
/// <reference types="react-native" />

import React from 'react';
import { ViewProps, ScrollViewProps } from '@types/react-native';

declare module 'react-native' {
...
```

I think the problem is `import ... from 'react-native'` imports itself, since we install the package like this in package.json: `"react-native": "npm:react-native-tvos@latest"`. I believe changing that would be very complicated, @dlowder-salesforce can you comment on that?

Although I agree having the types in react-native-tvos is preferred, it doesn't seem possible currently. I suggest to accept these additional types until someone can figure out how they should be extended properly. It would be worse to just leave like it is now.

**Comment by adbl** [comment]
@Krisztiaan proposed a solution for react-native-tvos, closing this one.

**Comment by alloy** [comment]
Great, thanks 👍

**Pull request closed without merging**
