### PR TITLE
Updating HashMap to the latest version

### PR DESCRIPTION
**Pull request by outring**
Updating [HashMap](https://github.com/flesler/hashmap) to latest version and adding commonjs modules support.

### CODE REVIEW

**Comment by vvakame** [comment]
@rafalwrzeszcz could you review this PR?

**Comment by rafalwrzeszcz** [comment]
I'm not really familiar with latest HashMap changes, but looks fine. The tests run fine, so I guess it's OK. If you ask me - I'm for merging it, always better than nothing. If someone will notice any problems with this `.d.ts`, we will know what to fix.

**Comment by outring** [comment]
So, maybe merge it? :)

**Comment by vvakame** [comment]
@rafalwrzeszcz okay, thanks!
@outring it merged. thanks mate!

**Pull request merged**
