### PR TITLE
Update the signature of Node.js fsPromises.mkdir

### PR DESCRIPTION
**Pull request by johan13**
Add support for passing an object as the second argument to fsPromises.mkdir. Starting with Node 10 the parameter can be an object and not just a string / number. This had already been updated for the regular fs.mkdir methods, but not to fsPromise.

From v9 to v10 the name of the parameter was changed from mode to options. This PR also updates that to match the Node.js documentation.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fspromises_mkdir_path_options
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The tests / lint doesn't run on my system even before my changes. I will wait for the CI build to validate. Increasing version number or changing tslint.json is not motivated.

### CODE REVIEW

**Review by ajafff — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by Flarna — APPROVED** [review]

**Review by islishude — APPROVED** [review]

**Review by ZaneHannanAU — APPROVED** [review]

**Comment by ZaneHannanAU** [comment]
We really need to get some of those broken packages deprecated.

**Comment by johan13** [comment]
I will rebase and see if that helps with the CI failure.

**Review by SimonSchick — APPROVED** [review]
My bad for forgetting the promisifed version I guess, a test would be nice tho :)

**Comment by Flarna** [comment]
@andy-ms @RyanCavanaugh Any chance that this get merged even CI fails? Fails are unrelated and we have seen similar fails since quite a while in several other PRs.

**Pull request merged**
