### PR TITLE
Make the 'value' prop optional in 'ProviderProps' interface.

### PR DESCRIPTION
**Pull request by felypeterra**
Make the 'value' prop optional in 'ProviderProps' interface to allow this cleaner syntax in cases where the context value is not dynamic:

```
import { Context } from '@/contextprovider

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
  <html>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <Context.Provider>
          {children}
        </Context.Provider>
      </body>
    </html>
  )
}
 
```

And contextprovider.tsx looks like:

```
import React from 'react';
import get_hostname from './get_hostname';

export const Context = React.createContext<object>(get_hostname(process.env.environment));

export const useContext = () => React.useContext(Context);
```

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
`createContext` has no optional value either so there's no strong case to support an optional value even if the context value can be undefined. 

In its current state, it's definitely wrong since it allows omission of the `value` prop even when the context value is non-nullable.

**Comment by felypeterra** [comment]
> `createContext` has no optional value either so there's no strong case to support an optional value even if the context value can be undefined.
> 
> In its current state, it's definitely wrong since it allows omission of the `value` prop even when the context value is non-nullable.

But that's just how it should be because when we don't provide a value prop to the `Context.Provider`, it will then use the initial value set in `createContext`. That should be required, even if nullable or undefined.

I actually provided the worst example possible above. But let's consider a case in Next.js, like a theme provider, which is the most common one.

If the value in `Context.Provider` is optional, I can create a context with useState with `theme` and `setTheme` being the default value of the context, in a `themecontext.tsx` file with the `'use client'` directive, and `export Context`.

In the `layout.tsx`, I then `import Context` from `themecontext.tsx` and use it directly in `RootLayout` without re-defining its value, since it's static, because it's managed by `useState` and can be changed with `setTheme` anywhere.

This way, it's not necessary to redefine the context value in `RootLayout`, which would not be possible because you can't use `useState` in server components. So, we would need to create a middleman component or import extra stuff, resulting in more lines of code than necessary.

**Comment by eps1lon** [comment]
> @eps1lon, but that's just how it should be because when we don't provide a value prop to the Context.Provider, it will then use the initial value set in createContext. That should be required, even if nullable or undefined.

That's a good point. I'll bring it up internally.

**Comment by eps1lon** [comment]
>  but that's just how it should be because when we don't provide a value prop to the Context.Provider, it will then use the initial value set in createContext. That should be required, even if nullable or undefined.

I double checked what happens if you nest a `<Context.Provider>`. It does not fall back to the default value. `<Context.Provider>` is equivalent to `<Context.Provider value={undefined}>`. Children of `<Context.Provider>` will not read the default value but `undefined`: https://codesandbox.io/p/sandbox/react-omitted-context-value-d7ylr5?file=%2Fsrc%2Findex.js%3A7%2C32

Was this maybe the case in an older version of React? Or do you have a repro highlighting how children of `<Context.Provider>` read the default value of `createContext` and not `undefined`?

So we shouldn't allow omitting `value` unless the possible value for the context is `undefined`. But even then we shouldn't allow omitting `value` for the same reason we also don't allow `createContext`.

**Pull request closed without merging**
