### PR TITLE
Create jBinary.d.ts

### PR DESCRIPTION
**Pull request by tbureck**
Hey folks,

some addition to this great project: the jBinary library by the jDataView team.. and probably some other folks as well. What do you think?

Best regards

### CODE REVIEW

**Comment by tbureck** [comment]
I apparently was on a veeery old TypeScript version :) Fixed the stuff Travis has moaned about!

**Comment by vvakame** [comment]
@tbureck thank you your contributions!
please check this document. http://definitelytyped.org/guides/contributing.html

* rename jBinary/jBinary.d.ts to jbinary/jbinary.d.ts
* add tests

**Comment by tbureck** [comment]
Alright, I missed that document.

I'm not too sure about the tests (neither their purpose if they're not used in any way), but is it good now?

**Comment by vvakame** [comment]
@tbureck okey, thanks mate!

**Pull request merged**
