### PR TITLE
:trash: remove Puppeteer v0 sources

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is to gradually phase out Puppeteer definition types, as from v7 it
ships native types included (rewritten to TS). This cannot be easily doe
due to popularity of the Puppeteer and its types. v0 seems to be non referenced across
DT.

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by cameronhunter — APPROVED** [review]
I'm happy to remove some of the older type definitions, however, I would like to keep more recent versions. I have a use-case where I need the type definitions without depending directly on the puppeteer package. I'm happy to talk more through this to provide context.

**Comment by peterblazejewicz** [comment]
> I'm happy to remove some of the older type definitions, however, I would like to keep more recent versions. I have a use-case where I need the type definitions without depending directly on the puppeteer package. I'm happy to talk more through this to provide context.

I'm about only to remove either old sources, or entire source on DT only. This won't impact @types/puppeteer on the NPM yet. I'd like to remove v0 first, just source, @types/puppeteer@0 are valid NPM entry:
https://unpkg.com/browse/@types/puppeteer@0.13.12/

**Comment by peterblazejewicz** [comment]
> . I'm happy to talk more through this to provide context.
@cameronhunter yes, please. The intent here is to ease the workload on the DT/TS ecosystem

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
