### PR TITLE
[big.js] Deconstify enums

### LINKED ISSUE #29864: [@types/big.js] TypeError: Cannot read property 'RoundUp' of undefined
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
@nycdotnet @googol 

I'm trying to use big.js, but I'm getting type errors on the const enums. I'm not sure if this is something that can be fixed through some sort of tsconfig change or if it's a genuine bug in the typing. Any guidance would be appreciated.

The simple code...

```
import { Big, RoundingMode } from 'big.js';

Big(1).round(0, RoundingMode.RoundUp);
```

Results in: `TypeError: Cannot read property 'RoundUp' of undefined`.

I'm running the app through ts-node (not compiled with tsc) when this occurs which I'd think is a totally normal use case at this point.

I think if these enums were changed to non-const so they'd work fine at runtime. However, I have other const enums in my code that work without issue so it seems to be specific to this package.

### PR DESCRIPTION
**Pull request by jablko**
These const enums [can't be used with `isolatedModules: true`](https://www.typescriptlang.org/tsconfig#references-to-const-enum-members):

```sh
error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

Can they be changed to plain enums?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29864

### CODE REVIEW

**Comment by nycdotnet** [comment]
Sorry it's been so long since I've worked on this I'm having a hard time thinking of how this would break current users.  @sandersn you added the linting rule regarding no const enums - this definition was set up with const enums before `isolatedModules` existed.  The library itself just wants the numbers at runtime.  Do you think this change will break things?  Is there a good way to test this (maybe both ways) within the Definitely Typed infrastructure?

@jablko I think your PR should also remove the linting rule in this directory that turns off the `no-const-enum` rule

**Review by sandersn — CHANGES_REQUESTED** [review]
big.js doesn't actually have objects named RoundingMode or Comparison, so they can't be turned into real enums because a reference like `RoundingMode.RoundDown` be emitted to .js that way.

There's no convenient way to get rid of the const enums that I can see--you can define a *type* for them, like `type Comparison = 1 | 0 | -1`.
But you can't define *values* that the original package doesn't define, so no `const RoundDown: 0 = 0`, for example.

For a less-used package, it might be OK to remove those names, but lots of people presumably depend on Typescript to emit Comparison.GT as 1.

**Comment by jablko** [comment]
@nycdotnet You're right, isolatedModules only bombs if const enums are used. What do you think about marking them `@deprecated` to discourage that?

**Review by sandersn — APPROVED** [review]
Technically, this looks good to me. I don't use big.js so I don't know how its users will respond. Maybe @nycdotnet has an opinion?

**Comment by nycdotnet** [comment]
looking

**Comment by nycdotnet** [comment]
I think this will work.  I suggest mentioning the readonly properties in addition to the constants, such as - `Use 0 or Big.roundDown instead`.  Nice work.

**Comment by nycdotnet** [comment]
Only other concern is that methods like `cmp` and `prec` may have to be refactored to take the constants.

**Comment by jablko** [comment]
@nycdotnet :+1: I've revised the messages as you suggested, good call thanks!

I think the existing types are compatible with literals: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/529f809a1287323e7a233733804de1bee5ac1f94/types/big.js/test/big.js-import-default-tests.ts#L127-L130

Also I'm going to mark this "Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29864". Whether technically that issue was addressed by this PR or by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52610, either way I think it's resolved.

**Review by sandersn — APPROVED** [review]

**Review by nycdotnet — APPROVED** [review]
many thanks - nice work

**Comment by nycdotnet** [comment]
Ready to merge

**Pull request merged**
