### PR TITLE
update webpack-merge-and-include-globally to 2.3.4

### PR DESCRIPTION
**Pull request by michaellopez**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/markshapiro/webpack-merge-and-include-globally#separator>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I was unable to run `npm run test webpack-merge-and-include-globally` successfully. See the following output:
```sh
$ npm run test webpack-merge-and-include-globally

> definitely-typed@0.0.3 test <repo-path>/DefinitelyTyped
> dtslint types "webpack-merge-and-include-globally"

Error: Errors in typescript@4.4 for external dependencies:
../clean-css/index.d.ts(11,50): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../uglify-js/index.d.ts(9,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/CachedSource.d.ts(1,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/ConcatSource.d.ts(2,28): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/index.d.ts(1,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/OriginalSource.d.ts(2,28): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/Source.d.ts(2,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/SourceMapSource.d.ts(1,50): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack/v4/index.d.ts(46,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`

    at <repo-path>/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (<repo-path>/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test: `dtslint types "webpack-merge-and-include-globally"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the definitely-typed@0.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <home-dir>/.npm/_logs/2021-06-02T13_23_49_512Z-debug.log
```
Trying the suggestion in the error log did not help.

### CODE REVIEW

**Comment by michaellopez** [comment]
I would not mind adding tests for this, but I need advice/help on how to make the tests run as they error out locally for me (as shown above).

**Comment by peterblazejewicz** [comment]
Hi,
switch to types and then into relevant folders and:
```
uglify-js git:(pr/53553) 19:00 npm i --no-package-lock
webpack git:(pr/53553) 19:01 npm i --no-package-lock
❯❯ webpack git:(pr/53553) 19:01 cd .\v4\
❯❯ v4 git:(pr/53553) 19:01 npm i --no-package-lock
```
hth!

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by michaellopez** [comment]
I'll give the instructions from @peterblazejewicz a try first.

**Comment by michaellopez** [comment]
Sorry, after following the given instructions the closest I (think) I could get was:

```sh
$ npm run test webpack-merge-and-include-globally

> definitely-typed@0.0.3 test <repo-path>/DefinitelyTyped
> dtslint types "webpack-merge-and-include-globally"

Error: Errors in typescript@4.4 for external dependencies:
../webpack-sources/index.d.ts(7,23): error TS4090: Conflicting definitions for 'node' found at '<repo-path>/DefinitelyTyped/node_modules/@types/node/index.d.ts' and '<repo-path>/DefinitelyTyped/types/webpack/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
  The file is in the program because:
    Type library referenced via 'node' from file '<repo-path>/DefinitelyTyped/types/webpack/v4/index.d.ts' with packageId '@types/node/index.d.ts@15.9.0'
    Type library referenced via 'node' from file '<repo-path>/DefinitelyTyped/types/webpack-sources/index.d.ts' with packageId '@types/node/index.d.ts@14.17.2'
../webpack-sources/lib/CachedSource.d.ts(1,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/ConcatSource.d.ts(2,28): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/index.d.ts(1,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/OriginalSource.d.ts(2,28): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/Source.d.ts(2,30): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack-sources/lib/SourceMapSource.d.ts(1,50): error TS7016: Could not find a declaration file for module 'source-map'. '<repo-path>/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
../webpack/v4/index.d.ts(32,3): error TS2305: Module '"tapable"' has no exported member 'Tapable'.
../webpack/v4/index.d.ts(1062,23): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1063,22): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1064,28): error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1065,27): error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1066,27): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1067,21): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1068,27): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1070,30): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1071,24): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1080,33): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1081,27): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1082,37): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1083,44): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1084,47): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1085,28): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1086,30): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1087,24): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1088,25): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1089,34): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1090,25): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1091,31): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1092,36): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1093,35): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1094,34): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1095,40): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1096,33): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1097,36): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1098,38): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1099,36): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1100,28): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1101,25): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1102,27): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1103,25): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1104,29): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1105,23): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1106,32): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1107,22): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1108,29): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1109,38): error TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
../webpack/v4/index.d.ts(1110,48): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1111,44): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1112,26): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1121,28): error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1122,27): error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1123,33): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1124,27): error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1144,21): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1145,19): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1147,40): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1148,35): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1149,43): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1152,23): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1154,35): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1155,30): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1156,38): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1171,27): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1190,25): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1191,24): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1197,33): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1198,40): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1199,32): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1204,31): error TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1210,33): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1211,24): error TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1219,33): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1220,28): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1224,43): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1225,38): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1226,46): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1239,27): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1240,22): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1241,32): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1242,28): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1243,24): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1244,27): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1258,22): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1259,21): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1260,21): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1261,22): error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1262,19): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1356,25): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1358,29): error TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
../webpack/v4/index.d.ts(1374,25): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1375,26): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1376,31): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1379,26): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
../webpack/v4/index.d.ts(1399,25): error TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
../webpack/v4/index.d.ts(1466,24): error TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.

    at <repo-path>/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (<repo-path>/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test: `dtslint types "webpack-merge-and-include-globally"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <home-path>/.npm/_logs/2021-06-03T10_49_52_585Z-debug.log
```
I am unable to put down more time right now for these test. So I will go forward with the merge and hope that the test issues can be solved in another PR.

**Comment by michaellopez** [comment]
Ready to merge

**Pull request merged**
