### PR TITLE
Break up ts-activex into separate modules

### PR DESCRIPTION
**Pull request by ghost**
#11284 Currently the `ts-activex` directory isn't being published because it has no main file to publish. Since there is no obvious main file, I've broken it up into 3 separate modules.

This also involved removing the file `jscript-extensions.d.ts`, which came with the comment `These will become unnecessary with the next version of Typescript`. @zspitz, are these now unnecessary? I've renamed uses of `VarDate` to `Date`.

The idea of a `VarDate` appears to be documented [here](https://msdn.microsoft.com/en-us/library/4d4x3w61%28v=vs.84%29.aspx), so it may still be necessary.

Waiting on #11284

### CODE REVIEW

**Comment by zspitz** [comment]
@andy-ms There are many ActiveX libraries; these are just three that I generated using [this](https://github.com/zspitz/ts-activex-gen).

I originally asked about how to structure these libraries at #4018 and was told to put all the libraries in a single folder.

Regarding `VarDate`, it is not the same as Javascript's built-in `Date` object (see Microsoft/TypeScript#9392). But the change has already been merged into lib.d.ts, so there's no need for the `extensions.d.ts` file

Out of curiosity, what does #11824 have to do with this?

**Comment by zspitz** [comment]
On further consideration, the only reason to include these libraries is if there is something beyond what is auto-generated by parsing the ActiveX library -- jsdoc comments, or parameters narrowed to specific literals etc. This is currently not the case.

**Comment by zspitz** [comment]
@andy-ms Should the `.d.ts` files for all such libraries be prefixed with `ts-activex`? In the case of ActiveX Data Objects, the **ActiveX** is also part of the library name, and therefore strictly speaking the library should be named `ts-activex-activex-data-objects`.

OTOH, there is no need to have the name of the file strictly match the name of the library, as long as it is possible to find it from the header. There are very often accepted shortcut names:

- `ts-activex-data-objects` -> `ts-activex-ado`
- `ts-activex-windows-image-acquisition` -> `ts-activex-wia`
- `ts-activex-microsoft-scripting-runtime` -> `ts-activex-scripting-runtime`

2) There are shorter names that could be used: `ts-activex-data-objects`

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
