### PR TITLE
Add Grant methods on Auth0 ManagementClient

### PR DESCRIPTION
**Pull request by frederikprijck**
Closes #52655

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://auth0.com/docs/api/management/v2#!/Grants/

### CODE REVIEW

**Review by nhardy — APPROVED** [review]

**Comment by frederikprijck** [comment]
Ready to merge

**Comment by peterblazejewicz** [comment]
folks, just opinion, that IMO would be better style for this particular high visibility types:
```ts
management.getGrants({ user_id: 'user_id', client_id: 'client_id', audience: 'audience' }).then(
    grants =>
        // $ExpectType GrantResponse[]
        grants,
);
// $ExpectType Promise<ResponseGrant[]>
management.getGrants({ user_id: 'user_id', client_id: 'client_id', audience: 'audience' })
```
- test typical usage (implicit types in params, who type types for everything)
- prevents wrong cast (e.g. from `any`)
- do not use another dependency

**Comment by frederikprijck** [comment]
@peterblazejewicz Thanks, I wasn't aware we could use that, that looks very useful!

**Comment by frederikprijck** [comment]
Added a follow up PR to correct this, thanks!

**Pull request merged**
