### PR TITLE
Consolidate redundant Tooltipster typings & update to latest API

### PR DESCRIPTION
**Pull request by joeskeen**
Currently there are two typings for Tooltipster: tooltipster and jquery.tooltipster, but they both refer to the same project / package (see the project URL in the header of both; they match).

This consolidates the two typings into one and updates it to the latest API as documented at <http://iamceege.github.io/tooltipster>.  Also, tests were added from the examples found on the documentation page (as the use cases documented there are quite extensive).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://iamceege.github.io/tooltipster>
- [n/a] Increase the version number in the header if appropriate.
- [n/a] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [n/a] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [n/a] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by joeskeen** [comment]
Also including other authors @pjmagee, @VorobeY1326, @leonard-thieu and @janhi (authors of typing for jquery.tooltipster)

**Comment by leonard-thieu** [comment]
Not sure what proper procedure here is since it seems like the removed package should get a stub package published with a warning to switch. @andy-ms advice?

**Comment by stephenlautier** [comment]
👍

**Comment by andy-ms** [comment]
I've manually deprecated `@types/jquery.tooltipster`.

**Pull request merged**
