### PR TITLE
Update snowpack-env to fix bug introduced in last change

### PR DESCRIPTION
**Pull request by FredKSchott**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/snowpackjs/snowpack/discussions/1533 & https://github.com/microsoft/TypeScript/issues/41468
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by stramel — APPROVED** [review]

**Review by drwpow — APPROVED** [review]

**Comment by FredKSchott** [comment]
DT Team/Maintainers: this fixes an unexpected breaking change in the last types release (more info: snowpackjs/snowpack#1533). Snowpack starter templates are broken as a result.

Please merge and release as soon as possible!

**Comment by stramel** [comment]
Ready to merge

**Comment by Jack-Works** [comment]
Strange! If you use "if" to check if import.meta.hot exists, in the if block it should be usable! I suggest not change the definition file but change the starter template

**Comment by Jack-Works** [comment]
I'd like to see the issue in the starter template later (it's 4am now in my timezones). Please don't hurry to merge the inaccurate definition

**Review by Jack-Works — CHANGES_REQUESTED** [review]
Need investigation

**Comment by FredKSchott** [comment]
@Jack-Works we do use `if`, see: https://github.com/snowpackjs/snowpack/blob/master/create-snowpack-app/app-template-react-typescript/src/index.tsx#L15-L17

The root here is a TS bug around its handling of `ImportMeta`, but right now we're just trying to unblock the CSA templates that were broken by this fix. If you have a problem approving this then I'll revert this back to `any`, which also would fix the existing templates. 

change request noted, but If you're heading to bed please don't leave your review status as "requested changes" which might prevent us from merging a fix in while you're asleep. Again, all TypeScript Snowpack templates (existing and new) were broken by the the TS bug that the newest @types package currently triggers.

**Review by Jack-Works — APPROVED** [review]

**Comment by Jack-Works** [comment]
I'm sorry for blocking, but the bot said you can dismiss my change request. I'm okay with this merging and I'm going to find what's happening in TypeScript itself.

**Comment by Jack-Works** [comment]
The bot requiring test file to be changed otherwise it won't merge this.

> ❌ Only a DT maintainer can approve changes without tests

**Comment by FredKSchott** [comment]
Just filed an issue here: https://github.com/microsoft/TypeScript/issues/41468

**Comment by FredKSchott** [comment]
@Jack-Works np, added a comment to the definition file for future readers as well.

**Review by drwpow — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]

**Review by stramel — APPROVED** [review]

**Comment by FredKSchott** [comment]
@thegecko mind taking a look? A lot of projects broken by this, would love to get a fix out as soon as possible.

**Comment by Jack-Works** [comment]
@FredKSchott now it's blocking by lacking test as @typescript-bot said

> *   :x: Only a DT maintainer can approve changes [without tests](https://github.com/DefinitelyTyped/DefinitelyTyped#editing-tests-on-an-existing-package)

**Comment by FredKSchott** [comment]
There is not currently a way to test `ImportMeta` in DT. Not blocked, we just need a DT maintainer to come in and merge. 

@weswigham any chance you could take a look? Would love to unblock Snowpack projects.

**Comment by stramel** [comment]
@FredKSchott I think if you just make the DT bot _think_ that you modified the tests we should be able to automerge. Maybe just change some wording in the file?

**Comment by FredKSchott** [comment]
lets see :)

**Review by stramel — APPROVED** [review]

**Comment by FredKSchott** [comment]
Ready to merge

**Comment by FredKSchott** [comment]
@stramel thanks for the suggestion!

**Pull request merged**
