### PR TITLE
Nodemailer transport addverify

### PR DESCRIPTION
**Pull request by AmyJeanes**
Sources:

https://github.com/nodemailer/nodemailer-smtp-transport/blob/b7a24868bf0a9c355f20a570465ce17eb3c4921b/lib/smtp-transport.js#L171-L254

'Verify SMTP connection configuration' section on: https://github.com/nodemailer/nodemailer/blob/c4b4623a7f575bae8f4ed56c0df48c22beceb738/README.md

### CODE REVIEW

**Comment by rogierschouten** [comment]
@MattJeanes  it looks good please just fix the indentation and I will give a thumbs-up.

**Comment by MattJeanes** [comment]
@rogierschouten there you go! not sure why it was wrong looked fine in notepad++ :confused:

**Comment by rogierschouten** [comment]
@MattJeanes that happens to the best of us :)

**Comment by rogierschouten** [comment]
:+!:

**Comment by yuit** [comment]
@MattJeanes Thanks for the PR and @rogierschouten  thanks for help reviewing

**Pull request merged**
