### PR TITLE
inquirer - make sure methods don't conflict

### PR DESCRIPTION
**Pull request by DmitryEfimenko**

### CODE REVIEW

**Comment by zhengbli** [comment]
👍

**Comment by vvakame** [comment]
*inquirer/inquirer.d.ts*

to author (@tkQubo). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
conflict occured. could you resolve it?

**Comment by tkqubo** [comment]
:+1:

**Pull request merged**
