### PR TITLE
[react-relay] add hook types

### PR DESCRIPTION
**Pull request by renanmav**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://relay.dev/docs/en/experimental/api-reference
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by renanmav** [comment]
This PR is related with https://github.com/relay-tools/relay-compiler-language-typescript/pull/149

**Comment by alloy** [comment]
Great work @renanmav 🙌

**Comment by hegelstad** [comment]
These types now appear outdated. Latest version of relay-hooks doesn't have preloadQuery anymore: https://github.com/facebook/relay/blob/relay-experimental-release/packages/react-relay/hooks.js

**Comment by alloy** [comment]
@hegelstad PRs for these would be much appreciated :pray:

**Pull request merged**
