### PR TITLE
[raphael] Added bbox intersection and inside check methods

### PR DESCRIPTION
**Pull request by DreierF**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [isPointInside](https://github.com/DmitryBaranovskiy/raphael/blob/b5fdbdc9850827eb49622cd0bc81b26025f8128a/dev/raphael.core.js#L3705), [isPointInsideBBox](https://github.com/DmitryBaranovskiy/raphael/blob/b5fdbdc9850827eb49622cd0bc81b26025f8128a/dev/raphael.core.js#L1295), [isBBoxIntersect](https://github.com/DmitryBaranovskiy/raphael/blob/b5fdbdc9850827eb49622cd0bc81b26025f8128a/dev/raphael.core.js#L1310) 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DreierF** [comment]
Test pass locally. Seems to be some problem with the latest typescript@next as it expects another type than Typescript 4.1 in a code area I haven't even touched.

**Comment by DreierF** [comment]
@blutorange Thanks for your attempt.
The issue has been fixed meanwhile on master with 17e6d24387b31c7e4632f809ec7737dfe3632465
I rebased my changes and also took the x2/y2/cx/cy fields into account.

Please have another look.

**Review by blutorange — APPROVED** [review]
Thanks for the changes and great the tests got fixed. Looks good me now!

**Review by blutorange — APPROVED** [review]

**Comment by blutorange** [comment]
Ready to merge

**Pull request merged**
