### PR TITLE
amqplib: callback api definition and tests added

### PR DESCRIPTION
**Pull request by abreits**
Add the callback api definition to the node.js amqplib library (in addition to the promise based api)

### CODE REVIEW

**Comment by vvakame** [comment]
*amqplib/amqplib.d.ts*

to author(@mnahkies). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mnahkies** [comment]
Looks fine to me. Only thing I would say is that I think it would be better to pull the replies, options and message declarations into separate shared modules, perhaps something like "amqplib/replies", etc. 

This would reduce duplication making maintenance easier going forward.

**Comment by abreits** [comment]
I have updated amqplib.d.ts with what (I think) you suggested, is this what you meant?

**Comment by mnahkies** [comment]
Yeah that's what I meant, thanks

:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
