### PR TITLE
Change <extends object> into <extends Object>

### PR DESCRIPTION
**Pull request by mszlapa**
Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
`extends object` is correct. `extends Object` would accomplish nothing since everything extends `Object`.

**Comment by mszlapa** [comment]
Thank you for prompt response.

This is the problem we see when using TS 2.1.5 and  types/lodash  4.14.62

`<project directory>/node_modules/@types/lodash/index.d.ts
Error:(12847, 29) TS2304:Cannot find name 'object'.
Error:(19587, 15) TS2428:All declarations of 'WeakMap' must have identical type parameters.
Error:(19587, 33) TS2304:Cannot find name 'object'.`

I am unclear, what is a meaning of lowercase 'object' type.

**Comment by andy-ms** [comment]
You must be using an older version of TypeScript. Read about `object` [here](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#object-type).

**Comment by mszlapa** [comment]
OK thanks, I see 'object' was introduced in 2.2 which was only 2 months ago :).

We are using typescript 2.1.5 (released 4mth ago), we will see if we can upgrade our projects so we can benefit from @types/lodash

Thanks for getting back to me so quickly

**Comment by andy-ms** [comment]
You can also install `@types/lodash@ts2.1`, although it's not as up-to-date.

**Pull request closed without merging**
