### PR TITLE
update(mini-css-extract-plugin): v2.2 updates

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- No api shape changes
- Documentation updates (JSDocs)
- unified format using DT defaults

https://github.com/webpack-contrib/mini-css-extract-plugin/compare/v2.0.0...v2.2.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
hanging an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by JounQin** [comment]
? You've raised the same PR at #54182 and that has been merged before.

**Comment by 43081j** [comment]
yep, curious as to how he managed that if anything 😂 

this should be closed.

@peterblazejewicz do you automate some of these PRs? how are you aware of the updates to so many unrelated packages? would be useful to others to understand how you track them

**Comment by peterblazejewicz** [comment]
Hey, obvioiusly that's wrong. I believe I've used wrong branch on upstream. The intent was to create v2.2 updates (JSDocs changes). Sorry for the noise (or for what looked like a noise), folks. Let me update this

**Comment by peterblazejewicz** [comment]
The branche version was staled (old one), really sorry. But we have some fun :)

**Comment by 43081j** [comment]
@peterblazejewicz  Off topic: so what process do you use to track the changes in all these seemingly unrelated projects? Do you manually follow them all or have you found a way to automate monitoring version bumps? For those of us who also maintain a bunch of types, it'd be useful to know. 

Will give this a review in the morning

**Review by johnnyreilly — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
> Off topic: so what process do you use to track the changes in all these seemingly unrelated projects?

no fuss, just old fashioned, but focused notifications. Also we use some of those at the company with a large code base, so I'm following stuff we're using.

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
