### PR TITLE
yargs: Fix incorrect type propagation of argv options by commands

### PR DESCRIPTION
**Pull request by gerben-stavenga**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gerben-stavenga/DefinitelyTyped/blob/45d54334fa561a8a6c4e6575848417b7e65c8171/types/yargs/yargs-tests.ts#L1370
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by forivall** [comment]
@gerben-stavenga please take a look at the use case mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62150, and consider my draft patch in the comments.

**Comment by gerben-stavenga** [comment]
@forivall I'm not sure what you mean or how it relates to this issue. Currently one gets types deduced that are undefined at runtime, which tells me the type inference is incorrect. 

yargs.command(
  ["foo"],
  "foo",
  (yargs) => yargs.options("name",  {describe: "name", type: string, require: true}, 
  async (argv) => {})
.command(
  ["bar"],
  "bar",
  (yargs) => yargs,
  async (argv) => {
     const { name } = argv;   // name is deduced string but will be undefined
  })

IMO this cannot be considered correct. The type deduction must follow what yargs is actually parsing.

**Comment by forivall** [comment]
The $0 command is handled specially by yargs, iirc. See what the arguments are when you use it as the command.

**Comment by gerben-stavenga** [comment]
@forivall I ran a quick test and posted result in the thread linked. Conclusion is that the result of asyncParse is not statically typeable as the result depends on the command chosen which depends dynamically on the process.args.

**Comment by forivall** [comment]
we could do some advanced typing using the unions then.

**Comment by gerben-stavenga** [comment]
That seems logically but for me outside of the intention of the PR. I think this PR fixes a clear type inference bug but not with the purpose of adding new features. That would be a follow up

**Comment by forivall** [comment]
Yup, i agree, i was just making a quick response from a phone.

**Pull request merged**
