### PR TITLE
Correct 'recluster' to a CommonJS 'export ='-style declaration.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
FYI @dex4er

**Comment by dex4er** [comment]
@DanielRosenwasser so you put everything in `recluster` namespace like for APIs before TypeScript 2.7. Currently `dtslint` forced me to use `"esModuleInterop": true` so new syntax worked.

Should we do not use newer `import` syntax? `namespace` keyword is already obsoleted? Some of modules are now in new style, some of them are in old style. I'm puzzled.

**Comment by DanielRosenwasser** [comment]
If the original module is declared with `module.exports`, you should use an `export =`. Check out [this snippet from the README](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/fd3ea4d8d3e25b69d97351a11d4b2a15468e1e29#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default).

**Comment by dex4er** [comment]
Probably you might be right: https://github.com/Microsoft/TypeScript/issues/21535

so we still should use `export = xxx` and namespaces. It would be nice to see some clarification from DefinitelyTyped team. @andy-ms maybe?

**Review by dex4er — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by andy-ms** [comment]
(@DanielRosenwasser and I work on the same team.)

**Pull request merged**
