### PR TITLE
Rename algolia-search-client-js to algoliasearch and convert to module

### PR DESCRIPTION
**Pull request by ghost**
- [X] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

This declares the "algoliasearch" module, so it should be in a directory with that name.
If this is merged I will deprecate `@types/algoliasearch-client-js`.

Since dt-bot doesn't catch this for renames, CC @cbaptiste

### CODE REVIEW

**Comment by alexeagle** [comment]
I'm sorry, I did a bad force-push to the types-2.0 branch which I believe lost this merge commit.

**Comment by andy-ms** [comment]
For reference, this was redone in #12892

**Comment by CBaptiste** [comment]
Hello @andy-ms could you explain why this PR ? 
it is breaking a few things now :(, we cannot compile it as a globale module anymore

**Comment by andy-ms** [comment]
Can you be specific about what you are trying and what error messages you are getting? It doesn't look like this ever declared any global variables. It did define interfaces globally, though, which are now scoped to the "algoliasearch" module. You can access them like:

```ts
import algoliasearch = require("algoliasearch");
const x: algoliasearch.AlgoliaResponse = ...
```

**Pull request merged**
