### PR TITLE
[@types/react-scroll] add types for ScrollLink and ScrollElement

### PR DESCRIPTION
**Pull request by jmtoung**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/fisshy/react-scroll/blob/ee167423739ecc50d161ab61ac74bab0905d1c20/modules/mixins/scroll-element.js>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
Can you consider to close this in favor of #44493?
(if that one is accepted, it will impact other ones, including #44493). 
#44493 is a nice palce to obtain feedback (e.g about prettier and same topic change as here).
Thanks!

**Comment by jmtoung** [comment]
I don't understand your suggestion to close this one in favor of 44493. 44493 only includes 2 of the commits, whereas this one contains all 3. 

If anything we should just keep this one.

**Comment by peterblazejewicz** [comment]
@jmtoung yes, obviously. Sorry, I could be tricked by the different PRs (hence my question to decide which one should stand).

**Comment by jmtoung** [comment]
Ah, got it. Ok I will delete the other two PRs and leave this one. 

By the way, what are the next steps? Do we wait for maintainers to respond? What if they don't respond? I noticed the last person who updated these types hasn't had any activity for a at least few months...

**Review by SudoPlz — APPROVED** [review]

**Comment by SudoPlz** [comment]
Looks good to me.

**Comment by SudoPlz** [comment]
Ready to merge

**Comment by jmtoung** [comment]
Ready to merge

**Pull request merged**
