### PR TITLE
Updated backbone.marionette and tinymce

### PR DESCRIPTION
**Pull request by codemannz**
Updated backbone.marionette and tinymce

### CODE REVIEW

**Comment by codemannz** [comment]
Bump

**Comment by codemannz** [comment]
can someone review this please?

**Comment by codemannz** [comment]
Can someone review this please?

**Comment by martinduparc** [comment]
@zhamid @nvivo @sventschui please review

**Comment by codemannz** [comment]
@zhamid @nvivo @sventschui please review

**Comment by sventschui** [comment]
Please stop mentioning me. I stopped using these frameworks years ago and may not be a good reviewer anymore.

**Comment by codemannz** [comment]
Well can someone please review this.

**Comment by mhegazy** [comment]
Sorry for the delay, can you please rebase this PR.

**Comment by codemannz** [comment]
@mhegazy done

**Comment by siegerx3** [comment]
Is there any specific reason why you changed the definitions for tinymce?

Because you removed `declare var tinymce: TinyMce.Static;` and `tinymce`, when imported, no longer extends `EditorManager` it's missing for example the `remove` function which you definitely need.

**Pull request merged**
