### PR TITLE
Fixed MDPalette definition.

### PR DESCRIPTION
**Pull request by ghost**
The values should be a string array and contrastStrongLightColors should be contrastLightColors

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-material/angular-material.d.ts*

to author(@mtraynham). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mtraynham** [comment]
@robertbaker 
The property name change looks correct, but the type should be a union of `string|string[]`.

Palettes use simple strings here:
https://github.com/angular/material/blob/master/src/core/services/theming/theme.palette.js#L20

But code splits and converts it to an array:
https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L535

Ultimately, these properties get deleted from the palette, so they are only used at creation of the palette and not present in retrieval:
https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L538

**Comment by robertbaker** [comment]
Changed it.

**Comment by mtraynham** [comment]
LGTM thanks @robertbaker

**Comment by vvakame** [comment]
@mtraynham thanks!
@robertbaker thanks mate!

**Pull request merged**
