### PR TITLE
Update log4js's typings

### PR DESCRIPTION
**Pull request by kevin-smets**
Added log4js's replaceConsole and restoreConsole

### CODE REVIEW

**Comment by cw-okuno** [comment]
I have wrote only a small part of the first edition. Therefore, I cannot be determined.

@DanielRosenwasser How about you? Could you review this?

**Comment by armorik83** [comment]
I have wrote only a small part of the first edition. Therefore, I cannot be determined.

@DanielRosenwasser How about you? Could you review this?

**Comment by DanielRosenwasser** [comment]
[`restoreConsole` doesn't take a parameter](https://github.com/nomiddlename/log4js-node/blob/0fc65d38eb0210bbb2d5bf12b40d3588f7c318e2/lib/log4js.js#L369-L373), even optionally, so just fix that up.

**Comment by kevin-smets** [comment]
@DanielRosenwasser damn copy paste :/. Thanks for pointing it out, fixed it.

**Comment by DanielRosenwasser** [comment]
Nice - thanks! :+1:

**Pull request merged**
