### PR TITLE
[@types/imap-simple]: Add `deleteMessage` and `closeBox` function declaration

### PR DESCRIPTION
**Pull request by mHooshdar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by pushplay — CHANGES_REQUESTED** [review]
Please add a comment documenting `deleteMessage` as well as a test for it.

**Comment by mHooshdar** [comment]
> Please add a comment documenting `deleteMessage` as well as a test for it.

Done

**Comment by mHooshdar** [comment]
I also added `closeBox` function declaration in the `imap-simple` types. please review it too.

Thanks.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## imap-simple ([<kbd>unpkg</kbd>](https://unpkg.com/browse/imap-simple@latest/))
was missing the following properties:
1. parseHeader
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ba25333e2192a415ae0e292853af3e2dd28f8545
</p>

**Review by pushplay — CHANGES_REQUESTED** [review]
Thanks for adding the docs.  Both of these still need tests.  Copying the example from the docs will suffice.

`parseHeader` isn't in the docs so that can be ignored.

**Comment by mHooshdar** [comment]
> Thanks for adding the docs. Both of these still need tests. Copying the example from the docs will suffice.
> 
> `parseHeader` isn't in the docs so that can be ignored.

- Added 2 examples from the `imap-simple` package in the `imap-simple-tests.ts` file. 
- I didn't see anything about `parseHeader` in the `@types/imap-simple` so I don't know what danger-bot says.

I think the message uid in the `imap-simple` functions is a number but `imap-simple` documents said that it's a string.
So after this PR, I will fix that in their documents and open a PR for it then I will fix the `imap-simple` type files too.

Thanks again for reviewing my PR.

**Comment by pushplay** [comment]
Oh I see.  This shows up in `delFlags` and `addFlags` as well.  I'd rather not release a version of the types that are wrong even if it's just for a while.

https://github.com/mscdex/node-imap is pretty clear that Message.attributes.uid is a number.  I'm confident `uid` is a number and the example in the doc is correct.  I think the best thing to do is test with the original code and fix the types to have `uid` as a number.  Then submit a PR to imap-simple fixing the docs.

**Comment by mHooshdar** [comment]
> Oh I see. This shows up in `delFlags` and `addFlags` as well. I'd rather not release a version of the types that are wrong even if it's just for a while.
> 
> https://github.com/mscdex/node-imap is pretty clear that Message.attributes.uid is a number. I'm confident `uid` is a number and the example in the doc is correct. I think the best thing to do is test with the original code and fix the types to have `uid` as a number. Then submit a PR to imap-simple fixing the docs.

Ok then, I will change the `uid` strings to the number in this PR and then submit a PR for imap-simple

**Comment by mHooshdar** [comment]
I changed the `uid` to number, but I'm not pretty sure about the `source` and I think it can be number too (it has `any` type in the `@types/imap`).

**Review by pushplay — APPROVED** [review]
Thanks for your work on this.

I don't know about `sources` either.  I guess if someone discovers it's wrong they can let us know.

**Comment by mHooshdar** [comment]
Ready to merge

**Pull request merged**
