### PR TITLE
[echarts] Add real type of context

### LINKED ISSUE #50955: SeriesCustom.RenderItemParams.context defination is wrong
I am using echarts@5.0.1 and @types/echarts@4.9.3 in my project. 

In file node_modules\@types\echarts\options\series\custom.d.ts, the defination SeriesCustom.RenderItemParams.context?: **string | undefined** conflict with the real type of renderItem.params.context which is an **empty object**.

Is the @types/echarts@4.9.3 incompatible with echarts@5.0.1?

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #50955

Documentation: https://echarts.apache.org/en/option.html#series-custom.renderItem.arguments.params

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by orta** [comment]
This change does not seem to match the docs you linked:

>     context: // {string} An object that developers can store something temporarily here. Life cycle: current round of rendering.

**Comment by martin-badin** [comment]
> This change does not seem to match the docs you linked:
> 
> > ```
> > context: // {string} An object that developers can store something temporarily here. Life cycle: current round of rendering.
> > ```
Hi. It seems the description of the documentation is correct but the type in the documentation is wrong.

**Comment by orta** [comment]
Hah, we've all been there - OK 👍🏻

**Review by orta — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
