### PR TITLE
React-big-calendar: DnD - Changes allDay to isAllDay in drop/resize

### PR DESCRIPTION
**Pull request by lenehan2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. (N/A)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Example illustrates the property name is `isAllDay` and not `allDay` for event drop handler: [here](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js#L45).  onEventDrop and onEventResize are called with the same argument as seen [here](https://github.com/jquense/react-big-calendar/blob/611a0ce7ceeae05b0537d698573b0a667fdd24d6/src/addons/dragAndDrop/withDragAndDrop.js#L97).  
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (N/A)

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
How does the [linked source](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js#L45) relate to `onEventResize`? I can understand `onEventDrop` since `this.moveEvent` is assigned to it but not `onEventResize`.

**Comment by lenehan2** [comment]
@eps1lon Apologies if a direct ping is not proper etiquette here.  I've updated the original comment as well, but the `onEventResize` and `onEventDrop` handlers are both called with the same `interactionInfo` argument as shown [here](https://github.com/jquense/react-big-calendar/blob/611a0ce7ceeae05b0537d698573b0a667fdd24d6/src/addons/dragAndDrop/withDragAndDrop.js#L97).  I know this technically can be a different type, but during testing (modifying the onMouseResize event handler in the examples demo), `isAllDay` is passed in the event of an all day event for both handlers.  `allDay` is not passed at all.  There is a relevant issue [here](https://github.com/jquense/react-big-calendar/issues/1725)

**Review by eps1lon — APPROVED** [review]
> @eps1lon Apologies if a direct ping is not proper etiquette here. I've updated the original comment as well, but the `onEventResize` and `onEventDrop` handlers are both called with the same `interactionInfo` argument as shown [here](https://github.com/jquense/react-big-calendar/blob/611a0ce7ceeae05b0537d698573b0a667fdd24d6/src/addons/dragAndDrop/withDragAndDrop.js#L97). I know this technically can be a different type, but during testing (modifying the onMouseResize event handler in the examples demo), `isAllDay` is passed in the event of an all day event for both handlers. `allDay` is not passed at all. There is a relevant issue [here](https://github.com/jquense/react-big-calendar/issues/1725)

Awesome, thanks for clarifying 👍

**Comment by lenehan2** [comment]
Ready to merge

**Pull request merged**
