### PR TITLE
Added gorilla-engine

### PR DESCRIPTION
**Pull request by jhwoodward**
Represents shape of module/library.

### CODE REVIEW

**Comment by jakebailey** [comment]
You deleted the entire PR template so it's very difficult for me to review this. This isn't an npm package; what is it? What can we use to review this? Does this need to be on DefinitelyTyped?

**Review by jakebailey — CHANGES_REQUESTED** [review]
You deleted the entire PR template so it's very difficult for me to review this. This isn't an npm package; what is it? What can we use to review this? Does this need to be on DefinitelyTyped?

**Comment by jhwoodward** [comment]
According to the instructions, I deleted the parts of the template that are not relevant. 
Gorilla Engine is a NodeJS toolkit for building audio plugins in JavaScript (please see https://gorilla-engine.com/)
It would be great to have the type definitions on DefinitelyTyped so that developers can opt to use TypeScript with the platform.

**Review by jakebailey — APPROVED** [review]

**Comment by jhwoodward** [comment]
Ready to merge

**Pull request merged**
