### PR TITLE
Go back to old style of React typings and merge in JSX to both

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Improves on the previous PR:
- Re-split the .d.ts files back in to a module version and a namespace version
- Add JSX support to both

This slightly pollutes the global namespace with a `__React` identifier in the module version, but I think this is preferable to rewriting the entire .d.ts file in a different way.

Thanks @vsiao and @jbrantly for feedback on the prior revision

### CODE REVIEW

**Comment by jbrantly** [comment]
+1 to merge

The `__React` identifier pollution is unfortunate but works. Good solution.

**Comment by vvakame** [comment]
@vsiao @pspeter3 can I merge this PR?

**Comment by pspeter3** [comment]
Looks good to me. I agree with @jbrantly about the `__React` solution but it looks like the best option for the situation.

**Comment by vvakame** [comment]
@jbrantly @pspeter3 thanks!
@RyanCavanaugh thanks mate! it merged.

**Comment by joewood** [comment]
Will this change be applied to react-addons too?

**Comment by jbrantly** [comment]
@joewood You're right, that probably should be looked at. In the meantime, just reference both react.d.ts and react-addons.d.ts and you should be good.

**Pull request merged**
