### PR TITLE
[numeral] Add `numeral.formats` type definition

### PR DESCRIPTION
**Pull request by SBoudrias**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/adamwdraper/Numeral-js/blob/master/src/numeral.js#L413
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (same version, not new)

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/runs/3636628481#step:6:88
related type is missing

**Comment by SBoudrias** [comment]
I think I got everything right this time.

I changed some namespace from `NumeralJs` to `NumeralJS` to keep it consistent (caps JS was the most common one in the current type-def file)

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@SBoudrias thx!

**Comment by SBoudrias** [comment]
Ready to merge

**Pull request merged**
