### PR TITLE
Add Ej typescripts.

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
What is the approximate time takes to merge the pull request into the repo after all the checks have passed? I cant find this info anywhere in the contribution guide. Or why this pull request has not been merged yet?

**Comment by vvakame** [comment]
http://help.syncfusion.com/js/installation-and-deployment
`bower install syncfusion-javascript`

please rename `ej.mobile.all/ej.mobile.all.d.ts` to `syncfusion-javascript/syncfusion-javascript.d.ts` and others.

**Comment by Syncfusion-JavaScript** [comment]
@vvakame We have three files named `ej.mobile.all.d.ts, ej.web.all.ts and ej.widgets.all.ts.` How can we include these three files into three different named directories or a single directories?

**Comment by vvakame** [comment]
I think single directory is better.

**Comment by mathikp** [comment]
As per the [contribution guide](http://definitelytyped.org/guides/contributing.html), 

1. **the definition file should be single and should placed in a folder as same as the library name.** Then how is it possible to place all the three files into one directory?

2. **If the library is published to multiple package managers (npm, bower, yam, NuGet, component etc) but under different names then also use the npm name.** But, we haven't published our library in any of the above package manager. Then why should we need to rename the files?

**Comment by Syncfusion-JavaScript** [comment]
As per the [contribution guide](http://definitelytyped.org/guides/contributing.html),

1. **The definition file should be single and should placed in a folder as same as the library name.** Then how is it possible to place all the three files into one directory?
2. **If the library is published to multiple package managers (npm, bower, yam, NuGet, component etc) but under different names then also use the npm name.** But, we haven't published our library in any of the above package manager. Then why should we need to rename the files?

**Comment by vvakame** [comment]
> Then how is it possible to place all the three files into one directory?

yes.

> But, we haven't published our library in any of the above package manager.

Oh, really?
Is this not target package?
```
$ bower info syncfusion-javascript
bower syncfusion-javascript#*       not-cached https://github.com/syncfusion/essentialjs-bower.git#*
bower syncfusion-javascript#*          resolve https://github.com/syncfusion/essentialjs-bower.git#*
...
```

**Comment by Syncfusion-JavaScript** [comment]
@vvakame No, that is not the packages which contains our definition files.

**Comment by Syncfusion-JavaScript** [comment]
Hi @vvakame Our pull request is waiting nearly 15 days. Please guide me in how can I proceed further.

**Comment by vvakame** [comment]
please exec `mv ej.mobile.all/* ej.widgets.all/* ej.web.all`.

**Comment by Syncfusion-JavaScript** [comment]
@vvakame Could you please explain me clearly?

**Comment by Syncfusion-JavaScript** [comment]
@vvakame You are saying to move all the three files into a single directory, right? In the [contribution guide](http://definitelytyped.org/guides/contributing.html), you guided to have single folder and single file.

sshot-1

Then is it okay to have the three definition files and their tests files in single folder? If yes, shall we have the three files in the folder named "ej.widgets.all"?

**Comment by vvakame** [comment]
> Then is it okay to have the three definition files and their tests files in single folder?

yes.
your three definitions has same header.
`// Project: http://help.syncfusion.com/js/typescript`.

> shall we have the three files in the folder named "ej.widgets.all"?

yes, you can choose name.

**Comment by Syncfusion-JavaScript** [comment]
@vvakame I have made the changes as you suggested. Please take a look.

**Comment by vvakame** [comment]
👍

**Pull request merged**
