### PR TITLE
Add support for react-router and react-router-dom v6

### PR DESCRIPTION
**Pull request by murbanowicz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reacttraining.com/blog/react-router-v6-pre/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

MESSAGE:
This is first step to provide support for `react-router` and `react-router-dom` v6 with TypeScript.
Until the maintainers figure out the way how they want to develop TS support further, it would be really nice to have `@types/react-router-dom` available.
I did not provide typings for new version of lib (corrected or added new, but not new version), so please feel free to lead me if I should change it in some way to e.g. not break v5 etc or obviously feel free to edit etc.

What have I done:
- removed obsolete: `Redirect`, `Switch`, `useHistory`
- added: `Routes`, `useNavigation`
- changed: `component/children -> element` in props

### CODE REVIEW

**Comment by murbanowicz** [comment]
I would appreciate some help to make dependencies work. I suppose I have to somehow make v6 as a separate version, but I have no idea how?

**Comment by eps1lon** [comment]
> I would appreciate some help to make dependencies work. I suppose I have to somehow make v6 as a separate version, but I have no idea how?

Have you read https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package? This should explain how to go about it.

**Comment by murbanowicz** [comment]
@eps1lon - haven't found it previously. Thanks, it should help. I will look into that tomorrow, unless someone will help earlier.

**Comment by murbanowicz** [comment]
@eps1lon Could you take a look? I have done all (as far as I understand) up to docs regarding braking changes but I still have this error and I cannot fix it in any way:
```
5> react-router/v5 failing:
5> Error: Errors in typescript@3.9 for external dependencies:
5> ../../react-router-dom/index.d.ts(26,5): error TS2724: Module '"../react-router/v5"' has no exported member 'Routes'. Did you mean 'Route'?
5> ../../react-router-dom/index.d.ts(27,5): error TS2724: Module '"../react-router/v5"' has no exported member 'RoutesProps'. Did you mean 'RouteProps'?
5> ../../react-router-dom/index.d.ts(34,5): error TS2305: Module '"../react-router/v5"' has no exported member 'useNavigate'.
```

**Comment by JeffBaumgardt** [comment]
FYI, types were added to dev directly in `React-Router`. The V6 types can be found in `6.0.0-alpha.4` or `npm install react-router@next`

**Pull request closed without merging**
