### PR TITLE
[react] Replace {} by ReactElement in ReactFragment definition

### LINKED ISSUE #29307: Type of React.ReactFragment, which includes {}, breaks certain usages of children in TS 3.1
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly 
  - (Note: it's really hard to mention any author since none of them have github tags in the `index.d.ts`)

The type of `ReactFragment` currently includes `{}`, which causes the new, safer handling of `typeof x === 'function'` to only narrow `x` to `Function`.

[Sample playground link](http://www.typescriptlang.org/play/#src=namespace%20React%20%7B%0D%0A%20%20type%20ReactChild%20%3D%20ReactElement%3Cany%3E%20%7C%20string%20%7C%20number%0D%0A%0D%0A%20%20interface%20ReactNodeArray%20extends%20Array%3CReactNode%3E%20%7B%7D%0D%0A%20%20type%20ReactFragment%20%3D%20%7B%7D%20%7C%20ReactNodeArray%0D%0A%20%20export%20type%20ReactNode%20%3D%20ReactChild%20%7C%20ReactFragment%20%7C%20ReactPortal%20%7C%20string%20%7C%20number%20%7C%20boolean%20%7C%20null%20%7C%20undefined%0D%0A%0D%0A%20%20interface%20ReactPortal%20extends%20ReactElement%3Cany%3E%20%7B%20%7D%0D%0A%0D%0A%20%20interface%20ReactElement%3CP%3E%20%7B%0D%0A%20%20%20%20type%3A%20any%3B%0D%0A%20%20%20%20props%3A%20P%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Props%20%7B%0D%0A%20%20children%3A%20React.ReactNode%20%7C%20(()%20%3D%3E%20React.ReactNode)%0D%0A%7D%0D%0A%0D%0Afunction%20Component(props%3A%20Props)%20%7B%0D%0A%20%20return%20typeof%20props.children%20%3D%3D%3D%20'function'%20%3F%20props.children()%20%3A%20props.children%0D%0A%7D%0D%0A)

This same code would work as intended in TS 3.0.

I don't know why an empty object is considered a valid fragment; this allows literally `any`thing to be passed as a child as long as it's not "fresh".

### PR DESCRIPTION
**Pull request by cshaa**
fixes #29307, possibly a breaking change

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Babel link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIogE6pQhlIA8AfABIZaIDucZ6AJgIS0B6egG4iAXyJA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.3.3). It's clear from here that fragments are just React Elements of the React.Fragment component.
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ferdaber** [comment]
@jessidhia I forgot, what was the blocker for removing this other than the high amount of breakage this causes?

**Comment by m93a** [comment]
Oh, it's probably failing because many packages pass functions or custom objects as children. This shouldn't have anything to do with Fragments, however. Maybe adding `| object` to the ReactNode type would be a good idea?

**Comment by m93a** [comment]
I've looked at the errors in Travis. Most of them seem unrelated to the PR 🤔. Could you please help me out with this?

**Comment by ferdaber** [comment]
A lot of those are from untouched dependencies that haven't been retested since newer versions of TS, but the recompose ones look interesting, did you take a look at those?

**Pull request closed without merging**
