### PR TITLE
mongodb.d.ts fixes to enable Promise and async-await scenarios

### PR DESCRIPTION
**Pull request by davetemplin**
Various fixes to enable Promise and async-await scenarios...
- Db.command: fix incorrect function overload signature
- Collection.aggregate: fix incorrect function overload signature
- Collection.find: add missing overload signature
- Collection.findOne: add missing interface function
- Collection.initializeOrderedBulkOp: correct type of option parameter
- Collection.initializeUnorderedBulkOp: correct type of option parameter
- Collection.insert: add missing interface function
- Collection.update: add missing interface function
- OrderedBulkOperation.execute: fix incorrect function overload signature
- UnorderedBulkOperation.execute: fix incorrect function overload signature

Fix spelling errors: CollectionAggrigationOptions -> CollectionAggregationOptions

### CODE REVIEW

**Comment by CaselIT** [comment]
The options in `initializeOrderedBulkOp` and `initializeUnorderedBulkOp` were correct before according to the documentation [here](http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#initializeOrderedBulkOp) and [here](http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#initializeUnorderedBulkOp). I agree that they should be optional.
[I've asked about the missing documentation for the other find options](https://jira.mongodb.org/browse/NODE-625). I think we should limit to the documented signature.
`insert`, `update` and `findOne` where left out on purpose since they are deprecated.

**Comment by davetemplin** [comment]
Totally understand the motive to omit legacy functions, but here's an argument to consider keeping them...

Omitting a legacy declaration prevents users from targeting a down-level (pre-3.2) mongodb instance that doesn't yet support the new interface. If the driver still exposes the interface (which it does), then so should the typing.

Arguably an ideal way to deal with this situation would be if the TypeScript compiler had a way to [flag obsolete declarations](https://github.com/Microsoft/TypeScript/issues/2900). But since we don't have that feature yet, my suggestion would be to keep legacy declarations and perhaps comment them as _//obsolete_ in the code.

**Comment by CaselIT** [comment]
> Omitting a legacy declaration prevents users from targeting a down-level (pre-3.2) mongodb instance that doesn't yet support the new interface.
I guess you have a point here.

**Comment by CaselIT** [comment]
@davetemplin I've updated the definition with the deprecated method you suggested for typings. If you use it you can install them with `typings i mongodb`

**Comment by davetemplin** [comment]
Thank you for making these updates. Great to see the legacy functions reintroduced but flagged as deprecated. However, a few other important details unfortunately got lost in the translation...

SUMMARY:

1. For **Collection.aggregate** the return-type of "void|AggregationCursor" prevents applying cursor functions (such as toArray) without explicit casts.

2. The secondary **Collection.find** overload was not added thus preventing projecting, skipping, limiting, and timeout functions.

3. The **Db.command** function does not return a Promise if options is passed, which prevents accessing the result.

4. The options argument on **initializeOrderedBulkOp** and **initializeUnorderedBulkOp** should be optional. 



DETAILS:

__1. For Collection.aggregate the return-type of "void|AggregationCursor" prevents applying cursor functions (such as toArray) without explicit casts.__

For example we should be able to write a simple aggregate statement like the following...

EXAMPLE: ```var documents = await db.collection('test').aggregate([{$match:{name:"foo"}}]).toArray();```
ERROR: Supplied parameters do not match any signature of call target. (options should be optional)
ERROR: Property 'toArray' does not exists on type 'void | AggregationCursor'. (return type should just be AggregationCursor instead)

Suggest in this case not trying to represent the void return type at all. Perhaps anyone who passes a callback isn't going to care about the return type anyway.


__2. The secondary Collection.find overload was not added and prevents projecting, skipping and limiting.__

EXAMPLE: ```var result = await db.collection('test').find({name:"foo"}, {_name:1}, 0, 10);```
ERROR: Supplied parameters do not match any signature of call target. (project, skip, limit should be defined parameters)

__3. The Db.command function does not return a Promise if options is passed, which prevents accessing the result.__

EXAMPLE: ```var result = await db.command({ping:1});```
ERROR: result is a void type but should be any type instead.


__4. The options argument initializeOrderedBulkOp and initializeUnorderedBulkOp should be optional.__

EXAMPLE: ```var bulk = db.collection('test').initializeUnorderedBulkOp();```
ERROR: Supplied parameters do not match any signature of call target. (options should be optional)

SUGGESTED CHANGES:
Once again here are the suggested definitions to resolve all of the issues outlined above...

for Db ...
```
command(command: Object, callback: MongoCallback<any>): void;
command(command: Object, options?: { readPreference: ReadPreference | string }, callback?: MongoCallback<any>): Promise<any>;
```

*Please note the callback must not be optional in the first declaration, otherwise it becomes ambiguous with the second declaration (masking out the promise since it is defined first). Again, suggest not worrying about the void case as above.*

for Collection ...
```
aggregate(pipeline: Object[], options?: CollectionAggregationOptions, callback?: MongoCallback<any>): AggregationCursor;
find(query: Object, fields?: any, skip?: number, limit?: number, timeout?: number): Cursor;
```

for OrderedBulkOperation and UnorderedBulkOperation ...
```
execute(options?: FSyncOptions, callback?: MongoCallback<BulkWriteResult>): Promise<BulkWriteResult>;
```

I appreciate there are a lot of scenarios and subtleties here and it's really tough to validate them all. But these additional changes if made should make mongodb work really well with async-await!

**Comment by CaselIT** [comment]
@davetemplin I've added the updates you suggested, could you check them here https://github.com/Think7/typings-mongodb/commit/deed273d8ada73ea12e29d632baf0b22aec3db8c ? Thanks for them.

Regarding the `find` method in the `collection`, the mongodb team suggested to use the cursor [here](https://jira.mongodb.org/browse/NODE-625). But maybe we could add the legacy signature with a deprecated annotation. What do you think?

**Comment by davetemplin** [comment]
The changes on Think7 look good, thanks!! By the way I also just now noticed ```Collection.save``` is missing.

Regarding the ```find``` method I've observed performance issues on pre-3.0 instances where using cursor functions such as ```find({}).limit(1000)``` do not perform well when a theoretically equivalent legacy query like ```find({},null,null,1000)``` is instantaneous. So yes I think keeping the legacy signature with a deprecation warning as you suggest is definitely the way to go.

**Comment by CaselIT** [comment]
Added the missing signatures https://github.com/Think7/typings-mongodb/commit/1061602e147ad58973dfb78f5ce5424f673eb05f
Should be available with typings as soon as the registry pull request is merged

**Comment by davetemplin** [comment]
Splendid, thanks!
Will the [master](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mongodb/mongodb.d.ts) copy on GitHub be updated as well?

...would like to these changes have the broadest possible reach--so folks still using tsd or grabbing directly from GitHub directly will get these changes.

**Comment by CaselIT** [comment]
You could update this pull request with a new push, else I can do a new pr with the new updates.

**Comment by davetemplin** [comment]
New pull request submitted. One last thing we didn't catch before was on ```Collection.aggregate``` the options and callback parameters were not marked as optional.

**Comment by CaselIT** [comment]
@davetemplin There is always something! :smile:  I'll fix that.
I've commented the other pr. Thanks for the help :)

**Pull request closed without merging**
