### PR TITLE
Add XDate Type definition

### PR DESCRIPTION
**Pull request by yamada28go**
I was make the XDate(*1) library type definition file .
I would like to marge this type definition file.
I ask you to give this matter your consideration.

*1 : http://arshaw.com/xdate/

### CODE REVIEW

**Comment by vvakame** [comment]
*xdate/xdate.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/xdate
  * http://bower.io/search/?q=xdate
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (xdate/xdate-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@yamada28go thank you for your contributions.
please rename xdate/xdate-test.ts to xdate/xdate-tests.ts

**Comment by yamada28go** [comment]
thank you for checking.
I was renamed  xdate/xdate-test.ts to xdate/xdate-tests.ts.

**Comment by vvakame** [comment]
@yamada28go thanks mate!

**Pull request merged**
