### PR TITLE
Update multer declaration

### PR DESCRIPTION
**Pull request by vilicvane**

### CODE REVIEW

**Comment by vilic** [comment]
According to Express documentation:

> In Express 4, req.files is no longer available on the req object by default. To access uploaded files on the req.files object, use a multipart-handling middleware like busboy, multer, formidable, multiparty, connect-multiparty, or pez.

`files` property should now be extended instead of being there by default. (Most importantly, being there is overriding the extended one. XD)

**Comment by vvakame** [comment]
*express/express.d.ts*

to author(@borisyankov). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*multer/multer.d.ts*

to author(@jt000). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vilic** [comment]
So, any progress?

**Comment by vvakame** [comment]
@vilic sorry, It merged!

**Pull request merged**
