### PR TITLE
Add delimiterLazyShow to CleaveOptions

### PR DESCRIPTION
**Pull request by dadapowell**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by dadapowell** [comment]
Did not need to edit tests or use `dts-gen` because I only added a single property to the CleaveOptions interface.

**Comment by sashashakun** [comment]
@dadapowell could you please share link to library source code/docs, where this property was added? So we will understand that why did you decide to add this type. Thank you.

**Comment by dadapowell** [comment]
@sashashakun Sure.

Here, it is defined in the Cleave class properties: https://github.com/nosir/cleave.js/blob/master/src/Cleave.js
(line 316)

 You can see it in use in the examples here: https://jsfiddle.net/nosir/aLnhdf3z/
(line 66 in the js file).

**Comment by sashashakun** [comment]
whooops, seems like I am unable to approve already 😞

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
