### PR TITLE
[node] adds missing ReadableStream.from constructor

### PR DESCRIPTION
**Pull request by jquagliatini**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [nodejs documentation (since v20.6.0)](https://nodejs.org/docs/latest-v20.x/api/webstreams.html#readablestreamfromiterable)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/stream.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 145eef35db0864947aa6b787a7bdf241d25135a2
</p>

**Review by Semigradsky — CHANGES_REQUESTED** [review]
Please add changes to `types/node/ts4.8` folder too

**Comment by jquagliatini** [comment]
@Semigradsky, I updated the ts 4.8 types as requested. What do you think about it?

**Comment by jakebailey** [comment]
I deleted ts4.8 in #68908, you'll have to update the PR again (sorry!)

**Comment by jakebailey** [comment]
I deleted ts4.8 in #68908, you'll have to update the PR again (sorry!)

**Review by Semigradsky — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@jquagliatini thanks!

**Comment by jquagliatini** [comment]
Ready to merge

**Pull request merged**
