### PR TITLE
Add typing for node and mark keys of prosemirror Schema in all prosemirror-* packages

### PR DESCRIPTION
**Pull request by patsimm**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
New usage:
```
const nodes = {
  blockquote,
  doc,
  hardBreak,
  heading,
  paragraph,
  text
}

const marks = {
  em
}

const schemaSpec: SchemaSpec<keyof typeof nodes, keyof typeof marks> = {
  marks,
  nodes
}

const schema = new Schema(schemaSpec)
```
Then this is possible:
screen shot 2018-04-17 at 13 24 22
screen shot 2018-04-17 at 13 23 41

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by timjb** [comment]
@patsimm Did you notice the comment

```
// IMPORTANT
// This file was generated by https://github.com/bradleyayers/getdocs2ts. Please do not edit manually.
// When you find an error in these declarations, fix the getdocs comment upstream or 'getdocs2ts', then regenerate.
```

at the top of the files you edited? Apparently you edited the type definitions manually in spite of this comment. This means that in the future, we won't be able to use the the tool mentioned in the comment to update the type definitions for future versions of ProseMirror, but will instead have to edit them manually to preserve your changes. Maybe this is not such a big deal, since ProseMirror's API is not changing as fast as it used to. But I would like to make sure that if we go this route, we do so by choice, not by accident.

@bradleyayers What are your thoughts on this?

**Comment by patsimm** [comment]
@timjb Yes I stumbled over this comment. But I am not quite sure if it would be possible to extract those typings by only parsing the prosemirror docs. In the docs [schema.nodes](https://prosemirror.net/docs/ref/#model.Schema.nodes) for example are defined as `nodes: Object<NodeType>`. By only parsing this you would not be able to build the connection between the this Object's keys and the Schema-constructor's parameters.

**Comment by bradleyayers** [comment]
I'm happy to switch over to manually maintaining them (rather than auto-generating them) for a few reasons:

- ProseMirror APIs have stabilised since 1.0, so manually keeping the TS declarations in sync seems like a similar amount of effort to running and maintaining the getdocs2ts tool.
- Having extra contributors is great and helps the community, and @patsimm appears to be very enthusiastic.
- The extra fidelity in the types should improve the consumer dev experience.

However I would suggest the comment blocks saying "don't manually edit, use getdocs2ts" should be deleted else it will just be confusing.

**Comment by davidka** [comment]
If I remember correctly, we have already merged a couple of manually changes.

@patsimm great job!

**Comment by patsimm** [comment]
Ok guys, I removed the comments and fixed all the indentation changes that I accidentally pushed.

Also I pushed a slight [change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25061/commits/c36c178093fefbb31cc655930d99fe7d740c22b3) which restores the ablility to access a typed Schema's nodes and marks via a string-key. This makes it possible to do things like `const doc = 'doc'; schema.nodes[doc]` in addition to `schema.nodes.doc`

**Comment by patsimm** [comment]
I think I still need to do a small change. I'm quite new to writing those typings and theres a small issue I still would like to change because working with or migrating to the changes I made is a bit of a pain. I will explain in a bit more detail later, just don't accept the PR yet ;)

**Comment by patsimm** [comment]
I was using the generic type definition `<S extends Schema = Schema>` a lot of times. For example the NodeType class was being defined like that:
```
export class NodeType<S extends Schema = Schema> { ... }
```
When in my code I used the NodeType for an exported variable/function and not providing any generic type argument I would get a typescript error saying that the exported variable/function is using a type `Schema` from an external module. 

I solved this issue by using `<S extends Schema = any>` instead. Now code like `export const nodeType: NodeType = ...` works again without having to import `Schema`.

**Comment by patsimm** [comment]
@bradleyayers Are you ok with those changes? I think this could be merged now.

**Review by bradleyayers — APPROVED** [review]

**Comment by bradleyayers** [comment]
@patsimm go for it!

**Comment by RyanCavanaugh** [comment]
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

**Pull request merged**
