### PR TITLE
Update which to v3

### PR DESCRIPTION
**Pull request by jakebailey**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/npm/node-which/blob/main/CHANGELOG.md#300-2022-11-01
	- All that changed is that the callback forms of the API have been removed, leaving only async functions.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
Thanks!

**Comment by jakebailey** [comment]
Ready to merge

**Comment by mjossdev** [comment]
Looks like the async functions should have a Promise<string|null> overload if the nothrow option is set to true:
https://github.com/npm/node-which/blob/main/lib/index.js#L72

**Comment by jakebailey** [comment]
You should send a PR or make a discussion thread; an old PR is not the right place for this.

**Pull request merged**
