### PR TITLE
Add undefined to optional properties, Node

### PR DESCRIPTION
**Pull request by sandersn**
In preparation for exactOptionalPropertyTypes in Typescript 4.4, add undefined to all optional properties. #no-publishing-comment

This PR covers node.
microsoft/dtslint#335

### CODE REVIEW

**Review by SimonSchick — CHANGES_REQUESTED** [review]
There appear to be unrelated changes in this, please make sure to rebase.

**Comment by SimonSchick** [comment]
I haven't kept close tabs on this feature/proposal but this seems rather.. bloaty, have there be any considerations to potentially add something like `property??: Type`?

**Comment by sandersn** [comment]
> There appear to be unrelated changes in this, please make sure to rebase.

You're right! It's easier to run the whole process over.

> I haven't kept close tabs on this feature/proposal but this seems rather.. bloaty, have there be any considerations to potentially add something like property??: Type?

No, it's opt-in, and those features are allowed to be more onerous to use. Typical use will *not* include `| undefined` half of the time anyway, it's just needed for backward compatibility. I expect to see follow-up PRs in react, especially, removing the `| undefined` because that's their semantics.

**Comment by sandersn** [comment]
It was easier for me to create a new PR after bringing my clone up to HEAD: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54342

**Comment by sandersn** [comment]
wwwqwqw

**Pull request closed without merging**
