### PR TITLE
@chromecast-caf-receiver - Update LoggerLevel to ENUM

### PR DESCRIPTION
**Pull request by felipe-silva-devtech**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.html#.LoggerLevel

OBS: In the documentation the numbers are not mentioned, but it says that the type is numeric. Typing "cast.framework.LoggerLevel" in the console can be proved.

### CODE REVIEW

**Review by craigrbruce — CHANGES_REQUESTED** [review]
The right side should be numerical here, not strings.

it would also be nice if they were in order :)

```
enum LoggerLevel {
  DEBUG: 0,
  VERBOSE: 500,
  INFO: 800,
  WARNING: 900,
  ERROR: 1000,
  NONE: 1500
}
```

**Comment by felipedkalves** [comment]
@craigrbruce Thanks for review. Changed.

**Review by craigrbruce — APPROVED** [review]
Awesome, thanks @felipedkalves

**Comment by felipedkalves** [comment]
Someone know why pipeline is falling?

**Comment by jessetrinity** [comment]
Looks like it was probably transient

**Pull request merged**
