### PR TITLE
node: add ChildProcess killed property, add Worker send callback argument and fix some error events.

### PR DESCRIPTION
**Pull request by mgroenhoff**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: see links below
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Changes:
- [Added ChildProcess killed property](https://nodejs.org/api/child_process.html#child_process_subprocess_killed)
- [Added callback property to cluster.Worker send method](https://nodejs.org/api/cluster.html#cluster_worker_send_message_sendhandle_callback)
- Fixed error event arguments for [cluster.Worker](https://nodejs.org/api/cluster.html#cluster_event_error) and [fs.FSWatcher](https://nodejs.org/api/fs.html#fs_event_error)

### CODE REVIEW

**Comment by wwwy3y3** [comment]
LGTM 👍

**Comment by mgroenhoff** [comment]
Those are some weird errors. The same errors seem to appear in #19121, #18766 and recent PR's that change node's typings

**Comment by wwwy3y3** [comment]
@andy-ms Are these error related to strict generic checks you mentioned here (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19069) ?

**Comment by andy-ms** [comment]
I'll fix the tests in other PRs, thanks!

**Pull request merged**
