### PR TITLE
[@types/lingui__core]: Add number and date into i18n type

### PR DESCRIPTION
**Pull request by igorDolzh**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [definition in the source code](https://github.com/lingui/js-lingui/blob/master/packages/core/src/i18n.js#L68)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by huan086 — COMMENTED** [review]
These methods do not exists on the i18n object at runtime. You should be importing from lingui/macro

**Comment by huan086** [comment]
You are doing it wrong. Follow the tutorial https://lingui.js.org/tutorials/react.html. Import from lingui macro e.g. `import { Trans } from '@lingui/macro'`

**Comment by igorDolzh** [comment]
Thanks for your guidance, but read this.
I tried this method first https://lingui.js.org/ref/macro.html#number for numbers
```
i18n._(t`There were ${number(10000)} people.`)
``` 
returns `There were [object Object] people. `

If I try without `t`
```
i18._(number(amount))
```
returns `amount,number,number0`

Also, I found this issue opened, people facing the same problem with `date` and `number` https://github.com/lingui/js-lingui/issues/560

Then, I was searching for other options to use "number", and `i18n.number` works as expected. It returns a string with the value.
And as you could see here https://github.com/lingui/js-lingui/blob/master/packages/core/src/i18n.js#L68, `number` and `date` are inside I18n. That's why I think it should be included in types as well.

Of course, `number` and `date` from `macro` should be fixed as well, but not here :)

If you know what I'm doing wrong, and how I could fix it, you will be a savior!)

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
please handle feedback already given

**Comment by igorDolzh** [comment]
It is sad, that no discussion happened here. But apparently, my solution is controversial. I close the PR. I will try to fix `lingui/macro` instead.

**Pull request closed without merging**
