### PR TITLE
[React]Change return type of stateless component

### PR DESCRIPTION
**Pull request by Ailrun**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactjs.org/blog/2017/09/26/react-v16.0.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@Ailrun Please fix the failures indicated in the Travis CI log.

**Comment by Ailrun** [comment]
Oh, I didn't notice that there's these many packages depend on `ReactElement` type.
IMO, we need some fundamental fix on React@16 typing...

**Comment by tkrotoff** [comment]
Why closing instead of fixing issues?

**Comment by Ailrun** [comment]
@tkrotoff
To many packages already depends on ReactElement, so IMO, Fixing ReactElement itslef is more appropriate in terms of compatibility.
However, it's not fully related what this PR try, so I close this PR.

**Pull request closed without merging**
