### PR TITLE
[color-string] Define behaviour on get.[rbg|hsl|hwb](null) 

### PR DESCRIPTION
**Pull request by ccjmne**
- [x] I used a meaningful title for the pull request. I included the name of the package modified.
- [x] I tested the change in your own code. (I compiled and ran.)
- [x] I [added tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] I followed the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] I avoided [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] I [ran `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

For changing an existing definition:
- [x] I hereby provide a URL to documentation or source code that provides context for the suggested changes: 
https://github.com/Qix-/color-string/blob/b541d55cc678fd9ac9574f8faec791ee7bf2cf05/index.js#L47-L49

### CODE REVIEW

**Review by BendingBender — CHANGES_REQUESTED** [review]
Why though? I don't get the use case... Why would you want to pass nothing to get back nothing? When I wrote the defintions I left this out on purpose...

**Comment by ccjmne** [comment]
@BendingBender Yeah, I thought about this also before submitting it, but here's my use-case and I think it's actually reasonable:

I'm creating a **Custom Element** and receiving colours passed as attributes, through `attributeChangedCallback`:

```typescript
public attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null>): void {
  //                                          ^      ^                 ^      ^
  //                                            these are `null` when "unset"
  switch (name) {
  case 'colour':
    this.doSomethingWith(get.rgb(newValue as string));
    //                           ^                ^
    //                             or `newValue!`
    // But we'd rather avoid as much as possible non-null assertions, especially when
    // the values **actually will be `null`** sometimes, **and** it's fine.
    break;
  // other stuff...
  }
}
```

The simple truth is:
1. my team frowns upon "non-null assertions" (we have linting rules against those, and just want to have them documented/avoided in general), so these are kinda unwelcome:
```typescript
// Even if `newValue` is null, it doesn't matter.
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
this.doSomethingWith(get.rgb(newValue!) ?? DEFAULT_COLOUR);
this.doSomethingWith(get.rgb(newValue as string) ?? DEFAULT_COLOUR);
```
2. I don't wanna do:
```typescript
this.doSomethingWith(get.rgb(newValue ?? '') ?? DEFAULT_COLOUR);
```

I definitely understand how this feels a bit over-the-top, maybe; and the behaviour isn't directly presented in `color-string`'s (arguably quite succint) documentation, so... no hard feelings if you think it doesn't have its place here!

Nonetheless, it's implemented and I don't think it's likely to go away (the `if (!string) return null;`).

Regardless of what you choose, really, I don't want a headache, the definitions have been accepted and used just fine as they are right now and I don't mean to suggest anything's broken 🙇‍♂️

**Comment by BendingBender** [comment]
No worries. I think your arguments are legitimate, especially because the lib actually implements checks for the `null`/`undeifned` case. That's ok with me.

**Review by BendingBender — APPROVED** [review]

**Comment by ccjmne** [comment]
Sweet!
Thanks for the quick review, have a good weekend!

**Comment by BendingBender** [comment]
Same to you!

**Comment by ccjmne** [comment]
Ready to merge

**Pull request merged**
