### PR TITLE
Fix error TS2507

### PR DESCRIPTION
**Pull request by JustinBack**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41353#issuecomment-579381008
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@JustinBack the types for Node has been updated IMO to allow exactly this, as there is internal 'EventEmitter' alias:

```ts
import EventEmitter = require("events");

import { EventEmitter as EventEmitterClzz } from "events";

const emitterOne = new EventEmitter();
const emitterTwo = new EventEmitterClzz();

emitterOne....
emitterTwo....
```
and it really works, but you need updated Node types:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50266

**Comment by JustinBack** [comment]
Interesting,

My CI fails to compile the typescript using latest node types.

I'll check that

**Comment by JustinBack** [comment]
Resolved by using the proper docker image!

**Comment by peterblazejewicz** [comment]
thx for the update!

**Pull request closed without merging**
