### PR TITLE
Add bluebird-global typings for bluebird.js.

### PR DESCRIPTION
**Pull request by d-ph**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

What it does.

`bluebird-global` uses `bluebird` typings in order to expose its functions on the global Promise symbol. This is generally how devs use bluebird.js in the browser. For various reasons this couldn't be done in the `bluebird` typings.

### CODE REVIEW

**Comment by lhecker** [comment]
@d-ph IMHO you should clean up the empty lines before and after the curly brackets, match the number of trailing newlines at the end of the files, as well as sort the interface members alphabetically. But that's my own purely stylistic opinion which you can follow if you want to or not. The code itself is as I see it correct and surely a wellcome addition to DefinitelyTyped! 👍 from me.

**Comment by d-ph** [comment]
Hi @lhecker . Thanks for your review. I don't quite agree with removing the empty lines around lines with curly brackets :( It's more readable this way according to my taste. As for the other two points -- agreed and fixed.

Cheers.

**Comment by lhecker** [comment]
Well yeah stylistic opinions are always purely subjective, which is why I said it's entirely your choice if you want to change it or not. 🙂 But I think in the end it's the right choice for this, since most JS/TS code is written this way (and can be seen for instance [here](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2015.core.d.ts)).

**Comment by d-ph** [comment]
You convinced me with this link to the official `es2015.core.d.ts` file. Fixed.

**Comment by vvakame** [comment]
sorry for late, and I merged by mistake...
I'm sorry but can I get a PR again to master?

**Comment by d-ph** [comment]
@vvakame https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13541

**Pull request merged**
