### PR TITLE
Added withRouter to react-router

### PR DESCRIPTION
**Pull request by empz**
I've added `withRouter` module that was added in version [2.4.0](https://github.com/reactjs/react-router/blob/master/CHANGES.md)

### CODE REVIEW

**Comment by galvesribeiro** [comment]
I think there are missing Interfaces that enforce the user to receive the this.props.router and this.props.location... You just exposed the `withRouter` but in order to that to work there are side-effects...

**Comment by emzero** [comment]
Yes, there are probably stuff missing. It's my first definition and I'm also new to TypeScript. 
Having a way to actually use `withRouter` is better to not even being able to import it IMHO.

**Comment by mhegazy** [comment]
@sergey-buturlakin, @mrk21, @vasek17 and @ngbrown any comments?

**Comment by Ciantic** [comment]
This is very difficult to review cause it reformats the whole file. But basically withRouter also includes `router` in the props too, so RouterContextProps or such should be exported also.

**Comment by frederickfogerty** [comment]
@emzero by the way, you can override types locally so you can at least import it, and wait for an "official" type definition to be implemented

**Comment by frederickfogerty** [comment]
By the way I 👎  this change, it needs to be a proper type definition, not just `type withRouter = Function`

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has not been approved by other authors and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs.

**Comment by atrauzzi** [comment]
Whoa, this one is fairly important.  Need type info for it.

**Pull request closed without merging**
