### PR TITLE
[@types/node]: child_process.ChildProcess should be a class, not an interface

### PR DESCRIPTION
**Pull request by AgentEnder**
…nterface

See #55400

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/child_process.html#child_process_class_childprocess
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (N/A)

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
I agree your use case is strange but this change is valid as the docs clearly declare it as a class.

**Comment by peterblazejewicz** [comment]
I've checked source tests, the constructor seems to be parameterless

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by AgentEnder** [comment]
Ready to merge

**Pull request merged**
