### PR TITLE
Update @types/echarts

### PR DESCRIPTION
**Pull request by AM-young-fun**
Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/AntiMoron/DefinitelyTyped/blob/fbe02a0916f6acde921311a76fd54865134ca967/types/echarts/index.d.ts>>

### CODE REVIEW

**Comment by AntiMoron** [comment]
已经测试通过。
Modification has been well tested.

**Comment by RyanCavanaugh** [comment]
Comments should be in English, please

**Comment by RyanCavanaugh** [comment]
Eh I guess none of the others are

**Comment by AntiMoron** [comment]
@RyanCavanaugh  

> 已经测试通过。  // The author is Chinese. So I tell him in Chinese.
> Modification has been well tested.   // The translated comment. For you guys. :]

**Pull request merged**
