### PR TITLE
fix(node): align with AbortConroller.abort(reason?: any)

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Adds optional parameter:
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64570

/cc @tonivj5 @Semigradsky

Thanks!

Closes #64570

### CODE REVIEW

**Review by Semigradsky — APPROVED** [review]

**Comment by tonivj5** [comment]
Thanks, so fast! 😁

`AbortSignal.reason` should be added too

https://nodejs.org/api/globals.html#abortsignalreason

**Comment by jakebailey** [comment]
@sandersn My memory is shoddy here, but, didn't we have issues with these APIs, including reason, breaking everyone?

**Comment by sandersn** [comment]
Mine is too, but I thought Typescript fixed its types as of TS 4.7 or 4.8.

**Comment by jakebailey** [comment]
I think I'm confusing this with #62909 which was `AbortSignal`, not `AbortController`.

**Review by jakebailey — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
