### PR TITLE
[react] Use csstype for React.CSSProperties

### PR DESCRIPTION
**Pull request by pelotom**
[`csstype`](https://github.com/frenic/csstype) generates CSS property typings from MDN data.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/frenic/csstype
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
So this PR is about reducing the need for re-implementing / maintaining CSS within React definition and instead leaning on csstype which already does that well? Seems like a reasonable idea. I'm unfamiliar with the csstype project so I'd like to hear other maintainers views. If it's a well maintained project then that seems like it could be a good idea...

**Review by Jessidhia — COMMENTED** [review]
This looks good to me; they even thought ahead and let you specify the type of the length-like properties in the generic parameter.

The main problem I expected to encounter would be them not accepting `number` parameters to properties such as `width`, where React automatically converts them to `px`, but the generic parameter let us say that `number`s are valid too.

**Comment by pelotom** [comment]
@johnnyreilly

> So this PR is about reducing the need for re-implementing / maintaining CSS within React definition and instead leaning on csstype which already does that well?

Yep, that’s the idea.

>If it's a well maintained project then that seems like it could be a good idea...

@frenic has been very responsive to feedback, and the approach of auto-generating from official docs seems like the best possible. In a sense, _nobody_ should be (manually) maintaining typings for CSS, and yet currently dozens of projects are doing so, and their definitions are sometimes inconsistent with one another. I have high hopes that csstype can finally provide a standard set of definitions usable across react, css-in-js and other ecosystems.

**Comment by johnnyreilly** [comment]
Sold!

**Pull request merged**
