### PR TITLE
AngularJS: add initial support for component router

### PR DESCRIPTION
**Pull request by davidreher**
this is the followup of #7260.
The corresponding documentation can be found [here](https://docs.angularjs.org/api/ng/type/angular.Module) and [here](https://angular.io/docs/ts/latest/api/router/Router-class.html)

### CODE REVIEW

**Comment by vvakame** [comment]
@andrejunges could you review this PR?
@davidreher please resolve conflict.

**Comment by andrejunges** [comment]
@vvakame The documentation added to the IComponentOptions properties is really good :+1:

**Comment by vvakame** [comment]
thanks!
@davidreher please resolve conflict.

**Comment by davidreher** [comment]
When I created this there were no conflicts, I will work on this tomorrow ...

**Comment by davidreher** [comment]
@vvakame fixed the conflicts, and travis ci has passed ...

**Comment by vvakame** [comment]
sorry for delay, happy new year!

**Pull request merged**
