### PR TITLE
[node] Add hash method to crypto module

### PR DESCRIPTION
**Pull request by dhritzkiv**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Node.js Docs for crypto.hash](https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptohashalgorith-data-outputencoding)

### CODE REVIEW

**Comment by dhritzkiv** [comment]
CI error appears to be unrelated:

> Cannot find module 'mime' or its corresponding type declarations  @definitelytyped/expect

**Comment by codershiba** [comment]
CI errors should be fixed by #69231

**Comment by codershiba** [comment]
Can be closed as changes have been included in #69212.

**Comment by dhritzkiv** [comment]
Oops - I somehow missed that PR. Closing this one.

**Comment by dhritzkiv** [comment]
@codershiba want to cherrypick my commit for test/crypto.ts? It adds crypto.hash 'tests'

 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69236/commits/1c2136173261f414da1d1883c3d8af05288c0fbc

**Pull request closed without merging**
