### PR TITLE
[aws-sdk2-types] ran dprint fmt

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
👋 Hi! This PR is meant to let you know that we're going to be applying formatting automatically to all DefinitelyTyped packages[^1]. This PR is split out of:

* https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993: the discussion that includes backing context and our planned approach
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66235: onboards the repository to [dprint](https://dprint.dev)

This package is particularly huge (>1MB), so we're tagging you in an individual PR as a heads up. Please post here to let us know if you have any workflow needs that auto-formatting might disrupt[^2].

Cheers! 💖 

[^1]: Note that formatting will be applied as a commit to `master` after each PR. PRs won't be blocked on any CI check for proper formatting. See #65993 for more information.
[^2]: For example, if this package is fully auto-generated (rather than manually edited), subsequent PRs might have a lot of noise from formatting differences. We can exclude it from formatting in that case.

### CODE REVIEW

**Review by sandersn — APPROVED** [review]
This package is a manual clone of *just* the parts of aws-sdk that are used by (old) types packages on DT. Realistically, it's never going to change, so it's fine to format it.

**Comment by JoshuaKGoldberg** [comment]
Great thanks - in that case I'll close this out and let it be done by the main commit.

**Comment by JoshuaKGoldberg** [comment]
Actually - instead of closing these individual ones out I'm going to start merging them in individually. That way we can get early testing of formatted packages, and revert individually if we need.

**Comment by JoshuaKGoldberg** [comment]
Ready to merge

**Comment by JoshuaKGoldberg** [comment]
Ready to merge

**Pull request merged**
