### PR TITLE
[pdfjs-dist] Add module declaration for pdf.js library

### PR DESCRIPTION
**Pull request by kevinlowe0x3F7**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by minestarks** [comment]
Is this for https://www.npmjs.com/package/pdfjs-dist ?
If so, the npm package name needs to match the folder in DefinitelyTyped. This should be added as a new typing under pdfjs-dist.

**Comment by kevinlowe0x3F7** [comment]
Hm I wonder how the folder was approved previously, I was wondering about the discrepancy myself. Would it be as simple as renaming the current `types/pdf/` to `types/pdfjs-dist`?

**Comment by minestarks** [comment]
Perhaps it was added before the npm/bower packages were published. Yes it should be just a matter of renaming the folder. 

Author @jbaldwin any feedback?

**Comment by kevinlowe0x3F7** [comment]
Folder's been renamed and appropriate files have been updated @minestarks

**Pull request merged**
