### PR TITLE
added render to router typing

### PR DESCRIPTION
**Pull request by adamiprinciples**
https://github.com/ReactTraining/react-router/blob/master/docs/API.md#renderprops

### CODE REVIEW

**Comment by vvakame** [comment]
Could you fix travis ci failed?

**Comment by adamiprinciples** [comment]
That should be good now. Somehow the render prop got put on the wrong interface

**Comment by minestarks** [comment]
@adamiprinciples Thanks for the contribution. The checks are still failing, could you fix them? Thank you.

Since there haven't been any changes in this PR for a month I plan to close this out in a couple of days if no further changes.

**Comment by paulvanbrenk** [comment]
This PR seems abandoned, please re-open when you made the requested changes.

**Pull request closed without merging**
