### PR TITLE
Rewrite globalize.d.ts

### PR DESCRIPTION
**Pull request by gcastre**
Rewrite the globalize.d.ts adding all the missing functions and their respective comments.

Doc available here: https://github.com/jquery/globalize

### CODE REVIEW

**Comment by vvakame** [comment]
*globalize/globalize.d.ts*

to author(@afromogli). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by afromogli** [comment]
Hi, sure I can give it a shot! Will have time to do it in the weekend, is that ok with you?

**Comment by RamanBut-Husaim** [comment]
@afromogli, hello. Any updates on this?

**Comment by afromogli** [comment]
@RamanBut-Husaim Sorry guys but I simply don't have time to do this at the moment. Can anyone else solve this?

**Comment by filoleg** [comment]
so, is it going to be merged into master anytime soon? I needed typings for globalize and was about to write my own until I noticed that @gcastre submitted a pull request that solves the issue very nicely.

**Comment by vvakame** [comment]
Okey, I merge this PR now. Please send another PR if we needed.

**Pull request merged**
