### PR TITLE
knex: Changed export to allow to define typed knex migration scripts (export Knex interface)

### PR DESCRIPTION
**Pull request by streuspeicher**
The previous version the factory function to create a Knex instance, only.

This change exports the Knex interface itself and declares an additional factory function called "Knex" to preserve the existing behavior.

### CODE REVIEW

**Comment by vvakame** [comment]
*knex/knex.d.ts*

to author(@tkQubo). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by tkQubo** [comment]
I think lines below can be removed since they are no longer used:
https://github.com/streuspeicher/DefinitelyTyped/blob/master/knex/knex.d.ts#L18-L25

@streuspeicher thanks for improvements!

**Comment by tkQubo** [comment]
@vvakame :+1:

**Comment by vvakame** [comment]
@tkQubo thanks!
@streuspeicher thanks mate!

**Pull request merged**
