### PR TITLE
Added vanilla-toast DT

### PR DESCRIPTION
**Pull request by ccrisrober**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

The link to the library is: https://github.com/AlexKvazos/VanillaToasts

### CODE REVIEW

**Comment by vvakame** [comment]
https://www.npmjs.com/package/vanillatoasts
please rename vanilla-toasts/vanilla-toasts.d.ts to vanillatoasts/vanillatoasts.d.ts and vanilla-toasts-test.ts to vanilla-toasts-test**s**.ts

**Comment by maldicion069** [comment]
Renamed now!

**Comment by RyanCavanaugh** [comment]
Need to rename it in the reference as well

**Comment by andy-ms** [comment]
Needs test fixes

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
