### PR TITLE
Credentials object spelling fix

### PR DESCRIPTION
**Pull request by aroslov**
Underlying google auth library requires this type of structure. It's actually documented in the dialogflow source code at https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/src/v2/intents_client.js#L68 so possibly just a typo. This fix is tested locally.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/src/v2/intents_client.js#L68

### CODE REVIEW

**Comment by aroslov** [comment]
Also note that when the Credentials structure is supplied, both fields are required. Otherwise authentication fails.

**Comment by tom139** [comment]
I opened the same PR yesterday, #28321 hope we will get a reviewer soon. If you are using Dialogflow with TypeScript, you may find #28349 interesting as well. 😉

**Comment by aroslov** [comment]
@tom139 nice! I should've checked before submitting.

I've also made it required ;)

**Comment by tom139** [comment]
Yes, although not explicitly stated, both of them are required.
Well done @aroslov on catching it! And thank you @DanielRosenwasser for the quick feedback and merge. 💪🏽

**Pull request merged**
