### PR TITLE
Add 'search' method to connection.js

### PR DESCRIPTION
**Pull request by douglascayers**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jsforce/jsforce/blob/master/build/jsforce-core.js
  * Line 1910
  * Also note, the jsdocs for the method in the jsforce library are wrong. What is returned is NOT an array of RecordResult; it's the SearchResult type included in this pull request.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### SOSL Response
```typescript
jsforceClient.search(
    'FIND {my} IN ALL FIELDS RETURNING Foo__c(Id, Name), Bar__c(Id, Name)',
    (err: Error, results: SearchResult) => {
        console.log(results);
    },
);
```
```json
{
    "searchRecords": [
        {
            "attributes": {
                "type": "Foo__c",
                "url": "/services/data/v49.0/sobjects/Foo__c/a7hB0000000GpeuIAC"
            },
            "Id": "a7hB0000000GpeuIAC",
            "Name": "My Foo"
        },
        {
            "attributes": {
                "type": "Bar__c",
                "url": "/services/data/v49.0/sobjects/Bar__c/a7vB000000006VWIAY"
            },
            "Id": "a7vB000000006VWIAY",
            "Name": "My Bar"
        }
    ]
}

```

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsforce ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsforce@latest/))
was missing the following properties:
1. addListener
1. on
1. once
1. prependListener
1. prependOnceListener

<details>
<summary>as well as these 13 other properties...</summary>
<p>removeListener, off, removeAllListeners, setMaxListeners, getMaxListeners, listeners, rawListeners, emit, eventNames, listenerCount, VERSION, RecordStream, require</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 782113cfa57f8bdf4bb176c6490363ac253e8fb2
</p>

**Comment by douglascayers** [comment]
> Hey @douglascayers,
> 
> 😒 Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module. This can potentially save days of time for you.

Subsequently added tests per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50220/commits/dbc869f4d9d7dc6d8873d40aae77e9ac5936b9f9

**Review by dolanmiu — APPROVED** [review]

**Comment by douglascayers** [comment]
Thanks @dolanmiu

**Comment by douglascayers** [comment]
Ready to merge

**Pull request merged**
