### PR TITLE
update(graphlib): setGraph should take an any

### PR DESCRIPTION
**Pull request by simmonmt**
dagred3 assumes/requires that callers use an object as the graph label
rather than a simple string.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://dagrejs.github.io/project/dagre-d3/latest/demo/arrows.html (the first line of the demo)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## graphlib ([<kbd>unpkg</kbd>](https://unpkg.com/browse/graphlib@latest/))
was missing the following properties:
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cd88cb0786c2feb315d895d7b97a7a33929b9c18
</p>

**Comment by simmonmt** [comment]
@lutzroeder could I convince you to take a look at this PR?

**Comment by lutzroeder** [comment]
LGTM

@weswigham

**Review by danvk — APPROVED** [review]

**Comment by simmonmt** [comment]
Ready to merge

**Comment by simmonmt** [comment]
Thanks for your help @lutzroeder !

**Pull request merged**
