### PR TITLE
[jasmine] Support custom async matchers

### PR DESCRIPTION
**Pull request by chivesrs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See below.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

See codepen https://codepen.io/chivesrs/pen/zYGEZvP and the Jasmine PR to introduce this feature https://github.com/jasmine/jasmine/pull/1732, Be sure to click on "Spec List" to see the passing tests (the first 2 are intended to pass, the 3rd is intended to fail, it should be obvious why based on reading the test source code). The test source code is available in the JS pane on the far right. You may need to scroll and/or maximize the panel.

image

### CODE REVIEW

**Comment by chivesrs** [comment]
You might be asking why does expectAsync now take in either a raw value or a Promise? Apparently this is intended; the comments in the PR I linked in the top comment explain this very well.

**Comment by chivesrs** [comment]
Also, to figure out exactly what expectAsync(8).toBeEight() returned, I did this code (not committed):

```
it('test', () => {
  const x = expectAsync(8).toBeEight();
  console.log(x);
  console.log(await x);
  await expectAsync(8).toBeEight();
});
```

The test passed, the values logged were a Promise of some sort, and undefined. So I believe the typing is Promise<void> which is what I have in the test code.

**Review by devoto13 — APPROVED** [review]
Looks well-aligned with the linked Jasmine PR. Thanks!

**Comment by amcasey** [comment]
@chivesrs did you want to wait for feedback from @borisyankov before merging?

**Comment by chivesrs** [comment]
No, you can merge whenever. GitHub automatically added Boris and I didn't do it myself.

**Comment by chivesrs** [comment]
@amcasey

**Pull request merged**
