### PR TITLE
Added a lot of missing types from angular2/* modules

### PR DESCRIPTION
**Pull request by georgiosd**
Only `angular2/http` is complete (pasted from alpha27 d.ts files), the rest I took from https://github.com/auth0/angular2-authentication-sample/blob/master/typings/_custom/ng2.d.ts

### CODE REVIEW

**Comment by vvakame** [comment]
@alexeagle could you review this PR?

@georgiosd please fix travis ci failed

**Comment by georgiosd** [comment]
@vvakame it compiles locally - are you on Typescript 1.5 on Travis?

**Comment by rolandjitsu** [comment]
@georgiosd note that some of the stuff with the latest release was renamed, for instance the `ControlNameDirective` is now a `NgControlName` and so on. So I think that this will not fix the typings missing. I think the angular team (maybe @gdi2290 or @rkirov knows more about it, but probably this will all be handler by [#2335](https://github.com/angular/angular/issues/2335)) should find a way to publish the typings with the right declarations so we can use them.

**Comment by georgiosd** [comment]
Guys, after hitting several roadblocks in the last few days, I think I'm going to wait for 2.0 to get to RC or at least beta before I put any more time into it. I can help out with the definition at that time.

**Comment by alexeagle** [comment]
Note the comment in the definition file - it is generated from source so we
would prefer PRs against the generator.

**Pull request closed without merging**
