### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by kaigth**
the `export as namespace ReduxActions;` is causing breakage in the newer renditions of typescript. The error now thrown is:

error TS1316: Global module exports may only appear at top level.

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Maybe you can refer this: [global.d.ts
](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html), not remove it.

**Comment by kaigth** [comment]
@TonyPythoneer Agreed, I updated it and it now functions correctly.

**Comment by kaigth** [comment]
Going to revise, closing PR for now.

**Comment by TonyPythoneer** [comment]
If you want to test it's correct or not, you can do it in your local environment. Until it's okay, you can push the new commits.

**Comment by kaigth** [comment]
@TonyPythoneer Updated and tests are passing.

**Comment by TonyPythoneer** [comment]
I had read the redux-actions document. It said it can offer UMD style, so the code can't be removed.

Therefore, I want to understand you use what version of TypeSrcipt and what happened with it.

**Comment by kaigth** [comment]
@TonyPythoneer I am using `typescript 2.1.5` and I installed redux-actions via typings command `typings install dt~redux-actions --save`

Once compiled I get `error TS1316: Global module exports may only appear at top level.` as an error. I am simply importing via node_modules redux-actions as `import * as ReduxActions from 'redux-actions` so nothing crazy here.

if I change what has been changes via the name space to `export namespace ReduxActions {}` all runs as should.

**Comment by TonyPythoneer** [comment]
@kaigth I guess you need to install typing file by npm, not typings. Since releasing TypeScript 2.0, DefinitelyTyped has released typings file on npm and I hadn't used typing. 

Maybe you can try to use npm to download typings file. Let's discuss next.

By the way, I use `import * as ReduxActions from 'redux-actions'`. It doesn't issue any error.

**Comment by kaigth** [comment]
I think I see what is happening @TonyPythoneer typings wraps the file in a declaration `declare module 'redux-actions' {` Oddly though the 8 other typing files I got from typings work just fine, this is the only one with issues.

**Comment by kaigth** [comment]
@TonyPythoneer does it break for you in my branch using my code change? If not would this be considered an enhancement to fix with use of typings?

**Comment by TonyPythoneer** [comment]
@kaigth Let's try to `npm install @types/redux-actions`. I will see better world. :smile:

**Comment by kaigth** [comment]
@TonyPythoneer I used NPM and it works fine, however I still feel that the typings community is large and growing. I adjusted the NPM code with my change and all continued to function just fine so I don't see issues with my code change (which was not removing the namespace). I can carry on and let this be a problem for someone else but it will probably rear it's head for typings that begin with `namespace as` I'll close.

**Comment by TonyPythoneer** [comment]
@kaigth In fact,  `typings community` can't solve module dependency. I think this is a design flaw. It's applied for  TypeScript 1.x generation. By the way, `tsd` has the same problem. `tsd` can't record updated time of the module. Though `typings` has solve `tsd` problem but they have the same problem is they can't solve module dependency.

Now, Typescript 2.x has advanced typing syntax for defining module, global and UMD. It has solved the most of issues. I hope you convert your typing source to `@types`. About TypeScript and typings file news, you can follow TypeScript repo and DefinitelyTyped. Maybe let you not be in vain.

**Pull request closed without merging**
