### PR TITLE
[cucumber] Use params and/or attach method from default world in a new custom world

### PR DESCRIPTION
**Pull request by manu7691**
At the moment, cucumber definition types only allow to add a custom world without any parameter

type -> `setWorldConstructor(world: () => void): void;`

```
var {defineSupportCode} = require('cucumber');
var seleniumWebdriver = require('selenium-webdriver');

function CustomWorld() {
  this.driver = new seleniumWebdriver.Builder()
    .forBrowser('firefox')
    .build();

  // Returns a promise that resolves to the element
  this.waitForElement = function(locator) {
    var condition = seleniumWebdriver.until.elementLocated(locator);
    return this.driver.wait(condition)
  }
}

defineSupportCode(function({setWorldConstructor}) {
  setWorldConstructor(CustomWorld)
});
```

So with this change

type -> `setWorldConstructor(world: (() => void) | ({})): void;`

it will be possible to do: 

```
var {defineSupportCode} = require('cucumber');
var seleniumWebdriver = require('selenium-webdriver');

function CustomWorld({attach, parameters}) {
  this.attach = attach;
  this.parameters = parameters;
  this.driver = new seleniumWebdriver.Builder()
    .forBrowser('firefox')
    .build();

  // Returns a promise that resolves to the element
  this.waitForElement = function(locator) {
    var condition = seleniumWebdriver.until.elementLocated(locator);
    return this.driver.wait(condition)
  }
}

defineSupportCode(function({setWorldConstructor}) {
  setWorldConstructor(CustomWorld)
});
```
This change will allow to use attach() in custom world, without losing the possibility of add a screenshot error, p.e, on JSON output.

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.

Changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/world.md

### CODE REVIEW

**Comment by minestarks** [comment]
@manu7691 Could you add a test that demonstrates the problem this change is solving? Thank you.

**Comment by hinell** [comment]
Well it changes nothing.

**Comment by jan-molak** [comment]
I'm wondering if it's a good idea to keep adding Cucumber 2-specific interfaces to current Cucumber 1.x typings...
For example, the `Scenario`, `Feature` and many other interfaces look completely different than they used to with Cucumber 1.x. In many cases, they're also incompatible: `scenario.getName()` vs `scenario.name`, etc.

Is it sensible to create `@types/cucumber-2` and put the new definitions there instead?

The same applies to `defineSupportCode`, which is only available with Cucumber 2.

Thoughts?

**Comment by manu7691** [comment]
@jan-molak I agree with your idea, specially, now that a lot of changes are happening on CucumberJS project. It will make clear to maintain. Although there is https://github.com/cucumber/cucumber-js/pull/721 which is supposed to define types in the project itself.

About [publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) a new package on npm, you must create it first on DefinitelyTyped and later package will be published automatically to npm using types-publisher tool.

**Comment by minestarks** [comment]
@jan-molak @manu7691  for new versions of the same package, please don't create a new folder -- your PR will be rejected if the name of the folder doesn't match the npm package. The `index.d.ts` should contain the latest version, and older versions should be moved to a subfolder. Please see the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version), it has all the relevant guidance.

**Comment by jan-molak** [comment]
Thanks for the suggestion, @minestarks, much appreciated! 

@manu7691 / @abraaoalves I'm going through the new Cucumber 2 interfaces as part of my work on adding the support for Cucumber 2 to [Serenity/JS](github.com/jan-molak/serenity-js). This is going to take a couple of days, so if you'd like to implement @minestarks' suggestion in the meantime I'll later add whatever new things I discover?

**Comment by manu7691** [comment]
@jan-molak In last commit, I split definition types into v1 and v2, but for some reason that I don't know, test is failing. @minestarks any idea? I follow the link you suggested me.
 Thanks in advance

**Comment by minestarks** [comment]
The test failure says:

> Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/cucumber/v1 indicates major version 1, but header indicates major version 0

Try updating your headers in the index.d.ts files with the version
```// Type definitions for cucumber-js v1```
```// Type definitions for cucumber-js v2```

**Comment by paulvanbrenk** [comment]
@manu7691 can fix the merge issues and any CI issues you may encounter after that.

**Comment by manu7691** [comment]
@paulvanbrenk done! ;)

**Comment by paulvanbrenk** [comment]
Thanks!

**Pull request merged**
