### PR TITLE
[qs] Add 'comma' to parse options

### PR DESCRIPTION
**Pull request by dpsmith3**
Please fill in this template.

- [y ] Use a meaningful title for the pull request. Include the name of the package modified.
- [y ] Test the change in your own code. (Compile and run.)
- [y ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [y ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [y ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [y ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [y ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ljharb/qs
"Some people use comma to join array, qs can parse it:"
```
var arraysOfObjects = qs.parse('a=b,c', { comma: true })
assert.deepEqual(arraysOfObjects, { a: ['b', 'c'] })
```
- [ y] Increase the version number in the header if appropriate.
- [n ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by CarlosBonetti — APPROVED** [review]

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
This appears to be a malformed header. Could you remove the line in the `tslint.json` file in this folder that says `dt-header: false` and fix any errors that come up? You will want this first line to say `Type definitions for qs 6.5`. You are welcome to remove any other such line from the `tslint.json` file, though that might be a lot of work depending on what issues are being ignored. Thanks!

**Comment by uniqueiniquity** [comment]
Actually, I may not be testing with the version of TSLint that added that rule. Let me look into this and see if we want this rule to be enabled in general or not.

**Comment by dpsmith3** [comment]
@uniqueiniquity Thanks for the review. Sorry for the delay in responding - I've been on holiday. Just added a commit which should cover it. Thanks, Dan

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
