### PR TITLE
[koa-bodyparser] add ability to strictly type request body

### PR DESCRIPTION
**Pull request by pkuczynski**
This is re-opening #52025 which was accidentally closed due to a mistake in the description of another PR.

### CODE REVIEW

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by pkuczynski** [comment]
Ready to merge

**Comment by AdamHerrmann** [comment]
@pkuczynski 

This PR seems to disallow the request body to be an array.  Was that intentional?

**Comment by pkuczynski** [comment]
I just followed what I have seen in the source for the body parser. I am not at my laptop at the moment so I can dbl check tonight and fire up PR. Do you have example repo or request body which should be supported?

**Comment by pkuczynski** [comment]
Here you go @AdamHerrmann https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53639

**Comment by pkuczynski** [comment]
> Why request body type changed to string | Record<string, unknown>? Now to type it I'm forced to do the following:
> 
> `const body = ctx.request.body as unknown as BodyValues;`
> Why it is not typed as `unknown`? Thanks for considering!

@crystalfp whats the type of `BodyValues`? Is this an array? If so, I fixed this issue in #53639

**Comment by crystalfp** [comment]
No, it is not an array. It is this:
```
interface BodyValues {
    mdate: number;
    displayName: string;
    description: string;
    filename: string;
    format: string;
    idFrom: string;
    directory: string;
}
```

**Comment by pkuczynski** [comment]
Than it should work as `const body = ctx.request.body as BodyValues` or `const body: BodyValues = ctx.request.body`

**Comment by crystalfp** [comment]
Unfortunately no:
`const body = ctx.request.body as BodyValues;` gives ts error 2352:
```
Conversion of type 'string | Record<string, unknown>' to type 'BodyValues' may be a mistake because neither type
sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Record<string, unknown>' is missing the following properties from type 'BodyValues': mdate, displayName,
description, filename, and 3 more.
```

`const body: BodyValues = ctx.request.body` gives ts error 2322:
```
Type 'string | Record<string, unknown>' is not assignable to type 'BodyValues'.
  Type 'string' is not assignable to type 'BodyValues'.
```

**Comment by pkuczynski** [comment]
@crystalfp you are right. The tests were not accurate. I created #53691 to fix that. Apologies for the inconvenience.

**Comment by hirochachacha** [comment]
We should revert this commit. This commit deleted original test because it isn't passed. #53691 is the same.

**Comment by hirochachacha** [comment]
```
~/D/t/koa-bodyparser ❯❯❯ yarn test koa-bodyparser
yarn run v1.22.10
warning ../package.json: No license field
$ dtslint types koa-bodyparser
Error: /Users/hiro/DefinitelyTyped/types/koa-bodyparser/test/koa-bodyparser-tests.ts:10:34
ERROR: 10:34  expect  TypeScript@4.4 compile error:
Property 'ok' does not exist on type 'string | Record<string, unknown>'.
  Property 'ok' does not exist on type 'string'.

    at /Users/hiro/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/hiro/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leumasme** [comment]
Can confirm that this is a breaking change on a PATCH version - this will break for many people. Please revert ASAP

**Comment by yvesnrb** [comment]
> Unfortunately no.
> 
> `const body = ctx.request.body as BodyValues;` gives ts error 2352:
> 
> ```
> Conversion of type 'string | Record<string, unknown>' to type 'BodyValues' may be a mistake because neither type
> sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
>   Type 'Record<string, unknown>' is missing the following properties from type 'BodyValues': mdate, displayName,
> description, filename, and 3 more.
> ```
> 
> `const body: BodyValues = ctx.request.body` gives ts error 2322:
> 
> ```
> Type 'string | Record<string, unknown>' is not assignable to type 'BodyValues'.
>   Type 'string' is not assignable to type 'BodyValues'.
> ```
> 
> In my humble opinion, defining body as `unknown` in index.d.ts is the most natural solution. It says the body content is in fact unknown and force you to cast it using `as SomeTypeTheDeveloperKnows`.

I'm still having the problem mentioned here. Is there a work around that we can use?

**Comment by crystalfp** [comment]
Here it is @yvesnrb !
```
const body = ctx.request.body as unknown as YourType;
```

**Comment by soswow** [comment]
> Can confirm that this is a breaking change on a PATCH version - this will break the projects of many people. Please revert or fix ASAP

100% it def. broke our project.

**Comment by soswow** [comment]
Maybe I am missing something obvious. Please help me understand if I am wrong.
What if incoming body is an json array? I can see in code that `koa-bodyparser` while `parseBody` method calls `parse.json` which in case calls `JSON.parse` which obviously can be an array.
So, how come body now strictly a string OR an object?

**Comment by leumasme** [comment]
I think the fact that 3 people invested the time to find this exact pull request and complain means that the actual numbers of projects having problems will be much greater.
Please accept that pushing a breaking change like this is not just nonsense but harmful.

**Comment by soswow** [comment]
I will go for a limb and assume that idea was to keep major version in sync with actual `koa-bodyparser` library.
@leumasme did you know there are version 5.0.0, 5.0.1 and 5.0.2 exist.? =) It was released in 2018 It took me some time to understand it's not really the latest-latest version.

**Comment by pkuczynski** [comment]
@soswow there are two PR waiting to be approved and merged:

* #53691 fixing this issue
* #53715 reverting this change in total

There is a disagreement between maintainers on how to proceed. So the status quo is that we are waiting for DT maintainers to help us solve this issue. Hopefully soon...

Apologies for the inconvenience this PR caused.

**Comment by soswow** [comment]
@pkuczynski Thank you!
Will it be a breaking change? I mean - will it break people's code? and if so will it be released as a breaking change? I understand the wish to have same looking version as library itself, but should semver take precedence?

**Pull request merged**
