### PR TITLE
[classnames] Support for ES modules

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/JedWatson/classnames/commit/915186aaa510e0c6be6c2cf20788aac474790e27
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by seansfkelley — CHANGES_REQUESTED** [review]
The corresponding change in `classNames` hasn't been released yet, so it seems these two PRs should block on that lest you break the entire Typescript-React community. :)

There is a ticket to track this release (https://github.com/JedWatson/classnames/issues/152), which I've taken the liberty of pinging the maintainer on.

**Comment by alexey-pelykh** [comment]
@seansfkelley the #25205 adds an extra declaration without breaking anything, but I'd rather avoid that approach at all. Indeed, the https://github.com/JedWatson/classnames/issues/152 is not yet there :( I guess it blocks this PR :|

**Comment by seansfkelley** [comment]
Got it. Totally agree the default import is stylistically preferable, but such a sudden transition for such a widely-used library seems likely to bring down a rain of complaints and bug reports... #25206 might be the best plan (assuming that the library change ever gets merged).

**Comment by alexey-pelykh** [comment]
#25205 is a workaround that would work until/if classnames gets updated and it would allow to use `esnext` approach.

**Comment by seansfkelley** [comment]
Ooh, I see, I didn't notice that it exposed a different path for the typings.

**Pull request closed without merging**
