### PR TITLE
[redux-orm] typings for 0.13.3

### PR DESCRIPTION
**Pull request by tomasz-zablocki**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
[QuerySet.at](https://redux-orm.github.io/redux-orm/QuerySet.html#at), [QuerySet.orderBy](https://redux-orm.github.io/redux-orm/QuerySet.html#orderBy)
- [X] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`

Note: 
Fixes invalid `QuerySet.at` argument type and incomplete `QuerySet.orderBy` signature

### CODE REVIEW

**Comment by keenondrums** [comment]
@tomasz-zablocki thank you for your work! If you want to upgrade typings to support v0.13, could you make a PR covering all changes between 0.13 and 0.9? Unfortunately, your current implementation is not complete, and I'm afraid a partial implementation could be misleading for others.

You could take some code from [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27274/files)

**Comment by tomasz-zablocki** [comment]
@keenondrums, thank you for the review.

I suppose that I have actually covered majority of changes between 0.9 and 0.13 on [this 0.13](https://github.com/tomasz-zablocki/DefinitelyTyped/tree/feature/redux-orm-0.13.3-types) dedicated branch, but I've also changed the 0.9 typings considerably and I was concerned about the size of the PR.

Let me know if you're willing to go through that much.

There's one thing that I don't quite get in the original 0.9 typings - specifically the `Additional` type parameter on Model and QuerySet, the purpose of it etc. I've been trying to find a clue in redux-orm codebase, without luck unfortunaltely.

**Comment by keenondrums** [comment]
@tomasz-zablocki if you tested your typings in a real-world app, I'd be happy to merge it. All of it. And pass the tourch of supporting this thing to you as I no longer use redux-orm.

As to `Additional`, as you can see `Model` accepts three generics: the first one for mandatory fields, the second one for optional fields we provide defaults for and the third one for virtual getters. It was made that way because some methods require or return only mandatory fields, some of them need both mandatory and optional fields. With the current TypeScript which has powerful mapped types which allow making all of the mapped fields required or optional this separation is not really necessary I guess. I guess when these typings were created TS lacked that power or I didn't know about it :)

**Comment by tomasz-zablocki** [comment]
@keenondrums Thank you, that actually cleared out any doubts I had regarding 0.9 types. 

I think I'll have a go at updating the definitions a bit. 

My experience with TS is modest at best, but I should manage maintaining these, but I'd appreciate a review once I'm done.

Last question: In current 0.9 typings for redux-orm, there's quite a bit of code dedicated to non-public package surface - private methods, non-exported types and functions, internal structures etc. 

PShall the typings cover both the API surface and the internals or just the exported bits  ?

**Comment by keenondrums** [comment]
@tomasz-zablocki I guess I just opened JS sources and added typing for everything I saw :) I guess you should cover only the public facing API.

**Comment by tomasz-zablocki** [comment]
@keenondrums thank you. 

I'll strip the internals of my current typings and possibly relax the mandatory string type of model ids. I shall update this PR by the end of this week.

**Review by fxlrnrpt — CHANGES_REQUESTED** [review]
Please, complete typings as discussed

**Comment by tomasz-zablocki** [comment]
@keenondrums takes a bit more time since this is a major rework, realistic ETA is wednesday. 

If this is too late I can close this PR and open up a new one once I'm done

**Comment by keenondrums** [comment]
@tomasz-zablocki no rush, take your time.

**Comment by tomasz-zablocki** [comment]
@keenondrums I'm almost done.

Aside from cleanup and updating test cases for new and changed things, I have one question left - shall I consider updating the doc comments in the provided declarations ?

**Comment by keenondrums** [comment]
@tomasz-zablocki great news! 
Yeah, updating comments would be nice.

**Comment by tomasz-zablocki** [comment]
@keenondrums still a bit to go, I'll let you know once the cleanup, docs and tests are done

**Comment by tomasz-zablocki** [comment]
@keenondrums aside from transferring and adjusting jsdocs I'm done in regard to what I've aimed for.

I'll continue updating the docs, but I'd really appreciate if you could spare some time to give these a look.

A rationale and summary of changes:

## Motivation
* Reduce the need for type annotations in client code, making it as close to JS counterpart as possible, while retaining static type checking, 
* Update declarations to comply with redux-orm@0.13.3 code base

## Major braking changes
* different type parameters on `Model` classes:
 * Models specification consists of two parameters - `typeof Model` extending class and an interface specifying fields on session bound Model instances
 * Model fields are provided as single interface, real/virtual grouping is automatic, based on static fields property on Model class, values of properties are limited to QuerySet's, Models and serializable structures 
 * `QuerySet` type parameters consist of a Model type and additional serializable properties object, used for instance/lookup specific cases

## Features
* major reduction of necessary type annotations - providing type parameters to `Model` classes and a tuple of `typeof Model` entries on `ORM` instantiation is generally enough to achieve all round type checking
* support for many to many `QuerySet` extensions (`add, remove, clear`) 
* support for configurable id property keys, automatically inferred from static Model.options property
* support for non-string identifier properties, automatically inferred and propagated to `getId, ref`, bound models, queries etc.
* `Session` instances returned by `ORM.session(...)` are extended with `{[K in modelName's]: typeof Model}` properties, where each property value has members narrowed to relevant Model type (via `ModelType` interface)
* fields of `Model` type on field specifying interfaces become `SessionBoundModel` when accessed through session/static creators. `SessionBoundModel`s are extended with relevant fields
* type checking of `Model.create|upsert|update` methods, supporting providing relations as ids or as models
* support for additional properties on Model instances, inferred from lookup args or `Model.create/update/upsert` args
* Inference of ORM state branch type based on registered Models (via `TableState`)

## Misc
* removed multiple references to internals / private code
* declarations split across multiple files 
* updated various function and method arguments and return types to match redux-orm@0.13.3

**Comment by tomasz-zablocki** [comment]
@keenondrums I've transferred and tweaked crucial doc comments and added documentation for important mapped types. I've also extended the test specs to cover added/modified bits. It's review ready now.

**Comment by tomasz-zablocki** [comment]
I have an additional batch of test cases and ORM docs ready, but I'll refrain from pushing until [utility-types](https://github.com/microsoft/types-publisher/pull/620) are whitelisted.

I've replaced helpers.d.ts with utility-types dependency due to [Publishing guidelines](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), specifically this section:

> **Packaging dependent declarations**
>
> If your type definitions depend on another package:
> 
> * Don’t combine it with yours, keep each in their own file.
> * Don’t copy the declarations in your package either.
> * Do depend on the npm type declaration package if it doesn’t package its declaration files.

In case the [types-publisher PR](https://github.com/microsoft/types-publisher/pull/620) won't get merged, I'll revert my helpers back.

**Comment by tomasz-zablocki** [comment]
@keenondrums It's done.

I'll be updating this code in future, mostly with test cases and optimizations to types, to cut on the autocompletion times, but I'll leave for review as it is. Shall I squash the PR contents or should I leave the history the way it is now ?

**Comment by keenondrums** [comment]
@tomasz-zablocki thank you! I'll try to review today. Go ahead and squash.

**Comment by tomasz-zablocki** [comment]
@keenondrums the code is squashed, thank you for the review and all the advice along the way.

**Review by fxlrnrpt — APPROVED** [review]

**Comment by keenondrums** [comment]
@tomasz-zablocki thank you for your work!

**Comment by tomasz-zablocki** [comment]
@keenondrums thank you - I still have this "Revision needed" label on my PR, will it get cleared automatically, or do I have to address something I haven't considered ?

**Pull request merged**
