### PR TITLE
Making `setControllerName` second argument optional

### PR DESCRIPTION
**Pull request by mboudreau**
Second argument `action` is optional as stated by the description above and the [newrelic docs](https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api/#controller).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by BrooksPatton — APPROVED** [review]
This change looks good to me

**Comment by mboudreau** [comment]
ready to merge.

**Comment by mboudreau** [comment]
@BrooksPatton is there a way for you to open this again and merge it?  Sorry, this must have slipped through in my inbox.

**Comment by BrooksPatton** [comment]
I seem to only be able to comment so I can't help.

**Comment by mboudreau** [comment]
Maybe one of the admins can help?

@RyanCavanaugh @Steve-Fenton @peterblazejewicz @DanielRosenwasser

**Pull request closed without merging**
