### PR TITLE
[happo-cypress]: wildcard version of cypress

### PR DESCRIPTION
**Pull request by havenchyk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by orta** [comment]
This PR could probably do with an explanation about why you want to make this change

**Comment by havenchyk** [comment]
@orta Sure thing, cypress released a couple of versions already since 6.9.1 which is hardcoded as a dependency in this package. So even if I use cypress 7 or 8, this package will install cypress@6.9.1 to my `node_modules`

**Comment by elibarzilay** [comment]
It sounds like just bumping the version is better, at least specifying the major version...?

**Comment by andrewbranch** [comment]
@havenchyk the issue is that these typings haven’t been properly updated in a long time. happo-cypress is now on version 3.0.0 and depends on cypress@^8.5.0, but these typings were written for happo-cypress 1.17, which depended on cypress@^5.0.0. So if you’re trying to use these typings with happo-cypress major versions 2 or 3, you’re going to have a bad time regardless. This PR is a small band-aid that will just reveal the next papercut as soon as it ships. Someone needs to give these typings a proper update, including bumping the cypress dependency version to ^8.5.0.

**Comment by havenchyk** [comment]
@andrewbranch thanks for looking into it. The only part we use from cypress dependency is extending cypress Chainable

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/happo-cypress/index.d.ts#L27-L34

happo-cypress was bumped because of rewritten internals and CLI command which has nothing to deal with typings.

So I just wanted to skip unnecessary install of the second package of cypress in my node_modules with this (maybe having "^6.9 || ^7 || ^8" is a better line for this

**Comment by andrewbranch** [comment]
If there’s really no update to the typings, then yeah, we can reopen this PR with

- Bumping the version in the header comment of index.d.ts to the latest
- Replacing the cypress dependency with a version string that accurately describes the cypress versions compatible with happo-cypress 3.0

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## happo-cypress ([<kbd>unpkg</kbd>](https://unpkg.com/browse/happo-cypress@latest/))
was missing the following properties:
1. configure
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eb4a48aa3c909eb420aa734c8f5326f0a2d76754
</p>

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Just waiting on a more specific version string and bumping the version in the header comment in index.d.ts

**Pull request closed without merging**
