### PR TITLE
Remove reachable files from OTHER_FILES.txt

### PR DESCRIPTION
**Pull request by jablko**
microsoft/types-publisher#767

### CODE REVIEW

**Review by ExE-Boss — APPROVED** [review]
`OTHER_FILES.txt` should never have been added to `@types/globalthis` in the first place.

---

Also, it seems like `types/openfin/_v2/api/application/application.d.ts` is still untested.

**Comment by jablko** [comment]
> Also, it seems like `types/openfin/_v2/api/application/application.d.ts` is still untested.

microsoft/types-publisher#767 is an attempt to address that: If it is accepted then the automated tests should start passing.

**Comment by tomer-openfin** [comment]
`types/openfin/_v2/api/application/application.d.ts` is the first namespace tested in `types/openfin/openfin-tests.ts`

**Review by ljharb — APPROVED** [review]

**Comment by jablko** [comment]
@sandersn Thanks for merging microsoft/DefinitelyTyped-tools#95 and releasing [@definitelytyped/definitions-parser v0.0.57](https://github.com/microsoft/DefinitelyTyped-tools/commit/313dd241acdb9bf7c9f5abbddabdf0bc381b1b0b). This PR is now ready to merge?

**Comment by sandersn** [comment]
The latest version of dtslint [just deployed 5 minutes ago](https://github.com/microsoft/dtslint/actions/runs/272783398), so this PR should be ready to go now.

**Comment by sandersn** [comment]
looks like there are some new files that need to be removed now

**Comment by jablko** [comment]
:thinking: It's passing locally ... Any chance the action isn't using v0.0.57?

**Comment by jablko** [comment]
`types/markedjs__html-differ/OTHER_FILES.txt` doesn't exist in HEAD or this change so where's that error coming from ... Does the action not test the merged commit?

**Comment by jablko** [comment]
It says it's [testing the merge commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44092/checks?check_run_id=1167026962#step:2:30) but the following doesn't contain `types/markedjs__html-differ/OTHER_FILES.txt` so ... hmm ...
```Shell
git fetch upstream pull/44092/merge
git show FETCH_HEAD:types/markedjs__html-differ/OTHER_FILES.txt
fatal: path 'types/markedjs__html-differ/OTHER_FILES.txt' does not exist in 'FETCH_HEAD'
```

@sandersn Would you mind triggering the action again? See if the SHA it's testing is now the same as mine locally ...

**Comment by jablko** [comment]
@sandersn Ohh, I bet it's this syntax `+21210d28c1fbf96e8acac06516fb3d000e548058:refs/remotes/pull/44092/merge` which is coming from the event payload that triggered the action, which, if it's being re-run, is from 29 days ago, before `types/markedjs__html-differ/OTHER_FILES.txt` was removed in #47767. So we need to trigger the action with a new event. Or merge this as is?

**Comment by sandersn** [comment]
Can you merge from master? That should fix it.

**Comment by sandersn** [comment]
OK, got a merge in.

**Comment by sandersn** [comment]
Hm, still broken, but master is broken too, so I think it's the new `@definitelytyped` code.

**Comment by jablko** [comment]
Oh good. I think everything's :+1: now? This is in, master is passing, thanks @sandersn!

**Comment by sandersn** [comment]
Yep, I just confused myself on a local run where I forgot to update `@definitelytyped/*`.

**Pull request merged**
