### PR TITLE
dockerode: Add Health to ContainerInspectInfo.State

### PR DESCRIPTION
**Pull request by cristianrgreco**
https://docs.docker.com/engine/api/v1.40/#operation/ContainerInspect

### CODE REVIEW

**Review by CameronDiver — APPROVED** [review]
Documentation here: https://docs.docker.com/engine/api/v1.40/#operation/ContainerInspect

There's also `FailingStreak` and `Log` in this object, if you wanted to add them.

**Comment by thegecko** [comment]
@cristianrgreco Can you reference where this is documented? Ideally by completing the PR template.

**Comment by cristianrgreco** [comment]
@thegecko https://docs.docker.com/engine/api/v1.40/#operation/ContainerInspect

**Review by thegecko — APPROVED** [review]
Lgtm

**Pull request merged**
