### PR TITLE
Add alias for 'plotly.js/lib/core' submodule

### PR DESCRIPTION
**Pull request by gnestor**
This provides type definitions for ‘plotly.js/lib/core’ which users of webpack depend on

### CODE REVIEW

**Comment by gnestor** [comment]
I fixed the build error 👌 

This is a minor change that allows users of webpack to import `plotly.js/lib/core` and still have Typescript declarations.

**Comment by RyanCavanaugh** [comment]
@gnestor Please fix the failures indicated in the Travis CI log.

**Comment by andy-ms** [comment]
This appears to actually change the types in addition to moving them into a new file. For example, there is no `PlotlyStatic` in the original definitions. Can you elaborate on the changes being made here?
CC authors @chrisgervang @martinduparc @frederikaalund @taoqf

**Comment by taoqf** [comment]
@gnestor It seems that's no need to add a submodule with webpack,if you do need this, try `alias`
```ts
import * as Plotly from 'plotly.js';
// or
import { ScatterData, Layout, PlotlyHTMLElement, newPlot } from 'plotly.js';
```
gulpfile.js
``` js
gulp.task('your task', () => {
	const dest = './dist/';
	const filename = 'generagedfile.js';
	const ws = require('webpack-stream');
	const webpack = require('webpack');
	return gulp.src(['./src/sourcefile.js'])
		.pipe(ws({
			resolve: {
				alias: {
					'plotly.js': '../node_modules/plotly.js/lib/core.js'
				}
			},
			output: {
				filename: filename,
			}
		}, webpack))
		.pipe(gulp.dest(dest));
})
```

**Comment by gnestor** [comment]
Hi @andy-ms . It looks like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17974 was merged since this was submitted. I upgraded and it has resolved my issues regarding webpack and importing `plotly.js` directly. 

@taoqf Unfortunately, jupyterlab manages the bundling of packages so I don't have control of the webpack config.

I am going to close this...

**Pull request closed without merging**
