### PR TITLE
Removed spotify-web-api-js from types-2.0

### PR DESCRIPTION
**Pull request by skovmand**
Remove the type definition for spotify-web-api-js because it is now integrated in the package. The removal of the typings from master were here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12145

### CODE REVIEW

**Comment by vvakame** [comment]
could you update `notNeededPackages.json` too?

**Comment by skovmand** [comment]
Yep. Done.

**Comment by vvakame** [comment]
LGTM.
@andy-ms could you review this change?

**Review by vvakame — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by andy-ms** [comment]
Thanks a lot for integrating your typings! FYI, the definition header has no meaning to the TypeScript compiler, so only packages on DefinitelyTyped need it.

**Pull request merged**
