### PR TITLE
Added allowed properties on the Telegram API to EditMessageCaptionOption

### PR DESCRIPTION
**Pull request by andezdev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

### CODE REVIEW

**Comment by toniop99** [comment]
Hi! This is my first PR and I am not sure if I have done it correctly. I have not touched the tests because it is not a significant change, I have only followed the telegram api for that method. If I have to modify something to do it correctly I will be happy to do it.

@ammuench @Agadar @Dabolus @Kallu609 @XC-Zhang @adityathebe @MiklerGM @ariutin @XieJiSS

**Comment by rbuckton** [comment]
Can you please provide a link to documentation or source that shows how this is defined or where this is used?

**Comment by toniop99** [comment]
> Can you please provide a link to documentation or source that shows how this is defined or where this is used?

[https://core.telegram.org/bots/api#editmessagecaption](url)
[https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+editMessageCaption](url)

```typescript
const bot = new TelegramBot(TOKEN);
const fakeChatId = 1923813;
const fakeMessageToEditId = 654;

bot.editMessageCaption(
        `<b>Editing message caption</b>`,
        {
          chat_id: fakeChatId ,
          message_id: fakeMessageToEditId ,
          parse_mode: 'HTML'
        });
```

**Review by rbuckton — APPROVED** [review]

**Comment by toniop99** [comment]
Ready to merge

**Pull request merged**
