### PR TITLE
@types/ramda:  support partial record in mapIndexedObj

### PR DESCRIPTION
**Pull request by wclr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by whitecolor** [comment]
Seems linting error 
The 'no-redundant-jsdoc-2' rule threw an error in '/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/ramda/tools.d.ts'

doesn't refer to this PR

**Comment by Nicholaiii** [comment]
There's also linting errors in your commits though:
```
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/ramda/test/mapObjIndexed-tests.ts:55:48
ERROR: 55:48  no-trailing-whitespace  trailing whitespace
ERROR: 88:49  no-trailing-whitespace  trailing whitespace
```

Regardlessly, the bot is going to block the PR untill all issues are fixed, so either you wait for some other commit to fix it, or you can change the `@see` to just `See`, which I reckon should fix `Unexpected tag kind: JSDocSeeTag` 

On a second note; when submitting a PR, you are supposed to pick _one_ of three blocks:

1. If adding a new definition:
2. If changing an existing definition:
3. If removing a declaration:

And _remove_ the other two.
Then of course make sure you follow all remaining steps and complete them. This makes it easier for maintainers (like me) to make sure everything is in order. If the step says something like "If..." and it doesn't apply to your case, tick it or remove the line.

**Comment by whitecolor** [comment]
@Nicholaiii ok, fixed the lint error.

**Comment by elibarzilay** [comment]
🔔 @TheHandsomeCoder @donnut @mdekrey @sbking @afharo @teves-castro @1M0reBug @hojberg @samsonkeung @angeloocana @raynerd @moshensky @ethanresnick @deftomat @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh @Krantisinh @pirix-gh @Nemo108 @jituanlin @Philippe-mills @Saul-Mirone @Nicholaiii @devrelm @LORDBABUINO — re-ping

**Comment by Nicholaiii** [comment]
One test failed, you need to push some changes to make it retry.
Also it seems you've used 4 spaces indendation, the rest of the project uses 2, so if you can make that change, the build should retry and we can merge it

**Comment by whitecolor** [comment]
> 4 spaces indendation, the rest of the project uses 2

VS code uses repo root prettier config in .prettierrc.json, why not support it?

**Comment by Nicholaiii** [comment]
Look in the checks. There's a failing build. 
Because I'm a package maintainer, not projectwide, I can't run the build manually, but any change will re-trigger it. Regardlessly, the formatting is not really up to me, I just noticed it was different from the rest of @types/ramda and suggested it as a potential edit so the build can re-trigger and we can merge it. I don't care what happens personally.

**Comment by whitecolor** [comment]
Wow, it seems all pass, I didn't change the formatting (because didn't figure out how to make in vscode). And prettier config says to use 4 spaces for indentation.

**Review by Nicholaiii — APPROVED** [review]

**Comment by Nicholaiii** [comment]
Ready to merge

**Pull request merged**
