### PR TITLE
[ramda] Update slice type

### PR DESCRIPTION
**Pull request by jeean**
I'm trying to use slice like this code.
```ts
import { pipe, slice } from 'ramda';

// slice => (list: string): string;
function testMethod1(text: string) {
  return pipe(
    slice(0, 7)
  )(text);
  // Error : Argument of type 'string' is not assignable to parameter of type 'readonly unknown[]'.ts(2345)
}

// slice => <T>(list: readonly T[]): T[];
function testMethod2(texts: string[]) {
  const sliceMethod = slice(0, 7)

  return pipe(
    (texts: string[]) => sliceMethod<string>(texts),
  )(texts);
}
```
I get ts(2345) error because type of slice inside `testMethod1` trying to use `<T>(list: readonly T[]): T[];` instead of `(list: string): string;`.
Above error is gone when I change `<T>(list: readonly T[]): T[];` type to precde `(list: string): string;` type.
(It seems that the order of types affects type inferring)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by Nicholaiii** [comment]
Any chance that you can update tests to reflect the changes?

**Comment by jeean** [comment]
> Any chance that you can update tests to reflect the changes?

I updated test code for slice. Can you give me some advice on the test code?

**Comment by Nicholaiii** [comment]
> 
> 
> > Any chance that you can update tests to reflect the changes?
> 
> I updated test code for slice. Can you give me some advice on the test code?

These do look fine for the issue you're solving; it would be nice to also have plain tests of slice that document that the generic version still works.

**Review by Nicholaiii — APPROVED** [review]

**Comment by jeean** [comment]
Ready to merge

**Pull request merged**
