### PR TITLE
swagger-schema-official: fixing types for exclusiveMinimum and exclusiveMaximum in BaseSchema

### PR DESCRIPTION
**Pull request by mauriedo**
Happy to chat about how to release this one, I can understand this might break people if they were relying on the wrong types for `exclusiveMinimum` and `exclusiveMaximum`.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
-- https://swagger.io/specification/v2/#parameterObject
-- https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.1.2
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mauriedo** [comment]
I'd rather not have this merged as of yet, keen to understand if this change is worth of a major version release and how do I have to do this. Cheers.

**Comment by uniqueiniquity** [comment]
@mauriedo Was the `number` type for those properties ever correct (i.e. in an earlier version of the spec)?

**Comment by mauriedo** [comment]
@uniqueiniquity I don't think so no, these properties become a `number` in the newest version of JSON Schema, but that's not the one being used here and I don't expect that to change. That's where I think this confusion comes from.

**Comment by uniqueiniquity** [comment]
I see. This is just a minor fix, then. Even though it might break people, you are changing it from an incorrect value to a correct one.

**Comment by mauriedo** [comment]
Thanks @uniqueiniquity :)

**Pull request merged**
