### PR TITLE
New type definitions and update

### PR DESCRIPTION
**Pull request by remojansen**
## New

deep-equal
redux-immutable-state-invariant
## Update

react-router-redux

### CODE REVIEW

**Comment by oizie** [comment]
It's working fine for me. I need this too. Thanks

**Comment by rosendi** [comment]
I'll check it tomorrow.

**Comment by rosendi** [comment]
@remojansen I have to create a single PR for each package. Please, take a look at this PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8231

**Comment by remojansen** [comment]
Hi @rosendi thanks for the comments the other pull request eliminates the need for my update.

I have create two PRs for the other two type definitions:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8362
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8363

**Pull request closed without merging**
