### PR TITLE
Restore type definitions needed by core-js and revert tsconfig lib hack.

### PR DESCRIPTION
**Pull request by navels**
As an ES6+ polyfill, the core-js typings should include the type definitions it needs, rather than rely on consumers to configure the typescript compiler to provide them.  This addresses [15140](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15140)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [15140](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15140)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
@andy-ms @rbuckton can you take a look at this? I don't want to modify an important package without understanding the issue?

**Comment by andy-ms** [comment]
We can't know that consumers will have `--lib es6` set, but we also can't know that they don't, and if they do, they can get compile errors if there is a slight difference between the builtin libs and the ones copied to here.

Microsoft/TypeScript#15780 was designed for this kind of situation. That would add `/// <reference lib="es6" />` to the file to pull in the ES6 typings that come with the user's version of typescript, so there are no possible duplicate definitions. @rbuckton is unavailable for the next few days but he would be the one to know about the status of this.

**Comment by weswigham** [comment]
@rbuckton what do you want to do with this?

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by sandersn** [comment]
This change shouldn't be merged until the new `lib` triple-slash reference feature is in Typescript. @rbuckton is working on that feature right now and it should be done soon-ish.

**Comment by minestarks** [comment]
@sandersn 

> This change shouldn't be merged until the new lib triple-slash reference feature is in Typescript. 

Any update on that?

**Comment by sandersn** [comment]
@rbuckton is the author of the feature. Ron?

**Comment by paulvanbrenk** [comment]
pinging @rbuckton once again

**Review by mhegazy — CHANGES_REQUESTED** [review]
The correct fix here is on the TS compiler side with https://github.com/Microsoft/TypeScript/pull/15780. A change we make here will just cause a lot of churn to exiting users of the library, with no much value, it just changes the problem from having to define `--lib` to making sure you never define a `--lib` if you are using core-js. I would rather we do not keep flip-flopping on this, and wait for a proper fix on the TS side.
For that i do believe we should **not** merge this PR.

**Pull request closed without merging**
