### PR TITLE
@types/highcharts: Highcharts.ganttChart() support. Initial types for basic gantt chart.

### PR DESCRIPTION
**Pull request by jgresham**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.highcharts.com/docs/gantt/getting-started-gantt 
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This adds support for a basic gantt chart from the Highcharts Gantt module.

### CODE REVIEW

**Review by meisamBalanian — APPROVED** [review]

**Comment by jgresham** [comment]
Any update or changes needed? Why is this on hold?

**Comment by jgresham** [comment]
@meisamBalanian @sandersn Is there anything I can do to help speed up this pull-request? Please let me know!

**Comment by sandersn** [comment]
@jgresham You can contact (or ping again) the owners and get them to sign off. That puts it immediately into the Check and Merge state instead of Other, which is where it is now. Otherwise a maintainer will eventually get to the Other column to merge it.

**Review by hanssens — APPROVED** [review]

**Comment by jgresham** [comment]
Thank you @sandersn  & @hanssens!

**Pull request merged**
