### PR TITLE
Add option "fallback" to @types/slug

### PR DESCRIPTION
**Pull request by danielclausmeyer**
Please fill in this template.

- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Trott/slug/blob/main/README.md

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/slug/slug-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3cb026e85c37aa55e52e7b712a228e35e054e72d
</p>

**Comment by andriinuts** [comment]
@mhegazy can you please have a look at this small fix of types?

**Comment by andriinuts** [comment]
@typescript-bot please assign another reviewer

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
@danielclausmeyer I recommend removing mhegazy and adding yourself to the owner list. He doesn't work on Typescript anymore.

**Pull request merged**
