### PR TITLE
[readable-stream] fix compatibility with NodeJS Streams

### PR DESCRIPTION
**Pull request by JMounier**
## TODO
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test readable-stream`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57038
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header: It updates the library's type declaration to match the new version of NodeJS

## What

readable-stream:
- Add EventEmitter properties from node >= 10: These properties are inherited without updating the library
- Use `never` type for Stream properties introduced in node > 10: Make `readable-stream` types compatible with new Node Stream while showing they are not implemented yet.
- Fix `pipe()` definition: Use a Writable interface to hide `readable-stream` implementation details
- Add `pipe()` property to the `Readable` class

duplex-to:
- use NodeJS Streams as destination type in `duplex-to` tests

### CODE REVIEW

**Review by tpluscode — COMMENTED** [review]
+1 on the duplex-to part

Does this bring the types in line with v3 of readable-stream? Might update the version finally

**Comment by JMounier** [comment]
@tpluscode I'm not 100% sure. Looking at [`readable-stream`'s changelog](https://github.com/nodejs/readable-stream/releases?page=2), version 3 only adds compatibility to node 10. I don't known why the version was not updated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45563 or a previous pr.

On the one hand, the [initial type declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31805) for `readable-stream` in `DefinitlyTyped` was done after [v3.0.0](https://github.com/nodejs/readable-stream/releases/tag/v3.0.0) was released and the current type declaration works with node 10.

On the other hand, the type declaration seem to have evolved to keep compatibility with new node versions instead of keeping track of the implementation (hence the static `from()` property in `Duplex` not defined by `readable-stream`).

IMHO, this package needs more investigation to differentiate properties:
- present in both type and implementation
- present in type only (for node compatibility)
- present in implementation only (type not up-to-date)

**Comment by ssm951** [comment]
Thanks for making this PR! That will fix my issue of being unable to call pipe() on a stream. What else needs to be done to merge this PR @tpluscode?

**Comment by tpluscode** [comment]
@ssm951 well, I only authored `@types/duplex-to`. Never really looked into `readable-stream`

**Comment by JMounier** [comment]
The PR is waiting for reviews on the `readable-stream` part by one of its maintainer (@TeamworkGuy2 or @markdreyer)

**Review by markdreyer — APPROVED** [review]
👍

**Comment by JMounier** [comment]
Ready to merge

**Pull request merged**
