### PR TITLE
React-Sortable-Hoc : Added the shouldCancelStart function

### PR DESCRIPTION
**Pull request by charlesrey**
To the SortableContainer props definition.

See :
<https://github.com/clauderic/react-sortable-hoc/issues/186#issuecomment-293954934>

### CODE REVIEW

**Comment by charlesrey** [comment]
Hi,

Our team need this correction so we can keep going, I'm not an experienced Github user so I,m asking, do someone knows how long a PRs waits to be reviewed ?

Many thanks for your help,

Charles

**Review by NoHomey — APPROVED** [review]

**Comment by NoHomey** [comment]
I'm sorry for seeing it after two weeks ..., my apologies.

**Comment by NoHomey** [comment]
LGTM :+1:

**Comment by charlesrey** [comment]
@NoHomey : No problems thanks for your quick response

**Pull request merged**
