### PR TITLE
[mongoose] find* lean option type

### PR DESCRIPTION
**Pull request by avaly**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mongoosejs.com/docs/api.html#query_Query-setOptions
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by oktapodia — CHANGES_REQUESTED** [review]
Happy with the changes on mongoose, however, can you please revert the changes on other libraries? That can have side effects we may not anticipate

**Comment by avaly** [comment]
@oktapodia Unfortunately, the new changes throws lint errors in TS 3.0 and 3.1, so I had to upgrade to 3.2. So all dependent packages also need the 3.2 bump.

**Comment by sandersn** [comment]
@oktapodia, can you take another look? It looks like @avaly found a way to revert changes to the other packages.

**Review by oktapodia — APPROVED** [review]
LGTM

**Comment by esetnik** [comment]
@avaly I am seeing a typescript error with the latest definition.

example:
```
  const callCountRateLimit: any = await RateLimit.findOne(
    { service: 'FACEBOOK', type: 'appLevelCallCountRateLimit' },
    {},
    { sort: { createdAt: -1 } }
  ).exec();
```

```
[tsserver 2769] [E] No overload matches this call.
  Overload 1 of 4, '(conditions: MongooseFilterQuery<Pick<IRateLimitModel, "_id" | "service" | "type" | "accountId" | "utilizedPercent" | "createdAt">>, projection: any, callback?: ((err: any, res: IRateLimitModel | null) => void) | undefined): DocumentQuery<...>', gave the following error.
    Argument of type '{ sort: { createdAt: number; }; }' is not assignable to parameter of type '(err: any, res: IRateLimitModel | null) => void'.
      Object literal may only specify known properties, and 'sort' does not exist in type '(err: any, res: IRateLimitModel | null) => void'.
  Overload 2 of 4, '(conditions: MongooseFilterQuery<Pick<IRateLimitModel, "_id" | "service" | "type" | "accountId" | "utilizedPercent" | "createdAt">>, projection: any, options: { ...; } & Pick<...>, callback?: ((err: any, res: IRateLimitModel | null) => void) | undefined): Query<...>', gave the following error.
    Argument of type '{ sort: { createdAt: number; }; }' is not assignable to parameter of type '{ lean: true; } & Pick<QueryFindBaseOptions, "populate" | "collation" | "explain" | "projection" | "session">'.
      Object literal may only specify known properties, and 'sort' does not exist in type '{ lean: true; } & Pick<QueryFindBaseOptions, "populate" | "collation" | "explain" | "projection" | "session">'.
  Overload 3 of 4, '(conditions: MongooseFilterQuery<Pick<IRateLimitModel, "_id" | "service" | "type" | "accountId" | "utilizedPercent" | "createdAt">>, projection: any, options: QueryFindBaseOptions, callback?: ((err: any, res: IRateLimitModel | null) => void) | undefined): DocumentQuery<...>', gave the following error.
    Argument of type '{ sort: { createdAt: number; }; }' is not assignable to parameter of type 'QueryFindBaseOptions'.
      Object literal may only specify known properties, and 'sort' does not exist in type 'QueryFindBaseOptions'.
```
I believe these definition should be using `QueryFindOptions` not `QueryFindBaseOptions`.

```
    /**
     * Finds one document.
     * The conditions are cast to their respective SchemaTypes before the command is sent.
     * @param projection optional fields to return
     */
    findOne(conditions?: FilterQuery<T>,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T, QueryHelpers> & QueryHelpers;
    findOne(conditions: FilterQuery<T>, projection: any,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T, QueryHelpers> & QueryHelpers;
    findOne(conditions: FilterQuery<T>, projection: any, options: { lean: true } & Omit<QueryFindBaseOptions, 'lean'>,
      callback?: (err: any, res: T | null) => void): Query<DocumentDefinition<T>> & QueryHelpers;
    findOne(conditions: FilterQuery<T>, projection: any, options: QueryFindBaseOptions,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T, QueryHelpers> & QueryHelpers;
```

**Pull request merged**
