### PR TITLE
[@types/jest]: bump dependencies to v26

### PR DESCRIPTION
**Pull request by L2jLiga**
Jest v26 requires TS 3.8+ (see https://github.com/facebook/jest/pull/9823).

## Changed
- updated dependencies
- merged typings from `index.d.ts` and `ts3.1/index.d.ts`
- removed `ts3.1`
- set minimum TypeScript version to 3.8

## Checklist
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/jest/pull/9823
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by L2jLiga** [comment]
Closing this for now, have to check `expect-puppeteer` types and find workaround for `Expect.addSnapshotSerializer` and `MatcherUtils.utils.diff`

**Comment by G-Rath** [comment]
I guess this means we're locked in to the old dependencies until 2022 😬

**Comment by L2jLiga** [comment]
We can bump minimal TS version everywhere to 3.8..

**Comment by G-Rath** [comment]
I don't mind doing that if it's ok with DT - I think it's fair to say that while DT doesn't drop support for <3.8 until 2022, `@types/jest` & co can drop it now as it's matching the min supported by `jest`.

**Pull request closed without merging**
