### PR TITLE
[mithril] Add missing route parameter to routeresolver's onmatch

### PR DESCRIPTION
**Pull request by joakimbeng**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/MithrilJS/mithril.js/blob/9f0dc2ab4692a65539accfe591cdeac2f592f34b/api/router.js#L111
(and its docs: https://mithril.js.org/route.html#routeresolveronmatch )
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mithril ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mithril@latest/))
was missing the following properties:
1. m
1. vnode
1. PromisePolyfill
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 769047beb0fde6b2a341c6d53112a9d643d76d55
</p>

**Review by dead-claudia — CHANGES_REQUESTED** [review]
Please remove all those whitespace changes. I can't readily find your change through all of that.

**Comment by joakimbeng** [comment]
@isiahmeadows that's why I split it into two commits 🙂 The first one is the actual change.

(I followed the instructions in the Readme regarding Prettier, so maybe that should be changed in case you don't want contributors to improve the overall "prettiness" of the code base when contributing)

**Review by dead-claudia — APPROVED** [review]

**Comment by isiahmeadows** [comment]
Okay, didn't catch that. Sorry!

Approved.

**Comment by isiahmeadows** [comment]
Ready to merge

**Pull request merged**
