### PR TITLE
sequelize - Added 'charset' at constructor options

### PR DESCRIPTION
**Pull request by drosi94**
Added charset variable to Options of Sequelize Constructor.

More information [here](http://docs.sequelizejs.com/en/latest/api/sequelize/)
#16069

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@drosi94 Please edit the description according to guidelines so that there is more information on why and what you are trying to fix.
Thank you

**Comment by drinchev** [comment]
Shouldn't this be in the `DefineOptions` interface ?

**Comment by mhegazy** [comment]
@drosi94 can you please respond to @drinchev's comment.

**Comment by drosi94** [comment]
@mhegazy It's already at DefineOptions, but 'charset' option is available to constryctor **Options** too.

**Comment by drinchev** [comment]
I can't see where `charset` option is in the constructor.

https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/sequelize.js#L55

As far as I can see in the code there isn't any. How did you decide that it should be there?

**Comment by aozgaa** [comment]
Unfortunately, it's impractical for the maintainers to consider PR's where the template hasn't been filled out. Please re-open the PR, filling out the template.

**Pull request closed without merging**
