### PR TITLE
[Ember__Test-Helpers] Update Target type to include Document type

### PR DESCRIPTION
**Pull request by eramod**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget The Document is a valid event target. Perhaps Window should be added to the Target type as well? 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by domdomegg** [comment]
Ember's docs say the type should be `string | Element`:

https://github.com/emberjs/ember-test-helpers/blob/master/API.md

Concerned that this would be defining an interface outside of their specified API docs. Could we try to update those docs first and see what emberjs say?

**Comment by chriskrycho** [comment]
For what it’s worth, the implementation (now authored in TS, but not yet publishing types) [defines exactly this override][src], so an upstream change to docs should be accepted. (Also, hopefully we can get it publishing types itself soon!)

[src]: https://github.com/emberjs/ember-test-helpers/blob/880272edf6475ddd05f2c2c2e39efb7db9cf2578/addon-test-support/%40ember/test-helpers/dom/-get-element.ts#L6

**Comment by chriskrycho** [comment]
@eramod do you mind opening a PR against Ember’s docs? I’ll happily give this a sign-off once we have the docs PR accepted.

**Comment by eramod** [comment]
> @eramod do you mind opening a PR against Ember’s docs? I’ll happily give this a sign-off once we have the docs PR accepted.

@chriskrycho Will do.

**Comment by eramod** [comment]
@chriskrycho https://github.com/emberjs/ember-test-helpers/pull/1103

**Comment by chriskrycho** [comment]
Thank you! Let me know once it’s merged!

**Review by domdomegg — APPROVED** [review]

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Marking this as "Request Changes" to prevent auto-merge until the Ember docs folks merge the blocking commit. (I'll give them a nudge if I don't see a response on that issue soon, @eramod!)

**Review by chriskrycho — APPROVED** [review]
It's not clear to me when the docs are going to get merged, but this is correct so I'm unblocking it.

**Comment by chriskrycho** [comment]
Ready to merge

**Pull request merged**
