### PR TITLE
Added @types/react-animations

### PR DESCRIPTION
**Pull request by mcbattirola**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
quick question, the native package use concepts of composed Keyframes of Animations. So there are `Keyframe` and `Animation` types there. why is this not reflected here, instead placating types with CSS props?

**Comment by mcbattirola** [comment]
I was following the way Styled Components does things, but your message made me realize it's much better to declare the types just like the original package does.

I'll update the PR with the types `Keyframe` and `Animation`

Thanks @peterblazejewicz

**Review by peterblazejewicz — COMMENTED** [review]
Please remove `packagejson`, which serves no purpose now, thx!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mcbattirola thx!

**Comment by mcbattirola** [comment]
Ready to merge

Thank you very much @peterblazejewicz !

**Comment by mcbattirola** [comment]
Ready to merge

**Pull request merged**
