### PR TITLE
Add Electron definitions

### PR DESCRIPTION
**Pull request by jednano**
Definitions for [Electron](http://electron.atom.io/), formerly known as Atom Shell.

### CODE REVIEW

**Comment by vvakame** [comment]
cool! but https://www.npmjs.com/package/electron is already exists...
https://www.npmjs.com/package/github-electron is not exists... 
Do you have any good name?

**Comment by jedmao** [comment]
github-electron sounds good. I'll rename everything.

**Comment by jedmao** [comment]
@vvakame everything has been renamed to github-electron.

**Comment by vvakame** [comment]
@jedmao thanks!

**Pull request merged**
