### PR TITLE
[react] fix React.memo TS 2590 Error

### PR DESCRIPTION
**Pull request by colinaaa**
This commit tries to fix a TS 2590 Error("Expression produces a union type that is too complex to represent.") when using `React.memo` and `React.lazy`.

The error happens if a `IntrinsicElements` with rather complex props is defined.
See [codesandbox] for a complete example.

The fix replaces `ComponentPropsWithRef` with `CustomComponentPropsWithRef` which will never deal with
`IntrinsicElements`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [codesandbox]

[codesandbox]: https://codesandbox.io/s/immutable-sky-jchfxn?file=/src/App.tsx

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c0e74d96717876d6fc2f4b64accdeb94d3dbe4e7
</p>

**Comment by eps1lon** [comment]
Sorry I've been sleeping on this one. I've reordered the declaration a bit to make it clearer how it relates to `ComponentPropsWithRef`.

**Comment by andrewbranch** [comment]
@eps1lon do your commits constitute an approval? 🙂

**Review by eps1lon — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
