### PR TITLE
[node] bump inspector types for V8 6.1

### PR DESCRIPTION
**Pull request by kjin**
A few new types for Node 8.7+; these are automatically generated by running `ts-node scripts/generate-inspector v8.8.0` in `types/node`

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/commit/d82e1075dbc2cec2d6598ade10c1f43805f690fd#diff-1304fac45f0f71f192e121d23a8afe5c

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@kjin Please fix the failures indicated in the Travis CI log.

**Comment by kjin** [comment]
@RyanCavanaugh I don't expect this to have any impact on whether tests pass. Force-pushing to restart CI.

**Comment by kjin** [comment]
@RyanCavanaugh Looks like the build is timing out like in #21003, which is also a Node PR. Could it be that since everything virtually depends on Node types there's too many dependents to sift through?

**Comment by kjin** [comment]
@andy-ms I saw that you were manually merging PRs with build timeouts. Would you mind taking a look at this one? No urgency; just that this just needs to make it in before Node 9 definitions are forked.

**Pull request merged**
