### PR TITLE
[node-fetch] Add missing AbortError

### PR DESCRIPTION
**Pull request by mlegenhausen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-fetch/node-fetch/blob/main/src/errors/abort-error.js and https://github.com/node-fetch/node-fetch/blob/main/src/index.js#L36

### CODE REVIEW

**Comment by kyranet** [comment]
You have linked the v3 code, which isn't what this `@types/` package covers.

I can't seem to find the relevant export in the v2 branch: https://github.com/node-fetch/node-fetch/blob/2.x/src/index.js, and 2.6.7 has those exports:

```js
<ref *1> [Function: fetch] {
  isRedirect: [Function (anonymous)],
  Promise: [Function: Promise],
  default: [Circular *1],
  Headers: [class Headers],
  Request: [class Request],
  Response: [class Response],
  FetchError: [Function: FetchError]
}
```

**Comment by glasser** [comment]
Agreed that this is not exported in v2, and [its docs](https://github.com/node-fetch/node-fetch/blob/2.x/ERROR-HANDLING.md) encourage you to check its `name` (rather than do an `instanceof` check). Since it is not actually part of the v2 API I don't think it belongs here?

**Comment by kyranet** [comment]
Indeed it doesn't. The PR should be made at the official repository instead.

**Comment by mlegenhausen** [comment]
Thanks for clarification! Seems I was on the wrong branch.

**Pull request closed without merging**
