### PR TITLE
Fix JQueryUi zindex() function to return a number, not a JQuery. 

### PR DESCRIPTION
**Pull request by StuartMoore**
Relevant documentation: https://api.jqueryui.com/zIndex/

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Looks like you've converted the wrong overload? The parameterless returns jquery and the one with a single parameter the number...

**Comment by StuartMoore** [comment]
I believe the documentation to be an error too, and have raised this as a separate bug - https://github.com/jquery/jqueryui.com/issues/146

If you read the text, the parameterless documentation refers to returning the css z-index (which is an integer), or 0 if none is found. Meanwhile the one with a parameter is described as equivalent to .css("zIndex", value) which returns a JQuery - see http://api.jquery.com/css/#css2

**Comment by StuartMoore** [comment]
My change has now been accepted and https://api.jqueryui.com/zIndex/ is updated.

**Comment by johnnyreilly** [comment]
Awesome!🤗

**Pull request merged**
