### PR TITLE
[node] [crypto] Added missing crypto update types

### PR DESCRIPTION
**Pull request by grantila**
* Added DataView as type of crypto update functions

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [cipher](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_cipher_update_data_inputencoding_outputencoding) [decipher](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_decipher_update_data_inputencoding_outputencoding) [hash](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_hash_update_data_inputencoding) [hmac](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_hmac_update_data_inputencoding) [sign](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_sign_update_data_inputencoding) [verify](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_verify_update_data_inputencoding)

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Comment by grantila** [comment]
Held back due to #20308 I suppose...

**Comment by RyanCavanaugh** [comment]
@grantila Please fix the failures indicated in the Travis CI log.

**Comment by grantila** [comment]
@RyanCavanaugh no thanks, please fix #20308 instead... It just became impossible to contribute to this repo. I'm not sure how this is not top priority already... I've done my part.

**Comment by Flarna** [comment]
@grantila I think the CI setup for node has been changed to avoid the timeouts. You could try to merge in master to re-trigger CI.

**Comment by grantila** [comment]
done

**Pull request merged**
