### PR TITLE
[styled-components] Carry over prop generics from attrs

### PR DESCRIPTION
**Pull request by Krisztiaan**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or [source code](https://github.com/styled-components/styled-components/blob/df94ac41323209a2037475e2a491e19e327c7e08/packages/benchmarks/src/implementations/styled-components-v4/styled-components-v4.esm.js#L2279) which provides context for the suggested changes
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

https://github.com/styled-components/styled-components/blob/df94ac41323209a2037475e2a491e19e327c7e08/packages/benchmarks/src/implementations/styled-components-v4/styled-components-v4.esm.js#L2279

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
.attrs does not magically enable additional props. The underlying component still needs to handle them. In your example React will render `<input foo="bar" />` which should definitely error.

Check out  https://styled-components.com/docs/basics#attaching-additional-props to find out what `.attrs` can be used for.

**Comment by Krisztiaan** [comment]
@eps1lon `.attrs` actually ["magically enables additional props"](https://codesandbox.io/s/sweet-sound-8y7qt?file=/src/App.js), as all the [contexts are merged, including `attrs`](https://github.com/styled-components/styled-components/blob/df94ac41323209a2037475e2a491e19e327c7e08/packages/benchmarks/src/implementations/styled-components-v4/styled-components-v4.esm.js#L2279)

A valid use-case for this modification is when you define your `styled-component` the following way:
```tsx
const AnimatedComponent = styled(Animatable)
  .attrs<{ opacity?: number }>(props => ({ isVisible: opacity > 0 }))`
  opacity: ${props => props.opacity}
`
```

This change just eliminates the need to duplicate the above generic declaration in front of the ttl.
```tsx
const AnimatedComponent = styled(Animatable)
  .attrs<{ opacity?: number }>(props => ({ isVisible: opacity > 0 }))<{ opacity?: number }>`
  opacity: ${props => props.opacity}
`
```

**Comment by eps1lon** [comment]
> A valid use-case for this modification is when you define your styled-component the following way:

Please use the actual use case for tests and not generic foo-bar. The test you included should not type-check while the example you posted is probably correct if `Animatable` handles `opacity`.

**Comment by Krisztiaan** [comment]
It doesn't matter if it handles the extra prop, `styled` will pass it anyways. If the wrapped component had the prop, we wouldn't need the generic extension.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 16f9a8d72a36dd07485347ae4fe91d3ca8c119ed
</p>

**Comment by Krisztiaan** [comment]
?

**Comment by sandersn** [comment]
@eps1lon is the test that @Krisztiaan added in 16f9a8d what you were thinking of?

**Comment by Krisztiaan** [comment]
Yeah no, thank you :)

**Pull request closed without merging**
