### PR TITLE
[@types/node] Add missing types for Readable iterator methods

### PR DESCRIPTION
**Pull request by mrbrianevans**
I have added some missing types to the Readable interface for Nodejs streams. These are new methods for iterating readable streams, added in early 2022. Discussion: #60753 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [nodejs.org/api/stream.html](https://nodejs.org/api/stream.html#readablemapfn-options)
- [?] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR is still a work in progress, please give comments or feedback:
 - documentation from nodejs docs. How to document the parameters of `fn` which is itself a parameter?
 - generic typing for Readable class? (I think it should be generically typed, but this might be a big change)
 - should the `options` parameter type be an interface that they all reference (to reduce code duplication)?
 - I still need to write tests for these types (not started yet)
 - I have the common mistake of typing the return value of a function generically, but I think it is appropriate due to the possibility of generifying the Readable class

### CODE REVIEW

**Comment by mrbrianevans** [comment]
Please could someone provide comment on this pull request so we can get it merged

**Comment by tilgovi** [comment]
The tests for stream-to-array are, indeed, incompatible. I would try changing the test to have a separate `interface Stream2 extends stream.Readable {}` that overrides `toArray`. The problem is that these `toArray` functions are incompatible as methods of a stream, so using an intersection type results in `never`.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I'm not sure what the fix should be for readable-stream. We recently shipped v4 which includes these methods too, so maybe it should just be updated as part of this PR?

**Comment by mrbrianevans** [comment]
Please could someone with knowledge of `readable-stream` update the types for v4 as stated above. I am not at all familiar with the library.

**Pull request closed without merging**
