### PR TITLE
Updated types for merge2 v1.1.0

### PR DESCRIPTION
**Pull request by smac89**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/teambition/merge2/blob/master/index.js#L96>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by smac89** [comment]
Hey can we merge this? It does not seem that the original author will be able to respond to this

**Comment by andy-ms** [comment]
Hi, since this is a new major-version release, could you add `types/merge2/tslint.json` containing `{ "extends": "dtslint/dt.json" }`?

**Review by tkrotoff — APPROVED** [review]

**Comment by sheetalkamat** [comment]
smac89 As @andy-ms mentioned before, please ad tslint.json.

**Comment by sheetalkamat** [comment]
@smac89  Please fix the test failures. Thanks

**Pull request merged**
