### PR TITLE
Add missing promises version for MemoryCookieStore to tough-cookie

### PR DESCRIPTION
**Pull request by utyfua**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
- - [fromCallback set promises](https://github.com/salesforce/tough-cookie/blob/2921fbdfe11e310b1b0835b4d050575578b4b2c3/lib/memstore.js#L179)
- - [optional allowSpecialUseDomain](https://github.com/salesforce/tough-cookie/blob/2921fbdfe11e310b1b0835b4d050575578b4b2c3/lib/memstore.js#L65)
- - Infinity expires: 
- - - [doc ref](https://github.com/salesforce/tough-cookie/blob/2921fbdfe11e310b1b0835b4d050575578b4b2c3/lib/memstore.js#L65): expires - Date - if set, the Expires= attribute of the cookie (defaults to the string "Infinity").
- - - [types above in already exists definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/407fe31012868fd2d0ba26e812bfe9ace80b0644/types/tough-cookie/index.d.ts#L89)

### CODE REVIEW

**Review by amcasey — COMMENTED** [review]
Please confirm that the version doesn't need to be bumped up from 4.0.

**Comment by amcasey** [comment]
LGTM, but I'd like to hear from an owner.

**Review by jakebailey — APPROVED** [review]
LGTM, same thing as `CookieJar` and `"Infinity"` appears to be valid by my reading upstream.

**Comment by utyfua** [comment]
Ready to merge

**Pull request merged**
