### PR TITLE
Updated WebdriverIO API

### PR DESCRIPTION
**Pull request by monolithed**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://webdriver.io/api.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by monolithed** [comment]
@andy-ms, @DanielRosenwasser, Is there anything I can do to speed the merge process along?

**Comment by TonyPythoneer** [comment]
@monolithed You should notify the author @nmalaguti to review this.

**Comment by nmalaguti** [comment]
I haven't been using WebdriverIO much in the last year or so. You may want to reach out to @fsmedberg-tc who has had PRs merged more recently.

**Comment by monolithed** [comment]
This project should be killed! Really, it's pain to spend several expensive days for contributing and wait when somebody merge it.

**Comment by TonyPythoneer** [comment]
@monolithed I don't agree with you! Every contributor or author is just enthusiasm to maintain this typing files. Besides, anyone doesn't owe you anything. Please respect their time whether authors of the typing files or DefinitelyTyped member. 

Let's back to the topic. If I am a contributor, how do I accelerate review and merge PR? The best way is you can explain what you was doing in these changes. Providing the link which directs the source code or document is better. When other contributors review this, they can take less time to understand the changes. Ideally, the PR can get merged fast. See, isn't this great?

**Comment by monolithed** [comment]
> Every contributor or author is just enthusiasm to maintain this typing files. Besides, anyone doesn't owe you anything. Please respect their time whether authors of the typing files or DefinitelyTyped member.

I have no complaints and I'm very respect these people, but I'm pretty sure the concept of this project is terrible.

> The best way is you can explain what you was doing in these changes. Providing the link which directs the source code or document is better.

There were extended some interfaces:

```diff
-    export interface RawResult<T> {
-        value: T;
-        error: string;
-    }

+    export interface RawResult<T> {
+        sessionId: string;
+        value: T;
+        state: 'failure' | 'success';
+        selector?: string;
+        message?: string;
+        hCode?: number;
+        class?: string;
+        error?: string;
+    }
```

There were added a wide variety of new interfaces:

```diff
+   export interface Capabilities {
+        browserName: string;
+        acceptInsecureCerts?: boolean;
+        browserVersion?: string;
+        platformName?: string;
+        pageLoadStrategy?: PageLoadingStrategy;
+        proxy?: ProxyObject;
+        setWindowRect?: boolean;
+        timeouts?: Timeouts;
+        unhandledPromptBehavior?: string;
+    }
+

+  export interface DesiredCapabilities extends Capabilities {
+        // Read-only capabilities
+        cssSelectorsEnabled?: boolean;
+        handlesAlerts?: boolean;
+        version?: string;
+        platform?: string;
+
```

[Hooks](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files#diff-edb3c2fb25a2ea3c4a46bc3ce3edbe84R329), [Capabilities](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files#diff-edb3c2fb25a2ea3c4a46bc3ce3edbe84R164), [DesiredCapabilities](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files#diff-edb3c2fb25a2ea3c4a46bc3ce3edbe84R176), [Options](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files#diff-edb3c2fb25a2ea3c4a46bc3ce3edbe84R391), [Status](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files#diff-edb3c2fb25a2ea3c4a46bc3ce3edbe84R75) and so on...

There were fixed several tens of methods:

```diff
-        clearElement(selector?: string): Client<void>;
+        clearElement(selector?: string): Client<RawResult<null>> & RawResult<null>;
```

There were added tens of new methods like [`$`, `$$`](http://webdriver.io/api/utility/$.html),  `hasFocus`
There were deprecated some methods like [touchClick](http://webdriver.io/api/protocol/touchClick.html)

And many other fixes with backward compatibility. I tested every command!

**Comment by monolithed** [comment]
I'm planning to close this PR due to inactivity

**Comment by fsmedberg-tc** [comment]
@monolithed and @nmalaguti: I've checked the diff and approve of the changes.

**Review by fredrik-smedberg — APPROVED** [review]

**Comment by ScenK** [comment]
@monolithed There is an issue for type Timeouts:
`type Timeouts = 'script' | 'pageLoad' | 'implicit';`

pageLoad here should be 'page load'. 
PER: http://webdriver.io/api/protocol/timeouts.html
screen shot 2017-03-17 at 5 08 07 pm


Please let me know if you want a PR to fix this minor issue.

**Comment by monolithed** [comment]
@ScenK, 

> pageLoad here should be 'page load'.

The `page load` keyword is not part of the official Webdriver specification and might not be supported for your browser. This keyword was replaced with [pageLoad](https://www.w3.org/TR/webdriver/#set-timeouts) and should't use it.

PS: I've tried to use the `page load` before,  and I have to say the following thing: Don't use it! This keyword is not fully [implemented](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/687) in Chrome yet and my tests were failed with very strange [reason](https://bugs.chromium.org/p/chromedriver/issues/detail?id=817). Use `waitForExist` instead of these timeouts.

**Comment by ScenK** [comment]
@monolithed Good to know, thanks so much.

**Comment by ajmath** [comment]
@monolithed Why were all of the `@deprecated` tags added?  It seems that there are many deprecation flags that were added that I cannot find a reference for in the wdio docs.  For example:

* `client.windowHandles` http://webdriver.io/api/protocol/windowHandles.html
* `client.localStorage` http://webdriver.io/api/protocol/localStorage.html
* `client.keys` http://webdriver.io/api/protocol/keys.html
* `client.localStorageSize` http://webdriver.io/api/protocol/localStorageSize.html
* .. along with many more

In all of the examples above, the typings are marking the code as deprecated without any documentation to support that deprecation.

**Comment by monolithed** [comment]
> `client.keys` http://webdriver.io/api/protocol/keys.html 
https://github.com/webdriverio/webdriverio/commit/c014a552e4d90e161c6074ff32d424b236e00981

>  `client.localStorage` http://webdriver.io/api/protocol/localStorage.html
> `client.localStorageSize` http://webdriver.io/api/protocol/localStorageSize.html

These commands are not part of the official Webdriver specification 

> `client.windowHandles` http://webdriver.io/api/protocol/windowHandles.html

That's my fault

**Pull request merged**
