### PR TITLE
Add definitions for [chai-as-promised] v7.1 which supports Chai v4

### PR DESCRIPTION
**Pull request by mattbishop**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <http://chaijs.com/api/><https://github.com/domenic/chai-as-promised>
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
NOTE: I'll add tslint.json in a subsequent PR as it masks the new definitions in this PR.

### CODE REVIEW

**Comment by mattbishop** [comment]
Addresses https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17329

**Comment by leonard-thieu** [comment]
There's additional steps you have to take for upgrading a package. Check out https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version.

**Comment by mattbishop** [comment]
"Please note that unless upgrading something backwards-compatible like node..."

@leonard-thieu I didn't think I had to create a different version folder because the actual chai-as-promised API did not change; what changed is the mixed-in chai v4 methods. They are all new methods, not redefining or deleting old methods. Do you think this qualifies as backwards-compatible?

**Comment by leonard-thieu** [comment]
Ah, okay, if it's only the mixed-in methods, then I think it should be fine.

From what I remember from last time I looked at the typedefs, there was a lot of duplication of `@types/chai`'s interfaces to make promisify'd versions of them. Do you think there's a way to define those interfaces as a function of the interfaces they proxy? This could make it so that `@types/chai-as-promised` isn't tightly coupled with a version of Chai. It could also make it possible to promisify other Chai plugins used alongside `@types/chai-as-promised` (which I assume Chai as Promised supports).

**Comment by mattbishop** [comment]
I thought about this but the trick is the fluent return types--chai sends back `Assertion` while chai-as-promised sends back `PromisedAssertion`. This is important because it has to be a `Promise` at the end so mocha can await it.

**Comment by mattbishop** [comment]
If you have an example project I can have a look at how to write a proxy like this.

**Comment by leonard-thieu** [comment]
I was thinking mapped types could cover this but it'd probably involve a lot of refactoring and be a big undertaking itself.

**Pull request merged**
