### PR TITLE
Update of ScrollToParameterOptions in mCustomScrollbar.d.ts

### PR DESCRIPTION
**Pull request by kwiateusz**

### CODE REVIEW

**Comment by vvakame** [comment]
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/88958733

**Comment by kwiateusz** [comment]
I know that it fails, but that log gives me nothing. Locally it works.

**Comment by vvakame** [comment]
definitelytyped_mcustomscrollbar_d_ts_at_master_ _kwiateusz_definitelytyped

**Comment by kwiateusz** [comment]
All the time I thought of it comes from diff... Sorry, and thanks.

**Comment by kwiateusz** [comment]
At last...

**Pull request closed without merging**
