### PR TITLE
Added playsInline property as introduced in React 15.3.2

### PR DESCRIPTION
**Pull request by schickling**
This is a follow up on #13086

@johnnyreilly could you merge this please? 🙏

### CODE REVIEW

**Comment by andy-ms** [comment]
Please rebase onto the latest `types-2.0` to fix tests. Fixed by #13133.

**Comment by schickling** [comment]
Thanks! Hopefully fixed now :)

**Comment by johnnyreilly** [comment]
Hi @schickling,

The PR says it's about React but there's a bunch of other stuff in there as well?  Could you clarify please?

**Comment by andy-ms** [comment]
Looks like a problem rebasing -- it contains some recent changes.

**Comment by schickling** [comment]
Closing in favor of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13141

**Pull request closed without merging**
