### PR TITLE
Update Backbone collection.comparator definition to accpet string and…

### LINKED ISSUE #6394: Backbone collection.comparator
According to documentation on the comparator attribute:
[collection.comparator](http://backbonejs.org/#Collection-comparator)

> A comparator can be defined as a sortBy (pass a function that takes a single argument), as a sort (pass a comparator function that expects two arguments), or as a string indicating the attribute to sort by.

Currently the type definition for the comparator is:

	comparator(element: TModel): number;
    comparator(compare: TModel, to?: TModel): number;

There is no typing that allows this to be set as string.  It should also be noted that the `sortBy` function can return a string or number:

>"sortBy" comparator functions take a model and return a numeric or string value by which the model should be ordered relative to others.

It appears the current type definitions do not appear to reflect these correctly.

### PR DESCRIPTION
**Pull request by Spinarooni**
… Function types. Closes #6394.

Thoughts?

### CODE REVIEW

**Comment by vvakame** [comment]
*backbone/backbone-global.d.ts*

to authors(@borisyankov @nvivo). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by danielheim** [comment]
This is correct. Could someone please merge this PR?

**Comment by vvakame** [comment]
@Spinarooni please resolve conflict & ping me again.

**Comment by Spinarooni** [comment]
@vvakame PR updated.

**Comment by danielheim** [comment]
Thanks @Spinarooni

**Pull request merged**
