### PR TITLE
Updated Mongodb to version 2.1

### PR DESCRIPTION
**Pull request by CaselIT**
Updated the type definitions to version 2.1 with Promise support.
Renamed the old version to mongodb-1.4.9.d.ts.

### CODE REVIEW

**Comment by tkqubo** [comment]
For `acl/acl.d.ts` it's completely OK! :+1:

**Comment by vvakame** [comment]
@borisyankov please take a look.

**Comment by CaselIT** [comment]
Any update?

**Comment by vvakame** [comment]
I decided to merge. thanks mate.

**Comment by CaselIT** [comment]
Cheers

**Comment by tkqubo** [comment]
:sparkles: :rocket: :sparkles:

**Pull request merged**
