### PR TITLE
Fixes #6489

### LINKED ISSUE #6489: Improve the RequestAPI.Options declaration
Currently, the following code will compile with no errors because all properties on `Options` are optional:

```typescript
import * as request from 'request';

request.defaults(8);
```

However, in reality either `uri` or `url` is required, so it would be preferable to enforce that constraint. The only way I know to do that would be to do something like this. However, other declarations that extend `RequestAPI.Options` would also need to be updated.

```
interface UriOptions {
  uri: string;
}

interface UrlOptions {
  url: string;
}

interface OptionalOptions {
...
}

export type Options = (UriOptions | UrlOptions) & OptionalOptions;
```

### PR DESCRIPTION
**Pull request by eggers**

### CODE REVIEW

**Comment by vvakame** [comment]
#6489

**Comment by vvakame** [comment]
*request-promise/request-promise.d.ts*

to author(@cglantschnig). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*request/request.d.ts*

to authors(@soywiz @bonnici @Bartvds). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by cglantschnig** [comment]
:+1: 
that is a great addition. thanks

**Comment by eggers** [comment]
I just want to mention one negative part of this pull request is that Options is changed from an interface to a union type alias. This is not ideal, but needed because an interface cannot extend an union type, [see this comment](https://github.com/Microsoft/TypeScript/issues/805#issuecomment-151718284)

**Comment by vvakame** [comment]
okay, thanks mate.

**Pull request merged**
