### PR TITLE
[three] Remove types

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Methuselah96** [comment]
Waiting on https://github.com/Microsoft/types-publisher/pull/582.

**Comment by sandersn** [comment]
Hm. Looks like anode and physijs still don't work with the external `three` dependency.

**Comment by Methuselah96** [comment]
Waiting on https://github.com/mrdoob/three.js/pull/15911.

**Comment by Methuselah96** [comment]
@sandersn Is there a way for a @types package to depend on an old version of another @types package? `physijs` depends on an old version of `three` and uses the deprecated `MeshFaceMaterial` [in its tests](https://github.com/chandlerprall/Physijs/blob/master/examples/vehicle.html#L167). Any advice on the path forward here?

**Comment by sandersn** [comment]
In the package.json of `@types/physijs`', try referencing `@types/three`? Take a look at this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20689

**Comment by Methuselah96** [comment]
@sandersn The build doesn't complete if I do that: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/502264565#L469.

**Comment by sandersn** [comment]
You have to add `@types/three` to dependenciesWhitelist.txt in Microsoft/types-publisher. Open a PR over there and I will merge it.

In the meantime, I'll fix the error message to explain that `@types` dependencies are legal in package.json under these circumstances.

**Comment by Methuselah96** [comment]
@sandersn Thanks, here it is: https://github.com/Microsoft/types-publisher/pull/587

**Comment by sandersn** [comment]
OK, I pushed to production (types-publisher doesn't publish to npm just yet) and restarted the build.

**Comment by sandersn** [comment]
OK, physijs passes now, but aframe and openjscad are still broken.

**Comment by Methuselah96** [comment]
@sandersn Yeah, it's still waiting on https://github.com/mrdoob/three.js/pull/15911. Once that's published, those packages should be fixed.

**Comment by Methuselah96** [comment]
Closing until `three@0.103.0` is released.

**Pull request closed without merging**
