### PR TITLE
[braintree-web]: Add type defs for ThreeDSecure.off(...) method

### PR DESCRIPTION
**Pull request by eloipr**
Add the missing type def for ThreeDSecure.off(...) method.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree-web ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree-web@latest/))
was missing the following properties:
1. masterpass
1. paymentRequest
1. visaCheckout
1. preferredPaymentMethods
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c75b40851db13389b9797bc061a1013bbbbbdced
</p>

**Comment by amcasey** [comment]
LGTM, but let's give the owner a bit more time.

**Review by jbuckner — APPROVED** [review]
Looks good, thanks for the update!

**Comment by eloipr** [comment]
Ready to merge

**Pull request merged**
