### PR TITLE
Add angular-scroll definitions

### PR DESCRIPTION
**Pull request by samherrmann**
New definitions for the angular-scroll library: https://github.com/oblador/angular-scroll

### CODE REVIEW

**Comment by samherrmann** [comment]
@oblador can you review?

**Comment by vvakame** [comment]
LGTM.
should I was waiting for his review?
@samherrmann If you want to merge immediately, please ping me.

**Comment by samherrmann** [comment]
@vvakame if you can merge immediately that would be great. I am not sure if @oblador (author of angular-scroll) is familiar with Typescript, but I pinged him on this review just so he is aware of this work.

**Comment by oblador** [comment]
Hi, I'm new to TypeScript so not entirely sure what I'm supposed to review. 

However, the interface for the `…Animated` methods without the duration argument looks wrong. They should always return a promise, if not then my implementation is wrong. 

Not sure how to run the unit tests and they don't look like the tests I'm used to write :-) Maybe it's just a demonstration?

How about the directives? Those are the most used part of the module I guess.

**Comment by samherrmann** [comment]
@oblador thanks for reviewing! You are definitely right about the wrong return type of the ```...Animated```  methods. I have made the corrections.

The tests are not runnable unit tests to test the implementations, but rather "sample" code that exercises the interfaces to make sure there is no compilation error. If you want to run the tests yourself, the instructions can be found [here](http://definitelytyped.org/guides/contributing.html#tests).

Regarding the directives, there is no need for type definitions because directives are used in the HTML, which is not touched by the TypeScript compiler anyway. If you want to develop directives in TypeScript, then you use the ng.IDirective interface that is defined in the [angular.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts) file.

If you want to learn more about writing Typescript definition files for existing JavaScript libraries, visit [this](https://typescript.codeplex.com/wikipage?title=Writing%20Definition%20%28.d.ts%29%20Files) page.

Thanks again for reviewing. Please let me know if you see any other issues or if you approve.

**Comment by oblador** [comment]
:+1: Good to merge!

**Comment by samherrmann** [comment]
@vvakame the review is complete.

**Comment by vvakame** [comment]
@oblador Thanks a lot!
@samherrmann thanks mate!

**Pull request merged**
