### PR TITLE
Remove pg-types

### LINKED ISSUE #49529: [@types/pg] Remove dependency on @types/pg-types
- [x] I tried using the `@types/pg` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pspeter3 @HoldYourWaffle 

`@types/pg-types` is really old and actually unnecessary because `pg-types` already has `index.d.ts`. For some reason, it's been working fine (typescript has been picking up `pg-types` instead of `@types/pg-types`), but upgrading to Yarn 2 and running `pnpify tsc ...` is now not working

### PR DESCRIPTION
**Pull request by brandonchinn178**
Resolves #49529 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

Added to upstream in https://github.com/brianc/node-pg-types/pull/83

### CODE REVIEW

**Comment by brandonchinn178** [comment]
Not sure if this is the best way to test this, but in my project, I have a dependency on `pg` and `@types/pg`. This works fine using Yarn v1 (ostensibly Yarn v1 chooses `pg-types` over `@types/pg-types`), but breaks in Yarn v2:
```
src/connection/database.ts:8:33 - error TS2339: Property 'builtins' does not exist on type 'typeof import("/Users/brandino/repos/worship-mate/.yarn/cache/@types-pg-types-npm-1.11.5-bdd25b9752-11a2b2aee9.zip/node_modules/@types/pg-types/index")'.

8 pg.types.setTypeParser(pg.types.builtins.INT8, BigInt)
                                  ~~~~~~~~
```
Manually removing `rm -rf .yarn/cache/@types-pg-types-npm-*.zip` and rerunning gives me a success

**Comment by brandonchinn178** [comment]
@waratuman Can you help me with the CI error?

**Comment by brandon-leapyear** [comment]
@waratuman bump

**Comment by waratuman** [comment]
Looks like a dependency causing this issue on the CI? Honestly haven't done TypeScript in a while, haha. Fine by me to remove the types.

**Comment by brandon-leapyear** [comment]
Yeah, the `pg` package in this repo imports from `pg-types`. Do you know how to tell the CI (and `@types/pg`'s package.json) to use the upstream pg-types instead of @types/pg-types?

**Comment by waratuman** [comment]
No idea really. My guess is you'd have to update the pg package?

**Comment by brandon-leapyear** [comment]
I'd think so too, I just don't know how to do it / what to do. Is there someone on the DT team I can ping?

**Comment by waratuman** [comment]
I don't know anyone there. Maybe just another PR or updating this one with the changes?

**Comment by hittingray** [comment]
Hi @brandonchinn178 @brandon-leapyear, I'd be happy to help out to remove the types from `pg`, since I'm working on some definition updates for `pg` where I would like to use the bundled definitions in `pg-types`. 

If you look in the readme of DefinitelyTyped under the removing a package section, you'll need to add a `package.json` to the types for `pg` and also [raise a PR here](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/definitions-parser/allowedPackageJsonDependencies.txt) to add it to the allowed dependencies list.

I think something like this should suffice:

```
{
    "private": true,
    "dependencies": {
        "pg-types": "^2.2.0"
    }
}

```

Let me know if you need any other help, or if you'd be ok with me making changes against your fork, cheers!

**Comment by brandonchinn178** [comment]
@hittingray if you're willing to take over this PR, I'd really appreciate it. If not, I can do the steps you mentioned!

**Comment by hittingray** [comment]
@brandonchinn178 Yep, I'm happy to

**Comment by hittingray** [comment]
@brandonchinn178 Would you be able to give me write access to your fork? (Just so we can keep this PR open and not need to open a new one)

**Comment by hittingray** [comment]
CI failed due to dependency list, will raise a PR in `DefinitelyTyped-tools`.

**Comment by hittingray** [comment]
Hi @waratuman @pspeter3 @HoldYourWafflem, I've fixed up this PR. Could somebody please take a look? Thank you!

**Pull request merged**
