### PR TITLE
Add type definition for async.nexttick

### PR DESCRIPTION
**Pull request by pyrho**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
  - Did it manually
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by sandersn** [comment]
Travis failed because index.d.ts needs a header as described in the readme: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#create-a-new-package

**Comment by paulvanbrenk** [comment]
ping @pyrho Can you add the header as @sandersn requested.

**Comment by pyrho** [comment]
Sorry i haven't had time lately, will do in the following days.

Le lun. 26 juin 2017 19:52, Paul van Brenk <notifications@github.com> a
écrit :

**Comment by pyrho** [comment]
I added the header, sorry for the delay. I'll use `dts-gen --dt` next time !

**Comment by paulvanbrenk** [comment]
I should not be allowed to make edits.... :|

**Pull request merged**
