### PR TITLE
[koa-bodyparser] default type body as unknown, expecting to be properly typed on usage

### PR DESCRIPTION
**Pull request by pkuczynski**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53483#issuecomment-855827765

Fixes #53715

### CODE REVIEW

**Comment by andresmosqueravtex** [comment]
i'm getting TS2687 and TS2717 when running TSC due to multiple "body" types or declarations, koa-bodyparser has the body property defined as:

body: string | Record<string, unknown>;

and packages like koa-joi-router has the body defined as:

body?: any;

it causes tsc errors when building the code. as both definitions should match.

**Comment by pkuczynski** [comment]
Would the fix proposed in this PR help with your issue?

**Comment by hirochachacha** [comment]
I sent revert request. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53715

**Comment by pkuczynski** [comment]
> i'm getting TS2687 and TS2717 when running TSC due to multiple "body" types or declarations, koa-bodyparser has the body property defined as:
> 
> body: string | Record<string, unknown>;

@andresmosqueravtex I fired up #53731 to get `koa-joi-router` in sync with #53691

**Comment by mckn** [comment]
Waiting for this to be merged

**Review by hirochachacha — CHANGES_REQUESTED** [review]
we should discuss  #53715

**Comment by pkuczynski** [comment]
We should merge this one and see if this is still a problem for anybody. AFAIK most people do already cast request body to some type, to get proper type checks later on in the code...

**Comment by hirochachacha** [comment]
> AFAIK most people do already cast request body to some type, to get proper type checks later on in the code...

no evidence...

On the other hand,  some people are starting to complain at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53483.

Why do you want to ignore the fact?

**Comment by pkuczynski** [comment]
I am not ignoring #53483 - I addressed the issue people reported there in #53691

**Comment by hirochachacha** [comment]
But it doesn't solve the root problem. you knew that. I think your approach is too invasive.

**Comment by pkuczynski** [comment]
> But it doesn't solve the root problem. you knew that. I think your approach is too invasive.

The fact is that the actual type is `string`, `object`, or `array of objects`. So using `any` is misleading and prevents any kind of type checking. Using `unknown` would encourage people to provide typings, yet they could still choose to typecast to `any` if they do not want to be bothered.

For me, this is the best compromise that leverages what typescript offers.

As I mentioned many times, koa allows typing things by providing types to `app.use`. If we keep `request.body: any`, there is no way to narrow down this type via `app.use<>`. This is how I come up with this change in #52025. You can read more details and my struggles there...

**Review by andrewbranch — CHANGES_REQUESTED** [review]
I think the best course of action is to move forward with the revert, unfortunately. I wish there were a way to let people get rid of `any`s like these without a lot of resulting pain, but in this case I didn’t see a good way, other than trying to get these changes in whenever koa-bodyparser releases a new major version. Thanks for your effort @pkuczynski. By all means, if you can find a way to accomplish this while keeping `any` the default for consumers, we should look at that. But in the meantime I think we should revert.

**Comment by pkuczynski** [comment]
@andrewbranch thing is that we do not know how much pain this can cause, and given the low number of complaints with the current, very imperfect typing, changing to `unknown` seems to be the best choice, to be honest. I would like to at least give it a try before we completely revert. Keeping body typed as `any` really sucks :( And `koa-bodyparser` is not that much actively develop, that we could expect any new version soon...

Can we give it a try? I promise to prepare a revert commit if this still does not work and people will complain...

Seems that @elibarzilay supported this PR initially?

**Comment by andrewbranch** [comment]
> And `koa-bodyparser` is not that much actively develop, that we could expect any new version soon...

This is the reason why we want to revert. It’s a very stable package, so people don’t expect to have to think about changing their usage of it on a regular basis like they do with large, complex libraries that ship new features and deprecate old ones all the time. It’s much easier to slip a useful typings change into a library like that than into one that’s been zero maintenance burden for people in the last 1.5 years.

These typings get 1.2 million downloads per week, and I think it’s a relatively safe assumption that most people who use the package probably access `request.body` in a way that would require some changes if it changed from `any` to `unknown`, given that the library’s sole purpose is to provide `request.body`. So it’s not so much about whether or not they can successfully make those changes, as this PR remedies over #53483; it’s more that we should never have merged #53483 in the first place, even if it went straight to `unknown`, because of the maintenance burden it imposes on a large number of people for an otherwise very stable library.

Three or four people showing up on #53483 is actually a fair number of people for DefinitelyTyped standards. Definitely enough to pay attention to. And I’m not sure if @elibarzilay’s move was intentional or not, but I talked with others on the team this morning and we came to the same unsatisfying conclusion. I know it sucks, but back compat is a pretty important consideration for popular packages like this one.

**Pull request closed without merging**
