### PR TITLE
Add Prettier badge

### LINKED ISSUE #41245: Add `Styled with Prettier` badge [README]
This is pure dev-x issue. Recent change to readme outlines usage of the `Prettier` in the repo.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9f2b299e70f71500b4d3bef7c30c366d5c7f057a#diff-04c6e90faac2675aa89e2176d2eec7d8R185

Can the `styled with Prettier` badge be added to the Readme, to point that out via visual clue?
https://github.com/prettier/prettier/blob/master/README.md#badge
Thanks!

### PR DESCRIPTION
**Pull request by yardenshoham**
Closes #41245

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
Can this go all online?
```diff
-[![Join the chat at https://gitter.im/DefinitelyTyped/DefinitelyTyped](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/DefinitelyTyped/DefinitelyTyped?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
-
-
-[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg)](https://github.com/prettier/prettier)
+[![Join the chat at https://gitter.im/DefinitelyTyped/DefinitelyTyped](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/DefinitelyTyped/DefinitelyTyped?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg)](https://github.com/prettier/prettier)
```

**Comment by uniqueiniquity** [comment]
cc: @sandersn @orta

**Comment by sandersn** [comment]
Actually, I'd prefer to keep the badge away from the gitter badge, in order to make the link to gitter stand out more. I'm not sure *where* to put it, though. @orta opinions?

**Comment by orta** [comment]
I'm not a fan of badges which are only for aesthetics, this badge doesn't really add value to the readme - IMO, we should not accept the PR

**Review by sandersn — CHANGES_REQUESTED** [review]
Badge doesn't add value, plus is a little misleading since we don't run prettier on commit as people might expect.

**Pull request closed without merging**
