### PR TITLE
chore: replace inline constants in chess.js

### PR DESCRIPTION
**Pull request by vicary**

### CODE REVIEW

**Comment by CapOfCave** [comment]
Looks good to me. You could have used the BLACK and WHITE constant types to define the PieceColor, but since this PR is a clear improvement to what was there before I won't complain.

Make sure to update the tests and I'll approve this PR.

**Comment by vicary** [comment]
@CapOfCave I wanted to use the constants, but the following line seems a little bit weird to me. We may leave it at the current state, or convert all constants into types. What do you think?

```ts
export type PieceType = typeof PAWN | typeof KNIGHT | typeof BISHOP | typeof ROOK | typeof QUEEN | typeof KING;
```

Also for test line 196, TypeScript 4.1 automatically flattens `SquareColor | null` into `'light' | 'dark' | null` while latter versions don't, I am leaning towards a major release when upstream behavior is breaking.

```ts
// $ExpectType SquareColor | null
chess.square_color('invalid square string');
```

What do you think?

**Comment by CapOfCave** [comment]
@vicary I agree, the line you mentioned does look a little weird. So to me, your implementation is totally fine.

Did we really have to upgrade the minimum supported typescript version, though? It doesn't look like we're using any new features. And you still had to alter the tests, so it wasn't typescript's fault but the testing framework's ...

Does the automatic flattening actually make a difference? You can still assign the result to the type `"w" | "b"`, so this should not be a breaking change... Thus, I don't really see a reason to increase the min. supported version. What do you think?

**Comment by vicary** [comment]
@CapOfCave With a min version, `dtslint` will test all the versions counting up. Which means if we stay at 3.3, it will test against both TypeScript 4.1 and 4.9. The problem is that 4.1 flattens to `'light' | 'dark' | null`, while ^4.2 is able to keep the original type `SquareColor | null`.

Which means `$ExpectType SquareColor | null` will fail on 4.1, and `$ExpectType 'light' | 'dark' | null` fails on 4.2+. They are different outputs in terms of type definitions.

Does this particular usage reveals a breach of semver on TypeScript side?

**Review by CapOfCave — APPROVED** [review]
Looking good. Pretty sure there's a solution which does not increase the min. TS version (using `||` in `$ExpectType`) but I don't think a lot of projects (if any) will break if we just increase it. So it's fine by me, time to merge.

**Comment by vicary** [comment]
Ready to merge

**Pull request merged**
