### PR TITLE
[braintree] Update statusHistory for Transaction class

### PR DESCRIPTION
**Pull request by martin-badin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by martin-badin** [comment]
@hitech95 Hi, please review. Thanks

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree@latest/))
was missing the following properties:
1. GraphQL
1. version
1. errorTypes
1. CoinbaseAccount
1. AmexExpressCheckoutCard

<details>
<summary>as well as these 5 other properties...</summary>
<p>PaymentInstrumentTypes, WebhookNotification, TestingGateway, UsBankAccountVerification, ValidationErrorCodes</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c2f840517843ba135f569f4f334ad75629382efe
</p>

**Comment by hitech95** [comment]
> 
> 
> @hitech95 Hi, please review. Thanks

Seems fine to me for Transaction, this allow me to attach a webhook and get the history of the transaction. Before I had to double cast it to force it to an array. 

About the other missing properties I have no idea, so far I'm not using them.

**Review by smrubin — APPROVED** [review]

**Comment by martin-badin** [comment]
@rbuckton Could you please review?

**Comment by orta** [comment]
👍🏻  looks good - @martin-badin you can speed up PR merge time by adding tests for your changes, then a DT maintainer doesn't need to merge it

**Pull request merged**
