### PR TITLE
Fixed google.maps.InfoWindow.setPosition interface

### PR DESCRIPTION
**Pull request by ysgk**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@Outlivier @nertzy@vankooch and @xaolas can you please review this change?

**Comment by xaolas** [comment]
Documentation URL is wrong

**Comment by xaolas** [comment]
Correct URL is https://developers.google.com/maps/documentation/javascript/reference#InfoWindow

**Comment by ysgk** [comment]
Yes, thanks.

**Comment by nertzy** [comment]
Looks good to me.

**Pull request merged**
