### PR TITLE
Update koa-bodyparser with stricter body and rawBody

### PR DESCRIPTION
**Pull request by anup-the-magic**
Parsed body should be `unknown` type (simulated until release in
Typescript 3.0). Any manipulations on `body` should come with type
assertions and/or verification. Note, this is a major change, and a
significant tightening of type safety.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Microsoft/TypeScript/pull/24439
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by anup-2s** [comment]
@hellopao

**Comment by mikew** [comment]
@anup-2s How is this supposed to be used now? Are we supposed to cast all references of `context.request.body`? Because after updating, our code is littered with things like this:

screen shot 2018-07-06 at 12 03 30 pm

**Comment by teevik** [comment]
@anup-2s Why is the "undefined | null" types included? This is what the docs say: (https://github.com/koajs/bodyparser)
```javascript 
app.use(async ctx => {
  // the parsed body will store in ctx.request.body
  // if nothing was parsed, body will be an empty object {}
  ctx.body = ctx.request.body;
});
```

If anything, i think it should stay as `any`, since that's what it can return based on the types from `co-body` (Used in https://github.com/koajs/bodyparser/blob/master/index.js#L91, `co-body` definition: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/co-body/index.d.ts#L20)

**Comment by anup-2s** [comment]
@mikew the goal was either typecast, use your own typeguard, or use a runtime type library like https://github.com/gcanti/io-ts (there are a few others out there, but this is the one that I've used most heavily). The reasoning behind this was largely from the discussions in the Typescript community regarding the new `unknown` type that will be shipping with Typescript 3.0 (see https://github.com/Microsoft/TypeScript/pull/24439, https://github.com/Microsoft/TypeScript/issues/10715), and this is the base type that `unknown` more explicitly satisfies. 

@teevik Good catch on the empty object, I was definitely just deriving from the placeholder definition of `unknown`, but `{}` is probably a fine and accurate definition for `body` -- I unfortunately can't submit a PR in the next couple weeks, but would be happy to after that. Returning to `any` is a definite possibility, but I will mention that this helped us catch numerous bugs around the hidden `any`, and I think an explicit `any` is much clearer than an implicit `any` that is untracked. If your team personally wants to fall back to `any`, I did make this a major version bump, so the install can pin to `1.x`, and I'm happy to go back and edit the MR if we want to separately maintain `1.x` and `2.x` versions, though again, I don't think I could get to it before a couple weeks. Alternatively, remember that these can be overridden locally by your own `typings` folder, as, again, I think it's truer to the API to use either `unknown` or `{}` for `ctx.body` over `any`.

**Comment by rbuckton** [comment]
@anup-2s: Dropping in from your link in #27717. You mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26330#issuecomment-403128294 that you bumped the major version, but that is incorrect as the latest version [on npm](https://www.npmjs.com/package/koa-bodyparser) is 4.2.1. DefinitelyTyped package numbers should at a minimum align with the Major version numbers of the package they represent, while our types-publisher automatically increases the revision/patch number each time we deploy. Changing the version number to 5.0 is incorrect as it does not follow this convention (since koa-bodyparser has not published a 5.X version yet).

// cc: @sandersn

**Comment by anup-2s** [comment]
Ah  @rbuckton, I think I was suffering from the same confusion noted in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25748 and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26847 -- are there easy steps to rectify this now? And what should the protocol be for a change like this (which requires significant code change to make this fix)? Should we advocate that users pin @types/X to absolute versions?

**Pull request merged**
