### PR TITLE
[node] Fix `http.createServer` signature (again) 

### PR DESCRIPTION
**Pull request by Lordfirespeed**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

I am changing an existing definition

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - #70289
  - #70453

This contains all changes from #70289 with the difference that the defaults for the `Response` type parameters are left unchanged. 
This should ensure no existing code is broken.

### CODE REVIEW

**Comment by Lordfirespeed** [comment]
<details>
<summary>Usual case</summary>

```ts
import * as http from "node:http"

export const createServer = () => {
  return http.createServer();
}
```

Emits declaration:
```d.ts
import * as http from "node:http";
export declare const createServer: () => http.Server<typeof http.IncomingMessage, typeof http.ServerResponse>;
```

</details>

<details>
<summary>Case with custom prototypes</summary>

```ts
import * as http from "node:http"

class Request extends http.IncomingMessage {
  
}

class Response<Req extends Request> extends http.ServerResponse<Req> {
  
}

export const createServer = () => {
  return http.createServer<typeof Request, typeof Response>();
}
```

Emits declaration:

```d.ts
import * as http from "node:http";
declare class Request extends http.IncomingMessage {
}
declare class Response<Req extends Request> extends http.ServerResponse<Req> {
}
export declare const createServer: () => http.Server<typeof Request, typeof Response>;
export {};
```

</details>

**Comment by Lordfirespeed** [comment]
@andrewbranch If you have time, I would really appreciate your review on this ❤️

**Comment by Lordfirespeed** [comment]
First check failure is a new test I need to adjust, as the type being asserted upon was previously not generic.

Second check failure is a problem on `master` that went under the radar

**Comment by Lordfirespeed** [comment]
@jakebailey  I'm afraid you're my only port of call for ecosystem breaks 😅 please do let me know if you'd prefer I not ping you like this

**Comment by Lordfirespeed** [comment]
Found the ecosystem break: https://github.com/Automattic/mongoose/issues/14863

**Comment by jakebailey** [comment]
Is mongoose guaranteed to not break this time?

**Comment by Lordfirespeed** [comment]
> Is mongoose guaranteed to not break this time?

I don't think mongoose was ever breaking because of this PR's (or the previous one's) changes 😅 

That said, `express` and anything using `http.createServer` without generic type parameters were broken by the previous PR.

I have very high confidence they are not broken by this PR, because it does not change the generic type parameter defaults, just the *constraints* applied to the generic type parameters *when supplied*.

**Comment by jakebailey** [comment]
I retested Andrew's example from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70289#issuecomment-2330091852, and the dts emit is now the same before/after this PR, so that issue is also fixed.

**Review by jakebailey — APPROVED** [review]
Willing to try this a second time given the extra testing we did.

**Comment by jakebailey** [comment]
Er, well, you may want to merge master and just verify that things work.

**Review by jakebailey — APPROVED** [review]

**Comment by Lordfirespeed** [comment]
Ready to merge

**Pull request merged**
