### PR TITLE
Typings For AngularJS Extensions For RxJS 

### PR DESCRIPTION
**Pull request by mickdelaney**
Initial Commit Of Minimum Support For The AngularJS Extensions For RxJS

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
@mickdelaney could this also be merged directly into the `rx.angular.js` project as well?

**Comment by mickdelaney** [comment]
Sure, whatever you guys think, I'm working with rx & typescript on angular most days now so whatever makes that easier 😉 do you want me to send another pull request with the code moved over ?

**Comment by vvakame** [comment]
*angular-rx/rx.angular.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-rx
  * http://bower.io/search/?q=angular-rx
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-rx/rx.angular-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
I can't found angular-rx project... where is it?

**Comment by mickdelaney** [comment]
https://github.com/Reactive-Extensions/rx.angular.js

**Comment by mickdelaney** [comment]
i called it angular-rx to follow the naming conventions for the rest of the angular-* projects on definitelytyped.  i guess we could stick to they're convention though, which would be rx-angular

**Comment by vvakame** [comment]
yep, please use rx-angular/rx-angular.d.ts

**Comment by mickdelaney** [comment]
i've move the angular rx typings to rx-angular

**Comment by vvakame** [comment]
@mickdelaney sorry for delay. It merged. thanks!

**Pull request merged**
