### PR TITLE
Patching vulnerable dependency in @types/mock-aws-s3

### PR DESCRIPTION
**Pull request by mxro**
```
├─ aws-sdk: 2.721.0
│  ├─ Issue: Prototype Pollution via file load in aws-sdk and @aws-sdk/shared-ini-file-loader     
│  ├─ URL: https://github.com/advisories/GHSA-rrc9-gqf8-8rwg
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <2.814.0
│  ├─ Patched Versions: >=2.814.0
│  ├─ Via: aws-sdk
│  └─ Recommendation: Upgrade to version 2.814.0
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

```
├─ aws-sdk: 2.721.0
│  ├─ Issue: Prototype Pollution via file load in aws-sdk and @aws-sdk/shared-ini-file-loader     
│  ├─ URL: https://github.com/advisories/GHSA-rrc9-gqf8-8rwg
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <2.814.0
│  ├─ Patched Versions: >=2.814.0
│  ├─ Via: aws-sdk
│  └─ Recommendation: Upgrade to version 2.814.0
```

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by mxro** [comment]
Seems like there was an

```
Error in mock-aws-s3
Out of memory
```

Error - assuming this may not be related to the change?

**Review by elliotblackburn — APPROVED** [review]

**Comment by BlueHatbRit** [comment]
It might be worth pushing an empty commit to force the rebuild, I'm not a DT maintainer though so don't know for sure.

**Comment by mxro** [comment]
Still seems to be the same out of memory error 😢

**Comment by BlueHatbRit** [comment]
It could be worth pinging a couple of the DT maintainers in that case :/

**Comment by mxro** [comment]
Pinging @andrewbranch @sandersn - saw you contributed to `CI.yml` - would you have any idea why we are getting an out of memory error for this change?

```
dtslint@0.0.111
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Maybe caused by `aws-sdk` being a huge package?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mxro thx!

**Comment by BlueHatbRit** [comment]
The azure run also seems to have run out of memory by the looks of things

**Comment by andrewbranch** [comment]
Yeah. I’m not sure what to do about this. The very odd thing is that other packages rely on aws-sdk with a similar version range, and we test every package overnight. I’m tempted just to merge and hope for the best, but I think I’d like to wait until @sandersn is back from vacation (I think next week) and discuss a plan with him. Thanks for your patience everyone ❤️

**Review by sandersn — APPROVED** [review]
2.814.0 definitely takes longer to compile locally than 2.169.0, but it should already be used in all test runs. I'll investigate separately to find out why CI runs crash but overnight runs do not.

**Comment by sandersn** [comment]
Also @andrewbranch and I decided that other aws-sdk dependents should require 2.814 as well. I'll do that in another PR.

**Pull request merged**
