### PR TITLE
Sequelize - Return a TInstance instead of a void in all createAssociationMixin.

### PR DESCRIPTION
**Pull request by JulienDuf**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by drinchev** [comment]
I think this is not correct.

According to the specs, you are not always receiving the Created Instance : 

http://docs.sequelizejs.com/en/v3/api/associations/belongs-to/

Also a small test proves that you don't always receive it : 

```js
const Sequelize = require("sequelize");
const sequelize = new Sequelize('so_tests', 'root', '');
const DataType = Sequelize;

const Team = sequelize.define('team', {
        name: { type: DataType.STRING, require: true }
});

const Player = sequelize.define('player', {
        name: { type: DataType.STRING, require: true }
});

const Championship = sequelize.define('championship', {
        name: { type: DataType.STRING, require: true }
});

Player.hasOne( Team );
Team.belongsTo( Championship );

sequelize.sync({ force: true })
         .then(() => {
                return Player.create( { name: "foo" } )
                             .then( player => player.createTeam( { name: "bar" } ) )
                             .then( result => console.log( result ) );
        }).then( () => {
                return Team.create( { name: "baz" } )
                           .then( team => team.createChampionship( { name: "boo" } ) )
                           // result is not Championship
                           .then( result => console.log( result ) );
        }).catch(err => console.log(err))
```

**Comment by JulienDuf** [comment]
You are right for belongsTo! Sequelize doesn't return the instance of the championship created because a team can only have one championship (according to your example). It should be the same for hasOne,

However, I think sequelize will return the instance of the instance of the new associated model for hasMany and belongsToMany, because you have no way to get this new instance. I know that the specs are not saying that (http://docs.sequelizejs.com/en/v3/api/associations/has-many/), but I always receive the new instance.

**Comment by paulvanbrenk** [comment]
@drinchev does this resolve the issue?

**Comment by drinchev** [comment]
Well okay then. Let's merge. @paulvanbrenk 👍

**Pull request merged**
