### PR TITLE
[node] Add type side of global Blob, along with tests

### PR DESCRIPTION
**Pull request by thw0rted**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

----

Fixes one missing piece from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59905

### CODE REVIEW

**Comment by thw0rted** [comment]
cc @peterblazejewicz , who reviewed the linked PR and 4.8 backport.

**Comment by doteric** [comment]
Hello @thw0rted 

I'm having an issue with the `16.11.65` version of `@types/node` and I'm wondering if this would fix it.
```
node_modules/@types/node/ts4.8/stream.d.ts(842,39): error TS2304: Cannot find name 'Blob'.
```
Adding `dom` to the `tsconfig.json` might actually bypass this error, but `dom` shouldn't really be added in a pure node.js app I guess...

The change was fine for v18 I guess, but a breaking change for v16 and anything under I guess.

**Comment by thw0rted** [comment]
Yes @doteric, this PR is designed to fix the error you mention.  Until it is merged, you could use an older version of `@types/node`, from before https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59905 was merged.

**Comment by meyfa** [comment]
@thw0rted Possibly I'm missing something obvious... why would this fix problems with `@types/node@16`, when changes are only made to the files at the top-level directory, that get released as `@types/node@18`?

**Comment by thw0rted** [comment]
Thanks @meyfa, I didn't notice that.  Sorry, I don't actually have a super firm grasp of how the simultaneous-versioning thing works here on DT.  I'll update the linked PR to address that as well, then.

**Comment by thw0rted** [comment]
@doteric, did your code work with an older 16.x version of `@types/node` previously?  The line you reference has been the same since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57678 -- it references a global `Blob` that comes from `lib: ['dom']`, so I would think that means it should never have worked without the consuming project also including lib-dom.  If you included it successfully without lib-dom, I'd like to figure out how that happened.

**Comment by meyfa** [comment]
@thw0rted What changed is that the `Blob` interface was removed from `stream/consumers` here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/85092f93d4fa4f7139ca36c686d38ed93cf0ef54#diff-cbbc0d1dbb422f3ff8a11040b66fb75a4b49a1f08a57ae743545db7cb4533436
I suppose this interface somehow got exposed to the global scope. I think `.d.ts` files automatically export everything, so the comment above ("This interface is not, and should not be, exported.") may have been incorrect.

During development and CI, the now missing `Blob` was not noticed because the v16 `tsconfig.json` still depends on DOM, but unless users also depend on DOM, then the error will manifest in their projects.

The same error @doteric mentioned also happened for me in an automated upgrade from `16.11.63` to `16.11.65`: https://github.com/meyfa/eslint-config/pull/41. Luckily Renovate provides a link to see the diff of the NPM package: https://app.renovatebot.com/package-diff?name=@types%2fnode&from=16.11.63&to=16.11.65#d2h-324327. Looking at that diff, I can't see anything other than `stream/consumers` being responsible.

**Comment by meyfa** [comment]
Should we maybe perform all the same changes from #59905 to the v14 and v16 directories as well, so that `Blob` becomes available again, and so that v14 and v16 become independent of DOM, just like version 18?

**Comment by thw0rted** [comment]
Thanks for refreshing my memory, it's been *months* since I initially did this work and I had forgotten about the incorrect comment, which actually sparked this whole process in the first place.

Backporting the changes to v16 (at least) makes sense, I think. Maybe v14 as well, though it has no `stream/consumers` and thus no erroneous global Blob.  I have to imagine the user base for v14 is getting pretty small by now, it's only on LTS until this coming April.

I don't have a lot of spare cycles right now, and probably won't at least through the end of the year or so.  If you have time to do the port, awesome, and if you don't I'll try to fit it in eventually but can't make any predictions about a timeline.

**Comment by meyfa** [comment]
I'll see what I can do!

**Comment by doteric** [comment]
> @doteric, did your code work with an older 16.x version of `@types/node` previously? The line you reference has been the same since #57678 -- it references a global `Blob` that comes from `lib: ['dom']`, so I would think that means it should never have worked without the consuming project also including lib-dom. If you included it successfully without lib-dom, I'd like to figure out how that happened.

@thw0rted , yes it worked perfectly fine on some other previous version. Yesterday I also set a temporary resolution to the version `16.11.62` and it works perfectly fine.

**Comment by meyfa** [comment]
Quick update, I noticed `Blob` was added to globals only in v18. So depending on it would be a mistake, as it isn't available at run-time. Actually, the "mistake" of removing it brought us closer to reality. Still we need to fix other types in v16 depending on it.

**Comment by meyfa** [comment]
I opened #62672 which should be the minimum change needed to fix v16. After that is merged we can try getting rid of DOM entirely for v16.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@thw0rted thanks!

**Pull request merged**
