### PR TITLE
Changed controls according to v0.26.0

### PR DESCRIPTION
**Pull request by fabio-silva**
case 2. Improvement to existing type definition.
- Documentation: https://www.mapbox.com/mapbox-gl-js/api/#Controls

### CODE REVIEW

**Comment by aozgaa** [comment]
Can you add a test using the renamed classes?

**Comment by minestarks** [comment]
@fabio-silva Thanks for your contribution. This PR is over a month old and has unaddressed comments. Do you plan to address them? If no further changes I plan to close this in a couple of days.

**Comment by fabio-silva** [comment]
@minestarks sorry for that. This was already solved in #11992 in a more complete way, that's why I let it go. This can definitely be closed.

**Comment by minestarks** [comment]
@fabio-silva No problem. Closing.

**Pull request closed without merging**
