### PR TITLE
Add definitions for mysql-live server and client side

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by basarat** [comment]
I'd be happy to merge. But since the original project is in typescript please reconsider : http://blog.johnnyreilly.com/2015/09/authoring-npm-modules-with-typescript.html?m=1 🌹

**Comment by kataras** [comment]
Yes, I was waiting for this 'typings' field inside package.json ( I used it on node-mysql-wrapper ) but it didn't worked, so I can try again. You suggest me that I should provide the mysql-live.d.ts inside compiled/ folder? and on package.json add 'typings' : './compiled/mysql-live.d.ts' ?

**Comment by basarat** [comment]
> You suggest me that I should provide the mysql-live.d.ts inside compiled/ folder

Yup. Have `declaration` true in tsconfig.json and that will generate the `.d.ts` files in the `compiled` folder *right next to the js*. Then have your `typings` point to `./compiled/index` : https://github.com/nodets/node-mysql-live-client/blob/master/package.json#L5 :rose:

**Comment by kataras** [comment]
Yes I get that, but I have one question, suppose that one exported variable has a type of SocketIO.Socket and I want code assistance in this variable. How can other developer have code assistance in this variable without  the mysql-live.d.ts references to the  ./socket.io.d.ts  file ?

**Comment by basarat** [comment]
> How can other developer have code assistance in this variable without the mysql-live.d.ts references

They don't need the *reference*. If `socket.io.d.ts` is included in their tsconfig.json (which it should be if you ask them to do `tsd install socket.io`) then it should just work :rose:

**Comment by kataras** [comment]
So we need this project yet :P , I get it I will put d.ts on compiled/ and here on definitely typed too

**Comment by basarat** [comment]
> but in order to do tsd install something ,something.d.ts

Yes ... but only stuff that is *not in TypeScript* ... stuff like `node.d.ts` `socket.io.d.ts` ... but not *your code that is already in TypeScript*. Typings for that can easily ship with your project. User only needs to do `npm install yourproject` and typescript should start working.

**Comment by basarat** [comment]
To be clear my intent is to help you and your project :rose:

**Comment by kataras** [comment]
I understand that a lot time ago, you re very good person and I'm grateful for this! My english are not so good and maybe my answers and questions looks blunt, excuse me!

**Comment by basarat** [comment]
@kataras for an example checkout : https://github.com/TypeStrong/tsconfig/tree/ea9f710a30bf364c86993abfbd7b92ee376e0b61 

its package.json : https://github.com/TypeStrong/tsconfig/blob/ea9f710a30bf364c86993abfbd7b92ee376e0b61/package.json#L5-L6

its tsconfig.json: 
https://github.com/TypeStrong/tsconfig/blob/ea9f710a30bf364c86993abfbd7b92ee376e0b61/tsconfig.json#L6

And the fact that it does need typings that come from here : https://github.com/TypeStrong/tsconfig/tree/ea9f710a30bf364c86993abfbd7b92ee376e0b61/typings

The complete package `tsconfig` is used *as is* without any need for typings to be put *here*.

**Comment by kataras** [comment]
I wrote a comment but never sent lol, 
I did these as you said me look at the https://github.com/nodets/mysql-live/ if you want.

I'm using gulp-typescript but it does not recognize the 'declaration' property so I have to do 'gulp' and after 'tsc' command to get it work, maybe this is a bug because on the (gulp-typescript's) docs says that this option is available.

As I understand the tsConfig project, resolves and concats all relative d.ts  files? I suppose it is not for gulp I have to make a script myself? :P

**Comment by basarat** [comment]
> As I understand the tsConfig project, resolves and concats all relative d.ts files? I suppose it is not for gulp I have to make a script myself? :P

No. To be honest its just one file `tsconfig.ts` and `tsconfig.d.ts` that is generated simply with `tsc` : https://github.com/TypeStrong/tsconfig/blob/ea9f710a30bf364c86993abfbd7b92ee376e0b61/package.json#L15 :rose:

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
