### PR TITLE
1.15.0

### PR DESCRIPTION
**Pull request by tom-schier**
Added energy, register, common, dcr API schemas.
Associated restructuring.
These definitions are in line with the 1.15.0 standards release

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@tom-schier can you please revert a change to this file? 'docs/support-window.svg' (doing this should properly relabel your PR type), thx!

**Comment by tom-schier** [comment]
Hi @peterblazejewicz I am not sure why this file is picked up as a change. They look identical. In my last commit I replaced the file in my PR with the one from master. Is that good enough?

**Comment by peterblazejewicz** [comment]
this is one of the most active (in terms of git graph objects rewrites) repos on the Github I think. Your branch dates back to August last year (the first commit).
Let's try to focus on your changes, can you try this:
```ms
 git co master
 git pull
 git co 1.15.0
 git checkout master -- docs/support-window.svg
 git co master -- types/cache-manager/cache-manager-tests.ts
 git co master -- types/cache-manager/index.d.ts
 git add .
 git commit
```
(this updates local master with recent changes from remote and resets couple of files not related to types you're changing to the same content as on master, commit and push a change)

**Comment by tom-schier** [comment]
Thanks @peterblazejewicz I believe that did the trick.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by tom-schier** [comment]
Ready to merge

**Pull request merged**
