### PR TITLE
Add definition for swaggerize-express

### PR DESCRIPTION
**Pull request by MugeSo**
Definition for https://www.npmjs.com/package/swaggerize-express

### CODE REVIEW

**Comment by vvakame** [comment]
*swaggerize-express/swaggerize-express.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/swaggerize-express
  * http://bower.io/search/?q=swaggerize-express
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (swaggerize-express/swaggerize-express-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
LGTM. I'll merge this PR when travis ci passed.

**Comment by vvakame** [comment]
please ping me again if I forget this PR :wink:

**Comment by kanreisa** [comment]
@vvakame ping :)

**Comment by vvakame** [comment]
thanks all!

**Comment by kanreisa** [comment]
:sushi: :sushi: :sushi:

**Pull request merged**
