### PR TITLE
[jquery] Add Animation API. Fix weak type issue for `jQuery.speed`.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

---

##### Add Animation API. (e724720)

See https://blog.jquery.com/2012/08/09/jquery-1-8-released/ which links to https://gist.github.com/gnarf/54829d408993526fe475.

**Note**: When attempting to use `keyof TElement` within `Tween<TElement>`, I ran into an issue I've previously encountered (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29687#discussion_r224824454). These changes and errors are seemingly unrelated. 

[Detailed log](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2476604/log.txt)

Being able to use `keyof TElement` would allow for stronger declarations.

##### Fix weak type issue for [`jQuery.speed`](https://api.jquery.com/jQuery.speed/). (713e97f)

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Can you fix the build please?

**Comment by leonard-thieu** [comment]
I... what... what even are these errors?

**Comment by johnnyreilly** [comment]
Dunno. I've requeued the build...

**Comment by leonard-thieu** [comment]
@RyanCavanaugh @andy-ms these test failures appear to be a tooling issue. Could you look into it?

**Comment by leonard-thieu** [comment]
:rage:

**Pull request merged**
