### PR TITLE
Allow auto filling using office-js ranges

### PR DESCRIPTION
**Pull request by gkfirst8**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://hongbo-miao.gitbooks.io/excel/content/tutorial/excel-add-ins-javascript-programming-overview.html (In the examples it is shown that a range can be assigned one (string) value ("Note that Range has 20 cells, whereas the provided input only has 1 cell value."))
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Hi @gkfirst8,

Thanks for submitting this suggestion. However, the Excel type definitions are automatically generated elsewhere. DefinitelyTyped serves as public endpoint, but we copy the definitions from an internal source-of-truth. These changes would either be overwritten next time we make changes, or require manual editing every time.

That said, these convenience overloads are excellent. Let me tag @wandyezj to take a look and see if this could get added to the source.

**Comment by gkfirst8** [comment]
@AlexJerabek I feared as much. This PR was kind of a way to start the conversation.

In my current project I look into a workaround but it would be cool if the full potential of the underlying library would be exposed.

Thank for tagging the person involved.

**Comment by AlexJerabek** [comment]
Makes sense. We believe we have similar overloads in Office Scripts, so this should be doable. Let me also tag @jayrathi and @jeremy-yoo as other office-js owners.

**Comment by wandyezj** [comment]
Good suggestion.

_note:_ numberFormat and values always return `any[][]`. Specifying `any[][] | string` indicates that `string` can be returned which is not the case. This change can present type issues for people reading the property since they would now need to ensure that it is not a string. This could also break compilation of existing references.

I would recommend taking advantage of [TypeScript 4.3+ which offers the ability to define different types for property get and set](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters). This would require a major version bump of the library since older TypeScript versions would not be able to take advantage of the new types.

**Comment by gkfirst8** [comment]
As the actual upstream of this part has explained why things are the way they are I suggest we abandon this PR.

**Comment by gkfirst8** [comment]
I suggest I drop this PR as this part is governed by someone else.

**Pull request closed without merging**
