### PR TITLE
Typings capable of being used within namespaces

### PR DESCRIPTION
**Pull request by Hobart2967**
Please fill in this template.

- [ x] Prefer to make your PR against the `types-2.0` branch.
- [ x] Test the change in your own code.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ]x Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

Making typings capable of being used within namespaces:

namespace Controls.Web {

    import IAttributes = angular.IAttributes;

### CODE REVIEW

**Comment by thorn0** [comment]
:-1: This change can't be accepted. It breaks too many things.

**Comment by Hobart2967** [comment]
Will fine-tune!

**Comment by thorn0** [comment]
What are you trying to achieve?
```ts
namespace Controls.Web {
  import IAttributes = angular.IAttributes;

}
```
I've tried to compile this code with the current version of `@types/angular`. It works.

**Comment by andy-ms** [comment]
Closing because this is probably not the types' fault.

**Pull request closed without merging**
