### PR TITLE
[wordpress__blocks] Updated @wordpress/element to v4

### PR DESCRIPTION
**Pull request by marekdedic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] ~Test the change in your own code. (Compile and run.)~
- [ ] ~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] ~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by dmsnell** [comment]
What's the purpose of updating the dependency?

**Comment by marekdedic** [comment]
Hi @dmsnell,
I want to upgrade this dependency because in `@wordpress/element` version 4.1.0, `@types/react` was bumped from v16 to v17 (WordPress/gutenberg#37365). As a result of that, using `@types/wordpress__blocks` together with `@wordpress/element` causes errors because of clashes between the 2 different versions of `@types/react`.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__blocks ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__blocks@latest/))
was missing the following properties:
1. store
1. store
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ca85f5cfd65424e5c67f1a48daf928458f88fc4b
</p>

**Comment by marekdedic** [comment]
I'd also like to do this for `wordpress__components` and `wordpress__editor` - should I do it in this PR as well, or open separate PRs?

**Comment by sirreal** [comment]
This seems reasonable, but the package version needs to be updated to match the version with the udpated dependency. [unpkg can be a good tool to figure out the correct version.](https://unpkg.com/browse/@wordpress/blocks@9.1.0/package.json)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5eb442fcb6bef5b6dad129456bc6b94c2f2b9a36/types/wordpress__blocks/index.d.ts#L1

> I'd also like to do this for wordpress__components and wordpress__editor - should I do it in this PR as well, or open separate PRs?

Let's do a single PR for each package. If you update a single package you get a streamlined review process. If you modify multiple packages I believe a maintainer needs to approve.

**Comment by marekdedic** [comment]
Ok, @sirreal, I split the changes to `wordpress__data` into #59511... I will probably supersede this PR with another one specific to `wordpress__blocks`, but that one needs #59511 to be merged (the tests are somehow broken on that package...) - thanks!

**Pull request closed without merging**
