### PR TITLE
added details to Grid and Table class, fixed typing for cell-measurer cache

### PR DESCRIPTION
**Pull request by kaoDev**
Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: 
    - https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js
    - https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Table.js
    - https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js

The classes of Table and Grid are extended by there public methods and properties

### CODE REVIEW

**Comment by mhegazy** [comment]
@kaoDev @vutran @Strate @kikemx78 @ericanderson @andrewdewaal can you please review

**Comment by Strate** [comment]
Unfortunatelly, I am not using this library for now.

**Comment by ericanderson** [comment]
I don't use this library either but just quickly browsing, this doesn't change the target library version number yet includes a bunch of breaking changes. 

Why?

**Comment by kaoDev** [comment]
there are breaking changes, because I did not use the CellMeasuerer at first and so there slipped in some mistakes in the typings.
The additions in the Grid and Table class are made to have access to all the public methods and properties. I think there are still more classes with missing public probs, so help is appreciated ;)

**Comment by ericanderson** [comment]
My point is you removed some props. Was the old definition wrong? Was it right for a different version?

When people update to this as is, those removed props will break their code. Trying to understand.

**Comment by kaoDev** [comment]
I think it was for an old version of react-virtualized, but because the old typing were old and very incomplete I don't know for which version they were exactly

**Comment by ericanderson** [comment]
Okay. Reading through the original code, this seems correct. cc / @mhegazy

**Review by ericanderson — APPROVED** [review]

**Comment by kaoDev** [comment]
Could be that there will be another PR like this in the next days, there are still some gaps I want to fill and or correct.

**Comment by ericanderson** [comment]
Makes sense. Feel free to tag me when it comes out, i'll review it which should reduce the delay.

**Pull request merged**
