### PR TITLE
[apple-mapkit-js-browser] Resolve conflict with npm package

### PR DESCRIPTION
**Pull request by jablko**
As per https://github.com/DefinitelyTyped/dts-critic/blob/fe0c907b821ec879bbc8f99e506a3df40914ce6a/index.ts#L222

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by orta** [comment]
Yeah, good call 👍🏻 - I've made it so that  @Kilghaz @wsmd @chrisdrackett @moritzsternemann can agree and merge

**Review by peterblazejewicz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@jablko can this detail be mentioned somewhere in the README.md, it seems usefull little gem. thx!

**Comment by elibarzilay** [comment]
@Kilghaz @wsmd @chrisdrackett @moritzsternemann: re-ping?

**Review by moritzsternemann — APPROVED** [review]
I can approved this from my side. But I think @peterblazejewicz wanted a quick explanation for the name change in the types README.

**Comment by jablko** [comment]
@moritzsternemann @peterblazejewicz Will do :+1:

**Comment by elibarzilay** [comment]
@jablko -- what's the status of this?

**Comment by jablko** [comment]
@elibarzilay Haven't gotten to the README yet but I'm fine with merging this in the meantime or waiting. This PR is ready.

**Comment by jablko** [comment]
> @jablko can this detail be mentioned somewhere in the README.md, it seems usefull little gem. thx!

@peterblazejewicz Done :heavy_check_mark: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50247

**Pull request merged**
