### PR TITLE
Updating Flickity index.d.ts, adding 'hash' option

### PR DESCRIPTION
**Pull request by DBollebakker**
Added missing 'hash' option under options.
https://flickity.metafizzy.co/options.html#hash

### CODE REVIEW

**Review by aheber — APPROVED** [review]
Looks good and aligns with
https://flickity.metafizzy.co/options.html#hash

**Comment by aheber** [comment]
Thanks, @DBollebakker!

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Comment by DBollebakker** [comment]
> Thanks, @DBollebakker!

No problem, Flickity is a great addition for my assets and I love the great documentation that comes with it!

**Pull request merged**
