### PR TITLE
Added 'search' input reference to vue-select

### PR DESCRIPTION
**Pull request by bartversluijs**
- Added the 'search' HTML Input reference to `vue-select`

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

---

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sagalbot/vue-select/blob/e8d7abbf33417c843716d7cff1f50e92447a5341/src/components/Select.vue#L757

### CODE REVIEW

**Review by FloEdelmann — APPROVED** [review]

**Review by FloEdelmann — CHANGES_REQUESTED** [review]
Nice! There are two outstanding changes though, see below.

Additionally, please update the version to `3.16` in the very first line of this file.

**Review by FloEdelmann — APPROVED** [review]
Nice, thanks!

**Comment by elibarzilay** [comment]
For future reference, adding tests would have made this quicker.

**Comment by bartversluijs** [comment]
Ready to merge

**Pull request merged**
