### PR TITLE
update @types/webpack-dev-middleware to 4.0

### PR DESCRIPTION
**Pull request by tqma113**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/webpack/webpack-dev-middleware/commit/05e4a3295dc1be69a9a75bf7702c9bd142d2ef1d>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by tqma113** [comment]
Do I need to do anything else?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
(some non-related changes we're added via prettier, no reason to update v1, probabl this freaked people out).
Thx!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by tqma113** [comment]
🎉

**Comment by rvion** [comment]
hi @tqma113  , thanks for the update.

There is an issue with the typings: `@types/webpack-dev-middleware@4.1.0` it still imports the legacy `@types/webpack`

but it should not, because latest webpack ships with its own types.
It cause various issues

image

**Pull request merged**
