### PR TITLE
[gapi.client.sheets] automatic update

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
  - [x] Test the change in your own code. (Compile and run.)
  - [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  - [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
  - [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
  - [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

  Select one of these and delete the others:

  If changing an existing definition:
  - [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Maxim-Mazurok/google-api-typings-generator#google-api-typings-generator
  - [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
  - [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
  - [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

  ----

  🤖 This pull request was automatically created by [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) which generates types from [Google API Discovery Service](https://developers.google.com/discovery). Types were linted and tested before submission.

  If there is an issue with this pull request, consider [submitting a new issue](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new).

  Note you can also [use these types](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279) from our [`types` branch](https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/types) which is updated hourly.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by elibarzilay** [comment]
@Maxim-Mazurok, given that it's self identifying as an auto-generated PR, and the numerous force-pushes, and the fact that currently the only change is in a `Revision` comment should this be dropped?  (I'm guessing that a likely explanation is that you're using some tool that keeps pushing these...)

**Comment by Maxim-Mazurok** [comment]
@elibarzilay yes, this is automated PR.
Changes to the script to don't force-push if there's no new changes (https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/150) and to only open new PRs if something apart from Revision number changed (https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/151) are on the way. I wanted to give some time for other contributors to review them before merging.
I will merge it in a couple of hours and close this PR.
Please, don't close it yet, as the current version of script will open new one.
Sorry for any inconvenience it may have caused, we're testing this script on one type definition before including others.
Thanks for understanding!

**Comment by Maxim-Mazurok** [comment]
Changes are merged

**Comment by elibarzilay** [comment]
@Maxim-Mazurok -- thanks!

**Pull request closed without merging**
