### PR TITLE
Moved everything out of cordova/plugins

### PR DESCRIPTION
**Pull request by bowdenk7**
Refactored cordova plugins to have folders matching their npm package names. Also removed Push.d.ts as it has since been replaced by a different plugin.

### CODE REVIEW

**Comment by bowdenk7** [comment]
@RyanCavanaugh @rakatyal

**Comment by mhegazy** [comment]
@bowdenk7 can you address the CI server errors.

**Comment by bowdenk7** [comment]
Looks like I need to split up all the tests

**Comment by mhegazy** [comment]
@bowdenk7 can you please refresh this PR? the CI server should be working now.

**Comment by paulvanbrenk** [comment]
@bowdenk7 gentle ping

**Pull request merged**
