### PR TITLE
[redux-form] Allow FormWarnings element to be an array of strings

### PR DESCRIPTION
**Pull request by DavyJohnes**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by DavyJohnes** [comment]
> @DavyJohnes The Travis CI build failed! Please [review the logs for more information](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/469586527?utm_source=github_status&utm_medium=notification).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!

Don't think it is related to my changes, however I fixed it in next commit.

**Comment by DavyJohnes** [comment]
Guys, can someone reviews this PR please? It is quite important for me.

**Comment by maddijoyce** [comment]
@DavyJohnes sorry I haven't used redux-form in a little while. Any chance you can show me where the FormWarnings are used in the redux-form repo?

**Comment by DavyJohnes** [comment]
> @DavyJohnes sorry I haven't used redux-form in a little while. Any chance you can show me where the FormWarnings are used in the redux-form repo?

Sure. Here is the place my changes related to (I am not 100% sure, but this is what I found in source code during fast search): https://github.com/erikras/redux-form/blob/e51957b115e545e7b92680be38c98322264d1ad0/src/ConnectedFieldArray.js#L29. In this particular case, when I use `FieldArray` then name of each field is equal to `fieldName[N]`, where `N` is index of particular field in field array. So, when redux-form tries to do `getIn(syncWarnings, `${name}._warning`)` (which is equal to  `getIn(syncWarnings, `fieldName[0]._warning` in my case) it expects `syncWarnings` to be an array of strings.

**Review by maddijoyce — APPROVED** [review]
Looked at the array warning code, this makes sense.

**Review by sandersn — CHANGES_REQUESTED** [review]
Please add tests for the change.

**Pull request closed without merging**
