### PR TITLE
Add `onerror` and `runInDebug` to Ember typings.

### PR DESCRIPTION
**Pull request by chriskrycho**

### CODE REVIEW

**Comment by jedmao** [comment]
Please link to the documentation for these additions.

**Comment by chriskrycho** [comment]
Sorry, missed that step!

- [`runInDebug`](https://emberjs.com/api/classes/Ember.html#method_runInDebug)
- [`onerror`](https://emberjs.com/api/classes/Ember.html#event_onerror)

**Review by rbuckton — APPROVED** [review]
Looks good. Thanks for the contribution!

**Comment by QuantumInformation** [comment]
awesome, about to jump into the ts-ember bandwagon

**Pull request merged**
