### PR TITLE
Add declaration for the Swipe

### PR DESCRIPTION
**Pull request by kant2002**
Type definitions for Swipe 2.0
Project: https://github.com/thebird/Swipe

### CODE REVIEW

**Comment by vvakame** [comment]
*swipe/swipe.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/swipe
  * http://bower.io/search/?q=swipe
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (swipe/swipe-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
umm... https://www.npmjs.com/package/swipe is already exists.
https://www.npmjs.com/package/swipe.js is not exists. it is adhoc fix, but please rename to swipe.js/swipe.js.d.ts.

**Comment by kant2002** [comment]
Could I ask why `swipe.js`? Everywhere project referenced as just Swipe. That's why I use that name.
It's not big deal to rename, but I want to know in case I will add another library in the future.

**Comment by vvakame** [comment]
@kant2002 please check this document. http://definitelytyped.org/guides/contributing.html#naming-the-file

**Comment by kant2002** [comment]
I already read it. 
I actually first install that package via `bower`
I too could not find `swipe` package via bower website search, but when do from command line it that package is found. Also seems that package is referred to swipe, not swipe.js.

on NPM package swipe is referring to the another package.
Do you still think that renaming is correct way to go?

**Comment by vvakame** [comment]
@kant2002 umm, okey. but npm package name is high priority than bower's. your definition may change in the future.

**Pull request merged**
