### PR TITLE
[relay-runtime] Improve type inference for `readInlineData`

### PR DESCRIPTION
**Pull request by janicduplessis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This updates `readInlineData` to use the same technique as `useFragment` to infer its data type. This avoids having to annotate the function with a type parameter.

Before:

```ts
function readData(
  dataRef: FragmentRef<Module_data>,
) {
  const data = readInlineData<Module_data>(
    graphql`
      fragment Module_data on Data @inline {
        id
      }
    `,
    dataRef,
  );
}
```
After:

```ts
function readData(
  dataRef: Module_data$key,
) {
  const data = readInlineData(
    graphql`
      fragment Module_data on Data @inline {
        id
      }
    `,
    dataRef,
  );
}
```

Note that this is a breaking change at the type level since the generic parameter type is now different. In most cases just removing it will fix the problem. The ref is also expected to be of type `Module_data$key` instead of `FragmentRef<Module_data>`.

### CODE REVIEW

**Review by Stephen2 — APPROVED** [review]
Seems much better.  Seems to match: https://github.com/facebook/relay/blob/main/packages/relay-runtime/store/readInlineData.js (slightly different methodology, but seems cleaner, and probably TypeScript works differently than Flow).

Has tests.

I remember this typing of `readInlineData` to be disappointing when last used, so thank you!

If it's breaking change, I don't know release policy.

**Comment by maraisr** [comment]
Hi there @janicduplessis looks great so far thank you so much!! Few points ill make just gotta link you. But the KeyData stuff already exists elsewhere, maybe just import those.

That and have a few broken tests. 

On the outset yeah, just to retain major version parity with Relay itself, lets do a minor bump here?? @alloy have we done breaking changes before?

**Comment by janicduplessis** [comment]
@maraisr I was considering code sharing, but then the key data stuff is in react-relay, which we should not depend on in this. This would require moving KeyData stuff in this package and update all react-relay to use it from this instead. I can do that, but would require more significant changes.

Yea getting a weird error from `react-relay` tests (although I didn't change anything in that package), gonna investigate in a bit.

**Comment by janicduplessis** [comment]
Turns out react-relay had readInlineData tests, removed those since it makes more sense to have them in relay-runtime.

**Comment by maraisr** [comment]
> @maraisr I was considering code sharing, but then the key data stuff is in react-relay, which we should not depend on in this. This would require moving KeyData stuff in this package and update all react-relay to use it from this instead. I can do that, but would require more significant changes.

Ah yeah i see that, 100% my bad 😅 really it should be in reverse, relay-runtime own that type, for react-relay to import. But its as you say, not the purpose of this PR. 

Let me just double check re release policy, then we can merge this guy.

**Review by maraisr — APPROVED** [review]

**Pull request merged**
