### PR TITLE
@ember/routing Make Route generic accepting a Model type

### PR DESCRIPTION
**Pull request by mongoose700**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://api.emberjs.com/ember/3.25/classes/Route/methods/model?anchor=model
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header (it does not)

This is mostly an improvement to the existing types to allow for declaring the type for the model of the route. For backwards compatibility, I'm defaulting it to `any`. I also made a slight change in making `modelFor` return `any` instead of `{}`, since it can return `undefined` or `null` if either of those are returned by the `model` hook of the provided route, and it will return `undefined` if the route hasn't run (because it isn't a parent) or the route name was invalid.

Further progress could be made with this to make a registry of routes, such that `paramsFor` or `modelFor` could identify what types they're supposed to return based on what routes have been registered.

### CODE REVIEW

**Comment by jamescdavis** [comment]
I actually had this on my todo list at one point and I think it's a good idea. @chriskrycho @dfreeman do you agree?

**Comment by dfreeman** [comment]
Agreed! This is a PR I've come close to making several times 🙂

**Review by jamescdavis — CHANGES_REQUESTED** [review]
This looks great and thank you for the thorough tests! For completeness and consistency, can you also type the `model` parameter on ` renderTemplate` and `setupController` with the `Model` generic?

**Comment by mongoose700** [comment]
> This looks great and thank you for the thorough tests! For completeness and consistency, can you also type the `model` parameter on ` renderTemplate` and `setupController` with the `Model` generic?

Added. It could also make sense to add `Controller` as another generic argument, though I would expect it to be used a lot less frequently.

**Review by jamescdavis — APPROVED** [review]
@mongoose700 I've thought the same about making Controller generic too, but this looks good as a first step.

**Comment by mongoose700** [comment]
Ready to merge

**Comment by chriskrycho** [comment]
Was swamped and unable to comment, but wanted to say two things:

1. Thank you for doing this! I have also had it on my mental to-do list for a long time!
2. Would you mind doing a fast-follow where we switch the type params from `any` to `unknown`? That *should* be a safe change, in that anything that "breaks" as a result is a bug, but will substantially increase the safety of the types here.

**Comment by mongoose700** [comment]
Sure! I didn't before because I thought it would be a forbidden breaking change.

**Comment by mongoose700** [comment]
Made a PR for it here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51823

**Pull request merged**
