### PR TITLE
[i18n-js] Added toTime

### PR DESCRIPTION
**Pull request by danilobuerger**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L978
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ypresto** [comment]
@danilobuerger
`toTime()` was omitted intentionally, as it is not documented in README.md.
 [date formatting section in README](https://github.com/fnando/i18n-js/blob/4070e7add941aaba6053b98a5150f8fb3c91622d/README.md#date-formatting) points `I18n.l()` (or `I18n.localize()`): 

```rb
I18n.l("date.formats.short", "2009-09-18");           // yyyy-mm-dd
I18n.l("time.formats.short", "2009-09-18 23:12:43");  // yyyy-mm-dd hh:mm:ss
```

Perhaps `toTime()` is internal function used by [`localize()` method](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L812).

**Comment by danilobuerger** [comment]
@ypresto `toTime` has to be used if the scope does not begin with `time` or `date`:
```
// If you provide a scope that matches the `/^(date|time)/` regular expression
// then the `value` will be converted by using the `I18n.toTime` function.
```
Also the function is documented like any other function in code:
```
// Convert the given dateString into a formatted date.
```
If it was for internal use why was it exported then?

I think it is not our job to assume those things. Fact is the function is being exported and is available so it should also be typed.

**Comment by ypresto** [comment]
> `toTime has to be used if the scope does not begin with time or date`

Indeed! I'll merge this. Thanks!

----

There are exported but clearly internal methods, for example `I18n.createTranslationOptions`  and `I18n.lookup`. Note that they also have jsdoc.

While I think it's i18n-js's job too, including them decreases maitainability of d.ts. So I'm choosing methods carefully. :)

**Comment by ypresto** [comment]
Looks good for me :+1:

**Review by ypresto — APPROVED** [review]
Looks good for me 👍

**Comment by danilobuerger** [comment]
@ypresto now its documented, see https://github.com/fnando/i18n-js/blob/master/README.md

**Pull request merged**
