### PR TITLE
[zarinpal-checkout] Exported Definition Namespace

### PR DESCRIPTION
**Pull request by iamomiid**
Exported Definition Namespace for zarinpal-checkout

### CODE REVIEW

**Comment by iamomiid** [comment]
@sandersn The CI failure is a test-all failure unrelated to my changes. Thanks for taking a look!

**Comment by sandersn** [comment]
master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

**Comment by iamomiid** [comment]
> master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

Thanks. Merged from master.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## zarinpal-checkout ([<kbd>unpkg</kbd>](https://unpkg.com/browse/zarinpal-checkout@latest/))
was missing the following properties:
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5c9dce4a4f2b82cb2de4eb522fc8876ef36e3311
</p>

**Pull request merged**
