### PR TITLE
[react-datepicker] Custom popper.js modifiers

### PR DESCRIPTION
**Pull request by tsvetkovda**
Added ability to provide custom Popper.js modifier
Playground: [codesandbox](https://codesandbox.io/s/react-datepicker-custom-modifier-36pnn?file=/src/App.tsx)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Hacker0x01/react-datepicker/blob/master/src/popper_component.jsx#L57
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by apepper** [comment]
Could you also adjust the dependencies? Currently this is specified:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a610fc0ffdf3efd5b5c7fcc338226e2ee3418df7/types/react-datepicker/package.json#L4

According to https://github.com/Hacker0x01/react-datepicker/releases/tag/v4.0.0 `react-datepicker` now uses version "^2.9.2" of "@popperjs/core" (see https://github.com/Hacker0x01/react-datepicker/blob/736c555bade634bea1c1ef2f892513372fb14d54/package.json#L115 ).

**Comment by tsvetkovda** [comment]
@apepper Thank you for your guidance

**Comment by peterblazejewicz** [comment]
@tsvetkovda please update PR description (what is really changed after all those updates, removing comments about parts already merged by other changes)

**Review by orta — APPROVED** [review]
Seems reasonable to me

**Comment by tsvetkovda** [comment]
Ready to merge

**Pull request merged**
