### PR TITLE
[@types/node-jose] Add kid for the rawKey type

### PR DESCRIPTION
**Pull request by WangHansen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/cisco/node-jose/blob/85610d6fdf411c72f58d15197e6f935e0b20a695/lib/jwk/basekey.js#L81
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by WangHansen** [comment]
@nadunindunil

**Comment by nadunindunil** [comment]
Hi @WangHansen ,
This is great. nice contribution. I went through your code and found a few questions,
- Can you describe what `node-jose-1.1.4.tgz` suppose to do?
- Could you please mention an example where RawKey uses kid property. perhaps an example JS code would be enough.

**Review by nadunindunil — CHANGES_REQUESTED** [review]
Hi @WangHansen ,
This is great. nice contribution. I went through your code and found a few questions,
- Can you describe what `node-jose-1.1.4.tgz` suppose to do?
- Could you please mention an example where RawKey uses kid property. perhaps an example JS code would be enough.

**Comment by WangHansen** [comment]
@nadunindunil 
- Sorry about the file, I think it is generated during the `npm test` process. I already have it removed.
- Of course, consider when I have 3 keys(generated/imported as string) in a keystore and try to get their key ids:
```javascript
let keyids = []
keystore.all().forEach((rawKey) => keyids.push(rawKey.kid));
```
Without the kid property, I will get the following message:

image

The only other way to achieve the same results is to use the `toJSON()` method that returns an `object` type result, which doesn't take advantage of the type checking.

**Review by nadunindunil — APPROVED** [review]
Thank you @WangHansen

**Pull request merged**
