### PR TITLE
Defintions for webpack dev server

### PR DESCRIPTION
**Pull request by maestroh**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
*webpack-dev-server/webpack-dev-server.d.ts*

Checklist

* [X] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/webpack-dev-server - http://github.com/webpack/webpack-dev-server
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (webpack-dev-server/webpack-dev-server-tests.ts or webpack-dev-server/webpack-dev-server-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
please rename webpack-dev-server/webpack-dev-server-test.ts to webpack-dev-server/webpack-dev-server-tests.ts

**Comment by maestroh** [comment]
@vvakame Any other changes?

**Comment by vvakame** [comment]
👍

**Pull request merged**
