### PR TITLE
swiper: Fix exports.

### PR DESCRIPTION
**Pull request by mattmccutchen**
See https://stackoverflow.com/q/52673117 .

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: `swiper` module [CommonJS version](https://github.com/nolimits4web/swiper/blob/v4.2.6/dist/js/swiper.js) / [ES6 version](https://github.com/nolimits4web/swiper/blob/v4.2.6/dist/js/swiper.esm.bundle.js); [`swiper/dist/js/swiper.esm` module](https://github.com/nolimits4web/swiper/blob/v4.2.6/dist/js/swiper.esm.js)
- [X] Increase the version number in the header if appropriate. _(N/A: The issue has been the same since the version number currently in the header, 4.2.)_
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. _(Already there)_

### CODE REVIEW

**Comment by ematseruk** [comment]
@mattmccutchen do you need any help with the investigation?

**Comment by mattmccutchen** [comment]
> @mattmccutchen do you need any help with the investigation?

Got it, Microsoft/dtslint#143 will fix the problem.  We'll have to wait for that to be deployed to the "production" branch of dtslint.

**Comment by mattmccutchen** [comment]
FTR, I wouldn't say the package maintainers have been snoozing, but if the YSYL clock gets a DefinitelyTyped maintainer to pay some attention to Microsoft/dtslint#143 (which is the blocker), that would be helpful.

**Comment by mattmccutchen** [comment]
Inspired by https://github.com/Microsoft/dtslint/pull/143#issuecomment-429144999, I went ahead and fixed `no-declare-current-package` (for Swiper v4 only), and it happens that the revised PR is no longer blocked on Microsoft/dtslint#143 being deployed.

**Review by odahcam — APPROVED** [review]
I see opportunities for improvements and this LGTM!

**Pull request merged**
