### PR TITLE
Updated webpack-dev-middleware to v2

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/webpack-dev-middleware/blob/master/breaking-changes.md
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

cc @shellscape: Does this cover the changes correctly?

### CODE REVIEW

**Comment by shellscape** [comment]
@donaldpipowitch thanks for the ping 😄 I'm no TypeScript expert, but that appears correct. I'll also link to this in the README for folks who need this typedef.

**Comment by donaldpipowitch** [comment]
Thank you for reviewing this! ♥️

**Comment by Flarna** [comment]
This change broke karma-webpack and koa-webpack as they still use webpack-dev-middleware in v1 (see referenced PRs). Maybe v1 typings should be kept?

**Comment by shellscape** [comment]
koa-webpack will be updated to use wdm@2 soonish. the webpack team is testing leveraging that package and we've got some tests to run yet. If this package is versioned properly, it shouldn't have caused any havok (and I don't mean that to insinuate that it is not)

**Comment by paulvanbrenk** [comment]
Didn't realize that these changes were in 2.x and the typing was still targeting 1.x, the correct way to handle would've been to have kept a v1 folder for the original typings. @donaldpipowitch can you make that change?

https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by Flarna** [comment]
Regarding tests: There was an issue (#22172) causing that dependents were not tested which is fixed meanwhile.
Not sure if it is worth to keep a V1 version if dependents get updated soon anyway. The two fixes I proposed are simple and should be ok till update is done.

**Comment by donaldpipowitch** [comment]
Oh snap. This slipped through... This should have been a new major version as announced in the title, but I forgot to update the file header. I'm sorry. Sadly I have no computer for some days. It would be great if this could be fixed by someone until I'm back again. 

Sorry.

**Comment by donaldpipowitch** [comment]
First attempt to fix this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22661.

**Pull request merged**
