### PR TITLE
[Jest] MockInstance functions should return self

### PR DESCRIPTION
**Pull request by gstamac**
Functions of `MockInstance` interface should return self as it is defined [here](https://github.com/facebook/jest/blob/96546d7b5c8c11133f004c643eb34c370f379382/packages/jest-mock/src/index.ts#L101)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/facebook/jest/blob/96546d7b5c8c11133f004c643eb34c370f379382/packages/jest-mock/src/index.ts#L101>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by gstamac** [comment]
Can somebody review this. Thanks.

**Comment by sandersn** [comment]
Can an owner review this? I just looked at the structure and here's what I got:

1. Changing the return type of WhenMock methods to `this` is fine, as long as returning `this` is intended by the package. It's not a good default because it's a little expensive.
2. Switching WhenMock to extend MockInstance instead of Mock might be correct. I need somebody to comment who knows about the intent of the types.
3. Isn't jest switching to typescript anyway? Are these types even needed any more?

Paging @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @antoinebrault @Favna @aldentaylor @immanuel192

**Comment by Favna** [comment]
Just reporting in that I have looked at the changes but I can't quite give an ultimatum since I lack this level of knowledge of Jest - I only use the basics of it.

**Review by immanuel192 — APPROVED** [review]
Looks good to me. 

Seem like `Mock<T>` is inherited from `MockInstance<T>` and is a newable.  Switching to use `MockInstance` can be a good point.

**Pull request merged**
