### PR TITLE
Added onrendered function

### PR DESCRIPTION
**Pull request by Firenter**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tan9** [comment]
As https://github.com/niklasvh/html2canvas/commit/467ff8748209c82640a5afec4a4b730cf5451b72 described:

> options.onrendered is deprecated, html2canvas returns a Promise containing the canvas

**Comment by Firenter** [comment]
@tan9 That's cool and all, but that's still in beta! I'm going off the most recent bower package here.

**Comment by Firenter** [comment]
Guess I'll just make my own for this project.

**Comment by tan9** [comment]
@Firenter You can try the previous version aligned to html2canvas v0.4.1 here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/94d8775a947f626269b06ccadd6f5e61839389d0/html2canvas/html2canvas.d.ts

**Pull request closed without merging**
