### PR TITLE
add baidu-aip-sdk

### PR DESCRIPTION
**Pull request by bangbang93**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/baidu-aip-sdk/AipImageSearch.d.ts
1. types/baidu-aip-sdk/AipKg.d.ts
1. types/baidu-aip-sdk/baidu-aip-sdk-tests.ts
1. types/baidu-aip-sdk/AipImageClassify.d.ts
1. types/baidu-aip-sdk/client/requestInfo.d.ts

<details>
<summary>as well as these 6 other files...</summary>
<p>types/baidu-aip-sdk/client/baseClient.d.ts, types/baidu-aip-sdk/auth/devAuth.d.ts, types/baidu-aip-sdk/auth/devAuthToken.d.ts, types/baidu-aip-sdk/auth/cloudAuth.d.ts, types/baidu-aip-sdk/http/httpClient.d.ts, types/baidu-aip-sdk/auth/bceAuth/auth.d.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e16b860f9b0b59603396083208c43a56dbab464e
</p>

**Comment by jakebailey** [comment]
Why are so many of the types `any`?

**Comment by bangbang93** [comment]
> Why are so many of the types `any`?

The file was generated from source code comments rather than being manually written based on documentation. Therefore, for parts where the source code documentation did not specify the type, any was used as a fallback. I am not an employee of Baidu, so I carefully reviewed only the parts of the API that I called, while the rest were auto-generated according to the documentation.

**Review by sandersn — APPROVED** [review]

**Comment by bangbang93** [comment]
Ready to merge

**Pull request merged**
