### PR TITLE
[chrome] add chrome.userScripts

### PR DESCRIPTION
**Pull request by raju-mechatronics**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [ Chrome Docs for chrome.userScripts ](https://developer.chrome.com/docs/extensions/reference/api/userScripts)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/test/index.ts
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 38e81aff74524cc05fe8501b93edf659f19423b9
</p>

**Comment by Timeraa** [comment]
Hey @raju-mechatronics, I think you forgot to add `chrome.runtime.onUserScriptConnect` & `chrome.runtime.onUserScriptMessage`
-> Reference: https://developer.chrome.com/docs/extensions/reference/api/userScripts#messaging

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1964ca01d6b09805fd56cfd9c279a7619ca113e8
</p>

**Comment by raju-mechatronics** [comment]
Thanks for your feedback, @Timeraa, I appreciate you bringing this to my attention. I took a look at the documentation you provided and made sure to include the necessary additions for chrome.runtime.onUserScriptConnect and chrome.runtime.onUserScriptMessage in my implementation.

If you have any further suggestions or concerns, please let me know.

**Comment by Timeraa** [comment]
Also I'm not sure if this is something that should be added but the new user scripts basically don't have any chrome api exposed to them except some of some constants and the connect / message apis if the world is configured. Perhaps this could be a separate exposed type or something?

**Comment by raju-mechatronics** [comment]
@Timeraa , I am not sure but there would be security issues if Chrome API is exposed to this userScript. Also this should be added as chrome supports it.

**Review by jakebailey — APPROVED** [review]

**Comment by raju-mechatronics** [comment]
Ready to marge

**Pull request merged**
