### PR TITLE
Fix CORS definition on restify

### PR DESCRIPTION
**Pull request by fortuna**
This fixes the issue discussed on https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2c0494ee207b36a5a86c8328bc428109ad1d94c9#commitcomment-22006629

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2c0494ee207b36a5a86c8328bc428109ad1d94c9#commitcomment-22006629
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by fortuna** [comment]
@mhegazy: FYI

**Comment by stevehipwell** [comment]
@fortuna did you start with the latest version of these typings as it looks like you've made significant changes that look like a regression.

E.g. using `declare module 'restify' {}`

**Comment by stevehipwell** [comment]
:-1:

**Comment by fortuna** [comment]
I'm sorry for the bad PR. Trying again.
Would you mind taking another look?

**Comment by stevehipwell** [comment]
@fortuna if you add a test to _restify-tests.ts_ to show the correct use of CORS then I can evaluate your change and we can make sure it works correctly.

**Comment by fortuna** [comment]
@stevehipwell : Done

Example borrowed from the official documentation: http://restify.com/#bundled-plugins

**Comment by stevehipwell** [comment]
@fortuna unless you are using the static `CORS` values (they look internal use only) I would suggest that you export CORS as a function and an interface:
``` typescript
export function CORS(options?: CORSOptions): RequestHandler;
export interface CORSOptions {
    origins?: string[];
    credentials?: boolean;
    headers?: string[];
}
```

**Comment by stevehipwell** [comment]
👍

**Comment by fortuna** [comment]
Thanks for the review @stevehipwell!

Do you have an idea of how long it takes to get the npm published?

**Comment by stevehipwell** [comment]
@fortuna once it has been merged publishing to npm is rapid, however getting code merged seems to be pretty slow at the moment; I've got three pull requests that have been open for almost a fortnight.

**Pull request merged**
