### PR TITLE
[jexl] TransformFunction accepts multiple args

### PR DESCRIPTION
**Pull request by nigelzor**
The jexl documentation only has examples of zero- and one-argument Transforms, but internally all args are passed through with `Function.prototype.apply`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/TomFrost/Jexl/blob/master/lib/evaluator/handlers.js#L142
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
CC @m-tomczyk

**Comment by m-tomczyk** [comment]
@nigelzor It seams that you are right. I was mislead by jsdoc's provided above function and tests case that suggest wrapping params in object: https://github.com/TomFrost/Jexl/blob/7ebc5f971bc47c9dea652cb4bdceaecb6d86e1eb/test/Jexl.js#L38 . But there seams to be more to this as I can see that according to docs there should be also handler function https://github.com/TomFrost/Jexl/blob/7ebc5f971bc47c9dea652cb4bdceaecb6d86e1eb/lib/Jexl.js#L72 and this is impossible as rest parameter can only be last one. That might be jus error in docs - I did quick scan over jexl source and couldn't place where this callback would be called.
I'll try to find some time and look deeper into it tomorrow, or maybe you can shed light on that?

**Comment by nigelzor** [comment]
@m-tomczyk I think that jsdoc is just out of date. From the [changelog](https://github.com/TechnologyAdvice/Jexl/blob/master/CHANGELOG.md#v100---2015-03-04) for version 1.0.0:
> Transform syntax has changed. Arguments are now passed in parentheses, and multiple arguments can be defined. Arguments are no longer limited to object literals.

**Review by m-tomczyk — CHANGES_REQUESTED** [review]
@nigelzor This is all good to go as code goes. 

I have only one nitpick: Jsdocs over transform function definition should be changed so they are in sync of what is really happening and maybe add annotation that it differs from original jsdoc.

**Comment by nigelzor** [comment]
@m-tomczyk I've updated the docs here, and submitted a [PR in jexl](https://github.com/TomFrost/Jexl/pull/41) to update them there.

**Review by m-tomczyk — APPROVED** [review]
Thanks! Good to go now

**Pull request merged**
