### PR TITLE
Correct library misnaming: highlight.js

### PR DESCRIPTION
**Pull request by joshgoebel**
**The correct name for our project and NPM library is `highlight.js`.**  

It doesn't help that long ago there was a `highlightjs` on NPM as well (we've since deprecated it).  Sadly, DefinitelyTyped has deprecated the WRONG library... `highlight.js` was deprecated when `highlightjs` should have been.

This simply renames the folder, but I'm not sure what else might need to
be done here to set things back right again, but someone please let me
know and I'm happy to try and facilitate.

This has been causing confusion for our TypeScripts users as they will
install the wrong package and then they get nothing but an empty package
that **effectively** does nothing.  The magic seems to be this package, which imports
then re-export our types.

I don't understand how to fix the failing tests. I think perhaps it's
confused that now the library names actually match properly?

```
Error: /Users/jgoebel/git/DefinitelyTyped/types/highlight.js/index.d.ts:7:1
ERROR: 7:1   expect          TypeScript@4.3 compile error:
Circular definition of import alias 'highlightjs'.
ERROR: 7:30  no-self-import  Declaration file should not use a global import of itself. Use a relative import. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-self-import.md
```

Reference:

- https://github.com/highlightjs/highlight.js/issues/2682
- https://www.npmjs.com/package/highlight.js (active)
- https://www.npmjs.com/package/highlightjs (deprecated)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by joshgoebel** [comment]
@ffflorian Can you help?  I don't know how to make the tests happy or if that is even sufficient to properly rename this and deprecate `@types/highlightjs`.

**Comment by ffflorian** [comment]
@joshgoebel I created a PR for a missing change: https://github.com/joshgoebel/DefinitelyTyped/pull/1

**Comment by joshgoebel** [comment]
Ah, progress. @ffflorian Thanks for assist!

**Comment by ffflorian** [comment]
Looks good so far, I'm just not sure if the DefinitelyTyped bot can publish a previously deprecated package.

**Review by andrewbranch — APPROVED** [review]
Hmmmm, I suspect this will take some manual intervention. I’ll keep an eye on it and update the status here.

**Comment by andrewbranch** [comment]
Sorry, I think I jumped the gun on merging this. @types/highlight.js _should_ be deprecated because highlight.js _ships its own types_. I’ve quickly reverted the merge at #52132 so we can discuss further. Sorry for the confusion.

**Comment by andrewbranch** [comment]
> This has been causing confusion for our TypeScripts users as they will install the wrong package and then they get nothing but an empty package that effectively does nothing.

This is the expected behavior. They also get a message upon installing that says

> npm WARN deprecated @types/highlight.js@10.1.0: This is a stub types definition. highlight.js provides its own type definitions, so you do not need this installed.

which is correct. `@types/highlight.js` is deprecated because it does nothing, because `highlight.js` includes types. Your TypeScript users should simply uninstall `@types/highlight.js`, though the only downside to them if they don’t is seeing the above deprecation message. This is what happens to all `@types` packages when their implementation library chooses to start shipping types. In other words, **deprecating a `@types` package does not imply that its implementation library is deprecated.**

What to do about `@types/highlightjs` is, I think, debatable. Typically, when an implementation library is deprecated on npm, we simply remove the typings from DT (because they will need no future updates) without deprecating the `@types` counterpart. The idea is that if you are choosing to use a deprecated npm library, you still have good reason to use the corresponding `@types` library, and you don‘t really need a deprecation message from both. The `@types` are still valid. 

I think the only thing we may want to do here is delete highlightjs from DT, since it will need no future updates. It would be wrong to add it to `notNeededPackages.json`, because that will result in a deprecation message that says `highlightjs provides its own type definitions`, which is false. If there was a really strong reason to manually deprecate `@types/highlightjs` with a custom message, we could do that, but I’m skeptical that that’s necessary. If someone is still using `highlightjs`, they have good cause to use `@types/highlightjs`.

**Comment by joshgoebel** [comment]
So `highlightjs` actually exists (and exports `highlight.js`) to solve the problem of the deprecated `highlighjs` npm package...??

> What to do about @types/highlightjs is, I think, debatable.

It should probably be removed.  The last `highlighjs` (note lack of period) package was 9.16.2 which is (in many ways) an entirely different codebase than the modern code.  Just exporting the 10.1 types for 9.16.2 sounds like a pretty bad idea.

---

My larger issue (that led to this whole sequence)... users TS compilation does not work.  The types evidently aren't found for some reason?  

```
Could not find a declaration file for module 'highlight.js/lib/core'. 
```

But after they install `@types/highlighjs` (wrong name) MAGICALLY everything starts working.  Leading me to believe that there is some magic in the `@types` system itself baked into TypeScript.  Is this incorrect thinking?  If you had any thoughts on the large issue I'd certainly appreciate it.  

And my apologies if this whole PR was misguided and I'm trying to solve the problem in the wrong place.

I can easily reproduce this with a tiny project using just `highlight.js`:

```
 % tsc b.ts --strict --esModuleInterop               2.7.1
b.ts:4:18 - error TS7016: Could not find a declaration file for module 'highlight.js/lib/core'. '/Users/jgoebel/work/highlight.js/build/lib/core.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/highlight.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'highlight.js/lib/core';`
```

Installing the incorrectly named `@types/highlighjs` immediately solves this and results in a clean compile with no errors.

**Comment by andrewbranch** [comment]
Blaasdfhalsdjf. I just noticed that `@types/highlightjs` [depends on and re-exports higlight.js](https://unpkg.com/browse/@types/highlightjs@10.1.0/index.d.ts), and is versioned at 10.1.0. I understand what you’re getting at now. It seems that was maybe a relic of a past mistake, so there is some confusion on both sides here. We probably should at least deprecate `@types/highlightjs@10`. (It can’t actually be unpublished, of course.)

> users TS compilation does not work

What are the contents of `b.ts`? I’m guessing something like this:

```ts
import hljs from 'highlight.js/lib/core';
```

Looking at your definition files, the error should go away if, anywhere else in the program, there is an import of `'highlight.js'` (without a trailing path). This is simply because of how the types are organized into [a single file](https://github.com/highlightjs/highlight.js/blob/main/types/index.d.ts#L247). When a user tries to import `'highlight.js/lib/core'`, if we have not yet found that `index.d.ts` file yet, we have no way of knowing that it magically declares a module called `'highlight.js/lib/core'`. So instead, we go searching in `node_modules/highlight.js/lib/core` and we see only a JS file. (We should _probably_ avoid emitting the error message that says to install `@types/highlight.js` once we see that your package.json has a `types` field.) At any rate, this can be fixed in your own repo by placing the types for `lib/core.js` at `lib/core.d.ts` instead of declaring them ambiently in the index file.

> Leading me to believe that there is some magic in the `@types` system itself baked into TypeScript.

This is true. The default value for the `typeRoots` field in tsconfig.json includes `node_modules/@types`, so anything in there gets _eagerly_ pulled into users’ programs unless they override that default somehow. That’s how this strategy of ambiently declaring `'highlight.js/lib/core'` could work (by default) if it was shipped through DT but not through your own package.

**Comment by joshgoebel** [comment]
> We probably should at least deprecate @types/highlightjs@10

Agree.  Some (or all) versions of `@types/highlightjs@9` may be just fine... 

> We should probably avoid emitting the error message that says to install @types/highlight.js once we see that your package.json has a types field

That sounds like it might be a better choice. :)

>  That’s how this strategy of ambiently declaring 'highlight.js/lib/core' could work (by default) if it was shipped through DT

I presume this is why installing `@types/highlightjs` works now?  It places our types "in scope" of typeRoots by way of the stub... yes?

>  I’m guessing something like this:

Indeed... and you're correct the following works:

```
import 'highlight.js' # added so the ambient modules can be found
import hljs from 'highlight.js/lib/core'
```

>  this can be fixed in your own repo by placing the types for lib/core.js at lib/core.d.ts instead of declaring them ambiently

Ok... OR someone could also add us to `typeRoots` I'd imagine?  But... _isn't this exactly the problem ambient modules were intended to solve?_  Or are they really only intended to work if someone FIRST includes the library itself (with no trailing path)?

**And thanks for your detailed explanation.  Its been super helpful.**

**Comment by joshgoebel** [comment]
I guess the behavior I was *hoping for* would be:

- I see `highlight.js/lib/core`
- Look for  `highlight.js/lib/core.d.ts`
- If not found, look for `highlight.js` package.json `types` key
- Look for any ambient modules

Is there any reason that magic doesn't happen by default?

**Comment by andrewbranch** [comment]
I’ll discuss with the team how we want to handle `@types/highlightjs@10`.

> That sounds like it might be a better choice.

https://github.com/microsoft/TypeScript/issues/43488

> I presume this is why installing `@types/highlightjs` works now? It places our types "in scope" of typeRoots by way of the stub... yes?

Yes, combined with the fact that it’s incorrectly/accidently/🤷 reexporting types from `highlight.js` instead of providing the old typings for `highlightjs`.

> But... _isn't this exactly the problem ambient modules were intended to solve?_

No. Ambient modules are good for things like `"fs"` or `"path"` which are part of `@types/node` instead of `@types/fs` and `@types/path`, where the module name can’t or isn’t supposed to be representative of a location on disk. Another issue that you already have with these ambient module declarations is that someone who’s natively using ESM in Node 14 will be broken, because the correct module specifier for them is `"highlight.js/lib/core.js"` (with the JS extension). If you place a declaration file alongside core.js, that module specifier will Just Work™. As it is now, it doesn’t work because it’s not a string match.

> Is there any reason that magic doesn't happen by default?

I also considered this, but I’m pretty sure it’s intentional that this doesn’t happen. Often times, index files import and re-export _everything_ from the whole package, and being able to avoid inflating your program size with all that if you just drill into a subdirectory is a feature, not a bug.

**Comment by joshgoebel** [comment]
>  combined with the fact that it’s incorrectly/accidently/🤷 reexporting types 

Yes, right - incorrect exporting the v10 types.  I just trying to understand the WHY and HOW. :-)

> Another issue that you already have with these ambient module declarations is that someone who’s natively using ESM in Node 14 will be broken, because the correct module specifier for them is "highlight.js/lib/core.js"

I played around with this a bit... is there no way to specify ambient modules for both paths?

>  If you place a declaration file alongside core.js, that module specifier will Just Work™

I may finally go that way... but I've also been told we need 190 `t.ds` files, _one for every language_ you can import individually... and it seems clear that's a silly requirement and that ambient modules are surely the solution there (no?) - since someone must always import the top-level before having any languages would make sense.  I'm always a bit hesitant when someone tells me "add a bunch of files!" or do something the computer should be smart enough to figure out. :-)

The whole "you need a separate file for every import point" has always felt wrong to me somehow.

**Comment by andrewbranch** [comment]
Don’t conflate normal ambient modules with _pattern_ ambient modules (ones with `*` in the name), though. Pattern ambient modules do indeed serve well for replacing 190 identically-shaped modules with a single declaration. But that’s not what you’re dealing with for lib/core.js.

Regarding the incorrect `@types/highlightjs`: this keeps getting worse. The v9 version of that package is wrong in the exact same way. It too just re-exports from `highlight.js`. So there has never been a correct `@types/highlightjs`, which means we can‘t just deprecate and move the `latest` dist tag. Ideally, we need to add the typings for highlightjs v9 (if they ever existed?), publish them as v9.x.x, set that to `latest`, and deprecated both of the currently published versions. What a pain.

**Comment by joshgoebel** [comment]
> So there has never been a correct @types/highlightjs

**There definitely was**, though I can't say it was correct - it was before my time - it was **correct-ish** at the very least.  But there definitely existed at one point a file with a FULL list of types (not just a re-export of us) - because I looked at it before for comparison long long ago.  Not sure why you can't seem to find it.

Although perhaps I'm thinking of `highlight[DOT]js` but no matter that would be what you wanted either way I think.  Here it is on unpkg for version 9.12.

https://unpkg.com/browse/@types/highlight.js@9.12.4/index.d.ts

**Comment by andrewbranch** [comment]
@types/highlightjs@9.12.1 has been published; it’s now `@latest`, and I manually deprecated 9.12.9 and 10.1.0 with the message

> This version was published in error as a shim for highlight.js. Use @types/highlightjs@~9.12.1 with highlightjs (deprecated), or use highlight.js instead, which ships its own types.

I think we’re all set. In the near future we can safely delete the `highlightjs` directory from DT.

**Comment by joshgoebel** [comment]
Sounds good.  Thanks for all the effort on this!

**Comment by ffflorian** [comment]
Wow, thanks @joshgoebel @andrewbranch!

**Pull request merged**
