### PR TITLE
[babel-traverse] [babel-types] Made most isXXX methods in babel-traverse be type guards.

### PR DESCRIPTION
**Pull request by cameron-martin**
Most of them are just a 1:1 mapping between isXXX and NodePath<t.XXX>, but for the ones that are not (which are all near the bottom of the list of methods) I looked at https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/lib/virtual-types.js and https://github.com/babel/babel/blob/master/packages/babel-types/src/validators.js to determine what type they are.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Urls listed above.
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by cameron-martin** [comment]
`isReferencedIdentifier` can actually be either an `Identifier` or a `JSXIdentifier`. I'll update the PR to reflect this when I am at my pc, I'm just making a note of it so I do not forget.

Also I'm guessing that I should update `babel-types` with these changes too.

**Comment by marvinhagemeister** [comment]
That's awesome! Feel free to ping me when you feel like the PR is ready to be merged :)

**Comment by cameron-martin** [comment]
@marvinhagemeister I've made those changes, I think this is ready to be merged :)

**Review by marvinhagemeister — APPROVED** [review]
LGTM, that's amazing, thanks for your work 👍

**Pull request merged**
