### PR TITLE
fix material-ui definition for Tooltip component

### PR DESCRIPTION
**Pull request by gordienkotolik**
Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/callemall/material-ui/blob/master/src/internal/Tooltip.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mhegazy** [comment]
> material-ui-tests.tsx(3071,39): error TS2365: Operator '===' cannot be applied to types 'horizontal' and '"middle"'.
material-ui-tests.tsx(3104,39): error TS2365: Operator '===' cannot be applied to types 'horizontal' and '"middle"'.

Looks like you need to update the tests as well.

**Comment by mhegazy** [comment]
@cauld @xaviergonz @ligaz @prashaantt  @gordienkotolik @chazclark @Li0liQ @karak @jshmrsn @ewgenius @ericanderson @CarsonF @DenisCarriere  any comments?

**Comment by DenisCarriere** [comment]
+1 for the PR once the tests pass.

**Comment by Li0liQ** [comment]
I do not think this is a correct place for a fix. According to my short investigation, material-ui is a bit inconsistent when it comes to positioning. The change proposed corresponds to https://github.com/callemall/material-ui/blob/master/src/utils/propTypes.js#L3 .
It is later used in https://github.com/callemall/material-ui/blob/master/src/Popover/Popover.js#L345 .
The correct fix in my opinion will update https://github.com/gordienkotolik/DefinitelyTyped/blob/b28a50ea0f02cc2a2b9b31a1a3d679a8f165e988/material-ui/index.d.ts#L8692 to refer to a new type instead of `__MaterialUI.propTypes.horizontal` (same is true for `verticalPosition`).

Reason is `Tooltip` does not use utils/propTypes but its own inline propType definition: https://github.com/callemall/material-ui/blob/master/src/internal/Tooltip.js#L88 .

**Comment by gordienkotolik** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15118

**Comment by paulvanbrenk** [comment]
Closing this PR, as it looks like #15118 is more current and correct. Let me know if i'm mistaken.

**Pull request closed without merging**
