### PR TITLE
remove(): `@types/fabric`

### PR DESCRIPTION
**Pull request by ShaMan123**
Since v6 types are part of the repo, the version will be released in the near future.
https://github.com/fabricjs/fabric.js/issues/7596

**Typing efforts are most welcome in the [repo](https://github.com/fabricjs/fabric.js)!**

---

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by ShaMan123** [comment]
Should I remove the types or just add the indication to [notNeededPackages.json](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62668/files/b7de936b7cb3efd803b15dab957ec501aeea9e79#diff-a275c2eae7b8f788a52327e76809026ee1bc5ea614393806c8f3cbab07202621)?

**Review by peterblazejewicz — CHANGES_REQUESTED** [review]
> the version will be released in the near future.

but it isn't yet I think. Removing here will publish plaholder version to NPM from DT, showing incorrect information for end users ('hey, this is placholder version ...' etc)

**Comment by ShaMan123** [comment]
> > the version will be released in the near future.
> 
> but it isn't yet I think. Removing here will publish plaholder version to NPM from DT, showing incorrect information for end users ('hey, this is placholder version ...' etc)

Can we make it publish a place holder for v6 as part of this PR?

**Comment by ShaMan123** [comment]
bot open this PR

**Comment by ShaMan123** [comment]
[v6 is in beta](https://github.com/fabricjs/fabric.js/issues/7596#issuecomment-1430393309) and contains types
please remove this stale package

**Pull request closed without merging**
