### PR TITLE
add types for react-native-swiper, fix types for react-navigation

### PR DESCRIPTION
**Pull request by mhcgrq**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

- react-native-swiper: https://github.com/leecade/react-native-swiper
- react-navigation: https://reactnavigation.org/docs/navigators/#Calling-Navigate-on-Top-Level-Component

### CODE REVIEW

**Comment by aozgaa** [comment]
👍 or 👎, @CaiHuan, @huhuanming, @mhcgrq ?

**Comment by huhuanming** [comment]
Cool!
And cloud you add some test for it? @mhcgrq

**Comment by mhcgrq** [comment]
add test for react-native-swiper, check it out please. @huhuanming

**Comment by huhuanming** [comment]
👍

**Review by huhuanming — APPROVED** [review]
LGTM

**Comment by huhuanming** [comment]
Thanks for your hard work

**Comment by mhcgrq** [comment]
@aozgaa could you help me merge it?

**Pull request merged**
