### PR TITLE
Update react-router type definition 

### PR DESCRIPTION
**Pull request by walkerburgin**
- Update the react-router definition to support actually instantiating a StaticLocation 
- Also add a function definition for running the router with a string location (which react-router interprets as a StaticLocation)

### CODE REVIEW

**Comment by walkerburgin** [comment]
+ Also relax the RouteProp definition to allow passing arbitrary properties to route handlers: 

    ~~~typescript 
    // Run the router
    Router.run(routes, Router.HistoryLocation, (MatchedRoute, state) => {
        React.render(<MatchedRoute flux={flux} />, document.getElementById("app"));
    });
~~~

**Comment by vvakame** [comment]
@walkerburgin thank you for your contributions.
please resolve conflict.

**Comment by walkerburgin** [comment]
Updated (sorry for the slow turnaround).

**Comment by vvakame** [comment]
*react-router/react-router.d.ts*

to authors(@mrk21 @vasek17). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Pull request merged**
