### PR TITLE
[swell-js] Updated wrong names and added definitions

### PR DESCRIPTION
**Pull request by gusfune**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by gusfune** [comment]
Fixing the Pull Request, the last one by accident updated the naming schemes according to GraphQL API, which isn't the actual name of the models according to the REST API

This is now amended and fixed, alongside more detailed definition for Products.

**Review by markus-gx — APPROVED** [review]
Nice one! Why did you change some interfaces and added a prefix "Swell"?

**Comment by gusfune** [comment]
> Nice one! Why did you change some interfaces and added a prefix "Swell"?

I was making some tests to match the type names from Swell GraphQL API, but that was never intended to be committed. Did by mistake, as it didn't match the names. Hopefully rolling back now this will not be an issue.

I have now reverted all `Swell` prefix to the way it was before, that actually matches the API model.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## swell-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/swell-js@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'swell-js'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0351f8ad8ac5af10883d33335a0403cd1e208173
</p>

**Pull request merged**
