### PR TITLE
Add Electron specific versions to process.versions

### PR DESCRIPTION
**Pull request by miniak**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

https://github.com/electron/electron/blob/master/docs/api/process.md#processversionselectron
https://github.com/electron/electron/blob/master/docs/api/process.md#processversionschrome

### CODE REVIEW

**Comment by miniak** [comment]
@rhysd Can you review this, please? Thanks

**Comment by rhysd** [comment]
@miniak :+1:

**Comment by rhysd** [comment]
I think this PR needs extra reviewer because it changes node.d.ts.

**Comment by miniak** [comment]
@rhysd I've checked several recent PRs for node.d.ts, but I couldn't figure out who to ask for review.

@mhegazy can you help us? thanks

**Pull request merged**
