### PR TITLE
update(copy-webpack-plugin): v8 updates

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- drop v5
- create v6 as latest maintained on DT
- updates from v7 and v8
- change `CopyPlugin` to be proper class, not interface, as in Webpack`s `types.d.ts`
- webpack 5.0 only support via package.json (as v8 is v5 specific)
- tests amended

Please review carefuly, the change is breaking mostly because of removal of options.

https://github.com/webpack-contrib/copy-webpack-plugin/compare/v6.4.1...v8.0.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by flo-sch** [comment]
(Not a reviewer, but I landed it while looking at it myself)

Any chance we could export those typings?
I am after forwarding options from a centralized webpack config to some plugins, and it would make things so much easier if I could use `import { ObjectPattern } from 'copy-webpack-plugin';` for instance

I was thinking about submitting a PR then I saw that one, just wondering if it is worth combining it here?

**Comment by peterblazejewicz** [comment]
@flo-sch here you're, comes with update. That feature is backward compatible (exports don't hurt).
up to maintainer, thx!

**Comment by flying-sheep** [comment]
Sorry, not using this anymore, I have no idea. I could rubber stamp it :shrug:

**Review by orta — APPROVED** [review]
Looks reasonable to me overall

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
