### PR TITLE
Added json option support to @types/got

### PR DESCRIPTION
**Pull request by keyten**
https://github.com/sindresorhus/got#json

### CODE REVIEW

**Comment by LinusU** [comment]
If you look at the interfaces defined above that type, you'll see that the `json` property gets added later. This is to support varying the return type based on the value of `json`.

Is there something that is not working currently?

**Comment by armanio123** [comment]
Hi @keyten could you address @LinusU questions?

**Comment by keyten** [comment]
I don't understand you well, sorry.

> Is there something that is not working currently?
Do you mean something in my code or in types?
I tried to use json option, ts compiler didn't accept it so i edited the types, put them into types/got in my project and it worked. So I did a pull request with it.

**Comment by LinusU** [comment]
> I don't understand you well, sorry.

No problem, I'll try and clarify.

The code should be able to work without your change since the `json` option is included a few lines above your addition.

Could you share the error that you get when you aren't using this patch?

**Comment by keyten** [comment]
Ah. Ok, I got it.
That's strange, I tried to remove my addition and compile the project now and it compiled without any errors. You're right. Don't know what that was.

**Pull request closed without merging**
