### PR TITLE
[sinon] allow SinonSpyCall for some asserts

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sinonjs/sinon/issues/1471
http://sinonjs.org/releases/v4.4.1/assertions/
https://github.com/sinonjs/sinon/pull/1688
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Flarna** [comment]
@RyanCavanaugh seems typescript-bot is sleeping...

**Review by rationull — APPROVED** [review]
Nice improvement.

**Comment by 43081j** [comment]
While it does work, it doesn't really seem to exist in sinon's own documentation and the maintainer never responded in your issue.

It would be better if it was official rather than "this happens to work, so we should support it".

**Comment by Flarna** [comment]
@43081j Agree, that would be nice. I use this since >1 year  via a local extension of the typings and thought it's time to share this. Don't know why the sinon maintainers have not responded in my issue there.
Do you suggest to not merge this PR?

**Comment by 43081j** [comment]
I think the PR is fine but we should really find confirmation from one of sinon's maintainers first that this is expected usage.

This will help us avoid adding type info for something which may break without notice.

**Comment by DanielRosenwasser** [comment]
I'll wait on further confirmation before merging this in. In the meantime, thanks for the PR!

**Comment by Flarna** [comment]
I created a PR for sinon docs: https://github.com/sinonjs/sinon/pull/1688
Lets see if it get's accepted or rejected.

**Comment by Flarna** [comment]
@DanielRosenwasser PR in sinon has been merged therefore I think this PR can be merged also.

**Comment by 43081j** [comment]
yup looks good to me.

thanks for the extra effort. its better that we make sure we're not relying on some unofficial behaviour that can change/break in future.

**Review by 43081j — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Thanks for the effort everyone!

**Pull request merged**
