### PR TITLE
Added restArguments, isMap, isWeakMap, isSet, isWeakSet, toPath inter…

### PR DESCRIPTION
**Pull request by xiaoxizi2303**
Added restArguments, isMap, isWeakMap, isSet, isWeakSet, toPath interface definitions to types/underscore

### CODE REVIEW

**Comment by hkleungai** [comment]
These methods had been added by me in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70844, which is merged already. Are you sure the change in this PR is still needed? 😅

**Comment by jgonggrijp** [comment]
I propose to close this PR for the following reasons:

- It is no longer needed because of #70844.
- It lacks new tests.
- It breaks existing tests.
- It is a duplicate of #69550, which had the above two problems, too.

CC @gabritto

**Comment by xiaoxizi2303** [comment]
> These methods had been added by me in #70844, which is merged already. Are you sure the change in this PR is still needed? 😅

I noticed, but the declaration file of the underscore library above the DefinitelyTyped repository is still missing the type definition of the restArguments method, can you help add it?

**Comment by xiaoxizi2303** [comment]
> I propose to close this PR for the following reasons:
> 
> * It is no longer needed because of [feat(underscore): Add is(Weak)Set & is(Weak)Map & toPath, add tests #70844](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70844).
> * It lacks new tests.
> * It breaks existing tests.
> * It is a duplicate of [@Added restArguments, isMap, isWeakMap, isSet, isWeakSet, toPath interface definitions to types/underscore #69550](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69550), which had the above two problems, too.
> 
> CC @gabritto

I noticed, but the declaration file of the underscore library above the DefinitelyTyped repository is still missing the type definition of the restArguments method, can you help add it?

**Comment by jgonggrijp** [comment]
If you remove the other declarations and add tests for `restArguments`, we can have a review. For the tests, I suggest taking example from the test for `get`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9256ab91a0db77303d55d751a5098b19bbbb6909/types/underscore/underscore-tests.ts#L522-L607

**Comment by xiaoxizi2303** [comment]
> Contributor

Can you help add the restArguments method?,It may take a long time for me to adapt here.

**Comment by xiaoxizi2303** [comment]
> If you remove the other declarations and add tests for `restArguments`, we can have a review. For the tests, I suggest taking example from the test for `get`:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9256ab91a0db77303d55d751a5098b19bbbb6909/types/underscore/underscore-tests.ts#L522-L607
Can you help add the restArguments method?,It may take a long time for me to adapt here.

**Comment by jgonggrijp** [comment]
I would be happy to help but I currently have too many other things going on. I hope someone else can help you. [This link](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) might also help.

**Comment by xiaoxizi2303** [comment]
> 我很乐意提供帮助，但我目前有太多其他事情要做。我希望其他人可以帮助你。[此链接](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package)也可能有所帮助。

Okay, thanks.

**Comment by xiaoxizi2303** [comment]
> I would be happy to help but I currently have too many other things going on. I hope someone else can help you. [This link](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) might also help.

Okay, thanks.

**Pull request closed without merging**
