### PR TITLE
Added Primitive JavaScript Types for Attributes properties for xast

### PR DESCRIPTION
**Pull request by malav2110**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/syntax-tree/xast#attributevalue
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@wooorm https://github.com/syntax-tree/xast#attributevalue implies that these will always be string, however at  https://github.com/syntax-tree/xastscript which is the build for this `number` and other types with `toString` are supported.
I think it may be accurate to update this, but want to double check.
This could also be done specifically at the xastscript level if it is specific to that library.

**Comment by wooorm** [comment]
We've discussed some of this here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48265#discussion_r495987460.

I think it should be in xastscript, because that project chooses to accept more things. It does output xast. I don't think other xast utilities should be required to handle numbers for example.

**Review by ChristianMurphy — CHANGES_REQUESTED** [review]
Apologies @malav2110, it looks like this would be a better fit for xastscript.
It would probably work to move the `Primitive` type there, and extend `Attributes`
Something like
```typescript
interface Attributes extends xast.Attributes {
  [name: string]: Primitive
}
```
in xastscript

**Comment by ChristianMurphy** [comment]
new PR opened as https://github.com/syntax-tree/xastscript/pull/5#pullrequestreview-521810632

**Comment by wooorm** [comment]
I guess this can be closed then?

**Comment by malav2110** [comment]
Closing as Xastscript types has been updated in v2.1.0 - https://github.com/syntax-tree/xastscript/releases/tag/2.1.0

**Pull request closed without merging**
