### PR TITLE
[anymatch] Remove, bundles its own types

### PR DESCRIPTION
**Pull request by BendingBender**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by bondz — APPROVED** [review]
Path to new typings

https://github.com/micromatch/anymatch/blob/master/index.d.ts

**Comment by andrevmatos** [comment]
It seems `@types/webpack` still uses `anymatch@2`, which doesn't come with types, and after our auto-deps-update bot got this updated, we started seeing errors about `anymatch` types being inferred as `any`, which prevented our project to compile. We had to pin `@types/anymatch@^1.3` in order to get it to compile again.

**Comment by peterblazejewicz** [comment]
Yes, @andrevmatos , just noticed same. It impacts DT itself on CI runs, TBU

**Comment by BendingBender** [comment]
Would it help to pin `@types/webpack@4` to `@types/anymatch@1.3`? Is it at all possible?

**Comment by peterblazejewicz** [comment]
https://github.com/microsoft/DefinitelyTyped-tools/pull/259
I've checked the webpack 4 resolution, it should be at least version 2 of anymatch, not v1.
For now let's try with `anymatch` v3:
https://github.com/microsoft/DefinitelyTyped-tools/pull/259
but I'll amend PR to add @types/anymatch, so we have a choice

**Pull request merged**
