### PR TITLE
[@types/reach__router] Remove history dependency

### LINKED ISSUE #46972: [@types/reach__router] typings shouldn't depend on 'history' typings
`@reach/router` typings depend on `history` typings although the packages themselves don't have this dependency. This leads to problems when used in a codebase that actually uses the `history` package.

As an example in our particular case our app uses `react-router@6` which depends on `history@5` which includes it's own typings. We also use storybook which depends on `@reach/router` which uses `@types/reach__router` typings which depend on `@types/history@4` typings. Now, since actual library has typings built-in typescript uses those instead of `@types/reach__router` typings and that makes them incompatible, e.g. `LocationState` is not present in v5 history. Note that there is no conflict in the source code packages versions, as `@reach/router` has no dependency on `history`

Currently the `@reach/router` typings depend on `history` typings for `Location` and `LocationState` types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0dc5a70adda8cf722f10d088f98f85cb9cf38951/types/reach__router/index.d.ts#L13-L14

Which in turn are fairly straightforward types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0dc5a70adda8cf722f10d088f98f85cb9cf38951/types/history/index.d.ts#L27-L33

with all the properties being strings, or in the case of `LocationState` a union of an object and undefined.

Given that this is not a true dependency I think that it would make sense to pull in these type definitions directly in `@types/reach__router`. I might not be aware of all the complications of such a change, so please advise if you see any.

Authors: @kingdaro @xMokAx @awwit @wroughtec @chilledoj @Eyas

### PR DESCRIPTION
**Pull request by Fredx87**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.

This PR removes the dependency on the history package and redefines the types internally. It fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46972

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## reach__router ([<kbd>unpkg</kbd>](https://unpkg.com/browse/reach__router@latest/))
was missing the following properties:
1. matchPath
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c6ae26d5d94d1a1ab6430f28dc2287d408c4363
</p>

**Comment by Eyas** [comment]
Hi @Fredx87 -- I agree with the spirit of the change, since reach router itself doesn't actually depend on history.

That said, could you add a couple of tests to this PR first?

**Comment by Fredx87** [comment]
Hi @Eyas, I'm not actually using `@reach/router`, so I don't know what is the desired behavior of these types and what tests should be added. I made it to fix the linked bug and bug that I am having with storybook (https://github.com/storybookjs/storybook/issues/11928).

My PR is not changing anything about types, just replacing the ones imported from `history` with new types defined directly in the file. For this reason, I don't think that is necessary to add new tests, but if you think that it is needed, one of the maintainers can take care of it or point me in the right direction.

**Comment by Eyas** [comment]
The issue is that the history property used to be covered by tests in the history package, but now we have new definitions that have no corresponding tests.

I know how it goes with OSS where you're trying to fix one issue and it ends up expanding, but I also want to make sure they existing usage doesn't regress, so I hope you bear with me here:

Adding tests shouldn't be too bad; take a look at existing tests-- You basically write code that uses these properties and the test suite ensured tsc can compile it and type check it properly.

You can even copy some of the basic tests from the history package and modify them to test the history property here.

**Comment by chilledoj** [comment]
Hi @Fredx87 ,

It should be possible to just expand upon, or copy and amend the tests using [location](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reach__router/reach__router-tests.tsx#L37-L52). Or create a new view which does something similar to the reach router [docs for useLocation](https://reach.tech/router/api/useLocation) hook. An example of testing a hook is [setup here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reach__router/reach__router-tests.tsx#L16-L19) and [implemented here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reach__router/reach__router-tests.tsx#L31).

**Comment by Fredx87** [comment]
I have added a test that uses the `useLocation` hook.

**Review by chilledoj — COMMENTED** [review]
Looks good to me.

**Review by Eyas — APPROVED** [review]

**Pull request merged**
