### PR TITLE
[Framework7] new definitions, v1.0

### PR DESCRIPTION
**Pull request by larrybahr**
Definitions for Framework7

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by zhengbli** [comment]
Do you own the package? If so please bundle the typing files directly with the product package, which is the preferred way as it guarantees version matching. Thanks

**Comment by larrybahr** [comment]
I do not own the package. I do use framework7 in my TypeScript projects and thought it would be nice to get the definition from Definitely Typed instead of copying this folder over manually.

**Comment by zhengbli** [comment]
@larrybahr why did you close this PR? It is ok that you do not own the package.

**Comment by larrybahr** [comment]
My mistake. I have already deleted my repository. I will have to create a new pull request from my new fork.

**Pull request closed without merging**
