### PR TITLE
fix(semver): add `toString` override to make eslint happy

### PR DESCRIPTION
**Pull request by viceice**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://typescript-eslint.io/rules/no-base-to-string/>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by viceice** [comment]
Just adding the `toString` method to make eslint rules happy

- https://typescript-eslint.io/rules/no-base-to-string/

**Review by G-Rath — APPROVED** [review]
Looks good to me - `semver` does indeed have it's own `#toString`:

https://github.com/npm/node-semver/blob/ac9b35769ab0ddfefd5a3af4a3ecaf3da2012352/classes/semver.js#L87-L89

**Review by peterblazejewicz — APPROVED** [review]
@viceice thanks!

**Comment by viceice** [comment]
Ready to merge

**Pull request merged**
