### PR TITLE
seamlessImmutable: Return the proper combined type for the .merge method

### LINKED ISSUE #20591: SeamlessImmutable merge definition does not return combined types
The @types/seamless-immutable package does not return the proper combined type for the .merge method.  It instead, just returns an Immutable<T>, ignoring the type of the passed in object.  The definition instead should return the compound type as follows:
`merge<U>(part: DeepPartial<U>, config?: MergeConfig): ImmutableObject<T> & U;`

### PR DESCRIPTION
**Pull request by garyyeap**
This PR should be merged along with authorization from @dustinhorne as the idea was came from #20591 

Fix #20591 

- [v ] Use a meaningful title for the pull request. Include the name of the package modified.
- [v] Test the change in your own code. (Compile and run.)
- [v ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ v] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [v ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [v] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20591
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by xsburg** [comment]
Hi @garyyeap,
Thanks for the PR!
When creating the typings I intentionally restricted the `part` argument of `merge()` to be a `DeepPartial<>` of the original type.
The assumption is that we normally use `merge` to alter several properties of a type (rather than extend the type with new properties). As a result, we have typechecking that will tell us if the property is missing in the original object. It is similar to what React typings do for the `setState()` method.
One common use case when such restriction is very useful is when writing Redux reducers. For example, when refactoring a state `{ a: string, b: string }` into `{ a: string, c: string }`, we will get extra errors that indicate that `merge` usages must be updates as well.
Please let me know what you think and what your use case is.

**Comment by geirsagberg** [comment]
IMO, type definitions should reflect the actual semantics of the functions, not how they are mostly used. Even though one of the most used cases is to merge objects of the same type, it is perfectly legal to merge objects of different types, and I believe the typings should reflect this.

On another note, shouldn't the signature be: 

    merge<U>(part: DeepPartial<U>, config?: MergeConfig): ImmutableObject<T & U>;

rather than:

    merge<U>(part: DeepPartial<U>, config?: MergeConfig): ImmutableObject<T> & U;

Seeing as the result of the merge is an immutable object, even if `part` is not? Or have I misunderstood how `merge` works?

**Comment by xsburg** [comment]
Speaking of the change, I think we should also omit `DeepPartial` in the arguments, we don't need it if the type is different:
```
merge<U>(part: U, config?: MergeConfig): ImmutableObject<T & U>;
```
Still, even though I totally agree with the reasoning, I believe that the expediency of extra type checking outweighs the restrictions in this case. Worst case scenario, you can always skip it with `any`.

**Review by weswigham — CHANGES_REQUESTED** [review]
Seems like @xsburg and @geirsagberg have some reservations about this as is. I'm going to wait until they give this the sign off.

**Comment by andy-ms** [comment]
@garyyeap What do you think about using `merge<U>(part: U, config?: MergeConfig): ImmutableObject<T & U>`?

**Comment by mhegazy** [comment]
@weswigham is this good to go now?

**Comment by weswigham** [comment]
@mhegazy there haven't been any changes to this PR since my comment?

**Comment by mhegazy** [comment]
sorry, i should have been clearer. should this PR be merged?

**Comment by weswigham** [comment]
@mhegazy I don't think so, the package reviewers had changes they wanted to see which haven't been made.

**Pull request closed without merging**
