### PR TITLE
feat(stripe): add errors

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/stripe/stripe-node/pull/530
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Also applied most linting rules without introducing any breaking changes.

Feel free to add suggestions for additional doc tags for the errors.

### CODE REVIEW

**Comment by galtalmor** [comment]
The addition of errors is good, but I do not understand why you've made all the other changes, including removing all of the tslint flags.
In my opinion all the changes should be reverted and the new changes should follow all the restrictions of the previous tslint configurations.

**Comment by LinusU** [comment]
> [...] and the new changes should follow all the restrictions of the previous tslint configurations.

I believe that all of the flags were _exceptions_ that were added since the code existed before we introduced linting at all, I might be wrong though...

Still would have been nice to have the style cleanup as a separate commit maybe, but I would not be opposed to just merging as is 👍

**Comment by LinusU** [comment]
Whoopsie, didn't mean to approve that without settling the discussion first 😅 

Please hold on merging until @galtalmor have had time to reply

**Comment by SimonSchick** [comment]
@galtalmor exactly what @LinusU said, I noticed a bunch of inconsistencies when adding the errors so did what the DT suggests enabled most rules and ran the auto fixer.

**Comment by galtalmor** [comment]
@LinusU Actually you are right. My bad. Didn't notice all the flags were set to false before.
I wasn't sure about removing all the namespaces and changing all the `Array<T>` to `T[]`.
But I guess it is actually alright.
Cheers.

**Pull request merged**
