### PR TITLE
[sockjs-client] export module-internal namespace globally

### LINKED ISSUE #11042: Refactor sockjs-client to reflect natural behaviour
- [ x ] I tried using the latest [socktjs-client/sockjs-client.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sockjs-client/sockjs-client.d.ts) file in this repo and had problems.
  - The authors of that type definition are:
    @arusakov 
    @mhegazy 

The current implementation is not straight forward.

I'm expecting the definition to reflect a use pattern similar to the one created by TS module.

For example:

```
npm install @types/sockjs-client
```

and 

``` ts
import * as SockJS from 'sockjs-client';

export class MySock {
  url: string;
  sock: SockJS;

  open(): void {
    this.sock = new SockJS(this.url);
  }
}
```

It will error:

```
ERROR in [default] /Users/shlomiassaf/Desktop/Cisco/angular-cli-gui/client/src/app/shared/cli-comm.service.ts:5:8 
Cannot find name 'SockJS'.
```

To fix that I need to use some non usual imports and un natrual behaviour / code.

``` ts
import SockJSClass = __SockJSClient.SockJSClass;
let sockJs: SockJSClass;
```

This is not how a TS build module behave.

> Truth be told could'nt even get it to work with **__SockJSClient** in my angular-cli@webpack project using `@types` but it works in the tests I guess so I won't argue.

If we change the definition files to this:

``` ts
declare module "sockjs-client" {
  export = SockJS;
}

declare class SockJS extends EventTarget {
  constructor(url: string, _reserved?: any, options?: SockJS.Options);

  readyState: SockJS.State;
  protocol: string;
  url: string;
  onopen: (e: SockJS.OpenEvent) => any;
  onclose: (e: SockJS.CloseEvent) => any;
  onmessage: (e: MessageEvent) => any;
  send(data: any): void;
  close(code?: number, reason?: string): void;

  static CONNECTING: SockJS.State;
  static OPEN: SockJS.State;
  static CLOSING: SockJS.State;
  static CLOSED: SockJS.State;
}

declare namespace SockJS {
  interface BaseEvent extends Event {
    type: string;
  }

  interface OpenEvent extends BaseEvent {}

  interface CloseEvent extends BaseEvent {
    code: number;
    reason: string;
    wasClean: boolean;
  }

  interface MessageEvent extends BaseEvent {
    data: string;
  }

  interface SessionGenerator {
    (): string;
  }

  interface Options {
    server?: string;
    sessionId?: number | SessionGenerator;
    transports?: string | string[]
  }

  enum State {
    CONNECTING = 0, OPEN, CLOSING, CLOSED
  }

}
```

No errors and almost natural behaviour.
No more `__SockJSClient.SockJSClass`, `__SockJSClient.OpenEvent` and others...

### PR DESCRIPTION
**Pull request by BendingBender**
to be able to reference all types defined by the module; found no other
way without breaking all dependants

fixes #11042 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by BendingBender** [comment]
@weswigham Do you have any advice on how to export the internal namespace from this module without making it global? Or whom can I ask for advice?

**Comment by weswigham** [comment]
@BendingBender If you're okay with losing the call signature ([which is just provided as a shortcut](https://github.com/sockjs/sockjs-client/blob/master/lib/main.js#L33)), a class and namespace merged would work excellently. Unfortunately, I can't think of an easy way to preserve both the call signature and the (named) nested type hierarchy.

Conventionally we'd suggest placing the instance and static halves of the class into separate interfaces; however you can't nest an interface inside another to expose all the associated typed we'd want here.

**Comment by BendingBender** [comment]
@weswigham Personally, I wouldn't mind. The question is: what happens to the users of these typings? The change will break some of the setups. If it's OK to do this without releasing a new major version (which isn't possible because the version of the typings align with the package version) then I'll do this.
Of course, if it's OK to have the interfaces in the global namespace then I'd prefer to solve the problem this way, the less disturbance to users the better.

**Comment by weswigham** [comment]
@BendingBender globals have issues, too. If you include two different versions of the types (from dependencies, for example), you'll get duplicate identifier conflicts on all the globals. (Which is why its avoided where its not how the JS works)

You could just use structural compatibility for everything and not actually export named types? You lose a lot of discoverability with that, though.

**Comment by andy-ms** [comment]
The problem here is that `const enum State` causes an error when trying to merge a namespace with a value. Issue: Microsoft/TypeScript#17372

**Comment by BendingBender** [comment]
@weswigham Structural compatibility is not an option here. This is what I had to write in my code to get the type of a socket to use it on an instance field of a class:
```
type SockJsCtor = typeof SockJs;
const sockJsSocketBinding = (<true>false) && new SockJs(''); // determine the type of a SockJs socket without actually creating one
type SockJSSocket = typeof sockJsSocketBinding;
```

**Comment by weswigham** [comment]
Ick.

**Comment by weswigham** [comment]
@BendingBender Does this get you what you want?:
```ts
// Type definitions for sockjs-client 1.0
// Project: https://github.com/sockjs/sockjs-client
// Definitions by: Emil Ivanov <https://github.com/vladev>
//                 Alexander Rusakov <https://github.com/arusakov/>
//                 BendingBender <https://github.com/BendingBender>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export = SockJS;
export as namespace SockJS;

declare const SockJS: {
    new (url: string, _reserved?: any, options?: SockJS.Options): SockJS.Socket;
    (url: string, _reserved?: any, options?: SockJS.Options): SockJS.Socket;
    prototype: SockJS.Socket;
    CONNECTING: SockJS.CONNECTING;
    OPEN: SockJS.OPEN;
    CLOSING: SockJS.CLOSING;
    CLOSED: SockJS.CLOSED;
};

declare namespace SockJS {
    type CONNECTING = 0;
    type OPEN = 1;
    type CLOSING = 2;
    type CLOSED = 3;
    type State = CONNECTING | OPEN | CLOSING | CLOSED;

    interface BaseEvent extends Event {
        type: string;
    }

    type OpenEvent = BaseEvent;

    interface CloseEvent extends BaseEvent {
        code: number;
        reason: string;
        wasClean: boolean;
    }

    interface MessageEvent extends BaseEvent {
        data: string;
    }

    type SessionGenerator = () => string;

    interface Options {
        server?: string;
        sessionId?: number | SessionGenerator;
        transports?: string | string[];
    }

    interface Socket extends EventTarget {
        readyState: State;
        protocol: string;
        url: string;
        onopen(e: OpenEvent): any;
        onclose(e: CloseEvent): any;
        onmessage(e: MessageEvent): any;
        send(data: any): void;
        close(code?: number, reason?: string): void;
    }
}
```

**Comment by BendingBender** [comment]
@weswigham This worked out nicely, thank you!
@andy-ms How did you find out that the root cause for the merging problem was the enum?

**Comment by andy-ms** [comment]
I deleted stuff until it worked, then hit undo until it broke again.
Thanks!

**Pull request merged**
