### PR TITLE
[gapi.client.discovery] automatic update

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
  - [x] Test the change in your own code. (Compile and run.)
  - [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  - [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
  - [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
  - [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

  Select one of these and delete the others:

  If changing an existing definition:
  - [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Maxim-Mazurok/google-api-typings-generator#google-api-typings-generator
  - [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
  - [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
  - [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

  ----

  🤖 This pull request was automatically created by [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) which generates types from [Google API Discovery Service](https://developers.google.com/discovery). Types were linted and tested before submission.

  If there is an issue with this pull request, consider [submitting a new issue](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new).

  Note you can also [use these types](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279) from our [`types` branch](https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/types) which is updated hourly.

### CODE REVIEW

**Review by declanvong — APPROVED** [review]

**Comment by Maxim-Mazurok** [comment]
Ready to merge

**Comment by Maxim-Mazurok** [comment]
I don't understand how this PR is possible, the same exact commit was already merged to master previously: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46787
@orta does it look like a Git/GitHub bug to you?...

**Comment by declanvong** [comment]
As long as they branch off the same parent commit, there isn't any issue (from a Git / GH perspective). So seems like it might be an issue with the generator accidentally triggering a second PR from the same base commit.

**Comment by Maxim-Mazurok** [comment]
Actually, the first PR #46787 was merged at `27 Aug 2020, 02:17 GMT+10`.
And this one was opened at `27 Aug 2020, 02:26 GMT+10`, which is 9 minutes after the first one was merged.
And when I [tried](https://github.com/Maxim-Mazurok/google-api-typings-generator/compare/master...skip-revision-only-updates) to open PR to our repo from `skip-revision-only-updates` branch which was merged earlier, I'm getting "No commits between master and skip-revision-only-updates" error from the API.
So, it looks like GH issue to me after all...

**Comment by Maxim-Mazurok** [comment]
I'm still not 100% sure why GH let me open this PR, but now I understand why it happened from the bot side:
1. Bot action starts at XX:10, clones fork and resets it to upstream, then gets type definitions and starts running tests
1. While tests were running, at XX:17 the previous PR got merged
1. Since we synced with upstream before PR got merged, we still think that this change is not in DT. And when we checked for open PR - there's none, because it is already merged!
1. So, the bot created new PR

This issue will be fixed when we'll be approving and merging PRs instantly: https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/245

**Pull request merged**
