### PR TITLE
support es module import style for memory-fs

### PR DESCRIPTION
**Pull request by JounQin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by JounQin** [comment]
@andy-ms It works with `esModuleInterop`, but I believe it should also wrok without `esModuleInterop`.

**Comment by andy-ms** [comment]
I don't think we're supporting adding the `namespace {}` hack any more -- @DanielRosenwasser We should add this to the README, and possibly highlight it more in the handbook.

**Comment by JounQin** [comment]
@andy-ms Would you like to show that how to support es module import style for commonjs module without `namespace {}` and `--esModuleInterop`?

**Comment by andy-ms** [comment]
@JounQin You can't use an es6 import of a commonjs `export =` module unless `--esModuleInterop` or `--allowSyntheticDefaultImports`. Instead, use `import x = require("x");`.

**Comment by rbuckton** [comment]
@JounQin, documentation regarding this can be found at https://github.com/DefinitelyTyped/DefinitelyTyped#should-i-add-an-empty-namespace-to-a-package-that-doesnt-export-a-module-to-use-es6-style-imports.

In ECMAScript `import * as x from "y";` imports the module `"y"` as a "Module Namespace Object". This object is not callable or constructable. As @andy-ms mentioned, you can use `--esModuleInterop` as of TypeScript 2.7 to use an ES6 import in the style `import x from "y"` in your own code, but the declaration on DefinitelyTyped should remain with the export syntax as written.

**Pull request closed without merging**
