### PR TITLE
add missing PIXI.loaders.shared

### PR DESCRIPTION
**Pull request by k8w**
add missing PIXI.loaders.shared

@clark-stevenson @andy-ms @ruslanchek @jakobmulvad @sotnight

### CODE REVIEW

**Comment by clark-stevenson** [comment]
@k8w 

Thanks! 👍 

I can't seem to see a shared loader property here though?

https://github.com/englercj/resource-loader/blob/master/src/Resource.js

**Comment by k8w** [comment]
http://pixijs.download/release/docs/PIXI.loaders.html

There is PIXI.loaders.shared in the documentation.

**Comment by clark-stevenson** [comment]
Man I totally forgot that Pixi extends Loader rather than uses it. 

You are totally right! Thanks @k8w 👍

**Review by clark-stevenson — APPROVED** [review]
Looks good!

**Pull request merged**
