### PR TITLE
[@types/react-native] Add missing 'unknown' and 'extension' values to AppStateStatus

### PR DESCRIPTION
**Pull request by TheAlmightyBob**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/d48f7ba748a905818e8c64fe70fe5b24aa098b05/React/CoreModules/RCTAppState.mm#L30
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by ca057 — APPROVED** [review]
Should we then also add the possible value `extension`, if I read the linked source correctly?
https://github.com/facebook/react-native/blob/d48f7ba748a905818e8c64fe70fe5b24aa098b05/React/CoreModules/RCTAppState.mm#L27

**Comment by TheAlmightyBob** [comment]
> Should we then also add the possible value `extension`, if I read the linked source correctly?
> https://github.com/facebook/react-native/blob/d48f7ba748a905818e8c64fe70fe5b24aa098b05/React/CoreModules/RCTAppState.mm#L27

@ca057 Oh.... yes, probably. I missed that. Any preference between adding that to this PR vs. creating a separate PR?

**Comment by ca057** [comment]
> > Should we then also add the possible value `extension`, if I read the linked source correctly?
> > https://github.com/facebook/react-native/blob/d48f7ba748a905818e8c64fe70fe5b24aa098b05/React/CoreModules/RCTAppState.mm#L27
> 
> @ca057 Oh.... yes, probably. I missed that. Any preference between adding that to this PR vs. creating a separate PR?

I think I would just do it directly here, but I leave it up to you :)

**Comment by TheAlmightyBob** [comment]
@ca057 Thanks, added `extension`

**Pull request merged**
