### PR TITLE
[@types/express-fileupload] Fix: type 'UploadedFile | UploadedFile[], property that doesn't exist

### PR DESCRIPTION
**Pull request by theoludwig**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/richardgirges/express-fileupload](https://github.com/richardgirges/express-fileupload)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

That PR, fix that issue #38334.

### CODE REVIEW

**Comment by Divlo** [comment]
Excuse me, I accidentally closed the pull request.
Looking forward for merging that pull request to master.

**Comment by peterblazejewicz** [comment]
@Divlo Yes, obviously the dual nature of the filed made this harder to grasp.
With your change single value can be lookup, what about nested values:
https://github.com/richardgirges/express-fileupload/blob/d55fa83832351eb3e44e7d2d14c9840ffc5d1b0e/lib/utilities.js#L88-L95

**Comment by Divlo** [comment]
@peterblazejewicz I see but in which case we have an array of UploadedFile ? 
The problem is we can't access mimetype on UploadedFile[] because it's an array, so we have an type error but it isn't (see issue).

**Comment by Divlo** [comment]
Well, I found a workaround solution :
```ts
const image = req.files?.image as UploadedFile;
```
But if I do destructuring, I have a type error :
```ts
const { image } = req.files! as UploadedFile;
```
Conversion of type 'FileArray' to type 'UploadedFile' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

**Comment by Naktibalda** [comment]
Previous attempt to change the type of `files` had some discussions too: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40915

I think that the best way is to use `if (Array.isArray(req.files.foo)) {` to check if it is an an array and act accordingly.

**Review by Naktibalda — CHANGES_REQUESTED** [review]
Please close this PR and associated issue.
The type is correct, it is up to your code to handle possible types correctly.

**Pull request closed without merging**
