### PR TITLE
[@types/react-table] Change SortingRule

### PR DESCRIPTION
**Pull request by thepocp**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by amcasey** [comment]
Does this correspond to a version change in the underlying library?

**Comment by amcasey** [comment]
@thepocp, do you have a link to the corresponding code change?

**Comment by thepocp** [comment]
@amcasey, please see sortColumn method: https://github.com/react-tools/react-table/blob/dd3f30b09906ca4941870de52fe04f05f5d402b0/src/methods.js#L458

**Comment by sandersn** [comment]
Looks like that section of code has been around since 6.0 at least. However, there's references to the old code still in utils.js: https://github.com/react-tools/react-table/blob/dd3f30b09906ca4941870de52fe04f05f5d402b0/src/utils.js#L177

Any idea if that code is still current?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Please address the concerns raised by @amcasey and @sandersn

**Comment by thepocp** [comment]
Changed version to 6.6. In versions less 6.6, asc is in the ServerSide.js

**Review by sheetalkamat — APPROVED** [review]

**Pull request merged**
