### PR TITLE
add engine.ws to SocketIO.Server

### PR DESCRIPTION
**Pull request by hongbo-miao**
case 2. Improvement to existing type definition.

---

Check the demo at https://github.com/uWebSockets/uWebSockets/blob/master/README.md#socketio

``` js
var io = require('socket.io')(80);
io.engine.ws = new (require('uws').Server)({
    noServer: true,
    perMessageDeflate: false
});
```

which is the current way to change socket.io engine.

### CODE REVIEW

**Comment by Hongbo-Miao** [comment]
Wait a little bit. I need change something. Because WebSocketServer is undefined now

**Comment by Hongbo-Miao** [comment]
I cannot make it perfect. So I changed to `any` now.. Because WebSocketServer is undefined.
But I know it is missing.

Please help me correct it. Thanks

**Comment by florentpoujol** [comment]
If I understand correctly (I actually don't use socket.io at all) :

In your examples, `io.engine` is an instance of `EngineIO.Server` which has a public `ws` property set to an instance of any `WebSocket.Server` implementation.

That implementation can be changed either by setting the `ws` property directly or by the `EngineIO.Server`'s constructor's `wsEngine` option.
See code at : https://github.com/socketio/engine.io/blob/master/lib/server.js#L74

I believe `WebSocket.Server` is already defined here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/91df1a377ba69a4f0f7ef85d31c41f6fec6c17c4/ws/ws.d.ts#L108

So the best course of action would be to add definitions for the whole `EngineIO`, so that we can type `SocketIO.Server.engine` correctly.

If no one wants to do that, just adding `engine: { ws: any }` really doesn't add any value to the current definition.
`{ ws: WebSocket.Server }` is slightly better but I don't know what are DefinitelyTyped's rules about dependencies between definitions...

**Comment by zhengbli** [comment]
I agree, the type of `ws` should be `WebSocket.Server` instead of `any`.

**Comment by Hongbo-Miao** [comment]
@zhengbli yeah, I tried that before too.

It will give the error:

> ERROR in /my-project/node_modules/@types/socket.io/index.d.ts
> (50,17): error TS2503: Cannot find namespace 'WebSocket'.

Still need other changes.. I cannot get it work well.

**Comment by zhengbli** [comment]
Actually after trying it is indeed nothing we can do here. This file is written in a fashion that designed to be consumed both a module and a global namespace, and the `WebSocket` file can only be consumed as a module. So we'll take it as is, and may refine it in the 2.0 branch later.

**Pull request merged**
