### PR TITLE
react: Fix wrong type for e.currentTarget

### PR DESCRIPTION
**Pull request by ypresto**
Many component type definitions uses React.Component subclass or `{}` for `T` of `HTMLProps<T>` or `HTMLAttributes<T>`, etc.
But it is used for e.currentTarget passed to event handlers and it (`T`) should be `HTMLElement`.

(This PR contains #14618 because it will conflict on below line:)

```diff
-    interface SVGAttributes<T> extends HTMLAttributes<T> {
+    interface SVGAttributes<T extends SVGElement> extends DOMAttributes<T> {
```

----

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (N/A)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
Looks like we need to update this PR.

**Comment by ypresto** [comment]
Fixed..! (force update is used)

**Comment by vsiao** [comment]
Thanks, @ypresto

**Comment by ericanderson** [comment]
Assuming you fix the build issue, LGTM.

**Comment by paulvanbrenk** [comment]
Closing, can you fix the CI build and the merge conflict.

**Pull request closed without merging**
