### PR TITLE
fix(jsdom): reference `dom` lib in source

### PR DESCRIPTION
**Pull request by SimenB**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

See https://github.com/facebook/jest/issues/12098

Having some DOM types that does not pollute the global namespace would be better, but 🤷

### CODE REVIEW

**Review by orta — COMMENTED** [review]
Yeah, this is implicitly dependent on the DOM types ( for example updating the DOM types meant updating types in here,  e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54052 ) so I think this is a pretty reasonable change

**Review by orta — APPROVED** [review]

**Comment by SimenB** [comment]
(Orta asked med to await more feedback, which is why I haven't landed it)

**Comment by ExE-Boss** [comment]
As I said in <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54052#discussion_r658719780>:
> Alternatively, `@types/jsdom` should depend on the <del>upcoming</del> `@types/dom` types:
> - <https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1023>

**Comment by orta** [comment]
We could be waiting for an unknown amount of time for a separate import of those types without the globals, its a constant debate in the dom-lib-generator chat room in discord

**Comment by SimenB** [comment]
Since these types depend on dom types I think it makes sense for them to reference then directly, rather than declaring it indirectly via a (unshipped) tsconfig.json

**Comment by SimenB** [comment]
Ready to merge

**Pull request merged**
