### PR TITLE
Update to DevExpress ASP.NET/MVC v16.1

### PR DESCRIPTION
**Pull request by romanresh**
This update contains the complete version of the definitions for DevExpress ASP.NET MVC controls. 

The definitions are based on the script references:
https://documentation.devexpress.com/#AspNet/DevExpressWebScripts

The test script is based on this demo: https://demos.devexpress.com/RWA/dxhotelstablet

Controls version: v16.1

### CODE REVIEW

**Comment by mhegazy** [comment]
@INullable any comments

**Comment by romanresh** [comment]
Hello @mhegazy,
 
This update contains the official version of TypeScript definitions for DevExpress ASP.NET/MVC controls. @INullable has made the great work publishing his version of the definitions, we appreciate his efforts and time. We were discussing this with him in our SupportCenter: https://www.devexpress.com/Support/Center/Question/Details/T331931. 
 
Starting with the latest release (v16.1), we've introduced the official support for TS. We're delivering the full version of the definitions in our installations and plan to maintain the actual version of the definitions in the DefinitelyTyped repository on GitHub as we do for the DevExtreme project (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/devextreme).
 
If you need additional clarifications, feel free to contact us here or via email: info@devexpress.com
 
Thank you for cooperation.

**Comment by mhegazy** [comment]
thanks for the explanation.

**Comment by INullable** [comment]
@romanresh Thanks for providing the official version of the TS definitions for DevExpress ASP.NET/MVC controls. 

:+1:

**Pull request merged**
