### PR TITLE
Upgrade knuddels-userapp-backend-api to new version 1.20220921162223

### PR DESCRIPTION
**Pull request by SirezKN**
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I don't think there is a real owner here for this definition, which was an overlook, lets' say.
How is this one supposed to be update through reviews? (it's not maintainers role to review everything IMO).

**Comment by SirezKN** [comment]
> 

These are only definitions, so no way to test.

**Comment by SirezKN** [comment]
> I don't think there is a real owner here for this definition, which was an overlook, lets' say. How is this one supposed to be update through reviews? (it's not maintainers role to review everything IMO).

Sorry, I don't understand what you try to tell us.

**Review by Supporterino — APPROVED** [review]

**Review by Knuddels — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by SirezKN** [comment]
Ready to merge

**Pull request merged**
