### PR TITLE
lodash: added _.thru() method

### PR DESCRIPTION
**Pull request by chrootsu**
https://lodash.com/docs#thru
https://lodash.com/docs#_ (description of the chainable wrapper)

### CODE REVIEW

**Comment by chrootsu** [comment]
@vvakame I'm not sure about the case of the array wrapper. As well there should be `_([1, 2, 3]).thru<number[]>(...`, but I don't know how in this case to define the return type. Maybe you know a better way?

**Comment by vvakame** [comment]
http://goo.gl/8s0x3Z ? like this?

**Comment by chrootsu** [comment]
@vvakame Thank you for your variant, but if return LoDashWrapper<any[]> instead of LoDashArrayWrapper<any>, many of the methods that take an array as the first argument, will not be found because they defined only in LoDashArrayWrapper in the context of the chainable wrapper. The same with LoDashObjectWrapper. So I think let it remain as it is now.

**Comment by vvakame** [comment]
@chrootsu please check this document. https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4151-overload-resolution
http://goo.gl/o2E8ZA

**Comment by vvakame** [comment]
@basarat do you have any other advice?

**Comment by basarat** [comment]
> do you have any other advice

nope. `_` definitions have been a problem for my brain

**Comment by chrootsu** [comment]
@vvakame I have not forgotten about this PR, do not have time to study the matter in detail ... Most likely it will do this weekend.

**Comment by vvakame** [comment]
@chrootsu okay, it merged. if you have other improvement, please send a new pull request :wink:

**Comment by chrootsu** [comment]
@vvakame thank you, ok ^_^

**Pull request merged**
