### PR TITLE
[luxon] add Interval constructor definition

### PR DESCRIPTION
**Pull request by wallw-dev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Luxon Interval constructor](https://github.com/moment/luxon/blob/master/src/interval.js#L41-L58)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (did not change header since I'm not sure of other needed changes to update to 2.3.0; this change is good for 2.0 through current master branch)

### CODE REVIEW

**Review by CarsonF — COMMENTED** [review]
I'm hard pressed to approve this since the source code declares this as private.

You could create a wrapper function in your own codebase like:
```ts
const fromObject = ({ start, end }: Record<'start' | 'end', DateInput>) => 
  Interval.fromDateTimes(start, end);
```

**Comment by mastermatt** [comment]
I agree with @CarsonF, DefinitelyTyped types are _usually_ intended to type the public API.
Per the [docs](https://moment.github.io/luxon/api-docs/index.html#interval), `Interval` is not meant to be instantiated manually.
> **Creation** To create an Interval, use Interval#fromDateTimes, Interval#after, Interval#before, or Interval#fromISO.

**Comment by peterblazejewicz** [comment]
afaik it's only used within static factories, not even within package own's tests, IMO this is implementation detail, not intended to be used.

**Comment by wallw-bits** [comment]
My thinking was that there is no way to hide a constructor from dev users, and if dev users want to extend that class, they need the constructor definition (regardless of the "prefer composition over inheritance" discussion).

**Comment by CarsonF** [comment]
> My thinking was that there is no way to hide a constructor from dev users, and if dev users want to extend that class, they need the constructor definition (regardless of the "prefer composition over inheritance" discussion).


I've extended `DateTime` in my repo for a `CalendarDate`. The whole thing is a bit hacky, but the constructor line can just be ignored.
```ts
export class CalendarDate extends DateTime {
  protected constructor() {
    // @ts-expect-error DateTime constructor isn't defined, because it's private
    // but it does require an object
    super({});
  }
```
https://github.com/SeedCompany/cord-api-v3/blob/master/src/common/temporal/calendar-date.ts

**Comment by wallw-bits** [comment]
I ended up going the composition route and from that point you can either use a union type or extract an interface from both for the type to use elsewhere. I had originally gone with something close to what you have except with `// @ts-ignore`, which prompted me to try updating this.

I'm fine with not adding it since there are multiple workarounds.

**Pull request closed without merging**
