### PR TITLE
Correcting RGB Led methods

### PR DESCRIPTION
**Pull request by kashyaprahul94**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Please provide documentation for the change and add test.

**Comment by simonbuchan** [comment]
@sheetalkamat the bot reverted your labels - it expects an explicit review I assume?

**Comment by DanielRosenwasser** [comment]
@kashyaprahul94 the idea is not to add comments for the PR (I'd actually request you remove them, they're not entirely useful), but to instead add tests for the API surface area you're changing, and also linking to the documentation or source that justifies the change you're making.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
@kashyaprahul94 the idea is not to add comments for the PR (I'd actually request you remove them, they're not entirely useful), but to instead add tests for the API surface area you're changing, and also linking to the documentation or original source code that justifies the change you're making.

**Review by ujvzolee — CHANGES_REQUESTED** [review]
@kashyaprahul94 the changes seem legit and to speed up the PR here are the references:
https://github.com/rwaldron/johnny-five/blob/279205d086d14d2b4738b531d114f8e11f869629/lib/led/rgb.js#L178
http://johnny-five.io/api/led.rgb/#intensityvalue
http://johnny-five.io/api/led.rgb/#colorvalue

Could you just remove the comments and reflect the API changes in the tests? Cheers!

**Review by DanielRosenwasser — APPROVED** [review]

**Review by ujvzolee — APPROVED** [review]

**Pull request merged**
