### PR TITLE
Add new method to Chess.js

### PR DESCRIPTION
**Pull request by zacnomore**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Documentation of the new method: https://github.com/jhlywa/chess.js#board

### CODE REVIEW

**Comment by JacobFischer** [comment]
I am very sorry and intended to approve the PR as the original post asked, but that escaped me on mobile. If a maintainer wants to re-assign me the review I'd be happy to do it now.

**Comment by patrickjm** [comment]
@JacobFischer @zacnomore does this look all good for merge?

**Comment by JacobFischer** [comment]
I see the CI failed aeea50bc67ee9f9353507f07a99b2bd60488d737 because the version was changed from `0.10` to `0.10.3`. I'm personally unsure how that string works within DefinitelyTyped and why it broke. However, otherwise the commits look solid to me; adding types for the new methods chess.js recently released.

**Comment by zacnomore** [comment]
@JacobFischer Thanks for checking it out! I fixed that mistake with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42869/commits/88675eb07746e75ab3bc07c4a9d1f0096a0e87ea when I realized I wasn't supposed to include the patch version. Could you mark your approval here? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42869/files

**Review by JacobFischer — APPROVED** [review]
Thanks for adding the new methods 👍

**Pull request merged**
