### PR TITLE
node export http2 constants in standard way

### PR DESCRIPTION
**Pull request by ctaggart**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  This modifes the HTTP2 constants to the standard way to declare constants already used in the file. This results in us being able to import the HTTP2 constants via ts2fable. https://github.com/fable-compiler/ts2fable/issues/122 https://github.com/fable-compiler/ts2fable/pull/127/files

### CODE REVIEW

**Comment by ctaggart** [comment]
I don't understand the failed tslint on travis-ci. I get this locally:
```
C:\Users\camer\ts\DefinitelyTyped [http2-constants ≡]> npm run lint node

> definitely-typed@0.0.1 lint C:\Users\camer\ts\DefinitelyTyped
> dtslint types "node"
```

**Comment by eps1lon** [comment]
I checked out your PR and run the linter with a fresh `npm install` and `npm install typescrpt` and got the same errors as travis got. 

The error however has nothing to do with the PR. The behavior was added with Microsoft/dtslint#89. There are currently however 65 packages which use tslint:disable.

**Comment by kjin** [comment]
Given that the errors have nothing to do with the PR, this looks good to me :+1

**Comment by ctaggart** [comment]
@eps1lon,  Microsoft/dtslint#89 is fixed now. What is the easiest way to get this passing the unrelated tests now.

**Comment by eps1lon** [comment]
#21768 should fix this. So I think you should/can wait for that one to be merged. 

After that I'm not so sure. Maybe it's enough to rebase your pr with master to trigger a rerun or if you have to reopen it for travis to recognize the change.

**Comment by ctaggart** [comment]
Triggering a new CI build.

**Comment by ctaggart** [comment]
The build passes now that the `tslint:disable` stuff was sorted out and merged to master.

**Pull request merged**
