### PR TITLE
aws-lambda: Added Lambda Proxy and API Gateway Event definitions

### PR DESCRIPTION
**Pull request by buggy**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-output-format
- [X] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

Cc @skarum @StefH @tobyhede @darbio

### CODE REVIEW

**Comment by tobyhede** [comment]
Nice idea! +1

**Comment by StefH** [comment]
Nice.

**Comment by skarum** [comment]
Nice 👍  - but be AWS have started bundling d.ts files with aws-sdk. https://github.com/aws/aws-sdk-js#usage-with-typescript

**Comment by StefH** [comment]
Does aws also have these Lambda definitions? Because some months ago this was not present I think.

**Comment by skarum** [comment]
I think they have everything https://github.com/aws/aws-sdk-js/blob/master/clients/lambda.d.ts Looks like they auto generate them for everything in the SDK.

**Comment by buggy** [comment]
@skarum @StefH https://github.com/aws/aws-sdk-js/blob/master/clients provides the definitions for using the AWS SDK. It doesn't appear to provide definitions for the events, context or callback parameters that your Lambda function receives when executed. Until it does that we still need types/aws-lambda to provide those definitions.

This PR add support for the API GW event and Lambda Proxy Integration callback. If this PR is accepted then I'll create another PR to add DynamoDB Stream and SNS events.

**Pull request merged**
