### PR TITLE
CometD d.ts improvements

### PR DESCRIPTION
**Pull request by ip7e**
transformed cometD module to interface. 

usage:

```
var cometd: CometD;
```

added some methods: `clearListeners, clearSubscriptions, handshake, disconnect`

added definition for jQuery: `$.cometd` returns CometD type

### CODE REVIEW

**Comment by vvakame** [comment]
*cometd/cometd.d.ts*

to author(@derekcicerone). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by derekcicerone** [comment]
Sorry, I haven't used cometd in a few years, I'm likely not a good reviewer for this anymore.

**Comment by vvakame** [comment]
@derekcicerone okay, thanks!
@ddramone thanks mate!

**Comment by villanuevadani** [comment]
Can you add the following to the interface `CometD`?

```
	websocketEnabled?: boolean;
	subscribe?(channel: string, listener: (message: any) => void): void;

```

**Pull request merged**
