### PR TITLE
Titanium updates

### PR DESCRIPTION
**Pull request by ffMathy**
made fireEvent event arg optional.

### CODE REVIEW

**Review by amcasey — COMMENTED** [review]
There appear to be identical signatures on a bunch of other types.  Is this the only one for which the "event" parameter is optional?

**Comment by ffMathy** [comment]
Not sure. I'm just improving a few things at a time as I go along.

**Comment by amcasey** [comment]
Okay.  Let's give @appcelerator and @janvennemann some time to respond.

**Comment by janvennemann** [comment]
@ffMathy the Titanium typings will be auto generated. Is there a matching PR on our side to reflect this change?

**Comment by ffMathy** [comment]
Nope, I didn't know these were auto-generated.

**Comment by janvennemann** [comment]
The typings are auto generated from our [apidoc](https://github.com/appcelerator/titanium_mobile/tree/master/apidoc/Titanium) folder.

For this change, for example, you need to modify [Proxy.fireEvent](https://github.com/appcelerator/titanium_mobile/blob/40bd1d92749857a37ebea2fa87c2f064d1775a51/apidoc/Titanium/Proxy.yml#L60) and make the parameter optional by adding `optional: true`. Then you can update typings with `npm run build:docs -- --format typescript --output .`, which will create the updated `index.d.ts` in the root dir of `titanium_mobile`.

**Review by amcasey — CHANGES_REQUESTED** [review]
Sounds like a change to the upstream project is required first?

**Comment by ffMathy** [comment]
I made a PR for it here: https://github.com/appcelerator/titanium_mobile/pull/11371

**Review by janvennemann — APPROVED** [review]
Upstream PR was merged so this is good to go!

**Review by amcasey — APPROVED** [review]

**Pull request merged**
