### PR TITLE
[@types/enzyme] add generic types support to getDOMNode

### LINKED ISSUE #35178: [@types/enzyme] getDOMNode contains vague return type
```typescript
it('disables button when textarea is empty', () => {
  const addIpAddress = jest.fn();
  const wrapper = mountWithIntl(
    <IpTextArea addIpAddress={addIpAddress} maxIpAmount={25} />
  );
  expect(wrapper.find(Button).getDOMNode().disabled).toBe(true);
});
```
**Error**: 
`Property 'disabled' does not exist on type 'Element'.ts(2339)`

**Proposed API:** 
```typescript
it('disables button when textarea is empty', () => {
  const addIpAddress = jest.fn();
  const wrapper = mountWithIntl(
    <IpTextArea addIpAddress={addIpAddress} maxIpAmount={25} />
  );
  expect(wrapper.find(Button).getDOMNode<HTMLButtonElement>().disabled).toBe(true);
});
```

What do you think about it? @MartynasZilinskas, @MarianPalkus, @screendriver, @DovydasNavickas, @ferdaber , @eps1lon

### PR DESCRIPTION
**Pull request by mateuszsokola**
Closes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35178

```typescript
it('disables button when textarea is empty', () => {
  const addIpAddress = jest.fn();
  const wrapper = mountWithIntl(
    <IpTextArea addIpAddress={addIpAddress} maxIpAmount={25} />
  );
  expect(wrapper.find(Button).getDOMNode().disabled).toBe(true);
});
```
**Error**: 
`Property 'disabled' does not exist on type 'Element'.ts(2339)`

**Proposed API:** 
```typescript
it('disables button when textarea is empty', () => {
  const addIpAddress = jest.fn();
  const wrapper = mountWithIntl(
    <IpTextArea addIpAddress={addIpAddress} maxIpAmount={25} />
  );
  expect(wrapper.find(Button).getDOMNode<HTMLButtonElement>().disabled).toBe(true);
});
```

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] ~~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~~ - I didn't find any existing docs for getDOMNode
- [X] ~~Increase the version number in the header if appropriate.~~
- [X] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]

**Comment by vkrol** [comment]
@mateuszsokola @eps1lon this change is described in "Common mistakes":
> getMeAT<T>(): T: If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion. Prefer to use a real type assertion, e.g. getMeAT() as number. Example where a type parameter is acceptable: function id<T>(value: T): T;. Example where it is not acceptable: function parseJson<T>(json: string): T;. Exception: new Map<string, number>() is OK.

https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes

I think it is better to revert this change.

**Comment by vkrol** [comment]
@sandersn what do you think about this?

this change is described in "Common mistakes":

> getMeAT(): T: If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion. Prefer to use a real type assertion, e.g. getMeAT() as number. Example where a type parameter is acceptable: function id(value: T): T;. Example where it is not acceptable: function parseJson(json: string): T;. Exception: new Map<string, number>() is OK.

https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes

I think it is better to revert this change.

**Comment by vkrol** [comment]
@eps1lon please could you comment on your -1?

**Comment by mateuszsokola** [comment]
@vkrol i am ok with that.

**Pull request merged**
