### PR TITLE
Add resolve-from

### PR DESCRIPTION
**Pull request by unional**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by horiuchi** [comment]
@unional Please rename to `resolve-form/resolve-form.d.ts`, and test file too.

**Comment by unional** [comment]
Even if the `package.json/main` is `index.js`? (this repo didn't really specify it, so it uses the default).
https://github.com/sindresorhus/resolve-from/blob/master/index.js

**Comment by unional** [comment]
Coming from `typings` so the convention is different. :smile:

**Comment by horiuchi** [comment]
@unional Thank you for renaming! :+1:

**Pull request merged**
