### PR TITLE
chrome: Split deprecated namespaces to avoid ambiguity

### PR DESCRIPTION
**Pull request by xuhdev**
typescript-eslint considers the following ambiguous:

```typescript
/**
 * Use the chrome.browser API to interact with the Chrome browser associated with
 * the current application and Chrome profile.
 * @deprecated Part of the deprecated Chrome Apps platform
 */
declare namespace chrome.browser {
```

As a result, the whole `browser` namespace is considered deprecated.

See https://github.com/typescript-eslint/typescript-eslint/issues/10220#issuecomment-2440563574

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2febef1d16d39cce305638a2375bf6ebb00db279
</p>

**Comment by erwanjugand** [comment]
Hello @xuhdev, To better understand the bug, could you please share a reproducible example or detailed steps to replicate the issue? :)

**Comment by xuhdev** [comment]
Sure. After installing this package and turning on the [`no-deprecated`](https://typescript-eslint.io/rules/no-deprecated/) rule, eslint would complain all lines that use `chrome.`, regardless of whether it's deprecated:

```
// Eslint complains the following line uses deprecated "chrome." namespace
chrome.action.onClicked.addListener(() => {});
```

This is the response I got from eslint side: https://github.com/typescript-eslint/typescript-eslint/issues/10220#issuecomment-2440563574

**Comment by erwanjugand** [comment]
Indeed your PR fixes this problem but perhaps we should scope all namespaces into a "Chrome" namespace to improve maintainability. These changes should be transparent and testing should help us.

Would a maintainer have an opinion?

**Comment by xuhdev** [comment]
I agree it's better moving all `chrome.*` namespaces under an umbrella `chrome` namespace.

**Comment by matcarlson** [comment]
+1 - It's a bit more work but we would greatly appreciate the change being applied to each namespace. 

Similarly but differently I have wanted to break the monolithic `index.d.ts` into a file for each individual namespace to increase readability and maintainability. Combining the two might make the types more readable, and it is similar to the layout of  [the example for mutli-file namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html#multi-file-namespaces) from the Typescript handbook.

**Comment by xuhdev** [comment]
Awesome! Do we have a consensus? If yes, I'll start making the change.

**Comment by xuhdev** [comment]
> Indeed your PR fixes this problem but perhaps we should scope all namespaces into a "Chrome" namespace to improve maintainability. These changes should be transparent and testing should help us.
> 
> Would a maintainer or owner have an opinion?

I've updated the PR. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71019/commits/e9265b02e116ff37ba0f047994e6ad0930190aed contains the changes before formatting, so it'll be easier to review. Then the file is formatted with `pnpm dprint fmt -- types/chrome/index.d.ts`.

**Review by erwanjugand — APPROVED** [review]
LGTM

**Comment by xuhdev** [comment]
Could someone else take a look? This PR is quite easy to make conflict...

**Comment by nicolas377** [comment]
> I have wanted to break the monolithic `index.d.ts` into a file for each individual namespace to increase readability and maintainability.

This is actually something I've wanted to do for a while as well. I started working on a script [here](https://github.com/nicolas377/chrome-typings-remake/tree/main/transformer) (check out plan.md for my plan on how the transformer would work) a while ago, but it's been dormant. I'd like to have some more maintainers sign off before we go about actually making the change. @xuhdev are you using this pr to make the entire change?
Let's split this discussion off into a discussion. I'm happy to do my remake strategy if people are on board with it.

**Comment by xuhdev** [comment]
I'm using this PR to move everything under an umbrella chrome namespace, but I didn't break the file up.

**Comment by nicolas377** [comment]
Gotcha, I think I'd be good with it as a temp fix until we do the big change. Discussion is at #71183.

**Comment by erwanjugand** [comment]
I also recommend having a dedicated PR to split `index.d.ts` into several files

**Comment by xuhdev** [comment]
Seems like the plan to proceed is a bit ambiguous. I can revert this PR to the state of only moving the `deprecated` annotations to subnamespaces only. If you can give me the green light, I'll work on it, since editing this file back and forth isn't quite pleasant :cry: 

(Link to https://github.com/typescript-eslint/typescript-eslint/issues/9902#issue-2493189703 for additional visibility)

**Comment by erwanjugand** [comment]
@xuhdev Your current changes are good 

If you resolve this last conflict, we should be able to quickly review this PR :)

**Comment by xuhdev** [comment]
@erwanjugand Thanks, resolved!

**Review by erwanjugand — APPROVED** [review]
Looks good to me

**Review by rbuckton — APPROVED** [review]

**Comment by xuhdev** [comment]
Ready to merge

**Pull request merged**
