### PR TITLE
difference between Crypt and Hash

### PR DESCRIPTION
**Pull request by mathewmeconry**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Added the encrypt and decrypt functions to the typings for Ciphers.

### CODE REVIEW

**Comment by mhegazy** [comment]
This change is not compatible with the Types-2.0 branch. this module has been changed to make sure it does not put any names in the global namespace. why are you making this change?

**Comment by mhegazy** [comment]
if all you need is the changes to the Hashes property types, then please revert the changes done to the shape of the module, i.e. `declare module "crypto-js" ... `

**Comment by mathewmeconry** [comment]
@mhegazy I need this change that I can encrypt and decrypt with Ciphers. with the current typing it's not possible to decrypt something

**Comment by mhegazy** [comment]
what version of the compiler are you using? what are the issues you are running into?

**Comment by mathewmeconry** [comment]
I'm using tsc 1.8.10 and don't habe any issues. 
The typing before just didn't definded the decryption function for ciphers

**Comment by RyanCavanaugh** [comment]
You can look at what other files in the types-2.0 branch are doing to create modules to see how to write a file for this branch. Notably you should not be having `declare module "crypto-js"` -- there should instead be top-level exports, etc..

**Comment by rbuckton** [comment]
@mathewmeconry do you plan to submit a follow-up to the comments above?

**Comment by mathewmeconry** [comment]
@rbuckton @RyanCavanaugh I hope the changes are now correct

**Comment by RyanCavanaugh** [comment]
There's still a merge conflict - can you take a look? Thanks!

**Comment by mathewmeconry** [comment]
@RyanCavanaugh  there are a lot of conflicts and the whole cryptojs stuff is now already done by someone else. I close this pull request

**Pull request closed without merging**
