### PR TITLE
[mongoose] add unwind method with new params type

### PR DESCRIPTION
**Pull request by lonsenluo**
In mongodb 3.2, the unwind operator can with a object params.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

### CODE REVIEW

**Comment by simonxca** [comment]
@lonsenluo thanks!

**Comment by sindrenm** [comment]
Awesome, @lonsenluo! :heart:

Do you mind adding a small test as well? It should just call the unwind function with proper arguments and still pass `tsc` when it's run.

Also, feel free to add yourself to the “Definitions by” list as is mentioned here:

[Make a pull request → Edit an existing package][1]

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#edit-an-existing-package

**Comment by lonsenluo** [comment]
@sindrenm Yes,I test and used in my project.

**Comment by sindrenm** [comment]
That's great! But what I mean is adding a line in [test file] as well. All you need to do is add a line in that file that calls `unwind` in the way that the docs say that it should be called, and then run `tsc` on the project to verify that the definition does what it's supposed to do. :smile: 

[test file]: https://github.com/lonsenluo/DefinitelyTyped/blob/master/mongoose/mongoose-tests.ts

**Comment by sindrenm** [comment]
Or rather, you want to add a call to `unwind` of the same signature that you defined here. Right now, the test file tests these two calls to `unwind`:

```javascript
aggregate.unwind("tags").unwind('tags');
aggregate.unwind("a", "b", "c").unwind('tag1', 'tag2');
```

But you also want to add a line that calls `unwind` with the `...opts` syntax as well.

**Comment by sindrenm** [comment]
Perfect, thanks, @lonsenluo! :+1:

**Comment by horiuchi** [comment]
👍

**Pull request merged**
