### PR TITLE
[enzyme] Pin @types/cheerio

### PR DESCRIPTION
**Pull request by astorije**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46006#issuecomment-699079290

### CODE REVIEW

**Comment by astorije** [comment]
So at the moment the dependency as listed in `@types/enzyme` is `"@types/cheerio": "*",`, which ends up breaking builds that were already having `@types/cheerio` in their `yarn.lock`. I see DT's CI doesn't allow for that, which is a little unfortunate as it breaks in all our repos.
What is the recommendation on that?

**Review by ljharb — APPROVED** [review]
If this works, great! but i was under the impression that DT packages lacked the ability to specify explicit dependencies.

**Comment by ljharb** [comment]
bump, in case that helps

**Comment by ljharb** [comment]
bump

**Comment by ljharb** [comment]
bump

**Comment by ljharb** [comment]
bump

**Comment by ljharb** [comment]
bump

**Pull request closed without merging**
