### PR TITLE
Fix for issue 14967 in DefinitelyTyped

### PR DESCRIPTION
**Pull request by 3n-mb**
This fixes (issue 14967 in DefinitelyTyped)[https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14967]

### template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

### Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14967
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by jtut1731** [comment]
@3n-mb ...I also have the same CI errors...seems to be due to some modules that depend on @types/node are not Typescript 2.0 compatible due to Jasmine not being Typescript 2.0 compatible.  #15013 
Not sure who to alert to this.

**Comment by minestarks** [comment]
@jtut1731 @3n-mb could you both try merging from master to trigger a rebuild? The failures are external to your code

**Comment by 3n-mb** [comment]
@jtut1731 I haven't run ci that you have, but I have been running this changed definition for almost a year, i.e. on different TS's and node's and working with arrays, returned by node, as per docs. I used to keep private d.ts in project, and now moving code to use `@types` goodness :) .

@minestarks I have no idea what you mean by "could you both try merging from master to trigger a rebuild".

Guys, there are only four (4) characters to add. I may reproduce these in any branch easily.

Thank you for dealing with this.

**Comment by minestarks** [comment]
@3n-mb There's nothing wrong with your change. I just can't merge until we get a clean test run :/ Sorry for the trouble.

The PR #14819 should have fixed these failures. 

Could you merge from the master branch, and push an update? This should trigger the tests to run again, hopefully they'll be clean and I'll merge.

**Comment by 3n-mb** [comment]
I went a simpler root of clicking on "propose file changes" button. It seemed to work in another place.
So, these changes are now in PR #15057

**Comment by 3n-mb** [comment]
Wow. This worked for ws package, but seems to fail here.

**Comment by jtut1731** [comment]
"Merge from the master branch, and push an update" can be done by following:
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by minestarks** [comment]
Alternatively, you can close + reopen this PR

**Comment by 3n-mb** [comment]
That new PR also fails the same way. Guess it is #14819 , but you know better your infra.

**Comment by minestarks** [comment]
Took this change in #15057

**Pull request closed without merging**
