### PR TITLE
Add webcrypto-core

### PR DESCRIPTION
**Pull request by microshine**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by aozgaa** [comment]
Can you rename the test file? ie:
`webcrypto-cote-tests.ts` -> `index-tests.ts`

**Comment by microshine** [comment]
@aozgaa I updated names for test file

**Comment by aozgaa** [comment]
Why are we adding null to all the types? This seems to disagree with the interface here:

https://github.com/PeculiarVentures/graphene/blob/56bb5b4bdfb18ecefd6f2be931feb7fc11009aed/src/template.ts

**Comment by microshine** [comment]
@aozgaa 
here is a [code](https://github.com/PeculiarVentures/node-webcrypto-p11/blob/develop/lib/crypto/aes.ts#L66) exaple of such `ITemplate` usage. I'm using `--strictNullChecks` for my TS project. So I can't use it without 'null' type.

PS there can be one more way of usage - 
```typescript
let vals = key.key.getAttribute({ value: undefined, valueLen: undefined });
```
but it's not pretty :)

What do you think?

**Comment by microshine** [comment]
@aozgaa Could you check error it's not my d.ts file, I'm suprised that it was broken

**Comment by microshine** [comment]
image

**Comment by aozgaa** [comment]
Does passing in `undefined` arguments work? That appears to be what the interface expects by making the properties optional.

**Comment by microshine** [comment]
@aozgaa I removed `null` types. But I can't understand why my travis-cli test is wrong. It shows error on libs that I didn't change. What is wrong?

**Comment by rmhrisk** [comment]
@aozgaa Do you have any ideas what we need to do here?

**Comment by minestarks** [comment]
@microshine I'm not entirely sure what went wrong with the tests either, but they seem unrelated. Could you merge the upstream changes to rerun the tests? I'll merge it in if the tests pass. Thank you.

**Comment by paulvanbrenk** [comment]
This PR seems abandoned, please re-open when you've fixed the merge issue and the Travis checks pass.

**Pull request closed without merging**
