### PR TITLE
[cookie-parser] finish incomplete typings

### LINKED ISSUE #16235: cookie-parser declaration file is incorrect
It's not only a function there. 

```typescript
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/cookie-parser/index.d.ts
declare module 'cookie-parser' {
// Type definitions for cookie-parser v1.3.4
// Project: https://github.com/expressjs/cookie-parser
// Definitions by: Santi Albo <https://github.com/santialbo/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped




import express = require('express');
function e(secret?: string, options?: any): express.RequestHandler;
namespace e { }
export = e;
}
```

### PR DESCRIPTION
**Pull request by BendingBender**
Fixes #16235.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/expressjs/cookie-parser
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by BendingBender** [comment]
No idea, why travis build fails. Typings contain the necessary compiler version header and restrict compiler version to 2.2. Nevertheless, travis build still tries to build with 2.0 and suggests to restrict the version to 2.3. I tried it out and it still didn't build. It looks like the travis build ignores the the header altogether.

**Comment by leonard-thieu** [comment]
The error message can be confusing. You actually need to add the header to `connect-timeout` and `easy-session`.

**Comment by BendingBender** [comment]
So do you think I should restrict the other two or change the definitions not to use the newer compiler features?

**Comment by leonard-thieu** [comment]
I think using up to TypeScript 2.2 features is relatively safe.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
