### PR TITLE
Removed OpenApi-v3 types

### PR DESCRIPTION
**Pull request by IulianOctavianPreda**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
x-ref:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46475#issuecomment-674539496

**Comment by thinkh** [comment]
@IulianOctavianPreda Why were the types for OpenAPI v3 removed? Is there an alternative available?

**Comment by IulianOctavianPreda** [comment]
> @IulianOctavianPreda Why were the types for OpenAPI v3 removed? Is there an alternative available?

Hello,

They were removed because it was a mistake in the first place to put them as those types  are not for a library that needs them. They are only specifications. 

I created a repository to hold the types and posted them to npm. 

https://www.npmjs.com/package/@tstypes/openapi-v3

If you find any misalignment with the specs please open an issue:

https://github.com/TsTypes/TypescriptTypes

**Comment by thinkh** [comment]
@IulianOctavianPreda thanks for the quick reply and the pointer to your repo. :+1:

**Pull request merged**
