### PR TITLE
[node-fetch] fix blob() return type

### PR DESCRIPTION
**Pull request by kbkk**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-fetch/node-fetch/blob/bb9c96de8059821b9f3dfdc85128b6131d144bf2/src/body.js#L94
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by AndrewLeedham — APPROVED** [review]
LGTM

**Review by kyranet — APPROVED** [review]
LGTM to me as well. 👍

**Comment by nikcorg** [comment]
@kbkk @AndrewLeedham @kyranet This PR is incorrect: `.blob()` returns a [`FetchBlob`](https://github.com/node-fetch/fetch-blob), as a `Blob` isn't a thing in node.

**Comment by AndrewLeedham** [comment]
> @kbkk @AndrewLeedham @kyranet This PR is incorrect: `.blob()` returns a [`FetchBlob`](https://github.com/node-fetch/fetch-blob), as a `Blob` isn't a thing in node.

Ah yes missed this at the top: https://github.com/node-fetch/node-fetch/blob/bb9c96de8059821b9f3dfdc85128b6131d144bf2/src/body.js#L10

**Comment by AndrewLeedham** [comment]
Hmm although these definitions do define `Blob`: https://github.com/kbkk/DefinitelyTyped/blob/422d426e1540021a5f13f77c499c344026fed4e5/types/node-fetch/index.d.ts#L134-L139 which seem to be similar to those from `fetch-blob` https://github.com/node-fetch/fetch-blob/blob/master/index.d.ts. Perhaps it should depend on those from `fetch-blob` itself?

**Comment by AndrewLeedham** [comment]
Ok a bit of further investigation. I think these definitions are right. Because these definitions are meant to target `node-fetch@2.5`. Which defines its own Blob: https://github.com/node-fetch/node-fetch/blob/0c2294ec48fa5b84519f8bdd60f4e2672ebd9b06/src/blob.js

`fetch-blob` was introduced in v3.

**Comment by nikcorg** [comment]
@AndrewLeedham you're right, my mistake.

I do wonder if this should be PR'd for v3, so that the change won't be lost.

**Pull request merged**
