### PR TITLE
[react-google-login-component] Ensure React types match runtime version

### PR DESCRIPTION
**Pull request by eps1lon**
16.x is the highest major supported: https://unpkg.com/browse/react-google-login-component@0.9.3/package.json

### CODE REVIEW

**Comment by andrewbranch** [comment]
Should this not include setting a minimum version range for `@types/react` in package.json?

**Comment by eps1lon** [comment]
I'm not aware that this is possible. In prior issues, this was rejected by Microsoft folks: https://github.com/microsoft/DefinitelyTyped-tools/issues/433

Right now I'm making a judgement call to side on the "every type change is a breaking change" since the scoped JSX namespace has been out for over half a year and was backported to 15.x, 16.x and 17.x

**Comment by peterblazejewicz** [comment]
I'd vote for ^16, to be pragmatic and looking forward (16 was out 6 years ago)

**Comment by eps1lon** [comment]
I don't understand the rules that are applied here but if you want to restrict the type version now, I'm all for it.

**Comment by peterblazejewicz** [comment]
let's quickly discuss (aka bring the cavalry), /cc @andrewbranch

**Comment by andrewbranch** [comment]
> I'm not aware that this is possible. In prior issues, this was rejected by Microsoft folks

DT still doesn't support specifying `peerDependencies`, but I don't think the idea was rejected. But specifying a version range for a `@types` dependency was already possible before https://github.com/microsoft/DefinitelyTyped-tools/issues/433 was opened, and since the pnpm transition, `@types` dependencies are always explicitly listed in package.json, effectively removing the `*` default range that used to get added by tooling. Since the dependency range will always be written explicitly by humans going forward, we don't expect them all to be `*`; we expect maintainers to put down whatever range makes sense. In this case, it sounds like something with a minimum range of `16.x` is appropriate.

**Comment by peterblazejewicz** [comment]
@eppsilon you pick, we follow :bow:

**Comment by eps1lon** [comment]
Following current practices and using 16.x.

**Review by peterblazejewicz — APPROVED** [review]
@eppsilon 🙇🏻

**Comment by eps1lon** [comment]
Ready to merge

**Pull request merged**
