### PR TITLE
add `object.assign`

### PR DESCRIPTION
**Pull request by ljharb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/object.assign/auto.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5454ef5fc80ec143329ff6fcb3a07d61462bbf07
</p>

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/object.assign/implementation.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 91621db8b771f7145fd69dfaa9e4ed89e8a7876a
</p>

**Comment by dnalborczyk** [comment]
@ljharb curious, you are the owner of the original package. why don't you distribute the types with that package? as far as I know, that is the encouraged way of distributing types and also taking load off of this repository.

**Comment by peterblazejewicz** [comment]
there is no semver  involved when shipping types with a module itself, IMO, package version dictates the code resolution. also it's recommended #1 way to distribute types (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#handbook-content).

**Comment by ljharb** [comment]
@peterblazejewicz a breaking change in the types breaks people, and so should be a major bump, but if it's not a breaking change in the JS, it shouldn't be - that's the inherent, unavoidable conflict, and it's not mentioned at all in that guide.

Lots of tools/frameworks make recommendations that aren't actually the best solution, and are often just the best *for the tool* - the appeal to authority doesn't hold up here.

Either way, I hope this discussion (that I've had like 5 or 6 times on previous PRs here) doesn't delay this relatively trivial PR.

**Comment by peterblazejewicz** [comment]
maybe I'm misunderstood: IMO if ones publishes types alongside with the source, there are no problems with versioning involved.
you've got valid question to answer.
I could answer that way: publishing here, gives types visibility, so we can catch up minor problems quickly (without a need to republish original source).

**Review by peterblazejewicz — APPROVED** [review]

**Comment by ljharb** [comment]
@peterblazejewicz certainly publishing in DT means the TS team keeps it up to date and validates it :-)

**Comment by ljharb** [comment]
Ready to merge

**Pull request merged**
