### PR TITLE
Showdown 1.4.1

### PR DESCRIPTION
**Pull request by tan9**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://github.com/showdownjs/showdown/blob/master/CHANGELOG.md and https://github.com/showdownjs/showdown/tree/master/src .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tan9** [comment]
@cbowdon, would you please help reviewing this PR about the latest version of slowdown?

**Comment by vvakame** [comment]
We can't get response from author. I'll merge this PR in 2 days. please ping me again.

**Comment by tan9** [comment]
@vvakame pong

**Comment by vvakame** [comment]
👍

**Pull request merged**
