### PR TITLE
[yup] Make typing for oneOf work to refine the schema type

### PR DESCRIPTION
**Pull request by iansan5653**
This PR adds better typing for yup's `oneOf` schema function, which asserts that the tested item is one of the given items. Until now, the function was typed such that it did not refine the type of the schema. For example:
```ts
const strSchema = yup.string().oneOf(["a","b"]); // has type StringSchema<string>
```
This is really frustrating when trying to make your schemas match your TypeScript types as you can't validate anything that has an enumerated type without a type assertion.

This change fixes that, so now calling `oneOf` will return the enumerated type schema:
```ts
const strSchema = yup.string().oneOf(["a","b"]); // has type StringSchema<"a" | "b">
```

Note that the optionality of the schema is maintained as noted in the docs:

> Note that `undefined` does not fail this validator, even when `undefined` is not included in `arrayOfValues`. If you don't want `undefined` to be a valid value, you can use `mixed.required`.

```ts
const strSchema = yup.string().notRequired().oneOf(["a","b"]); // has type StringSchema<"a" | "b">
```

Also adds the `equals()` test as an exact alias for `oneOf` (see [documentation](https://github.com/jquense/yup#mixedoneofarrayofvalues-arrayany-message-string--function-schema-alias-equals) section title).

This PR also updates the tests accordingly.

This could be considered a breaking change; I'm not really sure if it counts since it's just more accurate typing. 

**Note**: I had to update the TS version to 3.6 because one test was failing in 3.5 and below - somehow TypeScript couldn't infer the type of mixed schema fields on object schemas and was causing the inferred type to be `key: unknown`. Technically it still works in 3.5 and below (just with looser types in rare scenarios), but that test would have to be removed.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup#mixedoneofarrayofvalues-arrayany-message-string--function-schema-alias-equals
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by mauricedb** [comment]
@iansan5653 

Sweet, I really like the ability to infer the correct type from `yup.string().oneOf()`.

However I am not so happy with the default inclusion of `undefined`. I tried this in a codebase I am currently working on and the result was 200 or so compile errors, mostly because of types not matching `undefined`. I know you can add `.required()` to get rid of the `undefined` but that has additional implications for Yup validation. For example:
```
const emptyOrX = yup
  .string()
  .oneOf(["", "X"])
  .required();

console.log(emptyOrX.isValidSync("x"));
console.log(emptyOrX.isValidSync(""));
```
In this case `emptyOrX` seems to allow `""` but Yup will extually fail validation here.

See [here](https://github.com/jquense/yup#why-does-infertype-not-default-to-nonrequired) for more info.

Another this is the derived type. The values from `oneOf()` also seem to overide the generic type specified with `yup.string<T>()' or `yup.mixed<T>` which I don't think should be the case.

**Comment by iansan5653** [comment]
I think I screwed up when rebasing this branch - those changes shouldn't be part of this PR. I do want to make that change eventually, but I know that's a huge breaking change so that would definitely be a whole separate discussion.

**Comment by iansan5653** [comment]
> I am not so happy with the default inclusion of `undefined`.

I'm not sure what you mean here -- it doesn't add `undefined` if it's not there - it only maintains it if it already is, which is the behavior of the library. For example the following test (L389 of the test file):

```ts
numSchema.oneOf([1, 2] as const); // $ExpectType NumberSchema<1 | 2>
```

Since `yup.string()` makes `StringSchema<string>` (something I don't necessarily agree with but that's a separate discussion), the result of `yup.string().oneOf(["", "X"] as const)` *should* just be `StringSchema<"" | "X">`. If it's not then that's an issue I need to fix.

> The values from oneOf() also seem to overide the generic type specified with yup.string<T>() or yup.mixed

I'm not really sure I understand this either. For example, if you have `yup.string<"a" | "b" | "c">().oneOf(["a", "b"] as const)` should the result not be `StringSchema<"a" | "b">`?

Note how I used `as const` assertions in the examples - this is important and maybe what is causing your issues? Without `as const`, `["a", "b"]` gets typed by TypeScript as `string[]` and won't refine the type with `oneOf` at all.

**Comment by iansan5653** [comment]
I'm really not sure what's up with the performance - all I did was merge in the changes from the other PR and they were pretty minor.

**Comment by mauricedb** [comment]
@iansan5653 

Sorry, my bad. The compile errors I mentioned are about `yup.mixed()` not `yup.string()`.

The following works just fine and I really like it 👍:
```
const emptyOrX = yup.string().oneOf(["", "X"]);

const objectWithEmptyOrX = yup.object({
  emptyOrX
});

type SomeThing = yup.InferType<typeof objectWithEmptyOrX>;

const someThing: SomeThing = {
  emptyOrX: "X"
};
```

Turns out the errors I was seeing where about `yup.mixed()`.

Take the following: 
```
const emptyOrXOr1 = yup.mixed().oneOf(["", "X", 1]);

const objectWithEmptyOrX = yup.object({
  emptyOrXOr1
});

type SomeThing = yup.InferType<typeof objectWithEmptyOrX>;
```

The `SomeThing` type now infers to:
```
type SomeThing = {
    emptyOrXOr1?: string | number | undefined;
}
```
With an extra `undefined` that wasn't there before.

Instead I think it should infer to:
```
type SomeThing = {
    emptyOrXOr1: "" | "X" | 1;
}
```

**Comment by iansan5653** [comment]
@mauricedb the reason for that is because `mixed` defaults to `any` which includes `undefined` so it narrows down but keeps the optionality. I guess we could make it different just for `mixed`. However, then calling `mixed().notRequired().oneOf(["x"])` would result in `MixedSchema<"x">`, losing the optionality.

**Comment by mauricedb** [comment]
Looks like changing `yup.mixed()` from `any` to `<T extends string | number | boolean | symbol | object | null | undefined = string | number | boolean | symbol | object>(): MixedSchema<T>` would work.

**Comment by iansan5653** [comment]
Good suggestion - I went ahead and did that, with two changes: kept `extends` clause to `any`, and
included `null` in default (because `const schema = yup.mixed().validate(null);` validates).

Of course #44589 will revert this anyway if merged.

**Comment by mauricedb** [comment]
LGTM. I am pretty sure #44589 will be merged but that will take a bit longer. Lets get this one merged first.

**Review by mauricedb — APPROVED** [review]
👍

**Comment by iansan5653** [comment]
Ready to merge

**Review by mauricedb — APPROVED** [review]

**Pull request merged**
