### PR TITLE
feat(node): add `entryType` to all types and interfaces that use it

### PR DESCRIPTION
**Pull request by ryanrw**
Add `entryType` to all types and interfaces that use it. Because I think this is better than using `string` or `string[]` type, which could easily cause an error.

PS. I run the `npm test` twice and it passed on my machine.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [performanceEntry.entryType](https://nodejs.org/api/perf_hooks.html#perf_hooks_performanceentry_entrytype)

### CODE REVIEW

**Comment by Flarna** [comment]
Bot closes PRs based on commit date. You should rebase your branch to tip of master and retry.

**Comment by Ryan-Willpower** [comment]
> Bot closes PRs based on commit date. You should rebase your branch to tip of master and retry.

Could you explain how?

**Comment by Flarna** [comment]
Assuming you have checked out your branch.

- Configure this repo as remote named `upstream`: `git remote add upstream https://github.com/DefinitelyTyped/DefinitelyTyped.git`
- Fetch remotes: `git fetch --all`
- rebase: `git rebase upstream/master`
- force push your branch: `git push -f`
- reopen this PR (if github allows) or create a new one

**Comment by Ryan-Willpower** [comment]
> Assuming you have checked out your branch.
> 
> * Configure this repo as remote named `upstream`: `git remote add upstream https://github.com/DefinitelyTyped/DefinitelyTyped.git`
> * Fetch remotes: `git fetch --all`
> * rebase: `git rebase upstream/master`
> * force push your branch: `git push -f`
> * reopen this PR (if github allows) or create a new one

Thanks for your suggestion! 🙌

**Pull request closed without merging**
