### PR TITLE
fix message.fromBinary

### PR DESCRIPTION
**Pull request by errietta**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
@sandersn

**Comment by sandersn** [comment]
Yep, the fix is a follow-on to the fix that I linked. That fix made sure not to install `typescript@3.3` since it's already installed as `typescript@next`. The fix I need to make is to not *test* `typescript@3.3` (since it's already tested as `typescript@next`).

@errietta That means the failure is not related to your change at all, it is good on all versions of typescript. Want me to merge it?

**Comment by sandersn** [comment]
Actually, it looks like errors are getting swallowed by this failure. I did get an error on TS3.1: ReadableStream is not generic. So it looks like you may need a separate version for 3.1 and 3.2. The method for this has changed (and is much more complicated :(

See peerjs for a good example of a package that ships 3.2 along with 3.1 and earlier types. Basically, you create a subdirectory, ts3.2, and then put a special field in the parent package.json that points Typescript 3.2 to that subdirectory.

**Comment by errietta** [comment]
@sandersn thanks for the help, will check in a couple days, I guess this is easier now we have the real error :)

**Comment by sandersn** [comment]
Thanks!

**Comment by errietta** [comment]
Thanks for the help as well @sandersn , was this the best way to do it, i feel like I had to duplicate so many files to get the 3.2 directory 😱

**Comment by sandersn** [comment]
Yep! We might have to revisit this structure. It feels pretty wrong to me too.

**Pull request merged**
