### PR TITLE
[Node] Add missing OS Signals and EventEmitter APIs in Process, correct emit APIs

### LINKED ISSUE #17142: [@types/node] Wrong type definition for emit
in this commit
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c9e01b3e760ee7e2f93a7c9052d432f6713347c8#diff-7d84e08967cded0b99ed4328aab0a1a8R489
EventEmitter arguments were defined like this. 
emit(event: Signals, listener: () => void): boolean;
but as below,
https://nodejs.org/dist/latest-v8.x/docs/api/events.html#events_emitter_emit_eventname_args
emitter.emit(eventName[, ...args])
The arguments except 'eventName' can be omitted.

it should be changed like this.
emit(event: Signals, listener?: () => void): boolean;

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/os.html#os_signal_constants
https://nodejs.org/api/process.html
https://nodejs.org/api/events.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This is a followup on #16705 and related to #17137, #17138, 
Should also fix #17142.

@andy-ms, @mdebruijne, @sandersn Please take a look.

### CODE REVIEW

**Comment by mdebruijne** [comment]
@Flarna; thank you for the follow up, really appreciated!

Please note that the args of the emit method are optional, see https://nodejs.org/dist/latest-v8.x/docs/api/events.html#events_emitter_emit_eventname_args. In the original file (and in your patch) none of the emit args are optional. Maybe this is a good moment to fix this oversight.   ;-)

I don't think it is a good idea to add a catch-all to any type for custom event emitters/listeners to the node definition file. If a module uses a custom event emitter/listener, then it should be in the corresponding definition file with the correct type. All definition files in this repository do this already.

**Comment by Flarna** [comment]
The catch-all variant is needed as Process is an EventEmitter and therefore it's possible and allowed to install and emit any event. In my application I face the issue that events 'newListener' and 'removeListener' inherited from base class were missing resulting in transpile errors. Sure, we could add these two events also here but still this results in an artificial limitation.
Honestly speaking I wonder why the catch-all from base-class is not used by typescript here.

Regarding the parameters of emit: For the special variants the parameters are in the end needed, and the catch-all has optional arguments.

My PR here tries just to fix some issues I have seen in my application using latest typing. Honestly speaking I don't understand why all these special variants were added as without catch-all they API is violated and by adding it the type-safety is (mostly) gone.

**Comment by sandersn** [comment]
@Flarna Typescript doesn't reuse overloads from the base class. So you have to repeat all overloads that you want in each derived class. 

I haven't thought deeply about this limitation, although others may have. I couldn't find an existing issue on Microsoft/TypeScript with a proposal.

**Comment by Flarna** [comment]
@mdebruijne: You are right, it makes sense to add only 'newListener' and 'removeListener' and remove the catch-all. I was confused regarding what can be done and what should be done. If someone has really the need to (miss)use Process with other event types it's still possible by casting to EventEmitter. Will do the change later. 

@sandersn: Yes, seems to be similar as in C++ but C++ has using to pull in overloads from base class instead repeating it.

**Comment by mdebruijne** [comment]
@Flarna
Thanks for the update. Like you already mentioned in the comment in your patch; the newListener and removeListener events belong to the EventEmitter Class. You should define them in the EventEmitter Class so all instances of EventEmitter, including Process, can use these typings. Please maintain code consistency by defining one event per line.

**Comment by Flarna** [comment]
@mdebruijne did some more copy/paster to split newListener/removeListener.
I have not added them to the EventEmitter class bacause it adds no type safety there - Typescript automatically chooses the catch-all if you use a non matching listener.
Besides that adding it in the base class is of no help for other derived classes as typescript is not looking into the base class for overload resolution as mentioned above.
So to my understanding it would be needed to copy/paste these lines to all other locations where EventEmitters are specialized. Not sure if this is really the way to go.

**Comment by mdebruijne** [comment]
@Flarna 
You are correct. Adding newListener and removeListener events to the EventEmitter Class isn't really useful due to the current limitation.

@sandersn 
Do you want to discuss this with the Microsoft/TypeScript team? The ability to inherit overloads (DRY) seems like a good addition to TypeScript.

**Comment by sandersn** [comment]
@mdebruijne @Flarna Do you think this is ready to go once Travis succeeds?

**Comment by sandersn** [comment]
(Travis didn't succeed, but timed out with no [new] failures, so I'd call that good enough.)

**Comment by Flarna** [comment]
Besides avoiding some copy/paste I added overloads for listen to cover the issue reported by @glasser with `listen()` discussed at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16705#issuecomment-308272510.

**Comment by mdebruijne** [comment]
Good stuff @Flarna. Please note there are ways to bypass type checking when adding event listeners and therefore it is not possible to guarantee that process.listeners returns an array of functions with the correct types. That being said, it's good to have them for convenience and this behavior is probably what most people expect from process.listeners.

**Review by mdebruijne — APPROVED** [review]

**Comment by sandersn** [comment]
Thanks, @Flarna, for your diligent work on this one.

**Pull request merged**
