### PR TITLE
[crypto-js] Revert most of #43932

### PR DESCRIPTION
**Pull request by mymindstorm**
This reverts commit 844962b6f6bfd3d9bbb377a914d28ae1a17b0eb2 (#43932)

#43932 broke my builds and some others (https://github.com/brix/crypto-js/issues/279). `libWordArray` does not exist in crypto-js's source and was intentionally different from `WordArray` and should not have been changed.

cc @QuentinFombaron

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A

### CODE REVIEW

**Comment by mymindstorm** [comment]
@sheetalkamat ?

**Comment by sheetalkamat** [comment]
This was closed and reopened to run travis . Its still waiting on review from  @misak113 @maximlysenko

**Comment by QuentinFombaron** [comment]
Hello @mymindstorm, 

> `libWordArray` does not exist in crypto-js's source and was intentionally different from `WordArray` and should not have been changed.

Can you explain why, please?

**Comment by maximlysenko** [comment]
Hi, @mymindstorm, @QuentinFombaron! I'm confirming that this should be merged. `CryptoJS.lib.WordArray.random` indeed returns LibWordArray, please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43047. 
@QuentinFombaron, you can check this by running actual JavaScript.

**Review by maximlysenko — APPROVED** [review]

**Comment by QuentinFombaron** [comment]
Alright @maximlysenko thank you, what about the return type in CryptoJS documentation [here](https://github.com/brix/crypto-js/blob/31d00127a7c87066c51abe56e7b8be3a32141cae/crypto-js.js#L349)? Because my Lint is crying when returned type is `LibWordArray`...

**Comment by mymindstorm** [comment]
@QuentinFombaron can you give an example? I can add it to the teats and try to fix it.

**Comment by mymindstorm** [comment]
Ready to merge

**Comment by AlttiRi** [comment]
> what about the return type in CryptoJS documentation here?

You should look at the type signature, not just at its name.
See my report: https://github.com/brix/crypto-js/issues/279

crypto-js's `LibWordArray` === `lib.WordArray` of original CryptoJS.

**Pull request merged**
