### PR TITLE
Fix AuthConfig & RestartPolicy typings (@types/dockerode)

### PR DESCRIPTION
**Pull request by acburdine**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/apocas/dockerode#pull-from-private-repos](https://github.com/apocas/dockerode#pull-from-private-repos)

### CODE REVIEW

**Comment by acburdine** [comment]
A note for reviewers: I'm not 100% sure if the contents of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61741/commits/9bd5edfc6142abf4b2ecac6cecedbc1e281f28ef technically constitute a breaking change. This *does* remove the RestartPolicy type name, but given that there were duplicate interface names in the typings already, I'm not sure if the type was ever valid to begin with?

The type that showed up for me by default in my IDE was the HostConfigRestartPolicy (maybe because it was the first one defined?), so it might make sense to just have that one be left as "RestartPolicy" for backwards compatibility.

**Comment by Seikho** [comment]
Two interfaces sharing the same name would merge as long as they have no conflicting properties.
I don't think this can be fixed without a breaking change as you'd be removing bad properties from one of the `RestartPolicy` properties.

**Review by Seikho — APPROVED** [review]

**Comment by acburdine** [comment]
> I don't think this can be fixed without a breaking change as you'd be removing bad properties from one of the RestartPolicy properties.

hmm, ok. I may try and submit a few more changes to this then, that way if there are any other breaking changes I can get them done in one go.

**Review by sandersn — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
I think @typescript-bot got confused so I'm approving again.

**Comment by P4sca1** [comment]
> m, ok. I may try and submit a few more changes to this then, that way if there are any other breaking changes I can get them done in one go.

Has this been done yet?

**Pull request closed without merging**
