### PR TITLE
feat: export rdf-ext term as classes they are

### PR DESCRIPTION
**Pull request by tpluscode**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/rdf-ext/rdf-ext/tree/master/lib>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by tpluscode** [comment]
@peterblazejewicz @elibarzilay could you please explain why this failed? Same happened to me for #55676

**Comment by peterblazejewicz** [comment]
oh, DT under 4.5 is a proofing ground, so it failed due to recent changes to language definitions:
https://github.com/microsoft/TypeScript/pull/45843
you can (eventually) try local override to see if that fixed your PR CI tests
sorry for the pita

**Review by peterblazejewicz — APPROVED** [review]

**Comment by tpluscode** [comment]
Why did this affect my two PRs and not some of others created recently?

**Comment by tpluscode** [comment]
Ready to merge 

Sent from Nine
________________________________

**Pull request merged**
