### PR TITLE
Add node-progress definition

### PR DESCRIPTION
**Pull request by sebastian-lenz**
node-progress is a simple module to create progress bars with node:
https://github.com/tj/node-progress

### CODE REVIEW

**Comment by horiuchi** [comment]
@sebastian-lenz Thank you for your contribution.
But please rename to `progress/progress.d.ts`, because npm registry name is [progress](https://www.npmjs.com/package/progress).

**Comment by sebastian-lenz** [comment]
Gosh, should have known that guide :wink:

**Comment by sebastian-lenz** [comment]
Did it, could you check again?

**Comment by horiuchi** [comment]
@sebastian-lenz Thanks mate!
Sorry late... :crying_cat_face:

**Pull request merged**
