### PR TITLE
Update Clownface to v1.0

### PR DESCRIPTION
**Pull request by tpluscode**
Introduces latest code changes and also renames the exported interfaces, which I wanted to for some time

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/zazuko/clownface/pull/39
  - https://github.com/zazuko/clownface/pull/41
  - https://github.com/zazuko/clownface/pull/43
  - [diff with previous release](https://github.com/zazuko/clownface/compare/v0.12.3...v1.0.0)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by tpluscode** [comment]
> 🔔 @tpluscode — you're the only owner, but it would still be good if you find someone to [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46393/files) in the next few days, otherwise a maintainer will look at it. (And if you do find someone, maybe even recruit them to be a second owner to make future changes easier...)

@thewilkybarkid ?

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by peterblazejewicz** [comment]
@tpluscode  Tomasz, can be merged

**Comment by tpluscode** [comment]
Ready to merge

**Comment by tpluscode** [comment]
dunno why I missed the bot comment

**Pull request merged**
