### PR TITLE
[atlassian-connect-js] Add overloads for AP.resize and AP.history.getState

### PR DESCRIPTION
**Pull request by Halu89**
AP.resize with no parameters is not documented anywhere, but we use it in our codebase and it works great (in dynamic content macros for instance).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - [History API](https://developer.atlassian.com/cloud/confluence/jsapi/history/)
  - [Dialog sizes](https://developer.atlassian.com/cloud/confluence/modules/dialog/)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/atlassian-connect-js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4e27c2fcaab333615069f3148c4b413db7e2c4fa
</p>

**Review by tobias-theobald — APPROVED** [review]
Gotta love Atlassian undocumented APIs. Thanks for adding these!

I have experimentally verified these APIs and don't think there's a risk of backwards-incompatible changes.

**Comment by cbriand-RY** [comment]
Ready to merge

**Comment by Halu89** [comment]
Ready to merge

**Pull request merged**
