### PR TITLE
[parse] Adding `original` optional field to `BeforeSaveRequest` and overloading response.error

### PR DESCRIPTION
**Pull request by saulogt**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/parse-community/parse-server/blob/401cc357e5afe63f35a03754595311a192716969/src/triggers.js#L151
https://github.com/parse-community/parse-server/blob/70ad9e9ffd281180ea93abd4493726938d375d7d/src/Routers/FunctionsRouter.js#L90

### CODE REVIEW

**Comment by saulogt** [comment]
@dpoetzsch @flavionegrao @wesleygrimes

**Review by wesleygrimes — COMMENTED** [review]
Can you take a crack at adding a test for this?

Thanks!

**Comment by saulogt** [comment]
Test added

**Review by wesleygrimes — APPROVED** [review]
This looks great! Thanks @saulogt

**Comment by andy-ms** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Pull request merged**
