### PR TITLE
[nodegit] Fix Blame-related methods

### PR DESCRIPTION
**Pull request by julien-c**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by pvigier — APPROVED** [review]

**Review by tniessen — APPROVED** [review]

**Comment by dolanmiu** [comment]
can you show me the documentation for this change? AFAIK, they are not methods

**Review by dolanmiu — CHANGES_REQUESTED** [review]
https://www.nodegit.org/api/blame_hunk/

It shows that is an instance variable

**Comment by julien-c** [comment]
@dolanmiu You can check by running this repl: https://repl.it/@julienc1/nodegit-playground#index.js

I'll open a PR to fix the documentation in nodegit, but in fact, this was already reported in 2017: https://github.com/nodegit/nodegit/issues/1235

**Review by dolanmiu — APPROVED** [review]

**Comment by julien-c** [comment]
Ready to merge

**Pull request merged**
