### PR TITLE
[@types/hapi] Add null to Request.params and Request.payload

### PR DESCRIPTION
**Pull request by ozylog**
based on hapi.js request object on actual module that params and payload are possible to be null when there is no value applied against it.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/hapijs/hapi/blob/master/lib/request.js#L49
https://github.com/hapijs/hapi/blob/master/lib/request.js#L52

### CODE REVIEW

**Comment by SimonSchick** [comment]
Are you sure params can actually be `null`? I have worked with hapi quiet a lot and have never seen that happening, can you please clarify?

**Comment by SimonSchick** [comment]
Just asking because, by default params will always be an empty object, can you please demonstrate a scenario when it would not be populated?

**Comment by SimonSchick** [comment]
If you cannot provide a scenario for it being null I'd request @paulvanbrenk to revert this merge.

**Comment by ozylog** [comment]
Hi @SimonSchick 

here is my scenario. https://github.com/ozylog/test

**Comment by SimonSchick** [comment]
@ozylog It might be worth creating a separate interface then?
It seems kinda annoying that we have to add null assertions everywhere just for this niche use case.

**Comment by jhsimms** [comment]
@SimonSchick Agreed.  I missed this PR originally, but forcing null checks for 99.9% of the code where the object is guaranteed not to be null is poor form.  Creating a separate interface for the niche use case seems ideal. I think we should revert this merge and provide the separate interface.  Btw, @ozylog I do appreciate overall appreciate the effort to improve the typings.  I just think a separate interface for this case would have been ideal.

**Comment by ozylog** [comment]
all good @SimonSchick @jhsimms. thanks for your feedback.

**Pull request merged**
