### PR TITLE
bluebird: fixed inference issue with try/attempt

### PR DESCRIPTION
**Pull request by brandf**
The source of the issue is described here:
http://stackoverflow.com/questions/35182445/unsure-why-casting-is-required-in-this-typescript-code-my-derp-or-language-lim

I ran into a type inference issue with try/attempt (possibly a tsc bug/limitation) that is fixed by having the type definitions use a union type rather than two overloads with different return types.

I added two test cases for each try and attempt on both versions of bluebird.

The first test case demonstrates that tsc can't correctly infer the generic parameter for try/accept if we use overloads, and without this fix you get the following error:

```
bluebird/bluebird-1.0-tests.ts(511,1): error TS2322: Type 'Promise<Foo | Promise<Foo>>' is not assignable to type 'Promise<Foo>'.
    Type 'Foo | Promise<Foo>' is not assignable to type 'Foo'.
        Type 'Promise<Foo>' is not assignable to type 'Foo'.
        Property 'foo' is missing in type 'Promise<Foo>'.
```

The second test case demonstrates that even if you tell it the generic parameter the type inference doesn't pick up on the fact that () => T|Promise<T> would satisfy one overload or the other.  Without this fix you would get the following error:

```
bluebird/bluebird-1.0-tests.ts(514,28): error TS2345: Argument of type '() => Foo | Promise<Foo>' is not assignable to parameter of type '() => Foo'.
    Type 'Foo | Promise<Foo>' is not assignable to type 'Foo'.
    Type 'Promise<Foo>' is not assignable to type 'Foo'.
```

The fix to the type definitions is to use a union return type, which causes both tests to pass and better reflects the intent of the bluebird js api.

### CODE REVIEW

**Comment by brandf** [comment]
One thing worth noting is that union types were introduces in typescript 1.4.  I'm relatively new to DefinitelyTyped, so I'm not sure what the policy is around versioning and backwards compatibility.  If there is a policy where union types are prohibited from these type definitions, that's understandable.

**Comment by brandf** [comment]
I want to make sure I'm following the correct testing procedure.  I ran:

    tsc bluebird/bluebird-1.0-tests.ts &&  tsc bluebird/bluebird-tests.ts

If this isn't all I need to run, please inform.

**Comment by brandf** [comment]
It looks like the associated typescript issue I filed was closed as a dupe of another issue.

https://github.com/Microsoft/TypeScript/issues/1805

The discussion in that issue indicated that they have no plans to make the inference work for this type of overload, and that they recommend using union types as I have done in this PR.

**Comment by brandf** [comment]
It occured to me that I may have miss-interpreted what the 1.0 in bluebird-1.0.ts means.  Is this the bluebird version or the tsc version (I was assuming bluebird version)?  

If the latter I should pull my change out of the 1.0 files.  

If the former, then what I have should be fine as long as you folks are ok with these type definitions being for Typescript 1.4+.  If that's an issue I would recommend working with 'typings' to have the definition manager support having different definitions for different Typescript compilers.

**Comment by vvakame** [comment]
This repo supported latest tsc only. (it is 1.7.5 now.)
This PR LGTM. please resolve conflict.

**Comment by brandf** [comment]
Sorry for the delay on updating, will resolve conflict tonight.  It looks like someone checked in a similar change (although not to 1.0 version, and no tests).  I'm going to resolve vs. that and still push for mine on top if it since I think the tests are important at demonstrating why using the union type is important.

**Comment by brandf** [comment]
@vvakame should be good now.  conflicts resolved and tests pass.

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
