### PR TITLE
Add onCancel() support to Bluebird

### PR DESCRIPTION
**Pull request by ntrrgc**
See http://bluebirdjs.com/docs/api/cancellation.html

### CODE REVIEW

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by ntrrgc** [comment]
Where is the conflict? I can't see it.

**Comment by vvakame** [comment]
add_oncancel___support_to_bluebird_by_ntrrgc_ _pull_request__8603_ _definitelytyped_definitelytyped
please merge master/HEAD into your branch

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
