### PR TITLE
`react`: add `fetchPriority` to `LinkHTMLAttributes`

### PR DESCRIPTION
**Pull request by OliverJAsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/fetchPriority
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5d2cd2a28f6525374a562903fef2e56800dba810
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thanks but this is only shipped in the `canary` and `experimental` release channels. Stable versions need to use the lowercase `fetchpriority`

**Comment by OliverJAsh** [comment]
> Thanks but this is only shipped in the `canary` and `experimental` release channels.

Does that mean we should wait until it's stable? Or is there a way I can define a property as experimental?

**Review by eps1lon — APPROVED** [review]
Thanks

**Pull request merged**
