### PR TITLE
chore: add types for netlify-auth-providers

### PR DESCRIPTION
**Pull request by drazisil**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by drazisil** [comment]
I hand-crafted this, sorry. The library is quite old and archived. It does, ever still work, when following the directions from https://docs.netlify.com/visitor-access/oauth-provider-tokens/#site-usage-example, so I thought I'd share what I made to make Typescript happy. I welcome feedback. :heart:

**Comment by drazisil** [comment]
> Config files to check:
> 
>     * [`netlify-auth-providers/tsconfig.json`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55536/files/bae72bd5c51ba3d29f384bc6bc4eac1884aa6576#diff-f7c5574b5511bcce1f734bbb17e2827b5c15c25bee27c77b3a56331e4e05715d): not [the expected form](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-tsconfigjson) (check: `compilerOptions.target`)

Bot, respectfully I don't know what you are not liking. I followed the config docs, as well as added all other entries requested by the CI runs.

@RyanCavanaugh , since the bot updated the tags, and CI passed, did it miss an update on the comment, or is there still an error? (I'm not asking for a CR, the bot said to poke you if I suspected something wrong with it.

**Comment by elibarzilay** [comment]
@drazisil: The bot was indeed not ignoring an `es6` target...  That's fixed now.

**Comment by drazisil** [comment]
Is this the correct status, @elibarzilay ? I can not merge.

**Comment by drazisil** [comment]
Ready to merge

**Pull request merged**
