### PR TITLE
node: console.timeLog

### PR DESCRIPTION
**Pull request by dex4er**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/console.html#console_console_timelog_label_data

### CODE REVIEW

**Review by BrunoScheufler — APPROVED** [review]

**Review by r3nya — COMMENTED** [review]
What about tests? ;)

**Comment by dex4er** [comment]
@r3nya we didn't had tests for `time` and `timeEnd` but I could add it if you think that it is time to include them all.

**Comment by r3nya** [comment]
@dex4er got it! I mentioned tests just in case. :)

**Review by r3nya — APPROVED** [review]

**Comment by dex4er** [comment]
@r3nya ouch I don't see any tests for `console` module. I think the tests should go in separate PR.

**Comment by r3nya** [comment]
@dex4er agreed!

**Review by ThomasdenH — CHANGES_REQUESTED** [review]
The first parameter is optional according to the documentation. Can you change it?

**Comment by dex4er** [comment]
@ThomasdenH Syntactically you're right, but if you run without parameters then you'll get

`(node:33277) Warning: No such label 'undefined' for console.timeLog()`

so I think documentation is wrong and it doesn't make any sense to not put any arguments and TS should detect it.

**Comment by ThomasdenH** [comment]
I see. Super.

**Review by ThomasdenH — APPROVED** [review]

**Comment by dex4er** [comment]
@ThomasdenH 

Ah I see that:

```
> console.time('undefined')
undefined
> console.timeLog()
undefined: 1359.977ms
```

but still it looks like very bad code to me...

**Comment by ThomasdenH** [comment]
> 
> 
> @ThomasdenH
> 
> Ah I see that:
> 
> ```
> > console.time('undefined')
> undefined
> > console.timeLog()
> undefined: 1359.977ms
> ```
> 
> but still it looks like very bad code to me...

Yeah, exactly. This looks like an unintented artifact of using String() more than anything else.

**Pull request merged**
