### PR TITLE
[react-dom] add exports from client to index

### PR DESCRIPTION
**Pull request by jordanbtucker**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64112
  - https://github.com/facebook/react/blob/c5b9375767e2c4102d7e5559d383523736f1c902/packages/react-dom/index.js#L15
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/react-dom/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 01fd852ccd603418b2ff57c0e04e78854484a8a2
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
These are deprecated and warn at runtime. We generally don't add typings for things that cause runtime warnings. 

Only usage from the `/client` entrypoint is intended at this point.

**Comment by jordanbtucker** [comment]
> These are deprecated and warn at runtime. We generally don't add typings for things that cause runtime warnings.
> 
> Only usage from the `/client` entrypoint is intended at this point.

Thanks for the info. The problem is that using `createRoot` and `hydrateRoot` from the package index is only deprecated if you're not using UMD. The UMD build of react-dom exposes these two functions to the index without displaying a warning. What is the best path to allow users to have correct UMD typings?

**Comment by eps1lon** [comment]
How do you do UMD typings today?

**Comment by jordanbtucker** [comment]
The types for react-dom are already [UMD compatible](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-plugin-d-ts.html) because they declare a `namespace` with the same name as the UMD global `ReactDOM`. The issue is really with react-dom because the exports of the root entry point (`index.js`) do not match the members of the UMD global `ReactDOM`. However, I don't think UMD users should be punished for this.

**Comment by eps1lon** [comment]
The problem is that they will be removed anyway at which point exporting them from the index really would be wrong. So I'm asking how typings for UMD work today where the UMD entrypoint contains different exports than other entrypoints.

You may interpret this as punishing UMD users but so are users of the other entrypoints since they get incorrect auto-imports.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Please address concerns presented by the reviewers

**Pull request closed without merging**
