### PR TITLE
readme: install 2.x > 2.0

### PR DESCRIPTION
**Pull request by aretecode**
- [x] readme

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@andy-ms anything here.... we probably want to reference the latest version of TypeScript, but keeping that up to date may be a pain later.

**Comment by andy-ms** [comment]
Actually, this should be `npm run lint package-name`, to ensure you detect lint failures too.

**Comment by franklinyu** [comment]
Should be closed by #17998?

**Comment by andy-ms** [comment]
@franklinyu Yep, thanks.

**Comment by aretecode** [comment]
@andy-ms ah that makes more sense https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17998/files#diff-04c6e90faac2675aa89e2176d2eec7d8R99 I was not sure what linting meant in this context in relation to the 1 line change, now I do :-)

**Pull request closed without merging**
