### PR TITLE
[file-saver] Improve typedefs

### PR DESCRIPTION
**Pull request by ChrisMBarr**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint file-saver` and `tsc`

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/eligrey/FileSaver.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

----

This PR simply re-writes the typedefs in a bit simpler way, marks the 2nd & 3rd params on `saveAs` optional as they are in the original source, and adds `saveAs` to the `Window` interface.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by DanielRosenwasser** [comment]
I think the way you want to model this is as something that can be imported, but that also augments globals. So something like

```ts
export = FileSaver;

declare namespace FileSaver {
   export declare function saveAs(data: Blob, filename?: string, disableAutoBOM?: boolean): void;
}

declare global {
    declare const saveAs: typeof FileSaver.saveAs

    interface Window {
        declare const saveAs: typeof FileSaver.saveAs
    }
}
```

**Comment by chrismbarr** [comment]
Good suggestion thanks - changes have been made.

**Comment by RyanCavanaugh** [comment]
@chrismbarr Please fix the failures indicated in the Travis CI log.

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
