### PR TITLE
Mongoose:  fix wrong type of shardKey in schema option

### PR DESCRIPTION
**Pull request by HughKu**
Please fill in this template.

- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
   https://mongoosejs.com/docs/guide.html#shardKey
https://github.com/Automattic/mongoose/blob/7b92e8dde624ca8b73edd0bdec1d09597ba287ac/test/shard.test.js#L26
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---
Schema option field **shardkey** is actually an `object` type, NOT `boolean`.
Mongoose official documentation is not correct on this subject, as suggested in recent [issue](https://github.com/Automattic/mongoose/issues/7643)

### CODE REVIEW

**Comment by jendrikw** [comment]
Thanks a lot!

**Review by jendrikw — APPROVED** [review]

**Review by orblazer — APPROVED** [review]

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Could you please add a test? This will help future changes from accidentally regressing your change. Thanks!

**Comment by HughKu** [comment]
> Could you please add a test? This will help future changes from accidentally regressing your change. Thanks!

@uniqueiniquity Thanks for your reminder, I've added a test for this change 5c71a0e748e70e8a863ae85f5749e4740d9320a1.

**Review by emmanuelgautier — APPROVED** [review]

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
