### PR TITLE
pixi.js: Provides its own types

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This will deprecate `@types/pixi.js` in favor of just `pixi.js`. CC @clark-stevenson

### CODE REVIEW

**Comment by clark-stevenson** [comment]
@a-tarasyuk 

You are a Scholar 🙇

**Review by clark-stevenson — APPROVED** [review]
Awesome

**Comment by clark-stevenson** [comment]
@a-tarasyuk 

Just a second!  I felt I knew what you said when I first read it. 

I caught `not-needed-packages` . 

What does this mean for people who are still using V4?  Those people require @types/pixi.js,  will that still be available to them?

**Comment by sandersn** [comment]
Those stay on npm. Only version 5 is tagged as deprecated. But you can’t update 4.x anymore after deleting it from DT.

**Review by sandersn — CHANGES_REQUESTED** [review]
Sounds like the owner still has questions.

**Comment by clark-stevenson** [comment]
Thanks @sandersn in that case this looks good to me!

**Review by clark-stevenson — APPROVED** [review]
Happy to proceed

**Review by sandersn — APPROVED** [review]

**Pull request merged**
