### PR TITLE
[phoenix] Improve type definitions

### PR DESCRIPTION
**Pull request by princemaple**
- Improved types in general, added more detailed types to socket constructor options
- Removed method declarations that are marked as private in the source
- Fixed Ajax - added static to all methods
- Fixed inaccurate / incomplete types
- Added missing instance methods on Presence

### CODE REVIEW

**Comment by princemaple** [comment]
Hi @mciastek @John-Goff 
appreciate it if you could take a look

**Review by sandersn — CHANGES_REQUESTED** [review]
What's here looks good, but I'm not comfortable merging a change to package I don't know without better support from the linter. Can you try removing all the tslint overrides and see how much work that would require to fix?

**Comment by princemaple** [comment]
Hi @sandersn thanks for the review. I've turned on many of the flags and changed the definition and the test accordingly. Please take another look if you get a chance, thanks!

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
@princemaple I went ahead and merged this change. If you have time, you could make a follow-up PR that removes the overrides in the tslint config and just uses the defaults that come from dtslint.json. That will probably lead to lots of minor changes in the types.

**Pull request merged**
