### PR TITLE
Fix d3.dsv callback parameter types

### PR DESCRIPTION
**Pull request by drarmstr**

### CODE REVIEW

**Comment by gustavderdrache** [comment]
This is good! I just have one question (and I admit it's kind of a nitpick). In this block:
```
        get(callback?: (err: XMLHttpRequest, data: T[]) => void): DsvXhr<T>;
        post(data?: any, callback?: (err: any, data: T[]) => void): DsvXhr<T>;
        post(callback: (err: XMLHttpRequest, data: T[]) => void): DsvXhr<T>;

        send(method: string, data?: any, callback?: (err: any, data: T[]) => void): DsvXhr<T>;
        send(method: string, callback: (err: any, data: T[]) => void): DsvXhr<T>;
```

Is it intentional that only some of the `err` parameters are `XMLHttpRequest`?

**Comment by drarmstr** [comment]
Nope, thanks for fixing.

**Comment by gustavderdrache** [comment]
:+1: Very nice.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
