### PR TITLE
Allow custom Request and Response types

### PR DESCRIPTION
**Pull request by karaxuna**
Improvement to existing type definition.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Could you explain reason? I don't understand purpose of this PR.

**Comment by karaxuna** [comment]
@TonyPythoneer I have middleware which extends `req` object:

```javascript
function (req, res, next) {
    req.foo = 'bar';
}
```
I want req object to have foo property everywhere in the app without explicitly indicating custom interface. So:

```javascript
interface ICustomRequest extends express.Request {
    foo: string;
}

// instead of doing this every time:
app.get('/route1', function (req: ICustomRequest, res, next) {
    // use req.foo
});

app.get('/route2', function (req: ICustomRequest, res, next) {
    // use req.foo
});

// I do this:
app = express<ICustomRequest, express.Response>();

app.get('/route1', function (req, res, next) {
    // use req.foo
});

app.get('/route2', function (req, res, next) {
    // use req.foo
});
```

**Comment by TonyPythoneer** [comment]
I think it's your private requirement. It doesn't benefit this type definition.

**Comment by karaxuna** [comment]
@TonyPythoneer See this link: https://github.com/expressjs/multer/issues/343

**Comment by TonyPythoneer** [comment]
I see. But I haven't this requirement, you are on your own.

**Comment by minestarks** [comment]
@karaxuna Thanks for the contribution. I see the motivation for the change, unfortunately it would break everyone who uses the current non-generic interfaces in their code today. Indeed the tests are failing in this PR.  It also makes the code more verbose for people that don't have this custom request type requirement. The expressjs/multer#343 solution seems more targeted. 

Since this PR has been inactive for a while I plan to close it out in a couple of days if no further comments or changes.

**Comment by paulvanbrenk** [comment]
Closing since no changes in the past couple of days.

**Pull request closed without merging**
