### PR TITLE
Adding definitions for Microsoft Visual Studio Services.

### PR DESCRIPTION
**Pull request by serkan-inci**
This is type definitions for Microsoft Visual Studio Services. The details of the project can be found in: http://www.visualstudio.com/integrate/extensions/overview

We haven't decided yet how to approach testing since this a combination of multiple definition files which is mostly used for performing a Rest Client call to different services. However, we'll come up with a strategy soon.

### CODE REVIEW

**Comment by vvakame** [comment]
*vss/vss.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/vss
  * http://bower.io/search/?q=vss
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (vss/vss-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@serkan-inci thank you for your contributions.
please fix travis-ci failed.
@basarat

**Comment by basarat** [comment]
@serkan-inci Reasons for test failures:

* The reference paths need to be relative to location in *this* repo (so prefix a `../`)  : https://github.com/serkan-inci/DefinitelyTyped/blob/master/vss/vss.d.ts#L5-L7 

* The header format wants this to be a url instead of an email address : https://github.com/serkan-inci/DefinitelyTyped/blob/master/vss/vss.d.ts#L3

Again thanks for the PR :rose:

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
