### PR TITLE
Add removeClippedSubviews To SectionList & FlatList

### PR DESCRIPTION
**Pull request by huhuanming**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react-native/blob/264d67c424841660874bcf11ad686aea57fe7a44/Libraries/Lists/SectionList.js>><<https://github.com/facebook/react-native/blob/c7d37a208aed7889ca2ff4f82c6405ed56d9f1f8/Libraries/Lists/FlatList.js>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
@alloy @gyzerok

**Comment by huhuanming** [comment]
@alloy @gyzerok

**Comment by alloy** [comment]
Like I mentioned on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16634, we should get rid of the duplication between the two. Do you want to pick that up instead?

**Comment by huhuanming** [comment]
I think so and will add VirtualizedList in recent days.
However, this is temporary.

**Comment by alloy** [comment]
Fair enough, that works for me 👍

**Comment by huhuanming** [comment]
thx

**Pull request merged**
