### PR TITLE
Additions to CodeMirror definitions

### PR DESCRIPTION
**Pull request by koddsson**
I ran `prettier` in order to get to a consistent codestyle and then I did my changes in seperate commits. It might be easier to read this PR commit by commit because of that.

- Add `modeOption` property:
  - https://github.com/codemirror/CodeMirror/blob/master/src/model/Doc.js#L37
- Add `indentSelection` function:
  - https://github.com/codemirror/CodeMirror/blob/master/src/edit/methods.js#L97
- Add defintions for `codemirror/mode/meta`
  - https://github.com/codemirror/CodeMirror/blob/master/mode/meta.js

I tried running the tests or linting but I just get errors? Not sure if I'm doing anything wrong there.

### CODE REVIEW

**Comment by koddsson** [comment]
Seems like test files should have a `-tests.ts` postfix and that's why the comment isn't green? 🤔 

Ref: https://github.com/DefinitelyTyped/DefinitelyTyped#editing-tests-on-an-existing-package

I would work on fixing that but I don't want to do too much in a single PR.

**Comment by koddsson** [comment]
_Maybe_, this will make the comment go green?

**Comment by koddsson** [comment]
Rebased and force pushed in hopes to get @typescript-bot to pick up on that the tests are green now.

**Comment by koddsson** [comment]
@RyanCavanaugh am I doing something wrong here 🤔

**Review by sandersn — APPROVED** [review]
Normally I like to let other contributors sign off, but it's been a while and this change looks pretty safe to me.

**Pull request merged**
