### PR TITLE
Add delegate for parse

### PR DESCRIPTION
**Pull request by AngryPowman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by teppeis** [comment]
lgtm @RReverser

**Comment by RReverser** [comment]
I guess `node` should not be `any`, but rather `ESTree.Node`?

**Comment by weswigham** [comment]
@RReverser do you want to see that change made?

**Comment by RReverser** [comment]
@weswigham Yeah. Also, I'd prefer to see an explicit type definition for `meta` as defined in docs at https://esprima.readthedocs.io/en/latest/syntactic-analysis.html#syntax-delegate - it's a simple addition as there are just few fields.

**Comment by weswigham** [comment]
@RReverser if you make a "request changes" code review, the bot will ping the author asking for the changes, then ping you once they're made for an updated approval.

**Comment by RReverser** [comment]
@weswigham ah right, thanks!

**Review by RReverser — CHANGES_REQUESTED** [review]
Please provide explicit types for delegate arguments as noted above.

**Comment by AngryPowman** [comment]
@RReverser Thanks to your corrections, `node` has been change to a explicit type with `ESTree.Node`. BTW, `meta` has no type definition right now and it should depend another file, I will fix it on another PR next time.

**Comment by RReverser** [comment]
> has no type definition right now and it should depend another file

Well, yeah, that's the problem I'm talking about - it should have type definition that matches docs.

**Comment by andy-ms** [comment]
I think that can be left to a future PR.

**Pull request merged**
