### PR TITLE
react-jsonschema-form: now we can use 'disabled' on the Form

### PR DESCRIPTION
**Pull request by ccancellieri**
Hi,
 I've to disable the entire form (ref. to the changes here -> https://github.com/mozilla-services/react-jsonschema-form/pull/1056)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mozilla-services/react-jsonschema-form/pull/1056
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by iplus26** [comment]
I think you'd better add your name to the end of contributors to keep the order, as suggested in [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#edit-an-existing-package).

The code looks fine to me.

**Review by iplus26 — CHANGES_REQUESTED** [review]
I think you'd better add your name to the end of contributors to keep the order, as suggested in [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#edit-an-existing-package).

The code looks fine to me.

**Comment by iplus26** [comment]
My apology -- I found that the change is merged in another PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31977, thus this one could be closed.

**Comment by ccancellieri** [comment]
Not a problem this is a duplicated pull req, feel free to close

**Pull request closed without merging**
