### PR TITLE
openlayers: Cluster  and Source constructor and Layer.setZIndex function

### PR DESCRIPTION
**Pull request by cwmrowe**
Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by cwmrowe** [comment]
@sandersn it appears that @woutergd has been inactive for a quite some time. Would you be able to review this PR please?

**Comment by woutergd** [comment]
Hi @cwmrowe, it has been vacation time so that was my cause of inactivity ;) . Changes are looking good, so merging is fine to me.

**Comment by cwmrowe** [comment]
@woutergd great! How do we merge it then?

**Comment by cwmrowe** [comment]
Hi @woutergd, I naively assumed that this would automatically update the npm @types/openlayers package, but it has not. How do we update that too?

**Comment by woutergd** [comment]
Hi @cwmrowe, to answer both of your questions, the merge is done by specific people over here who administrate the whole repository (as you can see here above). For the second, if I am right this update should be automatically, I don't know at which time and how often those jobs run and on which time to update the packages so maybe this is delayed a day due to the late merge last night?

**Comment by cwmrowe** [comment]
Thanks @woutergd, I must learn to be more patient :-)

**Comment by cwmrowe** [comment]
Hi @woutergd so these changes still have not propagated to @types/openlayers on NPM. I have a hunch that I need to created a pull request to move code into the ```types-2.0``` branch, but I can't find that documented anywhere so can't be sure.

**Pull request merged**
