### PR TITLE
[tap@15] Fix invalid type for pattern in Assertions.Match

### PR DESCRIPTION
**Pull request by zkldi**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.npmjs.com/package/tcompare>>

Assertions.Match accepts any parameter, not string | regexp | { [k: any]: regexp }

note: The Git commit history for this PR is a bit weird - I'm not experienced enough with git to know exactly what caused it. If this causes issues, let me know and i'll smush it all into one commit or something.

### CODE REVIEW

**Comment by zkldi** [comment]
> 
> 
> 🔔 @zkldi — you're the only owner, but it would still be good if you find someone to [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52887/files) in the next few days, otherwise a maintainer will look at it. (And if you do find someone, maybe even recruit them to be a second owner to make future changes easier...)

What they said - If anyone wants to be added as a second maintainer just let me know in this thread.

**Comment by zkldi** [comment]
Hi - this is still a pretty important fix and is only two characters or so. I don't know or have anyone who would be interested in maintaining these types aswell as I, either.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by zkldi** [comment]
Ready to merge

**Comment by zkldi** [comment]
@RyanCavanaugh Thanks for approving the merge!

**Pull request merged**
