### PR TITLE
lodash: changed _.isObject() method

### PR DESCRIPTION
**Pull request by chrootsu**
https://lodash.com/docs#isObject
https://lodash.com/docs#_ (description of the chainable wrapper)

### CODE REVIEW

**Comment by vvakame** [comment]
@chrootsu please resolve conflict.

**Comment by chrootsu** [comment]
@vvakame done.

**Comment by vvakame** [comment]
@chrootsu oops. please resolve conflict again...

**Comment by chrootsu** [comment]
@vvakame done. )

**Comment by vvakame** [comment]
@chrootsu thanks mate!

**Pull request merged**
