### PR TITLE
removed ko.utils functions that are not part of minified knockout.js and added addOrRemoveItem() issue#4192

### PR DESCRIPTION
**Pull request by mdahamiwal**

### CODE REVIEW

**Comment by vvakame** [comment]
*knockout/knockout.d.ts*

to authors(@borisyankov @Igorbek @moonpyk). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by SergioMorchon** [comment]
`ko.utils.domData` contains: `clear`, `get` and `set` functions.

**Comment by mdahamiwal** [comment]
I couldn't find get or set on ko.utils.domData, or removeNode on ko.utils.domNodeDisposal. Can you make sure you are referring to the right minified file. http://knockoutjs.com/downloads/knockout-3.3.0.js 
.On a similar issue https://github.com/knockout/knockout/issues/670 SteveSanderson from knockout team has confirmed that they have exposed limited APIs and they don't want to expose such functions that are subject to change or can have backward compatibility issues in later versions. So, i guess it make sense to only include in typed file functions that are available in minified files. Any thoughts?

**Comment by mdahamiwal** [comment]
@SergioMorchon, any update on this? Can you approve the pull request if it looks good.?

**Comment by SergioMorchon** [comment]
It think that it could be provisionally ok, but we have to keep in mind this Knockout issue: https://github.com/knockout/knockout/issues/1858
The next release is almost here, and maybe with changes here.

**Comment by mbest** [comment]
> Maybe we could ask the to the Knockout team which is the API or how we can get it.

We don't have an "official" API, but anything that's exported using `ko.export...` or is specifically made public using a quoted property name should be fine. It's also pretty safe to just examine the objects in the `ko` namespace to find which methods aren't minified.

**Comment by bdoss** [comment]
This is something I also noticed as I made the switch from the debug knockout build to production build and noticed that certain methods defined in the TypeScript definition file for ko.utils no longer appeared to be exposed (specifically ko.utils.stringStartsWith is what I ran into).

The major addition to the TypeScript definition file for v3.4.0 that immediately stands out to me is the addition of the ko.onError callback.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
