### PR TITLE
Relay Runtime: remove myself from code owners

### PR DESCRIPTION
**Pull request by mrtnzlml**
I no longer have time for code reviews.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. MutationTypes
1. RangeOperations
1. MutationHandlers
1. VIEWER_ID

<details>
<summary>as well as these 9 other properties...</summary>
<p>VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c041af6391bafe94e6a602a862b47bffca81c2ec
</p>

**Review by Stephen2 — APPROVED** [review]
Sorry to see you go, and thanks for your time :+1:

**Review by rbuckton — APPROVED** [review]

**Comment by renanmav** [comment]
Ready to merge

**Comment by alloy** [comment]
@mrtnzlml Thanks for your assistance!

**Pull request merged**
