### PR TITLE
[react-native-input-spinner] Remove, bundles its own types

### PR DESCRIPTION
**Pull request by BendingBender**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by mkrishnan-codes — CHANGES_REQUESTED** [review]
Why all the files need to be removed

**Comment by BendingBender** [comment]
They don't really _need_ to be removed. It's just that the library now bundles the types directly (https://github.com/marcocesarato/react-native-input-spinner/blob/master/src/index.d.ts) and the `@types/react-native-input-spinner` package thus becomes obsolete. The expectation is that the types bundled with the lib will be generally more up-to-date than the ones on DefinitelyTyped. If you feel that this will not be the case, I'll just close this PR without merging it.

**Comment by BendingBender** [comment]
@mkrishnan-codes Is this ok now?

**Comment by BendingBender** [comment]
@mkrishnan-codes ping

**Comment by BendingBender** [comment]
@mkrishnan-codes ping

**Comment by BendingBender** [comment]
@mkrishnan-codes ping

**Review by andrewbranch — APPROVED** [review]

**Comment by BendingBender** [comment]
Ready to merge

**Pull request merged**
