### PR TITLE
[React Native] add tslint

### PR DESCRIPTION
**Pull request by gyzerok**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by gyzerok** [comment]
@johnnyreilly is it possible to have some help with merging here? :)

**Comment by minestarks** [comment]
Thanks for the changes. Why was it necessary to disable linting on those two lines?

**Comment by gyzerok** [comment]
@minestarks, was just unsure if it makes sense to split them into different lines. Do you think it would be better?

**Comment by minestarks** [comment]
@gyzerok I find it's better to not fight the linter :) Code is easier to read without the ```disable-next-line``` comments.

**Comment by gyzerok** [comment]
@minestarks sorry for quite a long delay. I removed `disable-next-line` where possible. However at one place it would introduce unnecessary breaking change so I guess we can live with it.

**Comment by alloy** [comment]
Only now found this, I added linting in this PR #15105. Let me know if there’s any improvements you had made that are missing.

**Comment by paulvanbrenk** [comment]
Looks like #15105 includes these fixes (and makes the merge terrible). Closing for now, please open a new PR if you need additional changes.

**Pull request closed without merging**
