### PR TITLE
@event-calendar/core: Add missing EventInput field "resourceId"

### PR DESCRIPTION
**Pull request by syncsynchalt**
# Description

This was missed in the initial types creation.  The library allows some singular field names (e.g. `resourceId`) which it can convert to plurals (e.g. `resourceIds`) when normalizing input.

~~I also added the library author as an owner so he can have visibility on these changes in the future if he'd like.~~

# Checklist
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [library documentation](https://github.com/vkurko/calendar?tab=readme-ov-file#parsing-event-from-a-plain-object)
- [x] (N/A) If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/event-calendar__core/event-calendar__core-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e40a1e2c271464dbbad9ffd44eb2b0f5a668b900
</p>

**Review by andrewbranch — CHANGES_REQUESTED** [review]
> I also added the library author as an owner so he can have visibility on these changes in the future if he'd like.

Thanks for the thought, but we only want folks to add themselves. It can potentially create a lot of pings, so you shouldn’t be able to sign someone else up for that without their consent.

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by syncsynchalt** [comment]
Ready to merge

**Pull request merged**
