### PR TITLE
@types/archiver - finalize is not a promise

### PR DESCRIPTION
**Pull request by sabrehagen**
Docs state @return void: https://github.com/archiverjs/node-archiver/blob/0bc4872daf94055ba3fafd958d6769711fa39652/lib/core.js#L131

Code also shows nothing is returned from the function i.e. undefined/void.

Please fill in this template.
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/archiverjs/node-archiver/blob/0bc4872daf94055ba3fafd958d6769711fa39652/lib/core.js#L131

### CODE REVIEW

**Review by Crevil — APPROVED** [review]
The tests should be changed to reflect this as well. 
Thanks for fixing it! 🙌

**Comment by dolanmiu** [comment]
Could you fix the tests also?

Thanks

**Comment by sabrehagen** [comment]
Tests fixed!

**Review by dolanmiu — APPROVED** [review]

**Comment by jkossis** [comment]
Agreed, finalize does indeed return a promise in its current state:

https://github.com/archiverjs/node-archiver/blob/master/lib/core.js#L759

When could we expect this to be resolved?

**Pull request merged**
