### PR TITLE
Recharts Typing Update

### PR DESCRIPTION
**Pull request by ZheyangSong**
+ Many interfaces are partially shaped or wrongly shaped.
+ Replace tab with 2-spaces

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/recharts/recharts **<= reshaped the typings for almost all files under `cartesian`, `chart`, `component`, `polar` and `shape`**.
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@ZheyangSong Please fix the failures indicated in the Travis CI log.

**Comment by ZheyangSong** [comment]
@RyanCavanaugh Just FYI, the current `definitelytyped-header-parser` doesn't support TS versions after 2.4... Which will break the linting, if the library's tsconfig.json has new features from 2.5+. This currently happens to this `recharts` library. Please suggest the right way to resolve it. The `tsconfig` uses `strictFunctionTypes` from 2.6 and dtslint cannot understand this option....

**Comment by andy-ms** [comment]
@ZheyangSong You probably need to refresh your `node_modules`.

**Comment by ZheyangSong** [comment]
@andy-ms worked like charm. thanks.

**Comment by ZheyangSong** [comment]
@RyanCavanaugh @andy-ms Is there npm script running test on specific library? It takes a long time running test on all definition files. Thanks.

**Comment by royxue** [comment]
@ZheyangSong use `npm run lint package-name`

**Comment by ZheyangSong** [comment]
@royxue yeah, that runs tslint. But it doesn't seem to run the TSX test files.

**Comment by ZheyangSong** [comment]
@mthmulders @rapmue @royxue Please spend time reviewing this PR. I hope it not break many things. This change is pretty much direct translation of the up-to-date flow definitions (which seem to be ill-defined) from the source repo. The PR bares backward-compatibility in mind to certain scale... Thanks, if you can share your time and opinion.

**Comment by ZheyangSong** [comment]
@RyanCavanaugh CI is fixed.

**Pull request merged**
