### PR TITLE
yeoman-generator: Replace registerTransformStream with queueTransformStream

### PR DESCRIPTION
**Pull request by melody-universe**
[As of 5.0.0](https://github.com/yeoman/generator/releases/tag/v5.0.0), `Generator.registerTransformStream` has been replaced with `Generator.queueTransformStream`.

**Note:** For backwards-compatibility, I've marked `Generator.registerTransformStream` as deprecated, but the function is completely removed from `yeoman-generator`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yeoman/generator/releases/tag/v5.0.0
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (N/A)

### CODE REVIEW

**Comment by manuth** [comment]
Personally, I'd rather delete the `registerTransformStream`-method than marking it as deprecated.
Marking it as deprecated suggests, that the method somhow is accessible (for instance by registering a mixin).

Not sure what others might think about it, though

**Comment by melody-universe** [comment]
> Personally, I'd rather delete the `registerTransformStream`-method than marking it as deprecated.
> Marking it as deprecated suggests, that the method somhow is accessible (for instance by registering a mixin).

I'd tend to agree with you. I've removed it instead, but can easily undo that if anyone has any strong counterpoint.

**Review by neurolag — APPROVED** [review]
In that case, this PR looks absolutely fine to me
Thanks for your patience

**Comment by melody-universe** [comment]
Ready to merge

**Pull request merged**
