### PR TITLE
Add a responsive propertie to datatable Settings

### PR DESCRIPTION
**Pull request by LandixSistemas**
Add a responsive propertie to datatable Settings

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by pragmatrix — CHANGES_REQUESTED** [review]
This PR's diff contains way too many indenting changes. Can you minimize the diff so that only the relevant changes are shown?

**Comment by CNBoland** [comment]
According to the documentation on the [responsive](https://datatables.net/reference/option/responsive) property, it can be either a `boolean` or a [Responsive Options](https://datatables.net/reference/option/#responsive) object. This PR defines it as a `boolean`, which I think is acceptable for now. A better definition may be `boolean | object` for those using Responsive Options until a type definition for the [DataTables Responsive](https://datatables.net/extensions/responsive/) extension is created.

**Comment by CNBoland** [comment]
@pragmatrix The last revision ([0889963](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24981/commits/0889963c99e0a833d8402562641b23c68ef58f43)) looks good to me.

**Comment by pragmatrix** [comment]
@CNBoland The diff looks fine, but merging this PR would obscure the history of large parts of the file, because the first two commits still change a lot of indenting and back. If this is ok, go ahead merging it. But if not, @LandixSistemas should remove the first two commits or squash all of them together.

**Pull request merged**
