### PR TITLE
Add missing definition

### PR DESCRIPTION
**Pull request by bersling**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

In angular you can either write `directive('myDirective', ['$http', function($http) {...}])`, which is minification safe, but it's also possible to write `directive('myDirective', function($http) {...})` which might not be minification safe, but valid angular nonetheless.

### CODE REVIEW

**Comment by thorn0** [comment]
Please revert this change. There was already a perfectly working strongly typed definition for this case:
```ts
directive(name: string, directiveFactory: IDirectiveFactory): IModule;
```
If it didn't work for you, it just means that your factory function wasn't of type `IDirectiveFactory` for some reason.

**Comment by bersling** [comment]
the problem with the IDirectiveFactory was that it expected an array, but it's also possible to use the last argument of the array (i.e. the actual function) directly. If I just revert the change there is a feature of angular that is not supported by the type definitions. What could be done is to extend the definition of `IDirectiveFactory` I guess?

**Comment by thorn0** [comment]
Sorry, but there was no such problem. Here is the definition of `IDirectiveFactory`, it's not an array.
```ts
    interface IDirectiveFactory {
        (...args: any[]): IDirective;
    }
```

**Comment by bersling** [comment]
Hm, but this works
```
angular.module('myApp').directive('myDirective', ['$http', function($http) {}]);
```
while this doesn't work
```
angular.module('myApp').directive('myDirective', function($http) {});
```
With the second example I get the following error message:

> Error:(22, 50) TS2345: Argument of type '($http: any) => void' is not assignable to parameter of type 'any[]'.
 Property 'push' is missing in type '($http: any) => void'.

To me this sounds like an array is expected?

**Comment by thorn0** [comment]
Of course, it doesn't work. Because a directive factory should return a DDO, not void.

**Comment by thorn0** [comment]
For the error message to be less misleading, we could change the order of the method overloads.
```ts
        directive(name: string, inlineAnnotatedFunction: any[]): IModule;
        directive(name: string, directiveFactory: IDirectiveFactory): IModule;
```

**Comment by bersling** [comment]
Thanks for the hint with the return value. That was just a mockup, my real directives would be something like this.
```
  .directive('addDir', function(){
    return {
      restrict: 'AE',
      replace: 'true',
      scope: {
        addText: '@',
        extraClass: '@'
      },
      templateUrl: '/components/directives/add-button/add-button.html'
    };
  });
```
I found that the problem here was just that `true` should be actually a boolean and not a string. But it's really quite misleading with the error message :) I'll change it back then

**Comment by thorn0** [comment]
I've already submitted #11039 :)

**Comment by bersling** [comment]
perfect, thanks a lot for your help

**Pull request merged**
