### PR TITLE
Added type definition 2.0 version for electron-process

### PR DESCRIPTION
**Pull request by WillStreeter**
Please fill in this template.
- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by WillStreeter** [comment]
Updating electron-process for @types/ usage per request

**Comment by vvakame** [comment]
@DefinitelyTyped/contributors can anyone review this PR?

**Comment by paulvanbrenk** [comment]
@WillStreeter Can you put all the exported classes in the index.d.ts, this matches the pattern used in most other typings and makes it easier to reason about.

**Comment by andy-ms** [comment]
If you still want to add these types, please make a new PR targeting the `master` branch and using `npm run new-package electron-process`.
To echo what @paulvanbrenk said, a file `electron-process/main.d.ts` should only exist if people will do `import * as main from "electron-process/main"`.
If people will instead import from `"electron-process"` directly, then you should directly write all types in `electron-process/index.d.ts`.

**Pull request closed without merging**
