### PR TITLE
Adding the 'resources' property to AlexaObject

### PR DESCRIPTION
**Pull request by theBenForce**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by blforce** [comment]
Can someone take a look at this? It's a really small change.

Thanks

_Sent from my Samsung SM-N920T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pascalwhoop** [comment]
👍 looks good to me

**Comment by pascalwhoop** [comment]
But I can't merge and also I'm only on mobile so I'm not sure how to direct dt bot to du stuff I want

**Comment by blforce** [comment]
Thanks @pascalwhoop

**Pull request merged**
