### PR TITLE
Update to 2.3.5

### PR DESCRIPTION
**Pull request by samael65535**
Update to 2.3.5

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
Can the original authors approve this?

@borisyankov / @mdocter / @MrBigDog2U

**Comment by mdocter** [comment]
Would like to, but can't say I have the time. 
I originally donated this definition, but it was never my intention to keep it up to date and be the owner.
But now I'm stuck in some approval flow I never signed up for, but I can't seem to get out.
My opinion on these pull requests are as good as any others. I'm not more as an expert than any other oss dev.

**Comment by panuhorsmalahti** [comment]
I'd imagine you can get out of the approval loop by removing your name from the state-machine.d.ts
 file.

**Comment by mdocter** [comment]
That would be an option. Although, I'm the original author. Removing my name would be similar to writing a book and put somebody-else's name on it. Not sure how they reviewed changes before, but they are probably better of by forming some kind of editor/reviewer group. For now I'll just ignore the messages.

**Comment by vvakame** [comment]
*state-machine/state-machine.d.ts*

to authors (@borisyankov @mdocter @MrBigDog2U). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
@mdocter Do not you want to receive notification?

**Comment by mhegazy** [comment]
@samael65535, can you address the merge conflicts. thanks.

**Comment by samael65535** [comment]
@mhegazy https://github.com/samael65535/DefinitelyTyped/commit/2f65577fc761a54a88c622e1e0264c6f2e3ae9b2

**Comment by mhegazy** [comment]
not sure i understand the reply. there are still merge conflicts in this PR and can not be merged.

**Comment by mhegazy** [comment]
Can you please fix the failing Travis CI tests and update the PR!

**Comment by samael65535** [comment]
OK

**Pull request merged**
