### PR TITLE
Deprecate types for packages that provide their own types

### PR DESCRIPTION
**Pull request by BendingBender**
If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by ltetzlaff — APPROVED** [review]

**Comment by ltetzlaff** [comment]
@sindresorhus allowing type definitions in his repositories? I'm astonished! 🤩😋

**Comment by BendingBender** [comment]
He does. This is the reason for all the removals.

**Comment by BendingBender** [comment]
He now even has a repo just for type definitions: https://github.com/sindresorhus/type-fest

**Comment by sindresorhus** [comment]
Hehe. DT is about to get a lot smaller, thanks to @BendingBender 🙌

**Review by LinusU — APPROVED** [review]
🔥 🔥 🔥

**Review by SimonSchick — APPROVED** [review]

**Pull request merged**
