### PR TITLE
[react-redux] Fix #33690: Require explicit version of @types/hoist-non-react-statics

### LINKED ISSUE #33690: [@types/react-redux] 'hoist-non-react-statics' has no exported member 'NonReactStatics'
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@jamesreggio @JounQin

updating from `@types/react-redux 7.0.1` to `@types/react-redux 7.0.2` gives the following error:

```
'/node_modules/hoist-non-react-statics' has no exported member 'NonReactStatics'.

47 import { NonReactStatics } from 'hoist-non-react-statics';
```
seems like it was introduced here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/8b1beff944f6c7bf913b6fcee31fb5f7129064a7

### PR DESCRIPTION
**Pull request by jamesreggio**
**This PR fixes a regression in a popular package (react-redux). Please review and merge ASAP.**

---

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] ~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~ Unnecessary.
- [X] ~Increase the version number in the header if appropriate.~ Unnecessary.
- [X] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~ Unnecessary.

---

See convoluted explanation here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-474043897

### CODE REVIEW

**Comment by weswigham** [comment]
@jamesreggio you'll need to resync and retrigger the build on this PR.

**Comment by sandersn** [comment]
I did that a few minutes ago. Looks like it's green now.

**Comment by weswigham** [comment]
Neat. Why wait for the bot when I could merge now then~

**Comment by jamesreggio** [comment]
YOLO.

**Comment by wolfy1339** [comment]
This doesn't fix the problem

**Pull request merged**
