### PR TITLE
react-calendar: Update props

### PR DESCRIPTION
**Pull request by danah-kim**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.npmjs.com/package/react-calendar>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
See comment from @ypresto

**Comment by sweetmilkys** [comment]
> You have included unrelated merge commit of i18n-js. Please remove it by rebase? 😉

oh, thank you.

**Review by andrewbranch — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by sweetmilkys** [comment]
Ready to merge

**Comment by Joeao** [comment]
Unfortunately since this PR I have a type error occurring. [OnChangeDateCallback](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52871/commits/955995db69de580f0da25c1c72e75d4787304560#diff-afbc145a811be316dbd20bbd2c1c629f22689e684229729e84fc79979b043c3dL11) actually returns `(date: Date | Date[], event: ChangeEvent<HTMLInputElement>)`. Which is a cross between what's been added here and what existed before.

The [Project Documentation](https://github.com/wojtekmaj/react-calendar#props) gives an example of a single `Date` being returned, but if `returnValue={"range"}` is set, `Date[]` will be returned.

**Comment by Pringels** [comment]
@Joeao I've addressed that problem with my PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53574

I will resolve the conflicts today and hopefully get it merged asap

**Pull request merged**
