### PR TITLE
Updated AmCharts definition

### PR DESCRIPTION
**Pull request by peteralbert**

### CODE REVIEW

**Comment by vvakame** [comment]
*amcharts/AmCharts.d.ts*

to author(@aleksey-bykov). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by peteralbert** [comment]
@aleksey-bykov / @vvakame 
Being new to GitHub/OS, quick question: is there anything in need to do for the PR to get accepted/merged? Am I missing something?

Thanks

**Comment by aleksey-bykov** [comment]
please go ahead and merge it

**Comment by aleksey-bykov** [comment]
(+1)

**Comment by aleksey-bykov** [comment]
:+1:

**Comment by peteralbert** [comment]
@aleksey-bykov How can I do this? I get a message "This branch is up-to-date with the base branch
Only those with write access to this repository can merge pull requests."

**Comment by aleksey-bykov** [comment]
I believe this branch needs to be rebased against master and in order to get up-to-date. After it I will be able to accept the pull request. Sorry for not being able to do it immediately.

**Comment by aleksey-bykov** [comment]
https://help.github.com/articles/merging-a-pull-request/

**Comment by vvakame** [comment]
It merged! thanks all.
pull request are merged by repository owner or collaborator.

**Pull request merged**
