### PR TITLE
[passport-jwt] Improve typings by adding required parameters, remove non-existant function, add docs, fix Request type

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://gist.github.com/QuentinLemCode/40552804fee8d73a9e2831ae8ed58956
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

The changes are the following : 
- In the StrategyOptions, it is required to have secretOrKey or secretOrKeyProvider defined (but not both). The types now reflect that.
- In the StrategyOptions, there is a parameter to have request in callback, this now change the type signature of the 'verify' callback function accordingly.
- The Request type, precedently used, is now any. As the lib can be used by multiple type of http server, the user can now define the proper type of Request object to handle.
- In the StrategyOptions, the "algorithms" type is now "Algorithm" from jsonwebtoken library. Reflecting the real usage of the javascript code : https://github.com/mikenicholson/passport-jwt/blob/master/lib/verify_jwt.js
- Added documentation
- Remove ExtractJwt.FromAuthHeader that seems to not exist in the library : https://github.com/mikenicholson/passport-jwt/blob/master/lib/extract_jwt.js

Source : https://github.com/mikenicholson/passport-jwt/tree/master/lib

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/passport-jwt/index.d.ts
1. types/passport-jwt/passport-jwt-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 397af69823a5e61db356d4523746cb0b243dd0ef
</p>

**Review by k725 — APPROVED** [review]

**Comment by soulchild** [comment]
I'm having a hard time following changes to DefinitelyTyped stuff. I came here because upgrading `@types/passport-jwt` broke my `jwtFromRequest` function. The generic `Request` type introduced by the latest release does not know about the `cookies` property that has been injected by Express's `cookie-parser` middleware. 

This PR [seems to change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68102/files#diff-b71c8d6ec401ffed807cc36d147e6eda88a0a5eb1a17175172ce9004026d8b79R108) the request type to `any` instead? Wouldn't it be better to make the type generic so people can pass it down if they want to:

```ts
new JWTStrategy<MyFrameworksRequestType>({
  jwtFromRequest: (req) => req.fancyPropertyFromMyFramework.jwt
})
```

IMHO, the generic type should be optional and default to `Express.Request` to keep backwards-compatibility. Or am I misunderstanding things completely? 🙈

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by QuentinLemCode** [comment]
Ready to merge

**Comment by QuentinLemCode** [comment]
> I'm not sure this is the right place to report an issue but there may be a problem with this latest change?
> 
> This snippet used to build on `@types/passport-jwt": "^3.0.13`:
> 
> ```js
> const options = {
>   jwtFromRequest: ExtractJwt.fromExtractors([
>     ExtractJwt.fromAuthHeaderWithScheme('jwt'),
>     ExtractJwt.fromAuthHeaderWithScheme('Bearer'),
>   ]),
>   secretOrKey: config.get<string>('auth.secret'),
>   passReqToCallback: true,
> };
> 
> const jwtStrategy = new JwtStrategy(options, verifyCallback);
> ```
> 
> After upgrading to `@types/passport-jwt": "^4.0.1` I am getting the following error:
> 
> ```
> Argument of type '{ jwtFromRequest: JwtFromRequestFunction<any>; secretOrKey: string; passReqToCallback: boolean; }' is not assignable to parameter of type 'StrategyOptionsWithRequest'.
>   Type '{ jwtFromRequest: JwtFromRequestFunction<any>; secretOrKey: string; passReqToCallback: boolean; }' is not assignable to type 'Omit<WithSecretOrKey, "secretOrKeyProvider"> & { passReqToCallback: true; }'.
>     Type '{ jwtFromRequest: JwtFromRequestFunction<any>; secretOrKey: string; passReqToCallback: boolean; }' is not assignable to type '{ passReqToCallback: true; }'.
>       Types of property 'passReqToCallback' are incompatible.
>         Type 'boolean' is not assignable to type 'true'.
> ```
> 
> The documentation indicates:
> 
> > passReqToCallback: If true the request will be passed to the verify callback. i.e. verify(request, jwt_payload, done_callback).
> 
> Am I missing something? Why can't I set `passReqToCallback: true` anymore?
> 
> Currently running `"passport-jwt": "^4.0.1"`. Thanks for your insights!

Hello
Can you try to add the type to the option object ? 
`const options: StrategyOptions = {`

**Comment by gzurbach** [comment]
Yep, that was it! Thanks for your help, really appreciate it 🙂

**Pull request merged**
