### PR TITLE
Add optional rawResponse to OperationType in relay-runtime

### PR DESCRIPTION
**Pull request by Stephen2**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition **N/A**

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/relay/releases/tag/v6.0.0 see @raw_response_type
- N/A If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- N/A If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration **N/A**

### CODE REVIEW

**Comment by Stephen2** [comment]
Context is a wrapper around `environment.mock.resolveMostRecentOperation`:

```
export const resolveMostRecentOperation = <T extends OperationType>(
  environment: MockEnvironment,
  modifier?: (generatedData: T["rawResponse"]) => T["rawResponse"],
): Promise<{ readonly data: T["rawResponse"]; readonly operation: OperationDescriptor }> =>
```

We were using `T["response"]` but now I want to use `T["rawResponse"]` but it isn't in the type declaration for `OperationType`, but the type outputs as:

```
export type HomeScreen_HomeScreenQuery = {
    readonly response: HomeScreen_HomeScreenQueryResponse;
    readonly variables: HomeScreen_HomeScreenQueryVariables;
    readonly rawResponse: HomeScreen_HomeScreenQueryRawResponse;
};
```

**Comment by alloy** [comment]
Can you add a test that demonstrates how this would be used?

**Comment by Stephen2** [comment]
> Can you add a test that demonstrates how this would be used?

Do you mean write a test in `relay-runtime-tests.tsx`?  I tried understanding that, but couldn't.  Not sure how to write test code for types

**Comment by alloy** [comment]
A passing test is one that simply doesn’t lead to any type errors. You can also make assertions against returned types or what usage should lead to type errors, which are specified as comments. Iirc the docs for these are in dts-lint, but you can also find them by search this repo for `// Assert`.

**Comment by Stephen2** [comment]
Argghh, I keep going round in circles with this.  I just don't see what to test.  I could see how this could be a test in `relay-compiler` where if the `@raw_response_type` directive exists, it populates `rawResponse`

But I can't see how it's a test here, or how to go about writing that test :(

If you have any direction you can give, it's the only way I'll be able to move forward.
----

What I can point you at is:
https://github.com/facebook/relay/blob/ed1c3628c3100b1fc34be4545d81f4b3494cf33c/packages/relay-runtime/util/RelayRuntimeTypes.js

```
export type OperationType = {|
  // TODO(T33395812) Make this an open object type
  +variables: Variables,
  +response: mixed,
  +rawResponse?: {...},
|};
```

**Comment by alloy** [comment]
@Stephen2 Can you provide a snippet of app code that shows exactly how you’d use this IRL?

**Comment by Stephen2** [comment]
@alloy sure man :)  It's a bit long winded, and very contrived.  The point is that we like to create a test file per page, not per component.  So we need access to the child components data to test against.

This is a bit long, bear with me:

`Component.tsx`:
```
import React, { useContext } from "react";
import { createFragmentContainer, graphql, QueryRenderer, ReactRelayContext } from "react-relay";
import { Component_bar } from "./__generated__/Component_bar.graphql";
import { Component_FooQuery } from "./__generated__/Component_FooQuery.graphql";

interface BarComponentProps {
  readonly bar: Component_bar;
}

const BarComponent = createFragmentContainer(
  ({ bar: { baz } }: BarComponentProps) => <h1 data-testid="baz">{baz}</h1>,
  {
    bar: graphql`
      fragment Component_bar on Bar {
        baz
      }
    `,
  }
)

export function FooPage() {
  const context = useContext(ReactRelayContext);

  if (!context) {
    throw new Error("Need a context, dummy!");
  }

  return (
    <QueryRenderer<Component_FooQuery>
      environment={context.environment}
      query={graphql`
        query Component_FooQuery @raw_response_type {
          __typename
          foo
          bar {
            ...Component_bar
          }
        }
      `}
      variables={{}}
      render={({ props }) => {
        if (props) {
          return (
            <>
              <h1 data-testid="foo">{props.foo}</h1>
              <BarComponent bar={props.bar} />
            </>
          );
        }

        return null;
      }}
    />
  );
}
```

`Component.test.tsx`:
```
import { MockEnvironment, MockPayloadGenerator, createMockEnvironment } from "relay-test-utils";
import { render } from "@testing-library/react";
import { ReactRelayContext } from "react-relay";
import React from "react";
import { FooPage } from "./Component";
import { GraphQLResponse, OperationDescriptor, OperationType } from "relay-runtime";
import { Component_FooQuery as FooQuery } from "./__generated__/Component_FooQuery.graphql";

const resolveMostRecentOperationHelper = <T extends OperationType>(
  environment: MockEnvironment,
): Promise<{ readonly data: T["rawResponse"]; readonly operation: OperationDescriptor }> =>
  new Promise(resolve => {
    environment.mock.resolveMostRecentOperation((operation: OperationDescriptor) => {
      const mockPayload: GraphQLResponse = MockPayloadGenerator.generate(operation);

      resolve({
        data: mockPayload.data as T["rawResponse"],
        operation
      });

      return mockPayload;
    });
  });

test("That foo page looks right", async () => {
  const environment = createMockEnvironment();

  const { getByTestId } = render(
    <ReactRelayContext.Provider value={{ environment }}>
      <FooPage />
    </ReactRelayContext.Provider>,
  );

  const { data: { foo, bar: { baz } }} = await resolveMostRecentOperationHelper<FooQuery>(environment);

  const fooNode = getByTestId("foo");
  expect(fooNode.textContent).toBe(foo);

  const bazNode = getByTestId("baz");
  expect(bazNode.textContent).toBe(baz);
});
```

**Comment by elibarzilay** [comment]
@Stephen2, @alloy, unclear to me whether this is ready or you want to add a test?

**Comment by Stephen2** [comment]
@elibarzilay ready from my POV as it mirrors the Flow types, and the types work in example code + production code.

I'm new to this repo though, and newish to Relay so would prefer a 2nd opinion from someone experienced.

**Comment by elibarzilay** [comment]
OK, re-ping @alloy then...

**Review by weswigham — APPROVED** [review]
This is a simple enough change and there's a reference to it in the original library's source, so this has waited long enough for more review, IMO.

**Comment by Stephen2** [comment]
Thanks all :)

**Comment by alloy** [comment]
The reason I wanted a test for this is because the actual library (relay-runtime) isn’t the only part that matters, but also the 3rd-party plugin for relay-compiler that generates the TS typings.

Anyways, we can cover it when we touch it again in the future 👍

**Pull request merged**
