### PR TITLE
Remove joi

### PR DESCRIPTION
**Pull request by lenovouser**
Depends on https://github.com/microsoft/definitelytyped-tools/pull/194

[**`joi/lib/index.d.ts`**](https://github.com/sideway/joi/blob/master/lib/index.d.ts)

### CODE REVIEW

**Review by katsanva — APPROVED** [review]
Please fix the CI

**Comment by lenovouser** [comment]
@katsanva 

> Depends on microsoft/DefinitelyTyped-tools#194

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bell ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bell@latest/))
was missing the following properties:
1. providers
1. oauth
1. providers
1. oauth
## crumb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/crumb@latest/))
was missing the following properties:
1. plugin
1. plugin
## dynogels ([<kbd>unpkg</kbd>](https://unpkg.com/browse/dynogels@latest/))
was missing the following properties:
1. documentClient
1. model
## frisby ([<kbd>unpkg</kbd>](https://unpkg.com/browse/frisby@latest/))
was missing the following properties:
1. delete
## h2o2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/h2o2@latest/))
was missing the following properties:
1. pkg
## hapi ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi@latest/))
was missing the following properties:
1. server
## hapi__basic ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__basic@latest/))
was missing the following properties:
1. plugin
1. plugin
1. plugin
## hapi__bell ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__bell@latest/))
was missing the following properties:
1. providers
1. oauth
1. providers
1. oauth
## hapi__cookie ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__cookie@latest/))
was missing the following properties:
1. pkg
1. pkg
## hapi__crumb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__crumb@latest/))
was missing the following properties:
1. plugin
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 782cf3a274c74dcc9c98165a4bea9d58bb16cd38
</p>

**Comment by lenovouser** [comment]
@weswigham quick general question, the Hapi organization moved from `hapi` to their own namespace `@hapi` like a year ago already. Back then modules were renamed like the following: `hapi → @hapi/hapi`, `catbox → @hapi/catbox` etc.  I am thinking of also removing all the types for the old modules as they definitely will not receive any updates in the future (and have not for the past year) and thus maintaining will at some point get kind of hard. But I think the current policies only allow for removal if the module adds types themselves, not when the module is "deprecated" or switches their name to be more precise. What are your thoughts on this?

**Comment by weswigham** [comment]
I think just leaving them as-is is pretty close to archiving them, and still leaves them available to receive bugfixes/updates from the TS side, should a problem arise with the types. Plus, they'll keep getting integration tested as their dependants change over them, even if they won't change.

**Pull request merged**
