### PR TITLE
[@types/detox] Adding Android attributes to getAttributes()

### PR DESCRIPTION
**Pull request by princefishthrower**
As the title states, this pull request brings in the Android types for getAttributes. I saw the iOS ones were there but not the Android ones. As far as I can tell, I've followed the [detox docs for `getAttributes`](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#getAttributes) exactly.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#getAttributes
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by princefishthrower** [comment]
Oh, one other thing, I noticed a mysterious `layer` property on the iOS attribute types which _isn't_ in the documentation - so it should either be added to the documentation for Detox, or removed from the typings I suppose.

**Review by grgr-dkrk — CHANGES_REQUESTED** [review]
Thank you!
This added type is a union of objects, so I think we need to add test code to see if it is correctly inferred by the type-guard.

**Comment by princefishthrower** [comment]
@grgr-dkrk - thanks for pointing that out. I've added a few tests - one for iOS and one for Android to test for that union. Is that what you had in mind?

**Review by grgr-dkrk — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
