### PR TITLE
Update Knockout.js definitions to 3.4.0

### PR DESCRIPTION
**Pull request by lediur**
Made a diff between 3.2.0 and 3.4.0 and tried to include and cover all the changes in between that haven't already been made by previous contributors.

### CODE REVIEW

**Comment by slaneyrw** [comment]
Tests appear to be failing due to the knockout-deferred-updates typing.... but this is only supported for Knockout <= 3.3.0.  The functionality for deferred has been bought into 3.4.

Is it possible to remove the knockout-deferred-updates from the build process, or do we need to "pin" the knockout.d.ts at v 3.3.0

**Comment by Igorbek** [comment]
It looks that only `KnockoutStatic` being augmented with `tasks` has caused this test failure. @lediur could you remove that `tasks` from _knockout-deferred-updates_ (since it's been defined in knockout itself).

**Comment by lediur** [comment]
Looks like knockout-deferred-updates defines something on `tasks` that knockout 3.4 doesn't, so the build is still failing. I'd agree with @slaneyrw that we could limit deferred-updates to the 3.3 version.

**Comment by Igorbek** [comment]
Something bad happened with this PR - see the files diffs. Could you clean it up and merge properly.

**Comment by lediur** [comment]
I'm going to close this and create a new PR, hopefully that gets fixed.

**Pull request closed without merging**
