### PR TITLE
[highcharts] Add the scrollbar property to the xAxis and yAxis to optionally enable scrolling in charts

### PR DESCRIPTION
**Pull request by ryanewtaylor**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
   - _Note_: Running `npm run lint highcharts` generated the error `Object.entries is not a function` however this error was generated on the master branch as well. It was not introduced with this pull request. `tsc` generated no errors.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://api.highcharts.com/highstock/scrollbar
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
Can you please address the CI failures.

**Comment by ryanewtaylor** [comment]
@mhegazy I am attempting to replicate these failures on my local machine, however, whenever I run `npm run lint highcharts` I receive the following error.

```
$ npm run lint highcharts

> definitely-typed@0.0.1 lint C:\Dev\neip\DefinitelyTyped
> dtslint types "highcharts"

Object.entries is not a function
```

I receive the same error when running this command among other packages as well. It may be something with my environment. I have been unable to resolve this (local) issue in order to replicate the CI build failures locally. 

Any ideas for how I can resolve this dtslint issue?

**Comment by mhegazy** [comment]
The server is using a different version of tslint. @andy-ms how can we force it to use tslint@5.1?

**Comment by mhegazy** [comment]
for now, try adding `"no-object-literal-type-assertion:" false` in the tslint.json.

**Comment by ryanewtaylor** [comment]
@mhegazy adding `"no-object-literal-type-assertion:" false;` worked. Thanks for the assist.

**Comment by andy-ms** [comment]
@mhegazy Not sure why travis isn't using tslint 5.1. But we can fix this with Microsoft/dtslint#34. (Must merge to `master`, then merge `master` into `production`).

**Comment by ryanewtaylor** [comment]
@mhegazy are any further steps required to be able to merge this change into master? @dt-bot did not automatically @mention anyone listed in the definitions. Should I manually @mention them for review?

**Comment by ryanewtaylor** [comment]
@mhegazy, @andy-ms , @subash-a, I was wondering if there was any further action required on my part for this Pull Request.

**Comment by subash-a** [comment]
@ryanewtaylor I was looking through the changes and found that the documentation for highcharts says that the `scrollbar` option is only present on the `yAxis` property and not found on the `xAxis` can you confirm if both the axes have the option available because the changes seem to make them available on both the axes.

**Comment by ryanewtaylor** [comment]
@subash-a I saw the same thing in their online documentation. However, [the examples they give](https://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/yaxis/inverted-bar-scrollbar/) apply the scrollbar to the `xAxis` and I am using this in my own code as well.

Further the blog post introducing scrollable charts for any axis mentions `scrollbars are not limited to stock charts or Y axis. Using the highstock.js file, it can be applied to regular Highcharts axes too`, So, I suspect that the missing `scrollbar` options is a documentation error.

**Comment by ryanewtaylor** [comment]
I reported the possible documentation bug in highcharts/highcharts#6712

**Comment by ryanewtaylor** [comment]
Comments to highcharts/highcharts#6712, online examples, and my own testing would seem to confirm that the `xAxis` does contain a `scrollbar` property that is currently undocumented (a documentation bug). 

@subash-a @damianog @baltie @AlbertOzimek @DavidKDeutsch, are there any further actions required before this pull request can be merged?

**Pull request merged**
