### PR TITLE
add exports field to react-dom

### PR DESCRIPTION
**Pull request by otakustay**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. unstable_createPortal
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 54d4f7a71fe8a00129f053af7693d722bb6d75fa
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
This should probably be handled when publishing automatically. Could you provide more context about this change e.g. what about other packages? Did you discuss this with maintainers? etc.

**Comment by otakustay** [comment]
> This should probably be handled when publishing automatically. Could you provide more context about this change e.g. what about other packages? Did you discuss this with maintainers? etc.

According to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/57195#issuecomment-1001249562 , republish will not add `exports` map but `react` and `react-dom` exports multiple sub-entries like `react/jsx` or `react-dom/server`, theses need to be added manually

**Comment by eps1lon** [comment]
I'd be surprised if this needs to happen manually. The tests already throw if there are unused files. So if the infra already knows about used and unused files, why does it not add these automatically?

I'd be more comfortable if there would be a holistic approach that specifically lists actions we need to take.

**Comment by otakustay** [comment]
It seems neither of us know the result of a republish, how about we just change some simple text and make a republish to see what happens, if republish automatically adds `exports` field then we can safely close these PRs.

**Pull request closed without merging**
