### PR TITLE
Convert chai to module and chai plugins to augment the module

### PR DESCRIPTION
**Pull request by ghost**
We should test this out in some real-world chai users before merging.

### CODE REVIEW

**Comment by aozgaa** [comment]
@andy-ms Have we tested this with real-world users?

If any of the authors tried using types from this branch, please let us know if you experienced any breakages or improvements.

**Comment by andy-ms** [comment]
No, better wait until I test it out in some real repositories.

**Comment by CaselIT** [comment]
I haven't tried it, but chat-http looks ok
thanks andy

**Comment by kuzn-ilya** [comment]
chai-spies looks ok
thanks, Ilya

**Comment by mhegazy** [comment]
@andy-ms can you refresh the PR and address the merge conflicts

**Review by clementprevot — APPROVED** [review]

**Review by CaselIT — APPROVED** [review]
chai-http looks ok

**Review by kuzn-ilya — APPROVED** [review]

**Comment by sheetalkamat** [comment]
@andy-ms can you please resolve the merge conflicts and refresh the PR. thanks

**Comment by aozgaa** [comment]
Looks stale.

**Pull request closed without merging**
