### PR TITLE
Added typings for the CodeMirror showhint addon

### PR DESCRIPTION
**Pull request by jacqt**

### CODE REVIEW

**Comment by thasner** [comment]
:+1:

**Comment by vvakame** [comment]
*codemirror-showhint/codemirror-showhint.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/codemirror-showhint
  * http://bower.io/search/?q=codemirror-showhint
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (codemirror-showhint/codemirror-showhint-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
um? codemirror-showhint is not part of CodeMirror?

**Comment by thasner** [comment]
it's an add-on, yet it's distributed within the main CodeMirror repo.

notice how the `main` entry of `bower.json` doesn't include any of the add-on files https://github.com/codemirror/CodeMirror/blob/master/bower.json

my guess is that this new file should be in `codemirror/addon` (or `codemirror/showhint`)

**Comment by vvakame** [comment]
yep, `codemirror/showhint.d.ts` is good.

**Comment by jacqt** [comment]
Renamed the files as suggested

**Comment by vvakame** [comment]
@jacqt ok! :+1: thanks mate.

**Pull request merged**
