### PR TITLE
Remove deta types

### PR DESCRIPTION
**Pull request by kognise**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
LGTM!
@kognise thank you for your work on this!

**Review by domdomegg — APPROVED** [review]
deta 1.0.0 has built-in type definitions: https://www.npmjs.com/package/deta

**Review by peterblazejewicz — APPROVED** [review]

**Comment by kognise** [comment]
Ready to merge! Thanks :)

**Comment by kognise** [comment]
Ready to merge

**Pull request merged**
