### PR TITLE
[jest] fix  mocking of generic functions

### LINKED ISSUE #32901: jest: jest.fn, Mock, MockInstance, SpyInstance are not properly typed (requires breaking change)
### Breaking Change

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

 - Authors: @antoinebrault 

Just as a follow-up to our discussion (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32864#discussion_r254924337), I open this ticket, so I we can properly discuss the issue and track progress.

Currently the types mentioned in the title of this issue are all typed `Xyz<SomeReturnType, SomeParamArray>` rather than being typed `Xyz<SomeFunction>` which is the intention of the underlying jest API.

This introduces redundancy and error potential.

IMO it would be better to template the mentioned types with a single parameter extending from a generic function type and derive return type and argument type where needed (via `ReturnType<F>`, `ArgsType<F>`). See the sample code in the PR referenced above.

**Update**: As @antoinebrault  has correctly pointed out this still requires migration from 23.x (other than I first assumed), as the return type `<T>` will have to be replaced by the function type `<F>`. Still the fact that this fixes mocking of functions with generics is a strong argument in favour of this change (see my next comment).

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: fixes #32901
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by jerico-dev** [comment]
Could one of the maintainers please review this PR or explicitly reject it if it's not appropriate?

@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @geovanisouza92 @aldentaylor

**Comment by jerico-dev** [comment]
FYI: I'll not invest any work in fixing conflicts unless one of the maintainers shows interest in this change.

**Comment by ExE-Boss** [comment]
Could you provide a description of what this PR is supposed to achieve in the PR summary?

**Comment by jerico-dev** [comment]
> Could you please provide a description of what this PR is supposed to achieve in the PR summary?

As the description mentions this PR is supposed to fix #32901.

**Comment by jerico-dev** [comment]
> Could you please provide a description of what this PR is supposed to achieve in the PR summary?

As the description mentions this PR is supposed to fix #32901. Please read there.

**Comment by jerico-dev** [comment]
> Could you please provide a description of what this PR is supposed to achieve in the PR summary?

As the description mentions this PR is supposed to fix #32901. Please read there.

**Pull request closed without merging**
