### PR TITLE
[unist] Fix dependency ranges for previous major version

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65789#issuecomment-1628765420
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR should release a new version for each package under the previous major version with the correct dependency on `@types/unist@2` instead of `@types/unist@*`.

### CODE REVIEW

**Comment by wooorm** [comment]
How does it pin down dependencies? Because of paths?

**Comment by Methuselah96** [comment]
Correct.

**Comment by Methuselah96** [comment]
The latest major versions will still use `*`, but the ones that have `paths` will pin them to the correct major version.

**Review by wooorm — APPROVED** [review]

**Comment by remcohaszing** [comment]
Based on a random package I picked that uses this construct, it appears to work that way indeed.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1b85e933696518a58ca05d48c31065e0d20430ca/types/enzyme/tsconfig.json

See `package.json` on https://www.npmjs.com/package/@types/enzyme?activeTab=code

**Review by remcohaszing — APPROVED** [review]

**Comment by wooorm** [comment]
@navya9singh Could you take a look at this?
You recently reviewed GH-65789 with us. Which introduced a bug due to how DT handles major changes in dependent packages. Several users are noticing this issue. This PR is the fix!

Or someone else on the DT team?!

**Review by ChristianMurphy — APPROVED** [review]

**Comment by Methuselah96** [comment]
@wooorm I reached out to the DT team on Discord.

**Review by andrewbranch — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Comment by wooorm** [comment]
Thanks all!

**Pull request merged**
