### PR TITLE
[types/three]: Update Object3D based classes.

### PR DESCRIPTION
**Pull request by Astrak**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@Astrak can you point to the docs you based this on?

**Comment by Astrak** [comment]
- Lensflares code update: lensflares have been moved out to the examples and the API has been changed in early 2018 (https://github.com/mrdoob/three.js/blob/dev/examples/js/objects/Lensflare.js)
- Material type: The `Material` type that we could pass to instantiate a mesh could include materials for lines and points, with this PR the internal `MeshMaterial` does not allow it.

Then for the rest of the changes, I just started seeing some missing properties in Camera subclasses and the PR turned into fixing every Object3D-related class. I just looked at ThreeJS, nothing fancy. In particular, the methods `add` and `remove` return `this`, which was also not up-to-date in Physi.js and caused this CI fail above, so Physi.js had to be updated with this change as well.

**Comment by paulvanbrenk** [comment]
ok, thanks. Looks good to me.

**Comment by petemcwilliams** [comment]
I'm just starting to work with three, I'm getting a build error could be related to this PR...
```
> ngc -p tsconfig.json

node_modules/@types/three/three-lensflare.d.ts(3,14): error TS2415: Class 'LensFlare' incorrectly extends base class 'Mesh'.
  Types of property 'type' are incompatible.
    Type '"LensFlare"' is not assignable to type '"Mesh"'.
```
        "three": "^0.94.0",
        "@types/three": "^0.92.10",

**Comment by Astrak** [comment]
@petemcwilliams  Indeed some `type` properties are overwritten, working on it.

**Comment by danvk** [comment]
If you'd like to use three.js typings in the meantime, pin yourself to `@types/three@0.92.9`.

**Comment by matthewtebbs** [comment]
This PR broke clone() for Object3D. It used to return the class type via 'this' such that a subclass could override clone(). It no longer does breaking code that relies on that.

Change was this,
 
```typescript
-    clone(recursive?: boolean): this;
+    clone(recursive?: boolean): Object3D;
```

**Comment by dhritzkiv** [comment]
@paulvanbrenk mind making that fix?

**Comment by Astrak** [comment]
Reverted in the PR referenced above. However I'm not sure to understand what went wrong. In this PR `Camera`-s, `Mesh`, `Points`, `Line`, `Sprite`... were all subclassing Object3D and writing their own signature for `clone` without issue @matthewtebbs ?

**Comment by dhritzkiv** [comment]
@Astrak I think the problem lies with subclassing Object3D with your own implementation, something which can’t be covered by these typings. The problem also applies to all the lesser known subclasses of Object3D in Three that aren’t covered by these typing.

**Comment by matthewtebbs** [comment]
Yes. It’s a type issue. this !== Object3D when transpiring TypeScript projects that derive (in my case mixin) from the declared Three class types. Copy/clone methods should always take and return objects of type this. Thx.

**Pull request merged**
