### PR TITLE
[@types/relay-runtime]: OperationAvailability v9.x.x

### PR DESCRIPTION
**Pull request by morrys**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/relay/blob/v9.0.0/packages/relay-runtime/store/RelayStoreTypes.js#L210
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by alloy** [comment]
The current relay-runtime typings are still for v8.x.x, in which these are just strings https://github.com/facebook/relay/blob/v8.0.0/packages/relay-runtime/store/RelayStoreTypes.js#L217.

We can make this change and bump the version to v9.x.x in the `index.d.ts` header, but I think it would be good to then assure most other APIs have stayed the same. What do you think?

**Comment by morrys** [comment]
Honestly I thought it was already at version 9.x.x ..
It is certainly a good idea to check the other APIs and for the moment change I the title of the PR by adding the version

**Comment by sandersn** [comment]
@morrys relay-runtime's index.d.ts still has 8.0 in this PR. Did you intend to update all of relay-runtime to 9.0?

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes so the bot understands the current status.

**Comment by alloy** [comment]
@morrys What do you want to do here? Do you have an idea of how often these might be used? If very little, then perhaps we should just bump the version to 9 and start with these changes?

**Comment by morrys** [comment]
OperationAvailability is mostly an internally used type, I would bump to version 9 with this change so as to allow other PRs to fix the other types.

**Comment by alloy** [comment]
Sounds good to me :+1: Mind updating the PR to bump the version requirement?

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getRequestIdentifier
1. MutationTypes
1. RangeOperations
1. VIEWER_ID

<details>
<summary>as well as these 9 other properties...</summary>
<p>VIEWER_TYPE, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isPromise, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5bfd114fb6022a53381ac9683a744e94a1eae907
</p>

**Comment by alloy** [comment]
Great, thanks!

**Pull request merged**
