### PR TITLE
Upgrade webpack to 2.0

### PR DESCRIPTION
**Pull request by flying-sheep**
- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes:

	- https://webpack.js.org/configuration/module/
	- https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json

- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
These types look good. But according to `npm info`, webpack is still at version `1.13`, with version 2 being in beta. Unfortunately, we don't yet have the infrastucture to support automated publishing of updates to an older version of the package when a newer version has been published. So I'm not sure if we should upgrade it just yet.
On the other hand, it's possible that the `1.13` types are fine as-is and won't ever have to be updated.
It looks like you've made some effort to be backwards-compatible with e.g. `OldLoader`, but how backwards-compatible is it?

**Comment by flying-sheep** [comment]
completely backwards-compatible.

[as you can see](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12589/files#diff-c89d9d3b3f5515b2b5321f5747670dcb) i only moved and edited the `ExtractTextPlugin` test (which changed because `ExtractTextPlugin`’s signature changed, and added one test for `webpack` using the new syntax.

**Comment by flying-sheep** [comment]
@andy-ms what do you say?

**Comment by andy-ms** [comment]
Sounds good then. Give it a few days for @tkqubo to respond. If there's no response for 3 days, ping me and I'll merge this.

**Comment by yuit** [comment]
Thanks @flying-sheep  for the PR. The build break is fixed in another branch. Once that is merged, I will let you know to update your PR as well

**Comment by andy-ms** [comment]
@flying-sheep Please rebase this onto the latest from `types-2.0`.

**Comment by flying-sheep** [comment]
done

**Comment by flying-sheep** [comment]
aw great!

**Pull request merged**
