### PR TITLE
[React] Fix linting errors and add support for transition timeout props on CSSTransitionGroup

### PR DESCRIPTION
**Pull request by adidahiya**
- also fixed some errors in material-ui typings which caused the build to fail (not sure why these errors weren't picked up in a different PR)

### CODE REVIEW

**Comment by adidahiya** [comment]
This change is purely additive (+ whitespace / semicolons), so not sure why material-ui tests are failing...

**Comment by adidahiya** [comment]
@ngbrown can I get some help here?

**Comment by ngbrown** [comment]
@adidahiya it helps to check if the DefinitelyTyped test suite is passing before you push to GitHub and make a pull request.

For your problem of tying the legacy Material-UI versions to the legacy React version, you have to switch over completely, the `react/addons` was replaced with something else that is still pulling in the current version of React.

For an example commit that fully switches over and passes the tests (ran locally), see https://github.com/ngbrown/DefinitelyTyped/commit/b241134edbbdbd3982a25a7f5e17cf5841341e1b.

**Comment by adidahiya** [comment]
@ngbrown great, thanks for providing the code. I ran the tests locally _before_ making those material-ui changes in my last commit and they passed, so I was confused when it failed in travis.

Any idea why my react changes here caused regressions in the test suites?

**Comment by adidahiya** [comment]
@vvakame who's the owner here? should I ping the contributors from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6205?

**Comment by vvakame** [comment]
@pspeter3 @vsiao @jbrantly @RyanCavanaugh .

**Comment by ngbrown** [comment]
I'm fine with the material-ui changes.

**Comment by adidahiya** [comment]
bump @pspeter3 @vsiao @jbrantly @RyanCavanaugh

**Comment by adidahiya** [comment]
@johnnyreilly .

**Comment by johnnyreilly** [comment]
I'm happy to merge if someone else can review this

**Comment by jbrantly** [comment]
Apologies for the delay. :+1: from me

**Comment by johnnyreilly** [comment]
Thanks!

**Pull request merged**
