### PR TITLE
[node] Type for module._compile

### PR DESCRIPTION
**Pull request by STRd6**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Module._compile](https://github.com/nodejs/node/blob/a2d86f6009dd0a33830ecf0677d69e1f181aea26/lib/internal/modules/cjs/loader.js#L1059)

### CODE REVIEW

**Review by SimonSchick — CHANGES_REQUESTED** [review]
This doesn't seem like it's part of the public api, can we get some docs on this?

**Comment by STRd6** [comment]
@SimonSchick It is not in the public documentation but it exists and is widely used. What's the policy for adding private types?

**Comment by peterblazejewicz** [comment]
this can be augmented in those impl requiring private api. Your specific implementation can be augmented IMO that way:
```ts
declare namespace NodeJS {
  interface Module {
    _compile(content: string, filename: string): void;
  }
}
...
...
require.extensions[".ts"] = (module, filename) => {
  module._compile("", filename);
};
```

I believe consensus for NodeJS is to not leak private api in definition file. Same for unuse, undocumented constructor, when docs/consesus is to use factories, etc.

**Comment by STRd6** [comment]
@peterblazejewicz Thanks for the clarification, sounds reasonable.

**Pull request closed without merging**
