### PR TITLE
Fix input property on styles object for @types/react-select

### PR DESCRIPTION
**Pull request by turisap**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- current definition gives an error when trying to set custom input styles as per docs:

```
const customStyles = {
  input: (provided: CSSObject ) => ({
    ...provided,
   opacity: 0
  }),
}

  const App = () => (
    <Select
      styles={customStyles}
      width='200px'
      menuColor='red'
    />
  );
```
The error looks as follows:

```
Types of property 'input' are incompatible.  
'(provided: CSSObject) => { opacity: number; alignContent?: string | string[] | undefined; alignItems?: string | string[] |
undefined; alignSelf?: string | string[] | undefined; alignTracks?: string | string[] | undefined; ... 881 more ...; ":visited"?:
CSSObject | undefined; }' is not assignable to type '(base: CSSObject, props: InputProps) => CSSObject'. Types of
parameters 'provided' and 'base' are incompatible.
```

However, with this PR edit it works as expected

### CODE REVIEW

**Comment by Methuselah96** [comment]
Can you explain why your change makes a difference? I would think that your change should not make a difference. Are you sure that the issue wasn't fixed by something else you changed in your code?

**Comment by turisap** [comment]
@Methuselah96, it actually feels strange to me as well as both implementation of `input` are actually the same, but both of my IDEs (VSCode and WebStorm) shows an error. Also, production builds fail with the same error.

Answering about your question about changing something in my code, I am not sure what to change as I did everything as per docs and the only solution I see for now is `@ts-ignore` on `styles` property of `ReactSelect`

**Review by Methuselah96 — APPROVED** [review]
I see now that it's making the `input` method consistent with the rest of them. Still not sure why it makes a difference, but I'm good with the change if only to make it consistent. Bonus points if you can add a test.

**Review by Methuselah96 — APPROVED** [review]
Thanks!

**Comment by turisap** [comment]
Ready to merge

**Pull request merged**
