### PR TITLE
Allow nodeFn.apply to accept an IArguments in addition to arrays

### PR DESCRIPTION
**Pull request by optical**
Allows the `apply` function to take in an `IArguments`. Seems to work fine from my testing - but probably worth having a second set of eyes checking that it makes sense.

### CODE REVIEW

**Comment by vvakame** [comment]
*when/when.d.ts*

to authors(@derekcicerone @Nemo157). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by derekcicerone** [comment]
Sorry, I haven't used "when" in several years so I'm probably not a good reviewer at this point.

**Comment by Nemo157** [comment]
Quick scan of https://github.com/cujojs/when/blob/master/lib/apply.js looks like it only uses `.length` and `[]` on the args object, and `arguments` supports both of those so should be good.

:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
