### PR TITLE
Update Bing Maps API type definition from V7 to V8

### PR DESCRIPTION
**Pull request by jamesmcroft**
This refers to the merge fixes asked for in the closed #11691 PR as requested by @yuit

### CODE REVIEW

**Comment by sandersn** [comment]
Actually, the old version needs to go in a nested directory, like `DefinitelyTyped/bingmaps/v7/...`. Sorry that we weren't clear about that earlier.

**Comment by jamesmcroft** [comment]
@sandersn no problem, I'll sort that out. Would you also expect this change to come under a v8 folder too or be at the root?

**Comment by sandersn** [comment]
The current version should be at the root. Generally `index.d.ts` should match what you get when you say `npm install bingmaps` so that `npm install @types/bingmaps` works as expected.

**Comment by paulvanbrenk** [comment]
@jamesmcroft gentle ping

**Comment by jamesmcroft** [comment]
I'll get this sorted now 👍

**Comment by andy-ms** [comment]
Since this is a fairly large change, could you make it on the `types-2.0` branch instead? You will need to make some changes to `tsconfig.json`, and it would be nice (but not required) to add a `tslint.json` too.

**Pull request closed without merging**
