### PR TITLE
Remove circular dependency

### LINKED ISSUE #6265: Circular dependency with serve-static
Hi,

I'm trying to add it via NuGet Package Manager, and I receive and error which says that there is a circular dependency with serve static.
> Install-Package : Circular dependency detected 'express.TypeScript.DefinitelyTyped 2.1.7 => mime.TypeScript.DefinitelyTyped 0.0.1 => node.TypeScript.DefinitelyTyped 1.7.8 => serve-static.TypeScript.DefinitelyTyped 0.0.4 => express.TypeScript.DefinitelyTyped 2.1.7'.

Can you fix this somehow?

### PR DESCRIPTION
**Pull request by flcdrg**
express.d.ts and serve-static.d.ts had a circular dependency, which causes NuGet pain.
Extract core definitions from express.d.ts and move them to express-serve-static-core.d.ts
Update serve-static.d.ts to depend on express-serve-static-core.d.ts

Fixes #6265

### CODE REVIEW

**Comment by vvakame** [comment]
`express-serve-static-core` is not exists npm...
@staxmanade could you handling this PR? Is there no other solution?

**Comment by staxmanade** [comment]
I can't say for certain whether it'll work until it is merged and we see how things go... Anyone against giving it a go? I can keep an eye on the NuGet side.

**Comment by flcdrg** [comment]
So is this ok to merge?

**Comment by staxmanade** [comment]
I can't see why not - if there are any issues down-stream we someone tackle them then :)

**Pull request merged**
