### PR TITLE
Add edge configuration parameter to dagre-d3.

### PR DESCRIPTION
**Pull request by Tichau**
I've jute added a missing parameter in the api of dagre-d3 lib.

### CODE REVIEW

**Comment by qinfchen** [comment]
looks reasonable to me, need to update the test. 
defer to dagre author, @cpettitt?

**Comment by ChristianBeilschmidt** [comment]
Your parameter is not optional, I posted a pull request that covered that some days ago.

#9143

**Comment by qinfchen** [comment]
prefer closing this one in favor of #9143

**Comment by Tichau** [comment]
Thanks for your pull request!

**Pull request closed without merging**
