### PR TITLE
React-native: enable JS intellisense for StyleSheet.create method

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
Add a non-generic overload for 'create' to enable intellisense in Javascript

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present - _not checked since running it shows a huge number of linting issues so fixing them IMO is a separate change, not related to this one_

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js#L197

This is refined version of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13988 with  comments from previous PR addressed. 

This PR adds non-generic overload to allow ts engine to provide intellisense in the following cases: 

- when function is called without providing generic type:

  screen shot 2017-03-23 at 17 17 30

- in Javascript projects where it's impossible to use generics to provide information about `T` fields types 

The initial generic signature also needs to be retained to not break compilation of existing projects .

### CODE REVIEW

**Comment by alloy** [comment]
Can you add tests? E.g. for when no `T` is specified and styles are not typed inline.

**Comment by vladimir-kotikov** [comment]
Hmm.. Sure, will add. Also looks like there are some failures, related to this change - I'll take a look shortly.

**Comment by alloy** [comment]
Ah yeah, makes sense, now all untyped uses (which I bet there are a lot of) are being limited in style types to those defined in `Style`, which means it will now be required for people to type their valid use-cases 🤔

**Comment by vladimir-kotikov** [comment]
Hmm, this works w/ Typescript 2.2 - there was some issue w/ accessing properties of interfaces, defined w/ `{[key: string]: SomeType}` syntax using '.' rather than `object[key]` notation (https://github.com/Microsoft/TypeScript/issues/12596). So using this would require people to upgrade their typescript version.

I can add `// TypeScript Version: 2.2` directive to those files to make CI pass but not sure about that - what's the policy about ts version requirements.

**Comment by vladimir-kotikov** [comment]
Also an alternative might be to make non-generic overload return value of `any` type but wouldn't it be too broad in that case?

**Comment by paulvanbrenk** [comment]
TypeScript 2.2 has been out for a while, so I'm ok with adding that requirement at this point. However I can't speak for the react-native community.

@mhegazy  thoughts?

**Comment by alloy** [comment]
I don’t know what the TS/RN community does, we do use 2.2 for our app, so I’m 👍 on updating that.

**Comment by alloy** [comment]
@vladimir-kotikov What about the solution in #14906? I think that one is the better solution, could you verify that that fixes your issue?

**Comment by vladimir-kotikov** [comment]
@alloy, thanks for pointing me out! That's definitely a better one and it works perfectly but looks like it has some other issues, so I'll keep this one open for now

**Comment by alloy** [comment]
@vladimir-kotikov Awesome, thanks for verifying 👍 I’ll ask them to rebase.

**Comment by andy-ms** [comment]
Hopefully we can use that PR and Microsoft/TypeScript#14841 will give autocomplete even in the generic case.

**Comment by alloy** [comment]
@vladimir-kotikov There hasn’t been much activity on the linked PR. Would you be up for rebasing that on current master so we can get this in?

**Comment by RyanCavanaugh** [comment]
Can we close this one?

**Comment by vladimir-kotikov** [comment]
@RyanCavanaugh, @alloy closing this one in favor of #14906

**Comment by alloy** [comment]
@vladimir-kotikov Thanks for the nudge, I hadn’t realised it got rebased.

**Pull request closed without merging**
