### PR TITLE
[faker] Added missing methods in faker.finance

### PR DESCRIPTION
**Pull request by wit1312**
Added methods in finance:
- routingNumber
- litecoinAddress
- creditCardNumber
- creditCardCVV
- ethereumAddress
- transactionDescription

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Marak/faker.js/blob/v5.1.0/lib/finance.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## faker ([<kbd>unpkg</kbd>](https://unpkg.com/browse/faker@latest/))
was missing the following properties:
1. locales
1. localeFallback
1. definitions
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f92d7048478f4dd99eaea2ff536f6a247403441e
</p>

**Comment by TastefulElk** [comment]
Thanks for the PR @wit1312! These methods are part of Faker v5 which was recently finally (🎉) released. Please update package version in the top of the `index.d.ts` file to 5.1 accordingly! 👍 

There's a bunch more methods that's been added in the v5 release that should be added as well but I guess that could be done separately

**Review by TastefulElk — APPROVED** [review]

**Review by TastefulElk — CHANGES_REQUESTED** [review]
Bump version in types header

**Comment by TastefulElk** [comment]
I added the rest of the v5 changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47301 👍

**Review by TastefulElk — APPROVED** [review]

**Comment by wit1312** [comment]
Ready to merge

**Pull request merged**
