### PR TITLE
Update directory_v1.d.ts - tie User interface to UserOrganization namespace.

### PR DESCRIPTION
**Pull request by tdesrosi**
User.organizations is not properly tied to UserOrganization interface.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. 
    - **N/A** Google Apps Script typings appear untested in this project.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Admin SDK Rest API Resource](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users#User)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. 
    **N/A** - Does not correspond to a major release.

### CODE REVIEW

**Review by mtgto — COMMENTED** [review]
It is not mentioned about type of organizations in the doc, but it seems to that your assertion is correct.
https://developers.google.com/admin-sdk/directory/reference/rest/v1/users#User.FIELDS.organizations

> N/A Google Apps Script typings appear untested in this project.

`Admin Directory (Advanced service)` is already tested.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/93480a775a6b0181fc0cf2ec5e3b5002d70fcaec/types/google-apps-script/test/google-apps-script-tests.ts#L71-L92

Add some your test code.

**Comment by tdesrosi** [comment]
Thanks again for the review. Like the changes for calendar v3, I've added some code in tests to access the user organization interface. Please let me know if there's anything else I can help with.

**Review by mtgto — APPROVED** [review]
LGTM. Thanks!

**Comment by tdesrosi** [comment]
Ready to merge

**Pull request merged**
