### PR TITLE
Fix declarations for 'bunyan'

### PR DESCRIPTION
**Pull request by KostyaTretyak**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

**Link**
It is possible to call i.e. [`log.trace()` without arguments](https://github.com/trentm/node-bunyan#log-method-api)

### CODE REVIEW

**Comment by KostyaTretyak** [comment]
Maybe someone will tell me, please, how to re-export `bunyan`?

I have `logger.ts` file:

```ts
import bunyan = require('bunyan');
export const Logger = bunyan;
```

And in other file I want encapsulate the `Logger`
```ts
import { Logger } require('./logger');

const log: Logger; // Error: Cannot find name 'Logger'.
```

How I can do this?

**Comment by KostyaTretyak** [comment]
I think I found the answer:

```ts
// In logger.ts
import bunyan = require('bunyan');
export {bunyan as Logger};

// In other files
import { Logger } require('./logger');
let log: Logger; // OK
```

**Comment by aozgaa** [comment]
Yes that pattern will work.

**Comment by aozgaa** [comment]
Can you take a look, @amikhalev ?

**Comment by KostyaTretyak** [comment]
Perhaps it is time to merge without confirmation from @amikhalev?

**Review by amikhalev — APPROVED** [review]
Sorry for the delay. This looks correct.

**Comment by amikhalev** [comment]
:+1:

**Pull request merged**
