### PR TITLE
Redis update to 0.12.1

### PR DESCRIPTION
**Pull request by MugeSo**
Update to 0.12.1 and fix some bugs.

### CODE REVIEW

**Comment by vvakame** [comment]
*redis/redis.d.ts*

to authors(@soywiz @CodeAnimal). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by kanreisa** [comment]
:+1:

**Comment by MugeSo** [comment]
ping @vvakame @soywiz @CodeAnimal

**Comment by vvakame** [comment]
@MugeSo thanks mate!

**Comment by MugeSo** [comment]
:smile:

**Pull request merged**
