### PR TITLE
Added type definitions for openplayer

### PR DESCRIPTION
**Pull request by rafa8626**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by plantain-00 — CHANGES_REQUESTED** [review]
Since the package bundles its types, this PR seems not needed here: https://github.com/rafa8626/openplayer/blob/master/package.json#L16

**Comment by rafa8626** [comment]
@plantain-00 Thanks for the feedback. Before I close this PR, I'd like to know if this definition type file meets the expected standards or if there's anything I need to modify in it.

**Comment by plantain-00** [comment]
Since the package is written by typescript, you don't have to write the declaration, just set `"declaration": true` in `tsconfig.json`, then `tsc` will generate the right one for you.

**Comment by rafa8626** [comment]
Thanks for the advise. I wasn’t aware of that option. Closing PR now

**Pull request closed without merging**
