### PR TITLE
[k6] Add k6/net/grpc constants (grpc status codes)

### PR DESCRIPTION
**Pull request by JHBaik**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
       https://k6.io/docs/javascript-api/k6-net-grpc/constants
       https://github.com/k6io/k6/blob/master/js/modules/k6/grpc/grpc.go
       https://pkg.go.dev/go.k6.io/k6/js/modules/k6/grpc
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ppcano — CHANGES_REQUESTED** [review]
@bjh970913 thank you for adding this. 

Please, would mind configuring the correct constant number according to https://github.com/k6io/k6/blob/master/js/modules/k6/grpc/grpc.go

**Comment by bjh970913** [comment]
> @bjh970913 thank you for adding this.
> 
> Please, would mind configuring the correct constant number according to https://github.com/k6io/k6/blob/master/js/modules/k6/grpc/grpc.go

Hi! @ppcano 

I don't know is it ok to declare actual value of constant on this repository.
Is there any guide lines for declaring constants?

**Comment by bjh970913** [comment]
> > @bjh970913 thank you for adding this.
> > Please, would mind configuring the correct constant number according to https://github.com/k6io/k6/blob/master/js/modules/k6/grpc/grpc.go
> 
> Hi! @ppcano
> 
> I don't know is it ok to declare actual value of constant on this repository.
> Is there any guidelines for declaring constants?

I found some similar examples from this repository.

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/uinput/index.d.ts
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-codes/index.d.ts

I think responsibility for providing constant's actual value is on implementations.

**Review by ppcano — APPROVED** [review]

**Comment by ppcano** [comment]
Ready to merge

**Pull request merged**
