### PR TITLE
Export module BootstrapFileInput

### PR DESCRIPTION
**Pull request by ne0h12**

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
Hey @ne0h12, sorry for the delay. I think that a more appropriate change would be

```ts
/// <reference types="jquery" />

declare global {
   interface JQuery {
        fileinput: (options?: BootstrapFileInput.FileInputOptions) => JQuery;
    }
}

export = BootstrapFileInput;
export as namespace BootstrapFileInput;

declare module BootstrapFileInput {
    // ... the contents in here stay the same ...
}
```

**Comment by RyanCavanaugh** [comment]
@ne0h12 Please address comments from the code reviewers.

**Comment by ne0h12** [comment]
@DanielRosenwasser I agree. Thanks.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
