### PR TITLE
upgrade @carbon/icons-react to version 10.31

### PR DESCRIPTION
**Pull request by metonym**
This PR types the icons shipped in the newly added `@carbon/icons-react/next` folder.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/tree/master/packages/icons-react
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by josefaidt — APPROVED** [review]

**Comment by elibarzilay** [comment]
@metonym: By a weird coincidence, I looked at sizes of DT packages a few days ago, and this wins the dubious prize of biggest directory, more than twice than the runner-up.  And this is not by byte-count (it's only 2nd place by that), but by actual usage -- due to having around 12k tiny files that all redirect to the main `index.d.ts`.  I see that this is a recent-ish change from #48930.

Why is this needed?  Also, must the whole thing be duplicated?

(And these questions also apply to `carbon__pictograms-react`, which is not as bad.)

(Ping @RyanCavanaugh)

**Comment by metonym** [comment]
@elibarzilay `@carbon/icons-react` ships icons with a slightly different API in the `/next` folder, intended for the next major release. If this is too much, I'm totally fine with waiting until the next major release when it would replace the existing files in `/es`, `/lib` etc.

**Comment by elibarzilay** [comment]
The question is whether it's possible to go back to the setup you had before #48930, avoiding the thousands of files that redirect to the main one.

**Comment by metonym** [comment]
@elibarzilay Ah, I don't think so, unfortunately. Adding the additional lib/es folders was needed because consumers were importing icons directly from those folders.

**Comment by elibarzilay** [comment]
@metonym, we discussed it and decided to keep things as they are for now, but please do consider suggesting adding jsdoc-style types to the source files.  Since the main cost here is the number of files rather than their size, and since the types are very simple (all are the same), it would make a lot of sense to just add these types and cut down the FS cost that people need to invest to get both the sources and the types.

**Pull request merged**
