### PR TITLE
[@types/carbon-components-react] add missing ReactAnchorAttr types to SwitcherItem

### PR DESCRIPTION
**Pull request by Garfield550**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/SwitcherItem.js

### CODE REVIEW

**Comment by Garfield550** [comment]
Hi @joshblack, can you review this pull request?

**Comment by Garfield550** [comment]
Hi @asudoh, can you review this pull request?

**Comment by Garfield550** [comment]
Hi @kalbert312, can you review this pull request?

**Review by kalbert312 — APPROVED** [review]
Makes sense. Not sure why it was `{}` given that default prop of the UIShell Link `element` is `"a"`.

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for the change @Garfield550 - LGTM as long as my assumption is right that `<E extends object = {}>` part should reflect the type of the element misc props of the component targets to.

**Comment by orta** [comment]
👍 looks good to me

**Pull request merged**
