### PR TITLE
Add GeometryUtil functions to leaflet-draw

### PR DESCRIPTION
**Pull request by locosmike**
Add two functions in the GeometryUtil namespace of leaflet-draw

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-geometryutil
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by reblace** [comment]
Can you add calls to the added functions to the tests to validate that the changes compile?

**Review by reblace — CHANGES_REQUESTED** [review]
Can you add calls to the added functions to the tests to validate that the changes compile?

**Comment by locosmike** [comment]
I added the function calls to the tests and resolved a merge conflict with #14791

**Comment by locosmike** [comment]
@reblace Any other suggestion?

**Comment by reblace** [comment]
They seem to be a bit behind in approving PRs. I've had one sit for almost a month before it got merged and published, so you're prob good. Just need to wait :(

**Comment by mhegazy** [comment]
Sorry for the delay.

**Pull request merged**
