### PR TITLE
d3-dispatch - parameter `that` need not be an `EventTarget`

### PR DESCRIPTION
**Pull request by kum-deepak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/d3/d3-dispatch - use example as a test case that fails without this change.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

I am one of the maintainers of https://github.com/dc-js/dc.js. We are converting it to Typescript. I want to get the PR process right so that I can raise additional ones if I come across any other inconsistency.

Many thanks for your great work!

### CODE REVIEW

**Comment by kum-deepak** [comment]
While reviewing the code, I also believe that there should be no restriction on `that` at all. Technically the same dispatch instance is free to use different `that` across different calls of `call`. If you suggest we can add `T=any` in the type defintion.

**Review by gustavderdrache — COMMENTED** [review]
This looks pretty good, but we might want to tighten the restriction so that `T extends object`, due to the requirement that `Function.prototype.call` (and `.apply`)'s first argument needs to be an object instance:

```
> d3.dispatch('test')
  .on('test', function (...args) { console.log(this, args); })
  .call('test', 42)
Number { 42 } Array []
```

Thoughts?

**Comment by kum-deepak** [comment]
Makes sense. I have pushed one more commit with `T extends object`.

**Review by gustavderdrache — APPROVED** [review]
Looks good!

**Comment by kum-deepak** [comment]
Ready to merge

**Pull request merged**
