### PR TITLE
Type definitions for Jquery Knob

### PR DESCRIPTION
**Pull request by iain8**
Created a definition file for the small but very useful jQuery Knob plugin (http://anthonyterrien.com/knob/)

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.knob/jquery.knob.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.knob
  * http://bower.io/search/?q=jquery.knob
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.knob/jquery.knob-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@iain8 thank you for your contributions.
please rename jquery.knob/jquery.knob.d.ts to jquery-knob/jquery-knob.d.ts
https://www.npmjs.com/package/jquery-knob

**Comment by iain8** [comment]
fixed (i think!)

**Comment by vvakame** [comment]
@iain8 one more. please remove jquery.knob/ dir.

**Comment by iain8** [comment]
oops, now more fixed.

**Comment by vvakame** [comment]
@iain8 thanks mate!

**Pull request merged**
