### PR TITLE
Add types for the CycloneDX SBOM specification

### PR DESCRIPTION
**Pull request by eoftedal**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Remarks:
For  tslint.json the test file is ignored as it contains JSON objects that needs to be tested and these generate a lot of noise if the linting is on for that file.

### CODE REVIEW

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
The .d.ts looks fine but the test file is 14,000 lines long which means it is a) too long to view in the GitHub UI and b) probably just too long altogether. Can you split it up / make it smaller / explain why neither of those are possible?

**Comment by eoftedal** [comment]
The the test file is using a couple of examples of valid CycloneDX JSON blobs form the CycloneDX sample repo to ensure the types are valid for real life CycloneDX documents. I can split them into multiple test files if that helps.

**Comment by eoftedal** [comment]
@RyanCavanaugh I've split the large file into smaller ones, and also found a smaller example of the 1.2 version.

**Review by andrewbranch — APPROVED** [review]

**Comment by eoftedal** [comment]
Ready to merge

**Pull request merged**
