### PR TITLE
Updated existing activex definitions

### PR DESCRIPTION
**Pull request by zspitz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
there's a ton of TSLint issues reported by Travis, which should be relatively easy to fix.

**Comment by zspitz** [comment]
@paulvanbrenk I am still left with two issues:

1. [String-valued enums](https://github.com/Microsoft/TypeScript/pull/15486) aren't recognized. It seems that Travis is not trying to compile under Typescript 2.4, even though that version is listed in the header of `types/activex-wia/index.d.ts`.
2.  A version number is expected. 
    `dt-header  Error parsing header. Expected: foo MAJOR.MINOR (Needs MAJOR.MINOR)`
    Isn't the version number optional?

**Comment by paulvanbrenk** [comment]
@zspitz not sure what's happening on Travis here... since it works on my machine. A potential solution is to merge `master` into your branch, since we released 2.4 on Monday.

@andy-ms can you clarify the version number thing?

**Comment by andy-ms** [comment]
We don't support a new TypeScript version on DefinitelyTyped until a month after its release.
A version number is not optional for a linted package. We need some major and minor version to publish; if you don't know what this should be you could just leave it as it was before. If it was missing before that would be `0.0`.

**Comment by zspitz** [comment]
@paulvanbrenk Looks like it's ready.

**Pull request merged**
