### PR TITLE
Update sinonjs/fake-timers types to 8.1.0

### PR DESCRIPTION
**Pull request by JadenSimon**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Looked through the commits in https://github.com/sinonjs/fake-timers to find the differences between the versions.

### CODE REVIEW

**Comment by justinmk3** [comment]
cc @fatso83  @remcohaszing

**Review by fatso83 — COMMENTED** [review]
Good additions, but I just realized some things:

1.  Our own docs are missing the fact that one can add "performance" to toFake. This is a recent addition. We have `​if​ ​(​method​ ​===​ ​"performance"​)​ ​` in there.
2. These docs miss it too. Might want to update it. 
3. Our NodeTimer needs to add hasRef()

**Review by fatso83 — APPROVED** [review]

**Review by remcohaszing — APPROVED** [review]

**Comment by fatso83** [comment]
Seems like Prettier complains. 
```
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

**Comment by JadenSimon** [comment]
> Seems like Prettier complains.

Yeah I think you need to run prettier on the README
I was see that before too.

**Comment by fatso83** [comment]
@JadenSimon Ha, I didn't realize that was a referenced commit 🙈 I thought it was from this project. I already knew about that other issue, just didn't see it was the same.

**Review by andrewbranch — APPROVED** [review]

**Comment by JadenSimon** [comment]
Ready to merge

**Pull request merged**
