### PR TITLE
fix(node): WritableStream .end() and .destroy() methods should be chainable

### PR DESCRIPTION
**Pull request by antongolub**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

* NodeJs doc ref: https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback
* NodeJs code refs: 
  * https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L613
  * https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L807

- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by antongolub** [comment]
I also had to change `node-expat` tsconfig.lib value because of:

```
Error in node-expat
Error: Errors in typescript@3.2 for external dependencies:
../node/globals.d.ts(859,38): error TS2304: Cannot find name 'ReadonlySet'.
../node/globals.d.ts(993,14): error TS2304: Cannot find name 'MapConstructor'.
../node/globals.d.ts(998,25): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
../node/globals.d.ts(1002,14): error TS2304: Cannot find name 'SetConstructor'.
../node/globals.d.ts(1012,18): error TS2304: Cannot find name 'WeakMapConstructor'.
../node/globals.d.ts(1013,18): error TS2304: Cannot find name 'WeakSetConstructor'.
```

**Comment by SimonSchick** [comment]
Are you sure that *all* of these libraries actually use a chainable implementation?
Historically the stream contract has been very imprecise and has often been violated by implementors or alternative stream implementations.

**Comment by antongolub** [comment]
@SimonSchick

It’s hard to say something specific about _all_ the libraries. But here is what is known for certain: current WritableStream interface does not correspond to actual NodeJs implementation. Let's try to reduce the imprecision in how Streams _really_ work in Nodejs.

I could add `@ts-ignore` everywhere, but I'm afraid this is a bad solution. If something extends/implements Nodejs stream contract it should inherit the original method signature. (SO**L**ID).

**Comment by sandersn** [comment]
@SimonSchick did you intend to sign off on this PR? Let me know if you think it should go in.

I would be hesitant to merge this unless it fixes concrete real-world problems, and is backed up by tests with the PR. `this` types can be expensive to check for assignability, especially when they're used in very large classes.

**Comment by antongolub** [comment]
@sandersn 

Some addition to what is happening. We are migrating from Flow to TS in our platform, therefore we notice differences that break our tests.

Have a look at [stream$Writable typings in Flow](https://github.com/facebook/flow/blob/master/lib/node.js#L1876)
```
  destroy(error?: Error): this;
  end(callback?: () => void): this;
  end(chunk?: string | Buffer | Uint8Array, callback?: () => void): this;
  end(chunk?: string | Buffer | Uint8Array, encoding?: string, callback?: () => void): this;
```

Well, this is our concrete real problem.

**Comment by sandersn** [comment]
@antongolub That sounds reasonable. Can you add a few more tests? I only see one new test. After the tests are in, I'll see if I can get another run of BenchmarkPR to see if performance is about the same as the first run.

@SimonSchick mind taking another look after the tests are in?

**Comment by antongolub** [comment]
@sandersn, @SimonSchick

Ok, here you go.

**Comment by antongolub** [comment]
It doesn't look like I could break it). Anyway, fixed.

```
Error in node-expat
Error: Errors in typescript@3.2 for external dependencies:
../node/globals.d.ts(247,65): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:193:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
Error in node-expat
Error: Errors in typescript@3.2 for external dependencies:
../node/globals.d.ts(247,65): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:193:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
Error in node-expat
Error: Errors in typescript@3.2 for external dependencies:
../node/globals.d.ts(247,65): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'
```

**Comment by PranavSenthilnathan** [comment]
Since this is touching a popular package, can an owner sign off:
@jkomyno @a-tarasyuk @alvis @r3nya @btoueg @BrunoScheufler @smac89 @tellnes @Touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @ZaneHannanAU @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias

**Comment by amcasey** [comment]
Closing and re-opening to trigger a fresh CI run.  Owner sign-off would still be greatly appreciated.

**Comment by amcasey** [comment]
I'm guessing the bot closed this because the latest CI run failed and no status changes had occurred in 12 (?) days.

**Comment by wa-Nadoo** [comment]
What needs to do to push forward this PR? Because of this, I cannot migrate to TS my library (previously written on JS) without partial rewrite. Example of invalid code (from TS point of view):
```js
import { once } from 'events'
import { request } from 'http'
import generateRequestOptions from './request-options'

const blobReq = request(generateRequestOptions(container, blobName, headers, method)).end()
const [blobResp] = await once(blobReq, 'response')
```

**Comment by amcasey** [comment]
@wa-Nadoo Owner sign-off would be nice, but we can bypass that after so much time without a review.  However, I haven't seen any comments addressing the perf regression.  If that's still an issue, I'm reluctant to merge this.

**Pull request closed without merging**
