### PR TITLE
Adapted jade not to have a default export

### PR DESCRIPTION
**Pull request by valotas**

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
What's the benefit of this PR? jade should have a default export. You also changed the import in the test file from ES6 style to ES5, which I don't agree with. ES6 modules are the future.

**Comment by valotas** [comment]
Maybe I did not understand something right. The old definition transpiles to something like `jade.default.compile` while the actual library exposes directly compile (which means `jade.compile`). Is there a way to tell ts not to tanspile to `default.*`?

**Comment by panuhorsmalahti** [comment]
Are we talking about plain TypeScript transpilation, not with babel? At least with babel it's transpiled correctly. The problem with not having a default export is that you need to do something like ``import * as jade from "jade";``. Not sure if this is a transpiler issue or a type definition issue.

**Comment by valotas** [comment]
I am trying to make use of jade with plain typescript transpilation. I do not use babel. 

Both `import * as jade from 'jade'` and `import jade = require('jade')` transpile to the same thing. I've changed the test to the es6 import as I agree this is the future.

The problem is that if the definition exports a default package (old definitions) typescript handles is as a an exported property with the name `default` and this is not happening within the jade library. For example the same tests with the old definitions transpiles to something like:

```
var jade_1 = require('jade');
jade_1["default"].compile("b")();
jade_1["default"].compileFile("foo.jade", {})();
jade_1["default"].compileClient("a")({ a: 1 });
jade_1["default"].compileClientWithDependenciesTracked("test").body();
jade_1["default"].render("h1", {});
jade_1["default"].renderFile("foo.jade");
```

while using `import * as jade from 'jade'` will give an error of non existing properties in `jade` (typescript expect them to be in `jade.default`).

If you directly export the functions (new definition) the transpiled test will be

```
var jade = require('jade');
jade.compile("b")();
jade.compileFile("foo.jade", {})();
jade.compileClient("a")({ a: 1 });
jade.compileClientWithDependenciesTracked("test").body();
jade.render("h1", {});
jade.renderFile("foo.jade");
```

which looks like the expected one IMHO (jade is not ES6 ready anyway).

I do not know if there is a proposed way of handling default imports though. I think it is an ES6 thing rather than a typescript thing. I think that babel patches the require to something like:

```
var import = require('import');
import = import.default || import
```

and that is why it might work. But the definitions should work as is with the typescript transpiler right?

**Comment by panuhorsmalahti** [comment]
Ok, thanks for the write up :). :+1:  for merge.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
