### PR TITLE
Remove sequelize types

### PR DESCRIPTION
**Pull request by samalexander**
Removing types for the sequelize library, which now ships official typings.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by samalexander** [comment]
Requested sequelize be added to the types-publisher dependencies whitelist:
https://github.com/Microsoft/types-publisher/pull/604

**Comment by todd** [comment]
The types that ship with Sequelize are for v5+ only. The types in this repository are for v4. Please do not remove these declaration files.

**Comment by samalexander** [comment]
@todd the types packages would still exist for v4. I assume you want to keep them around in case of issues with the definitions that require patching? If that is the case, can we warn the user to use the official types for v5+, which would help avoid confusion?

**Comment by todd** [comment]
@samalexander Yeah, agreed that we need a way to inform users about the distinction between declaration files. Open to suggestions. I'm thinking at minimum we add a `postinstall` hook that spits out some text about the difference in versions. The header comments in the declaration files themselves list what version the types are supposed to be for, but could probably be more specific. It might also be worth adding documentation directly to Sequelize about what to use for specific versions.

**Pull request closed without merging**
