### PR TITLE
Allow MDX wrapper to be an intrinsic element

### PR DESCRIPTION
**Pull request by remcohaszing**
For example, the following is valid:

```tsx
import Page from './page.mdx'

<Page components={{ wrapper: 'main' }} />
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by wooorm** [comment]
Your example above already works, right? Because it was included in `MDXComponents`.
Why should it be included in the other type? What does that solve?

**Comment by remcohaszing** [comment]
No, the example doesn’t work. See [this playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIhAEwB4INwChSVnAJQFMBDAY3gDMoIREpSLMdxp4AFEgcyLmtsQA6APSceglOmxYAPGN5lakAHZFlMAM4BeAN464AdygkwYIlABciECWDKEAGjgaYNZVysIARgjgBfPzhhAD5sIA).

**Comment by wooorm** [comment]
Ah, this is about `'wrapper'` specifically, I missed that.

I do wonder: `Component<Props>` is currently used in places where there is a `<Props>`.
But `keyof JSX.IntrinsicElements` is not related to those props.
An alternative approach would be to allow `keyof JSX.IntrinsicElements` for `wrapper` too.

To me, it seems slightly more logical to do that. But I don’t feel strongly about it.

**Comment by remcohaszing** [comment]
I get what you mean, but I think it’s fine as-is.

The main reason I even ran into this, is because I noticed this quirk while investigating the new `JSX.ElementType`

**Review by wooorm — APPROVED** [review]

**Comment by remcohaszing** [comment]
Ready to merge

**Pull request merged**
