### PR TITLE
Improve WebAudio typings

### PR DESCRIPTION
**Pull request by garciat**

### CODE REVIEW

**Comment by vvakame** [comment]
*chrome/chrome.d.ts*

to authors(@matthewkimber @otiai10). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*webaudioapi/waa.d.ts*

to authors(@bbss @kubosho). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*webrtc/MediaStream.d.ts*

to author(@smithkl42). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by otiai10** [comment]
sorry for late response. I'll check

**Comment by kubosho** [comment]
me too.

**Comment by otiai10** [comment]
Thank you! @Garciat 
Sorry for being late, it looks good to me.

@vvakame

**Comment by kubosho** [comment]
@Garciat 
Thank you for Pull Request and sorry for late for check.
`waa.d.ts` looks good to me.

@vvakame

**Comment by vvakame** [comment]
@otiai10 @kubosho thanks!
@Garciat thanks mate! I decide merge this PR.

**Comment by Garciat** [comment]
Thanks to all involved.

**Pull request merged**
