### PR TITLE
Remove global spyOn, pending, fail in @types/jest

### PR DESCRIPTION
**Pull request by ahnpnl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/jest/docs/en/api.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by douglasduteil — APPROVED** [review]
Seems legit as Jest is not Jasmine.

**Comment by alan-agius4** [comment]
Remove `spyOn` seems to be wrong, as even within `jest` flow types this is exposed as global
https://github.com/facebook/jest/blob/master/flow-typed/npm/jest_v21.x.x.js#L557

**Comment by AhnpGit** [comment]
in the package we use `jest.spyOn`. The author grouped all jest functions to namespace `jest`. `spyOn` actually belongs to Jasmine. Jest monkey-patched Jasmine therefore it can contain global `spyOn`. To be more precise, you should use `jest.spyOn`

**Comment by alan-agius4** [comment]
To be clear `jest.SpyOn` and `spyOn` are different. One is a jest-jasmine `spyOn` and the other one is `jest`, `spyOn` they have different types an different methods.

For me it doesn't make sense to install `@types/jasmine` to have typings for the global `spyOn`

While I agree that it's best to use `jest.spyOn`. `Jest` does expose the jasmine `spyOn` and thus, it should be in the typings. I believe.

**Comment by AhnpGit** [comment]
I think it's better to fix flow type on Jest repo. The flowtype in your URL is actually outdated. The last updated is 30th October 2017 and since then no one takes care of it. Better to fix it there not to expose flow type `spyOn` as global.

**Comment by alan-agius4** [comment]
But what is the point of removing it? Jest are exposing jasmine’s SpyOn as
global.

With your argument we should remove ‘it’ etc.. cause jest is not jamine and
instead of ‘it’ ine should use ‘test’.

**Comment by AhnpGit** [comment]
I removed it because those are the under the comments of the authors. As you can see inside the file
`// Relevant parts of Jasmine's API are below so they can be changed and removed over time.
  // This file can't reference jasmine.d.ts since the globals aren't compatible.`

Otherwise I wouldn't remove them :)

**Comment by AhnpGit** [comment]
if the migration takes time, I think it's good to add it back.
Btw, I did a small test by using global spyOn, the tests won't break. Only typescript linting will break if you lint test files

**Comment by alan-agius4** [comment]
I have enableTsDianostics from ts-jestenabled, which would fail my my tests
if there is a TS error.

**Comment by alan-agius4** [comment]
I created a PR that addresses this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23391

**Comment by jwbay** [comment]
@AhnpGit As the person who wrote that comment you quoted, my intent was definitely "so they can be changed and removed over time *as Jest changes and removes them*". There's no reason to remove APIs that are still present in the latest released version of Jest. It's not a definition file's job to lead the actual library in removing APIs.

**Comment by AhnpGit** [comment]
Thank you. I got your point about your comment now.

**Pull request merged**
