### PR TITLE
feat(recoil) add Recoil typings

### PR DESCRIPTION
**Pull request by kolodny**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## recoil ([<kbd>unpkg</kbd>](https://unpkg.com/browse/recoil@latest/))
was missing the following properties:
1. DefaultValue
1. useSetUnvalidatedAtomValues_UNSTABLE
1. useTransactionObservation_UNSTABLE
1. useTransactionSubscription_UNSTABLE
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 24a6bd16ab05e5afcb1d1fe01265951506f948ca
</p>

**Comment by amcasey** [comment]
@kolodny There's a pretty active discussion on this PR for the same: #44756.  Can you please try to coordinate with them?

**Review by amcasey — CHANGES_REQUESTED** [review]
Flagging just so we don't accidentally merge before reconciling with #44756.

**Comment by kolodny** [comment]
Whoops. I searched for recoil before creating this PR, not sure how I missed that

**Pull request closed without merging**
