### PR TITLE
remove 'faker' as of 6.6.6

### PR DESCRIPTION
**Pull request by martin-badin**
Remove type definitions because the package was removed from GitHub.

Discussion: #58206

- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Shinigami92** [comment]
I assume we need to wait so that `types/react-data-grid/package.json` switches to new home?

**Comment by martin-badin** [comment]
> I assume we need to wait so that `types/react-data-grid` switches to new home?

No, I created PR to allow 'types/faker' in package.json (DT-tools repository). See my PR https://github.com/microsoft/DefinitelyTyped-tools/pull/382.

**Comment by Shinigami92** [comment]
Ah so we need to wait until that is merged?

**Comment by martin-badin** [comment]
> Ah so we need to wait until that is merged?

yes we need to wait

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-data-grid ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-data-grid@latest/))
was missing the following properties:
1. toString
1. charAt
1. charCodeAt
1. concat
1. indexOf

<details>
<summary>as well as these 87 other properties...</summary>
<p>lastIndexOf, localeCompare, match, replace, search, slice, split, substring, toLowerCase, toLocaleLowerCase, toUpperCase, toLocaleUpperCase, trim, length, substr, valueOf, codePointAt, includes, endsWith, normalize, repeat, startsWith, anchor, big, blink, bold, fixed, fontcolor, fontsize, italics, link, small, strike, sub, sup, padStart, padEnd, trimLeft, trimRight, trimStart, trimEnd, toString, charAt, charCodeAt, concat, indexOf, lastIndexOf, localeCompare, match, replace, search, slice, split, substring, toLowerCase, toLocaleLowerCase, toUpperCase, toLocaleUpperCase, trim, length, substr, valueOf, codePointAt, includes, endsWith, normalize, repeat, startsWith, anchor, big, blink, bold, fixed, fontcolor, fontsize, italics, link, small, strike, sub, sup, padStart, padEnd, trimLeft, trimRight, trimStart, trimEnd</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cd8ddf6a96e88b35cf6769027b7959d3cf31ecf8
</p>

**Comment by martin-badin** [comment]
@orta @peterblazejewicz please review

**Review by Shinigami92 — APPROVED** [review]

**Review by pkuczynski — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thx!

**Review by Shinigami92 — APPROVED** [review]

**Review by pkuczynski — APPROVED** [review]

**Comment by martin-badin** [comment]
Sorry guys for the notification. I want to remove the label `The CI failed`

**Review by peterblazejewicz — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
