### PR TITLE
[simpl-schema] Add `required` key to SchemaDefinition

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Related discussion: #59570

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test simpl-schema`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/longshotlabs/simpl-schema#required>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by MysteryBlokHed** [comment]
More TS 4.7 issues :/
I'm not sure what to do about this since `mongodb` is causing the errors and it bundles its own types.

**Comment by MysteryBlokHed** [comment]
@arichter83 @Qkramer @deskoh @nicu-chiciuc @rafahoro @yurtsiv

Would one of you mind reviewing this now that the CI problems have been fixed?

**Review by joshuajeschek — APPROVED** [review]
👍

**Comment by MysteryBlokHed** [comment]
Ready to merge

**Pull request merged**
