### PR TITLE
Allow async event handler in `<Form onSubmit>`

### PR DESCRIPTION
**Pull request by ProchaLu**
Discussion https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66505#discussioncomment-10073459

This PR allows passing in async event handler for `onSubmit`. 

cc @eps1lon

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66505#discussioncomment-10073459
[Playground](https://typescript-eslint.io/play/#ts=5.5.3&fileType=.tsx&code=C4TwDgpgBACgTgezAZygXigbwFBSgMwFcA7AYwC4oAKASnQD4oA3BASwBMBubAX2%2ByJlgrBMSgBhBAFswoiMWBUwiFJXhJkdHHjgRghOGOKEANie49s2ADySZchQRKk0mAIbIQZanTSMADDxQAPT0QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMkRNHHRI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### CODE REVIEW

**Comment by eps1lon** [comment]
Looks like we'd have to write a codemod now to ensure all event handlers are void:
```diff
-<button onClick={() => returnSomethingOtherThanVoid()} />
+<button onClick={() => {returnSomethingOtherThanVoid()}} />
```

That's the same we did for `ref` (see [`no-implicit-ref-callback-return`](https://github.com/eps1lon/types-react-codemod#no-implicit-ref-callback-return)) but now it's considerably more involved since we now have to come up with a heuristic to detect event handlers.

**Comment by karlhorky** [comment]
> Looks like we'd have to write a codemod now to ensure all event handlers are void

Oh, wouldn't this have already been a problem before with the `void` return type?

Or does changing the event handler return type from `void` to `void | Promise<void>` somehow trigger extra strictness on the existing `void`?

**Comment by eps1lon** [comment]
> Or does changing the event handler return type from void to void | Promise<void> somehow trigger extra strictness on the existing void?

Yes. TypeScript does not care if you pass `() => number` as an argument to a function accepting `() => void` as a parameter.

**Comment by karlhorky** [comment]
Wow TIL super interesting!

```ts
function acceptEventHandler(eventHandler: () => void) {}

acceptEventHandler(() => 1)

function acceptEventHandlerWithAsyncFunction(eventHandler: () => void | Promise<void>) {}

acceptEventHandlerWithAsyncFunction(() => 1) // Type 'number' is not assignable to type 'void | Promise<void>'.(2322)
```

Screenshot 2024-07-22 at 12 40 35

[Playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAQwhApgBygUQG7phQASyYAJgDboBOAFOgUaRdTQFyJ0CUiAvAD5EeODHK8A3gF8AUDNQZs+QiTJVadHvyEBGbnNCRYCFGiy4mq1rQDqMKAAsAggGcAnpABi4aPDANLFnUOLl5BYVFyRAAfRAAFGjgAWxgXdAAeETEBSVk5fIVzZWY1NjtHVw8IbyM-TTDdfTkgA)

**Comment by ProchaLu** [comment]
@eps1lon @rickhanlonii, any updates about this from the React Team?

**Comment by eps1lon** [comment]
Part of the team was out so we didn't have time to discuss it yet.

**Comment by ProchaLu** [comment]
Closed

React decided not to allow async functions at the type level in event handlers like `<Form onSubmit>`. They considering adding runtime warnings when returning a Promise from an event handler, explained in this [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66505#discussioncomment-10411110)

**Pull request closed without merging**
