### PR TITLE
[mailparser] Fix address field and reference types

### PR DESCRIPTION
**Pull request by jekozyra**
I saw the original PR that made the changes to the address fields, and I don't think it should've been merged.

There have been multiple issues opened agains the mailparser library to call out that the types for this are incorrect at runtime.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - for the change to `ParsedMail.references`: [this](https://github.com/nodemailer/mailparser/blob/master/lib/mail-parser.js#L342) line of code sets the value, and due to the split, this will never be `string`. It is `string[] | undefined`.
  - for the changes to `ParsedMail.to`, `ParsedMail.from`, `ParsedMail.cc`, and `ParsedMail.bcc`, the value is set [here](https://github.com/nodemailer/mailparser/blob/master/lib/mail-parser.js#L360-L375). It is always an `AddressObject`, never `AddressObject[]`. The `value` field of the `AddressObject` contains an array of the addresses present in the field. 
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Let's wait for others opinion. I believe those types were legit, as the behaviour of the parser was not so terse previously, see e.g.:
https://github.com/nodemailer/mailparser/issues/289

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@jekozyra thanks!

**Comment by icaruswings** [comment]
can this be opened up again and merged? its still an issue as far as I can tell.

**Comment by DaRizat** [comment]
Seconded, the documentation of the library states that the address fields are a singular AddressObject with an array in the value field, yet the types allow it to be AddressObject[] which leads to a ton of defensive programming just to satisfy an incorrect type. Not sure why this was not merged? Anyone have any insight?

**Pull request closed without merging**
