### PR TITLE
Handle extra object literal properties (Part III)

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This is part of sweep of work to address https://github.com/Microsoft/TypeScript/issues/4081.

See Part I: #5151.
See Part II: #5233.

See Part IV: #5489.
See Part V: #5645.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Is something weird going on with Travis?

**Comment by DanielRosenwasser** [comment]
@danquirk @RyanCavanaugh can you take a look while I figure out what's failing?

**Comment by RyanCavanaugh** [comment]
:+1: :shipit:

**Comment by johnnyreilly** [comment]
Thanks @danielrosenwasser!

**Pull request merged**
