### PR TITLE
fix(styled-components): limited use of 'Omit' for strictly types

### LINKED ISSUE #3385: [typescript] react union types props is broken by @types/styled-components ?
## Environment

- macOS Big Sur 11.1
- node v14.3.0
- npm: 6.14.11

## Reproduction

Example:
https://codesandbox.io/s/dazzling-sun-2drq9

## Steps to reproduce

1. create typescript styled-components project ( install @types/styled-components etc. )
2. define a union object type, like this.

```
type Props = {
  type: "a";
  hoge: number;
} | {
  type: "b";
  hoge: string;
};
```

3. create react component using `Props`, like this.

```
const Component: React.FC<Props> = () => <div />
```

4. wrap it in styled-components, like this.

```
const StyledComponent = styled(Component)``;
```

5. use component, like this.

```
    <StyledComponent type="a" hoge={1} />     // <- OK: type is correct 
    <StyledComponent type="a" hoge="str" /> // <- NG: should types error
```

## Expected Behavior

The component props type should be inferred, and report type error, same as normal react component.

```
    <Component type="a" hoge="string" />
    ...
    Type '{ type: "a"; hoge: string; }' is not assignable to type '(IntrinsicAttributes & { type: "a"; hoge: number; } & { children?: ReactNode; }) | (IntrinsicAttributes & { type: "b"; hoge: string; } & { ...; })'.
  Types of property 'hoge' are incompatible.
    Type 'string' is not assignable to type 'number'.

```

## Actual Behavior

It does not occur types error.

## Why it is happened

I think it is occurred by using `Omit` in `StyledComponentProps`.

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L73-L82
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L308-L310

Typescript `Omit` make union type changed other type.

```
type AorB = {
  type: "a";
  hoge: number;
} | {
  type: "b";
  hoge: string;
};

type A = Omit<AorB, never>
const a: A = {type: "a", hoge: "str"}; // not error: 
```

Type `A` is inferred following type by typescript.

```
type A = {
    type: "a" | "b";
    hoge: React.ReactText;
}
```

So `hoge` is allowed number and string regardless of `type: "a"`.

## Suggestion

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L73-L82

If type `A` is `never`, can it avoid `Omit` ?

```
type IsExtendsNever<T> = T extends never ? true : false;

export type StyledComponentProps<
    // The Component from whose props are derived
    C extends string | React.ComponentType<any>,
    // The Theme from the current context
    T extends object,
    // The other props added by the template
    O extends object,
    // The props that are made optional by .attrs
    A extends keyof any
> =
    // Distribute O if O is a union type
    O extends object
        ? WithOptionalTheme<
            false extends IsExtendsNever<A> ?    //  <- If A is not never then use Omit
              Omit<
                  ReactDefaultizedProps<
```

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L308-L310

`WithOptionalTheme` does not use Omit.

```
type WithOptionalTheme<P extends { theme?: T }, T> = P & { theme?: T };
```

### PR DESCRIPTION
**Pull request by ka2jun8**
resolved https://github.com/styled-components/styled-components/issues/3385.

I stopped using 'Omit' where I think it is not needed for the types.

The reason why I want to avoid 'Omit'.
refer: https://github.com/microsoft/TypeScript/issues/28339

I think it is better solution for this issue,
but I am concerned about the following historical background,
because I can not perfectly understand difficulty of typescript performance issue.

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33061
- https://github.com/Microsoft/TypeScript/issues/30663
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34499

--

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by ka2jun8** [comment]
sorry, It did not pass the test.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bd298979629871e251d02bc8719e975be4b2ea79
</p>

**Comment by henrikra** [comment]
Looks good to my eye since you have fixed the tests to pass 👍

**Comment by henrikra** [comment]
@ka2jun8 Did you run the performance tests again btw? Since looks like fix for this was reverted some time ago 🤔

**Comment by ka2jun8** [comment]
> Did you run the performance tests again btw?

Benchmark test has done twice.

- https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=87148&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5
- https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=87797&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5

I think it might be same performance because there are no additional comments:

> `It looks like nothing changed too much. I won’t post performance data again unless it gets worse.`
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51252#issuecomment-779561258

**Comment by henrikra** [comment]
So good to merge? :)

**Comment by Daavidaviid** [comment]
@henrikra interested with this specific issue right now, are you guys gonna merge it ?

**Comment by sheetalkamat** [comment]
This being popular and widely used package needs review from one of @Igorbek, @Igmat, @lavoaster, @Jessidhia, @JKillian, @eps1lon, @flavordaaave, @wagerfield, @Lazyuki, @mgoszcz2, @danilofuchs.

**Review by eps1lon — APPROVED** [review]
Approving, given that the previously by bad perf affected TS versions have now reached EOL inside the DT repo and the perf benchmarks of this PR look ok ("It looks like nothing changed too much. I won’t post performance data again unless it gets worse.")

**Comment by ka2jun8** [comment]
Ready to merge

**Comment by fabb** [comment]
@ka2jun8 this change causes a compiler error when using `attrs`:
```
export const SkeletonLine = styled.div.attrs(
    (props: {
        variant?: 'dark' | 'bright'
        marginBottom?: ResponsiveValue<SystemValue>
        width?: ResponsiveValue<SystemValue>
        height?: ResponsiveValue<SystemValue>
    }) => ({ ...props })
)`
    ....
`
```
```
<SkeletonLine height={16} width="40%" marginBottom="s" />

error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: { key?: Key | null | undefined; ref?: ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type '{ height: number; width: string; marginBottom: string; }' is not assignable to type 'IntrinsicAttributes & { key?: Key | null | undefined; ref?: ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } & { ...; } & { ...; }'.
      Property 'height' does not exist on type 'IntrinsicAttributes & { key?: Key | null | undefined; ref?: ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } & { ...; } & { ...; }'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<"div", DefaultTheme, { variant?: "dark" | "bright" | undefined; margin?: ResponsiveValue<SystemValue> | undefined; marginTop?: ResponsiveValue<...> | undefined; ... 48 more ...; borderVertical?: ResponsiveValue<...> | undefined; }, "margin" | ... 50 more ... | "borderVertical", "div">): ReactElement<...>', gave the following error.
    Type '{ height: number; width: string; marginBottom: string; }' is not assignable to type 'IntrinsicAttributes & { key?: Key | null | undefined; ref?: ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } & { ...; } & { ...; }'.
      Property 'height' does not exist on type 'IntrinsicAttributes & { key?: Key | null | undefined; ref?: ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; } & { ...; } & { ...; }'.

80                         <SkeletonLine height={16} width="40%" marginBottom="s" />
```

https://styled-components.com/docs/api#attrs

**Pull request merged**
