### PR TITLE
Add types for commander-remaining-args

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by ffflorian** [comment]
@sandersn seems like `dtslint` broke when trying to parse commander's typings?

**Comment by sandersn** [comment]
@ffflorian that is a Typescript crash! I'll try to repro locally and figure out which version of typescript crashes and why. Then I'll try to find a workaround for this PR.

**Comment by sandersn** [comment]
The crash is fixed in 2.2 onwards. Add the line `// TypeScript Version: 2.2` below the rest of the header to fix this.

**Comment by sandersn** [comment]
For the error that shows up afterward, you'll need a package.json that references commander since it ships its own types.

**Comment by ffflorian** [comment]
Thank you @sandersn, I created a PR for that:

https://github.com/microsoft/types-publisher/pull/623

**Comment by ffflorian** [comment]
@sandersn could you please approve or request changes on microsoft/types-publisher#623?

**Pull request merged**
