### PR TITLE
Fix definitions of #bind/#unbind, merge overloads

### PR DESCRIPTION
**Pull request by OlsonDev**
Improvement to existing type definition.

See https://github.com/RobertWHurst/KeyboardJS/blob/master/lib/keyboard.js#L54 for bind()
See https://github.com/RobertWHurst/KeyboardJS/blob/master/lib/keyboard.js#L84 for unbind()

### CODE REVIEW

**Comment by OlsonDev** [comment]
For some reason GitHub isn't picking up my [other commit](https://github.com/OlsonDev/DefinitelyTyped/commit/1e2ac487809ebee9dbf534ecc7dc3fea0b97fc77) to `patch-2`... maybe the [maintenance](https://twitter.com/githubstatus/status/717455416934981632) that just happened?

**Comment by vvakame** [comment]
*keyboardjs/keyboardjs.d.ts*

to authors (@vbortone @piranha771). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by piranha771** [comment]
:+1: Thanks for your contribution

**Comment by vbortone** [comment]
:+1:   Thanks!

**Comment by horiuchi** [comment]
@OlsonDev Thanks mate!
@piranha771 @vbortone Thanks for review!

**Pull request merged**
