### PR TITLE
[gl] Export StackGL extension types

### PR DESCRIPTION
**Pull request by SuperSodaSea**
Export `STACKGL_destroy_context`, `STACKGL_resize_drawingbuffer` and `StackGLExtension` in `gl`.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pixijs/pixijs/pull/8842#issuecomment-1312517405

### CODE REVIEW

**Comment by michaeljherrmann** [comment]
@SuperSodaSea how are you trying to use the current typing version? When I do the following, I seem to have the correct typings:
```
import createContext, { WebGLRenderingContext } from 'gl';

const ctx1 = createContext(1, 1);
ctx1.getExtension('STACKGL_destroy_context').destroy();
ctx1.getExtension('STACKGL_resize_drawingbuffer').resize(2, 2);

const ctx2 = new WebGLRenderingContext();
ctx2.getExtension('STACKGL_destroy_context').destroy();
ctx2.getExtension('STACKGL_resize_drawingbuffer').resize(2, 2);
```

**Review by michaeljherrmann — APPROVED** [review]
Your changes also still work for me and make sense. I guess I'm just not sure why the previous code didn't quite work

**Comment by SuperSodaSea** [comment]
@michaeljherrmann The original types works just fine, but I want to use the types of the extensions directly:

```ts
import createContext from 'gl';
import type { STACKGL_resize_drawingbuffer, StackGLExtension } from 'gl';
class Foo {
    private context: WebGLRenderingContext & StackGLExtension;
    private resizeDrawingBuffer?: STACKGL_resize_drawingbuffer;
    constructor() {
        this.context = createContext(1, 1);
        this.resizeDrawingBuffer = this.context.getExtension('STACKGL_resize_drawingbuffer');
    }
}
```

Anyway, thanks for approving this.

**Comment by SuperSodaSea** [comment]
Ready to merge

**Pull request merged**
