### PR TITLE
Revert "Merge webpack-env.* into webpack.*"

### PR DESCRIPTION
**Pull request by tkqubo**
This reverts commit b123aa5469db5e5a56f8517eca31c1cdaf569ed4.

As commented here https://github.com/borisyankov/DefinitelyTyped/pull/6243#commitcomment-13792564, I wrongly merged two file, that should be used in different context.

Sorry about this @use-strict

### CODE REVIEW

**Comment by use-strict** [comment]
@vvakame , can you merge this? Thanks.

**Comment by vvakame** [comment]
merged!

**Comment by davidmoshal** [comment]
`Variable 'require' must be of type 'RequireFunction'`

still a major pain, occurs with node.d.ts, or any module which depends on it, e.g. redis.

**Comment by martin-liu** [comment]
`Variable 'require' must be of type 'RequireFunction'`
+1

**Pull request merged**
