### PR TITLE
mongoose-simple-random definition

### PR DESCRIPTION
**Pull request by rsxdalv**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sandersn** [comment]
dtslint doesn't recognise this a module extension, which is why it fails. Actually, I would have thought that the compiler would parse this as an ambient module instead of a module extension, too. Maybe `<reference types="mongoose">` changes this?

@RyanCavanaugh or @andy-ms can you tell whether this is a bug with dtslint?

**Comment by sandersn** [comment]
After talking to @RyanCavanaugh, it's not strictly a bug, but a limitation. The linter would have to resolve `types="mongoose"` and find that it, too, was an ambient module declaration. The workaround is just to disable that rule in the linter. I'll look up how to do that.

**Comment by sandersn** [comment]
Looks like it's probably:
```json
   "rules": {
        "no-single-declare-module": false
    }
```

**Comment by andy-ms** [comment]
Actually, it's better to use a comment `// tslint:disable-next-line no-single-declare-module`. Disables in a `tslint.json` imply that it should be fixed later, but this one can't be.

**Pull request merged**
