### PR TITLE
ramda updates

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Compiler version bump, updated tests to use consistent syntax, and updated the following function declarations:

* append
* binary
* bind
* both
* clone
* comparator
* complement
* countBy
* max
* maxBy
* mergeDeepWith (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18761)
* mergeDeepWithKey (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18761)
* min
* minBy
* sortBy
* prop
* tryCatch
* unary
* unnest
* where
* whereEq
* wrap (removed)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
:+1:

**Comment by BjornMelgaard** [comment]
@LiamGoodacre hi, can you resolve merge conflicts?

**Comment by BjornMelgaard** [comment]
@LiamGoodacre, tried to do it myself (it was hard), can you check?

its squashed rebase of 3 your commits (mergeDeepWith and mergeDeepWithKey were already changed)

**Comment by LiamGoodacre** [comment]
Hey, yeah I'll rebase.  1 mo

**Comment by BjornMelgaard** [comment]
@LiamGoodacre check my pr, it has @charlespwd in mentioned authors so he will be able to review it (because other authors are kind of missing)

**Comment by LiamGoodacre** [comment]
Oh okay; well, whichever one someone wants to merge.

**Comment by LiamGoodacre** [comment]
Actually, I will close mine.  @BjornMelgaard would you remove me as a contributor in your PR please?  I no-longer use typescript so I'm not particularly invested with this anymore.

**Comment by BjornMelgaard** [comment]
Wow, if you want so, okay(

**Pull request closed without merging**
