### PR TITLE
knex: Update knex whereIn to accept Raw

### PR DESCRIPTION
**Pull request by GabrielCastro**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by GabrielCastro** [comment]
cc: @RyanCavanaugh @tkqubo @baronfel @mastermatt @micksatana @shreyjain1994

**Comment by mastermatt** [comment]
@GabrielCastro can you add urls to the docs and/or source for this please?

**Comment by GabrielCastro** [comment]
Docs: 
https://knexjs.org/#Builder-whereIn
> Shorthand for .where('id', 'in', obj)
there `where` docs show support for raw in column, and the current type reflect that

**Review by mastermatt — CHANGES_REQUESTED** [review]
@GabrielCastro I don't want to imply that this doesn't work (I haven't tried it), but the docs don't cover this case of providing `Raw` as the first param. 

The docs do explicitly say, however, that `.whereIn` is a shorthand for `.where(..., "in", ...)`. Looking at the [signature definitions of `where`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7a6cc4fb8306aa0c89267b7b6757317d3fc1d4fb/types/knex/index.d.ts#L279) there is one case that has a `raw` for the left param while the right param is listed as `Value | QueryBuilder | null` which differs from the `values` types listed in this PR (`Value[] | QueryBuilder | QueryCallback`).

I think this PR either needs clarifications made to the docs or a detailed walkthrough of the source showing this functionality works and is intended to work.
I'm of the opinion that unintended functionality in libs are not meant to be represented in DT.

**Pull request closed without merging**
