### PR TITLE
Update gm.d.ts

### PR DESCRIPTION
**Pull request by dx1alex**

### CODE REVIEW

**Comment by vvakame** [comment]
*gm/gm.d.ts*

to author (@ChaosinaCan). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by ChaosinaCan** [comment]
Huh. That call signature is listed on GM's readme but I couldn't find it on the documentation page.

"img" isn't the best name for that parameter. What's the difference between "image" and "img" then? https://github.com/aheckmann/gm suggests a better name, "filename". I also missed the `(width: number, height: number, color?: string)` constructor, which you might add while you're at it.

Otherwise, it looks good to me.

**Comment by mhegazy** [comment]
@dx1alex, can you please update this PR, and resoponf to @ChaosinaCan's comments.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
