### PR TITLE
seedrandom: declared Math.seedrandom

### PR DESCRIPTION
**Pull request by DanKaplanSES**
- also added some tests at the bottom that the existing types let compile, but seem unusual

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/davidbau/seedrandom/blob/2.4.4/seedrandom.js#L108
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Zegnat** [comment]
This looks good to me, but just wondering if we should somehow expose this in the v3 as well ([based on this line](https://github.com/davidbau/seedrandom/blob/4460ad325a0a15273a211e509f03ae0beb99511a/seedrandom.js#L242)). Or if that is something we ignore for DefinitelyTyped and asume that the lib is never “included as a plain script”?

**Review by Zegnat — APPROVED** [review]

**Comment by DanKaplanSES** [comment]
@Zegnat 
> This looks good to me, but just wondering if we should somehow expose this in the v3 as well ([based on this line](https://github.com/davidbau/seedrandom/blob/4460ad325a0a15273a211e509f03ae0beb99511a/seedrandom.js#L242)). Or if that is something we ignore for DefinitelyTyped and asume that the lib is never “included as a plain script”?

Oof, that's tricky. Here's a question: can you use typescript if the code is included as a plain script? If no, I think that's a good reason to leave v3 as is.

**Comment by DanKaplanSES** [comment]
By the way, should there be an `any` here?

```ts
  interface prng {
    new (seed?: string, options?: seedRandomOptions, callback?: any): prng;
    //...
  }
```

As you can see in my test, this allows you to pass in a number for a callback. I've literally never used this library before, but it seems like the `callback` parameter should have this type instead:

```ts
  interface seedrandomCallback {
    (prng?: prng, shortseed?: string, global?: boolean, state?: State): prng;
  }
```

Let me know and I can create another PR for this, but this would be a potentially breaking change: if users are already passing in non-callbacks, this change will cause compilation errors for them.

FWIW, v2 already had a breaking change: earlier versions had `(seed?: string, entropy?: boolean, callback?: seedrandomCallback): prng;`. Today that second param is an object: `(seed?: string, options?: seedRandomOptions, callback?: seedrandomCallback): prng;`

**Comment by DanKaplanSES** [comment]
Ready to merge

**Comment by Zegnat** [comment]
> Let me know and I can create another PR for this, but this would be a potentially breaking change: if users are already passing in non-callbacks, this change will cause compilation errors for them.

My personal stance is this is OK, **if** passing in non-callbacks is actually something that will break the underlying library. Then the types change will hopefully be able to help them fix issues in existing code bases. The `any` is a type bug, if it does not match the underlying code.

> As you can see in my test, this allows you to pass in a number for a callback.

The types allow it, yes, but from my reading of [the code](https://github.com/davidbau/seedrandom/blob/62fd63021c1736ef77de2888ddf3d5d25bb882d8/seedrandom.js#L86C38-L86C38) this will throw a `TypeError` if you were to try and execute the code. Have you tried? (It will try to call the number as if it were a function.) My feeling is that people would not expect their code to throw `TypeError` when the TypeScript validates.

Seems like something where the type should be fixed 👍

**Note:** your proposed `seedrandomCallback` is probably not correct. Take a look at [my change to the v3 version](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ffad2a9ff9973199ca842d760f60dba97b29f913). I introduced a generic return type there, because the return type of `options.pass` and `callback` can be anything. It does not have to be `prng`. In fact, `options.pass` is [specifically mentioned by the documentation for seedrandom v2.4.4](https://github.com/davidbau/seedrandom/tree/62fd63021c1736ef77de2888ddf3d5d25bb882d8#reseeding-using-user-input) as a callback the user might want to change the return type of.

**Comment by DanKaplanSES** [comment]
@Zegnat 
> The types allow it, yes, but from my reading of [the code](https://github.com/davidbau/seedrandom/blob/62fd63021c1736ef77de2888ddf3d5d25bb882d8/seedrandom.js#L86C38-L86C38) this will throw a TypeError if you were to try and execute the code. Have you tried?[<sup>1</sup>] (It will try to call the number as if it were a function.) My feeling is that people would not expect their code to throw TypeError when the TypeScript validates.

I share your opinion on this. 

<sup>1</sup>: Admittedly, I have not; I'm porting some JavaScript code to typescript and it uses seedrandom v2 as `new Math.seedrandom(...)`. Pre-merge, the @type said that didn't exist. I solved this by creating my own local declaration file. After googling, I wasn't the only one experiencing this issue, so I submitted this PR. 

> Note: your proposed seedrandomCallback is probably not correct. Take a look at [my change to the v3 version](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ffad2a9ff9973199ca842d760f60dba97b29f913).

Ah. I was hoping it would be a one-liner—changing `any` to `seedrandomCallback`. Unless the solution is to copy and paste the code in your link I, unfortunately, won't have time to research, test, and implement this change. Thanks for understanding!

**Pull request merged**
