### PR TITLE
Fix CircleBufferGeometry inheriting from Geometry

### PR DESCRIPTION
**Pull request by alpynv**

### CODE REVIEW

**Comment by florentpoujol** [comment]
:-1:   CircleBufferGeometry do inherits from BufferGeometry.

**Comment by SereznoKot** [comment]
@florentpoujol well, yes... I'm confused, because currently it inherits from regular Geometry

**Comment by florentpoujol** [comment]
Hum no, neither on the r75 tag or the master branch.
https://github.com/mrdoob/three.js/blob/r75/src/extras/geometries/CylinderBufferGeometry.js#L7
https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/CylinderBufferGeometry.js#L7

In the code, the constructor clearly calls BufferGeometry's constructor and its prototype is built from BufferGeometry's .

**Comment by SereznoKot** [comment]
@florentpoujol this has got to be a crazy misunderstanding))) or I don't know what to think.
This is how the **type definition** for CircleBufferGeometry looks **right now**
2016-04-03 21_08_38-definitelytyped_three d ts at master definitelytyped_definitelytyped

**Comment by florentpoujol** [comment]
Alright my bad indeed.
We are talking about **Circle**BufferGeometry here, not **Cylinder**BufferGeometry.

The definition for CircleBufferGeometry is indeed currently wrong and fixed by your commit.
So :+1: :+1:

**Pull request merged**
