### PR TITLE
Feature/update mui datatables typings

### LINKED ISSUE #47376: Incorrect component types in @types/mui-datatables
- [x] I tried using the `@types/mui-datatables` package and had problems.
- [x] I tried using the latest stable version of tsc. 

- Authors: @Favna , @ankithkonda , @hwatersiv , @souppower , @byrekt 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8340511f346a28abcdf4b0811550c1ca81ea20e5/types/mui-datatables/index.d.ts#L568

Getting TS error:
JSX element type 'TableToolbar' does not have any construct or call signatures.

When:
<MuiDataTable
      title=""
      data={[]}
      columns={columns}
      options={options}
      components={{
        TableToolbar: (props: MUIDataTableToolbar) =>
          (<TableToolbar {...props} />) as React.ReactNode,
      }}
    />

Solution:
Type of TableToolbar and other components must be as ComponentType (not Component) 
export const TableToolbar: React.ComponentType<MUIDataTableToolbar>;

### PR DESCRIPTION
**Pull request by BohdanYavorskyi**
fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47376.

Updated typing for a last stable version of the library.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## dogapi ([<kbd>unpkg</kbd>](https://unpkg.com/browse/dogapi@latest/))
was missing the following properties:
1. client
1. now
1. OK
1. WARNING
1. CRITICAL

<details>
<summary>as well as these 1 other properties...</summary>
<p>UNKNOWN</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against daa6f47b6478f08e940bd62921e069a25e70a7b7
</p>

**Review by favna — CHANGES_REQUESTED** [review]
latest stable version as per your PR description = 3.4.1? If so please just 1 small change, can you bump the version in the header (first line of the file) from `3.2` to `3.4`? That way the bot will publish types that are meant to match version 3.4.x of the library.

If not LMK and I'll withdraw this change request (though then the types should still be updated to match 3.3.x / 3.4.x of the lib in some future PR)


---

Also add `fixes #47376` in your PR description so your issue gets autoclosed when this is merged

**Review by favna — APPROVED** [review]

**Comment by BohdanYavorskyi** [comment]
> latest stable version as per your PR description = 3.4.1? If so please just 1 small change, can you bump the version in the header (first line of the file) from `3.2` to `3.4`? That way the bot will publish types that are meant to match version 3.4.x of the library.
> 
> If not LMK and I'll withdraw this change request (though then the types should still be updated to match 3.3.x / 3.4.x of the lib in some future PR)
> 
> Also add `fixes #47376` in your PR description so your issue gets autoclosed when this is merged

I'm the newest here. How can I link the issue to that PR? And when it will be merged?

**Comment by BohdanYavorskyi** [comment]
> latest stable version as per your PR description = 3.4.1? If so please just 1 small change, can you bump the version in the header (first line of the file) from `3.2` to `3.4`? That way the bot will publish types that are meant to match version 3.4.x of the library.
> 
> If not LMK and I'll withdraw this change request (though then the types should still be updated to match 3.3.x / 3.4.x of the lib in some future PR)
> 
> Also add `fixes #47376` in your PR description so your issue gets autoclosed when this is merged

Could you merge the PR?

**Comment by Favna** [comment]
I can't. Only maintainers or the bot can. Either you have to add tests to cover the changed code, in which case the bot can, or you have to wait for a DT maintainer. 

This is described in the first comment the bot made on the PR btw.

**Comment by Favna** [comment]
As for linking an issue, I quite literally told you what to add. Just add `fixes #47367` to your PR description (where you said "Updated typing for last stable version of the library").

**Comment by BohdanYavorskyi** [comment]
> I can't. Only maintainers or the bot can. Either you have to add tests to cover the changed code, in which case the bot can, or you have to wait for a DT maintainer.
> 
> This is described in the first comment the bot made on the PR btw.

But I don't get what I should test. Should I simply add those new/updated properties in a test file?

**Review by favna — APPROVED** [review]

**Comment by Favna** [comment]
Ready to merge

**Comment by BohdanYavorskyi** [comment]
Ready to merge

**Pull request merged**
