### PR TITLE
[formidable] options is optional

### PR DESCRIPTION
**Pull request by forivall**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-formidable/formidable/blob/8f94fba/src/Formidable.js#L48
- ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~ N/A

### CODE REVIEW

**Comment by martin-badin** [comment]
@forivall Please, add optionally options here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fc461fe2889fa93dee315fc2f0c8b5657d6a290e/types/formidable/index.d.ts#L395

**Review by martin-badin — CHANGES_REQUESTED** [review]
@forivall Please, add optionally options here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fc461fe2889fa93dee315fc2f0c8b5657d6a290e/types/formidable/index.d.ts#L395

**Comment by forivall** [comment]
@martin-badin done!

**Review by martin-badin — APPROVED** [review]
LGTM

**Comment by forivall** [comment]
Ready to merge

**Pull request merged**
