### PR TITLE
Make the "undersore methods" to protected ones in the definitions

### PR DESCRIPTION
**Pull request by atd-schubert**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  ex. url https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback_1. Especially the note (Note: This function MUST NOT be called by application code directly. It should be implemented by child classes, and called only by the internal Writable class methods only.) 
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by mhegazy** [comment]
@zelein  and @vvakame can you review this change?

**Review by nickzelei — APPROVED** [review]
After cross-referencing the documentation of the protected keyword in TypeScripet https://www.typescriptlang.org/docs/handbook/classes.html and reading the note in the Node docs about underscore methods, this appears to be the correct behavior.

**Comment by mhegazy** [comment]
Looks like the CI Server is failing, can you take a look.

**Comment by zelein** [comment]
For file:cassandra-driver/cassandra-driver.d.ts
cassandra-driver/cassandra-driver.d.ts(365,15): error TS2430: Interface 'ResultStream' incorrectly extends interface 'Readable'.
  Property '_read' is protected but type 'ResultStream' is not a class derived from 'Readable'.

**Comment by atd-schubert** [comment]
For me it seems like the `_read` method of ResultStream of cassandra-driver is just part of the implementation of a readable stream and not part of the public APIs (look at the source-code: https://github.com/datastax/nodejs-driver/blob/master/lib/types/result-stream.js) and by following your guidelines (http://definitelytyped.org/guides/contributing.html#private-apis) it should not be part of the `d.ts`. Should I remove this method in my fork for a clean merge? The tests seems to be (more or less) fine after this change.

Sorry, that I have not checked this before, but I thought, that is was not depending on my changes...

But after I run the `npm test` the test-runner reports that especially cassandra-driver has no tests. This was the output:
```
-----------------------------------------------------------------------------
 Typing without tests
-----------------------------------------------------------------------------
 - cassandra-driver
 - base64url
 - gulp-load-plugins
 - gulp-plumber
 - gulp-sort
 - json-socket
 - locutus
 - pi-spi
 - sequelize
 - twilio
 - node_redis
 - body-parser
 - csurf
-----------------------------------------------------------------------------
 Total
-----------------------------------------------------------------------------
 Elapsed time    : ~18 minutes (1106.187s)
 Syntax error    : 0.00% (0/484)
 Failed tests    : 0.00% (0/538)
 Invalid header  : 0.00% (0/484)
 Without tests   : 2.43% (13/536)
-----------------------------------------------------------------------------
```

Then I try to run the tests on my own and get this output after running `tsc --noImplicitAny [--module commonjs] cassandra-driver.tests.ts`

```
cassandra-driver.tests.ts(9,41): error TS7006: Parameter 'err' implicitly has an 'any' type.
cassandra-driver.tests.ts(9,46): error TS7006: Parameter 'result' implicitly has an 'any' type.
```

But I think it is an wrong implementation of the static tests.

What are the next steps that I should do?

**Comment by vvakame** [comment]
umm...
http://docs.datastax.com/en/latest-nodejs-driver-api/module-types-ResultStream.html
it is undocumented method.
I think we can remove this method from cassandra-driver when we follow the guide.

**Pull request merged**
