### PR TITLE
Add types for bun.js, a new JavaScript runtime

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
[Bun](https://bun.sh) is a new JavaScript runtime environment, npm package manager, TypeScript & JSX transpiler, JavaScript & CSS bundler, and npm `package.json` scripts runner all in one incredibly fast CLI.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package. 
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

This _does_ conflict with an existing npm package, however I am one of the collaborators of that npm package. That npm package will eventually be migrated to bun. 

The `path` and `fs` modules are mostly copied from `@types/node`. Bun has native implementations of `node:fs` and `node:path` that closely mirrors Node's API.

Some of `index.d.ts` was copied from libdom.d.ts, but I have added more comments where relevant.

I tried to avoid modifying the `tslint.json` but
- `"npm-naming"` is disabled because bun doesn't export anything currently, unless I'm misunderstanding?

If there is a way to avoid modifying `tslint.json` please do say

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
the project url seems to be wrong (at least for me it gives me 404 on GitHub).
If the project is members only (or any kind of membership/access request), it could be part of source itself, included in documentation, etc.

**Comment by Jarred-Sumner** [comment]
It is not yet a public repo but it will be soon

Anyone can get access by going to bun.sh/discord, typing “I want Bun” and clicking the GitHub repo invite link the bot generates

**Comment by Jarred-Sumner** [comment]
@peterblazejewicz what's the next step to get this merged? Sent you an invite to the repo.

If you're not comfortable with merging this until the repository is public, then I can go ahead and make it public.

**Comment by peterblazejewicz** [comment]
Can you please generate a link for someone here to review the code? thx!

**Comment by Jarred-Sumner** [comment]
> Can you please generate a link for someone here to review the code? thx!

Here you go:

- https://i.bun.sh/still-fog-15696
- https://i.bun.sh/divine-cloud-25397
- https://i.bun.sh/misty-frog-71718
- https://i.bun.sh/jolly-violet-45118
- https://i.bun.sh/tiny-block-44878
- https://i.bun.sh/billowing-feather-20346

Note that roughly none of the types listed here actually correspond to code in JavaScript or TypeScript. Bun is written in Zig and C++, and so are the runtime APIs.

There are examples in https://github.com/Jarred-Sumner/bun/tree/main/examples

**Comment by jakebailey** [comment]
Just for reference, the docs for that dtslint rule is [here](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/npm-naming.md). The version number check should work because the `npm` package is 0.0.x, so it must be the export checks like you've noted.

In this case, I think things are getting quite confused thanks to the fact that you're using someone else's existing package name for these types, when that package is still published on npm (not to mention has importers). The same lint override is used in a number of other packages, so that's not unprecedented.

I know enough Zig and C++ to probably review this monstrous PR, but, I do sort of worry about taking over a package like this, especially when these types declare ambient stuff like other runtime-y declarations.

**Review by jakebailey — CHANGES_REQUESTED** [review]
What is the plan for that npm package? Is it just going to be deprecated and made empty such that this types package can exist? Or is it going to be where the bun binary is published?

If the latter, you're going to end up having a problem because the types will bring in ambient types even though they're not intended to be used like that.

Perhaps what you need to do is have a package `bun-env` instead that defines this environment, similar to `webpack-env` (which works similarly).

---

Regarding the code itself, if you're only intending on having ambient types, then I don't think all of the exports are needed, as there's no actual import one can make directly (as you've noted). The dtslint warning can be silenced by noting that it's a non-npm package, so that's OK.

**Pull request closed without merging**
