### PR TITLE
Remove empty namespaces from linted packages

### PR DESCRIPTION
**Pull request by ghost**
Microsoft/types-publisher#259

### CODE REVIEW

**Review by ulrichheiniger — CHANGES_REQUESTED** [review]
As requested in #13537 the module declaration for chai-json-schema could be omitted:

// Type definitions for chai-json-schema 1.4
// Project: https://github.com/chaijs/chai-json-schema/
// Definitions by: Ulrich Heiniger <https://github.com/ulrichheiniger>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// <reference types="node"/>
// <reference types="chai" />

declare global {
	namespace Chai {
		export interface Assert {
			jsonSchema(value: any, schema: any, msg?: string): void;
			notJsonSchema(value: any, schema: any, msg?: string): void;
		}

		export interface LanguageChains {
			jsonSchema(schema: any, msg?: string): void;
		}
	}
}

declare function chaiJsonSchema(chai: any, utils: any): void;
export = chaiJsonSchema;

**Comment by mizunashi-mana** [comment]
👍 
LGTM for `is-windows`/`chai-oequal`

**Comment by mhegazy** [comment]
This is needed where you want to enable `import *` on a module with only `export = <function>`.

**Review by mhegazy — CHANGES_REQUESTED** [review]
this breaks `import *` users.

**Comment by RyanCavanaugh** [comment]
@mhegazy can we point them at http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y and tell them to stop doing something that doesn't work?

**Comment by mizunashi-mana** [comment]
Actually, I want to use `import *`.
However, I regarded this was DefinitelyTyped's thought, so, I agreed.

I follow this repository line.

**Comment by mhegazy** [comment]
> @mhegazy can we point them at http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y and tell them to stop doing something that doesn't work?

it does not work for ES6 modules, which are not around yet. but it does work for commonjs for instance.

**Comment by minestarks** [comment]
@andy-ms @RyanCavanaugh @mhegazy what's the conclusion?  This PR is getting stale.

**Comment by andy-ms** [comment]
I think we should not do this. Wait until we know more about `mjs`.

**Pull request closed without merging**
