### PR TITLE
spotify-web-playback-sdk: Add not_ready event

### PR DESCRIPTION
**Pull request by NeoLegends**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.spotify.com/documentation/web-playback-sdk/reference/#event-not-ready
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by NeoLegends** [comment]
To maintainers: The first commit introduces changes from the SDK's API, the second one tidies up the typings, but bumps the minimum TS version to 2.1. As such, I increased the version to 0.2, but I'm not sure if that's the right thing to do here. It may make people hesistant to update their typings, even though it'll likely affect only a very very small amount of users (who on earth is still using 2.0 !?). If not, I'll add another commit that reverts the version to 0.1 to stay semver-compatible.

**Comment by andy-ms** [comment]
The version in the header should reflect the version of the library being typed. Types aren't versioned independently of the underlying library.

**Review by mraerino — APPROVED** [review]
This looks fine 👌

**Comment by NeoLegends** [comment]
> The version in the header should reflect the version of the library being typed. Types aren't versioned independently of the underlying library.

Alright, version change reverted.

**Pull request merged**
