### PR TITLE
[node] Sort fields in IncomingHttpHeaders

### PR DESCRIPTION
**Pull request by nwtgck**
Hi, developers!

The fields in `IncomingHttpHeaders` seems to be sorted in lexical order. However, I found some of them are not sorted. So I **sorted the fields in IncomingHttpHeaders** to feel **more comfortable, consistent and readable**. All I did is just sorting of the fields of the `interface`. It should not affect any logic, I think.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
Not sure why this is needed but sure.

**Review by BrunoScheufler — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Review by kuehlein — APPROVED** [review]

**Comment by Flarna** [comment]
CI fail is unrelated, should be fixed via #32710. Just rerun CI once #32710 has been merged.

**Review by Flarna — APPROVED** [review]

**Comment by nwtgck** [comment]
@typescript-bot Sorry, I don't know what you mean. I am waiting for the merge of #32710. But it has closed.

Could you tell what I shoud do?

**Comment by Flarna** [comment]
@nwtgck Just close and reopen the PR. This should trigger CI and hopefully it's green now (it was for me yesterday evening).
I closed #32710 because the problem it should fix disappeared for some reason (maybe an update of typescript@next).

**Comment by nwtgck** [comment]
@Flarna Thanks a lot. I'll do this.

**Comment by nwtgck** [comment]
@Flarna Unfortunately it failed again...

**Pull request merged**
