### PR TITLE
formidable v3: Add form.parse() promise overload

### PR DESCRIPTION
**Pull request by karlhorky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-formidable/formidable/pull/940
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

cc @martin-badin @gboer @peterblazejewicz as code owners

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@karlhorky does it look this declaration files are fully compatible with v3 of formidable? (so v3.4 can be quickly applied and no major changes are expected)

**Comment by karlhorky** [comment]
In our codebase, this was the only change needed to upgrade to `formidable@3.4.0` - but maybe we're not using all features of Formidable.

**Review by martin-badin — APPROVED** [review]

**Comment by karlhorky** [comment]
Ready to merge

**Comment by gboer** [comment]
aren't we dropping v2 types with this merge?

**Comment by peterblazejewicz** [comment]
> aren't we dropping v2 types with this merge?

2.0.5 will be latest from v2, unless `v2` source is reintroduced:
https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package

> If you intend to continue updating the older version of a library's type declarations, you may create a new subfolder (e.g. /v2/) named for the current (soon to be "old") version, and copy existing files from the current version to it.

**Pull request merged**
