### PR TITLE
[@types/react-jsonschema-form] Change WidgetProps

### PR DESCRIPTION
**Pull request by thepocp**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by iplus26 — CHANGES_REQUESTED** [review]
Check out [Custom Widget Options](https://github.com/mozilla-services/react-jsonschema-form#custom-widget-options).
I don't think that `options` property should be an array of something. Tell me if I'm wrong.

**Comment by thepocp** [comment]
@iplus26 Sorry, it was my mistake. I added a type for other options in the new commit.

**Review by iplus26 — CHANGES_REQUESTED** [review]
1. I don't think that `value` of `EnumOption` has to be a `string`, instead, `boolean` or `number` (probably others) works as well. 
2. Why is `enumOptions can be false` particularly metioned here?

**Comment by iplus26** [comment]
3. If you define `Options` like this, `enumOptions` should be a required property (which is not true) 
```typescript
 export type Options = {
        enumOptions: EnumOption[] | false;  
        [key: string]: any;
}
```

**Comment by thepocp** [comment]
enumOptions can be false for example in TextWidget props

**Comment by iplus26** [comment]
It has been a while since last time I use the component. It will be nice if you could point out, where the docs or source code reveals the usage of `enumOptions in TextWidget props`

**Comment by thepocp** [comment]
As far as I understand:
[StringField.js#L31](https://github.com/mozilla-services/react-jsonschema-form/blob/b3fb5ae703fc6aee6a9306f4aff01d89da47add3/src/components/fields/StringField.js#L31)
[utils.js#L334](https://github.com/mozilla-services/react-jsonschema-form/blob/b3fb5ae703fc6aee6a9306f4aff01d89da47add3/src/utils.js#L334)

**Review by iplus26 — CHANGES_REQUESTED** [review]
`enumOptions` should not be `false`.

**Comment by thepocp** [comment]
I'll check it again.
Here is my case:
```javascript
const TextWidget = (props) => {
  const {options} = props; // { enumOptions: false }
  ...
};

const SelectWidget = (props) => {
  const { options } = props; // { enumOptions: [ { label: "JSON", value: "json" }, ...] }
  ...
};

const schema = {
  type: 'object',
  properties: {
    source: { type: 'string', title: 'Source' },
    type: {
      type: 'string',
      title: 'Type',
      anyOf: [
        { type: 'string', title: 'JSON', enum: ['json'] },
        { type: 'string', title: 'XML', enum: ['xml'] },
        { type: 'string', title: 'TXT', enum: ['txt'] },
      ],
    },
  },
};

...

<Form
  schema={schema}
  widgets={SelectWidget, TextWidget, ...}
  ...
/>
```

**Comment by iplus26** [comment]
> As far as I understand:
> [StringField.js#L31](https://github.com/mozilla-services/react-jsonschema-form/blob/b3fb5ae703fc6aee6a9306f4aff01d89da47add3/src/components/fields/StringField.js#L31)
> [utils.js#L334](https://github.com/mozilla-services/react-jsonschema-form/blob/b3fb5ae703fc6aee6a9306f4aff01d89da47add3/src/utils.js#L334)

I'm aware of these lines you mentioned. The `enumOptions` variable in StringField.js#L31, is a local variable, while in your definition `enumOptions` should be a property of `ui:options`, they're different things. 

The local `enumOptions` (I'll call it `localEnumOptions` below), is converted from `schema.enums`(early version supported this) by 

```js
// StringField.js#L31
const localEnumOptions = isSelect(schema) && optionsList(schema);
```

and merged into 

```jsx
// StringField.js#L39-40
<Widget options={{...options, ...localEnumOptions}} ... />
```

If the `localEnumOptions` is truthy, means the widget probably should be a "select", while if not, it should be a "text". Which means, if the local variable is `false`, it doesn't mean in your definition, the property could be `false`.

**Pull request closed without merging**
