### PR TITLE
classnames: support es6 imports

### LINKED ISSUE #9003: Module "classnames" definition does not support ES6 module definition
- [x] I tried using the latest `classnames/classnames.d.ts` file in this repo and had problems.

image

As I result I get message "Module 'classnames' has no default export".

### PR DESCRIPTION
**Pull request by ohanar**
fixes #9003

### CODE REVIEW

**Comment by JKillian** [comment]
👎  This doesn't follow the shape of the actual `classnames` JS module. It probably works correctly for you @ohanar because of some middleman transpiler (babel?) that translates default imports.

**Comment by ohanar** [comment]
So for those of us who have using babel in our pipeline, what are we expected to do?

We can't use `import classNames = require('classnames')` when targeting es6 and we can't use `import * as classNames from 'classnames'` because babel tries to translate star imports in a way that is breaks function modules. Should we just role with our own typings?

**Comment by adidahiya** [comment]
> we can't use import * as classNames from 'classnames' because babel tries to translate star imports in a way that is breaks function modules

... sounds like a Babel bug then.

**Comment by ohanar** [comment]
@adidahiya I don't know about that. There is no way to create a es6 module `foo` such that when you `import * as bar from 'foo'` you get a callable `bar`. The only issue here is that typescript and Babel disagree on how to handle commonjs modules in es6 code:

- The typescript convention is to treat the `module.exports` as the `bar` object mentioned above, and has no default object.
- Babel treats `module.exports` as the default export, and for the previously mentioned `bar, it creates a new object whose properties are shallow copies of the `module.exports` properties.

Neither of these approaches are objectively correct, which is why they both exist. However, typescript's convention is incompatible with babel's behavior.

**Comment by JKillian** [comment]
@ohanar I hear you, and you're right, how TS/Babel translate CJS to ES6 and vice versa is somewhat of a grey area as (as far as I know) there's not spec on how to do it. However, in this case, we're obliged to go with the TS way, as these definition files are targeted at TypeScript users (and not TS & Babel) users.

I'm not entirely sure of its behavior, but are you able to get things working on your end using the `--allowSyntheticDefaultImports` flag @ohanar?

**Comment by ohanar** [comment]
@JKillian Yes that works, there isn't any way that I can specify it on a module by module basis, is there?

**Comment by vvakame** [comment]
I decline this PR.
I recommend you to use `--module commonjs --target es6` options.
You can use babel with `import * as classnames from "classnames";`.

```
$ cat main.ts
import * as classnames from "classnames";

classnames('foo', 'bar');
$ tsc --module commonjs --target es6 main.ts typings/classnames/classnames.d.ts
$ cat main.js
"use strict";
const classnames = require("classnames");
classnames('foo', 'bar');
```

@adidahiya @JKillian thanks you for your comments!

**Comment by alexey-pelykh** [comment]
Time to get back to this due to [original package change](https://github.com/JedWatson/classnames/pull/105): PR #25205 or PR #25206

**Pull request closed without merging**
