### PR TITLE
Add type definition for w3c-image-capture

### PR DESCRIPTION
**Pull request by reda-alaoui**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Fixed

**Comment by sheetalkamat** [comment]
```w3c-image-capture``` does not correspond to a valid package. I dont think this is right place for the definitions. Adding @andy-ms to comment if he thinks otherwise

**Comment by andy-ms** [comment]
Have you tried contributing to TSJS-lib-generator? https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-type-definitions-for-the-dom

**Comment by reda-alaoui** [comment]
Hello @andy-ms , @sheetalkamat ,
From `TSJS-lib-generator` project `README`:

> When should a DOM API be included here?
> 
> If a DOM API is still a draft, it belongs on DefinitelyTyped. When it graduates past draft stage, it can be added here and removed from DefinitelyTyped. A feature is considered a draft if:
> 
> W3C
> 
> A Working Draft should go on DefinitelyTyped. A feature that is a Candidate Recommendation (or has passed that stage) should be added here.

ImageCapture API is still a Draft. So according to this, it belongs to DefinitelyTyped.

**Comment by andy-ms** [comment]
OK, thanks!

**Comment by reda-alaoui** [comment]
Great :+1:

**Pull request merged**
