### PR TITLE
[react] update packages to TS 2.8 and add library managed attributes

### PR DESCRIPTION
**Pull request by ferdaber**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Part 2 of this closed PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27267. Dependent on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27378.

### CODE REVIEW

**Comment by ferdaber** [comment]
cc @weswigham

**Comment by ferdaber** [comment]
@johnnyreilly Travis is failing due to the number of packages changed. The tests are causing an out-of-memory error.

**Comment by johnnyreilly** [comment]
Hmmm not sure what to suggest; this is presumably a (regrettable) limitation of our test infrastructure set-up. Is this straightforward to batch up into a number of smaller PRs?

**Comment by Kovensky** [comment]
Not really. The overwhelming majority of the changes is bumping the minimum version of the typings to TS 2.8 which is a _necessary_ change because of how the dt publisher works. Unless you mean create a bunch of PRs that do nothing besides bumping version to 2.8.

**Comment by Hotell** [comment]
Same issue occurred here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26545 and to solve it we had to increase buffer size https://github.com/Microsoft/types-publisher/pull/471

**Comment by ferdaber** [comment]
I can do that. Going by how many tests were successful before the OOM issue occurred I think two PRs should be sufficient (I can test locally for that). Thanks for the suggestions, y'all!

**Comment by tkrotoff** [comment]
@ferdaber ferdaber @Hotell 

Current [Travis CI errors](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/406981684?utm_source=github_status&utm_medium=notification) are not related to https://github.com/Microsoft/types-publisher/pull/471 (am I missing something here?):

```
=== ERRORS ===


Error in react
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react/test/index.ts:128:9
ERROR: 128:9  expect  TypeScript@next compile error: 
Type 'Validator<Context>' is not assignable to type 'Validator<string | null | undefined>'.
  Type 'Context' is not assignable to type 'string'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:103:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>


Error in recompose
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/recompose/recompose-tests.tsx:255:33
ERROR: 255:33  expect  TypeScript@next compile error: 
Argument of type 'StatelessComponent<InnerProps>' is not assignable to parameter of type 'ComponentType<OutterProps & { count: number; } & { setCount: (state: number) => number; }>'.
  Type 'StatelessComponent<InnerProps>' is not assignable to type 'StatelessComponent<OutterProps & { count: number; } & { setCount: (state: number) => number; }>'.
    Type 'InnerProps' is not assignable to type 'OutterProps & { count: number; } & { setCount: (state: number) => number; }'.
      Type 'InnerProps' is not assignable to type 'OutterProps'.
        Property 'title' is missing in type 'InnerProps'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:103:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error: The following packages had errors: react, recompose
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:121:8
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

npm ERR! Test failed.  See above for more details.


The command "npm test" exited with 1.
```

**Comment by ferdaber** [comment]
You're right! I was wondering where the recompose errors went... Regardless I'm going to close this PR when I next work on it and split it otherwise I won't be able to see the actual errors before Travis poops the bed.

**Comment by goloveychuk** [comment]
@ferdaber can we add 
```ts
type StrictifyFunctions<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => infer R
    ? (...a: A) => R
    : T[K] extends Object ? StrictifyFunctions<T[K]> : T[K]
};

..... StrictifyFunctions<Defaultize<TProps, D>>
```
This addes correct variance checking for methods. 
See https://github.com/Microsoft/TypeScript/issues/25451

**Comment by weswigham** [comment]
@goloveychuk forcing strict variance checking on every react consumer is a big break. I wouldn't do it as the same time as this addition.

**Pull request closed without merging**
