### PR TITLE
Add types for codeclimate

### PR DESCRIPTION
**Pull request by remcohaszing**
These are types for the [codeclimate specification](https://github.com/codeclimate/platform), not for a package. There is a package named `codeclimate` in the npm registry, but it was last updated 7 years ago, has been deprecated, and links to a GitHub repo whose user no longer exist.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
One can still install `codeclimate`, it's just seems to be not listed on the NPM search. The package is there, including unpackaged.com.

**Comment by remcohaszing** [comment]
Yes, the package is there. It doesn’t have a main entry point, `index.js` file, `bin` entry, nor `scripts`. I’m really not concerned about the name clash, because it doesn’t do anything and the package is now owned by npm.

**Comment by peterblazejewicz** [comment]
but there could be concerns from maintainers: using `codeclimate` squatting a possible future NPM package name. Let's ask for opinion first,

**Comment by jakebailey** [comment]
Why does this need to be on DT at all? This doesn't describe the types of an npm package, nor a runtime environment / DOM extension, nor for an ambient script like jquery or something that is included on a web page.

The only use I can see for it is that DT is just a convenient place for these to live, but why not in a proper npm package or something? Where is this being used and how?

**Comment by andrewbranch** [comment]
Adding this to my list to discuss with @sandersn when he gets back

**Review by sandersn — CHANGES_REQUESTED** [review]
I think that Definitely Typed is the wrong place for type-only packages: it's intended for typing actual Javascript code.
The easiest way for me to see that this belongs on its own is that it would actually be imported like `import { Issue } from "@types/codeclimate"` if the unrelated `codeclimate` didn't exist, but DT's intended use is always for people to import an actual package and get types from `@types` on the side.

**Comment by remcohaszing** [comment]
Ok, I will publish it outside of DefinitelyTyped then 👍

**Pull request closed without merging**
