### PR TITLE
[ejs] adjust options.root parameter

### PR DESCRIPTION
**Pull request by mshima**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mde/ejs/pull/704
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mshima thanks!
Next time, please stick to advice of adding test case(s) when changing details of popular packages.
CI tests failing atm is not related to this PR

**Comment by mshima** [comment]
Is this PR missing something? Failures are unrelated.

**Comment by mshima** [comment]
@peterblazejewicz is this PR missing something to be merged?

**Comment by peterblazejewicz** [comment]
@mshima it was stuck in the void due to failing CI tests. I"ve added a commit that seems to (when tested locally) fix the errors listed in CI tests.
You would eventually have to update the PR with recent changes from master, as it's diverged greatly from current master

**Review by peterblazejewicz — APPROVED** [review]

**Comment by mshima** [comment]
Ready to merge

**Comment by mshima** [comment]
@peterblazejewicz thanks for the help.

**Pull request merged**
