### PR TITLE
[three] Some SSAARenderPass arguments are optional

### PR DESCRIPTION
**Pull request by willstott101**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [SSAARenderPass implementation being robust to undefined for the last two arguments](https://github.com/mrdoob/three.js/blob/master/examples/jsm/postprocessing/SSAARenderPass.js#L36)

### CODE REVIEW

**Comment by Methuselah96** [comment]
@willstott101 The types for three.js live [here](https://github.com/three-types/three-ts-types). Do you mind making your PR there instead?

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. AxisHelper
1. BinaryTextureLoader
1. BoundingBoxHelper
1. CanvasRenderer
1. DynamicBufferAttribute

<details>
<summary>as well as these 27 other properties...</summary>
<p>EdgesHelper, FaceColors, Font, FontLoader, ImmediateRenderObject, JSONLoader, LensFlare, Math, MeshFaceMaterial, MultiMaterial, NoColors, ParametricGeometry, Particle, ParticleBasicMaterial, ParticleSystem, ParticleSystemMaterial, PointCloud, PointCloudMaterial, RGBFormat, SceneUtils, TextGeometry, Vertex, VertexColors, WebGLRenderTargetCube, WebGLUtils, WireframeHelper, XHRLoader</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c5c2af811582b15d079057929518a3b9fa50e795
</p>

**Comment by willstott101** [comment]
@Methuselah96 sure, will do

**Comment by willstott101** [comment]
See: https://github.com/three-types/three-ts-types/pull/197

**Pull request closed without merging**
