### PR TITLE
add typings for stevelacy/gulp-bump

### PR DESCRIPTION
**Pull request by silkentrance**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by silkentrance** [comment]
This requires the typings for stevelacy/bump-regex to be in place.

**Comment by silkentrance** [comment]
Typings for stevelacy/bump-regex are now in place. Works as expected.

**Comment by silkentrance** [comment]
Is it possible to add a dependency towards @types/bump-regex so that it will be installed when installing @types/gulp-bump?

**Comment by aozgaa** [comment]
Hey @silkentrance , you can express dependencies via a `package.json` file. See here for an example:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fb68b21bea74048f69c7aa53bac60f91141725a3/types/jsdom/package.json

**Comment by silkentrance** [comment]
@aozgaa Very good. Thank you very much.

**Comment by aozgaa** [comment]
@silkentrance Looks like our past documentation indicates the `package.json` is indeed unnecessary. So your change is good to go! Sorry about the inconvenience.

Here is the relevant [documentation](https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/):

"
Dependency Management
Many packages in the @types repo will end up depending on other type declaration packages. For instance, the declarations for react-dom will import react. By default, writing a declaration file that imports any library in DefinitelyTyped will automatically create a dependency for the latest version of that library.
If you want to snap to some version, you can make an explicit package.json for the package you’re working in, and fill in the list of dependencies explicitly. For instance, the declarations for leaflet-draw depend on the the @types/leaflet package. Similarly, the Twix declarations package has a dependency on moment itself (since Moment 2.14.0 now ships with declaration files).
As a note, only the dependencies field package.json is necessary, as the DefinitelyTyped infrastructure will provide the rest.
"

**Pull request merged**
