### PR TITLE
`react-autosuggest`: `InputProps['onChange']`: restrict event type

### PR DESCRIPTION
**Pull request by OliverJAsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: see comment in tests
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by afucher — APPROVED** [review]
👍

**Review by afucher — CHANGES_REQUESTED** [review]
🛑

**Comment by afucher** [comment]
Hey @OliverJAsh , I saw that you have another PR changing the same file (#51673).
Could you please close one of them?

**Comment by OliverJAsh** [comment]
@afucher That PR depends on this one and should be reviewed/merged separately. I think I mentioned that in the PR description. If you're OK with that, would you mind approving this so it can get merged?

**Comment by afucher** [comment]
@OliverJAsh I can approve, but the other PR contains the same changes that this one + the other changes.

**Review by afucher — APPROVED** [review]
👍

**Comment by OliverJAsh** [comment]
Ready to merge

**Pull request merged**
