### PR TITLE
[jsrsasign] Fixed jsrasign RSAKey verify signature

### PR DESCRIPTION
**Pull request by alonstern**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/kjur/jsrsasign/blob/master/src/rsasign-1.2.js#L231>
- [] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 14 other properties...</summary>
<p>MessageDigest, Mac, Cipher, ASN1HEX, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, crypto, asn1, jws, lang</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1eb59a6fad062a3e786fd4215f93bf2770e4faec
</p>

**Review by ffflorian — APPROVED** [review]
Thanks!

**Review by gabritto — CHANGES_REQUESTED** [review]
This change seems to have been made as of version 10.2 of the original library (https://github.com/kjur/jsrsasign/commit/3f970510fe4bbf69c0f9ed4b8485a275dcabe3b9). However, those DT definitions are marked as for version 9.0 (first line of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsrsasign/index.d.ts). Could you also update the version to 10.2 in that header, so that the definitions match the original library? Thanks.

**Comment by alonstern** [comment]
> This change seems to have been made as of version 10.2 of the original library ([kjur/jsrsasign@3f97051](https://github.com/kjur/jsrsasign/commit/3f970510fe4bbf69c0f9ed4b8485a275dcabe3b9)). However, those DT definitions are marked as for version 9.0 (first line of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsrsasign/index.d.ts). Could you also update the version to 10.2 in that header, so that the definitions match the original library? Thanks.

Thanks @gabritto

**Review by ffflorian — APPROVED** [review]

**Review by gabritto — APPROVED** [review]

**Comment by alonstern** [comment]
Ready to merge

**Pull request merged**
