### PR TITLE
Delete Vega typings since Vega comes with its own types.

### PR DESCRIPTION
**Pull request by domoritz**
The typings are at https://github.com/vega/vega-typings and they are required in https://github.com/vega/vega/blob/7536fb08df686170c60d7225f5ecf766644ce4db/package.json#L66.

### CODE REVIEW

**Review by pelotom — APPROVED** [review]
👋🏼

**Comment by domoritz** [comment]
👋 @pelotom

**Review by minestarks — CHANGES_REQUESTED** [review]
Could you follow the steps at  https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package and update `notNeededPackages.json` please?

**Comment by domoritz** [comment]
Thank you @minestarks. I updated the PR.

**Pull request merged**
