### PR TITLE
Add ReadonlyArray<string> as an alternative type for angular.$inject.

### PR DESCRIPTION
**Pull request by jough**
It may be prudent to make injected dependencies immutable, but we can't Object.freeze() or use the Readonly interfae for our dependency array if $inject only accepts a mutable array of strings.

### CODE REVIEW

**Comment by vvakame** [comment]
please make a small changeset.
This pull request contains other people's commits.

**Comment by thorn0** [comment]
@jough Let's make it just `ReadonlyArray<string>`. The union type doesn't make much sense there.

**Comment by andy-ms** [comment]
I agree with @vvakame and @thorn0. Please update the pull request.

**Comment by andy-ms** [comment]
@jough If you still want to do this, please make a new pull request targeting `master`.

**Pull request closed without merging**
