### PR TITLE
fixed match interface in react-router v4

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

---

The motivation for the changes are documented here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15170#issuecomment-288395136. The comment references to the original source code.

Ping to @paulvanbrenk.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Can you fix the error in the CI build?

```
=== ERRORS ===



Error in react-router
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.2/node_modules/typescript/lib/tsc.js 

test/Recursive.tsx(22,13): error TS2322: Type '{ params: { id: number; }; url: string; }' is not assignable to type 'match<{ id: number; }>'.
  Property 'isExact' is missing in type '{ params: { id: number; }; url: string; }'.
```

**Comment by donaldpipowitch** [comment]
Sure. Sorry that I missed that one!

**Comment by tkrotoff** [comment]
From my experience these parameters should stay optional.

**Comment by donaldpipowitch** [comment]
> From my experience these parameters should stay optional

Have you seen a `match` object where these properties were set to `undefined` or why do you think they should stay optional? By reading the source code I can't see a way how this can be.

But... I see something else which I need to change. `matchPath` can actually return `null` [here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js#L38) and [here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js#L44).

**Comment by donaldpipowitch** [comment]
@paulvanbrenk Tests are green 🎉

**Comment by tkrotoff** [comment]
[This is wrong](github.com/donaldpipowitch/DefinitelyTyped/commit/a0687332469bb1b804667f9900667fcc98c0c02b): you cannot change [the examples taken from React Router website](https://reacttraining.com/react-router/examples/recursive-paths) so that your modifications to index.d.ts work!

**Comment by donaldpipowitch** [comment]
> This is wrong: you cannot change the examples taken from React Router website so that your index.d.ts modifications work!

I didn't know this example was taken from the official docs and shouldn't be changed. But I looked into the example deeper now and see it is typed in a wrong way.

The properties you get when `<Person/>` is used for the [first time](https://github.com/donaldpipowitch/DefinitelyTyped/blob/fac784746d9b5339cfcc50b799c9589b726ffd08/react-router/test/Recursive.tsx#L22) are different then [when it is used recursively](https://github.com/donaldpipowitch/DefinitelyTyped/blob/fac784746d9b5339cfcc50b799c9589b726ffd08/react-router/test/Recursive.tsx#L45).

The typings currently say that the properties extend [`Partial<RouteComponentProps<{id: number}>>`](https://github.com/donaldpipowitch/DefinitelyTyped/blob/fac784746d9b5339cfcc50b799c9589b726ffd08/react-router/test/Recursive.tsx#L26). This is not true for the first usage as you don't have a `location` and `history` object either. IMHO the example in _that_ good as it suggest the [custom `match`](https://github.com/donaldpipowitch/DefinitelyTyped/blob/fac784746d9b5339cfcc50b799c9589b726ffd08/react-router/test/Recursive.tsx#L22) is the same as the `match` you get [passed by a `<Route/>`](https://github.com/donaldpipowitch/DefinitelyTyped/blob/fac784746d9b5339cfcc50b799c9589b726ffd08/react-router/test/Recursive.tsx#L45). I'd rewrite the example to use `<Person/>` inside of a `<Route/>` on startup, too. But if I'm not allowed to do that, I'll change the interfaces.

**Comment by donaldpipowitch** [comment]
I have to say I _think_ the example is not good, but I reverted the test to the original example and just changed TypeScript-related code. Because I think the API is used in the wrong way in the example we need at least [one cast with `as`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15314/commits/0d06ba4519bcd8a49c3eb1242fec1f11ff567096#diff-ddabab4417cb3cab3037f90945246740R52).

I also [changed how the `component`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15314/commits/0d06ba4519bcd8a49c3eb1242fec1f11ff567096#diff-0f71fe6a8f24d2e8195a1b467fe555cdR55) property of `<Route/>` was typed. I don't know why it used `PartialRouteComponentProps`, but it now uses `RouteComponentProps` just as the properties `render` and `children`.

Looking into the source code the [`component`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L105), the [`render`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L107) and the [`children`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L110) all get the same `props` object.

**Comment by tkrotoff** [comment]
@donaldpipowitch

> I didn't know this example was taken from the official docs

It's written in [test/README.md](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-router/test/README.md)

> I'd rewrite the example [...]. But if I'm not allowed to do that, I'll change the interfaces.

If you think an example is not good, you should contact the React Router authors.

Anyway...

> [The props] when <Person/> is used for the first time are different [than] when it is used recursively

You are right, I've made a mistake: the first time, Person is called with `match` (specified by hand) and after that automatically with `match`, `location` and `history` due to React Router context thanks to `<Route component={Person} />`.

You can fully remove `PartialRouteComponentProps` from react-router/index.d.ts and react-router-dom/index.d.ts

**Comment by donaldpipowitch** [comment]
Removed `PartialRouteComponentProps ` 👍

**Comment by donaldpipowitch** [comment]
Fat finger...

**Comment by tkrotoff** [comment]
@paulvanbrenk good for me :+1

**Comment by donaldpipowitch** [comment]
Thank you  💪

**Pull request merged**
