### PR TITLE
Merge 20dec

### PR DESCRIPTION
**Pull request by ghost**
`git checkout -b merge_20dec` and `git merge origin types-2.0`, then fix merge conflicts.

Undid change to `enhanced-resolve` to use "include" instead of "files" since types-publisher needs "files". Filed Microsoft/types-publisher#238.

### CODE REVIEW

**Comment by thgreasi** [comment]
:+1:

**Comment by e-cloud** [comment]
@andy-ms , I'm glad that these updates are merged into master branch. 

IMHO, there is one concern about the merge strategy. It seems like you squash many PR into one commit. That may be convenient for batch merging. But it would somehow break down the git blame flow when someone wants to track down the changes from git history.

**Comment by e-cloud** [comment]
@andy-ms It's strange that these updated types haven't been published. Wouldn't they be published in short time once merged?

**Comment by andy-ms** [comment]
Sorry, did a squash by mistake. I'll fix it in the next merge.

**Pull request merged**
