### PR TITLE
Update Joi's ValidationOptions and AnySchema interfaces

### PR DESCRIPTION
**Pull request by ptrckc**
See validate options: https://github.com/hapijs/joi/blob/master/API.md#validatevalue-schema-options-callback

And any.error: https://github.com/hapijs/joi/blob/master/API.md#anyerrorerr

### CODE REVIEW

**Comment by vvakame** [comment]
Travis CI failed but it is our fault.
types-2.0/HEAD is back to green now(maybe...

**Comment by remolueoend** [comment]
I just stumbled upon the interface `Rules` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/06412ff108713dcfc75fd7c4887e5d241187bbb4/joi/joi.d.ts#L762), which should implement the property `description` as `optional` instead of `required`. See the docs at https://github.com/hapijs/joi/blob/master/API.md#extension under paragarph extension/rules/description.

@ptrckc Could we include that single change into this PR or should I open a new one?

**Comment by ptrckc** [comment]
@remolueoend I've updated the pull request with that change

@Bartvds @laurence-myers @cglantschnig @DavidBR-SW @GaelMagnan Could you review this PR?

**Comment by vvakame** [comment]
sorry for late!

**Pull request merged**
