### PR TITLE
[@types/jquery] Improve type for find function

### LINKED ISSUE #31891: [@types/jquery] Cannot specify type for variable
- [x] Authors: @leonard-thieu
@borisyankov
@choffmeister
@Steve-Fenton
@Diullei
@tasoili
@jasons-novaleaf
@seanski
@Guuz
@ksummerlin
@basarat
@nwolverson
@derekcicerone
@AndrewGaspar
@seikichi
@benjaminjackman
@s093294
@JoshStrobl
@johnnyreilly
@DickvdBrink
@King2500
@terrymun

### My code example ###
```js
/** @type {JQuery<HTMLBodyElement>} */
const $body = jQuery('body')
const firstAnchor = $body.find('a').first()
```
`firstAnchor` has `JQuery<HTMLBodyElement>`

image

And if I try change type then I get error:
```
Type 'JQuery<HTMLBodyElement>' is not assignable to type 'JQuery<HTMLAnchorElement>'.
  Type 'HTMLBodyElement' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 20 more.ts(2322)
```
image

How do I specify the types for variables that do not cause errors?

### LINKED ISSUE #41999: [jquery] Problem when using JQuery with generic typing
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x]  Authors: @leonard-thieu @borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @benjaminjackman @s093294 @JoshStrobl @johnnyreilly @DickvdBrink @terrymun

I tried the following and assume that the return type of the `find` method is wrong:
```ts
let $element: JQuery<HTMLFormElement> = $('.myForm');
$element.find('.child') // returns JQuery<HTMLFormElement> but should be JQuery<HTMLElement> or similar
// consequence:
$element.find('input.child').get(0) // returns HTMLFormElement which is wrong when you try to access Input-specific properties.

$element.find('li') // should be JQuery<HTMLLIElement> 
```
Current definition:
```ts
interface JQuery<TElement = HTMLElement> extends Iterable<TElement> {
    //...
    find(selector_element: JQuery.Selector | Element | JQuery): this;
    //...
}
```
First I suggest to change the return type for `find` method from `this` to `JQuery<TDecendent = HTMLElement>` if that is possible... ?

Maybe we can also have overloaded find methods with some specific cases when using explicit HTML tag-names like:

```ts
$element.find('li') // JQuery<HTMLLIElement>
$element.find('tr') // JQuery<HTMLTableRowElement>
$element.find('input') // JQuery<HTMLInputElement>
// ... and so on for all know HTMLElement sub types/tags ?
```
with
```ts
find('li'): JQuery<HTMLLIElement>;
find('tr'): JQuery<HTMLTableRowElement>;
find('input'): JQuery<HTMLInputElement>;
// ... and so on...
```

What do you think?
Are there any other similar methods where this problem applies?

### LINKED ISSUE #43693: [styled-components] Support `shouldForwardProp` option
The latest version of styled-components, 5.1.0, has [added support for `shouldForwardProp`](https://github.com/styled-components/styled-components/releases/tag/v5.1.0), which works slightly different than in `emotion`:

```tsx
const Comp = styled('div').withConfig({
  shouldForwardProp: (prop, defaultValidatorFn) => !['filterThis'].includes(prop),
})`
  color: red;
`;

render(<Comp filterThis="abc" passThru="def" />);

// Renders: <div className="[generated]" passThru="def"></div>
```

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @surgeboris @sandersn @Jessidhia @smockle @Igorbek @Igmat @Lavoaster @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2

### PR DESCRIPTION
**Pull request by martin-badin**
Closes #41999 
Closes #31891

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://api.jquery.com/find/>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by Steve-Fenton — CHANGES_REQUESTED** [review]
Thank you for this submission.

Although this mechanism is convenient, it does not result in correctness.

The type argument is being used to force-type results that are not guaranteed to be of the passed type.

    $('p').find<HTMLSpanElement>("a")

Instead of using a generic type, the result should be 

     JQuery<HTMLElement>

This will encourage callers to narrow the type with a type guard, ensuring they have the expected kind of element.

This is particularly the case with non-tag selectors.

**Comment by martin-badin** [comment]
In the current solution, we don't have an option to change the type of the second element. For example.
```javascript
$<HTMLParagraphElement>('p').find("a")
```
the second element would be the same as the first element (HTMLParagraphElement). That is bad.
We can use these options.
```javascript
$<HTMLAnchorElement>('p').find("a")
// ....
const anchors = $('p').find("a") as JQuery<HTMLAnchorElement>
```
but I mean all options are bad.

@Steve-Fenton  What do you prefer if we want to change the type of the second element?

**Comment by Steve-Fenton** [comment]
I believe the correct solution to this is:

      find(selector: JQuery.Selector | Element | JQuery): JQuery<HTMLElement>;

This fixes the bug, which is the assumption you'll get back the same type as the parent without introducing the problem with a type argument that may well be wrong.

Also, bear in mind that some the code in the bug reports is suspicious, for example:

    let $element: JQuery<HTMLFormElement> = $('.myForm');

An element with a class of myForm is not guaranteed to be an HTMLFormElement. There should be a type guard to narrow from HTMLElement to HTMLFormElement.

**Comment by martin-badin** [comment]
I updated the PR. 
My solution is the same as yours but I can change the return type if I need that.
```typescript
// old
find(selector: JQuery.Selector | Element | JQuery): JQuery<HTMLElement>;

// new
find<T extends HTMLElement>(selector_element: JQuery.Selector | Element | JQuery): JQuery<T>;
```

**Comment by Steve-Fenton** [comment]
Hi Martin,

Fundamentally, I don't feel my concerns have been understood or addressed. Surviving a type argument, whose sole purpose is to force a type that is not correct, is not something I can approve.

The return type should be the wider (correct) type. If you want to return narrower types, you could achieve it with overloads, which would be correct as passing 'p' could return HTMLParagraphElement.

**Review by Steve-Fenton — APPROVED** [review]

**Comment by Steve-Fenton** [comment]
@martin-badin thank you for this update. Looks great to me.

**Comment by nat42** [comment]
As per issue 43977 this fails to compile (TS2304 Cannot find name 'SVGElementTagname') in our downstream project which got this merged PR through npm.

**Comment by martin-badin** [comment]
Hi, this PR are using `SVGElementTagNameMap`, not `SVGElementTagname`. I am using this package in my project and there it works fine without errors.

**Comment by ishansharma2912** [comment]
Hi @martin-badin  , I am also started getting this error while creating a build of Angular project. 
With old node modules, everything works fine but if I reinstall them, then, in jquery.d.ts file, I notice some changes like:-

`find<K extends keyof HTMLElementTagNameMap>(selector_element: K | JQuery<K>): JQuery<HTMLElementTagNameMap[K]>;`
`find<K extends keyof SVGElementTagNameMap>(selector_element: K | JQuery<K>): JQuery<SVGElementTagNameMap[K]>;`
`find<E extends HTMLElement>(selector_element: JQuery.Selector | E | JQuery<E>): JQuery<E>;`

Due to these, I am getting below error:-
Capture

**Comment by martin-badin** [comment]
Hi @ishansharma2912, which version of TS are you using?

**Comment by ishansharma2912** [comment]
Hi @martin-badin , My project is in Angular5 and typescript version is :- 

`"typescript": "~2.5.3",
`

**Comment by Steve-Fenton** [comment]
If anyone is experiencing an issue with this, it would help a lot if they can share an example of their code. The previous behaviour was erroneous and you might be depending upon a bug. We can advise if you share your examples.

**Comment by martin-badin** [comment]
@ishansharma2912 Please, can you try to add TS version 2.7. I found that `SVGElementTagNameMap` was added there.

**Comment by ishansharma2912** [comment]
Hi @martin-badin , 2.7 still gives the same error. 
To overcome this issue, I have decreased my `@types/jquery` version to `3.3.31` and now it works fine. Earlier, I was using `3.3.35`

BTW, Thanks for your quick response!

**Comment by martin-badin** [comment]
I think you have a wrong version of typescript. If you don't need to update jquery types so please use the older version of this package.

Here was added `SVGElementTagNameMap` https://github.com/microsoft/TypeScript/issues/14783

I tried different versions of typescript. Version 2.7.2 works fine but 2.4.1 doesn't work. Here are examples.

https://www.typescriptlang.org/play/?ts=2.7.2#code/MYewdgzgLgBBBuBzAXDA1gUwJ4gGYwGUA1AcQFEAbDAWwzCgBUBDRAOSdoFkmAHGAXhgAiBIiFA

https://www.typescriptlang.org/play/?ts=2.4.1#code/MYewdgzgLgBBBuBzAXDA1gUwJ4gGYwGUA1AcQFEAbDAWwzCgBUBDRAOSdoFkmAHGAXhgAiBIiFA

**Comment by martin-badin** [comment]
@Steve-Fenton Should I change the typescript version of this package?

**Comment by babielmam** [comment]
We get an error with this code:
```
...find(document.activeElement)
```
document.activeElement is of type Element. With the new version of the @types/jquery, only HTMLElement is allowed.

**Comment by martin-badin** [comment]
Hi @babielmam, I created fix for your reported issue.

**Comment by Steve-Fenton** [comment]
This slightly opens a can of worms, because the current implementation of the core JQuery interface uses HTMLElement.

Really, the question needs to be asked... can you select other specialisations of Element and, if so, should we be correcting HTMLElement on the core JQuery interface (with the various knock on effects that may have).

I think we should focus on the first part of this question initially... and once we know what is correct we can discuss how much of a shock wave we might cause to make the definition correct.

**Comment by martin-badin** [comment]
I added back `Element` because there was before my changes.

I agree with you. The core of JQuery uses HTMLElement. The HTMLElement is extended from the Element so we can use Element as the base type. 

There is a lot of space to improve the types.

I can create PR but I need to know what is better.

**Comment by Steve-Fenton** [comment]
I've made a call for discussion, so we'll see what other views come in and then decide. It's worth spending a bit of time to get the call right on this one.




Sent from Outlook Mobile







On Mon, Apr 20, 2020 at 7:01 PM +0100, "martin-badin" <notifications@github.com> wrote:















I added back Element because there was before my changes.


I agree with you. The core of JQuery uses HTMLElement. The HTMLElement is extended from the Element so we can use Element as the base type.


There is a lot of space to improve the types.


I can create PR but I need to know what is better.

**Comment by Steve-Fenton** [comment]
@leonard-thieu @borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @benjaminjackman @s093294 @JoshStrobl @johnnyreilly @DickvdBrink @King2500 @terrymun

We could really use some input here...

An early assumption that jQuery returns an HTMLElement wrapped in the jQuery object is incorrect, it should be Element (the more abstract type that sits beneath HTMLElement, SVGElememt, etc).

Correcting this is likely to cause downstream problems with anyone who is working exclusively against HTMLElements and who is therefore benefiting from the incorrect assumption. They will get warnings about all the cases they depend on HTMLElement members that don't exist on Element.

Do we proceed to make the change, perhaps providing an alternate version of the file for those that need to depend on the incorrect version?

Is there a solution that won't be as drastic?

Thanks for your thoughts!

Steve

**Pull request merged**
