### PR TITLE
Update definitions for react-intl and react-intl-redux

### PR DESCRIPTION
**Pull request by LKay**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@Kallikrein @isman-usoh @gyzerok @ericanderson can you please review this change

**Comment by Kallikrein** [comment]
- I can't tell for the whole commit, but I noticed breaking and highly incorrect rewrites in the code.
- The PR is ~almost~ a full rewrite, the diff is irrelevant. It should have a smaller scope.
- What is the PR for ? There is no clear purpose, neither in the PR description nor in the commit.

A big no for me.

**Comment by LKay** [comment]
About the changes:

- First of all it follows the current standard for definitely typed by not using `declare module` statement. 
- Inherits global `Intl` interfaces where applicable.
- Fixes incorrect `Locale` interface
- Defines what actually is exported by library public api https://github.com/yahoo/react-intl/wiki

**Comment by LKay** [comment]
@Kallikrein ^

**Comment by Kallikrein** [comment]
@LKay 
- The current types are working for now, why do you need to update ?
- Can you split your modifications into more atomic and local rewrites ? You are replacing a whole file with a totally different one with no clear intent.

An example that is rewritten (my contribution, latest commit)

```typescript
function injectIntl<T>(component: React.ComponentClass<InjectedIntlProps & T> | React.StatelessComponent<InjectedIntlProps & T>): React.ComponentClass<T>;
```

Your rewrite:

```typescript
declare function injectIntl<Props>(component: ComponentConstructor<Props>, options?: InjectIntlConfig): ComponentClass<Props & InjectedIntlProps>;
```

You definition is wrong : the function argument, or 'inner component' has intl props injected, and the function return, or 'outer component' does not.
I don't say I don't agree to your PR : mine is wrong too, as your type indicates, there is a second 'options' arg I had no hint about.

But if I had not searched and checked you had rebased the latest commit, I would have had no clue you have actully rewritten a definition.

It's the same for the whole file, since there is no relevant diff, everything might be rewritten and I have no way to tell except to search and check for all... The whole point of history,  diff and blame is lost.

**Comment by LKay** [comment]
@Kallikrein 

Actually the signature for the HOC is more clear right when you look and the definition, I think. There is no guarantee that the input component has already ` InjectedIntlProps` as part of its own. The output will have this, however injected transparently to the input component. If you would like to enforce proper props the signature should look like (which is kind like you wrote):
```typescript
declare function injectIntl<Props extends InjectedIntlProps>(component: ComponentConstructor<Props>, options?: InjectIntlConfig): ComponentClass<Props>;
```
But interface `InjecteIntlProps` has all injected properties optional (to allow easy extend final props type/interface) so there is no gain in that. Anyway signature included in the update will still be corret for anything that used the previous one (it won't break anything).

**Comment by Kallikrein** [comment]
Your signature is still incorrect.

Output component props do not extend InjectedProps.
That would mean you would have to provide intl prop to your component to have it validate type checkings, wich is the precisely conflicting with the role of the decorator.

My problem is not on this specific point though, but with your whole PR.

Your are not iterating on the actual code, **you are pushing your own version**.  
You don't reuse already written types and introduce breaking changes.

I still reject your PR as far as git PR best practices are concerned.

---
I invite you to split your refactoring in atomic commits with clear intent.

Since you are using your definitions, I guess you are not using the community ones.
Why would you want to override them ?

Start using the DefinitelyTyped definitions, and when you have an actual issue, propose a fix and not a 100% refactoring from the ground up.

**Comment by gyzerok** [comment]
I agree here with @Kallikrein - there is no sense in changing type names so other people will get breaking changes in there code.

And it really make sense to make any contributions as small PR because they are much easier to review and insure that they are correct.

**Comment by LKay** [comment]
I will close this PR and address the changes to the existing typings in the new one as some types in current definitions are incorrect.

**Comment by LKay** [comment]
The new PR is up #15137

**Pull request closed without merging**
