### PR TITLE
[WS] Fix "this" context on "on" functions

### PR DESCRIPTION
**Pull request by orblazer**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Please provide a url motivating the changes and update the chackbox above. I'm confused as to why the listener callbacks should must bind `this` to a Websocket.

**Comment by orblazer** [comment]
When we bind `this` in callbacks fix the listener when define an function like this :

```ts
function onMessage (data: WebSocket.Data) {
 this.send(data)
}
[...]
webSocket.on('message', onMessage)
```

Without `this` bind the function make error because `this`context is not defined, now with that, this error is fixed.

**Comment by minestarks** [comment]
Authors @loyd @elithrar @mlamp @TitaneBoy could you review?

**Comment by sandersn** [comment]
Agreed, for a change like this that could add new errors, I’d like some experts to review.
@loyd @elithrar @mlamp @TitaneBoy can you take a look?

@orblazer alternatively, could you provide a link to documentation explaining what `this` is for the `on` callback parameters?

**Comment by orblazer** [comment]
`this` parameter is here : http://www.typescriptlang.org/docs/handbook/functions.html#this-parameters.

**Comment by sandersn** [comment]
No, I mean some documentation saying that the type of `this` in the callback to `Websocket.on` is of type `Websocket`.

**Comment by orblazer** [comment]
The source code : https://github.com/websockets/ws/blob/master/lib/websocket.js#L715

**Comment by sandersn** [comment]
Here's [an example the uses `this` from the documentation](https://github.com/websockets/ws#how-to-detect-and-close-broken-connections):

```js
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080 });
function heartbeat() {
  this.isAlive = true;
}
wss.on('connection', function connection(ws) {
  ws.isAlive = true;
  ws.on('pong', heartbeat);
});
```

Based on the type of `WebSocket.on('connection',...)`, I think that's good enough proof that `this: WebSocket`.

**Pull request merged**
