### PR TITLE
Fix ErrorCallbackDelegate signature

### PR DESCRIPTION
**Pull request by derekfinlinson**
The ErrorCallbackDelegate for the `then` methods should accept an error object rather than errorCode and message. Also updated the SuccessCallbackDelegate to have an optional Page.Lookup value parameter since only the Xrm.Utility.openQuickCreate callback passes a parameter.

https://msdn.microsoft.com/en-us/library/dn481607.aspx#BKMK_dataSave
https://msdn.microsoft.com/en-us/library/jj602956.aspx#BKMK_openQuickCreate

### CODE REVIEW

**Comment by daryllabar** [comment]
I believe the SuccessCallbackDelegate is wrong:

> The function that will be called when a record is created. This function is passed an object as a parameter. This object has a savedEntityReference property with the following properties to identify the record created:
> entityType: the logical name of the entity.
> id: A string representation of a GUID value for the record.
> name: The primary attribute value of the record created.

According to the above, this:

``` 
export` type SuccessCallbackDelegate = ( savedEntityReference?: Page.LookupValue ) => void;
```

Should be:

```
        export interface SuccessCallbackObject
        { 
            savedEntityReference: Page.LookupValue;
        }

        /**
         * Called when the operation is successful.
         */
        export type SuccessCallbackDelegate = (object?: SuccessCallbackObject ) => void;
```

**Comment by 6ix4our** [comment]
@daryllabar Are you going to make another PR with that change, instead?

**Review by 6ix4our — APPROVED** [review]
These changes meet with the agreed upon specification around this method.

**Comment by 6ix4our** [comment]
@derekfinlinson Please update the xrm-tests as part of this PR.

**Comment by derekfinlinson** [comment]
@daryllabar Good catch. @6ix4our I updated the signature and the test

**Review by 6ix4our — APPROVED** [review]
Tests adjustment approved.

**Pull request merged**
