### PR TITLE
Add logger function to video.js Log interface

### PR DESCRIPTION
**Pull request by ckybonist**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### Description
Add `logger` function in `interface Log {}`.

### CODE REVIEW

**Review by joeflateau — CHANGES_REQUESTED** [review]
Please update this so that it only has changes related adding the logger function and not the formatting changes. You may have to turn off your code formatter

**Comment by ckybonist** [comment]
> Please update this so that it only has changes related adding the logger function and not the formatting changes. You may have to turn off your code formatter

@joeflateau Ok, I'll fix it. Just follow the contribution guideline in README though

**Review by joeflateau — CHANGES_REQUESTED** [review]
Thank you, I do understand the guidelines, but it'd be better to reformat the code in a PR for that specifically rather than muddying this PR with unrelated changes.

createLogger was added in videojs 7.3 so please also bump the version up from 7.2 at the top of this file. and also add a test for createLogger, also remove the "Definitions by: [name]" from the jsdoc comment near createLogger, you should instead add your name to the top of the file w/ the rest of us.

**Comment by ckybonist** [comment]
Added a test function, but I don't know how to verify the log outputs, only pass `npm run test`...

**Comment by joeflateau** [comment]
@ckybonist you're doing that right. the test file doesn't actually get run, it's just used as syntax that should work w/ the typings (so there's no actual phase of verifying the log output). But, please revert the whitespace/formatting changes in the test file, the linter doesn't like the spaces. See the output here: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/601907814

**Comment by ckybonist** [comment]
> @ckybonist you're doing that right. the test file doesn't actually get run, it's just used as syntax that should work w/ the typings (so there's no actual phase of verifying the log output). But, please revert the whitespace/formatting changes in the test file, the linter doesn't like the spaces. See the output here: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/601907814

Fixed weird whitespace, please check

**Review by joeflateau — APPROVED** [review]

**Pull request merged**
