### PR TITLE
Raven: add `shouldSendCallback`

### PR DESCRIPTION
**Pull request by dcherman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://docs.sentry.io/clients/node/config/
https://github.com/getsentry/raven-node/blob/d359ff776dd1866351822384d0127b5c5c094141/lib/client.js#L446-L448
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by scttcper** [comment]
You have setShouldSendCallback returning `this` instead of `Client`. If there's no difference lets keep them all the same.

**Comment by dcherman** [comment]
@scttcper So there actually is a difference; using `this` allows the returned type to be polymorphic, so people could inherit from `Raven.Client` and have any additional API available on the returned object without requiring an additional cast.

It's actually a bug that the other methods *don't* do this, it's just that inheriting from Raven is probably incredibly uncommon, so it's never been noticed.

**Comment by scttcper** [comment]
Neat! Didn't know that. Want to correct the others then?

**Comment by dcherman** [comment]
Sure, I'll add another commit doing so.  1 minute.

**Comment by dcherman** [comment]
@scttcper So I actually ended up fixing a multitude of problems.  There was some non-existent API defined in the typings, and the return types for `wrap` and `context` were wrong; they were returning `void` whereas they actually do return something.

One change that I did not make since I'm not all that familiar with typing files yet is that the default value of the module is just an instance of `Client` with a couple additional properties bolted on.  Rather than repeating the entire API, it would be good to do something like `export default = new Client()` or something to DRY that up and make the typings less prone to errors/inconsistencies.

**Comment by scttcper** [comment]
👍 Lets get these changes in.

I wasn't sure how to avoid that repeated code when I first published. I guess you're right. It does seem to make a `Client()` as default export with some stuff pumped in. Could be tricky in the typings file.

**Pull request merged**
