### PR TITLE
urijs types: add function overloads for search and query

### PR DESCRIPTION
**Pull request by XVincentX**
Referenced here:

https://medialize.github.io/URI.js/docs.html

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## urijs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/urijs@latest/))
was missing the following properties:
1. version
1. protocol_expression
1. idn_expression
1. punycode_expression
1. ip4_expression

<details>
<summary>as well as these 19 other properties...</summary>
<p>ip6_expression, find_uri_expression, findUri, defaultPorts, hostProtocols, invalid_hostname_characters, domAttributes, getDomAttribute, characters, decodePath, decodeUrnPath, recodePath, recodeUrnPath, buildQueryParameter, setQuery, hasQuery, ensureValidHostname, ensureValidPort, noConflict</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 39564e4a5b1f1f90313db7af78001ca09e2b3cdb
</p>

**Review by marcelltoth — CHANGES_REQUESTED** [review]
A few suggestions:
1. The dataset's type is `{ [key: string]: string | string[]; }` (or `{ [key: string]: string | string[] | undefined; }`, depending on your preference for indexers). Check the example above the callback function examples.
2. Will you also add the overload that takes the data map? `uri.search({ foo: "bar", hello : ["world", "mars"] });` This is currently typed as `object` but that is way too broad, if you are typing the data map anyway, we could utilize that to replace that ugly `object` in there.
3. I'd probably be nice to extract the type of the datamap into a type we export.

**Review by marcelltoth — APPROVED** [review]
Looks good now!

**Review by marcelltoth — APPROVED** [review]

**Comment by XVincentX** [comment]
Ready to merge

**Pull request merged**
