### PR TITLE
Removed typings for spotify-web-api-js

### PR DESCRIPTION
**Pull request by skovmand**
This is a PR to remove spotify-web-api-js typings because they are now integrated in the spotify-web-api-js package.

### CODE REVIEW

**Comment by vvakame** [comment]
thank you for your contributions.
Could you send this change to `types-2.0` branch?
please check this document.
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package
We are working in `types-2.0` branch mainly.
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

**Comment by skovmand** [comment]
Sure, will do that.

**Comment by vvakame** [comment]
@skovmand `types-2.0` will merge into master. but I don't not when it happens.
Do you want to remove from master immediatly?
please ping me again when #12232 is merged.

**Comment by skovmand** [comment]
I think it should be removed now, because it is outdated.

**Comment by skovmand** [comment]
I have commented on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12232 now, it should be ready

**Pull request merged**
