### PR TITLE
fix: add PropsWithChildren to ExoticComponent

### PR DESCRIPTION
**Pull request by maddhruv**
Extends `ExoticComponent` (`memo`) with `PropsWithChildren`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by eps1lon** [comment]
We actually want to remove implicit children since not every component handles children. Could you clarify what you want to accomplish here by adding a test?

**Comment by maddhruv** [comment]
@eps1lon Just like how `FunctionComponent` accepts props with children, wanted to make sure `ExoticComponent` also has the same nature.
Faced a problem while using `React.memo` and I explicitly didn't declare the `children` prop so had to add it manually.

> We actually want to remove implicit children

If that is the story, we should remove it from the `FunctionComponent` as well

**Comment by eps1lon** [comment]
> If that is the story, we should remove it from the FunctionComponent as well

It's a breaking change and one that impacts a lot of code. We have the loose plan of removing them when react 17 comes out to align breaking changes. Until then we don't want to repeat our mistakes.

**Comment by maddhruv** [comment]
> Until then we don't want to repeat our mistakes.

can we not release this as a patch, was causing me trouble
now I have to explicitly write type for `children`

**Comment by eps1lon** [comment]
That is the point. You handle children explicitly so you should type them explicitly.

**Comment by maddhruv** [comment]
Then what about the `FunctionComponent` can we remove from there as well or will remove when React 17 lands

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Marking as changes requested until @eps1lon's concerns are satisfied.

**Comment by maddhruv** [comment]
@eps1lon Can you have a look at it again?

**Review by eps1lon — CHANGES_REQUESTED** [review]
Still rejecting since we don't want to add more implicit children. We will eventually remove them and don't want to add more features that will be eventually removed.

**Pull request closed without merging**
