### PR TITLE
github-electron showOpenDialog() should return string[]

### PR DESCRIPTION
**Pull request by bradacina**
The showOpenDialog() function returns string[] as per https://github.com/atom/electron/blob/master/docs/api/dialog.md

### CODE REVIEW

**Comment by rhysd** [comment]
:+1: (Adding test for this is better)

**Comment by jedmao** [comment]
:+1: agree with @rhysd

**Comment by bradacina** [comment]
i'll look into it then

**Comment by bradacina** [comment]
Actually I'm lost. The test file is full of "commands" but I don't see any asserts or verification that things are indeed happening as they should. Eg:
https://github.com/bradacina/DefinitelyTyped/blob/master/github-electron/github-electron-main-tests.ts#L68 

Is the test just going through a series of operations and if there are any errors thrown the test fails?

Thanks in advance.

**Comment by jedmao** [comment]
TypeScript definition tests aren't the typical tests that you are used to. There are not necessarily any asserts or anything like that. It's only meant to compile w/o errors.

See http://definitelytyped.org/guides/contributing.html#tests

**Comment by bradacina** [comment]
Ah makes sense. Thank you for the info.

**Comment by bradacina** [comment]
PR updated. Not sure if we want more detailed tests.

**Comment by jedmao** [comment]
Works for me! :+1:

**Comment by rhysd** [comment]
:+1:

**Comment by bradacina** [comment]
WTB merge, offering 0.00001 BTC

**Comment by horiuchi** [comment]
@bradacina Thanks mate!
@rhysd @jedmao Thanks for review!

**Pull request merged**
