### PR TITLE
Update react-select types

### PR DESCRIPTION
**Pull request by Slessi**
Update the types for `getOptionLabel`, `getOptionValue`, `formatGroupLabel` to use the `OptionType` generic as appropriate

> *Note*: The "builtin" function for `isOptionDisabled` does not appear to match the signature of the function you could potentially provide, so I left that one as is. It still uses generics so its fine.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by claasahl — APPROVED** [review]
Thanks for your contribution, @Slessi

**Comment by oliverwhk** [comment]
May I know which specific version of "react-select" does this change reflect? I'm using latest 2.1.1 and can't find ts definition for <AsyncSelect>

Thanks.

**Comment by claasahl** [comment]
Hi @oliverwhk 

The latest `react-select` definitions are still based on v2.0. The `theme`-property has already been added, but most changes from v2.1 have yet to be addressed.

**Comment by oliverwhk** [comment]
@claasahl Thanks for clarifying.

**Pull request merged**
