### PR TITLE
[react] added `width` attribute to TableHTMLAttributes, TdHTMLAttributes interfaces

### PR DESCRIPTION
**Pull request by hellatan**
originally from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44218

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stackoverflow.com/questions/40093655/how-do-i-add-attributes-to-existing-html-elements-in-typescript-jsx/56109822#56109822 - Adding this gets around having to augment this interface in the consuming project
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I couldn't run the tests from the root of DefinitelyTyped locally. I ran `npm test` after `npm install` but then this error was thrown:

```
Error: In package.json: Dependency jest-cucumber not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/library` to `namespace__library` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:216:19)
    at combineDataForAllTypesVersions (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:98:37)
    at Object.getTypingInfo (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:24:24)
    at /Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser-worker.ts:18:30
    at Object.logUncaughtErrors (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:99:38)
    at process.<anonymous> (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser-worker.ts:16:9)
    at process.emit (events.js:210:5)
    at process.emit (/Users/daletan/projects/DefinitelyTyped/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Error: Parsing failed.
    at fail (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:307:20)
    at ChildProcess.<anonymous> (/Users/daletan/projects/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:295:21)
    at ChildProcess.emit (events.js:210:5)
    at finish (internal/child_process.js:861:14)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! Test failed.  See above for more details.
```

But I modified the `@types/react` locally in my node_modules and the type checker passed with this addition.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Did you create this from the latest `master`?

**Comment by hellatan** [comment]
> Did you create this from the latest master?

I rebased this on top of the latest master.

**Comment by hellatan** [comment]
I just created a new branch (with the same name) off of master so 🤞... this is getting a little annoying haha

**Comment by hellatan** [comment]
@eps1lon i'm really confused by this error:
```
Error in react
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react/test/index.ts:464:1
ERROR: 464:1  expect  TypeScript@3.1 expected type to be:
  HTMLDivElement
got:
  {}
ERROR: 465:1  expect  TypeScript@3.1 expected type to be:
  SVGSVGElement
got:
  {}
```
have you seen this before? I'm also really confused why the `react-bootstrap/undefined` error keeps on happening.

**Comment by ferdaber** [comment]
this looks like this might be a regression from TS 3.9.

**Comment by hellatan** [comment]
@ferdaber i created an issue with the TypeScript project https://github.com/microsoft/TypeScript/issues/38794

**Comment by hellatan** [comment]
i'm so at a loss as to why all of this unrelated stuff is breaking. I rebased on top of the latest master as well but am getting these errors now:

```
Error in agiledigital__mule-preview
Error: Cannot find module '/home/travis/.dts/typescript-installs/4.0/node_modules/typescript'
...
Error in airbnb-prop-types
Error: Cannot find module '/home/travis/.dts/typescript-installs/4.0/node_modules/typescript'
...
Error in alt
Error: Cannot find module '/home/travis/.dts/typescript-installs/4.0/node_modules/typescript'
```

**Comment by eps1lon** [comment]
> i'm so at a loss as to why all of this unrelated stuff is breaking.

This is just something you have to get used to with DefinitelyTyped. I can only recommend developing a workflow that patches up your types locally if you need a change within days.

**Comment by hellatan** [comment]
@eps1lon 

> This is just something you have to get used to with DefinitelyTyped. 

lol...so basically you're saying I just need to stay persistent until my build passes?

> I can only recommend developing a workflow that patches up your types locally if you need a change within days.

basically making certain changes directly in my project for now until the type defs file is updated and published?

**Comment by hellatan** [comment]
@sandersn @aaronbeall I see that you two have worked on the `react-bootstrap` type definitions. I've been trying to get my PR merged for weeks now and I keep on getting the following error:
```
Error in react-bootstrap/undefined
Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/types/react-bootstrap/undefined/index.d.ts'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test: `node node_modules/@definitelytyped/dtslint-runner/dist/index.js --path .`
npm ERR! Exit status 1
```
do either one of you know what would be considered `undefined` here? I'm pretty unfamiliar with how all of this gets compiled and typed, honestly. Any help would be much appreciated.

**Comment by sandersn** [comment]
@hellatan I ran into the same problem last week and shipped [a temporary fix](https://github.com/microsoft/DefinitelyTyped-tools/pull/30), so if you `npm install` you should get it.

**Comment by hellatan** [comment]
@sandersn I rebased this branch on top of latest master but it still seems to fail. Shouldn't the `npm install` work on the `DefinitelyTyped.DefinitelyTyped` job and pull your fix in? It's still failing with the `react-bootstrap/undefined` error. I'm not sure how the `DefinitelyTyped-tools` repo works, but does that publish a package under `@definitelytyped/tools`? If so, which version should be installed? I ran `npm info @definitelytyped/tools` locally and have `0.0.38` installed. Also, it seems like https://github.com/DefinitelyTyped/tools#readme is not the correct url anymore.

**Comment by eps1lon** [comment]
The fix mentioned by @sandersn seems to not work for me either. #44898 and #44896 are still failing on react-bootstrap.

**Comment by eps1lon** [comment]
@hellatan The main branch is now green regarding `react` typings. If you rebase onto latest `master` the PR should pass.

**Comment by hellatan** [comment]
@eps1lon it finally passed! 🥳 i hope i don't have to touch react type defs for awhile now...

**Comment by hellatan** [comment]
@eps1lon bumping this while it's still green 😄

**Comment by eps1lon** [comment]
> @eps1lon bumping this while it's still green

I can't do anything because I don't have any write priviliges.

**Comment by hellatan** [comment]
> I can't do anything because I don't have any write privileges.

ah damn, i wasn’t aware of that. who typically merges theses PRs then?

**Comment by eps1lon** [comment]
> ah damn, i wasn’t aware of that. who typically merges theses PRs then?

Bots and Microsoft employees.

**Comment by sandersn** [comment]
@hellatan you finished an `@types/react` PR! Thanks for putting up with our automation troubles.

**Comment by hellatan** [comment]
haha thanks @sandersn...definitely a lot more than i was expecting. thanks @eps1lon for putting up with all this back and forth.

**Pull request merged**
