### PR TITLE
[Framework7] new definitions, v1.0

### PR DESCRIPTION
**Pull request by larrybahr**
Definitions for Framework7

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by larrybahr** [comment]
Repost of [[Framework7] new definitions, v1.0 #14602](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14602) do to a misunderstanding leading to the original repository being deleted. @zhengbli

**Comment by TonyPythoneer** [comment]
@larrybahr Please read the error log in Travis CI. The module should be framework7.
By the way, you should use TypeScript 2.x stynax to define typing file. Please refer https://www.typescriptlang.org/docs/handbook/declaration-files/templates.html

**Comment by minestarks** [comment]
@larrybahr will you be making the requested changes? Thank you.

As this PR is quite old, I will be closing in a few days if no changes.

**Comment by larrybahr** [comment]
Sorry for the silence. I don't have time to work on this right now. I'll close this and submit a new PR when I have time to fix the changes.

**Pull request closed without merging**
