### PR TITLE
Adding "start" and "end" to createReadStream() options definition.

### PR DESCRIPTION
**Pull request by micurs**
See node documentation here: https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

### CODE REVIEW

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by micurs** [comment]
Hi Vvakame, 
I am not sure how and I don't know how to see which conflicts we do have here. 
Any help pointing me on how to address this would be appreciated.  
Thanks

**Comment by micurs** [comment]
Ok, Let me know if that fixed it.

**Comment by vvakame** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ ?

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
