### PR TITLE
node: Fix link tags using parens

### LINKED ISSUE #124937: @link not working in node.js type definitions
image

```ts
            /**
             * The {@link console.info()} function is an alias for {@link console.log()}.
             */
            info(message?: any, ...optionalParams: any[]): void;
```

### PR DESCRIPTION
**Pull request by mjbvz**
`@link` should reference the symbol name without the `()`

Fixes https://github.com/microsoft/vscode/issues/124937

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
NA

### CODE REVIEW

**Comment by mjbvz** [comment]
@sandersn There's ~1000 other places in the types where `@link` is used this way. You may want to do a find/replace across the entire repo to fix these:

```
\{@link ([\w\.]+)\(\)\}
```

```
{@link $1}
```

**Review by SimonSchick — APPROVED** [review]
Sure.

**Comment by sandersn** [comment]
@mjbvz does trailing `()` break name resolution? I'm pretty sure TS correctly ignores the trailing `()`, in which case I don't think it's worth the effort to remove it from the whole repo.

**Review by amcasey — APPROVED** [review]
No objections, but please consider Nathan's question.

**Comment by mjbvz** [comment]
@sandersn The links still work, but TS is parsing them oddly, for example:

```
{
            "text": "{@link ",
            "kind": "link"
        },
        {
            "text": "foo",
            "kind": "linkName",
            "target": {
                "file": "/Users/matb/projects/vscode-github-issue-notebooks/src/renderer/index.tsx",
                "start": {
                    "line": 10,
                    "offset": 1
                },
                "end": {
                    "line": 10,
                    "offset": 17
                }
            }
        },
        {
            "text": "()",
            "kind": "linkText"
        },
        {
            "text": "}",
            "kind": "link"
        },
```

Specifically the `linkText` is just `()`.

I wasn't sure if this syntax was valid in JSDoc. If it is something we want to support, should I file an issue against TypeScript instead to improve the parsing of this link format?

**Comment by sandersn** [comment]
Yes, please do file a bug.

- I remember it being fairly common in the corpus I checked.
- I have real trouble remembering presentation issues, so my "successful resolution=good enough" approach is definitely wrong.

I *guess* that `linkName` should be `foo()` in this case, but a new bug will give us space to discuss. (There may be other cases where Typescript's view of an identifier differs from the author's view.)

**Comment by mjbvz** [comment]
Ready to merge

**Comment by mjbvz** [comment]
Ok, let's merge this for TS 4.3 but I'll open an issue for the parsing issue

**Pull request merged**
