### PR TITLE
feat(chalk): remove types as these are now in the library

### PR DESCRIPTION
**Pull request by alan-agius4**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [] Test the change in your own code. (Compile and run.)
- [] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Lgtm. Will wait for others to comment before merging

**Comment by sheetalkamat** [comment]
@Diullei @Bartvds @nicojs Can you please review

**Comment by danthegoodman** [comment]
Fixes #17644
Closes #20777 
Closes #20296

**Comment by emilio-martinez** [comment]
What's the process to update type definitions such as `gulp-util` that depend on `@types/chalk`?

**Comment by alan-agius4** [comment]
I am not sure, @andy-ms maybe you can shed some light on this?

**Comment by johnnyreilly** [comment]
@emilio-martinez you should be able to use the type defs that ship with chalk now. Stick to the 2.3 release that came out last night though. 2.2 was more problematic

**Comment by andy-ms** [comment]
Just add a `package.json`: 
```json
{
  "private": true,
  "dependencies": {
    "chalk": "^2.3.0"
  }
}
```

**Pull request merged**
