### PR TITLE
wpapi

### PR DESCRIPTION
**Pull request by guoyunhe**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by plantain-00 — APPROVED** [review]

**Comment by minestarks** [comment]
@guoyunhe this is almost good to go, but the Travis CI build hasn't run. We need the tests to run before I can merge.

This is _possibly_ because Travis mistakenly flagged your account as abusive. This has unfortunately happened before. Could you follow the directions below and connect your GitHub account at http://travis-ci.org ? So sorry for the inconvenience.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17642#issuecomment-315801915
> This is an unfortunate side effect of our abuse detection which sometimes produces false positives. In this case, the users who opened those pull requests don’t have accounts on Travis CI and this situation has led to abuse before (mostly through automated accounts). Could you ask the people who opened those PRs to visit travis-ci.org, click “Sign up”, and consent to connecting their GitHub accounts to Travis CI?

**Comment by guoyunhe** [comment]
@minestarks I have signed up on Travis CI and connected my GitHub account.

**Comment by guoyunhe** [comment]
I got this alert from Travis CI:

>  The account guoyunhebrave has been flagged for potential abuse. Please contact support@travis-ci.com. 

But I have never used it before...

**Comment by RyanCavanaugh** [comment]
Please do email them - they're very quick and friendly to unflag your account.

**Comment by guoyunhe** [comment]
@RyanCavanaugh Just emailed them. Waiting for reply.

**Comment by minestarks** [comment]
Travis is back! Thanks @guoyunhe for your patience.

**Pull request merged**
