### PR TITLE
openlayers: adds featureProjection to the GeoJSONOptions interface

### PR DESCRIPTION
**Pull request by aubm**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by osechet — CHANGES_REQUESTED** [review]
This change has been made with v3.19.0. Please update the version of the definition file accordingly.

**Comment by aubm** [comment]
It seems that v3.19.0 does not exist yet.
Here is the command I use and the corresponding output `npm i --save-dev @types/openlayers@3.19.0`:

```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "@types/openlayers@3.19.0"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @types/openlayers@3.19.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.18.41, 3.18.40, 3.18.39, 3.18.38, 3.6.37, 3.6.36, 3.6.35, 3.6.34, 3.6.33, 3.6.32, 3.6.31, 3.6.30, 3.6.29, 3.6.28, 3.6.27, 3.6.26-alpha, 3.6.25-alpha, 3.6.24-alpha, 3.6.23-alpha, 3.6.22-alpha, 3.6.21-alpha, 3.6.20-alpha, 3.6.15-alpha, 3.6.14-alpha
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aurelienbaumann/Developpements/go_code/src/github.com/airbusgeo/unicat-demo-web-ui/npm-debug.log
```

Am I missing something?

**Comment by osechet** [comment]
Version in npm depends on the version you specify at the top of the definition file (the [first line](https://github.com/aubm/DefinitelyTyped/blob/937782138c3eec4174e07f33a1dc1cc75158b98c/openlayers/index.d.ts#L1)). Change this version and next time the DefinitelyTyped team publish the definition to npm,  the new version will be available.

**Comment by aubm** [comment]
Ho ok, got it, sorry :) I amended the commit. Tell me if anything else is missing.

**Review by osechet — APPROVED** [review]

**Comment by horiuchi** [comment]
@aubm Thank you for your contribution. 👍 
Could you resolve the conflict?

**Comment by aubm** [comment]
Conflict resolved, though the version in the definition file was updated in the meantime. I set it back to `v3.19.0`, but I'm not really sure that it is the right thing to do...

**Comment by osechet** [comment]
@aubm You merged changes coming from v3.20.0. You should have kept v3.20.0.

**Comment by aubm** [comment]
@osechet it should ok now ^^

**Review by osechet — APPROVED** [review]

**Pull request merged**
