### PR TITLE
Provides Aligning of RSocket-xxx definitions with the latest RSocket-JS release

### PR DESCRIPTION
**Pull request by OlegDokuka**
Hello there!

One of the RSocket-JS maintainers here!

This PR provides a list of cleanup/removals/alignments with the latest version of RSocket.

Regards,
Oleh

### CODE REVIEW

**Review by adrianhopebailie — APPROVED** [review]
@OlegDokuka I am not up to date on the latest RSocket-JS codebase so I'm gonna trust that as a maintainer you know more than me here 😃 

I don't see any obvious issues 👍

**Review by adrianhopebailie — APPROVED** [review]
@OlegDokuka I am not up to date on the latest RSocket-JS codebase so I'm gonna trust that as a maintainer you know more than me here 😃 

I don't see any obvious issues 👍

**Comment by adrianhopebailie** [comment]
p.s. @OlegDokuka have you considered deprecating this and shipping the types with the package?

**Comment by OlegDokuka** [comment]
@adrianhopebailie https://github.com/rsocket/rsocket-js/issues/70#issuecomment-557049773

Feel free to leave your comment there 🤓

Regards,
Oleh

**Pull request merged**
