### PR TITLE
[node-fetch] extend Response type

### PR DESCRIPTION
**Pull request by LaseII**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by lasell82** [comment]
Usecase description :

```
import fetch from 'node-fetch';
import { LinkStatus } from '../types';

const doFetch = async (href: string: Promise<LinkStatus> => {
  return fetch(href)
    .then((response: Response) => {
      return {
        href,
        status: response.status,
        responseUrl: response.url,
        isRedirect: response.redirected
      };
    })
    .catch((err) => (console.log(err)));
};
```

**Comment by lasell82** [comment]
Can anyone help to find the right @author which can support with the PR

**Review by kyranet — APPROVED** [review]
You missed the URL where this value is defined at in the description, but [here it is](https://github.com/bitinn/node-fetch/blob/95286f52bb866283bc69521a04efe1de37b26a33/src/response.js#L63-L65) 😄

**Comment by lasell82** [comment]
@kyranet thanks a lot 😄

**Review by nikcorg — CHANGES_REQUESTED** [review]
Please update the [version number](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37069/files#diff-16dd1699972b26236bcd5bc367af23fbR1) ([introduced in 2.5.0](https://github.com/bitinn/node-fetch/blob/95286f52bb866283bc69521a04efe1de37b26a33/CHANGELOG.md#v250)).

Don't forget to add yourself to the contributors list while you're in there.

**Review by nikcorg — APPROVED** [review]
LGTM

**Pull request merged**
