### PR TITLE
feat(@carbon/icons-react): support v11

### PR DESCRIPTION
**Pull request by metonym**
This updated types for `@carbon/icons-react` to the latest major version. The API of the library is updated so that the icon size is a prop rather than a separate file. As a result, the package should be massively reduced in size.

Resolves:

- https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61203
- https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57008

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/carbon-design-system/carbon/tree/master/packages/icons-react)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by metonym** [comment]
Apologies for the ping @peterblazejewicz but is there anything I can do for this PR? I'm not seeing the typescript bot or other automated checks. I wonder if it's because of the size of the PR.

It's a big PR but it reduces the number of total files and would unblock TypeScript usage of the package.

**Comment by peterblazejewicz** [comment]
this PR is a beast. I guess due to number of artefacts. Let's look into details.
Are you folks sure you want to publish such a number of artefacts?

**Comment by metonym** [comment]
Good on my side. I'd also add that a DefinitelyTyped maintainer had [previously suggested](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52664#issuecomment-834800128) cutting down the file size. I think that this would be the right interim step until TypeScript is supported upstream so that these type definitions can finally be removed.

**Comment by peterblazejewicz** [comment]
can you folks, during build, amend single `index.d.ts` with your helper builder code and amend declaration for each symbol? Here only for 'Accessiblity':
```ts
declare module '@carbon/icons-react' {
    interface CarbonIconProps extends Omit<React.SVGProps<React.ReactSVGElement>, 'ref' | 'tabIndex' | 'aria-hidden'> {
        ...
    }

    type CarbonIconType = React.ForwardRefExoticComponent<CarbonIconProps & React.RefAttributes<SVGSVGElement>>;

    interface CarbonIconNextProps {
        ...
    }

    type CarbonIconNextType = React.ForwardRefExoticComponent<CarbonIconNextProps & React.RefAttributes<SVGSVGElement>>;

    const Accessibility: CarbonIconType;
}

/// amended per symbol
declare module '@carbon/icons-react/lib/accessibility/16' {
    import { Accessibility } from '@carbon/icons-react';
    export = Accessibility;
}

declare module '@carbon/icons-react/es/accessibility/16' {
    import { Accessibility } from '@carbon/icons-react';
    export default Accessibility;
}

declare module '@carbon/icons-react/next/Accessibility' {
    import { Accessibility } from '@carbon/icons-react';
    export default Accessibility;
}
```
/cc @andrewbranch topic from Discord

**Comment by andrewbranch** [comment]
Seems like a step in the right direction. I skimmed all the added/modified diffs for due diligence, tests are passing, think there’s nothing to do but merge it.

**Comment by metonym** [comment]
Thank you – I've forwarded your suggestion to the Carbon team in [one of their PRs](https://github.com/carbon-design-system/carbon/pull/11533) that aimed to support TypeScript.

For anyone reading this, the Carbon + TypeScript discussion can be found [here](https://github.com/carbon-design-system/carbon/discussions/10752).

**Pull request merged**
