### PR TITLE
Add vfile message

### PR DESCRIPTION
**Pull request by Rokt33r**
I added type definitions for vfile-message and updated vfile too.

I did... :
- Move VFileMessage type definition in `vfile` to `vfile-message`.
- Fix return type of `VFile#info` method.
- Introduce `AnyNode` type to make `vfile-message` constructor can takes any nodes for `position`.

---
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/vfile/vfile#vfileinforeason-position-origin
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Rokt33r** [comment]
Please review this! @ChristianMurphy @wooorm @bizen241

**Comment by bizen241** [comment]
I think the `stack` optional property of `VFileMessage` is missing.
`VMessage` in [vfile/vfile-message](https://github.com/vfile/vfile-message#vmessagereason-position-origin) and [Rokt33r/typed-remark](https://github.com/Rokt33r/typed-remark/blob/master/packages/vfile/src/lib/VFileMessage.ts) has it.

**Comment by Rokt33r** [comment]
@bizen241 I think we don't need it anymore because we extends `Error` and `Error` has the `stack` property.

**Comment by bizen241** [comment]
@Rokt33r I missed it. Thank you.

**Review by bizen241 — APPROVED** [review]

**Review by ChristianMurphy — APPROVED** [review]

**Review by wooorm — APPROVED** [review]

**Pull request merged**
