### PR TITLE
[vimeo] Remove types

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
This library has been deprecated for a while, so its typings should probably be removed.
See: <https://www.npmjs.com/package/vimeo>

Screenshot of the npm page, showing deprecation message

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:

- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mattleff** [comment]
@MysteryBlokHed Is this a standard practice? I'm not aware of other `@types/*` packages that were removed just because the library was deprecated. People use deprecated stuff...

**Comment by MysteryBlokHed** [comment]
> @MysteryBlokHed Is this a standard practice? I'm not aware of other `@types/*` packages that were removed just because the library was deprecated. People use deprecated stuff...

My thinking was that the two similarly named packages (`vimeo` and `@vimeo/vimeo`) could cause confusion when users are looking for the right types package, since there's currently `vimeo` and `vimeo__vimeo` for each respectively. Deprecating the types for the old package would make it more obvious to developers that they're downloading the wrong version.

I don't know if there's specific Definitely Typed guidance on what to do with deprecated packages; this is just what I thought made sense. But if you think it'd be best to just keep both types packages as they are, I can close this.

Also: I can add you as an owner to the `vimeo__vimeo` types. They're basically the same definitions under a new name.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
This shouldn’t go in `notNeededPackages.json`; the types can just be deleted eventually, but it’s also fine to keep them around to allow for fixes for folks who are still using the deprecated package.

**Comment by MysteryBlokHed** [comment]
> This shouldn’t go in `notNeededPackages.json`; the types can just be deleted eventually, but it’s also fine to keep them around to allow for fixes for folks who are still using the deprecated package.

I was just thinking for cases such as #69114, although I guess that it shouldn't really be an issue now that vimeo__vimeo types do exist.

I'll close this for now

**Pull request closed without merging**
