### PR TITLE
Add Resemble.js

### PR DESCRIPTION
**Pull request by pimterry**
Adds types for [Resemble.js](http://huddle.github.io/Resemble.js/)

This is the first library I've added, hope I've done it right :-).

The Resemble.js API is fairly minimal, so reasonably easy to come up with a clear outline. It's not a particularly well documented library though sadly, which makes it hard to be definitive. I've pulled in the examples from their page plus a few extra bits for detail as tests, and this does successfully compile everything I'm using it for in my project.

(Sorry, I've been doing lots of moving things to TypeScript today, so lots of PRs for libraries en route. Hope that's ok!)

### CODE REVIEW

**Comment by pimterry** [comment]
And indeed I had done it wrong; turns out while it compiled, it didn't actually pass the NPM tests. Now fixed.

**Comment by vvakame** [comment]
*resemble/resemble.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/resemble
  * http://bower.io/search/?q=resemble
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (resemble/resemble-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@pimterry thank you for your contributions!
please rename resemble/resemble.d.ts to resemblejs/resemblejs.d.ts

**Comment by pimterry** [comment]
Done :smile:

**Comment by vvakame** [comment]
@pimterry thanks mate!

**Pull request merged**
