### PR TITLE
fix(react-map-gl) use already defined MapboxGL anchor types in Popup Component instead of duplicate it

### PR DESCRIPTION
**Pull request by j8seangel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/j8seangel/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L169
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by j8seangel** [comment]
I couldn't run the tests as I got several errors like
``` Errors in typescript@4.1 for external dependencies:
../react/index.d.ts(38,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
```
```
../viewport-mercator-project/index.d.ts(7,22): error TS2307: Cannot find module 'gl-matrix' or its corresponding type declarations
```
any idea why? or how to fix them ?

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. register
1. Icons
1. Fx
1. Snapshot

<details>
<summary>as well as these 2 other properties...</summary>
<p>PlotSchema, Queue</p>
</details>

## react-map-gl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-map-gl@latest/))
was missing the following properties:
1. setRTLTextPlugin
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 83480d73120ba4f817c0e930d225ac4338dca1d7
</p>

**Review by oturpe — APPROVED** [review]
Looks good to me.

**Comment by oturpe** [comment]
> I couldn't run the tests as I got several errors like
> 
> ```
> ../react/index.d.ts(38,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
> ```
> 
> ```
> ../viewport-mercator-project/index.d.ts(7,22): error TS2307: Cannot find module 'gl-matrix' or its corresponding type declarations
> ```
> 
> any idea why? or how to fix them ?

The dependencies of this module have dependencies that need to be installed. So to properly try compile everything:
```
pushd ../react
npm install
pushd ../viewport-webmercator-project
npm install
popd
popd
tsc
```

**Comment by j8seangel** [comment]
Thank you @oturpe I ran the command and worked without any error 👍 
Will be very useful for the next types updates.

**Comment by j8seangel** [comment]
Ready to merge

**Pull request merged**
