### PR TITLE
add typings for tap (i.e. node-tap)

### PR DESCRIPTION
**Pull request by uwinkelvos**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by uwinkelvos** [comment]
This fixes #16400. Still open as draft, so that people over from https://github.com/tapjs/node-tap/pull/607 can give feedback.

**Comment by elibarzilay** [comment]
@uwinkelvos / @delvedor -- IIUC, since the [other PR](https://github.com/tapjs/node-tap/pull/607) looks under active discussion, and this is explicitly redundant when that's in, then is there really any need for it?  Especially given that there's a discussion there...

**Comment by uwinkelvos** [comment]
Hey @elibarzilay,

it seems to me, that judging by his lack of involvement in that PR, @isaacs is not really interested in merging that to node-tap. He even opened up the initial request for types here: #16400. SO i don't see it landing in node-tap soonish and as the package is used quite a lot, having the types here would be super helpful.

**Review by andrewbranch — APPROVED** [review]

**Comment by IlyaSemenov** [comment]
Those styles are really odd. `Test` class is not exported, so to refer to a tap instance one must use weird hacks like:

```ts
import { Test } from 'tap'

function foo(tap: typeof Test.prototype) { ... }
```

**Pull request merged**
