### PR TITLE
Add definition for refresh function of Netlify identity widget

### PR DESCRIPTION
**Pull request by ercgrat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Recent pull request that added the refresh method](https://github.com/netlify/netlify-identity-widget/pull/237)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

@nkprince007

### CODE REVIEW

**Comment by ercgrat** [comment]
Fixed the type of the return value to string instead of Token. See the `jwt` function in [gotrue-js/user.js](https://github.com/netlify/gotrue-js/blob/master/src/user.js).

**Comment by ercgrat** [comment]
Hoping for a review on these updates!
@uniqueiniquity 
@nkprince007

**Comment by sheetalkamat** [comment]
Closing this because of no updates from author

**Comment by ercgrat** [comment]
> Closing this because of no updates from author

The bot said I had a week to address this. I've been waiting on review. Perhaps @marierigal can review?

**Pull request closed without merging**
