### PR TITLE
angular: import should bring in the type information as well

### LINKED ISSUE #3670: AngularJS externs, ng.IAngularStatic vs angular
The externs for AngularJS define:
```js
declare var angular: ng.IAngularStatic;
// Support AMD require
declare module 'angular' {  // NB: doesn't currently work with TypeScript 1.4 AFAICT
    export = angular;
}
declare module ng {
  // ... definitions, including IAngularStatic
}
```

Is there a way to use `.d.ts` files like this without triple slash references (`/// <reference path=...>`)? If this would define:
```js
export = ng;

declare module ng {
  function module(...): ng.Module;
}
```

... then user code could simple and consistently write:
```js
import angular = require('angular');
var myMod: angular.Module = angular.module(...);
```

Is there a particular reason to split into an `angular` variable of type `ng.IAngularStatic` and the `ng` module?

### PR DESCRIPTION
**Pull request by basarat**
closes https://github.com/borisyankov/DefinitelyTyped/issues/3670
closes https://github.com/borisyankov/DefinitelyTyped/pull/3714

Basic objective is to support: 

``` ts
import angular = require('angular');
var myMod: angular.IModule = angular.module(...);

// and maintain backward compatibility: 
var myMod2: ng.IModule;
myMod2 = myMod;
```

This does break backward compatibilty if user does `declare module ng` or `module ng`.

They should update all to `module angular`. 

Note: This backward compatibility might be restored with TypeScript 1.5

### CODE REVIEW

**Comment by basarat** [comment]
Funny. Isn't an error in ts 1.5 

image

**Comment by basarat** [comment]
@vvakame alright I have an understanding now. 

Note TS 1.5 is okay with : 
```ts
import foo = bar;
module foo{}
```

TS 1.4 will however complain with `Import declaration conflicts with local declaration of 'foo'`. Note that given that changes I've made : https://github.com/borisyankov/DefinitelyTyped/pull/3851/files consumer code will work *fine* as long as they don't do `module ng` themselves. This is something that definition files are doing in our repo and hence the failing tests. 

I can update the definition files to all use `angular` instead of `ng` and *not touch any tests* to demo that user code will continue to work fine. Should I do this?

**Comment by basarat** [comment]
@vvakame this PR is good to go from by side. Best to review : https://github.com/borisyankov/DefinitelyTyped/pull/3851/files 

Please raise objections if any. I'll merge in two days :heart:

**Comment by mprobst** [comment]
@basarat thanks for doing this. LGTM indeed.

Maybe it'd be nice to add a test along these lines?

```js
import angular = require('angular');
var mod: angular.IModule = angular.module('mod', []);
```

**Comment by mprobst** [comment]
... and maybe a second one like this just to make sure that TS really picks up the types from the require, not from some ambient information.

```js
import localName = require('angular');
var mod: angular.IModule = angular.module('mod', []);
```

Then again, maybe this is just all still a bit spooky to me, and I'm being overly skeptical ;-)

**Comment by basarat** [comment]
Added the tests

**Comment by crissdev** [comment]
Merging 30 commits - which could easily be squashed into just a meaningful one - makes really hard to go through the repo log.

**Comment by vvakame** [comment]
:+1:

**Comment by basarat** [comment]
> angular-ui-router" because its bower package includes its own angular-ui-router.d.ts 

The bower packages have been deprecated and not updated for quite a while. 

>  I had to go through all *.d.ts downloaded from DefinitelyTyped which referenced angular.d.ts and change all the ng.XXXX to angular.XXXX

That is correct. However **you didn't need to do that if you just downloaded the fresh ones from DefinitelyTyped** as we updated all those in synchrony.

**Pull request merged**
