### PR TITLE
Update ramda version number in `index.d.ts`

### PR DESCRIPTION
**Pull request by essenmitsosse**
The changes introduced in bd989412ba2e15a8459ec1368e42191194455fab (#58847) only work with ramda 0.28 (that's when `count` was introduced), which wasn't reflected in the version in `index.d.ts`. So to the user of `@types/ramda` it would look like `count` already exists in 0.27, when it was only introduced in a later version.

Sorry for the oversight, I missed, that I had to update the version number in my original PR.

Also Version 0.27.65 of `@types/ramda` should be deprecated.

----

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. collectBy
1. modify
1. modifyPath
1. partialObject
1. on

<details>
<summary>as well as these 5 other properties...</summary>
<p>promap, sequence, splitWhenever, unwind, whereAny</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against abba6ac268ddeb0b956c1961bfebe20baf822f42
</p>

**Comment by jakebailey** [comment]
> Also Version 0.27.65 of @types/ramda should be deprecated.

Unfortunately there's not really a way to do this; if you want this effect, I think you'll need to submit a PR that undoes your previous change, allow it to be published again, then resubmit the PR with the version bump afterward.

**Comment by essenmitsosse** [comment]
@jakebailey thanks for your reply. NPM has a (feature for deprecations)[https://docs.npmjs.com/cli/v8/commands/npm-deprecate] so I hoped this might be possible.

If it isn't would you recommend going the route you described?

**Comment by jakebailey** [comment]
@RyanCavanaugh @sandersn @andrewbranch probably know better than me (I'm new to working on DT relatively speaking), but even if it's deprecated, the "bad code" is still the latest for that minor version. It's also totally possible that anyone doing an upgrade will get all new stuff anyway and avoid this (so this PR would be fine as-is).

**Comment by andrewbranch** [comment]
We can do it manually; I think it makes sense in this case. The other option would be to revert #58847 to publish a new, accurate 0.27.x, then reapply the changes with the version bump to 0.28. That seems like a lot of hoops to jump through, so we’ll just do the deprecation.

**Comment by jakebailey** [comment]
I issued the deprecation (see https://www.npmjs.com/package/@types/ramda/v/0.27.65), however, this doesn't have the desired effect, as clients get the bad version anyway:

```
$ npm i @types/ramda@latest
npm WARN deprecated @types/ramda@0.27.65: contains declarations added in 0.28
```

So, we'll have to do the revert, wait, unrevert. I'll send a revert PR in a moment.

**Comment by andrewbranch** [comment]
Revert up at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59002. After that’s published, we’ll un-revert it and add the version bump from this PR.

**Comment by jakebailey** [comment]
v0.27.66 has been published with the revert.

I was going to cherry pick the last change here and merge this PR, but it looks like you sent this PR from your `master` branch, so I'm a little wary of pushing there even if GitHub lets me. Normally it's not a good idea to send PRs from your master branch.

**Comment by essenmitsosse** [comment]
@jakebailey @andrewbranch thanks for helping to figure this out and sorry I made you jump through hoops. 

You can commit to my `master` since it's just for this PR. I'll create a branch next time! Otherwise I can also do the update and merge the recent changes.

**Comment by jakebailey** [comment]
`git` really doesn't like this. I'll just send a PR where I can control the commits and stuff.

**Comment by jakebailey** [comment]
Sent #59004. Closing this one as that one supersedes this.

I made sure to get the authorship right on the commits.

**Pull request closed without merging**
