### PR TITLE
[react-native] Fix FlatList/SectionList renderItem method types

### PR DESCRIPTION
**Pull request by timwangdev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://facebook.github.io/react-native/docs/flatlist.html> <http://facebook.github.io/react-native/docs/sectionlist.html>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
Thx!

But Could you add more detailed tests for you updates?

**Comment by alloy** [comment]
Did this API change in a newer RN version or has it always been like that? If it’s new, we should bump the version of the package to reflect that.

**Comment by timwangdev** [comment]
@alloy I believe the <FlatList> API was released with this but this types definition is not correctly implemented. This is a fix.

@huhuanming I noticed this, and I will add more test cases later on.

**Comment by huhuanming** [comment]
@alloy 
I think it's better to add tests after new api added and some apis missing tests in the future.

**Comment by huhuanming** [comment]
@timwangdev 

COOL!!!

**Comment by andy-ms** [comment]
Thanks!

**Comment by huhuanming** [comment]
@timbarclay 

> @alloy I believe the <FlatList> API was released with this but this types definition is not correctly implemented. This is a fix.

It's better to more close to the real implements.

Because a lot of custom types is not good for other maintainers and not easy to update the types.

In another typing repo I add much custom types, but when the original repo api updated, the repo cannot easy to follow it.

So it's important to follow the repo owner's design principles and design patterns.

And I will update `FlatList` and `SectionList` in this weekend, because they are `VirtualizedList` wrapper  actually and not a ScrollView. then it can be regarded that FlatList is a React `PureCompoent`, but it includes `VirtualizedList`'s properties,  `SectionList` too

**Comment by alloy** [comment]
Ok, so to summarise, we’re waiting for more tests to be added before merging, right?

**Comment by huhuanming** [comment]
Yep. ☺

**Comment by timwangdev** [comment]
@huhuanming @alloy, I did a few updates and please have a review. Thx.

**Review by iRoachie — CHANGES_REQUESTED** [review]
Could you also add `title` to the section list item? As far as the docs go, SectionList doesn't carry a key, just title and data.

https://facebook.github.io/react-native/docs/sectionlist.html

**Comment by timwangdev** [comment]
@iRoachie I think facebook documented this incorrectly. According to Flow-type in the [source code](https://github.com/facebook/react-native/blob/master/Libraries/Lists/SectionList.js#L25-L52) and [RNTester example](https://github.com/facebook/react-native/blob/master/RNTester/js/SectionListExample.js#L160-L180), the `title` shouldn't be here.

**Comment by timwangdev** [comment]
Added correct test cases.

**Comment by iRoachie** [comment]
Hmm interesting @timwangdev looks that way. Source code seems to be correct.

**Review by iRoachie — APPROVED** [review]

**Comment by timwangdev** [comment]
Actually the types in SectionList section could include some optional properties. Add the more correct types definitions.

**Comment by alloy** [comment]
Alrighty, thanks for the contribution, the fast updates, and the PR on the RN repo! 👏

**Pull request merged**
