### PR TITLE
[Async] Detect signatures callback

### PR DESCRIPTION
**Pull request by cedriclombardot**
Fix signatures of detect callbacks to follow doc https://github.com/caolan/async#detect

### CODE REVIEW

**Comment by Penryn** [comment]
This is close, but I think we don't need the second type `R` in there. The following should be correct:

`detect<T>(arr: T[], iterator: AsyncBooleanIterator<T>, callback?: AsyncResultCallback<T>): any;`

**Comment by cedriclombardot** [comment]
@Penryn fixed

**Comment by cedriclombardot** [comment]
See : https://github.com/caolan/async/issues/1137 before merge

**Comment by Penryn** [comment]
Thanks @cedriclombardot. Seems ok to me, and because of your issue they appear to have updated the docs: https://github.com/caolan/async#detect

I vote :+1:

**Pull request merged**
