### PR TITLE
add Aws namespace for aws serverless types

### PR DESCRIPTION
**Pull request by bryan-hunter**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

This seemed like the best place to adding typings for https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md

Expose `aws serverless` types so that can be imported using `import Aws from 'serverless/aws'`

### CODE REVIEW

**Review by kirill578 — APPROVED** [review]

**Review by gongjoonamu — APPROVED** [review]

**Comment by bryan-hunter** [comment]
Ready to merge

**Comment by sheetalkamat** [comment]
Need to run travis

**Comment by orta** [comment]
OK, so we confirmed that Travis did pass: https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/689035460

The commit statuses aren't getting sent back to the PR reliably though

**Comment by bryan-hunter** [comment]
Ready to merge

**Pull request merged**
