### PR TITLE
[react-native] Support Layout Props

### PR DESCRIPTION
**Pull request by brunolemos**
Related: #25081 

[TIL](https://twitter.com/brunolemos/status/986476909038104576) React Native supports layout styles as View and Image props.
E.g.: `<View flex={1} />`, `<Image width={200} />`

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Docs](https://facebook.github.io/react-native/docs/layout-props.html) | [Components search](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=LayoutPropTypes&type=)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by brunolemos** [comment]
Hm, it's conflicting with `react-native-modalbox` because they are overriding the `position` prop. What to do?

**Comment by iRoachie** [comment]
Doesn't actually seem to be the case of inheriting from `ViewProperties`, https://github.com/maxs15/react-native-modalbox/blob/master/index.js. May have been a error on my part when doing the original typings. So I guess we can change the typing of react-native-modalbox.

**Comment by iRoachie** [comment]
Only prop they seem to use is `style` https://github.com/maxs15/react-native-modalbox/blob/master/index.js#L426. I can patch this in

**Comment by brunolemos** [comment]
Seems to conflict with lot's of packages :(

**Comment by iRoachie** [comment]
Just react-native-linear-gradient and expo

**Comment by brunolemos** [comment]
@iRoachie but is it showing all errors? I'm afraid it's only showing for the `end` property now, like previously it only showed for the `position` property. Let me try locally.

**Comment by iRoachie** [comment]
May have to run again, since the modalbox PR just got merged

**Comment by brunolemos** [comment]
Yes I pushed again a few minutes ago

**Comment by brunolemos** [comment]
@iRoachie So these are all pending errors:

### Incompatible properties with packages:

- [x] `position`
  - [x] `react-native-modalbox`
- [ ] `end`, `start`
  - [ ] `react-native-google-signin`
  - [ ] `react-native-linear-gradient`
    - `expo`

### Other compiler errors

```
react-native-google-signin failing:
Error: /Users/brunolemos/Projects/packages/DefinitelyTyped/types/react-native-google-signin/react-native-google-signin-tests.tsx:18:32
ERROR: 18:32  expect  TypeScript@next compile error: 
Type 'PromiseConstructor' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
ERROR: 18:32  expect  TypeScript@next compile error: 
Type 'PromiseConstructor' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
  Types of parameters 'executor' and 'executor' are incompatible.
    Types of parameters 'resolve' and 'resolve' are incompatible.
      Type '[T] extends [void] ? (value?: T | PromiseLike<T> | undefined) => void : (value: T | PromiseLike<T...' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
        Type '((value?: T | PromiseLike<T> | undefined) => void) | ((value: T | PromiseLike<T>) => void)' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
          Type '(value: T | PromiseLike<T>) => void' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'T | PromiseLike<T> | undefined' is not assignable to type 'T | PromiseLike<T>'.
                Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
```

```
Error in react-native-google-signin
Error: /Users/brunolemos/Projects/packages/DefinitelyTyped/types/react-native-google-signin/react-native-google-signin-tests.tsx:18:32
ERROR: 18:32  expect  TypeScript@next compile error: 
Type 'PromiseConstructor' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
ERROR: 18:32  expect  TypeScript@next compile error: 
Type 'PromiseConstructor' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
  Types of parameters 'executor' and 'executor' are incompatible.
    Types of parameters 'resolve' and 'resolve' are incompatible.
      Type '[T] extends [void] ? (value?: T | PromiseLike<T> | undefined) => void : (value: T | PromiseLike<T...' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
        Type '((value?: T | PromiseLike<T> | undefined) => void) | ((value: T | PromiseLike<T>) => void)' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
          Type '(value: T | PromiseLike<T>) => void' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'T | PromiseLike<T> | undefined' is not assignable to type 'T | PromiseLike<T>'.
                Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
```

**Comment by iRoachie** [comment]
How do we go about fixing these? Changing prop names in libraries would have to be breaking changes for their packages.

**Comment by iRoachie** [comment]
Alright number 3 sounds good to me

**Comment by brunolemos** [comment]
@iRoachie ok, made #25147 and #25148 PRs. 
Also made one to `react-native-linear-gradient`: https://github.com/react-native-community/react-native-linear-gradient/pull/280

**Comment by brunolemos** [comment]
@iRoachie ok, ready 🍾

**Review by iRoachie — APPROVED** [review]
Thanks for taking the time to do this

**Pull request merged**
