### PR TITLE
Added @types/semaphore-async-await

### PR DESCRIPTION
**Pull request by Avol-V**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@Avol-V you checked the targets `typings-2.0` branch, but the PR still targets `master`. Can you update the PR? 

Further Travis has failed, can you make sure that passes?

**Comment by Avol-V** [comment]
> Further Travis has failed, can you make sure that passes?

I don't know whats wrong with Travis – locally its compiles just fine, but in Travis it can't find module. I use the same settings as in readme and example base64-js.

**Comment by paulvanbrenk** [comment]
@Avol-V my guess is that you may need to rebase or merge `types-2.0` into your branch again

**Comment by Avol-V** [comment]
My PR is not required any more — package ported to TypeScript.
https://github.com/jsoendermann/semaphore-async-await

**Pull request closed without merging**
