### PR TITLE
types for atom/tool-bar

### PR DESCRIPTION
**Pull request by aminya**
https://github.com/suda/tool-bar

See this in action here: https://github.com/aminya/juno-plus/blob/78c1ee36c83cc4f9371d7dafd0498b3ccec76aa1/src/juno-plus.ts#L1

------------------

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by aminya** [comment]
I thought `addButton` return is `void`, however, it returns the button element. I need to adjust this PR for that.

**Comment by lierdakil** [comment]
I'm a little torn on this one. On the one hand, tool-bar is a third-party package, and neither myself, nor, to my knowledge @GlenCFL or @smhxx are using it anywhere, so maintainers won't be able to actually maintain definitions for it in any meaningful sense. On the other hand, saying "it's a third-party package so we can't maintain it" isn't right either, since we _do_ have definitions for `linter` included (well, to be fair, it is a kinda-sorta part of atom-ide, which was at one point quasi-official)

In general, I would suggest making a separate package for this, but the definition probably references stuff from base atom definitions, which would make this approach more than a little unwieldy.

@aminya -- perhaps the solution here is to add yourself to maintainers for the atom type definitions.
The definitions could certainly use more eyes, and this would solve the problem of "maintainers not using the package they are supposed to maintain" wrt tool-bar. That said, I would suggest waiting for input from other maintainers first (if any).

@GlenCFL @smhxx thoughts?

**Comment by aminya** [comment]
How can I add myself as a maintainer? That's totally fine to me.

**Comment by GlenCFL** [comment]
My intent in adding the type definitions for third-party packages was always for
additional ones to be added, so long as they're both correct and potentially useful.
There's not much downside in them existing, as they rarely change and thus introduce
no maintainability issues. The three existing ones were last modified two years ago and are
still valid, with only a few minor additions being missing. The verification concern is valid, as documentation cant always be trusted.

@aminya You'd just add yourself to the list at the top of the Atom definition file.
My only issue with the PR is the use of `class` instead of `interface` for the `ToolBarManager` type, as this can result in invalid code if someone imports this type directly from the module and tries to instantiate an instance of it.

**Comment by aminya** [comment]
> 
> 
> My intent in adding the type definitions for third-party packages was always for
> additional ones to be added, so long as they're both correct and potentially useful.
> There's not much downside in them existing, as they rarely change and thus introduce
> no maintainability issues. The three existing ones were last modified two years ago and are
> still valid, with only a few minor additions being missing. The verification concern is valid, as documentation cant always be trusted.


Thank you! I will do it.

> 
> @aminya You'd just add yourself to the list at the top of the Atom definition file.
> My only issue with the PR is the use of `class` instead of `interface` for the `ToolBarManager` type, as this can result in invalid code if someone imports this type directly from the module and tries to instantiate an instance of it.

ToolBarManager is a valid class in tool-bar: https://github.com/suda/tool-bar/blob/0b8a1ced016b852ed175f72d7a860b324ef438fd/lib/tool-bar-manager.js#L4
Although not exported in the end: https://github.com/suda/tool-bar/blob/master/lib/tool-bar.js

**Comment by GlenCFL** [comment]
We're defining a module, `atom/tool-bar`, where that class isn't actually being exported.
```ts
import { ToolBarManager } from "atom/tool-bar";
const toolbar = new ToolBarManager();
```
That's a runtime error introduced through the definition file.

**Comment by lierdakil** [comment]
> ToolBarManager is a valid class in tool-bar

The primary difference between `class` and `interface` is that `class`es can be used in `new` expressions. The policy we use, at least for core Atom definitions, is "if you can't do `new X` in client code, it shouldn't be declared as class". There's a good reason for this policy actually, since this is valid code as far as TypeScript compiler is concerned:
```ts
declare class SomeRandomClass {
  constructor();
}

const newClass = new SomeRandomClass();
```
but the produced **javascript will break,** because constructor for `SomeRandomClass` isn't actually in scope.

As far as I can tell, it's completely impossible to get at the constructor for `ToolBarManager` in the client code, but declaring it as `class` will allow `new ToolBarManager` as far as TypeScript is concerned (but it isn't actually valid). Hence, it's better to declare it as `interface`.

Does this make sense?

**Comment by aminya** [comment]
Yes! Thank you all. I will change it to interface!

**Comment by aminya** [comment]
I updated the types. Could you approve this?

**Comment by aminya** [comment]
I updated the types. Could you approve this?

**Review by GlenCFL — APPROVED** [review]

**Comment by armanio123** [comment]
@GlenCFL, @lierdakil, @aminya I didn't quite follow the conversation, is this good to merge?

**Comment by aminya** [comment]
> 
> 
> @GlenCFL, @lierdakil, @aminya I didn't quite follow the conversation, is this good to merge?

Yes. I updated the types and GlenCFL already approved it.

**Pull request merged**
