### PR TITLE
chore(node): remove old versions

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

None of the usual options really applies here, I think it's time we purge old versions that have fallen out of LTS for a while, the packages will still be available (albeit with potential deprecation messages, which is OK imo).

I intend to become a little more active again maintaining nodejs typings and I'd love to see this to avoid contributors getting confused.

### CODE REVIEW

**Comment by SimonSchick** [comment]
I believe this failure is meaningless as dtlint doesn't handle version removals (still).

**Comment by Flarna** [comment]
Even NodeJs 8 is EOL since quiet a while not it's still used a lot in the wild. Maybe we should keep it a little longer to allow people to fix any issues they may find.

**Review by Flarna — APPROVED** [review]

**Comment by yoursunny** [comment]
Node 11 is EOL too.

**Comment by SimonSchick** [comment]
@Flarna we need to make a cut somewhere, node 8 is the 4th last LTS version, I don't see many changes being made there anymore.

Furthermore I did intentionally not delete anything >= v10 @yoursunny as it is somewhat more recent, I'm not opposed to dropping support for it.

(randomly chosen maintainer) @andrewbranch do you have any data on the distributions of @types/node downloads broken down by version?

**Comment by andrewbranch** [comment]
@SimonSchick unfortunately we don’t have any more granular info from npm than you see on the public package page 😕

**Comment by SimonSchick** [comment]
@andrewbranch do you think this deletion is OK regardless? It seem unreasonable to support/maintain non-LTS typings.

**Review by Flarna — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
I agree 100% with @andrewbranch's assessment

**Comment by sandersn** [comment]
Couple of additions:

I used npm [dev]dependencies, not github ones, which are a trailing indicator; people adding or updating dependencies are less likely to use node@6 than a random npm package which was last published years ago.

Here's the histogram:

image

I sampled 4000 packages -- the remainder didn't use node (3641), had an error downloading (60) or parsing package.json (5).

**Review by sandersn — APPROVED** [review]

**Pull request merged**
