### PR TITLE
Enforce strict identity in analytics-node types

### PR DESCRIPTION
**Pull request by vinassefranche**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://segment.com/docs/connections/sources/catalog/libraries/server/node/>>
  As stated in the documentation: `You must include at least one of userId or anonymousId in all track calls.`
  Not doing so results in a runtime error: `AssertionError [ERR_ASSERTION]: You must pass either an "anonymousId" or a "userId".`

### CODE REVIEW

**Comment by jakebailey** [comment]
The formatting changes make it basically impossible for me to review this PR as my eyes aren't helping me find the actual changes. Can you avoid making the style changes, or split the PR into two commits so they can be reviewed by someone like me who has no clue anything about this library?

**Comment by jakebailey** [comment]
Ah, oops! Missed it in all of the comment noise. Will take a look.

**Review by jakebailey — APPROVED** [review]

**Comment by vinassefranche** [comment]
> Ah, oops! Missed it in all of the comment noise. Will take a look.

No problem. Thanks a lot for the review!

**Comment by vinassefranche** [comment]
Ready to merge

**Pull request merged**
