### PR TITLE
refactor(laravel-vapor): add data, cancelToken and progress properties

### PR DESCRIPTION
**Pull request by awesome-fortune**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

Select one of these and delete the others:

If changing an existing definition:
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by saibotk — CHANGES_REQUESTED** [review]
While this is alright and fine, would you mind also adding `data?: any;` to the options?

I just saw that this is also missing currently.

I would appreciate that very much :) 

Thanks

**Comment by awesome-fortune** [comment]
> While this is alright and fine, would you mind also adding `data?: any;` to the options?
> 
> I just saw that this is also missing currently.
> 
> I would appreciate that very much :)
> 
> Thanks

Awesome, all done :)

Thanks a stack for the review

**Review by saibotk — APPROVED** [review]
Perfect! Thank you very much!

**Review by rbuckton — APPROVED** [review]

**Comment by awesome-fortune** [comment]
Ready to merge

**Pull request merged**
