### PR TITLE
[node] Update types to v20.11

### PR DESCRIPTION
**Pull request by Semigradsky**
https://github.com/nodejs/node/releases/tag/v20.11.0

- esm: add `import.meta.dirname` and `import.meta.filename`
- test_runner: adds built in `lcov` reporter

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/test.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bcfc5b635f26c073b9f9bc015b8575e0bb6b07ea
</p>

**Review by peterblazejewicz — APPROVED** [review]
@Semigradsky thanks!

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by alesmenzel** [comment]
@Semigradsky Hi, thanks for the change, but I have to say it is already super annoying in pure JS that dirname and filename are optional and you cant use declaration merging to fix the type...

**Comment by Semigradsky** [comment]
@alesmenzel Hi! Sorry, I don't understand. Is there something wrong with `dirname` and `filename`?

**Comment by alesmenzel** [comment]
@Semigradsky Most of the projects I work on use only file: imports so having it optional is a pain. Could there be some option to globally mark it as not optional? 
e.g. like luxon does with `throwOnInvalid` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/settings.d.ts#L62-L69

**Comment by alesmenzel** [comment]
@Semigradsky Could you help me understand what the `file:` module caveat means, does that mean when I impor from URL, I cannot use import.meta.dirname in the imported code?

**Comment by Semigradsky** [comment]
> These properties are missing for non-`file:`-based ES modules, such as those loaded from `data:` or `https:` URLs.

**Comment by alesmenzel** [comment]
@Semigradsky Thanks for the example. So the import.meta.dirname wont be available inside 'data:text/javascript,export default {}' but it will be available in the caller code .e.g.

```
import dataDirname from 'data:text/javascript,export default {}';

import.meta.dirname // is available as long this script was loaded as file: -> run by nodejs "node somefile.js"
```

so for most of the backend apps, where most modules are installed from npm, we will need to type cast import.meta.dirname to string as the type is string | undefined, even though for those cases we know it is always defined.

```
import path from "node:path"

path.resolve(import.meta.dirname, "somefile.js") // produces a TS error, because dirname might be undefined
```

so I would like to provide some alternative for those cases where we know before hand that it is always defined.

**Comment by Semigradsky** [comment]
@alesmenzel as temp solution you can use [Non-null Assertion Operator](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-): `path.resolve(import.meta.dirname!, "somefile.js")`

I see, `dirname` and `filename` are defined for most real code. So better to make them non-optional.

**Comment by alesmenzel** [comment]
@Semigradsky You cant do that in JS, thats a TypeScript thing. We can type cast `/** @type {string} */ (import.meta.dirname)`. But in comparison with __dirname (cjs), the DX is not great. And for most of node projects the undefined type will never happen.

**Comment by Semigradsky** [comment]
Ok, feel free to create PR with needed changes. Or I can create in Monday.

**Pull request merged**
