### PR TITLE
[react-table] type-safe accessor functions

### PR DESCRIPTION
**Pull request by andys8**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

---

### Purpose

`AccessorFunction` is of type `(row: object) => any`. This pull request has the purpose to type this depending on the given data `D[]`, so that `(row: D) => any` is the type.

### Further information 

The pull request removes `object` as a potential argument.

https://github.com/andys8/DefinitelyTyped/blob/52de94b301c4b5b4a8289690e13fe180f659ce7c/types/react-table/index.d.ts#L10

Since a `function` is also an `object` this would match wrong functions. It could be possible to use [conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html) and exclude this case. I tried so, but I wasn't able to use it the intended way with typescript. The [documentation](https://react-table.js.org/#/story/readme) has not a lot of information, but as of now I think that there is no valid way to pass an `object` in typescript. Therefore I think it's better to remove this case.

image

### CODE REVIEW

**Comment by andys8** [comment]
Happy to have feedback! @royxue @psakalo @Havret

**Review by rbuckton — CHANGES_REQUESTED** [review]
Introducing a new generic type parameter would be a breaking change for existing users. Consider using a type parameter default here to avoid impacting existing users.

**Comment by andys8** [comment]
Squashed the review changes for history readability.

**Comment by andys8** [comment]
Removed the lines where `D` was set explicitly to `any` because:
> use-default-type-parameter  This is the default value for this type parameter, so it can be omitted.

**Review by rbuckton — APPROVED** [review]

**Pull request merged**
