### PR TITLE
Added static required property to Validators class

### PR DESCRIPTION
**Pull request by ajtowf**

### CODE REVIEW

**Comment by vvakame** [comment]
@alexeagle ?

**Comment by ajtowf** [comment]
Was there a question? The validator class lacks a static property called required, as my commit message states.

**Comment by vvakame** [comment]
oh, sorry. he is main maintainer of angular2. I want to get his advice...

**Comment by alexeagle** [comment]
This is fine with me as a temporary fix, however the next angular release will overwrite this file and revert your change (see the comment near the top).
We already have an open issue: https://github.com/angular/angular/issues/3175
I'll work on that today so this is fixed more permanently in time for the next release.

**Comment by alexeagle** [comment]
Here is the updated file with my pending PR that adds all the missing static members. Want to give it a try and confirm?
https://gist.github.com/alexeagle/52fab280286e1220310b

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
