### PR TITLE
[node]: add node implementation of web streams api

### PR DESCRIPTION
**Pull request by wangzishi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/dist/latest-v16.x/docs/api/webstreams.html#web-streams-api>>
- [N/A] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by gabritto** [comment]
@SimonSchick @peterblazejewicz could you take a look and see if these changes make sense? it appears to be a copy of parts of `lib.dom.d.ts`, the parts relevant for the web stream API that node now implements.

**Comment by peterblazejewicz** [comment]
@gabritto they looks same because of ongoing effort to unitfy (webify) Node with same API (but to use split libraries for now)
Simon is probably better suited here.

@wangzishi you've added comments about TS errors, but I cannot see those locally (unless those are when running CI tests)

I haven't used this new api yet. So I've just copy MDN samples and they work without much change:
```ts
{
    // simple-pump
    (rs: ReadableStream) => {
        const reader = rs.getReader();
        return new ReadableStream({
            async start(controller) {
                while (true) {
                    const { done, value } = await reader.read();
                    if (done) {
                        break;
                    }
                    controller.enqueue(value);
                }

                // Close the stream
                controller.close();
                reader.releaseLock();
            },
        });
    };
}

{
    // simple-random-string
    let result = '';
    let interval: NodeJS.Timeout;
    function randomChars() {
        let string = '';
        let choices = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()';
        for (let i = 0; i < 8; i++) {
            string += choices.charAt(Math.floor(Math.random() * choices.length));
        }
        return string;
    }

    const stream = new ReadableStream({
        start(controller) {
            interval = setInterval(() => {
                let string = randomChars();
                controller.enqueue(string);
            }, 1000);
        },
        pull(controller) {
            // We don't really need a pull in this example
        },
        cancel() {
            // This is called if the reader cancels,
            // so we should stop generating strings
            clearInterval(interval);
        },
    });

    function readStream() {
        const reader = stream.getReader();
        let charsReceived = 0;

        // read() returns a promise that resolves
        // when a value has been received
        reader.read().then(function processText({ done, value }): void {
            if (done) {
                return;
            }
            charsReceived += value.length;
            const chunk = value;
            result += chunk;
            reader.read().then(processText);
        });
    }
}

{
    // stream tee example
    let result = '';
    let interval: NodeJS.Timeout;
    function randomChars() {
        let string = '';
        let choices = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()';
        for (let i = 0; i < 8; i++) {
            string += choices.charAt(Math.floor(Math.random() * choices.length));
        }
        return string;
    }
    const stream = new ReadableStream({
        start(controller) {
            interval = setInterval(() => {
                let string = randomChars();
                // Add the string to the stream
                controller.enqueue(string);
            }, 1000);
        },
        pull(controller) {},
        cancel() {
            clearInterval(interval);
        },
    });
    function teeStream() {
        const teedOff = stream.tee();
        readStream(teedOff[0]);
        readStream(teedOff[1]);
    }
    function readStream(stream: ReadableStream) {
        const reader = stream.getReader();
        let charsReceived = 0;
        reader.read().then(function processText({ done, value }): void {
            if (done) return;
            charsReceived += value.length;
            const chunk = value;
            result += chunk;
            reader.read().then(processText);
        });
    }
}

{
    // simple-writer
    function sendMessage(message: string, writableStream: WritableStream) {
        const defaultWriter = writableStream.getWriter();
        const encoder = new TextEncoder();
        const encoded = encoder.encode(message);
        encoded.forEach(chunk => {
            defaultWriter.ready
                .then(() => {
                    return defaultWriter.write(chunk);
                })
                .then(() => {})
                .catch(err => {});
        });
        defaultWriter.ready
            .then(() => {
                defaultWriter.close();
            })

            .catch(err => {});
    }

    const decoder = new TextDecoder('utf-8');
    const queuingStrategy = new CountQueuingStrategy({ highWaterMark: 1 });
    let result = '';
    const writableStream = new WritableStream(
        {
            write(chunk) {
                return new Promise((resolve, reject) => {
                    var buffer = new ArrayBuffer(2);
                    var view = new Uint16Array(buffer);
                    view[0] = chunk;
                    var decoded = decoder.decode(view, { stream: true });
                    result += decoded;
                    resolve();
                });
            },
            close() {
                //
            },
            abort(err) {
                console.log('Sink error:', err);
            },
        },
        queuingStrategy,
    );
    sendMessage('Hello, world.', writableStream);
}

{
    // strings-transform-stream
    async function main(rs: ReadableStream) {
        let results = '';
        const ts = new TransformStream();
        const lineStream = rs.pipeThrough(ts);
        const reader = lineStream.getReader();
        while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            results += value;
        }
    }
}
```

**Comment by wangzishi** [comment]
@peterblazejewicz  Yes, there is no error reported directly in the editor, but they will appear when I run `npm test node`.
 I don’t know how to fix these errors, even though I’ve written `Symbol.asyncIterator` definitions for them.

And the last 2 errors I commented is about transfer stream via `postMessage()` which is defined in standards and [documented in nodejs](https://nodejs.org/dist/latest-v16.x/docs/api/webstreams.html#transferring-with-postmessage). 
The reason of the error is because, according to the nodejs documentation, the `MessagePort` implemented by Nodejs lacks the `onmessage` event handler, but its use is written in the webstreams documentation example, so I don’t know whether it should be fixed. Fix those errors need to modify the type definitions in other files, so I didn't try to modify them together and leave comments in this PR.

**Comment by peterblazejewicz** [comment]
up to @gabritto

**Comment by gabritto** [comment]
I'm ok with this being merged as is, and then fixing the errors in the tests in other PR(s). but I guess this week it's up to @sandersn to also take a look and decide.

**Comment by sandersn** [comment]
I agree, I think this is OK to merge. However, I see the last commit was almost a month ago, so to avoid subtle merge conflicts, can you please merge from master one more time?

**Comment by wangzishi** [comment]
Sure!

**Pull request merged**
