### PR TITLE
[yeoman-generator] Add missing signature for custom parsing function to OptionConfig.type

### PR DESCRIPTION
**Pull request by jonnelaaglandwinder**
The 'type' option passed to the second argument of Generator.option accepts a custom function for parsing the option. (see [https://yeoman.io/authoring/user-interactions.html](https://yeoman.io/authoring/user-interactions.html))

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://yeoman.io/authoring/user-interactions.html](https://yeoman.io/authoring/user-interactions.html)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## yeoman-generator ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yeoman-generator@latest/))
was missing the following properties:
1. queues
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 00eeac9631b642c0e05df4d599c6d64567846191
</p>

**Comment by manuth** [comment]
Not quite sure whether or not to have this integrated.
While - according to the code - it's technically possible doesn't seem to be intended.

Could you explain what's the use of this briefly?

Thanks for your effort 😄

**Comment by Nocturne92** [comment]
It's a documented feature, so it should be intentional. Per the article I linked, section 'Arguments':

> The options hash accepts multiple key-value pairs:
> ...
> - `type` String, Number, Array (_can also be a custom function receiving the raw string value and parsing it_)

The use case would be parsing more complex options, say a list. By declaring the parsing function in the 'type' argument, you prevent unnecessary code duplication when the option is used in multiple callbacks.

**Comment by manuth** [comment]
Ooh thanks for pointing this out! Must have overlooked this part tbh 😅

**Review by neurolag — APPROVED** [review]
Looks fine to me!
Thanks for the work 😄

**Comment by Nocturne92** [comment]
Ready to merge

**Pull request merged**
