### PR TITLE
[nw.js] Update typings to v0.92.0

### PR DESCRIPTION
**Pull request by ayushmanchhabra**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nwjs.readthedocs.io/en/latest/References/Window/#winisdevtoolsopen>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/nw.js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a117e14bcb17a10b351bb908e59dbe3767970c41
</p>

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/nw.js/commit/ec95f45a70fd8d6a41ade72e951e0c14b0c3d2c4
Looks like this change was made in Git but not published to docs.

**Review by zkrige — APPROVED** [review]

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/nw.js/nw.js-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4af721b8845cc7275b8b025cb348dc2b3173155c
</p>

**Review by zkrige — APPROVED** [review]

**Comment by zkrige** [comment]
Ready to merge

**Comment by AlttiRi** [comment]
Not about this pull request, but about the package itself.


A decent number of fields are missing from it.

Here is how `nw` object looks in the console:

nw js object console

And types from `"@types/nw.js"`:

ide

**Comment by ayushmanchhabra** [comment]
@AlttiRi please open a pull request to add the missing fields, I'll be happy to review and merge in the changes

**Pull request merged**
