### PR TITLE
@wordpress/element: Remove react types re-export

### PR DESCRIPTION
**Pull request by sirreal**
Based on conversation in https://github.com/WordPress/gutenberg/issues/21767

- Replace manual `@wordpress/element` types with generated types. This removes the `react` re-export. These types were generated from https://github.com/WordPress/gutenberg/pull/21781/commits/b10377bd289b15ea53d96d09dd6ca64a89620857
- Import `react` directly from other `@wordpress/*` types rather than `@wordpress/element`.
- Make the linter happy.

When `@wordpress/element` including its own types is released, the types on DefinitelyTyped would be removed.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/WordPress/gutenberg/issues/21767
  - https://github.com/WordPress/gutenberg/pull/21781
- If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by sirreal** [comment]
@dsifford This is ready for a review 🙇 

FYI: @aduth

**Review by dsifford — APPROVED** [review]
LGTM. Thanks for doing this!

**Comment by marekdedic** [comment]
Hi,
this PR breaks the build for me and from what I've been able to tell, it's not an issue with my config, but with the typings...

Could you please confirm that? Here's the broken build: https://app.circleci.com/pipelines/github/skaut/skaut-google-drive-gallery/1039/workflows/f3c656b3-0320-4af8-a80a-c3678c72ba29/jobs/4345/steps

**Comment by sirreal** [comment]
@marekdedic In the PR you link, it appears that `@types/wordpress__element` is being upgraded while `@types/wordpress__data` is not. You wind up with incompatible versions.

If you upgrade all of the `@types/wordpress__*` packages, I suspect you'll be fine.

**Comment by marekdedic** [comment]
@sirreal Yes, that seems to be the case. However, `@types/wordpress_data` is not a direct dependency and `npm update` does not update it... So I have no way of updating it...

**Comment by sirreal** [comment]
> @sirreal Yes, that seems to be the case. However, `@types/wordpress_data` is not a direct dependency and `npm update` does not update it... So I have no way of updating it...

Something like `npm update --depth 4 @types/wordpress__data' should work.

**Comment by marekdedic** [comment]
@sirreal Thank, that fixed the errors in `@types/wordpress_data`. But there are still errors in `@types/wordpress_element` as well... :(

**Comment by sirreal** [comment]
@marekdedic - That looks like a stale react types: `npm update --depth 4 @types/react`.

**Comment by marekdedic** [comment]
Hmm, that helped. Strange, I thought `npm update` would update all dependencies to the newest version matching their requirements...

Anyway, thanks, problem solved

**Pull request merged**
