### PR TITLE
Leaflet: Fixed latLngBounds argument type and added missing variables to DomUtil

### PR DESCRIPTION
**Pull request by alejo90**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://leafletjs.com/reference-1.0.3.html#latlngbounds http://leafletjs.com/reference-1.0.3.html#domutil

### CODE REVIEW

**Comment by alejo90** [comment]
@dt-bot and maintainers, npm install in travis is failing. Is there a way to re run it?

**Comment by alejo90** [comment]
@typescript-bot and maintainers there are no failures in my test. npm install failed on the test run.

**Comment by RyanCavanaugh** [comment]
@alejo90 Please fix the failures indicated in the Travis CI log.

**Comment by alejo90** [comment]
@RyanCavanaugh have you read what I posted and the travis ci log? Please do and you'll see that the failure has nothing to do with what I did.

**Comment by RyanCavanaugh** [comment]
Sorry, that message is automated

**Comment by RyanCavanaugh** [comment]
Restarted Travis

**Comment by alejo90** [comment]
Thanks @RyanCavanaugh

**Pull request merged**
