### PR TITLE
Split out angular-ui-router and angular-ui-sortable

### LINKED ISSUE #3910: Split up angular-ui into angular-ui-router and angular-ui-sortable
Hi @michelsalib @jjeffery @santialbo @panuhorsmalahti @basarat @mattyork @thetallweeks @ofirgeller @gregwebs @cmc19 @vvakame @Bartvds 

I was wondering if it might be a good idea to break out the [angular-ui](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui) typings into angular-ui-router and angular-ui-sortable?  [UI-Bootstrap](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui-bootstrap) appears to already be following this convention and given the distinct nature of the various angular-ui projects I think it's the more sensible approach.

Would anyone have any objections?

### PR DESCRIPTION
**Pull request by johnnyreilly**
Resolves https://github.com/borisyankov/DefinitelyTyped/issues/3910

### CODE REVIEW

**Comment by johnnyreilly** [comment]
BTW I used [atom-typescript](https://github.com/TypeStrong/atom-typescript) to make these changes and I :heart: every moment of it @basarat!

**Comment by prasantasaha** [comment]
Hey @johnnyreilly, this commit has TypeScript error and currently breaking our build.

**Comment by prasantasaha** [comment]
angular-ui-router d ts

**Comment by johnnyreilly** [comment]
Are you sure all your typings are up to date? The CI tests are passing...

**Comment by johnnyreilly** [comment]
Also is your version of typescript up to date? It looks like you might need to install 1.4... (Union types)

**Comment by prasantasaha** [comment]
I've using TypeScript Version 1.0.3.0 (Visual Studio 2013). I think I need to upgrade.

**Pull request merged**
