### PR TITLE
change default test environment. --target es6 is default!

### PR DESCRIPTION
**Pull request by vvakame**
from https://github.com/DefinitelyTyped/definition-tester/pull/15
change default test procedure `tsc --module commonjs --noImplicitAny` to `tsc --target es6 --module commonjs --experimentalDecorators  --noImplicitAny` in Travis CI.

@DefinitelyTyped/contributors

### CODE REVIEW

**Comment by vvakame** [comment]
test passed in my local machine.

**Comment by davidreher** [comment]
@vvakame I am happy with this. We are already using it like this in our environment

**Comment by bgrieder** [comment]
:+1:

**Comment by vvakame** [comment]
:+1:

**Comment by horiuchi** [comment]
:+1:

**Comment by vvakame** [comment]
NOTE: If you want to use Promise with `--target es5`, you should add es6-promise/es6-promise.d.ts to your project.
https://github.com/DefinitelyTyped/definition-tester/pull/15#issuecomment-183177302 thanks alexeagle!

**Pull request merged**
