### PR TITLE
Add type to SendLocationOptions on package node-telegram-bot-api

### PR DESCRIPTION
**Pull request by LoicMoerman**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://core.telegram.org/bots/api#sendlocation>
Add : 
  - live_period
  - horizontal_accuracy
  - heading
  - proximity_alert_radius

### CODE REVIEW

**Review by XieJiSS — APPROVED** [review]
LGTM

**Comment by XieJiSS** [comment]
@LoicMoerman Please re-assure that these options are supported by the library (e.g., serialized and sent to the API endpoint when invoken). Also, would you mind adding some of the optional arguments to the sendLocation function in the test file? Thanks!

**Review by XieJiSS — APPROVED** [review]
Thanks

**Comment by XC-Zhang** [comment]
Ready to merge

**Pull request merged**
