### PR TITLE
fix(sinon): spying on instance should be possible

### PR DESCRIPTION
**Pull request by tpluscode**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://sinonjs.org/releases/latest/spies/#using-a-spy-to-wrap-all-object-method>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by 43081j** [comment]
@tpluscode i dont think its quite right as you're doing:

```ts
SinonStubbedInstance<T>
```

which means:

``ts
const instance = sinon.spy(someObj);

instance.someMethod.returns(5); // Shouldn't exist! this is a spy, not a stub
instance.someMethod.called; // Exists, just fine
```

i suspect you need a new `SinonSpiedInstance<T>` which looks like this:

```ts
    type SinonSpiedInstance<T> = {
        [P in keyof T]: SinonSpiedMember<T[P]>;
    };

    type SinonSpiedMember<T> = T extends (...args: infer TArgs) => infer TReturnValue
        ? SinonSpy<TArgs, TReturnValue>
        : T;
```

**Comment by tpluscode** [comment]
Ah, makes sense. I somehow assumed to use what is already there and it did not occur to me that I may need a new type 🤦

**Review by 43081j — APPROVED** [review]

**Comment by 43081j** [comment]
nice work @tpluscode , looks good to me 👍

**Comment by tpluscode** [comment]
Ready to merge

Sent from Nine
________________________________

**Pull request merged**
