### PR TITLE
Added Leaflet.DivIcon for icon type

### PR DESCRIPTION
**Pull request by pegel03**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified. 
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

### CODE REVIEW

**Review by danzel — CHANGES_REQUESTED** [review]

**Comment by danzel** [comment]
LGTM :+1:

**Comment by pegel03** [comment]
- [x] pass the Travis CI test?

**Comment by mhegazy** [comment]
sorry for the delay.

**Comment by danzel** [comment]
Thanks! :)

**Pull request merged**
