### PR TITLE
react-navigation: Add params to state property

### PR DESCRIPTION
**Pull request by LinusU**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactnavigation.org/docs/en/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by LinusU** [comment]
I'm using `NavigationScreenProp` directly instead of going via `NavigationScreenProps`, therefor the `this.props.navigation.state.params` wasn't typed correctly for me.

`NavigationScreenProps` always types `screenProps` as `{ [key: string]: any } | undefined` so that doesn't work for me. I'm also not a fan of using types added as a "CUSTOM CONVENIENCE INTERFACES" since these will not be taken into account when the original library author develops the library.

**Comment by iRoachie** [comment]
Isn't using `NavigationScreenProps` the recommend way to attach navigation props to a component? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/18c6b474749f6e2a706d4d09d28a1912df70c875/types/react-navigation/react-navigation-tests.tsx#L508-L539

In what instance would you use `NavigationScreenProp` directly? I see you mentioned `screenProps` in your comment, but your change doesn't affect the typing of `screenProps`.

P.S just trying to understand the use case. If another maintainer understands and agrees i'm fine.

**Comment by LinusU** [comment]
> P.S just trying to understand the use case. 

Absolutely understand, it's good to discuss it 👍 

I'm currently using it like this:

```js
type AccountPageNavigationProps = (
  { mode: 'add', saveHandler?: () => void } |
  { mode: 'edit', id: string, saveHandler?: () => void } |
  { mode: 'view', id: string, saveHandler?: () => void } |
  { mode: 'import', inboxEntryId: string, saveHandler?: () => void }
)

interface AccountPageProps {
  navigation: NavigationScreenProp<{}, AccountPageNavigationProps>
  screenProps: {
    api: ApiInterface,
    state: UnlockedState | ConnectedState,
  }
}
```

I cannot use `getParam` since my `params` is a tagged union struct and I need to narrow the type by `if`-ing on the `.mode`.

> I see you mentioned screenProps in your comment, but your change doesn't affect the typing of screenProps.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/18c6b474749f6e2a706d4d09d28a1912df70c875/types/react-navigation/index.d.ts#L1193-L1200

When using `NavigationScreenProps` `screenProps` is always typed as above, I want those properties to be typed.

In the example you linked, you are typing the `params`, which is different from the `screenProps` (`params` comes from the `nagivate` call whereas `screenProps` is passed when mounting the navigator).

-----

All this being said, I still think that this is the _correct_ way to type `NavigationScreenProp`, regardless of the existance of `NavigationScreenProps` for one simple reason: `NavigationScreenProp` types `getParam` over `T extends keyof P` and `getParam` is just a simple wrapper that reads from `state.params`, thus whenever `getParam` is valid for `keyof P` `state` always have a `params` type that is `P | undefined`.

Hope this helps to clear it up a bit ☺️

**Comment by RyanCavanaugh** [comment]
@LinusU @iRoachie I don't have a lot of context here - is this OK to merge?

**Comment by iRoachie** [comment]
Yes! Sorry about that, you can merge it.

**Review by iRoachie — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
