### PR TITLE
React - more type safety for componentDidCatch

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Codesandbox example](https://codesandbox.io/s/4wll1oom1x)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

Because everything can be thrown (even `undefined`) and React doesn't change the thrown value we can't use `Error` here. I guess `unknown` would actually be the best type to avoid any runtime errors.

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Same errors with recent master. I'm not sure if they happen because of my change or something else...?

**Comment by FredyC** [comment]
@donaldpipowitch The PR ##30331 fixing all React tests failing has been merged so I recommend rebasing and it should be much easier to make tests passing here.

**Comment by donaldpipowitch** [comment]
Rebased ❤️Even includes the commits from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30054 now, which was merged some minutes ago.

**Comment by donaldpipowitch** [comment]
Of course this would require `// TypeScript Version: 3.0` now. I'm not sure what the policy for this is? When it's allowed to update this setting to a new major version?

**Review by danielkcz — CHANGES_REQUESTED** [review]
@donaldpipowitch Looking what this PR is actually about, I kinda don't agree with this. Even though you can eg. `throw "some string"` it's a really bad practice and I don't think it should be promoted this way. What's possibly worth is adding `undefined` next to `Error`

**Comment by donaldpipowitch** [comment]
> I kinda don't agree with this.

This change is also in discussion for the native `try/catch`. https://github.com/Microsoft/TypeScript/issues/26174

Even if "throw "some string" it's a really bad practice" would be a bad practice (this is imho arguable) one could literally throw anything (custom objects, classes, arrays...) and because the error could be thrown in some 3rd party code I can't rely on a good practice rule alone 😢 . Just adding `Error | undefined` would create false assumptions and can confuse users (which led to real world bugs in our code), because React doesn't alter the error before it's passed to `componentDidCatch` (except maybe filtering out Promises for Suspense).

**Comment by donaldpipowitch** [comment]
Is there a way to automatically update all deps of React to TS3.0 to avoid the `Error: ... depends on react but has a lower required TypeScript version.`. That are quite a lot for React^^ Especially if I don't know, if someone would approve this PR? 🤔

**Comment by FredyC** [comment]
Ok, I see. Either way, I don't think you can update to TS 3.0 just yet. There was [some discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30057#issuecomment-435301101) about it I did not fully comprehend. So I think you cannot really use `unknown` here :/

**Comment by donaldpipowitch** [comment]
I see 🤔 Thank you. I feared that. Than I'll close this PR for now. Thank you for your time and feedback.

**Pull request closed without merging**
