### PR TITLE
[papaparse] Fix missing namespace for an external interface

### PR DESCRIPTION
**Pull request by BehindTheMath**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes:
The un-namespaced `ReadableStream` is defined in `lib.dom.d.ts`. The `ReadableStream` referenced here should be the one defined in `@types/node`. See https://github.com/mholt/PapaParse/blob/fb6f96ea9901b523b1b296bee8dbdba568a2fefc/papaparse.js#L249-L252

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I'm not sure this is correct? Papaparse is something that can be used in the browser and in node. So is it valid that we're only accepting node streams according to this change?

**Review by johnnyreilly — CHANGES_REQUESTED** [review]
I'm not sure this is correct? Papaparse is something that can be used in the browser and in node. So is it valid that we're only accepting node streams according to this change?

**Comment by BehindTheMath** [comment]
@johnnyreilly [The README] (https://github.com/mholt/PapaParse/tree/fb6f96ea9901b523b1b296bee8dbdba568a2fefc#papa-parse-for-node) for this library specifies that these overloads are only for Node. The WebAPI `ReadableStream` and Node's `ReadableStream` have the same name, but they are very different. If you look at the source of this library, you'll see that it uses methods and properties which only exist on Node's `ReadableStream`.

**Comment by BehindTheMath** [comment]
@johnnyreilly Does this still need revision?

**Review by albertorestifo — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Sorry - I missed your comment. Thanks!

**Pull request merged**
