### PR TITLE
Made StepProps augmentable according to docs

### PR DESCRIPTION
**Pull request by Kuirak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/americanexpress/react-albus#step
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by conradreuter** [comment]
I don't really like the approach, tbh. I would rather have this as a generic parameter.

**Comment by Kuirak** [comment]
this approach should only be used for global additional props, if you want to enhance the Wizard Component in your code base. 

I agree that  generics would be better  for a local solution. On the long term we need both approaches. 

For me generics in Context Based Systems are really hard to do so I didn't do it cause I had no time for it.
You need to add the generic everywhere you use it manually, because  you will never know in which context your component is used when implementing it

**Comment by conradreuter** [comment]
I don't really see a use-case for the global additional props. Why would all of the wizards throughout your entire application share the same set of props?

I agree that adding the props in every location is tedious, but that's just the way context works. It's inherently not statically verifyable.

**Comment by Kuirak** [comment]
I used it for adding  `<Step skip={condition}>` functionality to all my Wizards.
But having typing  in the `<WizardWrapper onNext={context =>  if(context.step.skip) {/*....*/}/>`  component was/is really nice

Yes I could work around, with reexporting and the usage of any. but I prefer it this way

**Comment by amcasey** [comment]
Sounds like there are still some things to resolve here?

**Comment by conradreuter** [comment]
I think the PR is fine for me.

I would suggest renaming `WizardStepObject` to just `Step` to make it more concise and more aligned with the terminology in the library itself. We can add the generics in a backwards-compatible way later.

What do you think, @Kuirak?

**Comment by Kuirak** [comment]
I am fine with the rename. 
I pushed the suggested changes.

**Comment by conradreuter** [comment]
Coolsies! No more objections, @amcasey. (-:

**Pull request merged**
