### PR TITLE
Update BraintreeNode: Transaction Gateway interface

### PR DESCRIPTION
**Pull request by malewis5**
Add a type for adjustAuthorization to the Transaction Gateway.
Seen here: https://developer.paypal.com/braintree/docs/reference/request/transaction/adjust-authorization

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developer.paypal.com/braintree/docs/reference/request/transaction/adjust-authorization>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree@latest/))
was missing the following properties:
1. GraphQL
1. version
1. errorTypes
1. CoinbaseAccount
1. AmexExpressCheckoutCard

<details>
<summary>as well as these 5 other properties...</summary>
<p>PaymentInstrumentTypes, WebhookNotification, TestingGateway, UsBankAccountVerification, ValidationErrorCodes</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cb54b370a614e60337c2c05cc45a820caaf3fdab
</p>

**Review by amcasey — APPROVED** [review]
LGTM, but please confirm that that API was available in 2.22 and, if not, bump the version in the header.

**Comment by malewis5** [comment]
> LGTM, but please confirm that that API was available in 2.22 and, if not, bump the version in the header.

This was made available in [3.30](https://github.com/braintree/braintree_node/blob/master/CHANGELOG.md#330). I'll update the header. Thanks.

**Comment by amcasey** [comment]
@malewis5 I don't see a version 3.30 on npm - possibly you meant 3.3?

**Comment by malewis5** [comment]
> @malewis5 I don't see a version 3.30 on npm - possibly you meant 3.3?

Sorry about that. A typo on my end. Meant to be 3.3.0.

**Comment by amcasey** [comment]
NP, but DefinitelyTyped manages the patch version itself, so you'll just want "3.3" (i.e. instead of "3.3.0").

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by malewis5** [comment]
Ready to merge

**Pull request merged**
