### PR TITLE
Add an optional property that is supported in Chrome 120

### PR DESCRIPTION
**Pull request by Tomo5524**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Exclusive accordion](https://developer.chrome.com/blog/css-wrapped-2023#named-details) . In my Nextjs project, I had to manually add name property to `index.d.ts` file. 
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## babel-plugin-react-html-attrs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/babel-plugin-react-html-attrs@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'babel-plugin-react-html-attrs'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act

## Formatting

The following files are not formatted:
1. types/react/test/elementAttributes.tsx
1. types/react/ts5.0/test/elementAttributes.tsx
1. types/react/v17/test/elementAttributes.tsx
1. types/react/v16/test/elementAttributes.tsx

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 463d8114e42d158860c48ca48d6af55417a83571
</p>

**Review by eps1lon — APPROVED** [review]
Thanks!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by Tomo5524** [comment]
> Ready to merge

**Comment by Tomo5524** [comment]
Ready to merge

**Pull request merged**
