### PR TITLE
fix(spritesmith): image result is Transform for processImages and Buffer for run

### PR DESCRIPTION
**Pull request by OlenDavis**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [the Transform created in `processImages`](https://github.com/twolfson/spritesmith/blob/master/src/smith.js#L127) vs [the buffer created in `run`](https://github.com/twolfson/spritesmith/blob/master/src/smith.js#L86)
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~

CC @twolfson and @Zenoo

### CODE REVIEW

**Review by Zenoo — CHANGES_REQUESTED** [review]
@OlenDavis I am not sure a generic interface is the way to go if the types are indeed different.

Having two separate interfaces extending the same base would be best, I think.

**Comment by OlenDavis** [comment]
@Zenoo I chose to make the result type a generic for cleanliness and backwards compatibility with how you'd originally wrote these types, in case anyone else had many been importing it. If I had chosen instead to split it into two interfaces with a common base interface, one would have to be called the original type name for backwards compatibility, and then the base result type and other fixed result type would need to be given new names like `ResultBase` and `ResultBaseTransform` or worse. When in reality, there's really only one type for the result, and the only thing that's sometimes different about it is its image property's type. 

So ultimately, using a generic allows for cleaner/literal naming by preserving your original naming of the type, thus allowing for backwards compatibility, while also fixing the more serious problem of the type for the result's image property being inaccurate for the other method.

**Comment by Zenoo** [comment]
The thing I'm hesitant about having the generic type is that it complexifies the use.
If you use this library without prior knowledge, you have no idea you need to use Buffer or Transform in your generic type.

Having two separate interfaces would negate this issue while keeping the same functionality.

**Comment by OlenDavis** [comment]
Having two separate interfaces to import doesn't itself solve that problem of informing which interface to use though. Because if a developer is importing all these artificial DefinitelyTyped types rather than just importing the real documented JS functionality and relying on DefinitelyTyped to inform its typing, then they're already writing brittle typescript by over-specifying their types with these artificial types. They could import the one result interface but then use the other method which returns the other interface, or vice-versa.

i.e. what matters is that when a developer does `import Spritesmith from 'spritesmith'` and then actually uses it, that all the types they're returned from the actual API when doing so are accurate and clear, which they are now with this PR. If instead they're importing and using _types_ from this DefinitelyTyped, what's brittle about their code is that it's tied to artificial types created here, not to the documented API of spritesmith. 'Cause if the spritesmith library were to become rewritten in TS later on, even without a single breaking change to its API, those devs code would break unless it spritesmith's TS rewrite _also_ preserved the naming _and exported_ all the undocumented types created here in DefinitelyTyped.

**Review by Zenoo — APPROVED** [review]
I can understand your point of view. I don't really share it, but in the end the functionality is the same, so I don't really mind either way.

**Comment by OlenDavis** [comment]
Ready to merge

**Pull request merged**
