### PR TITLE
Update JQuery UI Layout definitions

### PR DESCRIPTION
**Pull request by drarmstr**

### CODE REVIEW

**Comment by Steve-Fenton** [comment]
I have one question - there don't appear to be any changes to tests for this commit. This makes it highly likely someone could cause a regression in a future change. Should there be some additional tests to ensure the behaviour added in this change remains in a working state?

**Comment by drarmstr** [comment]
Sorry, there weren't any tests originally for this definition that I saw.  Is there any documentation on how tests should be prepared or how to deal with the "Travis Cl" build issue above?

**Comment by Steve-Fenton** [comment]
Let's start with the build issue. The main problem is that `JQueryAnimationOptions` is not defined. Did you mean to define this or is it in another file?

**Comment by drarmstr** [comment]
Yes, `JQueryAnimationOptions` is defined by JQuery.  I removed the `<reference path>` because it seems wrong to assume the relative directory structure like this when we don't know exactly how the users may organize their definitions.  The user should have included their own JQuery definitions to pull this in.  Adding back the `<reference path>` will fix this and I can do that if this is your preferred approach.

**Comment by Steve-Fenton** [comment]
Yes please - the paths to the definitions are pretty solid, because when you load in a package containing a Definitely Typed definition, it always places it in the same place in your project. Plus the build system needs it :)

**Comment by drarmstr** [comment]
Ok @Steve-Fenton, I have updated the push request so it passes the Travis CI requirements.

**Comment by Steve-Fenton** [comment]
:+1:

**Comment by drarmstr** [comment]
@Steve-Fenton Is this ok for merging then?

**Comment by Steve-Fenton** [comment]
@drarmstr looks good to me. We probably ought to have a task to backfill some tests - this definition was created before we started adding tests to the repo (we were wearing short trousers and watching The Hunger Games back then).

**Comment by drarmstr** [comment]
@Steve-Fenton: Sorry, I'm a bit new to GitHub and have just learned that you should always do push requests from private branches, not private master, since all new commits get included in pending push requests.  I cleaned out the new commits from my master branch to keep this push request clean.  Could we resolve and merge this request so I could move forward with other new requests (now properly from a branch)?

**Pull request closed without merging**
