### PR TITLE
express-http-proxy: Add definition for userResDecorator

### PR DESCRIPTION
**Pull request by jsinglet**
Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: It is sometimes necessary to access this attribute. This change exposes it. 
- [ x] Increase the version number in the header if appropriate.
- [ x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andrewbranch** [comment]
/azp run DefinitelyTyped.BenchmarkPR

👋 Please ignore me, I'm testing something out and have randomly selected this PR to bother 😄

**Review by niekvb — APPROVED** [review]

**Review by beltschatsar — COMMENTED** [review]
Should also be returning same type as the second parameter, according to https://github.com/villadora/express-http-proxy/blob/master/test/userResDecorator.js

**Comment by beltschatsar** [comment]
@jsinglet is it too late to you to fix it ? 

Would expect also these tests to work with the typings:

````javascript
proxy('www.google.com', {
    userResDecorator(proxyRes, proxyResData, userReq, userRes) {
        // some code
        return proxyResData;
    }
});

proxy('www.google.com', {
    userResDecorator(proxyRes, proxyResData, userReq, userRes) {
        // some code
        return Promise.resolve(proxyResData);
    }
});
````

**Comment by jsinglet** [comment]
> @jsinglet is it too late to you to fix it ?
> 
> Would expect also these tests to work with the typings:
> 
> ```js
> proxy('www.google.com', {
>     userResDecorator(proxyRes, proxyResData, userReq, userRes) {
>         // some code
>         return proxyResData;
>     }
> });
> 
> proxy('www.google.com', {
>     userResDecorator(proxyRes, proxyResData, userReq, userRes) {
>         // some code
>         return Promise.resolve(proxyResData);
>     }
> });
> ```

Happy to fix, but isn't this also the case with `userResHeaderDecorator`? I was trying to follow along with the conventions before me and wasn't sure how you were handling promise and non-promise forms.

**Comment by jsinglet** [comment]
> @jsinglet is it too late to you to fix it ?
> 
> Would expect also these tests to work with the typings:
> 
> ```js
> proxy('www.google.com', {
>     userResDecorator(proxyRes, proxyResData, userReq, userRes) {
>         // some code
>         return proxyResData;
>     }
> });
> 
> proxy('www.google.com', {
>     userResDecorator(proxyRes, proxyResData, userReq, userRes) {
>         // some code
>         return Promise.resolve(proxyResData);
>     }
> });
> ```

@beltschatsar happy to fix, but isn't this the same case for `proxyReqOptDecorator` (and others)? I was trying to make the change following along with the conventions before me -- how are you handling the promise and non-promise forms?

**Comment by beltschatsar** [comment]
According to test, the same type as the first parameter can be returned for userResHeaderDecorator. Test would tell if typings are ok (which I think it is but...)

Envoyé de mon iPhone

Le 17 mai 2019 à 13:20, John L. Singleton <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jsinglet<https://github.com/jsinglet> is it too late to you to fix it ?

Would expect also these tests to work with the typings:

proxy('www.google.com<http://www.google.com>', {
    userResDecorator(proxyRes, proxyResData, userReq, userRes) {
        // some code
        return proxyResData;
    }
});

proxy('www.google.com<http://www.google.com>', {
    userResDecorator(proxyRes, proxyResData, userReq, userRes) {
        // some code
        return Promise.resolve(proxyResData);
    }
});

Happy to fix, but isn't this also the case with userResHeaderDecorator? I was trying to follow along with the conventions before me and wasn't sure how you were handling promise and non-promise forms.

**Comment by beltschatsar** [comment]
Here is the missing tests:
````javascript
proxy('www.google.com<http://www.google.com>', {
    proxyReqBodyDecorator(bodyContent, srcReq) {
        // some code
        return bodyContent;
    }
});

proxy('www.google.com<http://www.google.com>', {
    userResHeaderDecorator(headers, userReq, userRes, proxyReq, proxyRes) {
        // some code
        return headers;
    }
});
````

**Comment by jsinglet** [comment]
> Here is the missing tests:
> 
> ```js
> proxy('www.google.com<http://www.google.com>', {
>     proxyReqBodyDecorator(bodyContent, srcReq) {
>         // some code
>         return bodyContent;
>     }
> });
> 
> proxy('www.google.com<http://www.google.com>', {
>     userResHeaderDecorator(headers, userReq, userRes, proxyReq, proxyRes) {
>         // some code
>         return headers;
>     }
> });
> ```

No problem, I'll add them...

**Comment by jsinglet** [comment]
@beltschatsar -- please see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35547

I've added the promise forms - I didn't add tests for definitions that aren't yet a part of that file.

**Pull request merged**
