### PR TITLE
React: Support for defaultValue in HTMLAttributes 

### PR DESCRIPTION
**Pull request by maglar0**
https://facebook.github.io/react/docs/forms.html#default-value

### CODE REVIEW

**Comment by jbrantly** [comment]
Can you make this change on `react-addons.d.ts` and `react-global.d.ts` as well?

**Comment by vvakame** [comment]
@pspeter3 @vsiao could you review this PR too?

**Comment by vsiao** [comment]
ok, might as well add `defaultChecked` as well. Please also follow the instructions in the README located at https://github.com/borisyankov/DefinitelyTyped/tree/master/react to keep the `.d.ts` files in sync, as @jbrantly said.

**Comment by pspeter3** [comment]
:+1:

**Comment by jbrantly** [comment]
+1 from me

**Comment by vvakame** [comment]
@vsiao @pspeter3 @jbrantly thanks!
@maglar0 thanks mate!

**Pull request merged**
