### PR TITLE
React-data-grid: adding Data and DraggableHeader

### PR DESCRIPTION
**Pull request by martinnov92**
Hello,

in this definition file is a few missing pieces, I tried to add exports for Data and DraggableHeader as I can't use it without errors in our project.

I am not in any mean the typescript pro so I hope I did this right.

Thank you.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: `https://github.com/adazzle/react-data-grid/blob/058eef31d79116e3f12ce8b9c72550692a43905f/packages/react-data-grid-addons/src/index.js`
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by SupernaviX** [comment]
Thanks for the PR!

This looks like it'll work, but the Selectors typings could be more specific. Looking at the [file in question](https://github.com/adazzle/react-data-grid/blob/058eef31d79116e3f12ce8b9c72550692a43905f/packages/react-data-grid-addons/src/data/Selectors.js), those are both a selector type from a package named reselect. Would you mind updating those types?

**Comment by martinnov92** [comment]
Hello @SupernaviX , I would like to do it, but I am not so sure how more specific I should be 😄 .

**Comment by SupernaviX** [comment]
Looking at some examples from react-data-grid docs, it looks like these selectors are functions that take the state and return an array of rows. Probably typing them as `(state: object) => object[]` would be specific enough to make it clear how to use them

**Comment by KieranPeat** [comment]
Also, do you want to change the test file as well?
It just needs to be a simple test to make sure it compiles when given the correct type.

**Comment by martinnov92** [comment]
Hello @SupernaviX and @KieranPeat , thank you for your advices, I tried to do what you said, but when I ran tsc it did not compile, it showed error error TS2304: `Cannot find name 'object'.`, so I changed all the 'object' from index.d.ts to 'Object'. Hope it is ok, otherwise I will change it back again...

**Comment by SupernaviX** [comment]
@martinnov92 `object` is a new feature of TypeScript 2.2, which these typings already depend on. It's different from `Object` (see https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type for exactly how). If you're getting an error that says it doesn't exist, you might need to update your local TypeScript version.

**Comment by martinnov92** [comment]
@SupernaviX Thank you for explanation! I change it back to object, hopefully now it is all gonna be ok. thank you

**Comment by SupernaviX** [comment]
LGTM 👍

**Comment by martinnov92** [comment]
@SupernaviX Hello, do you know if this is gonna get merge anytime soon? Thank you

**Comment by KieranPeat** [comment]
Is there any tests that could be put around DraggableHeader?

**Comment by martinnov92** [comment]
@KieranPeat  Is it necessary?

**Comment by martinnov92** [comment]
@SupernaviX or @KieranPeat do you know if is it possible to somehow extend this declaration file in my component where I am using ReactDataGrid? I need to make something work and this is slowing me down. Thank you

I tried something like this 
```
declare module 'react-data-grid' {
    interface GridProps {
        onRowClick: (rowId: number, width: number) => void;
    }
}
```

and several other combinations, but can´t make it work :/ Thank you

**Comment by SupernaviX** [comment]
@martinnov92 PRs are merged by Microsoft staff here, it could be a few days until it's merged. If you need these for local work in the meantime, my workflow for temporary typings has been:
- Add a top-level typings folder to the project
- Add a typeRoots property to tsconfig.json telling tsc to look for types there:
```
    "typeRoots": [
      "node_modules/@types",
      "typings"
    ]
```
- Copy the typedefs into typings/react-data-grid
- Remove @types/react-data-grid from node_modules
- Wait for the PR to get merged and remove the local typings

What are you trying to accomplish by extending the declaration files? Looking at the react-data-grid code, that onRowClick definition is inaccurate (and actively conflicts with these typings).

**Comment by martinnov92** [comment]
@SupernaviX  Hello, thank you for such a detailed answer... I need to use onRowClick in our project, but since it is not in the old typings (but DraggableHeader and Data is working, but in the new version 2.0.0 it is not...), I thought I could somehow extend it without breaking it 😄 . Never mind I think I will wait for merge. Thank you

**Pull request merged**
