### PR TITLE
Add TypeScript definitions and tests for Bootstrap TouchSpin

### PR DESCRIPTION
**Pull request by albinsunnanbo**
For [Bootstrap TouchSpin](http://www.virtuosoft.eu/code/bootstrap-touchspin/)

### CODE REVIEW

**Comment by vvakame** [comment]
@albinsunnanbo thank you for your contributions.
please check this document. http://definitelytyped.org/guides/contributing.html#naming-the-file
rename jquery.bootstrap-touchspin/jquery.bootstrap-touchspin.d.ts to bootstrap-touchspin/bootstrap-touchspin.d.ts

**Comment by albinsunnanbo** [comment]
Hi
The js file in TouchSpin is [jquery.bootstrap-touchspin.js](called https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/blob/master/src/jquery.bootstrap-touchspin.js)
I agree that bootstrap-touchspin is a more succinct name and matches the project name. However I thought keeping that js-file name into the TypeScript definitions would make users more confident that they found the right definition file.

But if you still think that bootstrap-touchspin/bootstrap-touchspin.d.ts is a better name I'll change.

**Comment by vvakame** [comment]
@albinsunnanbo I think bootstrap-touchspin/bootstrap-touchspin.d.ts is a better name still.
`bootstrap-touchspin` is on a https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/blob/master/package.json#L2 (but it is not published to npm and bower...

**Comment by albinsunnanbo** [comment]
Well, then I agree.
I have rebased on latest master and renamed files.

**Comment by vvakame** [comment]
@albinsunnanbo thanks mate!

**Pull request merged**
