### PR TITLE
[spotify-api] Fix ReplacePlaylistTracksResponse to have snapshot_id

### PR DESCRIPTION
**Pull request by nfaltermeier**
The new playlist snapshot ID is returned when replacing tracks in a playlist. I have verified this with the REST API.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.spotify.com/documentation/web-api/reference/#/operations/reorder-or-replace-playlists-tracks
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Some-Dood** [comment]
> Trying to approve this, but the review controls are not shown anywhere. Does anyone know why?

They're kinda tucked inside the `Files Changed > Review Changes` dropdown. Shall I approve it on your behalf or nah?

**Review by BastiDood — APPROVED** [review]
Approving on behalf of @Stadly. Thanks for your contribution!

**Comment by Some-Dood** [comment]
Since it's been five days or so, I hope you don't mind that I approved it. 🎉

**Review by Stadly — APPROVED** [review]

**Comment by Stadly** [comment]
I've been unavailable for the last few days, so thanks for approving on my behalf, @Some-Dood.

**Comment by Stadly** [comment]
Ready to merge

**Pull request merged**
