### PR TITLE
[validator] Refactor validator to ES6 import/export module style

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Improvement to existing type definition.
- Refactor `validator.d.ts` and enable to `validator` can **import that default export by omitting the curly braces** and **import only a subset of the library**.

Example:

```
import validator from 'validator';
import { blacklist, contains } from 'validator';
```
- Besides keeping original API test cases, it adds import tests.

---

I found this definition, it can't import like [validator document](https://github.com/chriso/validator.js#es6) describe.

It's because of invoking `export =` in the original definition, it won't export more any modules. It blocks `validator` has real ES6 module feature.

Therefore, I send this PR after I refactor a new file as `validator-es6-tests.ts`. I want to invite validator authors to review this, and not cover the original definition. When this PR get prove, I hope it will be the formal definition next PR.

If validator authors have any questions, please let me know. Thanks.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
@andy-ms, please tag this `Awaiting reviewer feedback`.

**Comment by andy-ms** [comment]
I don't want to have 2 different versions of the same thing.
It looks like validator [does](https://github.com/chriso/validator.js/blob/master/index.js#L285) in fact have an export named `default`, so you should be able to just update the current definition.

**Comment by andy-ms** [comment]
Also, looks like [isIso8601](https://github.com/chriso/validator.js/blob/master/lib/isISO8601.js) has a different type for the default export (function) and named export (regex).

**Comment by TonyPythoneer** [comment]
Close. I found better solution about this. I will send new PR.

**Comment by TonyPythoneer** [comment]
@andy-ms Would you talk more about that? I think I don't understand.

**Comment by andy-ms** [comment]
I was just looking at the code [here](https://github.com/chriso/validator.js/blob/master/lib/isISO8601.js) and noticed that `exports.default` is a function while `exports.iso8601` is a regexp.

Actually, it looks like I missed the `is` part of that name, so that's a red herring.

But in your PR you had:

```ts
declare module "validator/lib/isISO8601" {
    export const isISO8601: ValidatorJS.Validators.isISO8601;
    export default isISO8601;
}
```

If there's no `exports.isISO8601` and there's only a default export, you don't need `export const isISO8601`, you should be able to do it with a single function declaration `export default function isISO8601(arg: ArgType): ResultType`.

**Comment by TonyPythoneer** [comment]
@andy-ms Yes, you are right.

I have a question. In Typescript, how do I implement the equivalent codes as following?
```
var isEmail = require('validator/lib/isEmail');
isEmail('...')
```

When I declared a module as "validator/lib/isEmail" in TypeScript:
```
declare module "validator/lib/isEmail" {
    function isEmail: ...;
    export default isEmail;
}
```

I use it in TypeScript:
```
import isEmail from `isEmail`;
isEmail(...)
```

It compiles to es5 as this:
```
var isEmail = require('validator/lib/isEmail');
isEmail.default(...)
```

But it will be failed, this code is successful in Node.js:
```
var isEmail = require('validator/lib/isEmail');  // The isEmail is function, not a module or object
isEmail('...') // It doesn't need invoking `default`. It can directly use.
```

**Comment by louy** [comment]
```ts
export = isEmail;
```

**Comment by TonyPythoneer** [comment]
@Iouy Module '"validator/lib/isEmail"' resolves to a non-module entity and cannot be imported using this construct.

**Comment by louy** [comment]
with
```ts
import isEmail = require('isEmail');
```

**Comment by TonyPythoneer** [comment]
@louy The deinition is not pass. It causes complier can't correctly complie.

By the way, `import isEmail = require('isEmail');` is equivalent to `import * as isEmail from 'isEmail'`. If I want to use isEmail function, it need to do like `isEmail.isEmail(...)`.

**Comment by louy** [comment]
Ah I see. sorry I misunderstood you.
```ts
declare module "validator/lib/isEmail" {
    export function isEmail /*...*/;
}
```

with
```ts
import {isEmail} from `isEmail`;
```

**Comment by andy-ms** [comment]
`isEmail` uses [`export default`](https://github.com/chriso/validator.js/blob/master/src/lib/isEmail.js#L23) and the typings should reflect that.

**Comment by louy** [comment]
i'm not sure why you wouldn’t declare it in the lib file and export it in `index.ts`:
```ts
// index.ts
import isEmail from `validator/lib/isEmail`;
export {isEmail};
```

**Comment by andy-ms** [comment]
@louy see my above comment.

**Comment by louy** [comment]
oh yeah that makes sense now. :)

**Comment by TonyPythoneer** [comment]
@andy-ms The original defintion can do subset import

In defintion:
```
declare module "validator" {
  const validator: ValidatorJS.ValidatorStatic;
  export = validator;
}
```

It can do `import {isEmail} from "validator"` and won't be error.
From my understanding, the `validator` is typed as `ValidatorStatic`, is also considered a object. When using `export = validator;`, it's okay because the object can be resolve a module. If my understanding is not completely exact or you have better explanation, please tell me.

Although "validator/lib/isEmail" doesn't need to define, I expect it's able to do:
```
import isEmail from `isEmail`;
isEmail(...) // it will return true or false
```
I still want to use Typescript to define that. Therefore, I need your help. 😄 

The `validator`  source project is complied by `Babel`, maybe some processing details are different with `Typescript`. Especially, parse module when calling import default module such as `import isEmail from 'validator/lib/isEmail';`, it can get function, not module. This difference needs to investigate how to implement equivalent code by Typescript.

**Comment by andy-ms** [comment]
From [index.js](https://github.com/chriso/validator.js/blob/master/index.js):
```js
exports.default = validator;
module.exports = exports['default'];
```

Sorry, this was quite confusing.
The line `exports.default = validator;` will have no effect because `module.exports` gets overwritten and therefore the original `exports` is unreachable.

So this is just equivalent to `module.exports = validator`.

So you're right, `export =` is correct and `export default` is wrong.
Despite the original source code using `export default` and their example using a default import!

So as far as we are concerned right now, it needs to stay using `export =`.


## Explanation

This is the fault of [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports), which adds `module.exports = exports['default'];`.

This means that TypeScript users can't import the library the way it was designed to be imported! The following code:

```ts
import v from "validator";
console.log(v)
```

when run, will print `undefined`, because `require("validator").default` is undefined.

It would be nice if they instead did:

```js
module.exports = validator;
module.exports.default = validator;
```

So we could then support the default import syntax (and thereby support users who don't have `--module commonJs` turned on).
Maybe we should file an issue with `babel-plugin-add-module-exports`?

Pinging @mhegazy

**Comment by andy-ms** [comment]
@TonyPythoneer: You are correct, you can do `import { blah } from "foo"` if "foo" has a `export = foo` where `foo.blah` is valid.

**Pull request closed without merging**
