### PR TITLE
D3 version 4 TypeScript 2.0

### PR DESCRIPTION
**Pull request by tomwanzek**
This is the PR for the **first batch** of D3 module definitions as per the roadmap suggested in response to issue #9936 .

Please refer to the issue for the wider context of this PR.

cc: @gustavderdrache, @borisyankov,@mhegazy, @vvakame , @ledragon, @jnm2

Module coverage:
_d3-array, d3-axis, d3-brush, d3-chord, d3-collection, d3-color, d3-dispatch, d3-drag, d3-ease, d3-force, d3-format, d3-hierarchy, d3-interpolate, d3-path, d3-polygon, d3-quadtree, d3-queue, d3-random, d3-scale, d3-selection, d3-shape, d3-time, d3-time-format, d3-timer, d3-transition, d3-voronoi, d3-zoom_

Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

**Edit:** included d3-force and d3-queue in listing above, as they have since been added.

### CODE REVIEW

**Comment by tomwanzek** [comment]
It seems on Travis it tried to compile with TS 1.8.7?

**Comment by mhegazy** [comment]
looks like the same issue failing the CI server like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10223. @andy-ms can you update the definition-tester and merge this PR?

**Comment by tomwanzek** [comment]
Added d3-force modules complete with tests. Again, not sure why the failure occurs on Travis.

**Comment by ocombe** [comment]
So it looks like the test are passing, any chance this could be merged ?

**Comment by gustavderdrache** [comment]
I haven't looked over this as thoroughly as I would like. I've got a few clarification questions I'd like to ask before I give my thumbs up to this.

**Comment by gustavderdrache** [comment]
I'd like to start these comments off by saying that this work is absolutely incredible, and that even if none of my comments are addressed, I would gladly welcome this contribution. You really raised the bar with the `Selection` interface.

Unfortunately, being me (a terrible person), I do have a few comments and style nitpicks. I'll say right away that I'm only going to fight for the first item because I am _extremely_ opposed to the contagion that is the `any` type.

1. [`var event` in `d3-selection`](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-selection/index.d.ts#L240) has type `any` when I feel it really shouldn't. In previous incarnations, `var Event` was a merger of `KeyboardEvent` and `MouseEvent`, until #5756 came along. What came out of that was defining `event` to be one of the two base event types (either a custom D3 event or a DOM event). This mirrors the behavior of [lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L14285), which requires users to use ascription when they know the `event` variable has a more specific type:

  ```typescript
  // This is admittedly a silly example, but it should get the point across
  document.addEventListener("keydown", () => {
    if ((event as KeyEvent).which === 27) { /* ... */ }
  });
  ```

  My point is that `event` has a known base type, and that should be used instead of `any` because now the type checker knows that `d3.event` doesn't have a property named `asdf`, unless the user tells it it does.

  This also happens with stuff that has a `baseEvent` or `originalEvent` (like in [`d3-brush`](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-brush/index.d.ts#L41)). Those should be of the base event type as well. Unless they're DOM events, in which case the standard `Event` interface works.

2. It seems like you could save yourself a lot of headache by adding a small type alias:

  ```typescript
  export type Numeric = number | { valueOf(): number }
  ```

  From the looks of it, you seem opposed to adding unnecessary aliases, which is something I appreciate and applaud, but it's probably going to be easier on both clients and maintainers of this d.ts file. It's the reason I wound up creating [the `Primitive` alias](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L424-L427) back in the day -- it was kind of a hack to name things that worked well as DOM attribute values.

  This could be used in the shape definitions (since `pie()` returns a `Pie<any, number | { valueOf(): number }>`), scales, and probably event the array ones as well, since they just default to the regular-flavor `<` operator, which has defined semantics on objects with a `valueOf()` operator:

  ```typescript
  let o = { valueOf() { return 5; } };
  o > 42 // false
  o < 42 // true
  ```

3. Nitpick: In `d3-scale`, most scales accept `number | { valueOf(): number }`, except for [`ScaleSequential`](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-scale/index.d.ts#L211-L212). Is this intentional?

4. Nitpick: you're not quite consistent with callback parameters. Sometimes [they're optional](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-collection/index.d.ts#L49), sometimes [they're not](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-collection/index.d.ts#L40). As a matter of style, I'd rather the signature not have any `?` for callbacks, since the assignability relation will allow a user to omit the parameters in their implementation:

  ```typescript
  declare function foo(fn: (foo) => void);

  foo(() => {}); // legal
  foo((foo) => {}); // legal (matches signature exactly)
  foo((foo, bar) => {}); // illegal: too many parameters expected
```

Also, as an aside, I noticed your comment in [`d3-voronoi`](https://github.com/tomwanzek/DefinitelyTyped/blob/e511e4819e765da36dd026e69a963d2af4162735/d3-voronoi/index.d.ts#L11-L15) and played around with it in the [playground](http://www.typescriptlang.org/play/index.html#src=interface%20Pair%3CT%3E%20extends%20Array%3CT%3E%20%7B%0D%0A%090%3A%20T%3B%0D%0A%091%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Alet%20bad%3A%20Pair%3Cnumber%3E%20%3D%20%5B1%5D%3B%0D%0Alet%20good%3A%20Pair%3Cnumber%3E%20%3D%20%5B1%2C%202%5D%3B). I found that you can extend `Array<T>` and just define the properties yourself (since this is how tuples work internally):

```typescript
interface Pair<T> extends Array<T> {
  0: T;
  1: T;
}

let bad: Pair<number> = [1]; // nope
let good: Pair<number> = [1, 2]; // yup!
```

Do with this information what you will.

**Comment by tomwanzek** [comment]
Thanks @gustavderdrache. I will go through your comments shortly, most appreciated. FYI, I have just finished a fix for the outstanding issue on d3-axis (i.e. avoiding unnecessary coupling to d3-time). I will add a commit to this PR to apply the fix.

I will provide a separate status check point comment on the tracking issue #9936.

**Comment by tomwanzek** [comment]
O.k. Had a quick glance at the above:

_Ad 1)_ I will provide a follow-up comment, you are right this is not what I had hoped for either. But it came about after digging through the source code/tests and some of the patterns that surfaced there.

_Ad 2)_ I am with you in principle on the type aliases for maintainability. The rationale why I stopped using some of the most pervasive ones, like your example `Numeric` is as follows. Each individual d3-module exports into the same `d3` **global** when used as a vanilla script (This is D3 as per Mike's design). It also gets  re-exported as part of the standard D3 bundle. Having `Numeric` defined in each individual module, would create duplicate identifier problems. Defining the semantically same type alias just with a slightly altered name in each module, is a path I did not want to go at the time (e. g. `PieNumeric`, `ArrayNumeric` etc.) Where I could define an alias that can reasonably be imported following a _proper D3 module dependency_, I have done so (e.g. `BaseType` between **d3-selection** and **d3-transition**.

_Ad 3)_ Good catch. I believe, this can be generalized to a coercible-to-number. I'll check again and amend the PR.

_Ad 4)_ Correct. Will add a chore to establish consistency and amend PR in follow-up.

As for your added `d3-voronoi` hint, I think this should be something that can be carried over. I will do a sweep of the source code to check something related and if all goes well tighten up the interface.

**Comment by gustavderdrache** [comment]
1. I looked through the events and it looks like you're right. There really aren't any guarantees about a custom event (save for the fact that D3 writes appends a `sourceEvent` field). Alas.
2. D'oh! I completely forgot about the namespace clashing. I haven't really looked at how TS 2.0's new export features work, so it looks like I've got some homework to do.

**Comment by ocombe** [comment]
\o/
Awesome ! We can use it now, right ?

**Comment by tomwanzek** [comment]
@andy-ms Thanks a lot for merging. Any follow-ups for the other D3 modules or to close off the chores mentioned above I will do as new PRs referring to the same issue #9936 for tracking.

@ocombe I think there is a publication job moving the definitions in the `types-2.0` branch into the @types org on npmjs. Then you can use them with `npm install @types/d3-selection --save` or the like. (I just checked, but it has not run yet.)

The main handycap the definitions merged with this PR have, is that they individually still do not export to the to the `d3` global for vanilla script use. This is the [TypeScript issue 9681](https://github.com/Microsoft/TypeScript/issues/9681) on which I have unfortunately not yet seen any comment/response to date.

**Comment by ocombe** [comment]
@andy-ms any idea how long it will take until this is published to npm ?

**Comment by ocombe** [comment]
For anyone interested, they are now available on npm !!!

**Pull request merged**
