### PR TITLE
Add support to .component from Angularjs 1.5

### PR DESCRIPTION
**Pull request by andrejunges**

### CODE REVIEW

**Comment by vvakame** [comment]
thanks mate!

**Comment by Tushkiz** [comment]
Hi,
Can you update the `IComponentOptions`

[Angular Doc](https://code.angularjs.org/1.5.0-rc.0/docs/api/ng/type/angular.Module) says `template` is either string or function `template – {string=|function()=}`

Also
`$canActivate – {function()=}`
`$routeConfig – {object=}`

can be added to it.

```typescript
interface IComponentOptions {
  bindings?: Object;
  controller?: string|Function;
  controllerAs?: string;
  isolate?: boolean;
  template?: string|Function;
  templateUrl?: string|Function;
  transclude?: boolean;
  restrict?: string;
  $canActivate?: Function;
  $routeConfig?: Object
}
```

Thanks.

**Comment by andrejunges** [comment]
@vvakame should I replace those `,`with `;`?

**Comment by Tushkiz** [comment]
yes there should be `;`
I already did a 'pull request' for that. see #7315

**Comment by andrejunges** [comment]
oh ok, nice!
srry for not doing that initially, didn't know about it.

**Comment by Tushkiz** [comment]
No Problem pal :+1:

**Pull request merged**
