### PR TITLE
Convert the repo into a pnpm monorepo

### PR DESCRIPTION
**Pull request by jakebailey**
There's way too much to explain here; https://jakebailey.dev/posts/pnpm-dt-3/ contains a big overview of why we're doing this, what this changes, and so on.

The TL;DR is:

- The repo is now managed by `pnpm`. You'll need `pnpm` to work on DT (for the most part).
- `package.json` is now _required_ and replaces the header in `index.d.ts` entirely.
- Dependencies are all now _explicit_, no more heuristic.
- You can use `pnpm`'s `--filter` (https://pnpm.io/filtering) to scope down which packages you actually need, rather than installing the entire repo.
  - If you want to work on `@types/node`, `pnpm install -w --filter '@types/node...'`.
  - If you want to work on `@types/node` _and_ test what depends on it, `pnpm install -w --filter '...@types/node...'`. 

This change:

- Unblocks `fetch` in `@types/node@18`.
- Unblocks `node16` / `nodenext` resolution.
- Fixes loads of `react` packages that are broken due to `typesVersions`
- Makes CI a lot faster.

And probably more I'm forgetting.

Thank you @sandersn and @andrewbranch, @zkochan, probably more I'm forgetting.

ref https://github.com/microsoft/DefinitelyTyped-tools/issues/751

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
This PR is far too big to complete with a single runner given the 6 hour timeout; I want to eventually shard CI but certainly not now.

Merging, so we can start fixing infra and unblock PRs.

**Comment by mikex-oss** [comment]
Hi, after this change, the licensing terms seem to be inconsistent and missing info.

https://github.com/DefinitelyTyped/DefinitelyTyped#license

> Copyrights on the definition files are respective of each contributor listed at the beginning of each definition file.

This change:

> package.json is now required and replaces the header in index.d.ts entirely.

https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners

> Note that this list is not used to provide credit for contributions; it is only used for managing PR reviews.

Where does the contributor copyright info live?

**Comment by jakebailey** [comment]
Those docs are out of date, it seems; the header is not for copyright anything, but instead was only used for managing "ownership" of packages for review purposes and nothing else.

The git history tracks contribution history.

**Comment by mikex-oss** [comment]
I see. Could https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE be updated to reflect this?

**Pull request merged**
