### PR TITLE
Add missing methods of SCServer.

### PR DESCRIPTION
**Pull request by DanielRose**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/SocketCluster/socketcluster-server/blob/master/scserver.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
It is so confusing seeing your username.

**Comment by DanielRose** [comment]
> 
> 
> It is so confusing seeing your username.

My best friend in grade school was B. Rosenhauer, which can be translated as Rose-hitter or Rose-beater.

**Comment by DanielRosenwasser** [comment]
> Rose-hitter or Rose-beater

Who chose *that* last name ~300-600 years ago?

**Comment by DanielRose** [comment]
> 
> 
> > Rose-hitter or Rose-beater
> 
> Who chose _that_ last name ~300-600 years ago?

Hard to tell from free sources, but it probably is an old mutation of Rosenauer; an "Au" is a meadow or floodplain. Note that the Shire is translated in German as "Auenland".

**Pull request merged**
