### PR TITLE
added fetch function in react-native

### PR DESCRIPTION
**Pull request by hktonylee**
Please fill in this template.
- [ ] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by hktonylee** [comment]
Refer to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12198

**Comment by vvakame** [comment]
*react-native/react-native.d.ts*

to author (@bgrieder). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by bgrieder** [comment]
👍

**Comment by hktonylee** [comment]
I have made another [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12408) to branch `types-2.0`. Please review ;-) Thanks.

**Comment by vvakame** [comment]
thanks!

**Pull request closed without merging**
