### PR TITLE
Add TypeScript Definitions for QZ Tray

### PR DESCRIPTION
**Pull request by tomashlavac**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by jakebailey — CHANGES_REQUESTED** [review]
This is a UMD module, you should probably restructure this to stick everything into `namespace qz` and then:

```ts
namespace qz {}
export = qz;
export as namespace qz;
```

**Comment by jakebailey** [comment]
Hm, I think this lint is wrong on our end:

```
/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/qz-tray/index.d.ts
Error:   544:1  error  Instead of `export =`-ing a namespace, use the body of the namespace as the module body  @definitelytyped/export-just-namespace
```

**Comment by jakebailey** [comment]
No, sorry, I think I'm wrong and you can actually just write `export as namespace qz` without having put everything into a namespace. Sorry for the churn.

**Comment by jakebailey** [comment]
Er, that last commit does not seem right. This package does not have a named export `qz`. I think you can just revert the last two commits and add `export as namespace qz`.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/qz-tray/qz-tray-tests.ts
1. types/qz-tray/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dc9510420ec5307b3929bd384e8db3ab87a74bf9
</p>

**Review by jakebailey — APPROVED** [review]

**Comment by tomashlavac** [comment]
Ready to merge

**Pull request merged**
