### PR TITLE
Fix remaining lint errors

### PR DESCRIPTION
**Pull request by ghost**
Mostly `prefer-const`, `dt-header`, and `space-within-parens`.

### CODE REVIEW

**Comment by dbranco** [comment]
Hello,

I have add this dependency to my development dependencies, but it seems that I am not able to import it, any help?

Kind regards.

**Comment by AlexTeixeira** [comment]
I run the tests & TSLingt again. I go not have any conflicts.

Regards.

**Comment by dbranco** [comment]
Sorry @AlexTeixeira I am kinda new into web development and TypeScript, far now I have been using the @types/xxx and it was very straight forward.

But this types seems not to be read in my Visual Studio Code, maybe I am doing something wrong:

[ts] File 'f:/meanstack_by_myself/node_modules/@types/format-unicorn/index.d.ts' is not a module.

Comparing with other types like method-override they always have the:

declare function...
declare namespace...
others has declare module...

But this index.d.ts only has interface with no declaration of any function as I was expecting.

Kind regards.

**Comment by andy-ms** [comment]
@dbranco What package are you talking about?

**Comment by dbranco** [comment]
@andy-ms   now with your comment I have realized that I am in an issue that has nothing to do with my problem but eventhough there is no issue related maybe I have to open one.

I am talking about:
           import * as formatUnicorn from "format-unicorn"

I will open an issue sorry for the inconvinient

**Comment by dbranco** [comment]
@andy-ms just in case you have any comment about this the issue is:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19241

**Pull request merged**
