### PR TITLE
chore (micro): remove redundant types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

Types shipped since 10.0.0:

https://unpkg.com/browse/micro@10.0.0/types/src/lib/

### CODE REVIEW

**Review by kaoDev — APPROVED** [review]

**Comment by 43081j** [comment]
the build will pass when i trigger a new run btw, will do once im at my laptop.

its because the dependency wasn't whitelisted for some of the older packages

**Comment by kaoDev** [comment]
thanks for clarification and also for the cleanup

**Review by kaoDev — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@43081j thanks!

**Comment by 43081j** [comment]
did the typescript bot get lost? usually it would've done its merge comment by now 👀 😂

**Comment by 43081j** [comment]
ready to merge 🏃‍♂️

**Pull request merged**
