### PR TITLE
[Ramda] Generic types for curry

### PR DESCRIPTION
**Pull request by millsp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pirix-gh/medium/blob/master/types-curry-ramda/src/index.ts
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by afharo — APPROVED** [review]

**Comment by tycho01** [comment]
This might be the most beautiful type I've seen. I'm hella proud the TS community has come this far.
I'm pretty curious what we could pull off for `pipe` / `compose`, `path`-like functions (/ `partial.lenses`?) and `map`!

**Comment by pirix-gh** [comment]
@tycho01 I'm planning to do them as well. In a near future though, because I can't stand not having types. It's on my roadmap for learning functional programming. It would be nice of you if you can provide a list of missing important types (like pipe, compose...), since you've been the one working types for Ramda.

**Comment by infctr** [comment]
@pirix-gh Great work! Been looking for this PR since that post on Medium

**Comment by googol** [comment]
This looks great! What is that medium post by the way?

**Comment by infctr** [comment]
@googol  https://medium.freecodecamp.org/typescript-curry-ramda-types-f747e99744ab a very entertaining read

**Comment by tycho01** [comment]
@pirix-gh:

> I'm planning to do them as well. In a near future though, because I can't stand not having types. It's on my roadmap for learning functional programming. It would be nice of you if you can provide a list of missing important types (like pipe, compose...), since you've been the one working types for Ramda.

From the Ramda perspective, those above seemed like the main challenges to me, which unfortunately mostly seemed blocked by language features:
- `path`-like functions: these are really just about the same general recursion as in your `curry`. Bunch of ideas at https://github.com/Microsoft/TypeScript/issues/12290, my idea at the time [here](https://github.com/tycho01/typical/blob/master/src/ramda/PathFn.ts). Use-cases extend to lenses/traversals/prisms in general. (I personally ended up liking that `partial.lenses` as it seemed a nice Ramda complement to cut down on `map` / `path` / `pipe` nesting without having to deal with HKT serialization, but at the time typing it seemed way off.) This category we can probably do reasonably well today.
- `pipe` / `compose`: same basic category/challenges as `curry` -- my idea [here](https://github.com/tycho01/typical/blob/master/src/ramda/Pipe.ts), bunch of more discussion / attempts at https://github.com/Microsoft/TypeScript/issues/5453. The remaining challenge here and for `curry` seems to be to make these sensitive to functions that have generics, as current approaches based on `ReturnType` are unable to plug in the types based on actual argument values/types. I hoped https://github.com/Microsoft/TypeScript/issues/6606 (`$Call` equivalent) would fix that, but unfortunately it was rejected.
- `map` for tuples / objects: same problem as above, given just `ReturnType` I saw no way to be able to calculate return types that iterate over input elements and for each calculate a corresponding return type. My idea on a theoretical implementation for tuple inputs [here](https://github.com/tycho01/typical/blob/master/src/ramda/MapFn.ts).

Outside of Ramda proper, [HKTs](https://github.com/Microsoft/TypeScript/issues/1213) seem a big challenge as well -- most work for those seems to have taken place at https://github.com/gcanti/fp-ts.

**Comment by infctr** [comment]
Isn't [this PR](https://github.com/Microsoft/TypeScript/pull/30215) gonna make type inferences in `pipe` / `compose` work out of the box?

**Comment by tycho01** [comment]
@infctr: thanks, you're right! in that case in that category I'm mostly worried about `curry` getting equally robust there.

**Comment by pirix-gh** [comment]
Thanks @infctr and thanks @tycho01 for this thorough summary!

Nice PR, I just tested it and it's amazing! It's not generic though. Combine these new improvements to recursive types and we'll have it, most of the work is done now it's pie. This is really cool.

**Comment by jackmellis** [comment]
Just a note based on my experience. Previously the helper types were exported i.e. `r.CurriedFunction2<A, B>` which were really useful for writing small definition types for other libraries. These are now gone, so breaking change going on here.

**Comment by pirix-gh** [comment]
@jackmellis thanks for reporting this issue. I will restore the previous aliases to fix the problem. Please change back to "@types/ramda": "^0.25.6" in the mean time as it might take some time to republish.

Thanks

**Comment by fightingcat** [comment]
@pirix-gh [Some tuple manipulation doesn't need to be recursive](https://github.com/fightingcat/Typescript4Fun/blob/4551dda886bb5c7a23aa6fd1770d7bd99dc4d11b/src/tuple.d.ts#L3), I'm not familiar with ramda, but hope this is helpful for something.

**Comment by pirix-gh** [comment]
Hi @fightingcat,

I am very impressed with your `UnionToTuple`! And yes, about the `Last`, it does not need to be recursive, you're right. I did it for the purpose of an example and completely forgot to optimise it.

In the case of Ramda, the recursion (is necessary) solves the problem of variadic types.

**Comment by pirix-gh** [comment]
@tycho01 @googol @infctr

I finally found the time to build generic types for **pipe** and **compose**. So I summed it up into a [bonus](https://github.com/pirix-gh/medium/blob/master/types-curry-ramda/src/bonus.ts) file :smile:.

**Comment by tycho01** [comment]
That's pretty awesome! I wish I knew how we could do better than `ReturnType` in a generic way, but I'm not sure I do... :neutral_face:
To type a certain curried `pipe`, could we just be like `CurryF<AwesomePipeType>`?

**Comment by pirix-gh** [comment]
Thanks @tycho01 for revealing this. I heard your request and it's been updated. :hamburger: 
Think I'm done learning TS now x)

**Comment by MehdiSaffar** [comment]
image
Is there a way to keep generics instead of turning them to any?

**Comment by pirix-gh** [comment]
It is not possible at the moment, I explained it right after this similar comment https://github.com/Microsoft/TypeScript/issues/5453#issuecomment-478301595

**Comment by pirix-gh** [comment]
@tycho01 @googol @infctr @fightingcat @MehdiSaffar 

I finally released a library for those types, I thought this was worth sharing
https://github.com/pirix-gh/ts-toolbelt

It would be cool if you guys could use it for Ramda, since this is the ramda of types.

And @tycho01 I saw that you were looking to generate clean docs for types & ts... I will properly release "eledoc" soon. This is what I am using to generate the ts-toolbelt documentation, if you want to see how it looks.

**Comment by infctr** [comment]
`ts-toolbelt` looks great, will definitely dig into it! 

Are we allowed to include third party libraries as dependencies into DefinitelyTyped typings? Not sure how's that gonna work

**Comment by pirix-gh** [comment]
I think that it is possible, but I will have to publish my types directly on DefinitelyTyped.

**Comment by denkristoffer** [comment]
I'm a TS noob who just got around to updating `@types/ramda` to include this change. My question is how I'm supposed to handle return types with this? For example:

```ts
import { curry } from 'ramda'

const getFile = curry(
  async (
    storage: Storage,
    fileName: string,
  ): Promise<File> => storage.file(fileName),
)

const file = await getFile(storage, fileName)
```

`file` will have the type `Curry.Curry<(storage: Storage, fileName: string) => Promise<File>>`, not `File`.

**Comment by pirix-gh** [comment]
Hi @denkristoffer,

No problem on my side:

```ts
import { curry } from 'ramda'

class File {}

class Storage {
   file(fileName: string): File {
      return undefined as unknown as File
   }
}

const getFile = curry(
  async (storage: Storage, fileName: string): Promise<File> => storage.file(fileName),
);

(async () => {
  const file = await getFile(new Storage(), "file") // File
})()
```

Using ramda 0.26.1 and @types/ramda 0.26.18

**Comment by denkristoffer** [comment]
Thanks @pirix-gh, I think I got it: VS Code was using its own, separate TS version (3.2.2). I forced it to use the binary from `node_modules` (3.5.3) and everything seems to work 👍

**Comment by calamao** [comment]
Thanks @pirix-gh,
I did not know where to leave this comment... It's just to say I learnt a lot with your article, based on this PR. You opened my eyes to the real power of TS.
I think your utility types (Index, Next, Prev, Tail, Head, Drop,...) should be part of the TS core (like Partial, Params, ReturnType,...).
I'm looking forward to add them to my codebase.
Amazing-beautifully-typed!
Thanks!

**Comment by pirix-gh** [comment]
Thanks @calamao! 🦑

**Pull request merged**
