### PR TITLE
Highcharts: Fixed a comma that should've been a semicolon.

### PR DESCRIPTION
**Pull request by baltie**
Fixed a small issue mentioned in a recent comment on PR #6239.

### CODE REVIEW

**Comment by baltie** [comment]
:+1: :)

**Comment by SrTobi** [comment]
indeed :+1:

**Comment by leonyu** [comment]
There are 3 other cases according to `tslint`, however, they are following closing braces `}`: 

```
highcharts.d.ts[1307, 41]: missing semicolon
highcharts.d.ts[1956, 6]: missing semicolon
highcharts.d.ts[4424, 6]: missing semicolon
highcharts.d.ts[4729, 6]: missing semicolon
```

**Comment by vvakame** [comment]
thanks mate!
@leonyu please send a pull request ;)

**Pull request merged**
