### PR TITLE
workaround TS issue: resolves to a non-module entity

### PR DESCRIPTION
**Pull request by alexeagle**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by alexeagle** [comment]
Note, this modification was made locally in the tslint project:
https://github.com/palantir/tslint/commit/249c7d97c3fd936b2c5386699acc9f760f7e6036#commitcomment-18205081
For license compliance I need to upstream it before building tslint in google-internal

**Comment by ngbrown** [comment]
@alexeagle what TS bug? do you have a reference to it?

**Comment by weswigham** [comment]
At this point in time it's no longer a bug, since it can be worked with without this "hack" (since language target is now independent of module target). IMO, @alexeagle we should patch tslint to use the other import form and revert its local changes to findup-sync, rather than update findup-sync here.

**Comment by alexeagle** [comment]
thanks @weswigham

**Pull request closed without merging**
