### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by SuperHuangXu**
open source code in 'node-cookiejar' :
```js
//returns a list of cookies
            this.getCookies = function getCookies(access_info) {
                var matches = [], cookie_name, cookie;
                for (cookie_name in cookies) {
                    cookie = this.getCookie(cookie_name, access_info);
                    if (cookie) {
                        matches.push(cookie);
                    }
                }
                matches.toString = function toString() {
                    return matches.join(":");
                };
                matches.toValueString = function toValueString() {
                    return matches.map(function (c) {
                        return c.toValueString();
                    }).join(';');
                };
                return matches;
            };
```

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by paroxp — APPROVED** [review]
Yes, you're right. I've missed that... Sorry!

Your solution does fix the issue. It's a shame we cannot attach random working tests to these - as the two lines below would have caught it up...

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cookiejar/cookiejar-tests.ts#L30-L31

Either way, good spot!
Thanks.

**Comment by DanielRosenwasser** [comment]
I can see `toValueString()`, but what's the point of the `toString()`?

**Comment by paroxp** [comment]
I'm not bond to the function myself, but I'm not sure I agree with deletion of it... Shouldn't we be aiming at the parity with upstream library?

https://github.com/bmeck/node-cookiejar/blob/master/cookiejar.js#L232-L249

./cc @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Maybe, but it seems redundant to me. If you really want, feel free to send a PR that tests the type of `toString()` like

```ts
getCookies().toString() // $ExpectType string
```

**Pull request merged**
