### PR TITLE
knex: interface Transaction extends Knex instead of QueryBuilder.

### PR DESCRIPTION
**Pull request by ignitenet-martynas**
…red knex object, with a "commit", a "rollback" and a "savepoint" function.'

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tgriesser/knex/blob/master/src/transaction.js#L163

### CODE REVIEW

**Comment by ignitenet-martynas** [comment]
With my changes interface Transaction extends Knex instead of QueryBuilder because that's what it really does (see link to Knex source code and the comment there) and in some of our code I need to be able to pass the 'transactor' object to functions that accept arguments of type Knex.

I've also made 'commit' and 'rollback' method declarations more specific and added the missing 'savepoint' method declaration.

@tkQubo @baronfel would you please review this PR?

**Comment by baronfel** [comment]
I've reviewed the knex source and agree with your changes.  Thanks for the contribution, @ignitenet-martynas!

**Comment by baronfel** [comment]
👍

**Comment by baronfel** [comment]
One thing I do worry about here though is that the contracts for commit and roll back have gotten more strict now, which may break current code. Do we need some kind of significant version bump to signal this change?

**Comment by ignitenet-martynas** [comment]
@baronfel That's an interesting question. For code to break it should be using commit and rollback in a way that is incompatible with the new contract but then it's incompatible with Knex anyway? And should not be working, at least in theory?

**Comment by ignitenet-martynas** [comment]
@baronfel I hate to bother you but this PR is "Awaiting reviewer feedback" – I personally have no issues with bumping the significant version up – will update my dependencies accordingly.

**Comment by baronfel** [comment]
I'm fine going ahead with it for the reasons you specify, namely that the previous typing was an invalid usage of the app in the first place.

**Pull request merged**
