### PR TITLE
styled-system: Fix internal reference to types

### PR DESCRIPTION
**Pull request by LavaToaster**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by zephraph** [comment]
> Looks innocuous enough to me

Famous last words 😄

**Comment by misoguy** [comment]
@alloy For some reason I can't get this fixed version.

**Comment by Lavoaster** [comment]
@misoguy The types were published an hour or so ago so this fix should be available now.

**Comment by alloy** [comment]
@zephraph I definitely remember thinking that while typing! 😝

**Pull request merged**
