### PR TITLE
slickgrid: some fixes

### PR DESCRIPTION
**Pull request by Koloto**
- Added `DataProvider.getItemMetadata` which returns new interface `RowMetadata` (https://github.com/mleibman/SlickGrid/wiki/Providing-data-to-the-grid#item-metadata)
- `GroupRowMetadata` and `TotalsRowMetadata` were deleted, new ``RowMetadata` is used instead of them
- Removed `R` type argument from `Group<T,R>` and `GroupTotals<T,R>`. First of all `R` and `T` should be swapped: `R` is a type of `value` and `T` is a type of `rows`. Also `R` is usually unknown and `any` is used. This is inconvenient. So I think removing `R` is the best way.
- All properties of `GroupingOptions` are optional.

### CODE REVIEW

**Comment by vvakame** [comment]
*slickgrid/SlickGrid.d.ts*

to author(@jbaldwin). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by jbaldwin** [comment]
Looks ok to me.

**Comment by vvakame** [comment]
@jbaldwin thanks!
@Koloto please resolve conflict

**Comment by Koloto** [comment]
@vvakame I'll resolve it a bit later, after 09/26.

**Comment by Koloto** [comment]
@vvakame The conflict is resolved, merge pls.

**Comment by Koloto** [comment]
@vvakame Is something wrong with this PR? Could you merge it?

**Comment by vvakame** [comment]
sorry for late.
thanks mate!

**Pull request merged**
