### PR TITLE
[node] Add Buffer.poolSize() and correct Buffer.byteLength()

### LINKED ISSUE #19930: @types/node    Buffer.poolSize
- [x] I tried using the `@types/node` package and had problems.

Buffer.poolSize is not defined.

### LINKED ISSUE #20399: @types/node Buffer: incorrect signature of byteLength() method
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs  @RobDesideri @tellnes @WilcoBakker @octo-sniffle @smac89  @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas @kjin

[Taken from original Node.js documentation:](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding)

**Class Method: Buffer.byteLength(string[, encoding])**

- string `<string> | <Buffer> | <TypedArray> | <DataView> | <ArrayBuffer>` A value to calculate the length of
- encoding `<string>` If string is a string, this is its encoding. Default: `'utf8'`
- Returns: `<integer>` The number of bytes contained within `string`

But Node.js types describes this method as:
```Typescript
byteLength(string: string, encoding?: string): number;
```
I am assuming `string` argument type in `byteLength()` method should be extended with other types according to Node.js documentation.

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html#buffer_class_property_buffer_poolsize
https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

fixes #20399 @vbodnia: would be nice if you can test in your environment
fixes #19930 @guftall: would be nice if you can test in your environment

### CODE REVIEW

**Comment by Flarna** [comment]
Test failure look unrelated. Besides that travis times out...
@andy-ms @RyanCavanaugh : The list of node PRs lying around with unrelated CI fails grows. Any hints how to improve this?
see #20308, #20185, #20186, #20126, #20068, ...

**Comment by andy-ms** [comment]
@Flarna The way to improve it is for a human to go and actually look at the pull requests...

**Comment by Flarna** [comment]
@andy-ms Thanks!
Maybe it's possible to improve the Bot to give people submitting a PR the possibility to to mark them as "CI fail is unrelated" and Bot puts them into the human queue.

**Comment by andy-ms** [comment]
Either a package should be merged or a human should look at it. There's no third possibility or else we end up with 200 open pull requests.

**Pull request merged**
