### PR TITLE
[react-native] Add accessibilityLabel and testID on TextProperties and ButtonProperties

### PR DESCRIPTION
**Pull request by KevinVlaanderen**
testID and accessibilityLabel are used for end-to-end tests. For Button, the testID wasn't specified in the typings. For Text, the accessibilityLabel was missing.

https://github.com/facebook/react-native/blob/master/Libraries/Components/Button.js
https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js

### CODE REVIEW

**Comment by iRoachie** [comment]
@huhuanming @alloy Is there a better way we can do this? `accessiblityLabel` is actually available on all components https://facebook.github.io/react-native/docs/accessibility.html#accessible-ios-android. Instead of adding this prop to all component typings it maybe better to make an interface and extend it

**Comment by alloy** [comment]
Should it not just go on both `ViewPropertiesIOS` and `ViewPropertiesAndroid`?

**Comment by KevinVlaanderen** [comment]
ButtonProperties and TextProperties don't extend ViewProperties, nor should they, as their implementations don't use ViewPropTypes. I feel an accessibilityInterface would be the better approach. I'll see if I can make some time for that.

**Review by iRoachie — APPROVED** [review]

**Comment by alloy** [comment]
Nice! Thanks for taking the time 👏

**Comment by timwangdev** [comment]
Thanks!

**Comment by KevinVlaanderen** [comment]
You're welcome! Thanks for the quick follow-up.

**Pull request merged**
