### PR TITLE
mui-datatables@2.12 Missing fields…

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
Changes:
- add `filterType` as column option using FilterType enum [documented in README](https://github.com/gregnb/mui-datatables)
- add missing field `columns` on `TableState` (I'm using that to detect which sorting was enabled instead of parsing announceText which seemed to me like a hack)
- added `"none"` as a possible value of `sortDirection`. Warning: I don't believe this should be a valid value as `undefined` is possible as well, but I was receiving `none` so wanted to account that. Is that a bug that should be fixed?

CC @gabrielliwerant @MasterKale could you review it? It might be also good to pack definitions along mui-datatables to keep it up to date.

Checks:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Check If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gregnb/mui-datatables (README)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (it updates the given version)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by favna — CHANGES_REQUESTED** [review]
When adding TODO's it would be preferred if you also actually add them.

**Comment by Favna** [comment]
> It might be also good to pack definitions along mui-datatables to keep it up to date.

That's a good option. At the time I initiated typings for this package they were only a gist and DefinitetlyTyped is the fastest way to get typings for a library when unsure if the author of the library will merge them in and update the package accordingly, ergo I published them here.

Regardless, if @gregnb's is open to include the typings directly in the library and also maintain them then by all means he can do so by taking this file as base and when he adds them they can be removed from DefinitetlyTyped. Maintain is the important part here - making releases of the library without also updating the typings accordingly is extremely bad practice and ill advised with typings inside the library. However, as library author you have no commitment to keep typings in DefinitetlyTyped up-to-date.

**Comment by KrzysztofMadejski** [comment]
I haven't added all TODOs as I was not sure if I'm not exposing internals too much.

**Comment by Favna** [comment]
> I haven't added all TODOs as I was not sure if I'm not exposing internals too much.

As long as the value is exported (included in `export` or `module.export`) then it can be in the type declarations. If they are not then they should not be. I'd have to dig into the code myself to give a better answer right now.

**Comment by KrzysztofMadejski** [comment]
Sure, I won't have time for a while to fix it, so please close it for now.
Thanks for the review everyone

wt., 29 paź 2019, 17:09 użytkownik TypeScript Bot <notifications@github.com>
napisał:

**Pull request closed without merging**
