### PR TITLE
Update bytebuffer.d.ts

### PR DESCRIPTION
**Pull request by pocesar**
help the editors know better about conditionals and type unions

### CODE REVIEW

**Comment by cappellin** [comment]
The version bytebuffer.d.ts was originally created for browser. In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7109 we suggest to create bytebuffer-node.d.ts for the NodeJS version.

**Comment by pocesar** [comment]
yeah, that would be needed. the current typings doesn't work properly on node. if the class declaration would be split in 2 interfaces, maybe? 

as a side note, vscode has a silly way to include all .d.ts for lookup, having the same class name and module gives a duplicate error in editor, but works when compiling.

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by cappellin** [comment]
I think the PR can be merged only if a new file named bytebuffer-node.d.ts is created. Type Buffer as long as I know is available only with NodeJS.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
