### PR TITLE
inquirer - added prompt override returning Promise

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
case 2. Improvement to existing type definition.
- according to [docs](https://www.npmjs.com/package/inquirer#inquirerpromptquestions---promise)
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tkqubo** [comment]
:+1:

**Comment by vvakame** [comment]
@zhengbli What's mean `Revision needed` in this case?

**Comment by zhengbli** [comment]
I didn't realize the new "code review" feature of github needs an extra "submit" steps. This needs to be fixed.

**Comment by DmitryEfimenko** [comment]
created a new [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12247) with the proper fix

**Pull request merged**
