### PR TITLE
Add myself to react-relay contributor list to help maintain type definitions

### PR DESCRIPTION
**Pull request by levibuzolic**
Going to help out with the Relay types.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] ~Test the change in your own code. (Compile and run.)~
- [ ] ~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] ~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-relay ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-relay@latest/))
was missing the following properties:
1. MutationTypes
1. RangeOperations
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 14 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getPendingOperationsForFragment</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 796bbbfe45b40177ac0d6255eac8a661c5c1213c
</p>

**Review by maraisr — APPROVED** [review]
welcome to have you 💌

**Review by maraisr — APPROVED** [review]

**Comment by levibuzolic** [comment]
Ready to merge

**Review by jakebailey — APPROVED** [review]

**Comment by maraisr** [comment]
ready to merge

**Pull request merged**
