### PR TITLE
Added documentation to browser-sync.d.ts

### PR DESCRIPTION
**Pull request by joeskeen**
See http://www.browsersync.io/docs/options/ and http://www.browsersync.io/docs/api/ for reference

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3 could you review this PR?

**Comment by joeskeen** [comment]
Hey @pspeter3, would you mind taking a look at this?

**Comment by pspeter3** [comment]
Yeah, these are great!

**Comment by joeskeen** [comment]
@vvakame looks like we're ready to merge this one!

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
