### PR TITLE
Ember: make `get` unwrap module computed properties.

### PR DESCRIPTION
**Pull request by chriskrycho**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/ember-cli/ember-rfc176-data/> (see the entry for `Ember.ComputedProperty` near the top of the table).
- ~Increase the version number in the header if appropriate.~
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by chriskrycho** [comment]
Is there a new lint setting we need to disable?

**Comment by dwickern** [comment]
```
no-import-default-of-export-equals  The module "rsvp" uses `export = `. Import with `import RSVP = require("rsvp")`. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-import-default-of-export-equals.md
no-import-default-of-export-equals  The module 'ember' uses `export = `. Import with `import Ember = require('ember')`. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-import-default-of-export-equals.md
```
Looks like another broken rule since we don't use `export =` anywhere afaik

**Comment by chriskrycho** [comment]
@DanielRosenwasser this is the same as the issue under #23693.

**Comment by DanielRosenwasser** [comment]
Hooray the build was restarted!

**Comment by chriskrycho** [comment]
🎉 🤞

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
