### PR TITLE
Improvements for of email-templates

### PR DESCRIPTION
**Pull request by janwo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/crocodilejs/node-email-templates/blob/master/examples/handlebars_i18n/index.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by cyrilschumacher — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
@janwo can you try pushing an empty commit to see if that makes Travis run? I don't want to merge a possibly-failing commit

**Comment by janwo** [comment]
@RyanCavanaugh Seems like it did not work.

**Comment by RyanCavanaugh** [comment]
@janwo sorry - can you try opening a new PR instead? Not sure how to diagnose what's wrong with Travis

**Comment by RyanCavanaugh** [comment]
@janwo - It appears Travis did not correctly run on this PR! /cc @RyanCavanaugh to investigate and advise.

**Comment by RyanCavanaugh** [comment]
I've emailed Travis support linking this and the other non-CIing PR

**Comment by RyanCavanaugh** [comment]
@janwo Travis incorrectly flagged your account as abusive (it's a heuristic so who knows what triggered this, nothing personal). Can you follow these steps (courtesy the Travis support team) and see if that fixes it? Thanks!

> This is an unfortunate side effect of our abuse detection which sometimes produces false positives. In this case, the users who opened those pull requests don’t have accounts on Travis CI and this situation has led to abuse before (mostly through automated accounts). Could you ask the people who opened those PRs to visit travis-ci.org, click “Sign up”, and consent to connecting their GitHub accounts to Travis CI?

**Comment by janwo** [comment]
@RyanCavanaugh I signed up just now.

**Comment by RyanCavanaugh** [comment]
@janwo I suspect you'll have to push a new commit or possibly start a new PR

**Pull request closed without merging**
