### PR TITLE
Fix the signature of setDefaultEdgeLabel

### PR DESCRIPTION
**Pull request by Atry**
According to https://github.com/dagrejs/graphlib/blob/f65cf4301dbad3c53f883541f8484ec4b08e6882/lib/graph.js#L412

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/dagrejs/graphlib/blob/f65cf4301dbad3c53f883541f8484ec4b08e6882/lib/graph.js#L412
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by burtek** [comment]
> @Atry The Travis CI build failed! Please [review the logs for more information](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/524341729?utm_source=github_status&utm_medium=notification).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34973#issuecomment-486511704

**Comment by rustedgrail** [comment]
The function you linked is a locally defined function _defaultEdgeLabelFn, not the Graph.setDefaultEdgeLabel.

https://github.com/dagrejs/graphlib/blob/f65cf4301dbad3c53f883541f8484ec4b08e6882/lib/graph.js#L332

**Comment by Atry** [comment]
`_defaultEdgeLabelFn` is set in `setDefaultEdgeLabel`: https://github.com/dagrejs/graphlib/blob/f65cf4301dbad3c53f883541f8484ec4b08e6882/lib/graph.js#L334

**Comment by rustedgrail** [comment]
Sorry, this change is to the input to the newDefault (and _defaultEdgeLabelFn), not a change to the inputs of setDefaultEdgeLabel. Where do I explicitly select approve in the GitHub UI?

**Pull request merged**
