### PR TITLE
fix: Blob.stream return type which is incorrect and conflicts with lib.dom.d.ts

### PR DESCRIPTION
**Pull request by Gozala**
I frequently run into following issue 

image

Caused by incorrect type annotation of Blob

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2280eb45b474bf8e92ff34b1d2775afc03cffc6f/types/node/stream/consumers.d.ts#L11

Proposed changes replace that annotation with a more accurate one so that it:

1. Does not conflict with `lib.dom.d.ts`
2. Reflects actual state of things in node & specifically the fact that `Blob.prototype.stream` returns web stream and not a node one. See https://nodejs.org/api/buffer.html#blobstream

I do not know how current typedef ended this way. I think comment attempt to elaborate reason for this `Blob` interface definition, yet it does not explain why `stream()` method is typed incorrectly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Gozala** [comment]
Does what https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59057#issuecomment-1056815186 suggested

**Comment by Borewit** [comment]
Why did you revert f4c3955fe966c65fe528c1963e0fa217034c6ca5 @Gozala ? 

@favna can you clarify [duplicating the Blob interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream/consumers.d.ts#L1-L3) to ensure some unit tests are failing? 

[Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and [Readable streams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) are not introduced by Node.js, so it would make sense the types are neither re-introduced. The whole point of having them in Node.js is compatibility.

**Comment by favna** [comment]
> Why did you revert f4c3955fe966c65fe528c1963e0fa217034c6ca5 @Gozala ? 
> 
> 
> 
> @favna can you clarify [duplicating the Blob interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/b0d68aa0924582b6eaf294856dd847203f6a61fd/types/node/stream/consumers.d.ts#L1-L13)
> 
> 
> 
> > causes tests to pass that shouldn't pass
> 
> 
> 
> sounds like a dirty fix just to satisfy unit tests to me.
> 
> 
> 
> [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and [Readable streams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) are not introduced by Node.js, so it would make sense the types are neither re-introduced. The whole point of having them in Node.js is compatibility.

I have already stated in the initial PR's post merge comments that I do not want to be involved in this discussion. I have enough on my plate already and maintaining @types/node does not fit at all. Please do not bother me about this issue. Thank you kindly.

**Comment by Borewit** [comment]
There a bit of [history](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55311/files#diff-ea59275982a7902280ca02e8c4c15f49cc7ab5ba96d8eb2915ed259407565d95) to this  and related PR: #59905 which removes the Blob interface. Yet the Node interface lacks compatibility, amazing stuff.

**Comment by Gozala** [comment]
> Why did you revert [f4c3955](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f4c3955fe966c65fe528c1963e0fa217034c6ca5) @Gozala ?

The tests were failing otherwise, I can not explain why as per original PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59057 (which was rejected and closed), I do not understand how things are wired together nor I could find anyone with necessary expertise to provide some guidance. 

If it was up to me as per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59057#issuecomment-1128223689 I would much rather landed original PR that simply removes conflicting `stream()` method and let someone more qualified figure out how to get proper `stream()` such that it does not just override global `Blob`'s `stream()` method defined in `lib.dom.d.ts`.

**Pull request closed without merging**
