### PR TITLE
Added 'menubar' package

### PR DESCRIPTION
**Pull request by rhysd**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by rhysd** [comment]
Is `tsc` old on Travis CI? Typing such as `number | null` seems to cause an compilation error. Anyway, I'll fix it.

**Comment by vvakame** [comment]
@rhysd master branch is 1.8.10 still. please send to types-2.0 branch.

**Comment by rhysd** [comment]
this file has a little difference between 1.8 and 2.0.  So I modified it for 1.8.  Now available for 1.8.  When 2.0 is available, I'll upgrade this for 2.0.

**Comment by vvakame** [comment]
okey!

**Comment by Twister915** [comment]
@rhysd  Broken using recent electron typings

```node_modules/@types/menubar/menubar.d.ts(6,1): error TS2688: Cannot find type definition file for 'github-electron'.```

fixed manually by changing line 6 from
```/// <reference types="github-electron" />```

to

```/// <reference types="electron" />```

**Comment by rhysd** [comment]
@Twister915 I created a PR #12397

**Pull request merged**
