### PR TITLE
[types/recharts]Add index definitation in PieProps

### PR DESCRIPTION
**Pull request by kousaku-maron**
I can not see the "index" parameter in the document, but it actually exists and I added it for frequent use when creating custom labels.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://recharts.org/en-US/api/Pie>> <<https://jsfiddle.net/alidingling/c9pL8k61/>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by pkeuter — COMMENTED** [review]
I don't see index as a prop in your example url's as well as in the components propTypes. Could you explain why this prop is necessary?

**Comment by kousaku-maron** [comment]
if you wanna add custom label( from data) to "PieChart", you need to pick up data's "index" from PieProp.

I wrote an example below. 

and example url is here(https://jsfiddle.net/alidingling/c9pL8k61/)

```
import * as React from 'react'
import { PieChart, Pie, Cell, Tooltip, PieProps } from 'recharts'

const COLORS: string[] = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042']

interface OwnProps {
  data: Array<{name: string, amount: number}>
}

type Props = OwnProps

interface State {}

class ChartComponent extends React.Component<Props, State> {
  public renderCustomizedLabel: React.SFC<OwnProps & PieProps> = ({ cx, cy, midAngle, innerRadius, outerRadius, index }) => {
    const { data } = this.props
    
    const RADIAN = Math.PI / 180 
    const _ir: number = Number(innerRadius)
    const _or: number = Number(outerRadius)
    const _mi: number = Number(midAngle)
    const _cx: number = Number(cx)
    const _cy: number = Number(cy)

    const _index: number = Number(index)
  
    const radius: number = _ir + (_or - _ir) * 0.5
    const x: number = _cx + radius * Math.cos(-_mi * RADIAN)
    const y: number = _cy + radius * Math.sin(-_mi * RADIAN)
  
    return (
      <text x={x} y={y} fill='white' textAnchor={x > _cx ? 'start' : 'end'}>
        {data[_index].name}
      </text>
    )
  }

  public render () {
    const { data } = this.props
    
    return (
      <PieChart width={250} height={250}>
        <Pie
          nameKey='name'
          dataKey='amount'
          data={data}
          cx={125}
          cy={125}
          // innerRadius='40%'
          outerRadius='80%'
          fill='#8884d8'
          label={this.renderCustomizedLabel}
          labelLine={false}
        >
          {
            data.map((entry, index) => <Cell key={index} fill={COLORS[index % COLORS.length]}/>)
          }
        </Pie>
        <Tooltip />
      </PieChart>
    )
  }
}

export default ChartComponent
```

**Review by pkeuter — CHANGES_REQUESTED** [review]
Thanks @kousaku-maron, for the clarification! Adding the index property on PieProps makes it available when declaring `<Pie index={} />`. This is already happening in several other places in the code. But could you look into making a `PieLabelRenderProps extends PieProps` which adds the index property so it will only be available when rendering the template?

**Comment by kousaku-maron** [comment]
I create PieLabelRenderProps extends PieProps.
And "percent" parameter is often used, so I added it.

I appreciate your swift reply.

**Comment by pkeuter** [comment]
Have you tested the change? Because you only created it, and do not use it yet.

Please test it, but for what I can see you should change:
```
label?: {
        offsetRadius: number;
    } | React.ReactElement<any> | ContentRenderer<any> | boolean;```
```
to:
```
label?: {
        offsetRadius: number;
    } | React.ReactElement<any> | ContentRenderer<PieLabelRenderProps> | boolean;
```

**Comment by kousaku-maron** [comment]
sorry, I use it.
I wrote an example using "index" and "percent" below.

```
import * as React from 'react'
import { PieChart, Pie, Cell, Tooltip, PieProps } from 'recharts'

const COLORS: string[] = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042']

interface OwnProps {
  data: Array<{name: string, amount: number}>
}

type Props = OwnProps

interface State {}

class ChartComponent extends React.Component<Props, State> {
  public renderCustomizedLabel: React.SFC<OwnProps & PieProps> = ({ cx, cy, midAngle, innerRadius, outerRadius, index, percent }) => {
    const { data } = this.props
    
    const RADIAN = Math.PI / 180 
    const _ir: number = Number(innerRadius)
    const _or: number = Number(outerRadius)
    const _mi: number = Number(midAngle)
    const _cx: number = Number(cx)
    const _cy: number = Number(cy)

    const _index: number = Number(index)
    const _percent: number = Number(percent)
  
    const radius: number = _ir + (_or - _ir) * 0.5
    const x: number = _cx + radius * Math.cos(-_mi * RADIAN)
    const y: number = _cy + radius * Math.sin(-_mi * RADIAN)
  
    return (
      <text x={x} y={y} fill='white' textAnchor={x > _cx ? 'start' : 'end'}>
        {data[_index].name} {_percent * 100}%
      </text>
    )
  }

  public render () {
    const { data } = this.props
    
    return (
      <PieChart width={250} height={250}>
        <Pie
          nameKey='name'
          dataKey='amount'
          data={data}
          cx={125}
          cy={125}
          // innerRadius='40%'
          outerRadius='80%'
          fill='#8884d8'
          label={this.renderCustomizedLabel}
          labelLine={false}
        >
          {
            data.map((entry, index) => <Cell key={index} fill={COLORS[index % COLORS.length]}/>)
          }
        </Pie>
        <Tooltip />
      </PieChart>
    )
  }
}

export default ChartComponent
```

**Comment by kousaku-maron** [comment]
Sorry, I missed a "name" property.

```
export interface PieLabelRenderProps extends PieProps {
    name: string;
    index?: number;
    percent?: number;
}
```

**Comment by kousaku-maron** [comment]
If there is no problem, please merge.

**Review by pkeuter — CHANGES_REQUESTED** [review]
Hi, please have a look here:

https://github.com/recharts/recharts/blob/master/src/polar/Pie.js#L342 and add the missing fields like `textAnchor` and stroke. If you're not sure about all the fields, you can also add a `[key: string]: any` type hint prop to make sure things don't break for other users.

**Review by pkeuter — APPROVED** [review]
Thanks!

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
