### PR TITLE
Parameter formid is NOT required (xrm-7.1.d.ts)

### PR DESCRIPTION
**Pull request by wauters**
…request

formid is an optional parameter.
See: https://msdn.microsoft.com/en-US/library/jj602956.aspx#BKMK_OpenEntityForm

Please fill in this template.

- [ x] Make your PR against the `master` branch.
- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by daryllabar** [comment]
Looks like this got fixed in newer versions of the definitions, but not the 7.1.  Good catch.

**Comment by wauters** [comment]
Hi Daryl

You made me curious, does there exist a newer version than the 7.1?

Regards
Wauters

**Comment by daryllabar** [comment]
Yes @wauters.  The Xrm.d.ts is the 8.0 version essentially.  It says in the comments.

**Comment by wauters** [comment]
Daryl

Sorry to bother u again. Do you mean “index.d.ts”? As I cannot find the file xrm.d.ts in your repository.

When looking at index.d.ts, the two bugs I mentioned are still there:

- formid should be optional (FormOpenParameters)
- Xrm.ui.process should point to Page.ui.ProcessManager (and not Page.data.ProcessManager)

Regards
Wauters

**Comment by daryllabar** [comment]
Brilliant question: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/daf9bd392f4c8469ddc8849ee198bbdd1e57c7f4#commitcomment-20308919


Looks like some github magic has happend that I don't know about...


________________________________

**Comment by andy-ms** [comment]
The TypeScript compiler uses `index.d.ts` as the entry point for a package, so that is what we use on DefinitelyTyped. We don't publish older versions to `@types/xrm`, just `index.d.ts`, so new fixes should generally go there.

**Comment by andy-ms** [comment]
Sounds good. See also Microsoft/types-publisher#3.

**Comment by daryllabar** [comment]
Ah... Will have to update it to those guidelines.  Thanks!

**Comment by mhegazy** [comment]
merging this for now. please file a separate PR for reorganizing the package.

**Comment by daryllabar** [comment]
Submitted @mhegazy  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13634

**Pull request merged**
