### PR TITLE
Update bootstrap-datepicker index.d.ts

### PR DESCRIPTION
**Pull request by sousarka**
Please fill in this template.
- [ x] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

add following options to the bootstrap-datepicker/DatepickerOptions. Also update the options url to point to the correct URL.
templates?: any;
zIndexOffset?: number;
showOnFocus?: boolean;
immediateUpdates?: boolean;
 title?: string;

### CODE REVIEW

**Comment by sousarka** [comment]
@borisyankov  can you please review this?

**Comment by vvakame** [comment]
*bootstrap-datepicker/index.d.ts*

to author (@borisyankov). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by sousarka** [comment]
@vvakame ping!

**Comment by sousarka** [comment]
@vvakame @andy-ms can you please merge this?

**Pull request merged**
