### PR TITLE
Revert "fix: `lodash.groupBy` result never contains empty arrays"

### PR DESCRIPTION
**Pull request by jsalvata**
Reverting https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55914 as [requested by @aj-r](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55914#issuecomment-1012595869).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## select2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/select2@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'select2'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 517c11249623a6c97fdf8e2daa4d72bf081514aa
</p>

**Comment by jsalvata** [comment]
Oops. Looks like it was already reverted?

**Comment by parasol-me** [comment]
This is not reverted in the latest release and its causing problems for me.
Cant reassign key in group by result because of it being wrapped in [] and type not match.
Can we please revert this or if its already reverted, can that be released?

**Comment by jsalvata** [comment]
You're right, @parasol-me. Not sure what happened. I'll try to get it through.

**Comment by jakebailey** [comment]
I think there's an error in the PR; based on #55914, it seems like the intent was that this PR does a revert of the commit, but instead commits the change again and then reverts that change (leading to no changes).

**Comment by jsalvata** [comment]
@jakebailey 

> I think there's an error in the PR; based on #55914, it seems like the intent was that this PR does a revert of the commit, but instead commits the change again and then reverts that change (leading to no changes).

Oh, that's probably why I thought the change was already reverted.

Fixed. Can you review again, please?

**Comment by jakebailey** [comment]
Hm, seems to be failing because of https://github.com/microsoft/TypeScript/issues/47940.

**Review by aj-r — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
Approving/merging despite the CI failure; this is a plain revert of a previous change and passes on everything except 4.7 nightly (for the reason noted above).

**Pull request merged**
