### PR TITLE
Add `cleanReferencesAfterRun` to 'mocha'

### PR DESCRIPTION
**Pull request by nicojs**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mochajs.org/api/mocha#cleanReferencesAfterRun
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mocha ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mocha@latest/))
was missing the following properties:
1. unloadFile
1. xdescribe
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 979f000bf5492af3a1d956d364b11538d9110bee
</p>

**Comment by strangedev** [comment]
Hey @nicojs 👋 
Thanks for the PR! It looks good to me, but I'll have to double check later since I'm on mobile at the moment.

**Comment by nicojs** [comment]
Sure. I'm a mocha maintainer, so maybe that helps as well 😘

**Review by strangedev — APPROVED** [review]
:shipit:

**Comment by strangedev** [comment]
Hey @nicojs 👋 Thank you again for the PR, awesome to have an owner for the types who is also a contributor to mocha 😄

**Pull request merged**
