### PR TITLE
Correct GM_config type licensing to avert a DMCA inclusion

### PR DESCRIPTION
**Pull request by Martii**
* While we, the Copyright holders, can see the value of this project it was inadvertently merged by your maintainers without confirmation or knowledge of the actual "Code owners". The project and any derivatives are not owned by Microsoft as mentioned at https://www.npmjs.com/package/@types/gm_config
* Licensing of any derivative is dictated solely by the terms of LGPL 3 or later which was omitted by the third party in #57016 . GNU requires, at least, this header block to be added. A "publicação" is still a "publication" in a different language including, but not limited to, subsets of JavaScript or definitions of alternate scripting languages.
* This PR is submitted in hopes that this project will abide by the terms of licensing in a good faith effort to reconcile the Copyright violation.
* This is by no means an official verified TypeScript of the GM_config project but may be at a later date providing the licensing is corrected.

Thank you for your cooperation.

Signed-off-by: Martii <martii@users.noreply.github.com>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Martii** [comment]
@MysteryBlokHed *(since your bot specifically mentioned you)* and/or any other maintainer.

Re:

``` console
Error in gm_config
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/gm_config/index.d.ts:8:1
ERROR: 8:1   jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 8:1   jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 9:1   jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 9:1   jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 10:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 10:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 11:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 11:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 12:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 12:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 13:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 13:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 14:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 14:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 15:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 15:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 16:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 16:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 17:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 17:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 18:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 18:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 19:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 19:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 20:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 20:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 21:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 21:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 22:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 22:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 23:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 23:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 24:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 24:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 25:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 25:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 26:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 26:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 27:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 27:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 28:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 28:1  jsdoc-format  asterisks in jsdoc must be aligned
ERROR: 29:1  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 29:1  jsdoc-format  asterisks in jsdoc must be aligned
```

They are aligned and the LGPL  header notice text must be formatted as such. If you have any suggestions on how to work around your configuration please feel free with this in mind.

I took the liberty of making the comment block match TypeScript with the beginning `/**` instead of the normalized `/*` in anticipation that your CI is incorrect. As well as presumed that the beginning existing comments were needed in their current locations for automation.

As this is a comment only there should and won't be any additional ticks added to the checklist. Please review and merge this in a timely manner.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Marking this as not mergeable. I will have more information after following up with our lawyers.

**Comment by RyanCavanaugh** [comment]
Still waiting for our legal folks to chime in. @MysteryBlokHed if you want to delete this definition here given the events so far, please ping me and I will prioritize that.

**Comment by Martii** [comment]
> Still waiting for our legal folks to chime in

Appreciate the update.

> if you want to delete this definition here given the events so far, please ping me and I will prioritize that.

I'm not sure such a drastic response would be merited however that would alleviate the issue with an indirect acknowledgement that a Microsoft managed project won't follow licensing. 

I think a better suggestion would be to read, and understand, the LGPL terms and properly correct the code derivative for combined works by adding the comment. 

We licensed it to be used in combined works however attribution of same licensing and Copyright is always required. It is a simple addition to keep everyone reconciled and why I'm currently the representative here. 

Please note @MysteryBlokHed would be responsible for maintaining it for the rest of his life *(according to your CI system and how it works)*, if he chooses not to correct his issue on our end with circumvention of the contributor status, including any changes that come down the line in GM_config. We could have easily caught this snafu had he started on our project as an issue with PRs and then possibly sponsored him cross-stream.

**Comment by MysteryBlokHed** [comment]
The main reasons I decided to add the types to DefinitelyTyped as opposed to the GM_config repo was that DefinitelyTyped has good infrastructure for testing types and making changes. The repository is well-known for most TypeScript developers.

What I didn't know (and am still not sure about, I'll wait for the lawyers' response to be sure) was that the types counted as a derivative work. I'd be willing to change the license to LGPL no matter the lawyers' responses if possible with DefinitelyTyped just to resolve this conflict.

> Please note @MysteryBlokHed would be responsible for maintaining it for the rest of his life _(according to your CI system and how it works)_

On this note: I could add @Martii as an additional owner in the header of the `index.d.ts` file, here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/063a2fbd1613833521917475740f4dfa325054e0/types/gm_config/index.d.ts#L3

That would allow you to make changes and approve other people's PR's the same way I currently can. It would probably be a good idea to have a maintainer of the original project as an owner of the types any way.

**Comment by RyanCavanaugh** [comment]
We cannot accept other licenses in this repo.

**Comment by Martii** [comment]
@RyanCavanaugh 

> We cannot accept other licenses in this repo.

That is too bad. Noted to our legal counsel and may be forwarded to the FSF upon action taken.

So either @MysteryBlokHed needs to remove the type definitions in this repo or inclusion of this repo will face a DMCA.

@MysteryBlokHed 

See this is why its best to start at source instead of a foreign project. While they may have developed some tools specific to your use case it's always best to work as a team and have support. You are still welcome to open a new issue on GM_config for further discussion. TypeScripts aren't bound to this repos project and if it ever was it would not be a good thing for OSS/FOSS.

**Comment by Martii** [comment]
Closing as per #57261 status merged.

Please do not forget to update npmjs.com as well.

**Comment by MysteryBlokHed** [comment]
Package should be auto-removed by the bot.
sizzlemctwizzle/GM_config#101 can probably be closed too.

**Pull request closed without merging**
