### PR TITLE
Make SyntheticEvent.target generic, not SyntheticEvent.currentTarget.

### PR DESCRIPTION
**Pull request by Emm**
See #11508 for further discussion.

### CODE REVIEW

**Review by bogusfocused — APPROVED** [review]
This corrects the merge error.

**Comment by s-panferov** [comment]
What prevents this to be merged?

**Comment by nantaphop** [comment]
Merge please...

**Comment by vvakame** [comment]
sorry for late!

**Comment by bbenezech** [comment]
@vvakame see my comment here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11508#issuecomment-256045682

We need to revert this commit **as soon as possible** (before everyone wrongfully adapt their codebase and send their users to bugland)

**Comment by bbenezech** [comment]
Also (same opinion as mine, came earlier in the git-storm) https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10811#issue-173007384

For everyone: use event.currentTarget over event.target when you don't care/know the difference.

**Comment by bbenezech** [comment]
@vvakame PR created.

**Pull request merged**
