### PR TITLE
[density-clustering] Add missing distance function param to `OPTICS.run`

### PR DESCRIPTION
**Pull request by lggruspe**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/uhho/density-clustering/blob/6fd080356cb05ae6a9bc980ec49b4731d08cfb5d/lib/OPTICS.js#L59C1-L59C78>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## density-clustering ([<kbd>unpkg</kbd>](https://unpkg.com/browse/density-clustering@latest/))
was missing the following properties:
1. PriorityQueue
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a081d7e0122d373e49eacdcac379b7f24792ad73
</p>

**Comment by lggruspe** [comment]
PriorityQueue isn't documented and it doesn't have usage examples in the readme, so maybe it's okay to leave it out?

**Review by mfedderly — APPROVED** [review]

**Comment by mfedderly** [comment]
Agree on leaving PriorityQueue out

**Comment by lggruspe** [comment]
Ready to merge

**Pull request merged**
