### PR TITLE
update(toastify-js): UMD support, missing options

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit:
- adds support for UMD usage (module or global script)
- rename 'args' to 'options' - as per original package usage and
  documentation
- 'avatar' option
- 'reposition' static-like method support
- tests amended
- mantainer added

https://github.com/apvarun/toastify-js/blob/master/src/toastify.js

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## toastify-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/toastify-js@latest/))
was missing the following properties:
1. lib
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d9d4d15becda604cb0b7f8cd4550d543bc46afd2
</p>

**Review by adblanc — APPROVED** [review]
Thanks for contributing 👍

**Comment by adblanc** [comment]
Read to merge

**Comment by adblanc** [comment]
Ready to merge

**Pull request merged**
