### PR TITLE
[React-leaflet] Update Index.d.ts to fix error in using 2.3

### PR DESCRIPTION
**Pull request by yuit**
Remove type parameter for React Component class 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by davschne** [comment]
Hi, @yuit. I'm curious why you removed the type parameters. I added them to make it possible to extend any `react-leaflet` class with custom React props and a custom Leaflet Element. This was helpful for me in getting good type checking on my extending components. Did you find that the type parameters created problems in your code, or do you think there's an easier alternative to allow this extensibility?

**Comment by yuit** [comment]
@davschne Thanks to take a look at this! I am not familiar with the library and would love some advises from you. The reason I remove type parameters is that in 2.3 compiler, we change how we check JSXAttributes (more specifically we use CheckTypeRelatedTo to do the checking now instead of just loop through each property separately) So in this case if Map is generic
``` ts
export class Map<P extends MapProps, E extends Leaflet.Map> extends MapComponent<P, E> {... }
let m = <Map bounds={this.state.bounds} /> 
// "props" of Map will have be uninstatiate and maintain its generic mapped Type so it is false when do type comparison
```
That is why I remove the type parameter as we can't infer type parameter and there is no way for users to specify type argument at the moment. And there is no way out of this error
Could you help me understand about the extensibility usage here?

**Comment by davschne** [comment]
@yuit Ah, very interesting. I wondered how the compiler was able to figure out the correct type parameters for a React component, since it does seem possible (currently) to specify them in JSX. I noticed that in TypeScript 2.3, there's now a possibility of default type parameters. Would that work here?
```typescript
export class Map<P = MapProps, E = Leaflet.Map> extends MapComponent<P, E> { ... }
```

**Comment by yuit** [comment]
@davschne so when you extend from React.Component without using type parameter, you will supply concrete type for `props` as type argument for React.Component. For example [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16112/files#diff-f0801d9ba4c54233a155e62f1f05d665R244)  So `props` is now instantiate.  The reason pre-2.3 this work is because how we type-check attributes.

This  is interesting about using default type parameter. At the moment, with current 2.3 it doesn't work. But I think this is a bug. I am going to take a look at this

**Comment by yuit** [comment]
I am fixing this using default Type parameter instead

**Pull request closed without merging**
