### PR TITLE
feat(d3-fetch):  update to minor version 1.1

### LINKED ISSUE #24516: Property 'xml' does not exist on type 'typeof "node_modules/@types/d3/index"
- [x] I tried using the `@types/d3` package and had problems.
- [x] I tried using the 2.6.2 version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @andy-ms 
  - Authors: @tomwanzek 

According this issue https://github.com/d3/d3-fetch/issues/14 the following methods were added to d3-fetch 1.1.0: 
- d3.html
- d3.svg
- d3.xml

Is there any chance that `@types/d3` will support these methods?
Thank you!

### PR DESCRIPTION
**Pull request by tomwanzek**
* Update d3-fetch to minor version 1.1.
* Add `html(...)`
* Add `svg(...)`
* Add `xml(...)`

Closes #24516

@Ledragon 
cc @deniska-info

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-fetch/releases/tag/v1.1.0>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by Ledragon — APPROVED** [review]

**Comment by denisname** [comment]
@tomwanzek, you wrote `hmtl` instead of `html`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8a857d6473829df15ae8d695dbac310e824479df/types/d3-fetch/index.d.ts#L157

**Comment by paulvanbrenk** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24701

**Comment by Ledragon** [comment]
Good catch @denisname , thanks @paulvanbrenk for the fix!

**Comment by tomwanzek** [comment]
I thought, I was on the right path with HMTL (Hypered Media Troll Language), is that not a thing? Good catch, if not.

**Pull request merged**
