### PR TITLE
[three] r168

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/three-types/three-ts-types/issues/1147
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Comment by rnantes** [comment]
@Methuselah96 There is an error in this PR causing this when I try to build:

```[
ERROR] TS2304: Cannot find name 'XRWebGLDepthInformation'. [plugin angular-compiler]
    node_modules/@types/three/src/renderers/webxr/WebXRDepthSensing.d.ts:15:45:
    15 │ ...enderer, depthData: XRWebGLDepthInformation, renderState: XRRen...
```

currently in file [node_modules/@types/three/src/renderers/webxr/WebXRDepthSensing.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/src/renderers/webxr/WebXRDepthSensing.d.ts#L15) it is : 

`init(renderer: WebGLRenderer, depthData: XRWebGLDepthInformation, renderState: XRRenderState): void;`

XRWebGLDepthInformation cannot be found. I believe instead it should be

`init(renderer: WebGLRenderer, depthData: WebXRDepthSensing, renderState: XRRenderState): void;`

**Comment by Methuselah96** [comment]
My guess is that you have an out-of-date version of `@types/webxr`. The `XRWebGLDepthInformation` type was introduced in `@types/webxr@0.5.17`, so make sure you're using that version or newer.

**Comment by rnantes** [comment]
@Methuselah96 even when I deleted the package-lock.json file in my project and do a npm install it keeps resolving `@types/webxr@0.5.5` instead of `@types/webxr@0.5.17` or higher.

Should it not be specified here instead of "*": https://github.com/DefinitelyTyped/DefinitelyTyped/blob/be1197086ded3cdb634cb6e106d4352bd0e430e5/types/three/package.json#L22-L29


package-lock after delete an npm install:
```json
  "node_modules/@types/three": {
      "version": "0.168.0",
      "resolved": "https://registry.npmjs.org/@types/three/-/three-0.168.0.tgz",
      "integrity": "sha512-qAGLGzbaYgkkonOBfwOr+TZpOskPfFjrDAj801WQSVkUz0/D9zwir4vhruJ/CC/GteywzR9pqeVVfs5th/2oKw==",
      "license": "MIT",
      "dependencies": {
        "@tweenjs/tween.js": "~23.1.3",
        "@types/stats.js": "*",
        "@types/webxr": "*",
        "@webgpu/types": "*",
        "fflate": "~0.8.2",
        "meshoptimizer": "~0.18.1"
      }
    },
    "node_modules/@types/webxr": {
      "version": "0.5.5",
      "resolved": "https://registry.npmjs.org/@types/webxr/-/webxr-0.5.5.tgz",
      "integrity": "sha512-HVOsSRTQYx3zpVl0c0FBmmmcY/60BkQLzVnpE9M1aG4f2Z0aKlBWfj4XZ2zr++XNBfkQWYcwhGlmuu44RJPDqg=="
    },
```

**Comment by Methuselah96** [comment]
Do you have something else depending on `@types/webxr` that's pinning it back? Have you tried deleting your `node_modules` as well? I think some package managers look at your `node_modules` as a hint when constructing a lock file.

I think I can define a range for `@types/webxr`, it used to not be possible/encouraged for `@types/*` packages. @jakebailey Any reason for me to not do that?

**Comment by jakebailey** [comment]
It's technically possible but we of course have not done so for any of the other intra-DT packages, as the version numbers are generated (so you end up having to release the package and then bump it in a follow-up release to know what number it is). I don't know what the best solution is.

`node_modules` being left over is most likely what is happening here.

**Comment by rnantes** [comment]
Turns out I had to delete the pacakge-lock.json and /node_modules/pacakge-lock.json and it resolved properly without having to add @types/webxr to my pacakge.json

**Comment by neodescis** [comment]
I also had the above error mentioned by @rnantes . Uninstalling and re-installing three and @types/three fixed that error, caused by the * version dependency. However, I'm still getting this error:

TS2307: Cannot find module 'three/webgpu' or its corresponding type declarations.

It seems we may need types for that too now in order for `noImplicitAny: true` to work.

**Comment by Methuselah96** [comment]
It sounds like you're probably using `node`/`node10` which [should no longer be used](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node). You should probably update the `moduleResolution` setting in your TSConfig to be 'node16', 'nodenext', or 'bundler'. See [this guide](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html) if you're not sure which one to use.

**Comment by neodescis** [comment]
Indeed we are using `node` for `moduleResolution`. We are using Angular, and that is still the default setting even for new projects. I'll have to see how Angular behaves if it's changed.

**Comment by Methuselah96** [comment]
According to [this comment](https://github.com/angular/angular-cli/issues/26290#issuecomment-2074599231), they've updated the new default to `moduleResolution: 'bundler'`

**Comment by Methuselah96** [comment]
Yeah, looks they updated it in https://github.com/angular/angular-cli/pull/27266

**Comment by neodescis** [comment]
I found that myself... but I also just created a new app using the CLI and it still had it set to `"node"`. However, I am happy to report that changing it to "bundler" in our app worked. Thank you!

**Comment by neodescis** [comment]
Scratch that... I was using an outdated CLI. It does indeed use `"bundler"` as the default now. Thanks again!

**Pull request merged**
