### PR TITLE
readline-transform: convert to `export =`

### PR DESCRIPTION
**Pull request by dex4er**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This definition uses `export default class` syntax so it works with TS >= 2.7

### CODE REVIEW

**Comment by andy-ms** [comment]
I tested and this package compiles in `typescript@2.0` in no errors, so why is this PR necessary?

**Comment by dex4er** [comment]
@andy-ms This module uses `export default class` syntax and it works correctly after TS 2.7 with `esModuleInterop` setting. Maybe the module compiles without errors but it won't work because of missing `default` symbol.

I don't want to rewrite this module to `export = class` syntax because it will break compatibility with current module and it will force me to use `namespace` for interfaces: ie. it will be `ReadlineTransform.Options` as a part of namespace rather than `ReadlineTransformOptions` as a separate symbol.

There is no possible to re-export just an interface as a part of namespace, so I really prefer 2nd style even if it doesn't work before TS 2.7.

**Comment by andy-ms** [comment]
There's already a test file `readline-transform-tests.ts` that's working in TS 2.0. TypeScript has supported default exports for a long time.

All this PR does is add a comment. `tsconfig.json` isn't published, it's just used for testing. There's no new feature being added that would require limiting the TS version.

**Comment by dex4er** [comment]
@andy-ms In that case I converted this typings to `export =` with class and namespace because the class is an exported element of this module.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
