### PR TITLE
[types/react] Allow null return from stateless components.

### LINKED ISSUE #14064: Incorrect type definition for React elements
- [ x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

According to the [official site](https://facebook.github.io/react/docs/conditional-rendering.html#preventing-component-from-rendering), React components may return `null` to prevent any rendering. But due to a likely bug in the definition files, I get a type error when trying to use a component that possibly returns `null`.  Here is the compiler error:

```
    (54,3): error TS2345: Argument of type '(props: PaginationProps) => Element | null' is not assignable to parameter of type 'ComponentClass<PaginationProps & {}> | StatelessComponent<PaginationProps & {}>'.
      Type '(props: PaginationProps) => Element | null' is not assignable to type 'StatelessComponent<PaginationProps & {}>'.
        Type 'Element | null' is not assignable to type 'ReactElement<any>'.
          Type 'null' is not assignable to type 'ReactElement<any>'.
```

I think the fix is to make `ReactElement` nullable

### PR DESCRIPTION
**Pull request by gaspard**
Fixes #14064

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react/docs/conditional-rendering.html#preventing-component-from-rendering

Fixes: #14064

### CODE REVIEW

**Comment by gaspard** [comment]
This seems to be related to the version of typescript used during testing, linting.

Typescript version 2.3.4 solved this.

**Comment by mhegazy** [comment]
> This seems to be related to the version of typescript used during testing, linting.

just remove the test for now. we do not want to force all react users to move to TS 2.3

**Comment by yuit** [comment]
@andy-ms  would using update to "// TypeScript Version: 2.3" will use 2.3.4 or it will use 2.3 ?

**Comment by yuit** [comment]
I would also add as an issue so we can keep track of such tests

**Comment by gaspard** [comment]
Note that this issue cannot be solved without a the fix here: https://github.com/Microsoft/TypeScript/issues/11566

The failing tests are all over the place, not in `types/react`.

Things like types/rrc, types/react-loader, etc.

So either we use 2.3.4 or this will have to wait (which is annoying for users using strictNull).

What is the issue with 2.3.4 ?

**Comment by vbfox** [comment]
Btw stateless components can also return false, same as [`render()`](https://facebook.github.io/react/docs/react-component.html#render) (I have a PR open to add it there #17025)

**Comment by minestarks** [comment]
@gaspard please fix the failing tests before we can merge, thank you.

**Comment by sandersn** [comment]
Thanks for your contribution. This PR has failing CI tests/and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the master branch.

**Comment by gaspard** [comment]
Please note that this issue **cannot** be fixed unless TS is updated to 2.3

The failing tests are **not** directly related to the new type but due to a typescript bug prior to 2.3

What is the issue with TS 2.3 ?

**Comment by gaspard** [comment]
@sandersn It would be nice to have arguments against upgrading build system to TS 2.3 in this PR so that annoyed users with this `null` issue understand why it is currently a **won't fix**

**Comment by andy-ms** [comment]
I favor @mhegazy's suggestion, change the definition and leave the test as a comment for when this package is upgraded to ts2.3.

**Comment by ericanderson** [comment]
(Which we should do soon to make State an optional generic on Component and co)

**Comment by gaspard** [comment]
@ericanderson Just ring me when TS is upgraded and I'll update this PR or create a new one.

@andy-ms It's not this test that fails, it's a lot of other packages depending on `react` that fail if we change the definition.

**Comment by ericanderson** [comment]
2.3 has been out long enough to enable its features. @gaspard you just have to update the header in index.d.ts for all the libraries that depend on react (and the react one)

**Comment by gaspard** [comment]
OK, will do !

**Comment by tkrotoff** [comment]
@gaspard wait for #17288 to be merged and then rebase. #17288 updates the headers to TypeScript 2.3 so you won't have to do it.

**Comment by tkrotoff** [comment]
#17288 has been merged => just need to rebase

**Comment by gaspard** [comment]
Some tests still fail because they use react types but are linked to TS 2.2. Changing them now.

**Pull request merged**
