### PR TITLE
added definitely typed files and tests for flowjs and ngflow

### PR DESCRIPTION
**Pull request by ryanmcnamara**

### CODE REVIEW

**Comment by vvakame** [comment]
*flowjs/flow/flowjs.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/flowjs
  * http://bower.io/search/?q=flowjs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (flowjs/flow/flowjs-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*flowjs/ng-flow/ng-flow.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/flowjs
  * http://bower.io/search/?q=flowjs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (flowjs/ng-flow/ng-flow-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@ryan10132 thank you for your contributions.
please rename flowjs/ng-flow/ng-flow.d.ts to ng-flow/ng-flow.d.ts

**Comment by ryan10132** [comment]
done, I believe that's what you wanted?

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
