### PR TITLE
[i18n-node]: Updated type definitions for `i18n` v0.10.0

### PR DESCRIPTION
**Pull request by niekvb**
Checklist:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

**Changing an existing definition**:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mashpie/i18n-node/releases/tag/0.10.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by niekvb** [comment]
Not sure what's suddenly causing these problems 🤔

```
Error in i18n
Error: Errors in typescript@4.0 for external dependencies:
##[error]../express-serve-static-core/index.d.ts(505,18): error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.

    at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:198:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

**Comment by woodcockjosh** [comment]
Yall need help on this?

**Review by woodcockjosh — CHANGES_REQUESTED** [review]
Unless this line is changed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3acf01d3cab18777e2ffdf9f48caa65d227cb3d3/types/i18n/index.d.ts#L461

We will still have a conflict with @types/express-serve-static-core@4.17.9

**Comment by woodcockjosh** [comment]
According to `i18n` repo owner `Response` interface definition should be removed. 

> as far as I get it:
> 
> ```
>     interface Response extends i18nAPI {
>         locals: any;
>     }
> ```
> 
> SHOULD NOT be part of i18n types as `locals` is a property of express response object

https://github.com/mashpie/i18n-node/pull/441#issuecomment-665055177

**Comment by niekvb** [comment]
> According to `i18n` repo owner `Response` interface definition should be removed.

Agreed, unfortunately this won't work either:
```TypeScript
interface Response extends i18nAPI {
    locals: i18nAPI & Record<string, any>;
}
```

I'll remove the `Express.Response` definition in `@types/i18n` as it conflicts with `@types/express-serve-static-core@4.17.9`

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## i18n ([<kbd>unpkg</kbd>](https://unpkg.com/browse/i18n@latest/))
was missing the following properties:
1. addLocale
1. removeLocale
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e2c674a90a4e23ca81499b0e4691249cc249ae0f
</p>

**Comment by niekvb** [comment]
Resolves mashpie/i18n-node#440, resolves DefinitelyTyped/DefinitelyTyped#46281

**Comment by TheOneAndOnlyGarcia** [comment]
any news when this pr will be merged? 👍

**Comment by niekvb** [comment]
@SomaticIT, @FindQ: Could you take a look at these changes?

**Comment by amcasey** [comment]
The change looks sane to me.  @woodcockjosh good to go?

**Comment by woodcockjosh** [comment]
> The change looks sane to me. @woodcockjosh good to go?

I guess it's better than nothing. but I don't understand why this is not just `any` rather than `Record<string, any>`

**Comment by amcasey** [comment]
@woodcockjosh fair questions.  @niekvb?

**Comment by woodcockjosh** [comment]
Can I suggest we close this PR in favor of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47811 ? I believe this will give developers some flexibility in how they want to deal with the incompatibility of `locals` between i18n and express-serve-static-core. It also addresses other issues like missing interfaces and the still unresolved merge conflict on this PR.

**Comment by niekvb** [comment]
> Can I suggest we close this PR in favor of #47811 ? I believe this will give developers some flexibility in how they want to deal with the incompatibility of `locals` between `i18`n and `express-serve-static-core`.

Agreed. I will close this PR in favor of  #47811.

**Pull request closed without merging**
