### PR TITLE
fix(jest): remove `require.requireActual` and `require.requireMock`

### PR DESCRIPTION
**Pull request by Calvin-LL**
`require.requireActual` and `require.requireMock` have been removed by https://github.com/facebook/jest/pull/9854
this pull request remove the type definitions

### CODE REVIEW

**Comment by CoolCyberBrain** [comment]
The linting errors are unrelated to the changes.

**Comment by CoolCyberBrain** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46272 has been resolved. This should be good now.

**Review by jwbay — APPROVED** [review]

**Comment by CoolCyberBrain** [comment]
> @CoolCyberBrain Everything looks good here. Great job! I am ready to merge this PR on your behalf.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! :heart:
> 
> (@NoHomey, @jwbay, @asvetliakov, @alexjoverm, @epicallan, @ikatyang, @wsmd, @JamieMason, @douglasduteil, @ahnpnl, @joshuakgoldberg, @UselessPickles, @r3nya, @hotell, @sebald, @andys8, @antoinebrault, @gstamac, @ExE-Boss, @quassnoi, @Belco90, @tonyhallett, @ycmjason, @devanshj, @pawfa, @regevbr: you can do this too.)
> 

Ready to merge

**Comment by CoolCyberBrain** [comment]
Ready to merge

**Pull request merged**
