### PR TITLE
[jquery] Fix PromiseLike compatibility for Promise3, Promise2, and jqXHR

### LINKED ISSUE #17966: jquery's $.getScript() is not compatible with PromiseLike
```ts
import $ from 'jquery'
Promise.resolve($.getScript(''))
```

```
Argument of type 'jqXHR<string | undefined>' is not assignable to parameter of type 'string | PromiseLike<string | undefined> | undefined'.
  Type 'jqXHR<string | undefined>' is not assignable to type 'PromiseLike<string | undefined>'.
    Types of property 'then' are incompatible.
      Type '{ <ARD = never, AJD = never, AND = never, BRD = never, BJD = never, BND = never, CRD = never, CJD...' is not assignable to type '<TResult1 = string | undefined, TResult2 = never>(onfulfilled?: ((value: string | undefined) => T...'.
```

This seems to affect any `jqXHR` whose generic argument is not assignable to `object`.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

Fixes #17966 

@Kovensky

### CODE REVIEW

**Review by Jessidhia — APPROVED** [review]
Nice, it actually works with real promises too.

```js
$.when().then(() => Promise.resolve('foo')).then(r => console.log('result', r))
// Object { state, always, catch, pipe, then, ... }
// result foo
```

...as long as it's JQuery 3, I assume 😆

**Comment by leonard-thieu** [comment]
> ```typescript
> $.when().then(() => Promise.resolve('foo')).then(r => console.log('result', r))
> ```

That actually works without the change. 

This PR is supposed to fix the issue you reported in #17966. The following works now.

```typescript
Promise.resolve($.getScript(''))
```

**Comment by Kovensky** [comment]
Oh, I meant at runtime; I never checked that before since I want to move _from_ jquery promises, not convert native ones into jquery :)

**Comment by tedypranolo** [comment]
Using
```
"compilerOptions": {
    
    "target": "es5",                          
     "lib": ["es5","dom","es2015.iterable","es2015.promise"],    
...
}

```
calling `await $.getJson(...)`  produces compile error `
 error TS1320: Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member.
` 
It was working up to version 3.2.7

**Comment by leonard-thieu** [comment]
I don't understand why this happens. @andy-ms any ideas?

`$.getJson(...)` returns a `jqXHR`. `jqXHR` extends from `Promise3`. `Promise3` had the following signature added in this PR to resolve an issue with passing it as an argument.

```typescript
// PromiseLike compatibility
then<TResult1 = TR, TResult2 = never>(onfulfilled?: ((value: TR) => TResult1 | PromiseLike<TResult1>) | undefined | null,
                                      onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>;
```

Removing the signature does fix the error. I don't understand why though. The signature is identical to `PromiseLike`. Shouldn't that make it awaitable?

**Comment by andy-ms** [comment]
See #18421.

**Comment by dan-def** [comment]
This is quite a breaking change from the previous versions of this definition file that used the legacy JQueryPromise<T> interface. Are there any plans to support that going forward or will we be expected to migrate to using Promise3 instead? What is the largest PromiseN that you are planning to support?

In addition, I note that $.Deferred only allows 3 type parameters which means it is impossible to create anything other than the new Promise<R, J, N>. As a result, trying to do something where you either download something using $.ajax or simply using an already resolved deferred if you already have it is not possible.

**Comment by leonard-thieu** [comment]
`JQuery.Promise<T>` should be largely compatible with `JQueryPromise<T>`. Keep in mind these new definitions reflect the changes to Promises in jQuery 3. Could you provide a code example where it breaks unexpectedly?

I've only taken Promises up to 3 parameters because that's the most that jQuery itself uses. I believe variadic kinds will make it possible to support n-parameter Promises. This solution is really only a holdover until that lands in TypeScript. That said, `Promise3` and `Promise2` should still be supportable even after variadic kinds is available.

> In addition, I note that $.Deferred only allows 3 type parameters which means it is impossible to create anything other than the new Promise<R, J, N>.

I'm not sure it's possible to declare `Deferred` in a way that supports both any-parameters and 2- or 3-parameters.

> As a result, trying to do something where you either download something using $.ajax or simply using an already resolved deferred if you already have it is not possible.

You can use explicit type annotations for this case.

**Comment by dan-def** [comment]
Thanks for your response.

`JQuery.Promise<T>` is compatible with `JQueryPromise<T>` but unfortunately `JQuery.jqXHR` is not because it extends `Promise3<TResolve, jqXHR<TResolve>, never,
        Ajax.SuccessTextStatus, Ajax.ErrorTextStatus, never,
        jqXHR<TResolve>, string, never>`. When you performed an ajax call before you would get back a `JQueryXHR` that extended `JQueryPromise<any>`.

This broke all of our code where we would do the following:

    protected Foo(): JQueryPromise<any> {
        return $.ajax().promise();
    }

The promise was returned rather than the `JQueryXHR` so that when we moved the promise up the stack, the callers would be dealing with promises rather than a `JQueryXHR` that they could `abort()`.

Obviously this was fixable by changing everywhere that expected a `JQueryPromise<T>` to instead use a `JQuery.Promise3<...>`, which gives us the power to ensure type safety for rejected promises and notifications which is definite improvement.

During the upgrade of the code I came across an instance where we were doing something like the following:

    let somePromise: JQueryPromise<any>

    if(needToDownload)
        somePromise = $.ajax(...).promise();
    else
        somePromise = $.Deferred().resolve().promise();

    somePromise.then((data) => {
        if(data != null) {
            ...
        }
    });

I tried refactoring this to use `Promise3` similar to the following:

    let somePromise: JQuery.Promise3<any, JQuery.jqXHR, never, JQuery.Ajax,SuccessTextStatus,JQuery.Ajax,ErrorTextStatus, never,JQuery.jqXHR, string, never>; //9 types required here

    if(needToDownload)
        somePromise = $.ajax(...).promise();  //return JQuery.Promise3<...> as above
    else
        somePromise = $.Deferred<...>().resolve().promise(); //only allowed 0-3 types here

    somePromise.then((data) => {
        if(data != null) {
            ...
        }
    });

However, the `Deferred` would only allow me to specify 3 types rather than the 9 required. Is this an oversight in the types file for the `Deferred` or have I made a mistake?

**Comment by leonard-thieu** [comment]
You have a couple of options here depending on how you want to use the resulting Promise.

---

### Assert as `JQueryPromise<any>`

```typescript
let somePromise: JQueryPromise<any>;

if(needToDownload)
    somePromise = $.ajax('').promise() as JQueryPromise<any>;
else
    somePromise = $.Deferred().resolve().promise();

somePromise.then((data) => {
    if(data != null) {

    }
});
```

This option should minimize breakages and should leave your code base similar to how it was before.

---

### Annotate as `PromiseLike<any>`

```typescript
let somePromise: PromiseLike<any>;

if(needToDownload)
    somePromise = $.ajax('').promise();
else
    somePromise = $.Deferred().resolve().promise();

somePromise.then((data) => {
    if(data != null) {

    }
});
```

Using `PromiseLike` can shield you from future breaking changes and may make it easier to transition away from jQuery in the future. Note that `PromiseLike` does not include a `catch` method.

---

### Assert as `JQuery.jqXHR`

```typescript
let somePromise: JQuery.jqXHR;

if(needToDownload)
    somePromise = $.ajax('').promise();
else
    somePromise = $.Deferred().resolve().promise() as JQuery.jqXHR;

somePromise.then((data) => {
    if(data != null) {
        
    }
});
```

Using `JQuery.jqXHR` allows you to make full use of jQuery's `jqXHR` object.

**Comment by dan-def** [comment]
Thank you. I went with option 1 in the end as we still need to handle the case when the AJAX call is unsuccessful but don't need the full `jqXHR`.

As a rule of thumb, I try and avoid the `as` keyword if it can be done a different way as I feel it can defeat the point of having type safety if you're just going to override it.

To me, being able to work with promises that can resolve, reject or notify with up to 3 arguments but not be able to create your own versions of them with `Deferred()` doesn't feel right. Are there any plans to extend the types file to make this possible in the future?

**Comment by dan-def** [comment]
In addition, if we do something like the following:

    public Foo() {
        $.ajax(...)
        .then((data, statusTest, jqXHR) => {
            ....
            return this;
        });
    }

I would have expected the return type of this function to be `JQuery.Promise3<this, JQuery.jqXHR, never, JQuery.Ajax,SuccessTextStatus,JQuery.Ajax,ErrorTextStatus, never,JQuery.jqXHR, string, never>` given that my `then` doesn't handle the failure from the request. However, the IDE reports the return type as `JQuery.Promise3<this, never, never, never, never, never, never, never, never>`?

I have some other peculiarities relating to parameters into the `off()` function and a line in the definition file where `Iterable<T>` is not found. Would you like me to post them here or create separate issues?

**Comment by leonard-thieu** [comment]
> As a rule of thumb, I try and avoid the as keyword if it can be done a different way as I feel it can defeat the point of having type safety if you're just going to override it.

This is one of those exceptional cases where the types ought to be compatible but aren't because of TypeScript's limitations.

> To me, being able to work with promises that can resolve, reject or notify with up to 3 arguments but not be able to create your own versions of them with Deferred() doesn't feel right. Are there any plans to extend the types file to make this possible in the future?

I'm not sure this is possible to do in a useful way, at least not without support for variadic kinds.

> I would have expected the return type of this function to be JQuery.Promise3<this, JQuery.jqXHR, never, JQuery.Ajax,SuccessTextStatus,JQuery.Ajax,ErrorTextStatus, never,JQuery.jqXHR, string, never> given that my then doesn't handle the failure from the request. However, the IDE reports the return type as JQuery.Promise3<this, never, never, never, never, never, never, never, never>?

I need to look into this a bit more but this is likely because `this` is not typed.

> I have some other peculiarities relating to parameters into the off() function and a line in the definition file where Iterable<T> is not found. Would you like me to post them here or create separate issues?

Create separate issues.

**Pull request merged**
