### PR TITLE
fix(node): `fs.cp` accepts URL for src and dest

### PR DESCRIPTION
**Pull request by sapphi-red**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    - [`fs.cp`](https://nodejs.org/api/fs.html#fscpsrc-dest-options-callback)
    - [`fs.cpSync`](https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options)
    - [`fsPromises.cp`](https://nodejs.org/api/fs.html#fspromisescpsrc-dest-options)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by sapphi-red** [comment]
IIUC the CI fail is not related to this PR.
```text
=== ERRORS ===
Error in gulp-sass
Error: At /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/node-sass/index.d.ts:{"line":141,"character":7}: 'eslint-disable' is forbidden. Per-line and per-rule disabling is allowed, for example: 'tslint:disable:rulename', tslint:disable-line' and 'tslint:disable-next-line' are allowed.
    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:151:9)
Error in node-sass
Error: At /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/node-sass/index.d.ts:{"line":141,"character":7}: 'eslint-disable' is forbidden. Per-line and per-rule disabling is allowed, for example: 'tslint:disable:rulename', tslint:disable-line' and 'tslint:disable-next-line' are allowed.
    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:151:9)
```

**Comment by peterblazejewicz** [comment]
fixing CI: #60974

**Comment by sapphi-red** [comment]
Thank you!

**Review by mcollina — COMMENTED** [review]
Could you add some test?

**Comment by sapphi-red** [comment]
This PR already includes a test.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60970/files#diff-43dbba9b88448a53bef751e789c5ad2dcff51148e5adfef3fc9a29ef97c51e75R706-R712

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by sapphi-red** [comment]
I have rebased on master branch to include #60974.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by sapphi-red** [comment]
Ready to merge

**Pull request merged**
