### PR TITLE
Replace express req.params 'any' type with index types (Revive #17610 and #24648)

### PR DESCRIPTION
**Pull request by felipeochoa**

### CODE REVIEW

**Review by erikmav — APPROVED** [review]

**Comment by andy-ms** [comment]
Does this actually require ts2.3?

**Comment by felipeochoa** [comment]
@andy-ms I think so. It was like that in the original PR -- something about the indexed type I think

**Comment by andy-ms** [comment]
Indexed types should be usable as far back as ts2.0, you might be thinking about mapped types?

**Comment by felipeochoa** [comment]
I don't know. I did not author the original PR; I "just" went through and updated the version on all the dependent projects

**Review by atd-schubert — APPROVED** [review]

**Review by cyrilschumacher — APPROVED** [review]

**Review by kvcpr — APPROVED** [review]

**Comment by andy-ms** [comment]
@felipeochoa Could you rebase this to include just the change to `express-serve-static-core` (but not the version change)?

**Comment by sheetalkamat** [comment]
@felipeochoa  please update the PR to revert the version changes as @andy-ms suggested. Thank you.

**Review by pinguet62 — APPROVED** [review]

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
@felipeochoa please update the PR to revert the version changes as @andy-ms suggested. Thank you.

**Pull request closed without merging**
