### PR TITLE
[angular-ui-bootstrap] Providers extends IServiceProvider

### PR DESCRIPTION
**Pull request by bastienmoulia**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by ry8806** [comment]
@bastienmoulia i'm unsure what this PR achieves?? could you elaborate please..?

**Comment by bastienmoulia** [comment]
@ry8806 Yes, it's to override the service linked to the provider with `$get` like it's managed on the other angularJs providers: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/index.d.ts#L41

Otherwise the `$get` in not defined.

**Comment by ry8806** [comment]
thanks

looks good to me

**Comment by ry8806** [comment]
👍

**Pull request merged**
