### PR TITLE
[emscripten] fix: better type hints for cwrap and ccall

### PR DESCRIPTION
**Pull request by ahaoboy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
 
Just optimization type hint, no change api
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Now we have better type hints~
image

You can also also use [e-emscripten](https://www.npmjs.com/package/e-emscripten) to experience now.

### CODE REVIEW

**Review by kbumsik — APPROVED** [review]
Now I didn't know we can do this with TS. Thanks for improving `@types/emscripten`. Great job!

**Review by zakki — APPROVED** [review]

**Review by zakki — APPROVED** [review]

**Comment by ahaoboy** [comment]
Ready to merge

**Comment by ceifa** [comment]
Shouldn't the argument string type be represented by `string | null`? I'm having trouble typing a function that accept a string pointer that can be null.

**Comment by ahaoboy** [comment]
> Shouldn't the argument string type be represented by `string | null`? I'm having trouble typing a function that accept a string pointer that can be null.

A pointer should be number ? If you parse a null to string, I think it's not safe

**Comment by ahaoboy** [comment]
(⊙o⊙)… 
Because Emscripten.JSType  hasn't Pointer type, the number has two meanings, 1: it's a number, 2: it's a pointer to anything
In your case, you can use any as before, or use 0
 @ceifa

**Comment by ahaoboy** [comment]
> > A pointer should be number ? If you parse a null to string, I think it's not safe
> 
> Yep, the string example maybe was not the best example, but take a look at this library(which is exactly my use case): https://www.lua.org/manual/5.4/manual.html#lua_tonumberx
> 
> The third argument is a pointer but it can also be null

We can't add a new type "pointer" : number | null, or we need to change Emscripten
If you return a NULL from c/cpp to js, we receive 0 in js, and NULL in c is equal 0, so if you have to pass a null to a pointer type, you can wrap a function
```
function f(ptr: number | null){
  return ccall('test', 'number', ['number'],[+ptr]);
}
```

**Comment by ceifa** [comment]
I don't think people should create their own wrap function if we already have the `cwrap` exactly for that. It is very common to pass null as arguments for pointer parameters in C.
What do you think in accept `number | null` on `number` and `string | null` on string? We still will get the type assertion and will work for pointers.

**Comment by ahaoboy** [comment]
> I don't think people should create their own wrap function if we already have the `cwrap` exactly for that. It is very common to pass null as arguments for pointer parameters in C. What do you think in accept `number | null` on `number` and `string | null` on string? We still will get the type assertion and will work for pointers.

You can create a PR, but in some case will have some type noise and need explicit Conversion


```
int sun(int, int)

// we can add null with number, it's weird but works  
function sum(number|null, number | null) -> number | null
```

this case
```
// wasm
int getWidth()

// js
function setWidth(number)

// we can't do  this
setWidth(getWidth())

// but
setWidth(+getWidth())
```

**Comment by ahaoboy** [comment]
How about this, we export a const NULL value, and it's value is 0, You can use it as number...
```
// c
define NULL 0


// js
export const NULL = 0
```
@zakki @kbumsik  
Can you give us some suggestions

**Comment by ahaoboy** [comment]
@ceifa 
You also can use the custom ccall/cwrap like e-emscripten  to temporarily solve your problem
https://github.com/ahaoboy/e-emscripten

**Comment by ceifa** [comment]
> You can create a PR, but in some case will have some type noise and need explicit Conversion

Yeah, that is bad, but also is bad to expect a strict number and receive a null. :/

What you think about this @zakki @periklis @kbumsik @lourd ?

**Pull request merged**
