### PR TITLE
fix(node): `fs/promises` - use `TimeLike` typealias

### PR DESCRIPTION
**Pull request by turansky**
Related - https://github.com/JetBrains/kotlin-wrappers/pull/1678

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Neat 👍

**Review by peterblazejewicz — APPROVED** [review]
@turansky thanks!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by turansky** [comment]
Ready to merge

**Comment by trastvolt** [comment]
turansky:patch-1

**Pull request merged**
