### PR TITLE
Improvement(react-sortable-tree): Add missing placeholderRenderer prop

### PR DESCRIPTION
**Pull request by jzoric**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [docs](https://github.com/fritz-c/react-sortable-tree/blob/2145c14053ab20df356606d8e7ecb5cd3a868309/README.md)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by wouterhardeman** [comment]
Hey! Sorry for the late response.

Can you tell me what ```draggedNode: {[index: string]: any};```is used for? There can't be any nodes when the placeholder is used right?

**Comment by jzoric** [comment]
Hey,
you are right, when there are no nodes placeholder is used and `draggedNode` is `null` but when you start to drag a node, from external source to the tree view, then `draggedNode` exists.

**Comment by wouterhardeman** [comment]
Ah okay! Thanks for the clarification. Sorry for the late response, I missed the first e-mail. I'll approve this now. 👍

**Review by wouterhardeman — APPROVED** [review]

**Comment by jzoric** [comment]
No problem. Thanks.

**Pull request merged**
