### PR TITLE
Add type definitions for svgo v2

### PR DESCRIPTION
**Pull request by remcohaszing**
The plugin types are partially auto generated from the svgo source code using a script and some replace all magic using
VS Code.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/svg/svgo/releases/tag/v2.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
> The plugin types are partially auto generated from the svgo source code using a script and some replace all magic using
> VS Code.

may I ask how? if one does this:
```ts
const svgo = require('svgo');
Object.keys(svgo)
[
  'loadConfig',
  'extendDefaultPlugins',
  'optimize',
  'createContentItem'
]
```
these are exported functions, just like on unpkg (as of 2.0.3)

We can probably drop v1 (unless there is a requirement to keep v1 being maintained for future updates)

**Comment by peterblazejewicz** [comment]
> We can probably drop v1 (unless there is a requirement to keep v1 being maintained for future updates)

Skip this, I've missed the other packages updates.

**Comment by remcohaszing** [comment]
> > The plugin types are partially auto generated from the svgo source code using a script and some replace all magic using
VS Code.
>
> may I ask how? if one does this:

I ran the following script, followed by some regexp baded replace magic in VS Code to convert the params into types with `@default` tsdocs.

```js
import { promises as fs } from 'fs'

async function main() {
  const plugins = await fs.readdir('plugins');

  for (let filename of plugins) {
    if(filename.startsWith('_')) {
      continue;
    }
    const name = filename.replace(/\.js$/, '')
    const {description,params} = await import('./plugins/'+filename)
    console.log(`
/**
 * ${description}
 */
export type ${name[0].toUpperCase}${name.slice(1)}Plugin = DefaultPlugin<${name}, ${params}>;
`
  }
}

main()
```

I added the `loadConfig` types. I decided not to include `createContentItem` for now, because it’s not documented in the readme and returns an internal class.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@remcohaszing thx!

**Comment by dhoulb** [comment]
@remcohaszing Thanks for doing this! Hoping it's merged soon :)

**Review by dhoulb — CHANGES_REQUESTED** [review]
The `DefaultPlugin` type should support the `active?: boolean` property.

https://github.com/svg/svgo#configuration

**Review by peterblazejewicz — APPROVED** [review]

**Review by dhoulb — APPROVED** [review]

**Comment by remcohaszing** [comment]
Ready to merge

**Pull request merged**
