### PR TITLE
Deprecate typings for moment-timezone because since 0.5.30 they're inside moment-timezone

### PR DESCRIPTION
**Pull request by ellenaua**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by ellenaua** [comment]
I cannot understand why BenchmarkPR failed @michelsalib @alanblins @asermax @borys-kupar @pristinesource

**Comment by pristinesource** [comment]
@ellenaua It looks like one of the other types is referencing a module that does not exist.  The type you are needing to look at is called "react-date-range".  The file at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-date-range/index.d.ts is going to need more work.  I see you changed the import line on that file, but the problem is that there is no "moment" module in DefinitelyTyped.

You could try changing the line that says:
```import * as moment from "moment";```
to be
```import moment = require('moment');```
but I am not sure if that will work without testing it.

Also, make sure you run tests locally for any types you have modified (https://github.com/DefinitelyTyped/DefinitelyTyped#verifying).  So, since you have modified "react-date-range" you will want to run this from your command line:
```npm run lint react-date-range```
that should show you the same errors that you are getting from the automatic GitHub checks.

Here is your error: https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=46846&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5

**Review by pristinesource — CHANGES_REQUESTED** [review]
I am a bit concerned about removing this altogether.  There is still a need for it for older versions of moment-timezone and there may need to be bug fixes for this type definition for those older versions.  In order for someone to use the new type definitions included with moment-timezone instead of these, they would simply not install this package, thus still leaving this available for use with older versions of moment-timezone. For that reason, I cannot approve this PR.

**Comment by pristinesource** [comment]
@ellenaua I would be comfortable removing it if we had a history version so we can still maintain and use the existing type definition.  See: https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package

**Comment by pristinesource** [comment]
Also, on a final note, it looks like the file at https://github.com/moment/moment-timezone/blob/0.5.31/index.d.ts is remarkably similar to the moment-timezone.d.ts for this type, except it is missing the author credits and copyright info.  Do you plan on giving credit to the authors of the file? Or at least the required copyright info for DefinitelyTyped (MIT License)?

**Comment by ellenaua** [comment]
@pristinesource yes I added today information about authors, 
sorry I copied moment-timezone.d.ts only so info about authors wasnt copied

**Comment by rthreei** [comment]
Can we please get this reopened and merged?

**Pull request closed without merging**
