### PR TITLE
Update constructor options for vimeo__player

### PR DESCRIPTION
**Pull request by sonngdev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Latest Vimeo player embed options](https://github.com/vimeo/player.js#embed-options)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
what kind of the problem this PR is to fix? IMO those were added to provide compatibility with `exactOptionalPropertyTypes` TS feature. I understand, not having this compatibility is sometimes advised

**Review by amcasey — CHANGES_REQUESTED** [review]
Can you please explain the goal of this change?

**Comment by thanhsonng** [comment]
> Can you please explain the goal of this change?

@amcasey  Yeah sure, maybe the original title/description wasn't clear enough. This PR adds `keyboard` and `pip` as new constructor options for the Video class. As you can see in the [official doc](https://github.com/vimeo/player.js#embed-options), they have been supported in recent versions but the typing hasn't caught up. 

I also include a refactor commit to remove unnecessary unions with `undefined`. But as I just learnt from @peterblazejewicz 

> what kind of the problem this PR is to fix? IMO those were added to provide compatibility with exactOptionalPropertyTypes TS feature. I understand, not having this compatibility is sometimes advised

Maybe this change is unfavorable. I can revert it if you deem appropriate.

**Comment by amcasey** [comment]
@thanhsonng Thanks for adding the new properties!  If they were introduced in a newer version of the library (I didn't check), please update the version in the header comment.

Yes, please keep the `| undefined` unless you have a specific reason for removing it.

**Comment by thanhsonng** [comment]
I have reverted the commit, also added `interactiveparams` as a new option for version 2.16.3 that was just released 7 hours ago (!). Updated the version number as well.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@thanhsonng thx!

**Comment by thanhsonng** [comment]
Ready to merge

**Pull request merged**
