### PR TITLE
added ReactBootstrap definitions

### PR DESCRIPTION
**Pull request by flyon**
definitions for React Bootstrap (http://react-bootstrap.github.io/)

### CODE REVIEW

**Comment by ziahamza** [comment]
Any progress on this ... or any specific reason why its not accepted?

**Comment by vvakame** [comment]
please fix travis ci failed.
and check these document. http://definitelytyped.org/guides/best-practices.html http://definitelytyped.org/guides/contributing.html

**Comment by aindlq** [comment]
I think this one can be closed because https://github.com/borisyankov/DefinitelyTyped/pull/5716 has been merged.

**Comment by mhegazy** [comment]
closing in favor of #5716

**Pull request closed without merging**
