### PR TITLE
[ramda] R.and and R.or will not dynamicly dispatch

### PR DESCRIPTION
**Pull request by adispring**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by adispring** [comment]
I just only modified `R.and` and `R.or`, not modified `R.tryCatch`, why CI/test throw a error about `R.tryCatch`.

I notice that, Yesterday dstlint ran test with ts@4.2, but today dstlint run test with all ts version from 4.2 to 4.6, and ts@4.6 throw the error about `R.tryCatch`. So what's the test rule? and How can I decide which ts version should I use?

**Comment by Nicholaiii** [comment]
> I just only modified `R.and` and `R.or`, not modified `R.tryCatch`, why CI/test throw a error about `R.tryCatch`.
> 
> I notice that, Yesterday dstlint ran test with ts@4.2, but today dstlint run test with all ts version from 4.2 to 4.6, and ts@4.6 throw the error about `R.tryCatch`. So what's the test rule? and How can I decide which ts version should I use?

DT tests are run with typescript@next unless a specific version is specified.

**Review by Nicholaiii — APPROVED** [review]

**Comment by adispring** [comment]
@Nicholaiii I saw ramda/index.d.ts has a [specific ts version, ts@4.2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L36), but it seems not working. `npm test ramda` will run test randomly from ts@4.2 to ts@4.6.

**Comment by adispring** [comment]
Ready to merge

**Comment by Nicholaiii** [comment]
> @Nicholaiii I saw ramda/index.d.ts has a [specific ts version, ts@4.2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L36), but it seems not working. `npm test ramda` will run test randomly from ts@4.2 to ts@4.6.

As far as I understand this just sets minimum version, for requiring the presence of a certain featureset. DT will test with 3.7 and up to @next unless a minimum version is specified.

**Pull request merged**
