### PR TITLE
webpack - BannerPlugin update

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Docs for the change](https://webpack.js.org/guides/migrating/#bannerplugin-breaking-change)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by bcherny** [comment]
This does not seem correct according to the docs https://webpack.github.io/docs/list-of-plugins.html#bannerplugin.

**Comment by DmitryEfimenko** [comment]
@bcherny you are looking at the old api (version 1.x)
These types are for version 2.x. I provided link to the documents in my initial comment. [Here it is again though](https://webpack.js.org/guides/migrating/#bannerplugin-breaking-change)

**Review by bcherny — APPROVED** [review]
I see. Looks good!

**Comment by bumbleblym** [comment]
there's a pending pull request #14593

**Comment by DmitryEfimenko** [comment]
and it seems it's a bit more comprehensive. Close this one?

**Comment by minestarks** [comment]
Thanks, closing as requested.

**Pull request closed without merging**
