### PR TITLE
[sql.js] fix export format for Node16 and browser environments

### PR DESCRIPTION
**Pull request by pastelmind**
Rewrite the export statements so that the package can be used correctly in projects using `module: "Node16"` as well as browser scripts.

Previously, the type definitions for [sql.js](https://github.com/sql-js/sql.js/) incorrectly modeled how the library behaves. The typings used `export default` even though sql.js is actually a UMD library. This works fine in projects with `module: "ESNext"`, but caused errors when using `module: "Node16"` due to a recent bugfix in TypeScript 4.8.3+. For details, see https://github.com/microsoft/TypeScript/issues/50690<wbr>.

Also, the type definitions previously used `SqlJs` as the global namespace for browser script contexts. However, the library actually uses `initSqlJs` when loaded with the <script> tag in browsers. This caused compiler errors for the following code:

```ts
// browser-script.ts
/// <reference types="sql.js" />

// initSqlJs is globally available, but the typings were wrong and caused errors
initSqlJs().then(module => {
  const db = new module.Database()
  // ...
})
```

These issues have been fixed by using `export =`, `import x = require()` and `export as namespace` statements with the correct identifier.

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] ~~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~~ No changes to tests, since only the export syntax has been updated.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:\
    https://github.com/microsoft/TypeScript/issues/50690#issuecomment-1251892044
    https://github.com/microsoft/TypeScript/issues/50690#issuecomment-1252611409

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## sql.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/sql.js@latest/))
was missing the following properties:
1. Module
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 952eeb530969050a99d2f3394d85c3fc3d5f9a74
</p>

**Comment by pastelmind** [comment]
@ffflorian Note that this is mostly a revert of #51613, though this still allows types such as `SqlValue` to be directly imported.

```ts
import { SqlValue } from 'sql.js' // This still works
```

It also allows importing `Database` directly as a type:

```ts
import { Database } from 'sql.js' // This still works

// OK
function foo(db: Database) { /* ... */ }
// Error: 'Database' only refers to a type, but is being used as a value here
let a = new Database()
```

**Review by ffflorian — APPROVED** [review]
Thank you!

**Comment by pastelmind** [comment]
Ready to merge

**Pull request merged**
