### PR TITLE
Fix Triangle.closestPointToPoint() prototype

### PR DESCRIPTION
**Pull request by voidexp**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://threejs.org/docs/?q=triangle#Reference/Math/Triangle

### CODE REVIEW

**Comment by florentpoujol** [comment]
👍

**Comment by piranha771** [comment]
👍

**Comment by andy-ms** [comment]
Looks like this is already fixed in master.

**Comment by V0idExp** [comment]
@andy-ms it is not fixed in master: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/three-core.d.ts#L3925
The conflict was due to the `three.d.ts` refactored into `three-core.d.ts`.
Updated the fix, please reopen the PR

**Pull request closed without merging**
