### PR TITLE
Adding Kendo UI TS definitions

### PR DESCRIPTION
**Pull request by stefanrahnev**
Added TypeScripts definitions for the Telerik Kendo UI framework (http://www.telerik.com/kendo-ui). 

P.S.I work for Telerik, being Product Manager for Kendo UI.

### CODE REVIEW

**Comment by vvakame** [comment]
*kendo-ui/kendo.all.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/kendo-ui
  * http://bower.io/search/?q=kendo-ui
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (kendo-ui/kendo.all-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@stefanrahnev thank you for your contributions.
please add a test file. and rename kendo-ui/kendo.all.d.ts to kendo-ui/kendo-ui.d.ts

**Comment by IanYates** [comment]
Whenever I download Kendo (admittedly the professional version - I've never tried the open one) it comes with Typescript definitions already.  Will these be different somehow?

**Comment by stefanrahnev** [comment]
@IanYates  - no difference, this is pretty much the same file which you receive with the Kendo UI Professional trial or commercial distributions.

**Comment by stefanrahnev** [comment]
@vvakame - I applied the required file naming convention updates and included a test file. Hope everything is in conformance with the contribution guidelines how, and my pull request will be merged to the core. Thanks for the heads up.

**Comment by vvakame** [comment]
@stefanrahnev thanks mate!

**Pull request merged**
