### PR TITLE
Update types for tmp to the latest version of the API

### PR DESCRIPTION
**Pull request by silkentrance**
See the changes documented in the [CHANGELOG](https://github.com/raszi/node-tmp/blob/master/CHANGELOG.md).

The version number in the header was updated to `0.2`.

Additional tests have been added.

### CODE REVIEW

**Comment by silkentrance** [comment]
travis-ci builds are working, however their integration with github is no longer working.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@silkentrance thx for contribution!

**Comment by silkentrance** [comment]
@peterblazejewicz thanks for the approval.

**Comment by silkentrance** [comment]
Ready to merge

**Review by Perlmint — APPROVED** [review]

**Pull request merged**
