### PR TITLE
bugfix(react-router): Support optional params with a regexp in generatePath

### PR DESCRIPTION
**Pull request by sventschui**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pillarjs/path-to-regexp#modifiers
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by sventschui** [comment]
Not sure on how to address the newly required TS >=4.7. Happy to change all downstream types but I suspect this is not what the project wants, is it?

**Review by eps1lon — CHANGES_REQUESTED** [review]
Currently TypeScript 4.1 is still LTS so bumping to 4.7 is quite hefty. We can create a fork for 4.7 types if you're up for it.

**Comment by andrewbranch** [comment]
The typesVersions implementation looks right, and the code change looks reasonable to me. Will approve for merging this week if @eps1lon or another owner doesn’t object in the meantime.

**Review by eps1lon — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by sventschui** [comment]
Ready to merge

**Pull request merged**
