### PR TITLE
FIX Update FlatList and SectionList props

### PR DESCRIPTION
**Pull request by Esemesek**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [SectionList](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Lists/SectionList.js), [FlatList](https://github.com/facebook/react-native/blob/3aa8f09b4437eab8b91429b7325f8a6173ffa49a/Libraries/Lists/FlatList.js)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by iRoachie — APPROVED** [review]

**Comment by Esemesek** [comment]
It is already included in `React.ComponentType` - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L53

**Comment by vovkasm** [comment]
@Esemesek no. React.ComponentType says that function that returns null will be allowed, not `null` itself.
See:
no null allowed in FlatList

**Comment by Esemesek** [comment]
You are right. This is my fault because I was working on `"strictNullChecks": false` and this is how this repo has its compiler options set. I already went ahead and created pull request that makes all those fields nullable. Sorry for inconvenience. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29686

**Comment by vovkasm** [comment]
No problems, I actually found this by chance... and workaround was easy in my code. And thanks for super fast  #29686

**Pull request merged**
