### PR TITLE
fix export issue for cytoscape

### PR DESCRIPTION
**Pull request by wy193777**
cytoscape could be imported as 
```typescript
import cytoscape = require('cytoscape');
```
or
```typescript
import cytoscape from 'cytoscape'; // --allowSyntheticDefaultImports true
```

### CODE REVIEW

**Comment by phreed** [comment]
looks good to me.

**Comment by andy-ms** [comment]
Looks like you're right, it directly exports a function instead of an object with a `cytoscape` property.

**Comment by hudjoubert** [comment]
Hey, i trying use cytoscape.js with an Angular and Typescript. I import in my main module, but when I will import on component give me this message error 
`error TS2305: Module "path on node_modules" has no
exported member 'cytoscape'`.
I install the last version of types/cytoscape.

**Comment by andy-ms** [comment]
What did you type as the import statement?

**Comment by hudjoubert** [comment]
In main module I type this: 
`import cytoscape from 'cytoscape');`

in component I try all types of import:
`import cytoscape from 'cytoscape'`
`import cytoscape = require('cytoscape')`
`import {cytoscape} from 'cytoscape';``

but this error happened at the last.

**Comment by andy-ms** [comment]
`cytoscape` exports a function directly as a commonJS export, not as an es6 named export. So `import cytoscape = require('cytoscape')` is the correct import form.

**Comment by hudjoubert** [comment]
Yeaahhhh, you're right.  I try like you say and follow the example of link
 the documentation [http://blog.js.cytoscape.org/2016/05/24/getting-started/](url)

Thanks a lot. @andy-ms

**Comment by Jileni** [comment]
@hudjoubert it seems i share the same aims as you , i'm working on an angular project and i'm trying to use cytpscape to show a graph , i already worked on the cytoscape getting started from the blog but only on jsp , now i want it  on a better ui with angular. So  can you help me on this ? thanks .

**Pull request merged**
