### PR TITLE
[react-native-material-kit] Add MKComponent Builder property

### PR DESCRIPTION
**Pull request by timwangdev**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://xinthink.github.io/react-native-material-kit/docs/lib/builder.html>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by timwangdev** [comment]
@iRoachie please have review.

**Review by iRoachie — APPROVED** [review]
Been meaning to do this forever. Thanks for this

**Comment by timwangdev** [comment]
Hi @alloy , Can you help to merge this? Thanks!

**Comment by alloy** [comment]
Sure thing 👍

**Pull request merged**
