### PR TITLE
[google-libphonenumber] Add new method getLengthOfNationalDestination…

### PR DESCRIPTION
**Pull request by martin-badin**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test google-libphonenumber `](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <[method](https://github.com/ruimarinho/google-libphonenumber/blob/d02d2366b1a318409c100ee5cac9fbe4f1c33e9f/src/phonenumberutil.js#L1405)>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by StrictLine** [comment]
`index.d.ts` is modified exactly how I wanted, thanks! Admittedly, I don't know for what purpose are these exploratory test, so I cannot add any comments on that.

I'd be grateful if you could merge this PR as this makes the desired change.

**Review by StrictLine — APPROVED** [review]
`index.d.ts` is modified exactly how I wanted, thanks! _Admittedly, I don't know for what purpose are these exploratory test, so I cannot add any comments on that._

I'd be grateful if you could merge this PR as this makes the desired change.

**Review by jakebailey — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Comment by damien-swarm** [comment]
@martin-badin Pardon the ping, but do you know if this change makes the type definitions up to date with the latest `google-libphonenumber` version 3.2.33, corresponding to `libphonenumber` version 8.13.18?

The header https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-libphonenumber/index.d.ts#L1 still indicates a much older version.

**Pull request merged**
