### PR TITLE
Move `@types/google-apps-script` to `@types/script`

### PR DESCRIPTION
**Pull request by grant**
This moves `@types/google-apps-script` to `@types/script` in preparation for supporting TypeScript modules with Apps Script.

Other namespaces with `script`:
- https://github.com/script
- https://www.npmjs.com/~script
  - (`@script/types`) would be another option, but I'm hoping to use `@types`.

---
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/apps-script/reference/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by jafaircl — COMMENTED** [review]
Script is very generic and could refer to many things. What would be the benefit of this change?

**Comment by grant** [comment]
@jafaircl There are a few benefits:
- More readable TypeScript documentation
  - Before
    - screen shot 2018-11-11 at 03 27 11
    - screen shot 2018-11-11 at 03 27 22
  - After
    - screen shot 2018-11-11 at 03 32 16
    - screen shot 2018-11-11 at 03 32 27
- Alignment with [`@script`](https://npmjs.com/~script)
  - There are currently no packages now, but I plan to add a package management subsystem for use with [`@google/clasp`](https://github.com/google/clasp).
- Moving away from "Google" and more towards a standalone platform.

Of course TypeScript contains the string "script", so I'm sure you're cautious of this PR.
 
I could instruct users to `npm i @script/types` instead of `npm i @types/script`, but I'd rather use DefinitelyTyped if this PR is OK.

LMK how I can make this easier to review of you have any specific questions.

---

In terms of genericism of `script`, I can't find the requirement in the docs and see that there are a lot of generic types like `read`, `q`, `phone`, etc. If it would help, I can further attempt to acquire  https://www.npmjs.com/package/script, but we really don't have a npm modules for this platform.

**Comment by grant** [comment]
3 day checkup. Any requested changes @jafaircl @dhayab?

**Comment by jafaircl** [comment]
I appreciate the work you’ve put into this. But I don’t see the benefit to changing package names. It feels like making changes that could break other people’s projects just for the sake of making changes.

If you need to modify the types for your own packages, you could always provide them in your packages. If you want to create your own types at ‘@types/script’ you can certainly try that also.

**Comment by grant** [comment]
It's been 16 days. The @typescript-bot must be lagging.

**Review by sandersn — CHANGES_REQUESTED** [review]
apps-script might be a better name?

**Comment by grant** [comment]
Thanks @sandersn. Fair points. I'm mostly wanting to shorten the name to make a better devX like mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30439#issuecomment-437639322.

Not too concerned about existing users since it looks like most of them came from the Apps Script CLI this year. I'll close this and think a bit more. Perhaps bundling with the CLI instead.

**Pull request closed without merging**
