### PR TITLE
Update signature of module

### PR DESCRIPTION
**Pull request by Zzzen**
Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

See [issue #8996 ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8996)

### CODE REVIEW

**Comment by vvakame** [comment]
*mongodb/mongodb.d.ts*

to author (@CaselIT). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by CaselIT** [comment]
The `find` signature method you added in the mongodb definition is not for the nodejs api but for the mongo Shell. The  nodejs api documentation does not list it.

**Comment by Zzzen** [comment]
It has been included into nodejs. See [api](https://mongodb.github.io/node-mongodb-native/markdown-docs/queries.html#making-queries-with-find).
```collection.find(query[[[, fields], options], callback]);```

>>fields - indicates which fields should be included in the response (default is all)
@CaselIT

**Comment by CaselIT** [comment]
@Zzzen The link you provided is the documentation for version 1.4.9.
It's been removed in the documentation for [version 2.1](http://mongodb.github.io/node-mongodb-native/2.1/). I've also asked about it and [it's not a case of missing documentation](https://jira.mongodb.org/browse/NODE-625)

**Comment by Zzzen** [comment]
I see. So, how should I limit the fields to return? @CaselIT

**Comment by CaselIT** [comment]
Check che `Cursor` class, the objective returned by find. To limit the returned fields I think you can use the `filter` method
http://mongodb.github.io/node-mongodb-native/2.1/api/Cursor.html

**Comment by Zzzen** [comment]
Thanks.

**Comment by CaselIT** [comment]
@Zzzen regarding the mongodb other find method signature, it will be added to the definition when this pr is merged https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9064

**Pull request closed without merging**
