### PR TITLE
Move networkinterceptor to correct subfolder devtools for selenium webdriver

### PR DESCRIPTION
**Pull request by JulianJesacher**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-4.3.1.tgz](Direct download to tarball library)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
Does not apply.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## selenium-webdriver ([<kbd>unpkg</kbd>](https://unpkg.com/browse/selenium-webdriver@latest/))
was missing the following properties:
1. ThenableWebDriver
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b33ab39b1d6dd48580a3ddaa5a965317b8743fbd
</p>

**Review by SupernaviX — APPROVED** [review]
LGTM

**Review by navya9singh — APPROVED** [review]

**Comment by JulianJesacher** [comment]
@SupernaviX @navya9singh  Seems like it didn't work.

**Comment by SupernaviX** [comment]
Maybe because that comment was on a commit?

**Comment by SupernaviX** [comment]
Ready to merge

**Pull request merged**
