### PR TITLE
[next-auth] Fixed signIn, set optional conext, and set optional ID in credentials

### PR DESCRIPTION
**Pull request by JuanM04**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [Fixed `signIn`](https://next-auth.js.org/getting-started/client#signin)
  - [Set optional conext](https://next-auth.js.org/getting-started/client)
  - [Optional `id` in `Credetials`](https://next-auth.js.org/providers/credentials)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by 0ubbe — APPROVED** [review]
Thanks @JuanM04 👏🏽

**Comment by JuanM04** [comment]
Hey, @lluia, the version bumps up automatically?

**Comment by JuanM04** [comment]
Now, it's a fusion with #47111

**Comment by lluia** [comment]
@JuanM04 it should auto-bump as a _patch_ release. From the [main `README`](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) on this repo:
> This is because only the major and minor release numbers are aligned between library packages and type declaration packages. The patch release number of the type declaration package (e.g. .0 in 10.12.0) is initialized to zero by Definitely Typed and is incremented each time a new @types/node package is published to NPM for the same major/minor version of the corresponding library.

**Review by 0ubbe — APPROVED** [review]

**Comment by JuanM04** [comment]
Ready to merge

**Pull request merged**
