### PR TITLE
deprecate react-intl types

### PR DESCRIPTION
**Pull request by longlho**
react-intl v3 has been rewritten in TS https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#typescript-support so this package is no longer necessary

### CODE REVIEW

**Review by anion155 — CHANGES_REQUESTED** [review]
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

You need to update dependent packages. As far as log says, its `react-intl-redux` only.

**Comment by longlho** [comment]
Thanks for the pointer. I fixed that but now failing `typescript@3` test since `react-intl` relies on `typescript@3.3+`

**Review by anion155 — APPROVED** [review]
Looks good to me. And thanks for the great work in `react-intl`

**Comment by anion155** [comment]
Yep, I know май инглиш из бэд (из бед и огорчений). But I'm working on it.

**Comment by tkryskiewicz** [comment]
@longlho @anion155 
Thanks guys! Hope more and more packages provide their own typings.

**Pull request merged**
