### PR TITLE
Updated collection to reflect the returned data from shopify buy.

### PR DESCRIPTION
**Pull request by straiforos**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.) ==> Not applicable 
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
- [X] Other ==>  Mapped a undocumented type that is partially documented in the rest API documentation. Using Ng6 unit tests I exported the JSON of two collections with and without products. This showed me a couple flaws in my last PR, for the collections resource was not typed and typed improperly for one method. GraphQL interface was not expressing the two useful properties on it for simple paging, which is the benefit of this library. Also in this process identified a few other properties of use for the product interface.The documentation of the shopify buy js library is decent but could use more verbosity on the objects it returns.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@straiforos can you include some tests for these changes?

**Review by paulvanbrenk — CHANGES_REQUESTED** [review]
please add some tests

**Comment by straiforos** [comment]
@paulvanbrenk absolutely that will take me until tomorrow night. I have some angular 5 service tests so I will apply the same idea to a couple decent ones.

**Comment by straiforos** [comment]
@paulvanbrenk my apologies I have had some life circumstances pop up so I attended to those first. I will close this PR to create better unit tests. I will need to read up more on unit testing practices before I commit something useless.

Thank you for your time to review. 

Stephen Traiforos

**Pull request closed without merging**
