### PR TITLE
Redis add all caps PING and PUBLISH functions

### PR DESCRIPTION
**Pull request by sehrope**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/types/npm-redis and https://redis.io/ (*the upper case names are dynamically added to the `redis` module at runtime but were missing for these two commands*)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sehrope** [comment]
Mistake on the first URL listed above. Should be https://github.com/NodeRedis/node_redis for the code for the module.

**Review by 43081j — APPROVED** [review]

**Comment by 43081j** [comment]
looks good to me.

**Review by CodeAnimal — APPROVED** [review]
Looks good to me too.

**Comment by sehrope** [comment]
Great. Thanks all!

Big +1 on the streamlined process as well.

**Pull request merged**
