### PR TITLE
Improve localForage typings

### PR DESCRIPTION
**Pull request by garciat**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-localForage/angular-localForage.d.ts*

to author(@reppners). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*localForage/localForage.d.ts*

to author(@3x14159265). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by reppners** [comment]
looks good to me, thanks :+1:

**Comment by vvakame** [comment]
@reppners thanks!
@3x14159265 do you have any comment? can I merge this PR?

**Comment by arma-gast** [comment]
Take a look at my pr: https://github.com/borisyankov/DefinitelyTyped/pull/5800

**Comment by vvakame** [comment]
sorry for late.
@reppners thanks!
@Garciat thanks mate! :+1:

**Pull request merged**
