### PR TITLE
Remove password parameter from workbook protect/unprotect

### PR DESCRIPTION
**Pull request by Zlatkovsky**
case 2. Improvement to existing type definition.
It is not possible to use a password for protection/unprotection via the Excel API.

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
:+1:

**Comment by vvakame** [comment]
@robmhoward could you review this PR?

**Comment by MIchaelMainer** [comment]
@vvakame How can we use other reviewer's like myself or @Zlatkovsky for signoff? @robmhoward isn't working with these .d.ts files these days.

**Comment by Zlatkovsky** [comment]
@vvakame, ping on @MIchaelMainer's question.  We have both this pull request and another one (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9085) awaiting approval.

**Comment by vvakame** [comment]
history_for_office-js_office-js_d_ts_-_definitelytyped_definitelytyped
he maid initial commit.
and, I'm checking https://github.com/orgs/OfficeDev/people , but I can't find your name this page.

**Comment by robmhoward** [comment]
:+1:

**Comment by MIchaelMainer** [comment]
@vvakame My membership in OfficeDev wasn't public. I've made it public.

**Comment by vvakame** [comment]
oh, make sense. It merged!

**Pull request merged**
