### PR TITLE
[jsrsasign] add missing extname in ExtAuthorityKeyIdentifier

### PR DESCRIPTION
**Pull request by bindon**
All Extensions require an extname.
For all other extensions, extname is included, and AuthorityKeyIdentifier seems to be missing.

Real Certificate Extension Example:
image

```typescript
interface ExtCRLDistributionPoints {
    extname: 'cRLDistributionPoints';
    array: DistributionPoint[];
    critical?: boolean;
}
interface ExtCertificatePolicies {
    extname: 'certificatePolicies';
    array: PolicyInformation[];
    critical?: boolean;
}
interface ExtAuthorityKeyIdentifier { // extname is missing!
    kid: Hex;
    issuer?: Hex;
    sn?: Hex;
    critical?: boolean;
}
interface ExtExtKeyUsage {
    extname: 'extKeyUsage';
    array: string[];
    critical?: boolean;
}
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kjur/jsrsasign/blob/f3e32c71beb7e00e08f702543413d70636e7c862/src/x509-1.1.js#L2852
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 24 other properties...</summary>
<p>MessageDigest, Mac, Cipher, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, ucs2hextoutf8, oidtohex, hextooid, strpad, bitstrtoint, inttobitstr, bitstrtobinstr, binstrtobitstr, isBase64URLDot, namearraytobinstr, extendClass, crypto, asn1, jws, lang</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7748042c6a7b0db3bbbdb69a3e907938482e6240
</p>

**Review by ffflorian — APPROVED** [review]
Thanks!

**Review by ffflorian — APPROVED** [review]

**Comment by ffflorian** [comment]
Strange, seems like we had the same problem here. Anyone know what was going on in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63852 and here? @peterblazejewicz @sandersn @andy-ms

**Comment by ffflorian** [comment]
Ready to merge

**Pull request merged**
