### PR TITLE
Type Mutable Context in AWS-Lambda Handler

### PR DESCRIPTION
**Pull request by JimiPedros**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by simonbuchan** [comment]
I don't get it... what's the justification? There's nothing stopping you from doing something like:

```ts
import { SomeEvent, SomeResult, Context } from "aws-lambda";

interface CustomContext extends Context { ... }

export async function myHandler(event: SomeEvent, context: CustomContext): Promise<SomeResult> {
   ...
}
```

The point of this package is to tell you what you will get from AWS, and you can't control Context AFAIK.

**Comment by JimiPedros** [comment]
> I don't get it... what's the justification? There's nothing stopping you from doing something like..

Hey Simon, thanks for reading this pull request. The inspiration for these changes come from https://github.com/middyjs/middy/pull/666

At my workplace we use middleware that mutate the context property of the request handler. 

This pull request was inspired by the idea that we should be able to define the type of context which our handler expects depending on the middleware used.

**Comment by simonbuchan** [comment]
Assuming I understand what you're doing, I would first try [generically deriving the parameters from the handler type](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIHtwQB5mQbwFgAoZM5BTSXANTgBsBXCALmREYFsAjaAbhIBfEiTABPAA4oAEnBAATetAA8AFQCiANwjgANMlUAlCAGdG9MAD5kAXmQAKCNvBsNzsPspZcbDN7AAlLbWAApQ6JzAJhBqxmYWlgLEJKCQsIgoAMoREFo6eESk5E75dEysyCZgUKAA5knCxKnQ8EjI2ZwQceYFJOTIUKY9Zcxs3OjoSnINopJZObIKSlC2yIuKKh257vpb3QlJKVjpbQCywPIbAO5wg37UeDiQCiZoVE8EfeSRl0o3gyMKiYxDxJjNiOIpMhzr8IP8IOtlmpEdBkE8dPJXiioMo5GJ9HjLNYbF8yKpsWjcBisXINjjQDBUW58voGUz9lZkAB6LnIBg3MSvarMUlkAD8DhKLgMeT0FHePmhF2utwg9yeQRsoXCkWisSGCVFyDYIBKUEOELm7RyMJVgwpdltf1V2OUW2xiRExC8VWQAAtacs2FsnXCXYHUXY4MCQAhJTt5f4goV+kpHu5AWwqjUQLVVlKwAA6AuApKpiB4LwPTPsLi8FZ2KtPQtN2gMZhl8hp5A-O0QGvA0H0Vatou950A9sQTtkQZgRhQECfIr9WcGsA14UQXSiwQNJJAA)

The sticking point for doing that at the moment seems to be you're applying `middy` to what could already be `middy`ed handler types, right? So my concern with that is that `Handler<>` is a dumb and fragile type designed to avoid various typescript limitations while allowing backwards compatibility, and it might get weird changes in the future that would *type* break you without functionally breaking you (especially if AWS change things again, or if we start ab/useing the tuple changes in 4.0 to correctly restrict the return type).

I would suggest that instead of taking the `Handler` type from `aws-lambda` as a parameter that you declare *exactly* what type you do actually accept in the code, perhaps simply a copy of `Handler<>`, then if Handler does get updated to break you then your callers will be told (we would try to avoid breaking type assignment from the old to the new Handler type, unless there could be a runtime breakage!)

**Comment by ivanmartos** [comment]
I agree with @simonbuchan 
I'm also not aware of possibility to alter lambda execution context received from AWS. I would rather recommend extending the context in your code, instead of attaching new attributes to context that will never be filled by AWS

**Comment by JimiPedros** [comment]
closing based on conversation https://github.com/middyjs/middy/pull/666#discussion_r622732141

**Pull request closed without merging**
