### PR TITLE
fix(picomatch): Better types when returnState equals true

### PR DESCRIPTION
**Pull request by danez**
https://github.com/micromatch/picomatch/blob/master/lib/parse.js#L112
https://github.com/micromatch/picomatch/blob/master/lib/parse.js#L251
https://github.com/micromatch/picomatch/blob/master/lib/picomatch.js#L93-L97

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danez** [comment]
I think @Patcher56 was renamed to @p-kuen

**Comment by p-kuen** [comment]
Thanks, I will have a look in the next days - have a lot to do rn.

**Review by p-kuen — APPROVED** [review]
Thanks, LGTM

**Review by p-kuen — APPROVED** [review]

**Review by orta — APPROVED** [review]

**Comment by danez** [comment]
Ready to merge

**Pull request merged**
