### PR TITLE
[expo] SDK32 [WORK IN PROGRESS]

### PR DESCRIPTION
**Pull request by burtek**
# WORK IN PROGRESS, DO NOT MERGE

**Adding a PR now to notify others that a PR is being prepared :) Planning on finishing it in few hours**

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/expo/expo/blob/96d1d58163e9973a53ae572d743308e436ec8def/CHANGELOG.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by burtek** [comment]
Actually, expo provides now own typings for multiple packages (i.e. `expo-location` etc) but not all of them (i.e. `expo-contacts`, `expo-localization`). Should we remove duplicated modules and keep only the modules that don't have own typings?

**Comment by moshfeu** [comment]
Actually I haven't experience with modules which have only partial ts support. How the transpilation process handle duplicate definition?

**Comment by burtek** [comment]
Depending on project config, it uses the first definition found.

**Comment by moshfeu** [comment]
So, until expo will fully support types, this project should supply all the types. How is it possible to use the original expo package if `import .. from "expo"` will use the @types package?

**Comment by burtek** [comment]
@moshfeu `expo` internally is divided into multiple smaller packages (`expo-contacts`, `expo-permissions` etc). Some of them have definitions, some don't. My idea was to create definition for those packages that don't have defiitions and just re-export them **all** (both ours and official ones) from `@types/expo`

**Comment by moshfeu** [comment]
Interesting. So, the `import` is not `from "expo"`?

**Comment by burtek** [comment]
> Interesting. So, the `import` is not `from "expo"`?

@moshfeu `expo` re-exports modules from subpackages. The shole expo repository is a monorepo.
@janaagaard75 I will try to do it this way and will see how it works :)

**Pull request closed without merging**
