### PR TITLE
fix(matter-js): make index, body and isInternal optional in Vertex

### PR DESCRIPTION
**Pull request by hasparus**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/liabru/matter-js/blob/f1ba9b583ba92a56d307d63c850a0330d26bbd5e/src/geometry/Vertices.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by hasparus** [comment]
Hey @stevensnoeijen, do you think we could remove `Vertex` and use `Vector` instead?

The docs refer to `Vertices` as an array of `Matter.Vector` — https://brm.io/matter-js/docs/classes/Vertices.html

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## matter-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/matter-js@latest/))
was missing the following properties:
1. Matter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 603e3fc2f6b765c96f707e2fd64c26c4553a099b
</p>

**Review by stevensnoeijen — CHANGES_REQUESTED** [review]
Nice job! The optional properties are normally set within the library see https://github.com/liabru/matter-js/blob/f1ba9b583ba92a56d307d63c850a0330d26bbd5e/src/geometry/Vertices.js#L40
for Bodies.fromVertices this should indeed only be x and y see https://github.com/liabru/matter-js/blob/e49834d1e0574348cea3edd4a06d60edf1a67fa0/src/factory/Bodies.js#L212

I might create a later PR to make this somewhat more clearer. But for now this fix seems fine!

You only need to up the version patch version!

**Comment by stevensnoeijen** [comment]
> Hey @stevensnoeijen, do you think we could remove `Vertex` and use `Vector` instead?
> 
> The docs refer to `Vertices` as an array of `Matter.Vector` — https://brm.io/matter-js/docs/classes/Vertices.html

Yes, great idea!
Well, not remove that class but replace the vertex type in `Bodies.fromVertices` with vector would be a better fit.

**Comment by hasparus** [comment]
>  Well, not remove that class but replace the vertex type in Bodies.fromVertices with vector would be a better fit.

Ah, I just noticed that Vector is a class so we can't really do this.

I inlined `{ x: number, y: number }` there in my newest commit.

**Comment by stevensnoeijen** [comment]
> > Well, not remove that class but replace the vertex type in Bodies.fromVertices with vector would be a better fit.
> 
> Ah, I just noticed that Vector is a class so we can't really do this.
> 
> I inlined `{ x: number, y: number }` there in my newest commit.

Fine :)
Can you revert the changes done to `Vertex` as they are normally set in here https://github.com/liabru/matter-js/blob/f1ba9b583ba92a56d307d63c850a0330d26bbd5e/src/geometry/Vertices.js#L37
Also up the patch version before you release! :)

**Comment by stevensnoeijen** [comment]
> > Also up the patch version before you release! :)
> 
> AFAIK the version is bumped automatically, but we should remove the patch segment from the header.
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

ah I did not know that, thanks for sharing

**Comment by hasparus** [comment]
Edit: _Ah, I just noticed that Vector is a class so we can't really do this._

Vector doesn't have any methods nor any properties apart from `{ x: number, y: number }` so we can probably use it instead.

**Review by stevensnoeijen — APPROVED** [review]
Great adjustments 😎

**Comment by hasparus** [comment]
Ready to merge

**Pull request merged**
