### PR TITLE
Updated type definitions to yfiles for HTML 2.0.

### PR DESCRIPTION
**Pull request by martin-y**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.yworks.com/yfileshtml/#/api/yfiles.view.GraphComponent
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
The definitions claim to be written by "yWorks GmbH <http://www.yworks.com>". The last change seems to have been made by "Lukas Hollaender <lukas.hollaender@yworks.com>", who I've emailed a link to this. Would be nice to have a GitHub account in the "Definitions by" slot so that dt-bot could automatically notify authors of changes.

Also, the test failure is being fixed by #13399.

**Comment by martin-y** [comment]
Thanks for the reply!
'Would be nice to have a GitHub account in the "Definitions by" slot' - can we put our Github organization there (https://github.com/yWorks) or is a representative/single individual account required?

**Comment by andy-ms** [comment]
I think an organization will be fine; what matters is that dt-bot can pick it up and create an `@`-mention. Do you get notified when I mention @yWorks in this post?

**Comment by martin-y** [comment]
Hello, mentioning does not seem to work for organizations. According to https://github.com/blog/1121-introducing-team-mentions mentions will work for teams of organizations so I'll probably use @yWorks/html-team. Thanks!

**Comment by martin-y** [comment]
Dear Andy, 

organization mentions do not work I guess - the organization members did not get notified. 
The fork has been reviewed at yWorks and I've added a single contact to the .d.ts header. 

I'd be glad if the changes could be merged

About bundling: we'd like to maintain both options for our customers. Some find it more convenient to use the "typings" tool others will use our bundled version. We're bundling the .d.ts file with the Javascript library in a zip file and distribute this through our website. Could you suggest the best way to host multiple versions of a .d.ts file (e.g. on GitHub) - without bundling it with the library source code - that can be installed with the typings tool?

**Comment by andy-ms** [comment]
OK, I'll merge this. (Test failure will be fixed by #13399)
As for `typings`, you might want to ask at https://github.com/typings/typings/issues.
We don't yet support multiple versions; see Microsoft/types-publisher#3.

**Pull request merged**
