### PR TITLE
Add type definitions for fast9 npm package

### PR DESCRIPTION
**Pull request by JuanJoseGonGi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@JuanJoseGonGi if you mold your tests to this:
```ts
import { detect } from "fast9";

const width = 480;
const height = 640;
const gs = new Uint8Array(width * height);

const threshold = 20;
// $ExpectType Corner[]
const corners = detect(gs, width, height, threshold, true);
```
you will no longer need Node direct dependency, this will make CI tests quicker and save more CPU cycles.

Also, optional, do you intend to export 3 other methods?:
https://github.com/m320ng/fast9/blob/master/fast9.js#L4-L6

**Comment by JuanJoseGonGi** [comment]
> @JuanJoseGonGi if you mold your tests to this:
> 
> ```ts
> import { detect } from "fast9";
> 
> const width = 480;
> const height = 640;
> const gs = new Uint8Array(width * height);
> 
> const threshold = 20;
> // $ExpectType Corner[]
> const corners = detect(gs, width, height, threshold, true);
> ```
> 
> you will no longer need Node direct dependency, this will make CI tests quicker and save more CPU cycles.
> 
> Also, optional, do you intend to export 3 other methods?:
> https://github.com/m320ng/fast9/blob/master/fast9.js#L4-L6

Nice catch. I removed the node direct dependency and added the other 3 functions I missed.

**Comment by JuanJoseGonGi** [comment]
> @JuanJoseGonGi if you mold your tests to this:
> 
> ```ts
> import { detect } from "fast9";
> 
> const width = 480;
> const height = 640;
> const gs = new Uint8Array(width * height);
> 
> const threshold = 20;
> // $ExpectType Corner[]
> const corners = detect(gs, width, height, threshold, true);
> ```
> 
> you will no longer need Node direct dependency, this will make CI tests quicker and save more CPU cycles.
> 
> Also, optional, do you intend to export 3 other methods?:
> https://github.com/m320ng/fast9/blob/master/fast9.js#L4-L6

Nice catch. I removed the node direct dependency and added the other 3 functions I missed.

**Review by andrewbranch — APPROVED** [review]

**Comment by JuanJoseGonGi** [comment]
Ready to merge

**Pull request merged**
