### PR TITLE
More precise browser.name type for ua-parser-js

### PR DESCRIPTION
**Pull request by DerZyklop**
As you can see in the JSDoc, we know the possible values. It would be nice to have a more precise type than `string`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by MeLlamoPablo — CHANGES_REQUESTED** [review]
I feel conflicted with this change. Where are you seeing this JSDoc comment? [I don't see any in the public methods](https://github.com/faisalman/ua-parser-js/blob/97f3368ef053d63e24a04421dec1a55e73dbf2af/src/ua-parser.js#L767-L819).

If you mean the README, I would say from the `...` in there that the author's intention is to leave room for any string values:

image

So the only reliable source is the source code itself, which would create a maintainability burden on these types as for each release of `ua-parser-js` these types would need to be reviewed. For example, if a new `"Fancy Browser"` appears and users of this library specifically want to target it, their `name === "Fancy Browser"` code would error until the types are updated. This would work if the author themselves took care of the types, but for DefinitelyTyped this is a concern.

On the other hand, this isn't technically a breaking change since it only invalidates incorrect code, which can be really useful for devs to uncover potential bugs or dead code. And also autocomplete is a nice feature so devs don't have to double check whether it's `"Firefox"` or `"firefox"`.

Anyway those are my $.02. I'll flag this as Request changes to prevent automatically summoning a DefinitelyTyped maintainer, let's hear what others have to say first. Personally I'm not 100% against this change but I'm inclined to think that the way to go is to convince @\faisalman to distribute types, or to make a `ua-parser-ts` fork.

**Comment by MeLlamoPablo** [comment]
On a second thought, any package here can make types invalid by releasing a new version and changing the API. That's kind of the point.

> for each release of ua-parser-js these types would need to be reviewed

That would be true for every package. By taking my logic to the extreme, we should type every package as `any` and be done with it :man_shrugging:

So I'm not really confident in whether to agree or disagree.

**Comment by BendingBender** [comment]
I agree that browser names are constantly added to the list, someone would have to make sure to update the list every time a browser was added. I'm not really in favor of this change, I think `string` is a better type for this specific case.

**Comment by DerZyklop** [comment]
Thank you for all replies. I understand your concerns. I still want the autocompletion for my colleagues, so I added a type that I now have to maintain myself, if something changes. For those who want this too, here is my code:

```typescript
import { UAParser } from 'ua-parser-js';

export type CommonBrowserNames = 'Amaya' | 'Android Browser' | 'Arora' | 'Avant' | 'Baidu' | 'Blazer' | 'Bolt' | 'Camino' | 'Chimera' | 'Chrome' | 'Chromium' | 'Comodo Dragon' | 'Conkeror' | 'Dillo' | 'Dolphin' | 'Doris' | 'Edge' | 'Epiphany' | 'Fennec' | 'Firebird' | 'Firefox' | 'Flock' | 'GoBrowser' | 'iCab' | 'ICE Browser' | 'IceApe' | 'IceCat' | 'IceDragon' | 'Iceweasel' | 'IE' | 'IE Mobile' | 'Iron' | 'Jasmine' | 'K-Meleon' | 'Konqueror' | 'Kindle' | 'Links' | 'Lunascape' | 'Lynx' | 'Maemo' | 'Maxthon' | 'Midori' | 'Minimo' | 'MIUI Browser' | 'Safari' | 'Mobile Safari' | 'Mosaic' | 'Mozilla' | 'Netfront' | 'Netscape' | 'NetSurf' | 'Nokia' | 'OmniWeb' | 'Opera Mini' | 'Opera Mobi' | 'Opera Tablet' | 'Phoenix' | 'Polaris' | 'QQBrowser' | 'RockMelt' | 'Silk' | 'Skyfire' | 'SeaMonkey' | 'SlimBrowser' | 'Swiftfox' | 'Tizen' | 'UCBrowser' | 'Vivaldi' | 'w3m' | 'Yandex';

…

export const getBrowserByUserAgent = (userAgent : string) : CommonBrowserNames | undefined => {
    const parser = new UAParser();
    parser.setUA(userAgent);
    return parser.getBrowser().name as CommonBrowserNames | undefined;
}
```

The code is not 100% perfect, since the returned string can be some kind of 'FanyNewBrowserOnTheMatket', but that is acceptable for our project. 

From my perspective, it’s ok to close this issue now. I started related issue at [faisalman/ua-parser-js](https://github.com/faisalman/ua-parser-js/issues/560).

**Pull request closed without merging**
