### PR TITLE
Add the `cors` option to the browser-sync definition

### PR DESCRIPTION
**Pull request by thasmo**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.browsersync.io/docs/options#option-cors
- [x] ~~Increase the version number in the header if appropriate.~~
- [x] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.~~

### CODE REVIEW

**Comment by thasmo** [comment]
Anything else I can provide?

**Comment by pspeter3** [comment]
lgtm

**Comment by thasmo** [comment]
ping @vsiao @joeskeen

**Comment by thasmo** [comment]
What does it need to get this merged? Thanks!

**Review by joeskeen — APPROVED** [review]
Looks good to me. Sorry for the delay!

**Comment by thasmo** [comment]
Thanks! @vsiao, @pspeter3 can you approve the changes? Who may I contact to merge this or what are the next steps?

**Comment by pspeter3** [comment]
Unfortunately I do not have merge access, only approval access.

**Comment by thasmo** [comment]
@pspeter3 I see but you didn't approve formally yet, as much as I understand - like @joeskeen did.

**Comment by thasmo** [comment]
Awesome! :+1:

**Pull request merged**
