### PR TITLE
Baconjs event target

### PR DESCRIPTION
**Pull request by michael-jerred**
The Bacon.fromEvent method can take in JQuery objects, but it isn't currently allowed by the type definition.

### CODE REVIEW

**Comment by vvakame** [comment]
*baconjs/baconjs.d.ts*

to author(@alexander-matsievsky). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*lodash/lodash.d.ts*

to author(@bczengel). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by alexander-matsievsky** [comment]
:+1:

**Comment by michael-jerred** [comment]
@alexander-matsievsky : Updated :)

**Comment by alexander-matsievsky** [comment]
@michael-jerred Thanx!
@vvakame :+1:

**Comment by bczengel** [comment]
:+1: The lodash changes are same as PR #4927

**Comment by vvakame** [comment]
@alexander-matsievsky thanks!
@bczengel thank you so much!
@michael-jerred thanks mate!

**Pull request merged**
