### PR TITLE
Update Select.d.ts

### PR DESCRIPTION
**Pull request by VincentLanglet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Every props are allowed because they are passed to children component in the argument
```
selectProps: { [key in string]: any };
```

### CODE REVIEW

**Review by claasahl — APPROVED** [review]
Thanks for your contribution, @VincentLanglet

**Comment by lexwebb** [comment]
@VincentLanglet I know this is quite a while after this was merged in, but we've run into bugs created by this change to the types.

This change effectively means any props can be added onto the component which defeats the point of having types and type safety in the first place. The example we ran into was 'disabled' vs 'isDisabled', the compiler gives you no indication these are wrong, and are easy to mix up.

We cant seem to find what 'passed to children component in the argument' refers too. As far we can see the component takes no children, and components which you can replace do not have extra props passed to them from the parent.

If you remember, would you please be able to add more information in regards to this change, and why it was done? Because to us it looks like it needs to be undone.

**Comment by VincentLanglet** [comment]
I don't remember exactly but I needed extra props, used by my select component. 
Every props should be allowed because they are passed to children component in the argument.

You can't return error for `isDisabled` if the children component use it. Before my PR, it was.

**Comment by lexwebb** [comment]
Having looked at the source code, i have found where the children are passed props. It's in the 'selectProps' prop. I can see why you made this change.

@VincentLanglet  My apologies for bothering you about this!

I'm going to submit a PR with a few changes to allow the same behaviour but with a bit more type safety.

**Comment by ptgamr** [comment]
Yeap, We've got the issue with this changes as well...

```
type Keys = keyof SelectProps<any>
```

`Keys` is now typed as "string | number" - which is not helpful at all in our case, where we create a wrapper component of `<Select />` and having some property defined by default. We need to do

```
type WrapperComponentProps = Omit<SelectProps, 'defaultOptions' | 'onChange'>
```

It was working in previous version, but not anymore...

**Pull request merged**
