### PR TITLE
AngularJS - Fix #5931

### LINKED ISSUE #5931: AngularJS IFilterFunc too restrictive
IFilterFunc in angular.d.ts appears to require an array as the first parameter and it also specifies that the return type is the same as the input type.  However, it is possible for the first parameter to not be an array and the output type may be different than the input type.

See this plnkr for an example of a single number being used as input and the return type of the filter function being a string.

http://plnkr.co/edit/xwMZe5g9YuYNhW2obMjG?p=preview

### PR DESCRIPTION
**Pull request by richardTowers**
`IFilterFunc` was `filter('filter')` specific. This commit adds support
for all the built in filters and falls back to `Function` if a custom
filter is used.

Fixes #5931

### CODE REVIEW

**Comment by richardTowers** [comment]
Full list of built in filters from [the docs](https://code.angularjs.org/1.4.5/docs/api/ng/filter) implemented now.

**Comment by use-strict** [comment]
Already created fix in https://github.com/borisyankov/DefinitelyTyped/pull/5948

**Comment by use-strict** [comment]
@richardTowers , I see that your definition of orderBy is a bit different. The format of the predicate getter function is not very clear in the angular documentation, but I think it receives a single value as parameter and returns something based on that value, for comparison.

**Comment by richardTowers** [comment]
Agreed, your's looks correct, and good job on the docs; I couldn't be bothered!

I'll close this.

**Pull request closed without merging**
