### PR TITLE
kendo-ui: Add SchedulerView and TimelineView

### PR DESCRIPTION
**Pull request by fretje**
* Previous SchedulerView => SchedulerViewOptions (more inline with the rest of the naming)

* Also: remove some ? from event parameters that don't need it (the javascript code has been checked)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

It is to support extending the scheduler similar to http://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/custom-views/custom-view

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
👍 or 👎 @IAfanasov , @michaelaird ?

**Comment by michaelaird** [comment]
Won't changing the name of the SchedulerView interface be a breaking change? 

The rest looks fine to me.

**Comment by fretje** [comment]
It is indeed a breaking change, for those that actually use that name in their code, but generally this shouldn't be the case. 

What used to be the SchedulerView interface was actually the SchedulerViewOptions, the object literal that represents the options for one specific view (passed into the SchedulerOptions.views property). SchedulerOptions represents the object literal passed into the "kendoScheduler" jquery method. Similar as you pass a GridOptions object literal into the "kendoGrid" jquery method, or an AutoCompleteOptions object literal into the "kendoAutoComplete" jquery method, ...

So the naming SchedulerViewOptions is definitely more consistent with the rest of the code.

And also, I have been going trough the javascript code of the kendo scheduler, and there actually exists a SchedulerView object which acts as the base class for TimeLineView, AgendaView, etc... which is something totally different from the SchedulerViewOptions object (or interface). 
So I don't know how else this should be called to be able to use it as a base class for your own custom scheduler view (which is what I used it for).

**Comment by michaelaird** [comment]
That makes sense to me, just wanted to check on the name change.

**Pull request merged**
