### PR TITLE
[react-table]Added disableGlobalFilter in prep for 7.0.0 stable

### PR DESCRIPTION
**Pull request by riceboyler**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tannerlinsley/react-table/pull/1963

Added support for `disableGlobalFilter` that was added to both instance and column options in the above referenced PR.

### CODE REVIEW

**Comment by riceboyler** [comment]
FWIW, looking at the other PRs merged in on 3/6/20, it doesn't appear that the API changed in any other way since 7.0.0-rc.16.

**Comment by riceboyler** [comment]
@ggascoigne Looks like the bot isn't assigning for some reason. Just wanted you to have a heads up.

**Comment by riceboyler** [comment]
Please wait on this to be merged. Waiting for react-table to go to 7.0.0 stable

**Comment by riceboyler** [comment]
@ggascoigne Looks like Tanner is going to push 7.0.0 stable this afternoon. Hoping this can get reviewed and in soon thereafter.

**Review by ggascoigne — APPROVED** [review]
Looks good.

AFAIK this is the only interface change for the release version, which since it's just been released means that there's no reason to not merge this.

**Comment by riceboyler** [comment]
Sounds good to me. All we were waiting for was 7.0.0 stable. Thanks! 👍

**Pull request merged**
