### PR TITLE
@types/convert-units: export unit/measurement types

### PR DESCRIPTION
**Pull request by kibiz0r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/convert-units/convert-units/tree/v2.3.3

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I have a reservation, those were internal, so one could not look into naming convention.
But now, when those are to be public, should the type name be properly capitalized?
`unit` > `Unit`, etc. This should not impact usage (as there were no epxorts), but should improve consumption
Thoughts?

**Comment by vladkampov** [comment]
> I have a reservation, those were internal, so one could not look into naming convention.
> But now, when those are to be public, should the type name be properly capitalized?
> `unit` > `Unit`, etc. This should not impact usage (as there were no epxorts), but should improve consumption
> Thoughts?

I agree it would be a better choice.

**Comment by kibiz0r** [comment]
Updated to address capitalization feedback.

**Review by vladkampov — APPROVED** [review]
LGTM

**Review by peterblazejewicz — APPROVED** [review]

**Comment by vladkampov** [comment]
I’m thinking now maybe it would be easier now if we contribute to the original lib and rewrite it to typescript to deprecate this package. It seems inconvenient to maintain both…

**Comment by peterblazejewicz** [comment]
> I’m thinking now maybe it would be easier now if we contribute to the original lib and rewrite it to typescript to deprecate this package. It seems inconvenient to maintain both…

The v3 is TS native, so that's OK for v2. This will be published to NPM and used only with v2 (with less and less updates, if any)

**Comment by kibiz0r** [comment]
Ready to merge

**Pull request merged**
