### PR TITLE
Add missing method 'dropIndex' to Knex

### PR DESCRIPTION
**Pull request by mramos-dev**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://knexjs.org/#Schema-dropIndex>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by MRamos62786** [comment]
@tkQubo, any advice on fixing the failing build. I'm not sure how the errors relate to the change I made.

**Comment by andy-ms** [comment]
Looks like this was missed during #14288. Needs `// TypeScript Version: 2.1` added as the last line of the header (line 5).

**Comment by MRamos62786** [comment]
Thanks @andy-ms

**Comment by aozgaa** [comment]
Waiting on @tkQubo.

**Comment by tkqubo** [comment]
Sorry to be late.

Looks OK 👍

**Comment by aozgaa** [comment]
Thanks for the contribution and review, respectively!

**Pull request merged**
