### PR TITLE
Add type definition for sound-play

### PR DESCRIPTION
**Pull request by BrenekH**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@BrenekH thx for the PR!
Can you consider typing the return type as object containing two props, as in exec callback?
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
(see the promisified results). I think that should be the outcome of resolved promise

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by BrenekH** [comment]
@peterblazejewicz 
> Can you consider typing the return type as object containing two props, as in exec callback?

Thanks for the suggestion! I just added this in and I'm pretty sure the props have the correct type.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by BrenekH** [comment]
Ready to merge

**Pull request merged**
