### PR TITLE
Package: react-window-infinite-loader 1.0.3 updated types

### PR DESCRIPTION
**Pull request by jacklaurencegaray**
Updated the interface as per the latest version of `react-window-infinite-loader`

Version: 1.0.3
Link: https://www.npmjs.com/package/react-window-infinite-loader

### CODE REVIEW

**Review by Nibblesh — APPROVED** [review]

**Review by Nibblesh — CHANGES_REQUESTED** [review]
At the top of the file please change
```
// Type definitions for react-window-infinite-loader 1.0
```
to
```
// Type definitions for react-window-infinite-loader 1.0.3
```

**Comment by jacklaurencegaray** [comment]
Done @Nibblesh

**Comment by Nibblesh** [comment]
@jacklaurencegaray 

Sorry! apparently I was correct with my first approval, just checked the build and it failed due to the patch version my bad!

Could you undo that commit sorry again, and thanks for the help btw!

**Comment by jacklaurencegaray** [comment]
> @jacklaurencegaray
> 
> Sorry! apparently I was correct with my first approval, just checked the build and it failed due to the patch version my bad!
> 
> Could you undo that force push sorry again, and thanks for the help btw!
> 
> edit: Sorry for the waste of time, I'm new to adding @type packages, still getting used to the lint rules
> 
> `git reset --hard HEAD~1 && git push --force`

Had a fix for it now.

**Review by Nibblesh — APPROVED** [review]

**Pull request merged**
