### PR TITLE
[@types/ws]The first argument [of send(data, ...)] must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object

### PR DESCRIPTION
**Pull request by Avasam**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [?] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Closes #56554
- [N/A] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by amcasey** [comment]
Superficially, this looks correct, but it has the potential to break a lot of people so we need to hear from an owner.

**Comment by peterblazejewicz** [comment]
the source here says it can be a `number`:
https://github.com/websockets/ws/blob/00c34d726dca1c558fe5ee5e346979159b2297fe/lib/websocket.js#L448

**Comment by elibarzilay** [comment]
@Avasam ping re the above comment?

Also ping @loyd @mlamp @TitaneBoy @reduckted @teidesu @wojtkowiak @k-yle

**Comment by Avasam** [comment]
I forgot about this PR. I'm not sure how to link the fork back to it: https://github.com/Avasam/DefinitelyTyped/tree/ws

**Comment by peterblazejewicz** [comment]
try pushing changes to your fork using same branch name (`ws`). What happes? Is that recognized as PR commits update or as a new PR?

**Comment by Avasam** [comment]
> try pushing changes to your fork using same branch name (`ws`). What happes? Is that recognized as PR commits update or as a new PR?

That's what I hoped for as well, but no: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57921

**Comment by peterblazejewicz** [comment]
cool,, so close this one, thanks!

**Pull request closed without merging**
