### PR TITLE
React-data-grid: adding in onRowClick

### PR DESCRIPTION
**Pull request by KieranPeat**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes] (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes). I think I did, please feedback if not
- [x] Run `tsc` without errors. (ran tsc --p react-data-grid)
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: from demo js: http://adazzle.github.io/react-data-grid/scripts/example17-grid-events.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`. - not substantial changes, but can if requested

### CODE REVIEW

**Comment by SupernaviX** [comment]
The change itself looks good to me, but it looks like there's been a slight restructuring of the module in 2.0:

https://github.com/adazzle/react-data-grid/blob/master/migrations/v1-v2.md

If you're bumping the major version, could you rename the second export to "react-data-grid-addons" and [keep the v1 typings around](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version)? Aside from that, 👍

**Comment by KieranPeat** [comment]
@SupernaviX sorry I'm only just getting back to you on this, I suspected as we were doing more react-data-grid work that I might have to add some more changes in as well. I've moved your original stuff to v1 and updated my changes in the main directory

**Comment by OracPrime** [comment]
Is there a plan to fully update this for v2?  There are a number of properties in v2 missing from the types, e.g. getRowMetaData and cellClass.  Indeed we've found it more useful to have a generic column type, which can than catch errors in key:

export interface IDataGridColumn<T> extends ReactDataGrid.Column {
    getRowMetaData?: (rowdata: any) => any;
    cellClass?: string;
    key: keyof (T);
}

**Comment by KieranPeat** [comment]
I don't have any plans currently to check for the differences, so far just adding them when we find them. Not against checking for all missing ones, but struggling for time to go through it. I'll add those two in to this now as this request is still open.

**Comment by KieranPeat** [comment]
@OracPrime Weirdly, although in ReactDataGrid.js it's creating getRowMetaData as `(rowData) => rowData`, it's actually passing a second argument of column in its usage and tests in Cell.js - hasChangedDependentValues.

    if (currentColumn.getRowMetaData) {
      let currentRowMetaData = currentColumn.getRowMetaData(this.getRowData(), currentColumn);
      let nextColumn = nextProps.column;
      let nextRowMetaData = nextColumn.getRowMetaData(this.getRowData(nextProps), nextColumn);

      hasChangedDependentValues = !_.isEqual(currentRowMetaData, nextRowMetaData);
    }

I've added them in as:

    /**
      * Retrieve meta data about the row, optionally provide column as a second argument
      */
     getRowMetaData?: (rowdata: any, column?: Column) => any;
     /**
      * A class name to be applied to the cells in the column
      */
     cellClass?: string;

**Comment by KieranPeat** [comment]
@SupernaviX added two more properties to Column, className is easy enough to test, but wasn't sure how best to put a test in for getRowMetaData, any thoughts? Just simply put an a function with the right arguments to make sure it compiles, or should I do more?

**Comment by OracPrime** [comment]
The main way we're using it is when we need two properties to render.  So for example:

`            name: "Relative Start", key: "start", width: 120, formatter: RelativeStart,
            getRowMetaData: (row: ITask): Date => this.props.jobData.start
`
which refers to something like
`
 export interface IRelativeStartProps {
    value: Date; // Task start
    dependentValues: Date; // Job start
 }

 export class RelativeStart extends React.Component<IRelativeStartProps, {}> {
    public render(): JSX.Element {
        let taskStart = moment(this.props.value);
        let jobStart = moment(this.props.dependentValues);
        return <FormattedDuration value={taskStart.diff(jobStart)} />;
    }
 }
`

So if you were feeling really keen you could have something similar (or indeed just something which throws an error if the props values in the renderer weren't right.

**Comment by SupernaviX** [comment]
@KieranPeat The section on [optional parameters in callbacks](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) says that the second parameter shouldn't be optional (either way, consumers won't be required to provide it). Also, passing in a function with the right arguments would be fine for testing it.

**Comment by SupernaviX** [comment]
Also, looks like the repo owners just moved all the types into a subdirectory. Could you rebase?

**Comment by andy-ms** [comment]
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

**Comment by KieranPeat** [comment]
Sorry been on training. I've rebased from upstream master, and I've added a test around getRowMetaData. Unfortunately the rebase has messed up my ability to run the tests locally as it's doing:

    > definitely-typed@0.0.1 test /Users/peatk/projects/third-party/ForkedDefinitelyTyped
    > node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed --nProcesses 1
    
    Clean data
    Clean logs
    Clean output
    # Typing Publish Report Summary
    Started at Wed, 29 Mar 2017 12:52:24 GMT
    Found 3 typings folders in /Users/peatk/projects/third-party/ForkedDefinitelyTyped
    { Error: ENOENT: no such file or directory, open '/Users/peatk/projects/third-party/ForkedDefinitelyTyped/react-data-grid/index.d.ts' at Error (native)
      errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      path: '/Users/peatk/projects/third-party/ForkedDefinitelyTyped/react-data-grid/index.d.ts' }
    npm ERR! Test failed.  See above for more details.

It's picking up that the root type directory was changed from git changes before the rebase when trying to run tests.

**Comment by KieranPeat** [comment]
Added one more field to column with tests, hope it passes CI as can't currently run tests locally

**Comment by andy-ms** [comment]
This PR adds a directory `react-data-grid/v1`, should be `types/react-data-grid/v1`.

**Comment by KieranPeat** [comment]
Sorry, missed that when rebasing. Fixing now

**Comment by SupernaviX** [comment]
LGTM :shipit:

**Comment by KieranPeat** [comment]
Sweet, how do I go about getting this accepted and merged then?

**Comment by KieranPeat** [comment]
@yuit @dt-bot How do I get this merged now that the requested amends have been made?

**Comment by KieranPeat** [comment]
@SupernaviX Do you need to check the box on @dt-bot post as well to get it merged? Not sure what's stopping it from being merged

**Comment by SupernaviX** [comment]
I think a human has to do it. @andy-ms could you accept?

**Comment by KieranPeat** [comment]
Thanks @andy-ms @SupernaviX

**Comment by SupernaviX** [comment]
Thank you, this is really helpful

**Pull request merged**
