### PR TITLE
Added definitions for Sequelize 3.4.1

### LINKED ISSUE #4511: sequelize.d.ts fails with DataTypes.ARRAY(...)
Example:
```JavaScript
import Sequelize = require('sequelize');

[...]

names: {
  type: Sequelize.DataTypes.ARRAY(DataTypes.STRING) // Specific to PostgreSQL
}
```

`DataTypes.ARRAY(DataTypes.STRING)` provokes: `error TS2349: Cannot invoke an expression whose type lacks a call signature.`

### PR DESCRIPTION
**Pull request by drinchev**
I rewrote sequelize definitions ( backward compatible ) for the 3.4.1 version.

What I did ( most important improvements ) :
- Full support of 3.4.1 ( Removed Migrations, Events )
- Reuse of existing definitions ( Lodash, Bluebird, Validator )
- Improved DataTypes ( Fixes #4511 )
- Improved tests ( I took a lot of code from sequelize library tests )
- Improved `where` statements
- Renamed the old file to sequelize-2.0.0

I'm using these definitions for two weeks already, before I made this pull request and they work pretty well on my side ( ~ 5000 LOC NodeJS project ).

But anyway for anyone using sequelize definitions from DefinitelyType, please report if there are any problems before this is merged ( I don't wanna be the person that breaks anything ).

### CODE REVIEW

**Comment by vvakame** [comment]
*sequelize/sequelize.d.ts*

to authors(@samuelneff @codeanimal). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

@drinchev please resolve conflict

**Comment by kant2002** [comment]
Works fine so far for me, but bluebird conflicts with es6-promise in my project. But I don't use many fancy stuff on the project so far.

**Comment by horiuchi** [comment]
It's a great contribution! :+1:

**Comment by drinchev** [comment]
ping @vvakame @samuelneff @codeanimal

**Comment by vvakame** [comment]
sorry for late. I decided to merge. @drinchev thanks mate!

**Pull request merged**
