### PR TITLE
Update index.d.ts to import *

### PR DESCRIPTION
**Pull request by remimarenco**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

`export default Dropzone;` was leading me to have some issues with importing the module in my code.

I changed it to `export = Dropzone` so now we can do `import * as Dropzone from "react-dropzone";` like the others package importations in a tsx file.

### CODE REVIEW

**Comment by remimarenco** [comment]
Sorry for the false-notification. I wanted to do that quickly as it works properly on my side if I replace the `default` by `=`, but Travis testings do not seem to work.

Do you know why I make it works with `export = Dropzone` but not with `export default Dropzone`?

Thanks!

**Comment by andy-ms** [comment]
Hi, I believe this pull request may actually be correct.
To demonstrate:
```sh
npm install react react-dropzone
node -p 'require(\"react-dropzone\")' # Works
node -p 'require(\"react-dropzone\").default' # Undefined
```
See #13442.

**Comment by remimarenco** [comment]
Thank you @andy-ms! Will do on Wednesday

**Comment by remimarenco** [comment]
@andy-ms I made the change, although I did a `import * as Dropzone from 'react-dropzone'` instead of using the require. I thought it would be more consistent with some other tests I have seen around this repo.

But let me know if I should really do something else.

**Comment by andy-ms** [comment]
Sorry, tests are failing because the `types-2.0` branch isn't compatible with the latest tester
`import * as Dropzone` is OK since the compiler doesn't complain, but `import Dropzone = require("dropzone")` is technically more correct since `dropzone` doesn't actually export a namespace, it exports a module.

**Comment by GiedriusGrabauskas** [comment]
@remimarenco thanks. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13010

**Comment by remimarenco** [comment]
@andy-ms Unfortunately now it complains with this:

```
ERROR in [at-loader] frontend/src/components/modals/Upload.tsx:651:26
    TS2604: JSX element type 'Dropzone' does not have any construct or call signatures.
```

Do you know how I can fix that? (it does not prevent the react-dropzone js to be processed by webpack)

**Comment by andy-ms** [comment]
Not without knowing what code the compiler is failing on. Can you produce a simpler example? `react-dropzone-tests.tsx` in this repo compiles without errors.

**Comment by remimarenco** [comment]
Sure, here is what I am doing:

```
import * as Dropzone from "react-dropzone";

...
render() {
...
<Dropzone style={dropZoneStyle} onDrop={(acceptedFiles: any, rejectedFiles: any) => this.onDrop(acceptedFiles, rejectedFiles)}
>
    <div>Try dropping some files here, or click to select files to upload.</div>
</Dropzone>
...
}
```

I have `@types/react-dropzone` in `node_modules` folder and `react-dropzone`.

That's it :).

By changing this, in the definition file: `export default Dropzone;` to this `export = Dropzone;`, I don't have any complains anymore.

I am using `awesome-typescript-loader` in webpack:
```
{ test: /\.tsx?$/, loader: "awesome-typescript-loader" },
```

and my `tsconfig.json` is like this:

```
{
    "compilerOptions": {
        "outDir": "./taiga2/static/",
        "sourceMap": true,
        "noImplicitAny": false,
        "removeComments": true,
        "module": "commonjs",
        "target": "es6",
        "jsx": "react",
        "skipLibCheck": true,
        "skipDefaultLibCheck": true
    },
    "include": [
        "frontend/**/*"
    ],
    "exclude": [
        "node_modules",
        "frontend/node_modules",
        "frontend/src/components/modals/TreeView.tsx"
    ]
}
```

Thanks @andy-ms !

**Comment by andy-ms** [comment]
The latest `@types/react-dropzone` already uses `export = Dropzone`. Try checking your NPM dependencies?

**Pull request merged**
