### PR TITLE
[@types/react]: running prettier changes everything, Help?

### PR DESCRIPTION
**Pull request by lifeiscontent**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
For whoever's reviewing, the reason why I am committing this change is that when I ran tests locally they broke due to changes that prettier was making locally, I actually have plans to update some of the types here shortly, but wanted to at least know the tests are running correctly.

There are several HTML elements that are using the wrong interfaces and wanted to update that, as well as make props/state ReadOnly as I assume it should be.

**Comment by lifeiscontent** [comment]
test failed here as well, should I just add a `// prettier-ignore` to the failing line and move forward?

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3f99e35cbaf79850e7fe5e04f5880ab898967879
</p>

**Comment by eps1lon** [comment]
Could you check with DefinitelyTyped maintainers if there are plans to ensure prettier is run? If not, then I would not like this to get it because it'll diverge again and somebody will propose formatting again. This results in git noise that makes blame harder to use.

I would recommend ensuring that your IDE doesn't automatically run prettier on save (either globally or on a per-workspace basis).

**Comment by jakebailey** [comment]
Long term I do believe that we'd like to format all of DT and then have CI check to enforce this.

It used to be that prettier in VS Code didn't respect the prettier config if it wasn't at the workspace root (e.g., if you open one of the types packages and not the DT repo root, a very reasonable choice), but that appears to have been fixed.

By all rights, this repo's configuration implies that prettier should be run on everything, we just haven't actually enforced this.

But, I wouldn't accept this PR quite yet. I don't think it'd actually be the case that this would diverge too greatly (people tend to write code that looks like the surrounding code), but I am planning to (when I have the time and will) bulk reformat the entire repo and set up the workflows to enforce it.

For now, though, I would probably disable prettier within the workspace (pretty easy in VS Code's extension menu) unless the package is known to definitely already be formatted.

**Comment by eps1lon** [comment]
I just don't want a formatting commit every two months that clogs up git-blame unless we have good integration with [`blame.ignoreRevsFile`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt). It doesn't seem like this PR is needed if there are plans to do a bulk change that also sets up automatic enforcement. 

Anything else will just lead to blame pointing to commits that didn't actually change the line but merely had an author that always formatted on save instead of just the changed code.

**Comment by jakebailey** [comment]
Thankfully [github supports that now](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view), so when I make my PRs, I can add those there (but after those PRs, things should always be formatted anyway).

**Comment by gabritto** [comment]
Closing this for now because sounds like the solution is for us to run prettier on everything & enforce formatting. I realize it is inconvenient to have unformatted files, but until we do the formatting & enforcing, please consider just disabling prettier as suggested above.

**Comment by gabritto** [comment]
Closing this for now because sounds like the solution is for us to run prettier on everything & enforce formatting. I realize it is inconvenient to have unformatted files, but until we do the formatting & enforcing, please consider just disabling prettier as suggested above.

**Comment by lifeiscontent** [comment]
@gabritto I have questions still unanswered about the process of updating types for each version of the react types.

> There are several HTML elements that are using the wrong interfaces and wanted to update that, as well as make props/state ReadOnly as I assume it should be.
>
> is there a process in place for upgrading types across versions? or what has been the method for updating all versions of React?

@eps1lon do you have some suggestions here?

**Comment by gabritto** [comment]
@lifeiscontent yeah, I think a maintainer of the react types is the best person to answer that. Also, if you want to discuss questions like that, maybe it is best to post something in the "discussions" tab of the repo.

**Comment by eps1lon** [comment]
Tracking in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61494

**Pull request closed without merging**
