### PR TITLE
Add types/jsonlines

### PR DESCRIPTION
**Pull request by raineorshine**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@raineorshine those are not the same classes:
```js
> parser = require('jsonlines/lib/parser')
[Function: Parser]
> stringifier = require('jsonlines/lib/stringifier')
[Function: Stringifier]
```
goin literally, return type for both methods should be different IMO, though I agree, both are based on `Transform`.
So they have same public api shape, but different internals. What do you think?

**Comment by raineorshine** [comment]
Thanks for the feedback!

This works well:

```ts
export class Stringifier extends Transform {}
```

It would be nice if I could overload the 'data' event handler callback argument with a specific type for jsonlines since node's `Transform` only types it as `any`. However I haven't found a solution that works for 'data' while preserving other events:

```ts
  export class Parser extends Transform {

    // this is needed to allow other event subscriptions
    on: (eventName: string, cb: (...d: any) => void) => this 

    // this is needed to type 'd' arg in the callback function, but it gets typed as 'any' with the first overload
    on: (eventName: 'data', cb: (d: Line) => void) => this 

  }
```

@peterblazejewicz Do you know how this could be accomplished?

**Comment by peterblazejewicz** [comment]
> Do you know how the intended overload could be accomplished?

We cannot augment NodeJS types for this, as those event contracts are exported as classes, not interfaces.
You can do this (re-implementing all required methods):
```ts
export class Parser extends Transform {
    on(event: 'data', listener: (chunk: Line) => void): this;
    on(event: 'readable' | 'end' | 'close', listener: () => void): this;
    on(event: 'error', listener: (err: Error) => void): this;
    on(event: string | symbol, listener: (...args: any[]) => void): this;
}
```
(this is how it is done in other DT packages),
thx!

**Comment by raineorshine** [comment]
@peterblazejewicz Ready!

**Review by peterblazejewicz — APPROVED** [review]
LGTM@
@raineorshine

**Comment by raineorshine** [comment]
Ready to merge

**Comment by raineorshine** [comment]
Thanks for catching that! It seems it was a mistake, and was missed in the review.

I have submitted a fix in #60430

**Pull request merged**
