### PR TITLE
feat: add wshub types

### PR DESCRIPTION
**Pull request by muzychenka**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by k-yle — CHANGES_REQUESTED** [review]
It might be useful to import all these types from `@types/ws` instead of copy-pasting them into this package. This makes the types much easier to maintain. As far as I can tell, "wshub" is a fork of "ws" with only one difference: https://github.com/musicchenko/wshub/commit/8db3088ef

**Comment by musicchenko** [comment]
> It might be useful to import all these types from `@types/ws` instead of copy-pasting them into this package. This makes the types much easier to maintain. As far as I can tell, "wshub" is a fork of "ws" with only one difference: https://github.com/musicchenko/wshub/commit/8db3088ef

I've added a new interface called Room

**Comment by musicchenko** [comment]
> It might be useful to import all these types from `@types/ws` instead of copy-pasting them into this package. This makes the types much easier to maintain. As far as I can tell, "wshub" is a fork of "ws" with only one difference: https://github.com/musicchenko/wshub/commit/8db3088ef

And there are several new features like client id, rooms

**Comment by reduckted** [comment]
Please remove me from the list of maintainers.

**Comment by k-yle** [comment]
> And there are several new features like client id, rooms

> I've added a new interface called Room

Since `Room` is within `namespace Websocket`, you don't need to de-refine everything from `@types/ts`, since typescript automatically merges namespaces from multiple files. [see this page in the docs for more info](https://www.typescriptlang.org/docs/handbook/namespaces.html#multi-file-namespaces)

**Pull request closed without merging**
