### PR TITLE
Added definitions for the Urban Airship Cordova/Phonegap plugin

### PR DESCRIPTION
**Pull request by Justin-Credible**

### CODE REVIEW

**Comment by vvakame** [comment]
*phonegap-ua-push/phonegap-ua-push.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/phonegap-ua-push
  * http://bower.io/search/?q=phonegap-ua-push
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (phonegap-ua-push/phonegap-ua-push-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
please rename to urbanairship-cordova/urbanairship-cordova.d.ts

**Comment by Justin-Credible** [comment]
Renamed to urbanairship-cordova

**Comment by vvakame** [comment]
thanks mate!

**Comment by jonathanwkelly** [comment]
Is this meant to work in the context of an Ionic 2 app? Is it meant to facilitate an import statement, so that UAirship would be available to me inside my component code?

**Pull request merged**
