### PR TITLE
[webpack-hot-middleware] Separating client and middleware options into 2 separate types

### PR DESCRIPTION
**Pull request by saboya**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack-contrib/webpack-hot-middleware#config
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by saboya** [comment]
Also added the `close` function.

https://github.com/webpack-contrib/webpack-hot-middleware/blob/cb29abb9dde435a1ac8e9b19f82d7d36b1093198/middleware.js#L50...L55

**Comment by johanbaaij** [comment]
@saboya, should this have been a new major version?

**Comment by kevinmarrec** [comment]
@johanbaaij  Well the issue is that they keep in sync at least minor version between the package and its types. Which means they can only do patch releases on types.

Still that's bit boring :
```json
"@types/webpack-hot-middleware": "^2.25.0"  // Works since 4 months
```

And implementing breaking type changes in 2.25.1 just breaks projects that was importings options through :

```ts
import { Options as WebpackHotMiddlewareOptions } from 'webpack-hot-middleware'
```

**Comment by saboya** [comment]
@johanbaaij and @kevinmarrec: The problem is that passing client options to the middleware never worked anyway. So I'd rather let applications "break" to let developers know that what they're doing is... well, doing nothing.

**Comment by kevinmarrec** [comment]
@saboya Client options weren't the problem here. You changed main middleware options interface name, breaking the import even for people that never cared about client thing.

**Comment by saboya** [comment]
But it would break for anyone that did care about the client thing. And it wouldn't be an issue anyone unless you updated the types / didn't pin the version.

I see your point here about maintaining compatibility, and you can make a PR about it if you want. I think we can agree to disagree on this one.

**Comment by kevinmarrec** [comment]
I'm totally fine with the changes, my only concern was having a "breaking" change on a patch version release. But as the types version are tied to the package itself version, it couldn't have been other way than patch version, so according this, there wasn't just ideal solution.

The types are all good now.

**Comment by oneiho-safie** [comment]
```
[1m[31mERROR in /app/node_modules/@nuxt/types/config/build.d.ts
ERROR in /app/node_modules/@nuxt/types/config/build.d.ts(14,10):
14:10 Module '"../../../@types/webpack-hot-middleware"' has no exported member 'Options'.
    12 | import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
    13 | import { Options as WebpackDevMiddlewareOptions } from 'webpack-dev-middleware'
  > 14 | import { Options as WebpackHotMiddlewareOptions } from 'webpack-hot-middleware'
```

I has error when deploy in Jenkins. Useing Nuxt v2.x.
but build success in my local. need help.

**Comment by kevinmarrec** [comment]
@oneiho-safie 
It means you don't have same dependencies on the two.
Nuxt types have been fixed on last packages releases.

You need to somehow update accordingly your dependencies against Jenkins

**Comment by oneiho-safie** [comment]
@kevinmarrec thx! I fix my package.json
`"nuxt": "^2.0.0"` to `"nuxt": "^2.12.2"` then deploy success.

**Pull request merged**
