### PR TITLE
Openlayers - additional types.

### PR DESCRIPTION
**Pull request by cw882**
Added new types for StaticImageOptions and ZoomToExtentOptions. Added constructors to classes ol.control.ZoomToExtent and ol.source.ImageStatic

### CODE REVIEW

**Comment by mhegazy** [comment]
@cw882 is this still needed? can you refresh the PR?

**Comment by cw882** [comment]
@mhegazy this is still required but not sure how to update PR? Do I need to create a new PR to get rid of conflicts?

**Comment by mhegazy** [comment]
either merge master into your branch, resolve conflicts and push to this PR, or close and create a new one. up to you.

**Comment by cw882** [comment]
This PR has been recreated as #9856

**Pull request closed without merging**
