### PR TITLE
codemirror: Added some missing declarations

### PR DESCRIPTION
**Pull request by ukrukarg**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
http://codemirror.net/doc/manual.html#findWordAt
http://codemirror.net/doc/manual.html#addon_show-hint

### CODE REVIEW

**Comment by evmar** [comment]
@alexeagle

**Comment by evmar** [comment]
CC @rkirov look at the type for AsyncHintFunction -- it seems .async has to be optional otherwise there's no way to create one of these functions with the property?

**Comment by rkirov** [comment]
It's a limitation in JS too, that you can't create the function and the property on it with a single expression. You can have `async` be non-optional, if you are willing to lie at the first assignment :)

```typescript
let asyncHintFunc = (...) => {...} as CodeMirror.AsyncHintFunction;
// not truly AsyncHintFunction here.
asyncHintFunc.async = true;
// truth restored here
```

**Comment by bowdenk7** [comment]
@rkirov @evmar do yall think we're ready to merge?

**Comment by ukrukarg** [comment]
@rkirov @evmar Ping!

**Comment by alexeagle** [comment]
Discussed offline with @rkirov - thanks @ukrukarg !

**Pull request merged**
