### PR TITLE
[jsrsasign 10.5.20] Adding missing key arg for JWS.sign

### PR DESCRIPTION
**Pull request by andreisaikouski**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Official docs](http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.sign)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 19 other properties...</summary>
<p>MessageDigest, Mac, Cipher, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, ucs2hextoutf8, oidtohex, hextooid, strpad, bitstrtoint, inttobitstr, crypto, asn1, jws, lang</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6b9ad5f9deca6e935b724493cc8eca12347fd89f
</p>

**Comment by ffflorian** [comment]
@andreisaikouski thanks for the improvements! Could you add a test? 🙂

**Comment by andreisaikouski** [comment]
@ffflorian added!

**Comment by ffflorian** [comment]
> @ffflorian added!

Perfect, thanks!

**Review by ffflorian — APPROVED** [review]

**Pull request merged**
