### PR TITLE
[@types/three] Fix OBB.intersectsOBB argument not being optional

### PR DESCRIPTION
**Pull request by leumasme**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

There are no tests for /math/*, so i have not updated/added any.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/mrdoob/three.js/blob/dev/examples/jsm/math/OBB.js#L150>
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. AxisHelper
1. BinaryTextureLoader
1. BoundingBoxHelper
1. CanvasRenderer
1. CustomToneMapping

<details>
<summary>as well as these 27 other properties...</summary>
<p>DynamicBufferAttribute, EdgesHelper, FaceColors, Font, FontLoader, ImmediateRenderObject, JSONLoader, LensFlare, Math, MeshFaceMaterial, MultiMaterial, NoColors, ParametricGeometry, Particle, ParticleBasicMaterial, ParticleSystem, ParticleSystemMaterial, PointCloud, PointCloudMaterial, SceneUtils, TextGeometry, Vertex, VertexColors, WebGLRenderTargetCube, WebGLUtils, WireframeHelper, XHRLoader</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 488014f315dd62ba0222045bd46e047f5c626aa7
</p>

**Comment by joshuaellis** [comment]
Hey @leumasme would you be able to open this PR in 'three-ts-types', that's the actual repo for the type files.

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
@leumasme, I've approved the changes but because it doesn't add a test or modify we have to wait for a DT maintainer to merge.

**Review by andrewbranch — APPROVED** [review]

**Comment by leumasme** [comment]
Ready to merge

**Pull request merged**
