### PR TITLE
Kue process - add option to call it with a type and a callback

### PR DESCRIPTION
**Pull request by amiram**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/Automattic/kue#processing-jobs>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by amiram** [comment]
I just saw there are more issues. I'll update the pr with more fixes.

**Comment by minestarks** [comment]
@amiram so, sould I no merge, or...?

**Comment by pc-jedi** [comment]
@amiram I would like to help you updating the kue definition. Just tell me where I should start.

**Comment by amiram** [comment]
@minestarks Please merge. I don't have time currently to continue it. @pc-jedi There are many things to update. I don't know exactly where yet. In order to know that you can see kue docs and compare them to current definitions.

**Comment by amiram** [comment]
@minestarks added type for process callback and job.result
https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L205
https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L181

**Comment by amiram** [comment]
Added job.created_at
https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L195

**Comment by amiram** [comment]
Added get job callback
https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L161

**Comment by minestarks** [comment]
Thank you @amiram

**Comment by amiram** [comment]
@minestarks Is there anything I should do to make it published in npm? Currently it is not published.

**Pull request merged**
