### PR TITLE
Added "estimated_days" to Shippo response type

### PR DESCRIPTION
**Pull request by aylusltd**
added estimated days which is what comes back in their API.

Documentation is outdated on their site, but lists "days" as a response property. Hitting it in postmant shows "estimated_days". Either way existing type is stale, and estimated days is an optional parameter.

POST https://api.goshippo.com/shipments/
response:
```json
{
    "carrier_accounts": [],
    "object_created": "2022-05-22T04:04:18.420Z",
    "object_updated": "2022-05-22T04:04:18.564Z",
    "object_id": "048489de84bc4acda7aa20a78de9ab9e",
    "object_owner": "redacted",
    "status": "SUCCESS",
    "address_from": {
        "object_id": "fe32929b57a24b7eb4e7f49e7cb167c1",
        "is_complete": true,
        "name": "Mr. Hippo",
        "company": "",
        "street_no": "",
        "street1": "215 Clayton St.",
        "validation_results": {},
        "street2": "",
        "street3": "",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94117",
        "country": "US",
        "phone": "",
        "email": "",
        "is_residential": null,
        "test": false
    },
    "address_to": {
        "object_id": "9a987f31743847518f55c100218f000b",
        "is_complete": true,
        "name": "Mrs. Hippo",
        "company": "",
        "street_no": "",
        "street1": "965 Mission St.",
        "validation_results": {},
        "street2": "",
        "street3": "",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94105",
        "country": "US",
        "phone": "",
        "email": "",
        "is_residential": null,
        "test": false
    },
    "parcels": [
        {
            "object_state": "VALID",
            "object_created": "2022-05-22T04:04:18.395Z",
            "object_updated": "2022-05-22T04:04:18.441Z",
            "object_id": "aad40c7de34c4f519cd37099e729ae24",
            "object_owner": "redacted",
            "template": null,
            "extra": {},
            "length": "5.0000",
            "width": "5.0000",
            "height": "5.0000",
            "distance_unit": "in",
            "weight": "2.0000",
            "mass_unit": "lb",
            "value_amount": null,
            "value_currency": null,
            "metadata": "",
            "line_items": [],
            "test": false
        }
    ],
    "shipment_date": "2022-05-22T04:04:18.564Z",
    "address_return": {
        "object_id": "fe32929b57a24b7eb4e7f49e7cb167c1",
        "is_complete": true,
        "name": "Mr. Hippo",
        "company": "",
        "street_no": "",
        "street1": "215 Clayton St.",
        "validation_results": {},
        "street2": "",
        "street3": "",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94117",
        "country": "US",
        "phone": "",
        "email": "",
        "is_residential": null,
        "test": false
    },
    "alternate_address_to": null,
    "customs_declaration": null,
    "extra": {},
    "rates": [
        {
            "object_created": "2022-05-22T04:04:19.419Z",
            "object_id": "7f0639c64dc149f6ba4075fe61549ef8",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "9.01",
            "currency": "USD",
            "amount_local": "9.01",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "3 Day Select®",
                "token": "ups_3_day_select",
                "terms": "",
                "extended_token": "ups_3_day_select",
                "parent_servicelevel": null
            },
            "estimated_days": 3,
            "arrives_by": null,
            "duration_terms": "Delivery by the end of the third business day.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.419Z",
            "object_id": "fcc991ce1eac4e0e869ed41a6d0b7ea8",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "9.44",
            "currency": "USD",
            "amount_local": "9.44",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "2nd Day Air®",
                "token": "ups_second_day_air",
                "terms": "",
                "extended_token": "ups_second_day_air",
                "parent_servicelevel": null
            },
            "estimated_days": 2,
            "arrives_by": null,
            "duration_terms": "Delivery by the end of the second business day.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.418Z",
            "object_id": "301e55791a2d4af1b711260079f2449e",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "10.54",
            "currency": "USD",
            "amount_local": "10.54",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "2nd Day Air® A.M.",
                "token": "ups_second_day_air_am",
                "terms": "",
                "extended_token": "ups_second_day_air_am",
                "parent_servicelevel": null
            },
            "estimated_days": 2,
            "arrives_by": "10:30:00",
            "duration_terms": "Delivery on the second business day by 10:30 a.m. or 12:00 noon to most commercial destinations.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.417Z",
            "object_id": "96815de2e2d24ff5b9b0aa37857686b4",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "7.89",
            "currency": "USD",
            "amount_local": "7.89",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "Ground",
                "token": "ups_ground",
                "terms": "",
                "extended_token": "ups_ground",
                "parent_servicelevel": null
            },
            "estimated_days": 1,
            "arrives_by": null,
            "duration_terms": "Delivery times vary. Delivered usually in 1-5 business days.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.417Z",
            "object_id": "914977d21d5349a0bec4c020a25b298f",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "13.44",
            "currency": "USD",
            "amount_local": "13.44",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "Next Day Air Saver®",
                "token": "ups_next_day_air_saver",
                "terms": "",
                "extended_token": "ups_next_day_air_saver",
                "parent_servicelevel": null
            },
            "estimated_days": 1,
            "arrives_by": "15:00:00",
            "duration_terms": "Next business day delivery by 3:00 or 4:30 p.m. for commercial destinations and by end of day for residentail destinations.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.416Z",
            "object_id": "571d041f9ba7407dacc79fbdbe41af74",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "18.06",
            "currency": "USD",
            "amount_local": "18.06",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "Next Day Air®",
                "token": "ups_next_day_air",
                "terms": "",
                "extended_token": "ups_next_day_air",
                "parent_servicelevel": null
            },
            "estimated_days": 1,
            "arrives_by": "10:30:00",
            "duration_terms": "Next business day delivery by 10:30 a.m., 12:00 noon, or end of day, depending on destination.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:19.415Z",
            "object_id": "9e59676269f0475391c96db8e411cc60",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [
                "FASTEST"
            ],
            "amount": "48.06",
            "currency": "USD",
            "amount_local": "48.06",
            "currency_local": "USD",
            "provider": "UPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/UPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/UPS.png",
            "servicelevel": {
                "name": "Next Day Air® Early",
                "token": "ups_next_day_air_early_am",
                "terms": "",
                "extended_token": "ups_next_day_air_early_am",
                "parent_servicelevel": null
            },
            "estimated_days": 1,
            "arrives_by": "08:30:00",
            "duration_terms": "Next business day delivery by 8:30 a.m., 9:00 a.m., or 9:30 a.m. ",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": null
        },
        {
            "object_created": "2022-05-22T04:04:18.867Z",
            "object_id": "ed60ea5864514019b47d5861450d95d7",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [],
            "amount": "24.05",
            "currency": "USD",
            "amount_local": "24.05",
            "currency_local": "USD",
            "provider": "USPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/USPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/USPS.png",
            "servicelevel": {
                "name": "Priority Mail Express",
                "token": "usps_priority_express",
                "terms": "",
                "extended_token": "usps_priority_express",
                "parent_servicelevel": null
            },
            "estimated_days": 2,
            "arrives_by": null,
            "duration_terms": "Overnight delivery to most U.S. locations.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": "1"
        },
        {
            "object_created": "2022-05-22T04:04:18.866Z",
            "object_id": "1d73a20818bc4653bcb7a03adca36068",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [
                "BESTVALUE"
            ],
            "amount": "7.54",
            "currency": "USD",
            "amount_local": "7.54",
            "currency_local": "USD",
            "provider": "USPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/USPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/USPS.png",
            "servicelevel": {
                "name": "Priority Mail",
                "token": "usps_priority",
                "terms": "",
                "extended_token": "usps_priority",
                "parent_servicelevel": null
            },
            "estimated_days": 1,
            "arrives_by": null,
            "duration_terms": "Delivery within 1, 2, or 3 days based on where your package started and where it’s being sent.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": "1"
        },
        {
            "object_created": "2022-05-22T04:04:18.866Z",
            "object_id": "4a1274d677ce4119b0d21cff3eff6838",
            "object_owner": "redacted",
            "shipment": "048489de84bc4acda7aa20a78de9ab9e",
            "attributes": [
                "CHEAPEST"
            ],
            "amount": "7.28",
            "currency": "USD",
            "amount_local": "7.28",
            "currency_local": "USD",
            "provider": "USPS",
            "provider_image_75": "https://shippo-static.s3.amazonaws.com/providers/75/USPS.png",
            "provider_image_200": "https://shippo-static.s3.amazonaws.com/providers/200/USPS.png",
            "servicelevel": {
                "name": "Parcel Select",
                "token": "usps_parcel_select",
                "terms": "",
                "extended_token": "usps_parcel_select",
                "parent_servicelevel": null
            },
            "estimated_days": 7,
            "arrives_by": null,
            "duration_terms": "Delivery in 2 to 8 days.",
            "messages": [],
            "carrier_account": "redacted",
            "test": false,
            "zone": "1"
        }
    ],
    "messages": [
        {
            "source": "UPS",
            "code": "110971",
            "text": "RatedShipmentAlert: Your invoice may vary from the displayed reference rates"
        },
        {
            "source": "ShippoCommon",
            "code": "",
            "text": "Shipment origin or destination state is out of the service area for LSO."
        },
        {
            "source": "DHLExpress",
            "code": "",
            "text": "Shippo's DHL Express master account doesn't support shipments to inside of the US"
        }
    ],
    "metadata": "",
    "test": false,
    "order": null
}
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## shippo ([<kbd>unpkg</kbd>](https://unpkg.com/browse/shippo@latest/))
was missing the following properties:
1. AUTH_SCHEME_SHIPPO
1. AUTH_SCHEME_OAUTH
1. DEFAULT_HOST
1. DEFAULT_PROTOCOL
1. DEFAULT_PORT

<details>
<summary>as well as these 8 other properties...</summary>
<p>DEFAULT_AUTH_SCHEME, DEFAULT_BASE_PATH, DEFAULT_TIMEOUT, PACKAGE_VERSION, USER_AGENT, resources, Error, Resource</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 492056fdebb9a31a67a3feed233a4a880cb8951f
</p>

**Comment by amcasey** [comment]
LGTM but let's give @saiichihashimoto a bit more time to comment.

**Review by domdomegg — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
Given we waited the two weeks without response, I'll just approve this as it also LGTM.

**Comment by aylusltd** [comment]
Ready to merge

**Pull request merged**
