### PR TITLE
[standard-engine] Add missing /// <reference types="node" />

### PR DESCRIPTION
**Pull request by jablko**
#44178

### CODE REVIEW

**Review by atomicis — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@jablko 
I think there was overlooked mistype (I believe my VSCode extension could do this, by resolving `type` to proper module from Node), so I'd probably amend the module definition that way (in reference to your last commit), removing accidental import and restoring the 3slashes reference:
```diff
diff --git a/types/standard-engine/index.d.ts b/types/standard-engine/index.d.ts
index 7f1e714824..a16b82b874 100644
--- a/types/standard-engine/index.d.ts
+++ b/types/standard-engine/index.d.ts
@@ -1,11 +1,9 @@
 
-/// <reference types="node" />
 import eslint = require('eslint');
-import { type } from 'os';
 
 declare namespace standardEngine {
     class Linter {
diff --git a/types/standard-engine/standard-engine-tests.ts b/types/standard-engine/standard-engine-tests.ts
index bb9471cdc7..f7edcb6311 100644
--- a/types/standard-engine/standard-engine-tests.ts
+++ b/types/standard-engine/standard-engine-tests.ts
@@ -1,3 +1,4 @@
+/// <reference types="node" />
 import standardEngine = require('standard-engine');
 import { cli, linter as Linter, LinterOptions } from 'standard-engine';
 import path = require('path');
```
what do you think?

**Comment by peterblazejewicz** [comment]
so it surfaced thanks to your work on TS errors, btw!

**Comment by peterblazejewicz** [comment]
done as #44143

**Comment by jablko** [comment]
@peterblazejewicz Thanks for landing the proper fix!

I was surprised that pruning that import had zero consequences, or rather that the automation hadn't caught that unused import. I opened #44272 to propose enabling `noUnusedLocals`, for cases like this one.

**Pull request closed without merging**
