### PR TITLE
fix(pino): changing type from false to boolean of  LoggerOptions.time…

### PR DESCRIPTION
**Pull request by raoulus**
Some code formatting was done as well, sorry for that.

The only change was from `timestamp?: TimeFn | false` to `timestamp?: TimeFn | boolean`

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by raoulus** [comment]
Not sure if the failing checks are related to my commit, it says `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by raoulus** [comment]
Same error happens also for PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39355

**Comment by alferpal** [comment]
@raoulus can you try closing the PR and reopening again to see if this triggers the build again? Otherwise, try contacting a maintainer to see if they can trigger the travis build again

**Comment by raoulus** [comment]
Thanks @alferpal, re-triggering the pipeline helped. Everything's green now. Please have a look.

**Review by alferpal — APPROVED** [review]
LGTM

**Pull request merged**
