### PR TITLE
Plotly legendgrouptitle, legendrank

### PR DESCRIPTION
**Pull request by mrtnbrst**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
Plotly tests on master crash (on my machine), currently no plotly groups are used in the tests, so no need for editing those

- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
Note: I ran prettier with the npm command which lead to a test file being changed.
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
legendgrouptitle: https://github.com/plotly/plotly.js/issues/5260
Plotly attributes file with legendgrouptitle and legendrank right below:
https://github.com/plotly/plotly.js/blob/ab5e16afc34fa4f22efffef129f811381580e0fe/src/plots/attributes.js#L57

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
I don't have enough knowledge of plotly to assess if this makes it up to date with a version number, in doubt it does not.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. Fx
1. Snapshot
1. PlotSchema
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8d91330b6db2b60fa3bad1ffae3d0262bac6f119
</p>

**Comment by peterblazejewicz** [comment]
@mrtnbrst your test file changes seem to not include any actual change, except of format changes. Was that expected?

**Comment by mrtnbrst** [comment]
> @mrtnbrst your test file changes seem to not include any actual change, except of format changes. Was that expected?

As mentioned in the initial message, I couldn't even make the current tests work. Unfortunatelly my JavaScript / TypeScript knowledge is too little to figure out what's wrong. If we can make the test work (maybe it's just an issue on my machine), I can try to write a test for the change.
> Plotly tests on master crash (on my machine), currently no plotly groups are used in the tests, so no need for editing those
<br>

> Note: I ran prettier with the npm command which lead to a test file being changed.

The test file changed as it was, wasn't properly formatted - I ran the formatter as described in the `common mistakes` section, so yes, it it intended to commit the style change of the test file without any 'actual' change.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mrtnbrst thanks!

**Comment by mrtnbrst** [comment]
Ready to merge

**Pull request merged**
