### PR TITLE
[d3-zoom/d3-drag] Update to version 1.2/1.1, respectively

### LINKED ISSUE #16468: [d3-zoom/d3-drag] Update to version 1.2/1.1, respectively
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek  @gustavderdrache

Adds `zoom.clickDistance(...)`

### PR DESCRIPTION
**Pull request by tomwanzek**
* [Feature] Add support of `clickDistance(...)`
* [Chore] Bump version number.

Closes #16468 .

@gustavderdrache Another quick one for good measure... 😄 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-zoom/releases>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Review by gustavderdrache — APPROVED** [review]
You weren't kidding about it being a quick review!

**Comment by tomwanzek** [comment]
I have just added on **d3-drag** on this PR. It's the exact same change with minor version bump.

**Comment by tomwanzek** [comment]
@gustavderdrache Thanks for the swift turnaround! T

**Comment by tomwanzek** [comment]
@andy-ms If you have a second, could you kindly merge this PR. As always, thanks in advance!!! T

**Comment by tomwanzek** [comment]
@andy-ms Somehow, the merge has not triggered a publish to `npm/@types` for **d3-zoom** and **d3-drag**. Thx in advance for looking into it when you have a sec.

**Pull request merged**
