### PR TITLE
+ typings for angular-throttle

### PR DESCRIPTION
**Pull request by reppners**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-throttle/angular-throttle.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-throttle
  * http://bower.io/search/?q=angular-throttle
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-throttle/angular-throttle-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@reppners thank you for your contributions.
I think `angular.throttle` is better naming. https://github.com/BaggersIO/angular.throttle/blob/master/package.json#L2

**Comment by reppners** [comment]
renamed. thx for the hint :)

**Comment by vvakame** [comment]
@reppners sorry for delay. it merged! thanks.

**Pull request merged**
