### PR TITLE
plotly.js: improve plotly modeBarButtonsToAdd type

### PR DESCRIPTION
**Pull request by andoks**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Squash changes before final merge

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/plotly/plotly.js/pull/5654 & https://github.com/plotly/plotly.js/blob/v2.12.0/src/components/modebar/manage.js#L235
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.  
   - N/A - It merely brings the one definition __more__ up to date with the existing version

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. Icons
1. Fx
1. Snapshot
1. PlotSchema
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 285c5cc81014c3964a233538820e0c7b89abfcbf
</p>

**Comment by peterblazejewicz** [comment]
does it make sense to name those simply `ModeBarButtons` (as per usage `modeBarButtons[ToAdd]`,?

**Comment by andoks** [comment]
I would prefer to rename ModeBarDefaultButtons to ModeBarBuiltinButtons - ModeBarButton to ModeBarCustomButton - and then ModeBarButtonAny to ModeBarButton. However this will break backwards-compatibility.

I personally would prefer not to call ModeBarButtonAny ModeBarButtons, since it describes a singular object (either a typed string representing a builtin-button, or a custom-button). I am totally on board with not having "Any" in the name though, but that was what I came up with in the moment. However I do not have particular strong feelings about this, so if renaming it to ModeBarButtons is preferred by you as upstream maintainer, I can do that no problem.

**Review by peterblazejewicz — APPROVED** [review]
@andoks thanks!
LGTM!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by andoks** [comment]
Ready to merge

**Comment by andoks** [comment]
@peterblazejewicz: I can not see the updated version at https://www.npmjs.com/package/@types/plotly.js?activeTab=versions. Do you know when a new release of @types/plotly.js will be released so that I may use the updated version?

**Pull request merged**
