### PR TITLE
[chrome] add printingMetrics namespace

### PR DESCRIPTION
**Pull request by erwanjugand**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/docs/extensions/reference/api/printingMetrics
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

A screenshot of runtime : 
image

**Notes :** 
- Require [printing PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70664) before
- `sourceId` return `null`

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f038a2146e9278d47a6dd7a06debb3702e757674
</p>

**Review by nicolas377 — APPROVED** [review]
What's that sourceId comment about?

**Comment by erwanjugand** [comment]
> What's that sourceId comment about?

This is just to clarify that this value can be `null` and not `optionnal`

**Comment by erwanjugand** [comment]
Ready to merge

**Pull request merged**
