### PR TITLE
Select2 Better typing for v4

### PR DESCRIPTION
**Pull request by denisname**
This PR follows #24384, and improves typing for Selevt2 v4.

First, tests have been _radically changed_. All the tests in `select2-tests.ts` were coming from the [v3 documentation](http://select2.github.io/select2/). Now test file contains all the code to be found in [v4 documentation](https://select2.org/).

The type definition has been updated according to the tests and documentation. Lot of `any` types have been specified.

The `strictNullChecks` option has been unabled.

Removed v3 options: `formatSelection`, `formatResult`, `formatNoMatches`, `.select2("val", [value])`, `onSortStart`, `onSortEnd`, `readonly`, `separator`, etc.

Removed v3 types and interface: `AjaxFunction`, `Select2JQueryEventObject`, etc.

Removed properties in `Select2AjaxOptions` defined in parent interface.

Order properties in Select2.Options alphabetically and make sure everything is in there: [Configuration API](https://select2.org/configuration/options-api).

There is still some room for improvement. But this is already very complete. I am listening for any comments and improvements.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://select2.org/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by FrankGag** [comment]
No I'm using @types/jquery version 2.0.32, the one required by @types/select2 version 4.0.45

**Comment by FrankGag** [comment]
Thanks a lot for your answer, I'll probably update jQuery. Also, FYI, my package-lock.json seems to indicate that jQuery was already required but with version 2 : 
`"@types/select2": {
      "version": "4.0.45",
      "resolved": "https://registry.npmjs.org/@types/select2/-/select2-4.0.45.tgz",
      "integrity": "sha512-jvzZo7+kNTWgOo0aVxihZ4TiJDIkGOZIQ9LEafaD9zEJfq3ee8/OL6fvqXdsL6/ewn1F2tNAJolC1SszfbzwDg==",
      "dev": true,
      "requires": {
        "@types/jquery": "2.0.32"
      }
    }`

**Comment by evil-shrike** [comment]
Hi.
This PR completely broke our projects. Previous typing worked fine with jQuery 1.x/2.x. Select2 itself supports jQuery 1.x - look at https://github.com/select2/select2/blob/develop/select2.jquery.json
So what was the point to break type definitions by making it jquery-3 only?

Anyway it's not a good idea to do such changes with under a patch update. You could create another definition instead of breaking things for people.

>It need some work to write a select2 type definition which is compatible with older jQuery type definitions

I'm sorry but it **was** compatible before your changes.

**Comment by denisname** [comment]
First, nothing is broken just fix the version for that type definition: `npm install @types/select2@4.0.44`

> You could create another definition instead of breaking things for people.

No, I can not! Sure, it's a pity there is no way to have semantic versioning for type definitions. But that how it is, sadly.

You must realize that the previous definition used a lot of `any`, had no tests(!), had functions that did not exists and other problems. The point of using TypeScript is to have strong typing. What this definition lacked a lot: it was a mess before my last two PR. Sure it is not yet perfect. But it on a good way.

Select2 support jQuery 1/2 even if those are dead, yes! As I said before, if people still use jQuery 2 they are free to propose a PR. I don't have the time right now to do this. But I will be happy to review code and help.

**Comment by evil-shrike** [comment]
@denisname Excuse me, but are you an owner of the library? An owner of the typing? I guess no. Why do you decide that you are entitled to review code?
The library supports jQuery 1.x/2.x so the typing should do as well. And it did before your breaking changes. It has nothing to do with your attitude to jQuery 1/2 and the fact whether it's "dead" or not. 
If you wanted to fix some `any` types you could do that without breaking things. And BTW you broke not only jQuery 1.x stuff but some others like by removing `amd` field which makes the following code to fail:
`let DropdownSearch = $.fn.select2.amd.require("select2/dropdown/search");`

And it's ok that you "don't have the time" but then just rollback the changes and let other people to improve definitions without breaking existing code.

**Comment by evil-shrike** [comment]
>First, nothing is broken just fix the version for that type definition: npm install @types/select2@4.0.44

And you must realize what it means in practice. Consider a released library with `@types/select2: "^4.0.41"` in its dependencies. Now all projects that use that library have to reinstall the particular version 4.0.44 and pin it. The library authors have to release a fix with pinned version for avoiding problems for users. 
Additional work for free :(

**Comment by denisname** [comment]
As said, I may have miss some stuff. But biggest is done.
If people give some help everything can be fix really quickly.

**Comment by denisname** [comment]
Indeed, the `amd` field has been wrongly removed when removing old v3 properties. This is a quick and easy fix. No need to do a rollback.

For the jQuery v1 and v2 compatibility, I open a issue: #25548. Nothing impossible too.

> "don't have the time right now"

It's weekend!

By the way, be less aggressive in your speech.

**Pull request merged**
