### PR TITLE
Add support for ReadonlyArray<T> to chain() method

### PR DESCRIPTION
**Pull request by alexjlockwood**

### CODE REVIEW

**Comment by andy-ms** [comment]
A `ReadonlyArray<T>` is a `T[]`, so won't the array overload work?

**Comment by andy-ms** [comment]
A `T[]` is a `ReadonlyArray<T>`, so couldn't you just change the existing overload to take `ReadonlyArray<T>`?

**Comment by alexjlockwood** [comment]
@andy-ms You're right... much better. Thanks!

**Comment by andy-ms** [comment]
Oh, darn. Sorry, it looks like you actually do need both overloads due to the way generic type inference works.

**Comment by andy-ms** [comment]
Thanks!

**Comment by ericanderson** [comment]
Apologies. I just got back from Shenendoah. Glad to see this made it.

**Pull request merged**
