### PR TITLE
[@types/amqplib] Expose connection on channels

### PR DESCRIPTION
**Pull request by netroy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/amqp-node/amqplib/blob/main/lib/channel.js#L21

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## amqplib ([<kbd>unpkg</kbd>](https://unpkg.com/browse/amqplib@latest/))
was missing the following properties:
1. IllegalOperationError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f99d402607c07a39882ee1980ffe34fc06399dd5
</p>

**Comment by netroy** [comment]
@mnahkies @abreits @nfantone @nickzelei @XVincentX @seonggwonyoon 
Can one of you please review this 🙏🏽 🙇🏽

**Review by XVincentX — APPROVED** [review]

**Comment by mnahkies** [comment]
I'm a little unsure about this - I can't see this listed in the documentation, and therefore I think it was intended to be a private field. That said it seems fairly unlikely to change at this point :shrug: 

https://amqp-node.github.io/amqplib/channel_api.html#channel

**Comment by netroy** [comment]
Ready to merge

**Pull request merged**
