### PR TITLE
[@types/geojson] Add Coordinate Reference System to GeoJsonObject.

### PR DESCRIPTION
**Pull request by mat813**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://geojson.org/geojson-spec.html#coordinate-reference-system-objects
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by icholy** [comment]
The "crs" property is not part of the spec. All GeoJSON coordinates must use EPSG:4326 

* https://tools.ietf.org/html/rfc7946#section-4 
* https://tools.ietf.org/html/rfc7946#appendix-B.1

**Comment by mat813** [comment]
While it may be true that crs was dropped from the RFC in the end, GeoJSON libraries have to handle CRS because not everybody is using EPSG:4326, for example:

```
api_sig=> select ST_AsGeoJSON(coordonnees_legales) as coordonnees_legales_json from adresses limit 5;
                                           coordonnees_legales_json                                            
---------------------------------------------------------------------------------------------------------------
 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:2154"}},"coordinates":[723840.22,6261275.45]}
 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:2154"}},"coordinates":[723823.8,6261313.51]}
 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:2154"}},"coordinates":[723848.44,6261263.47]}
 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:2154"}},"coordinates":[723832.69,6261294.98]}
 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:2154"}},"coordinates":[723851.37,6261259.04]}
(5 lignes)
```

It would be great if the type here was in sync with what happens in the real world :sweat_smile:

**Comment by danvk** [comment]
@mat813 if your coordinates aren't WGS84, then you're not using GeoJSON.

Perhaps you could accommodate your GeoJSON variant by using an augmentation. If you add:

```ts
interface GeoJsonObject {
    crs?: CoordinateReferenceSystem;
}
```

somewhere in your own project, then the declarations will get merged and you'll have the property you want. (You might have to wrap this in some sort of `declare module` to make it work in practice.)

**Comment by icholy** [comment]
@mat813 I appreciate that `crs` is still in use. But if we add the property, it will lead people to believe it's supported in places where it's not. Like @danvk mentioned, you can use declaration merging to extend the `GeoJsonObject` in your own project.

``` typescript
declare namespace GeoJson {

  export interface GeoJsonObject {
    crs?: NamedCRS|LinkedCRS;
  }

  export interface NamedCRS {
      type: 'name';
      properties: {
        name: string;
      };
  }

  export interface LinkedCRS {
      type: 'link';
      properties: {
        href: string;
        type?: string;
      };
  }
}
```

**Comment by mat813** [comment]
Ah, with a bit of fiddling, I added a `types/geojson.d.ts` with:

```typescript
import 'geojson';

declare module 'geojson' {
  // export as namespace GeoJSON;

  export interface NamedCRS {
    type: 'name';
    properties: {
      name: string;
    };
  }

  export interface LinkedCRS {
    type: 'link';
    properties: {
      href: string;
      type?: string;
    };
  }
  export interface GeoJsonObject {
    crs?: NamedCRS | LinkedCRS;
  }
}
```

and this works.

I am quite new at TypeScript, thank you for pointing me in that direction.

**Comment by icholy** [comment]
@mat813 no problem! :)

**Pull request closed without merging**
