### PR TITLE
ramda - improve pick() output type readability

### PR DESCRIPTION
**Pull request by couzic**
When reading a question about `pick()`:
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/63571
I saw an opportunity to improve output type readability.

For example, `pick(["annie"], { annie: true, bob: true })` currently outputs:
`Pick<{ annie: boolean, bob: boolean }, "annie">`
With this PR, it will now output:
`{ annie: boolean }`

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0e5d3f7d8ed08177f4b505e48f527e97d159de9f
</p>

**Comment by rbuckton** [comment]
Can you add a test for this change?

**Comment by couzic** [comment]
@rbuckton the behavior did not change so there is not really a point in adding tests, the improvement is purely cosmetic, the resulting types are semantically identical but much more readable and obvious from a human point of view.

**Comment by rbuckton** [comment]
DT tests also verify the type you wrote behaves as expected, even if the behavior is purely cosmetic. It also means any maintainer for this types package can approve (barring changes that affect DT infrastructure), rather than needing to wait on a DT maintainer.

**Comment by couzic** [comment]
@rbuckton I looked at the existing tests and I saw more opportunities for improvement.
I also extended and improved the tests.

**Review by adispring — APPROVED** [review]

**Comment by couzic** [comment]
Ready to merge

**Pull request merged**
