### PR TITLE
uncomment tests that failed in versions prior to tsc 2.9

### PR DESCRIPTION
**Pull request by osdiab**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [N/A] Provide a URL to documentation or source code which provides context for the suggested changes
- [N/A] Increase the version number in the header if appropriate.
- [N/A] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
@osdiab do you plan to address the failing tests?

**Comment by osdiab** [comment]
@minestarks the tests are failing because `DefinitelyTyped` still doesn't support `typescript@2.9`, even though it's released. When would it likely be enabled?

**Comment by minestarks** [comment]
Hmmm, good question. @andy-ms ?

**Comment by andy-ms** [comment]
We usually only allow a new version on DT a month after its release, so please reopen this at the beginning of July.

**Pull request closed without merging**
