### PR TITLE
delete(feedme): remove package

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Not needed from 2.0.2:
https://github.com/fent/feedme.js/compare/v2.0.1...v2.0.2

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by ImRodry — CHANGES_REQUESTED** [review]
Packages in notNeededPackages.json should be sorted alphabetically

**Comment by peterblazejewicz** [comment]
> Packages in notNeededPackages.json should be sorted alphabetically

It should be automatic, never thought to check this detail. DT just rollled update to structore of this file. LMC

**Comment by peterblazejewicz** [comment]
@ImRodry let's wait. The sort step was removed:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/fe4505f5856690c4ec03c7c78ffbcf7be3ab390f#r48716597

**Comment by ImRodry** [comment]
> @ImRodry let's wait. The sort step was removed:
> [fe4505f#r48716597](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/fe4505f5856690c4ec03c7c78ffbcf7be3ab390f#r48716597)

It's not automatic and it doesn't have any practical purpose, it just makes the file way more organized

**Comment by peterblazejewicz** [comment]
amended, thx!

**Review by ImRodry — APPROVED** [review]
LGTM

**Pull request merged**
