### PR TITLE
[ember__runloop] Adding backburner to runloop public types

### PR DESCRIPTION
**Pull request by scalvert**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/runloop/index.d.ts#L13
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by scalvert** [comment]
@mike-north I chatted with @chriskrycho about this as part of changes I'm making to `@ember/test-helpers`. We agreed that extending the public exports as per ember itself made the most sense. Happy to chat more about it if necessary.

**Review by mike-north — CHANGES_REQUESTED** [review]
The current bar for adding things to end-user types like this is "it needs to be part of the public API". In this case, we need to dig in and figure out whether this particular flavor of "intimate API" is in fact public, and thus something we want to encourage direct use of.

I believe types you've cited as a documentation/source URL

>  Provide a URL to documentation or source code which provides context for the suggested changes: [emberjs/ember.js:packages/%40ember/runloop/index.d.ts@master#L13](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/runloop/index.d.ts#L13)

are only intended for consumption by other `@ember` packages. I think the intent here would be to treat them as equivalent to the `friend`/`internal` access modifier, and not take them as an indication of public API for ember.js consumers.

We've run into this a few times (i.e., which parts of the [router.js Transition](https://github.com/tildeio/router.js/blob/2d611a583b74b8f8d8290146cf2816f175e251e3/lib/router/transition.ts#L41) type should we use?) and the answer I've received from the core team is that the API documentation describes the public API. Anything that's not there, I tend to nag people until I get a clear public/non-public answer. "Intimate API" needs further clarification -- it's either public or not.

To be clear, I would be happy to get these types to a point where we're happy with them in the `./-private` folder without having to meet this bar.

**Action Requested:**

> 1. Please provide an unambiguous indication that these types are part of Ember's public API -- as in things that are guaranteed to not break without triggering a major framework release

or
> 2. Move these types into the `-private` subfolder, as an indication to consumers that they don't have the same stability guarantees, and are not to be taken as an indication of the official API surface.

**Comment by scalvert** [comment]
Thanks for the reply, @mike-north. What you say makes perfect sense. 

I realize that this API specifically walks the line between public and private, and I think it sensible to use the public API docs as the determining factor.

Just to be clear, you'd advocate moving them to a `-private` subfolder, which would allow 'friendly' addons/libs to utilize the types from there (think `@ember/test-helpers`, correct? If so, this seems reasonable.

This would mean that I'd import my types from the following location:

```
import { backburner } from '@ember/runloop/-private';`
```

Does this match your expectation?

**Comment by mike-north** [comment]
Having poked at this a bit, I think the following path is one that gets us everything we're after

1. Change the `@ember/runloop` types so the type of `const run` is a non-exported interface. This should require no alteration of tests, and should be the only changes necessary to `index.d.ts` here

```ts
// this is necessary in order to ensure your new `.d.ts` files
//   created in step 2 are published
import '@ember/runloop/-private/your_name(s)_here';

interface RunNamespace {
   // stuff
}
export const run: RunNamespace;
```

2. Add the backburner and other types to the `-private` folder, and write appropriate tests around them

3. We'll review this PR, get it merged, and a new `@ember/runloop` will be published

4. It will be the responsibility of each consuming package that needs this stuff to wire up these private types to the public API.

```ts
import { run } from '@ember/runloop';
import { IBackburner } '@ember/runloop/-private/your_name(s)_here';


declare module '@ember/runloop' {
  interface RunNamespace {
    backburner: IBackburner;
  }
}

// run.backburner will be of type IBackburner here
```

**Review by mike-north — APPROVED** [review]

**Comment by mike-north** [comment]
Looks like more breakage around `Pick<T,K>` in the nightly TS builds. Upstream issue tracked here https://github.com/Microsoft/TypeScript/issues/29898

**Comment by mike-north** [comment]
Re-submitted as #33516

**Pull request closed without merging**
