### PR TITLE
fix(react-native): optional trackColor colors

### PR DESCRIPTION
**Pull request by myrjola**
These changes fix a minor mistake in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29477. The `trackColor` colors are optional so that the developer can only set one of them. For example, I only want to set a custom color for the track when the switch is toggled on, i.e., `{ true: 'green' }`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: The trackColors are optional as can be seen from the Flow types https://github.com/facebook/react-native/blob/7536c9bdee27419ba21a46831de72edcad64dabc/Libraries/Components/Switch/Switch.js#L49-L50
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by myrjola** [comment]
Strange build failures. I can't see how my changes have caused this error:

```
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-native/test/index.tsx:365:14
ERROR: 365:14  expect  TypeScript@next compile error: 
JSX element type 'React.Fragment' does not have any construct or call signatures.
```

**Comment by iRoachie** [comment]
cc @alloy

**Comment by myrjola** [comment]
It seems `React.Fragment` is broken in Typescript 3.1 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29307.

Changing `React.Fragment` to `View` in the react-native tests makes `npm run lint react-native` pass. However, there are many React related failures in other libraries when running `npm test`.

**Comment by alloy** [comment]
@iRoachie Alas, I have not had the opportunity yet to run into this issue for us and don’t have the time to dive into it right now. Someone else who does will need to do so.

**Comment by alloy** [comment]
@iRoachie Alas, I have not had the opportunity yet to run into this issue for us and don’t have the time to dive into it right now. Someone else who does will need to do so.

**Comment by alloy** [comment]
@iRoachie Alas, I have not had the opportunity yet to run into this issue for us and don’t have the time to dive into it right now. Someone else who does will need to do so.

**Comment by alloy** [comment]
@iRoachie Alas, I have not had the opportunity yet to run into this issue for us and don’t have the time to dive into it right now. Someone else who does will need to do so.

**Pull request closed without merging**
