### PR TITLE
Fix redux-thunk #6231

### PR DESCRIPTION
**Pull request by Syati**

### CODE REVIEW

**Comment by vvakame** [comment]
#6231

**Comment by vvakame** [comment]
*redux-thunk/redux-thunk.d.ts*

to author(@tkqubo). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by tkqubo** [comment]
@vvakame It looks OK, it's nice refactoring.  
@Syati Thanks for your contribution!

**Comment by Syati** [comment]
:+1:

**Comment by tkqubo** [comment]
Oh I found that some might want to use `default` export for thunk.  So `default export` is needed, too. @Syati

**Comment by Syati** [comment]
I will close this pull req. According to the below URL, it can't import a default export from CommonJS. 

https://github.com/Microsoft/TypeScript/issues/2719

It's better to use the TS -> ES6 -> Babel -> CommonJS.

**Comment by johnjelinek** [comment]
@Syati: I think this should prolly still be merged: https://github.com/gaearon/redux-thunk/issues/35.

**Comment by johnjelinek** [comment]
@Syati: your PR fixes both:
```
import * as thunkMiddleware from "redux-thunk";
import thunkMiddleware = require("redux-thunk");
```

**Comment by Syati** [comment]
@johnjelinek 

I think It's better to leave it. according to the following url.

https://github.com/Microsoft/TypeScript/issues/5565
> BTW, it appears that Babel is killing off the export default magic  in their next release

I transpiled 'redux-thunk' with babel6. The definition works below style.

```
import thunk from 'redux-thunk
```

it's bettter to send redux-thunk a PR that change babel5 to babel6


In reference, I attach the transpiled result

```
# transpiled with babel6 (6.1.2)
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = thunkMiddleware;
function thunkMiddleware(_ref) {
  var dispatch = _ref.dispatch;
  var getState = _ref.getState;

  return function (next) {
    return function (action) {
      return typeof action === 'function' ? action(dispatch, getState) : next(action);
    };
  };
}
```

**Comment by johnjelinek** [comment]
hrmm ... ok

**Pull request closed without merging**
