### PR TITLE
[node] Secure module names by default

### PR DESCRIPTION
**Pull request by turansky**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Node documentation](https://nodejs.org/api/esm.html#node-imports)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### Motivation
* Secure auto imports in IntelliJ IDEA ([issue](https://youtrack.jetbrains.com/issue/WEB-57067)) and VS Code
  * IDEs use parent module by default

### CODE REVIEW

**Comment by Semigradsky** [comment]
`node:` imports supported in versions >= `14.18.0` also

**Review by Semigradsky — APPROVED** [review]
Looks good

**Review by gabritto — APPROVED** [review]

**Comment by turansky** [comment]
Ready to merge

**Comment by jakebailey** [comment]
I think this PR broke some code I had which wrote:

```ts
export * from "inspector";
```

The linked https://github.com/timocov/dts-bundle-generator/issues/259 is familiar.

Switching to `node:inspector` fixed this but this seems weird.

**Comment by turansky** [comment]
`inspector` module reexport fixed in #66756

**Comment by jakebailey** [comment]
This problem isn't unique to `inspector`; this PR changed every module to instead declare `node:` and then reexport from it via `export =`. I'm pretty sure this will break anyone in the ecosystem who are reexporting things from the old names. Whether or not that's anyone except me, I'm not sure.

**Comment by turansky** [comment]
> This problem isn't unique to `inspector`

`inspector` - single module, which export behaviour was changed in this PR.

For other modules, which use `export = `, behaviour isn't changed.
For example for `path` and `process` modules star reexport did't worked before changes and doesn't work after.

**Comment by jakebailey** [comment]
I'm not really sure what you mean. The change to `inspector.d.ts` is the same as the one done in `assert.d.ts`, `constants.d.ts`, no? Or is there some other info I'm missing?

**Comment by turansky** [comment]
> Or is there some other info I'm missing?

In `assert.d.ts` we have `export = ` usage in main namespace.
It means, that star reexport isn't supported for `node:assert` too.

In `inspector` module `export = ` was used for legacy module support only and wasn't used in `node:inspector` module declaration.

Screenshot 2023-09-20 at 01 08 47

**Comment by gabritto** [comment]
I'm going to revert the PR for now, and maybe someone can open a new version of this PR that doesn't break re-exports.

**Comment by jakebailey** [comment]
I'm not sure anyone but me has actually noticed (and the linked issue); before we revert, I'm curious if @andrewbranch or @sandersn have any opinions.

To be clear, I'm not sure I'm correct, but the explanations offered up so far haven't really clarified things for me.

**Comment by gabritto** [comment]
Ok, I can revert the revert if it turns out this PR was correct or the break is desired or something, but since within a few days two different people noticed a problem, I figured it would be safer to revert while we figure things out. I'll wait for @andrewbranch to chime in. @turansky sorry about the confusion and thank you for your patience while we sort this out.

**Comment by turansky** [comment]
@gabritto, @jakebailey Sorry, can you say please for which modules reexport worked before and doesn't work with this PR?

`inspector` was affected - it's true and I provided fix in #66756.
Do we have more affected modules?

For following modules reexport doesn't work in any case:
* `assert`
* `console`
* `constants`
* `events`
* `module`
* `path`
* `process`
* `stream`

because they use `export = ` in main namespace.

**Comment by turansky** [comment]
> Which export syntax should be used, after all?

Ideal variant - avoid `export = ` usage.
In `cluster` default [export/reexport used](https://github.com/turansky/DefinitelyTyped/blob/018f3b4f5c3f7e926cc52b823001b4b1f35c923f/types/node/cluster.d.ts#L411). Looks like possible solution for `path` and `process` (checks required).

**Comment by jakebailey** [comment]
I'm like 90% sure that they should be `export =` if they are implemented as CJS under the hood, which I'm pretty sure most Node builtins are.

**Comment by turansky** [comment]
@gabritto Will you restore PR changes and apply #66756?
Or should I do new PR?

**Comment by gabritto** [comment]
I think, in order not to break anyone, you can re-do this PR, but making consistent the way the exports are made in the two versions of each module, for all modules affected.
e.g. both `declare module "inspector" { ... }` and `declare module "node:inspector" { ... }` should use the same way of exporting.
If `"node:inspector"` uses named exports, `"inspector"` should use a re-export like `export * from ...`.
If `"node:inspector"` uses `export =`, `"inspector"` should also use `export =`.

Does that make sense?
This inconsistency was already present and not caused by your PR, but your PR switching the two modules can make something that worked before not work anymore, and we want to avoid that.

**Comment by turansky** [comment]
PR is ready - ##66767

**Pull request merged**
