### PR TITLE
Add `signedStorageUrl` property to `VaporStoreOptions` interface in laravel-vapor

### PR DESCRIPTION
**Pull request by tbhaxor**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/laravel-vapor/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against caf117b8358830a9ebd177e6fe47bda202de4367
</p>

**Review by saibotk — APPROVED** [review]
Nice 👍

**Comment by tbhaxor** [comment]
Hi @saibotk when it will be merged?

**Comment by saibotk** [comment]
Just wait until someone from the maintainers approves, because you did not add a testcase

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by saibotk** [comment]
Ready to merge

**Pull request merged**
