### PR TITLE
Ionic update

### PR DESCRIPTION
**Pull request by kwiateusz**

### CODE REVIEW

**Comment by spencerwi** [comment]
Hi @kwiateusz! Thanks for the pull request.

There a couple of steps needed before I can approve this to be merged in:

1. Could you provide a link to the Ionic documentation to reference for this change?
2. I've noticed that the test you added did not pass. I recommend changing the parameter from `value: boolean` to `value?: boolean` to indicate that it's an optional parameter (based on the test you wrote)

**Comment by kwiateusz** [comment]
1. http://ionicframework.com/docs/api/provider/$ionicConfigProvider/
2. Can you help me with test? Parameter isn't optional I just base on other $ionicConfigProvider.views tests

**Comment by spencerwi** [comment]
Thanks for the link! I checked out the docs and it looks like it both accepts and returns a boolean -- which is how Ionic usually signals "this is a setter when given a value or a getter when called without params".

I searched through their codebase to find usages of it, and sure enough they use it both as a setter (e.g. `$ionicConfigProvider.views.swipeBackEnabled(false)` ) and as a getter (e.g. `if ($ionicConfigProvider.views.swipeBackEnabled()){` ) -- here's the link to what I found: https://github.com/driftyco/ionic/search?utf8=%E2%9C%93&q=swipeBackEnabled&type=Code

With that in mind, I think your test is right, but that the parameter just needs to be marked as optional.

**Comment by spencerwi** [comment]
Thanks for the link! 

Looking through their codebase, it looks like `$ionicConfigProvider` both accepts and returns a boolean -- which is how the Ionic codebase tends to signal "this is a setter when given a parameter and a getter when not given a parameter". That's how the other tests currently pass.

So I think your test is right, but the definition just needs the param marked as optional.

**Comment by kwiateusz** [comment]
Thanks for help. Now it pass :)

**Comment by spencerwi** [comment]
Great, thanks! And thanks for the PR! 

:+1:

**Pull request merged**
