### PR TITLE
[s3rver] Update the types to v3.7

### PR DESCRIPTION
**Pull request by trygveaa**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jamhall/s3rver
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by trygveaa** [comment]
The build error is apparently an error from npm, so it seems unrelated to the changes in this PR:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by peterblazejewicz** [comment]
@feuGeneA

**Comment by peterblazejewicz** [comment]
@feuGeneA 
@trygveaa mind adding yourself as the owner? The change looks decent, but would be nice to have someone responsive if there is a problem with the change.
I understand, we cannot pin the previous actual version of this package exactly before 3.7 update?

**Comment by trygveaa** [comment]
> @trygveaa mind adding yourself as the owner? The change looks decent, but would be nice to have someone responsive if there is a problem with the change.

@peterblazejewicz: Sure, done.

> I understand, we cannot pin the previous actual version of this package exactly before 3.7 update?

No, I don't know which version the types before my changes was for. Looking at the history, I'm not sure it matches any version exactly. Since they have `configureBuckets` in `S3rverOptions` it has to be at least version 3.0.0. However, the signature for `run(callback)` matches the behavior in 2.x, while the behavior in 3.0.0 matches what I've changed to as far as I can see. And I don't think the signature `run(): Promise<string>` has ever been correct.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
this is reasonable update, pinned with versioning and with new owner added
@trygveaa thx!

**Comment by trygveaa** [comment]
Ready to merge

**Pull request merged**
