### PR TITLE
update(jsts): Add write method to WKTWriter

### PR DESCRIPTION
**Pull request by SugyoIn-LBSTech**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by StephaneAlie — COMMENTED** [review]
👍

**Comment by SugyoIn-LBSTech** [comment]
@StephaneAlie If there's no problem, can you approve this PR?

**Review by StephaneAlie — APPROVED** [review]

**Comment by StephaneAlie** [comment]
Apologies for the delay, I meant to approve earlier, must have submitted a simple comment.

**Comment by SugyoIn-LBSTech** [comment]
Ready to merge

**Pull request merged**
