### PR TITLE
Cancelled

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by anubmat** [comment]
Please close the PR if you want to cancel

**Comment by vvakame** [comment]
*prismjs/index.d.ts*

to author (@eriklieben). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
sorry for late.
Why negative reaction raise?

**Comment by andy-ms** [comment]
Closing since that's apparently what you intend.

**Pull request closed without merging**
