### PR TITLE
[Esprima] Extended Program interface

### PR DESCRIPTION
**Pull request by Robinfr**
I've added the optional `tokens` property to the `Program` interface of
Esprima.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://esprima.readthedocs.io/en/4.0/syntactic-analysis.html#token-collection
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Robinfr** [comment]
Created new pull request in favour of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19604

**Review by RReverser — APPROVED** [review]

**Comment by RReverser** [comment]
Maybe also update tests to cover access to `.tokens`.

**Review by peter-scott — APPROVED** [review]

**Comment by Robinfr** [comment]
@RReverser I'd love to add tests, but I honestly have no clue how. The tests look weird to me coming from a regular testing environment such as Mocha and Jasmine. It's also not very well explained in the README.

If you could explain how to test access, I'll add it.

**Comment by peter-scott** [comment]
@RobinFr The test is just a typescript file that uses the definitions. If the test file can be compiled without error, then it is deemed a success. 

The test script is never run, it is only type-checked.

**Comment by Robinfr** [comment]
@peter-scott Yeah I realized that..

Would this be OK?

```typescript
// Parsing Options
const title = 'Hello World!';
program = esprima.parseScript(`var el= <title>${title}</title>`, { jsx: true });
program = esprima.parseScript('if (x) function y() {}');
program = esprima.parseScript('"use strict"; with (x) {}', { tolerant: true });
program = esprima.parseScript('answer = 42', { range: true });
program = esprima.parseScript('answer = 42', { range: true });
program = esprima.parseScript('const answer = 42', { tokens: true });
if (program.tokens) {
    token = program.tokens[0];
}
program = esprima.parseScript('answer = 42 // TODO: why', { comment: true });
program = esprima.parseScript('answer = 42 // TODO: why', { comment: true, range: true });
```

It's a bit crappy to put it in the middle of the parsing options, but I suppose that would be where it belongs..

**Comment by peter-scott** [comment]
@Robinfr Sure. It gets the job done.

**Comment by Robinfr** [comment]
@peter-scott added.

**Review by peter-scott — APPROVED** [review]

**Pull request merged**
