### PR TITLE
react-router MemoryRouter.initialEntries can be string[]

### PR DESCRIPTION
**Pull request by kryops**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present. *(errored)*

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reacttraining.com/react-router/web/api/MemoryRouter/initialEntries-array
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by kryops** [comment]
@sergey-buturlakin
@mrk21
@vasek17
@ngbrown
@awendland
@KostyaEsmukov
@johnnyreilly
@LKay
@DovydasNavickas
@tkrotoff

**Comment by tkrotoff** [comment]
@kryops 
would be nice to add an example so that there is no regression in the future
Also maybe you can use `History.LocationDescriptor`:
`LocationDescriptor = Path | LocationDescriptorObject` given that `Path` is a `string`.

**Comment by kryops** [comment]
@tkrotoff good catch! `History.LocationDescriptor` is better because it also allows partial location objects.

**Comment by mhegazy** [comment]
@tkrotoff any other comments?

**Comment by tkrotoff** [comment]
👍  Perfect!! thx a lot

**Comment by kryops** [comment]
Rebased and squashed to resolve conflicts 😄

**Comment by kryops** [comment]
@mhegazy @sandersn can this be merged then? :-)

**Comment by sandersn** [comment]
Yep, sorry it fell between the cracks. Thanks for your contribution!

**Pull request merged**
