### PR TITLE
[stellar-sdk & stellar-base] Misc improvements 4

### PR DESCRIPTION
**Pull request by Akuukis**
## Changing an existing definition ([Docs](https://stellar.github.io/js-stellar-sdk/), Source: [SDK](https://github.com/stellar/js-stellar-sdk) & [BASE](https://github.com/stellar/js-stellar-sdk))

Among other things mentioned below, this PR also standardizes the way how types are grouped together. That applies to: AssetType, AuthFlag, MemoType, Operation, OperationOptions, OperationType, Signer, SignerOptions. Now, all of them should feel similar to enums (the only real enum is `Networks`). Here's example for Operation:

```ts
import { Operation } from 'stellar-sdk'  // Or 'stellar-base', either works now.
let anyOp: Operation;
let paymentOp: Operation.Payment;
console.log(Operation.Payment)  // Error -> not a run-time value.
```

Changes:

- fix(operations): default to widest type
- fix: add default type argument everywhere
- refactor: plain responses in Horizon namespace
- feat: PriceR, Flags, Account{Signer,Thresholds}
- fix: TransactionRecord
- feat: parameterize Transaction
- feat: extract module `stellar-base`
- fix: change fake enums into type+namespace
- feat: TransactionOperation -> Operation
- refactor: simplify SignerUnion
- feat: don't export utility types
- fix: Memo.text can be either string or Buffer

Breaking Changes:

- several `Server.*` -> `Horizon.*`
- There's two distinct `Server.*Record` & `Horizon.*Response`, choose wisely
- `ASSET_TYPE` -> `AssetType`
- `Memo*` -> `MemoType.*`
- `Memo.AnyType` -> `MemoType`
- `Memo.AnyValue` -> `MemoValue`
- `Operation.AuthFlags` -> `AuthFlag`
- `Operation.*Options` -> `OperationOptions.*`
- `TransactionOperation` -> `Operation`
- `Operation.Signer*Options` -> `SignerOptions.*`
- `Operation.Signer*` -> `Signer.*`
- `Operation.SignerOptions` -> `SignerOptions`
- `Operation.Signer` -> `Signer`
- `Operation.SignerUnion` is obsolete now

### Work to be done

This is a continued work since #31857. Here are the outstanding problems what I have noticed so far:

- feat: copy over comments from source for intellisense
- feat: separate *Record from plain responses [PARTLY DONE]
    For example, server.submitTransaction() returns plain response instead of enhanced `*Record`s returned by `*CallBuilder`s and thus currently is typed wrong. Furthermore, all `*Record`s are just extending plain responses, and thus obviously separating them would make that clear. Also, it would allow to use plain responses, e.g. for a quick `fetch` call. So far only operations and transaction is migrated.
- feat: introduce AccountId, PublicKey and Secret as types
    That's because at some places is confusing whenever you need an address of existing account, random publicKey or just a string. Comments and intellisense may help a lot:
    ```
    /**
     * 56-character long string, starts with S and passes StrKey.isValidEd25519SecretSeed().
     */
    export type Secret = string;

    /**
     * 56-character long string, starts with G and passes StrKey.isValidEd25519PublicKey().
     * Do not confuse with AccountId.
     */
    export type PublicKey = string;
    /**
     * Like PublicKey, but also points to existing account on the given Network.
     */
    export type AccountId = string;
    ```

### CODE REVIEW

**Comment by Akuukis** [comment]
Ping @Carl-Foster @TristonJ @pselden @maxbause @charlie-wasp - please review this PR. Bot picked up that there's new definition for `stellar-base`, but didn't ping you to review the changes at `stellar-sdk`, which essentially was split in two.

**Comment by Akuukis** [comment]
Looks like this PR is under the radar because it doesn't show up at "Pull Request Triage Backlog". Maintainers - @sheetalkamat, @sandersn -, please take a look.

**Review by TristonJ — APPROVED** [review]
This is awesome, you have done quite a bit of refactoring! From what I can tell, it aligns with the stellar docs.

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
