### PR TITLE
[@types/jsrsasign] JWS.sign password can be an object

### LINKED ISSUE #49266: jsrsasign token signing password param can be an object
According to the method docs for `jsrsasign.jws.JWS.sign()` and `jsrsasign.crypto.Mac.setPassword()`, the `pass` argument to both methods can be an object denoting string type (e.g. utf8, rstr, hex). However, the type declaration says it can only be a string. This is a problem because passing an even-length string with 0..9 and A..z characters causes the passward to be treated as a hexidecimal.

- [x] I tried using the `@types/jsrsasign` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ffflorian

### PR DESCRIPTION
**Pull request by znewton**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.sign
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

fixes #49266

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 14 other properties...</summary>
<p>MessageDigest, Mac, Cipher, ASN1HEX, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, crypto, asn1, jws, lang</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 06b32db83b2ba0f90a86a6b5be83de87d7180788
</p>

**Review by ffflorian — APPROVED** [review]
Thanks!

**Comment by znewton** [comment]
@ffflorian do you think I should add more tests or is this fine as is?

**Comment by ffflorian** [comment]
> @ffflorian do you think I should add more tests or is this fine as is?

Yes please add a simple test :)

**Review by ffflorian — APPROVED** [review]

**Comment by znewton** [comment]
Ready to merge

**Pull request merged**
