### PR TITLE
redux-pack: Fix lint

### PR DESCRIPTION
**Pull request by ghost**
Removes unnecessary type parameters.

### CODE REVIEW

**Comment by tansongyang** [comment]
Hi @andy-ms. Would you please describe what problems this fixes? Also, do any tests need to be updated?

**Comment by andy-ms** [comment]
@tansongyang This shouldn't affect the behavior so long as explicit type arguments aren't supplied. We have a lint rule that looks for extra type parameters that shouldn't be necessary.
Basically, if you have a function like this:
```ts
declare function f<T>(arg: T): void;
```
You are saying that for any `T`, you can pass an instance of `T` to `f`. That's basically saying that `f` can accept anything. So you might as well just write:
```ts
declare function f(arg: any): void;
```

**Review by tansongyang — CHANGES_REQUESTED** [review]
I tried this locally, and it appears to break some tests. Does that happen for you as well?

**Comment by andy-ms** [comment]
It works fine for me, what errors are you seeing?

**Comment by tansongyang** [comment]
Well, this is strange. I had some errors earlier when I tried on one machine. I didn't record them at the time, so I thought I would try again on my home machine. After getting latest, I can't even successfully run `tsc` in the `redux-pack` directory because I get this error:

> error TS5023: Unknown compiler option 'strictFunctionTypes'.

Tomorrow, I will record the other errors.

**Comment by andy-ms** [comment]
For `strictFunctionTypes` you need to update to `typescript@next`.

**Review by tansongyang — APPROVED** [review]
Upgrading to typescript@next made all errors go away.

**Pull request merged**
