### PR TITLE
[Bluebird] Fix reduce initialValue type

### PR DESCRIPTION
**Pull request by xndu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/petkaantonov/bluebird/blame/master/src/reduce.js#L16

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bluebird ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bluebird@latest/))
was missing the following properties:
1. TypeError
1. RangeError
1. RejectionError
1. fulfilled
1. rejected

<details>
<summary>as well as these 1 other properties...</summary>
<p>pending</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f320d6876f42e8b5f6adc29f76097b4a8a903bb3
</p>

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
From what i understand the function doesnt expect initial value to be resolvable but converts the value to it so I am not sure this is right change.

**Comment by lhecker** [comment]
@sheetalkamat `Resolvable` is defined as:
```ts
type Resolvable<R> = R | PromiseLike<R>;
```

I believe the change is correct because it allows the user to infer the correct type `U` (= it unwraps the promise type). I haven't been using TypeScript for a bit though so maybe I'm misunderstanding it.

**Comment by xndu** [comment]
> From what i understand the function doesnt expect initial value to be resolvable but converts the value to it so I am not sure this is right change.

`Promise.resolve` converts a `Resolvable<U>` into a `Bluebird<U>`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts#L737

**Review by jakebailey — APPROVED** [review]
> > From what i understand the function doesnt expect initial value to be resolvable but converts the value to it so I am not sure this is right change.
> 
> `Promise.resolve` converts a `Resolvable<U>` into a `Bluebird<U>`. [`master`/types/bluebird/index.d.ts#L737](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts?rgh-link-date=2023-09-23T22%3A03%3A27Z#L737)

It doesn't turn it into `Bluebird<U>`, it turns `Resolvable<U>` into `Promise<U>`. Of course, that's fine:

image

So this function could accept a `Promise`, and given the definition of `Resolvable` above, this PR seems correct to me.

**Comment by xndu** [comment]
> > > From what i understand the function doesnt expect initial value to be resolvable but converts the value to it so I am not sure this is right change.
> > 
> > 
> > `Promise.resolve` converts a `Resolvable<U>` into a `Bluebird<U>`. [`master`/types/bluebird/index.d.ts#L737](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts?rgh-link-date=2023-09-23T22%3A03%3A27Z#L737)
> 
> It doesn't turn it into `Bluebird<U>`, it turns `Resolvable<U>` into `Promise<U>`. Of course, that's fine:
> 
> image
> 
> So this function could accept a `Promise`, and given the definition of `Resolvable` above, this PR seems correct to me.

`Promise` in the source here is Bluebird's `Promise`, not the native `Promise`.

**Comment by xndu** [comment]
Ready to merge

**Pull request merged**
