### PR TITLE
react-router: enable jsx-a11y/anchor-has-content

### PR DESCRIPTION
**Pull request by anthonyjoeseph**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url](https://github.com/ReactTraining/react-router/pull/7435)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-router-hash-link ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-router-hash-link@latest/))
was missing the following properties:
1. genericHashLink
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1d50c5903be569bfa89c4d00b4f501c77b64122c
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
From my experience this isn't viable to enforce statically. It's usually a nuisance because some passed `children` is wider than it should be. Considering this is a popular package and has existing tooling (statically and dynamically) I'd not do this at this point.

**Comment by anthonyjoeseph** [comment]
I'm not sure I understand. What do you mean that "some passed children is wider than it should be"? Do you think `React.ReactChild | React.ReactChild[]` is the wrong type?

You mentioned static vs dynamic enforcement: I have updated made an [appropriate companion PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45630/files) that updates `prop-types` as well.

I think this PR is important because it would help many developers make their code more accessible

**Comment by anthonyjoeseph** [comment]
@eps1lon I just looked up your impressive credentials, and I realized that I am probably on the wrong side of this argument. I am still curious, however: why isn't this 'viable to enforce statically'? Because it's a 'nuisance'? Shouldn't it be a nuisance?

**Comment by eps1lon** [comment]
> What do you mean that "some passed children is wider than it should be"? 

The interface might be typed as `children?: ReactNode;` but practically it never receives `undefined` children. So throughout the codebase you're passing along `children` and they are never `undefined`. Now you enforce it at a type level and you have to look at every call site and have to verify it is actual defined.

This would definitely improve the soundness but did you actually achieve something? Paired with the fact that you can trick the type checker with `<NavLink> </NavLink>` or `<NavLink children="" />` or pass an empty array I don't see this helping many people. 

If `react-router` would warn at runtime via propTypes then we'd have a different conversation i.e. if their `children` are typed as `children: PropTypes.node.isRequired`.

**Comment by anthonyjoeseph** [comment]
My [companion PR](https://github.com/ReactTraining/react-router/pull/7435) does exactly what you describe with `PropTypes`. However, it has been closed (which I am protesting) (it would be helpful to have backup)

`<NavLink>` has the same restrictions as `<Link>` b/c `NavLinkProps` extends `LinkProps`. Good point about the empty array, I've just updated the type to prevent that.

**Comment by anthonyjoeseph** [comment]
A non-empty string is impossible to statically enforce w/o a [smart constructor](https://stackoverflow.com/questions/56006111/is-it-possible-to-define-a-non-empty-array-type-in-typescript) but I believe this is in the spirit of [jsx-a11y/anchor-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-has-content.md), which is also suppressed by the empty string

**Comment by anthonyjoeseph** [comment]
apologies for the broken commits, I haven't been able to figure out how to run `npm test` without pushing my changes first

**Comment by anthonyjoeseph** [comment]
Apologies for all of the extra CI builds & notifications, I was running into typescript version issues.

So to enforce NonEmptyArray in TS, turns out you need at least version 3.2 ([this solution](https://stackoverflow.com/questions/56006111/is-it-possible-to-define-a-non-empty-array-type-in-typescript) causes [this error](https://github.com/microsoft/TypeScript/issues/28810) in older versions). This required some bumping typescript on:
- `react-router-guard`
- `react-router-native`
- `react-router-navigation-core`
- `react-router-navigation`
- `react-router-redux`
- `redux-auth-wrapper`
- `rrc`
- `storybook-react-router`
- `mirrorx`.

Obviously this is not ideal, but I think this is the best way to accurately represent the intended behavior of `react-router-dom`'s `LinkProps`

**Comment by anthonyjoeseph** [comment]
closing in light of @timdorr 's comment [here](https://github.com/ReactTraining/react-router/pull/7435#issuecomment-647626702)

**Pull request closed without merging**
