### PR TITLE
Update Knockout.js definitions to 3.4.0

### PR DESCRIPTION
**Pull request by lediur**
Made a diff between 3.2.0 and 3.4.0 and tried to include and cover all the changes in between that haven't already been made by previous contributors.

### CODE REVIEW

**Comment by Igorbek** [comment]
It doesn't pass tests. Could please fix them?
Looks like it conflicts with `knockout.deferred.updates` where `tasks` was defined.
So if you removed `tasks` by intention, please refer doc and fix tests accordingly.

**Comment by Igorbek** [comment]
One more thing - PR has a lot of whitespace replacements which is not useful at all. Please remove all tab/spaces replacements as was defined originally to avoid history pollution.

**Comment by lediur** [comment]
Sorry for the whitespace fixup, I'll go revert that.

Do you have any tips on how to handle the `knockout-deferred-updates` issue? Deferred updates were introduced into Knockout itself in 3.4.0, which basically obsoletes `knockout-deferred-updates` (even says so on the repo https://github.com/mbest/knockout-deferred-updates).

**Comment by Igorbek** [comment]
@lediur just make tests working with ko's tasks instead of ko-deferred-updates. Probably it would be better to move tests to ko itself (as you did partially).

**Comment by Igorbek** [comment]
delete this line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/knockout.deferred.updates/knockout.deferred.updates-tests.ts#L204

**Comment by lediur** [comment]
Let me fix up whitespacing, for some reason reverting and squashing my changes still preserved the whitespace

**Pull request closed without merging**
