### PR TITLE
[loadsh] Add ReadonlyArray back, require TS >= 2.5

### LINKED ISSUE #23766: lodash: Add ReadonlyArray back and update to TS 2.5
In #23710 , we removed `ReadonlyArray` types because they don't work well in typescript pre-2.5 (apparently they result in an infinite loop). 

Now that lodash is fixed for the 2.2-2.4 people, I think we should add `ReadonlyArray` support back, and bump the typescript version up to 2.5.

It's a trade-off (support `ReadonlyArray` vs. support old versions of typescript), but I think supporting `ReadonlyArray` is the better option here, because people with old versions of typescript have a workaround: `npm install @types/lodash@ts2.4`. People who use `ReadonlyArray` currently have no good workaround - they'll need to add type assertions to their readonly arrays to make lodash accept them.

Thoughts @mhegazy ?

### PR DESCRIPTION
**Pull request by aj-r**
Fixes #23766 - see explanation there. @andy-ms @mhegazy 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [ ] Increase the version number in the header if appropriate. N/A
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
@aj-r Please fix the failures indicated in the Travis CI log.

**Comment by aj-r** [comment]
Ah, I see the problem - there are a few packages (`bookshelf`, `sequelize`, and `yog2-kernel`) that depend on `lodash`, and their typescript version is 2.3. So if we want to update to 2.5, they would need to do so as well.

How do the authors of those packages (@arcticwaters, @vesse, @samuelneff, @CodeAnimal , @drinchev , @babolivier , @kukoo1 , @oktapodia , @MorpheusXAUT @TitaneBoy , @zjy01 , @nidzov , @Raigen , @todd , @Torhal , @ssddi456 ) feel about bumping the typescript version up to 2.5? Background: `lodash` wants to update to 2.5 so we can add `ReadonlyArray` support.

If anyone doesn't want to upgrade (i.e. keep typescript version at 2.3 instead of 2.5), then I'll close this PR.

**Comment by todd** [comment]
Fundamentally, I don't have a problem with upgrading TypeScript for Sequelize, but version bumps always make me a bit nervous about what'll break for other people. I'm a bit new to the upgrade and release process for declaration files - how can we make sure this is going to be as painless for downstream consumers as possible?

**Comment by thorn0** [comment]
It probably has been answered, but can't we simply bump the major version for all those `@types/*` packages?

**Comment by aj-r** [comment]
@todd Bumping to version 2.5 just means you don't officially support versions lower than that. Anyone using typescript 2.4 (for example) should technically install `@types/sequelize@ts2.4`, which will install the latest version before you bumped to 2.5. Basically, it means they won't get any updates you your type definitions unless they also upgrade their typescript version.

I guess my only concern is that people might not realize that `@types/lodash` is a dependency of `@types/sequelize`. So by default, npm will automatically install `@types/lodash@latest`, no matter what version you specified for `@types/sequelize`. You can work around this by manually installing `@types/lodash@ts2.4`, but people might not know to do that, since it's a difficult thing to diagnose.

**Comment by thorn0** [comment]
My thinking was that the mess could probably be avoided if the types publisher had a more sophisticated approach to `dependencies` in `package.json` than it has now.

An example from https://unpkg.com/@types/sequelize@4.27.7/package.json :
```
 "dependencies": {
        "@types/lodash": "*",
        "@types/bluebird": "*",
        "@types/continuation-local-storage": "*",
        "@types/validator": "*"
    },
```

But I feel like it has been already discussed somewhere and is the way it is for some good reasons. Most probably, I guess, to prevent installing more than one different version of the same `@types` package.

**Comment by aj-r** [comment]
Another option is to remove the dependency on `@types/lodash`. However this looks likely to remove some functionality (at least for some packages).

**Comment by thorn0** [comment]
I mean `@types/sequelize@ts2.4` could have
```
 "dependencies": {
        "@types/lodash": "ts2.4",
        ...
  }
```
in its `package.json`. Does it make sense? What could go wrong if it gets done this way?

**Comment by aj-r** [comment]
I've done some more investigation, and it looks like we don't actually need TS 2.5 to get `ReadonlyArray` support. The error is not caused by an infinite loop, it is caused by the process running out of memory. I made a few optimizations to `lodash-tests`, and they pass (at least on my local machine) with TS 2.2 and `ReadonlyArray` enabled. The only downside it that `npm run lint lodash` seems to take about 30 minutes to run. I'll see if I can make any more optimizations to improve that.

Closing this PR - I'll make a new one using the new TS 2.2 approach.

**Comment by aj-r** [comment]
Update: I tried resolving the memory issues in TS 2.2-2.4, but then the tests actually fail. Looks like there were bugs with `ReadonlyArray` in 2.2-2.4 that are show-stoppers as far as lodash is concerned. So the only solution is upgrading to TS 2.5.

**Pull request closed without merging**
