### PR TITLE
Fix: behavior3js, export add

### PR DESCRIPTION
**Pull request by f-wrobel**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [N/A] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [N/A] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [N/A] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [N/A] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I want to add "export" since it is a npm package.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
I think this module looks like UMD module, export 'b3' on global scope.
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library

So most probably one would expect to flatten this module by removing namespace, like:
```diff
--- a/types/behavior3/index.d.ts
+++ b/types/behavior3/index.d.ts
@@ -84,833 +84,831 @@
  * CONDITION           | 'condition'
  *
  */
-declare namespace b3 {
```
exporting symbols directly, like:
```diff
-     *     class Inverter extends b3.Decorator {
+/**
+ * This export function is used to create unique IDs for trees and nodes.
+ *
+ * (consult http://www.ietf.org/rfc/rfc4122.txt).
+ *
+ */
+export function createUUID(): string;
+
+/**
```
and adding export as namespace declaration:
```diff
-export { b3 };
+export const VERSION: string;
+export const SUCCESS: number;
+export const FAILURE: number;
+export const RUNNING: number;
+export const ERROR: number;
+export const COMPOSITE: string;
+export const DECORATOR: string;
+export const ACTION: string;
+export const CONDITION: string;
+
+export as namespace b3;
````

**Review by weswigham — CHANGES_REQUESTED** [review]
Definitely what @peterblazejewicz said - this probably needs a UMD module declaration, rather than a swap like this.

**Comment by f-wrobel** [comment]
Actually, I found it easier to use a typescript port of this library:
https://github.com/asfisher/behavior3ts
than to modify this _types_. I think this PR is no longer relevant in that case.

**Comment by peterblazejewicz** [comment]
> I think this PR is no longer relevant in that case.

closing as per OP comment

**Pull request closed without merging**
