### PR TITLE
[vscode] Feat: Activate + Deactivate functions types

### PR DESCRIPTION
**Pull request by Malix-Labs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [-] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.

## Docs

- [**VSCode Extension Documentation - Extension Entry File**](https://code.visualstudio.com/api/get-started/extension-anatomy#extension-entry-file)

### CODE REVIEW

**Review by osbyrne — APPROVED** [review]

**Comment by weswigham** [comment]
cc @kieferrm - up to you if you're interested in this; I don't know how well changes like this mesh wish the extension API update process though. @Malix-off, you may be better off making changes over at [the vscode repo itself](https://github.com/microsoft/vscode/tree/df8db3a75a49b85c9636530a3557cdbc639f7bdc/src/vscode-dts) instead - extension API changes are usually synced to here periodically.

**Comment by Malix-off** [comment]
@weswigham
> @Malix-off, you may be better off making changes over at [the vscode repo itself](https://github.com/microsoft/vscode/tree/df8db3a75a49b85c9636530a3557cdbc639f7bdc/src/vscode-dts) instead

I'm confused because [the issue I just created from your advice](https://github.com/microsoft/vscode/issues/201694#issuecomment-1874753182) was denied because "we do not accept PR from DefinitelyTyped", did I do something in the wrong direction?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Needs approval by @kieferrm  to see if this is ok

**Comment by Malix-off** [comment]
> Needs approval by @kieferrm to see if this is ok

🆙

**Pull request closed without merging**
