### PR TITLE
[google-apps-script] Marked all fields for response types as optional

### PR DESCRIPTION
**Pull request by marekdedic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/drive/api/guides/fields-parameter, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71186#issuecomment-2561895144
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by jpoehnelt** [comment]
This doesn't seem correct. Please share more on the source for this change.

**Comment by marekdedic** [comment]
@jpoehnelt Thanks for the quick response

In Drive API, any API responding with some resource can specify the `fields` parameter to return a partial response (see https://developers.google.com/drive/api/guides/fields-parameter,). I've simply gone through all methods of this type (basically all that have `optionalArgs`) and marked as optional all types they return (and subtypes...)

**Review by jpoehnelt — APPROVED** [review]

**Comment by jpoehnelt** [comment]
consider updating the title of the pull request

**Comment by marekdedic** [comment]
@jpoehnelt Thanks, reworded the title. Sorry to re-request a review, I added a test...

**Review by jpoehnelt — APPROVED** [review]

**Comment by jpoehnelt** [comment]
Ready to merge

**Pull request merged**
