### PR TITLE
fix(node-hid): The HID class derives from the EventEmitter

### PR DESCRIPTION
**Pull request by ert78gb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-hid/node-hid/blob/67fa185f43ef52e33943b427f71d52cd556dce42/nodehid.js#L33
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by minestarks** [comment]
I'm holding off on merging this for now. I reached out for some guidance on how to handle the perf regression typescript-bot flagged.

**Comment by thegecko** [comment]
> I'm holding off on merging this for now

OK, the change looks fine to me, let me know if I should approve.

**Comment by ert78gb** [comment]
@minestarks can you share the guidance?

**Comment by minestarks** [comment]
@ert78gb I will as soon as I get some 🙂.

**Comment by minestarks** [comment]
OK, I have a clearer sense of what's going on. Essentially the typings went from being tiny to being massive thanks to the new reference to the `node` typings. But we decided the impact to the end user is basically zero, since this is `node-hid` and it's almost certain the end user is already referencing `node` typings. For a library that isn't *exclusively* for node.js, this new dependency might have been a red flag. But it's not, here. So we're all good to go. Thanks for your patience :)

**Pull request merged**
