### PR TITLE
[lodash] Adds a variant of lodash.d.ts that does not populate the global scope.

### PR DESCRIPTION
**Pull request by Andael**
- Adds lodash-module.d.ts which does not declare the _ global variable or namespace.
- For backwards compatibility, changes lodash.d.ts to wrap around lodash-module.d.ts which exposes _ as a namespace import and a global variable.

This addresses #4046

### CODE REVIEW

**Comment by myitcv** [comment]
@chrootsu has pointed out that #6112 is very similar. 

Just adding a note here to capture that I think we should prefer #6112 because:

* we can see the diff of changes being made
* It includes tests, following the [React](https://github.com/borisyankov/DefinitelyTyped/tree/master/react) model

**Comment by ander-nz** [comment]
@myitcv I agree, I prefer #6112's syntax. I only did it the way I did to preserve the existing behavior for people already using `tsd install lodash`.

**Comment by myitcv** [comment]
@ander-nz - yes, I should have acknowledged in my PR that the behaviour of `tsd install lodash` would change. But I think it's the right change, i.e. that the React pattern is correct. That way, the default install is 'safe' for everyone:

* for users of ES6 modules, they get compile time errors when they don't import the module
* for non-ES6 module users, they get a compile time error when installing the default and have to `tsd install lodash/lodash-global` to fix the problem

The friction experienced in the second point could easily be eased by creating a `README.md` in the [`lodash` directory](https://github.com/borisyankov/DefinitelyTyped/tree/master/lodash)

Just a note about your PR when using the `-module` type definition; it only exports the `_` variable, not the namespace. Hence the following fails to compile:

```typescript
/// <reference path="typings/lodash/lodash-module.d.ts" />

import * as _ from "lodash";

console.log(_.isUndefined(5));

let x: _.MapCache;
```

with

```
error TS2503: Cannot find namespace '_'
```

Unless I'm missing something?

This is why I [followed this approach](https://github.com/myitcv/DefinitelyTyped/blob/lodash_global_fix/lodash/lodash.d.ts#L8825) in my PR, where [`__Lodash` is declared as a variable and a module](https://github.com/myitcv/DefinitelyTyped/blob/lodash_global_fix/lodash/lodash.d.ts#L6-L8)

**Comment by ander-nz** [comment]
Closed in favor of #6112

**Pull request closed without merging**
