### PR TITLE
@types/node: Add url.domainToASCII, url.domainToUnicode

### PR DESCRIPTION
**Pull request by ikokostya**
**General**

Add definitions for:
  * [`url.domainToASCII`](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_domaintoascii_domain) (available since v7.4.0)
  * [`url.domainToUnicode`](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_domaintounicode_domain) (available since v7.6.0)

to Node.js 7, 8, 9.

***

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  * [`url.domainToASCII`](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_domaintoascii_domain) (available since v7.4.0)
  * [`url.domainToUnicode`](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_domaintounicode_domain) (available since v7.6.0)
- [x] ~~Increase the version number in the header if appropriate~~ (not needed)
- [x] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`~~. (not needed)

### CODE REVIEW

**Comment by ikokostya** [comment]
Looks like errors on Travis CI are unrelated to my changes.

**Review by Flarna — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
@sandersn this does indeed look like an unrelated Travis failure - can you investigate?

**Comment by sandersn** [comment]
Yes, it's unrelated. I reproed it on master after deleting package-lock.json and node_modules/. I'll figure out the fix and then come back here and merge from master to see whether Travis will now pass.

**Comment by sandersn** [comment]
OK, I merged from master with the react-flatpickr fix. Travis is now running.

**Comment by jdxcode** [comment]
I believe this change resulted in the `latest` tag changing to `7.0.58` which caused some failures for us. Is that expected? Shouldn't `latest` always point to a 9.x release right now?

**Comment by sandersn** [comment]
Certainly looks that way to me. @andy-ms any idea what's going on?

**Pull request merged**
