### PR TITLE
normalize line ending (CRLF -> LF)

### PR DESCRIPTION
**Pull request by vvakame**
#7879 #8061

### CODE REVIEW

**Comment by horiuchi** [comment]
LGTM :+1:

**Comment by vvakame** [comment]
wow... I'm using nkf but it cant handling UTF8 well...

**Comment by vvakame** [comment]
`find . -type f | grep "\.ts" | xargs -n 1 perl -pi -e 's/\r\n/\n/g' -- $@`

**Comment by vvakame** [comment]
@DefinitelyTyped/contributors I'll merge this PR tomorrow morning. (01:26 a.m. JST now)

**Comment by basarat** [comment]
🌹😊

**Pull request merged**
