### PR TITLE
[@types/react-native] Change type of DrawerLayoutAndroidProps.drawerPosition to 'left' | 'right'

### LINKED ISSUE #35852: Property 'positions' does not exist on type 'typeof DrawerLayoutAndroid'
If you know how to fix the issue, make a pull request instead.

- [*] I tried using the `@types/react-native` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [*] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @Skn0tt @timwangdev @kamal @swissmanu 

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by CometstarMH**
DrawerLayoutAndroid drawerPosition has been changed a year ago. Fixes #35852.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react-native/commit/305b0a28142414d559d2d08795a5963716dc4b0f>>
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by ca057 — COMMENTED** [review]
Can we add some tests for this? Otherwise it looks good to me!

**Comment by alloy** [comment]
No some other change was made recently, perhaps in DT’s infrastructure (@orta?), which introduced that issue. Nonetheless, I believe you should be able to create the test and ignore the TS version message. It doesn’t matter much that there’s no previous test, just write a snippet that uses the API as you would normally use it.

**Comment by CometstarMH** [comment]
Test added.

**Comment by alloy** [comment]
Great, thanks!

**Pull request merged**
