### PR TITLE
chrome: Add queue-interface for cast

### PR DESCRIPTION
**Pull request by tolu**
Changes
- Rename chrome-cast.ts to chrome-cast.d.ts
- Add interfaces for new Queue-functionality
- Fix failing syntax tests

### CODE REVIEW

**Comment by vvakame** [comment]
@eXeDK could you review this PR?

**Comment by eXeDK** [comment]
Sure, I'll take a look at it @vvakame

**Comment by eXeDK** [comment]
I think most of it is good, however I see some missing documentation strings for stuff like  `RepeatMode` and `QueueItem`. 

Besides those small needed additions I think the `*MediaMetadata` interfaces are no longer reflecting the fact that some of the properties are marked as deprecated as they were before and still are in the documentation like `releaseYear`: https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.MovieMediaMetadata

**Comment by tolu** [comment]
@eXeDK that's an easy fix. I realize now I didn't really see the use of `// Deprecated` as it does not (at least in VSCode) show up in the intellisense and so missed the logic on the order of params below your comment, which was why I swapped it for `/** Deprecated /` syntax.

**Comment by eXeDK** [comment]
I agreee @tolu, I'm not an TypeScript expert so maybe you know of a documentation practice which is correct and will be caught by Intellisense for deprecated properties?

**Comment by tolu** [comment]
@eXeDK neither am I :) I just noticed that `/** comments */` are picked up by OmniSharp while `// comments` are not. Either way I'll make sure to add deprecated where it should be.
A thing I'd like to know though is what a bang signifies in comments like these:
```
* @param {!Array<chrome.cast.media.QueueItem>} items
```
Non nullable?

I also noticed your use of the following Array[dot]-syntax.
Is this a stray dot or should it be that way?
```
* @const {!Array.<number>}
```

**Comment by eXeDK** [comment]
Fair enough :) 

Yes I'm pretty sure that is non-nullable, I'm unable to find it in the documentation though: http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf

Regarding the dot, I'm think that's a stray dot

**Comment by tolu** [comment]
@eXeDK thanks! I'll push some fixes then ;)

**Comment by eXeDK** [comment]
Perfect :) Thanks for the work!

**Comment by vvakame** [comment]
@eXeDK thanks!
@tolu thanks mate!

**Pull request merged**
