### PR TITLE
[atom] Make the types modular following the original file structure

### PR DESCRIPTION
**Pull request by aminya**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aminya** [comment]
@typescript-bot I want to add prettier.config.js to the project, but the CI errors for the added gitignore. Is there anything else I need to do?

**Comment by aminya** [comment]
@lierdakil I am making the code modular. However, some of the types in `index.dt.ts` are not related to Atom's code itself such as event-kit and text-buffer. Should I make top-level folders for their types like how we do for Linter and Toolbar? or I should make a folder calling it something like dependencies and put their types there? What do you think?

**Comment by peterblazejewicz** [comment]
> I want to add prettier.config.js to the project, but the CI errors for the added gitignore. Is there anything else I need to do?

Nope, the MS maintainers stresssed that either pick DT global one or (effectively) nothing. Some of the DT packages are formatted with TABS, not spaces. There is no way to compose Prettier configuration then, sry!
We could raise this again on Typescript tooling github project though:
https://github.com/microsoft/DefinitelyTyped-tools
You can start with require pragma, to gradually migrate your files:
https://prettier.io/docs/en/options.html

I can see the reason why there is only a single DT prettier config (same for Linter).

**Comment by orta** [comment]
Yeah, we don't want to complicate the overall repo with many different formatting setups throughout. I get that people have totally reasonable style opinions - but when it's a repo with +20k modules, having too much variety is a bit of a pain to maintain

**Comment by aminya** [comment]
> > I want to add prettier.config.js to the project, but the CI errors for the added gitignore. Is there anything else I need to do?
> 
> Nope, the MS maintainers stresssed that either pick DT global one or (effectively) nothing. Some of the DT packages are formatted with TABS, not spaces. There is no way to compose Prettier configuration then, sry!
> We could raise this again on Typescript tooling github project though:
> [microsoft/DefinitelyTyped-tools](https://github.com/microsoft/DefinitelyTyped-tools)
> You can start with require pragma, to gradually migrate your files:
> [prettier.io/docs/en/options.html](https://prettier.io/docs/en/options.html)
> 
> I can see the reason why there is only a single DT prettier config (same for Linter).

OK, That's understandable. I will run prettier with the DT config in a separate PR

**Comment by aminya** [comment]
> Hey @aminya,
> 
> 😒 Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module. This can potentially save days of time for you.

The tests already apply here. There is no need to add or update the tests.

**Comment by aminya** [comment]
> OK, That's understandable. I will run prettier with the DT config in a separate PR

I decided to run prettier in this PR to speed up the process. Because the DT maintainers' review process takes a while, I decide to do everything in this PR.

**Comment by peterblazejewicz** [comment]
@aminya it looks like being ready?
I undestand, you're the best person to decide what ends in the DT package, compared to original `atom/atom` sources? (that is, DT exposes some content to be consumed by users, not everything from package itself).
Am I correct?

**Comment by lierdakil** [comment]
@aminya as far as I understand this PR doesn't change the user-facing behaviour, only changes how the code is organized. Am I correct? Are you still iterating, or is it ready?

**Comment by aminya** [comment]
> @aminya it looks like being ready?
> I undestand, you're the best person to decide what ends in the DT package, compared to original `atom/atom` sources? (that is, DT exposes some content to be consumed by users, not everything from package itself).
> Am I correct?

Yes, this is ready to go! 

This PR makes it easier to follow the types of `atom/atom`, and makes it easier for me to improve the content.

**Comment by aminya** [comment]
> as far as I understand this PR doesn't change the user-facing behaviour, only changes how the code is organized. Am I correct? Are you still iterating, or is it ready?

No, this doesn't change anything user-facing. The tests are kept untouched to show backward compatibility.

**Review by lierdakil — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by aminya** [comment]
@elibarzilay the bot removed the review approvals! Could you merge this PR?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Review by lierdakil — APPROVED** [review]

**Comment by aminya** [comment]
Ready to merge

**Comment by lierdakil** [comment]
And... nothing. Let's try this one more time.

**Comment by lierdakil** [comment]
Ready to merge

**Pull request merged**
