### PR TITLE
Bull 3.3.5 update

### PR DESCRIPTION
**Pull request by weeco**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OptimalBits/bull/tree/master/lib
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by manast — COMMENTED** [review]
LGTM

**Comment by RyanCavanaugh** [comment]
@weeco Please fix the failures indicated in the Travis CI log.

**Comment by weeco** [comment]
@RyanCavanaugh Most issues are not caused by my commit, however I am willed to fix these. I am aware that the `object` keyword has been introduced with Typescript 2.2 and hence there is an issue. Can you let me know what I should use instead?

e. g.: 

```
    /**
     * Update a specific job's data. Promise resolves when the job has been updated.
     */
    update(data: object): Promise<void>;
```

**Comment by marshall007** [comment]
@weeco I would just disable the unified-signatures tslint rule for `process()` like I had done [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21277/files#diff-f92bb2dbabb4a196b0c99adc6bc4d2d1R18).

Aside from that LGTM.

**Pull request merged**
