### PR TITLE
added meow from Sindre Sorhus

### PR DESCRIPTION
**Pull request by ghost**
case 1. Add a new type definition.
- [X ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ X] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by yuit** [comment]
@crazyhuggins could you fix travis failure?

**Comment by minestarks** [comment]
Please refer to the [contribution guide](http://definitelytyped.org/guides/contributing.html) and add an appropriate header.

**Comment by paulvanbrenk** [comment]
@crazyhuggins gentle ping

**Comment by RyanCavanaugh** [comment]
Closing due to lack of response. Please open a new PR if you'd like to continue with this change. Thanks!

**Pull request closed without merging**
