### PR TITLE
[three] release 126

### PR DESCRIPTION
**Pull request by joshuaellis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by joshuaellis** [comment]
> Config files to check: three/OTHER_FILES.txt: not the expected form and not moving towards it

I'd really love to discuss with someone if there's a way to overcome this, the amount of files we have to deal with is *probably* far greater than any other library I've seen & this continues to hold us up in making releases with any kind of ease, resulting in PRs taking more than 3/4 days to be merged by which point we're already a quarter of the way there to making a new release and doing the whole process over again 🙃 

I'm completely open to any ideas to solve this DT maintainers 🙏🏼

**Comment by Methuselah96** [comment]
@joshuaellis There's still a few commits not crossed off on https://github.com/three-types/three-ts-types/issues/2. Do we want to get those resolved before merging this commit?

**Comment by joshuaellis** [comment]
> @joshuaellis There's still a few commits not crossed off on [three-types/three-ts-types#2](https://github.com/three-types/three-ts-types/issues/2). Do we want to get those resolved before merging this commit?

Oops, which ones did I miss? 😱

**Review by Methuselah96 — APPROVED** [review]

**Review by Methuselah96 — APPROVED** [review]

**Comment by orta** [comment]
Re: discussions on how to speed up your process - I'd recommend writing issues on https://github.com/DefinitelyTyped/dt-mergebot

We're open to ideas, we're just always careful to make sure it doesn't affect the whole ecosystem

**Review by orta — APPROVED** [review]

**Comment by joshuaellis** [comment]
@orta totally understandable and i'm understanding this type set might be a bit of an outlier.

**Comment by joshuaellis** [comment]
Ready to merge

**Pull request merged**
