### PR TITLE
feat(node): v16.7

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/releases/tag/v16.7.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Also minor improvements to the document generation:
- Buffer statics now generated
- Events statics now generated
- No more `<Type>`, now just `Type` (will make them `{@link ...}` later.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
I saw this `<T extends X | Y>` dilemma last time, but Ive missed the problem behind,

LGTM!

**Comment by SimonSchick** [comment]
@peterblazejewicz I didn't change it, prettier did, and I sure hope it knows that it's doing.

**Comment by SimonSchick** [comment]
Lint fixes only.

**Comment by SimonSchick** [comment]
@peterblazejewicz can you give this another approval?

**Review by peterblazejewicz — APPROVED** [review]

**Comment by SimonSchick** [comment]
Ready to merge

**Pull request merged**
