### PR TITLE
feat(bootstrap-fileinput): add missing instance methods

### LINKED ISSUE #43288: [@types/bootstrap-fileinput] Types for fileinput methods are missing
I am not good at typescript. I've tried to add them my self but i failed. Can you add typings for fileinput methods.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- missing methods added
- tests added to package
- TS details updated to match current DT recommendations
- formatting with DT prettier settings

https://plugins.krajee.com/file-input/plugin-methods

/cc @aliemre1990

Thanks!

Fixes: #43288

View with white-space diff removed:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files?diff=unified&w=1

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://plugins.krajee.com/file-input/plugin-methods
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by orta** [comment]
@peterblazejewicz Thank you for submitting this PR! 


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43312,
  "author": "peterblazejewicz",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "18af29b",
  "headCommitOid": "18af29b3ab5af43d22742aa23a9f366eb0174e17",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-22T11:30:23.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": false,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "bootstrap-fileinput"
  ],
  "files": [
    {
      "filePath": "types/bootstrap-fileinput/bootstrap-fileinput-tests.ts",
      "kind": "test",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/index.d.ts",
      "kind": "definition",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tsconfig.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tslint.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@peterblazejewicz Thank you for submitting this PR! 


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43312,
  "author": "peterblazejewicz",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "18af29b",
  "headCommitOid": "18af29b3ab5af43d22742aa23a9f366eb0174e17",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-22T11:30:23.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": false,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "bootstrap-fileinput"
  ],
  "files": [
    {
      "filePath": "types/bootstrap-fileinput/bootstrap-fileinput-tests.ts",
      "kind": "test",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/index.d.ts",
      "kind": "definition",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tsconfig.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tslint.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@peterblazejewicz Thank you for submitting this PR! 


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43312,
  "author": "peterblazejewicz",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "18af29b",
  "headCommitOid": "18af29b3ab5af43d22742aa23a9f366eb0174e17",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-22T11:30:23.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": false,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "bootstrap-fileinput"
  ],
  "files": [
    {
      "filePath": "types/bootstrap-fileinput/bootstrap-fileinput-tests.ts",
      "kind": "test",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/index.d.ts",
      "kind": "definition",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tsconfig.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tslint.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "unknown",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@peterblazejewicz Thank you for submitting this PR! 


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43312,
  "author": "peterblazejewicz",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "18af29b",
  "headCommitOid": "18af29b3ab5af43d22742aa23a9f366eb0174e17",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-22T11:30:23.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": false,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "bootstrap-fileinput"
  ],
  "files": [
    {
      "filePath": "types/bootstrap-fileinput/bootstrap-fileinput-tests.ts",
      "kind": "test",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/index.d.ts",
      "kind": "definition",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tsconfig.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tslint.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "fail",
  "travisUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18af29b3ab5af43d22742aa23a9f366eb0174e17/checks?check_suite_id=538453428",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@peterblazejewicz Thank you for submitting this PR! 


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43312,
  "author": "peterblazejewicz",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "18af29b",
  "headCommitOid": "18af29b3ab5af43d22742aa23a9f366eb0174e17",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-22T11:30:23.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43312/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": false,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "bootstrap-fileinput"
  ],
  "files": [
    {
      "filePath": "types/bootstrap-fileinput/bootstrap-fileinput-tests.ts",
      "kind": "test",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/index.d.ts",
      "kind": "definition",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tsconfig.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    },
    {
      "filePath": "types/bootstrap-fileinput/tslint.json",
      "kind": "package-meta",
      "package": "bootstrap-fileinput"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "fail",
  "travisUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18af29b3ab5af43d22742aa23a9f366eb0174e17/checks?check_suite_id=538453428",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@peterblazejewicz The Travis CI build failed! Please [review the logs for more information](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18af29b3ab5af43d22742aa23a9f366eb0174e17/checks?check_suite_id=538453428).

Once you've pushed the fixes, the build will automatically re-run. Thanks!

**Comment by orta** [comment]
@peterblazejewicz The Travis CI build failed! Please [review the logs for more information](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18af29b3ab5af43d22742aa23a9f366eb0174e17/checks?check_suite_id=538453428).

Once you've pushed the fixes, the build will automatically re-run. Thanks!

**Comment by peterblazejewicz** [comment]
It yelds error in jQuery itself, interesting. TBI

**Pull request merged**
