### PR TITLE
MySql: Pool `end` method takes optional err object

### PR DESCRIPTION
**Pull request by MadsBogeskov**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mysqljs/mysql/blob/283425b44bc7a310bf6613d0e112d89080516e55/lib/Pool.js#L165

The callback method on Pool.end takes an optional error object. Since this is marked as non-optional in the existing @types its very difficult to know that the pool isn't ended before the callback has been called.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mysql ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mysql@latest/))
was missing the following properties:
1. createQuery
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a54c91d7b88638451f5713b243312a13375c9c31
</p>

**Review by wjohnsto — CHANGES_REQUESTED** [review]
This looks good, I believe the best practice for optional arguments is to use `?`. Something like the following:

```
end(callback?: (err?: MysqlError) => void): void;
end(options: any, callback: (err?: MysqlError) => void): void;
```

Correct?

**Comment by MadsBogeskov** [comment]
> This looks good, I believe the best practice for optional arguments is to use `?`. Something like the following:
> 
> ```
> end(callback?: (err?: MysqlError) => void): void;
> end(options: any, callback: (err?: MysqlError) => void): void;
> ```
> 
> Correct?

I don't know if there would be any difference for the end-developer (as in 'I don't know' :) ), however I think that your suggestion is valid. I changed it. So happy to see this come in! 🤩

**Review by wjohnsto — APPROVED** [review]
Awesome!

**Comment by amcasey** [comment]
The difference between `f: Foo | undefined` and `f?: Foo` isn't so much a best practice as an expression of intention.  With the former, the caller has to specify a value, but that value can be `undefined`; with the latter, the caller can omit the argument entirely.

**Review by amcasey — CHANGES_REQUESTED** [review]
This is a common source of confusion.  Please confirm that it's intentional: https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#optional-parameters-in-callbacks

**Comment by wjohnsto** [comment]
That is a good point @amcasey, and looking at the [source](https://github.com/mysqljs/mysql/blob/283425b44bc7a310bf6613d0e112d89080516e55/lib/Pool.js#L186) (since the callback is only called internally) it appears that it's possible the callback will be called without a value.

**Review by amcasey — APPROVED** [review]
@wjohnsto Thanks for confirming!

**Pull request merged**
