### PR TITLE
[node]: Fix test runner HookFn method signature

### PR DESCRIPTION
**Pull request by sangaman**
This fixes an incorrect method signature on the `HookFn` type used by hooks such as `before` and `after`. Per the Node documentation, and based on my experience and observations using the Test Runner, the callback function is the second argument to the hook function. See https://nodejs.org/api/test.html#beforefn-options.

The first argument is not documented but it appears to be a `SuiteContext` object like the first argument passed to `describe`.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

NOTE: I could not run `npm test node` - it gives me this error:

```
dtslint@0.0.168
testing from 4.4 to 4.8 in /Users/dmcnally/github/DefinitelyTyped/types/node/ts4.8
Error: Cannot find module '/Users/dmcnally/.dts/typescript-installs/4.4/node_modules/typescript'
```

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/test.html#beforefn-options
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Semigradsky** [comment]
Please make changes also for Typescript <= 4.8 version (`types/node/ts4.8`) and for Node.js v18 (`types/node/v18` and `types/node/v18/ts3.8`)

**Comment by sangaman** [comment]
> Please make changes also for Typescript <= 4.8 version (`types/node/ts4.8`) and for Node.js v18 (`types/node/v18` and `types/node/v18/ts3.8`)

Done. When doing this, I realized that v18 doesn't have `SuiteContext` defined (although it's documented in v18 and unchanged since then https://nodejs.org/docs/latest-v18.x/api/test.html#describename-options-fn). So I added SuiteContext where it was missing, and updated the `SuiteFn` used by `Describe` to correctly use `SuiteContext` instead of a callback (describe doesn't use callbacks) in a separate commit.

**Review by Semigradsky — APPROVED** [review]
👍

**Review by peterblazejewicz — APPROVED** [review]
@sangaman thanks!

**Comment by sangaman** [comment]
Ready to merge

**Pull request merged**
