### PR TITLE
knuddels-userapp-backend-api - deprecated KnuddelAccount and KnuddelPot

### PR DESCRIPTION
**Pull request by SirezKN**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by SirezKN — COMMENTED** [review]
Looks fine to me

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/knuddels-userapp-backend-api/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6871828c08b1e79c0e565ba59d29958661abbe23
</p>

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/knuddels-userapp-backend-api/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5222a5a88572f71ced12d02b9515236506ffa6e1
</p>

**Comment by SirezKN** [comment]
> ## Formatting
> The following files are not formatted:
> 
> 1. types/knuddels-userapp-backend-api/index.d.ts
> 
> Consider running `pnpm dprint fmt` on these files to make review easier.
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [5222a5a](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5222a5a88572f71ced12d02b9515236506ffa6e1)

the command doesn't change the format

**Comment by jakebailey** [comment]
That's a lot of formatting changes; I'm not sure how we can validate this when there's so much noise and without any documentation.

**Comment by sandersn** [comment]
I would be OK with taking this change if somebody from Knuddels would be able to review it. @SirezKN, your branch came from the Knuddels fork. Are you affiliated with them?

**Review by sheetalkamat — DISMISSED** [review]
Need original author/organization approval

**Comment by SirezKN** [comment]
> I would be OK with taking this change if somebody from Knuddels would be able to review it. @SirezKN, your branch came from the Knuddels fork. Are you affiliated with them?

Hi,

I apologize for the delayed response. As you can see in my profile, I am part of the Knuddels organization. Could you please approve the changes?

Thank you.

**Comment by jakebailey** [comment]
Maybe your membership is hidden?

image

**Comment by SirezKN** [comment]
> Maybe your membership is hidden?
> 
> image

Thank you for the hint. It should show up now.

**Comment by SirezKN** [comment]
> Need original author/organization approval

I as a part of the organization Knuddels, approve the changes.

**Comment by jakebailey** [comment]
I definitely don't see anything on your profile that indicates anything to do with this org

**Comment by SirezKN** [comment]
image
You can't see this?

**Review by jakebailey — APPROVED** [review]
I'll approve this, but @Knuddels is the package owner and should really be approving this (as in, click the button), or you all should be added as specific owners.

**Comment by Knuddels** [comment]
Ready to merge

**Pull request merged**
