### PR TITLE
Update knex version to bring in line with bookshelf 0.15.1 (#36567 resubmit)

### PR DESCRIPTION
**Pull request by jwhitmarsh**
Bookshelf has a specific dependency on knex, so rather than @types/bookshelf having a direct dependency on knex use bookshelf instead so that the knex versions align. 

This PR depends on https://github.com/microsoft/types-publisher/pull/629 being merged (adding bookshelf to dependenciesWhitelist.txt)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bookshelf/bookshelf/pull/1982
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jwhitmarsh** [comment]
Can a maintainer help me understand why the tests are failing? types-publisher has been updated to include bookshelf, but it looks like the travis test hasn't got the latest - is that correct?

**Comment by bvenchak** [comment]
@jwhitmarsh , looks like without your changes it's impossible to compile the newest version of Bookshelf with TypeScript. Did you find another solution, while waiting for your PR to be reviewed?

**Comment by jwhitmarsh** [comment]
Yeah @bvenchak, I uninstalled @types/bookshelf copied the typings directly into my project. Then it knows to use the right version of knex.

**Comment by jwhitmarsh** [comment]
@arcticwaters @vesse Please can you have a look at this?

**Comment by jwhitmarsh** [comment]
@alloy apologies if you're the wrong person to ask about this but I think you're the only maintainer I've managed to find responding to PRs - would you be able to check this for me? It looks like the test is failing because CI is using an old/cached? version of `types-publisher`.

**Comment by alloy** [comment]
Hmm, not sure where you’re seeing the cache related issue? I see this in the Travis log https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/557715806#L489, which seems to indicate you need to allow for external deps if they provide types you depend on (I have no experience with this myself).

**Pull request closed without merging**
