### PR TITLE
Fix base64 did not find

### PR DESCRIPTION
**Pull request by carlosscheffer**
md5.base64 is not working because it is not in the interface

### CODE REVIEW

**Comment by andy-ms** [comment]
Could you add some tests? And fix the lint errors (`npm run lint js-md5`)

**Comment by RyanCavanaugh** [comment]
@carlosscheffer Please fix the failures indicated in the Travis CI log.

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by andy-ms** [comment]
This PR now has no changes, closing.

**Pull request closed without merging**
