### PR TITLE
[ramda] Add more typeguards

### PR DESCRIPTION
**Pull request by essenmitsosse**
Adding typeguard support to more functions (either being used as a type guard or accepting one)

Tried to separate each change into an individual commit, so feel free to review this PR per commit.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. collectBy
1. modify
1. modifyPath
1. partialObject
1. on

<details>
<summary>as well as these 5 other properties...</summary>
<p>promap, sequence, splitWhenever, unwind, whereAny</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 565fb46ebb441988f8fb2df84a3c9d2e6261efc6
</p>

**Comment by adispring** [comment]
I write [a test for `R.cond` in Playground](https://www.typescriptlang.org/play?&dtPR=59797&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcimRABNlCBuAKBrgbgGMIA7VeZOAXkwDoWrMgAoA2vUaTRw5AC44HKMFYBzOAB84rAK4gARgFMoGuHogQANgeSsAlPK7B0O-UZ4A+ODCjaDAGhQPQKQAJgBdPwlJBmk5BW9lNU0zS2s7BzgneKVVIO9fAK5uT2Q+K1UYAAsIqOiAejq4AFlkAGsDBW0oDogANyMLCGQydBBkGCZKgIN+1jgAd0qDOextViYYYDYUKBVdZfgsvTxhtyrluAMADzADDYMyWqkZeRSrGxMXQ2NNL6NRML2QJHczvObFLw+fyBCEyOAAfjgAEY4PIAAy2GrRRixBysACetjyUICwiJEMIlWAhCxjEBtFqgg4ph4KGESNstCAA), TSC throws a type error, can you look at what's wrong in the test?

**Comment by adispring** [comment]
This test also failed: https://www.typescriptlang.org/play?&dtPR=59797&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcimRABNlCBuAKBrgbgGMIA7VeZOAXkwDoWrMgAoA2vUaTRw5AC44HKMFYBzOAB84rAK4gARgFMoASjjyuwdDv1GeAPjgwo2gwBoU9j0gBMAXVcSkgzScgpOyiqm3A5OLu4y8ooRUQ6EABbAhP6BcL7GtDmCHHB6PCjCAIz5NEA

**Comment by somebody1234** [comment]
Nice catch - for the first one, it seems like one way to fix it is to separate all the return types into `R1`, `R2` etc, and then returning `(value: T) => R1 | R2 | etc`

For the second one one way to fix that specific instance is to make the last argument a `CondPairMaybeTypeguard`:
```typescript
export type CondPairMaybeTypeguard<T, TFiltered extends T, R> = [(value: T) => value is TFiltered, (value: TFiltered) => R] | [(value: T) => boolean, (value: T) => R];
```
but I don't think it's ideal since you probably want it to work in any position. Unfortunately I'm not quite sure how to solve it.
Changing every parameter to `CondPairMaybeTypeguard` would probably (almost) work but there are two issues:
- The `(value: TFiltered) => R` function doesn't seem to infer at all, since it could be `(value: TFiltered) => R` or `(value: T) => R`
- `TFiltered` is inferred as `T`, meaning `Exclude<T, TF>` would be `never` which is wrong - it should be inferred as `never` when it's not a type predicate

So I'm not sure whether we can support overloads where not every function is a type predicate

Worth noting that it can be worked around by turning the function into a type guard that returns `a is T`:
```typescript
const b = R.cond([
    [(a: string | number) : a is number => true, a => a * 2],
    [(a: string): a is string => true, a => 'hi'],
]);
```

**Comment by essenmitsosse** [comment]
Good catch. Yeah `cond` is a bit problematic. I removed it from this PR and will break it out into its own PR, and take a closer look at it.

**Comment by essenmitsosse** [comment]
@somebody1234 @adispring is there anything about the other types you noticed?

**Comment by somebody1234** [comment]
i haven't tested it yet... i guess i should do that now.

just started and... [uh oh...](https://www.typescriptlang.org/play?&dtPR=59797&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIimRABNlCBuAKBrIFMBjAG2SgZwFcA7JmYBB5xgqAMoAKAB4AuOLwDWPCAHceASjlSR6VDCjAeAc1qNW7Ttl79Bw0QDlpcxcrWa420XB5cQAIwYoU2Y2Dm4+ASEdMUdZeR4lVQ0tHTg9A2M4AB9vXwCg+hCLcJso7Cd4xLc5PwgIFgZkHloaJiE9FDgAXkwAOgZgGAALQIlRMQAaHXt1WgB6ObgluAA9AH4aIA)

**Comment by somebody1234** [comment]
still not sure whether that generic version of `is(Array)` is a good idea btw (see the review above)

**Comment by essenmitsosse** [comment]
@somebody1234 what review about `is(Array)` do you refer to? Can't see any other comment.

**Comment by somebody1234** [comment]
sorry, my bad... was wondering what was up with the pending

**Comment by essenmitsosse** [comment]
@somebody1234 @adispring could you have a final look. There are no outstanding comments but also no approval.

**Comment by somebody1234** [comment]
i think [this review](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59797/commits/c2a226fbd2f789468cb8830167439538b2158307#r850594952) still applies? i guess i could go take a quick look right now though

**Comment by somebody1234** [comment]
... actually i think `val: any` is a mistake since then `<T>` is unused, i think?

**Comment by somebody1234** [comment]
[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcAeAFQD4AKTHGALngEEYYoBPAYT0IxmRpgAaeADcoEBlFRsAlAzEQCheKQDaAXQDcAKFCRYCFOmx4lAJjJUBDZq07de-DLWEKGpOaPFL4AUQAevFCYZMJoANaoOADuqBrkOnrQcEhomLj4RADM1M70TCzsXKg8fAKu4gwRUbGeCj7VMXFa2toQIBjwUACEDKVYqADm8AA+8KjIALYARiAwGjrtndO941OzMKNrM3MLbR3wYKsTO-PqWycbGntL8MCr-UMaF+u7LbcgD7wDg88AZPAAN5IHA4BgAcmmsHBmngAF8Xqd4ADgVCAF4QgCOyGQ-hh8J02gA9ET4LMABZQEQgZQQLDhBBZMngKDIQgIAAGpA5PnE0XYyg5jViHIAdNosIh4JQiJRbOxhFAZMiAbL5WxhNNlX9VYQ5YUNYdtbr9XZhMBjUpTQr4CAZMrAdp4M6ujoSc6AHoAfidLumbtJ8G9vudYADnp9Lru4aDkZdIBjwbhxNJRDM8AAVBBQeFCBn4HSGQROoRyThkBBgPBBlhqV1mRgMHN4HBCBWMCmychOohaPAMOSEJMcDx4AAHWCdbLwdkgSa0+kILCdaK0XNIAYgcXuyZYQbk5YIVcwAf9mnYIbwHAD5sYNhjmnwCVSmWEMzWw1KlXmD+ay1p38jW-AD1XNf830Au0HRDV1O1jGD-Tg4MozDJC42dYBE3Q20sO0ZNJWlbJAK-HUlByUCyXA8iDWEMAqMAi1gMIaizVte0gRgqBcKjRD3XglDuJdTC0JghMRLhIA) (with just `is`)

**Review by Nicholaiii — CHANGES_REQUESTED** [review]
Adding typeguards is a worthy cause, but removing test cases means more than adding, these changes are potentially breaking, I suggest keeping the removed cases and adding the variant ones you replaced them with as well.

**Pull request closed without merging**
