### PR TITLE
fix(@types/color): fix circular ref to T

### PR DESCRIPTION
**Pull request by taktakpeops**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41612

### CODE REVIEW

**Review by beeequeue — CHANGES_REQUESTED** [review]
Are you sure you're on the latest version of TypeScript?

It supports circular type defs since 3.7

**Comment by taktakpeops** [comment]
Hi,

It works with 3.7.

However, for 3.6 and lower it doesn’t.

Since 3.0.1 was a minor, I assume it shouldn’t be a breaking change for the version lower than 3.7. 

That’s why the pull-request.

**Comment by BeeeQueue** [comment]
IMO it's better to keep the types package's major and minor versions aligned with the package it belongs to, but if other maintainers agree we should fix it

The update doesn't add any missing types or anything either way, so you can wait with updating the package until you've updated you TS version.

**Comment by taktakpeops** [comment]
Ok, I understand your point of view.

However, can we rely on semver for the typings? 

It seems to me that we mirror the published version of the modules using the typings more than applying the logic behind semver

**Comment by jameswlane** [comment]
I agree with @BeeeQueue that: 

> it's better to keep the types package's major and minor versions aligned with the package it belongs to

**Comment by BeeeQueue** [comment]
See also my comments in #41612

**Pull request closed without merging**
