### PR TITLE
Fix base props of react-bootstrap components (refs are useful!)

### PR DESCRIPTION
**Pull request by mikemagnusw**

### CODE REVIEW

**Comment by mikemagnusw** [comment]
I have another wad of changes that add a lot of missing types/properties, marks others as deprecated, etc. targeting react-bootstrap v0.29.4 released 2016-05-10.

This is not an exhaustive effort. There may well be cases where the typings reflect much, much older react-bootstrap.

I haven't added tests (at least yet) as it's taken most of my working day to just get the typings (more) up to date.

Ideally the entire file should be comprehensively verified with the actual react-bootstrap codebase but this is not something i have the time/agency to do right now.

**Comment by vvakame** [comment]
Sorry I'm not using react. We can't get response from authors. I'll merge this PR in 2 days. please ping me again.

**Comment by mhegazy** [comment]
No response from other authors for over two weeks. merging.

**Comment by vsiao** [comment]
@mikemagnusw: the `React.Props<T>` interface is deprecated. I specifically removed them from these typings. Why did you add them back?

**Comment by mikemagnusw** [comment]
@vsiao I'm afraid i no longer recall the details but even if the interface has been deprecated, i'm sure it was not marked in the referred react typings, was still quite available and surely could have been replaced with *something* to provide typings for refs. I certainly recall after updating the typings that tsc was making hundreds of complaints in a codebase about extraneous props. Turning this off in the tsconfig.json is not an option as it hides errors that would indicate mismatched code.

It is my contention that these components - like any React components - can have a ref provided in props. This ref is strongly-typed by the type of component class as it should be. Not to define this prop at all is simply an error.

**Comment by vsiao** [comment]
[deprecation notice](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L397-L400). refs are still accepted by [`createElement`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L112) and in [`JSX`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L112) via [`ClassAttributes<T>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L21-L23), but specifically not accessible via `this.props.ref` in a component because React removes the property from the props object.

**Comment by mikemagnusw** [comment]
That i had not realised at the time. That notice is not very discoverable unless combing through the immense wall of react typings. I was more concerned with the shower of compile-time errors with the codebase we had against react-bootstrap typings. You may have removed the deprecated `React.Props<T>`  but you didn't replace it with the use of `ClassAttributes<T>` having the outcome that any instance of attempting to provide a ref to a component was causing a TyepScript erorr.

There was no need to access the ref prop from inside any components. They were react-bootstrap components.

**Comment by vsiao** [comment]
> you didn't replace it with the use of `ClassAttributes<T>` having the outcome that any instance of attempting to provide a ref to a component was causing a TyepScript erorr.

Actually, yes I did. As mentioned in my previous comment, [`createElement`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L112) and in [`JSX`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L2358) both accept refs.

**Pull request merged**
