### PR TITLE
winston: add missing transport properties

### PR DESCRIPTION
**Pull request by FredKSchott**
Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/winstonjs/winston/tree/de69bccf957cca2247ef529c2b66c88059adbae6/lib/winston/transports
- [X] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
@FredKSchott Please merge from the latest `types-2.0` to fix tests.

**Comment by FredKSchott** [comment]
@andy-ms done! 
@bonnici @codeanimal please take a look and +1/-1

**Comment by sandersn** [comment]
@FredKSchott sorry we dropped this one. It looks good enough to merge.

**Comment by FredKSchott** [comment]
Thanks @sandersn!

**Pull request merged**
