### PR TITLE
braintree-web: Add missing ApplePay.merchantIdentifier and ApplePayPaymentRequest.lineItems properties and supporting interface and types

### PR DESCRIPTION
**Pull request by nstuyvesant**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree-web ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree-web@latest/))
was missing the following properties:
1. masterpass
1. paymentRequest
1. visaCheckout
1. preferredPaymentMethods
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7ec8f7233444fe4d25d6a7e9aac486f5e2eb300e
</p>

**Comment by nstuyvesant** [comment]
Added exports for several interfaces and types that were already there but not exported for some reason.

**Comment by nstuyvesant** [comment]
This is my first time contributing to this project. Seems this one is stuck. Should I just close this and abandon it?

**Comment by nstuyvesant** [comment]
It's been 28 days since I submitted this. Closing this PR as there's clearly no interest. I solved this for myself locally. So much for trying to give back to the community.

**Comment by nstuyvesant** [comment]
@jbuckner - can you please review this? I will try reopening it but was discouraged it was never checked which is why I closed it.

**Pull request merged**
