### PR TITLE
Add new failedDependency method for hapijs/boom 7.2.0

### PR DESCRIPTION
**Pull request by danielmachado**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/boom#boomfaileddependencymessage-data
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Hey @danielmachado can you potentially fix the incorrect constructor exports of boom?

I know this is feature creep but since you've already created this PR you might be able to squeeze it in.
There is already a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22996/files but it's stale.

If not I will try to get this done myself today.

**Comment by danielmachado** [comment]
Sorry for the late update, I've been out the last couple days. I'm a newbie in TS but i can give it a try 😸

**Comment by danielmachado** [comment]
Fixes -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22996

**Review by SimonSchick — APPROVED** [review]
👌 👌 👌 👌 👌

**Comment by danielmachado** [comment]
Any update on this? Why is this PR stale? i really appreciate any feedback.

**Comment by jineshshah36** [comment]
I’m pretty sure all PRs (once approved) are merged and released at specific intervals automatically. So in a few days it should automatically be released

**Pull request merged**
