### PR TITLE
Update azdata for TS 4.7

### PR DESCRIPTION
**Pull request by weswigham**
Removes an unused type parameter.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@weswigham How is this "unused"? The generic defines the type of the property object - this helps ensure that the object passed in is actually the type expected.

```
type MyType = {
   prop1: string
}
...
obj.withProperties<MyType>({ prop1: 'hello', prop2: 'world' }); // This would show an error
```

We could create and type the object earlier, but it's convenient to do it inline.

**Comment by weswigham** [comment]
Hmmmmm, well, the issue is that it spoils relational comparisons - by having a generic parameter, anything _assigned to it_, also _has to be generic_. Usage in the test indicates a concrete type is meant to be used, not a generic method. Prior to TS 4.7 we'd fail to catch this if the thing being assigned to it only had optional properties, but now we consistently report the error.

**Comment by weswigham** [comment]
The usage I'm talking about is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7b4793a42ff52587151e91ffbbf239474c3dea54/types/azdata/azdata-tests.ts#L26) - in TS 4.7 strict mode, this usage is an error unless the signature changes in some way.

**Comment by Charles-Gagnon** [comment]
What about 

`withProperties<TPropertyBag>(properties: TPropertyBag): ComponentBuilder<TComponent, TPropertyBag>;`

full definition : 

```
	export interface ComponentBuilder<TComponent extends Component, TPropertyBag extends ComponentProperties> {
		component(): TComponent;
		/**
		 * @deprecated Use withProps instead
		 */
		withProperties<TPropertyBag>(properties: TPropertyBag): ComponentBuilder<TComponent, TPropertyBag>;
		/**
		 * Sets the initial set of properties for the component being created
		 * @param properties The properties to apply to the component
		 */
		withProps(properties: TPropertyBag): ComponentBuilder<TComponent, TPropertyBag>;
		withValidation(validation: (component: TComponent) => boolean | Thenable<boolean>): ComponentBuilder<TComponent, TPropertyBag>;
	}
```

I don't know why it was done like this initially, but it should be using the type from the interface definition anyways.

**Comment by weswigham** [comment]
That would just shadow the outer `TPropertyBag` with a local variable of the same name, not reuse it. Moreover, the method would still be generic, which wouldn't fix the issue at hand - anyone trying to make an instance of the object would need to supply a generic method.

**Comment by Charles-Gagnon** [comment]
Right, it'd be 

`withProperties(properties: TPropertyBag): ComponentBuilder<TComponent, TPropertyBag>;`

instead I suppose

**Comment by weswigham** [comment]
Yep! I was thinking that's what it maybe was supposed to be, given that's how the `withProps` method below it is written, but what I have retained the permissiveness of the current signature.

**Comment by Charles-Gagnon** [comment]
Ok cool. This does cause some other issues though, and so for the time being let's get this in to unblock vs code and I'll follow up with trying to make this better.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Why did this just now break with the VS Code update though is a question I'd like to know, it seems like because we depend on them then it ran our tests when they updated their stuff (even though we were technically broken before, nothing caused our tests to be ran so it was never caught). Is that correct?

**Comment by Tyriar** [comment]
@Charles-Gagnon this actually fixed the VS Code one.

**Comment by Charles-Gagnon** [comment]
Yeah, I'm more just trying to figure out why our typings (which haven't been changed recently) blocked your stuff. Definitely want to avoid that in the future if we can...

**Comment by Charles-Gagnon** [comment]
When I run the tests (`npm run test-all`) locally it passes just fine. Do I need to do something special to have it run against TS 4.7?

**Comment by Tyriar** [comment]
@Charles-Gagnon azdata was failing before this was merged, I need to get that branch rebased now but don't have permissions to the repo.

The problem is TS nightly introduced a change that broke `azdata`, and any changes to `vscode` ends up running all dependent packages which includes `azdata`.

**Comment by Charles-Gagnon** [comment]
Yeah ok, that's what I figured.

What's the process for these kind of breaks in the future? @weswigham - was this something that you were keeping an eye on (and subsequently opened up the PR for fixing)? Just wondering if there's a way we could get notified when there's failures immediately so we can fix it ourselves instead of relying on other people to watch this for us.

**Comment by weswigham** [comment]
> What's the process for these kind of breaks in the future?

DT policy is broadly that when a package gets updated, you update its ecosystem of dependent packages, if need be, too, regardless of the underlying reason. It's one of the ways we try to keep quality high and packages continuously building. Naturally, you can get around that by contacting a DT maintainer if need be - every repo admin has the ability to merge PRs with failing statuses if absolutely needed; it's just bad form to leave a dependent in a failing state.

> was this something that you were keeping an eye on (and subsequently opened up the PR for fixing)?

Haha, I was completely unaware of the vscode thing - no - I was just trawling the nightly DT run for failures and fixing up the ones I could (a bunch of DT is currently blocked on mongo and knex, which are off-DT, which have similar errors, there's only a handful of others). AFAIK, we have no way for individual package authors on DT to know if a nightly TS build has broken them till someone comes by with a change to said package (or a dependency of it) and tries to update it. (Which works fast enough most of the time - in this case, you'd maybe have gotten notice a day or two earlier if we had some kind of notification system set up? Maybe?)

**Comment by weswigham** [comment]
> When I run the tests (npm run test-all) locally it passes just fine. Do I need to do something special to have it run against TS 4.7?

Oh, also, just a small fyi `npm run test-all` by default only runs packages changed in the most recent commit (misleading name, I know). To *actually* test all, you need to pass `-- --selection all`. Which, ah, can take awhile. On a single CI machine it's about 6 hours using 2 cores. It should test against the nightly (and every other DT-supported TS version) by default. Testing an individual package is kinda-easily done by cd'ing into it and running `npx dtslint`, though that skips some stuff like running `npm install` in that package and its dependencies if needed, which you'd have to do by hand.

**Comment by Charles-Gagnon** [comment]
Sounds good, I appreciate the info! Hopefully shouldn't happen often enough to worry about much at least, and we'll generally be pretty responsive if there are issues in the future.

Thanks for all the help here!

**Pull request merged**
