### PR TITLE
[node] definitions for crypto.constants

### PR DESCRIPTION
**Pull request by Touffy**
The `constants` property was missing entirely from the definitions for the node `crypto` module, so TypeScript kept complaining when any constant was used.

This PR adds the actual constants and comments copied from the Node.js docs.

https://nodejs.org/dist/latest/docs/api/crypto.html#crypto_crypto_constants

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
fyi, the list isn't complete, the documentation is missing a few such as `TLS1_2_VERSION`.
I'm good with adding this as is tho

**Review by Flarna — APPROVED** [review]
A test would be nice. Not needed to test all constants just one or two to ensure they are exported at the right place.

**Comment by Flarna** [comment]
CI fail is unrelated to the change. Should be fixed via #32710.

**Review by BrunoScheufler — APPROVED** [review]

**Comment by Touffy** [comment]
> A test would be nice. Not needed to test all constants just one or two to ensure they are exported at the right place.

I'm not sure where to test it. There are tests in the previous version subdirectories, should crypto.constants be copied into and tested in v6-v9 (since it was added in v6) ? why are there no tests of v10 definitions ?

**Comment by Flarna** [comment]
The file `node-tests.ts` in same folder as `crypto.d.ts`.

**Comment by Touffy** [comment]
> The file `node-tests.ts` in same folder as `crypto.d.ts`.

Thanks, I missed it among all the other files. I've added the tests.

**Comment by SimonSchick** [comment]
@Touffy can you rebase and see if the build passes?

**Comment by Touffy** [comment]
> @Touffy can you rebase and see if the build passes?

Done it twice now… could someone please merge this before I have to rebase again?

**Pull request merged**
