### PR TITLE
fix restify error classes

### PR DESCRIPTION
**Pull request by Fusselwurm**
- add missing restify error classes
- overloaded error constructors
- more constructor tests

### CODE REVIEW

**Comment by vvakame** [comment]
@blittle @ufon @ericlu88 could you review this PR?

**Comment by Fusselwurm** [comment]
*shameless bump @blittle  

@vvakame nobody seems to pick up on this. :(

**Comment by blittle** [comment]
@Fusselwurm @vvakame my initial look at the PR looks fine, though I haven't been involved with restify in quite a while and as a result I am slow to give my approval :)

**Comment by vvakame** [comment]
@blittle thank you for your comment!
@Fusselwurm thanks mate! I am recommended that you add your name to the author. https://github.com/gruppe-adler/DefinitelyTyped/blob/restify-fix-httperrors/restify/restify.d.ts#L3

**Pull request merged**
