### PR TITLE
chart.js - Add datasetIndex property to ChartLegendItem

### PR DESCRIPTION
**Pull request by archy-bold**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://www.chartjs.org/docs/latest/configuration/legend.html#custom-on-click-actions
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by guillaume-ro-fr — APPROVED** [review]

**Review by chicoxyzzy — COMMENTED** [review]
I'm not sure that this should be added. There is no `datasetIndex` in [legend item interface](http://www.chartjs.org/docs/latest/configuration/legend.html#legend-item-interface). Is it custom field? If so, it could be added by extending `ChartLegendItem`

**Comment by guillaume-ro-fr** [comment]
@chicoxyzzy I agree with you, but in this [doc](http://www.chartjs.org/docs/latest/configuration/legend.html#custom-on-click-actions), `datasetIndex` is a default property, I think the [legendItem interface](http://www.chartjs.org/docs/latest/configuration/legend.html#legend-item-interface) is not updated.

**Comment by chicoxyzzy** [comment]
In this case `legendItem` type should be a supertype of `ChartLegendItem` with optional `datasetIndex` field. This field is autogenerated if I understand this part correctly https://github.com/chartjs/Chart.js/blob/6bea15e7cf89003e3a5945a20cf1d2cc5096728e/src/plugins/plugin.legend.js#L47-L66

**Comment by archy-bold** [comment]
I can confirm that it is present when passed through to the `legends` `onClick`, `onHover` and `legends.labels.filter` functions in v 2.7.2 of chart.js.

**Review by chicoxyzzy — CHANGES_REQUESTED** [review]
[review comment was mistakenly duplicated]

**Review by chicoxyzzy — CHANGES_REQUESTED** [review]
see [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24712#issuecomment-378589431) above

**Comment by archy-bold** [comment]
@chicoxyzzy I'm not sure I understand. Do you mean it should be a subtype?

**Comment by chicoxyzzy** [comment]
`datasetIndex` is not presented in Legend Item Interface. It is autogenerated and presented in even handlers only. So event handlers interface should extend Legend Item Interface and add non-optional `datasetIndex` of type number.

**Comment by archy-bold** [comment]
That's what I thought you meant, but you said it should be a supertype; which is what confused me.

**Review by chicoxyzzy — APPROVED** [review]
Looks good!

**Comment by archy-bold** [comment]
@chicoxyzzy Not a problem. I just didn't want to make a decision over you guys who know the module far better than myself.

**Pull request merged**
