### PR TITLE
fix(maxmsp): LiveApi constructor arguments as optional

### PR DESCRIPTION
**Pull request by aptrn**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] (not changed) [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Live Api Object Docs](https://docs.cycling74.com/max8/vignettes/jsliveapi)
- [x] (n/a) If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by twhiston — CHANGES_REQUESTED** [review]
Please can you add a test which just instantiates this without any constructor arguments

**Comment by aptrn** [comment]
I added tests for it :)

**Review by twhiston — CHANGES_REQUESTED** [review]
sorry for the delay, i've been away! If you could make the suggested change i'll get this merged.

**Review by twhiston — APPROVED** [review]
Approved, thank you!

**Comment by aptrn** [comment]
Ready to merge

**Comment by aptrn** [comment]
Ready to merge

**Comment by aptrn** [comment]
Ready to merge

**Pull request merged**
