### PR TITLE
Added typings for react-router-bootstrap

### PR DESCRIPTION
**Pull request by vlesierse**
Added typed definition for react-router-bootstrap which is a related module for react-bootstrap.

[react-router-bootstrap](https://github.com/react-bootstrap/react-router-bootstrap)

### CODE REVIEW

**Comment by vvakame** [comment]
https://github.com/react-bootstrap/react-router-bootstrap#installation
please use `react-router-bootstrap` dir.

**Comment by vlesierse** [comment]
@vvakame sure, no problem.

**Comment by vvakame** [comment]
sorry for late. happy new year! :smile_cat:

**Comment by vlesierse** [comment]
Great, thnx! And a happy new year :-)

**Pull request merged**
