### PR TITLE
D3 - add "median" to array methods

### PR DESCRIPTION
**Pull request by zuzusik**
This method was lost during one of the latest refactorings.

Docs: https://github.com/d3/d3/wiki/Arrays#d3_median

### CODE REVIEW

**Comment by gustavderdrache** [comment]
Looks good, save for one caveat: it's `median`, not `mediane` (see [median.js](https://github.com/d3/d3/blob/v3.5.17/src/arrays/median.js#L5).)

**Comment by zuzusik** [comment]
@gustavderdrache 👍 for catching the typo, corrected

**Comment by gustavderdrache** [comment]
Nice! :+1:

**Comment by horiuchi** [comment]
@zuzusik Thanks!
@gustavderdrache Thanks for review!

**Pull request merged**
