### PR TITLE
New Types for JSForce

### PR DESCRIPTION
**Pull request by tnoonan-salesforce**
Additional Types added for jsforce

analytics
metadata
chatter

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://jsforce.github.io/jsforce/doc/
- [x] Increase the version number in the header if appropriate.
- [NA] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tnoonan-salesforce** [comment]
@dolanmiu @netes Please review.

**Comment by dolanmiu** [comment]
I see there is a new promise.d.ts class created, but it doesn't seem to be used. Remove?

**Comment by amphro** [comment]
Hey @dolanmiu - we need the promise.d.ts because JSForce adds some custom methods on the promise prototype that we need to reference in our code.

**Review by dolanmiu — APPROVED** [review]

**Comment by dolanmiu** [comment]
Ok fair point

Approved!

Good work

**Pull request merged**
