### PR TITLE
[@types/google-apps-script] Add Drive API V3

### PR DESCRIPTION
**Pull request by sinsky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/drive/api/reference/rest/v3
> [!IMPORTANT]
> To be precise, the Drive API v3 available in GAS has not been made public. Please refer to the following repository for how to extract it.
> https://github.com/sinsky/parse-gas-types
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

#69023

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/google-apps-script/apis/drive_v3.d.ts
1. types/google-apps-script/test/google-apps-script-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6c7ebc25eba0839cc5ffdbbd6900ae44646676b3
</p>

**Review by jpoehnelt — APPROVED** [review]

**Comment by sinsky** [comment]
Ready to merge

**Comment by marekdedic** [comment]
Hi, @sinsky, I think some of the new v3 typings are a bit problematic - In that they are overly optimistic about the presence of various fields.

An example is when calling `Drive.files.list({ fields: "items(id)" })`, the result will be `Array<{id: string}>`, not an array of full comments. The v2 typings handled this by making every field optional - I don't know if that's the best way to do it, but it's certainly safer than what the v3 types have right now.

**Comment by sinsky** [comment]
Hi, @marekdedic. Thank you for your comment.

You're right, making fields optional might offer more flexibility to users, as it would accurately reflect the potential absence of fields in partial API responses.
Unfortunately, I am not able to take this on at the moment due to other commitments.

**Comment by marekdedic** [comment]
@sinsky Understandable, I'll try to make a PR.

**Pull request merged**
