### PR TITLE
[valerie] Repair links

### PR DESCRIPTION
**Pull request by jablko**
#47261

### CODE REVIEW

**Comment by conficient** [comment]
Please cancel this pull request

**Comment by sheetalkamat** [comment]
> Please cancel this pull request

Why this is correct change

**Comment by conficient** [comment]
@sheetalkamat this is a link to a totally different JS library that _happens to have the same name_. The original library has been deleted but github now treats `https://github.com/smagreen/valerie` as the new base.

The Valerie library (that I wrote the definitions for) works with KnockoutJS. It adds a `.validate` method and rules to Knockout observables. e.g
```
ko.observable<string>().validate().required().end();
```

**Comment by jablko** [comment]
Ahh, nice. Based on this, I propose:
- Changing the header to `/// Type definitions for non-npm package valerie` (https://github.com/microsoft/dtslint/blob/master/docs/npm-naming.md)
- Changing the project link to https://github.com/smagreen/valerie

I'll open a PR with these changes, but please request revisions if they're not what is desired (or approve if they are).

**Pull request merged**
