### PR TITLE
Fix redux-form typings

### PR DESCRIPTION
**Pull request by alex3165**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
See the [note](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21) on using TS2.1 features.

**Comment by andy-ms** [comment]
CC'ing authors @carsonf @aikoven

**Review by CarsonF — CHANGES_REQUESTED** [review]
`Partial<FormData>` would be simpler

**Comment by philpl** [comment]
@CarsonF it's not using `Partial<>` as it's also changing the value types to `string`, which is crucial for the `FormErrors` to make sense

**Comment by CarsonF** [comment]
Hmm that's a good point. However, they don't have to be strings. For example, I have a project which returns `react-intl`'s `FormattedMessage` component to translate the error message.

**Comment by philpl** [comment]
@CarsonF I'm actually using `react-intl` as well and I'm just setting the `FormErrors` values to some message ids.

Also, `redux-form`'s docs themselves are saying that the error format is supposed to be FormData with error strings as values:

> If validation fails, it should return the validation errors in the form { field1: <String>, field2: <String> }.

http://redux-form.com/6.4.3/docs/api/ReduxForm.md/

**Comment by CarsonF** [comment]
So you're not using `description` or `defaultMessage` then? We are.

Yeah it makes sense for the docs to say that, but they don't do any string manipulation. Objects work too.

**Comment by philpl** [comment]
@CarsonF hm, that's a tricky one. @alex3165 and I just put `string` since that's what the docs say it's expecting. If it turns out that it can take any value, we could just set the value type to `any`. That's of course not optimal, but it would avoid having to add more generics.

**Comment by CarsonF** [comment]
Hmmm what about `ReactNode`?
```ts
type ReactText = string | number;
type ReactChild = ReactElement<any> | ReactText;

// Should be Array<ReactNode> but type aliases cannot be recursive
type ReactFragment = {} | Array<ReactChild | any[] | boolean>;
type ReactNode = ReactChild | ReactFragment | boolean | null | undefined;
```

If we wanted to be stricter we could do `ReactElement<any> | string`.

I think `ReactElement` will work now. I had problems in the past with types for passed components, hence the `ComponentConstructor` type. But that may have been / is probably fixed since 2.0.

**Comment by philpl** [comment]
@CarsonF Yea, I think that's a good idea. `ReactElement<any> | string` is not too loose. I think we should go with it :)

**Comment by CarsonF** [comment]
Cool. Let me double check locally that tsc doesn't complain about ReactElement.

**Comment by CarsonF** [comment]
@philpl Ok yeah that works for me!

**Comment by philpl** [comment]
@CarsonF Cool! @alex3165 will probably have time to update this later today (?) 👍

**Review by CarsonF — APPROVED** [review]
Looks good! Thanks 👍

**Comment by philpl** [comment]
@andy-ms I believe this can be merged now :) 🎊

**Pull request merged**
