### PR TITLE
[generate-ctrl-c-event] indent 4 spaces

### PR DESCRIPTION
**Pull request by kazarmy**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes 2nd item
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR indents to 4 spaces to comply with DefinitelyTyped formatting requirements, and edits the tests so that @typescript-bot doesn't complain about missing tests.

### CODE REVIEW

**Comment by zenflow** [comment]
> This PR indents to 4 spaces to comply with DefinitelyTyped formatting requirements, and edits the tests so that @typescript-bot doesn't complain about missing tests.

@kazarmy I understand the change to indentation, but I am not understanding what the problem is here: "edits the tests so that @typescript-bot doesn't complain about missing tests". The note above says "2nd item" [of common mistakes] but that just talks about the formatting & indentation (first issue) and says nothing about missing tests (second issue).

Where is typescript-bot complaining about either of these issues? It let the original PR be merged. I am a bit confused.

**Comment by kazarmy** [comment]
Sorry for the confusion. The problem here is indeed just the indentation of 4 spaces. I have changed the tests because @typescript-bot does not allow a merge on only owner approval if tests do not change in a pr i.e. a pr without tests will need to be approved by a DT maintainer instead of just you @zenflow (e.g. see the 3rd Status line in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54055#issuecomment-867999985).

**Review by orta — APPROVED** [review]

**Comment by kazarmy** [comment]
Ready to merge

**Comment by zenflow** [comment]
@kazarmy @orta Sorry to be critical, and it's no big deal, but I am surprised this was merged. I don't think formatting changes warrant a new patch release (or minor release or major release), since it doesn't fix a bug, and makes no functional changes, i.e. no changes as far as the package consumer is concerned. These changes could have been saved and included in the next release.

**Comment by kazarmy** [comment]
@zenflow I actually had your concerns, which is why I didn't push you to approve this pr, but my view on this is that a new patch release can be made because:

1. The release does not break functionality.
2. There might not even be a next release. In fact, the only enhancement I can see here that can be made is the addition of JSDoc comments for use by IDEs, but here the `generate-ctrl-c-event` API appears simple enough that one can understand it rather easily without needing reminders.

Besides, [DefinitelyTyped's workflow](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request) apparently discourages holding prs indefinitely, and a decision is better than no decision at all.

**Pull request merged**
