### PR TITLE
updated three libraries

### PR DESCRIPTION
**Pull request by TrabacchinLuigi**
those three definetly types were not very accurate, i've fixed the most that i was able to, and noticed

### CODE REVIEW

**Comment by subjectix** [comment]
Different libraries are authored by different people. And each would need to review their own. I would suggest making three different PRs from 3 different branches of your fork each for one of these libraries, so it's easier to track and review. I don't maintain any of them, just saying :grin: :grin:

**Comment by TrabacchinLuigi** [comment]
@subjectix i was expecting something like that, but i'm just too new in the git environment, i'm used to tfs :8ball: 

Well let's try if someone will blindly accept this, since they were just very outdated, 'couse i have no time now...

**Comment by subjectix** [comment]
Don't worry, if the maintainers don't merge this, I'll fork your fork, break it into 3 branches and make 3 PRs.

**Comment by vvakame** [comment]
> I would suggest making three different PRs

:+1: 

---

*bootstrap.v3.datetimepicker/bootstrap.v3.datetimepicker.d.ts*

to author(@bayitajesi). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*fullCalendar/fullCalendar.d.ts*

to authors(@nestalk @hasellcamargo). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*typeahead/typeahead.d.ts*

to authors(@igochkov @gjunge). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by gjunge** [comment]
typeahead :+1:

**Comment by bayitajesi** [comment]
I'll review the part related to bootstrap.v3.datetimepicker as soon as I can and comment here

**Comment by TrabacchinLuigi** [comment]
any news ?

**Comment by vvakame** [comment]
@nestalk @haskellcamargo can I merge this PR? I'll merge this PR 2days later.
@TrabacchinLuigi please ping me again.

**Comment by TrabacchinLuigi** [comment]
Looks like fullcalendar team haven't checked, but i'll go on, i do use the library and i wrote the code in order to be able to use the very outdated definitely typed

**Comment by haskellcamargo** [comment]
I didn't find any conflicts here, the `any` type definitions have been replaced by secure one, the dates still are able to receive strings. The code-style has been also standardized. It seems **ok** to me.

**Comment by TrabacchinLuigi** [comment]
@vvakame ping! :)

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
