### PR TITLE
belvo: Remove Belvo SDK support

### PR DESCRIPTION
**Pull request by renan-at-belvo**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
what's the change behind this PR?
https://github.com/belvo-finance/belvo-js/blob/bbbc064702c4651d6f2221aacb25840be607a7e2/.gitignore#L45

**Comment by renan-at-belvo** [comment]
> what's the change behind this PR? https://github.com/belvo-finance/belvo-js/blob/bbbc064702c4651d6f2221aacb25840be607a7e2/.gitignore#L45

Hi @peterblazejewicz I'm removing the TypeScript support for this SDK via DefinitelyTyped as I'm no more a maintainer for this library (I was the only one) and there's no one left to keep this project alive by now. Belvo team is considering to have a bundled support in the future but nothing in a near future. 

Is there any issue with the PR due that? 

Thanks in advance!

**Comment by peterblazejewicz** [comment]
OK, eventually you can consider:
- replacing yourself with `Definitions by: DefinitelyTyped <https://github.com/DefinitelyTyped>` as the owner
- (after update being published), removing sources from DT (maintainer can do this as well. That would prevent publishing stub definition to NPM registry.
Let me know what you think, thx!

**Comment by renan-at-belvo** [comment]
No problem, @peterblazejewicz. Only to confirm two things:

1. Should I need to close this pull request first, edit and PR the file change and open a new one? Or only opening a new one keeping this one opened will be good?
2. Do I need to run a `npm run not-needed` too or only delete the DT sources will attend to the proper way?

Thanks again!

**Comment by peterblazejewicz** [comment]
> Should I need to close this pull request first, edit and PR the file change and open a new one? Or only opening a new one keeping this one opened will be good?

you can leave this open, to be finished later

- Do I need to run a npm run not-needed too or only delete the DT sources will attend to the proper way?

just remove entry from 'not-needed' file, this will revent publishing of stub entry to NPM
thx!

**Comment by renan-at-belvo** [comment]
> you can leave this open, to be finished later

Great leaving this as opened. PR for owner change is opened (#58501).

> just remove entry from 'not-needed' file, this will revent publishing of stub entry to NPM thx!

I'll change this file and send it through this PR too. 

Thanks for your help, @peterblazejewicz 🙌

**Comment by renan-at-belvo** [comment]
@peterblazejewicz I did remove the belvo folder with the updated index.d.ts -- seems it's all good now. 

Please let me know if you need something else. 

Thx again!

**Comment by peterblazejewicz** [comment]
Yes, checked NPM  and it did publish updates already

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by renan-at-belvo** [comment]
Ready to merge

**Pull request merged**
