### PR TITLE
Improved - blessedjs typing

### PR DESCRIPTION
**Pull request by Diullei**
Improved blessedjs definition. The current code has no tests and is not working as expected. Tests were added.

### CODE REVIEW

**Comment by Diullei** [comment]
Hi @brynbellomy, would you like to verify this PR?

**Comment by paulvanbrenk** [comment]
@Diullei The changes are huge and thus hard to review. Can you split this into multiple commits to make the process easier?

**Comment by Diullei** [comment]
Hi @paulvanbrenk, I had to make a lot of changes because the current definition are not working correctly and not have tests. I merged the current definition with my own definition file and because this, I'll not be able to split it into small commits, sorry. 

Now this code is working well and have some tests. I not merged it before because I'd like to know if @brynbellomy has some comments about this. 

But, I'll merge this code if it's ok to you ;)

Thanks!

**Comment by paulvanbrenk** [comment]
Let's give @brynbellomy until Monday? It looks good to me.

**Comment by Diullei** [comment]
sure! :+1:

**Comment by brynbellomy** [comment]
Hey guys, I haven't had time to be involved in this stuff for quite some
time - my affair with blessedjs was brief and fleeting, and I've been under
the impression that it's changed a lot since I wrote these types. I'm
afraid I won't be able to provide much input, but you have my blessing (no
pun intended) to do as you see fit. :)

**Comment by Diullei** [comment]
@brynbellomy thanks! :+1:

**Pull request merged**
