### PR TITLE
Fixes casing of the Xrm.Panel.loadPanel method in package xrm

### PR DESCRIPTION
**Pull request by sbelzile-Coveo**
- [x] Use a meaningful title for the pull request. Include the name of the package modified (xrm).

If changing an existing definition:
- Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/xrm-panel/loadpanel
Doc was wrong.

### CODE REVIEW

**Comment by carltoncolter** [comment]
I incorporated this change into the changeset #21733 which is still waiting to be merged.

**Comment by sbelzile-Coveo** [comment]
Great! Closing PR since change is already included in this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21733).

**Comment by carltoncolter** [comment]
@sbelzile-Coveo Thanks!  Good catch.  I noticed the L is uppercase on this page: https://msdn.microsoft.com/en-us/library/mt790281.aspx  - I left a feedback response noting the discrepancy.  If you can do the same then we can help push getting the documentation updated accordingly.

**Comment by sbelzile-Coveo** [comment]
Yep, I did this as well.

**Pull request closed without merging**
