### PR TITLE
"Center" html tag support for React Typescript

### PR DESCRIPTION
**Pull request by ufukbakan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.w3schools.com/tags/tag_center.asp>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Semigradsky** [comment]
@ufukbakan This tag was deprecated and marked as obsolete in HTML standard. Why you need it?

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 94886cd38b3bfa8cc5a917feab13f9a6e298ee74
</p>

**Comment by ufukbakan** [comment]
> @ufukbakan This tag was deprecated and marked as obsolete in HTML standard. Why you need it?

Some people and most websites still use this tag, and adding this <center> wont broke anything since its different from <Center> and custom components can only start with an uppercase letter. Adding it as html tag will give us more backward compability for html4 sites.

**Review by eps1lon — APPROVED** [review]

**Comment by eps1lon** [comment]
We already have declarations for other deprecated tags.

**Comment by Semigradsky** [comment]
What about other obsolete tags like `acronym`, `dir`, `listing`, `strike`, `marquee`, `spacer`?

**Comment by ufukbakan** [comment]
> What about other obsolete tags like `acronym`, `dir`, `listing`, `strike`, `marquee`, `spacer`?

You can contribute for any tag if you use it commonly in your react projects

**Pull request merged**
