### PR TITLE
Update @types/react-dates to v21.8

### PR DESCRIPTION
**Pull request by jsonunger**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/airbnb/react-dates/tree/v21.8.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by cgriebel** [comment]
@jsonunger I'll take a look at this tonight.

**Review by cgriebel — CHANGES_REQUESTED** [review]
It looks like you included some types from master that aren't in v21.8.0.

I also noticed some additional type improvements we could add, I'm fine omitting those as long as the master properties are removed.

**Comment by jsonunger** [comment]
@cgriebel thanks for the review and catching some mistakes! Will tackle these pronto

**Comment by cgriebel** [comment]
@jsonunger I'm actually fairly new to TypeScript, could you explain why we need to do 
```ts
export type SingleDatePickerInput = React.FC<SingleDatePickerInputShape>;
export const SingleDatePickerInput: React.FC<SingleDatePickerInputShape>;
```
instead of just
```ts
export type SingleDatePickerInput = React.FC<SingleDatePickerInputShape>;
```

**Comment by cgriebel** [comment]
@jsonunger Looks great, thanks for the PR. I had planned on doing this after #46661 got merged, you saved me a lot of time! 😄

**Review by cgriebel — APPROVED** [review]

**Comment by cgriebel** [comment]
Ready to merge

**Pull request merged**
