### PR TITLE
using with ts 2.0

### PR DESCRIPTION
**Pull request by phaelmoita**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by tomwanzek — CHANGES_REQUESTED** [review]
This PR is not acceptable. The changes to package.json are diverting from the source of truth which is  DefinitelyTyped.

The remaining changes are unmotivated and revert back from the latest update to using TS 2.3 features like the new `object` type.

This PR should be closed. If there are specific issues with the recent changes to d3-collection, please open an issue and explain the motivation for any changes.

**Comment by gustavderdrache** [comment]
Raphael,

I'm sorry that you can't use this package as written due to the version requirements.

Unfortunately, when we started developing the type definitions for the d3 v4 packages, we made the decision to require version 2.3 for some language features. Most notably, we lean heavily on the `object` type, which is what the TypeScript Handbook recommends over the `Object` type (see [Do's and Don'ts](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)). You can see in the Travis build log that this is enforced by the project, so we don't want to change this lightly.

That does mean we've left people behind -- going by the title of this pull request, that includes you. Judging by the release notes, version 2.3 is almost a year old. It should be safe for you to update. Do you have any issues with trying to update the project (or projects) that need this change to a new TypeScript version instead?

**Comment by tomwanzek** [comment]
@phaelmoita It's been a long  day, so clearly I have been too brief... What @gustavderdrache said holds more water than my crude shorthand earlier. In any case, it is never necessary to touch the DefinitelyTyped `package.json` 😄

**Comment by tomwanzek** [comment]
@phaelmoita Do you require any follow-up to this PR or can it be closed? Just doing some housekeeping.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
