### PR TITLE
Updated yargs to 6.3.0

### PR DESCRIPTION
**Pull request by pushplay**
Please fill in this template.
- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: http://yargs.js.org/docs/
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by poelstra** [comment]
@pushplay Changes in the typings look good. I see you added tests for some items, but can you please add some for your other changes, too?

If so, I suppose this PR will replace #12336.

**Comment by pushplay** [comment]
The ones I added are in the official documentation. To add more I'll have
to make them up from my experience and understanding of the docs. Sound
okay?

**Comment by poelstra** [comment]
Yeah, ran into that myself too, long time ago. Docs and examples are a bit challenging :)

But yes, please do add them anyway!

**Comment by pushplay** [comment]
@poelstra Done.  Made a couple improvements to the typings in the process so that was a win.

**Comment by poelstra** [comment]
@pushplay Nice, thnx!

:+1: from me

**Comment by vvakame** [comment]
@pushplay could you resolve conflict?

**Comment by pushplay** [comment]
@vvakame 👍

**Pull request merged**
