### PR TITLE
[mapbox-gl] Use discriminated union for Layer

### PR DESCRIPTION
**Pull request by MichalPrzybys-TomTom**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-property
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by macobo — APPROVED** [review]

**Comment by macobo** [comment]
Ready to merge

**Comment by dmytro-gokun** [comment]
@MichalPrzybys-TomTom Hi, can you plz explain the rational behind this breaking change? The thing is that it have broken compilation for some library(-ies) which use this type definition. I do not think this is the correct way to do it. I'd suggest that we keep "Layer" named "LayerBase" (and keep it's definition) and user new name "AnyLayer" for new union type. This way we do not break any existing code.

**Comment by MichalPrzybys-TomTom** [comment]
@dmytro-gokun I'm sorry to hear that wykks/ngx-mapbox broke down because of my commit.
Please bear in mind that this was similar to changing `any` or `object` to stricter type, one used in actual mapbox; so, while inconvenient, compilation failing here is actually a good thing, tsc telling you that something is not used properly.
`AnyLayer` is great idea, but I'd suggest loose type like:
```
interface AnyLayer extends LayerBase {
    type: Layer["type"];
    layout?: AnyLayout;	
    paint?: AnyPaint;
}
```
to match existing `AnyLayout` and `AnyPaint` types.

**Comment by dmytro-gokun** [comment]
@MichalPrzybys-TomTom Well, the main reason of the breaking is that type 'Layer' used to be interface we implemented in a class and now 'Layer' is a union type (which we cannot be implemented). Thus, I think 'Layer' and should remain 'Layer' (so existing code is not broken) and your new type 'Layer' should become 'AnyLayer' (and that will follow the convention of using 'Any' prefix on union types).

**Comment by dmytro-gokun** [comment]
@MichalPrzybys-TomTom 

> compilation failing here is actually a good thing, tsc telling you that something is not used properly.

No, it is not. The compilation failure is not because of type issue in our code. It is because of the breaking change you made.

**Comment by MichalPrzybys-TomTom** [comment]
> @MichalPrzybys-TomTom
> 
> > compilation failing here is actually a good thing, tsc telling you that something is not used properly.
> 
> No, it is not. The compilation failure is not because of type issue in our code. It is because of the breaking change you made.

Yes, it manifested after my change, but all in all it's typescript trying to check whether you're creating proper `Layer` that mapbox-gl would accept. It won't work well with type `circle`, `FillPaint` and `BackgroundLayout`, but old `Layer` would be okay with that.

**Comment by MichalPrzybys-TomTom** [comment]
`AnyLayer` is a good idea, as it indeed matches `AnyLayout` and `AnyPaint`.

**Comment by dmytro-gokun** [comment]
@MichalPrzybys-TomTom Okay, i've created a new PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49986
If you have any objections, please chime in.

**Comment by JRigotti** [comment]
Moving the `Layer` interface to a union type is a breaking change by the way... A simple use case is a class implementing `Layer` which is not possible anymore.

**Comment by dmytro-gokun** [comment]
@JRigotti This has been reverted in version 1.12.9 to npm. Is it still a breaking change?

**Comment by JRigotti** [comment]
@dmytro-gokun oh yes I see that it was reverted, however now I see that `Layer` is not exported anymore, only `AnyLayer`. Is this an option, or can this interface also be exported?

**Comment by dmytro-gokun** [comment]
@JRigotti what do you mean it is not exported? It definitely is: https://github.com/dmytro-gokun/DefinitelyTyped/blob/511c4319da692cd0fa3bdad3401dca099758c84f/types/mapbox-gl/index.d.ts#L1878

Please show a reproduction project or stackblitz.

**Comment by JRigotti** [comment]
@dmytro-gokun I am confused, how can it be exported if there's no `export` keyword?

**Comment by dmytro-gokun** [comment]
@JRigotti I think you need to read up on how TypeScript type definition files work. But only if you need to :). Just go ahead and import stuff and you will see it is exported indeed.

**Comment by markcarroll** [comment]
Just for the record, this was a horrible change that caused a lot of issues that were otherwise working fine. 

The problem here is that `AnyLayer` includes `CustomLayerInterface` in it's type union, but unlike all the other layers `CustomLayerInterface` does not extend `Layer` so all the properties inherited from `Layer` in the other types are broken by the inclusion of `CustomLayerInterface`.  

So now to get everything passing we have to put a check for `layer.type !== "custom"` in everywhere that we reference common layer properties.

**Pull request merged**
