### PR TITLE
Fix react-table Header and render properties per issue #20713

### PR DESCRIPTION
**Pull request by ravihugo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://react-table.js.org/ (Click on section Columns in Table of Contents - direct linking is not working)
- [ ] Increase the version number in the header if appropriate. Not needed
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. Not needed

### CODE REVIEW

**Comment by minestarks** [comment]
@royxue @psakalo do you have any comments?

**Comment by minestarks** [comment]
Pinging people from issue #20713 @blindbox @rhonsby @Havret

**Comment by Havret** [comment]
I think I have already deal with this in #21878.

**Comment by minestarks** [comment]
@ravihugo mind if I close this in favor of #21878 ?

**Comment by ravihugo** [comment]
@minestarks Yes please it looks like 21878 is much more complete. Thanks!

**Pull request closed without merging**
