### PR TITLE
@types/aws-lambda: There are no types for the communication with Application Load Balancer

### PR DESCRIPTION
**Pull request by redlickigrzegorz**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33060)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by redlickigrzegorz** [comment]
@atombrenner yes, we can, I will commit the changes 👍

**Review by simonbuchan — COMMENTED** [review]
Only seems to be missing `ALBCallback`, for completeness (since this handler has a result)
Otherwise this looks good!

**Comment by redlickigrzegorz** [comment]
@simonbuchan I will add it for completeness 👍 I am not using it in my production code, that's why I forgot about it.

**Review by simonbuchan — APPROVED** [review]
Thanks!

**Pull request merged**
