### PR TITLE
[@types/morgan] Fix tests

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49879>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

## See also:
- <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50076>

---

/cc @Leithal3 @rbuckton

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
this snipped comes from readme:
https://www.npmjs.com/package/morgan#examples
```ts
const app = express();
app.use(morgan('combined'))
```
We shouldn't brake default way of using code, should we? 
It won't compile withe the upstream change, let me update

**Comment by Leithal3** [comment]
Hi @ExE-Boss, @peterblazejewicz 

This issue was caused by me, I have raised a PR that I believe addresses it. Hopefully this means you won't need to update any code.

**Comment by peterblazejewicz** [comment]
@Leithal3 thx!

**Comment by ExE-Boss** [comment]
@peterblazejewicz I still think we should update the tests.

**Comment by peterblazejewicz** [comment]
agree, should we keep default usage though?

**Comment by ExE-Boss** [comment]
@peterblazejewicz Default usage is still supported.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@ExE-Boss thx!

**Comment by ExE-Boss** [comment]
Ready to merge

**Pull request merged**
