### PR TITLE
[sequelize] add `force` option for TruncateOptions and `where` option for DefineIndexesOptions

### PR DESCRIPTION
**Pull request by Botik**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L2234> <http://docs.sequelizejs.com/en/v3/docs/models-definition/#indexes>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by drinchev** [comment]
Thanks for your contribution.

Why have you deleted the `force` option from DestroyOptions interface? Is there a specific reason not to leave it as it is, since as far as I can see from the source code it exists there as well!

**Comment by Botik** [comment]
No, just for pretty code

If see to sequelize code then 'truncate' method inherit all 'destroy' attributes excepted 'truncate'. But in this code contrariwise

**Comment by drinchev** [comment]
Yes, but the destroy method also accepts `force` option, so I think it should be there.

https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/model.js#L2248

**Comment by Botik** [comment]
Ok, a restore `error` option

**Comment by drinchev** [comment]
Also can you please separate the addition of `where` property to the index in a separate pull request.

It's the proper thing to do :) 

Thank you for your contribution.

**Comment by Botik** [comment]
Ok https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16353

**Pull request closed without merging**
