### PR TITLE
feat: make GraphQLSchema generic

### PR DESCRIPTION
**Pull request by polRk**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by polRk** [comment]
```
const resolver: GraphQLFieldResolver< null,  { db: Db },  { id: string }> = source => {
  return null
}

export const queryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    contact: {
      type: contactType,
      args: { id: { type: GraphQLString } },
      resolve: resolver,
    },
  },
})

const schema = new GraphQLSchema({ query: queryType }) //error
```

```
Property 'id' is missing in type '{ [key: string]: any; }' but required in type '{ id: string; }'.
```

**Review by jednano — APPROVED** [review]

**Review by jednano — APPROVED** [review]

**Comment by polRk** [comment]
The problem is that as long as we do not merge changes, graphql-errors-tests.ts will always fall :(
Help me solve this problem

**Comment by polRk** [comment]
And its make an error
```
const resolver: GraphQLFieldResolver<null, { db: Db }> = (
  source,
  args: { id: string }, // error
  context
) => {
  console.log(source, args, context)
  return null
}
```
Property 'id' is missing in type '{ [argName: string]: any; }' but required in type '{ id: string; }'.
```

**Comment by polRk** [comment]
> @polRk The Travis CI build failed! Please [review the logs for more information](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/554746185?utm_source=github_status&utm_medium=notification).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!

The problem is that as long as we do not merge changes, graphql-errors-tests.ts will always fall :(
Help me solve this problem

**Pull request closed without merging**
