### PR TITLE
screenfull: Exported type can be false

### PR DESCRIPTION
**Pull request by tenorok**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sindresorhus/screenfull.js/blob/v3.3.3/src/screenfull.js#L72
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by icholy — APPROVED** [review]

**Comment by tenorok** [comment]
@icholy it can be merged :-)

**Comment by icholy** [comment]
@tenorok one of the maintainers will merge it when they get a minute.

**Review by icholy — APPROVED** [review]

**Comment by ddmng** [comment]
@tenorok this change is blocking compilation in my Angular application:
```
Property 'enabled' does not exist on type 'false | IScreenfull'.
Property 'enabled' does not exist on type 'false'.
```
Do I need to change any typescript param to make it work again?

**Comment by icholy** [comment]
@ddmng you need to check if it's not `false` before using it.

``` js
if (screenfull && screenfull.enabled) {
  // now the type-checker knows that screenfull isn't `false`
}
```

**Comment by ddmng** [comment]
OK it works. I tried it before adding the comment but it was not working, now it's OK. Thanks!

**Comment by bobmoff** [comment]
I have never seen this pattern before. Setting the default export to be able to be false?

If I import the module, could it still be false or is this only for when including the script through a script tag ?

**Comment by icholy** [comment]
@bobmoff seems kinda janky, but it's what they did https://github.com/sindresorhus/screenfull.js/blob/41d0b41a3112abb64b4d9fcc50422974153be5f9/src/screenfull.js#L127-L135

**Pull request merged**
