### PR TITLE
fix(restrictChatMember): removing chat member restrictions not working

### PR DESCRIPTION
**Pull request by shadowplay1**
# node-telegram-bot-api

**This PR fixes the __breaking__ typings bug in `TelegramBot.restrictChatMember()` method:**
- Telegram API doesn't take the permissions in its own `permissions` object, but as part of the request body, while in typings the method does, which is *not correct*.
- As the permissions were passed inside the `permissions` object, not as part of request body, `restrictChatMember` method is not working as intended and it causes breaking bugs in muting/unmuting members.

**With this fix, chat members restrictions should be working without any problems, as well as removing the restrictions from the chat member should work fine now too.**

Changes in this PR:

- [x] Simplified the way of defining the `ChatPermissions` interface.
- [x] Removed the `permissions` object from `RestrictChatMemberOptions` interface.
- [x] Extend the `RestrictChatMemberOptions` interface with `ChatPermissions` type to allow specifying the permissions as part of the request body object, not the `permissions` object.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-telegram-bot-api/node-telegram-bot-api-tests.ts
1. types/node-telegram-bot-api/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 965cd6dcf4c45668a88f7933390ded0347dd9841
</p>

**Comment by XC-Zhang** [comment]
I wonder if I misunderstand the [doc](https://core.telegram.org/bots/api#restrictchatmember) of Telegram, which do put permission options in a `permissions` field.

TelegramDoc

**Comment by shadowplay1** [comment]
The module itself doesn't seem to be passing that permissions object as intended and it caused bugs with adding/removing them (removing permissions didn't work at all); it was tested and everything works fine with the permissions properties specified as part of the request body, not the `permissions` object

**Comment by XC-Zhang** [comment]
I did a quick test without success, some behavior is odd. Will try tomorrow with more test cases.

**Comment by shadowplay1** [comment]
my close friend was struggling with his unmuting system for a whole month, i tried my best helping him, and as soon as we both lost hope in making the unmute system working, we started digging inside the module and started testing some random changes, and then we tried putting the permissions properties outside of the `permissions` object, and voila, it finally worked! who knew that this small thing could cause the whole month of suffering lol

**Comment by XC-Zhang** [comment]
Did you try sending permissions as JSON-stringified string? 
```
bot.restrictChatMember(
    chatId, 
    userId, 
    { permissions: JSON.stringify({ can_send_messages: true, can_send_audios: false, }) 
})
```

**Comment by shadowplay1** [comment]
We did, no success

**Comment by XC-Zhang** [comment]
I just created a small repo to try to demonstrate the approach that I think we should use. Could you please try it on your environment?

**Comment by shadowplay1** [comment]
1) https://cdn.discordapp.com/attachments/874003225248936056/1176219046644023357/image.png?ex=656e1259&is=655b9d59&hm=d10e76205b3515f6ed4196a3e0a4a3d6192f05619ec8b90c8e598cc7271c1ef8&
2) https://cdn.discordapp.com/attachments/874003225248936056/1176219208690966570/Screenshot_8.png?ex=656e1280&is=655b9d80&hm=109177b65e37485dbf7f5944d457017c4987bba922fbfac20cc1f6835c894228&

tested ith typescript (screenshots):
1) is from my friend and
2) is from me

tested it with JS and with your JSON-stringify approach, it restricts the specified permissions, but not giving them back at all.
however, the method described above works as intended:
```ts
            bot.restrictChatMember(toRestrictItem.groupId, toRestrictItem.userId, {
                use_independent_chat_permissions: true,
                can_send_messages: true,
                can_send_audios: true,
                can_send_documents: true,
                can_send_photos: true,
                can_send_videos: true,
                can_send_video_notes: true,
                can_send_voice_notes: true,
                can_send_polls: true,
                can_send_other_messages: true
            })```

**Comment by XC-Zhang** [comment]
After looking into telegram bot api's changelog, I realize that putting permissions directly in the object root is an available way. This was the original api signature of `restrictChatMember`. The following screenshot is taken from [Web Archive](https://web.archive.org/web/20190719050947/https://core.telegram.org/bots/api#restrictchatmember):

Screenshot 2023-11-21 at 13 54 09

[On July 29, 2019](https://core.telegram.org/bots/api-changelog#july-29-2019), Telegram team changed the signature to what it looks like nowadays, keeping legacy signature working for compatibility.

> The method [restrictChatMember](https://core.telegram.org/bots/api#restrictchatmember) now takes the new user permissions in a single argument of the type [ChatPermissions](https://core.telegram.org/bots/api#chatpermissions). The old way of passing parameters will keep working for a while for backward compatibility.

Screenshot 2023-11-21 at 13 58 18

In this PR I suggest we make two overloads of `restrcitChatMember`, mark one of them as deprecated. 
Any ideas?

**Comment by shadowplay1** [comment]
Which overloads should I add?

**Comment by shadowplay1** [comment]
added overloads to support JSON.stringify approach and to support permissions properties inside the `options` object; marked overload with `permissions: TelegramBot.ChatPermissions` as deprecated

**Comment by XC-Zhang** [comment]
I thought that permissions properties inside the `options` object should be deprecated according to Telegram's changelog. Was I wrong?

By the way, the 4th overload is the combination of the 2nd and 3rd. It would be okay to keep the 4th one and remove the 2nd and the 3rd.

2nd:
`options?: TelegramBot.RestrictChatMemberOptions & { permissions?: string }`

3rd: 
```
options?: TelegramBot.RestrictChatMemberOptions & {
    permissions?: TelegramBot.ChatPermissions;
}
```

4th:
`options?: TelegramBot.RestrictChatMemberOptions & { permissions?: string | TelegramBot.ChatPermissions }`

**Comment by shadowplay1** [comment]
4th "overload" is the actual type definition to make all overloads above working
and i marked the `options?: TelegramBot.RestrictChatMemberOptions & {
    permissions?: TelegramBot.ChatPermissions;
}` overload as deprecated because it doesnt work as intended (in our case - removing restrictions doesn't work at all)

**Comment by XieJiSS** [comment]
I'm wondering why passing permissions inside the 'permission' property does not work. Seems like this is the latest documented usage of the API in the official docs (and I think this is why @XC-Zhang insists on marking old approaches as deprecated). If the actual behavior of the official bot api is not the same as documented, and we can reproduce that, I'd like to contact the telegram bot api dev team to inspect it.

That said, I'm OK with adding back the typing of the old API signature, as long as it is marked as deprecated.

**Comment by shadowplay1** [comment]
So for now, no further changes are needed from me?

**Comment by XieJiSS** [comment]
I'm not sure, for this PR I may need to wait for @XC-Zhang's opinion, because he has followed the whole thread. Meanwhile, I suspect there's some issue with `node-telegram-bot-api`, that it may fail to perform the `JSON.stringify` operation as noted in the official docs:

image

If that's the case, I'd suggest 1) leave the current signature as-is instead of changing to `string` and open a PR at `node-telegram-bot-api` to add a `JSON.stringify` on their side, and 2) add back the old signature with a deprecated mark.

**Comment by shadowplay1** [comment]
im a bit confused, i can't understand what you mean by "old signature" - i didnt remove anything, but added overloads so all the approaches could be possible

**Review by XieJiSS — APPROVED** [review]

**Comment by XC-Zhang** [comment]
Sorry for late reply! Been busy last week.
Thanks @XieJiSS for taking time into this! As you stated, node-telegram-bot-api does not stringify the permissions. I'd like to create a PR there. 
@shadowplay1 Could you please provide some cases where JSON-stringified approach does not work? I'll try reproducing them.

**Pull request merged**
