### PR TITLE
[`mapbox__mapbox-sdk`] - Add types for missing `@mapbox/mapbox-sdk` and `isochrone` service

### PR DESCRIPTION
**Pull request by tetarchus**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Main Export](https://github.com/mapbox/mapbox-sdk-js/blob/v0.15.16/lib/node/node-client.js) / [Docs for using the import](https://github.com/mapbox/mapbox-sdk-js/blob/v0.15.16/lib/node/node-client.js)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

Fixes `File '*/node_modules/@types/mapbox__mapbox-sdk/index.d.ts' is not a module.` error when following documentation:

```js
const mbxClient = require('@mapbox/mapbox-sdk');
const mbxStyles = require('@mapbox/mapbox-sdk/services/styles');
const mbxTilesets = require('@mapbox/mapbox-sdk/services/tilesets');

const baseClient = mbxClient({ accessToken: MY_ACCESS_TOKEN });
const stylesService = mbxStyles(baseClient);
const tilesetsService = mbxTilesets(baseClient);
```

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/mapbox__mapbox-sdk/mapbox__mapbox-sdk-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 20077c3b66512d8021e6e88be1f1d56ee903f5a2
</p>

**Review by jeffbdye — APPROVED** [review]
Thanks for updating the classes to match the latest of the mapbox docs and the updates for the Isochrone methods! Looks good to me.

**Comment by tetarchus** [comment]
Ready to merge

**Comment by tetarchus** [comment]
Ready to merge ?

**Pull request merged**
