### PR TITLE
Add several missing typings for the recharts Tooltip Component

### PR DESCRIPTION
**Pull request by richbai90**
Missing the following details from the Tooltip Payload:

- color?
- fill?
- formatter?
- datakey?

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L515 / http://jsfiddle.net/661f2qc7/2/
- [ x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mthmulders** [comment]
@richbai90, thanks for your contribution.

In the source code for `Tooltip`, there is a [propType for `payload`](https://github.com/recharts/recharts/blob/0777886e0461bf3048cfeabbfd33d5b0a274744d/src/component/Tooltip.js#L44). It has `name`, `value` and `unit`. I can't find any reference to `color`, `fill`, `dataKey` or `formatter`. Could you please explain why the new props would be needed?

**Comment by richbai90** [comment]
@mthmulders I'm having a tough time tracking down exactly what's happening here, but they are undocumented types, and I need to use them in my tooltip component. You can see that they exist in my linked fiddle. I will submit an issue with the recharts team to see if they can direct me to exactly where these props come from.

**Comment by richbai90** [comment]
After a little more digging I can show you where these props are added, but it's kind of a mess so bear with me:

It starts in the generateCategoricalChart.js line 1303
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L1303

This clones the Tooltip element and adds `this.state.activePayload` as the payload prop.
The `state.activePayload` is set `onMouseEnter` when the `recharts.SYNC_EVENT` event is emitted
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L966

The event is handled by the event handler
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L896

Which calculates the activePayload
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L922

And updates the state
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L930

When the activePayload is calculated the undocumented props are added
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L562

It is unclear whether these same props would exist on a chart that is not categorical, like a line or area chart, but at least for categorical charts, they will exist though may potentially be undefined. That is why the props are optional.

**Comment by mthmulders** [comment]
I can see why you had a hard time figuring out what happens and when it happens. Thanks for the extensive research!

First of all, I'm willing to merge this. However, I'd like to understand why we're adding undocumented props. So I'm trying to see exactly what these additional props do.

Let's take `color` for example. I've [forked your fiddle](http://jsfiddle.net/mthmulders/czyc6fqb/2/), removed the `CustomTooltip` (for simplicity) and added a `color` prop to the last data object. If I understood your research correctly, I suppose it should change the color of the _last_ tooltip. But as you can see in that fiddle, it doesn't. Did I misunderstand something?

**Comment by richbai90** [comment]
The color prop and the other custom props are useful really only when using `CustomTooltip`. under the hood it is this prop that sets the color of the text in the tooltip. It uses the `getMainColorOfGraphicItem` function [here](https://github.com/recharts/recharts/blob/master/src/util/ChartUtils.js#L132) to extract the `fill` or `stroke` color depending on whether its a categorical chart or line chart.  To demonstrate [I've updated your fiddle](http://jsfiddle.net/mthmulders/czyc6fqb/2/). It's not the data that sets the color, its the fill prop on the bar element. Without these documented props, I can't color code my custom tooltip the way they do out of the box.

**Comment by richbai90** [comment]
The color prop and the other custom props are useful really only when using `CustomTooltip`. under the hood it is this prop that sets the color of the text in the tooltip. It uses the `getMainColorOfGraphicItem` function to extract the `fill` or `stroke` color depending on whether its a categorical chart or line chart.  To demonstrate [I've updated your fiddle](http://jsfiddle.net/czyc6fqb/4/)

**Comment by mthmulders** [comment]
Thanks again for the info. Let's not await the updated documentation in Recharts and merge this one.

**Review by mthmulders — APPROVED** [review]

**Pull request merged**
