### PR TITLE
[jsonwebtoken] add create*Key as valid inputs

### PR DESCRIPTION
**Pull request by panva**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [[1]](https://github.com/auth0/node-jsonwebtoken/blob/bc28861f1fa981ed9c009e29c044a19760a0b128/sign.js#L116), [[2]](https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L122)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/jsonwebtoken/jsonwebtoken-tests.ts
1. types/jsonwebtoken/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e197933424a90d30f1534ac8a050a34307a5afc3
</p>

**Review by RunAge — CHANGES_REQUESTED** [review]

**Comment by panva** [comment]
@RunAge you're keen on maintaining this whenever `crypto.create*Key` arguments change? e.g. when CryptoKey is added as a valid input? I did it this way very intentionally.

**Comment by panva** [comment]
Furthermore doing the way I proposed also follows the user's @types/node version and so it will naturally provide types that are in the user's actual @types/node and in so the ones available in their' Node.js version.

**Comment by RunAge** [comment]
> Furthermore, keeping the way I proposed also follows the user's @types/node version and so it will naturally provide types that are in the user's actual Node.js version.

same thing, since they come from the same import, is also cleaner and requires less work for the IDE/tsc when the type is not inferred but explicitly provided.

**Comment by panva** [comment]
> > Furthermore, keeping the way I proposed also follows the user's @types/node version and so it will naturally provide types that are in the user's actual Node.js version.
> 
> same thing, since they come from the same import, is also cleaner and requires less work for the IDE/tsc when the type is not inferred but explicitly provided.

That is incorrect. `jsonwebtoken` targets Node.js runtimes long after their EOL, e.g. Node.js 12 is supported. Interfaces like JsonWebKeyInput do not exist in @types/node@12, I stand by this being the correct way given the target node engines.

**Comment by RunAge** [comment]
> > > Furthermore, keeping the way I proposed also follows the user's @types/node version and so it will naturally provide types that are in the user's actual Node.js version.
> > 
> > 
> > same thing, since they come from the same import, is also cleaner and requires less work for the IDE/tsc when the type is not inferred but explicitly provided.
> 
> That is incorrect. `jsonwebtoken` targets Node.js runtimes long after their EOL, e.g. Node.js 12 is supported. Interfaces like JsonWebKeyInput do not exist in @types/node@12, I stand by this being the correct way given the target node engines.

I see your point now and agree. Approved from my side.

**Review by RunAge — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by panva** [comment]
Ready to merge

**Pull request merged**
