### PR TITLE
[node][qs][history] `UnknownFacade` -> `unknown`

### PR DESCRIPTION
**Pull request by OliverJAsh**
Now we support TS 3+ only, we can finally make this change. 🎉 

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Following @orta's [lead](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46238#issuecomment-662151629) here:

> Specifically pinging a few folks from the list above who I've seen around a few times: @eps1lon @SimonSchick @ljharb @RWander @BrunoScheufler

---

I'm getting this error but I don't understand why. It doesn't seem to be related to the change in this PR. It seems I can fix it by renaming the `ts3.1` folder to `ts3.2` ([maybe related to this change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47610)), but I'm not sure if that's the right thing to do? /cc @sandersn 

```
Error in node/v12
AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
    at next (/Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:194:12)
    at Array.map (<anonymous>)
    at /Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:166:92
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)


Error in node/v11
AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
    at next (/Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:194:12)
    at Array.map (<anonymous>)
    at /Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:166:92
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oliverash/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

**Comment by sandersn** [comment]
A few things

1. Hooray for switching to standard `unknown`!
2. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47645 removes ts3.1/, so this PR should probably wait until that's in -- it might make this one a bit simpler, but you'll definitely have to modify files in ts3.4/ instead.
3. I don't know exactly what causes the error you see, but I saw it while producing #47645; it seemed to happen whenever I had broken relative references like `../ts3.1/process.d.ts` (after deleting process.d.ts) or maybe duplicate files (eg both ts3.1/process.d.ts and ./process.d.ts).

**Comment by OliverJAsh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47645 is merged. I merged `master` into this PR.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## qs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/qs@latest/))
was missing the following properties:
1. formats
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 03a9f1d37d698bf8f95885ff49ff15e3c6083954
</p>

**Review by sandersn — APPROVED** [review]

**Review by ExE-Boss — APPROVED** [review]

**Comment by OliverJAsh** [comment]
Ready to merge

**Pull request merged**
