### PR TITLE
Update react-day-picker.d.ts

### PR DESCRIPTION
**Pull request by davidlipo**
Upgrade following some breaking changes in react-day-picker 2.0

https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by mhegazy** [comment]
@gpbl and @jkillian any comment?

**Comment by gpbl** [comment]
LGTM! 
There are some new props tough, added between v 2.0 and 2.3 :)

**Comment by JKillian** [comment]
:+1: ! @davidlipo, feel free to add in the other new props if you have a chance before this merges

**Comment by davidlipo** [comment]
Added in the rest. How does that look?

**Comment by gpbl** [comment]
👍

**Pull request merged**
