### PR TITLE
First start of implementation for a openlayers 3 typescript definition file

### PR DESCRIPTION
**Pull request by woutergd**

### CODE REVIEW

**Comment by vvakame** [comment]
*openlayers3/openlayers3.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/openlayers3
  * http://bower.io/search/?q=openlayers3
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (openlayers3/openlayers3-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@woutergd thank you for your contributions.
please rename openlayers3/openlayers3.d.ts to openlayers/openlayers.d.ts

**Comment by woutergd** [comment]
@vvakame I made it on purpose a separate library as the definitions of openlayers 2 (the current type definitions on openlaayers/openlayers.d.ts) and openlayers 3 are completely different. Is there a way to preserve the openlayers 2 typescript definitions or is it 'useless' to keep these older definitions? 

About the tests, I will add them but the documentation about that in the contribution guide was quite short (and this is my first contirbution to this repo), do I need to add a test for every function and definition or just per class a test that covers most of it?

**Comment by vvakame** [comment]
@woutergd you should rename openlayers/openlayers.d.ts to openlayers/openlayers-2.10.0.d.ts and openlayers3/openlayers3.d.ts to openlayers/openlayers.d.ts. http://definitelytyped.org/guides/contributing.html#version

If you can write test per function, it would be great :+1: . but it is very hard. I'm glad when something is such that in the review of the help of the next pull request.
http://definitelytyped.org/guides/contributing.html#tests

**Comment by woutergd** [comment]
@vvakame  As you can see, I have moved the openlayers definitions into the correct folder and added tests. Took a couple commits as I forgot to update also the definitions, hope that doesn't matter (I ran the tests locally also before committing, just made a couple mistakes when committing). I will extend the tests in the future, but added for now some basic testing functionality with the core functionality of openlayers, for some classes more extensive as those are easier to test, for others also definitions from other parts are missing so this need to be extended before I can test those completely.

**Comment by vvakame** [comment]
@woutergd great works! thanks mate.

**Pull request merged**
