### PR TITLE
[react-bootstrap] Add bsSize property

### PR DESCRIPTION
**Pull request by r3nya**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ToggleButton.js#L53, https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ToggleButtonGroup.js#L87
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

## Context

Issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25592

### CODE REVIEW

**Comment by r3nya** [comment]
This PR for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25592.

Btw, @octatone I noticed that I can use all props from `Button` or `ButtonGroup`. Maybe I need to use something like this:

`lib/ToggleButton.d.ts`
```js
import * as React from 'react';
import { Button } from 'react-bootstrap';

declare namespace ToggleButton {
    export interface ToggleButtonProps extends React.HTMLProps<ToggleButton>, Button {
        checked?: boolean;
        name?: string;
        value: number | string;
        bsSize?: Sizes;
    }
}
declare class ToggleButton extends React.Component<ToggleButton.ToggleButtonProps> { }
export = ToggleButton;
```

But I don't know. WDYT?

**Comment by aaronbeall** [comment]
> But I don't know. WDYT?

Yes, I think you're right: `ToggleButton` should inherit props from `Button`, and `ToggleGroup` should inherit props from `ButtonGroup`.

**Comment by r3nya** [comment]
Hey @aaronbeall, I've update it. Please review ;)

**Review by aaronbeall — APPROVED** [review]

**Comment by aaronbeall** [comment]
@r3nya Looks great to me! 👍

**Pull request merged**
