### PR TITLE
Added 'temp'.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Definitions for https://www.npmjs.com/package/temp.

### CODE REVIEW

**Comment by horiuchi** [comment]
@DanielRosenwasser Thanks mate!

**Comment by DanielRosenwasser** [comment]
No problem - thanks for pulling it in!

**Comment by aeisenberg** [comment]
Small problem here. Apologies for not finding this earlier.  The `track` method should take an optional boolean, like this:

    export function track(value?: boolean): typeof temp;

So, missing a `?` on line 20.

**Comment by aeisenberg** [comment]
And, it's `mkdir` not `mkDir`

**Comment by DanielRosenwasser** [comment]
Hey @aeisenberg, I have a fix in #7247.

**Pull request merged**
