### PR TITLE
highcharts: Apply new lint rules

### PR DESCRIPTION
**Pull request by ghost**
New rules added by #15482

### CODE REVIEW

**Comment by Schmu** [comment]
Since that change we get the following error:
"TS2497: Module .../@types/highcharts/highcharts-more resolves to a non-module entity and cannot be imported using this construct."

We imported it as following:
import * as highchartsMore from 'highcharts/highcharts-more';

Do you have any idea what happened here?

Thanks in advance

**Comment by andy-ms** [comment]
`node -p 'require(\"highcharts/highcharts-more\")'` is a function, so `export =` is correct and `export default` is wrong (that would be an object with a `default` property). You probably need [`import highchartsMore = require("highcharts/highcharts-more");`](http://www.typescriptlang.org/docs/handbook/modules.html), or [`--allowSyntheticDefaultImports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by Schmu** [comment]
But I guess the problem is that with ES6 this is not working. 
And the allowSyntheticDefaultImports can not be setted for the gulp-typescript plugin.

The interesting stuff is, that with "export default HighchartsMore;" instead of "export = HighchartsMore;" everything seems to be running without problems...

**Comment by andy-ms** [comment]
Your module loader must be automatically injecting a default import. I would make an issue with gulp-typescript if it doesn't work with `allowSyntheticDefaultImports`.

**Pull request merged**
