### PR TITLE
added referrerpolicy to anchor tag in react types

### LINKED ISSUE #33226: [@types/react] HTML Anchor is missing `referrerPolicy` attribute
The `referrerPolicy` was added in https://github.com/facebook/react/issues/7263. But type definitions are missing them:
```tsx
<a href="/link" referrerPolicy="no-referrer">link</a>
```
yields an error:
```
Property 'referrerPolicy' does not exist on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'
```

### PR DESCRIPTION
**Pull request by saranshkataria**
Had sent this in as #33287 but the bot closed it due to inactivity even though tests were not failing because of my changes

Fixes #33226
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by saranshkataria** [comment]
@sandersn could you let me know what I should do to get this fixed? The last PR was closed because of Travis failing too. The log says "The job exceeded the maximum time limit for jobs, and has been terminated." which I don't think is related to this change

**Review by ferdaber — APPROVED** [review]

**Comment by sandersn** [comment]
The problem is just that we need to compile all 527 dependents of React to make sure nothing has broken, and the test *almost* gets all 527 -- it looks like the last 10 or so were remaining when Travis' hour limit expired. React and node both consistently hit this problem. 

I may need to try switching CI over to Azure devops, because I don't think Travis' hour limit is negotiable, and  I think I've exhausted the tweaking I can do to make Typescript itself run faster. Of course, other ideas are welcome. In the meantime, you can run `npm run test` locally and report back on the results. @ me again afterward and I'll merge despite the Travis failure.

**Comment by saranshkataria** [comment]
@sandersn tested it locally. All tests pass

**Comment by Jessidhia** [comment]
@sandersn the idea to make it run faster is to use a separate job per typescript version, with the matrix feature, instead of having dtslint itself download and manage all typescript versions. That helps when working locally, but it'd be good to have a CI mode that runs only the specific typescript version that was requested.

This problem is only going to get bigger with time. Switching providers so the build is allowed to last longer than 50min just feels like a workaround.

**Comment by sandersn** [comment]
@Jessidhia Right now, only react compiles with multiple typescript versions. Dependents of react only compile with typescript@next. So we wouldn't save much time by splitting different versions into different jobs.

I agree that switching from a 50-minute limit to a 360-minute limit is a workaround, but it's the only thing I've thought of so far.

**Pull request merged**
