### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by gperdomor**
adding missing waitForConnect

### CODE REVIEW

**Review by rogierschouten — CHANGES_REQUESTED** [review]
Hi, thanks for this PR.  I have two comments:

1)  The return type varies depending on whether you pass a callback or not. Is there a reason not to reflect this in the typings like so?

waitForConnect(): Promise<void>;
waitForConnect(cb...): void

2) Please add a test for the new method

**Comment by gperdomor** [comment]
please review again please @rogierschouten

**Comment by rogierschouten** [comment]
@gperdomor that's not what I meant. If you pass in a callback then the method returns void. If you don't pass in a callback, the method returns a promise. Instead, you changed the return type of  the callback. 

If I'm mistaken as to how the interface works, let me know

**Review by rogierschouten — CHANGES_REQUESTED** [review]
See my latest comment

**Pull request closed without merging**
