### PR TITLE
[qunit] [ember-qunit] Add module for qunit

### PR DESCRIPTION
**Pull request by jamescdavis**
*Note: this PR is a continuation of work done by @rwjblue in #47702.*

*Note: hide whitespace changes highly recommended when viewing the diff: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47731/files?diff=unified&w=1*

QUnit provides a commonjs export of the QUnit global, which can be used as:

```js
import * as QUnit from 'qunit';
```

In order to make this change, we need to refactor how `ember-qunit` augments the QUnit types to augment the global `QUnit` interface rather than the `qunit` module.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/qunitjs/qunit/blob/3e4229d8f837c71a9bec3a82e0602a266b6e5240/src/export.js#L17-L23
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember-qunit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember-qunit@latest/))
was missing the following properties:
1. name
1. init
1. included
1. targetOptions
1. contentFor

<details>
<summary>as well as these 3 other properties...</summary>
<p>treeForVendor, treeForAddonTestSupport, setTestGenerator</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7ef7ef7fea51fb3489e889603faf5c8080535f44
</p>

**Review by dfreeman — APPROVED** [review]
Looks great to me. Thanks for your work @jamescdavis and @rwjblue!

**Review by dfreeman — APPROVED** [review]

**Comment by jamescdavis** [comment]
Ready to merge

**Comment by jamescdavis** [comment]
Also published [`@types/quint@2.9.2`](https://www.npmjs.com/package/@types/qunit).

**Pull request merged**
