### PR TITLE
Add `editorKey` and `textDirectionality` props to `draft-js`

### PR DESCRIPTION
**Pull request by bensalilijames**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://draftjs.org/docs/api-reference-editor.html#textdirectionality
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by benhjames** [comment]
Looks like Travis is failing due to unrelated package (`@testing-library/vue`)

**Review by MunifTanjim — APPROVED** [review]
Look good :tada: Thanks @benhjames

**Comment by MunifTanjim** [comment]
Travis is failing because of this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37655#issuecomment-522041173

Maybe @sandersn can help?

**Comment by sandersn** [comment]
Invalidated Travis' cache again (grrr) and restarted the CI run.

**Pull request merged**
