### PR TITLE
[@types/react-native-auth0] update typing's for exchange() and refreshToken() responses

### PR DESCRIPTION
**Pull request by walterholohan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://auth0.com/docs/api/authentication?javascript#refresh-token
https://auth0.com/docs/api/authentication?javascript#authorization-code-flow-with-pkce46

### CODE REVIEW

**Review by NickGProcopiou — APPROVED** [review]

**Comment by sandersn** [comment]
master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

**Comment by walterholohan** [comment]
Hey, @ascariandrea @marknelissen @leoafarias @willdady @Bogidon this PR is ready for re-review

**Comment by walterholohan** [comment]
> master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

Thanks, @sandersn, this PR is ready to be merged

**Comment by walterholohan** [comment]
@ascariandrea @marknelissen @leoafarias @willdady @Bogidon @sandersn can one of you guys have a look at the PR? Thank you

**Review by ascariandrea — APPROVED** [review]

**Comment by walterholohan** [comment]
Ready to merge

**Pull request merged**
