### PR TITLE
add definitions for koa #4796

### PR DESCRIPTION
**Pull request by jkeylu**
add definitions for koa #4796

### CODE REVIEW

**Comment by vvakame** [comment]
please rename koa/koa-test.ts to koa/koa-tests.ts

**Comment by tuhoojabotti** [comment]
Seems good!

**Comment by vvakame** [comment]
@jkeylu sorry, please resolve conflict.

**Comment by jkeylu** [comment]
@vvakame done

**Comment by amcdnl** [comment]
@jkeylu any plans to do the others like `koa-body-parser` ?

**Comment by jkeylu** [comment]
@amcdnl yes, I am working on `koa-router`

**Comment by urossmolnik** [comment]
The problem with definition is that it is impossible to do module augmentation on it.
https://github.com/Microsoft/TypeScript/issues/6722

koa-bodyparser would need to augment Koa.Request for example (add body).

@jkeylu am I missing something and there is a way to augment module?

**Comment by coderfox** [comment]
:+1: I also want to know how to do module augmentation.

This code fails:

```typescript
// koa-views.d.ts
export var dummy: number; // <-- this means you are now in an ES6 module
declare module "koa" { // <-- which means that you can extend other ES6 modules
  namespace Koa {
    export interface Context {
      render(view: string, data: any): Promise<void>;
    }
  }
}
```

With error `tsd/koa-views.d.ts(4,15): error TS2665: Module augmentation cannot introduce new names in the top level scope.`

While this also fails with the same error:

```typescript
// koa-views.d.ts
declare module "koa-views" {
  export var dummy: number; // <-- this means you are now in an ES6 module
  module "koa" { // <-- which means that you can extend other ES6 modules
    namespace Koa {
      export interface Context {
        render(view: string, data: any): Promise<void>;
      }
    }
  }
}
```

**Pull request merged**
