### PR TITLE
Add loading spinner props to react-native-elements ButtonProps

### PR DESCRIPTION
**Pull request by awinograd**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://react-native-training.github.io/react-native-elements/API/buttons/
- [x] Increase the version number in the header if appropriate. **n/a**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **n/a**

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@awinograd Please fix the failures indicated in the Travis CI log.

**Comment by awinograd** [comment]
Hi @RyanCavanaugh, I'm not sure how I could have caused the jenkins failure. Can you point me in the right direction?

> Error: mock-knex depends on knex but has a lower required TypeScript version.

I get that locally running `npm test` on `master`

**Comment by andy-ms** [comment]
Hi @awinograd, that was fixed in a different PR. See updated failure messages -- just a few lint errors.

**Comment by awinograd** [comment]
@andy-ms i've rebased on master (to get the fix in #21384) and have fixed the lint errors

**Comment by awinograd** [comment]
Merge conflict fixed. Ready for re-review

**Pull request merged**
