### PR TITLE
[tapable] Fix .tapX() options, .taps types, add .isUsed()

### PR DESCRIPTION
**Pull request by opl-**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/tapable/blob/tapable-1/lib/Hook.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by opl-** [comment]
Wanted to take a little more time to test and consider more changes, but ended up being busy. Marking as ready for review for now and will open a new PR if I decide to make any other changes.

**Comment by sandersn** [comment]
tapable is relied on by so much code that I don't want to merge this without reviews from both @e-cloud and @johnnyreilly.

**Comment by opl-** [comment]
I should perhaps mention that after submitting this PR i discovered [the official typings for tapable 2 in their repository](https://github.com/webpack/tapable/blob/ffc660840d2814b00a3e5e00cecb09519136bd37/tapable.d.ts) and I feel that they are far better, but they'd be incompatible with the current typings Definitely Typed provides, while the ones I submitted here aim to be fully backwards compatible.

That being said, the option of backporting them to Definitely Typed or the official tapable 1.x releases could be worth exploring. Any thoughts?

**Comment by andrewbranch** [comment]
We shouldn’t copy v2 typings into DefinitelyTyped if they’re maintained elsewhere. This PR is strictly in maintenance of v1, right? Thanks for your patience with the holidays @opl-.

**Comment by opl-** [comment]
I wasn't suggesting copying the v2 typings into DefinitelyTyped to be used for tapable v2. I was suggesting porting the v2 typings to be compatible with tapable v1 and using those for v1 instead, as they're more flexible.

**Comment by RyanCavanaugh** [comment]
@opl- how would you like to proceed with this PR? I'm flexible

**Comment by opl-** [comment]
I opened a new issue for my question, as I should've done from the very beginning. Let's just treat this PR as a PR and handle the question in #41380 instead.

**Pull request closed without merging**
