### PR TITLE
Add missing strategy options to StrategyOptionsBase typing

### PR DESCRIPTION
**Pull request by daphnesmit**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js>

### CODE REVIEW

**Review by EduardoAC — APPROVED** [review]
Well done @daphnesmit

**Comment by EduardoAC** [comment]
@daphnesmit the Github update got stuck perhaps you can try to re-trigger the build

**Comment by daphnesmit** [comment]
> @daphnesmit the Github update got stuck perhaps you can try to re-trigger the build

Yeah I have no clue how tho hahah!

**Comment by EduardoAC** [comment]
Yep, we need to ask the maintainer for merging since there are the only ones with permissions if Travis fail :(

**Comment by RyanCavanaugh** [comment]
Interesting failure mode today; Travis reports the build as green if you click through, but isn't pushing through the status to GitHub correctly. Merging!

**Comment by EduardoAC** [comment]
@RyanCavanaugh Thanks for your assistance, my guess is a problem with the webhook with Travis but hard to know fully

**Pull request merged**
