### PR TITLE
add inferred parameters in createAction for redux-actions

### PR DESCRIPTION
**Pull request by pocesar**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.

also added tslint.json and fixed lint errors according to the update-to-date best practices

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Thank you very much for the PR. I'm wondering if there's a better way to name `Function0` and friends? Maybe `ActionFunction0` or something else a little bit less ambiguous?

**Comment by pocesar** [comment]
yeah sure, why not?

**Comment by pocesar** [comment]
went ahead and also added a `combineActions` test and better parameters for it

**Comment by alexgorbatchev** [comment]
Great job, thank you! 👍

**Comment by horiuchi** [comment]
@pocesar Thanks!

**Pull request merged**
