### PR TITLE
mui-datatables: Extra types for subcomponents + Updated for lib updates

### PR DESCRIPTION
**Pull request by favna**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: This covers various changes as listed below
  - https://github.com/gregnb/mui-datatables/pull/469
  - https://github.com/gregnb/mui-datatables/pull/314
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

It should be noted that I purposely used the large amount of `any` in the subcomponent type definitions as they are not documented in the library's README (where all other documentation resides) nor are they properly documented through React's PropTypes. I had to do a lot of guessing and so I figured going for `any` and `?:` (optionals) was the safest way to do so. If someone else could really thoroughly delve into the library and properly type the subcomponents that would be very much appreciated. Or maybe the library creator @gregnb could come through for us and describe all the `props` of all the subcomponents. I am also tagging @gabejohnson here as he requested types for the subcomponents in #32591

### CODE REVIEW

**Comment by Favna** [comment]
@ maintainers: Please hold off on merging this until I give the greenlight. I have just come to realise I made some big mistakes concerning the exporting of the subcomponents but I cannot fix it right at this moment.

**Comment by gabejohnson** [comment]
@Favna you can edit the title of the PR to prepend "WIP". This will prevent anyone from merging it.

**Comment by cwbuecheler** [comment]
@Favna - I'm running into an issue with the typings. It looks like `customFooter` in the `MUIDataTableOptions` interface should be capable of taking some arguments. Specifically used in `TableFooter.js`:

```
? options.customFooter(rowCount, page, rowsPerPage, changeRowsPerPage, changePage)
```

But the typing seems to expect an empty function:

```
customFooter?: () => React.ReactNode;
```

I solved this locally in the following manner, but am unsure it's the best solution because I'm still new to TS:

```
  customFooter?: (
    rowCount: number,
    page: number,
    rowsPerPage: number,
    changeRowsPerPage: () => any,
    changePage: number,
  ) => React.ReactNode;
```

Is this something you could look into while you're updating this PR? Am I missing something obvious? If I try to run this code without my updated typings, I get a TS error about `rowCount`:

```
const paymentsTableOptions = {
  customFooter: (rowCount: number) => {
    return (
      <tr>
        <td>count: {rowCount}</td>
      </tr>
    );
  },
};
```

Thanks for doing this, btw!

**Comment by Favna** [comment]
This PR is now ready to be merged

I have also addressed @cwbuecheler's feedback and included the suggested changes, which I also confirmed to be correct with the libraries' code.

**Comment by cwbuecheler** [comment]
@Favna - awesome, thanks!

**Pull request merged**
