### PR TITLE
Add some Methods and Interfaces into types/google-apps-script/apis/peopleapi_v1.d.ts

### PR DESCRIPTION
**Pull request by luthpg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/people/api/rest?hl=ja
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by mtgto — COMMENTED** [review]
Thank you for your contribution.
Could you please tell me how you obtained this type definition so that I can review this pull request easily?

As described in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70875/#issuecomment-2408590629, could you write tests for some methods? This repository does not allow to merge pull request without unit test even if I, one of a maintainer of this type definition, approve it.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/google-apps-script/test/google-apps-script-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ff43f0ec8947465c38dbeb4a529b012193875322
</p>

**Comment by luthpg** [comment]
@mtgto 
Thank you for checking.
For the methods, I referred to the auto-completion in the AppsScript editor and the [official document](https://developers.google.com/people/api/rest/v1/people), and for the Interfaces, I referred to the [Node.js SDK repository](https://github.com/googleapis/google-api-nodejs-client/blob/main/src/apis/people/v1.ts) to align them with other predefined types.

**Review by mtgto — APPROVED** [review]
LGTM. Thank you for the conrtib.

> For the methods, I referred to the auto-completion in the AppsScript editor and the [official document](https://developers.google.com/people/api/rest/v1/people), and for the Interfaces, I referred to the [Node.js SDK repository](https://github.com/googleapis/google-api-nodejs-client/blob/main/src/apis/people/v1.ts) to align them with other predefined types.

I didn't know `googleapis/google-api-nodejs-client` existed, but that's a good idea to refer to it 👍 
Thanks for letting me know.

**Comment by luthpg** [comment]
Ready to merge

**Pull request merged**
