### PR TITLE
Add support for reset keys in react-navigation

### PR DESCRIPTION
**Pull request by andrewlinfoot**
See https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L204-L209

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by huhuanming** [comment]
Need to provide a URL to documentation or source code which provides context for the suggested changes.
thx 😳

**Comment by huhuanming** [comment]
the source code link or capture

**Comment by andrewlinfoot** [comment]
I linked to react-navigations flow types file. Does that work?

I'm going to close and reopen this PR anyway because it need to fix it to support `null` and `undefined` but want to know if the link to the Flow types file will work for my next PR?

**Comment by huhuanming** [comment]
It's okay.
The link is the evidence to support changes.

**Pull request closed without merging**
