### PR TITLE
Fix MakeDirectoryOptions for node 12

### PR DESCRIPTION
**Pull request by simhnna**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_mkdir_path_options_callback
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by yoursunny — APPROVED** [review]

**Review by Flarna — CHANGES_REQUESTED** [review]
Please update also /types/node/fs.d.ts

**Review by ExE-Boss — APPROVED** [review]
There should probably be a documentation on the expected string format somewhere.

**Comment by simhnna** [comment]
I found out node 11 types were also wrong. The format isn't documented in the nodejs api docs. It only mentions the default value

**Review by Flarna — APPROVED** [review]
Usually there is no need to adapt EOL versions like node 11 but it's not wrong either.

**Review by galkin — APPROVED** [review]

**Comment by simhnna** [comment]
I'm not sure why the tests are failing. It doesn't appear to be anything related to my changes. Anyone got any ideas?

**Comment by Flarna** [comment]
I think there was some issue because 3.9. Maybe it was fixed meanhwhile. Try to rebase or merge master. This should retrigger CI.

**Comment by peterblazejewicz** [comment]
> Anyone got any ideas?

You should be able to run local npm test now to verify status and push update (or push empty commit) to restart CI:
microsoft/TypeScript#37610

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
