### PR TITLE
[Ramda] includes missing #30917

### PR DESCRIPTION
**Pull request by jottenlips**
Please fill in this template.
#30917
- [Y] Use a meaningful title for the pull request. Include the name of the package modified.
- [Y] Test the change in your own code. (Compile and run.)
- [Y] Add or edit tests to reflect the change. (Run with `npm test`.)
- [Y ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [Y] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [Y] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [Y] Provide a URL to documentation or source code which provides context for the suggested changes: https://ramdajs.com/docs/#includes
- [N] Increase the version number in the header if appropriate. (already on v 25)
- [N] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by googol — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

It looks to me that this would be possible with this type definition:

```
R.includes(8, 'banana')
```

We probably don't want that, we'd like for target to be a string when the list is a string (ofc if the target is a string, then also an array of strings is a valid list). Could you separate out a specialized version for this case?

**Comment by googol** [comment]
That's better! There's just one more case that needs to be addressed, which is that when the first parameter is a string, the second one can be an array of strings too. Like so:
```
R.includes('ba', 'banana') // => true
R.includes('ba', ['ba', 'na', 'na']) // => true
```
([ramda repl](https://goo.gl/cSFBLW))

**Comment by jottenlips** [comment]
@googol should be good to go

**Review by googol — APPROVED** [review]
Perfect! Good to merge!

**Pull request merged**
