### PR TITLE
Enable strictFunctionTypes

### PR DESCRIPTION
**Pull request by jablko**
```Shell
sed --in-place /strictFunctionTypes/s/false/true/ $(git ls-files '*/tsconfig.json')
```

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by krishnaglick** [comment]
I'm going to be the first here and say, this not pass CI.
Changing something like this, should in theory, require code changes. But I might be wrong.

**Comment by chriskrycho** [comment]
Can you provide context on *why* you're making this change? I'll need to review in detail to see how it impacts the Ember types, but we disabled this a long time ago because some of our type safety for old Ember stuff *cannot* be appropriately covariant/contravariant (known limitations in the type system which can't cover it).

**Review by SimonSchick — APPROVED** [review]
- CI passed
- No code changes
- Won't affect consumers (due to no code changes)
Don't see the problem with this.

**Comment by Serabe** [comment]
This code modifies several different packages. Even if I'm a maintainer of one of them, I cannot approve this knowing this might not be wanted for some of them. Please, if you are interested in this change, submit a PR for each package you want to submit. Also, as this changes how types are resolved, explain what is the limitation you are hitting for each of them.

Thank you and have a nice day!

**Comment by jgonggrijp** [comment]
@sandersn @sheetalkamat Drawing your attention because I think this PR reveals a leak in the review system. @jablko changed the `tsconfig.json` of 65 packages. He did *not* test all of the changes in his own code (which is understandable given the large number of packages involved). Only one of the maintainers did a formal review, which happened to be an approval. A few other maintainers expressed concerns in human language, which typescript-bot doesn't detect. The PR then got merged automatically because of this single approval. 

@krishnaglick @chriskrycho @Serabe I think that as long as the review system works this way, we need to err on the side of caution and leave a formal "request changes" to prevent typescript-bot from automatically moving this into the "OK humans, you can safely merge this" queue.

**Comment by SimonSchick** [comment]
Changes could've been requested, but the fact that they weren't makes me think there really wasn't a problem here in the first place, at least not with this particular PR.

**Comment by joeflateau** [comment]
> Changes could've been requested, but the fact that they weren't makes me think there really wasn't a problem here in the first place, at least not with this particular PR.

The problem is nobody else had a chance to review. You approved it 2 hours after it was submitted. PR's should require sign off from each affected package, not a PR affecting 65 packages that is approved because of an approval by 1 package maintainer.

**Comment by chriskrycho** [comment]
Yeah, I will in the future just file a Changes Request review preemptively on a change like this. I didn't because I didn't assume that it would be auto-merged by a TS maintainer after only one package maintainer had signed off when others had objected.

I also just typed up almost exactly what @joeflateau said but he posted it in the time I was typing, so I'll just loudly second his comment:

> PR's should require sign off from each affected package, not a PR affecting 65 packages that is approved because of an approval by 1 package maintainer.

**Comment by joeflateau** [comment]
Just for absence of doubt here: I don't think you (@SimonSchick) did anything wrong. It's a process problem.

**Comment by SimonSchick** [comment]
Also @sheetalkamat was the PR merged 'automatically' or were the contents actively reviewed before merge? I'm assume the latter is the case.

@joeflateau I can agree on this tho, a rule that'd require at least 2 contributors to sign off if more than ~10 packages are affected makes sense to me.

On the other hand I'd be vary to increase the required review count as it could cause even more PRs to get stuck than before which might slow down DT as a whole and might discourage further contributions 😕.

So if such a rule was to be introduced we'd need to be rather conversative, example:

- 2 required signoffs on X or more packages affected (see above).
- Auto dismissal of PR disapprovals after a set time to prevent PR lockup due to reviewer inactivity  and the chance of other approvers overriding inactive ones.
- Potential manual sign-off by DT maintainers at a certain size (assuming this isn't the case already).

**Comment by chriskrycho** [comment]
@SimonSchick I actually think that unless it's a TS maintainer introducing changes, *very few if any* changes should affect (just hypothetically :joy:) the tsconfig values for 65 separate packages.

Most of us who maintain these types do so as either side work or some small fraction of our jobs, and these kinds of changes can have ecosystem-wide impacts. It's not going to be obvious to most contributors *why* the configurations for any given package have the rules they do. *Maybe* it's because they just haven't been updated… or *maybe* (as in our case) it's because there was a *very* good reason for them to be set the way they were. As it is, I now need to make time today to go see what if any damage has been done in the Ember TS ecosystem as a result of this change, and possibly take the time to file a revert for our packages—and introduce more tests if so to boot.

Moreover, when TS maintainers have introduced changes like this, they've usually gone out of their way to (a) proactively reach out to the maintainers of the affected types and (b) give them a good while to bake. They do that precisely *because* they recognize all the dynamics I just highlighted.

**Comment by jgonggrijp** [comment]
@SimonSchick I want to chime in with everyone else that I believe you were acting with best intentions and that you only did what you're supposed to do. You can act in exactly the same way next time, as far as I'm concerned.

> Also @sheetalkamat was the PR merged 'automatically' or were the contents actively reviewed before merge? I'm assume the latter is the case.

The contents were actively reviewed, *by you*. This is how the system works.

There are thousands of DT package and the turnover of issues and PRs is *huge* (as evidenced by the PR number). The DT team is pretty small in comparison. They need checkboxes, typescript-bot, `@mention`s etcetera to keep up with all of it. They work with a queue of PRs that have already passed all the checks and are ready to merge, which this PR ended up in because there was a single approving review. If I were @sheetalkamat, I wouldn't want to read every PR in the merge queue in detail but just try to work through them as fast as possible so I could focus on other issues and PRs that demanded my attention. Also keep in mind that the PR title doesn't include any warning about it affecting 65 packages. In any case, I think she isn't to blame, either.

> 
> @joeflateau I can agree on this tho, a rule that'd require at least 2 contributors to sign off if more than ~10 packages are affected makes sense to me.
> 
> On the other hand I'd be vary to increase the required review count as it could cause even more PRs to get stuck than before which might slow down DT as a whole and might discourage further contributions 😕.

I have no statistics ready, but my impression about stuck PRs is that they're usually stuck for a good reason. In any case, I think this is a clear case where merging happened *too fast*. I agree with everyone else here that this is due to a process problem.

**Comment by sheetalkamat** [comment]
After typescript-bot tags the PR as being approved by one of the reviewers, we normally glance through it to check if the change seems reasonably . Since it was just config change without any failures, I had merged it.. In future if PR needs more approvals, please mark it as Changes requested or leave comment that is easy to find when glancing through so we can mark it accordingly. Sorry if this has broken someone. If this change is not correct, feel free to file PR to revert the change or fix the issue that it reveals. Thanks

**Pull request merged**
