### PR TITLE
Delete react-editext as-of v4.0

### PR DESCRIPTION
**Pull request by alioguzhan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/alioguzhan/react-editext/blob/master/CHANGELOG.md
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by AviVahl** [comment]
The original package is now written in typescript. It might already contain built-in typings, which would mean the types package can be removed...

**Comment by alioguzhan** [comment]
> The original package is now written in typescript. It might already contain built-in typings, which would mean the types package can be removed...

Yes. No need to update here since the original package already has typings. But I would like to keep existing type definitions instead of removing them. Because if any user prefers to use an older version of the package they will need type definitions anyway. What do you think? @AviVahl

**Comment by AviVahl** [comment]
Not my call, heh. I'm an upgrade freak, so for the sake of simplicity I usually lean toward removal.

Even after removal from `DefinitelyTyped`, the existing `@types/react-editext` releases would still be available for those who'd like to stay on a previous major. Leaving the types package around is justified, imo, in cases which you'd like to update/maintain those typings. For a small library, like this case, I don't see a huge benefit.

**Comment by alioguzhan** [comment]
That makes sense. Ok then. Let's remove this...

**Comment by AviVahl** [comment]
Check out the details in https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by alioguzhan** [comment]
Done. And thanks for the guidance @AviVahl

**Pull request merged**
