### PR TITLE
Update hellojs.d.ts

### PR DESCRIPTION
**Pull request by lordgreg**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

.init method, which, in your case uses `HelloJSLoginOptions` as param, from HelloJS also has option to overwrite the popup parameters of window.

### CODE REVIEW

**Comment by vvakame** [comment]
dup #8304

**Comment by lordgreg** [comment]
@vvakame this isn't duplicate! check my updates in commited file.

**Comment by vvakame** [comment]
oh, sorry.

**Comment by mhegazy** [comment]
@lordgreg can you fix the failing CI tests.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
