### PR TITLE
express-serve-static-core: add support for custom locals

### PR DESCRIPTION
**Pull request by OliverJAsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: http://expressjs.com/en/api.html#app.locals and http://expressjs.com/en/api.html#res.locals
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
I don't see how the build errors are related to this change?

```
Error in i18n
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/i18n/i18n-tests.ts:110:13
ERROR: 110:13  expect  TypeScript@next compile error: 
Argument of type '(request: Request, response: Response, next?: () => void) => void' is not assignable to parameter of type 'RequestHandlerParams'.
  Type '(request: Request, response: Response, next?: () => void) => void' is not assignable to type '(RequestHandler | ErrorRequestHandler)[]'.
    Property 'push' is missing in type '(request: Request, response: Response, next?: () => void) => void'.
ERROR: 113:16  expect  TypeScript@next compile error: 
Argument of type '(_req: Request, res: Response) => void' is not assignable to parameter of type 'RequestHandlerParams'.
  Type '(_req: Request, res: Response) => void' is not assignable to type '(RequestHandler | ErrorRequestHandler)[]'.
    Property 'push' is missing in type '(_req: Request, res: Response) => void'.
ERROR: 158:16  expect  TypeScript@next compile error: 
Argument of type '(_req: Request, res: Response) => void' is not assignable to parameter of type 'RequestHandlerParams'.
  Type '(_req: Request, res: Response) => void' is not assignable to type '(RequestHandler | ErrorRequestHandler)[]'.
    Property 'push' is missing in type '(_req: Request, res: Response) => void'.
ERROR: 195:16  expect  TypeScript@next compile error: 
Argument of type '(_req: Request, res: Response) => void' is not assignable to parameter of type 'RequestHandlerParams'.
  Type '(_req: Request, res: Response) => void' is not assignable to type '(RequestHandler | ErrorRequestHandler)[]'.
    Property 'push' is missing in type '(_req: Request, res: Response) => void'.
```

**Review by MichalLytek — CHANGES_REQUESTED** [review]
This change breaks a lot of express app. Empty inteface is not equal to any. Please try add index signature to the interface and check if you can overwrite it later by yourself.

**Comment by OliverJAsh** [comment]
> This change breaks a lot of express app. Empty inteface is not equal to any. Please try add index signature to the interface and check if you can overwrite it later by yourself.

Done!

**Comment by andy-ms** [comment]
`i18n` augments the `Response` interface with `locals: i18nAPI;`, which conflicts with the definition you gave here.

I'm wondering it this PR is the best solution to custom locals -- the custom locals are local to a single app, but by augmenting the interface you're declaring them to exist everywhere. Might be better to cast to a `Response` subtype? Reminds me of #20820.

**Comment by OliverJAsh** [comment]
@andy-ms Good point. I'll explore using generics in that case!

**Comment by andy-ms** [comment]
@OliverJAsh Unfortunately that will only work in ts2.2 and above and we didn't really think it was worth it since one can use a subtype -- see the comments near the bottom.

**Comment by OliverJAsh** [comment]
@andy-ms How come it wouldn't work in TS versions prior to 2.2?

I didn't realise this could be achieved by subtyping. You're right!

``` ts
interface TypedApplication extends express.Application {
    locals: {
        foo: string;
    };
}

const app: TypedApplication = express();

// $ExpectType string
app.locals.foo;
// $ExpectError
app.locals.notDefined;
```

**Comment by OliverJAsh** [comment]
Ideally these custom types would be merged with the official typings. Here are a few approaches I tried:

``` ts
declare module 'express-serve-static-core' {
  interface Application {
    // Error: Subsequent variable declarations must have the same type.  Variable 'locals' must be of type 'any', but here has type 'CustomLocals'.
    locals: CustomLocals;
  }
}
```

This makes sense. Declaration merging won't allow us to merge two properties of different types.

``` ts
declare module 'express' {
  interface Application {
    locals: CustomLocals;
  }
}
```

This one works, however it is merging with `express.Application`, which is a subtype of `core.Application`—and `core.Application` is the one that is used everywhere, not `express.Application`. So it doesn't get us very far!

Finally I noticed that `core.Application` extends `Express.Application`, where `Express` is a global namespace which is explicitly for the use case of declaration merging:

``` ts
declare global {
  namespace Express {
    interface Application {
      locals: LocalsWithUnsplashNamespace;
    }
  }
}
```

Got there in the end!

**Comment by OliverJAsh** [comment]
In fact, merging with the global `Express.Application` interface won't work either, because `locals` will be overridden to `any` by `core.Application`. Essentially:

``` ts
declare global {
  namespace Express {
    interface Application {
      locals: { foo: string; }
    }
  }
}

// core module
interface Application extends Express.Application {
  locals: any;
}

app.locals.foo // type is `any` because our custom locals are overriden by `core.Application`!
```

@andy-ms I can't find any way of doing this. Can you advise? If this is not possible with the current typings, what changes can we make to help?

**Comment by andy-ms** [comment]
@OliverJAsh Maybe instead of changing the interface you could use a rule like [no-unsafe-any](https://palantir.github.io/tslint/rules/no-unsafe-any/)  to remind you to cast every time you access `locals`?
The reason that solution wouldn't work in ts<2.2 is that the type parameters needed default values for backwards-compatibility (not force people to provide them), but type parameter defaults are only present in ts2.2 and above.

**Comment by OliverJAsh** [comment]
> Maybe instead of changing the interface you could use a rule like no-unsafe-any to remind you to cast every time you access locals?

That would certainly work, although it would be much more noisy than augmenting the type once, either through generics or declaration merging.

Unfortunately generics is not possible until we decide to break backwards compatibility with TS 2.2 (due to support for default generics), and currently declaration merging won't work because of the way the types are set up, as I detailed earlier.

@andy-ms What if we moved the definition of `locals` from `core.Application` to a supertype of `Express.Application`? This way the subtype `Express.Application` would take precedence:

``` ts
// core typings
declare global {
    namespace Express {
        // These open interfaces may be extended in an application-specific manner via declaration merging.
        // See for example method-override.d.ts (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/method-override/index.d.ts)
        interface Request { }
        interface Response { }
        interface FallbackApplication {
          locals: any;
        }
        interface Application extends FallbackApplication { }
    }
}

// in custom code
interface CustomLocals {
  foo: string;
}

declare global {
  namespace Express {
    interface Application {
      locals: CustomLocals;
    }
  }
}
```

``` ts
app.locals.foo // type is `string`
app.locals.notDefined // error
```

If the user does not specify their own `Application` to merge, `app.locals` will be `any`.

**Comment by andy-ms** [comment]
It seems like we should just allow declaring a type for something that was `any` on DefinitelyTyped. See Microsoft/TypeScript#4062

**Comment by OliverJAsh** [comment]
@andy-ms Good suggestion, I'll track that issue.

In the meantime, would a PR for the above suggestion be accepted? If so, I will raise one.

**Comment by andy-ms** [comment]
I'm leaning against it, because this issue affects any interface with an `any` in it and we don't want to start adding a supertype for every one of those. The workaround of creating `MyApplication extends Application` seems like it should work well enough.

**Comment by OliverJAsh** [comment]
I just ran into this again: #27012. Once again, I'm having to patch the types to replace `any` with something that can be overridden/merged. 😒

> The workaround of creating MyApplication extends Application seems like it should work well enough.

This doesn't work for us because we can't always control where we receive an `Application` interface from, and thus we would be required to cast to `MyApplication` every time we receive an `Application` (which is a lot).

Can we implement the solution I proposed here until we get a fix in TS (if/when that happens)?

**Comment by OliverJAsh** [comment]
@andy-ms Did you have any thoughts regarding my last comment? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23169#issuecomment-402085390

**Comment by sandersn** [comment]
@andy-ms moved to the .NET team so I've taken over Definitely Typed from him. I'm afraid I lost the context, though. Is your proposed solution the code change from this PR, or one of the other ideas in the comments? 

It looks like the main obstacle for the code change was a break in i18n. Maybe you can check whether that's still a problem?

**Pull request closed without merging**
