### PR TITLE
change my github name in definitions

### PR DESCRIPTION
**Pull request by ricmello**
Hey guys, I recently changed my github username from `ricardo-mello` to `ricmello` to be easier to type, but I need to change the definitions to point to the new name.

Github already did the redirects so https://github.com/ricardo-mello/DefinitelyTyped now points to https://github.com/ricmello/DefinitelyTyped

Can you please approve these changes?

### CODE REVIEW

**Comment by adripanico** [comment]
If I could, I'll reject this PR right away.

**Comment by ricmello** [comment]
@adripanico could you explain why?

**Comment by lekoaf** [comment]
> @adripanico could you explain why?

- It edits several packages at once
- It seems utterly pointless to release a new version of 4 type definitions just because you changed your username

**Review by amcasey — APPROVED** [review]
In a perfect world, the bot would probably detect this sort of change and skip publishing, but this seems fine.

**Review by orta — APPROVED** [review]

**Comment by ricmello** [comment]
Yeah @amcasey I was wondering about if the bot could skip the publish

But thank you for understanding, and sorry the inconvenience guys 😅

**Comment by ricmello** [comment]
Ready to merge

**Pull request merged**
