### PR TITLE
Moved method scrollToEnd to correct interface

### PR DESCRIPTION
**Pull request by iRoachie**
Moved method scrollToEnd from RecyclerViewBackedScrollViewStatic to ScrollViewStatic

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by alloy — CHANGES_REQUESTED** [review]
This PR changes the indentation from 4 to 2 spaces for the whole file, please refrain from making such whitespace changes and limit to just moving the method around.

**Comment by iRoachie** [comment]
Zzz vscode... Will fix

**Comment by iRoachie** [comment]
@alloy Good now?

**Comment by alloy** [comment]
Can you please undo _all_ changes other than moving the method around?

**Comment by alloy** [comment]
And can you also please squash the commits to a single one so that it’s clear what the exact changes are?

**Comment by iRoachie** [comment]
@alloy Made a new pr #15952

**Pull request closed without merging**
