### PR TITLE
[@types/react-highlight] add innerHTML prop and make all props optional

### PR DESCRIPTION
**Pull request by jplew**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/akiran/react-highlight#syntax-highlighting-of-mutiple-code-snippets
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by jplew** [comment]
@JoshuaKGoldberg 

opening this MR because this code yields the following error:

```
                  <Highlight innerHTML>{marked(readmeContent)}</Highlight>
```

```
Type '{ children: string; innerHTML: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<HighlightProps, any, any>> & Readonly<HighlightProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'innerHTML' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<HighlightProps, any, any>> & Readonly<HighlightProps> & Readonly<{ children?: ReactNode; }>'.ts(2322)
```

This is because the types are missing the `innerHTML` boolean documented here: https://github.com/akiran/react-highlight#syntax-highlighting-of-single-code-snippet

Also, the `className` prop is not mandatory. `<Highlight>`my code snippet`</Highlight>` is perfectly valid.

Please let me know if you have any comments.

**Comment by amcasey** [comment]
@jplew are you still waiting for feedback?

**Comment by jplew** [comment]
yes sir

**Review by rbuckton — APPROVED** [review]

**Comment by jplew** [comment]
thanks a lot! @rbuckton @amcasey

**Pull request merged**
