### PR TITLE
fix(conventional-commits-parser): update flaky tests under TS5.*

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Fixing @types/node failing CI tests under TS5.0.

x-ref: #63201

Thanks!

/cc @Semigradzki

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

### CODE REVIEW

**Comment by Semigradsky** [comment]
Any progress here? 😃

**Comment by peterblazejewicz** [comment]
Requires maintainer, i'll ask on Discord channel

**Review by orta — APPROVED** [review]
Looks reasonable to me 👍🏻

**Comment by peterblazejewicz** [comment]
Ready to merge

**Pull request merged**
