### PR TITLE
Fix the definition of class Note in @Types/VexFlow to address Issue #17023

### PR DESCRIPTION
**Pull request by bgnkim**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Issue #17023 explains the corresponding change
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by bohoffi** [comment]
Hi @nearbydelta first of all thank you for your effort.

But I think that this will not completely work as expected.
Although this will work with `BarNote` it will crash with `Note` if one **does not pass** the parameter when constructing note as of:
```ts
if (!note_struct) {
  throw new Vex.RuntimeError(
    'BadArguments', 'Note must have valid initialization data to identify duration and type.'
  );
}
```
in the `Note` constructor.

@sebastianhaas @rquiring any thoughts on this?

**Comment by rbuckton** [comment]
This looks like the wrong change. Is there a reason you cannot add an appropriate constructor to `BarNote`?

**Comment by nearbydelta** [comment]
@rbuckton No, I just want to fix it by simplest way. Your comment is reasonable, so I fixed them as you proposed. Please review.

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
