### PR TITLE
DataTables Buttons extension types added.

### PR DESCRIPTION
**Pull request by SammyG4Free**
Hey, this is my first time using github and contributing to a project so please point out any mistakes. I'd appreciate any help and feedback!

I added types for DataTables Buttons extension into the existing jquery.dataTables.d.ts file, and added test code. I did not add 100% of the types, but included all the button config options which should cover most use cases. Will add types as needed or as requested to fully support the Buttons extension, and maybe other DataTable extensions as well.

### CODE REVIEW

**Comment by omidkrad** [comment]
I'm not familiar with DataTables Buttons extension. The code looks fine to me but I think any extension/plug-in code should go into their separate definition file instead of adding to `jquery.dataTables.d.ts`.

**Comment by SammyG4Free** [comment]
I would normally agree with you, however in this case the buttons option had to be added into an existing interface in <code>jquery.dataTables.d.ts</code>, specifically the <code>DataTables.Settings</code> interface. 

I am new to typescript, but I am not sure how I would be able to add to an existing interface externally.

**Comment by omidkrad** [comment]
@SammyG4Free it's possible with TypeScript. Just give the interface the same name in the external file. DataTables itself is a JQuery plug-in but it is placed in a separate definition file (see [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.dataTables/jquery.dataTables.d.ts#L13-L15)). See [Declaration Merging](http://www.typescriptlang.org/Handbook#declaration-merging) in TS handbook.

**Comment by SammyG4Free** [comment]
@omidkrad Ok, checked out the documentation and will create a separate .d.ts file. Thanks for the help!

**Pull request closed without merging**
