### PR TITLE
[react-router] Allow numeric and optional router params for generatePath

### PR DESCRIPTION
**Pull request by Rycochet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stackoverflow.com/a/35604855/3328079
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Note: This fixes two things.

Firstly this reverts a regression that used to support any type of primitive data. Previous type definition:

```ts
export function generatePath(
    pattern: string,
    params?: { [paramName: string]: string | number | boolean | undefined },
): string;
```

Secondly this now understands the difference between required and optional path params. This isn't documented properly, although is linked in the stackoverflow answer. Essentially it allows a `?` suffixed param to be optional (as used by [path-to-regexp](https://www.npmjs.com/package/path-to-regexp)), instead of the previous "everything is optional" or the current "everything is required".

Tests are added to check that the optional params are recognised correctly, and that params are allowed to be numbers or booleans in addition to strings.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]

**Comment by eps1lon** [comment]
The errors are likely unrelated since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50405 displays the same errors.

**Review by johnnyreilly — APPROVED** [review]

**Comment by Rycochet** [comment]
Ready to merge

**Comment by apieceofbart** [comment]
hi, one comment, shouldn't this
```
generatePath('/posts/:postId');
```
be an error? I would expect that the second param is required in this case

**Comment by Rycochet** [comment]
> hi, one comment, shouldn't this
> 
> ```
> generatePath('/posts/:postId');
> ```
> 
> be an error? I would expect that the second param is required in this case

There's no colon before it to make it a second param (or technically first as I assume you're meaning `posts`) - that's just a static path part :-)

**Comment by apieceofbart** [comment]
I meant the second param of generatePath function, this will result in runtime error but not in compile error

**Comment by apieceofbart** [comment]
I think we can agree that ideally that would work like this:
```
generatePath("/no/params/here") // no need for the second argument since there are no params in the path
generatePath("/no/required/params/:here?") // no need for the second argument since the param is optional

generatePath("/required/params/:here?") // ERROR, missing second argument
```
I don't know if this is possible to achieve (maybe through function overload) but it would be awesome to have.

**Comment by Rycochet** [comment]
Oooh, that's a good point, I get what you mean! It should only enforce it for any number of non-optional params. I did want to try and unify the interface into a single object rather than `{param} & {param}`, which might have made things easier (but added hundreds of lines of type definitions that definitely wasn't worth the effort).

Given this, and the other PR in place right now - we're definitely getting closer to it! :-)

**Pull request merged**
