### PR TITLE
[js-captcha] Create types for js-captcha 1.1

### PR DESCRIPTION
**Pull request by PikachuEXE**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Ignored `npm-naming` rule since it keeps failing even there is a [`js-captcha`](https://www.npmjs.com/package/js-captcha) package

**Comment by RyanCavanaugh** [comment]
@sandersn what's going on with the lint rule?

**Comment by RyanCavanaugh** [comment]
@sandersn what's going on with the lint rule?

**Comment by sandersn** [comment]
@PikachuEXE I can't repro this error on my clone of Definitely Typed. Did you ever observe the error on the CI, or just locally?

**Comment by PikachuEXE** [comment]
@sandersn I saw it locally
I will remove it and see if the build fails tomorrow

**Comment by PikachuEXE** [comment]
OK I have removed it and Travis build still passes
But I still got error for `npm-naming` locally
I can just ignore it if I submit a new definition next time but would be great to know why it is happening 
The error is not raised when I submit definition **updates**
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35430
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35096

image

**Comment by PikachuEXE** [comment]
Please let me know if you have more questions/comments/changes to be made
Thanks

**Pull request merged**
