### PR TITLE
[Ramda] Added dropRepeats, mergeLeft and hasPath definition

### PR DESCRIPTION
**Pull request by minitesh**
Added a missing definition for 
1. [dropRepeats](https://ramdajs.com/docs/#dropRepeats)
2. [mergeLeft](https://ramdajs.com/docs/#mergeLeft)
3. [hasPath](https://ramdajs.com/docs/#hasPath)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Issue 33347](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33347)

### CODE REVIEW

**Comment by minitesh** [comment]
The build is failing because of recent TS change.

**Comment by googol** [comment]
Typings for the `src/` paths have been added recently, could you add those too for these functions (just like for the `es/` paths)

**Comment by googol** [comment]
Hey! Would you mind adding `mergeRight` and `dropRepeatsWith` also in this PR?
We'd have the 'symmetry' of the ramda functions preserved then.
Especially `mergeRight` would make sense, since it's replacing the deprecated `merge` function.

**Comment by googol** [comment]
@minitesh I incorporated your commit into my PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34141

**Comment by minitesh** [comment]
@googol  Thanks. 
Sorry I was not available to replay you and work on your last comment.

**Pull request closed without merging**
