### PR TITLE
Add hide_zero_doc_count for aggregations in itemsjs

### PR DESCRIPTION
**Pull request by mastoj**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Aggregations doc](https://github.com/itemsapi/itemsjs#configuration)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. -- only fixed what I need, so not sure about version.

### CODE REVIEW

**Review by MysteryBlokHed — CHANGES_REQUESTED** [review]
Could you update the tests (`itemsjs-tests.ts`) to use the new option? It lets me approve this instead of needing to wait for a maintainer.

You could add an aggregation using `hide_zero_doc_count` here:

<https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c8c9eeaf8ad996b3fd6763cf4c1e98c3a32cea28/types/itemsjs/itemsjs-tests.ts#L29-L34>

**Comment by mastoj** [comment]
@MysteryBlokHed , finally got some time to follow up on this. Added the property to the existing aggregation as you suggested.

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by mastoj** [comment]
Ready to merge

**Pull request merged**
