### PR TITLE
classnames - function is exposed as the default export (updated syntax)

### PR DESCRIPTION
**Pull request by niieani**

### CODE REVIEW

**Comment by vvakame** [comment]
https://github.com/JedWatson/classnames/blob/master/index.js#L39
classnames does not have `exports["default"] = classNames ;`.
I think this definition is not works fine. http://goo.gl/uu03ZM

**Comment by niieani** [comment]
@vvakame It is true, but if the module `exports` a function instead of an object, TypeScript exposes it under a `.default` (only when using using `import`). I've tested this locally with the actual package using latest stable TypeScript and it works. It is also the only way to make both `import` and `require` work with the package.

**Comment by vvakame** [comment]
I tried your PR locally.

```
$ cat node_modules/classnames/package.json | grep version
  "version": "2.2.0"
$ tsc --module commonjs classnames-tests.ts
$ node classnames-tests.js
/Users/vvakame/Dropbox/work/DefinitelyTyped/classnames/classnames-tests.js:3
classnames_1["default"]('foo', 'bar'); // => 'foo bar'
                       ^

TypeError: classnames_1.default is not a function
    at Object.<anonymous> (/Users/vvakame/Dropbox/work/DefinitelyTyped/classnames/classnames-tests.js:3:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by niieani** [comment]
Seems my test environment is at fault.

**Pull request closed without merging**
