### PR TITLE
[@types/luxon] Add Datetime.toRelative/toRelativeCalendar.

### LINKED ISSUE #32213: [@types/luxon]  -  toRelative doesnot exist on DateTime
- [x] I tried using the `@types/luxon` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @colbydehart @FourwingsY @jsiebern @mastermatt 

[@types/luxon]  -   toRelative, toRelativeCalendar does not exist on DateTime mentioned at
https://moment.github.io/luxon/docs/manual/moment.html#humanization

### PR DESCRIPTION
**Pull request by mastermatt**
Fixes #32213.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [docs](https://moment.github.io/luxon/docs/manual/moment.html#humanization)
  - [changeset](https://github.com/moment/luxon/pull/390/files#diff-9ecf9d66fc87566271977e944f605443R1754)
- [x] Increase the version number in the header if appropriate.
  - **NOTE:** these methods were added in [v1.19](https://github.com/moment/luxon/blob/master/changelog.md#190), but I'm not updating the version header specifically because #32164 is already opened to add the new methods from v1.10 and I don't want to create an unnecessary conflict. 
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Review by milesj — APPROVED** [review]
Looks good to me.

**Comment by milesj** [comment]
There's also a handful of new additions in the changelog, not sure if they are all in the types. Maybe handle them all in this PR? https://github.com/moment/luxon/blob/master/changelog.md

**Comment by mastermatt** [comment]
@milesj I have a stash of changes and linting that I'll PR later, after this and 32164 get in. I put this out in isolation because the issue was opened.

**Comment by milesj** [comment]
@mastermatt Perfect, sounds good. 👍

**Pull request merged**
