### PR TITLE
Added Boomify as per the new API [types/boom/index.d.ts]

### PR DESCRIPTION
**Pull request by jineshshah36**
Select one of these and delete the others:

If changing an existing definition:
Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/hapijs/boom#boomifyerror-options>>

### CODE REVIEW

**Comment by AJamesPhillips** [comment]
Hey @jineshshah36 could you add a test for this please.

**Comment by AJamesPhillips** [comment]
Also as you bumped the version number to 5.2 from 4.3 then you'll need to update to include the typeof change, which I think is just an extra attribute and a quick test, but not sure:

https://github.com/hapijs/boom/commit/7f68bcd875f0970c893ba3488c76bd9fb43e5069
https://github.com/hapijs/boom/commit/9a6da998d70f795bc0cc264005ab2acd4ca5b6aa

Thanks.  (or you can leave at v4.3 and just put an issue in to fix this later).

**Comment by jineshshah36** [comment]
@AJamesPhillips I bumped the version back down to 4.3. Sorry, I'm a bit new to this. Where exactly do I need to add the test?

**Comment by AJamesPhillips** [comment]
No problem.  Welcome to Typescript :) 👍  

You can add the test here:  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/boom/boom-tests.ts

**Comment by jineshshah36** [comment]
added in the test and ran tsc

**Comment by AJamesPhillips** [comment]
Great thanks @jineshshah36

**Comment by AJamesPhillips** [comment]
Ready to merge @typescript-bot

**Comment by jineshshah36** [comment]
Is there anything else I have to do or will it merge on it's own?

**Comment by AJamesPhillips** [comment]
@jineshshah36 no nothing for you to do.  Just wait for one of the busy maintainers to get to it :)

**Pull request merged**
