### PR TITLE
Enable noImplicitThis

### PR DESCRIPTION
**Pull request by jablko**
```Shell
sed --in-place /noImplicitThis/s/false/true/ $(git ls-files '*/tsconfig.json')
```

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by jablko** [comment]
Splitting in half to duck Travis CI resource limit ...

**Review by henrythasler — APPROVED** [review]

**Review by pocesar — APPROVED** [review]

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Proactively blocking via "Request Changes" until I have a chance to check that this is good.

**Comment by chriskrycho** [comment]
@sandersn @sheetalkamat or someone else from TS team – I'm fine with this from my own responsibility (ember-testing-helpers) but I'd prefer to avoid a repeat of #42687 here; that *I* approve doesn't mean that every *other* definition should be good this way. How would you like to handle this?

**Review by NoMoreDeps — APPROVED** [review]

**Comment by fskorzec** [comment]
I do Agree with @chriskrycho

**Comment by sandersn** [comment]
So: we have a general problem and a specific problem.

1. Generally, typescript-bot is not good at co-ordinating changes to multiple packages. Fine when they are closely related, untenable when they're not. *Generally*, PRs should not change multiple packages unless they're related.
2. Specifically, I don't think this PR is a problem. tsconfig changes don't ship to customers, meaning that they only have two possible effects:
  a. Breaking the tests and forcing them to be stricter. But there are no test changes here.
  b. Breaking the types and forcing them to be stricter. No types break, so the only effect is that future changes to these packages will have to be stricter about using `this`. But type declarations don't have `this` expressions anyway, since they don't have any expressions at all.

tsconfig changes can *not* break customers who get the new version as long as there aren't any type changes. I think this specific change is fine since it doesn't do much of anything.

@jablko I appreciate your effort to get packages up to par on strictness, because strictness holes in `@types` packages do inconvenience people who have `"strict": true`.
Since you are using automation to create these PRs anyway, can you please switch to opening one PR per change?

**Comment by jablko** [comment]
:+1: Yes, will do: https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=in%3Atitle+Enable+noImplicitThis+author%3Ajablko+created%3A%3C%3D2020-03-06

**Pull request closed without merging**
