### PR TITLE
Bugfix in ReactSelect.Async definitions

### PR DESCRIPTION
**Pull request by wassname**
case 2. Improvement to existing type definition.
- [ x] documentation or source code reference which provides context for the suggested changes.  
  - https://github.com/JedWatson/react-select#async-options
  - Some props were missing and Select.Async didn't inherit others properly. I made it match react-select code by extending it.
- [ x] it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by wassname** [comment]
Oh hang on with a review, one of my commit's hasn't been pushed...

**Comment by wassname** [comment]
Ready to review

**Comment by giladgray** [comment]
This looks great! Thanks @wassname for updating the Async typings.

**Comment by giladgray** [comment]
:+1:

**Comment by vvakame** [comment]
@wassname please fix conflict.

**Comment by wassname** [comment]
@vvakame conflict fixed

**Pull request merged**
