### PR TITLE
[phoenix] Update typings for v1.5

### PR DESCRIPTION
**Pull request by thiamsantos**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

## Motivation

- There was some API changes on the [version 1.5](https://diff.intrinsic.com/phoenix/1.4.0/1.5.4) of phoenix package.
- The `Timer` class was missing from the typings.

## Changes

- Include new `vsn` option to Socket constructor. https://github.com/phoenixframework/phoenix/pull/3533
- Include new typing for `Socket.off` method. https://github.com/phoenixframework/phoenix/pull/3553 https://github.com/thiamsantos/phoenix/commit/5c98c571da8adcb5ec8a5b126e1da6cb1892ac24
- Update typings for `onOpen`, `onClose`, `onError`, `onMessage` method of Socket.
- Add missing [`Timer` class](https://hexdocs.pm/phoenix/js/#timer).

### CODE REVIEW

**Comment by princemaple** [comment]
Could you revert the whitespace changes?

**Comment by princemaple** [comment]
Or run prettier with 2space indentation.

**Comment by thiamsantos** [comment]
Sure @princemaple . I just got a little confused because it is different than what is recommended in the PR instructions. But is really an unrelated change. I'll revert it.

**Review by princemaple — APPROVED** [review]
LGTM

**Comment by thiamsantos** [comment]
Ready to merge

**Pull request merged**
