### PR TITLE
feat: remove Terser types definitions

### PR DESCRIPTION
**Pull request by Kocal**
Since version 3.12, Terser provide it's own [types definitions](https://github.com/terser-js/terser/blob/master/tools/terser.d.ts) (search for `TypeScript` in https://github.com/terser-js/terser/compare/v3.11.0...v3.12.0).

I just ran `npm run not-needed -- terser 3.12 https://github.com/terser-js/terser`, I hope this will be fine.

I also patched `@types/terser-webpack-plugin` to prevent some breaks.

**EDIT**: ~Created a PR on `types-publisher` for whitelist `terser`: https://github.com/Microsoft/types-publisher/pull/567~
**EDIT 2**: The PR has been merged, but I can't restart the Travis build.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/terser-js/terser/pull/121
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by JordiAnderl — COMMENTED** [review]
I'd have to take a look at the typings over at Terser since the last time I checked (and informed them of the existance of these typings) they seemed somewhat incomplete to me. 

I'd have no issue with completing their typings and aproving the PR.

**Comment by Kocal** [comment]
Actually, there is a lot of missing types in our `@types/terser` for the final user (the one which only use Terser to compress its JS), because it has not been updated for a long time (versions 3.8 vs 3.12).

A tons on properties in `ParseOptions`, `CompressOptions`, `OutputOptions` (...) are missing in our types.

For _internal types_ (like `Tree*`, `AST_*, ...)` I can't confirm if they are complete and if there is any differences with our `@types/terser`. 
But since https://github.com/terser-js/terser/pull/121 got a lot of reviews, I think this is ok.

**Review by Danscho — APPROVED** [review]
I have no problem with removing the typings here as the typings over a terser-js are more complete than these are. I just added the definitions I am using myself.

**Review by JordiAnderl — APPROVED** [review]
It's better for terser-js to handle their types and update them as they see fit.

**Comment by Kocal** [comment]
Yep :+1: 

Also, we just have to wait for https://github.com/Microsoft/types-publisher/pull/567 to be merged and that will be good I guess.

**Comment by Kocal** [comment]
The Travis build should pass but I can't restart it.

**Comment by Kocal** [comment]
Well, I have nothing to push and I can't restart the build... :man_shrugging:

**Comment by Kocal** [comment]
Hum, even when rebasing the PR on master, I still have the error about dependency `terser` is not allowed to be install, even after my PR to whitelist it...
Is there something I'm missing??

**Comment by Kocal** [comment]
Help @PranavSenthilnathan :disappointed:

**Comment by sandersn** [comment]
Weird, now it's failing with "unexpected semver" in notNeededPackages.json. All the other entries use "n.n.n" format instead of just "n.n" so I suspect that's the problem.

**Comment by Kocal** [comment]
Ah werd, I will rebase, try with 3.12.0, and see what happens

**Pull request merged**
