### PR TITLE
feat(react): Add types for `next` release channel

### PR DESCRIPTION
**Pull request by eps1lon**
Same approach as with `experimental` typings.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  
   - https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html
- ~[ ]~ If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by dimitropoulos — APPROVED** [review]
wow, that was fast.  any reason not to just use v18 since we know that's what these are for?

**Comment by eps1lon** [comment]
> wow, that was fast. 

React working group members were invited a week earlier so I did have some time to get everything in place.

> any reason not to just use v18 since we know that's what these are for?

This isn't possible with DefinitelyTyped. The latest types on DT have to match the latest library version. So if we would move the current typings to v17 everybody would install typings for v18 by default.

I've asked for a better "API" for pre-release types but didn't receive a response.

**Review by johnnyreilly — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Good work - probably worth blogging about the consumption pattern for these types. Is this ready to merge?

**Comment by eps1lon** [comment]
> Good work - probably worth blogging about the consumption pattern for these types. Is this ready to merge?

Since this PR is just moving things around, there's hopefully little risk of breakage.

Ready to merge

**Comment by eps1lon** [comment]
Ready to merge

**Comment by johnnyreilly** [comment]
> Since this PR is just moving things around, there's hopefully little risk of breakage.

It's not breakage I was thinking of, more "if you want to use react 18, here's the tricks you have to do to make that happen". The information is in the typing comments - not sure how well people will discover it. Just a thought

**Comment by johnnyreilly** [comment]
One blog to make it easier for people to get on board: https://blog.logrocket.com/how-to-use-typescript-with-react-18-alpha/

**Comment by dimitropoulos** [comment]
Oh, that's funny, I was just coming here to mention that I saw that logrocket about it (I didn't realize it was you john, I thought that was quite a fast turnaround from a random person!).  Thanks for doing that @johnnyreilly.

I really love logrocket's blog.  It's one of the best out there I've seen.

**Comment by unadlib** [comment]
I installed `react-dom@17.0.13` and found that the react18 type didn't work, but `react-dom@17.0.7` was fine.

**Pull request merged**
