### PR TITLE
[aws-lambda] Add aws guard duty scan result event notification

### PR DESCRIPTION
**Pull request by ebussieres**
Please fill in this template.

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ X ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/aws-lambda/trigger/guard-duty-event-notification.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d11c705516ab44f0a0f07b00d854b68fd8dec734
</p>

**Review by jamesorlakin — COMMENTED** [review]
Thanks for you first PR in DefinitelyTyped!

Please add tests. Perhaps have a look at the existing tests for other Lambda trigger for inspiration.

In addition you'll probably want a Handler type defined here (for assigning functions to directly), as well as adding this file to `.../index.ts` so it gets re-exported package-wide.

**Review by rbuckton — APPROVED** [review]

**Comment by darbio** [comment]
Where are the changes and  tests as requested by @jamesorlakin ??  

This PR is not ready to be merged and shouldn't have been approved by @rbuckton

**Review by darbio — CHANGES_REQUESTED** [review]
Tests, formatting and handler export as requested by @jamesorlakin  please.

**Review by jakebailey — APPROVED** [review]

**Comment by ebussieres** [comment]
Ready to merge

**Comment by darbio** [comment]
Thank you @ebussieres ❤️

**Review by darbio — COMMENTED** [review]
👍

**Pull request merged**
