### PR TITLE
fix(is-map): make function type guard

### PR DESCRIPTION
**Pull request by tristan-f-r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/inspect-js/is-map/blob/e07e23affca99f469937dade44abc02e05a26739/index.js#L39
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Since many of the utilities in `inspect-js` serve as type guards (e.g. `is-set` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67585), `is-map` should also serve as a type guard.

### CODE REVIEW

**Review by Ankan002 — COMMENTED** [review]
I guess we should not use directly Map to define as the function originally returns a boolean value simply.

**Review by Ankan002 — CHANGES_REQUESTED** [review]
Please review the above mentioned once

**Comment by LeoDog896** [comment]
The only issue I see with that is that as much as `is-map` returns a boolean, that boolean also acts as a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), which can help conditionally assert that something is a value. As shown in [one of the tests](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67587/files#diff-d5dfaf633f3419223532098f89823bb0f8580e0ad78e0ffce162423332a39546R12-R19), you can use it to tell if a variable extends a `Map<any, any>`:

```ts
declare var x: unknown

if (isMap(x)) {
    // Even though `x` was unknown, with the types proposed in this PR, we can safely call map-like functions.
    x.set(1, 1);
}
```

**Comment by Ankan002** [comment]
> The only issue I see with that is that as much as `is-map` returns a boolean, that boolean also acts as a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), which can help conditionally assert that something is a value. As shown in [one of the tests](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67587/files#diff-d5dfaf633f3419223532098f89823bb0f8580e0ad78e0ffce162423332a39546R12-R19), you can use it to tell if a variable extends a `Map<any, any>`:
> 
> ```ts
> declare var x: unknown
> 
> if (isMap(x)) {
>     // Even though `x` was unknown, with the types proposed in this PR, we can safely call map-like functions.
>     x.set(1, 1);
> }
> ```
> 
> (@Ankan002)

But if we use `isMap` under the if statement it would protect from going inside if block like

```typescript
const isMap = require("is-map");

let x: unknown;

console.log(isMap(x)); // returns false

if (isMap(x)) {
    // Even though `x` was unknown, with the types proposed in this PR, we can safely call map-like functions.
    x.set(1, 1);
}
```

like isMap function returns a false above

**Comment by LeoDog896** [comment]
With the older code, `declare function isMap(value: unknown): boolean;`, when you tried to do the following:

```ts
if (isMap(x)) {
  x.set(1, 1) // this would have been a type error!!
}
```

it wouldn't compile in TypeScript (assuming `x: unknown`), even if `isMap(x) === true`.

**Comment by Ankan002** [comment]
Hmm, interesting. We can consider that case.

**Review by Ankan002 — APPROVED** [review]

**Comment by LeoDog896** [comment]
Ready to merge

**Pull request merged**
