### PR TITLE
[node-7z] Update for v2.1.1

### PR DESCRIPTION
**Pull request by colin969**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/quentinrossetti/node-7z#readme
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by colin969** [comment]
Changing to fix the linting errors would seriously reduce readability.

main, mainFactory, listen, listenFactory while exported are never mentioned / used in the documentation, and seem to only be used in their test cases.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## node-7z ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-7z@latest/))
was missing the following properties:
1. listenFactory
1. mainFactory
1. main
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f428529d36ea69adaae242f42eade84d24c32293
</p>

**Comment by erkie** [comment]
Is there no way to extend the builtin event listener types to not have to add types for all event listener methods?

**Comment by colin969** [comment]
I tried with no luck. TypeScript won't allow to add 'progress', something to do with the way overloads works, and I wouldn't be able to type 'data'.

**Pull request merged**
