### PR TITLE
fix(express-session): remove unnecessary needed guard for "initialized" sessions

### PR DESCRIPTION
**Pull request by simllll**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/express-session and also as discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46576#issuecomment-724674879
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by andrewbranch** [comment]
@simllll thanks for taking the initiative to do this! Based on the conversations after the previous PR, I think this is the right move. I’m not approving now because that will make the bot eager to merge, and I want to give others a chance to review and discuss. But based on my understanding of the problem, this seems right.

**Comment by kstiehl** [comment]
Looks good to me 👍

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@simllll thx!

@HoldYourWaffle so we frequently deal with the problem of two-edged sword kind changes here in DT. Here we take an approach that alings with day-to-day usage, more
aligned with non-typed JS, just an easy-goer experience. This does not mean that we do not appreciate the intent behind your changes, thx!

**Review by andrewbranch — APPROVED** [review]

**Comment by simllll** [comment]
Ready to merge

**Comment by rijkvanzanten** [comment]
@simllll @kstiehl @HoldYourWaffle @andrewbranch What is the policy around breaking changes / SemVer here? 

From `1.17.0` to `1.17.1`, there was a very big (breaking) change that introduced this `InitializedSession` (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49484), so we went ahead and patched our project to include this new setup. Now a couple days later this `InitializedSession` is ripped out, causing another breaking change in our project.....

Shouldn't these changes have been released as `2.0.0` and `3.0.0` respectively?

**Comment by simllll** [comment]
Fully agree @rijkvanzanten, but as 1.17.1 was already a breaking change released as patch update, I didn't think about it too much and thought we gonna "revert" the old behaviour with 1.17.2 back to 1.17.0.

**Comment by andrewbranch** [comment]
> Shouldn't these changes have been released as `2.0.0` and `3.0.0` respectively?

No. There is no SemVer for `@types` packages. The major/minor version of the types package mirrors that of the source package, then the patch version increments. If this were not the case, it would be a nightmare for anyone to try to figure out what version of `@types/express-session` they need to install for a given version of `express-session`. To be pedantic about it, every typings change could be a breaking change, so if we tried to follow SemVer, literally every publish would be a new major version, or you’d get into subjective arguments about how likely a given change is to break someone in practice. That said, we try not to cause unnecessary churn on popular packages, but we made a mistake on 1.17.1, and felt it was best to fix it quickly. That way, anyone who didn’t happen to upgrade their typings for express-session in this window of a couple days won’t be affected. Apologies that you were in the unlucky few who upgraded in that window.

**Comment by rijkvanzanten** [comment]
Thanks for clearing that up @andrewbranch 👍

**Comment by HoldYourWaffle** [comment]
@peterblazejewicz First of all, thanks for showing your appreciation. It means a lot to see that the thing you've been (passively) working on for 20 months is appreciated.

To give my (late) opinion on the matter: I fully agree with the implemented "fix".
As @kstiehl put it: "The whole thing wasn't probably one of my brightest moments"...

Like you said, I don't think that the `InitializedSession`-model is/was *wrong*, but it's inconveniently restrictive for day-to-day "idiomatic" use.
I feel like this comment by @andrewbranch sums up exactly why the original reasoning turns out to be overzealous/unnecesary:

> But you could just as well go from a type like Session & Partial<SessionData> to Session & SessionData with a type assertion or user-defined type guard, right? So you could a) treat all your data properties as optional, without needing to narrow the type given to you by default, and b) treat all your data properties as non-optional (as declared) with a type guard. Whereas now, it sounds like the situation is you need a type guard for both situations, which seems unnecessarily painful.

My main goal was to make type-assertions/guarding easy(er), which is exactly what this fix does too (but better).
If I had had the time to respond sooner, I would've put a big "approve" on this :)

**Pull request merged**
