### PR TITLE
request fix defaults

### PR DESCRIPTION
**Pull request by enriched**
Some additional fixes for the defaults funciton so that it works with the features in #6489

### CODE REVIEW

**Comment by eggers** [comment]
+1
Good catches, thanks

**Comment by vvakame** [comment]
*request/request.d.ts*

to authors(@soywiz @bonnici @Bartvds @joeskeen). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@enriched please resolve conflict.

**Comment by enriched** [comment]
@vvakame Resolved

**Comment by joeskeen** [comment]
@enriched this is an interesting pull request... I see a small issue though.  After doing some testing I can verify that you indeed can set a url/uri in the defaults, then not pass it into subsequent requests.  This contradicts the request in #6489 that the requirement of (`uri` OR `url`) be enforced in the options passed into requests, which is the reason (I think) that `Options` was broken up into `RequiredOptions` and `OptionalOptions` to begin with.
As the definition file is right now in `master`, the following valid use case does not work:

```js
import nodeRequest = require('request');
const request = nodeRequest.defaults({url: 'https://github.com'});
request({}, function(error, response, body) {console.log(body);});
```
This pull request, although it allows you to add a `url` or `uri` to the `defaults`, it doesn't allow you to not include `url` or `uri` later on.

The most true-to-life way to describe this API IMHO would be to recombine the `Options` into a single interface where `url` and `uri` are both optional, since there is no way for TS to know whether a default `url` or `uri` has previously been set.  Doing this would simplify the API a bit and remove the intersection types (which can make autocompletion more verbose than it needs to be sometimes).

If you have a better idea of how to address this, I would be happy to see it.

**Comment by enriched** [comment]
Yeah, good catch.  We could have defaults return ```RequestAPI<TRequest, TOptions & OptionalUriUrl>``` it's not fantastic because I can't think of a way for that to detect if the uri or url were specified in the passed in options.  Unless if typescript is smart up to pick up that defaults(options: RequiredOptions & TOptions) is different from defaults(options: TOptions) but I don't think that it does that.

**Comment by vvakame** [comment]
can I merge this PR?

**Comment by enriched** [comment]
I'm fine with it.  @joeskeen any changes that we want to make now or is this good enough?

**Comment by joeskeen** [comment]
@enriched, I think that the code looks OK, but I would feel better about it if you were to add some tests that prove that those scenarios work as expected.

**Comment by joeskeen** [comment]
@enriched, I got a little extra time and I think I worked out a solution: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...joeskeen:request-fix-defaults  What do you think about it?

**Comment by enriched** [comment]
The thing that I am wary of is adding another type to the generic list, seems like that will get confusing if that pattern continues.

**Comment by joeskeen** [comment]
@enriched I agree that adding more generics makes things more confusing.  I'm open to other ideas, but as of now, I think this will work.  Do you think this is ready for a merge?

**Comment by enriched** [comment]
I agree, for now this works, and hopefully if someone adds something else that adds on top of request they don't add more types to that list.  :shipit:

**Comment by joeskeen** [comment]
Agreed. :) Thanks @enriched for your contribution!
@vvakame , I think this is ready to be merged!

**Comment by jamesrmccallum** [comment]
@ enriched, @vvakame  i've stumbled on this separately and had problems in the case where i'm using a requests.default wrapper in accessing multiple endpoints of the same API. 

I've set it up using baseUrl (which i've also had to add to the .tsd) then when i call it later as req.post('url', {body: foo}) I get the uri or url required error. This is baked into the options object.

In my view neither the urloptions or urioptions object is required here, but because it's unioned up with the optionaloptions object there's no getting around it. 

I used a new type and a 4th overload for the request function to do it. Maybe this breaks something else? 

/** For use when defaults are already specified, options object isn't required */
```typescript    

export type OptionswithDefaults = OptionalOptions;

function RequestAPI(uri: string, options?: RequestAPI.OptionswithDefaults, callback?: RequestAPI.RequestCallBackFn): RequestAPI.Request;

**Comment by vvakame** [comment]
*request-promise/request-promise.d.ts*

to author(@cglantschnig). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@jamesrmccallum sorry, I don't know how to use this library. @enriched @joeskeen ?

**Comment by cglantschnig** [comment]
:+1:  looks good to me

**Comment by joeskeen** [comment]
@jamesrmccallum Could you please provide some sample code that exhibits the issue you are talking about?  I'm trying to understand your use case better.

**Comment by jamesrmccallum** [comment]
Hey @joeskeen  - here we go...

Essentially using the req defaults wrapper as a pre-configured version of request for consuming various endpoints of the same API. I then call this with just the /endpoint later. It works OK and I think according to the request docs it's a valid use case 

```typescript
var req = request.defaults({
	baseUrl: 'https://someserver.com/apiroot,
	headers: {
		"Authorization": 'Basic %%%TOKEN%%%',
		"Accept": 'application/json'
	}
});

\\\ Called later as 

req.get('/someEndpoint', (e, r, b) => {
			if (e) {  reject('Endpoint problem at: '+endPoint + e) };
			
			try {
				console.log('Parsing response from endPoint' + endPoint)
				var res = JSON.parse(b);
			} catch (e) {
				reject('Error parsing response at ' + endPoint + e);
			}
			
			if(transform) { 
				try { res = transform(res);}
				catch (e) {reject(e)};
			}
			
			resolve(res);
		})

**Comment by joeskeen** [comment]
@jamesrmccallum the code you posted had a few typos, but I got the idea...
I pasted your code into `request-tests.ts` and after massaging the typos out, it appeared to work compile fine:

```js
var reqDefaultTest = request.defaults({
    baseUrl: 'https://someserver.com/apiroot',
    headers: {
        "Authorization": 'Basic %%%TOKEN%%%',
        "Accept": 'application/json'
    }
});

/// Called later as 
reqDefaultTest.get('/someEndpoint', (e, r, b) => {
    if (e) {  reject('Endpoint problem at: '+endPoint + e) };
    try {
        console.log('Parsing response from endPoint' + endPoint)
        var res = JSON.parse(b);
    } catch (e) {
        reject('Error parsing response at ' + endPoint + e);
    }
    if(transform) { 
        try { res = transform(res);}
        catch (e) {reject(e)};
    }
    resolve(res);
});
```

**Comment by jamesrmccallum** [comment]
If this PR fixes it then that works for me, thanks for taking a look.

**Comment by joeskeen** [comment]
@vvakame , it looks like we have a :+1: from @eggers, @enriched, @cglantschnig, and @jamesrmccallum.  I think we are ready to merge this one!

**Comment by enriched** [comment]
:+1: lets put a :bowtie: on this

**Comment by vvakame** [comment]
:clap:

**Pull request merged**
