### PR TITLE
types/xrm - Added Entity and EntityReference interfaces to WebApiOffline

### PR DESCRIPTION
**Pull request by metjuperry**
Added Entity and EntityReference interfaces to WebApiOffline

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi

### CODE REVIEW

**Review by orta — APPROVED** [review]
Looks reasonable to me based on the documentation link!

**Comment by metjuperry** [comment]
Ready to merge

**Comment by fowl2** [comment]
hola, this breaks the build of anyone doing this

`Xrm.WebApi.createRecord('xxx_entity_with_all_defaults', {})`

**Comment by fowl2** [comment]
also, this new `interface EntityReference` 

```
     interface EntityReference {
        /**
         * The record id. Read-only.
         */
        id: { guid: string; };

        /**
         * The entity logical name. Read-only.
         */
        etn?: string;

        /**
         * The name of the entity reference. Read-only.
         */
        name: string;
    }
```

doesn't match the docs for the return type for `Xrm.WebApi.createRecord` or `Xrm.WebApi.updateRecord`:



> An object with the following properties will be passed to identify the new record:
> entityType: String. The table logical name of the new record.
> id: String. GUID of the new record.> 


or `Xrm.WebApi.deleteRecord`:

> A function to call when a record is deleted. An object with the following properties will be passed to identify the deleted record:
> 
>     entityType: String. The table type of the record.
>     id: String. GUID of the record.
>     name: String. Name of the record.

**Pull request merged**
