### PR TITLE
[paper] Added Size.add & Size.subtract methods

### PR DESCRIPTION
**Pull request by StickerFiend**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://paperjs.org/reference/size/#add-number

### CODE REVIEW

**Review by clark-stevenson — APPROVED** [review]
👍

**Comment by clark-stevenson** [comment]
@StickerFiend thanks as always man.

Do you know where we are with this?  Do you think we should push my repo here and close my repo? 

I hate there are two places :(

**Comment by StickerFiend** [comment]
It seems like there are a few differences between your repo and this repo. It would probably be a good idea to close yours so people don't get confused. Do you know if there are any projects that depend on yours? I guess the other option would be to not accept any more pull requests on yours and point people here.

**Comment by clark-stevenson** [comment]
Just people as yourself man.   There has been maybe a half dozen others over the years. 

Do you mind if I ask where you take your declaration from? From here?  I would be happy to go with your workflow.  

I maintain https://github.com/pixijs/pixi-typescript

So for me, that is the core project.  Definitely Typed is simply a delivery mechanism.  I reject any pixi talk or PRs here instantly and point them to this "core place". Only I can be the judge of when I feel it is relevant to hit DT with changes.  

So it is "managed" as best as it can be. 

Do you have the time and occasional effort to be the "paper typescript" king of the globe??? If so, lets do this somehow!

**Comment by clark-stevenson** [comment]
Lol sorry if that made no sense.

Basically I wonder 2 things:

1. Would you be willing to be the "Owner" here on PR of that paper.d.ts? (when people make PRs, YOU are the judge)
1. Perhaps the authors are willing to accept index.d.ts on paperjs.   Or atleast make a repo like pixi did so that there is a "single souce of truth".

**Comment by StickerFiend** [comment]
@clark-stevenson Sorry, I was out of the office Thursday & Friday. I take the declarations from DT. Sure, I can take over paper typings. I like your workflow, so I'll probably do the same. How do you want to go about doing this? Can you add me to your paper typings repo so I can review & merge PRs?

Thanks!

**Pull request merged**
