### PR TITLE
react-map-gl: Added string to width and height on ViewportProps for use with 'vw', …

### PR DESCRIPTION
**Pull request by arthur-cheung**
…'vw' and '%'.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/visgl/react-map-gl/blob/6.1-release/src/components/static-map.js#L64 and https://github.com/visgl/react-map-gl/blob/6.1-release/src/components/static-map.js#L64
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by ireznik** [comment]
looks good to me

**Review by fnberta — APPROVED** [review]

**Comment by arthur-cheung** [comment]
Ready to merge

**Comment by ireznik** [comment]
@arthur-cheung did you see my comment?

**Comment by arthur-cheung** [comment]
@ireznik so sorry! I only so the bot response.  I’ll fix it up. I’ll create another pull request?

**Pull request merged**
