### PR TITLE
react-router: add missing onEnter and onLeave to RouteProps type

### PR DESCRIPTION
**Pull request by hiddestokvis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#enter-and-leave-hooks
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
👍 or 👎 ,
@sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @tkrotoff @huy-nguyen @grmiade @DaIgeb ?

**Comment by KostyaEsmukov** [comment]
The typings are for v4. There are no `onEnter`/`onLeave` props in v4.

But these are present in v3 typings: https://github.com/hiddestokvis/DefinitelyTyped/blob/ea0aa098edc6ce6ba72bdb45cc699b5fb229c0a3/types/react-router/v3/lib/IndexRoute.d.ts#L20-L22

You should install them using `npm install --save @types/react-router@3` command.

I'm sorry, but this PR should be closed.

**Comment by DovydasNavickas** [comment]
Looked what was added and I can only agree with @KostyaEsmukov.

**Comment by hiddestokvis** [comment]
My bad working between projects missed the fact that onenter and onleave are no props in v4 anymore. Closing this pr.

**Pull request closed without merging**
