### PR TITLE
fix(node): add missing util.types.isArrayBufferView

### PR DESCRIPTION
**Pull request by addaleax**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/util.html#util_util_types_isanyarraybuffer_value
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by galkin — APPROVED** [review]

**Review by galkin — APPROVED** [review]
As I know we don't make changes for unsupported node.js version like v11.

**Review by a-tarasyuk — APPROVED** [review]

**Review by SimonSchick — APPROVED** [review]
You should omit v11 changes.

**Review by ExE-Boss — APPROVED** [review]
I think that types for old **Node** versions can still be updated if they need fixes (otherwise they wouldn’t be in this repository).

**Comment by addaleax** [comment]
I can omit the v11 changes here if this won’t land otherwise but I don’t really see why we wouldn’t apply bug fixes to them.

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
I think it's fine to adapt EOL versions but if they are not changed it's also fine.

**Review by Flarna — APPROVED** [review]

**Pull request merged**
