### PR TITLE
feat: wx-js-sdk for 1.6.0

### PR DESCRIPTION
**Pull request by adndyxu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
is this the same native project behind third declaration files? With just name and project home page changes, including owners change? Or this PR covers a 'fork' of existing project?

**Review by peterblazejewicz — DISMISSED** [review]
Please review the question on the nature of this PR code changes, thx!

**Comment by adndyxu** [comment]
> is this the same native project behind third declaration files? With just name and project home page changes, including owners change? Or this PR covers a 'fork' of existing project?

Yes ,this is the LST version for the same native project(wx-js-sdk-dt) with some api change, last week I start a PR to the @types/wx-js-sdk-dt but get no response, so I start a new one for LST support.

**Comment by peterblazejewicz** [comment]
OK, you're effectively renaming definition (due to usage of git mv). What about those folks, what's their input on the change?
```ts
Bian Zhongjie <https://github.com/agasbzj>
Ming Huang <https://github.com/forzoom>
```

**Comment by adndyxu** [comment]
> OK, you're effectively renaming definition (due to usage of git mv). What about those folks, what's their input on the change?
> 
> ```ts
> Bian Zhongjie <https://github.com/agasbzj>
> Ming Huang <https://github.com/forzoom>
> ```

just modify on the basic of theirs old version lib, should I add them to the author as well?

**Comment by peterblazejewicz** [comment]
ok, so DT supports 'ownership' of the code here. Those folks are current authors:
https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners
There is no strict rule here, what to do in case similar to your PR, but I assume we should at least mention them in the pull request. 
IMO that's the least one should do, as you are effectively removing older package, due to use of 'git mv' (renaming old package to new one, etc).

We can see, that DT bot does not support this particular path of PR upgrades (diagrom from readme):
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

**Comment by adndyxu** [comment]
> ok, so DT supports 'ownership' of the code here. Those folks are current authors: https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners There is no strict rule here, what to do in case similar to your PR, but I assume we should at least mention them in the pull request. IMO that's the least one should do, as you are effectively removing older package, due to use of 'git mv' (renaming old package to new one, etc).
> 
> We can see, that DT bot does not support this particular path of PR upgrades (diagrom from readme): https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

Sorry for my negligence, just mention them in the head.

**Comment by adndyxu** [comment]
> /cc @agasbzj @Forzoom

Should we wait util they response? Do we have a deadline?

**Comment by peterblazejewicz** [comment]
No, there is no deadline I believe.
The only problem here, as mentioned, is that you are renaming a package down by others. 
If instead, you'd just added new package with your as an owner, I'd not need to check the other people feedback. 
I hope I explained this clearly

**Comment by adndyxu** [comment]
> No, there is no deadline I believe. The only problem here, as mentioned, is that you are renaming a package down by others. If instead, you'd just added new package with your as an owner, I'd not need to check the other people feedback. I hope I explained this clearly

Ok,If they don't active on github, but on the same time I wish to make some updates on their package, what should I do? Create a new One without checkout from their branch?

**Comment by peterblazejewicz** [comment]
ok, let me explain (and this is just my opinion here):

What you've did, was probably is similar to:
```cli
git mv types/node types/my-node
```
that would remove sources for @types/node, and create sources for 'new' package `@types/my-node`

While you probably should just:
```cli
cp -r types/node types/my-node
```
that ould create source for new package `@types/my-node`.
and make amendments in `@types/my-node` (changing details, updating names, etc)

If you want to remove sources for older package, just create additional, focused PR that will cover removing `wx-js-sdk` sources, DT maintainers can work in place of the original owners, if there is a valid reason

**Comment by adndyxu** [comment]
> ok, let me explain (and this is just my opinion here):
> 
> What you've did, was probably is similar to:
> 
> ```
> git mv types/node types/my-node
> ```
> 
> that would remove sources for @types/node, and create sources for 'new' package `@types/my-node`
> 
> While you probably should just:
> 
> ```
> cp -r types/node types/my-node
> ```
> 
> that ould create source for new package `@types/my-node`. and make amendments in `@types/my-node` (changing details, updating names, etc)
> 
> If you want to remove sources for older package, just create additional, focused PR that will cover removing `wx-js-sdk` sources, DT maintainers can work in place of the original owners, if there is a valid reason

Thanks, it really help me.I will create a new one in another PR and close this issue.

**Pull request closed without merging**
