### PR TITLE
chore: remove EOL node v14 types

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Node v14 has fallen out of LTS `2023-04-30` see https://github.com/nodejs/release#end-of-life-releases it should likely not be updated anymore.

### CODE REVIEW

**Comment by Semigradsky** [comment]
So after this change it will be not posiible to publish any fix for v14?

**Comment by SimonSchick** [comment]
That's correct, this reduces the maintenance surface for contributors and has historically been done, it's also in-line with the NodeJS maintenance schedules.

**Comment by peterblazejewicz** [comment]
it's (the version) no longer on the Node version radar, so let's do this. There is a thread on GH contributors forum on how to reduce carbon footprint (this is how)

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@SimonSchick thanks!

**Comment by SimonSchick** [comment]
READY TO MERGE

**Comment by SimonSchick** [comment]
> it's (the version) no longer on the Node version radar, so let's do this. There is a thread on GH contributors forum on how to reduce carbon footprint (this is how)

@peterblazejewicz link? 👀

**Comment by Semigradsky** [comment]
@SimonSchick should we remove EOL node v16 types too?

v16 EOL is 2023-09-11

**Pull request merged**
