### PR TITLE
Types 2.0

### PR DESCRIPTION
**Pull request by robessog**
New version of **react-autosuggest** is released and the current typing is no more compatible with that.

A required method name for fetching the suggestions changed to **onSuggestionsFetchRequested**. I also aligned the interface type name of its input argument to reflect the new method name: **SuggestionsFetchRequest**

Also some other **optional** methods and properties were introduced into the **AutosuggestProps** class:
- optional **onSuggestionsClearRequested**
- optional **alwaysRenderSuggestions** property
etc.

I changed the return type of **getSuggestionValue** method form **string** to **any** because it can happen that you would like to return with an object with multiple properties instead of a single string.

Added **tslint.json**

**ExplicitSuggestionSelectedEventData** was renamed to SuggestionSelectedEventData. I know that the original author wants to keep the empty SuggestionSelectedEventData non-generic interface, but I think we can go with the SuggestionSelectedEventData\<any\> type in all places where we would use the non-generic interface. Plus tslint throws warning on empty interfaces.

More information of current interface:
https://github.com/moroshko/react-autosuggest#props

### CODE REVIEW

**Comment by nicolas-schmitt** [comment]
Hi, there is already an ongoing PR about 7.0 compatibility : #13255 
Also, you shouldn't include your tslint.file since there is no guarantee that an another one exists in the parent folder.

**Comment by robessog** [comment]
Yes, there is. But that one is on the master branch. As I know new changes should be added to types-2.0 branch, so I did the modifications here on the types-2.0 branch as well. Or are you planning to merge the changeset from master to the type-2.0 branch?

As far as the tslint file: I just followed the readme, Check the Lint section. It requires that new packages should be linted, and in the example it references a tslint.json file in the parent folder so I thought I can be sure that it exists.

**Comment by andy-ms** [comment]
Yes, you can depend on `tslint.json` existing in the root directory. `tslint.json` is not published to npm.
On that topic, your tests are failing due to a lint error. You can fix that by removing the `declare namespace ReactAutosuggest { }` and `declare module 'react-autosuggest' { }` wrappers and just doing everything on the top level.

**Comment by robessog** [comment]
Thanks for your help @andy-ms. I've checked in the changes and now the linting passed.

**Comment by robessog** [comment]
Should I now create a pull request for the master branch if I want this issue to be closed, @andy-ms?

**Comment by andy-ms** [comment]
You don't have to; we'll do a merge from `types-2.0` to `master` soon.

**Pull request merged**
