### PR TITLE
updates rsocket-core types to the latest 0.0.22 version

### PR DESCRIPTION
**Pull request by OlegDokuka**
for more info on changes see https://github.com/rsocket/rsocket-js/tree/master/packages/rsocket-core/src

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## rsocket-core ([<kbd>unpkg</kbd>](https://unpkg.com/browse/rsocket-core@latest/))
was missing the following properties:
1. WellKnownAuthType
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d915245bb9924f19a225835bcb6a99009e879eaf
</p>

**Comment by OlegDokuka** [comment]
Hi @danger-public!

RSocket maintainer here!

Thank you for commenting!

Can you please double check the following source and d.ts files:

d.ts - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50191/files#diff-884933243c4fd76b5b02eb404d07bb528f9e10e49326480b6a6090fa05aa5fc3
source - https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-core/src/WellKnownAuthType.js

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by peterblazejewicz** [comment]
> Can you please double-check the following source and d.ts files:

It probably means `WellKnownAuthType` is not re-exported from `index.d.ts` (as it is in `index.js`:
https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-core/src/index.js#L52

**Comment by OlegDokuka** [comment]
Have no idea what went wrong. @peterblazejewicz any suggestions?

**Comment by peterblazejewicz** [comment]
IMO the problem sneaked into 4.2 nightly:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50431
https://github.com/microsoft/TypeScript/issues/42229
Looks same as your CI problem?

**Comment by OlegDokuka** [comment]
ready to merge

**Review by peterblazejewicz — APPROVED** [review]

**Comment by OlegDokuka** [comment]
Ready to merge

**Pull request merged**
