### PR TITLE
[ramda] overhaul

### PR DESCRIPTION
**Pull request by somebody1234**
**Note:** Many tests are still failing, this is nowhere near ready to merge

What this PR includes
- Updates to all docs
  - Adds examples (all tested in TypeScript), and "See also" links (not that useful in VS Code since it links to the definition in the source file)
  - Some are slightly changed from ramda docs
- Numerous changes/fixes to all functions (WIP)
  - A *lot* of breaking changes, however most of them should be reasonable
  - Quite a few functions have had their overloads completely 
  - Generic parameters have/are being reordered to be more friendly for manually specifying them
    - Inference should still have first-class support though, so when it makes sense, there are separate overloads solely for inference
  - Numerous overloads have also been reordered (I think)
  - Many simple helper types have been inlined and deprecated
- Updated and/or more comprehensive tests (very WIP - unfinished)
  - This should include at least one test for every overload
  - Also should have tests that explicitly specify generic parameters.
  - Formatting has been changed to be consistent - e.g. `// $ExpectType` on the line above
  - Unused variables changed, unused parameters prefixed with `_`. This is more of a personal style choice but I think it looks better not seeing dimmed out variables
  - Missing tests are being added (WIP - let me know, or submit another PR, if you find any others)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (Docs taken from) https://ramdajs.com/docs/

### CODE REVIEW

**Comment by somebody1234** [comment]
Still very WIP, opening PR now since it's a big change and so it will probably take a while to review anyway

**Comment by somebody1234** [comment]
Just a heads up, I may have accidentally added some unnecessary overloads (e.g. extra, more curried overloads)

**Comment by somebody1234** [comment]
What even is the correct type/intended usecase of `unary`/`binary`/`nAry`?
JavaScript and TypeScript both handle extra parameters fine

**Comment by somebody1234** [comment]
(As always, feel free to extract parts of this PR to merge separately - it's probably too big to merge all at once anyway)

**Comment by somebody1234** [comment]
thoughts on removing support for fantasy-land functors? i think it'd make sense since i don't think there are any other functions that have support for fantasy-land types

**Comment by essenmitsosse** [comment]
Definitely would love to see this split into smaller PRs. Love the updated JSDoc comments for example but its really hard to check with all the other stuff going on. Also discussions will be more focused on several smaller PRs.

**Comment by somebody1234** [comment]
oosp

**Comment by somebody1234** [comment]
@essenmitsosse @adispring Asking here because I don't know if it's worth opening a new PR for something that might not even be an issue:
Should `and` and `or` require the same type? Alternatively - are there any common usecases where you would want the type of `a` and `b` to be different?

Also worth noting that with the new typing:
```ts
export function and<T>(a: T, b: T): T;
export function and<T>(a: T): (b: T) => T;
```
You *could* still manually specify `A | B` as a generic parameter to get the old behavior, if the change is implemented

**Comment by somebody1234** [comment]
(incomplete) checklist of things to do:
- update Curry & friends
- update functions that need DeepRecord & friends
- update `and`/`or`
- add missing tests
- add testcases in general
  - add testcases for generic parameters. I think this is important since you *will* need to specify generic parameters if you're doing anything complex
- deprecate simple helper types

**Comment by essenmitsosse** [comment]
@somebody1234 I always wondered why `and` and `or` are typed likes this. As far as I can tell `and("a", 0)` would be perfectly fine. 


Bonus points: I also would actually love if both could express that for example `or(0, "a")` would return `string` and not `number | string`, if the value passed is actually falsy. While this might seem like overkill it could do for some fantastic expressibility.

**Comment by somebody1234** [comment]
Yeah I believe `and("a", 0)` is currently fine - however I'm not sure how useful it is in practice - maybe it would be more useful to make that error by default, who knows.
As for `or(0, "a")`, I did actually have the typings like that at one point - however I think it's unneccessary complexity - if the left side really is the constant `0` you should already have enough information to not need the `or` in the first place

**Comment by essenmitsosse** [comment]
I thought more about something like:

```typescript
const a: null | string;
const b: number;

or(a,b) // string | number
```

Not that it doesn't return `string | number | null`, since we can rule out `null` here.

**Comment by somebody1234** [comment]
Ah. `a: T | null | undefined` should work - still not sure about the other falsy values like `false` and `0` and `''` though. `false` maybe, the other two... not sure.

**Comment by essenmitsosse** [comment]
```typescript
type NotFalsy<T> = Exclude<T, undefined | null | 0 | "">

function or<T, U>(a: T, b: U): NotFalsy<T> | U;


const a: string | null | '0';
const b: number;
const result = or(a, b) // string | number
```
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcg9sAYgQwDYGcQB4AqA+KAXigFEAPAY1QFcATCXAGimoDt6AzAS1YlqgA+UVtVSpBUAAwSARDLwAoBRzYVgXOKyhwATkygBVPAApkALig5mAIwsGAlBfhI0mXASEGA3EoUVN6MBQ5lCBOjwA5hIiYhIA5JJxPv6sgVC2wtQAttYQOskBQToQ6KJBxLqmNvZAA)

**Comment by somebody1234** [comment]
[Playground without type errors](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcg9sAYgQwDYGcQB4AqA+KAXigFEAPAY1QFcATCXAGimoDt6AzAS1YlqgA+UVtVSpBUAAwSARDLwAoBfSrIATtA5sKwLnFZQ4aplACqeABTIAXFBzMARrdMBKW-CRpMuAkNMBuJQVUCGAoZABCWwByDjg4B3VoiRExCUlAkLCHKOFqAFsHCDVAin10MI10UTDiIytHFwUAemaodqgAPQB+IA) (it's the same thing, just telling tsc to be quiet

[My suggestion](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxxgB4AVAGngFUA+ACigC54T4AfeNURLVEYN+KmQQIAgAwCARJIGIoEAM4gKAIyaUAlExbtKAbgBQRiCAzwoAQiYByRDhwrY1gUJHjDJsyquDkAWxUQGEMwPAUzOAVhMwBeAhh6VQ1DAHoU+Az4AD0AfiA)
The reason I prefer this way is that I'm wary of using complex types in general, they tend to hinder inference. *Maybe* not a problem here but I wouldn't risk it

**Comment by essenmitsosse** [comment]
Ah that one is even better!

**Pull request closed without merging**
