### PR TITLE
auth0-js: make it work with module syntax

### PR DESCRIPTION
**Pull request by csvn**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

-------------------------------------------------------------

Currently, using auth0-js as a global works fine:
```typescript
const auth = new auth0.Authentication({});
```

While working with ES2015 modules, the typings will error:
```typescript
import * as auth0 from 'auth0-js'; // [ts] File '.../auth0-js/index.d.ts' is not a module.
const auth = new auth0.Authentication({});
```

The change I made makes the above code work. I followed the template Typescript suggests for UMD modules (which is the format that `auth0-js` is using). The testfile cannot be both non-module and module (i.e. using global and import) at the same time, but this change does work for both formats.

### CODE REVIEW

**Comment by adrianchia** [comment]
thanks @csvn, I have a pending PR at #14536 which tries to resolve similar issues.

**Comment by csvn** [comment]
Oh sorry, I missed that a PR already existed.

**Comment by csvn** [comment]
@adrianchia I checkout out #14536, and the solutions seem to be a bit different. I suggest that `export default auth0` ([source](https://github.com/adrianchia/DefinitelyTyped/blob/669e7aaa82dff0abfdde240e3fd33cd52af3aa2b/auth0-js/index.d.ts#L514)) be avoided, since `auth0-js` is actually a CommonJS module with no default export ([source](https://github.com/auth0/auth0.js/blob/master/src/index.js#L6-L11)).

The optimal way to import CommonJS modules with ES2015 syntax is:
```typescript
import * as auth0Js from 'auth0-js';
// or
import { Authentication } from 'auth0-js';
```

There is a Typescript setting called `"allowSyntheticDefaultImports": true` whose purpose it is to allow the default import syntax. This allows the following syntax:
```typescript
import auth0Js from 'auth0-js';
```

>_What many bundlers (like webpack/browserify) often does behind the scenes if the `default` import is missing is to set the default value as the whole module (e.g. `module.exports`). Relying on this can be messy and increase confusion though._

**Comment by minestarks** [comment]
@adrianchia , I'll merge this one since per @csvn 's description, this way of exporting is more appropriate for the library. Could you then merge his change so I can take your PR too? Thanks.

**Comment by adrianchia** [comment]
Sure i'll rework my PR

**Pull request merged**
