### PR TITLE
fix(sinon): stub.callsFake should accept parameters

### PR DESCRIPTION
**Pull request by JustinBeckwith**
The `5.0.6` release of `@types/sinon` broke ... a lot of Google npm modules 😆 

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by lumaxis — APPROVED** [review]
Thanks for the quick fix @JustinBeckwith 🙂

**Review by 43081j — CHANGES_REQUESTED** [review]
Can you leave a parameterless test in too?

Looks good otherwise. The recent pr should have been better reviewed and has caused many problems 🙈

**Comment by 43081j** [comment]
Hmm possible duplicate of #656 actually?

**Comment by JustinBeckwith** [comment]
I went ahead and added the parameterless test back in. It's unsurprising that two people filed a PR to fix this, one, it hurt! :)

**Review by 43081j — APPROVED** [review]

**Pull request merged**
