### PR TITLE
[request] fix for Typescript 2.4

### PR DESCRIPTION
**Pull request by nicolashenry**
I get this error with typescript 2.4
```
node_modules/@types/request/index.d.ts(66,15): error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>; (options: (UriOptions & T
O...'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'delete' are incompatible.
          Type '{ (uri: string, options?: TOptions | undefined, callback?: request.RequestCallback | undefined): ...' is not assignable to type '{ (uri: string, options?: TOptions | undefined, callback?: request.Reque
stCallback | undefined): ...'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'options' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'OptionalUriUrl & TOptions'.
                Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl & TOptions'.
                  Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl'.
                    Types of property 'uri' are incompatible.
                      Type 'string | Url' is not assignable to type 'string | undefined'.
                        Type 'Url' is not assignable to type 'string | undefined'.
                          Type 'Url' is not assignable to type 'string'.
```
This pull request should fix this error.

### CODE REVIEW

**Review by joeskeen — CHANGES_REQUESTED** [review]
This looks good, but could you update the tests, adding a case where `Url` is used instead of `string`?

**Comment by DanielRosenwasser** [comment]
Pinging @nicolashenry

**Comment by nicolashenry** [comment]
I realized that the definition was broken because options could not be used with DefaultUriUrlRequestApi methods. So the change is a bit more complicated than I expected for testing it.

**Comment by Torhal** [comment]
So you're aware: Prior to this, I could simply use `response.request.uri.href` in the callback if I wanted to see what the href was after a redirect. Now, to access href, I have to do this:
```
const uri = (response.request as request.OptionsWithUri).uri as URL;
```

**Comment by nicolashenry** [comment]
@Torhal This PR do not change Options (response.request) typing.

**Comment by nicolashenry** [comment]
@minestarks I still get an error with `response.request.uri.href` using the definition before this PR so I doubt that it change anything to this problem.

**Comment by minestarks** [comment]
I think the issue is with the ```.uri``` access here rather than ```.href```.

**Comment by nicolashenry** [comment]
@minestarks Yes but the issue was already here before this PR. 
Using the previous definition : 
image

**Comment by Torhal** [comment]
Interesting. This seems to be a coincidence, then; the code that started throwing the TypeScript error is at roughly the 90% conversion mark from JavaScript, so apparently a pre-existing type error earlier in the chain was masking this error.

**Pull request merged**
