### PR TITLE
[ember] Fix wrongly deprecated Ember.assign

### PR DESCRIPTION
**Pull request by simonihmig**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/polyfills/lib/assign.ts#L22-L46
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by mike-north — CHANGES_REQUESTED** [review]
Looks like this improper deprecation was introduced here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20301/files#diff-49f99cfcf81b26a8c52a0257f0bb0827R3212.

@simonihmig could you also add an identical fix to the v2 types here

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21cd41db1ad200ccc3b096b04a556ab1a32ae02f/types/ember/v2/index.d.ts#L3287-L3291

and

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21cd41db1ad200ccc3b096b04a556ab1a32ae02f/types/ember/v2/index.d.ts#L3134-L3136

**Comment by simonihmig** [comment]
> could you also add an identical fix to the v2 types here

@mike-north sure, done!

**Review by mike-north — APPROVED** [review]
Thanks for this fix!

**Comment by chriskrycho** [comment]
@simonihmig I recommend a nonsense commit and force push removing it to quiet the bot.

**Comment by amcasey** [comment]
We're having CI problems that are causing significant issues for widely consumed packages (esp Node).  We know how frustrating it is and we're working on a fix, which you can track here: https://github.com/Microsoft/TypeScript/issues/29898.  Sorry!

**Pull request closed without merging**
