### PR TITLE
Fix for issue #17103

### PR DESCRIPTION
**Pull request by PublicParadise**
## Fix for issue #17103

- [x] Trivial fix for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17103
- [x] Fixes formatting (Visual Code's [format on save](https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode))

### PR template

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alloy** [comment]
As you mentioned in #17103, vscode reformatted the file. I’m not necessarily opposed to the reformatted, styling (although we should probably have a discussion about styling first), but this mainly makes it real hard to review the PR’s change in functionality. So can you please redo the PR with just the functionality change?

**Comment by minestarks** [comment]
@alloy agreed it would be better to have a separate commit - but in case you still want to review, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17111/files?w=1 to review without the whitespace changes

**Comment by alloy** [comment]
@minestarks Thanks! Didn’t know about that, that’s a very helpful option 👌

**Comment by alloy** [comment]
@PublicParadise bump, can you please redo your PR to have just that change?

**Comment by PublicParadise** [comment]
@alloy I think I am going to close this PR and let @minestarks move forward with the one line change without formatting.

**Review by PublicParadise — COMMENTED** [review]
Looks good!

**Pull request closed without merging**
