### PR TITLE
add promise.prototype.finally.d.ts

### PR DESCRIPTION
**Pull request by slavik57**
Added a new d.ts file: promise.prototype.finally.d.ts

### CODE REVIEW

**Comment by slavik57** [comment]
Why no tests ran on this pull request?

**Comment by mhegazy** [comment]
Here is the new definition checklist:

case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

**Comment by mhegazy** [comment]
Please follow the naming convention and add test files.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
