### PR TITLE
[styled-components] add native definition

### PR DESCRIPTION
**Pull request by sottar**
Fix for #29795

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by rchanaud** [comment]
Thank you for this PR 🙂 

Are your types based on those of Styled Components v3 ? Those types are using:
```typescript
ThemedBaseStyledInterface<any>
```
to define a RN component.

By default this "any" used in the generic is preventing the use of themed re-export of the `styled` object. So [the recommended way of using TS with Styled components](https://www.styled-components.com/docs/api#define-a-theme-interface) can't be achieved.

**Review by Igorbek — CHANGES_REQUESTED** [review]
I believe that original idea was to move react native typings to its own package - `@types/styled-components-native`. It would work at both entry points `styled-components/native` **and** `styled-components`. The reason for that is that `/native` entry point was deprecated and now recommended to use just main entry. This is basically the same way as `@types/react-native` works.

I do understand however, that making this would require effectively copying everything from styled-components and duplicate almost everything. Unfortunately it is the way it is.

**Comment by sottar** [comment]
@Igorbek 
Thank you for your feedback.
it's unfortunately but I can understand the reason.
So I'll try it to create `@types/styled-components-native`.

**Comment by sottar** [comment]
🤔
@Igorbek Do you know how to solve these errors?

**Comment by soutot** [comment]
Thanks for this @sottar! I needed to downgrade to SC 3.x just because of this issue. After this we just need to add ```@types/styled-components-native``` as @Igorbek suggested?

**Comment by bntzio** [comment]
Any news from this PR?

**Comment by limianwang** [comment]
What actually happened to this PR?

**Comment by glauberfc** [comment]
Any news from this PR?

**Pull request closed without merging**
