### PR TITLE
[codemirror] fixed types for modes in EditorConfiguration for CodeMirror

### PR DESCRIPTION
**Pull request by Akashdeep98**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [mode-options](https://codemirror.net/mode/htmlmixed/index.html)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Akashdeep98** [comment]
I have made this change because:

// Homomorphic mapped type over unknown
type T50<T> = { [P in keyof T]: number };
type T51 = T50<any>; // { [x: string]: number }
type T52 = T50<unknown>; // {}

therefore:
type ModeSpec<T> = {
   [P in keyof T]: T[P];
 } & { name: string }; // { name: string };

**Comment by Akashdeep98** [comment]
@mihailik, @nrbernard, @Pr1st0n, @rileymiller, @toddself, @ysulyma, @azoson, @kylesferrazza, @fityocsaba96, @koddsson, @ficristo: Hi, I have been waiting for review on my PR for 2 weeks, It would be great if someone help me figure out if I am missing something. Thanks :)

**Review by koddsson — CHANGES_REQUESTED** [review]
Going from `unknown` to `any` seems like a backwards step to me. `any` essentially turns off the type checker, which runs counter to having a type checker in the first place. I don't know what the solution is, but I'd like to see us trying to make stricter types rather than looser ones.

**Comment by Akashdeep98** [comment]
Hi @koddsson Thanks for you review, I understand your concern and have tried to define stricter types for ModeSpecs. Please review it again. Thanks :)

**Review by koddsson — APPROVED** [review]
This looks good to me 👍🏻

**Comment by Akashdeep98** [comment]
Ready to merge

**Pull request merged**
