### PR TITLE
Remove releaseConnection from Pool interface

### PR DESCRIPTION
**Pull request by move-zig**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mysqljs/mysql/issues/2441

### CODE REVIEW

**Comment by move-zig** [comment]
According to the DefinitelyTyped contribution guide:

>#Private APIs
>We do not support exposing undocumented internal implementation details of libraries in .d.ts files. We follow this more strictly for popular libraries with good documentation e.g. jquery, angular, node etc.

The official word from the mysqljs/mysql team is that Pool.releaseConnection is an undocumented internal implementation detail.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mysql ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mysql@latest/))
was missing the following properties:
1. createQuery
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ad3fbfc59d1a12d17ddbebfd93dfcfa4d568279a
</p>

**Review by amcasey — APPROVED** [review]
Thanks for taking the initiative!

**Comment by move-zig** [comment]
Ready to merge

**Pull request merged**
