### PR TITLE
Add eventHandlers/uploadEventHandlers properties to angular $http con…

### PR DESCRIPTION
**Pull request by joeuy**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

…figuration object https://docs.angularjs.org/api/ng/service/$http#usage

### CODE REVIEW

**Comment by thorn0** [comment]
:-1: What is `EventListenerOrEventListenerObject`? Where is it defined?

**Comment by thorn0** [comment]
Sorry. Found `EventListenerOrEventListenerObject` in lib.d.ts.
Please squash the commits.

**Comment by joeuy** [comment]
It is defined in [lib.d.ts](https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html#libdts) 
and it is what XMLHttpRequest uses in its definition:

addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;

**Comment by thorn0** [comment]
can be merged :+1:

**Pull request merged**
