### PR TITLE
Udate Action interface

### PR DESCRIPTION
**Pull request by radziksh**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://egghead.io/lessons/javascript-redux-reducer-composition-with-objects .

while passing the lesson: https://egghead.io/lessons/javascript-redux-reducer-composition-with-objects  from @gaearon, at 2:33 minute I noticed that Typescript gives an error if I send additional "filter" action in store.dispatch function.

### CODE REVIEW

**Comment by xStrom** [comment]
This seems incorrect. [Other than `type`, the structure of an action object is really up to you.](http://redux.js.org/docs/basics/Actions.html)

I think you may be using the `Redux.Action` type as your action type. That is incorrect. You'll want to use your own types, potentially extending `Redux.Action`.

```typescript
// This would work
interface MyActionA extends Redux.Action {
    filter: string;
}

// This would probably also work
interface MyActionB {
    type: string;
    filter: string;
}
```

**Comment by radziksh** [comment]
@xStrom I would like to point out that this quote (from the page that you gave me) sounds as the definition of mine version of interface:
> Actions are plain JavaScript objects. Actions must have a type property that indicates the type of action being performed. Types should typically be defined as string constants.

and current version of interface sounds as:

> Actions are plain JavaScript objects that must have **only** a type property that indicates the type of action being performed. Types should typically be defined as string constants.

So I don't restrict users for use their own types:
```typescript
interface Action {      
    type: any;
    [key: string]: any;
}
```
all there cases will be correct:
```typescript
store.dispatch({
  type:'SET_VISIBILITY_FILTER',
  filter:'SHOW_COMPLETED',
});

store.dispatch({
  type:'SET_VISIBILITY_FILTER'
});

store.dispatch({
  type:'SET_VISIBILITY_FILTER',
  whateverYouWantProperty:{
    x:{
      y:{
        z:"whatever"}
      }
  },
});
```

by my opinion сurrent interface does not match the definition given on [redux](http://redux.js.org/docs/basics/Actions.html) page. The user shouldn't be limited to define action. Everything that he could write it is already the definition of action. If he wants, he can limit himself by writing the extended interfaces. The main interface shouldn't do this. So what do you think?

**Comment by xStrom** [comment]
Those three dispatch call cases you wrote seem to work just fine with the current definitions. Do those error out for you? If so, please update your pull request with the smallest test case that would fail with the older definitions. It would help me understand what exactly are you currently failing to do, and it would prevent regressions should this be merged.

**Comment by radziksh** [comment]
Ok, I'm wrong. The reason for my confusion is that I took the project where the local typings modules is used. I used to use the command: typings install dt~some-modue --save --global. So I thought that the definitions are taken from DefinitelyTyped but actually definitions are from [other repo](https://raw.githubusercontent.com/andrew-w-ross/typings-redux/2e0b57e18c6240d17fde045573d74e649762437b/redux.d.ts. ).
This implementation was the cause of the typescript error:
```typescript
//This should be extended
export interface IAction {
  type: string | number;
}
export interface IDispatch {
  (action: IAction): IAction;
}
```

and you right, current implementation is correct:
```typescript
interface Action {
  type: any;
}
interface Dispatch<S> {
  <A extends Action>(action: A): A;
}
```
I think I have to write to them about this and not to you :) I close pull-request.

**Pull request closed without merging**
