### PR TITLE
add GetAttributeId and GetAttribute method interface, and GeometryAttribute_Type Property

### PR DESCRIPTION
**Pull request by horizon0514**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
[GeometryAttribute_Type](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl#L28)
[GetAttributeId](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl#L209)
[GetAttribute](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl#L216)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by donmccurdy — APPROVED** [review]
Thanks!

**Comment by horizon0514** [comment]
Ready to merge

**Comment by javagl** [comment]
@donmccurdy @horizon0514 Hoping that a comment here is the least intrusive or annoying way to bring this up: 

Should't the type definitions match the IDL at https://github.com/google/draco/blob/9f856abaafb4b39f1f013763ff061522e0261c6f/src/draco/javascript/emscripten/draco_web_decoder.idl ? 

Right now, there are several elements that are not part of the TypeScript definition. This refers low-level things like `DT_BOOL`, but also structures like `AttributeQuantizationTransform`. 

Would it make sense to update the definitions to match the IDL? 

(Maybe even by giving something like https://github.com/giniedp/webidl2ts a try, in doubt with manual tweaks for compatibility?)

**Comment by donmccurdy** [comment]
Ideally they should match the IDL, yes! If this can be automated, that would be ideal. I've contributed types for areas of the interface that I have used and tested, but I don't have bandwidth to do that for the complete Draco API.

**Pull request merged**
