### PR TITLE
pino: use record type argument for log formatter

### PR DESCRIPTION
**Pull request by kjarmicki**
This pull request changes the` pino.LoggerOptions.formatters.log` argument type from `object` to `Record<string, unknown>`. The reason for this change is due to the fact that the index signature is missing in the `object` type, so it has to be type-casted to become usable:

```ts
log(payload) { // inferred as object
  payload.context = 'something'; // type error 
  const payloadRecord = payload as Record<string, unknown>;
  payloadRecord.context = 'something'; // ok
}
```

This change should be backward-compatible (see test cases) because it uses a narrower type for input and leaves `object` as a return type.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino/blob/master/lib/tools.js#L112
Here pino itself is using an index to access log keys, so this change is type-safe.

### CODE REVIEW

**Comment by kjarmicki** [comment]
@psnider @BendingBender @screendriver @paambaati @alferpal @mortiy @lummish @raoulus @Cooryd @AdamVig @austin-beer @Pegase745 would any of you folks be so kind to take at this PR during this week? 🙂

**Review by aferrando-tid — APPROVED** [review]

**Comment by alferpal** [comment]
Sorry, approved it with my work account 🤦🏼

**Review by alferpal — APPROVED** [review]

**Comment by alferpal** [comment]
@kjarmicki could you request review again from the @aferrando-fon account, so that it's not approved by that account anymore, please?

**Comment by kjarmicki** [comment]
@alferpal trying to, but clicking on re-request review doesn't seem to do anything, maybe it sees that there were no changes and refuses to re-request 😞  Perhaps it would work to request changes from that account?

**Comment by alferpal** [comment]
Let's leave it like that for now, I don't think it will be a problem, and in any case there's the comments on the PR.

**Comment by kjarmicki** [comment]
Ok 🙂 Thanks for the approve!

**Comment by kjarmicki** [comment]
Ready to merge

**Pull request merged**
