### PR TITLE
[yup]: add support for string.uuid

### PR DESCRIPTION
**Pull request by dncrews**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup/commit/8f2bd2b1c33615e7e68b90796d0bf6619fc7c51c
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by dncrews** [comment]
Apparently this version isn't published yet. [Waiting on this issue](https://github.com/jquense/yup/issues/986)

**Comment by iansan5653** [comment]
@dncrews you may want to make this PR a draft so it doesn't get merged early by accident

**Comment by hhsnopek** [comment]
Looks like yup@0.29.3 was published which includes `uuid`, any word on when this will be merged & published?

**Review by iansan5653 — APPROVED** [review]

**Comment by dncrews** [comment]
Ready to merge

**Comment by iansan5653** [comment]
Hey @dncrews I just realized the title of the PR has [yum] instead of [yup]. Can you edit it to fix that? It just helps a lot with searching since there's 50k issues to sort through

**Comment by thebitrock** [comment]
validator don't support UUIDv8 :/

**Pull request merged**
