### PR TITLE
[CodeMirror] add a few missing property on TextMarkerOptions

### PR DESCRIPTION
**Pull request by Carreau**
Also the all files lines end in CR,LF.  Would you mind if I send a PR that `s/CRLF/\n/g` ?

### CODE REVIEW

**Comment by Carreau** [comment]
Actually there were a few other missing options. Now included.

**Comment by vvakame** [comment]
*codemirror/codemirror.d.ts*

to author(@mihailik). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
I like CR. but it's okay to not have to worry too much.

**Comment by Carreau** [comment]
Ok, no issues in having CR, it just strucked me as I never see them. 

also these a "just" copy and pasted from [this section codemirror docs](http://codemirror.net/doc/manual.html#api_marker), plus the question mark to make them optional.

**Comment by vvakame** [comment]
@Carreau okey, thanks mate!

**Comment by Carreau** [comment]
Thanks !

**Pull request merged**
