### PR TITLE
Added ngcordova definition

### PR DESCRIPTION
**Pull request by Zorgatone**

### CODE REVIEW

**Comment by masimakopoulos** [comment]
There is another pull request regarding ngcordova #6510 with much less definitions, but including tests, doc comments etc. Maybe collaborate for a complete solution?

**Comment by Zorgatone** [comment]
This is what I've been using in the last year. I used these definitions from another repo, but I can't remember the original author.

I'll review the PR to include comments and tests

**Comment by masimakopoulos** [comment]
@Zorgatone maybe this guy? https://github.com/mvidailhet/ngcordova-typescript-definitions Been waiting for ages for a pull request according to https://github.com/mvidailhet/ngcordova-typescript-definitions/issues/1. Glad you are up to the task.

**Comment by Zorgatone** [comment]
Yes, if @mvidailhet agrees, we can modularize this, add tests and comments and resubmit the pull request

**Comment by ksachdeva** [comment]
I plan to finish all the definitions in a week time frame. Reason I am taking time is because I want to have a full fledged demo application using the typings (please see this - https://github.com/ksachdeva/ngCordova-typescript-demo). IMHO it is not the type definition but writing a demo application that is showing how to use them properly is what takes time.

**Comment by mvidailhet** [comment]
@Zorgatone Sure, you can totally use and modularize what the file I started. It's meant for that. Tell me if you need help.

Sorry if you waited for ages @masimakopoulos I had a lot to do the last couples weeks.

**Comment by Zorgatone** [comment]
I will try to refactor the code in the next few days, or in the weekend and let you know

**Comment by masimakopoulos** [comment]
Didn't mean to whine @mvidailhet, I am thankful you wrote all these definitions, the comment was mostly towards me, that although I waited for the pull request I didn't go ahead and create it as @Zorgatone did. Let me know if I can lend a hand guys to atone myself.

**Comment by Zorgatone** [comment]
I'm closing this, and I will open a new PR

**Pull request closed without merging**
