### PR TITLE
[@types/node]: Fix typing of UserInfo.shell to be correct to behaviour and documentation

### PR DESCRIPTION
**Pull request by Nokel81**
Quote from https://nodejs.org/docs/latest-v18.x/api/os.html#osuserinfooptions

> Returns information about the currently effective user. On POSIX platforms, this is typically a subset of the password file. The returned object includes the username, uid, gid, shell, and homedir. On Windows, the uid and gid fields are -1, and shell is null.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Versions:
- v20
- v18 (needs to be backported)

### CODE REVIEW

**Review by LinusU — COMMENTED** [review]
LGTM 👍

**Review by Semigradsky — COMMENTED** [review]
Please add also to ts4.8 folders

**Comment by Semigradsky** [comment]
Add also to v16?

**Comment by Nokel81** [comment]
@Semigradsky done

**Comment by Semigradsky** [comment]
`ndoe`, `node/ts4.8`, `node/v18/ts4.8`, `node/v16` and `node/v16/ts4.8` for full complect =)

**Comment by Nokel81** [comment]
Ah okay, I think I missed some

**Comment by WilcoBakker** [comment]
@Nokel81 could you please add the change to `v18/ts4.8` and `v16/ts4.8` as well?

**Comment by Nokel81** [comment]
@WilcoBakker It seems that @peterblazejewicz has done that

**Review by Semigradsky — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@Nokel81 thanks!

**Comment by jakebailey** [comment]
@typescript-bot ping

(This may cause the status to break temporarily, we're working through the new infra changes at the moment)

**Comment by Nokel81** [comment]
Ready to merge

**Pull request merged**
