### PR TITLE
[@types/shopify-buy] Add language to the Config interface

### PR DESCRIPTION
**Pull request by Gomah**
If the Shopify store supports multiple languages, the Storefront API can return translated resource types and fields.

```ts
// Initializing a client to return translated content
const clientWithTranslatedContent = Client.buildClient({
  domain: 'your-shop-name.myshopify.com',
  storefrontAccessToken: 'your-storefront-access-token',
  language: 'ja-JP'
});
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Shopify/js-buy-sdk#initializing-the-client
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
N/A as the change require adding locales to the existing shopfront.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## shopify-buy ([<kbd>unpkg</kbd>](https://unpkg.com/browse/shopify-buy@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'shopify-buy'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 76fa59235af76db0ff08c2e2b24712850832b3ab
</p>

**Review by chrisworman-pela — APPROVED** [review]

**Review by straiforos — APPROVED** [review]
This is an optional parameter added to the interface which is safe for addition and extension as far as I am aware, test may want to be revisited if this could be added at the moment this will suffice and thank you for your contribution @Gomah! 

I double checked on the current API Docs for this, seems like it could be nonoptional so if tests do not break I would leave it be.

**Review by rbuckton — APPROVED** [review]

**Comment by straiforos** [comment]
@Gomah may I set this to merge or if you would like put in the comment ready to merge.

I would like this to not impeed your work.

**Comment by straiforos** [comment]
Oops hopefully that doesn't merge it 🤦🤦‍♂️

**Comment by Gomah** [comment]
Ready to merge

**Pull request merged**
