### PR TITLE
Add missing chrome-app to the @types/chrome pkg

### PR DESCRIPTION
**Pull request by alexeagle**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Based on mhegazy comment at https://github.com/Microsoft/types-publisher/issues/68#issuecomment-252104274

### CODE REVIEW

**Comment by mhegazy** [comment]
waiting on CI server

**Comment by mhegazy** [comment]
@alexeagle looks like there is a reference to `chrome.d.ts` that should be `index.d.ts`

**Comment by alexeagle** [comment]
I have commit in this repo, so you can just "LG if Travis says so" and we can skip a step next time.

**Comment by mhegazy** [comment]
need to get #11835 in first to fix CI server tests.

**Comment by fortuna** [comment]
FYI, it seems PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11835 is now merged into `types-2.0`.

**Comment by mhegazy** [comment]
I have fixes for the CI tests in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11913

**Comment by mhegazy** [comment]
fixed by #11913

**Pull request closed without merging**
