### PR TITLE
[node] Add aborted to http.IncomingMessage

### PR DESCRIPTION
**Pull request by entropitor**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: As defined here: https://nodejs.org/api/http.html#http_message_aborted
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by Flarna — CHANGES_REQUESTED** [review]
please update additionally node/http.d.ts.

**Review by Flarna — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Comment by entropitor** [comment]
@RyanCavanaugh It seems like the CI is failing but I get the same errors on master

**Comment by peterblazejewicz** [comment]
@entropitor
That's untintended effect of TS@next I think:
https://github.com/microsoft/TypeScript/issues/37556

**Comment by entropitor** [comment]
@peterblazejewicz so we should be good to go on the CI side?

**Comment by peterblazejewicz** [comment]
Yes, at the moment local and CI tests can fail for no related reason. I think CI will be restarted, when problem is sorted out.

**Comment by peterblazejewicz** [comment]
@entropitor 
you should be able to run local `npm test` now to verify, push update or empty commit to restart CI
https://github.com/microsoft/TypeScript/pull/37610

**Comment by entropitor** [comment]
@peterblazejewicz we should be good to go now! :D

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
