### PR TITLE
wavesurfer.js: format everything with prettier

### PR DESCRIPTION
**Pull request by tmladek**
following the README, i.e. running
`npm run prettier -- --write types/wavesurfer.js/**/*.ts`

PR created as per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59201#issuecomment-1062927109

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59201#issuecomment-1062927109)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wavesurfer.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wavesurfer.js@latest/))
was missing the following properties:
1. debounce
1. Observer
1. absMax
1. clamp
1. fetchFile

<details>
<summary>as well as these 10 other properties...</summary>
<p>frame, getId, ignoreSilenceMode, max, min, preventClick, requestAnimationFrame, style, withOrientation, WaveSurfer</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d5206a9a60c6ba2fc372bdc456e18750049337b3
</p>

**Review by caugner — APPROVED** [review]
LGTM, thanks!

**Review by caugner — CHANGES_REQUESTED** [review]
Oh, just a quick nit: Can you rename the PR title to start with `wavesurfer.js: `? Thanks!

**Comment by tmladek** [comment]
> Oh, just a quick nit: Can you rename the PR title to start with `wavesurfer.js: `? Thanks!

Oh right of course, done :)

**Review by thijstriemstra — APPROVED** [review]

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Ready to merge

**Pull request merged**
