### PR TITLE
requirejs.RequireConfig

### PR DESCRIPTION
**Pull request by seawerst**
Add a missing signature for urlArgs property of the RequireConfig object.
Documentation in the file.

Needs review by a DefinitelyTyped member, per PR template

### CODE REVIEW

**Comment by andy-ms** [comment]
`{ (id: string, url: string): string; }` could just be `(id: string, url: string): string`. Looks good otherwise.

**Comment by seawerst** [comment]
Is this required as this notation is less used in the file. I was trying to keep the same format.

**Comment by andy-ms** [comment]
You might have gotten confused by the type `{ [key: string]: any; }`, which is an index signature and does have to be written that way. `{ (key: string): any; }` looks similar but would be a function signature instead, and plain function signatures in that file are written in the arrow (`(key: string) => any`) style. 

(For something like `RequireDefine` with multiple call signatures the curly brace style is needed, but for simple functions prefer arrows.)

**Comment by seawerst** [comment]
I think I managed to update my pull request. By error, I create two new pull that I closed and deleted. I'm new in the git world.

**Pull request merged**
