### PR TITLE
Catch up assert typesVersions <= 3.6

### PR DESCRIPTION
**Pull request by jablko**
#49363 and #49462 for #50311. Incorporate #50311 into typesVersions <= 3.6 and into `types/assert`.

### CODE REVIEW

**Review by Flarna — APPROVED** [review]
Can't judge the changes in pipeline files but node looks fine.

**Comment by weswigham** [comment]
Uhh, @sandersn you know if you wanna do this this way? Or should we have a `dtslint-runner` change?

**Comment by jablko** [comment]
I'm happy to push a revision without `CI.yml`/`azure-pipelines.yml`, it just won't pass the CI thanks to (I believe?) an unrelated issue with `types/mongoose` (v5) and TypeScript 4.2? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50683/checks?check_run_id=1718094202#step:7:1991

`types/mongoose` is included because it depends on `types/node`.

**Comment by sandersn** [comment]
Yes, please revert the CI changes. The mongoose failure is definitely unrelated; it's due to microsoft/typescript#42337 which should be fixed during the 4.2 beta. It's better to merge this with mongoose failing than to patch the CI script.

**Comment by jablko** [comment]
@sandersn Thanks, done :heavy_check_mark:

**Pull request merged**
