### PR TITLE
Added definition for node-apn

### PR DESCRIPTION
**Pull request by zenorbi**
This is my first real definition commit. Please bring to my attention if I missed something or did something wrong.

### CODE REVIEW

**Comment by argon** [comment]
Nice work.

**Comment by Zenorbi** [comment]
@argon: Thank you for the amazing library!

**Comment by vvakame** [comment]
*apn/apn.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/apn
  * http://bower.io/search/?q=apn
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (apn/apn-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@Zenorbi thank you for your contributions.
please rename apn/apn-test.ts to apn/apn-tests.ts

**Comment by Zenorbi** [comment]
@vvakame: Done, thank you for noticing.

**Comment by vvakame** [comment]
@Zenorbi thanks mate!

**Pull request merged**
