### PR TITLE
Added highcharts.zoomOut() method

### PR DESCRIPTION
**Pull request by petrkoutnysw**

### CODE REVIEW

**Comment by damianog** [comment]
Hi @petrkoutnysw 

By http://api.highcharts.com/highcharts#Chart I did not find any evidence of "zoomOut"
could you point us an Highcharts API reference with zoomOut method?

Thanks

**Comment by petrkoutnysw** [comment]
Source code is here:
https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js

Also I found it missing when working with that.

**Comment by baltie** [comment]
This function is mainly for supporting the "Reset zoom" button which is shown when you specify a zoomType in the chart options and the user zooms in. While the function is there and part of the Chart.prototype, it is not part of the official API and also undocumented.

In my opinion, we should not add this to the definitions file. However @petrkoutnysw , you are free to make your own local extensions to the definitions and add the function there to HighchartsChartObject.

**Comment by petrkoutnysw** [comment]
Well I disagree - the function is available and programmer can use it. I dont think that the fact it is missing in official API is reason for ignoring it in d.ts. Btw having one source for typings is the main reason of existing this project. Everyone can create his own typings but that is very bad practice.

**Comment by baltie** [comment]
That wasn't what I meant. What I meant is that you could have a file in your project called highcharts.local.d.ts containg only this:
`interface HighchartsChartObject {
    zoomOut(): void;
}`

Then the `zoomOut` function would be added to the interface definition in your project.

If we should freely add all the available functions and properties that are undocumented, and there are a lot of them, we would face maintenance issues down the road where the functions abruptly changes. I'd also rather not promote functions that aren't part of the API, giving users of the definitions the impression that the function is supported while it could be removed or had its name or functionality changed at any time.

**Comment by damianog** [comment]
I agree with @baltie  

I looked to that function and there are many people that ask for this undocumented functionality,
someone used for example:

`chart.xAxis[0].setExtremes(null,null);`

so @petrkoutnysw consider to open an issue to Highcharts forum to have that function in public API,
and please do not be angry for our fussiness

**Comment by petrkoutnysw** [comment]
I am not angry, I just wanted to describe my point of view :) no offense.

**Comment by vvakame** [comment]
> consider to open an issue to Highcharts forum to have that function in public API

👍

**Comment by mhegazy** [comment]
Closing for now. The recommendation is to add a local definition as noted by @baltie  in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9646#issuecomment-226210368. Please resubmit when this is added to the public API

**Comment by Timppe** [comment]
This is now in the public API, at least the current version, don't know if the version these types are supposed to support contains zoomOut(), but I think it should be reflecting the current, however that's another discussion. I had to add it locally today when I found out this is not in the types. I noticed a lot of other stuff is not in the types as well, but that's also not related to this PR

**Pull request closed without merging**
