### PR TITLE
Fixed the types for pupeteer/elementhandle type method

### PR DESCRIPTION
**Pull request by paynoattn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #21210 
- [x] Increase the version number in the header if appropriate.

See #21210 for why this PR is being submitted.

### CODE REVIEW

**Comment by paynoattn** [comment]
@ondrejsevcik

**Review by cdeutsch — APPROVED** [review]
Good catch 👍

**Review by marvinhagemeister — APPROVED** [review]
Awesome, thanks for finding this!

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Pull request merged**
