### PR TITLE
Added className to SVG attributes

### PR DESCRIPTION
**Pull request by ccapndave**
Added `className` to SVG nodes (since these can be targeted with CSS)

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3 @vsiao @RyanCavanaugh @jbrantly can anyone review this PR?

**Comment by jbrantly** [comment]
Seems OK to me.

I think that the DOMAttributes interface was meant to keep stuff that was common between HTML and SVG. In that case you might consider just moving this to DOMAttributes and removing from HTMLAttributes (and SVGAttributes). But this way doesn't hurt anything.

**Comment by pspeter3** [comment]
I agree with @jbrantly. I would prefer it on DOM Attributes.

**Comment by JKillian** [comment]
+1 to adding it to DOM Attributes. I'd also suggest moving `id` as well unless there's a reason to not do that.

**Comment by ccapndave** [comment]
Moved `className` and `id` to DOMAttributes as suggested.

**Comment by jbrantly** [comment]
:+1: from me

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
