### PR TITLE
[react-native] Bump version 0.52

### PR DESCRIPTION
**Pull request by timwangdev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react-native/releases/tag/v0.52.0>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
👍

**Comment by alloy** [comment]
@timwangdev Can you tell me what this effectively changes? Is it just to signal to people that these typings will work with RN 0.52? Because people can install whatever version of the typings they want, right?

**Comment by timwangdev** [comment]
@alloy When I tried to upgrade my project package.json `react-native` version to `~0.52.0` and I set the same version to `@typed/react-native`. Then I got an error that the version is invalid. That's the main purpose of this PR to keep the version sync.

People still can install all the history version from npm.

**Comment by alloy** [comment]
Ok, yeah I guess that’s a reasonable expectation of people.

**Pull request merged**
