### PR TITLE
[keep-network__tbtc.js] Unmangle scoped package names

### PR DESCRIPTION
**Pull request by jablko**
#47115

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## keep-network__tbtc.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/keep-network__tbtc.js@latest/))
was missing the following properties:
1. BitcoinHelpers
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b624fb574da924e118d56854e482c8b0c71839c1
</p>

**Comment by corollari** [comment]
I'm not sure what this PR adds, given that the package already works fine as is.

**Review by amcasey — APPROVED** [review]

**Review by corollari — CHANGES_REQUESTED** [review]
Why change it if it's currently working fine? See my previous comment.

**Comment by jablko** [comment]
@corollari That's a good question. This is [the change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19237) that introduced the advice to [the README](https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-scoped-packages), but there isn't any context there either.

It's clear why we need the path mapping in some cases, and don't just use the mangled name universally. You need to `import TBTC from '@keep-network/tbtc.js'` in a `.ts` file that you plan to execute, or Node.js or whatever won't find the `.js` implementation. `.d.ts` files aren't affected, they're only for compilation, but you probably need to `import TBTC from '@keep-network/tbtc.js'` there too, or users will be surprised at having to `declare module 'keep-network__tbtc.js'` to augment `@keep-network/tbtc.js`? There could be additional reasons to use the path mapping vs. the mangled name, and I'd be curious to know them.

These two reasons don't apply to `keep-network__tbtc.js-tests.ts` assuming you don't plan to try running it. One of your (transitive) dependencies/test dependencies *could* augment `@keep-network/tbtc.js`, in which case you'd get different results with/without the unmangled name. Maybe the best reason to use it is to keep things simple and consume the types in the way you expect users to (presumably `import TBTC from '@keep-network/tbtc.js'`). Also, some uniformity makes it simpler to enforce the cases that do require the path mapping, without considering the exceptions that don't.

Are there reasons/perspectives I haven't thought of?

**Review by corollari — APPROVED** [review]

**Comment by corollari** [comment]
Thanks for the explanation @jablko, I agree with the points you make.

**Comment by jablko** [comment]
@corollari Awesome, thanks for reviewing! Ready to merge.

**Comment by corollari** [comment]
Ready to merge

**Pull request merged**
