### PR TITLE
fix(datastore-core): correct DT owner handle

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This fixes what seems to be a simple omission.

/cc @carsonfarmer

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
This needs explicit approval from @carsonfarmer

**Comment by carsonfarmer** [comment]
I'm not sure how to officially "approve"? I can't seem to be able to review it per se. But it gets my 👍 !

**Comment by peterblazejewicz** [comment]
> I can't seem to be able to review it per se.

This is what we're trying to fix here. One cannot add someone else handle without a consent, simple as this 😄

**Comment by peterblazejewicz** [comment]
@orta would you mind? thx!

**Pull request merged**
