### PR TITLE
Align Matchers type with the one from `expect` for @testing-library/jest-dom

### PR DESCRIPTION
**Pull request by Vinnl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/testing-library/jest-dom/issues/426#issuecomment-1623790932
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

As per https://github.com/testing-library/jest-dom/issues/426#issuecomment-1623790932, I hope this fixes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65987#discussioncomment-6371630, ~~but I can't verify because I don't know how to reproduce~~ (edit: someone who could reproduce [has verified it](https://github.com/testing-library/jest-dom/issues/426#issuecomment-1624120507), and so has [someone else](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65987#discussioncomment-6378257)), and I'm not 100% confident about what I'm doing :/ However, potentially this supersedes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65990 and fixes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65987.

### CODE REVIEW

**Comment by Vinnl** [comment]
We got confirmation at https://github.com/testing-library/jest-dom/issues/426#issuecomment-1624120507 that this does indeed resolve the reported issue, while it still fixes https://github.com/testing-library/jest-dom/issues/426 as well :tada:

**Review by G-Rath — APPROVED** [review]

**Review by abhi-works — APPROVED** [review]
Works locally

**Comment by benjdlambert** [comment]
Could we perhaps get these changes merged? Our builds are still broken :(

**Review by jgoz — APPROVED** [review]

**Comment by Vinnl** [comment]
Haha no it's not been a few days typescript-bot, but unfortunately, like in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65981:

> Unfortunately I couldn't add tests for this, since the types for @jest/globals do not come from DefinitelyTyped. Happy to take suggestions on how to add them after all.

**Review by andrewbranch — APPROVED** [review]

**Comment by Vinnl** [comment]
Ready to merge

**Comment by DevinXian** [comment]
After a few times test, here is another solutions:

1. install package `@jest/expect`

2. write to `globals.d.ts`

```typescript
import type { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers';

declare module '@jest/expect' {
  export interface Matchers<R extends void | Promise<void>, T = unknown> extends TestingLibraryMatchers<typeof jestExpect.stringContaining, R> { }
}
```

`@jest/expect` depends on `expect`, that's why this works. Just as `@jest/globals` does.

**Comment by DevinXian** [comment]
After a few times test, here is another solutions:

1. install package `@jest/expect`

2. write to `globals.d.ts`

```typescript
import type { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers';

declare module '@jest/expect' {
  export interface Matchers<R extends void | Promise<void>, T = unknown> extends TestingLibraryMatchers<typeof jestExpect.stringContaining, R> { }
}
```

`@jest/expect` depends on `expect`, that's why this works. Just as `@jest/globals` does.

**Pull request merged**
