### PR TITLE
update react-native image source typing

### PR DESCRIPTION
**Pull request by dannycochran**
When requiring in an image path (require('./path/to/image.png')), the require resolves to a number.

This number can be passed directly into the image source, e.g:

```javascript
const imageId = require('./path/to/image.png');
return <Image source={imageId} />;
```

I'm not sure if this has official documentation anywhere but this is how I've been rendering images for some time:

https://facebook.github.io/react-native/docs/image.html#source

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/image.html#source
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by iRoachie** [comment]
What version of typescript are you using? I have never seen this as an error. This is how I load images all the time. Are you adding this out of thought, or does it actually throw a warning?

**Comment by dannycochran** [comment]
@iRoachie Typescript 2.4.2

You're right -- I should have specified a little more what's happening. Using "require" returns an "any" type. But if you require in some image, then pass it around elsewhere and type it as number (which it is), the source attribute of an Image no longer accepts the argument, e.g:

```javascript
import * as React from 'react';
import { Image } from 'react-native';
class ImageExample extends React.Component<{ requiredImage: number }, {}> {
  render() {
    // TypeScript will complain about this.
    return <Image source={this.props.requiredImage} />;
  }
}

class SomeParentClass extends React.Component<{}, {}> {
  render() {
    return <ImageExample requiredImage={require('./path/to/image.png')} />;
  }
}
```

So, you could certainly keep the "requiredImage" as an any type, but that's dangerous and would allow you to pass in anything into the image source.

**Comment by huhuanming** [comment]
is it better to do like this.

```
import * as React from 'react';
import { Image } from 'react-native';
class ImageExample extends React.Component<{ requiredImage:  ImageURISource | ImageURISource[] }, {}> {
  render() {
    // TypeScript will complain about this.
    return <Image source={this.props.requiredImage} />;
  }
}

class SomeParentClass extends React.Component<{}, {}> {
  render() {
    return <ImageExample requiredImage={require('./path/to/image.png')} />;
  }
}
```

**Comment by dannycochran** [comment]
@huhuanming hmm I disagree -- that means in "ImageExample" a dev would expect an ImageURISource or an array of ImageURISources, neither of which is the case.

There's a number of ways to work around this (which I am), but ultimately if the "source" attribute can accept a number, that should be reflected in the typings.

**Comment by huhuanming** [comment]
I have read through the source and found this  in  `react-native.d.ts`

```
function require(name: string): any;
```
So the code includes ‘require’ cannot be work now.

But the image source number is made by webpack, maybe we need a type to express the number of webpack source

**Comment by bowdenk7** [comment]
@DanielRosenwasser are you familiar with how webpack resolves these requires?

**Comment by aozgaa** [comment]
Pinging @DanielRosenwasser.

**Comment by DanielRosenwasser** [comment]
This thing can be

* An object with a `uri` and a `headers`
* **A `number`**
* An array of objects with a `uri`, `width`, and `height`.

So 👍

**Comment by alloy** [comment]
@dannycochran @DanielRosenwasser Rather than completely leak the implementation details, would it be helpful to define a type alias of `number` that’s called e.g. `ImageRequireSource` ?

**Comment by DanielRosenwasser** [comment]
That also sounds reasonable since I recall there's other types in the .d.ts file which are like that.

**Comment by alloy** [comment]
@dannycochran Can you take a stab at that?

**Comment by dannycochran** [comment]
@alloy & @DanielRosenwasser -- done, I think? Not sure if the change I just made is what you intended.

**Comment by alloy** [comment]
Yeah that looks good to me 👍 That CI failure is legit, though. I’ll merge tomorrow if nobody disagrees.

**Comment by alloy** [comment]
Thanks 🙏🏽

**Pull request merged**
