### PR TITLE
[react-window] Add itemData typing instead of `any`

### PR DESCRIPTION
**Pull request by henrywarhurst**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by jgoz — CHANGES_REQUESTED** [review]
Though I like this change, it's probably a breaking one since those `T`s will default to `unknown` instead of `any` (I think?). This kind of thing would probably need to wait for a new major version of `react-window`.

As an alternative, you could use `<T = any>` everywhere and make the data type opt-in.

**Comment by henrywarhurst** [comment]
@jgoz that's fair enough - it's definitely a breaking change.

I think the `<T = any>` is a decent step at this stage and then we can just make it `<T>` quite easily when that major version jump eventually happens in `react-window`?

**Comment by jgoz** [comment]
Yeah that make sense to me. Thanks for taking this on.

One additional thing you could do would be to create the tests for v2 now, which include the use of `T` and then leave the current tests unchanged. I'm thinking copying the current tests to a new file and adding type args. That way we are guarding against breaking changes by not changing the current tests and then when v2 comes around we can simply move the v1 tests file to the v1 dir.

Hope that made sense...

**Comment by henrywarhurst** [comment]
@jgoz CI wanted me to add an index.d.ts in the v2 directory. Is that fine?

**Comment by jgoz** [comment]
Hmm, I'm not sure we want to add actual v2 typings at this point since there isn't a v2 of the real library.

Sorry for all the requests, but instead of adding a v2 folder at all, could you just copy the v2 tests into the current tests file (maybe with a comment)? That way the first half of the tests will be for the `any` version and the second half for `T`. Then when the real v2 happens we can split the test file.

**Comment by henrywarhurst** [comment]
@jgoz no worries! Happy to make the required changes so this is how you want it.

I've dropped the v2 directory and added the typed tests to the end of the existing tests file, along with a comment explaining why they're there

**Review by jgoz — APPROVED** [review]
👍 this is great, thanks for taking this on!

**Comment by henrywarhurst** [comment]
Ready to merge

**Pull request merged**
