### PR TITLE
A JsonLdArray is an array of JsonLdObj's not an array with a single JsonLdObj

### PR DESCRIPTION
**Pull request by agustaf9**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: SEE TEST
- [NA] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by agustaf9** [comment]
Please advise on how I can fix the test:
image
image

https://github.com/agustaf9/DefinitelyTyped/blob/bebe3fc0d401ea6acdeb9fcae79431971828ab18/types/jsonld/jsonld-spec.d.ts#L8-L9

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/jsonld/jsonld-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b79101ea0082736fd6a1c727cac6552502929b7b
</p>

**Comment by sandersn** [comment]
I don't think there's a great way to fix the test except to change the ExpectType to NodeObject[] -- since JsonLdArray is just an alias, and ExpectType just checks whatever the hover says (the first line, it appears, in fact).

**Review by sandersn — APPROVED** [review]
I think it's fine as-is, although having an `ExpectType NodeObject[]` would be good too.

**Comment by agustaf9** [comment]
Ready to merge

**Pull request merged**
