### PR TITLE
[react-intl] FormattedMessage children prop

### PR DESCRIPTION
**Pull request by osdiab**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L130
- ~[ ] Increase the version number in the header if appropriate.~
- ~[ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

Pretty sure the argument for `children` should be a `string[]`, given what `formatMessages` returns.

### CODE REVIEW

**Comment by tillwolff** [comment]
_I can have a look at wednesday_

**Comment by brikou** [comment]
@tillwolff I really don't why formattedMessage is a string, `children?: (formattedMessage: string[]) => React.ReactNode;` 

Is it a bug? I guess

**Comment by tillwolff** [comment]
@brikou I dont really get your point, but when I check the react-intl code here: 
https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L130

Then the defintion should be `children?: (...nodes: string[]) => React.ReactNode;`

Would you agree to that?

**Comment by davidspiess** [comment]
`children(...nodes);` destructures the nodes string array to a string.

So the correct typings would be `children?: (formattedMessage: string) => React.ReactNode;`

The following valid code throws currently an error in my application as `placeholder` expects a string.

```jsx
<FormattedMessage id="guestInfos.email.placeholder">
  {text => <Field type="email" name="email" placeholder={text} />}
</FormattedMessage>
```

**Pull request merged**
