### PR TITLE
Improve the intellisense of lazypipe

### PR DESCRIPTION
**Pull request by neurolag**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I've just noticed that there is no IntelliSense when using `lazypipe`.
This PR adds auto-completion to the `lazypipe`-module.

### CODE REVIEW

**Comment by manuth** [comment]
Uhm... Guys I need some help
This solution doesn't seem to work for methods with multiple overloads.

***test.d.ts***
```ts
import "node";
declare function example(name: string): NodeJS.ReadWriteStream;
declare function example(options: { name: string, author: string }): NodeJS.ReadWriteStream;
```
***index.ts***
```ts
import lazyPipe = require("lazypipe");
import test = require("./test");

// This here works
lazyPipe(test, { name: "", author: "" });
// While this here does not
lazyPipe(test, "");
```

**Comment by manuth** [comment]
I've created an issue in the TypeScript repository: https://github.com/microsoft/TypeScript/issues/31716
I'll notify you guys as soon as my PR is ready.

**Comment by amcasey** [comment]
@manuth, I believe that's a known (and intentional) limitation of TS's type inference - a more general system would be too expensive.  I think you might be able to work around the issue by using a union type `nameOrOptions: string | { name: string, author: string }`.

**Comment by manuth** [comment]
@amcasey Well, ya see - actually `lazypipe.pipe(fn, args)` should take the arguments of `fn`, no matter what nature they have and what overloads `fn` has.

This means I sadly cannot work with union types.

Do you have any other idea?

**Comment by amcasey** [comment]
Sorry, I blanked and read your example backwards - I thought it was `example` you were trying to get working, rather than `pipe`.

I think you're definition is correct and you're just hitting a limitation of the type system.

For now, I think you'll either need to use looser types (e.g. allowing `any`) or accept that some callers will see errors. 😞

**Comment by manuth** [comment]
Alright - thanks for your support 🎉

**Pull request closed without merging**
