### PR TITLE
update types for fancade-editor beta

### PR DESCRIPTION
**Pull request by bricked-dev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.fancade.com/wiki/fancade-web#editor-scripting
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by brckd** [comment]
I had to fix the owner definition, because it got removed after renaming my account ¯\_(ツ)_/¯

**Comment by brckd** [comment]
The CI fails, because it thinks that the single element tuple I used for defining a single function argument was an accident :/

**Comment by brckd** [comment]
I guess `[key: number, ...args: []]` works as a single tuple ¯\\\_(ツ)_/¯

**Review by jakebailey — APPROVED** [review]
Just to note it, I checked and it was an account rename and this is the same owner.

Need to update ghostbuster to ask maintainers to check for account renames before merging 😓

**Comment by brckd** [comment]
thanks for approving the pr :D

**Comment by brckd** [comment]
ready to merge

**Pull request merged**
