### PR TITLE
Add missing maxFreeSockets property of Agent class in node

### PR DESCRIPTION
**Pull request by akihikodaki**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.) (I found no test for property references of `http.Agent` so I didn't add one. It also doesn't make sense for this case.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v8.x/api/http.html#http_agent_maxfreesockets
- [X] Increase the version number in the header if appropriate. (not this case)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (not this case)

### CODE REVIEW

**Review by Flarna — CHANGES_REQUESTED** [review]
Could you please add the same to latest node typings?

**Comment by akihikodaki** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27014#pullrequestreview-133955206: done with commit 6acbfd9867ad1c7a6ba21c177ded1578313da144.

**Comment by Flarna** [comment]
@akihikodaki I'm sorry but with latest I meant that one directly in node folder (`types\node\index.d.ts`).
No need to revert the others.

**Comment by akihikodaki** [comment]
951131bfbab1ab8af4c7183628301229e3e39fff addresses https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27014#issuecomment-402139548. Thanks for reviewing again.

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
CI fail looks unrelated and caused by #27002

**Comment by Flarna** [comment]
@mhegazy Ci shows two issues:

- TypeError Exceptions in typescript (see #27016) which cause no fail
- fails caused by removing typedefinition for winston (see #27002)

**Comment by mhegazy** [comment]
Winston issue should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27020

**Comment by mhegazy** [comment]
#27016 is caused by https://github.com/Microsoft/TypeScript/pull/25333. please see my comment in https://github.com/Microsoft/TypeScript/pull/25333#issuecomment-402242763

**Comment by Flarna** [comment]
@mhegazy the two errors mentioned above are fixed :thumbsup:

There is one left which is strange, most likely introduced by a lint rule change as chai was not changed since a while:
```
Error in chai
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/chai/chai-tests.ts:1915:40
ERROR: 1915:40  use-default-type-parameter  This is the default value for this type parameter, so it can be omitted.
ERROR: 1922:40  use-default-type-parameter  This is the default value for this type parameter, so it can be omitted.
ERROR: 1931:45  use-default-type-parameter  This is the default value for this type parameter, so it can be omitted.
```

The corresponding code is as follows: `assert.hasAnyKeys(new Map<any, any>([[{foo: 1}, 'bar'], ['key', 'value']]), [{foo: 1}, 'key']);`

I tried to `Map<>` and `Map<any>` and `Map` but none of these variants passes the tests.

**Comment by mhegazy** [comment]
looking into it.

**Comment by Flarna** [comment]
@mhegazy I think it's important to do a fresh npm install. After playing around a little I found a way to fix this, see #27033. Change doesn't look that nice...

**Comment by Flarna** [comment]
new CI fail should be fixed via #27081

**Comment by mhegazy** [comment]
thanks @Flarna for the help getting this one in.

**Pull request merged**
