### PR TITLE
Pikaday: added showDaysInNextAndPreviousMonths property.

### PR DESCRIPTION
**Pull request by FlavienR**
Improvement to existing type definition : a property was missing in Pikaday definition file.

### CODE REVIEW

**Comment by vvakame** [comment]
@MidnightDesign could you review this PR?

**Comment by MidnightDesign** [comment]
Test is missing.

**Comment by FlavienR** [comment]
@MidnightDesign could you review this PR please?

**Comment by MidnightDesign** [comment]
LGTM

**Pull request merged**
