### PR TITLE
[restify] Correct and tighten type declarations.

### PR DESCRIPTION
**Pull request by djcsdy**
The attached pull request makes multiple improvements to the type declarations for restify:

 * Remove spurious exports: restify does not export the constructors for `Server` or `Router`, so modify the type declarations to export these as interfaces only, not classes. (see [lib/index.js](https://github.com/restify/node-restify/blob/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib/index.js)).
 * Correct type of `bunyan` export: The previous declaration bore no resemblance to the actual exported object. I have corrected this declaration to be correct as of restify 5.0.1 and 6.0.1. (Probably earlier versions too but those are the ones I checked.) (see [lib/index.js](https://github.com/restify/node-restify/blob/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib/index.js) and [bunyan_helper.js](https://github.com/restify/node-restify/blob/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib/bunyan_helper.js)).
 * Specify stricter types for members of `ServerOptions`. (see [lib/server.js](https://github.com/restify/node-restify/blob/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib/server.js)).
 * Correct type signature for formatters (see files in [lib/formatters](https://github.com/restify/node-restify/tree/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib/formatters)).
 * I have not bumped the version number because I’ve not made any effort to update the types for restify 6.0. I verified the changes I have made against both restify 5.0.1 and 6.0.1. So these types are still closer to restify 5.0.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/restify/node-restify/tree/35b078d922f9ae4afafcfce0fe72cc43529bba7b/lib
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by djcsdy** [comment]
note: I tested this against my own code and it works for me, but the project I tested it against is still fairly trivial, so not the best test.

**Comment by stevehipwell** [comment]
@djcsdy - Is there a reason you removed the router as a class?

**Comment by djcsdy** [comment]
Yes. As I said in the pull request, I removed `Router` as a class because the constructor isn’t exported.

Under the previous typings this would have passed typecheck but thrown ReferenceError at runtime:

```ts
import {Router} from "restify";
new Router();
```

After my changes the type checker will catch this.

The same applies to `Server`.

**Comment by stevehipwell** [comment]
@djcsdy - I obviously missed the full details when I originally read your pull request.

**Comment by stevehipwell** [comment]
👍

**Pull request merged**
