### PR TITLE
[react-select] switch DOM Node for ReactNode as per other files

### PR DESCRIPTION
**Pull request by jonfreedman**
The signature for `builtins.formatGroupLabel` is correct but is currently incompatible `formatOptionLabel` as `Select.d.ts` does not create an alias for ReactNode.
e.g. returning a ReactNode so you write something like
```typescript
formatter = (option: Foo, meta: FormatOptionLabelMeta<Foo>) => <div>{option.bar}</div>
```

### CODE REVIEW

**Comment by jonfreedman** [comment]
@claasahl looks like @typescript-bot only @-mentions the first 12 authors, you may want to take a look at this

**Comment by claasahl** [comment]
Thanks for the pointer, @jonfreedman

I'll have a look and get back to you.

**Comment by claasahl** [comment]
Looks good to me.

Is it worthwhile updating these imports/refereces?

- [.\lib\builtins.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/builtins.d.ts)
  - Line 4: `export function formatGroupLabel(group: GroupType<any>): Node;`
- [.\lib\components\Placeholder.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/Placeholder.d.ts)
  - Line 8: `children: Node,`
- [.\lib\components\containers.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/containers.d.ts)
  - Line 19: `children: Node,`
  - Line 36: `children: Node,`
  - Line 53: `children: Node,`
- [.\lib\components\Control.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/Control.d.ts)
  - Line 17: `children: Node,`
- [.\lib\components\Group.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/Group.d.ts)
  - Line 8: `children: Node;`
  - Line 12: `label: Node;`
- [.\lib\components\Menu.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/Menu.d.ts)
  - Line 92: `children: Node;`
  - Line 111: `children: Node,`
  - Line 132: `children: Node, // ideally Menu<MenuProps>`
- [.\lib\components\MultiValue.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/MultiValue.d.ts)
  - Line 7: `children: Node,`
  - Line 26: `children: Node;`
  - Line 36: `children: Node,`
  - Line 47: `children: Node,`
- [.\lib\components\Option.d.ts](https://github.com/jonfreedman/DefinitelyTyped/blob/master/types/react-select/lib/components/Option.d.ts)
  - Line 25: `children: Node,`

**Comment by jonfreedman** [comment]
Those are the correct type, I think you decided to alias ReactNode to Node to make the type names line up with the original Flow types.  Happy to remove that aliasing - I think that would be clearer...

**Review by claasahl — APPROVED** [review]
Thanks for double-checking and updating, @jonfreedman

**Comment by jonfreedman** [comment]
@RyanCavanaugh it seems the typescript-bot doesn't recognise @claasahl as an owner now that the typedef has been split into a v1 and v2 definition.

**Pull request merged**
