### PR TITLE
Added overload for row event to allow for useColumnNames

### PR DESCRIPTION
**Pull request by bvandevliet**
In the [tedious documentation](https://tediousjs.github.io/tedious/api-request.html#event_row) about the `row` event it says the following:

> An array or object (depends on `config.options.useColumnNames`), where the columns can be accessed by index/name.

In case `useColumnNames` is set to `true`, the `row` event handler is passed an object type `Record<string, ColumnValue>`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## tedious ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tedious@latest/))
was missing the following properties:
1. BulkLoad
1. library
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a95edb6d63780f85cd8011979e2e648b24c8c969
</p>

**Review by amcasey — COMMENTED** [review]
Can you please add a test showing a scenario this lights up?

Basically, I'm confused about what it means to have two different kinds of handlers for the same event (chiefly because I don't know anything about tedious).  So you'll always register either a column number handler or a column name handler, but not both?  And the appropriate one will be invoked, based on some mode variable?  Or are you saying that all handlers need to be able to handle being called with column names?

**Comment by bvandevliet** [comment]
Hi, excuse me for not explaining. In the [tedious documentation](https://tediousjs.github.io/tedious/api-request.html#event_row) about the `row` event it says the following:

> An array or object (depends on `config.options.useColumnNames`), where the columns can be accessed by index/name.

In case `useColumnNames` is set to `true`, the `row` event handler is passed an object type `Record<string, ColumnValue>`.

**Comment by amcasey** [comment]
@bvandevliet Thanks!  This bit makes me think the callback needs to be able to handle an array even in name mode:

> If there are multiple columns with the same name, then this will be an array of the values.

Specifically, I'm wondering if it should be `Record<string, ColumnValue> | ColumnValue[]`.  Again though, I'm not a domain expert.

**Comment by bvandevliet** [comment]
Hi @amcasey, fair point. And in that case, I would expect `Record<string, ColumnValue | ColumnValue[]>` to be the returned type. However, I tested this and it seems that if there are multiple columns with the same name, the first one that occurs in the query wins. It is not replaced by subsequent values, nor is it converted to an array containing all the values. To me, this actually feels like a bug in the `tedious` package. So what do you think, maybe we should report this to the dev team of `tedious` first?

**Comment by amcasey** [comment]
@bvandevliet Thanks for investigating!   If the behavior of `tedious` looks wrong, then definitely follow up on their repo.  Having said that, I don't think you need to hold off on updating the types - callers shouldn't be prevented from passing callbacks that work today.  Maybe just suggest that whoever makes the change to `tedious` follow up with a change here?

**Review by amcasey — APPROVED** [review]
The types aren't perfect, but they unblock a legitimate scenario.

**Comment by bvandevliet** [comment]
@amcasey I think you are right. I will trigger the merge and make this known to tedious soon.

**Comment by bvandevliet** [comment]
Ready to merge

**Pull request merged**
