### PR TITLE
[ramda] Update prop: allow to handle more variants of usage

### PR DESCRIPTION
**Pull request by anion155**
Update `prop` function:

+ allow usages with proper typings with maybe undefined values
+ allow usages with props not included in type of the value
+ allow usage of arrays as values with number keys, with proper typings for tuple types
+ add more usable cases for manual passed generic types
+ updated currying

All usage cases are in the updated [test file](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62789/files#diff-b0160efc3802fbf27927d8436d8c405c1e4820e5bd2945cf0b6dc8100ab6d878)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  + [prop function](https://ramdajs.com/docs/#prop)
  + [currying placeholder](https://ramdajs.com/docs/#__)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b9b77e527bc0f23bf19594b74b12702be044a9cc
</p>

**Review by Nicholaiii — APPROVED** [review]
This looks good, but please be mindful of removing tests - so that we can ensure backwards compatibility.

**Comment by anion155** [comment]
Maybe add previous tests back?

**Comment by anion155** [comment]
Reverted old tests

**Review by Nicholaiii — APPROVED** [review]
Cool! Thank you, let's get this boat on the water

**Comment by anion155** [comment]
Ready to merge

**Comment by perrin4869** [comment]
this broke in my app, now `prop("foo")` is being inferred as `<T>(obj: T) => undefined` whereas before it would be `<T>(obj: T) => T["foo"]`. I will look into what broke

**Comment by anion155** [comment]
@perrin4869 Can you write specific code? 'Cause before this `prop('foo')` would be `<T>(obj: Record<"x", T>) => T`, not `<T>(obj: T) => T["foo"]`

**Comment by perrin4869** [comment]
Specifically what broke is, given:

```
import { prop } from "ramda";

Promise.resolve({ foo: "bar" }).then(prop("foo"));
```

Before, this would resolve to `Promise<string>`, now it is `Promise<undefined>`
Been wracking my brain why this is the case. If I remove one of the two definitions for `prop("foo")`, regardless of which, this will be correctly inferred, but if both are present, the type is incorrectly inferred...
Do you have any clues?
Thanks!

**Comment by anion155** [comment]
@perrin4869 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63184

**Pull request merged**
