### PR TITLE
Update Google Apps Script Types (2017-05-12 -> 2018-07-11)

### PR DESCRIPTION
**Pull request by grant**
This PR updates Google Apps Script types. (2017-05-12 -> 2018-07-11)
This is a generated type definition.
CC: @erickoledadevrel

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
```
npm run lint google-apps-script
definitely-typed@0.0.2 lint /Users/timmerman/Documents/github/DefinitelyTyped
dtslint types "google-apps-script"
# No result.
```

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/apps-script/reference/
- [x] Increase the version number in the header if appropriate.
  - The version should be bumped by the publisher.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by grant** [comment]
The Travis error does not seem to be related to this PR:
```
Error: amqp-connection-manager depends on amqplib but has a lower required TypeScript version.
    at checkTypeScriptVersions (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/check-parse-results.ts:75:11)
```

**Comment by grant** [comment]
This failure is not related to this PR. Master is failing.

**Comment by BehindTheMath** [comment]
@grant It looks like you removed a bunch of JSDoc comments, as well as some interfaces. Why were those removed?

**Comment by grant** [comment]
@BehindTheMath These types are generated from https://github.com/motemen/dts-google-apps-script. Unforunately the owner there doesn't maintain that repo.

I see some google-apps-script.drive.d.ts comments were removed and some interfaces are plain Object types but some types are added. Generating the types again would result in this update.

Which other comments and interfaces were removed?

**Comment by BehindTheMath** [comment]
>@BehindTheMath These types are generated from https://github.com/motemen/dts-google-apps-script. Unforunately the owner there doesn't maintain that repo.

Is it broken? If yes, is there any reason not to fork it and fix it?

>I see some google-apps-script.drive.d.ts comments were removed and some interfaces are plain Object types but some types are added. Generating the types again would result in this update.

>Which other comments and interfaces were removed?

`google-apps-script.gmail.d.ts` also has some JSDoc comments that were removed.

Those are the interfaces I was referring to.

**Comment by tombell** [comment]
Looks like `ActionEvent` from the former `Card` module was removed.

**Comment by BehindTheMath** [comment]
* Some methods and interfaces were removed from:
  * `google-apps-script.forms.d.ts`
  * `google-apps-script.gmail.d.ts`
  * `google-apps-script.script.d.ts`
  * `google-apps-script.url-fetch.d.ts`.
* As you mentioned earlier, some JSDoc comments were removed from `google-apps-script.drive.d.ts`, as well as from `google-apps-script.spreadsheet.d.ts`.

**Comment by grant** [comment]
Please comment on PR #27459 for fixes to these issues. You can also submit your own PRs to suggest fixes to the types. Do note that these type comments aren't perfect and some methods may still be missing comments.

**Pull request merged**
