### PR TITLE
react-virtualized: Add the role prop for Grid

### PR DESCRIPTION
**Pull request by niik**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md, https://github.com/bvaughn/react-virtualized/blob/77ddcbee490ee8c67ae2913f325d854c20d288c0/source/Grid/Grid.js#L705
- [x] ~~Increase the version number in the header if appropriate.~~
- [x] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.~~

---

The role prop was omitted from the list of valid props even though the propType declarations include it.

### CODE REVIEW

**Comment by niik** [comment]
> can't parse definition header...

Hmm, I guess there isn't one in this particular file. @kaoDev @mhegazy you're the only other contributors to this file that I could find. Want me to add a header or are you okay with 👍 this anyway?

**Comment by aozgaa** [comment]
If you could add a header, that would be great!

**Comment by kaoDev** [comment]
yesterday I opened the pull request with an update to version 9.7 (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16515) the role property is already included.
The definition header is included in the root index.d.ts, how is this handled normaly for suche a file/folder structure?

**Comment by aozgaa** [comment]
Yes, looks like a bug with dt-bot... sorry for the inconvenience.

Pinging @kaoDev, can you take a look?

**Comment by kaoDev** [comment]
the change is valid. 
@niik if you want you can add yourself as a contributor in the index.d.ts file

**Comment by aozgaa** [comment]
Merged #16515

**Pull request closed without merging**
