### PR TITLE
Split activex-interop from windows-script-host; replace activex-iwshruntimelibrary

### PR DESCRIPTION
**Pull request by zspitz**
https://github.com/Microsoft/TypeScript/issues/21440
https://github.com/Microsoft/TypeScript/issues/21442

Note that these two packages supersede the definitions in [`lib.scripthost.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/src/lib/scripthost.d.ts), and do not require setting `scripthost` for the `libs` TypeScript compiler option.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [X] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@andy-ms are we suppose to have these definitions here? this is not npm package.

**Comment by andy-ms** [comment]
As long as it doesn't conflict with the name of an npm package it should be fine.

**Comment by andy-ms** [comment]
@zspitz `activex-faxcomexlib` and `activex-shell` depend on `activex-iwshruntimelibrary`, could you update those?

**Comment by zspitz** [comment]
@andy-ms I've fixed this in #25745

**Comment by andy-ms** [comment]
Yes, that's a bug that we should fix -- works for edited files, but not so well for deleted ones. Thanks for the fix.

**Pull request merged**
