### PR TITLE
Remove prose from READMEs which hardcode the minimum supported TS

### PR DESCRIPTION
**Pull request by jakebailey**
While updating the support diagram, I noticed that we hardcoded the minimum supported TS version in each readme. They're all out of date, and often differently out of date. This changes the wording such that there's no need to make sure they're updated ever again. The "2 years of updates" plus diagram are always going to be accurate.

Note that this makes the diagram always visible as the collapsible block is now "older TypeScript versions". Perhaps that's a bad idea?

In the non-english files, I used the requisite text if it was available, otherwise I left it in English to be translated later (as I don't speak the other languages).

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot are you awake. you should be sleeping by now

**Comment by jakebailey** [comment]
@typescript-bot hello friend, are you there

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## i18next-ko ([<kbd>unpkg</kbd>](https://unpkg.com/browse/i18next-ko@latest/))
was missing the following properties:
1. convertAPIOptions
1. convertJSONOptions
1. convertTOptions
1. appendBackwardsAPI
1. get

<details>
<summary>as well as these 9 other properties...</summary>
<p>transformOptions, makeString, copy, setPath, pushPath, getPath, deepExtend, regexEscape, escape</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 707e62011accf9c6cfffcb3013590b781250e0eb
</p>

**Comment by jakebailey** [comment]
Ready to merge

**Pull request merged**
