### PR TITLE
Adding types for react-hint lib

### PR DESCRIPTION
**Pull request by lucasghizoni**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
Is that really functional component?
https://github.com/slmgc/react-hint/blob/master/src/index.js#L2
It looks like old-plain class component

**Comment by lucasghizoni** [comment]
> Is that really functional component?
> https://github.com/slmgc/react-hint/blob/master/src/index.js#L2
> It looks like old-plain class component

Good point, @peterblazejewicz. It is indeed class component, but I find the type definitions for class components much more complex than for Function Components, thats why I decided to leave it with `React.FunctionComponent` instead. I tested in my project and it works, so I see no problem on leave as it is. What do you think?

**Comment by peterblazejewicz** [comment]
I can see the point in doing this, but can you point similar solution in other existing DT types?
Let's wait for 2nd 👀 to review the problem, ok?

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Disliking class component types isn’t really a valid reason for claiming that a class component is something else entirely. Fundamentally, `Component<T>` and `FunctionComponent<T>` do not have assignability in either direction, so substituting one for the other is always wrong. It may be wrong in ways that do not _commonly_ manifest, but these types are for everyone, so “it works for me” isn’t really relevant here—it needs to be correct.

**Pull request closed without merging**
