### PR TITLE
Adding definitions for Lovefield library

### PR DESCRIPTION
**Pull request by freshp86**
Hi. I would like to add Lovefield's (https://github.com/google/lovefield) definitions file to DefinitelyTyped repository.
Thank you.

### CODE REVIEW

**Comment by vvakame** [comment]
*lovefield/lovefield.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/lovefield
  * http://bower.io/search/?q=lovefield
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (lovefield/lovefield-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@freshp86 thank you for your contributions.
please rename lovefield/lovefield-test.ts to lovefield/lovefield-tests.ts

**Comment by freshp86** [comment]
Done.

**Comment by vvakame** [comment]
@freshp86 thanks mate!

**Pull request merged**
