### PR TITLE
Allow to use `import React from 'react';`

### PR DESCRIPTION
**Pull request by alexeyraspopov**
Improvement to existing type definition.

This is a simple fix for default React's export.
- [ ] it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
I hope I didn't forget anything here.

**Comment by alexeyraspopov** [comment]
And I'm not quite sure how to fix tests :(

**Comment by vsiao** [comment]
Why do you want to do this? React doesn't export a default, so I think this is wrong.

**Comment by alexeyraspopov** [comment]
Yes

image

It does

image

**Comment by pspeter3** [comment]
That is not a default export.

**Comment by alexeyraspopov** [comment]
Doesn't matter how you call it, [people have to write weird things](https://github.com/search?l=typescript&q=%22import+%2A+as+React%22&type=Code&utf8=%E2%9C%93). For those who is coming from JavaScript this is confusing and not obvious.

**Comment by vvakame** [comment]
`export default xxx;` can not convert to `module.exports = xxx`. `export = xxx` is right way.

**Pull request closed without merging**
