### PR TITLE
Add missing extendOwn and assign methods to _ and chain objects

### PR DESCRIPTION
**Pull request by cacilhas**

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by cacilhas** [comment]
No problem.

[]’s
ℜodrigo Arĥimedeς ℳontegasppα ℭacilhας

2016-11-07 14:42 GMT-02:00 Masahiro Wakame <notifications@github.com>:

**Comment by minestarks** [comment]
I'm closing out this PR as there seems to be agreement that the changes should be targeting types-2.0 instead.

**Pull request closed without merging**
