### PR TITLE
[webpack] Add resolve.symlinks and resolve.plugins

### PR DESCRIPTION
**Pull request by kryops**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). *(errored `Object.entries is not a function`)*

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://webpack.js.org/configuration/resolve/#resolve-symlinks
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by kryops** [comment]
@tkqubo
@mattlewis92
@bumbleblym
@bcherny
@tommytroylin

**Review by bumbleblym — APPROVED** [review]

**Comment by sod** [comment]
While you are at it, could you also add `resolve.plugins` https://webpack.js.org/configuration/resolve/#resolve-plugins ? :D 

Something like
```typescript
        /**
         * A list of additional resolve plugins which should be applied
         */
        plugins?: Plugin[];
```

**Comment by kryops** [comment]
Good catch!
Complete typings for `resolve.plugins` seem to need the `Resolver` from `enhanced-resolve`, which is not exported at the moment. Should we leave it at `any` or modify `enhanced-resolve` to export the `Resolver`?

**Comment by bumbleblym** [comment]
When I looked into this, I couldn't confirm if the `enhanced-resolve` `Resolver` specified the minimal interface that `resolve.plugins` accepted.

We need something like the currently exported `Plugin` abstract class or `ICompiler` interface, which `enhanced-resolve` can extend/implement.

This is the same situation for file system properties e.g. `this.fs` in [loader context](https://webpack.js.org/api/loaders/#this-fs), currently typed as `any`. I remember reading that it should be compatible with the [Node.js fs module](https://nodejs.org/api/fs.html), but [memory-fs](https://github.com/webpack/memory-fs) only implemented a subset of the methods.

These types should be defined in `webpack`, where they can be imported by other modules like `enhanced-resolve` and `memory-fs`, so that alternative implementations are supported. We'll need to clarify the minimal interfaces with the webpack team.

**Comment by kryops** [comment]
yeah that makes sense. Unfortunately there does not seem to be much documentation around for `resolve.plugins` at the moment, it took me a while to even find the reference to `enhanced-resolve`.

So we should land this with `(resolver: any)` for now? That will at least allow us to use `resolve.fallback` and `resolve.plugins` correctly, just not typeguard against what the plugins actually do with the resolver.

**Comment by bumbleblym** [comment]
SGTM 👍

**Pull request merged**
