### PR TITLE
@types/bull: updates for API changes in v3

### PR DESCRIPTION
**Pull request by marshall007**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [CHANGELOG.md](https://github.com/OptimalBits/bull/blob/v3.0.0-rc.2/CHANGELOG.md)
  - [REFERENCE.md](https://github.com/OptimalBits/bull/blob/v3.0.0-rc.2/REFERENCE.md)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### Notable Changes

- Added constructor interface to `Queue` (i.e. `new Queue(name)`)
- Various updates to support API changes in v3
- Strict typings for `Queue` event callbacks

### CODE REVIEW

**Comment by marshall007** [comment]
**Note:** I tried adding a `tslint.json` config for this project, but I am unable to run the linter:

```
$ npm run lint bull

> definitely-typed@0.0.1 lint /Users/marshall/Projects/DefinitelyTyped
> dtslint types "bull"

Warning: ts.forEachLeadingCommentRange is not a function
ts.forEachLeadingCommentRange is not a function
```

**Comment by elyscape** [comment]
@marshall007 The tests are failing because `types/bull/v2/tsconfig.json` [needs to have the paths for `baseUrl` and `typeRoots` updated to `../../`][paths]. Fix that and you're good.

[paths]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version

**Comment by marshall007** [comment]
@elyscape thanks! Looks like they're passing now.

**Comment by marshall007** [comment]
@bgrieder or @JProgrammer could one of you take a look so we can get this merged? Most of the changes are related to linting, you can look at the first commit to get a better idea of what actually changed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17002/commits/dcfbea5aeb8838c9a1f6a670ab6adea8e1f04a99#diff-f92bb2dbabb4a196b0c99adc6bc4d2d1

**Comment by bgrieder** [comment]
My apologies but I have not be using those types for quite some time.
My name should be removed from the reviewers list

**Comment by marshall007** [comment]
@yuit would you consider going ahead and merging this? I'm already using these definitions in a project and I feel confident that they are correct. I'm happy to maintain going forward if any issues arise.

**Review by cmcrothers — APPROVED** [review]
👍

**Pull request merged**
