### PR TITLE
Updates assign/extend declarations

### PR DESCRIPTION
**Pull request by aholmes**
This change updates the assign and extend declaration for lodash objects and lodash static. It:
- Removes the P type argument, which is not referenced or documented.
- Follows the .d.ts documentation by not defining optional method arguments, and expands each existing definition to include a method with a callback argument, and another with a callback and thisArg argument.
- Defines a variadic method without callback and thisArg arguments.
- Updates documentation for the variadic method declaration.

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to author(@bczengel). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

@aholmes please fix travis ci failed.

**Comment by aholmes** [comment]
Yes, I started looking into it, but getting the tests running correctly in windows is a challenge. I will have an updated commit as soon as I get that working.

**Comment by mhegazy** [comment]
Looks like there are still failing tests. can you take a look.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Comment by aholmes** [comment]
Thanks for the info. I'll make an effort to get this back into mainline; unfortunately haven't had time to loop back around to this.

**Pull request closed without merging**
