### PR TITLE
[enzyme] Fix signature of the "filter" method.

### PR DESCRIPTION
**Pull request by UselessPickles**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Bug introduced by this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22975. Explained below.
- [ ] Increase the version number in the header if appropriate. (not sure about this)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (not sure about this)

This is a fix to a bug I introduced with a recent pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22975

I incorrectly updated the signature of "filter" to return "ReactWrapper<HTMLAttributes, any>" when the param is of type "string". This causes undesirable results, such as the following example:

```ts
// props should be the props of MyComponent, but is instead incorrectly HTMLAttributes
const props = wrapper.find(MyComponent).filter(".specialCssClass").props();
```

Compared to other methods like "find", filter is more special in that it is guaranteed to return only a subset of what currently exists in the collection of components/elements, without ever adding new items to the collection. So when the param does not clearly indicate an exact type of the result, the type of the result should remain "this".

### CODE REVIEW

**Comment by UselessPickles** [comment]
I don't understand why this PR includes all changes from my prior PR too: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22975

Wasn't my prior PR already merged? I'm only intending to add the last commit in this PR.

**Comment by MartynasZilinskas** [comment]
@UselessPickles I think it was squashed commit. After every pr I delete the branch and start from the newest in master to prevent something like this.

**Review by MartynasZilinskas — CHANGES_REQUESTED** [review]
By looking at enzyme documentation, it doesn't return the same instance. It returns a new wrapper.
[Docs link](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/filter.md#returns)

**Comment by UselessPickles** [comment]
Maybe my problem is that I was lazy and worked directly on the master branch of my forked repo instead of creating a branch? Should I cancel this PR and try again from a branch?

**Comment by UselessPickles** [comment]
At this point, I don't understand what you think is wrong with the changes I have here. What type do you think should be returned by "filter" when the param is a string CSS selector?

**Comment by UselessPickles** [comment]
The types already are consistent. 

The return type of `shallow()` cannot be `this` because `shallow()` is not a member function of a class. 

`filter()` is a member function of class `ShallowWrapper<P, S>`, so a return type of `this` on `filter` is effectively `ShallowWrapper<P, S>`. 

Using type `this` instead of explicitly `ShallowWrapper<P, S>` has 2 main benefits:
* Clarity: it takes zero mental energy to arrive to the conclusion that the method's return type is the same as the class that the method belongs to.
* Polymorphic: Not really relevant in this case because there are no subclasses of `ShallowWrapper`, but the return type `this` is polymorphic and will be the correct subclass type when the inherited method is called on an instance of a subclass.

**Comment by DovydasNavickas** [comment]
@UselessPickles, you're not 100% right.
If you look at this image:
image 4

It seems that both cases are identical.

But this one shows they're not:
image 5

Because if you don't actually return this, it is not the right notation.
In enzyme's case, `filter()` returns a **NEW** wrapper, and **NOT** `this`, as you can see here:
https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ShallowWrapper.js#L625-L628
```js
filter(selector) {
    const predicate = buildPredicate(selector);
    return filterWhereUnwrapped(this, predicate);
}
```

And inside `filterWhereUnwrapped` here:
https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ShallowWrapper.js#L62-L64
```js
function filterWhereUnwrapped(wrapper, predicate) {
  return wrapper.wrap(compact(wrapper.getNodesInternal().filter(predicate)));
}
```

I hope now you see that `this` as a return type is incorrect as the `filter` function returns a new instance of `ShallowWrapper`.

**Comment by DovydasNavickas** [comment]
And inside `wrapper.wrap`, you can see a new instance of `ShallowWrapper` being created when node is not an instance of `ShallowWrapper`:
https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ShallowWrapper.js#L1126-L1131
```js
wrap(node, root = this[ROOT], ...args) {
    if (node instanceof ShallowWrapper) {
      return node;
    }
    return new ShallowWrapper(node, root, ...args);
}
```

Which means `this` as a return type would not be *always* correct and `ShallowWrapper` would.

**Comment by UselessPickles** [comment]
@DovydasNavickas Thanks for the clarification. I understand now. 

Looks like there are many other incorrect signatures in this project defined as returning `this`, but even the documentation in this project specifically says it returns a new wrapper. Maybe a separate issue should be created to more broadly address this issue?

**Comment by UselessPickles** [comment]
I fixed the `filter()` signatures to not use `this` as the return type.

There are several methods defined in the `CommonWrapper` interface that specify a return type of `this`, but clearly return a new instance. I'll work on a separate pull request to move these signatures into both `ShallowWrapper` and `ReactWrapper` with correct return types.

**Review by MartynasZilinskas — APPROVED** [review]

**Pull request merged**
