### PR TITLE
[webpack-dev-server] v4.0 updates

### PR DESCRIPTION
**Pull request by kseino**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md>
- moved current files to `./v3` dir

### CODE REVIEW

**Comment by kseino** [comment]
webpack-dev-server v4.0 has some breaking changes.
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

Tests that depend on previous versions of this package failed...

**Comment by kseino** [comment]
webpack-dev-server v4.0 has some breaking changes.
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

Tests that depend on previous versions of this package failed...

**Comment by kseino** [comment]
> webpack-dev-server v4.0 has some breaking changes.
> https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
> 
> Tests that depend on previous versions of this package failed...

Fixed.

**Comment by peterblazejewicz** [comment]
@kseino mind reviewing this PR first? thanks for understanding,
#55300

**Comment by kseino** [comment]
duplicated
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55300

**Pull request closed without merging**
