### PR TITLE
@types/snoowrap - Make RedditContent thenable

### PR DESCRIPTION
**Pull request by TheAppleFreak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getMe__anchor (under 1.14, tslint would say this isn't thenable)
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by vitosamson** [comment]
Can you add some tests for this change? I recall having some issues making the typings work both when the chained promises are enabled and disabled.

**Comment by TheAppleFreak** [comment]
Yeah, I'll see what I can do about the tests.

**Comment by TheAppleFreak** [comment]
Alright, poked at it. Not gonna lie, I'm not super familiar with the test suite that DefinitelyTyped uses, but I added a quick test to see whether .then() works and it passes, so I'll take that as a success.

**Review by vitosamson — APPROVED** [review]

**Comment by dessalines** [comment]
I'm really confused, a lot of these are broken, the `.then()` s don't work on them. This version says `1.16` yet snoowrap is only at `1.15.2`

**Comment by TheAppleFreak** [comment]
...crap. I think the versioning was a mistake on my end; I might have incremented the minor version instead of the patch version. 

In regards to `.then()` it's been working perfectly as expected on my end; `RedditContent` derivatives now behave like actual promises instead of... well, not promises.

**Comment by dessalines** [comment]
I'm getting a lot of 
```
[ts] Property 'then' does not exist on type 'Listing<Submission>'.
```

**Comment by TheAppleFreak** [comment]
That's weird. Sounds like you're on an earlier version of the typings. Try running `npm install -D @types/snoowrap` or `yarn add -D @types/snoowrap` again to update to the latest version of the types.

**Comment by TheAppleFreak** [comment]
Huh, that doesn't work... that's funny. Looks like the `.map()` function is set to return a literal string array instead of a Promise that resolves to a string array. I'll take a look at the definitions and see if I can't fix that.

**Comment by dessalines** [comment]
Nevermind I figured it out, the examples are wrong in a lot of cases, its often `.forEach`.

**Pull request merged**
