### PR TITLE
fix(mongoose): remove type checking for document creation

### LINKED ISSUE #45305: @types/mongoose throws errors after upgrading to 5.7.22
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

With the latest update to `@types/mongoose` I get a lot of errors in my IDE (vscode) about missing properties when creating new documents.

```(property) RocketDocumentPage.dimensions: [number, number]
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ order: number; label: string; width: number; height: number; publication: string; kiosk: Ref<KioskModel>; }' is not assignable to parameter of type 'Pick<{ _id: any; order: number; label: string; width: number; height: number; publication: Ref<PublicationModel>; kiosk: Ref<KioskModel>; userId: string; available: boolean; migrationRef: string; } & { ...; }, "order" | ... 7 more ... | "migrationRef"> & { ...; }'.
      Type '{ order: number; label: string; width: number; height: number; publication: string; kiosk: Ref<KioskModel>; }' is missing the following properties from type 'Pick<{ _id: any; order: number; label: string; width: number; height: number; publication: Ref<PublicationModel>; kiosk: Ref<KioskModel>; userId: string; available: boolean; migrationRef: string; } & { ...; }, "order" | ... 7 more ... | "migrationRef">': userId, available, migrationRefts(2769)
```

This can be easily reproduced by creating a model and trying to call `.create({ ... })` on it.

This worked perfectly fine with 5.7.21.

Downgraded to 5.7.21 as a workaround for now until this is fixed.

### LINKED ISSUE #45608: @types/mongoose create schema forces non-required properties at crate time
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andreialecu 

In the example below, `addedInMiddleware` is required on the document but not on the create schema since it's added in a middleware.

The schema added in 88a54a939455efa0937b55ed507631415a574c44 causes `addedInMiddleware` to be required at compile time, but it shouldn't be.

@andreialecu I'd appreciate if you can fix this.

```typescript
import * as Mongoose from 'mongoose'

interface IDocument extends Mongoose.Document {
    addedInMiddleware: string
}

const schema = new Mongoose.Schema({
    addedInMiddleware: String,
})

schema.pre('validate', async function (this: IDocument) {
    if (!this.addedInMiddleware) this.addedInMiddleware = 'added';
});

const model = Mongoose.model<IDocument>('model', schema);

/*
TS2769: No overload matches this call.   
The last overload gave the following error.     
Argument of type '{}' is not assignable to parameter of type 'Pick<{ _id: any; addedInMiddleware: string; } & { _id: any; }, "addedInMiddleware"> & { _id?: any; }'.       
Property 'addedInMiddleware' is missing in type '{}' but required in type 'Pick<{ _id: any; addedInMiddleware: string; } & { _id: any; }, "addedInMiddleware">'.
 */
model.create({});
```

### LINKED ISSUE #45609: @types/mongoose create schema doesn't allow string source to objectid
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andreialecu 

@andreialecu This is another example of how your PR breaks totally valid code.

I'm going to post a PR that reverts it soon.

This is not the first attempt made at creating a schema for document creation.
See
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/26587aa3aa75e0021180a9a7f9b4cb45e036002b#diff-f77e4c92e873042528b4ef79285cdf3c
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/22761c884a9542171583f83ccd178acd0c1e3b11#diff-f77e4c92e873042528b4ef79285cdf3c

This attempt was also not adequately testd and had PLENTY of issues.

I reverted it in
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c860c1dc7ba152a7e09b518eee900125a1a3bc3d#diff-f77e4c92e873042528b4ef79285cdf3c

Please STOP adding schema to create without testing all the possibilities. This is not that simple and causes the rest of us to waste a lot of time.

```typescript
import * as Mongoose from 'mongoose'

interface IDocument extends Mongoose.Document {
    objectId: Mongoose.Types.ObjectId
}

const schema = new Mongoose.Schema({
    objectId: Mongoose.Types.ObjectId,
})

const model = Mongoose.model<IDocument>('model', schema);

/*
TS2769: No overload matches this call.   The last overload gave the following error.     Type 'string' has no properties in common with type '{ generationTime?: number; }'.  tmp.ts(4, 5): The expected type comes from property 'objectId' which is declared here on type 'Pick<{ _id?: any; objectId?: { generationTime?: number; }; } & { _id: any; }, "objectId"> & { _id?: any; }' index.d.ts(3259, 5): The last overload is declared here.
 */
model.create({
    objectId: 'valid-object-id-source',
});

// passes
model.create({
    objectId: new Mongoose.Types.ObjectId(),
});

```

### PR DESCRIPTION
**Pull request by tomyam1**
This reverts the (second) attempt made at adding schema for document creation because it
causes valid well-typed code to break.

The previous attempt was made at:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/26587aa3aa75e0021180a9a7f9b4cb45e036002b#diff-f77e4c92e873042528b4ef79285cdf3c

And reverted at:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c860c1dc7ba152a7e09b518eee900125a1a3bc3d#diff-f77e4c92e873042528b4ef79285cdf3c

This attempt suffers from the same faults as the previous attempt and causes valid,
well-typed, code to break which should never happen in a types library.

Some of them are listed here in the previous PR I made to remove this type checking
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37823

In the issues discussions: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45608
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45609

The author made suggestions on how to circumnavigate the situation by none of them are correct or sufficient.

fixes #45305
fixes #45609
fixes #45608

revert 88a54a939455efa0937b55ed507631415a574c44

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by andreialecu — CHANGES_REQUESTED** [review]
This has been adopted already and there's a PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45610 fixing the issue reported that led to this.

https://github.com/typegoose/typegoose/commit/09ddddb1925f8b3723eeb2aacd66594dbf52ec58

Let's not revert things because of one person's overreactions please. Thanks.

**Comment by tomyam1** [comment]
@andreialecu Since this reverts your own commit, you requesting changed with "..." with commit is just unethical.

**Comment by andreialecu** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45610#issuecomment-646987118

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongoose ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongoose@latest/))
was missing the following properties:
1. modelSchemas
1. options
1. cast
1. driver
1. deleteModel

<details>
<summary>as well as these 7 other properties...</summary>
<p>ObjectId, Decimal128, Mixed, Number, now, CastError, SchemaTypeOptions</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 98eb40e92a8937e981219d076da2103bee5d5143
</p>

**Review by andreialecu — CHANGES_REQUESTED** [review]
I would suggest you close this, as it is just malicious at this point. You submitted an issue for which I opened a PR within minutes (which wasn't even a big deal in the first place), then submitted your own PR to revert a massive amount of work both in tweaking the types here and in downstream packages. 

The 30 minutes between reporting and sending a PR based on mainly your own project's inconsistencies are not what Open Source contributions should be about.

Would be better if you put it in Draft mode until you have time to cool off.

**Comment by tomyam1** [comment]
Decided to close this PR since it might break the code for users that already adopted the typings in new document creation, e.g. if they use `CreateQuery` on their own.

I hope that @andreialecu will fix and keep fixing the issues that arise from the type checking that he added.

**Comment by tzellman** [comment]
Not sure if this is related, but after updating to `5.7.22` (which contains the strongly typed `create`), I am having build failures in a project related to calling `create` without specifying `_id`. I unfortunately have to downgrade to `5.7.21` in the meantime.

**Comment by andreialecu** [comment]
If your `_id` is not typed as `_id: ObjectId` in the schema type then that can happen because it isn't safe to assume that `_id: string` can be auto-generated. Only `ObjectId` can be autogenerated.

You can override that behavior manually via `.create<Omit<YourType, "_id">>(...)`

**Pull request closed without merging**
