### PR TITLE
[Node]: String.prototype has additional ES2019 methods

### PR DESCRIPTION
**Pull request by Luxcium**
The properties trimStart and trimEnd are preferred. The trimLeft and trimRight properies are provided principally for compatibility with old code. It is recommended that the trimStart or trimEnd  properties be used in new ECMAScript code.

https://github.com/nodejs/node/commit/12a1b9b8049462e47181a298120243dc83e81c55#diff-5fb85405f1ec035ec82ebead4371e7e8

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://www.ecma-international.org/ecma-262/10.0/index.html#sec-string.prototype.trimend
https://www.ecma-international.org/ecma-262/10.0/index.html#sec-string.prototype.trimstart
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

B.2.3Additional Properties of the String.prototype Object : 
B.2.3.15String.prototype.trimLeft ( )
B.2.3.16String.prototype.trimRight ( )

trimStart and trimEnd on String.prototype as better-named alternatives to the widely implemented but non-standard String.prototype.trimLeft and trimRight built-ins. 

The initial value of the trimLeft property is the same function object as the initial value of the  String.prototype.trimStart property.
The initial value of the trimRight property is the same function object as the initial value of the  String.prototype.trimEnd property.

21.1.3.28String.prototype.trimEnd ( )
This function interprets a String value as a sequence of UTF-16 encoded code points, as described in 6.1.4.

The following steps are taken:

Let S be this value.
Return ? TrimString(S, "end").
NOTE
The trimEnd function is intentionally generic; it does not require that its this value be a String object. Therefore, it can be transferred to other kinds of objects for use as a method.

21.1.3.29String.prototype.trimStart ( )
This function interprets a String value as a sequence of UTF-16 encoded code points, as described in 6.1.4.

The following steps are taken:

Let S be this value.
Return ? TrimString(S, "start").
NOTE
The trimStart function is intentionally generic; it does not require that its this value be a String object. Therefore, it can be transferred to other kinds of objects for use as a method.

### CODE REVIEW

**Review by islishude — CHANGES_REQUESTED** [review]
These have been already added to the stdlib

https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2019.string.d.ts

**Review by SimonSchick — CHANGES_REQUESTED** [review]
What @islishude said, use the existing lib.

**Review by Luxcium — COMMENTED** [review]
The test was missing the test string initialization `const s = 'foo';`

**Comment by Luxcium** [comment]
@SimonSchick what existing lib should I be using?
 I have error: **`Property 'trimStart' does not exist on type 'string'.ts(2339)`**

with in /tsconfig.json:
```json
{
    "compilerOptions": {
    "lib": [
            "dom",
            "esnext",
            "dom.iterable",
            "es2017.string",
            "es2019.string",
            "es2020.string"
        ],
    }
}
```

and with in package.json:
```json
{
    "devDependencies": {
        "@types/node": "^12.7.2",
        "typescript": "^3.5.3",
    }
}
```

**Comment by Luxcium** [comment]
to many commits and corrections will close PR

**Comment by Luxcium** [comment]
to many commits and corrections will close PR

**Pull request closed without merging**
