### PR TITLE
[tuya-panel-kit] add docs comment and add TransitionPresets、useTheme

### PR DESCRIPTION
**Pull request by youngjunning**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## tuya-panel-kit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tuya-panel-kit@latest/))
was missing the following properties:
1. OfflineView
1. FullView
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f2be4c0405cdb74809c8922dfaa57d664f14384d
</p>

**Review by ShinyLeee — APPROVED** [review]

**Review by ShinyLeee — APPROVED** [review]
@ @

**Review by ShinyLeee — APPROVED** [review]

**Review by ShinyLeee — APPROVED** [review]

**Comment by youngjuning** [comment]
@nex3 please merge the pr, thanks a lot

**Review by ShinyLeee — APPROVED** [review]

**Comment by nex3** [comment]
I'm not sure why you're @-ing me, I'm not a maintainer for this package or this repo.

**Comment by youngjuning** [comment]
@nex3 :) sorry, just because your nickname appear after `@`

**Comment by elibarzilay** [comment]
This has a few things that make it hard to see what's going on:

1. Can you please rebase & squash the commits so there's not so many?
2. Why is @ZengBeauty added?  That user looks otherwise unrelated to this PR.
3. Can you avoid adding exceptions to the linter rules?

**Comment by youngjuning** [comment]
> This has a few things that make it hard to see what's going on:
> 
> 1. Can you please rebase & squash the commits so there's not so many?
> 2. Why is @ZengBeauty added?  That user looks otherwise unrelated to this PR.
> 3. Can you avoid adding exceptions to the linter rules?

1. I had rebased it
2. I had removed @ZengBeauty
3. If it is deleted, there is a lot of work to be done, thank you for your understanding

**Review by ShinyLeee — APPROVED** [review]

**Review by andrewbranch — CHANGES_REQUESTED** [review]
> If it is deleted, there is a lot of work to be done, thank you for your understanding

The title of this PR is "add docs comment," but if that were the only change, none of these lint rule exceptions would need to be added (except maybe the max-line-length one—not sure whether that applies in comments, but I thought it didn’t). The very first changes in index.d.ts introduce new types, so I’m a little confused about what this PR is. Maybe this should be split into two PRs, one adding doc comments and one adding the new types, so it’s easier to review, and we can easier help you avoid disabling lint rules. As it is, I’m not super comfortable merging a huge set of unexplained changes that require disabling lint rules.

**Comment by youngjuning** [comment]
@andrewbranch

image

**Comment by youngjuning** [comment]
- useTheme: line 9973
- TransitionPresets: line 10429

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by youngjuning** [comment]
Ready to merge

**Pull request merged**
