### PR TITLE
`immutable` provides its own types

### PR DESCRIPTION
**Pull request by ghost**
This deprecates "@types/immutable" in favor of just "immutable". CC @tht13 @leebyron

### CODE REVIEW

**Review by mhegazy — APPROVED** [review]

**Comment by alejo90** [comment]
@andy-ms @mhegazy I just realized this had been done. The typings provided by the library do not support `strict-null-checks`, whereas the ones here do.

**Comment by andy-ms** [comment]
Why not make a pull request to the library improving their typings?

**Comment by alejo90** [comment]
I'll try but I don't know if they want to commit to typescript 2 yet. The project may still be used by lots of companies that use 1.8 and I don't know if adding `null` and `undefined` to the signatures will break things for them.

**Comment by alejo90** [comment]
Never mind. It seems like they want to support `strict-null-checks` https://github.com/facebook/immutable-js/commit/e7be08bcf353aa29fcf5400022973d6dcfaa1cc2

**Pull request merged**
