### PR TITLE
Remove the typings for Protractor as it provides its own typings

### PR DESCRIPTION
**Pull request by thorn0**
done like described here: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

### CODE REVIEW

**Comment by thorn0** [comment]
People run into issues with @types/protractor whereas they should use the bundled typings instead. E.g. see #12225.

**Comment by cnishina** [comment]
@juliemr Let's discuss this tomorrow.

**Review by vvakame — APPROVED** [review]

**Comment by vvakame** [comment]
@andy-ms could you review this PR?

**Review by ghost — APPROVED** [review]

**Comment by cnishina** [comment]
:tada: This is awesome. Thanks @thorn0

**Pull request merged**
