### PR TITLE
Added the type definitions for the lobibox library

### PR DESCRIPTION
**Pull request by itboy87**
i tested it working perfect i'm also using it in my project

### CODE REVIEW

**Comment by itboy87** [comment]
@dt-bot  i updated the code also fixed some errors please build it again i also added test file (lobibox/lobibox.js-test.ts)

**Comment by itboy87** [comment]
@dt-bot Travis CI test is passed every thing is ok now test file also included please merge it

**Comment by vvakame** [comment]
@itboy87 please rename lobibox/lobibox.js-test.ts to lobibox/lobibox.js-tests.ts

**Comment by itboy87** [comment]
@vvakame  done

**Comment by vvakame** [comment]
@itboy87 oh, sorry. rename to `lobibox/lobibox-tests.ts`. not `lobibox/lobibox.js-tests.ts`.

**Comment by itboy87** [comment]
@vvakame i think its ok now

**Comment by vvakame** [comment]
congrats! :+1:

**Pull request merged**
