### PR TITLE
elasticsearch: add error classes, flatten definitions, lint

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/elastic/elasticsearch-js/blob/14.x/src/elasticsearch.js#L13 https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/errors.html
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

# Note: Diff is huge as I moved everything out of a redundant `module` declaration, actual diff is smaller, view with `?w=1` to ignore whitespace changes.

The initial goal was to simply add the error typings, went a little further tho.
I had to restrict the new typings to >= TS 2.2 due to the use of `object`.

### CODE REVIEW

**Comment by pushplay** [comment]
I didn't take on the linting changes because I'm a wuss but those get a :+1: from me.

Why the change of Array notation?  eg: `GetResponse<T>[]` to `Array<GetResponse<T>>`.  My understanding is that `[]` is preferred.

**Comment by SimonSchick** [comment]
@pushplay TSLint complained. Apparently `complex` types must be used with `Array<>` for some reason.

**Comment by pushplay** [comment]
😞 ... well I guess if that's what the repo prefers that's what we go with.

The change in module structure means an `Elasticsearch` namespace is no longer exported globally.  That's a breaking change although I think that brings that package in line with the standard so I'm good with it.  I'd like to give other people a chance to weigh in on it though.

**Comment by SimonSchick** [comment]
I was considering the `global` to  be an unintentional leak.
In retrospect I cannot imagine anyone using this aside from a browser environment (which I find highly unlikely).

In any case the consumer should decide wether they want the namespace to be global or not, in the end it's basically:

```typescript
import * as elasticsearch from 'elasticsearch';
declare global {
   Elasticsearch: typeof elasticsearch;
}```

**Comment by uniqueiniquity** [comment]
Code looks good, waiting to merge due to request by @pushplay for more input on removed global export.

**Comment by pushplay** [comment]
It's been 2 days and no one else has added input.  Let's merge it.

:+1:

**Pull request merged**
