### PR TITLE
Add definitions for apple-signin-api

### PR DESCRIPTION
**Pull request by voidpumpkin**
Adding definitions for [apple-signin-api](https://developer.apple.com/documentation/signinwithapplejs)

Apple documentation is actually not completely in sync with all the data we have, so here are some pictures objects in use:
image
image
image

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Comment by koenpunt** [comment]
Thanks for this, but how am I supposed to use this?

**Comment by koenpunt** [comment]
I've now added a custom declaration, but I think it's supposed to work straight away?

```ts
declare var AppleID: AppleSignInAPI.AppleID;
```

**Comment by voidpumpkin** [comment]
@koenpunt It seems you are using it perfectly with `AppleSignInAPI.AppleID` since `AppleSignInAPI` namespace is just available globally.

Unless im being a noob and i was supposed to do this in some other way.

In my use case we just add to the Window interface `AppleID: AppleSignInAPI.AppleID;`.

**Pull request merged**
