### PR TITLE
Update MongoDB type definitions inside @types/meteor

### PR DESCRIPTION
**Pull request by filipenevola**
Update MongoDB type definitions inside Meteor types so we can read directly from MongoDB typedefs now that they are published from the npm package.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url](https://github.com/mongodb/node-mongodb-native/blob/HEAD/docs/CHANGES_4.0.0.md)

Pending tests:
- [x] When running `npm test meteor` I'm getting errors due to Typescript 3.8, the errors are coming from `node_modules/mongodb`. Many errors like:
  ```txt
  Error: Errors in typescript@3.8 for external dependencies:
  node_modules/mongodb/mongodb.ts34.d.ts(36,135): error TS2304: Cannot find name 'TypedEventEmitter'.
  ```

### CODE REVIEW

**Comment by Julusian** [comment]
@filipenevola If you set https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor/index.d.ts#L22 to `// Minimum TypeScript Version: 4.1`, that resolves the issue.

I don't know why dtslint isnt liking mongodb in typescript 4.0 and older. It feels likes a bug in typescript/dtslint not handling the declarations being in the wrong order, but as meteor doesnt support typescript that old I dont see the point in figuring out a proper solution

**Comment by Julusian** [comment]
oh good.. I didnt realise that it could fail in that way

**Comment by filipenevola** [comment]
> oh good.. I didnt realise that it could fail in that way

Let me see if I can fix the other packages with the commit above.

**Comment by Julusian** [comment]
I have no idea what the policy is on setting minimum typescript versions, but doing it to some of those packages doesnt feel ok..
I feel like its going to end up going down a bit of a rabbit hole chasing dependants.
It does look like some could be patched to not rely on meteor, or perhaps deleted altogether. 
this one is such a great package  https://github.com/jboulhous/dev

**Comment by filipenevola** [comment]
The CI npm tests are passing now but we have this markdown error, in my machine, it is running fine, without errors.

I believe this is a problem in the CI setup. Not sure who could help with this.

**Comment by filipenevola** [comment]
This PR is failing because any changes to readmes are causing PRs to fail as you can see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58591).

**Comment by amcasey** [comment]
Re-opened to re-trigger CI.

**Comment by filipenevola** [comment]
This PR is ready to be merged.

**Review by radekmie — APPROVED** [review]

**Comment by perbergland** [comment]
what can we do to get this merged?

**Review by amcasey — APPROVED** [review]

**Comment by amcasey** [comment]
@perbergland Sorry about that, the bot got wedged, so this fell off our radar.

**Comment by amcasey** [comment]
It's just not going to let go of that CI Failed label...

**Pull request merged**
