### PR TITLE
[node-persist@v3.1.3] : Add writeQueue and descriptions to InitOptions

### PR DESCRIPTION
**Pull request by Dan-Shields**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/simonlast/node-persist/tree/master#async-initoptions-callback
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-persist/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f25c12f2c60835fde07f0a80c090c0411d363997
</p>

**Review by gabritto — CHANGES_REQUESTED** [review]
Does the original library disallow setting the properties to `undefined`? If not, please re-add the `| undefined` to the properties. Thanks.

**Comment by Dan-Shields** [comment]
> Does the original library disallow setting the properties to `undefined`?

@gabritto Is this a DT convention I missed? I'm using TS v5.3.2 to test and doing something like `storage.init({ dir: undefined })` works fine without `| undefined` in the type definition.

**Comment by Dan-Shields** [comment]
Thanks for explaining @eps1lon, now fixed.

**Review by andrewbranch — APPROVED** [review]

**Comment by Dan-Shields** [comment]
Ready to merge

**Pull request merged**
