### PR TITLE
Update StatusBar.d.ts

### PR DESCRIPTION
**Pull request by kdcllc**
Allows to build successfully the IONIC Cordova projects with TypeScript

### CODE REVIEW

**Comment by vvakame** [comment]
@Xinkai can I merge this PR?

**Comment by kdcllc** [comment]
Yes, i am not sure about the parse error. Thanks @Xinkai

**Comment by Xinkai** [comment]
From a syntax point of view, it looks good to me.

To be honest, I am not sure either as I have lost interest in this particular cordova plugin.

**Comment by vvakame** [comment]
sorry for late. happy new year! :smile_cat:

**Pull request merged**
