### PR TITLE
relay-runtime: Allow array of Uploadable in UploadableMap

### PR DESCRIPTION
**Pull request by AaronBuxbaum**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. (no relevant tests)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/relay-tools/react-relay-network-modern/blob/master/src/middlewares/upload.js#L19 (note that `extractFiles` allows taking an array of files or FileList)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 13 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b0fc7463d851ed3069f8d298459e3780b380f1a1
</p>

**Review by Stephen2 — COMMENTED** [review]
Can you please explain more to me?

https://github.com/facebook/relay/blob/eb256a3b2c85161936f742f3dbea8de9b6cb2a3e/packages/relay-runtime/network/RelayNetworkTypes.js#L123
There :arrow_up: you will see that in the actual `relay-runtime` library, this type is correct (inexact type converts to Interface, only accepts `Uploadable`)

I think the current types are correct, but you linked to a different library?

**Comment by AaronBuxbaum** [comment]
> Can you please explain more to me?
> 
> https://github.com/facebook/relay/blob/eb256a3b2c85161936f742f3dbea8de9b6cb2a3e/packages/relay-runtime/network/RelayNetworkTypes.js#L123
> There ⬆️ you will see that in the actual `relay-runtime` library, this type is correct (inexact type converts to Interface, only accepts `Uploadable`)
> 
> I think the current types are correct, but you linked to a different library?

The link is a case of a popular-ish network layer library; it's not necessarily canonical, but it's an example of a use-case which considers an array of files (or `FileList`) to be a reasonable input as uploadable.

For context, imagine you have a `multiple` file input and want to upload two files, for sake of example. The "raw" type will be `FileList` -- which is not supported as an uploadable type, nor is an array of files. As far as I can tell, the two approaches are:
1. allow `FileList` or `Uploadable[]` as uploads (this does correctly "work", for what it's worth)
2. force the consumer to create a map from uploadables such that the user sets two separate uploadables along with another `FormData` attribute to provide the backend information about which `FormData` attributes are uploadables.

In the case of relay-tools' implementation, it compiles simply because it's not written in Typescript.

I'm okay with either way; the former seems more reasonable to the consumer and I saw no information indicating that leaving out multiple file input boxes was an intentional design, but there very well could be good reasons to avoid `FileList` or `Uploadable[]`. You're right that it's counter to this suggestion in the actual library; I'm happy to suggest this change there as well, at least to get some context on why it was designed in that way.

**Comment by Stephen2** [comment]
Thanks for the explain.  On this repo, I have to say this is above my pay grade, and defer to a more experienced maintainer

**Comment by maraisr** [comment]
I think the idea here is that, its one file_name to one file. So there _would_ only ever be a one-to-one mapping. The idea being that you'd fundamentally use [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#creating_a_formdata_object_from_scratch), where it's just a `.append`, of a key value pair.

There are no _real_ implementation details that tell us if this **should** be an array or not, other than the types not covering that case—and the docs alluding to this being used for FormData  [_"and uploading form data for mutations (the uploadables parameter)."_](https://github.com/facebook/relay/blob/master/website-v2/versioned_docs/version-v1.5.0/Modern-NetworkLayer.md).

Granted `react-relay-network-modern` implement this as an array, this particular package isnt types for that one. Its types for the Facebook Relay package.

Thankyou for the effort here though @AaronBuxbaum

**Comment by AaronBuxbaum** [comment]
> I think the idea here is that, its one file_name to one file. So there _would_ only ever be a one-to-one mapping. The idea being that you'd fundamentally use [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#creating_a_formdata_object_from_scratch), where it's just a `.append`, of a key value pair.
> 
> There are no _real_ implementation details that tell us if this **should** be an array or not, other than the types not covering that case—and the docs alluding to this being used for FormData [_"and uploading form data for mutations (the uploadables parameter)."_](https://github.com/facebook/relay/blob/master/website-v2/versioned_docs/version-v9.1.0/Modern-NetworkLayer.md).

Thanks for the thoughtful response here! I think this is fair enough; I did just want to point out that `FormData` can natively be an array (or at least, array-like in behavior):
```
const formData = new FormData();
formData.append('myKey', 1);
formData.append('myKey', 2);
formData.append('myKey', 3);
```
this results in a value of `[1, 2, 3]`, not `3`; therefore I think the allusion to FormData doesn't signal much either way


> Granted `react-relay-network-modern` implement this as an array; however this particular package (`@types/relay-runtime`) isnt types for that one. Its types for the Facebook Relay package.

The reason I submit here is because we use `react-relay-mutation`, which uses `relay-runtime` as its config types, so it makes most sense to figure out what the "correct" approach is all the way at the end of the line and bubble that forward. I reference `react-relay-network-modern` just as an example to show that a library with light support from Relay accepts arrays, in absence of stronger guidance from Relay itself

To be clear, I'm unsure if the missing array input is intentional or an oversight; I'm not attached to either way but very interested in proper approach to the problem

**Comment by alloy** [comment]
To me, the foremost question is, should the upstream definition of the API and its typings be amended? In which case, after fixing it there, we can follow that here. Would you mind sending a issue/PR upstream first?

**Comment by AaronBuxbaum** [comment]
Here's the PR to Relay: https://github.com/facebook/relay/pull/3359

No progress yet, so no worried about this PR!

**Comment by Stephen2** [comment]
Let's close this PR

**Comment by AaronBuxbaum** [comment]
👍 I'll reopen if I have any success on the relay PR. Thanks for your attention :D

**Comment by elibarzilay** [comment]
@AaronBuxbaum: should this be closed?

**Pull request closed without merging**
