### PR TITLE
Improve JSDoc formatting

### PR DESCRIPTION
**Pull request by xamgore**
In this PR I have changed:
* outdated links (3.1 -> 3.6 version) with simultaneous update of outdated type definitions `ClientSession`, `ReadPreference`
* `http://` links into `http://` for MongoDB websites
* documentation comments: formatting, @see and @link attributes, etc
* functions, where the return type depends on the parameters
* error classes as the driver exports more than there are now in `d.ts`

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongodb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongodb@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'mongodb'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f748f68b39a74b2e637adf6e493549529ab3e138
</p>

**Comment by peterblazejewicz** [comment]
It seems not so strightforward as JSDocs improvement, there real minor changes there were not covered by test,
(opting out to method overloads, etc). Can this lead to unexpected outcomes?

**Comment by xamgore** [comment]
Overloads — barely possible. The returned type used to be `Promise<void> | void`, now it is either `Promise` or `void` which is subset of their union. That means the user land code should work as expected.

Errors — they were just added, no breaking changes.

**Review by rbuckton — APPROVED** [review]

**Comment by xamgore** [comment]
Ready to merge

**Pull request merged**
