### PR TITLE
Added some missing properties

### PR DESCRIPTION
**Pull request by Strato**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

'getSignalBars()' seems to always return null anyway...

Whole Windows.Data.Pdf namespace is still missing.

Lots of class of Windows.ApplicationModel.Contacts are missing as well.

### CODE REVIEW

**Comment by vvakame** [comment]
please fix travis ci first.

**Comment by Strato** [comment]
I made the changes directly in GitHub. I have no idea what Travis is.

**Comment by Strato** [comment]
I found what was wrong. Sorry for the waste of time.

Should be ready for merge now.

**Comment by vvakame** [comment]
@craigktreasure @Megasware128 can anyone review this PR?

**Comment by mhegazy** [comment]
No response from other authors for over 2 weeks. Merging.

**Pull request merged**
