### PR TITLE
Implemented xml-js

### PR DESCRIPTION
**Pull request by DenisCarriere**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
These travis-ci build times are so long... Anyway to speed up the testing?

**Comment by vvakame** [comment]
you can try `./node_modules/.bin/tsc -p ./xml-js` before send pull request.

**Comment by DenisCarriere** [comment]
The test failed but not from my package.

`chocolatechipjs` caused the error.
```
.............................................................................
.............................................................................
.............................................................................
.................................................== Errors when compiling /home/travis/build/DefinitelyTyped/DefinitelyTyped/chocolatechipjs/tsconfig.json ==
\home\travis\build\DefinitelyTyped\DefinitelyTyped\chocolatechipjs\index.d.ts
	 Line 1363: All declarations of 'responseURL' must have identical modifiers.
............x...............
.............................................................................
.............................................................................
.............................................................................
.........................
-----------------------------------------------------------------------------
 Elapsed time    : ~1 hour (5629.835s)
 Successful      : 99.96% (2257/2258)
 Failure         : 0.04% (1/2258)
=============================== Header format ===============================
.............................................................................
```

**Comment by DenisCarriere** [comment]
Opened a new PR.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12433

**Pull request closed without merging**
