### PR TITLE
feat(puppeteer): 2.0

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Changes:
 - Removed 0.x
 - Updated 1.x to 2.x in place

Rationale:
 - 0.x (unstable) is 2 years old and no longer maintained, the package will remain
 - 1.x Moved to own folder, package currently has ~250k downloads per week and will probably need minor maintenance in the future.
 - 2.x VERY few changes major release was due to dropping node v6. Used opportunity to bump to TS 3.0 and change some instances of `any` to `unknown` for improved type safety.

### CODE REVIEW

**Comment by SimonSchick** [comment]
@jessetrinity same issue as node, can't remove the v0 typings, breaks ci.

**Comment by jessetrinity** [comment]
@sandersn same `cannot find version 0` issue as #39399

**Comment by sandersn** [comment]
Filed https://github.com/microsoft/types-publisher/issues/696 to track this; I think it's something that needs to be explicitly allowed because we didn't consider the case that people would want to explicitly drop support for old versions.

**Comment by SimonSchick** [comment]
@jessetrinity can we keep this PR alive?

**Comment by SimonSchick** [comment]
*sigh*

**Comment by SimonSchick** [comment]
😂

**Comment by SimonSchick** [comment]
Going to re-open this in another PR since the bot obviously hates me.

**Pull request closed without merging**
