### PR TITLE
[jsdoc-to-markdown] Fix JsdocOptions noCache prop name

### PR DESCRIPTION
**Pull request by fturmel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgetjsdocdataoptions--promise
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by fturmel** [comment]
@azerella Heads up, I think you might've changed your GitHub account username and are not getting PR notifications from this repo's bot. You are set as a code owner for `jsdoc-to-markdown` and about 40 projects under @adamzerella.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@fturmel thx!

**Comment by fturmel** [comment]
Ready to merge

**Comment by fturmel** [comment]
@peterblazejewicz thanks for the quick review!

**Pull request merged**
