### PR TITLE
feat(cache-manager): update types for cache usage

### PR DESCRIPTION
**Pull request by BlackDark**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test cache-manager`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/BryanDonovan/node-cache-manager
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. Updated to **3.4.0**

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50499 provides small part of changes. I updated similar methods and added tests.

Issue in repo: BryanDonovan/node-cache-manager#150

Cheers

### CODE REVIEW

**Review by MickL — APPROVED** [review]
Looks awesome!

**Comment by MickL** [comment]
Could you add yourself, and maybe @BryanDonovan, to the "Definitions by" in `index.d.ts`? Seems like @GausSim @dominikeinkemmer are not maintaining anymore.

**Comment by BlackDark** [comment]
@MickL could your refresh the approval. Then I can merge the PR

**Review by MickL — APPROVED** [review]

**Comment by BlackDark** [comment]
Ready to merge

**Comment by rubiin** [comment]
getting errors like {} not assignable to type x after update?

**Comment by BlackDark** [comment]
> getting errors like {} not assignable to type x after update?

How does your code look like?

```ts
    const value1 = await this.cacheManager.get('hello'); // type is unknown
    const value2 = await this.cacheManager.get<any>('hello'); // type is any
    const value3 = await this.cacheManager.get<string>('hello'); // type is string
    const value4 = await this.cacheManager.get<{}>('hello'); // type is object
```

**Comment by rubiin** [comment]
first one

**Pull request merged**
