### PR TITLE
Fix default export in rc-tooltip package (fix #19372)

### LINKED ISSUE #19372: types/rc-tooltip suggests Tooltip module is not 'default'
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rhysd, @ahstro 

Apologies in advance if I've specified the wrong authors. This is such a large repo I went for people who at least touched some of the files in `types/rc-tooltip`. Using `npm` package `rc-tooltip: 3.4.8` with `@types/rc-tooltip 3.4.8` indicates something wrong in the types declaration. I have remedied this myself by changing the last three lines of `types/rc-tooltip/index.d.ts` to

```
declare module "rc-tooltip" {
    export default Tooltip
}
```

This correctly reflects what the actual `rc-tooltip` library does. I thought I'd leave this here and ask whether I'm consuming this type / rc-tooltip library incorrectly (works with this one small change) or whether I should make a pull request with this fix / change in it.

Thanks!

### PR DESCRIPTION
**Pull request by rhysd**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19372
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by rhysd** [comment]
Author of this PR is also the author of the type definitions file. How can I get review?

**Comment by ikatyang** [comment]
The bot works fine with author links like `https://github.com/xxxxxx`, I think you can correct the link and open another PR, the bot should triage correctly with that.

**Comment by rhysd** [comment]
@ikatyang I'm correctly recognized as author of this type definition file as per [the comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19417#issuecomment-325622877). But even if type definition author, PR cannot be approved by the author of the PR.

**Comment by ikatyang** [comment]
The question is, the PR creator should not be mentioned, and self-approved is not allowed.

If there's no author be mentioned, this PR will be marked as `Unowned` then the DT maintainers will review this PR.

**Comment by ikatyang** [comment]
For example, this is my PR (#19413) and I'm the only author, it's correctly triaged by the bot and be reviewed by DT maintainer.

**Comment by rhysd** [comment]
Yeah, actually there is another name in header but I don't know how to request a review to this person. Mention by bot is not working due to unknown URL in signature.

> ahstro <http://ahst.ro>

**Comment by ikatyang** [comment]
The new dtslint rule enforce author links to be `https://github.com/xxxxx`, but it seems dtslint is not enable in this definition.

- [DT progress](https://github.com/DefinitelyTyped/DefinitelyTyped/projects/3?card_filter_query=is%3Aopen)
- [triage rule](https://github.com/RyanCavanaugh/dt-mergebot/blob/master/policy.md)

As you can see in the DT progress and triage rule, un-labeled PRs won't be reviewed by DT maintainers within 3 days (at least).

- Express Merge
  - author approved
  - no delay
- Unowned
  - need review from DT maintainer
  - no delay
- LGTM Merge
  - other approved
  - three days later
- YSYL Merge
  - no one review
  - five days later

So I'm suggesting you to open another PR with correct author link (at least yours), it should be marked as `Unowned` then DT maintainer will review it. Otherwise you'll have to wait for 5 days.

I'm not familiar with React so I'm not able to review this one, sorry for that.

**Comment by rhysd** [comment]
Thank you for the detail. I understood the situation. This PR does not block my project hence it's not urgent. So I leave this PR open and wait for YSYL merge. Next time, I'll consider to fix the signature.

**Pull request merged**
