### PR TITLE
[draft-js] Export EditorCommand

### PR DESCRIPTION
**Pull request by PeterDekkers**
Resolves #54954

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://draftjs.org/docs/quickstart-rich-styling#richutils-and-key-commands

### CODE REVIEW

**Comment by PeterDekkers** [comment]
Tidying up the commit history... 😬

**Comment by PeterDekkers** [comment]
The owners are _not_ being edited by this PR. The label was added due to incorrectly rebased history, which has now been fixed. Thanks!

**Review by ankitr — APPROVED** [review]
Sorry for the delay — looks good!

**Comment by PeterDekkers** [comment]
Ready to merge

**Pull request merged**
