### PR TITLE
Updating copy-webpack-plugin 6.3+ to use the default webpack 5 typings instead of the @types/webpack one

### PR DESCRIPTION
**Pull request by dl748**
Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49528
copy-webpack-plugin 6.3+, they upgraded the webpack support to version 5 which includes its own typings

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## copy-webpack-plugin ([<kbd>unpkg</kbd>](https://unpkg.com/browse/copy-webpack-plugin@latest/))
was missing the following properties:
1. createSnapshot
1. checkSnapshotValid
1. runPattern
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7edefe334a7b5b8b991f32d238648f4dc74e4d49
</p>

**Review by peterblazejewicz — APPROVED** [review]

**Comment by LabhanshAgrawal** [comment]
@peterblazejewicz @dl748 it's still showing as dependent on @types/webpack which is causing issues. I can send a pr if someone can direct me as to how to remove the dependency.

**Comment by dl748** [comment]
While it does have a dependency @types/webpack, and it does install.  Typescript will use the packages typings before @types/webpack unless you force it.  I've installed the latest into my projects and i'm not seeing any errors.  Try npm ci or deleting your node_modules/package-lock.json file and reinstall.

Its more likely, that you installed the latest version of copy-webpack-plugin which requires webpack 5, and you are using webpack 4.  Webpack 4 does NOT have typings and will default to @types/webpack.

**Comment by LabhanshAgrawal** [comment]
I'm using webpack 5 with the latest copy-webpack-plugin and the types. I'm getting errors for the `@types/webpack` files which look like collisions with the bundled types. I've removed `@types/webpack` from my `package.json` but it's installing as dependency of this module.
I'm not forcing the types (afaik). I'm getting the errors during `tsc --build`.
Also, I think even if it's not causing trouble, the dependency should be removed as it's not using it.

**Comment by dl748** [comment]
While I agree with you.  I'm not seeing any problems.

webpack@5.6.0
@types/webpack@4.41.25
typescript@4.1.2

6.2.0 version
```
$ npm install @types/copy-webpack-plugin@6.2.0
$ npx tsc webpack.config.ts
node_modules/@types/copy-webpack-plugin/index.d.ts:7:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

7 import { Plugin } from 'webpack';
           ~~~~~~

$
```

6.3.0 Version
```
$ npm install @types/copy-webpack-plugin@6.3.0
$ npx tsc webpack.config.ts
$
```

**Comment by LabhanshAgrawal** [comment]
You can check https://github.com/LabhanshAgrawal/hyper/tree/webpack
and run `yarn && yarn run tsc webpack.config.ts`
it gives errors like
```
node_modules/@types/webpack/index.d.ts:32:3 - error TS2305: Module '"../../tapable/tapable"' has no exported member 'Tapable'.

32   Tapable,
     ~~~~~~~

node_modules/@types/webpack/index.d.ts:1062:23 - error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1062             resolver: SyncWaterfallHook;
                           ~~~~~~~~~~~~~~~~~

node_modules/@types/webpack/index.d.ts:1063:22 - error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1063             factory: SyncWaterfallHook;
                          ~~~~~~~~~~~~~~~~~

node_modules/@types/webpack/index.d.ts:1064:28 - error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1064             beforeResolve: AsyncSeriesWaterfallHook;
                                ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/webpack/index.d.ts:1065:27 - error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1065             afterResolve: AsyncSeriesWaterfallHook;
                               ~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by dl748** [comment]
Umm that doesn't have anything to do with copy-webpack-plugin update.  Looks like tapable is using those symbols.  That has nothing to do with this PR.

**Comment by dl748** [comment]
Cloned your repo.  I'm not seeing ANY of those errors.

```
$ ~/.local/bin/yarn run tsc webpack.config.ts
yarn run v1.22.10
$ ./hyper/node_modules/.bin/tsc webpack.config.ts
webpack.config.ts:1:8 - error TS1259: Module '"./hyper/node_modules/@types/copy-webpack-plugin/index"' can only be default-imported using the 'esModuleInterop' flag

1 import Copy from 'copy-webpack-plugin';
         ~~~~

  node_modules/@types/copy-webpack-plugin/index.d.ts:119:1
    119 export = copyWebpackPlugin;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

webpack.config.ts:2:8 - error TS1259: Module '"path"' can only be default-imported using the 'esModuleInterop' flag

2 import path from 'path';
         ~~~~

  node_modules/@types/node/path.d.ts:152:5
    152     export = path;
            ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

webpack.config.ts:3:8 - error TS1259: Module '"./hyper/node_modules/@types/terser-webpack-plugin/index"' can only be default-imported using the 'esModuleInterop' flag

3 import TerserPlugin from 'terser-webpack-plugin';
         ~~~~~~~~~~~~

  node_modules/@types/terser-webpack-plugin/index.d.ts:95:1
    95 export = TerserPlugin;
       ~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

webpack.config.ts:4:8 - error TS1259: Module '"./hyper/node_modules/@types/webpack/index"' can only be default-imported using the 'esModuleInterop' flag

4 import webpack from 'webpack';
         ~~~~~~~

  node_modules/@types/webpack/index.d.ts:49:1
    49 export = webpack;
       ~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 4 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However, I am able to fix that but updating the webpack.config.ts for correctly importing the modules

```
$ ~/.local/bin/yarn run tsc webpack.config.ts
yarn run v1.22.10
$ ./hyper/node_modules/.bin/tsc webpack.config.ts
Done in 10.59s.
```
```
$ ~/.local/bin/yarn run tsc --version
yarn run v1.22.10
$ ./hyper/node_modules/.bin/tsc --version
Version 4.0.5
Done in 0.35s.
```

I think you may have a problem with your environment setup, and someone needs to fix the webpack.config.ts imports.

**Comment by LabhanshAgrawal** [comment]
I'm guessing you checked the default branch (canary)
I'd put the link but should've mentioned also that I'm doing the update in `webpack` branch, my bad.
I'm getting the errors there, and have checked that it's using the correct version

```
$ yarn run webpack --version
yarn run v1.22.5
$ /Users/l0a00lp/git/hyper/node_modules/.bin/webpack --version

webpack-cli 4.1.0

webpack 5.6.0

✨  Done in 0.39s.
```

Note: the errors come even if you replace the imports with `import * as`

**Comment by dl748** [comment]
Because there are no new version according to the readme, there is a way to remove webpack from the inclusion list which is considered the correct way

`npm run not-needed -- webpack 5.0.0`

which says "as of webpack 5.0.0, use webpacks built in types. 

Readme doc
```
Removing a package
When a package bundles its own types, types should be removed from Definitely Typed to avoid confusion.

You can remove it by running npm run not-needed -- typingsPackageName asOfVersion [libraryName].
```

Unfortunately, that breaks other types.

**Comment by dl748** [comment]
@LabhanshAgrawal see issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49757 that i opened.

**Comment by nzjony** [comment]
@dl748 , I have the issue that @LabhanshAgrawal  mentioned above reproducing here: https://github.com/nzjony/copy-webpack-plugin-types-typescript-test

**Pull request merged**
