### PR TITLE
feat(three): improve ts moduleResolution

### PR DESCRIPTION
**Pull request by Wxh16144**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. CompressedCubeTexture
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 882cf3ee55a79cefca7707521c13037faeed35ef
</p>

**Comment by Methuselah96** [comment]
Hey @Wxh16144!

Can you explain what you are trying to accomplish? Also, can you create the PR at https://github.com/three-types/three-ts-types?

Thanks!

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Please provide explanation for the issue you are trying to fix.

**Comment by jakebailey** [comment]
Also, why does `@types/three` contain an export map with `.js` files at all?

**Comment by Wxh16144** [comment]
This PR I'll review again, in my project I fixed it temporarily in the form of a patch.

**Pull request closed without merging**
