### PR TITLE
added typings for mendixmodelsdk@0.0.1

### PR DESCRIPTION
**Pull request by mweststrate**
Please note that these typings depend on https://github.com/borisyankov/DefinitelyTyped/pull/5943 to be accepted first.

### CODE REVIEW

**Comment by vvakame** [comment]
*mendixmodelsdk/mendixmodelsdk.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/mendixmodelsdk
  * http://bower.io/search/?q=mendixmodelsdk
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (mendixmodelsdk/mendixmodelsdk-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by mweststrate** [comment]
Since #5943 has been merged, I'll pushed a commit to trigger the CI again. It passes now.

**Comment by mweststrate** [comment]
Ping! @vvakame could you verify that the CI succeeds now? Thanks in advance!

**Comment by vvakame** [comment]
okay! thanks mate.

**Pull request merged**
