### PR TITLE
[react-intl] add number to possible types of values passed to FormattedMessage

### PR DESCRIPTION
**Pull request by briantobo**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yahoo/react-intl **see how the example passes a number value (unreadCount) in 'values'**
- [ ] Increase the version number in the header if appropriate. **I'm not sure if this is needed and if so where to do it**
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`. **These are not really substantial changes.**

### CODE REVIEW

**Comment by gyzerok** [comment]
Hi @briantobo!

First of all thank you for you PR and welcome to DefinitelyTyped!

What benefits do you see of being able to pass `number` instead of just making `num.toString()` conversion?

Also can you, please, next time use link to the specific line in code so one do not need to spend time searching it himself.

**Comment by briantobo** [comment]
Hi !

Well it makes the code just a little bit shorter, but mostly it is supported by the react-intl library so I think the typings should allow it.

There is only one piece of code in the page I linked to so I thought it would be pretty straightforward but let me copy a shorter version here if that helps :

    render() {
        // This data will come from an API or a Redux store or something else...
        const name = "Joe";
        const unreadCount = 123;

        return (
            <p>
                <FormattedMessage
                    id="welcome"
                    defaultMessage={`Hello {name}, you have {unreadCount, number} {unreadCount, plural,
                      one {message}
                      other {messages}
                    }`}
                    values={{name: <b>{name}</b>, unreadCount}}    // <-- unreadCount is number here
                />
            </p>
        );

**Comment by gyzerok** [comment]
Makes sense to me :)

Maybe I am missing something, but it looks like you linked the whole repository, not the particular page.

**Review by gyzerok — APPROVED** [review]
LGTM 👍

**Comment by cdroulers** [comment]
👍 LGTM!

**Comment by briantobo** [comment]
Ah sorry I see what you mean, I meant to link to the README of react-intl which has that example :)

**Pull request merged**
