### PR TITLE
[detect-port]: add PortConfig type for first argument from default function

### PR DESCRIPTION
**Pull request by ivandevp**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/node-modules/detect-port/blob/master/lib/detect-port.js#L10>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by orta** [comment]
I think you accidentally included the .tgz in this PR

**Comment by ivandevp** [comment]
Thanks @orta! I didn't see it. I've just removed it.

**Comment by peterblazejewicz** [comment]
> I think you accidentally included the .tgz in this PR

@orta 
Maybe the `.gitignore` can be amended to ignore this (referring to the gitter's discussion).

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@ivandevp thx for contribution!

**Comment by ivandevp** [comment]
Ready to merge

**Pull request merged**
