### PR TITLE
feat: add slot element for jsx

### PR DESCRIPTION
**Pull request by Jack-Works**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Slot

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Slot

### CODE REVIEW

**Comment by Jack-Works** [comment]
the CI error is not related to my changes

**Review by ferdaber — APPROVED** [review]
Can a maintainer merge this in manually? It doesn't seem like the Travis errors are related to his changes.

**Comment by Jack-Works** [comment]
@typescript-bot hey stop! don't do it!

@Jessidhia @johnnyreilly Hi please check this out! I don't want to open a third PR for this small change!

**Comment by eps1lon** [comment]
@Jack-Works Try rebasing this with master. Should get the new bot workflow and hopefully resolves issues.

**Comment by orta** [comment]
Let's see if this fixes it

**Pull request merged**
