### PR TITLE
Ember Data: fix `Snapshot.belongsTo`.

### PR DESCRIPTION
**Pull request by chriskrycho**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/emberjs/data/blob/master/addon/-private/system/snapshot.js#L159-L193>
- ~Increase the version number in the header if appropriate.~
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by dwickern** [comment]
Could we add some tests for this snapshot stuff? I'm not sure there are any official code samples but there's plenty on emberobserver code search.

**Comment by chriskrycho** [comment]
I’m happy to, but couldn’t figure out how I wanted to do it and wanted feedback as well. These APIs are “intimate” but very accessible and hard to avoid in some circumstances, and not at all documented.

Thoughts?

**Comment by DanielRosenwasser** [comment]
@chriskrycho should I just go ahead and pull this in?

**Comment by DanielRosenwasser** [comment]
Ping @dwickern - I'd appreciate tests here too, but it sounds like @chriskrycho is looking for some guidance.

**Comment by chriskrycho** [comment]
I can put together some tests that it does what I think it does, at least. The problem from where I stand is that none of us writing this particular piece are especially confident on the Ember Data internals this reflects.

**Comment by DanielRosenwasser** [comment]
I figure we can always circle back to this.

**Comment by dwickern** [comment]
so.. circling back to it 😆 
I just added a couple of tests. I opened a new PR at #23770

**Comment by chriskrycho** [comment]
😆

**Pull request merged**
