### PR TITLE
react-vis: Fix Treemap and Sunburst types

### PR DESCRIPTION
**Pull request by fdw**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://uber.github.io/react-vis/documentation/other-charts/treemap and https://uber.github.io/react-vis/documentation/other-charts/sunburst-diagram

### CODE REVIEW

**Comment by fdw** [comment]
Is there any way I can help to speed this up?

**Comment by fdw** [comment]
I haven't abandoned the PR at all. But I don't see how I can help merging it, if no one reviews it.

**Comment by fdw** [comment]
@andrewbranch I'm truly sorry to mention you here even though you have nothing to do with this PR, but you seem to be an active maintainer of this repo. How can I make progress with this PR? @Domino987 seems to have abandoned it, and there is no other author for this package. I also haven't found any info in the readme or the FAQ.

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Hi @fwd I did not actually abandon it but I did not get these messages becuase they were moved to my spam folder. I Approved it just yet. Thank you

**Comment by fdw** [comment]
Awesome, thank ypu @Domino987 !

@typescript-bot Ready to merge

**Comment by fdw** [comment]
Ready to merge

**Pull request merged**
