### PR TITLE
Changed the GeocoderGeometry interface in googlemaps

### PR DESCRIPTION
**Pull request by jyotendra**
Please have a look at this [issue ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14400).
I propose solution to that problem with this fork.

### CODE REVIEW

**Comment by minestarks** [comment]
@jyotendra Could you please fix the failing tests so I can review? Thank you.

Since this PR is rather stale I plan to close in a few days if no activity.

**Comment by jyotendra** [comment]
It seems all tests are passing now. Please review the changes.

**Comment by minestarks** [comment]
@jyotendra Sorry for the delay. According to Google's documentation for the [Geocoding Service](https://developers.google.com/maps/documentation/javascript/geocoding), the existing types were accurate. 

I believe the link you referenced contains the API response, not the type of the JS objects in the client package.

**Comment by minestarks** [comment]
@cgwrench @Silver-Connection @nertzy @xaolas  are the authors (for some reason dt-bot can't parse the header) 

Any feedback on this PR?

**Comment by cgwrench** [comment]
I agree with [a previous comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14527#issuecomment-285520016): the previous types were correct. I think this pull request should be closed and not merged in.

**Comment by jyotendra** [comment]
I myself am not able to reproduce the issue now. It seems that just like @minestarks and @cgwrench said, the previous types are correct.
As I looked into google's docs [here](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingResults), I found that viewPort is indeed of type: "[LatLngBounds](https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBounds)".

Thanks for putting in your time. I will close the corresponding issue as well.

**Pull request closed without merging**
