### PR TITLE
[tether-drop] Remove 'element' property

### PR DESCRIPTION
**Pull request by elektromodulator**
Drop objects do not have an 'element' property, rather the root element of the drop DOM subtree is stored in a 'drop' property.
For this reason I renamed 'element' property to 'drop'.

### CODE REVIEW

**Comment by zhengbli** [comment]
Can you point to a documentation or spec about this change?

**Comment by elektromodulator** [comment]
No, just the source code. This part of the API is undocumented, unlike the [_content_ property](http://github.hubspot.com/drop/#changing-content).
This property is not necessary, since we could use the _content_ property to manipulate drop HTML content, but the d.ts file still does not correspond to the current state of the tether-drop library API, and this change is meant to amend that.
Do you think it would be preferable to remove _element_ property instead?

**Comment by zhengbli** [comment]
I would suggest not putting undocumented features in the d.ts file, because it may be misleading and they could always have breaking changes.

**Comment by elektromodulator** [comment]
OK, I can agree with that :smiley:. That's probably the source of this issue too.
I removed _drop_ property, which effectively means that the agenda of this pull request changed to:
Removing _element_ property from _Drop_ class, since it does not exist in JavaScript.

**Comment by zhengbli** [comment]
👍

**Comment by adidahiya** [comment]
sorry, I was on vacation during this PR. change lgtm 👍

**Pull request merged**
