### PR TITLE
[@types/assets-webpack-plugin]: Fix types to work with webpack 5

### PR DESCRIPTION
**Pull request by dfilatov**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by kryops — CHANGES_REQUESTED** [review]
Hi there,

while your're at it, would you mind bringing the options up to date with the current release?

Looking through the changelog and the current README, the following options are missing or outdated here:

* `integrity` is missing
* `includeFilesWithoutChunk` is missing
* `removeFullPathAutoPrefix` is missing
*  `includeManifest` seems to accept `boolean | string | string[]` now

(I might have overlooked something, feel free to double-check yourself :wink:)

Thanks a lot!

**Comment by dfilatov** [comment]
@kryops Thank you for quick response! I've added changes you requested.

**Review by kryops — APPROVED** [review]
LGTM, thanks!

**Comment by dfilatov** [comment]
Ready to merge

**Pull request merged**
