### PR TITLE
Add type definitions for @sematext/gc-stats

### PR DESCRIPTION
**Pull request by Jarco-dev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
Is this just a clone of @types/gc-stats?  Could you just use those types?

**Comment by Jarco-dev** [comment]
> Is this just a clone of @types/gc-stats? Could you just use those types?

Hello, yes this is a clone of @types/gc-stats because @sematext/gc-stats is a fork of gc-stats but with some vulnerabiliets fixed as gc-stats is no longer maintained as far as i know.

I've tried using them but ran into problems so i figured this would be the cleanest and most simple sollution around it.

**Comment by amcasey** [comment]
@Jarco-dev can you tell me a bit more about what problems you were having with the existing types?  They appear to be identical, aside from using double, rather than single, quotes around string literals.

**Review by amcasey — APPROVED** [review]
Sorry, mental blank on my part.   Forking the types makes sense. :smile:

**Comment by Jarco-dev** [comment]
Ready to merge

**Pull request merged**
