### PR TITLE
Fix tslint errors in node.d.ts.

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
This fixes most of the tslint errors in node.d.ts. I used the default tslint.json file. I'll make another PR to fix rest of the issues. It's quite useful to fix tslint issues in definition files since it's often inconvenient to exclude the .d.ts files from tslint. In addition, a good coding style is never a bad thing.

### CODE REVIEW

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by panuhorsmalahti** [comment]
Fixed conflicts.

**Comment by mhegazy** [comment]
some more conflicts. @panuhorsmalahti can you take a look.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
