### PR TITLE
fix: Fix Shippo constructor args and add missing instance methods

### PR DESCRIPTION
**Pull request by clalexander**
Fixes DefinitelyTyped/DefinitelyTyped#67776

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Provide a URL to documentation or source code which provides context for the suggested changes: [goshippo/shippo-node-client/lib/shippo.js](https://github.com/goshippo/shippo-node-client/blob/master/lib/shippo.js)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## shippo ([<kbd>unpkg</kbd>](https://unpkg.com/browse/shippo@latest/))
was missing the following properties:
1. DEFAULT_TIMEOUT
1. PACKAGE_VERSION
1. resources
1. Error
1. Resource

## Formatting

The following files are not formatted:
1. types/shippo/shippo-tests.ts
1. types/shippo/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0af6e56e54487faf70b45d96a605d622fc23ed7a
</p>

**Comment by clalexander** [comment]
Will create a separate PR for resources, Error and Recource types

**Comment by saiichihashimoto** [comment]
How does one get removed from these, and can I have that happen in one PR? I know nothing about shippo, I'm not going to be the one to ever review these.

**Comment by saiichihashimoto** [comment]
I'm unsure how to raise it to the maintainers directly besides in an issue/PR. Is this not the place to do that?

**Comment by clalexander** [comment]
I'm not sure.

@andrewbranch I found your name as an author as part of the `pnpm` conversion.  Are you able to provide any guidance regarding @saiichihashimoto 's question? Or could you point us to the right person if not?

**Comment by clalexander** [comment]
Thank you @andrewbranch !

@saiichihashimoto I removed you from the owners in `package.json`.

**Review by acommodari — APPROVED** [review]
LGTM 👍

**Comment by clalexander** [comment]
Ready to merge

**Pull request merged**
