### PR TITLE
[react-native] Make autoComplete prop cross-platform

### PR DESCRIPTION
**Pull request by chwallen**
Starting with 0.71, the autoComplete TextInput prop is available for both iOS and Android, whereas 0.70 only supported Android.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes). (I have not run Prettier as the entire package is incorrectly formatted)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://reactnative.dev/docs/textinput#autocomplete>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Is there a PR for facebook/react-native as well? /cc @lunaleaps

**Review by navya9singh — APPROVED** [review]

**Comment by chwallen** [comment]
> Is there a PR for facebook/react-native as well?

The change has already been merged to the react-native code. It is only the typing that has not.

**Comment by iRoachie** [comment]
@chwallen I opened the PR there -https://github.com/facebook/react-native/pull/36931. I added you as a co-author

**Comment by chwallen** [comment]
Ready to merge

**Pull request merged**
