### PR TITLE
feat(react): Remove type safety from returned ReactElement of JSXElementConstructor

### PR DESCRIPTION
**Pull request by eps1lon**
The `type` of the returned `ReactElement` of the function component constituent of `JSXElementConstructor` is now `any` (was `string | JSXElementConstructor<any>`.

This reduces the verbosity of this type.
Before:
screenshot of displayed type when JSX.ElementConstructor is hovered: `type React.JSXElementConstructor<P> = ((props: P) => React.ReactElement<any, string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: P) => React.Component<P, any, any>)`

After:
screenshot of displayed type when JSX.ElementConstructor is hovered: `type React.JSXElementConstructor<P> = ((props: P) => React.ReactElement<any, any> | null) | (new (props: P) => React.Component<P, any, any>)`

It matches the return type of `React.FunctionComponent` et. al.

 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- ~[ ]~ [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- ~[ ]~ Provide a URL to documentation or source code which provides context for the suggested changes: 
   Internal change of typings
- ~[ ]~ If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by eps1lon** [comment]
Can't reproduce the errors in CI with `npm run test-all` locally (even with a prior `git clean -fdx`)

**Review by dimitropoulos — APPROVED** [review]
please correct me if I'm wrong, but this seems like an uncontroversial consistency improvement

**Comment by dimitropoulos** [comment]
haha @eps1lon I appreciate the honesty

**Review by johnnyreilly — APPROVED** [review]

**Comment by eps1lon** [comment]
Ready to merge

**Pull request merged**
