### PR TITLE
First commit. Type definition for node-serialport.

### PR DESCRIPTION
**Pull request by sumitkm**
case 1. Add a new type definition.
- [ y] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ y] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ y] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by vvakame** [comment]
can you use this pattern? http://definitelytyped.org/guides/best-practices.html#ghost-modules

**Comment by sumitkm** [comment]
@vvakame Sure thing, I'll update the definition and re-submit.

**Comment by vvakame** [comment]
@sumitkm you can push additional commit to this branch. PR update automatically.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has merge conflicts and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
