### PR TITLE
React Native: Add type support for StyleSheet.create to get function style value

### PR DESCRIPTION
**Pull request by amerllica**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://reactnative.dev/docs/stylesheet>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by TheSavior** [comment]
These functions aren't recommended and aren't an official part of the StyleSheet API, just something StyleSheet isn't blocking. 

Instead we recommend a regular function that returns styles, outside of StyleSheet.

**Comment by amerllica** [comment]
@TheSavior, Does it mean, this PR is not acceptable?

**Comment by alloy** [comment]
If the API documentation doesn’t mention/recommend them—and I don’t see anything about such functions on the documentation page you linked to—then this PR is indeed not acceptable. Thanks for taking the time, though! 🙏

**Comment by amerllica** [comment]
Thanks to @TheSavior and @alloy 

This PR and its rejection is proof to many developers that using function styling is not a proper way, I always doubt it. thanks a lot. ❤️

**Pull request closed without merging**
