### PR TITLE
[types/smpte-timecode] Updated type of frameRate parameter

### PR DESCRIPTION
**Pull request by rakibhasan48**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/CrystalComputerCorp/smpte-timecode/blob/617c92e8f8de813e8fec0209725c12e562b83dfc/smpte-timecode.js#L8
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
If you update the tests ([smpte-timecode-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/smpte-timecode/smpte-timecode-tests.ts)), then this PR can get merged sooner 😊

**Comment by rakibhasan48** [comment]
> If you update the tests ([smpte-timecode-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/smpte-timecode/smpte-timecode-tests.ts)), then this PR can get merged sooner 😊

Added tests in [c8556a3](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69421/commits/c8556a3b5584d38f2e9768a3014353748da4f773)
Sorry, should've done that since the beginning.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/smpte-timecode/smpte-timecode-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bd1eef337ce232af05c384bf4a208ff6779f245f
</p>

**Review by Anonymous4078 — APPROVED** [review]

**Comment by rakibhasan48** [comment]
Ready to merge

**Pull request merged**
