### PR TITLE
fix type in zarinpal-checkout PaymentVerificationOutput RefId => refid as in the actual object

### PR DESCRIPTION
**Pull request by aliotadi**

### CODE REVIEW

**Comment by iamomiid** [comment]
@aliotadi 
Thanks for your PR.
I checked API documentation of Zarinpal [here](https://www.zarinpal.com/lab/) and `RefID` is still mentioned as the correct field
Can you confirm that it's changed?

**Comment by aliotadi** [comment]
> @aliotadi Thanks for your PR. I checked API documentation of Zarinpal [here](https://www.zarinpal.com/lab/) and `RefID` is still mentioned as the correct field Can you confirm that it's changed?

i'm using zarinpal in sandbox environment ant this is what i'm getting in the response object of provided type:
Screenshot 2024-11-06 184124

**Review by iisaduan — APPROVED** [review]
docs for change/[implementation](https://github.com/siamak/zarinpal-checkout/blob/f9ea07108ecd581c3e3ab7e0069c710c4c11164c/lib/zarinpal.js#L101)

Looks like the name changed from `RefID` to `refId` recently: https://github.com/siamak/zarinpal-checkout/commit/030911b53f5562b230eb52cb50cd1b4142e88aa8#diff-03731ceef658345d0e24bcd75ebb3844c1d842b14f011ba6a6f1d27f79689e4cL82

**Comment by iamomiid** [comment]
Ready to merge

**Pull request merged**
