### PR TITLE
Fixes Knex for ES6.

### PR DESCRIPTION
**Pull request by ryasmi**
Removed Bluebird Promises in favour of native Promises.

### CODE REVIEW

**Comment by ryansmith94** [comment]
knex/knex-tests.ts file needs updating I think

**Comment by vvakame** [comment]
You can do it!

**Comment by ryansmith94** [comment]
I'll give it a go @vvakame

**Comment by ryansmith94** [comment]
How's that @vvakame?

**Comment by tkqubo** [comment]
Thanks, it looks good to me! @ryansmith94

**Comment by horiuchi** [comment]
@ryansmith94 Thanks mate!
@tkqubo Thanks for review!

**Comment by ryansmith94** [comment]
No worries :-)

**Pull request merged**
