### PR TITLE
[babel__standalone] Use wildcards for scope path mappings

### PR DESCRIPTION
**Pull request by jablko**
#47089

### CODE REVIEW

**Review by matheus1lva — APPROVED** [review]

**Comment by sheetalkamat** [comment]
@jablko can you please batch the similar changes in one PR for about 10 packages instead of creating one for each package. This keeps the number of PRs in check and makes reviewing and merging easier. Thanks

**Comment by jablko** [comment]
@sheetalkamat So, the easiest for me would be to prepare a single PR with all the changes, like #47089 but with the few outstanding CI failures excluded. One PR per package [was requested](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42836#issuecomment-595508657) a while ago, and there have been [process/infrastructure changes](https://devblogs.microsoft.com/typescript/changes-to-how-we-manage-definitelytyped/) in the meantime. It's more work, but doable. Batches of about 10 packages is doable too.

Or, once these changes pass the CI, I think they're safe enough to merge without maintainer approval, which would remove the burden entirely? I've opened DefinitelyTyped/dt-mergebot#193 to explore that.

Thank you for merging so many of my PRs this week! I'm super grateful.

**Comment by sheetalkamat** [comment]
@jablko thank you for pointing to the [suggestion](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42836#issuecomment-595508657) While i agree with @sandersn in case there are code changes (.ts or test file changes) having PR per package is really good idea and preferred, changes in lint file or tsconfig only changes that adhere to our preferences like enabling strict or no rule disabling in dtslint file that dont require any change  to actual code or test are better to be batched especially if those are huge. I also understand that one PR would be ideal but i think we have some infra structure issues (last i remember) if done so. So middle ground of batching changes is ideal. I dont think we want to automate the bot for these as in the end we do want to ensure the change is correct and desired in lint or tsconfig. But i did ask and @andrewbranch has updated to not run benchmark suite for lint only change so that should be helpful in conserving machines as well. 

Appreciate your contribution in making things better.

**Comment by jablko** [comment]
@sheetalkamat Okay, I've marked #47089 ready for review to see if there are still problems with a single PR, or if the infrastructure issues have been addressed ...

**Pull request merged**
