### PR TITLE
update(webpack-dev-server): v4.3

### PR DESCRIPTION
**Pull request by lex111**
Also updates description for `magicHtml` server configuration option

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/webpack-dev-server/releases/tag/v4.3.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@lex111 thx!

note for owners: there seems to be wrong def for function factory here for 'headers', it should return a dictionary or a list, thx!

**Comment by lex111** [comment]
@peterblazejewicz thanks for pointing that out, decided to improve it as part of the current PR.

**Review by peterblazejewicz — APPROVED** [review]
LGMT!
@lex111 thx!

**Comment by lex111** [comment]
Ready to merge

**Pull request merged**
