### PR TITLE
[jest] improve expect spy matcher inference

### PR DESCRIPTION
**Pull request by CreativeTechGuy**
## Change summary

When expecting arguments or return types of spied methods, this change will infer the types to provide better auto-complete and errors if the types don't match.

This is backwards compatible except in the case where this identifies an issue that was not caught previously. This shouldn't break any expected behaviors but instead find issues which were missed.

## DefinitelyTyped PR Template

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A, just improving auto-complete for existing functionality
  * Other packages only had tests updated based on the new types (if their code would have ever been executed, it would have failed at runtime so it had always been a mistake).

### CODE REVIEW

**Comment by mrazauskas** [comment]
Interesting. Recently there was an attempt to add similar type inference in Jest repo. It had to be reverted, because of few problems, see https://github.com/facebook/jest/pull/13278

For instance, type inference did not work with function overloads (https://github.com/facebook/jest/issues/13337).

Also support of asymmetric matchers seemed to be complicated (https://github.com/facebook/jest/pull/13278#issuecomment-1251937905). (Note that `@types/jest` ignores the return type of asymmetric matchers. It is not `any`.) The return type was the general problem, more specific one was related with `expect.objectContaining` (https://github.com/facebook/jest/pull/13268#issuecomment-1262946721).

**Review by mrazauskas — CHANGES_REQUESTED** [review]
Could you add tests for cases which I mentioned, please?

The return type of asymmetric matcher is hard to reproduce here. Perhaps it could be casted for testing reasons. I mean, ideally it would be good to have the return type of asymmetric matchers reflect the reality. So this could cause a problem.

**Comment by CreativeTechGuy** [comment]
Thanks for the review @mrazauskas! I added tests for overloaded methods and this change works great with them!

I'm not sure what test you'd like me to write for asymmetric matchers. Since the most recent `@types/jest` release, the return type of every asymmetric matcher is now `any` so those will work just fine with these new types.

**Comment by mrazauskas** [comment]
The actual return type of asymmetric matcher can be seen [here](https://github.com/facebook/jest/blob/41bf2300895a2c00d0525d21260f0a392819871f/packages/expect/src/types.ts#L74-L79). I try to understand: if `@types/jest` would implement this type some day, how that would work with the change you are proposing.

I was trying it out this way:

```ts
type AsymmetricMatcher = {
  asymmetricMatch(other: unknown): boolean;
  toString(): string;
  getExpectedType?(): string;
  toAsymmetricMatcher?(): string;
};

expect(someSpy).toHaveReturnedWith({
  one: expect.stringContaining('a') as AsymmetricMatcher,
  two: expect.stringContaining('x') as AsymmetricMatcher,
});
```

With no luck:

Screenshot 2022-12-15 at 08 46 10

**Comment by CreativeTechGuy** [comment]
Ooh that's no good. I guess if/when that is added to `@types/jest`, we can update these types to contain `| AsymmetricMatcher`. I am not sure of another way to do it since that type is definitely incompatible.

It seems like Jest's types are in a really difficult place. There's so much potential for type safety in many places but due to a few edge cases everything must be `any`. If only there was a way to opt-in to stricter types at the cost of some things needing extra type assertions to work. I wonder if there's a potential for something like what [i18next did for their typescript](https://www.i18next.com/overview/typescript) support. You can extend an interface with module augmentation and their types will conditionally check if certain properties are present on that type and branch behavior based on that.

----

Is the AsymmetricMatcher issue a blocker? If so, is there anything we can do?

**Comment by mrazauskas** [comment]
I just took a look at function overloads. In the test you added we have type union, so I thought it would be good to look play with real overloads. Just a quick try, might be something is incorrect in my thinking:

```ts
interface Element {
    add(a: string): void;
    add(a: boolean): void;
}

declare const spiedElement: Element;

const elementSpy = jest.spyOn(spiedElement, 'add');

expect(elementSpy).toHaveBeenCalledWith('yes');
expect(elementSpy).toHaveBeenCalledWith(true);
```

VSCode shows me an error:

Screenshot 2022-12-15 at 13 10 11

Seems like to make this work, `.toHaveBeenCalledWith()` should be overloaded. But is that possible? Hm.. tricky.

**Comment by CreativeTechGuy** [comment]
Before we spend any more time on trying to improve this, let's see if it even has a chance of getting merged. From what I'm seeing, the Jest types are just getting looser not stricter.

What are all of the things that would need to be solved for this to actually get merged (and not reverted a week later)?

**Comment by mrazauskas** [comment]
What you mean by “Jest types are just getting looser not stricter”?

I think we should separate types of Jest APIs from type inference of actual and expected expressions. The APIs are strictly typed (with exception of `AsymmetricMatcher` here in `@types/jest`). But the actual and expected expressions are typed as `unknown` in Jest repo and as `any` here in `@types/jest`.  I see the reasons behind this after wrestling with https://github.com/facebook/jest/pull/13278#issuecomment-1251937905 (that is the `AsymmetricMatcher` problem mentioned above).

Probably there is no need to talk about the value of the API typings. For instance, using an IDE one can see the list of all matchers and pick one quickly using auto completion.

Knowing that expected must be of type `string` is not that useful. Because `'new'` and `'old'` are both strings, one will pass the test, other will fail. I think in this case `vscode-jest` does better job, than `tsc`. Both of them provide IDE with more or less immediate results in the context of a test file, but `vscode-jest` without competition will be more precise.

I understand that `vscode-jest` does not work with all editors, it might be too slow with e2e tests and there are other limitations. The idea here is that Jest is JavaScript testing tool. Static type is great thing, but in testing the execution of code creates the value. Also JavaScript allows us to use mocking. For simplicity one can replace an object with a string. The expected value will be correct for Jest, but TypeScript will complain. How to type that? `unknown` is just perfect, or?

These are few rough ideas and just one humble opinion (; 

For more see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62128

**Comment by CreativeTechGuy** [comment]
Okay given that, it sounds like this will never get merged and if so, it'll get quickly reverted.

For the record, the goal is not for TypeScript to replace the runtime checks, but to help against silly mistakes when writing the code for the first time. The perfect example is with complex nested objects, ensuring that you include all of the right fields with the right types.

While things _can_ accept `any` so technically it is correct, to me (and clearly many others) it's a red flag when something isn't attempting to be as strict as possible.

The only solution at this point seems to be an opt-in version [like I proposed here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63610#issuecomment-1352652528) which has the much stricter types. Then people who don't want that can just not opt-in and those who do see value in it can. Would that be accepted or should I just close the PR?

**Comment by mrazauskas** [comment]
Indeed this change could get reverted quickly. That is what I was trying to point to.

---

Regarding the proposed opt-in strict typed API. My first though was – it should have some documentation. Where it would live? Obviously Jest website sounds like a good place. It was referencing APIs of `@types/jest` before, but that is history. There is just tiny note on `@types/jest` left and the rest of TypeScript related documentation talks about Jest build-in types.

What I try to say – wouldn’t it make sense to implement the opt-in strict types in Jest repo first and reflect them here later? There is one more person interested in something similar: https://github.com/facebook/jest/issues/13334#issuecomment-1353944086

I mention this, because there is a long term plan to expose Jest build-in types through `@types/jest`. See #62037

---

Also I agree that for large objects typings are helpful. What about:

```ts
import { ComplexObject } from '../types';

expect(someMock).toHaveBeenCalledWith<ComplexObject>({
  // all typed here
});
```

For my eye that is more simple than additional `.d.ts` declaration.

**Comment by CreativeTechGuy** [comment]
Okay we can totally add the stricter opt-in types to `@jest/globals` if that's the future. Sounds good! Let me know how you would like me to proceed with that approach.

------

As far as explicitly giving the matchers a generic, there's a few problems with that:

* All types now need to be exported for this purpose even if otherwise they would have been private.
  * This is a bigger issue for 3rd party types which cannot be modified which then we'd need to try to extract the type from the variable and that can get messy fast.
* Since this isn't actually being checked against `someMock`, If the arguments change, then there'll be no TypeScript error to indicate that something is wrong here.
* The code is unnecessarily verbose
* It's easy to miss. Since the generic isn't required, a developer can easily just forget to add it and end up writing an incorrect value as a result. It'd be very hard to standardize across a project to ensure that every usage adds a generic.

True it'd be simpler from a `@types/jest` perspective, but then at that point, why even have generics at all and just force the users to use `satisfies` everywhere. I believe the value of TypeScript comes from being able to protect yourself and your fellow developers from human error. So a one-time opt-in works, but having to essentially opt-in on every single function call goes back to a high chance of human error.

**Comment by mrazauskas** [comment]
Don’t know how to proceed. Perhaps an RFC (or even PR) in Jest repo with some concrete API proposal could be good start?

I understand your thinking and the problem you see. At the same time I understand the reasons behind the shape of current typings. How to make both approaches work at the same time? How the API could look? Good question.

**Comment by CreativeTechGuy** [comment]
Thanks for the discussion. I'll see where some of the open PRs in the Jest repo turn out and go from there!

**Pull request closed without merging**
