### PR TITLE
Fixes lodash contains searching keys instead of values on objects

### LINKED ISSUE #4854: lodash _.contains() should search object values, not keys
According to the [docs](https://lodash.com/docs#includes), `contains` should search values of an object, not [keys](https://github.com/borisyankov/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L2205). The test for this is written correctly for the proper behavior, but coincidentally allows the incorrect behavior by providing a key that's a string. Also it should have the `includes` alias, currently it only has `contains` and `include` (actually, `contains` and `include` should be aliases for `includes`). I can submit a PR later today to fix, as well as a better test.

### PR DESCRIPTION
**Pull request by dbeckwith**
#4854

### CODE REVIEW

**Comment by dbeckwith** [comment]
Hmm, `sequelize` seems to have a [conflicting definition](https://github.com/borisyankov/DefinitelyTyped/blob/master/sequelize/sequelize.d.ts#L2706).
How should I get around that? The `includes` name should definitely belong to lodash.

**Comment by dbeckwith** [comment]
I guess if `includes` is already in lodash's type definition then it's okay if I just remove it from sequelize.

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to author(@bczengel). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by bczengel** [comment]
:+1:

**Comment by vvakame** [comment]
@bczengel thanks!
@dbeckwith thanks mate!
If you have a additional improvement, please send a pull request again. :wink:

**Pull request merged**
