### PR TITLE
Make React-Redux Connected Props Optional on Connected Components

### LINKED ISSUE #18795: React-Redux package doesn't correctly infer connected props as optional.
When using the current `react-redux` typings, any props specified by the `mapStateToProps`, `mapDispatchToProps`, or `mergeProps` parameters are not correctly removed from any component decorated by the result of the `connect` function. For example, all of the `Test*` lines should compile, but none of them do:

```
import * as React from "react";
import {connect} from "react-redux";

interface Props {
    a: boolean;
    b: string;
    c: () => void;
}

const Component = (props: Props) => <div />;

function mapStateToProps(state: any, props: Props) {
    return {
        a: true
    };
}

function mapDispatchToProps(dispatch: any, props: Props) {
    return {
        c: () => {}
    };
}

function mergedProps(props: any, dispatch: any, myProps: Props) {
    return {
        b: "",
        c: dispatch.c,
    };
}

const ConnectedA = connect(mapStateToProps)(Component);

const TestOptionalA = <ConnectedA b="" c={() => {}} />;

const ConnectedAC = connect(mapStateToProps, mapDispatchToProps)(Component);

const TestOptionalAC = <ConnectedAC b="" />;

const ConnectedMergedBC = connect(mapStateToProps, mapDispatchToProps, mergedProps)(Component);

const TestMergedBC = <ConnectedMergedBC a />;

```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Use 2.4 type machinery from Microsoft/Typescript#12215 to make all connected props optional and correctly infer prop types for connected components. Fixes #18795.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by thasner** [comment]
is this a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18510 ?

**Comment by jkoritzinsky** [comment]
Looks like it is.

**Comment by jkoritzinsky** [comment]
I added in some inference tests and fixes for `connectAdvanced` to work the same as `connect`, so there's a slight difference there but both PRs are fixing the same thing for `connect`.

**Comment by clayne11** [comment]
Please clean this up if you intend to have it merged. There's a lot of overlap with #18510.

**Review by clayne11 — CHANGES_REQUESTED** [review]
Lots of duplication with #18510. Please rebase off of `master` and use the definitions for `Diff` / `Omit` added in that PR if you still have changes you want to make.

**Pull request closed without merging**
