### PR TITLE
Missing dialogData

### PR DESCRIPTION
**Pull request by rasmuseeg**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

As mentioned here:
https://www.proworks.com/blog/archive/how-to-pass-data-to-the-umbraco-7-dialogservice-on-open/

And shown in the core here:
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/services/dialog.service.js#L92

### CODE REVIEW

**Comment by mhegazy** [comment]
there is a failing test, @rasmuseeg can you take a look.

**Comment by rasmuseeg** [comment]
Not sure what kind of test?

**Comment by mhegazy** [comment]
From travis CI log:

```txt
----------------- For file:umbraco/umbraco-tests.ts
umbraco/umbraco-tests.ts(22,20): error TS2345: Argument of type '{ template: string; iframe: boolean; callback: () => void; }' is not assignable to parameter of type 'IDialogRenderingOptions'.
  Property 'dialogData' is missing in type '{ template: string; iframe: boolean; callback: () => void; }'.
```

**Comment by rasmuseeg** [comment]
@mhegazy i think i fixed the issue. Can you take another look?

**Comment by mhegazy** [comment]
thanks!

**Pull request merged**
