### PR TITLE
[Antlr] Add and fix types for Antlr 4.11

### PR DESCRIPTION
**Pull request by Codex-**
## Rework the Antlr typings

Many were missing or no longer valid. The Antlr examples and documentation for the JS runtime are also in conflict with the current implementation, for example, a `Parser` consumes a `CommonTokenStream` and not an `InputStream` which is what the docs specify.

My strategy for completing these types:
- Use TypeScript to infer the types with `index` specifically as the entrypoint.
- Inspect existing typings and see what works, what doesn't, etc.
- Inspect the JS implementation.
- Inspect the Java implementation where types are difficult to infer from usage.

### Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
  - JavaScript runtime: https://github.com/antlr/antlr4/tree/master/runtime/JavaScript
    - Used to validate the implementation.
  - Java runtime:  https://github.com/antlr/antlr4/tree/master/runtime/Java
    - Used to validate the intended types (The JS runtime is just a direct port).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Codex-** [comment]
Apologies for dragging my heels with this, I got covid part way through and have been on the struggle bus 😭

**Comment by Codex-** [comment]
The `antlr4-autosuggest` typings relied on the old 4.8 typings exports but the package doesn't appear to be maintained anymore, I don't feel like the updates to those typings should be in this PR but the CICD required them to pass, thoughts?

**Comment by sandersn** [comment]
> The antlr4-autosuggest typings relied on the old 4.8 typings exports but the package doesn't appear to be maintained anymore, I don't feel like the updates to those typings should be in this PR but the CICD required them to pass, thoughts?

They probably aren't but they are still required to be updated. It might be OK to remove them before or after this PR since they *also* appear to be rarely used and it might be OK to stop updating them. But you'd have to clear it with the types maintainers.

(I'm going to leave this PR for a bit more to see if some maintainers will review it. Re-ping @jonfreedman @mcchatman8009 @tarilabs @jgellin-sf )

**Review by sandersn — APPROVED** [review]
Structure looks OK. After you merge this and it publishes, watch for complaints in the Discussions section.

**Comment by Codex-** [comment]
@sandersn thanks a lot for taking a look!

Just to double check before I trigger the bot to run, for changing the version is this the only change needed? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62582/files#diff-984db3169c8935ad7fb9af3080ee6a86f002b47c746e787be5510ca60bb36d83R1

Looks like it, but wanting to make triple sure :)

**Comment by sandersn** [comment]
yep, the DT publisher generates a package.json from the header line that you linked.

**Comment by Codex-** [comment]
Ready to merge

**Comment by JoeNemo** [comment]
This update fixed many problems and covers much more of ANTLR4 than the previous and I appreciate the work.  I found a few minor nits, but would like to start with just one.   If a class is mentioned in an API in a "*.d.ts", should that class itself be exported?   One example is ParseTree.   This class is used in many method prototypes, but is not itself exported.   Is this by design or a bug.   I added this locally and it fixed many issues?

**Comment by Codex-** [comment]
If you add an export that `antlr` does not export themselves then you'll run into issues, any exports I've added match what is currently being exported by `antlr`, so it'd be worth checking to see if they export it first before adding or removing any exports.

You can use `ReturnType<T>` to get the type, or you can `import type x from 'antlr/full/path` to get a specific type and use the type itself. There are quite a few ways to get these types, I also have a PR on the antlr repository to use named exports too

**Comment by JoeNemo** [comment]
in antlr4/tree/ParseTree.js it says

`export default class ParseTree extends SyntaxTree {
}
`
Is that what you mean?  I hope I am not referring to different branches/revs of Antlr4.   I apologize if I am being thick about what is considered "exported" by the Antlr4 maintainers.

**Comment by Codex-** [comment]
Not quite, these types are exports and used in peer files, however, that does not mean that `antlr` actually exports them.

To see what `antlr` actually exports, follow the trail starting from the `index`: https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/index.js

**Comment by JoeNemo** [comment]
I still don't know how to import ParseTree.   You said I could "import type x from 'antlr/full/path", but I am unclear on how to do this:
`import type ParseTree from 'antlr/tree/ParseTree';
`
does not seem to do the trick.   I have never used this workaround and am unclear on what you meant by "antlr/full/path".

**Comment by JoeNemo** [comment]
Also something seems deeply wrong in antlr if they export ParseTreeVisitor, which has the method 

`visit(tree: ParseTree): any;`

And yet don't export ParseTree.  There types exported should make a referential closure and not have dangling definitions.

**Comment by Codex-** [comment]
> I still don't know how to import ParseTree. You said I could "import type x from 'antlr/full/path", but I am unclear on how to do this: `import type ParseTree from 'antlr4/tree/ParseTree'; ` does not seem to do the trick. I have never used this workaround and am unclear on what you meant by "antlr/full/path".

Yeah `ParseTree` is not exported by `antlr`, but you can access the type:
```ts
import type ParseTree from 'antlr4/tree/ParseTree'
```

From what I can tell from antlr, they don't intend for you to use this directly though if that's something you're trying to do.

**Comment by JoeNemo** [comment]
I still cannot get that "import type..." to work for me.  You may have something different (i.e. better) in your tsconfig.json than I do.  I am on typescript 4.7.4 and have no 'types' or 'typeRoots' in my tsconfig.  But the the following hack works:

```
import { default as antlrTree } from "antlr4/tree";

type ParseTreeVistor_VisitMethod = antlrTree.ParseTreeVisitor["visit"];
type VisitMethodArgs = Parameters<ParseTreeVistor_VisitMethod>;
type ParseTree2 = VisitMethodArgs[0];
```

I admit its ugly, but it gets the type ParseTree2 to have exactly the type I want.  

In terms of theory, typescript must know all of the types of all the function args and return values that are exported in order to work.  And Parameters<> and ReturnType<> utility types allow you to access them, so there is effectively no hiding of ParseTree, anyway.   

I have been a user of the Java Runtime of Antlr for about 20 years.  ParseTree is "exported" (ie public) there.   I think that typescript can express the original intent of the antlr runtime better than JS can, and some things have just come out wonky.  But there is no native typescript runtime for Antlr.

Thanks for your help and attention.

**Comment by JoeNemo** [comment]
Also, I found I think a "real" and easy bug in antlr4/tree/Trees.d.ts:

`function getNodeText(t: Tree, ruleNames: string[], recog: Parser): string;`

The JS code in antlr/runtime/Trees.js has ruleNames and recog as optional:

```
    getNodeText: function(t, ruleNames, recog) {
        ruleNames = ruleNames || null;
        recog = recog || null;
        if(recog!==null) {
            ruleNames = recog.ruleNames;
        }
```

I would be glad to make the PR and fix it.

**Comment by Codex-** [comment]
> I still cannot get that "import type..." to work for me. You may have something different (i.e. better) in your tsconfig.json than I do. I am on typescript 4.7.4 and have no 'types' or 'typeRoots' in my tsconfig. 

`import type` has been in TS since 3.8: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

> I have been a user of the Java Runtime of Antlr for about 20 years. ParseTree is "exported" (ie public) there. I think that typescript can express the original intent of the antlr runtime better than JS can, and some things have just come out wonky. But there is no native typescript runtime for Antlr.

There is a WIP for antlr to support TS: https://github.com/antlr/antlr4/pull/3870

> Also, I found I think a "real" and easy bug in antlr4/tree/Trees.d.ts:
> 
> `function getNodeText(t: Tree, ruleNames: string[], recog: Parser): string;`
> 
> The JS code in antlr/runtime/Trees.js has ruleNames and recog as optional:
> 
> ```
>     getNodeText: function(t, ruleNames, recog) {
>         ruleNames = ruleNames || null;
>         recog = recog || null;
>         if(recog!==null) {
>             ruleNames = recog.ruleNames;
>         }
> ```
> 
> I would be glad to make the PR and fix it.

Good catch, get a PR up and I'm happy to take a look :)

**Comment by JoeNemo** [comment]
Here's the PR:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63466 

Only 4 characters changed!!

**Comment by ericvergnaud** [comment]
@JoeNemo @Codex- Gents, please note that [PR #4027](https://github.com/antlr/antlr4/pull/4027) addresses this need. Once it is released you may want to revisit this topic, since the npm package comes with the types.

**Pull request merged**
