### PR TITLE
[vis] added order property for TimelineGroup

### PR DESCRIPTION
**Pull request by avrahamcool**
currently missing from official docs.
awaiting merge https://github.com/almende/vis/pull/4091

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/almende/vis/pull/4091

### CODE REVIEW

**Review by adripanico — COMMENTED** [review]
That property doesn't belong to TimelineGroup: http://visjs.org/docs/timeline/#groups

There is currently a ```subgroupOrder``` that is intended for what you are looking for.

**Comment by avrahamcool** [comment]
@adripanico 
it actually is, its even in the docs [but not in the table]
image
thats why I commented in the PR that I also pushed another PR to the vis docs, to add it there as well.

you can check the `vis` source code, and also test it in an app to see that vis is taking `order` into considuration.

**Comment by adripanico** [comment]
The only thing I see there is a commented line. Have you explored the source code to check if this property is actually expected?

**Comment by avrahamcool** [comment]
the default value for `groupOrder` of an `ItemSet` is `order`.
so, specifying the `order` property on the groups will sort them via this property.
https://github.com/almende/vis/blob/5563fc616885578ad51b2dfa6ccf70ccebf06126/lib/timeline/component/ItemSet.js#L43

running the demo will show you that the groups are ordered via the `order` property. (and not by they inserted order).
removing the `order` property from the groups, or specifying a different property for `groupOrder`, will result in a different order.
proving that by default, `vis` is taking `order` into consideration as stated.

demo without any configuration: you can see that the groups are shown in the order they were inserted
http://jsfiddle.net/e7uodse2/2815/

demo with `order` set: you can see it's taken into consideration.
http://jsfiddle.net/e7uodse2/2812/

demo with `order` but specifying a different  `groupOrder` property: you can see that `order` is no longer taken into consideration:
http://jsfiddle.net/e7uodse2/2817/

**Comment by adripanico** [comment]
Alllllright

1) I was totally wrong with the ```subgroupOrder``` property. I have confused it with the ```order``` property of the timeline options :-1: 

1) You are totally right, the ```order``` property is intended for that and it is not properly documented on vis site.

But also:

2) If ```order``` is not provided, ```id``` is then used as sorter property (http://jsfiddle.net/sdtb162p/)

3) If ```groupOrder``` is provided with the options, the values of ```id``` and ```order``` are ignored (http://jsfiddle.net/3wjhtu8n/)

So, it is OK for me. I will approve your PR. Sorry for the inconveniences!

**Review by adripanico — APPROVED** [review]

**Pull request merged**
