### PR TITLE
[@types/hard-source-webpack-plugin] Add definition of plugins

### PR DESCRIPTION
**Pull request by Yama-Tomo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - source code:
    - https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/index.js#L570-L578
  - readme:
    - https://github.com/mzgoddard/hard-source-webpack-plugin#excludemoduleplugin
    - https://github.com/mzgoddard/hard-source-webpack-plugin#parallelmoduleplugin
  
- [ ] ~~Increase the version number in the header if appropriate.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by jessetrinity** [comment]
@woitechen

Any interest in this PR?

Thanks!

**Comment by jessetrinity** [comment]
@woitechen good question! Generally the guidance is to increase the major.minor version number of the types package to match the library. 

In this case it looks like the library is actually behind at 0.13 while these are at 1.0. It may be prudent to follow the guidance on [updating the major version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) to get them to match. Maybe @sandersn has an opinion on that?

**Comment by sandersn** [comment]
I don't think it's a good idea to move the version backward. Some of our update logic, at least, relies on versions increasing.

Since the version is already wrong, I think the best thing to do is just let the types publisher bump the patch number. The difference between 1.0.0 and 1.0.1 is arbitrary at this point.

**Comment by jessetrinity** [comment]
@woitechen I hope that answers your question!

If these changes look good to you, could you please approve the PR?

**Pull request merged**
