### PR TITLE
lodash: Add inRange, add dropWhile/takeWhile, fix drop/take

### PR DESCRIPTION
**Pull request by faithanalog**
drop and take only take a numeric parameter, dropWhile and takeWhile
are used for all other types of parameters. Additionally, takeWhile,
drop and dropWhile have been added to LoDashArrayWrapper

Signed-off-by: Unknownloner unknownloner.online@gmail.com

### CODE REVIEW

**Comment by unknownloner** [comment]
Tests need to be updated, standby

**Comment by unknownloner** [comment]
Alright, should be good now.

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to author(@bczengel). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by bczengel** [comment]
@unknownloner The definitions look good but first, take, takeWhile, rest, drop, and dropWhile are all different methods and require separate documentation.  You should only reference another method if its an alias.

@vvakame The definitions are correct so we can merge the PR unless you think we should wait for the documentation to be fixed.

**Comment by unknownloner** [comment]
I was simply copying the existing descriptions for the (improperly named)
methods, but I agree that the descriptions aren't 100% accurate. I can fix
them later this evening when I get home to better match the original
documentation.

**Comment by bczengel** [comment]
@unknownloner The previous version of lodash had take as an alias of first.  I believe they were separated in v3.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
