### PR TITLE
[react] Use HTMLDialogElement for the dialog node

### PR DESCRIPTION
**Pull request by ForbesLindesay**
The [HTMLDialogElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) accepts an `open` property, but I can't add it because the react typings think dialogs are just like all other HTML elements.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks for contributing @forbeslindesay!

Ping me when you've taken care of the build failure and I'll take a look.

**Comment by ForbesLindesay** [comment]
@johnnyreilly Is setting `TypeScript Version: 2.6` on all the dependencies an acceptable solution here?

**Comment by johnnyreilly** [comment]
I'm imagining that would handle all the `Error: alt depends on react but has a lower required TypeScript version.` messages.

It's fine from my perspective; it could be worth soliciting the feedback of other react definition contributor's to see what they say. But in the absence of significant objection it seems reasonable. 2.6 has been out for months.

**Comment by DovydasNavickas** [comment]
If it fixes the errors, it shouldn't break things too much. If someone is still using older than 2.6 TypeScript, they will be able to use fixed older version of types.

**Comment by ForbesLindesay** [comment]
@johnnyreilly that seems to have fixed the build.

**Review by joscha — APPROVED** [review]
Happy for this change to go into all the `storybook__*` and `enzyme-to-json` packages.

**Comment by johnnyreilly** [comment]
In the absence of objections I think we're good to go.  Merging.  Thanks for your work!

**Comment by jacobstern** [comment]
This change broke the build at my company this afternoon because we had `@types/react` pinned to the minor version, and are using version 2.4 of TypeScript. Is it expected for patch versions of type definitions to include major breaking changes?

**Comment by MartynasZilinskas** [comment]
@jacobstern types does not follow semver. I recommend pinning exact version.

**Comment by jacobstern** [comment]
@MartynasZilinskas Okay, good to know.

**Comment by johnnyreilly** [comment]
@jacobstern see https://blog.johnnyreilly.com/2017/02/typescript-types-and-repeatable-builds.html for details but the tl;dr is @MartynasZilinskas is correct

**Pull request merged**
