### PR TITLE
[tmi.js] remove specific typing for badges

### PR DESCRIPTION
**Pull request by crutchcorn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Could not find docs, see explanation below
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

While working with TMI.JS in my Twitch chat, I noticed that there were 2 badges that were missing from the `Badges` interface:

- `bits-leader`
- `sub-gifter`

I also suspect that there are many other badges that are missing as a result of poor documentation from Twitch.js themselves on just how many badges there are and what they reflect

However, while working with this API, I also discovered that it's relatively unpleasant to do string indexing on the object, as it's `const` typed (so I couldn't do `badges[string]` without type coercion). This seems like a fairly common use-case and is even utilized by `tmi.js` author, Alca, themselves in a codepen demonstrating the project:

https://codepen.io/Alca/pen/zzomog

(line 233)

While yes, this is less strict, it is more consumer-friendly and removes inaccuracies due to being overly strict

### CODE REVIEW

**Review by wpapsco — CHANGES_REQUESTED** [review]
I'd actually like to keep the baked-in badges so that users of the library can see at least some of the available badges in the completion. Though I do agree it shouldn't be limited the way it is right now. Maybe you can do something like:
```ts
export interface Badges {
    admin?: string;
    ...
    founder?: string;
    [other: string]: string;
}
```

I will definitely approve of a change like that, but if you think that's not a great idea please let me know your thoughts. It would also be great if you would add in some of the badges you know of that aren't already in the interface.

Best,
-wpapsco

**Comment by crutchcorn** [comment]
Changes have been made! Should be GTG

**Review by wpapsco — APPROVED** [review]
Looks great! Thanks for the contribution!

**Comment by crutchcorn** [comment]
Ready to merge

**Pull request merged**
