### PR TITLE
lodash: changed _.merge() method

### PR DESCRIPTION
**Pull request by chrootsu**
https://lodash.com/docs#merge
https://lodash.com/docs#_ (description of the chainable wrapper)

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors(@bczengel @chrootsu). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by chrootsu** [comment]
@bczengel ping

**Comment by bczengel** [comment]
:+1:

**Comment by chrootsu** [comment]
@bczengel thanks for the review )

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
