### PR TITLE
react-native-popup-dialog: PopupDialog show and dismiss methods typings

### PR DESCRIPTION
**Pull request by michelebombardi**
Added `show` and `dismiss` methods typings in `react-native-popup-dialog`  `PopupDialog` class.
Updated _Definitions by_ and version to 1.0.

### CODE REVIEW

**Comment by PaitoAnderson** [comment]
@bm-software mind updating [react-native-popup-dialog-tests.tsx](/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-popup-dialog/react-native-popup-dialog-tests.tsx) to include show/dismiss being used?

**Review by PaitoAnderson — CHANGES_REQUESTED** [review]
Requested tests be updated.

**Comment by bm-software** [comment]
@PaitoAnderson Hi, I've updated `react-native-popup-dialog-tests.tsx` as requested. Sorry for the forgetfulness.

**Review by PaitoAnderson — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
