### PR TITLE
[jquery] Define type for JQueryStatic.fn

### LINKED ISSUE #12685: Fix the declaration of JQueryStatic.fn
- [x] I want to talk about `jquery/jquery.d.ts`.
  - The authors of that type definition are cc/ @borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @jameshfisher @seikichi @benjaminjackman  @JoshStrobl @johnnyreilly @DickvdBrink

- [x] I want to talk about `jquery.dataTables/jquery.dataTables.d.ts`.
  - The authors of that type definition are cc/ @Silver-Connection @omidkrad @pragmatrix @CNBoland 
---
The static property`JQueryStatic.fn` (AKA `jQuery.fn` or `$.fn`) is declared as `any` which makes it impossible for plugin authors to write proper type declarations.

An example of such a plugin is the DataTables plugin, which has a handful of static functions that you can access via `$.fn.dataTables`.

In jquery/jquery.d.ts
```ts
fn: any;  //TODO: Decide how we want to type this
```

In jquery.dataTables/jquery.dataTables.d.ts
```ts
//TODO: Wrong, as jquery.d.ts has no interface for fn
//interface JQueryStatic {
//    dataTable: DataTables.StaticFunctions;
//}
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L966
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.dataTables/jquery.dataTables.d.ts#L17-L20

Example: https://datatables.net/reference/api/$.fn.dataTable.tables()
```ts
// get all DataTables on the page.
let tables: DataTables.DataTable[] = $.fn.dataTables.tables() as DataTables.DataTable[];
```

Here, the inferred return type of `tables()` is `any` because the type of `fn` is `any`, but the actual return type is an array of `DataTable`.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12685#issuecomment-304383623
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

Depends on
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16742~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16760~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16762~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16763~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16764~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16765~~
- ~~https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16767~~

Fixes #12685.

### CODE REVIEW

**Comment by leonard-thieu** [comment]
Only significant change is on jquery-match-height.

---

*types/jquery-match-height/index.d.ts*

to author (@kbytesys). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by leonard-thieu** [comment]
:tada:

**Comment by kbytesys** [comment]
👍

**Comment by johnnyreilly** [comment]
Thanks!

**Pull request merged**
