### PR TITLE
Create kcors definitions

### PR DESCRIPTION
**Pull request by Xstoudi**

### CODE REVIEW

**Comment by Xstoudi** [comment]
Help needed, don't understand what's wrong.

**Comment by andy-ms** [comment]
There was a pull request template. Follow the advice there.

**Comment by Xstoudi** [comment]
I added tslint.json, the only things I saw missing.
I actually don't understand the remaining error :
Travis errors

**Comment by andy-ms** [comment]
Just rebase to `master` which doesn't have that error. It's being fixed by #13399.

**Comment by Xstoudi** [comment]
Don't know how to do this. Specially don't know how to rebase my fork on the original repository.
Do what you want with the defs.

**Comment by andy-ms** [comment]
FYI, `git pull --rebase upstream master` usually works.

**Pull request closed without merging**
