### PR TITLE
nodemailer 4.1.3

### PR DESCRIPTION
**Pull request by dex4er**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by dex4er** [comment]
All other nodemailer-plugins will be removed

**Comment by dex4er** [comment]
@rogierschouten please review...

**Comment by dex4er** [comment]
@otociulis please review for nodemailer-mailgun-transport

**Comment by andy-ms** [comment]
Could you clarify why all the plugins should be deleted? `npm info nodemailer-stub-transport` doesn't show it as providing its own types or having been deprecated.

**Comment by dex4er** [comment]
@andy-ms they're all obsoleted by new Nodemailer. See https://www.npmjs.com/package/nodemailer-stub-transport and go to the repository: github.com/andris9/nodemailer-stub-transport

It is empty now because it is not supported by new Nodemailer.

The Nodemailer 4.x is written now in ES6 and have new APIs and bundles most of plugins and more libraries, ie. mail-composer, mime-node and smtp-connection has been separate modules and now they're a part of Nodemailer framework.

**Comment by andy-ms** [comment]
OK. It looks like it was downloaded 4000 times in the last day, so I'm not sure about deprecating it just yet, but we could remove it from DefinitelyTyped.
These shouldn't go in `notNeededPackages.json` though as that is for packages that provide their own types.

**Comment by dex4er** [comment]
Howto document was not clear what should I do in this situation. I can remove it from `notNeededPackages.json` but then my `npm test` just fails badly:

```
> definitely-typed@0.0.1 test /home/dexter/src/js/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed

Clean data
Clean logs
Clean output
# Typing Publish Report Summary
Started at Tue, 17 Oct 2017 15:22:08 GMT
Found 3824 typings folders in /home/dexter/src/js/DefinitelyTyped/types
{ Error: ENOENT: no such file or directory, open '/home/dexter/src/js/DefinitelyTyped/types/nodemailer-ses-transport/index.d.ts'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/dexter/src/js/DefinitelyTyped/types/nodemailer-ses-transport/index.d.ts' }
npm ERR! Test failed.  See above for more details.
```

What can I do?

**Comment by andy-ms** [comment]
I think you just need to remove that directory locally.

**Comment by dex4er** [comment]
@andy-ms so I moved old v3 typings to new directory and I restored other plugin directories and now I thing I've found some error in types-publisher because nodemailer/v3 depends on nodemailer-smtp-transport and they have correct and the same path mapping, but `npm test` reports:

```
Error: nodemailer v3 depends on nodemailer-direct-transport, which has a path mapping for nodemailer v3. nodemailer v3 must have the same path mappings as its dependencies.
```

I think it is because in `/types-publisher/data/definitions.json` path mappings are cleared for the main package even if it is not main version of this package.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
