### PR TITLE
TypeScript-STL v1.2.4

### PR DESCRIPTION
**Pull request by samchon**
IComparable has changed:
  - `IComparable.equal_to` -> `IComparable.equals`
  - `IComparable.hash` -> `IComparable.hashCode?`

```typescript
namespace std
{
    export interface IComparable<T>
    {
        less(obj: T): boolean;
        equals(obj: T): boolean;
        hashCode?(): number;
    }
}
```

### CODE REVIEW

**Comment by samchon** [comment]
@dt-bot I'm the origin author.

My answer is 👍

**Comment by andy-ms** [comment]
`typescript-stl` [bundles](https://github.com/samchon/typescript-stl/blob/master/lib/typescript-stl.d.ts) typings. Since people can just install `typescript-stl` and get typings from there, can we deprecate `@types/typescript-stl`?

**Comment by samchon** [comment]
@andy-ms I do not want the deprecation.

Bundling the `d.ts` file is not omnipotent. Some people may install the `typescript-stl` with global option. In that case, the bundled `d.ts` is not effective. Some independent `d.ts` should be provided. It's the reason why I'm publishing this PR on the `@types`

```bash
npm install -g typescript-stl
npm install --save @types/typescript-stl
```

**Comment by samchon** [comment]
@andy-ms Please do not forget my PR. I'm waiting for your answer.

**Comment by andy-ms** [comment]
I'll merge this anyway. But I don't understand your reasoning since people will still need to install a package locally, and there's no guarantee that they're installing a version in sync with their global installation.

**Pull request merged**
