### PR TITLE
[ramda] split tests into one module per ramda function

### PR DESCRIPTION
**Pull request by devrelm**
This is an alternative to #37636 which just splits the `ramda-tests.ts` file and adds a `README.md` to guide contributors towards writing tests for the `@types/ramda` package.

Unlike #37636, no changes were made to `types/ramda/index.d.ts`, and no assertions were added to the tests. The only thing this PR does is split out the tests for each function into a separate file for each function.

The added readme lays one ground rule for the tests: that each test file should only contain tests where the outermost function called is the one which shares the name of the file. For instance, the following:

```ts
R.pipe(
  R.add(2),
  R.add(3),
  R.add(4),
);
```

tests `R.pipe`, _not_ `R.add`. So it belongs in `test/pipe-tests.ts` rather than `test/add-tests.ts`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] ~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- [ ] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by pirix-gh** [comment]
@devrelm could you run the tests locally before pushing?

And thanks for the massive cleanup you're doing :tada:

**Comment by devrelm** [comment]
Sure thing! I ran `yarn lint ramda` but I guess the CI server goes a bit further.

I'll check out what's going wrong and get it fixed up later tonight. Cheers!

**Comment by pirix-gh** [comment]
@devrelm, run `npm test` (`yarn test`) in the base directory. The dt script will then test your changes. This is what the CI does.

**Comment by devrelm** [comment]
@pirix-gh I've fixed the errors and it looks like everything's passed

**Comment by pirix-gh** [comment]
@devrelm I would love to see this merged... But I just can't find the time to check it all. I would love to blindly merge it and hope that everything still works the same. However, I am scared of the human error factor. I don't say that you've made mistakes, we all do. I'd have trusted a script more because, like I said, I don't have the time to review everything.

**Comment by devrelm** [comment]
That's completely fair. ~7000 lines is a lot to review in one go. I get upset with coworkers when they give me PRs with >200 lines changed 😅 

All I can say to ease fears is:
1) I didn't touch `index.d.ts`, so there at least won't be any regressions in the library itself. Depending on how the [`types-publisher`](https://github.com/Microsoft/types-publisher) works, there shouldn't even be a new version created. It's one of the reasons that I didn't yet add myself to the list of contributors — I didn't want to cause a version bump when there aren't any actual changes to the types themselves.
2) As far as the possibility that I accidentally removed some tests, I tried my best not to let that happen, but I wouldn't be too worried if I did. The tests themselves are currently in pretty poor shape. Few of them assert the types in any meaningful way, so any accidentally-removed tests probably won't be missed. The point of this PR is to highlight that fact and set us up with a more-organized test suite so that we can focus on writing meaningful tests and reducing the number of breaking changes going forward.

**Comment by devrelm** [comment]
closing -- preferring smaller PRs

**Pull request closed without merging**
