### PR TITLE
Update type to include OnDragStart OnDragEnter OnDrop

### PR DESCRIPTION
**Pull request by tquinlan1992**
Was following this example and converting to typescript https://github.com/react-component/tree/blob/master/examples/draggable.js

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Looking to add onDrag Types
https://github.com/react-component/tree/blob/master/README.md

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
Would you be able to provide the parameter information as well please? It's detailed here: https://github.com/react-component/tree/blob/master/README.md

It'd be nice to be more specific than just `Function`

**Comment by tquinlan1992** [comment]
Yup, I'll update it.  looks like that's why the Travic CI build failed as well. @johnnyreilly

**Comment by johnnyreilly** [comment]
Looks good!  Could you add tests for the new bits please?

**Comment by tquinlan1992** [comment]
I'll add test as well!  Will look into how they're performed on the other types

**Comment by mhegazy** [comment]
@tquinlan1992 The Travis CI build failed! Please review the logs for more information. Once you've pushed the fixes, the build will automatically re-run. Thanks!

**Comment by andy-ms** [comment]
Merged with a fix.

**Pull request merged**
