### PR TITLE
[webpack] fix AggressiveMergingPlugin

### PR DESCRIPTION
**Pull request by bumbleblym**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://webpack.github.io/docs/list-of-plugins.html#aggressivemergingplugin
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
@bumbleblym Could you resolve the merge conflicts please? Thanks.

**Comment by bumbleblym** [comment]
@minestarks the sole lint error will be resolved by #15058

**Comment by minestarks** [comment]
@bumbleblym I merged #15058 - could you merge from master? When the tests run clean I'll merge. Sorry for the trouble...

**Comment by bumbleblym** [comment]
@minestarks ready to merge

**Pull request merged**
