### PR TITLE
Fix issues in @vimeo/player types

### PR DESCRIPTION
**Pull request by remcohaszing**
This fixes two issues in the type definitions for `@vimeo/player`.

Firstly, the main export of `@vimeo/player` uses `module.exports =`. This means the correct way to write type definitions, is using `export =`. A namespace was used to export additional types.

Secondly, the package loads `native-promise-only`, and returns native promises. Before this change, there was a special promise type `VimeoPromise` that has a call expression, but this call expression doesn’t exist at runtime. This has been replaced with native `Promise` return values.

There were some specific error types that were used in conjunction with `VimeoPromise`. These errors have been removed. The package does document a specific error type that has a `method` property. This is unused by the type definitions, but it’s kept so users can use it for custom checks.

Also the minor version has been updated.

Hint for the reviewer: A lot of indentation changed due to the namespace, hide whitespace changes.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/vimeo/player.js/blob/master/src/player.js#L4, https://github.com/vimeo/player.js/blob/master/dist/player.js#L3
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
I think the more proper fix would be to follow UMD pattern:
```ts
declare namespace Vimeo {
    type TrackKind = 'captions' | 'subtitles';
    ...
}

export as namespace Vimeo;

export = Vimeo.Player;
```
as per:
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library
https://github.com/vimeo/player.js/blob/master/dist/player.js

also as the change could impact existing code users (different export, requiring `esModuleInterop` config, etc), this would be best to get some owners input here

**Comment by remcohaszing** [comment]
Thanks for the feedback! You’re absolutely correct. I applied your suggestions, but I added the type exports in the namespace `Vimeo.Player`. That way they are still accessible from modules, even with the same syntax as before.

If you are really concerned about how this change might impact existing code, I could add a static property `default`. However, this is technically incorrect, and if this affects any users, it’s because they didn’t configure TypeScript correctly.

Also I’m hesitant to mention `esModuleInterop`, as that tends to lead to bugs. Consumers of this library probably use a bundler and should use `allowSyntheticDefaultImports`.

I would love to get owners’ input, but they’re not responding despite the @typescript-bot pings. I don’t know any of them.

**Comment by peterblazejewicz** [comment]
Let's give the owners a second chance, ping me before this stales

**Comment by sandersn** [comment]
I agree, can the current owners @denisyilmaz, @timc13, @terrymun, @kou029w, @mikeamarkey OK this? 
Switching the export may be more correct, but might break existing users without esModuleInterop, for example. Still probably the right thing.

**Comment by terrymun** [comment]
@sandersn My only comment is, if we will introduce a breaking change, we might want to look into ensuring that a major version bump for this?

**Comment by remcohaszing** [comment]
The version must match that of `@vimeo/player`. It can be made non-breaking by adding a static property `default` of type `Player`. Personally I'd rather not, as it's technically incorrect.

**Comment by terrymun** [comment]
If we cannot make a major version bump, then we need some mitigation strategies so that a minor/patch version bump does not break the the typing for users that does not have `esModuleInterop` enabled.

**Review by RyanCavanaugh — APPROVED** [review]
I'm OK with this. DT packages follow the version of the modules they typed; if the previous module format was wrong, then it's a bugfix to correct it.

**Comment by remcohaszing** [comment]
Note that I did restore the default export. Although I personally also think it's best to remove it.

**Comment by remcohaszing** [comment]
Ready to merge

**Pull request merged**
