### PR TITLE
React: support AnchorHTMLAttribute Target

### PR DESCRIPTION
**Pull request by shevchenkonik**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
The docs mention that these values have a specific meaning but they don't state that `target` is an enumerated attribute (like [`type` for `button`](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type)) i.e. it only allows the listed values.

Could you find out if `target` is indeed an enumerated attribute?

**Comment by shevchenkonik** [comment]
> The docs mention that these values have a specific meaning but they don't state that `target` is an enumerated attribute (like [`type` for `button`](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type)) i.e. it only allows the listed values.
> 
> Could you find out if `target` is indeed an enumerated attribute?

@eps1lon

I found two docs –– [rule](https://html.spec.whatwg.org/multipage/semantics.html#attr-base-target) and [browsing context names](https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword).

> A **valid browsing context name** or keyword is any string that is either a valid browsing context name or that is an ASCII case-insensitive match **for one of: _blank, _self, _parent, or _top.**

**Comment by eps1lon** [comment]
> I found two docs –– rule and browsing context names.

These apply to the `<base>` element not `<a>` as far as I can tell.

**Comment by shevchenkonik** [comment]
> > I found two docs –– rule and browsing context names.
> 
> These apply to the `<base>` element not `<a>` as far as I can tell.

But we have a link to [this documentation](https://html.spec.whatwg.org/multipage/links.html#links-created-by-a-and-area-elements) from those pages as specific docs about `a` 🙂

**Comment by shevchenkonik** [comment]
It's ok (progress > 2h)? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47002/checks?check_run_id=1021414216

**Comment by hellatan** [comment]
Here's a list of enumerated values for anchor tags - https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword (linked from @shevchenkonik's last comment) though it does seem to accept an empty string as a value.

**Comment by shevchenkonik** [comment]
Based on https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword I found new info.

The best way would be to create `target?: string | '_self' | '_blank' | '_parent' | '_top'` or just keep `target?: string`?

Thanks @hellatan

**Pull request closed without merging**
