### PR TITLE
feat(sinon): Make stub factory method optionally generic

### PR DESCRIPTION
**Pull request by nicojs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://sinonjs.org/releases/v7.2.2/stubs/
- [x] Increase the version number in the header if appropriate.
(not appropriate)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nicojs** [comment]
Can someone help with this PR. Build is failing because if this line: `<TArgs extends any[]= any[], R = any>(): SinonStub<TArgs, R>;`. As `TArgs` and `R` are only used once. See https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md.

This would mean that this cannot work:

```
interface Foo {
   bar(baz: string): void
}

const logMock: sinon.SinonStubbedInstance<Foo >;
logMock = {
  bar: sinon.stub(); 
  // => should be bar: sinon.stub() as SinonStub<[string], void>;
}
});
```

I feel like forcing everyone to cast is pretty unhelpful.

**Comment by nicojs** [comment]
@andy-ms what is your take on this? I mostly agree  with your article except for this part:

> **Bad:**
> 
> ```ts
> function parse<T>(): T;
> const x = parse<number>();
> ```
> 
> **Good:**
> 
> ```ts
> function parse(): {};
> const x = parse() as number;
> ```
```

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by DanTup** [comment]
Are there any docs on how to use this? I'm seeing errors after upgrading my Sinon types that I think may be related to this change - can anyone here advise how it's supposed to work (and whether this was expected to be breaking)?

My code looks like this:

```ts
const showInformationMessage = sb.stub(vs.window, "showInformationMessage");
showInformationMessage.withArgs(sinon.match.any, "TEST").resolves(stopLogging.promise);
```

The `showInformationMessage` method has overloads that look like this:

screenshot 2019-01-30 at 12 10 22 pm

I'm using the top overload, however after upgrading I got this error:

> Argument of type "TEST" is not assignable to parameter of type 'MessageOptions | SinonMatcher'."

So I changed the code to use `string` instead of `any` and wrap the string arg with `sinon.match()` like this:

```ts
const showInformationMessage = sb.stub(vs.window, "showInformationMessage");
showInformationMessage.withArgs(sinon.match.string, sinon.match(["TEST"])).resolves(stopLogging.promise);
```

However now it complains that the return value is expected to be `never`:

> Argument of type 'Promise<undefined>' is not assignable to parameter of type 'never'.

I tried `"TEST"` both on its own and as an array but same error. I presume it's not matching the overload correctly, but I can't figure out how to make it.

**Comment by DanTup** [comment]
Rolling back Sinon (but keeping updated TypeScript) also has issues:

screenshot 2019-01-30 at 12 35 10 pm

I'm just gonna roll them both back for now :(

**Comment by DanTup** [comment]
> It probably works with older sinon because it has less precise types?

I think so - the older one showed `any` when I hovered over it.

Is there any way around this? It'll be a shame if anyone stubbing overloads has to stick on an old version :(

**Comment by weswigham** [comment]
I think adding the `any` overloads back to the declaration file (below the more precise ones) would work OK. It'd allow you to match incorrect parameter types though, unfortunately.

**Comment by mykwillis** [comment]
It appears this is still a problem using latest sinon (8.1.1.). I'm not sure how to interpret @weswigham 's comment above ("I think adding the any overloads back to the declaration file (below the more precise ones) would work OK. ")

Are you implying that there is a workaround I can implement locally to fix this issue? In my particular case I am attempting to update dependencies for a project that has a testcase stubbing (one overload of) a mongoose Model's `fineOne` method:

```
const User = mongoose.model<IUser>('User', {...});
const userStub = sinon.stub(User, 'findOne');

// TS2554: Expected 3-4 arguments, but got 1.
userStub.withArgs({ firebaseUid: readOnlyUserFirebaseUid })
      .resolves(readOnlyUser);

```
// from @types/mongoose:
```
    findOne(conditions?: any,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T> & QueryHelpers;
    findOne(conditions: any, projection: any,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T> & QueryHelpers;
    findOne(conditions: any, projection: any, options: any,
      callback?: (err: any, res: T | null) => void): DocumentQuery<T | null, T> & QueryHelpers;
```

**Pull request merged**
