### PR TITLE
add react-panelgroups missing callbacks

### PR DESCRIPTION
**Pull request by Yolonaise**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (https://github.com/DanFessler/react-panelgroup/blob/master/src/PanelGroup.js#L28-L29)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Review by MysteryBlokHed — CHANGES_REQUESTED** [review]
Wait—correct me if I’m wrong, but doesn’t this pass only an array?

<https://github.com/DanFessler/react-panelgroup/blob/52b62222e5d1a6b27d4592d7f6026cf0d24d11de/src/PanelGroup.js#L144>

**Comment by Yolonaise** [comment]
> Wait—correct me if I’m wrong, but doesn’t this pass only an array?
> 
> https://github.com/DanFessler/react-panelgroup/blob/52b62222e5d1a6b27d4592d7f6026cf0d24d11de/src/PanelGroup.js#L144

I think so, panels is an array of PanelWidth. 
And according to this [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), when we slice an array wihtout params, it returns an array. 

To confirm that, I've made a little project to test params of the new callbacks: https://stackblitz.com/edit/react-ot8xm4?file=src%2FApp.js.

**Comment by Yolonaise** [comment]
> Wait—correct me if I’m wrong, but doesn’t this pass only an array?
> 
> https://github.com/DanFessler/react-panelgroup/blob/52b62222e5d1a6b27d4592d7f6026cf0d24d11de/src/PanelGroup.js#L144

Nice catch

**Comment by ThibautMarechal** [comment]
The `onUpdate` props is also wrong then. It should also passs an array

**Review by ThibautMarechal — APPROVED** [review]

**Comment by Yolonaise** [comment]
Ready to merge

**Pull request merged**
