### PR TITLE
pull request for new MaskedInput and JQuery JqGrid

### PR DESCRIPTION
**Pull request by lokeshpeta**
missing reference in underscore.stiring.d.ts
using Interface in Noty.d.ts

### CODE REVIEW

**Comment by vvakame** [comment]
@lokeshpeta thank you your contributions.
please rename jquery.jqgrid/jquery.jqgrid.d.ts to jqGrid/jqGrid.d.ts.
http://definitelytyped.org/guides/contributing.html#naming-the-file

please split PR per library at the next.

**Comment by lokeshpeta** [comment]
@vvakame Thanks very much for the review. As requested, I have changed the file and folder names.

**Comment by vvakame** [comment]
@lokeshpeta thanks mate!

**Comment by lokeshpeta** [comment]
@vvakame Thanks very much !

**Pull request merged**
