### PR TITLE
styled-components: Enable 'as' and 'forwardedAs' props to be linted

### PR DESCRIPTION
**Pull request by JoSuzuki**
When passing a component or an html tag in `as` or `forwardedAs` the props of this component should appear and be allowed in the base component.

For example consider the following situation:
```
const Button = styled.button``;
const WrappedButton = styled(Button)``;

const HomeLink = () => <Button as="a" href="/home">Home</Button>;
const BlogLink = () => <WrappedButton forwardedAs="a" href="/blog">Blog</Button>;
```

Both situations should allow the prop `href` to be passed. 

This is related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50404
This enhances the behavior of PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49239, which was also the origin of the issue pointed above.

The inference of props is working for html tags and React.FC (or similar), I couldn't get the inference of required props of styled-components to work.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://styled-components.com/docs/api#forwardedas-prop

### CODE REVIEW

**Comment by JoSuzuki** [comment]
> @JoSuzuki, I'm making it possible to merge, but it would be good if you can get anything from the owners before doing so.
> 
> (Ping @Igorbek, @Igmat, @lavoaster, @Jessidhia, @jkillian, @eps1lon, @flavordaaave, @wagerfield, @Lazyuki, @mgoszcz2, @danilofuchs.)

Thanks @elibarzilay, I'm going to wait for feedback from one of the owners.

**Comment by JoSuzuki** [comment]
Is there something that I can do to help this PR getting reviewed?

**Comment by JoSuzuki** [comment]
Ready to merge

**Comment by ahoisl** [comment]
@JoSuzuki It seems this change broke typing for generic styled components, see this issue and my comment including a very small sandbox example:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136#issuecomment-858085061

I would be very grateful if this can be fixed soon, upgrading breaks the code for generic components and makes generics even harder to use with styled components...

**Comment by JoSuzuki** [comment]
> @JoSuzuki It seems this change broke typing for generic styled components, see this issue and my comment including a very small sandbox example:
> [#39136 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136#issuecomment-858085061)
> 
> I would be very grateful if this can be fixed soon, upgrading breaks the code for generic components and makes generics even harder to use with styled components...
> I would love to provide a PR myself, but I cannot get my head around the typings you changed, sorry 😄

Oh, I will see what I can do, I'm not the best with typing too 😅, thanks for the sandbox it helps a lot!

**Comment by JoSuzuki** [comment]
AHA, I think I got it! Will try to open a PR soon enough.

The problem was with the inference of a function overload, when you specify the generic it assumes it should be the overload with generics (even though, at this time the one with generics should be used only when it passes the `as` or the `forwardedAs` props), I think adding an overload to allow an `SpecificC` to be passed should solve it!

```diff
export interface StyledComponentBase<
    C extends string | React.ComponentType<any>,
    T extends object,
    O extends object = {},
    A extends keyof any = never
 > extends ForwardRefExoticBase<StyledComponentProps<C, T, O, A>> {
    // add our own fake call signature to implement the polymorphic 'as' prop
    (props: StyledComponentProps<C, T, O, A> & { as?: never; forwardedAs?: never }): React.ReactElement<
        StyledComponentProps<C, T, O, A>
    >;
+    <SpecifiedC extends string | React.ComponentType<any> = C>(props: StyledComponentProps<SpecifiedC, T, O, A> & { as?: never; forwardedAs?: never }): React.ReactElement<
+        StyledComponentProps<SpecifiedC, T, O, A>
+    >;
    <AsC extends string | React.ComponentType<any> = C, FAsC extends string | React.ComponentType<any> = C>(
        props: StyledComponentPropsWithAs<C, T, O, A, AsC, FAsC>,
    ): React.ReactElement<StyledComponentPropsWithAs<C, T, O, A, AsC, FAsC>>;

}

```

**Pull request merged**
