### PR TITLE
Lil.gui

### PR DESCRIPTION
**Pull request by maxwell60701**
feats:add lil.gui

### CODE REVIEW

**Comment by georgealways** [comment]
Hi there, could you help me understand why we need this? The lil-gui package on npm is already published with a TS definition file.

**Comment by maxwell60701** [comment]
> Hi there, could you help me understand why we need this? The lil-gui package on npm is already published with a TS definition file.

Hi,Author,i could not find lil.gui in types file

**Comment by georgealways** [comment]
Hey—might just be a typo, it's `lil-gui` not `lil.gui`. If you've got the library installed locally you should see TS integration automatically.

**Comment by georgealways** [comment]
Right, but as I understand it, this project is for libraries that don't provide TS definitions, and lil-gui [already does](https://cdn.jsdelivr.net/npm/lil-gui@0.17.0/dist/lil-gui.esm.d.ts). VSCode does type validation with lil-gui out of the box:

 
Screen Shot 2022-07-20 at 12 17 23 PM

**Comment by MysteryBlokHed** [comment]
As @georgealways said, lil-gui includes its own types:
npm screenshot of lil-gui, showing TypeScript badge

**Pull request closed without merging**
