### PR TITLE
Add missing types for Component.month

### PR DESCRIPTION
**Pull request by decimoseptimo**

### CODE REVIEW

**Comment by marknelissen** [comment]
@decimoseptimo , please explain the origin of the modifications. I don't find references to these properties in the documentation: https://jquense.github.io/react-big-calendar/examples/index.html#api

**Comment by decimoseptimo** [comment]
Hi @marknelissen, following up...

`EventProps`
The components prop https://jquense.github.io/react-big-calendar/examples/index.html#prop-components
Which I have implemented in my tests https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55439/files#diff-572b321f6d26c6b3a3b77eee45a32b0ecbf918f02de21a9b0c322988435e0db8R476
Has an event key which receives a componentType with EventProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1771bd64eb2d23ade6477ac08838a75229640b3b/types/react-big-calendar/index.d.ts#L204
We can see that on BigCalendar, the Event component receives additional props to the ones defined at EventProps https://github.com/jquense/react-big-calendar/blob/master/src/EventCell.js#L44

`DateLocalizer`
This is more complicated, I followed it, I think it starts around here https://github.com/jquense/react-big-calendar/blob/d695d0a51143f83f3ecda35044e53c28d7d39a2a/src/Calendar.js#L866

**Review by marknelissen — APPROVED** [review]

**Comment by decimoseptimo** [comment]
I think this is it, looking forward to the review.

**Review by marknelissen — APPROVED** [review]

**Comment by decimoseptimo** [comment]
Ready to merge

**Pull request merged**
