### PR TITLE
[express] Update "@types/express" dependency "@types/express-serve-static-core": "^4.17.33"

### PR DESCRIPTION
**Pull request by bombillazo**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This is related to #63006, updating the required new `@types/express-serve-static-core` version.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## express ([<kbd>unpkg</kbd>](https://unpkg.com/browse/express@latest/))
was missing the following properties:
1. Route
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 884ee4366d9412e320fed4859f6881cdf2f62202
</p>

**Comment by bombillazo** [comment]
Any update on this PR?

**Comment by bombillazo** [comment]
Hey @borisyankov @puneetar @dfrankland, a quick review would be appreciated, no complex change here, just updating a required dependency.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by bombillazo** [comment]
Ready to merge

**Pull request merged**
