### PR TITLE
angular-material: definitions for IDateLocaleProvider

### PR DESCRIPTION
**Pull request by gsipos**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-material/angular-material.d.ts*

to author(@mtraynham). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mtraynham** [comment]
@gsipos @vvakame Definition looks good.  Can we snapshot the current definition (pre-PR) to `angular-material-0.10.1.d.ts` and [up the main definition to 0.11.0](https://github.com/borisyankov/DefinitelyTyped/blob/master/angular-material/angular-material.d.ts#L1) when IDateLocaleProvider was added?

**Comment by gsipos** [comment]
So I should include the pre-PR defintions in a new angular-material-0.10.1.d.ts file?

**Comment by mtraynham** [comment]
Just for convention, I think that would be good.  It may seem a bit overkill since the PR is additive only, but if someone is using angular 0.10.1 and still pointed at this main .d.ts file, they could try to use the IDateLocaleProvider and it wouldn't exist.  Alternatively, their `tsd.json` could point at the 0.10.1 version if necessary.

**Comment by vvakame** [comment]
thanks all!
DefinitelyTyped is maintains for latest version only. :wink:

**Pull request merged**
