### PR TITLE
add proxy for StrategyOptions

### PR DESCRIPTION
**Pull request by leozhao9527**
This proxy property is used for some like heroku product using.

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
@leozhao0709 I can't seem to find any reference to the `proxy` value in the main documentation, can you point me to where you found it?

**Comment by leozhao0709** [comment]
@BlueHatbRit  Yes, it not shows in their main documentation. But it makes things not working happily with nginx proxy or if I deploy my code to heroku. Then I happened to find this post thread: https://www.bountysource.com/issues/25900178-dynamic-callbackurl. I tried to add the `proxy` to my code, then it makes everything works except the typescript compile complain.

**Comment by leozhao0709** [comment]
Another way to resolve this I can think is maybe you export the `StrategyOptions` to a global module, then users can expend the `StrategyOptions` according to their own requirement like the `Express Request`.

**Comment by BlueHatbRit** [comment]
I did some digging and found the `proxy` flag is in the base `passport-oauth2` library (https://github.com/jaredhanson/passport-oauth2/blob/9ddff909a992c3428781b7b2957ce1a97a924367/lib/utils.js) which is used as the foundation of most passport oauth / oauth2 strategies. So this should work in all libraries using that under the hood. That said, it is not documented on that repository readme.

Due to how the types are done in this module I think adding the `proxy` boolean field is just fine, though it might be good to use inheritance from the base library for building our option types. That'll be one for the future I guess, but in an effort to make this work properly I think we should let it though. I'll approve this now 👍

**Review by elliotblackburn — APPROVED** [review]
LGTM, see comments above for reasons.

**Pull request merged**
