### PR TITLE
Add support for Organizations in Auth0

### PR DESCRIPTION
**Pull request by frederikprijck**
This PR adds support for the Organization feature at Auth0 so that people using TypeScript can use it in a type-safe way.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://auth0.com/docs/api/management/v2#!/Organizations/ and https://auth0.github.io/node-auth0/module-management.OrganizationsManager.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by nhardy — APPROVED** [review]
LGTM. Nice work on the extensive tests.

**Comment by frederikprijck** [comment]
Ready to merge

**Comment by alexframe** [comment]
Hi @frederikprijck, there are some overloads missing for some of these endpoints.

For example, `getMembers` should be able to take the `include_totals` option, which then returns a paged result as documented in the auth0 api.

Should I open an issue for this, or is there any plan to resolve this?

At the moment we can't use this version of the auth0 types as we need to maintain our own typings for the `organizations` functions until they are in line with the actual api.

**Comment by alexframe** [comment]
I've opened #56432 to add support to `getMembers` and `getMembersRoles`.

@frederikprijck, as `ManagementClient.organizations.getUserOrganizations` does not have a proxy in the management client, what would you suggest is the best way to add support to this?

I was thinking I could add a `ManagementClientUsersManager` and add it there, similar to what you've done with the `OrganizationManager` - the only problem with that is it will only have this one function in the types - though it would at least make this feature more usable with types.

**Comment by alexframe** [comment]
@frederikprijck I agree the proxies probably do add some confusion.

Tomorrow I may open a draft PR that has a working `getUserOrganizations` type and if I could some quick feedback on the approach from you before I open it up for review that would be great 🙏🏼

**Pull request merged**
