### PR TITLE
[multiple packages] Update GitHub links to HTTPS

### PR DESCRIPTION
**Pull request by westy92**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by westy92** [comment]
@peterblazejewicz I'm seeing similar errors as in my [other recent PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57176#issuecomment-972283058):

```
2> Errors in typescript@4.6 for external dependencies:
Error: 2> ../pino-pretty/index.d.ts(8,31): error TS2307: Cannot find module 'pino' or its corresponding type declarations.
2> 
2>     at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
2>     at Generator.next (<anonymous>)
2>     at fulfilled (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

**Comment by peterblazejewicz** [comment]
it's 7 days old, rebase from master. We've made fixes for `types/pino` usage in #57241

**Comment by westy92** [comment]
@peterblazejewicz I have synced with master and it's still failing.

**Comment by peterblazejewicz** [comment]
@westy92 sorry for pushing into your PR directly. I've make a clean rebase of your changes and found a failing package (and next a hack, to trick DT tooling to install missing dependency)
thanks!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@westy92 thx!

**Comment by westy92** [comment]
Thank you! Glad to see this moving along. 😅

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## dot ([<kbd>unpkg</kbd>](https://unpkg.com/browse/dot@latest/))
was missing the following properties:
1. name
1. log
1. process
## ffi-napi ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ffi-napi@latest/))
was missing the following properties:
1. version
## gulp-stylus ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gulp-stylus@latest/))
was missing the following properties:
1. stylus
## hapi ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi@latest/))
was missing the following properties:
1. server
## hiredis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hiredis@latest/))
was missing the following properties:
1. writeCommand
## jsforce ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsforce@latest/))
was missing the following properties:
1. addListener
1. on
1. once
1. removeListener
1. off

<details>
<summary>as well as these 12 other properties...</summary>
<p>removeAllListeners, setMaxListeners, getMaxListeners, listeners, rawListeners, emit, listenerCount, prependListener, prependOnceListener, eventNames, VERSION, require</p>
</details>

## json-query ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json-query@latest/))
was missing the following properties:
1. lastParent
## jsontoxml ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsontoxml@latest/))
was missing the following properties:
1. json_to_xml
1. obj_to_xml
## memjs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/memjs@latest/))
was missing the following properties:
1. Server
1. Utils
1. Header
## node-resque ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-resque@latest/))
was missing the following properties:
1. MultiWorker
1. PluginRunner
1. Plugin
## node-xmpp-client ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-xmpp-client@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'node-xmpp-client'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. NS_CLIENT
1. SASL
## node-xmpp-core ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-xmpp-core@latest/))
was missing the following properties:
1. exportCoreUtils
## openstack-wrapper ([<kbd>unpkg</kbd>](https://unpkg.com/browse/openstack-wrapper@latest/))
was missing the following properties:
1. Heat
## poker-evaluator ([<kbd>unpkg</kbd>](https://unpkg.com/browse/poker-evaluator@latest/))
was missing the following properties:
1. eval
1. evalCard
## react-responsive ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-responsive@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'react-responsive'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. resetWarningCache
1. match
1. parse
1. typeOf

<details>
<summary>as well as these 28 other properties...</summary>
<p>AsyncMode, ConcurrentMode, ContextConsumer, ContextProvider, Element, ForwardRef, Fragment, Lazy, Memo, Portal, Profiler, StrictMode, Suspense, isValidElementType, isAsyncMode, isConcurrentMode, isContextConsumer, isContextProvider, isElement, isForwardRef, isFragment, isLazy, isMemo, isPortal, isProfiler, isStrictMode, isSuspense, MediaQuery</p>
</details>

## string-replace-webpack-plugin ([<kbd>unpkg</kbd>](https://unpkg.com/browse/string-replace-webpack-plugin@latest/))
was missing the following properties:
1. REPLACE_OPTIONS
## tar-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tar-js@latest/))
was missing the following properties:
1. utils
1. stringToUint8
1. uint8ToBase64
1. base64ToUint8
## thepiratebay ([<kbd>unpkg</kbd>](https://unpkg.com/browse/thepiratebay@latest/))
was missing the following properties:
1. convertOrderByObject
1. defaultOrder
1. primaryCategoryNumbers
## uuid-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/uuid-js@latest/))
was missing the following properties:
1. new
## webpagetest ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpagetest@latest/))
was missing the following properties:
1. paths
1. filenames
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9eb08aecab8987beebabf6b2c688cd90b6825761
</p>

**Comment by westy92** [comment]
Ready to merge

**Pull request merged**
