### PR TITLE
Added event listeners to i18next.d.ts

### PR DESCRIPTION
**Pull request by anwalkers**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by anwalkers** [comment]
handle the `i18next.on('eventName', (arg) => {})` event emitter.

https://github.com/i18next/i18next/blob/master/src/EventEmitter.js

**Comment by mxl** [comment]
@anwalkers According to [documentation](http://i18next.com/docs/api/#on-initialized) each event has unique callback type. Also it would be nice to have `EventEmitter.off()` method in type definition.

**Comment by anwalkers** [comment]
I've added events and emitter.off...

**Comment by mxl** [comment]
@anwalkers Good job. But one more thing.

TypeScript has String Literal Type (read more here https://www.typescriptlang.org/docs/handbook/advanced-types.html) and you can use them as type for event name parameter to restrict its possible values to only one value:
```
on(initialized: 'initialized', listener: (options: I18next.Options) => void): void;
on(loaded: 'loaded', listener: (loaded: any) => void): void;
```

**Comment by anwalkers** [comment]
@mxl tslint is throwing errors for string literal type but I see that is should be supported. Seeing if travis-ci chokes on them

**Comment by anwalkers** [comment]
@mxl the build failed using String Literal Type

```
----------------- For file:i18next/i18next.d.ts
i18next/i18next.d.ts(123,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(124,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(125,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(126,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(127,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(128,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
i18next/i18next.d.ts(129,9): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
```

**Comment by mxl** [comment]
@anwalkers Add non-specialized version: `on(event: string, listener: () => void);` before specialized overloads.

**Comment by mxl** [comment]
👍

**Pull request merged**
