### PR TITLE
[node] Update types to v18.13

### PR DESCRIPTION
**Pull request by Semigradsky**
- [async_hooks] add hook to stop propagation
- [net] add autoSelectFamily and autoSelectFamilyAttemptTimeout options
- [test] add t.after() hook
- [tls] add "ca" property to certificate object
- [utils] add MIME utilities

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/releases/tag/v18.13.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Semigradsky I asked TS team on discord, if `s3-download-stream` can be removed from DT (small sacrifice, big saving). I cannot see how this can be rectified in other way

**Comment by peterblazejewicz** [comment]
under review, TS fix: 
https://github.com/microsoft/TypeScript/pull/52170

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by peterblazejewicz** [comment]
Please update with recent, thx! (I bet you're already on this)

**Comment by Semigradsky** [comment]
Still `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

**Comment by peterblazejewicz** [comment]
@Semigradsky this will be closed/reopened by DT maintainer

**Comment by sandersn** [comment]
5 more AWS dependents need to be updated. First PR is here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64204

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@Semigradsky thanks for the patience!

**Review by peterblazejewicz — APPROVED** [review]
💯

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by rodrigo-voll** [comment]
Can't import mock. What am I doing wrong?

`Module '"node:test"' has no exported member 'mock'.`

the Node documentation says mock is already exposed as of v18.13.0

**Comment by Semigradsky** [comment]
@rodrigo-voll I am trying to add 'mock' in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63892 but have some troubles with getters/setters. I will try solve it on this week

**Comment by rodrigo-voll** [comment]
> @rodrigo-voll I am trying to add 'mock' in #63892 but have some troubles with getters/setters. I will try solve it on this week

Thank you

**Comment by tlhunter** [comment]
I'm still trying to wrap my head around it but a recent change to this project, which I believe to be associated with this PR based on file name and line ranges, is causing our typescript tests to now fail in CI:

```
$ node -v && tsc -v && tsc -p . && tsc test
v16.19.0
Version 3.9.10
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,42): error TS1005: ',' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,44): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,57): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,65): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,66): error TS[11](https://github.com/DataDog/dd-trace-js/actions/runs/4199067431/jobs/7283482447#step:5:12)09: Expression expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1485,67): error TS1109: Expression expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1490,17): error TS1005: ',' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1490,26): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1494,17): error TS1005: ',' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1494,26): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1498,15): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1498,41): error TS1005: '(' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1504,17): error TS1005: ',' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1504,32): error TS1005: ',' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1504,41): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1504,47): error TS1109: Expression expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1508,17): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(1508,43): error TS1005: '(' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(15[12](https://github.com/DataDog/dd-trace-js/actions/runs/4199067431/jobs/7283482447#step:5:13),26): error TS1005: ';' expected.
Error: ../node_modules/@types/node/ts4.8/util.d.ts(15[14](https://github.com/DataDog/dd-trace-js/actions/runs/4199067431/jobs/7283482447#step:5:15),1): error TS11[28](https://github.com/DataDog/dd-trace-js/actions/runs/4199067431/jobs/7283482447#step:5:29): Declaration or statement expected.
```

I'm guessing this change breaks compatibility with the older typescript compiler?

Screenshot 2023-02-16 at 15 42 40

**Comment by yoursunny** [comment]
@tlhunter see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64262#discussioncomment-4896665

**Pull request merged**
