### PR TITLE
rsync: Add typings for "build" static method

### PR DESCRIPTION
**Pull request by LucianBuzzo**
This change adds typings for the [build static method](https://www.npmjs.com/package/rsync#static-methods).
The build method takes an options object, where the keys are Rsync methods and the values are arguments to the methods.
I was able to accurately type this using `keyof` and `Parameters`, but to make this work efffectively I had to refactor
the overloads in the Rsync interface to use union types instead. This is because overloading and `Paramaters` do not
play well together, see https://github.com/microsoft/TypeScript/issues/32164

Change-type: minor
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@LucianBuzzo you've unified signatures, mind updating (removing) `tslint.json` exclusion rule? I'll approve the changes, thx!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@LucianBuzzo thx!

**Comment by LucianBuzzo** [comment]
@typescript-bot Ready to merge

**Comment by LucianBuzzo** [comment]
Ready to merge

**Pull request merged**
