### PR TITLE
Update definitions of @types/react-portal 4.0

### PR DESCRIPTION
**Pull request by HorusGoul**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tajo/react-portal/blob/master/README.md
- [X] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alex-ketch** [comment]
May I ask as to why this PR was closed?
From a preliminary use of the v4 typings, it seems to be working well.

**Comment by shuntksh** [comment]
For some reason, I did not get notification on this. Change seems to be valid.
👍

**Comment by Unislash** [comment]
It doesn't appear that this ever got merged in, @HorusGoul . Seeing as @shuntksh signed off on it, it looks like it's good to go?

**Comment by dmitrika** [comment]
Sorry, it's not clear why this PR was closed. Seems like we don't have correct types for v4.
How can we help to improve it?

**Comment by HorusGoul** [comment]
Sorry, I can't remember why I closed the PR. 

@dmitrika, can you check if the new typings are still working? I've created a new PR with the same changes as I can't reopen this one because I deleted the repo a while ago.

**Pull request closed without merging**
