### PR TITLE
Make Hook<T> Generic with a Default, Add Seleniums Options, Add `moz:firefoxOptions`

### PR DESCRIPTION
**Pull request by phil-lgr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes (see comments below)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by phil-lgr** [comment]
`// TypeScript Version: 2.3`

Is is ok to put the version to 2.3? 🤔 I'd like to make `Hook<T>` have a default: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults

Like this: 
```
interface Hooks<T = void> {
        onError?<T>(error: Error): Promise<T> & undefined;

        onPrepare?<T>(
            config: Options,
            capabilities: DesiredCapabilities
        ): Promise<T> & undefined;
```

That way you don't have to defined the return type of the different hooks `onError?<T>(error: Error): Promise<T> & undefined;`, `T` will default to `void`.

**Comment by phil-lgr** [comment]
I also added `'moz:firefoxOptions'?: any;` to `DesiredCapabilities`

See: https://github.com/mozilla/geckodriver/blob/master/README.md#firefox-capabilities

**Comment by phil-lgr** [comment]
UGH, chai-webdriverio depends on this typing.. mmm make sense to add `// TypeScript Version: 2.3` in chai-webdriverio as well?

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
