### PR TITLE
fix(steam-user): user owned apps type

### PR DESCRIPTION
**Pull request by simonkovtyk**
- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DoctorMcKay/node-steam-user/issues/471
- [ x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/steam-user/steam-user-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3414ffb0f6a64974c4de0cf75bc788281367c96b
</p>

**Review by nordowl — APPROVED** [review]
lgtm

**Comment by simonkovtyk** [comment]
Ready to merge

**Comment by Sec32fun32** [comment]
Tamam teşekkürler

fs

21 Ağu 2024 Çar 23:29 tarihinde TypeScript Bot ***@***.***>
şunu yazdı:

**Pull request merged**
