### PR TITLE
Improved radium type definition

### PR DESCRIPTION
**Pull request by asvetliakov**
case 2. Improvement to existing type definition.

Major overhaul

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
@asvetliakov This looks fantastic! Thanks for doing the work. Do you think you could add a few tests? Let me know if you have any questions about that, I'd be happy to help to get this merged.

**Comment by asvetliakov** [comment]
@alexgorbatchev Sure, i'll add few tests

**Comment by asvetliakov** [comment]
@alexgorbatchev Added test

second decorator with config fails if used with generic so i put any. One of possible solution to use React.StatelessComponent<any> | React.ComponentClass<any> to restrict it only to react components but react component intersection type works only with latest ts next.

**Comment by alexgorbatchev** [comment]
Looks great, thank you!

**Pull request merged**
