### PR TITLE
feat: add types for the SketchApp designer tool

### PR DESCRIPTION
**Pull request by manekinekko**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by amcasey** [comment]
It looks like the underlying project might be written in checkbox.  If that's the case, it might be cleaner to directly distribute the declaration files: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Review by amcasey — CHANGES_REQUESTED** [review]
I guess I'm reluctant to merge this without a compelling reason it can't be distributed with the underlying package.

**Comment by manekinekko** [comment]
Hi @amcasey here is some context...

I am the author of [xlayers.app](https://github.com/xlayers/xlayers/). For the purpose of the app, I built a SketchApp parser in TS and at the same time, created the d.ts file for it. We are gonna distribute the parser + the d.ts file on NPM, in the near future. However, for the time being, the parser is bundled with the xlayers app. Please note that xlayers is an app that isn't meant to be distributed on NPM. 

Also, the reason why we think this definition file should better be hosted in here is that more and more people are writing their own implementation of the SketchApp parser, and spent a lot of time re-writing the definition files. We want to provide them with this file.

**Comment by manekinekko** [comment]
> I'm not aware of a clear policy on which type definitions should and shouldn't be hosted on DT, so I mostly wanted to confirm that you had a conscious reason for diverging from the most common pattern.

My understanding is that TS type definitions are better hosted on DefinitelyTyped and distributed under @types/**. 

> I imagine you plan to remove these type definitions when you start publishing your own version?

My hope is that the SketchApp types got distributed under @types/sketchapp.

**Review by amcasey — APPROVED** [review]

**Comment by amcasey** [comment]
Sorry, I thought I'd already merged this.  That sounds fine.

**Comment by manekinekko** [comment]
Thank you @amacleay

**Comment by amacleay** [comment]
You're welcome! I take full credit for whatever it is I've been thanked for.

**Comment by manekinekko** [comment]
Oops! I meant @amcasey 😇

**Pull request merged**
