### PR TITLE
[enzyme] Added missing methods and deprecation warning on method.

### PR DESCRIPTION
**Pull request by MartynasZilinskas**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Shallow rendering docs](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md), [Full DOM rendering docs](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by MartynasZilinskas** [comment]
@andy-ms I am not sure about `Definitions by` in dts header. Can it be multi line or should it be inline?

**Comment by andy-ms** [comment]
If there are this many people it should definitely be multiline.

**Comment by MartynasZilinskas** [comment]
@andy-ms got it. I think it should be mentioned in `README.md` file, that it can be multiline. Should I make another PR for that?

**Comment by andy-ms** [comment]
Go ahead.

**Comment by MartynasZilinskas** [comment]
Ping for PR: @MarianPalkus, @NoHomey, @pelotom, @jwbay, @huhuanming.

**Comment by huhuanming** [comment]
I was too sleepy. （01:00  GMT+8)
Will tomorrow be OK?

**Comment by MartynasZilinskas** [comment]
Yeah, fine.

**Comment by huhuanming** [comment]
it's ok. @MartynasZilinskas

**Comment by MarianPalkus** [comment]
Lgtm :yes:

**Pull request merged**
