### PR TITLE
[@types/mongodb] Added withTransaction definition and another necessary type.

### PR DESCRIPTION
**Pull request by Ranguna**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

This is a small addition, what kind of tests should be added ?
I don't quite understand what `Create it with "dts-gen --dt", not by basing it on an existing project.` means here. I just wrote the type in the types file.

### CODE REVIEW

**Comment by Ranguna** [comment]
I just noticed that `withTransaction` returns what `commitTransaction` returns and not the return type of the provided function. Which is a bummer for me, since it no longer fits my use case..

Currently, `commitTransaction` returns `Promise<void>`, this is wrong since I'm getting something out of it, but I can't find it in the types file.
Here's what I get:
```
CommandResult {
  result:
   { ok: 1,
     operationTime:
      Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1563904214 },
     '$clusterTime': { clusterTime: [Timestamp], signature: [Object] } },
  connection:
   Connection {
     _events:
      [Object: null prototype] {
        error: [Function],
        close: [Function],
        timeout: [Function],
        parseError: [Function],
        message: [Function] },
     _eventsCount: 5,
     _maxListeners: undefined,
     id: 3,
     options:
      { host: 'blah-blah.my-host.something',
        port: 27017,
        size: 5,
        minSize: 0,
        connectionTimeout: 30000,
        socketTimeout: 360000,
        keepAlive: true,
        keepAliveInitialDelay: 300000,
        noDelay: true,
        ssl: true,
        checkServerIdentity: true,
        ca: null,
        crl: null,
        cert: null,
        key: null,
        passPhrase: null,
        rejectUnauthorized: false,
        promoteLongs: true,
        promoteValues: true,
        promoteBuffers: false,
        reconnect: false,
        reconnectInterval: 1000,
        reconnectTries: 30,
        domainsEnabled: false,
        disconnectHandler: [Store],
        cursorFactory: [Function],
        emitError: true,
        monitorCommands: false,
        setName: 'The Cluster's Name-0',
        promiseLibrary: [Function: Promise],
        clientInfo: [Object],
        servers: [Array],
        retryWrites: true,
        w: 'majority',
        authSource: 'admin',
        replicaSet: 'The Cluster's Name-0',
        caseTranslate: true,
        useNewUrlParser: true,
        auth: [Object],
        dbName: 'my_awesome_db_name',
        socketTimeoutMS: 360000,
        connectTimeoutMS: 30000,
        credentials: [MongoCredentials],
        monitoring: false,
        parent: [ReplSet],
        bson: BSON {} },
     logger: Logger { className: 'Connection' },
     bson: BSON {},
     tag: undefined,
     maxBsonMessageSize: 67108864,
     port: 27017,
     host: 'The Cluster's Name0-0',
     socketTimeout: 360000,
     keepAlive: true,
     keepAliveInitialDelay: 300000,
     connectionTimeout: 30000,
     responseOptions:
      { promoteLongs: true,
        promoteValues: true,
        promoteBuffers: false },
     flushing: false,
     queue: [],
     writeStream: null,
     destroyed: false,
     hashedName: 'somehash',
     workItems: [],
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'The Cluster's Name0-0',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 6,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'The Cluster's Name0-0',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: false,
        timeout: 360000,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 161,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 360000,
           _idlePrev: [TimersList],
           _idleNext: [Timeout],
           _idleStart: 12984,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 199,
           [Symbol(triggerId)]: 161 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object],
        [Symbol(disable-renegotiation)]: true },
     buffer: null,
     sizeOfMessage: 0,
     bytesRead: 0,
     stubBuffer: null,
     ismaster:
      { hosts: [Array],
        setName: 'The Cluster's Name-0',
        setVersion: 1,
        ismaster: true,
        secondary: false,
        primary: 'The Cluster's Name0-0',
        tags: [Object],
        me: 'The Cluster's Name0-0',
        electionId: 7fffffff0000000000000001,
        lastWrite: [Object],
        maxBsonObjectSize: 16777216,
        maxMessageSizeBytes: 48000000,
        maxWriteBatchSize: 100000,
        localTime: 2019-07-23T17:50:02.702Z,
        logicalSessionTimeoutMinutes: 30,
        minWireVersion: 0,
        maxWireVersion: 7,
        readOnly: false,
        ok: 1,
        operationTime: [Timestamp],
        '$clusterTime': [Object] },
     lastIsMasterMS: 165 },
  message:
   BinMsg {
     parsed: true,
     raw:
      <Buffer a  pr et ty bi g  bu ff er ... >,
     data:
      <Buffer a  pr et ty bi g  bu ff er ... >,
     bson: BSON {},
     opts:
      { promoteLongs: true,
        promoteValues: true,
        promoteBuffers: false },
     length: 163,
     requestId: 40756096,
     responseTo: 25,
     opCode: 2013,
     fromCompressed: undefined,
     responseFlags: 0,
     checksumPresent: false,
     moreToCome: false,
     exhaustAllowed: false,
     promoteLongs: true,
     promoteValues: true,
     promoteBuffers: false,
     documents: [ [Object] ],
     index: 147,
     hashedName: 'anotherhash' } }
```

**Review by CaselIT — APPROVED** [review]

**Comment by CaselIT** [comment]
The typing looks good.
Maybe file a bug report in the mongodb repository to report this issue

**Comment by Ranguna** [comment]
Thanks :smiley: 

It's not really an issue, it's just their way of doing things.
I'm going to have to write my own `withTransaction` now.

But the issue here is that, according to this typing file, `commitTransaction`'s return type is `Promise<void>`, but in reality, it's not.
It returns something, but it's kinda huge to type it all.
I guess we could keep it that way for the time being, until a better solution is found.

Should I set `withTransaction` return type to `commitTransaction`'s ?
`withTransaction` returns `commitTransaction`, so it absolutely returns whatever `commitTransaction` returns. but it's not `Promise<void>`.

**Comment by CaselIT** [comment]
I guess so. The documentation is not really clear on what the return type should be.
Thanks

**Comment by Ranguna** [comment]
Well.. I guess I was too late to cancel the merge.
I'll make another PR soon to fix the wrong typing, with some other additions as well .

**Pull request merged**
