### PR TITLE
Update prop types

### PR DESCRIPTION
**Pull request by nik-john**
This commit updates the propTypes to reflect the new set as of react-spinkit v3.0.0

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/KyleAMathews/react-spinkit/commit/16d7a7db2748e468a30c8b991b126f9cd195cee4>>
- [X] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by sandersn** [comment]
Travis failed because of the header changes. Can you take a look at how other multi-line headers are formatted? Also, please stick with spaces if the original files use spaces. That might be the source of the problem.

**Comment by mleko** [comment]
👎
v3 definitions are available here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-spinkit/index.d.ts

**Comment by zzanol** [comment]
I recommend https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17444, which includes additional v3 changes not included in the PR.

**Comment by sandersn** [comment]
OK, I merged #17444. Does that obsolete this PR such that it should be closed?

**Comment by zzanol** [comment]
Yes, this PR should be closed.

**Pull request closed without merging**
