### PR TITLE
lodash: add/update min, max, first, head, reduce

### PR DESCRIPTION
**Pull request by seansfkelley**
This PR fixed a bunch of issues I've seen while using the typings (sorry that there's not a more specific theme).
- `min`/`max`: added to the explicit wrapper
- ~~`fromPairs`: fixed the dummy to at least return an object; added implicit and explicit wrapper types (they still use `any`)~~
- ~~`mapValues`: added to the explicit wrapper~~
- `first`/`head`: removed from explicit object wrapper; fixed return type of explicit array wrapper version
- ~~`pickBy`: make predicate optional as specified in the docs~~
- `reduce`: added to the explicit wrapper

Edit: I have since moved the less controversial changes into #8783.

### CODE REVIEW

**Comment by seansfkelley** [comment]
So I realized that the **tests are failing**, but I had a question about those: the tests for `first` and `head` instantiate a `List`, which is the type that mimics both arrays and jQuery objects, but that seems to be hitting the object version of the wrapper, which I removed `first` and `head` from because it's not actually supported by Lodash (by design). I feel like this issue could/should be solved elsewhere but I couldn't find an example of it, and I didn't want to just delete the tests without due diligence. Thoughts @bczengel, @chrootsu?

**Comment by chrootsu** [comment]
Hi @seansfkelley! Thanks mate!
Unfortunately I don't agree with some changes:

**_.head, _.first**
```javascript
// example in js

// returns simple value
console.log(_.first([1]));
console.log(_([1]).first()); 

// returns wrrapper when a chain is explicitly chained before
console.log(_([1]).chain().first().value()); // returns LoDashExplicitWrapper<number> in typescript
console.log(_([[1]]).chain().first().value()); // returns LoDashExplicitArrayWrapper<number> in typescript
console.log(_([{a: 1}]).chain().first().value()); // returns LoDashExplicitObjectWrapper<{a: number}> in typescript

// the same with _.head clearly, and _.min, _.max also
```

Setting of a return type directly isn't an elegant way, I agree but don't see better one. In this case any of ExplicitWrappers can be returned and it depends on a type of input collection elements but can't be inffered from it.

**_.min, _.max**
The same as above when excplicitly chained.

**_.reduce**
The same as above when excplicitly chained. Also the `thisArg` don't exist in the lodash-4 variant of this method.

**_.fromPair**
That's ok. I will extend the dummy for other cases after merge the PR... Or will add commit to this PR if to be before.

**_.mapValues and _.pickBy**
These signatures look good to me. :+1:


P.S. Sorry for my bad English.

**Comment by chrootsu** [comment]
@bczengel @vvakame @basarat Do you know a more elegance way for cases when a chain is explicitly and returns value of `any` type that should be wrapped to different generics in dependence on an actualy type? Or do you have any advices maybe? I would be very thankful! ^_^

**Comment by seansfkelley** [comment]
I did some noodling with `head` and `first` using this modified version of your example there, and the typings check out just after adding c09a6d3d8c6c3cae7644caca85e5a89b6a6e7bf3:

```
let num: number = _([1]).chain().head().value();
let arr: number[] = _([[1]]).chain().head().value();
let obj: { a: number } = _([{ a: 1 }]).chain().head().value();

console.log(num);
console.log(arr);
console.log(obj);
```

**Comment by seansfkelley** [comment]
I appreciate you taking a look at this; I pulled out the changes you okayed into https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8783 so that this PR could just be about what to do about min/max/first/head/reduce, which as you say all have the same problem.

**Comment by seansfkelley** [comment]
I don't have the time to bring this PR to completion, so I'm going to close it out to reduce noise in the repo.

**Pull request closed without merging**
