### PR TITLE
[react-redux] Update for redux@4.0.0-beta.2

### PR DESCRIPTION
**Pull request by ryym**
Hi, could I update a package for a beta version?

Currently [Redux][redux] is bumping up its major version to 4.0.0, and it published the latest version [`4.0.0-beta.2`][redux-4beta2] last month. Though it is still a beta version, I want to use it with `react-redux`. However current `@types/react-redux` type definitions are only for `redux@3.x` so I created this PR.

[redux]: https://github.com/reactjs/redux
[redux-4beta2]: https://github.com/reactjs/redux/releases/tag/v4.0.0-beta.2

(There is a similar PR #22953, but it updates `@types/react-redux` for `redux@4.0.0-beta.1`, not `4.0.0-beta.2`)

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/reactjs/redux/blob/8c5fbc10bdc3114883/index.d.ts>
- [ ] Increase the version number in the header if appropriate.
    - The current version seems wrong. `types/react-redux/index.d.ts` says `5.0.8` but the actual latest version is `5.0.7` ([react-redux on npmjs](https://www.npmjs.com/package/react-redux)). Should I decrease the version number?
   https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c895c48502fcad26bb2caa00b0db0c603089f4b7/types/react-redux/index.d.ts#L1

- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
This doesn't seem like a good idea for the average user. We prefer not to have dependencies on beta packages in the main folder.

**Comment by ryym** [comment]
OK, thanks for reviewing!

**Comment by thchia** [comment]
Just a quick heads up that the [day has come.](https://github.com/reactjs/redux/releases)

**Comment by ryym** [comment]
@thchia Thanks,  I created a new PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25109 :)

**Pull request closed without merging**
