### PR TITLE
added guess(): MomentZone

### PR DESCRIPTION
**Pull request by sclausen**

### CODE REVIEW

**Comment by michelsalib** [comment]
Thanks for your contribution @sclausen :)
Can you add a test ?

**Comment by sclausen** [comment]
sorry, I missed ;)

**Comment by michelsalib** [comment]
We are now good

**Comment by michelsalib** [comment]
:+1:

**Comment by horiuchi** [comment]
@sclausen Thanks mate!
@michelsalib Thanks for review!

**Pull request merged**
