### PR TITLE
Web Speech API

### PR DESCRIPTION
**Pull request by saschanaz**
Basic definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
@SaschaNaz thank you your contributions.
please check this document http://definitelytyped.org/guides/contributing.html#tests

* [ ] add tests

**Comment by SaschaNaz** [comment]
Oh, I didn't do as I saw their are some definitions without tests. OK, I'll add one :D

**Comment by SaschaNaz** [comment]
Added. :D

**Comment by SaschaNaz** [comment]
OK, let's go again.

**Comment by vvakame** [comment]
@SaschaNaz thanks mate!

**Pull request merged**
