### PR TITLE
Add Swagger API

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by vvakame** [comment]
*swagger/swagger.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/swagger
  * http://bower.io/search/?q=swagger
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (swagger/swagger-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
is this definition file for https://github.com/swagger-api/swagger-node ?

**Comment by mohsen1** [comment]
No, this is for a Swagger object in general. Swagger is a JSON object.

**Comment by SamuelMarks** [comment]
Thanks @mohsen1 ; you just saved me a bunch of time for my project :dancer:

**Comment by mohsen1** [comment]
The naming for this is kind of different. "swagger" in npm is the swagger-node project but this is more related to [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official). So should this be named swagger-schema-official or swagger?

I don't know what to test? Can you help me with that?

**Comment by vvakame** [comment]
I think `swagger-schema-official` would be good.
Test is use case. do you have any sample code? please use it.

**Pull request closed without merging**
