### PR TITLE
lodash: use intersection types for _.memoize, support _.memoize.Cache

### PR DESCRIPTION
**Pull request by thorn0**
see https://lodash.com/docs#memoize

### CODE REVIEW

**Comment by vvakame** [comment]
@th0br0 please resolve conflict.

**Comment by chrootsu** [comment]
@thorn0 thanks for your contribution!
:+1:

**Comment by th0br0** [comment]
@vvakame accidental highlight, I presume?

**Comment by thorn0** [comment]
@vvakame done

**Comment by vvakame** [comment]
wow, sorry! it is mistake...

**Pull request merged**
