### PR TITLE
[jsforce] Add few missing definitions

### PR DESCRIPTION
**Pull request by netes**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
http://jsforce.github.io/jsforce/doc/SObject.html
http://jsforce.github.io/jsforce/doc/Connection.html

### CODE REVIEW

**Comment by dolanmiu** [comment]
Thanks, good work

I noticed that Query doesn't have the `end()` method in the documentation though:

http://jsforce.github.io/jsforce/doc/Query.html

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17828/commits/fc18988b7e3505e60649f2a290d7b6db0a15ba52#diff-63387d907f8e11804fedd76945ee03a0R11

**Comment by netes** [comment]
You're right, but here's a fragment of documentation:
```js
conn.sobject("Contact")
  .select('*, Account.*')
  .include("Cases") // include child relationship records in query result. 
     // after include() call, entering into the context of child query.
     .select("*")
     .where({
        Status: 'New',
        OwnerId : conn.userInfo.id,
     })
     .orderby("CreatedDate", "DESC")
     .end() // be sure to call end() to exit child query context
```

If we don't have `end` defined in `Query` it throws an error.
I'm a novice when it comes to TypeScript, maybe you've got an idea what might be wrong or how to solve it?

**Comment by dolanmiu** [comment]
Ok after some more search, I found that:

`end()` is in SubQuery
and `orderby()` doesn't exist in `Query` nor `SubQuery`

http://jsforce.github.io/jsforce/doc/Query-SubQuery.html
http://jsforce.github.io/jsforce/doc/Query.html

So odd, perhaps making a new `SubQuery` class which extends the `Query` class would be nice

**Comment by netes** [comment]
It's funny actually. I've made additional class for `SubQuery` with `end` method and that's fine, but... We've also got `select` on `SubQuery` which is inherited from `Query` and, based on the docs, returns `Query`, not `SubQuery`. Then, if we do something like this:
```js
        this.sfConnection.sobject('property')
          .select('something')
          .include('relationship)
            .select('something')
            .end()
```
we'll still get an error that `.end` is not found on `Query` ;)

I see 2 solutions here - don't differentiate `Query` and `SubQuery` and add `.end` to `Query` in definitions or override all methods in `SubQuery` definition to return `SubQuery` (which is not consistent with documentation too :( ).

What's your opinion on that?

**Comment by dolanmiu** [comment]
Hmm, I see what you mean

I'd say make it simple and just add `.end()` to Query then. It sounds like the second option is leading to a dark path :P

**Comment by netes** [comment]
I've added one small change - `Record` type, as `.retrieve` should return `Record`.

**Comment by dolanmiu** [comment]
Nice work!

**Pull request merged**
