### PR TITLE
Updating LoDashExplicitArrayWrapper.first declaration

### LINKED ISSUE #14337: Lodash chain methods uses wrong generic type
- [ x ] I tried using the `@types/xxxx` package and had problems.

- Authors: @bczengel, @chrootsu, @stepancar

// Type definitions for Lo-Dash 4.14

This interface (and others) uses wrong types. Type `<T>` should not be used in the method name, only in the interface.

```
    interface LoDashExplicitArrayWrapper<T> {
        /**
         * @see _.head
         */
        first<T>(): T;
    }
```

To make this code use correct type:

```
let a = _([1, 2, 3])
	.chain()
	.first();
```

Currently this code makes `a` with type `{}`.

Definition of interface should be as below, to make `a` of type `number`.

```
    interface LoDashExplicitArrayWrapper<T> {
        /**
         * @see _.head
         */
        first(): T;
    }
```

### PR DESCRIPTION
**Pull request by eggers**
Fixes #14337

### CODE REVIEW

**Comment by eggers** [comment]
A similar thing might need to be done for `LoDashExplicitObjectWrapper`, but I'm not sure so I didn't include it in my pull request.

I would think it would be something like:

```ts
        first<T>(): LoDashExplicitWrapper<T>;
```

**Comment by aj-r** [comment]
Unfortunately, `first(): LoDashExplicitObjectWrapper<T>;` isn't quite right in all cases, for example:

```
_.chain([[1, 2], [3, 4]]).first();  // should be LoDashExplicitArrayWrapper<number>
```

That's why the types are written the way they are - the intent is that you pass in the type of wrapper that you want back, e.g.:

```
_.chain([[1, 2], [3, 4]]).first<_.LoDashExplicitArrayWrapper<number>>();
```

It sucks, I know. I'm actually working on a PR that revamps all of the implicit/explicit wrappers to fix this. Sorry I didn't realize #14337 existed, or I would have commented there. Basically, the new types will look like this:

```
interface LoDashExplicitWrapper<TValue> {
    /**
     * @see _.head
     */
    first<T>(this: LoDashExplicitWrapper<List<T> | null | undefined>): LoDashExplicitWrapper<T | undefined>;
}
```

This will also fix `head`, `last`, `find`, and any other function with this issue.

**Comment by aj-r** [comment]
Hopefully my PR will be ready soon. In the meantime, I think we should close this one.

**Comment by eggers** [comment]
@aj-r Will your pull request require a return type to be specified? Or will it have sensible defaults? i.e. something like this:'

```
    interface LoDashExplicitArrayWrapper<T> {
        /**
         * @see _.first
         */
        first<U = LoDashExplicitObjectWrapper<T>>(): U;
    }
```

**Comment by aj-r** [comment]
Yes - I've added some tests for this - I can now do: `_.chain([{ a: 1 }]).first()` and it infers the correct type of `LoDashExplicitWrapper<{ a: number }>`

**Comment by aj-r** [comment]
Maintainers: I would prefer to close this PR in favor of #19356

**Comment by minestarks** [comment]
@eggers OK if I close this in favor of @aj-r's PR?

**Comment by eggers** [comment]
@minestarks yeah that's good by me

**Comment by minestarks** [comment]
Thanks. Will take a look at the other PR shortly

**Pull request closed without merging**
