### PR TITLE
bugsnag-node: Add types - bugsnag-js: Provides its own types

### PR DESCRIPTION
**Pull request by kal-rein**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by kattrali** [comment]
👎 

I'm not sure I understand what's going on here. [bugsnag-js](https://github.com/bugsnag/bugsnag-js) and [bugsnag-node](https://github.com/bugsnag/bugsnag-node) are two separate libraries. Why remove one to add the other?

**Comment by DarkerTV** [comment]
@kattrali At NPM [bugsnag](https://npmjs.com/bugsnag) points to [bugsnag-node](https://github.com/bugsnag/bugsnag-node) library. And bugsnag-js provide their [own typings](https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.d.ts) in their library.

**Comment by kattrali** [comment]
Ah, I see. Thanks for the clarification @DarkerTV. It might be a breaking change though if someone was using the bugsnag-js types and then suddenly gets the new definitions, right? 

As an workaround, would you mind sending a PR to bugsnag-node with the type definitions and then both libraries can be marked as not needing definitions? I can test and merge it later today.

**Comment by DarkerTV** [comment]
Ok @kattrali. Right now I have to leave, I'll send the PR at bugsnag-node later today.

**Pull request closed without merging**
