### PR TITLE
Definitions for arrive

### PR DESCRIPTION
**Pull request by samdark**
https://github.com/uzairfarooq/arrive

### CODE REVIEW

**Comment by vvakame** [comment]
*arrive/arrive.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/arrive
  * http://bower.io/search/?q=arrive
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (arrive/arrive-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by samdark** [comment]
Added tests.

**Comment by vvakame** [comment]
@samdark https://travis-ci.org/borisyankov/DefinitelyTyped/builds/66732869 travis ci failed...

**Comment by samdark** [comment]
Yeah. Seems I've covered jQuery only. Need to add defs for Document.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
