### PR TITLE
"chartist" improvements: added "series" to the ILineChartOptions, files reformat, definitions change

### PR DESCRIPTION
**Pull request by affilnost**
- [x] The package "chartist" was modified
- [x] Improvements made: added "series" to the ILineChartOptions, files reformat, definitions change
- [x] Changed the tests accordingly, tested

**Info**
The case shown here https://gionkunz.github.io/chartist-js/examples.html#example-line-series-override (press **Edit Example**) was not supported. To be precise, having "series" inside of "options" was not possible.
I added this test case, added support of "series" inside of "options" and tested everything. In addition, I reformatted the files with 4 spaces indentation and added myself into definitions.

- [x] URL to documentation which provides context for the suggested changes: https://gionkunz.github.io/chartist-js/examples.html#example-line-series-override
(press **Edit Example**)

### CODE REVIEW

**Comment by mtgibbs** [comment]
Was formatting causing the CI to fail?  I'd prefer if that large of a change was not present in a functional change.

**Comment by affilnost** [comment]
When editing files, an IDE uses **.editorconfig** where it says the indentation is 4 spaces. It means, that 4 spaces are being applied in IDE for the new changes, and it's just inconvenient: whether you need to edit your new changes manually to have 2 spaces indentation(which takes time), or you have to live with having different indentations inside of one file.
Therefore it sounds logical for me to format file before doing any functional changes, just for development convenience purpose. It needs to be done somewhen anyway, why not before doing changes. I did formatting in a separate commit of course.
How else would you separate those changes? If I did them in separate pull-requests, there would be conflicts when merging.
Formatting itself looks like a big change, but in fact changing indentation from 2 spaces to 4 can not cause any compilation/execution problems, because those are just spaces.

**Review by mtgibbs — APPROVED** [review]
All changes have corresponding tests.  👍

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
