### PR TITLE
[jointjs] Added export for nodejs

### LINKED ISSUE #14815: jointjs: Declare and export module
- [X] I tried using the `@types/jointjs` package and had problems.
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @ChrisMoran et al.

Currently I am not able to import JointJS correctly with TypeScript and had to resort to using the (typeless) JavaScript require syntax. Despite reading the TS modules docs & more, I'm by no means a TS expert...but shouldn't the definitions file define and export a module, so it can actually be loaded?

* tsconfig.json: Node package resolution, CommonJS modules.
* Failing statement: `import * as joint from 'jointjs';`
* Also fails: `import joint = require('jointjs');`
* Error in VS Code: **'File ...../node_modules/@types/jointjs/index.d.ts is not a module'**

IMO one way to solve this would be to add following module declaration:

`declare module "jointjs" {
  export = joint;
}`

If I'm doing something completely wrong here, do let me know. Otherwise could you please update the definitions as suggested? Cheers for your feedback!

### PR DESCRIPTION
**Pull request by CaselIT**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
jointjs could not be imported with a `import * as joint from 'jointjs'` or `import joint = require('jointjs')`
Closes #14815

### CODE REVIEW

**Comment by andy-ms** [comment]
Better: Remove the `declare namespace joint { ... }` wrapper around everything (and unindent all the code inside). Then add `export` in front of each namespace declaration, and `export as namespace joint;` at the top.

**Comment by CaselIT** [comment]
@andy-ms I wanted to avoid it since I did not want to change the rappid package.
But I've update both now.
Thanks for the feedback

**Comment by mhegazy** [comment]
@CaselIT can you please rebase

**Comment by CaselIT** [comment]
@mhegazy Should have rebased it correctly

**Pull request merged**
