### PR TITLE
Update restify typings

### PR DESCRIPTION
**Pull request by jtrinklein**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
We can't receive from author. please ping me again in 2 days. I'll merge this PR.

**Comment by jtrinklein** [comment]
@vvakame `ping` it's been 2 days

**Comment by jtrinklein** [comment]
Just checking in, did you want to merge this?

**Comment by jtrinklein** [comment]
@vvakame been a couple more days, were you able to hear from the author?

**Comment by vvakame** [comment]
@jtrinklein sorry for late! it merged. I'm working hard to review pull request.

**Comment by jtrinklein** [comment]
Thank you! I really appreciate it.

**Pull request merged**
