### PR TITLE
normalised interfaces names (module contains local and session storag…

### PR DESCRIPTION
**Pull request by jpmnteiro**
case 2. Improvement to existing type definition.

The [readme.md](https://github.com/gsklee/ngStorage/blob/master/README.md) at the module's [repository](https://github.com/gsklee/ngStorage), clearly shows that the `.$reset()` argument is optional, so updated the definition to reflect that.

Furthermore, given that the module deals with both Session and Local storage, and given that they both share the same interface, it made sense that the interfaces names would be made agnostic to the storage medium.

### CODE REVIEW

**Comment by vvakame** [comment]
I'll merge this PR if we can't get response from author. please ping me again in 2 days.

**Comment by jpmnteiro** [comment]
Thanks @vvakame. Curious question, module author or typings author? Anyway, I've left a note on the module's github page telling him about the typings, but he appears to be silent at the moment.

**Comment by vvakame** [comment]
typings author. he is 1st user of this definitions. 😉

**Comment by jpmnteiro** [comment]
@vvakame any news from the author?

**Comment by vvakame** [comment]
none. I decided to merge this PR. sorry for late.

**Pull request merged**
