### PR TITLE
Add object type to the MJML package

### PR DESCRIPTION
**Pull request by eiskalteschatten**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mjml.io/documentation/#using-mjml-in-json (the function also takes a JSON object; not just a string)

### CODE REVIEW

**Review by marpstar — CHANGES_REQUESTED** [review]
@eiskalteschatten thanks for this PR. 

this looks pretty good. Ideally, we'd use a more specific type that just `object` here, to provide better support for autocomplete / type-checking. 

After checking the docs, it looks like the schema would be something like the following:

```ts
interface MJMLJsonObject {
    tagName: string;
    attributes: object;
    children: MJMLJsonObject[];
}
```

and then the function signature would be changed to

```ts
declare function mjml2html(inp: string | MJMLJsonObject, opts?: MJMLParsingOpts): MJMLParseResults;
```

Would you be willing to make this small change?

**Comment by eiskalteschatten** [comment]
@marpstar No problem. You're right, that does make more sense. I'll make the change now.

**Comment by eiskalteschatten** [comment]
Just pushed it.

**Review by marpstar — CHANGES_REQUESTED** [review]
Perfect.  

I didn't think about this until after I submitted my last review, but would you mind adding a usage example to the test file?  Apologies for not realizing it earlier. 

Once that's done, I'll happily to approve.

**Comment by eiskalteschatten** [comment]
No problem. I also just noticed we forgot the "content" property. I'll add that as well and make both it and children optional since neither of those are required.

**Review by marpstar — APPROVED** [review]
Looks great. Thank you!

**Comment by eiskalteschatten** [comment]
You're welcome!

**Pull request merged**
