### PR TITLE
chrome: Make chrome.input.ime.KeyboardEvent.requestId optional.

### PR DESCRIPTION
**Pull request by darrnshn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/input_ime.json;l=21;drc=90e7b855cf36d356fe676a9243b412081cd50d34?originalUrl=https:%2F%2Fcs.chromium.org%2F
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by fredrikhr — CHANGES_REQUESTED** [review]
I see from https://developer.chrome.com/extensions/input_ime#type-KeyboardEvent that this property has now been deprecated. Can you please update the comment to the comment shown in the docs and mark the property as deprecated?

**Review by fredrikhr — COMMENTED** [review]
Hmm... The documentation does not specify when the property was deprecated. I wonder whether we should just write `@deprecated` without specifying a version...

**Comment by darrnshn** [comment]
I found the [patch](https://crrev.com/c/1808666) that made the change. It seems to have first landed in 79 according to omahaproxy.

Happy to just remove the version if you prefer.

**Review by fredrikhr — APPROVED** [review]
Great, then I have no worries :+1:

**Review by fredrikhr — APPROVED** [review]

**Pull request merged**
