### PR TITLE
dockerode: Improve GetEventsOptions to allow passing a filter object

### PR DESCRIPTION
**Pull request by Page-**
I added a separate initial commit that runs prettier on the files as covered in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bc6280c39eaf2f533e0e6591fc9260609e310a38/README.md#common-mistakes I can remove that commit if desired but wanted to match the guidelines

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
* The command getEvents maps to for docker is https://docs.docker.com/engine/api/v1.37/#operation/SystemEvents which accepts "A JSON encoded value of filters (a `map[string][]string`) to process on the event list."
* The options are passed through docker-modem and will be automatically stringified if necessary: 
https://github.com/apocas/docker-modem/blob/v2.1.1/lib/modem.js#L425-L435
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by P4sca1 — CHANGES_REQUESTED** [review]
Would be great to be more specific on the key and value type to improve auto completion. The following filter keys are supported according to the docs:
* config
* container
* daemon
* event
* image
* label
* network
* node
* plugin
* scope (value: local or swarm)
* secret
* service
* type (value: container or image or volume or network or daemon or plugin or service or node or secret or config)
* volume

**Review by CameronDiver — APPROVED** [review]
I'd like to see better key typings as well, but happy for this to go ahead without.

**Comment by Page-** [comment]
@P4sca1 @CameronDiver I've changed to use stricter typings, the reason I didn't initially was to avoid issues as/when docker adds more keys to filter on but they can be added explicitly later instead

**Review by P4sca1 — APPROVED** [review]

**Comment by Page-** [comment]
I fixed the conflicts from #43238 being merged

**Comment by Page-** [comment]
@orta if it helps get this merged I'm completely happy to remove the prettier commit, I was just trying to follow the repo guidelines as set out in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bc6280c39eaf2f533e0e6591fc9260609e310a38/README.md#common-mistakes

**Comment by thegecko** [comment]
@Page- reformatting chanbes are certainly easier to review in a separate PR ;)

**Comment by Page-** [comment]
@thegecko I did make it into a separate commit to make it easier, the easiest would be to run the prettier command locally and check the diff to verify it if you want. I'm also happy to ignore the repo guidelines if one of the DefinitelyTyped maintainers ask me to drop the commit but two people already reviewed and approved so ideally I'd rather not do it purely on speculation

**Comment by orta** [comment]
I think we have enough 👍s to consider this PR mergeable, the formatting is totally cool with me

**Pull request merged**
