### PR TITLE
[got] Export error classes as properties on got function

### LINKED ISSUE #19542: [got] instanceof checks broken for error types
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BendingBender, @LinusU 

I'm having another small problem which I'm not entirely sure on how to best solve. I'm trying to do a `instanceof` check with an error that is coming back from `got`. My code looks something like this:

```typescript
import got = require('got')
import assertRejects = require('assert-rejects')

// ...

await assertRejects(
  got.post(`${server.url}/v1/accounts`, { json: true, headers, body: input }),
  err => (err instanceof got.HTTPError && err.statusCode === 409)
)
```

But since `HTTPError` is exported as an interface on the namespace `got`, and not a class as a property on the got function, I get the following error:

> [ts] Property 'HTTPError' does not exist on type 'GotFn & Record<"get" | "post" | "put" | "patch" | "head" | "delete", GotFn> & { stream: GotStream...'.

### PR DESCRIPTION
**Pull request by LinusU**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sindresorhus/got/blob/e31282dfd3402e7581bc7921746a62b35e9a8a31/index.js#L592-L641
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

fixes #19542

### CODE REVIEW

**Comment by BendingBender** [comment]
:+1:

**Comment by LinusU** [comment]
Might be missing something 🤔 but shouldn't @dt-bot add appropriate tags?

**Comment by sandersn** [comment]
@LinusU, @typescript-bot was down for a couple of days because of a build error. It's back at work now!

**Comment by LinusU** [comment]
Awesome! 👏

**Pull request merged**
