### PR TITLE
add `make-arrow-function`

### PR DESCRIPTION
**Pull request by ljharb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
If this is your own package, then it's probably best to bundle these type definitions with the library instead of having a separate `@types` package

**Comment by ljharb** [comment]
I disagree; that conflates the semver of the types with that of the implementation.

**Comment by rbuckton** [comment]
> I disagree; that conflates the semver of the types with that of the implementation.

If you are the package author, then it is usually better to ship the types with your own package and have it versioned along with your package since you have control over your own package's repository and don't need to wait on reviews from a DT maintainer.

**Comment by rbuckton** [comment]
I do not understand the semver distinction you made earlier. Types on DT must match the `major.minor` of the package they describe, so any changes to the types only occurs at the patch level.

**Comment by ljharb** [comment]
On DT, yes, but if i make a breaking change to types shipped with a package, semver dictates that be a major bump - but if it’s not a break at runtime, it shouldn’t be major.

**Comment by MysteryBlokHed** [comment]
Even if breaking changes are made to the types, the guideline is that the types' major and minor versions should match the library's. So even if there is some huge change that needs to be made to the types on DT, the types package version can't be incremented unless the library's is as well.

By having the types bundled with the library instead, you can decide whether you feel a major version change is necessary.

**Comment by ljharb** [comment]
@MysteryBlokHed i'm aware of how DT works. In my own package, I'm saying that semver *requires* a major version change in that case - it's simply not up to me. Either I do it, and punish my JS consumers, or don't, and no longer comply with semver.

**Comment by rbuckton** [comment]
> (Another alternative, ofc, would be that package authors wouldn't require maintainer review in DT, but i understand why that might not be ideal)

Assuming you have a second reviewer for the types package, add tests accompanying any changes to the types, and aren't making changes to configuration (including the `package.json`, `tsconfig.json`, lint rules, etc.), maintainer review isn't usually required.

Ideally, for cases like this there would be a better mechanism for package authors to publish types themselves in a way that is not bound to the `@types` organization on NPM, such as a field in the `package.json` of a runtime package that points to an independent types package and the ability to install a package's types automatically (or via a `--types` flag) when it's listed in `devDependencies`.

**Comment by ljharb** [comment]
Sure, that would be a fine alternative. In the meantime, DT seems appropriate.

**Review by rbuckton — APPROVED** [review]

**Comment by ljharb** [comment]
Ready to merge

**Pull request merged**
