### PR TITLE
koa: add types for parsed query and headers

### PR DESCRIPTION
**Pull request by tellnes**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/koajs/koa/blob/2.13.1/lib/request.js#L36
  - https://github.com/koajs/koa/blob/2.13.1/lib/request.js#L175
  - https://github.com/koajs/koa/blob/2.13.1/lib/response.js#L47
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by harryparkdotio — APPROVED** [review]
Nice ✨

**Comment by tellnes** [comment]
New commit was just to make the CI run again after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51152 was merged.

**Review by harryparkdotio — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by tellnes** [comment]
Ready to merge

**Comment by minidonut** [comment]
Dude, You just broke backward compatibility. Replacing certain type with more narrowed type is not compatible. If you meant, Major version of the package should be updated 😕

**Comment by linxiaowu66** [comment]
breaking change...... i have to modify so much files

**Comment by linxiaowu66** [comment]
if i pass ctx.query to function , will report this error:

`xxFunction(ctx.query)`

```
Argument of type 'ParsedUrlQuery' is not assignable to parameter of type '{ page: number; pageSize: number; }'.
  Type 'ParsedUrlQuery' is missing the following properties from type '{ page: number; pageSize: number; }': page, pageSize
```

**Comment by tellnes** [comment]
@minidonut Definitely Typed packages matches the version for the corresponding library. This is not a change in the Koa library, but fixed the type here which was wrong. So how it is possible to do this as a major update?

@linxiaowu66 The error message sounds to me like there is a problem in your code. Remember that the parsed query string object is not an object with only strings as value. The value can can also be an array with strings. Eg. `querystring.parse('foo=A&foo=B&bar=C')` will results in `{ foo: [ 'A', 'B' ], bar: 'C' }`. So if you are assuming the values in the parsed query string objects always will be a string, you have a bug in your code. In your error above you are expecting values as numbers. The type `string | string[] | undefined` is not a number, and that is the type you are getting from the parsed query string object.

**Pull request merged**
