### PR TITLE
[HAL] Link object

### PR DESCRIPTION
**Pull request by Maks3w**
https://tools.ietf.org/html/draft-kelly-json-hal-06#section-5

### CODE REVIEW

**Comment by vvakame** [comment]
*hal/hal.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/hal
  * http://bower.io/search/?q=hal
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (hal/hal-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by Maks3w** [comment]
This is not related with any implementation.

I use this for type my API responses etc. Just this, typing.

**Comment by Maks3w** [comment]
It's like to type promises. This is the abstract code and implementators "should" extend from this.

**Comment by vvakame** [comment]
@Maks3w https://www.npmjs.com/package/hal is already exists.
we should choose another naming. e.g. json-hal . it is vacancy on npm.

**Comment by Maks3w** [comment]
Should we? IMO the standard name is most important than the package.

Really suck to have a FQCN like this `HypertextApplicationLanguage.Link.hreflang = "foo"`, forces to the developer to alias the namespace always.

Also the rule is a endless story. Take a free name can be disputed later when a package with the same name is pushed.

**Comment by vvakame** [comment]
@Maks3w please check this document. http://definitelytyped.org/guides/contributing.html#naming-the-file
It only the file name is the problem.

**Comment by Maks3w** [comment]
@vvakame Done. However I suggest to review the name restriction policy.

As I said is an endless history avoid conflict with any existing or future package registered on all repositories, NPM, Bower, NuGet What's the next?

**Pull request merged**
