### PR TITLE
Delete typesVersions outside the minimum support window

### PR DESCRIPTION
**Pull request by andrewbranch**
~~I’m not sure if it was intended to have to update these every time we roll the support window, but I propose doing this at least for now while @sandersn is out so we can unblock the npm publishes.~~

Of course I can’t just bump them to 4.2; they were set lower than 4.2 on purpose. I guess deleting the versions that fall outside the support window must be standard procedure?

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bluebird ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bluebird@latest/))
was missing the following properties:
1. TypeError
1. RangeError
1. RejectionError
1. fulfilled
1. rejected

<details>
<summary>as well as these 1 other properties...</summary>
<p>pending</p>
</details>

## ffi-napi ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ffi-napi@latest/))
was missing the following properties:
1. version
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8735fea8e62a599e18a959e455d10e09ff3c277e
</p>

**Review by jakebailey — APPROVED** [review]

**Review by danez — APPROVED** [review]

**Review by forivall — APPROVED** [review]

**Review by retyui — APPROVED** [review]

**Review by defnotrobbie — APPROVED** [review]
react-blessed deletions LGTM

**Review by sandersn — APPROVED** [review]

**Comment by mrgrain** [comment]
Heads up, this package is in the dependency graph of `jest@27` and `ts-jest@27`. Expect a lot of failing builds with older TypeScript versions.

**Comment by news-manishpatel** [comment]
> Heads up, this package is in the dependency graph of `jest` and `ts-jest`. Expect a lot of failing builds with older TypeScript versions.

Yep, just hit this issue could this change be versioned differently or too late?

**Comment by sandersn** [comment]
@mrgrain
> Heads up, this package is in the dependency graph of jest and ts-jest. Expect a lot of failing builds with older TypeScript versions.

- Which package?
- How old a version of Typescript?
- What is the dependency path? I would guess that something in the chain needs to publish a patch version that pins a specific version of `@types/react-blessed` (or whichever package is the problem).

**Comment by mrgrain** [comment]
@sandersn It's `@types/babel__traverse`. Sorry for being unspecific, I didn't realise this PR affected more than one package.

From my own observation I can only say it affects TS3.9, but given the change I assume it will affect 4.1 and lower. (I'm aware of the supported versions, hence this just being a heads up.)

Dependcy graph, as below. Jest has moved on to v29 and also requires TS 4.2 so I doubt any pinning will happen over there.
```
$npm ls @types/babel__traverse
cdk-app@0.1.0 
├── @types/babel__traverse@7.18.2
├─┬ jest@27.5.1
│ └─┬ @jest/core@27.5.1
│   └─┬ jest-snapshot@27.5.1
│     └── @types/babel__traverse@7.18.2 deduped
└─┬ ts-jest@27.1.5
  └─┬ babel-jest@27.5.1
    ├─┬ @types/babel__core@7.1.20
    │ └── @types/babel__traverse@7.18.2 deduped
    └─┬ babel-preset-jest@27.5.1
      └─┬ babel-plugin-jest-hoist@27.5.1
        └── @types/babel__traverse@7.18.2
```

**Pull request merged**
