### PR TITLE
[ramda] adds more control to lensIndex

### PR DESCRIPTION
**Pull request by dimitropoulos**
The current implementation of the `lensIndex` function works great if every element in the array is the same type, but does not work so well for tuples.

Consider the following:
```ts
type First = string;
type Second = number;
type Third = boolean;

type Line = [First, Second, Third];

const lines: Line[] = [
  ['a', 1, true],
  ['b', 2, false],
  ['c', 3, true],
];

const firstLens = lensIndex(0);
const viewFirst = view(firstLens);
```

Today, the only option available is to do `lensIndex<Line>(0)` but this returns a type of `Lens<Line[], Line>` which is wrong and returns the error when we try to use the lens (e.g. `viewFirst(lines[0])`):
```
Type 'string | number | boolean' is not assignable to type 'Line'.
    Type 'string' is not assignable to type '[string, number, boolean]'.
```

And yet, our actual type is `Lens<Line, First>` (or, `Lens<Line, string>`).

If we could specify `lensIndex<Line, 0>(0)` then the problem is solved, because the type of `viewFirst` then becomes `(obj: Line) => string` instead of `(obj: Line[]) => Line` as it was before.  This PR implements that functionality.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. sequence
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 05d08d8be87ccfaaa74f488eb5d8b62ea065da95
</p>

**Review by Nicholaiii — COMMENTED** [review]
You should write some tests for the additions

**Comment by dimitropoulos** [comment]
@Nicholaiii I added a test with my use-case.  thanks.

**Review by Nicholaiii — APPROVED** [review]
LGTM

**Comment by dimitropoulos** [comment]
Ready to merge

**Pull request merged**
