### PR TITLE
Package jira-client : update to version 6.21 - added docs

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Added JSDoc for every public method

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jira-node.github.io/class/src/jira.js~JiraApi.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Worlor** [comment]
Hello @orta 
Can you check this please ?

**Comment by rkesters** [comment]
@Worlor I take a look at this tonight

**Review by rkesters — APPROVED** [review]

**Comment by rkesters** [comment]
Ready to merge

**Comment by Worlor** [comment]
Thanks @rkesters

**Pull request merged**
