### PR TITLE
chromecast-caf-receiver - Expose `player` namespace on `cast` 

### LINKED ISSUE #46169: chromecast-caf-receiver - Add type `player` to the cast namespce
**Affected Repo**
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chromecast-caf-receiver

**Version**
5.0.7

**Authors**
@brandonrisell
@craigrbruce
@Serabe

**Issue**
Currently the player instance exists on `cast` in the debugger, however, it doesn't exist as a type in the chromecast-caf-receiver
Screenshot 2020-07-18 at 17 41 28
So for example, if I need to control the log level of the player, I will have to cast the `cast` variable to `any` in order to achieve that
Screenshot 2020-07-18 at 17 42 47

 
**Solution**
Provide type `player` on `cast` along with the `LoggerLevel` enum and the `setLoggerLevel` function which can be seen in the debugger of the receiver.
Screenshot 2020-07-18 at 16 19 55

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by WafaZaidan**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46169
Tested locally and it worked 

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by WafaZaidan** [comment]
hi @Serabe @craigrbruce @brandonrisell and @weswigham, would be great to have your review on this please

**Review by Serabe — CHANGES_REQUESTED** [review]
I cannot find the documentation for cast.player / cast.player.api in https://developers.google.com/cast/docs/reference

Can you point to where this is documented?

**Comment by WafaZaidan** [comment]
@Serabe 
I wasn't able to find docs for this either but still was able to control the log level in the debugger. I have created an issue for this on Google issue tracker https://issuetracker.google.com/issues/162811283

**Comment by Serabe** [comment]
Great, let's wait for their response. I rather not add types for anything not documented as it may change or disappear at any moment.

**Pull request closed without merging**
