### PR TITLE
[simpl-schema] Add method setDefaultMessages

### LINKED ISSUE #50706: [@types/simpl-schema] missing SimpleSchema static functions and dist
`SimpleSchema` exposes a `setDefaultMessages`function that can be used to set default messages.
Also `SimpleSchema` provides a dist folder with some functions that can be extended. For example: `import regExpObj from 'simpl-schema/dist/regExp';` this import produces an error.

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #50706

Documentation: https://github.com/longshotlabs/simpl-schema#customizing-validation-messages

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I think there is limited content that can be set as messages:
```ts
type CreateFunc = (options: { label: string; regExp: string }) => string;
type MessageType = {
  [key: string]: string | CreateFunc;
};
type MessagesDict = Record<string, MessageType>;

const messages: MessagesDict = {
  en: {
    required: "{{{label}}} is required",
    // ...
    // ...
    expectedType: "{{{label}}} must be of type {{dataType}}",
    regEx({ label, regExp }) {
      return `${label} ${regExp}`;
    },
    keyNotInSchema: "{{name}} is not allowed by the schema",
  },
};
```
so each language definition can containe keys with a string or a function returning string:
https://github.com/longshotlabs/simpl-schema/blob/d440902f75d10ab05eef8fa7d189408042ac2a54/package/lib/defaultMessages.js#L19
what do you think?

**Comment by peterblazejewicz** [comment]
Sorry, that was pseudocode tested on playground only, I've forgotten about this TSLint rule about interfaces

**Comment by peterblazejewicz** [comment]
Looks ok, can you update this detail? thx1

**Comment by martin-badin** [comment]
@peterblazejewicz Thanks for your review. :)

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thx!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
