### PR TITLE
hapi: correct server.inject response type

### PR DESCRIPTION
**Pull request by jeffkenney**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: _([https://github.com/hapijs/hapi/blob/v16.1.1/API.md#serverinjectoptions-callback]())_
- [x] Increase the version number in the header if appropriate. _(correction for existing version)_
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`. _(one-liner)_

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Please address merge conflicts

**Comment by jasonswearingen** [comment]
sorry i missed reviewing this earlier, was on vacation.

**Comment by jeffkenney** [comment]
hey @RyanCavanaugh / @jasonswearingen, merge conflicts are fixed

**Comment by AJamesPhillips** [comment]
Sorry @jeffkenney I'm sure it's possible to include your commit with a cherry picking across git trees but as it's a one liner I just copied and pasted it.  Once #16065 gets into master it will have your changes too.  If there's a delay with 16065 then obviously this PR (15794) should get priority and I'll fix any merge conflict.

**Comment by jasonswearingen** [comment]
still, it would be nice if the "old" hapi definition gets the update, so plz merge DT maintainers!

👍

**Comment by AJamesPhillips** [comment]
https://github.com/AJamesPhillips/DefinitelyTyped/commit/065bbc7970cd4ac6189cba2ba155c49499901917#diff-df9df01927740f6adbf8027e55067caaL1031

@jasonswearingen it will with either PR :) Unless you meant something else?

**Comment by jasonswearingen** [comment]
@AJamesPhillips  sorry I didn't see the pull request for the rework!   yes you are right.

**Pull request merged**
