### PR TITLE
[openui5] Update definition files for OpenUI5 1.90

### PR DESCRIPTION
**Pull request by akudev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).   → _some are unavoidable at this point, see below_
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  → _no specific URL about the changes, it's just a new release_: https://openui5.hana.ondemand.com/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR brings an update for @openui5/types, which is still on a very old outdated version 1.40.

The previous definition files were done by community member @maylukas (thanks!!) who is also the sole owner of the definitions right now, but has stopped working on this project years ago. We contacted him and he confirmed that we could/should take over ownership, hence he is now being removed from the list.

We (@codeworrior, @petermuessig and me) are members of the original OpenUI5 development team, but due to the structure and ways of consumption of this JS library it is not feasible to bundle the declaration files inside, so we would like to continue to use DefinitelyTyped instead.

The definition files need to cover a 10+-years-grown API and are generated, hence not all guidelines can easily be fulfilled and not all common mistakes avoided. We are working on it and on reducing the number of disabled linting rules.
One example is the "no-any-union" rule: while it completely makes sense from pure type-checking perspective, most violations are for cases when a value of type "any" can be either _set_ or _bound_. For _setting_, "any" is needed, but for _binding_, it's still good to have the type "PropertyBindingInfo" present for documentation purposes.
Another example: the "ban-types" rule complains about type "Function": while we could enable and satisfy the rule by saying "(..any) => any|void" instead, this does not actually improve quality/type-safety. Instead, we plan to work on providing the full function signatures in those places (we have to solve an issue in JSDoc for that).

The tests from the previous definition files have been taken over and adapted as closely to the original as possible.

Two links to a "helloworld" project in the README are not working right now, but this project is already finished and about to be published in the next 2-3 days.

### CODE REVIEW

**Comment by akudev** [comment]
I'm a bit puzzled why the "No Other Owners" label and the bot say that I am [the only owner](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53680#issuecomment-856700670) when the bot also noted that [four owners are added](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53680#issuecomment-856700639).

**Comment by amcasey** [comment]
@akudev The source of truth for ownership is actually https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS, which won't be updated until after this PR merges.

**Review by amcasey — APPROVED** [review]
Thanks for the detailed explanation!  Please keep working on those lint suppressions.

**Comment by akudev** [comment]
Ready to merge

**Comment by akudev** [comment]
@amcasey: thanks for the quick approval!
We'll get rid of some of the lint suppressions, but unfortunately by far not of all.

**Pull request merged**
