### PR TITLE
openpgp: encrypt() now take a message parameter instead of data, dataType and filename.

### PR DESCRIPTION
**Pull request by damonpam**
parameter instead of data, dataType and filename.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0 (High-Level API Changes)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by errietta** [comment]
Thanks will look during the weekend

**Review by errietta — APPROVED** [review]
Looking good, 🚢 it

**Comment by amcasey** [comment]
Does this change correspond to a different version of openpgp?  If so, it might be helpful to either include a version header or maintain both versions in parallel: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by amcasey** [comment]
@damonpam the first line would usually be something like `// Type definitions for openpgp 4.0.0`

**Comment by damonpam** [comment]
@amcasey done! I thought it was another kind of change. Thanks a lot!

**Review by errietta — APPROVED** [review]

**Pull request merged**
