### PR TITLE
Add missing functions to "jexl"

### PR DESCRIPTION
**Pull request by chetbox**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/TomFrost/Jexl/blob/v2.2.2/lib/Jexl.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by chetbox** [comment]
We discovered this type definitition is missing the `.compile()` function, among others, which we require. 

`compile()` returns an `Expression` and, ideally, we'd like `Expression.prototype.getAst()` to return a fully typed object however, for now, working out a type definition for such a complex nested type seems like something that will take a little longer.

**Review by m-tomczyk — APPROVED** [review]
Looks like `Expression` and `.compile()` functionality was not documented at the time, see https://github.com/TomFrost/Jexl/commit/babf688e9bd2b54fbfb1bf4fd2ac006c93aa23e7
And it's quite significant feature.
lgtm - thanks!

**Comment by chetbox** [comment]
Thanks for the speedy review!

**Comment by orta** [comment]
Nice work on the comments. Thanks @chetbox

**Pull request merged**
