### PR TITLE
react-datepicker: Fix callback prop signatures. Type dates as moment.Moment.

### PR DESCRIPTION
**Pull request by enoshixi**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Hacker0x01/react-datepicker
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by ericanderson** [comment]
👎 
This is false. Dates do not have to be _just_ moment.Moment. In all cases they are either passed to `moment()` or after having a moment to something like `isBefore`. See: https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L25-L32

Also see: https://momentjs.com/docs/#/query/is-before/

Valid arguments are `Moment|String|Number|Date|Array`

**Comment by enoshixi** [comment]
@ericanderson I thought that also, but started looking at the source and found several places that assumes moment.Moment. For example, a bit further down in the same file: https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L50

See also a recent issue: https://github.com/Hacker0x01/react-datepicker/issues/700

So it appears that moment is required, although it may by chance work in some places with `Moment|String|Number|Date|Array`.  Unfortunately the docs are not super clear on this.

**Comment by ericanderson** [comment]
I stand corrected.

**Comment by ericanderson** [comment]
:+1: This is ready for merge

**Pull request merged**
