### PR TITLE
tappay 5.1.4 type

### PR DESCRIPTION
**Pull request by huang7017**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/tpdirect/direct-pay.d.ts
1. types/tpdirect/tpdirect-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b39012a3cb87bf2342475ad1a2a20f411a4069ed
</p>

**Comment by huang7017** [comment]
@Yu-Jack  Hello, due to some updates in Tappay's usage, your type is no longer applicable.

**Review by gabritto — CHANGES_REQUESTED** [review]
The title of this pull request mentions version 5.1.4, but these type definitions are for version 5.5: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1902c6358de8e3f2a7575de9253950a1ef6a09c4/types/tpdirect/package.json#L4

Also, please provide a link to documentation or implementation of the original project that justifies the changes in this pull request, otherwise it is hard for maintainers to review.

**Comment by huang7017** [comment]
@gabritto 

However, the latest version I obtained from the Tappay API is 5.1.4, not 5.5.
https://docs.tappaysdk.com/tutorial/en/web/front.html#setupsdk

**Comment by gabritto** [comment]
> @gabritto
> 
> However, the latest version I obtained from the Tappay API is 5.1.4, not 5.5. https://docs.tappaysdk.com/tutorial/en/web/front.html#setupsdk

Do you mean version v5.**14**.0? That's what the website mentions. If you mean to update these definitions to be compatible with version 5.14, please also update the version in the `package.json`.

**Pull request closed without merging**
