### PR TITLE
add Tycho + Ika to Ramda authors to get @'d in issues

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
I just realized people have been posting issues here, and I wasn't getting notifications to help me respond. Also adding @ikatyang, who is currently maintaining Ramda typings at https://github.com/types/npm-ramda/.

### CODE REVIEW

**Comment by ikatyang** [comment]
I'm not sure if I should be added to DT now since the types here is completely different from npm-ramda, and I'm not able to maintain two versions simultaneously.

And also it looks a little weird to me that when people ask for help in DT and we just point them to npm-ramda, which is the different repo and it doesn't look like the goal of DT, though they probably don't mind.

I think it'd be better to do types/npm-ramda#233 first. I started to work on [`ts-2.8`](https://github.com/types/npm-ramda/tree/feat/ts-2.8) recently and I'll update that PR when `ts-2.8` is done.

(I'm `Ika` not `Ika Tyang`. 😂)

**Comment by tycho01** [comment]
@ikatyang sounds like squid to me!
Anyway, updated, along with a link.

If we can push types here, that'd be great, yeah. I also wouldn't advocate double maintenance.

I just recently noticed a bunch of people are posting here that don't realize that many of their issues have already been solved elsewhere.
I figured if we know about them, it'd get easier to point them in the right direction. Until we manage to pull off a merge to here that might be the best workaround for now I guess?

I mean, I dunno how DT feels about that either, but that's why I made this PR -- to find out from them.
To me it isn't a competition, but more about helping people.
Their view is up to them, but considering no-one here is really responding to Ramda typing issues, I figure they'd appreciate the opportunity to get fewer new issues raised.

**Comment by googol** [comment]
What's the aim of the `types/npm-ramda` project btw? Why is there a parallel typings project for ramda?

**Comment by tycho01** [comment]
@googol: fair question.

afaik efforts on typing Ramda evolved from a gist by one guy into a repo by another (donnut), who burned out on it again, at which point I started contributing more.

I got push access there, but looked for a more neutral space where we could still retain a dedicated issue list (and thus repo), around which time @blakeembrey suggested we use the [Types](https://github.com/types/) org, which appeared to be a more progressive alternative to DefinitelyTyped.
We'd been promised PRs from the Types org to DT would go from manual to automated with the advances proposed in https://github.com/Microsoft/types-publisher/issues/4, though that ended up not gaining traction.

It wasn't so much the intention to distance the effort from DefinitelyTyped -- I'll agree end users shouldn't have to think about where to get their types.
Even so, adjusting to some of the Types conventions inadvertently led to a few differences that got us further away from conforming to DT's CI, currently tracked at https://github.com/types/npm-ramda/issues/191, though no-one's been actively working on it recently.

I apologize for the inconvenience and confusion caused there -- that's mostly on me.

Dedicated issue list aside though, we've also appreciated being able to use branches, which would become more complicated in DT.

This library is relatively tough to type (think properly typed currying, function composition, [deep object navigation](https://github.com/Microsoft/TypeScript/issues/12290)), and as such, we've had branches for trade-offs in customization vs simplicity (placeholder [`R.__`](http://ramdajs.com/docs/#__) support, explicit overloads), for our code generation (mostly needed to handle currying and placeholders), and TypeScript versions (e.g. what's possible in the latest version vs. what those in front-end frameworks are stuck with).

For typing tougher libraries, I'd be at a loss as to how to properly handle things like that in a mono-repo like DT. And if that sounded overkill, in my view we've yet to achieve the intended UX, as quite some cases (esp. function composition) still require manual type hints.

I hope that helps give some background -- I'd love to see some more of these gaps bridged as well.

**Comment by googol** [comment]
Thanks for the great response @tycho01.

While I think it's a shame there's a split like this in the typings, it's great that it's used for properly useful features and experimentation that DT is unable to supported.

I know many of my collegues maintain custom typings for ramda (adding lots of overhead). , as it is very powerful but lacking somewhat in the DT typings. I hope there's opportunities for bringing more of the advanced features to DT too.

**Comment by tycho01** [comment]
a DT update to TS 2.9 broke things, now the bots here blame me?

**Comment by googol** [comment]
Ok so it seems this died. If you'd like you can rebase and make a new pr. If I'm not mistaken the fix for the build error this branch experienced has been merged. (Could you squash the commits in the branch too while rebasing?) 

IMO it's ok to add you to the authors, but I wasn't sure if @ikatyang is ok with being added here though. Also I think the comment about crossposting issues is confusing, I'd rather not have that added.

**Comment by tycho01** [comment]
okay. I made #25660 now, if @ikatyang want in maybe they can do a similar PR then. until then maybe I can respond to issues with this.

**Pull request closed without merging**
