### PR TITLE
fix(d3-fetch):  update signatures and expand JSDoc comments

### LINKED ISSUE #23253: [d3-fetch] Add definitions for d3-fetch (Required for D3v5)
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @LeDragon @gustavderdrache 

I just looked at the release notes for the RC1 of D3 Version 5. **d3-fetch** will be added in as a replacement for **d3-request**.

So we'll need definitions for it proactively for D3 v5.

### PR DESCRIPTION
**Pull request by tomwanzek**
* fix(image): init object is not request init, but rather initializes image element properties
* fix(json): add generic parameter to allow return type casting
* fix(csv, dsv, tsv): overload signatures to be more specific about return type (with or without row parsing function).
* fix(csv, dsv, tsv): update row parsing function signature to be in line with parser signature in d3-dsv, which is called under the hood.
* chore(tslint): add tslint rules to allow signature overloading and single-use generic
* doc(*) Expand JSDoc comments
* chore(tests): update tests

@Ledragon The signatures are now split out, which achieves two things in line with what you likely already saw in the source code:
* without `row` parser functions the `*sv` fetchers are returning all row objects with `string` properties
* we are not forcing the submission of a possibly spurious `init` object anymore when a user wants to pass in a `row` parser for the `*sv` fetchers

I amended to tslint to support this behaviour as it seems the unified signatures rule was counterproductive here and we are definitely not running into any issues with union type arguments being split across signatures.

Closes #23253

cc @gustavderdrache fyi.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-fetch>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@Ledragon not sure, why the DT bot did not pick you up as the owner of the definition?

**Comment by Ledragon** [comment]
Don't know either, I also never get mentioned as reviewer on `d3-geo`...
Anyhow this looks awesome to me, you achieved what I wanted on `json` (I guess I need to learn more about tsconfig options :p ), and split the overloads only where required (it indeed makes less sense when the return types for all overloads are the same). Plus your augmentation of the docs is great!

**Review by Ledragon — APPROVED** [review]

**Comment by tomwanzek** [comment]
Yep, as far as the `tslint.json` rules go, we ran into the `unified signatures` and a couple of similar issues on other D3 modules before. [Here](https://github.com/Microsoft/dtslint/tree/master/docs) is a great reference  source for the dtslint rules, you might have to play with. In fairness, as far as I recall this is also the only D3 module, which under the hood allows the flexibility to have two different second arguments (`init` vs `row`) depending on the signature. Unless, we have been too conservative in other cases with enforcing argument position 🤔

**Comment by tomwanzek** [comment]
As for your owner status, I never noticed it on `d3-geo`. `d3-fetch` is the first time that I saw that the bot did not pick you up. On NPM you are always listed as a maintainer.

My guess: your github handle is `Ledragon` and the the definitions we have you as `ledragon`. Maybe just in that case it is a case-sensitivity issue?

We should check it with  however merges this PR.

**Comment by Ledragon** [comment]
I think I get mentionned on `d3-geo`, but not as a reviewer (in the right column of the PRs). But that's fine, I still get notified when changes occur (generally by you at least :-) ). You might be right about the case sensitivity stuff, I will submit a pr to update it after this one gets merged
Thanks for the heads up on rules for for dtslint, I will try and check this out (someday, maybe...)

**Pull request merged**
