### PR TITLE
Update react-router definitions to 3.0.x and react-router-redux to 4.0.x

### PR DESCRIPTION
**Pull request by LKay**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ReactTraining/react-router/blob/v3.0.2/CHANGES.md
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mhegazy** [comment]
some merge conflicts.

**Comment by LKay** [comment]
@mhegazy I know, fixing it right now. Looks like yesterday some PR fixing linter for v2 was merged. I'm gonna apply this to my branch soon.

**Comment by andy-ms** [comment]
Hi, the error message (`react-breadcrumbs has unused path mapping for history`) is misleading. The real problem is that `react-breadcrumbs` currently depends on `react-router`, so it needs a path mapping to the old version.
So its `tsconfig.json` should be have:
```json
"paths": {
    "history": ["history/v2"],
    "react-router": ["react-router/v2"]
},
```

And it needs to be rewritten in external module style to make use of path mapping. Like so:

```ts
// Type definitions for react-breadcrumbs 1.3
// Project: https://github.com/svenanders/react-breadcrumbs
// Definitions by: Kostya Esmukov <https://github.com/KostyaEsmukov>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as React from "react";
import * as ReactRouter from "react-router";

export = Breadcrumbs;
interface Breadcrumbs extends React.ComponentClass<Breadcrumbs.Props> {}
declare const Breadcrumbs: Breadcrumbs;

declare namespace Breadcrumbs {
    interface Props extends React.Props<Breadcrumbs> {
        separator?: string | JSX.Element;
        displayMissing?: boolean;
        prettify?: boolean;
        displayMissingText?: string;
        displayName?: string;
        breadcrumbName?: string;
        wrapperElement?: string;
        wrapperClass?: string;
        itemElement?: string;
        itemClass?: string;
        customClass?: string;
        activeItemClass?: string;
        excludes?: string[];
        hideNoPath?: boolean;
        routes: ReactRouter.Router.RouteConfig;
        setDocumentTitle?: boolean;
        params?: any;  // todo make it compatible with params of the ReactRouter.RouteComponentProps<P, R>
    }
}
```

**Comment by LKay** [comment]
@andy-ms, @mhegazy I followed https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version and updated all libraries that depend on older version of `react-router` updated `tsconfig.json` files seem to be correct, yet for some reason updated typing try to resolve `history` in old `v2` version instead of the currently up to date one. Can you check and tell me what I'm doing wrong? Tried to play around with path mapping in config but none of the configurations worked.

**Comment by andy-ms** [comment]
You are referring to this error?

```
Error in react-router-redux v3

Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.1/node_modules/typescript/lib/tsc.js 

../../react-router/lib/Router.d.ts(4,5): error TS2305: Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/history/v2/index"' has no exported member 'Hash'.
```

Notice that `react-router-redux/v3` is still depending on `react-router` latest.
To fix this, you need to add a path mapping in `react-router-redux/v3/tsconfig.json` of `"react-router": ["react-router/v2"],`. Also, remove the `reference types` lines from its tests; they aren't needed anyway, and don't play nice with path mapping.

**Comment by LKay** [comment]
@andy-ms Well, I did but the travis tests are still failing. Actually the typings themselves are not depending on any types defined in `react-router/v2` just tests import something from `react-router` maybe this is the source of the problem as tests assume if library is not used in typings the treat path mapping as not necessary?

**Comment by andy-ms** [comment]
Hm, this isn't something the tester is prepared for. If there is a path mapping it will create a dependency, but we don't want that if a dependency is not actually needed. Could you remove the dependence  on `react-router` from the tests, then remove the path mapping?

**Comment by LKay** [comment]
@andy-ms Alright, I removed this from tests and also added necessary path mapping to yet another definitions. Test are finally passing.

**Comment by olmobrutall** [comment]
Any news on this PR? I need this to get merged to move forward with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14346

**Comment by jbrantly** [comment]
Was using some of these in advance of them being merged and find a minor quibble (although the issue existed in the previous typing as well). For `match`, the location is actually optional. The react-router docs are slightly wrong in this regard. Take a look at https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/match.js#L20-L22

Also, +1 for getting this merged soon

**Comment by LKay** [comment]
@jbrantly You're right, nice catch! I added another function signature to match address this case. 

Honestly, I always used `match` providing `Location` object so never checked actual code for this function too carefully.

**Comment by olmobrutall** [comment]
What about the dependency to History 3? Out of the scope of this PR?

**Comment by bowdenk7** [comment]
We'll take a separate PR for that change. Thanks everyone!

**Pull request merged**
