### PR TITLE
@types/tizen-tv-webapis: fix typings getCurrentStreamInfo and getTotalTrackInfo

### PR DESCRIPTION
**Pull request by hcodes**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by hcodes** [comment]
https://developer.samsung.com/smarttv/develop/api-references/samsung-product-api-references/avplay-api.html
See example for getCurrentStreamInfo. This method returns array.
```js
var StreamInfo = webapis.avplay.getCurrentStreamInfo();
var Text = '';
for (var I = 0; I < StreamInfo.length; I++) 
{
  Text += 'index: ' + StreamInfo[I].index + '';
  Text += 'type: ' + StreamInfo[I].type + '';
  Text += 'extra_info: ' + StreamInfo[I].extra_info + '';
}
//All streams have extra_info as a JSONString.
//video extra_info example : "{fourCC:"H264","Width":"1920","Height":"1080","Bit_rate":" 477000"}"
//audio extra_info example : "{"language":"eng","channels":"2","sample_rate":"44100","bit_rate":"96000","fourCC":"AACL"}"
//text(subtitle) extra_info example : "{"track_num":"0","track_lang":"eng","subtitle_type":"-1","fourCC":"TTML"}"
//If the stream is invalid, the DOMString is null and the index value is -1.
```

The same is with the method  getTotalTrackInfo()

**Comment by hcodes** [comment]
I checked it on real TV with Tizen.

**Review by SejoongDeJang — APPROVED** [review]
@hcodes  Thanks to fix it!

**Comment by hcodes** [comment]
Ready to merge

**Pull request merged**
