### PR TITLE
[@tabulator-tables] updated the return value of getData on the CellComponent to any

### PR DESCRIPTION
**Pull request by atebeta**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Note i was unable to run the tests due to #67921 - but i only changed '{}' to 'any' so its a small change. 

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://tabulator.info/docs/5.5/components#component-cell)>>
- Note that this is the return value given by all of the other getData functions.
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by mike-lischke** [comment]
The documentation explicitly says the method returns a "data object"

```
var data = row.getData(); //get data object for row
```

which makes me think this the object you have to specify for that row (which must be an object to make it work). What makes you think it could be, say, a number or a string (which would be possible, when you change the result to `any`)?

**Comment by atebeta** [comment]
> The documentation explicitly says the method returns a "data object"
> 
> ```
> var data = row.getData(); //get data object for row
> ```
> 
> which makes me think this the object you have to specify for that row (which must be an object to make it work). What makes you think it could be, say, a number or a string (which would be possible, when you change the result to `any`)?

if you look at the other definition for the getData() function which also returns a data object (ie for the CalculationComponent) it returns 'any'.

Doing cell.getData() returns the same data as row.getData() (RowComponent is an extension of the CalculationComponent)

The reason why i changed it was because i was getting an error when it was returning {} when i was trying to access a key on the data object: Property 'xxxx' does not exist on type '{}'.
 
So its not so much about it being possibly a string or a number, but being able to access the keys of the object without having the shape predefined.

So to conclude, i changed it to 'any' to make it consistent with the other getData properties defined and in order to access properties not specifically defined in the definition.

**Comment by Jojoshua** [comment]
What if we started using **_unknown_** instead of {} and any?

**Comment by atebeta** [comment]
Wouldn't it make more sense to use `{ [key: string]: any; }` in that case?

**Comment by Jojoshua** [comment]
> Wouldn't it make more sense to use `{ [key: string]: any; }` in that case?

No, using unknown is more flexible. It's a step up from any. Typescript will still force you to type your object when you try to access properties.

**Comment by mike-lischke** [comment]
While `unknown` is way better than `any` it's still not in line with the documentation. Also `unknown` would allow primitive types, while the docs say it's an object. Using an object with an index signature is probably the better choice (like @atebeta suggested).

**Comment by Jojoshua** [comment]
> While `unknown` is way better than `any` it's still not in line with the documentation. Also `unknown` would allow primitive types, while the docs say it's an object. Using an object with an index signature is probably the better choice (like @atebeta suggested).

We've seen where the project documentation is inconsistent and lacking. Sometimes it says the method returns one thing but it actually return multiple possible things/types. It did specifically say object in this case but wasn't specific in the other getData()'s. That's why those were set to `any`...and `unknown `didn't exist at the time of authoring.

It seems the choice is one of either,,,

#### Consistency 
- If only wanting to address table.getData(), then we'll not be consistent.
- If the goal is to be consistent (change all uses of `any`),  `unknown `is a better choice overall than `any` because I don't know that we can replace all instances of `any` with `{ [key: string]: any; }`. 

#### Strong Typing
- `unknown` is better at forcing type safety
- `{ [key: string]: any; }` is better than `any `but it's worse than `unknown `because you're still going to be allowed to use a property from the object regardless of if it actually exists and can cause runtime errors

#### Reality
-  The actual source code of table.getData() just returns `[]`

**Comment by atebeta** [comment]
So far I have only been referring the `getData()` functions on the CellComponent and RowComponents. Those both return objects where the key is a string and the value can be any.

`getData()` on the Table will return an array of objects, where each object is equivalent to what you would get if you did 'getData()' on the CellComponent or the RowComponent.

I don't really care that much. The only reason I made the pull request was that I was getting an error when the definition was set to return {} even though I had typed the object and it should have known the key I was trying to access was on the object returned by `cell.getData()` . If unknown fixes that problem great, but I would say for the Row and Cell Components `getData()` will always return an object so to me putting it as `unknown` doesn't seem correct.

**Comment by mike-lischke** [comment]
Looks like the object with index signature is the right choice, as it represents reality 🤷‍♂️, which should be the primary requirement.

**Comment by Jojoshua** [comment]
I'm OK with the index signature, should it also apply to the CalculationComponent?

**Comment by atebeta** [comment]
Yes, the calculation component is a subset of the row component. It will return an object where the key is the value of the field property for the column and the value is the result of the calculation to be performed on that column (ie total, average, or some custom function).

**Comment by mike-lischke** [comment]
@atebeta are you going to change the PR to use an object with index signature, as we discussed?

**Comment by atebeta** [comment]
Sorry - yes will do it tomorrow.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/tabulator-tables/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7638b8d55b4c0b6b948b1c4300a3de1a94e5fac5
</p>

**Review by mike-lischke — CHANGES_REQUESTED** [review]
Please revert all format changes.

**Comment by atebeta** [comment]
> Please revert all format changes.

sorry - formatting should be correct now.

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
ready to merge

**Pull request merged**
