### PR TITLE
Remove chartjs in favor of chart.js

### LINKED ISSUE #12134: "chartjs" is invalid package
- [x] I want to talk about `chartjs/chart.d.ts` and `chart.js/chart.js.d.ts`
  - The authors of that type definition are cc/ @Steve-Fenton @anuti 

I think that `chartjs/chart.d.ts` is declaration file of old version Chart.js (v1.x.x) which is not used at present. Now, 2.3.0 is the latest version and its declartion file is created in `chart.js/chart.js.d.ts` differently.

Also, I think `chartjs` is a name of the other package ([this](https://www.npmjs.com/package/chartjs)) so that this is invalid.

Can I create pull request of removing `chartjs/chart.d.ts`?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #12134
`chartjs` provides types for the same packages as `chart.js`, which on NPM is named `chart.js`. CC @FanaHOVA @JeroenDragt
Looking at the commit history `chart.js` is much more popular than `chartjs`, so I'll just assume that its types are more accurate.
If this is merged, I will run `npm deprecate @types/chartjs "'@types/chartjs' is now '@types/chart.js'"`.

### CODE REVIEW

**Comment by FanaHOVA** [comment]
@andy-ms looks like the other definitions are more updated, but also not sure if they will work as a replacement for the ones we are removing. Any way to test that? Maybe run the current test suite against the other definitions?

**Review by paulvanbrenk — CHANGES_REQUESTED** [review]
See comment by @FanaHOVA

**Comment by andy-ms** [comment]
@FanaHOVA It looks like `chartjs` may be for an earlier version of the library? (The version number is missing in the header.) The newer one doesn't seem to have a `.Line`, `.Bar., `.Radar`, etc. methods on `Chart`.

**Comment by mhegazy** [comment]
@andy-ms please merge and run the depreciation script.

**Comment by andy-ms** [comment]
Ran deprecation script.

**Comment by FanaHOVA** [comment]
@andy-ms yup, so I'm assuming old versions are unsupported now that this is merged?

**Comment by andy-ms** [comment]
@FanaHOVA It should still be possible to install the old `chartjs` -- you will see a deprecation message but installation should still succeed.
If you want to maintain types for an old version of the package on DefinitelyTyped it would also be possible to create a `chart.js/v0` or `chart.js/v1` directory containing those typings, similar to `node/v0`.

**Pull request merged**
