### PR TITLE
[Material-UI] Move icon to svg-icons.d.ts file

### PR DESCRIPTION
**Pull request by isman-usoh**
- move icon to svg-icons.d.ts file.
- generate svg-icons.d.ts
- add prepareStyles function to MuiTheme.
- update utils/withWidth module.

Generator 
https://github.com/isman-usoh/mui-icon-type-generator

### CODE REVIEW

**Comment by mhegazy** [comment]
@ngbrown @herrmanno can you please review?

**Comment by ngbrown** [comment]
@isman-usoh Thanks for sharing the generator.  I'm good with this :+1:.

**Comment by ngbrown** [comment]
@isman-usoh can you include the generator in a subdirectory of these type definitions?

**Comment by andy-ms** [comment]
This needs to be made merge-able.

**Comment by andy-ms** [comment]
@isman-usoh Please make a new PR if you still want to do this.

**Pull request closed without merging**
