### PR TITLE
google-cloud__pubsub - Added publish message attributes definition as attributes in publish() method can only have string-like values

### PR DESCRIPTION
**Pull request by msiviero**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/googleapis/nodejs-pubsub/issues/177
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by pheromonez** [comment]
If the `Attributes` interface is used exclusively for the `Publisher` class could we move it inside the `Publisher` namespace? I think that would help to keep the top-level namespace clean.

**Comment by pheromonez** [comment]
Also, I noticed that the URL for the project in `index.d.ts` now returns a 404 error. Would you mind updating the project URL as part of this PR? (https://github.com/googleapis/nodejs-pubsub)
Sorry for the trouble!

**Comment by msiviero** [comment]
@pheromonez Updated PR following your advices

**Review by pheromonez — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
