### PR TITLE
express-validator.d.ts updates

### PR DESCRIPTION
**Pull request by EricByers**
#### Changes
- Added `checkBody`, `checkParams`, `checkQuery`, `checkHeader`, `checkFiles`, `filter`, `check`, `validate` to `RequestValidation`
- Split internal/external modules apart because...
- This now extends `Express.Request` to add on `ExpressValidation.RequestValidation`.
- Since there was not a test file, I added a very basic test for now that handles the Express Request object and a a few of the sanitize/validate interface pieces.

Let me know if there are any concerns or something I missed.  Thanks!

### CODE REVIEW

**Comment by vvakame** [comment]
*express-validator/express-validator.d.ts*

to authors(@axefrog @dreampulse). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by EricByers** [comment]
@vvakame How do I proceed from here?  It doesn't look like @axefrog @dreampulse have weighed in.

Also, in the time that this has been sitting a different PR went through and made some of the same updates -- https://github.com/borisyankov/DefinitelyTyped/pull/4168 -- I've merged that in and fixed the conflicts.  I feel this branch still provides value since it adds the interface on to the Express.request, allowing you to use multiple express middlewares.  Thanks!

**Comment by vvakame** [comment]
@EricByers okey, I decided to merge this PR.

if @axefrog @dreampulse and @JacobDanton has any improvement. please send a new PR.

**Comment by dreampulse** [comment]
Sorry, i'm a little bit late. But the PR seems fine to me

**Pull request merged**
