### PR TITLE
Add typings for the W3C Credential Management (Level 1) API

### PR DESCRIPTION
**Pull request by iainmcgin**
This specification is still "draft", but is implemented in Chrome.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

### CODE REVIEW

**Comment by vvakame** [comment]
sorry for late.
@DefinitelyTyped/contributors can anyone review this PR?

**Comment by DanielRosenwasser** [comment]
Considering that we pulled in #11459 which is pretty similar in spirit, I think we can pull this in.

**Comment by andy-ms** [comment]
If we're not putting it in `lib.d.ts` yet, we can publish it as `@types/webappsec-credential-management` and deprecate it once it's in `lib.d.ts`.

**Comment by iainmcgin** [comment]
Thank you all, have a great holiday.

**Pull request merged**
