### PR TITLE
[prettier] Add tests for plugin options, convert oppositeDescription to string

### PR DESCRIPTION
**Pull request by EliteMasterEric**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/prettier/prettier/blob/12bddae20c0bd6c31c53ec44656868f21ec5aca7/src/common/common-options.js#L13

### CODE REVIEW

**Comment by MasterEric** [comment]
The `oppositeDescription` option is a string which is used when defining a boolean option. If defined, a corresponding inverse option, with the name `--no-<option>`, will be added which sets the option to false when passed as an argument to prettier. The string passed to `oppositeDescription` is used as the description of that new option.

It makes no sense for `oppositeDescription` to be a boolean, or to have been a boolean at any point, since it provides a text description for an option. This is confirmed by the source code linked above, which uses the option as a string.

**Review by thorn0 — APPROVED** [review]

**Comment by ffflorian** [comment]
@MasterEric thanks! Could you please add a test?

**Comment by MasterEric** [comment]
> @MasterEric thanks! Could you please add a test?

Prettier options, of which there is different validation for each of the eight subtypes and thus desperate need for a test to validate their type definitions, previously had no test for typing.

I have now added a commit which implements tests for all options parameters, including the `oppositeDescription` property which needed modification earlier. @ffflorian I hope this PR is to your liking now.

@thorn0 You will need to re-approve the additional changes but hopefully there's no problems with these additions.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## prettier ([<kbd>unpkg</kbd>](https://unpkg.com/browse/prettier@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'prettier'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. re
1. src
1. t
1. tildeTrimReplace

<details>
<summary>as well as these 299 other properties...</summary>
<p>caretTrimReplace, comparatorTrimReplace, outdent, apiDescriptor, supportsColor, commonDeprecatedHandler, commonInvalidHandler, levenUnknownHandler, createSchema, Schema, AliasSchema, AnySchema, ArraySchema, BooleanSchema, recordFromArray, mapFromArray, createAutoChecklist, partition, isInt, comparePrimitive, normalizeDefaultResult, normalizeValidateResult, normalizeDeprecatedResult, normalizeTransferResult, normalizeForwardResult, normalizeRedirectResult, ChoiceSchema, NumberSchema, IntegerSchema, StringSchema, defaultDescriptor, defaultUnknownHandler, defaultInvalidHandler, defaultDeprecatedHandler, normalize, Normalizer, matchToToken, isIdentifierStart, isIdentifierChar, isIdentifierName, isReservedWord, isStrictReservedWord, isStrictBindOnlyReservedWord, isStrictBindReservedWord, isKeyword, shouldHighlight, getChalk, codeFrameColumns, posix, win32, SEMVER_SPEC_VERSION, parse, valid, clean, SemVer, inc, diff, compareIdentifiers, rcompareIdentifiers, major, minor, patch, compare, compareLoose, rcompare, sort, rsort, gt, lt, eq, neq, gte, lte, cmp, Comparator, Range, toComparators, satisfies, maxSatisfying, minSatisfying, minVersion, validRange, ltr, gtr, outside, prerelease, intersects, coerce, minimatch, parseSync, parseString, parseFromFiles, parseFromFilesSync, flatten, splitWhen, isEnoentCodeError, createDirentFromStats, unixify, makeAbsolute, escape, removeLeadingDotSegment, isInteger, find, exceedsLimit, escapeNode, encloseBrace, isInvalidBrace, isOpenOrClose, reduce, isObject, hasRegexChars, isRegexChar, escapeRegex, toPosixSlashes, removeBackslashes, supportsLookbehinds, isWindows, escapeLast, removePrefix, wrapOutput, isStaticPattern, isDynamicPattern, convertToPositivePattern, convertToNegativePattern, isNegativePattern, isPositivePattern, getNegativePatterns, getPositivePatterns, getBaseDirectory, hasGlobStar, endsWithSlashGlobStar, isAffectDepthOfReadingPattern, expandPatternsWithBraceExpansion, expandBraceExpansion, getPatternParts, makeRe, convertPatternsToRe, matchAny, merge, isString, isEmpty, array, errno, fs, path, pattern, stream, string, generate, convertPatternsToTasks, getNegativePatternsAsPositive, groupPatternsByBaseDirectory, convertPatternGroupsToTasks, convertPatternGroupToTask, read, FILE_SYSTEM_ADAPTER, createFileSystemAdapter, Settings, stat, statSync, IS_SUPPORT_READDIR_WITH_FILE_TYPES, readdirWithFileTypes, readdir, scandir, scandirSync, isFatalError, isAppliedFilter, replacePathSegmentSeparator, joinPathSegments, walk, walkSync, walkStream, DEFAULT_FILE_SYSTEM_ADAPTER, ast, code, keyword, extract, strip, parseWithComments, print, $EOF, $BSPACE, $TAB, $LF, $VTAB, $FF, $CR, $SPACE, $BANG, $DQ, $HASH, $$, $PERCENT, $AMPERSAND, $SQ, $LPAREN, $RPAREN, $STAR, $PLUS, $COMMA, $MINUS, $PERIOD, $SLASH, $COLON, $SEMICOLON, $LT, $EQ, $GT, $QUESTION, $0, $7, $9, $A, $E, $F, $X, $Z, $LBRACKET, $BACKSLASH, $RBRACKET, $CARET, $_, $a, $b, $e, $f, $n, $r, $t, $u, $v, $x, $z, $LBRACE, $BAR, $RBRACE, $NBSP, $PIPE, $TILDA, $AT, $BT, isWhitespace, isDigit, isAsciiLetter, isAsciiHexDigit, isNewLine, isOctalDigit, StaticSymbol, StaticSymbolCache, dashCaseToCamelCase, splitAtColon, splitAtPeriod, visitValue, isDefined, noUndefined, ValueTransformer, SyncAsync, error, syntaxError, isSyntaxError, getParseErrors, escapeRegExp, utf8Encode, stringify, resolveForwardRef, isPromise, Version, global, sanitizeIdentifier, identifierName, identifierModuleUrl, viewClassName, rendererTypeName, hostViewClassName, componentFactoryName, CompileSummaryKind, tokenName, tokenReference, CompileStylesheetMetadata, CompileTemplateMetadata, CompileDirectiveMetadata, CompilePipeMetadata, CompileShallowModuleMetadata, CompileNgModuleMetadata, TransitiveCompileNgModuleMetadata, ProviderMeta, templateSourceUrl, sharedStylesheetJitUrl, ngModuleJitUrl, templateJitUrl, ParseLocation, ParseSourceFile, ParseSourceSpan, EMPTY_PARSE_LOCATION, EMPTY_SOURCE_SPAN, ParseErrorLevel, ParseError, typeSourceSpan, r3JitTypeSourceSpan</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2f944094790189d6efb0bbb9fdf93fe0a3a5c2a2
</p>

**Review by ffflorian — APPROVED** [review]

**Comment by ffflorian** [comment]
Thanks for the extra work! Well done.

**Review by Shinigami92 — APPROVED** [review]

**Review by ffflorian — APPROVED** [review]

**Comment by ffflorian** [comment]
What's going on here? @Shinigami92 and I already approved.

**Comment by Shinigami92** [comment]
> What's going on here? @Shinigami92 and I already approved.

I don't know :slightly_frowning_face:  
Maybe the bot is sick? Maybe we didn't care enough and they need a little bit more love :heart:

**Comment by ffflorian** [comment]
@RyanCavanaugh the bot is misbehaving :)

**Comment by MasterEric** [comment]
@ffflorian @Shinigami92 The first message on this PR, maintained by the bot, reads:

> Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

This is despite approval from multiple definition owners. Ideally this could get merged quickly but I don't know how to reach a maintainer.

**Review by orta — APPROVED** [review]
Looks good to me

**Comment by orta** [comment]
For super popular packages like prettier an admin needs to give a thumbs up, even for tiny changes like these, you never know how the ecosystem can be affected at this scale. 

You can see the bot message saying so above:

image

**Comment by ffflorian** [comment]
Ah, right, thanks for the explanation @orta!

**Comment by MasterEric** [comment]
@orta Thanks for the review!

**Comment by MasterEric** [comment]
Ready to merge

**Pull request merged**
