### PR TITLE
Define proper jqLite interface instead of JQuery

### LINKED ISSUE #2734: angular-protractor: conflict with JQuery
I'm seeing the following conflict when using Protractor with JQuery. 

```
Subsequent variable declarations must have the same type.  
Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.
Web\Scripts\typings\jquery\jquery.d.ts   3936
```

I tried to uninstall JQuery, but  'angularjs.TypeScript.DefinitelyTyped 2.0.6 depend(s) on it.

I'm using the following version:

```
<package id="angularjs.TypeScript.DefinitelyTyped" version="2.0.6" targetFramework="net45" /
<package id="angular-protractor.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
<package id="jquery.TypeScript.DefinitelyTyped" version="1.3.8" targetFramework="net45" />
```

Thanks
Jay

### LINKED ISSUE #3528: Remove dependency to jQuery from angular
In the first lines of angular.d.ts there's this line:

```
/// <reference path="../jquery/jquery.d.ts" />
```

jQuery is optional for angular to work, and many run without it, because you might not need it.

If I remove its typing file, I got

```
Error   24  Incorrect reference: file "...\typings\jquery\jquery.d.ts" does not exist
```

Would it be possible to make it optional also in its typing?

For instance, when not using jQuery, interface for angular.element() would offer methods that aren't available and even some that don't fulfill the same signature.

I propose to have IAugmentedJQuery not extend JQuery but jqLite interface. For those using jQuery,it could extend current IAugmentedJQuery in another .d.ts.

What do you think?

PS: it could solve #2734, conflict with protractor, that defines a '$' symbol too.

### PR DESCRIPTION
**Pull request by awerlang**
Closes #2734
Closes #3528

Calling angular.element(), when jQuery is not loaded, returns a jqLite instance, a stripped-down version of jQuery. It has fewer methods and some of them do not handle the same parameters as jQuery would.

A jqLite object is never an augmented jQuery object, as it is implied today. They are mutually exclusive.

As a result, no dependency on JQuery anymore. This has the benefit of avoiding conflict with protractor, which also defines a $ symbol.

### CODE REVIEW

**Comment by nojaf** [comment]
Any updates on this? Why can't this be merged?

**Comment by vvakame** [comment]
I'm inclined to say "no". I think angular.js user uses real jQuery object. It can use jQuery plugin methods.
why do you want to use angular.d.ts and protractor.d.ts in the same time?

@basarat what do you think?

**Comment by basarat** [comment]
I agree with @vvakame. 

If we merge this than more people will complain of breaking there code (where they depend on `element` returning `JQuery`).

> A jqLite object is never an augmented jQuery object, as it is implied today

it is. See https://github.com/angular/angular.js/blob/9e8a687c370297688d59bcfa430d2142255302b6/src/jqLite.js#L87 I am sure you know this and I am probably quoting out of context, just wanted to be clear.

> Calling angular.element(), when jQuery is not loaded, returns a jqLite instance, a stripped-down version of jQuery. It has fewer methods and some of them do not handle the same parameters as jQuery would.

That is true. But we don't have a good solution that can exist in a single definition (A solution would be to split into `ngWithouJQuery` but I *strongly* advise against it).

We love the effort you have put in this and hate to reject it but afraid that merging might do more harm to decrease the barrier for entry into TypeScript / Angular.

**Comment by Sebazzz** [comment]
This is no longer relevant right, with Union types?

**Pull request closed without merging**
