### PR TITLE
Added module getmac,z85 & Correction for module nock

### PR DESCRIPTION
**Pull request by 0815fox**
- z85 based on what i gathered from their documentation (https://www.npmjs.com/package/z85)
- getmac based on what i gathered from their documentation (https://www.npmjs.com/package/getmac)
- nock: as of https://github.com/node-nock/nock#specifying-path not only string arguments are allowed, but also regex and filter functions

### CODE REVIEW

**Comment by vvakame** [comment]
wow lot of changes occured. please exec rebase, squash and `push -f`.

**Comment by vvakame** [comment]
https://help.github.com/articles/using-git-rebase/

**Comment by 0815fox** [comment]
Sorry for bothering you. The provided link did not help me at all. Here's the story of all I did (as a complete git beginner):
1. I forked this repo to add modules I was missing definitions for (https://help.github.com/articles/fork-a-repo/)
2. I made my changes and before sending out the pull request, I synced it with upstream (https://help.github.com/articles/syncing-a-fork/)
3. I committed that and sent out a pull request.
4. I was requested to "exec rebase, squash and push -f" which I did not understand.
5. Now, some weeks later, I think I have to sync from upstream again, but it gives me conflicts in files which I did not even modify. Probably they changed on upstream since my previous pull. But why does git not notice, that I did not modify them?
6. Trying the rebase command and I actually do not know what I really do. Reading the article @vvakame suggested (https://help.github.com/articles/using-git-rebase/) did not help me. It does not explain, what the argument `Head~7` means in their example and what I have to write there instead.
7. Now I am stuck and do not know how to get forwards nor backwards. I came like into an endless loop, still not knowing what I am actually doing, because I do not know why I have those conflicts.
```
$ git status
rebase in progress; onto 9048d22
You are currently rebasing branch 'master' on '9048d22'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   material-ui/material-ui.d.ts

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:      material-ui/material-ui-tests.tsx

$ git checkout --theirs material-ui/material-ui-tests.tsx
$ git add . -A
$ git commit --amend -m "Take theirs"
[detached HEAD b2f102f] Take theirs
 Author: Nathan Brown <nathan@nkbrown.us>
 2 files changed, 8397 insertions(+), 15958 deletions(-)
 rewrite material-ui/material-ui-tests.tsx (90%)
 rewrite material-ui/material-ui.d.ts (65%)
mk@mk-actifsource:~/work/4.5.1/workspace2/DefinitelyTyped/DefinitelyTyped$ git status
rebase in progress; onto 9048d22
You are currently editing a commit while rebasing branch 'master' on '9048d22'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working directory clean
mk@mk-actifsource:~/work/4.5.1/workspace2/DefinitelyTyped/DefinitelyTyped$ git rebase --continue
error: could not apply a0655e2... Sort all the parameters like the documentation.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply a0655e2acf23eb61915f7927da20fd1e75906fa4... Sort all the parameters like the documentation.
mk@mk-actifsource:~/work/4.5.1/workspace2/DefinitelyTyped/DefinitelyTyped$ git status
rebase in progress; onto 9048d22
You are currently rebasing branch 'master' on '9048d22'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:      material-ui/material-ui.d.ts

no changes added to commit (use "git add" and/or "git commit -a")
```

Actually I am feeling like an idiot now, because everyone says git is so good and easy.

**Comment by 0815fox** [comment]
So I got a suggestion on StackExchange (http://stackoverflow.com/questions/38050756/conflicts-after-merge-from-master-multiple-times) - I will try that soon.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
