### PR TITLE
[sortablejs] adds all options, plugins and mount function

### PR DESCRIPTION
**Pull request by waynevanson**
## Details 
+ All the options available on Sortable have been added.
+ Added `Sortable.mount()` with tests
+ Added a plugin base class
+ Added AutoScroll, MultiDrag, OnSpill and Swap plugins 
+ Changed a test for Sortable.options.group.put

I also took on the advice from the last pull I had a review on #38648 

## Issue Template
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
+ [Options](https://github.com/SortableJS/Sortable#options)
+ [Plugins](https://github.com/SortableJS/Sortable/tree/master/plugins)
  + [AutoScroll](https://github.com/SortableJS/Sortable/tree/master/plugins/AutoScroll)
  + [MultiDrag](https://github.com/SortableJS/Sortable/tree/master/plugins/MultiDrag)
  + [OnSpill](https://github.com/SortableJS/Sortable/tree/master/plugins/OnSpill)
  + [Swap](https://github.com/SortableJS/Sortable/tree/master/plugins/Swap)

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by evenfrost** [comment]
@waynevanson thanks for PR! Would you consider also changing `options` argument to be optional here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39049/files#diff-ac54d3e569f8e4fa54f33f2dc725aadbR31 as Sortable can be instantiated without this using the default ones? Something like this should work:

```ts
    constructor(element: HTMLElement, options?: Sortable.Options);
```

**Comment by waynevanson** [comment]
> @waynevanson thanks for PR! Would you consider also changing `options` argument to be optional here:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c6c30f8b93b21664b69958d42593338985dcd548/types/sortablejs/index.d.ts#L31
> 
> as Sortable can be instantiated without this using the default ones? Something like this should work:
> ```ts
>     constructor(element: HTMLElement, options?: Sortable.Options);
> ```

Sure thing. I'll do it now.

**Comment by waynevanson** [comment]
@evenfrost There we are :)

**Comment by waynevanson** [comment]
>  @Maw-Fox @MaartenStaa - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39049/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.
> 
> If no reviewer appears after a week, a DefinitelyTyped maintainer will review the PR instead.

I made a change as requested by evenfrost

**Pull request merged**
