### PR TITLE
chore(restify): definitions updated for v8

### LINKED ISSUE #50937: Correct testify definitions for v8
- [ x] I tried using the `@types/xxxx` package and had problems.
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

If you do not mention the authors the issue will be ignored.
@andy-ms, @sheetalkamat I've corrected definitions for v8 of restify. Please verify and merge

### PR DESCRIPTION
**Pull request by GaikwadPratik**
Please fill in this template.
closes #50937
- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## restify ([<kbd>unpkg</kbd>](https://unpkg.com/browse/restify@latest/))
was missing the following properties:
1. helpers
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1c403a23a3ccf61f579c7a846b29345c36c1f806
</p>

**Review by martin-badin — CHANGES_REQUESTED** [review]
Please add tests. Example
```
// @ExpectedType restify.Route[]
server.router.getRoutes();
```

**Review by martin-badin — CHANGES_REQUESTED** [review]
Upgrade version of the package to `8.5`

**Comment by GaikwadPratik** [comment]
> Please add tests. Example
> 
> ```
> // @ExpectedType restify.Route[]
> server.router.getRoutes();
> ```

Done

**Comment by GaikwadPratik** [comment]
> Upgrade version of the package to `8.5`

Done

**Review by martin-badin — APPROVED** [review]
Thanks. Look good to me. 👍

**Comment by GaikwadPratik** [comment]
Ready to merge

**Pull request merged**
