### PR TITLE
[@types/ws] Correct onerror received information

### PR DESCRIPTION
**Pull request by vladfrangu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/websockets/ws/blob/master/lib/websocket.js#L769
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by vladfrangu** [comment]
This might be incorrect, and I might have gotten code confused around... Need to test but don't know how

**Comment by orblazer** [comment]
Hello @vladfrangu, for test that you can try force make an error et check the arguments of `onerror`.

**Comment by armanio123** [comment]
@vladfrangu @orblazer Can we have a confirmation if this is working? otherwise let me know if you feel comfortable and I can merge the pull request.

**Comment by PranavSenthilnathan** [comment]
Looking at the spec, it seems like this change might be incorrect: https://html.spec.whatwg.org/multipage/indices.html#event-error. There it says the type can be Event or ErrorEvent.

**Comment by vladfrangu** [comment]
It seems as though I got confused, mainly due to uWs well, not respecting the spec and emitting a partial error object. I will close this PR as it isn't valid. Thank you!

**Pull request closed without merging**
