### PR TITLE
Fixed lack of audience property in SignInOptions type for auth0 

### PR DESCRIPTION
**Pull request by maxism**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
- https://github.com/auth0/node-auth0/blob/master/src/auth/PasswordlessAuthenticator.js#L115
- https://github.com/auth0/node-auth0/blob/master/src/auth/OAuthAuthenticator.js#L94
- https://auth0.com/docs/api/authentication#get-code-or-link
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Is this for this particular part of API? 
https://auth0.github.io/node-auth0/PasswordlessAuthenticator.html#signIn

**Comment by maxism** [comment]
> Is this for this particular part of API? https://auth0.github.io/node-auth0/PasswordlessAuthenticator.html#signIn

Yes, it is. I also prepared [PR](https://github.com/auth0/node-auth0/pull/699) to change this part of the node-auth0 documentation. I think type definitions and documentation are not tied up in each other, because users can already use this type of functionality in the lib.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@maxism thx!

**Comment by maxism** [comment]
Ready to merge

**Pull request merged**
