### PR TITLE
[node] Improve http2 definitions

### PR DESCRIPTION
**Pull request by alessiodionisi**
Changes:
- `Http2ServerResponse` extends `stream.Writable` instead of `events.EventEmitter`

Checks:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://nodejs.org/api/http2.html#http2_class_http2_http2serverrequest
https://nodejs.org/api/http2.html#http2_class_http2_http2serverresponse
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by chyzwar** [comment]
Http2ServerResponse and Http2ServerRequest have their constructor marked a private. But according to the documentation, it should be possible to extend them.

https://nodejs.org/api/http2.html#http2_http2_createsecureserver_options_onrequesthandler
https://github.com/nodejs/node/pull/15560

As a part of this PR can you into changing access modifier for these constructors?

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Tests pls, (only needed for v11).
Feel also free to move the `http2` section from `node-tests.ts` to `/test/http2.ts`, that's entirely optional tho.

**Comment by adnsio** [comment]
@SimonSchick I've added some tests and moved all to `test/http2.ts`.

**Review by SimonSchick — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by SimonSchick — APPROVED** [review]

**Review by ZaneHannanAU — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by adnsio** [comment]
@SimonSchick @Flarna someone can merge this pull request?

**Comment by Flarna** [comment]
@sanders could you please re-open and merge this? CI fails are unrelated as far as I can see.

**Comment by amcasey** [comment]
We're having CI problems that are causing significant issues for widely consumed packages (esp Node).  We know how frustrating it is and we're working on a fix, which you can track here: https://github.com/Microsoft/TypeScript/issues/29898.  Sorry!

**Pull request closed without merging**
