### PR TITLE
Add Expected<T> to ArrayLikeMatchers.toContain

### PR DESCRIPTION
**Pull request by lukas-zech-software**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

The generic `ArrayLikeMatchers.toContain` function was expecting the old non-generic type and therefore would not accept  `jasmine.objectContaining` as input

I missed that when I implemented the generic matchers

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
@borisyankov @theodorejb @davidparsson anyone up for a review?

**Comment by aozgaa** [comment]
Pinging @theodorejb @davidparsson

**Comment by lukas-zech-software** [comment]
As there were no reviews so far I added another feature to this PR

* jasmine.Any can now also be a function

**Comment by andy-ms** [comment]
Please fix the merge conflict.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
