### PR TITLE
[node] `node:sea`

### PR DESCRIPTION
**Pull request by turansky**
If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [SEA](https://nodejs.org/docs/latest-v20.x/api/single-executable-applications.html)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by Semigradsky — APPROVED** [review]

**Comment by Semigradsky** [comment]
@turansky would be nice to add simple tests also

**Comment by turansky** [comment]
> @turansky would be nice to add simple tests also

Simple test on board

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/sea.ts
1. types/node/scripts/generate-docs/node-doc-processing.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 33815f3fb20989e73221966bf7f89c46a91963ca
</p>

**Review by peterblazejewicz — APPROVED** [review]
@turansky thanks!

**Comment by turansky** [comment]
@peterblazejewicz sorry, formatting update removed approve :(

**Review by peterblazejewicz — APPROVED** [review]

**Comment by turansky** [comment]
Ready to merge

**Pull request merged**
