### PR TITLE
Added new featured to $rootScope from 1.6.10

### PR DESCRIPTION
**Pull request by scipper**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1610-crystalline-persuasion-2018-04-17
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by thorn0 — CHANGES_REQUESTED** [review]
Could you please add JSDoc descriptions? E.g. it's not obvious that `isSuspended` returns `false` when an ancestor scope is suspended. With JSDoc descriptions, we'll make it possible for our IDE to remind us about such subtleties as it shows those descriptions in tool tips along with method signatures.

**Comment by thorn0** [comment]
Please fix linting errors and remove angular-specific jsdoc tags: `@name, @ngdoc, @kind, @link, @description`. `@description` is redundant because all untagged content is considered to be description.

**Comment by scipper** [comment]
I am not responsible for the errors in angular-desktop-notifications, am I?

**Review by thorn0 — APPROVED** [review]

**Comment by minestarks** [comment]
@scipper Please address the test failures, thanks!

**Comment by thorn0** [comment]
@minestarks Test failures are irrelevant to the proposed change. See #26357. Also if you merge #26178, they'll be gone.

**Comment by thorn0** [comment]
@scipper Please re-push or add a commit to trigger Travis again. It shouldn't fail this time.

**Comment by scipper** [comment]
@thorn0 how do I re-push? I don't have anything to commit and I do not want to commit nonsense.

**Comment by leonard-thieu** [comment]
You can close and re-open a PR to trigger CI services. That said, you probably need to pull in master anyway.

**Comment by scipper** [comment]
closing pull request in order to retrigger Travis on re-open.

**Pull request merged**
