### PR TITLE
Utw/update angular idle typings

### PR DESCRIPTION
**Pull request by philipbjorge**

### CODE REVIEW

**Comment by philipbjorge** [comment]
@mthamil -- I think you're looking at an old revision.
Thank you for looking :+1: !

**Comment by mthamil** [comment]
Wow, you are responsive!. Looks good.

**Comment by philipbjorge** [comment]
Thanks @mthamil

**Comment by mthamil** [comment]
Hopefully when TypeScript 1.8 comes out, autoResume can be updated to use string literal types: https://github.com/Microsoft/TypeScript/pull/5185. I totally forgot that feature was not released yet.

**Pull request merged**
