### PR TITLE
Maintains type safety during safeApply

### PR DESCRIPTION
**Pull request by bytenik**

### CODE REVIEW

**Comment by vvakame** [comment]
*rx-angular/rx.angular.d.ts*

to author(@mickdelaney). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mickdelaney** [comment]
Yes its looks good to me.

**Comment by mickdelaney** [comment]
+1

**Comment by vvakame** [comment]
@mickdelaney thanks!
@bytenik thanks mate!

**Pull request merged**
