### PR TITLE
[har-format] Har spec compliance and WPT compatibility.

### PR DESCRIPTION
**Pull request by tobli**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://gist.github.com/soulgalore/bfe2be5916f85c2a6d4b34f3be285b92
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by micmro — APPROVED** [review]

**Comment by tobli** [comment]
Thanks! I couldn't figure out how to bump the version number for the npm release.

**Comment by micmro** [comment]
I think it will be auto-bumped.

**Review by micmro — APPROVED** [review]

**Comment by tobli** [comment]
Seems like the bot might need a little nudge to pick up the approval?

**Review by micmro — APPROVED** [review]
Looks like need to wait for the Maintainers to kick it off and merge the PR.

**Comment by uniqueiniquity** [comment]
Sorry for the delay!

**Pull request merged**
