### PR TITLE
GeoJSON layer can be interactive

### PR DESCRIPTION
**Pull request by marco6**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://leafletjs.com/reference-1.7.1.html#interactive-layer
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by henrythasler — CHANGES_REQUESTED** [review]
Can you please:
1. Give some reference to the leaflet sourcecode that help understand the change
2. Add tests

**Comment by marco6** [comment]
Hi @henrythasler! I would add a test, but maybe I need some guidance. The main point is that the [leaflet guide](https://leafletjs.com/reference-1.7.1.html#interactive-layer) states that "some" Layers are interactive, without actually saying which are. The reason I changed GeoJSON layer's options to Interactive is that I _tried_ and it actually supports clicking and bubbling - so it should support passing things like "interactive" and "bubblingMouseEvents" to control its behavior (again, tried them and they work). I don't actually know how can I show this in a test.

I also couldn't easily find code related to this as it just inherits from Layer. If you want I can try dig deeper to find a reference in the code. Also please, note this change makes GeoJSON a superset of the previous definition, so it wouldn't break any existing code.

**Comment by ronikar** [comment]
Hi @marco6 ,
Are all the GeoJSON layers interactive? I think that it will be very confusing if `GeoJSONOptions` interface will extend `InteractiveLayerOptions`, but actually there are some GeoJSON layers that aren't interactive

**Comment by marco6** [comment]
Hi again @ronikar,

I dug a little deeper and I can confirm they are all interactive. In detail, GeoJSON is a FeatureGroup whose layers are created on calling [addData](https://github.com/Leaflet/Leaflet/blob/e66948d15df65a1014968ff9242c8bf825d16156/src/layer/GeoJSON.js#L98) which in turn calls [geometryToLayer](https://github.com/Leaflet/Leaflet/blob/e66948d15df65a1014968ff9242c8bf825d16156/src/layer/GeoJSON.js#L171). The latter, depending on feature type creates a layers:

 - Point, MultiPoint => [Marker](https://github.com/Leaflet/Leaflet/blob/e66948d15df65a1014968ff9242c8bf825d16156/src/layer/GeoJSON.js#L225)
- LineString, MultiLineString => Polyline
- Polygon, MultiPolygin => Polygon

Marker is InteractiveLayer (already typed as interactive).
Polygon extends Polyline extends Path which is an InteractiveLayer (already typed as interactive).

**Comment by ronikar** [comment]
@marco, In your case, each feature like `Point`, `LineString`, `Polygon`, is interactive separately. The question is, can we click on `FeatureGroup` ? Does `FeatureGroup` Fire mouse/touch events?

**Comment by marco6** [comment]
@ronikar, it follows the usual bubbling of events, meaning: if a layer inside a FeatureGroup is clicked, the event is first fired in the layer inside, then in the FeatureGroup. So you will receive a 'click' event on the FeatureGroup. Of course, if you manually add a non-interactive layer (e.g. not through the addData method) to the FeatureGroup, it will not fire anything.

**Comment by ronikar** [comment]
@marco6 , I tested `click event` on Chrome 86. When I clicked on `Marker` the `event.target` was the `FeatureGroup` object.
@alejo90 @atd-schubert @mcauer @life777 @henrythasler @captain-igloo, Would someone review it before I will approve it?

**Comment by ronikar** [comment]
@marco6 , I tested `click event` on Chrome 86. When I clicked on `Marker` the `event.target` was the `FeatureGroup` object.
@alejo90 @atd-schubert @mcauer @life777 @henrythasler @captain-igloo, would someone review it before I approve it?

**Review by ronikar — APPROVED** [review]
👍

**Comment by marco6** [comment]
@ronikar @henrythasler is there something blocking this PR from being merged? Can I help somehow not to get this closed automatically?

**Comment by henrythasler** [comment]
Hi @marco6, I'm still reluctant to set the options to interactive by default. Could it also work, to use a `LayerOptions | InteractiveLayerOptions` signature where needed?

**Comment by marco6** [comment]
@henrythasler I think it would work, but from the typing pov `InteractiveLayerOptions` extends `LayerOptions`, so I don't know if it does make sense... Maybe reading the typings code is cleaner this way, but it creates the same result.

IMHO since in vanilla JS I can pass an option that produces an effective result on the behavior, that property should be available in TS, too. Otherwise, I cannot use all the features of the library without hacks like `<any>` which is (again, IMHO) far worse than an ignored option...

**Comment by henrythasler** [comment]
Ok, but you should at least add a test that uses this new type

**Comment by marco6** [comment]
Ok, but what kind of test should I add? This is the same question I asked before... Maybe the test @ronikar tried manually before? Checking that the event bubbles? Do you have any suggestion?

> 
> 
> Hi @henrythasler! I would add a test, but maybe I need some guidance. The main point is that the [leaflet guide](https://leafletjs.com/reference-1.7.1.html#interactive-layer) states that "some" Layers are interactive, without actually saying which are. The reason I changed GeoJSON layer's options to Interactive is that I _tried_ and it actually supports clicking and bubbling - so it should support passing things like "interactive" and "bubblingMouseEvents" to control its behavior (again, tried them and they work). I don't actually know how can I show this in a test.
>

**Comment by ronikar** [comment]
You should create `GeoJSONOptions` object with `interactive` property and create a new `GeoJSON` layer with that options. 
Create the test after that [line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f3b4ddaf5ca04f07fa09cbdd48dc3b04e3f46b8d/types/leaflet/leaflet-tests.ts#L515)

**Comment by marco6** [comment]
Hi @ronikar, I added a very basic test. I hope it is enough.

**Review by henrythasler — APPROVED** [review]

**Comment by marco6** [comment]
Ready to merge

**Pull request merged**
