### PR TITLE
[jquery] Update type definitions (new for v3).

### LINKED ISSUE #426: jQuery originalEvent should be on the BaseJQueryEventObject
The following commit is incorrect
https://github.com/borisyankov/DefinitelyTyped/commit/62bc3e0772cdb54b1ae297f2a7500ae6885f2973

The originalEvent should be of type Event and on the BaseJQueryEventObject

http://api.jquery.com/category/events/event-object/

### LINKED ISSUE #1445: jQuery.d.ts and "Could not select overload for 'call' expression"
Hi,

Just this morning I've stumbled across the following problem - trying to call the overload of the mousedown event adder:

 mousedown(eventData: any, handler: (eventObject: JQueryMouseEventObject) => any): JQuery;

and I get the following error: could not select overload for 'call' expression.

I've guessing this is related to the 0.9.5 method overloading breaking change?
Or is it a bug with 0.9.5?
Or is it a bug with the method overload definition?

Is there a known fix that can be made to the jQuery method overloads that take the eventData argument?

Thanks

Donal

### LINKED ISSUE #2012: jquery.d.ts still has issues with promises
With the latest version it now has the return values strongly typed. This is great!

However, it's not valid for the reject to return the same type as the resolve. This needs to have an option to have to generic types defined on JQueryDeferred. One that is for the resolve and the other for the reject. (i.e. for an ajax call, it will return JQueryDeferred, where the reject is always type JQueryXHR)

### LINKED ISSUE #2146: Jquery event handler defination
jQuery event handlers can have more then one argument.
Function trigger ( eventType [, extraParameters ] )
All extra extraParameters passed to handler as is, but defination of handlers is:
 (eventObject: JQueryEventObject) => any.
I think it should be:
(eventObject: JQueryEventObject, ...extraParameters:any[]) => any

it affects all event handling functions: bind,on,one,click,keypress,live, etc. Cose all of them can be triggered.

### LINKED ISSUE #5596: $.merge argument type ArrayLikeObject
this is extension to this issue: #5472
the [merge](http://api.jquery.com/jquery.merge/) method should accept `ArrayLikeObject`

In the ts the arguments defines as simple arrays
https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1085

this code is ok, but shows errors by type checking:

``` javascript
var arrayLikeObject = $("div");
var arr = [1,2,3];
$.merge(arr, arrayLikeObject)
```

the jquery selector result is an `ArrayLikeObject`.

### LINKED ISSUE #7042: jQuery.extend and union types
Hey there!
I think, one chould add some overloads for jQuery.extend:

``` TypeScript
extend<A, B>(target: A, object1: B): A & B;
extend<A, B, C>(target: A, object1: B, object2: C): A & B & C;
extend<A, B, C, D>(target: A, object1: B, object2: C, object3: D): A & B & C & D;
```

This would be useful for the most common cases and add typesafety for simple extends. Unfortunately one cannot add typing for any number of parameters, I think.

What do you think?

### LINKED ISSUE #11115: JQueryXHR and .promise()
In the latest version of jquery.d.ts there is no support for for calling the promise() function on instances of the jQueryXHR type which you can do in jQuery v3.1.0.

In the jQuery documentation (http://api.jquery.com/Types/#Promise) it states that you should be able to call promise() on promise objects which is not present in the JQueryPromise<T> interface.

### LINKED ISSUE #13017: selectionStart not exists in <JQueryKeyEventObject>.target
- [x] I tried using the latest `jquery/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `jquery/index.d.ts`.

I write:
```
<JQueryKeyEventObject>.target.selectionStart === 0
```

But it fire error:
**selectionStart not fount in <Element> type**

Why:
jquery/index.d.ts:
```
JQueryKeyEventObject extend BaseJQueryEventObject
/* ... */
<BaseJQueryEventObject>.target === <Element> /* lib.es6.d (webstorm integrated) */
```

lib.es6.d (webstorm integrated):
```
HTMLInputElement extends HTMLElement
/* ... */
HTMLElement extends Element
/* ... */
HTMLInputElement {
  /* ... */
  selectionStart: number;
  /* ... */
}
```

Temporary solution:
```
public onInputKey($event: JQueryKeyEventObject) {
  let input = (<HTMLInputElement> $event.target);
  if (input.selectionStart === 0 && input.selectionEnd === 0) {
    // some code
  } 
}
```

Possible Solution:
1. extend <JQueryKeyEventObject> to generetic
```
$event: JQueryKeyEventObject<HTMLInputElement>
```

2. extend <JQueryKeyEventObject> to <JQueryKeyEventObjectFromTextfield>
```
JQueryKeyEventObjectFromTextfield {
  target: HTMLInputElement
}
```

### LINKED ISSUE #14515: @types/jquery - jQuery Event Object currentTarget not flexible enough
- [ ] I tried using the `@types/jquery` package and had problems.

jQuery allows the user to create events on any object i.e. 
```typescript
class A {
  $el: JQuery = $('<div />');
  constructor() {
    this.$el.on('click', this.onClick.bind(this));
  }
  onClick(): void {
    jQuery(this).trigger('objectevent');
  }
}
```
`this` (the app instantiation in the new `objectevent`; a non `Element`) is then assigned to `currentTarget` by jQuery but at present `currentTarget` is typed to `Element` which won't work for any other object such as my case. `currentTarget` needs to be `any` or something along those lines as I can't create a new `JQueryEventObject` and assign any other object to test the events with, nor can I assume the above works in practise.  See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/index.d.ts#L497 for what I mean.

In essence, if I were to emulate a `JQueryEventObject` with that `currentTarget` behaviour I would have to do the following:
```typescript
const a = new A();
jQuery(a).on('objectevent', function (ev) {
  console.log(ev.currentTarget);
});
const objectEvent = jQuery.Event('objectevent');
// forcing it to be an "any" shouldn't be necessary
objectEvent.currentTarget = a as any;
// this should give the console.log with the correct currentTarget as the object "a"
jQuery(a).trigger(objectEvent);
// so should this
a.$el.click();
```

### LINKED ISSUE #15733: jQuery 3 Typings
jQuery 3 is missing in the repo.

I found the latest version here https://www.nuget.org/packages/jquery.TypeScript.DefinitelyTyped/ from DT.

How come it is not included in this git repo, Is the community trying to enforce us to use MS Package Manager now? -_-

### LINKED ISSUE #16620: JQuery.css(properties: Object) is not strongly typed
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

When attempting to access specific css properties before passing them to jQuery.css I cannot type them correctly.

Example:
```ts
function resetCSSProps(obj: Object, ...properties: string[]) {
	let currentProp;
	for (let i = 0, len = properties.length; i < len; i++) {
		currentProp = properties[i];
		obj[currentProp] = ''; //Error TS7017: Element implicitly has an 'any' type because type 'Object' has no index signature.
	}
}

let cssProps: Object = {};
cssProps['min-height'] = height || '';
cssProps['min-width'] = width || '';
resetCSSProps(cssProps, 'top', 'left', 'width', 'height', 'transform');

myElt.css(cssProps);
```

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/
http://blog.jquery.com/2016/07/07/jquery-3-1-0-released-no-more-silent-errors/
http://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### Summary
This is a rewrite of the jQuery type definitions. My goals were to increase accuracy, coverage, and align terminology/names with how they're presented in jQuery docs. I tried to maintain backwards-compatibility with the old type definitions when possible. This also makes use of TypeScript 2.1, 2.2, and 2.3 features. As a result, I had to tag a lot of dependents (this look a **long** time).

- Fixes #15733
- Fixes #11115
- Closes #426 (this was already fixed in the old definitions)
- Closes #16620 (fixed for v2 in #16621)
- Fixes the following _only_ for v3
  - Fixes #14515
  - Fixes #13017
  - Fixes #7042
  - Fixes #5596
  - Fixes #2146
  - Fixes #2012
  - Fixes #1445

### File structure
Old typings were copied to both `v2` **and** `v1` since they represented 2.0 and 1.10 respectively.
- `test/example-tests.ts` contains tests generated from examples in docs
- `test/longdesc-tests.ts` contains tests generated from code snippets in descriptions in docs
- `jquery-tests.ts` covers TypeScript-specific features and parts not covered by the other tests

### Changes
- Dropped portions of the API that were removed in 3.0
- `JQuery` now declares `Iterable` as a base type so `for...of` is now possible
- `JQuery` is now generic, allowing for the possibility of working with other DOMs
  - jQuery can work with SVG, although it's officially unsupported
- The export is now correctly defined as a factory function
- More overloads should be covered along with a few missing methods
- Typed `this` in callbacks
- Matched jQuery's terminology where reasonable
  - For example, `JQueryEventObject` is now `JQuery.Event`

### Issues and potential bugs
- The following overloads have to be kept separated. If they're unified, `any` seems to 'win' and the function becomes untyped. 
  - [source](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L1671)
  - [test](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/test/longdesc-tests.ts#L2100)
```typescript
prop(propertyName: string, value: (this: TElement, index: number, oldPropertyValue: any) => any): this;
prop(propertyName: string, value: any): this;
```
- `Deferred.promise(object)` mixes an `object` with a `Promise`, however, the intersected type doesn't seem to survive chaining even when the method returns `this`.
  - [source](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L1652)
  - [test](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/test/example-tests.ts#L1217)
```typescript
promise<TTarget extends object>(target: TTarget): JQuery.Promise<TResolve> & TTarget;
```
- [`AjaxSettings<TContext>`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L3279) can't set its type argument to itself. `this` in callbacks on `AjaxSettings` is supposed to be the settings object itself unless [`context`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L3337) is defined. If `TContext` is set to `AjaxSettings`, it results in a compiler crash. I'm not sure how to properly model this relationship.
- Content adding methods on `JQuery` ([`after`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L88), [`append`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L197), [`before`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L255), [`prepend`](https://github.com/leonard-thieu/DefinitelyTyped/blob/6a556da667ad5eac21c171c50d26bd81c75a99a5/types/jquery/index.d.ts#L1584)) are supposed to be called with at least 1 argument. Declaring it like the following hurts usability with the spread operator though. Is there a decent way to represent it?
```typescript
append(content: JQuery.htmlString | JQuery.TypeOrArray<Element | Text> | JQuery,
       ...contents: Array<JQuery.htmlString | JQuery.TypeOrArray<Element | Text> | JQuery>): this;
```
- Variadic types aren't currently available but would help a lot.

Since this is a large amount of changes, I appreciate _anyone_ who takes the time to review this PR.

<sub>On a side note, I tried to declare `jQuery` as a class given that `jQuery` is really a constructor function but that didn't pan out. I got everything working except for plugins (which some people may find to be a big deal). I couldn't figure out why `jQuery` interfaces were refusing to merge. If anyone wants to take a crack at it, my best attempt can be found at https://github.com/leonard-thieu/DefinitelyTyped/tree/jquery-rewrite/types/jquery.</sub>

### CODE REVIEW

**Review by Toxantron — APPROVED** [review]

**Review by laurentiustamate94 — APPROVED** [review]

**Review by cyrilschumacher — APPROVED** [review]

**Review by mthamil-eml — APPROVED** [review]

**Review by deenairn — APPROVED** [review]

**Comment by leonard-thieu** [comment]
Looks like the bot missed a few people. I'll mention the ones for packages that had non-trivial changes.

<sub>

---

*[types/bootstrap.timepicker/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files?diff=unified#diff-fb8ce5ec3d3d078ce22d5f08908cbb92)*

to author (@derikwhittaker). Could you review this PR?
:+1: or :-1:?

------

*[types/jquery.tools/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-b4944e65252a3fa1cfc7c63af7f10f3a)*

to author (@joeskeen). Could you review this PR?
:+1: or :-1:?

------

*[types/jqueryui/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-727caf24c37b58eb1565b0a3782b2469)*

to authors (@borisyankov @johnnyreilly). Could you review this PR?
:+1: or :-1:?

------

*[types/materialize-css/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-a1e232c07e6a92869aeb7af860735768)*

to authors (@eriklieben @leonyu @SinghSukhdeep). Could you review this PR?
:+1: or :-1:?

------

*[types/menubar/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-bf9e1ed9d40598e310997c12827e0ccc)*

to author (@rhysd). Could you review this PR?
:+1: or :-1:?

------

*[types/nouislider/v7/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-857fd2767f2ae63e0244f09c19609517)*

to author (@acoreyj). Could you review this PR?
:+1: or :-1:?

------

*[types/sharepoint/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-e9a922a271af0c93f686f3294bc1796c)*

to authors (Stanislav Vyshchepan (account can't be detected) Andrey Markeev (account can't be detected)). Could you review this PR?
:+1: or :-1:?

------

*[types/shopify-buy/index.d.t](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-32fb2e98992f4843c1404815cfb89428)s*

to author (@openminder). Could you review this PR?
:+1: or :-1:?

------
</sub>

and of course

---
*[types/jquery/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159/files#diff-38ca0d3fc099227b1c19a1df229bc03e)*

to authors (@borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @.benjaminjackman @s093294 @JoshStrobl @johnnyreilly @DickvdBrink @King2500). Could you review this PR?
:+1: or :-1:?

------

**Review by Odrin — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Looks good to me. Let's allow people a little more time to respond. If no significant issues are raised then I'll be happy to merge. Thanks for your work!

**Review by AkosLukacs — APPROVED** [review]

**Review by joeskeen — APPROVED** [review]
LGTM Thanks for your hard work!

**Comment by mikehaas763** [comment]
Hey, thanks for this work it's good to see improvement. I think there may be an issue though. Does it really make sense to have es2015 lib support for this? Let me explain the issue we had after these new type defs got released.

We depend on @types/angular which depends on @types/jquery: '*'. Having a * version dep scares me, but idk if that's standard convention for type definition deps? We use typescript, but only have the es5 lib. eg we're not using any polyfills such as core-js. That's what we want, we don't care about newer es2015+ apis, just using typescript language features. Anyway, back to angular, now it's pulling @types/jquery v3 which uses `Iterable`. Iterable is an es2015 construct. So our builds have failed because the typescript compiler errors letting us know Iterable isn't available.

We know all the ways this can be fixed from our end, and have done so, although they're less then ideal. So, my proposal is that if jquery doesn't use es2015 features then we should use lib version of es5 so that we don't run into conflicts like the one we experienced. Thoughts? Should I open a new issue?

**Comment by johnnyreilly** [comment]
I think that opening an issue for this is probably a good idea - I can't actually see your comment on GitHub. It just landed in my inbox. If I can't see it then probably others can't either.
________________________________

**Pull request merged**
