### PR TITLE
GSAP @types: Tween.to method changes. vars property from TweenConfig to {} object type at tween.d.ts file

### PR DESCRIPTION
**Pull request by chukwu**
static to(target: {}, duration: number, vars: TweenConfig): TweenMax; //before
static to(target: {}, duration: number, vars: {}): TweenMax; //Now

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by chukwu** [comment]
can't parse definition header...? 
Please elaborate.

**Comment by aozgaa** [comment]
It looks like there is no author for the type definitions you changed.

Can you link to documentation?

**Comment by sandersn** [comment]
Thanks @chukwu for the fix. Here's the documentation: https://greensock.com/docs/#/HTML5/GSAP/TweenLite/to/

For future contributors, it looks like TweenConfig needs to be refactored into a base type and (at least) two subtypes, one of which should be used in `Tween.to`.

**Comment by mhegazy** [comment]
@chukwu can you please adopt the changes from @sandersn comment.

**Comment by yuit** [comment]
Thanks for your contribution. This PR has unaddressed comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
