### PR TITLE
Add support for `tapCatch` to bluebird typings

### PR DESCRIPTION
**Pull request by Retsam**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- ~~[] Run `npm run lint package-name` if a `tslint.json` is present.~~

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://bluebirdjs.com/docs/api/tapcatch.html
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
@Retsam looks like the tests failed some place unrelated to your change ... could you merge from master to rerun the checks please?

**Comment by Retsam** [comment]
@minestarks Looks like the same problem.

**Comment by minestarks** [comment]
@andy-ms I don't quite understand what's going on with the tests-- how did the failing jasmine test slip through? Would you mind taking a look?

**Comment by lhecker** [comment]
@Retsam You can safely ignore errors in typings you didn't touch (in this case: yasmine). If you know how I'd remove the merge commit to keep the git history clean and force push the result. (Your fork is used by no one anyways right?) But that's just my personal preference... 😄

Apart from that: Please add an appropriate, simple definition alias to [bluebird-global](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bluebird-global/index.d.ts) for this PR for `tapCatch`. Afterwards I'll approve it. 🙂

**Comment by andy-ms** [comment]
Those tests are fixed by #14819.

**Comment by minestarks** [comment]
I merged #14819 . Sorry about that @Retsam could you merge and try again?

**Comment by Retsam** [comment]
@minestarks I rebased onto the new master and it looks like it passed this time.

**Comment by minestarks** [comment]
Great, thank you. @lhecker good to go?

**Comment by lhecker** [comment]
@minestarks Good to go.
Great work @Retsam! 🙂

**Pull request merged**
