### PR TITLE
[node] Improve consistency of JSDoc since tags

### PR DESCRIPTION
**Pull request by josh-**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59434#discussion_r858114731>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

@amcasey [noticed a `@since` tag that wasn't consistent](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59434#discussion_r858114731) with the other JSDoc tags - this PR updates other incorrect tags too.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
just open thoughts for readers pleasure: AFAIK `v1.2.3` is not a proper semantic versioning:
https://semver.org/#is-v123-a-semantic-version
but it's a convention used in very own Node sources:
https://github.com/nodejs/node/blob/606bb521591a29df5401732bfbd19c1e31239ed9/lib/util.js#L83

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@josh- thx!

**Comment by josh-** [comment]
Thanks @peterblazejewicz 🎉

**Comment by josh-** [comment]
Ready to merge

**Comment by SimonSchick** [comment]
These tags are auto-generated via script, you should consider normalizing the script instead as it will be removed next time.

Also generally adding the `patch` version might not be worth-while since features/changes are almost always introduced in major and minor versions.

**Comment by josh-** [comment]
Ah thanks very much Simon, I've just run the script `VERSION=17.0.0 npm run generate-docs --prefix scripts/generate-docs` and it doesn't appear to have reverted any of these changes (I didn't run it for `v12/`, `v14`/ or `/v16` though). It looks like node has prefixed all their `added` and `deprecated` comments with `v` in the `major.minor.patch` format?

For example: https://github.com/nodejs/node/blob/68fb0bf553e2af3e0b61733d29e1e9ba7f73d9b2/doc/api/modules.md?plain=1#L1008-L1028

So perhaps the script doesn't need to be normalised?

**Comment by josh-** [comment]
However I notice that by running the script it reverted https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59930:

```diff
diff --git a/types/node/buffer.d.ts b/types/node/buffer.d.ts
index 18be30d2e9e4468c40c308bc6e6f9ecebd4f1b65..1a26043cde63ee07a805d020c732b7b12f3df18e 100644
--- a/types/node/buffer.d.ts
+++ b/types/node/buffer.d.ts
@@ -443,7 +443,7 @@ declare module 'buffer' {
              * Allocates a new `Buffer` of `size` bytes. If `size` is larger than {@link constants.MAX_LENGTH} or smaller than 0, `ERR_INVALID_ARG_VALUE` is thrown.
              *
              * The underlying memory for `Buffer` instances created in this way is _not_
-             * _initialized_. The contents of the newly created `Buffer` are unknown and _may contain sensitive data_. Use `Buffer.alloc()` instead to initialize`Buffer` instances with zeroes.
+             * _initialized_. The contents of the newly created `Buffer` are unknown and_may contain sensitive data_. Use `Buffer.alloc()` instead to initialize`Buffer` instances with zeroes.
              *
              * ```js
              * import { Buffer } from 'buffer';
```

so I've opened https://github.com/crosstype/node-html-markdown/issues/34 to try and resolve that.

**Pull request merged**
