### PR TITLE
[reactstrap] Updated types for reactstrap Input

### PR DESCRIPTION
**Pull request by amikhalev**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactstrap/reactstrap/blob/master/src/Input.js#L8
- [x] Increase the version number in the header if appropriate. (not sure if appropriate for such a small change?)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by amcasey** [comment]
Would any of the typing authors care to take a look? 
@alihammad, @mfal, @danilobjr

**Comment by amikhalev** [comment]
Bump? @alihammad, @mfal, @danilobjr

**Comment by bowdenk7** [comment]
@amikhalev it looks like there are some merge conflicts. Can you resolve these? Thanks!

**Comment by amikhalev** [comment]
@bowdenk7 Done! It looks like another PR which added the `getRef` was merged before this, but it had the wrong type anyways. So all fixed now, plus test added

**Pull request merged**
