### PR TITLE
Update Native File System / File System Access API

### PR DESCRIPTION
**Pull request by RReverser**
- Rename typings as per upstream spec rename.
 - Fix types to be classes where appropriate.
 - Define new APIs as per latest version of spec.
 - Update stable Chrome fallbacks.

**Note:** I'm not 100% sure what the workflow should be in case of a package rename. This is definitely not a "not needed" package, so I don't want to mark it as such as per README, however it won't be updated anymore and the new one should be used instead. I guess in this case what I did (removing old dir & creating a new one) should be sufficient.

That said, is there a way to `npm deprecate` the old package with a message suggesting the new one via DefinitelyTyped configs? Or perhaps one of the maintainers could do that?

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/WICG/file-system-access
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by RReverser** [comment]
@tomayac You looked at the original PR, in case you want to take a look at this one as well...

**Comment by amcasey** [comment]
@RReverser AFAIK, renaming the types folder is the correct course of action.  Consumers of the old underlying library should continue to get the old types since they'll still be on npm.  Consumers of the new underlying library will use the new types since the names will match.

**Review by amcasey — APPROVED** [review]

**Comment by RReverser** [comment]
@amcasey Sounds good, thanks. What about the `npm deprecate` + a message - do you think it would be useful?

**Comment by RReverser** [comment]
Ready to merge

**Comment by amcasey** [comment]
@RReverser I'm not sure I understand which scenario you're trying to improve - people who are explicitly referencing the new library and the old types?

**Comment by RReverser** [comment]
Yeah since technically the library / API is still the same, just got renamed - I want to make sure they know that the typings they rely on will never get updated, and switch to the new ones instead.

**Comment by RReverser** [comment]
(note that this is not for an npm library, so there are no "consumers of the old underlying library" vs consumers of the new one here; it's just an experimental browser API)

**Comment by amcasey** [comment]
Apparently, we do deprecate renamed types packages.  News to me. :smile:

Should be done.

**Comment by RReverser** [comment]
Awesome, thanks a lot for the quick turnaround!

**Comment by tomayac** [comment]
> Awesome, thanks a lot for the quick turnaround!

Quicker than I could wake up :-) Thanks for working on this, and thanks for the merge.

**Pull request merged**
