### PR TITLE
Update dagre-d3 typings for 0.6

### PR DESCRIPTION
**Pull request by simmonmt**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/dagrejs/dagre-d3
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## dagre-d3 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/dagre-d3@latest/))
was missing the following properties:
1. dagre
1. util
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1d9109b7cf1a9b00df635fa8366218502c4f41a8
</p>

**Comment by simmonmt** [comment]
What I've done:
1. I replaced types/dagre-d3's local version of graphlib.Graph with a direct dependency on graphlib. As far as I can tell, graphlib did not exist in DefinitelyTyped when dagre-d3 was created. Now it does, so I assume it's reasonable to depend on it? Regardless, the local version is out of date.
1. I removed the tests that verify members from the local version of graphlib.Graph.
1. I updated to 0.6.1 because that's the version we're using internally, and thus that's what I have to compile/test against. Going to 0.6.1 seemed better than staying at 0.4.

What I'm not sure about:
1. I had to add several imports to the test. Without them, `npm test` couldn't find graphlib. I don't understand how it was able to see d3 (before my change), but now can't find graphlib. That is, what's different between d3 and graphlib that affects their visibility. Anyway, once I imported graphlib, it became a module (IIRC), and thus I needed to import everything else.
1. The impact of the missing properties noted by danger-public below, namely `dagre`, `util`, and `version`.
1. I don't know how to react to the benchmarking results. Are they because the transitive closure of dependencies of dagre-d3 has increased in my change, with the addition of graphlib? Is it better to inline a stub copy of Graph, as the current version does, than to add a dependency?

Thanks for your help with the graphlib change, @lutzroeder. Since you seem to be active in both graphlib and dagre-d3, I thought you'd be interested in this one as well. Would either you or @danvk be interested in becoming the definition owner for this package? It looks like the current owner hasn't been active on GitHub in quite some time.

**Comment by simmonmt** [comment]
This should help with #14261.

**Comment by simmonmt** [comment]
@elibarzilay I'm new here. What does that queue change you just made mean? Maintainer review is pending code review? The current definition owner doesn't seem to be responding, so am I waiting for a maintainer to do a code review?

**Comment by simmonmt** [comment]
Hi @sandersn! @chivesrs referred me to you. Would it be possible to bump this change up a bit in the code review queue? I'm volunteering to be Definition Owner, but need some help with the review. Thanks!

**Comment by elibarzilay** [comment]
@simmonmt, I just passed the ball back to the owner, I'll let @orta decide if it's worth waiting more or merge it now.

(Also, @markwongsk -- ping)

**Comment by simmonmt** [comment]
Safe to conclude that @markwongsk is no longer actively maintaining this project?

**Comment by orta** [comment]
Yeah, I agree, let's get this in.

**Pull request merged**
