### PR TITLE
Rebass: Add tx prop to BoxKnownProps

### PR DESCRIPTION
**Pull request by tpict**
The `tx` prop is used to modify the lookup on the theme object when a `variant` is specified. Handy if you want to write an extension of a Rebass component with its own variants.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/rebassjs/rebass/blob/c8aaa05e7207f2304897e4f4a78071827dd085fe/packages/reflexbox/src/index.js#L16-L25
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by tpict** [comment]
Nor I 😢what's the DefinitelyTyped policy on undocumented props?

**Comment by Ilaiwi** [comment]
I've been using this feature as well. Not sure why it is not documented though

**Review by rhysd — APPROVED** [review]
Looks good. Though I'm not understanding when this value becomes number.

**Comment by tpict** [comment]
I was considering the possibility that a given set of variants might be keyed by number, but since the `tx` prop corresponds to the _name_ of a variant, it should probably be string only, so I'll change that. Thanks!

**Comment by andrewbranch** [comment]
> what's the DefinitelyTyped policy on undocumented props?

There’s no policy; it’s up to the owners of the package. The thing you should consider is if the target package follows semver, but doesn’t consider internal/undocumented API changes as breaking, they could decide to change or remove it in a patch version. If that happens, it would be fairly easy for users to get their typings and JS out of sync even though they appear to match in major/minor version.

In this scenario, you’d make another update here, and it would be published as a patch. Users would have to update to that patch in order to have safe typings again. So, it’s not the end of the world, but could be a minor risk or nuisance if things go poorly. Your job here as package owners is simply to weigh the potential costs and benefits.

**Review by rhysd — APPROVED** [review]

**Pull request merged**
