### PR TITLE
Update type definition for sharp 0.26.0

### PR DESCRIPTION
**Pull request by billykwok**
Add new properties added in 0.25.4 and 0.26.0.

For more information, please refer to [Changelog](https://sharp.pixelplumbing.com/changelog).

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by fdebijl — APPROVED** [review]
LGTM

Sources for changes that weren't provided in the OP:
- Add `sharpness` and `dominant` to stats: https://github.com/lovell/sharp/commit/c42de19d2acc8fb29cff0e18a81421fb05e71e1b
- Missing TIFF output options and new bitdepth options: https://sharp.pixelplumbing.com/api-output#tiff

As a sidenote, changing all the double quotes to single quotes, along with all the other linting, makes it harder to review the changes. I'd suggest splitting the linting changes and functional changes into two commits so the may be reviewed more easily.

**Comment by billykwok** [comment]
> LGTM
> 
> Sources for changes that weren't provided in the OP:
> 
> * Add `sharpness` and `dominant` to stats: [lovell/sharp@c42de19](https://github.com/lovell/sharp/commit/c42de19d2acc8fb29cff0e18a81421fb05e71e1b)
> * Missing TIFF output options and new bitdepth options: [sharp.pixelplumbing.com/api-output#tiff](https://sharp.pixelplumbing.com/api-output#tiff)
> 
> As a sidenote, changing all the double quotes to single quotes, along with all the other linting, makes it harder to review the changes. I'd suggest splitting the linting changes and functional changes into two commits so the may be reviewed more easily.

Thanks for approving and listing the sources for changes. Will be aware of that next time.

**Comment by billykwok** [comment]
Ready to merge

**Comment by billykwok** [comment]
Ready to merge

**Pull request merged**
