### PR TITLE
async: Convert to module

### PR DESCRIPTION
**Pull request by ghost**
Previously the definition defined an interface globally, the used:
```ts
declare var async: Async;
declare module "async" { export = async; }
```

Now, we simply export the members of the `Async` interface directly as functions.

### CODE REVIEW

**Comment by fenying** [comment]
@andy-ms Nice job, but if we do make this huge change, maybe the major version of its [NPM package](https://www.npmjs.com/package/@types/async) should be increased from 2 to 3, or all its dependents would be destroyed. (Perhaps the increment will be done automatically? I just want to make sure about it.)

**Comment by andy-ms** [comment]
@fenying Unfortunately `@types` packages don't have their own versions, they share it with the NPM package, which hasn't upgraded to a version 3. So users will need to lock down a specific patch version if they want the old behavior.

**Comment by Penryn** [comment]
I vote :+1: on this solution to bring the Async definitions into the future.

This is going to be a difficult transition no matter what. Unfortunately the async library is heavily used and therefore had its definitions written first in an incompatible way.

This pull request will hurt once to solve the global definition conflicts we see, whereas #19837 will maintain backward compatibility and hurt every time a global definition is stepped on by other modules.

**Comment by mhegazy** [comment]
@andy-ms, can you address the test failure.

**Comment by bytexro** [comment]
Presuming people should take the latest master from here instead of just a version of async? Is that intended??

**Pull request merged**
