### PR TITLE
Added "for" attribute.

### PR DESCRIPTION
**Pull request by illuxio**
Added "for" attribute to react.d.ts

### CODE REVIEW

**Comment by jbrantly** [comment]
React doesn't support a `for` attribute. You [should use `htmlFor` instead](https://facebook.github.io/react/docs/tags-and-attributes.html#supported-attributes).

**Comment by illuxio** [comment]
The TAG "label"  includes the attribute label!
https://developer.mozilla.org/de/docs/Web/HTML/Element/label

**Comment by jbrantly** [comment]
@illuxio Yes, I'm not disagreeing that the HTML spec has a `for` attribute. I'm saying that React does not, and therefore the definitions for React should not. Instead of `for` React uses `htmlFor` since that is the [DOM property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement) and React generally uses DOM properties for attributes/props.

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
