### PR TITLE
Update i18next and express-brute-memcached, add i18next plugins

### PR DESCRIPTION
**Pull request by cyrilschumacher**
- Update **connect-timeout**: fix error ;
- Update **i18next**: adding module to extend interface for i18next ;
- Update **express-brute-memcached**: adding default export ;
- Update **i18next-express-middleware**: removing unnecessary interface ;
- Update **i18next-sprintf-postprocessor**: improving definition ;
- Add definition for **i18next-browser-languagedetector** ;
- Add definition for **i18next-node-fs-backend** ;

### CODE REVIEW

**Comment by cyrilschumacher** [comment]
Is that my pull request has problems?

**Comment by vvakame** [comment]
oh, sorry. We can't get response from reviewer. I'll merge your pull request. please resolve conflict & ping me again.

**Comment by cyrilschumacher** [comment]
@vvakame No problem ;) I solved conflicts.

**Comment by vvakame** [comment]
wow, so many changes...
please make a small change set.

**Comment by cyrilschumacher** [comment]
I'll create a new pull request with only the changes. Sorry for the problem ^^

**Comment by cyrilschumacher** [comment]
@vvakame I created new pull request here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8318

**Pull request closed without merging**
