### PR TITLE
Order overloaded functions consistently in @types/elasticsearch

### PR DESCRIPTION
**Pull request by joshdover**
This reorders the overloaded functions in the Client class to have the Promise-returning definition last. This allows consistent return type lookups when adding types for a wrapper in downstream usages. Example:

```ts
type MyWrapperFunc = (params: BulkIndexDocumentsParams, myAddedArg: string) =>
    ReturnType<Client['bulk'>;
```

Before this change, some lookups would return the callback version of the function, which returns `void` rather than a promise with the specific return type of that function.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by joshdover** [comment]
@andy-ms @pushplay

**Comment by pushplay** [comment]
I don't think this change makes sense for the types file.

Per the docs https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#type-inference-in-conditional-types it's assumed the last signature is "the most permissive catch-all case."  It's not the case that the Promise is a catch-all for the callback.  Changing the ordering for your use case can easily break someone else's code.

I would have hoped that you would be able to use the following:

```typescript
type PromiseReturnType<T extends (...args: any[]) => Promise<any>> = T extends (...args: any[]) => Promise<infer R> ? Promise<R> : any;
```

But that infers a return type `{}` which doesn't seem right.  Maybe someone from the larger TypeScript can help you out or maybe the type system needs an improvement.

**Comment by joshdover** [comment]
@pushplay Right that is what I attempted at first as well. I also explored trying to combine each of the overloaded signatures paris to into a single signature using conditional types (if passed a callback the return type would be different than if you didn't) but I wasn't happy with how some of the type inferencing wasn't working on Promise callbacks.

I understand the general guidance is to have the last function be the "catch-all" but seeing how I expect most users to use Promises these days anyways, I think having the Promise signature last makes sense so ReturnType lookups work. It should be noted that on all of the other API functions (eg. client.cat.*) the Promise signature is last right now.

In other news, it looks like the elasticsearch-js lib will begin shipping it's own type definitions in the near future, so this point may be moot.

Thoughts?

**Comment by pushplay** [comment]
@joshdover That's great news about ES shipping their own.  I wonder how they plan on doing it.

Consistency is a good argument but I'm still gunshy about breaking changes.  Especially those that don't have a good migration path.

Does anyone else watching this have an opinion?

**Review by pushplay — APPROVED** [review]
Well no one else has an opinion and consistency is good so let's go with it.

**Pull request merged**
