### PR TITLE
Export videojs as module and add tslint.json

### PR DESCRIPTION
**Pull request by M0ns1gn0r**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

The following thing were done:

1. videojs exported as a module (interfaces renamed to remove the excessive VideoJS prefix).
2. tslint.json added.
3. Code adjusted according to found issues.
4. Additional tests for on() and off() functions written.

### CODE REVIEW

**Comment by M0ns1gn0r** [comment]
Can someone do the review?

**Review by vbortone — APPROVED** [review]
👍 +1

**Comment by M0ns1gn0r** [comment]
@zhengbli could you merge this PR?

**Comment by zhengbli** [comment]
👍

**Pull request merged**
