### PR TITLE
Updated i18next definitions to 2.3.4.

### PR DESCRIPTION
**Pull request by mxl**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by mxl** [comment]
@mdocter @cyrilschumacher Could you review this pull request?

I fully rewrote definitions for i18next because they were not correctly updated from 1.* to 2.* version and there were many inconsistencies.

I kept old definitions with version suffix for using with definitions for i18next plugins which I currently have no time to update but may be find few hours in the near future.

Also notice that I removed definitions for jQuery plugin because it now leaves in separate npm module https://github.com/i18next/jquery-i18next and I suppose that it's also incompatible with old definitions.

**Comment by cyrilschumacher** [comment]
Sorry for the late, I approve your pull request :+1:
Good job!

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by mxl** [comment]
@vvakame I rebased pull request changes.

**Comment by mxl** [comment]
@vvakame If everything is ok, pls merge pull request.

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
