### PR TITLE
update(): add topic var to InitOptions interface

### PR DESCRIPTION
**Pull request by thielpa**
@fredgalvao @macdonst I added a missing topics var in your type definition. I also formatted your code to 2 space indention....I hope that is okay for you.

Improvement to existing type definition.

### CODE REVIEW

**Comment by fredgalvao** [comment]
I'd rather the whitespace changes be left to another PR or at least different commits, as it makes it hard to glance at what changed when everything changed, but that's just me. I prefer tabs too, but I won't rekindle that flame in here :wink:, so make yourself at home.

For me it's a :+1: , thanks for helping keep the project updated.

**Comment by vvakame** [comment]
I prefer diff is less!

**Comment by mhegazy** [comment]
@Lordnoname can you refresh this PR and respond to review comments.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
