### PR TITLE
fix(microsoft-graph): Group, User.memberOf

### PR DESCRIPTION
**Pull request by jgburet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#relationships
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by nikithauc** [comment]
@jgburet Thank you for this pull request!

The typings is always auto generated with the source being https://graph.microsoft.com/v1.0/$metadata. We cannot add this manually and the values must come from the metadata source.

Can you please provide the reference or source for this change?

**Comment by jgburet** [comment]
@nikithauc There you go. What else do you need me to do? How do I provide you the tests I wrote in this PR?

```xml
<EntityType Name="group" BaseType="graph.directoryObject" OpenType="true">
<Property Name="assignedLabels" Type="Collection(graph.assignedLabel)"/>
<Property Name="assignedLicenses" Type="Collection(graph.assignedLicense)"/>
<Property Name="classification" Type="Edm.String"/>
<Property Name="createdDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="creationOptions" Type="Collection(Edm.String)"/>
<Property Name="description" Type="Edm.String"/>
<Property Name="displayName" Type="Edm.String"/>
<Property Name="expirationDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="groupTypes" Type="Collection(Edm.String)" Nullable="false"/>
<Property Name="hasMembersWithLicenseErrors" Type="Edm.Boolean"/>
<Property Name="licenseProcessingState" Type="graph.licenseProcessingState"/>
<Property Name="mail" Type="Edm.String"/>
<Property Name="mailEnabled" Type="Edm.Boolean"/>
<Property Name="mailNickname" Type="Edm.String"/>
<Property Name="membershipRule" Type="Edm.String"/>
<Property Name="membershipRuleProcessingState" Type="Edm.String"/>
<Property Name="onPremisesDomainName" Type="Edm.String"/>
<Property Name="onPremisesLastSyncDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="onPremisesNetBiosName" Type="Edm.String"/>
<Property Name="onPremisesProvisioningErrors" Type="Collection(graph.onPremisesProvisioningError)"/>
<Property Name="onPremisesSamAccountName" Type="Edm.String"/>
<Property Name="onPremisesSecurityIdentifier" Type="Edm.String"/>
<Property Name="onPremisesSyncEnabled" Type="Edm.Boolean"/>
<Property Name="preferredDataLocation" Type="Edm.String"/>
<Property Name="preferredLanguage" Type="Edm.String"/>
<Property Name="proxyAddresses" Type="Collection(Edm.String)" Nullable="false"/>
<Property Name="renewedDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="resourceBehaviorOptions" Type="Collection(Edm.String)"/>
<Property Name="resourceProvisioningOptions" Type="Collection(Edm.String)"/>
<Property Name="securityEnabled" Type="Edm.Boolean"/>
<Property Name="securityIdentifier" Type="Edm.String"/>
<Property Name="theme" Type="Edm.String"/>
<Property Name="visibility" Type="Edm.String"/>
<Property Name="allowExternalSenders" Type="Edm.Boolean"/>
<Property Name="autoSubscribeNewMembers" Type="Edm.Boolean"/>
<Property Name="hideFromAddressLists" Type="Edm.Boolean"/>
<Property Name="hideFromOutlookClients" Type="Edm.Boolean"/>
<Property Name="isSubscribedByMail" Type="Edm.Boolean"/>
<Property Name="unseenCount" Type="Edm.Int32"/>
<Property Name="isArchived" Type="Edm.Boolean"/>
<NavigationProperty Name="appRoleAssignments" Type="Collection(graph.appRoleAssignment)" ContainsTarget="true"/>
<NavigationProperty Name="createdOnBehalfOf" Type="graph.directoryObject"/>
<NavigationProperty Name="memberOf" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="members" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="membersWithLicenseErrors" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="owners" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="permissionGrants" Type="Collection(graph.resourceSpecificPermissionGrant)" ContainsTarget="true"/>
<NavigationProperty Name="settings" Type="Collection(graph.groupSetting)" ContainsTarget="true"/>
<NavigationProperty Name="transitiveMemberOf" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="transitiveMembers" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="acceptedSenders" Type="Collection(graph.directoryObject)" ContainsTarget="true"/>
<NavigationProperty Name="calendar" Type="graph.calendar" ContainsTarget="true"/>
<NavigationProperty Name="calendarView" Type="Collection(graph.event)" ContainsTarget="true"/>
<NavigationProperty Name="conversations" Type="Collection(graph.conversation)" ContainsTarget="true"/>
<NavigationProperty Name="events" Type="Collection(graph.event)" ContainsTarget="true"/>
<NavigationProperty Name="photo" Type="graph.profilePhoto" ContainsTarget="true"/>
<NavigationProperty Name="photos" Type="Collection(graph.profilePhoto)" ContainsTarget="true"/>
<NavigationProperty Name="rejectedSenders" Type="Collection(graph.directoryObject)" ContainsTarget="true"/>
<NavigationProperty Name="threads" Type="Collection(graph.conversationThread)" ContainsTarget="true"/>
<NavigationProperty Name="drive" Type="graph.drive" ContainsTarget="true"/>
<NavigationProperty Name="drives" Type="Collection(graph.drive)" ContainsTarget="true"/>
<NavigationProperty Name="sites" Type="Collection(graph.site)" ContainsTarget="true"/>
<NavigationProperty Name="extensions" Type="Collection(graph.extension)" ContainsTarget="true"/>
<NavigationProperty Name="groupLifecyclePolicies" Type="Collection(graph.groupLifecyclePolicy)" ContainsTarget="true"/>
<NavigationProperty Name="planner" Type="graph.plannerGroup" ContainsTarget="true"/>
<NavigationProperty Name="onenote" Type="graph.onenote" ContainsTarget="true"/>
<NavigationProperty Name="team" Type="graph.team" ContainsTarget="true"/>
</EntityType>

<EntityType Name="user" BaseType="graph.directoryObject" OpenType="true">
<Property Name="accountEnabled" Type="Edm.Boolean"/>
<Property Name="ageGroup" Type="Edm.String"/>
<Property Name="assignedLicenses" Type="Collection(graph.assignedLicense)" Nullable="false"/>
<Property Name="assignedPlans" Type="Collection(graph.assignedPlan)" Nullable="false"/>
<Property Name="businessPhones" Type="Collection(Edm.String)" Nullable="false"/>
<Property Name="city" Type="Edm.String"/>
<Property Name="companyName" Type="Edm.String"/>
<Property Name="consentProvidedForMinor" Type="Edm.String"/>
<Property Name="country" Type="Edm.String"/>
<Property Name="createdDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="creationType" Type="Edm.String"/>
<Property Name="department" Type="Edm.String"/>
<Property Name="displayName" Type="Edm.String"/>
<Property Name="employeeHireDate" Type="Edm.DateTimeOffset"/>
<Property Name="employeeId" Type="Edm.String"/>
<Property Name="employeeOrgData" Type="graph.employeeOrgData"/>
<Property Name="employeeType" Type="Edm.String"/>
<Property Name="externalUserState" Type="Edm.String"/>
<Property Name="externalUserStateChangeDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="faxNumber" Type="Edm.String"/>
<Property Name="givenName" Type="Edm.String"/>
<Property Name="identities" Type="Collection(graph.objectIdentity)"/>
<Property Name="imAddresses" Type="Collection(Edm.String)"/>
<Property Name="isResourceAccount" Type="Edm.Boolean"/>
<Property Name="jobTitle" Type="Edm.String"/>
<Property Name="lastPasswordChangeDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="legalAgeGroupClassification" Type="Edm.String"/>
<Property Name="licenseAssignmentStates" Type="Collection(graph.licenseAssignmentState)"/>
<Property Name="mail" Type="Edm.String"/>
<Property Name="mailNickname" Type="Edm.String"/>
<Property Name="mobilePhone" Type="Edm.String"/>
<Property Name="officeLocation" Type="Edm.String"/>
<Property Name="onPremisesDistinguishedName" Type="Edm.String"/>
<Property Name="onPremisesDomainName" Type="Edm.String"/>
<Property Name="onPremisesExtensionAttributes" Type="graph.onPremisesExtensionAttributes"/>
<Property Name="onPremisesImmutableId" Type="Edm.String"/>
<Property Name="onPremisesLastSyncDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="onPremisesProvisioningErrors" Type="Collection(graph.onPremisesProvisioningError)"/>
<Property Name="onPremisesSamAccountName" Type="Edm.String"/>
<Property Name="onPremisesSecurityIdentifier" Type="Edm.String"/>
<Property Name="onPremisesSyncEnabled" Type="Edm.Boolean"/>
<Property Name="onPremisesUserPrincipalName" Type="Edm.String"/>
<Property Name="otherMails" Type="Collection(Edm.String)" Nullable="false"/>
<Property Name="passwordPolicies" Type="Edm.String"/>
<Property Name="passwordProfile" Type="graph.passwordProfile"/>
<Property Name="postalCode" Type="Edm.String"/>
<Property Name="preferredLanguage" Type="Edm.String"/>
<Property Name="provisionedPlans" Type="Collection(graph.provisionedPlan)" Nullable="false"/>
<Property Name="proxyAddresses" Type="Collection(Edm.String)" Nullable="false"/>
<Property Name="showInAddressList" Type="Edm.Boolean"/>
<Property Name="signInSessionsValidFromDateTime" Type="Edm.DateTimeOffset"/>
<Property Name="state" Type="Edm.String"/>
<Property Name="streetAddress" Type="Edm.String"/>
<Property Name="surname" Type="Edm.String"/>
<Property Name="usageLocation" Type="Edm.String"/>
<Property Name="userPrincipalName" Type="Edm.String"/>
<Property Name="userType" Type="Edm.String"/>
<Property Name="mailboxSettings" Type="graph.mailboxSettings"/>
<Property Name="deviceEnrollmentLimit" Type="Edm.Int32" Nullable="false"/>
<Property Name="aboutMe" Type="Edm.String"/>
<Property Name="birthday" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="hireDate" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="interests" Type="Collection(Edm.String)"/>
<Property Name="mySite" Type="Edm.String"/>
<Property Name="pastProjects" Type="Collection(Edm.String)"/>
<Property Name="preferredName" Type="Edm.String"/>
<Property Name="responsibilities" Type="Collection(Edm.String)"/>
<Property Name="schools" Type="Collection(Edm.String)"/>
<Property Name="skills" Type="Collection(Edm.String)"/>
<NavigationProperty Name="appRoleAssignments" Type="Collection(graph.appRoleAssignment)" ContainsTarget="true"/>
<NavigationProperty Name="createdObjects" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="directReports" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="licenseDetails" Type="Collection(graph.licenseDetails)" ContainsTarget="true"/>
<NavigationProperty Name="manager" Type="graph.directoryObject"/>
<NavigationProperty Name="memberOf" Type="Collection(graph.group)"/>
<NavigationProperty Name="oauth2PermissionGrants" Type="Collection(graph.oAuth2PermissionGrant)"/>
<NavigationProperty Name="ownedDevices" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="ownedObjects" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="registeredDevices" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="scopedRoleMemberOf" Type="Collection(graph.scopedRoleMembership)" ContainsTarget="true"/>
<NavigationProperty Name="transitiveMemberOf" Type="Collection(graph.directoryObject)"/>
<NavigationProperty Name="calendar" Type="graph.calendar" ContainsTarget="true"/>
<NavigationProperty Name="calendarGroups" Type="Collection(graph.calendarGroup)" ContainsTarget="true"/>
<NavigationProperty Name="calendars" Type="Collection(graph.calendar)" ContainsTarget="true"/>
<NavigationProperty Name="calendarView" Type="Collection(graph.event)" ContainsTarget="true"/>
<NavigationProperty Name="contactFolders" Type="Collection(graph.contactFolder)" ContainsTarget="true"/>
<NavigationProperty Name="contacts" Type="Collection(graph.contact)" ContainsTarget="true"/>
<NavigationProperty Name="events" Type="Collection(graph.event)" ContainsTarget="true"/>
<NavigationProperty Name="inferenceClassification" Type="graph.inferenceClassification" ContainsTarget="true"/>
<NavigationProperty Name="mailFolders" Type="Collection(graph.mailFolder)" ContainsTarget="true"/>
<NavigationProperty Name="messages" Type="Collection(graph.message)" ContainsTarget="true"/>
<NavigationProperty Name="outlook" Type="graph.outlookUser" ContainsTarget="true"/>
<NavigationProperty Name="people" Type="Collection(graph.person)" ContainsTarget="true"/>
<NavigationProperty Name="photo" Type="graph.profilePhoto" ContainsTarget="true"/>
<NavigationProperty Name="photos" Type="Collection(graph.profilePhoto)" ContainsTarget="true"/>
<NavigationProperty Name="drive" Type="graph.drive" ContainsTarget="true"/>
<NavigationProperty Name="drives" Type="Collection(graph.drive)" ContainsTarget="true"/>
<NavigationProperty Name="followedSites" Type="Collection(graph.site)"/>
<NavigationProperty Name="extensions" Type="Collection(graph.extension)" ContainsTarget="true"/>
<NavigationProperty Name="agreementAcceptances" Type="Collection(graph.agreementAcceptance)"/>
<NavigationProperty Name="managedDevices" Type="Collection(graph.managedDevice)" ContainsTarget="true"/>
<NavigationProperty Name="managedAppRegistrations" Type="Collection(graph.managedAppRegistration)"/>
<NavigationProperty Name="deviceManagementTroubleshootingEvents" Type="Collection(graph.deviceManagementTroubleshootingEvent)" ContainsTarget="true"/>
<NavigationProperty Name="planner" Type="graph.plannerUser" ContainsTarget="true"/>
<NavigationProperty Name="insights" Type="graph.officeGraphInsights" ContainsTarget="true"/>
<NavigationProperty Name="settings" Type="graph.userSettings" ContainsTarget="true"/>
<NavigationProperty Name="onenote" Type="graph.onenote" ContainsTarget="true"/>
<NavigationProperty Name="activities" Type="Collection(graph.userActivity)" ContainsTarget="true"/>
<NavigationProperty Name="onlineMeetings" Type="Collection(graph.onlineMeeting)" ContainsTarget="true"/>
<NavigationProperty Name="presence" Type="graph.presence" ContainsTarget="true"/>
<NavigationProperty Name="authentication" Type="graph.authentication" ContainsTarget="true"/>
<NavigationProperty Name="chats" Type="Collection(graph.chat)" ContainsTarget="true"/>
<NavigationProperty Name="joinedTeams" Type="Collection(graph.team)" ContainsTarget="true"/>
<NavigationProperty Name="teamwork" Type="graph.userTeamwork" ContainsTarget="true"/>
<NavigationProperty Name="todo" Type="graph.todo" ContainsTarget="true"/>
</EntityType>
```

**Comment by jgburet** [comment]
@nikithauc what's missing?

**Comment by nikithauc** [comment]
@jgburet  Sorry for the delay in response. 

https://github.com/microsoftgraph/msgraph-metadata -The change that you are suggesting would first have to go into the metadata.

The typings file or the https://www.npmjs.com/package/@microsoft/microsoft-graph-types is never manually generated or modified. 

So I suggest you raise this issue here https://github.com/microsoftgraph/msgraph-metadata/issues .

**Pull request closed without merging**
