### PR TITLE
Fix incorrect uritemplate typings

### PR DESCRIPTION
**Pull request by rubensworks**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/fxa/uritemplate-js/blob/master/bin/uritemplate.js#L860
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The current typings incorrectly expect a named `UriTemplate` class with static methods on it. Instead, `UriTemplate` is the export itself, so the functions should be brought one level up.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by DanielRosenwasser** [comment]
Can you remove the unnecessary linter suppressions [in the package's `tslint.json`](https://github.com/rubensworks/DefinitelyTyped/blob/a2cdbb8d730c5427b3e76f9159079715e181a8b6/types/uritemplate/tslint.json) as well?

**Comment by rubensworks** [comment]
@DanielRosenwasser Sure thing! I've removed all unnecessary linter expressions and improved the style of the typings.

**Comment by rubensworks** [comment]
@RyanCavanaugh It looks like this unmerged PR has been removed from your backlog. Has something gone wrong, or is there something that should be changed on my end?

**Comment by DanielRosenwasser** [comment]
Sorry, thanks for the PR!

**Pull request merged**
