### PR TITLE
[Twitchat] feat(icons): :sparkles: add new icon enum in twitchat types

### PR DESCRIPTION
**Pull request by Drilmo**
- Introduced an enum called Icon in the Twitchat namespace.
- This enum includes a comprehensive list of icon constants such as AD, ALERT, ANNOUNCEMENT and many others.
- These constants provide a more robust way to handle and reference icons within the Twitchat application.
- This addition improves code readability and maintainability by providing a centralized list of available icons.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [see icon list here](https://github.com/Durss/Twitchat/blob/main/PUBLIC_API.md#custom_chat_message)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/twitchat/twitchat-tests.ts
1. types/twitchat/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1dd9a01bfdec2f5a2a8e19713b8de350a899ba2e
</p>

**Review by Durss — APPROVED** [review]
All good !

**Comment by Drilmo** [comment]
Ready to merge

**Comment by Drilmo** [comment]
Ready to merge

**Review by Durss — APPROVED** [review]

**Comment by Durss** [comment]
Ready to merge

**Pull request merged**
