### PR TITLE
add typings for "table" module

### PR DESCRIPTION
**Pull request by evanshortiss**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
Please use `npm run new-package -- table` to generate correct package structure. And target the `master` branch.

**Comment by evanshortiss** [comment]
@andy-ms would you like me to make the PR _toward_ master? Currently it's targeted at types-2.0.

**Comment by andy-ms** [comment]
In addition to changing the base branch on GitHub, you also need to rebase your branch so that it has only your changes.

**Comment by andy-ms** [comment]
Now at #13441

**Pull request closed without merging**
