### PR TITLE
[fabric] fix: gradient colorStop offset type should be number, not string

### PR DESCRIPTION
**Pull request by SeanBarry**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://fabricjs.com/docs/fabric.js.html#line7615
The docs don't explicitly say the type needs to be number, but I've linked to the source code where a float is parsed. Passing a string doesn't work either.

### CODE REVIEW

**Review by mike667 — COMMENTED** [review]
I had same issue with color stops. But maybe add some tests?

**Comment by SeanBarry** [comment]
> I had same issue with color stops. But maybe add some tests?

This is such a simple change and clearly aligns with the underlying library source code. Does it really justify a test? 

Happy to add some if the general consensus is yes

**Review by mike667 — APPROVED** [review]
Yeah, I checked source code. Offset is always number.

**Comment by SeanBarry** [comment]
@mike667 Ah great, thanks for approving. Happy to have contributed (even if it's something small! 😄 )

**Pull request merged**
