### PR TITLE
Update moxios to reference latest axios version

### PR DESCRIPTION
**Pull request by cryptojuice**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## moxios ([<kbd>unpkg</kbd>](https://unpkg.com/browse/moxios@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'moxios'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
1. moxios
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7cc80c46d016fc4e5bdf0fe6870be05c9a4a5e81
</p>

**Review by andrewbranch — COMMENTED** [review]
Why is this needed? The current moxios implementation lists `"axios": ">= 0.13.0"` as its peer dependency. Seems like this may force users to upgrade or have duplicate dependencies unnecessarily.

**Comment by andrewbranch** [comment]
Uggh, I forgot that v0 is magic in Semver. This wouldn’t be a problem if axios was on major version 1, because then `^1.24.0` would be compatible with v1.26.0. This is the problem you’re trying to fix:

```
❯ npm i axios
❯ npm i @types/moxios
❯ npm ls axios
ts@1.0.0
├─┬ @types/moxios@0.4.14
│ └── axios@0.24.0
└── axios@0.26.0
```

It seems to me that if moxios itself lists only a minimum version of axios, then @types/moxios should follow suit. The caret range is too restrictive; you shouldn’t need to be coming back to make these updates every time axios bumps their minor version. In fact, this PR is already out of date—v0.26.0 was published 3 days ago.

Let’s fix this by matching the version requirement of the implementation package. Please change to `">= 0.13.0"` and that should solve the duplication issue without requiring users to pinpoint which version of @types/moxios they need to match their axios version (literally nobody will ever figure out that they need to do this), and you won’t have to make PRs like this every week.

**Comment by peterblazejewicz** [comment]
I usually suggest same, pin the version literally. Should work best on most scenarios.

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
