### PR TITLE
improve defination of ndarray

### PR DESCRIPTION
**Pull request by taoqf**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by pawsong** [comment]
@taoqf Could you explain what this commit is for?

**Comment by taoqf** [comment]
@pawsong I would like make it as a module which I could use it like this:
```
import * as ndarray from 'ndarray';
```

**Comment by pawsong** [comment]
I think this PR will break the following line:

```ts
function fn(a: ndarray) { } // [ts] Cannot find name 'ndarray'.
```

as ndarray is not an interface anymore.

How about adding module declaration like this?

```ts
// ...

declare function ndarray(
    data: Data, shape?: number[], stride?: number[], offset?: number
): ndarray;

// Add this line
declare module ndarray { }

export = ndarray;
```

**Comment by taoqf** [comment]
Actually, I would like use
```ts
import ndarray, { NDarray } from 'ndarray';
```
but, anyway, I have changed it by your advise.

**Pull request merged**
