### PR TITLE
Added avgTypingSpeed property to react-typist type

### PR DESCRIPTION
**Pull request by mbruhler**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48594>>
- ~~[ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~
- Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~~

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-typist ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-typist@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'react-typist'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. thatReturns
1. thatReturnsFalse
1. thatReturnsTrue
1. thatReturnsNull

<details>
<summary>as well as these 11 other properties...</summary>
<p>thatReturnsThis, thatReturnsArgument, sleep, gaussianRnd, eachPromise, exclude, isBackspaceElement, isDelayElement, extractTextFromElement, cloneElement, cloneElementWithSpecifiedText</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4a8a723c6b3b95867c50bfda97f4177ca19b6b79
</p>

**Review by shawnkoon — COMMENTED** [review]
Hello @bearfromtheabyss, thank you for the contribution!

I was wondering, I don't see this new `avgTypingSpeed` property for TypistProps under their [official doc](https://github.com/jstejada/react-typist#typist-props) nor [javascript def](https://github.com/jstejada/react-typist/blob/master/src/Typist.jsx#L13-L24).

If I am missing something, would you be able to refer me to a point in `react-typist` please? 👍

**Comment by bearfromtheabyss** [comment]
Hi, 
Well I think I'm too fast and I should refer to you as maintainers if that's something to work on. I'm new to open source thing, I tried to help :)

[here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48594#issuecomment-705678534) is some more insight on the thing. Maybe there is something more to work on? I just added here this property to the react-typist component

**Comment by shawnkoon** [comment]
Ahh gotcha, no worries - You did good :+1:

I think the requestor of the issue must be referencing to an older doc produced by `react-typist`.  There was `avgTypingSpeed` (typo) in their examples before, which was [fixed here](https://github.com/jstejada/react-typist/pull/70/files). I will address this in the issue linked.

Again, nice job. Good luck with Hacktoberfest 😁

**Review by peterblazejewicz — COMMENTED** [review]
Can you please point where this is defined in original package?
Thanks!

**Comment by weswigham** [comment]
Yeah, sorry, looks like this prop isn't needed, and the backing issue was just referring to an old doc bug~

**Pull request closed without merging**
