### PR TITLE
[proper-lockfile] Add lockfilePath option

### PR DESCRIPTION
**Pull request by LinusU**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/moxystudio/node-proper-lockfile/blob/b91cb551abf74c11e59b822f42fdbb851be32db8/lib/lockfile.js#L10-L12, https://github.com/moxystudio/node-proper-lockfile#lockfile-options
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by qlonik — CHANGES_REQUESTED** [review]
According to the documentation of the `proper-lockfile`, it seems that `lockfilePath` option is also available on `UnlockOptions` and `CheckOptions`. Could you add the same line you added to `LockOptions` to the other too? Thank you for PR. :smile:

**Comment by LinusU** [comment]
@qlonik done 👍

**Comment by qlonik** [comment]
Looks good to me. I'm not sure how to trigger the bot that its done.

**Review by qlonik — APPROVED** [review]
:+1: 

EDIT: oh, I guess leaving the comment is not required when approving changes....

**Pull request merged**
