### PR TITLE
Add definitions for fetch-jsonp (https://github.com/camsong/fetch-jsonp)

### PR DESCRIPTION
**Pull request by tkrotoff**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.

=> got a crash:
```
$ npm run new-package toto123

> definitely-typed@0.0.1 new-package /DefinitelyTyped
> dts-gen --dt "toto123"

Unexpected crash! Please log a bug with the commandline you specified.
/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:109
        throw e;
        ^

Error
    at new ArgsError (/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:25:28)
    at Object.<anonymous> (/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:39:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
```
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by tkrotoff** [comment]
`tsc` works because it's using TypeScript 2.2
`npm test` fails because it's using an older version, don't know how to force TypeScript 2.2 with `npm test`

**Comment by mhegazy** [comment]
Please see https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21

**Comment by tkrotoff** [comment]
@mhegazy already done, waiting for TS 2.2 support

**Comment by tkrotoff** [comment]
@mhegazy @andy-ms
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14818 is done now, this can be merged

Tested locally with:
```
./node_modules/.bin/tsc -p fetch-jsonp
npm run lint fetch-jsonp
```

=> OK

**Comment by paulvanbrenk** [comment]
There seems to be a legit issue in the CI server now:

```
=== ERRORS ===



Error in fetch-jsonp
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.0/node_modules/typescript/lib/tsc.js 

index.d.ts(14,34): error TS2304: Cannot find name 'RequestInfo'.
index.d.ts(14,86): error TS2304: Cannot find name 'Response'.
```

**Comment by andy-ms** [comment]
Why did you disable `only-arrow-functions-2`? It should be easy to fix.

**Comment by tkrotoff** [comment]
@andy-ms because `fetch-jsonp-tests.ts` are examples copy-pasted from fetch-jsonp website and I want them to be as close as possible to the original examples.

Suggestion: tslint rules should only apply to the .d.ts files (or different rules should be allowed)

Other example: my PR for react-router v4. All tests are the examples (a dozen) copy-pasted from the website. I don't want to spend time fixing tslint rules each time the original examples are changed

**Comment by andy-ms** [comment]
I think in the future we'll want to encourage writing tests yourself and using [`$ExpectType`](https://github.com/Microsoft/dtslint#write-tests), so we'll want to keep linting tests by default.

**Pull request merged**
