### PR TITLE
[socketcluster] Add new versions

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by sandersn — APPROVED** [review]
This all looks technically correct, but I do wonder whether you need to create old version directories for all these types; that's only needed to ship updates for the old versions. But a lot of the packages have versions that *never* got updates, which tells me that they're not likely to do so in the future either.

I approved the PR, so you can merge if you want to, but consider dropping the old-version copies.

**Comment by Methuselah96** [comment]
Ready to merge

**Comment by Methuselah96** [comment]
@sandersn The reason I'm creating old version directories is so that I can declare the correct major version for each dependency, otherwise old major versions will depend on `*` for all its dependencies, when in reality they need to pinned to a specific major version once new majors come out. Let me know if there's a better way to accomplish that.

**Comment by sandersn** [comment]
That makes sense. No, I don't think there's a better way -- I hadn't even thought of that problem till you pointed it out.

**Pull request merged**
