### PR TITLE
Rewriting the react-fa typings

### PR DESCRIPTION
**Pull request by patsissons**
This PR rewrites the typings using the module template from the typescript handbook and adds a lot of missing type information.

This PR changes the export style (which was previously incorrect) and as such is a major version bump (as per SemVer 2). Most consumers will not notice as there is now a default export which should bridge that gap (for most). Individual components are now exported and therefore should be imported explicitly.

Example:
```ts
// recommended import style
import { Icon, IconStack } from 'react-fa';

// still possible via default export, but not recommended
import Icon from 'react-fa';

// No longer possible
import * as Icon from 'react-fa';
```

namespace import syntax is [not officially supported by react-fa](https://github.com/andreypopp/react-fa/blob/master/src/index.js#L10)

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/andreypopp/react-fa
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
@patsissons Merge from latest `types-2.0` to fix tests.

**Comment by patsissons** [comment]
it seems these typings were upgraded already, so my changes are much less significant now. Probably still worth discussing my proposed changes. I'll start some reviews on the proposals.

**Comment by paulvanbrenk** [comment]
@patsissons do you want to keep this PR? Or did you create a new one?

**Comment by patsissons** [comment]
@paulvanbrenk I believe this PR is still valid. I started the reviews to get confirmation that my reasoning for the changes was sound.

**Comment by paulvanbrenk** [comment]
@patsissons cool.

@flaub any feedback?

**Comment by vvakame** [comment]
We can't get response from author. I decided to merge this PR.
sorry for late response...

**Pull request merged**
