### PR TITLE
Add grant and channel group definitions to @types/pubnub

### PR DESCRIPTION
**Pull request by pettero**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.pubnub.com/docs/web-javascript/api-reference-channel-groups, https://www.pubnub.com/docs/web-javascript/api-reference-access-manager#grant 
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by vitosamson** [comment]
@pettero does the `grant` method provide a Promise variant like the other methods? If so, could you add that as well for completeness? Same for the `channelGroup.addChannels` and `channelGroup.listChannels` methods.

Also small nitpick, the `GrantChannelParameteres` interface has a typo, it should be `GrantChannelParameters`.

**Comment by pettero** [comment]
[Add channels](https://www.pubnub.com/docs/web-javascript/api-reference-channel-groups#adding-channels), [list channels](https://www.pubnub.com/docs/web-javascript/api-reference-channel-groups#listing-channels) and [grant channels](https://www.pubnub.com/docs/web-javascript/api-reference-access-manager#grant) does not have promises as [other methods](https://www.pubnub.com/docs/web-javascript/api-reference-publish-and-subscribe#publish-successful-using-promises) has.

**Comment by pettero** [comment]
Fixed spelling error as well.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
