### PR TITLE
[node] Correct constants module for node v6

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Environment

Nodejs 6.5.0
# Description

Based on interest. I tried to trace #11022. I get amazing discovery as following:

In fact, there are **136** exported properties of  constants in **Nodejs**.
But there are **271** exported properties of  constants in **node.d.ts**.
The quantity is not consistency.

Sample code:

```
const c = constants;
Object.keys(constants).length
// 136
```

134 in 136 properties have been defined in **node.d.ts**. The 2 missing properties are **['ENGINE_METHOD_RSA', 'ALPN_ENABLED']**, so I had added in definition.

137 in 271 exported properties of  constants in **node.d.ts** are unknown properties. To avoid causing unknown issues, it keeps in place, it's in order to discuss on next issue or PR, so it decided to not be deleted. Therefore, I used comments `/// The following needs to be reviewed` to split them.
# Actions

In **node.d.ts**:
- Add missing stuff: **'ENGINE_METHOD_RSA', 'ALPN_ENABLED'**
- Use comments to split into real and unknown properties

In **node-tests.ts**:
- Add tests for **constants**

### CODE REVIEW

**Comment by hriss95** [comment]
The file changes suggest that you just copied what your log gave you and it was in different order so it is kind of hard to track the exact changes. If you have only added these 2 constants you mention in the PR description, it should be fine since they can be accessed on your systems. However, for the same reasons, I don't think that the separation is a good idea as unknown ones are not exactly unknown, but rather specific to some other system.

**Comment by hriss95** [comment]
Further [reference](https://github.com/nodejs/node/blob/master/lib/constants.js). If you open the documentation for the modules that the constants are taken from you can see that they are specific depending on the OS( [os module](https://nodejs.org/api/os.html#os_os_constants) for example )

**Comment by TonyPythoneer** [comment]
Hi @hriss95, could you review **node.d.ts**?
To avoid modifing too much, I only add two properties in the definition.

**Comment by hriss95** [comment]
Yup, looks good. :+1:

**Comment by TonyPythoneer** [comment]
@hriss95 thanks for your time and instruction. :smile:

**Pull request merged**
