### PR TITLE
[mongoose] type definitions are not needed since 5.11.0

### PR DESCRIPTION
**Pull request by kaznovac**
mongoose is providing official types as of version 5.11.0
https://github.com/Automattic/mongoose/blob/master/History.md#5110--2020-11-30

wip until other type packages using mongoose are updated

question: what should we do with abandoned packages like https://github.com/chevtek/mongoose-auto-increment; that one depends of the `"mongoose": "^4.1.12"` which does not have types?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

related:
- https://github.com/Automattic/mongoose/issues/9625
- #49902

### CODE REVIEW

**Comment by acrilex1** [comment]
The `npm run not-need` command deletes the folder for these types, including v3 and v4. I think this should not be the case, as previous versions are still needed.

There will be a big job of verifying and adding tests for every types which depends on @types/mongoose.

I'll be glad to contribute, if coordination is needed you can contact me on my email (see my profile). Also, you can add me as an author in index.d.ts so I can help review.

**Comment by acrilex1** [comment]
I removed it from my previous comment as I was not sure this would change anything unless revisions are necessary for old types, but:

The npm run not-need command deleted the folder for these types, including v3 and v4. I think this should not be the case, as previous versions are still needed.

**Comment by kaznovac** [comment]
thanks @acrilex1, some help would be greatly appreciated

deletion here would not retract already published packages on npm, which is good thing; but it will make those old versions impossible to update (as i understand not-needed mechanism)

mongoose v4.13 has seen 5 releases in the past 2 years  - all look like bugfixes to me (they probably won't risk any breaking changes in the api so updates to the mongoose v4 types might not be needed; but i also see that v4 types have been recently updated https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/mongoose/v4)

i'm not aware if it's possible to mark as not-needed the newest version of a type package and leave old ones for maintenance.

maybe we should start with leaf packages (like the one you need https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose-paginate-v2) first and make them depend on official mongoose types fist

**Comment by kaznovac** [comment]
hi maintainers, sorry for summoning you here, we would need some advise on the matter of mongoose types
@sandersn @DanielRosenwasser @horiuchi @borisyankov @weswigham @RyanCavanaugh 

to summarize:
- mongoose package started to provide the official type declarations since [5.11.0](https://github.com/Automattic/mongoose/blob/master/History.md#5110--2020-11-30)
- v4 is still somewhat maintained, v3 hasn't seen release since 2016 (here, type informations have seen some updates lately)

is there a way to mark the v5 types as not needed, and continue to maintain the type declarations for older versions?

the other problem (as @acrilex1 described in Automattic/mongoose#9625) is that leaf type packages can introduce duplicate typing declarations when used with `mongoose` which provides it's own types (e.g. https://www.npmjs.com/package/@types/mongoose-paginate-v2 depends on `@types/mongoose`)

i would purpose that leaf packages peer-depend on the parent types package (this can be somewhat cumbersome on `npm:^6`, but [`npm:^7`](https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md) and `yarn` already automatically install the peer dependencies)

thanks && appreciate your comments

**Comment by sandersn** [comment]
I'm not sure if the CI or bot will like it, but the ideal would be to pull the v4 types back up to the top level and put a note saying "Please do not upgrade to 5 because mongoose ships its own types."

It would cause a good deal of churn in the repo, but you could *possibly*
1. merge this PR to publish a deprecated stub 5.11 pointing 5.* users to the real types.
2. undelete the files, and move v4 to v5.

I have no idea if that's allowed with the current system without testing it. I don't think it's worth it either, because side-by-side installed `mongoose` and `@types/mongoose` will always resolve to `mongoose` for versions that ship their own types.

Not sure about the leaf package question; I'll have to think about that separately.

**Comment by jakebailey** [comment]
This change was made in #53417.

**Pull request closed without merging**
