### PR TITLE
[hapi__hapi] remove types

### PR DESCRIPTION
**Pull request by martin-badin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## hapi-auth-bearer-token ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi-auth-bearer-token@latest/))
was missing the following properties:
1. plugin
## hapi__basic ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__basic@latest/))
was missing the following properties:
1. plugin
1. plugin
## hapi__bell ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__bell@latest/))
was missing the following properties:
1. providers
1. oauth
## hapi__cookie ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__cookie@latest/))
was missing the following properties:
1. plugin
## hapi__crumb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__crumb@latest/))
was missing the following properties:
1. plugin
1. plugin
## hapi__h2o2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__h2o2@latest/))
was missing the following properties:
1. plugin
## hapi__inert ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__inert@latest/))
was missing the following properties:
1. plugin
## hapi__nes ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__nes@latest/))
was missing the following properties:
1. plugin
1. plugin
1. plugin
## hapi__vision ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__vision@latest/))
was missing the following properties:
1. plugin
1. plugin
## hapi__yar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__yar@latest/))
was missing the following properties:
1. plugin
## hapipal__toys ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapipal__toys@latest/))
was missing the following properties:
1. onPreStart
1. onPostStart
1. onPreStop
1. onPostStop
1. onPreStart

<details>
<summary>as well as these 3 other properties...</summary>
<p>onPostStart, onPreStop, onPostStop</p>
</details>

## schwifty ([<kbd>unpkg</kbd>](https://unpkg.com/browse/schwifty@latest/))
was missing the following properties:
1. migrationsStubPath
1. migrationsStubPath
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 639ad96eb9706af3f8f139dd9d12af6fa9b7c3a9
</p>

**Review by lenovouser — APPROVED** [review]

**Review by ffflorian — APPROVED** [review]

**Comment by lenovouser** [comment]
@SimonSchick this looks fairly straightforward, but maybe you can take another look as well

**Comment by SimonSchick** [comment]
I can't verify that all types are compatible but that's an acceptable cost, the change here looks fine.

**Comment by martin-badin** [comment]
@lenovouser @SimonSchick I can update all packages separately if you prefer it.

**Comment by SimonSchick** [comment]
I think this would just undue process.

**Comment by martin-badin** [comment]
@SimonSchick Could you approve that?

**Review by SimonSchick — APPROVED** [review]

**Comment by martin-badin** [comment]
@peterblazejewicz Could you please review that? I got some approvals. Thanks

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thanks!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
