### PR TITLE
remove simple-icons

### PR DESCRIPTION
**Pull request by sachinraja**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

We include types in `simple-icons` as of v5.21.0.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
LGTM!
@sachinraja was there a support in new definition for direct import? ('simple-icons/icons')?

**Comment by sachinraja** [comment]
Not sure what that means but we have definitions for all the entry points:
`simple-icons`, `simple-icons/icons`, and `simple-icons/icons/*`. We generate a definition file for each of the icons now (`icons/*.d.ts`)

**Comment by peterblazejewicz** [comment]
oh, OK, thx! I've just missed this detail when reviewing recent change on 'simple-icons'.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by sachinraja** [comment]
Ready to merge

**Comment by sachinraja** [comment]
Thanks for reviewing so quickly @peterblazejewicz!

**Pull request merged**
