### PR TITLE
Node's console is global

### PR DESCRIPTION
**Pull request by julien-c**
Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes. https://nodejs.org/api/console.html

### CODE REVIEW

**Comment by julien-c** [comment]
@mhegazy let me know whether this looks good to you – thanks!

**Comment by vvakame** [comment]
um? lib.d.ts has global console definition. 
What kind of situation do you assume?

**Comment by julien-c** [comment]
@vvakame I'm using `tsc v2.0.3` and in my `tsconfig.json` I specify `"lib": ["es6", "es2016"]` (see "Including built-in type declarations with --lib" here: https://www.typescriptlang.org/docs/release-notes/typescript-2.0.html

With this setup, `tsc` reports this error and is unable to compile: 
```
Cannot find name 'console'. (2304)
```

**Comment by minestarks** [comment]
@julien-c I think what you're looking for is [--target es6](https://www.typescriptlang.org/docs/handbook/compiler-options.html) , you'd get the console definition then. --lib es6 only includes the core library which doesn't include console.

Since this PR is rather stale and the tests are failing, I'm closing it out. Thank you!

**Pull request closed without merging**
