### PR TITLE
[cosmiconfig] update definitions for v5

### PR DESCRIPTION
**Pull request by stevenzeck**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/davidtheclark/cosmiconfig
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by szeck87** [comment]
@ozum would you mind taking a look at this too?

**Comment by ozum** [comment]
@szeck87 Thank you. I see your updates are for a new major version.

Instead of updating files directly, could you please create a directory called `v4` and put old files _(including test and json configurations)_ into it, and leave a full set of files for v5 in root.

See a simple example of major versioning in [hapi repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hapi)

This is recommended method for major version updates. Please see [updating to a new major version in FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version) about this.

**Review by ozum — CHANGES_REQUESTED** [review]
Please put old files in `v4` directory.

**Comment by ozum** [comment]
@szeck87

> Is there any way to write the declaration file so it can be imported via import * as cosmiconfig from "cosmiconfig"; or at least be able to import the interfaces?

Yes, see `import cosmiconfig, { CosmiconfigResult } from "cosmiconfig";` line in `cosmiconfig-tests.ts` below.



Please consider files below and update PR if they are OK. Also I realized that original module author is using Flow, so I tried to be faithful to his/her type names

**sample-config.json**
```json
{ "size": 12 }
```

**index.d.ts**
```ts
// Type definitions for cosmiconfig 5.0
// Project: https://github.com/davidtheclark/cosmiconfig
// Definitions by: ozum <https://github.com/ozum>
//                 szeck87 <https://github.com/szeck87>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

export type Config = { [key: string]: any };

export type CosmiconfigResult = {
  config: Config;
  filePath: string;
  isEmpty?: boolean;
} | null;

interface LoaderResult {
  config: Config | null;
  filepath: string;
}

export type SyncLoader = (filepath: string, content: string) => Config | null;
export type AsyncLoader = (filepath: string, content: string) => Config | null | Promise<Object | null>;

export interface LoaderEntry {
  sync?: SyncLoader;
  async?: AsyncLoader;
}

export interface Loaders {
  [key: string]: LoaderEntry;
}

export interface Explorer {
  search(searchFrom: string): Promise<null | CosmiconfigResult>;
  searchSync(searchFrom: string): null | CosmiconfigResult;
  load(loadPath: string): Promise<CosmiconfigResult>;
  loadSync(loadPath: string): CosmiconfigResult;
  clearLoadCache(): void;
  clearSearchCache(): void;
  clearCaches(): void;
}

// These are the user options with defaults applied.
export interface ExplorerOptions {
  stopDir?: string;
  cache?: boolean;
  transform?: (result: CosmiconfigResult) => Promise<CosmiconfigResult> | CosmiconfigResult;
  packageProp?: string;
  loaders?: Loaders;
  searchPlaces?: Array<string>;
  ignoreEmptySearchPlaces?: boolean;
}

export default function cosmiconfig(moduleName: string, options: ExplorerOptions): Explorer;
```

**cosmiconfig-tests.ts**
```ts
import cosmiconfig, { CosmiconfigResult } from "cosmiconfig";
import path from "path";

const explorer = cosmiconfig("yourModuleName", {
  searchPlaces: [],
  loaders: {},
  packageProp: "yourModuleName",
  stopDir: "someDir",
  cache: true,
  transform: (result: CosmiconfigResult) => result,
  ignoreEmptySearchPlaces: false,
});

Promise.all([
  explorer.search(path.join(__dirname)),
  explorer.searchSync(path.join(__dirname)),
  explorer.load(path.join(__dirname, "sample-config.json")),
  explorer.loadSync(path.join(__dirname, "sample-config.json")),
]).then(result => result);

explorer.clearLoadCache();
explorer.clearSearchCache();
explorer.clearCaches();
```

I checked against `tsconfig.json` below quickly, but it is different from repo requirements. Please edit definition or test if necessary for repo `tsconfig.json`.
```json
{
  "compilerOptions": {
    "strict": true,
    "module": "commonJS",
    "outDir": "lib",
    "sourceMap": true,
    "declaration": true,
    "target": "esnext",
    "lib": ["es2015", "es2016", "es2017"],
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "lib", "**/*.spec.ts", "**/*.test.ts", "**/__test-supplements__"]
}
```

Hope this helps.

**Review by ozum — CHANGES_REQUESTED** [review]
Please see my answer above.

**Comment by szeck87** [comment]
@ozum Thanks.  I made the changes you suggested and fixed the compile/lint errors with the exception of `interface-over-type-literal` for the `Config` type, I just disabled that rule for that line.

**Comment by szeck87** [comment]
@ozum any other changes?

**Comment by ozum** [comment]
According to doc's [create a new package](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) section, it seems `cosmiconfig-tests.ts` does not run, just used for typing tests. It seems you have two choices for `sample-config.json`:

* either, you may just delete it, library pass travis tests (according to doc), but you can not run test file yourself,
* or, you may still delete it but add `fs.writeFileSync("sample-config.json", '{ "size": 12 }')` and `fs.unlinkSync("sample-config.json")` to `cosmiconfig-tests.ts` file to create and delete it dynamically. This way, you can run test file.

Also re-enable `interface-over-type-literal`, and change `Config` from type to interface. (Same result for this context)

**index.d.ts** (Change below)
```ts
export interface Config {
  [key: string]: any;
}
```

**cosmiconfig-tests.ts**
```ts
import cosmiconfig, { CosmiconfigResult } from "cosmiconfig";
import path from "path";
import fs from "fs";

const TESTDIR = __dirname;
const TESTFILE = path.join(__dirname, "sample-config.json");

fs.writeFileSync(TESTFILE, '{ "size": 12 }');

const explorer = cosmiconfig("yourModuleName", {
  searchPlaces: [],
  loaders: {},
  packageProp: "yourModuleName",
  stopDir: "someDir",
  cache: true,
  transform: (result: CosmiconfigResult) => result,
  ignoreEmptySearchPlaces: false
});

Promise.all([
  explorer.search(TESTDIR),
  explorer.searchSync(TESTDIR),
  explorer.load(TESTFILE),
  explorer.loadSync(TESTFILE)
])
  .then(result => {
    fs.unlinkSync(TESTFILE);
    return result;
  })
  .then(result => result);

explorer.clearLoadCache();
explorer.clearSearchCache();
explorer.clearCaches();
```

**Comment by szeck87** [comment]
@ozum I updated the Config type.  I'll just leave the file out since it's not tested against anyways.

If there are no other changes can you approve from your end?

**Review by ozum — APPROVED** [review]
Thank you for the contribution.

**Pull request merged**
