### PR TITLE
Change definitions of jquery-param for support es6 import

### PR DESCRIPTION
**Pull request by alfaslash**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

URL to documentation or source code which provides context for the suggested changes: [jquery-param](https://github.com/knowledgecode/jquery-param)

Issue: #16456

### CODE REVIEW

**Comment by patsissons** [comment]
While this type def could use a refresh (`export as namespace` does not belong for example), i don't think going back to an ambient definition is the right approach. It looks like the proper import syntax when using es6/es2015 modules is `var param = require('jquery-param');`

**Comment by alfaslash** [comment]
`var param = require('jquery-param');`
I don't think this is the right approach. This is a temporary approach that works now. But I use in project only ECMAScript 6 modules.

**Comment by patsissons** [comment]
it is the recommended approach as per https://github.com/Microsoft/TypeScript/issues/4170

from @mhegazy 
> The error is there as there is no valid ES6 construct that maps to the export= semantics; so we do not know how to emit it. However, we could relax the constraint for ambient module declarations as there is no code emit impact.
https://github.com/Microsoft/TypeScript/issues/4170#issuecomment-128171614

**Comment by aozgaa** [comment]
So, what changes should be made to this PR?

**Comment by andy-ms** [comment]
This isn't the right solution. Depending on your situation, you could:
* Not target ES6 modules.
* [`--allowSyntheticDefaultImports`](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
* Add `declare namespace param {}` to the type declaration and use `import * as param from "jquery-param";`.

**Comment by yuit** [comment]
Thanks for your contribution. This PR has unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
