### PR TITLE
[dom-chromium-ai] Add typings for the translation API

### PR DESCRIPTION
**Pull request by christianliebel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/WICG/translation-api
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by christianliebel** [comment]
@tomayac I had some time during my journey back from TPAC, so I started working on the typings for the Translation API. As we discussed, we'll leave this PR in draft for now, as the namespace for the Translation API may still change.

**Review by tomayac — APPROVED** [review]
LGTM, approval

Thanks for preparing this. I've reviewed it, despite it still being in Draft, and it all seems perfect.

**Comment by xmlking** [comment]
can we merge this PR as the translation and language detentions APIs are in **origin-trial**  ?

**Review by tomayac — APPROVED** [review]
LGTM

**Comment by tomayac** [comment]
This will be relatively short-lived, as the APIs will migrate to the `self.ai` namespace, but it's good to merge for now.

**Pull request merged**
