### PR TITLE
gl-matrix definitions update

### PR DESCRIPTION
**Pull request by MattijsKneppers**
Added the changes suggested here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10166#issuecomment-234813627 by @nkassis:
- All vec input arguments allow for number[] input as well
- Renamed the new files to gl-matrix and gl-matrix-tests and renamed the old ones to gl-matrix-legacy

I also:
- Removed the definition of glMatrix, since this is only used internally in the javascript library and doesn't need to be exposed
- Cleaned some code formatting

### CODE REVIEW

**Comment by nkassis** [comment]
Just a note after trying this file locally. I had to change the export to declare to use the definitions with typing as a global module (in my setup glMatrix is loaded globally using systemjs and not imported). I believe using declare is preferable for definition files but I may be wrong.

**Comment by MattijsKneppers** [comment]
I see.. I currently don't have a project set up to test that situation in. I don't think it is possible to export multiple classes from one file and use declare, but I may be wrong.

Would you know of a solution that would satisfy both importing per class and importing as a global module?

**Comment by paulvanbrenk** [comment]
@DanielRosenwasser can you answer this question?

**Comment by DanielRosenwasser** [comment]
Hey all, please tell me more about this API (and point me in the direction of documentation). From the current definitions, it looks like it introduces *multiple* globals into your program like `glMatrix` and `vec2`.

Is there absolutely *no* way of scoping these entities such as `lib.glMatrix` and `lib.vec2`?

**Comment by MattijsKneppers** [comment]
Hi Daniel, the original library is here: http://glmatrix.net/, it's a math library specifically for WebGL.

Indeed all classes are exported separately, without an encapsulating namespace. I would say that the reason for this is that in a typical WebGL program, these commands are used so often that we would not want to have to prefix a namespace everywhere.

**Comment by DanielRosenwasser** [comment]
In the pre-2.0 world, I don't think there's a way to do this short of creating two different files. The legacy file is going to be the only way you can use the globals for now.

The thing is, in 2.0 we're trying to make it so that you can use these declarations either assuming that they're globals or through imports. Unfortunately, I don't think the current scheme is designed appropriately for the scenario where you have global entities from the same module `.d.ts` file.

I brought the concern up to @RyanCavanaugh a while back, but it wasn't in the scope of the 2.0 timeframe, so maybe we need to revisit the discussion.

**Comment by MattijsKneppers** [comment]
@DanielRosenwasser summarizing, would you say that the latest version I supplied is fit to pull, or is there anything you think I should improve?

**Comment by DanielRosenwasser** [comment]
I think that this is probably fine given that these are mainly global entities that are not typically imported.

**Pull request merged**
