### PR TITLE
react-calendar: Add missing closeCalendar prop

### LINKED ISSUE #255: closeCalendar does not exist on type DatePickerProps
Hi, Am using trying to close the calendar with the above props method in react typescript, yet seems not to figure out what is going on here. 

Any help is would be highly appreciated.

### PR DESCRIPTION
**Pull request by samir-araujo**
+ Introduces closeCalendar prop to react-calendar

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wojtekmaj/react-date-picker#datepicker

Fixes https://github.com/wojtekmaj/react-date-picker/issues/255
Closes wojtekmaj/react-date-picker#255

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-calendar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-calendar@latest/))
was missing the following properties:
1. Calendar
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4f85f60bb717619cef43bf31f8c3f5be630e1ab2
</p>

**Comment by peterblazejewicz** [comment]
@samir-araujo can you add this to your PR message? thx!

Closes wojtekmaj/react-date-picker#255

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@samir-araujo thx!

**Comment by samir-araujo** [comment]
Thanks for the reply, @peterblazejewicz !

PR updated

**Review by peterblazejewicz — APPROVED** [review]

**Pull request merged**
