### PR TITLE
Fix froogaloop

### PR DESCRIPTION
**Pull request by laszlopandy**

### CODE REVIEW

**Comment by vvakame** [comment]
*vimeo/froogaloop.d.ts*

to author (@DazWilkin). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by mhegazy** [comment]
@DazWilkin any comments?

**Comment by DazWilkin** [comment]
Apologies for the delayed reply. It's been almost 4 years since I touched this code. I'm no longer a reliable reviewer for PRs against it.

**Comment by mhegazy** [comment]
The interface `VimeoPlayer` does not seem to be used anywhere. so look like a safe change for me. merging.

**Pull request merged**
