### PR TITLE
[dynmap] Fix configuration types

### PR DESCRIPTION
**Pull request by ghost**
Co-authored-by: James Lyne <jim+github@not-null.co.uk>

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

https://github.com/JLyne/LiveAtlas/issues/224

### CODE REVIEW

**Comment by elibarzilay** [comment]
Making it possible to merge, but adding tests would avoid making the bot sad...

**Comment by SNDST00M** [comment]
It's a gigantic undocumented and unstable API so I've kept the tests barebones.

**Comment by SNDST00M** [comment]
Ready to merge

**Comment by elibarzilay** [comment]
Making it possible to merge, but IMO tests are useful regardless...

**Comment by SNDST00M** [comment]
Ha, I added tests and immediately found a major bug! Good on you for pushing it 😁

**Review by mikeprimm — APPROVED** [review]

**Comment by SNDST00M** [comment]
Ready to merge

**Pull request merged**
