### PR TITLE
Update maintainer

### PR DESCRIPTION
**Pull request by falsandtru**
vvakame is inactive. I'm a long-standing contributor of power-assert: https://github.com/power-assert-js/power-assert#contributors

### CODE REVIEW

**Comment by falsandtru** [comment]
@orta See https://github.com/power-assert-js/power-assert/issues/140#issuecomment-942493183. That proofs the correctness of my technical decision.

**Comment by falsandtru** [comment]
Merge #57062

**Comment by orta** [comment]
How correct your code was is not the reason I undid this PR.

I reverted this PR is because of how you handled the comments here in DT on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56227. We don't treat each other like that here. Making #57062 just re-enforced that it was the right call, so I'd recommend taking a pause on this. I'll close up that PR.

**Comment by falsandtru** [comment]
Your reason is too fuzzy. What do you want from me?

**Comment by orta** [comment]
> I'd like to see some more successful PRs to this dependency from you @falsandtru before giving access rights to the DT module. 

If you want to make some changes to DT, I'd like to see some PRs go through without friction.

**Comment by falsandtru** [comment]
So my contribution on DT isn't enough?

**Comment by orta** [comment]
To this module specifically

**Comment by falsandtru** [comment]
I've many merged PRs on this module.

https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/power-assert

**Comment by falsandtru** [comment]
I'll be away for an hour.

**Comment by elibarzilay** [comment]
Apologies for not knowing the context of this PR, I wouldn't have merged it if I'd known about it.

**Comment by falsandtru** [comment]
Then can you account that how can you approve @ChristianMurphy although the owner approved my decision?

**Comment by orta** [comment]
Sure, it's about your behavior on the DT pull requests and not about the technical merit of the code. You weren't treating the other contributors with respect and others folks in that conversation were. So, I'd like to see PRs which do not raise red flags in our DT chat room go through before giving you admin access to a DT module which is now become contentious.

**Comment by falsandtru** [comment]
Yeah it means you have no reason except your strange bias. I explained how he is technically wrong but unlike the others on the other my PRs he couldn't understand it. And it's still unclear that which comment is bad. Your comment has no concreteness. Anyway that isn't the requirement you specified. My contribution is more than ChristianMurphy. Thus I satisfied the requirements to become a reviewer to reject bad changes.

**Pull request merged**
