### PR TITLE
Added definition for Redux

### PR DESCRIPTION
**Pull request by wbuchwalter**

### CODE REVIEW

**Comment by vvakame** [comment]
*redux/redux.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/redux
  * http://bower.io/search/?q=redux
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (redux/redux-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@wbuchwalter thanks mate!

**Comment by sompylasar** [comment]
@wbuchwalter How about making State a type that extends any to make it explicit?

**Comment by wbuchwalter** [comment]
@sompylasar see [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6629/files) which changes a lot of things.

**Comment by sompylasar** [comment]
@wbuchwalter :+1:

**Pull request merged**
