### PR TITLE
[@types/struct] Added typing that allows infinite arguments in array

### PR DESCRIPTION
**Pull request by Rechdan**
Reason for that change:
```ts
const charlist = Struct() // 908
	.array('unk1', 4, 'word8')
	.array('posX', 4, 'word16Ule')
	.array('posY', 4, 'word16Ule')
	.array('name', 4, 'charsnt', 16)
	.array('status', 4, status)
	.array('equips', 4, 'array', 18, item) // here is the major reason
	.array('unk2', 8, 'word8')
	.array('gold', 4, 'word32Ule')
	.array('exp', 4, 'word64Ule');
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/xdenser/node-struct

### CODE REVIEW

**Review by benallfree — APPROVED** [review]
@Rechdan Looks good, thank you for the work!

**Comment by Rechdan** [comment]
@benallfree thanks for the approval! Should I fix the error in CI or just ignore it?

**Review by benallfree — APPROVED** [review]

**Comment by benallfree** [comment]
@Rechdan Yes please fix CI errors.. I see you did already :) Feel welcome to add some tests too, if appropriate.

**Comment by Rechdan** [comment]
@benallfree after some time fighting the types, got it to work in the way its meant to work, hope to have solved all the requirements now!

**Review by benallfree — APPROVED** [review]

**Comment by Rechdan** [comment]
Ready to merge

**Comment by Rechdan** [comment]
@benallfree one thing I noticed is that the version didn't changed, its the first time I contribute here so I don't know how to do that hahaha

**Comment by benallfree** [comment]
@Rechdan I’m not too sure either! According to https://github.com/microsoft/DefinitelyTyped-tools/tree/master/packages/publisher#calculate-versions, the publishing process is supposed to bump the version automatically. 

However, I just looked at https://www.npmjs.com/package/@types/struct and it looks like it hasn’t published. It was supposed to publish within an hour. 

I think the issue might be here, can you take a closer look? https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

**Comment by Rechdan** [comment]
@benallfree it's not clear to me either, but it seems like it follows the package version? If we don't figure it out we can increase the minor version... hahaha

**Pull request merged**
