### PR TITLE
Reorganize @types/node into packages

### PR DESCRIPTION
**Pull request by jablko**
Has there already been any discussion about reorganizing `@types/node` into packages? To avoid having to `/// <reference types="node" />` in order to import/require Node.js built-in modules?

I initially opened microsoft/types-publisher#765 to add dependencies on `@types/node` to types that import/require built-in modules.

I later opened DefinitelyTyped/DefinitelyTyped#44178 to add `/// <reference types="node" />` to packages without it, because dependencies alone [aren't sufficient](https://github.com/microsoft/types-publisher/pull/765#issuecomment-619060782).

But by reorganizing `@types/node`, could you instead import/require built-in modules *without* `/// <reference types="node" />`, as currently works when importing most modules?

At the end of the day, this proposal should introduce no changes from the perspective of `@types/node` dependants: Afterwards, `@types/node` depends on new `@types/${module}` packages and references the same versions of the same declarations that it does today, just in new locations. The only difference is that you don't need to `/// <reference types="node" />` to import/require a built-in module anymore.

### Description

The changes are currently:
1. Move `types/node/*/${module}.d.ts` -> `types/${module}/*/index.d.ts`
   - Prepend the header from `types/node/*/index.d.ts` to `types/${module}/*/index.d.ts`
2. Move `types/node/*/test/${module}.ts` -> `types/${module}/*/${module}-tests.ts`
3. Copy `types/node/*/tsconfig.json` -> `types/${module}/*/tsconfig.json`
   - Update the list of files:
     ```JSON
     "files": [
         "index.d.ts",
         "${module}-tests.ts"
     ],
     ```
   - Update path mappings (older versions):
     ```JSON
        "paths": {
            "${module}": [
                "${module}/v12"
            ]
        },
     ```
4. Copy `types/node/*/package.json` -> `types/${module}/*/package.json`
   - Update types versions (if any exist, for each particular module):
     ```JSON
     "typesVersions": {
         ">=3.2.0-0": {
             "*": [
                 "ts3.2/*"
             ]
         }
     }
     ```
5. Copy `types/node/*/tslint.json` -> `types/${module}/*/tslint.json`
6. Update the lists of files in `types/node/*/tsconfig.json` (remove relocated test files).
7. Update the references in `types/node/*.ts` (`/// <reference path="${module}.d.ts" />` -> `/// <reference types="${module}" />`).
8. To each older version, add path mappings to corresponding older versions of each dependency. I.e. `types/http/v12` imports `"net"`, therefore add:
   ```JSON
            "net": [
                "net/v12"
            ],
   ```

### Implementation

These changes were implemented by the following two scripts:
```Shell
#!/bin/sh

modules='
  async_hooks
  buffer
  child_process
  cluster
  console
  constants
  crypto
  dgram
  dns
  domain
  fs
  http
  http2
  https
  inspector
  module
  net
  os
  path
  perf_hooks
  process
  querystring
  readline
  repl
  stream
  string_decoder
  timers
  tls
  trace_events
  tty
  url
  util
  v8
  vm
  worker_threads
  zlib
'
for module in $modules; do
  typesVersions=$(
    git ls-files \
      "types/node/$module.d.ts" \
      "types/node/*/$module.d.ts" \
  )
  for types in $typesVersions; do
    sourceDirectory=$(dirname "$types")
    destination=$(dirname "types/$module/${types#types/node/}")
    mkdir --parents "$destination"

    # types/node/*/${module}.d.ts -> types/${module}/*/index.d.ts
    git mv "$types" "$destination/index.d.ts"
    # Prepend header
    perl -p -0 -i -e '
      open(my $fh, "<", "'"$sourceDirectory"'/index.d.ts");
      print(<$fh> =~ m%(// Type definitions for .*?^(?!//)\s*)%ms);
    ' "$destination/index.d.ts"

    # types/node/*/test/${module}.ts -> types/${module}/*/${module}-tests.ts
    tests=$sourceDirectory/test/$module.ts
    [ -f "$tests" ] && git mv "$tests" "$destination/$module-tests.ts"

    # types/node/*/tsconfig.json -> types/${module}/*/tsconfig.json
    tsconfig=$sourceDirectory/tsconfig.json
    if [ -f "$tsconfig" ]; then
      cp "$tsconfig" "$destination"
      # Update files and path mappings
      perl -p -0 -i -e '
        s%test/'"$module"'\.ts%'"$module"'-tests.ts%;
        my $replacement = sub { join(",", grep(/index\.d\.ts|'"$module"'-tests\.ts/, split(",", $&))) };
        s/(?<=\[).*?(?=\s*])/&$replacement/se;
        s/node/'"$module"'/g; # Path mappings
      ' "$destination/tsconfig.json"
    fi

    # types/node/*/package.json -> types/${module}/*/package.json
    packageJson=$sourceDirectory/package.json
    subDirectories=$(dirname $typesVersions | sed --quiet "s%$sourceDirectory/%%p")
    if [ "$subDirectories" ] && grep --fixed-strings --quiet "$subDirectories" "$packageJson"; then
      cp "$packageJson" "$destination"
      # Update types versions
      perl -p -0 -i -e '
        my $patterns = join("|", qw('"$subDirectories"'));
        my $replacement = sub { join(",", grep(/$patterns/, split(",", $&))) };
        s/(?<=.{).*\S(?=\s*}.*})/&$replacement/se;
      ' "$destination/package.json"
    fi

    # types/node/*/tslint.json -> types/${module}/*/tslint.json
    tslint=$sourceDirectory/tslint.json
    [ -f "$tslint" ] && cp "$tslint" "$destination"
  done
done

# Remove files from types/node/*/tsconfig.json
perl -p -0 -i -e '
  my $patterns = join("|", qw('"$modules"'));
  my $replacement = sub { join(",", grep(!/$patterns/, split(",", $&))) };
  s/(?<=\[).*?(?=\s*])/&$replacement/se;
' $(
  git ls-files \
    types/node/tsconfig.json \
    'types/node/*/tsconfig.json' \
)

# Update references in types/node/*.ts
perl -p -i -e '
  my $patterns = join("|", qw('"$modules"'));
  s%/// <reference path="($patterns)\.d\.ts" />%/// <reference types="$1" />%;
' $(git ls-files 'types/node/*.ts')

rm --dir $(find types/node -empty)
```

Run [types-publisher](https://github.com/microsoft/types-publisher) `parse` to update `../types-publisher/data/definitions.json`, then add path mappings to corresponding older versions of each dependency:

```Shell
#!/bin/sh

jq --raw-output '
  . as $definitions
  | (
    "node",

    "async_hooks",
    "buffer",
    "child_process",
    "cluster",
    "console",
    "constants",
    "crypto",
    "dgram",
    "dns",
    "domain",
    "fs",
    "http",
    "http2",
    "https",
    "inspector",
    "module",
    "net",
    "os",
    "path",
    "perf_hooks",
    "process",
    "querystring",
    "readline",
    "repl",
    "stream",
    "string_decoder",
    "timers",
    "tls",
    "trace_events",
    "tty",
    "url",
    "util",
    "v8",
    "vm",
    "worker_threads",
    "zlib")
  | "\(.) \(
    $definitions[.][]
    | select(
      .libraryVersionDirectoryName and (
        .dependencies != [] or .testDependencies != []
      )
    )
    | "\(.libraryVersionDirectoryName) \(
      (
        .dependencies
        | map(.name)
      ) + .testDependencies
      | unique
      | join(" ")
    )"
  )"
' ../types-publisher/data/definitions.json | while read -r module libraryVersionDirectoryName dependencies; do
  perl -p -0 -i -e '
    my $replacement = sub { "$&," . join(",", map { $& =~ s/'"$module"'/$_/gr } qw('"$dependencies"')) };
    s/\s*["'"'"']'"$module"'["'"'"'](?s).*?]/&$replacement/e;
  ' "types/$module/v$libraryVersionDirectoryName/tsconfig.json"
done
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by sandersn** [comment]
@SimonSchick @Flarna @rbuckton you might be interested in this. Feel free to tag others -- I'm not familiar with all the node types maintainers.

**Comment by SimonSchick** [comment]
I'm not sure about this:

To clarify, does that mean every package will be shipped as `@types/http` etc?
If that's the case it would make dependency hell magnitudes worse if people start depending on these packages due to fragmentation, versioning issues (diamond problem).

Also assuming `@types/node` would depending on all of these micro packages we would contribute to `node_modules` even more (there are already a lot of people complaining that certain package ship with @types/node as a dependency).

Should this be the case I'm heavily inclined to veto this.

I'm also worried about the extra churn we will experience when shipping new node (major) version (source: I have rolled the last ~5 major node versions in DT).
This has already been painful in the past, and I can see that become even more so without some better tooling.

Overall I'm not sure if avoiding the type reference is worth these caveats, the monolithic definition has given us a lot of flexibility I'm worried we might lose it and put a lot of burden on developers.

**Comment by Flarna** [comment]
I'm also not a big fan of splitting node into parts. I don't see the use case to allow using different versions of e.g. http and net.
Splitting node types into several files to avoid duplication because of types version made it already quite hard to review non basic changes. Splitting it even more would make it even harder.

**Comment by SimonSchick** [comment]
So far the consensus seems to relatively negative, I'm not sure if you should focus your efforts on this change.

I'd like to hear some more voices on this though.

**Comment by jakebailey** [comment]
I'm going to close this; this PR is super old and out of date, but most importantly given that node now has `node:` imports (introduced a year after this PR) + the fact that there are (on purpose) packages with the same name of node builtins published to npm, I don't think that this makes sense.

**Pull request closed without merging**
