### PR TITLE
Adding LatLngLiteral to googlemaps CircleOptions.center

### PR DESCRIPTION
**Pull request by curtis-h**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developers.google.com/maps/documentation/javascript/reference#LatLng>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@cgwrench, @nertzy, @xaolas, @mrmcnerd can you take a look?

@curtis-h can you point to the docs for this change?

**Comment by curtis-h** [comment]
[https://developers.google.com/maps/documentation/javascript/reference#LatLng](https://developers.google.com/maps/documentation/javascript/reference#LatLng)

Most relevantly this bit:
> Most methods that accept LatLng objects also accept a LatLngLiteral object, so that the following are equivalent:
 map.setCenter(new google.maps.LatLng(-34, 151));
 map.setCenter({lat: -34, lng: 151}); 
>

**Comment by nertzy** [comment]
Looks good to me. Have you checked that a LatLngLiteral works against the actual API? My vote is to merge this.

**Comment by mrmcnerd** [comment]
I tried a small test against the actual API. It works great, as per documentation. I'd also vote to merge this.

**Comment by curtis-h** [comment]
Great, thanks everyone! :)

**Pull request merged**
