### PR TITLE
added Date to extent() for d3, and make the index optional

### PR DESCRIPTION
**Pull request by co-dh**

### CODE REVIEW

**Comment by co-dh** [comment]
The implicitly error is not related to this change.
Somebody have added --noImplicitAny to the test.

**Comment by vvakame** [comment]
um? d3-tests.ts passed `--noImplicitAny` in 77d4701d466eb65f08efc8d28114314777a6210f 
please rebase to master/HEAD

**Comment by co-dh** [comment]
I've made it pass. Can anybody merge the pull request?

**Comment by vvakame** [comment]
please squash & push -f .
this pull request has very huge diff. We can't review this pull request...
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6595/files

**Comment by co-dh** [comment]
Please use 6713 instead.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6713

**Pull request closed without merging**
