### PR TITLE
lodash: compile error in _.partial fixed

### PR DESCRIPTION
**Pull request by chrootsu**
Issues https://github.com/borisyankov/DefinitelyTyped/issues/6461 and https://github.com/borisyankov/DefinitelyTyped/issues/6462 fixed

### CODE REVIEW

**Comment by piyushchauhan2011** [comment]
Builds nicely, please merge!

screen shot 2015-10-28 at 12 00 48 pm

**Comment by piyushchauhan2011** [comment]
any updates ? The last PR merge is causing us pain, if possible please merge this ASAP.

**Comment by vvakame** [comment]
thanks mate!

**Comment by iamryandrake** [comment]
Thank you! Thanks @piyushchauhan2011 for following up.

**Pull request merged**
