### PR TITLE
[@types/bull] Update Queue and Job definitions

### LINKED ISSUE #38619: [@types/bull] Missing "notFetch " in Job.moveToCompleted
- [ ] I tried using the `@types/bull` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder , @JProgrammer , @marshall007, @danmana， @aleccool213 

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by douglascayers**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - [Queue.close](https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L533)
  - [Job.moveToCompleted](https://github.com/OptimalBits/bull/blob/develop/lib/job.js#L208)
  - Fixes #38619

### CODE REVIEW

**Review by pc-jedi — CHANGES_REQUESTED** [review]
Could you please do not change the indention?
This makes it impossible to review the PR.

**Comment by douglascayers** [comment]
@pc-jedi Sure, sorry about that. Seems my IDE has a "format on save" option enabled.

**Comment by douglascayers** [comment]
@pc-jedi, fyi on the diff page you can hide whitespace changes and that shows the actual changes, but I'll push a new commit without formatting changes

image

**Review by pc-jedi — APPROVED** [review]
LGTM :+1: 
Thank you for the contribution :slightly_smiling_face:

**Comment by douglascayers** [comment]
Thank you 🙂

**Pull request merged**
