### PR TITLE
[react] Add support for BigInt in `key`

### PR DESCRIPTION
**Pull request by MarceloSpessoto**
Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react/issues/27351>>
- [x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b71befdab38f7ff84ca5f10ab43ea2ee31dc9cb4
</p>

**Comment by MarceloSpessoto** [comment]
@eps1lon, I have fixed my PR and added the changes you have requested. I believe it is now ready to be merged.

**Comment by MarceloSpessoto** [comment]
Ok, I have just removed an incorrectly placed bigint declaration, now it is finished

**Review by eps1lon — APPROVED** [review]

**Comment by zombieJ** [comment]
This is potential breaking change since typescript not support `bigint` as key of object even it does support in real world.

**Comment by yoyo837** [comment]
Just 3 lines of code made a huge difference.

**Comment by gioacostax** [comment]
This breaks my code with

`Property 'children' is missing in type 'Element' but required in type 'ReactPortal'`

in every `createPortal` and `render` functions.

Downgraded to `18.2.21`

**Comment by teobmg** [comment]
Same issue here.
image

**Comment by eps1lon** [comment]
> This is breaking typings for different types that do not expect bigint in the Key type: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66749

This sort of breakage is expected and will not be fixed. `React.Key` was never intended to be used to index objects. It structurally matched that purpose but not semantically.

The other issues are likely due to having multiple versions of `@types/react` installed. For how to fix, check out https://solverfox.dev/writing/duplicate-types-react

**Comment by dcastil** [comment]
> This breaks my eslint and tsc with
> 
> `Property 'children' is missing in type 'Element' but required in type 'ReactPortal'`
> 
> in every `createPortal` and `render` functions.
> 
> Downgraded to `18.2.21`

Had this too and was indeed due to having multiple version of `@types/react` installed. Thanks @eps1lon!

**Pull request merged**
