### PR TITLE
slate-react: Separated type for onChange function

### PR DESCRIPTION
**Pull request by yurist38**
A small change in order to be able to import and re-use types of `onChange` function and its parameter.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andrewbranch** [comment]
I would suggest, rather than using this PR, doing

```ts
import { BasicEditorProps } from 'slate-react';
type OnChangeFunction = BasicEditorProps['onChange'];

// Or, if you need to remove `undefined` from the domain:
type OnChangeFunction = Exclude<BasicEditorProps['onChange'], undefined>;

// To get the parameter type:
type OnChangeParam = OnChangeFunction extends (p: infer P) => unknown ? P : never;
```

It seems like having a unique reference to this type is a bit of an edge case, and as such I think it’s better not to add new types to the exports when you can get them other ways.

**Comment by yurist38** [comment]
@andrewbranch To be honest, I don't agree that it's an edge case. If you write the event handler function (what you most probably will do when using this component) you will need those types. And the way you suggested not a friendly one, too complicated, as for me. Consumers of the package should not do this, it's much easier to simply export it. I don't see any problem with exporting it.

**Comment by andrewbranch** [comment]
Consumers of the package needn’t do either. I’m actually a Slate user myself, coincidentally, and I used contextual typing:  https://github.com/andrewbranch/blog/blob/50939b0baf65839a724543694578ef23952d8697/src/components/InteractiveCodeBlock/InteractiveCodeBlock.tsx#L235

If I had really wanted to write it as a separate function, I don’t think it’s unfriendly to do

```tsx
const onChange: EditorProps['onChange'] = ({ value, operations }) => {
  //
};

<Editor onChange={onChange} />
```

([Note this technique is already used in slate-react typings hundreds of times.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36789/files#diff-5d1ba452e78bcfee7592a6cc1c9b7ccaL151))

There’s no real problem with exporting it, it’s just a bit unusual. And it’s unclear why `onChange` should get its own exported type and not, for example, [decorateNode, renderEditor, renderMark, renderBlock, renderDocument, renderInline, and shouldNodeComponentUpdate](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36789/files#diff-5d1ba452e78bcfee7592a6cc1c9b7ccaR85). I think things would start to get messy if all of them had named, exported types for their functions and their params.

But, my job isn’t to stop you, I just wanted to offer an alternative in the absence of @andykent, @majelbstoat, @JanLoebel, @PatrickSachs, @YangusKhan, @isubasti, @sgreav, @Kornil, @jackall3n, and @benjiro—I would really prefer for one of them to weigh in. I’ll wait a little longer after this second ping, and then come back around after a couple days to merge this if nobody else reviews. Thanks for hearing me out!

**Comment by yurist38** [comment]
Thank you for the explanation @andrewbranch ! I've got your point and the alternative you've suggested is a good option too. Let's see maybe we will get more feedback on this. Thanks again for your time! 👍

**Comment by andrewbranch** [comment]
Well, no one else showed up, so I guess you win by default 😄

**Pull request merged**
