### PR TITLE
Update Kendo UI definitions to 2015 Q3 SP1

### PR DESCRIPTION
**Pull request by tsvetomir**
These are the latest TypeScript definitions for Kendo UI, version 2015.3.1111.

Thanks!

### CODE REVIEW

**Comment by vvakame** [comment]
@stefanrahnev can I merge this PR?

**Comment by stefanrahnev** [comment]
Yes, @vvakame. It was submit by the team lead of the product team developing the Kendo UI library.

**Comment by vvakame** [comment]
okay, thanks mate.

**Comment by stefanrahnev** [comment]
sure, thank you, too.

**Pull request merged**
