### PR TITLE
Resolves #8227 - splits Electron into github-electron-main & github-electron-renderer because the environments are different

### LINKED ISSUE #8227: Re-split electron definitions into common, main, and render APIs
I propose that this change get reversed: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b10b59fe42978878f23b6bbae44c1c98a76ec492#commitcomment-16281602

"The purpose of using typescript is the strong typing and compile time errors about things that won't be valid at runtime. Combining the definitions of the main and render environments bypasses compile-time checks and allows attempts to use render-only APIs in the background scripts and background-only APIs in the foreground scripts."

### PR DESCRIPTION
**Pull request by JasonKleban**
Splits the electron type definitions into new environment-specific main
worker and renderer definitions for Typescript 2.0+
- [✓] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [✓] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [✓] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.
- [✓] passes travis-ci tests

### CODE REVIEW

**Comment by JasonKleban** [comment]
The naming is based on the naming of the unioned `github-electron` definitions and this particular library/libraries is a little non-standard.

**Comment by JasonKleban** [comment]
These are both optional things, but to address any concerns that might be raised:

I do suggest to the community that we should deprecate the unioned `github-electron` because its types cannot be correct for any one environment and maintaining the shared definitions among all three packages is even more burdensome than these two new ones that are required.

If there were a way to have a dependency from both of these on another new `github-electron-common` to avoid the duplicate maintenance of the shared types, that would also be an improvement.  But I'm not aware of that feature being currently supported by tsd, etc.

**Comment by vvakame** [comment]
related? #10993

**Comment by andy-ms** [comment]
Pinging anyone I could find: @rhysd @mmc41 @vvakame @miniak
Could one of you review this?

**Comment by miniak** [comment]
Do we need the github prefix?

**Comment by miniak** [comment]
Also this change is based on Electron 1.3.3 version of the typings. It has to be based on the latest version.

**Comment by miniak** [comment]
Also, unless there is a way to share the common stuff, I don't agree with this chnage. You can use remote the access all the main modules from renderer. I really don't want to modify 2 definitions all the time.

**Comment by vvakame** [comment]
ummm... I'm not electron user now. I want to wait reviewer's opinion.
IMHO, We should keep directory name should be link to npm package name 1 by 1.

**Comment by rhysd** [comment]
I also disagree with this change because these files include multiple 'electron' modules in `github-electron-renderer.d.ts` and `github-electron-main.d.ts`.  They causes compilation error with module name collision when we install both `@types/github-electron-renderer` package and `@types/github-electron-main.d.ts` with npm.  So, if splitting definitions to two files, we will not be able to use the definitions for rendrer and main at the same place.

**Comment by JasonKleban** [comment]
I do agree that it would be better if the common definitions could be shared.  Maybe the new npm stuff can support that.  

But regarding conflicting module names: it is exactly the point that there is no single Electron environment - so the types assumed should only be one or the other.  The npm-supported projects should be kept separate.

**Comment by JasonKleban** [comment]
There are other libraries with dependencies on other types.  Can it work if there is a third github-electron-common.d.ts that would be referenced by both?

**Comment by yuit** [comment]
@JasonKleban  I will close this PR for now since reviewers @miniak and @rhysd have some disagreement with the change. Feel free to reopen or open issue if you feel that the change is necessary and further discuss with others

**Pull request closed without merging**
