### PR TITLE
Create a non-instantiated Xrm module

### PR DESCRIPTION
**Pull request by markusmauch**
Makes the Xrm `object` available in the browser's `window` object (`window`, `parent`, `top`, etc.) by introducing a dedicated interface `XrmStatic` and extending the `Window` interface specified in `lib.d.ts`:

```
interface Window {
    Xrm: Xrm.XrmStatic;
}
```

The `XrmStatic` interface is added to the already existing `Xrm` module:

```
declare module Xrm {
    interface XrmStatic {
        Page: Page;
        Utiltiy: Utiltiy;
    }
    module Page {...}
    module Utility {...}
}
```

To make the `Xrm` object globally available (not as a property of `window`) the following declaration is best practice:

```
declare var Xrm: Xrm.XrmStatic;
```

Declaring a variable and a module with the same name works only if the module is a so-called non-instantiated module (see section 2.3 of the TypeScript 1.5 language specification for more details). The current implementation of the `Xrm` module contains enums and is therefore introduced to the declaration space.

In order to solve this problem, the present proposal extracts the enums `FormType`, `SaveMode`, `StageCategory`, `GridControlContext`, `ViewType` into a separate `XrmEnum` module, allowing the `Xrm` module to be non-instanciated:

```
module XrmEnums {
    export const enum FormType {...}
    export const enum ViewType {...}
}
```

This allows to keep almost the entire Library within the `Xrm` root and also having a type (`Xrm.XrmStatic`) that can be referenced.

### CODE REVIEW

**Comment by markusmauch** [comment]
Any comments on this proposal?

**Comment by vvakame** [comment]
okey, we can't get response from reviewers. I decided to merge this PR. thanks!

**Comment by 6ix4our** [comment]
@vvakame  I apologize for the delay, but my daughter had surgery recently, and I've been a single parent with the rest of the kids, and taking care of a myriad of other things.  I'm not convinced of the wisdom of implying that *all* parenting Window objects know about "Xrm" or have an Xrm member, because there are situations in which they definitely do not, however they would be able to obtain Xrm context information.  While I appreciate the goals of this PR, I was *not* on board with this particular adjustment.

**Comment by vvakame** [comment]
oh... I'm praying your god. don't worry.

**Comment by markusmauch** [comment]
@6ix4our If you don't like the window thing we could settle this by simply *removing* the following interface extension from my proposal:
```
interface Window {
    Xrm: Xrm.XrmStatic;
}
```
The important improvement is that there *is* a type that can be referenced: ``Xrm.XrmStatic``. Those who need the window extension can place it elsewhere in their code, anyway.

If you still don't see the benefit of my proposal feel free to let me know and I will try to explain better.

**Comment by 6ix4our** [comment]
@markusmauch I completely appreciate the approach you've taken, and with the PR merged now, we'll all be able to benefit.  I generally *extend* Window with an alternate interface that provides the "Xrm" object.... but I haven't needed to do that in long time, because I prefer using Window.sendMessage() to communicate between Web Resources and their containing form.  This is an HTML5 spec that helps abstraction, and provides for better automated test scenarios.  I let form scripts worry about the form, and Web Resource scripts worry about the HTML Web Resource--with sendMessage facilitating the interchange of information between them in a standard, secure way.  Allowing cross-frame scripting is no longer a requirement of my work.

**Pull request merged**
