### PR TITLE
[serverless-step-functions] Add types for JSONata

### PR DESCRIPTION
**Pull request by zirkelc**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://states-language.net/
  - https://docs.aws.amazon.com/step-functions/latest/dg/transforming-data.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/serverless-step-functions/types/map.d.ts
1. types/serverless-step-functions/types/wait.d.ts
1. types/serverless-step-functions/serverless-step-functions-tests.ts
1. types/serverless-step-functions/types/fail.d.ts
1. types/serverless-step-functions/types/choice.d.ts

<details>
<summary>as well as these 4 other files...</summary>
<p>types/serverless-step-functions/types/task.d.ts, types/serverless-step-functions/types/pass.d.ts, types/serverless-step-functions/types/parallel.d.ts, types/serverless-step-functions/types/succeed.d.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c42eec3f5a09d2f23bc5687078eee12692d4acd
</p>

**Comment by ebisbe** [comment]
Hey @zirkelc I'm OOL for JSONata. First time hearing this was with this PR. Looks ok to me but have no clue if it's wrong or right. Should I just approve? 🙈 ?

**Comment by zirkelc** [comment]
Yes, please! 😄

**Review by ebisbe — APPROVED** [review]

**Comment by zirkelc** [comment]
Ready to merge

**Comment by julian99m** [comment]
This appears to be a breaking change, dropping support for part of the JsonPath-style configuration: The `ItemsPath` field is not present anymore, even though it is still part of the [states-language](https://states-language.net/).
Could you please confirm or explain if this is configured in another way now?

**Comment by zirkelc** [comment]
@julian99m I think this was a mistake, the field was dropped while re-organizing the fields on the `Map` state

I created PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72642 to add it back in, please take a look.

Furthermore, would you mind if I add you to the list of owners of the package?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a21a7b75db006fa02186f6c15c75c310b2318e8f/types/serverless-step-functions/package.json#L11-L20

This would notify you in case of future changes and allow you to approve them.

**Comment by julian99m** [comment]
Hi @zirkelc, thanks for the quick response+fix 😄 
Yes, that would be fine, thanks 👍

**Pull request merged**
