### PR TITLE
Fix issue where Sequelize.Model.scope would not respect children

### PR DESCRIPTION
**Pull request by todd**
The `Model.scope` method in Sequelize returns a new version of `Model` with the scope applied. The existing method signature is fine for this if you haven't defined custom types that inherit from `Model`, but, if you have, specifying `this` as the return type in the type definitions wreaks havoc with your own code. Consider:
```typescript
const scope = MyModel.scope('someScope');
const theThing = await scope.find({ where: { some_attr: 'foobar' } });
```

Results in:
```
Argument of type '{ where: { some_attr: string; }; }' is not assignable to parameter of type 'FindOptions<TAttributes & {}>'.
  Types of property 'where' are incompatible.
    Type '{ some_attr: string; }' is not assignable to type '(string | col | and | or)[] | fn | where | WhereOptions<TAttributes & {}>'.
      Type '{ some_attr: string; }' is not assignable to type 'WhereOptions<TAttributes & {}>'
```

`some_attr` may be specified on your own `TAttributes` definition, but the Sequelize definitions ignore them when the method returns `this`. Changing to `Model<TInstance, TAttributes>` clears the issue and should be functionally equivalent.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-scope
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by todd** [comment]
I feel like this fell off the Merge board after I resolved that merge conflict - what's the proper way forward here? I'd really like to get this merged.

**Comment by jpdutoit** [comment]
This is inconvenient. I was relying on the fact that scope returns my Model subclass. I haven't seen it wreak any havoc. Checking the sequelize source code, they do in fact return an extended version of `this`.

**Comment by jpdutoit** [comment]
I extend my model objects with helper methods. Before this change I could call those helper methods after calling .scope:  but now it is prevented by the type checker

I.e.
```
Model.scope("extraStuff").helperMethod(...args)
```

Since `helperMethod` does exist on the result of the scope call I am inclined to think this change is a regression. Is there another way to fix the issues you were having?

**Comment by todd** [comment]
How are your models defined such that TypeScript gains the ability to introspect it and see your static method? And are your static helper methods performing your queries for you? The primary issue I'm working around here is that having the return type be `this` wipes out the type checker's knowledge of the attributes associated with my model, resulting in `FindOptions` not recognizing them.

I wonder if a union type would work instead, but I'd still like to know more about your use-case.

**Comment by jpdutoit** [comment]
I make use of the following pattern to extend my sequelize models:

```
export const Schema = {
  id: Sequelize.STRING,
  field: Sequelize.STRING
}

export interface Column {
  id: string
  field: string
}

export interface Instance extends Sequelize.Instance<Column>, Partial<Column> {}
type BaseModel = Sequelize.Model<Instance, Column>
type Options = Sequelize.FindOptions<Column>

export interface Model extends BaseModel {
  helperMethod(id: string): Promise<string | undefined>
}

export function createModel(sql: Sequelize.Sequelize): Model {
  return Object.assign(sql.define<Instance, Column>("model", Schema), {
    async helperMethod(this: Model, id: string): Promise<string | undefined> {
      let row = await this.findById(id)
      return row ? row.field : undefined
    }
  })
}

const column = createModel(new Sequelize("database"))
column.scope("someScope").helperMethod("id")
```

And the last line is the one that fails to compile after this PR, but not before.

**Comment by jpdutoit** [comment]
@todd Have you looked into this more? Can we revert this change?

**Comment by todd** [comment]
@jpdutoit Sorry, I haven't had the time to really dig into this. I'm not really sure why my change breaks this for you, but I'm not sure I've ever seen the pattern you're using here for model definition.

**Comment by todd** [comment]
@jpdutoit I've spent the last hour or so looking into this and I think I agree with you that this is indeed a regression. I'll need to find some other way to get `FindOptions` to honor my attributes. I'll open a PR reverting this change and adding a test for your use-case.

Sorry about that.

**Pull request merged**
