### PR TITLE
[node] Add `node:`‑prefixed module aliases

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
	- <https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_node_imports>
	- <https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_node_imports>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by rbuckton** [comment]
I think using the non-prefixed version is the correct call, as anyone currently using module augmentation against a module like `fs`, for example, wouldn't be broken by this change. Users will have to take care, however, that they don't add module augmentations for the `node:`-prefixed versions. It may be worthwhile to add a comment as to why the non-prefixed form is the version that contains the definitions. 

This does lead to an interesting discussion we should have in the TypeScript team about the possibility of defining multiple canonical names for a package *in the package itself* (as I think this can be accomplished using `"paths"` on a per-project basis). I've filed https://github.com/microsoft/TypeScript/issues/42764 to track this on the TypeScript side.

/cc @DanielRosenwasser @sheetalkamat

**Review by rbuckton — APPROVED** [review]

**Comment by Flarna** [comment]
As far as I know the prefixed versions work only in esm mode but not in commonjs.
But I guess there is no way to add the prefixed versions only if users transpile to esm.

**Comment by ExE-Boss** [comment]
Ready to merge

**Comment by ExE-Boss** [comment]
@Flarna The `node:`‑prefixed form is coming to **CommonJS** as well: <https://github.com/nodejs/node/issues/36098> (PR <https://github.com/nodejs/node/pull/37246>)

**Comment by lucascaro** [comment]
I think this change broke my IDE (vscode), it will alwaws add the `node:` prefix to all imports even when working with commonjs modules. node itself has no idea how to "`import path from "node:path"` or what `node:path`.

is there any way to opt out and back into the non-prefixed version?

**Comment by ExE-Boss** [comment]
@lucascaro That will most likely depend on <https://github.com/microsoft/TypeScript/issues/42764>.

**Comment by SimonSchick** [comment]
Should we perhaps temporarily revert this then? I have not seen the `node:` prefix in the wild _yet_.

**Comment by lucascaro** [comment]
either reverting or moving the prefixed declarations after the non-prefixed ones would work, I think.

**Comment by adekau** [comment]
> Should we perhaps temporarily revert this then? I have not seen the `node:` prefix in the wild _yet_.

I discovered this pull request after looking into a StackOverflow question (https://stackoverflow.com/questions/67172090/vscode-typescript-why-suggest-auto-import-from-nodepath), so it seems like something that is starting to show up in the wild.

**Comment by G-Rath** [comment]
@ExE-Boss @SimonSchick I think we should just revert this for now, at least until it lands in new versions of node. Ideally it might best to wait until this feature is available in the current LTS (which if I'm understanding things correctly, will be v16 which is in a few months so not that far away).

It might be worth including a check for this in `eslint-plugin-node` too? (/cc @mysticatea - I'm thinking one of the `node/no-unsupported-features` rules maybe?)

**Comment by matt-huh** [comment]
Reverting this sounds good. VSCode does auto imports well for my old projects, but it's broken for my new projects with the latest type definition.

**Comment by SimonSchick** [comment]
Currently my nodev15 PR contains node aliases, can we have a decision here so I can either remove them or move forward?

**Comment by ExE-Boss** [comment]
@SimonSchick I’d prefer if we tried moving the `node:`‑prefixed module names after the unprefixed forms before removing them entirely.

**Pull request merged**
