### PR TITLE
Add node-resque.Queue.enqueueAt

### PR DESCRIPTION
**Pull request by gfoltz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/taskrabbit/node-resque/blob/master/lib/queue.js#L56
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by gordey4doronin — APPROVED** [review]

**Comment by gordey4doronin** [comment]
@gfoltz JFYI There is also WIP PR which brings many others changes including `enqueAt` and should be merged soon. #39973 But your PR doesn't hurt anyway.

**Comment by gfoltz** [comment]
@gordey4doronin thanks for the quick approval. I updated my branch to include the `redis` attribute, as I described in my comment here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39973#issuecomment-548432911

**Comment by gfoltz** [comment]
rebased on new master because a build step kept failing for unclear (to me) reasons

**Comment by gordey4doronin** [comment]
Here is an issue for failing build https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40054

**Comment by gordey4doronin** [comment]
@gfoltz All the changes have been pulled to another PR. I think this one can be closed. Thanks for the proposed chnages!

**Comment by petetnt** [comment]
Thanks @gfoltz ! Should have added you as an additional contributor but the PR was merged before that.

**Pull request closed without merging**
