### PR TITLE
style(geojson): prettier ts files

### PR DESCRIPTION
**Pull request by wangxingkai**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

No type definition changes.
 
All style changes are made by running `npm run prettier -- --write types/geojson/**/*.ts` as suggested in here:
https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes

### CODE REVIEW

**Comment by wangxingkai** [comment]
@icholy follow up with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61105#issuecomment-1182641767

**Review by icholy — APPROVED** [review]

**Review by JeffJacobson — APPROVED** [review]
Looks OK.

**Review by JeffJacobson — APPROVED** [review]

**Review by navya9singh — APPROVED** [review]

**Comment by wangxingkai** [comment]
Ready to merge

**Comment by byalesk99** [comment]
Hello, we are getting below error on updating @types/geojson to 7946.0.10

Error: Error at node_modules/@types/geojson/index.d.ts:79:13: Type alias 'Geometry' circularly references itself.

Version History: 
@types/geojson@7946.0.10
@types/highcharts@5.0.0

Please let us know if we are missing any or any workaround to use updated version without any issues.

P.S: It's working fine with [7946.0.8](https://www.npmjs.com/package/@types/geojson/v/7946.0.8)

export interface GeometryCollection extends GeoJsonObject {
    type: "GeometryCollection";
    geometries: Geometry[];
}

**Pull request merged**
