### PR TITLE
Update Meteor type definitions to v1.4

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.meteor.com/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by birkskyum** [comment]
I'm writing an extensive guide on how to use TypeScript with Meteor, so I'm interested in having an updated version of the meteor type definitions available for easy install through @types/meteor

I have therefore moved the contents of https://github.com/meteor-typings/meteor/tree/master/1.4 to DefinitelyTypes, and it seems to be working great.

**Comment by fullflavedave** [comment]
This looks good -- thumbs up!  It makes sense since the meteor-typings/meteor definitions were the best definitions up to this point.  I was actually planning on doing the same in the next couple of weeks, so you saved me the effort.  Thanks for your contribution!

The only housekeeping left is to make sure that the last two PRs to this repo are included in these definitions, and if not, re-add them.

**Comment by birkskyum** [comment]
Great, which two PRs are you referring to, and is it something I can help with?

**Comment by fullflavedave** [comment]
It looks like #14624 was already corrected in the meteor-typings/meteor definitions that were copied over -- so this one is accounted for.  However, there wasn't a test written for it, which would be a nice-to-have.  You probably noticed that there are a lot of holes in the test coverage.  Although it might be time-consuming to get to 100% coverage, I was trying to at least create a test for all new updates to the definitions for bugs fixed or pull requests merged.

#14718, adding `Accounts._hashPassword()` isn't in the new definitions.  Even though the underscore indicates it's not a stable part of Meteor core (as far as a dependable public API), I'm inclined to leave it in the definitions and let users use it at their own risk since you can find it referenced in Meteor forums, etc.  Here are two conversations about it:  https://github.com/meteor/meteor/pull/2271, https://github.com/meteor/meteor/pull/3410.

**Comment by minestarks** [comment]
@fullflavedave want to make sure I'm reading this right - are you suggesting changes or should I merge? Thanks.

**Comment by fullflavedave** [comment]
Sorry for the lack of clarity -- please merge.

**Comment by minestarks** [comment]
No problem! Not familiar with this library and didn't want to jump the gun. Thanks for the review.

**Comment by pdthang59** [comment]
Hello @birkskyum 

I tried your Series of https://medium.com/@birkskyum/modern-meteor-development-with-typescript-introduction-836f2a89f79
 to apply on https://www.meteor.com/tutorials/react/creating-an-app  example.

I met issue like this: 

```
imports/ui/Task.tsx (8, 23): Property 'task' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.
imports/ui/Task.tsx (14, 6): Property 'propTypes' does not exist on type 'typeof Task'.
```

Can you check it ? Thanks

**Pull request merged**
