### PR TITLE
Update react-redux to support `redux`'s types

### PR DESCRIPTION
**Pull request by 7mllm7**
More info https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9611

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by 7mllm7** [comment]
@typescript-bot there ya go :)

**Comment by uniqueiniquity** [comment]
@7mllm7 I'm not sure this is fixing the issue you intend it to be fixing.
Reading the thread you linked, it seems like your goal is to provide the `Dispatch` type a type argument where _required_. However, the types for Redux express it as having an optional type parameter, where if no type parameter is supplied it will default to `AnyAction`.
I'm a bit surprised you're getting compiler errors that are complaining about `Dispatch` requiring a type argument. What version of TS are you compiling with?

**Review by uniqueiniquity — DISMISSED** [review]
See previous comment.

**Comment by michal-ciechan** [comment]
@uniqueiniquity I am getting the same issues with dispatch with the latest version of all assemblies. This seems to be the case because Redux (latest: `4.0.0`) now provide their own TS file which  contains:

redux\index.d.ts
---

```
export interface Dispatch<A extends Action = AnyAction> {
  <T extends A>(action: T): T;
}
```

And using latest typescript `3.0.1` and VS Code I am also getting the following error:

```
(192,16): Generic type 'Dispatch<S>' requires 1 type argument(s).
```

Although after using the fix in this pull request, I get the following error:

```
 Generic type 'Store<S>' requires 1 type argument(s).
```

Which I fixed by changing 

```
export interface ProviderProps<A extends Action = AnyAction> {
    /**
     * The single Redux store in your application.
     */
    store: Store<any, A>;
}
```
to

```
export interface ProviderProps<A extends Action = AnyAction> {
    /**
     * The single Redux store in your application.
     */
    store: Store<any>;
}
```

**Comment by sm-tc** [comment]
Any updates on this? Had the same issue and a combination of @7mllm7 and @michal-ciechan 's changes resolved the problem for me.

**Comment by johnolos** [comment]
I can confirm that combination of @7mllm7  and @michal-ciechan 's changes resolves the problems for me as well.

**Comment by DanielRosenwasser** [comment]
So here's my take

1. This change shouldn't be needed
2. but it only seems to be the case that it works in nightly versions of TypeScript so
3. the change appears to be appropriate.

:+1:

**Comment by sm-tc** [comment]
@DanielRosenwasser fwiw the root cause for me turned out not to be react-redux types; instead my issue was some weird npm module resolution.

```
node_modules/
  redux/ <-- my own redux; version ^4.0.0
  @types/
    react-redux/<-- package.json lists redux: ^4.0.0
    react-intl-redux/ <-- package.json lists redux: ^3.6.0 as a dependency
      node_modules/
        redux/

```

For some reason, the `import { ... } from 'redux'` in react-redux `index.d.ts` was pulling redux in from `node_modules/@types/react-intl-redux/node_modules/redux` instead of `node_modules/redux` and then I guess the out of sync type definitions were causing the actual problem. I can't speak for the other guys, but I was able to fix the problem just by removing react-intl-redux (i.e. removing/reverting the added `Action` type parameter here and the change @michal-ciechan made to Store as well). 

I suspect that they're having the same problem as well - maybe not necessarily with the same package but probably the same weird module resolution thing as I had. Given @types/react-redux gets ~430k downloads a week I can't imagine only a handful of people would be commenting here if it was actually down to this repo.

**Comment by DanielRosenwasser** [comment]
@sm-tc Right - I found that TypeScript was correctly resolving `redux` in nightly versions of TypeScript, but not in older versions. I figure this must be a bug of some sort (and perhaps @sheetalkamat knows why it occurred) but I figured using explicit type arguments really couldn't hurt.

**Comment by michal-ciechan** [comment]
@sm-tc How can I find out where `import { ... } from 'redux'` is pulling its typings from?

**Comment by michal-ciechan** [comment]
@DanielRosenwasser  the root cause of my issue was similar to @sm-tc, but for me it was picking up `redux ^3.6.0` from `react-logger` package.

I manually changed that`react-logger` (`node_modules/@types/redux-logger/package.json`) to point to `redux: 4.0.0` and deleted the `node_modules/@types/redux-logger/node_modules/redux` folder.

FWIW

The way I found that it was using `react-logger` specific version was by searching for `"redux"` and looking at any `import { .... } from `redux`` and hovering over it in VS Code to see what package it was importing. It then showed `node_modules/@types/redux-logger/node_modules/redux` folder in the tooltip.

**Comment by maxkostow** [comment]
@DanielRosenwasser I think this change prevents you from using redux-thunk actions in mapDispatchToProps since you cannot control the Dispatch type

**Pull request merged**
