### PR TITLE
ui-grid: Made the enableColumnResizing field optional.

### PR DESCRIPTION
**Pull request by baltie**
Also added a test for creating an empty IColumnDef object, implying
setting everything to default values.

### CODE REVIEW

**Comment by vvakame** [comment]
*ui-grid/ui-grid.d.ts*

to author(@btesser). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by btesser** [comment]
Looks good to me

**Comment by baltie** [comment]
@vvakame @btesser My PR was made obsolete (apart from the test) by #5650 which was the exact same change. Some specific reason why that one was merged directly and not this?

**Comment by btesser** [comment]
@baltie no idea

**Comment by baltie** [comment]
Well, it doesn't matter much, of course, I guess we both had the same need for this fix. ;) I'm just curious if I did something wrong with regard to contributions guidelines or something.

**Comment by vvakame** [comment]
wow, @baltie & @btesser sorry #5650 was merged...

**Comment by baltie** [comment]
Well, I guess that kinda answers my question. Thanks. :) (Though I still think the test had some (smallish) value. ;) ).

**Pull request closed without merging**
