### PR TITLE
Add Shopify Prime to notNeededPackages.json

### PR DESCRIPTION
**Pull request by nozzlegear**
This pull request adds Shopify Prime to the list of packages that provide their own definitions, [as recommended by the TypeScript handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

### CODE REVIEW

**Comment by sandersn** [comment]
Looks good to me. Can you merge from types-2.0 before I merge the PR?

**Comment by nozzlegear** [comment]
Okay I just merged from types-2.0, though I'm not sure I did that correctly.

**Comment by paulvanbrenk** [comment]
@nozzlegear that last merge doesn't seem right, there's now a ton of unrelated changes. If you can create a new clean PR, based of typings-2.0, and ping me I'll merge it in.

**Comment by paulvanbrenk** [comment]
Replaces with #13030

**Pull request closed without merging**
