### PR TITLE
Lodash: `pickBy`: add overload for user defined type guards

### PR DESCRIPTION
**Pull request by OliverJAsh**
Similar to the overloads we have for `filter`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d360bc9e009c58230bcf327c53410f9d550b3273/types/lodash/lodash-tests.ts#L1776

If this looks good, I will go ahead and complete the tests for the other Lodash variants.

For some reason, when trying to lint locally with these changes, I get a memory allocation error. However, I can see the correct type being returned by `pickBy` in my IDE.

/cc @aj-r 

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by aj-r — COMMENTED** [review]
Looks good to me.

The problem with lodash tests is that they are so big that they can easily cause NPM to run out of memory. Since the change you made is very small, I'm guessing that this is happening because there is an error in a previous version of typescript.

To diagnose the error, try temporarily deleting all tests except `pickBy` - then hopefully NPM will have enough memory to tell you the real error.

**Review by aj-r — CHANGES_REQUESTED** [review]
Also don't forget to do `npm run generate` to update the `lodash/fp` definitions. See `readme.md` in the lodash folder. (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/readme.md)

**Comment by OliverJAsh** [comment]
@aj-r Thanks for the helpful debugging info. I followed the steps for debugging the tests with regards to the memory issue. Oddly, the tests pass if I delete the top or bottom half, but when I try to run them all at once, I get memory errors.

The docs says this:

> Note: If both halfs succeed on their own, then the tests are probably just consuming too much memory. Try simplifying them until they pass.

However I only added one test in this PR. 🤔

**Comment by aj-r** [comment]
> Oddly, the tests pass if I delete the top or bottom half, but when I try to run them all at once, I get memory errors.

That's unfortunate. I didn't think that 20 lines of code would put you over the memory limit, but apparently it does. There may not be much you can do except find some tests that don't look super important, and delete them to make room :P. Or complain to the TypeScript team.

**Comment by OliverJAsh** [comment]
@aj-r I've updated this PR. Mind giving it a 👍?

**Review by aj-r — APPROVED** [review]

**Pull request merged**
