### PR TITLE
[@types/line-by-line] Fixed stream use case

### PR DESCRIPTION
**Pull request by seancroach**
Checklist:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Because I'm changing an existing definition...
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Osterjour/line-by-line#api and https://github.com/Osterjour/line-by-line/blob/master/line-by-line.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by TheEdgyDev** [comment]
The Travis CI build failed because of an error originating from ../node/v7/index.d.ts, not as a result of my modifications.

**Comment by jessetrinity** [comment]
@TheEdgyDev is @etomsen no longer maintaining this?

**Comment by TheEdgyDev** [comment]
Given his lack of communication and tracking the updates of line-by-line, I can only assume @etsomen is no longer maintaining this.

**Comment by jessetrinity** [comment]
It might be preferable to let people remove themselves if they no longer wish to receive notifications. We do allow multiple owners so you can just add yourself instead of replacing the owner.

**Pull request merged**
