### PR TITLE
github-electron: merge back into a single file to fix issues with 'typings'

### PR DESCRIPTION
**Pull request by miniak**
Moving individual Electron modules into separate files apparently was not a good decision of mine. It caused this issue:

```
typings install --ambient --save github-electron
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/node/node.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.app.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.auto-updater.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.browser-window.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.clipboard.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.content-tracing.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.crash-reporter.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.desktop-capturer.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.dialog.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.dom.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.event-emitter.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.global-shortcut.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.ipc-main.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.ipc-renderer.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.menu.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.menu-item.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.native-image.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.power-monitor.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.power-save-blocker.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.protocol.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.remote.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.screen.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.session.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.shell.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.tray.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.web-contents.d.ts" during installation from "github-electron"
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87b243541e9c2f99ccf772d8eccf4f45f9ee767a/github-electron/github-electron.web-frame.d.ts" during installation from "github-electron"
github-electron
└── (No dependencies)
```

The user would have to manually install all references, as typings does not currently support following references: https://github.com/typings/typings/issues/227.

### CODE REVIEW

**Comment by miniak** [comment]
@ToastHawaii the endline change was necessary as I wasn't able to work with the repository properly.

**Comment by rhysd** [comment]
Gathering all PRs to this one is better.  Nice work :+1:

**Comment by ToastHawaii** [comment]
:+1:

**Comment by vvakame** [comment]
@miniak please resolve conflict.
@jedmao can I merge this PR?
@rhysd @ToastHawaii :+1:

**Comment by miniak** [comment]
@vvakame resolved

**Comment by jedmao** [comment]
:+1:

**Comment by miniak** [comment]
@vvakame can you please merge this? All the involved parties have approved of the changes.

**Comment by HB-2012** [comment]
Yes, please merge! The github-electron library is basically unusable in this form.

I ran into the issue of having to install all dependencies manually. This Pull Request offered me some sort of help, but I'm running into issues with typings failing to connect to GitHub.. waiting for this to be merged. :)

**Comment by andrefgneves** [comment]
Please merge this

**Comment by miniak** [comment]
This is starting to get ridiculous. It's already been 10 days since I created this PR to fix the annoying problem that I have caused by splitting the typings into separate files, and it's still not merged. What are we waiting for?

**Comment by vvakame** [comment]
waiting for my room. sorry for late.

**Pull request merged**
