### PR TITLE
Update  types/elasticsearch/SearchResponse.hits.total to current format

### PR DESCRIPTION
**Pull request by Max-Levitskiy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## elasticsearch ([<kbd>unpkg</kbd>](https://unpkg.com/browse/elasticsearch@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'elasticsearch'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. ConnectionPool
1. Transport
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6546f5139f344722126856fdbaffbfc2d1525808
</p>

**Comment by Max-Levitskiy** [comment]
Guys, could you please help me with the PR? I'm not sure about the connection between this code and JS lib version. 
But I know this code works for me locally with Elasticsearch 7.9.1.
Probably, I need to update some dependencies, but I didn't find where is it in the repo.

**Comment by pushplay** [comment]
@Max-Levitskiy The Elasticsearch 7 client comes with TypeScript support.  Have you tried using that instead?  Is there a reason to keep this package around?

**Comment by Max-Levitskiy** [comment]
> @Max-Levitskiy The Elasticsearch 7 client comes with TypeScript support. Have you tried using that instead? Is there a reason to keep this package around?

Hi @pushplay! 

For some reason, [elasticsearch](https://www.npmjs.com/package/@elastic/elasticsearch) client doesn't work for me and I have to use [elasticsearch-browser](https://www.npmjs.com/package/elasticsearch-browser), which is good enough for me but doesn't have TS types included.

**Comment by pushplay** [comment]
Hmmm.  Could you install the official client as well and just use it for its types?

**Comment by Max-Levitskiy** [comment]
It won't have compatible types. Probably, I can try to cast something, but it's not a solution I'm looking for.

**Comment by pushplay** [comment]
I don't understand why the typings here would work and the ones in the official package wouldn't because they're supposed to describe the same thing.

I wouldn't want new work to rely on this package as it's due for removal.  You could copy the typings to a new `@types/elasticsearch-browser` but that would require maintenance where you'd be better off riding the official typings for free if you can.  This post https://stackoverflow.com/a/58020165/2116213 suggests it's possible (just don't install `@types/elasticsearch`).

**Comment by Max-Levitskiy** [comment]
@pushplay it doesn't look like a good solution when we need to replace tiny package @types/elasticsearch to the full package only for getting types. And anyway, we won't get ready solution, because @elastic/elasticsearch and elasticsearch-browser has different API and response object format as well, so we need to transform types at some point. 
 I'm not so good in js-ts types mapping and solution with d.ts file tells me nothing for now. I need to read how to use it. But it doesn't seem like an obvious solution, but more than hack, which should do every developer wanna call elasticsearch from angular, for example. 

Do you think there is a sense to create @types/elasticsearch-browser from @types/elasticsearch in this case?

**Comment by pushplay** [comment]
@Max-Levitskiy 

> it doesn't look like a good solution when we need to replace tiny package @types/elasticsearch to the full package only for getting types

You'd only be using it at compile time so it doesn't need to be in the distributable.  I don't know the details of how Bower works but I know for Webpack that sort of thing works automatically.  I imagine Bower has to figure that out otherwise you'd be shipping all your dev tools like the TypeScript compiler in your distributable and that's just nutty.

> Do you think there is a sense to create @types/elasticsearch-browser from @types/elasticsearch in this case?

If the types aren't compatible then yes, that's probably the right solution.

**Comment by Max-Levitskiy** [comment]
> You'd only be using it at compile time so it doesn't need to be in the distributable. I don't know the details of how Bower works but I know for Webpack that sort of thing works automatically. I imagine Bower has to figure that out otherwise you'd be shipping all your dev tools like the TypeScript compiler in your distributable and that's just nutty.

The problem not only in the resulting package size but for the development and pipelines as well. Adding the package can bring more disk space and network usage, increase time of build. Also, it brings not only one package, but all the dependencies. 


> If the types aren't compatible then yes, that's probably the right solution.

It will be right to say, that we don't have compatibility between @types/elasticsearch and @elastic/elasticsearch, same as with @types/elasticsearch and last elasticsearch API.

**Comment by pushplay** [comment]
Well it's your project so you know what's best for it.

This change doesn't describe elasticsearch 5 so I don't think it should be merged in.

**Comment by Max-Levitskiy** [comment]
> This change doesn't describe elasticsearch 5.x so I don't think it should be merged in.

But why 5? es 5 is kind of 2 minor versions behind. They even don't support 5.x anymore: https://www.elastic.co/support/eol

Until the package called @types/elasticsearch, the logical expectation will be having the latest version in there. 
Won't it be better to migrate the old versions into @types/elasticsearch-x for old minor versions and have the latest one here? 

Correct me if I'm wrong, but I think until we'll have a client which covers all the common cases with typescript support, we need to have this package with the actual version. Rest interface of the elasticsearch makes it an excellent candidate to call it directly from the browser. And until Angular is one of the most popular front-end frameworks and is written on typescript, it looks like a really common case for me. 

Well, I kind of can make a fork and release it by myself, but I have a feeling other people may need this change as well. 

Please tell me if I should go ahead and do it only for myself?

**Comment by pushplay** [comment]
> But why 5?

Because that's the [version ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6546f5139f344722126856fdbaffbfc2d1525808/types/elasticsearch/index.d.ts#L1) this is published as.  [Some context on versioning](https://github.com/DefinitelyTyped/DefinitelyTyped/#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package).  The hits.total change didn't happen until 7.0.

There are three options for this typing:
1. Create a @types/elasticsearch 7.0 with only this change.  All the other breaking changes in Elasticsearch wouldn't be captured and it would confuse a lot of people.
2. Create a @types/elasticsearch 7.0 and someone does the work to capture all the breaking changes.  Since Elasticsearch started shipping their own types this typing has been pretty quiet so I don't see that as likely.
3. Deprecate this typing.

If you believe others out there will need a @types/elasticsearch-browser then I encourage you to create that.  Then you can do what makes sense in that context.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Agree with the comments above; you can also create major-version-specific subfolder to simultaneously publish multiple major versions from this repo

**Pull request closed without merging**
