### PR TITLE
Bull: Add types to some private functions

### PR DESCRIPTION
**Pull request by aleccool213**
- Job.moveToCompleted
- Job.moveToFailed
- Queue.getNextJob
- Also add null possibility to Queue.getJob

Me and my team are using these functions to implement a multiple-repo job processor service (despite being told by the author that this pattern for Bull isn't [supported](https://github.com/OptimalBits/bull/issues/208#issuecomment-157497444) or [planned](https://github.com/OptimalBits/bull/issues/790#issuecomment-345387700)). We are manually moving jobs from state to state as the `process` function is not being used. Work for a job is being done in another repo and we are exposing these functions via an API. We know these functions are private currently but hopefully with this exposure and a future PR to the actual Bull repo, we can get these functions to be public. We have this working in production for hundreds of jobs per day and this pattern seems to be working just fine.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
- https://github.com/OptimalBits/bull/blob/742a86e0af0e7d829e7d9cea55b74e7f7e850938/lib/job.js#L182
- https://github.com/OptimalBits/bull/blob/742a86e0af0e7d829e7d9cea55b74e7f7e850938/lib/job.js#L203
- https://github.com/OptimalBits/bull/blob/742a86e0af0e7d829e7d9cea55b74e7f7e850938/lib/queue.js#L1055

### CODE REVIEW

**Comment by rbuckton** [comment]
I would be wary about making "private" APIs public in a package, especially when the package author has expressly indicated that these APIs are private and may change. Are you able to use a module augmentation in your own project to add these APIs for your own internal use, as opposed to making this change for all users? Alternatively, are you able to work with the package author to find ways of making these APIs public first? Unless there is a very compelling case for adding these types for the entire development community, I would caution against adding them here.

**Comment by aleccool213** [comment]
@rbuckton You raise a very good point. Thanks for being defence compared to just merging :)

I have opened a [PR](https://github.com/OptimalBits/bull/pull/1017) on the original module where I speak to the author and have received his blessing.

**Comment by rbuckton** [comment]
@aleccool213: I would like to postpone merging until that PR has been merged, in the event the package author requires any other API changes, per this comment:

> I am not against to expose these functions, but I think the APIs needs to be sanitised first […]

Once that PR has merged and this PR is up to date with any changes, post a comment to this thread and a reviewer will take another look.

**Comment by aleccool213** [comment]
@rbuckton sounds good!

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Marking as changes requested until the other PR is merged.

**Comment by aleccool213** [comment]
@rbuckton @uniqueiniquity good to go! other pr has been merged

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
