### PR TITLE
Fixed XLSX typings

### PR DESCRIPTION
**Pull request by DxCx**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url :

[write](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.js#L11647)

[encode_cell](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.js#L11451)

[encode_range](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.js#L11455)
- it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by sandersn** [comment]
DxCx, can you merge from master? This PR conflicts with master now.

**Comment by DxCx** [comment]
@sandersn NP :) Done.

**Comment by DxCx** [comment]
@sandersn 
Great! :) Thanks.
is types-2.0 is auto generated branch?
or i'll do manual update there as well?

**Comment by sandersn** [comment]
No, we're merging manually for now. I'll take make sure this changes gets merged over there either today or tomorrow.

**Comment by DxCx** [comment]
@sandersn 
Thanks, Done :)

**Pull request merged**
