### PR TITLE
[@types/react-redux] mergeProps takes DispatchProp when mapDispatchToProps is undefined or null

### PR DESCRIPTION
**Pull request by saraid**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/reduxjs/react-redux/blob/4d384029e3fa0355e762f40409a5dac4358a3de3/src/connect/mapDispatchToProps.ts#L14-L20
  - https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59297
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by markerikson — APPROVED** [review]

**Review by val1984 — APPROVED** [review]
As it was already approved by @markerikson, it should be mergeable as is.

**Review by markerikson — APPROVED** [review]

**Comment by saraid** [comment]
This is what I see on my screen:
<details><summary>Collapsed the screenshot because it'd be confusing</summary>

Screen Shot 2022-04-06 at 1 47 46 PM
</details>

**Review by jakebailey — APPROVED** [review]
I have no idea what is going on with the bot or github actions, so I ran things locally and it seems fine to me.

**Comment by jakebailey** [comment]
Ok, approving wasn't enough, so I'll click the button.

**Comment by markerikson** [comment]
And FWIW I just ported this over to React-Redux v8:

https://github.com/reduxjs/react-redux/pull/1897

**Pull request merged**
