### PR TITLE
[reactstrap] Replacing components with generics.

### PR DESCRIPTION
**Pull request by Sprogel**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: *N/A* - no functional code change
- [x] Increase the version number in the header if appropriate. *N/A*
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. N/A

### CODE REVIEW

**Comment by FaithForHumans** [comment]
@timc13 @deepu105 - As promised. I haven't gotten a chance to add tests yet, but I wanted you guys to have a chance to start looking it over in case you noticed anything.

Deep, I know you said you didn't have time to keep up with this, but I thought I'd tag you anyway so you were aware.

**Comment by deepu105** [comment]
@FaithForHumans thanks. I trust that you know what is best for the community. I guess its a fine compromise. Unfortunately, I'm a minimalist when it comes to static typing in TS, so declaring custom types for the components where I use tags is not something I'm eager to do and hence probably I'll give this a miss and reconsider if I really need typing for these components. But I'm sure this will help people who want their typing to be as perfect and strict as possible.
I wish there was a way to choose generic or `[key: string]: any` based on personal preference.

**Review by timc13 — APPROVED** [review]
YES!

**Comment by FaithForHumans** [comment]
Actually, I think I can make a change to get the `[key: string]: any` behavior if you import each component directly (eg: `import Row from 'reactstrap/lib/Row'`) while still retaining the strict generic typing if you do the imports straight from the reactstrap directory. @timc13 would you agree to this if I did so?

**Comment by FaithForHumans** [comment]
@deepu105 After I started the PR, I had an idea to do just that. I pushed the change.

@timc13 I might not have explained it the  best, but the test shows what I'm talking about.

@ DefinitelyTyped maintainers - I feel like I'm shooting myself in the foot by saying this; it looks like the build failed due to a memory issue, but travis still reported it as passing. I have dropped this into an existing project and I haven't noticed anything wrong. Is there anything I need to do about the failing build?

**Pull request merged**
