### PR TITLE
brainhubeu__react-carousel - slides: JSX.Element[]

### PR DESCRIPTION
**Pull request by oprogramador**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@oprogramador what's the reason behind this change?

**Comment by oprogramador** [comment]
it's because of this comment https://github.com/brainhubeu/react-carousel/issues/60#issuecomment-571501831

**Comment by peterblazejewicz** [comment]
Thanks! So this probably meant just `JSX.Element[]`? - as per docs?, 
> ```slides: Array``` Alternative way to pass slides. This prop expects an array of JSX \ elements.

(if used) will loosen up requirements on that prop. Up to you folks though, as you own this :)

**Review by peterblazejewicz — APPROVED** [review]
LGTM
see also:
https://github.com/brainhubeu/react-carousel/issues/60#issuecomment-571501831

**Comment by oprogramador** [comment]
@peterblazejewicz 

I used `JSX.Element`.
I talked with @pierzchalatomasz and he's OK with that.

**Review by peterblazejewicz — APPROVED** [review]

**Pull request merged**
