### PR TITLE
add nib

### PR DESCRIPTION
**Pull request by NomNes**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

---

**NOTE:** I was unable to import the actual `Renderer` class declaration from stylus because it is not exported. So I used `any`. If someone tells me how to deal with this, I will fix it

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
> I was unable to import the actual `Renderer` class declaration from stylus because it is not exported. So I used `any`. If someone tells me how to deal with this, I will fix it

This works at runtime:
```js
const Renderer = require('stylus/lib/renderer');
```
so I guess `stylus` types were not kept in sync with JS. Do you want to fix tis detail in your PR?

**Comment by NomNes** [comment]
@peterblazejewicz thanks, yes, just a moment

**Comment by NomNes** [comment]
@peterblazejewicz this breaks the tests
```
ERROR: 6:1   expect           TypeScript@4.4 compile error: 
Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
ERROR: 6:18  no-var-requires  require statement not part of an import statement
ERROR: 6:18  expect           TypeScript@4.4 compile error: 
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
```

**Comment by peterblazejewicz** [comment]
This is JS, it works at runtime. As you said, there is no support for this yet, one sec, I'm fixing this atm

**Comment by peterblazejewicz** [comment]
You will be able to consume Renderer (and use in your change, if required), after this is merged: #53007

**Comment by NomNes** [comment]
ok, thanks!

**Pull request merged**
