### PR TITLE
[node] Add 'etag' in http.IncomingHttpHeaders

### PR DESCRIPTION
**Pull request by sbellone**
Hi, I've noticed that the `etag` header is not listed in Node's `IncomingHttpHeaders`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
  - When trying to run tests either on master or this branch, I get the following error:
    ```
    AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
      at next (/path/to/DefinitelyTyped/node_modules/dtslint/bin/index.js:194:12)
      at Array.map (<anonymous>)
      at /path/to/DefinitelyTyped/node_modules/dtslint/bin/index.js:166:92
      at Generator.next (<anonymous>)
      at fulfilled (/path/to/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
    npm ERR! Test failed.  See above for more details.
    ```

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@sbellone thx!

**Comment by peterblazejewicz** [comment]
@sbellone not sure how old is your branch, can you try to rebase and push changes?
The errors are not related to your change, that's for sure, DT is using TS@next as one of preflight checcks

**Comment by sbellone** [comment]
I had updated my fork right before opening the PR. I can try to rebase yes 👍

**Comment by sbellone** [comment]
So I don't know what to do next. Error message on CI is empty, and locally I get the error mentioned in the PR description 😕 
Is someone able to run the tests locally or should we investigate the dtslint error?

**Comment by peterblazejewicz** [comment]
We should check the errors with DT team,
I've getting same locally just after tests started:
```
found 0 vulnerabilities
1> koa-graphql START
2> node START
3> node/v10 START
4> node/v11 START
5> node/v12 START
6> node/v13 START
7> accepts START
8> acl START
testing from 3.5 to 3.6 in C:\development\DefinitelyTyped\types\node\v11\ts3.6
2> node failing:
2> AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
2>     at next (C:\development\DefinitelyTyped\node_modules\dtslint\bin\index.js:194:12)
2>     at Array.map (<anonymous>)
2>     at C:\development\DefinitelyTyped\node_modules\dtslint\bin\index.js:166:92
2>     at Generator.next (<anonymous>)
2>     at fulfilled (C:\development\DefinitelyTyped\node_modules\dtslint\bin\index.js:6:58)
2> addressparser START
```
(note: I have to patch koa-graphq package.json locally, could be not related)
you could rise the topic on Discord `#definitely-typed`, I'd review the other Node CIs builds here first

**Comment by sbellone** [comment]
Thanks for confirming, I see that those errors are not present anymore on that PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51646 (remove ts3.4 support).
So I'll rebase once it's merged.

**Comment by sbellone** [comment]
So yes it fixed the `node` tests 🙂 . The only remaining error is the one related to `cheerio`, but I've seen that #51646 has been merged anyway, so I think this one should be ok to go too?

**Review by peterblazejewicz — APPROVED** [review]

**Comment by sbellone** [comment]
Oh cool the unrelated issues are fixed 🎉 (Thanks to the person who took care of them)
May I bother you one last time @peterblazejewicz? 🙂

**Review by peterblazejewicz — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by sbellone** [comment]
Ready to merge

**Pull request merged**
