### PR TITLE
js-lock

### PR DESCRIPTION
**Pull request by nick-loginov**

### CODE REVIEW

**Review by weswigham — COMMENTED** [review]
This doesn't _seem_ right - namely, the published `js-lock` default-exports `Lock` but, perhaps moreover, the package isn't actually directly consumable in `node` (it'll throw if you try to `require` it - syntax error) - only via a `browserify` transform that also runs an old babel transform is it runnable... Because of this, I'm unsure what the types should look like, to be honest, since the package is so narrowly usable...

**Comment by jurca** [comment]
If I may, I would also like to argue **against** merging this PR.

As stated by @weswigham , the package is not compatible with node out-of-box (ES modules weren't supported by node at the time of creation, and the way it was written was the "best shot" I had). This should be addressed in the first place. Also, I would prefer porting this small package to TypeScript instead of adding a @types/ packages.

While I'm not currently focused on maintaining the package, I do accept PRs.

**Comment by sandersn** [comment]
@kemphack since @jurca would prefer a PR to jurca/js-lock to port it to Typescript, do you want to keep this PR open? I'll close it if not.

**Comment by sheetalkamat** [comment]
Closing this since this change doesnt look desirable

**Pull request closed without merging**
