### PR TITLE
Reactstrap: Add toast component and update props and tests based on 8.0 release

### PR DESCRIPTION
**Pull request by kyletsang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactstrap/reactstrap/releases/tag/8.0.0
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Any chance you can also address the other changes such as removed components and such?

**Review by SimonSchick — APPROVED** [review]

**Comment by kyletsang** [comment]
@SimonSchick Sure will add it into this PR

**Comment by kyletsang** [comment]
I've updated this PR to include all changes in the reactstrap 8.0 release. I left the Toast feature as that was already covered in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34453.

@alihammad @mfal @danilobjr @FaithForHumans @timc13 @patrickrgaffney @prabodht @georg94 @SimonSchick

**Comment by SimonSchick** [comment]
Some components were removed too IRC, would be 👌 if you could drop those too!

**Comment by kyletsang** [comment]
@SimonSchick The removed components listed in the release notes were already dropped from the type definitions at some point in the past, so I didn't need to do a thing :)

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Same feedback as in the Toast PR; since this is a popular package, [perhaps it would be best to create a `v8` directory](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/a26cc7b6f60de02a152168a21a9159a856bf581b#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package).

**Comment by seansfkelley** [comment]
@kyletsang would it be easier to just merge my branch for Toasts into this PR since they might conflict? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34453

If we go for type versioning, we'd actually want to create a v7 directory, not a v8, per the linked docs:

> If you intend to continue updating the older version of a library's type declarations, you may create a new subfolder (e.g. /v2/) named for the current (soon to be "old") version, and copy existing files from the current version to it.
> 
> Because the root folder should always contain the type declarations for the latest ("new") version...

**Comment by kyletsang** [comment]
@seansfkelley Sure we can do that. Let me look into this now.

**Comment by seansfkelley** [comment]
Awesome, thanks for taking that on! @uniqueiniquity how about now?

**Comment by kyletsang** [comment]
@seansfkelley I just noticed you didn't put your name into the authors list.  Would you like me to do that?

**Comment by seansfkelley** [comment]
Oh, no, that's okay. Thanks for asking.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Looks great! Thanks for doing that (and good catch on my version number mistake).

Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
