### PR TITLE
'text=auto' changes crlf automatically in local repository and pollutes work tree

### PR DESCRIPTION
**Pull request by rhysd**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

---

This commit is none of the above cases.
I fixed the option because it polluted work tree and caused an error on merging upstream to my fork and emitted so many 'CRLF will be replaced...' warnings.
My environment is OS X 10.11.3.

### CODE REVIEW

**Comment by vvakame** [comment]
@cspotcode what do you think this PR? I believe that trying to merge.

**Comment by cspotcode** [comment]
(#7879)

I don't have a strong opinion one way or the other.  I added `text=auto` for a few reasons:

* Before my commit, .gitattributes looked like this:
  ```
  # Auto detect text files and perform LF normalization
  * text=none
  ```
  Which doesn't make sense.  Lines 1 and 2 contradict.  I assumed it was a mistake.  Maybe it wasn't.

* I was pinged for this PR: #7823  It changed every single line of a definition, just to normalize line endings.  I'd like to avoid that in the future.

Another option is to normalize the whole repository to LF in a single commit.  Then these errors won't appear anymore.

Either solution is fine with me.

**Comment by cspotcode** [comment]
@vvakame Oh, I see you already normalized line endings in #8095.  Shouldn't those CRLF errors go away once you rebase / merge to the latest master?

**Comment by rhysd** [comment]
In the latest repository, the error looks gone.  Thanks.

I suggest adding CRLF detection to @dt-bot to reject CRLF at review.

**Pull request closed without merging**
