### PR TITLE
`@types/auth0` add support for `include_totals` to `getMembers` and `getMemberRoles` organization functions.

### PR DESCRIPTION
**Pull request by alexframe**
This PR adds `include_totals` types for two of the new `organization` endpoints, `getMembers` and `getMemberRoles`.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [`getMembers` documentation*](https://auth0.com/docs/api/management/v2#!/Organizations/get_members)
  - [`getMemberRoles` documentation*](https://auth0.com/docs/api/management/v2#!/Organizations/get_organization_member_roles)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

_*neither of these endpoints actually return a `length`, so we cannot fully reuse the `Page` type, so I have omitted the `length` property_

---

### Additional Context
When you supply a `include_totals: true` to a request, it returns the data with additional details, this PR adds missing types that have already been released in the sdk.

I have tested both of these changes locally both with a promise and a callback and they work as expected.

### CODE REVIEW

**Review by frederikprijck — COMMENTED** [review]
Is there any reason we arent adding include_totals to the PagingOptions? I believe this is missing from every method supporting pagination.

**Comment by alexframe** [comment]
Sorry to tag you directly @peterblazejewicz, is there a way to nudge people to take a look at this please, as it does add some functionality.

Thanks 🙏🏼

**Review by nhardy — CHANGES_REQUESTED** [review]
Just some suggested changes here regarding using of `// $ExpectType Type` instead of typing parameters in the callback.

**Review by nhardy — APPROVED** [review]

**Comment by alexframe** [comment]
Ready to merge

**Pull request merged**
