### PR TITLE
Add `@types/json-rpc` package

### PR DESCRIPTION
**Pull request by SevenOutman**
Hi team, I'm adding this `@types/json-rpc` package to act as the recognized 
 source of typescript declaration for JSON-RPC specs, just like `@types/json-schema`.

This package does not reflect the [`json-rpc` package](https://www.npmjs.com/package/json-rpc) APIs as it's long out of maintenance and not widely in use (as per npm download stats).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by SevenOutman** [comment]
@riga Would you please review this PR as the author of the original `json-rpc` package? Thanks.

**Comment by jakebailey** [comment]
I'm not totally a fan of DT being the source for random declaration files that don't describe actual runtime values; is there a reason why this isn't just a regular npm package you publish?

**Comment by SevenOutman** [comment]
@peterblazejewicz @jakebailey Thanks for your response. JSON-RPC is an open spec of RPC calls represented by JSON messages, and `json-rpc` is an implementation of some JSON-RPC related utils that follows the spec. Given this relation, I think it should be OK to export JSON-PRC types from this types packages.

But I see your points here, the `json-rpc` package API should also be included. I'll add them then, thus this types package becomes typing for `json-rpc` package with additionally exported JSON-RPC types.

**Comment by jakebailey** [comment]
The package hasn't been updated in 9 years and doesn't get any downloads. I don't think it's worth typing it; doing that sounds like a workaround for my comment more than anything. 😅

**Comment by SevenOutman** [comment]
> The package hasn't been updated in 9 years and doesn't get any downloads.

That's just why I didn't type it initially.

I assume your suggestion is I publish a package say `json-rpc-types` instead of a `@types` package. In fact I've considered that before even writing this types package, but finally decided to create this PR. If this is types for some random convention I just made up today, I would definitely publish my own package. But it's not, it's an open spec and I feel it's better held by community rather than individual - we've all seen widely used packages eventually lost maintenance because of individual ownership.

**Comment by jakebailey** [comment]
Our readme does mention this exact case: https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-type-definitions-with-no-matching-package

> If there's no source JavaScript code at all, for example if you're writing helper types or types for a spec, you should publish the types yourself, not on Definitely Typed. Because they're meant to provide types for existing JavaScript code, `@types` packages are not meant to be imported directly. That is, you shouldn't create a Definitely Typed package that's meant to be used like `import type { ... } from "@types/foo"`. Nor should you expect to write `import type { ... } from "foo"` when there's no `foo` installed.

**Comment by SevenOutman** [comment]
@jakebailey That makes sense then. Thanks for the explanation. I'll probably publish a package myself.

**Pull request closed without merging**
