### PR TITLE
Adding balanced.d.ts

### PR DESCRIPTION
**Pull request by jt000**

### CODE REVIEW

**Comment by vvakame** [comment]
@jt000 thank you your contributions.
please rename balanced/balanced.d.ts to balanced.js/balanced.js.d.ts .
http://definitelytyped.org/guides/contributing.html#naming-the-file
https://www.npmjs.com/package/balanced (other library already exists

**Comment by jt000** [comment]
No problem... done... Thanks!

**Comment by vvakame** [comment]
@jt000 please fix Travis CI. thank you!

**Comment by jt000** [comment]
Whoops... Good thing we have CI :) Fixed...

**Comment by jt000** [comment]
Balanced Payments is no longer a marketplace option. They are [pushing their customers to Stripe](https://www.balancedpayments.com/stripe), so this PR is no longer needed.

**Pull request closed without merging**
