### PR TITLE
[angular-ui-router] remove typings provided by package directly

### PR DESCRIPTION
**Pull request by BendingBender**
@nateabele @ProLoser @christopherthielen @michelsalib @matiishyn:
I am removing the typings for `angular-ui-router` from DefinitelyTyped because they are now available in the project repo (https://github.com/angular-ui/ui-router) and the ones available here are outdated. Could you please give your ack?

One of the packages to remove from the list in #13364

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by christopherthielen** [comment]
We added types to ui-router in version 1.0 and renamed the non package to `@uirouter/angularjs`. However, the previous version of ui-router (0.x) is written inJS, and is still maintained for legacy users.  Those users will still benefit from definitely typed definitions. 

I would prefer that these types defs remain here

**Comment by BendingBender** [comment]
No possibility to add them directly to the legacy branch? Would be better experience for users of both, the legacy and the stable branches. I suppose that currently some users of the current branch may still install the package from DefinitelyTyped out of habit.

**Comment by christopherthielen** [comment]
I guess my concern is that this will break many users setups. We can add the type defs to a new release of legacy branch, but a huge number of my users are pinned to specific legacy release and don't update. Those users will see broken builds if the types are removed from DT

**Comment by BendingBender** [comment]
Removing the types from the repo doesn't mean that the removed types will be unpublished from npm. This only means that stub typings will be published with a new version tag.
This means that nothing will change for the users who pinned all their dependencies. The ones who didn't pin them will receive an update for both, the stub typings and you lib where you've added the typings directly. The transition will be completely transparent for them. But you will of course have to add the typings to the legacy branch first and release a new version.

**Comment by BendingBender** [comment]
@christopherthielen If you don't agree, then I will simply close this pull request. Just give me your NACK, please.

**Comment by christopherthielen** [comment]
In that case, NACK, please keep these.

**Pull request closed without merging**
