### PR TITLE
connect-pg-simple: add disableTouch property to PGStoreOptions

### PR DESCRIPTION
**Pull request by rbranham**
Here is the typedef doc comments in js file found here: https://github.com/voxpelli/node-connect-pg-simple/blob/main/index.js
/**
 * @typedef PGStoreOptions
 * @property {string} [schemaName]
 * @property {string} [tableName]
 * @property {boolean} [createTableIfMissing]
 * @property {number} [ttl]
 * @property {boolean} [disableTouch]                         <- This is the parameter missing
 * @property {typeof console.error} [errorLog]
 * @property {Pool} [pool]
 * @property {*} [pgPromise]
 * @property {string} [conString]
 * @property {*} [conObject]
 * @property {false|number} [pruneSessionInterval]
 * @property {false|PGStorePruneDelayRandomizer} [pruneSessionRandomizedInterval]
 */

disableTouch was missing from the interface definition.
disable touch was added to original package on Oct 11, 2020, here is that commit: 
https://github.com/voxpelli/node-connect-pg-simple/commit/75ea11fded4f3c7694cc0248319ce628a1203d94

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [x ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/voxpelli/node-connect-pg-simple/blob/main/index.js
- [ x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.  
The latest is Version 7.0.0, there wasn't a previous version number in the header of this file so I added one.

### CODE REVIEW

**Review by samarmohan — CHANGES_REQUESTED** [review]
I think I found the CI issue, write Type definitions for (PACKAGE) (VERSION). You’ve written something like connect-pg-simple Version and the CI can’t parse that.

**Comment by samarmohan** [comment]
How can I make edits to this, the change is needed?

**Comment by pasieronen** [comment]
I think only the PR author can edit the PR. @rbranham, I think replacing this

```
// Type definitions for connect-pg-simple 4.2
// Project: https://github.com/voxpelli/node-connect-pg-simple#readme
// connect-pg-simple Version: 7.0.0
```
with this
```
// Type definitions for connect-pg-simple 7.0
// Project: https://github.com/voxpelli/node-connect-pg-simple#readme
```
should resolve the failing CI test...

**Review by samarmohan — APPROVED** [review]

**Comment by rbranham** [comment]
Ready to merge

**Pull request merged**
