### PR TITLE
Add types for `cldr`

### PR DESCRIPTION
**Pull request by jesseplymale**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.jesseplymale.com/github/2021_10_07_DefinitelyTyped.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by thewilkybarkid — CHANGES_REQUESTED** [review]
Thanks for going through all these. 👍  I've not tried them all out to see if they work or not (since there's a lot and quite a few undocumented etc.), but I've left a few comments based on what I can see.

**Comment by jesseplymale** [comment]
@thewilkybarkid I wrote a response to each of your concerns above. Hopefully I've addressed them sufficiently so that you can sign off on it. Let me know here if you have remaining concerns.

**Comment by thewilkybarkid** [comment]
Looking good; I think it's worth testing promisify though. I just tried adding

```ts
/// <reference types="node" />

import { promisify } from 'util';

// $ExpectType (arg1: string) => Promise<Document>
promisify(Cldr.getDocument);
```

to the tests and it doesn't work, but does when reversing the declaration order.

**Comment by jesseplymale** [comment]
I realized what you were saying, and found [this StackOverflow post](https://stackoverflow.com/questions/57314805/in-typescript-why-function-overloading-order-matters-only-when-the-overloaded-f) which showed that the reordering of the method overloads matters in cases like `util.promisify()`.

I changed the order as you suggested, and added type checks for it, and it works as desired.

Note that I needed to add a `package.json` to bring in the `node` dependencies, [as shown here](https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md).

**Comment by jesseplymale** [comment]
Inadvertently, I had pulled in a more-recent `docs/support-window.svg` file from the main branch, so I backed that out of the pull request.

**Comment by thewilkybarkid** [comment]
> Note that I needed to add a `package.json` to bring in the `node` dependencies, [as shown here](https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md).

Is that right? My understanding of `/// <reference types="node" />` was that it caused DT to recognise the dependency, whereas the `package.json` `dependency` means `@types/node` will become a full dependency of the published package (which isn't right either, as this is just for tests).

Does removing it cause the build to fail?

**Comment by thewilkybarkid** [comment]
> Yes, removing it causes the build to fail with a `no-outside-dependencies` error, giving a link to the web page [that I linked to above](https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md). So, if we want `util.promisify` usage to be tested in the unit test, we have to include the `@types/node` dependency.

If I remove the `package.json` file locally and run `npm test cldr` it still passes, does it fail somewhere else?

**Comment by jesseplymale** [comment]
It failed for me when I ran `npm test cldr`. Did you delete the
`node_modules` directory after removing your `package.json`?

**Comment by jesseplymale** [comment]
Well, this is confusing! The automated checks passed after the `package.json` was removed.

Locally, I deleted my `types/cldr/package.json` and it still worked, but as soon as I deleted my `types/cldr/node_modules`, the test would fail when going to the repository root and running `npm test cldr`.

To get it to work again locally, I had to put the `types/cldr/package.json` back, then `cd types/cldr` and `npm install`, and then I could again successfully run `npm test cldr` from the repository root.

I wish I understood why it is not working on my local machine. I did a sparse checkout of the repo so perhaps that is related? Also I wish I understood why it works differently for you.

At least the actual `index.d.ts` has no dependencies on `@types/node`, so I'm not worried about it being published. But if you have any ideas on why your setup and mine are different, I'd be interested in knowing.

**Comment by jesseplymale** [comment]
Did some more research and saw that older versions of the `dtslint` library did not have `no-outside-dependencies` set to `true` in their `dtslint/dt.json`. The recent ones do. Maybe you have an older version of `dtslint` in your `node_modules`? That still wouldn't explain why it succeeds on their build server, tho.

Anyway, feel free to approve the pull request, if you have no further issues.

**Comment by thewilkybarkid** [comment]
Weird! Oh well, let’s just trust the CI. 😃

**Review by thewilkybarkid — APPROVED** [review]

**Comment by thewilkybarkid** [comment]
Ready to merge

**Pull request merged**
