### PR TITLE
[calendar] Map exact return types with generics

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ramalho/calendar.js/blob/master/lib/calendar.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by quentincaffeino** [comment]
Sorry but when is it expected to be merged?

**Comment by ffflorian** [comment]
I am waiting for someone from the DefinitelyTyped team to approve this PR. In the meantime, you could approve it if you like :)

**Comment by elibarzilay** [comment]
@ffflorian: what's the status of this?  There are things here like `DayFormatter<T> = (day: Date) => T` that seem fishy.

**Comment by ffflorian** [comment]
@elibarzilay what do you mean by "what's the status of this"? I am waiting for a DT maintainer to merge this.
Why do you think `DayFormatter<T> = (day: Date) => T` is fishy? I test this manually a lot and also added tests in my PR.

**Comment by elibarzilay** [comment]
Because generic types on the RHS are usually questionable...?   But it's your types...

**Pull request merged**
