### PR TITLE
[auth0] Add getLogStreams method

### PR DESCRIPTION
**Pull request by arjenvanderende**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://auth0.com/docs/api/management/v2#!/Log_Streams/get_log_streams
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@arjenvanderende your change looks good, can you please run formatted on your changes to unify indentation? (always 4, not mixed 2 or 4), 
thanks!

**Comment by arjenvanderende** [comment]
@peterblazejewicz Doh, formatting is fixed. Thanks for the review!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@arjenvanderende thanks!

**Comment by arjenvanderende** [comment]
Ready to merge

**Pull request merged**
