### PR TITLE
Added missing ready function on Turnstile interface for @types/cloudflare-turnstile

### PR DESCRIPTION
**Pull request by rezo12**
- [*] Use a meaningful title for the pull request. Include the name of the package modified.
- [*] Test the change in your own code. (Compile and run.)
- [*] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [*] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [*] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [*] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [* ] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/cloudflare-turnstile/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e03f82c58077977ebfc08bbb0cbc11c58e31eaa0
</p>

**Review by jasongerbes — APPROVED** [review]
Thanks for the contribution :)

**Comment by jasongerbes** [comment]
> ## Formatting
> The following files are not formatted:
> 
> 1. types/cloudflare-turnstile/index.d.ts
> 
> Consider running `pnpm dprint fmt` on these files to make review easier.
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [e03f82c](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e03f82c58077977ebfc08bbb0cbc11c58e31eaa0)

@rezo12 could you please address this formatting issue. Otherwise this PR looks good to go 👍

**Comment by rezo12** [comment]
Done :)

**Review by jasongerbes — APPROVED** [review]

**Comment by jasongerbes** [comment]
Ready to merge

**Pull request merged**
