### PR TITLE
[react-table] selectTableHOC fixes

### PR DESCRIPTION
**Pull request by Gelio**
The HOCs types were too strict. Moreover, the names of components props have been fixed.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by minestarks** [comment]
Could you elaborate on why they were too strict? Maybe an example of valid code that wasn't possible with the existing types?

**Comment by Gelio** [comment]
@minestarks Sure! Sorry for not providing the example immediately.

While the previous HOCs typing worked for the unmodified `ReactTable` component, it expected all the props from `ReactTable` to be present. In my project, I created a `DataTable` component whose props mostly align with `ReactTable`, but I have hidden some of the props that are managed by `DataTable`.

Then, when I wanted to apply `selectTableHOC` on my `DataTable`, there was an error that `DataTable` does not contain all the props that `ReactTable` has:

```ts
class DataTable extends Component<Omit<ReactTableProps, 'page' | 'pages' | 'pageSize'>> {
  // ...
}

const DataTableWithSelectableRows = selectTableHOC(DataTable); // Typescript error because DataTable does not have: page, pages, pageSize
```

The ideal solution would be to find all the props that are used by `selectTableHOC` and specify them in the HOC's definition (`selectTableHOC<Props extends AllThePropsThatSelectTableHOCUses>`), but I did not have enough time to find all of them.

**Comment by minestarks** [comment]
@Gelio thanks for the explanation. However I'm still not quite sure if the change is needed. When I try out your example with the typings before your changes, it works without an error. (I modified it slightly to look like the below):

```ts
class DataTable extends Component<Exclude<TableProps, 'page' | 'pages' | 'pageSize'>> {
    // ...
}

const DataTableWithSelectableRows = selectTableHOC(DataTable);
```

This is because `selectTableHOC`'s type argument extends `Partial<TableProps>`, not `TableProps` itself which would have been too strict. As long as you have at least one property in your component that overlaps with any of the `TableProps`, you should be good without having to change the typings.



On the other hand, the current typings do raise an error in the following usage:

```ts
class DataTable extends Component<{totallyUnrelatedProp: string}> {
    // ...
}

const DataTableWithSelectableRows = selectTableHOC(DataTable); // error
```

TypeScript is stricter here because there is zero overlap between `Partial<TableProps>` and your component's type arguments. I'd say this is a helpful error in most cases - you probably didn't mean to do this - and if you wanted to work around it, you can always use an explicit cast to beat the compiler:

```ts
const DataTableWithSelectableRows = selectTableHOC(DataTable as unknown as React.ComponentType<TableProps>);
```

So overall I'd say the benefits of "strict" checking outweigh the drawbacks here.

**Comment by Gelio** [comment]
@minestarks You are right! Thanks to you today I learned that

```ts
interface A extends B {
  someProperty: any;
}
```

is not equal to

```ts
type A = B & { someProperty: any };
```

at least when it comes HOCs. Here the problem was in my codebase:

```ts
type TableLeftProps = Omit<
  Partial<TableProps>,
  'page' | 'pages' | 'pageSize'
>;

interface DataTableProps extendsTableLeftProps {
  initialPage: number;
  initialPageSize: number;
}
```

Having changed that to:

```ts
type TableLeftProps = Omit<
  Partial<TableProps>,
  'page' | 'pages' | 'pageSize'
>;

interface DataTableOwnProps {
  initialPage: number;
  initialPageSize: number;
}

type DataTableProps = TableLeftProps & DataTableOwnProps;
```

applying the `selectTableHOC` to `DataTable` started working. Frankly, I have no idea why. I thought those two ways of composing types were equivalent to each other.

I will restore the original types for those HOCs and add a `resolveData` property that I found to be missing in the current type definitions.

**Comment by Gelio** [comment]
I have reverted the HOC typing and added a missing prop for `resolveData`. It is listed in the docs:
https://react-table.js.org/#/story/readme

(Ctrl+F for `resolveData` and the prop will be there)

I have also rebased the commits so as not to bloat the repo.

I'm waiting for a review 🙂

**Pull request merged**
