### PR TITLE
[react-dates] added DayPickerRangeControllerShape#hideKeyboardShortcutsPanel

### PR DESCRIPTION
**Pull request by screendriver**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/airbnb/react-dates#daterangepicker
- [x] Increase the version number in the header if appropriate.

@Artur-A

### CODE REVIEW

**Comment by Artur-A** [comment]
Hi @screendriver, 
all looks good, 
thank you for the update!

**Comment by screendriver** [comment]
Hmm strange. If I install `@types/react-dates` in my project I get `12.1.1` in my `package.json` as expected. But when I open the `index.d.ts` I see `12.1.0` in the comments at the top of the file and an outdated definition file 🤔 

Any ideas @Artur-A or @RyanCavanaugh ?

**Comment by Artur-A** [comment]
Indeed, that's a strange behaviour in npm package build.

Everything came to the index.d.ts in npm, except the first line `Type definitions for react-dates v12.1.1`.
At the same time the source has this line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dates/index.d.ts

**Comment by screendriver** [comment]
Hmm no. If you download the current published `index.ts` from https://unpkg.com/@types/react-dates@12.1.1/index.d.ts you can see that [line 229](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dates/index.d.ts#L229) is missing.

**Comment by screendriver** [comment]
There was a new publish yesterday 😳 Now it's version `12.1.2` at npmjs.com although it is `12.1.1` in `index.ts` 🤔

**Comment by RyanCavanaugh** [comment]
The minor version has to rev in order for us to publish a new package. Only the first two digits of the version are copied to the NPM version.

**Comment by screendriver** [comment]
I believe I don't get it. When I just change the patch version (like in this pull request) then the package still get's updated on npmjs.com but the version number in the comment of `index.ts` will be ignored and the publisher automatically increments the patch version number on npmjs.com?

**Comment by RyanCavanaugh** [comment]
Sorry, I said minor when I meant patch.

**Pull request merged**
