### PR TITLE
Leaflet: Add LeafletLayersControlEvent

### PR DESCRIPTION
**Pull request by rimig**
http://leafletjs.com/reference.html#layers-control-event

### CODE REVIEW

**Comment by vvakame** [comment]
*leaflet/leaflet.d.ts*

to author(@rgripper). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by rgripper** [comment]
@rimig Is it ok to block tests with alert (I may be wrong :))?

**Comment by rimig** [comment]
The test is just to compile I believe.

**Comment by rgripper** [comment]
@rimig Right! )
@vvakame :+1:

**Comment by vvakame** [comment]
@rgripper thanks!
@rimig thanks mate!

**Pull request merged**
