### PR TITLE
simpl-schema: Fix support for oneOf, add support for simple array forms, add static validate function

### PR DESCRIPTION
**Pull request by abjennings**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
oneOf is static: https://github.com/longshotlabs/simpl-schema#multiple-definitions-for-one-key
shorthand array forms: https://github.com/longshotlabs/simpl-schema#more-shorthand
static version of validate function: https://github.com/longshotlabs/simpl-schema#validating-and-throwing-validationerrors

- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by abjennings** [comment]
When reviewing this PR, I would recommend using the commit dropdown to examine the commits separately. One commit has substantive changes. The other one just prettifies the whole file (because the docs said to do that). But we can remove the prettifying commit if that would help anything.

image

**Review by yurtsiv — APPROVED** [review]

**Comment by yurtsiv** [comment]
Nice!

**Comment by yurtsiv** [comment]
Ready to merge

**Comment by yurtsiv** [comment]
@typescript-bot Ready to merge

**Comment by yurtsiv** [comment]
Ready to merge

**Pull request merged**
