### PR TITLE
Stripe - Subscriptions Transfer Data Definition

### PR DESCRIPTION
**Pull request by asithade**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stripe.com/docs/api/subscriptions/create#create_subscription-transfer_data

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## stripe ([<kbd>unpkg</kbd>](https://unpkg.com/browse/stripe@latest/))
was missing the following properties:
1. DEFAULT_HOST
1. DEFAULT_PORT
1. DEFAULT_BASE_PATH
1. DEFAULT_API_VERSION
1. DEFAULT_TIMEOUT

<details>
<summary>as well as these 7 other properties...</summary>
<p>PACKAGE_VERSION, USER_AGENT, USER_AGENT_SERIALIZED, MAX_NETWORK_RETRY_DELAY_SEC, INITIAL_NETWORK_RETRY_DELAY_SEC, webhooks, Stripe</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b9eff9bb5baead85a2856ce6343938b1ff60c1a3
</p>

**Comment by vaskevich** [comment]
Stripe now ships with official types. Just use those?

**Review by saranshkataria — CHANGES_REQUESTED** [review]
```amount_percent``` should be optional according to the docs. So please change that. Also, could you add some tests for this too?

**Review by LinusU — APPROVED** [review]

**Comment by LinusU** [comment]
Sorry, disregard my review, I missed that `amount_percent` should be optional 🙈

**Comment by asithade** [comment]
> amount_percent should be optional according to the docs. So please change that. Also, could you add some tests for this too?

Oops -- fixed! And added a test for subscription with transfer_data

**Review by saranshkataria — APPROVED** [review]
LGTM. Thanks!

**Comment by asithade** [comment]
Ready to merge

**Pull request merged**
