### PR TITLE
[@types/email-templates] Export all interfaces and types and remove duplicated code

### PR DESCRIPTION
**Pull request by ksewo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## email-templates ([<kbd>unpkg</kbd>](https://unpkg.com/browse/email-templates@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'email-templates'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 47ecb96b4abf151146a8813ec8770dc5daf9b5e9
</p>

**Review by peterblazejewicz — COMMENTED** [review]
Why this change for export type?
It really looks should be a CommonJS module, without an export default being used:
https://github.com/forwardemail/email-templates/blob/master/src/index.js#L331

**Comment by ksewo** [comment]
@peterblazejewicz 
It can't be "export =", if there are anything else exported within file (I've added interfaces exports).

These changes shouldn't cause any issues as in typescript you should use ES6 imports instead of requires.

**Comment by ksewo** [comment]
@cyrilschumacher @gurisko @blankstar85 @vesse @qqilihq @peterblazejewicz can you review changes, please?

**Comment by elibarzilay** [comment]
Re-ping @cyrilschumacher @gurisko @blankstar85 @vesse @qqilihq @peterblazejewicz

**Comment by peterblazejewicz** [comment]
The package is published as CJS module, one can see the source and the published content, no multple exports (JS modules/CommonJS modules) yet that culd somehow explain the DT change. I just cannot see the reason behind the change (save the modern syntax), the README (public facing document) uses CJS syntax.

**Comment by ksewo** [comment]
@peterblazejewicz what do you mean by that "I just cannot see the reason behind the change"? These are typings and typescript transpiler allows for syntax like that when module is exported with "export =". The reason for exporting interfaces is that you can use interfaces later in code, for example if you want create object and type it with EmailConfig then change some value of this object based on some condition i.e.:

`
import { MailOptions } from 'email-templates';

interface SomeLocals {
  fullName: string;
}

const locals: SomeLocals = {
  fullName: 'Full name here',
};

const options: MailOptions<any> = {
  locals,
}

if (!options.from) {
  options.from = process.env.NO_REPLY_EMAIL_ADDRESS;
}

`

I know it could be done in other way, but it's just an example, I am writing wrapper for sending mail and I need to use these types.

**Comment by peterblazejewicz** [comment]
>I just cannot see the reason behind the change

to rephrease: from CommonJS to JavaScript module. The source is CommonJS module.

**Comment by ksewo** [comment]
@peterblazejewicz I am trying to modify just typings, so it doesn't affect email-templates source code, require still can be used in javascript. I don't see the reason not to export is as a default, as it will work with import syntax.

**Require syntax should not be used inside typescript code as it lacks typing and compile-time checking if module exists.**

Typescript is superset of javascript which adds types to javascript, typing files should be written for typescript not javascript and they should export all interfaces, so they can be used in code. Typings should be exported from every module (and mostly they are). It's hard to use any library if there aren't typings exported.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Thanks for opening this @ksewo!

But, there is a lot that needs to be cleared up here.

## Why this change is incorrect

For starters, the long and short of it is that @ksewo, it seems you have some misinformation about module formats in TypeScript. As a TypeScript user (especially one who uses the `esModuleInterop` option), the differences are usually hidden from you, but when writing definitions on DefinitelyTyped, the differences matter. It’s the most confusing part of contributing to DT for sure, but @peterblazejewicz is quite knowledgeable in this stuff as one of the most prolific active DT contributors, so listening to his feedback is a good start 😄 

Let’s see if we can address the confusion statement by statement.

> It can't be "export =" if there is anything else exported within a file.

This is true, so I see why it motivated the rest of your changes. But, there is a way to accomplish your goal that does not change the module format (I’ll get to that in a moment). The important thing is that `export =` and `export default` represent _fundamentally different_ module formats, and it is categorically incorrect to use one to represent the other. This is easily missed as a TypeScript consumer, because with `esModuleInterop: true`, you can _import_ them exactly the same way. (However, this is also what @peterblazejewicz _and_ the dtslint rule you had to disable were trying to tell you.)

> These changes shouldn't cause any issues as in typescript you should use ES6 imports instead of requires.

Neither half of this statement is true. These changes _will_ cause issues for people who do not use `esModuleInterop`. This change will insist that all users use a default import of `EmailTemplates`, while the actual source code uses `module.exports =`. For users with `esModuleInterop` enabled, this won’t matter in practice. But without the interop shim provided by that config option, runtime code will break, because it will try to access the `default` module record from a module which does not have one. This is because `module.exports =` and `export default` are fundamentally different. In the future, it may be an official standard that one can use a ES6 default import of a `module.exports` (CommonJS) module, but the current state of the world is that an ES6 default import is _not_ a valid way to import a CommonJS module in TypeScript unless `esModuleInterop` is explicitly enabled. So, it is also not correct to say “you should use ES6 imports instead of requires.” In some combinations of modules and configuration settings, ES6 imports are wrong and explicitly forbidden. The first-class TypeScript syntax for importing a CommonJS module is

```ts
import EmailTemplates = require("email-templates");
```

There is a very common misconception that this is antiquated, deprecated, or defunct. It is not; it is the correct syntax for importing CommonJS modules, which are still commonly used today. It is a syntax you can always avoid using, if you like, if you enable `esModuleInterop`. If you do not, you _must_ use the import/require syntax in some cases.

> Require syntax should not be used inside typescript code as it lacks typing and compile-time checking if module exists.

I think my last point cleared this up, but for the sake of clarity, I’ll repeat it. It is true that `const foo = require('foo')` is not recognized as special TypeScript syntax; it will not type check unless there is an ambient declaration for a `require` function. People/libraries often add one and make its return type `any`, so this should be avoided. However, the drop-in replacement is `import foo = require('foo')`, which _does_ perform module resolution and propagate types, as you would expect with TypeScript.

## How to accomplish your goal without using an incorrect module format

You wanted to export the utility interfaces, which is a good goal. Now we know that the correct way to do it must not change the module format from CJS to ESM. The correct way to do that would be to move the interfaces into the namespace. Then, usage would look like this:

```ts
// CJS imports:
import EmailTemplate = require('email-templates');
const config: EmailTemplate.EmailOptions = {};

// ESM imports, with or without esModuleInterop:
import * as EmailTemplate from 'email-templates';
const config: EmailTemplate.EmailOptions = {};

// ESM imports, with esModuleInterop
import EmailTemplate, { EmailOptions } from 'email-templates';
```

## Why was this namespace here in the first place?

When looking at the source code to resolve this issue, I noticed that the existing namespace with the functions `juiceResources`, `render`, etc. seem to be superfluous; my guess is they’re left over from an older version of the library. I don’t see any static members on the class, and the class is also now named `Email`, not `EmailTemplate`, so it seems like there may be some cleanup to do in this library anyway, unless I’m missing something. @peterblazejewicz, would you be able to confirm?

**Comment by peterblazejewicz** [comment]
@andrewbranch thank you!

@ksewo let me reiterate, I was only concerned about the change, that would made default usage of the package not working as expected. I do respect people who do copy-paste from the source README when learning new stuff, so the first thing to avoid when we add TS support, is to not add another confusion level. I do respect your work and see why you want to introduce changes and I'm here only trying to help (I hope it hasn't looked differently).

**Comment by ksewo** [comment]
@andrewbranch Thanks, for explaining everything. I didn't know it can be done with namespaces and that it won't work for people without esModuleInterop flag. I have moved the interfaces into namespace EmailTemplate and removed rules that I have added to tslint.

@peterblazejewicz I am sorry, I didn't know that it can be done with CJS export. Thanks for your time in reviewing my changes.

**Review by andrewbranch — APPROVED** [review]
This looks correct to me. Thank you @ksewo!

**Comment by ksewo** [comment]
Ready to merge

**Pull request merged**
