### PR TITLE
[@types/chai] Remove should from Object interface

### PR DESCRIPTION
**Pull request by villasv**
Avoids Object pollution and solves #9120

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: *change not related to the library itself*
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by villasv** [comment]
Hang on, I realize that there are many other type libs that currently depends on `should` being there so I'm going to propose a separate definition without it.

**Review by jednano — APPROVED** [review]
This is not a great situation. There's no way you can know if they actually depended on `should` being there or not. At the same time, these changes are definitely improving the accuracy of the types.

Considering the latter, I think I'm personally OK with merging this PR. It might break some implementations, but it will eventually create a better, more accurate set of types.

**Comment by villasv** [comment]
Should I work on removing all tests that depend on .should? Or should I just make it an alternative chai typing?

**Comment by jedmao** [comment]
Are you 100% sure that `should` style is not included in `chai`? I'm looking at https://www.chaijs.com/guide/styles/#should and I don't see any installation docs for installing `should`.

**Comment by villasv** [comment]
`should` IS included in chai, but because it violates our type system, we don't use it. We only use the `expect` form, which is equivalent and doesn't mess with the Object Prototype.

So it's not wrong to include that Object interface in the @types/chai lib, this is not a bugfix. But this is an improvement, because TypeScript folks should avoid using the `should` syntax. Of course this decision is opinionated and will break lots of code, which is why I'm saying that it might be better to release this as a parallel typing library.

**Comment by villasv** [comment]
I don't mind the PR getting close, as long as we come to a conclusion and the discussion doesn't end here. I still want to see some typed chai lib that doesn't have the Object pollution.

**Comment by villasv** [comment]
Tracked by https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9120 already

**Comment by jwalton** [comment]
> should IS included in chai, but because it violates our type system, we don't use it.

```
$ node.js
> chai = require('chai');
> x = {};
> x.should
undefined
```

Not sure if Chai polluted this prototype before, but it doesn't seem to now.

**Comment by jwalton** [comment]
```
$ node.js
> chai = require('chai');
> chai.should();
> x = {};
> typeof x.should
'object'
```

-_-

**Pull request closed without merging**
