### PR TITLE
screeps-arena 0.0.1 Initial package

### PR DESCRIPTION
**Pull request by thmsndk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

These types are for a programming game where you write your bot in javascript, and the bot runs in their environment.

This is the game
https://store.steampowered.com/app/1137320/Screeps_Arena/

This is the documentation for the api
https://steamcommunity.com/sharedfiles/filedetails/?id=2505541950

### CODE REVIEW

**Review by lmik — APPROVED** [review]
👍

**Review by pyrodogg — APPROVED** [review]

**Comment by orta** [comment]
This generally looks good to me, but the bot has some requests around the tsconfig and the tslint.json (you can keep the npm-naming: false) which I think are at least worth explaining why you need to differ from the defaults, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53875#issuecomment-862800802

**Comment by thmsndk** [comment]
Hi @orta 
Mostly the config files looks like they do because I've copied them from the `@types/screeps` package that exists for a similar product from the Screeps developers.

I have taken a look at the configs again and adjusted them.

# tsconfig.json
- lib should now target es6
- target has been removed

# tslint.json
- "npm-naming": false,
  - Has been added because there is no npm package for `screeps-arena` that code is private on the game servers.
- "no-single-declare-module": false
  - Has been added because for now, we need to use the declare module syntax to define the types present in the runtime
- "strict-export-declare-modifiers": false
  - Has been added because we use declare and to be explicit about what is exported.
- "dt-header": false,
  - Is to allow patch version in the header
- "whitespace":false,
  - Is because the whitespace rule seems to fail verification with the following error
 ```js
 dtslint types "screeps-arena"

The 'whitespace' rule threw an error in 'C:/Projects/Screeps/DefinitelyTyped/types/screeps-arena/game/index.d.ts':
TypeError: Cannot read property 'forEach' of undefined
    at cb (C:\Projects\Screeps\DefinitelyTyped\node_modules\tslint\lib\rules\whitespaceRule.js:140:45)
    at visitNodes (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27054:30)
    at Object.forEachChild (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27290:24)
    at cb (C:\Projects\Screeps\DefinitelyTyped\node_modules\tslint\lib\rules\whitespaceRule.js:236:12)
    at visitNode (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27045:24)
    at Object.forEachChild (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27391:21)
    at cb (C:\Projects\Screeps\DefinitelyTyped\node_modules\tslint\lib\rules\whitespaceRule.js:236:12)
    at visitNodes (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27054:30)
    at Object.forEachChild (C:\Projects\Screeps\DefinitelyTyped\node_modules\typescript\lib\typescript.js:27292:24)
    at walk (C:\Projects\Screeps\DefinitelyTyped\node_modules\tslint\lib\rules\whitespaceRule.js:99:8)
 ```


Having just looked at them I would also like to point out that the links that @typescript-bot generates seem to be wrong. There does not appear to be an anchor called `#user-content-tsconfigjson` nor `#user-content-linter-tslintjson`  there is however `#tsconfigjson` and `#linter-tslintjson`

**Review by orta — APPROVED** [review]
Cool, thanks this seems reasonable to me then 👍🏻

**Comment by thmsndk** [comment]
Ready to merge

**Pull request merged**
