### PR TITLE
[@types/telegram-web-app] feat: add detailed comments for requestContact callback types.

### PR DESCRIPTION
**Pull request by wuchendi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by WuChenDi** [comment]
@MKRhere hi, Would you find this approach acceptable?

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/telegram-web-app/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 908f372c6d32ee840adfaa752d5438debaf924e0
</p>

**Comment by WuChenDi** [comment]
> I extend my profound gratitude towards @WuChenDi for their PR.
> 
> May I inquire if it is now possible to proceed with a merge and release?

It appears to be infeasible; I have noticed issues with formatting, yet my machine's specifications do not meet the project's requirements.

```
[root@localhost DefinitelyTyped]# pnpm dprint fmt
/home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint)
/home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint)
/home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint)
/home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint)
/home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/wudi/github/DefinitelyTyped/node_modules/.pnpm/dprint@0.45.0/node_modules/dprint/dprint)
```

**Comment by MKRhere** [comment]
Wow, okay. Seems like you may need a system update before you can run dprint. Would you mind if I pulled your branch and raised this PR for you, with the format fix?

**Comment by WuChenDi** [comment]
> Wow, okay. Seems like you may need a system update before you can run dprint. Would you mind if I pulled your branch and raised this PR for you, with the format fix?

Sure, that sounds good. Feel free to pull my branch and raise the PR for the format fix.

**Comment by MKRhere** [comment]
I've opened #68912 including your commits. I've touched up the comments to better reflect existing style, have a look. Thanks!

**Comment by MKRhere** [comment]
Please review and merge https://github.com/WuChenDi/DefinitelyTyped/pull/1 :)

**Comment by WuChenDi** [comment]
> Please review and merge [WuChenDi#1](https://github.com/WuChenDi/DefinitelyTyped/pull/1) :)

done

**Review by MKRhere — APPROVED** [review]

**Comment by WuChenDi** [comment]
Ready to merge

**Pull request merged**
