### PR TITLE
@feathersjs/feathers + @feathersjs/socketio: Minor fixes

### PR DESCRIPTION
**Pull request by j2L4e**
`@feathersjs/feathers`: add generic default type to `Application` interface
`@feathersjs/feathers`: make Params.paginate optional
`@feathersjs/socketio`: make callback optional

I am the owner.

### CODE REVIEW

**Comment by andy-ms** [comment]
@j2L4e Please fix the failures indicated in the Travis CI log.

**Comment by j2L4e** [comment]
```
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/feathersjs__feathers/index.d.ts:45:76
ERROR: 45:76  void-return  Use the `void` type for return types only. Otherwise, use `undefined`. See: https://github.com/Microsoft/dtslint/blob/master/docs/void-return.md
```
I'm not sure how to fix this. `void` is exactly what I need here and it is used as a return type:

```ts
export type Hook = <T>(hook: HookContext<T>) => (Promise<HookContext<T>> | void);
```
Using `(Promise<HookContext<T>> | undefined)` forces you to actually `return undefined;`

Do you have any suggestions?

**Comment by andy-ms** [comment]
@j2L4e I think just disable the lint rule there. Normally it makes more sense to write a function like `tryParseInt(): number | undefined` instead of `number | void`, but this may be an exception if it's typical for callers to not return anything at all.

**Comment by j2L4e** [comment]
@andy-ms thanks for the advice. Done.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
