### PR TITLE
[Lodash] Restrict string values in list iteratees to being keys of the items in the list

### PR DESCRIPTION
**Pull request by CruseCtrl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.15#orderBy
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by niieani — APPROVED** [review]
thanks

**Review by aj-r — APPROVED** [review]
Looks good! This may break some projects but I think this change is still worth it. I would expect any breakages to becaused by bugs/typing issues in the project itself, but we may need to revert this if someone finds a valid use case that breaks.

**Comment by sjoerdmulder** [comment]
Similar issue: `find(obj, 'foo')` breaks while lodash correctly resolves a nested object like: 
```ts
const obj = {
  a: {
    'foo': {
     'this': 'isfound'
    }
  }
};

find(obj, 'foo')
```

**Comment by carsondarling** [comment]
This change broke our build when it was published today. We use:
```ts
uniqBy(object, 'property.path')
```

**Comment by tHe-AK** [comment]
> This change broke our build when it was published today. We use:
> 
> ```ts
> uniqBy(object, 'property.path')
> ```
Hi @CruseCtrl / @aj-r 
Any quick fix for this use-case?

**Comment by CruseCtrl** [comment]
> Hi @CruseCtrl / @aj-r / @niieani, Any quick fix for this use-case?

This was only reported 12 hours ago and I was asleep for most of that time. The quick fix is using the previous version of `@types/lodash` (4.14.191)

I'll try to sort out a more permanent fix today, if I get time.

**Comment by sidoruk-sv** [comment]
@CruseCtrl Hi! 
Could you please revert and publish new version with previous code, and only after that create a new PR (if you will have time of course).

For now Renovate and Dependabot continue to update `@types/lodash` version all over the world.
And I think nobody want to receive broken version

**Comment by lukeapage** [comment]
Just came looking for what caused this after finding the same thing.

I just saw there is a Pr up to revert this:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64922

If it is re-introduced in some way please think about how it is done to minmize errors.

e.g. what happens for me is that if I have a lodash method acting on a array of items, when it can't fit that method type, it falls back to treating my array of items as an object, then screwing up all the return types to be something completely barmy.. which means its difficult to track down the cause of the typescript error.

I'm not sure if there is a way to stop lodash "objects" from ever having arrays being type-cast as them (matching the lodash behavior essentially) so that the error would show on the call site?

**Pull request merged**
