### PR TITLE
missed API added and comments improved

### PR DESCRIPTION
**Pull request by rebelwolfson**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/cpettitt/graphlib
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by rebelwolfson** [comment]
@cpettitt

**Comment by mhegazy** [comment]
@danvk can you please review?

**Comment by danvk** [comment]
👍  looks great on substance

This module contains a mix of tabs and spaces for indentation now (tabs in the `.d.ts`, spaces in the test). The DT docs say "Formatting: Either use all tabs, or always use 4 spaces." I'd also suggest adding a `tslint.json` file as the PR template suggests.

**Comment by mhegazy** [comment]
Feel free to get these changes done in a separate PR.

**Pull request merged**
