### PR TITLE
Add type definitions for rule-reactor

### PR DESCRIPTION
**Pull request by mad-mike**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by mad-mike** [comment]
If I read Travis's output correctly, it only complains about the code snippets I copied into the tests file. Is there any way to exclude that file from checking?

**Comment by mad-mike** [comment]
@typescript-bot Not helpful…

**Comment by mhegazy** [comment]
here are the errors:

> Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/rule-reactor/rule-reactor-tests.ts
ERROR: 4:1    no-var-keyword              Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: 4:5    prefer-const                Identifier 'reactor' is never reassigned; use 'const' instead of 'var'.
ERROR: 13:1   no-unnecessary-class        Every member of this class is a constructor. Use functions instead.
ERROR: 16:1   no-unnecessary-class        Every member of this class is a constructor. Use functions instead.
ERROR: 20:30  whitespace                  missing whitespace
ERROR: 20:32  whitespace                  missing whitespace
ERROR: 21:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 22:17  whitespace                  missing whitespace
ERROR: 22:17  triple-equals               == should be ===
ERROR: 22:19  whitespace                  missing whitespace
ERROR: 22:36  whitespace                  missing whitespace
ERROR: 22:36  triple-equals               == should be ===
ERROR: 22:38  whitespace                  missing whitespace
ERROR: 22:59  triple-equals               == should be ===
ERROR: 22:59  whitespace                  missing whitespace
ERROR: 22:61  whitespace                  missing whitespace
ERROR: 24:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 25:41  whitespace                  missing whitespace
ERROR: 27:1   no-trailing-whitespace      trailing whitespace
ERROR: 28:33  whitespace                  missing whitespace
ERROR: 28:35  whitespace                  missing whitespace
ERROR: 29:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 30:16  triple-equals               == should be ===
ERROR: 30:16  whitespace                  missing whitespace
ERROR: 30:18  whitespace                  missing whitespace
ERROR: 32:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 36:1   no-consecutive-blank-lines  Consecutive blank lines are forbidden
ERROR: 37:1   no-var-keyword              Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: 37:5   prefer-const                Identifier 'p' is never reassigned; use 'const' instead of 'var'.
ERROR: 44:22  whitespace                  missing whitespace
ERROR: 44:27  whitespace                  missing whitespace
ERROR: 44:27  only-arrow-functions        non-arrow functions are forbidden
ERROR: 44:39  no-trailing-whitespace      trailing whitespace
ERROR: 45:4   comment-format              comment must start with a space
ERROR: 45:35  no-trailing-whitespace      trailing whitespace
ERROR: 48:1   no-consecutive-blank-lines  Consecutive blank lines are forbidden
ERROR: 49:27  whitespace                  missing whitespace
ERROR: 49:32  whitespace                  missing whitespace
ERROR: 50:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 53:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 57:1   no-consecutive-blank-lines  Consecutive blank lines are forbidden
ERROR: 62:26  whitespace                  missing whitespace
ERROR: 63:31  whitespace                  missing whitespace
ERROR: 63:33  whitespace                  missing whitespace
ERROR: 64:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 65:42  only-arrow-functions        non-arrow functions are forbidden
ERROR: 65:42  whitespace                  missing whitespace
ERROR: 65:87  whitespace                  missing whitespace
ERROR: 65:89  whitespace                  missing whitespace
ERROR: 67:2   only-arrow-functions        non-arrow functions are forbidden
ERROR: 68:5   comment-format              comment must start with a space
ERROR: 71:1   no-consecutive-blank-lines  Consecutive blank lines are forbidden
ERROR: 72:57  whitespace                  missing whitespace
ERROR: 73:51  whitespace                  missing whitespace
ERROR: 74:57  whitespace                  missing whitespace
ERROR: 75:57  whitespace                  missing whitespace

Either you fix the lint errors or you disable the lint rules. for new packages we ask to address the lint issues.

**Comment by mhegazy** [comment]
Since this has been unchanged for over a month now, i am going to close it. feel free to reopen with the lint issues addressed.

**Pull request closed without merging**
