### PR TITLE
React updates (improved cloneElement & TestUtils return-type inference)

### PR DESCRIPTION
**Pull request by vsiao**
I broke up this PR into multiple commits for easy review.
## `React.cloneElement`

It's not perfect, but it's a heck of a lot better than it was before. The type of `cloneElement` now allows it to take a subset of `P` by using a [new TypeScript 1.8 feature](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#type-parameters-as-constraints). The only problem that I've encountered so far is overriding optional props:

``` ts
interface FooProps {
    foo?: number;
}
class Foo extends React.Component<FooProps, {}> {
}
var element = React.createElement(Foo);
React.cloneElement(element, { foo: 2 });
```

```
error TS2345: Argument of type 'ReactElement<FooProps>' is not assignable to parameter of type 'ReactElement<{ foo: number; }>'.
  Type 'FooProps' is not assignable to type '{ foo: number; }'.
    Property 'foo' is optional in type 'FooProps' but required in type '{ foo: number; }'.
```

The workaround is to just cast your props object to the desired type:

``` ts
React.cloneElement(element, <FooProps>{ foo: 2 });
```
## `ReactTestUtils.xxxRenderedComponentWithType`

Now infers the return type of `findRenderedComponentWithType` and `scryRenderedComponentsWithType` correctly so that you don't have to explicitly pass the type parameter or cast the result.
## Other changes:
- added `React.Key` and `React.Ref<T>` types for easy reference throughout the definition file
- cleaned up `React.CSSProperties` interface (removed comments to reduce bloat, and added some obviously missing properties).

cc @jbrantly

### CODE REVIEW

**Comment by vvakame** [comment]
and cc/ @RyanCavanaugh and @DanielRosenwasser 

If we can't receive response from reviewers, I'll merge this PR after 2 days. please ping me again.

**Comment by pspeter3** [comment]
This looks good but why are the props and state empty interfaces? Could they not be refined generics?

**Comment by RyanCavanaugh** [comment]
> removed comments to reduce bloat

A lot of these comments seem useful -- I don't see why they should be deleted for the sake of file size. Can you justify this more concretely?

**Comment by DanielRosenwasser** [comment]
Agreed with @RyanCavanaugh. This is a `.d.ts` file, don't remove documentation.

**Comment by vsiao** [comment]
@RyanCavanaugh + @DanielRosenwasser:
The `CSSProperties` interface isn't part of the core React API. There's plenty of documentation elsewhere about CSS, so I don't see any reason to document them here. The same argument applies to the `DOMFactory`s—it would be distracting and unhelpful to users to fully document each property in `React.DOM`.

**Comment by DanielRosenwasser** [comment]
> it would be distracting and unhelpful to users

> There's plenty of documentation elsewhere

These descriptions come up in tooltips and completion lists. They are helpful for exploratory coding/review.

So I'm still not convinced that the desire to author more easily (and I'm not convinced it is dramatically harder to do so) is a good enough reason to remove existing documentation which can be useful for users. The ratio of users to declaration file writers should justify this cost.

**Comment by vsiao** [comment]
> These descriptions come up in tooltips and completion lists.

Thanks, I didn't know that users could actually read these comments without reading the .d.ts file. I assume it's a Visual Studio feature?

**Comment by DanielRosenwasser** [comment]
@vsiao it's also a feature shared among all editors that use TSServer - so VS Code and any other editor that leverages it in its UI can take advantage of it.

**Comment by vsiao** [comment]
Well, the comments are back. I added some missing comments, too. Let me know if you have any other feedback.

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Thanks @vsiao!

**Comment by adidahiya** [comment]
@vvakame @vsiao is there any way I get added as a reviewer for `react.d.ts` in the future? Would be nice to have heads up about typings upgrades that are slightly breaking like this one (I had to add some type casts as noted in the PR description -- thanks for the explanation btw). I have touched the file so I believe I'm in the git history already.

**Pull request merged**
