### PR TITLE
three: Fixed declaration for class PolyhedronGeometry to use number arrays and not Vector3/Face3 arrays (#17041).

### PR DESCRIPTION
**Pull request by matthewtebbs**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

### CODE REVIEW

**Comment by mhegazy** [comment]
@LebedenkoN
@couchninja
@noveyak
@markezine
@V0idExp
@efokschaner
@mpk
@efokschaner
@saabi
@jnordberg
can you please review?

**Comment by efokschaner** [comment]
:+1: Thanks @matthewtebbs for the fix. Whoever merges this can also close https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17041

**Comment by jnordberg** [comment]
👍 

Matches docs at https://threejs.org/docs/#api/geometries/PolyhedronGeometry

**Comment by matthewtebbs** [comment]
Indices are retrieved in groups of 3, e.g. `Face3`, so I can see how the docs might call the array `faces`, strictly speaking I suppose it could be `faceIndices`.

**Comment by efokschaner** [comment]
Entirely cosmetic but I prefer matching the implementation over the docs.

**Pull request merged**
