### PR TITLE
[node] Adds isBuiltin method to Node Module

### PR DESCRIPTION
**Pull request by philnash**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/module.html#moduleisbuiltinmodulename
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. 

This method was added in Node v18.6.0 and v16.17.0. I'm not sure what to do about version numbers.

My auto formatting in my IDE has changed double quotes to single quotes and fixes some whitespace in the test files. I have left this in the change since it follows the project's `.prettierrc.json`. Please let me know if you'd rather I revert those parts of the change.

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Neat 👍

**Comment by philnash** [comment]
The CI tests failed due to an out of memory error that doesn't seem related to my changes. I'm unable to start the Action again without pushing an update. Could someone else try the test suite again? 
Thanks!

**Comment by philnash** [comment]
CI failed with an out of memory error again. This seems weird to me, especially as [another PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63824) that change the Node definitions also fail the same way, yet other recent PRs haven't failed. Am I reading too much into this?

Has anyone seen this sort of failing before and is there anything we can do about it? Thanks!

**Comment by peterblazejewicz** [comment]
> Has anyone seen this sort of failing before and is there anything we can do about it? Thanks!

This can be same case as here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63033
(blanket imports causing recursion)

**Comment by philnash** [comment]
Is there anything I can do to fix it or otherwise move this PR along?

**Comment by philnash** [comment]
Rebased with master and force pushed to get CI going again (and hopefully pass this time).

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@philnash sorry for delay due to issue with `aws-sdk` related declarations!

**Comment by philnash** [comment]
Ready to merge

**Pull request merged**
