### PR TITLE
[react-instantsearch] reflect `smartSort` widget/connector implementation and new parameters `stats` widget/connector

### PR DESCRIPTION
**Pull request by shortcuts**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <[smartSort](https://github.com/algolia/react-instantsearch/pull/3009)><[stats](https://github.com/algolia/react-instantsearch/pull/3010)>

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]
this is good! (but should only be merged once the version with those is released)

don't forget to update the applicable React InstantSearch  version in the headers of these files

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-instantsearch-native ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-instantsearch-native@latest/))
was missing the following properties:
1. ExperimentalConfigureRelatedItems
1. QueryRuleContext
1. EXPERIMENTAL_connectConfigureRelatedItems
1. connectHitInsights
1. connectQueryRules

<details>
<summary>as well as these 5 other properties...</summary>
<p>ExperimentalConfigureRelatedItems, QueryRuleContext, EXPERIMENTAL_connectConfigureRelatedItems, connectHitInsights, connectQueryRules</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against caef431a23c6df924e6b72b635775f538c72f716
</p>

**Comment by shortcuts** [comment]
Released in https://github.com/algolia/react-instantsearch/commit/cd814534b01e6ecd7b7cb0582d085b3fc1ee73d2

**Review by Haroenv — APPROVED** [review]

**Comment by shortcuts** [comment]
Converted to draft until the new version is released

**Comment by shortcuts** [comment]
Rename released in https://github.com/algolia/react-instantsearch/pull/3028

**Review by Haroenv — APPROVED** [review]
thanks @shortcuts

**Comment by shortcuts** [comment]
Ready to merge

**Pull request merged**
