### PR TITLE
Make render optional in react-loadable

### PR DESCRIPTION
**Pull request by mohsen1**
Reference: https://github.com/thejameskyle/react-loadable#example

### CODE REVIEW

**Comment by odensc** [comment]
I don't really understand this PR. There's already a `OptionsWithoutRender` and `OptionsWithRender` interface, which are then unioned and used as the `Options` object, effectively making `render` optional.

As you can see in the tests, there are even some places where render is not included and it works fine. Could you please explain what this changes?

**Comment by mohsen1** [comment]
in my simple case I was getting an error. Try it yourself. Just paste the example I posted in the original post

**Comment by Kovensky** [comment]
That example should have already passed. Making `render` optional means that your Promise can now resolve to _anything_ that `extends object`, even if you don’t provide `render` – it’ll just pick the overload where `render` is optional, making the first overload useless.

AFAICT this should only have been an error if you incorrectly exported your component; now it will never be an error.

**Comment by odensc** [comment]
I'm not getting any error with that example.

`render` is only required when the `loader` promise does not directly return a React Component or an object of `{ default: React.Component }`.

If you were getting an error about missing `render`, that means the return type of the loader promise is invalid. Have you tested the code that had the error, and does it work in the browser? If it works, that means making `render` optional is only a bandage over a different root issue which should be fixed.

By simply making render optional, we actually lose some type checking abilites. For example:

```ts
// Component.tsx

export const MyComponent = () => <div />;
```

```ts
// App.tsx

// With the previous version of types, this would give an error because the promise does not return a React component or { default: React.Component }. Which is correct, as this code would cause an error in the browser because react-loadable cannot handle such a promise.
 
// With the changes in this PR, this code passes the type checking but causes an error in the browser because the promise doesn't return the correct export.

const LoadableComponent = Loadable({
    loader: () => import("./MyComponent"),
    loading: () => null
});

[...]
```

Would you mind sharing the piece of code that gave you an error before? I don't think this PR is a proper fix for it.

cc/ @RyanCavanaugh I think this should be reverted for now, as it causes a regression in type checking.

**Comment by Kovensky** [comment]
Looking more into it, this seems to be caused by a problem either with `@types/react` or with typescript 2.4.1.

```ts
// test-component.tsx
import * as React from 'react';

export default class AComponent extends React.Component {
  render() {
    return null;
  }
}
```

```ts
// index.ts

async function load<Props>(): Promise<React.ComponentType<Props> | { default: React.ComponentType<Props> }> {
  return import('./test-component'); // error
}
```

Full error message:

```
Type 'typeof ".../DefinitelyTyped/types/react-loadable/test-component"' is not assignable to type 'ComponentClass<Props> | StatelessComponent<Props> | { default: ComponentType<Props>; }'.
  Type 'typeof ".../DefinitelyTyped/types/react-loadable/test-component"' is not assignable to type '{ default: ComponentType<Props>; }'.
    Types of property 'default' are incompatible.
      Type 'typeof AComponent' is not assignable to type 'ComponentType<Props>'.
        Type 'typeof AComponent' is not assignable to type 'StatelessComponent<Props>'.
          Type 'typeof AComponent' provides no match for the signature '(props: Props & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.'
```

It seems that the compiler is _requiring_ that a `React.ComponentClass` _also_ be a `React.StatelessComponent` at the same time.

The only reason making `render` optional is working is because it is hiding the actual error.

**Comment by Kovensky** [comment]
Follow-up:

Changing the type to be `React.ComponentClass` instead shows why it is requiring that the component be a `StatelessComponent`:

```ts
async function load<Props> (): Promise<React.ComponentClass<Props> | { default: React.ComponentClass<Props> }> {
  return import('./test-component')
}
```

```
Type 'typeof ".../DefinitelyTyped/types/react-loadable/test-component"' is not assignable to type 'ComponentClass<Props> | { default: ComponentClass<Props>; }'.
  Type 'typeof ".../DefinitelyTyped/types/react-loadable/test-component"' is not assignable to type '{ default: ComponentClass<Props>; }'.
    Types of property 'default' are incompatible.
      Type 'typeof AComponent' is not assignable to type 'ComponentClass<Props>'.
        Type 'AComponent' is not assignable to type 'Component<Props, ComponentState>'.
          Types of property 'setState' are incompatible.
            Type '{ <K extends never>(f: (prevState: {}, props: {}) => Pick<{}, K>, callback?: (() => any) | undefi...' is not assignable to type '{ <K extends never>(f: (prevState: ComponentState, props: Props) => Pick<ComponentState, K>, call...'.
              Types of parameters 'f' and 'f' are incompatible.
                Types of parameters 'props' and 'props' are incompatible.
                  Type '{}' is not assignable to type 'Props'.'
```

Is this possibly caused by the stronger weaker property checks, or by the change done in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17288? It seems that specifying default prop types cause strange compiler behavior when the actual value given is not itself a subtype of the default value.

**Comment by mohsen1** [comment]
Isn't `React.ComponentType` union of statelesss and class components?

**Comment by Kovensky** [comment]
Yeah, I investigated more and it turns out that this whole thing is just caused by a very confusing error message. Ignore my code snippets above, they are invalid as they don't do generics correctly.

The error message will complain about a missing `render` function if you only provide a `loader`, but what is _actually_ missing is a `loading` function.

**Pull request merged**
