### PR TITLE
fix(maxmsp): mgraphics size missing

### PR DESCRIPTION
**Pull request by FrancescElies**
mgraphics size is missing.

Size represent the dimensions of a jsuiobject.
image

Sadly size I couldn't find it in the max docs but at runtime it's definitely there.

### CODE REVIEW

**Comment by twhiston** [comment]
Sorry I haven’t had a chance to look at this yet. I’ll get to it tomorrow

**Review by twhiston — APPROVED** [review]

**Comment by FrancescElies** [comment]
@twhiston sorry for my late reply, I was on vacations, thanks for the invite to cowning this part, I added myself to `index.d.ts`. 

Now we can merge this pr :)

**Review by twhiston — APPROVED** [review]
Thanks! Great to have you onboard as a maintainer, very much appreciated!

**Comment by FrancescElies** [comment]
Ready to merge

**Pull request merged**
