### PR TITLE
[Flickity] Add module declaration

### PR DESCRIPTION
**Pull request by harrygr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
We're trying to avoid `declare module`. I think the best way to structure this would be:

```ts
export = Flickity;
export as namespace Flickity;

declare global {
    interface JQuery {
        flickity: Flickity.FlickityJquery;
    }
}

declare class Flickity { ... }

declare namespace Flickity {
	interface FlickityJquery { ... }
	interface Options { ... }
}
```

**Comment by harrygr** [comment]
Fair enough, although wouldn't it need to be:

```typescript
export = Flickity;
export as namespace flickity;
```

as when used as a module Flickity is imported with `import * as Flickity from 'flickity'. (I.e. shouldn't the namespace equal the module name?)

Sorry, still learning about declaration files. I can update the PR if ok.

**Comment by andy-ms** [comment]
The namespace name should match the name of the global variable. So if it's `window.Flickity` use `export as namespace Flickity;`, if it's `window.flickity` use `export as namespace flickity;`

**Comment by harrygr** [comment]
But if I'm using the library as a module then the global name is surely irrelevant. If we are `import`ing from `flickity` then how will typescript know to use the definitions from the `Flickity` namespace?

**Comment by andy-ms** [comment]
`import`ing and `export as namespace` are two separate things. If you write `import * as foo from "foo";` TypeScript [module resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html) will (eventually) find `node_modules/@types/foo/index.d.ts` and use whatever's there.

In contrast, `export as namespace Bar` has nothing to do with modules; it instead declares a global variable `Bar` (AKA `window.Bar`), When TypeScript sees that, it will add `Bar` to its map of global symbols, and then when a `Bar` identifier is seen in code, if it's not matched by any local, it will be linked to the global `Bar`.

**Comment by harrygr** [comment]
I'll open a new PR with the suggested approach when I get a chance to test it

**Pull request closed without merging**
