### PR TITLE
Switch all packages which compile with module=node16 to node16

### PR DESCRIPTION
**Pull request by jakebailey**
655 packages fail this check: https://gist.github.com/jakebailey/864006c88463c64a8f15ef73496898ec

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
CI failed `verror` and `db-migrate-pg`. `verror` fails on master, but `db-migrate-pg` does actally pass when flipped back to `commonjs` and I will revert it.

**Comment by jakebailey** [comment]
I missed `db-migrate-pg` because I didn't actually run `dtslint`, but rather `tsc` only, and the error is an expect error.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jakebailey** [comment]
I'm also reverting verror, not sure what's going on there but I don't want to futz with that.

**Comment by 0564692083** [comment]
186000010006086026045

**Pull request merged**
