### PR TITLE
D3 version 4 Legacy + Additional Module

### PR DESCRIPTION
**Pull request by tomwanzek**
This PR is related to D3 version 4 definition request issue #9936.

@Ledragon thanks for your contribution of d3-request!

@gustavderdrache and @mhegazy @RyanCavanaugh @andy-ms Please see [this specific comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9936#issuecomment-237378115) the latest status update and key open issues (items 1-3 listed there)

cc: @vvakame 

Thanks in advance!!!
- Adds new definitions for d3-dsv with test. Old definitions by Jason Swearingen renamed to d3-dsv-0.0.28.d.ts in accordance with old version number used on @types. Note: The old definitions are not a reflection of the new d3-dsv module
- Adds new definitions for d3 standard bundle. The module re-exports the constituent modules and also exposes a d3 global for vanilla script use. The old legacy definitions and tests are included in renamed files with -3.5.17- suffix in the file name. (d3-geo re-exports  are currently commented out pending completion of the module definitions)
- d3-request is added complete with tests in this PR as it uses d3-dsv.

Add a new type definition and replace legacy version definitions.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
I fixed a missing space in d3-timer as per latest definitions tester. As for the remaining errors...

From what I see in the Travis output, these are the errors related to the d3.d.ts legacy renaming to d3-3.5.17.d.ts, as they depend on the old D3 library:

* plottable
* dc
* d3.cloud.layout
* dagre-d3
* c3
* cal-heatmap

How should they now import the legacy version? Back to the already flagged issues.

Not sure about the purpose of the old d3/plugin directory in the files therein in terms of historic relevance.
d3/plugin. But its part of the legacy conversion.

(All other Travis error output seems unrelated to the definition changes.)

**Comment by tomwanzek** [comment]
As far as this PR is concerned, the changes cause dependencies to the legacy definitions of **d3** to fail. As mentioned before, I require guidance on how to ensure the legacy dependencies can be fixed.

**Comment by paulvanbrenk** [comment]
@tomwanzek Can you point the failing tests to use the legacy definition files?

**Comment by tomwanzek** [comment]
@paulvanbrenk I would love to do that, however, this is where my predicament comes in. I have posed two questions related to the treatment of legacy definitions/transition under #9936 which tracks the overall completion of the new D3 definitions. Specifically, in [this issue comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9936#issuecomment-237378115), I have posed these two questions to @mhegazy @RyanCavanaugh @andy-ms :

> 2 **Legacy Definitions:** I will create a second new PR against the `types-2.0` branch for the following: **d3-dsv**, **d3-request** and _d3 standard bundle definitions_. The latter are a re-export of the relevant separate d3 modules with a UMD format and an `export as namespace d3` for the shared **global**. This pull request will require re-naming the old `d3-dsv.d.ts` and `d3.d.ts` and their related test. @gustavderdrache pointed out the old convention. I am assuming that this is still correct in the world of **npm @types** definition file acquisition. If not, please advise otherwise on how we can ensure people can access the old D3 version 3.5.17 definitions.
3 **Branch Merge Conflict Prevention** As we have currently addressed definitions for TS2 in the `types-2.0` branch, how do we avoid them being overwritten by merge/pub jobs from `master` to `types-2.0`? For the legacy definitions currently under `master` for `d3` and `d3-dsv` (which is not truly d3-dsv as we know it today). Even if we created TS 1.8.x definitions, which can be published under `master`, they would be a substantial step back from the definitions using TS2 features. Do we bleed them out until all of DefinitelyTyped  is TS2 compatible? What is the timeline? Or do we need an alternative strategy, please advise.

My ability to re-point the affected libraries to the legacy definitions is in particular tied to question 2 (Legacy Definitions). To date I have been unable to find an updated contribution guide that clarifies how the legacy definitions should be renamed or move to a separate folder with version suffix. And then in turn, how the affected consuming libraries (**plottable** etc.) should be re-pointed to them under the new **DefinitelyTyped/types-2.0 -> @types** publication chain.

I.e. is a partial `package.json` the way to go, which includes a dependency on a legacy version as per @types version count? What is the proposed approach?

I have only seen comments elsewhere that would suggest to use something like `npm install @types/d3@0.0.31 --save` when installing a specified legacy definition version into a project. Note, that what @types tracks as version 0.0.31 is indeed a set of definitions for the old version 3.5.17 of D3. 

But how the upstream definitions in `DefinitelyTyped/types-2.0` should reference the same legacy version of the definitions is not clear to me.

**Comment by tomwanzek** [comment]
I have refreshed this PR branch from types-2.0. As it now includes the since merged definitions for the **d3-geo** module, I have included into the re-export for the new *d3* standard bundle definitions.
I have also updated the version number headers in `d3/index.d.ts` (version 4.2.1) and `d3/d3-3.5.17.d.ts`.

The key issue related to how to handle the re-pointing of libraries consuming the legacy definitions still affects this PR. I have since opened issue #10711 still hoping for an answer/guidance.

If I am overlooking the obvious, feel free to set me straight and let me know how to fix this PR :smile:.

**Comment by tomwanzek** [comment]
As per my [issues comment on issue 10711 New Contribution Guide/Transition Issues] (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10711#issuecomment-243946489) I am closing this PR.

The new (v4) and legacy (v 3.5.17) definitions for the standard D3 bundle can currently not yet be set up in accordance with the new folder structure intended for future use. A follow-up will be required for `d3` when the new structure is implemented.

The definitions for `d3-dsv` and `d3-request` will be spun off as a separate new PR.

cc @RyanCavanaugh @gustavderdrache @Ledragon

**Pull request closed without merging**
