### PR TITLE
fix(webdriverio): $$ utility returns an array, fixes #16841

### LINKED ISSUE #16841: webdriverio.Client.$$ returns Array
- [x] I tried using the `@types/webdriverio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti @timbru31

`webdriverio.Client.$$` returns an Array that you can map over, etc:

```
browser.$$('foo').map(() => {})
```

However this throws a compile error due to incorrect typings.

### PR DESCRIPTION
**Pull request by timbru31**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webdriverio/webdriverio/blob/master/lib/commands/$$.js
- [x] as per #16147, I've added @fsmedberg-tc as an author, too

Crossref to https://github.com/webdriverio/webdriverio/issues/2118
This fixes:  #16841

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Looks like this will fix https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16841?

**Comment by timbru31** [comment]
@OliverJAsh yes 👍

**Comment by timbru31** [comment]
@christian-bromann could you possibly assist?

**Comment by christian-bromann** [comment]
@timbru31 this looks good to me

**Pull request merged**
