### PR TITLE
Add missing property className.

### PR DESCRIPTION
**Pull request by Strato**
[For reference](https://facebook.github.io/react/docs/animation.html#rendering-a-different-component).

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by pspeter3** [comment]
Do you have a link to the React documentation for this?

**Comment by Strato** [comment]
Yes. See first line of top comment.

**Comment by pspeter3** [comment]
👍

**Comment by vsiao** [comment]
duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8292

**Pull request merged**
