### PR TITLE
[faker] Add missing `cityName` and fix `city` argument type in faker.address

### PR DESCRIPTION
**Pull request by p-j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
[faker.address.city argument type (code)](https://github.com/Marak/faker.js/blob/master/lib/address.js#L63-L81) [(doc)](https://marak.github.io/faker.js/faker.address.html#.city)
[faker.address.cityName (code)](https://github.com/Marak/faker.js/blob/master/lib/address.js#L100-L107)

---

Please don't hate me for the quote change, it's a [config change at the root level](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e3d4752e1587ec54c37636161a7d96b5a1984a61)

### CODE REVIEW

**Review by pkuczynski — CHANGES_REQUESTED** [review]
Can you revert changing ' to " please? It makes a lot of noise and is not relevant to the subject of this PR, neither required.

**Comment by p-j** [comment]
> Can you revert changing ' to " please? It makes a lot of noise and is not relevant to the subject of this PR, neither required.

It's been changed in the [prettier config](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e3d4752e1587ec54c37636161a7d96b5a1984a61) about a month ago. I guess we've gotta go through the noise at least once.  

To make it easier, here is the actual changes I've made: [test file](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52787/files#diff-40aa97dbdd4fa4724083c972b6f7097a57d5169ffcfe94764ce9f4bdb6236514R19-R20) - [source file](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52787/files#diff-22605747c70de0fe07b686b06a1235f39c32faf85b32d66fc18c9623379d3f50L24-R26)

**Comment by p-j** [comment]
@pkuczynski I've split the prettier changes and the actual code change in 2 separate commits.

**Review by pkuczynski — CHANGES_REQUESTED** [review]
Prettier is not a mandatory tool. If you wanna run it on this package, feel free to fire up a separate PR for it. But this PR should only do one thing at a time and in this case its adding missing method and fixing the argument

**Comment by p-j** [comment]
Running prettier is part of the "Avoid [common-mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes)" as the 2nd bullet point.
But I agree the PR is a bit messy as it is so I've made [another one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52790).

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
Ready to merge

**Pull request merged**
