### PR TITLE
Add oauth-signature typings for 1.5

### PR DESCRIPTION
**Pull request by okcoker**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
You can simplify it a little(optionally), but you would have to implement `export as namespace`:
https://github.com/bettiolo/oauth-signature-js/blob/master/src/app/oauth-signature.js#L293
```ts
// Type definitions for oauth-signature 1.5
// Project: https://github.com/bettiolo/oauth-signature-js
// Definitions by: Sean Coker <https://github.com/okcoker>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare namespace OauthSignature {
    function generate(
        httpMethod: string,
        url: string,
        parameters: { [key: string]: any },
        consumerSecret: string,
        tokenSecret?: string,
        options?: GenerateOptions,
    ): string;

    interface GenerateOptions {
        encodeSignature: boolean;
    }

    class SignatureBaseString {
        constructor(httpMethod: string, url: string, parameters: { [key: string]: any });

        generate(): string;
    }

    class HttpMethodElement {
        constructor(httpMethod: string);

        get(): string;
    }

    interface ParsedUrl {
        scheme: string;
        authority: string;
        port: string;
        path: string;
    }

    class UrlElement {
        constructor(url: string);

        get(): string | undefined | null;
        parseInBrowser(): ParsedUrl;
        parseInNode(): ParsedUrl;
    }

    class ParametersElement {
        constructor(parameters: { [key: string]: any });
        get(): string;
    }

    class ParametersLoader {
        constructor(parameters: { [key: string]: any });

        get(): { [key: string]: any };
    }

    class Rfc3986 {
        encode(decoded?: string): string;
        decode(encoded?: string): string;
    }

    class HmacSha1Signature {
        constructor(signatureBaseString: string, consumerSecret?: string, tokenSecret?: string);
        generate(encode?: boolean): string;
    }

    class HmacSha1 {
        constructor(text?: string, key?: string);

        getBase64EncodedHash(): string;
    }
}

declare var oauthSignature: typeof OauthSignature;

export as namespace oauthSignature;
export = oauthSignature;
```

**Comment by okcoker** [comment]
@peterblazejewicz thanks for that. Just pushed up that change.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@okcoker thx!

**Comment by okcoker** [comment]
Ready to merge

**Pull request merged**
