### PR TITLE
angular2: update typings for angular2 and angular2 router Alpha 31

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by jeffbcross** [comment]
@alexeagle already peer-reviewed this on our fork: https://github.com/angular/DefinitelyTyped/pull/7

**Comment by alexeagle** [comment]
:+1:

**Comment by alexeagle** [comment]
By the way, we've had a pattern of these typings lagging the public release of angular by as much as a week. On a couple occasions, users have asked us "where are the typings for the current release? Can you publish them on NPM as well" which is not the distribution pattern we are recommending.
Maybe we could discuss a faster track for this part of our release? @vvakame @basarat

**Comment by basarat** [comment]
> Maybe we could discuss a faster track for this part of our release

Perhaps one of you can become a collab for this repo /cc @borisyankov

**Comment by borisyankov** [comment]
That sounds like a solution, @basarat.
@alexeagle will that work for you guys, or thinking of something more automated?

**Comment by alexeagle** [comment]
That would be fantastic. We will review PRs into DT/angular2/... and then
we'll be able to commit them ourselves on our own release schedule.

What can we do to ensure we don't commit anything to another directory? Is
our promise and good intention enough for you?

Thanks!

**Comment by borisyankov** [comment]
I have a rather high confidence of your abilities not to mess up anything (and/or to fix it if so) :)

If touching other definitions is a high enough concern, in future, I think we can add some step in the CI to check if files only in a single directories have changed on a given commit.

@alexeagle do you want your account added or another one?

**Comment by alexeagle** [comment]
You can add me, please. Thanks!
-Alex

**Comment by borisyankov** [comment]
You are in, Alex.
Welcome ;)

**Comment by alexeagle** [comment]
Thanks Boris, I'm looking forward to contributing to the TypeScript
ecosystem!

**Pull request merged**
