### PR TITLE
Signer and Verifier are Writable Stream in Crypto

### PR DESCRIPTION
**Pull request by sledorze**
From the doc:

https://nodejs.org/docs/v0.10.0/api/crypto.html#crypto_class_verify
https://nodejs.org/docs/v0.10.0/api/crypto.html#crypto_class_sign

### CODE REVIEW

**Comment by vvakame** [comment]
@sledorze thanks mate!
This change not contains latest node.js? if v0.12.0 same as v0.11, please send PR to node/node.d.ts again. :wink:

**Comment by sledorze** [comment]
not sure about how the branches are organised
Which one should be updated?

**Comment by vvakame** [comment]
latest .d.ts is without versioning one. node/node.d.ts is definition for latest version's node.js.

**Comment by sledorze** [comment]
done: https://github.com/borisyankov/DefinitelyTyped/pull/5654

**Pull request merged**
