### PR TITLE
Generic GeoJSON properties in the type definition of leaflet

### LINKED ISSUE #20103: @types/leaflet Generic geojson feature properties
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90 @iv-mexx @rbuckton @Timmmm @jramsay 

Hi :smile: 

I'd like to discuss a general proposal for leaflet types.

I work with leaflet and flowtype and wrote my own definitions. This project is not my latest version and far from being perfect but that's not the point.

The important thing is that I use a generic type for geojson properties and this leads to generic leaflet features. Say I create a new `L.Polygon`. It would be of type `LeafletPolygon<PolygonProperties>`. So when I want to have the 'classic' behavior it's just `LeafletPolygon<Object>`.

Since I started to work with typescript I really miss the type safety here.

What do you think?

### LINKED ISSUE #21069: Leaflet. FeatureGroup.setStyle should return PathOptions
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5761cfc6f2bb9de0af9085e4f119d0ef590c500e/types/leaflet/index.d.ts#L744
It should be PathOptions. According to http://leafletjs.com/reference-1.2.0.html#featuregroup , setStyle method accept PathOptions object as an argument. But in d.ts it says it accept function which returns PathOptions.

### PR DESCRIPTION
**Pull request by atd-schubert**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #20103.
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

This is a pull request according to issue #20103 including some tests.

In addition I enhanced the `Marker` class with the property `feature` and the `toGeoJSON` method, like it was already typed for a `CircleMarker`...

I fixed #21069, also. It would have a merge conflict when I open another merge request, so I decided to fix it here directly...

---

Closes #20103
Closes #21069

### CODE REVIEW

**Comment by alejo90** [comment]
Just a question. Wouldn't it be better to have the generic default value be `object` instead of `any`?

**Comment by atd-schubert** [comment]
In my opinion the `any` type is the better type. Here an example, why I think so:

```typescript
const test: any = {};
test.property = "it works...";
```
vs.
```typescript
const test: object = {};
test.property = "it doesn't work...";
```
*Reason: `property` is an unknown property of type `object`*

On the other hand:

```typescript
let test: any = {};
test = "it works, but it shouldn't...";
test = ["it works, but it shouldn't..."];
test = 123;
```

But I don't know a solution for both... Does somebody else?

**Comment by alejo90** [comment]
👍Yeah, I see no way around it

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
As far as I understand, this doesn't actually seem to introduce any type safety as described in #20103 because your type parameters aren't being observed anywhere - in other words, they're unused beyond feeding them to other types that feed them to other types, etc.

So maybe I'm missing something, but where are these type parameters actually used?

**Comment by atd-schubert** [comment]
You have a type safety for the properties connected to your geometry in a GeoJSON feature. For example you use the GeoJSON Layer of Leaflet like this:

```typescript
interface IMyProperties {
  example: string;
  // ...
}
const geoData: geojson.FeatureCollection<geojson.Point, IMyProperties> = {
  // ...
};

const geoJSONLayer: L.GeoJSON<IMyProperties> = L.geoJSON(geoData, {
  onEachFeature: (feature) => {
    // `feature.properties` is typed as IMyProperties now...
    // ...
  },
  pointToLayer: (feature, latlng) => {
    // `feature.properties` is typed as IMyProperties now...
    if (feature.properties.example === "monument") {
        return L.marker(latlng).setIcon({url: "monumentIcon.png"})
    }
  },
});
```

Similar with Polygon, Marker etc.:

```typescript
const marker: L.Marker<IMyProperties> = L.marker(/* ... */);
marker.feature.properties.example = "valid";
// marker.feature.properties.another = "is not valid anymore";
marker.toGeoJSON(); // returns a GeoJSON feature with properties of type `IMyProperties`
```

**Comment by RyanCavanaugh** [comment]
@atd-schubert Please address comments from the code reviewers.

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
