### PR TITLE
allow optional success parameter on callback passed to it()

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vvakame** [comment]
*jasmine/jasmine.d.ts*

to authors(@borisyankov @theodorejb @davidparsson). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by theodorejb** [comment]
:-1:

As far as I can tell from the [Jasmine documentation](http://jasmine.github.io/edge/introduction.html#section-Asynchronous_Support) the `done` callback does not accept any parameters.

However, it does look like there is a `done.fail` function which can be used to fail an async spec. It would be great if the TypeScript definitions supported this.

**Comment by errorx666** [comment]
If you pass false to this function it will fail the test.  I use it for the "catch" handlers in my promises, where no specific condition has failed but the code is somewhere it shouldn't be, so the test should bail out.

**Comment by theodorejb** [comment]
@errorx666 Is that behavior documented anywhere? If so a test should also be added for it.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
