### PR TITLE
[linkifyjs] re-write definitions

### PR DESCRIPTION
**Pull request by G-Rath**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://soapbox.github.io/linkifyjs/docs/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

----

The general gist is that the type definitions for the core are not correct, and the tests don't test the types.

I've re-write the definitions to properly type linkify, but haven't had time to do full testing, due the amount of work improved, and the general state of linkify.

When running the tests locally, I get an error about `Dependency @emotion/styled not in whitelist`

It's very late here, so I'm about to go to bed - I'll pick this back up in the morning and make any required changes to get the test passing.

### CODE REVIEW

**Comment by G-Rath** [comment]
@szhu Cheers for the ping. I'm not in any rush about it - I just wanted to get these corrected to reduce the amount of breaking changes for people who might consume the types .

I've used linkify in a couple of my libraries for a while, and so had type definitions for the core for a while, which is why I was surprised when I saw the ones here.

I saw the the two PRs for the types, and read through some of your comments which helped me understand and improve specific areas, such as the tests.

More than happy to answer any questions you might have :)

(and hope you feel better soon!)

**Comment by armanio123** [comment]
Maintainer here. This is a fairly big change that introduces a bunch of breaking changes but I have very limited knowledge on the library so I'll defer the approval to the original owner. Nonetheless, I have review the type declarations and syntax and lgtm. 

Let me know @szhu when review is done and I can help with merging it.

**Comment by szhu** [comment]
Hey @G-Rath, one thing that would help me is if you separated this PR into two commits, one of the commits is purely about fixing formatting (single quotes/double quotes, etc.) That way, I can just look at the other commit to review the import parts of the diff.

First, can I ask how you chose the formatting style you used? Is that simply what your editor was set to, or is there some DefinitelyTyped-enforced formatting standard? (There wasn't when I contributed this, but I remember discussions about adding a style guide.)

Anyway, I think your style updates are fine, but it would be great if you could keep them separate the formatting changes from the content changes. Here's a simple way to do that that I typically use:

1. Checkout the original code:
   `git checkout f4627ee~1`
2. Run the formatter you used over all the files in this PR.
3. Create a commit out of just those changes.
4. Set the working directory to be after your original changes:
   `git checkout f4627ee .`
5. Create a commit out of this. This is the new version of your original commit.
6. Force push. (GitHub will keep a record of what the old commit was.)

**Comment by G-Rath** [comment]
@szhu The majority of the stylings come from DT - this includes the quotes, simple vs complex array types, and indentation.

What's left over is pretty minimal, and mostly prettier driven. iirc the only conscious styling choice I made was to make the `LinkEntityType` union chopped, and w/ the `;` on a newline - I find that works well for unions of that type, as it makes it easy to adjust it's members and overall treat it as a list.

When I've got a chance I'll look to apply formatting in a commit prior to the type changes, however, I don't think it'll be of much value due to size of changes I've made.

The only formatting change outside of the `tsconfig.json` is the quotes on the imports - the `tsconfig.json` itself doesn't require review, since it's controlled by DT.

**Comment by G-Rath** [comment]
@szhu have you managed to have any time to review this?

Sadly I've not had the time to revert the formatting changes, but you should just be able to chuck the old files into prettier to match the current formatting, making it pretty much a non-issue :)

It would be nice to get this merged if possible, given the state of the current typings

**Comment by jessetrinity** [comment]
>Anyway, I think your style updates are fine, but it would be great if you could keep them separate the formatting changes from the content changes. Here's a simple way to do that that I typically use:

@szhu are you requesting changes before you approve? If so could you start a review so this gets sorted correctly? Otherwise it will probably get merged on YSYL. Thanks!

**Comment by szhu** [comment]
Haven't had time, but it's probably fine, I'll just approve it

**Review by szhu — APPROVED** [review]

**Comment by szhu** [comment]
Sorry I didn't have time to give this a detailed review @G-Rath, but thanks for all the updates to this definition!

**Pull request merged**
