### PR TITLE
Adds onFinishCommand method from yargs@15.1

### PR DESCRIPTION
**Pull request by mdouglass**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yargs/yargs/blob/master/docs/advanced.md#command-finish-hook
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
🔔 @poelstra @mizunashi-mana @pushplay @jeffkenney @JimiC @steffenvv @forivall @ExE-Boss  for review

**Comment by forivall** [comment]
It would be nice to track the return types from commands, so that `any` could be avoided, but otherwise, LGTM

**Comment by mdouglass** [comment]
> It would be nice to track the return types from commands, so that `any` could be avoided, but otherwise, LGTM

My test code was using commandDir which makes that impossible (afaik) so it didn’t occur to me. Maybe you could do it for command and then if commandDir is called widen to any? Or maybe make it unknown|undefined?

**Comment by forivall** [comment]
yeah, `commandDir` does make it impossible. `unknown` would be best imo, but that requires a newer typescript version (though, i haven't checked if these typedefs only target newer versions.)

**Comment by ExE-Boss** [comment]
Well, `@types/yargs` has&nbsp;been&nbsp;targetting **TypeScript&nbsp;3.0+** for&nbsp;several&nbsp;major&nbsp;versions&nbsp;now, so&nbsp;we&nbsp;can&nbsp;use&nbsp;the&nbsp;`unknown`&nbsp;type.

**Comment by armanio123** [comment]
@forivall @ExE-Boss @mdouglass Seems like despite the `commandDir` comment, this PR is ready to be merged. Let me know if this is the case and I can help you with that.

**Comment by forivall** [comment]
@armanio123 yes, it's ready to merge.

**Pull request merged**
