### PR TITLE
Material ui was missing proper support for <List>

### PR DESCRIPTION
**Pull request by Reggino**

### CODE REVIEW

**Comment by samwalshnz** [comment]
Hi @Reggino. I don't think that `ListProps` should extend `PaperProps` as the material-ui source doesn't show any use of the Paper component. Have you added this just so that you can use the `className` prop? If so, perhaps there's a better way to do this that doesn't automatically inherit all of `PaperProps` props?

See the List component, and notice how there is no use of Paper. https://github.com/mui-org/material-ui/blob/v0.x/src/List/List.js

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes based on @samwalshnz's comments, so that @typescript-bot will be aware of the PR's state.

@Reggino, can you discuss with @samwalshnz to find the right change?

**Comment by Reggino** [comment]
@samwalshnz Thanks for the review, sorry for the late reply.

I think you're right. I was set on the wrong foot by comments in the existing definitions. I'll revise the PR

**Comment by Reggino** [comment]
@samwalshnz @sandersn I've updated the PR . 

Based on reading the source code, _any_ property will be passed down to the List-component, (effectively a <div>). This change will allow using these HTML-properties.

**Comment by sandersn** [comment]
(I'll give @samwalshnz a day or two to take another look.)

**Comment by samwalshnz** [comment]
Very sorry for the delay - I was involved in a very intense 'sprint' this week and had no spare time. It looks good to me.

**Review by samwalshnz — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Pull request merged**
