### PR TITLE
[spotify-web-playback-sdk] rename Player class.

### PR DESCRIPTION
**Pull request by y-hiraoka**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.spotify.com/documentation/web-playback-sdk/reference/#api-reference
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by mraerino — COMMENTED** [review]
can you provide some reasoning around this change?
why is it needed? did something change in the SDK that made these types apply wrongly?
if so, please provide a test case that covers the usage pattern that requires this change.

**Comment by y-hiraoka** [comment]
In the current version, we can write `new Spotify.SpotifyPlayer` without compile error in an editor like VSCode.
```ts
const player = new Spotify.SpotifyPlayer( { /*...*/ } );
```

However, the `Spotify.SpotifyPlayer` class is undefined in the browser that loads the SDK.
image

That's the reason for this pull-request.

As for the test code, I don't know where to change it. Because the test code already uses "Spotify.Player" instead of "Spotify.SpotifyPlayer".

**Review by mraerino — APPROVED** [review]
good point and makes sense to me. thanks for explaining!

**Comment by y-hiraoka** [comment]
I'm so sorry.
I made a mistake and committed to my master branch while  this pull-request was being submitted.

**Comment by y-hiraoka** [comment]
I'm going to close this pull request and recreate it.

**Comment by y-hiraoka** [comment]
@mraerino Please check the pull-request: #52520

**Pull request closed without merging**
