### PR TITLE
vis: Fix lint

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adripanico** [comment]
👎

**Comment by andy-ms** [comment]
@adripanico This PR changes code like:
```ts
/**
 * @export
 * @interface IViewPortOptions
 */
export interface ViewPortOptions {
```
to just:
```ts
export interface ViewPortOptions
```

Why shouldn't we make such a change? The existing jsdoc is not only redundant but wrong as the interface has since been renamed.

**Comment by adripanico** [comment]
I agree those are redundant, but I don't see that as critical as to launch a PR only changing code comments.

Now, what do you mean with "as the interface has since been renamed"? Maybe I skipped something.

**Comment by andy-ms** [comment]
`IViewPortOptions` vs `ViewPortOptions`

**Comment by adripanico** [comment]
I see. Well then, you win :)

**Pull request merged**
