### PR TITLE
Updated react-select root type to enable typings for custom input types

### PR DESCRIPTION
**Pull request by lexwebb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/JedWatson/react-select/blob/8fa6c0f01416b923d2c7a6f31ee687b6248fcd71/packages/react-select/src/Select.js#L1447

### CODE REVIEW

**Comment by lexwebb** [comment]
For more context please see the following issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42074

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
This is a popular package and we want someone from author to review this.

**Comment by lexwebb** [comment]
If anyone who has the ability to review this would like to comment that would be lovely. As far as I can see there are no actual requested changes?

**Review by Methuselah96 — APPROVED** [review]

**Comment by Methuselah96** [comment]
@lexwebb I guess open a new PR and I'll approve it?

**Comment by VanTanev** [comment]
This is something that's definitely worth texploring. @lexwebb, do you intend to open a new PR for this?

**Comment by lexwebb** [comment]
@VanTanev I've since moved on from this problem, but if its still an issue i can spend some time this weekend and get a new one up

**Comment by VanTanev** [comment]
@lexwebb I can't rightly ask that of you. If you have the time and desire, great, but if not let me know and I'll work on it myself.

**Pull request closed without merging**
