### PR TITLE
when.js - Add definition with tests for spread

### PR DESCRIPTION
**Pull request by mnahkies**

### CODE REVIEW

**Comment by vvakame** [comment]
*when/when.d.ts*

to authors(@derekcicerone @Nemo157). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by derekcicerone** [comment]
Sorry, the spread functionality is new to me so I'm not entirely sure I understand it. The definition looks reasonable to me but I just can't 100% confirm its correct.

**Comment by vvakame** [comment]
@derekcicerone okey! thanks.
@Nemo157 is there anything?

**Comment by Nemo157** [comment]
Sorry about the delay. @vvakame it looks good enough, I don't think it's possible to fully support `spread` in TypeScript's type system. :+1:

**Comment by vvakame** [comment]
@Nemo157 thanks!
@derekcicerone thanks mate!

**Pull request merged**
