### PR TITLE
Update to TS v2.0.3

### PR DESCRIPTION
**Pull request by microshine**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by microshine** [comment]
@mhegazy sorry for disturbing you. I want to update `graphene-pk11` d.ts file. I want to use TS v2.0.3. But Travis-CLI throw error for updated file. How can I resolve this problem?

**Comment by mhegazy** [comment]
Can you move this PR to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0. master branch is still on TS 1.8.

**Comment by mhegazy** [comment]
also @types publishes from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0 branch.

**Comment by minestarks** [comment]
Thanks for your contribution @microshine .  I'm closing out this PR as it's been untouched for a while, and is better suited for the types-2.0 branch as mhegazy said.

**Pull request closed without merging**
