### PR TITLE
[geojson] allow any Object as Feature property not just empty one

### PR DESCRIPTION
**Pull request by tylkomat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
`{}` is not the type of empty objects, it is the type of anything except `null` or `undefined`.
If you want to be able to have a more specific type for `properties`, you could make `Feature` generic in that too as was done for `geometry`. As in:
```ts
export interface Feature<T extends GeometryObject, Props = {}> extends GeoJsonObject {
    type: 'Feature';
    geometry: T;
    properties: Props | null;
    id?: string;
}
```
This uses a TypeScript 2.3 feature so you would need to add a `// TypeScript Version: 2.3` comment on line 5.

**Comment by tylkomat** [comment]
> {} is not the type of empty objects, it is the type of anything except null or undefined.

That might be true, unless you don't access that object. If you try to access any property on that object the linter complains that that property does not exist. With the proposed change it does not.

**Comment by andy-ms** [comment]
That's because when an object is stored as `{}`, the type checker doesn't know what properties it has -- so it errs on the side of caution.
If you add a string indexer it will allow you to access any property, but this is obviously unsafe. A better solution is to allow people to specify what properties they will have.

**Comment by tylkomat** [comment]
I see.

**Pull request closed without merging**
