### PR TITLE
Add typings for Chromecast CAF Sender API

### PR DESCRIPTION
**Pull request by samuelmaddock**
This adds types for the `cast.framework` namespace provided by the [Chromecast Application Framework](https://developers.google.com/cast/docs/caf_receiver_overview) Sender API. There is no associated NPM package so the name 'chromecast-caf-sender' was chosen instead.

Type dependencies: chrome (depends on changes in #26037)
For the dependency on `chrome/chrome-cast.d.ts` to work, I had to move the file for CI to build successfully in c1fe29f.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by samuelmaddock** [comment]
If anyone is able to help, I'm not sure how to get around this error that CI is throwing
```
ERROR: 8:23    expect  TypeScript@next compile error: 
Cannot find type definition file for 'chrome/chrome-cast'.
```
These type definitions depend on typings in `chrome-cast.d.ts` from `@types/chrome`. The reference I'm using works locally in my own codebase.

**Comment by craigrbruce** [comment]
Hi. Just a quick question: Are these types intended for the chromecast _**sender**_ framework? If so, I would suggest saying so in the title as there are 2 distinct chromecast SDKs (each with different versions: 
* Sender 
* Receiver
I raised this as I have just submitted a PR for the chromecast CAF receiver framework.

Thanks

**Comment by samuelmaddock** [comment]
@craigrbruce Thanks for the heads up. I've changed these types to compliment yours with the name 'chromecast-caf-sender'.

**Comment by craigrbruce** [comment]
@samuelmaddock .. thanks, that's great! would be awesome to have these available in tandem, as we will be using your typings soon 😄

**Pull request merged**
