### PR TITLE
[react-native] FormData is a class

### PR DESCRIPTION
**Pull request by danilobuerger**
See https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js#L49

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js#L49
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by danilobuerger** [comment]
Failing tests seem to be unrelated to this PR.

**Comment by alloy** [comment]
@huhuanming @iRoachie @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk This is imo small enough to merge without a test right now, but for the future I’d love to hear all your thoughts if you agree or disagree.

**Comment by alloy** [comment]
Thanks @danilobuerger!

**Comment by iRoachie** [comment]
Yea no problem. Fine with me

**Pull request merged**
