### PR TITLE
[@types/tabulator-tables] Remove types for table constructor arguments that were moved to event callbacks in tabulator-tables 5.0

### PR DESCRIPTION
**Pull request by awesomund**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://tabulator.info/docs/5.0/upgrade#callbacks
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by awesomund** [comment]
Hi. Just commenting to give some extra context.

After upgrading from tabulator-tables 4 to 5, i noticed that adding e.g. the `dataChanged` callback as an option to the constuctor did not actually work. I had to add the event listener for my callback to actually get called. I noticed this was also the case with several other callback options, see [https://tabulator.info/docs/5.0/upgrade#callbacks](https://tabulator.info/docs/5.0/upgrade#callbacks).

I hope I'm not jumping the gun and missing something here, but it seems like there were some old table constructor options that should be removed to reflect the changes from v4 to v5.

**Review by mike-lischke — APPROVED** [review]
Good to see someone takes care for removed stuff, which is usually more difficult to track than added functionality.

I tested with some of the cell events in the `Options` member of the constructor and got `Invalid table constructor option: cellClick` etc. which shows me this patch is correct.

**Comment by awesomund** [comment]
Ready to merge

**Comment by mike-lischke** [comment]
About versioning: the version in the type definition should be in sync with that of the library, even if it will not reflect further patches (they are still for that particular library version).

I'm not sure if type definitions even *can* use semantic versioning at all.

**Comment by awesomund** [comment]
@mike-lischke thanks for clarifying!

**Comment by awesomund** [comment]
@mike-lischke @Jojoshua it seems the build broke after merging this (even with all checks passed), and it seems the latest version of `@types/tabulator-tables` (5.5.5) does not actually contain the changes. Seems it's also no longer on npm.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a323e5f61254e5f2b304569d89ffde3e11c62211

Any tips on how to proceed with this?

**Comment by mike-lischke** [comment]
5.5.5 is not the latest version, check https://www.npmjs.com/package/@types/tabulator-tables (5.5.6, updated today).

And which build do you refer to?

**Comment by awesomund** [comment]
My mistake! I didnt see 5.5.6 was the latest. I saw some of the checks were failing on the merge commit, so I wondered if there was a problem. Sorry for the confusion.

**Pull request merged**
