### PR TITLE
D3 array iterable

### PR DESCRIPTION
**Pull request by Ledragon**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [2.0.0](https://github.com/d3/d3-array/releases/tag/v2.0.0)
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Should resolve issue #32162 and problems with PR #32528

### CODE REVIEW

**Comment by Ledragon** [comment]
cc @denisname @gustavderdrache @tomwanzek

**Comment by denisname** [comment]
Will check it...
You can remove all `@deprecated` in v2.

**Comment by Ledragon** [comment]
Juste removed `@deprecated` methods; still remains the mystery of the types at line 611 in  TS 3.3

**Comment by Ledragon** [comment]
If this can wait til @denisname or @gustavderdrache reviews it, I would prefer

**Comment by Ledragon** [comment]
If possible for you, then yes, but I can understand you do not wish to keep PR open for too long

**Comment by denisname** [comment]
Got some work but I check it this week, promise.

**Comment by Ledragon** [comment]
@denisname any update? or should we proceed as is?

**Comment by Ledragon** [comment]
To anyone in this thread, how do we go from here? Shall we merge as is?

**Pull request merged**
