### PR TITLE
[react-redux] Add ref and children props to Connected Components

### PR DESCRIPTION
**Pull request by EvanCahill**
Issue:
Connected components should be able to accept refs and children, but with the current definition both do not exist in the connect components' props.

Fixing the types to accept `children` is done by adding an optional `children` property to all connected components. 

The fix for `ref` requires some additional logic since not all wrapped components can accept refs and those that can can take different types of refs:
- Functional components cannot take any refs. This is currently working as expected.
- Functional components that are wrapped with React.forwardRef can accept all ref types except string refs. This is also working as expected since the wrapped component is of type FowardRefExoticComponent which already has `ref` in its prop types.
- Class components can take all ref types including string types. This does not work with the current definitions and requires us to explicitly add `ref` to the components prop types.

Considerations:
`connect()` require the `forwardRef` option to be passed in order to forward the ref to the wrapped component [2], but the typings in this PR will still expose the `ref` prop on the connected component regardless. This is actually existing behavior for function component using `React.forwardRef` so no attempt was made to change the type based on the option value. Additionally while it might be possible to do with some overloads on connect, it would be a breaking change. 

PR Template:

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
[1]https://reactjs.org/docs/glossary.html#refs
[2]https://react-redux.js.org/api/connect#forwardref-boolean

### CODE REVIEW

**Comment by kazuma1989** [comment]
Related to #42537? @OliverJAsh gives advice that you have to define explicit `children` prop.

**Comment by EvanCahill** [comment]
For functional components I would agree that they need to explicitly specify them but for class components the react typings continue to internally expose children on this.props. If people are in agreement I can update the changes to only add children when connecting a class component. If not I would still like the ref changes to go through and will split the children changes into a separate PR.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Requesting changes per the above two comments

**Comment by EvanCahill** [comment]
I have reverted the changes for adding children props and will open a separate PR to only add them for class based components. Thanks for the reminder typescript-bot! 😄

**Review by weswigham — APPROVED** [review]

**Pull request merged**
