### PR TITLE
Fix the signature for `logInWith` in types for @types/parse

### PR DESCRIPTION
**Pull request by kulshekhar**
Also brings it in line with the rest of the related method signatures

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://parseplatform.org/Parse-SDK-JS/api/2.9.0/Parse.User.html#.logInWith

### CODE REVIEW

**Review by JeffGuKang — APPROVED** [review]

**Review by rdhelms — CHANGES_REQUESTED** [review]
If you want this change to take effect for TS 3.7+, it will also need to be done here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parse/ts3.7/index.d.ts#L869

Also, this isn't a huge deal but it would be awesome if you could add a test case for this method passing a type parameter. Somewhere near this existing test (and in the non-ts3.7 test file):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parse/ts3.7/parse-tests.ts#L1686

**Review by yagotome — APPROVED** [review]
LGTM

**Comment by kulshekhar** [comment]
@rdhelms I've updated the other file as well. 

To add the test, I tried cloning the repo a couple of times but my internet connection (on mobile) gave out so I can't do that for now!

**Review by rdhelms — APPROVED** [review]

**Comment by rdhelms** [comment]
@kulshekhar No worries - that test case really isn't that crucial. It would be nice to have at some point, but I think it's better to go ahead and get this fixed.

**Pull request merged**
