### PR TITLE
[react-intl 2.0.0] Definition for react-intl 2.0.0 (#6518)

### PR DESCRIPTION
**Pull request by cdroulers**
I've got most things figured out. I'm not sure about intlShape. Would love feedback from anyone that knows more react / react-intl!

@bgrieder Have you followed the development of v2.0.0 of react-intl?

### CODE REVIEW

**Comment by cdroulers** [comment]
fixes #6518

**Comment by drinchev** [comment]
Yep I think you are right about the props and `intlShape`, since types are checked by TypeScript, not by React internally.

I checked [the source](https://github.com/yahoo/react-intl/blob/master/src/inject.js) and it looks that `propTypes` are not considered when injecting.

Sorry for that.

`defineMessages` now works proper and :+1: from me for the pull request ;) 

Thank you!

**Comment by vvakame** [comment]
*react-intl/react-intl.d.ts*

to author(@bgrieder). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by bgrieder** [comment]
Sorry I did no jump on it earlier and thank you for working on this.

One minor thing ( I made this mistake with 1.2.0 too ): to make de definitions available as an Internal Ambient Module too  - if that is of any use - , the `module `ReactIntl` should be extracted out the `react-intll` external module declaration and then re-imported into it i.e.

    declare module ReactIntl {
         import React = __React;
         ....
     }

     declare "react-intl" {
         export = ReactIntl     
    }


An example of this pattern is `react-router.d.ts`

**Comment by cdroulers** [comment]
@bgrieder Thanks for the tip, I just pushed the changes.

Is it generally ok to push stuff like the `tsconfig.json` and the `.vscode` folder or should I remove them and rebase before it's merged?

Also, for each of the languages (as seen at the end of file), I could generate all the modules from the locale list in the actual react-intl package, or I could give an interface to allow declaring it in client projects instead, since the list is pretty extensive!

**Comment by bgrieder** [comment]
@cdroulers 
Do not push anything but the declaration, the tests and a tscparams file.
For the list of languages, I would just give an interface
Aside from this, :+1:

**Comment by cdroulers** [comment]
@bgrieder Perfect. I'll rebase and push sometime today, thanks!

**Comment by cdroulers** [comment]
@bgrieder I cleaned everything and rebased!

**Comment by bgrieder** [comment]
:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
