### PR TITLE
SwipeRecognizer extends AttrRecognizer

### PR DESCRIPTION
**Pull request by diontools**
Please review.

### CODE REVIEW

**Comment by vvakame** [comment]
*hammerjs/hammerjs.d.ts*

to authors(@milkisevil @codler). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by codler** [comment]
Ye it seems correct, the documentation says extends also
https://hammerjs.github.io/jsdoc/SwipeRecognizer.html

**Comment by vvakame** [comment]
@codler thanks!
@diontools thanks mate!

**Comment by diontools** [comment]
Thank you so much!

**Pull request merged**
