### PR TITLE
Update firefox-webext-browser, fix spelling typos in comments

### PR DESCRIPTION
**Pull request by beck**
Fixing typo, correct the spelling of words like `additon` (missing 'i') and and `occured` (missing 'r').

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.

Select one of these and delete the others:

Not adding, removing, or changing and functional definitions.

### CODE REVIEW

**Comment by jsmnbom** [comment]
These spellings are directly from Mozilla. Therefore they should be fixed upstream, and will automatically be updated ("automatically" meaning i need to get around to it - been slow lately, but I'll try to do it more often).

**Review by jsmnbom — COMMENTED** [review]
See my comment above. Thanks for the PR, but my recommendation is to close this issue.

**Review by jsmnbom — CHANGES_REQUESTED** [review]
See my comment above. Thanks for the PR, but my recommendation is to close this issue.

**Comment by beck** [comment]
Makes sense.

**Pull request closed without merging**
