### PR TITLE
Add type references to dojo/index.d.ts for individual definition files. Fixes #20089.

### LINKED ISSUE #20089: compiler not picking up type definition unless named index.d.ts
Is this by design?  I have installed `@types/dojo` which includes:

`@types/dojo/index.d.ts`
`@tpes/dojo/dijit.d.ts`

The former works fine, the latter is not picked up by the compiler and I get "TS2307: Cannot find module" errors trying to use dijit typings.  This is with ts version 2.5.2.

### PR DESCRIPTION
**Pull request by navels**
Fixing #20089.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by weswigham** [comment]
@vansimke Would you review this and give feedback? I'm not sure this is the right way to fix this if these references point to definitions for optional extensions.

**Comment by navels** [comment]
FYI I went this route after seeing that a few other types (e.g., meteor) handle it the same way.

**Comment by weswigham** [comment]
@navels provided the files are actually still in the published npm package, the other option is to just let consumers include the files by hand for each extension they have enabled (via a direct triple slash reference of the full path or an explicit inclusion of the full path via include or files). However, if most people have most of the extensions on, then the added convenience of including them all by default can be worth the lower safety (from all the ghost types of things that might not be there). It's likely a judgement call for any package maintainers.

All these type definition files are actually still in the published npm package though, right? If not, then there's likely an issue/feature improvement with the types publisher.

**Comment by vansimke** [comment]
I don't maintain this anymore on Definitely Typed. The [dojo/typings](https://github.com/dojo/typings) repo is the official, maintained version of the TypeScript typings for Dojo 1 now.

**Comment by dgwaldo** [comment]
@vansimke Would it be possible to consider a way to sync from dojo/typings to Definitely-Typed? As far as I can tell dojo/typings doesn't contain the dojox chart typings, but they are contained in this repo here. Is there any effort being made to get the remaining missing dojo typings into the dojo/typings repository. 

I too am using the /// reference syntax to get typings from this library pulled into our app.  Would be nice to have one set of typings with everything.  Also, if you npm install @types/dojo doesn't it reference this repo?

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by sandersn** [comment]
For housekeeping purposes, I'm going to close this PR since it sounds like the discussion for the solution should probably be on dojo/typings, or at least somewhere inside dojo.

**Pull request closed without merging**
