### PR TITLE
Update

### PR DESCRIPTION
**Pull request by lucalaissue**
I **updated** definitions for the new tournament api and Champion Mastery of **Riot Games Api**

### CODE REVIEW

**Comment by ZafixLRP** [comment]
:+1:

**Comment by Xstoudi** [comment]
1. Edit the header to pass the Travis CI test.
2. Change "DTO" by "Dto" to respect the types names.

**Comment by ZafixLRP** [comment]
I modified **DTO** to **Dto** but i don't understand what you mean with "*Edit the header to pass the Travis CI test*"

**Comment by Xstoudi** [comment]
:+1:

**Comment by horiuchi** [comment]
@ZafixLRP Thanks mate!
@Xstoudi Thanks for review!

**Pull request merged**
