### PR TITLE
[raven] fix key substructure

### PR DESCRIPTION
**Pull request by lenovouser**
Fix key substructure

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/getsentry/raven-node/blob/master/lib/client.js>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by scttcper** [comment]
:+1:

**Comment by scttcper** [comment]
@lenovouser do you know if anything needs to change for 2.0 that was released the other day?

**Comment by SimonSchick** [comment]
Question: Why do you not make the PR on the raven repo itself? It has typings.

**Comment by lenovouser** [comment]
@SimonSchick the raven repository doesn't have typings?

There was a PR to get types merged but the maintainers refused:

> While I appreciate the effort that went into this, we're intentionally avoiding having TypeScript typings in raven-node. They're a burden to maintain, people get upset if they don't work, they will be continuously out of date, and there hasn't been enough community push for them. We only support them in raven-js because Angular 2 is an officially supported platform, and it uses TypeScript by default.
> 
> We'd prefer if you consider submitting these to DefinitelyTyped instead.

**(https://github.com/getsentry/raven-node/pull/282)**

**Comment by lenovouser** [comment]
@scttcper yes, changes are needed for `v2.0`. Some stuff was removed. Haven't checked out everything yet though. I guess that should be a different PR?

**Comment by SimonSchick** [comment]
@lenovouser That's a shame, they should just remove them instead.

**Comment by lenovouser** [comment]
@SimonSchick remove them from what? 😄

**Review by scttcper — APPROVED** [review]
👍

**Pull request merged**
