### PR TITLE
[ssh2] add typings for generateKeyPair(sync)?

### PR DESCRIPTION
**Pull request by tristan-f-r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

https://github.com/mscdex/ssh2/blob/a56e70e68efd6a1c7e665c9a473eb68d25571a55/lib/index.js#L36

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68899

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/ssh2/ssh2-tests.ts
1. types/ssh2/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 01f11b118266f7ff2129b460c5586ea6601176e3
</p>

**Review by dhensby — COMMENTED** [review]
It would be good to run the code formatting as requested by the bot.

Also, this appears to be your first contribution to the ssh2 types, so I'm not sure adding you as a code owner is that appropriate. Do you use the lib regularly or have involvement in the development of it to justify adding yourself as a code owner at this point?

**Comment by LeoDog896** [comment]
> Also, this appears to be your first contribution to the ssh2 types, so I'm not sure adding you as a code owner is that appropriate. Do you use the lib regularly or have involvement in the development of it to justify adding yourself as a code owner at this point?

Oh! Didn't realize that the dts authors adds you as a code owner; this is only my second time editing a type on definetlytyped :sweat:.

**Review by dhensby — APPROVED** [review]

**Comment by LeoDog896** [comment]
Ready to merge

**Pull request merged**
