### PR TITLE
[iost-contract] [node] Fixed typo: definnitions => definitions

### PR DESCRIPTION
**Pull request by krizalys**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [NA] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [NA] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [NA] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [NA] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@krizalys 
sorry for the noise in the CI tests (obvioulsy your change should not impact CI results). I've noticed the problem in other PR (and passed the info up).

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@krizalys thx for the correction!

**Review by a-tarasyuk — APPROVED** [review]

**Review by Flarna — APPROVED** [review]

**Review by j-oliveras — APPROVED** [review]

**Review by ExE-Boss — APPROVED** [review]

**Review by galkin — APPROVED** [review]

**Review by monaka — APPROVED** [review]
Nice catch. LGTM.

**Review by r3nya — APPROVED** [review]

**Review by ryanrw — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
LGMT!
Sorry if you waited for me bot!

**Review by ExE-Boss — APPROVED** [review]

**Review by j-oliveras — APPROVED** [review]

**Comment by orta** [comment]
Hah, yeha, easy pickings this one - thanks!

**Pull request merged**
