### PR TITLE
Add CylinderBufferGeometry

### PR DESCRIPTION
**Pull request by alpynv**
- Add CylinderBufferGeometry definition
  https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/CylinderBufferGeometry.js

### CODE REVIEW

**Comment by florentpoujol** [comment]
This is specific to Three r75, so you should change the first line of the file.
Also ideally you should have added your other commit to this PR (so that the Definitely typed team doesn't drown in commits (at least more than it currently do)).

I believe the best course of action would be to actually update as much as possible to r75 in a single PR, like I did for r74.
I suggest that I actually do that this week-end, branching from your "SereznoKot:cylinder-buffer-geometry".

**Comment by SereznoKot** [comment]
Ok, got it!

**Comment by mhegazy** [comment]
@florentpoujol and @SereznoKot should this be merged?

**Comment by florentpoujol** [comment]
No, because these definitions are included in PR #8825, which is already merged.
No more need for this one now.

**Comment by mhegazy** [comment]
thanks for the reply. closing.

**Pull request closed without merging**
