### PR TITLE
[react] add missing html table attributes

### PR DESCRIPTION
**Pull request by tholman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f76f08ac226a313e1f8fdba69818887656d6c644
</p>

**Review by eps1lon — COMMENTED** [review]
Did you check if we have other deprecated attributes here? Did we maybe remove these in the past or discussed it earlier?

**Review by eps1lon — APPROVED** [review]
> All of the attributes on Table are deprecated including the ones currently in the types file.

Gotcha. We'll mark them all as deprecated in a follow-up. Thanks for checking!

**Review by rbuckton — APPROVED** [review]

**Comment by tholman** [comment]
Ready to merge

**Comment by alden-codaio** [comment]
`border` is typed as `border?: number | undefined;` -- Shouldn't this include `string`?

**Comment by tholman** [comment]
> `border` is typed as `border?: number | undefined;` -- Shouldn't this include `string`?

Naw, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#attr-border

**Comment by alden-codaio** [comment]
Oh, interesting! So `cellpadding` can be `5px` but `border` implies pixels so it's just `5`.

HTML is weird sometimes...

Thanks!

**Pull request merged**
