### PR TITLE
update(figlet): v1.5

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- `width` and `whitespaceBreak` options
- version bump
- tests amended
- drop owner (see discussion below)

https://github.com/patorjk/figlet.js/releases/tag/1.5.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
resolved/rebased. Props were added in upstream change.

**Comment by Ailrun** [comment]
TBH, I don't want to manage these type definitions anymore. This one has only one author, so it's not possible to remove that from the file. Is there a way?

**Comment by peterblazejewicz** [comment]
> TBH, I don't want to manage these type definitions anymore. This one has only one author, so it's not possible to remove my name from the file. Is there a way?

Yes, that's completely OK. The package will be marked as 'unowned', but that does not prevent it from being maintained. DT mantainers can always approve any change, I'll remove you from a haeader and you will approve, sounds like a plan?

**Comment by peterblazejewicz** [comment]
@Ailrun done, amended!

**Comment by Ailrun** [comment]
> I'll remove you from a haeader and you will approve, sounds like a plan?
Sounds good.

**Review by Ailrun — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
