### PR TITLE
Deprecate electron

### PR DESCRIPTION
**Pull request by zeke**
As of 1.6.10, `electron` ships with its own typings. See the blog post at https://electron.atom.io/blog/2017/06/01/typescript

This is a followup to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12888

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by yuit** [comment]
@DanielRosenwasser

**Comment by yuit** [comment]
There is this existed PR to do the same thing : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16928.

**Comment by zeke** [comment]
> There is this existed PR to do the same thing

I'm fine with either PR, as they both have the same goal. Feel free to close this and merge the other , or vice-versa.

**Comment by zeke** [comment]
Closing this because https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16928 was merged. 

Thanks, @plantain-00!

**Pull request closed without merging**
