### PR TITLE
[@types/react-native] AccessibilityInfo needs forward port to RN0.60 API

### LINKED ISSUE #1125: Accessibility code needs forward-port to RN60 APIs
There is a related issue in #893 about some deprecated APIs, but more importantly, an API in use now is completely gone from RN59 to RN60 - RN.AccessibilityInfo.fetch()

React-Native added support for more accessibility features, and they broke the API out into multiple feature-specific APIs.

Here's the documentation update https://github.com/facebook/react-native-website/pull/835

The API in use is here: https://github.com/microsoft/reactxp/blob/master/src/native-common/Accessibility.ts#L39

The corresponding API (for screen-reader only, to make ReactXP work with RN60) would be to use [RN.AccessibilityInfo.isScreenReaderEnabled()](https://facebook.github.io/react-native/docs/accessibilityinfo#isscreenreaderenabled) and to register the listener for 'screenReaderChanged' event vs 'changed'

I will propose a PR for that specific change as ReactXP will be a breaking-change anyway so it's okay for it not to work on RN59, but future enhancements should expand the Accessibility to take advantage of the rest of the new features. If that is desired I could propose a second PR that offers complete coverage of the enhanced API though I may need some hand-holding in how to deal with iOS/Android-specific differences as parts of the API are available only on one platform or another

Cross-linking with #1123 for visibility there since I mentioned it prior.

### PR DESCRIPTION
**Pull request by mikehardy**
AccessibilityInfo was expanded between RN59 and RN60 to include lots
of accessibility feature information beyond just screen reader status.

This updates the typings to match the docs: https://facebook.github.io/react-native/docs/accessibilityinfo

I have trouble running both `npm test` and `npm run lint react-native` for some reason, it complains of naming issues, but...I have not created a new package I am just editing an existing one? It definitely works for me in testing though, and is required to fix https://github.com/microsoft/reactxp/issues/1125

The old APIs are deprecated but still exist, so this PR preserves them and just adds the new APIs that should be used going forward

**This is a re-submission of #37486 - for some reason the automatic status there were incorrect and it rendered the PR inactive despite review from @alloy and me submitting a correction based on the review? Seemed like it was good to go, and then...nothing**

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [!] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [!] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/accessibilityinfo
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mikehardy** [comment]
Examining CI failure for 'DefinitelyTyped.BenchmarkPR' it does not appear to be related to this PR:

```

Comparing react-native/v0 because it changed...


No previous benchmark for react-native/v0. Checking out master and running one...
Parsing definitions...
Found 6071 packages.
Parsing in parallel...
Error: Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links
npm ERR! code ENOENT
npm ERR! syscall lchown
npm ERR! path /home/vsts/.npm/_locks/staging-311601e281b44cd9.lock
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lchown '/home/vsts/.npm/_locks/staging-311601e281b44cd9.lock'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by mikehardy** [comment]
Just rebased from master to make sure recent changes still worked well, and force-pushed that back out to my branch. All clean

**Comment by alloy** [comment]
Sorry for the delay, still getting up to speed after vacation.

Thanks, this looks great! 🙌

**Comment by mikehardy** [comment]
I certainly understand - just finished all my summer travel myself and still have a backlog :-). Thanks for the original review on the original PR - definitely made it better, and thanks for merging this. Cheers

**Pull request merged**
