### PR TITLE
[yup]: adds TestContext and originalValue on types

### PR DESCRIPTION
**Pull request by abnersajr**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup/issues/1007
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

**Review by lukaselmer — APPROVED** [review]

**Comment by abnersajr** [comment]
I'm not able to merge it. So if someone could do this. I appreciate it.

**Comment by lekoaf** [comment]
@abnersajr, just make a comment with "Ready to merge" and the bot will merge it for you.

**Review by iansan5653 — APPROVED** [review]

**Comment by iansan5653** [comment]
I don't know if I am able to do this on someone else's PR, but...

**Comment by iansan5653** [comment]
Ready to merge.

**Pull request merged**
