### PR TITLE
Remove @types/naja

### PR DESCRIPTION
**Pull request by rozsival**
Remove [naja](https://github.com/jiripudil/Naja) types as the package includes its own types since `2.0.0`. See [related issue](https://github.com/jiripudil/Naja/issues/23#issuecomment-678624197) for further info.

### CODE REVIEW

**Comment by rozsival** [comment]
@andrewbranch Hey Andrew, could you please give me some tips about failing checks on this PR? I've run all necessary checks locally before submitting the PR, everything was fine. It seems there's an issue with some `react-native` typings, which are not related to any changes I've made. Could it be a CI issue? Thanks a lot!

**Comment by ffflorian** [comment]
@rozsival I think you might need to pull in the latest changes from `master`.

**Comment by rozsival** [comment]
@ffflorian Thanks for the tip! I did that before making my changes in this PR, however, it seems there really was one small change made in `master` before I was able to submit the PR.

**Comment by rozsival** [comment]
@elibarzilay Thank you for reviewing and merging this PR.

**Pull request merged**
