### PR TITLE
[update-notifier] add missing type for shouldNotifyInNpmScript

### PR DESCRIPTION
**Pull request by grinich**
Was added to update-notifier in v2.5.0

https://github.com/yeoman/update-notifier/commit/ac0d3cbf556c7a78f80e9dc91ddfeec46f9a663b

Also increase version number in header to 2.5

### CODE REVIEW

**Comment by grinich** [comment]
Oops forgot to mark it as optional

**Comment by grinich** [comment]
Looks like it passed. @vvakame @nchen63 @bitjson can you take a look?

**Review by bitjson — APPROVED** [review]
Looks good to me 👍

**Comment by grinich** [comment]
🕺

**Pull request merged**
