### PR TITLE
solidity-parser-antlr: improve multiple type definitions

### PR DESCRIPTION
**Pull request by yxliang01**
The type definition for this library is still very incomplete.

-----
Improved the type definition for `SourceUnit`, `ContractDefinition` and `FunctionDefinition`.

-----
The `Visitor`'s return value should really be that `false | any` which is equal to `any`.
See https://github.com/federicobond/solidity-parser-antlr/blob/73c6818452ba2eb50338b6a857acb82e976c34be/src/index.js#L97 . Current master version of `solidity-parser-antlr` only cares whether it's `false`.

### CODE REVIEW

**Comment by LogvinovLeon** [comment]
@yxliang01 Thanks for those changes. I think it would be even more clear if we define that type as `false | any`. I understand that it's essentially the same as `any`, but I think it's more accurate from the semantics standpoint and more readable and understandable.

**Comment by yxliang01** [comment]
Yep @LogvinovLeon  . I was actually thinking between `false | any` and `any`. That's why I mentioned both. :)
Addressed your comment at commit 2e8330c53ab072972a13a27b2693fbc0f8fd47df .

**Comment by yxliang01** [comment]
Oops, no @LogvinovLeon  They have enabled the rule `no-any-union`. What do you think?

**Comment by LogvinovLeon** [comment]
In that case - Let's remove it. I'll approve this PR now.

**Review by LogvinovLeon — APPROVED** [review]

**Comment by yxliang01** [comment]
Okay this is ready to be merged.

**Pull request merged**
