### PR TITLE
Johnny-Five: Basic i2c commands

### PR DESCRIPTION
**Pull request by scottgonzalez**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/johnny-five/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f0a45daa4b58d858b06ce1212edd6e0510d053b2
</p>

**Comment by ScreamZ** [comment]
I would like to, but i Don't see the button anymore

**Comment by scottgonzalez** [comment]
@ScreamZ any luck now?

**Review by ScreamZ — APPROVED** [review]

**Comment by ScreamZ** [comment]
The review button is fucking hidden, I tricked it. Should be fine

**Comment by scottgonzalez** [comment]
Ready to merge

**Pull request merged**
