### PR TITLE
Remove moment-timezone from DefinitelyTyped

### PR DESCRIPTION
**Pull request by chivesrs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

See https://github.com/moment/moment-timezone/blob/develop/index.d.ts for the library owned typings. I believe they just copied what was in this repo and moved it there, so we should delete what's in DT to not duplicate, and to let the library owners own the typings as well.

### CODE REVIEW

**Comment by chivesrs** [comment]
It looks like `@types/moment-strftime2` and `@types/react-date-range` depend on this.

What do you reckon is the best way to solve this issue? I don't want to break those typings, but at the same time, I would rather break them rather than have them depend on something that's deprecated/outdated/unmaintained.

**Comment by chivesrs** [comment]
@DanielRosenwasser Do you have any suggestions on this?

Re moment-strftime2, that package is deprecated per https://www.npmjs.com/package/moment-strftime2
And react-date-range isn't too many users per https://www.npmjs.com/package/react-date-range

So my approach would be merge this, and then remove @types/moment-strftime2, and fix @types/react-date-range as best as I can

Thoughts?

**Comment by pristinesource** [comment]
@chivesrs  You will want to move the current version to a "history" version and have those other packages point to the "historical" version, and then you will be able to remove the current version.  https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package

**Comment by chivesrs** [comment]
@pristinesource That doc seems to imply that I want to keep supporting moment-timezone typings in this repo, where in fact I want it removed.

I guess the way I can go about it is to call the package `deprecated` and I think that satisfies everyone. I'll put a comment at the top of the index.d.ts saying where to go for the non deprecated typings.

**Comment by pristinesource** [comment]
> @pristinesource That doc seems to imply that I want to keep supporting moment-timezone typings in this repo, where in fact I want it removed.
> 
> I guess the way I can go about it is to call the package `deprecated` and I think that satisfies everyone. I'll put a comment at the top of the index.d.ts saying where to go for the non deprecated typings.

We don't want to remove it completely as it will need to be used by anyone using a moment-timezone version before the type definition was added.  This would break countless projects everywhere as they would not be able to access this version of the type definition as a project dependency (my company's project included).  This is why the best plan of action is to set it to a historical version that can still be used and referenced and the new/current version would be empty, and maybe with something stating that it is merely a placeholder for use  with older versions of moment-timezone and that for newer/current versions of moment-timezone, the type definition file is included with it.

**Comment by chivesrs** [comment]
I don't see how it'd break you if the historical typings are still on NPM?
For example https://www.npmjs.com/package/@types/moment

**Comment by pristinesource** [comment]
> I don't see how it'd break you if the historical typings are still on NPM?
> For example https://www.npmjs.com/package/@types/moment

@chivesrs  Indeed, you are correct! 😉

**Comment by chivesrs** [comment]
Made some decent progress per https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package.

Currently waiting on https://github.com/microsoft/DefinitelyTyped-tools/pull/79 and then I'll force a CI run here once that's merged, and go from there.

**Comment by chivesrs** [comment]
Yay the CI passes! Bit of a run around in different repos, but it all works now.

**Comment by DevsAnon** [comment]
In relation to react-date-range
Changes Approved

**Review by andrewbranch — APPROVED** [review]

**Comment by chivesrs** [comment]
Ready to merge

**Pull request merged**
