### PR TITLE
ngCordova plugins: ActionSheet, Badge, File, FileTransfer

### PR DESCRIPTION
**Pull request by pmccloghrylaing**

### CODE REVIEW

**Comment by ksachdeva** [comment]
looks ok.

**Comment by pmccloghrylaing** [comment]
A couple of small fixes - allowed `Blob` for `$cordovaFile.write*` and `$cordovaFile.readAsArrayBuffer` actually returns an `ArrayBuffer`.

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by pmccloghrylaing** [comment]
Conflicts resolved.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
