### PR TITLE
Node: Update and add missing options for util#inspect

### PR DESCRIPTION
**Pull request by bcherny**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/util.html#util_util_inspect_object_options
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
#16692 should be fixed now, please rebase against master.

**Comment by mhegazy** [comment]
never mind rebasing, just reran the tests, now there are relevant lint failures. @bcherny please take a look.

**Comment by bcherny** [comment]
@mhegazy I must be missing it - the lint errors seem to be for other packages, not for my changes.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
