### PR TITLE
[i18n] Add missing configuration options

### LINKED ISSUE #50977: i18n - retryInDefaultLocale
Ad retryInDefaultLocale to @types/i18n please. Thx Tom

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #50977

Documentation: https://github.com/mashpie/i18n-node#list-of-all-configuration-options

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by martin-badin** [comment]
@peterblazejewicz Hi. Could you please review?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thx!

btw:
Oh, why this `4.1` header is there for a Node package that supports older runtime features?:
```json
 "engines": {
    "node": ">=0.10.0"
  },
```

**Comment by martin-badin** [comment]
@peterblazejewicz I am not sure.

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
