### PR TITLE
Add $mdTheming service to angular-material

### PR DESCRIPTION
**Pull request by mtraynham**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://material.angularjs.org/latest/api/service/$mdTheming
https://github.com/angular/material/issues/2965
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mtraynham** [comment]
```sh
Testing angular-material
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js
	Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/angular-material/index.d.ts
ERROR: 7:26 no-implicit-dependencies Module 'angular' is not listed as dependency in package.json
```
Not entirely sure why that failed.  The index file [already imports angular](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular-material/index.d.ts#L7).  Is the import broken here?

**Comment by andy-ms** [comment]
@mtrayham Sorry, this looks like a new lint rule. I'll disable it since we use path mapping on DT.

**Comment by mtraynham** [comment]
No worries @andy-ms.  Thanks for help!

**Comment by geertjansen** [comment]
LGTM

**Pull request merged**
