### PR TITLE
[react-datepicker] fix missing renderMonthContent type

### PR DESCRIPTION
**Pull request by DavidShefcik**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Hacker0x01/react-datepicker/blob/main/src/month.jsx#L628

### CODE REVIEW

**Comment by inomn** [comment]
Hi @DavidShefcik , thank you! I think would be good to update the package version to match the latest react-datepicker version since it's a new prop introduced only 2 weeks ago.

**Comment by DavidShefcik** [comment]
@inomn Just updated the version number!

**Review by 1pete — APPROVED** [review]

**Comment by DavidShefcik** [comment]
Ready to merge!

**Comment by DavidShefcik** [comment]
Ready to merge

**Pull request merged**
