### PR TITLE
Foundation sites

### PR DESCRIPTION
**Pull request by samvloeberghs**

### CODE REVIEW

**Comment by samvloeberghs** [comment]
@borisyankov , what does this fail message imply? I've just renamed foundation.d.ts to foundation-sites.d.ts because it had a conflict with foundation 5.

**Comment by horiuchi** [comment]
@samvloeberghs Why you rename the definition file?
Please read the contribution guide: http://definitelytyped.org/guides/contributing.html#naming-the-file

---
It looks like the original name is correct to me.
Is this `npm` library the defined target? https://www.npmjs.com/package/foundation

**Comment by samvloeberghs** [comment]
@horiuchi 
because it has a naming conflict with foundation 5.
This is Foundation 6.1, which is named "foundation-sites"

no the npm library is:
https://www.npmjs.com/package/foundation-sites

**Comment by horiuchi** [comment]
@samvloeberghs OK, I see :+1: 
The rest task is to remove changing to `CONTRIBUTORS.md`.
This file is auto-generated.

**Comment by samvloeberghs** [comment]
Funny, I did not change that.
Isn't this updated automatically when you/I/whomever runs 'npm test' in the project?

**Comment by horiuchi** [comment]
@samvloeberghs Thanks mate!
@vvakame When execute the auto-generate script?

**Comment by horiuchi** [comment]
done to update `CONTRIBUTORS.md` from #7521

**Pull request merged**
