### PR TITLE
add interact method

### PR DESCRIPTION
**Pull request by MoLow**
this makes it much easy to `spyOn(interact, 'interact');` using Jasmine. the function exists

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
image

❓

**Comment by DanielRosenwasser** [comment]
Ah, I just re-read

> this makes it much easy to `spyOn(interact, 'interact');` using Jasmine. the function exists

It seems like you should be augmenting the type for your project rather than asserting that it already exists for everyone.

**Comment by MoLow** [comment]
Hi. this dose work for me:
image

anyway, I have found a local solution in my project.
BTW. @DanielRosenwasser we ate lunch together at AngularUp, in TLV, nice talking again :)

**Comment by DanielRosenwasser** [comment]
Hey @MoLow, I remember speaking with you! Glad to find you on GitHub 😄 

I can't find any place in the source itself that this occurs, and the project's webpage doesn't seem have this working from the console (http://interactjs.io/). Perhaps there's a version mismatch?

Maybe @taye can weigh in here - is `interact.interact` a valid property?

**Comment by MoLow** [comment]
@DanielRosenwasser  I ended up writing `spyOn(interact.prototype, 'constructor')`, so im Ok with closing this PR.

**Comment by thasner** [comment]
It seems like the fact that `interact()` calls `interact.interact` is an implementation detail, and shouldn't be exposed in the typings. @MoLow do you agree with that?

**Comment by MoLow** [comment]
@thasner Sure

**Pull request closed without merging**
