### PR TITLE
Make React's SyntheticEvent.currentTarget generic over T again

### PR DESCRIPTION
**Pull request by joshaber**
This change was added in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/084926e23accedcbf700bf480e38abdeabcd971e but then reverted in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5607f54defce88bc52a0440288f434cafffdb5ce. The revert _looks_ like an accident to me, as it's a merge coming in from master vs. a purposeful change. Maybe it got accidentally stepped on in resolving a conflict?

If `target` should no longer be the intersection of `EventTarget` and `T`, then there's not much point to `SyntheticEvent` being generic over `T` 😄

### CODE REVIEW

**Comment by joshaber** [comment]
The CI failures seem unrelated to my change.

**Comment by vvakame** [comment]
related? #10811

**Comment by joshaber** [comment]
@vvakame Ah yeah, good catch 👍 Switched to make `currentTarget` generic over `T` instead of `target`.

**Comment by joshaber** [comment]
This is green now 🎉

**Pull request merged**
