### PR TITLE
Update redux-storage-decorator-filter to 1.1.6

### PR DESCRIPTION
**Pull request by duydao**
Improvement to existing type definition.
https://github.com/michaelcontento/redux-storage-decorator-filter/blob/master/src/index.js

Added support for blacklist.

### CODE REVIEW

**Comment by duydao** [comment]
@asvetliakov do you have an update on this pull request?

**Comment by asvetliakov** [comment]
👍

**Comment by duydao** [comment]
@asvetliakov Thanks mate!

**Comment by duydao** [comment]
@vvakame Any chance you could merge this pull request in the near future? thanks!

**Pull request merged**
