### PR TITLE
angular.IRoute.controller can be defined as array

### PR DESCRIPTION
**Pull request by alextkachman**
This is minor change. The point is that controller in definition of route can be not only string or function but also whole injectable array

### CODE REVIEW

**Comment by park9140** [comment]
@alextkachman is it an array of anything or specifically an 'Array<string|Function>'

**Comment by alextkachman** [comment]
It's array where all elements but last are strings and last one is Function. Angular convention for function with injected parameters. I don't think it's practical to specialize type here more that just any[]

**Comment by park9140** [comment]
@alextkachman still seems like the limit is 
```typescript
Array<string|Function>
```
But I guess if we don't want to change all the instances in the angular definitions we shouldn't really change this one.  Can we at least make a local Type definition for DependencyAnnotatedConstructor so that it is clear what the ```Array<any>```  represents?

**Comment by alextkachman** [comment]
Please have a look now. 
After doing this I start thinking that changing of definition of IProvideService and Module might make sense. What do you think?

**Comment by alextkachman** [comment]
@park9140 do you have any more input or maybe it could be merged?

**Comment by vvakame** [comment]
LGTM. @park9140 can i merge this PR?

**Comment by park9140** [comment]
:shipit:

**Comment by park9140** [comment]
:+1:

**Pull request merged**
