### PR TITLE
[node/readline] Expose 'line' & 'cursor' properties

### PR DESCRIPTION
**Pull request by Js-Brecht**
The current "line" and "cursor" states are often necessary when developing applications that use readline for prompts.

While the properties should be accessible, they are also meant to be used internally, and modifying them could result in unexpected behavior when drawing, which is why they are `readonly`.  They **_can_** be modified safely, but `cursor` would have to be modified in tandem with `line`.  IMO, it's better to make them `readonly`, so overwriting them will be an explicit effort; that way whoever does it is fully aware of what they are doing.

See https://github.com/nodejs/node/issues/30347

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

---

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/nodejs/node/issues/30347>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Flarna** [comment]
It's usually not needed to updated typings for EOL versions of node (9, 11).

**Review by galkin — APPROVED** [review]
Looks good for me

**Comment by Js-Brecht** [comment]
@Flarna Is it EOL for 9-11 already?  I just figured that since they are valid properties for those versions as well, that they should be typed.  Or are you saying they are EOL for `@types/node` (I was thinking node itself), so those changes won't get published anyway?

---

Anybody have an idea why the `DefinitelyTyped.BenchmarkPR` is failing?  It appears to be an issue with the v12 changes, but I'm not sure if I actually have any control over the issue: not being able to find a lock file seems like an internal problem 😕 
```
2019-11-20T00:21:57.3155921Z Comparing node/v12 because it changed...
2019-11-20T00:21:57.3157374Z 
2019-11-20T00:21:57.3157893Z 
2019-11-20T00:21:57.6322302Z No comparable benchmark for node/v12. Checking out master and running one...
2019-11-20T00:21:58.3418386Z Parsing definitions...
2019-11-20T00:21:58.5600708Z Found 6222 packages.
2019-11-20T00:21:58.5602296Z Parsing in parallel...
2019-11-20T00:28:53.0657250Z 0.7% done...
2019-11-20T00:33:53.6105395Z 1.3% done...
2019-11-20T00:38:54.4625154Z 2.0% done...
2019-11-20T00:43:54.6796649Z 2.7% done...
2019-11-20T00:48:55.2633369Z 3.4% done...
2019-11-20T00:53:56.0081457Z 4.1% done...
2019-11-20T00:58:56.3525277Z 4.8% done...
2019-11-20T01:03:57.2109218Z 5.5% done...
2019-11-20T01:08:58.1184355Z 6.2% done...
2019-11-20T01:13:58.4209360Z 6.8% done...
2019-11-20T01:18:58.8171726Z 7.5% done...
2019-11-20T01:24:00.1149405Z Parsing definitions...
2019-11-20T01:24:00.3571551Z Found 6222 packages.
2019-11-20T01:24:00.3572840Z Parsing in parallel...
2019-11-20T01:25:28.3442045Z Error: Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links
2019-11-20T01:25:28.3443372Z npm ERR! code ENOENT
2019-11-20T01:25:28.3444274Z npm ERR! syscall lchown
2019-11-20T01:25:28.3445186Z npm ERR! path /home/vsts/.npm/_locks/staging-4f31c809bbe9df41.lock
2019-11-20T01:25:28.3445966Z npm ERR! errno -2
2019-11-20T01:25:28.3446549Z npm ERR! enoent ENOENT: no such file or directory, lchown '/home/vsts/.npm/_locks/staging-4f31c809bbe9df41.lock'
2019-11-20T01:25:28.3446808Z npm ERR! enoent This is related to npm not being able to find a file.
2019-11-20T01:25:28.3446987Z npm ERR! enoent 
```

It was successful at one point.  I recall it failed after I originally submitted the PR, then I added the v11 test, and it was successful when it ran again.  I pushed the v9 change, and it failed again, the same way as the first time.  These changes are so innocuous, I don't know what is breaking it.

**Comment by SimonSchick** [comment]
@Js-Brecht We avoid updating EOL versions as the node team itself doesn't support them either, 10 is LTS (odd vs. even).
The install is a known issue https://github.com/microsoft/types-publisher/issues/707

**Comment by Js-Brecht** [comment]
@SimonSchick Ahh, I see.  I should have looked at https://nodejs.org/en/about/releases/.  I will revert the changes to v9 and v11

**Comment by SimonSchick** [comment]
@JS-Brecht so I can see these properties currently exist but are not documented.
The node discussion seems to imply they'd rather expose the getCursorPos method rather than making those properties public.
Can you elaborate?

**Comment by Js-Brecht** [comment]
@SimonSchick Sure.  The plan was to expose `line`, `cursor` _and_ `getCursorPos`.  They mentioned that the `line` and `cursor` properties were just never documented (https://github.com/nodejs/node/issues/30347#issuecomment-552824045), but didn't seem to care about them being exposed. They've asked that I also submit a PR documenting them (https://github.com/nodejs/node/issues/30347#issuecomment-555776017).  That will be the next one I open for this particular endeavor.

I could ask for them to explicitly approve making these two properties public.

`getCursorPos` is going to be a separate PR, since it's going to involve promoting `_getCursorPos()` to public API.  That has to be implemented, and approved by the node team before I write types for it.

**Comment by Js-Brecht** [comment]
Or if you'd like to wait until the documentation PR is approved, I'd be okay with that

**Comment by Js-Brecht** [comment]
Finally had a moment to file my PR with nodejs.  See https://github.com/nodejs/node/pull/30667.  

@SimonSchick Is it possible to get @typescript-bot to hold off until that PR gets reviewed and accepted/rejected?

**Review by SimonSchick — APPROVED** [review]

**Comment by SimonSchick** [comment]
Nope, and it's kind of annoying 😛 

Just create a new PR if this one gets closed.

**Comment by Flarna** [comment]
@Js-Brecht The easiest way to keep this open is to rebase your branch and force push it.

**Comment by Js-Brecht** [comment]
@Flarna good idea.  I just squashed my commits... didn't really need all that extra, and I figure that would likely happen eventually anyway 🤷‍♂.

Looks like it's just going to keep failing, with some fun errors... finicky thing, isn't it?  I will do a full rebase later on, if needed.

**Comment by Flarna** [comment]
This CI fail looks strange.
@sandersn is this caused by or related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40676?

**Comment by sandersn** [comment]
#40676 is the fix; I updated CI, which caught 6 or so PRs in a failure while I waited for the tests on #40676 to pass.

You might have to merge from master to get tests to pass, although I just restarted the current run.

**Comment by Js-Brecht** [comment]
Let's see how that works

**Review by r3nya — APPROVED** [review]

**Comment by amcasey** [comment]
@Js-Brecht is this ready to go or are we waiting on https://github.com/nodejs/node/pull/30667?

**Comment by Js-Brecht** [comment]
@amcasey I guess it would be a good idea to wait for https://github.com/nodejs/node/pull/30667.  Though they didn't seem opposed to making these properties public, the documentation will be the clearest indicator that it is approved.  I probably should have done that PR before submitting this one; I just didn't think about it.

**Review by amcasey — CHANGES_REQUESTED** [review]
Please ping when https://github.com/nodejs/node/pull/30667 is merged.

**Comment by Js-Brecht** [comment]
@amcasey is it possible to reopen this PR, or do I need to open a new one?  https://github.com/nodejs/node/pull/30667 landed here https://github.com/nodejs/node/commit/bd9be0418a4ce528c3497ff80d5d70404be10f6f

See docs here:
https://github.com/nodejs/node/blob/master/doc/api/readline.md#rlline
https://github.com/nodejs/node/blob/master/doc/api/readline.md#rlcursor

**Comment by amcasey** [comment]
@Js-Brecht Reopened.  Good to go?

**Comment by Js-Brecht** [comment]
Yes, it is good to go

**Comment by amcasey** [comment]
I don't know what's up with the bot, but I'll merge it once CI completes.

**Review by amcasey — APPROVED** [review]

**Comment by amcasey** [comment]
Note to future readers - the Travis build passed on re-run.

**Pull request merged**
