### PR TITLE
Nightwatch.js - Changing Page Objects to any value

### PR DESCRIPTION
**Pull request by ClaytonAstrom**
Gonna be honest, I'm hoping @alecmerdler / @Schlesiger can make more sense of this, it's mostly a PR in the dark for me.

Things like [Commands](https://github.com/nightwatchjs/nightwatch/wiki/Page-Object-API#enhanced-page-object-commands) and [Sections](https://github.com/nightwatchjs/nightwatch/wiki/Page-Object-API#enhanced-section-instances) aren't going to be defined functions for NightwatchBrowser type.  The Page object has to be more open-ended, though [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes) suggests this should just be `page: any;` rather than `page: {[name: string]: any};`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by wallzero — CHANGES_REQUESTED** [review]
I'm a little outdated on the Nightwatch API or TypeScript definitions since I helped get these definitions published months ago. 

That being said; I am uncomfortable using `[name: string]: any`. If `page` has more use cases, you should be able to explicitly include them alongside `() => NightwatchBrowser`, no?

**Comment by ClaytonAstrom** [comment]
`Page` allows you to have defined actions/commands.  For example:
```ts
// the page object
module.exports = {
  elements: {
    customElement: 'selector'
  },
  commands: [
  {
  customCommand: function(this: NightwatchBrowser) {
    this.click('@selector');
  }
}

// in use:
var myPageObject = browser.page.MyPage(); // this is currently type NightwatchBrowser
myPageObject.customCommand(); // NightwatchBrowser does not have customCommand
```

In the same respect, you can have global custom commands that are directly chained from browser:
```ts
//In the command file
exports.command = function(){
  console.log('Custom command')
}

// in use:
browser.globalCommand() //NightwatchBrowser does not have globalCommand
```

I'm still super novice to typescript, so I'm hoping there's a better way than just allowing `any` but I can't think of a solution off the top of my head.  Any suggestions?

**Comment by Schlesiger** [comment]
Ahh I see. Thank you.

I still would prefer not to use 'any'. I assume `page` is included in `NightwatchCustomPageObjects` because Nightwatch populates it by default?

Since `NightwatchCustomPageObjects` is intended to be custom, could a local definition override suffice? See how it's done in the [nightwatch-vrt](https://github.com/Crunch-io/nightwatch-vrt/blob/master/index.d.ts) plugin.

**Comment by ClaytonAstrom** [comment]
Thanks!  Let me give it a try.

**Comment by ClaytonAstrom** [comment]
Alright, if I understand correctly, here's what you're suggesting?  For posterity - 

```ts
// the page object
module.exports = {
  elements: {
    customElement: 'selector'
  },
  commands: [
  {
  customCommand: function(this: NightwatchBrowser) {
    this.click('@selector');
  }
}
// types/nightwatch/index.d.ts - define an interface for each page object
export interface MyPage extends NightwatchBrowser {
  customCommand: () => NightwatchBrowser;
}
// in use:
const myPageObject = browser.page.MyPage() as MyPage; // cast to custom interface
myPageObject
  .customCommand()
  .click('@customElement'); // We still have access to standard NightwatchBrowser commands as well, so we can reference the elements
```
And for custom commands -

```ts
//In the command file
exports.command = function(){
  console.log('Custom command')
}

// types/nightwatch/index.d.ts - define 1 interface that lists all available global commands
export interface NightwatchBrowserWithCustomCommands {
  globalCommand: () => {};
  someOtherCommand: () => {};
}

// in use:
module.exports = {
  'Example Test': (browser: NightwatchBrowserwithCustomCommands) => {
    {
      browser
        .globalCommand()
        .click('someCSS') // Still preservers NightwatchBrowser commands
        .someOtherCommand();
    }
  }
};
```

**Comment by Schlesiger** [comment]
It looks alright at a glance. Does it work?

**Comment by ClaytonAstrom** [comment]
Yup works for me, just wanted to make sure I understood clearly and left it documented here.  Thanks!  Please decline the PR :)

**Comment by Schlesiger** [comment]
Cool. It appears I can only comment, approve, or request changes. Are you able to close the PR?

**Comment by ClaytonAstrom** [comment]
Ah yup, my mistake!  Closing it now :)

**Pull request closed without merging**
