### PR TITLE
[ember__service] Add new `service` export

### PR DESCRIPTION
**Pull request by mydea**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/emberjs/ember.js/pull/19776
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
A couple notes here:

1. Please restore the existing file structure for the tests. While, yes, Octane should be considered the default, this isn't the right PR for changing that!
2. This looks good overall, but there are two other blocking-for-now issues:
    1. Ember 4.1 is not out yet, so this is not yet stable and indeed does not appear in the docs (which is why you had to link to an implementation PR!). We will release this *after* 
    2. Related, this introduces the first set types for Ember which do not work on Ember 3.x. We need to think about how to solve that on DefinitelyTyped, and that *likely* means introducing a 3.x/4.x folder structure which also removes all the non-4.x types. That's on my radar to do *anyway* as prep for migrating the types into Ember's own source, so I will aim to make a PR doing that, probably tomorrow.

**Comment by chriskrycho** [comment]
Also, I meant to say: thank you for the change—it looks good other than those couple of tweaks!

**Comment by mydea** [comment]
> 1. Please restore the existing file structure for the tests. While, yes, Octane should be considered the default, this isn't the right PR for changing that!

Sure thing! I only changed it because of the DefintelyTyped readme where it instructed tests to be structured that way, so I thought that might be new. I will revert it then and just add the two cases in both the "main" and "octane" tests then.

>    1. Ember 4.1 is not out yet, so this is not yet stable and indeed does not appear in the docs (which is why you had to link to an implementation PR!). We will release this _after_

Ember 4.1 is out as far as I can tell, I only noticed these things because dependabot updated it in our apps :sweat_smile: The docs are not updated yet, though, that's right!

>    2. Related, this introduces the first set types for Ember which do not work on Ember 3.x. We need to think about how to solve that on DefinitelyTyped, and that _likely_ means introducing a 3.x/4.x folder structure which also removes all the non-4.x types. That's on my radar to do _anyway_ as prep for migrating the types into Ember's own source, so I will aim to make a PR doing that, probably tomorrow.

Sounds good to me!

**Comment by mydea** [comment]
I reverted the tests to the previous structure!

**Comment by chriskrycho** [comment]
Thank you! I'm working on the v4 types PR today, so hopefully should be able to land this by the end of the week!

**Comment by chriskrycho** [comment]
@mydea for simplicity, I’ve integrated this directly into #58060.

**Comment by chriskrycho** [comment]
@mydea thanks again; this landed as 6fb0f68 (with you credited, of course).

**Comment by mydea** [comment]
Awesome, great to hear that!

**Pull request closed without merging**
