### PR TITLE
Added KnockoutStatic.options property and defined Globalize interfaces

### PR DESCRIPTION
**Pull request by smartchenko-sdl**
Added options property to KnockoutStatic with deferUpdates,
Defined Globalize interfaces

### CODE REVIEW

**Comment by janb87** [comment]
@smartchenko-sdl Looks like there is a mistake inside Globalize.d.ts.

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/97428955

```
----------------- For file:globalize/globalize-tests.ts
globalize/globalize.d.ts(6,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
globalize/globalize.d.ts(7,12): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(8,12): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(9,14): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(10,13): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(14,15): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(15,15): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(19,14): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(20,18): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(21,12): error TS1066: In ambient enum declarations member initializer must be constant expression.
globalize/globalize.d.ts(22,12): error TS1066: In ambient enum declarations member initializer must be constant expression.
```

**Comment by Igorbek** [comment]
Regarding _knockout_, it looks good for me.

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
