### PR TITLE
fix: drop incorrect types for webtorrent org packages: webtorrent, create-torrent, parse-torrent, bittorrent-protocol

### PR DESCRIPTION
**Pull request by ThaUnknown**
Please fill in this template.

- [x Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

These types for webtorrent's packages have been outdated for ages, and for the most part aren't needed because we use JSDoc where it's important.

These types are causing an insane amt of issues for us, both for development, and for maintaining, since VSCode incorrectly inherits DT's types, and people keep making issues complaining that a function works incorrectly, because these types are wrong and are telling them incorrect things.

### CODE REVIEW

**Review by iisaduan — APPROVED** [review]

**Comment by ThaUnknown** [comment]
Ready to merge

**Comment by proton-ab** [comment]
@iisaduan
Why was this approved with package being added to `notNeededPackages.json`? `webtorrent` **does not** provide any TypeScript definitions because author thinks JSDoc is enough. This should not have been merged because it breaks all TypeScript projects using `webtorrent` and forces them to coerce all types to `any`.

**Comment by iisaduan** [comment]
@proton-ab This is my mistake, for not examining the source packages closely enough. I had assumed "we use JsDoc" meant they were generating any needed definition with the `d.ts` generator as you mentioned.

**Comment by iisaduan** [comment]
@ThaUnknown I am reverting this for now, so users can receive types that are not `any`. You can submit another PR to re-remove the packages on DT once you ship your own types. 

Alternatively, if you do not wish to ship definitions with webtorrent's packages, you could use the `d.ts` generator to generate improved/updated definitions from your JSdoc and merge them here to DT. This would also allow community members to update webtorrent type definitions as well

**Comment by ThaUnknown** [comment]
it does provide jsdoc types, @iisaduan then simply make it return window or something, it doesn't matter since the types are completely wrong anyways

**Comment by ThaUnknown** [comment]
you do not understand that these types are forced in vs code and break our entire development process inside webtorrent

**Comment by iisaduan** [comment]
@ThaUnknown What do you mean by "forced in vscode"?

**Comment by ThaUnknown** [comment]
@iisaduan I mean that, when u take a normal vscode install, import webtorrent:
image
it will forcefully use these inaccurate types
image
so we need to manually go to their install location, and delete them, every single time vscode updates, just to make sure that we don't see incorrect errors, when developing our own webtorrent packages

this is a massive issue for us as developers of webtorrent, because we get INACCURATE errors, in OUR OWN packages! it's insane to me that some1 can force inaccurate types on a module, and the maintainers of said module can't do anything about it

it gets worse, every week we'll have a couple of people go into webtorrent's discord, or github issues, cry about something not working, just to figure out they were miss-lead by the incorrect types and tried using interfaces or methods which either don't exist, or return different data than what the types specify

you can't just disable vscode's "javascript language features" extension, that breaks intellisense, autocomplete, syntax highlighting and everything else js related

I considered simply adding a d.ts file to all webtorrent modules which simply export an `any` object, but that breaks intelisense, jsdocs, and type infering

**Comment by jakebailey** [comment]
> it does provide jsdoc types

Where? https://www.npmjs.com/package/webtorrent contains no `d.ts` files. You should not be expecting users to actually get types from published JS files.

Just using JSDoc in your project is not sufficient; you need to actually run typescript or something to publish those types if you believe your types to be accurate. That or, the package on DT needs to be updated to match what you expect.

The "forcing" here is just "automatic type acquisition", which can be controlled via: https://www.typescriptlang.org/tsconfig/#typeAcquisition

If someone has not installed types, the editor will try and download types, and those must come from DT unless the webtorrent package itself provides them.

**Comment by ThaUnknown** [comment]
> You should not be expecting users to actually get types from published JS files.

but that is the exact use case of JSDoc? webtorrent is not compiled in any way, that's the way it's designed?

> you need to actually run typescript or something

it's a javascript project, we want nothing to do with typescript, and we intentionally don't need to use any of it's tooling, yet we're being punished by this

> That or, the package on DT needs to be updated to match what you expect.

you do it then? I don't think you're fully aware of what you're suggesting, we're talking about writing types for over 40 thousand lines of code, I don't have that kind of time, I'm almost solo maintaining and leading this project, with some help from @silentbot1 in my spare time, that kind of task is way above what I can do

> The "forcing" here is just "automatic type acquisition"

yes, and to disable this, you need to bring in typescript tooling and configuration into your project, wohoooo, these are raw JS projects

as I said, I'm perfectly fine with simply adding a `d.ts` file to all these projects which simply export `any`, since as I've said before, I don't have the time to create types for such an insane amt of code, but I'd rather do this the correct way, again it's wild to me that someone can add types to a package, refuse to maintain them and the package maintainers can't do anything about it

**Comment by jakebailey** [comment]
> but that is the exact use case of JSDoc? webtorrent is not compiled in any way, that's the way it's designed?

Not exactly; JS code is only a last resort when loaded by tsserver, which powers all JS and TS editing in most editors.

> yes, and to disable this, you need to bring in typescript tooling and configuration into your project, wohoooo, these are raw JS projects

You can set `"typescript.disableAutomaticTypeAcquisition": true` in VS Code to disable this feature.

> as I said, I'm perfectly fine with simply adding a `d.ts` file to all these projects which simply export `any`, since as I've said before, I don't have the time to create types for such an insane amt of code

You're totally free to do that; it's your package after all, but users will expect this to work. But there are better options.

> I'd rather do this the correct way

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69947#issuecomment-2229732054 gave the correct way for your case; you can use JSDoc, you just have to use TypeScript to generate some extra files to put in your package. This is how `webpack` does it in v5.

I went to the webtorrent package and did this:

```diff
diff --git a/.gitignore b/.gitignore
index 2c7a4c8..32d403b 100644
--- a/.gitignore
+++ b/.gitignore
@@ -3,3 +3,4 @@ package-lock.json
 webtorrent.debug.js
 sw.debug.js
 pnpm-lock.yaml
+types/
diff --git a/package.json b/package.json
index 39f9d28..78f9c60 100644
--- a/package.json
+++ b/package.json
@@ -112,6 +112,7 @@
     "tape": "^5.8.1",
     "terser-webpack-plugin": "^5.3.10",
     "timers-browserify": "^2.0.12",
+    "typescript": "^5.5.3",
     "webpack": "^5.92.1",
     "webpack-cli": "^5.1.4",
     "webtorrent-fixtures": "1.7.5"
@@ -164,8 +165,9 @@
     "build-chromeapp": "webpack --config ./scripts/chromeapp.webpack.js",
     "build-js": "webpack --config ./scripts/browser.webpack.js",
     "build-js-worker": "webpack --config ./scripts/worker.webpack.js",
-    "prepublishOnly": "npm run build && npm run update-authors",
+    "prepublishOnly": "npm run build && npm run update-authors && npm run types",
     "preversion": "npm run build && npm run update-authors",
+    "types": "tsc",
     "size": "npm run size-js && npm run size-disc",
     "size-disc": "npm run build-js && cat ./dist/webtorrent.min.js | discify --open",
     "size-js": "npm run build-js && cat ./dist/webtorrent.min.js | gzip | wc -c",
diff --git a/tsconfig.json b/tsconfig.json
new file mode 100644
index 0000000..cdad268
--- /dev/null
+++ b/tsconfig.json
@@ -0,0 +1,21 @@
+{
+    // Change this to match your project
+    "include": ["index.js", "lib/**/*"],
+    "compilerOptions": {
+      // Tells TypeScript to read JS files, as
+      // normally they are ignored as source files
+      "allowJs": true,
+      // Generate d.ts files
+      "declaration": true,
+      // This compiler run should
+      // only output d.ts files
+      "emitDeclarationOnly": true,
+      // Types should go into this directory.
+      // Removing this would place the .d.ts files
+      // next to the .js files
+      "outDir": "types",
+      // go to js file when using IDE functions like
+      // "Go to Definition" in VSCode
+      "declarationMap": true
+    }
+  }
```

Which generated types (albeit, very incomplete, as your JSDoc is not complete): 

image

**Comment by ThaUnknown** [comment]
> You're totally free to do that; it's your package after all, but users will expect this to work. But there are better options.

yeah, but I don't see how having incorrect types is in any way better than simply using type inheritance

**Comment by ThaUnknown** [comment]
I'm saying "why are maintainers of packages hassled with extra work, that they never signed up for without being able to control it"

- this is weeks if not months of work
- same result as what we have currently
- same result as what we have currently
- same result as what we have currently, these generated types are inaccurate and create a lot of the same issues like "field doesnt exist on type"
- same end result as what we have right now, no1 is going to maintain these types, they are already years out of date

**Comment by jakebailey** [comment]
Given the empty types package has already been published at 2.0.0, there's no undoing the fact that everyone using your package will now have no types at all (or at best, types attempted to be pulled from JS), except to either restore newer types here or to publish types within your package. So, we can just remove the types from here and nobody is any worse off than they already are (which is to say, still bad).

It's a little bit odd that you are using JSDoc but are saying that they're not accurate; surely you want accurate types in your own codebase. Anything you do to make the JSDoc types more accurate in your codebase are going to make the types better for those who consume your package; you're really just writing TypeScript in comments. That's all VS Code is.

For the second to last bullet point, I don't think the result is "the same". If you generate types from your codebase, users will get exactly the same experience you do when you work on your codebases today. All TypeScript is doing is exporting them to a separate file.

**Comment by ThaUnknown** [comment]
webtorrent was started over 10 years ago, this was long before there were standards for these things, since then the codebase outgrew the people that built it, the JSDoc was placed where people had time to place it, this is completely 0 profit FOSS, it's a miracle there even are any JSDoc types, again you don't fully grasp how insanely complex of a library webtorrent is, and just how much time it would take to define the types for this, even these old types were quite inaccurate

> second to last bullet point

it is different, not fully specified types generated from jsdoc are different from loose types, to fix this we would need to update jsdoc in a lot of places, at which point might as well just define the types. strict types with missing fields will throw errors when u try to access those missing fields, loose types wont error
image

**Pull request merged**
