### PR TITLE
[teslajs] Added consistent typings for callbacks & options

### PR DESCRIPTION
**Pull request by JAD3N**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by fcastilloec** [comment]
@JAD3N Is there a reason for the `nodeBack` change? I haven't been keeping up with new conventions but from my previous understanding, there's a difference between a simple `Callback` and a `nodeBack` and because TeslaJS is designed for nodejs, we should be using the appropriate one.
Regarding `optionsType`, I have no comment on that. Maybe somebody with more experience can chime in and decide if this change is worth it.

**Comment by JAD3N** [comment]
@fcastilloec

I didn't realize there was a specific reason to have it as nodeBack, but regardless it seems fine as a callback by itself is not node-specific.

The main library only uses 'request' to make GET requests so it doesn't really seem that the callbacks would only work on Node? I assume this would also work on browsers if using an appropriate bundler for example.

I've just named them what I think was more appropriate for their use cases. I also changed them to be camel-cased just so it fits with the other typings.

**Comment by fcastilloec** [comment]
I know it seems fine but we'll probably need to set tests to **know** that's fine. Even then, teslaJS project page specifies that the library it's supposed to be used with nodejs, so I rather not assume anything and go with what the creator/maintainer of the project has specified.

I don't have a problem with the camel-cased change to `optionsType`, as I mentioned earlier; but I rather let somebody with more knowledge be the judge of that.

**Comment by elibarzilay** [comment]
I'm making it possible to self merge when approved, but please consider adding tests -- I realize that this changes an existing definition that had no tests (for this), but adding them would be good for the future too.

**Pull request closed without merging**
