### PR TITLE
Update array-find-index-tests.js

### PR DESCRIPTION
**Pull request by aayushjainx**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by aayushjain7** [comment]
Can anyone review, please?

**Comment by aayushjain7** [comment]
@SamVerschueren Hey!

**Comment by SamVerschueren** [comment]
Why these changes? I don't see any added benefit except for changing some strings?

**Comment by aayushjain7** [comment]
I am new to open source contribution and wanted to get started with it. Hope I get approval and get mentored on how to make effective changes.

**Comment by aayushjain7** [comment]
Can I get approval? @SamVerschueren

**Comment by SamVerschueren** [comment]
I don't think this PR should be merged. It doesn't add anything besides changing some strings and thus just feels like a PR to create a PR.

If you are new to open source, welcome! Everyone has to start somewhere, right :). So if you want to contribute, there are a shit ton of projects which have labels like "good first issue" or something. My suggestion is, pick a project you are genuinely interested in and that you use yourself. Open source should be fun, it shouldn't feel like a drag. The only way you can do that is if you are really liking the project and have some personal affection with it.

Just my 2 cents though :). I'm open to answering questions. My twitter DM is open.

**Comment by aayushjain7** [comment]
No issues and Thanks for the great advice! I'll surely try to contribute in a better manner and would definitely reach out to you for more guidance. 👍🏼  @SamVerschueren

**Pull request closed without merging**
