### PR TITLE
Fixed IReply definition

### LINKED ISSUE #4986: Hapi IReply can not be called with void parameter
reply() works from javascript, but it fails when tsc compiles the code with   error TS2346: Supplied parameters do not match any signature of call target.

### PR DESCRIPTION
**Pull request by bherila**
Supersedes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/4990#issuecomment-208975588

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4986

Looks like the original author is very out of date. I rebased my own fork and fixed the whitespace in the file which was causing a merge conflict. I also added support for reply.state/unstate which was not in the d.ts file already (defined here: http://hapijs.com/api )

### CODE REVIEW

**Comment by jasonswearingen** [comment]
Hi @bherila definitelyTyped doesn't like implicit ```any```, can you fix this?  (the travis CI failed)
```
----------------- For file:hapi/hapi.d.ts
hapi/hapi.d.ts(278,9): error TS7010: 'header', which lacks return-type annotation, implicitly has an 'any' return type.
```

**Comment by bherila** [comment]
@jasonswearingen fixed

**Comment by vvakame** [comment]
@jasonswearingen  can I merge this PR?

**Comment by jasonswearingen** [comment]
yep all's good :+1:

**Pull request merged**
