### PR TITLE
add some definitions for leaflet 1.0.0

### PR DESCRIPTION
**Pull request by hagai26**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by rgripper** [comment]
@hagai26 Hi! I think, this is not a good idea to expose private members:
> We do not support exposing undocumented internal implementation details of libraries in .d.ts files.
http://definitelytyped.org/guides/contributing.html

And Control definition begs for an update (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9661)

@dt-bot :-1:

**Comment by hagai26** [comment]
That's too bad.
These are the only options to use these features (get source marker of a pop-up for example).

So I will remove the private defs and update this PR.
I will update more control defs as well.

**Comment by rgripper** [comment]
@hagai26 That'd be good :), coz now it's messy. If private members are so usable, leaflet itself probably needs issue added.

**Comment by hagai26** [comment]
Hi, 
I reverted the private members.
I added other additions to the typings.

Is this OK now?
I don't want to make too many changes on my first PR.

**Comment by rgripper** [comment]
@hagai26 Thats's lovely! :+1: 

@vvakame :)

**Pull request merged**
