### PR TITLE
[parse-torrent] version bump to 5.8, webtorrent changes

### PR DESCRIPTION
**Pull request by tlaziuk**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/feross/parse-torrent/blob/v5.8.1/index.js>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by tlaziuk** [comment]
I don't know if I can make an PR with many packages, but all the typings are related to the WebTorrent ecosystem.

**Comment by mhegazy** [comment]
@niieani  can you please review?

**Comment by mhegazy** [comment]
> I don't know if I can make an PR with many packages, but all the typings are related to the WebTorrent ecosystem.

you can; it makes it easier to process them if they are separate however.

**Review by niieani — APPROVED** [review]
Looking good.

**Pull request merged**
