### PR TITLE
Fix SAXParser startTag attrs type.

### PR DESCRIPTION
**Pull request by MeirionHughes**
case 2. Improvement to existing type definition.
Fix typing bug, see: https://github.com/inikulin/parse5/issues/147

update ASTAttribute to include optional prefix field

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Can you add a couple of tests for this change?

**Comment by nicojs** [comment]
👍

**Comment by MeirionHughes** [comment]
@paulvanbrenk added some better tests and fixed some of the existing ones so they run with parse5.

**Comment by MeirionHughes** [comment]
@azakus @garlicnation @nevir @polymer dom5 - could you check this won't break for you. I'm working to get this on @types namespace asap.

**Pull request merged**
