### PR TITLE
bip38grs type definitions were added

### PR DESCRIPTION
**Pull request by gruve-p**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by jakebailey — CHANGES_REQUESTED** [review]
See above; you own the package, so I don't see a reason to stick this on DT when you can just publish the types.

**Comment by gruve-p** [comment]
> Given https://github.com/groestlcoin/bip38grs, you are the primary author of this package; why not ship these types with your package?

Thank you for the review. We are in the process of adding other authors to this package where I no longer will be the primary author. I need this PR to be able to continue my/our work on https://github.com/Groestlcoin/bluewallet. Currently we work on a private branch but we can't push the work because this PR is blocking the merge.

**Review by jakebailey — APPROVED** [review]
I am not sure why we accepted `bs58grscheck` if it was also maintained by those who submitted the types; I would not have done so without a clear reason. I'm still not sure I understand your reasoning, either.

**Comment by gruve-p** [comment]
Ready to merge

**Pull request merged**
