### PR TITLE
[react-native-google-analytics-bridge] - Updated the typings for v5.2

### PR DESCRIPTION
**Pull request by nbperry**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/idehub/react-native-google-analytics-bridge/blob/master/README.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nbperry** [comment]
The travis build failed however there is no log file, I am not really sure how to proceed.

**Comment by huhuanming** [comment]
Is it a bug for travis?

it would be a while.

**Comment by nbperry** [comment]
Not really sure. I will try to retrigger a travis build tomorrow.

**Comment by huhuanming** [comment]
I will try more than once today.

Sometime I think many benefits will flow from this jet lag. :-D

**Comment by nbperry** [comment]
@huhuanming Updated the styling to be consistent throughout the tests, which kicked off a new build. TravisCI build successfully ran, I suspect the worker just got stuck and eventually just got cleaned up by TravisCI.

**Review by huhuanming — APPROVED** [review]
LGTM

**Comment by huhuanming** [comment]
it always does sometimes happen.

**Pull request merged**
