### PR TITLE
[oauth2orize] add more functions with different arities

### PR DESCRIPTION
**Pull request by saschanaz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    * ValidateFunction: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/middleware/authorization.js#L229-L236
    * IssueGrantCodeFunction: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/grant/code.js#L178-L186
    * IssueExchangeCodeFunction: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/exchange/authorizationCode.js#L103-L109
    * `modes.query`: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/grant/code.js#L67-L70
    * `scope` being an array: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/grant/code.js#L102-L109
    * `server.authorization === server.authorize`: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/server.js#L135-L138
    * `grant.code === grant.authorizationCode`: https://github.com/jaredhanson/oauth2orize/blob/1ffdd85feea087e478e748e1d59f7e7821853cfb/lib/index.js#L48
    * Why expose `ArityN` functions?: Because TypeScript cannot properly resolve the correct function signature and always matches to the longest one. One would need to either just use the longest signature or use explicit type cast with new ArityN functions. See also https://github.com/Microsoft/TypeScript/issues/14107.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

There are more things to be fixed but these are in my current scope.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## oauth2orize ([<kbd>unpkg</kbd>](https://unpkg.com/browse/oauth2orize@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'oauth2orize'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. errorHandler
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dfbf6234c912029c5c9fa37aa4a03a60fb71691e
</p>

**Comment by saschanaz** [comment]
Should I trim existing maintainers and add myself instead? 😅)

**Review by sandersn — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
(Testing merge bot, thanks for your patience)

**Comment by saschanaz** [comment]
Ready to merge

Yay!

**Comment by saschanaz** [comment]
Thanks!

**Pull request merged**
