### PR TITLE
add export to qiniu

### PR DESCRIPTION
**Pull request by xialeistudio**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [4b73624](https://github.com/xialeistudio/DefinitelyTyped/commit/4b73624d17d1f578b167f0c3f4a8147fefdef31e)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
This change breaks the tests. See the travis log for details.

**Comment by paulvanbrenk** [comment]
@xialeistudio can you fix this issue, which seems to be the root problem:

`Testing qiniu
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js 
	/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/qiniu/index.d.ts
ERROR: 264:1   export-just-namespace  Instead of `export =`-ing a namespace, use the body of the namespace as the module body.`

**Comment by xialeistudio** [comment]
please wait a moment.

**Comment by xialeistudio** [comment]
remove types/qiniu definition due to qiniu provides its own type definitions.

**Pull request closed without merging**
