### PR TITLE
[stampit] moved Stamp type to reside in main namespace

### PR DESCRIPTION
**Pull request by lummish**
Moved the ```Stamp``` type to within the main exported namespace to make it accessible when the package is imported.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

Provision of a URL here should not be necessary as the original package does not explicitly mention TypeScript and the only purpose for making this change was to enable TS users to make more explicit the typings of their Stamps.

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by koresar** [comment]
Thank you. That's a great PR @lummish 

Two questions.

* The latest version of stampit is 4. The PR is for v3. Are you sure you want only v3 supported?

* What if https://github.com/stampit-org/stampit would add `./types/*.ts` folder to the distributive would that help?

**Comment by koresar** [comment]
Oh. And last question if that's okay.

* Do you think that it would be helpful to see link(s) to the official docs https://stampit.js.org/ in the coding assistant (aka intellisense)  ?

**Comment by lummish** [comment]
@koresar Thank you for the compliment! To answer your questions...

- I am aware that the latest version is v4. I'm slowly moving towards it but I'd like to finish up v3 first. Very few breaking changes were made between the two versions so I don't the upgrade should be particularly difficult.
- It probably would. Is that generally preferred to writing definitions in this repo?
- Links to the docs might be helpful. What's the syntax for that?

**Comment by koresar** [comment]
* Ok. Sounds great.
* I might copy and ammend this `.d.ts` file to stampit repo
* The syntax can be found here: http://usejsdoc.org/tags-inline-link.html For example: `{@link https://stampit.js.org Stampit Docs}`

I'll click "Approve" now.

Thanks again mate!

**Review by koresar — APPROVED** [review]

**Pull request merged**
