### PR TITLE
fix(node): revert ts3.6 removal for Node v12

### LINKED ISSUE #55430: [@types/node] Drops support for TypeScript < 3.7 in 12.20.21 ("assert.d.ts:2:68 - error TS1144: '{' or ';' expected.")
This report was for some reason created as a "discussion" #55429 ; moving to a proper ticket.

Our TypeScript 3.5 project stopped compiling yesterday, due to an upgrade to @types/node 12.20.21, with a bunch of errors:

> ERROR in ../node_modules/@types/node/assert.d.ts:2:68 - error TS1144: '{' or ';' expected.
> 2     function assert(value: any, message?: string | Error): asserts value;

image

This would be no surprise as TypeScript 3.5 is fairly old and DefinitelyTyped does not support old versions indefinitely, except after analysis it turns out our package.json properly specify the dependency:
`    "@types/node": "^12.7.1",`

In fact, @types/node had already dropped support for TypeScript 3.6, but for some reason, this week this change was backported to branch 12, and while 12.20.20 was fine, 12.20.21 drops support, breaking semantic versioning.

The exact reason why TypeScript 3.5 now fails to compile is usage of TypeScript 3.7 [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions).

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Fixes #55430 and #55429

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@orta (while you're around)

**Comment by peterblazejewicz** [comment]
@SimonSchick is this a full revert or partial one?
I know you've discussed this topic with other folks on TS (I've ready the thread)

**Comment by peterblazejewicz** [comment]
> it seems dtslint doesn't like this PR since 3.6 is no longer considered supported, can we add some sort of exception to this package?

what's this error about? Are expectations failing as 3.7 is used? Can we except tests by @ts-ignore comments?

**Comment by SimonSchick** [comment]
@peterblazejewicz no this is a DTSLint assertion failing, not a lint rule..

**Comment by peterblazejewicz** [comment]
adding @sandersn

**Review by sandersn — CHANGES_REQUESTED** [review]
I commented on the issue; this break is by design, so v12 should continue supporting only 3.7 and above.

**Comment by SimonSchick** [comment]
Alright, not like this PR was a whole lot of work :)

**Pull request closed without merging**
