### PR TITLE
Add proper type for process.env in Node.js

### PR DESCRIPTION
**Pull request by miniak**

### CODE REVIEW

**Comment by andy-ms** [comment]
Please fix the compile errors.

**Comment by xeoneux** [comment]
@miniak would love to have this merged as soon as possible...
@andy-ms why are there compile errors?

**Comment by andy-ms** [comment]
Just `npm run lint node` to see the errors for yourself.
`ProcessEnv` is used in a few places where it's not in scope; `NodeJS.ProcessEnv` should be used instead.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
