### PR TITLE
[@storybook/react] Add demo subpackage.

### LINKED ISSUE #21136: @types/storybook__react misses declarations for demo.js
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @joscha

If you do not mention the authors the issue will be ignored.

The statement `import { Button, Welcome } from '@storybook/react/demo';` causes compile error in "stories/index.js" generated by `getstorybook 3.2.3` .

I avoid this by providing my own file like following now.

```typescript
declare module '@storybook/react/demo' {
  export class Button extends React.Component<React.HTMLProps<Button>> {
  }

  export interface WelcomeProps {
    showApp: React.MouseEventHandler<Welcome>;
  }

  export class Welcome extends React.Component<WelcomeProps> {
  }
}
```

Should we include this fragment in @types/storybook__react to complete?

### PR DESCRIPTION
**Pull request by karak**
Fixed #21136

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/storybooks/storybook/tree/master/app/react/src/demo
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by karak** [comment]
Does anyone know the _preferred_ submodule position?

The module has subdirectory `demo` which contains `Button` and `Welcome` in own package.

And, some package allows both usage like `import { Button } from 'great-ui'` and `import Button from 'great-ui/button'`.  For example, material ui has multi-module structure that root 'index.d.ts' includes all the module declarations with ghost namespaces.

**Comment by minestarks** [comment]
`demo.js` isn't part of the library, it's just an example file in the package. As such, I don't think it's typings should be added to DefinitelyTyped.

Package author @joscha any comments?

**Comment by joscha** [comment]
> Package author @joscha any comments?

I agree. I don't think it's worth maintaining them.

**Comment by karak** [comment]
Hmm....
OK.  Then, I just share this by gist or something with somebody need it as me. 
Thank you for your review @minestarks @joscha.

**Comment by minestarks** [comment]
Thank you for your contribution -- I'm sorry it didn't make it. Sounds like a great idea to share it, if not here.

**Comment by louy2** [comment]
I have to disagree that examples are not part of library. They are crucial resources instructing users to get started with the library. The type for the examples here serves a similarly crucial purpose of instructing users to get started declaring types using the library. 

That said, it is a bit awkward to maintain the types here. @karak Maybe we can convince storybook/react to include them.

**Comment by charlesgivens** [comment]
I am setting up storybooks on a blank monorepo. I have nothing in it yet, but I want to make sure storybooks is configured properly in my repo using typescript. 

Storybooks will not run with typescript because of this. So in order to make sure that it is working properly, you're saying I have to write a whole new component because you don't want to maintain simple types. Just add an **ANY** to it so at least storybooks will run with a basic typescript instillation.

Also for your information, both React and React-Native now offer default typescript installation with just a flag. Can you at least get this commit in so we can verify our installation.

Thank you for reading.

**Pull request closed without merging**
