### PR TITLE
[twine-suragcube] fixes for the 2.37 update

### PR DESCRIPTION
**Pull request by ezsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.motoslave.net/sugarcube/2/docs

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/twine-sugarcube/extensions.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4bdd9eb0663945e0ac8c58f84cb6a858db5c319a
</p>

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/twine-sugarcube/test/config.ts
1. types/twine-sugarcube/test/story.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5e17dbaf515d4ad65ad6dd55e315d94d64f34815
</p>

**Review by tmedwards — APPROVED** [review]

**Comment by ezsh** [comment]
Thanks, @tmedwards!

**Comment by ezsh** [comment]
Ready to merge

**Pull request merged**
