### PR TITLE
[@types/screeps] Update screeps' definition for version 2.12.1

### PR DESCRIPTION
**Pull request by Skida12138**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Screeps Documentation](https://docs.screeps.com/api/)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by Arcath — APPROVED** [review]
Looks good to me.

**Comment by pyrodogg** [comment]
FYI A 3.0 push from typed-screeps has been in development for a few weeks now. I'm looking to push it to DT this weekend.

**Comment by Skida12138** [comment]
@pyrodogg That's the best thing I've heard today:smiley:! Shall I close this PR and wait for yours?

**Comment by pyrodogg** [comment]
It would certainly reduce noise to wait until Saturday. Follow https://github.com/screepers/typed-screeps/issues/148 for my status on pushing update.

**Pull request closed without merging**
