### PR TITLE
[oidc-provider] 7.2 update

### PR DESCRIPTION
**Pull request by panva**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/panva/node-oidc-provider/releases/tag/v7.2.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by panva** [comment]
Why am i not able to self merge given i'm the sole author and owner of the module in question?

**Review by ralphbragg-ob — APPROVED** [review]
Thanks Filip for this addition. Very much appreciated.

**Review by milo526 — APPROVED** [review]
LGTM

**Review by adamjmcgrath — APPROVED** [review]

**Comment by panva** [comment]
Ready to merge

**Pull request merged**
