### PR TITLE
update to selenium-webdriver 4 typings

### PR DESCRIPTION
**Pull request by cnishina**
- Update typings and tests
  - control flow and promise.Promise deprecated
  - API changes with regard to W3C
- Moved previous typings to v3

### CODE REVIEW

**Comment by cnishina** [comment]
Oops. Should have added v3/test/ and v3/tsconfig.json

**Comment by cnishina** [comment]
Okay I also added in a tslint.json and changed the compilerOptions.

**Comment by cnishina** [comment]
This PR blocks: https://github.com/angular/protractor/issues/5192

**Comment by cnishina** [comment]
🤦‍♂️ I thought I was changing the selenium-webdriver version and I changed the TypeScript version.

**Comment by cnishina** [comment]
Thanks @typescript-bot

**Comment by cnishina** [comment]
Woo hoo! @andy-ms I might need your help for review. Some of the other owners haven't been as active. Also not having this published is causing my users to have issues when installing Protractor 6.

**Comment by oddui** [comment]
@cnishina I'm testing it in a small project it looks it's missing the logging API change from #31073

**Comment by cnishina** [comment]
Hmmmmm. Has the selenium 4 logging API changed?

**Comment by oddui** [comment]
The selenium 4 logging API hasn't changed. #31073 is a type fix for the logging API.

**Comment by cnishina** [comment]
Great! We were working off a forked version of selenium webdriver types that did not have these changes.

**Comment by oddui** [comment]
Thanks! It works nicely for me now.

**Comment by cnishina** [comment]
Also added back oddui to the "Definitions By" section.

**Comment by oddui** [comment]
@cnishina thanks for doing that

**Pull request merged**
