### PR TITLE
[passport] corrected type definitions version.

### PR DESCRIPTION
**Pull request by kstiehl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

For more info see #31432

### CODE REVIEW

**Comment by kstiehl** [comment]
You are looking at the npm package for the type definitions.
Which is now at 1.0.0 because of my previous oopsie. 
whilst https://www.npmjs.com/package/passport is still hat version 0.4

**Comment by danielpa9708** [comment]
Yeah, I mean, when an user install `@types/passport` will be installing the 1.0.0 already published, event if a new version 0.5 is published

**Comment by kstiehl** [comment]
Yes you are right. The 1.0.0 version should actually be removed from npm, so that is is correct again. But I am afraid that there are more than a few thousands downloads already. Maybe @sandersn or @weswigham know what to do in this case.

**Comment by sheetalkamat** [comment]
Adding @weswigham to see what needs to happen with package version.

**Comment by weswigham** [comment]
We can't really unpublish type definitions (technically you can npm unpublish, but it  just tombstones  that version number - and only publishes within 72 hours at that) so this is a bit of a sticky wicket, since reverting the version number to lower would result in us publishing type defs that would never get installed, since they'd be less than the latest version...

**Comment by kstiehl** [comment]
Now what?

**Pull request closed without merging**
