### PR TITLE
[recompose]: Improve withHandler & withStateHandlers 

### PR DESCRIPTION
**Pull request by alatushkin**
[recompose]:Improve withHandler & withStateHandlers to restrict updaterName/handlerName to corresponding type filed names.

### CODE REVIEW

**Comment by alatushkin** [comment]
It will prevent typos (and force to fill all handlers necessary) in such cases:
```
interface HandlerProps {handler1: Function; handler2: Function;}
interface OutterProps { out: number; }
    const enhancer = withHandlers<OutterProps, HandlerProps>({
      handler1: (props) => (e: any) => {}, //ok
      hnadler1: (props) => (e: any) => {}, //show compile error cause of typo
      //show compile error cause of absent of handler2
    });
```

**Review by clayne11 — CHANGES_REQUESTED** [review]
I'm not totally sold on the value of this. We're creating the handlers with this function so what's the purpose of passing in an object with the handler keys?

**Comment by alatushkin** [comment]
@clayne11 
Let's look to original source. It was 
` type HandleCreatorsFactory<TOutter, THandlers> = (initialProps: TOutter) => HandleCreators<TOutter>;`

Doesn't it looks strange?  
Purpose of type parameters is to restrict input or output types. But what purpose of THandler in your code? what it restricts? Seems like nothing.

My patch close this issue. 
And in 'everyday use' cause IDE to prevent typos in code (as i mentioned in above)

**Comment by andy-ms** [comment]
@alatushkin Could you add a test to show how this would be used?

**Comment by RyanCavanaugh** [comment]
@alatushkin Please address comments from the code reviewers.

**Comment by leemhenson** [comment]
@andy-ms This change requires no changes to existing usages. It just incrementally increases typesafety by forcing the correct names to be provided for the updater functions. I think the only test you could write would be to prove the negative (ie. misnamed updater functions should cause compiler errors). Is that kind of test possible within DefinitelyTyped?

I can verify that this PR works for me (I even wrote the same PR before looking here, d'oh!).

**Comment by minestarks** [comment]
@leemhenson Yes you can add a negative test cases using [`// $ExpectError`](https://github.com/DefinitelyTyped/DefinitelyTyped#lint)

**Review by minestarks — CHANGES_REQUESTED** [review]
please address the existing feedback and add a test case to avoid the PR being closed due to staleness. Thank you!

**Comment by minestarks** [comment]
Thanks - closing in favor of #22159 which contained your changes.

**Pull request closed without merging**
