### PR TITLE
Rx: resultSelector should be optional

### PR DESCRIPTION
**Pull request by ntrrgc**
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/concatmap.md
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/selectmany.md
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/withlatestfrom.md

### CODE REVIEW

**Comment by ntrrgc** [comment]
Why is that? I haven't touched the header at all.

**Comment by vvakame** [comment]
@Igorbek could you review this PR?

**Comment by mhegazy** [comment]
no reply from other authors for over 2 weeks. merging.

**Comment by Igorbek** [comment]
Sorry that didn't respond. Thank you for contribution.
I need to note that those signatures will not work, or at least will not be very convenient to use. If `resultSelector` were not passed the result type would be different, so the type inference wouldn't work correctly.

So, for example, 

```ts
combineLatest<T2, TResult>(second: Observable<T2>, resultSelector?: (v1: T, v2: T2) => TResult): Observable<TResult>;
```
must be split up into:
```ts
combineLatest<T2, TResult>(second: Observable<T2>, resultSelector: (v1: T, v2: T2) => TResult): Observable<TResult>;
combineLatest<T2>(second: Observable<T2>): Observable<[T, T2]>;
```
Note that in case of omitted `resultSelector` the resulting type is predictable, instead of it being generic parameter.

@ntrrgc do you think you could make another PR with this in mind?

**Comment by ntrrgc** [comment]
@Igorbek You're right, I see how they can fail. Indeed they lost the payload type.

I'm looking into it right now.

**Comment by ntrrgc** [comment]
Hm. I've noticed there is a combinatory explosion of `Observable` and `IPromise` in many operators.

Why couldn't we use `Observable<T2>|IPromise<T2>` instead of creating several overloads?

**Comment by ntrrgc** [comment]
Many Vim macros after, I got to modify the definitions to infer proper types. I've also added union types so I could write them without doubling the number of overloads for some operators (e.g. `zip`).

Please check it out, @Igorbek https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9785

**Comment by Igorbek** [comment]
> Why couldn't we use Observable<T2>|IPromise<T2> instead of creating several overloads?
It were created back in the time when union types weren't supported :)

**Comment by ntrrgc** [comment]
Yeah, I guessed it would be something like that.

**Pull request merged**
