### PR TITLE
[node] `http.Agent` extends from `EventEmitter`

### PR DESCRIPTION
**Pull request by TooTallNate**
```
$ node
Welcome to Node.js v16.20.0.
Type ".help" for more information.
> http.globalAgent instanceof events.EventEmitter
true
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    * Docs (doesn't really mention EventEmitter): https://nodejs.org/api/http.html#class-httpagent
    * Source Code: https://github.com/nodejs/node/blob/v16.20.0/lib/_http_agent.js#L199
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Semigradsky** [comment]
@TooTallNate please add these changes to `v18` folder too (rebase from master, folder was created recently)

**Comment by TooTallNate** [comment]
Ya, sure thing. Added.

**Review by Semigradsky — APPROVED** [review]
LGTM!

**Review by peterblazejewicz — APPROVED** [review]
@TooTallNate thanks!

**Comment by TooTallNate** [comment]
Ready to merge

**Pull request merged**
