### PR TITLE
[exceljs] Fix column properties

### PR DESCRIPTION
**Pull request by alitaheri**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alitaheri** [comment]
I'm in the author list, why is this bot not including my own name, or at least mentioning that I'm one of the authors. :|

**Comment by andy-ms** [comment]
I think it doesn't ask people to review their own PRs.
Thanks!

**Comment by alitaheri** [comment]
@andy-ms Thanks. But how will a member know that the PR was submitted by an author without having to explicitly check the file?

**Comment by andy-ms** [comment]
There are lots of improvements that could be made to dt-bot, maybe file an issue if it's not already there? https://github.com/DefinitelyTyped/dt-review-bot

**Pull request merged**
