### PR TITLE
[@types/pdfkit] Add definition for mixin Attachment

### PR DESCRIPTION
**Pull request by longdoan7421**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://pdfkit.org/docs/attachments.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## pdfkit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pdfkit@latest/))
was missing the following properties:
1. LineWrapper
1. from
1. finished
1. pipeline
1. Stream

<details>
<summary>as well as these 10 other properties...</summary>
<p>Readable, Writable, Duplex, Transform, PassThrough, errorMonitor, captureRejectionSymbol, captureRejections, defaultMaxListeners, EventEmitter</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9282267e4ee7c227718e13e399e123366b264e8
</p>

**Review by BamButz — CHANGES_REQUESTED** [review]
LGTM!

**Review by BamButz — APPROVED** [review]
Sorry, my bad, I should drink my coffee first.

**Comment by longdoan7421** [comment]
Ready to merge

**Pull request merged**
