### PR TITLE
log4js.d.ts: remove express reference and types (#10910)

### PR DESCRIPTION
**Pull request by samizdam**
Fix to #10910.

### CODE REVIEW

**Comment by zhengbli** [comment]
Thank you for your contribution.

Can you please fix the failing Travis CI tests and update the PR?

**Comment by samizdam** [comment]
@zhengbli, fixed.

**Comment by zhengbli** [comment]
@armorik83 Can you review it please

**Comment by andy-ms** [comment]
Is this really an improvement? `log4js` might not declare a dependency on `express`, but it returns a value of the correct handler type, and that type is defined in the express typings. Seems like you could just install the `express` typings. In `types-2.0`, the `@types/log4js` module depends on `@types/express`, so this is done for you.

**Comment by mhegazy** [comment]
As noted in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11067#issuecomment-248955091, this is not needed.

**Comment by samizdam** [comment]
I think, it's not good idea, install something about express if I don't use it. 

@andy-ms solution work work for me, but it's not very good way... 
I am reinstall log4js, follow for all its stripped dependencies and try transpile my code every time: 

``` 
$ typings prune
typings INFO prune log4js (main) (global)

$ typings install dt~log4js --global --save
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b6be233cb45c5d9be041591528c57d3c87737db1/express/express.d.ts" during installation from "log4js" (main)
log4js
`-- (No dependencies)

$ tsc
typings/globals/log4js/index.d.ts(4,28): error TS2307: Cannot find module 'express'.

$ typings install dt~express --global --save
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5fd6d6b4eaabda87d19ad13b7d6709443617ddd8/serve-static/serve-static.d.ts" during installation from "express" (main)
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5fd6d6b4eaabda87d19ad13b7d6709443617ddd8/express-serve-static-core/express-serve-static-core.d.ts" during installation from "express" (main)
express
`-- (No dependencies)

$ tsc
typings/globals/express/index.d.ts(4,34): error TS2307: Cannot find module 'serve-static'.
typings/globals/express/index.d.ts(5,27): error TS2307: Cannot find module 'express-serve-static-core'.

$ typings install dt~serve-static --global --save
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/26a1f8c44f5fe76168df717020bfb93839b63db3/express-serve-static-core/express-serve-static-core.d.ts" during installation from "serve-static" (main)
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/26a1f8c44f5fe76168df717020bfb93839b63db3/mime/mime.d.ts" during installation from "serve-static" (main)
serve-static
`-- (No dependencies)

$ typings install dt~express-serve-static-core --global --save
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/bbf7d433237a5e8eb455e74bbd561f614eea9f15/node/node.d.ts" during installation from "express-serve-static-core" (main)
express-serve-static-core
`-- (No dependencies)

$ tsc
typings/globals/serve-static/index.d.ts(13,24): error TS2307: Cannot find module 'mime'.

$ typings install dt~mime --global --save
mime
`-- (No dependencies)

```

Phhh... Now I have 4 outsiders in my project for use 1 required for me dependency: express, express-serve-static-core, mime, serve-static. Only after this I can run my app. It's hell, to my mind. 

Seems like it is issue for typings: resole stripped dependencies by default or optionally.

**Pull request closed without merging**
