### PR TITLE
[react-alert] Update react-alert to 5.2.

### PR DESCRIPTION
**Pull request by huan086**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/schiehll/react-alert
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huan086** [comment]
Do not merge yet

**Comment by g1eny0ung** [comment]
@huan086 Good jobs. I learned a lot of types definitions from u. But how can I approve u pr? I haven't found any button named **Approve**.

**Comment by huan086** [comment]
Go to the Files changed tab. You can click on the line of the code to start review and comment. Once you are done, on the top right, there is a review changes green button.

**Review by g1eny0ung — APPROVED** [review]

**Comment by g1eny0ung** [comment]
@huan086 Thx. Already approved.

**Pull request merged**
