### PR TITLE
[angular] Add index signature to JQLite

### LINKED ISSUE #17772: @types/angular JQuery in jqlite.d.ts doesn't have index signature
- [x] I tried using the `@types/angular` v1.6.25 package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [x] Caused by PR #17304 
  - Authors: @leonard-thieu 

The JQuery interface in jqlite.d.ts doesn't have an index signature. As a consequence the compiler throws an error when `noImplicitAny` is on and you want to access the underlying HTML `Element`(s).

Example:
```
// error: Element implicitly has 'any' type because type 'JQuery' has no index signature.
const logElement = (el: JQuery) => console.log( el[0] );
```
Obviously, the same happens with `IAugmentedJQuery`.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

Fixes #17772

### CODE REVIEW

**Comment by leonard-thieu** [comment]
*types/angular/index.d.ts*

to authors (@diegovilar @thorn0 @calebstdenis). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

------

*types/angular/jqlite.d.ts*

to authors (@borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @.benjaminjackman @s093294 @JoshStrobl @johnnyreilly @DickvdBrink @King2500 @andrewiggins). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by thorn0** [comment]
What's the motivation for adding a separate `JQLite` interface and adding the indexer to it? What would happen if you just add it to `JQuery`?

**Comment by leonard-thieu** [comment]
Declaring the index signature on `JQuery` causes a `Duplicate number index signature.` error when merging with `@types/jquery`. Note that the index signatures on `@types/jquery` v1/v2 and v3 are different. Declaring the index signature on `JQLite` allows for compatibility between `@types/angular` and any version of `@types/jquery`.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17676 for more details.

**Comment by thorn0** [comment]
LGTM

**Pull request merged**
