### PR TITLE
[@types/quickapp-interface] Add type definitions

### PR DESCRIPTION
**Pull request by tech-bro-in-vivo**

### CODE REVIEW

**Comment by elibarzilay** [comment]
Context: this is essentially re-opening #56456, and addresses the questionable name point.

But there's still the question of why put this on DT?  The code is taken directly [from a repo](https://github.com/vivoquickapp/quickapp-types/) in the org that owns the library too, so it would be best to distribute it with the library.

(I'm not sure which libraries in the org are the main entry points since I can't read most of the texts.  I see that the repo that this code is coming from references the npm library, but I'm guessing that there are some other libraries from the `vivoquickapp` organization on npm too, and dealing with the names of all of these should be sorted out at the org level...  Also, given that this code lives in a repo, it's not clear to me why a different person makes this PR.)

**Comment by tech-bro-in-vivo** [comment]
@elibarzilay 

**why put this on DT?**

This library is mainly used to give grammar hints to fast application development tools. We used to put it on github, but many people have problems when downloading content on github through npm(please see the following code), so we consider putting it in DT. More stable.

```json
// package.json
{
	  "devDependencies": {
	      "@types/quickapp": "git+https://github.com/vivoquickapp/quickapp-types.git",
          // ......
	   },
}
```


This account is a key member of the `vivoquickapp` organization and in our opinion, it is normal behavior to use this account to initiate pull requests.  I would like to add an additional note, Considering that our engine code is not open source, and we want to provide code syntax hints for developers through vscode or our IDE, so the `@types/quickapp-interface` approach is the best way we got after a lot of thought, we hope we can get your understanding and support, thank you very, very, very much.

**Comment by elibarzilay** [comment]
It sounds to me like the only thing you're getting from DT then is the distribution as an npm package, which you can do yourself.  The above `package.json` fragment has the problem of making npm go through the git protocol to fetch the code, but if you'll publish it, you'll get a normal download.  Further, assuming that you distribute the actual library via npm, you can specify this as dependency, which means that people won't need to add it at all.

**Comment by tech-bro-in-vivo** [comment]
Perfect. Thank you very  much,  Based on your suggestion, we found a suitable way to install `@types/quickapp`(No need to publish `@types/quickapp` ) and now I can close this pull requests, thanks again.

```bash
npm i @types/quickapp@npm:quickapp-interface --save-dev
```

**Pull request closed without merging**
