### PR TITLE
update(minify): v9 update and missing exports added

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- v9 bump
- add missing methods exports on the `minfify` itself
- tests amended
- structure aligned with origin module

https://github.com/coderaiser/minify/blob/e76f6790b24a4ca5cc294dd658b1110adb829cc3/lib/minify.js#L34

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## minify ([<kbd>unpkg</kbd>](https://unpkg.com/browse/minify@latest/))
was missing the following properties:
1. minify
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against df3ea5d252e5569ec543be5534e940f484570157
</p>

**Review by joshuajeschek — APPROVED** [review]
👍

**Comment by peterblazejewicz** [comment]
@joshuajeschek sorry to bother you, template literal restriction is not yet for prime-time, thx!

**Comment by joshuajeschek** [comment]
just ping me when I should take another look :)

**Comment by peterblazejewicz** [comment]
It's ready to go, just without string template literals (yet)

**Review by andrewbranch — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@andrewbranch sorry to mark you directly. I've missed native imports (`{....}.js`). Once noticed, the OTHER_FILES etc is no longer required, sorry for the pita!

**Review by joshuajeschek — APPROVED** [review]
👍

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
