### PR TITLE
[cote] add error argument to responder on callback for cote package 

### PR DESCRIPTION
**Pull request by roblabat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR add typings for the error argument on the Responder.on callback as it is used in this workshop from the author https://github.com/dashersw/cote-workshop.

It seem's seems the documentation of this package is not up to date on this point.

### CODE REVIEW

**Comment by roblabat** [comment]
I made a small repo to illustrate that behavior: [coteTypingsExemple](https://github.com/roblabat/coteTypingsExemple)

As you can see the problem comes when you want to mix callback written responder with promise based requester. Most of the time you don't want to do that but as the package is for microservices architecture you can have separate teams working on separate microservices and they could use different patterns that could break the communication between services. I'm currently discussing with dashersw for updating the documentation (see [#124](https://github.com/dashersw/cote/pull/124)).

I've got an point to submit to you:
I saw you use the Event type for arguments passed to responder function and on many other similar places. I do not completely understand that choice. Effectively Event have a type property that perfectly match cote pattern that find the write method using that type property. But cote also allows use to pass all fields we want in this object as arguments to the method, shouldn't we consider using a custom type that can handle all properties ? 
It would looks something like that: 
class Arguments {
    type: string;
    [key: string]: any;
}

**Comment by makepost** [comment]
Does changing the callback types in index.d.ts both for Requester and Responder, including the one where you're adding the error, to `(...result: any[]) => void)`, achieve what you suggest?

**Comment by roblabat** [comment]
Effectively I think that would achieve it and I think that an even better solution than mine.

I will make a new commit on this PR with that solution.

It would be great if you had time to look at my other point on the use of the Event type that maybe doesn't match some places where it's used. I'll update my exemple repository with new exemples showing my problems with Event on tomorrow right after my commit on the callbacks arguments.

**Comment by roblabat** [comment]
As discussed I updated my [coteTypingsExemple](https://github.com/roblabat/coteTypingsExemple) repo to show my issue on the Event type, I also updated my PR with a fixe for that.

I'm less sure than yesterday on the `(...result: any[]) => void)` solution. Effectively the discussion on my cote PR [#124](https://github.com/dashersw/cote/pull/124) seems to lead to the adoption of the '(error, result?) => void' signature in the doc. I would suggest to wait the conclusion of this PR and then adopte same convention as the doc.

**Comment by makepost** [comment]
Excellent, I see the upstream has decided to make the two-argument, error-first callback the standard, so am going to approve this part of the change. However, I'll have to ask you to undo the Event type edit, because it's generic already and helps enforce event type safety. Your example should look like this:

```ts
interface IHello {
  args: string;
  type: "hello";
}

responder.on("hello", (event: IHello, done) => {
  done(null, event.args);
});

// Also works:
responder.on<IHello>("hello", (event, done) => {
  done(null, event.args);
});

// Untyped event is most likely an accident, TypeScript helps catch early:
responder.on("hello", (event, done) => {
  done(null, event.args); // Intentionally an error, other app events don't have `.args`
});
```

**Comment by roblabat** [comment]
I'm not completely agree with this approach on Event type but that's maybe not the best place to discuss that. I will revert my changes for that to allow you to merge this PR and open an other one to discuss this new point.

**Comment by roblabat** [comment]
I also made a last commit for the send method of requester that I forgot updating the callback signature

**Review by nykula — APPROVED** [review]

**Pull request merged**
