### PR TITLE
[facebook-js-sdk] Updated types to SDK version 3.1

### PR DESCRIPTION
**Pull request by fluidsonic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.facebook.com/docs/javascript/reference/v3.1
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

## Changes

- changed version from 2.8 to 3.1 (current)
- added `FB.ui(ShareOpenGraphDialogParams, …)`
- added `FB.ui(CreateOfferDialogParams, …)`
- added `FB.ui(LeadgenDialogParams, …)`
- added `FB.ui(InstantExperiencesAdsDialogParams, …)`
- added `FB.ui(InstantExperiencesPreviewDialogParams, …)`
- added `FB.ui(CollectionAdsDialogParams, …)`
- added `PayDialogParams.pricepoint_id`
- added `InitParams.autoLogAppEvents` (documented only in the [Quickstart](https://developers.facebook.com/docs/javascript/quickstart/))
- added `DialogResponse` base interface
- removed `ShareDialogParams.picture`
- made most callbacks optional
- fixed parameter types of `FB.login()`
- fixed type of `GameRequestDialogParams.data` and `.title`
- fixed type of `PayDialogResponse.request_id`
- fixed type of `StatusResponse.status`
- fixed types of `PaymentsLiteDialogResponse` properties
- fixed return type of `FB.getAuthResponse()`
- fixed JSDoc issues

### CODE REVIEW

**Review by amritk — APPROVED** [review]

**Comment by MayhemYDG** [comment]
@fluidsonic 
Any specific reason why `auth_type` is restricted to `'rerequest'` instead of `'rerequest' | 'reauthenticate' | 'reauthorize'` as the docs would suggest?
https://developers.facebook.com/docs/reference/javascript/FB.login/v3.2

**Comment by fluidsonic** [comment]
@MayhemYDG nope, oversight on my side. Will fix now.

**Comment by MayhemYDG** [comment]
Thanks!

**Comment by fluidsonic** [comment]
@MayhemYDG will be fixed with #33613

**Pull request merged**
