### PR TITLE
[@mailchimp/mailchimp-transactional] Add missing interfaces

### PR DESCRIPTION
**Pull request by BendingBender**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mailchimp.com/developer/transactional/api/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Tobbe** [comment]
@BendingBender Thanks for this massive update to the mailchimp types! 

If it's not too much to ask, could you please also add `mailchimp.ping.get()` and `mailchimp.lists.getAllLists()`. Thank you!

**Comment by BendingBender** [comment]
@Tobbe There are no `mailchimp.ping.get()` and `mailchimp.lists.xyz()` in this package.... Neither are they documented on the mailchimp API pages.... Not sure what you want me to do.

**Comment by Tobbe** [comment]
@BendingBender Sorry dude! Wrong package 🙈 They're in mailchimp-marketing

**Review by PieterScheffers — APPROVED** [review]

**Comment by PieterScheffers** [comment]
@BendingBender Wow! This is a massive update. Nice work!

**Comment by BendingBender** [comment]
Ready to merge

**Pull request merged**
