### PR TITLE
feat(carbon-components-react): add 'align' to Accordion

### PR DESCRIPTION
**Pull request by maniax89**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/pull/4754
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. -> still many other changes needed
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by sgregoire** [comment]
Hello, it looks like the `align` prop has been introduced in Carbon 9.

See here the definitions of carbon 7: https://github.com/carbon-design-system/carbon/blob/v10.7.4/packages/react/src/components/Accordion/Accordion.js

Please note that the support of Carbon 9 will be merged soon: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42126

**Comment by maniax89** [comment]
Does that include all of carbon 9?

**Comment by uniqueiniquity** [comment]
Closing in favor of #42126. Please make sure this change is included there.

**Comment by maniax89** [comment]
That PR hasn't seen activity in 2 months :confused:

**Comment by sgregoire** [comment]
> Does that include all of carbon 9?

I'm not sure all of Carbon 9 is supported, but they do not change their API so often.

**Comment by sgregoire** [comment]
> That PR hasn't seen activity in 2 months 😕

Since your PR is for Carbon 9 (or newer), I strongly encourage you to fork his PR, and verify that it's working well for you, and then create a new PR.

**Pull request closed without merging**
