### PR TITLE
Turn on first two eslint rules

### PR DESCRIPTION
**Pull request by sandersn**
- Turn on the first two eslint rules that shipped with https://github.com/microsoft/DefinitelyTyped-tools/releases/tag/v0.0.120
- Add .eslintrc.json files to disable the new rules in the same places where the old rules are disabled.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## firmata ([<kbd>unpkg</kbd>](https://unpkg.com/browse/firmata@latest/))
was missing the following properties:
1. Board
1. SYSEX_RESPONSE
1. MIDI_RESPONSE
1. test
## ftpd ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ftpd@latest/))
was missing the following properties:
1. LOG_LEVELS
## mysql ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mysql@latest/))
was missing the following properties:
1. createQuery
## powerbi-visuals-tools ([<kbd>unpkg</kbd>](https://unpkg.com/browse/powerbi-visuals-tools@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'powerbi-visuals-tools'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
1. createVisualPackage
1. loadVisualPackage
1. installPackages
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5a739c641c21c1e8c07d08b3b16d9061e80b4636
</p>

**Comment by thw0rted** [comment]
Hi @sandersn , it looks like enabling these rules causes errors in vanilla (non-dtslint) eslint.  The eslint plugin in VSCode gets confused:

image

Does dtslint provide a `plugin` for `eslintrc` or something that would enable vanilla eslint to find those rules?

**Comment by sandersn** [comment]
@thw0rted can you open a separate issue? I don't like lint rules in my editor (and don't usually use VS Code to boot), so I'll have to put some work in to repro and fix that problem.

**Comment by thw0rted** [comment]
Done, please see #61764 .

**Pull request merged**
