### PR TITLE
Updated typings for fullcalendar

### PR DESCRIPTION
**Pull request by DxCx**
Hi,
i've aligned abit fullCalendar typings,
it's still not perfect, but much closer to the documentation.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  
  [BusinessHours](http://fullcalendar.io/docs/display/businessHours/)
  [eventLimit](http://fullcalendar.io/docs/display/eventLimit/)
  [eventConstraint](http://fullcalendar.io/docs/event_ui/eventConstraint/)
  [EventObject](http://fullcalendar.io/docs/event_data/Event_Object/)
  [refetchEventSources](http://fullcalendar.io/docs/event_data/refetchEventSources/)
- it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Can you add tests for the changes you made. Any you probably need to pull in the most recent changes from types-2.0

**Comment by DxCx** [comment]
Yep, will do..

**Comment by DxCx** [comment]
Hi @paulvanbrenk,
I've already had all changes from types-2.0 branch,
Also, I've added tests for the fields i've added/adjusted.
locally (before and after the tests) dt --changes passes.
looks like the branch types-2.0 is currently broken (tests-wise)
Travis shows the tests that are failing are not related to fullCalendar changes..

**Comment by paulvanbrenk** [comment]
LGTM, waiting on the tests to complete

**Comment by DxCx** [comment]
@paulvanbrenk , test looks good now :) (Altough i'm not sure how come, becuase i didn't do any further merge, was that a problem on travis machine?)

**Comment by paulvanbrenk** [comment]
yep, there was a casing issue

**Pull request merged**
