### PR TITLE
Fixed angularjs promises then signature.

### PR DESCRIPTION
**Pull request by marcogrcr**
Pull request #966 attempted to implement an overload to `angular.IPromise<T>.then(...)` to return `angular.IHttpPromise<T>` instances:
- a0b3d5f added an overload as follows:

``` ts
then<TResult>(successCallback: (promiseValue: T) => IHttpPromise<TResult>, errorCallback?: (reason: any) => any): IHttpPromise<TResult>;
```

However this change caused compilation errors.
- 8c6037d fixed this by changing the overload as follows:

``` ts
then<TResult>(successCallback: (promiseValue: T) => IHttpPromise<TResult>, errorCallback?: (reason: any) => any): IPromise<TResult>;
```

This change, effectively reversed the intent of the pull request.

When pull request #3488 introduced union types. This code started to fail in my **TypeScript 1.5.3** setup:

``` ts
var promise: angular.IPromise<string>;
var httpPromise: angular.IHttpPromise<number>;

var result = promise.then(result => {
    return httpPromise;
});
```

The returned error is:

```
Error   23  The type argument for type parameter 'TResult' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'IHttpPromiseCallbackArg<number>' is not a valid type argument because it is not a supertype of candidate 'number'.
```

`angular.IPromise<T>.then(...): angular.IHttpPromise<T>` never really got implemented, and shouldn't be (according to the deprecation notice in https://docs.angularjs.org/api/ng/service/$http#get).

### CODE REVIEW

**Comment by vvakame** [comment]
@marcogrcr LGTM. please resolve conflict.

**Comment by marcogrcr** [comment]
@vvakame Done!

**Comment by marcogrcr** [comment]
@vvakame CI build failed, but it's unrelated to the files in this pull-request.

**Comment by vvakame** [comment]
okey dokey

**Pull request merged**
