### PR TITLE
Added `react-overlays` typings

### PR DESCRIPTION
**Pull request by aaronbeall**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them: https://github.com/react-bootstrap/react-overlays/issues/126
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/react-bootstrap/react-overlays
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by aaronbeall** [comment]
@vvakame Will do... seems quite a bit has changed, each dir should have a `tsconfig.json` now and not use `/// <reference>`?

**Comment by aaronbeall** [comment]
Done: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12676

**Comment by paulvanbrenk** [comment]
@aaronbeall thanks for converting the PR to typings-2.0. Closing this one.

**Pull request closed without merging**
