### PR TITLE
[args] fix command options argument typings

### PR DESCRIPTION
**Pull request by jantimon**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/leo/args#commandname-description-init-aliases 
> the "options" argument [...] will contain the options registered within the current binary

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/leo/args#configuration
all configuration options are optional

The current typings are reusing a different type which is only usefull for the `parse` function `options` argument.  
However the `command` function `options` argument is similar to the return value of the `parse` function.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## args ([<kbd>unpkg</kbd>](https://unpkg.com/browse/args@latest/))
was missing the following properties:
1. details
1. config
1. printMainColor
1. printSubColor
1. Args
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e2586c94550fd004d2090826f695e91d54e2d3fe
</p>

**Comment by jantimon** [comment]
It's ready to merge :)

@Slessi what do you think?

**Comment by jantimon** [comment]
Re-ping @Slessi

**Review by gabritto — APPROVED** [review]

**Comment by jantimon** [comment]
@typescript-bot please reopen

**Comment by jantimon** [comment]
moved to #65776

**Comment by jantimon** [comment]
@gabritto - if you have time please approve the pr once again in the follow up pr :)

**Pull request closed without merging**
