### PR TITLE
[redis] fix BRPOPLPUSH callback

### PR DESCRIPTION
**Pull request by iamolegga**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://redis.io/commands/brpoplpush#return-value](https://redis.io/commands/brpoplpush#return-value)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by 43081j** [comment]
can you explain the change a little? why did we go from `[string, string]` to `string`?

**Comment by iamolegga** [comment]
You can check reply value of `brpoplpush` command

run docker with redis
```sh
$ docker run --name redis-test -p 6379:6379 -d redis
$ docker exec -it redis-test bash
root@12b3b2ad43bd:/data# redis-cli
127.0.0.1:6379> rpush list value
(integer) 1
```
our js code
```js
require('redis').createClient({ port: 6379 })
  .brpoplpush('list', 'list2', 0, (er, reply) => {
    console.log(typeof reply);
    console.log(reply);
  });
```
So you can see that it's not `[string, string]` but `string` in case when you get something
```sh
string
value
```
and `null` when not
```sh
object
null
```

**Comment by iamolegga** [comment]
So, are we going to merge it?

**Comment by 43081j** [comment]
Yup it looks good to me, the redis docs clearly state it should be a bulk string.

**Review by 43081j — APPROVED** [review]

**Pull request merged**
