### PR TITLE
fix: add allowEmptyInput option to LinterOptions

### PR DESCRIPTION
**Pull request by xboy2012**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L53
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by xboy2012** [comment]
I noticed that two checks above failed.
It's not related to the changes I made, but might be a common problem, which I also see in the other PRs.

**Review by bmatcuk — APPROVED** [review]
👍

**Comment by 43081j** [comment]
keep in mind, stylelint has its own types now AFAIK:
https://github.com/stylelint/stylelint/blob/master/types/stylelint/index.d.ts

though im not entirely sure how they work / how you get at them. since their package.json doesn't define it and their `main` doesn't have a `main.d.ts` equivalent.

**Comment by xboy2012** [comment]
> keep in mind, stylelint has its own types now AFAIK:
> https://github.com/stylelint/stylelint/blob/master/types/stylelint/index.d.ts
> 
> though im not entirely sure how they work / how you get at them. since their package.json doesn't define it and their `main` doesn't have a `main.d.ts` equivalent.

I see that, but the author of stylelint seems to ONLY use the types in development. The code base is not typescript, just some .d.ts files. As you say, the types are not exported yet.

**Comment by xboy2012** [comment]
I noticed that two checks above failed.
It's not related to the changes I made, but might be a common problem, which I also see in the other PRs.

Anyone helps?

**Comment by 43081j** [comment]
@sandersn or someone may know since it looks unrelated to the change

**Comment by sandersn** [comment]
stylelint indirectly depends on @nodelib/fs.walk, which ships its own types that require Typescript 3.8 or higher. I guess that it's a fairly recent addition to stylelint's dependency tree.

You can play with package.json trying to find versions of stylelint dependencies that also work with TS 3.7, but it's a lot easier to change to requiring `// TypeScript Version: 3.8` in the header of index.d.ts.

3.7 will go out of DT's support window in 3 months anyway, so I think that's the right solution.

**Review by 43081j — APPROVED** [review]

**Comment by xboy2012** [comment]
Ready to merge

**Pull request merged**
