### PR TITLE
Update types/jsrender definitions

### PR DESCRIPTION
**Pull request by BorisMoore**
Updates to the types/jsrender type definitions and test file

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. 
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- n/a

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.jsviews.com/#jsrapi and https://github.com/BorisMoore/jsrender
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- n/a

### CODE REVIEW

**Comment by jessetrinity** [comment]
@BorisMoore is @zakki no longer maintaining this?

**Comment by BorisMoore** [comment]
Hi @jessetrinity - I am the owner and maintainer of [JsRender](https://github.com/BorisMoore/jsrender). @zakki contributed some TypeScript definitions (for a small subset of the JsRender and JsObservable APIs). I don't know whether he is interested in an ongoing maintainer role for the definitions. (My guess is not... I emailed him to let him know of my updated definitions, and he responded, but did not mention a wish to maintain, and made no comments on the code. I also pinged him on whether he wanted to review, but didn't hear back).

BTW I also have a set of definitions for [JsViews](https://github.com/BorisMoore/jsviews) (which depends on JsRender). Once the JsRender definitions are merged I will submit as a PR for a new definition, at types/jsviews.  (See https://www.jsviews.com/)

**Comment by jessetrinity** [comment]
@BorisMoore I certainly don't want to keep blocking you, especially with your great contribution here, but it might be preferable to allow people to remove themselves if they no longer wish to receive notifications.

**Comment by zakki** [comment]
This looks good to me. 
I'm not using JsRender, and I don't know about new APIs.

**Comment by jessetrinity** [comment]
Awesome. Thanks!

**Comment by BorisMoore** [comment]
Excellent, thank you @jessetrinity and @zakki!

**Pull request merged**
