### PR TITLE
js-yaml: Optional `construct` second argument for the tag type.

### PR DESCRIPTION
**Pull request by Zoramite**
Used as a way to resolve unknown tags in js-yaml.

`construct()` can be [called with a second argument](https://github.com/nodeca/js-yaml/blob/ab31bba6b41f58390f431123ffec5031b986edf5/lib/loader.js#L1531).
Also shows up in the examples as a way to [handle unknown tags](https://github.com/nodeca/js-yaml/blob/master/examples/handle_unknown_types.js#L29).

- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by Zoramite** [comment]
Was not sure if it was best to do it as an optional argument, or as a separate option for the value.

Ex: `(data: any, type?: string) => any` vs `((data: any) => any) | ((data: any, type: string) => any)`

**Comment by peterblazejewicz** [comment]
@Zoramite where is the second argument used? I cannot see this in the example code linked (those are IMO
just either list of ints or keyed object as a single param)

**Comment by Zoramite** [comment]
@peterblazejewicz sorry for the confusion, I accidentally pasted the wrong link. The example is in the [unknown tag example](https://github.com/nodeca/js-yaml/blob/master/examples/handle_unknown_types.js#L29).

**Review by orta — APPROVED** [review]
Looks right according to https://github.com/nodeca/js-yaml/blob/master/examples/handle_unknown_types.js#L29

**Comment by Zoramite** [comment]
Ready to merge

**Pull request merged**
