### PR TITLE
[@types/node] Use ExecException for child_process.execFile()

### PR DESCRIPTION
**Pull request by thinca**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<following>>

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27708 changed type of error in `child_process.exec`, but `child_process.execFile` should be also change.
[`exec` just calls `execFile`](https://github.com/nodejs/node/blob/147317f60c41acdd934c6da3868f442e05226e37/lib/child_process.js#L149-L154).  They have same callbacks.

### CODE REVIEW

**Comment by galkin** [comment]
@thinca, could you also make changes at Node.js v10?

**Comment by thinca** [comment]
@galkin OK.  I updted with force-pushed.  What about v11?

**Comment by galkin** [comment]
@thinca, v11 is EOL, so we don't update @types for such versions.

**Review by galkin — APPROVED** [review]
Thank you for your work!

**Comment by thinca** [comment]
Thank you for the review 😃

**Comment by thinca** [comment]
CI seems to have failed regardless of this change.
I force-pushed a new commit without change to re-run the CI.

**Comment by orta** [comment]
Hrm, I'm not sold on the accuracy of the perf hit in the stats above - given that both files have the same changes and the reported identifiers look pretty un-related. Merging.

**Pull request merged**
