### PR TITLE
Updated @types/offscreencanvas, added missing definitions and tests

### PR DESCRIPTION
**Pull request by ova2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33519
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ova2** [comment]
After almost three weeks nobody has reviewed this PR :-( This is disappointing. We need this improved TS defintion because OffscreenCanvas is Transferable. Other libraries suffer from that, look e.g. https://github.com/developit/workerize/issues/36 The updated definition will fix all these issues.

Thanks in advance.

**Review by kayahr — CHANGES_REQUESTED** [review]
Sorry about the late review. Maybe I had looked at it sooner if you haven't unnecessarily moved stuff around and changed quote characters to meet your personal preferences ;-) Smaller Diffs are always nicer to review.

`npm test` fails here because of an unknown `GlobalFetch` in the Window interface. Looks like this type is no longer available in current TypeScript 3.6.0-dev Snapshot.

**Comment by ova2** [comment]
@kayahr TypeScript 3.6.0-dev Snapshot is not for production (not released yet). Why do you use a snapshot version? But well, I've removed `GlobalFetch` from `Window` and updated this PR.

Sorry for moved stuff around and changed quote characters. I've replaced single quotes by double quotes again. Thanks for review in advance.

**Review by kayahr — APPROVED** [review]

**Comment by ova2** [comment]
Thanks for approvement! How to merge this PR now?

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
