### PR TITLE
Add @babel/types

### PR DESCRIPTION
**Pull request by ForbesLindesay**
This uses a script to auto-generate most of the typescript defintion because babel-types provide various data to help you introspect the schema of babel. It includes a number of helper methods and properties not present in the definition for `babel-types`.  The auto-generated test case ensures that there is a type for every exported property of @babel/types

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
@mohsen1 @yortus @baxtersa @marvinhagemeister @bcherny - Maybe one of you could review this?

**Comment by DanielRosenwasser** [comment]
Hey @ForbesLindesay, I guess I don't understand exactly what this adds on top of https://github.com/babel/babel/tree/master/packages/babel-types which provides its own types. Additionally, without some path mapping, this will get shadowed by the `@babel/types` itself. So could you give some more specifics here?

CC @andy-ms

**Comment by ForbesLindesay** [comment]
I didn't see that they'd added their own types (they're new).  This was a waste of time then :(

**Comment by DanielRosenwasser** [comment]
Sorry about that. I've been in similar situations, but I can tell you that the PR and the intent is still appreciated!

**Pull request closed without merging**
