### PR TITLE
feat: add @adobe/aio-lib-analytics

### PR DESCRIPTION
**Pull request by bodinsamuel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by bodinsamuel** [comment]
I don't understand the error can somebody help me?

**Comment by bodinsamuel** [comment]
Hey @sandersn 
Sorry to bother you, I can't seems to make this pass, looks like I need the package to be installed but other def does not have this requirement. Can you provide some guidance? ☺️

**Comment by sandersn** [comment]
You need a `paths` redirect in the tsconfig for scoped packages, since their names are mangled in DT. Here's an example from `@absinthe/socket`:

```
        "paths": {
            "@absinthe/*": ["absinthe__*"]
        }
```

**Comment by bodinsamuel** [comment]
Amazing, thanks a lot of for taking the time 🙏🏻 ❤️

**Pull request merged**
