### PR TITLE
Tedious: The "Error.code" property should be a string

### PR DESCRIPTION
**Pull request by asztal**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tediousjs/tedious/search?utf8=%E2%9C%93&q=ETIMEOUT&type=
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by rogierschouten** [comment]
:+1:

**Comment by cjthompson** [comment]
The source code actually doesn't indicate at all what type `code` is expected to be and there doesn't appear to be any code that assumes it is of a certain type.

If one wants to use the `RequestError` class in their own code, I don't see any reason that `code` must be a string.

Alternatively, if there is a limited number of known error codes, then an enum would be a better type to use than string.

**Comment by rogierschouten** [comment]
I did a quick check and only found strings being put in. Did you find other values being used? I'm curious because I think I remember them being numbers at some point in time

**Comment by cjthompson** [comment]
I have been using RequestError in unit tests to simulate database error responses and I seem to recall the "code" property could be a value that comes from the actual database error response code.  However, digging through the code today I couldn't find where that was happening. 

Since this has already been merged, I'm okay leaving it as-is.  We can always submit a new PR in the future if we find a reason to change it again.

**Comment by asztal** [comment]
I too only found places where `code` is a string. If the error code is `EREQUEST` then there will also be a `number` property with the SQL Server error number, along with `state`, `procName`, `lineNumber`, and others -- I was going to look at updating the types to include these properties at a later date when I have the time, since my project uses them extensively.

image

https://github.com/tediousjs/tedious/blob/master/src/connection.js#L355

I don't know if it's been this way forever, but as far as I know tedious more or less follows semantic versioning and hopefully wouldn't have released a minor version that changes something like that.

**Pull request merged**
