### PR TITLE
add protected property OutgoingMessage._header to http

### PR DESCRIPTION
**Pull request by SachinShekhar**
Useful when extending `http.ServerResponse`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/b560645d6b0a4bed58ef9a13ce7ac70d92283626/lib/_http_outgoing.js#L546
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Is this considered part of the API? It's not in the [docs](https://nodejs.org/dist/latest-v15.x/docs/api/http.html).

**Comment by SachinShekhar** [comment]
@SimonSchick Given the way JavaScript operates, why not (so long as it's exported from the module)? Actually, we should do it for all other internal properties for better type-safety. In this particular case of `_header`, it's supposed to be `string`. First, I need to declare this variable which is wrong in itself. Second, if I declare it to be of `boolean` type, TS compiler won't complain & beg for runtime error.

Docs is meant for end-users who don't need to extend `ServerResponse`. It's right there in the [source code](https://github.com/nodejs/node/blob/b560645d6b0a4bed58ef9a13ce7ac70d92283626/lib/_http_outgoing.js#L546) & can be verified by console logging `ServerResponse` object.

**Comment by SachinShekhar** [comment]
@typescript-bot CI Test failures aren't introduced by this PR.

**Comment by SimonSchick** [comment]
We've historically denied introducing undocumented APIs to avoid a false sense of stability, I'm not sure where the consensus is right now but I'd suggest you instead do something like this:

```ts
interface ServerResponsePrivate {
  _header: string;
}

// or similar
function assertServerResponsePrivate(res: ServerResponse): res is ServerResponsePrivate {
  if (!('_header' in res) || typeof res._header !== 'string') throw new AssertionError('Missing internal property _header');
}

class MyResponse extends ServerResponse {
 myMethod() {
   assertServerResponsePrivate(this):
   this._header = 'foo';
}
```

This will ensure that things will fail if the node team ever decides to change this field.

**Comment by SachinShekhar** [comment]
@SimonSchick Runtime assertion is not the point (that's actually foolish if you know that it's always going to be string).

The main point is doing it Typescript way (block the user before the code runs).

**Comment by dnalborczyk** [comment]
I think we should not add this to the type definitions. it's meant to be _class private_ and is also _deprecated_:

https://nodejs.org/dist/latest-v15.x/docs/api/deprecations.html#DEP0066

**Pull request closed without merging**
