### PR TITLE
Adobe ExtendScript types

### PR DESCRIPTION
**Pull request by pravdomil**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by pravdomil** [comment]
you are fixing! not me

**Comment by mhegazy** [comment]
Please specify values for your "lib". currentlly you are building with no default library. possible values can be `"es5", "es2015"`

**Comment by vespakoen** [comment]
The added packages are for use in Adobe software, which uses their own implementation of JavaScript, the JavaScript types are also defined in a package included in this PR.

See https://github.com/Microsoft/TypeScript/issues/3930
We need to bring in some core types to please the TS compiler

**Comment by ericdrobinson** [comment]
@mhegazy ExtendScript is based on ECMAScript 3 to the extent that you could do a passable job working in it with a [basic ES3 library](https://github.com/Microsoft/TypeScript/issues/2410#issuecomment-298097084). This PR actually does a more comprehensive job of providing API definitions (based upon Adobe's own documentation). I called it out specifically [here](https://github.com/Microsoft/TypeScript/issues/19183#issuecomment-360999149) as well (see the "_A 'Complex' Use Case_" section for details).

Can someone explain what the `IArguments` interface is for? Does it define the `arguments` ECMAScript Object available within the context of any function?

**Pull request closed without merging**
