### PR TITLE
feat(react-dependents): update to TS 2.8 (part 2 of 2)

### PR DESCRIPTION
**Pull request by ferdaber**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This is the follow up to this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27482
Counterpart to this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27743

### CODE REVIEW

**Comment by iRoachie** [comment]
Shouldn't we just go 3.0? Especially since it just added support for `defaultProps`?
https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

**Comment by ferdaber** [comment]
We wouldn't need to set the requirement itself to 3.0. Consumers of the package that have TS 3.0 will get the benefits of the library managed attributes, but we want those that haven't upgraded to still be able to use them. The minimum requirement is 2.8 since the changes require conditional types.

**Review by jacobbaskin — APPROVED** [review]

**Comment by ferdaber** [comment]
Unsure why Travis is failing on `redux-auth-wrapper`, looks like the dependency is correctly set in `package.json`, and I'm locally seeing `redux` being installed in that package's `node_modules` directory.

**Comment by ferdaber** [comment]
@johnnyreilly this one is now good to go.

**Review by pocesar — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by gyzerok** [comment]
Hi @johnnyreilly!

Can you, please, explain how I ended up being mentioned here? I was never maintainer of Expo. It feels a bit like spam to me. Maybe there is some bug with bot pings?

**Comment by johnnyreilly** [comment]
I'm not sure - my guess is you're mentioned somewhere in here.  I'm not au fait with the mechanism though

**Comment by ferdaber** [comment]
@gyzerok You may have been mentioned here because I had to update over 175 distinct packages in this PR, so you may be a maintainer of one of them.

**Pull request merged**
