### PR TITLE
chai-enzyme add .type(func) typing

### PR DESCRIPTION
**Pull request by sir-marc**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/producthunt/chai-enzyme#typefunc
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Please fix conflicts.

**Comment by aozgaa** [comment]
Can you 👍 or 👎 , @asvetliakov?

**Comment by asvetliakov** [comment]
LGTM 👍

**Comment by minestarks** [comment]
@sir-marc Could you fix the merge conflicts so I can merge? 

This PR is rather stale so I plan to close it out in a few days if no activity.

**Comment by sir-marc** [comment]
As i am in holiday, it may take a while for me to et chance to fix it

**Comment by minestarks** [comment]
No problem, I ended up merging since it was simple.

**Pull request merged**
