### PR TITLE
[promise.allsettled] Add new type declarations

### PR DESCRIPTION
**Pull request by jurca**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Note: The author of the project is considering adding types into the package itself, but without rewriting the project in TypeScript. More info available [here](https://github.com/ljharb/Promise.allSettled/pull/2).

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by vitch** [comment]
Can you provide an example of using these types in a typescript codebase?

I may be missing something obvious because I'm pretty new to TypeScript but I'm trying like this:

```typescript
import * as allSettled from 'promise.allsettled';

// ...

const results =  await allSettled(loadVertexCalls);
```

But the return type of `allSettled` is being inferred as `Promise<Vertex>[]` (the same type as `loadVertexCalls`). I was expecting it to be `Promise<PromiseResultTuple<Vertex>>[]`.

**Comment by epfremmer** [comment]
It looks like the return type in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36314/files#diff-3823403ef03734f7b9743ca98a31fd93R8 might need to change

I think it should be something along the lines of:
```
declare function allSettled<T>(iterable: Iterable<T>): Promise<PromiseResultTuple<[T, ...T[]]>>;
```

**Comment by jurca** [comment]
@vitch @epfremmer 

Thank you for pointing this out, I sincerely apologize for this mishap. I focused mostly on types for tuples, and as a result I overlooked this issue.

I have submitted a new PR fixing this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36815/

**Comment by jurca** [comment]
@vitch @epfremmer A new version fixing this [has been published](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36815#issuecomment-510684593) (@types/promise.allsettled@1.0.1)

**Comment by vitch** [comment]
Thank you very much @jurca and sorry for the slow reply!

**Comment by jurca** [comment]
@vitch You are very much welcome :), thanks for pointing out this issue!

**Pull request merged**
