### PR TITLE
[react-native] Fix NetInfo module type.

### LINKED ISSUE #19605: @types/react-native Missing and Incorrect Types of React Native NetInfo Component
Delete please

### PR DESCRIPTION
**Pull request by timwangdev**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react-native/blob/master/Libraries/Network/NetInfo.js>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fix #19605

### CODE REVIEW

**Comment by timwangdev** [comment]
@alloy, Can you have a review? Thx

**Comment by timwangdev** [comment]
Also ping @huhuanming @iRoachie @kamal ...

**Review by iRoachie — APPROVED** [review]
LGTM 👍🏽

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Comment by DanielRosenwasser** [comment]
Thanks all!

**Pull request merged**
