### PR TITLE
[jsforce] Add typing for get-recent-items method

### PR DESCRIPTION
**Pull request by mcelearr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jsforce.github.io/jsforce/doc/connection.js.html#line1164
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by douglascayers** [comment]
Hi @mcelearr, thanks for the update. Would you please update `jsforce-tests.ts` to use your new method signatures. It’s not a “real” test, it just needs to call your methods so the test can ensure the signature is correct and catch if someone changes it later. Thanks

**Comment by mcelearr** [comment]
@douglascayers I added some tests as you recommended. My PR and a lot of others are failing CI due to an error installing typescript 3.7.

Any idea what we should do from here?

```
Installing to /home/vsts/.dts/typescript-installs/3.7...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@3.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2019-10-31T01_12_15_257Z-debug.log
```

**Comment by dolanmiu** [comment]
Can you fix the build errors?

**Comment by douglascayers** [comment]
Hi @mcelearr @dolanmiu, I believe the test failure "No matching version found for typescript@3.7" is not something we control but rather part of the typescript test infrastructure. We may need to wait for a project maintainer to resolve.

**Comment by douglascayers** [comment]
@mcelearr You can try pushing an empty commit to cause the tests to re-run.

`git commit -m "empty" --allow-empty && git push`

No guarantee that'll resolve the issue, but if the test failure was a fluke then retrying can't hurt.

**Review by dolanmiu — APPROVED** [review]

**Pull request merged**
