### PR TITLE
Fix trap suggestion

### PR DESCRIPTION
**Pull request by falsandtru**
Sorry, my previous fix has a problem!
jQuery official specification is wrong and trap!

> http://api.jquery.com/deferred.done/
> deferred.done( doneCallbacks [, doneCallbacks ] ) **Returns: Deferred**

Definable this code by official specification, but this code error occurs.

``` js
$.Deferred().done().resolve(); // done
$.Deferred().promise().done().resolve(); // runtime error
$.Deferred().then(function () { }).done().resolve(); // runtime error
```

This problem has not been covered by tests.
So I added a test.

Total diff.
https://github.com/borisyankov/DefinitelyTyped/compare/69bdfb0884020e41f17a1dd80ad4c77de2636874...falsandtru:jquery-deferred

### CODE REVIEW

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
Hi @falsandtru,

Could you remove the Q-tests.ts change please? Otherwise looks good.

**Comment by falsandtru** [comment]
Hi @johnnyreilly,

 Q-tests.ts error occurs.
https://travis-ci.org/borisyankov/DefinitelyTyped/builds/53436871

I can not solve the problem of JQueryGenericPromise without `Generic` additional type variable.

```ts
/**
 * Allows jQuery Promises to interop with non-jQuery promises
 */
interface JQueryGenericPromise<T, Generic> {
    /**
     * Add handlers to be called when the Deferred object is resolved, rejected, or still in progress.
     * 
     * @param doneFilter A function that is called when the Deferred is resolved.
     * @param failFilter An optional function that is called when the Deferred is rejected.
     */
    then<U>(doneFilter: (value: T, ...values: any[]) => U|JQueryGenericPromise<U, Generic>, failFilter?: (...reasons: any[]) => U|JQueryGenericPromise<U, Generic>, progressFilter?: (...progression: any[]) => any): JQueryGenericPromise<U, Generic>;
}

/**
 * Allows jQuery Promises to interop with non-jQuery promises
 */
interface JQueryDeferredSubset<T> {
    /**
     * Add handlers to be called when the Deferred object is resolved, rejected, or still in progress.
     * 
     * @param doneFilter A function that is called when the Deferred is resolved.
     * @param failFilter An optional function that is called when the Deferred is rejected.
     */
    then<U>(doneFilter: (value: T, ...values: any[]) => U|JQueryPromise<U>, failFilter?: (...reasons: any[]) => U|JQueryPromise<U>, progressFilter?: (...progression: any[]) => any): JQueryPromise<U>;
    then<U, Generic>(doneFilter: (value: T, ...values: any[]) => U|JQueryGenericPromise<U, Generic>, failFilter?: (...reasons: any[]) => U|JQueryGenericPromise<U, Generic>, progressFilter?: (...progression: any[]) => any): JQueryGenericPromise<U, Generic>;

    /**
     * Determine the current state of a Deferred object.
     */
    state(): string;

    // Deprecated - given no typings
    pipe(doneFilter?: (x: any) => any, failFilter?: (x: any) => any, progressFilter?: (x: any) => any): JQueryPromise<any>;
}
```

```ts
declare var arrayPromise: Q.IPromise<number[]>;
declare var stringPromise: Q.IPromise<string>;
declare function returnsNumPromise(text: string): Q.Promise<number>;

Q<number[]>(arrayPromise) // type specification required
    .then(arr => arr.join(','))
    .then<number>(returnsNumPromise) // requires specification
    .then(num => num.toFixed());

declare var jPromise: JQueryPromise<string>;

// if jQuery promises definition supported generics, this could be more interesting example
Q<string>(jPromise).then(str => str.split(','));
jPromise.then<number, void>(returnsNumPromise);
```

Compiler does not solve this pattern match. Perhaps it is a compiler bug.

```ts
    then<U>(doneFilter: (value: T, ...values: any[]) => U|JQueryPromise<U>, failFilter?: (...reasons: any[]) => U|JQueryPromise<U>, progressFilter?: (...progression: any[]) => any): JQueryPromise<U>;
    then<U>(doneFilter: (value: T, ...values: any[]) => U|JQueryGenericPromise<U>, failFilter?: (...reasons: any[]) => U|JQueryGenericPromise<U>, progressFilter?: (...progression: any[]) => any): JQueryGenericPromise<U>;
```

How should I do?
Is this jquery.d.ts comment really specification...?
>Allows jQuery Promises to interop with non-jQuery promises

**Comment by johnnyreilly** [comment]
Hi @falsandtru,

Yes Q deliberately support the interop with non-jQuery promises.  I know that the jQuery promise typings aren't in the greatest of shape (one of the reasons I use Q).  

Your change is probably the best course of action in the circumstances.  I'll merge.

Thanks,
John

**Pull request merged**
