### PR TITLE
doT: make index.d.ts export doT ot be imported in Typescript 2 and fix linter complaints

### PR DESCRIPTION
**Pull request by Dervol03**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.
- [x] pass the Travis CI test?

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  simply install doT to your node project and try to import it into typescript
- [x] Increase the version number in the header if appropriate.
  it's 1.1 now
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.
  The default tslint.json did the job pretty well

### CODE REVIEW

**Comment by Dervol03** [comment]
@ZombieHunter travis CI passed now

**Comment by andy-ms** [comment]
If you are linting please add `tslint.json`. Its presence determines whether the tester lints.

**Comment by Dervol03** [comment]
@andy-ms  added `tslint.json` to project and fixed further linting complaints

**Comment by andy-ms** [comment]
To expose as a module, try this:
```ts
// Type definitions for doT 1.1
// Project: https://github.com/olado/doT
// Definitions by: ZombieHunter <https://github.com/ZombieHunter>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export as namespace doT;

/** Version number */
export const version: string;

/** Default template settings */
export const templateSettings: TemplateSettings;

type RenderFunction = (...args: any[]) => string;

/** Compile template */
export function template(tmpl: string, c?: TemplateSettings, def?: {}): RenderFunction;

/** For express */
export function compile(tmpl: string, def?: {}): RenderFunction;

interface TemplateSettings {
	evaluate: RegExp;
	interpolate: RegExp;
	encode: RegExp;
	use: RegExp;
	useParams: RegExp;
	define: RegExp;
	defineParams: RegExp;
	conditional: RegExp;
	iterate: RegExp;
	varname: string;
	strip: boolean;
	append: boolean;
	selfcontained: boolean;
}

declare global {
	interface String {
		encodeHTML(): string;
	}
}
```

Also, are all of the properties of `TemplateSettings` mandatory? If not, make them optional, e.g. `evaluate?: RegExp;`. Currently there are no tests for `TemplateSettings` or for `encodeHTML`.
Also, should `selfcontained` be `selfContained`?

**Comment by Dervol03** [comment]
@andy-ms I'm not the author of these typings, I was just fixing the capability to import them to Typescript, as the compiler couldn't properly load them before.
Therefore, I didn't want to change any externally visible interfaces, to avoid breaking existing projects using it.
I definitely won't make that mistake again.

**Pull request closed without merging**
