### PR TITLE
[@types/match-sorter] Add support for string[] to the property callback syntax.

### PR DESCRIPTION
**Pull request by rriski**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kentcdodds/match-sorter/blob/master/README.md (see Property Callbacks)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by ChrisRu** [comment]
Thanks for your PR!

I'm assuming we will also need to support the key syntax then?

Because this would not pass the linter right now:
```js
const tea = [
    { tea: 'Earl Grey', alias: 'A' },
    { tea: 'Assam', alias: 'B' },
    { tea: 'Black', alias: 'C' }
];
matchSorter(tea, 'e', {
    keys: [{
        key: item => [item.alias, item.tea],
        minRanking: matchSorter.rankings.EQUAL
    }]
});
// [{tea: 'Earl Grey', alias 'A'}]
```

I'm proposing something like the following:
```ts
type KeyOptions<T> = string | ((item: T) => string);

type ExtendedKeyOptions<T> = { key: KeyOptions<T> } & (
    | { minRanking: number }
    | { maxRanking: number }
    | { threshold: number });

interface Options<T> {
    keys?: Array<KeyOptions<T> | ExtendedKeyOptions<T>>;
    threshold?: number;
    keepDiacritics?: boolean;
}
```

But I would very much like some feedback on this from @claasahl before passing.

**Review by claasahl — COMMENTED** [review]
Exactly my thought, @ChrisRu 😄

**Review by claasahl — CHANGES_REQUESTED** [review]
as discussed above

**Comment by rriski** [comment]
Updated the definitions and tests to reflect ChrisRu's suggestion.

**Review by claasahl — APPROVED** [review]
👍 thanks for your contribution @rriski

**Pull request merged**
