### PR TITLE
Electron v0.35

### PR DESCRIPTION
**Pull request by rhysd**
I updated type definitions for Electron v0.35 because @jedmao currently doesn't have any plan to fix it (answered in #7046).
## API changes for Electron v0.35

Electron v0.35 has some breaking changes in APIs.
1. `electron` module was defined and all previous modules were put in it.
2. Many options for `BrowserWindowOptions` are renamed because of change of naming style (e.g. `max-height` -> `maxHeight`
3. Renamed `Url` to `URL`

Only 3. was already reflected to previous `github-electron.d.ts`.

So I updated 1. and 2.
## Unite type definitions for renderer process and main process

I did this because `github-electron-main.d.ts` and `github-electron-renderer.d.ts` can't be used at the same time because `tsd.d.ts` includes both definition files and they collided each other.
So I decided to unite them to one `github-electron.d.ts` file.

I left `github-electron-renderer-tests.ts` and `github-electron-main-tests.ts` separated because actual codes for Electron app are separated like that.
## Defined interface for `webPreferences` options

I added this because `webPreferences` property of `BrowserWindowOptions` were defined as `any`.  And I moved some options from `BrowserWindowOptions` to `WebPreferences` because they had been moved in the past.

### CODE REVIEW

**Comment by rhysd** [comment]
I already used this change in some apps and they seem to work well.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7121/files?w=#diff-d9b14b562531db141c6ca0a7980b5e86R3
please add your name `Definitions by: ` in header.

**Comment by rhysd** [comment]
@vvakame 

OK, I will fixup the last commit.

**Comment by rhysd** [comment]
@vvakame Added!

**Comment by vvakame** [comment]
thanks mate! :+1:

**Comment by elisee** [comment]
The merging of main and renderer definitions is helpful bit it brings some issues of its own. When doing `require("electron")` on the renderer-side, TypeScript thinks `electron.BrowserWindow` exists but it's actually `undefined`. Maybe we'll just have to live with that?

Anyway, it seems `GitHubElectron.Remote` is missing a `BrowserWindow` property, as well as others. I've done a little digging and all "built-ins" are exposed on `electron.remote` automatically: https://github.com/atom/electron/search?utf8=%E2%9C%93&q=ATOM_BROWSER_GET_BUILTIN. 

I believe the exposed properties are taken from those places:
 * https://github.com/atom/electron/blob/master/atom/browser/api/lib/exports/electron.coffee
 * https://github.com/atom/electron/blob/master/atom/browser/api/lib/exports/electron.coffee

Don't have time to put together a pull request at the moment but hopefully this is helpful.

**Comment by rhysd** [comment]
@elisee 

Yes, some definitions are broken because maintenance is not active and Electron's APIs are frequetly changed.  So PR is very helpful.

**Comment by rhysd** [comment]
> When doing require("electron") on the renderer-side, TypeScript thinks electron.BrowserWindow

Yes, that's actually a pitfall because of API difference between main process and render process.  But I don't know the best practice to separate definitions.  Both process has the same name module `electron` but its contents is different between main and renderer.  TypeScript compiler can't know the current source is for main process or renderer process...

**Pull request merged**
