### PR TITLE
[seedrandom] refactor, remove all rules from tslint

### LINKED ISSUE #51456: seedrandom's types exported prngs require `new` keyword
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @EugeneZ, @kernhanda, @vvakame, @rakatyal

`seedrandom`'s additional prngs should normally be used as follows:

```typescript
import {alea} from "seedrandom";

const myRng = new alea("seed"); // notice the `new` keyword
```

it should NOT normally be used as:

```typescript
import {alea} from "seedrandom";

const myRng = alea("seed");
```

which seems to be the only way the TS types permit. It's not clear to me from the docs if `seedrandom` itself should require the `new` keyword.

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #51456

Documentation: https://github.com/davidbau/seedrandom

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
Why are there so many linter exceptions?

**Comment by kernhanda** [comment]
LGTM, but I have not kept up with v3 seedrandom changes.

**Comment by EugeneZ** [comment]
LGTM, thanks for updating this to v3!

**Review by EugeneZ — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Comment by punkeel** [comment]
With this change, did users lose the ability to refer to `prng`, the value returned by calls to `seedrandom()`, or am I missing something?
```
const x: ... = seedrandom();
```

**Comment by bmarotta** [comment]
Why do we have to types version (v2 folder)? How do I use the v2 version?

**Pull request merged**
