### PR TITLE
fix: `morgan` is not tightly coupled to `express`

### PR DESCRIPTION
**Pull request by SimenB**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/expressjs/morgan/blob/19a6aa5369220b522e9dac007975ee66b1c38283/README.md#expressconnect
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

As can be seen in the linked docs, the middleware works with plain `http` module as well, not just the `express`-enhanced ones.

One thing to not, is that `skip` etc will be called with the request passed in. So we might wanna do some sort of generic handling so people using `express` stuff (like `req.header('user-agent')`) can still do that if they're using `express`. I'm not sure how to best do that, though.

### CODE REVIEW

**Comment by pscanf** [comment]
The change makes sense and looks good to me. I wonder however, won't it break compatibility with code which expects to receive an `express.RequestHandler` and will now receive a `connect.NextHandleFunction`?

The signatures look close enough, so I'm guessing they're compatible, but I would add a test verifying it, something like:

```ts
express().use(morgan(/* options*/))
```

**Comment by SimenB** [comment]
@pscanf they are compatible (express is built on `connect`), so your example will work. However, as noted in the OP, people relying on express-specific extensions will get errors unless we're able to infer the correct type of request somehow.

I can add the plain express test, though 👍

**Comment by SimenB** [comment]
Also pushed a commit ditching `connect` - it's just `(req, res, callback)`, so it's enough to just use `node`'s types.

Still wanna fix inference though, so we don't break people relying on `express`'s extensions

**Comment by pscanf** [comment]
Ah sorry, I missed the comment, thought it was all PR boilerplate. 😅 

Yeah, your concern makes sense. Maybe generics defaulting to the native http types could be used. Though consumers would still break, the fix would be trivial.

**Comment by SimenB** [comment]
@pscanf pushed now. It felt pretty verbose, but maybe fine?

**Comment by SimenB** [comment]
Not sure what I can do about the `no-unnecessary-generics  Type parameter Response is used only once. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md` errors... I need it to be generic so I can do `extends` and default, don't I?

**Comment by SimenB** [comment]
@orta any ideas for what I can do about the linting errors? As mentioned, I _think_ I need the current syntax for `extends` and default type, no?

**Comment by pscanf** [comment]
> @pscanf pushed now. It felt pretty verbose, but maybe fine?

Yeah, it does look verbose, but it does take care of the problem I guess.

With generics the calling code looks like:

```ts
morgan<express.Request, express.Response>(
    (tokens, req, res) => {
        /* ... */
    },
    {
        skip: (req, res) => {
            /* ... */
        },
    }
);
```

Without generics:

```ts
morgan(
    (tokens, req: express.Request, res: express.Response) => {
        /* ... */
    },
    {
        skip: (req: express.Request, res: express.Response) => {
            /* ... */
        },
    }
);
```

Tbh I thought it'd be more of a pain without generics, but it doesn't seem to be. So if the version with generics is problematic (lint errors and such) the generics-less one seems adequate as well.

**Review by pscanf — APPROVED** [review]

**Comment by SimenB** [comment]
While that example isn't too bad, this better illustrates why generics are better:

```ts
express().use(morgan(
    (tokens, req: express.Request, res: express.Response) => {
        /* ... */
    },
    {
        skip: (req: express.Request, res: express.Response) => {
            /* ... */
        },
    }
));
```

vs
```ts

express().use(morgan(
    (tokens, req, res) => {
        /* ... */
    },
    {
        skip: (req, res) => {
            /* ... */
        },
    }
));
```

I think the linting rule is a bit too dumb, maybe we can just add an ignore comment of some sort?

**Comment by SimenB** [comment]
I wonder if we could just ignore the lint error?

**Comment by pscanf** [comment]
I mean, I understand the rationale behind the rule. The typing:

```ts
interface Options<Request extends http.IncomingMessage, Response extends http.ServerResponse> {
    skip?(req: Request, res: Response): boolean;
}
```

and the typing:

```ts
interface Options {
    skip?(req: http.IncomingMessage, res: http.ServerResponse): boolean;
}
```

should be equivalent from a "strictness" perspective.

However using the generics does allow to improve the specificity of the request / response types, so it looks preferable to me. But maybe it's considered a kind of type assertion, and its use is therefore discouraged. I appeal to more competent people to judge this one. 🙂  For me adding an ignore comment seems fine.

**Comment by orta** [comment]
WRT the final two fails: `function format<Request extends http.IncomingMessage = http.IncomingMessage, Response extends http.ServerResponse = http.ServerResponse>(name: string, fmt: string): Morgan<Request, Response>;` failing, I think you don't need those generics on the function because they live in the interface above?

**Comment by SimenB** [comment]
@orta those are outside the `interface` declaration

**Comment by orta** [comment]
Good point.

I assume this rule is used to reduce complexity in DT with folks needlessly using generics - I think for consistency adding the ignore is fine here. 

My gut says this was done because the end user is effective writing the same code to pull this off

```ts
 function compile<Request extends http.IncomingMessage = http.IncomingMessage, Response extends http.ServerResponse = http.ServerResponse>(format: string): FormatFn<Request, Response>;
```

For custom types they are either writing:

```ts
compile<MyReq, MyRes>("string")

// or

compile("string") as Thing<MyReq, MyRes>
```

because it's basically only used once you can put it elsewhere

**Comment by SimenB** [comment]
Cool, pushed up the ignores. I think this comment provides some justification as well: https://github.com/Microsoft/dtslint/issues/76#issuecomment-364201501

Thanks @orta!

**Review by pscanf — APPROVED** [review]

**Comment by SimenB** [comment]
Ready to merge

**Comment by SimenB** [comment]
Hopefully it won't break people 🤞

**Comment by medington** [comment]
So Dependabot brought in a PR for `@types/morgan 1.9 => 1.9.1` to our repo and this broke our code.

Perhaps what we have coded has always been wrong but I'm little surprised by a "patch release" would break existing code. That seems in violation of [semver](https://semver.org/) policy for releases. Am I missing something?

Also, as long as I'm inquiring, can someone point out for me what is wrong with this code? Sorry I'm not the author and it's not a public repo. 


image

**Comment by pscanf** [comment]
Hey @medington, sorry to hear that, I can definitely relate to the frustration of a patch update breaking a build.

If you haven't fixed it yet, you should be able to avoid the compilation error by supplying the express request and response types as generics to the `morgan` function:

```ts
export const morganLogger = morgan<express.Request, express.Response>(
  /* ... */
);
```
---
About the _breaking change in a patch release_, as I understand it, `@types` packages don't _really_ follow semver, in that [their version tries to trail the version of the corresponding package](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library), using only the patch number to identify the revision of the `@types` package.

So _I think_ that in general one could expect even a patch update to a `@types` package to break compilation. In the README [it is advised to update a major version if breaking changes are introduced](https://github.com/DefinitelyTyped/DefinitelyTyped#edit-an-existing-package), but I think it just refers to breaking changes derived from breaking changes of the corresponding library. I'm not a super expert on this though, and I might have misinterpreted.

That said, in this particular case, since `morgan@1.10.0` is available, we could have updated the `major.minor` version of the definition, which would have avoided the breaking change on a patch release, but alas I missed that in my review, apologies.

**Comment by medington** [comment]
@pscanf Thanks for the quick response! No need to apologize, I very much appreciate the education about the semver not being applicable to `@types/` packages. Thanks also for providing the fix to the code. Worked like a 💎 . Hopefully that'll prove helpful to anyone else who lands here after trying to upgrade with a similar issue.

Finally, thank you 🙇 and @SimenB and everyone else for all the hard work providing all this great OSS to the world at large. We couldn't build great software without people like you. 🦸

**Comment by pscanf** [comment]
🙏 Glad the fix worked! Cheers

**Pull request merged**
