### PR TITLE
Added initial knex@next types

### PR DESCRIPTION
**Pull request by JakeGinnivan**
I am not sure if I have done this right, there is a `@next` tagged package on NPM, I don't want to update the `@types/knex@latest` with this PR. Please advise if I have done this correctly.

FYI @kibertoad @elhigu

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes] (in this case, am using `Function` because otherwise it will require adding a bunch of extra typings, will do this later)(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). 

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tgriesser/knex/pull/2775
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Not sure how to link/build sub directories, not even sure if this is the best way to do what I want.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
So, I don't know how to fix the build. It is because of the sub-directory. Help required :(

**Comment by JakeGinnivan** [comment]
@DanielRosenwasser was wondering if you could tag someone who could help me. I am not sure how to resolve this issue, the docs are about supporting old versions when creating sub folders, not creating types for pre-release versions of a package.

**Comment by sgoll** [comment]
@JakeGinnivan Would this be the right place to add types for a minor change that was merged recently in tgriesser/knex#2835 (tgriesser/knex#2834), adding optional table names to `forUpdate()`/`forShare()`?

**Comment by JakeGinnivan** [comment]
@sgoll yeah it would be.

@DanielRosenwasser this will just be temporary, I plan on just doing a path mapping to knex/next once this is merged, I just don't know how to make the build pass

**Comment by andy-ms** [comment]
Anything merged into the master branch gets published, so we can't just merge something temporarily.

Like @DanielRosenwasser suggested, I think we should just do the same thing as if `knex` had already packaged this newest version, using the new major version number that it will have.

@sgoll If that change affects the current version, then that should be its own PR.

**Pull request closed without merging**
