### PR TITLE
@types/chrome - reorder overloaded functions to be consistent

### PR DESCRIPTION
**Pull request by DoviRivkin**
in `@types/chrome` some functions define the "promise version" first, while others define the "callback version" first.
this makes it hard to use with "typescript utility types" such as `Parameters` and `ReturnType`, most of the functions had the "promise version" first, so i made sure the rest of the fucntions follow the same order.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chrome/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6cf9f34ba3de3d8805de69ef82b87df76fc97ec3
</p>

**Review by gabritto — CHANGES_REQUESTED** [review]
> in `@types/chrome` some functions define the "promise version" first, while others define the "callback version" first. this makes it hard to use with "typescript utility types" such as `Parameters` and `ReturnType`, most of the functions had the "promise version" first, so i made sure the rest of the fucntions follow the same order.

Please provide examples of what is improved by this PR, and add those as tests.

**Comment by DoviRivkin** [comment]
It mainly affects the `ReturnType` and `Parameters` utility types, as those do not support overloaded functions (and it seems like `Parameters` fallback to the first, while `ReturnType` to the last). See [this example](https://www.typescriptlang.org/play/?#code/C4TwDgpgBMEM7CgXigbwLACgpTAJwHsBbASzggDES8EAKAQzwHMAuKBPEgOyYEo2ACoVLkAPB25MAfAG4sOfMTKVqdRq3bBOPADRQAxvQA2RgEb19Aaza0AbsYCuENhJ69kUqA66WuBAO5c-FC2BCQAJnKY8gbGZhaWVDTADMwuWpJ6hibmVjb2Rk7p2nweXj5+gcGhEVE42fFWSWppmiXBQkpirtJRAL5RWKCQuMIk8M3AAoz0RBCwNMhQ03iz8xA0orAIANoA5IoiKsl7ALqyWAD0lzhQAHoA-Fc34QTwUH6I3PqF4dDAAAtoAAiBq5SzAqDqBxzLjALBDcDQMEJSYrNYLOBLdFzTFbeDAfYopqqYBnC6Ya63R7PKCvd7fX7-IFQUFxcGQ6Gw+HRTDDaCHZSTABK8wceC4ABUkUtRcBxVKkfjdgcxuRJuSolScDTKTduAAzDZ4CDhKAG4QwFlsnIJEIbOAkAhcYEIvky4mJUlyhXSkYoH0Sv0QZWEvaejXnLU3HVPPVQQ3G03my2AkGC8j2mhOl1AA)

I'm not too sure how to test it TBH

**Comment by erwanjugand** [comment]
Maybe by doing this, though it could really increase the amount of testing needed

```
type AddParameters =  Parameters<typeof chrome.systemLog.add>; // $ExpectType [options: MessageOptions, callback: () => void]
type AddReturn =  ReturnType<typeof chrome.systemLog.add>; // $ExpectType void
```

**Pull request closed without merging**
