### PR TITLE
Make ts3.1 the default for jasmine

### PR DESCRIPTION
**Pull request by sandersn**
Remove the 3.0-and-older types since only 3.1 and above are supported on DT now.

### CODE REVIEW

**Review by devoto13 — APPROVED** [review]
Nice :+1:

**Comment by ienzam** [comment]
This PR may have reverted PR #46476

**Comment by devoto13** [comment]
@ienzam Yeah... please submit a PR to restore them.

**Comment by ienzam** [comment]
Thanks @devoto13 for your response.
Created PR #49336, PTAL

**Pull request merged**
