### PR TITLE
[node] Add `os.availableParallelism()` available in 18.4.0

### PR DESCRIPTION
**Pull request by leafac**
I did my best to follow the style of the surrounding definitions and it’s a relatively small change, so I didn’t run all the test locally in the hope that CI will catch possible mistakes.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/api/os.html#osavailableparallelism>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@leafac thanks!

**Comment by leafac** [comment]
Thank **you**, @peterblazejewicz. That was **fast** feedback on my pull request. And thanks for working on `@types/node`, y’all are doing a fantastic job here 👏

I read your commit and learned for next time 😀

**Comment by Semigradsky** [comment]
Looks like it can be merged only when `os.availableParallelism()` will be added in v18

**Comment by peterblazejewicz** [comment]
@Semigradsky great point, completely missed this
@leafac this has to wait till community bumps Node types to v19 here or feature is backported to v18 in the Node source

**Comment by leafac** [comment]
@peterblazejewicz Oh, I see. Let’s wait 🤷

**Comment by Semigradsky** [comment]
https://nodejs.org/dist/latest-v18.x/docs/api/os.html#osavailableparallelism

> Added in: v18.14.0

**Comment by Semigradsky** [comment]
@leafac could you rebase please? And change `@since` to `v18.14.0`

**Review by Semigradsky — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@leafac thanks!
amended the title

**Comment by peterblazejewicz** [comment]
ready to merge

**Pull request merged**
