### PR TITLE
[@types/slate] Command and Query methods accept function types (#34867)

### PR DESCRIPTION
**Pull request by hanstarj**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
 - command accepts function: https://github.com/ianstormtaylor/slate/blob/67e397100e2f4cc6bcd4b8f98d7a85dcf30c72fd/packages/slate/src/controllers/editor.js#L145
 - query accepts function: https://github.com/ianstormtaylor/slate/blob/67e397100e2f4cc6bcd4b8f98d7a85dcf30c72fd/packages/slate/src/controllers/editor.js#L221
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by benjiro — APPROVED** [review]
LGTM Thanks

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by hanstar17** [comment]
No problem! What happens to the linked issue #34867 ?

**Comment by rbuckton** [comment]
It wasn't linked as `Fixed #34867` in the description, so it wasn't automatically closed. I can close the issue.

**Pull request merged**
