### PR TITLE
Update from node 12/6 to node 16

### PR DESCRIPTION
**Pull request by sandersn**
azure defaults to node 6
github was set to node 12

### CODE REVIEW

**Comment by AviVahl** [comment]
Title says 18. Diff says 16.

**Comment by Tantalon** [comment]
I'm unclear why this is modifying BrokenLinkCheckerReport.d.ts, was there an issue after upgrading node, or was this change inadvertently included?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by peterblazejewicz** [comment]
@Tantalon sorry to drag you into the review, there is a problem with CI gate tests when parsing some of the AWS related type definitions, so maintainers are trying to figure out the best way to move forward, thanks for understanding!

**Comment by Tantalon** [comment]
I've submitted #63033 to remove aws-sdk from aws-synthetics-puppeteer. It provided little value, as it's only used on two function parameters, and it's breaking CI for three pull requests (#62907, #62948, #62887).

**Comment by sandersn** [comment]
This consistently fixes the problem locally, and we'll eventually want to update node anyway, so I'm going to merge and wait for the overnight run to see if it helps.

**Pull request merged**
