### PR TITLE
[@types/ember__controller] Enable controller type discovery through …

### PR DESCRIPTION
**Pull request by sergey-panov**
...`Owner::lookup()`.

These changes allow TS to resolve correctly the return type of `getOwner().lookup('controller:any')`. 

```ts
declare module '@ember/controller' {
  interface Registry {
    foo: FooController;
  }
}

const fooController = this.owner.lookup('controller:foo'); // TS resolves fooController's type as FooController.
const barController = this.owner.lookup('controller:bar'); // If not specified via Registry interface, will resolve type as Controller | undefined
```

See also: 
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__owner/index.d.ts
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__service/index.d.ts

Previous attempt: #64528 (tests added!)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [`@ember/owner`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__owner/index.d.ts)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by littleredridingfox** [comment]
BTW, should I also create a PR to `emberjs/ember.js` repo?

**Comment by littleredridingfox** [comment]
> > BTW, should I also create a PR to `emberjs/ember.js` repo?
> 
> I'm not sure I understand the question here; is this code not a part of ember already? What code change are you suggesting upstream?

As Ember is moving towards publishing the types straight from the `ember-source` package itself, this change might be needed to be done in both repositories.

> is this code not a part of ember already

It is, but without proper typing even though modern Ember is rewritten to TS. So if you would try to use `getOwner(this).lookup('controller:whatever')` TS would infer it as `any` while in runtime it will be resolved as an instance of `WhateverController`. This change fixes this behavior and removes inconsistency with other types of Ember DI Container's entities like services

**Comment by sandersn** [comment]
I don't know ember's current state, but I would guess that a PR to ember is the first step by now. However, it's really a question for the types authors  @chriskrycho @dfreeman @jamescdavis @wagenet -- can any of you comment?

**Comment by chriskrycho** [comment]
Sorry, I turned off notifications when I went on vacation and forget to turn them back on. Will fix that. We'll discuss as an Ember TS team.

However, as sort of “guiding principles”:

1. The types for Ember itself are now the source of truth and all development should *start* there.

2. Backports to these types will generally be focused solely on bug fixes going forward – so while we *might* choose to support something like this, it’s more likely that we *won’t*, because we want to treat these as being in maintenance mode and only here for legacy compatibility for Ember v4 (and Ember Data integration).

(I will work with the team to get public statements to that effect out in the world, too!)

In the meantime, note that for this specific case, by design app and addon authors can get this safety in their own apps *without* it having to be integrated into the mainline types, simply by doing a declaration merge.

**Comment by littleredridingfox** [comment]
Hi Chris, thanks for paying attention to this one.

I've [created a PR for the Ember itself](https://github.com/emberjs/ember.js/pull/20521) too. But do I get it right that types published from the `ember-source` package are only distributed since version 5.1?

I'd also like to add a few thoughts on why I'm proposing this change. When I first looked at the reason for getting `unknown` in my code instead of an actual controller type, I discovered that the `Registry` interface in `@ember/controller` is declared and exported, but not registered in `@ember/owner`'s `DIRegistry` -- so I assumed it was meant to work with `Owner::lookup`'s type resolution. I've also compared it to the `@ember/service`'s Registry implementation and decided that it looks like an accidentally missed important thing.

That's why I considered it as a bug, and that PR as a bugfix: it looks like something that has to be fixed in the framework itself, not in the app or addon. And in case you and the team agree that it might be considered a bug, then I would also propose to fix it for 4.x LTS, as `Owner::lookup` was introduced in 4.10.

**Review by chriskrycho — APPROVED** [review]
I'm going ahead and approving this; the Ember TS team is going to actively discuss and then publish an official policy on what our approach for these types will be going forward. I expect it will *probably* look as described above: (rare!) critical bug fixes only, no new feature support, and in particular no support for Ember 5.x changes.

**Comment by chriskrycho** [comment]
I'll add that as I noted on the Ember types: it's not a bug, as we consider these things. The existing version will *never* cause a run-time error; it is just less convenient to work with. That was on purpose. We don't want people treating controllers as basically-just-jankier-services. We agreed to go ahead and land this for “symmetry” and to help people migrate—it is an officially supported part of Ember’s API—but do encourage people to move away from this.

(Also, as a historical note, the controller registry has been present for many, many years, long predating the support for type-safe `owner.lookup()`.)

> But do I get it right that types published from the ember-source package are only distributed since version 5.1?

That's correct. People can use the preview types *or* the DT types from 4.8–4.12. However, for the reasons described above, I do not think this falls under the category of the kind of critical bug fix we're likely to back port to an LTS, since it is not even a *bug* as we think about these things. (I understand if you disagree, but that's how we're thinking about it!)

**Comment by chriskrycho** [comment]
Ready to merge

**Comment by chriskrycho** [comment]
For reference, all anyone needs to do to enable this behavior in their own apps or addon is add the exact same code in their `my-addon/types/index.d.ts` or `my-app/types/index.d.ts` that this adds to `controller/own_ext.d.ts`. I designed the DI registry types *very* carefully to allow just that. (This is the other reason we won't back-port it!)

**Pull request merged**
