### PR TITLE
[better-sqlite3] Add type declarations

### PR DESCRIPTION
**Pull request by Morfent**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by Morfent** [comment]
@JoshuaWise can you take a look at this?

**Comment by Morfent** [comment]
Could you link me to those @typescript-bot ?

**Comment by Morfent** [comment]
I'll give it a shot.

**Comment by Morfent** [comment]
Opened this drunk. I'll reopen later

**Comment by Morfent** [comment]
Ok, I double checked `npm run lint better-sqlite3` and `tsc` in `types/better-sqlite3`, but I found nothing... until I found out `npm test` is also used here. It should be fixed now

**Comment by Morfent** [comment]
Er,

**Comment by JoshuaWise** [comment]
I recommend just opening a new PR

**Pull request closed without merging**
