### PR TITLE
[Luxon] Swap true/false types for invalid reason and explanation

### PR DESCRIPTION
**Pull request by BrentSouza**
Bringing type signatures for `invalidReason` and `invalidExplanation` inline with `DateTime` for `Interval` and `Duration`.  When the object is invalid, we expect a value to be present for `reason`. `explanation` is optional so can still be null.

This was raised in moment/luxon#1419

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/moment/luxon/blob/master/src/interval.js#L211-L221
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by CarsonF — APPROVED** [review]
Thanks @BrentSouza!

**Review by CarsonF — APPROVED** [review]

**Comment by BrentSouza** [comment]
Sorry was having issues getting pnpm running the tests locally. Switched to WSL and was able to get it running.

**Review by CarsonF — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@BrentSouza thanks!

**Comment by CarsonF** [comment]
Ready to merge

**Pull request merged**
