### PR TITLE
@types/unist: update to v2.0.0

### PR DESCRIPTION
**Pull request by lujun2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/syntax-tree/unist/commit/8055bf46ba0c735964cb771df1e72dfc8b2899ae
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by PranavSenthilnathan** [comment]
Adding the owner of the package @bizen241. I'm curious why you decided to keep the v1 version around - do you expect that both might be used side by side? Otherwise letting the users choose the package version through npm seems like a better option.

**Comment by lujun2** [comment]
@PranavSenthilnathan Yes, you are right.
I was blindly followed the [advice](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version) without carefully thinking. 
Seems like the old version is unlikely to update, I'll remove v1 version

**Comment by bizen241** [comment]
@PranavSenthilnathan @lujun2 I'm sorry for the inconvenience. You are right. Thank you for updating.

**Review by bizen241 — APPROVED** [review]

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
