### PR TITLE
node: Add child_process options for Windows

### PR DESCRIPTION
**Pull request by vidartf**
Add `windowsHide` option to the appropriate options interfaces for node's `child_process` functions. Following the documentation for node v9.5.0.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by ajafff — APPROVED** [review]

**Comment by vidartf** [comment]
Note: CI timed out so cycled the PR to trigger a fresh go.

**Comment by Flarna** [comment]
Would be nice to apply this additionally on v8.
CI fails look unrelated.

**Comment by vidartf** [comment]
Pushed commit adding to v8 as well after confirming it was in v8 docs.

**Review by Flarna — APPROVED** [review]

**Comment by vidartf** [comment]
I cannot see how the CI failures are related to this PR. Am I missing something? Do I need to do anything more to get this merged?

**Comment by Flarna** [comment]
Most of the fails in your last run are already fixed on master. Just created a PR to fix the final one #23931.
Once that PR is merged you can retrigger CI (e.a. close/reopen, push some commit,...) and hope that no new problem was introduced meanwhile. I know this is a pain but it seems there is no better solution at this time.

**Comment by BrunoScheufler** [comment]
@vidartf correct me if I'm wrong, but the `SpawnOptions ` interface of the child_process module seems to miss the `windowsHide` property.

**Comment by vidartf** [comment]
@BrunoScheufler You're right, it seems that while `SpawnSyncOptions` got it, `SpawnOptions` did not, while according to https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options it should be for `spawn` as well.

**Comment by BrunoScheufler** [comment]
I've added a simple PR addressing these changes [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24720)

**Pull request merged**
