### PR TITLE
[react-native] Fix SectionList<T> generics (#37077), add new methods (Re-open of #37178)

### PR DESCRIPTION
**Pull request by Skn0tt**
See #37077 for a bug report of this.
For the added instance methods, refer to https://facebook.github.io/react-native/docs/sectionlist#recordinteraction.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Skn0tt** [comment]
> @Skn0tt To keep things tidy, we have to close PRs that aren't mergeable but don't have activity from their author. No worries, though - please open a new PR if you'd like to continue with this change. Thank you!

Is this behaviour intended? 😅

**Comment by alloy** [comment]
Seems like a bot overreaching to me 😅

**Comment by Skn0tt** [comment]
Well, this PR was interrupted by the bot. Maybe @alloy can reopen it to see if it got better? I can also open a new PR, if that helps.

**Comment by alloy** [comment]
There must have been a reason why I didn’t merge it yet, no? Perhaps CI was failing?

**Comment by alloy** [comment]
Ah yes, there we go, CI was red. Can you update/fix that?

**Comment by alloy** [comment]
So the bot will close immediately again when there’s a merge conflict…

@Skn0tt Ok, can you rebase your branch, fix the issues that CI [previously already reported](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/570601534?utm_source=github_status&utm_medium=notification), and let me know when done? Then I can re-open again and merge.

**Comment by Skn0tt** [comment]
I've re-opened.

**Comment by kkirby** [comment]
@Skn0tt Any update on re-opening this to try for another CI test?

**Pull request closed without merging**
