### PR TITLE
Avoid having to pass a definition for Props for React.PropsWithChildren

### PR DESCRIPTION
**Pull request by yordis**
Sometimes, we only care about having `children` definition, for example:

```tsx
export function CanvasProvider(props: React.PropsWithChildren) {
  const value = useCanvas();
  return <Context.Provider value={value}>{props.children}</Context.Provider>;
}
```

In that case, I must pass an empty `Props` definition since there is none.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by dimitropoulos** [comment]
To you, does `PropsWithChildren` mean:

- **Option A**: "has props and also has children"

- **Option B** "the props argument that does have children (but may or may not have other props specified)"

**Comment by yordis** [comment]
**Option B "has children and may or may not have other props"**

As I reflected in the usage case I shared in the description (I had to update it, sorry), since my `props` is still `PropsWithChildren` regardless if I have extra properties or not.

**Comment by dimitropoulos** [comment]
Ok, cool.  @yordis now could you tell which option you think best fits the use case this type was added for:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33381

```ts
interface P {
  foo: number;
  bar: string;
}

const Component: FunctionComponent<P> = (props: PropsWithChildren<P>): ReactElement => ...
```

I am not trying to make a statement about anything (yet), and certainly not one about this being somehow set in stone, but I am asking for you response because I want to be totally sure I understand you.

**Comment by yordis** [comment]
@dimitropoulos sure no problem,

The problem with your example is that I don't have  extra props for my component as I described in the description

```tsx
// this is not possible today since I must pass an empty interface, which is what the PR is improving
export function CanvasProvider(props: React.PropsWithChildren) {
  const value = useCanvas();
  return <Context.Provider value={value}>{props.children}</Context.Provider>;
}
```

**Comment by dimitropoulos** [comment]
Could you please just answer my question about the use case this type was designed for?  That's a necessity level of understanding I don't think we have established and I think it will be beneficial to do so.

**Comment by yordis** [comment]
I am not sure what you want to get out of it, and I feel we are entering the opinion realm, so I am not sure.

Would you mind answer the question since you know the answer?

**Comment by dimitropoulos** [comment]
I'm trying to help.  It's a simple question and I genuinely don't know how you understand it.

We've had this come up multiple times with this type and it perplexes me that you would evade such a question since it is on a thing that clearly is in disagreement.  I think it's valuable to seek to understand, but if you don't then I guess wait for some other maintainer to respond, become a maintainer yourself... or answer the question.

**Comment by yordis** [comment]
From my perspective, that type will help you to mitigate mistakes around the type of `children` in the `props`.

I still don't know what you want to get out of the conversation we are having, precisely.

**Comment by dimitropoulos** [comment]
I'm sorry to hear that you won't answer the simple question.  I suppose you'll have to wait for a different maintainer to respond then.  

Twice now, and this will be a third time.. I told you plainly that what I'm trying to get out of it is to understand your position and your use-case (also, compared to the use-case this type was designed for).

**Comment by rbuckton** [comment]
From what I can guess, @yordis's goal is to have a concise type that represents props that only allow children. They currently have two options to achieve their goal with the current set of types:

**Option 1 - pass `{}` to `React.PropsWithChildren<T>`:**
```ts
export function CanvasProvider(props: React.PropsWithChildren<{}>) {
  const value = useCanvas();
  return <Context.Provider value={value}>{props.children}</Context.Provider>;
}
```

**Option 2 - Define their own props that accepts children:**
```ts
export function CanvasProvider(props: { children?: ReactNode }) { // or an interface
  const value = useCanvas();
  return <Context.Provider value={value}>{props.children}</Context.Provider>;
}
```

Option (1) isn't terrible, but it is unfortunate since type parameter defaults exist and this one seems reasonable. Option (2) isn't terrible, but if for any reason what is considered a valid value for `children` changes then it will no longer match the definition that is defined on `React.PropsWithChildren`.

I see two different approaches for simplification:

- Give a default to `T` so that they can reuse `React.PropsWithChildren` without writing a redundant `<{}>`:
  ```ts
  export type PropsWithChildren<T = {}> = T & { children?: ReactNode };
  ```
- Give a name to the `{ children?: ReactNode }` type used in `React.PropsWithChildren` so that it can be referenced on its own:
  ```ts
  export interface ChildrenOnlyProps { // name open for debate...
    children?: ReactNode;
  }
  export type PropsWithChildren<T> = T & ChildrenOnlyProps;
  ```

I think what @yordis wants to do seems fairly sound, and wouldn't negatively affect existing cases where a component has props that want to opt into having children.

I'll give this until tomorrow for follow up from project owners, otherwise I'll probably approve the change as it seems reasonable.

**Comment by dimitropoulos** [comment]
In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311#issuecomment-721714840 I tried to, as clearly as possible, separate the cases we're all taking about here.  That's why I was sad to see @yordis refuse to cooperate in getting a baseline of understanding.  I realize that breaking things down to a very primitive state is annoying for some, but we've had a number of issues/PRs on this topic and continue to talk past each other (I was hoping by making the three options mentioned above that I'd make that clear).

To me, @rbuckton, when you said:
> @yordis's goal is to have a concise type that represents props that only allow children.

That sounds exactly like
> Option C "has children and no other props"

And yet, @yordis actually said [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311#issuecomment-723526599) that he is talking about option B: "has children and may or may not have other props".

This distinction matters because, as has been thoroughly demonstrated by the confusion with this name, "PropsWithChildren" means different things to different people (including, as far as I can tell, the original author and use-case this was designed for (I realize we're not married to that, but worth acknowledging I think)).

**Comment by rbuckton** [comment]
If that's the case, then perhaps giving a name to the `{ children?: ReactNode }` type would be a better solution, as it provides an alternative to `PropsWithChildren<{}>` or `PropsWithChildren` on its own. If so, then the next question would be what would be the best name for such a type. I'd be tempted to suggest something like `ContainerProps` for a non-specific container of children:

```ts
interface ContainerProps {
  children?: ReactNode;
}
```

There are even a number of places in the react types that would benefit from the name (rather than using a type literal), such as:
```ts
const Fragment: ExoticComponent<ContainerProps>; // was ExoticComponent<{ children?: ReactNode }>;
const StrictMode: ExoticComponent<ContainerProps>; // was ExoticComponent<{ children?: ReactNode }>;

interface SuspenseProps extends ContainerProps { // was interface SuspenseProps {\n children?: ReactNode; ...
    /** A fallback react tree to show when a Suspense child (like React.lazy) suspends */
    fallback: NonNullable<ReactNode>|null;
}
```

**Comment by yordis** [comment]
From a linguistic perspective,

Given `type PropsWithChildren<P = {}> = P & { children?: ReactNode };`  in the context of defining a React prop with children.

Does omitting the interface change the meaning of the type?

If so,

Would you mind explaining your thought process how it does change the meaning?

From my perspective,

I want to go from "Option A has children and also has other props" to "Option B has children and may or may not have other props" since as I displayed in my example, the type that comes out of it does not change the meaning,

but for "Option B", I am forced to pass an empty interface when TypeScript has the capabilities to set default interfaces.

Now, if such a thing has caused issues before, I would like you to share them, it may help me to understand the concerns about it.

>  but we've had a number of issues/PRs on this topic and continue to talk past each other

This is what I wanted you to share since we would focus the conversation around such issues and allow me to research and see your perspective in the situation rather than my understanding of the situation.

I refused to be dragged down by something that you knew the answer to your own concern, and I let you know that I much rather you tell me precisely what you want to get out, than going for a lengthy process.

#33381 gives no context about those issues are precise.

So I flip it back to you, I was sad to see @dimitropoulos refused to cooperate in sharing things like "we've had a number of issues before" and streamline the process and share precisely the issues with such thing.

Please don't take it personally, just understand that your attitude in the situation didn't help either, I collaborated with you as much as I could.

**Comment by dimitropoulos** [comment]
yawn... I feel that, @yordis, you're trying way too hard to be antagonistic for this to be a productive conversation any longer.  I don't know why but.. I wish you would consider toning it down and focus on code and not people/emotions.  You keep telling me what my own thoughts are and flatly won't acknowledge my repeated and genuine requests to understand what you are talking about. 

> I refused to be dragged down by something that you knew the answer to your own concern

This is so strange to me that you are so hellbent on telling me what I know and don't know, despite me clarifying to you exactly the reason for my asking ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311#issuecomment-723680954), for example).  You have stated enough times now that you know what I think better than I do.  I hope you consider this approach in the future as it has made it quite unpleasant to work with you.

It seems to me that you just want to fight.  I had hoped I was wrong about that feeling but your last message where you, from my reading, only dug your heels further in the ground confirms this to me:

> So I flip it back to you, I was sad to see @dimitropoulos refused to cooperate in sharing things like "we've had a number of issues before" and streamline the process and share precisely the issues with such thing.

I apologize for not being precise enough when I said "issues/PRs" because I should have said "GitHub issues and GitHub Pull Requests".  Here are four examples of what I'm taking about (including this) [one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311) [two](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48248) [three](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46043) [four](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43816).  Also... dude... what are you even talking about?  Where, before the quote you mentioned did I refuse to cooperate with anyone in this manner?  Seems impossible to me since your talking about something I raised in the message immediately before yours.  anyway...

I thank you @yordis for what substance you did add to the conversation in your last message, but to be perfectly honest your dedication to make a person who is genuinely just trying to understand you the enemy in the context of something like this is so silly to me that I just can't continue the conversation at this point.  I've given it a good ol' college try and now I will bow out and unsubscribe from this issue.

I'm not perfect and somehow my genuine seeking to understand you @yordis came off to you as disrespectful.  I meant no disrespect in anything I have said with perhaps the exception of this message, which I feel you quite thoroughly earned.  It's a shame this conversation must happen over GitHub rather than in person because if it were in person you'd find that I am approaching this with a very gentle tone of curiosity.  I'm not upset or anything of the sort - but you seem to think I am, judging by your responses.  If you happened to live near me I'd offer to buy you a beer and listen to what you have to say without interruption.  And shit, you know what: I live in Michigan.  If you're ever in Michigan drop me a line and I'll buy you a beer anyway (100% serious offer).  After so much time in so many exchanges with you and others over this damn type, haha, I could use a laugh about it anyway.

---

Thanks @rbuckton for what you contributed here - I thought you were getting somewhere productive and was very excited to have the conversation with someone that was a little more willing to talk about code rather than personal attacks.  Despite that, I'm a little burned out on this topic and am just going to step away.

If you or anyone else continues with this I'll just say that I've asked a good deal of my colleagues (just out of my own curiosity) which thing "PropsWithChildren" means to them and it is quite the mix.  There are people on both "sides" of the interpretation that find any other interpretation absolutely preposterous.  That, to me, is the core reason it's worthwhile to make completely sure we all understand each other when having the conversation because we are likely (according to my unofficial and unscientific survey) to be actually talking about different things.  

---

As [eps1lon did before me](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46043#pullrequestreview-458656328) (which I now see that you have thumbs-downed @yordis... heh.) I'll leave my disapproval here for posterity.  I'm not in any kind of control here so if someone wants to merge this despite the disapproval of at least two of the active contributors who are daily maintaining these types then I understand and take no offence - after all, that's life in the big city, baby.

**Comment by yordis** [comment]
>  As eps1lon did before me (which I now see that you have thumbs-downed @yordis... heh.) I'll leave my disapproval here for posterity. I'm not in any kind of control here so if someone wants to merge this despite the disapproval of at least two of the active contributors who are daily maintaining these types then I understand and take no offence - after all, that's life in the big city, baby.

Disapproval based on "one person" opinion.

I deeply appreciate that daily maintenance takes their free time for it, and also say there is another side, people concern with the usage instead of the maintains of it, and so far your arguments are as valid as the arguments present by many other people.

The person from the other PR had to give up to you https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46043#issuecomment-666931604 because of the one reviewer strong opinion.

And simply a person being authoritarian position despite from his own words  "It's generally frustrating because this "it's just a minor addition" argument is all I hear everyday" the issue is something that comes up "everyday".

At what point you knowledge the situation?

Who is right? 🤷🏻 

I don't know, what I do know is the pain as an active React programmer in that this is unnecessary when a language like a TypeScript gives you the power to have a middle grown.

**Comment by dimitropoulos** [comment]
hopefully we can reset this conversation.  I had a situation where I was using `PropsWithChildren` recently and this came to mind.

@yordis I mean no malice whatsoever.  Truly.  I have a question that I would please like you to share your thoughts on.  If it is not clear to you why I am asking then I humbly ask for your trust that I am sincere and share your thoughts anyway:

### Question Context

As far as I can tell, the available interpretations of what `PropsWithChildren` means include:

- **Option A**: "has children and also has other props"

- **Option B**: "has children and may or may not have other props"

- **Option C**: "has children and no other props"

You have [said](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311#issuecomment-723526599) that your perspective aligns with Option B.

### Question

Which of the above options do you believe best fits the use-case this type [was designed for](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33381)?

-------

Please assume no further context beyond this concrete question about the code.  I have asked people other than yourself this exact question and gotten different answers.  I do not know your view on which.

I realize you want more context than I'm giving, and I can say more about why I think the answer to this question is relevant but I'm quite afraid to go on any tangents until we're all on the same page (which, I strongly feel we are not) about terminology and use-cases.

------

p.s.

You have said in your last message:

> I didn't refuse to answer anything.

I reread everything up to this point to make sure I'm not antagonizing you (very deeply trying to avoid doing so) and I have not seen where you answered this question (originally asked [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49311#issuecomment-723675540)).

I apologize if you did answer it and I missed it - please link to it.

**Comment by yordis** [comment]
> Which of the above options do you believe best fits the use-case this type was designed for?

Please help me to understand what was designed for. I can't understand from that PR what was the intention behind the PR. The description says nothing about it unless I am completely misunderstood.

My main point is that, regardless of the original intention (which is not the case that doesn't matter at all, that is not the point, but the fact that it is what it is in real production codebases 🤷🏻 ), I see Option B: "has children and may or may not have other props" being used all over the place.

Which implementing Option B doesn't affect current production codebases, but it does allow people to continue leveraging the typespec without having to pass empty interfaces for silly reasons IMO.

Sure, but why?

Sometimes you discover the issue at compile time because they don't have good local tooling and some setups use Babel over TypeScript so they actually turn the type checking off unintentionally, relying on VSCode or some weird setups; and they forgot to add the silly empty interface.

Personally, such concern is the last thing I could care about, but I see many mistakes made around the topic, and people struggling with tooling and CI logs, and so on because of such silly mistakes.

And it is hard for me to understand where some of you stand are when you knowledge that many people keep requesting and facing the issue.

I am trying to get some technical reasons to avoid such changes, that we can at least, align without having to rely completely on personal opinion; otherwise, your stands exclude people's experience, and in the worst case, knowledge them but decide to ignore it.

🤷🏻

**Comment by dimitropoulos** [comment]
I'd like to note that I [literally approved this change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46043#issuecomment-659123275), once upon a time.  Please, instead of arguing can we please just focus on the code.

You said:

> Sure, but why?

I'd like to take you up on the "sure" part right here and now, and refer you to my previous message which explained the why.  You have said you will answer, but we're approaching double digit times where you have had an opportunity to do so but still have not (and again, if you did somewhere and I missed it, please link it - my apologies).

> The description says nothing about it unless I am completely misunderstood.

The description contains a use-case:

```ts
interface P {
  foo: number;
  bar: string;
}

const Component: FunctionComponent<P> = (props: PropsWithChildren<P>): ReactElement => ...
```

Please let me know which option you think this use-case covers.  I am not asking you to reach into the mind of the author - I'm only asking for your own opinion, as the author of this PR and the one asking for the change.  I think it's very fair for me to ask you to share your perspective.  Thank you.

-----

To make it easy, all that would be necessary is something like:

> from what I can tell it seems like Option X is the use-case this type was designed to handle.

**Comment by elibarzilay** [comment]
Since this seems to have diverged into a mini flamewar, maybe follow the suggestion to reset the conversation, and just stick to the code change and the issues with it?  (If there is a disagreement on what such a default should be, then maybe it's best to keep it default-less?)

**Comment by weswigham** [comment]
It looks like the type maintainers who have chimed in don't really care for this change (consumers can just say `React.PropsWithChildren<{}>` after all), so I'm going to close this PR.

**Comment by yordis** [comment]
Is it really fair to use such an argument and invalidate many of us?

@weswigham How does one become a type maintainer? Maybe becoming one my opinion does matter (as many other people share the same opinion, so don't take it as a singular)

**Comment by yordis** [comment]
After having an amazing conversation with @dimitropoulos over a Zoom call,

The deviation is not based on the allowed values of a `React.ReactNode` but if `children` property must be present in the object or not. I believe that is where most of the confusion comes from 50% of the discussion users.

- Should the `props` contain the `children` key or not?
- Would `With` be the appropriate conjunction to use here? (probably not)

---

Moving forward, we talked about proposing a type `PropsHasChildren` where the `children` prop is required to be present, fixing a linguistic problem for 50% of the users that meant `"Option A: "has children and also has other props."`

Leaving behind `Option B "has children and may or may not have other props"` where we need to figure out the linguistic problem since `With` in this context implies that `children` must be there from a correct linguistic perspective.

So the typespec is misleading as of today, taking into consideration. that

Example:

```TSX
import * as React from 'react';

function MyComponent(props: React.PropsWithChildren<{}>) {
  return (
    <div>
      {props.children}
    </div>
  )
}

function Root() {
  return (
    <MyComponent>{/* I should pass a children based on the existing type and linguistic */}</MyComponent>
  );
}
```

Notice that I am not passing any children to  `<MyComponent></MyComponent>` but stills renders without a type error.

**Pull request closed without merging**
