### PR TITLE
export { ReCAPTCHA } removed.

### PR DESCRIPTION
**Pull request by sinanbozkus**
**"export { ReCAPTCHA }" was removed** because it doesn't work if you use this instead of default export.

### CODE REVIEW

**Comment by sinanbozkus** [comment]
> Hey @sinanbozkus,
> 
> 😒 Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module.
> 
> _**This can potentially save days of time for you!**_

I can't add a test because that export isn't working.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-google-recaptcha ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-google-recaptcha@latest/))
was missing the following properties:
1. ReCAPTCHA
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 111b80d5369c69c39a77a2854786cab90f3f57ba
</p>

**Comment by smujmaiku** [comment]
It looks like `export { ReCAPTCHA };` still exists in the [source package](https://github.com/dozoisch/react-google-recaptcha/blob/master/src/index.js#L5). Would you expand on why you are trying to remove this from Typed? Perhaps you can fix what you see is broken instead, other people might be using this feature.

**Comment by gabritto** [comment]
I'm going to close this because the source package does seem to have a named `ReCAPTCHA` export, and there's been no activity on this PR. Feel free to re-open if you think it's a mistake. Thanks.

**Pull request closed without merging**
