### PR TITLE
[@types/mime] Remove mime types in favour of `mime@4.0.0`

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by dhritzkiv — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@codershiba thanks!

**Comment by codershiba** [comment]
Ready to merhe

**Comment by codershiba** [comment]
Ready to merge

**Comment by esetnik** [comment]
@codershiba this breaks `@types/serve-static` which depends on `@types/mime` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serve-static/index.d.ts#L4C21-L4C25.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69231

**Comment by codershiba** [comment]
> @codershiba this breaks `@types/serve-static` which depends on `@types/mime` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serve-static/index.d.ts#L4C21-L4C25.
> 
> See #69231

Yeah I have tried to fix this in PR #69231 by pinning the version to a lower version.

**Comment by jakebailey** [comment]
We should revert this; this PR should not have modified notNeededPaackages as the mime types are far too popular (22M weekly!!!) for a shim package to work.

**Comment by jakebailey** [comment]
Er, it's too late, `@types/mime` was published as a shim at v4, so we can't undo that. All we can do is start switching users to v3 when needed, and everyone else needs to be pinning to the right major version, as the DT types versioning aren't _wrong_ here.

**Comment by peterblazejewicz** [comment]
Sorry for this, I could have undervalued the v3, it was listed as updated (npm) 2 years ago.

**Comment by jakebailey** [comment]
No worries, I think the shim is actually okay in this instance given it's a clear major version difference. But it's also a failure of the tooling that we did not detect that the other package would break.

**Pull request merged**
