### PR TITLE
[ssh2] Tweaks to SSH2 typings

### PR DESCRIPTION
**Pull request by dhensby**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

1. Define the list of supported KeyTypes for better interoperability with ServerHostKeyAlgorithm type
2. Allow hostVerifier function that accepts a string (instead of buffer) as was the "old style" for host verification and is what is used if `hostHash` prop is provided.
3. Fix issues with callback parameters that are optional; sftp event callback parameter; and SignRequestOptions.hash is not optional

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
recall in TS callbacks (functions) passed as param to other functions are always supporting params in optional fashion:
```ts
declare function addListener(type: 'test', callback: (error: Error, data: string) => void): void;

addListener('test', () => {});
addListener('test', (error) => {});
addListener('test', (error, data) => {});
```
is there a reason to complicate callbacks types?

**Comment by dhensby** [comment]
Thanks for taking a look at the PR @peterblazejewicz, however I don't entirely follow what you're suggesting.

In this instance the callbacks are executed by the consumer, not by the internals, so the consumer can provide the parameters, but doesn't have to provide them all. These are not analogous with event callbacks/listeners in that sense.

For example I can use the sign callback like so:

```js
const { sign } = require('crypto');

function sign(pubKey, data, { hash }, callback) {
  const privKey = findPrivateKeyFromPublicKey(pubKey);
  sign(hash, data, privKey, (err, sig) => {
    if (err) {
      callback(err); // no second param, it is optional
    } else {
      callback(null, sig); // first param can be null/undefined, second is supplied
    }
  });
}
```

**Review by bragle — APPROVED** [review]
LGTM

**Comment by dhensby** [comment]
Ready to merge

**Pull request merged**
