### PR TITLE
[google-spreadsheet] - Add insertDimension function to GoogleSpread allow to add rows and 

### PR DESCRIPTION
**Pull request by shreyngd**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-insertdimension
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by the-vampiire — APPROVED** [review]
LGTM

**Review by the-vampiire — APPROVED** [review]
LGTM

**Comment by MysteryBlokHed** [comment]
The `insertDimension` function seems to have been added in v3.2.0, so the version in the DT header should probably be updated.

**Review by EndBug — CHANGES_REQUESTED** [review]
As @MysteryBlokHed pointed out, the header needs to be updated

**Comment by the-vampiire** [comment]
Good catch on the headers guys. Sorry I missed that.

**Review by the-vampiire — APPROVED** [review]
LGTM now that the header is updated. 

Personal preference would be to match the param names (docs uses "range" but types are using "bounds"). That being said using bounds is closer to the rest of the types style and the end usage is the same.

**Review by EndBug — APPROVED** [review]
LGTM ✅

**Comment by shreyngd** [comment]
Ready to merge

**Pull request merged**
