### PR TITLE
Fix react-autocomplete renderItem prop type

### PR DESCRIPTION
**Pull request by bfncs**
I fixed the missing second argument in the renderItem prop type of react-autocomplete. See: https://github.com/reactjs/react-autocomplete/blob/master/README.md#renderitem-function

If changing an existing definition:
- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactjs/react-autocomplete/blob/master/README.md#renderitem-function>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

@lstanden

### CODE REVIEW

**Comment by lstanden** [comment]
Good catch.  Might be worth adding the third argument too if you're willing? 

        renderItem: (item: any, isHighlighted: boolean, styles: CSSProperties) => ReactNode;

That should do it?

**Comment by bfncs** [comment]
Thanks for reviewing, you were totally right. This should do it.

**Comment by lstanden** [comment]
👍 from me

**Comment by lstanden** [comment]
@RyanCavanaugh @andy-ms Been just shy of 24 hours since this was merged... did we need to increment the type version in order for a release to happen?

Thanks

**Pull request merged**
