### PR TITLE
Typo fix for passport module

### PR DESCRIPTION
**Pull request by npenin**
I guess there is not so much to discuss about it. 

All the information is in your hands : https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts

:)

### CODE REVIEW

**Comment by horiuchi** [comment]
`Express` interface is here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express-serve-static-core/express-serve-static-core.d.ts#L8

**Comment by npenin** [comment]
But then why Express is not a recognized namespace in vscode ? 
I have installed typings and have referenced express module in typescript this way : 
```import * as express from 'express';```

**Comment by npenin** [comment]
It seems typings from npm and from dt do not provide the same interfaces and namespaces. Should I raise an issue for that ?

**Comment by andy-ms** [comment]
`express` now appears to be using `declare module "express"`, so this probably needs to be revised.
The `master` and `types-2.0` may not be identical, so you may need slightly different solutions for each.

**Comment by zhengbli** [comment]
@npenin Can you update the PR to address the comments? Thanks

**Comment by yuit** [comment]
@npenin  Thanks for your contribution. This PR has unaddress comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
