### PR TITLE
DatePicker: hintText, floatingLabelText

### PR DESCRIPTION
**Pull request by tsv2013**

### CODE REVIEW

**Comment by vvakame** [comment]
*material-ui/material-ui.d.ts*

to author(@ngbrown). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by tsv2013** [comment]
Hi! Any movements on this?

**Comment by vvakame** [comment]
it merged. sorry for late!

---
note
http://material-ui.com/#/components/date-picker

**Comment by tsv2013** [comment]
Thanks!

**Pull request merged**
