### PR TITLE
Change member types to function

### PR DESCRIPTION
**Pull request by emoldtmann**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by dolanmiu** [comment]
Hey again! I remember we had this issue before...

http://www.nodegit.org/api/diff_line/

It says "Instance Variables"

Are you 100% sure the documentation is wrong?

**Comment by SilentFlyBy** [comment]
Hey again as well!
Unfortunately, the documentation seems to be wrong here again.
Calling `console.log()` on each of these fields indicates that these fields are functions.
Only calling them as a function will return the desired value.

**Review by dolanmiu — APPROVED** [review]

**Comment by dolanmiu** [comment]
Ok, approved!

**Comment by RyanCavanaugh** [comment]
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

**Comment by RyanCavanaugh** [comment]
It'd probably be nice to file a bug in their repo

**Pull request merged**
