### PR TITLE
Improved visionmedia/debug to include non-amd version

### PR DESCRIPTION
**Pull request by galtalmor**
Improved visionmedia/debug, a tiny npm package for debugging.
Added both AMD and non-AMD definition support

### CODE REVIEW

**Comment by swook** [comment]
(n) I'm afraid I have not been developing with Typescript in a while. Nonetheless, thank you for the contributions.

**Comment by galtalmor** [comment]
That's not a good reason to vote down :(

**Comment by swook** [comment]
Sorry for the misunderstanding, I meant that I'm not in a good position to effectively review the PR! (I thought the bot would try to find another reviewer once I mark it so)

In general the changes lgtm apart from the fact that the interface renaming is a breaking change (though a sensible one).
I would also suggest using a consistent spacing rule for formatting the code, for example just `variable_name: type_name` or `variable_name:type_name`.

**Comment by galtalmor** [comment]
That's cool.
Thanks for the comments.
Fixed the spacing.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
