### PR TITLE
knex: Add alias definition to QueryBuilder#select

### PR DESCRIPTION
**Pull request by nounder**
QueryBuilder#select also accepts arguments in form of alias object:

    knex.select({ owner: "user.name" });

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://knexjs.org/#Builder-identifier-syntax
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by mastermatt — COMMENTED** [review]
This could use some tests. The examples from the docs would be a good starting point.

**Comment by rgtk** [comment]
Example for `QueryBuilder#select` are provided in pull request: http://knexjs.org/#Builder-identifier-syntax

For Raw in FROM clause, example can be found [here](http://knexjs.org/#Raw-Expressions). It does not show that you can use Raw in `QueryBuilder#from` but point is, it is supported by every QueryBuilder so also for `from`.

**Comment by mastermatt** [comment]
@rgtk I'm not sure if your comment is directed at mine, but to clarify: the examples you've linked to need to be added to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knex/knex-tests.ts so the tests can verify your changes are understood by `tsc`.

**Comment by rgtk** [comment]
Test added. Thank you for directing me :)

**Review by mastermatt — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
