### PR TITLE
Added the definition for the npm package simple-url-cache

### PR DESCRIPTION
**Pull request by a-lucas**
- [X] npm test passes
- [X] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [X] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

https://www.npmjs.com/package/simple-url-cache

### CODE REVIEW

**Comment by a-lucas** [comment]
I'm not sure where the Travis test is, so closing, and reopening another one...

**Comment by jasonnian1978** [comment]
untitled 1

**Comment by jasonnian1978** [comment]
snapshot - 1

**Comment by a-lucas** [comment]
*Antoine LUCAS*

*ReactJS, PHP / Javascript / MySQL / Angular / MEAN Stack / LAMP Stack
Developer*


http://a-lucas.github.io/resume/app/#/AntoineLucas

*Skype:* montpellier_1001net
*Phone:* 0424 207 292

**Pull request closed without merging**
