### PR TITLE
[rnmds] Adds alwaysShowBackButton prop

### PR DESCRIPTION
**Pull request by iRoachie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/ananddayalan/react-native-material-design-searchbar/pull/23>>

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Waiting for reviewers to give feedback.
<sub>This message was posted by a script</sub>

**Comment by RyanCavanaugh** [comment]
Waiting for reviewers to give feedback.
<sub>This message was posted by a script</sub>

**Comment by iRoachie** [comment]
👍🏽

**Comment by RyanCavanaugh** [comment]
Would be nice if this file had owners :/

**Comment by iRoachie** [comment]
Lool hah @RyanCavanaugh  just me! Testing out a new bot?

**Pull request merged**
