### PR TITLE
add type definitions for 'random-seed' package

### PR DESCRIPTION
**Pull request by endel**
Type definitions for [random-seed](https://github.com/skratchdot/random-seed)
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by endel** [comment]
I've exported the `create` method and generator interface due to TypeScript's limitations. As far as I know there's no way to allow those 3 ways to construct the generator (described in [project's README](https://github.com/skratchdot/random-seed#create-a-random-number-generator)):

```js
// javascript
var gen = require('random-seed');
var rand1 = gen.create(); // method 1
var rand2 = new gen();    // method 2
var rand3 = gen();        // method 3
```

So, in TypeScript, we would have to choose between one of those. I've chosen the first option, which doesn't need a `export default`, therefore we can also export the interface of the generator.

```ts
import { RandomSeed, create } from "random-seed";
let rand1: RandomSeed = create();
rand1.random();
```

Thoughts about this @skratchdot?

**Comment by skratchdot** [comment]
@endel-  This is great! This is exactly the API think I was going for when I made this lib.  If I would re-write it today, it would basically follow what you've laid out here.  Basically I would remove `method 3` from my original example code (and the lines you pasted above).  If I re-write, the interface would look more like what you have, except for 1 point: I might export RandomSeed as both a named export, and as the default, so you could do:
```
import RandomSeed, { create } from 'random-seed';
```
or
```
import { RandomSeed, create } from 'random-seed';
```

But that might fall into the problem the original lib had: too many options :)

Perhaps someday (after this PR is pulled in) I can re-write the original lib in either typescript or es2015/16/17 via babel.

If you need me to pull in a PR to the upstream lib, let me know.  I'm all for it.

**Comment by vvakame** [comment]
@endel FYI https://github.com/DefinitelyTyped/DefinitelyTyped/blob/072d9db2ee9613ce96eecf11a3425a5eea12d8a5/node/node.d.ts#L3412-L3457

**Comment by endel** [comment]
Hi @vvakame, I didn't understand the relation of these lines of code to this pull request. Could you elaborate? Cheers

**Comment by vvakame** [comment]
@endel TypeScript can function + namesplace structures.
https://goo.gl/t8w6QL
see this code example.

**Comment by andy-ms** [comment]
You can do:
```ts
declare namespace randomSeed {
    export interface RandomSeed { ... }

    export function create(): RandomSeed;
}
declare var randomSeed: {
    new(): randomSeed.RandomSeed;
    (): randomSeed.RandomSeed;
}
export = randomSeed;
```

**Pull request merged**
