### PR TITLE
Update rxjs dependency in @types/inquirer

### PR DESCRIPTION
**Pull request by LBBO**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
  - Since this PR only updates a dependency, I'm not sure if this applies and, if so, how the tests should be updated to ensure an up-to-date version of rxjs
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
  - Again, I dodn't really find the advice to apply to this type of change
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
  - They fail on my machine, but they also failed before I made any changes and fixing that seems like a task for another PR.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/package.json#L50
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Here's an example of the issue that this fixes:

```ts
import type { Observable } from 'rxjs' // v7.3.0, installed manually but matches the inquirer dependency
import inquirer, { DistinctQuestion } from 'inquirer' // Uses types from rxjs@^6.4.0

declare const prompts: Observable<DistinctQuestion>

// TS2345: Argument of type 'Observable<DistinctQuestion<Answers>>' is not assignable to parameter of type 'QuestionCollection<Answers>'.
//   Type 'Observable<DistinctQuestion<Answers>>' is missing the following properties from type 'Observable<DistinctQuestion<Answers>>': _isScalar, _trySubscribe, _subscribe
inquirer.prompt(prompts)
```

### CODE REVIEW

**Comment by LBBO** [comment]
For the pinged reviewers, just to make sure you don't miss the part in the PR description: the tests already failed on my machine before I introduced any changes. Since I am only updating the rxjs dependency to reflect the actual library (see [inquirer `package.json`](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/package.json#L50)), I'm pretty confident that my change is not the cause of these errors.

**Review by neurolag — CHANGES_REQUESTED** [review]
Please change the required TypeScript-version to 4.2

As seen in `rxjs`s `package.json`, `rxjs@7.2.0` requires at least TypeScript v4.2 to be installed:
https://github.com/ReactiveX/rxjs/blob/7.2.0/package.json#L9-L15

Thus, all tests with TypeScript < 4.2 fail.

**Comment by manuth** [comment]
Hello
I'm very sorry for the late response, I didn't realize you're having trouble with fixing the errors.
Have a look at my short review to fix the package.

Thanks for being patient! ✨

**Comment by manuth** [comment]
Looks like you have to add a `// Minimum TypeScript Version: 4.2`-comment for all other `@types`-packages which depend on `inquirer`, too:
* console-ui
* inquirer-autocomplete-prompt
* inquirer-fuzzy-path
* inquirer-npm-name
* yeoman-environment
* yeoman-generator

**Comment by LBBO** [comment]
This whole DT stuff is really confusing me. Locally, the tests fail with the following message:

```
> definitely-typed@0.0.3 test /path/to/DefinitelyTyped
> dtslint types "inquirer"

Error: /path/to/DefinitelyTyped/node_modules/chalk/types/index.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /path/to/DefinitelyTyped/node_modules/chalk/types/index.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md

    at /path/to/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
npm ERR! Test failed.  See above for more details.
```

I couldn't figure out what the issue was and so I decided to just push my changes and then ask for help once the CI fails with the same error. Now, the CI failed, but with a totally different error🎉

@manuth thanks for the suggestion to change the minimum TS version for the other packages. I'll try that and push the changes again, but the other issue might still come up afterwards.

**Comment by manuth** [comment]
That's weird - as far as I can see, the current `inquirer`-types don't import `chalk` at all...
Let's see whether the issue still occurs now

**Comment by LBBO** [comment]
My thoughts exactly. I couldn't find anything either. But this is going to take a while anyway if more dependencies keep arising...

**Comment by manuth** [comment]
Looks like you have to add the `// Minimum TypeScript Version: 4.2` which don't have such a comment yet, too...
As far as I can see, following dependencies need to have said comment added to the heading:
* inquirer-autocomplete-prompt
* inquirer-fuzzy-path
* yeoman-test
I think that's all that's left to do

**Comment by manuth** [comment]
`inquirer-autocomplete-prompt` is still missing the required minimum TypeScript-version.
As far as I can see, this is the last one ✨

**Comment by LBBO** [comment]
Awesome, thanks for your work! I guess my local setup is just messed up and the error only exists on my machine 🤷

**Review by neurolag — APPROVED** [review]
Looks fine to me!
Thanks for your effort 😄

**Comment by manuth** [comment]
Yeah, that's quite strange - mostly, when running into such an issue in the DT-project, I wipe all changes using `git clean -fdx` and run a fresh `npm install`, which (in most cases) solves all issues on its own ^^

**Comment by LBBO** [comment]
Nice, I wasn't familiar with `git clean` yet but it sounds like the solution to some frequent and somewhat annoying problems. Thanks!

**Comment by manuth** [comment]
No worries, I'm glad I could help 😄

**Review by MaikoTan — APPROVED** [review]
Looks good to me.
Thank you all!

**Review by orta — APPROVED** [review]
Looks pretty reasonable to me 👍🏻 and there's been enough time for any of the other owners to raise their opinions

**Comment by LBBO** [comment]
Ready to merge

**Pull request merged**
