### PR TITLE
Fix #36308 - underscore has bad chain typings

### PR DESCRIPTION
**Pull request by regevbr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by regevbr** [comment]
Fix #36308 - underscore has bad chain typings
@jgonggrijp can you please review?

**Comment by regevbr** [comment]
@jgonggrijp @DanielRosenwasser can you please help get this PR merged?
Thanks!

**Comment by regevbr** [comment]
any news?

**Comment by jgonggrijp** [comment]
@regevbr I'm a bit late to the party, but it looks good to me. ;-)

**Comment by renjfk** [comment]
This seems to resolve only `without` and `union` but what about other chain methods? They still seem to be broken such as `filter`, `map` etc.

**Comment by regevbr** [comment]
@renjfk I'm working on a full blown solution but it will take time as it requires refactoring the entire library.
If you have something that requires a quick fix I can make it happen as another patch

**Comment by renjfk** [comment]
Nah no need, for the time being I can stick to 1.8 line.

**Pull request merged**
