### PR TITLE
[inert] update types to 5.1

### PR DESCRIPTION
**Pull request by lenovouser**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by lenovouser** [comment]
Everything in `v4/` is old code @nycdotnet 

/cc @SimonSchick @AJamesPhillips

**Comment by SimonSchick** [comment]
Hu?

**Comment by lenovouser** [comment]
I ran a cleanup script and it deleted the branch 😆

**Review by SimonSchick — APPROVED** [review]

**Comment by housejumper** [comment]
Can this be merged? My hapi v17 project is failing due to the types being outdated

**Comment by lenovouser** [comment]
@DanielRosenwasser this should be ready to merge, not sure when @nycdotnet is online the next time

**Review by nycdotnet — APPROVED** [review]

**Comment by nycdotnet** [comment]
@SimonSchick since you're using Hapi and involved with this, please submit a PR to add yourself to the inert package in the `.github/CODEOWNERS` file.  I am not using hapi anymore at work so I don't want to be a blocker.  Thanks so much for picking up the progress on this!!!

**Comment by lenovouser** [comment]
@nycdotnet thanks! 🎉  ❤️

**Pull request merged**
