### PR TITLE
Fix braintree module export

### PR DESCRIPTION
**Pull request by syymza**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sandersn** [comment]
If you want to create a module that can be imported but is also available globally in the browser, you should use the new `export as namespace` syntax instead of the `declare module "braintree"` syntax:

```ts
export = braintree;
export as namespace braintree;
```

Also please add a test file that uses braintree-web via import.

**Comment by syymza** [comment]
@sandersn @chlela I have updated the PR with the suggested export.
I am unsure on how to test importing `braintree-web` and using it as a global at the same time

**Comment by sandersn** [comment]
Create a separate test file that imports braintree-web. Then add the file to tsconfig.json.

**Comment by syymza** [comment]
@sandersn thank you. I have added the test file for the import. Unfortunately the suggested approach for exporting was breaking the already existing test, hence I reverted it.

**Comment by sandersn** [comment]
Yes, `export as namespace braintree` requires that *types* be qualified as well as *expressions* (which already were required to be qualified):

```ts
braintree.client.create({ authorization: clientToken },
  function (error: braintree.BraintreeError, clientInstance: any) {
....
```
notice that both `client` and `BraintreeError` must now be qualified with `braintree.`

**Comment by syymza** [comment]
@sandersn Your suggestion doesn't work, here is the error I have when I use `braintree.BraintreeError`: `Cannot find namespace 'braintree'`. Also I have seen the CI suggest me to rename my file from `braintree-web-import-tests.ts` to `braintree-web-tests.ts` even though I added `braintree-web-import-tests.ts` to tsconfig.

**Comment by sandersn** [comment]
Hm, yeah, it turns there is a lot more refactoring needed to make this work. I ended up creating a PR at #15520.

**Comment by syymza** [comment]
@sandersn thanks. should I close this one?

**Comment by sandersn** [comment]
Yes, seems like it.

**Pull request closed without merging**
