### PR TITLE
Adding definitions for the "plugapi" package

### PR DESCRIPTION
**Pull request by 4xiom5**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by aozgaa** [comment]
What are the objects in `namespace Enum`? Are they supposed to be instantiated, or would a library writer do something like 
```
bot.on(Enum.Events.ROOM_JOIN, function (room) {
    console.log("joined " + room);
});
```

What sort of type-safety or advice do the declarations under `namespace Enum` provide?

**Comment by aozgaa** [comment]
Please add or modify the test to exercise `PlugAPIStatic`

**Comment by BNedry** [comment]
Actually the enums are supposed to be in the PlugAPIStatic interface.
´´´
import * as PlugAPI from "plugapi"
bot.on(PlugAPI.events.ROOM_JOIN, function (room) {
    console.log("joined " + room);
});
´´´
 Unfortunately, it's impossible to add an enum in an interface so I used an interface and a var.
Do you know a proper way to do that ?

**Comment by BNedry** [comment]
The test file has been modified.

**Pull request merged**
