### PR TITLE
Update bluebird/index.d.ts from 'export =' to 'export default'

### PR DESCRIPTION
**Pull request by rummelsworth**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present. *Not present.*

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require
- [ ] Increase the version number in the header if appropriate. *Not appropriate.*

---

This change seems necessary because importing from a `export =`-declared module is incompatible with tsc option `"module": "es2015"`.

I encountered this issue while developing an angular 2 AoT project whose build uses rollup, which requires ES2015 modules.

### CODE REVIEW

**Comment by ericanderson** [comment]
This breaks tests in the following libraries:

- [ ] amqplib
- [ ] asana
- [ ] bluebird-retry
- [ ] project-oxford
- [ ] sequelize
- [ ] supertest-as-promised
- [ ] waterline

**Comment by lhecker** [comment]
@wrummler I'll run some actual tests tomorrow, but I don't think this PR will work even if you fix the typings @ericanderson listed here.

Bluebird is simply not an ES6, but rather a CommonJS module. `export = A` is equivalent to `module.exports = A` while `export default A` is (kinda) equivalent to `exports["default"] = A`.

As you can see it's not the same and cannot be used interchangeably. If Bluebird would be a ES6 module you'd have to write `const Bluebird = require("bluebird").default` every time in non-ES6 code, but as you know that's not the case which is why this PR contains incorrect typings.

But I'll take a proper look tomorrow. Promise. 🙂

**Comment by andy-ms** [comment]
Have you tried using [--allowSyntheticDefaultImports](http://www.typescriptlang.org/docs/handbook/compiler-options.html)?

**Comment by wrummler** [comment]
Thanks for the detailed explanation, @lhecker, and thanks for the pointer, @andy-ms. The former makes sense to me and the latter actually worked for my project. Learning me some tsc options for great good. 💯

I'll leave this PR open for now for @lhecker's feedback. The naivete that caused me to open it is also causing me to not be sure whether it contains a salvageable goal. If the verdict is closure, I'm okay by that. Thanks again.

**Comment by lhecker** [comment]
@wrummler Alright... What @andy-ms wrote is probably the only correct solution for this and I believe you can close this PR now.

In fact I didn't even know about this option yet. Up till now I always wrote

```
import * as Bluebird from "bluebird";
```

(which would have been another solution for this), but if I understand it correctly this option would allow me to write

```
import Bluebird from "bluebird";
```

while retaining the exact same code emit, right?

**Comment by andy-ms** [comment]
They won't have the same emit if you have `--module commonjs`: `import * as Bluebird from "bluebird"` will use `require("bluebird")` while `import Bluebird from "bluebird"` will use `require("bluebird").default`.
You can use `--module es6` and the emit will be exactly what you wrote: ES6 syntax. A tool like rollup will then have to handle translation to something that can run today. So, the handling of synthetic default exports must be done by some tool other than TypeScript.

**Comment by lhecker** [comment]
Thanks for the explanation @andy-ms!

**Pull request closed without merging**
