### PR TITLE
added definitions for postcss-load-config

### PR DESCRIPTION
**Pull request by bmatcuk**
This PR depends on [adding @types/cosmiconfig to dependenciesWhitelist.txt](https://github.com/microsoft/types-publisher/pull/621)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by bmatcuk** [comment]
CI failure will be resolved once my PR in types-publisher is accepted.

**Comment by bmatcuk** [comment]
Actually, hold off on this one for a moment... I've got a PR out to postcss-load-config to update the cosmiconfig version which could simplify this PR

**Comment by bmatcuk** [comment]
My PR with postcss-load-config has been accepted, so I updated this PR with the new definitions

**Review by rbuckton — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
