### PR TITLE
[IORedis] - Fix typing for getBuffer to `<Buffer | null>` for parity with library

### PR DESCRIPTION
**Pull request by ChrisBlair2019**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Link to ioredis type testing](https://github.com/luin/ioredis/blob/308017a6b9429c16b074e03e70f5524499476fa9/test/typing/commands.test-d.ts#L34)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ioredis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ioredis@latest/))
was missing the following properties:
1. createClient
1. defaultOptions
1. ScanStream
1. Pipeline
1. AbstractConnector

<details>
<summary>as well as these 5 other properties...</summary>
<p>SentinelConnector, SentinelIterator, ReplyError, Promise, print</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d45581d54ff7cd95e5ddf9623bae5c78da31c708
</p>

**Review by plantain-00 — APPROVED** [review]

**Comment by jakebailey** [comment]
This package appears to ship its own types (and they are linked to in the PR description); is there any reason to keep this package around anymore?

**Comment by plantain-00** [comment]
> This package appears to ship its own types (and they are linked to in the PR description); is there any reason to keep this package around anymore?

In 2019.10, the library author said `@types/ioredis` keep used. https://github.com/luin/ioredis/pull/981#issuecomment-538718567
In 2022.3, the library provides types, https://github.com/luin/ioredis/issues/1053
So I think `@types/ioredis` can be removed now.

**Comment by jakebailey** [comment]
I'll send a PR to remove these types instead.

**Review by jakebailey — APPROVED** [review]
I sent #62883, but that looks like it's going to be a little more tricky than I thought. Approving this in the meantime.

**Comment by jakebailey** [comment]
Closing; these types have now been removed (#62883).

**Pull request closed without merging**
