### PR TITLE
Type definitions for Highmaps 4.2.7 - Project: http://www.highcharts.…

### PR DESCRIPTION
**Pull request by AlbertOzimek**
…com/products/highmaps

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by AlbertOzimek** [comment]
Successfully added the highmaps

**Comment by zhengbli** [comment]
Do you own the product? Or does this product release via NPM? If so you can bundle the typing files directly with the npm package, that's the preferred way as it guarantees version matching.

**Comment by AlbertOzimek** [comment]
Highmaps is comertial product, however they don't have the typescript types. Please check the following thread:
http://forum.highcharts.com/highmaps-usage-f14/typescript-type-definition-for-highmaps-t32058/

Im my project we get the Typescript types from the npm.

I need the entry in the npm repository simmilar to this one:
https://www.npmjs.com/package/@types/highcharts
the new entry that I need is this:
https://www.npmjs.com/package/@types/highmaps

So for the highcharts we need this: @types/highcharts

In my application, if the dependency does not have a the Typescript type it is not loaded.

To make dependencies load properly and have clean solution I need @types/highmaps

Please let me know what I need to do next to see the @types/highmaps entry in npm

**Comment by AlbertOzimek** [comment]
So, I'm not he owner of the highcharts, but I know if I don't create the highcharts typescript types nobody will do it.

Please let me know what are the next steps of publishing the @types/highcharts into npm

**Comment by zhengbli** [comment]
Thanks for clarification. Can you add a `tslint.json` file per our requirement when adding a new package? (https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)

**Comment by AlbertOzimek** [comment]
Hi zhengbli,

I have created a new pull request:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14727

Please approve this pull request instead. I have found the better way way.

Highmaps are part of the highcharts.

When the map.js plagin is added to the highmaps is works
https://github.com/highcharts/highcharts/blob/master/lib/modules/map.js

Please approve the request: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14727

Let me know what are the next steps.

Albert Ozimek

**Comment by minestarks** [comment]
Closing this PR and looking at the other one as requested

**Pull request closed without merging**
