### PR TITLE
Any to unknow on @types/is-number

### PR DESCRIPTION
**Pull request by UltiRequiem**
unknow is the type-safe counter part of any
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
I'm not sure I understand the goal of this change - aren't `any` and `unknown` equivalent in a parameter position?

**Comment by UltiRequiem** [comment]
> I'm not sure I understand the goal of this change - aren't `any` and `unknown` equivalent in a parameter position?

Anything is assignable to unknown, but unknown isn’t assignable to anything but itself and any without a type assertion or a control flow based narrowing.

**Comment by amcasey** [comment]
> > I'm not sure I understand the goal of this change - aren't `any` and `unknown` equivalent in a parameter position?
> 
> Anything is assignable to unknown, but unknown isn’t assignable to anything but itself and any without a type assertion or a control flow based narrowing.

That's true, but what is that parameter going to be assigned to?

**Comment by UltiRequiem** [comment]
> > > I'm not sure I understand the goal of this change - aren't `any` and `unknown` equivalent in a parameter position?
> > 
> > 
> > Anything is assignable to unknown, but unknown isn’t assignable to anything but itself and any without a type assertion or a control flow based narrowing.
> 
> That's true, but what is that parameter going to be assigned to?

Nothing, but IMO it makes more sense to use unknown in this case.

**Review by amcasey — APPROVED** [review]
Since this shouldn't affect anyone using TS >= 3.0, it seems harmless enough.

**Comment by UltiRequiem** [comment]
Ready to merge

**Pull request merged**
