### PR TITLE
[validator] Add import test

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Improvement to existing type definition

This module can import subset so I add the related tests.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
:confused: The CI doesn't inform the authors.

/cc @tgfjt @chrootsu @IOAyman @louy

**Comment by TonyPythoneer** [comment]
@andy-ms I could put that #11402 discussion on hold.
I had defined the module can do import subset. If you are available, would you review this? :smile:

**Comment by tgfjt** [comment]
I don't understand why we need this test ❓

**Comment by TonyPythoneer** [comment]
@tgfjt  First, it proves that the module can import subset.
Second, It checks the subset import equals the function of the interface. 😄

**Comment by tgfjt** [comment]
IMO it's just a little too much verbose test.

**Comment by TonyPythoneer** [comment]
I know it's too much verbose.
But it's in order to ensure definition quality, it's required. :smile:

**Comment by TonyPythoneer** [comment]
@tgfjt Do you approve these changes? :smile:

**Comment by tgfjt** [comment]
👍

**Pull request merged**
