### PR TITLE
Node: specify `UnhandledRejectionListener` `reason` param type

### PR DESCRIPTION
**Pull request by OliverJAsh**
Same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33195, but updates types for v8/v9/10.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by islishude — APPROVED** [review]

**Comment by ostkrok** [comment]
Is this really correct?

https://nodejs.org/docs/latest-v10.x/api/process.html#process_event_unhandledrejection

**Comment by OliverJAsh** [comment]
Yes, a promise can reject with any type.

**Comment by ostkrok** [comment]
> Yes, a promise can reject with any type.

So shouldn't the old typing (`any`) be correct then?

This PR changes the type to be: an empty object, null or undefined.

**Comment by OliverJAsh** [comment]
`any` disables type checking, e.g.

``` ts
declare const foo: any;
any.whatever.goes.here // runtime exception!
```

Thus, `unknown` should be preferred.

`unknown` shipped in a recent version of TS, but these typings don't yet support that version. The type used here is like a "poor man's `unknown`"—it does the same thing.

**Comment by ostkrok** [comment]
Ahh, that makes sense.

Thanks for explaining!

**Pull request merged**
