### PR TITLE
Add missing types for Jexl 2.3.0

### PR DESCRIPTION
**Pull request by mikelamutxastegi**
Add missing types for Jexl 2.3.0.

### CODE REVIEW

**Review by m-tomczyk — CHANGES_REQUESTED** [review]
Hey, I'm sorry for taking so long, I'll look into this ticket later this day but I spotted one issue right now.
Types are for Jexl 2.3.0 but type definition header in index.d.ts is still pointing to 2.2.x
`// Type definitions for jexl 2.2`

**Comment by m-tomczyk** [comment]
Everything else looks good to me so I'll go for approve as soon as new version for those changes is set. Again, I'm sorry it took so long

**Comment by mikelamutxastegi** [comment]
Hi! Sorry for the mistake. I've just changed the type definition header in index.d.ts. Let me know if there is any other issue I need to fix. Thank you!

**Review by m-tomczyk — APPROVED** [review]
Lgtm

**Comment by mikelamutxastegi** [comment]
Ready to merge

**Pull request merged**
