### PR TITLE
Add createMarker function type to Leaflet Routing control

### PR DESCRIPTION
**Pull request by codingholt**

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/leaflet-routing-machine/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2331bd3c1092f887a414bff2aa68c4401c313e36
</p>

**Review by chanakadrathnayaka — COMMENTED** [review]
Hey, Thanks for the change. However I am unable to find the `createMarker` function in the original js library. Could you help me to find it please?

**Comment by codingholt** [comment]
Yes sure, check this line; [https://github.com/perliedman/leaflet-routing-machine/src/plan.js#L26](https://github.com/perliedman/leaflet-routing-machine/blob/04e899ea765cadae033d941e9de13846540ce69b/src/plan.js#L26)
Wanted to change the marker style as demonstrated in [this stackoverflow post.](https://stackoverflow.com/questions/41296413/how-to-replace-default-marker-to-custom-icon-in-waypoint-leaflet-routing) But I got some type errors, thats why opened this PR.

**Comment by chanakadrathnayaka** [comment]
The line you shared from the js library already has it's type as [a property of `PlanOptions`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2331bd3c1092f887a414bff2aa68c4401c313e36/types/leaflet-routing-machine/index.d.ts#L87) .

I also came across that stackoverflow post while I am looking for `createMarker` function. But it doesn't come from leaflet-routing-machine js library.

If `createMarker` is not implemented in the js library, It doesn't make sense to add to it's type definition.

**Review by sandersn — CHANGES_REQUESTED** [review]
Requested changes so the bot can track the status.

**Pull request closed without merging**
