### PR TITLE
[ember_routing] Add refresh method to router service

### PR DESCRIPTION
**Pull request by mydea**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/emberjs/ember.js/pull/19471
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Looks good! As on the other PR you opened, I'm blocking this till 4.0 comes out and we split the 3.x/4.x types. Thanks!

**Comment by chriskrycho** [comment]
@mydea for simplicity, I’ve integrated this directly into #58060.

**Comment by chriskrycho** [comment]
@mydea thanks again; this landed as 7ffcb40 (with you credited, of course).

**Comment by mydea** [comment]
:+1:

**Pull request closed without merging**
