### PR TITLE
[pdfjs-dist] use Promise instance of PDFPromise

### PR DESCRIPTION
**Pull request by lublak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mozilla/pdf.js/blob/e16c99fc020903d705ed7e81cbf3b83cf84e139b/src/shared/util.js#L930
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## pdfjs-dist ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pdfjs-dist@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'pdfjs-dist'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. build
1. LoopbackPort
1. renderTextLayer
1. AnnotationLayer

<details>
<summary>as well as these 132 other properties...</summary>
<p>createPromiseCapability, PasswordResponses, InvalidPDFException, MissingPDFException, SVGGraphics, NativeImageDecoding, PermissionFlag, UnexpectedResponseException, OPS, UNSUPPORTED_FEATURES, createValidAbsoluteUrl, createObjectURL, removeNullCharacters, shadow, ReadableStream, URL, RenderingCancelledException, getFilenameFromUrl, LinkTarget, addLinkAttributes, loadScript, apiCompatibilityParams, toRomanNumerals, arrayByteLength, arraysToBytes, assert, bytesToString, deprecated, getInheritableProperty, getLookupTableFactory, getVerbosityLevel, info, isArrayBuffer, isBool, isEmptyObj, isNum, isString, isSpace, isSameOrigin, isLittleEndian, isEvalSupported, log2, readInt8, readUint16, readUint32, setVerbosityLevel, string32, stringToBytes, stringToPDFString, stringToUTF8String, utf8StringToString, warn, unreachable, IDENTITY_MATRIX, FONT_IDENTITY_MATRIX, TextRenderingMode, ImageKind, AnnotationType, AnnotationFlag, AnnotationFieldFlag, AnnotationBorderStyleType, StreamType, FontType, PasswordException, UnknownErrorException, MissingDataException, XRefEntryException, XRefParseException, FormatError, AbortException, f, typeIsObject, createDataProperty, createArrayFromList, ArrayBufferCopy, CreateIterResultObject, IsFiniteNonNegativeNumber, InvokeOrNoop, PromiseInvokeOrNoop, PromiseInvokeOrPerformFallback, TransferArrayBuffer, ValidateAndNormalizeHighWaterMark, ValidateAndNormalizeQueuingStrategy, DequeueValue, EnqueueValueWithSize, PeekQueueValue, ResetQueue, TransformStream, IsReadableStreamDisturbed, ReadableStreamDefaultControllerClose, ReadableStreamDefaultControllerEnqueue, ReadableStreamDefaultControllerError, ReadableStreamDefaultControllerGetDesiredSize, AcquireWritableStreamDefaultWriter, IsWritableStream, IsWritableStreamLocked, WritableStream, WritableStreamAbort, WritableStreamDefaultControllerError, WritableStreamDefaultWriterCloseWithErrorPropagation, WritableStreamDefaultWriterRelease, WritableStreamDefaultWriterWrite, setPDFNetworkStreamFactory, PDFDocumentProxy, PDFPageProxy, DEFAULT_LINK_REL, DOMCanvasFactory, DOMCMapReaderFactory, DOMSVGFactory, PageViewport, StatTimer, DummyStatTimer, FontLoader, FontFaceObject, CanvasGraphics, getShadingPatternFromIR, TilingPattern, MessageHandler, Metadata, SimpleXMLParser, PDFDataTransportStream, WebGLContext, PDFNodeStream, createResponseStatusError, extractFilenameFromHeader, validateRangeRequestCapabilities, validateResponseStatus, getFilenameFromContentDispositionHeader, PDFFetchStream, PDFNetworkStream, NetworkManager, pdfjs-dist/build/pdf</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 82351bf3367ed7d08b332a5abad1e86aaa29d0ec
</p>

**Review by peterblazejewicz — APPROVED** [review]
This looks OK, should the version be bumped to 2.7 as one with only native Promise support?
https://github.com/mozilla/pdf.js/releases/tag/v2.7.570

**Review by peterblazejewicz — COMMENTED** [review]
Please review my coment about version bump, thx!

**Comment by lublak** [comment]
> 
> 
> Please review my coment about version bump, thx!
I think a version bump should be made.
Since it is possibly a breaking change.

**Comment by orta** [comment]
@lublak - you can make the change by editing the header of the .d.ts files 👍🏻

**Comment by lublak** [comment]
@orta year thank you.
And done!

**Review by peterblazejewicz — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Pull request merged**
