### PR TITLE
meteor: Set up a script to help us maintain the duplicate global and module typings.

### LINKED ISSUE #15071: Remove duplicate content
@birkskyum: About duplicate content. I think the Accounts module nested in meteor/accounts-base is necessary, in order to match the javascript, but can the global Accounts module be removed?

@fullflavedave: It would be great to remove all the duplication. This was created when Meteor added support for ES2015 modules (the global modules were the original). Does Meteor 1.4 still support global modules (e.g. for super quick prototyping)? If so, then the global module definitions probably need to be there for backwards compatibility. However, it would be great if the global Accounts module and the one nested in meteor/accounts-base referenced one set of definitions (and all other modules too). My TypeScript skills are a little out-dated, and I haven't fooled around to see if it's possible -- want to give it a try @birkskyum? Let's add a separate issue and continue discussion there.

@birkskyum: Sure, I'll have a look at it.

### PR DESCRIPTION
**Pull request by mattmccutchen**
Other minor fixes.

Fixes #15071 (as best we can without a massive breaking change).

My request for feedback on the approach in #15071 is still open, but I wanted to start the YSYL clock ticking.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: _(N/A)_
- [X] Increase the version number in the header if appropriate. _(N/A)_
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. _(Already there)_

### CODE REVIEW

**Comment by mattmccutchen** [comment]
I realized something: if `"meteor"` is excluded from the `"types"` compiler option, importing `"meteor/meteor"` (for example) used to partially work because the declaration file was named `meteor.d.ts`, but this PR proposes to rename the file to `meteor_module.d.ts`, which would make the import not work at all.  However, the import never worked completely because the module declarations are sloppy and refer to some of the global declarations, which don't get loaded when `"meteor"` is excluded from `"types"`.  I could rename `meteor_module.d.ts` back to `meteor.d.ts` and so forth to maintain the status quo.  I could additionally fix the sloppiness at the expense of (1) making meteor-dup-typings a little more complicated and (2) conceivably breaking some existing code that uses the module declarations and augments the global declarations, expecting them to be used by the module declarations.  Opinions?  Is anyone other than me even still using `@types/meteor`?  Someone is bumping the download counter on the NPM registry, but I don't know who.

**Comment by andrei-markeev** [comment]
Isn't it so that generating globals from module is actually a better approach as it doesn't require those placeholders in the comments?

Also, how is it supposed to be used? Should we always run the script manually after some update? If yes, is there any way to avoid it / incorporate it into the CI pipeline?

**Comment by mattmccutchen** [comment]
@andrei-markeev, thanks for the feedback.

> Isn't it so that generating globals from module is actually a better approach as it doesn't require those placeholders in the comments?

Sure, I've switched the script to go that way.

> Should we always run the script manually after some update?

Yes.

> If yes, is there any way to avoid it / incorporate it into the CI pipeline?

I doubt the DefinitelyTyped maintainers will want to make a special case for the Meteor typings.  Let's ask @andy-ms, who was the last one (to my knowledge) to introduce an inconsistency between the two sets of definitions, in 36735d136a29a107600a658bf15e02a941c2bff6.  However, if the answer is no or we don't get an answer in a few more days (this PR has already waited long enough), I don't think the lack of automation should block this PR.  Even if people sometimes forget to run the script, having a script at all is a big improvement compared to the status quo.

One thing we could do is have module and global copies of the tests (where applicable), so that hopefully if someone enables a new strict option that breaks the definitions, the failure will show up in both versions of the tests and the person will fix both versions of the definitions.  Would you like me to do that?

**Comment by mattmccutchen** [comment]
Recommitted to trigger the CI again.

**Comment by mattmccutchen** [comment]
Thanks @andy-ms for the input!

> I'm wondering if it would be feasible to just change all global augmentations on DT to module augmentations, then point the globals to the module versions?

Pointing a top-level global to something from a module requires some ugly hacks, which fortunately I am well familiar with. :smile:

> If something just augments the global that would be a problem for people using the module version, and since these are copy-pasted rather than linked it would be necessary to do the augmentation twice.

Yes, those problems both exist in the status quo, and presumably anyone affected has worked around them.  If we do as you suggest, then we immediately break anyone who is augmenting the global declarations, whether or not they are also augmenting the module declarations.  That would include [my own app](https://bitbucket.org/espalier-spreadsheet/espalier/) and a few other declarations in DefinitelyTyped, which I am happy to update; I don't know how many others outside DefinitelyTyped will be affected.  In the absence of input from others with authority, I proposed to make the most conservative change possible to get the duplication under control in preparation for contributing other enhancements to the Meteor typings, but if you think it is right to impose this one-time pain on the community to reach a better state, I will do it.

**Comment by andy-ms** [comment]
OK, I see -- probably better to maintain the duplicate definitions then.
We wouldn't run this script in CI but it's OK to have it.

**Comment by mattmccutchen** [comment]
@andrei-markeev I've addressed all of your comments except I didn't want to put `generate-globals` in the `globals` directory because it's easiest for the script to delete and recreate the entire directory.  Is the PR satisfactory to you now?

**Comment by andrei-markeev** [comment]
Yes it is now much cleaner, thank you!

One small thing still, I'm now trying to run `node scripts\generate-globals` and getting empty files under globals. Any ideas what could be wrong there?

image

Btw great that the script is now typescript 👍

**Comment by andrei-markeev** [comment]
Ah ok got it. It's Windows and it's CRLF.
Could you apply this small fix please?
```javascript
let inLines = fs.readFileSync(inFile, "UTF-8").split(/\r?\n/);
```

**Review by andrei-markeev — APPROVED** [review]

**Comment by mattmccutchen** [comment]
> Btw great that the script is now typescript

Yes, that was only feasible way to parse the `tsconfig.json` without additional dependencies, so I was forced to learn how to read and write files in Node.js. :/

> Could you apply this small fix please?

Thanks for tracking down the problem.  I opted to use `os.EOL` instead.

**Comment by andrei-markeev** [comment]
Yes, I re-tested and it works now!
Thanks for your efforts trying to get us rid of those duplicates! 🤝

**Pull request merged**
