### PR TITLE
added types for lodash-es

### PR DESCRIPTION
**Pull request by stephenlautier**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

Also i tried to contribute this to the lodash-es itself, however the author doesn't want to accept it.
https://github.com/lodash/lodash/pull/2837

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Awesome!

**Comment by Belev** [comment]
When is this expected to go in master?

**Comment by sandersn** [comment]
As far as I know we are going to turn types-2.0 into master in a few weeks. Until then, `@types` on npm comes from the types-2.0 branch, so we're not merging anything back into master.

**Comment by Belev** [comment]
Cool, thanks @sandersn.

**Comment by stephenlautier** [comment]
@sandersn, is there a reason why its not published yet? It has been merged 4days ago, and according to the FAQ it should take 1hr.

https://www.npmjs.com/package/@types/lodash-es

**Comment by Belev** [comment]
@stephenlautier it is working now.

**Comment by stephenlautier** [comment]
@Belev cheers for the update!

**Pull request merged**
