### PR TITLE
Remove outdated OTHER_FILES

### PR DESCRIPTION
**Pull request by sandersn**
The new @definitelytyped/* packages are better at finding used files in name-mangled packages: https://github.com/microsoft/DefinitelyTyped-tools/pull/93

### CODE REVIEW

**Comment by jablko** [comment]
@sandersn Please see #44091

**Comment by sandersn** [comment]
@jablko That PR over-removes OTHER_FILES.txt and fails in the other direction, though.

@aaronmcadam
@bastibuck
@NoriSte
@wKovacs64
@existentialism
@airato
@simjes

I had to bump `@testing-library/cypress`' minimum TS version to 3.8 because it depends on cypress@latest, which in turn depends on prettier, which requires TS 3.8. It should be possible to downgrade cypress to a version that works with 3.3 or 3.4, but I didn't have time to do that since this is blocking all DT PRs. If supporting old TS versions is important, can you try to downgrade `@testing-library/cypress`'s `cypress` dependency?

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## feathersjs__errors ([<kbd>unpkg</kbd>](https://unpkg.com/browse/feathersjs__errors@latest/))
was missing the following properties:
1. 400
1. 401
1. 402
1. 403
1. 404

<details>
<summary>as well as these 11 other properties...</summary>
<p>405, 406, 408, 409, 411, 422, 429, 500, 501, 502, 503</p>
</details>

## hapi__nes ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__nes@latest/))
was missing the following properties:
1. plugin
1. plugin
## markedjs__html-differ ([<kbd>unpkg</kbd>](https://unpkg.com/browse/markedjs__html-differ@latest/))
was missing the following properties:
1. diffHtml
1. isEqual
## testing-library__cypress ([<kbd>unpkg</kbd>](https://unpkg.com/browse/testing-library__cypress@latest/))
was missing the following properties:
1. commands
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6e438b09754696e9dc15a958b980280bcc95b354
</p>

**Comment by jablko** [comment]
@sandersn Okay. I did just test it locally but must have missed something. Thanks for your help.

**Comment by sandersn** [comment]
Oh, I see, the CI runs are from before the change. I didn't notice that.

**Comment by sandersn** [comment]
I think I'll take this one anyway because it needs to bump `@testing-library/cypress`' version.

**Comment by jablko** [comment]
All good. FYI I've prepared #44092 for microsoft/DefinitelyTyped-tools#95 and #44382 for microsoft/DefinitelyTyped-tools#100.

**Pull request merged**
