### PR TITLE
Copy ramda commonjs package type declaration file

### PR DESCRIPTION
**Pull request by samMeow**
Considering ramda repository has also provide commonJS build to allow partial import. (https://github.com/ramda/ramda/blob/master/package.json#L62)
It would be more convince if declaration files can cover those packages.
Please fill in this template.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (https://github.com/ramda/ramda/blob/master/package.json#L62)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
I don't understand what's going on here. If ramda supports commonjs exports, I think this change should use `export =` instead of `export default`, at least.

Can you take a look,
@donnut @tycho01 @mdekrey @mrdziuban @sbking @afharo @teves-castro @1M0reBug @hojberg @samsonkeung @angeloocana @raynerd @googol @moshensky @ethanresnick @leighman @CaptJakk @deftomat @deptno @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh ?

**Comment by weswigham** [comment]
naw @sandersn this seems right to me - ramda compiles from esm to cjs, so it actually does make a member named "default" within each of these modules in its cjs output folder.

**Comment by guillaumep** [comment]
@weswigham This should have not been merged, tests are failing.

**Comment by weswigham** [comment]
They are, but this isn't what caused it - a change in TS@next did, and the (some of the) ramda definition authors are aware of the change. One of the failures has a corresponding open bug on TS itself.

**Comment by sandersn** [comment]
@weswigham I don't see it on unpkg at least, trying to recreate commonjs resolution logic. Where is the code that exports a "default" member?

**Comment by weswigham** [comment]
I'd thought [here](https://github.com/ramda/ramda/blob/master/package.json#L62). The input source is esm, which is babel'd to produce output. Looks like it's still using babel 6, tho, which has a non-interopy default behavior for standalone defaults, where the default is transpiled to a namespace assignment. Looks like all the cjs files need to use `export =` rather than `export default`, despite what the source in the repo would imply. :(

**Pull request merged**
