### PR TITLE
Update gulp-useref to version 3.0.0

### PR DESCRIPTION
**Pull request by tkrotoff**

### CODE REVIEW

**Comment by tkrotoff** [comment]
to myself: :+1: :-)

**Comment by tomc974** [comment]
@tkrotoff It would be easier for reviewers to have one PR per updated module

:+1: for commit f9a085d (gulp-typescript). I know nothing about the other modules though.

**Comment by tkrotoff** [comment]
@tomc974 I know but here it is not possible:
- gulp-rev-replace-tests.ts [uses gulp-useref](https://github.com/tkrotoff/DefinitelyTyped/commit/a2e956e0f1bf38a0713c90f1164e1d6462ad6e45#diff-c6ccb3dbe3e0ec267498acb2be926e92R13) and thus needs to be updated
- gulp-useref-tests.ts features [one example that uses gulp-typescript](https://github.com/tkrotoff/DefinitelyTyped/commit/877a6206a148c3212dead5b74923a5e43ed039b3#diff-691d118447a92da0b5d4ac46fc952f6bR57) (examples taken from [gulp-useref README](https://github.com/jonkemp/gulp-useref#optionsadditionalstreams)) thus the gulp-typescript fix is needed

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
