### PR TITLE
[fbt] Update `fbt()` return type

### PR DESCRIPTION
**Pull request by retyui**
Initially returns `fbt(): string[]` and developers need to cast that array to string 
 
But in runtime `fbt` returns an mixed magic object (is a react element  and object and string)

```tsx
import { isValidElement } from 'react';
import {GenderConst, IntlVariations, fbs, fbt, init} from 'fbt';

const withParams = fbt('Hello, ' + fbt.param('name', 'retyui'), 'param example');

typeof withParams; // object (jsx element)
withParams.toString() // "Hello, retyui"
JSON.stringify(withParams) // "\"Hello, retyui\""
isValidElement(withParams) // true
```

So to simplify developers life this PR exists ...

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/fbt/docs/getting_started_react_native#notes
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by alexandernanberg — APPROVED** [review]

**Comment by retyui** [comment]
Ready to merge

**Review by alexandernanberg — APPROVED** [review]

**Comment by retyui** [comment]
Ready to merge

**Comment by retyui** [comment]
omg, Everything  is green!

**Comment by retyui** [comment]
Added test to fix `clock1 Only a DT maintainer can approve changes without tests`

**Review by alexandernanberg — APPROVED** [review]

**Comment by retyui** [comment]
Ready to merge

**Pull request merged**
