### PR TITLE
Update angular2 typings for alpha.28.

### PR DESCRIPTION
**Pull request by alexeagle**
[Review on Reviewable](https://reviewable.io/reviews/borisyankov/definitelytyped/4738)

### CODE REVIEW

**Comment by alexeagle** [comment]
Hi there, I'm not sure we should include the `angular2.d.ts` unversioned file. We are still making breaking changes so it's generally not going to work with newer runtime source bundles. Maybe we should break your rules, and only have the versioned files?

**Comment by alexeagle** [comment]
ping!

**Comment by vvakame** [comment]
@alexeagle We manage only the most recent one version. (but we have a lot of exception :wink: 

@basarat

**Comment by basarat** [comment]
> We are still making breaking changes so it's generally not going to work with newer runtime source bundles

Did you mean *older* runtime source bundles?

> Maybe we should break your rules, and only have the versioned files

Better to have the unversioned files as `tsd query angular2` and nuget ([https://www.nuget.org/packages?q=angular2](link)) will show the unversioned version. Like @vvakame said *we manage only the most recent one version*, so if you want you can drop the *older `alpha` versions* but we are happy to keep them.

**Comment by jpsfs** [comment]
@alexeagle Sorry to bother you.
Any update on typings for alpha 30?

Cheers!

**Comment by alexeagle** [comment]
We are working on the alpha30 dts right now.

**Pull request merged**
