### PR TITLE
add typings for d3-slider

### PR DESCRIPTION
**Pull request by lk-chen**
Typings for [d3-slider](https://github.com/MasterMaps/d3-slider)
- [x] checked compilation succeeds with `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by vvakame** [comment]
This target library is not publish to npm?
check this document.
http://definitelytyped.org/guides/contributing.html#naming-the-file
https://github.com/MasterMaps/d3-slider/blob/master/package.json#L2

**Comment by lk-chen** [comment]
@vvakame No, it is not published on npm. But it is registered on bower.

**Comment by vvakame** [comment]
I found https://bower.io/search/?q=d3.slider
please rename d3-slider to d3.slider

**Comment by lk-chen** [comment]
@vvakame renamed to d3.slider

**Pull request merged**
