### PR TITLE
[react-native-vector-icons] Change color types to include opaque colors

### PR DESCRIPTION
**Pull request by svbutko**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/oblador/react-native-vector-icons/pull/574
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by indentedspace** [comment]
I don't think `ColorValue` is the right type to put here for your needs. The change you've linked explicitly mentions that color can now be a `number`, and `ColorValue` is essentially `symbol | string`. You might want to use [ProcessedColorValue](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L6063) instead if you want to be able to pass a `number` value to the color prop.

Either way, please modify the test file to include a case where the color is an opaque/transparent value to ensure that this change works as intended.

**Review by codebure-au — CHANGES_REQUESTED** [review]
Please add tests for this new color prop type

**Comment by svbutko** [comment]
@indentedspace sorry, my bad, it's just the closes reference I could find regarding opaque colors, I've added tests as requested

**Review by codebure-au — APPROVED** [review]

**Comment by svbutko** [comment]
Ready to merge

**Pull request merged**
