### PR TITLE
Updated the ol.control.Attribution class with constructor and methods.

### PR DESCRIPTION
**Pull request by rgvassar**
case 2. Improvement to existing type definition.

Documentation: http://openlayers.org/en/latest/apidoc/ol.control.Attribution.html

### CODE REVIEW

**Comment by andy-ms** [comment]
* `render` is probably meant to be `() => void`.
* Not sure what the point of having a `@param mapEvent` comment is if there's no extra documentation provided for it.

**Comment by rgvassar** [comment]
I recommend contacting the OpenLayers team, if you think their documentation is wrong on the render method. Hey @vvakame, can we merge this, since we haven't heard anything from the author yet?

**Comment by andy-ms** [comment]
OpenLayers isn't necessarily using TypeScript syntax for the types in their documentation, so they can't necessarily be copied verbatim. In TypeScript, `Function` is a very broad type, covering functions of any type. `() => void` is more specific.

**Comment by rgvassar** [comment]
@andy-ms I thought you were talking about the render method that had the `@param mapEvent` jsdoc on it. I used the `Function` type on the other render method because I'm not sure that `() => void` is correct. The documentation says it is called in a `requestAnimationFrame` callback, which I believe can receive an argument. I wasn't sure, so I'd rather not explicitly say that it receives no arguments.

**Comment by andy-ms** [comment]
According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) this would provide a number representing the current time. But openlayers may not actually provide this. Merging this since `Function` will at least work for now.

**Pull request merged**
