### PR TITLE
new typings: sprintf-js, json5, dsv.  commonjs support for paralleljs

### PR DESCRIPTION
**Pull request by jasonswearingen**

### CODE REVIEW

**Comment by vvakame** [comment]
*dsv/dsv.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/dsv
  * http://bower.io/search/?q=dsv
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (dsv/dsv-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*json5/json5.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/json5
  * http://bower.io/search/?q=json5
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (json5/json5-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*parallel/parallel.d.ts*

to author(@jbaldwin). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*sprintf-js/sprintf-js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/sprintf-js
  * http://bower.io/search/?q=sprintf-js
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (sprintf-js/sprintf-js-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@jasonswearingen thank you for your contributions.
please rename *-test.ts to *-tests.ts.

**Comment by mtraynham** [comment]
In the browser, I think sprintf-js automatically appends to the window.
https://github.com/alexei/sprintf.js/blob/master/src/sprintf.js#L195

I had to instead do:
#### sprintf.d.ts
```
declare module 'sprintf' {
    interface SprintF {
        (fmt: string, ...args: any[]): string;
    }
    var sprintf: SprintF;
    export = sprintf;
}
```
#### vsprintf.d.ts
```
declare module 'vsprintf' {
    interface VSprintF {
        (fmt: string, args: any[]): string;
    }
    var vsprintf: VSprintF;
    export = vsprintf;
}
```

**Comment by jasonswearingen** [comment]
renamed test files to *-tests.ts

**Comment by vvakame** [comment]
@mtraynham I think this code is more better.

```
interface Window {
  sprintf(fmt: string, ...args: any[]): string;
  vsprintf(fmt: string, args: any[]): string;
}
```

**Comment by vvakame** [comment]
@jasonswearingen thanks mate!

**Comment by mtraynham** [comment]
@vvakame That does look better :)

**Pull request merged**
