### PR TITLE
localPort and localAdress can undefined

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [docs]( https://nodejs.org/api/net.html#net_socket_localaddress). The documentation does not say that it can contain undefined. But my experiments have shown what it can.
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by weswigham — CHANGES_REQUESTED** [review]
The docs linked don't indicate the value can be `undefined`, and I don't know any examples when they are offhand - can you provide such an example? (And maybe also make a PR to the node docs?)

**Comment by Vector1dev** [comment]
@weswigham Yes I can provide an example. This happens when using Unix Socket.
```
let net = require('net');

let unixServer = net.createServer(function(client) {
    console.log(client.localPort, client.localAddres); // Prints "undefined undefined"
});
unixServer.listen('sock'); 

setTimeout(() => {
    net.createConnection("sock");
}, 200);
```

**Comment by peterblazejewicz** [comment]
It also happens before actual underlying transport has been created (that is before `connect` is used). am I right?

**Review by LinusU — APPROVED** [review]
> The docs linked don't indicate the value can be `undefined`, [...]

I _think_ that the Node.js documentation usually doesn't document nullability of values, which is a bit unfortunate 🤔

> Yes I can provide an example. This happens when using Unix Socket.

Tested the example myself and it does indeed print `undefined, undefined`.

**Pull request merged**
