### PR TITLE
[selenium-webdriver]: types for bidi BrowsingContext

### PR DESCRIPTION
**Pull request by harsha509**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/selenium-webdriver/bidi/browsingContextTypes.d.ts
1. types/selenium-webdriver/bidi/protocolValue.d.ts
1. types/selenium-webdriver/bidi/captureScreenshotParameters.d.ts
1. types/selenium-webdriver/bidi/createContextParameters.d.ts
1. types/selenium-webdriver/bidi/browsingContext.d.ts

<details>
<summary>as well as these 2 other files...</summary>
<p>types/selenium-webdriver/bidi/clipRectangle.d.ts, types/selenium-webdriver/index.d.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 81e0a1c423c7b561d4d0850f23dd7210196b4e0e
</p>

**Review by SupernaviX — APPROVED** [review]
looks totally good

**Comment by harsha509** [comment]
Ready to merge

**Comment by Zzz-101** [comment]
@harsha509  Thank you for your contribution. Can you help me understand why both `#` and `private` are being used to make these lines inaccessible? Can a single pattern satisfy the requirements? Thank you for your feedback. CC: @SupernaviX

**Pull request merged**
