### PR TITLE
Updated FHIR types for Release 3 (STU)

### PR DESCRIPTION
**Pull request by meirgottlieb**
These are the updated types for Release 3 of FHIR. You can read more about it here: http://hl7.org/fhir/diff.html.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@meirgottlieb I'd love to chat about this file sometime. Can you email me? ryanca@microsoft.com

**Comment by meirgottlieb** [comment]
I emailed you.

**Comment by fud** [comment]
@meirgottlieb Hello! Wondering if you're working on an update for Release 4?

**Comment by meirgottlieb** [comment]
Hey @fud. I don't have any current plans to update for Release 4. However, the generator is open source here: https://github.com/artifacthealth/fhir-dts-generator.

**Comment by fud** [comment]
@meirgottlieb Thanks I'll check that out.

**Pull request merged**
