### PR TITLE
Add webpack

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by Zorgatone** [comment]
Why hasn't this been merged yet?

**Comment by tkqubo** [comment]
Since it's just made hours ago :rocket: 

And some plugin typings are not well-considered so refinements are needed by further PRs :smile:

**Comment by Zorgatone** [comment]
Oh, my bad... I thought I had read something like "weeks ago" :grin:

**Comment by tkqubo** [comment]
:+1:

**Comment by vvakame** [comment]
*webpack/webpack.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/webpack
  * http://bower.io/search/?q=webpack
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (webpack/webpack-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
