### PR TITLE
plotly.js: Add Plotly.Icons constant

### PR DESCRIPTION
**Pull request by miccehedin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/plotly/plotly.js/blob/master/src/fonts/ploticon.js

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. Fx
1. Snapshot
1. PlotSchema
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c857369da263b12eabb2ba8dbd9974d8668a960d
</p>

**Review by lindapaiste — APPROVED** [review]
Looks good.  The types could potentially be more specific about which properties these icons contain, since all except for `newplotlylogo` have the properties `width`, `height`, `path`, and `transform` defined.  But that's probably overkill and it's doubtful that a user would want to access these properties directly.  Should be sufficient to say that it's an `Icon`.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@miccehedin thanks!

**Comment by miccehedin** [comment]
Ready to merge

**Review by peterblazejewicz — APPROVED** [review]

**Comment by miccehedin** [comment]
Ready to merge

**Pull request merged**
