### PR TITLE
fix type issue in @types/supertest v6: supertest.agent is not expected to be called with `new`

### PR DESCRIPTION
**Pull request by ignatiusreza**
image

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Example from supertest README.md](https://github.com/ladjs/supertest/blob/master/README.md#example)

  image

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by DavidTanner — APPROVED** [review]

**Review by DavidTanner — APPROVED** [review]
The source code should handle with or without `new`.

https://github.com/ladjs/supertest/blob/c1b8f9da7b58a5ffe6bf6a1b5056435a21d3c365/lib/agent.js#L27

**Comment by ignatiusreza** [comment]
Correct.. if you prefer, we can expand the types test to cover both with and without `new`..

but I believe, the fact that it is working with `new` is implementation details.. all example in the README, and in the test cases are writing without `new`.. wdyt?

**Review by sandersn — APPROVED** [review]

**Comment by DavidTanner** [comment]
Either way. I don't mind not having the tests, as they weren't there before.

**Comment by ignatiusreza** [comment]
Then let's keep it as is, as it matches the example in the readme.

This is ready to merge

**Comment by ignatiusreza** [comment]
Ready to merge

**Pull request merged**
