### PR TITLE
ari-client: add missing `start():Promise` signature

### PR DESCRIPTION
**Pull request by vash1486**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [node-ari-client](https://github.com/asterisk/node-ari-client)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by dioris-moreno — CHANGES_REQUESTED** [review]
I checked client.js of node-ari-client and the resolve() function is called without arguments:

`
480      // onced, will not be called when an automatic reconnect succeeds.
481      resolve();
`

, so the returned value of the promise should be void as follows.

`
37      start(apps: string | string[], subscribeAll?: boolean): Promise<void>; 
`

**Comment by vash1486** [comment]
Oops, you're right! I assumed that the same parameters were passed... fixed :)

**Review by dioris-moreno — APPROVED** [review]
Perfect. 💯

**Comment by gabritto** [comment]
thanks. please consider also updating the tests in the future.

**Pull request merged**
