### PR TITLE
aws-lambda Authorizer response context only allows booleans, numbers and strings

### PR DESCRIPTION
**Pull request by richardcornelissen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by richardcornelissen** [comment]
Doesn't seem like typescript-bot is in a good mood. Copying from last PR.

🔔 @skarum @tobyhede @buggy @y13i @wwwy3y3 @OrthoDex @MichaelMarner @daniel-cottone @kostya-misura @coderbyheart @palmithor @daniloraisi @simonbuchan @Haydabase @repl-chris @aneilbaboo @jeznag @louislarry @dpapukchiev @ohookins @trevor-leach @jagregory @dalen - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32855/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

If no reviewer appears after a week, a DefinitelyTyped maintainer will review the PR instead.

**Comment by simonbuchan** [comment]
> You can access the stringKey, numberKey, or booleanKey value (for example, "value", "1", or "true") of the context map in a mapping template by calling $context.authorizer.stringKey, $context.authorizer.numberKey, or $context.authorizer.booleanKey, respectively. The returned values are all stringified. Notice that you cannot set a JSON object or array as a valid value of any key in the context map.

This implies to me that despite the bizarre wording and examples, the actual value types will always be a `string`?

**Comment by richardcornelissen** [comment]
> > You can access the stringKey, numberKey, or booleanKey value (for example, "value", "1", or "true") of the context map in a mapping template by calling $context.authorizer.stringKey, $context.authorizer.numberKey, or $context.authorizer.booleanKey, respectively. The returned values are all stringified. Notice that you cannot set a JSON object or array as a valid value of any key in the context map.
> 
> This implies to me that despite the bizarre wording and examples, the actual value types will always be a `string`?

Tested a few cases with a custom authorizer function that returns IAM policies (and returns an Unauthorized if the policy does not match AWS' schema):
- Integers are allowed;
- Floating point numbers are allowed;
- Booleans are allowed;
- Strings are allowed;
- Arrays are not allowed;
- Objects are not allowed;
- Nulls are not allowed.

Perhaps policies are allowed booleans and numbers, but are stored and cached as strings.

**Review by simonbuchan — APPROVED** [review]
Thanks for checking! AWS docs are irritatingly misleading sometimes.

**Comment by penguinbroker** [comment]
I think this update should be reverted. The response context actually supports objects as well. Using a cognito pool as an authorizer for an api gateway that proxies to a lambda causes the cognito claims to be added as an object on the Authorizer response context.

**Comment by kossmoboleat** [comment]
This should really be reverted, I think. Someone has opened a [separate issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34059) with an alternative, but until that's completed this PR's change isn't correct and should be reverted.

**Comment by simonbuchan** [comment]
Sure.

**Pull request merged**
