### PR TITLE
Add types for youtube-api

### PR DESCRIPTION
**Pull request by KonradPerlicki**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by KonradPerlicki** [comment]
Yes it is, but package [youtube-api](https://www.npmjs.com/package/youtube-api) doesn't have typings to use them, besides that, it also provides two more functions on top of that and I'd like to add types for them

**Comment by jakebailey** [comment]
Oh, this is for an npm package. Gotcha.

**Comment by jakebailey** [comment]
In which case pulling in the `gapi` packages may not be idea, as they create globals, IIRC, sorry for the mixup.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## youtube-api ([<kbd>unpkg</kbd>](https://unpkg.com/browse/youtube-api@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'youtube-api'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 981efe580c088f62f660035e18804bb45bb689af
</p>

**Comment by jakebailey** [comment]
Seems like you're going to need to use the namespace + function merge pattern here to get the exports right.

**Comment by KonradPerlicki** [comment]
I achieved proper behavior by adding new() into an interface, but I have some problems with running npm run test-all and I can't test it with strict validation rules as here, maybe you have seen this error before?

image

**Comment by jakebailey** [comment]
I don't recommend using `test-all` given you're only adding a package, you should be running `npm test youtube-api` from the repo root to just test this one package.

Not sure about the error, though; are you on Windows?

**Comment by jakebailey** [comment]
Er, what failed tests? This is a new definition; it can't possibly cause errors in other packages, and that's what test-all does, run the entire repo.

**Comment by KonradPerlicki** [comment]
For example failed because of googleapis which was not in allowedpackages.txt and other one was because of not exporting like export = variable or that it's not recommended to use file with single declare module sth like that

**Comment by KonradPerlicki** [comment]
It looks like googleapis is making the tests run out of memory...

**Comment by jakebailey** [comment]
I was afraid of this when I saw the size of that package. You may need to cut down what things you declare, or be really, really careful about which subpaths get imported. But, not sure if that's tenable.

**Comment by jakebailey** [comment]
Related is: https://github.com/googleapis/google-api-nodejs-client/issues/2187

Maybe there's an `@googleapis/*` package which has the bits you need.

**Comment by KonradPerlicki** [comment]
The problem is I need an interface 'GoogleApis' which has properties for all its modules not only which is used... :/

**Pull request closed without merging**
