### PR TITLE
Update systemjs

### PR DESCRIPTION
**Pull request by unional**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.

https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjssetmodulename-module
In the comment:

> it is usually necessary to run SystemJS.set(SystemJS.resolveSync('custom-module'), SystemJS.newModule({ prop: 'value' }));

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
:+1:

**Comment by unional** [comment]
Also added `resolve()`

**Comment by unional** [comment]
And add the missing optional `parentName`

I've updated the docs in `systemjs`: https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjsresolvesyncmodulename-parentname---string

**Comment by GiedriusGrabauskas** [comment]
Cool, thanks 👍

**Pull request merged**
