### PR TITLE
lodash types compatibility with TypeScript 2.2

### PR DESCRIPTION
**Pull request by AviVahl**
In TypeScript 2.2, WeakMap's has a key that extends **object**. This broke lodash's types.
Updated code, tests, and marked file as requiring ts2.2
Also updated isWeakMap with the change.

See: https://github.com/Microsoft/TypeScript/blob/release-2.2/lib/lib.es2015.collection.d.ts#L45

Please review and merge if possible, as lodash is widely used, and 2.2.1 was just released to stable.

### CODE REVIEW

**Comment by AviVahl** [comment]
Travis is running ts 2.1, so it will fail on not knowing the new object type.

**Comment by mhegazy** [comment]
This will force users to move to TS 2.2 (released yesterday) to get new updates. We should wait for a 4-6 weeks before making this change.

**Comment by jmezach** [comment]
I'm sorry, but how does delaying releasing this help anyone? Right now, people who want to move to TS 2.2 can't because of the conflicting type definitions for lodash (unless they aren't using lodash of course). But people will want to move to TS 2.2 eventually, so delaying releasing this is just delaying the inevitable.

Why can't this be released as a breaking change for people who want to move to TS 2.2, while not breaking anyone still using TS 2.1? That is the whole point of semver isn't it?

**Comment by daprahamian** [comment]
This is breaking the builds on over 20 of my enterprise-level applications right now. Please get this in ASAP.

**Comment by alitaheri** [comment]
@mhegazy The projects that don't want to update their typescript can simply lock lodash to the previous version. But the ones wanting to migrate will have a really hard time. I for one have to manually add the extra lines to the typings every time I run `npm install`.

**Comment by AviVahl** [comment]
Merged master into pull request. It seems type guard were removed from isWeakMap.

I personally think this isn't the correct way to deal with backward/forward compatibility issues.

Removing the type guard and changing it to boolean **changed the behavior** of the type checking (it no longer assumes the thing is WeakMap).

The real question here is: can we use new language features in types packages? For my prespective, changing it to boolean is like shooting ourselves in the foot. This reduces the accuracy of the types package just to be compatible with both older and newer TypeScript versions.

**Comment by paulvanbrenk** [comment]
@AviVahl can you rebase against master. Hopefully that resolves the CI issues

**Comment by AviVahl** [comment]
@paulvanbrenk @mhegazy merged master. Travis is currently running. (for some reason it tries ts2.1 first and then

**Comment by AviVahl** [comment]
It failed. Is types-publisher expecting me to add `// TypeScript Version: 2.2` to even d.ts file in a subfolder of lodash?

**Comment by mhegazy** [comment]
All dependencies of lodash needs to be pumped up to 2.2 as well. see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994 for an example when it was moved to 2.1.

**Comment by AviVahl** [comment]
Thanks for the tip. Found `scripts/generate-modules.ts`
Lets see how Travis behaves now...

**Comment by AviVahl** [comment]
@mhegazy Thanks again for the tip.
Changed all liabilities of lodash to ts 2.2 as well (used listing of errors in Travis).
Build is now passing.
Also reduced change noise (had to update the script to match the current white-spacing of the lint files, etc...).

This is ready for review.

**Review by mhegazy — APPROVED** [review]

**Pull request merged**
