### PR TITLE
Create three-EarthControls.d.ts

### PR DESCRIPTION
**Pull request by pksorensen**

### CODE REVIEW

**Comment by s093294** [comment]
This is ready. It adds the EarthControls class for https://github.com/potree/potree/blob/master/src/EarthControls.js

Will add methods/members on later iteration.

**Comment by vvakame** [comment]
@gyohk could you review this PR?

**Comment by gyohk** [comment]
Is it included in the original three.js repository?
https://github.com/mrdoob/three.js/tree/master/examples/js/controls

**Comment by gyohk** [comment]
Thank you for this PR.
Is it included in the original three.js repository?
https://github.com/mrdoob/three.js/tree/master/examples/js/controls/

**Comment by gyohk** [comment]
@s093294 Thank you for this PR.
Is it included in the original three.js repository?
https://github.com/mrdoob/three.js/tree/master/examples/js/controls/

**Comment by s093294** [comment]
TBH I was not sure if it was included - i just added the PR due to needing the definitions at build the other day and I intuitive when looking in the Three folder for TSD to find it and assumed this would be a logical place to put it as the library that was depending on it do not have any definition files as of yet.

**Comment by s093294** [comment]
They are not part of the official three library no.

https://github.com/potree/potree/blob/master/src/EarthControls.js
https://github.com/potree/potree/blob/master/src/FirstPersonControls.js

What would be the best way to add these? under a potree folder here at the repository?

**Comment by gyohk** [comment]
I think better to make a "potree" directory directly under DT repository.
Potree has dependency on three.js, but it seems an independent tool (like [physijs](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/physijs)).

**Comment by s093294** [comment]
Let's just close this then and I will make a new PR later for potree folder.

**Pull request closed without merging**
