### PR TITLE
Update flatten typing under StyleSheet namespace. React-Native

### PR DESCRIPTION
**Pull request by ahoseinian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactnative.dev/docs/stylesheet#flatten

### CODE REVIEW

**Comment by iRoachie** [comment]
What’s the reason behind this change?

**Comment by ahoseinian** [comment]
@iRoachie as explained by on the react-native docs:
```
StyleSheet.flatten([styles.listItem, styles.selectedListItem]);
// returns { flex: 1, fontSize: 16, color: 'green' }
---
StyleSheet.flatten(styles.listItem);
// returns { flex: 1, fontSize: 16, color: 'white' }
```
this function turns `T[]` to `T` if the input type is an array. that's why I have submitted this change. I had some typing issues on my project

**Review by alloy — CHANGES_REQUESTED** [review]
I assume you’re doing more work on this PR, as it’s labelled as “WIP”? I’ll mark it as needing changes so no drive-by merging occurs.

Also, please do add test coverage to illustrate what case you are fixing.

**Comment by ahoseinian** [comment]
@alloy I have added the test. should be fine now :)

**Comment by alloy** [comment]
Great, thanks 👍

**Review by alloy — APPROVED** [review]

**Pull request merged**
