### PR TITLE
express.d.ts - fix unrecognized overloads for app.use( ... )

### LINKED ISSUE #4212: express.d.ts - overload is not recognized
The following code reports an issue:
```javascript
import express = require('express');
var app = express();

if (app.get('env') === 'development') {
    app.use(function (err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}
```
It's supposed to be using the following overload
```javascript
use(path: string, handler: ErrorRequestHandler): T;
```

### PR DESCRIPTION
**Pull request by zhantongz**
This PR is intended to fix #4212.

### CODE REVIEW

**Comment by zhantongz** [comment]
Seems like using union types would result in error if --noImplicitAny is enabled.

**Comment by horiuchi** [comment]
@zhantongz Thank you for your contribution.
Please fix Travis CI error.

**Comment by westy92** [comment]
Bump.  Could you please fix the Travis CI error(s)?  It would be great to get this merged. :)

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
