### PR TITLE
ssh2: fix Server `accept`/`reject` types

### PR DESCRIPTION
**Pull request by samuela**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mscdex/ssh2
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by samuela** [comment]
Blocked on https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67484

**Comment by dhensby** [comment]
Can you provide more context this change and why the arguments should be optional? I'm not seeing anything in the origin repo that indicates that these callbacks can be (or ever are) omitted.

**Comment by samuela** [comment]
> Can you provide more context this change and why the arguments should be optional? I'm not seeing anything in the origin repo that indicates that these callbacks can be (or ever are) omitted.

Well, I can't fault you there. Upstream's documentation is a bit confusing IMHO:
> accept and reject are functions if the client requested a response.

In practice, I found this to be an issue with the `window-change` event, but the same language is used on the `accept`/`reject` arguments across all documented events on the `Server`. Presumably a different SSH client than mine ought to be able to exercise these code paths on other events as well. Experimentally I found that `accept` and `reject` take the value `undefined` when missing.

To reproduce these values it is sufficient to create a toy SSH server, add a handler for the `window-change` event, connect to the SSH server, and then change the size of the client's terminal window.

**Comment by dhensby** [comment]
Ah - I see: https://github.com/mscdex/ssh2/blob/v1.14.0/lib/server.js#L821-L1010

So if `wantReply` is false, then the `accept`/`reject` variables are never assigned and so the callbacks are `undefined`.

**Review by dhensby — APPROVED** [review]
If you add some tests, you'll be able to merge this when it goes green without any one else having to review

**Comment by samuela** [comment]
> If you add some tests, you'll be able to merge this when it goes green without any one else having to review

Thanks -- writing tests is currently blocked on https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67484

**Comment by samuela** [comment]
@typescript-bot writing tests is blocked on https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67484

**Comment by dhensby** [comment]
@samuela - it is possible to write/update tests without running them locally - CI can run them for you if you're having trouble locally.

**Pull request closed without merging**
