### PR TITLE
fix(@types/folder-hash): Add missing encoding `base64url`

### PR DESCRIPTION
**Pull request by marc136**
See https://github.com/marc136/node-folder-hash/commit/c7e1508f2bb588c44624df6c378ef72160385f6f

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/marc136/node-folder-hash/commit/c7e1508f2bb588c44624df6c378ef72160385f6f

### CODE REVIEW

**Review by thekevinbrown — CHANGES_REQUESTED** [review]
Edit: Comment moved below, meant to request changes on the PR, my bad!

**Review by thekevinbrown — CHANGES_REQUESTED** [review]
The docs on this package mention:

```console
encoding | string | <optional> | 'base64' | encoding of the resulting hash. One of 'base64', 'hex' or 'binary'
```

So I'm not sure that `base64url` is supported. Can you PR up to `folder-hash` itself on the readme so we can make sure the author of the package is committed to supporting this option?

**Comment by marc136** [comment]
> So I'm not sure that base64url is supported. Can you PR up to folder-hash itself on the readme so we can make sure the author of the package is committed to supporting this option?

I'm the author of the package :smile: 

I have added the text to the readme with https://github.com/marc136/node-folder-hash/commit/c7e1508f2bb588c44624df6c378ef72160385f6f but I did not yet publish a new npm version because I wanted to only document that `base64url` is also supported.

I needed it in another project where the linter failed because it did not exist in the type definition.

For the next released patch, I wanted to add further changes (that actually change the code).

Is this ok?

**Review by thekevinbrown — APPROVED** [review]
That’s my fault. It’s all good!

**Pull request merged**
