### PR TITLE
Removing react-bootstrap

### PR DESCRIPTION
**Pull request by aaronbeall**
Per https://github.com/react-bootstrap/react-bootstrap/issues/3489

I ran `npm run not-needed -- react-bootstrap 1.0.0-beta.0 https://github.com/react-bootstrap/react-bootstrap "React Bootstrap"`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by vitosamson** [comment]
How does this work for versions < 1.0.0? What happens if a correction needs to be made to the typings for previous versions?

**Comment by aaronbeall** [comment]
@vitosamson 
> How does this work for versions < 1.0.0? 
Pre 1.0 versions are still available on NPM, basically this stubs out >=1.0. 
> What happens if a correction needs to be made to the typings for previous versions?
That's a good question, I don't know if it's possible. I tried to research this. It isn't really addressed in the DT docs: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package
@RyanCavanaugh

**Comment by vitosamson** [comment]
Is it possible to just update `notNeededPackages.json` for >= 1.0.0 while still leaving the old code, and allowing new typings to be published for < 1.0.0?

**Comment by aaronbeall** [comment]
That would make sense... I'm not sure if the publisher supports that. I couldn't find any example that maintained old versions in DT.

**Comment by collingreen** [comment]
As far as I know, react-bootstrap is going to maintain both the <1.0 and >=1.0 forks for bootstrap 3 and 4, respectively. The >=1.0 version includes its own types, which is why I assume this PR exists. However, we can't just remove all the types since the <1.0 branch will continue development and, as @vitosamson pointed out, we need to maintain the ability to update/fix things over time.

**Comment by aaronbeall** [comment]
@collingreen I agree, I'll close this PR because I don't think outright removing `@types/react-bootstrap` seems right at this point. However we still have the problem that `npm install react-bootstrap @types/react-bootstrap` results in an invalid state that isn't immediately obvious. It seems we need to publish a `1.0` that is a stub, while leaving open the possibility to publish `0.x` definitions. I haven't had any luck finding info on what the protocol for that would be or if the DT types publisher can support that.

@RyanCavanaugh is it possible to do what @vitosamson mentioned:

> Is it possible to just update `notNeededPackages.json` for >= 1.0.0 while still leaving the old code, and allowing new typings to be published for < 1.0.0?

**Comment by collingreen** [comment]
That's certainly true and I've run into that exact problem with several other libraries recently while upgrading a large codebase. I don't know much about the underlying DT code but it would be great if it could support that kind of thing.

**Comment by RyanCavanaugh** [comment]
> Is it possible to just update notNeededPackages.json for >= 1.0.0 while still leaving the old code, and allowing new typings to be published for < 1.0.0?

I think the best we can do without adding new features to types-publisher is to have `react-bootstrap/v1` with an empty `.d.ts`. Alternatively we could add support for a custom message in the not-needed-package text to say "If you meant to get this for pre-1.0, npm install @types/whatever@thething` instead. Thoughts?

**Comment by aaronbeall** [comment]
> I think the best we can do without adding new features to types-publisher is to have `react-bootstrap/v1` with an empty `.d.ts`. 

Hm! So that led me to a part of the FAQ I had missed: [If a library is updated to a new major version with breaking changes, how should I update its type declaration package?](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package)

This seems pretty close to what we want. Can't we add a `/v0` dir folder and move all the old (current) definitions in there, and put a stub in the root for Version 1.0.0?

I guess the issue is that the types publisher doesn't actually publish the `/v0` dirs to npm, so consumers to get the latest 0.x definition would actually have to install `1.x` and set a path mapping to `/v0`? Or does the types publisher continue to publish the based on the `index.d.ts` version in the sub-dirs?

**Comment by aaronbeall** [comment]
Superseded by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43756

**Pull request closed without merging**
