### PR TITLE
humanparser - optional parameter added to parseName type definition

### PR DESCRIPTION
**Pull request by garrymotorway**
https://github.com/ralyodio/humanparser/blob/master/index.js - second optional argument is available

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [click here](https://github.com/ralyodio/humanparser/blob/a918a9e8b8017f06ac5df3fc2b2c05521fe745b2/index.js#L9)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
Updating the tests (`humanparser-tests.ts`) to include this optional parameter will let the PR get merged. For example:

```typescript
human.parseName("Mr. William R. Hearst, III", ["iii"]);
```

**Review by MysteryBlokHed — CHANGES_REQUESTED** [review]
Requesting changes so the bot will consider comments

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by garrymotorway** [comment]
Ready to merge

**Pull request merged**
