### PR TITLE
initial declaration for mailparser

### PR DESCRIPTION
**Pull request by psnider**
Declarations for the current version of mailparser lib.

### CODE REVIEW

**Comment by vvakame** [comment]
*mailparser/mailparser.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/mailparser
  * http://bower.io/search/?q=mailparser
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (mailparser/mailparser-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@psnider thank you for your contributions.
please rename mailparser/mailparser-test.ts to mailparser/mailparser-tests.ts

**Comment by psnider** [comment]
The test file has been renamed, and should be ready.
Note that I had a problem and recreated the repo. Hopefully, this won't affect you.
Thanks

**Comment by psnider** [comment]
Creating a new pull request...

**Pull request closed without merging**
