### PR TITLE
@types/oracledb - Make DBObject class generic

### PR DESCRIPTION
**Pull request by connorjayfitzgerald**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by sandersn** [comment]
@connorjayfitzgerald You'll need to merge from master to get the fix for `@hapi/joi` -- it's unrelated to your change but the tests look at a diff from master to figure out which packages to test.

**Comment by connorjayfitzgerald** [comment]
@Bigous Could you review this PR when you've got 5 minutes please?

**Comment by elibarzilay** [comment]
@connorjayfitzgerald: no review from @Bigous yet -- do you want to continue waiting?

**Comment by cfitz1995** [comment]
I don’t think he’s going to. Would you be able to, please?

**Comment by connorjayfitzgerald** [comment]
I don’t think he’s going to. Would you be able to, please?

**Review by Bigous — COMMENTED** [review]
Everything sounds good to me.

**Pull request merged**
