### PR TITLE
fixed the semver note in the header comment

### PR DESCRIPTION
**Pull request by kaoDev**
I just realised that I missed the patch version in the header comment, so the types got released with v0.0.3

With this change the publishing to npm should work correctly

### CODE REVIEW

**Comment by kaoDev** [comment]
@sandersn you just merged the last PR, are you still online ? :)

**Comment by sandersn** [comment]
Just at lunch. But it looks like Travis because of the new lint rules.

**Comment by andy-ms** [comment]
We don't allow a patch version in the header anyway. We publish the increment of the last patch version.

**Comment by kaoDev** [comment]
yes I've seen it and I'm working on it. 
enjoy your meal

**Comment by kaoDev** [comment]
hmm okay, when the patch version is not allowed how did it happen that the npm @types version does not match with the header version?

**Comment by andy-ms** [comment]
Looks like this was a ts2.2 package, so it was published as prerelease.
I've taken ts2.2 out of prerelease, though, so it will get a normal release soon. (Will lint the file to trigger a new publish.)

**Comment by sandersn** [comment]
@andy-ms, does that mean this PR is OK to merge once the lints are removed?

**Comment by andy-ms** [comment]
No, this PR adds a patch version which is not allowed.

**Comment by kaoDev** [comment]
ok I have removed the patch version again and the linter and test is happy now

**Pull request merged**
