### PR TITLE
[mousetrap] add pause and unpause methods definitions 

### PR DESCRIPTION
**Pull request by maiha2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://craig.is/killing/mice#extensions.pause>>

### CODE REVIEW

**Comment by nicbarker** [comment]
👀

**Comment by nicbarker** [comment]
Hey, thanks for raising this PR. Adding these definitions looks good to me. Would you mind adding a small test to the test file?

**Comment by maiha2** [comment]
@nicbarker I was not sure about the differences between the 3 test files. I added small test codes to `test/index.ts`. Thanks.

**Comment by nicbarker** [comment]
@maiha2 yep all good, the tests are just to make sure we don't get type checking regressions.

**Review by nicbarker — APPROVED** [review]
LGTM 🎉

**Comment by maiha2** [comment]
Ready to merge

**Comment by peterblazejewicz** [comment]
@maiha2 @nicbarker those will fail at runtime, will they? (if there is no extension added to JS stack)

**Comment by maiha2** [comment]
@peterblazejewicz @nicbarker I'm sorry. Yes, you're right. Extensions must be added. What should I do in these cases?

**Comment by nicbarker** [comment]
Ah sorry I didn't realise they were from extensions. Shall we change these to optional? e.g.
```
pause?: this
unpause?: this
```

This would force a non null assertion at runtime right?

**Comment by maiha2** [comment]
@nicbarker 
These type definitions are not enough to occur the failure, I thought. You want to use these methods(pause and unpause), it needs to add the extension. If it will fail, you used these methods without adding the extension.

The type definition `bindGlobal()` is an extension of the mousetrap like a pause method. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52122/files#diff-5f2a40f2c923e7e100048425a51beba6791c48bd81189c7416873aedc6e03950R30

Sorry if I missed the point 🙇

**Comment by peterblazejewicz** [comment]
folks, how your users are typically consume this package? Via installing `@types/mousetrap` manually or by using types automatic acquisition?

**Pull request merged**
