### PR TITLE
Expose RawContentState internals for draft-js 0.10

### PR DESCRIPTION
**Pull request by unindented**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://draftjs.org/docs/api-reference-data-conversion.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by unindented** [comment]
@RyanCavanaugh why didn't the bot mention any of the previous authors?

**Comment by sandersn** [comment]
Not sure what happened here. In any case, @dmitryrogozhny
@eelco
@ghotiphud
@schwers
@michael-yx-wu
@willisplummer
@smvilar
can you take a look?

**Comment by unindented** [comment]
@sandersn how long do you usually wait?

**Comment by sandersn** [comment]
Usually five days when the bot is working. Seems like it's broken again. @RyanCavanaugh

**Pull request merged**
