### PR TITLE
N3Store implements RDFJS.Store & RDFJS.DatasetCore

### LINKED ISSUE #53162: [@types/n3] N3Store should also implement RDFJS DatasetCore
N3 as of version 1.10.0 implements RDFJS DatasetCore.

I think [`match`](https://github.com/rdfjs/N3.js/blob/main/src/N3Store.js#L412) will need some extra care since now it returns [`DatasetCoreAndReadableStream`](https://github.com/rdfjs/N3.js/blob/main/src/N3Store.js#L835)

pinging authors: | @phreed | @rubensworks | @LaurensRietveld | @joachimvh | @AlexeyMz |

### PR DESCRIPTION
**Pull request by elf-pavlik**
### rdf-js

Removes RegExp per current version of the spec

* https://rdf.js.org/stream-spec/#source-interface
* https://rdf.js.org/stream-spec/#store-interface

### n3

closes #53162 

as per changes in commit https://github.com/rdfjs/N3.js/commit/cf8d28f0c05fc327151c1a76e333f2f8f0fce819 released in n3.js 1.10.0

### CODE REVIEW

**Review by rubensworks — CHANGES_REQUESTED** [review]
The changes themselves look ok to me.

But changes to both packages are breaking changes, so these will require a major version increment.

Instead of changing the rdf-js types here, it might be better to immediately do this at https://github.com/rdfjs/types though.

**Comment by elf-pavlik** [comment]
Thanks @rubensworks

> Instead of changing the rdf-js types here, it might be better to immediately do this at https://github.com/rdfjs/types though.

I've made equivalent PR to `@rdfjs/types`: https://github.com/rdfjs/types/pull/12
I don't think we can make it *instead* at this moment since `@types/n3` currently depends on `@types/rdf-js`. This could change in future via another PR.

> But changes to both packages are breaking changes, so these will require a major version increment.

`n3` package doesn't support regular expression on `match` or `removeMatches` so this update seems to reflect the current implementation. I think the change would be braking if N3 would have been supporting regexp and removed it, but in that case `n3` would have bumped its own major and we would just need to reflect it in this PR.

**Comment by rubensworks** [comment]
> I don't think we can make it instead at this moment since @types/n3 currently depends on @types/rdf-js. This could change in future via another PR.

Is this change urgent for your case?
If not, then I would wait with this PR until we finish migrating the RDF/JS typings to the new package.

If it is urgent, then I would indeed include the RDF/JS changes here, but mark it a major version update (as it's breaking).

> I think the change would be braking if N3 would have been supporting regexp and removed it, but in that case n3 would have bumped its own major and we would just need to reflect it in this PR.

It is breaking though.
For example, the following code may exist, and will not work anymore in the future:
```typescript
function something(term: Term | RegExp) {
  return n3Store.match(term, term, term);
}
```
Indeed, passing `RegExp` at runtime would not work in any case, but typings may created in a more general manner, so we don't want to cause any problems with those.

**Comment by elf-pavlik** [comment]
> Is this change urgent for your case?
> If not, then I would wait with this PR until we finish migrating the RDF/JS typings to the new package.

Ok, let's do it this way. In that case I would like that we really focus on getting that migration done. I don't really know what's the status of it but please let me know if any help is needed.

> It is breaking though.

Do you suggest diverging major versions of `n3` and `@types/n3`? 
```ts
// Type definitions for N3 2.0
```

**Comment by rubensworks** [comment]
> In that case I would like that we really focus on getting that migration done. I don't really know what's the status of it but please let me know if any help is needed.

@tpluscode may know more.

> Do you suggest diverging major versions of n3 and @types/n3?

Just `@types/n3` is ok, since only `n3` influences `@types/n3`, but not the other way around. (versions of packages and their typings do not have to be aligned)

**Comment by tpluscode** [comment]
I do know 😀. I pinged you on GH and GItter for an NPM token so that we can actually publish

**Comment by rubensworks** [comment]
@tpluscode I gave you access to the `rdf-js` package a while ago, so you should be able to publish to that?

**Pull request closed without merging**
