### PR TITLE
change interface of i18next as v8.4.2

### PR DESCRIPTION
**Pull request by aalenliang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.i18next.com/api.html>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aalenliang** [comment]
Should fix this issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16590

**Comment by mxl** [comment]
Sorry, did not have time to review it, but it looks good! 👍

**Comment by aalenliang** [comment]
@mxl Thanks, actually the file changed a lot, because it's originally support i18next for v.2.x.x, which is out of date for a long time. maybe we should keep 2 version for this.

**Comment by mxl** [comment]
@aalenliang You could add them, though I don't think that someone is still using 2.x.x version, but even so these type definitions is backward compatible.

**Pull request merged**
