### PR TITLE
[@types/redux-actions] Fix error when payload has the same type as state

### PR DESCRIPTION
**Pull request by someden**
Example with error:
screen shot 2018-05-28 at 16 11 41

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Isn't this case covered by this test https://github.com/DefinitelyTyped/DefinitelyTyped/blob/348d75dac9cb9bc550171e09d248e49691910946/types/redux-actions/redux-actions-tests.ts#L37
?

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
Please check the comment in the main thread - not sure that a `Reducer<Type, Type>` would expect an action of `Action<Type>` with `payload` having a `value` field unless `Type` itself has one

**Comment by someden** [comment]
I think state and payload must have a different types. For example, in my cases state is instance of Map or OrderedMap (immutable) and payload is simple array getting from server.

**Comment by alexey-pelykh** [comment]
Does `handleActions<MapType, any[]>` or similar work for you?

**Comment by someden** [comment]
Yes, similar)
screen shot 2018-05-30 at 14 34 45

**Comment by alexey-pelykh** [comment]
In other words, issue is that not specifying types explicitly leads to selection of a "wrong" declaration. Solution is to either specify type of the payload, seems to me

**Comment by someden** [comment]
Yes, but in most cases state and payload have different types, so why it is not by default?

**Comment by alexey-pelykh** [comment]
Don't have an answer for that. From TypeScript usage perspective, it would be more than advisable to use the `handleActions<StateType, any>` explicit notation to identify the `any` type. Not sure about `flow` world.

**Comment by alexey-pelykh** [comment]
Thus, let's see what maintainers would say =)

**Pull request closed without merging**
