### PR TITLE
Adds missing error for optimized function in svgo

### PR DESCRIPTION
**Pull request by mikaelbr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/svg/svgo/blob/700f2031699e35da29efc19da74b8765aea127e6/lib/svgo.js#L36

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## svgo ([<kbd>unpkg</kbd>](https://unpkg.com/browse/svgo@latest/))
was missing the following properties:
1. createContentItem
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9be32391566217adff8d45dc628f677662a6cab
</p>

**Comment by peterblazejewicz** [comment]
can we rework the types to align with every day usage?
```js
let optimized = optimize('');

if (optimized.modernError) {
    optimized; // $ExpectType OptimizedError
    optimized.modernError; // $ExpectType SvgoParserError
} else {
    optimized; // $ExpectType OptimizedSvg
    optimized.data; // $ExpectType string
}
```
to support discrimated union we can for example:
```ts
export interface OptimizedError {
    error: string;
    modernError: SvgoParserError;
}

export interface OptimizedSvg {
    data: string;
    info: {
        width: string;
        height: string;
    };
    path?: string | undefined;
    modernError: undefined;
    error: undefined;
}
```

**Comment by mikaelbr** [comment]
Thanks! Good suggestion, that's much better approach.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@mikaelbr thx!

**Review by petrzjunior — APPROVED** [review]

**Comment by mikaelbr** [comment]
Ready to merge

**Pull request merged**
