### PR TITLE
mqtt: add getLastMessageId function to mqtt.Client

### PR DESCRIPTION
**Pull request by yohei1126**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mqttjs/MQTT.js/pull/527/files

### CODE REVIEW

**Review by PekkaPLeppanen — COMMENTED** [review]
You might want to add semicolon to the end of the line, because missing one is causing errors for people using tslint.

**Comment by yohei1126** [comment]
Thanks. Please check it again.

**Review by PekkaPLeppanen — APPROVED** [review]

**Comment by PekkaPLeppanen** [comment]
👍

**Review by PekkaPLeppanen — APPROVED** [review]

**Comment by yohei1126** [comment]
Could you update the npm module as well?
https://www.npmjs.com/package/@types/mqtt

**Comment by PekkaPLeppanen** [comment]
Sorry, I don't have the rights for merge this back to master. :(

**Comment by ogis-onishi** [comment]
Sure but who merges this request?

**Comment by yohei1126** [comment]
Sure but who merges this request?

**Comment by horiuchi** [comment]
@yohei1126 Thank you for your contribution. 👍 
`@types` is automatically updated by `Microsoft/types-publisher`, probably per day.

**Comment by yohei1126** [comment]
@horiuchi thanks!

**Comment by yohei1126** [comment]
The new version of the npm module has already released.
https://www.npmjs.com/package/@types/mqtt

**Pull request merged**
