### PR TITLE
update(mousetrap): parameterless ctor support and other changes

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- just like creation function constructor comes with optional target
  element support
https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L438
- DT support updated and unified with default settings
- DT header cleared out
- default formatting applied after DT linting change
- maintainer added

Thanks!

Sorry for loads of changes, while the most important one is just parameterless ctor support, thx!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mousetrap ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mousetrap@latest/))
was missing the following properties:
1. init
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d5b5debff4e20c5b94f7e9e9282d05dcd856c34e
</p>

**Comment by nicbarker** [comment]
👀

**Comment by nicbarker** [comment]
Nice work, these changes LGTM. Although those performance improvements look kind of suspicious.
Do you know what in your changes could have improved some of the metrics 40%? Mem usage -27% 🤔
Perhaps it's accrued changes in the background over time that are unrelated to this PR? I'm not sure how they are calculated.

**Review by nicbarker — APPROVED** [review]

**Review by qcz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
> Do you know what in your changes could have improved some of the metrics 40%? Mem usage -27% 🤔

I've removed jQuery reference from test file, not used in the code at all (not mentioning package itself),
Thx!

**Review by rbuckton — APPROVED** [review]

**Comment by qcz** [comment]
Ready to merge

**Pull request merged**
