### PR TITLE
Update react-notification-system.d.ts

### PR DESCRIPTION
**Pull request by AyaMorisawa**

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
:+1: 
Thanks for fix.

**Comment by DovydasNavickas** [comment]
@AyaMorisawa, you changed `Function` to `() => void` and added yourself to authors? Seriously? :)

**Comment by AyaMorisawa** [comment]
@DovydasNavickas I removed myself from authors. :)

**Comment by DovydasNavickas** [comment]
:clap: :+1:

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
