### PR TITLE
updated localforage definitions + angular-localforge (dependent)

### PR DESCRIPTION
**Pull request by stephenlautier**
Updated localforge:
- Support es6 imports
- added createInstance method
- some minor doc
- changed driver to accept also a string (to use their property e.g. localforage.LOCALSTORAGE
- added some minor tests

### CODE REVIEW

**Comment by vvakame** [comment]
@stephenlautier please resolve conflict.

**Comment by stephenlautier** [comment]
I will redo some changes since the conflicts were quite big, we almost did the same changes and its hard to merge

**Comment by stephenlautier** [comment]
@vvakame Reincluded my changes

**Comment by vvakame** [comment]
*localForage/localForage.d.ts*

to author(@3x14159265). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by stephenlautier** [comment]
Is it possible to merge this please? @vvakame. Thanks!

**Comment by vvakame** [comment]
sorry for late. It merged. thanks!

**Comment by stephenlautier** [comment]
no problem, wanted to bump it a little bit. Thanks :+1:

**Pull request merged**
