### PR TITLE
update Mithril.js definition from 0.1.x to 0.2.0

### PR DESCRIPTION
**Pull request by shibukawa**

### CODE REVIEW

**Comment by aodag** [comment]
:+1:

**Comment by horiuchi** [comment]
@borisyankov For this update, are you OK?

**Comment by vvakame** [comment]
@shibukawa sorry for late. please resolve conflict first.

**Comment by shibukawa** [comment]
Finally, I update to 0.2.4.

**Comment by vvakame** [comment]
*mithril/mithril.d.ts*

to authors (@lhorie @cbowdon). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by shibukawa** [comment]
I just copy from https://github.com/lhorie/mithril/blob/master/mithril.d.ts and add header lines. And rewrite this repository's test code that uses deprecated method (``m.module``).

**Pull request merged**
