### PR TITLE
fix(node): make fs.watchFile listener stats parameters optional

### PR DESCRIPTION
**Pull request by frenzzy**
See https://github.com/nodejs/node/blob/v22.4.0/lib/fs.js#L2483-L2484

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by rbuckton** [comment]
This seems like it's possibly a case of poor JSDoc notation, as the internal `StatWatcher` class always emits `"change"` with two arguments. Since you are always allowed to undersupply parameters to a callbac, is there any particular reason you need to make this change?

**Comment by frenzzy** [comment]
@rbuckton because the tests were failing here: https://github.com/runk/node-maxmind/pull/850 (in the first commit)

Screenshot 2024-07-10 at 1 23 19 PM

```js
fs.watchFile(filepath, watcherOptions, async (curr, prev) => {
  if (curr.mtimeMs === prev.mtimeMs) {
       // ^ TypeError: Cannot read properties of undefined (reading 'mtimeMs')
```

**Comment by rbuckton** [comment]
This looks to be due to the mock implementation, not the actual implementation, and should be fixed in the source project instead:

https://github.com/runk/node-maxmind/blob/9a753438c61e55de9a2be59cdb1d7a7e8c8ddc6d/src/index.test.ts#L18-L20

https://github.com/runk/node-maxmind/blob/9a753438c61e55de9a2be59cdb1d7a7e8c8ddc6d/src/index.test.ts#L63

**Comment by frenzzy** [comment]
Thank you for pointing that out!

**Pull request closed without merging**
