### PR TITLE
delete(algoliasearch): remove types

### PR DESCRIPTION
**Pull request by peterblazejewicz**
No longer required as of version 4:

```
The client now natively supports TypeScript. If you’re using it in a
TypeScript project, you no longer need the @types/algoliasearch package.
```
https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/#upgrading-from-3351-to-4x

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]
last time I made this PR it failed because somehow it wasn't allowed to have ts-ignores in transitive deps here, if it is, way to go!

**Comment by peterblazejewicz** [comment]
@Haroenv I've started a thread to catch up with DT matinainers on the subject. Wish me a luck!

**Comment by Haroenv** [comment]
for reference @peterblazejewicz, the previous PRs and issues are: https://github.com/microsoft/dtslint/issues/297 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46945 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45699 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44699 https://github.com/microsoft/types-publisher/pull/780

**Review by Haroenv — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
