### PR TITLE
[React] Include ElementChildrenAttribute for 2.3 

### PR DESCRIPTION
**Pull request by yuit**
This is a new feature in 2.3 as TypeScript will be able to check JSX.children

This is the update need for this feature to work https://github.com/Microsoft/TypeScript/pull/15160

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@yui can you rebase against master

**Comment by shiftkey** [comment]
@yuit this change broke previously-valid TSX code and I'm not sure what the right way is to fix it. I've uploaded a repro to demonstrate the issue here: https://github.com/shiftkey/react-types-children

**Comment by yuit** [comment]
@shiftkey Thanks for trying this out!..... I will put simplified version of the code here for reference.

**Original Code**
```ts
import * as React from 'react'

interface IRowProps {
     readonly children?: ReadonlyArray<JSX.Element>;
}

export class Row extends React.Component<IRowProps, void> {
  public render() {
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
}

let row = <Row>
            <span>things go here</span>
        </Row>
```

**Error**
```
 error TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Row> & Readonly<{ children?: ReactNode; }> & Reado...'.
  Type '{ children: Element; }' is not assignable to type 'Readonly<IRowProps>'.
    Types of property 'children' are incompatible.
      Type 'Element' is not assignable to type 'ReadonlyArray<Element> | undefined'.
        Type 'Element' is not assignable to type 'ReadonlyArray<Element>'.
          Property 'length' is missing in type 'Element'.
```

**Explaination**
The error is because in an interface `IRowProps` "children" property is declared to be a readonly array of JSX.Element but when declared in `let row...`, "children" property is just a JSX.Element (e.g it is not wrapped as an array with one element) 

**Fix**
When you declared property `IRowProps` you will want "children" to be either Array of Jsx.Element

```ts
interface IRowProps {
     readonly children?: ReadonlyArray<JSX.Element> | JSX.Element;
}
```

**Comment by AlgusDark** [comment]
@yuit So, If I have something like:

```
export const MenuList: React.SFC<React.HTMLProps<HTMLUListElement>> = (props) => {
    return (
        <ul {...props} />
    )
}
```

How I can type force `MenuList` to only accept `<li>` elements? (single, or multiple).

I've been trying to figure it out, but without success, thanks in advance.

**Comment by Hotell** [comment]
@AlgusDark that's unfortunately not supported. 

You can constrain children only to be `JSX.Element | Array<JSX.Element> | string | number | () => JSX.Element ` and so on, no capability to explicitly restrain that children can be only specific DOM element or ReactElement ( although this is possible with Flow >= 0.56 )

**Pull request merged**
