### PR TITLE
refactor(node): use ESM instead of CJS in JSDoc comments

### PR DESCRIPTION
**Pull request by crowlKats**
This change is to improve consistency, as currently there is a mix of ESM and CJS, so this PR moves all JSDoc comments to use ESM. 
This is also needed for [Deno's Node reference documentation](https://docs.deno.com/api/node), which is completely genereated from this package, and we would like not to have to maintain floating patches or fork it for these changes.

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM - always nice to see modernization like this!

As a followup, it might be good to find/write an ESLint rule / plugin setup that enforces using ESM over CJS in comments. Kind of a niche use case but very applicable here. Without any CI/repo enforcement, it's not improbable this will get broken once in a while later on.

**Comment by JoshuaKGoldberg** [comment]
Note that the CI failures in _CI / test (7, 12)_ are unrelated to this PR. They're existing failures in packages that happen to depend on `@types/node`.

**Comment by jakebailey** [comment]
Aren't these docs generated by Node's docs?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
> Aren't these docs generated by Node's docs?

It’s currently impossible to do it. But we would definitely love to.

**Comment by crowlKats** [comment]
> Note that the CI failures in _CI / test (7, 12)_ are unrelated to this PR. They're existing failures in packages that happen to depend on `@types/node`.

is there anything that can be done about that?

**Comment by jakebailey** [comment]
> > Aren't these docs generated by Node's docs?
> 
> It’s currently impossible to do it. But we would definitely love to.

Then what's the deal with https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70298?

**Comment by jakebailey** [comment]
> is there anything that can be done about that?

Separate PRs to fix them and a rerun here (we have a DT maintainer rotation to look at these regularly); but the fails here are old, so you could just close/reopen the PR to rerun CI. Though, `mongoose-delete` is failing on master, so not sure if it would actually pass.

**Comment by jakebailey** [comment]
This PR only touches the latest `@types/node`; did you mean to not change any of the versioned subdirs?

**Comment by jakebailey** [comment]
The PR still only touches the latest Node; I'm not sure having them be inconsistent is a good idea, but I understand why you may not care (as deno will only ever load the latest anyway).

**Comment by crowlKats** [comment]
@jakebailey sorry for the delay, just didnt get around to doing this until now! pretty much everything should be covered now

**Review by jakebailey — APPROVED** [review]
Thanks.

**Comment by jakebailey** [comment]
I'm approving this, but know that your branch is 121 commits behind `master`, so it's possible there are some docs in recent PRs that have been missed.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/v16/events.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0cbeab0465cb8bae0216cb3ccd528f2f94ba35c5
</p>

**Comment by crowlKats** [comment]
@jakebailey I merged with main and fixed up a few more missed cases, so latest changes should all be covered now.

**Review by jakebailey — APPROVED** [review]

**Comment by crowlKats** [comment]
Ready to merge

**Pull request merged**
