### PR TITLE
fix: req-real-ip Request type

### PR DESCRIPTION
**Pull request by lacherogwu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request-ip/index.d.ts
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

## Context
I have noticed that the types do not match if I pass a request object of a lib such as Fastify/Express so I added only the necessary parts.

### CODE REVIEW

**Comment by jakebailey** [comment]
I said this on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70756#issuecomment-2420374570 but I have no idea what happened to this package; where did it go? Did you unpublish it? We need to mark the package as not being on npm, or just delete it. It's not clear to me how the PR was accepted if the package didn't exist.

**Comment by jakebailey** [comment]
`npm info req-real-ip` confirms that this was unpublished.

**Comment by jakebailey** [comment]
I deleted this package in #70948. We can revert if the package comes back to npm.

**Comment by lacherogwu** [comment]
I recommend to delete the package from NPM https://www.npmjs.com/package/@types/req-real-ip, the author of the npm package unpublished it

**Comment by jakebailey** [comment]
Now I'm even more confused. This was your package all along? Why did you send types to DT in the first place?

I don't think it's worth bringing the DT package back just to delete it again; the real package will override the DT package, and the DT package will just remain undownloaded by anyone.

(In any case, this PR itself is no longer a candidate for merging, so, closing it)

**Comment by lacherogwu** [comment]
> Now I'm even more confused. This was your package all along? Why did you send types to DT in the first place?
> 
> I don't think it's worth bringing the DT package back just to delete it again; the real package will override the DT package, and the DT package will just remain undownloaded by anyone.
> 
> (In any case, this PR itself is no longer a candidate for merging, so, closing it)

No it wasn't my packages, if was some dude's package and he suddenly unpublish it, so I re-published it

**Pull request closed without merging**
