### PR TITLE
[react] Added types for ARIA role attribute

### PR DESCRIPTION
**Pull request by priyanshurav**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.w3.org/TR/wai-aria-1.1/#role_definitions>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by dimitropoulos** [comment]
>  Provide a URL to documentation or source code which provides context for the suggested changes: <>

please provide a source when you have a moment

**Review by eps1lon — CHANGES_REQUESTED** [review]
1. It should still allow unknown roles e.g. when new roles are added but types are outdated
2. what about fallback roles e.g. `role="none presentation"`?

**Comment by priyanshurav** [comment]
> 1. It should still allow unknown roles e.g. when new roles are added but types are outdated
> 2. what about fallback roles e.g. `role="none presentation"`?

@eps1lon I have made the changes that you suggested

**Review by eps1lon — APPROVED** [review]
Nice, thanks!

**Pull request merged**
