### PR TITLE
Added definitions for eq.js

### PR DESCRIPTION
**Pull request by stephenlautier**

### CODE REVIEW

**Comment by horiuchi** [comment]
@stephenlautier Thank you for your contribution.
Please rename `eq.js/eq.js.d.ts`.
http://bower.io/search/?q=eq.js
https://github.com/Snugug/eq.js/blob/master/bower.json#L2

**Comment by stephenlautier** [comment]
Opps sorry! I will do it right now, cheers

**Comment by stephenlautier** [comment]
Just done it @horiuchi , thanks.

**Comment by horiuchi** [comment]
@stephenlautier Thank you! :smile:

**Pull request merged**
