### PR TITLE
[@types/relay-runtime]: Support object & list value arguments

### PR DESCRIPTION
**Pull request by tapayne88**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/relay/blob/master/packages/relay-runtime/util/ReaderNode.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getRequestIdentifier
1. MutationTypes
1. RangeOperations
1. ConnectionResolver_UNSTABLE

<details>
<summary>as well as these 11 other properties...</summary>
<p>VIEWER_ID, VIEWER_TYPE, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isPromise, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier, getFragmentSpecIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eb6dfe408359bdd3ec76e474879c7aca40706a97
</p>

**Comment by tapayne88** [comment]
Some of the files don't currently comply with the prettier config. I can fix them up in this change if people think that's a good idea

**Review by alloy — APPROVED** [review]
Looks good, thanks 👍 

Yeah sure, I’ll wait with merging for you to add those prettier changes too.

**Comment by alloy** [comment]
Ace, thanks! 🙏

**Pull request merged**
