### PR TITLE
Added support for strictNullChecks by allowing null | undefined as message values

### PR DESCRIPTION
**Pull request by aaronbeall**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22131#issuecomment-351218248 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22131#issuecomment-352462763
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by kristerkari** [comment]
I might not understand everything related to the message values, so what's the use case for this? When would you need to pass `undefined` or `null` to as a value to a message?

**Comment by gyzerok** [comment]
Currently :-1:

There is no link to documentation nor explanation at all.

**Comment by aaronbeall** [comment]
@kristerkari @gyzerok With `strictNullChecks: true` the previous definitions would not allow the passing of a type that *might* be `null` or `undefined`:
```ts
function format(value?: string) {
  intl.formatMessage("foo", { value: myValue} ); // Error: Type 'undefined' is not assignable to type 'string | number | boolean | Element | Date'.
}
```
But FormatJS allows `null` and `undefined` values, it interpolates them as an empty string and you can [`{select}`](https://formatjs.io/guides/message-syntax/#select-format) on `null` or `undefined`. I couldn't find any explicit documentation on the handling of `null` and `undefined`, it [just states it will "interpolate the value"](https://formatjs.io/guides/message-syntax/#simple-argument). Documentation on `strictNullChecks` is [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html).

**Comment by aaronbeall** [comment]
@kristerkari @gyzerok Also see this unit test in source code that verifies `false`, `null`, and `undefined` all interpolate to an empty string (`false` is already part of the type-defs):

https://github.com/yahoo/intl-messageformat/commit/b749b4d234e30a73651ae3fda292b7c9e8108b98

**Pull request merged**
