### PR TITLE
[agiledigital] added package.json

### PR DESCRIPTION
**Pull request by hellatan**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

added a package.jsonf file to `agiledigital__mule-preview` and marked typescript@~3.4.0  as a dependency to avoid installing the incorrect typescript version for these type definitions to pass properly. 

This is causing the benchmark build job to fail on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671

### CODE REVIEW

**Comment by NoxHarmonium** [comment]
After having a better look I don't know if this is the way to go. I've looked through other type folders and it looks like its not very common to have a package.json. Maybe the issue is lack of Typescript 4 support. I'll have a look at doing what other types like `react-router` do and have different folders for different versions of TS.

**Comment by NoxHarmonium** [comment]
I've done some digging around and testing locally and I can't reproduce this issue. I've looked at a whole heap of similar projects and none of them peg the Typescript version through package.json. It seems like a bug in the perf tool (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671#issuecomment-642138999) so I don't think we should merge.

**Review by NoxHarmonium — CHANGES_REQUESTED** [review]
I don't think this should be merged. I think we should close this PR unless a DefinitelyTyped maintainer disagrees.

**Comment by hellatan** [comment]
@NoxHarmonium - i'm really not sure what is going on here. Someone mentioned using [`typesVersions`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) but I think that means duplicating types so it does work with version 4? It's super unclear as to what the direct path is for this stuff or I just haven't found the right documentation. `react-router` doesn't use `typesVersions` but has a `v2` and `v3` folder. I don't know these agile digital types at all so I'm definitely just grasping at straws right now in order to get my react PR into a mergeable state. This was the one solution that I found that allows for that to work.

**Comment by hellatan** [comment]
> Happy to approve this but would a better solution be to update these types to the latest Typescript version? I should be able to get that done within 24 hours.

great, just let me know when that happens

> Strange that these types are singled out out of the many typings in this repo. I would have thought there would be other older types sitting unmaintained.

ya, agreed. not sure why that's the case. Well, `airbnb-prop-types` and `alt` (idk what that is) were both flagged in my #44671 PR and I had similar solutions.

**Comment by NoxHarmonium** [comment]
> Someone mentioned using typesVersions but I think that means duplicating types so it does work with version 4?

The docco for how to use typesVersions is at:
https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-31-or-above

Sounds like its only useful if you want to support multiple versions of Typescript. As long as Typescript 3.4 is used (readonly tuples) these types should work. I've tested them locally.

As I mentioned in my comment on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45409#issuecomment-642925567 it looks like a bug in the perf tool.

**Comment by NoxHarmonium** [comment]
Looks like the builds on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671 have passed :tada: 

It must have been a transient bug in the perf testing tooling

@hellatan can you please close this PR?

**Comment by hellatan** [comment]
@NoxHarmonium omg...this has been the biggest PITA mainly not understanding the whole pipeline of things...and react's overall reach to other types. yes, closing this PR!

**Pull request closed without merging**
