### PR TITLE
Allows using the .ordered flag in both expect and assert style.

### PR DESCRIPTION
**Pull request by tomc974**
Documentation for the added type definition:
- [expect style](http://chaijs.com/api/bdd/)
- [assert style](http://chaijs.com/api/assert/)

### CODE REVIEW

**Comment by sandersn** [comment]
Any idea why the diff is so large?

**Comment by jedmao** [comment]
It's probably the newlines.

**Comment by tomc974** [comment]
Sorry guys, I don't know why my editor messes with the new lines in one of the file... It should be fine now.

**Comment by jedmao** [comment]
Do you need to bump the version of chai for these changes?

**Comment by tomc974** [comment]
@jedmao No, it was released as part of [Chai 4.0.0](https://github.com/chaijs/chai/releases/tag/4.0.0) and the type definition is already at this version.

**Review by jednano — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
:+1:

**Pull request merged**
