### PR TITLE
Mocha 8 - RootHook object type

### PR DESCRIPTION
**Pull request by arnulfojr**
Follow up PR from: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46017

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mochajs/mocha/blob/7d3151d08a3082dd022116d00234caf1600a71b5/lib/mocha.js#L1099-L1107
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mocha ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mocha@latest/))
was missing the following properties:
1. unloadFile
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 38b3f0c983d1a9224b6ea1cd48ecf3a9be892589
</p>

**Comment by arnulfojr** [comment]
@elibarzilay @sheetalkamat any update/comments?

**Comment by elibarzilay** [comment]
It's best to get a review from an owner

(@kazimanzurrashid @otiai10 @jt000 @enlight @cspotcode @1999)

**Review by andrewbranch — APPROVED** [review]
Looks right according to API docs.

It’s worth noting, though, that `AsyncFunc` is assignable to `Func`, so everywhere `Func | AsyncFunc` appears, it is useless. If `AsyncFunc` were not assignable to `Func`, the property signature `afterAll?: Func | AsyncFunc | Func[] | AsyncFunc[]` would actually be wrong—what I think you intended was `afterAll?: Func | AsyncFunc | (Func | AsyncFunc)[]`, since sync and async functions can occupy the same array. However, since `AsyncFunc` is assignable to `Func`, both of these signatures are functionally equivalent to `Func | Func[]`, so the way it’s written now doesn’t impose a burden upon users. Given that, and the fact that this definition already contains lots of useless `Func | AsyncFunc`, I don’t think it needs to be addressed in this PR.

**Comment by arnulfojr** [comment]
Ready to merge

**Pull request merged**
