### PR TITLE
marked: Added missing type: 'def' to Marked.Tokens.Def

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
We _(a large group of coworkers mob programming this from @Codecademy, hi everyone!)_ are pretty sure the `Tokens` union type as returned by `lexer()` should not indicate that `Def` is a possible token to output. In experimenting with the demo page and link defs, we couldn't find a way to make it output any nodes that don't have a `type` member: including `Def`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://marked.js.org/demo & https://github.github.com/gfm/#link-reference-definitions & https://raw.githubusercontent.com/markedjs/marked/master/test/specs/new/def_blocks.md
- ~[ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- ~[ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## marked ([<kbd>unpkg</kbd>](https://unpkg.com/browse/marked@latest/))
was missing the following properties:
1. parseInline
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 777656af792a792028a5f5aaca3808b9e3b2018f
</p>

**Comment by worr** [comment]
Hey, it sounds more like y'all found a bug with marked rather than a bug in the type definitions. Looking through the code, it's definitely the intent that `def` is a valid token, but I do see that the parser doesn't seem to handle it, at least from a passing glance. I'm not a marked maintainer or anything, so take this all with a grain of salt. I'd recommend either filing a bug there, or filing a PR there.

Let me know if I misunderstood.

**Comment by amcasey** [comment]
I'm not really in a position to say whether this is a types bug or a library bug.  @JoshuaKGoldberg thoughts on @worr's comment?  Assuming it's a bug, I would personally lean towards leaving the types as-is because consuming code should be able to handle the (currently unexpected) value.

**Review by amcasey — CHANGES_REQUESTED** [review]
There's an open question.  Changing status for bookkeeping reasons.

**Pull request closed without merging**
