### PR TITLE
[openlayers] Rewrite for openlayers 3.18.2

### PR DESCRIPTION
**Pull request by osechet**
This PR rewrites the definition for latest version of openlayers: v3.18.2. The file has been created from the jsdoc annotations. Each type and method is associated with the original documentation.

Previous definition file has been renamed as 3.6.0 since it has originally been designed for that version.

### CODE REVIEW

**Comment by osechet** [comment]
Any update about this PR. I hope you are not waiting for @woutergd feedback: he had no activity on github for more than a year.

**Comment by woutergd** [comment]
@osechet, I am not active in development of this type definitions lately unfortunately because my work doesn't allow it at the moment, but I am still trying to check all the PR's that are passing by, sometimes with a bit of delay. Really thanks for updating the whole library, as there are also a lot of tests written I assume that everything is fine so the merge is fine to me! 👍

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by osechet** [comment]
Conflicts have been merged.

**Comment by vvakame** [comment]
sorry, please resolve conflict again.

**Comment by osechet** [comment]
@vvakame conflicts resolved.

**Comment by osechet** [comment]
@vvakame What is blocking the merge of this PR? All the conflicts I had to resolve until now were lead by modifications already done in thir PR.

**Comment by StephaneMourgues** [comment]
@osechet first thanks for this great work. But there is some things I don't really understand. I'll take the ol.Map.forEachFeatureAtPixel as an example. You wrote the definition like this:

`forEachFeatureAtPixel<S, T, U>(pixel: ol.Pixel, callback: ((self: S, feature: (ol.Feature | ol.render.Feature), layer: ol.layer.Layer) => T), opt_this?: S, opt_layerFilter?: ((self: U, layer: ol.layer.Layer) => boolean), opt_this2?: U): (T);`

I do not understand why you put the `self` in the parameters of the callback and the opt_LayerFilter. For the opt_LayerFilter the doc says `The filter function will receive one argument, the layer-candidate` and even though it's actually invoked with 2 parameters in ol.js: `layerFilter.call(thisArg2, layer)` the first one is merely the value to use as this in the method, and this value is already set in `opt_this2`.

For me (and I'me quite new to js/typescript) the definition should be:

`forEachFeatureAtPixel<S, T, U>(pixel: ol.Pixel, callback: ((feature: (ol.Feature | ol.render.Feature), layer: ol.layer.Layer) => T), opt_this?: S, opt_layerFilter?: ((layer: ol.layer.Layer) => boolean), opt_this2?: U): (T);`

I'd like to know if I'm correct before submitting a PR to fix that.

**Comment by osechet** [comment]
Hi @StephaneMourgues,
I'm following the javascript documentation. If you look at the [ol.Map class](https://github.com/openlayers/ol3/blob/v3.18.2/src/ol/map.js#L603), the documentation describes the callback as ` {function(this: S, (ol.Feature|ol.render.Feature), ol.layer.Layer): T}`. 
The first parameter (`this`) is just the name of the argument inside the callback. Since `this` is a reserved word in typescript, I renamed it as `self`. `opt_this` is the value that will become `self` in the callback. The callback doesn't know the `opt_this` argument.
In the Map class; the callback is called with `callback.call(opt_this, feature, layer)`, with your custom callback being defined as `function mycallback(self: Foo, feature: ol.Feature, layer: ol.layer.Layer): Bar {}`.

**Comment by osechet** [comment]
@StephaneMourgues The modification you were requesting have been done in PR #11745. I made a mistake about how the `this` context is managed in Typescript. In Javascript, when callback.call() is used the first argument becomes the `this` of the function. It's a special argument and it seems it has no meaning in Typescript.

**Comment by StephaneMourgues** [comment]
Great. thanks

**Pull request merged**
