### PR TITLE
@typs/sinon - Calls fake passes through the arguments

### PR DESCRIPTION
**Pull request by johnjesse**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
 - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30442#discussion_r234531825
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. - not substantial

I made a mistake in #30442 - the callsFake type was overly restrictive, it is passed the arguments of the function call by Sinon and so should expect to be called with the same arguments as the method it's replacing.

### CODE REVIEW

**Review by egilsster — APPROVED** [review]
Appreciate the quick turnaround on this

**Comment by johnjesse** [comment]
Hmmm... the build failure appears to be
```
Error in sinon-chrome
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/sinon-chrome/sinon-chrome-tests.ts:3:18
ERROR: 3:18  no-angle-bracket-type-assertion  Type assertion using the '<>' syntax is forbidden. Use the 'as' syntax instead.
```

which is in a package I didn't touch 😕

**Comment by PranavSenthilnathan** [comment]
@uniqueiniquity to take a look

**Comment by uniqueiniquity** [comment]
@johnjesse The way the build works is that it tests all packages that depend on the package you do change. The lint rule that's failing was added on September 26, which is why it hadn't been failing previously. I'm not sure why it didn't fail in #30442 .

I'll put up a PR to fix that package's tests. Once that gets merged, we can try again.

**Comment by uniqueiniquity** [comment]
@johnjesse looks like you have a merge conflict now from #30676

**Comment by johnjesse** [comment]
surely we should only merge one of this and #30656 as they both address the same issue. If that is the accepted solution shouldn't we close this? Although i'd argue using `TArgs` instead of `any[]` is more correct

**Comment by uniqueiniquity** [comment]
@johnjesse It just so happened that I merged the other one first, not out of any preference for the expressiveness of the change. Without knowing anything about the underlying package, I'd superficially agree that your change is more correct. But that would be up to one of the package owners to decide.

**Comment by uniqueiniquity** [comment]
Tagging @lumaxis for thoughts on which approach is better.

**Comment by 43081j** [comment]
I would rebase onto master and use this pr to simply change to `TArgs`. 

I would discard your changes to the tests during rebase as they already exist in master now. 

Making this pr near enough a one liner. 

I think it probably is more appropriate that always using `any`.

**Comment by uniqueiniquity** [comment]
@johnjesse Thanks for your contribution (and for your patience)!

**Comment by johnjesse** [comment]
no worries, thanks for your help :)

**Pull request merged**
