### PR TITLE
[ValidatorJS] Add isISO31661Alpha3

### PR DESCRIPTION
**Pull request by henrikra**
I noticed that ValidatorJS has [isISO31661Alpha3](https://github.com/validatorjs/validator.js#validators) but the types don't have it.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/validatorjs/validator.js#validators
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by henrikra** [comment]
@osdiab @kacepe @amcasey Can you guys check this out? :)

**Comment by osdiab** [comment]
Looks about right to me!

**Comment by henrikra** [comment]
@osdiab so what happens next?

**Comment by osdiab** [comment]
@henrikra I'm not a maintainer, so we just wait for one of them to show up, give it the thumbs up and then merge in. Shouldn't be too long! But if none of them show up in a reasonable timeframe typescript-bot will loop in `DefinitelyTyped` people to review it instead.

**Pull request merged**
