### PR TITLE
add types & methods from dockerode current (v2.4)

### PR DESCRIPTION
**Pull request by nlaplante**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/apocas/dockerode/tree/v2.4.2
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by Seikho** [comment]
👎 High care factor that `any` isn't introduced where the return types are known.
I also believe that authors are maintainers of the types. Can you remove your name as well.

**Comment by nlaplante** [comment]
I added my name as per the [DefinitelyTyped pull request checklist](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request). I can remove it if you wish so.

**Comment by Seikho** [comment]
Cool, you're right 🙂 
In reference to the `any` return types: Do you want to fix them or shall I?

**Comment by nlaplante** [comment]
The return types of the callbacks are the same data structures documented in the Docker API right?

**Comment by nlaplante** [comment]
I just added some type definitions. It's still incomplete. Let me know what you think about it.

**Comment by Seikho** [comment]
👍 Thank you 🙂

**Comment by sandersn** [comment]
@Seikho can you resolve the conflicts so I can merge this?

**Comment by sandersn** [comment]
Sorry I meant @nlaplante.

**Comment by nlaplante** [comment]
@sandersn done, and I fixed some dtslint errors

**Pull request merged**
