### PR TITLE
Fixed connect decorator.

### PR DESCRIPTION
**Pull request by jkanczler**
case 2. Improvement to existing type definition.
Now it can be applied on components that has custom properties or functions.

Reason:
When using connect on a class that has custom behavior like custom properties or function than the TypeScript compiler gives back the following error:
Unable to resolve signature of class decorator when called as an expression. Type 'ComponentClass<{}>' is not assignable to type 'void'.

I modified the test to contain my issue:
@connect(mapStateToProps)
class CounterContainer extends Component<any, any> {
    private myProperty: string; // custom "behavior"
}

According to TypeScript documentation:
"If the class decorator returns a value, it will replace the class declaration with the provided constructor function.

NOTE  Should you chose to return a new constructor function, you must take care to maintain the original prototype. The logic that applies decorators at runtime will not do this for you."

https://www.typescriptlang.org/docs/handbook/decorators.html

### CODE REVIEW

**Comment by minestarks** [comment]
@tkqubo / @seansfkelley any feedback?

The union type ```MyType | any``` doesn't quite make sense since it is the same as ```any```, which defeats the purpose of having ```MyType``` there at all.

Unfortunately I'm not familiar enough with React to understand your use case here -- will defer to other reviewers here.

**Comment by seansfkelley** [comment]
I would prefer this not get merged.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9951

**Comment by seansfkelley** [comment]
Erg, can't seem to edit on mobile, so double post. Downgrading this type to any, as you pointed out, is both redundant and needlessly lax. #9951 goes into more detail, but suffice to say, just making it compile is not enough. This will quickly leak any types all over your code!

Also in the future, please search before issuing a PR; #9951 mentions the offending error message almost verbatim on its title.

**Comment by jkanczler** [comment]
Hmm. You're right, I haven't checked the opened issues. Apologies for that.

And yeah, it seems it's more like a TypeScript problem rather than a react-redux definition bug as you mentioned in your opened issue. As decorators are experimental right now, maybe the connect function should be used as a function instead of a decorator. It's just so ugly to go down to the file to see the 'wrapping' of the constructor.

I'm thinking on a workaround right now, maybe we can do something like this:
```
  // A decorator that can mutate the constructor:
  interface ComponentMutator<TComponentConstruct, TOriginalProps, TOwnProps> {
    (component: ComponentClass<TOriginalProps>|StatelessComponent<TOriginalProps>): TComponentConstruct;
  }

  // Definition of connect:
  export function connect<TComponentConstruct, TStateProps, TDispatchProps, TOwnProps>(
    mapStateToProps: FuncOrSelf<MapStateToProps<TStateProps, TOwnProps>>,
    mapDispatchToProps?: FuncOrSelf<MapDispatchToPropsFunction<TDispatchProps, TOwnProps>|MapDispatchToPropsObject>
  ): ComponentMutator<TComponentConstruct, TStateProps & TDispatchProps, TOwnProps>;

// Usage of connect with component mutation:
@connect<{ new(): CounterContainer }, any, any , any>(mapStateToProps)
class CounterContainer extends Component<any, any> {
    private myProperty: string;
}
```
image

I'm not a TypeScript expert and I'm not a native English speaker either. So please, if you can find better name for it, give suggestions.

But after all, what do you think about the workaround?

**Comment by seansfkelley** [comment]
This doesn't work in the general case, unfortunately, as mentioned in the issue #9951 links to re: decorators that output a different type than they are given. A [stripped down example](https://www.typescriptlang.org/play/#src=interface%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09(component%3A%20T1)%3A%20T2%3B%0D%0A%7D%0D%0A%20%20%0D%0Afunction%20makeDecorator%3CT1%2C%20T2%3E()%3A%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09return%20function()%7B%7D%20as%20any%20as%20MutatingDecorator%3CT1%2C%20T2%3E%3B%0D%0A%7D%0D%0A%20%20%0D%0A%40makeDecorator%3Ctypeof%20Foo%2C%20typeof%20Bar%3E()%0D%0Aclass%20Foo%20%7B%0D%0A%09static%20foo%3A%20any%3B%0D%0A%7D%0D%0A%20%20%0D%0Aclass%20Bar%20%7B%0D%0A%09static%20bar%3A%20any%3B%0D%0A%7D) I put together to try this out:

```ts
interface MutatingDecorator<T1, T2> {
	(component: T1): T2;
}
  
function makeDecorator<T1, T2>(): MutatingDecorator<T1, T2> {
	return function(){} as any as MutatingDecorator<T1, T2>;
}
  
@makeDecorator<typeof Foo, typeof Bar>()
class Foo {
	static foo: any;
}
  
class Bar {
	static bar: any;
}
```

This fails, complaining that `'typeof Bar' is not assignable to type 'void'`, since a class decorator must be of type `T => T | void`. It _does_ work if the output class is a superset of the input one (try deleting `static foo`), but that's pretty sketchy.

Perhaps there is something here that will allow the decorator to work properly in at least _some_ of the cases, but I'm not sure.

**Comment by jkanczler** [comment]
You forgot the inheritance. It much more realistic if you have inheritance between Bar and Foo. Bar inherits Foo. Here's the improved [example](https://www.typescriptlang.org/play/#src=interface%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09(component%3A%20T1)%3A%20T2%3B%0D%0A%7D%0D%0A%20%20%0D%0Afunction%20makeDecorator%3CT1%2C%20T2%3E()%3A%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09return%20function()%7B%7D%20as%20any%20as%20MutatingDecorator%3CT1%2C%20T2%3E%3B%0D%0A%7D%0D%0A%20%20%0D%0A%40makeDecorator%3Ctypeof%20Foo%2C%20typeof%20Bar%3E()%0D%0Aclass%20Foo%20%7B%0D%0A%09static%20foo%3A%20any%3B%0D%0A%7D%0D%0A%20%20%0D%0Aclass%20Bar%20extends%20Foo%20%7B%0D%0A%09static%20bar%3A%20any%3B%0D%0A%7D).

I think it's much more realistic. What do you think?

And actually, I forgot the typeof, so the usage:
```
@connect<typeof CounterContainer, ICounterStateProps, ICounterDispatchProps, any>(mapStateToProps)
class CounterContainer extends Component<any, any> {
    static myProperty: string;
}```

**Comment by seansfkelley** [comment]
Right, okay, so that passes type-checking at the decorator statement, but if I'm interpreting your intent correctly, the end result still isn't useful. The `T => T | void` restriction above still holds, so even though you return a superset of the original class (and it will behave as that class at runtime), the compile-time signature is still of the original class. [Updating the example](https://www.typescriptlang.org/play/#src=interface%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09(component%3A%20T1)%3A%20T2%3B%0D%0A%7D%0D%0A%20%20%0D%0Afunction%20makeDecorator%3CT1%2C%20T2%3E()%3A%20MutatingDecorator%3CT1%2C%20T2%3E%20%7B%0D%0A%09return%20function()%7B%7D%20as%20any%20as%20MutatingDecorator%3CT1%2C%20T2%3E%3B%0D%0A%7D%0D%0A%20%20%0D%0A%40makeDecorator%3Ctypeof%20Foo%2C%20typeof%20Bar%3E()%0D%0Aclass%20Foo%20%7B%0D%0A%09static%20foo%3A%20any%3B%0D%0A%7D%0D%0A%20%20%0D%0Aclass%20Bar%20extends%20Foo%20%7B%0D%0A%09static%20bar%3A%20any%3B%0D%0A%7D) (and using slightly less confusing terminology):

```
interface MutatingDecorator<TInput, TOutput> {
	(component: TInput): TOutput;
}
  
function makeDecorator<TInput, TOutput>(): MutatingDecorator<TInput, TOutput> {
	return function(){} as any as MutatingDecorator<TInput, TOutput>;
}
  
@makeDecorator<typeof Foo, typeof Bar>()
class Foo {
	static foo: any;
}
  
class Bar extends Foo {
	static bar: any;
}

// Fails typechecking, as you might expect.
let f: Foo;
f.bar;
```

`Bar` of course works fine, but `Bar` is not the class being decorated. The point is to be able to use `Foo` and have its compile-time signature reflect the result of applying the decorators. In any case, juggling multiple class definitions is not really the way that react-redux is designed, so I think any workaround down this route is going to be non-intuitive and work-intensive for the consumer.

**Comment by jkanczler** [comment]
Hmm. You're right. I've just getting to understand what is going on. Basically the connect function is giving back a new component that is wrapping the original one. Sorry, as I mentioned I'm just starting to learn React and Redux.

And the problem is TypeScript right now as a class decorator must be of type T => T | void. Then I have the following suggestion:

```
  interface ComponentDecorator<TOriginalProps, TOwnProps> {
    (component: ComponentClass<TOriginalProps>|StatelessComponent<TOriginalProps>): ComponentClass<TOwnProps> & void;
  }
```
That means, if you would like to use connect as a decorator, then the & operator will fulfill the restriction of TypeScript as class decorator T =>  T| void as now the result of the connect can assignable to type void.

But if you would like to use connect as a normal function. Then the result is assignable to ComponentClass<TOwnProps>. The void won't be a problem here, as void has nothing, so you can just see the properties and functions of the ComponentClass<TOwnProps>.

Sample code [here](https://www.typescriptlang.org/play/#src=declare%20class%20Base%20%7B%0D%0A%20%20%20%20constructor()%3B%0D%0A%09%0D%0A%09doSomething()%3A%20void%0D%0A%7D%0D%0A%0D%0Ainterface%20BaseClass%20%7B%0D%0A%20%20%20%20new()%3A%20Base%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20decorator()%3A%20(component%3A%20BaseClass)%20%3D%3E%20BaseClass%20%26%20void%3B%0D%0A%0D%0A%40decorator()%0D%0Aclass%20TestClass%20extends%20Base%20%7B%0D%0A%20%20someMethod()%3A%20void%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20TestClassWrapperClass%3A%20BaseClass%20%3D%20decorator()(TestClass)%3B%0D%0Alet%20testClassWrapperClassInstance%20%3D%20new%20TestClassWrapperClass()%3B%0D%0AtestClassWrapperClassInstance.doSomething()%3B).

**Comment by seansfkelley** [comment]
Hm, interesting workaround. I hadn't thought of that. `T & void` is an unusual signature, and I'm not clear on what weird side effects (if any) it might have on usage-as-a-function (i.e., will the propagation of the `& void` through all the usages of the `connect`ed class work as expected?). 

This is basically tricking the compiler into accepting the decorator form by lying and saying that `connect` operates strictly on side-effects (which is what a `void` type means in this context). The output type will (of course) be the same as the input type, so usage of this component elsewhere will erroneously claim to require/accept props that it shouldn't (i.e., those are are added by `map{State,Dispatch}ToProps`). This could be undesirable, since you will be forced to make all your `connect`-injected props optional or to otherwise work around the fact that those injected props are appearing on the signature of the decorated component, where they shouldn't be.

@tkqubo, thoughts? I don't use this as a decorator and I don't know the intricacies of the type system enough to know if `& void` is bad or not.

Re: the tests, I think you should be able to write meaningful tests without introducing more types. Can you do that? Also, using TSX instead of `new` would be preferable, since that's how these components are actually used and that's where they need to type check. Lastly, a comment on the `& void` explaining what, exactly, it's trying to do and what drawbacks it has would be appreciated.

**Comment by jkanczler** [comment]
Ahh. You're right again, it's ugly to use optional properties in the state props and dispatch props. I don't like that, because of the following sample scenario:

```
    const createIncrementAction = () => {
        return {
            type: 'INCREMENT'
        };
    };

    const createDecrementAction = () => {
        return {
            type: 'DECREMENT'
        };
    }

    interface CounterState {
        // Bug can be introduced here, if the modifications are not checked in all the mapStateToProps function
        // someone changed the value property to nameOfTheValuePropertyIsModified
        nameOfTheValuePropertyIsModified: number;
    }

    interface CounterStateProps {
        value?: number;
    }

    interface CounterDispatchProps {
        increment?: () => void;
        decrement?: () => void;
    }

    interface CounterProps {
        initialValue: number;
    }

    type CombinedProps = CounterStateProps & CounterDispatchProps & CounterProps;

    @connect(Counter.mapStateToProps, Counter.mapDispatchToProps)
    class Counter extends React.Component<CombinedProps, any> {
        static mapStateToProps(state: CounterState): CounterStateProps {
            // Bug can be introduced here, because of the modifications in the state
            // who is modified the CounterState won't be notified the error here, as value is optional in the state props
            return state;
        }

        static mapDispatchToProps(dispatch: Dispatch<CounterState>): CounterDispatchProps {
            return {
                increment: () => dispatch(createIncrementAction()),
                decrement: () => dispatch(createDecrementAction())
            };
        }

        onIncrement(): void {
            this.props.increment();
        }

        onDecrement(): void {
            this.props.decrement();
        }
    }

    ReactDOM.render(<Counter initialValue={1} />, document.getElementById('root'));
```

It seems, in TypeScript it's much more safe to use connect as a function instead of a decorator until something is proposed for TypeScript compiler.

Should I close the pull request then?

**Comment by seansfkelley** [comment]
I think so, yeah. The problems with optionality you pointed out I think are bad enough to be a deal-breaker, and it seems like the only reasonable way around this problem is language support for this  feature. 

Thanks for contributing, though!

**Comment by paulvanbrenk** [comment]
Closing this. Thanks for contributing though.

**Pull request closed without merging**
