### PR TITLE
[@types/react-flatpickr] Add className to DateTimePickerProps

### PR DESCRIPTION
**Pull request by fayway**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/coderhaoxin/react-flatpickr/pull/79>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by begincalendar** [comment]
@fayway thank you for your contribution.

Please see the [failed build log](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/487334961) for details on how to fix your patch.

_Hint: You can run "npm test" on your local machine to replicate the issue_.

**Review by begincalendar — CHANGES_REQUESTED** [review]
@fayway thank you for your contribution.

Please see the [failed build log](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/487334961) for details on how to fix your patch.

_Hint: You can run "npm test" on your local machine to replicate the issue_.

**Review by fayway — COMMENTED** [review]
Fix test

**Review by begincalendar — APPROVED** [review]

**Comment by begincalendar** [comment]
Thank you @fayway.

_Note: This fixes a regression I missed in #30924_

**Pull request merged**
