### PR TITLE
Adding Definitions for Ladda jQuery Plugin 0.9.4

### PR DESCRIPTION
**Pull request by leemicw**
These are the definitions for the Ladda button when wrapped in a jQuery object.

### CODE REVIEW

**Comment by vvakame** [comment]
@leemicw thank you for your contributions!
ladda.d.ts is already exists. https://github.com/borisyankov/DefinitelyTyped/blob/master/ladda/ladda.d.ts
please merge your modify to that definition file.

**Comment by leemicw** [comment]
@vvakame no problem, i saw the ladda file but thought since it was a the jQuery plugin definition it would go with the other jQuery files.  I should be able to update it later tonight.

**Comment by leemicw** [comment]
@vvakame I have update the pull request.  please let me know if you need anything else.

**Comment by vvakame** [comment]
@leemicw thanks mate!

**Pull request merged**
