### PR TITLE
Adds connect-modrewrite middleware

### PR DESCRIPTION
**Pull request by tinganho**
Title says it all

### CODE REVIEW

**Comment by vvakame** [comment]
*connect-modrewrite/connect-modrewrite.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/connect-modrewrite
  * http://bower.io/search/?q=connect-modrewrite
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (connect-modrewrite/connect-modrewrite-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@tinganho thank you for your contributions.
please rename connect-modrewrite/connect-modrewrite.ts to connect-modrewrite/connect-modrewrite-tests.ts. and fix travis ci failed.

**Comment by tinganho** [comment]
@vvakame I fixed the issues.

**Comment by tinganho** [comment]
I'm just wondering if you are going to put DT in a web service some time? I think when they see the size of the repo it would scare most people off.

**Comment by vvakame** [comment]
@tinganho please use connect-modrewrite-tests.ts, not connect-modrewrite-test.ts.

web service? http://definitelytyped.org/ ?
If users use tsd and dtsm, and if you use the NuGet, Though I think that it is not too troubled ....
@basarat @Diullei

**Comment by tinganho** [comment]
@vvakame sorry for the miss. I fixed it now.

I meant like `npm` but for `tsd`. So I can `tsd publish` without any review.

**Comment by vvakame** [comment]
@tinganho thanks, it merged.

please open new issue, if you want to talk more. :wink:

**Pull request merged**
