### PR TITLE
[react-native] Fix NavigationBarRouteMapper

### PR DESCRIPTION
**Pull request by ligaz**
`NavigationBarRouteMapper` properties return type should be the same as the one of `Component.render()` method: `JSX.Element | null`

### CODE REVIEW

**Comment by ligaz** [comment]
Ping @andy-ms

**Comment by andy-ms** [comment]
We don't accept pull requests to `types-2.0` any more (#13233). Please rebase onto `master`, then hit "Edit" in the upper-right and change the base branch to `master`.

**Comment by ligaz** [comment]
Done.

**Comment by ligaz** [comment]
Ping @andy-ms

**Comment by andy-ms** [comment]
If the reviewer (@bgrieder) hasn't responded in 3 days, ping me and I'll merge.

**Comment by mhegazy** [comment]
No response from other authors for over 2 weeks. Merging.

**Pull request merged**
