### PR TITLE
gapi.client Make Batch.add opt_params partial

### PR DESCRIPTION
**Pull request by runarberg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientbatchaddrequestopt_params--

### CODE REVIEW

**Review by Maxim-Mazurok — CHANGES_REQUESTED** [review]
Hello and thank you for the PR!

Before we proceed we'll need to verify if these types are correct.

From the [documentaion](https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientbatchaddrequestopt_params--) I can see that `opt_params` is an optional object. However, it's not clearly stated that all of its properties are optional as well. For [gapi.client.init(args)](https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientinitargs--), for example, they say "Every argument is optional", but not for the Batch.add.

Also, this is typed in the same way in another gapi types project: https://github.com/runarberg/DefinitelyTyped/blob/801d48635252a140eb6dc54681f4661d8b9a8661/types/gapi/index.d.ts#L316-L331

So, if you still believe that suggested types are correct - we'll have to confirm this with tests (because source code of gapi is minified and we're trying to solve this in the [Un-minified GAPI project](https://github.com/Maxim-Mazurok/gapi)):
1. When `opt_params = {}`
2. When `opt_params = { id: something }`
3. When `opt_params = { callback: something }`
4. Optionally, when `opt_params = { id: something, callback: somethingElse }`

I've added a few tests to figure out how GAPI loads API definitions here: https://github.com/Maxim-Mazurok/gapi/blob/master/client/test/modules.karma.js

It would be amazing if you could open PR in that repo with your tests for Batch.add.

Or at least some code that I can run myself (and hopefully transform it into tests) to experiment with how Batch.add works.

I realize that this might sound more complex than you originally anticipated, but this would move us closer to accurate GAPI types and ultimately help all of the Google API users out there, thank you!

**Comment by runarberg** [comment]
@Maxim-Mazurok Thanks for the feedback. The API docs don’t mention if the param is partial, but the guide for the batch method states:

> If an ID is supplied, the API attaches it to the response to this request. If no ID is supplied, the API generates a random ID.

And their examples show a param object without the `callback` field:

> ```js
> // Adding the request with an ID
> batch.add(getYou, {'id': 'getYou'});
> ```

https://github.com/google/google-api-javascript-client/blob/master/docs/batch.md

In my code I’m doing something like this:

```js
const copyBatch = gapi.client.newBatch();

for (const { id, owner } of conversations) {
  const name = displayName(owner);

  copyBatch.add(
    gapi.client.drive.files.copy({
      fileId: file.id,
      fields: 'id, parents, webViewLink',
      resource: {
        name: `${file.name}: ${name}`,
      },
    }),
    { id: `${id}` },
  );
}

// TODO: Just return this and run everything else behind the scenes.
const copyResults = await copyBatch;
```

If I find time tomorrow I can see about adding to the karma test module to confirm this works more reliably. I can also amend my PR to include equal changes to `HttpBatch` in `gapi/index.d.ts`.

**Comment by Maxim-Mazurok** [comment]
I see, it's very likely that your suggested types are correct, I just want to have a reliable way to verify this.
I don't consider their documentation to be reliable as they have many open unaddressed issues, like [this one](https://github.com/google/google-api-javascript-client/issues/629).
So let's try to come up with some tests for this. The current test doesn't require making actual API calls, but in your case, we'll probably have to make them, make sure you don't include your API key in the PR, would be ideal to make it read from `.env` file but just having a string const to replace would be a good start.

**Comment by Maxim-Mazurok** [comment]
Hey @runarberg I'm pretty happy to merge it as is if you confirm that it's working for you. Integration tests would be great, but shouldn't be a blocker for this, please let me know if that works, cheers!

**Pull request closed without merging**
