### PR TITLE
Fix es6 import for blueimp-md5.

### PR DESCRIPTION
**Pull request by mkohlmyr**
The exsting type definition allowed importing the module using `import { md5 } from "blueimp-md5";`, which leads to effectively calling blueimp-md5.md5 (undefined) as a function (once compiled with webpack).

The new definition allows the pre-existing alternative format: `import md5 = require("blueimp-md5");` as well as `import * as md5 from "blueimp-md5";` which also works correctly.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/blueimp/JavaScript-MD5#server-side
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
I'm not sure about this. ```import * as md5 from 'blueimp-md5'``` syntax isn't appropriate for this module as ```md5``` is not an ES6 module, it's a function. Looks like adding the empty ```declare namespace md5``` made the error go away but it's still incorrect - See http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y

**Comment by mkohlmyr** [comment]
I agree the semantics of it aren't very pretty, at the end of the day all I was trying to achieve here is to restrict the import formats that typescript marks as correct to ones that will actually work once compiled. (As mentioned, `import { md5 } from "blueimp-md5";` is currently indicated as being correct by TypeScript, but actually ends up with md5 being undefined.)

Is there a way to only permit `import md5 = require("md5");` and eliminate the other existing broken format?

The reason I went with this approach was that I saw it used in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/object-assign/index.d.ts which obviously should have similar semantics.

**Comment by paulvanbrenk** [comment]
@minestarks thoughts?

**Comment by minestarks** [comment]
Oops sorry for the delay. I was suggesting removing ```declare namespace md5``` from the .d.ts file and using ```import md5 = require("md5"); ``` in the test file. I agree with the rest of the change.

**Comment by mkohlmyr** [comment]
@minestarks making that change causes the typescript compiler in vs-code to not recognize the signature of the export.
 > [ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/[...]/DefinitelyTyped/blueimp-md5/index"' has no compatible call signatures.

Would the following be an acceptable solution (in addition to changing the test file import)? Using `export =` instead of `export default` appears to make both tsc and vs-code happy.
```typescript
declare function md5(value: string, key?: string, raw?: boolean): string;
export = md5;
```

If so I can make that change tomorrow and you guys can move on to bigger and better pull requests :)

**Comment by minestarks** [comment]
@mkohlmyr yup that's exactly what I was suggesting. Should have just typed it out, sorry!

**Comment by paulvanbrenk** [comment]
@mkohlmyr do you need to make any more changes?

**Comment by mkohlmyr** [comment]
Sorry about the confusion on my end, should be good to go now I believe.

**Comment by paulvanbrenk** [comment]
Thanks!

**Pull request merged**
