### PR TITLE
fix: issues/57402: @types/polkajs: error TS2430

### PR DESCRIPTION
**Pull request by btakita**
Interface 'Polka' incorrectly extends interface 'Trouter<RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>>'.

Types of property 'use' are incompatible.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/lukeed/polka/blob/master/packages/polka/index.js

### CODE REVIEW

**Comment by btakita** [comment]
This change includes converting the `Polka` interface to a class which extends the `Trouter` class.

**Review by pkuczynski — APPROVED** [review]

**Comment by btakita** [comment]
@pkuczynski I'm unable to reproduce this issue using the test suite on this project. I was able to reproduce this on another project. The interface approach in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57403/commits/ba7bfddfdac71589f179db0f1bb8171de07310ac seems to work while the previous class based approach does not seem to work.

**Review by amcasey — APPROVED** [review]

**Comment by btakita** [comment]
It looks like the polka package has it's own type definition.

https://github.com/lukeed/polka/issues/151

I move to deprecate this package in favor of polka's .d.ts

**Comment by btakita** [comment]
Ready to merge

**Pull request merged**
