### PR TITLE
ws: use numeric literals for readyState types

### PR DESCRIPTION
**Pull request by k-yle**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

ictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/websockets/ws/blob/master/doc/ws.md#ready-state-constants
- [x] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

### CODE REVIEW

**Comment by k-yle** [comment]
not sure what's causing tests to fail in a separate dependant pacakage. `npm run test-all` passes when I run it locally...

**Review by andrewbranch — CHANGES_REQUESTED** [review]
This is incorrect; it implies that there is a `require('ws').ReadyState` object at runtime. Enums should basically never be used in DefinitelyTyped. You can type the properties as numeric literals, but you can’t use an enum.

**Comment by k-yle** [comment]
I've changed it to just use numeric literals instead of enums @andrewbranch

I had assumed that enums exported by `@types/x` packages would be merged into `import { } from "x"` like how it works for types - but on second thought that doesn't make sense.

**Review by andrewbranch — APPROVED** [review]

**Comment by k-yle** [comment]
Ready to merge

**Pull request merged**
