### PR TITLE
[react-native] Reformat all files using prettier.

### PR DESCRIPTION
**Pull request by alloy**
I’ve already been using [prettier](https://github.com/prettier/prettier) with the Relay typings and think it makes sense to start using it for the RN typings too. This is the command I used and which we can periodically run to get all the style consistent again.

    prettier --parser typescript --tab-width 4 --semi --trailing-comma es5 \
             --write --print-width 120 \
             types/react-native{,/test}/*.ts*

@iRoachie @huhuanming @timwangdev @kamal Opinions? 👍 👎

### CODE REVIEW

**Comment by alloy** [comment]
cc @andy-ms

**Comment by huhuanming** [comment]
maybe need TSLint?

**Comment by alloy** [comment]
@huhuanming Can you elaborate on what you mean?

**Comment by huhuanming** [comment]
I'm sorry,  I misread it.

Read it on iPhone just now. 😳

It's cool. 👍

**Review by ghost — APPROVED** [review]

**Comment by iRoachie** [comment]
I am allllll for this lol! I keep having to turn off prettier when editing this :D

**Comment by alloy** [comment]
Aight, going for it 🕺

**Pull request merged**
