### PR TITLE
[@type/react-infinite-calendar]update: locale.locale

### PR DESCRIPTION
**Pull request by qkreltms**
This is related with https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38528

- [x] Test the change in your own code. (Compile and run.)
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/clauderic/react-infinite-calendar>>

### CODE REVIEW

**Review by christianchown — CHANGES_REQUESTED** [review]
Hi - can we be more specific with `locale` than `any`? I'm thinking that it should match the date-fns definition here:

https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L35-L63

**Comment by bart-lewandowski-conichi** [comment]
this was not approved ? how come ?

**Comment by qkreltms** [comment]
I'll do this soon.

**Comment by qkreltms** [comment]
@christianchown I've searched documentation when I found you referenced ```date-fns: 2.x.x```, but calendar uses ```"date-fns": "^1.27.2"``` as a result of this I think we should process this issues when react-infinite-calendar move date-fns version to 2.x.x

**Comment by bart-lewandowski-conichi** [comment]
also using 1.27 version of date-fns fix the issue and all works like it should im sorry i didnt wrote it right after i made it work :<

**Pull request closed without merging**
