### PR TITLE
angular-animate

### PR DESCRIPTION
**Pull request by rgvassar**
Added the on, off, and pin methods to the IAnimateService interface per [$animate documentation](https://docs.angularjs.org/api/ng/service/$animate).

### CODE REVIEW

**Comment by vvakame** [comment]
@rgvassar please wait for merge https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8150

**Comment by rgvassar** [comment]
Sounds good. Didn't realize those were new to 1.5.

**Comment by vvakame** [comment]
@rgvassar sorry for late. please resolve conflict.

**Comment by rgvassar** [comment]
Conflicts resolved.

**Comment by adidahiya** [comment]
lgtm :+1: would you mind squashing these commits?

**Comment by michelsalib** [comment]
Yep, squash, then :+1:

**Comment by vvakame** [comment]
please ping me again.

**Comment by vvakame** [comment]
please ping me again.

**Pull request merged**
