### PR TITLE
:fire: remove sources for angular-ui-bootstrap

### PR DESCRIPTION
**Pull request by peterblazejewicz**
The upstream module has been archived and no longer maintained. There was no native port, so DT module cannot be technically 'no longer required', so just removing sourves to save the Earth and maintainers sanity.

https://github.com/angular-ui/bootstrap
(public archive)

`angular-dialog-service` is being removed as it consumes `angular-ui-bootstrap`. The upstream module for this DT definition was last published to NPM 7 years ago:
https://www.npmjs.com/package/angular-dialog-service (never changed status to public archive, just abandoned)

Thanks!

### CODE REVIEW

**Comment by jakebailey** [comment]
Out of curiosity, was there an issue with this package that deleting it fixes?

**Comment by peterblazejewicz** [comment]
> Out of curiosity, was there an issue with this package that deleting it fixes?

No, I've noticed the DT module being updated in other maintainer's PR (ESLint config changes I'd recall, not sure atm). So just wanted to get rid of sources here, as the upstream is not maintained.

**Comment by jakebailey** [comment]
I'm a little wary of removing the types for a package that still gets >100k weekly downloads, but, it hasn't been updated in 6 years, yeah. At some point we should probably institute a max age for DT packages, but, at the same time it's kinda useful to have such a huge database of types to check TS PRs on.

**Comment by peterblazejewicz** [comment]
Understood, thanks!

**Pull request closed without merging**
