### PR TITLE
fix: add missing types 'line' to Strategy and UnlinkAccountsParamsProvider

### PR DESCRIPTION
**Pull request by gasugesu**
…vider

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
   - [x] https://marketplace.auth0.com/integrations/line-social-connection
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by danursin — COMMENTED** [review]
The docs do list line as a valid strategy for creating a connection. https://auth0.com/docs/api/management/v2#!/Connections/post_connections

Though I don't see it in the unlink provider dropdown they have in the docs.

**Comment by gasugesu** [comment]
@danursin 
Thanks for providing document links. 
I tried to find the list of unlink providers from the link you provided and found "line" in the dropdown at the bottom of it.
https://auth0.com/docs/api/management/v2#!/Users/delete_user_identity_by_user_id
screenshot

**Review by danursin — APPROVED** [review]
Documentation supports that this is an available provider/strategy. The addition of a union type is not runtime-testable so missing tests is understandable.

**Review by gabritto — APPROVED** [review]

**Comment by gasugesu** [comment]
Ready to merge

**Pull request merged**
