### PR TITLE
[passport-jwt] fix: Library agnostic to Express

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://gist.github.com/QuentinLemCode/2d03e59c1728e0ee907e45f27c8c75df >>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Version number updated to follow the version of passport-jwt

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/passport-jwt/passport-jwt-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c8be52cdb8518d371a6703156551c8aaada54518
</p>

**Comment by k725** [comment]
@QuentinLemCode 

There are some packages that are broken due to this change, and we have already reported this to the jwks-rsa package (https://github.com/auth0/node-jwks-rsa/issues/393), but there are some concerns.

1. Does `passport-jwt` itself support fastify? Or does this change make it work by chance? (Looks like this discussion remains in the passport package, so i think it doesn't seem to be explicitly supported https://github.com/jaredhanson/passport/discussions/818 )
2. Have you checked to what extent the `Express.Request` type and the undici `Request` type included in `@types/node` are compatible?

**Comment by QuentinLemCode** [comment]
> @QuentinLemCode
> 
> There are some packages that are broken due to this change, and we have already reported this to the `jwks-rsa` package ([auth0/node-jwks-rsa#393](https://github.com/auth0/node-jwks-rsa/issues/393)), but there are some concerns.
> 
> 1. Does `passport-jwt` itself support `fastify`? Or does this change make it work by chance? (Looks like this discussion remains in the `passport` package, so i think it doesn't seem to be explicitly supported [Is it possible to use passport.js with fastify framework? jaredhanson/passport#818](https://github.com/jaredhanson/passport/discussions/818) )
> 2. Have you checked to what extent the `Express.Request` type and the undici `Request` type included in `@types/node` are compatible?

1. Passport is express-compatible and thus, related strategies should follow this guideline. However, I'm using it with Fastify without issues and the lib works well too. The Fastify API is close from the express one, but I haven't deep down on that way.
2. No, I'm wrong on this. On this context, it should be something more closer to `IncomingMessage` . I open a PR to fix that.

**Comment by k725** [comment]
@QuentinLemCode I tried. I feel good.

**Comment by QuentinLemCode** [comment]
> @QuentinLemCode I tried. I feel good.

@k725 Can you add your review on the PR please?

**Pull request merged**
