### PR TITLE
Updated Google Chrome JavaScript API documentation

### PR DESCRIPTION
**Pull request by fredrikhr**
Added/Updated google Chrome JavaScript API definitions according to documentation from https://developer.chrome.com/extensions/api_index

### CODE REVIEW

**Comment by vvakame** [comment]
wow, what a huge patch!
@couven92 please resolve conflict.

*chrome/chrome.d.ts*

to authors(@matthewkimber @otiai10). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by couven92** [comment]
Ah, ok, so I should merge the file into the repo myself... First time, I'm doing this...

Will do... :-)

**Comment by couven92** [comment]
Merge complete

**Comment by otiai10** [comment]
@couven92 
Thanks for pull-req.
It might be good but too large to review for me. It would have been better if this pull-request is separated (by each module or chrome.* namespace).

Anyway, it could be merged, IMO.
Thank you,

CC: @vvakame

**Comment by vvakame** [comment]
thanks all!

**Pull request merged**
