### PR TITLE
[react-transition-group] Replace usage of React's global JSX namespace with scoped JSX

### PR DESCRIPTION
**Pull request by eps1lon**
Was deprecated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464. Cherry-picked from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67588.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-transition-group ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-transition-group@latest/))
was missing the following properties:
1. ReplaceTransition

## Formatting

The following files are not formatted:
1. types/react-transition-group/TransitionGroup.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c66eedfc23e255268d30dc198b0a5e4c599a9e19
</p>

**Review by ybiquitous — COMMENTED** [review]
Looks good. 👍🏼 

Just to confirm, what version did `@types/react` add the scoped `JSX` type?

**Comment by eps1lon** [comment]
15.17.7, 16.14.41, 17.0.59, and 18.2.6

**Review by ybiquitous — APPROVED** [review]
Thanks. This change is back-ported to older versions. 👍🏼

**Pull request merged**
