### PR TITLE
`react-modal`: add `portal` instance property

### PR DESCRIPTION
**Pull request by OliverJAsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactjs/react-modal/issues/486#issuecomment-324922621
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by jpowell — CHANGES_REQUESTED** [review]
I'm unsure what the use case is, for the instance of the react component to provide access to the `portal` variable. Do you have an example? I can't seem find this documented in the the component public API.

**Review by jpowell — CHANGES_REQUESTED** [review]
I guess to be more clear, can your test do the `focus` action in the component did mount where you're doing it in your use-case?

**Comment by OliverJAsh** [comment]
Done @jpowell

**Review by jpowell — APPROVED** [review]
Thanks!

**Comment by orta** [comment]
Cool, - looks good :+1:

**Pull request merged**
