### PR TITLE
[koa-session] fix: replace koa.Context with koa.BaseContext

### PR DESCRIPTION
**Pull request by liaozhongwu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jessetrinity** [comment]
@kerol2r20 @tlaziuk @hirochachacha any interest in this PR?

@liaozhongwu perhaps if you include context for the change in the PR description you will get a better response?

**Comment by hirochachacha** [comment]
@liaozhongwu Could you fill in the template? At least, tests are necessary because it helps people understand usefulness of the change.

**Comment by liaozhongwu** [comment]
@hirochachacha Sorry, since it's just a type mismatch and test works fine now, I have no idea how to test the changes.

koa.Middleware use ParameterizedContext rather than Context, so overwrite of the Context has no effect to koa.Middleware.

the following code will show the problem to you:
`
import { Middleware, ParameterizedContext, Context } from 'koa';

const a: Middleware = (ctx: ParameterizedContext, next) => {
    // just any
    ctx.session;
};

// ts will throw error
// Type 'ParameterizedContext<any, {}>' is missing the following properties from type 'Context': session, sessionOptions
const b: Middleware = (ctx: Context, next) => {};
`

Thanks

**Comment by hirochachacha** [comment]
If the change will fix compilation error, why not add those as test cases?
We are making type definitions, runtime tests are not important. We want to resolve compilation errors.

**Comment by hirochachacha** [comment]
By the way, I could not reproduce the error. I've found the cause https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L664-L667.
This line make everything acceptable, so that whole `Context` type definitions turned into useless.
I don't know why this line was approved, I also don't know why you environment isn't affected.

**Review by sandersn — CHANGES_REQUESTED** [review]
Marking with "Request changes" so the bot will categorise correctly.

**Pull request closed without merging**
