### PR TITLE
Dedup createElement overloads in react/index.d.ts.

### PR DESCRIPTION
**Pull request by epabst**
Please fill in this template.

- [ yes ] Prefer to make your PR against the `types-2.0` branch.
- [ no ] The package does not provide its own types, and you can not add them.
- [ yes ] Test the change in your own code.
- [ done ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ done ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ n/a ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ n/a ] Run `tsc` without errors.
- [ n/a ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ n/a ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ n/a ] Increase the version number in the header if appropriate.

This is causing issues for ts2kt where it results in duplicate Kotlin methods.

### CODE REVIEW

**Comment by epabst** [comment]
Replaces https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12334.

**Comment by vsiao** [comment]
This may be fine, but in the future I want the last overload to be a proper catch-all so that we generate a more helpful error message. I don't know what ts2kt is, but have you considered that this may be a bug in that instead?

**Comment by epabst** [comment]
What is an example error message with and without a catch-all?

**Comment by epabst** [comment]
In other type-safe languages (Java, Scala, Kotlin, etc.) no two methods can conflict or it will cause a compilation error.  However, in looking at TypeScript, it looks like it doesn't have the concept of conflicting functions.  The first function that matches will be used.  I would highly prefer that, even if only by convention, TypeScript declarations not conflict with each other anyway.  That makes it less ambiguous and more type-safe.  How do you feel about that?

**Comment by epabst** [comment]
Rebased to fix conflict.

**Comment by paulvanbrenk** [comment]
This PR seems abandoned, please re-open when you made the requested changes.

**Comment by epabst** [comment]
@paulvanbrenk Maybe I've misunderstood.  What requested change?

**Comment by paulvanbrenk** [comment]
@epabst I believe like Travis failed, those should be fixed.. re-opened and kicked off a new Travis build.

**Pull request merged**
