### PR TITLE
react-modal: Remove default export

### PR DESCRIPTION
**Pull request by vladzdev**
Typescript not working with synthetic default import: https://github.com/reactjs/react-modal/issues/497

### CODE REVIEW

**Comment by HelveticaScenario** [comment]
can we get this merged?

**Comment by hallowatcher** [comment]
Looking good 👍

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
See above comment

**Comment by vlazh** [comment]
I updated test. But I suppose it's not necessary because 'react-modal' is an external javascript library and runtime behaviour will not change and 'new ReactModal()' will be work in both cases. From https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries: ...and then load the modules using import url = require("url"); or import * as URL from "url".

**Pull request merged**
