### PR TITLE
Update buffer.d.ts to include `buffer` in BufferEncoding union

### PR DESCRIPTION
**Pull request by lifeiscontent**
add `"buffer"` encoding

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodemailer/nodemailer/blob/f9a92ed5cbaa3ab2e5e17770ccfd5df506643ba5/test/mime-node/mime-node-test.js#L1455-L1457
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
this is actually a valid change.

```ts
Buffer.from('café', 'utf-8').toString('binary');
// prints 'cafÃ©'

Buffer.from('café', 'utf-8').toString('utf-8')
// prints 'café'
```

**Comment by lifeiscontent** [comment]
this is a valid change, but I'm not sure if this is the right approach, you can use `Buffer.from('foo', 'buffer')` but not `Buffer.from('foo').toString('buffer')` anyone have suggestions on the right approach?

a few ideas I've come up with is:

1. augment all the valid method calls with `BufferEncoding | 'buffer` or Exclude<BufferEncoding, 'buffer'> from calls that it doesn't make sense in

**Comment by lifeiscontent** [comment]
@eps1lon do you have any thoughts here on how to do this in a reasonable way?

**Comment by lifeiscontent** [comment]
can someone please give some feedback to the concerns I've outlined?

@microsoft @jkomyno @alvis @r3nya @btoueg @smac89 @Touffy @DeividasBakanas @eyqs @Hannes-Magnusson-CK @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @galkin @parambirs @eps1lon @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @bhongy @chyzwar @trivikr @yoursunny @qwelias @ExE-Boss @peterblazejewicz @addaleax @victorperin @ZYSzys https://github.com/nodejs @LinusU @wafuwafu13 @mcollina @Semigradsky

**Comment by Semigradsky** [comment]
> this is a valid change, but I'm not sure if this is the right approach, you can use `Buffer.from('foo', 'buffer')` but not `Buffer.from('foo').toString('buffer')` anyone have suggestions on the right approach?
> 
> the ideas I've come up with are as follows:
> 
> 1. augment all the valid method calls with `BufferEncoding | 'buffer'`
> 2. `Exclude<BufferEncoding, 'buffer'>` from calls that it doesn't make sense in
> 
> with 2. it feels like a bit of a foot gun because that would require devs to make intentional augmentations

We already have `BufferEncoding | "buffer"` in some interfaces: `SpawnSyncOptions` and `CommonExecOptions` in `node:child_process`, `WatchOptions` in `node:fs`. For me, the first variant looks better.

Also see `mkdtemp`, `readdir`, `watch` in `node:fs`. The argument type in callbacks differs if `encoding` is `"buffer"`.

**Pull request closed without merging**
