### PR TITLE
knex cb selectors: `this` is a `QueryBuilder`

### PR DESCRIPTION
**Pull request by osdiab**
In pretty much all the examples, the value of `this` is a `QueryBuilder` interface, so this just makes it so that gets applied in general, so that I don't have to explicitly in my own code say that this in fact is a `QueryBuilder`. Makes code completion work automatically.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: pretty much all of the documentation lol. But [this should be the relevant implementing code](https://github.com/tgriesser/knex/blob/50557f757121798cf2e1328afe085e80b6cdb4d1/src/formatter.js#L126).
- **N/A**: Increase the version number in the header if appropriate.
- **Nah.** If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by mastermatt — CHANGES_REQUESTED** [review]
There seems to be discrepancies between the returned value of the callbacks. 
The majority of the cases you switch out were typed as returning `void`. Note that `Function` is equivalent to `() => void`.
But your new fn type returns `any`.

Since the docs don't clarify, can you reference the src code for these? 
And add test please.

**Comment by osdiab** [comment]
With respect to `Function` being equivalent to `() => void`, isn't that not actually true? I can say

```
const foo: Function = (x: number) => "lol"
```

... and Typescript will say this is fine—whereas if I said

```
const foo: () => void = (x: number) => "foo"
```

... it would tell me there's a type error since `foo` shouldn't be returning anything.

---

As for adding a test, all of the existing code in the tests that use callbacks as arguments are already testing the functionality, so I don't see what the value of adding more test cases there is. It already is being tested by the typechecker.

---

I'll look into the source code for examples

**Comment by osdiab** [comment]
Pretty sure this is the relevant code, added to the description. Called with `this` set to `queryBuilder`, as well as the first argument it seems

https://github.com/tgriesser/knex/blob/50557f757121798cf2e1328afe085e80b6cdb4d1/src/formatter.js#L126

**Comment by mastermatt** [comment]
Sorry about what I said about `Function`, you're right. I should have double checked that before posting. I was trying to point out that some of the replaced fns where listed to return `void` and some `any`.

I agree with you on the src of how the callback is fired. That should make the fn type something like `type QueryCallback = (this: QueryBuilder, queryBuilder: QueryBuilder) => void;`

For the tests, now that `this` should no longer be considered `any` we should enforce it with something like
```ts
knex.select('*').from('users').union((builder) => {
  let self: Knex.QueryBuilder = this;
  self = builder;
});
```

**Comment by osdiab** [comment]
This is more of a qualitative thing, but if we enforce the `queryBuilder` parameter, then even if people use `this` to access the same thing, tsc will yell at the user for missing that param... which technically it is correct that it will be there, it does seem to mess with the syntax sugar of the library.

Would it be no good to make it an optional arg in the typings? it's technically wrong, but it reflects how code is written in the documentation rather than how it is truly implemented internally.

**Comment by mastermatt** [comment]
Is that correct about `tsc` yelling for the missing param?
I can't pre-produce that even with `"strict": true` in `tsconfig.json`.
If you make it optional, users would have to assert it wasn't undefined before use.

**Comment by osdiab** [comment]
Ah my bad, the example code I wrote was not actually testing that. You're right. OK, thanks for the conversation! pushing up those edits.

**Review by mastermatt — APPROVED** [review]
This is great. Thanks.

**Pull request merged**
