### PR TITLE
Fix errors encountered while typing example from the official repository

### PR DESCRIPTION
**Pull request by arthurflachs**
Type errors encountered while typing this example from the draft-js repo
: https://github.com/facebook/draft-js/blob/dc4351e7d6c8fbfb37dfa0a899d26f8bec8981f0/examples/draft-0-10-0/entity/entity.html#L40-L92

See :
* https://github.com/facebook/draft-js/blob/dc4351e7d6c8fbfb37dfa0a899d26f8bec8981f0/src/model/encoding/RawDraftEntity.js#L20-L25
* https://github.com/facebook/draft-js/blob/dc4351e7d6c8fbfb37dfa0a899d26f8bec8981f0/src/model/encoding/RawDraftContentBlock.js#L22-L32

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/draft-js/blob/dc4351e7d6c8fbfb37dfa0a899d26f8bec8981f0/examples/draft-0-10-0/entity/entity.html#L40-L92

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## draft-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/draft-js@latest/))
was missing the following properties:
1. EntityInstance
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ba2f14ed4e39f61b49061eda64b329bf3a356da2
</p>

**Comment by amcasey** [comment]
Without actually knowing flow, I would have guessed that `name: ?type` meant `name` was required but could be undefined/null, whereas `name?: type` meant `name` was optional.  Is that not the case?

Is it possible the example is just out of date?

**Comment by arthurflachs** [comment]
Thanks for the feedback!

From what I understand : `name: ?type` is a [Maybe type](https://flow.org/en/docs/types/primitives/#toc-maybe-types). It can be void, and is omitted in one of the examples.
I think the only difference is that `name?: type` would throw if name is `null`, whereas it would be fine with `name: ?type`

**Comment by orta** [comment]
Confirming @amcasey's earlier feedback `?string` represents `undefined | string` - if you try remove some of the keys from this object in the flow playground you'll see that the keys are required 

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBKBDA7gEShgMxgGEIA7GYCgIQBsIBjAazgF44BvAKDjieEQAuOAH4AzjCgBLMgHMANDwTJgwgERrFvSiBjCJ0uVrgATYGBgALYSLIBXALYAjYFGMzaM4AGUktYJhywGI2AIJQ+IgAPBhkiAB8xlQwUkiBssFhERjRsQnGJhgwGCLCAPJOAFbADDDGDJZStCZQVKVw4ZFRmLj4RKQUyXSMTIlKAHSTXAC+ANxcXAzkEnAYwj14hCTklDT0zGycSkgo6prHoHpwGgXmVsIATMb8QnB2ZGYEXibuZJ5kPj8AViGRCbw+wC+AJ+SmSqUQ6Uy4M+30U0zgXCAA

**Comment by arthurflachs** [comment]
Thanks! I was not reading the right part of the doc I suppose, apparently it can be [omitted for an argument](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBKBDA7gEShgMxgGEIA7GYCgIQBsIBjAazgF44BvAKDjieEQAuOAH4AzjCgBLMgHMANDwTJgwgERrFvSiBjCJ0uVrgATYGBgALYSLIBXALYAjYFGMzaM4AGUktYJhywGI2AIJQ+IgAPBhkiAB8xlQwUkiBssFhERjRsQnGJhgwGCLCAPJOAFbADDDGDJZStCZQVKVw4ZFRmLj4RKQUyXSMTIlKAHSTXAC+ANxcXAzkEnAYwj14hCTklDT0zGycSkgo6prHoHpwGgXmVsIATMb8QnB2ZGYEXibuZJ5kPj8AViGRCbw+wC+AJ+SmSqUQ6Uy4M+30U0zgCyWZBWBDIhwAFGtRAYZLIAJTCABuECkJjY8U40y4uPxZNmQA), which is why I got confused.

I will try to update the PR tomorrow

**Comment by arthurflachs** [comment]
After checking, it looks like I don't have any change to make after this conversation, so I will close the PR.

Thanks for the feedback!

**Pull request closed without merging**
