### PR TITLE
Globalize definition for NuGet package v0.1.3.

### PR DESCRIPTION
**Pull request by eloekset**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by eloekset** [comment]
I've tried asking the NuGet package owners which version of Globalize corresponds to the NuGet package v0.1.3, but no answer back yet. https://www.nuget.org/packages/jquery-globalize/0.1.3

I'll update the comment that fails the test when I know the correct version.

Globalize has breaking changes after this version, so all projects that I work on are stuck at this version because DevExtreme.Web is stuck at this version.

**Comment by eloekset** [comment]
@vvakame, does this PR look ok now?

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by eloekset** [comment]
Is this a 👎 @staxmanade?

**Comment by eloekset** [comment]
So how do we get a TypeScript definition for the Globalize v0.1.3 NuGet package?

**Comment by staxmanade** [comment]
Sorry didn't mean to close this...ill have a look in a bit...

**Comment by staxmanade** [comment]
@eloekset I hope this helps you out...

**Comment by eloekset** [comment]
Thanks a lot! :)

**Pull request merged**
