### PR TITLE
Files moved to types-2.0

### PR DESCRIPTION
**Pull request by MindfusionSoftware**
Please fill in this template.
- [X] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by MindfusionSoftware** [comment]
Checklist:
jsdiag/jsdiag.d.ts has a correct naming convention and has passed the Travis CI test before: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12288

We got an email-request to move the PR to the types-2.0 branch which we did. The compile errors listed above do not seem to have anything to do with our files.

**Comment by andy-ms** [comment]
Failing tests here are OK, they are fixed by #12344.

**Comment by andy-ms** [comment]
`types-2.0` packages use a different [structure](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) than `master`.
Also, it looks like the package comes bundled with its own types.

**Comment by MindfusionSoftware** [comment]
Thanks for your cooperation. We have changed the dir structure to comply with the types-2.0 rules. Here it is:

https://github.com/MindfusionSoftware/DefinitelyTyped/tree/types-2.0/jsdiag

Should we close this PR and open a new one for that?

**Comment by andy-ms** [comment]
You could, but I still wonder why you need to make a PR to DefinitelyTyped if the types are already bundled into the package.

**Comment by MindfusionSoftware** [comment]
Could you clarify what "bundled into the package" means?

We are sending you a PR because our users asked us to add the mindfusion definitions at the official @types repository. They want to use the angular-cli tool which pulls definitions from DefinitelyTyped.

**Comment by andy-ms** [comment]
For NPM packages at least, we would absolutely want typings to be bundled -- users only need to call `npm install` once, typings are guaranteed to be up-to-date, and package authors don't need to wait for their PR to be accepted to DefinitelyTyped.

When I go to http://www.mindfusion.eu/javascript-diagram.html and download the trial, I get a ZIP drive containing `jsdiag.d.ts`. I don't know how exactly people will be installing jsdiag into their projects, but possibly the same process that installs `.js` files could install `jsdiag.d.ts` as well.

If you think that would be too difficult, we could accept a duplicate copy of it into DefinitelyTyped; but any time you wanted to update the types, you would need to make a PR here.

**Pull request closed without merging**
