### PR TITLE
Add definitions for bootstrap-select

### PR DESCRIPTION
**Pull request by LKay**

### CODE REVIEW

**Comment by sousarka** [comment]
@LKay can you please make it available to types-2 branch also so that it goes to npm@types.

**Comment by LKay** [comment]
@sousarka Yeah, I will make a change soon.

**Comment by Jogai** [comment]
I'm a bit new to TS, but I think selectpicker returns a jquery object.

**Comment by ioanes** [comment]
Return types shouldnt be void;

This code is returning value of an input
```code javascript
$(input).selectpicker('val');
```
Its a good idea to change it to any at least.

**Pull request merged**
