### PR TITLE
Add jest.mockRestore()

### PR DESCRIPTION
**Pull request by KSXGitHub**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jestjs.io/docs/en/mock-function-api#mockfnmockrestore
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by KSXGitHub** [comment]
Since the bot didn't mention you: @NoHomey, @jwbay, @asvetliakov, @alexjoverm, @epicallan, @ikatyang, @wsmd, @JamieMason, @douglasduteil, @ahnpnl, @joshuakgoldberg, @UselessPickles, @r3nya, @hotell, @sebald

**Review by JoshuaKGoldberg — APPROVED** [review]
Sweet!

**Comment by wsmd** [comment]
Hmmm... this is an interesting one. It seems like `.mockRestore()` is already a method on the `SpyInstance` interface, which is what `spyOn` returns:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/263e4088446ef5717d322e21e97b972c917ad59b/types/jest/index.d.ts#L729-L737

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/263e4088446ef5717d322e21e97b972c917ad59b/types/jest/index.d.ts#L200

So this matches the exact behavior explained in the documentation:

> Beware that mockFn.mockRestore only works when mock was created with jest.spyOn. Thus you have to take care of restoration yourself when manually assigning jest.fn().

However, according to Jest's implementation of mocks, `mockRestore` is _actually_ available on all mocks, and calling on a `jest.fn()` mock is technically valid.

https://github.com/facebook/jest/blob/f8efff95431dd079abf8ae02b8e541e3019d211b/packages/jest-mock/src/index.js#L485-L488

Although this will not work as one might think expected. This caveat is explained in the documentation anyway, so I'm not sure if that is enough reason not to include this in the type definition.

Given that, I'm going to approve this PR, but I'd love to hear what the other reviewers think!

One thing I'd like to mention, if this going to be merged, `SpyInstance` might be useless at that point; `spyOn` could return a `MockInstance` instead.

**Review by wsmd — APPROVED** [review]

**Comment by wsmd** [comment]
@JoshuaKGoldberg any thoughts? ☝️

**Review by r3nya — APPROVED** [review]

**Comment by jwbay** [comment]
I'm guessing we're trying to support something like this:
```ts
const api = {
  foo: () => 42,
}

const spy = jest.spyOn(api, 'foo').mockImplementation(() => null);
spy.mockRestore(); // expected to work, but currently doesn't

const mock = jest.fn().mockImplementation(() => null);
mock.mockRestore(); // not expected to work, currently doesn't, but would work with this PR
```

From a quick test, we could support this by making the chainable mock functions return `this` instead of `Mock<T>`. Then the SpyInstance type is propagated correctly through chained calls.

**Comment by KSXGitHub** [comment]
> From a quick test, we could support this by making the chainable mock functions return `this` instead of `Mock<T>`. Then the SpyInstance type is propagated correctly through chained calls.

That's a good idea.

I was trying to get `jest.spyOn().mockImplementation().mockRestore()` to work so I haven't give much thought on this.

Does `mockRestore()` actually `return this` in its JavaScript code? In other words, if I call `mockRestore.call(somethingElse)`, what would it returns?

**Comment by KSXGitHub** [comment]
It seems that `mockRestore()` or any methods for that matter does not actually depends on `this`: [code](https://github.com/facebook/jest/blob/v23.6.0/packages/jest-mock/src/index.js#L464-L466)

**Comment by JoshuaKGoldberg** [comment]
No preference from me - looks good either way.

**Comment by KSXGitHub** [comment]
I also take a look at [Jest's flow definition](https://github.com/facebook/jest/blob/v23.6.0/flow-typed/npm/jest_v23.x.x.js#L33-L40) and see that both `jest.spyOn()` and `jest.mock()` return the same object that has `mockRestore()`. I think we should follows that and remove `SpyInstance`.

**Comment by KSXGitHub** [comment]
So I made https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29306 as an alternative.

**Comment by shawnmclean** [comment]
Hi, I just stumbled  on this.

What do I now do in this case?

```
  let someSpy: jest.SpyInstance
  someSpy = jest.spyOn(foo, 'someFunc');
```

**Comment by wsmd** [comment]
Hi @shawnmclean, thanks for the feedback!

`SpyInstance` was removed as of #29306. I can see how that's not going to work anymore in your case. I have just opened a PR (#29508) to restore it; we'll have to wait and see where it goes.

For the time being, you could use `MockInstance` as a workaround (perhaps not the right word since that's the only way to do it currently 😅). You still have to pass a generic type argument, though, to match your original/mocked `foo` implementation. 

```diff
-let someSpy: jest.SpyInstance
+let someSpy: jest.MockInstance<() => void>;

someSpy = jest.spyOn(foo, "someFunc");
```

Worth noting that changing that to `MockInstance` will be also future proof in case `SpyInstance` makes an appearance again.

**Pull request closed without merging**
