### PR TITLE
[mongodb] collection.findOne is coming back Closes #14444

### LINKED ISSUE #14444: @types/mongodb findOne in no longer deprecated
- [ ] I tried using the `@types/mongodb:2.1.38` package and had problems.
The functions findOne have /** @deprecated **/ comment. This @deprecated comment is causing problem in IntelliJ code completion - it puts strike through the method name.

This is the JIRA issue saying that it is no longer deprecated (some time in Dec of 2016) and it actually works in latest mongodb node.js driver (I tested it)

https://jira.mongodb.org/browse/NODE-890

### PR DESCRIPTION
**Pull request by hinell**
## Description
Quick fix of the revived collection.findOne() method according to official [docs](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#findOne) and [mongodb](https://jira.mongodb.org/browse/NODE-890) issue tracker:

### Closes 
#14444 
## Template
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Can you 👍 or 👎 , @CaselIT ?

**Comment by CaselIT** [comment]
👍 
@aozgaa No more DT bot?

**Comment by aozgaa** [comment]
Not sure what's up with the bot :/

**Comment by aozgaa** [comment]
Thanks for the contribution and reviews though :)

**Pull request merged**
