### PR TITLE
[@types/express-serve-static-core] Fix express-serve-static-core locals type so it can be overwritten

### LINKED ISSUE #46639: Error: Interface 'Response<ResBody>' incorrectly extends interface 'Response'
When I compile from typescript I get this bug

```
node_modules/@types/express-serve-static-core/index.d.ts:505:18 - error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.

505 export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
                     ~~~~~~~~

```

from my package.json 

```
    "dependencies": {
        "@types/i18n": "^0.8.6",
        "@types/jest": "^26.0.7",
        "@types/moment": "^2.13.0",
        "@types/node": "^14.0.26",
        "@types/node-schedule": "^1.3.0",
        "@types/ws": "^7.2.6",
        "@typescript-eslint/eslint-plugin": "^3.7.0",
        "@typescript-eslint/parser": "^3.7.0",
        "@types/express": "^4.17.7",
        "chokidar": "^3.4.1",
        "dblapi.js": "^2.4.0",
        "discord.js": "^12.2.0",
        "eslint": "^7.5.0",
        "eslint-plugin-jest": "^23.18.2",
        "express": "^4.17.1",
        "findit2": "^2.2.3",
        "i18n": "^0.10.0",
        "jest": "^26.1.0",
        "moment": "^2.27.0",
        "node-schedule": "^1.3.2",
        "npm-check-updates": "^7.0.3",
        "tree-kill": "^1.2.2",
        "ts-jest": "^26.1.4",
        "typescript": "^3.9.7"
    }
```

Anyone know what's wrong?

### PR DESCRIPTION
**Pull request by bryanph**
As mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46639#issuecomment-695227732, the `locals` type on the `Application` interface is of type `Record<string, any>` which currently prevents it from being extended. This adds a generic parameter to `Application` which allows you to extend `locals`

Closes #46639

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46639>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
First, this is popular enough to require some review from an owner.

Second, I looked at the issue and at the code.  The line that you changed is indeed coming from a change that was "recent" at the time that [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46639#issuecomment-695227732) was made --- it was done in #46230.  But after that, in #50390, there was an added `Locals` which might be useful here too?  (Using `any` is generally not a good idea...)

**Comment by bryanph** [comment]
Can add a `Locals` type parameter to the `Application` interface instead as well

**Comment by bryanph** [comment]
@elibarzilay thanks for the pointer on the response.locals. See the latest changes, I added a generic parameter on Application which allows you to extend `Locals` like you would do on `Response` and `Request`

**Comment by bryanph** [comment]
Ready to merge

**Comment by bryanph** [comment]
After trying this in a bigger project I'm not sure this is the way to go as now declaration merging doesn't work with `Application` (which is how most users tend to extend the types I think?)

**Pull request merged**
