### PR TITLE
Add abortSignal option to docker-modem & dockerode

### PR DESCRIPTION
**Pull request by pimterry**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/apocas/docker-modem/pull/132
  - https://github.com/apocas/dockerode/pull/630

The docker-modem PR adds support to pass abortSignal in the dial() method. The Dockerode PR adds the corresponding option to most methods there (in various cases changing the method signatures to allow optionally passing a new options param).

### CODE REVIEW

**Review by amcasey — APPROVED** [review]
These look like recent changes.  Does the version number in the header need to be updated?

**Review by thegecko — CHANGES_REQUESTED** [review]
A few formatting nits.

I fail to see the AbortSignal interface, is it brought in via another type?

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by thegecko** [comment]
> AbortSignal comes from the Node types

👍

**Pull request merged**
