### PR TITLE
feat(json-merge-patch): Upgrade package version

### PR DESCRIPTION
**Pull request by hkleungai**
As shown in [npm](https://www.npmjs.com/package/json-merge-patch?activeTab=versions), most users are using v1 already, and v0 is no longer having update anymore.

It makes sense to upgrade the package version accordingly.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by jakebailey** [comment]
Why change the tests to this extent?

**Comment by hkleungai** [comment]
I heard that changing tests can help get someone's review much quicker(?) 😂

**Comment by jakebailey** [comment]
I mean sure but I would consider not making a frivolous change; bumping the version is enough

**Review by jakebailey — APPROVED** [review]

**Comment by hkleungai** [comment]
Ready to merge

**Pull request merged**
