### PR TITLE
@types/sockjs-client add a timeout option

### PR DESCRIPTION
**Pull request by PutilovAI**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sockjs/sockjs-client

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## sockjs-client ([<kbd>unpkg</kbd>](https://unpkg.com/browse/sockjs-client@latest/))
was missing the following properties:
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2efeceb2636a1f659240904776c67b3c76e6a345
</p>

**Review by peterblazejewicz — COMMENTED** [review]
In order to be accepted, it requires version bump IMO:
https://github.com/sockjs/sockjs-client/releases/tag/v1.4.0
https://github.com/sockjs/sockjs-client/compare/v1.3.0...v1.4.0
am I correct?

**Comment by PutilovAI** [comment]
> In order to be accepted, it requires version bump IMO:
> https://github.com/sockjs/sockjs-client/releases/tag/v1.4.0
> [sockjs/sockjs-client@v1.3.0...v1.4.0](https://github.com/sockjs/sockjs-client/compare/v1.3.0...v1.4.0)
> am I correct?

You put right links, but I don't understand what the phrase 'bump IMO' means .

**Comment by renjfk** [comment]
He's basically saying you should probably also align type definition version with library since that option comes with v1.4.0.

By the way **IMO** stands for **in my opinion**.

**Comment by PutilovAI** [comment]
Ok. But which of these versions should I take? 
or **1.2.0** (next version of @types/sockjs-client)
or **1.4.0** (version of sockjs-client where timeout came) 
or **1.5.0** (current version of sockjs-client)

**Comment by renjfk** [comment]
It should be min 1.4 since the props you added appears on 1.4 specifically but if it also covers 1.5 meaning there's nothing new on it then it's safe to go with 1.5.

**Comment by peterblazejewicz** [comment]
@renjfk thx mate!

**Review by peterblazejewicz — APPROVED** [review]

**Review by renjfk — APPROVED** [review]

**Comment by PutilovAI** [comment]
Ready to merge

**Comment by PutilovAI** [comment]
@renjfk Why didn't typescript-bot publish the new version of package?

**Comment by peterblazejewicz** [comment]
@sandersn this bot thing, at your mercy, sire!

**Comment by sandersn** [comment]
The publisher was down all weekend, and is just now working again. There's a backlog so it'll still probably be a bit.

Status updates on #definitely-typed on discord.gg/typescript.

**Pull request merged**
