### PR TITLE
Redux logger 2.6.0

### PR DESCRIPTION
**Pull request by seansfkelley**

### CODE REVIEW

**Comment by arusakov** [comment]
LG2M
Maybe @theaqua review this too.

**Comment by theaqua** [comment]
In [2.6.0](https://github.com/fcomb/redux-logger/releases/tag/2.6.0) `level` option was changed.

**Comment by seansfkelley** [comment]
@theaqua fixed, how does it look now?

**Comment by theaqua** [comment]
Looks good!

**Pull request merged**
