### PR TITLE
storybook__addon-options: Add new attributes for withOptions decorator & bump type definition version

### PR DESCRIPTION
**Pull request by gaetanmaisse**
PR to fix issue discuss here in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30978#issuecomment-444011836

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/storybooks/storybook/commit/d309b918cc487a55bb29c21806fb38a00b05409e
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. -> It was already there

### CODE REVIEW

**Review by joscha — APPROVED** [review]
I think there is another PR with the same changes, can't find it right now as I am on mobile

**Comment by joscha** [comment]
@gaetanmaisse - you are right, that slipped past. Can we update the version?

**Comment by gaetanmaisse** [comment]
@joscha I resolved my PR conflicts, so everything should be ok when this PR will be merged

**Comment by amcasey** [comment]
@gaetanmaisse Thanks for sorting that out!

**Pull request merged**
