### PR TITLE
[@types/oracledb] Database types from number to DbType class

### PR DESCRIPTION
**Pull request by mfteuscher**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test oracledb`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [oracledb/types.js](https://github.com/oracle/node-oracledb/blob/main/lib/types.js)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by mfteuscher** [comment]
I chose to be really verbose in the specific DbTypes, since presumably these will be very constant, and it would be really rare to see a change in these constant type definitions. If you prefer them all to be more generic (just DbType without additional information), I can update the PR to reflect that.

**Review by Anonymous4078 — APPROVED** [review]

**Comment by dannyb648** [comment]
@mfteuscher Hey, thanks for your additions - I'm going to merge this branch into my 6.3.0 branch which includes all the changes needed for that - so we end up with a good aligned version number. Thanks fella!

**Comment by mfteuscher** [comment]
Ok, I would like to get this PR merged in, so if it's ok with you, I'll drop the version back to 6.2.9999 and merge so that we can still have these types in version 6.2.0, and then you'll still have your clean 6.3.0 update

**Review by Anonymous4078 — APPROVED** [review]

**Comment by dannyb648** [comment]
My worry here is these are really breaking changes as the underlying types will now be broken. I think the test is a good example of this fact. Really should we save these changes for the next breaking change? You are right these changes are from 6.x and missed out - my concern here is 6.2.1 will look like a patch change but could break everyones builds

**Comment by dannyb648** [comment]
I dont know who approved these changes - i wanted to bring them into 6.3.0 so we could do some proper testing before release - who is @Anonymous4078 and how have these been approved / merged before connor or I could sign off?

**Comment by Anonymous4078** [comment]
Even `@types/node` doesn't follow semantic versioning so I don't know what's wrong with pushing breaking changes in any version.
Moreover the popularity level of this package is low so not many will be affected by this

**Comment by dannyb648** [comment]
Just because other packages dont - doesn't mean we dont. This package has followed it since 3.x when Connor and I started maintaining it. Breaking peoples build in a small patch is not a good approach to opensource and damages its reputation. 

The popularity of the package may be low, but its still broken builds and an impacted community. These changes could've been tested and rolled out better with the community involved and aware. The changes @mfteuscher are great and a useful addition - and I want to thank him for his help.

**Comment by ritschwumm** [comment]
could it be this broke ExecuteOptions.fetchInfo? 
unless i am mistaken, the example code
```
 fetchInfo: {
                   "HIRE_DATE":    { type: oracledb.STRING },  // return the date as a string
                   "HIRE_DETAILS": { type: oracledb.DEFAULT }  // override fetchAsString or fetchAsBuffer
 }
 ```
 will not work after this is merged because FetchInfo is defined as
 ```
  fetchInfo?:
            | Record<
                string,
                {
                    type: number;
                }
            >
            | undefined;
 ```
 and `oracledb.STRING` is no longer a `number` but a `class DbType` now

**Comment by dannyb648** [comment]
I think this might be the type of breaking change that will happen - the question is - is it correct. should fetchInfo actually take in the new type based on the documentations? I'll have to have a look

**Comment by ritschwumm** [comment]
thanks you very much!

**Comment by mfteuscher** [comment]
fetchInfo has been deprecated as of oracledb v6

>Deprecated execution option attribute fetchInfo. Use the new [Using Fetch Type Handlers](https://node-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#fetchtypehandler) functionality instead.

[OracleDB Change log Reference](https://node-oracledb.readthedocs.io/en/latest/release_notes.html#node-oracledb-v6-0-0-24-may-2023)

**Comment by mfteuscher** [comment]
Example of code I'm currently using:
``` javascript
 fetchTypeHandler: function (metadata: Metadata<any>) {
      if (metadata.name === 'COLUMN_NAME_1' || metadata.name === 'COLUMN_NAME_2')
        return { type: oracledb.STRING };
 }
```

**Comment by ritschwumm** [comment]
@mfteuscher if i understand the documentation comments correctly, i should be able pass a fetchTypeHandler in ExecuteOptions - but the is no such property in the the ExecuteOptions yet, so typescript doesn't let me.

**Pull request merged**
