### PR TITLE
Missing "require" property on IComponentOptions

### PR DESCRIPTION
**Pull request by damianog**
Added missing require property on IComponentOptions

### CODE REVIEW

**Comment by mhegazy** [comment]
No response from other authors for over 2 weeks. Merging.

**Comment by zumbo** [comment]
Unfortunately, this is breaking everything. The require property has already been added. Now, when compiling, I get:

1707         require?: any;
typings/globals/angular/index.d.ts(1707,9): error TS2300: Duplicate identifier 'require'.
1717         require?: {[controller: string]: string};
typings/globals/angular/index.d.ts(1717,9): error TS2300: Duplicate identifier 'require'.

**Comment by AndreyUtka** [comment]
@zumbo +1. 

```typescript
        /**
         * Define object mapping to other directive or component required controllers.
         */
        require?: any;
        /**
         * Define DOM attribute binding to component properties. Component properties are always bound to the component
         * controller and not to the scope.
         */
        bindings?: {[binding: string]: string};
        /**
         * Whether transclusion is enabled. Enabled by default.
         */
        transclude?: boolean | string | {[slot: string]: string};
        require?: {[controller: string]: string};
```

**Comment by mhegazy** [comment]
should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9831

**Pull request merged**
