### PR TITLE
Adding properties related with custom styles

### PR DESCRIPTION
**Pull request by diego-antonelli**
Properties related with this PR https://github.com/mmazzarolo/react-native-dialog/pull/25

### CODE REVIEW

**Comment by ibarrae** [comment]
Looks great @diego-antonelli!. I can't review it so I guess we'll have to wait for someone else 😞

**Review by MrLuje — APPROVED** [review]
Looks good 👍

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Please increase the version number accordingly.

**Comment by diego-antonelli** [comment]
@SimonSchick please review again when you can

**Review by SimonSchick — APPROVED** [review]

**Pull request merged**
