### PR TITLE
chore(ol): remove redundant types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

shipped with types since 6.3.0:

https://unpkg.com/browse/ol@6.3.0/index.d.ts

### CODE REVIEW

**Comment by navya9singh** [comment]
This is a huge change, and it needs a review by the owner to ensure that it is appropriate.

**Comment by 43081j** [comment]
Of course, and ideally one or more DT maintainers. 

I don't particularly have any attachment to this package, I'm just doing cleanup. 

So if we want to avoid doing it for now, fine by me. Should happen one day though of course

**Review by gabritto — APPROVED** [review]

**Comment by 43081j** [comment]
@andrewbranch could you or one of the other maintainers give this a quick look over?

its huge but thats really just because `ol` itself seems to be, rather than anything to do with complexity or cross-package changes. so im fairly certain its a safe merge. but i'd still like a 2nd review if possible

**Review by andrewbranch — APPROVED** [review]
Looks good to me. Like you said, cross-package dependencies are scary, but this is just a lot of files. Not so scary.

**Pull request merged**
