### PR TITLE
Added missing options to Joi.string().guid()

### PR DESCRIPTION
**Pull request by JJayet**
This commit allow for a more complete guid validation.
See here for more informations : https://github.com/hapijs/joi/blob/master/API.md#stringguid---aliases-uuid

### CODE REVIEW

**Comment by laurence-myers** [comment]
Based on the docs, looks like you can pass an array of versions _or_ a single version. 

Can you please make the version param accept either an array or a single value?

**Comment by JJayet** [comment]
Sure, thanks

**Comment by JJayet** [comment]
@laurence-myers Done !

**Comment by laurence-myers** [comment]
Nice, thanks for the contribution! :)
👍

**Comment by JJayet** [comment]
Thanks :)

**Pull request merged**
