### PR TITLE
[react-dates] fixed inaccurate renderCalendarDay props

### LINKED ISSUE #36501: [@types/react-dates] renderCalendarDay prop type declaration incorrect
If you know how to fix the issue, make a pull request instead.

- [X ] I tried using the `@types/react-dates` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ArturAmpilogov, @NathanNZ 

If you do not mention the authors the issue will be ignored.

The type definition for `renderCalendarDay` appears to be incorrect.

```ts
renderCalendarDay?: (day: momentPropTypes.momentObj) => string | JSX.Element;
```

While the most recent source code for react-dates passes in a much more complext `props` object: https://github.com/airbnb/react-dates/blob/v20.2.5/src/components/CalendarMonth.jsx#L223-L239

### PR DESCRIPTION
**Pull request by cgriebel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [CalendarDay.jsx](https://github.com/airbnb/react-dates/blob/v17.1.0/src/components/CalendarDay.jsx)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

 fixes #36501.

### CODE REVIEW

**Comment by cgriebel** [comment]
This addresses https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36501

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dates ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dates@latest/))
was missing the following properties:
1. CalendarMonth
1. CalendarMonthGrid
1. DateRangePickerInput
1. DateRangePickerInputController
1. DateRangePickerShape

<details>
<summary>as well as these 3 other properties...</summary>
<p>DayPicker, SingleDatePickerInput, SingleDatePickerShape</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7fb59a10167ac33c5787f889352280672d2140d1
</p>

**Comment by johanjmoncada** [comment]
Someone knows what's needed to get the PR merged?

I need this definition for my current project, so, if something missed, I could try to take a look.

Cheers :)

**Comment by johanjmoncada** [comment]
Hi guys @ArturAmpilogov @NathanNZ is there something on this PR that is missed? I can help fixing those possible items to get this PR merged.

Thanks!

**Comment by NathanNZ** [comment]
Hey @johanjmoncada - apologies I've long since moved away from using this library. I really should have myself removed from the maintainer list!

Can you ensure that the version of your typings matches the correct version? (you've linked v21.8.0 however the type definition mentions v17.1.0)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7fb59a10167ac33c5787f889352280672d2140d1/types/react-dates/index.d.ts#L1

**Comment by cgriebel** [comment]
@NathanNZ, these types are for v17.1.0 as well, I accidentally linked the wrong version. I didn't fully update as there were a lot of other types missing, I planned on updating to v21.8.0 in a separate PR.

**Review by NathanNZ — APPROVED** [review]

**Comment by cgriebel** [comment]
Ready to merge

**Comment by cgriebel** [comment]
fixes  #36501.

**Pull request merged**
