### PR TITLE
Refactored sharepoint.d.ts to use microsoft.ajax.d.ts, added\fixed some definitions

### PR DESCRIPTION
**Pull request by gandjustas**

### CODE REVIEW

**Comment by vvakame** [comment]
@gandjustas thank you for your contributions.
could you make commits only pointed for summary?

**Comment by gandjustas** [comment]
I create definotions in different project  using separate files then merge it and copy new version to this repository. It's almost impossible to commit every change to two repositories. It there any way to automate process?

**Comment by gandjustas** [comment]
@vvakame Hi, i've pushed some empty commits for changes summary.
Please merge my request.

Thanks.

**Comment by vvakame** [comment]
@gandjustas why this PR contains file mode changing? 

---

*microsoft-ajax/microsoft.ajax.d.ts*

to author(@pjmagee). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by gandjustas** [comment]
@vvakame, sorry, I don't know, I don't touch them. What is the file mode?

**Comment by pjmagee** [comment]
I'm unsure of the changes, however the Author knows more about the uses of Sharepoint. 
It would be good if the tests were updated to demonstrate the changes.

**Comment by gandjustas** [comment]
Tests should be run on sharepoint pages. Can travis-ci automatically deploy sharepoint app?

**Comment by pjmagee** [comment]
Tests only need to be typescript related. They don't need to test an application.

**Comment by gandjustas** [comment]
Is test code runs? Or it just compiles?

**Comment by pjmagee** [comment]
compiles for ts.

**Comment by gandjustas** [comment]
I've added lots of test code from source repository.

**Comment by vvakame** [comment]
@gandjustas this is it. It represents the permissions.
refactored_sharepoint_d_ts_to_use_microsoft_ajax_d_ts__added_fixed_some_definitions_by_gandjustas_ _pull_request__4375_ _borisyankov_definitelytyped

**Comment by gandjustas** [comment]
How to revert these changes?

**Comment by vvakame** [comment]
try chmod command.

**Comment by gandjustas** [comment]
I'm on windows, there is no chmod command. Revert to previous version of files using git does nothing (no changes to commit) :(

**Comment by gandjustas** [comment]
Woo-ha! Reverted file modes. And fixed tests for microsoft-ajax.d.ts
@vvakame, please check in

**Comment by vvakame** [comment]
good! :+1: 
next, resolve conflict between this PR and master branch.

**Comment by gandjustas** [comment]
Finally fixed all issues.

**Comment by vvakame** [comment]
@pjmagee could you review this PR again? can i merge it?

**Comment by gandjustas** [comment]
Guys???

**Comment by pjmagee** [comment]
Yep looks good with me.

**Comment by vvakame** [comment]
@pjmagee thanks!
@gandjustas thanks mate! :+1:

**Pull request merged**
