### PR TITLE
Add types for new `express-flexible-mysql-session` (forked package from `express-mysql-session`)

### PR DESCRIPTION
**Pull request by mattwoolford**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by Ionaru — APPROVED** [review]

**Review by mattwoolford — COMMENTED** [review]
Added new type definitions to satisfy `express-flexible-mysql-session`

**Comment by mathe42** [comment]
1. As this is a npm package maintained by yourself you should just add the types to your package. No need to create it here...
2. Don't put some maintainers to a new types package without asking. Please remove me.

**Comment by mattwoolford** [comment]
@mathe42 Hi 👋 , apologies this was a mistake in the `package.json` file where you were listed as an `owner`, but you are a `contributor`. I have now fixed this.

**Comment by mattwoolford** [comment]
Adding types directly into the package.

**Review by Ionaru — APPROVED** [review]

**Pull request closed without merging**
