### PR TITLE
Add tokenizeAndStem() and attach() to stemmers

### PR DESCRIPTION
**Pull request by coyotte508**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/NaturalNode/natural#stemmers https://github.com/NaturalNode/natural/blob/master/lib/natural/stemmers/stemmer.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by coyotte508** [comment]
actually wouldn't it be better to declare all stemmers to be of type `Stemmer`?

**Comment by dmoonfire** [comment]
Having them extend `Stemmer` would be more DRY.

**Comment by coyotte508** [comment]
@dmoonfire done!

**Comment by dmoonfire** [comment]
I'm trying to figure out how the Travis build failed but the check says it passed.

**Comment by coyotte508** [comment]
Build failed, I force pushed, build succeeds but label wasn't changed

**Review by dmoonfire — APPROVED** [review]
Looks good.

**Pull request merged**
