### PR TITLE
[react-native] realign the RN types dependency to the right React version counterpart

### PR DESCRIPTION
**Pull request by kelset**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (added below)

This PR does some "maintainance work" for the `@types/react-native` (so no new tests have been added) - basically, one core issue currently with RN types is that they all depend on latest of `@types/react`.

This PR attends to that in the way that the [README suggest as ideal](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package=) (at the FAQ question "If a library is updated to a new major version with breaking changes, how should I update its type declaration package?"), by changing the dependency in the `tsconfig` - before proceeding I also asked in the TS Discord in the #definitely-typed channel.

Considering that RN 0.69, the current latest/main, is the first version to support [React 18](https://reactnative.dev/blog/2022/06/21/version-069#react-18), I've lowered the version of the versions 68 -> 64 to `@types/react` 17 (64 was the first version [to support it](https://github.com/facebook/react-native/releases/tag/v0.64.0)) and of 63 to `@types/react` 16.

On top of this, I've also added myself to the list of owners/authors of the package so that I can keep an eye on the RN types moving forward :)

### CODE REVIEW

**Comment by kelset** [comment]
> If I understand you correctly, would that mean if react releases a new version (react 19) that has breaking changes to the API we would then have to come back here and specify the "paths" field in the current tsconfig.json?

yeah - that's my understanding of how DT handles direct dependencies between types (see the links in the body)

**Comment by kelset** [comment]
About the CI error:
```
Error in styled-components-react-native
Error: 
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.
Before you debug, first try running:
   npm install --prefix /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/styled-components
Then re-run. Full error logs are below.
Errors in typescript@4.8 for external dependencies:
Error: ../styled-components/index.d.ts(21,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
Error: ../styled-components/index.d.ts(29,18): error TS2430: Interface 'CSSObject' incorrectly extends interface 'CSSPseudos'.
```

This also happened to me locally but running `npm install --prefix /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/styled-components` addressed it, I'm not sure what I'm supposed to do here on CI :(

**Comment by kelset** [comment]
I tried digging a bit more into `styled-components-react-native`; it looks like it has created some problems in the past.

Here are some key info:
* was created by @Methuselah96 here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914
* @thomazcapra attempted to address some issues for RN 67 here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59547 but the PR was abandoned because of CI issues
* at a later stage, @reichhartd tried again to address some problems here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60023 but CI was failing again because of this https://github.com/microsoft/DefinitelyTyped-tools/issues/413 by @sandersn

sooooo yeah. I'm not really sure what I should try to do - @sandersn any ideas? 🤔

**Comment by eps1lon** [comment]
I tried this in the past as well but didn't succeed. Can't remember in which PR though.

**Comment by jablko** [comment]
@kelset Thanks for the PR! I think this is the problem with the CI: https://github.com/microsoft/DefinitelyTyped-tools/pull/484#issue-1275254272

`styled-components-react-native` [depends on `styled-components`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0cdaceec056e291318c5bce030c8be6d4b3c6fa0/types/styled-components-react-native/index.d.ts#L35), [declares `styled-components/native`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0cdaceec056e291318c5bce030c8be6d4b3c6fa0/types/styled-components-react-native/index.d.ts#L7), the DT infrastructure currently incorrectly omits the dependency, so `styled-components`' transitive external dependencies ([CSSType](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5c49d4ddc6f5bd06c5cf04d911398f3db05ead54/types/styled-components/package.json#L4)) aren't installed.

You'll need some maintainer assistance, I think, either to land https://github.com/microsoft/DefinitelyTyped-tools/pull/484#issue-1275254272 (which will clear up the CI), or manually merge this PR in the meantime.

**Comment by kelset** [comment]
Thanks for the insights @jablko! Since today is 4th of July it's likely the maintainers are OOF, but hopefully by end of the week we'll have some more clarity :)

**Review by jablko — APPROVED** [review]
Although I'm unfamiliar with these types, I confirm the added path mappings will make `@types/react-native@0.63` depend on `@types/react@16`, etc. https://github.com/microsoft/DefinitelyTyped-tools/blob/068213db7286da860ce4d1d71e53ad0fc011fd24/packages/definitions-parser/src/lib/definition-parser.ts#L443

I also followed the links you provided to confirm >=0.69 supports React 18 and >=0.64 supports React 17.

Thanks! :+1:

**Comment by kuasha420** [comment]
@kelset LGTM! Will this makes the "[resolution](https://github.com/react-native-community/react-native-template-typescript/blob/8d24510f9d6195143828bc28e68f62ab9be14ca9/template/package.json#L33-L35)" field on community typescript template redundant?

**Comment by kelset** [comment]
> @kelset Lorenzo Sciandra FTE LGTM! Will this makes the "[resolution](https://github.com/react-native-community/react-native-template-typescript/blob/8d24510f9d6195143828bc28e68f62ab9be14ca9/template/package.json#L33-L35)" field on community typescript template redundant?

probably - I didn't know the TS template had a resolution

**Review by sandersn — APPROVED** [review]

**Pull request merged**
