### PR TITLE
update uuid to v3

### PR DESCRIPTION
**Pull request by felipeochoa**
This PR updates the typings for the `uuid` module to v3. (Related: #12820, #14286). Going from v2 to v3 had a breaking change:

> remove .parse and .unparse

and a backwards-compatible change:

> split uuid versions into separate files [i.e., allow importing 'uuid/v1' and 'uuid/v4' directly] 

Given the naming of submodules, I've moved the old definitions to `uuid-v2` rather than `v2`.

This PR does not address #12045, #10925,  #10153, etc., since I wasn't sure how to conditionally reference the `Buffer` type. 

***
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [main documentation](https://github.com/kelektiv/node-uuid/blob/master/README.md), [changelog](https://github.com/kelektiv/node-uuid/blob/master/HISTORY.md) -- this definition is updated for 3.0.0 and 3.0.1
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by felipeochoa** [comment]
```
Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/uuid/uuid-v2 has unused file index.d.ts
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:349:11
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:4:58)
```

I'm not sure what this error means. Do I need to add the old version to the new `tsconfig`?

**Comment by mhegazy** [comment]
jsut call the folder `v2` and not `uuid-v2`

**Comment by felipeochoa** [comment]
Updated!

**Comment by felipeochoa** [comment]
@mhegazy Travis is working now

**Pull request merged**
