### PR TITLE
React: Added attributes 'width' and 'height' to SVGAttributes for Rect.

### PR DESCRIPTION
**Pull request by benishouga**
Without these attributes, it becomes an error when compiling tsx including the rect element.

> error TS2339: Property 'height' does not exist on type 'SVGAttributes'.
> error TS2339: Property 'width' does not exist on type 'SVGAttributes'.

These are not supported on the [document](http://facebook.github.io/react/docs/tags-and-attributes.html).
But it seems to work in the definition of HTMLDOMPropertyConfig.

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3 @vsiao @jbrantly could you review this PR?

**Comment by jbrantly** [comment]
OK by me, except that the change needs to also be made to `react-addons.d.ts` and `react-global.d.ts` before a merge.

**Comment by vsiao** [comment]
I'd argue that maybe the right thing to do is to make `SVGAttributes extend HTMLAttributes` instead.

**Comment by benishouga** [comment]
@vvakame @jbrantly @vsiao Thank you for review. I tried updated :)

**Comment by jbrantly** [comment]
@vsiao Is that right though? I'm not saying you're wrong, but it seems that SVG attributes and HTML attributes have very little in common. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
And I don't believe HTML-land attributes apply to SVG elements unless the SVG element natively supports it (at least not according to the HTML5 spec as I read it).

**Comment by pspeter3** [comment]
Yeah, I agree with @jbrantly here. I don't think that we should make them extend `HTMLAttributes`. It seems fine for these attributes to be duplicated.

**Comment by benishouga** [comment]
@jbrantly @pspeter3 Thanks ! Updated :)

Which is DefinitelyTyped conform to standard spec, library spec or ease of use?

**Comment by vvakame** [comment]
@jbrantly @pspeter3 @vsiao thanks!
@benishouga thanks mate! DT has contribution guide. http://definitelytyped.org/guides/contributing.html . only it.
I want to do correctly along the specification.

**Pull request merged**
