### PR TITLE
Add the missing parameter type ArrayBuffer to SparkMD5

### PR DESCRIPTION
**Pull request by dnhy**
…5 class

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x]  Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x]  Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/satazor/js-spark-md5/blob/master/spark-md5.js#L452
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by ffflorian** [comment]
@dnhy please add a link to the source upon which you made the PR. Please also add a test.

Thank you!

**Comment by dnhy** [comment]
@ffflorian A test and code links have been added.Please check.

**Review by ffflorian — APPROVED** [review]
Thanks!

**Comment by dnhy** [comment]
Ready to merge

**Pull request merged**
