### PR TITLE
add easing functions to jquery and jqueryui

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Isn't easing part of jQuery UI not jQuery?

**Comment by johnnyreilly** [comment]
Also no tests.

**Comment by errorx666** [comment]
jQuery (without UI) defines $.easing.linear and $.easing.swing, with swing being the default used if none is specified.  jQueryUI extends the interface with many more.  This is how I have implemented the interfaces.

I will add tests.

**Comment by johnnyreilly** [comment]
Do you have a link to the docs please? I've had a quick look but found no mention of it.

**Comment by DickvdBrink** [comment]
@johnnyreilly it is in the docs of jQuery ui (http://api.jqueryui.com/easings/)
>jQuery core ships with two easings: linear, which progresses at a constant pace throughout the animation, and swing (jQuery core's default easing), which progresses slightly slower at the beginning and end of the animation than it does in the middle of the animation. jQuery UI provides several additional easing functions

**Comment by johnnyreilly** [comment]
Thanks @dickvdBrink. Yes I see what you mean about the docs. We try to avoid adding undocumented typings as a rule. But I kind of get why this is the way it is. Once we've got tests I'm happy to merge.

**Comment by errorx666** [comment]
Tests have been added.

**Comment by vvakame** [comment]
@johnnyreilly can i merge this PR?

**Comment by johnnyreilly** [comment]
Sure

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
