### PR TITLE
libxmljs: major overhaul of types to latest version

### PR DESCRIPTION
**Pull request by ComFreek**
Important changes:

- The previous libxmljs-tests.ts file used a require, thus made any
variable from the imported 'libxmljs' typed 'any'. Hence, the test file
actually tested no type declarations at all.
  This has been fixed via an ordinary 'import' statement.
- Enabled strict null checks in tsconfig.json
- Removed some exported classes (such as HTMLDocument) which are not
used anymore in more recent libxmljs versions.
- Added null return values to functions which sometimes return null,
e.g. prevSibling(): Node|null.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/libxmljs/libxmljs/wiki
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ComFreek** [comment]
The error is

> 
Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/libxmljs/v0.14 has unused file index.d.ts


I am not sure why it appears since I modified `libxmljs/tsconfig.json` to reference the `v0.14` version (see https://github.com/ComFreek/DefinitelyTyped/blob/8288004e20714284984de58fc6eef9896f19a4ee/types/libxslt/tsconfig.json#L16). I guess I'll wait until either @fdecampredon or one of the DefinitelyTyped maintainers comment.

**Comment by DanielRosenwasser** [comment]
I'm not sure what the "unused `index.d.ts`" rule is about (CC @andy-ms?), but I don't think we handle `vMAJOR.MINOR` folder names - I think we only support folders with new major versions.

**Comment by andy-ms** [comment]
We warn on files that are present in a directory but not present in the tsconfig, since those won't be published.
In this case, don't bother making a directory for the old version, since the major version hasn't changed.

**Comment by ComFreek** [comment]
[x] Done!
> In this case, don't bother making a directory for the old version, since the major version hasn't changed.

Unfortunately, it seems that libxmljs didn't follow semver. The typings for `0.18` are vastly different than for `0.14`. `libxslt`, however, depended on `0.14` (implicitly). In the last commit I had to refactor `libxslt` as well. This might break the typings for end users, though. But if @DanielRosenwasser is right, then there is no other solution.

**Comment by andy-ms** [comment]
We don't support separate minor versions, so yeah, you'll just have to replace it.

**Comment by ComFreek** [comment]
@lorenzleutgeb 

@lorenzleutgeb I apologize for that change. As far as I remember, I went through the [official libxmljs API docs](https://github.com/libxmljs/libxmljs/wiki/Document) synchronizing the typings. Since `Document.validate` was *not* mentioned there (until now) I removed it. Apparently, it was only "documented" in [source code](https://github.com/libxmljs/libxmljs/blob/3879e7b4790a5d49218db71578c64098c7d4d04c/lib/document.js#L87) and [in the wiki overview page](https://github.com/libxmljs/libxmljs/wiki)).

- [x]: Added the missing docs to wiki API documentation: https://github.com/libxmljs/libxmljs/wiki/Document
- [x]: Opened https://github.com/libxmljs/libxmljs/issues/525 to prevent further inconsistencies
- [x]: Created a PR to reintroduce `validate`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28737. @lorenzleutgeb It sounds as if you currently use libxmljs. If so, could you please test it in a "real-world scenario"? I don't use libxmljs at the moment.

**Pull request merged**
