### PR TITLE
[xrm] Add headerSection and footerSection support

### PR DESCRIPTION
**Pull request by filcole**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
- https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-footersection
- https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-headersection

### CODE REVIEW

**Comment by filcole** [comment]
@scottdurow / @daryllabar: I *think* this PR is OK, but I'm not 100% sure whether the interfaces for FooterSection or HeaderSection are OK as they are, or if they should be in a separate namespace.  Do you have any thoughts?  Thanks!

**Comment by filcole** [comment]
Thanks, @scottdurow. 👌  I've moved them into Xrm.Controls namespace.  I'm marking this PR as ready for review.  Any improvements/tweaks are gratefully accepted!

**Comment by scottdurow** [comment]
Here are the links to the docs:
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-footersection
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-headersection

**Review by daryllabar — APPROVED** [review]

**Comment by filcole** [comment]
Ready to merge

**Pull request merged**
