### PR TITLE
Add types for express-multipart-file-parser 0.1.x

### PR DESCRIPTION
**Pull request by chenasraf**
Types for [express-multipart-file-parser](https://www.npmjs.com/package/express-multipart-file-parser)

This is a relatively old package but it is still useful in some cases.

~I needed to use `esModuleInterop: true` in `tsconfig.json`, not sure if it was avoidable.~

Not sure about how dependencies should work - I only need `@types/busboy` and `raw-body` for the types they contain, as this package accepts their options, and passes them to the respective package.  

Therefore they needed to be contained in the type. I hope I defined the version numbers correctly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test express-multipart-file-parser`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## express-multipart-file-parser ([<kbd>unpkg</kbd>](https://unpkg.com/browse/express-multipart-file-parser@latest/))
was missing the following properties:
1. length
1. toString
1. toLocaleString
1. pop
1. push

<details>
<summary>as well as these 25 other properties...</summary>
<p>concat, join, reverse, shift, slice, sort, splice, unshift, indexOf, lastIndexOf, every, some, forEach, map, filter, reduce, reduceRight, find, findIndex, fill, copyWithin, entries, keys, values, includes</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8beef20320e77178145db96637719566078ce8bc
</p>

**Comment by cristovao-trevisan** [comment]
I didn't test but types look fine. If you can add me as owner too it'd be great!

**Review by cristovao-trevisan — APPROVED** [review]

**Comment by chenasraf** [comment]
@cristovao-trevisan done :)

**Review by cristovao-trevisan — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@chenasraf thanks!
LGTM!

**Comment by chenasraf** [comment]
Ready to merge

**Pull request merged**
