### PR TITLE
@testing-library/vue: Fix ConfigurationCallback type

### PR DESCRIPTION
**Pull request by cimbul**
The first parameter to ConfigurationCallback is the Vue *constructor* (or rather a localVue constructor as returned by [createLocalVue()](https://vue-test-utils.vuejs.org/api/createLocalVue.html#createlocalvue)), not a Vue instance. Also removed some unused imports.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [relevant line in source](https://github.com/testing-library/vue-testing-library/blob/af30961a9a633f7362abc7d6cc56c9d4d36a4232/src/vue-testing-library.js#L51)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by cimbul** [comment]
@afontcu, this is a fairly simple change, so if you have time I'd appreciate if you'd sign off on this. See the usage example I added to `testing-library__vue-tests.ts`.

I'm going to update the types for vue-testing-library v5 in a follow-up, but I wanted to get this fix in for v2 first.

**Review by afontcu — APPROVED** [review]
LGTM! I wonder if we should port types back to VTL repo to make all this changes more straightforward..

**Comment by cimbul** [comment]
Ready to merge.

@afontcu, it’s up to you if you want me to move these back to the main repo. IIRC, we put these here to follow DTL’s lead in moving their types to DefinitelyTyped, but they seem to have reversed that now. Honestly, VTL is small enough that it would be trivial to convert the main code to TS, but I understand if you don’t want to have to deal with that maintenance. Happy to help either way.

I’m going go ahead and put up the PR for v5 later today. We might as well update them while they’re here, and deal with any moves afterward.

**Comment by afontcu** [comment]
Sure! Thanks for your help :)

**Pull request merged**
