### PR TITLE
Support compatibility with lib.es6.d.ts for bluebird

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by falsandtru** [comment]
sorry, mistake. wip.

**Comment by falsandtru** [comment]
Fixed.

**Comment by vvakame** [comment]
great! please resolve conflict.
and add your name to definition header :+1:

**Comment by falsandtru** [comment]
Alright, please remove a reference for es6-promise if you need. es6-promise and bluebird has a conflict. Or we should fix es6-promise definition.

```ts
// Type definitions for MongoDB v2.1
// Project: https://github.com/mongodb/node-mongodb-native/tree/2.1
// Definitions by: Federico Caselli <https://github.com/CaselIT> 
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Documentation : http://mongodb.github.io/node-mongodb-native/2.1/api/

/// <reference path='../node/node.d.ts' />
/// <reference path='../es6-promise/es6-promise.d.ts' />
```

```diff
- /// <reference path='../es6-promise/es6-promise.d.ts' />
```

**Comment by falsandtru** [comment]
Ah, I understand. Now this pr has a conflict on master branch. Wait a moment please.

**Comment by falsandtru** [comment]
Seems difficult. I'll remake this pull-request. Please merge my new pull-request.

**Comment by falsandtru** [comment]
Please review and move to #7321.

**Pull request closed without merging**
