### PR TITLE
[mapbox-gl] update to mapbox-gl 1.13

### PR DESCRIPTION
**Pull request by dmytro-gokun**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.13.0
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by dmytro-gokun** [comment]
@dobrud @patrickr @macobo @LiamAttClarke @life777 @mklopets @amxfonseca Anyone? :)

**Comment by dmytro-gokun** [comment]
@amxfonseca Do you mind looking at this?

**Review by amxfonseca — APPROVED** [review]
Looks good. Just some new methods added. Seems like a safe change 👍

**Comment by dmytro-gokun** [comment]
Ready to merge

**Comment by dmytro-gokun** [comment]
@amxfonseca Thanks a ton, buddy :)

**Pull request merged**
