### PR TITLE
Missing SVG icon definitions

### PR DESCRIPTION
**Pull request by clbond**
I wrote a script to generate icon definitions for all of the files in the material-ui svg-icons folder. Enjoy.

### CODE REVIEW

**Comment by ngbrown** [comment]
@clbond Please add some examples to the test file and resolve the test errors.

Since these icons are not going to have unique properties, they could all share the same property interface.

I saw that you have an `export namespace Icons { ... }`.  The actual definitions could go there instead of having `export import ...` to each of the icons in the main namespace.  This would reduce the pollution in the main namespace and better organize the file.

**Comment by clbond** [comment]
Alright, will do

**Comment by clbond** [comment]
OK, I have made the changes you suggested and fixed the tests. I hope you will accept these changes as the DefinitelyTyped definitions for material-ui have diverged significantly from the current npm package. It is in fact not usable with the current version (without this pull at least).

Let me know if there is anything else you would like from me

**Comment by clbond** [comment]
Hello? Is this patch acceptable to merge now? It would be great because the type definitions for Material-UI are badly out of date / unusable with the current npm package. If you want other changes to the patch just let me know

**Comment by ngbrown** [comment]
@clbond Sorry about the delay in reviewing.

Please update the `material-ui` version in the file header to 0.14.0, since there are breaking changes (ES6 style imports).

As a whole, it looks good.

Thanks for your work.  You can add your name to the "Definitions by" list if you want notified of future merge requests.

**Comment by clbond** [comment]
Alright, done. Thank you very much.

**Comment by ngbrown** [comment]
:+1:

**Comment by vvakame** [comment]
@clbond please resolve conflict.

**Comment by clbond** [comment]
Y'all have implemented SVG icons in a way that fundamentally does not work with ES6 imports. I do not understand why you didn't just use my patch instead. My patch allows the examples on the material-ui site to work in TypeScript. The way it has been implemented outside this patch does not. So people are going to pull this type definition and try to use it with the examples from the Material-UI site, find out it doesn't work and probably get discouraged and drop the library. I do not understand why this was not pulled in months ago. As for the merge I have no interest in spending any more time on this unless it is actually going to be pulled into the master. I have fixed every issue y'all have raised. The only reason it conflicts is because it was not merged in a timely manner, which I believe places the responsibility upon you to merge it.

**Comment by ngbrown** [comment]
@clbond 

I agree that the SVG icons should work with ES6 imports.

Please re-base your changes to the current head of DefinitelyTyped.  You may want to squash into a single commit first before rebasing.  Then, resolve the conflicts by selecting the better solution, then perform a force push, then this pull request can be reviewed and merged.

I'm not a committer to this repository, but @vvakame relies on the community to review and provide improvements.  I wasn't involved with the merge that caused the issue with svg icons (#7906), but you are welcome to replace it with something better.  You had been asked to do the rebasing on this pull request before the conflicts by @malekpour got submitted. If you had, then it would have been simpler as there were no svg icons at that point.

**Comment by mxl** [comment]
Any progress with this pull request?

**Comment by mxl** [comment]
I copied definition to my project material-ui.d.ts from last @clbond fork commit.
Then I tried to import `DeviceAccessTime` icon and few other elements and use it in `render()` of my custom React component :

`import {List, ListItem, DeviceAccessTime} from 'material-ui';`

    render() {
        return (
            <div>
                <h1>{this.state.name}</h1>
                <DeviceAccessTime />
                <List>
                    <ListItem
                        primaryText={
                                <p>Hello</p>
                              }
                    />
                </List>
            </div>
        );
    }

With `<DeviceAccessTime />` it compiles but browser gives errors:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `t`.
>Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`.

Without `<DeviceAccessTime />` it works just fine.

**Comment by ngbrown** [comment]
@mxl use:

    import DeviceAccessTime from 'material-ui/lib/svg-icons/device/access-time';

In the actual library, it's not exported from the base `material-ui` and the definition in this pull request is wrong...  I am working on a new pull request that will include this one and others to fix a bunch of stuff.

**Comment by ngbrown** [comment]
@clbond This was included in #8314.  Check it out and close this pull request if that meets your needs.

**Comment by mxl** [comment]
@ngbrown Thx, it's perfect!

**Comment by clbond** [comment]
Yes, thank you Nathan. I also did not realize that the icons should not have been exported from the root 'material-ui' since I have always used the ES6 imports (import DeviceAccessTime from 'material-ui/lib/svg-icons/device/access-time').

**Pull request closed without merging**
