### PR TITLE
[nuxtjs__auth] enable TS detection in vuex

### PR DESCRIPTION
**Pull request by phips28**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by danielgek — APPROVED** [review]
LGTM

**Review by jonnyparris — APPROVED** [review]
LGTM

**Comment by phips28** [comment]
when do you merge this?

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## nuxtjs__auth ([<kbd>unpkg</kbd>](https://unpkg.com/browse/nuxtjs__auth@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'nuxtjs__auth'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6a21e9951dbbc16c7f4b1e18b12670c903248bb
</p>

**Comment by danielgek** [comment]
LGTM

**Comment by orta** [comment]
Looks like a bunch of people have 👍🏻  and the changes are additions only, merging

( note if you want PRs to be able to get merged faster, you can add tests to DT changes to avoid waiting for one of us to come by and merge )

**Pull request merged**
