### PR TITLE
Improve RC types

### PR DESCRIPTION
**Pull request by kusyka911**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. (not required in this PR)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/dominictarr/rc
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
The process will be easier if you'd add tests...

**Comment by kusyka911** [comment]
> The process will be easier if you'd add tests...

There were nos major updates of the `rc` package. But I'm not satisfied with the current return type of `rc` function. `{ [key: string]: any }` so I make it generic. As I see all documented API of `rc` were covered with tests before. So tests don't require any modifications.

**Comment by andrewbranch** [comment]
@kusyka911 please add tests that demonstrate what is changing here. DefinitelyTyped tests are for testing the _types_ that flow into and out of these libraries, and you made a significant change to the return type of the function. You need to show what effect that has in tests.

**Review by BendingBender — CHANGES_REQUESTED** [review]
Please address the comment in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54428#issuecomment-879260772

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by kusyka911** [comment]
> @kusyka911: Everything looks good here. I am ready to merge this PR (at e781801) on your behalf whenever you think it's ready.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️
> 
> (@DanielRosenwasser, @BendingBender: you can do this too.)

Ready to merge

**Comment by kusyka911** [comment]
Ready to merge

**Pull request merged**
