### PR TITLE
[better-sqlite3] allow generic result type on Statement methods

### PR DESCRIPTION
**Pull request by beenotung**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

This change is purely on typing , unrelated to underneath js library

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/better-sqlite3/index.d.ts
1. types/better-sqlite3/better-sqlite3-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eec8e01b0b261f8009c9bdd511e7cc7a63eb8fe2
</p>

**Comment by beenotung** [comment]
While the bot is waiting maintainers to review the PR, what can I do to speed up the process?

**Review by sant123 — APPROVED** [review]

**Comment by sant123** [comment]
Ready to merge

**Comment by sant123** [comment]
@beenotung just approved, thanks for the PR

**Comment by beenotung** [comment]
Thanks, I'll be able to help review subsequent PR on this package 💪

**Pull request merged**
