### PR TITLE
Fix/ibm db/missing types

### PR DESCRIPTION
**Pull request by tmill2000**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

CloseSync C++ implementation shows always returning true:
https://github.com/ibmdb/node-ibm_db/blob/52573c5a01a92c90ae8121d0115abab94fe215ff/src/odbc_statement.cpp#L1287-L1309

Close C++ implementation shows void return alongside a callback:
https://github.com/ibmdb/node-ibm_db/blob/52573c5a01a92c90ae8121d0115abab94fe215ff/src/odbc_statement.cpp#L1168-L1221

From ibm_db base library their docs show these methods do exist on an ODBCStatement:

Link: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-18-stmtclosecallback

image

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/ibm_db/ibm_db-tests.ts
1. types/ibm_db/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a8b06cac2f97d092bc1cbd8b6384e1618554e4cf
</p>

**Comment by tmill2000** [comment]
Open Question: Do I need to update the package.json version or will that happen automatically through deployment?

**Comment by tmill2000** [comment]
> ## Formatting
> The following files are not formatted:
> 
> 1. types/ibm_db/ibm_db-tests.ts
> 2. types/ibm_db/index.d.ts
> 
> Consider running `pnpm dprint fmt` on these files to make review easier.
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [a8b06ca](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a8b06cac2f97d092bc1cbd8b6384e1618554e4cf)

resolved

**Comment by tmill2000** [comment]
Bump @agov

**Comment by iisaduan** [comment]
@tmill2000 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71001#issuecomment-2435757927
You should manually bump the version in the package.json, and the version should reflect the latest version of the JS package that the types should be accurate for. (So if the intention after this PR is that the types should match the latest version of ibm_db, then the version should be bumped to 3.2.9999)

**Review by iisaduan — APPROVED** [review]
I'm marking as approve so you can merge if you don't want to update the version, but if you do decide to update, you can re-request me to approve again

**Comment by tmill2000** [comment]
@iisaduan -- I have synced the package version with the main library's latest release

**Review by iisaduan — APPROVED** [review]
Thanks! 😄

**Comment by tmill2000** [comment]
Ready to merge

**Pull request merged**
