### PR TITLE
Remove @types/gl-matrix now that gl-matrix ships with types.

### PR DESCRIPTION
**Pull request by davidnx**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

NOTE: Requested whitelisting in a separate PR here: https://github.com/microsoft/types-publisher/pull/787

### CODE REVIEW

**Comment by davidnx** [comment]
This is intended to resolve incompatibilities between the official gl-matrix types and the ones from @types/gl-matrix. Using @types/viewport-mercator-project would trigger issues like the following:

D:/example/node_modules/@types/gl-matrix/index.d.ts
TypeScript error in D:/example/node_modules/@types/gl-matrix/index.d.ts(9,1):
Definitions of the following identifiers conflict with those in another file: RANDOM, setMatrixArrayType, toRadian, equals, vec2, vec3, vec4, mat2, mat2d, mat3, mat4, quat  TS6200

     7 | // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
     8 | 
  >  9 | declare module 'gl-matrix' {
       | ^
    10 |     // Global Utilities
    11 |     export class glMatrix {
    12 |         // Configuration constants

**Comment by nbabanov** [comment]
@davidnx Please first merge the whitelist PR.

**Comment by davidnx** [comment]
@typescript-bot retry

**Comment by davidnx** [comment]
@nbabanov can you help re-run the failing checks now that the other PR went in?

**Comment by nbabanov** [comment]
@davidnx Just reword our commit and force push or add a whitespace somewhere.

**Pull request closed without merging**
