### PR TITLE
minor fixes to type definitions for datatables.net-fixedcolumns and datatables.net-select

### PR DESCRIPTION
**Pull request by Arik-neKrol**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://datatables.net/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Hi! Thanks for your effort here.

Unfortunately, you’ve checked the checkboxes in the PR template, but didn’t actually do the things they said:

> - [ ] Use a meaningful title for the pull request. Include the name of the package modified.
> - [ ] Provide a URL to documentation or source code which provides context for the suggested changes:

I have no way of reviewing this PR without some context about what this is and why the change is being made—the `heightMatch` property type makes sense with the title of this PR, but you’ve also removed an interface and added two more. Since these typings don’t have any owners that can vouch for your changes, we need to have some kind of documentation or source code or at the very least a verbal explanation of what this is about.

**Comment by Arik-neKrol** [comment]
> Hi! Thanks for your effort here.
> 
> Unfortunately, you’ve checked the checkboxes in the PR template, but didn’t actually do the things they said:
> 
> > * [ ]  Use a meaningful title for the pull request. Include the name of the package modified.
> > * [ ]  Provide a URL to documentation or source code which provides context for the suggested changes:
> 
> I have no way of reviewing this PR without some context about what this is and why the change is being made—the `heightMatch` property type makes sense with the title of this PR, but you’ve also removed an interface and added two more. Since these typings don’t have any owners that can vouch for your changes, we need to have some kind of documentation or source code or at the very least a verbal explanation of what this is about.

updated

**Comment by Arik-neKrol** [comment]
Removed interface because it doesn't work correctly. My mistake in previous PR.
Context: https://datatables.net/reference/api/#fixedcolumns

About new interfaces in datatables.net-select typings, it is to get access to api functions, that previous contributor not implement.
Context: https://datatables.net/reference/api/#select

**Comment by Arik-neKrol** [comment]
@andrewbranch do I need something else?

**Review by andrewbranch — APPROVED** [review]
Thanks for fixing this up!

**Pull request merged**
