### PR TITLE
moment: expose interfaces

### PR DESCRIPTION
**Pull request by jklmli**
enables type annotations for files using moment definitions as an external module

### CODE REVIEW

**Comment by jiaweihli** [comment]
Fixed tests, bump.

**Comment by vvakame** [comment]
umm... this PR is include a breaking change.
but I think this is good refactoring.

@Lakerfield @kingdango @horiuchi @DickvdBrink @adidahiya @michelsalib
can I merge this PR?

**Comment by horiuchi** [comment]
LGTM :+1:

**Comment by michelsalib** [comment]
:+1:

**Comment by kingdango** [comment]
It's been a while since I looked at any of this but I'll give it a :+1:

**Comment by vvakame** [comment]
@jiaweihli thanks mate! :+1: 
@horiuchi @michelsalib @kingdango thanks!

**Comment by Lakerfield** [comment]
:+1:

**Comment by kingdango** [comment]
Cheers @vvakame, for keeping this updated!  May the Force be with you...

**Pull request merged**
