### PR TITLE
Update ocLazyLoad definitions and tests to 1.0.1 spec.

### PR DESCRIPTION
**Pull request by ylibrach**
As defined at: https://oclazyload.readme.io/v1.0/docs/oclazyloadprovider.

### CODE REVIEW

**Comment by vvakame** [comment]
*oclazyload/oclazyload.d.ts*

to author(@rolandzwaga). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by ylibrach** [comment]
Thanks @vvakame. This is my first PR to DefinitelyTyped, so just curious, what happens if @rolandzwaga doesn't reply? He hasn't been active on GitHub in close to a year. Does the PR never get merged, or does someone else review it?

**Comment by vvakame** [comment]
@ylibrach if we can't get reply in 2 days. please ping me again.

**Comment by rolandzwaga** [comment]
Hi there, I see nothing wrong with ylibrach's changes, so as far as I'm concerned its a go ;)

**Comment by vvakame** [comment]
@rolandzwaga thanks!
@ylibrach thanks mate!

**Pull request merged**
