### PR TITLE
[react-native-auth0] Adding missing parameter 'strategy' for requireLocalAuthentication method and TimeoutError

### PR DESCRIPTION
**Pull request by joaquinperezlopez**
Hey guys, this is my first PR to this repo, so please, let me know if I missed anything regarding rules/community guidelines

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [https://auth0.github.io/react-native-auth0/CredentialsManager.html#requireLocalAuthentication](https://auth0.github.io/react-native-auth0/CredentialsManager.html#requireLocalAuthentication)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-native-auth0 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-native-auth0@latest/))
was missing the following properties:
1. TimeoutError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d87dc8e0e1fa5cfed8ebd25ce467786c79d2dec9
</p>

**Comment by joaquinperezlopez** [comment]
🔔 @ascariandrea @marknelissen @leoafarias @willdady @Bogidon @yammesicka @mdjarv @gfriedm4 @poovamraj — please take a look at this PR, I think it's ready to be merged

**Review by poovamraj — APPROVED** [review]
These are great improvements!

**Comment by joaquinperezlopez** [comment]
Ready to merge

**Pull request merged**
