### PR TITLE
Update HighchartsExportingOptions and HighchartsDataLabel interfaces

### PR DESCRIPTION
**Pull request by inad9300**
The HighchartsExportingOptions and HighchartsDataLabels interfaces now
include all the properties present in Highcharts version 5.0.0.

### CODE REVIEW

**Comment by baltie** [comment]
LGTM :+1: Thank you, @inad9300.

**Comment by vvakame** [comment]
conflict occured. @inad9300 please resolve it.

**Comment by baltie** [comment]
@inad9300 I think you've mixed up your branches... You have now pushed things into this PR that isn't related to highcharts, and the conflict in highcharts.d.ts is still unresolved. Or actually, I see that you've pushed this from your forks master branch. You're maybe not aware that updating the branch would update this PR as well. In the future, you should make your PRs from separate branches.

**Comment by inad9300** [comment]
This was a mixture between my ineptitude and graphical tools doing too much for you. Anyway, the conflicts in this PR should be fixed now. However, I have made the same mistakes as the last time: I committed many files unrelated with highcharts (just everything that git added to the stash by default) and did the changes from my fork's master branch. Sorry for that.

**Comment by baltie** [comment]
Yes, I have about the same experience with some graphical tools. :) I think this PR is okay again to be merged. 

:+1:

**Pull request merged**
