### PR TITLE
Remove JPush React Native

### PR DESCRIPTION
**Pull request by huhuanming**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/jpush/jpush-react-native>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
@DanielRosenwasser 

Could you help me review review this?

**Comment by amcasey** [comment]
@huhuanming might also like to have a look.

**Comment by huhuanming** [comment]
thx.

Maybe but need to remove this from repo, because the original repo will be added this typing.

keep it a while.

**Comment by huhuanming** [comment]
@DanielRosenwasser

😳

could you help me remove this from repo please.

the typing added the original repo just now.

**Comment by amcasey** [comment]
The steps for removing typings are here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package

**Review by amcasey — CHANGES_REQUESTED** [review]
It looks like some additional work is required before this can be removed.

**Comment by DanielRosenwasser** [comment]
Hey @huhuanming, can you just update the `notNeededPackages.json` file? Then I can pull this in.

**Comment by huhuanming** [comment]
I'll look into the matter right away.

**Comment by huhuanming** [comment]
is it okay now?

**Pull request merged**
