### PR TITLE
Feature: remove theme-ui and theme-ui__components typings (no longer needed)

### PR DESCRIPTION
**Pull request by flo-sch**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by flo-sch** [comment]
NOTE: I am unable to run `npm run test-all` locally for some reason (`npm v7.9.0`) 🤔 

> Error: Unused file ./types/styled-system/package-lock.json (used files: ["index.d.ts","styled-system-tests.tsx","tsconfig.json","tslint.json"])

Original issue: https://github.com/system-ui/theme-ui/issues/1582

**Review by hasparus — APPROVED** [review]
LGTM I suppose?

**Comment by flo-sch** [comment]
Not sure why typescript-bot things theme-ui is "probably deleted"?

Anyway, this is the very first time I remove a package here, so if someone who has done it before can confirm that's for the best, but I guess there is no big risk here anyway

**Comment by elibarzilay** [comment]
@flo-sch, looks like you did remove `theme-ui`, did you not intend to so?

**Comment by flo-sch** [comment]
> @flo-sch, looks like you did remove `theme-ui`, did you not intend to so?

This is intentional, theme-ui, as well as the scoped @theme-ui/* packages have been rewritten to TypeScript

**Comment by elibarzilay** [comment]
@flo-sch, so I'm not sure why you said:

> Not sure why typescript-bot thinks theme-ui is "probably deleted"?

:)

**Comment by flo-sch** [comment]
> @flo-sch, so I'm not sure why you said:
> 
> 
> 
> > Not sure why typescript-bot thinks theme-ui is "probably deleted"?
> 
> 
> 
> :) 

typescript-bot states:

> 2 packages in this PR
> 
> theme-ui (probably deleted!) on npm, on unpkg
> theme-ui__components (probably deleted!) on npm, on unpkg

I misunderstood this part: I thought it was mentioning the actual packages on NPM & unpkg (which are not removed) and not the types... 😅 
My bad!

Thanks for merging :)

**Comment by elibarzilay** [comment]
Ah, well, I can see how that's confusing.  I'll make it add a dash to make it clearer.

**Pull request merged**
