### PR TITLE
Added amplify with JQuery Deferred support

### PR DESCRIPTION
**Pull request by laurentiustamate94**
I modified the [original amplifyjs](https://github.com/borisyankov/DefinitelyTyped/tree/master/amplifyjs) definitions to support [JQuery deferred](https://github.com/laurentiustamate94/amplify-deferred)

### CODE REVIEW

**Comment by vvakame** [comment]
*amplify-deferred/amplify-deferred.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/amplify-deferred
  * http://bower.io/search/?q=amplify-deferred
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (amplify-deferred/amplify-deferred-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@laurentiustamate94 thank you for your contributions.
please rename amplify-deferred/amplify-deferred.d.ts to amplify/amplify.d.ts

**Comment by laurentiustamate94** [comment]
I respected the naming convention.
The npm package `amplify-deferred` is created and maintained by me; if needed I will upload the package to bower.
It does pass the [Travis-CI test](https://travis-ci.org/borisyankov/DefinitelyTyped/builds/79221116)
I don't think it should be renamed to `amplify` because it can create confusion between the current `amplifyjs` typings, and will not be the same with the npm package created.

So what should we do in this case? :)

**Comment by vvakame** [comment]
okay.

**Pull request merged**
