### PR TITLE
[ember] ObjectProxy allows setting

### PR DESCRIPTION
**Pull request by wagenet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://api.emberjs.com/ember/3.24/classes/ObjectProxy/methods/set?anchor=set
https://api.emberjs.com/ember/3.24/classes/ObjectProxy/methods/set?anchor=setProperties

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
This is great. Thanks! Can you also add a test confirming that it correctly allows setting props on the Proxy itself and not just the proxied value?

**Comment by wagenet** [comment]
@chriskrycho updated

**Comment by wagenet** [comment]
Ok, hopefully this is good enough now!

**Review by chriskrycho — APPROVED** [review]
Thanks!

**Pull request merged**
