### PR TITLE
react-native - Update backgroundColor of StatusBar

### PR DESCRIPTION
**Pull request by MoKhajavi75**
Add missing `@platform android`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://facebook.github.io/react-native/docs/statusbar#backgroundcolor>>

### CODE REVIEW

**Comment by alloy** [comment]
Thanks! Just needs a slight fix to make the linter green.

**Comment by MohamadKh75** [comment]
Whay should i do 🤔?

**Comment by alloy** [comment]
According to [the CI failure](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/581560379#L526),  the issue is on line 8221, so presumably there’s an extra space after the `*`?

**Comment by alloy** [comment]
Thanks!

**Pull request merged**
