### PR TITLE
update snapsvg & fix some test

### PR DESCRIPTION
**Pull request by tgfjt**
1. add `export function matrix():Matrix;` 
2. fix test for `tsc --noImplicitAny`
3. fix indent
### (1)

`Snap.Matrix` accepts empty arguments:
https://github.com/adobe-webplatform/Snap.svg/blob/84fbff7d512c8145c522b71fc9c872cb0bcae49a/src/matrix.js#L37-L42

### CODE REVIEW

**Comment by tgfjt** [comment]
@AllBogs could you also review please?

**Comment by AllBogs** [comment]
Looks good to me - calling "Snap.matrix()" without arguments gives the same result as using the constructor function through "new Snap.Matrix()" without arguments. Must admit I didn't pay much attention to the tests the first time around. Changes to them look good, at a glance. Changing the indendation everywere makes comparing a bit of a pain, though :sweat_smile:

**Comment by tgfjt** [comment]
Uh It's my bad.:sweat:
I'll split last commit into two.

**Comment by tgfjt** [comment]
ping @lhk @mattanja

**Comment by mattanja** [comment]
:+1: Looks good to me

**Comment by tgfjt** [comment]
@mattanja Thanks :smile:

**Pull request merged**
