### PR TITLE
Update popper.js types to 1.10

### PR DESCRIPTION
**Pull request by marcfallows**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/FezVrasta/popper.js/blob/v1.10.2/docs/_includes/popper-documentation.md#modifiers..preventOverflow.priority>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by joscha — APPROVED** [review]

**Review by seckardt — APPROVED** [review]

**Review by rhysd — APPROVED** [review]

**Comment by marcfallows** [comment]
Hmmm, I would have expected https://www.npmjs.com/package/@types/popper.js to have updated by now. I usually see it happen within a couple hours, not days...

**Comment by sandersn** [comment]
Looks like it's 1.10 now. Not sure what the delay was.

**Comment by sandersn** [comment]
The lint rules only allow two-part versions, so that's probably why it shows 1.10. I'm not sure of the reason for that limitation. @andy-ms @RyanCavanaugh do you know why?

**Comment by andy-ms** [comment]
We can't publish a specified patch version, because that may stay the same in the real library while the typings still need to be updated. So we increment the patch ourselves and it has no relation to the real library.

**Comment by FezVrasta** [comment]
Ok I see, btw the `computeStyle` modifier was added in the "not officially published" `1.10.0` version but it's missing here

**Comment by marcfallows** [comment]
@FezVrasta `computeStyle` modifier is not in the documentation here which is what I used to build up the 
types for the library: https://github.com/FezVrasta/popper.js/blob/v1.10.2/docs/_includes/popper-documentation.md#modifiers

**Comment by FezVrasta** [comment]
Sorry you are right, I must have forgot to publish the new doc 😔

**Pull request merged**
