### PR TITLE
[pino] Update pino v4 type definition

### PR DESCRIPTION
**Pull request by jeffryang24**
I am actually still using pino v4 in my project. I found that pino has not created the `v4` directory inside the DefinitelyTyped repo after released the v5 (current master branch), but the v3 directory exists.

Currently, I want to change the `formatter` method inside the `PrettyOptions` interface. Based on https://github.com/pinojs/pino/blob/v4.16.1/pretty.js#L180, the `formatter` method actually accepts two arguments, JSON object log data and an options object that exposes utility functions (https://github.com/pinojs/pino/blob/v4.16.1/docs/API.md#parameters-1). But, in `v4.16.1` d.ts file, it only accepts one argument.

**Step to revive pino v4 definition file**

1. First, I find the last v4 commit before major version change, which is at https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0dcfb2b4836606bf3bdace6ce688a8883cb0af7d#diff-1c4c896c1bac5fe476720d51fdbbf2d3.
2. Next, I copy all of the files in that commit, such as `index.d.ts`, `tslint.json`, `tsconfig.json`, and `pino-tests.ts` inside created `v4` directory. I also configure `tsconfig.json` to point `../..` in its `baseUrl` and `typeRoots`, and map `pino` to `pino/v4`.
3. After that, I compare the content of `index.d.ts` and `pino-tests.ts` with the `@types/pino@4.16.1` from [npm](https://www.npmjs.com/package/@types/pino/v/4.16.1) to make sure I get the correct version.
4. Then, I add the utility function interface and modify the `fomatter` method.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino/blob/v4.16.1/pretty.js#L180
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
The bot got confused about this one. This should have been in the fast-track bin, and should have pinged the v4 authors:

@psnider @BendingBender @screendriver

I'll merge this and watch npm to make sure that 4.16.2 gets published. I don't think any of the tags should get updated since TS 2.0-2.2 are stuck on pino v3.

**Review by sandersn — CHANGES_REQUESTED** [review]
Actually, is the version supposed to be 4.17 or 4.16? 
The header says 4.16 still but your description mentions 4.17.

**Comment by jeffryang24** [comment]
> Actually, is the version supposed to be 4.17 or 4.16?
> The header says 4.16 still but your description mentions 4.17.

Oh, sorry for that. Wrong url, but in 4.17 also shares the same api with 4.16. You can try diffcheck between https://raw.githubusercontent.com/pinojs/pino/v4.16.1/pretty.js and https://raw.githubusercontent.com/pinojs/pino/v4.17.6/pretty.js.

I will change the given link to v4.16, since I use 4.16 in my project. Pardon me... :bowing_man:

**Comment by jeffryang24** [comment]
> The bot got confused about this one. This should have been in the fast-track bin, and should have pinged the v4 authors:
> 
> @psnider @BendingBender @screendriver
> 
> I'll merge this and watch npm to make sure that 4.16.2 gets published. I don't think any of the tags should get updated since TS 2.0-2.2 are stuck on pino v3.

I also got confused when the bot said that this a new definition while the maintainer list already contains more than one person. :smile: Also, I still don't know why former contributor bump the version to v5 without maintaining the old v4 version...

**Pull request closed without merging**
