### PR TITLE
added missing variables

### PR DESCRIPTION
**Pull request by ninja342**

### CODE REVIEW

**Comment by nperryEG** [comment]
@nbperry

**Comment by armanio123** [comment]
I'll wait until @nperryEG or any other owner (@blove , @welkie , @ogawa0071) approval before getting this merged.

**Comment by welkie** [comment]
I was going to review this once @ninja342 responded to @nperryEG with the docs link. That's important for this. Can you link us to where you found this?

**Comment by ninja342** [comment]
https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/global#GetFilesRequest

**Review by nbperry — APPROVED** [review]
Looks good.

**Pull request merged**
