### PR TITLE
Nodejs Process interface add binding method

### PR DESCRIPTION
**Pull request by wind-hx**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by islishude — CHANGES_REQUESTED** [review]
Please add test for it.

**Comment by isLishude** [comment]
image

```js
function binding(module) {
  module = String(module);
  // Deprecated specific process.binding() modules, but not all, allow
  // selective fallback to internalBinding for the deprecated ones.
  if (internalBindingWhitelistHas(module)) {
    return internalBinding(module);
  }
  let mod = bindingObj[module];
  if (typeof mod !== "object") {
    mod = bindingObj[module] = getBinding(module);
    moduleLoadList.push(`Binding ${module}`);
  }
  return mod;
}
```

**Comment by hvaexlove** [comment]
> image
> 
> ```js
> function binding(module) {
>   module = String(module);
>   // Deprecated specific process.binding() modules, but not all, allow
>   // selective fallback to internalBinding for the deprecated ones.
>   if (internalBindingWhitelistHas(module)) {
>     return internalBinding(module);
>   }
>   let mod = bindingObj[module];
>   if (typeof mod !== "object") {
>     mod = bindingObj[module] = getBinding(module);
>     moduleLoadList.push(`Binding ${module}`);
>   }
>   return mod;
> }
> ```

Because the project core using C++ extension module, the upper service wants to use typescript for encapsulation, So we use Process.binding function.

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Github bugged out, please see comment.

**Comment by hvaexlove** [comment]
> This looks like an internal method, it's not in the official API, I would be hesitant to add it to the typings.

If the binding function is added to typescript, the bridge between typescript and c++ module is established, so hopefully it can be added, thank.

**Comment by SimonSchick** [comment]
Again, it's not in the public API, can you please provide documentation?

**Comment by hvaexlove** [comment]
> Again, it's not in the public API, can you please provide documentation?


It's not in the public API,I can't provide a detailed documentation, but I can give a comment about the binding function.

image

https://stackoverflow.com/questions/20382396/what-are-node-js-bindings
https://stackoverflow.com/questions/24042861/nodejs-what-does-process-binding-mean

**Comment by Flarna** [comment]
What is your usecase for this internal API? Native addons are usually loaded like other modules using `require()` therefore I assume you have to do something really special here.
The issue with adding internals to type definition is that they may break at any time and users of typings usually assume that APIs typed are actually correct to use - which is not really the case for internals like `process.binding()`.

**Pull request closed without merging**
