### PR TITLE
[@types/luxon] Fix args type for Interval#toDuration

### PR DESCRIPTION
**Pull request by pf-siedler**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#instance-method-toDuration
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

According to [luxon reference](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#instance-method-toDuration), argument `unit` for function `Interval#toDuration` is optional.

### CODE REVIEW

**Comment by pietrovismara** [comment]
Hi @pf-siedler, why bump the version to `1.11`? 

[This PR doesn't seem to be related to it](https://github.com/moment/luxon/blob/master/changelog.md#1110).

**Comment by pf-siedler** [comment]
Just because version number of luxon is updated, but I not have to change index.d.ts version number. ?

**Comment by pietrovismara** [comment]
Nevermind, it seems all changes in 1.11 are bug fixes that don't require changes to the typings, so we can safely bump the version up.

**Review by pietrovismara — APPROVED** [review]

**Comment by pf-siedler** [comment]
@pietrovismara Thank you.
I revert latest commit, and set version number 1.11 .

**Pull request merged**
