### PR TITLE
chore (puppeteer): remove redundant types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

feel like there might be a reason this hasn't been done yet, similar to why node-fetch is holding on. if anyone's aware of one, do let me know and ill throw this away.

types shipped since 7.0.4:
https://unpkg.com/browse/puppeteer@7.0.4/lib/types.d.ts
https://unpkg.com/browse/puppeteer-core@7.0.4/lib/types.d.ts

some of these dependent packages are super old, so i've made them use `@types/puppeteer` as a dependency.

some don't use puppeteer in the source package but expect the type, so i've moved them to use puppeteer-core instead.

some use an older puppeteer in the source package but one which has types, so i've made those use the same dependency here.

### CODE REVIEW

**Comment by 43081j** [comment]
ok cool i see why we might not do this!

the puppeteer types have private identifiers in them. that means we'd have to update dependent packages to target ES2015+.

if we do that, does it mean anyone targeting lower can't use them? or is it scoped within DT and doesn't affect consumers?

**Comment by peterblazejewicz** [comment]
I'd submit `@types/puppeteer` to allowed packages (and `puppeteer`), so one can lock down older packages to current types, skipping those problems.

**Comment by 43081j** [comment]
i already did.

some of the packages here i've given the DT package as a dependency.

the ones i gave `puppeteer` itself was because they depend directly on it in the source package (sometimes even the later versions).

i could for now just put them all to `@types/puppeteer` for sake of avoiding having to bump minimum versions etc.

**Comment by peterblazejewicz** [comment]
> i could for now just put them all to @types/puppeteer for sake of avoiding having to bump minimum versions etc.

Yes, please

**Comment by 43081j** [comment]
done and tests pass other than that pesky aws-synthetics-puppeteer package...

even just moving it to use the DT package as a dependency causes all sorts of memory exceptions. no clue whats going on there

**Review by Tantalon — APPROVED** [review]
LGTM for aws-synthetics-puppeteer

**Review by peterblazejewicz — APPROVED** [review]

**Comment by 43081j** [comment]
this is a fun one.

it seems when typescript tries to parse the aws-sdk (which is a dependency of aws-synthetics-puppeteer), it eventually runs out of memory.

i've attached a debugger and can see already i've reached 1GB of memory running the tests. most of it seems to be allocated to `NodeObject` instances.

could this be some (maybe worrying) problem with TS4.9 parsing the aws-sdk?

**Comment by peterblazejewicz** [comment]
'run-all' passes when run locally. It peaked 6GB memory allocation on my local machine though.

**Comment by 43081j** [comment]
impressive huh 😂 

thank you for checking that though, good to know they pass.

sanders did actually come across it a couple of weeks ago i think but didn't get far with it. i think it comes down to the aws-sdk just being very large (especially the type definitions).

each instance of typescript populates a cache, which means 1GB per version.

**Comment by Tantalon** [comment]
I've submitted #63033 to remove aws-sdk from aws-synthetics-puppeteer. It provided little value, as it's only used on two function parameters, and it's breaking CI for three pull requests.

**Comment by 43081j** [comment]
@Tantalon that's great, thanks a lot for taking a look. 

I couldn't find much documentation on those methods so wasn't sure if we could drop it or not. Your solution looks good to me I think. 

From what I hear, there's a newer version of the SDK which isn't monolithic too. So probably good to get off this one anyway.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jest-environment-puppeteer ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jest-environment-puppeteer@latest/))
was missing the following properties:
1. setup
1. teardown
## pa11y ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pa11y@latest/))
was missing the following properties:
1. defaults
1. allowedStandards
1. defaults
1. allowedStandards
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 07204ea6d01f90b2163084bd59ae216aa0339686
</p>

**Comment by 43081j** [comment]
Build passes! thanks a lot @Tantalon for fixing that.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by 43081j** [comment]
Ready to merge

Those packages whose maintainers didn't show up all use the old types package so I'm fairly confident they will be fine.

**Pull request merged**
