### PR TITLE
Update Iterable interfaces for upstream

### PR DESCRIPTION
**Pull request by falsandtru**
Updates for https://github.com/Microsoft/TypeScript/pull/19763

### CODE REVIEW

**Comment by Flarna** [comment]
Isn't this a breaking change? How is it planned to sync the changes in typescript with the changes here?
Are all users of node typings then forced to switch to latest typescript?

**Comment by RyanCavanaugh** [comment]
@falsandtru Please fix the failures indicated in the Travis CI log.

**Comment by falsandtru** [comment]
Need to switch as follows:

- `IterableIterator` -> `Iterator`
- `Iterator` for polyfill without `Symbol.iterator` -> `NonIterableIterator`

**Comment by falsandtru** [comment]
@RyanCavanaugh That log says `The job exceeded the maximum time limit for jobs, and has been terminated.`. This is not a type error. How can I fit it?

**Comment by falsandtru** [comment]
Almost the changes of node definitions have failed: https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/node

Me too.

**Comment by minestarks** [comment]
Yes Node tends to do this. Restarted Travis

**Comment by Flarna** [comment]
I don't think that this should be merged now as to my understanding it depends on https://github.com/Microsoft/TypeScript/pull/19763 which is still open.
Besides that it's a breaking change which would avoid that this typings can be used with typescript versions having https://github.com/Microsoft/TypeScript/pull/19763 not included.

**Comment by minestarks** [comment]
@Flarna thanks for pointing this out, I hadn't reviewed the code yet.

@falsandtru Thanks for the changes, but I can only accept PRs that work with existing versions of TypeScript.

**Comment by minestarks** [comment]
Closing as this PR can't be taken until changes in TypeScript have been made. If in the future the TypeScript side change is merged, please feel free to open a new PR. Thanks!

**Pull request closed without merging**
