### PR TITLE
update mssql definitions to 4.0.1

### PR DESCRIPTION
**Pull request by pkeuter**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/patriksimek/node-mssql#3x-to-4x-changes
- [x] Increase the version number in the header if appropriate.
~- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.~

### CODE REVIEW

**Comment by pkeuter** [comment]
@andy-ms any chance you can check (and merge) this?

**Comment by delight-by** [comment]
Great job! Just started using it. Noticed one quirk - ConnectionPool should also accept connection string in constructor.

**Comment by pkeuter** [comment]
@delight-by I have just added the connection-string constructor. Since this PR is not merged to master yet, it is added in this PR.

**Comment by mrrichar** [comment]
👍

**Comment by delight-by** [comment]
Sorry guys, I've just noticed another quirk:
- Templated query() method is a method of ConnectionPool, not Request. The same goes to templated batch() which is missing right now.

**Comment by pkeuter** [comment]
@delight-by You are right. I've moved this and created another PR #16260

**Pull request merged**
