### PR TITLE
Update snekfetch to 4.0.0 release

### PR DESCRIPTION
**Pull request by DevYukine**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ The end user interface didn't change so much  that this would be needed ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://snekfetch.js.org/?api=snekfetch
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Dev-Yukine** [comment]
agreed to what @ShayBox said, i though after our last PR we are also authors now since we mostly chagned the typings to be up-to-date

**Comment by ShayBox** [comment]
In 2 weeks when a manual reviewer reads this, please remove the original author. he doesn't use github anymore, and this is going to be getting more PRs in the future and would prefer not to wait 2 weeks.

**Review by ShayBox — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh how often are authors refreshed?

**Comment by DanielRosenwasser** [comment]
(Thanks for the patience!)

**Comment by Dev-Yukine** [comment]
@DanielRosenwasser No Problem :) i would still ask you if you could add us to the reviewers (me and @ShayBox) since we want to keep the Typings up to date and not always wait 2 weeks for that.

**Pull request merged**
