### PR TITLE
betterr-queue initial PR

### PR DESCRIPTION
**Pull request by maozedong**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by maozedong** [comment]
A little help needed with this PR. 
It's required to use 'strictFunctionTypes' according to PR rules, but I can't figure out how to type 'process' method of Queue options correctly. It's first argument should be `T | T[]`, but that's not permitted by 'strictFunctionTypes' rule
'process' method declaration - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27305/files#diff-75717454ea2b2452a0fb30e36fe49691R42

**Review by plantain-00 — APPROVED** [review]

**Comment by andy-ms** [comment]
@maozedong 
I would recommend not explicitly providing a type to callbacks. So instead of writing `process(task: TestTask, cb) { ... }`, just write `process(task, cb) { ... }`. Then when you provide a type to `process`, `task` will pick up on that and get the correct contexual type, which could be `TestTask | TestTask[]` if you fix the type of `ProcessFunction`.

**Comment by maozedong** [comment]
@andy-ms 
Unfortunately I didn't manage to apply you recommendation. Even if I do not specify type of `task` argument TypeScript complains that types are incompatible. 

```
// index.d.ts
type ProcessFunction<T, K> = (task: T | T[], cb: ProcessFunctionCb<K>) => void;
```

```
// better-queue-tests.ts
new Queue<TestTask>((task, cb) => {
    const id = task.taskId; // got error here
});
```
Error
```
[ts]
Property 'taskId' does not exist on type 'TestTask | TestTask[]'.
  Property 'taskId' does not exist on type 'TestTask[]'.
```

I'm ok to go with `task:any` type. It'll be better than nothing
If everything else is ok, than this PR is ready to merge

**Comment by andy-ms** [comment]
But that error is correct -- if `task` is `TestTask | TestTask[]`, you can't treat it as if it definitely has a `taskId` property, since an array would not have that property.

**Comment by rbuckton** [comment]
@maozedong is this PR ready to go, or do you still need to make changes based on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27305#issuecomment-408137107?

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
