### PR TITLE
Add readable stream type body to request object

### PR DESCRIPTION
**Pull request by kkamboj-aka**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by bmatthew — APPROVED** [review]

**Comment by bmatthew** [comment]
Just noticed the build failure; once it's fixed if my approval disappears I can re-approve 😃

**Comment by kkamboj-aka** [comment]
> Just noticed the build failure; once it's fixed if my approval disappears I can re-approve 😃
@bmatthew 
I got a couple of warnings as I am creating an empty interface that extends from another interface. I am not sure how to make this work.
Intention behind this change: I need to use ReadableStream inside EW namespace. I can't use it directly nor I can import streams module inside EW namespace. So instead I did the following:
1. I moved ReadableStream interface(& its dependencies) to EW namespace as ReadableStreamEW.
2. Inside streams module, I am creating ReadableStream interface that extends the ReadableStreamEW. 

Any suggestions?

**Review by bmatthew — APPROVED** [review]
Approved -- we discussed the tslint changes offline to make the linter stop complaining about things that don't matter.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by kkamboj-aka** [comment]
Ready to merge

**Pull request merged**
