### PR TITLE
[lodash] fix _.get return type cannot refer to correct type and default type in nested object with optional fields

### PR DESCRIPTION
**Pull request by ncnthien**
### Todos:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [The sample code](https://replit.com/@ThienNguyen10/AlarmedTemptingGenres#index.ts)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### Problem:
Imagine when we use _.get to retrieve the deep value in an object, which contains many nested optional fields, then the type returned should be the type of value followed by the path or the type of the default value.
image

And when we pass the generic path to the function, we cannot retrieve the property if the higher level of that property is optional. In this case, `bar` is optional so TS cannot recognize `baz` property.
image

### Solution:
We could wrap the middle-level nested fields with NonNullable, which could remove the `null | undefined`, and then TS could read the type needed, NonNullable will not affect the type of optional value in this case, because we only care about the final result followed by the path, and the default value (Please check the changes for more details).

Please let me know if I missed any cases, thank you guys!

### CODE REVIEW

**Review by aj-r — APPROVED** [review]
Thanks! Should the overloads without default values be fixed, too, or do they already work somehow?

**Comment by ncnthien** [comment]
> Thanks! Should the overloads without default values be fixed, too, or do they already work somehow?

Oh how could I miss that? Will update soon

**Comment by ncnthien** [comment]
just updated, I've added some test cases to ensure that the overloads with nested **required** fields object won't be overridden by the ones with **nested** optional fields object.

**Review by aj-r — APPROVED** [review]
Looks great!

**Comment by TienThinh-fe** [comment]
I am facing the same issue. Hope this one will be merged soon. 
Thanks a lot

**Comment by lduchuy2002** [comment]
Looks great

**Review by jakebailey — APPROVED** [review]

**Comment by ncnthien** [comment]
Ready to merge

**Pull request merged**
