### PR TITLE
Update Titanium Mobile types to 7.1.0

### PR DESCRIPTION
**Pull request by janvennemann**
This updates the types for Titanium SDK to version 7.1.0. The typings are generated from YAML documentation files at https://github.com/appcelerator/titanium_mobile/tree/master/apidoc/Titanium. The script that generates these typings can be found over at https://github.com/appcelerator/titanium_mobile/pull/9936.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.appcelerator.com/platform/latest/#!/api/Titanium
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
@janvennemann Looking at the header I noticed that
1. The previous version was for Titanium Mobile 3.5 but the new one is for Titanium 7.1. Are these the same package?
2. You inadvertently overwrote cyounkins in the Definitions By field.

**Comment by janvennemann** [comment]
@sandersn Yes, they are the same package. Titanium (SDK), Titanium Mobile or Axway Titanium SDK are all common names for the same product. It wasn't updated for quite some time, that's the reason for the huge version bump.

Also i wasn't quite sure wether to keep @cyounkins as a maintainer or not, since this is a total rewrite of the old definition and there is nothing left of the old code.

**Comment by sandersn** [comment]
Is it worthwhile [to keep the old types around in a sub directory](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version)? I don't know if people will still want to keep the 3.x line up-to-date.

Besides those questions, the *structure* of the package looks OK. I haven't looked at the contents in any detail.

**Comment by janvennemann** [comment]
@sandersn Titanium 3.x is not supported anymore and won't receive any further updates so i don't think the old types need to be kept around.

**Pull request merged**
