### PR TITLE
[react-router-redux] Fix compat issues with latest dependencies

### PR DESCRIPTION
**Pull request by eps1lon**
Fixes

```
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react-router-redux/react-router-redux-tests.tsx:30:67
ERROR: 30:67  expect  TypeScript@5.4 compile error: 
Type 'Reducer<RouterState>' is not assignable to type 'RouterState'.
ERROR: 53:16  expect  TypeScript@5.4 compile error: 
Argument of type 'RouterAction' is not assignable to parameter of type 'UnknownAction'.
  Index signature for type 'string' is missing in type 'RouterAction'.
```
-- https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/7091732557/job/19301508685?pr=67430
(make sure you re-install node_modules when testing locally)

Unblocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67430 and all other React related PRs.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-router-redux ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-router-redux@latest/))
was missing the following properties:
1. getLocation
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bcb463054946ffcc93540c04e5f32cad8b8f5460
</p>

**Comment by eps1lon** [comment]
No longer required.

**Comment by eps1lon** [comment]
Actually required. Just looked like it was fixed because CI didn't work for a while (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67971)

**Comment by eps1lon** [comment]
GH wouldn't let me reopen: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67997

**Pull request closed without merging**
