### PR TITLE
added definition for textbox

### PR DESCRIPTION
**Pull request by yoxdev**
Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [ X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ X] Provide a URL to documentation or source code which provides context for the suggested changes: http://fabricjs.com/docs/fabric.Textbox.html
- [X ] Increase the version number in the header if appropriate.
- [X ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by yoxdev** [comment]
Added definition for textboxes to fabric js type definition

**Comment by BradleyHill** [comment]
@yoxdev You look into the fail at all. I just tried adding the Object.skewX/Y and it failed in linting. Reverted all changes and it still fails in same place. Feels like something amiss with project.

**Comment by BradleyHill** [comment]
@yoxdev Seems like latest `dtslint` or one of its dependencies introduced (or uncovered) an error. Anyway, i think i have a fix for the test code the linter was flagging. In this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28278
If mine gets merged, i think yours will go green.

**Comment by yoxdev** [comment]
Hello, i fixed the tests with my commit, 'this' was use inappropriately in a couple tests so i changed those to comply.

Cheers

________________________________

**Pull request closed without merging**
