### PR TITLE
Add download-package-tarball

### PR DESCRIPTION
**Pull request by LinqLover**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by LinqLover** [comment]
> @LinqLover The CI build failed! Please [review the logs for more information](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3dd3484ed0d5648c7361dc44add4295bc221b72b/checks?check_suite_id=4205250598).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!
> 
> **Note: builds which are failing do not end up on the list of PRs for the DT maintainers to review.**

The CI failed for the same reason as described here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56874#issuecomment-955046643

```
Error in download-package-tarball
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/download-package-tarball: Contains the word 'download', which is banned by npm.
    at assertPathIsNotBanned (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:232:15)
    at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:136:13
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

What shall I do, open another PR against tslint? :)

**Comment by LinqLover** [comment]
> 🔔 @LinqLover — you're the only owner, but it would still be good if you find someone to [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56875/files) in the next few days, otherwise a maintainer will look at it. (And if you do find someone, maybe even recruit them to be a second owner to make future changes easier...)

@kesla Are you interested? :)

**Comment by LinqLover** [comment]
@peterblazejewicz Could you maybe help with this one too? It also contains "download" :)

**Comment by peterblazejewicz** [comment]
I've updated the microsoft/dtslint#350
(it works locally, one needs to wait to get those merged), 
thx!

**Comment by LinqLover** [comment]
No, this PR should not be canceled. Please refer to the issue in https://github.com/microsoft/dtslint/pull/350#issuecomment-999811954.

**Comment by LinqLover** [comment]
No, this PR should not be canceled. Please refer to the issue in https://github.com/microsoft/dtslint/pull/350#issuecomment-999811954.

**Comment by peterblazejewicz** [comment]
@LinqLover eventually change to draft

**Pull request closed without merging**
