### PR TITLE
Mongo db updates

### PR DESCRIPTION
**Pull request by Think7**
Please let me know if i have done anything incorrectly. I am quite new to Githubbing...

### CODE REVIEW

**Comment by Think7** [comment]
Looks like the integration failed due to not finding Node and ES6 types. Not sure how to fix this as all works on my end. If someone could provide instructions i'm happy to make the changes.

**Comment by vvakame** [comment]
try with .tscparams. like this.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/be165111df0ef72108fc30bdeddc138010c65388/wu/wu.d.ts.tscparams

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by Think7** [comment]
Hello,

I've moved over entirely to Typings: https://github.com/typings/typings. The def can be found there and is maintained by a few others.

**Pull request closed without merging**
