### PR TITLE
[@types/three] Type refinements for GLTFExporter and DRACOExporter

### PR DESCRIPTION
**Pull request by epreston**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test three`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
   - Documentation Updates
      - https://github.com/mrdoob/three.js/pull/25348
      - https://github.com/mrdoob/three.js/pull/25349
   - Source code for reference
      - https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/GLTFExporter.js
      - https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/DRACOExporter.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. BoxBufferGeometry
1. CapsuleBufferGeometry
1. CircleBufferGeometry
1. ConeBufferGeometry
1. CylinderBufferGeometry

<details>
<summary>as well as these 19 other properties...</summary>
<p>DataUtils, DodecahedronBufferGeometry, ExtrudeBufferGeometry, IcosahedronBufferGeometry, ImmediateRenderObject, LatheBufferGeometry, LinearSRGBColorSpace, NoColorSpace, OctahedronBufferGeometry, PlaneBufferGeometry, PolyhedronBufferGeometry, RingBufferGeometry, SRGBColorSpace, ShapeBufferGeometry, SphereBufferGeometry, TetrahedronBufferGeometry, TorusBufferGeometry, TorusKnotBufferGeometry, TubeBufferGeometry</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 17c7862911138a9add96e58c5c1323140d3a699a
</p>

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Can you open this PR in three-TS-types please?

**Comment by epreston** [comment]
Sure, I can raise it in that repository as well.

**Comment by joshuaellis** [comment]
> Sure, I can raise it in that repository as well. Feel free to approve this change for this repository.

As i've said on the other PR, this isn't how we work with this type library and it will not be approved.

**Comment by epreston** [comment]
Oh ?  I'm following the instructions in the readme.  

I hope to contribute.  Few of the types are correct and the tests are bogus.  I'd like to be able to rely on these types.

**Comment by epreston** [comment]
Please stop blocking commits to this type library.  Most of the types and tests need updating.

**Comment by Methuselah96** [comment]
I'm not sure what you mean by "blocking commits." We welcome contributions, you just need to do so at [three-ts-types](https://github.com/three-types/three-ts-types) where the README and contribution guide explain how to contribute.

**Comment by epreston** [comment]
You guys don't maintain these properly over there and I take credit for my own work, thank you.

**Comment by Methuselah96** [comment]
I think we're being reasonable (cross-referencing https://github.com/three-types/three-ts-types/issues/326 for anyone reading this without context) and I don't see how we're not letting you take credit for your own work in comparison to how open-source usually works.

**Comment by epreston** [comment]
I'm not interested in dealing with 10 different projects to correct issues with types.  

You have setup a "sub project" for people feel this project is too intimidating, but you force all changes through it.  Your tests don't test the types, the tests are based on old versions of the library forcing the types to always be wrong.  Nearly every file has an issue.  You yourself described how you "game" the build tools here so nothing is checked with this tooling.

I'm half way through the process of correcting this and following the process laid out by this project.  Goodday.

**Comment by Methuselah96** [comment]
> I'm not interested in dealing with 10 different projects to correct issues with types.

This and and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64117 are your only contributions to DefinitelyTyped so far, and we believe that most contributors to three-ts-types have never contributed to DefinitelyTyped.

> You have setup a "sub project" for people feel this project is too intimidating, but you force all changes through it. Your tests don't test the types, the tests are based on old versions of the library forcing the types to always be wrong. Nearly every file has an issue. 

We welcome contributions to improve the types and tests. We are against dropping all the current tests (as you suggested in https://github.com/three-types/three-ts-types/issues/326) just because they don't test things the way you would like, but we support you improving the tests to match that style if that's what you would like to do.

Part of open-source is being able to work together with others. It seems like you're intent on doing things the way you think is best, regardless of what others think. Feel free to do so, but as the current maintainers of the types, we're going to do what we think is best for everyone.

> You yourself described how you "game" the build tools here so nothing is checked with this tooling.

I believe I described [here](https://github.com/three-types/three-ts-types/issues/326#issuecomment-1407417963) how we type-check all the files, so I'm not sure how you came to the conclusion that "nothing is checked with this tooling."

> I'm half way through the process of correcting this and following the process laid out by this project. Goodday.

You're welcome to start your own endeavor at fixing the three.js types/tests, but we do not plan on accepting contributions that are made outside of the three-ts-types process.

**Comment by epreston** [comment]
I am not interested in dealing with you or your project.  

I want to correct types on this project, one similar, or publish the ones I've been using.

**Comment by Methuselah96** [comment]
Understood, as the current definition owners on this project, we do not plan to approve contributions made directly to DefinitelyTyped.

**Comment by epreston** [comment]
You may find that statement limits your future contributions more than mine.

**Comment by Methuselah96** [comment]
If my decision to expect contributions to be made through three-ts-types is overruled, I plan to abide by that overruling decision, so it seems unlikely that my current stance would limit my future contributions.

**Comment by epreston** [comment]
If you put more effort into types than waving around what little responsibility you've been given, you'd have the library half updated.

**Comment by Methuselah96** [comment]
We clearly got off on the wrong foot.

I understand your frustration at it being unclear that we expect contributions to be made to three-ts-types. We link to it in `index.d.ts`. Ideally we would be able to link to it from npm, but unfortunately I don't think there's a way for us to modify or augment the `README.md` or `package.json` that gets published to allow us to do that. We would love to improve the situation since this is a common issue. It seems like we would need to petition the DefinitelyTyped maintainers and contribute updates to the tooling that would allow for this situation, which I don't currently have the time to do.

We would love to fix the other issues you've mentioned, but we lack the time to do a better job. If we had more time and contributors, we could maintain much higher-quality types. We also add any long-term contributors to the maintaining team, but since this is open-source, there are not many long-term contributors.

If you have the time and can keep the types up-to-date at a higher quality then what we're currently doing with the support of the community, I'd personally be fine with letting you modify the process however you like. I hope you understand that you need to build trust that you are a long-term contributor and that you can work well with others in the community before I would feel comfortable depending on you to put in the work for an alternative process to work. (Not to mention that it's not only up to me.)

Until then, we have a process that has been working well for us and the community. We welcome improvements to that process. Given our current time constraints, this is the best we know how to do. We try to all pull in the same direction, and we would love it if you would join us.

I wish I had time to do actual maintenance work on the the types, but I don't. My main role is helping to settle any controversial issues or giving a second opinion if there's a question on how to type something. When I respond to these types of conversations, it's putting in time that I would normally not spend on the three types in order to try to support the community.

I hope you will still consider contributing to the three types and joining the community despite these frustrating encounters. If not, I wish you all the best.

**Pull request closed without merging**
