### PR TITLE
Revert fix for @types/calendar for monthDays

### PR DESCRIPTION
**Pull request by quentincaffeino**
@ffflorian Ok, here's the revert. Hope I got it right) Then I should create new pr with the same fix?

### CODE REVIEW

**Comment by ffflorian** [comment]
Looks good so far, but you forgot to update the test :)

**Comment by quentincaffeino** [comment]
Huh, I've already removed this test, might messed it up while merging.

**Comment by ffflorian** [comment]
While testing the library a bit more I noticed that I totally forgot that the `dayFormatter` and `weekFormatter` change the return type of `monthDates`. Please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51166.

**Comment by quentincaffeino** [comment]
That's neat! Thanks for your help)

**Comment by quentincaffeino** [comment]
I'm going to close this pr in favour of #51166

**Pull request closed without merging**
