### PR TITLE
add max javascript js/jsui types @types/maxmsp

### PR DESCRIPTION
**Pull request by twhiston**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by gabritto** [comment]
Before I can approve, I'd like to clarify what the project is behind these typings and the relationship to `max-api`. I couldn't really understand what that project is supposed to be from the link provided (http://max-javascript-reference.tim-schenk.de/).

**Comment by twhiston** [comment]
Sure, happy to clarify. `max-api` are the types for max msp's new nodejs implementation, which is used inside the [node.script] object in max. The types here are for the older javascript objects [js] and [jsui]. There is further documentation describing them here: https://docs.cycling74.com/max8/vignettes/javascript_usage_topic If you think that would be a better link I'd be happy to change it.
They both expose completely different functionality, in this case a lot more low level access to max's own APIs for making patcher objects and manipulating Jitter Matrix data. This and `max-api` are not cross compatible because they both have distinct max object implementations wherein the types described in both cases are baked into the implementation of the max object.

**Comment by twhiston** [comment]
Just for additional context regarding the type naming, Florian Demmer of Cycling 74, who maintains the `max-api` types, agreed in this discussion that this package being named `maxmsp` was acceptable to them: https://github.com/ErnstHot/TypeScript-for-Max/issues/26#issuecomment-1518588070

**Comment by gabritto** [comment]
> Sure, happy to clarify. `max-api` are the types for max msp's new nodejs implementation, which is used inside the [node.script] object in max. The types here are for the older javascript objects [js] and [jsui]. There is further documentation describing them here: https://docs.cycling74.com/max8/vignettes/javascript_usage_topic If you think that would be a better link I'd be happy to change it. They both expose completely different functionality, in this case a lot more low level access to max's own APIs for making patcher objects and manipulating Jitter Matrix data. This and `max-api` are not cross compatible because they both have distinct max objects wherein the types described in both packages are baked into the implementation of the object itself and not provided as libraries you can optionally include.

I think it would be slightly better to update the project link on the DT header, yeah. Thanks for clarifying. I'll approve this once you change the project link.

**Comment by twhiston** [comment]
I've updated the project link, but still included the API link further down, I hope this is ok, if not please let me know and I will remove. Thanks for your time supporting me getting this merged!

**Review by gabritto — APPROVED** [review]

**Comment by twhiston** [comment]
Ready to merge

**Pull request merged**
