### PR TITLE
[react-bootstrap-table-next] Update SelectRowProps interface small change to bgColor

### PR DESCRIPTION
**Pull request by chris-hockley-dynium**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowbgcolor-string-function>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I am trying to follow all the steps but this is my first contribution to DefinitelyTyped.

### CODE REVIEW

**Comment by gosticks** [comment]
Hey @chris-hockley-dynium,
sorry I was berried with work the past couple of weeks. Thanks for your fix looks great 👍 . I would add a test to the bgColor so we have it covered.

**Review by gosticks — APPROVED** [review]
Thanks for the fix!

**Comment by chris-hockley-dynium** [comment]
> Hey @chris-hockley-dynium,
> sorry I was berried with work the past couple of weeks. Thanks for your fix looks great 👍 . I would add a test to the bgColor so we have it covered.

Thanks. I will have a look at the tests.

Ready to merge

**Comment by chris-hockley-dynium** [comment]
Ready to merge

**Pull request merged**
