### PR TITLE
[@types/aws-lambda] APIGatewayEventRequestContext's connectedAt field should be optional

### PR DESCRIPTION
**Pull request by skyzenr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This PR is a fix for the already closed PR: #32855 
The `connectedAt` field must be optional.

### CODE REVIEW

**Comment by simonbuchan** [comment]
Do you know under what circumstances this will be undefined? I'm not sure why API Gateway would ever not know this?

**Comment by skyzenr** [comment]
> Do you know under what circumstances this will be undefined? I'm not sure why API Gateway would ever not know this?

Hi @simonbuchan ! The events that come from an API Gateway without creating a WebSocket API (REST API) do not contain the `connectAt` property. According to the (doc)(https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html) there is no evidence that this field is required (or better, it is set only when using WebSocket). Hence I wonder why some fields e.g. connectionId, eventType are optional whereas the connectAt field is not..

**Review by simonbuchan — APPROVED** [review]
Seems legit. Probably would make more sense to break this event apart into events with and without the websocket properties, but we have enough handler types already....

**Comment by skyzenr** [comment]
Well, I think that we could consider to split them. Does it make sense to have something like a `APIGatewayRESTApiEventRequestContext `and a `APIGatewayWebSocketEventRequestContext` ? :) Or do you think it is better to keep properties optional?

**Comment by simonbuchan** [comment]
You can take a stab at it, but it gets a bit messier, as each `FooEvent` should have a `FooHandler` (and if there is a `FooResult`, a `FooCallback`), plus tests.

**Comment by skyzenr** [comment]
But it would make sense.

**Comment by simonbuchan** [comment]
Yep. Just make sure you try to avoid breaking back-compat too much, probably easiest to leave the current handler and add an alias `export type APIGatewayEventRequestContext = 
APIGatewayRESTApiEventRequestContext | 
APIGatewayWebSocketEventRequestContext`, and likewise for the event itself. Does that make sense?

**Comment by skyzenr** [comment]
Yes, that is what I meant!

**Pull request merged**
