### PR TITLE
remove no-longer-existing `LogLuvEncoding` constant

### PR DESCRIPTION
**Pull request by trusktr**
three 0.139 no longer has this

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mrdoob/three.js/blob/r139/src/constants.js#L140-L141
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by trusktr** [comment]
@joshuaellis  @peterblazejewicz @Methuselah96

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. AxisHelper
1. BinaryTextureLoader
1. BoundingBoxHelper
1. CanvasRenderer
1. ColorManagement

<details>
<summary>as well as these 29 other properties...</summary>
<p>DynamicBufferAttribute, EdgesHelper, FaceColors, Font, FontLoader, ImmediateRenderObject, JSONLoader, LensFlare, LinearSRGBColorSpace, Math, MeshFaceMaterial, MultiMaterial, NoColorSpace, NoColors, ParametricGeometry, Particle, ParticleBasicMaterial, ParticleSystem, ParticleSystemMaterial, PointCloud, PointCloudMaterial, SRGBColorSpace, SceneUtils, TextGeometry, Vertex, VertexColors, WebGLRenderTargetCube, WireframeHelper, XHRLoader</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0c5091347eb522b3fa9955cf7fcaafc800e935f0
</p>

**Comment by Methuselah96** [comment]
@trusktr Do you mind moving this pull request over to [three-ts-types](https://github.com/three-types/three-ts-types)? That's where we maintain the three.js types.

**Review by joshuaellis — CHANGES_REQUESTED** [review]
see comment above

**Comment by trusktr** [comment]
Moved to https://github.com/three-types/three-ts-types/pull/209

**Pull request closed without merging**
