### PR TITLE
Update type definitions for Redux

### PR DESCRIPTION
**Pull request by aikoven**
Multiple updates and refinement for Redux typings.
Introduces stronger types employing generics as well as Redux API updates.

### CODE REVIEW

**Comment by tkqubo** [comment]
`react-redux/react-redux.d.ts` looks :+1:

**Comment by wbuchwalter** [comment]
What about PR #6629 ?

**Comment by aikoven** [comment]
@wbuchwalter I left a comment there, please see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6629#issuecomment-178370641

**Comment by wbuchwalter** [comment]
:+1:  We should go ahead with that one, the other PR has been stuck in limbo for too long.

**Comment by xogeny** [comment]
I took a quick glance and things looked fine for me.  I didn't actually check it against my existing code...but I didn't see any obvious problems.  I hope this one doesn't get stuck in limbo like #6629.  I'll add a comment to that pull request directing people here.

**Comment by mhegazy** [comment]
Can you please refresh this PR and address merge conflicts.

**Comment by wbuchwalter** [comment]
@mhegazy  We should close this PR.
Typings have been migrated to Redux's repo directly and are being maintained there: .https://github.com/reactjs/redux/blob/master/index.d.ts

**Comment by wbuchwalter** [comment]
Just saw your and @basarat comments on #8593. You seem to be proposing to maintain the typings at two different places at the same time. I understand why, but can we really expect contributors to do it automatically?
Regardless, we should close all the open PRs for Redux anyway and just copy paste the existing `.d.ts` from Redux's repo since updates are missing here, and some PRs were already refuser/modified there.

**Comment by isman-usoh** [comment]
`react-router-redux/react-router-redux.d.ts` :+1:

**Comment by mc-petry** [comment]
`redux-devtools/redux-devtools.d.ts` :+1:

**Comment by aikoven** [comment]
@wbuchwalter is right, closing this.

**Pull request closed without merging**
