### PR TITLE
[@types/serve-static] Remove dependency on `@types/mime`

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test serve-static`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by jakebailey** [comment]
Why?

**Comment by esetnik** [comment]
I think the correct fix is in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a219ae4154eb078252637b873edd07aa6c1be98a since mime v4 ships with it's own types that may end up being incompatible with `@types/serve-static`.

**Comment by stu43005** [comment]
I think the most accurate solution would be to change the dependency to `@types/send`.

Because `serve-static` actually depends on `send` package instead of `mime`.

see: https://github.com/expressjs/serve-static/blob/9b5a12a76f4d70530d2d2a8c7742e9158ed3c0a4/index.js#L29

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/serve-static/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d4c286738e15c79670ad64c00606c4cf3bb6b6fa
</p>

**Comment by AviVahl** [comment]
> Why?

When #69213 landed, half the web broke. That's why. :)
`@types/express` use `@types/serve-static`. `@types/serve-static` used `"@types/mime": "*"`, which broke once `@types/mime@4` released.

Like @stu43005 wrote, `serve-static` actually uses `send`, which uses an older mime package version (and its relevant types).

refs:
https://github.com/firebase/firebase-admin-node/issues/2512
https://github.com/googleapis/nodejs-storage/issues/2434
https://github.com/fastify/send/issues/60

**Comment by jakebailey** [comment]
Then we should revert #69213 and delete it. `@types/mime` was far too large to publish a shim for.

**Comment by jakebailey** [comment]
No, nevermind, the shim package is fine as it only applied to mime v4. But we should fix this package.

**Comment by jakebailey** [comment]
I'm not sure why moving it to `send` helps, though; that package is still using `@types/mime@*`.

**Comment by AviVahl** [comment]
TBH, it looks like the change here is the correct way to go.
`mime@4` _does_ have built-in types, so it should probably follow the usual procedure of deprecating a `@types` packages.

It's just that packages that depended on it using `"*"` need to get fixed.

**Comment by AviVahl** [comment]
> I'm not sure why moving it to `send` helps, though; that package is still using `@types/mime@*`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/send/package.json
`"@types/mime": "^1",`

**Comment by jakebailey** [comment]
I apparently can't read!

**Review by jakebailey — APPROVED** [review]

**Comment by AviVahl** [comment]
Thank you for merging.
`master` is green, but no new `@types/serve-static` release yet...?
https://www.npmjs.com/package/@types/serve-static

**Comment by codershiba** [comment]
> Thank you for merging. `master` is green, but no new `@types/serve-static` release yet...? https://www.npmjs.com/package/@types/serve-static

Takes some time I guess

**Comment by jakebailey** [comment]
Publishing happens every half hour; give it like 5 minutes or so.

**Comment by codershiba** [comment]
Sorry for breaking this and causing so much chaos but I guess this was the only major package here that depending on `@types/mime: "*"`

**Comment by jakebailey** [comment]
All good, our tooling unfortunately can't detect this kind of break because at the point at which a package is removed, the dummy package has not yet been published to npm. A known downside of the new pnpm layout that we need to figure out, probably by erroring on `*` deps which are present in notNeededPackages.

**Comment by stu43005** [comment]
Just a note

This PR changes the import to `node:http`, which only supports `@types/node@>=14.18.0`.

**Comment by jakebailey** [comment]
Feel free to send a PR and tag me, that seemed like an unnecessary change I missed.

**Comment by jakebailey** [comment]
Actually, just sent https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69258

**Pull request merged**
