### PR TITLE
[pdfkit] add string type for image links

### PR DESCRIPTION
**Pull request by bencevans**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>> https://pdfkit.org/docs/images.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/pdfkit/pdfkit-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6def077e19e57cbbd1e41d2d0cfc00683b129494
</p>

**Review by BamButz — APPROVED** [review]
LGTM!

During my review, I noticed that AnnotationOption could be potentially wrong as type in this declaration (seems to be also true for goTo). I will investigate this on my own later.

**Review by BamButz — APPROVED** [review]

**Comment by bencevans** [comment]
@BamButz Cheers. I did wonder too but didn't want to break current types in case it is something.

**Comment by bencevans** [comment]
Ready to merge

**Pull request merged**
