### PR TITLE
[tizen-common-web] Modification of Time module

### PR DESCRIPTION
**Pull request by SejoongDeJang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by SejoongDeJang** [comment]
@egorshulga I'm Sejoong, owner of the tizen-common-web. Thanks for your PR.
But, when I tested your PR, there was error like followed:
``` ts
let datetime: TZDate = tizen.time.getCurrentDateTime();
// 'TZDate' refers to a value, but is being used as a type here. Did you mean 'typeof TZDate'?
```
Because the `class TZDate` cannot used interface as type. In this case, you need to declare new interface with `new():TZDate`. Not `TZDate: typeof TZDate`.
So I seperate the `class TZDate` to `interface TZDateConstructor` and `class TZDate`. The `interface TZDateConstructor` is return `class TZDate` and this is exported to user.
``` ts
//time.d.ts
export interface TZDateConstructor {
    new (datetime?: Date, timezone?: string): TZDate;
    new ( year: number,  month: number,  day: number,  hours?: number,  minutes?: number,  seconds?: number, milliseconds?: number, timezone?: string, ): TZDate;
}

export class TZDate {}
//index.d.ts
import { TimeUtil, TZDateConstructor, TimeDurationConstructor } from './time';

interface Tizen {
    TZDate: TZDateConstructor;
    TimeDuration: TimeDurationConstructor;
}
```
You can check code in File changed.

Thanks for join us again :)

**Comment by egorshulga** [comment]
That's cool, thanks for the amendment!
BTW, could you check another PR where I'm trying to add activity monitor API?
#48991 

I suppose it's better to use `type` instead of `enum` for `TimeDurationUnit`, what do you think?

**Comment by egorshulga** [comment]
Let me revert all `time` module changes from 48991, so it would be pure human activity monitor definitions

**Comment by SejoongDeJang** [comment]
Now we are checking about the #48991. 
We consider about using `type`, but refer to the guidance of the DefinitelyTyped, donot use `type` keyword.
Do you have any special reason for using `type` keyword?

**Comment by egorshulga** [comment]
`enum` is compiled to runtime object. AFAIK all api methods accept simple strings, but in TS `string` values are not compatible with `enum` keys of the same value (so we cannot pass `"MSECS"` instead of TimeDurationUnit.MSECS).
And I guess we could align with the examples in the api docs. Is it reasonable?

**Comment by SejoongDeJang** [comment]
I understand about your wish. I had tried to using `const enum`. But the maintainers doesn't accept about that. And the `type` is not to enumerate values. 
So, I released with `enum` object in our `[tizen-common-web](https://www.npmjs.com/package/tizen-common-web)`. With npm module, you can code like `TimeDurationUnit.MSECS`. Your `time` module has been released v1.0.4. 

Anyways, I think do not use `type` is better. It's the guidance of DefinitelyType for high quality typescript.

**Comment by egorshulga** [comment]
OK, I will now switch back to `enum`s in 48991. Thanks for your time!

**Comment by egorshulga** [comment]
@SejoongDeJang let me get back to the issue with enums again. You see, enums are compilable items, but there is a guideline to ship only a shape of the module the definitions are written for, not additional items for compilation.
And there is this issue in typescript repository: https://github.com/Microsoft/TypeScript/issues/12358
E.g., webpack ts-loader by default does not compile `.ts`  from `node_modules`.
Could it be a reason to decide against `enum`s in favor of `type`s? 
We still would receive all IDE suggestions, and we would follow the API provided by the tizen platform naturally as it is

**Comment by SejoongDeJang** [comment]
There are several reason I don't agree your opinion.
First, the `enum` values be constant and it only accept `string` and `number` type. But the `type` can include `function`, `object`  or `array`.
Second, as more as enumerated item increased, the readability get worse. For example, you need to a language code, but it have over 200 items. It's hard to find it.
Third, some `enum` object have same `number` value. Refer to my `tizen-tv-webapis`, there is `enum TvInfoMenuValue`.
It's a legacy code, someone developed in past. If I accept your opinion, developer doesn't seperate `TvInfoMenuValue.OFF` and `TvInfoMenuValue.CAPTION_OFF`. 
``` ts
enum TvInfoMenuValue {
    OFF = 0,
    ON = 1,
    CAPTION_OFF = 0,
    CAPTION_ON = 1,
}

```

**Comment by egorshulga** [comment]
But again, enums are compilable items, and it is supposed that packages from `node_modules` are not to be included in user compilation (and it is especially significant for packages in `node_modules/@types`). Npm modules should come in a form so it could be consumed by a user without applying any transforms.

`enums` are not constants, in runtime it's just pure objects. Probably that is why strings of the same value are not assignable to string-based enums.

Type _can_ include `function`, `object`, etc, but if we _define_ that it is a union of a set of `strings` only, so it would be so :) And typescript compiler guarantees us that only on of those strings would be assignable to a variable of that type. 
Besides, one of the most important features that we still get is a list of suggestions, which typescript language server provides us. And there is no need to find a specific value from the type, because a user would know which one he wants, as he would come from the documentation, as this one in particular would solve the issue the user is working on. And he would just start typing the value and he would immediately get a very short list of suggestions, and he would select a needed one. This feature works great for string unions.

Yes, there is a complication with number-based values from the API. I would suggest to use constants, which could be defined in a namespace of the same name as the target consumer of the value, or just a bunch of constants which could be imported from the library. Again, it would solve the issue of compiling the sources from a `node_modules` package.

**Comment by SejoongDeJang** [comment]
@egorshulga I know that language server is powerful, my second reason is not important anymore.
You know, our modules had been tested in tizen tv platform. At that time, I tried to using `type`, but there was some problem. I don't remember exactly. We will test about your suggestion at next week, how it works or not. I reply the result of it your [#48991](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48991). We have discussed the `enum`, not TZDate. 
So I want to close this PR, and keep discuss about enum in your PR [#48991](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48991). Do you agree with me?

**Comment by egorshulga** [comment]
Cool, let's do it!

**Review by pwsses — APPROVED** [review]
LGTM

**Comment by SejoongDeJang** [comment]
Ready to merge

**Comment by capscrom** [comment]
LGTM

**Pull request merged**
