### PR TITLE
[@types/node-forge] - change return type of decryptRsaPrivateKey()

### PR DESCRIPTION
**Pull request by Felix212**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/digitalbazaar/forge/blob/c5ab1e503dfd3dedf2de3dd5ce39b8387a0b0f48/lib/pbe.js#L529
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by wiktor-k — CHANGES_REQUESTED** [review]
This looks good in general but could you add tests to node-forge-tests.ts that would use decryptRsaPrivateKey and make sure the result is always rsa.PrivateKey (and not ed25519.Key that PrivateKey aliases to)?

Thanks!

**Comment by Felix212** [comment]
> 
> 
> This looks good in general but could you add tests to node-forge-tests.ts that would use decryptRsaPrivateKey and make sure the result is always rsa.PrivateKey (and not ed25519.Key that PrivateKey aliases to)?
> 
> Thanks!

Hey wiktor thanks for your reply.
I don't know what kind of tests i should add. `decryptRsaPrivateKey()` always calls `privateKeyFromAsn1()` https://github.com/digitalbazaar/forge/blob/c5ab1e503dfd3dedf2de3dd5ce39b8387a0b0f48/lib/rsa.js#L1278  which returns a rsa key. I am still new to cryto in general. I dont understand everything of the function yet.
 
Hope you can help me. 
Thanks

**Comment by wiktor-k** [comment]
Yes, your change is valid. I mean tests for the definitions that someone will not revert it accidentally.

Check out `types/node-forge/node-forge-tests.ts`.

Probably something like that at the end would suffice:
```ts
{
    let x: forge.pki.rsa.PrivateKey = forge.pki.decryptRsaPrivateKey('test');
}
```

Check out what happens if you keep this test but revert your change in the type definitions (then the test should fail). (`npm test` from the root repo will run tests).

Hope this helps if this is still unclear just tell.

**Comment by Felix212** [comment]
Ahh okay I get it now.
Thank you.

**Review by wiktor-k — APPROVED** [review]
LGTM :+1:

**Comment by wiktor-k** [comment]
Ready to merge

**Comment by wiktor-k** [comment]
Thanks for your contribution @Felix212!

**Pull request merged**
