### PR TITLE
Update of react-datepicker types after version update 3.0.0

### PR DESCRIPTION
**Pull request by flakronkadriu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-datepicker ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-datepicker@latest/))
was missing the following properties:
1. CalendarContainer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 351c0e0c06059ea72ab40299f8639ea3977f53ca
</p>

**Comment by Ky6uk** [comment]
It looks the library has more changes in [v3.0.0](https://github.com/Hacker0x01/react-datepicker/releases/tag/v3.0.0).

**Comment by flakronkadriu** [comment]
@Ky6uk Is it okay?

**Comment by Ky6uk** [comment]
@flakronkadriu I see the breaking change in 3.0

```
Replace inlineFocusSelectedMonth with focusSelectedMonth
```

Can you also reflect this in PR?

**Comment by Ky6uk** [comment]
Also, I think the major version of this type definition should be bumped to v3.

**Comment by flakronkadriu** [comment]
> Also, I think the major version of this type definition [should be bumped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) to v3.

@Ky6uk  I think to should i change the version in the header?

**Comment by flakronkadriu** [comment]
@Ky6uk  If you can take a look the PR because we need these changes. Thanks! @smrq @Rogach

**Comment by Ky6uk** [comment]
> > Also, I think the major version of this type definition [should be bumped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) to v3.
> 
> @Ky6uk I think to should i change the version in the header?

Yep. `3.0` in the header should work well.

**Review by Ky6uk — APPROVED** [review]

**Comment by flakronkadriu** [comment]
Ready to merge

**Pull request merged**
