### PR TITLE
[qrcode-svg] Added missing method type definitions

### PR DESCRIPTION
**Pull request by orangestark**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/papnkukn/qrcode-svg/blob/47d56ec28fcd0a3aabbb5f11a34167a02a80c54e/lib/qrcode.js#L88>>, <<https://github.com/papnkukn/qrcode-svg/blob/master/test/test.js>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by ericbf — COMMENTED** [review]
These are undocumented internal options and methods—is it wise to include them in the type? Why don’t you add a `.d.ts` to your specific project?

At least, according to copilot:

"When defining a TypeScript type on DefinitelyTyped, you typically do not include internal undocumented methods. DefinitelyTyped aims to provide type definitions for publicly accessible APIs that are well-documented, so including internal or undocumented methods would go against this purpose. It is best to only include methods and properties that are part of the public API."

Someone correct me if I am wrong on this though. The types look to be technically correct from my cursory review.

**Comment by jakebailey** [comment]
Yeah, we typically avoid putting things on DT that the author meant to be an internal detail. Often, with JS libs, it's hard to tell.

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes to reflect review status for the bot.

**Comment by orangestark** [comment]
Thanks for the feedback. I'll close this PR for now.

**Pull request closed without merging**
