### PR TITLE
Update: Ionic Framework, PouchDB, blobUtil, Cordova AppVersion

### PR DESCRIPTION
**Pull request by jfspencer**
Updating Support for Ionic Framework, Adding promise support to PouchDB(in progress) and added blobUtil definition for @nolanlawson 's blobUtil, added appVersion to cordova definition

### CODE REVIEW

**Comment by vvakame** [comment]
*blob-util/blob-util.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/blob-util
  * http://bower.io/search/?q=blob-util
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (blob-util/blob-util-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*cordova/cordova.d.ts*

author: Microsoft Open Technologies Inc. (account can't detected)

check list

* [ ] pass the Travic-CI test?

---

*cordova/plugins/AppVersion.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/cordova
  * http://bower.io/search/?q=cordova
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (cordova/plugins/AppVersion-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*ionic/ionic.d.ts*

to author(@spencerwi). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*pouchDB/pouch.d.ts*

to author(@MrBigDog2U). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by spencerwi** [comment]
The ionic changes look accurate to me, though I don't 100% understand the use of specific-string-value overloads with otherwise-identical signatures.

**Comment by jfspencer** [comment]
@spencerwi I may have missed the duplicate signatures, what line numbers are duplicated?

**Comment by spencerwi** [comment]
@jfspencer Lines 68-92 and 94-118 define lots of signatures for onGesture/offGesture. Might be a style difference, though; just curious about the decision there.

**Comment by jfspencer** [comment]
@spencerwi Ah, I see. I pulled the additions, with modification to be 1.1 compliant from https://github.com/danibo86/ionic-typescript-definitions/blob/master/beta14/ionic.d.ts where the onGesture/offGesture signatures were created. I tested to see if typescript would enforce the string literals in the gesture signatures, which it doesn't, so I'll remove all the duplicates. Thanks for catching that.

**Comment by spencerwi** [comment]
No problem! Looks good to me otherwise.

**Comment by jfspencer** [comment]
Added tests for AppVersion in in the cordova-tes.ts in the section with the other plugins

**Comment by mhegazy** [comment]
Can you please fix the failing Travis CI tests and update the PR!

**Comment by vladimir-kotikov** [comment]
@vvakame, @jfspencer, @mhegazy, I think I'd prefer to see typings for AppVersion plugin as a separate typings package (in a separate directory) similar to [cordova-plugin-ibeacon](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/cordova-plugin-ibeacon) or [cordova-plugin-ms-adal](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master\cordova-plugin-ms-adal), because `cordova` package was supposed to contain only cordova core API and core plugins.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
