### PR TITLE
Fixing TransactionObject.send return type in @types/web3

### PR DESCRIPTION
**Pull request by nanspro**
TransactionObject.send() on calling should return the type TransactionReceipt!!

### CODE REVIEW

**Review by zlumer — CHANGES_REQUESTED** [review]
Please add unit tests that fail before this fix is applied and pass afterwards.
Also, please link to the docs where the return type is declared.

**Comment by nanspro** [comment]
@zlumer  the test case where it fails is present in [Typechain](https://github.com/ethereum-ts/TypeChain/pull/129)!!
@Levino  is there any need of creating another testcase since we already know where it is failing?

**Comment by zlumer** [comment]
@nanspro Typechain is a separate project not related to these web3 types. Unit tests help prevent regressions in the code, which is not the case if tests are located outside of the codebase.

**Comment by Levino** [comment]
I agree with @zlumer but have not seen the code yet. Will review on Monday the earliest. Will not approve without unit tests that are run in CI here.

**Comment by Levino** [comment]
Also please fill out the pull request template with a link to the appropriate part of the web3 documentation.

**Pull request closed without merging**
