### PR TITLE
[@types/cytoscape] Added type definitions for Edge Endpoints

### PR DESCRIPTION
**Pull request by Veckodag**
Greetings Maintainers!

I make this PR to help with [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45090) regarding inclusion of [Edge Endpoints](https://js.cytoscape.org/#style/edge-endpoints) style option.

Have a wonderful day!

PS. I made a small mistake in PR #44975, so I added a minor fix for it.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## cytoscape ([<kbd>unpkg</kbd>](https://unpkg.com/browse/cytoscape@latest/))
was missing the following properties:
1. version
1. stylesheet
1. Stylesheet
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 70dd3a9a849ff1552122052233f3fedf6ebb61ca
</p>

**Review by ypconstante — APPROVED** [review]

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## cytoscape ([<kbd>unpkg</kbd>](https://unpkg.com/browse/cytoscape@latest/))
was missing the following properties:
1. version
1. stylesheet
1. Stylesheet
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e803204fec619f86459e4156181cf618880fc153
</p>

**Review by ypconstante — APPROVED** [review]

**Comment by Veckodag** [comment]
@andrewbranch Ping! Regarding the CI Label issue stated in #44317

**Comment by orta** [comment]
Yes, if it's green it is green - there's a few stragglers with the label, maybe next week I can just automatically remove them all

**Comment by orta** [comment]
OK, this has an approval and looks good to me 👍

**Pull request merged**
