### PR TITLE
github-electron: update shell module interface + tests

### PR DESCRIPTION
**Pull request by miniak**

### CODE REVIEW

**Comment by jedmao** [comment]
:+1:

**Comment by rhysd** [comment]
:+1:

**Comment by miniak** [comment]
Why does it take so long to get these changes merged? Especially after they have been thumbed up.

**Comment by rhysd** [comment]
PR review by DefinitelyTyped members is manual and there're hundreds of PRs.  So we need to wait patiently.

**Comment by miniak** [comment]
Actually, I would like to find a better way to mantain the typings.
Here it is too slow and it also does not allow versioning.

https://github.com/atom/electron/issues/4875

**Comment by miniak** [comment]
What about creating a separate repo for electron typings and registering it here?
https://github.com/typings/registry/blob/master/README.md

**Comment by miniak** [comment]
Superseded by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8723

**Pull request closed without merging**
