### PR TITLE
[@types/react-native-auth0] Add custom URL parameters to AuthorizeParams

### PR DESCRIPTION
**Pull request by bombillazo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [Forum Discussion 1](https://community.auth0.com/t/custom-authorize-params-extraparams/38412/8),
  - [Forum Discussion 2](https://community.auth0.com/t/passing-initialscreen-to-lock-from-webauth/6906/2)
  - [Source Code](https://github.com/auth0/react-native-auth0/blob/ad2af24d9e10ce76ddc1613a14eb0950a5c0baab/src/webauth/index.js#L70-L146)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-native-auth0 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-native-auth0@latest/))
was missing the following properties:
1. TimeoutError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ce5841df4a7ff3264296e9c239e184130c82ee3
</p>

**Comment by ascariandrea** [comment]
Wouldn't be better to make the `AuthorizationParams` interface parametric? In this wat the user can define exactly which custom params is gonna use

**Comment by bombillazo** [comment]
@ascariandrea  Please aid me in how one would define this. I'm not too savvy with Typescript to be honest.

**Comment by ascariandrea** [comment]
@bombillazo sure!

You can define the type as
```ts
type AuthorizeParams<P> = P & {
    state?: string; // Random string to prevent CSRF attacks and used to discard unexepcted results. By default its a cryptographically secure random.
    nonce?: string; // Random string to prevent replay attacks of id_tokens.
    audience?: string; // Identifier of Resource Server (RS) to be included as audience (aud claim) of the issued access token
    scope?: string; // Scopes requested for the issued tokens. e.g. `openid profile`
    connection?: string; // The name of the identity provider to use, e.g. "google-oauth2" or "facebook". When not set, it will display Auth0's Universal Login Page.
    language?: string;
    prompt?: string;
    max_age?: number; // The allowable elapsed time in seconds since the last time the user was authenticated (optional).
    organization?: string; // The ID of the organization to join
    invitationUrl?: string; // The invitation URL to join an organization. Takes precedence over the "organization" parameter.
}

const authorizaParamsWithCustom: AuthorizeParams<{ customParam1: string, customParam2: number }> = {
 customParam1: 'foo',
 cutomParam2: 2
}
```

Or you can actually define your own `AuthorizeParams` type with customs, in the same way:

```ts
type MyAuthorizeParams = AuthorizeParams & { customParam1: string; customParam2: number }

const authorizaParamsWithCustom: MyAuthorizeParams = {
 customParam1: 'foo',
 cutomParam2: 2
}
```

**Comment by bombillazo** [comment]
So this is where that type will be used:
```ts
export class WebAuth {
    authorize(parameters: AuthorizeParams, options?: AuthorizeOptions): Promise<Credentials>; // <-----
    clearSession(parameters?: ClearSessionParams): Promise<any>;
}
```
In that case, to make it parametic, would it be better to add an optional type parameter to the authorize function and AuthorizeParams?

```ts
export class WebAuth {
    authorize<P = void>(parameters: AuthorizeParams<P>, options?: AuthorizeOptions): Promise<Credentials>; // <-----
    clearSession(parameters?: ClearSessionParams): Promise<any>;
}

type AuthorizeParams<P> = P & {
    state?: string; // Random string to prevent CSRF attacks and used to discard unexpected results. By default its a cryptographically secure random.
    nonce?: string; // Random string to prevent replay attacks of id_tokens.
    audience?: string; // Identifier of Resource Server (RS) to be included as audience (aud claim) of the issued access token
    scope?: string; // Scopes requested for the issued tokens. e.g. `openid profile`
    connection?: string; // The name of the identity provider to use, e.g. "google-oauth2" or "facebook". When not set, it will display Auth0's Universal Login Page.
    language?: string;
    prompt?: string;
    max_age?: number; // The allowable elapsed time in seconds since the last time the user was authenticated (optional).
    organization?: string; // The ID of the organization to join
    invitationUrl?: string; // The invitation URL to join an organization. Takes precedence over the "organization" parameter.
}
```
It should be optional since these custom properties are optional.

**Comment by bombillazo** [comment]
Any thoughts @ascariandrea ?

**Comment by bombillazo** [comment]
awesome! Thanks for the input, Ill update the PR

**Comment by bombillazo** [comment]
I'm getting this error:
```
ERROR: 237:105  no-unnecessary-generics  Type parameter P is used only once. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md
```
on authorize
```ts
export class WebAuth {
    authorize<P extends { [key: string]: string | number | undefined } = {}>(parameters: AuthorizeParams<P>, options?: AuthorizeOptions): Promise<Credentials>; 
    clearSession(parameters?: ClearSessionParams): Promise<any>;
}
```

**Comment by bombillazo** [comment]
Hey @ascariandrea! Once again, thanks for the help.

It still gave the error, I think because `{ [key: string]: string | number | undefined }` includes the empty object, and given this I think the linter views the generic type as unnecessary to specify. With the new changes adding any other property works, you just wont have a type defining them, which is fine.

**Comment by bombillazo** [comment]
Is this good to go?

**Comment by ascariandrea** [comment]
> Is this good to go?

In this way is not that useful, as the compiler can't infer the extended type of `AuthorizeParams` (if I'm not wrong). 

Did you try changing the type def `{ [key: string]: string | number | undefined }` by removing the `undefined`? It shouldn't be needed and you can replace it with `{[key:string]?: string| number}`

**Comment by bombillazo** [comment]
Any type of combination like this:
```js
authorize<C extends { [key: string]: string | number } = {}>(parameters: AuthorizeParams<C>, options?: AuthorizeOptions): Promise<Credentials>;
```
Is triggering an unnecessary generics error:
```bash
ERROR: 237:94  no-unnecessary-generics  Type parameter C is used only once. See: https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md
```

**Comment by leoafarias** [comment]
Hey guys just jumping in on this. But I think the best approach would be the following.

```ts
export class WebAuth {
    authorize<T extends AuthorizeParams>(parameters: T, options?: AuthorizeOptions): Promise<Credentials>;
    clearSession(parameters?: ClearSessionParams): Promise<any>;
}
```

This would allow us to do this:

```ts
export interface ExtendedAuthorizeParams extends AuthorizeParams {
    customParam:number;
    customParam2:number;
}
```

and use it like this

```ts
auth0.webAuth.authorize<ExtendedAuthorizeParams>({
    state: 'state',
    nonce: 'nonce',
    scope: 'openid',
    max_age: 10,
    customParam:1,
    customParam2:2
});
```

**Comment by bombillazo** [comment]
Hey @leoafarias, thanks for the input! I like that approach as well, but `dtslint` still fails the that approach with the same error. 😞 

Seems the linter does not like any type of single use for a generic parameter, but without it Im not sure how  one could pass an optional type that extends AuthorizeParams.

**Comment by leoafarias** [comment]
@bombillazo I think we might be trying to solve an issue with the lib through the types... looking through the source code, most likely there should be a customParams property that you can define and pass, and within the lib do the proper parsing.

It is tough to have proper typing and also say you can pass anything to it.. I think we should open up an issue on the repo, and ask for the core team input.

**Comment by bombillazo** [comment]
The response from the auth0 team would be one similar to the ones suggested earlier without the generic:

```ts
type AuthorizeParams = { [key: string]: any } & {
    state?: string; // Random string to prevent CSRF attacks and used to discard unexpected results. By default its a cryptographically secure random.
    nonce?: string; // Random string to prevent replay attacks of id_tokens.
    audience?: string; // Identifier of Resource Server (RS) to be included as audience (aud claim) of the issued access token
    scope?: string; // Scopes requested for the issued tokens. e.g. `openid profile`
    connection?: string; // The name of the identity provider to use, e.g. "google-oauth2" or "facebook". When not set, it will display Auth0's Universal Login Page.
    language?: string;
    prompt?: string;
    max_age?: number; // The allowable elapsed time in seconds since the last time the user was authenticated (optional).
    organization?: string; // The ID of the organization to join
    invitationUrl?: string; // The invitation URL to join an organization. Takes precedence over the "organization" parameter.
}
```

I'm fine with this as it reflects the typing reality and intention of the library. I've updated the PR.

**Comment by leoafarias** [comment]
Also thank you for your work on this @bombillazo lot of work for a simple change ;)

**Comment by bombillazo** [comment]
Funnily enough that was the very first approach I took, only thing was I limited the Value type. Revisiting it, I agree its cleaner 😆 I've updated the PR.

And glad to help and contribute!

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by leoafarias** [comment]
Ready to merge

**Comment by bombillazo** [comment]
Awesome! Thanks for the help!

**Comment by leoafarias** [comment]
@bombillazo thank you!

**Pull request merged**
