### PR TITLE
[@types/spotify-api] run prettier

### PR DESCRIPTION
**Pull request by gnbaron**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developer.spotify.com/documentation/web-api/reference>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by gnbaron** [comment]
This only runs `npm run prettier -- --write types/spotify-api/**/*.ts` to format the package code accordingly so next contributors don't have to.

As discussed in #53777.

**Comment by piksel** [comment]
Are you sure you did what you intended to do?
image

**Comment by gnbaron** [comment]
> Are you sure you did what you intended to do?

Yeah, I went through both files and everything looks good. Also, tests are passing.

> Can't even view the test file in github. 😓

Considering the fact that pretty much the whole test file was not matching the formatting settings, yes. You can always pull the branch and compare using a git client, let me know if you need help with that.

**Comment by peterblazejewicz** [comment]
@gnbaron I've got different diff stats when run on the current master, was this the reason you've closed this PR?

**Comment by gnbaron** [comment]
@peterblazejewicz actually no, I've discussed this with other contributors and on discord and looks like no one was willing to review it, that's why I closed it. It's also just formatting, so it's fine to leave as it is rn.

**Pull request closed without merging**
