### PR TITLE
Create node-pipewire types

### PR DESCRIPTION
**Pull request by kakxem**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-pipewire/node-pipewire-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ba587ec8ca567b678a4a9a2bc98e12357629ca5d
</p>

**Review by MysteryBlokHed — COMMENTED** [review]
It looks like this library already includes its own `.d.ts` files: <https://unpkg.com/browse/node-pipewire@1.0.15/build/>

Screenshot of node-pipewire on npm, showing its bundled types

**Comment by kakxem** [comment]
> It looks like this library already includes its own `.d.ts` files: https://unpkg.com/browse/node-pipewire@1.0.15/build/
> Screenshot of node-pipewire on npm, showing its bundled types

I know, but this library has a native module. Because maybe can't be compiled, I've added the library to the 'optionalDependencies' in the project's package.json. 

The problem is that when the library is not installed, I can't get the necessary TypeScript types to handle errors effectively...
So I thought It'd be a good idea to have the types here too.

I've already read "a package bundles its own types, types should be removed from Definitely Typed to avoid confusion" from the README, but I would like to have the types here too.

Can I merge this or should I remove the bundle types?

**Comment by kakxem** [comment]
@MysteryBlokHed, can I have your ok?

**Comment by MysteryBlokHed** [comment]
Personally, I'd recommend keeping the types bundled with the original library and closing this. It means that you need to pull down the entire library to get its types, which might seem inconvenient, but I think it makes more sense to keep everything in one repository. If you really want the `@types` package, you'd probably need to remove the bundled types from the original library.

At the end of the day I'm not actually a DefinitelyTyped maintainer, so it'd be up to one of them whether to merge this in its current state. If you want, you can wait until one of them checks on this PR to see what their advice might be.

**Comment by kakxem** [comment]
I would like to have both, so I'll wait for a maintainer... 😢

**Comment by peterblazejewicz** [comment]
@MysteryBlokHed is correct, as it appears, as of today, module ships it's own types:
https://github.com/kakxem/node-pipewire/blob/master/package.json#L6
For now it seems to be best outcome for users (e.g. when using TS automatic type acquisition feature in IDEs)
What's the exact scenario to ditch this existing support and outcome for users?

**Comment by kakxem** [comment]
As I said, if the library is set to '[optionalDependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies)' instead of dependencies/devDependencies and the library could not be installed (It could be caused by external factors, in my case, the module is not compatible with the operating system or the processor architecture does not match), I cannot have the proper types of my library. I need the types to handle the TS errors(due to the try/catch), and I can't move progress with my pull request right now. [Here's one example](https://github.com/kakxem/WebCord/blob/feature/screenshare-with-audio/sources/code/common/modules/node-pipewire-provider.ts)

I need to do hacks to make it work + many ts-ignore in places where I use my library because TS is not ready to handle 'optionalDependencies'.

**Comment by peterblazejewicz** [comment]
OK, how you would prevent two versions, diverged definitions out in the wild?
Can you consider to remove shipping types with nom package (remove 'types' entry, etc) and just ship `@types/ndoe-pipewire`? (declaration will be looked for by automatic types acquisition feature in TS afaik in supported IDEs)

**Comment by kakxem** [comment]
@peterblazejewicz I would have no problem removing the bundled one, but I would like to still keep it (because if I make an application for 'x' OS that supports my library, I don't have to install the @types in my devDependency). 

The problem I understand is that if there are two versions and they don't match, TS can't tell which one is correct. In that case, the only thing I can say is that I would have to update both when a new version is released.

I thought the IDE tries to find the types in the module, but if it doesn't find them, it will try to find the @types.

**Comment by peterblazejewicz** [comment]
Types acquisition primary helps plain JS project authoring, for TS based projects user has to add types explicitely anyway:
https://www.typescriptlang.org/tsconfig#type-acquisition

Your module already ships TS declaration files and those are always picked up, as a proper, TS-friendly export:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

I"d not go against well known TS patterns.

Really sorry for not having a clear answer, I think having a well defined do-donts for DT is a huge plus for the community

- keep 'as is' (part of setups could suffer)
- remove bundled decorations, just publish to DT (you would have to advertise this usage within e.g. README)

**Comment by kakxem** [comment]
Alright, I made the changes in my repo and now my library no longer has types.

@peterblazejewicz  I guess that's enough to merge the types, right?

**Review by peterblazejewicz — APPROVED** [review]
@kakxem thanks!
LGTM!

**Comment by kakxem** [comment]
Ready to merge

**Pull request merged**
