### PR TITLE
fix for newer react version, State as second argument for Component

### PR DESCRIPTION
**Pull request by pesakitan22**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by weswigham** [comment]
@pesakitan22 What's the motivation for this change? The parameter is never instantiated with anything other than `any`, and it already has a default set by the `react.d.ts` maintainers.

**Comment by RyanCavanaugh** [comment]
@pesakitan22 Please address the merge conflict.

**Review by minestarks — CHANGES_REQUESTED** [review]
Per @weswigham 's comment, could you please explain why this change is needed, and/or add test cases?

**Comment by minestarks** [comment]
I'm closing this PR due to lack of activity. If you would still like to get in these changes, please open a new PR. Thank you!

**Pull request closed without merging**
