### PR TITLE
Add type declarations for [bristol] logger

### PR DESCRIPTION
**Pull request by ElliottCampbellJHA**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
Unfortunately, the underlying library has complicated exports that can't be perfectly captured in a .d.ts file.  In particular, the module it exports is effectively both a class instance and a namespace.  Of the two, the former is arguably more important (e.g. see the sample usage on the GH page).  To make that work, you probably want to remove your existing `export` keywords, `declare const bristol: Bristol;`, and then `export = bristol;`.  Then `import bristol = require('bristol');` will work as expected, except that `bristol.Bristol` and `bristol.Bristol.logUtil` will be unavailable.

If you'd like to get fancier and build a better approximation, let me know.

**Comment by eheikes** [comment]
@amcasey I see what you're saying. Unfortunately, for our situation we need/use the `Bristol` constructor rather than the pre-constructed instance. But I also agree that the class instance is probably more common, so we can modify the PR for that case if it's not possible to include both.

**Comment by ElliottCampbellJHA** [comment]
I think I'd rather not get too fancy at the moment I've uploaded the suggested changes.

**Comment by amcasey** [comment]
@eheikes I think supporting the common case is the key consideration, so I'm inclined to merge this version as is (thanks for the changes @ElliottCampbellJHA !).  However, I believe a more complicated version could address your use case as well and I'd be happy to work with you to create a new PR.

**Comment by eheikes** [comment]
I'm fine with merging this PR for now.

> However, I believe a more complicated version could address your use case as well and I'd be happy to work with you to create a new PR.

That would be great! How do you want to do that -- do you want to start work on it, or should we give it a shot?

**Review by amcasey — APPROVED** [review]

**Comment by amcasey** [comment]
@heikes, cool, let me draft a skeleton for you and you can flesh it out in a separate PR.

**Comment by amcasey** [comment]
@eheikes, here you go:
```ts
import logUtil2 = require("./logUtil");

interface LogError {
    message?: string;
    reason?: any;
    stack?: any;
}

interface LogData {
    code?: number;
    id?: string;
    path?: string;
    error?: LogError;
    data?: any;
}

export class Bristol {
    addTarget(target: any, opts?: any): any;
    withFormatter(formatter: string): any;
    withLowestSeverity(severity: string): any;
    info(message: string, data: LogData): any;
    warn(message: string, data: LogData): any;
    error(message: string, data: LogData): any;
    debug(message: string, data: LogData): any;
}

export namespace Bristol {
    const logUtil: typeof logUtil2;
}

export function addTarget(target: any, opts?: any): any;
export function addTarget(target: any, opts?: any): any;
export function withFormatter(formatter: string): any;
export function withLowestSeverity(severity: string): any;
export function info(message: string, data: LogData): any;
export function warn(message: string, data: LogData): any;
export function error(message: string, data: LogData): any;
export function debug(message: string, data: LogData): any;
```

Two caveats:
 1. The module object won't actually be an instance of the `Bristol` class for nominal typing purposes
 2. All members of the class are declared twice

I'll ask around in case there's a clever way to eliminate the duplication, but I think we're stuck with the first restriction.

**Pull request merged**
