### PR TITLE
Typings for Snowboy

### PR DESCRIPTION
**Pull request by dolanmiu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
It looks like this library is already written in TypeScript. Is there any reason the authors can't just provide the generated `.d.ts` files over npm?

@nekuz0r @evancohen @chenguoguo

**Comment by dolanmiu** [comment]
@DanielRosenwasser I have put a pull request for this, but it never got merged. I think it caused problems:

https://github.com/Kitt-AI/snowboy/pull/206

**Comment by minestarks** [comment]
Kitt-AI/snowboy#206 seems to be making progress, will be waiting on that before merging this

**Comment by dolanmiu** [comment]
Can you put this on hold, the merge request just got merged:

https://github.com/Kitt-AI/snowboy/pull/206#issuecomment-326812056

I want to test it first

**Comment by sandersn** [comment]
@dolanmiu any word on whether the bundled d.ts is now working? Should I close this PR?

**Comment by dolanmiu** [comment]
Could you merge this in? The fix I made on the repo did not work, and I am not sure what the problem is

**Pull request merged**
