### PR TITLE
lodash: changed _.rest() method (alias _.tail())

### PR DESCRIPTION
**Pull request by chrootsu**
https://lodash.com/docs#rest
https://lodash.com/docs#_ (description of the chainable wrapper)

### CODE REVIEW

**Comment by vvakame** [comment]
@chrootsu please resolve conflict

**Comment by chrootsu** [comment]
@vvakame done.

**Comment by chrootsu** [comment]
@vvakame please check this PR, conflicts are resolved

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
