### PR TITLE
[dynogels] Added typings

### PR DESCRIPTION
**Pull request by moraneva**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by moraneva** [comment]
hmmmm @RyanCavanaugh any idea why travis didn't run?

**Comment by sandersn** [comment]
I'll try to close/re-open and see if Travis notices.

**Comment by sandersn** [comment]
@moraneva in the past Travis has incorrectly flagged people as "abusive" just because they don't have a Travis account. (I guess they are then using Travis anonymously?)

If you don't have a Travis account, can you visit travis-ci.org, create an account, and consent to connect your Github account to your new Travis account? I think you will have to create a new PR afterward as well.

If you already have a Travis account, let me know and I'll see if Travis support can help.

**Comment by moraneva** [comment]
@sandersn I've got a travis account, but do you think it would have anything to do with me creating the PR from a github organization that I own? Not sure if it's worth trying to just open it back up from a personally forked repo

**Comment by sandersn** [comment]
Maybe so? It's worth trying at least.

**Pull request closed without merging**
