### PR TITLE
chore: rename google-maps-web to google.maps

### PR DESCRIPTION
**Pull request by jpoehnelt**
Simple rename of the package. These types match Google Maps Platform JS which adds `window.google.maps.*`. This name seems more fitting than `google-maps-web`

### CODE REVIEW

**Comment by amuramoto** [comment]
lgtm!

**Review by amuramoto — APPROVED** [review]
lgtm

**Comment by jpoehnelt** [comment]
@sandersn Please take a look.

**Review by sandersn — APPROVED** [review]

**Comment by jpoehnelt** [comment]
Ready to merge

**Pull request merged**
