### PR TITLE
Update chart.js Chart constructor from v2.4.0

### PR DESCRIPTION
**Pull request by diogosantana**
Version 2.4.0 new Chart constructor signature

chartjs/Chart.js@4a5b5a0

### CODE REVIEW

**Comment by mhegazy** [comment]
@stephtr @ulikoehler @tobias-kutter @oosoloviov can you please review this change.

**Review by tobias-kutter — APPROVED** [review]
Useful changes.

**Comment by stephtr** [comment]
Doesn't that add jQuery's definition file into global scope?

**Comment by yuit** [comment]
@stephtr yep it does

**Comment by stephtr** [comment]
But only because I use Chart.js it doesn't mean that I also want to include jQuery.
For example I created a new project, added chart.js and immediately VS Code's IntelliSense has jQuery's types and variables listed.
screenshot

**Review by yadavvineet — COMMENTED** [review]
code is working, changes in line with updated chartjs library.

**Pull request merged**
