### PR TITLE
[bluebird] Restore assignability to native Promises (fixes #11027)

### LINKED ISSUE #11027: bluebird 3.0 definifion is not assignable to ES6 Promises
The bluebird 3.0 definition is not assignable to standard es6 Promise definition:
```ts
Types of property 'then' are incompatible.
Type 'Bluebird<any>' is not assignable to type 'Promise<any>'.
```
 /cc @lhecker

### PR DESCRIPTION
**Pull request by lhecker**
## Intention

Recently Bluebird added support for `Symbol.toStringTag` in https://github.com/petkaantonov/bluebird/pull/1421.
This PR adds typings for this new "feature", in turn restores assignability of Bluebird to native Promise types and thus fixes the longstanding issue #11027.

This Bluebird feature has _not_ been released yet, but I expect this to happen relatively soon.
We'll have to decide whether we wait or not for Bluebird to release the changes in the above PR.
I've inquired @petkaantonov whether we intends to release a minor version for this [here](https://github.com/petkaantonov/bluebird/pull/1421#issuecomment-484134806).
In that case we could safely release this PR as part of seperate Bluebird 3.6 typings.
If it'll be a patch release we can merge this PR at any point in time instead.

## Code

The PR is split up in 2 commits. You should review them seperately.
The first commit only renames the Bluebird import for tests, in order for us to more easily have access to the native `Promise` class (including in the future).

cc: @tmueller

## Template

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/petkaantonov/bluebird/pull/1421
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by lhecker** [comment]
Bluebird has an absolute massive amount of dependents which must be upgraded for this to work.
(The TSC version upgrade is necessary because `Symbol.toStringTag` is incompatible otherwise.)
I'm not sure if there's any better way about this. 🤔

**Review by jasonswearingen — APPROVED** [review]

**Comment by jasonswearingen** [comment]
glad to finally see bb made compatable with native promises.  props for seeing this through!

**Comment by armanio123** [comment]
@lhecker As you mentioned this has not been release yet, I'll keep from merging until you let me know otherwise.

**Review by plantain-00 — APPROVED** [review]

**Comment by lhecker** [comment]
To be completely honest I didn’t expect the release of this feature to take quite that long.
I‘m not sure what to do about it though.

I‘ll fix the merge conflict once Bluebird was released with this change.

**Comment by lhecker** [comment]
@armanio123 Bluebird 3.5.5 was released just now with this particular feature.
[I've had to rebase this PR to resolve a minor conflict as can be seen above.](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/f9c715dfe4d96ae5bf7ba7e61abf35843b40942d..0997c58d9b846ef52e2239eaf45e3c67e3f8f40a)

You should be able to safely merge this PR now. 🙂

**Review by mastermatt — APPROVED** [review]

**Pull request merged**
