### PR TITLE
fix(fluent-ffmpeg): mergeToFile signature

### PR DESCRIPTION
**Pull request by arthurjdam**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [npmjs.com/package/fluent-ffmpeg](https://www.npmjs.com/package/fluent-ffmpeg#mergetofilefilename-tmpdir-concatenate-multiple-inputs)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (not needed)

### CODE REVIEW

**Review by tcaesvk — APPROVED** [review]
LgTM

**Comment by ox-arthur** [comment]
Ready to merge

**Comment by arthurjdam** [comment]
Ready to merge

**Comment by takahashi-shotaro** [comment]
@arthurjdam Hello. Looking at the actual code,

https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/68d5c948b689b3058e52435e0bc3d4af0eee349e/lib/recipes.js#L421

it looks like `mergeToFile` is an alias for `concat`. Perhaps the README has not been updated and is wrong.
At least it worked for me without the second argument.

**Pull request merged**
