### PR TITLE
Add template import type for uniqueId helper

### PR DESCRIPTION
**Pull request by vstefanovic97**
Please fill in this template.

- [+] Use a meaningful title for the pull request. Include the name of the package modified.
- [+] Test the change in your own code. (Compile and run.)
- [+] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [+] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [+] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [+] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [+] Provide a URL to documentation or source code which provides context for the suggested changes: [unique-id](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/unique-id?anchor=unique-id)
- [+] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by SergeAstapov — APPROVED** [review]

**Comment by gitKrystan** [comment]
@vstefanovic97 Can you try a rebase? I think the failing test should pass now due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69838

**Comment by vstefanovic97** [comment]
@gitKrystan actually, it seems that `uniqueId` helper was only added to `ember-source` version 5, should we still add this with that in mind?

**Comment by SergeAstapov** [comment]
> @gitKrystan actually, it seems that `uniqueId` helper was only added to `ember-source` version 5, should we still add this with that in mind?

@vstefanovic97 just to clarify:
per https://github.com/emberjs/ember.js/blob/main/CHANGELOG.md#v440-may-2-2022 `unique-id` helper was implemented in 4.4

and then, per https://github.com/emberjs/ember.js/blob/main/CHANGELOG.md#v520-august-7-2023 created public import for `uniqueId` helper in 5.2

so the issue we are trying to address here is to make helper importable for use in .gts/.gjs which is possible starting 5.2+.

However, that requires using native types, which is not what I guess everyone has migrated to (knowing Ember Data types are in alpha/preview stage right now).

@vstefanovic97 @gitKrystan with above info, IMO this does not hurt to land and release as is to unblock wider audience.

**Comment by vstefanovic97** [comment]
That is exactly right @SergeAstapov

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/ember__helper/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against da4f5c9c645fe7a4f39de85ca1906ae0f1fec2e1
</p>

**Comment by vstefanovic97** [comment]
@gitKrystan mind to re-review and approve if all looks good now?

**Review by gitKrystan — APPROVED** [review]

**Pull request merged**
