### PR TITLE
Prosemirror-Model: Adds missing optional target argument to serializeFragment function

### PR DESCRIPTION
**Pull request by stefannew**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Source Code](https://github.com/ProseMirror/prosemirror-model/blob/master/src/to_dom.js#L44)

This function definition hasn't changed in 5 years, so it looks like this type was just incorrect.

### CODE REVIEW

**Comment by Narretz** [comment]
This method is not in the docs, which usually means it's not public: https://prosemirror.net/docs/ref/#model.DOMSerializer.serializeFragment. Types should only contain public interfaces.

**Comment by stefannew** [comment]
@Narretz I'm confused, you linked to the method in the docs.

**Comment by Narretz** [comment]
@stefannew sorry, I meant to write the parameter "target" is not in the docs. And the docs are the source of truth for the types, because they are generated from code comments.

**Comment by stefannew** [comment]
@Narretz Ah, I understand. No problem - would it help if I got the docs updated in `prosemirror-model`? I'm fairly certain the intention is to allow for a public interface with a third argument (target) in this instance. I can dig up examples from the Prosemirror forums.

**Comment by Narretz** [comment]
@stefannew yes, that's right. If the parameter was described in the comments here: https://github.com/ProseMirror/prosemirror-model/blob/23221300428f1b485cb17d86bb1bd72570096647/src/to_dom.js#L44 it would become part of the public API. The code is pretty old, maybe Marijn simply forgot to add the docs.

**Comment by stefannew** [comment]
@Narretz Gotcha, thanks. I'll see what I can do and I'll ping you here once I hear back.

**Pull request closed without merging**
