### PR TITLE
update types for autosize

### PR DESCRIPTION
**Pull request by zikaari**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://www.jacklmoore.com/autosize/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

# Changes
- Add jQuery overloads
- Fixed return values of functions, they now return whatever type is passed in
- Module no longer pollutes global scope, consumers will now require `import autosize from 'autosize'`
- Added function comments (for better intellisense experience)

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@NeekSandhu Please fix the failures indicated in the Travis CI log.

**Comment by NeekSandhu** [comment]
@RyanCavanaugh As the Travis CI Log mentions, are we allowed to move on to Typescript 2.3+

Or it must be 2.0. Gives me IE8 nostalgia.

**Comment by RyanCavanaugh** [comment]
@NeekSandhu yes, please add the version string to the header as suggested by the Travis log

**Comment by NeekSandhu** [comment]
I could not modify this PR (I deleted my fork after making PR), so had to start over.
New PR is at  #18089

**Pull request closed without merging**
