### PR TITLE
[@types/node] Remove myself from contributors

### PR DESCRIPTION
**Pull request by j-oliveras**

### CODE REVIEW

**Comment by j-oliveras** [comment]
mongoose errors are unrelated to these changes.

**Review by Flarna — APPROVED** [review]

**Review by trivikr — APPROVED** [review]

**Review by SimonSchick — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@j-oliveras thx!

**Review by r3nya — APPROVED** [review]

**Comment by j-oliveras** [comment]
@rbuckton you seems to be active here this week. Can you merge this? The bot don't removed the 'The CI failed' tag.

Thanks.

**Comment by j-oliveras** [comment]
@RyanCavanaugh Seems that the bot doesn't remove the 'The CI failed' tag after the CI passed.

Can you merge this?

**Review by r3nya — APPROVED** [review]

**Review by Flarna — APPROVED** [review]

**Review by ryanrw — APPROVED** [review]

**Comment by j-oliveras** [comment]
@orta Can you merge this?

**Review by trivikr — APPROVED** [review]

**Pull request merged**
