### PR TITLE
meteor: Use mongodb driver types for Selector=>Filter, Modifier=>UpdateFilter, SortSpecifier=>Sort instead of homebuilt types

### PR DESCRIPTION
**Pull request by perbergland**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
[MongoDB driver v4 now contains good types to use](https://www.npmjs.com/package/mongodb)

### CODE REVIEW

**Comment by radekmie** [comment]
I like this change, but the fact that we can't do it in the `globals` directory is a problem - these types will be significantly different. Overall, I think we should stop improving these and focus on the ones in Core. What do you think?

**Comment by perbergland** [comment]
I think the meteor core team should just import these types since we have a good maintainer team that can push updates more frequently.

The core team has too much on their hands and there is no test harness for types in core anyway (as proven in the last 2.9.0 release where types were accidentally dropped).

**Comment by radekmie** [comment]
I get that, but the types in Core are already slightly improved (@piotrpospiech did that), and I'm pretty sure we'll diverge them sooner or later _too much_. Improving them in both places also suggests that there's no preferred option and I'd like to believe the ones in Core are the preferred ones.

As I have maintainer rights in the Core repo, let's put it like this: @Grubba27, can I redirect all of the type-related PRs there and take care of them?

And lastly, as for the type-level test harness in Core - I think we have to think about it anyway.

**Comment by andrei-markeev** [comment]
@perbergland nowadays they are focusing on Typescript a lot and are gradually replacing community types with core types. I don’t think DefinitelyTyped community contributors are more active actually.

I fully agree that types from the mongo driver should be used instead of homebuilt types as much as possible, and in general, hopefully the core team will get rid of those Mongo wrappers altogether at some point.

**Comment by perbergland** [comment]
Added a PR for core meteor

**Comment by Grubba27** [comment]
>  @Grubba27, can I redirect all of the type-related PRs there and take care of them?

Yes, you can @radekmie!

Again I would like to say thanks to  @perbergland and @radekmie  for helping with this.

**Comment by radekmie** [comment]
@perbergland Can you close this PR as it got merged to Core? I'll look into deprecating the `@types/meteor` completely.

**Comment by perbergland** [comment]
Closing in favor of core types in meteor/meteor

**Pull request closed without merging**
