### PR TITLE
Update `inquirer` to v9

### PR DESCRIPTION
**Pull request by neurolag**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - <https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%408.0.0>
  - <https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%408.1.0>
  - <https://github.com/SBoudrias/Inquirer.js/compare/inquirer%408.2.4...inquirer%409.0.0>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Changes made in this PR add a few features to the currently published inquirer types version (which is v8.2). Furthermore, this PR adds declarations for the new inquirer version (`inquirer@9`) which is completely written as an ES module.

For the sake of having the new `postfix` option available for `EditorPrompt`s, this PR adds a separate type declaration for `inquirer@8.2`.

Furthermore, I have noticed, that `"module": "Node16"` typescript projects have a tough time working with classes exposed using `typeof`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0be9ba582713cf343b1532519d02b241b820a7ed/types/inquirer/index.d.ts#L188-L206

Thus, the namespace export in `inquirer@8` has been completely dropped while still allowing `inquirer` and `inquirer`-types to be imported in the same manner as before.

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Thanks for the well-organized commits. I think the only thing that’s missing is a package.json with `{ "type": "module" }`.

**Comment by manuth** [comment]
> Thanks for the well-organized commits. I think the only thing that’s missing is a package.json with `{ "type": "module" }`.

Awesome! Thank you so much for having a look through it 😄

**Review by andrewbranch — APPROVED** [review]
I wish another owner had reviewed, but oh well 🤷‍♂️

**Comment by manuth** [comment]
Well at least the tests are all running through, so I think we might be safe 😂
Ready to merge

**Comment by manuth** [comment]
Ready to merge

**Pull request merged**
