### PR TITLE
Flip unstable_useTransition array params  + edit eslint test

### PR DESCRIPTION
**Pull request by damikun**
- This is breaking change in API from FB Core team from March.. https://github.com/facebook/react/pull/20976 

To be able to use last experimental versions we need to update this types for experimental...

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by damikun** [comment]
@Jessidhia  or @johnnyreilly  looks good to go ;)

**Review by dimitropoulos — APPROVED** [review]
Huh.  Why do I feel like we already got a PR for this recently?  Was this not the only react API to switch the order of the tuple in the last few weeks.  Either way..  Thanks! :)

**Comment by damikun** [comment]
> Huh. Why do I feel like we already got a PR for this recently? Was this not the only react API to switch the order of the tuple in the last few weeks. Either way.. Thanks! :)

Hi @dimitropoulos 

It was but it is not merged + is outdated + test did not pass + there was already changes in that files from another pulls.. its not my brunch and is not updated or fixed more weeks... Author seems to not fix it...

**Review by eps1lon — APPROVED** [review]

**Comment by damikun** [comment]
Can we merge this?

**Comment by dimitropoulos** [comment]
Ready to merge

**Pull request merged**
