### PR TITLE
fix(webpack-dev-middleware): support webpack5

### PR DESCRIPTION
**Pull request by tqma113**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by tqma113** [comment]
#50773 #50802 #50870

**Comment by peterblazejewicz** [comment]
see #52030

**Comment by bengry** [comment]
Any news on this?
I'm having the same issues with 2 other packages - `@types/webpack-dev-server` and `@types/webpack-manifest-plugin`, and want to see if this is  the solution deemed correct by Definitely Typed before I go ahead and open PRs for those 2 packages.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@tqma113 thx!

**Comment by tqma113** [comment]
Ready to merge

thx @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@tqma113 mind adding a test? this will pass the CI check and make this PR self-merged, thx!

**Comment by elibarzilay** [comment]
(@tqma113: Made it possible to merge, but please do consider following up on @peterblazejewicz's suggestion to add tests before you do.)

**Review by peterblazejewicz — APPROVED** [review]

**Comment by tqma113** [comment]
Ready to merge

**Comment by lizthegrey** [comment]
This should ideally have been a separate major version, as it breaks webpack v4 compatibility. going to webpack-dev-middleware@5.0.0 might have been good to communicate that it goes with webpack v5.

**Pull request merged**
