### PR TITLE
Remove `@storybook/addon-storyshots` types

### PR DESCRIPTION
**Pull request by gaetanmaisse**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

Select one of these and delete the others:

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

--

`@storybook/addon-storyshots` and `@storybook/addon-storyshots-puppeteer` were migrated to TS in this PR https://github.com/storybooks/storybook/pull/4758 and publically available with [Storybook 5.3.0](https://github.com/storybookjs/storybook/releases/tag/v5.3.0) release.

### CODE REVIEW

**Review by bradleyayers — APPROVED** [review]

**Review by Yama-Tomo — APPROVED** [review]
LGTM 👍

**Comment by SimenB** [comment]
`error Couldn't find package "storybook__addon-storyshots@*" required by "@types/storybook__addon-storyshots@^5.0.0" on the "npm" registry.`

**Comment by gaetanmaisse** [comment]
@SimenB it is surely related. As `@storybook/addon-storyshots` now exports its own types I removed the old and not up to date ones from DefinitelyTyped. You can either use the last version available on DefinitelyTyped i.e. `@types/storybook__addon-storyshots@5.1.2` or remove it completely and use types provided by the package itself.

**Comment by SimenB** [comment]
Installing it shouldn't error though, that's a bug

**Comment by gaetanmaisse** [comment]
Great, I'm not crazy, that's not the correct behavior. 
Not great, it looks like there is something broken for all scoped packages.

**Comment by SimenB** [comment]
@sandersn seems to be a bug in the publisher?

**Comment by sandersn** [comment]
Yep, looks like the publisher forgets to unmangle the name before adding the dependency.

The dependency is kind of bogus anyway -- it's a deprecated package!

**Comment by sandersn** [comment]
It should now be fixed for future deprecations; I didn't fix the 38 existing packages that the buggy code generated because (1) it's a royal pain (2) the workaround -- deleting the `@types/storybook__addon-storyshots` dependency -- seems easy. I'm happy to discuss whether I'm wrong about that.

**Comment by sandersn** [comment]
Never mind, I decided to fix them. The fixup script wasn't *that* hard to write...

**Pull request merged**
