### PR TITLE
[steam-tradeoffer-manager] fixing incorrect import as type, adding export of IEconService types

### PR DESCRIPTION
**Pull request by sentisso**
- fixing incorrect import as type
- adding a possibility to use the `IEconService` types outside of the type definitions via a namespace
- added some descriptive comments about the `IEconService` types from https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService

`import type MyType = require('module');` is not a valid way to import a CommonJS's export as a type, which even fails when compiled with typescript version `<= 4.1` with the following errors:
```
node_modules/@types/steam-tradeoffer-manager/index.d.ts:6:44 - error TS1370: Only ECMAScript imports may use 'import type'.

6 import type { EventEmitter } from 'events';
7 import type Steam = require('steam');
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/steam-tradeoffer-manager/index.d.ts:7:38 - error TS1370: Only ECMAScript imports may use 'import type'.

7 import type Steam = require('steam');
8 import type SteamID = require('steamid');
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/steam-tradeoffer-manager/index.d.ts:8:42 - error TS1370: Only ECMAScript imports may use 'import type'.

8 import type SteamID = require('steamid');
9 import type SteamUser = require('steam-user');
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`steam-user` has the same problem and has been discussed here #65127.
These types most likely copied the wrong way of importing from the `steam-user` types? Doesn't matter...

### DefinitelyTyped stuff

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by kldzj — APPROVED** [review]
Looks good to me, thank you very much!

**Comment by sentisso** [comment]
Ready to merge 🚀

**Comment by sentisso** [comment]
Damn, I just accidentally closed this PR...

**Comment by sentisso** [comment]
Ready to merge 2.0 🚀

**Review by kldzj — APPROVED** [review]
Still looking as good as before. Again, thank you very much! 😄

**Pull request merged**
