### PR TITLE
Turf - Fixed function names

### PR DESCRIPTION
**Pull request by DenisCarriere**
- `featurecollection` was changed to [`featureCollection`](http://turfjs.org/docs/#featurecollection)
- `linestring` was changed to [`lineString`](http://turfjs.org/docs/#linestring)

@gcroteau @tmcw

### CODE REVIEW

**Comment by tmcw** [comment]
Looks like this is still based off of the http://npmjs.org/turf package, which is at 3.0.14, not https://www.npmjs.com/package/@turf/turf which is the updated package, and which removes much of the surface area covered by this PR

**Comment by DenisCarriere** [comment]
@tmcw This Typescript definition hasn't been updated with all the new functions, we should update this definition to reflect the current Turf module.

I will help with the transition, however it's a lot of changes.

**Comment by DenisCarriere** [comment]
This PR was only to fix the `lineString` & `featureCollection` function name.

Installing a new install from NPM and using node to detect available functions.

```bash
$ npm install turf
$ node
> const turf = require('turf')
> turf.line
turf.lineDistance  turf.lineSlice     turf.lineString 
> turf.feature
turf.feature            turf.featureCollection 
```

**Comment by DenisCarriere** [comment]
Also removed deprecated Turf functions
- `aggregrate`
- `average`
- `count`
- `deviation`
- `max`
- `media`
- `min`
- `sum`
- `variance`
- `extent`
- `size`
- `merge`
- `filter`
- `remove`
- `jenks`
- `quantile`
- `reclass`

I've tested the `turf-test.ts` using Turf 3.0.14

**Comment by DenisCarriere** [comment]
@gcroteau Would it better to make two versions (2.0 & 3.0.14) for the Turf library? The difference between V2 & V3 is pretty drastic.

**Comment by DenisCarriere** [comment]
Reopened a new PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11123 and kept the old Turf 2.0 definition which was renamed `turf-2.0.d.ts` & `turf-2.0-tests.ts`.

**Pull request closed without merging**
