### PR TITLE
uuid: Revert "added uuid v5 to uuidStatic List (#20634)"

### PR DESCRIPTION
**Pull request by mattmccutchen**
This reverts commit ce9e109a99b10ed1235b53ed990b6088a4e9f531.

AFAICT, the `uuid` module never exported `v5`.  See
https://stackoverflow.com/questions/52048772 .

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.) (Consider [this](https://stackoverflow.com/questions/52048772) a test, even though it wasn't done by me.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.) (N/A: The removed functionality was untested.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kelektiv/node-uuid/blob/master/index.js (Look, v5 is not exported!)
- [X] Increase the version number in the header if appropriate. (Not applicable?)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (Already there)

### CODE REVIEW

**Comment by felipeochoa** [comment]
LGTM. [This comment](https://github.com/kelektiv/node-uuid/pull/188#issuecomment-300361574) talks about it

**Comment by cjbarth** [comment]
I'm not sure I understand why this is being removed as there seems to be support for it: https://github.com/kelektiv/node-uuid

**Comment by mattmccutchen** [comment]
@cjbarth `import { v5 } from "uuid"` never worked and was mistakenly added to the typings; that's what I'm reverting.  `import v5 from "uuid/v5"` does work and is still supported by the typings.

**Comment by cjbarth** [comment]
In that case: LGTM.

**Pull request merged**
