### PR TITLE
[relay-runtime] null fields are removed

### PR DESCRIPTION
**Pull request by maraisr**
In order to support https://github.com/facebook/relay/commit/3c701233f3794607f5cd168a258970880ee8ffa3

(also synced with all other missed types)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 14 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getPendingOperationsForFragment</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 86cd96869d22f194013b390ddd022c7fe70cd1ff
</p>

**Comment by maraisr** [comment]
@DangerBotOSS ill create a seperate PR with an alignment on those in a second moment, this PR is scoped purely to the nullability of metadata fields.

**Comment by amcasey** [comment]
@maraisr Because the types have been reordered, the diff is basically impossible to read.  Can you please provide an overview of the change?

**Comment by maraisr** [comment]
Ya, was a copy and paste of flow types converted to typescript, they are largely still ordered the same. I found them easy to follow. 

But ya for sure just check the corresponding flow types, and you'll be right.

**Review by amcasey — APPROVED** [review]

**Pull request merged**
