### PR TITLE
lodash: support strict function types

### LINKED ISSUE #21206: _.chain from `@types/lodash` is broken on Typescript 2.6
_.chain from `@types/lodash` is broken on Typescript 2.6

I have little knowledge of lodash internals, but the project that I'm working on uses it a lot. Using the new `@ts-ignore` silences the error, but I wanted to register it here.

### Reproducing:
install typescript ~2.6.0
`tsc -init`
`npm i lodash @types/lodash --save`
index.ts:
```ts
import * as _ from 'lodash'

var a = _.chain([1,2,3]).map((x) => { return x + 1 })

console.log(a.value())
```
run `tsc`

### Result:
```
index.ts(3,9): error TS2684: The 'this' context of type 'LoDashExplicitWrapper<number[]>' is not assignable to method's 'this' of type 'LoDashExplicitWrapper<ArrayLike<number> | Dictionary<number> | NumericDictionary<number> | null |...'.
  Types of property 'push' are incompatible.
    Type '<T>(this: _.LoDashExplicitWrapper<ArrayLike<T> | null | undefined>, ...items: T[]) => _.LoDashExp...' is not assignable to type '<T>(this: _.LoDashExplicitWrapper<ArrayLike<T> | null | undefined>, ...items: T[]) => _.LoDashExp...'. Two different types with this name exist, but they are unrelated.
      Type 'LoDashExplicitWrapper<number[]>' is not assignable to type 'LoDashExplicitWrapper<ArrayLike<number> | Dictionary<number> | NumericDictionary<number> | null |...'.
index.ts(3,31): error TS7006: Parameter 'x' implicitly has an 'any' type.
```

### Dependencies:

```
    "@types/lodash": "^4.14.80",
    "lodash": "^4.17.4"
```

@aj-r,  @thorn0, @andy-ms any ideas?

### PR DESCRIPTION
**Pull request by aj-r**
Fixes #21206.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [ ] Increase the version number in the header if appropriate. (not appropriate)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by aj-r** [comment]
@bczengel @chrootsu @stepancar @ericanderson @Ailrun @e-cloud @thorn0 @jtmthf - care to review this so we can properly support TS 2.6?

**Comment by thorn0** [comment]
I'll try to review it soon, but as it's pretty big. can you briefly explain how this change fixes the issue?
E.g. all these changes `ListIterateeBoolean<T>` -> `ListIterateeCustom<T, boolean>`, are they part of the fix or just a refactoring?

**Comment by aj-r** [comment]
@th0br0 sorry - that was just refactoring. I needed to add a new `ListIteratee` type that returned `PropertyName` (instead of `NotVoid`). I decided that instead of making many different `ListIteratee` types (`ListIteratee`, `ListIterateeBoolean`, `ListIterateePropertyName`), I would just make a generic version (`ListIterateeCustom`) that could return whatever value I want. So as a result, `ListIterateeBoolean` no longer exists (I use `ListIterateeCustom<T, boolean>` instead).

Some other notes:

- I needed to add special string overloads for some functions, because `strictFunctionTypes` does not allow us to assign `string` to `ArrayLike<string>` in a function parameter anymore.
- I also make some small changes to `conformsTo` and `toArray` to make the compiler happy. a return value of `TValue[keyof TValue]` drives typescript crazy when `strictFunctionTypes` are enabled, so I had to make some changes.
- I'm not sure where the `_.pick` functions came from. Maybe it was a merge issue - I'll fix it.

**Comment by thorn0** [comment]
> I needed to add special string overloads for some functions, because strictFunctionTypes does not allow us to assign string to ArrayLike<string> in a function parameter anymore.

It happens not only with strings. Strings are just one instance of the problem. Consider this code:
```ts
_.countBy([1, 2], (value, index, collection) => {
  console.log(collection.join(','));
  return value;
});
```
Similar to strings, `collection` should get the type `number[]` here, but it doesn't, so we can't call `join` on it. And if we add an annotation, the type of `value` becomes something crazy because the wrong overload gets used. I believe `ListIterator` should have one more type parameter for the collection type:
```ts
type ListIterator<T, TResult, TCollection extends ArrayLike<T>> = (
  value: T,
  index: number,
  collection: TCollection
) => TResult;

type ListIteratee<T, TCollection extends ArrayLike<T>> =
  | ListIterator<T, NotVoid, TCollection>
  | string
  | [string, any]
  | PartialDeep<T>;
```
So e.g. the definition of `countBy` would look like:
```ts
countBy<T, TCollection extends ArrayLike<T>>(
  collection: TCollection | null | undefined,
  iteratee?: ListIteratee<T, TCollection>
): Dictionary<number>;
```

**Comment by aj-r** [comment]
@thorn0 I tried something like that before, e.g.

```ts
countBy<T, TCollection extends ArrayLike<T>>(
  collection: TCollection | null | undefined,
  iteratee?: ListIteratee<T, TCollection>
): Dictionary<number>;
```

but it didn't work because typescript doesn't set the `T` constraint properly (it is always set to `{}`).

In this case we could try something like:

```ts
countBy<TCollection extends ArrayLike<T>>(
  collection: TCollection | null | undefined,
  iteratee?: ListIteratee<TCollection[0], TCollection>
): Dictionary<number>;
```

Hopefully that works. If not, We may need separate overloads for `T[]` and `ArrayLike<T>`.

**Comment by aj-r** [comment]
However fixing this issue will be a very big change - it will affect a large percentage of lodash functions. I vote we merge this PR as-is (assuming there are no other issues with it) and create a separate PR for the `T[]` vs `ArrayLike<T>` issue. That way we don't delay the fix for #21206.

**Comment by thorn0** [comment]
Ok, let's merge it and research that `TCollection` issue later.

**Review by thorn0 — APPROVED** [review]

**Comment by niieani** [comment]
Thank you! 🤝

**Pull request merged**
