### PR TITLE
update(cfn-response): v1.0 update and fix

### PR DESCRIPTION
**Pull request by arturovt**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://unpkg.com/browse/cfn-response@1.0.1/index.js

You can check the exported function by going to this URL. It doesn't have the `noEcho` argument and doesn't return a `Promise`.

### CODE REVIEW

**Comment by ivoisbelongtous** [comment]
`cfn-response` is actually a module that AWS CloudFormation injects itself rather than pulling from NPM: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html. The module on NPM is just a mirror of the AWS source code. In fact, the change to add `noEcho` has been copied over to the repository backing the NPM module, but the update was never published to the registry: https://github.com/LukeMizuhashi/cfn-response/blob/master/index.js#L11.

As for the `Promise<void>` return type, it was pointed out in #43128 that you will get code that accepts a `Promise` as a return type depending on the node runtime you use.

**Review by ivomurrell — COMMENTED** [review]
`cfn-response` is actually a module that AWS CloudFormation injects itself rather than pulling from NPM: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html. The module on NPM is just a mirror of the AWS source code. In fact, the change to add `noEcho` has been copied over to the repository backing the NPM module, but the update was never published to the registry: https://github.com/LukeMizuhashi/cfn-response/blob/master/index.js#L11.

As for the `Promise<void>` return type, it was pointed out in #43128 that you will get code that accepts a `Promise` as a return type depending on the node runtime you use.

**Comment by arturovt** [comment]
> `cfn-response` is actually a module that AWS CloudFormation injects itself rather than pulling from NPM: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html. The module on NPM is just a mirror of the AWS source code. In fact, the change to add `noEcho` has been copied over to the repository backing the NPM module, but the update was never published to the registry: https://github.com/LukeMizuhashi/cfn-response/blob/master/index.js#L11.
> 
> As for the `Promise<void>` return type, it was pointed out in #43128 that you will get code that accepts a `Promise` as a return type depending on the node runtime you use.

CloudFormation injects the `cfn-response.js` file only when using `ZipFile`. There is no `cfn-response` when the Lambda pulls the code from S3 buckets, thus it should be bundled along with Lambda code e.g. via Webpack.

**Comment by arturovt** [comment]
@ivoisbelongtous I've decided to check the comment in that PR link that you've provided:

> (unfortunately, the source code on that page is outdated and does not show the Promise being returned, however if you create an AWS Lambda function using AWS::Lambda::Function's ZipFile field with nodejs12.x as the runtime, you'll get a version of the code that returns Promise<void>)

I've created that stack on the fast hand:
```yml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 900
      Code:
        ZipFile: |
          const fs = require('fs');
          const response = require('cfn-response');

          console.log(
            fs.readFileSync('./cfn-response.js', 'utf-8')
          );

          exports.handler = (event, context, callback) => {
            const result = response.send(event, context, response.SUCCESS);
            console.log(result instanceof Promise);
            callback(null);
          };

  Custom:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt Lambda.Arn
```

This is the module source using the latest runtime:

image

The function doesn't return `Promise<void>`.

**Comment by arturovt** [comment]
But you're right regarding the `noEcho`. The question is then why the `cfn-response@1.0.1` (that is published to npm) doesn't contain the `noEcho` argument.

**Comment by ivoisbelongtous** [comment]
You're right about the function only returning `void`. Should have verified that myself previously. Let's change the return type then.

> But you're right regarding the `noEcho`. The question is then why the `cfn-response@1.0.1` (that is published to npm) doesn't contain the `noEcho` argument.

The library hasn't been maintained for years. They should have published a new version when they made the code changes but looks like they never did. Certainly don't want to treat it as anything but an unreliable mirror; the source of truth is the AWS documentation/pulling the source from CloudFormation as you did.

**Comment by arturovt** [comment]
I will restore the `noEcho` argument then.

**Comment by arturovt** [comment]
```ts
export type ResponseStatus = "SUCCESS" | "FAILED";
export const SUCCESS: ResponseStatus;
export const FAILED: ResponseStatus;
```

Do you think it also makes sense to remove the `ResponseStatus`? Because `const SUCCESS` is not type of `SUCCESS | FAILED`, it rather should be:
```ts
export const SUCCESS: 'SUCCESS';
export const FAILED: 'FAILED';
```

**Comment by ivoisbelongtous** [comment]
What would be the type of the `responseStatus` argument in `send` if we were to remove `ResponseStatus`? That's what it's defined for.

**Comment by arturovt** [comment]
> What would be the type of the `responseStatus` parameter in `send` if we were to remove `ResponseStatus`? That's what it's defined for.

```ts
export const SUCCESS: 'SUCCESS';
export const FAILED: 'FAILED';

export function send(
  responseStatus: typeof SUCCESS | typeof FAILED,
```

**Comment by ivoisbelongtous** [comment]
Can we instead have
```typescript
export const SUCCESS: 'SUCCESS';
export const FAILED: 'FAILED';
export type ResponseStatus = typeof SUCCESS | typeof FAILED;

export function send(
  responseStatus: ResponseStatus,
```
So that we get the specificity of your approach along with the clarity and reusability of the original.

**Comment by arturovt** [comment]
> Can we instead have
> 
> ```ts
> export const SUCCESS: 'SUCCESS';
> export const FAILED: 'FAILED';
> export type ResponseStatus = typeof SUCCESS | typeof FAILED;
> 
> export function send(
>   responseStatus: ResponseStatus,
> ```
> 
> So that we get the specificity of your approach along with the clarity and reusability of the original.

Of course, great!

**Review by ivomurrell — APPROVED** [review]

**Comment by arturovt** [comment]
Ready to merge

**Pull request merged**
