### PR TITLE
tabulator-tables: missing optional argument in row.getData()

### PR DESCRIPTION
**Pull request by germanfr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

https://github.com/olifolkerd/tabulator/blob/c81d881972d7fa1d125ed671b918aebe1e6d3449/src/js/core/row/Row.js#L294

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## tabulator-tables ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tabulator-tables@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'tabulator-tables'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ebca1eef7b6c3c5a713cd1f83613226c6de686e7
</p>

**Comment by Jojoshua** [comment]
@germanfr can you provide a link to the public api documentation for this?

**Comment by Jojoshua** [comment]
I could not find that being valid here http://tabulator.info/docs/5.1/components#component-calc

**Comment by germanfr** [comment]
@Jojoshua it's not documented (or I can't find it), but the functionality exists. Here is the method definition: https://github.com/olifolkerd/tabulator/blob/c81d881972d7fa1d125ed671b918aebe1e6d3449/src/js/core/row/Row.js#L294

You can call the function without parameters to get the raw data as it is in the cells, or with the transform parameter, and in that case Tabulator transforms the data with the accessor function before returning it.

**Comment by Jojoshua** [comment]
> @Jojoshua it's not documented (or I can't find it), but the functionality exists. Here is the method definition: https://github.com/olifolkerd/tabulator/blob/c81d881972d7fa1d125ed671b918aebe1e6d3449/src/js/core/row/Row.js#L294
> 
> You can call the function without parameters to get the raw data as it is in the cells, or with the transform parameter, and in that case Tabulator transforms the data with the accessor function before returning it.

Just because it works doesn't necessarily mean that it is meant for the public api and documented as such. Could you get concurrence from the library owner that it is part of the public api and forgot to document on the website?

**Review by Jojoshua — CHANGES_REQUESTED** [review]
Need public api documentation

**Comment by germanfr** [comment]
It's more or less documented here: http://tabulator.info/docs/5.0/mutators#accessors

> There are four options for accessor callbacks
> * **accessorData** - only called when data is extracted via a command {eg. getData).
> * **accessorDownload** - only called when data is being converted into a downloadable file.
> * **accessorClipboard** - only called when data is being copied into the clipboard.
> * **accessorPrint** - only called when data is being printed.
> * **accessorHtmlOutput** - only called when data is being turned into a HTML table for the getHtml function.
> * **accessor** - called if the matching accessor from the above list is not set.

The function `accessorData` and `accessor` are not called if the argument is not passed according to the code. There is no API documentation at the moment.

**Comment by germanfr** [comment]
Mentioning @olifolkerd if you could confirm this is not a bug.

**Comment by germanfr** [comment]
Also mention I've been using it like that all over my app before sending the data back to the server and it works just fine. It's now I decided to use the typed package that I'm getting the compiler error.

**Comment by germanfr** [comment]
Please @olifolkerd could you confirm if `cell.getData('data')` is part of the public API, even if an example of it does not appear in the documentation guides?

**Pull request closed without merging**
