### PR TITLE
Add `redux-devtools-extension` to notNeededPackages.

### PR DESCRIPTION
**Pull request by odensc**
Typings are included as of `v2.13.2`.

- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I am hesitant to do this. The `.d.ts` files contributed to `redux-devtools-extension` are worse in that they create global ambient module declarations (i.e. `declare module "redux-devtools-extension"`). Having multiple of these declarations around can potentially cause issues Can those be fixed up first?

**Comment by odensc** [comment]
Sure, I'll submit a PR for that and ping back.

**Comment by DanielRosenwasser** [comment]
Thanks a bunch! Sorry if this seems pedantic, I just want to set users on the path to the pit of success 😄

**Comment by odensc** [comment]
@DanielRosenwasser Actually, I don't see `declare module` anywhere, perhaps you're looking at an old version? https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/index.d.ts

Or are you referring to something else?

**Comment by DanielRosenwasser** [comment]
You are indeed correct, I couldn't find the file so I looked up the PR. My apologies!

**Pull request merged**
