### PR TITLE
[Luxon] Added DateTime.zone and Interval.mapEndpoints definitions

### PR DESCRIPTION
**Pull request by pietrovismara**
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
- [DateTime.zone](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-get-zone)
- [Interval.mapEndpoints](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#instance-method-mapEndpoints)

I also added a few query parameters for `node-geocoder`, that can be used with the `locationiq` provider:
[Documentation -> Query Parameters](https://locationiq.com/docs)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by mastermatt — CHANGES_REQUESTED** [review]
These were [added in v.1.10](https://github.com/moment/luxon/blob/master/changelog.md#1100) so the first line of `types/luxon/index.d.ts` needs to be updated.

Also the `node-geocoder` changes seem random. How are they related to this PR?

**Comment by pietrovismara** [comment]
@mastermatt updated the version line, thanks for the tip. Regarding `node-geocoder`, I squeezed those in because I thought since it's a small non breaking change it should not be a big deal. 

What should be the process otherwise? Should i wait for this PR to be merged and then create a new one?

**Comment by mastermatt** [comment]
@pietrovismara the `node-geocoder` don't seem to be blocked by the `luxon` changes. I'd just open a separate PR in parallel. 

Also can you prefix the title of this PR with "[luxon] " please. It just helps with folks that get pinged for a handful of different projects on DT.

**Comment by pietrovismara** [comment]
@mastermatt Removed `node-geocoder` changes and updated the title, we should be set!

**Review by mastermatt — APPROVED** [review]
Looks great. Thanks.

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by pietrovismara** [comment]
@DanielRosenwasser Thanks I rebased my commits, didn't notice it was the work account!

**Pull request merged**
