### PR TITLE
react-mixin

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by vvakame** [comment]
*react-mixin/react-mixin.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/react-mixin
  * http://bower.io/search/?q=react-mixin
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (react-mixin/react-mixin-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
wow, please wait.
related https://github.com/DefinitelyTyped/definition-tester/issues/11

**Comment by tkqubo** [comment]
@vvakame Oh, sorry I see.  I'll wait until the issue above has been fixed.

**Comment by vvakame** [comment]
thanks mate! now DefinitelyTyped support `.tsx`

**Comment by tkqubo** [comment]
Thanks for your quick response!

**Pull request merged**
