### PR TITLE
update french readme for definition owners

### PR DESCRIPTION
**Pull request by erwanjugand**
Update `Definition owners` for french readme

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. README.fr.md

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eccf146344946a56c6fccb771db36fa209740b4e
</p>

**Review by jakebailey — CHANGES_REQUESTED** [review]
Why is this PR both updating the French readme _and_ adding you as an owner to the chrome types?

Additionally, your only DT PR was #70514; the bar for adding people as owners is much higher than that, especially for an important package like `chrome`.

**Comment by erwanjugand** [comment]
Hello @jakebailey, I initially only wanted to make a PR to suggest myself as Owner for @types/chrome. But I saw that the French documentation for this is outdated. I can separate the PR if you want 😊

I have several PRs waiting for review concerning `chrome` and I think I can help follow this lib

**Comment by jakebailey** [comment]
Two separate PRs, please.

**Review by jakebailey — APPROVED** [review]

**Comment by erwanjugand** [comment]
Ready to merge

**Pull request merged**
