### PR TITLE
fix(formidable): attempt to amend changes from #51364

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- backward compatible creation exports
- restructure types for easier maintenance
- aliases (re)added

/cc @karlhorky

See: #51364
node-formidable/formidable#718

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by karlhorky** [comment]
@martin-badin @sandersn can you take a look at this and approve?

This fixes the types which were broken in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52697

**Review by sandersn — APPROVED** [review]

**Comment by Nemo108** [comment]
> @Nemo108

Wrong Nemo, dude

**Comment by peterblazejewicz** [comment]
@Nemo157

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Comment by karlhorky** [comment]
@peterblazejewicz I can confirm that the new version is working with the new API of Formidable (at least, the parts that we're using) 🙌

Thanks for this change! 👍

**Comment by karlhorky** [comment]
Seems like `formidable@2` just dropped 🙌

https://github.com/node-formidable/formidable/issues/718#issuecomment-955414974

**Comment by karlhorky** [comment]
It seems like @gboer has since opened a PR to `DefinitelyTyped` to add the types for `2.0.1` 👍 Thanks!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56925

**Pull request merged**
