### PR TITLE
Add types to `@types/qunit` that are needed for `ember-qunit`

### PR DESCRIPTION
**Pull request by gitKrystan**
Adds and fixes types used by `ember-qunit` in https://github.com/emberjs/ember-qunit/pull/994

Add optional `source` property to `Assert.pushResult` argument:
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/test.js#L572

Make `QUnit.config.testTimeout` optional:
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/test.js#L733
`ember-qunit` sets `testTimeout` to `null` in "dev mode." Additionally, code surrounding `testTimeout` seems to assume it can be something other than a number.

~Add `QUnit.config.timeout` type: https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/test.js#L752~

Add `QUnit.urlParams` type:
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/html-reporter/html.js#L256
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/test/reporter-urlparams.js#L11

Adds `Module` interface:
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/module.js#L45
I included only the properties needed for `ember-qunit` but left some commented out properties I discovered during my code reading but didn't need. Do you want to make any of these public?

Adds `Test` interface:
https://github.com/qunitjs/qunit/blob/fc278e8c0d7e90ec42e47b47eee1cc85c9a9efaf/src/test.js#L23
I included only the properties needed for `ember-qunit` but left some commented out properties I discovered during my code reading but didn't need. Do you want to make any of these public?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~

### CODE REVIEW

**Comment by gitKrystan** [comment]
> > ```diff
> > @@ -256,7 +256,7 @@ interface Config {
> > + timeout?: ReturnType<typeof setTimeout> | null;
> > ```
> 
> This is an internal undocumented property. I'd prefer we silence the use in ember-qunit for the time being instead of possibly encouraging use elsewhere by documenting it for TypeScript.

Sounds good. I removed it from this PR and updated my ember-qunit PR accordingly.

Any thoughts on the rest of the stuff? Specifically, is there anything else on the Test and Module interfaces you'd like to make public while I'm at it?

**Comment by Krinkle** [comment]
@gitKrystan Beyond what is on <https://api.qunitjs.com/extension/>, I'd consider the Module and Test objects fully internal. They're fairly stable, but to ease maintenance of the TS definitions I'd recommend against adding much detail here beyond that helps you right now.

**Review by Krinkle — APPROVED** [review]

**Comment by Krinkle** [comment]
@gitKrystan If you're interested, perhaps you'd like to look at adding `test.each()` to the TS defs next?

I have an old PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62328 but can't find the time to get it in mergable state. It's a relatively new and well-liked features, but lacking TS definitions at the moment.

**Comment by Krinkle** [comment]
Ready to merge

**Comment by sukima** [comment]
Hey everyone! it has been well over a year. What is blocking `QUnit.test.each()`? It is **very** unfortunate many developers are unable to use this feature in qunit.

**Pull request merged**
