### PR TITLE
fixed typing error & argument type error for THREE.js.

### PR DESCRIPTION
**Pull request by jcyuan**
@dhritzkiv here it is

### CODE REVIEW

**Review by dhritzkiv — COMMENTED** [review]
three js changes look good!

**Comment by dhritzkiv** [comment]
Ha - what I meant by opening two PRs was to only submit commits for one project at a time.

No matter: I’m sure someone will come along and approve the tweenjs changes as well

**Comment by dhritzkiv** [comment]
For other reviewers, see #25810 for previous PR

**Comment by jcyuan** [comment]
XD..   sorry I didnt realize that a new commit will be auto added to a created PR...

**Pull request merged**
