### PR TITLE
[@types/node] fix CryptoKey.usages

### PR DESCRIPTION
**Pull request by panva**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/webcrypto.html#cryptokeyusages

### CODE REVIEW

**Comment by panva** [comment]
CI failure is, once again, unrelated... sigh

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by peterblazejewicz** [comment]
@panva please update from master, to get CI passing after #61251

**Review by domdomegg — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by navya9singh — APPROVED** [review]

**Comment by panva** [comment]
Ready to merge

**Pull request merged**
