### PR TITLE
Added type definitions for module custom-error-generator

### PR DESCRIPTION
**Pull request by thmiceli**

### CODE REVIEW

**Comment by vvakame** [comment]
*custom-error-generator/custom-error-generator.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/custom-error-generator
  * http://bower.io/search/?q=custom-error-generator
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (custom-error-generator/custom-error-generator-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@thmiceli thank you for your contributions.
please rename custom-error-generator/custom-error-generator-test.ts to custom-error-generator/custom-error-generator-tests.ts

**Comment by thmiceli** [comment]
Sorry the misnaming. This is now fixed.

**Comment by vvakame** [comment]
@thmiceli thanks mate!

**Pull request merged**
