### PR TITLE
Update tmp to 0.1

### PR DESCRIPTION
**Pull request by pluma**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/raszi/node-tmp/blob/master/lib/tmp.js
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

-----

This adjust the typings for version 0.1.0 and changes the export to use a TS CommonJS export object instead of ES6 module export syntax.

### CODE REVIEW

**Comment by pluma** [comment]
This corrects some interfaces that were wonky before:

* synchronous dir results no longer have an "fd" attribute (which doesn't exist for dirs)
* removeCallback/name used everywhere instead of cleanupCallback/path for consistency
* the Options for files and dirs are actually different

**Comment by pluma** [comment]
Pinging @optical and @Perlmint because reformatting seems to have confused the bot.

**Comment by optical** [comment]
Hey @pluma. Looks like quite a big change and from what I can see it looks good, but unfortunately I haven't used `tmp` in years now and its been awhile since I wrote any meaningful type definitions or contributed to definitely typed. So I'll probably defer approving this to someone else more qualified

**Comment by pluma** [comment]
After some testing I've realised the CommonJS export style actually doesn't make all that much sense as the module doesn't really export anything but an object of functions. Sorry about that.

**Comment by pluma** [comment]
@optical that's fine.

From what I can see not much has actually changed in 0.1 although it's described as a breaking release. The existing typings already seem to be a bit off for 0.0 as the API documentation is a bit misleading. I dug through the actual implementation of 0.1 to figure out which options are actually supported by each method as it doesn't make sense to list things they don't actually use -- also directories don't return file descriptors, so that one was also wrong.

Most of the remaining changes are for consistency between names in the sync and async APIs (erring on the side of property names) and auto-formatting because I forgot to turn off prettier (with the default settings so hopefully this isn't considered gratuitous).

**Review by Perlmint — APPROVED** [review]
I just skimed this PR with code mentioned, It looks good.

**Comment by mceachen** [comment]
@pluma thanks for doing this refactor, but this PR requires all nontrivial consumers of `tmp` to change their code (replacing `Options` to some sub-variant). It would have been nice to try to maintain existing interface names. 

Again, thanks for doing this spring cleaning.

**Comment by pluma** [comment]
Sorry about that. At least 0.1 is a semver breaking release though, so hopefully this shouldn't catch anyone out of the blue if they're using semver ranges.

**Comment by pluma** [comment]
FWIW I think the only avoidable case was the rename from SimpleOptions to TmpNameOptions. All the other name changes were the result of disambiguations (i.e. one type being replaced by several distinct but mutually incompatible ones).

**Pull request merged**
