### PR TITLE
yargs: Add false to command description type

### PR DESCRIPTION
**Pull request by eseliger**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yargs/yargs/blob/master/docs/api.md#commandmodule as stated here, desc can either be a string, or false to mark it as a hidden command
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by eseliger** [comment]
Seems like the test is failing because of another reason. 
The tslint-disable statement seems to have been added before the check was added?

**Comment by poelstra** [comment]
Thanks for your work!

For some reason yargs typings updates always happen in pairs :wink: 

The change seems sensible, but given the broken build and a lot of other improvements to the typings in #21921, I suppose this change is better integrated into the latter, or re-applied on top of that later.

**Comment by JimiC** [comment]
@eseliger You can close this PR. We are going to address this on #21921.

**Comment by poelstra** [comment]
#21921 is merged and includes the changes of this PR, so this one can really be closed now.

**Pull request closed without merging**
