### PR TITLE
Angular Material - IToastPreset: add missing toastClass() method

### PR DESCRIPTION
**Pull request by christophercr**
A toast preset has also a toastClass() method which is currently missing in the IToastPreset.

### CODE REVIEW

**Comment by AlStar01** [comment]
👍

**Comment by zhengbli** [comment]
Can you point to the documentation that proves the change is correct?

**Comment by christophercr** [comment]
Oh I though I added it in the description, but apparently not :s

Anyway, this is it: https://material.angularjs.org/latest/api/service/$mdToast  in the $mdToast.simple();  method.

**Comment by AlStar01** [comment]
👍

**Pull request merged**
