### PR TITLE
[geojson] Bring type definition of Position more in to line with the official spec

### PR DESCRIPTION
**Pull request by smallsaucepan**
This PR aims to bring the definition of the geojson Position type more in to line with the [official spec](https://www.rfc-editor.org/rfc/rfc7946).

Rather than a Position being a number array of no particular size (including empty), the revised type mandates a minimum of two elements while allowing additional elements if desired. This seems to be the best trade off between strictness, and not limiting legacy implementations.

This change will allow GeoJSON types to be used without casting workarounds when using libraries that type their interfaces strictly. Libraries that only expect number[] should also be happy to accept the more exacting Position type.

Some notes:

This change _will_ cause type errors in client code where Position coordinates have simply be defined as number[] e.g.

```
const n: number[] = [1, 2]
function f(p: Position) {
  // whatever
}

// not happy
f(n)
```

Presuming the implementation adheres to the GeoJSON spec though and includes at least two elements at runtime, it should be safe to replace number[] with Position.

Due to the above this would be a major semver bump. While the current release helpfully defines the version as the same as the GeoJSON RFC (7946) incrementing to 7947 might prove confusing. So fast forwarding to 8000 for a clean break. Maybe I'm being pedantic though.

A few previous attempts to refine this type have fallen by the wayside. I think this approach addresses all the counter arguments and concerns raised previously. In the interests of rigour am including those below and tagging some people that may have a POV. Firmly believe this will improve the utility of the typedef and help produce more robust GeoJSON aware code.

Previous PRs

* #21590
* #60732

Discussions
* #56182
* #67773
* #58642

@michaeloliverx @oddvarogreid @thw0rted @DenisCarriere @tomwanzek @Ledragon @gustavderdrache

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: this PR, plus previous discussions 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by icholy — CHANGES_REQUESTED** [review]
This has been previously proposed and rejected https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60732

**Comment by thw0rted** [comment]
Per the discussion on https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58642 , the previous "owner" ( @JeffJacobson ) agreed that it's better to make correct types even at the expense of breaking consumer code that relied on the more-lenient (but less correct) versions.

Array destructuring is a common way to break out values from a fixed size tuple and it is better to be able to write

```ts
function midpoint([x,y,z]: Point) {
  if (null != z) {
    return [x/2, y/2, z/2]
  } else {
    return [x/2, y/2]
  }
}
```

rather than having to either add sanity-check/error-handling code you know will never be used (to convince the type-checker that x and y are always defined via control-flow analysis), or add non-null assertions everywhere you refer to the type.

You ask what the case is for making the types correct; I would argue that if anyone should be required to defend a position, it should be the one trying to keep the types inaccurate -- "consumers will have to fix their also-incorrect code" is not a compelling reason.

**Comment by icholy** [comment]
>  "consumers will have to fix their also-incorrect code" is not a compelling reason.

Yes it is. Your OCD on the other hand is not a compelling reason to break everyone's code.

**Comment by smallsaucepan** [comment]
Thanks for responding @icholy.

I have read #60732 and I don't believe the objections are justified. They mostly seem to boil down to whether this is worth doing, and I believe it is.

> break everyone's code

Simply not true. If I decide to opt in to a major version upgrade, Typescript will _show me where my code might break at runtime_, and I can fix it if I wish. That's the whole point of Typescript - to provide a safety net and avoid making preventable mistakes.

> This isn't worth changing

With all due respect, it's not up to you to assess how important type safety is to my code. Pretty sure it would be "worth it" to someone who uncovers or avoids a defect because the types were more strict. What's the point of publishing types that could, but don't, accurately reflect the spec?

I read through the history, prepared a PR with good intent, and hoped to discuss it on its merits. Instead I see people being dismissed as having OCD, a debilitating mental disorder.

I just do not understand the aggression towards people trying to help improve this module. No one is expecting you to take responsibility for all the code ever written that uses these types. All anyone is asking is for you to be custodians of the closest possible match to the GeoJSON spec, and leave any decisions after that to the users.

**Comment by icholy** [comment]
Nothing has changed since the last time this debate happened. As such, I'm not interested in having it again.

**Comment by smallsaucepan** [comment]
Of course, that's totally up to you. I understand.

I'm leaving the PR open though as that previous debate didn't actually resolve anything, and the leniency of the current type isn't in the best interests of users. If one of the other maintainers is interested enough to listen to a different point of view, I'll be happy to work through it with them.

**Comment by thw0rted** [comment]
Looking at the owners for these types, @Cobster and @atd-schubert have not been active on GH for years, and @JeffJacobson has said previously that he is no longer involved in this domain.  That leaves @danvk as the only other listed owner who might have a differing opinion about publishing more-correct (vs less-breaking) types here.

As an aside: I wonder what DT is "supposed" to do when this package (with 4M+ weekly downloads!) doesn't actually describe the types for https://www.npmjs.com/package/geojson , or indeed any client-side code at all?  The only thing I could find in the DT guidelines about it is this (from [the "Naming" section](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master?tab=readme-ov-file#naming) ):

> In rare occasions, `nonNpm` may be set to `"conflict"`, which indicates that there is a package on npm with the same name, but the types intentionally conflict with that package. This can be true for packages which define an environment like `@types/node` or for dummy packages like `aws-lambda`. **Avoid using `"conflict"` where possible**

(Emphasis mine)

But the package is already here, and already "conflicts" with the matching package.  And because it's a type-only package, the semver doesn't even make sense.

Maybe the best solution is to spin up a new fork of these types, using real semver (1.x on release, 2.x for a breaking update), with maintainers who care about correctness, and try to convince consumers to switch?

**Comment by danvk** [comment]
I'll chime in with more thoughts on this change when I find time, but for now I just want to encourage everyone to keep the conversation civil. Concrete examples of wins and losses are helpful. Speculation about motivations and psychological conditions is not.

**Comment by icholy** [comment]
Don't $&#@&# break people's code. Incrementing the major version doesn't make it ok. If you don't understand why, google "diamond dependency problem". If we were writing these from scratch, then I'd have no problems with the proposed method (it's a clear improvement), but you need weigh the pros and cons. A marginal improvment in type safety doesn't justify the pain this will cause.

**Comment by smallsaucepan** [comment]
Concrete examples as requested:

* polygon-clipping library base level coordinate pair - [Pair](https://github.com/mfogel/polygon-clipping/blob/82b0ac2c35304bfea9cac24eabcbda32a808ee55/src/polygon-clipping.d.ts#L2) - defined as `[number, number]`. Can't pass Positions or derivatives as args without casting first
* polyclip-ts more or less [same as above](https://github.com/luizbarboza/polyclip-ts/blob/ea8a46848435b69aa6d25a59eaffe7d96d348d48/src/geom-in.ts#L7)
* d3-geo [expects points as [number, number]](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5be58a75483be41164b64f7bf57d7d57e1460a93/types/d3-geo/index.d.ts#L132). Casting required to accept a number[] like Position
* Unable to pass Position as "[LatLonLike](https://github.com/mapbox/mapbox-gl-js/blob/bfb0a2050e6cc8fa068809f9b77c1965b1d9e5fb/src/types/point-like.ts#L3)" in mapbox-gl. ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f12705b83b35eb0c9c96aaf6211113431738022a#r30900787))
* Position not compatible with leaflet [coordsToLatLng](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5be58a75483be41164b64f7bf57d7d57e1460a93/types/leaflet/index.d.ts#L2339) ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f12705b83b35eb0c9c96aaf6211113431738022a#r36187090))

**Comment by JeffJacobson** [comment]
@smallsaucepan, I just gave up on trying to update @types/geojson and now I just create my own interfaces in my projects. If you can't work things out, you can actually configure TypeScript to get types from other packages besides the "@types/..." ones. So you could create your own NPM project and define the types however you want them.

Some suggested compromises:

- Add additional "Strict" interfaces. 
    Before I gave up, I started a fork where I began to add [alternate "Strict..." interfaces & types](https://github.com/JeffJacobson/DefinitelyTyped/blob/strict-geojson/types/geojson/index.d.ts). I had to stop due to other work that has taken priority over this, and it was easier to just add my own GeoJson interfaces to my TypeScript projects than to this one updated.
- Create a completely new type definition called something like `geojson-rfc-7946` or `geojson-strict`.

**Comment by danvk** [comment]
@smallsaucepan thanks for the concrete examples. Unfortunately, this PR would not fix any of them because `[number, number, ...number[]]` is not assignable to `[number, number]`:

```ts
type Position = [number, number, ...number[]];
function process(point: [number, number]) {}

declare let pt: Position;
process(pt);
//      ~~ Argument of type 'Position' is not assignable to parameter of type '[number, number]'.
//           Target allows only 2 element(s) but source may have more.
```

([playground])

`[number, number, ...number[]]` is _also_ not assignable to `[number, number] | [number, number, number]`, so unless an existing library is specifically expecting `[number, number, ...number[]]`, then this is not a justification for this PR.

Regarding destructuring assignment, this PR would make pulling out lng/lat from a `Position` easier only if you have `noUncheckedIndexedAccess` enabled:

```ts
declare const position: number[]
const [lng, lat] = position;
//     ^? const lng: number
//                   number | undefined (with noUncheckedIndexedAccess)
```

This PR would also force you to consider that a third element might be `undefined`, even without `noUncheckedIndexedAccess`. That's a good thing. But my sense is that it's pretty rare for projects to use `noUncheckedIndexedAccess`, and it's also rare for GeoJSON positions to have a third element. For the most part, the status quo works fine.

If anyone is generating validation code using `@types/geojson`, this this change will result in more precise validation. But why not use the [official schema] instead?

There are simple examples of correct code that would break with this change, for example https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60732#issuecomment-1152942293.

But my big fear in making a change like this is that we'll fragment the ecosystem of projects that depend on `@types/geojson`. npm lists [517 published packages] that depend on these types, and presumably there are many private packages as well. If we publish a major new version and some subset of these adopt it (which will presumably be the case for many years), then they'll become incompatible with each other. A `Position`, `Geometry` and `Feature` produced by a library on the old `@types/geojson` won't be compatible with the types expected by a library on the new `@types/geojson`. Users will get lots of cryptic, spurious errors, without an obvious resolution.

(Caveat: this is how npm would model things at runtime, but I'm not 100% sure this is how TypeScript would treat `@types` at type checking time. If anyone knows better or can run an experiment, that would be helpful.)

Assuming that's correct, I'm 👎 on this change.

I'm 👍 on a comment in the types explaining why `Point` doesn't precisely match the spec and linking to this PR.

No one can stop you from forking `@types/geojson`. It is admittedly weird that the TypeScript types for this spec live on DT, and a fork would fix that. But if other projects start depending on the fork, then we'll run into the same fragmentation issue.

[playground]: https://www.typescriptlang.org/play/?&noUncheckedIndexedAccess=true#code/C4TwDgpgBACg9gZwJbCXAdlAvFA2ugVwFsAjCAJwBopDSLqA6J2s83AXXYG4AoAMwLoAxqgxQw5OEIgIEACjBwk6YAC48LejWKt2ASigBvAL48eAEwhCANgENy0axGDi1sRCjTpeEqTPlgwHq8APQhUBGRAH5RUACC5ADmxBAqUHB8UKCQUADk8Mii6LlQSAg0cC62skiJ6LYkTllw4va2RM4U6ZnZ0Ln4Olqa5Oy5DDxhkVNTACr2ic5QttbWcADu5RjWIFAATFAQTh0qcggGJAQuCHAE5NJQRLY7ABa2AG7QRHAO40A
[517 published packages]: https://www.npmjs.com/package/@types/geojson?activeTab=dependents
[official schema]: https://github.com/geojson/schema

**Comment by smallsaucepan** [comment]
Thanks for critiquing the PR on its merits @danvk.

> `[number, number, ...number[]]` is not assignable to `[number, number]`

Good point, and obvious in hind sight. That's on me for not working through that side of it more rigourously.

It sounds like there is no way to provide a useful and strict type for a spec that allows for a potentially unlimited number of co-ordinate entries. It's an unfortunate limitation of the spec being a bit open ended in that one place.

> If we publish a major new version and some subset of these adopt it (which will presumably be the case for many years), then they'll become incompatible with each other.

While I understand this rationale, I don't find it as compelling. Letting a flaw propagate indefinitely because it's hard to fix _now_ isn't being fair on future devs. Idealistic sure. Though that strictness is why I use TS in the first place. As mentioned above though, maybe this is as good as it ever could be.

> I'm 👍 on a comment in the types explaining why Point doesn't precisely match the spec and linking to this PR.

Will do this, and remove some notes that are causing confusion.

> No one can stop you from forking @types/geojson. It is admittedly weird that the TypeScript types for this spec live on DT, and a fork would fix that. But if other projects start depending on the fork, then we'll run into the same fragmentation issue.

I will look into this some more, taking on board what you've mentioned about destructuring, etc.

Thanks again.

**Comment by JeffJacobson** [comment]
> It is admittedly weird that the TypeScript types for this spec live on DT, and a fork would fix that. But if other projects start depending on the fork, then we'll run into the same fragmentation issue.

GeoJSON itself isn't a library where a type definition could be included, and DT seems to be the de facto source for TypeScript typings. So it makes sense to me for it to be in DT. (Maybe I'm misunderstanding the purpose of DT.)

**Pull request closed without merging**
