### PR TITLE
Add typings for raygun4js

### PR DESCRIPTION
**Pull request by xt0rted**
These are based on the [documentation](https://raygun.io/docs/languages/javascript) and [source](https://github.com/MindscapeHQ/raygun4js/blob/c7d8880045214ab6d403d5cc613c207f696a3cdd/src/raygun.js) for this version.

### CODE REVIEW

**Comment by vvakame** [comment]
*raygun4js/raygun4js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/raygun4js
  * http://bower.io/search/?q=raygun4js
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (raygun4js/raygun4js-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@xt0rted thank you for your contributions.
please rename raygun4js/raygun4j-tests.ts to raygun4js/raygun4js-tests.ts.

**Comment by xt0rted** [comment]
@vvakame the file name is fixed

raygun4js is also on [NuGet](https://www.nuget.org/packages/raygun4js/) with the same name

**Comment by vvakame** [comment]
@xt0rted thanks mate!

**Pull request merged**
