### PR TITLE
fix: update @types/jest dependencies

### PR DESCRIPTION
**Pull request by SimenB**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I just made this change in the GH UI, hopefully it'll pass 🙂

### CODE REVIEW

**Comment by ExE-Boss** [comment]
@SimenB See <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45603> and <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47545>.

**Comment by SimenB** [comment]
wonderful 😛 I'm not gonna dig into that, so I'll just close this

**Comment by G-Rath** [comment]
I'm thinking it's probably just time to make the min ts version for `@types/jest` & dependents 3.8:

```
3.1 expect-puppeteer
3.5 heft-jest
3.1 jest-axe
3.4 jest-expect-message
3.1 jest-image-snapshot
3.1 jest-image-snapshot/v2
3.1 jest-in-case
3.1 jest-json-schema
3.1 jest-matcher-one-of
3.1 jest-plugin-context
3.8 jest-sinon
3.1 jest-specific-snapshot
3.1 jest-when
3.1 testing-library__jest-dom
3.1 wordpress__jest-console
```

While breaking, I don't think we could attempt to do this in a major due to the downstream types, and also I don't think it'll be as negative as it may seem, since:
  * if you're using <   jest 26 then you shouldn't be using `@types/jest@26` so you wouldn't be affected
  * if you're using >= jest 26 then you're currently consuming some jest 24 types, which is wrong anyway, so the act of upgrading the dependencies in theory would cause breakages
  * if you can't upgrade typescript then you can stay on the current version of the types you're using - while not ideal, typescript will need to be updated at some point anyway

@ExE-Boss @L2jLiga what do you think? The best way to go about this is probably to make a PR against each of the above packages bumping their min ts version to 3.8, and then we'll be able to bump `@types/jest` & the dependencies.

**Comment by SimenB** [comment]
My hope for `@types/jest` is still #44365, but if just tweaking the minimum TS version brings us closer, that makes me happy! 😀

**Comment by G-Rath** [comment]
@SimenB yeah this'll be one of the requirements for landing #44365, so we need to do this at some point - 3.8 becomes the min supported by DT in 2022, so it'll happen eventually... provided that jest doesn't bump their min.

All the more reason I think that we should force downstream types to match jest's min, and then ensure they're updated whenever jest ups its min.

**Pull request closed without merging**
