### PR TITLE
Update definitions for Handsontable

### PR DESCRIPTION
**Pull request by mrpiotr-dev**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://docs.handsontable.com .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
@swistach sorry! DT member do `push -f` to master branch inadvertently.
your previous pull request are recovered now.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/handsontable

We use this feature now. https://help.github.com/articles/about-protected-branches/

**Comment by swistach** [comment]
Hi @vvakame,
thanks for info, but i've added the update definitions in this pull request.
When can we expect the merge?

**Comment by vvakame** [comment]
@swistach oh, please resolve conflict.

**Comment by swistach** [comment]
@vvakame sorry, i didn't notice the conflict. Fixes sent.

**Comment by vvakame** [comment]
:+1:

**Comment by dcsan** [comment]
adding a comment to this rather than just another issue in the repo... is that OK?

cc @swistach @vvakame よろしくお願いします！

[~/dev/rikai/boteditor]$ tsc 
public/components/training.ts(69,7): error TS2345: Argument of type '{ data: any; minSpareRows: number; rowHeaders: boolean; dropdownMenu: boolean; colHeaders: string...' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'afterChange' does not exist in type 'Options'.

from here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/handsontable/handsontable.d.ts

as pointed out in this discussion
https://github.com/typings/typings/issues/485#issuecomment-217661014

**Comment by dcsan** [comment]
can i fork that file and just add a single 

    afterChange?: any[];

? not sure if its that simple a fix..

**Comment by horiuchi** [comment]
@dcsan Please create new pull request for adding missing line on `handsontable.d.ts`.

**Pull request merged**
