### PR TITLE
[react] Add `value` attribute to `data` element

### PR DESCRIPTION
**Pull request by dosentmatter**
`<data>` should include `value` attribute in addition to the global
attributes:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data#Attributes

Also add `HTMLDataElement` to global.d.ts

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data#Attributes
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by dosentmatter** [comment]
Hmm, it failed travis-ci but it looks like it was caused by dependent packages:

```
Error in baseui
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/baseui/baseui-tests.tsx:422:1
...
Error in react-intl-redux
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-intl-redux/react-intl-redux-tests.tsx:17:5
...
Error in react-scroll-into-view-if-needed
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-scroll-into-view-if-needed/react-scroll-into-view-if-needed-tests.tsx:29:5
...
Error in redux-devtools
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/redux-devtools/redux-devtools-tests.tsx:27:7
...
Error in styled-components
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/styled-components/test/index.tsx:897:5
```

**Comment by ferdaber** [comment]
Should `value` always be a `string` or `number`? Doesn't the DOM stringify any value that is passed in?

**Comment by dosentmatter** [comment]
@ferdaber, I don't know if the DOM or React the the stringification, but I know if you do `<data value={398}>Mini Ketchup</data>` in React, it will become `<data value="398">Mini Ketchup</data>` in the DOM.

The spec says [`data.value` is `[CEReactions] attribute DOMString value;`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-data-element). The description just says ["machine-readable translation of the content of the element"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data).
Compare that with `[input.value - \[CEReactions\] attribute \[TreatNullAs=EmptyString\] DOMString value;](https://html.spec.whatwg.org/multipage/input.html#the-input-element).

I actually just copied the type definition from [`InputHTMLAttributes`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1974).

Another thing is that if only numbers were allowed it would be like [`img.height` - `[CEReactions] attribute unsigned long height;`](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element)

**Comment by dosentmatter** [comment]
Please do not close yet. I think the errors are existing errors and are not caused by my changes.

**Review by ferdaber — APPROVED** [review]

**Pull request closed without merging**
