### PR TITLE
JQuery .val(value)

### PR DESCRIPTION
**Pull request by yardee**
Added possiblity to add number or number[] to .val(value), based on JQuery docs

### CODE REVIEW

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
According to http://api.jquery.com/val/#val2 `string|string[]|number` are supported but not `number[]`:

> A string of text, a number, or an array of strings corresponding to the value of each matched element to set as selected/checked.

Could you remove `number[]` from your PR and we can merge just the `number` change to the union type?

Thanks.

**Comment by yardee** [comment]
Soory for mistake, fixed.

**Comment by johnnyreilly** [comment]
Looks good - thanks!

**Pull request merged**
