### PR TITLE
[@onfleet/node-onfleet] Add missing fields to Tasks and make some completionDetails fields optional

### PR DESCRIPTION
**Pull request by neilpoulin**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.onfleet.com/reference/webhook-payload-examples
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by neilpoulin** [comment]
hey @marcobeltempo  any chance you can review this PR so i can get the type definitions fixed? I also noticed there are a few methods that the Onfleet sdk now supports that aren't represented in the type definitinos, particularly get assigned tasks for a worker `workers.getTasks(id: string)`

**Review by saladin-uzh — APPROVED** [review]

**Review by saladin-uzh — APPROVED** [review]

**Comment by marcobeltempo** [comment]
Thanks for the contribution @neilpoulin. Everything LGTM 👍🏼

**Comment by neilpoulin** [comment]
thanks everyone. i would like to continue making more updates to these types so expect some more PRs soon. There are some new fields/methods that onfleet has added support for that i'm using in my project.

**Comment by neilpoulin** [comment]
ready to merge

**Pull request closed without merging**
