### PR TITLE
Update hapi.d.ts

### PR DESCRIPTION
**Pull request by JakubJagoda**
Various changes updating Hapi's API to the newest version. Includes changes from following commits:
https://github.com/hapijs/hapi/commit/df6fffd4acafafc99fb5534e9c4f274a72994b95, closing https://github.com/hapijs/hapi/issues/3002
https://github.com/hapijs/hapi/commit/4e78875d30a458d835520a8614e2e43f2137f1e1, closing hapijs/hapi#3018
https://github.com/hapijs/hapi/commit/ee1fd9d4f1b4fb71aa70fee12cbc566bfbc5d47a, closing hapijs/hapi#3000
https://github.com/hapijs/hapi/commit/26a9697d7ee532ec66cfb67f4fb843c0ecb27a95, closing hapijs/hapi#2998
https://github.com/hapijs/hapi/commit/e724897cc9339935d8900fc2c1ef073eef046d9d, closing hapijs/hapi#2936
https://github.com/hapijs/hapi/commit/94085098afd2f09490ef9a1276b722a9a1231a24, closing hapijs/hapi#2928

### CODE REVIEW

**Comment by jasonswearingen** [comment]
looks like a great update!

:+1:

**Comment by JakubJagoda** [comment]
Nice to hear that @jasonswearingen. Are the added declarations ok? I only wasn't 100% sure if it is fine to use intersection type in functions that might return either nothing or a promise (depending on callback argument presence). Another question, what about file versioning? Should I only update the header of the existing file or should I also create a separate `hapi-12.0.1.d.ts` file for the previous (before this PR) version?

**Comment by jasonswearingen** [comment]
use of intersection types is fine for me, as I can't see any reason people would be on an old version of typescript (i had no upgrade problems and never saw anything serious holding anyone back)  keep in mind that some tooling (like the browserify tsify plugin) doesn't like intersection types because they use old versions, but thankfully that doesn't matter for d.ts files as they are not consumed by tools like tsify.

regarding versioning, I think we should keep the ```hapi.d.ts``` as up-to-date as possible, so feel free to update the header.  If you want to have a definition locked to a very specific hapi version, I do think that  making a new file such as ```hapi-12.0.1.d.ts``` is the right path to take.   But, very little changes across hapi versions, and mostly people can use the same latest definition for old version of hapi.   The only conflict I ever ran into is when (around v9.x) they stopped shipping some plugins by default (like the ```inert``` and ```h2o2``` modules)

**Comment by JakubJagoda** [comment]
@jasonswearingen my question about intersection types was concerning the _conceptual_ usage of them rather than what you mentioned (to be honest I didn't even think about it, my thought was exactly the same, i.e "I can't see any reason people would be on an old version of typescript"). Conceptually intersection type represents a type that is **both** of type A and B and resulting type consinst of properties of both types. Union type (a type that is **either** type A or B) would fit better here, but in order to properly use it you need to use type guards or explicit type casting. So either:
- I can keep the current typing, which feels wrong conceptually, but allows you to easily write
```ts
server.start().then(...)
```
- or I can change it to union type `IPromise<something>|something` which feels better, but then it needs to be written like below :
```ts
(<IPromise<something>>server.start()).then(...);
```
What do you think?

**Comment by jasonswearingen** [comment]
@JakubJagoda  I see what you mean.    Sorry I didn't see it in the commit with all the other changes.

Maybe there's an example where it could make sense, but for ```.stop()``` and ```.start()``` and ```initialize()``` it's certainly not needed to return ```IPromise<void>&void```    instead you can just return ```IPromise<void>```  no union or intersection is at all required. 

In general I think unions are better unless there is an actual mixin occuring, otherwise it will produce invalid typings.

**Comment by JakubJagoda** [comment]
@jasonswearingen agreed. I changed that and updated the header.

**Comment by jasonswearingen** [comment]
:+1:

**Pull request merged**
