### PR TITLE
Uses "export default" syntax.

### PR DESCRIPTION
**Pull request by ryasmi**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by ryansmith94** [comment]
I need some input on this. Happy to fix the problems raised by Travis.

**Comment by vvakame** [comment]
Is this PR same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9020#issuecomment-211047386 ?

**Comment by ryansmith94** [comment]
I don't think so @vvakame, because Knex is actually a function and they use [`module.exports =`](https://github.com/tgriesser/knex/blob/master/src/index.js#L62).

**Comment by vvakame** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9019#issuecomment-211058255

**Comment by ryansmith94** [comment]
See [#9019 comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9019#issuecomment-213773775)

**Comment by tkqubo** [comment]
Sorry I'm not familiar with the specification of `default`, but does it behave differently depending on the exported module is a function or an object?

I think babel transpiles `default` as you expected, whereas TypeScript doesn't, which would cause run-time error with new knex typings.

**Comment by ryansmith94** [comment]
> Sorry I'm not familiar with the specification of default, but does it behave differently depending on the exported module is a function or an object?

I think if you did `module.exports = a` where `a` is an object like `{b: c}`, it would be the equivalent of `export b = c;`.

> I think babel transpiles default as you expected, whereas TypeScript doesn't, which would cause run-time error with new knex typings.

If that's true then that makes some sense as I'm currently hitting this error by compiling TypeScript to ES6 and then using Babel to convert that to ES5 because I'm using Async/Await.

**Comment by ryansmith94** [comment]
Closing because of inactivity

**Pull request closed without merging**
