### PR TITLE
[@types/chai] Improve chai definition to version 4.1

### PR DESCRIPTION
**Pull request by micksatana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Solve #22402

### CODE REVIEW

**Comment by micksatana** [comment]
The build fail caused by an unrelated module named `hexo-fs` with Error `no-unnecessary-type-assertion`. I'll close and open this PR to trigger Travis to re-run.

**Comment by micksatana** [comment]
Merge from latest master wasn't work. So I added `no-unnecessary-type-assertion` as false in `hexo-fs` as a quick fix.

If this is not correct, kindly point out the problem and solution.

**Comment by segayuu** [comment]
Hi @micksatana 
It is possible to modify the lint rule that is in violation, but, currently I can not make suggestions for corrections to this PR with a pull request.
Is `Allow edits from maintainers` enabled for this pull request option?
If you continue to do so, you can only make correction requests by sending comment text.
I would be happy if you can check it :)

**Comment by micksatana** [comment]
Thank you for quick reply  :)

> Is Allow edits from maintainers enabled for this pull request option?
Yes, it's enabled. But I can't assign a reviewer directly, it's default to `@types/chai` author.

**Comment by segayuu** [comment]
OK, [please confirm the difference of this commit page](https://github.com/segayuu/DefinitelyTyped/commit/1b7b0fe8462daa6a30efddb6d12538eb0bfcef72).
I think Travis build test will pass by this fix.

**Comment by micksatana** [comment]
Passed! Thank you very much. I really appreciate your help.

**Comment by micksatana** [comment]
Resolved conflict

**Pull request merged**
