### PR TITLE
Implementation of gapi.analytics namespace

### PR DESCRIPTION
**Pull request by gatsbimantico**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@gatsbimantico can you please update the header for the file.

**Comment by jramsay** [comment]
@gatsbimantico :  Thanks for your contribution! Can you please fix the failing Travis CI tests and update the PR.

**Comment by gatsbimantico** [comment]
Hi, I'm new at this. Thank you for your feedback.

@mhegazy I updated the header 👍 Sorry, I didn't understood what you meant.

@jramsay Checked.

Why dt-bot says that is not correct naming convention? Can I fix that?

**Comment by yuit** [comment]
thank you the PR @gatsbimantico

**Pull request merged**
