### PR TITLE
TopoJSON: Improve types

### PR DESCRIPTION
**Pull request by denisname**
Improve types for `topojson` library: remove all `any`, add tests and activate `StrictNullChecks`.

@tomwanzek: Should we not add TopoJSON to the ["D3 - Outside of core team maintenance"](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23611) list? Same question for [d3-hcg](https://github.com/d3/d3-hcg), [d3-geo-projection](https://github.com/d3/d3-geo-projection), [d3-geo-polygon](https://github.com/d3/d3-geo-polygon), [d3-tile](https://github.com/d3/d3-tile).

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [The TopoJSON Format Specification](https://github.com/topojson/topojson-specification/blob/master/README.md)
  - [TopoJSON](https://github.com/topojson/topojson/blob/master/README.md)
  - [TopoJSON Server](https://github.com/topojson/topojson-server/blob/master/README.md)
  - [TopoJSON Simplify](https://github.com/topojson/topojson-simplify/blob/master/README.md)
  - [TopoJSON Client](https://github.com/topojson/topojson-client/blob/master/README.md)
  - [U.S. Atlas TopoJSON](https://github.com/topojson/us-atlas)
  - [World Atlas TopoJSON](https://github.com/topojson/world-atlas)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@denisname 

> Should we not add TopoJSON to the "D3 - Outside of core team maintenance" list? Same question for d3-hcg, d3-geo-projection, d3-geo-polygon, d3-tile.

I think, the general inclusion threshold for tracking the definitions in the issue you referenced should be defined as:
* the source repo is part of the `d3` organization
* not flagged as `deprecated`
* a D3 version 4+ repo

So the "d3-xxx" repos, you listed can indeed be added, based at a quick first glance.
While `topojson` is not in the `d3` org, one could make a judicious :wink: exception for it given its author and use case link to `d3-geo`.

I just don't want the scope of tracking/management to become too unwieldy.

So I will review them for status and add them (but purely for an initial tracking at this point, no intent on my part to review/PR). The reason I listed **d3-hsv** as outside the "core team", was not to loose sight of it, without devoting cycles on assuming maintenance responsibilities.

This, of course does not mean that the "core team" (which currently I would consider to be @gustavderdrache and @Ledragon, who have earned frequent flyer miles/their stripes 🏅 , and myself), could not expand in the future.

Scope management is your friend 🕺

**Comment by denisname** [comment]
OK as you want. I was not sure if they missed voluntarily or by mistake.

**Comment by tomwanzek** [comment]
@denisname To be clear: any addition of people who want to routinely contribute to the **d3-xxx** definitions is welcome. Shared burden :smile: Historically, most people simply tend to be more event-driven, one-time contributors of issues/PRs. So, technically, the D3-related tracking issue #23611 deserves a "Help Wanted" tag in this sense.

**Comment by ricardo-mello** [comment]
I agree with @tomwanzek. 

I'm sorry, but as I don't use d3 frequently is a quite difficult to routinely contribute, because I don't know what the community needs. My first commit was just a starting point, with the intention to share a solution that I found to a problem that a friend of mine had when testing **topojson** on Angular 😅

**Review by ricmello — APPROVED** [review]
Great job!

**Comment by denisname** [comment]
@tomwanzek
I am also working on d3-axis and d3-format. And after I will go fo d3-array. I have some questions...

In d3-format I want to use the same `Numeric` interface than in d3-array:

```typescript
interface Numeric {
    valueOf(): number;
}
```

But when doing this, in the d3 global definitions, I logically have the error: `Module 'd3-array' has already exported a member named 'Numeric'`. Is there a place to put shared types for d3 libraries?

Also in some d3 definitions (interpolate, scale, shape) you can find the union type `number | { valueOf(): number }`. Is `{ valueOf(): number }` not enough?

**Comment by tomwanzek** [comment]
@denisname I would suggest keeping this PR thread focused on topojson.

I am assuming, you are referring to the Technical Debt Reduction/Refinement Issue #23611. Thanks in advance for taking on the mentioned modules 🌞 So, if you could kindly re-post your intent to volunteer and related questions there, then we are more in keeping with (a) topical issues, and (b) @gustavderdrache, @Ledragon and others will be in the loop on who tackles what.

Cheers😄

**Pull request merged**
