### PR TITLE
types/big.js: Don't export global 'Big' identifier

### PR DESCRIPTION
**Pull request by cakoose**
Only <script src=...> users will get the global definition.  Node.js and ES module users won't.

I'm using Node.js and I sometimes accidentally use `Big(...)` without importing `Big`.  Because of the global definition, TypeScript doesn't catch this issue and I only notice the mistake when I get the error at runtime.

I'm proposing removing the global definition.  People who want the global import can opt in with:

```typescript
import BigJs from 'big.js';

declare global {
    const Big = BigJs;
    type Big = BigJs;
}
```

(I suspect there's a shorter way to accomplish the above.  Does anybody know how?)

Here are some other type definitions that have run into something similar: #42543, #11187.

**Filled-in template**

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: My comments above explain the reason for the change, but here's a link to the code in Big.js that decides whether to export a global symbol: [GitHub link](https://github.com/MikeMcl/big.js/blob/581037601e596234f0bbc340165d62750cf7ac8b/big.js#L996).
- N/A If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- N/A If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by cakoose** [comment]
@googol, @Ky6uk: Do either of you have time to review this change?

**Comment by googol** [comment]
I haven't been using this library for a couple of years so I don't feel comfortable commenting on any changes.

**Comment by peterblazejewicz** [comment]
So it looks wrong, the module has global export for browser:
https://github.com/MikeMcl/big.js/blob/master/big.js#L1026, so it could be used as `Big` and `Big.Big` (alias),
it depends on client (consuming code) TS setup on how it is used.
This one is probably just UMD like module:
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library

**Comment by cakoose** [comment]
@peterblazejewicz Yes, the presence of the global symbol depends on the how the module is being used.  I've never dealt with this in TS before.  My proposal was to omit the global symbol by default.  Users that want the global symbol can opt-in like this:

```typescript
import BigJs from 'big.js';

declare global {
    const Big = BigJs;
    type Big = BigJs;
}
```

Is there a better solution?

**Comment by cakoose** [comment]
BTW, my original problem was:
1. I'm using TypeScript and Node and imports, e.g. `import Big from 'big.js';`
2. I sometimes forget the "big.js" import, but I don't get an error from TypeScript.
3. At runtime my code fails because `Big` is an unknown symbol.

This was my attempt to fix the problem.  I got the idea from this open issue for the jQuery typings: #11187.

These are some of my tsconfig settings; are they to blame?
```json
        "module": "commonjs",
        "moduleResolution": "node",
        "esModuleInterop": true,
```

**Comment by peterblazejewicz** [comment]
Most propbably that's problem with current module. you've found a problem using it.
There is this pattern for UMD modules (supporting global/CJS/ESM imports) that can be used here I think:
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#reference-example
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html

**Review by Ky6uk — APPROVED** [review]

**Comment by Ky6uk** [comment]
I agree the global import should be removed from the typings. I'm also using it as a local import in a Vue project and few times I've got a runtime error because I'd forgot to add the import. The typescript compiler hasn't caught it because of global export.

**Comment by cakoose** [comment]
@peterblazejewicz: I tried for a while to use the `export as namespace` pattern to make this module work for both types of users, but ran into issues that I couldn't figure out.

My plan is to proceed with the current diff, which removes the global definition.  This is not ideal, but hopefully still a net improvement because there is a workaround for users that want the global definition .

**The issue I ran into with `export as namespace`**

I added `export as namespace Big` to the bottom of "index.d.ts".  That sort of worked, in that module-style code did not get the global symbol.

However, when I tried to use the symbol in non-module code, I got an error:

```
// ERROR: This expression is not constructable.
//   Type 'typeof import("/Users/kannan/Anrok/deps/DefinitelyTyped/types/big.js/index")' has no construct signatures.
function f1() { return new Big(1); }

// ERROR: This expression is not callable.
//   Type 'typeof import("/Users/kannan/Anrok/deps/DefinitelyTyped/types/big.js/index")' has no call signatures.
function f2() { return Big(1); }

// ERROR: ﻿Cannot use namespace 'Big' as a type.
function f3(b: Big) {}
```

**Comment by cakoose** [comment]
Ready to merge

**Comment by cakoose** [comment]
@Ky6uk: Can you approve again?  I added some comments, not realizing that it would require re-review.  Sorry about that.

**Review by Ky6uk — APPROVED** [review]

**Comment by Ky6uk** [comment]
Ready to merge

**Comment by cakoose** [comment]
Ready to merge

**Comment by cakoose** [comment]
Ready to merge

**Comment by SplitThePotCyrus** [comment]
This was actually a breaking change.

**Comment by SplitThePotCyrus** [comment]
This was actually a breaking change.

This change has caused an issue for us. We use this library in an Angular project with Lazy loaded modules etc. To keep the bundle size small, we only import this script once as vendor script and use it through out the app. With this change we cannot do that anymore. 

We will revert now, but this should not be a minor version change as it breaks stuff.
Perhaps a better way was to allow the global declaration to be, but to change its name to `BigConst` or `BigStatic` to avoid confusions for your use cases.

**Comment by SplitThePotCyrus** [comment]
True, but what good is the runtime if it does not compile? 😊

**Comment by cakoose** [comment]
@SplitThePotCyrus: Sorry for breaking.  I was aware that this might happen, but couldn't think of a better solution.

There are two ways people use "big.js": with and without the global symbol.  I _think_ there is a way to support both with the same typings, but I wasn't able to figure out how.  Any tips would be appreciated.

I thought the next best option was to support the without-global use case by default, and offer a workaround for the with-global use case: [link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f34fbb0657304cb11f8c4a3385cf434e7651924e/types/big.js/index.d.ts#L326-L336).  Maybe there's a better way to document that workaround, e.g. a way to add the workaround code to the NPM page for "@types/big.js"?

Re: major version bump.  Since DefinitelyTyped typings typically use the same major version number as the original package, I didn't bump the major version number, even though this is a breaking change.  But maybe there's a better way to handle this type of situation?

**Comment by Ky6uk** [comment]
I can also recommend creating your own `d.ts` file locally with global Big export. It should help. In our project, we have many libraries with controversial typings with local `d.ts` file with fixes of that.

**Pull request merged**
