### PR TITLE
Add faker library timeZone type definition

### PR DESCRIPTION
**Pull request by el-pendeloco**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/faker
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## faker ([<kbd>unpkg</kbd>](https://unpkg.com/browse/faker@latest/))
was missing the following properties:
1. locales
1. localeFallback
1. definitions
1. unique
1. time

<details>
<summary>as well as these 2 other properties...</summary>
<p>git, vehicle</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 95b9b78118b479c00df57f8992fbf3befb24c23c
</p>

**Comment by TastefulElk** [comment]
Hi @PhilLavoie , thank you for your contribution! Looks good to me once conflicts are resolved! 👍

**Review by TastefulElk — APPROVED** [review]

**Comment by PhilLavoie** [comment]
Thanks :),

Interestingly, the merge conflict covered a bunch of other functions, but not that one :laughing:

**Comment by TastefulElk** [comment]
Yeah, it was actually my PR that was merged with all of the Faker v5 changes and additions. Funny enough it seems I accidentally missed this particular one though 😁

**Review by TastefulElk — APPROVED** [review]

**Comment by PhilLavoie** [comment]
Ready to merge

**Pull request merged**
