### PR TITLE
add(svg-maps/common): shared types for @svg-maps

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This extracts common interfaces used accross @svg-maps packages into
definition only repo file, that could be shared accross all packages
implementing @svg-maps/* on DT

/cc @nickglazer for your review

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
It looks like there's also an `svg-maps__brazil` folder - should it consume these shared types too?

**Comment by peterblazejewicz** [comment]
> It looks like there's also an `svg-maps__brazil` folder - should it consume these shared types too?

Yes, it was under PR review (FIFO), so let me update and incorporate owner of the `brazil` in the discussion, thx!

**Comment by peterblazejewicz** [comment]
Amended with proper changes, thx!

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
