### PR TITLE
[form-data] Remove form-data

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

See https://github.com/form-data/form-data/releases/tag/v2.5.0

### CODE REVIEW

**Comment by ffflorian** [comment]
@sandersn types-publisher tells me:

> Error: In package.json: Dependency form-data not in whitelist

But I see form-data in the whitelisted dependencies:

https://github.com/microsoft/types-publisher/blob/79dc4eda9669b877d4d56b2b93f5644a4453dc46/dependenciesWhitelist.txt#L58-L60

**Comment by sandersn** [comment]
Sorry, forgot to publish types-publisher after merging. I published it just now.

types-publisher works from the `production` branch, so in the future you can check there to see what its dependency list currently looks like.

**Comment by sandersn** [comment]
@ffflorian can you try merging from master? I'm not sure why Azure gets the new types-publisher but Travis does not.

**Comment by ffflorian** [comment]
@sandersn I rebased from master but Travis still has the same problem :slightly_frowning_face:

**Comment by sandersn** [comment]
This still fails on Travis, even after I delete its cache. I'm not sure what's going on, but if author(s) will sign off, I'll go ahead and merge regardless.

**Review by LinusU — APPROVED** [review]
Nice 👍

**Comment by mapleeit** [comment]
I tried to remove @types/form-data several times. But CI blocks it somehow every time. I noticed that today and remade one.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36926

**Pull request merged**
