### PR TITLE
Make `import { fabric } from "fabric";` work

### LINKED ISSUE #20766: [@types/fabric] Error in module structure
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/fabric` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01

If you do not mention the authors the issue will be ignored.

## Description
When trying to initialize the canvas, I get this runtime error: _TypeError: fabric.Canvas is not a constructor_.

The cause seems to be the module structure of the JavaScript source: the correct path/signature is `fabric.fabric.Canvas`, not `fabric.Canvas`.

#### Versions
types/fabric 1.5.26
fabric 1.7.19

### PR DESCRIPTION
**Pull request by ghost**
Fixes #20766

### CODE REVIEW

**Comment by sid-kap** [comment]
@andy-ms Are you still planning to push this? I'm looking forward to this fix...

**Comment by georgberecz** [comment]
Hey @andy-ms,
is there any way to help you out here? Would love to see this landed. :)

**Comment by andy-ms** [comment]
Closing in favor of #23787

**Comment by hga77** [comment]
`import { fabric } from "fabric";`

Does not work. I am having to use
`const fabric = require('fabric');`

**Pull request closed without merging**
