### PR TITLE
[react-native] Adding divide routine to Animated

### PR DESCRIPTION
**Pull request by anthonyhiga**
### Description
Adding the divide routine into Animated.

### Related Links
Documented here: https://facebook.github.io/react-native/docs/animated.html

I'm not sure where exactly this needs to go. So if it's the wrong branch, that's cool.

### CODE REVIEW

**Comment by weswigham** [comment]
@dt-bot seems to have missed this one - @alloy @gyzerok @huhuanming @iRoachie do you of you have any comments on this PR?

**Review by iRoachie — APPROVED** [review]

**Comment by iRoachie** [comment]
Looks good @weswigham

**Review by huhuanming — COMMENTED** [review]
LGTM 👍

**Comment by huhuanming** [comment]
👍

**Comment by cliffkoh** [comment]
Thanks @anthonyhiga

**Pull request merged**
