### PR TITLE
[electron-window-state] Electron should not be a dependency 

### PR DESCRIPTION
**Pull request by timfish**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

With electron as a full dependency of `@types/electron-window-state`, the latest version of electron is downloaded into the dependency tree, even if you're not using this version.

If changing an existing definition:
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by timfish** [comment]
I'm not sure how to fix this because it looks like `devDependencies` are not allowed. 

However, electron definitely shouldn't be a full dependency of any `@types` package. Currently you can end up with multiple versions of electron in you dependency tree.

**Comment by timfish** [comment]
Also @andy-ms as it looks like you've worked on this package!

**Comment by rhysd** [comment]
You should add `electron` as dev dependency of your project, not here because whether depending on `electron` using npm is up to the project.

**Comment by timfish** [comment]
Electron is already a dependency of `@types/electron-window-state`. 

https://www.npmjs.com/package/@types/electron-window-state?activeTab=dependencies

**Comment by DanielRosenwasser** [comment]
Technically this **should** work the same as `@types/node` itself. It really feels like it should be a `devDependency` which the end-user needs installed. @sandersn, any clues?

**Comment by rhysd** [comment]
I thought someone may not have `electron` dependency in `package.json` in favor of `electron-builder`. `electron-builder` [does not depend on `electron`](https://www.npmjs.com/package/electron-builder) because it downloads Electron binary for each platform by itself.

**Comment by timfish** [comment]
If you don't depend on an Electron version, when packaging with electron-builder it downloads and uses the latest release. This is almost always not want you want as it will likely break when major versions are released.

The electron package uses electron-download to download the binaries in postinstall.

The Electron npm module is not shipped in node_modules of a packaged app so the recommendation from the electron maintainers is to add it to your project as a devDependency. Electron-builder will pick this up and stop packaging your app with the latest.

**Review by rhysd — APPROVED** [review]

**Comment by timfish** [comment]
@DanielRosenwasser what was the resolution for this? 

Does the typings check/test tooling need to be changed to accept `devDependencies` with a whitelist?

**Pull request closed without merging**
