### PR TITLE
[tabulator-tables] Update properties using MenuObject

### PR DESCRIPTION
**Pull request by zanatoshi**
The documentation define a menu item as either a MenuObject or a MenuSeparator.
A MenuObject is bind to one component which is either a column, a row or a column.
To reflect that I updated the definition of MenuObject with the use of a generic.

The documentation define 4 menu : 
- headerMenu in columns definition : all items are bind to a column
- headerContextMenu in column definition : all items are bind to a column
- cellContextMenu in column definition : all items are bind to a cell
- rowContextMenu in tabulator options : all items are bind to a row

Regarding this, I updated this 4 attributes to reflect the binding.

I also fix the following : 

- an item is either a MenuObject or a MenuSperator not both : MenuObject does not extends MenuSeparator
- all menu are defined by an array of MenuObject or MenuSperator `Array<MenuObject<ColumnComponent> | MenuSeparator>` not by an array of MenuObject or an array of MenuSparator `MenuObject[] | MenuSeparator[]`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://tabulator.info/docs/4.6/menu>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Jojoshua** [comment]
Good update @zanatoshi . While we have this PR could you also include the pending changes listed here so it can be merged together? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44743/files

**Comment by zanatoshi** [comment]
How could I include this changes ? A simple cherry-pick ?

**Comment by Jojoshua** [comment]
Yes if you could just add the UIEvent

**Comment by zanatoshi** [comment]
Added

**Review by Jojoshua — APPROVED** [review]

**Comment by Jojoshua** [comment]
Thanks!

**Review by Jojoshua — APPROVED** [review]

**Comment by Jojoshua** [comment]
Ready to merge @zanatoshi?

**Comment by zanatoshi** [comment]
Ready to merge

**Pull request merged**
