### PR TITLE
[jest] add toHaveBeenNthCalledWith matcher

### PR DESCRIPTION
**Pull request by r3nya**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/jest/pull/5826
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

# Context

Issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26387

### CODE REVIEW

**Review by orlandohohmeier — APPROVED** [review]

**Comment by orlandohohmeier** [comment]
I was about to add the types for `toHaveBeenNthCalledWith` as well. 😸

**Review by JoshuaKGoldberg — APPROVED** [review]
Missing unit tests, but there've been a few Jest pull requests lately and it looks like there's already a gap in test coverage.

If you're up for adding tests to `jest-tests.ts` that would be great! Otherwise I can just add them in a subsequent PR.

**Comment by r3nya** [comment]
Hey @JoshuaKGoldberg! Thanks for your review. I'm going to add tests for it. ;)

**Comment by r3nya** [comment]
@JoshuaKGoldberg added test for it. Now everything is ok. 🎉

**Pull request merged**
