### PR TITLE
[animejs] use default export

### PR DESCRIPTION
**Pull request by spkjp**
Fixes https://github.com/juliangarnier/anime/issues/527.

- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by omaishar** [comment]
Worked for me!

**Review by A-Babin — APPROVED** [review]

**Comment by minestarks** [comment]
I'm not sure about this change - while it makes the default import work, it would now introduce errors in CommonJS and UMD module scenarios (both of which should be supported according to [documentation](https://www.npmjs.com/package/animejs))

The linked issue https://github.com/juliangarnier/anime/issues/527 is still solvable by adding `"allowSyntheticDefaultImports": true` to the `tsconfig.json` and using the `import anime from 'animejs'` syntax.

**Review by minestarks — CHANGES_REQUESTED** [review]
Updating review status since I don't think this change is correct or necessary at the moment (see comment)

**Comment by supaiku0** [comment]
@minestarks Good catch, thanks.

I updated the PR and also pushed one more fix I had lying around locally. Context:
https://animejs.com/documentation/#timelineBasics

**Comment by supaiku0** [comment]
@minestarks Friendly ping!

**Review by minestarks — APPROVED** [review]

**Pull request merged**
