### PR TITLE
remove react-native as of version 0.71

### PR DESCRIPTION
**Pull request by lucasraziel**
Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by lucasraziel** [comment]
How should I proceed with this PR? react-native does not require types anymore since 0.71.0, but I got some errors in some packages (e.g react-native-vector-icons) that were using types/react-native (There are some differences between types/react-native and the new types in react-native package).
I think that this repository should add the information that react-native is no longer needed here, and little by little other packages will have to update with this new information. but since this package was largely used by other libraries, I do not know how to deal with It.

**Review by iRoachie — CHANGES_REQUESTED** [review]
Why not just update the notNeedPackages.json like you have here? Not understanding why you the files are deleted

**Comment by lucasraziel** [comment]
> Why not just update the notNeedPackages.json like you have here? Not understanding why you would go and delete the files


The removal was made automatically by not-needed script. As this was the instruction to do this kind of PR, I thought that this is the right thing to do, but I can restore the folder if It is convenient.

**Comment by iRoachie** [comment]
My apologies man. If I'm not mistaken, I think the other 102 packages that depend on this must be updated to use the `react-native` package and reference the types from there.

This probably needs to be done first before we can mark it here as not needed.

**Comment by lucasraziel** [comment]
> My apologies man. If I'm not mistaken, I think the other 102 packages that depend on this must be updated to use the `react-native` package and reference the types from there.
> 
> 
> 
> This probably needs to be done first before we can mark it here as not needed. 

Ok, I will try to help by doing new PR's to the packages that I currently need fixes, but what should I do with this PR? should I keep here until the packages are eventually fixed as a remainder?

**Comment by iRoachie** [comment]
I was thinking maybe we have an umbrella issue where we can track the status to completion.

@lunaleaps @eps1lon how should we go forward here?

**Comment by lucasraziel** [comment]
> I was thinking maybe we have an umbrella issue where we can track the status to completion.
> 
> @lunaleaps @eps1lon how should we go forward here?

I can see now that there were a closed PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63276 about this update. Unfortunately, what was made there did not avoid erros in typescript when using react-native 0.71, I will close this PR and try to open an issue about the errors. It seem that updating the libraries to react-native 0.71 will not be an easy job to do. Thanks anyway.

**Comment by lunaleaps** [comment]
Hey guys, the plan is to release a 0.72 version of TS types and then deprecate.

**Pull request closed without merging**
