### PR TITLE
Add react-places-autocomplete definition

### PR DESCRIPTION
**Pull request by guilhermehubner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
👏

**Comment by FdeFabricio** [comment]
👍

**Comment by laryssamagalhaes** [comment]
🎉

**Comment by gabsprates** [comment]
🔝

**Comment by Eugene-Sviridov** [comment]
@guilhermehubner 
Is it still a correct definition? When I use `onChange` inside `inputProps` I get an error 
The prop `onChange` is marked as required in `PlacesAutocomplete`, but its value is `undefined`.
This error appears for value too.

**Comment by SirwanAfifi** [comment]
I also get this error:

```
[ts]
Type '{ children: ({ getInputProps, suggestions, getSuggestionItemProps, loading }: any) => Element; value: string; onChange: (address: string) => void; onSelect: (address: any) => void; }' is not assignable to type 'Readonly<PropTypes>'.
  Property 'inputProps' is missing in type '{ children: ({ getInputProps, suggestions, getSuggestionItemProps, loading }: any) => Element; value: string; onChange: (address: string) => void; onSelect: (address: any) => void; }'.
(alias) class PlacesAutocomplete
import PlacesAutocomplete
```

Here's how I use the component:

```
<PlacesAutocomplete
              value={state.address}
              onChange={handleChange}
              onSelect={handleSelect}
            >
```

**Comment by Eugene-Sviridov** [comment]
I've created a `react-places-autocomplete.d.ts` file in the root directory of my project. And put this
`declare module 'react-places-autocomplete';`
inside it.

It isn't the best solution but it works

**Comment by SirwanAfifi** [comment]
I changed it to this:
```
<PlacesAutocomplete
              inputProps={{
                value: state.address,
                onChange: handleChange,
                onBlur: handleSelect
              }}
            >
```
But I get this error in the console:

```
Warning: Failed prop type: The prop `onChange` is marked as required in `PlacesAutocomplete`, but its value is `undefined`.
    in PlacesAutocomplete (created by State)
    in State
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by State)
    in div (created by FormControl)
    in FormControl (created by WithStyles(FormControl))
    in WithStyles(FormControl) (created by State)
    in form (created by State)
    in State (created by Formik)
    in Formik
    in div
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by Mutation)
    in div (created by Mutation)
    in div (created by Mutation)
    in Mutation (created by removeImage)
    in removeImage (created by Mutation)
    in Mutation (created by getSignedUrl)
    in getSignedUrl (created by Mutation)
    in Mutation (created by deleteEvent)
    in deleteEvent (created by Mutation)
    in Mutation (created by updateEvent)
    in updateEvent (created by Mutation)
    in Mutation (created by createEvent)
    in createEvent (created by Query)
    in Query (created by getEvent)
    in getEvent (created by Adopt)
    in Adopt (created by Adopt(getEvent))
    in Adopt(getEvent) (created by Adopt(getEvent)(createEvent))
    in Adopt(getEvent)(createEvent) (created by Adopt(getEvent)(createEvent)(updateEvent))
    in Adopt(getEvent)(createEvent)(updateEvent) (created by Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent))
    in Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent) (created by Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent)(getSignedUrl))
    in Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent)(getSignedUrl) (created by Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent)(getSignedUrl)(removeImage))
    in Adopt(getEvent)(createEvent)(updateEvent)(deleteEvent)(getSignedUrl)(removeImage)
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by Route)
    in Route (created by App)
    in main
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper)
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by App)
    in MuiThemeProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in ApolloProvider (created by App)
    in App
```

**Comment by Eugene-Sviridov** [comment]
I use it like this
`
<PlacesAutocomplete
  value={this.state.address}
  onChange={this.onChange}
  onSelect={this.onSelect}
>
```
but with a custom type definition. 
I think `inputProps` props doesn't work now but the definition wasn't updated. Try to use the method that I describe above. It should help you.

**Comment by SirwanAfifi** [comment]
@Eugene-Sviridov Thanks, I had to create a declaration file `react-places-autocomplete.d.ts` (which I think it's a clean way, but it works)

```
declare module "react-places-autocomplete";

```

Then I used the way you described.

**Pull request merged**
