### PR TITLE
[memory-fs] support ES6 import syntax

### PR DESCRIPTION
**Pull request by hronro**
Support ES6 import syntax in `memory-fs`.

### CODE REVIEW

**Comment by amcasey** [comment]
Would any of the typing authors care to take a look? 
@e-cloud

**Comment by e-cloud** [comment]
sorry, I wasn't notified before. @foisonocean, I wonder why addding the declare? star import should work without it.

**Comment by foisonocean** [comment]
@e-cloud 
I can't use `import * as MemoryFileSystem from 'memory-fs';` with current typings, or I get something wrong ?

**Comment by e-cloud** [comment]
Emmm, it seems it worked in older version of typescript. By the way, declaring the namespace is just shelling the actual types. Why not use require style? But feel free to update the typings. LGTM.

**Comment by amcasey** [comment]
https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this

**Pull request closed without merging**
