### PR TITLE
Fix missing imports

### PR DESCRIPTION
**Pull request by calebmer**
Closes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12621

This will also need to get merged into `master`.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
thx for your help. @calebmer 

although the ci check failed, it doesn't show any issue about this. It's so wired.

**Comment by nknapp** [comment]
The fix works for me at least. CI failed because of a timeout. Does it check *all* definitions on Definitely typed? Maybe this is taking too long now, so Travis is complaining.

**Comment by TonyPythoneer** [comment]
Hello @andy-ms,

The CI exceeded the maximum time limit for jobs.
Would you fix it? Thx.

**Comment by andy-ms** [comment]
Tested manually.

**Pull request merged**
