### PR TITLE
Fix koa-router to avoid koa.Context shadowing.

### PR DESCRIPTION
**Pull request by bradleyayers**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR removes the the `declare module "koa"` definition which includes a `Context` interface which ends up shadowing the one defined in `koa`.

Concretely, the following would not work:

```ts
import { Context } from 'koa';

function (ctx: Context) {
  ctx.body = 'Hello world!'; // ERROR: no property `body`
}
```

### CODE REVIEW

**Comment by Kovensky** [comment]
They should augment each other, not shadow. IIUC, it should only be a problem if you _don't_ have `@types/koa` installed.

**Comment by bradleyayers** [comment]
Hmm. In my case I definitely had `@types/koa` installed and the `koa-router` definition was shadowing it. I'll do a bit more experimenting though to confirm. It probably makes sense to just add an example to `koa-router-tests.ts` and get it failing without the patch.

**Comment by schfkt** [comment]
@bradleyayers typescript docs say @Kovensky is right: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
So, this module doesn't shadow anything. It augments the Context interface from koa module.

**Comment by paulvanbrenk** [comment]
Going to close this, per @schfkt

**Pull request closed without merging**
