### PR TITLE
RethinkDB 2.x JS clients (rethinkdb and rethinkdbdash)

### PR DESCRIPTION
**Pull request by niieani**
Feature complete, since I've first built a crawler for the RethinkDB documentation and then tuned it by hand. Closes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551.

### CODE REVIEW

**Comment by vvakame** [comment]
@seanhess could you review this PR?

**Comment by rakam** [comment]
I use these definitions since a few days and they work well.

BTW I have found some omissions, I can make a PR if needed. It should be done on this repo or https://github.com/niieani/rethinkdb-typescript-definition?

**Comment by niieani** [comment]
Hi @rakam, the pull request here is a bit outdated. I've completely rewritten the definitions here: https://github.com/niieani/rethinkdb-typescript-definition.
Feel free to correct if you see any mistakes there.
There's a discussion going on here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551 about the latest iteration of these typings.

**Comment by niieani** [comment]
I'm closing this for now since the pull request needs to be updated to the latest iteration of the typings.

**Pull request closed without merging**
