### PR TITLE
Initial definitions for react-native 0.14

### PR DESCRIPTION
**Pull request by bgrieder**
Comments, additions, etc.. welcome

### CODE REVIEW

**Comment by bgrieder** [comment]
I need help here: can I not set the target to ES6 in tscparams ?

**Comment by bgrieder** [comment]
Please hold on this PR. I need to add a few additional definitions

**Comment by bgrieder** [comment]
This can go as a first PR but I am worried you will get a lot of PRs. Is it better that people open PRs and issues against my repo first so I can merge anything appropriate and then submit batch modifications to you ?

**Comment by vvakame** [comment]
*react-native/react-native.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/react-native
  * http://bower.io/search/?q=react-native
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (react-native/react-native-tests.ts or react-native/react-native-tests.tsx)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
np. thanks mate!

**Pull request merged**
