### PR TITLE
Improved struct construction typing

### PR DESCRIPTION
**Pull request by Rechdan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Rechdan** [comment]
Hey @benallfree, I hope you are doing well! I've implemented some changes so we can have a better typing experience with `structs`, hope you like it 😁

**Comment by benallfree** [comment]
Hey @Rechdan thank you! Can you please explain how the experience is improved? I'm not familiar with this use of TS.

**Comment by Rechdan** [comment]
@benallfree sure! The idea behind these changes it to construct the typing as the struct is made, here's an example:

```ts
new Struct().charsnt("name", 100).word8("age");
```

This struct would be, at the end, this type:

```ts
Struct<{
    name: string;
    age: number;
}>
```

So we don't need to create `types` for each struct, they will be automatically created!

**Comment by benallfree** [comment]
@Rechdan Interesting idea. How can we avoid this kind of mistake:

```ts
new Struct<{name: string}>.charsnt('namme') // typo
```

becomes

```
Struct<{
   name: string
   namme: string
}>
```

**Comment by Rechdan** [comment]
> @Rechdan Interesting idea. Is there a way to enforce a type if it is specified in advance? How can we avoid this kind of mistake:
> 
> ```ts
> new Struct<{name: string}>.charsnt('namme') // typo
> ```
> 
> becomes
> 
> ```
> Struct<{
>    name: string
>    namme: string
> }>
> ```

I believe we can enforce that, but then I'm not sure how to do that while also having it automatically constructed

**Comment by benallfree** [comment]
@Rechdan Please see below:

[TS Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIiB2BDAtgSwMYGVgCcCu6wAPACpQQAewE8AJgM5QDeAvgHxQC8zAsAFBQo6ABaIc8YiQByKaJWp1G9XKngBzNgAokyCAC4o02QEoDcHRmz5CpKADJmUANoBpKKsMzdAXQPKcqmpQ7Pws-PzoADaI9IxWBJLkVDQMzCxQAD5QeHQQAGaqELRc2bkF8EVsTPyCImISpF5yyYpQmmTyKYysUAD8UADWECAA9nmGUH4q6sZaOvqeJgYdLak5tPmFxf3mKJa4CURMzm4eRj5TAerBHAbxNiQc1QKCUAD0b1AAAsD0ALSoNTwEY4CA1V6g4B4cRQYDCVD0cFhPjI-hvABU-E42JxuLx+IJhKJxOxNWwIEi0AAjFA-lB-BhgPSDoQagBhUSqQLuRjApmggCOeFQoNoWJJEslUvx-HRbwiI3gynpNO4FQA7lB7sRjnkRiNLtz2JpjPx6FSAHR1cTATQAcj1Iztxnen3owhGeEixXVIIGUHVqDhUDAYhQ7gkEEikQRNHo0CQOBwI3VRVhI0Gwyg80RfHNVtENvtACNEAAvZ2u+ker3FMDJ2gEaCIQyYchJkFQYsQdCIPDxqB20sVnnZkZMlsAN0QMeKQxA4T4GPF0tXa4JZNAlKgACZaVBaAg9uhmdZgDVdmgsCyJ9GU4xEPAQFAClHijmagB1ACCACUpAAklIADiBh1Fy1wIlAgrCqKUCdoeFi9tGz7oIq-gJGmgbRl20CqGhyBgJS1AruuZFrrK8p8GhSpMvQe5qhAmraia4IFvUtoOvqzpsdaEglmIlYfC+qgzrC4B4Ywl77GeRyOnoDLqAANF2YiGuoIR5ju7FFkO5ZCZ8ABC34wFAhkAKpkN+AAy1kAPKfgAoqZdKvt6UCILQGzFMAGYYYQKnFngTJ8um4mQIuQA)

```ts
type DynamicStruct<T extends {}> = {
  charnt<TName extends string>(name: TName): DynamicStruct<T & { [K in TName]: string }>
}

class Struct<T extends {} | undefined = undefined>{
  charnt<TName extends (T extends {} ? keyof T : string)>(name: TName): T extends undefined ? DynamicStruct<{ [K in TName]: string }> : Struct<T> {
    // @ts-ignore
    return this
  }
}

/*
=========================================================
 Style 1 - strict struct
 Chaining is not required
=========================================================
*/
const s1 = new Struct<{ foo: string }>()
s1.charnt('foo') // should work with param intellisense narrowed to key names
s1.charnt('baz') // should produce a TS error because 'baz' is not a valid key

/*
=========================================================
 Style 2 - dynamic struct
 DynamicStruct allows any field names
 WARNING: chaining is required or dynamically constructed will be incomplete
=========================================================
*/
const s2 = new Struct()
  .charnt('foo')
  .charnt('bar') // final type is DynamicStruct<{foo:string, bar: string}>
s2.charnt('baz') // BAD BUT ALLOWED - field added to struct, but not to type


```

**Comment by Rechdan** [comment]
@benallfree that looks great!

**Comment by benallfree** [comment]
@Rechdan Ok please update & test. Please also add a `README.md` to this package so people understand the different ways to use it and the implications behind dynamic chaining.

Thank you for this effort, great ideas.

**Comment by elibarzilay** [comment]
Moving this to a waiting-for-review state re the above comment.

**Comment by benallfree** [comment]
@elibarzilay i believe we are waiting for changes from the submitter @Rechdan

**Comment by Rechdan** [comment]
@benallfree I'll not be able to give further updates here, sorry about that!

**Comment by benallfree** [comment]
Please close this PR without merging.

**Pull request closed without merging**
