### PR TITLE
[react-native-web] Fix UIManager fn typing

### PR DESCRIPTION
**Pull request by adamhari**
# Why

We need to extend `UIManagerStatic`, otherwise attempting to `import {UIManager} from 'react-native'` and call fns results in `TS2339: Property 'blur' does not exist on type 'UIManagerStatic'.`

### CODE REVIEW

**Comment by blazejkustra** [comment]
Thanks for the contribution to RNW types ❤️ 

@adamhari Could you also bump the version package to `0.19.9999`? In the initial release I made a mistake, [RNW is at 0.19.12 currently](https://www.npmjs.com/package/react-native-web) so we have to copy major and minor and add 9999 following [this](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) guide.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/react-native-web/react-native-web-tests.tsx

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 122f9fc85efe9e56bcf0c2124f419d66b8ee4a2a
</p>

**Review by blazejkustra — APPROVED** [review]
Looks good to me, thanks for the version update

**Comment by blazejkustra** [comment]
Ready to merge

**Pull request merged**
