### PR TITLE
[braintree-web] Add tokenize as valid payment intent value

### PR DESCRIPTION
**Pull request by mbillz**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/braintree/braintree-web/issues/544
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by jbuckner — CHANGES_REQUESTED** [review]
Hi, thank you for the PR! This is a rather large diff for what looks like just adding the `tokenize` option to `intent`. Also, the rest of the files in this package use single-quotes so changing this all to double-quotes is an outlier. Could you pare down this MR to just the type change?

**Comment by mbillz** [comment]
Thanks @jbuckner - I went back and forth a few times on whether I should apply Prettier formatting (I saw that we were potentially supposed to via the [README.md ](https://github.com/DefinitelyTyped/DefinitelyTyped/#common-mistakes) but maybe I misunderstood! I removed the formatting.

One other question - should I be updating the versioning? I left that in, but if that's not expected behavior, I'll happily remove. This is my first contribution to `DefinitelyTyped` so I want to make sure I'm doing things right! Thanks for the guidance!

**Comment by jbuckner** [comment]
@mbillz Thanks for the cleanup! I checked out that thread that was linked and it looks like the `tokenize` option was added in `3.75` right? I might bump the version to that since it wasn't available before then. Otherwise, this looks good to go!

**Comment by mbillz** [comment]
Oh yeah, duh, updated!

**Review by jbuckner — APPROVED** [review]
Looks good! :shipit:

**Pull request merged**
