### PR TITLE
Remove 'del' package

### PR DESCRIPTION
**Pull request by j-oliveras**
Starting on v4.0.0 it includes types declarations: https://github.com/sindresorhus/del/releases/tag/v4.0.0

Needs https://github.com/Microsoft/types-publisher/pull/586 to pass tests.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by j-oliveras** [comment]
Only coping from opening post: needs https://github.com/Microsoft/types-publisher/pull/586 to pass tests.

**Comment by j-oliveras** [comment]
Now, tests for `gulp` and `vinyl-paths` fails on TS 2.0 because that don't have Readonly. Is only used on tests, so a workaround is remove `del` from the tests.

`rollup-plugin-delete` fails on rollup declaration file (TS 2.3) with `node_modules/rollup/dist/rollup.d.ts(376,24): error TS1110: Type expected.`. The package is needed because the options extends from `del`. Is it caused because `del` own type not compatible with `rollup-plugin-delete`?

@sandersn what to do in this cases?

**Comment by sandersn** [comment]
rollup-plugin-delete's error actually comes from rollup, which was already required. I'm not sure why it's failing now -- perhaps it was cached on the build server until now? In any case, rollup.d.ts used to have Typescript 2.3-compatible types before 1.2.0, but upgraded them at https://github.com/rollup/rollup/pull/2679, which released on February 17. 

So you have two choices:
1. Make rollup-plugin-delete require TS 3.2.
2. Make rollup-plugin-delete depend on rollup <1.2.0.

I recommend (2) since 3.2 is a pretty new version of Typescript still.

**Comment by sandersn** [comment]
The reason rollup didn't fail until now is that the only time that we try to compile a package with all versions of typescript is when the package is actually changed. When it's just a dependent, it's only tested with `typescript@next`.

**Comment by j-oliveras** [comment]
Done: changed `gulp` and `vinyl-paths` to not require `del` and make rollup on `rollup-plugin-delete` to < 1.2.0

**Pull request merged**
