### PR TITLE
[@types/recharts@1.1.0] add capHeight and lineHeight field type to TextProps interface 

### PR DESCRIPTION
**Pull request by Yann-Wang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/recharts/recharts/blob/0420cda617d7de62db240830d8bafe848c08bc1e/src/component/Text.js#L42>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by jrsaunde — CHANGES_REQUESTED** [review]
Hey @Yann-Wang! Thanks for the fix!

Do you mind adding/updating a test demonstrating this option?

**Comment by Yann-Wang** [comment]
@jrsaunde , ok, I'll add the test later.

**Comment by Yann-Wang** [comment]
@jrsaunde ,  some test has been added for this option, and the previous test can't be rendered normally, I have fixed it.

**Review by jrsaunde — COMMENTED** [review]
Hi Yann, sorry I missed this!

Everything looks good to me, except the merge commit. If you can remove that commit I’d be happy to approve :)

**Comment by johnnyreilly** [comment]
Hi - thanks for submitting this PR! There's a lot of "noise" in it for what should be a minor amend. Please could you resubmit with only the relevant changes?

**Comment by Yann-Wang** [comment]
@johnnyreilly , ok, I'll resubmit it.

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by Yann-Wang** [comment]
@johnnyreilly , done.

**Comment by johnnyreilly** [comment]
Thanks!

**Pull request merged**
