### PR TITLE
Add more strongly typed version of gl-matrix 2.3.0 definitions.

### PR DESCRIPTION
**Pull request by MattijsKneppers**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by mhegazy** [comment]
Just as a side note, this is not going to be picked up by the @types packages once it is published since the file name does not match the package name. why not update the main file?

**Comment by MattijsKneppers** [comment]
@mhegazy I personally believe this new version is better in all ways, but it is not fully backwards compatible with the current one. I'm not sure what the policy is on this, any advise is welcome.

**Comment by mhegazy** [comment]
Well. i do not know much about the library so i can not comment, but @nkassis might have a better idea.

**Comment by MattijsKneppers** [comment]
Let me explain the backwards compatibility issue: 

The current definitions file uses a generic return type for all methods, mirroring the JavaScript implementation of the Float32Array result. The problem is that this allows for instance to pass a vector argument where a 4x4 matrix is needed, since the only technical difference between the two is the required amount of elements in the array.

I added stricter typing, a vec3 can no longer be passed when a mat4 is needed. This is artificially imposed, but IMO saves time and makes code more readable. Also, looking at the code documentation of the author of the library (@toji), I believe this is the intended typing.

I am not familiar with the tool chains linked to DefinitelyTyped, so I am happy to change the file names if that helps, but I suspected that simply replacing the current file could break things; when replacing it with my implementation in a project there will certainly be compile errors, although they will be easy to fix.

**Comment by nkassis** [comment]
I like this version of the definition file and would probably switch to using it myself. 

It does have some drawbacks that will break existing code and make some valid code no longer valid. For example

`mat4.rotate(outMat, currMat, angle, [0,1,0])`

will no longer be accepted. 

Also the assumption that the array type the library uses is Float32Arrays is probably true in practice but gl-matrix checks to see if the browser supports and fallback to regular js arrays otherwise. It's also possible to override the type globally using glMatrix.setMatrixArrayType. This might be a reason to maintain the GLM.IArray interface as the base type instead of Float32Array.

With all that said I personally not opposed to making this the default version but it's definitively a breaking change. What's the policy on breaking changes for DT defintions? 

Alternatively, this could be made into a new package name gl-matrix-typed such that it be obtainable through npm.

**Comment by MattijsKneppers** [comment]
Thanks for the rundown @nkassis 

To support `mat4.rotate(outMat, currMat, angle, [0,1,0])`, it could be an idea to change the definitions to 

`public static rotate(out:mat4, a:mat4, rad:number, axis:vec3 | number[]):mat4;`

As long as the gl-matrix types keep extending Float32array, this would prevent the methods from accepting a different gl-matrix type but they would accept literal number arrays. 

On the other hand, gl-matrix is big on not allocating memory unnecessarily. Forcing the use of `vec3.fromValues(0, 1, 0)` instead of allowing `[0,1,0]` does raise the awareness that memory is being allocated there.

--
One thing I found puzzling about the current implementation is that the `GLM.IArray` type is not accepted as an argument to WebGL methods like [`gl.uniformMatrix2fv`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix), for instance it doesn't have the `BYTES_PER_ELEMENT` property, so typescript will complain when compiling.

Since this library is called gl-matrix and Float32Array is supported by all browsers that support WebGL, I would say that having the types extend Float32Array is obligatory, but maybe I'm missing something.

**Comment by nkassis** [comment]
> To support mat4.rotate(outMat, currMat, angle, [0,1,0]), it could be an idea to change the definitions to
> 
> public static rotate(out:mat4, a:mat4, rad:number, axis:vec3 | number[]):mat4;
> 
> As long as the gl-matrix types keep extending Float32array, this would prevent the methods from accepting a different gl-matrix type but they would accept literal number arrays.

I like that change, I'd prefer to let the dev decide if they want to use literal number arrays vs vec3.fromValue. 

> One thing I found puzzling about the current implementation is that the GLM.IArray type is not accepted as an argument to WebGL methods like gl.uniformMatrix2fv, 

Right that's a good point. 

> Since the library is called gl-matrix and Float32Array is supported by all browsers that support WebGL, I would say that having the types extend Float32Array is obligatory, but maybe I'm missing something.

Agreed. 

I'm ok with this change I think it should be the default version of the types going forward if possible. I'm in favor of renaming this new file to gl-matrix.d.ts and  the old version can be renamed to gl-matrix-legacy.d.ts so it's still available for devs who don't want or have time to refactor their code.

**Comment by mariusGundersen** [comment]
It would be nice if these methods were generic, so that they could handle array-like objects. For example:

        public static invert<TOut extends number[] | mat2d, TIn extends number[] | mat2d>(out: TOut, a: TIn): TOut | null;

This way the inputs and outputs can handle arrays and mat2d objects

**Comment by MattijsKneppers** [comment]
From your code example I infer that you always want to return a number array when a number array is input, however in at least some cases you'd want to return the base type instead, or mix argument types. 

For example: 

`public static scale(out: mat4, a: mat4, v: vec3 | number[]): mat4;`

I often only input the scale as a number array, intending to modify the mat4 and continue to use the mat4 as such.

**Comment by mariusGundersen** [comment]
Yes, that's not a problem, the point here is that (in `scale`) the variables `out` and `a` don't need to be the same type. The rules are as follows:

* `v` can be any array like object, `vec3 | number[]`
* `a` can be any array like object, `mat4 | number[]`
* `out` and the return type bust me the same
* `out` can be any array like object, `mat4 | number[]`

so the definition would be:

```
export type mat4ish = mat4 | number[];
export type vec3ish = vec3 | number[];

public static scale<Tout extends mat4ish>(out : Tout, a : mat4ish, v : vec3ish) : Tout;
```

This enforces that the return type is the same as the `out` parameter.

**Comment by mariusGundersen** [comment]
Yes, that's not a problem, the point here is that (in `scale`) the variables `out` and `a` don't need to be the same type. The rules are as follows:

* `v` can be any array like object, `vec3 | number[]`
* `a` can be any array like object, `mat4 | number[]`
* `out` and the return type bust me the same
* `out` can be any array like object, `mat4 | number[]`

so the definition would be:

```
export type mat4ish = mat4 | number[];
export type vec3ish = vec3 | number[];

public static scale<Tout extends mat4ish>(out : Tout, a : mat4ish, v : vec3ish) : Tout;
```

This enforces that the return type is the same as the `out` parameter, but they can now be arrays, if needed.

**Comment by MattijsKneppers** [comment]
Aah, thanks for explaining. I agree, using generics for the output type like this would indeed be a nice addition.

**Pull request merged**
