### PR TITLE
Remove wordpress__editor

### PR DESCRIPTION
**Pull request by manzoorwanijk**
`@wordpress/editor` now includes the types since `v14.12.0` and this package here is no longer needed.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by rbuckton — APPROVED** [review]

**Comment by manzoorwanijk** [comment]
Ready to merge

**Comment by jakebailey** [comment]
This PR broke DT; the `@wordpress/editor` package contains incorrect types for `Element`, causing errors in other packages:

```
Error in wordpress__edit-post
Error: 
/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/header/plugin-more-menu-item.d.ts
  1:64  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/header/plugin-sidebar-more-menu-item.d.ts
  1:78  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/sidebar/plugin-document-setting-panel.d.ts
  1:80  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/sidebar/plugin-post-publish-panel.d.ts
  1:72  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/sidebar/plugin-post-status-info.d.ts
  1:68  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/sidebar/plugin-pre-publish-panel.d.ts
  1:70  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect

/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__edit-post/components/sidebar/plugin-sidebar.d.ts
  1:54  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error: 
Cannot find module '@wordpress/editor' or its corresponding type declarations  @definitelytyped/expect
```

The upstream package appears to have confused the global DOM `Element` with `import("react").JSX.Element` (which is correct in other wordpress packages).

Unfortunately, CI does not catch this as shims are only published after merge.

**Comment by jakebailey** [comment]
Er, oops, wrong error. This PR forgot to update the dependencies, and after doing that, you get:

```
dtslint@0.2.28
Error:
/home/jabaile/work/DefinitelyTyped/types/wordpress__edit-post/wordpress__edit-post-tests.tsx
  44:5    error  TypeScript@5.0 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 163 more

                                                                                                                   @definitelytyped/expect
  44:5    error  TypeScript@5.1, 5.2, 5.3 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 164 more

                                                                                                         @definitelytyped/expect
  44:5    error  TypeScript@5.4 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 165 more

                                                                                                                   @definitelytyped/expect
  44:5    error  TypeScript@5.5 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 168 more

                                                                                                                   @definitelytyped/expect
  44:5    error  TypeScript@5.6 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 169 more

                                                                                                                   @definitelytyped/expect
  44:5    error  TypeScript@5.7, 5.8 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 172 more

                                                                                                              @definitelytyped/expect
  48:5    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5 compile error:
Type 'React.JSX.Element' is not assignable to type 'Element'


                                                                                          @definitelytyped/expect
  48:5    error  TypeScript@5.6 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 169 more

                                                                                                                   @definitelytyped/expect
  48:5    error  TypeScript@5.7, 5.8 compile error:
Type 'ReactElement<any, any>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 172 more

                                                                                                              @definitelytyped/expect
  54:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; icon: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & { href?: string | undefined; icon?: any; onClick?: Function | undefined; other?: any[] | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { href?: string | undefined; icon?: any; onClick?: Function | undefined; other?: any[] | undefined; }'                                                @definitelytyped/expect
  58:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; href: string; }' is not assignable to type 'IntrinsicAttributes & { href?: string | undefined; icon?: any; onClick?: Function | undefined; other?: any[] | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { href?: string | undefined; icon?: any; onClick?: Function | undefined; other?: any[] | undefined; }'                                                                     @definitelytyped/expect
  63:111  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPostPublishPanel' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  66:28   error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPostPublishPanel' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  71:65   error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPostStatusInfo' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  72:26   error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPostStatusInfo' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  77:109  error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPrePublishPanel' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  80:27   error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
'ep.PluginPrePublishPanel' components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'Element'

                                                                           @definitelytyped/expect
  85:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; name: string; isPinnable: false; title: string; icon: Element; }' is not assignable to type 'IntrinsicAttributes & { name: string; className?: string | undefined; title: string; isPinnable?: boolean | undefined; icon?: any; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { name: string; className?: string | undefined; title: string; isPinnable?: boolean | undefined; icon?: any; }'  @definitelytyped/expect
  88:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; name: string; title: string; }' is not assignable to type 'IntrinsicAttributes & { name: string; className?: string | undefined; title: string; isPinnable?: boolean | undefined; icon?: any; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { name: string; className?: string | undefined; title: string; isPinnable?: boolean | undefined; icon?: any; }'                                    @definitelytyped/expect
  95:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; target: string; icon: string; }' is not assignable to type 'IntrinsicAttributes & { target: string; icon?: any; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { target: string; icon?: any; }'

                                                     @definitelytyped/expect
  98:2    error  TypeScript@5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8 compile error:
Type '{ children: string; target: string; }' is not assignable to type 'IntrinsicAttributes & { target: string; icon?: any; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { target: string; icon?: any; }'
```

**Comment by jakebailey** [comment]
It's not super clear that this can be fixed without fixing `@wordpress/editor`.

**Comment by jakebailey** [comment]
Aha, great, thanks.

**Pull request merged**
