### PR TITLE
Enzyme: add signature for exists method

### PR DESCRIPTION
**Pull request by pelotom**
See:
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/exists.md
https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/exists.md

### CODE REVIEW

**Comment by NoHomey** [comment]
@pelotom Can you add a test for it?

**Comment by andy-ms** [comment]
We don't accept pull requests to `types-2.0` any more (#13233). Please rebase onto `master`, then hit "Edit" in the upper-right and change the base branch to `master`.

**Comment by pelotom** [comment]
Ok, rebased onto `master` and added a test for `exists()`.

**Comment by NoHomey** [comment]
LGTM now :+1:

**Pull request merged**
