### PR TITLE
[mongodb] First update to bring the mongodb to version 3

### LINKED ISSUE #22538: @types/mongodb v3
`node-mongodb-native` v3 is released. Let's play together to provide new typings. Some links:
* Official API reference: [mongodb.github.io/node-mongodb-native/3.0/api/](http://mongodb.github.io/node-mongodb-native/3.0/api/)
* Version 3 changes: [mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md)

@CaselIT @kikar @bitjson @dante-101  @mcortesi

### PR DESCRIPTION
**Pull request by CaselIT**
Please fill in this template.
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md
- [x] Increase the version number in the header if appropriate.

First update to the mongodb typings to support version 3.
I've used this version change to also change the comment style from `// ..` to `/** .. */`

Closes #22538
@arusakov

### CODE REVIEW

**Comment by CaselIT** [comment]
@andy-ms I've set the version of mongodb on some packages the older v2 because the test failed. Should I set to v2 also on the other packages that use mongodb but that do not fail the tests?

**Comment by andy-ms** [comment]
Nah, just leave the dependency on the latest mongodb if possible. Most people will use the latest versions of typings for everything, so we should aim for as many things as possible to be compatible with mongodb v3.

**Comment by CaselIT** [comment]
Very well
Thanks 😉

**Comment by CaselIT** [comment]
@typescript-bot seem to have mistaken this for a new definition.
Pinging the authors to they can review @alanmarcell @kikar @bitjson @dante-101 @mcortesi

**Comment by CaselIT** [comment]
@mhegazy seems like the @typescript-bot is a bit of a rebel 😄

**Comment by avikalpa** [comment]
If the update to v3 is completed, then push it to ```npm @types/mongodb```. 😃 

Currently npm houses ```@types/mongodb@2.2.18``` as the latest.

**Comment by CaselIT** [comment]
@avikalpa  Npm will be automatically updated once this pr is merged.
It's still waiting for reviews by the other authors

**Comment by ohrrkan** [comment]
Hi guys,

Seems : https://github.com/CaselIT/DefinitelyTyped/blob/9427cc6db08f4490a6f312debedadfa2effd624a/types/mongodb/index.d.ts#L28

need an extends EventEmitter : 
export class MongoClient extends EventEmitter {


SRC  : https://jira.mongodb.org/browse/NODE-1267?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=1767134#comment-1767134

**Comment by CaselIT** [comment]
@ohrrkan  it should be fixed now. Thanks for the review!

**Pull request merged**
