### PR TITLE
Add generics to d3.d.ts

### PR DESCRIPTION
**Pull request by gustavderdrache**
This is a complete rewrite of d3.d.ts and is extensively breaking. By way of apology for the utterly massive pile of changes this brings in, I'm going to list what happened and why:
## Name Reorganization

Any empty namespace (things like `D3.Svg` and `D3.Geo`) have been removed, along with `D3` itself.

Type names follow the path of their associated constructor function: `d3.rgb()` returns a `d3.Rgb`, and `d3.svg.line.radial()` returns a `d3.svg.line.Radial`.
## Selections

Selections are now parameterized by their bound data. Most code should be compatible, but usage of the `.datum` method may cause some type issues. This in fact broke a test. Thanks to type unions, usage of `(d, i) => ...` can be inferred even in the object case.
## Sets

Since `d3.set` only uses string keys, it is no longer generic.
## Interpolators

Interpolation requires two values: the input value and the resulting interpolated value. This exists largely to support the interpolation of `d3.color` and its subclasses; `d3.interpolate(d3.rgb("#000"), d3.rgb("#fff"))` returns a function of `(t: number) => string`. However, there is a one-parameter variation of `d3.interpolate` that most users will find useful: `d3.interpolate("#fff", "#000")` will just work.
## Scales

Due to the interpolation issue above, scales require two parameters due to their `.interpolate` method. Constructor functions accept single-parameter variations for ease of use: `d3.scale.linear<number>()` constructs a scale whose domain and range are both numeric.
## Generators

Generators (SVG graphics, controls, and the layout functions) have zero-parameter variations that accept the D3 default types (i.e., area generators expect `Array<[number, number]>`).
## Layouts that Write to Values

Layouts like `d3.layout.tree` write values to their input. I've mimicked this with a type called `Result` which has a suite of the optional properties that are populated on a node. Input values are expected to extend this interface. Since the values are computed, they are not required on creation.
## Inheritance

D3 uses inheritance very, very sparsely. I removed any base types. They became incredibly difficult to sustain due to the way D3 changes some methods around.

The biggest offenders here are the generators and their radial equivalents. `d3.svg.line.radial()` actually creates a `d3.svg.line` under the hood, but it deletes the `x` and `y` methods, renaming them to `radius` and `angle`. It is much easier to treat the line and its radial equivalent as disparate types.
## CSV, TSV, DSV

Delimiter-separated value parsers return property bags of type `{ [key: string]: string }` instead of `any`. 
The code is parameterized over row functions, so most code will need to change uses of `d3.csv` and friends to include a row function. This is most apparent in the tests, which relied on the `any` type to pretend that the data was pre-converted.
## Overloads

D3's flexibility was extremely difficult to work with in places. I think I captured most of the spirit. However, I may have missed some edge cases. See also the `d3.extent` tests, where I had to disable some invocations because TypeScript 1.4's lib.d.ts thinks `Number.prototype.valueOf` returns an `Object` instead of a `number`.
## Other Changes

I had to rewrite `d3.layout.cloud`. It follows the pattern established by other generators, and is generic over the result interface `Word`.
## Open Issues
- The handling of `Event` is less than ideal. D3 likes to attach arbitrary properties, and it's hard to guarantee when they exist and when they don't.
- What D3 considers a "scale" varies from control to control. I ended up defining a `Scale` interface that represented what that particular control used.
- I have more than likely broken the dcjs typings. I'm not familiar with dcjs, so I was only able to make minor changes.
- I haven't added documentation comments for most of the types, functions, and modules in this library.
- There is a really strong probability that these types are overly precise.

### CODE REVIEW

**Comment by horiuchi** [comment]
@hansrwindhoff @mtraynham Please review this PR.

**Comment by hansrwindhoff** [comment]
Hello Alex (@gustavderdrache , I know what this means ;) I don't understand how you got the test to compile with the --noImplicitAny flag set. I had to change a bunch of places in the the tests. I am sending a patch (https://dl.dropboxusercontent.com/u/8561342/alexford/0001-get-d3-test.ts-to-compile-with-noimplicitany-add-tsc.patch), I also added atom editor tsc plugin tsconfig.json files, not sure if we want to keep those around in general...@borisyankov? 
In general I think putting the generics in is an excellent idea. It didn't break the dcjs stuff for me.

**Comment by mtraynham** [comment]
Couldn't have said it better than @hansrwindhoff, this is really awesome.  I probably won't be able to check the whole thing tonight, but I can give some notes over the next day or so.

One thing I noticed, and confined to the usage you have for [Primitive](https://github.com/gustavderdrache/DefinitelyTyped/blob/7600257d34baa6305ee1da58245242926960d5a8/d3/d3.d.ts#L424), does Date or anything that specifies `valueOf` on it's prototype belong as well?  I only ask, because I've had a case in the past where an [ordinal](https://github.com/gustavderdrache/DefinitelyTyped/blob/7600257d34baa6305ee1da58245242926960d5a8/d3/d3.d.ts#L1636) scale's domain was based on a set of a dates, and was not treated like a continuous domain.

I was going to add the [extended geo library](https://github.com/d3/d3-geo-projection) sometime in the next week or so, I'll likely follow suit with what you've done here.  Again, this is really good stuff.

**Comment by gustavderdrache** [comment]
@hansrwindhoff -- Good catch on the noImplicitAny. That was a step I completely missed. I looked over your patch and the tests and added type annotations. There were quite a few places where I could give a stronger type than `any`, so I did that. I'm not sure about adding the tsconfig.json, so I left it out. This pull request is already pretty big.

@mtraynham -- I played with `d3.scale.ordinal` more, and it turns out that I really should've used string coercion. Ordinal scales are parameterized over two arguments. The domain array is preserved, so it's safe to use `Date`s or even a custom type that implements its own `toString` function. This ought to catch quite a few cases I missed, such as using D3 colors.

**Comment by mtraynham** [comment]
@gustavderdrache That does look better, thanks!

Also, can we identify which other libraries depend on d3 that also need to change as well.  I made updates to `dc.js` recently, so that will need to be updated as well.  Once this PR is finished, it may be good to open bugs on the others.

**Comment by gustavderdrache** [comment]
I changed the libraries that I know I broke (dc.js is among them), but they'll need someone more familiar with them to really correct it. The build is passing, so there at least aren't invalid references. But I do know that this will break a handful of open PRs against D3, so we'll want to keep an eye out for those.

**Comment by mtraynham** [comment]
Ahh I see, overlooked the bottom.  It's kind of unfortunate that scales don't inherit from a a base scale sharing the following properties:
- domain
- range
- copy

Specifically in cases like:
https://github.com/borisyankov/DefinitelyTyped/pull/3999/files#diff-3b4e05c4d0fb325a49f97f31c4951eceR328

But I can see how the typing may make it hard to properly convey that.

**Comment by gustavderdrache** [comment]
Yeah, it's troublesome, but I found that the easiest thing to do is create an interface specifically for that scale type. If, for example, the scale needs to be `number => string` and have a mutable domain, then it's not too much hassle to create an interface like so:

```
interface Scale {
    (n: number): string;

    domain(): number[];
    domain(values: number[]): Scale;
}
```

The compiler can sort out structural compatibility. It makes it easier for the user to provide custom scales and it keeps the type definitions honest, in the sense that they don't invent type hierarchies that don't really exist. Right now the dc.js scales are just raw functions because I wasn't sure of the usage patterns. (This is why all the layouts have their own `Link` type despite them having the same shape.)

The really egregious part about having a "base" scale is that it really doesn't help anything: TypeScript doesn't have a good notion of "returns self" in setters. `d3.scale.pow().domain(foo)` has the base scale type and therefore loses all of its extra properties. At that point, you have to copy _all_ the properties and we've just duplicated work. This exact thing happened to me with the [DSV-specific XHR](https://github.com/gustavderdrache/DefinitelyTyped/blob/master/d3/d3.d.ts#L2654), which [actually does inherit](https://github.com/mbostock/d3/blob/master/src/dsv/dsv.js#L8) from d3.xhr, but the setters' return types don't reflect the subtype.

**Comment by mtraynham** [comment]
> ...in the sense that they don't invent type hierarchies that don't really exist.

I agree.  And hopefully in the future d3.js does take better advantage of structure sharing.  

But maybe just specific to `dc.js` we should be more definitive about the types of scales it can handle instead of that `any` functor.  I don't believe the charts can handle scales other than the one's provided by d3.  If they do, I imagine the number of users doing so is slim to none.  So being stricter at compile time, reducing the amount of casting, as well as lending type inference to the text editors really does help.

Something like this added to `dc.js`:
```
export type GenericScale = d3.scale.Identity | d3.scale.Linear | d3.scale.Pow | d3.scale.Quantize | d3.scale.Quantile | d3.scale.Threshold | d3.scale.Ordinal | d3.time.Scale
```

Although, I havn't tried this before, so I'm assuming it will work.

**Comment by gustavderdrache** [comment]
It's not as easy as it seems, unfortunately. Most default D3 scales use numbers, but there's the potential for an x axis to use time scales instead. At that point you're better off looking for a scale that maps the input domain to something expected.

As an example, the [color mixin](https://github.com/dc-js/dc.js/blob/develop/src/color-mixin.js#L99-L118) only requires a function with an additional `domain(Array)` method, as parameterized by a color accessor and the data array. We can't actually make any guarantees about the underlying type, because the default scale is just `d3.scale.category20`, which happily accepts anything that turns into a string. One user may tag data by date, but another may use string IDs. The interface would look kind of like this:

```typescript
/**
 * A scale that maps a datum of type T to a color.
 */
interface ColorScale<T> {
    (x: T): string | d3.Color;

    domain(values: T[]): ColorScale<T>;
}

/**
 * Provides universal coloring support as a mix-in.
 */
interface ColorMixin<Datum, Color> {
    colorAccessor(accessor: (d: Datum, i: number) => Color): ColorMixin<Datum, Color>;

    getColor(d: Datum, i: number): string | d3.Color;

    colors(scale: ColorScale<Color>): ColorMixin<Datum, Color>;
}
```

But this interface doesn't extend to other scales: the [bubble mixin](https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#bubble-mixin) has a radius function that is, by default, `number => number`, but there's no reason we can't use string tags of `'small'`, `'medium'`, and `'large'`. That gives us something like this:

```typescript
/**
 * A linear scale for bubble chart radii.
 */
interface RadiusScale<T> {
	(x: T): number;
}

/**
 * A bubble chart mixin.
 */
 interface BubbleMixin<Datum, Radius> {
	 radiusValueAccessor(accessor: (d: Datum) => Radius): BubbleMixin<Datum, Radius>;
	 
	 r(radius: RadiusScale<Radius>): BubbleMixin<Datum, Radius>;
	 
	 bubbleR(d: Datum): number;
 }
```

This does get insanely complicated, and the reason for it is this:
```
> dc.bubbleChart()
    .radiusValueAccessor(function () { return "small"; })
    .r(function (d) { return d === 'small' ? 20 : 100 })
    .bubbleR({});
20
```

**Comment by mtraynham** [comment]
Mmm yeah, I see what you're getting at when you add in the context of the accessors.  I'm still on the fence because there is now the expectation that you only have to pass an `any` functor, which may/may not contain `domain` and `range` (or `rangeBand`) properties, even though dc expects them.

For instance, dc's coordinate grid does make the assumption that it is being passed a valid d3 scale:
https://github.com/dc-js/dc.js/blob/develop/src/coordinate-grid-mixin.js#L25

I've looked over a lot of the other changes.  LGTM.

I did mean to ask one last thing:
https://github.com/gustavderdrache/DefinitelyTyped/blob/master/d3/d3.d.ts#L1309
Is that valid?  I tried that in a [previous request](https://github.com/mtraynham/DefinitelyTyped/commit/516266a0ac7cc5f8b4e64ae9998121ff9306aad5#diff-9eb3fdff1a5a5638bdfa7d4c2c84ff00R853) and Webstorm seemed to complain about using `typeof` within the method signature's arguments.  I know Webstorm has had it's own share of problems, but I think I was on TS1.3 at the time, and don't remember if the tests passed or not.

**Comment by gustavderdrache** [comment]
A `typeof` query is legal in that position. I don't use Webstorm, but it seems like it's in the wrong given the spec (§3.7.9, "Type Queries"). It compiled cleanly for me locally (1.4.1 compiler), so I don't foresee any complications.

As far as the dc.js typings go, it seems more prudent to open a new bug so that others who have worked on the project can provide guidance on what scales are used where.

In the immediate case, it may be good enough to create an interface type `Scale<Range>` which has `domain` and `range` accessors and use that everywhere. It'd be customized to accept an `any` type (given the input issues) but have output types appropriate to the usage (`number` for the radius example above and `string` for the color one). Thoughts?

**Comment by mtraynham** [comment]
Sounds good to me :)

**Comment by gustavderdrache** [comment]
Done. I picked over the diff and replaced the annotations with `Scale<T>`, but do you mind double-checking and making sure I didn't miss one?

**Comment by hansrwindhoff** [comment]
@gustavderdrache I will try to take a look tonight?

**Comment by hansrwindhoff** [comment]
@gustavderdrache I plugged your new headers d3.d.ts and d3.cloud.layout.d.ts into a ~25k line ts d3js project, got ~350 compilation errors. After a simple rename of the newly named force interfaces I am down to ~100 errors. 
One thing that I find problematic is, that some of the remaining errors are around the Event interface that now comes from lib.d.ts and doesn't contain many of the valid fields I had from the d3 version of the event (was called D3Event). Are you sure this is the correct interface?
Also in the force node the size property is gone... Before I plugged in the new headers, I updated my d3.js to the latest 355. And the code runs, so I think these properties are actually there. I have not had the time to go through every error, but I guess I would maybe put this in a new branch and we can iron the details out...?
There are also some valid errors that are discovered by the generic versions of the new definitions, that's really cool! Things where the vars were typed any and are now getting the types flowing into them, the stuff I was doing was some sort of shortcut...so that is great. 
All in all I think this very nice!! Good stuff.

**Comment by gustavderdrache** [comment]
The `event` object is really annoying to handle... it's a global that has arbitrary properties glued on to it based on the dynamic context (see [selection/on.js](https://github.com/mbostock/d3/blob/master/src/selection/on.js#L85-L96)), which is difficult to give a proper type to. I suppose it may just be simplest to have `d3.event`'s type be an aggregation of the various standard DOM events, with extra properties added on by the core event handlers:

```typescript
interface Event extends KeyboardEvent, MouseEvent /* etc */ {
    // ...
}
```

As far as the force node `size` is concerned, [it is not documented as existing](https://github.com/mbostock/d3/wiki/Force-Layout#nodes), so I didn't include it. One quirk of TypeScript's inference is that if you have this code:

```typescript
interface Foo {
    size: number;
}

var foos: Foo[];

var layout = d3.layout.force().nodes(foos);
```

The layout is of type `Force<force.Node>` and you lose the extra properties on `Foo`.

**Comment by gustavderdrache** [comment]
Temporarily closing this request: I made a major oopsie in the merge resolution.

**Pull request closed without merging**
