### PR TITLE
Update knockout-postbox.d.ts

### PR DESCRIPTION
**Pull request by eriksimonic**
Added disposeTopic(topic: string): void; method to KnockoutPostBox

### CODE REVIEW

**Comment by sandersn** [comment]
I looked at the [knockout-postbox source](https://github.com/rniemeyer/knockout-postbox/blob/master/src/knockout-postbox.js) and couldn't find `disposeTopic` assigned to `exports`. Are you sure this is part of the current version of knockout-postbox?

**Comment by eriksimonic** [comment]
Stupid me, I did remember now that I had add the function to the library / bah..
I will make a suggestion to knockout-postbox to add the method as is very useful.

Can you wait with the pull/reject? I will get back when I do have some more information.
Thanks.

**Comment by paulvanbrenk** [comment]
@eriksimonic gentle ping

**Comment by andy-ms** [comment]
If it won't be added any time soon, we should probably close this.

**Pull request closed without merging**
