### PR TITLE
fix(papaparse): Add a common overload to accept file or string

### PR DESCRIPTION
**Pull request by OpportunityLiu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.papaparse.com/docs#config>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]

**Comment by dobesv** [comment]
It seems like after adding this overload, typescript won't select the overload for 

```
export function parse(stream: typeof NODE_STREAM_INPUT, config?: ParseConfig): NodeJS.ReadWriteStream;
```

Instead it picks the new overload and complains we are trying to use a `void` value.

I'm not quite sure what to do about this ... it's really a shame papa parse didn't use a different name for the stream version.

**Comment by OpportunityLiu** [comment]
> It seems like after adding this overload, typescript won't select the overload for
> 
> ```
> export function parse(stream: typeof NODE_STREAM_INPUT, config?: ParseConfig): NodeJS.ReadWriteStream;
> ```
> 
> Instead it picks the new overload and complains we are trying to use a `void` value.
> 
> I'm not quite sure what to do about this ... it's really a shame papa parse didn't use a different name for the stream version.

You should use `NODE_STREAM_INPUT` for the first param for the stream API. I marked it as a unique symbol despite of that it is in fact a number, since the value of `NODE_STREAM_INPUT` should be opaque to users of papaparse. Users should always use `NODE_STREAM_INPUT` not `1`.

**Comment by dobesv** [comment]
> You should use `NODE_STREAM_INPUT` for the first param for the stream API

That's exactly what I am doing, but I am getting the complaint above if I try to update to the latest `@types/papaparse`.  I think the generic makes that first overload match pretty much anything.

**Comment by dobesv** [comment]
It seems like the error occurs if you pass options.  This case wasn't covered by the existing tests, apparently.

```
$ npm test papaparse

> definitely-typed@0.0.3 test
> dtslint types "papaparse"

Error: /home/ubuntu/DefinitelyTyped/types/papaparse/papaparse-tests.ts:161:7
ERROR: 161:7   expect              TypeScript@4.6 compile error: 
Type 'void' is not assignable to type 'ReadWriteStream'.
ERROR: 161:55  no-void-expression  Expression has type `void`. Put it on its own line as a statement.
ERROR: 162:5   expect              TypeScript@4.6 compile error: 
No overload matches this call.
  The last overload gave the following error.
    Type 'true' is not assignable to type 'string | false | undefined'.

    at testTypesVersion (/home/ubuntu/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:189:15)
    at async runTests (/home/ubuntu/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:165:13)
    at async main (/home/ubuntu/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:77:9)
18:53:25 ~/DefinitelyTyped (detached*)*
$ git diff
diff --git a/types/papaparse/papaparse-tests.ts b/types/papaparse/papaparse-tests.ts
index a9e9fb93dd..6c902be263 100644
--- a/types/papaparse/papaparse-tests.ts
+++ b/types/papaparse/papaparse-tests.ts
@@ -158,6 +158,14 @@ const papaStream: NodeJS.ReadWriteStream = Papa.parse(Papa.NODE_STREAM_INPUT);
 
 readable.pipe(papaStream);
 
+const papaStreamWithOptions: NodeJS.ReadWriteStream = Papa.parse(Papa.NODE_STREAM_INPUT, {
+    comments: true,
+    header: true,
+    skipEmptyLines: 'greedy',
+});
+
+readable.pipe(papaStreamWithOptions);
+
 // generic
 Papa.parse<string>('a,b,c', {
     step(a) {

```

**Comment by dobesv** [comment]
Not quite sure at the moment what the fix would be here, I would have expected typescript to pick the one for the stream in this case but it's probably picking one of the generic functions that is also compatible.

**Comment by dobesv** [comment]
Actually, it seems to be just a confusing error.  The real problem is that `comments` doesn't accept `true` as a value.  So I guess it got a type error and picked an arbitrary overload.  Sorry for the noise.

**Comment by OpportunityLiu** [comment]
image

After fix the `comment` part, it got corrected.

**Comment by OpportunityLiu** [comment]
`comment: true` makes all overloads failed to match, so the first is used for error resuming.

**Comment by dobesv** [comment]
@OpportunityLiu Exactly.  Thanks for confirming.  The error I was getting confused me but it is indeed because I passed the wrong type of value for `comments`.

**Pull request merged**
