### PR TITLE
@types/antlr4 - Fix InputStream.LA() and InputStream.LT() declarations

### PR DESCRIPTION
**Pull request by jgellin-sf**
Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/InputStream.js

InputStream.LA() and InputStream.LT() return a char code or code point, which is a number and not a string.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## antlr4 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/antlr4@latest/))
was missing the following properties:
1. atn
1. codepointat
1. dfa
1. fromcodepoint
1. tree

<details>
<summary>as well as these 5 other properties...</summary>
<p>error, CharStreams, FileStream, PredictionContextCache, Utils</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ca50f08d9ef2626300b2a96d92c96f3e7279cb77
</p>

**Comment by tarilabs** [comment]
@jgellin-sf looks good to me, on the basis that
either this (`String.prototype.codePointAt()`): https://github.com/antlr/antlr4/blob/eb1adaa8a7a6993803f08f5ffa0350a45eb24a13/runtime/JavaScript/src/antlr4/InputStream.js#L27 
or either this (`String.prototype.charCodeAt()`): https://github.com/antlr/antlr4/blob/eb1adaa8a7a6993803f08f5ffa0350a45eb24a13/runtime/JavaScript/src/antlr4/InputStream.js#L33

return a number, so `this.data` is an array of number, used as a basis for the two methods you highlight.

I'm not an expert in this repo, but I understand if you provide some tests it can eventually be merged more easily.
Do you want to add a small test? Maybe you can take inspiration from here: https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/antlr4/antlr4-tests.ts#L2160

Finally, don't forget to evaluate to add your name to the `index.d.ts` file if you wanted to ;)

Let me know!

**Comment by jgellin-sf** [comment]
@tarilabs Thanks for the quick review. I added tests and put my name in the `index.d.ts`.

**Review by tarilabs — APPROVED** [review]
addressed all open points and looks good to me as detailed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46137#issuecomment-659652785

thank you for your contributions!

**Comment by jgellin-sf** [comment]
Ready to merge

**Comment by qqaimh** [comment]
Will support version4.8 ？

**Pull request merged**
