### PR TITLE
[node] Explicitly mention Error as a type for "reason" argument for UnhandledRejectionListener

### PR DESCRIPTION
**Pull request by FlyingDR**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Node.js documentation](https://nodejs.org/docs/latest/api/process.html#process_event_unhandledrejection)

Node.js documentation for `unhandledRejection` event of the `process` defines that while `reason` argument can get the value of any type - in most cases it will receive an instance of `Error`.  

This PR adds `Error` as an explicit part of the type definition for this argument to reflect documentation.

Type itself is not completely correct, but it was changed from `any` by 819e30f49880da50e2c72fc27778d2dc0bc5d860

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@FlyingDR please update from master and push changes, there were changes in other DT packages that are part of Node ecosystem CI tests, thx!

**Comment by FlyingDR** [comment]
@peterblazejewicz Failed build for this pull request seems to be caused by (or at least related to) #57023. 

There are two failed packages and both were changed as part of that pull request:
 - `ari-client` ([change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57023/files#diff-366fb2a67ef90c00973132d96cb390178dc6c4a432268f673e81a0deee2acd8b))
 - `hapi-pino` ([change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57023/files#diff-28146525cbfe6208fb23406f9b9fd9142de87961d75fae7d7fb8074f22ff2e1d))

Here is a line that causes an issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/22c9dda13fe14635394ed06320ad42ff1da34294/types/pino-pretty/index.d.ts#L7

This is quite right because `pino` is not here anymore. 

Experment with replacing this line with explicit type definition:
```diff
-import { LogDescriptor } from "pino";
+type LogDescriptor = Record<string, any>;
```
fixes build.

Could you please suggest a way to improve the situation?

**Comment by peterblazejewicz** [comment]
working on fix

**Comment by peterblazejewicz** [comment]
fixing CI resolutions: #57241

**Review by SimonSchick — CHANGES_REQUESTED** [review]
I am unsure what this achieves, you will still need to use type assertions (or real assertions).
This should be changed to `unknown`.

**Comment by FlyingDR** [comment]
> I am unsure what this achieves, you will still need to use type assertions (or real assertions). This should be changed to `unknown`.

As I wrote in pull request description - there was a change in 819e30f49880da50e2c72fc27778d2dc0bc5d860 from any to this compound type. Since it was merged - I've decided to not expand this type back to a broader type.

However it looks like the previous commit was made at a time before TypeScript 3, so it is a good idea to change to `unknown`. 

I will update definitions to use `unknown` instead, thank you for a suggestion.

**Review by SimonSchick — COMMENTED** [review]
Sorry I should've been more clear, this should be strictly ONLY `unknown` since `unknown | Error` => `unknown`.

**Comment by LinusU** [comment]
I think this is a very good change (with the change to only `unknown`) since the current types are simply wrong. This can be demonstrated with e.g.

```js
Promise.reject(1)
Promise.reject(false)
Promise.reject('test')
Promise.reject(Symbol('test'))
```

**Comment by FlyingDR** [comment]
> Sorry I should've been more clear, this should be strictly ONLY `unknown` since `unknown | Error` => `unknown`.

Surely, I understand that `Error` can be omitted in the case of the presence of `unknown`. I keep it to let type definition to be compatible with one in [Node.js documentation](https://nodejs.org/docs/latest/api/process.html#process_event_unhandledrejection), which is also not completely correct since `Error | any => any`

@SimonSchick Technically current version is not wrong, but if you think that it is better to use `unknown` explicitly - I will update the code.

Completely agree with @LinusU

**Comment by SimonSchick** [comment]
It's not wrong but it doesn't really add any value to most users as the type union ultimately becomes `unknown`.
I'm concerned that developers will get confused rather than helped by the type union.

I think the most valuable thing we can do here is adding a docstring that states `most of the time the unhandledRejection will be an Error, but this should not be relied upon as *anything* can be thrown/rejected, it is therefor unsafe to assume the the value is an Error.`.


FYI: The reason why we used `{} | null` before was that `unknown` simply wasn't available (and I overlooked it when moving various `any` to `unknown`), there was a long discussion about this `poor man's unknown` which luckily is no longer needed.

**Review by SimonSchick — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by FlyingDR** [comment]
Ready to merge

**Pull request merged**
