### PR TITLE
react-syntax-highlighter styles moved to dist/

### PR DESCRIPTION
**Pull request by Vinnl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/conorhastings/react-syntax-highlighter/blob/master/CHANGELOG.MD#1000
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`

Looking at the package layout in my installed project, it appears that `/languages` has been moved to `/dist/languages` as well, and that `/light`, `/prism` and `/prism-light` have also been moved to `/dist/light`, `/dist/prism` and `/dist/prism-light`, respectively. However, since I don't use those features myself, I can't test them in my own code. Would be happy to submit a PR changing that otherwise.

### CODE REVIEW

**Review by jessetrinity — CHANGES_REQUESTED** [review]
@Vinnl could you add a version to this? It looks like react-syntax-highlighter is in [10.1](https://www.npmjs.com/package/react-syntax-highlighter). You will need to enable "dt-header" in ```tslint.json```.

**Comment by Vinnl** [comment]
@jessetrinity Done!

**Comment by Vinnl** [comment]
@jessetrinity Done!

**Review by jessetrinity — APPROVED** [review]

**Comment by jessetrinity** [comment]
@Vinnl  Awesome, Thanks for contributing!

**Pull request merged**
