### PR TITLE
feat(auth0): add `decode` and `validate`

### LINKED ISSUE #50364: [@types/auth0] Decode and Validate missing
@ianhowe76
@peterblazejewicz 
@RyanCavanaugh 

Missing [decode](https://auth0.github.io/node-auth0/global.html#decode) and [validate](https://auth0.github.io/node-auth0/global.html#validate).

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- export `auth/src/idToken` module `decode` and `validate`
- amend tests
- add maintainer
- version bump
- minor DT linter change for header

https://auth0.github.io/node-auth0/global.html

Thanks!

/cc @jonathaneckman

Closes #50364

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by rbutera** [comment]
> - export `auth/src/idToken` module `decode` and `validate`
> 
> - amend tests
> 
> - add maintainer
> 
> - version bump
> 
> - minor DT linter change for header
> 
> 
> 
> https://auth0.github.io/node-auth0/global.html
> 
> 
> 
> Thanks!
> 
> 
> 
> /cc @jonathaneckman
> 
> 
> 
> Closes #50364
> 
> 
> 
> - [x] Use a meaningful title for the pull request. Include the name of the package modified.
> 
> - [x] Test the change in your own code. (Compile and run.)
> 
> - [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
> 
> - [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
> 
> - [x] Provide a URL to documentation or source code which provides context for the suggested changes
> 
> - [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Please fix merge conflicts and ensure I am kept as owner, thanks!

**Comment by peterblazejewicz** [comment]
> Please fix merge conflicts and ensure I am kept as owner, thanks!

Done, thx!

**Review by rbutera — APPROVED** [review]

**Comment by rbutera** [comment]
Ready to merge

**Comment by rbutera** [comment]
Ready to merge

**Comment by solymosi** [comment]
I believe the new version number is incorrect. `auth0` is on version `2.3X.X` these days, not on `2.3.X` ⚠️

**Comment by peterblazejewicz** [comment]
@solymosi it looks so, let me fix

**Pull request merged**
