### PR TITLE
add PaymentRequest spec

### PR DESCRIPTION
**Pull request by AdamCmiel**
Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Run `tsc` without errors.
- [X] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: https://www.w3.org/TR/payment-request/
- [X] Increase the version number in the header if appropriate.  - w3c standard

### CODE REVIEW

**Comment by AdamCmiel** [comment]
this is a spec from w3c, the tests would be in the browser engine, how can I move forward with this proposal?

**Comment by vvakame** [comment]
cc/ @RyanCavanaugh

**Comment by paulvanbrenk** [comment]
@AdamCmiel Can you add some tests which show the usage for the API in the definition file.

**Comment by AdamCmiel** [comment]
@paulvanbrenk are the tests expected to run?  PaymentRequest is only defined in Android Chrome 53

**Comment by AdamCmiel** [comment]
@paulvanbrenk g2g?

**Comment by paulvanbrenk** [comment]
Looks good to me, but I'm wondering if this shouldn't be part of the `lib.d.ts` when browsers implement this? 

I guess we can take this now, and add it to the `lib.d.ts` at that point... thoughts @RyanCavanaugh or @mhegazy?

**Comment by Garbee** [comment]
Chrome at least now has this implemented in 53 for Android. So one vendor is shipping it in stable currently.

**Comment by mohsen1** [comment]
@paulvanbrenk  can you add depreciation warning to @type packages? This should be deprecated with a warning that tells users to use TypeScript dom.d.ts instead.

**Comment by paulvanbrenk** [comment]
@mohsen1 feel free to open a PR. I just merged this in, I have no further context.

**Pull request merged**
