### PR TITLE
[relay-test-utils] Create new package

### PR DESCRIPTION
**Pull request by renanmav**
Depends on #38692 to be merged (I made some adjusts on `relay-runtime`)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by alloy** [comment]
@renanmav Nice one 👌

**Comment by renanmav** [comment]
Thanks. Next one is `babel-plugin-relay`.

**Comment by alloy** [comment]
Huh, you need to access `babel-plugin-relay` from TypeScript? How so?

**Comment by renanmav** [comment]
When I'm using CRA, I need to use the graphql from [`babel-plugin-relay/macro`](https://relay.dev/docs/en/installation-and-setup#set-up-babel-plugin-relay). Typescript warns me that this package does not have a type, so I'll create it.

**Pull request merged**
