### PR TITLE
remove(stylelint): no longer needed

### PR DESCRIPTION
**Pull request by ybiquitous**
`stylelint@14.0.0` has added its type definitions. See below:

- https://github.com/stylelint/stylelint/releases/tag/14.0.0
- https://github.com/stylelint/stylelint/pull/5582

Note: This change is created by the `npm run not-needed -- stylelint 14.0.0` command.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Review by bmatcuk — APPROVED** [review]
👍

**Review by filips-alpe — APPROVED** [review]
Thanks!

**Review by peterblazejewicz — APPROVED** [review]

**Review by alan-agius4 — APPROVED** [review]

**Review by bmatcuk — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by ybiquitous** [comment]
Ready to merge

**Pull request merged**
