### PR TITLE
FIX: #14693

### LINKED ISSUE #14693: @types/loopback
- [x] I tried using the `@types/loopback` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kattsushi 

There are various mistakes in the definitions file.  app.middleware should have Handler instead of empty function, also settings in the built-in models are not array of ACLs which they should be. PersistedModel is also not extending Model.

### PR DESCRIPTION
**Pull request by bariscicek**
FIX #14693 for app.middleware should have Handler istead of empty function, also
settings in the built-in models are not array of ACLs which they should
be. PersistedModel is also not extending Model.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://apidocs.strongloop.com/loopback/#app-middleware
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by bariscicek** [comment]
Commited fix for #14697

**Review by kattsushi — APPROVED** [review]
Thanks ! good contribution

**Comment by zhengbli** [comment]
Thank you for your contribution.

Can you please fix the failing Travis CI tests and update the PR?

**Comment by bariscicek** [comment]
Done

**Comment by bariscicek** [comment]
@zhengbli comment to mention.

**Review by kattsushi — APPROVED** [review]

**Pull request merged**
