### PR TITLE
[react] Make all refs mutable by default

### PR DESCRIPTION
**Pull request by eps1lon**
Ready for review but won't be merged here and rather in a PR for 19 stacking all changes from https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64451

Closes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64855
Closes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64772
Fixes first gotcha in https://twitter.com/mattpocockuk/status/1636098722982404096 (second one will be fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64920).

```diff
 interface RefObject<T> {
-   readonly current: T | null
+   current: T
 }
```

`RefObject` is no longer considered a ref managed by React (i.e. it no longer makes `current` nullable). Instead, `current` will only have the type you declare and be mutable.

Historically `RefObject` was the type returned from `createRef` so it made sense to always include `null` since that what React does on initialization. The mistake we made was reusing it for `useRef` which has a different audience (`useRef` for function components where it can act as "instance variables", `createRef` for class components where we only care about React managed refs).

But now that we moved along it makes sense to fix this incorrect abstraction, take on a breaking change and reduce papercuts going forward.

## Migration

1. Update all `@types/*` packages to their latest versions
2. Apply `npx types-react-codemod refobject-defaults ./src` (see [`types-react-codemod`](https://github.com/eps1lon/types-react-codemod) for full usage)

The remaining fixes should only include libraries shipping their own types. Either these libraries are already compatible with React 19 types and you just need to upgrade them or you should raise an issue on their repositories notifying them that their types are not compatible with React 19.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## babel-plugin-react-html-attrs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/babel-plugin-react-html-attrs@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'babel-plugin-react-html-attrs'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
## gatsbyjs__reach-router ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gatsbyjs__reach-router@latest/))
was missing the following properties:
1. BaseContext
1. LocationContext
1. insertParams
1. match
1. navigate

<details>
<summary>as well as these 8 other properties...</summary>
<p>pick, resolve, shallowCompare, startsWith, useBaseContext, useLocationContext, useNavigate, validateRedirect</p>
</details>

## reach__router ([<kbd>unpkg</kbd>](https://unpkg.com/browse/reach__router@latest/))
was missing the following properties:
1. matchPath
## react-bootstrap-typeahead ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-bootstrap-typeahead@latest/))
was missing the following properties:
1. useHint
1. Input
1. asyncContainer
1. useAsync
1. withAsync

<details>
<summary>as well as these 5 other properties...</summary>
<p>menuItemContainer, useItem, withItem, tokenContainer, withToken</p>
</details>

## react-map-gl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-map-gl@latest/))
was missing the following properties:
1. AttributionControl
1. setRTLTextPlugin
1. MapContext
1. AttributionControl
1. setRTLTextPlugin

<details>
<summary>as well as these 1 other properties...</summary>
<p>MapContext</p>
</details>

## react-onclickoutside ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-onclickoutside@latest/))
was missing the following properties:
1. IGNORE_CLASS_NAME
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
## tuya-panel-kit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tuya-panel-kit@latest/))
was missing the following properties:
1. Drawer
1. Wave
1. Diffusion
1. OfflineView
1. FullView
## wordpress__components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__components@latest/))
was missing the following properties:
1. CustomGradientPicker
1. DuotonePicker
1. DuotoneSwatch
1. GradientPicker
1. GuidePage

<details>
<summary>as well as these 28 other properties...</summary>
<p>Line, SearchControl, TextHighlight, ToolbarDropdownMenu, ToolbarItem, useBaseControlProps, CustomGradientPicker, DuotonePicker, DuotoneSwatch, GradientPicker, GuidePage, Line, SearchControl, TextHighlight, ToolbarDropdownMenu, ToolbarItem, useBaseControlProps, CustomGradientPicker, DuotonePicker, DuotoneSwatch, GradientPicker, GuidePage, Line, SearchControl, TextHighlight, ToolbarDropdownMenu, ToolbarItem, useBaseControlProps</p>
</details>

## wordpress__rich-text ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__rich-text@latest/))
was missing the following properties:
1. store
1. store
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 95c7b2e0d27ccbd92c92dc77e2b4c4a4be895e10
</p>

**Comment by ericanderson** [comment]
I kept MutableRefObject around so that anyone using RefObject in their application code would not have the type change from under them and represented RefObject with MutableRefObject. It seemed like a cleaner deprecation path.

I also think if we are making breaking changes for React 19, we should not allow the zero argument version of `useRef()` since there are no documented uses in react. The behavior of `useRef<T>()` implying `{ current: T | undefined }` is really confusing to most people when we inherit `null` in the other cases. I think either `useRef<T>()` needs to be `{ current: T | undefined | null }` or needs to not exist. Both cover issue 2 in the referenced tweet.

**Comment by DiegoAndai** [comment]
Hi @eps1lon. What would be the recommendation for the refs that are handled by React, i.e.:

```jsx
const divRef = React.useRef<HTMLDivElement>(null)

// ...

<div ref={divRef} />
```

If I understand correctly, `divRef` will be mutable in React 19. Should we keep it as such even though it's not supposed to be mutated? Is this restriction outside of `@types/react`'s scope?

I don't have an opinion on it, just wondering what is the recommended usage.

**Comment by eps1lon** [comment]
> If I understand correctly, divRef will be mutable in React 19. Should we keep it as such even though it's not supposed to be mutated?

There was never such a restriction that you shouldn't mutate it. React will not read this value so you can write whatever you want into that value. You just need to be aware that React may overwrite what you wrote into the ref. But that would equally apply to all instances where you pass a `ref` to multiple places that will write to it.

**Comment by DiegoAndai** [comment]
Thanks for the reply!

> There was never such a restriction that you shouldn't mutate it.

This confuses me a bit, wasn't the `readonly` in 

```ts
interface RefObject<T> {
    readonly current: T | null;
}
```

A restriction about not mutating it?

**Comment by eps1lon** [comment]
> A restriction about not mutating it?

At the type level, yes. But types are in service to how we want React code to be authored. And there this restriction never existed.

**Comment by DiegoAndai** [comment]
Thanks for the clarification

**Pull request closed without merging**
