### PR TITLE
Add grouped joins

### PR DESCRIPTION
**Pull request by balazser**
Add orOn, andOn support. see: http://knexjs.org/#Builder-join
Join accepts subqueries. see: http://knexjs.org/#Builder-as

### CODE REVIEW

**Comment by baronfel** [comment]
Can you add an example to the test file next to the declarations?  Just replicating the example from the documentation would be fine in my opinion.

**Comment by baronfel** [comment]
Also I'm not sure the typing is quite correct here. I think we should be altering the signature of the `(tableName: string, callback: Function): QueryBuilder;` overload to replace the simple `Function` with the `(this: JoinClause): void` you've provided here.  What are your thoughts?

**Comment by balazserdos** [comment]
I wanted to use subquery then after some googling found that actually I'm able to but the typings didn't let me. Then I modified it locally and it works me.

```
 let selectBestPrice = this.knex.select([
            "exchange_rate.base_currency",
            "exchange_rate.quote_currency",
            "exchange_rate.buying_rate",
        ])
            .from(tables.EXCHANGE_RATE)
            .groupBy("base_currency", "quote_currency")
            .max("buying_rate")
            .as("best");

        let selecting = (this.knex.select([
            "exchange.id",
            "exchange.name",
            "exchange_rate.base_currency",
            "exchange_rate.quote_currency",
            "exchange_rate.buying_rate",
            "exchange_rate.selling_rate",
        ])
            .from(tables.EXCHANGE_RATE))
            .innerJoin(selectBestPrice, function() {
                return this.on('exchange_rate.base_currency', 'best.base_currency')
                    .andOn('exchange_rate.quote_currency', 'best.quote_currency')
                    .andOn('exchange_rate.buying_rate', 'best.buying_rate');
            })
            .innerJoin(tables.EXCHANGE, 'exchange.id', 'exchange_rate.exchange_id');
```

**Comment by baronfel** [comment]
You're exactly right, I forgot that the tablename was technically a builder.

**Comment by baronfel** [comment]
👍

**Comment by balazserdos** [comment]
thank you :)

**Pull request merged**
