### PR TITLE
vis - make font-options in interface "NodeOptions" optional

### PR DESCRIPTION
**Pull request by mkollers**
**It's already implemented that way in EdgeOptions**

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://visjs.org/docs/network/nodes.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by MichaelBitard** [comment]
Not sure to understand what you want to do here, is it something possible? Nothing is mandatory if you use the object instead of the string?

**Comment by mkollers** [comment]
Yes, you're right. In my case, i want to change "face" and "size", but perhaps you want to change only the color, so everything must be optional. If not, you have to define every property even if you just what to change one of them.

**Comment by MichaelBitard** [comment]
Ok, changing my vote to :+1:

**Comment by kaktus40** [comment]
:+1:

**Pull request merged**
