### PR TITLE
[react-native-auth0] Add customScheme typing (WebAuth ClearSessionParams and AuthorizeOptions)

### PR DESCRIPTION
**Pull request by julien-HAM**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - webauth.authorize support `customScheme` =>  https://github.com/auth0/react-native-auth0/blob/91c08f93d37e0dd2f2c41415ebb65f4cf720f1a4/src/webauth/index.js#L62-L71
  - webauth.clearSession support `customScheme`=> https://github.com/auth0/react-native-auth0/blob/91c08f93d37e0dd2f2c41415ebb65f4cf720f1a4/src/webauth/index.js#L149-L158
- [N/A] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by julien-HAM** [comment]
Hi @ascariandrea @marknelissen @leoafarias @willdady @Bogidon @yammesicka,

**Comment by julien-HAM** [comment]
Hi @ascariandrea @marknelissen @leoafarias @willdady @Bogidon @yammesicka - Any chance one of you could look at the PR please?

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by julien-HAM** [comment]
Ready to merge

**Comment by julien-HAM** [comment]
> LGTM

Thank you

**Pull request merged**
