### PR TITLE
[xlsx] Add cell value types

### PR DESCRIPTION
**Pull request by DMan577**
1. The cell's raw value can also be a `number`, `boolean` or `Date` ([Data Types](https://github.com/SheetJS/js-xlsx#data-types))
2. Added `IWritingOptions` interface ([Writing Options](https://github.com/SheetJS/js-xlsx#writing-options)) for the `write` function because it's different from the `IParsingOptions` (as described in #14974 )
3. Removed `bookType` property from `IParsingOptions`, because it isn't a valid option ([Parsing Options](https://github.com/SheetJS/js-xlsx#parsing-options))
4. Added the comments from the main docs.
5. Added the `writeFile` function as described in [Writing Functions](https://github.com/SheetJS/js-xlsx#writing-functions)
6. Added missing `{en,de}code_{row,col}` util functions ([Utilities](https://github.com/SheetJS/js-xlsx#utilities)). 

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/SheetJS/js-xlsx#data-types
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by mhegazy** [comment]
@rinzeb @DxCx can you please review this change?

**Comment by mhegazy** [comment]
Now tests are failing

**Comment by DMan577** [comment]
Not sure what caused the fail in the latest commit, checking it now.

**Comment by DMan577** [comment]
`IWorkSheet` is currently an object of `IWorkSheetCell`, which is incompatible with the special keys that start with `'!'` ([Worksheet Object](https://github.com/SheetJS/js-xlsx#worksheet-object)), but I'm not sure about the correct data types.

**Comment by andy-ms** [comment]
Sorry, there was a build failure affecting recent PRs. Fixed by #15125. Please rebase to the latest `master` to fix test failures.

**Comment by DMan577** [comment]
Looks like I broke something with the rebase, I'll just open a new PR

**Pull request closed without merging**
