### PR TITLE
Vinyl@1.2.0

### PR DESCRIPTION
**Pull request by bdchauvette**
**Overview**
- Adds a test for the `Vinyl.isVinyl` static method
- Adds support for `Vinyl.isCustomProp` static method (introduced in [Vinyl 1.2.0](https://github.com/gulpjs/vinyl/commit/7b01e7523fcc97317580107b02f874b09641e5e9))
- Updates the Vinyl repo from [`wearefractal/vinyl`](https://github.com/wearefractal/vinyl) to [`gulpjs/vinyl`](https://github.com/gulpjs/vinyl)

**Reason**

I was creating a new class that extends Vinyl. Following the [Extending Vinyl guidelines](https://github.com/gulpjs/vinyl#extending-vinyl), I tried overriding the `isCustomProp` method, but tsc complained that `isCustomProp` does not exist on type Vinyl.

So I checked the DT Vinyl definitions and noticed they haven't been updated to 1.2.0, where the `isCustomProp` method was introduced.

Let me know if I need to change anything!

### CODE REVIEW

**Comment by jedmao** [comment]
:+1:

**Comment by bdchauvette** [comment]
Great, thanks everyone! 😃 

Will this be automatically merged into the `types-2.0` branch, or should I open a separate PR for that?

**Comment by andy-ms** [comment]
These will be *manually* merged into `types-2.0` as soon as we get around to it.

**Comment by bdchauvette** [comment]
Ok cool! I was just a bit unclear about the relationship between `master` and `types-2.0`.

Thanks for all the hard work you guys are doing with this repo 😃👍

**Pull request merged**
