### PR TITLE
[Material-UI] Replace on*IconButtonTouchTap with on*IconButtonClick in AppBar

### PR DESCRIPTION
**Pull request by mthmulders**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [commit](https://github.com/mui-org/material-ui/commit/7c2b03e65cea3a2c227804bbba5030adc2922978) and [current source source](https://github.com/mui-org/material-ui/blob/7529338fcc70df6b4823220277f8c2d2287c48fd/src/AppBar/AppBar.js#L109)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by openscript** [comment]
Thank you @mthmulders for the pull request!

Maybe you can also change `onTitleTouchTap?: TouchTapEventHandler;` to `onTitleClick?: TouchTapEventHandler;`? This changed too.

**Comment by mthmulders** [comment]
Sure thing! Just for the `AppBar` or also elsewhere in the type definitions for Material UI?

**Comment by openscript** [comment]
According to the release notes of v0.20.0 `TouchTap` was replaces through `Click` everywhere.
image

When I 'grep' the code of material or check what modules are exported I can't find anything with `TouchTap` in it. I think we can replace all occurrences of `TouchTap` with `Click`.

I've tried this out and found one collision:
image

It seems like the `onTouchTab` was just removed in this case?

**Comment by openscript** [comment]
Maybe something like this could be a solution?
https://github.com/openscript/DefinitelyTyped/commit/ea7da566a8c46d9163ba3d08961a1585c4866712

**Comment by mthmulders** [comment]
That looks pretty nice, @openscript. It seems simpler than declaring custom types for the events.

**Review by paulvanbrenk — CHANGES_REQUESTED** [review]
Looks like there's more changes needed based on the comments from @openscript

**Comment by paulvanbrenk** [comment]
Looks good to me, going to give @openscript a couple of days to give feedback.

**Comment by openscript** [comment]
Looks great to me too! Thank you @mthmulder!

**Pull request merged**
