### PR TITLE
node-schedule: Add Promise<any> to JobCallback return

### PR DESCRIPTION
**Pull request by RoelGo**
node-schedule/lib/Invocation.js:272

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Invocation.js#L272](https://github.com/node-schedule/node-schedule/blob/bd9cbe52d551e4eb855ad836635311e22c55df5b/lib/Invocation.js#L272)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## node-schedule ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-schedule@latest/))
was missing the following properties:
1. gracefulShutdown
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 973dd01f1bcaba1cb3497b2a8065367a4cd3aacc
</p>

**Review by MysteryBlokHed — COMMENTED** [review]
The `void` type means that the return of the function is ignored, so a function that returns `Promise<void>` should already be allowed.

**Comment by RoelGo** [comment]
After looking closer at the source code it seems like the result of the promise is not ignored and is passed as an arg to the `emit` method from the `EventEmitter` prototype. I will change the subtype to any.

**Comment by MysteryBlokHed** [comment]
Looks good to me now. Apologies for misreading the code at first 😄

To let the PR be merged by an owner, it should modify the tests (`node-schedule-tests.ts`) to test any new changes. For example, to test the new `gracefulShutdown` function:

```typescript
function testGracefulShutdown() {
    nodeSchedule.gracefulShutdown();
}
```

**Comment by RoelGo** [comment]
Ah great! I will add those somewhere next week. Thanks for letting me know.

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!
Still needs an owner's approval to get merged though

**Comment by seohyun0120** [comment]
LGTM! :)

**Review by seohyun0120 — APPROVED** [review]
LGTM! 👍

**Comment by RoelGo** [comment]
Ready to merge

**Pull request merged**
