### PR TITLE
jws support isValid

### PR DESCRIPTION
**Pull request by robertmassaioli**
This is supported in the library but not by the types: https://github.com/auth0/node-jws/blob/master/index.js#L16

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by robertmassaioli** [comment]
@JustinBeckwith I believe that you originally added these types. Can you please review this or tell me who the right reviewer would be?

**Review by JustinBeckwith — APPROVED** [review]
LGTM.  One worry here - I see that this method is specifically [exported](https://github.com/auth0/node-jws/blob/master/index.js#L14), but it doesn't appear in the [README](https://github.com/auth0/node-jws#node-jws-).  That makes me worried it shouldn't be exposed, or that it could go away. It may be worth opening a doc issue on their issue tracker!

**Comment by robertmassaioli** [comment]
Good call! Issue raised: https://github.com/auth0/node-jws/issues/99

**Comment by robertmassaioli** [comment]
@JustinBeckwith Bump, just wondering if you could submit a fresh review like the bot requested? Cheers.

**Review by JustinBeckwith — APPROVED** [review]

**Comment by JustinBeckwith** [comment]
Apologies, didn't know I was blocking

**Comment by JustinBeckwith** [comment]
Ready to merge

**Comment by robertmassaioli** [comment]
Thankyou @JustinBeckwith ! I really appreciate your help!

**Pull request merged**
