### PR TITLE
Add location type arg for query params to route definition v3

### PR DESCRIPTION
**Pull request by aaronbeall**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: `history` v3 module defines the `Q` type here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7c0251edd89f0694134425ff33ea44fe790fd12f/types/history/v3/index.d.ts#L38
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Looks fine. You need to fix the formatting issues reported by CI though.

**Review by nulladdict — APPROVED** [review]

**Review by gillchristian — APPROVED** [review]

**Comment by aaronbeall** [comment]
How does this get published, since it's part of the `v3` sub-folder? I'm not seeing it on npm...

**Comment by uniqueiniquity** [comment]
The publishing step isn't immediate - typescript-bot will post here when it's been published.

**Comment by aaronbeall** [comment]
@uniqueiniquity Thanks, wasn't seeing it in npm initially but maybe it was a caching issue.

**Pull request merged**
