### PR TITLE
pino.d.ts updated to 3.0.5

### PR DESCRIPTION
**Pull request by psnider**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ x Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] ~Run `npm run lint -- package-name` if a `tslint.json` is present.~ none present

~If adding a new definition:~ not new

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/pino
- [x] Increase the version number in the header if appropriate.

Replaces PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13303

### CODE REVIEW

**Comment by psnider** [comment]
Please advise: What am I supposed to do to correct this error?
```
Error: In /home/travis/build/DefinitelyTyped/DefinitelyTyped/pino index.d.ts: Definitions must use global references rather than reaching outside of their directory.
```

Things have changed since I last did this, and I don't think the documentation I referenced was updated.

**Comment by andy-ms** [comment]
It looks like there are a lot of changes in this PR other than the specific changes in types that you wanted to make. For example, semicolons were removed. And `/// <reference types="node"/>` was changed to `/// <reference path='../node/index.d.ts' />`, causing the above error. Since the definitions are written in a new style now, you should edit them as they are rather than pasting definitions written in the old style.

**Comment by psnider** [comment]
I just saw your comment. 

I completely replaced the tests with the updated examples from the package documentation.
As for the index.d.ts file, I don't think anyone else has changed the types since I last worked on them.

**Comment by andy-ms** [comment]
Since you're the main author, could you add a `tslint.json` containing `{ "extends": "../tslint.json }` and fix the warnings generated by `npm run lint -- pino`?
It would be nice to convert from `declare module 'pino' {` to writing the declarations directly at the top level as exports. (That's a linter warning, just warning you about the warning...)

**Comment by psnider** [comment]
I prefer external modules, but unfortunately pino isn't written this way.
If there's a way I can write the declaration file as if pino is an external module, I'd be happy to.
I just had trouble doing it.

Regarding the lint, I can take a look...

**Comment by andy-ms** [comment]
The current `pino/index.d.ts` is written as an external module; see `export = P;` at the bottom. Pino itself uses `module.exports = pino` (https://github.com/pinojs/pino/blob/master/pino.js#L452), so this seems accurate. The definitions you're writing here also use `export = P;`, but inside an ambient declaration.

**Comment by psnider** [comment]
I thought ```export=``` only allows exporting that single thing.
I would like to not have any namespace or module and just use:
```
export a ...
export b ...
```
The problem I had when I tried to do this is that ```export = p``` then causes the error:
> [ts] An export assignment cannot be used in a module with other exported elements.

If there's a way to make this work, I'd be happy to make the changes.

**Comment by andy-ms** [comment]
The current `pino/index.d.ts` is already written as an external module. It does this by merging `namespace P` with `function P` and using `export = P;` at the end. All of the "other exports" go in the namespace. (These actually are types/values namespaced to the function, not true exports.) So all you need to do is use the code from before and make your changes to that, rather than trying to rewrite it from scratch.

**Comment by psnider** [comment]
FWIW, I can get the declaration file to compile using es6 external modules declarations, such as:
```
export interface Pino {
    // omitted for brevity
}

declare var p: Pino
export default p
```

but I don't know if this is right, and haven't figured out how to import this in consuming code.

**Comment by psnider** [comment]
OK, it looks like I may have finally stumbled across a solution:
- use es6 module style declarations as above
- use this in the tests file:
```
import PINO, {Logger} from 'pino'
```

Does this look right?
I'll try it in my code next...

**Comment by psnider** [comment]
Yes, it works in my code.
But I had to switch all of the imports to the es6 module imports.
In my opinion, an improvement, and worth the effort.

What is policy on switching the style to es6 modules?

**Comment by psnider** [comment]
Sorry, didn't see your comment ```The current pino/index.d.ts is already written as an external module.``` until just now...

The problem that I had with the existing declaration was I couldn't figure out any way to export the interfaces as well, without putting them in the global scope. And putting them in the global scope seems polluting.
If there is a way to export them from the namespace, I'll be happy with that too.
But I greatly prefer the es6 path, if it's an option.

**Comment by andy-ms** [comment]
You can put them in the namespace and they will be available as namespaced types on the main export.
For example:

```ts
// index.d.ts
declare namespace P {
	...

	// There already
	interface Headers {
	    [header: string]: string;
	}

	interface YourInterfaceHere {
	   x: number;
	}
}
```

Then in tests:

```ts
// pino-tests.ts
const x: PINO.YourInterfaceHere = { x: 1 };
```

Or:

```ts
import { YourInterfaceHere } from "pino";
const x: YourInterfaceHere = { x: 1 };
```

**Comment by psnider** [comment]
You are right.
And I'm confused.

I started working on updating this about a month ago.
I'd received one notification of someone else trying to modify pino.d.ts, but that PR was aborted.

Now, when I look at pino.d.ts, it has been changed, and it doesn't match the version that I had received in @ types. (Likely I haven't updated @ types since then.)

So now the file has changes that work for me, as you described in your last comment, and I don't need to update anything!

I don't know why I didn't see this latest version of the file. Something seems odd...
I also noticed that there is no history on DT showing that I created this file!
Likely these are related. See https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/pino/index.d.ts
so closing the PR...

**Comment by psnider** [comment]
I found the main reason for my confusion: I never received any notifications that pino.d.ts was updated by evanshortiss, so I thought I was still the only author.

So perhaps something changed in the repository, so that I wouldn't receive notifications anymore?
I also wonder if I might have been working off of the wrong branch? (it used to be *master*, not *types-2.0*.

I find the docs at http://definitelytyped.org/guides/contributing.html confusing, 
as it seems they haven't been updated to match the new processes (DT and @ types).

**Comment by andy-ms** [comment]
Looks like dt-bot didn't respond to that PR: #12850. But it did for this one.
We were working on the `types-2.0` branch for the new style of definitions, but have since merged back to `master`.

**Pull request closed without merging**
