### PR TITLE
 Add type definition for Aurelia

### LINKED ISSUE #34: Please add Aurelia DefinitionTypes to definitely typed :)
Would be lovely in we could install Aurelia simply via tsd

https://github.com/DefinitelyTyped/tsd/

What is the reason these DTs are not on http://definitelytyped.org yet?

### PR DESCRIPTION
**Pull request by behzad888**
case 1. Add a new type definition.
- [x]  checked compilation succeeds with --target es6 and --noImplicitAny options.
- [x]  has correct naming convention
- [x]  has a test file with the suffix of -tests.ts or -tests.tsx.

I want to close cmichaelgraham/aurelia-typescript#34

### CODE REVIEW

**Comment by vvakame** [comment]
@behzad888 We want a `-tests.d.ts` file. could you make some simple use case for it?

**Comment by behzad888** [comment]
@vvakame ping...

**Comment by vvakame** [comment]
@behzad888 umm. your tests can't detected by [definition-tester](https://github.com/DefinitelyTyped/definition-tester).
please check our [guides](http://definitelytyped.org/guides/contributing.html#tests).

**Comment by mhegazy** [comment]
@behzad888 can you update the test file?

**Comment by mhegazy** [comment]
@behzad888 🔔

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
