### PR TITLE
[lodash] When iterating over objects, infer well-known property names

### PR DESCRIPTION
**Pull request by karol-majewski**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.15#mapValues
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

**Problem**

Assume an object with well-known properties:

```ts
declare const errors: {
  401: boolean;
  404: boolean;
};
```

And a function that accepts those well-known properties as its argument:

```ts
declare function getErrorMessage(code: 401 | 404 | 500): string;
```

We can't use `getErrorMessage` as the callback argument for `mapValues` because of a TypeScript error.

```ts
// Compile-time error: Argument of type 'string' is not assignable to parameter of type '401 | 404 | 500'.ts(2345)
mapValues(errors, (_, key) => getErrorMessage(key));
```

**Solution**

If we replace `string` with `keyof T`, everything works as expected.

```ts
mapValues(errors, (_, key) => getErrorMessage(key));

declare module 'lodash' {
  interface LoDashStatic {
    mapValues<T extends object, TResult>(object: T, callback: (value: T[keyof T], key: keyof T, collection: T) => TResult): { [K in keyof T]: TResult };
  }
}
```

**Considerations**

1. Because of structural typing, it's not 100% safe to assume that `key` will be of type `keyof T`. See [why](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript). [Playground illustrating the problem](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=22#code/JYWwDg9gTgLgBAbziAhmAaigNgVwKYDOcAvnAGZQQhwDkWEAJigQBY0DcAUJw3gMZYUUPMkY4sIuo2ZtEnOHGAA7GHihkUfEQBkIAERkBlGChjA+chQtQZs+AgB4AKnDwAPVUoZEIAIwBW-DAANHBOAEqE4jAAfAAUfoF8MABcYaF82Fi+mgDWaXEAbnZ4aU4A2rl4AJ4QZGEAuqFV1WktdelwfBBYEsnAEEplAJRwALwxYZEE0cNpSOUA0opKcO31Tg1l09EkXArEnIecyqrqmiIAYqbYAKJQlFBECPJwAKwADB9pvhA9eCglFxjmQcEp+oM4ABzPAwe6PACyhAIKBhcW6vDSABYPgBGOAAHzgOKxhPeXzmcAIMCgyihlipAHdgDA+Cw4OjGHhRi8rF1mCIcbiUq8+cIYDgoKsaAAJEAgDii-kEQUfLEivkKcWS6WGaBQaqKvmZFXk75KrWwnW0ADyODABCNVl4GmiaRgLEojLgSjw3vh0DiNAAqkphN0oUpgAAvPAMVwPaBdLkAQhow32JCO3FB4LMkJhMCRBBRMIIcTUjwIaWuJiwAaePNe2qlyDQmFwhAriaeoTiAH1mjVRhNobCG8XS3g4i1hhns5xukpqchqg2iGMGZ9vnAafhgq8AMx4tIaLAqg-ELicQuT1FdkBrnsEDNwAD0b7CnogjKIvn4KA4KahYTsi94rAQwC8Lu36-kAA).
1. This change, if accepted, could be applied to other functions such as `omitBy`. However, because you may have had good reasons _not_ to define object iterators this way, I haven't introduced any other change in this pull request.

### CODE REVIEW

**Review by thorn0 — CHANGES_REQUESTED** [review]
There is a [reason](https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208) why the TS team doesn't use such definition for `Object.keys`. I guess the same logic applies here. If they ever decide to change their mind regarding `Object.keys`, we can revisit this too.

**Comment by karol-majewski** [comment]
@thorn0 Thank you for your response. It makes sense.

On possible way out of this problem would be to make such a precise (but potentially dangerous) overload work only when the user opts-in explicitly.

To opt-in, an explicit type argument would need to be provided by the user. If none is provided, the current behavior is preserved.

[Playground](https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbziAhmAaigNgVwKYDOcAvnAGZQQhwDkWEAJigQBY0DcAUJw3gMZYUUPMkY4sIuo2ZtEnOHGAA7GHihkUfEQBkIAERkBlGChjA+chQtQZs+AgB4AKnDwAPVUoZEIAIwBW-DAANHBOAEqE4iFhANJ4AJ6uHnheRAAKlGBqMAnxSQC8cJkQ2bB5iQB8ABR+gXwwAFxhoXzYWL6aANbN1QBudnjNTgDaXYkQZGEAuqHjCcP5rRBYEg3AEErDAJRwBZVhkQTR281II7GKSnDzkzPDR9EkXArEnG+cyqrqmiIAYqZsABRKCUKBEBDyOAAVgADLDmr4ICs8CglFwPmQcEp1ps4ABzPAwEFggCyhAIKEJ1T4jCGcAALLCAIxwAA+jNhDPZMPhpzgBBgUGU+MsAoA7sAYHwWHAaXTdpCrHA2gQREzmY0ocrhDAcFBrjQABIgEAcbUq5jqrla5UKXX6w2GaBQBLm5WqkRwhEW+1Ex20ADyODABHdVl4GmizRgLEo4rgSjwCZJ0GqNAAqkphLT8UpgAAvPAMVyg6AqukAQho2xeJHe3CxOLMeMJMHJBEphII1TUYIIzQBJiwqfBiqhAHoAFRT7VTuCjuX+HCCuBYYDjRTwcXQLpEYX4ljwJQQcXbOcTqEOg3INCYXCEXtl8GhaoAfTmiV2+wJRNHHa7PBqnmbZa24BRp1nKx5wAOQgUswSXFd4HXTcpTgHcoD3OADyPRNT3PaDLwgiccP9G8bHvewHCHYFnwIUJBWFJR8U-BI7lokd6JqPtoAYuUPxuL89gONt-wpKkgJAsCPlpJRVxABJRyIIolV5BE4CFfBgihABmFlmg0LA1R04guE4NsAMkntFOU2s4AnUinDjU8iF8fgUBXEQxOfKzCSuAhgF4TSXPFAggA) illustrating the solution.

**Comment by karol-majewski** [comment]
Another, perhaps more sustainable solution, would be to recommend users looking for that functionality to create an unsafe version of the function in question themselves.

```ts
import { mapValues } from 'lodash';

const UNSAFE_mapValue: <T extends object, TResult>(
  object: T, callback: (value: T[keyof T], key: keyof T, collection: T) => TResult
) => { [K in keyof T]: TResult } = mapValues;
```

Such a recipe could be added to the docs. No code would be changed.

**Comment by aj-r** [comment]
That might be ok. Beware that keyof T could include non-string types, but
in _.map the key will always be a string. If we recommend this solution, it
should be clearly marked as "use at your own risk" with this caveat.

**Pull request closed without merging**
