### PR TITLE
add support for AMD require

### PR DESCRIPTION
**Pull request by rcchen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by rcchen** [comment]
Talked with @sixinli and she couldn't get TravisCI working, we're going to do this to replace #18142

**Review by sixinli — APPROVED** [review]
lgtm!

**Review by weswigham — CHANGES_REQUESTED** [review]
Is the library name `keypress` or `keypress.js`? The folder name is `keypress`, but you're adding a global library `keypress.js` - which is inconsistent. One of the two should be changed, I think?

**Comment by andy-ms** [comment]
Merged #18142 before seeing this, they look identical so I'll close this one.

**Pull request closed without merging**
