### PR TITLE
refactor react-bootstrap into individual modules

### LINKED ISSUE #15856: Importing 'react-bootstrap' works but importing individual components dont
Why do I need to import `react-bootstrap` like

    import {Button} from 'react-bootstrap';
    ...

    <Button></Button>

but importing like this wont work:

    import * as Button from 'react-bootstrap/lib/Button'

i get this error: `TS2604: JSX element type 'Button' does not have any construct or call signatures.`

as well as this:

    import Button from 'react-bootstrap/lib/Button'
gives this error: `TS1192: Module ''react-bootstrap/lib/Button'' has no default export.`

And when I do `import {Button} from 'react-bootstrap/lib/Button'` then Button is undefined

tsconfig.json:

    {
      "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
      },
      "exclude": [
        "node_modules"
      ]
    }

webpack:

    ...
            {
              test: /\.tsx?$/,
              loader: "awesome-typescript-loader",
              exclude: /node_modules/
            }
    ...

I even tried using `ts-loader` instead of `awesome-typescript-loader` but the errors are same.

### PR DESCRIPTION
**Pull request by vitosamson**
this allows individual components to be imported in addition to named imports on the root module. closes #15856

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15856, https://github.com/react-bootstrap/react-bootstrap/tree/v0.31.1/src
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by vitosamson** [comment]
Tests are currently failing with `Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-bootstrap/lib/utils has unused file PropTypes.d.ts`.

That file [exists in the react-bootstrap source](https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.1/src/utils/PropTypes.js) but isn't directly imported by any of the type defs here. How can I work around that to get the tests to pass?

**Comment by vitosamson** [comment]
I've fixed some of the errors but there are new errors now which are related to some previous erroneous relations between react-bootstrap and react-overlays. This is now blocked by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18197

**Comment by vitosamson** [comment]
Rebased onto master, tests now pass since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18197 was merged.

**Comment by sheetalkamat** [comment]
@walkerburgin,  
@vsiao,  
@danilojrr,  
@Batbold-Gansukh,  
@octatone,  
@chengsieuly,  
@katbusch,  
 Can you please review.

**Comment by mhegazy** [comment]
@walkerburgin,
@vsiao,
@danilojrr,
@Batbold-Gansukh,
@octatone,
@chengsieuly,
@katbusch,

another gentle reminder, this is a big change and would help if you take a look.

**Comment by mattvperry** [comment]
This PR has caused a breaking change since the individual component Props interfaces seem to no longer be exported. Anyone depending on them will need to stick to a version before this refactor.

**Comment by bowdenk7** [comment]
@mattvperry do you mind sending a pull request to fix the issue?

**Comment by grovesNL** [comment]
It also broke `ValidComponentChildren`

**Pull request merged**
