### PR TITLE
http-proxy. Response can actually be http.ServerResponse or net.Socket in emit('error') callback

### PR DESCRIPTION
**Pull request by firecow**
As illustrated

Here
https://github.com/http-party/node-http-proxy/blob/master/lib/http-proxy/passes/web-incoming.js#L165
and
https://github.com/http-party/node-http-proxy/blob/master/lib/http-proxy/passes/ws-incoming.js#L157

### CODE REVIEW

**Review by moberghammer — APPROVED** [review]
Lgtm

**Review by bodinsamuel — APPROVED** [review]
LGTM
not sure the renaming was necessary but it's personal coding style ^^'

**Comment by firecow** [comment]
> LGTM not sure the renaming was necessary but it's personal coding style ^^'

I've changed it back to res...

**Review by bodinsamuel — APPROVED** [review]

**Review by moberghammer — APPROVED** [review]
Lgtm

**Pull request merged**
