### PR TITLE
d3-selection - key function in `.data` may return `number` as well

### PR DESCRIPTION
**Pull request by kum-deepak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

The key in d3 data binding can be number as well.

### CODE REVIEW

**Comment by kum-deepak** [comment]
While going through other d3 typing I realized that there is following used in `d3-array`:

```typescript
export type Primitive = number | string | boolean | Date;
```

If you suggest this can be used.

**Review by gustavderdrache — COMMENTED** [review]
I'm hesitant about the allowance of `Date` here - `d3-selection`'s `.data()` method implicitly converts to string, and it feels like Date's stringification behavior may not be desirable for data binding.

For what it's worth, the React and Inferno types only allow `string | number` for the `key` prop for reconciliation, so I think I'd suggest following that. If there is a need for more specific keying, I'd rather err on the side of caution and require that users write `d => String(d)` or similar if they need to key by some other type.

**Comment by kum-deepak** [comment]
Thanks for your review. I have reviewed the code in https://github.com/d3/d3-selection/blob/master/src/selection/data.js. What you say makes sense - the key is used as a hash key. So, we can assume only numbers apart from strings make sense. I will update the PR.

**Review by gustavderdrache — APPROVED** [review]

**Comment by kum-deepak** [comment]
Ready to merge

**Pull request merged**
