### PR TITLE
update(webpack-dev-middleware): v4.2 updates

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- drop legacy v1 and v2
- restores Webpack v4 support
- add support for 'header' handler
- amend tests

https://github.com/webpack/webpack-dev-middleware/compare/v4.1.0...v4.2.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lizthegrey** [comment]
Thanks for putting webpack v4 support back.

**Review by tqma113 — APPROVED** [review]
LGTM

**Comment by peterblazejewicz** [comment]
Ready to merge ♥

**Comment by rchl** [comment]
v4.2.0 still seems to have webpack ^5 dependency set in https://unpkg.com/browse/@types/webpack-dev-middleware@4.2.0/package.json

Is that correct?

**Pull request merged**
