### PR TITLE
Added d.ts files for Backbone-Associations

### PR DESCRIPTION
**Pull request by craigbrett17**
Added Backbone Associations.d.ts along with tests to see its usage

### CODE REVIEW

**Comment by vvakame** [comment]
*Backbone-Associations/backbone-associations.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/Backbone-Associations
  * http://bower.io/search/?q=Backbone-Associations
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (Backbone-Associations/backbone-associations-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@craigbrett17 thank you for your contributions.
umm.. please rename Backbone-Associations/backbone-associations.d.ts to backbone-associations/backbone-associations.d.ts
200: https://www.npmjs.com/package/backbone-associations
404: https://www.npmjs.com/package/Backbone-Associations

**Comment by craigbrett17** [comment]
Okay? Sure.

**Comment by vvakame** [comment]
@craigbrett17 thanks mate!

**Pull request merged**
