### PR TITLE
Type Definition Fixes

### PR DESCRIPTION
**Pull request by faridansarii**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[Success response](https://razorpay.com/docs/payments/payment-gateway/how-it-works#step-4-bank-authenticates-the-payment)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### Type definitions
- SuccessResponse - <<[Success response](https://razorpay.com/docs/payments/payment-gateway/how-it-works#step-4-bank-authenticates-the-payment)>>
- ErrorResponse - API returns a different object than the one mentioned in the docs. It can be tested using the existing tests in this package.

### CODE REVIEW

**Comment by Ankan002** [comment]
@Kroniac check for linting checks, once they get passed, I can check the changes

**Review by Ankan002 — APPROVED** [review]
LGTM!

**Comment by Ankan002** [comment]
@Kroniac Hey please change the test files as well, so that I can directly approve and merge

**Comment by Ankan002** [comment]
@Kroniac Please update the test files. This will let me merge the changes.

**Comment by Kroniac** [comment]
@Ankan002 updated the test file. Added documentation.

**Review by Ankan002 — APPROVED** [review]
LGTM! Thank you

**Comment by Kroniac** [comment]
Ready to merge

**Pull request merged**
