### PR TITLE
recharts added generic any to React.ReactElement<any,any> 

### PR DESCRIPTION
**Pull request by repac37**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by claasahl** [comment]
This seems to be a related PR #33568

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
You shouldn't need this change

**Comment by kkgogst** [comment]
Why this PR closed? This causes an issue to build my node module

**Comment by claasahl** [comment]
You might be referencing outdated `react`-types. 

This commit should have resolved this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2fc40ca501f2cc734deb9313fa1032e3381a0e26

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L100-L104

**Pull request closed without merging**
