### PR TITLE
fix(mailgun-js): Ambient Type References

### PR DESCRIPTION
**Pull request by jlmart88**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: **(no changes to the source code prompted this change)**
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by jlmart88** [comment]
I resorted to using `tslint:disable`, because the only way I could find to get the ambient types working was through using a `declare module`. If someone can find a way to make the test addition that I wrote work in a manner that pleases the linter, I'd be happy to have that go in instead.

**Comment by sampsonjoliver** [comment]
@jlmart88 This is awesome!

So you can change the "style" of the types file by, instead of declaring the encapsulating namespace, making it export all the contained interfaces and classes.

E.g.

Current style:
```
declare namespace Mailgun [
  interface Messages { ... }
  interface Lists { ... }
  interface MailgunExport { ... }
}
const x: Mailgun.MailgunExport
export = x
```

Export style
```
export interface Lists { ... }
export interface Messages { ... }

interface MailgunExport { ... }

const x: MailgunExport
export = x

// Usage
import * as Mailgun from "mailgun-js";

```

But this approach doesn't seem to work when using `require('mailgun-js')`.

So I'm happy to approve either this, or if you can figure out the `require` caveat of this other approach, happy to approve that instead

**Comment by jlmart88** [comment]
I'd say let's stick with with the namespace approach; IMO it looks cleaner

**Review by sampsonjoliver — APPROVED** [review]

**Comment by andy-ms** [comment]
Please look at #29579 which I think is a better way to do this. It exposes the type members via the export instead of introducing a global export.

**Review by sampsonjoliver — CHANGES_REQUESTED** [review]
Agree with @andy-ms that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29579 is a cleaner and more appropriate resolution to the problem, using namespace merging.

**Comment by jlmart88** [comment]
Thanks @andy-ms, I knew I was missing something straightforward

**Pull request closed without merging**
