### PR TITLE
Added declarations for 'moonjs'.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/dtslint/issues/31

**Comment by andy-ms** [comment]
@DanielRosenwasser Reran the tests, new failures are legitimate.

**Comment by mhegazy** [comment]
@DanielRosenwasser  still needs some more lint 💘

**Comment by yuit** [comment]
Thanks for your contribution. This PR has failing CI and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
