### PR TITLE
add abort() into the websocket client

### PR DESCRIPTION
**Pull request by jdneo**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/theturtle32/WebSocket-Node/blob/662f8ccd57eb8eed85cabe46597d55ef6cdb6b70/lib/WebSocketClient.js#L342
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by simonbuchan — APPROVED** [review]
Seems straightforward.
Docs link: https://github.com/theturtle32/WebSocket-Node/blob/662f8ccd57eb8eed85cabe46597d55ef6cdb6b70/docs/WebSocketClient.md#abort

**Comment by jdneo** [comment]
@simonbuchan Thanks.

**Review by simonbuchan — CHANGES_REQUESTED** [review]
Actually, should add a test to `websockets-test.ts` that simply calls this.

**Comment by jdneo** [comment]
@simonbuchan Do you mean simply call `client.abort()` at the bottom of `clientTest2()`?

**Comment by simonbuchan** [comment]
Hmm, the tests should ideally stay runnable to check that the runtime matches the definitions. Maybe add a separate client test which simply calls `connect()` and `abort()`, but I'm not too worried.

**Comment by jdneo** [comment]
@simonbuchan Yes that's making sense. I'll update the PR later.

**Review by simonbuchan — APPROVED** [review]
:+1: great!

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
