### PR TITLE
[chrome] Add missing definitions of functions (mainly MV3)

### PR DESCRIPTION
**Pull request by michaelts1**
This pull request adds definitions for missing functions in a number of `chrome.*` namespaces.

I have noticed that some of the definitions for chrome are out of date and don't include the new [MV3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) promise-based signatures, so I decided to update the definitions myself. I have not not updated all namespaces, so there is still work to be done updating the rest of the definitions.
While updating the definitions, I have noticed a few incorrect parameter types or completely missing functions, so I went ahead and added them too.
I have tried to to keep using the same style already found in the files.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: See bellow.

All new/modified signatures in this PR are from the official documentation (https://developer.chrome.com/docs/extensions/reference).
Note that the definitions in the linked resources incorrectly say that returning a promise "is coming soon and not yet in a stable release of Chrome". This is not true, and I have tested all function signatures using the latest stable Chrome version (v99) before adding them.
Links to individual documentation pages in case they are needed:
* chrome.browsingData - https://developer.chrome.com/docs/extensions/reference/browsingData
* chrome.commands - https://developer.chrome.com/docs/extensions/reference/commands
* chrome.debugger - https://developer.chrome.com/docs/extensions/reference/debugger
* chrome.downloads - https://developer.chrome.com/docs/extensions/reference/downloads
* chrome.extension - https://developer.chrome.com/docs/extensions/reference/extension
* chrome.fontSettings - https://developer.chrome.com/docs/extensions/reference/fontSettings
* chrome.history - https://developer.chrome.com/docs/extensions/reference/history
* chrome.i18n - https://developer.chrome.com/docs/extensions/reference/i18n

### CODE REVIEW

**Comment by michaelts1** [comment]
Should I split this PR into multiple smaller PRs?

**Review by JasonXian — APPROVED** [review]
Changes are mostly additive and match docs, tests look great as well. Thanks for taking the time to do this!

**Comment by michaelts1** [comment]
Ready to merge

**Comment by datgrog** [comment]
Hello, I might be wrong but chrome.runtime also need promise-based signatures ?
Screenshot 2022-03-21 at 17 34 31

**Comment by michaelts1** [comment]
Yes, the definitions are wrong here. According the the [docs](https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage), `chrome.runtime.sendMessage` does support promises now.

As I have stated above, I have not not updated all namespaces, so this is just another instance of an outdated definition. I don't have the time to update more definitions right now, but if you feel like doing so you can update them yourself and send a new PR.

**Comment by datgrog** [comment]
Not sure I can make it but thanks anyway for your reply and your work.

**Pull request merged**
