### PR TITLE
Add typings for react-native-datepicker

### PR DESCRIPTION
**Pull request by jacobbaskin**
- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

---
This change is [Reviewable](https://reviewable.io/reviews/definitelytyped/definitelytyped/14276)

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by DanielRosenwasser** [comment]
Quick question before I pull in - is there any reason this needs to use TS 2.1? We usually only add that tag if you're using a 2.1-specific feature in there.

**Comment by jacobbaskin** [comment]
React typings fail to compile correctly at 2.0 right now so any typings of
libraries that use React have to be 2.1 only.

**Comment by ericanderson** [comment]
@DanielRosenwasser: @jacobbaskin is correct. We had to bump everything that depends on react to 2.1: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13155

**Comment by jacobbaskin** [comment]
@DanielRosenwasser anything else or ready to merge?

**Pull request merged**
