### PR TITLE
ioredis zadd transaction/pipeline signature

### PR DESCRIPTION
**Pull request by tasinet**
The existing pipeline/transaction `zadd` signature forces `score` (2nd argument) to be a string. It is actually a `number`.

The zadd pipeline definition extends up to 6 pairs of {score, member} elements which was also the number used in the OverloadedKeyCommand interface which is used for the normal zadd command.

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://npmdoc.github.io/node-npmdoc-ioredis/build/apidoc.html#apidoc.element.ioredis.pipeline.prototype.zadd

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ioredis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ioredis@latest/))
was missing the following properties:
1. createClient
1. defaultOptions
1. ScanStream
1. Pipeline
1. AbstractConnector

<details>
<summary>as well as these 5 other properties...</summary>
<p>SentinelConnector, SentinelIterator, ReplyError, Promise, print</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 39535215f2d2ad99260d26662f99bcabc27775b6
</p>

**Review by plantain-00 — APPROVED** [review]

**Review by barakplasma — APPROVED** [review]
https://redis.io/commands/zadd
"The score values should be the string representation of a double precision floating point number"

I agree that declaring score should be a number is better for the types though.

**Comment by tasinet** [comment]
Ready to merge

**Comment by urossmolnik** [comment]
@tasinet this pull request is causing type errors when using spread operator.
```
let pipeline = redisClient.multi()
for (...) {
  const items: (number|string)[] = ... // array of score, member pairs
  pipeline.zadd('key', 'NX', ...items) // type error, but this is valid zadd command
}
```

**Comment by tasinet** [comment]
Are you certain a list of strings is valid for zadd? I thought it had to include the scores. Should I change it to accept (number|string)[] ?

**Comment by urossmolnik** [comment]
@tasinet score can be a string. From https://redis.io/commands/zadd
> The score values should be the string representation of a double precision floating point number. +inf and -inf values are valid values as well.

Not sure what is the use case of using +inf/-inf on `zadd` thou :) 

Problem I have is related only to `zadd` on `Pipeline` (when using `multi`) and not on `Redis` directly. Example: https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAJQKYBNgGc4DMoRHAcmGlQwIChyBjCAO3XilPQGEAbYJWmALkWYB0yNJgC8cWgFc2bOAENMc2gE9qdBnCoALJQHMkYuAG0A3uhpM+ARgA0cEEhAAjJFD4EFKLFYIBfO2YWSHwATHYOzq7unlghfgC65Ewi7JzcAiDSMMAAFACUAgBecigoOQToeEgA+gDWSMoEdgQAcgAaTXAC3dp6BgJYbHIwALJyYDnAcKIAfMbAAuYkdgsRLlDxeXnkQA

Not sure why `zadd` would be have different type definition on Pipeline?

**Pull request merged**
