### PR TITLE
Finalize Chrome API coverage for Platform Apps

### PR DESCRIPTION
**Pull request by niikoo**
*Short summary:*

- Thorough review of the typings.
- Added missing ones, fixed and updated the typings and doc of existing typings.
- Better tests, and for all parts of the API.
- Added AppView.
- Moved WebView to it's own file and namespace.
- Added other APIs which are referenced in the documentation (e.g. html5 APIs that requires permissions)
- WebView constructor in Window.
- Detailed permission information.
- Used the source code to find exact which API's that was usable. Some of the documentation is in the apps section and some in the extensions section. It's sometimes hard to know which is which.

*Breaking changes:*
HTMLWebViewElement is now in the global namespace, not under chrome.webview

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/apps/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by niikoo** [comment]
Can someone review this? Thanks!

**Comment by armanio123** [comment]
Seems @AdamLay @pine613 @mzsm @RReverser @pyle @matthewkimber @otiai10 @couven92 @RReverser @sreimer15 have not yet reviewed the PR. I'll wait until you get a review; otherwise let me know and I can help you with merging.

**Comment by couven92** [comment]
I am actually only an author on chrome itself, not the Chrome Apps APIs. I have not yet acquainted myself with the differences (if any) between these two APIs. I can do a review later this week, but maybe someone else would be better suited to do this review?

**Comment by niikoo** [comment]
Hello, there is quite a few differences. The API docs I've used are from the source code of chromium. They are not always that updated online. Also, some APIs are both for extensions and apps, but with differences. I've tested these definitions on a few chrome app projects, including Chrome OS only kiosk app projects.

**Review by fredrikhr — APPROVED** [review]
Looks good to me. However, as I said before, maybe you'd like someone more qualified than me to make the verdict on this review.

Great standardization of the patterns used throughout the entire file (i.e. using 'integer' everywhere to reflect the API documentation). Nice! 👍

**Comment by niikoo** [comment]
@armanio123, it's now approved by @couven92.
Can you help with merging?

**Pull request merged**
