### PR TITLE
Joi v6.5.0

### PR DESCRIPTION
**Pull request by laurence-myers**
Updates to the definitions for the Joi validation library, matching the docs for v6.5.0.

### CODE REVIEW

**Comment by vvakame** [comment]
@Bartvds could you review this PR?

**Comment by laurence-myers** [comment]
@vvakame, I think @Bartvds does not have time to review PRs. PR #4374 has been open for a few months now. If a code review is required, is someone else available to conduct the review? 

If the concern is that these changes could break the existing definitions, would it be acceptable to commit the new definitions under a different version of the Joi lib?

(Also, these changes overwrite PR #4521)

**Comment by vvakame** [comment]
@laurence-myers #4374 and #4521 are small change, I review it myself. your change is large but breaking changes are little. I decided merge your PR. thanks mate!

**Comment by laurence-myers** [comment]
Oh cool, thank you! :smile:

**Pull request merged**
