### PR TITLE
[office-js][office-js-preview] (Excel) Pulling latest Excel type definitions from CDN, releasing ExcelApi 1.17 to GA

### PR DESCRIPTION
**Pull request by alison-mk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
Release URL: https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js
Beta URL: https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by Rick-Kirkham — APPROVED** [review]

**Comment by jakebailey** [comment]
@alison-mk @Rick-Kirkham @ElizabethSamuel-MSFT 

It seems like you appear to be changing the version of dtslint in `package.json`; I don't know if this is intentional or if there's some automated process which is doing this, but can you make sure to not merge these PRs if they still touch `package.json`? Changing it away from `latest` ends up breaking things.

(The same happened last time in #64576, which I fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/67f600cabd9f9dc92bf73895d491ad790e3c47ac)

**Comment by Rick-Kirkham** [comment]
@jakebailey I will investigate.

**Comment by alison-mk** [comment]
Hi @jakebailey thanks for bringing this to our attention! I didn't realize that update was causing issues down the line. We can make sure not to push updates to package.json in the future. The reason I update package.json is because the line `"@definitelytyped/dtslint": "latest"` results in linter errors like this: 

image

Updating the dtslint version resolves these linter errors. Have you seen this with other projects? The linter errors are unrelated to changes made in our PRs, and they only started appearing in early 2023. We've discussed and come up with workarounds to avoid committing changes to package.json, but we're still interested in understanding the root cause of the unexpected errors with using `"@definitelytyped/dtslint": "latest"`.

**Comment by jakebailey** [comment]
What package manager are you using? What version of the package is being installed? Theoretically, you should get the full latest tree. Does it go away if you delete node_modules and clean install?

**Comment by jakebailey** [comment]
Also, if you have a problem, do file bugs on https://github.com/microsoft/DefinitelyTyped-tools! We're definitely watching there (or, ping us internally). We haven't seen something like this but if you've been having the problem for months we definitely would have liked to look.

**Comment by alison-mk** [comment]
Thanks for the suggestion @jakebailey — deleting node_modules and reinstalling fixed the issue.

**Pull request merged**
