### PR TITLE
[validator] Correct import submodule

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Improvement to existing type definition.

`validator` can import submodules.

```
> var isEmail = require('validator/lib/isEmail')
undefined
> isEmail
[Function: isEmail]
```

It's equivalent in Typescript.

```
import * as blacklistFunc from 'validator/lib/blacklist';
blacklistFunc(...)
```

So, it can implement import submodule! :smile:

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Hi, @andy-ms 
We keep on #11402 discussion.
In fact, in order to implement import submodule, in Typescript, it doesn't need to do the same import syntax `import isEmail from 'validator/lib/isEmail';` or add a plugin to meet babel.

Therefore, I finally get solution about it! It's `import * as isEmail from 'validator/lib/isEmail` because the export is equivalent to a function. :smile:

**Comment by TonyPythoneer** [comment]
Hello, who can answer me?

**Comment by andy-ms** [comment]
["validator/lib/blacklist"](https://github.com/chriso/validator.js/blob/master/lib/blacklist.js) uses `module.exports =`. So it should be imported as `import blacklist = require("validator/lib/blacklist")`. See more explanation [here](https://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y).

**Comment by TonyPythoneer** [comment]
@andy-ms So, I need to fix about single export and import as following:
```
import blacklist = require(validator/lib/blacklist');
```

**Comment by andy-ms** [comment]
Yes. This module uses that [`module.exports = exports['default'];`](https://github.com/chriso/validator.js/blob/master/lib/blacklist.js#L18) line, which means it does not have a `default` export and instead needs the `require` syntax.

**Comment by TonyPythoneer** [comment]
@andy-ms OK, I will fix this.

**Comment by TonyPythoneer** [comment]
@andy-ms I finished. Please take a look.

**Review by ghost — APPROVED** [review]

**Pull request merged**
