### PR TITLE
ui-grid: added defaultSort property to columnDef

### PR DESCRIPTION
**Pull request by pbojanczyk**
supporting ui-grid documentation: http://ui-grid.info/docs/#!/tutorial/324_default_sorting

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://ui-grid.info/docs/#!/tutorial/324_default_sorting
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by btesser** [comment]
I will take a look.  Sorry for the delay

**Comment by btesser** [comment]
@pbojanczyk can you add a test?

**Review by btesser — APPROVED** [review]
Looks good

**Review by pbojanczyk — COMMENTED** [review]
updated unit test

**Pull request merged**
