### PR TITLE
google-spreadsheet: Add sheetsByTitle

### PR DESCRIPTION
**Pull request by banyan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/theoephraim/node-google-spreadsheet/pull/349 https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=worksheets
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

---

I've run the following in a real script and worked well: 

```
  await doc.addSheet({ title });
  const newSheet = doc.sheetsByTitle[title];
  console.log('newSheet: ', newSheet);
```

### CODE REVIEW

**Review by the-vampiire — COMMENTED** [review]
@banyan i'm on mobile. can you link to the package docs where this feature was added?

lgtm if the feature is there. unless @EndBug sees an issue

**Comment by the-vampiire** [comment]
> @banyan i'm on mobile. can you link to the package docs where this feature was added?
> 
> lgtm if the feature is there. unless @EndBug sees an issue

oops it's right in the PR template! thanks

**Review by the-vampiire — APPROVED** [review]

**Comment by banyan** [comment]
@the-vampiire thanks for the quick response! 😄

**Comment by the-vampiire** [comment]
ah we forgot the magic words!

ready to merge

**Comment by banyan** [comment]
Ready to merge

**Pull request merged**
