### PR TITLE
Update pino definitions for 5.8

### PR DESCRIPTION
**Pull request by alferpal**
Hello everyone:

Template
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This PR adds a new package needed for the update of another, so I selected both options

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino/blob/master/docs/legacy.md#Migration
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR updates pino documentation to 5.8, also reflecting the breaking changes from pino v4 to v5 that were not previously reflected.

Such changes include:
  - Remove extreme option
  - Remove pretty option
  - Remove slowtime
  - Add extreme function
  - Add destination function

For this upgrade to be correct, the module sonic-boom needs to be aded

This is my first PR for a type definition, so anything that could be enhanced, please, tell.

### CODE REVIEW

**Comment by alferpal** [comment]
Closed, there are some style issues that I did not see before. Will reopen once they're fixed

**Comment by DanielRosenwasser** [comment]
@BendingBender @screendriver @paambaati any chance you can review?

**Review by paambaati — APPROVED** [review]

**Comment by paambaati** [comment]
@alferpal Thanks for the PR!

**Comment by screendriver** [comment]
Why is there a mix of ESModule import `import ... from ...` and CommonJS `import ... = require(...);`?

**Comment by alferpal** [comment]
@paambaati thank you for reviewing and merging!

@screendriver I'm still fairly new to typescript and ESModules. So when I get somewhat confused I still rely on CommonJS.

I'll try to do better next time

**Comment by screendriver** [comment]
> So when I get somewhat confused I still rely on CommonJS.

Yes, I understand that but if you look at all the other imports in the file

```ts
import * as stream from 'stream';
import * as http from 'http';
import { EventEmitter } from 'events';
import SonicBoom = require('sonic-boom');
```

it's confusing now 😬

**Comment by alferpal** [comment]
You're right.

I'll create another PR in the following days to address that

**Pull request merged**
