### PR TITLE
[atom] Support version v1.26.

### PR DESCRIPTION
**Pull request by GlenCFL**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
[Atom v1.26 Release Page](https://github.com/atom/atom/releases/tag/v1.26.0)
[Atom v1.26 Blog Post](http://blog.atom.io/2018/04/18/atom-1-26.html)
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Atom v1.26 has no changes to the API whatsoever. With no changes, we're really just following up on a few things here:
1. Pull request #24967, which kept a type around in order to prevent breakage within a patch version.
2. The deprecation of a property, now that we have clarification from the Atom team [here](https://github.com/atom/atom/pull/17089).

### CODE REVIEW

**Review by lierdakil — APPROVED** [review]
LGTM

**Review by smhxx — APPROVED** [review]

**Comment by lierdakil** [comment]
Actually, I found one thing missing: https://github.com/atom/atom/pull/16661 -- this apparently made it into 1.26, but there's zero documentation except what's in that PR description (JSDoc wasn't touched at all in that PR). Don't want to block over it though.

**Comment by GlenCFL** [comment]
I don't have a problem tacking that on. The only issue would be, as you mentioned, there not being any descriptions for those four properties.

**Comment by lierdakil** [comment]
Well, I can tell you looking at the specs that all those properties should have type `string[]`, and strings are actually `command`s. That's pretty much it. And I think we can always add docstrings later when/if Atom team writes something.

... also, while at it, looking at `ContextMenuOptions`, I think that's a bit under-typed. Should probably be something like

```ts
type ContextMenuOptions = ContextMenuOptionsWithoutType | { type: "separator" }
```

**Comment by lierdakil** [comment]
:+1:

**Pull request merged**
