### PR TITLE
[node] set correct type for process.env and fix node dependents

### PR DESCRIPTION
**Pull request by mdebruijne**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/process.html#process_process_env
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mdebruijne** [comment]
Travis CI result; The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by blakeembrey** [comment]
You might want to make it an interface so someone can add to it. See https://github.com/types/env-node/blob/917516445b42b147384e4c82443322e06548ecf4/6.0/node.d.ts#L431-L434

**Comment by mdebruijne** [comment]
@blakeembrey; good suggestion, thanks, done

**Comment by Seikho** [comment]
The change to `dockerode` looks good to me.

**Comment by paulvanbrenk** [comment]
@andy-ms how do we deal with timeouts for Travis?

**Comment by andy-ms** [comment]
If it made it that far with no errors it should be good.

**Pull request merged**
