### PR TITLE
Node: remove `Dict` type in favour of new compiler option `noUncheckedIndexedAccess`

### PR DESCRIPTION
**Pull request by OliverJAsh**
`Dict` was originally added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43931 as a workaround for https://github.com/microsoft/TypeScript/issues/13778. However, now that https://github.com/microsoft/TypeScript/issues/13778 is resolved and we have the new compiler option `noUncheckedIndexedAccess ` at our disposal, this workaround is no longer necessary.

By making this change we also fix the following issue:

```ts
declare const dict: ParsedUrlQuery;

const value = dict['foo']; // string | string[] | undefined ✅ (when using `noUncheckedIndexedAccess`)

Object.values(dict).map((value) => {
    // Expected: string | string[];
    // Actual: string | string[] | undefined; ❌
    value;
});
```

Reverts https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43931

In some cases I kept `undefined` in the index signature to avoid making breaking changes:

- All new usages of `Dict` (those that appeared after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43931).
- All usages of `Dict` that were included in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43931 which included `undefined` before the change to use `Dict`.
 
We should remove `undefined` from these too but that can be done gradually.

Net result: this PR removes `undefined` from all index signatures which didn't have it in their index signature before https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43931.

/cc @SimonSchick @Flarna 

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Flarna** [comment]
I don't like to be the messenger with the bad news... 
But please note that `noUncheckedIndexedAccess` is available for >= 4.1 but definitions here should support >= 3.3.

According to the [table in readme](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-33-and-earlier) 4.0 is supported till August 2022 so it seems this needs either a lot duplication or has to wait 1.5 years.

**Comment by OliverJAsh** [comment]
> But please note that `noUncheckedIndexedAccess` is available for >= 4.1 but definitions here should support >= 3.3.

I guess it's a question of what "support" should entail. These types will certainly work in 3.3, it's just that indexing will not produce an `undefined`. That's already the behaviour that index signatures will have everywhere else they are used (without `noUncheckedIndexedAccess`), so I think that's acceptable. It's a bug in TS, not the types.

**Comment by Flarna** [comment]
My understanding is that you remove the workaround for a bug before it is ensured that the fix arrives at the users.

Anyhow, I'm on latest typescript so I don't care that much.

**Comment by OliverJAsh** [comment]
Same. My main motivation for doing this was to fix the bug I mentioned: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51160#pullrequest-571298994-permalink:~:text=By%20making%20this%20change%20we%20also%20fix%20the%20following%20issue%3A.

**Comment by OliverJAsh** [comment]
Let's see what other people think. If there's consensus we should wait, we can close this and revisit in August 2022.

**Review by ExE-Boss — CHANGES_REQUESTED** [review]
This is also a breaking change for code that uses the `NodeJS.Dict` type directly.

**Comment by OliverJAsh** [comment]
> This is also a breaking change for code that uses the `NodeJS.Dict` type directly.

What are you suggesting we should do regarding this?

**Comment by ExE-Boss** [comment]
> > This is also a breaking change for code that uses the `NodeJS.Dict` type directly.
> 
> What are you suggesting we should do regarding this?

Keep the `NodeJS.Dict<…>` and `NodeJS.ReadOnlyDict<…>` type definitions.

**Comment by OliverJAsh** [comment]
> Also maybe use `typesVersions` to supply different `NodeJS.Dict<…>` and `NodeJS.ReadOnlyDict<…>` definitions for **TS 4.2+** and revert the other changes.

That could work. I started doing that here, but I got stuck. Can you help? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51177/files#r574374146

**Comment by OliverJAsh** [comment]
Closing in favour of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51177

**Pull request closed without merging**
