### PR TITLE
Update Chai typings to v3.4.0.

### PR DESCRIPTION
**Pull request by mwistrand**
v3.3.0 introduces the following methods:
- `isNotTrue`
- `isNotFalse`
- `isAtLeast`
- `isAtMost`

v3.4.0 introduces:
- `oneOf` assertion.
- `approximately` alias for `closeTo`.

### CODE REVIEW

**Comment by jedmao** [comment]
Looks good, but you'll need two test files now, as the checklist above suggests. Just copy the old tests to chai-3.2.0-tests.ts and you're good to go.

**Comment by mwistrand** [comment]
Thanks; I just added that test file.

**Comment by jedmao** [comment]
:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
