### PR TITLE
[FIX] chained calls with "this" in interfaces

### PR DESCRIPTION
**Pull request by htuscher**
The interfaces nvd3 reference themselves using `this`.

This commit solves the following two errors:
`error TS1110: Type expected`
`error TS2300: Duplicate identifier 'this'`
which occured in masses.

### CODE REVIEW

**Comment by PjMitchell** [comment]
Could I check what the issue was as v1.7 of Ts introduced the use of this to represent fluent apis. Has this been changed or did I use the key word in an incorrect manner?

**Comment by anubmat** [comment]
Thanks for your contribution. This PR has unaddressed comments for over a week and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by hhoechtl** [comment]
I'm using TS 1.8.10, so why is the compiler giving me that errors if it should be supported? Is that something that must be enabled in tsconfig.json? @mhegazy

**Comment by mhegazy** [comment]
Can you share more details about the error?

**Pull request closed without merging**
