### PR TITLE
[aws-lambda] Add authorizer.principalId to APIGatewayEvent.requestContext.

### PR DESCRIPTION
**Pull request by dashmug**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html?tag=vig-20#context-variable-reference
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by buggy** [comment]
No. 👎 

@dashmug The documentation you linked to is for the request/response payload-mapping template and not the the event the API Gateway send Lambda. Do you have a link to something showing this parameter in that event? I've also checked some of my Lambda's and they definitely aren't receiving this property.

**Comment by dashmug** [comment]
@buggy I found a [better documentation here](http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output). Basically, if you use a custom authorizer, you'll get this additional key in `requestContext`.

My definition update still seems to be incomplete though and now I realize it must be optional.

Here's what my Lambda is getting from API Gateway.

```json
{
        "accountId": "670493921695",
        "resourceId": "6bxs6b",
        "stage": "development",
        "authorizer": {
            "principalId": "eyJ1c2VyX3R5cGUiOiJkdW1teSIsImZpcnN0X25hbWUiOiJEZW1vIiwibGFzdF9uYW1lIjoiVXNlciIsImVtYWlsIjoic3VwcG9ydEBhc3NpZ25hci5jb20uYXUiLCJ1c2VybmFtZSI6ImR1bW15IiwidXNlcl9pZCI6MSwidGVubmFudF9pZCI6ImRlbW8iLCJkYmhvc3QiOiJibGFibGFibGEuYXAtc291dGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20iLCJkYiI6ImRldl9kZW1vIiwibW9kdWxlcyI6WyJzZXR0aW5ncyIsImRhc2hib2FyZCIsInByb2plY3RzLWNsaWVudHMiLCJ0YXNrcy1tYWNoaW5lcyIsImRvY3VtZW50cyIsInNraWxscy1jb21wZXRlbmNpZXMiLCJvcmRlcnMiLCJvcmRlcmltcG9ydCIsInRpbWVzaGVldHMtZG9ja2V0cyIsInVzZXJzIiwic21zIiwicmVwb3J0cyIsInRvb2xzIiwicGF5cm9sbCIsImludm9pY2VzIiwiY2hhcmdlX3JhdGVzIiwicGF5X3JhdGVzIiwic3VwcGxpZXJzIiwidXNlcmFjY2VzcyIsImVkaXQtZm9ybS1yZXN1bHRzIiwiZWRpdC1mb3JtLXJlc3VsdHMiLCJzZXR0aW5ncyIsImltcG9ydCIsImRhc2hib2FyZCJdLCJzdWJzY3JpcHRpb25UeXBlIjoiZnVsbCIsImlhdCI6MTQ5MzI1ODQ1MCwiZXhwIjoxNDkzMzAxNjUwfQ=="
        },
        "requestId": "8a169cab-2b13-11e7-a0da-0bb94065480c",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "apiKey": null,
            "sourceIp": "202.134.226.22",
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "PostmanRuntime/3.0.11-hotfix.2",
            "user": null
        },
        "resourcePath": "/{proxy+}",
        "httpMethod": "POST",
        "apiId": "cqinofo4x7"
    },
```

**Comment by buggy** [comment]
This still looks wrong. :-1:

I finally had a chance to go through the second document you linked to. While the custom authorizer needs to return a policy document there's no mention of this being passed into the Lambda as part of the event and your example event doesn't show it either.

```typescript
authorizer?: {
           principalId: string;
           policyDocument?: any; // <-- This doesn't appear to exist
           context?: any; // <-- See below
       };
```

With the context it says:

> For the Lambda proxy integration, the context object returned from an custom authorizer is passed to the back-end Lambda function as the input event. You can retrieve the context key-value pairs in the Lambda function by calling $event.requestContext.authorizer.key. For the preceding custom authorizer example, key can be stringKey, numberKey or booleanKey.

So your definition is wrong there. I would expect to see the `requestContext` inside the `APIGatewayEvent` modified to include:

```typescript
authorizer?: {
  [name: string]: string | number | boolean;
}
```

It would be really useful if you could setup a custom authorizer to return some context values to confirm this is correct.

**Comment by dashmug** [comment]
@buggy 

I have confirmed that `policyDocument` isn't being passed to the lambda function despite my custom authorizer function returning it.

You are right about the `context` so I have modified the code accordingly.

**Comment by buggy** [comment]
@mhegazy Why was this closed? It's still under review.

**Pull request closed without merging**
