### PR TITLE
Karma update

### PR DESCRIPTION
**Pull request by noldor**
Update definitions from version 0.13 to 1.7

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://karma-runner.github.io/1.0/about/changelog.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@tkrotoff, @noldors and @elektromodulator can you please review this change

**Comment by noldors** [comment]
- [x] pass the Travis CI test?

**Comment by tkrotoff** [comment]
It's basically a rewrite, looks good.

Would be safe to keep older definitions inside a `v0.13` directory (examples: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash, https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react)
Is it worth it? Not an obsolete pattern?

**Comment by mhegazy** [comment]
@noldors please see https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version for major version upgrades. you will need to create a new folder `v0` and copy the files before your change into it.

**Comment by andy-ms** [comment]
@noldors It looks like #20144 also made some changes, could you fix the merge conflicts?

**Comment by RyanCavanaugh** [comment]
@noldors Please address the merge conflict.

**Comment by minestarks** [comment]
I'm closing this PR as stale since unfortunately it has merge conflicts that haven't been addressed in over a month. If you would still like to get these changes in, please open a new PR. Sorry about that and thank you!

**Pull request closed without merging**
