### PR TITLE
[metro] Update types for metro packages as of 0.76

### PR DESCRIPTION
**Pull request by huntie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/metro/releases
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

- This is a best-effort update of types for existing metro packages in DefinitelyTyped (all updated types are correct, however in some cases lack of type coverage has not been increased).
- The package `metro-file-map` is added.
- **We are considering this PR a final release**, before inlining type definitions within the Metro repo.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## metro-config ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metro-config@latest/))
was missing the following properties:
1. getDefaultConfig
1. getDefaultConfig
1. getDefaultConfig
## metro-core ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metro-core@latest/))
was missing the following properties:
1. AmbiguousModuleResolutionError
1. Logger
1. PackageResolutionError
## metro-resolver ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metro-resolver@latest/))
was missing the following properties:
1. FailedToResolveNameError
1. FailedToResolvePathError
1. formatFileCandidates
1. InvalidPackageError
## metro-source-map ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metro-source-map@latest/))
was missing the following properties:
1. BundleBuilder
1. composeSourceMaps
1. Consumer
1. createIndexMap
1. generateFunctionMap

<details>
<summary>as well as these 5 other properties...</summary>
<p>fromRawMappings, fromRawMappingsNonBlocking, normalizeSourcePath, toBabelSegments, toSegmentTuple</p>
</details>

## metro ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metro@latest/))
was missing the following properties:
1. loadConfig
1. createConnectMiddleware
1. loadConfig
1. createConnectMiddleware
1. loadConfig

<details>
<summary>as well as these 9 other properties...</summary>
<p>createConnectMiddleware, loadConfig, createConnectMiddleware, loadConfig, createConnectMiddleware, loadConfig, createConnectMiddleware, loadConfig, createConnectMiddleware</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f449e1f296081e1097d7e2a78239c76fccefef6e
</p>

**Comment by jakebailey** [comment]
Hm, the above seem to imply there's a good bit missing.

**Comment by huntie** [comment]
@jakebailey Yes — however this was also the case in the starting state (where types were defined by the consuming `rnx-kit` repo maintainers). This PR has made some type coverage improvements (e.g. [`metro-cache` is fully typed now](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64735/files#diff-4c7bebbf3babad6cf068f064595dbffd12c8c5660c460f557a714385a57fc7f8)), but the aim/effort on our side is we're happy with type coverage remaining partial, so long as the existing covered types are accurate.

Put differently: At least every type that was previously exposed has been reviewed and updated.

**Comment by jakebailey** [comment]
Thanks. The new package seems fine, though I dunno if the maintainers of the existing packages should take a look at the rest. I know @tido64 mentioned this PR above, so it shouldn't be a surprise.

**Review by jakebailey — APPROVED** [review]
That being said, clearly from your profile I can tell you're a metro maintainer, so, I'll let you merge when ready.

**Review by tido64 — APPROVED** [review]
Thanks for updating the types ❤️

I've looked it over and it all looks good to me. I will pull this into rnx-kit for more testing when the packages get published.

**Comment by huntie** [comment]
Ready to merge

**Pull request merged**
