### PR TITLE
[@types/react] New Component types - typing state and props as DeepReadonly

### PR DESCRIPTION
**Pull request by carpben**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Following [feature suggestion 31914](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31914)

Currently this commit adds: 
1. DeepReadonly generic
2. a new component type DRFC which types props as DeepReadonly. 

It's important to note that typing props as DeepReadonly is a breaking change, since you can't pass a regular array to a function that expects to receive a ReadonlyArray (which lacks methods as push etc.). Therefor it is necessary to offer a new type, and not to replace a current one.

### CODE REVIEW

**Comment by carpben** [comment]
As for a class component I tried this class definition:
```
class DRPureComponent<P = {}, S = {}, SS = any> extends React.PureComponent<DR<P>, DR<S>, SS> { }
```
This worked well for many componts, but in one case the combination of this definition and React.ComponentProps (as well as React-Redux' connect function) did not work well. Here is a demo of this on StackBlitz: https://stackblitz.com/edit/react-ts-hhychq . 
This is (almost) the actual code in which the problem occured. As you can see the type of Pr is not recognized (The problem occurs also in SelectionFilter parent - ConnectedSelectionFilter which uses React-Redux' connect). 
Any of the following solves the issue so the type of Pr is recognized: 
1. commenting out the constructor. 
2. (on my VsCode, but not on Stackblitz) commenting selectedIds, and replacing it's instances by []. 
3. Changing Pr's definition to : 
```
export type GetPropsFor<T> = T extends ForwardRefExoticComponent<infer P>
	? P
	: T extends React.ComponentClass<infer P>
		? P
		: T extends (...args: any[]) => any
			? Parameters<T>
			: T extends DRPureComponent<infer P>
				? P
				: never

type Pr = GetPropsFor<SelectionFilter>
```

**Comment by carpben** [comment]
Running "npm run lint react" (on my machine) results in an error: Cannot find module 'csstype'. Any suggestions?

**Comment by ferdaber** [comment]
Go into the React directory in the repo and run npm install

**Comment by carpben** [comment]
The Travis CI build fails since it exceeded the maximum time limit, but there is no error. It seems none of the [recent PRs](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+label%3A%22Popular+package%22+react) pass this test . 

What do you think about the PR?

**Comment by carpben** [comment]
I'll submit a PR later today

**Pull request closed without merging**
