### PR TITLE
Codemirror doc updates

### PR DESCRIPTION
**Pull request by krzysztof-grzybek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

- https://codemirror.net/doc/manual.html#api
- https://github.com/codemirror/CodeMirror/blob/master/src/edit/CodeMirror.js#L41
- https://github.com/codemirror/CodeMirror/blob/3d3bf0e6321ec845bf342f35a1c4a60a44d5fa7a/src/edit/main.js#L21

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Thir PR introduces two changes:

1. Added doc property in CodeMirror.Editor -https://github.com/codemirror/CodeMirror/blob/master/src/edit/CodeMirror.js#L41
2. Added all Doc methods to CodeMirror.Editor - https://github.com/codemirror/CodeMirror/blob/3d3bf0e6321ec845bf342f35a1c4a60a44d5fa7a/src/edit/main.js#L21

### CODE REVIEW

**Comment by krzysztof-grzybek** [comment]
@mihailik what do You mean by that? We don't touch `Doc` here at all. From what I understand, we have to be sure that `Doc` can be used in every place where `Editor` can. Since we're extending prototype of `Editor` with delegated methods, I think we're sure. However, I don't have much experience with `CodeMirror`, so please correct me if I'm wrong.

**Comment by krzysztof-grzybek** [comment]
Additionally, I excluded some delegated methods (see: https://github.com/codemirror/CodeMirror/blob/3d3bf0e6321ec845bf342f35a1c4a60a44d5fa7a/src/edit/main.js#L20 )

**Comment by mihailik** [comment]
I've put my thoughts into the code context.

On the balance, the changes expose parts of the API that are either undocumented or not recommended. I don't think we should do that.

For teams that use `CodeMirror` and make a choice to use those APIs, it is quite easy to add project-specific typings augmenting and extending the standard one. I prefer to steer developers away from non-recommended APIs.

P.S. The documented way is via <a href="https://codemirror.net/doc/manual.html#getDoc"><b>Editor.getDoc()</b> method</a>

**Comment by krzysztof-grzybek** [comment]
When it comes to exposing `doc` property, You're right, it's not documented and it shouldn't be exposed.

Regarding `Doc` methods on `Editor` - I agree that it's arguable in terms of best practices. But in fact, it's documented:

`
Methods prefixed with doc. can, unless otherwise specified, be called both on CodeMirror (editor) instances and CodeMirror.Doc instances. Methods prefixed with cm. are only available on CodeMirror instances.
`

I understand Your arguments, and I somewhat agree with You. But on the other hand, it might be confusing for newcomers (like me :) ) to see methods specified in docs, but unavailable in TS interface.

**Comment by mihailik** [comment]
I think this **SHOULD NOT** be added to CodeMirror typings.

To reiterate:
I understand the intention, but the positive effect of exposing those members is outweighed by the fact those members are non-recommended, exposed in CodeMirror out of compatibility with a very old versions (I believe v2, way before NPM era!) and there is a known, standard and simple way to use those methods. Also, teams really keen on those methods can easily extend standard typings at their side.

Clever use of `keyoff` though, and good API observation. Thanks for the work and effort @krzysztof-grzybek

**Comment by amcasey** [comment]
Where did this land?  Shall I close it?

p.s. @mihailik the bot will do a better job of tagging the PR if you explicitly request changes.

**Pull request closed without merging**
