### PR TITLE
[formidable]: Update - Add type parameters to form.parse function and Fields & Files object types

### PR DESCRIPTION
**Pull request by devLana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test formidable`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## formidable ([<kbd>unpkg</kbd>](https://unpkg.com/browse/formidable@latest/))
was missing the following properties:
1. OctetstreamParser
1. QueryStringParser
1. octetstream
1. querystring
1. multipart

<details>
<summary>as well as these 1 other properties...</summary>
<p>json</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 11b2c0371ba7bfeadecc58b6086134fa14681f5c
</p>

**Comment by devLana** [comment]
This PR adds support for properly typing the keys of `Fields` and `Files`:
1. `parse.form` takes two optional string unions type arguments for `Fields` and `Files` respectively.
2. `Fields` and `Files` will generate an object of optional keys based on the unions passed in as type arguments to `parse.form`
  * The keys are optional because they may or may not be in the parsed request. This enforces the keys to be checked and validated to prevent runtime errors.
  * If no type arguments are passed to `parse.form`, `Fields` and `Files` will be regular object types with optional keys

**Review by martin-badin — APPROVED** [review]

**Comment by devLana** [comment]
> @devLana: Everything looks good here. I am ready to merge this PR (at [11b2c03](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/11b2c0371ba7bfeadecc58b6086134fa14681f5c)) on your behalf whenever you think it's ready.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️
> 
> (@Nemo157, @martin-badin: you can do this too.)

Ready tomerge

**Comment by keysking** [comment]
Is the Files type correct?
```typescript
type Files<U extends string = string> = {
        readonly [Prop in U]?: File[];
};
````
or
```typescript
type Files<U extends string = string> = {
        readonly [Prop in U]?: File;  // Note that this is not an array
};
```
From my debugging results, the latter is correct (using koa-body)

(Sorry for my English)

**Comment by devLana** [comment]
Sorry for the late reply.

I have just ran a test on an express server using formidable. I guess formidable resolves each property in the files and fields to an array after parsing the request. I attached a screenshot for reference.
type Files<U extends string = string> = {
        readonly [Prop in U]?: File[]; // The value is a File array
};

    On Monday, 25 September 2023 at 04:57:28 GMT+1, keysking ***@***.***> wrote:  
 
 


Is the Files type correct?
type Files<U extends string = string> = {
        readonly [Prop in U]?: File[];
};
or
type Files<U extends string = string> = {
        readonly [Prop in U]?: File;  // Note that this is not an array
};
From my debugging results, the latter is correct (using koa-body)

(Sorry for my English)

**Comment by devLana** [comment]
> Is the Files type correct?
> 
> ```ts
> type Files<U extends string = string> = {
>         readonly [Prop in U]?: File[];
> };
> ```
> 
> or
> 
> ```ts
> type Files<U extends string = string> = {
>         readonly [Prop in U]?: File;  // Note that this is not an array
> };
> ```
> 
> From my debugging results, the latter is correct (using koa-body)
> 
> (Sorry for my English)

Sorry for the late reply.

I have just ran a test on an express server using formidable. I guess formidable resolves each property in the files and fields to an array after parsing the request.

I attached a screenshot for reference:
https://github.com/DefinitelyTyped/DefinitelyTyped/assets/52106721/729cb476-a17e-450a-bdf6-954df601f07b

```ts
type Files<U extends string = string> = {
        readonly [Prop in U]?: File[]; // The value is a File array
};
```

**Pull request merged**
