### PR TITLE
feat(node-telegram-bot-api): improved event emitter typings

### PR DESCRIPTION
**Pull request by shadowplay1**
# node-telegram-bot-api

**This PR is making improvements to the typings of `node-telegram-bot-api` package, mainly to the typings of events.**

Changes in this PR:
- Removed `eventemitter3` package from dependencies
- Created a `TelegramBotEventEmitter` interface with every single Telegram API event and parameter types described
- Created a `TelegramBotEventEmitter<E>` class, where `E` is events descriptions interface
- `TelegramBot` now extends `TelegramBotEventEmitter<TelegramBot.TelegramBotEventEmitter>`
- Removed the duplicate code related to event emitter
- Added missing `options` parameter for [TelegramBot.banChatMember()](https://github.com/yagop/node-telegram-bot-api/blob/595cdbd0c656be258bebda2aab5d343de1e938d4/src/telegram.js#L1422C3-L1422C3) and [TelegramBot.unbanChatMember()](https://github.com/yagop/node-telegram-bot-api/blob/595cdbd0c656be258bebda2aab5d343de1e938d4/src/telegram.js#L1444) methods

Checks:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

### CODE REVIEW

**Comment by shadowplay1** [comment]
i'm not sure why do i see the errors (shown at the bottom), especially the fact that i dont see any errors in first half of this interface is really confusing me

is there really anything that im doing wrong in these declarations? or i'm just kinda dumb, idk
```ts
    interface TelegramEvents {
        message: [message: Message, metadata: Metadata]
        text: [message: Message, metadata: Metadata]
        animation: [message: Message, metadata: Metadata]
        audio: [message: Message, metadata: Metadata]
        channel_chat_created: [message: Message, metadata: Metadata]
        contact: [message: Message, metadata: Metadata]
        delete_chat_photo: [message: Message, metadata: Metadata]
        document: [message: Message, metadata: Metadata]
        game: [message: Message, metadata: Metadata]
        group_chat_created: [message: Message, metadata: Metadata]
        invoice: [message: Message, metadata: Metadata]
        left_chat_member: [message: Message, metadata: Metadata]
        location: [message: Message, metadata: Metadata]
        migrate_from_chat_id: [message: Message, metadata: Metadata]
        migrate_to_chat_id: [message: Message, metadata: Metadata]
        new_chat_members: [message: Message, metadata: Metadata]
        new_chat_photo: [message: Message, metadata: Metadata]
        new_chat_title: [message: Message, metadata: Metadata]
        passport_data: [message: Message, metadata: Metadata]
        photo: [message: Message, metadata: Metadata]
        pinned_message: [message: Message, metadata: Metadata]
        sticker: [message: Message, metadata: Metadata]
        successful_payment: [message: Message, metadata: Metadata]
        supergroup_chat_created: [message: Message, metadata: Metadata]
        video: [message: Message, metadata: Metadata]
        video_note: [message: Message, metadata: Metadata]
        voice: [message: Message, metadata: Metadata]
        video_chat_started: [message: Message, metadata: Metadata]
        video_chat_ended: [message: Message, metadata: Metadata]
        video_chat_participants_invited: [message: Message, metadata: Metadata]
        video_chat_scheduled: [message: Message, metadata: Metadata]
        message_auto_delete_timer_changed: [message: Message, metadata: Metadata]
        chat_invite_link: [message: Message, metadata: Metadata]
        chat_member_updated: [message: Message, metadata: Metadata]
        web_app_data: [message: Message, metadata: Metadata]
        callback_query: [query: CallbackQuery] // errors start appearing somewhere here
        inline_query: [query: InlineQuery]
        poll: [poll: Poll]
        poll_answer: [poll: PollAnswer]
        chat_member: [member: ChatMemberUpdated]
        my_chat_member: [member: ChatMemberUpdated]
        chosen_inline_result: [result: ChosenInlineResult]
        channel_post: [message: Message]
        edited_message: [message: Message]
        edited_message_text: [message: Message]
        edited_message_caption: [message: Message]
        edited_channel_post: [message: Message]
        edited_channel_post_text: [message: Message]
        edited_channel_post_caption: [message: Message]
        shipping_query: [query: ShippingQuery]
        pre_checkout_query: [query: PreCheckoutQuery]
        polling_error: [error: Error]
        webhook_error: [error: Error]
        chat_join_request: [query: ChatJoinRequest]
    }
```

errors i get on CI:
```ts
1442:15  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1443:22  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1444:22  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1445:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1446:31  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1447:23  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1448:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1449:30  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1450:33  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1451:30  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1452:35  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1453:38  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1454:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1455:29  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1456:24  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1457:24  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
  1458:28  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
```

**Comment by shadowplay1** [comment]
> i'm not sure why do i see the errors (shown at the bottom), especially the fact that i dont see any errors in first half of this interface is really confusing me
> 
> is there really anything that im doing wrong in these declarations? or i'm just kinda dumb, idk
> 
> ```ts
>     interface TelegramEvents {
>         message: [message: Message, metadata: Metadata]
>         text: [message: Message, metadata: Metadata]
>         animation: [message: Message, metadata: Metadata]
>         audio: [message: Message, metadata: Metadata]
>         channel_chat_created: [message: Message, metadata: Metadata]
>         contact: [message: Message, metadata: Metadata]
>         delete_chat_photo: [message: Message, metadata: Metadata]
>         document: [message: Message, metadata: Metadata]
>         game: [message: Message, metadata: Metadata]
>         group_chat_created: [message: Message, metadata: Metadata]
>         invoice: [message: Message, metadata: Metadata]
>         left_chat_member: [message: Message, metadata: Metadata]
>         location: [message: Message, metadata: Metadata]
>         migrate_from_chat_id: [message: Message, metadata: Metadata]
>         migrate_to_chat_id: [message: Message, metadata: Metadata]
>         new_chat_members: [message: Message, metadata: Metadata]
>         new_chat_photo: [message: Message, metadata: Metadata]
>         new_chat_title: [message: Message, metadata: Metadata]
>         passport_data: [message: Message, metadata: Metadata]
>         photo: [message: Message, metadata: Metadata]
>         pinned_message: [message: Message, metadata: Metadata]
>         sticker: [message: Message, metadata: Metadata]
>         successful_payment: [message: Message, metadata: Metadata]
>         supergroup_chat_created: [message: Message, metadata: Metadata]
>         video: [message: Message, metadata: Metadata]
>         video_note: [message: Message, metadata: Metadata]
>         voice: [message: Message, metadata: Metadata]
>         video_chat_started: [message: Message, metadata: Metadata]
>         video_chat_ended: [message: Message, metadata: Metadata]
>         video_chat_participants_invited: [message: Message, metadata: Metadata]
>         video_chat_scheduled: [message: Message, metadata: Metadata]
>         message_auto_delete_timer_changed: [message: Message, metadata: Metadata]
>         chat_invite_link: [message: Message, metadata: Metadata]
>         chat_member_updated: [message: Message, metadata: Metadata]
>         web_app_data: [message: Message, metadata: Metadata]
>         callback_query: [query: CallbackQuery]
>         inline_query: [query: InlineQuery]
>         poll: [poll: Poll] // errors start appearing somewhere here
>         poll_answer: [poll: PollAnswer]
>         chat_member: [member: ChatMemberUpdated]
>         my_chat_member: [member: ChatMemberUpdated]
>         chosen_inline_result: [result: ChosenInlineResult]
>         channel_post: [message: Message]
>         edited_message: [message: Message]
>         edited_message_text: [message: Message]
>         edited_message_caption: [message: Message]
>         edited_channel_post: [message: Message]
>         edited_channel_post_text: [message: Message]
>         edited_channel_post_caption: [message: Message]
>         shipping_query: [query: ShippingQuery]
>         pre_checkout_query: [query: PreCheckoutQuery]
>         polling_error: [error: Error]
>         webhook_error: [error: Error]
>         chat_join_request: [query: ChatJoinRequest]
>     }
> ```
> 
> errors i get on CI:
> 
> ```ts
> 1442:15  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1443:22  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1444:22  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1445:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1446:31  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1447:23  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1448:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1449:30  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1450:33  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1451:30  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1452:35  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1453:38  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1454:25  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1455:29  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1456:24  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1457:24  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
>   1458:28  error  Type [T] is a single-element tuple type. You probably meant T[]  @definitelytyped/no-single-element-tuple-type
> ```
> 
> is there any fix or workaround for these errors?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67167/commits/c1215c9fe68ff071dbde777f305a4602893902d1, I thought that the problem could happen because of `poll: [poll: Poll]` were all the same (even though it makes no sense to throw errors bc of it), but yeah, renaming "poll" to "pollObject" as kind of workaround didn't help

Hope to get feedback on this from devs or DT maintainers, thanks in advance ❤

**Comment by XC-Zhang** [comment]
There is a rule @definitelytyped/no-single-element-tuple-type that prevent us using type like `[poll: poll]`

**Comment by shadowplay1** [comment]
how am i supposed to type this then?

**Comment by shadowplay1** [comment]
i think i got an idea

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-telegram-bot-api/index.d.ts
1. types/node-telegram-bot-api/node-telegram-bot-api-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 21c14abf15b200440016170275bad9f5092266f5
</p>

**Comment by shadowplay1** [comment]
🙂

**Review by XieJiSS — APPROVED** [review]
Seems like this should work

LGTM

**Comment by shadowplay1** [comment]
🙂

**Comment by shadowplay1** [comment]
Ready to merge

**Pull request merged**
