### PR TITLE
Easeljs SpriteSheets The parameter in getNumFrames can be ommited

### PR DESCRIPTION
**Pull request by DayLightDancer**
The parameter in getNumFrames can be null.
Reference:
http://www.createjs.com/docs/easeljs/classes/SpriteSheet.html#method_getFrame

### CODE REVIEW

**Comment by mhegazy** [comment]
@DayLightDancer can you rebase?

**Comment by DayLightDancer** [comment]
I rebased but I am not sure what to do next.

**Comment by mhegazy** [comment]
your remote seems to be set to an old revision. so i would create a new PR, but first make sure your fork is sync'ed with master, then create the PR.

**Comment by bowdenk7** [comment]
Thanks for your contribution. This PR has merge conflicts and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
