### PR TITLE
googlemaps: make a type definition consistent with docstring for strictNullChecks

### PR DESCRIPTION
**Pull request by svenkreiss**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: docstring is right above the changed line
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@svenkreiss Please fix the failures indicated in the Travis CI log.

**Comment by andy-ms** [comment]
Fixed by #21384.

**Comment by svenkreiss** [comment]
To clarify ^, fix refers to CI failures. This is PR is still waiting for reviewer feedback.

**Comment by martincostello** [comment]
Seems legit.

**Pull request merged**
