### PR TITLE
fs-extra - error callback compatible with strictFunctionTypes

### PR DESCRIPTION
**Pull request by GLahotiTech**
The existing error callbacks with `err: Error | null` fail with `strictFunctionTypes` set to true in TS 2.6.1. This commit makes them compatible.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by alan-agius4** [comment]
Will I didnt look that much in deep in strictFunctionTypes i am not sure about the change cause the callback value can be either an Error or null.

I’d need to look into it a bit more unless someone else from DT pr TS agrees with the change. 

Ill try to look into it this weekend

**Comment by Dante-101** [comment]
Probably NodeJS `fs` definitions will help.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts

In short, the idea is that the argument to the callback function in the definition must be the same or subset of the argument of the callback function passed. 
`Error` is subset of `Error | null` and `Error | undefined`

**Comment by alan-agius4** [comment]
Cheers for that and the PR

Approved!

**Comment by Dante-101** [comment]
I just realized someone will have to upgrade the definitions. With NodeJS 8 in LTS, we need to move beyond v6 definitions and make them same as NodeJS 8.

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Comment by rbuckton** [comment]
@Dante-101 Can you elaborate on what needs to change in the NodeJS definitions?

**Comment by Dante-101** [comment]
@rbuckton I saw few differences in Node 8.x `fs` definitions and `fs-extra` definitions.

For instance, in the latest node definitions, paths are assigned type `string | Buffer | URL | number`  instead of `string | Buffer | number`. I presume there will be other changes too. I haven't analyzed the differences completely.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts

Nevertheless, I believe it will be better to upgrade the definitions of NodeJS native `fs` methods for future compatibility.

**Comment by RyanCavanaugh** [comment]
@Dante-101 Please address the merge conflict.

**Pull request merged**
