### PR TITLE
update(svg-spritemap-webpack-plugin): v3.6 updates

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- 'keepAttributes' style options
- remove references to webpack 4 only types

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/compare/v3.5.10...v3.6.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
fixed merge conflict (v3.7 went earlier than v3.6)

**Comment by peterblazejewicz** [comment]
Ready to merge 💋

**Review by amcasey — APPROVED** [review]

**Comment by amcasey** [comment]
@peterblazejewicz "ready to merge" stops working after a push, but the bot should re-offer in a moment.

**Comment by peterblazejewicz** [comment]
Ready to merge 💋

**Pull request merged**
