### PR TITLE
fix: drop incorrect types for webtorrent org packages

### PR DESCRIPTION
**Pull request by ThaUnknown**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

These types for webtorrent's packages have been outdated for ages, and for the most part aren't needed because we use JSDoc where it's important.

These types are causing an insane amt of issues for us, both for development, and for maintaining, since VSCode incorrectly inherits DT's types, and people keep making issues complaining that a function works incorrectly, because these types are wrong and are telling them incorrect things.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69947

### CODE REVIEW

**Review by jakebailey — CHANGES_REQUESTED** [review]
These packages do not contain types; this is definitely not the right fix: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69947#issuecomment-2231285511

**Comment by ThaUnknown** [comment]
@jakebailey what is the correct way of proceeding then, that doesn't require me to waste weeks of my free time?
- making DT types accurate is unrealistic because of the sheer amt of work it requires
- overriding these invalid types in our package with `any` breaks type inference and intellisense
- generating from JSDoc leads to similarly incorrect types as `tsc` isn't omnipotent and can't detect dynamic key access and probably other things

I'd preferably want to not have types from DT apply after specific versions:
- webtorrent@2.0.0
- create-torrent@6.0.0
- bittorrent-protocol@3.5.4
- parse-torrent@11.0.0
since thats roughly where the old types are still accurate _enough_, and simply let the already defined jsdoc in the package and type inference take over, but I don't know if typescript even allows that

**Comment by ThaUnknown** [comment]
bump

**Comment by ThaUnknown** [comment]
bump

**Comment by ThaUnknown** [comment]
bump

**Comment by ThaUnknown** [comment]
bump

**Review by jesec — CHANGES_REQUESTED** [review]
Reject.

The same set of changes has been reverted in #70059. 

Also +1 on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69947#issuecomment-2229732054 , https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69947#issuecomment-2231285511 .

Please reply to those comments and avoid spamming new pull requests and trying to force it through without additional merit.

**Comment by ThaUnknown** [comment]
lord this is by far the most annoying repository i've ever experienced, package provides jsdoc where it's applicable, and all these people whining that there are no types, aren't fixing the types, WHICH ARE COMPLETLY INCORRECT, I do NOT understand how some1 can merge broken and incorrect types, and then the repository maintainers can't remove them, even tho they are malicious, anyways since i'm the package maintainer so since this repo is so against me being able to remove the incorrect types, i'll just force resolve it to `any`

**Comment by ThaUnknown** [comment]
also @jesec those comments were replied to, so idk what you're saying

**Comment by ThaUnknown** [comment]
yes, that PR was created because DT tied my hands, it wouldn't exist if I could simply control the types over the packages I maintain, the fact that package maintainers don't have permissions to their own types is a bit wild to me

to me marking the packages as not needed is the best way to do it, but DT clearly doesn't agree until I have my own types, which is why that PR exists

**Comment by jakebailey** [comment]
> it wouldn't exist if I could simply control the types over the packages I maintain, the fact that package maintainers don't have permissions to their own types is a bit wild to me

What you you mean? You can totally be an owner on the DT packages and send PRs to DT.

**Comment by ThaUnknown** [comment]
> > it wouldn't exist if I could simply control the types over the packages I maintain, the fact that package maintainers don't have permissions to their own types is a bit wild to me
> 
> What you you mean? You can totally be an owner on the DT packages and send PRs to DT.

clearly not, because I cannot remove these incorrect types

**Comment by jakebailey** [comment]
Removing the types and breaking all TS users is a totally different scenario to just updating the types so that they're correct. Adding/removing packages from DT is something that has to be monitored.

There are a non-zero number of packages which are on DT and have types updated by their maintainers or community members; if you sent a PR that updated the types here, it would absolutely be reviewed and accepted. DT is supposed to be wikipedia for types, but even wikipedia doesn't just let anyone delete pages.

**Comment by ThaUnknown** [comment]
yes, but wikipedia moderates incorrect entries, this doesnt, maybe by breaking it for users which auto-update all packages instead of locking versions, some1 will spent the month or so of their life creating these types

**Comment by jakebailey** [comment]
The options here are:

- You put `.d.ts` files (of any quality, I don't care!) into your packages making them typed, we merge this PR after those are published so your packages are pointed to in the deprecated shims in `@types` on npm. Your users (TS and JS users both) file issues about the quality / accuracy of your types to your repo and you fix them (or don't).
- You update the types here to be accurate. TS and JS users are happy.
- You don't personally update the types here, but point anyone on your repo to the DT repo to make contributions to fix this, and close their issues as not your problem. 

Which of these do you want to do to resolve the problem?

I do not see any other option. We simply cannot merge this PR as-is without other `d.ts` files present as that will make your packages _unimportable_ in any TypeScript file.

**Pull request closed without merging**
