### PR TITLE
Use consistent syntax for ramda-test blocks + Random updates + typings generator

### PR DESCRIPTION
**Pull request by BjornMelgaard**
* append
* binary
* bind
* both
* clone
* comparator
* complement
* countBy
* max
* maxBy
* min
* minBy
* sortBy
* prop
* tryCatch
* unary
* unnest
* where
* whereEq
* wrap (removed)

Added typings generator based on handlebars templates (to cover more cases with different variations of arguments and functions number) and generated this typings
* pipeP (added)
* pipe
* pipeK (added)
* composeK (added)
* composeP (added)
* compose

Related issues: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17796

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
TODO: 
- generate compose functions
- add 0 args case to generator
- reference generated through
```ts
///<reference path="generated/pipePFn.d.ts"/>
///<reference path="generated/pipeFn.d.ts"/>
```

**Comment by BjornMelgaard** [comment]
@RyanCavanaugh , im waiting answer on this comment https://github.com/ramda/ramda/pull/2306#issuecomment-333974740 to remove `.gitignore` and `package.json` and left only generator script

**Comment by BjornMelgaard** [comment]
I am abandoning this pr in favor of [npm-ramda](https://github.com/types/npm-ramda/), but I wont close it in case someone want to make use of it.

**Comment by RyanCavanaugh** [comment]
@BjornMelgaard Please address the merge conflict.

**Comment by RyanCavanaugh** [comment]
@BjornMelgaard - It appears Travis did not correctly run on this PR! /cc @RyanCavanaugh to investigate and advise.

**Comment by minestarks** [comment]
@RyanCavanaugh are you a robot?

Closing due to abandonment.

**Pull request closed without merging**
