### PR TITLE
Separated JointJS from Rappid

### PR DESCRIPTION
**Pull request by DenEwout**
Follow-up on: https://github.com/borisyankov/DefinitelyTyped/pull/3595

### CODE REVIEW

**Comment by DenEwout** [comment]
Will fix the above issue as soon as I can. I was a bit ahead of myself with the pull-request.

**Comment by horiuchi** [comment]
@DenEwout Thank you your contributions.
Please fix Travis CI failed. https://travis-ci.org/borisyankov/DefinitelyTyped/builds/49714131

**Comment by DenEwout** [comment]
Voilla.

**Comment by DenEwout** [comment]
I believe remove(): void would be more correctly defined on the Cell class, but the API documents them seperately (see http://jointjs.com/api#joint.dia.Element:remove, 
http://jointjs.com/api#joint.dia.Link:remove), so I added it to both Link and Element.

**Comment by vvakame** [comment]
@areel @DavidDurman @DenEwout could you review this PR?

**Comment by DenEwout** [comment]
Any update regarding this? We'd rather switch over to the DefintelyTyped repository rather than worrying about keeping this fork up to date for possible changes.

**Comment by areel** [comment]
Hi

 

Sorry for not replying.

 

I am no longer actively using JointJS / Rappid.

 

So feel free to take ownership the repo. 

 

Let me know if there is any task I need to do in order to release ownership.

 

Regards

 

Aidan

**Comment by vvakame** [comment]
@areel thanks to reply.
@DenEwout thanks mate. It merged!

**Comment by DenEwout** [comment]
No problem, thanks for the merge.

**Pull request merged**
