### PR TITLE
Add null assertions and an undefined assertion alias to should.js.

### PR DESCRIPTION
**Pull request by seansfkelley**

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from authors. I'll merge this PR in 2 days. please ping me again.

**Comment by seansfkelley** [comment]
@vvakame here's that ping you asked for!

**Comment by seansfkelley** [comment]
@vvakame can you merge this? Thanks!

**Comment by horiuchi** [comment]
@seansfkelley Thanks!

**Pull request merged**
