### PR TITLE
Added more definitions to Leaflet 1.0

### PR DESCRIPTION
**Pull request by alejo90**
Added more missing definitions

case 2. Improvement to existing type definition.
- API http://leafletjs.com/reference-1.0.0.html

### CODE REVIEW

**Comment by andy-ms** [comment]
Thanks! Could you review #11431 and #11433?

**Comment by alejo90** [comment]
Sure.

**Comment by andy-ms** [comment]
@lediur could you review?

**Comment by lediur** [comment]
Looks good to me - I think there are a few minor `coordsToLatLng` and `latLngToCoords` overrides that are missing, but otherwise :+1:

What's the general consensus for adding descriptions for type definitions? If you'd like, I can make the comments suggested to my pull request for #11433 so the descriptions get preserved, then merge that in here

**Comment by alejo90** [comment]
Preserving the descriptions would be great. I don't know what the best approach is, though. Maybe wait for this to be merged and then you can add as a pull request for on this branch? I still have to complete the tests and other definitions, so I wouldn't get in your way with the descriptions.

**Comment by lediur** [comment]
Maybe I can make a PR with the descriptions into your working branch `alejo90/improve-leaflet-1.0.0-typings`?

**Comment by alejo90** [comment]
Thanks! That would work too.

**Comment by lediur** [comment]
Going through and adding descriptions, I found some typos - will also fix in my PR to you

**Comment by alejo90** [comment]
Great, thanks.

**Comment by andy-ms** [comment]
Can I get a :+1:?

**Comment by alejo90** [comment]
👍

**Comment by lediur** [comment]
Great - will wait for @types to update :tada:

**Comment by andy-ms** [comment]
This requires a manual merge, which happens about every week. I'll do one tomorrow morning.

**Pull request merged**
