### PR TITLE
about graphic

### PR DESCRIPTION
**Pull request by PollionChang**
add echarts graphic LinearGradient

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/ecomfe/echarts/issues/4817>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
[The tests](https://github.com/ecomfe/echarts/blob/fb87c5f863187399dfb18026570b3b4334bec48f/test/axis.html#L131) seem to indicate that it's a constructor, not a simple function. Also, please add tests.

See: https://github.com/ecomfe/echarts/blob/fb87c5f863187399dfb18026570b3b4334bec48f/test/axis.html#L131

**Comment by RyanCavanaugh** [comment]
@PollionChang Please address comments from the code reviewers.

**Comment by PollionChang** [comment]
Oh...I'm sorry for this situation because I did not think carefully, indeed it's a constructor, not a simple function.I will rewrite the code and  add tests.

**Comment by DanielRosenwasser** [comment]
@PollionChang you can quickly hack around this with

```ts
LinearGradient: new (x: number, y: number, x2: number, y2: number, colorStops: Array<Object>, globalCoord?: boolean): any;
```

**Comment by PollionChang** [comment]
@DanielRosenwasser  
thanks for your advice,In fact I have made improvements about this ,i will recommit  this later;

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
