### PR TITLE
Correctly type d3.event

### PR DESCRIPTION
**Pull request by myitcv**
In https://github.com/borisyankov/DefinitelyTyped/pull/4623 @gustavderdrache defined the type of `d3.event` to be `Event` where `Event` is defined as:

``` typescript
interface Event extends KeyboardEvent, MouseEvent {}
```

However, I don't think this is correct. `d3.event` will be a `KeyboardEvent` _or_ a `MouseEvent` (or indeed other event types, see below). In which case a union type is the more correct definition.

Indeed with zooming, `d3.event` can also be [another type](https://github.com/mbostock/d3/wiki/Zoom-Behavior#event):

``` typescript
interface ZoomEvent {
  scale: number;
  translate: [number, number];
}
```

It can also be a [drag event](https://github.com/mbostock/d3/wiki/Drag-Behavior#on), hence I have defined this type as well (per the definition in the D3 docs) and fixed up the use of `any` in the tests.

Tests updated, @gustavderdrache would appreciate your thoughts.

### CODE REVIEW

**Comment by gustavderdrache** [comment]
It's going to be an imperfect solution either way since `d3.event` is a global. That having been said, this seems like a substantially better solution. A+!

That having been said, since we have to include type assertions anyway, it may be simplest to define the type as `Event | ZoomEvent | DragEvent`, so that any usage of the property as a DOM event goes through the same logic as if using the global `window.event` property. Thoughts?

**Comment by myitcv** [comment]
@gustavderdrache - thanks, your comment forced me to look a bit harder at the documentation.

According to [this page](https://github.com/mbostock/d3/wiki/Selections#d3_event), we should be defining `d3.event` with type `Event` (as defined by [`lib.dom.d.ts`](https://github.com/Microsoft/TypeScript/blob/e9dc96598cd635265881104b08b4a4120b43f845/lib/lib.dom.d.ts#L3167))

The only discrepancies that then remain appear to be:

* The [D3 documentation for a drag event](https://github.com/mbostock/d3/wiki/Drag-Behavior#on) and the [MDN definition for a DragEvent](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent) seem to differ, in that the D3 event exposes `dx` and `dy` properties
* The [D3 documentation for a zoom event](https://github.com/mbostock/d3/wiki/Zoom-Behavior#on) and the [MDN definition for a ZoomEvent](https://github.com/Microsoft/TypeScript/blob/e9dc96598cd635265881104b08b4a4120b43f845/lib/lib.dom.d.ts#L10440) (which is in fact an SVGZoomEvent) differ, in that the D3 definition exposes `scale` and `translate` (compare `newScale` and `newTranslate`)

Hence my suggestion would be the following:

```typescript
// is there a way to refer to DragEvent as defined in the global
// module without defining a type alias? According to 
// https://github.com/Microsoft/TypeScript/issues/983 apparently not
declare type _DragEvent = DragEvent;

declare module d3 {
	// ...

	interface ZoomEvent extends UIEvent {
		scale: number;
		translate: [number, number];
	}

	interface DragEvent extends _DragEvent {
		dx: number;
		dy: number;
	}

	// Event as defined in lib.dom.d.ts
	export var event: Event;

	// ...
}
```

How does that sound?

**Comment by gustavderdrache** [comment]
Huh, this is starting to get interesting. I think that your original definitions of `ZoomEvent` and `DragEvent` were actually correct.

I rooted around in the D3 source and found that while there are a few convolutions in the drag behavior, it goes roughly like this:

1. The drag behavior creates a [custom dispatcher](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L11).
2. There is a [great deal of text](https://github.com/mbostock/d3/blob/master/src/event/event.js#L26-L34) that describes what the event dispatcher does, but the important thing to note is that the [dispatch function](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L26):
  1. Only receives the fields passed to it (see e.g., [`"dragstart"`](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L42), [`"drag"`](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L53-L59), and [`"dragend"`](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L66), and
  2. Populates the [source event](https://github.com/mbostock/d3/blob/master/src/event/event.js#L39) that caused the custom event to be dispatched.

The usage of things like [dragstart](https://github.com/mbostock/d3/blob/master/src/behavior/drag.js#L13-L14) indicate that it could be either mouse or touch events that caused those events to fire, so the `sourceEvent` field is probably properly a DOM `Event` interface that users will have to query (e.g., `instanceof`) or assert to use:

```typescript
drag.on('drag', () => {
    let event = <d3.DragEvent> d3.event,
        // probably not actually correct, but you get the idea
        source = event.sourceEvent.type === 'mousemove'
               ? <MouseEvent> event.sourceEvent
               : <TouchEvent> event.sourceEvent;
});
```

Incidentally, the zoom events [do the same thing](https://github.com/mbostock/d3/blob/master/src/behavior/zoom.js#L175-L186).

The most correct (and, admittedly, most annoying) solution might therefore be to define all of these interfaces (at least most of them will only look like `{ type: string; sourceEvent: Event }`) and let the user assert as needed.

**Comment by myitcv** [comment]
> The most correct (and, admittedly, most annoying) solution might therefore be to define all of these interfaces (at least most of them will only look like { type: string; sourceEvent: Event }) and let the user assert as needed.

Just to check I've understood, are you essentially advocating the following:

```typescript
declare module d3 {
	// ...

	interface BaseEvent {
		type: string;
		sourceEvent?: Event;
	}

	interface ZoomEvent extends BaseEvent {
		scale: number;
		translate: [number, number];
	}

	interface DragEvent extends BaseEvent {
		x: number;
		y: number;
		dx: number;
		dy: number;
	}

	export var event: Event | BaseEvent;

	// ...
}
```

If so I'm totally behind that.

**Comment by gustavderdrache** [comment]
Yup!

**Comment by myitcv** [comment]
@gustavderdrache - just pushed up exactly that change.

**Comment by gustavderdrache** [comment]
Lookin' good! :+1:

**Comment by myitcv** [comment]
@vvakame et al, this is ready for your consideration please!

**Comment by vvakame** [comment]
@gustavderdrache thanks!
@myitcv thanks mate! sorry for late.

**Comment by myitcv** [comment]
@vvakame no worries, thanks for merging.

**Comment by bcrigler** [comment]
I am still having this issue with the latest version.  Not sure if someone messed it up with a newer commit or what?

**Pull request merged**
