### PR TITLE
gapi.calendar: Adding gapi calendar event delete functionality in gapi.calendar wrapper

### PR DESCRIPTION
**Pull request by bmandalapu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by tkrotoff** [comment]
Could you provide a link to the documentation of delete() so I can check + add a test to gapi.calendar-tests.ts if possible.
Thx

**Comment by bmandalapu** [comment]
Thanks @tkrotoff . I will add the tests.
Let me know where to add documentation for delete(). Shall I add it in the read me file?

**Comment by tkrotoff** [comment]
Here in this PR comments, just for me to have a look. It is true that it can also be added as a comment just above the delete() function, as you want

**Comment by bmandalapu** [comment]
Hi @tkrotoff ,
I have added comments in index.d.ts and provided the tests. 
Could you please merge this PR.

Documentation:
The new method delete() is added to delete the existing event from the user calendar. Please refer to https://developers.google.com/calendar/v3/reference/events/delete for more info.
Below are mandatory input parameters.
calendarId: 'primary' or the calendar from which the event need to be deleted
eventId: the event that need to be deleted from calendar (you can use the Event.id from the list/insert responses)

If successful, this method returns an empty response body.

**Comment by tkrotoff** [comment]
You have inverted documentation between gapi.calendar-tests.ts and index.d.ts, documentation should be inside index.d.ts

**Comment by bmandalapu** [comment]
removed documentation from gapi.calendar-tests.ts.

**Review by tkrotoff — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Comment by bmandalapu** [comment]
Thanks All.

**Pull request merged**
