### PR TITLE
[markdown-it] Move to ES modules

### PR DESCRIPTION
**Pull request by runarberg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md#1400---2023-12-08
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by runarberg** [comment]
This is my first contribution, and I’m not sure if I’m doing things correctly here.

I couldn’t get the tests to pass, unless I duplicated the code for the commonjs modules. Version 14 of Markdown-It builds the `dist/` directory, and only exports a single file there. So I’m not sure if you can actually import from `/lib` (or subdirectories inside `/dist`) any more using commonjs any longer.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/markdown-it-external-links/index.d.ts
1. types/markdown-it/index.d.mts
1. types/markdown-it-container/markdown-it-container-tests.ts
1. types/markdown-it-link-attributes/index.d.ts
1. types/markdown-it/markdown-it-tests.ts

<details>
<summary>as well as these 5 other files...</summary>
<p>types/markdown-it/lib/parser_inline.d.mts, types/markdown-it/lib/index.d.mts, types/markdown-it/test/helpers/index.mts, types/markdown-it/lib/helpers/index.d.mts, types/markdown-it/test/index.mts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6109d310649d220a1711690e66ae91b1909118a2
</p>

**Review by weswigham — CHANGES_REQUESTED** [review]
> I couldn’t get the tests to pass, unless I duplicated the code for the commonjs modules. Version 14 of Markdown-It builds the dist/ directory, and only exports a single file there. So I’m not sure if you can actually import from /lib (or subdirectories inside /dist) any more using commonjs any longer.

Looks like the package [ships a single cjs file in dist](https://www.npmjs.com/package/markdown-it?activeTab=code), but exclusively esm in `lib`, and actually does expose both in its exports map (imo, a sloppy and very breaky migration to esm!). You'll want to duplicate that structure here - `dist` should just have a single `markdown-it.d.ts` in it, with types reexported in `index.cjs.d.ts` and `markdown-it.min.d.ts`. `lib` also needs all its files renamed to `.d.mts` to match all the `.mjs` files now in `lib` (which you've done). You'll also need to add an export map that roughly matches their published one (which you've also done).

This *will* break every other package doing a deep import of `markdown-it` - but so, too, did the source package. If the dependencies actually work with the new `markdown-it`, they'll have to be updated to use a shallow import or mode-appropriate import, otherwise be fixed to an old version of the `markdown-it` types.

**Comment by runarberg** [comment]
@weswigham You can still access the exported symbols from the default export, albeit sometimes via a very roundabout way:

```js
const MarkdownIt = require("markdown-it");

// import Token from "markdown-it/lib/token.mjs";
const Token = MarkdownIt().core.State.prototype.Token;
```

I’m guessing downstream libraries will have to go an equally roundabout way of getting the type symbols:

```ts
import MarkdownIt = require("markdown-it");
type Token = InstanceType<MarkdownIt["core"]["State"]>["Token"];
```

**Comment by weswigham** [comment]
> I’m guessing downstream libraries will have to go an equally roundabout way of getting the type symbols

Yes and no - for actual value shapes, yes - if that's where the values are at runtime, that's where they gotta be. For type-only things like interfaces? You can probably get away with exposing them under a namespace merged with the top level call (for cjs), or directly at the top level (for esm). There's a long history of types being more easily accessible than the existing values that use them.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by runarberg** [comment]
There is a fair bit of duplicated code here, I’m wondering if it were better to import the typedefs from `dist/markdown-it.d.ts` to the `lib/*.mts` files.

I also worry that the tests are separated between the `lib/*.mts` typedefs and `dist/markdown-it.d.ts` typedefs. I didn’t really add tests that cover the stuff I moved to the main namespace from the various modules in the commonjs portion.

**Comment by jakebailey** [comment]
You can totally do that; if it compiles and node16 is enabled, that should work.

**Comment by runarberg** [comment]
@jakebailey I tried to reference the type definitions in `dist/markdown-it.d.ts` from the `lib/*.mts` files, but couldn’t cleanly separate the namespace imports from the class/value imports (unsurprising really, I never use namespaces in my own code and don’t really know what I’m doing 😉). So I’m gonna leave the duplicated typedefs as is.

However I amended the PR with the tests copy-pasted from `/tests/*.mts` files over to the main `markdown-it-tests.ts` (and discovered an error and a type-o doing so), so I feel a little more confident in the correctness now.

**Review by jakebailey — APPROVED** [review]
alright, so long as you are okay with someone potentially accidentally changing one declaration file but not another!

**Comment by runarberg** [comment]
Ready to merge

**Pull request merged**
