### PR TITLE
[node] Add definition for Node.js v8

### PR DESCRIPTION
**Pull request by ikokostya**
List of changes:

* Move current `types/node/index.d.ts` to `types/node/v7/index.d.ts`
* Remove `util.promisify` (introduced by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16946) from `v7/index.d.ts`, because this function is available since Node.js v8.
* Use `types/node/index.d.ts` for Node.js v8 - increase the version number in the header.
* Change `compilerOptions.lib` to `es6` in `tsconfig.json` like in `types/node/v6/tsconfig.json`.

***

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v8.x/docs/api/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
See #16860.
This branch doesn't seem to make any type changes to `node/index.d.ts`.

**Comment by ikokostya** [comment]
@andy-ms The problem now that users add feature to declaration for Node.js **v7** which doesn't exist in Node.js v7 runtime.

There are several problems:
* Code will be compiled with such definition, but will fail at runtime.
* People can start to use declaration for Node.js **v7** with Node.js **v8** runtime. After that, removing anything related to Node.js v8 from v7 definition potentially can brake many modules.

If you have separated issue (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16860) for Node.js v8, why pull request with [util.promisify](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16946) was merged?

**Comment by hinell** [comment]
@ikokostya This solution doesn't seem solve broken runtime anyway cause there are plenty modules that just referencing the latest ``DT/node/index.d.ts`` version in their dependencies meaning moving index.d.ts to separate folder won't help it.

**Comment by ikokostya** [comment]
So @yuit @andy-ms what we wait here? Could you provide TODO list of necessary changes for Node.js 8 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16860#issuecomment-306265687?

**Comment by minestarks** [comment]
@andy-ms to close the loop. I don't see a reason not to merge this. It'll keep people from adding v8 features to v7 typings. Any objections?

**Review by ghost — APPROVED** [review]

**Comment by magnushiie** [comment]
It seems this has not been published to @types/node npm package yet? The latest version of that package is 7.0.31

**Comment by minestarks** [comment]
@magnushiie check again, it's up

**Comment by magnushiie** [comment]
Thanks!

**Pull request merged**
