### PR TITLE
Added more component definitions to video.js

### PR DESCRIPTION
**Pull request by Akxe**
Added functions to player and some components and theirs basic functions.

### CODE REVIEW

**Comment by Akxe** [comment]
Hello, I am not sure what to do with this. Anyone cold point me in right direction?

**Comment by Akxe** [comment]
I have fixed the tslint error, but I don't know what to do about test on TS@next not working...

**Comment by Akxe** [comment]
I need some asistence here.

**Comment by Akxe** [comment]
But if I do so then a the common syntax won't work `import videojs from 'video.js'`

**Comment by Akxe** [comment]
@vbortone as I thought using this method break the other one. I would be more inclined to this version, so I gonna rewrite tests
error: `An export assignment cannot be used in a module with other exported elements.`

**Comment by vbortone** [comment]
👍

**Comment by briandk** [comment]
## First, thanks

Thank you for the work and time you put into making this wonderful set of types. I really do appreciate it.

## I think this is a breaking change

 Assuming we use [semantic versioning,][2] reverting to [default export][1] is a breaking API change.

```ts
// Behavior in 6.2.5
import { PlayerOptions } from "video.js" // works just fine
```

```ts
// Behavior in 6.2.9
import { PlayerOptions } from "video.js" // error TS2305
                                         // Module has no exported member 'Player'.
```

## The Workaround

```ts
// import videojs, then access its properties directly
import videojs from "video.js"
const myOptions: videojs.PlayerOptions = {autoplay: true}
```

## My questions

1. Do you folks agree this constitutes a breaking change? 
2. If so, should this be a MAJOR version bump as per [semver][2]?
3. Should we add tests that would catch these kinds of changes?

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27163#issuecomment-405623554
[2]: https://semver.org/

**Comment by weswigham** [comment]
Ahhhh, I didn't catch the export kind change with the options change. Can you open a PR to change it back? The default is almost certainly wrong.

**Comment by Akxe** [comment]
Can you show me then how pass the new tests? Also, what about all those changes? The breaking change is on one line only.

**Comment by weswigham** [comment]
No - the export assignment was correct. If your bundler looked at the es module file and loaded it as a default, for example, you should enable the `alloeSyntheticDefaultImports` and/or `esModuleInterop` flags on your TS build. This can be turned on for the tests, though simply changing the import back to an import require would also suffice.

**Comment by Akxe** [comment]
Also, there is new video.js type definitions beeing created from author.
see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27515

**Comment by briandk** [comment]
@weswigham I'm happy to PR this. Would it be a problem if there are merge conflicts between my PR and @giofreitas 's PR?

**Comment by weswigham** [comment]
Naw, his'll just need to be refreshed with the change.

**Pull request merged**
