### PR TITLE
Automatically remove definition owners with deleted GitHub accounts

### PR DESCRIPTION
**Pull request by andrewbranch**
Main question is do we feel ok about @typescript-bot pushing the results straight to master? We could have it open a PR instead, which would ping the other definition owners, but that might not be the worst thing after the first run, which modifies a lot of packages. Subsequent monthly runs will presumably be smallish and the DT maintainer for that week can make sure the script didn’t go off the rails.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
LGTM!
love this little one:
```diff
//                 A penguin <https://github.com/sirMerr>
```

**Review by peterblazejewicz — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
I like the idea of a PR after the first run

**Review by orta — APPROVED** [review]
Code looks good

**Comment by andrewbranch** [comment]
I just updated the action to support opening a PR. I think there’s not a great way to test this without pinging a lot of people, so I would propose that I’ll just commit to keeping an eye on it on the first of each month until we see it do the right thing.

**Review by sandersn — APPROVED** [review]

**Comment by andrewbranch** [comment]
Updating the cron schedule to daily based on @RyanCavanaugh's suggestion

**Review by weswigham — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
