### PR TITLE
[bitcore-lib] added Message class

### PR DESCRIPTION
**Pull request by hoonsubin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bitpay/bitcore/blob/master/packages/bitcore-lib/lib/message.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Additional notes:
Sorry for all the junk in the commits. This was caused due to the use of auto-formatting code in my text editor and rebasing my fork to solve a CI error (and my lack of professionalism)
The following blocks of code are the only changes that I am making to the type definitions, everything else is irrelevant. Sorry for the confusion.

```
// types/bitcore-lib/index.d.ts
export class Message {
    constructor(message: string);

    magicHash(): Buffer;
    sign(privateKey: PrivateKey): string;
    verify(bitcoinAddress: Address | string, signatureString: string): boolean;
    fromString(str: string): Message;
    fromJSON(json: string): Message;
    toObject(): { message: string };
    toJSON(): string;
    toString(): string;
    inspect(): string;
}
```
```
// types/bitcore-lib/bitcore-lib-tests.ts
const message = new bitcore.Message('sign this message');
const signedMessageSig = message.sign(privateKey);
message.verify(privateKey.toAddress(), signedMessageSig);
```

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bitcore-lib ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bitcore-lib@latest/))
was missing the following properties:
1. version
1. versionGuard
1. encoding
1. util
1. errors

<details>
<summary>as well as these 5 other properties...</summary>
<p>MerkleBlock, BlockHeader, Opcode, URI, deps</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1706215e1ee06252f598d21be504d0b3fd3d7530
</p>

**Review by lautarodragan — COMMENTED** [review]
Hey @hoonsubin! 

I just quickly reviewed this PR. One thing I notice is a ton of unrelated files figure as updated, as well as many whitespace changes that aren't directly relevant.

It may be nice / help others understand the changes if only the relevant bits were included in the PR.

I'm guessing you merged master into your branch and git diff is not being super smart about it. If you could fix this (maybe by starting a branch from scratch with just your changes from a new `master`) it'd be easier to read.

I think the only actual change is the addition of `export class Message` and its test.

Not officially requesting changes since that much seems right, but please consider it.

**Comment by hoonsubin** [comment]
@lautarodragan thank you for your comment.
the irrelevant spacing on the code must be due to my use of auto formating in VS code and reading the fork due to a CI error. I'll try to make it clean. Do you think it'll be easier for everyone if I would just close this PR and open a new one from scratch? (considering all the commits that aren't related to the actual addition that I'm making).
I'll edit my description to explicitly mention the code block that I'm adding to prevent any further confusion. Thanks

**Comment by lautarodragan** [comment]
Awesome, thanks for reading my comment and considering it @hoonsubin!

> Do you think it'll be easier for everyone if I would just close this PR and open a new one from scratch?

Definitely, if you can do that I'd appreciate it :)

**Pull request closed without merging**
