### PR TITLE
[relay-runtime]: RecordSource exposes a toJSON method too

### PR DESCRIPTION
**Pull request by maraisr**
With this PR I aim to expose the `toJSON` as a method on the RecordStore.

example:

```ts
const environment = new Environment(...);

environment
    .getStore()
    .getSource()
    .toJSON()
``` 

@voxmatt @alloy @ckknight  Did one of you guys mind reviewing this one?

### CODE REVIEW

**Review by alloy — CHANGES_REQUESTED** [review]
Thanks and yeah we'd definitely appreciate such changes!

However, I don’t think this is currently correct. I believe `toJSON` will give you an JS object, for example see [here](https://github.com/facebook/relay/blob/1a94841b1d7809836ef5b71854d3ade2b5cb4dde/packages/relay-runtime/store/RelayRecordSourceObjectImpl.js#L78), whereas `JSON.stringify` returns a `string`.

**Comment by maraisr** [comment]
@alloy thank you so much for taking the time review this. Sorry about that misunderstanding.

Looking into the types more, it looks like this method returns the type `Record` (which is what I used) - do you think there is a appetite to just use the [built in type from TypeScript](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt)?

The `toJSON` method expose the type `Record<DataID, unknown>` effectively, with the exception of the `__Root` typename, which for me is `client:root`.

Or is the Record type being implemented here, because of old versions of tsc?

Sure; DataID === string, and Record is a object of string keys. So its much of a muchness. 🤷🏼‍♂️

Thank you again - looking forward to this being merged! 🕺

**Comment by alloy** [comment]
@maraisr Oh, I like that–yeah that makes sense to me 👍

**Comment by alloy** [comment]
@typescript-bot Hold your horses, bottie, the PR is still marked as “change requested”.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Requesting changes just because @typescript-bot got confused; this should unconfuse him (her? I don’t want to make assumptions). I learned the other day that if you comment with a thumbs-up emoji, it’s interpreted as an approval 😬

**Comment by andrewbranch** [comment]
BTW, the pending CI checks actually completed (and succeeded)—it seems like Azure DevOps had some transient issues updating status checks, as another PR around the same time had the same problem.

**Comment by maraisr** [comment]
Sorry friends I'm a little bit confused with I'm actually needing to still do.

cc @alloy @andrewbranch

**Comment by alloy** [comment]
@maraisr Sorry for the confusion, I gave the thumbs-up to your suggestion to drop our custom `Record` and just use TS’ version.

**Comment by alloy** [comment]
Great, thanks!

**Pull request merged**
