### PR TITLE
Formatted types/j* packages with dprint

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
> 👉 Partial implementation of https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993. If you're seeing this and are surprised it's happening, please read the discussion and give feedback! ❤️ 

Implements the dprint formatting changes on packages whose names start with `j`. We're splitting up the changes to make it a bit easier to apply & review them en masse - and, if we need later on, revert / bisect for issues. These changes generated with roughly:

```shell
git checkout dprint-onboarding -- .dprint.jsonc
time npx dprint fmt "types/j*/**/*.t*"
# Formatted 803 files.
# npx dprint fmt "types/j*/**/*.t*"  4.93s user 0.79s system 235% cpu 2.427 total
rm .dprint.jsonc
```

~CI failures are due to [DefinitelyTyped-tools > feat: remove formatting rules rules from dtslint](https://github.com/microsoft/DefinitelyTyped-tools/pull/699) not being ~merged~ included in CI yet.~ ✔️

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I think once this branch is caught up with master it'll pass - see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66707 and @sandersn work

**Comment by johnnyreilly** [comment]
I think once this branch is caught up with master it'll pass - see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66707 and @sandersn work

**Review by nweber-gh — APPROVED** [review]
for `jasmine-expect-jsx`

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jackrabbit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jackrabbit@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jackrabbit'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
## jade ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jade@latest/))
was missing the following properties:
1. selfClosing
1. doctypes
1. filters
1. utils
1. Compiler

<details>
<summary>as well as these 6 other properties...</summary>
<p>Parser, Lexer, nodes, runtime, cache, compileFileClient</p>
</details>

## jaeger-client ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jaeger-client@latest/))
was missing the following properties:
1. Configuration
1. SpanContext
1. Span
1. Tracer
1. ConstSampler

<details>
<summary>as well as these 11 other properties...</summary>
<p>ProbabilisticSampler, RateLimitingSampler, RemoteSampler, experimental, CompositeReporter, InMemoryReporter, LoggingReporter, NoopReporter, RemoteReporter, TestUtils, TChannelBridge</p>
</details>

## jake ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jake@latest/))
was missing the following properties:
1. PackageTask
1. PublishTask
1. TestTask
## javascript-state-machine ([<kbd>unpkg</kbd>](https://unpkg.com/browse/javascript-state-machine@latest/))
was missing the following properties:
1. doCallback
1. beforeAnyEvent
1. afterAnyEvent
1. leaveAnyState
1. enterAnyState

<details>
<summary>as well as these 10 other properties...</summary>
<p>changeState, beforeThisEvent, afterThisEvent, leaveThisState, enterThisState, beforeEvent, afterEvent, leaveState, enterState, buildEvent</p>
</details>

## jdataview ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jdataview@latest/))
was missing the following properties:
1. wrapBuffer
1. is
1. from
1. wrapBuffer
1. is

<details>
<summary>as well as these 1 other properties...</summary>
<p>from</p>
</details>

## jenkins ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jenkins@latest/))
was missing the following properties:
1. Jenkins
## jest-environment-puppeteer ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jest-environment-puppeteer@latest/))
was missing the following properties:
1. setup
1. teardown
## jest-when ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jest-when@latest/))
was missing the following properties:
1. WhenMock
1. WhenMock
## jexcel ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jexcel@latest/))
was missing the following properties:
1. nil
1. div0
1. value
1. ref
1. name

<details>
<summary>as well as these 364 other properties...</summary>
<p>num, na, error, data, flattenShallow, isFlat, flatten, argsToArray, numbers, cleanFloat, parseBool, parseNumber, parseNumberArray, parseMatrix, parseDate, parseDateArray, anyIsError, arrayValuesToNumbers, rest, initial, arrayEach, transpose, DATE, DATEVALUE, DAY, DAYS, DAYS360, EDATE, EOMONTH, HOUR, INTERVAL, ISOWEEKNUM, MINUTE, MONTH, NETWORKDAYS, NOW, SECOND, TIME, TIMEVALUE, TODAY, WEEKDAY, WEEKNUM, WORKDAY, YEAR, YEARFRAC, FINDFIELD, DAVERAGE, DCOUNT, DCOUNTA, DGET, DMAX, DMIN, DPRODUCT, DSTDEV, DSTDEVP, DSUM, DVAR, DVARP, MATCH, BESSELI, BESSELJ, BESSELK, BESSELY, BIN2DEC, BIN2HEX, BIN2OCT, BITAND, BITLSHIFT, BITOR, BITRSHIFT, BITXOR, COMPLEX, CONVERT, DEC2BIN, DEC2HEX, DEC2OCT, DELTA, ERF, ERFC, GESTEP, HEX2BIN, HEX2DEC, HEX2OCT, IMABS, IMAGINARY, IMARGUMENT, IMCONJUGATE, IMCOS, IMCOSH, IMCOT, IMDIV, IMEXP, IMLN, IMLOG10, IMLOG2, IMPOWER, IMPRODUCT, IMREAL, IMSEC, IMSECH, IMSIN, IMSINH, IMSQRT, IMCSC, IMCSCH, IMSUB, IMSUM, IMTAN, OCT2BIN, OCT2DEC, OCT2HEX, ACCRINT, ACCRINTM, AMORDEGRC, AMORLINC, COUPDAYBS, COUPDAYS, COUPDAYSNC, COUPNCD, COUPNUM, COUPPCD, CUMIPMT, CUMPRINC, DB, DDB, DISC, DOLLARDE, DOLLARFR, DURATION, EFFECT, FV, FVSCHEDULE, INTRATE, IPMT, IRR, ISPMT, MDURATION, MIRR, NOMINAL, NPER, NPV, ODDFPRICE, ODDFYIELD, ODDLPRICE, ODDLYIELD, PDURATION, PMT, PPMT, PRICE, PRICEDISC, PRICEMAT, PV, RATE, RECEIVED, RRI, SLN, SYD, TBILLEQ, TBILLPRICE, TBILLYIELD, VDB, XIRR, XNPV, YIELD, YIELDDISC, YIELDMAT, CELL, ERROR, INFO, ISBLANK, ISBINARY, ISERR, ISERROR, ISEVEN, ISFORMULA, ISLOGICAL, ISNA, ISNONTEXT, ISNUMBER, ISODD, ISREF, ISTEXT, N, NA, SHEET, SHEETS, TYPE, AND, CHOOSE, FALSE, IF, IFERROR, IFNA, NOT, OR, TRUE, XOR, SWITCH, ABS, ACOS, ACOSH, ACOT, ACOTH, AGGREGATE, ARABIC, ASIN, ASINH, ATAN, ATAN2, ATANH, BASE, CEILING, COMBIN, COMBINA, COS, COSH, COT, COTH, CSC, CSCH, DECIMAL, DEGREES, EVEN, EXP, FACT, FACTDOUBLE, FLOOR, GCD, INT, LCM, LN, LOG, LOG10, MDETERM, MINVERSE, MMULT, MOD, MROUND, MULTINOMIAL, MUNIT, ODD, PI, POWER, PRODUCT, QUOTIENT, RADIANS, RAND, RANDBETWEEN, ROMAN, ROUND, ROUNDDOWN, ROUNDUP, SEC, SECH, SERIESSUM, SIGN, SIN, SINH, SQRT, SQRTPI, SUBTOTAL, ADD, MINUS, DIVIDE, MULTIPLY, GTE, LT, LTE, EQ, NE, POW, SUM, SUMIF, SUMIFS, SUMPRODUCT, SUMSQ, SUMX2MY2, SUMX2PY2, SUMXMY2, TAN, TANH, TRUNC, UNIQUE, FLATTEN, ARGS2ARRAY, REFERENCE, JOIN, NUMBERS, NUMERAL, ASC, BAHTTEXT, CHAR, CLEAN, CODE, CONCATENATE, DBCS, DOLLAR, EXACT, FIND, FIXED, HTML2TEXT, LEFT, LEN, LOWER, MID, NUMBERVALUE, PRONETIC, PROPER, REGEXEXTRACT, REGEXMATCH, REGEXREPLACE, REPLACE, REPT, RIGHT, SEARCH, SPLIT, SUBSTITUTE, T, TEXT, TRIM, UNICHAR, UNICODE, UPPER, VALUE, AVEDEV, AVERAGE, AVERAGEA, AVERAGEIF, AVERAGEIFS, COUNT, COUNTA, COUNTIN, COUNTBLANK, COUNTIF, COUNTIFS, COUNTUNIQUE, FISHER, FISHERINV, FREQUENCY, LARGE, MAX, MAXA, MIN, MINA, MODE, PERCENTILE, PERCENTRANK, PERMUT, PERMUTATIONA, PHI, PROB, QUARTILE, RANK, RSQ, SMALL, STANDARDIZE, STDEV, STDEVA, STDEVPA, VAR, VARA, VARPA, WEIBULL, Z</p>
</details>

## jexl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jexl@latest/))
was missing the following properties:
1. expr
## jmespath ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jmespath@latest/))
was missing the following properties:
1. tokenize
1. compile
1. strictDeepEqual
## johnny-five ([<kbd>unpkg</kbd>](https://unpkg.com/browse/johnny-five@latest/))
was missing the following properties:
1. Color
1. Expander
1. GPS
1. SIP
1. Keypad

<details>
<summary>as well as these 13 other properties...</summary>
<p>LedControl, Light, Repl, Multi, Luxmeter, Magnetometer, Buttons, Leds, Pins, Sensors, Servos, Switches, Touchpad</p>
</details>

## jquery-deferred ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jquery-deferred@latest/))
was missing the following properties:
1. type
1. isArray
1. isFunction
1. isPlainObject
1. each

<details>
<summary>as well as these 3 other properties...</summary>
<p>extend, noop, Callbacks</p>
</details>

## jquery-formatdatetime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jquery-formatdatetime@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jquery-formatdatetime'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
## js-md5 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-md5@latest/))
was missing the following properties:
1. blocks
1. buffer8
1. h0
1. h1
1. h2

<details>
<summary>as well as these 11 other properties...</summary>
<p>h3, start, bytes, hBytes, finalized, hashed, first, lastByteIndex, finalize, hash, toString</p>
</details>

## js-nacl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-nacl@latest/))
was missing the following properties:
1. crypto_auth_BYTES
1. crypto_auth_KEYBYTES
1. crypto_box_BEFORENMBYTES
1. crypto_box_BOXZEROBYTES
1. crypto_box_NONCEBYTES

<details>
<summary>as well as these 59 other properties...</summary>
<p>crypto_box_PUBLICKEYBYTES, crypto_box_SECRETKEYBYTES, crypto_box_ZEROBYTES, crypto_hash_BYTES, crypto_hash_sha256_BYTES, crypto_onetimeauth_BYTES, crypto_onetimeauth_KEYBYTES, crypto_secretbox_BOXZEROBYTES, crypto_secretbox_KEYBYTES, crypto_secretbox_NONCEBYTES, crypto_secretbox_ZEROBYTES, crypto_sign_BYTES, crypto_sign_PUBLICKEYBYTES, crypto_sign_SECRETKEYBYTES, crypto_stream_KEYBYTES, crypto_stream_NONCEBYTES, crypto_scalarmult_SCALARBYTES, crypto_scalarmult_BYTES, encode_utf8, encode_latin1, decode_utf8, decode_latin1, to_hex, from_hex, random_bytes, crypto_box_keypair, crypto_box_random_nonce, crypto_box, crypto_box_open, crypto_box_precompute, crypto_box_precomputed, crypto_box_open_precomputed, crypto_stream_random_nonce, crypto_stream, crypto_stream_xor, crypto_onetimeauth, crypto_onetimeauth_verify, crypto_auth, crypto_auth_verify, crypto_secretbox_random_nonce, crypto_secretbox, crypto_secretbox_open, crypto_box_seal, crypto_box_seal_open, crypto_sign_keypair, crypto_sign, crypto_sign_detached, crypto_sign_open, crypto_sign_verify_detached, crypto_hash, crypto_hash_sha256, crypto_hash_string, crypto_sign_seed_keypair, crypto_box_seed_keypair, crypto_box_keypair_from_raw_sk, crypto_sign_keypair_from_seed, crypto_box_keypair_from_seed, crypto_scalarmult, crypto_scalarmult_base</p>
</details>

## js-quantities ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-quantities@latest/))
was missing the following properties:
1. version
## js-to-java ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-to-java@latest/))
was missing the following properties:
1. simpleTypeMap
1. enum
## js-yaml ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-yaml@latest/))
was missing the following properties:
1. safeLoad
1. safeLoadAll
1. safeDump
## jsen ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsen@latest/))
was missing the following properties:
1. browser
1. ucs2length
1. SchemaResolver
1. resolve
## jsforce ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsforce@latest/))
was missing the following properties:
1. addListener
1. on
1. once
1. removeListener
1. off

<details>
<summary>as well as these 12 other properties...</summary>
<p>removeAllListeners, setMaxListeners, getMaxListeners, listeners, rawListeners, emit, listenerCount, prependListener, prependOnceListener, eventNames, VERSION, require</p>
</details>

## jsftp ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsftp@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jsftp'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
## jsmidgen ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsmidgen@latest/))
was missing the following properties:
1. Midi
## json-diff ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json-diff@latest/))
was missing the following properties:
1. colorize
1. colorizeToCallback
## json-patch ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json-patch@latest/))
was missing the following properties:
1. version
1. JSONPointer
1. JSONPatch
## json-query ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json-query@latest/))
was missing the following properties:
1. lastParent
## json-schema-md-doc ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json-schema-md-doc@latest/))
was missing the following properties:
1. JSONSchemaMarkdown
## json3 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json3@latest/))
was missing the following properties:
1. runInContext
## json_ml ([<kbd>unpkg</kbd>](https://unpkg.com/browse/json_ml@latest/))
was missing the following properties:
1. stringifyListMode
1. stringifyElement
1. parseElementList
1. parseElement
1. JsonML
## jsonic ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonic@latest/))
was missing the following properties:
1. noConflict
1. jsonic
## jsonld ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonld@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jsonld'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
## jsonlint ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonlint@latest/))
was missing the following properties:
1. parser
1. main
## jsonpath ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonpath@latest/))
was missing the following properties:
1. initialize
1. parser
1. handlers
## jsonrpc-serializer ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonrpc-serializer@latest/))
was missing the following properties:
1. errorHandler
## jsontoxml ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsontoxml@latest/))
was missing the following properties:
1. json_to_xml
1. obj_to_xml
## jspath ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jspath@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jspath'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. version
1. params
1. compile
## jspreadsheet-ce ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jspreadsheet-ce@latest/))
was missing the following properties:
1. nil
1. div0
1. value
1. ref
1. name

<details>
<summary>as well as these 366 other properties...</summary>
<p>num, na, error, data, flattenShallow, isFlat, flatten, argsToArray, numbers, cleanFloat, parseBool, parseNumber, parseNumberArray, parseMatrix, parseDate, parseDateArray, anyIsError, arrayValuesToNumbers, rest, initial, arrayEach, transpose, DATE, DATEVALUE, DAY, DAYS, DAYS360, EDATE, EOMONTH, HOUR, INTERVAL, ISOWEEKNUM, MINUTE, MONTH, NETWORKDAYS, NOW, SECOND, TIME, TIMEVALUE, TODAY, WEEKDAY, WEEKNUM, WORKDAY, YEAR, YEARFRAC, FINDFIELD, DAVERAGE, DCOUNT, DCOUNTA, DGET, DMAX, DMIN, DPRODUCT, DSTDEV, DSTDEVP, DSUM, DVAR, DVARP, MATCH, BESSELI, BESSELJ, BESSELK, BESSELY, BIN2DEC, BIN2HEX, BIN2OCT, BITAND, BITLSHIFT, BITOR, BITRSHIFT, BITXOR, COMPLEX, CONVERT, DEC2BIN, DEC2HEX, DEC2OCT, DELTA, ERF, ERFC, GESTEP, HEX2BIN, HEX2DEC, HEX2OCT, IMABS, IMAGINARY, IMARGUMENT, IMCONJUGATE, IMCOS, IMCOSH, IMCOT, IMDIV, IMEXP, IMLN, IMLOG10, IMLOG2, IMPOWER, IMPRODUCT, IMREAL, IMSEC, IMSECH, IMSIN, IMSINH, IMSQRT, IMCSC, IMCSCH, IMSUB, IMSUM, IMTAN, OCT2BIN, OCT2DEC, OCT2HEX, ACCRINT, ACCRINTM, AMORDEGRC, AMORLINC, COUPDAYBS, COUPDAYS, COUPDAYSNC, COUPNCD, COUPNUM, COUPPCD, CUMIPMT, CUMPRINC, DB, DDB, DISC, DOLLARDE, DOLLARFR, DURATION, EFFECT, FV, FVSCHEDULE, INTRATE, IPMT, IRR, ISPMT, MDURATION, MIRR, NOMINAL, NPER, NPV, ODDFPRICE, ODDFYIELD, ODDLPRICE, ODDLYIELD, PDURATION, PMT, PPMT, PRICE, PRICEDISC, PRICEMAT, PV, RATE, RECEIVED, RRI, SLN, SYD, TBILLEQ, TBILLPRICE, TBILLYIELD, VDB, XIRR, XNPV, YIELD, YIELDDISC, YIELDMAT, CELL, ERROR, INFO, ISBLANK, ISBINARY, ISERR, ISERROR, ISEVEN, ISFORMULA, ISLOGICAL, ISNA, ISNONTEXT, ISNUMBER, ISODD, ISREF, ISTEXT, N, NA, SHEET, SHEETS, TYPE, AND, CHOOSE, FALSE, IF, IFERROR, IFNA, NOT, OR, TRUE, XOR, SWITCH, ABS, ACOS, ACOSH, ACOT, ACOTH, AGGREGATE, ARABIC, ASIN, ASINH, ATAN, ATAN2, ATANH, BASE, CEILING, COMBIN, COMBINA, COS, COSH, COT, COTH, CSC, CSCH, DECIMAL, DEGREES, EVEN, EXP, FACT, FACTDOUBLE, FLOOR, GCD, INT, LCM, LN, LOG, LOG10, MDETERM, MINVERSE, MMULT, MOD, MROUND, MULTINOMIAL, MUNIT, ODD, PI, POWER, PRODUCT, QUOTIENT, RADIANS, RAND, RANDBETWEEN, ROMAN, ROUND, ROUNDDOWN, ROUNDUP, SEC, SECH, SERIESSUM, SIGN, SIN, SINH, SQRT, SQRTPI, SUBTOTAL, ADD, MINUS, DIVIDE, MULTIPLY, GTE, LT, LTE, EQ, NE, POW, SUM, SUMIF, SUMIFS, SUMPRODUCT, SUMSQ, SUMX2MY2, SUMX2PY2, SUMXMY2, TAN, TANH, TRUNC, UNIQUE, FLATTEN, ARGS2ARRAY, REFERENCE, JOIN, NUMBERS, NUMERAL, ASC, BAHTTEXT, CHAR, CLEAN, CODE, CONCATENATE, DBCS, DOLLAR, EXACT, FIND, FIXED, HTML2TEXT, LEFT, LEN, LOWER, MID, NUMBERVALUE, PRONETIC, PROPER, REGEXEXTRACT, REGEXMATCH, REGEXREPLACE, REPLACE, REPT, RIGHT, SEARCH, SPLIT, SUBSTITUTE, T, TEXT, TRIM, UNICHAR, UNICODE, UPPER, VALUE, AVEDEV, AVERAGE, AVERAGEA, AVERAGEIF, AVERAGEIFS, COUNT, COUNTA, COUNTIN, COUNTBLANK, COUNTIF, COUNTIFS, COUNTUNIQUE, FISHER, FISHERINV, FREQUENCY, LARGE, MAX, MAXA, MIN, MINA, MODE, PERCENTILE, PERCENTRANK, PERMUT, PERMUTATIONA, PHI, PROB, QUARTILE, RANK, RSQ, SMALL, STANDARDIZE, STDEV, STDEVA, STDEVPA, VAR, VARA, VARPA, WEIBULL, Z, PROGRESS, RATING</p>
</details>

## jsreport-core ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsreport-core@latest/))
was missing the following properties:
1. Reporter
1. tests
## jsreport ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsreport@latest/))
was missing the following properties:
1. Reporter
1. renderDefaults
1. render
1. extendDefaults
1. reporter

<details>
<summary>as well as these 61 other properties...</summary>
<p>core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core, Reporter, renderDefaults, render, extendDefaults, reporter, core</p>
</details>

## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 24 other properties...</summary>
<p>MessageDigest, Mac, Cipher, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, ucs2hextoutf8, oidtohex, hextooid, strpad, bitstrtoint, inttobitstr, bitstrtobinstr, binstrtobitstr, isBase64URLDot, namearraytobinstr, extendClass, crypto, asn1, jws, lang</p>
</details>

## jstimezonedetect ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jstimezonedetect@latest/))
was missing the following properties:
1. olson
## jsts ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsts@latest/))
was missing the following properties:
1. abstractFunc
1. error
1. index
1. geomgraph
1. noding

<details>
<summary>as well as these 1 other properties...</summary>
<p>triangulate</p>
</details>

## jwt-simple ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jwt-simple@latest/))
was missing the following properties:
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e44775dfeff1ff096e27523d8278b785ef9bdee2
</p>

**Review by johnnyreilly — APPROVED** [review]

**Pull request merged**
