### PR TITLE
fix(mysql): error when exactOptionalPropertyTypes is enabled

### PR DESCRIPTION
**Pull request by michal-kocarek**
TypeScript 4.4 introduces the option `exactOptionalPropertyTypes`.
When enabled, this makes `foo?: footype` distinct of `foo?: footype | undefined`.

Same error, that was happening for `@types/node` is happening in `@types/mysql`. Both packages extend native `Error`, and the `stack` property was extended from `stack?: string` to `stack?: string | undefined`. That collides with parent property definition and produces an error.

Solution borrowed from same issue in node types:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55425

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55425

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mysql ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mysql@latest/))
was missing the following properties:
1. createQuery
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 70499902f6b4262075bf8163004e6ee8404bfda5
</p>

**Comment by michal-kocarek** [comment]
Hello, @wjohnsto @kpping @jdmunro @sedenardi - can I very, very, very kindly ask you to review this PR? It is blocking me in some development... Or is there something more I could do to improve it? Thank you a lot in advance...

**Review by wjohnsto — APPROVED** [review]
👍🏻 LGTM!

**Comment by michal-kocarek** [comment]
Ready to merge

**Pull request merged**
