### PR TITLE
Removed attribute clientMetadata for unprovided triggers

### PR DESCRIPTION
**Pull request by lmanerich**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lmanerich** [comment]
Fix for #65605

**Review by coderbyheart — APPROVED** [review]

**Comment by darbio** [comment]
@lmanerich any chance you could add some tests for this?

**Comment by bhb603** [comment]
@lmanerich @weswigham  @coderbyheart 
I believe the AWS Documentation referenced in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65605 is incomplete or misleading...

We have been using `clientMetadata` in "Create auth challenge" and "Verify auth challenge" Lambdas, and I can confirm from our logs that `clientMetadata` is present.

According to these docs, it IS present on those events in certain circumstances (ie when "AdminRespondToAuthChallenge" is used)
- https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html
- https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html

I believe the other event triggers are similar - tho I haven't checked.

But I think we should add back the `clientMetadata` key as an optional Stringmap

**Comment by darbio** [comment]
It is not unusual for the documentation to be incomplete or missing. 

The best way to combat this kind of issue is proper unit testing, which will help us ensure that these types are resilient and accurate.

All PRs _should_ be accompanied by a unit test (I know... I'm sitting in my ivory tower). 

@bhb603 do you have any code samples that we can use in a unit test?

**Comment by bhb603** [comment]
@darbio - yes, in the pattern of tests in this repo, we would just add an assertion about `request.clientMetadata` for all these trigger events, e.g.:

```diff
diff --git a/types/aws-lambda/test/cognito-tests.ts b/types/aws-lambda/test/cognito-tests.ts
index b44c129999..4c650eb494 100644
--- a/types/aws-lambda/test/cognito-tests.ts
+++ b/types/aws-lambda/test/cognito-tests.ts
@@ -118,6 +118,8 @@ const defineAuthChallenge: DefineAuthChallengeTriggerHandler = async (event, _,
 
     // @ts-expect-error
     nullOrUndefined = request.userAttributes;
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const createAuthChallenge: CreateAuthChallengeTriggerHandler = async (event, _, callback) => {
@@ -140,6 +142,8 @@ const createAuthChallenge: CreateAuthChallengeTriggerHandler = async (event, _,
 
     triggerSource === 'CreateAuthChallenge_Authentication';
 
+    objectOrUndefined = request.clientMetadata;
+
     // @ts-expect-error
     nullOrUndefined = request.userAttributes;
 };
@@ -157,6 +161,8 @@ const validateAuthChallengeResponse: VerifyAuthChallengeResponseTriggerHandler =
     bool = response.answerCorrect;
 
     triggerSource === 'VerifyAuthChallengeResponse_Authentication';
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const preAuthentication: PreAuthenticationTriggerHandler = async (event, _, callback) => {
@@ -181,6 +187,8 @@ const postAuthentication: PostAuthenticationTriggerHandler = async (event, _, ca
     objectOrUndefined = response;
 
     triggerSource === 'PostAuthentication_Authentication';
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const preTokenGeneration: PreTokenGenerationTriggerHandler = async (event, _, callback) => {
@@ -207,6 +215,8 @@ const preTokenGeneration: PreTokenGenerationTriggerHandler = async (event, _, ca
     triggerSource === 'TokenGeneration_HostedAuth';
     triggerSource === 'TokenGeneration_NewPasswordChallenge';
     triggerSource === 'TokenGeneration_RefreshTokens';
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const userMigration: UserMigrationTriggerHandler = async (event, _, callback) => {
@@ -234,6 +244,8 @@ const userMigration: UserMigrationTriggerHandler = async (event, _, callback) =>
 
     triggerSource === 'UserMigration_Authentication';
     triggerSource === 'UserMigration_ForgotPassword';
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const customMessage: CustomMessageTriggerHandler = async (event, _, callback) => {
@@ -256,6 +268,8 @@ const customMessage: CustomMessageTriggerHandler = async (event, _, callback) =>
     triggerSource === 'CustomMessage_SignUp';
     triggerSource === 'CustomMessage_UpdateUserAttribute';
     triggerSource === 'CustomMessage_VerifyUserAttribute';
+
+    objectOrUndefined = request.clientMetadata;
 };
 
 const customEmailSender: CustomEmailSenderTriggerHandler = async (event, _, callback) => {
```

**Comment by darbio** [comment]
A discussion for another place, but as the type owners, maybe we should not be accepting PRs that don't have adequate tests in place. 

We have fallen into the trap of just getting it done (TM).

**Comment by simonbuchan** [comment]
It's an odd case, as a maintainer had requested changes, but not with the bot-aware official red brand of shame, and another had accepted them...

The root cause is likely the lack of tests showing this to be a breaking change which would likely have forced the issue, which isn't really any *specific* person's fault.

There's a few things like this such that it would be nice if we could add some things to the PR template for this package, like "AWS documentation is often very incomplete, please verify against the real endpoint" and "sorry our tests suck " 😅 - I don't know if that's possible with GitHub though.

**Comment by bhb603** [comment]
I've created a PR to resolve the issue and add tests: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65768

**Comment by darbio** [comment]
> The root cause is likely the lack of tests showing this to be a breaking change which would likely have forced the issue

How do we feel about not accepting changes that don't have unit tests?

I'm not saying that the unit tests have to be exclusive, but it would help get the coverage up of any new code is accompanied with unit tests. 

This would need to be adopted across the board by all maintainers when accepting changes.

No tests, no merge. 

> There's a few things like this such that it would be nice if we could add some things to the PR template for this package, like "AWS documentation is often very incomplete, please verify against the real endpoint" and "sorry our tests suck " 😅 - I don't know if that's possible with GitHub though.

Let me look into this. I'm sure it's possible, but might be a definitely typed thing.

**Pull request merged**
