### PR TITLE
JointJS/Rappid Added findModelsFromPoint definition to Graph, Handle interface and SelectionView class definitions.

### PR DESCRIPTION
**Pull request by DenEwout**
Hi,

I'm working with JointJS/Rappid and I'm adding whatever I'm missing. Handle and SelectionView are from Rappid. If you prefer me to use a separate file for Rappid, please let me know (but as you can see they are within the same module).

Kind Regards,

DenEwout.

### CODE REVIEW

**Comment by vvakame** [comment]
@DenEwout thanks mate!

**Comment by DenEwout** [comment]
No problem, it's ok to keep the jointjs and rappid API's in one file then?

**Comment by vvakame** [comment]
@DenEwout I don't know about jointjs...
I think It should be separate if it is install separately.

**Comment by DenEwout** [comment]
It's a separate install, Rappid is a commercial product built on top of JointJS (by the creator of JointJS). 

Is there a certain procedure to go through to add an extra library to DefinitelyTyped? (I believe only one tsd per library-folder is allowed, correct?). There are other libraries which are called "rappid" so perhaps jointjs-rappid would be a good name for it?

**Comment by vvakame** [comment]
We can choose angularjs style or createjs style.
https://github.com/borisyankov/DefinitelyTyped/blob/master/createjs/createjs.d.ts
https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs
I think createjs is more better for tsd.

**Comment by DenEwout** [comment]
Alright. I'm currently busy with something else, but you can expect some more additions to come in during upcoming week. Thanks!

**Pull request merged**
