### PR TITLE
Fix yeoman environment

### PR DESCRIPTION
**Pull request by neurolag**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/yeoman/environment/tree/de51971b18a408a9dfc9e50ec9c7edd0ec86803b>
- [x] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## yeoman-environment ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yeoman-environment@latest/))
was missing the following properties:
1. UNKNOWN_NAMESPACE
1. UNKNOWN_RESOLVED
1. queues
1. lookups
1. repository
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against edde8e0d36c3b8cf256eb2f6422afd1acb23a9a6
</p>

**Comment by peterblazejewicz** [comment]
sorry for late review. Should the version be increased?

**Comment by manuth** [comment]
> sorry for late review. Should the version be increased?

Thanks for taking care 😄 
No, I didn't touch the version on purpose - I managed it to break the markdown of my issue ending up with the link not being displayed. I fixed it now.

I took all the API specifications from the v3.3.0 docs (which are linked in the issue now).

**Review by peterblazejewicz — APPROVED** [review]
Thanks!

**Comment by manuth** [comment]
Ready to merge

**Pull request merged**
