### PR TITLE
Add Animated.Value to react-native Transforms

### PR DESCRIPTION
**Pull request by stantoncbradley**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12202
- [x] Increase the version number in the header if appropriate. (not necessary, no breaking changes)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (changes aren't substantial)

### CODE REVIEW

**Comment by timwangdev** [comment]
Hi, could you add some tests for this change?

**Review by timwangdev — CHANGES_REQUESTED** [review]
See comment

**Comment by huhuanming** [comment]
I think so.
You need test for changes.

**Comment by stantoncbradley** [comment]
These changes are really straightforward, and I don't see any tests around the current code here. If we really need to add tests for this, can someone point me to an example of what these tests should look like?

**Comment by iRoachie** [comment]
A test for this repo is just a block of code that represents real-world usage. In your example since you are adding `Animated.Value` to the transform; a real-world example would be a component(View) adding a style prop that uses an animated value as the value.

**Comment by stantoncbradley** [comment]
Ok finally figured out how the typing works in Animated, it's a little tricky. So `TransformsStyle` only applies to `Image`, `View`, and `Text`, but (a little counterintuitively) not to `Animated.Image`, `Animated.View`, or `Animated.Text` because `Animated` redeclares these as type `any`. I'm a little surprised the `Animated` components are so loosely typed, and also that `TransformsStyles` only applies to the non-animated components. In any case, this PR no longer makes sense in light of how the lib handles these animated types.  Thanks!

**Pull request closed without merging**
