### PR TITLE
Bootstrap v3: Update type definition

### PR DESCRIPTION
**Pull request by denisname**
Update type definition:
* Remove all linting exceptions but `no-single-declare-module`.
* Activate `strictNullChecks`.
* `ModalOptions#backdrop` use `"static"` instead of `string`.
* `TooltipOptions#container`, use `false` instead of `boolean`.
* `TooltipOptions#delay`, use an interface instead of `Object`.
* `TooltipOptions#placement`, use interface instead of `Object` and `Function`.
* `TooltipOptions#title`, use callable signatures instead of `Function`.
* `TooltipOptions#trigger`, use union type instead of `string`.
* `TooltipOptions#viewport`, use an interface instead of `Object`.
* `PopoverOptions` inherits from `TooltipOptions`.
* `PopoverOptions#content` don't use `any`.
* `CollapseOptions#parent` is `string | false`.
* `CarouselOptions#interval` is `number | false`.
* `CarouselOptions#pause` is `"hover" | null`.
* `TypeaheadOptions` is not part of bootstrap, removed!
* `AffixOptions#offset` use an interface instead of `Object`.
* `AffixOptions#target` don't use `any`.
* In JQuery methods, use union string for actions.
* Add lot of tests.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://getbootstrap.com/docs/3.3/javascript/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by michaelaird** [comment]
These are breaking changes. Why was this released as patch version?

**Comment by denisname** [comment]
Please specify what problems you encounter.
Type definition versions follows library versions. There is no way to release it otherwise.

**Comment by michaelaird** [comment]
Yes. I've been informed that type definitions don't follow semver but are locked to the library versions. 

Introducing Placement broke our builds because we had ~ in our package.json. I've locked down the versions so this doesn't happen in the future.

**Comment by ZaLiTHkA** [comment]
Please excuse the potentially stupid question. I'm relatively new to TS and there are many differing opinions online, seemingly dependent on the version system used by different libraries. I didn't find a clear answer in the `DefinitelyTyped` readme, so...

Just for clarification on *this* package specifically: If I'm working on a project that's stuck on Bootstrap 3, should I keep `@types/bootstrap` in the `^3` range, or could I upgrade it to `^4`?

**Comment by denisname** [comment]
@ZaLiTHkA `@types` versions take the form Major.Minor.Path but are not [simver](http://simver.org/). Use same Major and Minor in `@types/bootstrap` than in `bootstrap`. Major and Minor in DefinitelyTyped follows the library version. The Patch number is specific to `@types`. For example, if you use Bootstrap 3.3.7, install latests @types/bootstrap 3.3.x, if you use Bootstrap 4.1.0, install latests @types/bootstrap 4.1.x.

**Comment by ZaLiTHkA** [comment]
Cool beans. That's what I suspected, thanks for the confirmation. :)

**Pull request merged**
