### PR TITLE
Update for prosemirror-model 1.7.0

### PR DESCRIPTION
**Pull request by RatoX**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ProseMirror/rfcs/blob/master/text/0008-block-marks-wrapping.md
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by timjb — CHANGES_REQUESTED** [review]
In version 1.6.0, a property named `toDebugString` was added to `NodeSpec`. Could you add a type declaration for this property too, please?

**Review by timjb — APPROVED** [review]
LGTM

**Comment by timjb** [comment]
@RatoX Thanks!

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
