### PR TITLE
Add pym.js type definitions

### PR DESCRIPTION
**Pull request by igowerf**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by gabritto — CHANGES_REQUESTED** [review]
The definition itself looks correct, however you should not change the default `tsconfig.json` and `tslint.json` unless you really have to. I don't think it's the case here, so if you can, please change the way you're declaring the module (e.g. not using `declare module 'pym.js'` but instead doing something like `export class Child ... `), and use the default configs, we'd really appreciate it. Thanks!

**Comment by igowerf** [comment]
@gabritto , thanks for reviewing!

The pym.js factory function returns an object with the pym classes and functions attached to it.  I believe it's intended to provide a namespace when attached to the `window` global.  I felt like the typing should reflect this pattern to avoid any confusion with the official pym.js documentation.

Should I declare a `namespace` instead of a `module` in this case?  I looked at a few other modules and I've seen it implemented both ways, and to be totally honest, I don't totally understand the differences yet.

Without type support, users can currently import pym in the following ways in JavaScript:
```
import pym from 'pym.js';

const child = new pym.Child();
```
or alternatively
```
import { Child } from 'pym.js';

const child = new Child();
```

If I export my class declarations without wrapping them in the module, I get an error stating that 'pym.js' doesn't have a default export, so the first example no longer works.  Do you have a recommendation for preserving this usage?

**Comment by gabritto** [comment]
Ok, if I understand correctly what you're trying to do, you want the pym module to be used both as a global in a browser context, and in an e.g. node context via an import.
I think the way to do this would be to:
1. get rid of the `declare module ... ` surrounding the declarations.
2. export the declarations (e.g. `export class Child ...`, `export function autoInit() ...`).
3. add an `export as namespace pym` (as seen [here](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#optional-global-usage), and on DT there's a similar thing done in [react-dom-server](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7e3fee45d6cc2168afacbee6df893a9a8691d652/types/react-dom/server.d.ts#L119) and [lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7e3fee45d6cc2168afacbee6df893a9a8691d652/types/lodash/index.d.ts#L27)).

This covers both trying to access the module in a browser environment via a global (you'd just use it like `pym.autoInit()`), and importing the module (e.g. `import { autoInit } from "pym.js"`).

About having a default import, I'm not sure that should really work. Looking at the package source (https://unpkg.com/browse/pym.js@1.3.2/dist/pym.v1.js), there doesn't seem to be a default export. Can you point me to the documentation that says you can use it via a default import (`import pym from "pym.js"`)?

**Comment by igowerf** [comment]
Thanks for clarifying.  I've updated my pull request.

You're right that there is no default export; I was mistaken, because `import pym from 'pym.js'` still works correctly in a React project that I set up locally to test my declarations.  Maybe there's something in the create-react-app tooling that automatically makes it work?

**Review by gabritto — APPROVED** [review]
thanks ✨

**Comment by igowerf** [comment]
Ready to merge

**Comment by igowerf** [comment]
I just wanted to note that `import pym from 'pym.js'` works with my create-react-app application, because the included `tsconfig.json` has `allowSyntheticDefaultImports: true`.  
https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

This was a pretty big source of confusion for me when I was trying to test the type definitions locally.

**Pull request merged**
