### PR TITLE
[markItUp] Support extra settings

### PR DESCRIPTION
**Pull request by stonio**
If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/markitup/1.x/blob/master/markitup/jquery.markitup.js
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
*markitup/markitup.d.ts*

to author (@drillbits). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by yuit** [comment]
@stonio  Thank you for the PR. It seems that this PR contains more than just your change. I think you will to create new PR that is branch off from `types-2.0`. and cherry-pick just your change.

**Comment by paulvanbrenk** [comment]
Redid this PR without the merge issue: #13027

**Pull request closed without merging**
