### PR TITLE
[Bluebird] cleanup lint errors

### PR DESCRIPTION
**Pull request by segayuu**
Regarding what I cared about while fixing it ...
- Simply combining `Promise.props()` will generate an incompatible generic type.
- When trying to apply `max-line-length`, it is expected that the doc comment will change drastically.

I will be very glad when advice comes!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by segayuu** [comment]
There are two causes of CI Test Error.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request/index.d.ts#L267
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request-promise/index.d.ts#L13
If you do not send an issue to either of these two libraries, it will remain error. Oh...

**Comment by lhecker** [comment]
@segayuu Thanks for all the continued great work!

I just realized that there seems to be a generally accepted solution of simply having

```json
{ "extends": "dtslint/dt.json" }
```

as the `tslint.json` file though. For instance here's [`d3`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3/tslint.json).

Would it make sense to update this PR with that?
(We might also might want to switch from `Array<T>` to `ArrayLike<T>` btw.)

**Comment by segayuu** [comment]
Thanks @lhecker !
The goal of this PR is there.
However, if you want to do so, you need to destroy the current `bluebird-test.json` structure or invalidate nearly the entire area in the file with `/* tslint: disable: void-return */` It will come out. Furthermore, if you activate `strictNullCheck` it will conflict with the structure of the test.
I am doing PR by choosing to invalidate by inline comment, choosing to rebuild the test, or doing a place that can be done before the decision is made.

**Comment by raseel-mohamed** [comment]
@segayuu, Typescript newbie here so please forgive my ignorance. My package.json pulls in @types/request-promise that now uses this commit. When  running my test (using protractor-typescript) I get the error the error:
```
node_modules/@types/request-promise/index.d.ts(13,15): error TS2320: Interface 'RequestPromise' cannot simultaneously extend types 'Request' and 'Bluebird<any>'.
  Named property 'toJSON' of types 'Request' and 'Bluebird<any>' are not identical.
```
Stemming from this line:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request-promise/index.d.ts#L13.
Should I open the issue on request-promise or here? or is there another change that I need to implement on my side? If you wish I can also take this discussion to a different forum.  
Thanks

**Comment by lhecker** [comment]
@raseel-mohamed No this is the right place to complain:
This PR changed the definition of the `toJSON()` method for the `bluebird` as well as the `request` typings.
But sadly I fail to see why this PR should’ve broken the `request-promise` as the `toJSON()` Definition is the same in both typings (it returns `object`) and should be identical and thus compatible.
Can you check if the 2 `@types/{bluebird,request}/index.d.ts` files you have in your `node_modules` folder match those you find in the master-branch of this project?
You basically have to use a compatible versions for both typings (bluebird and request) where both *either* have `toJSON(): Object` *or* `toJSON(): object`.

**Comment by raseel-mohamed** [comment]
@lhecker, @segayuu sorry for not getting back sooner. It turns out that I had to update all my packages and once that was done, the issue was resolved. I was able to identify the issue after following your instructions. Thanks for all your help

**Pull request merged**
