### PR TITLE
Isomorphic fetch update

### PR DESCRIPTION
**Pull request by toddlucas**
This is an update to add new properties suggested by @zengfenfei in a related PR. It also includes changes suggested by @SaschaNaz, incorporating some improvements made in the related whatwg-fetch type definitions.

We may eventually merge these. However, there are two considerations. First, isomorphic-fetch must also represent the node-fetch interface--ideally, the common subset of whatwg-fetch and node-fetch. Second, this definitions file is structured differently, and we should maintain compatibility for anyone with established code. In particular, it distinguishes between interfaces and classes.

### CODE REVIEW

**Comment by SaschaNaz** [comment]
I don't understand why there is `IHeader` interface. This is not C#, classes are already interfaces, so no need to duplicate them. What do you think?

**Comment by zengfenfei** [comment]
I create a version that references the definitions of `whatwg-fetch`: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e9cfa1d1ad6452822ceb44c24ba00a8e0974ab49, so that we don't have to bother creating a duplicate definition for `fetch`.

But I fail to create the reference without modifying `whatwg-fetch` definitions. So I made a slight change to `whatwg-fetch` definitions(No interface change). It works in my `tsc` and `vscode`.

@toddlucas @SaschaNaz If it's ok I'll submit a PR with that version.

**Comment by toddlucas** [comment]
@SaschaNaz, interfaces make it easier to do certain things, like writhing unit tests with mock objects. They are one of the key differences between TypeScript and ES6. The class declarations mirror the actual classes, including constructors and static methods.

**Comment by toddlucas** [comment]
@zengfenfei, as I said earlier, it may make sense to merge these at some point. Doing so now will break anyone who is using isomorphic-fetch and making use of interface definitions.

I'm not sure if you read my initial PR comment, but isomorphic-fetch also has to represent node-fetch definitions, which is lagging further behind the fetch spec. If someone uses these definitions, they may see that they can use headers.keys(), for example. But when they run that code on the server, it will fail.

We've been spending a lot of time talking about the whatwg-fetch definitions. What about the node-fetch definitions? If you two are using isomorphic-fetch, I assume you're also running fetch on the server.

Finally, how do people reference this? There are two problems here. First, how do people know that they also have to install typings for whatwg-fetch when they're using isomorphic-fetch? Second, some tools, like typings, rewrite the type definitions files and change the names. So the reference would fail.

**Comment by RyanCavanaugh** [comment]
This looks OK to me. Any objections @SaschaNaz ?

**Comment by SaschaNaz** [comment]
@RyanCavanaugh I don't think there is any blocking problem, so no objections.

**Comment by toddlucas** [comment]
Thanks @RyanCavanaugh. @SaschaNaz, I'm hoping that these can be merged somehow in the near future. We'll need to take the three projects into account. At some point we'll hopefully just have fetch on the client and in Node and we'll have one set of definitions. Thanks for your input and help.

**Pull request merged**
