### PR TITLE
Uses "export default" syntax.

### PR DESCRIPTION
**Pull request by ryasmi**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Wow, that breaks lots of things. Might want to close this to avoid irritating lots of people.

**Comment by vvakame** [comment]
Is this PR same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9020#issuecomment-211047386 ?

**Comment by ryansmith94** [comment]
I don't think so @vvakame, because Express is actually a function and they use [`module.exports =`](https://github.com/expressjs/express/blob/master/index.js).

**Comment by vvakame** [comment]
`module.exports =` can't convert to `export default e;` in `tsc --target es5` context.

```
$ cat test.d.ts
declare module "test1" {
    function test(): void;
    export default test;
}

declare module "test2" {
    function test(): void;
    namespace test {}
    export = test;
}
$ cat index.ts
import test1 from "test1";
import * as test2 from "test2";

test1();
test2();
$ tsc --target es5 index.ts test.d.ts
$ cat index.js
"use strict";
var test1_1 = require("test1");
var test2 = require("test2");
test1_1.default();
test2();
```

**Comment by ryansmith94** [comment]
I'm pretty sure `import * as test2 from "test2";` and then `test2();` causes type errors though? I'm pretty sure that's why I started doing this in the first place.

**Comment by vvakame** [comment]
please show me your sample code.

**Comment by ryansmith94** [comment]
Actually, just been checking this. Express seems to be fine. Firebase and Knex are still imported like `import knex from "knex";`

**Comment by ryansmith94** [comment]
Closing because of inactivity

**Pull request closed without merging**
