### PR TITLE
Fix wordpress__components & wordpress__compose type mismatch after change to React v18

### PR DESCRIPTION
**Pull request by danieliser**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://github.com/WordPress/gutenberg/pull/45235
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danieliser** [comment]
@typescript-bot Test changes were not necessary as the type mismatch came from a dependency version mismatch.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__components@latest/))
was missing the following properties:
1. CustomGradientPicker
1. DuotonePicker
1. DuotoneSwatch
1. GradientPicker
1. GuidePage

<details>
<summary>as well as these 6 other properties...</summary>
<p>Line, SearchControl, TextHighlight, ToolbarDropdownMenu, ToolbarItem, useBaseControlProps</p>
</details>

## wordpress__compose ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__compose@latest/))
was missing the following properties:
1. useConstrainedTabbing
1. useCopyOnClick
1. useCopyToClipboard
1. useFocusOnMount
1. useFocusReturn

<details>
<summary>as well as these 12 other properties...</summary>
<p>useInstanceId, useIsomorphicLayoutEffect, useKeyboardShortcut, usePrevious, useViewportMatch, useResizeObserver, useAsyncList, useWarnOnChange, useDebounce, useThrottle, useMergeRefs, useRefEffect</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e53b41db6d0da41f55e893a92da2ee780d48e9cc
</p>

**Comment by danieliser** [comment]
Didn't realize this PR included the update for @types/wordpress__compose as well, so bumped the version for it as well. Same issue fixed in both packages still.

**Review by noahtallen — APPROVED** [review]
Makes sense to me, but I don't know if it will accept my approval!

**Comment by danieliser** [comment]
@noahtallen - thanks, seems to have resolved everything we were seeing with react/JSX component type mismatches.

**Review by sirreal — APPROVED** [review]

**Pull request merged**
