### PR TITLE
[mumath] Add mumath typing

### PR DESCRIPTION
**Pull request by azerella**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by amcasey** [comment]
Just to confirm, this is intentionally not covering cases like `import round = require('mumath/round');`?

**Comment by adamzerella** [comment]
> Just to confirm, this is intentionally not covering cases like `import round = require('mumath/round');`?

Right, I coudln't find any guidance on if this was a requirement, happy to test for it if you'd prefer. I'm assuming we'd just wrap the functions in a `namespace` ?

**Comment by amcasey** [comment]
@adamzerella Partial types are better than no types, so I think it would be acceptable to merge as-is.  I just wanted to make sure you had intentionally decided to defer that work.

To handle the other modules, I think you'd have to add a bunch of additional files (e.g. round.d.ts).

**Comment by adamzerella** [comment]
I agree @amcase, I think this is fine for now.

I can see myself in the future adding in the additional types for those edge cases

**Review by amcasey — APPROVED** [review]

**Pull request merged**
