### PR TITLE
[@types/sinon] Added signature for assert.calledOnceWithExactly

### PR DESCRIPTION
**Pull request by rhodgkins**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sinonjs/sinon/pull/2080#issuecomment-589197118
- ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~ Don't need to do this as it was missed from the current ([7.5](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e32d4f0292c57f63310af65a7fb3708155cf8083/types/sinon/index.d.ts#L1)) version (https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md#750--2019-09-23).

### CODE REVIEW

**Review by johnjesse — COMMENTED** [review]
Is this correct? Looking at the sinon docs for assert https://sinonjs.org/releases/v9.0.0/assertions/, `calledOnceWithExactly` does not appear to be on the assert interface - or have I read it wrong?

ahh - I should have read your comments properly first, it is now in Sinon... but for some reason not in their docs - do we know of any reason why their docs don't have this method? I thought we typically try to keep the types up to date with the Documentation

**Comment by 43081j** [comment]
looks to be another case of an undocumented sinon feature.

we've had a fair amount of them.. we should PR a docs update before we put it in the types tbh, as thats the definitive source of whats "supported". though yeah its clear that it is a feature in this case

**Comment by rhodgkins** [comment]
I’m happy to put a PR together to update the Sinon docs but does that need to be a blocker for merging this in? This method has been available for two major version changes now?

**Comment by 43081j** [comment]
Not really no. As long as we get it into the docs, as in a pr is open before this is merged, all is good. 

It's not a huge pr to make so if you don't have the time, let me know and I'll open one.

**Comment by rhodgkins** [comment]
@43081j - done: https://github.com/sinonjs/sinon/pull/2229

**Review by 43081j — APPROVED** [review]

**Pull request merged**
