### PR TITLE
Spectacle - Slide and Deck component prop updates

### PR DESCRIPTION
**Pull request by rawrmonstar**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/FormidableLabs/spectacle/pull/626>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by kale-stew** [comment]
This LGTM! I will approve once the feature PR is approved inside of Spectacle

**Comment by rawrmonstar** [comment]
Please hold off on merging for now. Who should I ping when the corresponding PR is merged?

**Comment by weswigham** [comment]
If it's in the next 6 days, me.

**Comment by rawrmonstar** [comment]
@weswigham This can now be merged. Thanks 🙇‍♀️

**Pull request merged**
