### PR TITLE
[ramda] Use `types-ramda` package

### PR DESCRIPTION
**Pull request by Harris-Miller**
# `types-ramda` package is live!

The new `types-ramda` [package](https://github.com/ramda/types) is now published to [npm](https://www.npmjs.com/package/types-ramda)

That package brings all the types that are defined here as `@types/ramda` in-house. The goal is to have more direct control and work on filling out all the missing pieces. Eventually, that repo will be migrated into the core `ramda` repo so types can be first-class. Until then, the plan is to just have `@types/ramda` re-export `types-ramda` until then

## Changes to `@types/ramda`

* The `index.d.ts` now just re-exports all of `types-ramda` (all definitions were moved [there](https://github.com/ramda/types))
* `tools.d.ts` removed except from a single common function that is still used for tests
* A lot of test assertion types were updated to support a major bump of `ts-toolkit` done in `types-ramda`

## Looking for help with `types-ramda`!

If you would like to contribute, please check out [https://github.com/ramda/types](https://github.com/ramda/types)

### CODE REVIEW

**Comment by Harris-Miller** [comment]
@TheHandsomeCoder @donnut @mdekrey @sbking @afharo @teves-castro @hojberg @samsonkeung @angeloocana @raynerd @moshensky @ethanresnick @deftomat @blimusiek @biern @rayhaneh @rgm @jottenlips @minitesh @Krantisinh @Nemo108 @jituanlin @Philippe-mills @Saul-Mirone @Nicholaiii @LORDBABUINO @couzic @NEWESTERS @adispring @essenmitsosse

I'm looking for help over at https://github.com/ramda/types, please message me if you'd like to help!

**Comment by Nicholaiii** [comment]
Cool! Did you read the CI output? You need to add the package to an allowlist

**Comment by jakebailey** [comment]
I guess this isn't different than what jest is doing, but why not move the types to ramda and then remove the package from DT entirely, leaving it as a "not needed package" per our normal removal process?

**Comment by jakebailey** [comment]
As in you can install `@types/jest` and now all of your files can use `test`/`describe/`it`, etc globally without imports. Same as how installing `@types/node` gets you the `process` object and such.

**Comment by Harris-Miller** [comment]
Ah ok. Not what we're going for here. Were's just looking to transfer the source of truth to be in-house, have control over MRs to update, and pass onward those updates to all consumers of `ramda` by having `@types/ramda` re-export.

End-goal is to eventually merge `types-ramda` directly into `ramda` and then deprecate `@types/ramda`

**Comment by jakebailey** [comment]
Right, hence saying to ignore it 😄 

But, I think @andrewbranch's comment (https://github.com/microsoft/DefinitelyTyped-tools/pull/660#issuecomment-1490751890) definitely still applies. It really seems like it'd be better to just stick these in to `ramda` directly rather than going through the process of trying to migrate twice.

**Comment by Harris-Miller** [comment]
> It really seems like it'd be better to just stick these in to ramda directly rather than going through the process of trying to migrate twice.

Ideally, yes, and the plan is to do exactly that... eventually. Ramda's core team isn't quite ready to make that leap yet. What we're doing here is the "compromise". `types-ramda` is born-to-die and I'm hoping to get the types defined directly into the core `ramda` lib ASAP

**Comment by Harris-Miller** [comment]
@jakebailey @andrewbranch I've been thinking about the conversation over at https://github.com/microsoft/DefinitelyTyped-tools/pull/660, and I'd like your opinions about a few things

The `types-ramda` package is meant to serve 2 purposes:

* move type definition in house
* prepare them to be migrated into the core `ramda` repo

This means that `types-ramda` was born to die. The feedback that you both have given is "either keep type definitions here or put them in the core `ramda` repo". While I fully understand and support that, I cannot do the latter option right now, so it's either keep types here in `DefinitelyTyped` or do what I'm proposing in this MR.

To keep the typings here, I could use your help with a few at-large problems:

The "move type definitions in house" part is so a smaller group of people have control over merges, and its not just up to the community at-large. The second is to work inside of an isolated repo to do the type updates, and not directly in `DefinitelyTyped`, which can be very challenging

The second, "prepare them to be migrated into the core `ramda` repo". The existing [types-ramda](https://github.com/ramda/types) repo is the [ts-branch of ramda](https://github.com/ramda/ramda/tree/ts) with the types part ripped out. The idea is to update all the types, then move them back into the core repo. There are 2 key differences between `@types/ramda` and `types-ramda`

* `@types/ramda` has all the types defined in `index.d.ts`, and they are re-exported out from `src/function.d.ts`, `types-ramda` is done inversely to this
* For testing `@types/ramda` uses `@definitelytyped/dtslint`, while `types-ramda` uses `tsd`

Migrating type definitions to be `src/functions.d.ts` just takes time and effort, but I'm not sure how `@definitelytyped/dtslint` can be used to test outside of `DefinitelyTyped`

I was hoping to get your opinions on solving the above issues, specifically:
* limiting approval rights for `@types/ramda`
* How to work in `DefinitelyTyped` in a way that simplifies out development
* How to continue to use the current tests once migrating the type definitions into `ramda`

**Comment by andrewbranch** [comment]
> The "move type definitions in house" part is so a smaller group of people have control over merges, and its not just up to the community at-large.

PRs on DT don’t exactly operate on a democratic process with the whole community. The people in the header comment of index.d.ts, along with DT admins (the TypeScript team and a handful of others) can give approvals that allow the PR author to merge without an admin. We can add your group of maintainers to the header, though I’m not totally sure how to feel about removing everyone else in the list.

> How to continue to use the current tests once migrating the type definitions into `ramda`

It’s possible to use dtslint outside of DT; it’s just not super highly recommended. I guess I would recommend writing tests that rely on real TS errors as much as possible, using `// @ts-expect-error` to assert where errors should be and allowing the lack of compiler errors on assignments to assert where errors shouldn’t be. That might give you less to migrate down the line.

**Comment by jakebailey** [comment]
> It’s possible to use dtslint outside of DT; it’s just not super highly recommended. I guess I would recommend writing tests that rely on real TS errors as much as possible, using `// @ts-expect-error` to assert where errors should be and allowing the lack of compiler errors on assignments to assert where errors shouldn’t be. That might give you less to migrate down the line.

Just to add on, there are libraries that work a lot better outside of DT, e.g. [tsd](https://www.npmjs.com/package/tsd); that's what I'd recommend if you're wanting a DT-like experience externally.

Preferably of course the library would be in TS from the start (then you get to test things by way of needing to use functions and write tests), but it's still useful regardless.

**Comment by Harris-Miller** [comment]
@andrewbranch @jakebailey we are using `tsd` in `types-ramda`. And we wanted to migrate the existing tests that currently exist here. To do that, however, we need `types-ramda` to exist as an intermediary. To be able to update the types and migrate all the testing, we don't want to have to manage 2 sources of truth, thus, `@types/ramda` re-exporting `types-ramda`.

We've thought this plan out quite thoroughly, and we understand the risks and the rewards. We just weren't aware of the need for https://github.com/microsoft/DefinitelyTyped-tools/pull/660

**Comment by afharo** [comment]
> I’m not totally sure how to feel about removing everyone else in the list.

As someone in the header, I'm happy to be removed for the greater good. I can happily switch to contribute to `types-ramda`.

**Comment by andrewbranch** [comment]
@Harris-Miller we recommend doing development here on DT or in ramda itself, but if you’re still set on this approach, we’ll merge https://github.com/microsoft/DefinitelyTyped-tools/pull/660. It sounded like you were reconsidering developing on DT. Just let me know what you’d like to do.

**Comment by Harris-Miller** [comment]
@andrewbranch If you could merge https://github.com/microsoft/DefinitelyTyped-tools/pull/660 I would very much appreciate it. Check out the PRs I already have over on `types-ramda`: https://github.com/ramda/types/pulls. Being able to migrate the tests to use `tsd` in that way will help us slowly improve all the types until the core `ramda` lib is ready to ingest them itself

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fbdd304094769cd04ac1af81452e2dea59655e90
</p>

**Comment by jakebailey** [comment]
Unsure why @typescript-bot hasn't dropped the "CI failed" label.

**Comment by Harris-Miller** [comment]
Ok! I believe I just need approval from someone in the header and we can merge!

**Review by afharo — APPROVED** [review]
LGTM! So exciting for this being the first step towards having all types served by `ramda`.

I have a question, though... how will the `@types/ramda` versioning work? I assume that if we need to publish new versions, we'll need to come here to make _some_ changes (to the tests?) so that a new version is published.

**Comment by jakebailey** [comment]
I was going to say that it wouldn't matter, but I'm now seeing that the dependency is on `^0.2.0`.

This means people won't get 0.3.0, for example. Was it intentional to use a version so restrictive? Any reason to not just use `*`?

**Comment by Harris-Miller** [comment]
@jakebailey no reason, I changed it to `*`

**Review by jakebailey — DISMISSED** [review]

**Comment by jakebailey** [comment]
I'll approve it provided you're okay with `"*"`; basically every option has its upsides and downsides, I just wanted you to make sure that you chose the one that works for you!

**Comment by Harris-Miller** [comment]
@jakebailey Actually, thinking about this. I think I'd rather have it be `semver`.

Let's say that we merge this MR with `'*'`. That will bump `@types/ramda` to `0.29.0` to match the latest release of `ramda`.

Now if start a new project right after and `npm i @types/ramda` I'll get `@types/ramda@0.29.0` and `types-ramda@0.3.0`.

With the `'*'` dependency, we will never release a new `@types/ramda`, only `types-ramda`.
So let's say a month goes by and `types-ramda` is at `0.6.0`. A fresh `npm i @types/ramda` will get `types-ramda@0.6.0`, but that previous project will still be at `0.3.0`. It won't know that `types-ramda` had releases under the hood because there was never a new version of `@types/ramda`.

I'm thinking for stuff like Depend-a-bot, Renovate-Bot, Whitesouce, or just manual package bumps utilizing something like `npm-check-updates`. These processes would fail to recognize `types-ramda` had updates.

For that reason, I think it makes more sense to have continue MRs for the `@types/ramda` package just to bump the `types-ramda` semver

**Comment by jakebailey** [comment]
This is another reason why trying to do this forwarding is problematic; now there are _three_ packages which are versioning themselves in different ways. At least when it's just `ramda` and `@types/ramda`, the user explicitly depends on both and can control them, but, when `@types/ramda` depends on `types-ramda`, now there's no control that can be given outside of lockfiles and overrides, unless versions are bumped in DT, except that the DT versions are _supposed_ to match the versions of the project being typed.

For this to idea work, I think the only reasonable thing is for `types-ramda` to version itself like DT and bump itself up to `0.29.x` to match `ramda`, then when `0.30.0` of `ramda` comes out, `types-ramda` releases `0.30.x` and `@types/ramda` bumps its version to `0.30` and its dep on `types-ramda` to `^0.30.0` to match.

Hopefully you can see why we are really recommending either using DT in full or not using DT at all; there are a lot of things that can go wrong.

**Comment by jakebailey** [comment]
Reading the readme on https://www.npmjs.com/package/types-ramda, I can see that your plan appears to not be the above:

> We cannot lock the semver to be the same as ramda's since we plan on doing multiple releases to this library to progressively update the types until they are all correct. So for that reason, we are starting at 0.1.0 and will simply do Minor releases for new changes and Patch release for regression fixes.

I know you can't "lock" to be the same as ramda, but I think you're definitely going to need to be doing some sort of versioning to indicate which `0.x` version of `ramda` each version of `types-ramda` aims to describe. It's fine if that means major version bumps of `types-ramda` instead (as major=0 versions in the Node ecosystem give _minor_ versions the semantics of _major_ versions), or even do `0.x` releases, so long as there's thought put into it.

But, I wouldn't expect any DT maintainers to really understand what's going on if it's not clear; matching versioning makes things a lot simpler.

I'll also point out that any modification of `package.json` will require DT maintainer approval; I don't think ramda releases _that_ often, so it probably won't cause too many negative affects, but it's noteworthy. It's possible that restriction will change in the near future (as we're converting DT to a pnpm monorepo), but it still is a friction point.

**Comment by Harris-Miller** [comment]
I could bump `types-ramda` to `0.29.0`, which would trigger `@types/ramda` to be `0.29.0`. This way for each `types-ramda` patch release `@types/ramda` would get a patch release and they'd be in sync. We don't expect `ramda` to match those, no differently that `react` and `@types/react`. We'd just try and stick to `major.minor` syncing

**Comment by jakebailey** [comment]
That works, I think.

Feasibly, you could start at 0.3.0 like you are now and bump minor for each minor of ramda, but, I figured that keeping them even would be the least confusion option. But, any changes you make must be released in a patch release (just like ramda, I suppose).

**Comment by afharo** [comment]
++ to having better control over the versions. `*` seemed a bit too permissive. Thanks for iterating on this.

**Comment by Harris-Miller** [comment]
`types-ramda@0.29.0` now in MR

**Review by jakebailey — APPROVED** [review]

**Comment by Harris-Miller** [comment]
Ready to merge

**Comment by Harris-Miller** [comment]
@jakebailey Hey man. This merge did a `patch` release and we had meant for it to do a minor release. What do I need to do to correct that?

**Comment by jakebailey** [comment]
Uh oh. What we should have done was bump the types to 0.29 first, let it publish, then update them. I didn't realize they were set to 0.28.

What we can do now is this:

- First, bump this package to 0.29, so people get the latest.
- Create a `v0.28` folder and copy the old state back in with the old version, and let that publish.
- Once 0.28 is published again but with the old contents put back over, delete it again.

**Comment by jakebailey** [comment]
Rather, what we should have done was bump the version in index.d.ts, actually. No need for that waiting game. But, too late now. I am happy to do the above real quick.

**Comment by jakebailey** [comment]
I've now done this whole rigmarole.

- 0.29.0 is out, pointing to 0.29.0 of `types-ramda`.
- 0.28.25 is out, restoring the old contents of 0.28 before this change. 0.28.24 is the bad release; hopefully people update past it.
- The 0.28 types are deleted again.

So, we should be good. Thanks for letting me know.

**Comment by Harris-Miller** [comment]
@jakebailey Thank you so much!

**Pull request merged**
