### PR TITLE
Updating type definitions for nes >= 7.0.0 and hapi-auth-basic >= 5.0.0

### PR DESCRIPTION
**Pull request by saboya**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/nes/commit/9b08d91b19b35d9c340a61605be025304603aa88
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

~Running tests on this PR by itself isn't possible because the tests won't run unless types for [hapi](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hapi) and [hapi-auth-basic](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hapi-auth-basic) are updated accordingly, which I'm currently unable to do so.~

~However I did test the changes I made to the code via another project that depends on the Nes.Client type definitions, which worked just fine.~

Updated hapi-auth-basic as well, don't know if it should fit a separate PR. Still depends on Hapi v17 definitions. Apparently there's some work going on here: https://github.com/rafaelsouzaf/DefinitelyTyped/pull/1

Tests pass nonetheless.

### CODE REVIEW

**Review by NoHomey — APPROVED** [review]

**Comment by armanio123** [comment]
Tagging @AJamesPhillips for review on hapi-auth-basic types.

**Comment by AJamesPhillips** [comment]
Hey @armanio123 thanks for tagging me in.  I'm not actively developing with this tech at the moment  (though am using in production on other products) so I don't feel confident in saying things should be done one way or the other.  Labelling a callback as `h` instead of `callback` is one of the things that I would ask about.  The other was if the callback pattern in nes was actually removed or if it's just possible to use callbacks and promises now.  If so I'd try (if it's not too difficult with the typings) to keep both function signatures... though historically I have struggled to implement this well, for example this looks like carnage! :|  :P https://github.com/DefinitelyTyped/DefinitelyTyped/blob/954ee27/types/hapi/index.d.ts#L422-L429  but I don't know if there's a better solution / pattern.

Haven't checked any of the details but generally looks great.  Thanks very much for efforts saboya!

**Comment by saboya** [comment]
Hello

As far as I know, the callback pattern was indeed removed from Nes.

About `h`, it's the new response toolkit from Hapi v17. I used `h` because that's what the Hapi documentation itself uses:

https://github.com/hapijs/hapi/issues/3658

`h` will be better documented once Hapi v17 typings lands, and proper typing is added, like `h: ResponseToolkit` or something like that.

**Comment by armanio123** [comment]
Thanks @AJamesPhillips and @saboya for working through this, I will merge this PR.

**Pull request merged**
