### PR TITLE
Fix uuid 7.0

### LINKED ISSUE #42634: [@types/uuid] - v7.0.0 breaks `uuid/v4`
- [X] I tried using the `@types/uuid` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamolivinius, @felipeochoa, @cjbarth, @rauno56, @LinusU, and @ctavan

Imports of `uuid/v4` broke today as no declaration file found after update to @types/uuid v7.0.0

```
Could not find a declaration file for module 'uuid/v4'. '/Users/pete.burkindine/git/ccxp/ccxp-client/node_modules/uuid/v4.js' implicitly has an 'any' type.
  Try `npm install @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid/v4';`
```

### PR DESCRIPTION
**Pull request by ghost**
Doesn't solve the problem from #42634, but fix other issue with new types. cc @ctavan

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
This is the published file:

https://cdn.jsdelivr.net/npm/uuid@7.0.2/dist/index.js

Based on this I think that this change is correct 👍

**Review by ctavan — CHANGES_REQUESTED** [review]
I‘m not a typescript pro but I don’t really understand how this fixes the linked issue.

The linked issue is about deep imports. Wouldn’t we have to revive the additional v1.d.ts etc files to fix the linked issue?

**Comment by LinusU** [comment]
I should add that I didn't look at the linked issue, my review was based solely on what I think is the correct typings for the `index.d.ts` file, additional changes might be needed to facilitate direct deep imports...

**Comment by clar-cmp** [comment]
Oh, I linked that issue but I appear to be wrong on that.

My particular issue is that these types actually are wrong; there is no default export for `uuid` so the original types don't actually work. I mistakenly linked the wrong issue because I saw that  there was a bug and linked that.

**Comment by ctavan** [comment]
Ok, it‘s true we removed the default export but missed that in the types update. Thanks for the fix!

But please remove the issue reference from the PR description because right now GitHub still thinks it will fix the other issue (seem like GitHub isn’t smart enough to interpret „doesn‘t fix“...)

**Comment by clar-cmp** [comment]
Oops, removed that from the description.

**Review by ctavan — APPROVED** [review]
👍🏼

**Comment by clar-cmp** [comment]
Is anyone going to merge this? :(

The PR #43090 got merged but this one is still hanging.

**Comment by orta** [comment]
Yep, let's get this in.

**Pull request merged**
