### PR TITLE
[react-native] add enabled prop to KeyboardAvoidingView

### PR DESCRIPTION
**Pull request by xzilja**
Adding missing prop, this is my first time contributing to definitely typed, library is very large so I can't pull it to run the tests :/ whats the advised approach here?

https://facebook.github.io/react-native/docs/keyboardavoidingview#enabled

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by a-tarasyuk — CHANGES_REQUESTED** [review]
Could you add tests?

**Comment by alloy** [comment]
Ah, I see. I still don’t really understand what the issue is. Is the repo too large _for your internet connection_? Because it definitely works for others.

**Comment by alloy** [comment]
(But to be clear, if you can make a good test case that passes CI from the GH editor then that’s absolutely fine with me of course.)

**Comment by IljaDaderko** [comment]
@alloy yep, I was at coffee shop at the time, couldn't pull it

**Comment by alloy** [comment]
Gotcha, makes sense.

**Comment by IljaDaderko** [comment]
@alloy Hey, I want to wrap this up, sorry it is taking to long. But I'm not sure where / how to start with the tests, I assume due to how simple my change is it shouldn't be anything crazy, but could you point me to correct direction please?

Also I am not too sure what that ci error is about

> ERROR: 2057:1  no-trailing-whitespace  trailing whitespace

**Comment by andy-ms** [comment]
@IljaDaderko That's a lint error because a line of text ends in a space. Try enabling rendering whitespace in your editor (or better, enable automatic trimming of whitespace).

**Pull request closed without merging**
