### PR TITLE
Type updates for frappe-gantt library

### PR DESCRIPTION
**Pull request by ELI7VH**
- removed `any`
- added new options to constructor arguments
- added typing of event handlers
- updated tests
- incremented version

### CODE REVIEW

**Comment by ELI7VH** [comment]
@samalexander

**Review by samalexander — APPROVED** [review]
Cool, looks good to me 👍

**Review by orta — APPROVED** [review]

**Comment by ELI7VH** [comment]
Ready to merge

**Comment by ELI7VH** [comment]
@samalexander , hey man, do you see anything in this PR that would cause this error:

```
 /home/elucian/vizzn-web/node_modules/frappe-gantt/src/index.js:1
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import date_utils from './date_utils';
                                                                                           ^^^^^^
  SyntaxError: Cannot use import statement outside a module
    1 | import React, { useState, useEffect, useRef } from 'react'
  > 2 | import Gantt from 'frappe-gantt'
      | ^
    3 | 
    4 | export const GanttView = () => {
    5 |   // let context = useScheduleContext()
    at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
    at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
    at Object.<anonymous> (src/components/JobScheduling/GanttView/index.tsx:2:1)
```

seems like importing the date-fns is now causing an error.. could using the `dom` library cause this? Not sure how...

**Comment by ELI7VH** [comment]
false alarm: `lint-staged` will fail because brouhaha:

fix: added `"frappe-gant": "frappe-gantt/dist/frappe-gantt.js"` to our `package.json:jest:moduleNameMapper` array

**Pull request merged**
