### PR TITLE
babel-types: Improve accuracy of node types

### PR DESCRIPTION
**Pull request by rpetrich**
- Update the optionality/null presence of node type properties based on observed behaviour from babel
- Allow passing null to `is...` and `assert...` functions, so that values peeled from optional/nullable properties can be used without additional validation

_(built alongside updated types for babel-traverse in #26432)_

### CODE REVIEW

**Comment by bcherny** [comment]
Thanks for the contribution @rpetrich . Babel-Types [comes with packaged types already](https://github.com/babel/babel/blob/d383659ca6adec54b6054f77cdaa16da88e8a171/packages/babel-types/package.json#L10), so you should make you change there instead. Note that the types are codegen'd from the [AST definitions](https://github.com/babel/babel/tree/master/packages/babel-types/src/definitions.

We should really delete these typings from DT.

**Review by bcherny — CHANGES_REQUESTED** [review]
See feedback above.

**Comment by marvinhagemeister** [comment]
@bcherny No, the future `babel v7` will come with definitions. `babel v6` still doesn't have them. As long as the former is in beta, I'm in favour of merging this.

**Comment by bcherny** [comment]
Sounds good to me. Can we lift the types directly from Babel-types 7, or do the APIs differ?

**Pull request closed without merging**
