### PR TITLE
Knex: add missing transaction.raw

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by sandersn** [comment]
Can you point to documentation or example source? I don't see it in the Knex documentation but I'm not really familiar with it either.

**Comment by OliverJAsh** [comment]
http://knexjs.org/#Transactions

A transaction is just like a "promise aware" knex connection object, it has the same interface.

**Comment by OliverJAsh** [comment]
And http://knexjs.org/#Raw

**Comment by sandersn** [comment]
Makes sense. 

It looks like the tests failed, saying that "Raw is not callable".

**Comment by OliverJAsh** [comment]
Sorry about that, should now be fixed.

**Pull request merged**
