### PR TITLE
faker: Support locale (and few bug fixes)

### PR DESCRIPTION
**Pull request by Kuniwak**
### Abstract

Support locales and fix few bugs.
This changes are based on [recent master](https://github.com/Marak/faker.js/tree/20ec97b9b7449ba0ca37a90226a8651f18164e53) of faker.
### Changes
1. Support localization by [changing `faker.locale`](https://github.com/Marak/faker.js#localization)
   
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/ad28dfc40bb80209cc4f058f526d465d01dc5e81#diff-5e33a4044a8c5be04b1e3e02796d6723R10).
2. Support [Individual Localization Packages](https://github.com/Marak/faker.js#individual-localization-packages)
   
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/ad28dfc40bb80209cc4f058f526d465d01dc5e81#diff-5e33a4044a8c5be04b1e3e02796d6723R172).
3. Fix types for `faker.helpers.randomize()`
   
   [If its param is omitted, it should return a string](https://github.com/Marak/faker.js/blob/20ec97b9b7449ba0ca37a90226a8651f18164e53/lib/helpers.js#L7).
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/d80194e8f36b9c9955948af53460ca8005842828#diff-5e33a4044a8c5be04b1e3e02796d6723R90).
4.  Fix types for `faker.random.objectElement()` 
   
   [If its param is omitted, it should return a string](https://github.com/Marak/faker.js/blob/20ec97b9b7449ba0ca37a90226a8651f18164e53/lib/random.js#L57).
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/d80194e8f36b9c9955948af53460ca8005842828#diff-5e33a4044a8c5be04b1e3e02796d6723R166).
5.  Fix types for `faker.random.arrayElement()` 
   
   [If its param is omitted, it should return a string](https://github.com/Marak/faker.js/blob/20ec97b9b7449ba0ca37a90226a8651f18164e53/lib/random.js#L50).
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/d80194e8f36b9c9955948af53460ca8005842828#diff-5e33a4044a8c5be04b1e3e02796d6723R164)
6. Fix types for `faker.helpers.createCard` 
   
   [It should contains `address.streetA`](https://github.com/Marak/faker.js/blob/20ec97b9b7449ba0ca37a90226a8651f18164e53/lib/helpers.js#L78).
   See [the test](https://github.com/borisyankov/DefinitelyTyped/commit/d80194e8f36b9c9955948af53460ca8005842828#diff-5e33a4044a8c5be04b1e3e02796d6723R101).

### CODE REVIEW

**Comment by Kuniwak** [comment]
@basp Could you review this PR please?

**Comment by basp** [comment]
@Kuniwak Thanks a lot for the fixes and additions. Looks good!

**Comment by Kuniwak** [comment]
@basp Thanks!

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
