### PR TITLE
Adds isUtf8 to Node.js Buffer

### PR DESCRIPTION
**Pull request by philnash**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/buffer.html#bufferisasciiinput
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I have a question about the last check box. These functions were added to Node in 19.4 (`isUtf8`) and 19.6 (`isAscii`), since version 18 is the LTS, do we still add types for Node 19, or should they wait until 20?

### CODE REVIEW

**Comment by philnash** [comment]
Apologies, I hadn't noticed `isUtf8` in v18.14, the v19 docs just said it was added in v19.4. If the types are at 18.11, does that mean that this PR is too early?

Also, I realised I didn't add these types to the `ts4.8` directory. Should I do that before this will be merged? (I'm not sure of the reason for the `ts4.8` directory, I'd be interested to know what it's for, but if you're all busy, just a yes or no on whether I should add these two definitions to it will suffice :) .)

**Comment by Semigradsky** [comment]
My suggestions:
- remain only `isUtf8` changes
- add these changes to `ts4.8` folder too
- update the version number in the header of `index.d.ts` file to `18.14`

**Comment by Semigradsky** [comment]
> do we still add types for Node 19, or should they wait until 20?

If I understand correctly, odd-numbered versions of Node.js (...13, 15, 17, 19...) are unstable like "beta" and we don't want to waste time supporting them.

**Comment by philnash** [comment]
Thanks @Semigradsky, I've made those changes. Will open another PR to bring in `isAscii` when the time/version is right. 

Hopefully this PR is in a good place to merge too.

**Comment by philnash** [comment]
Hey team, any chance you can take a look at this now?

**Review by vansergen — APPROVED** [review]
The title also could be updated 👍

**Comment by philnash** [comment]
Yep, good point about the title! I've updated it, thanks @vansergen.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@philnash thanks!

**Comment by philnash** [comment]
Ready to merge

**Pull request merged**
