### PR TITLE
fix(eslint-utils): fix types and add generics

### PR DESCRIPTION
**Pull request by roikoren755**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [source code](https://github.com/mysticatea/eslint-utils/blob/master/src/reference-tracker.js). [Similar](https://github.com/typescript-eslint/typescript-eslint/issues/4159) [discussion](https://github.com/typescript-eslint/typescript-eslint/pull/4173) in `@typescript-eslint`'s repo.
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM (thanks!), but I'm no expert on eslint-utils. Someone from #53803 / @bradzacher / @mysticatea might want to take a look.

**Comment by roikoren755** [comment]
@JoshuaKGoldberg thanks for reviewing, I'll wait for another approval before merging :)

@ota-meshi @MichaelDeBoey in case you want to look at this

**Review by ota-meshi — APPROVED** [review]
LGMT!

**Comment by roikoren755** [comment]
Ready to merge

**Pull request merged**
