### PR TITLE
Add failing test for enzyme instance() method

### PR DESCRIPTION
**Pull request by mohsen1**
I'm not sure how to type ShallowWrapper so it carries over types of wrapping class. 

Wrote the failing test and will try to fix it tonight. In the meanwhile any help is appreciated.

### CODE REVIEW

**Comment by mohsen1** [comment]
ping @andy-ms @sandersn

**Comment by andy-ms** [comment]
I think `CommonWrapper` would have to be generic of the particular type being wrapped, and not just its props/state.

**Comment by RyanCavanaugh** [comment]
@mohsen1 Please fix the failures indicated in the Travis CI log.

**Comment by mohsen1** [comment]
Wait, @RyanCavanaugh is a bot too?! 🤖

@andy-ms Do you mean something like this?

```ts
interface ShallowWrapper<P, S, T extends React.Component<P, S>> {
    instance(): T
}
```

**Comment by andy-ms** [comment]
Yep.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by amacleay** [comment]
I ran into exactly this problem recently. Should this be revived, perhaps as a proper issue?

**Pull request closed without merging**
