### PR TITLE
Definitions for needle 2.0

### PR DESCRIPTION
**Pull request by sindilevich**
Adding definitions for needle 2.0. This includes new properties on `NeedleOptions` and the definitions for the new `needle(): Promise<NeedleResponse>` method.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tomas/needle/blob/master/README.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nikeee** [comment]
:+1:

**Review by sandersn — CHANGES_REQUESTED** [review]
Can you follow [the readme's directions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version) for archiving the types for 1.4 ? Thanks.

**Comment by sindilevich** [comment]
Hello @sandersn,

I am a bit confused by the README, as it doesn't state where should I place files for v2. Do I understand correctly, you want me to create a folder, say `v2` and make my changes to comply with needle 2.0 there? Those files, left in the root of the needle repo will be those of 1.4? Thank you for further clarifications.

**Comment by nikeee** [comment]
You have to move the old definitions and tests to a new folder called v1, I think.

**Comment by sindilevich** [comment]
Thank you, @nikeee.

**Comment by sindilevich** [comment]
@sandersn, have addressed your comment by preserving the old version of the definitions in a separate folder.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
Thanks @sindilevich!

**Pull request merged**
