### PR TITLE
[graphql] Meet types-2.0 style

### PR DESCRIPTION
**Pull request by TonyPythoneer**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
@calebmer @intellix
Could you review this PR?
👍 or 👎?

**Comment by TonyPythoneer** [comment]
Hello, @calebmer @intellix 
If you have time, could you review this PR?

**Comment by intellix** [comment]
LGTM!

**Comment by calebmer** [comment]
The reason I've deferred looking at this for so long is that a lot has changed 😊

Did you change anything other then file structure?

Also, the single file is kind of convenient in that it can be easily copy/pasted between projects. So why change it?

**Comment by TonyPythoneer** [comment]
@calebmer No, it's just copy/pasted to build the structure. If I had updated in this file, I will offer the document or source code as reference.

It's because graphql is a big project. As we have seen, there are thousand of code lines in the whole file. I I think it's not good to maintain for any contributor. 

In fact, I made originally this definition was very difficult. It didn't have typescript 2.0. It means when a contributor wants to build a definition, we can't assert individual module as a file.

If a contributor wants to update specified codes, he/she doesn't need to find the code in the whole file, so it will be good to maintain in the future.

**Comment by intellix** [comment]
I'm all for separated files :) was a bitch to update one large file whilst looking at the real source which is in lots of little files

**Comment by TonyPythoneer** [comment]
@intellix Yes, you know the feeling, too. 😄

**Comment by calebmer** [comment]
Ok then, I'm cool with it 😉

I was pretty neutral on the issue anyway. I just wanted to be thorough 👍

LGTM.

**Comment by TonyPythoneer** [comment]
@andy-ms Wow, you are so fast. Thanks!

**Comment by jucrouzet** [comment]
Hello,
The PR makes all the travis checks fails on DT since 2 hours (Ex https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/190991119 or https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/190987734)
@andy-ms could you please revert it asap ?

Thanks

**Comment by andy-ms** [comment]
@jucrouzet Instead, I'll fix the tester.

**Comment by jucrouzet** [comment]
Thanks !

**Pull request merged**
