### PR TITLE
Updated typings for change-case

### PR DESCRIPTION
**Pull request by wmaurer**
Added missing definitions: lcFirst & lowerCaseFirst

### CODE REVIEW

**Comment by vvakame** [comment]
@verticalpalette could you review this pull request?

**Comment by wmaurer** [comment]
Really, I simply added two function definitions, but the files looked like they changed more because I resorted the function names alphabetically.
Should I remove the resorting so that this simple PR can go through?

**Comment by vvakame** [comment]
oh, yes. yes please.

**Comment by vvakame** [comment]
thanks mate!

---
note
https://github.com/blakeembrey/change-case#usage
https://github.com/blakeembrey/change-case#lowercasefirst

**Pull request merged**
