### PR TITLE
[Styled-Components] Increase PERF 10x

### PR DESCRIPTION
**Pull request by christianalfoni**
Working on an improvement experience of typing with "stitches" I noticed that typing `keyof JSX.IntrinsicElements` is insanely costly. By rather using `string` through the typing and rather `extend` at the very end, we gain an insane performance boost.

The only downside to this is that the "as" prop is now typed as a string. But, I would argue that we do not need to type it as anything else, since it is just name of HTML elements. It will still throw an error if invalid as we `extend` it at the end. And the performance boost is such a huge improvement.

### CODE REVIEW

**Comment by christianalfoni** [comment]
I have no idea what is failing here? It seems unrelated to my changes?

**Comment by eps1lon** [comment]
Looks related to me. Is `master`failing as well for you locally? Did `npm run test` not fail for you locally?

**Comment by christianalfoni** [comment]
Hm, I am having a hard time understanding this: It references `styled-react-modal START`. Does this mean some other package breaks related to the changes I made? I can not see in the docs how I would go about figuring out these errors? Does the other packages use the definitely typed from the local repo? Also I get this when I try to test locally:

Screenshot 2020-08-02 at 21 03 39

I tested this locally updating the `d.ts` file directly, did not get any errors and it is a pretty straight forward change so I do not understand why it starts referencing `number´ (which is unrelated to my change), and also `color` was in there for some reason? 

A bit confused, so all help would be very much appreciated 😄

**Comment by mxstbr** [comment]
> The only downside to this is that the "as" prop is now typed as a string.

Just for clarification, does this mean one can no longer do this?

```JSX
<StyledComponent as={OtherStyledComponent} />
```

**Comment by MichaelDeBoey** [comment]
@mxstbr types are now:
```ts
C extends string | React.ComponentType<any>
```

So I think that's still possible because you can pass a `React.ComponentType`, no? 🤔

**Comment by christianalfoni** [comment]
> > The only downside to this is that the "as" prop is now typed as a string.
> 
> Just for clarification, does this mean one can no longer do this?
> 
> ```js-jsx
> <StyledComponent as={OtherStyledComponent} />
> ```
> 
> If that is the case, this should not be shipped as that's a feature that needs to be supported by the types.

This works as normal 😄  Cause it is `string | React.ComponentType`, so not messing with that. It is only that `as=""` does not give you intellisense for all possible HTML elements, it is typed as a string.

I just tested this on Codesandbox project and it is just insane how much it improves. Our typing basically did not work before this change... it took 2-3 seconds to get intellisense for anything in React

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d0a68c3c846dbe08ce386a807f9620bb26af0c63
</p>

**Comment by christianalfoni** [comment]
Ops, I found my mistake, quick fix. Is good now 😄 

Just to be explicit:

This change does not affect the `<SomeComponent as={SomeOtherComponent} />`, this typing has not been changed. It is only when you do `<SomeComponent as="" />`, inferring to string, where the typing has changed. Basically we give away the intellisense showing a list of all HTML elements on that prop and rather gain a HUGE performance boost. 

If you do write something like: `<SomeComponent as="bippetibo" />` you will still get an error though, so it is still type safe in that regard.

**Comment by JKillian** [comment]
Hi @christianalfoni, just wondering, do you have a demo and/or benchmarks available that show the performance changes this brings? It would be interesting to see some hard numbers for this, as [I know the TypeScript team has put a lot of work in to optimizing perf for styled-components in recent releases](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#speed-improvements).

**Comment by eps1lon** [comment]
@JKillian DTBot will soon post perf results. They didn't show up since CI was failing. Wait for https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=57892&view=results to complete

**Comment by JKillian** [comment]
> @JKillian DTBot will soon post perf results. They didn't show up since CI was failing. Wait for https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=57892&view=results to complete

Hmm, looks like the Bot may have flaked or something with posting a report? Reason I asked originally is because [the first perf report](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46510#issuecomment-667713181) didn't seem to show much difference, other than more memory usage. But I'm not sure if what it's testing is granular / accurate enough to show the improvement that @christianalfoni saw, so I was thinking perhaps a custom perf demo / numbers could be useful here.

**Comment by christianalfoni** [comment]
Yeah, I was super surprised the perf thingy did not show anything. Maybe this is more a VSCode thing? Here is a video showing... I tried my best to create something comparable. Kinda difficult :-)


https://www.youtube.com/watch?v=cbQYERG1F1Y&feature=youtu.be

Let me know if you can think of a better way to showcase it 😄

**Comment by rbuckton** [comment]
We're aware of performance issues related to using `keyof JSX.IntrinsicElements`. The downside of this change is that you can create a `StyledComponentProps<"some-random-string", ...` due to the weakened constraint, so a typo in the string wouldn't be caught at the declaration but instead you would end up seeing errors about `type 'X' is not assignable to 'never'` that would be hard to trace to the source. I'd rather defer to the maintainers as to whether this is a change they would consider.

**Comment by JKillian** [comment]
> We're aware of performance issues related to using `keyof JSX.IntrinsicElements`. The downside of this change is that you can create a `StyledComponentProps<"some-random-string", ...` due to the weakened constraint, so a typo in the string wouldn't be caught at the declaration but instead you would end up seeing errors about `type 'X' is not assignable to 'never'` that would be hard to trace to the source. I'd rather defer to the maintainers as to whether this is a change they would consider.

If the tradeoff here is a still-present-but-less-understandable error vs. significantly improved performance, I'd probably vote for the perf increase in this case. I expect the the factory functions, like `styled.div`, are a more common use case than using `StyledComponentProps<"some-string", ...>` and that errors with this wouldn't pop up too often.

I also defer to the more knowledgeable maintainers though - I don't have a full grasp on what specific cases see a perf increase vs. which don't, or the full type-checking implications of the change. But I suspect typing performance is probably a much bigger pain point for users than JSX element name typos of the above kind.

**Comment by eps1lon** [comment]
> If the tradeoff here is a still-present-but-less-understandable error vs. significantly improved performance, I'd probably vote for the perf increase in this case.

It would help if we could get @dt-bot to post benchmark results. If I understood https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=57892&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5 correctly then this change doesn't increase performance generally.

If we know that this change leads to a worse error message (which is a common frustration with TypeScript) but do not know the extend of the performance implications I'd rather choose the devil I know and not merge this PR.

But then I'm asking myself how common typos are when styling host components (which is basically what we're trying to prevent). If this almost never happens then an obscure error message might be ok if we get better perf for the 99%.

Do we still get completions for styled host component e.g. does `<Styled as="sec" />` show `section` in the completions?

**Comment by christianalfoni** [comment]
Thanks for all the considerations here 😄 

I agree with all the thoughts here, but want to point out that we are forced to change this typing at codesandbox.io cause the delayed typing is what puts us between "just writing the code" and "waiting for TS to catch up". So it would sad if this perf is lost, but maybe there is an other way developers could opt-in to this performance gain 🤔 

But to answer your question @eps1lon , doing: `<Styled as="sec" />` would not give any completions, that is the cost of the perf update. But the component would be typed as `never` and the whole thing becomes red as "sec" is not a valid `keyof JSX.IntrinsicElements`.

I would suggest trying it out by just pasting the code of this PR into `node_modules` and restart TS-Server. Kinda to build confidence in the improvement 😄

**Comment by eps1lon** [comment]
> I would suggest trying it out by just pasting the code of this PR into node_modules and restart TS-Server. Kinda to build confidence in the improvement smile

Sharing your benchmark would help a lot.

**Comment by christianalfoni** [comment]
@eps1lon The only way I could think of showing it was with the video above 😄 

I do not how the **dt-bot** benchmarks, but looking at the results it does not benchmark the developer experience change I experience through VSCode.

I just have no idea how to give any numbers on this? 😞

**Comment by eps1lon** [comment]
> I just have no idea how to give any numbers on this?

No numbers needed. A minimal repository with which you verified your work.

**Comment by rbuckton** [comment]
I was discussing this with @DanielRosenwasser and it seems this change dramatically increases the memory usage of styled-components by 40%, which does not seem like a reasonable trade-off. The result of this change is a significant increase in the number of conditional types created in any end-user library that uses styled-components, since we generate the union for `JSX.IntrinsicElements` once currently, but with this change we would have to create two new conditional types for every instantiation of `StyledComponentProps`.

**Comment by JKillian** [comment]
And the TypeScript bot did identify this issue [in its initial run of the perf metrics](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46510#issuecomment-667713181):

image

(Tangential sidenote: wonder why the bot categorizes this as: "It looks like nothing changed too much. I won’t post performance data again unless it gets worse." Is the bot's code on GH? I couldn't find it at a glance.)

Seems like it's unfortunately a no-go then @christianalfoni, unless there's a less memory-intensive way to get the speedup.

**Comment by christianalfoni** [comment]
Hm, interesting. But an increase of memory consumption... was it already high? Like... is the new memory consumption bad, or is it just that it increased and that is the only numbers we have to go by? Cause increased perf typically means more memory consumption. Sorry, I do not mean to be difficult, but the developer experience is so much better and I can throw a lot of memory on that ;-)

**Comment by andrewbranch** [comment]
For judging a developer’s editing experience, the perf bot is going to be far inferior to a human who’s paying attention. It’s there for the benefit of humans who are _not_ paying attention, so I’m inclined to trust @christianalfoni that the experience is better. The increased memory and assignability cache size are concerning, though, so I’d have to defer to @DanielRosenwasser’s judgment on that.

**Comment by mgcrea** [comment]
Working with typescript+styled-components is a painful slow experience today, I'd personally happily trade some RAM usage for a snappier feedback loop.

**Comment by orta** [comment]
Coming in fresh to this issue today. Feels pretty tied for merte/close.

The PR looks like a trade-off for a potential extra 40% of memory for a potential 10x speed increase. It's tricky because that though that doesn't seem to be showing up on the results (but they aren't quite indicative of using SC in a real project) and the video helps but isn't necessarily conclusive in a way that makes the memory increase obviously worth it.

Finally, we have both TS team & styled-components maintainers both for and against the merge. With a request on @DanielRosenwasser to take a final call.

My gut sense for adding to either side of whether it should be merged or not at this point, is to use these types in your own project (C&P the `index.d.ts` in @types/styled-components into your project) then do two things:

- Have both before/after results for a tsc run with `--diagnostics` added
- Give an opinion on the before/after feel for auto-completion like what @christianalfoni has done

**Comment by sandersn** [comment]
@DanielRosenwasser or @amcasey can you make a call on this one?

**Comment by sheetalkamat** [comment]
ping @DanielRosenwasser and/or @amcasey on your thoughts on taking this PR or declining it

**Comment by amcasey** [comment]
@sheetalkamat I would intuitively expect this to be a huge perf win.  If it's not showing up in the benchmarks, that probably just means the test coverage is not representative of real use cases.  As @rbuckton and others mentioned above, the real question is whether the worsened IntelliSense is an acceptable trade-off and only an experienced consumer of the library (which I am not) can evaluate that.

**Comment by mxstbr** [comment]
> The real question is whether the worsened IntelliSense is an acceptable trade-off and only an experienced consumer of the library (which I am not) can evaluate that.

In that case let me tie-break this: I am one of the creators and main maintainer of styled-components and would much rather have faster TypeScript performance than Intellisense for HTML elements when using the as-prop! 

I.e: let's ship this if you're okay with the change :blush:

**Comment by amcasey** [comment]
I'm sold.  @christianalfoni can you please clean up the merge conflicts and we'll get this in?

**Comment by markmcdermid** [comment]
Would we not get the best of both worlds if we could persuade `@types/react` to define an enum or a string union separately for the keys of `JSX.IntrinsicElements`?

**Comment by amcasey** [comment]
@markmcdermid While naming a type can make comparisons easier for the compiler, a lot of the performance cost comes from the size of that union.  I believe switching from a large union of string literals to just `string` was the primary perf win here.

**Comment by nfarina** [comment]
I just want to confirm that this PR makes a *major* difference in performance - like, for me `@types/styled-components` was unusable before. I wrote up a whole issue to illustrate the problem then actually tried this version and the problems went away. Before this patch, you could just type spaces into an editor with `styled-components` imported and watch the CPU stay at >100% and memory grow unbounded:

ezgif-2-16aba93a2bdc

Not so with this PR. I hope it can be merged soon so others can stop wondering why VSCode is so incredibly slow!

**Comment by orta** [comment]
I had some downtime during tsconf - this is now good to merge, and I'm gonna do it when it's green. 

Thanks everyone for providing feedback!

**Comment by mxstbr** [comment]
Huh interesting that the performance difference bot now caught a 30% increase in speed. I wonder what changed its mind 🤔

**Comment by robeady** [comment]
@christianalfoni @orta @mxstbr  apologies for bumping, but I am still seeing major performance issues with styled-components, whose cause seems similar to what this PR addresses.

As soon as I use `styled(Component)` rather than `styled.div`, typescript incremental compilation becomes 10x slower. It's so bad that I consider the library basically unusable with typescript at least on my machine.

Could a similar change to what was made in this PR fix the issue? I notice that if I navigate into the type definitions for `styled(Component)` it reaches `ThemedBaseStyledInterface`, which in turn refers to multiple types that include `keyof JSX.IntrinsicElements`.

Versions: typescript 4.3.5, @types/styled-components 5.1.12

**Comment by nfarina** [comment]
In case it helps anyone, I made a "lite" type definition file for Styled Components that ended up covering my personal use cases. Might allow you to get work done while waiting for an official fix:

  https://gist.github.com/nfarina/ea282fbb01574e95d87ce661f7fe8630

**Pull request merged**
