### PR TITLE
react: Disallow to pass every object as children

### PR DESCRIPTION
**Pull request by ddprrt**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stackblitz.com/edit/react-ts-q6xgam?file=index.tsx
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by ddprrt** [comment]
Btw. allowing any object to be passed as children creates real errors that blow up the application 😅 

Screenshot 2021-09-02 at 13 15 25

**Comment by dimitropoulos** [comment]
Can you please find the commit where this `{} |` was introduced?  I'd like to know if there was a rationale for doing so.

**Comment by KapitanOczywisty** [comment]
@dimitropoulos Introduced: #3813
Issues: https://github.com/microsoft/TypeScript/issues/26182 From this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37596 , https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35622 , https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49705 , https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29307
And rabbit hole continues from there

**Comment by ddprrt** [comment]
@dimitropoulos Sorry for the delay, I wasn't receiving any notifications. 
@KapitanOczywisty thanks for digging! I thought this is an issue that has been around for a while! I can't see the reasoning ... but I guess the reason why a change hasn't been applied yet is that it breaks a couple of other type definitions :-/

**Comment by ddprrt** [comment]
See #56026

**Pull request closed without merging**
