### PR TITLE
test(jest): Assert `it.each(…)` callback args are correct for tuples

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39291>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Favna** [comment]
Looks good but the tests are failing so I can't approve the changes just yet ¯\\\_(ツ)_/¯

**Comment by ExE-Boss** [comment]
The issue here is&nbsp;that **TypeScript&nbsp;3.0** doesn’t&nbsp;support&nbsp;tuples as&nbsp;the&nbsp;type of&nbsp;rest&nbsp;parameters, and&nbsp;**dtslint**&nbsp;doesn’t currently&nbsp;provide any&nbsp;easy&nbsp;way to&nbsp;limit certain&nbsp;assertions to&nbsp;only&nbsp;some **TypeScript**&nbsp;versions.

**Comment by Favna** [comment]
Can't we just header the typings with 3.1 then? 3.1 didn't introduce any breaking changes so I personally hardly see how, even enterprises (I'm in such a setting myself), cannot go from 3.0 to 3.1.

**Comment by ExE-Boss** [comment]
Closing in favour of #39291, which also contains this.

**Pull request closed without merging**
