### PR TITLE
[react] Make "type" button attribute match W3C spec

### PR DESCRIPTION
**Pull request by lukyth**
According to https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type, the `type` button attribute can only be one of the three keywords, `"submit"`, `"reset"`, and `"button"`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type
- [ ] Increase the version number in the header if appropriate.
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

I'm not sure how to deal with these two checklist.
> - [ ] Add or edit tests to reflect the change. (Run with `npm test`.)

> - [ ] Increase the version number in the header if appropriate.

This seems like a breaking change, but I don't know if that's appropriate or not. 😅

### CODE REVIEW

**Comment by ferdaber** [comment]
I don't know if this is a *great* idea, there are some issues with passthrough props where the literal type gets widened into string, thus causing odd errors. This is most definitely a big breaking change for application authors who have wrappers around the native button element.

**Comment by lukyth** [comment]
@ferdaber Thank you for your comment! I can kind of see the issue now :)

What do you think is required for this idea to work out? Would it be safe to assume that the breaking change is possible and application authors need to update their codebase somehow to use the new major version of `@types/react`?

**Comment by tkrotoff** [comment]
If it's not possible to make the change, would be nice to have something like:
```JS
// TODO Should be `'submit' | 'reset' | 'button'`,
// see [[react] Make "type" button attribute match W3C spec](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33648)
// This is a breaking change that cannot be done for the moment
type?: string;
```

**Comment by lukyth** [comment]
I've reverted the change and add a TODO as you suggested. :) @tkrotoff

**Comment by lukyth** [comment]
Is there a way to reopen this without opening a new PR? 😅

**Comment by ferdaber** [comment]
You can ask any of the maintainers of the DT repo to reopen this if you want to keep working on it.

**Comment by lukyth** [comment]
@ferdaber I want to keep working on this, but I'm not sure what else could be done at this point though.

@Jessidhia Could you please reopen this for me? Thank you so much :)

**Comment by Jessidhia** [comment]
Sure.

Also, it's perfectly fine to do "good break"s that make sure code is correct. No correct code should break with this change, and at worst things that blindly forward a `string` value to `type` will have to adopt the more strict annotation.

**Comment by ferdaber** [comment]
I trust @jessidhia’s word so let’s just go for it 🙆🏻‍♀️

**Comment by ferdaber** [comment]
@typescript-bot plsssss

**Comment by lukyth** [comment]
Seems like the bot wants me to open a new PR for this 😆

So I'll create a new version (`17.0.0`) that contains a more specific `ButtonHTMLAttributes['type']`. I'll get back to you all later.

**Comment by lukyth** [comment]
@Jessidhia @ferdaber 

According to [How do Definitely Typed package versions relate to versions of the corresponding library?](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library)

> the major and minor release numbers are aligned between library packages and type declaration packages

We can't create a new major version for this breaking change. Is that okay?

**Comment by ferdaber** [comment]
DT packages cannot follow semver for this reason, so if we have to make a breaking change then it just goes into a patch version.

**Pull request closed without merging**
