### PR TITLE
[types/noble] Add global namespace and option to some apis

### PR DESCRIPTION
**Pull request by yaeda**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L90
  - https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L129
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by yaeda** [comment]
oh, `callback` is better than `listener`...

**Comment by swook** [comment]
Thanks for your contributions @yaeda . Please add relevant tests to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/noble/noble-tests.ts to complete this pull request.

**Comment by yaeda** [comment]
Thank you for your reviewing! I updated test code.

**Comment by swook** [comment]
@yaeda thanks for this.

One last thing is, I'd rename the namespace as `noble` (instead of `Noble`) for backward compatibility. Here I'd like to ask the opinions of @wind-rider and @shantanubhadoria

**Comment by yaeda** [comment]
OK, I also think it has room for discussion.
I cannot find the style guide of the namespace. In fact, they are not unified in DefinitelyTyped/types. 

@wind-rider and @shantanubhadoria, how do you think about this?

**Comment by yaeda** [comment]
This is why I want to introduce the namespace.
https://gist.github.com/yaeda/3881d93bf57cac69f4258661fee98ad5
I think `Noble` is not so bad even from the backward compatibility point of view, 

I’m a newbie in TypeScript so please tell me if there are more good ways.

**Comment by aozgaa** [comment]
On balance, prefer a lower-case namespace name.

**Comment by yaeda** [comment]
@aozgaa Thanks for your comment, I followed your suggestion.
@swook, @wind-rider and @shantanubhadoria Could you review again?

**Comment by swook** [comment]
:+1:

**Pull request merged**
