### PR TITLE
Make @types/next Document generic for defining custom props.

### PR DESCRIPTION
**Pull request by gustofbreak**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I'm not familiar with writing these kind of testing code, so I didn't update that. Give me some guidance if necessary. Thanks.

### CODE REVIEW

**Comment by scottdj92** [comment]
Question: Why do you need this? Wouldn't this be handled via `getInitialProps`? Document is the main entry point of all next.js apps, and wouldn't be a child of any React component.

**Comment by gustofbreak** [comment]
@scottdj92 If I understand correctly, custom properties of the object returned from Document.getInitialProps can be injected into custom Document element as `this.props`. I indeed need this to insert server-side rendered CSS rules.

Roughly my code is like this.

```tsx
import Document, { Head, Main, NextScript } from 'next/document';
import React from 'react';

interface IMyDocumentProps {
  css: string;
}

export default class MyDocument extends Document<IMyDocumentProps> {
  public static async getInitialProps({ renderPage }) {
    // blah blah...
    return {
      // other props
      css: ssrCssRules,
    };
  }

  public render() {
    return (
      <html>
        <Head>
          <style>{this.props.css}</style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

If my approach is wrong, please let me know :(

**Comment by scottdj92** [comment]
Your approach isn't incorrect. I've done something similar before, and I'd prefer it if you could make that type a generic and have it extend from whatever getInitialProps returns

**Comment by armanio123** [comment]
@scottdj92 seems like you're waiting for changes, I'll keep it from merging until hearing from @gustofbreak . Let me know if you think otherwise.

**Comment by scottdj92** [comment]
@armanio123 I'd like to see some changes mentioned above

**Comment by gustofbreak** [comment]
> I'd prefer it if you could make that type a generic and have it extend from whatever getInitialProps returns 

@scottdj92 I'm not sure what you mean by "that type".

**Comment by scottdj92** [comment]
@gustofbreak can you update your code to the following:

export default class Document<T extends {} = T> extends React.Component<T & DocumentProps> {
    static getInitialProps<U>(ctx: NextDocumentContext): Promise<DocumentProps & U> | DocumentProps & U;
}
```

And see if that works for you? If that doesn't work, I think what you have now will suffice.

**Comment by gustofbreak** [comment]
@scottdj92 Oh, I see. I should have checked the signature of getInitialProps. I'm really a newcomer to TypeScript. Sorry for misunderstanding.

Your code works fine, but before I update, I want to make sure couple of points.

A. What's the difference between `<T = {}>` and `<T extends {} = T>`? I came to know generic constraints thanks to your code but I just want to make sure of it for some thoughts.

- The former one works fine.
- Isn't it implying what latter one achieve?
- app.d.ts is written as the former one, which I referenced.
- The latter one feels a little bit verbose to me.

B. I think `U` doesn't need to be different from `T`, since it is exactly what I'm trying to inject as additional props.

So here's my another draft. I appreciate your feedback. Thanks.

```tsx
export default class Document<T = {}> extends React.Component<T & DocumentProps> {
  static getInitialProps(ctx: NextDocumentContext): Promise<T & DocumentProps> | T & DocumentProps;
}
```

**Comment by gustofbreak** [comment]
@scottdj92 It was my mistake :( Everything worked fine because I was testing in my own project that uses the library and the declaration file was being excluded from type checking.

I tested in DefinitelyTyped project this time, but your version failed with tsc :(

```
test/next-document-tests.tsx:21:7 - error TS2417: Class static side 'typeof MyDoc' incorrectly extends base class static side 'typeof Document'.
  Types of property 'getInitialProps' are incompatible.
    Type '({ renderPage }: NextDocumentContext) => Promise<{ html: string | undefined; head: ReactElement<any>[]; errorHtml: string; chunks: { names: string[]; filenames: string[]; }; buildManifest: { [key: string]: any; }; style: {}; }>' is not assignable to type '<U>(ctx: NextDocumentContext) => (DocumentProps & U) |Promise<DocumentProps & U>'.
      Type 'Promise<{ html: string | undefined; head: ReactElement<any>[]; errorHtml: string; chunks: { names: string[]; filenames: string[]; }; buildManifest: { [key: string]: any; }; style: {}; }>' is not assignable to type '(DocumentProps & U) | Promise<DocumentProps & U>'.
        Type 'Promise<{ html: string | undefined; head: ReactElement<any>[]; errorHtml: string; chunks: { names: string[]; filenames: string[]; }; buildManifest: { [key: string]: any; }; style: {}; }>' is not assignable to type 'Promise<DocumentProps & U>'.
          Type '{ html: string | undefined; head: ReactElement<any>[]; errorHtml: string; chunks: { names:string[]; filenames: string[]; }; buildManifest: { [key: string]: any; }; style: {}; }' is not assignable to type 'DocumentProps & U'.
            Type '{ html: string | undefined; head: ReactElement<any>[]; errorHtml: string; chunks: { names: string[]; filenames: string[]; }; buildManifest: { [key: string]: any; }; style: {}; }' is not assignable to type 'U'.

21 class MyDoc extends Document {
```

Any thought?

**Comment by scottdj92** [comment]
You need to update the test if you update the type file. See `test/next-document-test.tsx`.

**Comment by RyanCavanaugh** [comment]
@scottdj92 does this PR need changes before being merged?

**Comment by scottdj92** [comment]
@RyanCavanaugh I don't have any additional feedback. I'd be ok with this being merged.

**Pull request merged**
