### PR TITLE
Ember: make `Mixin` exported in namespaced modules a `class`.

### PR DESCRIPTION
**Pull request by chriskrycho**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~Provide a URL to documentation or source code which provides context for the suggested changes:~ There isn't actually *documentation* of this per se; it's just making the re-export match the type it's re-exporting.
- ~Increase the version number in the header if appropriate.~
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by dwickern** [comment]
I think it was written this way for IDEs to autocomplete `Mixin`. Can we fix it in such a way that autocomplete still works?

**Comment by chriskrycho** [comment]
I’ll double check locally, but I think it should still work this way?

**Comment by chriskrycho** [comment]
@dwickern confirmed locally that the IDEs auto-import/autocomplete properly with the change I made.

**Review by dwickern — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Thanks @chriskrycho!

**Pull request merged**
