### PR TITLE
[react] Refacto aria attributes for svg

### PR DESCRIPTION
**Pull request by VincentLanglet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@weswigham @sandersn This PR was already approved (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34555) but the bot closed it.

I can't do nothing with the fake failed tests if the CI crash

**Review by eps1lon — APPROVED** [review]

**Comment by eps1lon** [comment]
> After 5 days, no one has reviewed the PR . A maintainer will be reviewing the PR in the next few days and will either merge it or request revisions. Thank you for your patience!

Forgot what actually worked but I usually create a new branch and change the last commit id to trick the bot.

**Comment by sandersn** [comment]
Sorry about the delay. I am trying to fix the CI crash. Please don't merge until it's fixed; I don't want this innocuous change to cause other, risky React changes to be merged without adequate testing.

**Comment by sandersn** [comment]
reactstrap is runs out of memory since 3.4 and since it depends on react, it runs as part of CI. I've got a partial solution and should have it ready some time today. Then we can re-open this and merge it.

**Comment by VincentLanglet** [comment]
@sandersn Every time you open this PR, the bot close it.
Did you fix the CI, should I create a new PR from now ?

**Comment by eps1lon** [comment]
> @sandersn Every time you open this PR, the bot close it.
> Did you fix the CI, should I create a new PR from now ?

Have you tried opening it from a new branch and with a new commit at the HEAD? As far as I know the bot as limited ability to detect copied PRs.

**Comment by VincentLanglet** [comment]
@eps1lon Nope, I didn't. Thanks for the advice.
Since it's already the second time I open the PR, I wait for an answer from @sandersn before doing it.

**Comment by sandersn** [comment]
I just merged master. Let's see if it works now.

**Comment by sandersn** [comment]
Looks good! I'll merge it.

Also, I'm going to turn off Travis next week if I don't find any more problems with Azure. So React PRs will be able to follow the normal workflow again.

**Pull request merged**
