### PR TITLE
Allow AMD/CommonJS loading of Cordova and Ionic Framework (shim)

### PR DESCRIPTION
**Pull request by Zorgatone**
Example:

```
import ionic = require("ionic")
```

### CODE REVIEW

**Comment by Zorgatone** [comment]
Without this PR typescript says module is not found.

This is usefull with AMD like RequirejS

**Comment by vvakame** [comment]
*cordova/cordova.d.ts*

author: Microsoft Open Technologies Inc. (account can't detected)

check list

* [ ] pass the Travic-CI test?

---

*ionic/ionic.d.ts*

to author(@spencerwi). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
*ionic/ionic.d.ts*

to author(@spencerwi). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---
note
https://git-wip-us.apache.org/repos/asf?p=cordova-cli.git;a=blob;f=cordova.js;h=687d74c99d3648893aa3d95ab097b3192a0e9496;hb=HEAD

**Comment by spencerwi** [comment]
Yep, looks good to me.

**Comment by Zorgatone** [comment]
::blush::

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
