### PR TITLE
React Native: Added `unstable_pressDelay` prop to `Pressable`

### PR DESCRIPTION
**Pull request by reichhartd**
# React Native: Added `unstable_pressDelay` prop to `Pressable`

https://reactnative.dev/docs/pressable#unstable_pressdelay

Exists according to the docs since `0.64.0`: https://reactnative.dev/docs/0.64/pressable#unstable_pressdelay

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactnative.dev/docs/pressable#unstable_pressdelay
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Please revert the unrelated formatting changes. They make reviewing this PR harder than it needs to be

**Comment by reichhartd** [comment]
@eps1lon According to checklist and the "Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes)" I should format the package with Prettier.
> Formatting: Use 4 spaces. Prettier is set up on this repo, so you can run npm run prettier -- --write path/to/package/**/*.ts.

So, should I still revert the changes?

**Comment by reichhartd** [comment]
I have fixed a bug in `styled-components`, otherwise the ci pipeline fails.
(https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59691/commits/7de4519d357f5cc13dddea8955b2857d2ba07f15)

Now it still fails because of `meteor`. But this is due to a dependency of the types of `mongodb`. I have already updated the dependency, but it still fails.
What is the best solution for this? `skipLibCheck` does not seem to work with `dtslint`.

````
Error in meteor
Error: Errors in typescript@4.7 for external dependencies:
Error: node_modules/mongodb/mongodb.d.ts(1792,97): error TS2344: Type 'TLocal' does not satisfy the constraint 'Document'.
Error: node_modules/mongodb/mongodb.d.ts(2595,99): error TS2344: Type 'TSchema' does not satisfy the constraint 'Document'.
Error: node_modules/mongodb/mongodb.d.ts(4082,99): error TS2344: Type 'TSchema' does not satisfy the constraint 'Document'.
```

**Review by eps1lon — APPROVED** [review]
Reviewing by commit looks fine. 

For meteor we need to wait for a relase of https://github.com/mongodb/node-mongodb-native/pull/3183. For styled-components we need to wait for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59551

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ca4685796c375e5944456a540ed507ae59097eb4
</p>

**Comment by reichhartd** [comment]
I've just read a lot of issues, but I can't figure out why the CI pipeline is failing.
It runs locally because I can install the dependencies here (in this case `csstype`).

I don't understand why this works with other packages like `react` with the ci pipeline, but not with `styled-component`.

```
Error in styled-components-react-native
Error: 
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.

Before you debug, first try running:

   npm install --prefix /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/styled-components

Then re-run. Full error logs are below.

Errors in typescript@4.7 for external dependencies:
Error: ../styled-components/index.d.ts(21,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
Error: ../styled-components/index.d.ts(29,18): error TS2430: Interface 'CSSObject' incorrectly extends interface 'CSSPseudos'.
  'string' index signatures are incompatible.
    Type 'string | number | CSSObject | undefined' is not assignable to type 'CSSObject | undefined'.
      Type 'string' is not assignable to type 'CSSObject'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:151:9)
```
@eps1lon Can you help me out?

**Comment by eps1lon** [comment]
Blocked by https://github.com/microsoft/DefinitelyTyped-tools/issues/422

**Review by chefgsaroar — APPROVED** [review]

**Comment by reichhartd** [comment]
Blocked by https://github.com/microsoft/DefinitelyTyped-tools/issues/413

**Pull request closed without merging**
