### PR TITLE
Add generics to d3.d.ts

### PR DESCRIPTION
**Pull request by gustavderdrache**
Round two (original PR was #3999); I made a bad merge and ended up having to rewrite history.

### CODE REVIEW

**Comment by mtraynham** [comment]
@gustavderdrache @hansrwindhoff I'd like to see this get resolved, as others are already opening PRs against D3 .  Can we discuss what's left, next steps?  Does this resolve any of the other [PRs](https://github.com/borisyankov/DefinitelyTyped/pulls?q=d3+is%3Aclosed+is%3Apr)

**Comment by gustavderdrache** [comment]
This PR covers the full d3.js API as of v3.5.5; most (if not all) of the other open PRs would be superseded by this one.

**Comment by vvakame** [comment]
@borisyankov @nestalk @danmane @abakirov could you review this PR? :+1: or :-1:

**Comment by grahamc** [comment]
:+1:

**Comment by gustavderdrache** [comment]
This pull request is getting really long in the tooth... what can we do to resolve it?

**Comment by vvakame** [comment]
@gustavderdrache wow, sorry! It merged. thanks mate.
@grahamc thanks!

**Comment by grahamc** [comment]
Woohoo! Thank you!

**Pull request merged**
