### PR TITLE
fixes #19554 Office js function overloads for optional parameters

### LINKED ISSUE #19554: Office.js methods with optional parameter should provide function overloads
- [X ] I tried using the `@types/office-js` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @OfficeDev

methods with optional parameter should provide more than one definition , one for each combiantion of parameters

like for `getAsync` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/38894f063d8711edebf1b846b34ba55d59a10577/types/office-js/index.d.ts#L1714

we could have
```ts
 getAsync(coercionType: CoercionType): void;
 getAsync(coercionType: CoercionType, options: AsyncContextOptions): void;
 getAsync(coercionType: CoercionType,  callback: (result: AsyncResult) => void): void;
 getAsync(coercionType: CoercionType, options: AsyncContextOptions, callback: (result: AsyncResult) => void): void;
```

this will enable writing more typesafe callback

typescript ref https://www.typescriptlang.org/docs/handbook/functions.html#overloads

### PR DESCRIPTION
**Pull request by abdulkareemnalband**
@OfficeDev

This package now can be compiled against typescript 2.5

### CODE REVIEW

**Comment by mhegazy** [comment]
@Zlatkovsky can you please review?

**Review by Zlatkovsky — CHANGES_REQUESTED** [review]
@abdulkareemnalband , thank you very much for your thorough commit!  I left quite a few comments, but hopefully they should be very simple to address.

@annich-MS , since most of these APIs are on the Outlook side, if you can take a look and/or do the edits yourself, that would be great.  Thanks!

**Comment by abdulkareemnalband** [comment]
@Zlatkovsky
I'm on vacation till Tuesday, so will work on it later

**Comment by Zlatkovsky** [comment]
Sounds good, thanks again for doing this.  Have a great vacation!

**Review by annich-MS — CHANGES_REQUESTED** [review]

**Comment by abdulkareemnalband** [comment]
Pushed changes as requested
Removed unused doc lines
Removed non callback overloads from get calls

**Review by Zlatkovsky — APPROVED** [review]
Looks good to me!  @abdulkareemnalband , thanks again for your work on this.

TypeScript team, please feel free to merge in.

**Review by annich-MS — APPROVED** [review]

**Comment by abdulkareemnalband** [comment]
@mhegazy @annich-MS Do you know why this PR is not merged/rejected yet?
We are waiting on this to upgrade `Typescript` in our project

Thanks again for reviewing

**Pull request merged**
