### PR TITLE
Fix incorrect module export declaration for noisejs

### PR DESCRIPTION
**Pull request by SardineFish**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/xixixao/noisejs/blob/b21feed054db415022d8109fa7013d55418f72e9/index.js#L325>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
@SardineFish 
the definition looks correct, to match UMD-like pattern in source code:
https://github.com/xixixao/noisejs/blob/master/index.js#L325-L331
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library

ES2015 imports are only part of the story here.
thanks!

**Review by amcasey — CHANGES_REQUESTED** [review]
Can you please explain what was wrong with the old exports?  They appear to match the underlying library.  In particular, `export as namespace` corresponded to the `global.Noise` line you linked in your description.  Thanks!

**Comment by notme1560** [comment]
I just ran in to this while trying to use the types. It seems like the published version on npm doesn't match the repo? This is how `index.js` of `noisejs` looks in my node_modules:

```js
(function(global){
  function Noise(seed) { ... }

  // ...

  global.Noise = Noise;
})(typeof module === "undefined" ? this : module.exports);
```

**Comment by amcasey** [comment]
@notme1560 I'm afraid I'm still missing something.  Can you please give an example of how you consumed the library and what problem(s) you encountered?  Thanks!

**Comment by SardineFish** [comment]
> Can you please explain what was wrong with the old exports? They appear to match the underlying library. In particular, `export as namespace` corresponded to the `global.Noise` line you linked in your description. Thanks!

The latest `noisejs` on npm is `2.1.0` which is actually export by `module.exports.Noise = Noise` that should not be export as namespace.
However the latest version on repo are `2.2.0` which is export by namespace but have not published to npm.

**Comment by amcasey** [comment]
@SardineFish Sorry, I'm not seeing that - can you please provide a link?  The code I'm looking at is [here](https://unpkg.com/browse/noisejs@2.1.0/index.js) and it has 

Line 325
```js
global.Noise = Noise;
```

Line 327
```js
typeof module === "undefined" ? this : module.exports
```

Those appear to match the exports that existed before your change.  I don't see `module.exports.Noise = Noise`.

**Comment by notme1560** [comment]
@amcasey If `module.exports` is defined, it passes `module.exports` to the IIFE, otherwise it passes `this`, which I guess is the global scope? Then inside the IIFE it does `global.Noise = Noise`, but `global` is the first parameter of the IIFE, so I think that is what SardineFish meant by `module.exports.Noise = Noise`.

**Comment by peterblazejewicz** [comment]
@SardineFish what about:
```ts
declare global {
    const Noise: NoiseConstructor;
}

export const Noise: NoiseConstructor;

interface NoiseConstructor {
    new (seed?: number): Noise;
}

interface Noise {
    simplex2(x: number, y: number): number;
    ...
    ...
}

export {};
```
I thinkk this looks to match this custom module exports.

**Comment by amcasey** [comment]
@SardineFish Sorry for the confusing feedback - I'd have to agree that @peterblazejewicz's proposal matches the library more closely than mine does.

**Comment by SardineFish** [comment]
@peterblazejewicz What is different between
```typescript
export const Noise: NoiseConstructor;

interface NoiseConstructor {
    new (seed?: number): Noise;
}

interface Noise {
    simplex2(x: number, y: number): number;
    ...
    ...
}
```
and 
```typescript

export class Noise {
    constructor(seed?: number);
    //...
}
```

**Comment by peterblazejewicz** [comment]
to be honest, none from usage point I think, a function with constructor function is same as a constructor in JS (I cannot recall quickly how to distinguish one from another at runtime, without prototype chain lookup). Literally, the symbol within module is not a class (pre-ES2015), so we can just re-assemble its features, with constructor function returning an instance with methods are behavior from interface.
It's your call here, we just wanted to have DT aligned with details of native module

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request closed without merging**
