### PR TITLE
fix(node): fix the params of clearInterval

### PR DESCRIPTION
**Pull request by mengFxing**
changing an existing definition
fix(node.timers):
fix the params of clearInterval
becouse the ReturnType&lt;typeof setInterval &gt; != Parameters&lt;typeof clearInterval&gt;
[url here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L72)

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Hey,
congrasts for your first contribution!
- you would have to modify tests for a types like `@types/node` due to package visibility
- those are identical, there is no real difference in TS. Not sure why two different were used in first place. Docs are using 'Timeout' 
What's the use-case you're fixing here?

**Comment by mengFxing** [comment]
@peterblazejewicz [peterblazejewicz](https://github.com/peterblazejewicz)
couse the ReturnType<typeof setInterval > != Parameters<typeof clearInterval>
- [ReturnType&lt;typeof setInterval &gt; == NodeJS.Timer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L73)
- [Parameters&lt;typeof clearInterval&gt; == NodeJS.Timeout](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L80)
- [interface Timeout extends Timer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L44)

**Comment by peterblazejewicz** [comment]
@mengFxing as Simon hinted, we can remove NodeJS.Timer and have only the NodeJS.Timeout (which is documented in docs). That would be better fix. I'd say this can be done only in current source (v18).

**Comment by mengFxing** [comment]
@peterblazejewicz [peterblazejewicz](https://github.com/peterblazejewicz)

I understand and I also prefer the second kind;
Two options：
- [Parameters&lt;typeof clearInterval&gt; == NodeJS.Timeout --&gt; NodeJS.Timer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L80)
- [ReturnType&lt;typeof setInterval &gt; == NodeJS.Timer --&gt; NodeJS.Timeout ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers.d.ts#L73)

**Pull request closed without merging**
