### PR TITLE
Change autoComplete to a string typing in React

### PR DESCRIPTION
**Pull request by rcchen**
autoComplete either takes "off" or "on", not a boolean.

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3  @vsiao @jbrantly could you review this PR?
@rcchen please fix travis ci failed.

**Comment by jbrantly** [comment]
The change itself looks good. :+1:

Regarding travis ci, that's not related to this PR. For example, see #6236 which also failed the build with the same error. I can't quite figure out where stuff started breaking there. My suspicion is #5869

**Comment by rcchen** [comment]
+1 would appreciate help in nailing down why the build is breaking; I tried identifying it yesterday and ended up in a bunch of libraries that I'm unfamiliar with/unsure why I touched with an optional property

**Comment by jbrantly** [comment]
@rcchen Yea it's definitely not your fault the build is breaking. It was already breaking before your change.

**Comment by pspeter3** [comment]
Are we sure that React does not convert the boolean into off and on?

**Comment by jbrantly** [comment]
@pspeter3 Per Facebook/React#1838 and [the source](https://github.com/facebook/react/blob/8e9682c542e08b4e5d019a3d93d86931bd36df0e/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L56) (notice no `HAS_BOOLEAN_VALUE`) it should be a string.

**Comment by pspeter3** [comment]
Awesome, lgtm then

**Comment by jbrantly** [comment]
@vvakame I think you can merge this as-is :+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
