### PR TITLE
Add react-native-sha1 typescript type

### PR DESCRIPTION
**Pull request by vanenshi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
index.d.ts requires a standard header comment like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4fa3c61b9c8f32877592fec6d1b89bfd3b5b9d5c/types/add-zero/index.d.ts#L1).

**Comment by shekari-ah** [comment]
> index.d.ts requires a standard header comment like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4fa3c61b9c8f32877592fec6d1b89bfd3b5b9d5c/types/add-zero/index.d.ts#L1).

thank you very much, I fix the problem and push again

**Review by vanenshi — COMMENTED** [review]
Fixed the problem

**Review by amcasey — APPROVED** [review]
Thanks for the update!

**Comment by shekari-ah** [comment]
Ready to merge

**Pull request merged**
