### PR TITLE
feat(pubnub): add new typings for Objects and signal

### PR DESCRIPTION
**Pull request by divyun**
Adds new typings for new PubNub SDK v4 features _Objects_ and _Signal_.

Additionally, formats the existing code with prettier.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Link to signal Doc](https://www.pubnub.com/docs/web-javascript/api-reference-publish-and-subscribe#signal) / [Link to Objects Doc](https://www.pubnub.com/docs/web-javascript/api-reference-objects)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by FlorianDr** [comment]
Hey @divyun, thank you for your pull request. It's great that you took sometime to bring the new functionalities. I quickly wanted to ask you, if the formatting happened on purpose? It's really hard to review the actual change with that amount of changed lines. Could we do the formatting in another PR? 

Thank you again for your contribution! It's awesome to have this stuff in.

**Comment by divyun** [comment]
@FlorianDr I heard you. I've split up the commit into two. I hope them being part of the same PR is fine.

1.  **https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38830/commits/7c6d5313883f67f72dddd7439ddadf0e7a3b08e5**: Formats using prettier
2. **https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38830/commits/6b40e7f4ca6c095dde70d53b376c519a6b64d41a** Does the following:
a. Adds typings for `signal`
b. Adds typings for `object`, there are various functions for the users, spaces and memberships.
c. I realized the statuses are same regardless of the operation so unified them. For example, all 5 properties are present if *Access Manager* is turned on and `secret key` or `authKey` is incorrect or missing.

**Comment by andrewbranch** [comment]
@FlorianDr would you mind taking another look? Looking at the non-formatting commit (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6b40e7f4ca6c095dde70d53b376c519a6b64d41a) seems like it should be easy to see what changed, but it could use a review from someone familiar with the library. Thank you!

**Review by andrewbranch — APPROVED** [review]
This seems reasonable to me. I spot-checked this for glaring issues but I’m not familiar with this library. I’ll give the owners one more day to voice any concerns; otherwise I’ll merge tomorrow. Thanks!

**Comment by divyun** [comment]
> Was `errorData` really not optional on `PublishStatus` or was this a mistake previously?

@andrewbranch errorData only shows up if error (Boolean) is true.

**Comment by divyun** [comment]
@andrewbranch Do you think this can be merged now?

**Comment by andrewbranch** [comment]
Ack, sorry for forgetting! Thanks for pinging me.

**Pull request merged**
