### PR TITLE
added referrerPolicy to AnchorHTMLAttributes in React types

### LINKED ISSUE #33226: [@types/react] HTML Anchor is missing `referrerPolicy` attribute
The `referrerPolicy` was added in https://github.com/facebook/react/issues/7263. But type definitions are missing them:
```tsx
<a href="/link" referrerPolicy="no-referrer">link</a>
```
yields an error:
```
Property 'referrerPolicy' does not exist on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'
```

### PR DESCRIPTION
**Pull request by saranshkataria**
Fixes #33226
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by ferdaber — APPROVED** [review]
Adding your name into the maintainer list is optional if you don't want to contribute in the future. Just a fair warning as one-time contributors can get frustrated by the number of issues that come in 😂

**Comment by saranshkataria** [comment]
Thanks for the heads up! 😆 
I hope I can keep up with them. If that will be a problem, I'll remove my name. 😄

**Comment by saranshkataria** [comment]
The build failure does not look like to have been because of my changes. Not sure what to do to get it fixed?

**Comment by saranshkataria** [comment]
cannot do anything, the build is not failing because of my changes

**Comment by pshrmn** [comment]
@saranshkataria can you rebase against `master`? I believe that #33381 fixed a number of other test errors.

**Pull request closed without merging**
