### PR TITLE
Change shown to visible

### PR DESCRIPTION
**Pull request by dalwadani**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jacklam718/react-native-popup-dialog#breaking-change
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by PaitoAnderson — CHANGES_REQUESTED** [review]
I agree with your changes, you just also need to update the test:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-popup-dialog/react-native-popup-dialog-tests.tsx#L75

**Review by PaitoAnderson — CHANGES_REQUESTED** [review]
Just update the version in the header to 0.16 excluding patch version. Thanks!

**Review by PaitoAnderson — COMMENTED** [review]
Shouldn't it be 0.16 instead of 16.0?

**Comment by dalwadani** [comment]
@PaitoAnderson,
Really appreciate your help

**Review by PaitoAnderson — APPROVED** [review]
LGTM

**Pull request merged**
