### PR TITLE
update project link of expressjs/cors 

### PR DESCRIPTION
**Pull request by gtpan77**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/expressjs/cors

### CODE REVIEW

**Review by pluma — APPROVED** [review]
lgtm, the old URL redirects to this new URL.

**Comment by pluma** [comment]
Yeah, that's why I've approved it. "lgtm" means "looks good to me" and is generally used to indicate approval.

For what it's worth, adding yourself as a definition author for fixing a URL in he metadata seems a bit excessive but I don't mind, just remember that this means you will likely get tagged by the bot in future pull requests for these typings just like I did.

If this is a hacktober contribution, enjoy your shirt I guess?

**Comment by gtpan77** [comment]
I apologise for adding me as an author. I was afraid before adding me as author because you are the sole contributor of this work. I have been contributing to open source for almost a month. I find open source very awesome and I want to go into depth of it. I'll promise I'll do my best to review and maintain all upcoming PRs. Thanks for your support for newbies like me!

**Comment by pluma** [comment]
No worries. I don't mind having other people share ownership of DT typings I've contributed. I usually create these when I run into missing typings in development, so I have no personal stake in them either way.

You're doing great.

**Review by rbuckton — APPROVED** [review]

**Comment by gtpan77** [comment]
Ready to merge

**Comment by gtpan77** [comment]
### Before  --

Screenshot 2020-10-07 at 8 41 08 PM

### After --

Screenshot 2020-10-10 at 11 49 53 AM

**Pull request merged**
