### PR TITLE
[react] Upgrade useInsertionEffect to next

### PR DESCRIPTION
**Pull request by eps1lon**
Closes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57554

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
   - https://github.com/facebook/react/pull/22589
- ~[ ]~ If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by latin-1** [comment]
I think it could be merged since it's already published at the next tag on npm. @eps1lon WDYT?

**Comment by eps1lon** [comment]
> I think it could be merged since it's already published at the next tag on npm. @eps1lon WDYT?

Forgot to mark as ready for review. Can be approved now if you think this is fine.

**Comment by amcasey** [comment]
LGTM, but let's give the other owners a bit more time.

**Review by latin-1 — APPROVED** [review]

**Review by johnnyreilly — APPROVED** [review]
Thanks! :christmas_tree:

**Comment by eps1lon** [comment]
Ready to merge

**Pull request merged**
