### PR TITLE
[node] Secure module names by default

### PR DESCRIPTION
**Pull request by turansky**
Union of #66681 and #66756

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Node documentation](https://nodejs.org/api/esm.html#node-imports)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### Motivation
* Main module definition with recommended name (with `node:` at start)
* Unlock priority reducing for old-style module names

#### Positive sideeffects
* ~~Secure auto imports in IntelliJ IDEA ([issue](https://youtrack.jetbrains.com/issue/WEB-57067))~~
  * UPD: Issue solved without `@types/node` actualization
  
### Next steps
* Discuss actualization in TypeScript Discord
  * New PR (if actualization won't be blocked)
* Reduce priority for old-style module names
  * Hints for `tsserver`?
  * `ReplaceWith` comments?

### CODE REVIEW

**Comment by jakebailey** [comment]
RE: the motivation on this one, it looks like the only reason for this change is that WebStorm/IntelliJ/etc can't auto-import both names.

`tsserver` definitely does this properly; is there a reason to create churn in the package to fix what could be called a bug in WebStorm's auto-import functionality? After all, the user may want to use either of them, or want to _not_  use `node:` prefixes, and this PR just flips the status quo over to `node:` for anyone using WebStorm and co. You're likely to get people complaining the _other_ way that their auto-imports don't import their preferred style anymore, so this isn't exactly an improvement.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
As suggested@jakebailey this is not the route we would be going with ~~infact we need to revert #66681~~ (missed the fact that we already reverted this)

**Comment by jakebailey** [comment]
> As suggested@jakebailey this is not the route we would be going with infact we need to revert #66681

Everything is all reverted at this point as of last night.

**Comment by Semigradsky** [comment]
> ...that their auto-imports don't import their preferred style anymore...

Things change 😄  By Node.JS doc using `node:` prefix is the preferred way, you can't find old-style import in examples.

**Comment by jakebailey** [comment]
This is true, but if it's breaking existing projects(per the other thread), then it doesn't feel like this is the right place to fix an editor bug unless there are other benefits.

(I do use `node:` everywhere in my projects, to be clear, but I am willing to bet most people do not...)

**Comment by turansky** [comment]
> but if it's breaking existing projects

@jakebailey In current PR contains 0 known breaking changes.
Problem with `inspector` reexport fixed.
If you see other problems - please write about ut.

**Comment by jakebailey** [comment]
https://github.com/timocov/dts-bundle-generator/issues/259 https://github.com/search?q=repo%3Atimocov%2Fdts-bundle-generator+%2Fexport+%5C*%2F&type=code

**Comment by jakebailey** [comment]
It's possible that you handled things better this time, but I think my point still stands that this isn't really the right fix for an editor bug, unless we definitely do our homework to ensure that projects still build. The tests here aren't enough, unfortunately. This is likely the _most important_ types package, so getting it right is important.

**Comment by turansky** [comment]
> https://github.com/timocov/dts-bundle-generator/issues/259, https://github.com/search?q=repo%3Atimocov%2Fdts-bundle-generator+%2Fexport+%5C*%2F&type=code, https://github.com/timocov/dts-bundle-generator/actions/runs/6212960177/job/16863603097

I checked imports in described tests - all of them works for me fine with this PR

**Comment by turansky** [comment]
> tsserver definitely does this properly

It recommends old-style import as recommended option :(
Recommended imports has lower priority in common case

**Comment by turansky** [comment]
> but I think my point still stands that this isn't really the right fix for an editor bug

@jakebailey I believe, that definitions - single fine place, where we can mark main/recommended namespaces and potentially mark old namespaces as non-recommended/outdated. 
And yes information about priorities will be shared between compilers and IDEs.

Old-style imports have higher priority in IDEs (VS Code, IDEA) and it doesn't look fine.

cc @gabritto

**Comment by jakebailey** [comment]
I would be greatly surprised if this order mattered to tsserver; I am much more likely to believe that it's the length of the import that makes it preferred by the editor, not how it's declared. `assert` is shorter than `node:assert`, no matter what.

**Comment by turansky** [comment]
> `assert` is shorter than `node:assert`, no matter what.

After this PR it will be possible to mark `assert` without sideeffect for `node:assert` :)

**Comment by sgrishchenko** [comment]
@jakebailey The idea behind the lower priority of re-exported module is that re-exports are often used for backward compatibility, but most actual declarations are pleased in the original module/namespace. 

Often, if a module has a longer name, it doesn't necessarily mean that it is more relevant. E.g. there was `babel-core` module, but the Babel team realized that using of npm organizations provides additional certainty to check the fact that the published module is official. So they decided to republish this module as `@babel/core`. As you can see, the new module name is longer (by one char) but is safer, so it should have higher priority for import.

Also, using of secure module by default is a good demonstration of the fact that it is the recommended way to use Node modules now. So it is not a fix for IDEs, it is an actualisation of typings. The fact that auto-import in IDEs will be improved is a positive side effect of this change, nothing more.

**Comment by peterblazejewicz** [comment]
I'd love to have all secure import, it would fix a lot of `require('buffer')` and similar dramas, but I agree with @jakebailey, it should stay as is. 
We can promote phasing out this gradually (new modules > 'node:*' only, etc)

**Comment by jakebailey** [comment]
If there are other good reasons to do this, and we can definitely be sure that we don't break things, then I am not against it. It just broke me and at least one other person. I haven't had the time to test this PR against my code but I plan to do so when I have some time.

I don't want to be the blocker to progress; I just think the motivation of the original change is not really a good one. A reasonable editor experience should be able to handle both, because there's lots of code out there that writes it both ways, or still (unfortunately) targets old versions of Node.

**Comment by peterblazejewicz** [comment]
> I support your idea about graceful migration to new module names, but if we use your strategy, we will never rich the point were `fs` module declared just for the sake of backward compatibility. What if we swap module names one by one in separate PRs?

Still, this is not a Sunday walk kind of problem (due ot nature of @types/node). Please try to get TS folks input on this via dicord TS #definitelytyped channel

**Comment by timocov** [comment]
Hi there, I'm the maintainer of `dts-bundle-generator` tool and I finally found some time to analyze what caused https://github.com/timocov/dts-bundle-generator/actions/runs/6212960177/job/16863603097 and https://github.com/timocov/dts-bundle-generator/issues/259. In my particular use-case I'd say that the issue is in the tool itself as it doesn't handle re-exports precisely - the tool goes via all files in the compilation and checks every single node in it for whether it should be imported or not, and if node A should be imported, it looks for source files where this node A is used and tries to find `import` statement(s) that was used to import that node A so the generated file would contain import statements you use in your project. In addition, the tool has a configuration that allows you to specify what packages are allowed to be imported (so you won't get anything you don't expect to see). In the failed tests one of the allowed packages are `fs` and `events` (and they are imported via `fs` and `events` packages accordingly). Now, the actual problem is that the tool goes over _source_ nodes and doesn't consider re-exports (`export =` in this case, which with `declare module` "introduces" a new module which doesn't contain any nodes, just re-exports). So as the result, it sees a used node from `node:events` module, but only `events` imported module is allowed and it is being ignored.

There are several workaround for this while using the tool:
- you can add `node:events` to allowed list of imported packages
- you can change imports from `events` to `node:events`

I'll try to look if it would be possible to handle this particular re-export approach, but these changes look legit for me. But I appreciate that if any other tool makes similar assumptions as `dts-bundle-generator` does, they would probably need to make some changes to make it work.

Don't know if it is helpful or gives you any new information 😂

**Comment by jakebailey** [comment]
FWIW I do plan on retesting this; I haven't forgotten about it, but other big DT infrastructure changes have preempted spending time on this.

**Pull request closed without merging**
