### PR TITLE
material-ui - updated definitions for v0.12.1

### PR DESCRIPTION
**Pull request by use-strict**

### CODE REVIEW

**Comment by use-strict** [comment]
@ngbrown, can you review this?

**Comment by ngbrown** [comment]
@use-strict 

In `ThemePalette`, there is now an `alternateTextColor` and `canvasColor` has been removed.

With the new ThemeManager, the call to `getMuiTheme(rawTheme: RawTheme)` none of the fields in `RawTheme.palette` or `RawTheme.spacing` are optional.  The application breaks if they are left out.  I'm not sure how to correlate that with the `modifyThemePalette()` and `modifySpacing()` having those same fields be optional.

**Comment by use-strict** [comment]
@ngbrown, I added the ```alternateTextColor``` property. ```canvasColor``` is still referenced in ```theme-manager.js```, so I didn't remove it. Made the ```spacing``` property mandatory. I'm not sure what you mean about ```modify*()``` methods.

**Comment by ngbrown** [comment]
@ngbrown looks good :ship:

**Comment by subjectix** [comment]
very nice :+1: thank you

**Comment by use-strict** [comment]
@vvakame , can you merge this?

**Comment by vvakame** [comment]
sure, thanks mate!

**Comment by subjectix** [comment]
@vvakame Thanks for merging this, I love it <3 <3

**Pull request merged**
