### PR TITLE
[DRAFT] @types/chess.js - Update missing types

### PR DESCRIPTION
**Pull request by MrBr**
As per chess.js@0.13.4

https://github.com/jhlywa/chess.js/blob/master/README.md

I'll go through requirements, just opening a draft.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Review by vicary — APPROVED** [review]
LGTM

**Review by vicary — CHANGES_REQUESTED** [review]
One question.

**Comment by MrBr** [comment]
@vicary you're right, I messed it up. Will add tests and go once more through it

**Comment by MrBr** [comment]
@vicary I've added tests but couldn't run them locally. I am getting the error:

```
Could not find implementations for the following rules specified in the configuration:
    no-bad-reference
```

Patch versions are controlled by the CLI how much I figured, if so PR should be fine now to merge.

**Comment by vicary** [comment]
The changes looks fine.

Running in my local machine gives even more errors, but as far as Github shows all green, I'm good with it.

<details>
<summary>Click to show logs</summary>

```
Error: 
~/DefinitelyTyped/types/chess.js/chess.js-tests.ts
  1:1  error  Definition for rule 'dt-header' was not found              dt-header
  1:1  error  Definition for rule 'export-just-namespace' was not found  export-just-namespace
  1:1  error  Definition for rule 'no-bad-reference' was not found       no-bad-reference
  1:1  error  Definition for rule 'no-useless-files' was not found       no-useless-files

~/DefinitelyTyped/types/chess.js/index.d.ts
  1:1  error  Definition for rule 'dt-header' was not found              dt-header
  1:1  error  Definition for rule 'export-just-namespace' was not found  export-just-namespace
  1:1  error  Definition for rule 'no-bad-reference' was not found       no-bad-reference
  1:1  error  Definition for rule 'no-useless-files' was not found       no-useless-files

✖ 8 problems (8 errors, 0 warnings)
```

</details>

**Review by vicary — APPROVED** [review]

**Comment by MrBr** [comment]
Ready to merge

**Pull request merged**
