### PR TITLE
Type definitions for for the JSF 2.0 Ajax request API

### PR DESCRIPTION
**Pull request by larmic**
Based on https://docs.oracle.com/cd/E17802_01/j2ee/javaee/javaserverfaces/2.0/docs/js-api/symbols/jsf.ajax.html

### CODE REVIEW

**Comment by larmic** [comment]
Hi,

https://travis-ci.org/ButterFaces/DefinitelyTyped passed.

JSF is part of Java Enterprise Development and has no bower oder node package at this time. It comes from Oracle with a specification (https://docs.oracle.com/cd/E17802_01/j2ee/javaee/javaserverfaces/2.0/docs/js-api/symbols/jsf.ajax.html).

**Comment by vvakame** [comment]
umm... jsf is already exists on npm. I think `oracle-jsf` is better...

**Comment by larmic** [comment]
https://www.npmjs.com/package/jsf was created two month ago. But i can rename it to oracle-jsf if you want to.

Should I send another pullrequest?

**Comment by larmic** [comment]
I've renamed it to jee-jsf.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
