### PR TITLE
	Added Artyom.js TypeScript type definition file

### PR DESCRIPTION
**Pull request by semagarcia**
Please fill in this template.

- [ X ] Make your PR against the `master` branch.
- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ X ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

### CODE REVIEW

**Comment by andy-ms** [comment]
You need to run `npm run new-package artyom.js` to generate the correct package structure.

**Comment by semagarcia** [comment]
Thanks @andy-ms, but this command gave me the following output:

`sema@my-laptop:~/Workspace/DefinitelyTyped$ npm run new-package artyom.js
npm ERR! Linux 4.8.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "new-package" "artyom.js"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! missing script: new-package
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sema/Workspace/DefinitelyTyped/npm-debug.log
`

**Comment by andy-ms** [comment]
That's strange, it works fine for me. Can you confirm that `~/Workspace/DefinitelyTyped` is checked out to the latest master branch and contains [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/package.json) `package.json`? NPM should see the `"scripts"` there and run the associated command.

**Comment by semagarcia** [comment]
Thanks for your tip @andy-ms. That works!

**Comment by semagarcia** [comment]
Deleted the branch and writting changes into "types-2.0" branch following the instructions (create package with new-package and so on).

**Comment by andy-ms** [comment]
Don't use `types-2.0`. We only accept pull requests to `master` now.

**Comment by semagarcia** [comment]
Ok, thanks and sorry for the inconvenience.

**Pull request closed without merging**
