### PR TITLE
Fix/update editorconfig

### PR DESCRIPTION
**Pull request by ZaneHannanAU**
* Adds `*.ts` to the `.editorconfig` file.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ZaneHannanAU** [comment]
... oops

**Comment by ZaneHannanAU** [comment]
... okay what's with parity-pmr/parity-poe?

... oh $ExpectError expects an error on this line.... wat

**Comment by Flarna** [comment]
Regarding parity-pmr/parity-poe see #28833 and #28831

Not sure if it is a good idea to mix a node change with a global change editorconfig in one PR.

**Comment by ZaneHannanAU** [comment]
… I didn't mean to; and actually I had actually tried to switch branches so it wouldn't conflict…

… idk how to git

**Review by Flarna — CHANGES_REQUESTED** [review]
Please split the node and editorconfig changes into two PRs.

**Comment by ZaneHannanAU** [comment]
Will it just be easier to close this and open a new one with github branch?
… I think so.

**Comment by ZaneHannanAU** [comment]
@Flarna did on #28931

**Pull request closed without merging**
