### PR TITLE
[pino] Add missing types for pino-pretty

### PR DESCRIPTION
**Pull request by dunklesToast**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino-pretty/tree/v4.4.0#Options
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## pino ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pino@latest/))
was missing the following properties:
1. pino
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7846ea21611b5d531a0149eef22f5bede1146804
</p>

**Comment by paambaati** [comment]
@dunklesToast Thanks for the PR!

I don’t see these new properties documented in `pino` though; in fact, one of the properties included in this PR - `levelKey` - has been deprecated for a while now - see https://github.com/pinojs/pino/blob/master/docs/api.md

**Comment by dunklesToast** [comment]
Hey @paambaati ,

the properties come from [pino-pretty](https://github.com/pinojs/pino-pretty) which ships with Pino as you can read [here](https://github.com/pinojs/pino/blob/master/docs/pretty.md) under API Example 

> Note: the default prettifier module is pino-pretty, so the preceding example could be

`levelKey` is deprecated for sure, but since it'll be removed in v7 I guess it should stay in these types.

**Comment by paambaati** [comment]
@dunklesToast 

> the properties come from pino-pretty 

In that case shouldn't these changes be submitted as types for `@types/pino-pretty`?

**Comment by dunklesToast** [comment]
I askes myself the same but since they were already in the Pino Package I just extended them. I could take a look if you want me to create a seperate types-package for pino-pretty

**Comment by dunklesToast** [comment]
Any idea how to do it @paambaati ?

**Comment by paambaati** [comment]
@dunklesToast This information is available in the README - see https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by dunklesToast** [comment]
Okay I just wasn't sure if I should create a new package for pino-pretty or if we're gonna leave them where they currently are. Then I'll see what I can do.

**Review by screendriver — APPROVED** [review]
-

**Review by screendriver — CHANGES_REQUESTED** [review]
I would also introduce dedicated types for pino-pretty

**Comment by dunklesToast** [comment]
Ready to merge

**Pull request closed without merging**
