### PR TITLE
angularjs - better granularity for filter service parameter types

### PR DESCRIPTION
**Pull request by use-strict**

### CODE REVIEW

**Comment by vvakame** [comment]
@use-strict thanks mate!

**Comment by albv** [comment]
@vvakame this commit broke support for all filters except 'filter' (https://code.angularjs.org/1.4.2/docs/api/ng/filter/filter), consider https://code.angularjs.org/1.4.2/docs/api/ng/filter/date for example. I think there is no way to establish a strict interface for IFilterFunc, it could be anything.

**Comment by use-strict** [comment]
@albv , I'll have a fix for this tomorrow. Can be solved with overloads to cover all filter types.

**Comment by btesser** [comment]
Please revert this.  It breaks string filters

**Comment by albv** [comment]
wasn't aware that TypeScript allows overloads by argument values, nice trick @use-strict, thanks

**Comment by btesser** [comment]
@use-strict @baltie @albv.  In testing this I've found that it breaks any filter that isn't explicitly defining the generic.  Any chance you can submit a pr that makes the use of generics optional.  Also from what I've seen the string overloads are not working correctly with typescript 1.6.2

**Comment by btesser** [comment]
@albv @use-strict from the typescript docs regarding how overload call signatures work:
> Functions with specialized overload signatures (those that use string literals in their overloads) do not use their specialized signatures when checking for compatibility.

**Pull request merged**
