### PR TITLE
feat(lodash-es): Export supporting types DebouncedFunc, DebounceSettings and ThrottleSettings

### PR DESCRIPTION
**Pull request by swese44**
Exports supporting types `DebouncedFunc`, `DebounceSettings` and `ThrottleSettings`, which we need to import from another project.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## lodash-es ([<kbd>unpkg</kbd>](https://unpkg.com/browse/lodash-es@latest/))
was missing the following properties:
1. chain
1. commit
1. lodash
1. next
1. plant

<details>
<summary>as well as these 15 other properties...</summary>
<p>tap, thru, toIterator, toJSON, value, valueOf, wrapperAt, wrapperChain, wrapperCommit, wrapperLodash, wrapperNext, wrapperPlant, wrapperReverse, wrapperToIterator, wrapperValue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1de9ee3241ad5ae925f38822888e5617c2bfa7f9
</p>

**Comment by swese44** [comment]
Hello @stephenlautier or @e-cloud, could I get a review? Thanks!

**Comment by swese44** [comment]
Ping @stephenlautier or @e-cloud, thanks!

**Comment by swese44** [comment]
@typescript-bot can we move this forward?

**Review by stephenlautier — APPROVED** [review]

**Comment by swese44** [comment]
Ready to merge

**Pull request merged**
