### PR TITLE
[cesium] Add `properties` property in Entity constructor

### PR DESCRIPTION
**Pull request by fc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://cesium.com/docs/cesiumjs-ref-doc/Entity.html?classFilter=entity

### CODE REVIEW

**Comment by fc** [comment]
@Zuzon @hnipps @szechyjs @golyalpha @KeyboardSounds @soyarsauce @jrafidi @Crocsx

**Review by Crocsx — CHANGES_REQUESTED** [review]
Thanks for the PR,

You current change are not adding types, this will not help.

You have to Manually add a class for PropertyBag and replace the any with your newly created property :

https://cesium.com/docs/cesiumjs-ref-doc/PropertyBag.html

If you have no time, and just want to change the constructor, then I believe just adding 
`properties: any;` is better



Thank you

**Comment by fc** [comment]
> Thanks for the PR,
> 
> You current change are not adding types, this will not help.
> 
> You have to Manually add a class for PropertyBag and replace the any with your newly created property :
> 
> https://cesium.com/docs/cesiumjs-ref-doc/PropertyBag.html
> 
> If you have no time, and just want to change the constructor, then I believe just adding
> `properties: any;` is better
> 
> Thank you

I currently do not have the time.  Throughout the type definition file, it is implemented the same way I have done though so I intentionally made it this way to be consistent with that.

**Comment by Crocsx** [comment]
@fc you right, I didn't see all those `// PropertyBag`, well I guess it's correct for the moment then. I will add that part as I don't like seeing all those `// PropertyBag`

**Review by Crocsx — APPROVED** [review]

**Comment by Crocsx** [comment]
@fc I applied your change here : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42782 Thank you for pointing this out

**Review by Crocsx — CHANGES_REQUESTED** [review]
no need to merge

**Pull request closed without merging**
