### PR TITLE
[merge-images] Update types to 1.2

### PR DESCRIPTION
**Pull request by BendingBender**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/lukechilds/merge-images/compare/v1.1.0...v1.2.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by BendingBender** [comment]
@laurensnl You can sign off on this PR if you want.

**Review by k-yle — APPROVED** [review]

**Comment by laurensnl** [comment]
> @laurensnl You can sign off on this PR if you want.

Thanks for updating the types @BendingBender! Looks great! Not sure if I can sign off this PR though.

**Comment by BendingBender** [comment]
Just make a review and approve the changes. This seems to be enough according to what typescript-bot suggests.

**Review by laurensnl — APPROVED** [review]

**Comment by BendingBender** [comment]
Ready to merge

**Comment by laurensnl** [comment]
> Just make a review and approve the changes. This seems to be enough according to what typescript-bot suggests.

Done! Thanks for updating these types!

**Pull request merged**
