### PR TITLE
Add optional arguments for init and willDestroy

### PR DESCRIPTION
**Pull request by mfeckie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://emberjs.com/api/ember/3.7/classes/CoreObject/methods/init?anchor=init and https://emberjs.com/api/ember/3.7/classes/CoreObject/methods/init?anchor=willDestroy
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by buschtoens** [comment]
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31481?

**Review by mike-north — CHANGES_REQUESTED** [review]
@mfeckie we need a better indication of whether the arguments passed to `init` and `willDestroy` are part of Ember's public API. The API docs represent them as zero-argument functions.

#31481 has a relevant discussion for a nearly identical change

**Comment by mfeckie** [comment]
I've linked to the documentation where it says 'always call super' for
init.

I can remove `willDestroy` which is not explicit.

Would that address the issue?

**Comment by mfeckie** [comment]
So the vibe I'm getting is there's no path this PR being acceptable.  So I guess I should close it?

**Comment by mike-north** [comment]
> So the vibe I'm getting is there's no path this PR being acceptable. So I guess I should close it?

As it stands, I can see how the changes you're seeking to make are in alignment with Ember's public API.

You could either

A) Lobby the core team and seek to surface any arguments you care about as part of the public API. 
B) Close this PR and possibly be ok with using `super.init()` and `super.willDestroy()` in situations where you know there are no arguments to pass along

**Comment by mfeckie** [comment]
Closing this due to the lack of a path to marging.

**Pull request closed without merging**
