### PR TITLE
feat: implement types for `number-oddoreven` package

### PR DESCRIPTION
**Pull request by ArthurKa**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by elibarzilay** [comment]
I had a look at the library, and it seems that you're one of its authors -- in that case, and especially given the style of that code, it would be best to add the types directly there.

**Comment by peterblazejewicz** [comment]
on the subject:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by ArthurKa** [comment]
See... I just made one simple PR and accidentally become a contributor. I'm not a maintainer of that repo. Just a volunteer to cover simple function with type definitions. ¯\\\_(ツ)_/¯

**Comment by andrewbranch** [comment]
Hm, nothing against joke packages on npm, but having typings for them on DT takes up human and compute resources, so I’m leaning towards closing this. @ArthurKa, is there, uh, a non-joke reason to have this?

**Comment by ArthurKa** [comment]
Nope. I just thought [is-odd](https://www.npmjs.com/package/is-odd) already has one, so does [is-even](https://www.npmjs.com/package/is-even), so why not `oddoreven`. But if not, so not:) At least I tried.

**Comment by andrewbranch** [comment]
I mean `is-odd` and `is-even` are amusing reflections of the JS ecosystem, but whatever you think about their existence, they are implemented with some level of seriousness and apparently have actual dependents. `number-oddoreven` is literally a meme: https://unpkg.com/number-oddoreven@1.0.5/index.js

```js
const none                                  =
require                                     (
'none'                                      )
                                            ; // this makes the program load faster!
var throwErr                                =
require                                     (
'is-number'                                 )
                                            ; // we are using var instead of const for speed!
const isNum                                 =
require                                     (
'throw-error'                               )
                                            ;
const True                                  =
require                                     (
'false'                                     )
                                            ;
var Oof                                     =
require                                     (
'If'                                        )
                                            ; // named oof so that it doesn't get confused with regular js if
var Camelcase                               =
require                                     (
'camelcase'                                 )
                                            ;
var sleep                                   =
require                                     (
'system-sleep'                              )
                                            ;
var log                                     =
require                                     (
"log"                                       )
                                            ; // just in case we need it later
const chalk                                 =
require                                     (
'chalk'                                     )
```

I think we all had a good chuckle but there’s no need to merge it.

**Pull request closed without merging**
