### PR TITLE
Revert "Fix item types for @types/steam-tradeoffer-manager"

### PR DESCRIPTION
**Pull request by kjsmita6**
Reverts DefinitelyTyped/DefinitelyTyped#67150

@Nicklason this commit is not correct because BaseItem doesn't extend CEconItem as well. Partially my fault for not checking this against my own code. I mentioned this in the old one, but https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/EconItem it says this is identical to CEconItem. So now my code that says

```js
offer.itemsToReceive.forEach(item => {
                if (item.appid == 440 && item.market_hash_name === 'Mann Co. Supply Crate Key') {
```

doesn't compile anymore because `market_hash_name` doesn't exist.

### CODE REVIEW

**Comment by jakebailey** [comment]
The failure was just fixed on master, you should be able to merge to fix CI.

**Review by kldzj — APPROVED** [review]

**Comment by Nicklason** [comment]
It makes sense that you get an error because typescript does not know if it is an econ item or an item with just the 4 required properties to create offers. The problem is that the items you add to the offer only requires 4 properties but for a sent offer then it will be replaced with econ items. I think the best solution is to tell typescript that you know what type the items are, maybe using ‘satisfies’ but I have not tested this. I just wanted to give my thought before you decide to revert it.

**Comment by kjsmita6** [comment]
> The problem is that the items you add to the offer only requires 4 properties 

This is true, but I don't believe it's recommended to create items manually. Normally you only add items if you are loading an inventory first. For example, I want to send a trade offer to player Foo. I load my inventory, filter for the items I want to add, and add them. Then I can also load Foo's inventory and do the same. I would never add an item like 

```js
offer.addMyItem({
    appid: 440,
    contextId: 2
    ...
});
```

So we can work on this in the future, but for now I think this needs to be reverted because it is breaking existing code.

**Comment by kldzj** [comment]
> The failure was just fixed on master, you should be able to merge to fix CI.

@kjsmita6 if you merge master I'll approve and we can get this published asap.

**Comment by kjsmita6** [comment]
Ready to merge

**Pull request merged**
