### PR TITLE
node crypto sign should accept a private key in jwk format

### PR DESCRIPTION
**Pull request by omkelderman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/crypto.html#signsignprivatekey-outputencoding and https://nodejs.org/api/crypto.html#cryptosignalgorithm-data-key-callback
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

---

I've also taken the liberty of adding some extra code to the test file that includes the crypto.verify function on jwk objects. This was already in the type definitions (and what I used as inspiration for the new ones I added), but figured it couldnt hurt to add some tests for those as well.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/crypto.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9edbd375c691774184cde8e70049d900269530d2
</p>

**Comment by jakebailey** [comment]
This seems like it could be applied to the other versions of the node types in the versioned directories, correct?

**Comment by omkelderman** [comment]
oh I didnt even realize those versioned directories existed, missed those earlier. These changes do apply to those versions of node (just double checked), so I've copied over my changes to those directories as well.

**Comment by jakebailey** [comment]
This sort of thing is very common on DT, especially when contributing to then Node types, which are depended on by thousands of packages. All of them must pass for any PR to go in.

This is failing on master (https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/9956462624) so I'm going to be looking into fixing that now.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/v18/crypto.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cf83bdd61b79a948c3320e3e69708d9648d47f58
</p>

**Review by jakebailey — APPROVED** [review]

**Comment by omkelderman** [comment]
Ready to merge

**Pull request merged**
