### PR TITLE
[indy-sdk] fix(indy-sdk): fix revocation types

### PR DESCRIPTION
**Pull request by TimoGlastra**
I encountered some issues with the revocation types in AFJ.

@jameskebert do these changes look good to you. It wouldn't compile for me without these changes, and was already what was being used in AFJ

DO NOT MERGE UNTIL SIGNED OFF BY JAMES

Signed-off-by: Timo Glastra <timo@animo.id>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x]Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hyperledger/indy-sdk/tree/master/wrappers/nodejs
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## indy-sdk ([<kbd>unpkg</kbd>](https://unpkg.com/browse/indy-sdk@latest/))
was missing the following properties:
1. capi
1. setRuntimeConfig
1. setDefaultLogger
1. setLogger
1. issuerRotateCredentialDefStart

<details>
<summary>as well as these 75 other properties...</summary>
<p>issuerRotateCredentialDefApply, proverGetCredentials, proverSearchCredentials, proverFetchCredentials, proverCloseCredentialsSearch, proverDeleteCredential, updateRevocationState, toUnqualified, setKeyMetadata, getKeyMetadata, cryptoAuthCrypt, cryptoAuthDecrypt, cryptoAnonDecrypt, replaceKeysStart, replaceKeysApply, storeTheirDid, keyForDid, setEndpointForDid, getEndpointForDid, setDidMetadata, getDidMetadata, getMyDidWithMeta, listMyDidsWithMeta, qualifyDid, submitAction, multiSignRequest, buildGetDdoRequest, buildAttribRequest, buildNodeRequest, buildGetValidatorInfoRequest, buildGetTxnRequest, buildPoolConfigRequest, buildPoolRestartRequest, buildPoolUpgradeRequest, buildAuthRuleRequest, buildAuthRulesRequest, buildGetAuthRuleRequest, buildTxnAuthorAgreementRequest, buildDisableAllTxnAuthorAgreementsRequest, buildAcceptanceMechanismsRequest, appendRequestEndorser, getResponseMetadata, deleteWalletRecordTags, getSchema, getCredDef, purgeSchemaCache, purgeCredDefCache, isPairwiseExists, createPairwise, listPairwise, getPairwise, setPairwiseMetadata, createPaymentAddress, listPaymentAddresses, addRequestFees, parseResponseWithFees, buildGetPaymentSourcesRequest, buildGetPaymentSourcesWithFromRequest, parseGetPaymentSourcesResponse, parseGetPaymentSourcesWithFromResponse, buildPaymentReq, parsePaymentResponse, preparePaymentExtraWithAcceptanceData, buildMintReq, buildSetTxnFeesReq, buildGetTxnFeesReq, parseGetTxnFeesResponse, buildVerifyPaymentReq, parseVerifyPaymentResponse, getRequestInfo, signWithAddress, verifyWithAddress, refreshPoolLedger, listPools, generateWalletKey</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4303fb23c354b1d23272572103e18ea9e77dd652
</p>

**Review by JamesKEbert — APPROVED** [review]
Thanks for making these changes @TimoGlastra! You beat me to it, I was planning on submitting a PR this week as I had been making local changes so far only, but I didn't realize how gross that'd be for compiling. Looks like you got everything!
There's some minor adjustments for verifying w/revocation that'd probably be good to do, but I'm thinking it'd probably be smart to make a separate PR for that.

**Comment by JamesKEbert** [comment]
The changes needed for the proof portions were fairly minimal. So, if you want to alter your PR or if you'd like me to create an additional PR, whichever is easier, just let me know @TimoGlastra!

---
Adjust the revocation registry definitions type:
```
export interface RevRegsDefs {
    [key: string]: unknown;
}
```
to:
```
export interface RevocRegDefs {
    [revRegId: string]: RevocRegDef;
}
```
---
Also change the verifyProof function from:
```
export function verifierVerifyProof(
    proofRequest: IndyProofRequest,
    proof: IndyProof,
    schemas: Schemas,
    credentialDefs: CredentialDefs,
    revRegsDefs: RevRegsDefs,
    revRegs: RevStates,
): Promise<boolean>;
```
to:
```
export function verifierVerifyProof(
    proofRequest: IndyProofRequest,
    proof: IndyProof,
    schemas: Schemas,
    credentialDefs: CredentialDefs,
    revRegDefs: RevocRegDefs,
    revRegs: RevStates,
): Promise<boolean>;
```
---
And lastly change the revocation registry delta to reflect that issued & revoked can be undefined if there are none returned:
```
export interface RevocRegDelta {
    value: {
        prevAccum: string;
        accum: string;
        issued: number[];
        revoked: number[];
    };
    ver: string;
}
```
to:
```
export interface RevocRegDelta {
    value: {
        prevAccum: string;
        accum: string;
        issued: number[] | undefined;
        revoked: number[] | undefined;
    };
    ver: string;
}
```

**Review by karimStekelenburg — APPROVED** [review]

**Comment by TimoGlastra** [comment]
Ready to merge

**Pull request merged**
