### PR TITLE
[hapi] Correct JoiValidationObject for route validate option.  Correct inject result.

### PR DESCRIPTION
**Pull request by AJamesPhillips**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16065#issuecomment-302216131
- [x] Increase the version number in the header if appropriate.  **-  not applicable**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.  **- not applicable**

### CODE REVIEW

**Comment by AJamesPhillips** [comment]
@mmc41 I think SchemaMap should be used instead of Schema.

**Review by SimonSchick — APPROVED** [review]

**Comment by mmc41** [comment]
Thanks for the quick fix. Agree about SchemaMap but difficult to see if the change is complete. But since you added a test it properly is. Look forward to try it out once a new npm is released

**Comment by AJamesPhillips** [comment]
@mmc41, no problem, can't always promise to be that fast.  If you want to try it out now, a very easy way is to [copy the new index.d.ts](https://raw.githubusercontent.com/AJamesPhillips/DefinitelyTyped/678cc80ff5bcf9f660d4784e810134c60a0d7b03/types/hapi/index.d.ts) raw contents straight from github over the top of your current node_modules/@types/hapi/index.d.ts and see how it behaves with your code.  If it works the only thing you need to do is remember you've done that and update the npm package as you said when it's published.

**Comment by mmc41** [comment]
@AJamesPhillips I have copied and checked the latest version as you suggest. It fixes the regression problem for headers and params but it introduce a new regression problem with payload validation where a singular Joi validation is possible (there is usually (or always?) only one payload while there can be many parameters and query parameters)

I.e. the code below should compile but does not with your latest fix (you can update you test for it).

```
				const validate: Hapi.RouteValidationConfigurationObject = {
				    headers: true,
				    params: {
				        id: Joi.string(),
				    },
				   payload: Joi.object().required(),
				    query: {
				        providerId: Joi.string(),
				    }
				}
```

**Comment by AJamesPhillips** [comment]
Ok good to know @mmc41 .  I actually looked at the code this time:

`hapi/lib/route.js`
https://github.com/hapijs/hapi/blob/b0e37ab8f5268de75ec6cf4e232679afe06f4499/lib/route.js#L63
https://github.com/hapijs/hapi/blob/b0e37ab8f5268de75ec6cf4e232679afe06f4499/lib/route.js#L102
https://github.com/hapijs/hapi/blob/b0e37ab8f5268de75ec6cf4e232679afe06f4499/lib/route.js#L113-L116
https://github.com/hapijs/hapi/blob/b0e37ab8f5268de75ec6cf4e232679afe06f4499/lib/route.js#L14

`hapi/lib/validation.js` calls `Joi.compile()`
https://github.com/hapijs/hapi/blob/e688595a8dce3b3921484eba478753359e388399/lib/validation.js#L24

`joi/lib/index.js` calls `Cast.schema()`
https://github.com/hapijs/joi/blob/70066f1c3cf8f047db4b9572c71807ba23d79ca5/lib/index.js#L133

`joi/lib/cast.js` shows it can also be an array
https://github.com/hapijs/joi/blob/70066f1c3cf8f047db4b9572c71807ba23d79ca5/lib/cast.js#L37

So I've set the following which is hopefully now correct:
`type JoiValidationObject = JoiSchema | JoiSchemaMap | (JoiSchema | JoiSchemaMap)[];`

Thanks for the help so far, let me know if it's still left wanting.

**Comment by mmc41** [comment]
@AJamesPhillips Thanks again for the quick fix. With your new definition my entire project now compiles with the new type definition :-) Great. Now we just need someone to merge your changes. I am still unsure what the process is and what version number it will get etc.

**Comment by AJamesPhillips** [comment]
@mmc41 no worries.  I remember reading a bit of the `@types` publishing code and it should get version `16.1.n` where the `16.1` comes from the top of the index.d.ts file and the `n` is incremented by 1 from the current value.

Process of merging is when one of the DT maintainers is available to get to it.  They might also have a heuristic like no new commits for 3 days or something, not sure.

**Comment by AJamesPhillips** [comment]
@dt-bot @mhegazy @aozgaa ready for merging.

**Comment by AJamesPhillips** [comment]
(sorry, bit cheeky but wanted to save a whole PR just for one change)

**Pull request merged**
