### PR TITLE
Update angularfire / firebase.

### PR DESCRIPTION
**Pull request by nimaen**

### CODE REVIEW

**Comment by vvakame** [comment]
*angularfire/angularfire.d.ts*

to author(@thSoft). could you review this PR?

check list

* [ ] pass the Travic-CI test?

---

*firebase/firebase.d.ts*

to authors(@vbortone @in-async). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by nimaen** [comment]
Looks right to me, will do that in the afternoon.

**Comment by thSoft** [comment]
Otherwise, everything looks good!

**Comment by vvakame** [comment]
@thSoft thanks!
@nimaen thanks mate!
change of firebase/firebase.d.ts is not contains breaking change. I decide it merging.

**Comment by nimaen** [comment]
@vvakame  You're welcome ;)

**Comment by rixrix** [comment]
thanks for merging, was about to ask when it will be merged. cheers

**Pull request merged**
