### PR TITLE
body-parser: this should not be marked as deprecated

### PR DESCRIPTION
**Pull request by samarmohan**
expressjs/body-parser#434

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by samarmohan** [comment]
Tests are not needed.

**Comment by peterblazejewicz** [comment]
Did anything change from the last PR on same topic?:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52314

**Comment by jcrben** [comment]
@samarmohan @peterblazejewicz just to be clear, did you intend for this removal to be closed without a merge? as @akc42 pointed out in the other PR it's striking out valid uses like `bodyParser.json()`

**Comment by akc42** [comment]
> @samarmohan @peterblazejewicz just to be clear, did you intend for this removal to be closed without a merge? as @akc42 pointed out in the other PR it's striking out valid uses like `bodyParser.json()`

Exactly

**Comment by ChenKun1997** [comment]
> @samarmohan @peterblazejewicz just to be clear, did you intend for this removal to be closed without a merge? as @akc42 pointed out in the other PR it's striking out valid uses like `bodyParser.json()`

Why not merge

**Pull request closed without merging**
