### PR TITLE
Node: Fixes for TLSSocket

### PR DESCRIPTION
**Pull request by jtut1731**
Fixes open issue:   #https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14141

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v6.x/docs/api/tls.html#tls_class_tls_tlssocket  ALSO: https://github.com/types/env-node/blob/master/6.0/node.d.ts
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by jtut1731** [comment]
The errors...in jasmine and jimp do not appear to be due to these changes.  I see others PR CI tests are failing also for these two modules.

**Comment by minestarks** [comment]
Sorry @jtut1731  for the trouble - #14819 should fix these failures but I merged it after your last update. If you could merge from master one more time, hopefully the failures will go away.

**Comment by minestarks** [comment]
@jtut1731 still getting external errors... sorry about that, I'm looking into it.

**Comment by jtut1731** [comment]
Thanks @minestarks.

**Comment by minestarks** [comment]
#15077 should fix that last test

**Comment by jtut1731** [comment]
@minestarks Thanks so much!

**Pull request merged**
