### PR TITLE
Fix continuation-local-storage namespace types

### PR DESCRIPTION
**Pull request by leviathanbadger**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). (Note: I had to change the tests extensively to get them to work with the lint, but the same was true before I made any changes)

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/othiym23/node-continuation-local-storage/blob/master/context.js
- [x] Increase the version number in the header if appropriate. (Not appropriate, it's the same version, just a couple of type fixes)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by heycalmdown** [comment]
LGTM

The test was just copied from the source repository, so it will be much easier to diff between them that not to do refactor without good reason.

**Comment by aboveyou00** [comment]
I change the tests to get them to work with the lint function, but none of the changes are material changes. For the most part, I just replaced `function() {}` declarations with arrow functions. (`this` is not referenced in the tests, so I didn't see a problem with that.)

Do you still think I should leave it as it was? I think the DefinitelyTyped readme indicates how to change the tslint settings per-project. I can look into it.

**Comment by heycalmdown** [comment]
Surely there are pros and cons. Having good linted tests is important as a type definition. But more important thing is keeping the type definition consistent with original source code. So I think that keeping the tests from the source repository is an easiest way to do that. However the changes are very small so it is okay.

**Comment by aboveyou00** [comment]
I reverted the tests file. In order to do that, I overwrote the tslint settings for the project.

**Comment by heycalmdown** [comment]
I didn't know that even it can be overwritten. 😄 
It's okay to me.

**Review by heycalmdown — APPROVED** [review]

**Pull request merged**
