### PR TITLE
Revert "feat(node): Error.cause property support"

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Reverts DefinitelyTyped/DefinitelyTyped#61790

It's better to not have this unstable implementation yet:
microsoft/TypeScript#49639
preferring not breaking existing code usage (it passed all tests here, broke stuff in the wild):
#61824

Thanks!

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@jakebailey thanks!

**Comment by peterblazejewicz** [comment]
@jakebailey CI now fails after dt-lint/es-lint stuff was just merged

**Comment by peterblazejewicz** [comment]
Posted on Discord TS channel

**Comment by jakebailey** [comment]
I'm looking into it (I don't have a discord for DT because they won't let me set up a second account 😢)

**Comment by TheNickmaster21** [comment]
We encountered a breaking change from the original change this is reverting (adding the cause property conflicted with a dependency of a dependency of a dependency...); I am hopeful this can be merged sometime soon. Thanks!

**Comment by jakebailey** [comment]
Since this is just a plain revert generated by git, I'm going to merge this despite the CI failure; hopefully the package gets published.

I'll try and send another PR that touches node to reproduce this so this PR isn't the "testing" one.

**Pull request merged**
