### PR TITLE
add support for AMD require

### PR DESCRIPTION
**Pull request by sixinli**
this supports the import syntax import * as keypress from "keypress.js";

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Reopening to see if Travis reappears

**Comment by RyanCavanaugh** [comment]
@sixinli if you could sign up for a Travis account as mentioned in the prior PR, they can unflag your account and re-enable CI for your PRs. Ping me if you open an account and I'll get support on the case

**Comment by sixinli** [comment]
@RyanCavanaugh unfortunately on signing up the account, it asks me permission to access organizations im in, and im not sure what it's accessing since there are private organizations :(

**Comment by andy-ms** [comment]
I'll just merge this then.

**Pull request merged**
