### PR TITLE
[react-spinkit]: update to 3.0.0

### PR DESCRIPTION
**Pull request by zzanol**
Prop 'spinnerName' was changed to 'name' in 3.0.0.

https://github.com/KyleAMathews/react-spinkit/commit/60af1a334e4ffe841b23384b970223f58e0a3503

### CODE REVIEW

**Comment by mleko** [comment]
👎

Use subfolder for breaking change
https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by mleko** [comment]
👍
LGTM

**Comment by tkqubo** [comment]
👍

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
