### PR TITLE
Type defs + test for Segment's analytics library for Node.js

### PR DESCRIPTION
**Pull request by fongandrew**
Adds definitions for the Segment's server-side Node.js library (which differs slightly from the existing  definitions for their client side library).

Based off documentation at https://segment.com/docs/libraries/node/

### CODE REVIEW

**Comment by vvakame** [comment]
*segment-analytics/segment-analytics-node.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/segment-analytics
  * http://bower.io/search/?q=segment-analytics
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (segment-analytics/segment-analytics-node-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
please rename segment-analytics/segment-analytics-node.d.ts to analytics-node/analytics-node.d.ts

**Comment by fongandrew** [comment]
Renamed.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
