### PR TITLE
Update jquery.payment.d.ts

### PR DESCRIPTION
**Pull request by johnrutherford**
I made some improvements to the definition file for jquery.payment:
- Put interfaces inside a module so they aren't in the global namespace.
- Added `JQuery` return type to `JQuery.payment()` so calls can be chained more easily.
- Added `cards` array property and `CardInfo` interface.
- Added documentation for most methods and properties.
- Marked `type` parameter on `validateCardCVC()` method as optional.

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.payment/jquery.payment.d.ts*

to author(@ejsmith). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@johnrutherford please fix travis ci failed.
https://travis-ci.org/borisyankov/DefinitelyTyped/builds/75300030

**Comment by johnrutherford** [comment]
@vvakame Sorry, I couldn't see the Travis-CI page for a while. I should have runs the tests before my initial commit. It's fixed now.

**Comment by ejsmith** [comment]
Looks good to me. :+1:

**Comment by vvakame** [comment]
@ejsmith thanks!
@johnrutherford thanks mate!

**Pull request merged**
