### PR TITLE
Update dom-mediacapture-record for TS 5.1

### PR DESCRIPTION
**Pull request by jakebailey**
Based on #64672.

### CODE REVIEW

**Comment by jakebailey** [comment]
Per #62472 apparently I can't do this and have to preserve the types?

**Comment by jakebailey** [comment]
Alright, well, I need 5.0 to be released to test this, I guess.

**Comment by jakebailey** [comment]
Actually, I think the types here are just "wrong"; https://w3c.github.io/mediacapture-record/#bitratemode says that the options are "variable" and "constant", whereas these types say "vbr" and "cbr".

Is it the case that all of these types are now covered by `lib.dom.d.ts`? What happens to this package if that's true?

**Comment by jakebailey** [comment]
Seems like nobody uses it anyway? Guess I should actually just update the type to be accurate?

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
Ready to merge

**Pull request merged**
