### PR TITLE
[@types/aws-lambda] Fixing SNSMessage field names to match the AWS developer guide

### PR DESCRIPTION
**Pull request by markscamilleri**
I noticed that the `SNSMessage` type is inconsistent with what AWS documents on the SNS Developer's guide (https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html) and what the event looks like in practice (via logging). The fields `UnsubscribeUrl` and `SigningCertUrl` are actually named `UnsubscribeURL` and `SigningCertURL`, so this PR seeks to fix that.

AWS' own documentation was inconsistent with the[ Lambda docs ](https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html) showing the wrong field naming as well. A PR has been opened to update this documentation as well (awsdocs/aws-lambda-developer-guide#438)

I have also run prettier as per [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes) instructions and due to that, I have also fixed a tslint issue.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (It does not)

### CODE REVIEW

**Comment by markscamilleri** [comment]
>- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

I kept this unchecked as when running `npm run prettier -- --write types/aws-lambda/**/*.ts` it seems all files needed to be changed and that would have made this PR too large. Could you please advise what to do regarding this? I'm more than happy to open a separate PR running prettier as well.

**Review by darbio — APPROVED** [review]

**Comment by simonbuchan** [comment]
> Could you please advise what to do regarding this? I'm more than happy to open a separate PR running prettier as well.

I suspect this package simply predates that advice, or at least it working. The separate PR might be a bit of overkill, since it will publish a separate package, so my vote is a separate commit in here is probably fine (I don't think there's any other open PRs that would invalidate?)

**Comment by markscamilleri** [comment]
> > Could you please advise what to do regarding this? I'm more than happy to open a separate PR running prettier as well.
> 
> I suspect this package simply predates that advice, or at least it working. The separate PR might be a bit of overkill, since it will publish a separate package, so my vote is a separate commit in here is probably fine (I don't think there's any other open PRs that would invalidate?)

@simonbuchan thanks for this! I have just ran prettier and included the changes in this PR

**Comment by darbio** [comment]
@markscamilleri Please can you put the subject change in a new PR (with a link to the documentation)  and roll this one back to just be the discussed changes.

This further change is unrelated to the original change/discussion. Thanks mate!

**Comment by markscamilleri** [comment]
> @markscamilleri Please can you put the `subject` field change in a new PR (with a link to the documentation) and roll this one back to just be the discussed changes.
> 
> This further change is unrelated to the original change/discussion. Thanks mate!

@darbio sorry about that! I thought that it made sense to add it to the scope of the PR as it's not breaking and it fits with the title of the PR (albeit I needed to edit the description)

I've reverted it and I'll open another PR for that change :slightly_smiling_face:

**Review by darbio — APPROVED** [review]

**Comment by markscamilleri** [comment]
Ready to merge

**Pull request merged**
