### PR TITLE
Delete packages that have failed for a long while

### PR DESCRIPTION
**Pull request by sandersn**
No substantive updates for 2 years and <10,000 downloads per week.

The packages will remain on npm, but won't get updates from DT.

### CODE REVIEW

**Comment by sandersn** [comment]
CI failure is from a concurrent change I merged while working on this PR.

**Comment by MTRNord** [comment]
> 🔔 @maartenvanvliet @nightillusions @slowtick @diegodalbosco @MTRNord @Jungwoo-An @djpereira @thekevinbrown @abhijithvijayan @tclain @pselden @tomasz-zablocki @shaunluttin — please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64559/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.
> 

I gave no consent to be scraped by this bot. Please opt me out of this. Thank you.

**Comment by sandersn** [comment]
You were on the authors list of `@types/dialogflow-fulfillment`, and the bot was asking for reviews. The package's source is deleted now, so you won't get any more emails about it.

**Comment by MTRNord** [comment]
> You were on the authors list of `@types/dialogflow-fulfillment`, and the bot was asking for reviews. The package's source is deleted now, so you won't get any more emails about it.

Hi thanks for explaining I wasn't aware that this code ever made it into this repo 🤔

**Pull request merged**
