### PR TITLE
fix(trianglify): seed should not accept numbers, only strings

### PR DESCRIPTION
**Pull request by fdaciuk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/qrohlf/trianglify

### CODE REVIEW

**Review by mxthevs — COMMENTED** [review]
Looks good to me!

**Review by mxthevs — APPROVED** [review]

**Comment by fdaciuk** [comment]
Ready to merge

**Review by mxthevs — APPROVED** [review]
LGTM

**Comment by mxthevs** [comment]
Ready to merge

**Pull request merged**
