### PR TITLE
Aurelia typescript definitions from https://github.com/cmichaelgraham/aurelia-typescript-atom

### PR DESCRIPTION
**Pull request by eriklieben**
Typescript definitions from https://github.com/cmichaelgraham/aurelia-typescript-atom.

Related to pull request #4311.

### CODE REVIEW

**Comment by vvakame** [comment]
check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/aurelia
  * http://bower.io/search/?q=aurelia
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)?
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
umm... I wonder what kind of name is good. @basarat

**Comment by basarat** [comment]
Thanks for the effort, but I would recommend not adding this. Hopefully we can have https://github.com/Microsoft/TypeScript/issues/2338 soon that the typescript definitions can accompany the js files for aurelia. The aurelia team has TS support a high priority and it should work *just out of the box* soon.

**Comment by basarat** [comment]
Refs https://github.com/borisyankov/DefinitelyTyped/pull/4325

**Pull request closed without merging**
