### PR TITLE
[detox] Add missing function pressBack

### PR DESCRIPTION
**Pull request by henrikra**
Detox types where missing [pressBack](https://github.com/wix/Detox/blob/50ee9943ff6ed50248a6955117afed7621827d8d/docs/APIRef.DeviceObjectAPI.md#devicepressback-android-only) which is Android only function. Now it has been added to the types 🌮 

I also added test that validates that the function is available now

### CODE REVIEW

**Comment by henrikra** [comment]
@TareqElMasri Do you have chance to look at this? :)

**Comment by andy-ms** [comment]
@henrikra Please fix the merge conflict, then we can merge

**Comment by henrikra** [comment]
@andy-ms Conflict fixed

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
