### PR TITLE
prune(openfin): remove source for older versions

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This change intent is to ease CPU workload required to pass through any
Node ecosystem PR on DT, which started to last for non acceptable time,
hours on local dev machine (+30 minutes on CI).
Removing older version of declaration files (already published to NPM),
according to matrix from release notes:
https://cdn.openfin.co/versions/?product=Runtime

From CI runs:
```bash
...,openfin,openfin v50.0,openfin v49.0,openfin v45.0,openfin v43.0,openfin v41.0,openfin v39.0,openfin v37.0,openfin v34,...
````

@chrisbarker for review

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by gabritto — APPROVED** [review]
This change looks ok to me. Let's wait for an author review and then I think we're good to merge this. @chrisbarker @rdepena @whyn07m3 @licui3936 @tomer-openfin please review this.
Also, I'm curious:  why do we have so many files for `openfin`?

**Comment by chrisbarker** [comment]
@peterblazejewicz & @gabritto - I wrote the initial implementation because I needed it and then the people at Openfin it took over. I'll reach out to them and see if someone wants to pick this up. I guess this is an automated process that is generating all these files. I know they support a lot of concurrent versions but...

**Comment by gabritto** [comment]
@chrisbarker thanks for clarifying

**Review by gabritto — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
