### PR TITLE
adds types declaration for CanvasFlowmapLayer

### PR DESCRIPTION
**Pull request by vishalseshagiri**
Co-authored-by: vishalseshagiri <vishaljsesh@gmail.com>
Co-authored-by: kaladharusc <mummadi@usc.edu>
Co-authored-by: bthiagar <bthiagar@usc.edu>

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by vishalseshagiri** [comment]
fixes https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/issues/16

**Comment by alejo90** [comment]
Thanks for the contribution. This, however doesn't belong in the leaflet definition, since what you're adding is coming from a plugin. I recommend you create a new definition for the plugin that enriches the leaflet type definition.

**Comment by vishalseshagiri** [comment]
@alejo90 , I am using a json file in the tests to load data, but travis fails with error unused file, little new to angular, can you help me debug this.

**Comment by alejo90** [comment]
The purpose of the test file is to assert that the typing definition conforms to the target library's api. You can expect to see things like method calls and assignments in such test files because they are fed to the compiler to be typechecked so that you can validate that the function declaration you defined in your typing accepts the right amount of arguemnts, thar those arguments are of the right types, that the return type is what you expect it to be, etc. You don't need the json file or loading data because the code in the test file will never be executed. Lastly, the angular framework doesn't need to be a concern around this typing, since the library the typing describes is not dependent on angular.

**Comment by vishalseshagiri** [comment]
Angular throws an error though since the leaflet window object doesn't contain the canvasFlowMapLayer method. The error only goes away after the declaration either in the angular types or as a new definition.

**Pull request closed without merging**
