### PR TITLE
Add undefined to optional properties, React to Regenerate

### PR DESCRIPTION
**Pull request by sandersn**
In preparation for exactOptionalPropertyTypes in Typescript 4.4, add undefined to all optional properties. #no-publishing-comment

This PR covers widely used packages, those with more then 100,000 packages per month, from react-slider -- regenerate

microsoft/dtslint#335

### CODE REVIEW

**Comment by sandersn** [comment]
Failure is from a dependent of mongoose, which fails on master as well.

**Comment by kokushkin** [comment]
Just wonder why did you do this? Looks like it wasn't a breaking change in TS 4.4 (flag exactOptionalPropertyTypes : false by default), isn't it? So, everything would be ok until somebody decided to make exactOptionalPropertyTypes : true but then they could deal with it in their own code just fine. On another side now I see a lot of ``` | undefined ``` in React types which definitely troubles my understanding even more (they where hard enough before that). (I tried to read microsoft/dtslint#335  I didn't get the explanation though)

**Comment by sandersn** [comment]
> it might have bad consequences in the future if such things happen too often, I think

We don't intend to edit every package on DT very often, no fear. =)

Unfortunately backward compatibility means the "don't care" semantics are longer to write. We would definitely do it the other way if we started over from scratch.

**Comment by kokushkin** [comment]
So do you think it's gonna stay till the end of Typescript? And it's too big change even for a new major version or couple of such? And this's kind of a relatively new stuff, not even one year ago, right? I mean introducing the exactOptionalPropertyTypes  flag, starting from which all these "don't care cases" ( I think they constitute over 99% of all cases) should be written like ```blablabla?: type | undefined```. So there was no way to say "I'll accept nothing but not undefined", correct? Could you please point me out to the issue where  exactOptionalPropertyTypes  was conceived?) I really want to know what were the discussions behind this.

**Comment by sandersn** [comment]
https://github.com/microsoft/TypeScript/pull/43947

**Pull request merged**
