### PR TITLE
express-validator: fix and new methods

### PR DESCRIPTION
**Pull request by marcoancona**
Method isUrl() should be isURL().
New methods are now available in validator.js. This pull requests adds isLength(), isMongoId() and is ISO8601()

### CODE REVIEW

**Comment by marcoancona** [comment]
Travic CI fails because isUrl() has been refactored to isURL() which is the correct method

**Comment by vvakame** [comment]
please fix test case together.

**Comment by marcoancona** [comment]
Fixed, thanks

**Comment by vvakame** [comment]
@axefrog could you review this PR?

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
