### PR TITLE
[node] Update script for processing `<sup>` tag

### LINKED ISSUE #58684: crypto.d.ts randomInt documentation error
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7467038c60726c43ccfc0f084cd8d5d8f062d234/types/node/crypto.d.ts#L1746
https://nodejs.org/api/crypto.html

"The range (`max - min`) must be less than 248."
Should actually be:
"The range (`max - min`) must be less than 2**48."

I'm not sure if this is from copying the formatted Node.js HTML documentation into a text document and losing <sup>48</sup>. If so, there could be errors like this elsewhere.

### PR DESCRIPTION
**Pull request by Semigradsky**
Close #58684

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/scripts/generate-docs/html-doc-processing.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 35c79f4b209e88089c016ca6a259d0f88cf7776d
</p>

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by navneerajmishra** [comment]
We get a following error since yesterday after this commit was merged in our project
```
#24 248.5 Error: node_modules/@types/node/ts4.8/crypto.d.ts:4477:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'crypto' must be of type 'Crypto', but here has type 'Crypto'.
#24 248.5 
#24 248.5 4477         var crypto: webcrypto.Crypto;
```
We're using typescript version 4.7.4.

**Comment by peterblazejewicz** [comment]
@navneerajmishra this one was a tech detail for JSDoc parser. You meant probably this (and similar) issue: #68370

**Comment by navneerajmishra** [comment]
> @navneerajmishra this one was a tech detail for JSDoc parser. You meant probably this (and similar) issue: #68370

As a workaround I have explicitly set the @types/node to 18.11.9 temporarily. I'll wait for this PR to be merged
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68371

**Pull request merged**
