### PR TITLE
[React] Update crossOrigin attribute

### PR DESCRIPTION
**Pull request by hyeongrok7874**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
<https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin>

---

Update `crossorigin` attribute `"anonymous" | "use-credentials" | "" | to undefined`

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 67467befc928c3861e75802033b720384e04cbc3
</p>

**Review by dimitropoulos — APPROVED** [review]

**Comment by nam-diijam** [comment]
I have been struggling with this error in type checking:
```
(property) JSX.IntrinsicElements.input: DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>
Type '{ accept?: string; alt?: string; autoComplete?: string; autoFocus?: boolean; capture?: boolean | "user" | "environment"; crossOrigin?: string; disabled?: boolean; enterKeyHint?: "search" | "enter" | ... 4 more ... | "send"; ... 279 more ...; onBlur: FocusEventHandler<...>; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ accept?: string; alt?: string; autoComplete?: string; autoFocus?: boolean; capture?: boolean | "user" | "environment"; crossOrigin?: string; disabled?: boolean; enterKeyHint?: "search" | "enter" | ... 4 more ... | "send"; ... 279 more ...; onBlur: FocusEventHandler<...>; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    Types of property 'crossOrigin' are incompatible.
      Type 'string' is not assignable to type '"" | "anonymous" | "use-credentials"'.ts(2322)
```

My component:
```tsx
const CheckboxField = forwardRef(function CheckboxField(
  {checked, ...props}: Props,
  forwardedRef: Ref<HTMLInputElement>,
) {
  return (<input
    //     ^ TS error here
    defaultChecked={checked}
    ref={forwardedRef}
    {...props}
  />);
}

type Props = InputHTMLAttributes<HTMLInputElement>;
```

My packages:
```json
"react": "18.2.0",
"react-dom": "18.2.0",
"@types/react": "18.0.25",
"typescript": "4.8.4"
```

Does anyone have same error? How can I solve it?

**Comment by nam-diijam** [comment]
I have been struggling with this error in type checking:
```
(property) JSX.IntrinsicElements.input: DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>
Type '{ accept?: string; alt?: string; autoComplete?: string; autoFocus?: boolean; capture?: boolean | "user" | "environment"; crossOrigin?: string; disabled?: boolean; enterKeyHint?: "search" | "enter" | ... 4 more ... | "send"; ... 279 more ...; onBlur: FocusEventHandler<...>; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ accept?: string; alt?: string; autoComplete?: string; autoFocus?: boolean; capture?: boolean | "user" | "environment"; crossOrigin?: string; disabled?: boolean; enterKeyHint?: "search" | "enter" | ... 4 more ... | "send"; ... 279 more ...; onBlur: FocusEventHandler<...>; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    Types of property 'crossOrigin' are incompatible.
      Type 'string' is not assignable to type '"" | "anonymous" | "use-credentials"'.ts(2322)
```

My component:
```tsx
const Checkbox = forwardRef(function Checkbox(
  {checked, ...props}: Props,
  forwardedRef: Ref<HTMLInputElement>,
) {
  return (<input
    //     ^ TS error here
    defaultChecked={checked}
    type="checkbox"
    ref={forwardedRef}
    {...props}
  />);
}

type Props = InputHTMLAttributes<HTMLInputElement>;
```

My packages:
```json
"react": "18.2.0",
"react-dom": "18.2.0",
"@types/react": "18.0.25",
"typescript": "4.8.4"
```

Does anyone have same error? How can I solve it?

**Pull request merged**
