### PR TITLE
Add typings for Swiper 3.3.0

### PR DESCRIPTION
**Pull request by WarriorRocker**
Updated typings for Swiper 3.3.0 replacing the current targeting version 2.0.0

### CODE REVIEW

**Comment by WarriorRocker** [comment]
Not sure about convention, should the old tests be removed? Additionally the errors from the build  seem to come from either the old definitions file or from the plugin example in the tests. The test itself is directly from the Swiper demos.

**Comment by vvakame** [comment]
It is all right in this state. but you should fix travis ci for merge this PR.
try with `--noImplicitAny` option.

**Comment by mhegazy** [comment]
@WarriorRocker can you please address the merge conflicts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
