### PR TITLE
`DSVRowString` and `DSVRowAny` return `undefined` for non-existing rows, and `DSVParsedArray` return `undefined` for columns of empty input.

### PR DESCRIPTION
**Pull request by azoson**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-dsv/blob/master/README.md#dsv_parse>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@azoson Thanks for the contribution. As it stands the definitions for **d3-request** have not been officially vetted for use with `strictNullChecks`. (see #11365).

As you are putting your finger on an open TODO, I would suggest to use this PR as a starting point to address this is on complete sweep. I.e. we should vet the whole definition, make the appropriate changes and activate `strictNullChecks` in the `tsconfig.json` for the **d3-request** definitions.

This may also entail updating some of the tests.

Would you be willing to tackle this jointly as part of this PR? Would be appreciated... 🥇

**Comment by tomwanzek** [comment]
To correct my mistake: For **d3-request** in my above comment, read: **d3-dsv**.

**Comment by azoson** [comment]
At first, I excuse that my poor English skill may lead misunderstanding and rude sentences.
(Even this sentence may be rude, but I cannot judge myself 😣)

I have the willingness to fix this errors in this PR.
I am very interested in your proposal.
As you said, now my changes cause some errors in the test when `strictNullCheck` activated.

I will update `d3-dsv-test.ts`.
Then check if the codes passed test.
Is there other to do?

**Comment by tomwanzek** [comment]
No worries about your English. All good  😄 Let me have a look at **d3-dsv** this weekend. I haven't looked at it in a while, so I can't tell you off the top of my head, what changes may be needed to make it viable for `strictNullChecks`.

I'll provide you input based on what I see. So thanks for staying tuned.

**Comment by tomwanzek** [comment]
@azoson My apologies for the brief delay. Upon closer look at the definitions for **d3-dsv**, I thought it would be easier to do a more complete sweep. So I am going to create a new PR as the basis for addressing both the `strictNullChecks` and complete JSDoc comments.

It seemed easier in this case, as the explanation of "requested/suggested" changes might have been longer and more cumbersome to follow.

I will cross-reference this PR to it, as I submit the request for review/merge. I will @-mention you alongside @gustavderdrache on the new PR for review/discussion.

Feel free to leave this PR open for now, until we align on the new PR.

**Comment by azoson** [comment]
Do not worry about the delay 😄 
I am glad to hear that there is a better way to enable strictNullChecks.
I pushed my changes to fix the test script.
It may help your new PR.
I'm looking forward to your new PR and discussion.

**Comment by tomwanzek** [comment]
See #21162.

**Comment by tomwanzek** [comment]
@azoson Can this be closed now in favour of #21162? If you have any further comments/suggestions, you could add them to the new PR before it is merged. (I.p. see my point there about how to handle the `columns` property.) Cheers, T.

**Review by tomwanzek — CHANGES_REQUESTED** [review]
@azoson Let's close this PR with a big thank you as it is superseded by #21162.

**Comment by RyanCavanaugh** [comment]
@azoson Please address comments from the code reviewers.

**Comment by rbuckton** [comment]
Closed as it was superseded by #21162

**Pull request closed without merging**
