### PR TITLE
Reference DOM in opentype.js

### PR DESCRIPTION
**Pull request by alecmev**
Otherwise consumers blow up on `CanvasRenderingContext2D` and `SVGPathElement` if they don't provide them themselves.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45752
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by alecmev** [comment]
Hmm, is that a problem? The reference is scoped to just this file.

**Comment by danmarshall** [comment]
I'm not certain. I'll try spinning up a repo to test https://github.com/danmarshall/test-opentype-node

**Comment by danmarshall** [comment]
Seems to work for a node-only project. I'll approve :)

**Review by danmarshall — APPROVED** [review]

**Comment by alecmev** [comment]
Thanks for testing it!

**Review by gabritto — APPROVED** [review]

**Comment by alecmev** [comment]
Ready to merge

**Pull request merged**
