### PR TITLE
Update faker for v5.5.0

### PR DESCRIPTION
**Pull request by heavenshell**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Marak/faker.js/pull/1123
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

This PR related to #52009 
Faker 5.5.0 now shows deprecation warning such as
```
    console.log                                                                 
      Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid                                                                              
                                                                                
      at Random.uuid (node_modules/faker/lib/random.js:121:13)                  
```

Add datatype and add `@deprecated` annotation to `random`

### CODE REVIEW

**Review by martin-badin — APPROVED** [review]

**Comment by revskill10** [comment]
Please considering merge !

**Comment by slaheux** [comment]
Is it possible to merge it ? I have tons of warning since the last faker update but cannot use `faker.datatype` because of types..
Thanks in advance :)

**Review by TastefulElk — CHANGES_REQUESTED** [review]
Looks like the following generators are still missing: 
- datetime
- string
- json
- array

Could you add those as well?

https://github.com/Marak/faker.js/blob/master/lib/datatype.js

**Comment by heavenshell** [comment]
Thank you for review!

I added another datatype!

**Review by TastefulElk — APPROVED** [review]

**Comment by TastefulElk** [comment]
Thanks a lot for contributing @heavenshell! 🏆

**Pull request merged**
