### PR TITLE
lodash: added _.sortedLastIndex

### PR DESCRIPTION
**Pull request by brampouwelse**

### CODE REVIEW

**Comment by Arzie** [comment]
Looks good!

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors(@bczengel @chrootsu). could you review this PR?
:+1: or :-1:?

check list

* [x] pass the Travic-CI test?

**Comment by chrootsu** [comment]
@vvakame :+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
