### PR TITLE
[ramda] Begin isolated file migration

### PR DESCRIPTION
**Pull request by Harris-Miller**
# Begin migration of everything in `index.d.ts` to their `src/function.d.ts` files

Right now, `src/add.d.ts` is just
```typescript
import { add } from '../index';
export default add;
```

But is should, and can, be the other way around
```typescript
/**
 * Adds two values. Equivalent to `a + b` but curried.
 *
 * @example
 * ```typescript
 * R.add(2, 3);       //=>  5
 * R.add(7)(10);      //=> 17
 * ```
 */
declare function add(a: number, b: number): number;
declare function add(a: number): (b: number) => number;

export { add };
export default add;
```

and then in `index.d.ts`, replace where the definition of `add` was with
```typescript
export * from './src/add';
```

For the sake of example, this MR _only_ does one function, `add`. I'm purposefully doing this to show MR reviewers what the plan is so we can agree with move, which I believe will make the handling of ramda types far easier.

Furthermore, the ramda core team has created a `@ramda/types` which I'm beginning to work on to bring move all the types into `ramda` so `@types/ramda` can be deprecated. That process will take a while, and the repo is currently private. See this [discussion](https://github.com/ramda/ramda/discussions/3329) for more info

#### Template stuff

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bc85c93c0b0ff2efb8d61c7178f5673035b2df37
</p>

**Comment by Nicholaiii** [comment]
Do you think this work is worth the effort if official types are in the works?

**Comment by Harris-Miller** [comment]
@Nicholaiii Ideally, no. If I had it my way, The aforementioned `@ramda/types` lib will be public and published and this MR would be to do the re-export. However, communication with the ramda core team has been difficult to say the least.

The idea of this effort in my mind is to get the ball rolling on that my getting this library to mirror that library (which I'm sorry you can't see because it's private, but it's looks like this [here](https://github.com/ramda/ramda/tree/ts/types) where each function is defined in solo files). By doing that, we can do updates here and easily mirror those changes in ramda/types once it is public.

**Comment by Nicholaiii** [comment]
> @Nicholaiii Ideally, no. If I had it my way, The aforementioned `@ramda/types` lib will be public and published and this MR would be to do the re-export. However, communication with the ramda core team has been difficult to say the least.
> 
> The idea of this effort in my mind is to get the ball rolling on that my getting this library to mirror that library (which I'm sorry you can't see because it's private, but it's looks like this [here](https://github.com/ramda/ramda/tree/ts/types) where each function is defined in solo files). By doing that, we can do updates here and easily mirror those changes in ramda/types once it is public.

Ah well, I applaud the effort. Signing off on this PR and imho you can just do whatever you feel is best to get the ball rolling.

**Review by Nicholaiii — APPROVED** [review]

**Comment by Harris-Miller** [comment]
Closing, we're going to release `@ramda/types`. Will have another MR in a few days that make this re-export that

**Pull request closed without merging**
