### PR TITLE
[Braintree] Update statusHistory definition to array

### LINKED ISSUE #48540: [Braintree] Wrong definition: statusHistory is an array
@smrubin @sedenardi Loks like that the statusHistory argument is a list.
On the documentation is maked as a "collection".

On PHPand JAVA library is an Array:
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Subscription.php#L99
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Transaction.php#L446
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Dispute.php#L81

And on Node library test is also an array.
https://github.com/braintree/braintree_node/blob/master/spec/unit/braintree/dispute_spec.js#L42

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #48540

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree@latest/))
was missing the following properties:
1. GraphQL
1. version
1. errorTypes
1. CoinbaseAccount
1. AmexExpressCheckoutCard

<details>
<summary>as well as these 5 other properties...</summary>
<p>PaymentInstrumentTypes, WebhookNotification, TestingGateway, UsBankAccountVerification, ValidationErrorCodes</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b61fcdf6c5275c1fad30e3d94454cd9a151d6ed7
</p>

**Review by sedenardi — APPROVED** [review]
Based on the source and documentation of Disputes, looks good to me.

**Comment by martin-badin** [comment]
@sedenardi Thank you so much

**Review by smrubin — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
