### PR TITLE
[oidc-provider] bump to v7.12.0

### PR DESCRIPTION
**Pull request by panva**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/panva/node-oidc-provider/releases/tag/v7.12.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## oidc-provider ([<kbd>unpkg</kbd>](https://unpkg.com/browse/oidc-provider@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'oidc-provider'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. once
1. on
1. listenerCount
1. errorMonitor

<details>
<summary>as well as these 4 other properties...</summary>
<p>captureRejectionSymbol, captureRejections, defaultMaxListeners, EventEmitter</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3aa23ca77eed097898f7e40f655e8459f51e58a9
</p>

**Comment by RalphBragg** [comment]
LGTM

**Review by RalphBragg — APPROVED** [review]
Approved - Back Channel is now final so the Ack is being removed.

**Comment by panva** [comment]
Ready to merge

**Pull request merged**
