### PR TITLE
 [react-native] add Share and Surface definitions for ART

### PR DESCRIPTION
**Pull request by evollu**
add Share and Surface definitions for React native ART
it is not complete, but at least can make my project going

### CODE REVIEW

**Comment by evollu** [comment]
@dt-bot can some one review it?

**Comment by zhengbli** [comment]
@evollu sure. Do you mind adding a link to the documentation / actual implementation for the changes you want to make?

**Comment by evollu** [comment]
Thanks.
https://github.com/facebook/react-native/blob/master/Libraries/ART/ReactNativeART.js#L390

**Comment by mhegazy** [comment]
Do not think this is needed any longer. please reopen if this is not the case.

**Comment by evollu** [comment]
strokeDash should be a number array. need to fix that in master

**Pull request closed without merging**
