### PR TITLE
react-select

### PR DESCRIPTION
**Pull request by DLTKJimMcCarthy**
Updated type file to include support for Async dropdowns.  Added tests.

### CODE REVIEW

**Comment by Hesquibet** [comment]
Hey Jimm !
Thank you for collaborating on this.
Is there any reason why you've extended the class 

```javascript
SelectWithAsync extends ReactSelectClass
```
 instead of just adding it to the ReactSelectProps class ?

Thanks,
Hugo

**Comment by jimmccarthy** [comment]
Hi Hugo,

I tried that initially but could not get it to work.  Since 'Async' is set
up in the React component in the 'statics' property as a static object I
could not get typescript to recognize it as a property, even though it was
throwing an error as if it was expecting it to be a property.  Would love
to hear if there is a better way to handle this.  Thanks.

Jim

**Comment by Hesquibet** [comment]
Not sure if i get this right, but anyways it's just a detail. Thanks for the unit test by the way !

**Comment by jimmccarthy** [comment]
Sure, no problem.  Pretty new to React and Typescript myself so I may not
be explaining it well.

Thanks,
Jim

**Comment by marknadig** [comment]
@Hesquibet I think you have to give a final thumbs up for this to be merged.

**Pull request merged**
