### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by stepancar**
allow set disabled attribute in firefox as string

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Can you show where this is documented? If this is Firefox-specific, it's not clear whether it's appropriate to permit strings here.

If we do add this change, can you add a test for this?

**Comment by johnnyreilly** [comment]
I'm not aware of any browser specific support in react - could you provide a docs example?

**Comment by stepancar** [comment]
@DanielRosenwasser , @johnnyreilly  https://github.com/facebook/react/issues/961

**Comment by johnnyreilly** [comment]
Could you fix the existing tests and privide a  new one please? Also shouldn't it be `boolean | 'disabled'`?

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
