### PR TITLE
Definitions for angular-formly.

### PR DESCRIPTION
**Pull request by scatcher**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-formly/angular-formly.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-formly
  * http://bower.io/search/?q=angular-formly
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-formly/angular-formly-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@scatcher thank you for your contributions.
please rename angular-formly/angular-formly-test.ts to angular-formly/angular-formly-tests.ts

**Comment by scatcher** [comment]
Test file renamed as requested.  Let me know if you need anything else.

**Comment by vvakame** [comment]
@scatcher it merged. thanks mate.

**Pull request merged**
