### PR TITLE
Fix issues in d3 typings when compiling with --strictNullChecks

### PR DESCRIPTION
**Pull request by alejo90**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: no new methods, just fix issues when compiling with --strictNullChecks
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@alejo90 please see my comments under PR #12340. This is a duplicate of the work that needs to be completed related to the already open PR.

I have been busy updating d3-voronoi and d3-geo and bringing the definitions up to D3 v4.3 as a priority.

So it seems best to entertain further work under only on of the PRs, but conduct the full review outlined in said PR.

Open to suggestions on how to best split the work, as I have unrelated priorities to cater to.

cc @alitaheri

**Comment by alitaheri** [comment]
This is a better approach 👍 I'll close mine

**Comment by tomwanzek** [comment]
I am just bringing this  one over for ease of reference. It was previously included with #12340 .

> First of and for the sake of cross-referencing, this is related to the tracking issue #11365.
> 
> Enabling `strictNullChecks` in the `tsconfig.json` for any definition file, should only be done, after it has been vetted to enable `strictNullChecks` reliably. Otherwise, it gives the wrong impression to users.
> 
> For D3, in some cases the API documentation is explicit enough to understand on the issue of return values in "failure modes" or similar circumstances, like callback functions. In others, it is necessary to validate against the actual source code, to see whether e.g. the a function returns `null` or `undefined` if it does not return the "normal expected" return type `SomeType`. It may even be `SomeType | null | undefined`, or `never`.
> 
> I venture to say, it may not be as simple as adding `null` to the `BaseType`, I did some initial investigation a while back to see how things flow through callbacks, sub-selections, appends, inserts, enter, event handlers etc. in a Selection and there where additional considerations to follow up on.
> 
> So it will require going back to the documentation/source code. In any case the shape tests will have to be updated to ensure coverage of the `strictNullChecks` as well.
> 
> This was a primary reason to prioritize issue #11366 regarding adding JSDoc comments to all the definitions first.
> 
> In any case, because of the nature of the coupling between `d3-selection`, `d3-transition`, `d3-selection-multi`, `d3-drag`, `d3-zoom`. The update to `strictNullChecks` should be done for all of them with the same stroke to ensure consistency. Other D3 modules should be addressable in a more isolated manner.

**Comment by tomwanzek** [comment]
One off the next  steps will have to be to identify which shape tests need updating. To ensure the definitions are reflective of actual behavior.

This also implies, as part of completing this PR, we will need to set the compiler option for `strictNullChecks` to `true` in the `tsconfig.json` files, for each of the definitions, that are validated as part of this PR.

**Comment by tomwanzek** [comment]
I started going though a few of the considerations I mentioned above in a local branch, when I am done experimenting with some of the approaches/impact assessment, I will comment back.

**Comment by tomwanzek** [comment]
Given the amount of homework  on the test files, I have created a new PR #12858. While it would have been possible to comment on the definition files themselves in this PR. The changes to the test files where a bit too extensive... Needed to clean up a little technical debt in the process... 😄 

Feel free to review and comment on the PR I created as an alternative.

**Comment by alejo90** [comment]
Thanks , @tomwanzek. 
Closing in favor of #12858

**Pull request closed without merging**
