### PR TITLE
Refined some declarations for snapsvg

### PR DESCRIPTION
**Pull request by FlashSystems**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://snapsvg.io/docs/#Element.append for add/append (58db3b7), http://snapsvg.io/docs/#Paper.symbol for symbol (d4ebbf3), https://github.com/adobe-webplatform/Snap.svg/blob/master/src/attr.js#L434 for attr and viewBox (7c8dcfd).
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by kant2002 — COMMENTED** [review]
Could you add examples of usage to the tests?

**Comment by FlashSystems** [comment]
I copied and simplified my production code to make it into a test and added it into `2.ts`. It uses all of the three additions of my previous commits. I hope it's no problem I've made one extra commit for all three tests. It would be hard to separate them.

**Comment by FlashSystems** [comment]
**Please do not merge this pull request now**. I found a problem with commit "7c8dcfd" that I've to fix: attr("viewBox") does not return a viewBox but a BBox with the x, y, width and height populated from the viewBox. I'll fix this in the declaration and will modify the pull request accordingly.

**Comment by FlashSystems** [comment]
Ok, done.
I fixed my mistake regarding the "viewBox" parameter of the `attr` method and corrected the test. Sorry for any inconvenience.

**Review by kant2002 — APPROVED** [review]
LGTM

**Pull request merged**
