### PR TITLE
Update [shopify-buy] updateLineItems to accept CheckoutLineItemUpdateInput

### PR DESCRIPTION
**Pull request by nrandell**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [checkoutLineItemsUpdate](https://shopify.dev/docs/api/storefront/2023-01/mutations/checkoutLineItemsUpdate)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by nrandell** [comment]
The tests don't need changing as the current test works ok. Our code uses the line item id to update the line item which is allowed in the api.

**Comment by straiforos** [comment]
> The tests don't need changing as the current test works ok. Our code uses the line item id to update the line item which is allowed in the api.

Thank you!

**Comment by straiforos** [comment]
Approved

**Review by openminder — APPROVED** [review]
Approved

**Review by martin-badin — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by nrandell** [comment]
Ready to merge

**Pull request merged**
