### PR TITLE
[chai-http] Updated FinishedRequest interface

### PR DESCRIPTION
**Pull request by CaselIT**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR closes the issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18576

### CODE REVIEW

**Comment by BendingBender** [comment]
Fixes #18576.

**Comment by Nemo157** [comment]
LGTM

**Comment by CaselIT** [comment]
Sorry to bother you @Nemo157 , can you add a 👍 so the bot typescript-bot can add the labels?

Thanks

**Comment by Nemo157** [comment]
:+1:

**Comment by CaselIT** [comment]
Sorry to spam here,
@RyanCavanaugh maybe the typescript-bot should recognize also LGTM and similar. 
I could not find its repository. If there is one I can try to add it

**Pull request merged**
