### PR TITLE
Add type for NodeJS `process.arch`

### PR DESCRIPTION
**Pull request by mpoc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v17.x/api/process.html#processarch
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by SimonSchick** [comment]
I think we should avoid adding more items to the `NodeJS` scope, and instead keep it in the `process` module if possible.

**Comment by peterblazejewicz** [comment]
Simon, to be clear, you meant exporting a type from a process module? (so kind of like `Process.Architecture`)

**Comment by SimonSchick** [comment]
`import { Architecture } from 'process';`

**Review by mcollina — APPROVED** [review]
lgtm

**Review by LinusU — APPROVED** [review]
Neat 👍

**Review by amcasey — APPROVED** [review]

**Comment by mcollina** [comment]
Ready to merge

**Pull request merged**
