### PR TITLE
[proj4js] Use ES6 export default, to match v2.4

### PR DESCRIPTION
**Pull request by wulfsberg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/proj4js/proj4js/pull/246
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
👍 Looks good to me, it does seem like `proj4` is using `export default proj4`.

https://github.com/proj4js/proj4js/blob/master/lib/index.js#L21

**Comment by aluanhaddad** [comment]
I really wish it were, but if you install it and look in the `package.json` indicated main it in UMD format.

**Comment by wulfsberg** [comment]
Hm, this is problematic, then.
Digging into it, is seems the ES6 version comes from the `lib/index.js` bundled with the release. It is referenced from the `module` field in package.json, which, as I understand it, is a rollup-specific way of publishing it.
I am a little unsure of the status of the `module` field, but that is the version my (webpack-based) environment picks up.

I ran into the issue with imports in https://github.com/proj4js/proj4js/issues/247, and was directed to use the ES6-style import, so it didn't occur to me that it was *not* actually "officially" published that way in the main entry.

It seems that the proj4 authors definitely *intend* it to be used that way, given their answers in various issues, but which should DefinitelyTyped support? The semi-official `module` version, which I suspect is the one most people who use TypeScript will hit, or the "strictly-by-spec" main entry?

**Comment by aluanhaddad** [comment]
If the following works at runtime (irregardless of typescript errors)
```ts
import proj4 from 'proj4';
console.log(proj4.defs);
```
Then your loader or bundler supports synthetically importing CommonJS modules as a synthetic default as per the intended Node CJS <-> ESM interop.

If that is the case, it works, throwing no errors at runtime, simply inform TypeScript that you are using such a loader or bundler in `tsconfig.json`
```json 
{
  "compilerOptions": {
    "allowSyntheticDefaultImports: true
```
or via the command line `tsc --allowSyntheticDefaultImports`

**Comment by wulfsberg** [comment]
Doh, I had completely forgotten about `allowSyntheticDefaultImports`.
You're right. That's probably the right way to do it in this case.
I'll close this pull request, then, and spread the word.

**Pull request closed without merging**
