### PR TITLE
[@types/wavesurfer.js] Add barRadius to the list of available options

### PR DESCRIPTION
**Pull request by kubk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
- The change introduced in this commit: https://github.com/katspaugh/wavesurfer.js/commit/0a3f609afcef8bf54ea69abebef16d4f7e3f1211
- Released here: https://github.com/katspaugh/wavesurfer.js/pull/1783/files
- Here is the link to the docs: https://wavesurfer-js.org/docs/options.html
image
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by higuri — COMMENTED** [review]
I'm sorry for the late reaction.
Does your changeset cover all changes from 2.0 to 3.2 ?
Thanks!

**Comment by kubk** [comment]
Hi @higuri 
I've only added `barRadius` option. This change was introduced in 3.2 version of wavesurfer.js, that's why I bumped the version number of type definitions. I can try to add more types to this commit, but first, I'd like to ask how did you generate type definitions for this library? Did you use some generators such as [dts-gen](https://github.com/Microsoft/dts-gen)? Wavesurfer.js uses JSDoc to document function signatures, maybe we can leverage it? Since this is a major version update there might be plenty of changes in API, manually checking types of each property, method or class might be error-prone. Thank you.

**Comment by orta** [comment]
This PR looks good to me as it is  - you're welcome to look into [using `allowJs` and `declaration`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs) to try generate the types from the JS in the future

**Comment by kubk** [comment]
@orta Thank you, I'll look into it. :+1:

**Pull request merged**
