### PR TITLE
jquery-colorpicker update

### PR DESCRIPTION
**Pull request by daareiza**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by daareiza** [comment]
@pushplay Hi, sorry but I don't have a proper answer, in my implementation I have to use any because the TS compiler complained about that.

**Comment by andy-ms** [comment]
What does the code using this look like? This is probably a problem with the code using the definition rather than with the definition itself. (If you need a quick fix you can cast to `any` in your own code, but there's probably an even better solution.)

**Comment by daareiza** [comment]
@andy-ms thanks, I will try it at night

**Comment by mhegazy** [comment]
@daareiza  🔔

**Comment by daareiza** [comment]
@andy-ms thanks for the suggestion, it works perfectly.
@pushplay type reverted 👍

**Comment by mhegazy** [comment]
thanks!

**Pull request merged**
