### PR TITLE
@types/three: Wring typings for ObjectLoader.parseImages #16914

### PR DESCRIPTION
**Pull request by LebedenkoN**
fixed typings for THREE.ObjectLoader.parseImages

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by efokschaner** [comment]
Thanks for the fix @LebedenkoN :+1:

**Comment by andy-ms** [comment]
Can you use a more specific type than `{}`?

**Comment by LebedenkoN** [comment]
@andy-ms `{}` can be changed to `Object` or `any`

**Comment by andy-ms** [comment]
Those aren't more specific though -- doesn't this function return something in particular?

**Comment by LebedenkoN** [comment]
@andy-ms this function returns object, properties of which are persed images

**Comment by andy-ms** [comment]
Do you know what the keys of the object will be?
Even if you don't, you can still use `{ [key: string]: ParsedImage }`.

**Comment by efokschaner** [comment]
@andy-ms, while it would be nice to see the types fleshed out more here, @LebedenkoN 's proposed change is at least more correct than it was previously which is why I'd be fine with the change.

@LebedenkoN, that said, I did some digging and it appears that parseImages delegates to `ImageLoader.load` (see https://github.com/mrdoob/three.js/blob/b4054f2b6f8a3d7698bab8ec1bb6da9b231ac6b5/src/loaders/ObjectLoader.js#L438 and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/89578a5f1eee1319358e4e493cfa6f6db03ad4c2/types/three/three-core.d.ts#L2123) and so the values of the object probably have the type `HTMLImageElement`. I would appreciate if you could confirm this in practice and change it to `{ [key: string]: HTMLImageElement }` if that's correct.

**Comment by LebedenkoN** [comment]
@efokschaner the result type was changed to { [key: string]: HTMLImageElement }. Thank you for your help.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
