### PR TITLE
node: improved EventEmitter's definition with this-typing

### PR DESCRIPTION
**Pull request by chrootsu**

### CODE REVIEW

**Comment by jvilk** [comment]
:+1: to `browserify.d.ts` changes. Couldn't have done it any better myself!

**Comment by ccurrens** [comment]
:+1: on request.d.ts. Actually, the whole thing LGTM.

**Comment by jedmao** [comment]
:+1:

**Comment by Zenorbi** [comment]
:+1: to apn/apn.d.ts

**Comment by rhysd** [comment]
:+1: to `github-electron.d.ts`

**Comment by psnider** [comment]
:+1: to mailparser/mailparser.d.ts

**Comment by tkqubo** [comment]
:+1: to `gulp-nodemon/gulp-nodemon.d.ts` and `ssh2/ssh2.d.ts`

**Comment by nicojs** [comment]
:+1: to parse5/parse5.d.ts
this is much better!

**Comment by swook** [comment]
:+1: to `noble/noble.d.ts`

**Comment by kant2002** [comment]
:+1: to `steam/steam.d.ts`

**Comment by joeskeen** [comment]
:+1:

**Comment by vvakame** [comment]
:+1: thanks all!

**Pull request merged**
