### PR TITLE
introduce ag-Grid typings

### PR DESCRIPTION
**Pull request by ceolter**
Typings for project www.ag-grid.com

### CODE REVIEW

**Comment by vvakame** [comment]
*ag-grid/ag-grid.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/ag-grid
  * http://bower.io/search/?q=ag-grid
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (ag-grid/ag-grid-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by ceolter** [comment]
hi @vvakame, is this PR been rejected? thanks.

**Comment by vvakame** [comment]
http://definitelytyped.org/guides/contributing.html please check this document.

**Comment by aciccarello** [comment]
@ceolter You still need tests. Basically, just add some of the documentation from the webpage and reference the d.ts file. You might need to add types in the tests but you're showing the d.ts file matches the syntax used by the library. I can put something together if you'd like.

**Comment by ceolter** [comment]
@vvakame @aciccarello i've put tests around the GridOptions and ColDefs objects, by checking each attribute that i expect exists on the definition. Is this enough?

**Comment by vvakame** [comment]
:+1: thanks mate!

**Comment by aciccarello** [comment]
woot! That's working for me.

**Comment by ceolter** [comment]
Excellent, thanks all.

**Comment by tbenbrahim** [comment]
What is the reason for this, is this really part of ag-grid?
`declare function require(name: string): any;`, line 1467
I have to use workarounds to use this file due to conflicts

Thanks

**Pull request merged**
