### PR TITLE
[solverjs] Add new package

### PR DESCRIPTION
**Pull request by martin-badin**
Discussion: #57153
Documentation: https://github.com/suryapratapsinghsuryavanshi/solverjs

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test solverjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## solverjs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/solverjs@latest/))
was missing the following properties:
1. info
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ab9b848e575ab1a7c3239af0a3c0107a1942b1c
</p>

**Comment by peterblazejewicz** [comment]
this works, but one could just recreate modules with proper exports and re-exports:
```ts
// area.d.ts
export function sqKmToSqMe(sqkm: number): number;
export function sqKmToSqYd(sqkm: number): number;
....
```
```ts
// length.d.ts
export function kmToMe(km: number): number;
export function kmToCm(km: number): number;
...
```
`index.d.ts`
```ts
// Type definitions for solverjs 3.28
// Project: https://github.com/suryapratapsinghsuryavanshi/solverjs
// Definitions by: Martin Badin <https://github.com/martin-badin>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export * from './area';
export * from './length';
....
````

**Comment by martin-badin** [comment]
Hi @peterblazejewicz. Your comments are always helpful. Thank you so much. I updated PR.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thx!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
