### PR TITLE
[tea-merge] Remove attribution

### PR DESCRIPTION
**Pull request by pluma**
The author of these typings (@mihhail-lapushkin) has asked for me to remove his attribution on his behalf because he is no longer actively using TypeScript. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25177#issuecomment-383220067 for his authorisation of this change.

This PR only removes the attribution, it doesn't make any other changes.

### CODE REVIEW

**Comment by pluma** [comment]
@RyanCavanaugh I'm not sure how to fix the lint error. The linter complains because there's no attribution but that's the point of the PR. Is there a default for unowned typings or do I have to adopt it?

**Comment by RyanCavanaugh** [comment]
@pluma We need the header line but I think you can write
```
Definitions by: No one <null@example.com>
```
and everything should work as expected

**Comment by pluma** [comment]
That seems to have worked.

**Comment by pluma** [comment]
:tada:

**Pull request merged**
