### PR TITLE
[Knex] add batch builder typedef for knex

### PR DESCRIPTION
**Pull request by baronfel**
Per [the docs](http://knexjs.org/#Utility-BatchInsert) Batch Insert exists.

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: (http://knexjs.org/#Utility-BatchInsert)[http://knexjs.org/#Utility-BatchInsert]
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by baronfel** [comment]
Looks like it didn't like the format of my changes to the header?

**Comment by tkqubo** [comment]
Maybe you need a space between your name and bracketed URL?

https://github.com/Microsoft/types-publisher/blob/d12147faa56a6ab0768d018258b72a3e685e3530/src/lib/header.ts#L7-L11
https://github.com/Microsoft/types-publisher/blob/d12147faa56a6ab0768d018258b72a3e685e3530/src/lib/header.ts#L99-L107

**Comment by baronfel** [comment]
Hah, looks like that fixed it.  Thanks for the pointer, @tkqubo.

**Comment by tkqubo** [comment]
👍

**Pull request merged**
