### PR TITLE
Fix typing error in PolygonGraphics [Cesium]

### PR DESCRIPTION
**Pull request by golyalpha**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Discussion on AnalyticalGraphicsInc/cesium](https://github.com/AnalyticalGraphicsInc/cesium/issues/6831)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by hnipps — CHANGES_REQUESTED** [review]
I think the line should be `outlineColor: Color` - You should remove the 'Property' part altogether.

**Comment by golyalpha** [comment]
@hnipps It can be both Property and Color, as Cesium devs themselves stated.

**Comment by hnipps** [comment]
@golyalpha I agree that’s what the documentation says, but I haven’t seen an instance where you actually get a Property back if you access this at runtime. It’ll be a Color, and the type definition should reflect that.

**Comment by golyalpha** [comment]
Well, I've provided everything I can, that says that Property should be kept in the typedef, but since you haven't changed your mind, I have corrected it so it's according to your liking.

**Review by hnipps — APPROVED** [review]
Thanks for making the change.

**Pull request merged**
