### PR TITLE
Add fatal and ignoreBOM parameters to the TextDecoderOptions and Text…

### PR DESCRIPTION
**Pull request by xiaoxizi2303**
Add fatal and ignoreBOM parameters to the TextDecoderOptions and TextDecoder interfaces

### CODE REVIEW

**Comment by xiaoxizi2303** [comment]
Please review this PR.

**Comment by pine** [comment]
Hello @xiaoxizi2303.

Do you have any reference material for the changes? That would be helpful for review. Thank you.

**Comment by xiaoxizi2303** [comment]
> Hello @xiaoxizi2303.
> 
> Do you have any reference material for the changes? That would be helpful for review. Thank you.

You can refer to the https://github.com/DefinitelyTyped/DefinitelyTyped/commit/207749d1fabbf72c898123c88c98016c86a8e461 file submitted this time. The source database also has these attributes: https://github.com/inexorabletash/text-encoding/blob/master/test/test-misc.js.

**Review by nwmqpa — APPROVED** [review]

**Comment by xiaoxizi2303** [comment]
> ⏳ Hi @xiaoxizi2303,
> 
> It's been a few days since this PR was approved by nwmqpa and we're waiting for a DT maintainer to give a review.
> 
> If you would like to short-circuit this wait, you can edit some of the [test files](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-my-package-teststs) in the package that verify how the `.d.ts` files work. This would allow the PR to be merged by you or the DT module owners after a re-review.

The original test file contains the test of the added interface.

**Comment by xiaoxizi2303** [comment]
Hello, do you have any questions about this PR?

**Review by rbuckton — APPROVED** [review]

**Comment by xiaoxizi2303** [comment]
Ready to merge

**Pull request merged**
