### PR TITLE
[toobusy-js] Adding overload for getter with no args

### PR DESCRIPTION
**Pull request by davemneo**
Before this update, TS threw this error:
error TS2554: Expected 1 arguments, but got 0.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.typescriptlang.org/docs/handbook/functions.html#overloads
- [x] Increase the version number in the header if appropriate.

Continuous Integration / travis-ci / pr  failed... hmmm

### CODE REVIEW

**Review by BendingBender — CHANGES_REQUESTED** [review]
I'm not sure what you're trying to achieve here. All of the getters you've changed already had the first parameter marked as optional. What was the issue with that?

**Comment by BendingBender** [comment]
What TS version did you try to use these definitions with?

**Comment by davemneo** [comment]
tsc --version
    Version 2.9.2

**Comment by atd-schubert** [comment]
I don't think you need this change. You should try it again with an updated TypeScript version, but as far as I know version 2.9.2 should also have no problems with the notation of optional parameters.

Maybe you should proof if the error is really caused by this type-definition.

**Comment by davemneo** [comment]
updated: deleting my yarn.lock did the trick got me the latest version. 0.o

**Comment by davemneo** [comment]
I wish there was a better way to get latest changes of definitions.

**Pull request closed without merging**
