### PR TITLE
fix: FieldRoleType enum

### PR DESCRIPTION
**Pull request by 0o001**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## loopback ([<kbd>unpkg</kbd>](https://unpkg.com/browse/loopback@latest/))
was missing the following properties:
1. version
1. registry
1. errorHandler
1. faviconFile
1. remoteMethod

<details>
<summary>as well as these 15 other properties...</summary>
<p>template, createModel, configureModel, findModel, getModel, getModelByType, createDataSource, memory, DataSource, Connector, Memory, Mail, Remote, GeoPoint, ValidationError</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7a3e6667e3bd430180841841aff542195c4294bf
</p>

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## loopback ([<kbd>unpkg</kbd>](https://unpkg.com/browse/loopback@latest/))
was missing the following properties:
1. version
1. registry
1. errorHandler
1. faviconFile
1. remoteMethod

<details>
<summary>as well as these 15 other properties...</summary>
<p>template, createModel, configureModel, findModel, getModel, getModelByType, createDataSource, memory, DataSource, Connector, Memory, Mail, Remote, GeoPoint, ValidationError</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 257bb026930e69b5b71315db9e8abff0e3e0904c
</p>

**Review by kattsushi — APPROVED** [review]
LGTM

**Review by karimsa — COMMENTED** [review]
The loopback change seems fine to me, but I don't use tableau so hard for me to confirm that. On their official website, it says:

> One of the following values: DIMENSION, MEASURE, UKNOWN

Source: https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_ref.htm

Is this auto generated from the types?

**Comment by 0o001** [comment]
> > The loopback change seems fine to me, but I don't use tableau so hard for me to confirm that. On their official website, it says:
> > > One of the following values: DIMENSION, MEASURE, UKNOWN
> > 
> > 
> > Source: https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_ref.htm
> > Is this auto generated from the types?
> 
> Oh, i see that place. I think it might not be right to change UKNOWN, but I can't say the same for loopback "application".

https://loopback.io/doc/en/lb4/Authorization-overview.html

image

**Comment by karimsa** [comment]
If you can remove the change to UNKNOWN, I can approve

**Review by kattsushi — APPROVED** [review]

**Review by gabritto — CHANGES_REQUESTED** [review]
@0o001 please provide evidence of why the tableau change should be made. It's possible it's correct, but I couldn't verify it.

**Comment by 0o001** [comment]
@karimsa @gabritto 

https://tableau.github.io/extensions-api/docs/enums/tableau.fieldroletype.html
https://github.com/tableau

I guess "unknown" is the correct one.

**Review by gabritto — APPROVED** [review]

**Comment by 0o001** [comment]
> @0o001: Everything looks good here. I am ready to merge this PR (at [e44b874](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e44b8740326902719782e4ee55be7ad74609a4ee)) on your behalf whenever you think it's ready.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️

Ready to merge

**Pull request merged**
