### PR TITLE
Node: specify `UnhandledRejectionListener` `reason` param type

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fourth attempt at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33189

See my response to @SimonSchick's comments: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32835#issuecomment-462671097

### CODE REVIEW

**Comment by OliverJAsh** [comment]
😢 I used a unique branch name. What's going on?

**Comment by eps1lon** [comment]
@OliverJAsh Maybe regenerate the commit sha e.g.
```bash
git commit --allow-empty -m 'trick ts-bot'
```

**Comment by amcasey** [comment]
There are known CI issues, but reopening to give reviewers another chance.

**Comment by Flarna** [comment]
@amcasey this one has already a followup: #33195

**Comment by amcasey** [comment]
@Flarna thanks!

**Pull request closed without merging**
