### PR TITLE
initial support fot the serverless.com framework

### PR DESCRIPTION
**Pull request by jatsrt**

### CODE REVIEW

**Comment by andy-ms** [comment]
Please use the [instructions](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) for creating a new package. `tslint.json` should be `{ "extends": "../tslint.json" }`.

I also noticed that this definition only defines interfaces. What does the `serverless` module export? The test should import a value from the `serverless` module and use it in some way, not just define constants.

**Comment by jatsrt** [comment]
Perhaps this is a non-starter then.  The serverless framework is not a lib, but a framework that provides a consistent interface.  Essentially there is no lib, but there are defined interfaces as part of the framework.  

This is an attempt to type those interfaces.

Let me know if this is not appropriate.

**Comment by andy-ms** [comment]
You can have a definition with only interfaces, but I assumed that this was for the `serverless` NPM package, which appears to export a class. If you aren't typing the `serverless` package, then this should have a different name. If you are typing the `serverless` package, you could also consider [bundling](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) the types with it.

**Comment by jatsrt** [comment]
OK, maybe drop this then.  It is for the serverless package, but that only exports what is needed for their CLI.  But that generates a framework/context that your code runs in.  This has certain inputs/outputs that can be types and are specific to serverless, but are not part of the "library".  

As opposed to typing their framework and their code base.

I'll pass this around with the serverless team a bit more first.

**Pull request closed without merging**
