### PR TITLE
Fix heremaps group get bounds

### PR DESCRIPTION
**Pull request by Kuraikiko**
See https://developer.here.com/documentation/maps/3.1.17.0/api_reference/H.map.Group.html#getBoundingBox

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by DaSchTour** [comment]
Were there any changes to the Here Maps API regarding this or was this just wrong?

**Review by DaSchTour — APPROVED** [review]

**Comment by denyo** [comment]
It looks like there were more breaking changes in the here api: https://developer.here.com/documentation/maps/3.1.0.0/release_notes/topics/api-changes.html
So I guess it would make sense to integrate all of them and perhaps also call it a breaking change.

**Comment by Kuraikiko** [comment]
I found this issue from february - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42456 , I guess it can be closed afterwards.

**Comment by elibarzilay** [comment]
@Kuraikiko: is this not ready to be merged yet?

**Comment by Kuraikiko** [comment]
Ready to merge

**Pull request merged**
