### PR TITLE
[react-table] Properly type default export

### PR DESCRIPTION
**Pull request by dyst5422**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/react-tools/react-table/blob/dadfcc121cb48ab4ab7b78372fe25ddc8d1da0a4/src/index.js>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by dyst5422** [comment]
No idea why the test is failing for the version parsing

**Comment by royxue** [comment]
@dyst5422 did you try to run it in your local???

**Comment by dyst5422** [comment]
Yes. It fails locally on that same version parsing. I suppose I haven't tried running just the react-table test yet.

**Comment by royxue** [comment]
@dyst5422 
And why you wanna set the version as TS 2.5 but not 2.3? Any specific reasons?

**Comment by dyst5422** [comment]
I happened to test it using 2.5.

**Pull request closed without merging**
