### PR TITLE
react-select: Fixed renderer handlers return types.

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by MartynasZilinskas — APPROVED** [review]

**Comment by MartynasZilinskas** [comment]
LGTM :+1:

**Comment by skirsdeda** [comment]
@GiedriusGrabauskas why not define one more common type, e.g. `HandlerElementResult` since they are all the same.

**Comment by GiedriusGrabauskas** [comment]
@skirsdeda, updated.

**Comment by skirsdeda** [comment]
👍 Great.

**Pull request merged**
