### PR TITLE
Add factory function for mCustomScrollbar

### PR DESCRIPTION
**Pull request by delphinus**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/5f1bb9d0c234b0404492b3a2dd8e872d33a87122/jquery.mCustomScrollbar.js#L43-L43
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@delphinus please address the CI test failures

**Comment by delphinus** [comment]
Sorry, I've fixed. @mhegazy

**Comment by delphinus** [comment]
Woops, I noticed I added unneeded formatting fix. I will remove it...

**Comment by delphinus** [comment]
fixed!

**Comment by delphinus** [comment]
ping @mhegazy

**Pull request merged**
