### PR TITLE
[@types/fluent-ffmpeg] Fix return for PresetFunction. Fix typos. Closes #52550

### LINKED ISSUE #52550: [@types/fluent-ffmpeg] Support the second kind of presets
- [x] I tried using the `@types/fluent-ffmpeg` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tcaesvk, @DingWeizhe, @mabidina, @hados99, @Buzzertech.

In the `fluent-ffmpeg` [documentation](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#presetpreset-use-fluent-ffmpeg-preset) it is said:

> The second kind of preset is preset functions. To use those, pass a function which takes an FfmpegCommand as a parameter.

And a code example:

```JS
function myPreset(command) {
  command.format('avi').size('720x?');
}

ffmpeg('/path/to/file.avi').preset(myPreset);
```

According to the example code, the preset function should return `void`.

We have the following type
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7e4e74d63eb242a0c0bdee70f914fc8d6c0178e/types/fluent-ffmpeg/index.d.ts#L42 which does not match the expected signature of the preset function. I believe it should be

```JS
type GetPreset = (command: FfmpegCommand) => void;
```
Also, in this case the type name itself is not very much suitable, it should be something like `PresetFunction`.

Besides that, I guess there are two typos here (pr**o**set and p**n**reset):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7e4e74d63eb242a0c0bdee70f914fc8d6c0178e/types/fluent-ffmpeg/index.d.ts#L362-L363

There is another method spelled properly which seems to be a duplicate of the misspelled one mentioned above:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7e4e74d63eb242a0c0bdee70f914fc8d6c0178e/types/fluent-ffmpeg/index.d.ts#L323

### PR DESCRIPTION
**Pull request by danmana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#presetpreset-use-fluent-ffmpeg-preset and https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/options/misc.js#L20
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Closes #52550

### CODE REVIEW

**Comment by elibarzilay** [comment]
Making it possible to merge, so up to you if you want to continue waiting for a review...

**Comment by danmana** [comment]
Ready to merge

**Comment by danmana** [comment]
Ready to merge

**Comment by danmana** [comment]
Ready to merge

**Pull request merged**
