### PR TITLE
[yandex-maps] Fix module format, fix each()

### PR DESCRIPTION
**Pull request by kachkaev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/LayerCollection-docpage/#LayerCollection__methods-summary
-  ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

/cc @Delagen @gastwork13

### CODE REVIEW

**Review by delagen — APPROVED** [review]
Seems correct. But I dont't sure it need export as module

**Review by delagen — CHANGES_REQUESTED** [review]
Please fix CI errors

**Comment by kachkaev** [comment]
@Delagen without exporting the namespace I'm getting this error: https://github.com/Delagen/typings-yandex-maps/issues/3

Ideally, we should remove `ymaps` namespace completely as recommended by [`export-just-namespace`](https://github.com/Microsoft/dtslint/blob/master/docs/export-just-namespace.md). However I'm just ignoring this rule for now to avoid a massive diff. A few other modules do the same: [🔎](https://github.com/DefinitelyTyped/DefinitelyTyped/search?utf8=✓&q=export-just-namespace).

**Comment by kachkaev** [comment]
Should be good to go I guess 🕺

**Comment by kolkov** [comment]
Hi! I use to correct this issue (solution from Google maps typings)/ All works fine.
`/// <reference types="@types/yandex-maps" />`

**Comment by kachkaev** [comment]
Hi @kolkov! Could you please elaborate on how `/// <reference types="@types/yandex-maps" />` can help? [Typings for google-maps](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-maps/index.d.ts) Do the same thing in the end of the file.

**Comment by kolkov** [comment]
> Hi @kolkov! Could you please elaborate on how `/// <reference types="@types/yandex-maps" />` can help? [Typings for google-maps](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-maps/index.d.ts) Do the same thing in the end of the file.

https://stackoverflow.com/questions/36064697/how-to-install-typescript-typings-for-google-maps

**Comment by kachkaev** [comment]
I believe it's just a workaround for these lines (not related to Yandex Maps):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7fe167420c7d8b3e18b9c27f2afc97eef0fff69c/types/google-maps/index.d.ts#L10-L12

**Comment by Delagen** [comment]
Reference via types need only project name without "@types/" prefix

**Review by delagen — APPROVED** [review]
Seems correct now

**Pull request merged**
