### PR TITLE
[tabulator-tables] - Export TabulatorOptions from Tabulator.Options

### PR DESCRIPTION
**Pull request by Jojoshua**
This allows us to now access the Tabulator options as it was hidden under the namespace before.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] This is a pure TS improvement to allow Options be accessible

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## tabulator-tables ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tabulator-tables@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'tabulator-tables'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5af5a1ce1fffb8b2064fbc5c0551819f46784348
</p>

**Review by mike-lischke — COMMENTED** [review]
Nothing wrong with this patch, but I wonder why this change was necessary. Putting classes + interfaces in a namespace is a pretty common practice, so I don't see a real advantage.

**Comment by Jojoshua** [comment]
> Nothing wrong with this patch, but I wonder why this change was necessary. Putting classes + interfaces in a namespace is a pretty common practice, so I don't see a real advantage.

The issue is that if you need to use Options as a standalone object, swap objects, or allow a user to extend those options before instantiating there was no way to define it. 

The following wont work
const defaultTableOptions:Tabulator.Options ={}

So now we can do
import { TabulatorOptions } from 'tabulator-tables';
const defaultTableOptions:TabulatorOptions ={}

new Tabulator(tableElement,defaultTableOptions);

**Review by mike-lischke — APPROVED** [review]

**Comment by Jojoshua** [comment]
Ready to merge

**Pull request merged**
