### PR TITLE
Add support for v5 of node-uuid

### PR DESCRIPTION
**Pull request by cjbarth**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by cjbarth** [comment]
The file `v5.d.ts` is not unused. It is to support a namespace `uuid/v5` as in `import uuidv5 = require('uuid/v5')`. How can I address this and get the checks passing?

**Comment by RyanCavanaugh** [comment]
@cjbarth Please fix the failures indicated in the Travis CI log.

**Comment by cjbarth** [comment]
@RyanCavanaugh I'm not sure how to. The file is needed, and I've tried several different ways of convincing Travis that it is in use. Suggestions?

**Comment by RyanCavanaugh** [comment]
@andy-ms do we need to make the parser also include files that are part of the test suite?

**Comment by andy-ms** [comment]
Normally we consider a file as unused if it isn't reachable from `index.d.ts`, but it can be overridden by explicitly adding it to `tsconfig.json`.

**Pull request merged**
