### PR TITLE
@types/rosie - make attrs and opts optional for build and buildList

### PR DESCRIPTION
**Pull request by dotbear**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by subvertallchris** [comment]
@dotbear Thanks! Could you throw quick examples of this into the tests file? It'll hopefully keep someone from accidentally refactoring this out again in the future.

**Comment by dotbear** [comment]
@subvertallchris good call!

**Comment by dotbear** [comment]
@subvertallchris I have added some "tests" :)

**Comment by subvertallchris** [comment]
Haha, yeah, the type def "tests" really are... something... But it's better than nothing.

**Comment by subvertallchris** [comment]
👍 on this

**Pull request merged**
