### PR TITLE
Add middleware definition to aws-serverless-express

### PR DESCRIPTION
**Pull request by jcaffey**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/awslabs/aws-serverless-express/blob/v2.1.3/middleware.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@jcaffey  the version needs to be updated to `major.minor`

**Comment by jcaffey** [comment]
@mhegazy patch version removed. Please re-review.

**Comment by andy-ms** [comment]
Sorry, there was a build failure affecting recent PRs. Fixed by #15125. Please rebase to the latest `master` to fix test failures.

**Comment by jcaffey** [comment]
@andy-ms / @mhegazy, rebased/squashed.

**Pull request merged**
