### PR TITLE
feat(puppeteer): 2.0

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Rinse and repeat (one last time) https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40061

Changes:
 - Removed 0.x
 - Updated 1.x to 2.x in place

Rationale:
 - 0.x (unstable) is 2 years old and no longer maintained, the package will remain
 - 1.x Moved to own folder, package currently has ~250k downloads per week and will probably need minor maintenance in the future.
 - 2.x VERY few changes major release was due to dropping node v6. Used opportunity to bump to TS 3.0 and change some instances of `any` to `unknown` for improved type safety.

### CODE REVIEW

**Comment by SimonSchick** [comment]
@RyanCavanaugh what's the current timeline for allowing removing typings? Would you recommend I alter my PR to *not* remove the v0 ones?

**Comment by Aankhen** [comment]
I’m waiting with bated breath for this one!

As an aside, if you’ve bumped up the minimum TypeScript version to 3.0, it might make sense to use tuple types for things like `page.evaluate`. I have a WIP version of this, if you’re interested.

**Comment by SimonSchick** [comment]
Feel free to suggest the diff and/or point me to your fork with the commit (I can cherrypick it)

**Comment by Aankhen** [comment]
> Feel free to suggest the diff and/or point me to your fork with the commit (I can cherrypick it)

I’ve pushed the (no longer WIP) changes [to my fork](https://github.com/Aankhen/DefinitelyTyped/commits/add-ts3.1-puppeteer-types). I was going to open a PR against your branch, but that became difficult because I had also rebased to pull in the changes from `master`, so the diff was huge. Note that I separated my changes into two commits: one two create a `ts3.1` directory with the same definitions, and one to actually use TS3.1 features in that directory. (Otherwise the specific changes would have been lost.)

**Comment by Aankhen** [comment]
The correct branch: https://github.com/Aankhen/DefinitelyTyped/commits/add-ts3.0-puppeteer-types

**Comment by SimonSchick** [comment]
@Aankhen I tried to manually apply the diff from the last commit, unfortunately I'm getting a few errors, specifically on page.evaluate* calls, see my `feat/puppeteer-2.0-tuples` branch :)

**Comment by Aankhen** [comment]
> @Aankhen I tried to manually apply the diff from the last commit, unfortunately I'm getting a few errors, specifically on page.evaluate* calls, see my `feat/puppeteer-2.0-tuples` branch :)

Where are you getting the errors? If you mean you’re getting TypeScript errors complaining about the rest args, I got the same ones, because it won’t be parsed by 3.0 by default. I believe it will only be parsed by 3.0 when you run the tests.

**Comment by SimonSchick** [comment]
I'm using 3.6 in vscode, I'd ask you to checkout my branch and see for yourself.

**Comment by Aankhen** [comment]
> I'm using 3.6 in vscode, I'd ask you to checkout my branch and see for yourself.

I’ve checked out SimonShick/DefinitelyTyped@3a84f88e and I’ve got `types/puppeteer/index.d.ts` open. I’m not seeing any errors.

**Comment by SimonSchick** [comment]
See 
image

**Comment by Aankhen** [comment]
Thanks! That’s why I was asking where the error was, heh. I spent a few hours on this and fixed that, but the complexity keeps increasing, and it’s contagious. I think it’s something a more experienced developer would have to implement. For the moment, I’m going to drop the idea. Thank you for trying to integrate the changes, though.

**Pull request merged**
