### PR TITLE
fixed palette def.

### PR DESCRIPTION
**Pull request by ghost**
Don't know how that wasn't in there when I versioned it.

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-material/angular-material-0.9.0.d.ts*

to author(@mtraynham). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
usually, We maintain newest versions only.

**Comment by mtraynham** [comment]
:+1: Looks like the PR before this palette definition change is there, so I think you're good.

**Comment by vvakame** [comment]
@mtraynham thanks!
@robertbaker thanks mate!

**Pull request merged**
