### PR TITLE
Remove upstreamed types

### PR DESCRIPTION
**Pull request by BendingBender**
If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
I'm sorry, what is this? What's the purpose of this PR?

**Review by SimonSchick — APPROVED** [review]
Neat.

**Comment by SimonSchick** [comment]
@BendingBender you'll have so specify the actual dependencies in the `package.json` files, you can't reference @types in those.

**Comment by BendingBender** [comment]
@MadaraUchiha I'm removing types for packages that have types bundled with them. There is no need to futher maintain these types on DT.

**Comment by BendingBender** [comment]
@SimonSchick I know, but some of the relesed packages are no longer compatible with the base packages. So I was hoping that I can reference the old DT types for the time being for these packages. I was wrong.

No idea what to do here, I will just leave them alone.

**Comment by sandersn** [comment]
@BendingBender if you want to generate the entire list of superceded types, clone Microsoft/types-publisher and `npm run check` (after running build/parse).

**Pull request merged**
