### PR TITLE
[standard-http-error]: Static Status Message Constants

### PR DESCRIPTION
**Pull request by saiichihashimoto**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/moll/js-standard-http-error#using-with-express
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by saiichihashimoto** [comment]
@roblabat, is there something here I still need to do? I think I did it all correctly.

**Comment by saiichihashimoto** [comment]
Is there a way to rotate reviewers @roblabat? Just wanting to get this out the door.

**Comment by saiichihashimoto** [comment]
Can I expect anything here? Who should I talk to? I have more types for more libraries I want to make sure it's worth it. @DefinitelyTyped @andy-ms @jablko @peterblazejewicz @BendingBender

**Comment by roblabat** [comment]
Sry @saiichihashimoto, I were quite busy those days and this package is not my priority. I approve your PR as soon I'll have check all errors code.

Thanks for your patience and your work on those types.

**Review by roblabat — CHANGES_REQUESTED** [review]
according to [HTTP status code registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) code 425 is associated to "Too Early" message instead of "Unordered Collection". 
Correct this code and it will be ready for me to merge.

**Comment by saiichihashimoto** [comment]
That's true @roblabat, but the values are coming from [here](https://github.com/moll/js-standard-http-error/blob/master/codes.json#L46), being transformed to the constants [here](https://github.com/moll/js-standard-http-error/blob/master/index.js#L42), and are being published in this library according to [this table](https://www.npmjs.com/package/standard-http-error#error-codes). I think it makes sense to follow parity with the library rather than the Http status code registry.

**Comment by roblabat** [comment]
You're right @saiichihashimoto, it seems that nodeJS also implement this table and that "Unordered Collection" error. I agree with you we should be consistent with the library and nodeJS rather than with the HTTP spec.
I'll approve your changes then.
Do you want to add your name to the authors list before I approve then PR ?

**Comment by saiichihashimoto** [comment]
Sure, though I can't seem to find the authors list. How do I do it?

**Comment by roblabat** [comment]
It's in comments at the start of the index file.
Currently it looks like that:

```
// Type definitions for standard-http-error 2.0  
// Project: https://github.com/moll/js-standard-http-error  
// Definitions by: Labat Robin <https://github.com/roblabat>  
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
```

and you can change it to something like that:

```
 // Type definitions for standard-http-error 2.0
 // Project: https://github.com/moll/js-standard-http-error
 // Definitions by: Labat Robin <https://github.com/roblabat>
 //                 [Your name] <[your github profil adress]>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
```

**Comment by saiichihashimoto** [comment]
Done @roblabat!

**Review by roblabat — APPROVED** [review]

**Comment by roblabat** [comment]
Ready to merge

**Pull request merged**
