### PR TITLE
change IAnimateService methods signature

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vvakame** [comment]
*angularjs/angular.d.ts*

to author(@diegovilar). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@mif007 please fix travis ci failed.

**Comment by mif007** [comment]
@vvakame done

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
