### PR TITLE
[@types/k6] Update k6 type definitions for v0.55.0

### PR DESCRIPTION
**Pull request by oleiade**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by mstoykov** [comment]
apperantly I did not add the changes to [54f5a4d](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71141/commits/54f5a4dbb5f7b723b46e807e79cb086bd618f9b7) and had them just staying locally :facepalm:

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/k6/browser/index.d.ts
1. types/k6/test/browser.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 54f5a4dbb5f7b723b46e807e79cb086bd618f9b7
</p>

**Comment by oleiade** [comment]
Cheers @mstoykov, what's the command you ran out of curiosity? Running `pnpm dprint fmt` on my side as suggested was succesful but did nothing 🙂

**Review by mstoykov — APPROVED** [review]

**Comment by mstoykov** [comment]
Ready to merge

**Pull request merged**
