### PR TITLE
Add lory definition file

### PR DESCRIPTION
**Pull request by kubosho**
This is from http://meandmax.github.io/lory/
repo: https://github.com/meandmax/lory

### CODE REVIEW

**Comment by vvakame** [comment]
*lory/lory.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/lory
  * http://bower.io/search/?q=lory
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (lory/lory-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@kubosho thank you for your contributions.
please check this document. http://definitelytyped.org/guides/contributing.html#naming-the-file
rename lory/lory.d.ts to lory.js/lory.js.d.ts https://www.npmjs.com/package/lory.js

**Comment by kubosho** [comment]
@vvakame 
Thanks for your review. I see for document, and fix file names.

**Comment by kubosho** [comment]
@vvakame 
Thanks for your review. I seen a document, and change file & directory names.

**Comment by vvakame** [comment]
@kubosho thanks mate!

**Pull request merged**
