### PR TITLE
Update to winreg 0.0.16

### PR DESCRIPTION
**Pull request by RX14**
Also fixed accidental capitalisation of string.

### CODE REVIEW

**Comment by RX14** [comment]
1. Why does this bot want me to review my own PR
2. Is keeping the old definition file around like this the right thing to do?

**Comment by horiuchi** [comment]
@RX14 Answers:
1. The `dt-bot` assign to original definition file author by the `Definitions by` header.
2. In this case, No, the old version definition file is not required, when it is compatible.

**Comment by RX14** [comment]
Ok, removed the previous file, everything looks good to me. :+1:

**Comment by horiuchi** [comment]
@RX14 Thanks mate!

**Pull request merged**
