### PR TITLE
Update react.d.ts

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Support strict null checks in TypeScript 2.0. https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/

### CODE REVIEW

**Comment by vsiao** [comment]
There's a TS 2.0 branch for this, I believe. This won't pass tests on the master branch.

**Comment by donaldpipowitch** [comment]
Oh! Do you know how I can get the updated definitions then?

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by donaldpipowitch** [comment]
@mhegazy I that an error I can/should fix? @vsiao said there is already a branch for that? And I'm not sure what [these errors](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/146588506#L629) tell me?

```
629 ----------------- For file:fixed-data-table/fixed-data-table-0.4.7.d.ts
630 react/react.d.ts(167,33): error TS1110: Type expected.
```

Is every library in DefinitelyTyped tested against each other? I don't know what is wrong [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/fixed-data-table/fixed-data-table-0.4.7.d.ts).

**Comment by yuit** [comment]
@donaldpipowitch so the `master` branch use TypeScript 1.8 version which doesn't have `null` and `undefined` type so the compiler complains that in such position, you have to supply type not value. However, if you open the PR against `types-2.0` which use TypeScript 2.0 as @vsiao suggests, there will no longer be an error because `null` and `undefined` are both become their own type. 

You will want to close this PR and open a new one against `types-2,0` and the CI-server should pass

**Comment by donaldpipowitch** [comment]
@yuit thank you for this great explanation. I'll do that.

**Pull request closed without merging**
