### PR TITLE
[@types/chromecast-caf-receiver] Extensible customData types

### PR DESCRIPTION
**Pull request by steve-taylor**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [`cast.framework.messages.Track#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.Track#customData)
  - [`cast.framework.messages.TextTrackStyle#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.TextTrackStyle#customData)
  - [`cast.framework.messages.SessionState#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.SessionState#customData)
  - [`cast.framework.messages.QueueItem#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.QueueItem#customData)
  - [`cast.framework.messages.MediaStatus#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.MediaStatus#customData)
  - [`cast.framework.messages.MediaInformation#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.MediaInformation#customData)
  - [`cast.framework.messages.BreakClip#customData`](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.BreakClip#customData)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts
1. types/chromecast-caf-receiver/cast.framework.d.ts
1. types/chromecast-caf-receiver/cast.framework.messages.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 288a9eea50f3ca077f1edc5dca06554c2ca76884
</p>

**Review by Anonymous4078 — APPROVED** [review]

**Comment by steve-taylor** [comment]
@Anonymous4078 after your approval, I [updated formatting](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/288a9eea50f3ca077f1edc5dca06554c2ca76884..3e839fd562138ca24fbf72df78d5cfd91a70769a) by running `pnpm dprint fmt` to remove the related warning on this pull request. I'd appreciate another ✅ when you have a moment.

**Review by Anonymous4078 — APPROVED** [review]

**Comment by steve-taylor** [comment]
Ready to merge

**Comment by cristian-atehortua** [comment]
I think this PR makes custom data types less extensible.

I was using some structure of Generics to type the customData of the media across the project but when updating to this version it's complaining with the TS error `ts(2345)`: `MediaInformationCustomData is assignable to the constraint of type CustomDataType, but CustomDataType could be instantiated with a different subtype of constraint MediaInformationCustomData`.

**Pull request merged**
