### PR TITLE
Fixed Validator API

### PR DESCRIPTION
**Pull request by IOAyman**
Fixed [Validator.js](https://github.com/chriso/validator.js) A.  (Similar to https://github.com/types/npm-validator/pull/4)

### CODE REVIEW

**Comment by tgfjt** [comment]
👍

**Comment by TonyPythoneer** [comment]
This PR is interesting. It encourages what I will do. :smile:

**Comment by IOAyman** [comment]
@TonyPythoneer, Thanks :smile: What are you willing to do?

**Comment by IOAyman** [comment]
#11374 covers this.

**Pull request closed without merging**
