### PR TITLE
[i18next]: `export default` instead of `export =`

### PR DESCRIPTION
**Pull request by emilgpa**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/i18next/react-i18next/issues/627
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by lenovouser — CHANGES_REQUESTED** [review]
There is no default export?

**[`i18next@12.1.0/index.js`](https://cdn.jsdelivr.net/npm/i18next@12.1.0/index.js)**

When I test this in my server side (Node) code it breaks it.

**Comment by emilgpa** [comment]
`i18next@12.1.0` is the old version. The new version (PR) has `export default`.

**Comment by lenovouser** [comment]
@emilgpa https://github.com/i18next/i18next/pull/1142#issuecomment-443525555 - let's see what @jamuhl answers

**Comment by lenovouser** [comment]
Also the `// Type definitions for <package> <x.x>` header needs to correspond to the current version of the package. So it would still stay on `12` in theory.

**Comment by emilgpa** [comment]
I thought that the version was that of the definition and not the package ...My bad.
Anyways, I found that with "esModuleInterop" in "true" it is possible to compile with TypeScript `import i18n from" i18next "` and with `export =` in the definition. It is not necessary to do this pull request due to this option that I found doing not need to change anything but if `i18next` has `module.exports = require ('./ dist / commonjs / index.js'). default;` in the definition should be `export deefault` instead of` export = `.

**Comment by dmradford** [comment]
Also had this issue. I found that changing my import statement fixed the issue for me.

Failed:
import Modal from 'react-modal';

Succeeded
import * as Modal from 'react-modal';

**Comment by jamuhl** [comment]
@dmradford could you eventual give some insights here: https://github.com/i18next/i18next/pull/1142 would make this getting merged on i18next repo itself if working as intended...

**Pull request closed without merging**
