### PR TITLE
Change transaction() autoCallback param type from Blueburd to PromiseLike

### PR DESCRIPTION
**Pull request by 0x6368656174**
`autoCallback` param in `transaction()` must be `PromiseLike` not `Bluebird`, so that you can perform:
````.ts
return sequelize.transaction(async () => {
    //Some code
});
````
Because, `async function` return native promise.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@samuelneff @codeanimal @drinchev @babolivier can you please review.

**Comment by drinchev** [comment]
This is similar to : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16185

Although I think that changing to `PromiseLike` is not the precise way to handle the issue.

Maybe bluebird should be changed to be compatible with `async`, since sequelize is based on bluebird.

**Comment by mhegazy** [comment]
@drinchev is this a 👍  or a 👎 ?

**Comment by drinchev** [comment]
@0x6368656174, last conversation we had in #16185 went in a similar direction. What's different, since then? Have you found something else ?

**Comment by drinchev** [comment]
@mhegazy 👍 , since tests are working

**Comment by 0x6368656174** [comment]
@drinchev, sequelize is based on a `Bluebird` and must return a `Bluebird`. But the input parameters of the functions should be as flexible as possible, therefore, it should be accepted by `PromiseLike`.

The `async` function must always return a global `Promise`, unfortunately, it can not return a `Bluebrid`. I added tests that check the compatibility of the `transactional` method with native `Promise`, `Bluebird`, `Q`, and `async` functions.

Without changing the input parameters of the `transactional` method, the tests do not pass.

**Comment by drinchev** [comment]
Looks good :) Thanks!

**Pull request merged**
