### PR TITLE
[Luxon] Fix DateTime.toObject types to reflect conditional locale output

### PR DESCRIPTION
**Pull request by CarsonF**
Also correct invalid reason and explanation to be nullable.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by CarsonF** [comment]
Ready to merge

**Comment by zub0r** [comment]
@CarsonF This breaks A LOT of stuff.
image

**Comment by CarsonF** [comment]
It was this one actually #64995. See its description for how to adapt to it.

**Comment by CarsonF** [comment]
@zub0r Though your snippet crawled into my mind and I couldn't get it out.
`DateTime.now()` does always return a valid `DateTime`, so `toISO` shouldn't return nullable.
I've opened #65078 to potentially address this.

**Pull request merged**
