### PR TITLE
Added additional parameters for chrome/chrome-app

### PR DESCRIPTION
**Pull request by pyle**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/apps/app_runtime#event-onLaunched

- [x] Increase the version number in the header if appropriate.

## Commit messages
* Added extra parameters to LaunchData per API docs
https://developer.chrome.com/apps/app_runtime#event-onLaunched
* Changed typescript version required to 2.4 since named enums are used
  * Also for sion-chrome since this depends on chrome

* Added new line after newly created enum

### CODE REVIEW

**Comment by couven92** [comment]
changes for `types/chrome/index.d.ts` are fine (obviously! ;) )

this is for reviewers of `types/chrome/chrome-apps.d.ts`.

**Comment by pyle** [comment]
Bumping this :smiley: 

@RReverser Could you please check `types/chrome/{chrome-app.d.ts, index.d.ts}`
@pimterry Can you make sure this doesn't affect your type `types/sinon-chrome/index.d.ts` ?

**Review by pimterry — APPROVED** [review]
Sinon-chrome changes are just a comment with a TS update, totally fbm.

**Comment by uniqueiniquity** [comment]
Waiting on @RReverser approval, despite typescript-bot's confusion.

**Comment by armanio123** [comment]
Hi authors @AdamLay @mzsm @RReverser, could you help us reviewing this PR?

**Pull request merged**
