### PR TITLE
[carbon-components-react] getExpandHeaderProps, make few fields optional as they are in reality

### PR DESCRIPTION
**Pull request by pr0gramista**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/pull/5682/files
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

About the last one. My changes do bring some of the definitions up to date, but I also know that there are missing few exports of the components. I am not able at this moment to track all changes. My changes are backward compatible.

### CODE REVIEW

**Comment by sgregoire** [comment]
Hello, it looks like you are targeting Carbon version 10, this current set of typings is done for Carbon 7 (for now...)

**Review by sgregoire — CHANGES_REQUESTED** [review]
Hello, it looks like you are targeting Carbon version 10, this current set of typings is done for Carbon 7 (for now...).

**Comment by pr0gramista** [comment]
@sgregoire  I don't know what I should do now.
These changes are not breaking anything, but they also don't update everything up to Carbon 10. Unfortunately, I am not able to do that 😔 

Should I close this PR?

**Comment by sgregoire** [comment]
Hello, please have a look to this PR #43925.

kalbert312 is upgrading Carbon from V7 to V10.

Once it's merged, please have a look if your changes are still required, if so, please poke one of the maintainers.

**Pull request closed without merging**
