### PR TITLE
D3 version 4 Follow-up (Chores, Bug Fixes, Enhancements, New Modules)

### PR DESCRIPTION
**Pull request by tomwanzek**
This PR is related to issue #9936.

The PR adds definitions and tests for (in alphabetical order):
- **d3-geo** (Thanks to @Ledragon)
- **d3-hsv** (Thanks to @arrayjam)
- **d3-selection-multi** (Thanks to @gustavderdrache)

The PR also contains follow-up changes identified as chores in PR #10228, bug fixes and enhancements.
Details are contained in the commit messages.

This PR brings `DefinitelyTyped/types-2.0` to the same versions of module definitions as release v1.22.0 of the collaborative staging repo used for the initial drafting process, [d3-v4-definitelytyped](https://github.com/tomwanzek/d3-v4-definitelytyped). The exception to this statement are the separate D3 module additions contained in PR #10453, which are still subject to the legacy dependency issue.

For review/merge: @gustavderdrache @mhegazy @andy-ms @paulvanbrenk 

Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.t

Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tomwanzek** [comment]
Reviewed the Travis log. All errors are unrelated to this PR from what I saw.

**Comment by gustavderdrache** [comment]
:+1: Code looks good to me.

Strange that the tests are failing, though. Wonder if you just need to merge a more up-to-date copy of types-2.0, since that branch is building cleanly.

**Comment by paulvanbrenk** [comment]
The tests failures are caused by a different issue... there is some case-sensitivity happening on the test server, which is not on your local machine.

**Comment by tomwanzek** [comment]
Thanks to both of you@gustavderdrache and @paulvanbrenk .

**Comment by tomwanzek** [comment]
@paulvanbrenk thanks for the merge. Is it possible to activate the webhook/publish these changes to npm~types? It does not seem to have run automagically. Thanks a lot in advance.

**Comment by paulvanbrenk** [comment]
No idea... @andy-ms or @RyanCavanaugh  can you answer the question about publishing?

**Pull request merged**
