### PR TITLE
Lodash: Added detailed types for flowRight

### PR DESCRIPTION
**Pull request by jtmthf**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/#flowRight

Updated typings on `flowRight` to match the verbosity of `flow`. This should help with users of Apollo as their `compose` function uses `flowRight` internally.

### CODE REVIEW

**Comment by thorn0** [comment]
Looks goods, but I've noticed that `_.flowRight((x: string) => x.length, () => 0)` compiles without errors. Can we make the catch-all overload a bit less catch-all to actually catch errors like this? If it's too complex (which it probably is), then let's merge this first.

**Comment by jtmthf** [comment]
@thorn0 It seems like what is needed is a catch-all to only kick in when there are over 7 functions and/or over 4 arguments. It looks like this could be done by having a catch-all per number of arguments block. For 0 arguments this seems to work:

```ts
flowRight(f7: (a: any) => any, f6: (a: any) => any, f5: (a: any) => any, f4: (a: any) => any, f3: (a: any) => any, f2: (a: any) => any, f1: (a: any) => any, ...funcs: Array<Many<(a: any) => any>>): () => any;
```

With `_.flowRight((x: string) => x.length, () => 0)` the error is then
```
Argument of type '() => number' is not assignable to parameter of type '(a1: {}, a2: {}) => string'.
  Type 'number' is not assignable to type 'string'.
```

I'll try applying this to all sections of `flow` and `flowRight` and then also add some test cases for that.

**Comment by jtmthf** [comment]
After updating the generic versions to be "less generic", it uncovered a few errors in the tests which I have now updated and am using as validation of the change.

**Review by thorn0 — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Pull request merged**
