### PR TITLE
Updated hls.js

### PR DESCRIPTION
**Pull request by kuczek**
* added Hls class audioTrack property
* added Hls class audioTracks property

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/video-dev/hls.js/issues/2611
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by drax98** [comment]
Please restore all syntax changes, you are probably not using linter properly.

**Comment by peterblazejewicz** [comment]
These juse look like DT default prettier formatting being applied.

**Review by adripanico — CHANGES_REQUESTED** [review]
If this is a PR to add definitions, do not make all those syntax/format refactors. Please revert syntax/format changes and create a different PR for that. It's hard to review a change of this size. Thanks.

**Comment by djeikyb** [comment]
After cleaning up the extraneous formatting, I get a patch like:

```
From 1b2565d905b97e0ef3033f7839271745f5c27bd4 Mon Sep 17 00:00:00 2001
From: jace42@gmail.com
Date: Wed, 3 Jun 2020 18:13:59 -0700
Subject: [PATCH] add audiotrack properties to hls.js

Addresses https://github.com/video-dev/hls.js/issues/2611
---
 types/hls.js/hls.js-tests.ts |  3 +++
 types/hls.js/index.d.ts      | 13 ++++++++++++-
 2 files changed, 15 insertions(+), 1 deletion(-)

diff --git a/types/hls.js/hls.js-tests.ts b/types/hls.js/hls.js-tests.ts
index e4d2af8c..cf7bd34f 100644
--- a/types/hls.js/hls.js-tests.ts
+++ b/types/hls.js/hls.js-tests.ts
@@ -39,6 +39,9 @@ if (Hls.isSupported()) {
         console.log('src: ', hls.media.src);
     }
 
+    const audioTracks = hls.audioTracks;
+    hls.audioTrack = audioTracks[0];
+
     hls.once(Hls.Events.MANIFEST_PARSED, (event: "hlsManifestParsed", data: Hls.manifestParsedData) => {
         video.play();
     });
diff --git a/types/hls.js/index.d.ts b/types/hls.js/index.d.ts
index 276ea772..f3d94bf1 100644
--- a/types/hls.js/index.d.ts
+++ b/types/hls.js/index.d.ts
@@ -1,10 +1,11 @@
-// Type definitions for hls.js 0.12
+// Type definitions for hls.js 0.13
 // Project: https://github.com/video-dev/hls.js
 // Definitions by: John G. Gainfort, Jr. <https://github.com/jgainfort>
 //                 Johan Brook <https://github.com/brookback>
 //                 Adrián Caballero <https://github.com/adripanico>
 //                 Alexey I. Berezin <https://github.com/beraliv>
 //                 Arkadiusz Babiarz <https://github.com/drax98>
+//                 Krystian Kuczek <https://github.com/kuczek>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // TypeScript Version: 2.4
 
@@ -1714,6 +1715,16 @@ declare class Hls {
      * position of live sync point (ie edge of live position minus safety delay defined by hls.config.liveSyncDuration)
      */
     readonly liveSyncPosition: number;
+    /**
+     * get : array of audio tracks exposed in manifest
+     */
+    readonly audioTracks: any[];
+    /**
+     * get/set : audio track id (returned by).
+     * Returns -1 if no track is visible.
+     * Set to -1 to hide all audio tracks.
+     */
+    audioTrack: number;
     /**
      * get : array of subtitle tracks exposed in manifest
      */
-- 
2.26.2

```

which I believe matches the latest released state – 0.13.2 – of the hls.js lib: https://github.com/video-dev/hls.js/blob/v0.13.2/src/hls.ts#L594

**Pull request closed without merging**
