### PR TITLE
Add Tip and VisuallyHidden to @wordpress/components

### PR DESCRIPTION
**Pull request by sirbrillig**
This PR adds types for two components in the `@wordpress/components` package.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: `Tip` is [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tip/index.js) and `VisuallyHidden` is [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/visually-hidden/component.js) (note that the latter has a [special type](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/ui/context/wordpress-component.ts) copied directly from the source into this repo).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header (the definition claims to be for version 14, which was [released on May 14, 2021](https://www.npmjs.com/package/@wordpress/components/v/14.0.0), and I believe that these both existed before that version: `Tip` [in 2019](https://github.com/WordPress/gutenberg/pull/16813) and `VisuallyHidden` in [April 2021](https://github.com/WordPress/gutenberg/commit/fda8d09c0d34fd863c8b20459bf9a1be2638dd9a#diff-c0bd4c7fa173293e03ab5f39f1c84b358453d1598d9bb688c1ab545881088b37)).

### CODE REVIEW

**Review by maldito-dot — COMMENTED** [review]
@maldito-dot

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__components@latest/))
was missing the following properties:
1. ComboboxControl
1. DuotoneSwatch
1. DuotonePicker
1. Guide
1. GuidePage

<details>
<summary>as well as these 3 other properties...</summary>
<p>TextHighlight, ToolbarGroup, ToolbarItem</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 429f9add370c513567d4db9afde7092ee3d8277a
</p>

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Comment by sirbrillig** [comment]
Ready to merge

**Pull request merged**
