### PR TITLE
[helmet] Make kebab-cased script-, style-, and worker-src arrays of HelmetCspDirectiveValue

### PR DESCRIPTION
**Pull request by TDurrr1**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/helmetjs/helmet/blob/master/middlewares/content-security-policy/README.md, which itself uses a couple of these definitions albeit in camel case
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by EvanHahn** [comment]
@TDurrr1 Before I review this: Helmet 4 bundles TypeScript types. Is this intended for `helmet@3`, or `helmet@4`?

**Comment by TDurrr1** [comment]
Sorry, I had no idea. Now that I'm looking at the bundled types for `helmet@4`, this would be for `helmet@3`, I suppose.

**Comment by EvanHahn** [comment]
Sounds good. I'll plan to review today or tomorrow.

**Review by EvanHahn — APPROVED** [review]

**Comment by EvanHahn** [comment]
Ready to merge

**Comment by TDurrr1** [comment]
Ready to merge

**Pull request merged**
