### PR TITLE
Enable strictNullChecks

### PR DESCRIPTION
**Pull request by jablko**
```Shell
sed --in-place /strictNullChecks/s/false/true/ $(git ls-files '*/tsconfig.json')
```

This makes the automated tests a bit stricter. Before the change, if someone used the types in a project where `strictNullChecks: true`, the DefinitelyTyped automation wouldn't catch breaking changes to the types.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Polite question: should we go through filed CI build, find specific type one is referenced in, and fix?
https://gist.github.com/mikepea/863f63d6e37281e329f8#it-is-not-the-reviewers-responsibility-to-test-the-code

**Comment by tkrotoff** [comment]
Why not go with `strict: true`? It's a bit more work but we gain in a single line: --noImplicitAny, --noImplicitThis, --alwaysStrict, --strictBindCallApply, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization

**Comment by SimonSchick** [comment]
@tkrotoff In the past the TS team has added new rules to `strict` that would've potentially broken builds, for small projects being on the bleeding edge works well, for a project the size of DT it doesn't.

**Comment by peterblazejewicz** [comment]
> sed --in-place /strictNullChecks/s/false/true/ $(git ls-files '*/tsconfig.json')

I think this replaces all versions, I think 'v*' should be really excluded from change. I have to review a project that previous version (`v*`) spans years back.

Can this change be done in more focused steps, starting for current version only?:

```bash
git ls-files '*/tsconfig.json' ':!:*/v*/*tsconfig.json'
```

**Comment by jablko** [comment]
@peterblazejewicz Thanks for reviewing this! I think it's safe and positive to apply this change to that years-old version because `tsconfig.json` isn't distributed with the types. The change (I believe) affects the automated tests only, not the definitions themselves.

At best it makes the tests slightly stricter. At worst it has no effect (except to increase alignment with the [project's advice](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#some-packages-have-no-tslintjson-and-some-tsconfigjson-are-missing-noimplicitany-true-noimplicitthis-true-or-strictnullchecks-true)).

**Comment by jgonggrijp** [comment]
@jablko for my understanding, what is your approach? Do you just enable the rule everywhere it is disabled, and then disable it again for the packages that break?

**Comment by jablko** [comment]
@jgonggrijp Yes, that's it.

**Comment by simonbuchan** [comment]
I'm a bit confused, this only seems to remove ref types=node?

**Review by LinusU — APPROVED** [review]
😍

**Comment by jablko** [comment]
@simonbuchan That was for another PR, sorry! I've restored the correct changes.

**Pull request closed without merging**
