### PR TITLE
new: Type definitions for phaser

### PR DESCRIPTION
**Pull request by ampled**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

I can't tick the last box in good conscience since these typings are automatically generated by parsing jsdocs and can't have strictNullChecks or strictFunctionTypes set to true in their current state. However these typings are in a usable states and a lot better than having none available, and the jsdocs used to generating these are constantly getting improved.

### CODE REVIEW

**Comment by ampled** [comment]
Looks like it failed lint tests. Would disabling these in tslint.json be okay for now?

**Review by armanio123 — CHANGES_REQUESTED** [review]
@ampled I prefer not to disable the rules unless there's a valid reason for it. Is there any particular rule you're struggling to fix? I can help you with that if necessary.

**Comment by ampled** [comment]
@armanio123 I completely understand. I'll go over the issues and try fixing them.

 The fact is that these typings aren't handwritten but generating by a custom parser that reads jsdoc and outputs these type declarations, and editing these by hand would "defeat the purpose" of all the work put into the parser and jsdocs.

However, I think the benefits of having them published here while the parser is being improved is better than nothing so I'll try fixing the issues.

**Comment by ampled** [comment]
I've re-enabled all the lint-rules I disabled in the first pull request except for `no-single-declare-module` and `no-declare-current-package`. I couldn't quite figure out how to fix them without breaking how the typings are used. I'll gladly accept help or advice on how to fix them.

I also re-enabled `strictNullChecks` and `strictFunctionTypes` in `tsconfig.json`

**Comment by armanio123** [comment]
Thanks for enabling the lint rules, it's a big d.ts file. I'm unsure myself how to fix the last rules as let's mention @DanielRosenwasser , I'm pretty sure he'll be able to help us. 

Other than this I think the PR is good so I'm approving it.

**Review by armanio123 — APPROVED** [review]

**Comment by minestarks** [comment]
Sorry @ampled , this must have taken a lot of effort but it's not a supported use case for DefinitelyTyped, as we don't want to be another source of truth competing with official typings. I would highly recommend directing any contributions to the package itself. Perhaps they could bundle their typings in their npm package?

**Comment by ampled** [comment]
@minestarks Thank you for the response.
I just want to quickly say that I completely understand that this doesn't fit the use case for DefinitelyTyped and I don't mind the PR being rejected.

My goal was to have an easily installable version of the typings available from `@types/phaser` (as most users expect these days) that was "merge compatible" with the official ones. As you can see, it took a lot of work to improve the official ones to make them good enough quality-wise for DT which kind of defeated that goal.

> Perhaps they could bundle their typings in their npm package?

That is the package author's plan. I tried getting them published to allieviate some push/pull between the community that wants easily attainable (and versioned) typings, and the package author that (understandably) don't think they're good enough to be included yet. They're now only available in a separate repo. It's not an ideal situation, but I figured this was worth a shot as a temporary fix.

**Comment by minestarks** [comment]
I'll go ahead and close this PR for maintainability reasons - but I do understand the pain, this happens frequently with other packages too. Hopefully the official typings get to a point soon where they can easily be used!

Thanks @ampled!

**Pull request closed without merging**
