### PR TITLE
Add windowsVerbatimArguments for node child_process

### PR DESCRIPTION
**Pull request by andrewstucki**
To go along with https://github.com/nodejs/node/pull/16299.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/nodejs/node/pull/16299>

### CODE REVIEW

**Comment by andrewstucki** [comment]
Closing because of PR build timeouts

**Comment by andrewstucki** [comment]
Re-opening to re-run failed test because of PR build timeouts

**Comment by andrewstucki** [comment]
I don't think that this is going to pass in travis due to the sheer number of type definitions that are affected by the definitions in `types/node`. The build is timing out while running the tests because it's going through pretty much every single test possible.

**Comment by Flarna** [comment]
If I understand the node source code correct then `exeFile` allows also to specify `windowsVerbatimArguments`.

**Comment by andrewstucki** [comment]
Looks like @Flarna is right. `execFile` doesn't override `shell`, so it should still be valid to pass in `windowsVerbatimArguments`. Updated.

**Review by Flarna — APPROVED** [review]

**Comment by andrewstucki** [comment]
so... wondering what to do with this given that the build can't possibly pass due to the fact that it requires testing 1211 packages and exceeds Travis's time limit for jobs every time it runs?

**Comment by smac89** [comment]
@andrewstucki I believe you can do something like:

Forking the repo, create the travis hook on your account, run the tests there and try to do another commit after that. Travis will be able to skip running the long tests if you have already run it through travis once.

**Comment by andrewstucki** [comment]
@smac89 I enabled travis on my branch and am going to see if it can pass there, but seeing as there appears to be a global travis timeout of 50 mins for jobs and the CI build above was canceled at 49:57, I'm kind of doubtful that I can get the tests to pass there.

**Comment by andrewstucki** [comment]
See #20308

**Comment by RyanCavanaugh** [comment]
@andrewstucki Please fix the failures indicated in the Travis CI log.

**Comment by andrewstucki** [comment]
@RyanCavanaugh as mentioned multiple times, this relates to #20308 -- the build is timing out because of the fact that this is a change to one of the definitions for node which is a dependency of pretty much every other definition in this project. It's not possible to fix because Travis times out before it can finish testing every single type definition.

**Comment by andrewstucki** [comment]
@andy-ms noticed you resolved and merged https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20185

Seeing as this is related because of the Travis timeouts and has sat here untouched for 2 weeks, think you could take a look? Otherwise I think I'm just going to close this PR soon as it looks like it's getting no attention.

**Pull request merged**
