### PR TITLE
[jsrp] Add type definitions

### PR DESCRIPTION
**Pull request by svens-uk**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Welcome back Travis

**Comment by harryshipton** [comment]
Yeah, I don't really know what happened there, but it seemed to resolve itself. For a minute I thought I'd somehow broken something though.

**Comment by harryshipton** [comment]
I've just noticed a type which I didn't update from using `dts-gen`. Please do not merge PR until I've updated it (which should be in a minute or two).

**Comment by harryshipton** [comment]
Okay - the previous typing problems have now been resolved. I've squashed my commits as requested elsewhere in the handbook.

**Pull request merged**
