### PR TITLE
Added AWSLambda.KinesisDataFirehose event type defintions (aws-lambda)

### PR DESCRIPTION
**Pull request by DSegal92**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-kinesis-firehose
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by simonbuchan** [comment]
If this is for the transform flow, it would also be nice if the type names had `Transform` to be a bit clearer where they apply.

**Comment by minestarks** [comment]
@simonbuchan Do you plan to address the merge conflict? Thanks!

**Comment by simonbuchan** [comment]
@minestarks Err, this isn't my PR, I just reviewed it, are you asking me to adopt it?

**Comment by minestarks** [comment]
Oops, meant to ping @DSegal92, got confused.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has merge conflicts and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
