### PR TITLE
Catch up Microsoft Teams SDK with what we support today.

### PR DESCRIPTION
**Pull request by swingtempo**
Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). 
**npm run lint microsoftteams ** didn't do anything. however I did run tsc.

Select one of these and delete the others:

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OfficeDev/microsoft-teams-library-js
- [X ] Increase the version number in the header if appropriate.
- [X ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by ydogandjiev — APPROVED** [review]
Changes are correct and ready to go once tslint issues are fixed.

**Review by davidchesnut — APPROVED** [review]

**Review by davidchesnut — APPROVED** [review]

**Comment by jayongg** [comment]
Thanks!  Do you know when the npm will get updated, and can you confirm it will be version 1.1.0(since I had it as 1.1 in the header)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated

**Comment by jayongg** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
