### PR TITLE
Johnny-Five: Fix piezo methods and allow undefined boards

### PR DESCRIPTION
**Pull request by scottgonzalez**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## johnny-five ([<kbd>unpkg</kbd>](https://unpkg.com/browse/johnny-five@latest/))
was missing the following properties:
1. Color
1. Expander
1. GPS
1. SIP
1. Keypad

<details>
<summary>as well as these 12 other properties...</summary>
<p>LedControl, Light, Repl, Multi, Luxmeter, Magnetometer, Buttons, Leds, Pins, Sensors, Switches, Touchpad</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 88b87ca558071b734eba98ad979b00f7b199bb1e
</p>

**Comment by scottgonzalez** [comment]
@screamz can you review?

**Comment by ScreamZ** [comment]
> @ScreamZ can you review?

Of course

**Review by ScreamZ — APPROVED** [review]

**Comment by scottgonzalez** [comment]
@screamz Sorry, can you review again? I had to touch the test file to make the bot happy 🙄

**Comment by ScreamZ** [comment]
@scottgonzalez got it ! Do you have discord or some way to chat with you, as we are the two left people alive using Johnny five I might have some questions time to time 😆

**Review by ScreamZ — APPROVED** [review]

**Comment by scottgonzalez** [comment]
Ready to merge

**Comment by scottgonzalez** [comment]
@screamz I'm not on discord, but I use plenty of other chat apps. Send me an email and we'll find something that works.

**Pull request merged**
