### PR TITLE
fix chai-json-schema styling

### PR DESCRIPTION
**Pull request by vvakame**
Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `npm run lint -- package-name` if a `tslint.json` is present.

### CODE REVIEW

**Comment by andy-ms** [comment]
Why not make for `master`? We'd like to get rid of `types-2.0` once we've gotten rid of all PRs targeted for it.

**Comment by ulrichheiniger** [comment]
What is the reason for removing the module declaration for "chai-json-schema"?
`declare module "chai-json-schema"`

With the module declaration it can be imported like this (as in the test file **chai-json-schema-tests.ts**):

`import ChaiJsonSchema = require('chai-json-schema');`

What is the correct way of importing it if it is not a module? (Sorry I'm quite new to Typescript and writing type definitions).

**Comment by andy-ms** [comment]
It still declares a module since it's named `chai-json-schema/index.d.ts` and has `export = ` on the top-level. So the tests will still work.

**Comment by ulrichheiniger** [comment]
Thanks for the fast answer. I was not aware of that. I just tried it in my application and it works fine.

**Review by ulrichheiniger — APPROVED** [review]

**Pull request merged**
