### PR TITLE
[d3-contour] Add Definitions

### LINKED ISSUE #16243: [d3-contour] Add Definitions
Add TS definitions for **[d3-contour](https://github.com/d3/d3-contour)** module.

Self-assigned @tomwanzek

### PR DESCRIPTION
**Pull request by tomwanzek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

_Unable to run lint script locally. Script fails before testing definitions_

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

This PR adds definitions for [**d3-contour**](https://github.com/d3/d3-contour)

Closes #16243. Related to #11365  and #11366.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@gustavderdrache @Ledragon If either of you, or both, would like to be added as  co-maintainer, please let me know. For now these should be good to go.

**Comment by tomwanzek** [comment]
Thx @mhegazy for the extremely speedy turnaround! T

**Comment by Ledragon** [comment]
Did not check the module yet, but you can add me to give you some air :-)

**Comment by tomwanzek** [comment]
@Ledragon Thx 🕺 I am going going to push a minor "chore" PR to **d3-geo** shortly and send it to you for  review (very limited effort). I will combine the change with adding you as a co-maintainer for **d3-contour**.

**Comment by Ledragon** [comment]
Reviewed (well, more like approved, not much to be said)

**Pull request merged**
