### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by siavelis**
#13273

### CODE REVIEW

**Comment by andy-ms** [comment]
Looks like this pulled in a lot of commits. Could you try rebaseing so that the only commit here is yours?

**Comment by siavelis** [comment]
Ok. I fetched from types-2.0 the latest changes and cherry-picked the appropriate commit. Sorry for the inconvinience. I did the change using github's inline tool and I didn't see the bunch of commits after pressing the 'pull&request' button.

**Comment by andy-ms** [comment]
Could you change this so that it changes `react-bootstrap-table/index.d.ts` instead of adding a new file?

**Comment by siavelis** [comment]
Done

**Pull request merged**
