### PR TITLE
[pem] Update typings to 1.14.8

### PR DESCRIPTION
**Pull request by meekay**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/Dexus/pem/blob/v1.14.8/lib/pem.js
  - https://dexus.github.io/pem/jsdoc/module-pem.html#.checkPkcs12
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by meekay** [comment]
Hi @PopeFelix @tony19 @DethAriel, can someone please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66704) for `@types/pem`? Thank you!

**Review by kpeters-cbsi — COMMENTED** [review]
This looks good, but I'd really prefer to see `ecparam` have a more explicit type.

**Comment by PopeFelix** [comment]
My comments as @kpeters-cbsi stand. I'd like to see an explicit shape for `ecparam` in `createEcparam()` instead of `any`.

**Review by PopeFelix — APPROVED** [review]
My comments as @kpeters-cbsi stand. I'd like to see an explicit shape for `ecparam` in `createEcparam()` instead of `any`, but otherwise this looks good.

**Comment by meekay** [comment]
> My comments as @kpeters-cbsi stand. I'd like to see an explicit shape for `ecparam` in `createEcparam()` instead of `any`, but otherwise this looks good.

Thanks, I'll look into it. I'm not using that method myself so I included it for completeness using `createDhparam()` as a model, which also uses `any`. If I can't figure it out I'll merge as-is.

**Comment by kpeters-cbsi** [comment]
> > My comments as @kpeters-cbsi stand. I'd like to see an explicit shape for `ecparam` in `createEcparam()` instead of `any`, but otherwise this looks good.
> 
> Thanks, I'll look into it. I'm not using that method myself so I included it for completeness using `createDhparam()` as a model, which also uses `any`. If I can't figure it out I'll merge as-is.

It looks like it takes the form: 
```
type ECParameter = { ecparam: string };
```
This is based upon my reading of [createEcparam](https://dexus.github.io/pem/jsdoc/pem.js.html#line155) and a practical demonstration of this method in 
[the attached script](https://github.com/DefinitelyTyped/DefinitelyTyped/files/12664253/curves.js.txt)

**Comment by meekay** [comment]
I updated it before I saw your comment, looks like they're both just base64 strings. I left the callback type anonymous. Would you prefer that I give it a type alias (exported or not) or nah?

**Comment by kpeters-cbsi** [comment]
Go ahead and give it a type alias, please.

**Comment by kpeters-cbsi** [comment]
> Go ahead and give it a type alias, please.

No, scratch that. It's good as is.

**Review by kpeters-cbsi — APPROVED** [review]

**Review by PopeFelix — APPROVED** [review]

**Comment by PopeFelix** [comment]
Ready to merge

**Pull request merged**
