### PR TITLE
[react-native] Added missing importantForAutofill for TextInput

### PR DESCRIPTION
**Pull request by BenWildeman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/textinput#importantforautofill
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by BenWildeman** [comment]
side note, at the beginning of the file, shouldn't this be changed from `// Type definitions for react-native 0.57` to `// Type definitions for react-native 0.59` ?

**Comment by alloy** [comment]
> side note, at the beginning of the file, shouldn't this be changed from `// Type definitions for react-native 0.57` to `// Type definitions for react-native 0.59` ?

That depends. Is this API not available in RN 0.57?

**Review by alloy — CHANGES_REQUESTED** [review]
Thanks!

Could you add some test coverage for this?

**Comment by BenWildeman** [comment]
@alloy appears as though this was added into 0.59 so yeah, this won't be available in 0.57. the types here already references `autoCompleteType` which were probably also added into 0.59 (it's undocumented on the react-native website) so I'm surprised that the version hasn't got a bump yet

**Comment by alloy** [comment]
Cool, thanks for bringing this up. Please do bump it then 👍

**Comment by patrickomeara** [comment]
Can we get this added now?

https://github.com/facebook/react-native/blob/7a8e10dac83b6a43e4cea7e92df0dcfbcf3ad3ac/Libraries/Components/TextInput/TextInput.js#L382-L388

**Review by alloy — APPROVED** [review]

**Pull request merged**
