### PR TITLE
Improve stompjs typings.

### PR DESCRIPTION
**Pull request by JimiC**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

This PR improves the typings for the `connect` function.

### CODE REVIEW

**Comment by JimiC** [comment]
👍

**Comment by andy-ms** [comment]
Tested manually.

**Comment by JimiC** [comment]
@andy-ms Thanks a lot for overseeing this personally. Any ETA when this is going to be published to `@types`?

**Comment by andy-ms** [comment]
It's published.

**Pull request merged**
