### PR TITLE
extend react-google-recaptcha with div props

### PR DESCRIPTION
**Pull request by smujmaiku**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [passing props directly to the containing div](https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha.js#L144)

Closes: #58374

### CODE REVIEW

**Review by martin-badin — APPROVED** [review]

**Review by RohrerF — APPROVED** [review]
Thanks for your contribution @smujmaiku 🎉

**Comment by smujmaiku** [comment]
Ready to merge

**Comment by ChrisCrossCrash** [comment]
Thanks for your work on this, but I'm having some problems with my project after this PR was merged.

With `@types/react-google-recaptcha` at version 2.1.2 it works fine, but when I install version 2.1.3 I get the following error:

```
> Executing task: yarn run build <

yarn run v1.22.17
$ next build
info  - Loaded env from C:\Users\Chris\Sync\PythonProjects\chriskumm.com-nextjs\.env.local
Failed to compile.

./components/ContactForm/ContactForm.tsx:154:17
Type error: No overload matches this call.
  Overload 1 of 2, '(props: ReCAPTCHAProps | Readonly<ReCAPTCHAProps>): ReCAPTCHA', gave the following error.
    Type 'RefObject<ReCAPTCHA>' is not assignable to type '((string | RefObject<ReCAPTCHA> | ((instance: ReCAPTCHA | null) => void)) & (string | ((instance: HTMLDivElement | null) => void) | RefObject<...>)) | null | undefined'.
      Type 'RefObject<ReCAPTCHA>' is not assignable to type '((instance: ReCAPTCHA | null) => void) & RefObject<HTMLDivElement>'.
        Type 'RefObject<ReCAPTCHA>' is not assignable to type '(instance: ReCAPTCHA | null) => void'.
          Type 'RefObject<ReCAPTCHA>' provides no match for the signature '(instance: ReCAPTCHA | null): void'.
  Overload 2 of 2, '(props: ReCAPTCHAProps, context: any): ReCAPTCHA', gave the following error.
    Type 'RefObject<ReCAPTCHA>' is not assignable to type '((string | RefObject<ReCAPTCHA> | ((instance: ReCAPTCHA | null) => void)) & (string | ((instance: HTMLDivElement | null) => void) | RefObject<...>)) | null | undefined'.

  152 |             {process.env.NODE_ENV !== 'development' && (
  153 |               <ReCAPTCHA
> 154 |                 ref={recaptchaRef}
      |                 ^
  155 |                 size='invisible'
  156 |                 sitekey={recaptchaSiteKey}
  157 |               />
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run build" terminated with exit code: 1.
```

The site works fine with the latest version of `react-google-recaptcha` and version 2.1.2 of `@types/react-google-recaptcha`. 

[Here's a link](https://github.com/ChrisCrossCrash/chriskumm.com-nextjs/commit/5e8de62f016284a35446f8dce4e31900d2bd70e2) to a commit where `@types/react-google-recaptcha` works fine with 2.1.2 (installed) but breaks when you update it to 2.1.3. Maybe I'm just doing something wrong.

Thanks for your help.

**Comment by smujmaiku** [comment]
You are correct, `ref` should have been part of the list of omits along with `onUpdate`. I opened up another PR to address that for you: #58556

**Comment by ChrisCrossCrash** [comment]
@smujmaiku Thanks so much for your help and hard work. I've tested the project I linked to earlier with the changes you made in your PR, and it works great!

**Pull request merged**
