### PR TITLE
Add missing semicolon in ui-grid.d.ts file

### PR DESCRIPTION
**Pull request by labrute**

### CODE REVIEW

**Comment by joeskeen** [comment]
:+1: Thanks for catching that!

**Comment by labrute** [comment]
it's nothing, just less red with tslint ;)

**Comment by btesser-r7** [comment]
lgtm

**Comment by btesser-r7** [comment]
@labrute it looks like some of the placement of the semicolons is invalid

**Comment by horiuchi** [comment]
@labrute Thanks mate!

**Pull request merged**
