### PR TITLE
Improved service typings.

### PR DESCRIPTION
**Pull request by deskoh**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
See description below.

Current typings consists of a catch-all for any service name:

```TypeScript
export interface Application<ServiceTypes = any> extends EventEmitter {

    service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;

    // vvv: Catch-all for any service name
    service (location: string): Service<any>;
}

```

This allows service type to resolve if no `ServiceType` is specified.

```TypeScript
const app = feathersExpress(feathers());
let service1 = app.service('messages'); // service1: Service<any>
```

However, if `ServiceType` is specified, invalid service name should not be resolved:

```TypeScript
type Message = { text: string };
type App = Application<{ messages: Message }>;

const app2 = feathersExpress(feathers()) as App;
let service3 = app2.service('messages'); // service3: Service<Message>
let service4 = app2.service('message');  // service4: never <- Will resolve to Service<any> for current typings
```

Defaulting the `ServiceType` to `{}` and modifying the 'catch-all' typings can fulfill the above:

```TypeScript
export interface Application<ServiceTypes = never> extends EventEmitter {

    service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;

    // vvv: Modified catch-all for service name if `ServiceType` is not provided,
    service(location: string): keyof ServiceTypes extends never ? Service<any> : never;
}
```

### CODE REVIEW

**Review by TimMensch — COMMENTED** [review]
Do we really want to bump our TypeScript version to 2.8?

**Comment by deskoh** [comment]
> Do we really want to bump our TypeScript version to 2.8?

@TimMensch Yup. Conditional types used below were introduced in [TypeScript 2.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html).

```ts
service(location: string): keyof ServiceTypes extends never ? Service<any> : never;
```

**Comment by TimMensch** [comment]
The nature of my question was "are we going to be breaking the types for people using TypeScript < 2.8"?

**Comment by deskoh** [comment]
Eliminating the catch-all `Service<any>` type did caught errors of service names for an existing project.

**Comment by Ismail-codinglab** [comment]
@deskoh can you please add `.watch()` from `feathers-reactive` to Service as a method
`watch(any): any;` will do.
source: https://github.com/feathersjs-ecosystem/feathers-reactive

**Comment by deskoh** [comment]
@Ismail-codinglab `feathers-reactive` typings is already provided. See https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/index.d.ts.

**Comment by Ismail-codinglab** [comment]
How do i make it work?
image
image

**Comment by deskoh** [comment]
Any code repo to reproduce? By right the types should resolve automatically.

**Comment by Ismail-codinglab** [comment]
You are correct.

I should check what I am missing. Thank you sir.

image

**Comment by Ismail-codinglab** [comment]
I guess a version mismatch because @types/feathersjs__feathers@3.1.4 won't work with feathers-reactive@0.8.1 but 3.1.5 will

**Pull request merged**
