### PR TITLE
#11535 - Added missing method definition  for datePicker

### PR DESCRIPTION
**Pull request by tkarthick81**
Added below method definitions for **datePicker** in **JQueryUI**
- _getInst
- _formatDate
- _adjustDate
- _get
- _selectDay
- _hideDatepicker
- _getDaysInMonth

### CODE REVIEW

**Comment by tkarthick81** [comment]
@vvakame This request is pending for long, when will it get merged?

**Comment by johnnyreilly** [comment]
I think that perhaps it shouldn't be; it exposes the internals of jQueryUI which (unless I misunderstand) aren't part of the official API.

**Comment by yuit** [comment]
Hi, @tkarthick81. I really not familiar with this lib but from what I am looking at (http://api.jqueryui.com/datepicker/) I can't find the definition of method you added. Let me know if I misunderstand.

**Comment by johnnyreilly** [comment]
Closing for reasons given.

**Pull request closed without merging**
