### PR TITLE
[ioredis] Update types to match version 4.17.1 of the ioredis library

### PR DESCRIPTION
**Pull request by asyrique**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/luin/ioredis/commit/ad5b45587b2e378c15fa879cc72580c391c3c18d
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

Opening this PR because I need a second pair of eyes and some assistance. When I run `npm run lint ioredis`, I keep getting this error.
```
ERROR: 703:32  unified-signatures  This overload and the one on line 702 can be combined into one signature with an optional parameter.
```

Looking at the relevant lines:
```typescript
auth(password: string): Promise<string>;
auth(username: string, password: string): Promise<string>;
```
I'm not sure how to combine them, as what has happened is the library update introduced a new optional parameter `username` which should be passed as the first argument, and `password` should be passed either as the first argument when no username is passed, or as the second one when `username` is passed.

adding `?` to the username argument raises another Typescript error, which is that a required parameter cannot follow an optional one in arguments.

I'm a bit stumped here, as I can't think of any way these 2 lines can be combined, but Typescript somehow thinks it can, and would appreciate any suggestions on how to proceed, as right now, the lint run is erroring out.

Thanks.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ioredis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ioredis@latest/))
was missing the following properties:
1. createClient
1. defaultOptions
1. ScanStream
1. Pipeline
1. AbstractConnector

<details>
<summary>as well as these 5 other properties...</summary>
<p>SentinelConnector, SentinelIterator, ReplyError, Promise, print</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5172906d2ad32b060a4c5ce2a58fa247b0c4a446
</p>

**Comment by asyrique** [comment]
Hi,
I merged the overloads so that I could get some human attention on this PR, but I don't think this is the right solution as now if a someone using and IDE with Intellicode, they will see suggestions to put in `username` as the first param rather than password, which should be the first when only password is passed.

I've left the original overload which when uncommented causes the overload error from tslint commented here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44998/files#diff-77c12eda472c636dbbde3195da016159R703

**Comment by elibarzilay** [comment]
Re-ping @plantain-00 @chrisleck @aliarham11 @br8h @palindrom615 @reconbot @funthing @iamolegga @tingwai-to @pettyalex @SimonSchick @tianlinle @demian85 @alavers @ClaudiuCeia

**Comment by ClaudiuCeia** [comment]
Hey, sorry, I saw this earlier but forgot to chime in. 

I think you probably figured it out, but here goes. The way the default lint rules are written, it's optimized for reducing the number of function signatures. So for the two signatures, it suggests the function could be written as:

```ts
auth(foo: string, bar?: string): Promise<string>;
```

That makes sense from a type perspective (either one, or two string arguments), but it doesn't make sense from a documentation point of view. We don't have named arguments in Typescript, so from TS point of view, `auth(foo: string): Promise<string>` and `auth(bar: string): Promise<string>` are the same. 

With the current rules, we're left with the option of typing this as:

```ts
auth(usernameOrPassword: string, password?: string): Promise<string>;
```

However that's quite crappy, so I think the best option in this case is optimizing for developer experience and disabling the `unified-signatures` rule. Can you please change `tslint.json` to:

```json
{
  "extends": "dtslint/dt.json",
  "rules": {
	"unified-signatures": false,
  }
}
```

This would allow typing the overloads like you did, which is much nicer for IDE auto-completion. 

Alternatively, you can just ignore the rule inline with:

```ts
// tslint:disable-next-line unified-signatures
```

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Requesting changes on behalf of @ClaudiuCeia.

> Alternatively, you can just ignore the rule inline with:
> 
> ```
> // tslint:disable-next-line unified-signatures
> ```

☝️ please do this instead of changing dtslint.json.

Thanks!

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by asyrique** [comment]
Ready to merge

**Pull request merged**
