### PR TITLE
add undefined as possible setPosition-parameter

### PR DESCRIPTION
**Pull request by mogoh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html#setPosition>>

As described in the API, setPosition allows undefined as parameter. Thus the little change.

### CODE REVIEW

**Comment by hanreev** [comment]
@mogoh FYI, this definition is generated using generator script and `undefined` literal was intentionally deleted. If not, there would be a lot of type casting especially when return type might be `undefined`.

Casting `undefined` as `any` would be the best approach instead of unifying `undefined` with another type. For this case, you can simply use
```js
overlayObject.setPosition(undefined as any);
```

**Comment by mogoh** [comment]
@hanreev I did not know that. What generator script generates the definitions?

> If not, there would be a lot of type casting especially when return type might be undefined.

I guess this is not the right place to discuss that design decision and for return types this sounds plausible, but as parameter type I don't see the benefit from 

~~~typescript
overlayObject.setPosition(undefined as any);

//...

setPosition(position: Coordinate): void;
~~~

over

~~~typescript
overlayObject.setPosition(undefined);

//...

setPosition(position: Coordinate | undefined): void;
~~~

Anyway, thanks for your help. I think everything else should be discussed over at [github.com/openlayers/openlayers](http://github.com/openlayers/openlayers), right?

**Comment by hanreev** [comment]
@mogoh at least your pull request must cover all unified `undefined` parameter type to make this definition consistent.

Here is the list of method and function that use unified `undefined` type:
- ol/Feature~Feature#setId
- ol/format/Feature~FeatureFormat#adaptOptions
- ol/format/KML~createFeatureStyleFunction
- ol/format/KML~createFeatureStyleFunction
- ol/format/KML~createNameStyleFunction
- ol/format/KML~findStyle
- ol/format/KML~writeScaleTextNode
- ol/format/TopoJSON~readFeatureFromGeometry
- ol/format/TopoJSON~readFeaturesFromGeometryCollection
- ol/format/WFS~WFS#setFeatureType
- ol/format/WFS~getTypeName
- ol/geom/SimpleGeometry~SimpleGeometry#setLayout
- ol/Image~ImageWrapper
- ol/ImageBase~ImageBase
- ol/interaction/Interaction.rotate
- ol/interaction/Interaction.rotateWithoutConstraints
- ol/interaction/Interaction.zoom
- ol/interaction/Interaction.zoomWithoutConstraints
- ol/layer/Base~BaseLayer#setExtent
- ol/layer/Vector~VectorLayer#setRenderOrder
- ol/layer/Vector~VectorLayer#setStyle
- ol/Overlay~Overlay#getRect
- ol/Overlay~Overlay#getRect
- ol/Overlay~Overlay#updateRenderedPosition
- ol/Overlay~Overlay#setElement
- ol/Overlay~Overlay#setMap
- ol/Overlay~Overlay#setPosition
- ol/PluggableMap~PluggableMap#setSize
- ol/PluggableMap~PluggableMap#setTarget
- ol/proj.createProjection
- ol/render/canvas.drawImage
- ol/render/Feature~RenderFeature
- ol/render/ReplayGroup~ReplayGroup#getReplay
- ol/rotationconstraint.disable
- ol/rotationconstraint.none
- ol/source/ImageArcGISRest~ImageArcGISRest#setUrl
- ol/source/ImageWMS~ImageWMS#setUrl
- ol/source/Source~Source#setAttributions
- ol/source/Source~adaptAttributions
- ol/style/IconImage~IconImage
- ol/style/RegularShape~RegularShape#render_
- ol/style/Stroke~Stroke#setLineCap
- ol/style/Stroke~Stroke#setLineDashOffset
- ol/style/Stroke~Stroke#setLineJoin
- ol/style/Stroke~Stroke#setMiterLimit
- ol/style/Stroke~Stroke#setWidth
- ol/style/Style~Style#setRenderer
- ol/style/Style~Style#setZIndex
- ol/style/Text~Text#setFont
- ol/style/Text~Text#setRotation
- ol/style/Text~Text#setScale
- ol/style/Text~Text#setText
- ol/style/Text~Text#setTextAlign
- ol/style/Text~Text#setTextBaseline
- ol/View~View#constrainCenter
- ol/View~View#constrainResolution
- ol/View~View#constrainRotation
- ol/View~View#setCenter
- ol/View~View#setResolution

-

**Comment by mogoh** [comment]
@hanreev we do not need to discuss if my pull request is ok. It can be closed and discarded. If the type definitions are auto generated anyway than there is no point in changing this anyway.

But please tell me, where is the type definition generating script.

**Comment by hanreev** [comment]
@mogoh oh sorry, i forgot to tell you. [https://github.com/hanreev/types-ol](https://github.com/hanreev/types-ol)

**Comment by mogoh** [comment]
@hanreev thank you

**Comment by hanreev** [comment]
@mogoh u're welcome. i'll try to modify the generator script to include `undefined` parameter type

**Comment by hanreev** [comment]
#37406 covers all unified `undefined` parameter type.

**Comment by mogoh** [comment]
@hanreev Wow, thank you for your work! :heart:

**Pull request closed without merging**
