### PR TITLE
Remove upstreamed typings for cash (cash-dom on NPM)

### PR DESCRIPTION
**Pull request by chocolateboy**
If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---
This PR removes typings for cash ([cash-dom](https://www.npmjs.com/package/cash-dom) on NPM).
    
These have been bundled with cash-dom since v3.0.0 (Mar 18, 2019) [1][2], when it was rewritten in TypeScript. [3]
    
[1] https://github.com/fabiospampinato/cash/releases/tag/3.0.0
[2] https://unpkg.com/browse/cash-dom@3.0.0/dist/cash.d.ts
[3] https://github.com/fabiospampinato/cash/issues/151#issuecomment-431991606

**Cc**:

- Cash: @fabiospampinato
- Cash typings: @ashokvishwakarma

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## materialize-css ([<kbd>unpkg</kbd>](https://unpkg.com/browse/materialize-css@latest/))
was missing the following properties:
1. version
1. keys
1. tabPressed
1. keyDown
1. initializeJqueryWrapper

<details>
<summary>as well as these 11 other properties...</summary>
<p>objectSelectorString, guid, escapeHash, elementOrParentIsFixed, checkWithinContainer, checkPossibleAlignments, getOverflowParent, getIdFromTrigger, getDocumentScrollTop, getDocumentScrollLeft, throttle</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 46ed8428c6a6cd97d6f01d8aa7325850f2f21c6b
</p>

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## materialize-css ([<kbd>unpkg</kbd>](https://unpkg.com/browse/materialize-css@latest/))
was missing the following properties:
1. version
1. keys
1. tabPressed
1. keyDown
1. initializeJqueryWrapper

<details>
<summary>as well as these 11 other properties...</summary>
<p>objectSelectorString, guid, escapeHash, elementOrParentIsFixed, checkWithinContainer, checkPossibleAlignments, getOverflowParent, getIdFromTrigger, getDocumentScrollTop, getDocumentScrollLeft, throttle</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bee4919b18c46c7ee25f6da813d8088e34a0a4f2
</p>

**Comment by chocolateboy** [comment]
Before I spend more time on this, do the materialize-css team have any insights into the failures [here](https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/686841846)? They have nothing to do with this change (cash(-dom) isn't mentioned in the error messages).

materialize-css is the only library in DT which references the old ([misnamed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10765#issuecomment-243652859)) @types/cash dependency. It would be nice to get rid of it because it's hopelessly out of date (e.g. [`Cash#has`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9c0c135e0b7bc1aab22786af70bc95aea7ca44bd/types/cash/index.d.ts#L241-L245) has the [wrong return type](https://github.com/fabiospampinato/cash#fnhas-) and [`Cash#get`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9c0c135e0b7bc1aab22786af70bc95aea7ca44bd/types/cash/index.d.ts#L235-L239) is [missing an overload](https://github.com/fabiospampinato/cash#fnget-)).

As things currently stand, @types/cash is being downloaded [4000+ times a week](https://www.npmjs.com/package/@types/cash) by unwitting users despite being completely broken for many common uses.

Cc @huww98 @MaximBalaganskiy @MonizDave @broccoliarchy @SnowyLeopard

**Comment by sandersn** [comment]
@chocolateboy I couldn't repro the same failures as you, but I got some weird ones too. I flailed around until I got it to compile:

Internally, materalize-css isn't written with modules, which worked fine with `@types/cash`, which also didn't use modules. But cash-dom's types do. (materialize-css' index.d.ts then re-exports everything in a module, so I guess the reason for that is to allow web pages to individually reference files inside materialize-css?) I worked around this with an import type.

materialize-css' tests *also* expected cash to be globally available, so I had to add an import.

I also had to upgrade materialize-css to require TS 3.1, but this isn't a big deal since that'll be the lowest supported version starting in July.

Anyway, I created a PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44969, which looks good so far.

**Comment by chocolateboy** [comment]
@sandersn Great! I was in the process of just restoring materialize-css's use of the old @types/cash dependency, just to get this out the door, which is probably what I should have done originally (like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39618/files)).

More than happy to cancel [that plan](https://github.com/microsoft/types-publisher/pull/784) if you've got the new types working. :+1:

**Comment by chocolateboy** [comment]
Closing this favour of #44969.

**Pull request closed without merging**
