### PR TITLE
[react] Add inert

### PR DESCRIPTION
**Pull request by mbelsky**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert)
  - [react PR](https://github.com/facebook/react/pull/24730)
  - [react-native PR](https://github.com/facebook/react-native/pull/43912) Remove `tvParallaxProperties`
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by mbelsky** [comment]
I see the pipeline has failed for a test in `react-native-material-ripple` package but I don't really understand how my changes might affect or introduce the issue.

**Review by eps1lon — CHANGES_REQUESTED** [review]
inert is not supported as a boolean prop in React 18. We're going to add it to React 19 though: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69022

**Comment by mbelsky** [comment]
@eps1lon thank you for pointing that out, I updated the type definition

**Review by eps1lon — CHANGES_REQUESTED** [review]
This will be included in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69022

We couldn't merge this now anyway since React 19 is not out yet.

**Pull request closed without merging**
