### PR TITLE
Node: Added missing windowsHide properties to SpawnOptions (revision)

### PR DESCRIPTION
**Pull request by BrunoScheufler**
As advised by @andy-ms in my [former PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24720), this PR's should trigger the fixed CI again.

Changes: Added missing `windowsHide` property to SpawnOptions interface of the child_process module

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [child_process SpawnOptions](https://nodejs.org/dist/latest-v9.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
Seems you are that lucky to hit again a broken CI when creating a PR. All fails are unrelated in my opinion.

**Comment by BrunoScheufler** [comment]
I hope the @typescript-bot doesn't shut down this PR due to the failed CI before we can get the changes approved

**Comment by Flarna** [comment]
Well, I approved it already. But as long as a PR is marked with CI failed (or merge conflict) bot is not informing maintainers (like @andy-ms) that it is ready to merge.
Untouched PRs not ready to merge (like our previous on) get cleaned up after a while.

**Comment by andy-ms** [comment]
Sorry, this is a TypeScript bug, working on a fix at Microsoft/TypeScript#23538.

**Pull request merged**
