### PR TITLE
feat: :sparkles: add types for @bugsnag/cuid

### PR DESCRIPTION
**Pull request by Ankan002**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bugsnag__cuid ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bugsnag__cuid@latest/))
was missing the following properties:
1. fingerprint
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 04bf4b0b59e0309f7ce5362bd4b401ad8850b604
</p>

**Comment by Ankan002** [comment]
@peterblazejewicz Hi, actually I was trying to contribute for the package `@bugsnag/cuid`. First I use the dt-gen tool to generate the template and then I simply wrote the types and pushed the changes, finally created the PR. But DangerBot was mentioning about some attribute. Is it some attribute that I am missing? Or it the contribution PR fine? Please confirm and let me know once you get time. Thanks in advance.

**Comment by rbuckton** [comment]
> @peterblazejewicz Hi, actually I was trying to contribute for the package `@bugsnag/cuid`. First I use the dt-gen tool to generate the template and then I simply wrote the types and pushed the changes, finally created the PR. But DangerBot was mentioning about some attribute. Is it some attribute that I am missing? Or it the contribution PR fine? Please confirm and let me know once you get time. Thanks in advance.

DangerBot is talking about Line 57 here: https://unpkg.com/browse/@bugsnag/cuid@3.0.2/index.js#L57 It looks like `@bugsnag/cuid` also exports `fingerprint` as a property of the `cuid` function. I can approve these types as-is, but it may be worth including if you need to reference it at any point.

**Comment by Ankan002** [comment]
@rbuckton oh sorry I didn't notice  that will fix that.

**Comment by Ankan002** [comment]
Just now updated the missing declaration issue. Thanks, @rbuckton for pointing out the missing declaration. Please look into the PR once you get time.

**Comment by Ankan002** [comment]
@rbuckton @peterblazejewicz  Hi please look into the PR once you get time.

**Review by jakebailey — APPROVED** [review]

**Comment by Ankan002** [comment]
Ready to merge

**Pull request merged**
