### PR TITLE
Chartist - add another possible series type to IChartistData

### PR DESCRIPTION
**Pull request by clottman**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: 
There's not a lot of documentation on this feature on the website but it works for me in a production site. 
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mtgibbs** [comment]
Can we get a test case showing the use case that we're covering here?

**Comment by clottman** [comment]
You can see that it's accounted for in the docs at this link, https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type under Fixed Scale Axis. Note that `series` takes a nested array of objects. 

I'm about to leave on vacation so I don't have the time right now to write up a unit test, but here's a standalone version of the code that I'm calling to create the chart. 

```
class ChartistHelpers {
            static TimeSeriesAxis: Chartist.IChartistFixedScaleAxis = {
            type: Chartist['FixedScaleAxis'],
            divisor: 5,
            labelInterpolationFnc: (value) => {
                 return moment(value).format(ChartistHelpers.TimeFormat);
             },
        };

    static CreateBaseLineChartOptions = (): Chartist.ILineChartOptions => {
        return {
            axisX: ChartistHelpers.TimeSeriesAxis,
            axisY: {
                onlyInteger: true
            },
            low: 0,
            plugins: [Chartist['plugins']['tooltip']({
                transformTooltipTextFnc: (val) => val.split(',')[1]
        })],
        };
    }

    static PerformanceSeriesData = (times: Date[], yValues: number[]): Chartist.IChartistData[] => {
        let seriesData = [];

        for (let i = 0; i < times.length; i++) {
            let momentDate = moment(times[i]);
            seriesData.push({
                x: momentDate.format('x'),
                y: yValues[i],
                meta: momentDate.format('MM/D H:mm')
            });
        }
        return seriesData;
    };

    static ResponsiveTimeSeriesOptions: Array<Chartist.IResponsiveOptionTuple<Chartist.ILineChartOptions>> = [
        ['(max-width: 1340px)', {
            axisX: {
                labelInterpolationFnc: (value, index) => {
                    let odd = 2;
                    // skip every other label when screen is small
                    return index % odd === 0 ? moment(value).format(ChartistHelpers.TimeFormat) : null;
                }
            }
        }]
    ];
}

let time1, time2, time3 = 3 dates
let seriesData = ChartistHelpers.PerformanceSeriesData([time1, time2, time3], [1, 3, 5]);

new Chartist.Line("#my-chart", {
                    series: [seriesData],
                    labels: times
                }, baseLineChartOptions, ChartistHelpers.ResponsiveTimeSeriesOptions);
```

**Comment by mtgibbs** [comment]
I normally just used to pop the use cases in from the docs.  I've not been super active with Chartist in a bit, does this work in the current 8.9 version or do we need to bump the version specified in the typings?

**Comment by clottman** [comment]
I assumed we'd want to bump the version because there's been a minor change - is your usual pattern something different? It works with the current version of chartist.

**Comment by mtgibbs** [comment]
If these are still current for latest, we should probably change

```
+// Type definitions for Chartist v0.9.81
```
to be the latest, `11.x`?  But we can just handle that in another change honestly.  Let's get this pulled in so people pulling types can get them and go back and review the test cases for compile since there's been some additions.

**Comment by clottman** [comment]
Ah - other libraries give the version number as the version of the typings, not the library version it works with. Is that what's going on here? If so, no bump necessary.

**Comment by mtgibbs** [comment]
Yeah that comment is just saying what version we're supporting.  I have no idea what version of the Chartist Typings is at this point.  I assume that each successful change just bumps it automagically.  Let's not mess with that version line and then we can review that later.

**Review by mtgibbs — APPROVED** [review]
We need to come back and write up the test case for this given use case.  There's really no v0.9.81 of chartist, but it's just a comment and we probably need to review if all of these typings are still valid for 11.x.

**Comment by clottman** [comment]
I was understanding it not as version 0.9.8 of the typings, not of chartist at all. That's how it works for the bootstrap and underscore typings, for example.

**Comment by clottman** [comment]
Going back through git blame on the version line in the typings file supports my interpretation - and in fact I myself [bumped it to version 0.9.7](https://github.com/clottman/DefinitelyTyped/commit/e7b3ad2f1cd5b344f0511887f6a73ecb12450825)

**Comment by mtgibbs** [comment]
Yeah that comment is just the version of Chartist that we're saying these typings work for.  I went and looked up the actual package version:  https://www.npmjs.com/package/@types/chartist

It's 0.9.37.

It's a meaningless number though, we don't need to worry about it for the sake of this PR.  We can fix it later when we update the test case.

**Pull request merged**
