### PR TITLE
Update Redux dependency for redux-logger and redux-seamless-immutable to v5

### PR DESCRIPTION
**Pull request by EskiMojo14**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://redux-toolkit.js.org/usage/migrating-rtk-2#middleware-type-changed---middleware-action-and-next-are-typed-as-unknown
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Need more info - why are we doing this if the current version works (i.e. there are no broken tests) ? The underlying packages don't seem to depend on redux 5.

**Comment by EskiMojo14** [comment]
The underlying packages don't depend on Redux 5 because there are no breaking *runtime* changes.

However, in Redux 5 we [changed the Middleware type](https://redux-toolkit.js.org/usage/migrating-rtk-2#middleware-type-changed---middleware-action-and-next-are-typed-as-unknown) to something safer. This was a breaking change, and the Redux 4 Middleware type is not assignable to the Redux 5 Middleware type. 

This means that packages that pull their Middleware type from Redux 4 will get a type error when trying to use it with Redux 5:
https://github.com/reduxjs/redux-toolkit/issues/4072
https://github.com/reduxjs/redux-toolkit/issues/3966

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by EskiMojo14** [comment]
It's worth noting (for anyone finding this in future) that this will be a breaking change for those still using Redux 4 and below. However, my understanding of the README is that the major version must match the major version of the original package, and thus breaking type changes are published in patch versions.

People still using Redux 4 will either need to pin their dependency on the version before this, or [override the resolution](https://redux-toolkit.js.org/usage/migrating-rtk-2#overriding-dependencies) of Redux itself to ensure consistency.

With all of that said:

**Comment by EskiMojo14** [comment]
Ready to merge

**Comment by spamshaker** [comment]
this is a breaking change when you enforce redux 5 in the dependencies. So that when the redux 4 is in the project semantic `pnpm up` while `"@types/redux-logger": "^3.0.12"`  breaks typing

**Comment by EskiMojo14** [comment]
@spamshaker yes, that's what my comment above says, along with the two approaches you'd need to choose between to sidestep the change.

**Comment by spamshaker** [comment]
> @spamshaker yes, that's what my comment above says, along with the two approaches you'd need to choose between to sidestep the change.

My apologies for missing that, will pin it, thanks

**Pull request merged**
