### PR TITLE
chore (fs-capacitor): types now shipped

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

since 8.0.0 they ship their own types:
https://unpkg.com/browse/fs-capacitor@8.0.0/dist/index.d.ts

### CODE REVIEW

**Comment by 43081j** [comment]
missed a dependent package, my mistake. may have to update the allowed dependencies list before this can be merged

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by 43081j** [comment]
ready to merge 🥳

**Comment by L-U-C-K-Y** [comment]
We are using an older version of https://github.com/jaydenseric/graphql-upload as we cannot migrate to ESM just yet and by removing this type definitions, we are receiving this error: 

```
error TS2688: Cannot find type definition file for 'fs-capacitor'.
   The file is in the program because:
     Entry point for implicit type library 'fs-capacitor'
```

**Comment by 43081j** [comment]
did you update `@types/fs-capacitor`? the previous version will exist and work fine until you can upgrade fs-capacitor itself.

or maybe you don't use package-lock files?

basically the only way you should be able to get that error is by updating to the latest types package (which you shouldn't do unless you are ready to upgrade fs-capacitor too).

**Pull request merged**
