### PR TITLE
fixed CodeMirror.TextMarker.find() return type

### PR DESCRIPTION
**Pull request by RaduW**
Added CodeMirror.Range type
Changed CodeMirror.TextMarker.find() to return CodeMirror.Range instead
of CodeMirror.Position (which was wrong).

### CODE REVIEW

**Comment by mihailik** [comment]
Brilliant! :+1:

**Comment by vvakame** [comment]
*highlightjs/highlightjs.d.ts*

to authors (@nikeee @sourrust). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by nikeee** [comment]
Everything fine! :+1:

**Comment by sourrust** [comment]
Looks good. :+1:

**Pull request merged**
