### PR TITLE
Add non-private "connect()" method to ldapjs Client class

### PR DESCRIPTION
**Pull request by Llorx**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests). (Edited online so not possible to run tests. Lets see what the bot says)

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/ldapjs/node-ldapjs/blob/b86c493e7bbec6ae1d639951158645e1515467d7/lib/client/client.js#L790](https://github.com/ldapjs/node-ldapjs/blob/b86c493e7bbec6ae1d639951158645e1515467d7/lib/client/client.js#L790)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ldapjs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ldapjs@latest/))
was missing the following properties:
1. Client
1. Server
1. persistentSearch
1. PersistentSearchCache
1. filters

<details>
<summary>as well as these 2 other properties...</summary>
<p>url, parseURL</p>
</details>


## Formatting

The following files are not formatted:
1. types/ldapjs/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 82f56b4a2033fa2f677baac487e2fb438daabbda
</p>

**Comment by pmoleri** [comment]
Hi. I see in the linked code that the connect() method exists and is not underscored (convention for private).
But it's not listed in the documentation [Client API ](http://ldapjs.org/client.html), it's called from the constructor and probably not meant to be public API.

Is there a relevant use case for it? Otherwise, it might be misleading to new developers thinking that they need an explicit call to connect().

I also saw a discussion about [exposing connect() and not calling it from the constructor](https://github.com/ldapjs/node-ldapjs/pull/574#issuecomment-541347736) but it never happened.

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes so the bot can track the status.

Based on @pmoleri's comment, perhaps this would be an acceptable change if the jsdoc explicitly mentions that it only needs to be called manually to re-connect, not after initial construction?

**Comment by Llorx** [comment]
@sandersn that's true. I vote to add the information to the jsdoc. The more Information on how a method works, the better.

If you want me to add it I would do so. Even I would do a PR in the original project to update its jsdoc too.

**Comment by Llorx** [comment]
Just changed the jsdoc to clarify the usability.

**Pull request merged**
