### PR TITLE
[node] Add `TracingChannel`

### PR DESCRIPTION
**Pull request by Semigradsky**
https://nodejs.org/dist/latest-v20.x/docs/api/diagnostics_channel.html#class-tracingchannel

Related:
- https://github.com/nodejs/node/issues/50996

### CODE REVIEW

**Comment by Semigradsky** [comment]
```
Error in enzyme
/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.197_typescript@5.4.0-dev.20231202/node_modules/@definitelytyped/dtslint/src/index.ts:213
    throw new Error(err);
          ^

Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/enzyme/enzyme-tests.tsx:106:9
ERROR: 106:9  expect  TypeScript@5.4 compile error: 
Unused '@ts-expect-error' directive.
```
It looks like smth unrelated to my changes

**Comment by Semigradsky** [comment]
```
Error in knex-db-manager
Passed but was expected to fail.
```

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/diagnostics_channel.ts
1. types/node/v18/test/diagnostics_channel.ts
1. types/node/ts4.8/test/diagnostics_channel.ts
1. types/node/v18/ts4.8/test/diagnostics_channel.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f97a03b069236780a821603ab437d55d86708a17
</p>

**Review by peterblazejewicz — COMMENTED** [review]
still on the road map?

**Review by sheetalkamat — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
