### PR TITLE
[mui-datatables] Add types for string literal unions

### PR DESCRIPTION
**Pull request by shawnmitchell**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by amcasey** [comment]
Closing and re-opening to trigger Travis.

**Comment by amcasey** [comment]
```
1> Error: /home/vsts/work/1/s/types/mui-datatables/mui-datatables-tests.tsx:20:9
1> ERROR: 20:9  expect  TypeScript@next compile error: 
1> Type 'false' is not assignable to type '"none" | "multiple" | "single" | undefined'.
```

**Review by amcasey — CHANGES_REQUESTED** [review]
Please update the tests.

**Comment by Favna** [comment]
Apologies I didn't checkout the PR and run tests myself before I approved. Thanks for the checking @amcasey!

**Comment by shawnmitchell** [comment]
Hey guys, I feel like I'm making a mess of this whole process. I've updated the test. Sorry for all the confusion.

**Review by favna — CHANGES_REQUESTED** [review]
@shawnmitchell Could you change the title of the PR `[mui-datatables] Add types for string literal unions`? I asked @amcasey to close #35971 in favour of this PR.

**Comment by shawnmitchell** [comment]
Should be good to go? Thanks for the help getting the pull request together properly.

**Review by favna — APPROVED** [review]
Did a check through the change myself and it looks all good. This PR just needs an approval from @amcasey before it can be merged.

**Review by amcasey — APPROVED** [review]

**Comment by shawnmitchell** [comment]
Thanks again guys!

**Pull request merged**
