### PR TITLE
d3.Selection<Datum>.node() returns Datum

### PR DESCRIPTION
**Pull request by zbjornson**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes. https://github.com/mbostock/d3/wiki/Selections#node .
  - it has been reviewed by a DefinitelyTyped member.

See discussion in last four comments here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7014#issuecomment-233207998

### CODE REVIEW

**Comment by zbjornson** [comment]
Hrm, don't merge yet. There are other larger problems with d3.d.ts that should maybe be addressed together.

**Comment by gustavderdrache** [comment]
:-1:

This isn't correct. The return value of `selection.node()` is the DOM node, not the bound datum -- that is returned by the `.datum()` method, which is what is referenced in the `Datum` type parameter.

In general, it's not possible to give a good type for the type of the `.node()` method since CSS selectors don't have to include a type selector at all: `d3.selectAll('.some-class')`, for instance. TypeScript's own definitions for things like `querySelectorAll()` and `getElementsByClassName()` return a simple `NodeList` rather than the stronger `NodeListOf<T>` returned by `getElementsByTagName()`.

Ultimately there is always going to be a tension between the flexibility afforded by CSS-style selections and the desire to give them strong types. I have found that it is much more important when dealing with D3 to be accurate with the bound data rather than the kind of node being dealt with.

**Comment by zbjornson** [comment]
@gustavderdrache right, that's what I was looking at.

The `Datum` in `Selection<Datum>` refers to the interface for the data applied to the elements in the selection, not the type of the element as I think all three of us assumed in the thread that I linked to. I think it would make sense to define `Selection<Element>` and `Selection<Element, Datum>` considering that the types of both the nodes and of the datum are useful, and that not all selections have Datum. Thoughts on that?

**Comment by gustavderdrache** [comment]
One the one hand, knowing the kind of node in your selection is useful, but on the other hand, the flexibility of JavaScript and the DOM makes it impossible to really have any kind of static guarantees. And without those, adding the type parameter (since TS doesn't let us distinguish between numbers of type parameters, there would only be `Selection<Element, Datum>`) would create a lot of needless busywork for the few cases when it actually did work out.

Right now, what we have is just about as good as I feel it can get as a middle-of-the road solution: you can get as strong a type using `d3.select()` as you would using, say, `document.getElementById`  or jQuery:

```
const domSidebar = document.getElementById('#sidebar');
const d3Sidebar = d3.select('#sidebar');
const $sidebar = $('#sidebar');
```

I like to consider the `Selection<Datum>` type to be a pragmatic compromise, since quite a lot of DOM manipulation will go through the `attr()`, `classed()`, and `on()` methods, which is safe on the vast majority of nodes. But the thing that will matter most when writing code is making sure access to the `Datum` type is sound, which is what has tripped myself and several team members up while developing pretty extensive visualizations.

At the very least, if you're not using data, you could always use `d3.Selection<void>`, which will effectively prevent you from mentioning the data.

**Comment by zbjornson** [comment]
Appreciate the explanation, thanks. Sorry for the hasty PR :)

**Pull request closed without merging**
