### PR TITLE
Define cloudfront headers closer to an object in aws-lambda

### PR DESCRIPTION
**Pull request by corollari**
## Change
When getting the headers of a lambda@edge request it is possible for some headers to just not exist in that object, but with the current definitions it is assumed that it's impossible for a header not to be defined, this PR brings the type closer to the definition of an object by simply adding undefined as a possible value, thus acknowledging the possibility of a missing header.

## Problems
This change could be backwards incompatible, but if someone isn't testing whether a header exists in their cloudfront headers then their code is probably broken already.

## Boilerplate
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

I don't think that the following items are relevant for this PR (maybe testing? I'm not sure how to test for this)

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>> -> Not relevant
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed. -> No substantial changes

### CODE REVIEW

**Review by darbio — CHANGES_REQUESTED** [review]
Why is the type changed to be a union with undefined? Shouldn't the property be undefined?


E.g. customHeaders: CloudFrontHeaders | undefined

**Comment by darbio** [comment]
Maybe I am uncaffeinated... 😂☕️ is it the individual header value (e.g. Authorization = undefined) that is not defined, or the fact that there are no headers at all? Do you have an example of this?

**Comment by corollari** [comment]
The headers are defined but a specific header may be undefined, essentially:
```ts
const wrong = headers['doesnt-exist']
wrong // -> string but should be string|undefined
```

So essentially due to this type type guards end up being regarded as dead code for typescript:
```ts
const wrong = headers['doesnt-exist']
if(wrong === undefined){
  throw new Error() // -> marked as dead code
}
```

**Comment by darbio** [comment]
Ah I see what you mean. It's the fact that when you access a key that doesn't exist on a map, JavaScript returns undefined.

In other typed languages (e.g. C#) this would be a dictionary which would throw an exception (and gives you the option to check if the key exists). 

You could check if the property exists using object.hasOwnProperty('name') however I can see how this is confusing for type checking in TS.

I'll defer to someone else to review as I could go either way on this. My concerns are that adding in the undefined actually doesn't represent what the event looks like - the header is never actually undefined.

**Review by simonbuchan — CHANGES_REQUESTED** [review]
Adding `undefined` to a type is a breaking change in read locations, but that's OK if it's going to be catching real runtime errors and not annoying existing users.
The problem I have with these types of changes is it's pushing a strictness preference onto users in a way they can't control, and if it's going to be done in one place, why not everywhere else there's a map lookup?
Given that Typescript is [experimenting](https://github.com/microsoft/TypeScript/pull/39560) with adding a user-controllable option to add undefined to unguarded index operations, I'm even more strongly sticking with the current convention of not manually adding undefined to maps, given the trade-offs.

**Comment by darbio** [comment]
> Given that Typescript is [experimenting](https://github.com/microsoft/TypeScript/pull/39560) with adding a user-controllable option to add undefined to unguarded index operations, I'm even more strongly sticking with the current convention of not manually adding undefined to maps, given the trade-offs.

Agreed. Thanks for the input. We should document this decision (elsewhere) for the benefit of future pull requesters.

**Comment by corollari** [comment]
> The problem I have with these types of changes is it's pushing a strictness preference onto users in a way they can't control

You could also say that you are already pushing a strictness preference onto users with the current package, and at the end of the day users can control this by simply changing the types in their local environments, thus the only difference that this PR makes is that it changes the strictness preference. 

However, the solution proposed by the typescript team seems to be much better than changing the types directly, so I agree in rejecting this change.

**Comment by darbio** [comment]
> You could also say that you are already pushing a strictness preference onto users with the current package

The standard behaviour of Typescript (and hence Javascript) is that when you access a property that doesn't exist on a Map, it returns undefined. This isn't our design and if you code defensively shouldn't be an issue. 

If I'm not mistaken, in your case, the issue this PR addressed was a linting warning which can be easily worked around (by checking if the key exists) or even ignored (ts-ignore), if you prefer.

**Pull request closed without merging**
