### PR TITLE
[@types/node] Add stream.Writable events to stream.Duplex class

### PR DESCRIPTION
**Pull request by Alexthemediocre**
Explicitly lists each event from both stream.Readable and stream.Writable in the Duplex class so that all overloads are visible to TypeScript. Adds some tests in `./types/node/test/stream.ts`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/stream.html#event-close

### CODE REVIEW

**Comment by Alexthemediocre** [comment]
Seems like it failed due to the `@types/hapi` package
image
```js
Error: node_modules/@hapi/hapi/lib/types/server/server.d.ts(5,10): error TS2617: 'Mimos' can only be imported by using 'import Mimos = require("@hapi/mimos")' or by turning on the 'esModuleInterop' flag and using a default import.
```

**Comment by gabritto** [comment]
Friendly re-ping @eps1lon @peterblazejewicz: could you take a look at this?

**Comment by peterblazejewicz** [comment]
@Alexthemediocre this looks ok, can you add TS4.8 version (I cannot do this via PR review, as it seems you forgotten to create a PR branch, just using master: https://docs.github.com/en/get-started/quickstart/contributing-to-projects#creating-a-branch-to-work-on)
```diff
commit a1524ade0a3b62a09979cca884a8f3583fee470d
Author: Piotr Błażejewicz <peterblazejewicz@users.noreply.github.com>
Date:   Tue Feb 14 21:14:06 2023 +0100

    [pr] add TS4.8 version

diff --git a/types/node/ts4.8/stream.d.ts b/types/node/ts4.8/stream.d.ts
index a0df689e1d..926a5644e5 100644
--- a/types/node/ts4.8/stream.d.ts
+++ b/types/node/ts4.8/stream.d.ts
@@ -912,6 +912,105 @@ declare module 'stream' {
             end(chunk: any, encoding?: BufferEncoding, cb?: () => void): this;
             cork(): void;
             uncork(): void;
+            /**
+             * Event emitter
+             * The defined events on documents including:
+             * 1.  close
+             * 2.  data
+             * 3.  drain
+             * 4.  end
+             * 5.  error
+             * 6.  finish
+             * 7.  pause
+             * 8.  pipe
+             * 9.  readable
+             * 10. resume
+             * 11. unpipe
+             */
+            addListener(event: 'close', listener: () => void): this;
+            addListener(event: 'data', listener: (chunk: any) => void): this;
+            addListener(event: 'drain', listener: () => void): this;
+            addListener(event: 'end', listener: () => void): this;
+            addListener(event: 'error', listener: (err: Error) => void): this;
+            addListener(event: 'finish', listener: () => void): this;
+            addListener(event: 'pause', listener: () => void): this;
+            addListener(event: 'pipe', listener: (src: Readable) => void): this;
+            addListener(event: 'readable', listener: () => void): this;
+            addListener(event: 'resume', listener: () => void): this;
+            addListener(event: 'unpipe', listener: (src: Readable) => void): this;
+            addListener(event: string | symbol, listener: (...args: any[]) => void): this;
+            emit(event: 'close'): boolean;
+            emit(event: 'data', chunk: any): boolean;
+            emit(event: 'drain'): boolean;
+            emit(event: 'end'): boolean;
+            emit(event: 'error', err: Error): boolean;
+            emit(event: 'finish'): boolean;
+            emit(event: 'pause'): boolean;
+            emit(event: 'pipe', src: Readable): boolean;
+            emit(event: 'readable'): boolean;
+            emit(event: 'resume'): boolean;
+            emit(event: 'unpipe', src: Readable): boolean;
+            emit(event: string | symbol, ...args: any[]): boolean;
+            on(event: 'close', listener: () => void): this;
+            on(event: 'data', listener: (chunk: any) => void): this;
+            on(event: 'drain', listener: () => void): this;
+            on(event: 'end', listener: () => void): this;
+            on(event: 'error', listener: (err: Error) => void): this;
+            on(event: 'finish', listener: () => void): this;
+            on(event: 'pause', listener: () => void): this;
+            on(event: 'pipe', listener: (src: Readable) => void): this;
+            on(event: 'readable', listener: () => void): this;
+            on(event: 'resume', listener: () => void): this;
+            on(event: 'unpipe', listener: (src: Readable) => void): this;
+            on(event: string | symbol, listener: (...args: any[]) => void): this;
+            once(event: 'close', listener: () => void): this;
+            once(event: 'data', listener: (chunk: any) => void): this;
+            once(event: 'drain', listener: () => void): this;
+            once(event: 'end', listener: () => void): this;
+            once(event: 'error', listener: (err: Error) => void): this;
+            once(event: 'finish', listener: () => void): this;
+            once(event: 'pause', listener: () => void): this;
+            once(event: 'pipe', listener: (src: Readable) => void): this;
+            once(event: 'readable', listener: () => void): this;
+            once(event: 'resume', listener: () => void): this;
+            once(event: 'unpipe', listener: (src: Readable) => void): this;
+            once(event: string | symbol, listener: (...args: any[]) => void): this;
+            prependListener(event: 'close', listener: () => void): this;
+            prependListener(event: 'data', listener: (chunk: any) => void): this;
+            prependListener(event: 'drain', listener: () => void): this;
+            prependListener(event: 'end', listener: () => void): this;
+            prependListener(event: 'error', listener: (err: Error) => void): this;
+            prependListener(event: 'finish', listener: () => void): this;
+            prependListener(event: 'pause', listener: () => void): this;
+            prependListener(event: 'pipe', listener: (src: Readable) => void): this;
+            prependListener(event: 'readable', listener: () => void): this;
+            prependListener(event: 'resume', listener: () => void): this;
+            prependListener(event: 'unpipe', listener: (src: Readable) => void): this;
+            prependListener(event: string | symbol, listener: (...args: any[]) => void): this;
+            prependOnceListener(event: 'close', listener: () => void): this;
+            prependOnceListener(event: 'data', listener: (chunk: any) => void): this;
+            prependOnceListener(event: 'drain', listener: () => void): this;
+            prependOnceListener(event: 'end', listener: () => void): this;
+            prependOnceListener(event: 'error', listener: (err: Error) => void): this;
+            prependOnceListener(event: 'finish', listener: () => void): this;
+            prependOnceListener(event: 'pause', listener: () => void): this;
+            prependOnceListener(event: 'pipe', listener: (src: Readable) => void): this;
+            prependOnceListener(event: 'readable', listener: () => void): this;
+            prependOnceListener(event: 'resume', listener: () => void): this;
+            prependOnceListener(event: 'unpipe', listener: (src: Readable) => void): this;
+            prependOnceListener(event: string | symbol, listener: (...args: any[]) => void): this;
+            removeListener(event: 'close', listener: () => void): this;
+            removeListener(event: 'data', listener: (chunk: any) => void): this;
+            removeListener(event: 'drain', listener: () => void): this;
+            removeListener(event: 'end', listener: () => void): this;
+            removeListener(event: 'error', listener: (err: Error) => void): this;
+            removeListener(event: 'finish', listener: () => void): this;
+            removeListener(event: 'pause', listener: () => void): this;
+            removeListener(event: 'pipe', listener: (src: Readable) => void): this;
+            removeListener(event: 'readable', listener: () => void): this;
+            removeListener(event: 'resume', listener: () => void): this;
+            removeListener(event: 'unpipe', listener: (src: Readable) => void): this;
+            removeListener(event: string | symbol, listener: (...args: any[]) => void): this;
         }
         type TransformCallback = (error?: Error | null, data?: any) => void;
         interface TransformOptions extends DuplexOptions {
diff --git a/types/node/ts4.8/test/stream.ts b/types/node/ts4.8/test/stream.ts
index a5614ea2e7..46beb50329 100644
--- a/types/node/ts4.8/test/stream.ts
+++ b/types/node/ts4.8/test/stream.ts
@@ -643,3 +643,21 @@ async function testTransferringStreamWithPostMessage() {
     // error TS2532: Cannot use 'stream' as a target of a postMessage call because it is not a Transferable.
     // port2.postMessage(stream, [stream]);
 }
+
+{
+    // checking the type definitions for the events on the Duplex class and subclasses
+    const transform = new Transform();
+    transform.on('pipe', (src) => {
+        // $ExpectType Readable
+        src;
+    }).once('unpipe', (src) => {
+        // $ExpectType Readable
+        src;
+    }).addListener('data', (chunk) => {
+        // $ExpectType any
+        chunk;
+    }).prependOnceListener('error', (err) => {
+        // $ExpectType Error
+        err;
+    });
+}
```

**Comment by Alexthemediocre** [comment]
> @Alexthemediocre this looks ok, can you add TS4.8 version (I cannot do this via PR review, as it seems you forgotten to create a PR branch, just using master: https://docs.github.com/en/get-started/quickstart/contributing-to-projects#creating-a-branch-to-work-on)
> 
> ```diff
> commit a1524ade0a3b62a09979cca884a8f3583fee470d
> Author: Piotr Błażejewicz <peterblazejewicz@users.noreply.github.com>
> Date:   Tue Feb 14 21:14:06 2023 +0100
> 
>     [pr] add TS4.8 version
> 
> diff --git a/types/node/ts4.8/stream.d.ts b/types/node/ts4.8/stream.d.ts
> index a0df689e1d..926a5644e5 100644
> --- a/types/node/ts4.8/stream.d.ts
> +++ b/types/node/ts4.8/stream.d.ts
> @@ -912,6 +912,105 @@ declare module 'stream' {
>              end(chunk: any, encoding?: BufferEncoding, cb?: () => void): this;
>              cork(): void;
>              uncork(): void;
> +            /**
> +             * Event emitter
> +             * The defined events on documents including:
> +             * 1.  close
> +             * 2.  data
> +             * 3.  drain
> +             * 4.  end
> +             * 5.  error
> +             * 6.  finish
> +             * 7.  pause
> +             * 8.  pipe
> +             * 9.  readable
> +             * 10. resume
> +             * 11. unpipe
> +             */
> +            addListener(event: 'close', listener: () => void): this;
> +            addListener(event: 'data', listener: (chunk: any) => void): this;
> +            addListener(event: 'drain', listener: () => void): this;
> +            addListener(event: 'end', listener: () => void): this;
> +            addListener(event: 'error', listener: (err: Error) => void): this;
> +            addListener(event: 'finish', listener: () => void): this;
> +            addListener(event: 'pause', listener: () => void): this;
> +            addListener(event: 'pipe', listener: (src: Readable) => void): this;
> +            addListener(event: 'readable', listener: () => void): this;
> +            addListener(event: 'resume', listener: () => void): this;
> +            addListener(event: 'unpipe', listener: (src: Readable) => void): this;
> +            addListener(event: string | symbol, listener: (...args: any[]) => void): this;
> +            emit(event: 'close'): boolean;
> +            emit(event: 'data', chunk: any): boolean;
> +            emit(event: 'drain'): boolean;
> +            emit(event: 'end'): boolean;
> +            emit(event: 'error', err: Error): boolean;
> +            emit(event: 'finish'): boolean;
> +            emit(event: 'pause'): boolean;
> +            emit(event: 'pipe', src: Readable): boolean;
> +            emit(event: 'readable'): boolean;
> +            emit(event: 'resume'): boolean;
> +            emit(event: 'unpipe', src: Readable): boolean;
> +            emit(event: string | symbol, ...args: any[]): boolean;
> +            on(event: 'close', listener: () => void): this;
> +            on(event: 'data', listener: (chunk: any) => void): this;
> +            on(event: 'drain', listener: () => void): this;
> +            on(event: 'end', listener: () => void): this;
> +            on(event: 'error', listener: (err: Error) => void): this;
> +            on(event: 'finish', listener: () => void): this;
> +            on(event: 'pause', listener: () => void): this;
> +            on(event: 'pipe', listener: (src: Readable) => void): this;
> +            on(event: 'readable', listener: () => void): this;
> +            on(event: 'resume', listener: () => void): this;
> +            on(event: 'unpipe', listener: (src: Readable) => void): this;
> +            on(event: string | symbol, listener: (...args: any[]) => void): this;
> +            once(event: 'close', listener: () => void): this;
> +            once(event: 'data', listener: (chunk: any) => void): this;
> +            once(event: 'drain', listener: () => void): this;
> +            once(event: 'end', listener: () => void): this;
> +            once(event: 'error', listener: (err: Error) => void): this;
> +            once(event: 'finish', listener: () => void): this;
> +            once(event: 'pause', listener: () => void): this;
> +            once(event: 'pipe', listener: (src: Readable) => void): this;
> +            once(event: 'readable', listener: () => void): this;
> +            once(event: 'resume', listener: () => void): this;
> +            once(event: 'unpipe', listener: (src: Readable) => void): this;
> +            once(event: string | symbol, listener: (...args: any[]) => void): this;
> +            prependListener(event: 'close', listener: () => void): this;
> +            prependListener(event: 'data', listener: (chunk: any) => void): this;
> +            prependListener(event: 'drain', listener: () => void): this;
> +            prependListener(event: 'end', listener: () => void): this;
> +            prependListener(event: 'error', listener: (err: Error) => void): this;
> +            prependListener(event: 'finish', listener: () => void): this;
> +            prependListener(event: 'pause', listener: () => void): this;
> +            prependListener(event: 'pipe', listener: (src: Readable) => void): this;
> +            prependListener(event: 'readable', listener: () => void): this;
> +            prependListener(event: 'resume', listener: () => void): this;
> +            prependListener(event: 'unpipe', listener: (src: Readable) => void): this;
> +            prependListener(event: string | symbol, listener: (...args: any[]) => void): this;
> +            prependOnceListener(event: 'close', listener: () => void): this;
> +            prependOnceListener(event: 'data', listener: (chunk: any) => void): this;
> +            prependOnceListener(event: 'drain', listener: () => void): this;
> +            prependOnceListener(event: 'end', listener: () => void): this;
> +            prependOnceListener(event: 'error', listener: (err: Error) => void): this;
> +            prependOnceListener(event: 'finish', listener: () => void): this;
> +            prependOnceListener(event: 'pause', listener: () => void): this;
> +            prependOnceListener(event: 'pipe', listener: (src: Readable) => void): this;
> +            prependOnceListener(event: 'readable', listener: () => void): this;
> +            prependOnceListener(event: 'resume', listener: () => void): this;
> +            prependOnceListener(event: 'unpipe', listener: (src: Readable) => void): this;
> +            prependOnceListener(event: string | symbol, listener: (...args: any[]) => void): this;
> +            removeListener(event: 'close', listener: () => void): this;
> +            removeListener(event: 'data', listener: (chunk: any) => void): this;
> +            removeListener(event: 'drain', listener: () => void): this;
> +            removeListener(event: 'end', listener: () => void): this;
> +            removeListener(event: 'error', listener: (err: Error) => void): this;
> +            removeListener(event: 'finish', listener: () => void): this;
> +            removeListener(event: 'pause', listener: () => void): this;
> +            removeListener(event: 'pipe', listener: (src: Readable) => void): this;
> +            removeListener(event: 'readable', listener: () => void): this;
> +            removeListener(event: 'resume', listener: () => void): this;
> +            removeListener(event: 'unpipe', listener: (src: Readable) => void): this;
> +            removeListener(event: string | symbol, listener: (...args: any[]) => void): this;
>          }
>          type TransformCallback = (error?: Error | null, data?: any) => void;
>          interface TransformOptions extends DuplexOptions {
> diff --git a/types/node/ts4.8/test/stream.ts b/types/node/ts4.8/test/stream.ts
> index a5614ea2e7..46beb50329 100644
> --- a/types/node/ts4.8/test/stream.ts
> +++ b/types/node/ts4.8/test/stream.ts
> @@ -643,3 +643,21 @@ async function testTransferringStreamWithPostMessage() {
>      // error TS2532: Cannot use 'stream' as a target of a postMessage call because it is not a Transferable.
>      // port2.postMessage(stream, [stream]);
>  }
> +
> +{
> +    // checking the type definitions for the events on the Duplex class and subclasses
> +    const transform = new Transform();
> +    transform.on('pipe', (src) => {
> +        // $ExpectType Readable
> +        src;
> +    }).once('unpipe', (src) => {
> +        // $ExpectType Readable
> +        src;
> +    }).addListener('data', (chunk) => {
> +        // $ExpectType any
> +        chunk;
> +    }).prependOnceListener('error', (err) => {
> +        // $ExpectType Error
> +        err;
> +    });
> +}
> ```

Done; thanks.

**Comment by jakebailey** [comment]
@peterblazejewicz Did you have any remaining concerns here? I think you had LGTM'd this, so long as the other types were updated, which they now are.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@Alexthemediocre thanks!

**Comment by Alexthemediocre** [comment]
Ready to merge

**Pull request merged**
