### PR TITLE
switch to tsc 1.8.2

### PR DESCRIPTION
**Pull request by vvakame**
@DefinitelyTyped/contributors TypeScript 1.8.2 released!
https://blogs.msdn.microsoft.com/typescript/2016/02/22/announcing-typescript-1-8-2/

### CODE REVIEW

**Comment by horiuchi** [comment]
:+1:

**Comment by vvakame** [comment]
to maronetter authors @zhamid @nvivo @sventschui .
please check this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/41f24da0a56bb8ad35d98689d4f1ef22b35e487e
please send a PR if this change is wrong.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/definition-tester/pull/17

**Comment by vvakame** [comment]
:clap:

**Comment by basarat** [comment]
Wow :rose: :100: that was fast :rocket:

**Comment by johnnyreilly** [comment]
First thing I saw when I woke up. Yay!

**Comment by horiuchi** [comment]
Great Job! :clap:

**Pull request merged**
