### PR TITLE
1.4.1

### PR DESCRIPTION
**Pull request by karthikkeyanv**

### CODE REVIEW

**Comment by cglantschnig** [comment]
:+1:

**Comment by btesser** [comment]
Lgtm

**Comment by vvakame** [comment]
@karthikkeyanv please resolve conflict.

**Comment by karthikkeyanv** [comment]
Please ignore/close the pull request.

**Comment by karthikkeyanv** [comment]
Kindly discard my changes and cancel my pull request. Thanks You!Regards,
Karthikkeyan Vijayan.  From: Masahiro Wakame <notifications@github.com>
 To: DefinitelyTyped/DefinitelyTyped <DefinitelyTyped@noreply.github.com> 
Cc: karthikkeyanv <karthikkeyanv@yahoo.com>
 Sent: Wednesday, December 23, 2015 12:58 PM
 Subject: Re: [DefinitelyTyped] 1.4.1 (#7255)
 
@karthikkeyanv please resolve conflict.—

**Pull request closed without merging**
