### PR TITLE
Leaflet: Various fixes

### PR DESCRIPTION
**Pull request by webbiesdk**
A lot of or errors related to strict nulls.
Also some arguments that were too general, where the functions don't behave as expected with some of the possible inputs.
And other various errors.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present. (no error in the files modified)

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`. (Already there)

### CODE REVIEW

**Comment by minestarks** [comment]
@alejo90 any comments on this?

**Comment by alejo90** [comment]
It's a very extensive change. I haven't had time to review it yet. I hope I'll have enough time during the weekend.

**Comment by paulvanbrenk** [comment]
@alejo90  thoughts here, the changes seem mostly mechanical.

**Comment by andy-ms** [comment]
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

**Comment by webbiesdk** [comment]
@andy-ms Thanks for notifying me. 

Rebased.

**Pull request merged**
