### PR TITLE
[react-select] Add generic argument for custom select components props

### PR DESCRIPTION
**Pull request by szymkab**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34959

@claasahl - new pull request

### CODE REVIEW

**Review by claasahl — APPROVED** [review]
Thanks for your contribution, @szymkab

**Comment by sandersn** [comment]
This solution is really expensive and may result in users of react-select in running out of memory, particularly if they use a lot of other react packages. Is there some other way to accomplish what you want?

Before this change, react-select takes 180MB of memory to compile, and generates 91,335 types. 
After this changes, it generates 105,571 types. Types are a decent proxy for both time and memory usage, so that means it is about 15% more expensive.

That is with typescript@next. The numbers about 3% worse with 3.4.

**Review by sandersn — CHANGES_REQUESTED** [review]
Need to find a more efficient way to restrict usage.

**Comment by szymkab** [comment]
@sandersn There is no other way to accomplish what I've done. That generic argument was missing from the beginning and issue was solved by adding `{ [key: string]: any }` but that's a workaround and nothing more.

**Comment by szymkab** [comment]
@sandersn bump

**Comment by sandersn** [comment]
Inside types/react-select, run `tsc --diagnostics`. Compare resource usage between master and your branch. Play around with variations to see if you can find a cheaper way to fix the problem. Memory usage doesn't vary much between compiles, and type count correlates well with both memory usage and compile time, and is stable between compiles. Those are the two measures I would focus on.

You might not be able to make this improvement to the types, unfortunately. We *really* need commonly used React components to avoid high memory usage since everybody in VS Code depends on them, and it increases batch compile times as well.

**Pull request closed without merging**
