### PR TITLE
Initial State support for reduceReducers.

### PR DESCRIPTION
**Pull request by daliusd**
You can pass initialState to reduceReducers function as last argument.

### CODE REVIEW

**Comment by huy-nguyen** [comment]
Since I created this definition in early 2017, the API of the package has changed a bit. I looked into it a bit and the behavior with respect to the `initialState` is interesting. 

- `initialState` is optional i.e it's ok to not give it a value but you must indicate this by passing `null`: https://runkit.com/huy-nguyen/5c4f62c54ea3a50012e6d1d3.
- `initialState` cannot be undefined: https://runkit.com/huy-nguyen/5c4f631d4ea3a50012e6d241 (unit test: https://github.com/redux-utilities/reduce-reducers/blob/master/test/index.test.js#L29-L33).

Can you update your PR to model this behavior?

**Comment by daliusd** [comment]
@huy-nguyen Fixed.

**Comment by daliusd** [comment]
Travis CI failed initially but it was not code's problem. Now everything is OK but label "The Travis CI build failed" is not removed while Travis CI build passed.

**Comment by daliusd** [comment]
@huy-nguyen Could you review my pull request again?

**Comment by huy-nguyen** [comment]
Thanks for the update. Based on the package's [unit tests](https://github.com/redux-utilities/reduce-reducers/blob/c98af2d653f668d934abd0c2f6c1cfe45e607dde/test/index.test.js#L36-L39), it's OK to not provide `initialState`. If possible, would you mind updating the definition to model this behavior?

**Comment by daliusd** [comment]
@huy-nguyen Yes, and code checks if last argument is function and if it is not then initialState is not necessary.

**Review by huy-nguyen — APPROVED** [review]
Thanks. Looks good to me.

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
