### PR TITLE
[react-navigation] Fixed type definitions for NavigationActions.*

### PR DESCRIPTION
**Pull request by petejkim**
```javascript
NavigationActions.navigate({
  routeName: 'HomeScreen'
})
// ==> { type: 'Navigation/NAVIGATE', routeName: 'HomeScreen' }
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-community/react-navigation/blob/master/src/NavigationActions.js#L14

### CODE REVIEW

**Comment by huhuanming** [comment]
It's awesome!
And what do you think?
 @mhcgrq @fangpenlin @abrahambotros

I think it is reasonable.

**Comment by fangpenlin** [comment]
@huhuanming @petejkim 👍

**Comment by huhuanming** [comment]
And what do you think?
@mhcgrq @abrahambotros

If over half of the reviewers accept the PR,  the PR should be merged.

**Comment by mhcgrq** [comment]
@huhuanming @petejkim 👍

**Review by huhuanming — APPROVED** [review]

**Comment by huhuanming** [comment]
LGTU!

Then just wait for it to merge.

**Comment by abrahambotros** [comment]
Also looks good to me, thanks @petejkim!

However, it'd be great to have some tests too for creating these `NavigationActions` - especially since this commit is technically introducing a difference not in the referenced `react-navigation/TypeDefinition.js` or explicitly in `react-navigation/NavigationActions.js`. Tests would prevent future contributors from erroneously changing back to what we had if they were just naively referencing the Flow types.

**Comment by huhuanming** [comment]
good idea!
Why didn't I think of that... 😳

**Comment by petejkim** [comment]
I will add tests

**Comment by petejkim** [comment]
Tests added.

```
$ cd types/react-navigation
$ tsc --noEmit  # should not show any errors
```

**Comment by fangpenlin** [comment]
the tests look good to me 👍

**Comment by iRoachie** [comment]
@abrahambotros Hey going through the typings, is there any reason why type property on the action isn't optional? 

```js
NavigationActions.reset({
   index: 0,
   actions: [NavigationActions.navigate({ routeName: 'Main' })],
})
```

the reset method already carries the type 'Navigation/RESET'. Adding it in options as a required prop seems redundant

**Pull request merged**
