### PR TITLE
[apollo-codegen] Remove types

### PR DESCRIPTION
**Pull request by jablko**
These types appear to be for a [deprecated npm package](https://www.npmjs.com/package/apollo-codegen):
> The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.

Can they be removed?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@jablko 
Jack, seems the original package is still used (thousands a week), together with DT types (hundreds a week):
https://www.npmjs.com/package/@types/apollo-codegen

**Comment by jablko** [comment]
@peterblazejewicz Thanks a lot for taking a look! This won't unpublish @types/apollo-codegen. I think it (the types package) should be marked as deprecated, if it's no longer maintained?

**Comment by peterblazejewicz** [comment]
good question, I assume it publishes a stub, so nothing that can be consumed, effectively `@latest` install no consumable code, only markdown content with repeated message in package.
If for situation client uses that types without providing specific version (so @0.3.0 works and installs non-deprecated version), I'm concerned about the impact.
Let's have second opinion, let me ask on Discord

**Comment by peterblazejewicz** [comment]
@jablko Jack, please see comments on DS, https://discord.com/channels/508357248330760243/757992230077333655/775484626818433064
I'd probably left it as is, due to package popularity and low cost, etc.

**Comment by jablko** [comment]
@peterblazejewicz Sorry I meant the current, non-stub types package should be marked as deprecated. This PR doesn't touch `notNeededPackages.json` so it won't publish a stub.

 #48796 is an example: It removed `types/storybook__polymer` but didn't unpublish [@types/storybook__polymer](https://www.npmjs.com/package/@types/storybook__polymer) or replace it with a stub.

**Comment by peterblazejewicz** [comment]
Oh, sorry, I was as well confused what we'd like to acchieve,
So:
- it will remove the stuff from DT repo (making space here for other stuff)
- it will keep published NPM types
let me approve

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by jablko** [comment]
@peterblazejewicz All good thank you for reviewing :+1:

**Comment by orta** [comment]
Agree - thanks!

**Pull request merged**
