### PR TITLE
React-slick "cannot assign string to 'ondemand' | 'progressive' issue"

### PR DESCRIPTION
**Pull request by sumanla13a**
Please fill in this template.

- [* ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [* ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [ *] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andrewBalekha** [comment]
LGTM

**Review by qndrey — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by sumanla13a** [comment]
Thanks,
@r3nya @andrewBalekha 
Could you guys help me upgrade the version so that I can close this branch?
I didn't know I had to update the version in comment in order to publish it in npm.

**Comment by r3nya** [comment]
Hey @sumanla13a!
It will be upgrade automatically … Please wait. ;)

**Comment by uniqueiniquity** [comment]
@sumanla13a It should be automatically published to npm soon; we publish changes every couple hours.

**Comment by sumanla13a** [comment]
Great Thank you, I'll close the branch then.

**Pull request merged**
