### PR TITLE
[braintree-web] Add new option cardholderName

### LINKED ISSUE #50724: [@types/braintree-web] missing HostedFieldOption of cardholderName
- [x] I tried using the `@types/braintree-web` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chlela @jbuckner 

@types/braintree-web 3.69 is missing the `HostedFieldOption` for `cardholderName` in the declaration which was added in [3.66](https://github.com/braintree/braintree-web/issues/480#issuecomment-696310477).

Here's the link to the location where it is missing: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aef680843dc3938080759c8ffdb7b389890f1b71/types/braintree-web/modules/hosted-fields.d.ts#L40

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #50724

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## braintree-web ([<kbd>unpkg</kbd>](https://unpkg.com/browse/braintree-web@latest/))
was missing the following properties:
1. localPayment
1. masterpass
1. paymentRequest
1. vaultManager
1. visaCheckout

<details>
<summary>as well as these 1 other properties...</summary>
<p>preferredPaymentMethods</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 011e419168cca611699c2ae595bb52c469995af6
</p>

**Review by jbuckner — APPROVED** [review]
Looks good 👍 Thanks for the update!

**Comment by martin-badin** [comment]
Ready to merge

**Review by Courtney2n — COMMENTED** [review]
Fixed

**Pull request merged**
