### PR TITLE
[@types/apidoc] Fix wrong args + add `src` param

### PR DESCRIPTION
**Pull request by rigwild**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
 - Add `src` parameters: https://github.com/apidoc/apidoc/blob/master/bin/apidoc#L106
 - Fix invalid argument definitions: https://github.com/apidoc/apidoc-core/blob/568d40f7f41b705bf3a90798716648341a803964/lib/index.js#L42-L97
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by rigwild** [comment]
@hoonga I checked your previous edits to the typings by looking more into `apidoc-core`.
It seems that the filters, languages, parsers and workers options are simple records objects (see https://github.com/apidoc/apidoc-core/blob/568d40f7f41b705bf3a90798716648341a803964/lib/index.js#L42-L97)

I also added the `src` arg, I don't know how I could forgot about it in the first place 
:sweat_smile:

**Comment by hoonga** [comment]
If you check here
https://github.com/apidoc/apidoc-core/blob/568d40f7f41b705bf3a90798716648341a803964/lib/filter.js#L23-L27
You can directly `inject` filters, which is also possible for others (languages, parsers, workers).

I'd suggest we use both options

**Comment by rigwild** [comment]
> If you check here
> [apidoc/apidoc-core@`568d40f`/lib/filter.js#L23-L27](https://github.com/apidoc/apidoc-core/blob/568d40f7f41b705bf3a90798716648341a803964/lib/filter.js#L23-L27)
> You can directly `inject` filters, which is also possible for others (languages, parsers, workers).
> 
> I'd suggest we use both options

Good catch!

**Comment by hoonga** [comment]
LGTM!

**Comment by rigwild** [comment]
@hoonga You need to review the pr and to click on "approve" here so I can merge: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46474/files

**Review by hoonga — APPROVED** [review]

**Comment by rigwild** [comment]
Ready to merge

**Pull request merged**
