### PR TITLE
Update Rebass typings to use types from Styled System

### PR DESCRIPTION
**Pull request by alexdriaguine**
Using the types from the [Styled System](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-system) seems like a better option. They have thourough interface for all the different kinds of props, and since Rebass uses Styled System under the hood it makes sense to have these types based on Styled System.

I'm not sure about the version bump though. There are none breaking changes so I bumped the minor version, even though the changes are substantial.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-system>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
CC @rhysd @ryee-dev for review

**Comment by eloiqs** [comment]
I think there may be missing `alt: string` on `ImageProps` @alexdriaguine

**Comment by alexdriaguine** [comment]
I noticed I missed the `as` prop for Heading. Not at a computer right now but will fix as soon as I have time

**Comment by eloiqs** [comment]
@sheetalkamat Sure

@alexdriaguine +1 for HTMLAttributes.Regarding the `as` prop, doesn't it come from styled-components? Would it make sense to somehow extend the rebass components with `StyledComponentClass` from @types/styled-components instead?

**Comment by alexdriaguine** [comment]
@eloiqs I've updated components to extend `StyledComponentClass` instead :grin:, so now the `as` prop works as intended. Perhaps we should do a major version bump so major version of types follows the one of the project? :thinking:

**Comment by alexdriaguine** [comment]
Although, I'm not really sure what to do about the second type argument (Theme) to `StyledComponentClass`. Passing in `{}` for now..

**Comment by eloiqs** [comment]
Maybe we should let the generic types flow from higher up in the rebass classes like `BoxClass<P extends BoxProps, T, O = P> extends StyledComponentClass<P, T, O>`. If i'm not mistaken `P` is the props type, `T` is the theme type and I'm still not sure what `O` is but i'd pass it as well. +1 for bumping the major version, and would you mind adding me to the contributors list 😅?

**Comment by alexdriaguine** [comment]
@eloiqs absolutely!

Not sure about `O`, but it seems to be `Original Props` or something like that.. By default it's assigned the value of `P`

I'm not sure i follow why sending the generic Props and Theme type arguments like that would have a benefit, Rebass components should not have any generic props if i'm not mistaken?

It would be if users have a typescript version that supports generic tsx and can do `<Box<CustomBoxProps>>` but the props defined in `CustomBoxProps` would not be picked up by rebass components anyway. If we want to extend some component and add additional props to it, I think this is achieved like
```typescript
interface CustomBoxProps extends BoxProps {
    customProp: number
}
const CustomBox = styled<CustomBoxProps, BoxProps>(Box)`
    ${(props) => props.customProp}
`
```

Thoughts? :grin:

**Comment by eloiqs** [comment]
Yeah I think you are right :) 

My concern was for theme props but I saw on the styled-components doc that you can require the styled function and re-export and cast the whole module with your theme type so that ‘${props => props.theme}’ is properly typed when you extend with ‘styled’.

The other way to extend I think is by wrapping a component in your own and spreading down the props like ‘const Header = (props) => <Box {...props} as=“header” css={{}} />’ but I don’t know how to make sure this Header component would have all prop types from Box and styled-component + the custom props. 

I will be trying some things as soon as I get at a computer.

**Comment by eloiqs** [comment]
Actually your example gives me errors :(

Im adding some test cases to test extension and theme prop right now. I'm pretty new to the whole github thing, I'll see if I can commit changes to your PR, I'm getting pretty close to supporting what I was mentioning earlier.

**Comment by alexdriaguine** [comment]
@eloiqs sure you have the newest version of the styled components types?

I'll check it out when i have som free time :)

**Review by rhysd — COMMENTED** [review]
Looks good for me but I'm not sure since I'm no longer actively using rebass in my projects. I did not catch up for the latest release changes. Let me leave others to approve.

**Comment by eloiqs** [comment]
@alexdriaguine In the PR I sent you (https://github.com/alexdriaguine/DefinitelyTyped/pull/1) I added a test for styled-components based extension with the right way to do it, and it is using the types from this repo so it should be v4 😄

**Comment by eloiqs** [comment]
@alexdriaguine Please can you take a look at the improvement suggestions I pr'ed you? I think with those additions it would make it a really strong merge candidate 😁

**Comment by alexdriaguine** [comment]
@eloiqs sorry, had a busy week 😢 I'll try to make some time to take a look as soon as I can! 😁

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Changes as requested by @eloiqs

**Comment by eloiqs** [comment]
Yep I think the version should be like rebass now so `3.0`

**Comment by alexdriaguine** [comment]
I'll fix version and check out why tests are failing as soon as I'm at a computer 😁

**Comment by alexdriaguine** [comment]
@eloiqs 

I'm getting a `[ts] Operator '>' cannot be applied to types 'boolean' and 'string'.` at the style extended tests in the tests. Could you check it out? :)

Here is the log I'm getting
```
Error in rebass
Error: /home/alex/Development/OSS/DefinitelyTyped/types/rebass/rebass-tests.tsx:296:23
ERROR: 296:23  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Operator '>' cannot be applied to types 'boolean' and 'string'.
ERROR: 296:35  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
'CustomBoxProps' only refers to a type, but is being used as a value here.
ERROR: 297:11  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Parameter 'props' implicitly has an 'any' type.
ERROR: 298:11  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Parameter 'props' implicitly has an 'any' type.
ERROR: 299:11  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Parameter 'props' implicitly has an 'any' type.
ERROR: 303:10  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
JSX element type 'CustomBox' does not have any construct or call signatures.
```

**Comment by alexdriaguine** [comment]
@eloiqs 

I had a closer look and it seems to me that the genric arguments are in the wrong place :confused: 

Putting them like
```typescript
const CustomBox = styled<CustomBoxProps>` ... `
```
gives me TS errors aswell.

One could extend the components with custom props this way:

```typescript
interface CustomBoxProps {
        customProp: number
        optionalProp?: string
    }

    const {default: styled} = styledComponents as ThemedStyledComponentsModule<Theme>

    const CustomBox = styled(Box)`
        ${(props: CustomBoxProps) => ''}
    `

    return (
        <CustomBox customProp={3} as="header" css={{maxWidth: '200px'}} theme={{dark: {backgroundColor: '#666666'}}} />
    )
```

and the new component will pick up that it should allow `CustomBoxProps`.
That's how I've extended styled components with custom props before. Whatcha think? :D

**Comment by alexdriaguine** [comment]
May be because of TS version. I think running 'npm test' installs and runs on different versions ☺

**Comment by alexdriaguine** [comment]
According to Travis logs it goes from 2.0 to 3.1 and testing each minor version

**Comment by eloiqs** [comment]
Ok, I think I get it, the template string interpolations got improvments in 3.0+ but we got to support lower typescript versions.

I don't see anything wrong with going with what you have then.

**Comment by alexdriaguine** [comment]
Ah okay! Yeah, you can still do it the way you want to if running TS 3.0, even if the tests are implemented another way to appease earlier versions of TS 😁 

I'll push the fix later, just ran away from my computer..

**Comment by eloiqs** [comment]
@sheetalkamat is there anything else we need to do in order to get this merged?

**Review by eloiqs — APPROVED** [review]

**Review by eloiqs — APPROVED** [review]

**Comment by eloiqs** [comment]
@sheetalkamat my changes were merged in this PR, can you dismiss your change request so we can get this merged?

**Comment by alexdriaguine** [comment]
So apparently another PR was merged for rebass typings, I'll have to fix the conflicts.

We should try to get this merged as fast as possible since the typings now are not complete.

**Comment by eloiqs** [comment]
@alexdriaguine maybe we should put the old typings in a v2 folder, to keep supporting rebass v2 users

**Comment by alexdriaguine** [comment]
However there are no `rebass@v2`, the versions before this did not follow semver, they just bumped minor/patch version. We have bumped major to `3` so it follows the librarys version

**Comment by andy-ms** [comment]
@sheetalkamat Good to merge?

**Comment by eloiqs** [comment]
@sheetalkamat I think we are good to go here, don’t you agree?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eloiqs** [comment]
@alexdriaguine at this point do you think closing this PR and opening a new one would bring more visibility to it / is an acceptable thing to do? :/ 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexdriaguine** [comment]
@eloiqs Not sure. Let's try pinging @sheetalkamat once more and see if we can get this merged :)

**Comment by alexdriaguine** [comment]
So I just checked and seems like SC typings have been updated, `ThemedOuterStyledProps` does not exist anymore in 4.1, so we have to redo our typings... @eloiqs. I'm gonna have a look it tonight if possible :)

**Comment by alexdriaguine** [comment]
@eloiqs @sheetalkamat I've updated the PR now so it works with the latest version of styled components typings. Could you take a look and see what you think?

**Comment by alexdriaguine** [comment]
I'm gonna close this, seems like another PR has been merged for new types.

**Pull request closed without merging**
