### PR TITLE
[react] revert recent change to useState

### PR DESCRIPTION
**Pull request by ferdaber**
This reverts commit 598ffd0b99dcfa511ab6056d9652c99665a7bbe4. The PR is #36080

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
*sigh*

**Comment by DanielRosenwasser** [comment]
Maybe you can send a follow-up PR to add a comment on why this is a problem.

**Comment by joehillen** [comment]
@DanielRosenwasser I added a test case https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36338

**Comment by ferdaber** [comment]
I don't think it's a bad idea per se, it is somewhat edge-casey as far as
use case goes. We do need to figure out why the contextual typing is lost
after the change was made, because it seemed to be working fine in the test
cases.

**Pull request merged**
