### PR TITLE
Add types for @babel/{core,generator,parser,template,traverse}

### PR DESCRIPTION
**Pull request by mgroenhoff**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project. **Did not work with scoped packages?**
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

**Note** to current maintainers of `babel-{core,generator,template,traverse,types}` types: If you want me to add you as maintainer one or more of the types please let me know!

@baxtersa, @bcherny, @ForbesLindesay, @johnnyestilles, @marvinhagemeister, @mohsen1, @rpetrich, @tdreyno, @yortus

### CODE REVIEW

**Comment by mgroenhoff** [comment]
For reference: #27384

**Comment by yortus** [comment]
@mgroenhoff wherever these new files are based off the babel v6 definitions, I think you should leave all the contributors names as they were, and add your own. As currently submitted it looks like you wrote all these definitions by yourself, which is a little unfair on all the others that have put time into them.

**Comment by mgroenhoff** [comment]
All of them besides `@babel/core` are just copy/pasted with some minor additions/unification and I did some larger tweaks to @babel/core.

I asked all the maintainers if they want to be a maintainer for these types too because that would indeed be unfair but I figured I should ask first instead of just add them.

@yortus Does that mean that I can add you as a maintainer to all of the types 👍 ?

**Comment by yortus** [comment]
@mgroenhoff the list of names at the top of the definitions after 'definitions by' are the *contributors* to these definitions. None of these names should be removed. It's not relevant which of these people are currently actively maintaining the definitions.

**Comment by mgroenhoff** [comment]
Yes I know what the line `Definitions by:` means. With `maintainers` I actually meant `contributors` since the people in that list will be asked to review changes made to types which they might not want to anymore which is why I asked.

Do you want me to add them back without their consent?

**Comment by andy-ms** [comment]
If everything else is copy-pasted, I think the authors should be too.

**Comment by mgroenhoff** [comment]
They are already added

**Comment by mgroenhoff** [comment]
Please do not merge until https://github.com/Microsoft/types-publisher/issues/474 is merged and published.

**Comment by mgroenhoff** [comment]
@andy-ms I believe something went wrong during publishing. In `package.json` the following dependencies are present:
```
  "dependencies": {
    "@babel/types": "^7.0.0-beta.54",
    "@types/babylon": "*"
  },
```
But I expected to also see `@babel/generator`, `@babel/traverse` and `@babel/template` in there. Those types were not present at the time but included in this PR. I suppose another publish round will do the trick? Is this an issue with `types-publisher`?

**Pull request merged**
