### PR TITLE
Including missing array operator on update

### PR DESCRIPTION
**Pull request by albertossilva**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://docs.mongodb.com/manual/reference/operator/update>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by albertossilva** [comment]
@CaselIT In order to get out of that other messy branch... I decided to restart from scratch.

**Review by CaselIT — APPROVED** [review]
Looks ok. Thanks

**Comment by CaselIT** [comment]
> @CaselIT In order to get out of that other messy branch... I decided to restart from scratch.

That was probably the best move

**Comment by CaselIT** [comment]
@albertossilva Since now we also have some nicely organized tests in mongodb, could you add some for the newly added properties?

I forgot before

**Comment by albertossilva** [comment]
@CaselIT ow man... it is quite a challenge create type that define mongo operator following those expectations.... but I did it. =) thanks for the CR

**Comment by CaselIT** [comment]
that are some complex types. The test look good.

I think there is a way to tell the that a certain line should produce an error in the test, so the comments can be avoided.
 I'm not familiar with how the test framework works, maybe @HosseinAgha can help.

**Comment by albertossilva** [comment]
> that are some complex types. The test look good.
> 
> I think there is a way to tell the that a certain line should produce an error in the test, so the comments can be avoided.
> I'm not familiar with how the test framework works, maybe @HosseinAgha can help.

Oh yes... I tried do it, but I couldn't

**Comment by HosseinAgha** [comment]
@albertossilva checkout `filterQuery.ts` and `insertX.ts` tests
you can use `// $ExpectError` like this
```
// $ExpectError
await collectionT.find({ addedBy: { family: 'Anderson' } }).toArray();
```
you may also use `// $ExpectType` for passing tests
```
result.ops[0]._id;   // $ExpectType ObjectId
```

**Comment by albertossilva** [comment]
Where did you get this information, I would like to learn more about it.

**Comment by HosseinAgha** [comment]
@albertossilva https://github.com/Microsoft/dtslint#write-tests

**Comment by HosseinAgha** [comment]
Unfortunately maintainers merged this :))   
Could you please add the failing tests in another PR?

**Comment by albertossilva** [comment]
Yes... I will do it.

**Comment by dauledk** [comment]
Sorry to bring this up, but I don't know where else to ask for help 😳. But this PR seems to have disabled support for using $currentDate with optional types, like the following: 

```typescript
interface Car {
  name: string;
  updatedDate?: Date;
}

const updateQuery: UpdateQuery<Car> = {
  $currentDate: {
    updatedDate: true // <== this throws error when updatedDate is optional.
  }
}

```

**Pull request merged**
