### PR TITLE
@types/react - rename useImperativeMethods -> useImperativeHandle

### PR DESCRIPTION
**Pull request by threepointone**
React is renaming one of its hooks `useImperativeMethods` to `useImperativeHandle` (https://github.com/facebook/react/pull/14565) Thought I'd try to get a PR here ready for when we launch (which will be soon...ish). Do not merge this in just yet!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react/pull/14565 / https://github.com/reactjs/reactjs.org/pull/1544
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (sunil: I'm not)

### CODE REVIEW

**Review by ferdaber — APPROVED** [review]

**Comment by ferdaber** [comment]
Ugh it's to the point where any React types changes will timeout the CI server due to the number of dependent packages. Pinging Mr. @johnnyreilly

**Comment by Kovensky** [comment]
It's also partially because of the complexity of some conditional types
(when I was prototyping what eventually became ComponentPropsWithRef its
mere presence was enough to noticeably slow down vscode); but yeah, sheer
numbers are what's bringing us down here......

I ran into this same issue the last time I tried doing any major change,
and the suggestion was to just do TypeScript Version bumps in a PR and
actual changes in another, but that wouldn't solve the problem at all. The
tests would still have to run because they're still packages that depend on
the changed packages.

**Comment by ferdaber** [comment]
This one isn't even a TS version bump though, which IMO makes it even worse because it basically means we're blocked from making any changes to this package. 😢

**Review by Jessidhia — APPROVED** [review]

**Comment by Kovensky** [comment]
Looks like there's nothing DT can do to _directly_ fix this: https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts

We need either dtslint to be able to be split into multiple jobs, or typescript to speed up. A relatively easy change is probably to use travis build matrices for each typescript version to test, instead of leaving it to dtslint to fetch and install and run all tests for all versions.

**Comment by johnnyreilly** [comment]
I think we need the help of someone on the Typescript team I'm afraid...

**Comment by Kovensky** [comment]
A workaround that can be used locally in any `.ts` file:

```ts
import {} from 'react'
declare module 'react' {
  export const useImperativeHandle: typeof useImperativeMethods
  export function useDebugValue<T>(
    value: T,
    formatter?: (value: T) => string | number | object
  ): void
}
```

This won't erase the `useImperativeMethods` and so it will throw at runtime if you actually call it; there's only so much module augmentations can do. But there will be a `useImperativeHandle` and `useDebugValue` to use.

@bvaughn is the `formatterFn` parameter intended to be public API? It's not documented but there are tests for it in the `react-debug-tools` package.

**Comment by ericanderson** [comment]
@DanielRosenwasser seems some help is needed here

**Comment by bvaughn** [comment]
> @bvaughn is the `formatterFn` parameter intended to be public API? It's not documented but there are tests for it in the `react-debug-tools` package.

Yes. It's public. I'll correct the docs oversight.

**Comment by DanielRosenwasser** [comment]
> Ugh it's to the point where any React types changes will timeout the CI server due to the number of dependent packages. Pinging Mr. @johnnyreilly 

Oh boy. Okay. Trying to run one more build on here. I'll clone and try it out locally if this is blocked.

CC @RyanCavanaugh @sandersn

**Comment by bvaughn** [comment]
Hurry up, @threepointone

**Comment by Jessidhia** [comment]
Simply rebasing this against `master` should keep the bot... satisfied 😓

**Comment by threepointone** [comment]
I rebased, but I'm getting a couple of unrelated errors in packages I haven't touched (visible on the last CI build too - https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/479608764?utm_source=github_status&utm_medium=notification) not sure how to proceed from here tbh.

**Comment by ferdaber** [comment]
It's fine to merge I think. We had the hooks api as part of the official releases of react types for a while now, people are expecting them to be there 💁🏻‍♀️

**Comment by Jessidhia** [comment]
Would be nice to also have useDebugValue. The version I put in my snippet is correct, it's just missing the JSdoc. I can just do it in another PR though, there are other things I want to tweak in the JSdocs.

**Comment by sw-yx** [comment]
tsbot is a cruel master

**Comment by johnnyreilly** [comment]
I feel this could be turned into a thriller movie where that final build passing is the big climax... "Will it pass? Will it pass?? Come on!!!!" 😁

**Comment by sw-yx** [comment]
serious question - is DT now too big for Travis?

**Comment by ferdaber** [comment]
@Jessidhia had a good idea of using build matrices in Travis to test out the individual supported versions of TS, which supports some kind of parallelism. I think more specifically, the react types have gotten too big for Travis :)

**Comment by sw-yx** [comment]
oh so this travis run takes almost 1hr just for the react stuff? i assumed it was running on all of DT. how can the react types take that long? its big but not lodash big. i think i’m misunderstanding you.

**Comment by ferdaber** [comment]
Yes, the travis build looks at dependents of the package being updated, and tests those dependents, against all supported versions of TS going up from the supported version in the package itself. Since react types supports 2.8, it tests 200 dependencies * [2.8, 2.9, 3.0., 3.1, 3.2] which is over 1000 test 🙃

**Comment by sw-yx** [comment]
oh boy. wow. i underestimate the scope of @types/react. thanks guys.

**Comment by artyomtrityak** [comment]
How can i define type for setter from useState?

```ts
const [openDropdownName, setOpenDropdownName] = useState<IDropdowns>(null);
....
return [openDropdownName, setOpenDropdownName];
```

I am trying to define type for `setOpenDropdownName`

```
enum DROPDOWNS {
  REPORT = "REPORT",
  USER = "USER"
}
type IDropdowns = keyof typeof DROPDOWNS | null;

Dispatch<SetStateAction<IDropdowns>> // does not work, can not find SetStateAction
```

**Pull request merged**
