### PR TITLE
Fix typo paramter

### PR DESCRIPTION
**Pull request by antonhalim**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Hello, this is my first PR here. I haven't seen an open PR for this issue/typo. While developing on VS Code, I found what I believe as a typo `paramter` coming from this repo as the source of the IntelliSense documentation. Please let me know if its a false alarm. And/or anything I can update to have this to be fixed.

Thanks!

screen shot 2018-10-14 at 9 59 47 pm
`paramter` typo in the second line of the paragraph.

### CODE REVIEW

**Review by ajafff — APPROVED** [review]

**Review by ZaneHannanAU — APPROVED** [review]
Should work with the exception of react being a pain but still fine

**Comment by ZaneHannanAU** [comment]
```
business-rules-engine failing:
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/business-rules-engine/Validation.d.ts:6:1
ERROR: 6:1  expect  TypeScript@next compile error: 
Definitions of the following identifiers conflict with those in another file: LessThan, LessThanEqual, Equal, NotEqual, GreaterThanEqual, GreaterThan, Error, ValidationFailure, ValidationResult, CompositeValidationResult, AbstractValidator, MessageLocalization
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/business-rules-engine/index.d.ts:9:1
ERROR: 9:1  expect  TypeScript@next compile error: 
Definitions of the following identifiers conflict with those in another file: LessThan, LessThanEqual, Equal, NotEqual, GreaterThanEqual, GreaterThan, Error, ValidationFailure, ValidationResult, CompositeValidationResult, AbstractValidator, MessageLocalization
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

... unrelated errors that happen often so far.

**Comment by ZaneHannanAU** [comment]
jsdom again...

yeah, next happened again

anything involving types/node fails by default because of react/jsdom/puppeteer

we really need to deprecate the ones that cause unneeded errors at some point

actually if we can just move them to one called "deprecated" or something it'll help with tests

**Comment by ZaneHannanAU** [comment]
Cool so we can deprecate at least

```log
6494:Error: The following packages had errors: business-rules-engine, jsdom, next, puppeteer/v0, react-flag-icon-css, react-helmet/v4, react-native-modalbox, react-native-svg-charts, react-native-vector-icons, reactstrap, redux-form
```

(from https://api.travis-ci.org/v3/job/449219821/log.txt )

**Review by islishude — APPROVED** [review]
LGTM

**Review by ThomasdenH — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Comment by antonhalim** [comment]
@ZaneHannanAU Thanks for the clarification. @DanielRosenwasser Thanks for merging it. I know its small fixes but it made my day.

**Pull request merged**
