### PR TITLE
[interactjs] Fix module name

### PR DESCRIPTION
**Pull request by elektromodulator**
interact.js library uses UMD pattern, and in its AMD module definition 'interact' module name is used, making it incompatible with the current d.ts file.
See: interact.js distributed with npm or bower package.

### CODE REVIEW

**Comment by adidahiya** [comment]
huh, I see how that would be a problem for you @elektromodulator. However the `"name"` in package.json is "interact.js" (https://github.com/taye/interact.js/blob/master/package.json) and that is the standard we follow on DefinitelyTyped. It's probably best to get this resolved in the interact.js package itself (CommonJS and AMD module names should match). I'm personally a fan of making the module name "interact" but that would break existing CommonJS consumers.

**Comment by elektromodulator** [comment]
Well, that sucks :(
I created an issue for consistent module names for interact.js, but I fear this won't be fixed, as this inconsistency is clearly stated in its documentation, so it is known to the author.
What do you think about defining two modules in the d.ts, an "interact" and an "interact.js" module, which are identical otherwise, as a solution?

**Comment by elektromodulator** [comment]
I'm not sure about this solution.
Is it OK to have different d.ts files for AMD and CommonJS in DefinitelyTyped?
Is portability between AMD and CommonJS environments something we should not be concerned with in case of definition files?
What do you think?

**Comment by mhegazy** [comment]
The module identifier is what counts. this is what the compiler uses to resolve the import. so if the package does indeed have two module names, regardless of which module-system is used, then we should have two folders.

**Comment by anubmat** [comment]
Thanks for your contribution. This PR has unaddressed comments for over a week and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by elektromodulator** [comment]
Sorry for not responding earlier, I was taking a long vacation.
Since this issue is not that urgent for me, I'll create another pull request later.
Maybe by then the interact.js package name issue will be resolved in the JS library itself.

**Pull request closed without merging**
