### PR TITLE
Missing property `socket.destroyed`

### PR DESCRIPTION
**Pull request by maghis**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v4.x/docs/api/net.html#net_socket_destroyed
- [x] Increase the version number in the header if appropriate.

https://nodejs.org/dist/latest-v4.x/docs/api/net.html#net_socket_destroyed

### CODE REVIEW

**Comment by maghis** [comment]
@zhengbli @andy-ms @mhegazy feedback? Travis timed out.

**Comment by andy-ms** [comment]
@maghis Please rebase onto the latest `types-2.0` to fix tests.
Also, you are editing `node-4.d.ts`, did you mean `node/index.d.ts`?

**Comment by maghis** [comment]
@andy-ms thanks, better?

**Comment by maghis** [comment]
@vvakame @zhengbli @andy-ms @mhegazy any feedback?

**Pull request merged**
