### PR TITLE
chore(node): remove non current/lts versions

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/en/about/releases/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Changes keep being made to non LTS/Current versions of the node typings, imo we should not maintain these for the same reason the node team doesn't support these versions.

Since the maintenance effort is significantly lower however, I think adding an extra 6 months as a grace period for LTS versions is reasonable.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Looks like removing version `0` breaks the build pipeline lol.

**Review by Flarna — APPROVED** [review]

**Comment by SimonSchick** [comment]
@jessetrinity can I get some 👀 ?

**Comment by jessetrinity** [comment]
Unrelated to the failure - why do you want to remove all of the old versions?

**Comment by nguymin4** [comment]
I guess Simon's idea was to remove all end-of-life version https://github.com/nodejs/Release
But my opinion is that we only remove versions < 8  which is maintainance LTS until the end of December 2019.

**Comment by SimonSchick** [comment]
@jessetrinity rationale is in OP
@nguymin4 That is correct, I want to retain all *active* LTS versions but at the same time remove all non unmaintained non-LTS versions after v8 (9, 11) as they have the lowest value for consumers.

**Comment by SimonSchick** [comment]
@jessetrinity do I have to re-open this?

**Pull request closed without merging**
