### PR TITLE
delete(imagemin-pngquant)

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Package ships its own types as early os of 7.0.0:
https://github.com/imagemin/imagemin-pngquant/releases/tag/v7.0.0
https://github.com/imagemin/imagemin-pngquant/pull/54

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by TokugawaTakeshi — APPROVED** [review]
I approve your changes, but please resolve the failed tests.

**Comment by peterblazejewicz** [comment]
> I approve your changes, but please resolve the failed tests.

Done, there was a mistake in the DT, allowing same version as the version that introduced TS (7.0.0). I've referenced the verison 8.0.0 simply.
Thanks!

**Review by TokugawaTakeshi — APPROVED** [review]
LGTM

**Comment by orta** [comment]
Rock, thanks

**Pull request merged**
