### PR TITLE
[@uswds/uswds]: Fix inaccurate typings for optional elements, add new components

### PR DESCRIPTION
**Pull request by aduth**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
   - [Optional target for `on` and `off`](https://github.com/uswds/uswds/blob/4ec68cecfe1288fa510f3d54c97323e68812dc35/packages/uswds-core/src/js/utils/behavior.js#L12)
   - [Optional target for `init` and `teardown` uses `selectOrMatches`, documented as "If not provided, defaults to the document"](https://github.com/uswds/uswds/blob/4ec68cecfe1288fa510f3d54c97323e68812dc35/packages/uswds-core/src/js/utils/select-or-matches.js#L15-L16)
   - [`tooltip.show` receives 3 arguments](https://github.com/uswds/uswds/blob/4ec68cecfe1288fa510f3d54c97323e68812dc35/packages/usa-tooltip/src/index.js#L33)
   - [New `button` component](https://github.com/uswds/uswds/blob/4ec68cecfe1288fa510f3d54c97323e68812dc35/packages/usa-button/src/index.js), added in [v3.5.0](https://github.com/uswds/uswds/releases/tag/v3.5.0) (https://github.com/uswds/uswds/pull/4385)
   - [New `range` component](https://github.com/uswds/uswds/blob/4ec68cecfe1288fa510f3d54c97323e68812dc35/packages/usa-range/src/index.js), added in [v3.7.0](https://github.com/uswds/uswds/releases/tag/v3.7.0) (https://github.com/uswds/uswds/pull/5472)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.
   - Updated to from `3.3.9999` to `3.7.9999`

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/uswds__uswds/js/usa-range/index.d.ts
1. types/uswds__uswds/js/usa-button/index.d.ts
1. types/uswds__uswds/uswds__uswds-tests.ts
1. types/uswds__uswds/js/usa-tooltip/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against af3bd7f8f2820b2be1c0bb313891605d6bb6a198
</p>

**Comment by aduth** [comment]
Hi @morganmspencer 👋 Thanks for maintaining these types. I added myself to the owners list here since I'd be willing to help maintain them. I'm a heavy consumer and contributor to USWDS so I'd have an interest in keeping these types accurate and up-to-date. Let me know if there's any issue!

**Review by morganspencerdev — APPROVED** [review]
Thanks for submitting these updates!

**Comment by aduth** [comment]
Ready to merge

**Comment by aduth** [comment]
Hey @morganmspencer , I noticed I forgot to update the [`index.d.ts` file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/uswds__uswds/index.d.ts) as part of this to include `range` and `button`. I was going to create a follow-up fix, but in trying to consider how to write tests for this, it occurred to me that the root `@uswds/uswds` doesn't actually have any exported members, so maybe it's correct to have just [`js/index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/uswds__uswds/js/index.d.ts) (imported as [`@uswds/uswds/js`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/792195da327585d1bb0df798060f78ba7b30e414/types/uswds__uswds/uswds__uswds-tests.ts#L25))?

Do you think it could make sense to remove or empty out the contents of `index.d.ts`?

**Pull request merged**
