### PR TITLE
fix type of  cytoscape's  AbstractEventObject

### PR DESCRIPTION
**Pull request by isamu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://js.cytoscape.org/#events/collection-events
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by isamu** [comment]
If you specify a collection or graph event, a type error will occur.
It works when I apply my patch.
```
This comparison appears to be unintentional because the types 'UserInputDeviceEventName | UserInputDeviceEventNameExt' and '"select"' have no overlap.
    64 |         context.emit("update_position", position);
    65 |       }
  > 66 |       if (e.type === "select") {
  ```

**Comment by jakebailey** [comment]
The failure was just fixed on master, you should be able to merge to fix CI.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## cytoscape ([<kbd>unpkg</kbd>](https://unpkg.com/browse/cytoscape@latest/))
was missing the following properties:
1. version
1. stylesheet
1. Stylesheet
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f052ee3f7c66f4bb61554c5505b9276a19200d70
</p>

**Comment by isamu** [comment]
@jakebailey
Thank you for your advice !!
I fixed my PR.

**Comment by isamu** [comment]
Is there any action I should take?
Waiting to be merged.

**Comment by jakebailey** [comment]
The package is still waiting for author review (or if that times out, a maintainer review).

**Review by gabritto — APPROVED** [review]

**Comment by isamu** [comment]
Ready to merge

**Pull request merged**
