### PR TITLE
[WIP] React native elements

### PR DESCRIPTION
**Pull request by iRoachie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://react-native-training.github.io/react-native-elements/API/avatar/#avatar-props>>

### CODE REVIEW

**Comment by iRoachie** [comment]
Don't merge. WIP

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by iRoachie** [comment]
@RyanCavanaugh Is there any label you have to block merges? It's definitions for a library that are still ongoing. Still a WIP

**Comment by RyanCavanaugh** [comment]
@iRoachie won't be merged automatically, no worries

**Comment by RyanCavanaugh** [comment]
Don't listen to @typescript-bot 's lies. Robots can't be trusted.

**Comment by iRoachie** [comment]
Hahah that is hilarious

**Comment by andy-ms** [comment]
CC authors @alloy @gyzerok @huhuanming @iRoachie

**Comment by iRoachie** [comment]
@andy-ms I'm the author. Just leave the PR it's a WIP, all the typings arent there yet. I'm in the process of finishing adding them

**Review by weswigham — CHANGES_REQUESTED** [review]
This is still WIP. By requesting changes, the bot should tag this PR appropriately for future triage. Ping the `@DefinitelyTyped/typescript-team` for a review when you're done.

**Comment by iRoachie** [comment]
@weswigham is there a special label to tell the bot to not watch this PR? Like a WIP label?

**Comment by weswigham** [comment]
That's pretty much what I just did by requesting changes. Until I approve, it shouldn't come calling again.

**Comment by iRoachie** [comment]
Phew lol thought we had a robot uprising there 😆

**Comment by ifiokjr** [comment]
@iRoachie are there any plans to take this forward? I'm about to use this library in a project and was wondering if I could help out.

**Comment by iRoachie** [comment]
@ifiokjr sure man, i’d Appreciate the help. You can see the progress in the README.

**Comment by gyzerok** [comment]
Should this PR be better closed? There is no sense in keeping abandoned PRs. If the work will continue then a new PR could be created once the work is finished.

**Comment by iRoachie** [comment]
Cool np

**Comment by ifiokjr** [comment]
@iRoachie, I'll get started soon.

**Pull request closed without merging**
