### PR TITLE
[react] Make "type" button attribute match W3C spec

### PR DESCRIPTION
**Pull request by lukyth**
Continue from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33648

According to https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type, the `type` button attribute can only be one of the three keywords, `"submit"`, `"reset"`, and `"button"`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type
- [ ] ~~Increase the version number in the header if appropriate.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Review by ferdaber — APPROVED** [review]

**Comment by lukyth** [comment]
I ran the test locally (`yarn test` at the root directory) and there're some errors.
```
=== ERRORS ===



Error in ramda
Error: /Users/kanitkorn/Code/DefinitelyTyped/types/ramda/ramda-tests.ts:970:26
ERROR: 970:26  expect  TypeScript@next compile error:
Argument of type '<T>(obj: Record<"id", T>) => T' is not assignable to parameter of type '(a: Record<"id", T>) => string'.
  Type 'T' is not assignable to type 'string'.

    at /Users/kanitkorn/Code/DefinitelyTyped/node_modules/dtslint/bin/index.js:210:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)


Error in restify
Error: At least one of the project urls listed in the header, ["https://github.com/restify/node-restify","http://restifyjs.com"], must match the homepage listed by npm, 'http://restify.com'.
If your d.ts file is not for the npm package with URL http://restify.com,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package restify-browser

    at check (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
    at dtsCritic (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:20:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Error in storybook-addon-jsx
Error: At least one of the project urls listed in the header, ["https://github.com/storybooks/storybook"], must match the homepage listed by npm, 'https://github.com/storybooks/addon-jsx'.
If your d.ts file is not for the npm package with URL https://github.com/storybooks/addon-jsx,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package storybook-addon-jsx-browser

    at check (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
    at dtsCritic (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:20:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Error in strophe
Error: /Users/kanitkorn/Code/DefinitelyTyped/types/strophe/index.d.ts:1111:3
ERROR: 1111:3  expect  TypeScript@next compile error:
Exports and export assignments are not permitted in module augmentations.

/Users/kanitkorn/Code/DefinitelyTyped/types/strophe/muc.d.ts:841:23
ERROR: 841:23  expect  TypeScript@next compile error:
Namespace '"/Users/kanitkorn/Code/DefinitelyTyped/types/strophe/index".Strophe' has no exported member 'MUC'.

/Users/kanitkorn/Code/DefinitelyTyped/types/strophe/strophe-tests.ts:97:31
ERROR: 97:31   expect  TypeScript@next compile error:
Argument of type '(msg: HTMLElement) => boolean' is not assignable to parameter of type '(stanza: Element) => boolean'.
  Types of parameters 'msg' and 'stanza' are incompatible.
    Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 110 more.

    at /Users/kanitkorn/Code/DefinitelyTyped/node_modules/dtslint/bin/index.js:210:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)


Error in vscode
Error: At least one of the project urls listed in the header, ["https://github.com/microsoft/vscode-extension-vscode"], must match the homepage listed by npm, 'https://github.com/microsoft/vscode'.
If your d.ts file is not for the npm package with URL https://github.com/microsoft/vscode,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package vscode-browser

    at check (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
    at dtsCritic (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:20:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Error in restify
Error: At least one of the project urls listed in the header, ["https://github.com/restify/node-restify","http://restifyjs.com"], must match the homepage listed by npm, 'http://restify.com'.
If your d.ts file is not for the npm package with URL http://restify.com,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package restify-browser

    at check (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
    at dtsCritic (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:20:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Error in storybook-addon-jsx
Error: At least one of the project urls listed in the header, ["https://github.com/storybooks/storybook"], must match the homepage listed by npm, 'https://github.com/storybooks/addon-jsx'.
If your d.ts file is not for the npm package with URL https://github.com/storybooks/addon-jsx,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package storybook-addon-jsx-browser

    at check (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
    at dtsCritic (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/dts-critic/index.js:20:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: The following packages had errors: ramda, restify, storybook-addon-jsx, strophe, vscode, restify, storybook-addon-jsx
    at doRunTests (/Users/kanitkorn/Code/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:129:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Most of them are header errors. There's an actual type error in `ramda` and `strophe`, which doesn't seem to be related to this PR.

I think it's safe to merge this PR and create issues for those errors separately. 

cc @sandersn

**Comment by sandersn** [comment]
@lukyth I added Azure pipelines CI yesterday and that passed. In the next few weeks I'll probably switch entirely away from Travis and see if I can pull some strings to get more machines to parallelise PR with lots of dependents like react.

In the meantime, a clean build from Azure is good enough to check in, but of course you'll have to ping me or the maintainer-for-the-week.

**Comment by ferdaber** [comment]
YESS!! thank you @sandersn !!!

**Comment by lukyth** [comment]
Thank you so much! 😄 @sandersn

**Pull request merged**
