### PR TITLE
[redux-mock-store] Fix Store<s> type argument issue

### PR DESCRIPTION
**Pull request by kevcenteno**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/reduxjs/redux/blob/master/index.d.ts#L139>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by kevcenteno** [comment]
@lapski

**Comment by rbuckton** [comment]
@kevcenteno: What exactly is the type argument issue this is intended to solve?

**Comment by kevcenteno** [comment]
@rbuckton the definition prior to my change conflicts with its usage at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c61c8c0323ec3bc9df98e5870ae76c1d3a947541/types/redux-mock-store/index.d.ts#L16

This causes a type error when creating a mock store.

**Comment by rbuckton** [comment]
What is the type error? It seems like `MockStore<S>` should just end up becoming `MockStore<S, Redux.AnyAction>` when the default for `A` is filled in.

**Comment by kevcenteno** [comment]
`Generic type 'Store<S>' requires 1 type argument(s).`

**Comment by rbuckton** [comment]
What versions are you using for redux and each other types package? This seems to be a version mismatch, as https://github.com/reduxjs/redux/blob/master/index.d.ts#L139 specifies two type arguments.

**Comment by rbuckton** [comment]
To clarify, these definitions were modified in #26732 to support redux@4.0, which changed the number of type arguments on `Store`. If you are using a version of redux prior to 4.0, you should pin your version of `@types/redux-mock-store` to `0.0.14`, as that was the last published version of the types package prior to the update.

**Comment by kevcenteno** [comment]
We're using redux@4.0

Here's the usage: 

```
const middlewares = [thunk];
type DispatchExts = ThunkDispatch<any, undefined, AnyAction>;
const mockStoreCreator: MockStoreCreator<any, DispatchExts> = createMockStore<
  any,
  DispatchExts
>(middlewares);
```

**Pull request closed without merging**
