### PR TITLE
hapi__hapi: request payload any

### PR DESCRIPTION
**Pull request by moander**
request payload `any` instead of `stream.Readable | Buffer | string | object`

### CODE REVIEW

**Comment by saboya** [comment]
Is there a reasoning behind this change? Any documentation?

**Comment by moander** [comment]
> Is there a reasoning behind this change? Any documentation?

Payload can be any type. Maybe |any instead of |object is a better alternative?

**Comment by saboya** [comment]
What use case is not covered by the current types? What are you attempting to do?

**Comment by moander** [comment]
> What use case is not covered by the current types? What are you attempting to do?

In typescript i'm getting a compiler error when accessing payload props so because of |object I have to first cast it to any. 

let payload = <any>req.params;
let foo = payload.bar;

instead of

let foo = req.payload.bar;

**Comment by orta** [comment]
I'm gonna nope this PR, I don't think this is the right answer - if you want to add arbitrary properties to the request you can use interface declaration merging.

**Pull request closed without merging**
