### PR TITLE
Add missing server.error in Socket.IO types

### PR DESCRIPTION
**Pull request by murbanowicz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/socketio/socket.io/blob/master/lib/socket.js#L464

### CODE REVIEW

**Comment by KentarouTakeda** [comment]
@murbanowicz 
Thank you for your pull request.

I could not find `error` method in `Server` interface, but found it in `Socket`.
So, your code should be added below.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21f4daf9837ddc03ac8222fa8c2a8d6b1cf123e7/types/socket.io/index.d.ts#L664

```
import sio = require('socket.io');

const server = sio():

// sio.error('server error');
// `TypeError: sio.error is not a function`

server.on('connection', socket => {
  socket.error('socket error');
  // OK: Emit `error` event to client.
});
```

**Comment by murbanowicz** [comment]
You are right! God bless code review :) 
Fixed.

**Review by KentarouTakeda — CHANGES_REQUESTED** [review]
Please see the conversation.

**Review by KentarouTakeda — APPROVED** [review]
Thank you for the fix!!

**Pull request merged**
