### PR TITLE
react: Add `as` attribute to AllHTMLAttributes

### PR DESCRIPTION
**Pull request by kaelig**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This definition was missing in #20628 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20769 

This should not impact https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20812

### CODE REVIEW

**Review by vsiao — CHANGES_REQUESTED** [review]
Couple questions:
- is this a global attribute? Can you link to documentation that explains how this attribute should be used?
- Did you mean to add this to just the v15 typings?
- Can you add a test?

**Comment by kaelig** [comment]
Thank you @vsiao for following up - this PR is here to add what's already in the v16 typing but missing from the v15 one: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1cf7a72cb6be7ccee2647c9aa57218c4abeb490c/types/react/index.d.ts#L2501

Since the v16 one doesn't seem to warrant a test, I didn't add one either. 

Does this answer your questions?

**Comment by RyanCavanaugh** [comment]
@kaelig Please address comments from the code reviewers.

**Comment by kaelig** [comment]
@RyanCavanaugh I believe those were addressed, let me know if additional info is needed

**Pull request merged**
