### PR TITLE
[aws-lambda]: Add missing types for Cognito Custom Messages Trigger

### PR DESCRIPTION
**Pull request by DanielMuller**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
AWS hasn't updated their examples yet (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html#aws-lambda-triggers-custom-message-example).
I retrieved the definitions by logging the received event in Lambda:

```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "abcdefghijkl"
  },
  "triggerSource": "CustomMessage_SignUp",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:email_alias": "me@example.com",
      "email_verified": "false",
      "cognito:user_status": "UNCONFIRMED",
      "phone_number_verified": "false",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

### CODE REVIEW

**Comment by simonbuchan** [comment]
Was this from a "real" request? Eg should users have to handle the chance these properties are null? Breaking changes are OK, if they're revealing a probable bug and aren't proportionally arduous to resolve, I'm just trying to figure if this is like the API gateway "tester" that doesn't send the same payloads as the real API gateway.

**Comment by DanielMuller** [comment]
Yes, the event is a real one. I just changed some of the values for privacy reasons.
I attached a lambda to Cognito's custom message trigger and did a `console.log(event)`

I could get the payload from the logs for other triggerSource if needed.

**Comment by simonbuchan** [comment]
I'm mostly wondering why `usernameParameter` could be `null`: should all the parameters be nullable? Is it due to config changes, or different request situations (sign up vs other triggers, for example), and what's the impact on the code?

AWS docs are infuriatingly sparse on these sorts of details, so having detail we can give the users that get these breaking changes on why they were broken helps.

**Comment by DanielMuller** [comment]
I was able to get almost all of the payloads, except for "UpdateUserAttribute".

My Cognito setup is to use _email_ as _username_, email, phone_number, given_name, family_name are mandatory fields.

_usernameParameter_ only has a value on _AdminCreateUser_, it's the only event for which a user wouldn't know it's username. I guess it's _null_ in other events to avoid that someone could send a username and a code in the same message?

I found this [AWS documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-message-templates.html) regarding messages templates defined in Cognito settings:

> You can't use the {username} placeholder in verification email messages. You can use the {username} placeholder in invitation email messages that you generate with the [AdminCreateUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html) operation. These invitation email messages use two placeholders: the user name, as {username}, and the temporary password, as {####}.

For the _null_ values in _response_, when returned as _null_, the value from the Cognito Settings is used, which would allow to overwrite only email related messages and keep SMS messages as defined in Cognito.

**AdminCreateUser**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "CLIENT_ID_NOT_APPLICABLE"
  },
  "triggerSource": "CustomMessage_AdminCreateUser",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:user_status": "FORCE_CHANGE_PASSWORD",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "cognito:default_val",
      "family_name": "cognito:default_val",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": "{username}"
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

**ForgotPassword**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "65uj4opd096vucqmiivf3v5d1g"
  },
  "triggerSource": "CustomMessage_ForgotPassword",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:email_alias": "me@example.com",
      "cognito:user_status": "CONFIRMED",
      "email_verified": "true",
      "phone_number_verified": "true",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

**Authentication**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "65uj4opd096vucqmiivf3v5d1g"
  },
  "triggerSource": "CustomMessage_Authentication",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:email_alias": "me@example.com",
      "cognito:user_status": "CONFIRMED",
      "email_verified": "true",
      "phone_number_verified": "true",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

**ResendCode**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "65uj4opd096vucqmiivf3v5d1g"
  },
  "triggerSource": "CustomMessage_ResendCode",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:email_alias": "me@example.com",
      "cognito:user_status": "UNCONFIRMED",
      "email_verified": "false",
      "phone_number_verified": "false",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

**SignUp**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "65uj4opd096vucqmiivf3v5d1g"
  },
  "triggerSource": "CustomMessage_SignUp",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:email_alias": "me@example.com",
      "email_verified": "false",
      "cognito:user_status": "UNCONFIRMED",
      "phone_number_verified": "false",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```
**VerifyUserAttribute**:
```json
{
  "version": "1",
  "region": "eu-central-1",
  "userPoolId": "eu-central-1_XXXXX",
  "userName": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
  "callerContext": {
    "awsSdkVersion": "aws-sdk-unknown-unknown",
    "clientId": "65uj4opd096vucqmiivf3v5d1g"
  },
  "triggerSource": "CustomMessage_VerifyUserAttribute",
  "request": {
    "userAttributes": {
      "sub": "AAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEE",
      "cognito:user_status": "CONFIRMED",
      "email_verified": "true",
      "phone_number": "+XXXYYYYYYY",
      "given_name": "John",
      "family_name": "Doe",
      "email": "me@example.com"
    },
    "codeParameter": "{####}",
    "linkParameter": "{##Click Here##}",
    "usernameParameter": null
  },
  "response": {
    "smsMessage": null,
    "emailMessage": null,
    "emailSubject": null
  }
}
```

**Review by simonbuchan — APPROVED** [review]
Wow, thanks for the effort getting all that detail!

Barring tying the trigger to `usernameParameter`, which seems like overkill, this looks bang on.

**Review by jamesorlakin — COMMENTED** [review]
I don't have a strong opinion here, but thanks for the contribution @DanielMuller! Of my occassional run-ins with Cognito I find it can be a bit odd at times.

**Review by jamesorlakin — APPROVED** [review]

**Review by simonbuchan — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by DanielMuller** [comment]
Ready to merge

**Pull request merged**
