### PR TITLE
rollup: improved correctness for strictNullChecks

### PR DESCRIPTION
**Pull request by csvn**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/rollup/rollup/blob/master/src/Bundle.js#L116
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by csvn** [comment]
Just a small fix for correctness in the plugin API when using `strictNullChecks`.

**Comment by csvn** [comment]
Also found that `Plugin` did not lust `null`/`undefined` as valid return values for `transform` & `transformBundle`. I did not find any mentions on wiki/docs, but here are the relevant sections in the code:

* [utils/transform.js#L78](https://github.com/rollup/rollup/blob/master/src/utils/transform.js#L78)
* [utils/transformBundle.js#L12](https://github.com/rollup/rollup/blob/master/src/utils/transformBundle.js#L12)

**Comment by flying-sheep** [comment]
The `?` already mean that it can be undefined, am i right?

if so, only `null` should be added

**Review by flying-sheep — CHANGES_REQUESTED** [review]
The `?` already mean that it can be undefined, am i right?

if so, only `null` should be added

**Comment by csvn** [comment]
Do you mean for `transform` and `transformBundle`?

The `?` in `transform?(...): string | null | undefined | ...` means that the whole method is optional, i.e. both the following are valid:

```typescript
const plugin: Plugin = {
  transform() {
    return 'foo'
  }
}

const plugin2: Plugin = {}
```

The addition of `null | undefined` to these methods is to allow them as return values. Without those typings, the following would error:

```typescript
const plugin: Plugin = {
  transform() {
    return undefined // Type undefined is not assignable to type string | { code: string ... }
  }
  transformBundle() {
    return null // Type nullis not assignable to type string | { code: string ... }
  }
}
```

Returning `null` or `undefined` in these transfoms means that the plugin should let the next plugin (or default behaviour) handle this file. This is not documented clearly for transform functions, but [it is for `resolveId`](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins). Existing plugins rely on this behaviour.

**Comment by flying-sheep** [comment]
Ah, i’m dumb, what you changed is the method return value!

**Review by flying-sheep — APPROVED** [review]

**Comment by csvn** [comment]
@flying-sheep No worries man, confusing things in Typescript happens to all of us 😉

**Pull request merged**
