### PR TITLE
feat(semver): migrate to v7. Fixes #41326

### LINKED ISSUE #41326: [@types/semver] Types have not been updated for version 7 of the package
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @BendingBender @LucianBuzzo @ajafff @ExE-Boss

Version 7 of the package changes the API such that this no longer works:

```
import { coerce } from 'semver';
```

Now you have to do something like this:

```
import { coerce } from 'semver/preload';
import { coerce } from 'semver/functions/coerce';
```

However, when doing either of the latter, TypeScript complains:

```
Could not find a declaration file for module 'semver/preload'.
```

More discussion here: https://github.com/npm/node-semver/issues/306

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- migrate modules to support new v7 usage
- create v6 folder to support older version
- update v7 tests with usage samples from readme while preserving
v6 tests

Thanks!

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/npm/node-semver#usage
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by armanio123** [comment]
Pinging @Bartvds @BendingBender @LucianBuzzo @ajafff @ExE-Boss for review.

**Comment by ExE-Boss** [comment]
I’d&nbsp;prefer if&nbsp;we&nbsp;switched to&nbsp;using the&nbsp;superior&nbsp;tabs for&nbsp;indentation.

**Comment by peterblazejewicz** [comment]
can't, mandated via: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.editorconfig#L8

**Comment by ExE-Boss** [comment]
You&nbsp;can&nbsp;reformat&nbsp;it to&nbsp;use&nbsp;tabs, just&nbsp;like I&nbsp;did&nbsp;in&nbsp;<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40531#discussion_r350507597> with&nbsp;**@⁠types/ejs**.

**Comment by armanio123** [comment]
> You can reformat it to use tabs, just like I did in [#40531 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40531#discussion_r350507597) with **@⁠types/ejs**.

Please don't change the indentation. It's true that we don't specifically enforce it (for now) but the `.editorconfig` @peterblazejewicz points out, should be used as the standard for the repository.

**Comment by peterblazejewicz** [comment]
@armanio123 
Thanks! That's quite easy to do per-project, as the`.editorconfig` is composable. I could amend the readme to point the to the owners (if they really want tabs in the project)

**Comment by armanio123** [comment]
> @armanio123
> Thanks! That's quite easy to do per-project, as the`.editorconfig` is composable. I could amend the readme to point the to the owners (if they really want tabs in the project)

Please don't. I don't believe the matter is about how easy it's to do but rather having a convention for the repository. We should stick with what's defined.

**Review by jetersen — APPROVED** [review]
LGTM

**Comment by elibarzilay** [comment]
@peterblazejewicz, do you want to wait for @casz, or merge it?

**Comment by peterblazejewicz** [comment]
> do you want to wait for @casz, or merge it?
@elibarzilay 
It's already given. Silll amount of changes makes me nervous 🙈

**Comment by elibarzilay** [comment]
> > do you want to wait for @casz, or merge it?
> 
> @elibarzilay
> It's already given. Silll amount of changes makes me nervous

Bah, I meant to ask if you want to wait for @Bartvds or merge it.  (Or wait for anyone else if you're nervous...)

**Comment by casz** [comment]
I am fine with waiting for another reviewer :)

**Comment by elibarzilay** [comment]
@Bartvds @BendingBender @LucianBuzzo @ajafff -- ping?

**Review by weswigham — APPROVED** [review]
Seems fine to me; pretty much just moving everything into subfiles and reexporting them from the root to match the package.

**Pull request merged**
