### PR TITLE
update(svgo): update to 2.6

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- js2svg options added
https://github.com/svg/svgo/releases/tag/v2.6.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by petrzjunior — APPROVED** [review]
LGTM, I don't see why the CI is failing

**Comment by peterblazejewicz** [comment]
> LGTM, I don't see why the CI is failing

Unrelated change in upstream tooling repo broke DT CI, on it already, thx!

**Review by petrzjunior — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💖

**Review by giladgray — APPROVED** [review]
Looks good 👍

**Pull request merged**
