### PR TITLE
bunyan: add writerfn interface to writer stream

### PR DESCRIPTION
**Pull request by tzzh**
It doesn't have to actually implement the nodejs writer interface but can just provide an object with a writer function as shown in https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/examples/raw-stream.js#L12-L20 and https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/lib/bunyan.js#L310
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/examples/raw-stream.js#L12-L20 https://github.com/trentm/node-bunyan/blob/0ff1ae29cc9e028c6c11cd6b60e3b90217b66a10/lib/bunyan.js#L310
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by tzzh** [comment]
also ran `prettier` on the test, hence the big diff

**Comment by elibarzilay** [comment]
@tzzh: I think that it would be better if you undo the prettier changes so the diff is limited to what you did, then reping the owners.

**Comment by tzzh** [comment]
@elibarzilay ok thanks I removed the formatting changes
Not sure who to ping but based on the bot it seems it's you @amikhalev

**Review by amikhalev — APPROVED** [review]
I don't really use bunyan anymore, but this looks fine to me

**Comment by tzzh** [comment]
Ready to merge

**Pull request merged**
