### PR TITLE
Fix module definition for IModule

### PR DESCRIPTION
**Pull request by okamiconcept**
Put the IModule definition in angular module.

### CODE REVIEW

**Comment by adidahiya** [comment]
not sure this is right; can you link to the documentation that suggests this?

**Comment by okamiconcept** [comment]
The IModule.animation() have to be linked to the angular.IModule interface.

https://docs.angularjs.org/guide/animations

As you can see the IModule interface is in the module angular {}, not in angular.animate {}

See here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts

**Comment by adidahiya** [comment]
@okamiconcept ok cool can you please add tests for this change?

**Comment by IvanStoilov** [comment]
The IModule interface is declared in the angular namespace. Isn't `declare namespace angular` more appropriate than `declare module angular`?

**Comment by adidahiya** [comment]
@IvanStoilov well that's an issue with ambient typings across the board -- many have not been updated to use the newer `namespace` syntax. As this file previously used internal modules via the `module` keyword, I think it's ok to keep it that way for now.

**Comment by okamiconcept** [comment]
The commit has not been merged yet?

**Comment by adidahiya** [comment]
@okamiconcept please add tests for this change

**Comment by okamiconcept** [comment]
@adidahiya Sorry i don't know how to add tests for this...

**Comment by adidahiya** [comment]
hmm, I see there are no tests for this file. not really worth adding a new test suite for this small change.

lgtm then :+1:

**Comment by horiuchi** [comment]
@okamiconcept Thanks mate!
@adidahiya @IvanStoilov Thanks for review!

**Pull request merged**
