### PR TITLE
Definitions for angular-ui-router-extras

### PR DESCRIPTION
**Pull request by rraziel**
Type definitions for the UI Router extras library:
- sticky states
- previous state

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-ui-router-extras/angular-ui-router-extras.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-ui-router-extras
  * http://bower.io/search/?q=angular-ui-router-extras
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-ui-router-extras/angular-ui-router-extras-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@mputters thank you for your contribiutions.
please rename angular-ui-router-extras/angular-ui-router-extras-tests.ts to ui-router-extras/ui-router-extras.d.ts

**Comment by mputters** [comment]
My bad, should be better now (squashed the commits and also changed the commit message).

**Comment by vvakame** [comment]
@mputters thanks mate!

**Pull request merged**
