### PR TITLE
fix error for newer sequlize version

### PR DESCRIPTION
**Pull request by MoLow**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by drinchev** [comment]
Hmm, I don't see particular reason for downgrading sequelize to `-2.0`. Do you have any reasoning behind this PR?

**Comment by MoLow** [comment]
Hi. so I understand that `sequelize.d.ts` is a newer version then `sequelize-2.0.0.d.ts`?
becasue when I ran `typings install dt~sequelize --save --global` it installed `sequelize-2.0.0.d.ts`,
which is what led me to this PR.

**Comment by drinchev** [comment]
I can't confirm that. I just tried and it installs the latest. Can you double check inside an empty project?

**Comment by MoLow** [comment]
Well, @drinchev the last release of sequelize, both at [github](https://github.com/sequelize/sequelize/releases) and [npm](https://www.npmjs.com/package/sequelize) is >3.2 ,
and this file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sequelize/sequelize.d.ts is for Sequelize 3.4.1,
So I guess changing `umzug` from `sequelize-2.0.0.d.ts` to `sequelize.d.ts` is an upgragde, not a downgread.

**Comment by drinchev** [comment]
Sorry. Conversation got wrong. Yes it's an upgrade. But as far as I can see you are committing a change to `downgrade` to `-2.0.0.d.ts` ?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13026/files

And I can't understand precisely why.

**Comment by MoLow** [comment]
well, I now ran `ypings install dt~sequelize@3.4.1 --save --global` (added `@3.4.1`) and umzug just worked, so I guess the problem isnt in umzugs files, but the problem is that typings thinks sequelize-2.0.0 is the latest version of sequelize

**Pull request closed without merging**
