### PR TITLE
[@types/aws-lambda] add authorizer to context

### PR DESCRIPTION
**Pull request by brianjd**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by darbio — CHANGES_REQUESTED** [review]
Please add a summary of changes, a link to AWS documentation and some tests and we will reassess.

**Comment by brianjd** [comment]
@darbio

Please see https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html

**Comment by brianjd** [comment]
@darbio As per the AWS documentation:

> You can use the context map to return cached credentials from the authorizer to the backend, using an integration request mapping template. This enables the backend to provide an improved user experience by using the cached credentials to reduce the need to access the secret keys and open the authorization tokens for every request.
> 
> For the Lambda proxy integration, API Gateway passes the context object from a Lambda authorizer directly to the backend Lambda function as part of the input event. You can retrieve the context key-value pairs in the Lambda function by calling $event.requestContext.authorizer.key.

**Comment by simonbuchan** [comment]
That comment doesn't agree with the change you're making, it's talking about a context bring provided in the handler *event* not the lambda context. 

You're looking for one of the interfaces in triggers/api-gateway.d.ts, maybe APIGatewayProxyWithLambdaAuthorizerHandler or related type

**Comment by brianjd** [comment]
@simonbuchan You are correct, my mistake.  Now looking, there is still an error in that type as it it `[name: string]: any;` whereas as per the doc I sent, the values are always stringified.

**Comment by darbio** [comment]
> Now looking, there is still an error in that type as it it [name: string]: any; whereas as per the doc I sent, the values are always stringified.

The types correctly model the library in that they can be set as any primitive type, but when they are provided by lambda, they are stringified.

I'm all for narrowing the types to fix them/more closely model the output from lambda, however I don't believe this is the correct thing to do here.

**Comment by darbio** [comment]
@brianjd I went down the rabbit hole with this one to check and the types are correct, in that it is possible that the context can contain anything, not only just a string (as per the AWS documentation).

The documentation is also correct, in that any contexts that you add will be stringified.

Here is the example:

```
import { APIGatewayAuthorizerHandler, APIGatewayAuthorizerResult, APIGatewayProxyHandler } from "aws-lambda";

export const authorizer: APIGatewayAuthorizerHandler = async () => {
  const result: APIGatewayAuthorizerResult = {
    "principalId": "my-username",
    "policyDocument": {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "execute-api:*",
          "Effect": "Allow",
          "Resource": "arn:aws:execute-api:us-east-1:008281161880:1lz9h1uurk/*/GET/"
        }
      ]
    },
    "context": {
      "str": "hello",
      "num": 123,
      "bool": true,
      "null": null,
      "undefined": undefined
    }
  };

  return result;
};

export const handler: APIGatewayProxyHandler = async (event, context) => {
  return {
    statusCode: 200,
    body: JSON.stringify(event.requestContext.authorizer),
  };
};
```

Result:

```
{
    "str": "hello",
    "bool": "true",
    "null": null,
    "num": "123",
    "principalId": "my-username",
    "integrationLatency": 0
}
```

You will see that:

- number is stringified
- boolean is stringified
- undefined is undefined (removed)
- null is null (not "null")
- there is an extra property of number type called `integrationLatency`

The types state:

```
// Default authorizer type, prefer using a specific type with the "...WithAuthorizer..." variant types.
// **Note that this doesn't have to be a context from a custom lambda authorizer**, AWS also has a cognito
// authorizer type and **could add more, so the property won't always be a string.**
export type APIGatewayEventDefaultAuthorizerContext =
    | undefined
    | null
    | {
        [name: string]: any;
    };
```

Given it is possible that AWS will add _anything_ to the context, we cannot narrow the types to `string`.

**Pull request closed without merging**
