### PR TITLE
[node] Update with changes from v14.6.0

### PR DESCRIPTION
**Pull request by addaleax**
Refs: https://github.com/nodejs/node/pull/34371

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: nodejs/node#34371
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by ExE-Boss — APPROVED** [review]

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Does this include changes from .5 etc?
Also missing minor version bumb in index.d.ts

**Comment by addaleax** [comment]
@simonschick No, I only specifically looked at the 14.6.0 release. I’ve bumped the version number here, though.

**Review by nguymin4 — APPROVED** [review]

**Comment by SimonSchick** [comment]
@addaleax can you please file an issue to apply changes from .1 to .5?
People could be lead to believe that .6 contains all of those changes.

**Comment by addaleax** [comment]
Hm yeah… I can probably just update this to actually incorporate those changes later, that might be the easiest way

**Comment by addaleax** [comment]
@simonschick I’m not sure I’ll have time for finishing that task up this week.

So can you pick either one of your review comments? You’ve asked me to bump the version, and subsequently asked me to bump the code so that it matches that version; that basically leaves me with no option but a massive scope creep for this PR. I don’t think that’s a helpful review process, and I would appreciate it if you were to pick one (update the version or not, but not expect me to do a ton of extra work).

**Comment by addaleax** [comment]
Can somebody merge this / weigh in on @simonschick’s comments?

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
@addaleax If I understand [bot ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46244#issuecomment-662655441) correct you just have to comment with `Ready to merge` and bot will merge this.

**Review by galkin — APPROVED** [review]

**Comment by addaleax** [comment]
Ready to merge

**Pull request merged**
