### PR TITLE
IActionDescription and ICurrentRoute members update.

### PR DESCRIPTION
**Pull request by bogh**

### CODE REVIEW

**Comment by vvakame** [comment]
*angularjs/angular-resource.d.ts*

to authors(@diegovilar @miffels). could you review this PR?

check list

* [ ] pass the Travic-CI test?

---

*angularjs/angular-route.d.ts*

to author(@park9140). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by miffels** [comment]
Hi @Bogh,

Thank you for contributing! Before we can merge your PR, could you elaborate on the changes, please? The ``$$route`` parameter of ``$route: ICurrentRoute`` looks an awful lot like a private property that should not go into the published API, and is [not documented](https://docs.angularjs.org/api/ngRoute/service/$route).

I haven't dug around in this portion of the API lately, so I would be very grateful if you could complete these items:

- [ ] Verify ``$$route`` is meant to be exposed
- [ ] Link to documentation (or angular-resource source) for the remaining changes
- [ ] Add/adjust tests to include the new ``IResourceServiceProvider`` interface (see the [Contribution guide](http://definitelytyped.org/guides/contributing.html#tests))

Thanks,
Michael

**Comment by miffels** [comment]
Dunno why it's closed, but it looks fine to me :+1: 

Cheers,
Michael

**Comment by Bogh** [comment]
I closed because I opened another more complete pull request. I'm quite new
to this. Dunno how all github api works.

**Comment by diegovilar** [comment]
Guys, careful when removing things from the interfaces. Indeed I exposed a lot of angular internals back when I first made this definition file, mainly because at the time angular docs were not very good and frequently failed to document properties correctly, so I opted to define interfaces based both on docs and actual implementation.

Anyways... years have passed and a lot of code depends on these definitions now, for better or worse. Consider depreciating interface members through documentation for a period of time before completely removing them. Some advanced libraries do tap on such internals now because I exposed them at the time. Allow them a grace period.

PS: I'm not talking specifically about $$route, but in a general sense.

**Comment by miffels** [comment]
Hi Diego,

It is good to see that you have an eye on things, too, and I could not 
agree more. I wonder why you would need to point this out, though? It is 
a very basic principle of library design, and the changes in the past 
year were nowhere near that.

Cheers,
Michael

**Pull request closed without merging**
