### PR TITLE
Protractor/Selenium: allow to use numbers with sendKeys()

### PR DESCRIPTION
**Pull request by tkrotoff**
Selenium officially accepts numbers for `sendKeys()`, see https://github.com/SeleniumHQ/selenium/issues/2211

### CODE REVIEW

**Comment by Kuniwak** [comment]
LGTM :+1:

**Comment by cnishina** [comment]
Are we still supporting protractor typings in master? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12482

**Comment by sandersn** [comment]
@tkrotoff can you target types-2.0 instead, and remove the protractor changes?

**Comment by paulvanbrenk** [comment]
This PR seems abandoned, please re-open when you made the requested changes.

**Pull request closed without merging**
