### PR TITLE
Fix several typings in ProseMirror

### PR DESCRIPTION
**Pull request by ocavue**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
 
If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (see below)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

- `DirectEditorProps`: https://github.com/ProseMirror/prosemirror-view/blob/1.23.12/src/index.js#L644-L668
- `EditorState.create`: https://github.com/ProseMirror/prosemirror-state/blob/1.3.4/src/state.js#L164-L182
- `NodeSpec.defining`: https://github.com/ProseMirror/prosemirror-model/blob/b8c5166e9ac5c5cf87da3f13012b0044fd8a4bd9/src/schema.js#L379-L393
- `Transform.replaceRange`: https://github.com/ProseMirror/prosemirror-transform/blob/7f6622d93ca99dad10b99ee1036a640b9b221a92/src/replace.js#L342-L358

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## prosemirror-transform ([<kbd>unpkg</kbd>](https://unpkg.com/browse/prosemirror-transform@latest/))
was missing the following properties:
1. TransformError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8aadddb02bcf3f79ec36b3fc6580aa316183f4a4
</p>

**Comment by cmlenz** [comment]
@ocavue this appears to have made the `plugins` field on `DirectEditorProps` required, but it doesn't seem to really be required by ProseMirror, you can create a new editor view without passing plugins with no problem:

```ts
new EditorView(elem, {state});
```

This is probably also a common case, as you can only pass stateless plugins that way, if I understand the document correctly: https://prosemirror.net/docs/ref/#view.DirectEditorProps.plugins

**Comment by ocavue** [comment]
@cmlenz I will submit a PR to `@types/prosemirror-view` once the document is clarified that the `plugins` field is optional. In the mean time, you can use `// @ts-ignore`, `// @ts-expect-error`, or just add `plugins: []` to avoid this error.

**Comment by cmlenz** [comment]
@ocavue awesome, thx

**Pull request merged**
