### PR TITLE
[resemblejs] Update to 4.1.0

### PR DESCRIPTION
**Pull request by GreenYun**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/rsmbl/Resemble.js/commit/17ed085ab81784b971b6bcbdca98fb656cc99b54 https://github.com/rsmbl/Resemble.js/blob/master/compareImages.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by pimterry** [comment]
I know I'm in here as the owner, but it's a big change, and I haven't used this lib in many years, so I'm not well placed to reviewed it I'm afraid. I'd be happy to be removed as a owner to be honest! 

I'm going to leave this here for a DT maintainer to review (it should be bumped into maintainer review automatically in a week or two I think).

**Review by Grayson-code — APPROVED** [review]

**Comment by Grayson-code** [comment]
there seems to be no mistakes with first look

**Review by Grayson-code — CHANGES_REQUESTED** [review]
Well if @pimterry wants to be removed as contributor you can commit with removing him contributor after asking him/

**Comment by Grayson-code** [comment]
@pimterry if this is good , we can ask dt maintainers to review this

**Comment by pimterry** [comment]
> @pimterry if this is good , we can ask dt maintainers to review this

:+1: Yes, thanks, looks good to me

**Review by Grayson-code — APPROVED** [review]

**Comment by GreenYun** [comment]
Ready to merge

**Pull request merged**
