### PR TITLE
update to api@0.5.0

### PR DESCRIPTION
**Pull request by TsumiNa**
update to api@0.5.0 and add the offical tutorial code

### CODE REVIEW

**Comment by vvakame** [comment]
@DanielRosenwasser can I merge this PR?

**Comment by TsumiNa** [comment]
@DanielRosenwasser yes please :)

**Comment by DanielRosenwasser** [comment]
After speaking with @mhegazy, I'm not sure whether having this .d.ts here makes sense anymore, given than TypeScript 1.6 will do the "correct" node module resolution and find the supplied .d.ts files in `node_modules/typescript`.

What makes a little more sense is if you are writing a non-CommonJS app, in which case you might want to use our `built\local\typescript_standalone.d.ts`.

**Comment by TsumiNa** [comment]
@DanielRosenwasser I think ide will need this. If you make typescript project ignore the node_modules folder in tsconfig.json.

Btw, I want keep all my d.ts files managed by the tsd. :)

Of course, if no need now, close this.  :)

**Comment by vvakame** [comment]
tsc is not support for node_modules resolution for amd/umd.
I think this repository should maintain hosting .d.ts files.

**Comment by TsumiNa** [comment]
Maybe you are right. I will think about it :+1:

**Comment by mhegazy** [comment]
i have created a PR for updating the typings at https://github.com/borisyankov/DefinitelyTyped/pull/6213. @vvakame if you do not think there is value in having these typings updated, feel free to close it.

**Pull request closed without merging**
