### PR TITLE
[angular-ui-bootstrap] Export module name

### PR DESCRIPTION
**Pull request by Igorbek**
This PR adds exports of the module name `'ui.bootstrap'` from the module. It started to do it from version 1.0.0, so the version is upgraded as well.

Also, `exports = ` does not work with any other exports, so other exports are removed, which is ok because types are available through `ng.ui.bootstrap`. And this is ok since the version is major.

### CODE REVIEW

**Comment by Igorbek** [comment]
It might be fixing #14630, partially #8394 and supersedes #32341

**Comment by tomyam1** [comment]
Hey @Igorbek 
May I ask why did you remove all the type aliases?

Before we could do
```typescript
import { IModalInstanceService, IModalScope, IModalSettings } from 'angular-ui-bootstrap'
```

Now we have to do something like:
```typescript
import IModalInstanceService = angular.ui.bootstrap.IModalInstanceService 
import IModalScope = angular.ui.bootstrap.IModalScope 
import IModalSettings = angular.ui.bootstrap.IModalSettings 
```
Or maybe there is another solution?

**Comment by Igorbek** [comment]
Hey @tomyam1 thank you for bringing a question.

So the package starting from 1.0.0 uses commonjs export `module.exports = ` (see https://github.com/angular-ui/bootstrap/blob/1.0.0/index.js)

This means the only way to import it is to write:

```ts
import * as uibootstrap from 'angular-ui-bootstrap';
// this also works with --syntheticDefaultModules
import uibootstrap from 'angular-ui-bootstrap';
```

Named imports (`import { ... } from `) are not correct in this context.
For that reason, TypeScript explicitly restricted to have both `export = ` and other named exports, including types.

Other type packages for angular (for example see type definitions in `@types/angular-route` or `@types/angular-sanitize`) also used this approach.

This was a breaking change, definitely, but the workaround is to use types in `angular.ui.bootstrap`.
For that reason, I bumped to a major version change.

BTW, there's a trick to define a default export along with types. `@types/angular-ui-router` (deprecated) used this approach. But it only works if TS has synthetic modules enebled, otherwise the statement is not correct from runtime perspective.

Also, the fix would be to ask authours of `angular-ui-library` to create a new version with default exports (proper es modules).

**Comment by Igorbek** [comment]
Also, before the change I made a _bit ts query_ to see how many users of these types:
https://bigtsquery.firebaseapp.com/query?selector=ImportDeclaration:has(StringLiteral%5Bvalue%3D%27angular-ui-bootstrap%27%5D)%20ImportSpecifier:nth-child(1)

It seems it is used in a few projects for type imports, so the scope is quite limited.
I understand the inconvenience, sorry but I think it is the right thing to do.

**Comment by tomyam1** [comment]
Thanks @Igorbek for the explanation.

**Pull request merged**
