### PR TITLE
Add new useUniqueDomain option to doubleclick-gpt

### PR DESCRIPTION
**Pull request by btippett**
Google recently added a new option, useUniqueDomain, to the SafeFrameConfig interface.
https://developers.google.com/publisher-tag/reference#boolean-useuniquedomain

Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by krishnaglick** [comment]
1. useUniqueDomain looks to accept null, which your types do not allow. Only undefined.
2. Should this new functionality default to true? What was google doing before?

**Comment by btippett** [comment]
@krishnaglick, good catch on allowing null. I missed that in the property description. Re, the default, https://support.google.com/admanager/answer/9999596 has the rationale for adding this new property. Previously, there was no way to set this behavior using the GPT library. It was only configurable at the account level. The new default, as of 10/26/2020 is to set this to true.

**Comment by krishnaglick** [comment]
Well, it's just the test that's set to true so no problem.

**Review by krishnaglick — APPROVED** [review]

**Comment by btippett** [comment]
Ready to merge

**Pull request merged**
