### PR TITLE
redux 4.x support.

### PR DESCRIPTION
**Pull request by daliusd**
Redux 4.x requires different Reducers syntax.

### CODE REVIEW

**Comment by huy-nguyen** [comment]
What problem are you trying to solve with this PR?

**Comment by daliusd** [comment]
@huy-nguyen redux 4.x support. Without these changes we have problem with redux 4.x.

**Comment by daliusd** [comment]
@huy-nguyen Do you have any idea why nothing happens with this fast-tracked pull request?

**Comment by huy-nguyen** [comment]
I think you should ping one of the maintainers.

**Pull request merged**
