### PR TITLE
[daterangepicker] Fixed minYear/maxYear properties for DateRangePicker

### PR DESCRIPTION
**Pull request by WiseBird**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L45
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by nertzy** [comment]
I see that the default value for those fields is a string.

But, it also seems like they can be assigned as a number, from the following: https://github.com/dangrossman/daterangepicker/blob/8495717c4007a03fd5dee422f161811fd6140c0e/daterangepicker.js#L236-L241

Would it be better to use `string | number` here?

**Comment by SirMartin** [comment]
It is a year, so probably a number is the most exactly and it is supported.

**Comment by Semigradsky** [comment]
http://www.daterangepicker.com/#options

There are numbers in the documentation.

**Review by nertzy — CHANGES_REQUESTED** [review]
Looks like the value for `minYear` and `maxYear` can be either a string or a number.

So we should use `string | number` here instead.

**Comment by WiseBird** [comment]
@nertzy Done

**Review by SirMartin — APPROVED** [review]

**Review by nertzy — APPROVED** [review]

**Review by SirMartin — APPROVED** [review]

**Comment by nertzy** [comment]
I think it would usually get automatically merged once approved. I'm not sure who to ping to have this looked at...

**Review by sandersn — APPROVED** [review]

**Pull request merged**
