### PR TITLE
vhtml: Move JSX from global namespace to vhtml.JSX

### PR DESCRIPTION
**Pull request by pastelmind**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

----

Instead of injecting the `JSX` namespace as a global symbol, move it under a new namespace named `vhtml`.
This `vhtml` namespace is merged with the `vhtml()` function. Library consumers can access it as `.JSX`:

```ts
import h from "vhtml";
type A = h.JSX.Element;
```

The `JSX` namespace can also be imported directly:

```ts
import h, {JSX} from "vhtml";
type A = JSX.Element;
```

Note that this is a **BREAKING CHANGE**, as you _must_ import `JSX` or use `h.JSX`. I apologize to anyone using `@types/vhtml` for this.

This should allow vhtml-powered JSX code to be used together with other JSX-based libraries, such as React. It _should_ solve the issue: https://github.com/developit/vhtml/issues/19#issuecomment-734971419

Background: TypeScript 2.8 supports [locally scoping the `JSX` namespace](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#locally-scoped-jsx-namespaces) ([see PR for this feature](https://github.com/microsoft/TypeScript/pull/22207)). This allows a package to use multiple libraries that expose different variations of the `JSX` namespace without conflicts.

Note: This does not allow consumers to use two different JSX libraries together in a single module. No transpiler that I know of supports this use case.

### CODE REVIEW

**Comment by pastelmind** [comment]
All CI builds have been failing today, see #51835. The PR passes `npm test` on my PC.

@ThaNarie and @AndrewLeedham could you please review this PR? It _should_ cover the use case mentioned at https://github.com/developit/vhtml/issues/19#issuecomment-734971419 and https://github.com/developit/vhtml/issues/19#issuecomment-750914692.

**Comment by ThaNarie** [comment]
@pastelmind Unfortunately I cannot easily test this as I've abandoned the JSX route in my current project in favour of `htm`. 

But based on the PR description and the code changes, all seems solid.

**Review by AndrewLeedham — APPROVED** [review]
I have also gone a different route away from `vhtml`. But agree the changes look good 👍

**Comment by sandersn** [comment]
A change in the TS nightly makes DT parsing run out of memory. I pinned Typescript to a version before the change while I investigate.

**Comment by pastelmind** [comment]
(Nothing has really changed since d491a62c8779b98b25ac8daa01a5960309ea1e69, I just force-pushed the commmit to trigger a C)I

**Review by AndrewLeedham — APPROVED** [review]

**Comment by pastelmind** [comment]
Ready to merge

**Pull request merged**
