### PR TITLE
@types/prosemirror-markdown: Add missing type definitions and fix incorrect definition for "render"

### PR DESCRIPTION
**Pull request by marcusellis05**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by marcusellis05** [comment]
I don't have any documentation that I'm able to share publicly. But in working with the "prosemirror-markdown" package and these types, I found that the type definitions were somewhat incomplete and, in the case of the `render` method, inaccurate. This PR fixes those issues.

I saw that there was a test file. I wasn't quite sure how to add to those tests to provide coverage for these changes. I'm open to adding tests, if someone can provide a little bit of guidance.

I'm hoping we can get this reviewed and a new version published fairly quickly as I need these types for a project I'm actively working on.

Thanks.

**Comment by marcusellis05** [comment]
I believe I've added tests that successfully cover my changes. Please let me know if further tests or changes are needed. Thanks.

**Review by timjb — CHANGES_REQUESTED** [review]
The aim of these type definitions is to describe the public API of prosemirror-markdown. The public API consists of what is documented in [prosemirror-markdown's README](https://github.com/ProseMirror/prosemirror-markdown/blob/master/README.md) which is generated from source code comments using [builddocs](https://github.com/marijnh/builddocs).

If you believe that the documentation above is incorrect or that some currently internal functions/parameters should be declared part of the public API, please discuss that with @marijnh.

I will not approve this PR until the type definitions only describe the public API.

If you need a workaround for a project of yours you can use TypeScript's declaration merging feature to augment the types locally.

**Comment by marcusellis05** [comment]
@timjb that makes sense. 

FWIW, it looks like the signature for `render` was [changed over 5 years ago](https://github.com/ProseMirror/prosemirror-markdown/commit/ff8b640fcb1a08577df9dc4112d9d80099e208d3) and the comment just never got updated to match. I'll raise a PR against the prosemirror-markdown repo to update it, and also ask about marking those other methods as public by adding comments to those.

**Pull request closed without merging**
