### PR TITLE
update(mousetrap): optional extensions

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- extensions.global
- extensions.pause

usage:
```ts
/// <reference types="mousetrap/extensions/global" />
```
or:
```ts
import "mousetrap/extensions/global";
```
or add path to extension in `tsconfig`.

Thanks!

/cc @maiha2 @nicbarker 

ref: #52122 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by nicbarker** [comment]
👀

**Comment by nicbarker** [comment]
This looks great! Awesome work. Tested it locally and it appears to work well.
cc @tstirrat this PR moves mousetrap "extension" definitions out of the main mousetrap definitions, as they are not included by default in the mousetrap NPM package.

**Review by nicbarker — APPROVED** [review]

**Comment by maiha2** [comment]
@peterblazejewicz Thanks!!

**Comment by peterblazejewicz** [comment]
cool, I'll make this proper PR, but folks, please first try this yourself. If that's OK, let go. If you receive complaints (oh, programming is an art of making choices), we can revert this change, just wanted to hint a way to push forward your extensions model withuot hampering the main package. thx!

**Comment by amcasey** [comment]
Re-opening to re-trigger CI

**Comment by amcasey** [comment]
The failure is an infrastructure bug and not a problem with this PR, which looks good.  I'm going to run it one more time to see if we've managed to fix it.

**Review by amcasey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
