### PR TITLE
Added type definitions for `markdown-navbar`

### PR DESCRIPTION
**Pull request by drpsyko101**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@drpsyko101 why you opted for functional component like interface? This seems to be regular component:
https://github.com/parksben/markdown-navbar/blob/master/src/index.js#L5

**Comment by drpsyko101** [comment]
@peterblazejewicz Sorry, I didn't know the best way to approach type definition for functional component in react. There are so many ways I've read for typings and I happen to pick that method. I'll read up some more and will edit it back later. Thanks for the heads up.

**Comment by peterblazejewicz** [comment]
@drpsyko101 where are we with this? Everything is OK, just added a question abut what is really the export that users are supposed to consumer (class or function based components)

**Comment by drpsyko101** [comment]
@peterblazejewicz Sorry for the very late reply. It is a simple functional component that takes in markdown string and output them in JSX.Element. I should change the input to type instead of interface to make things clearer.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by drpsyko101** [comment]
Ready to merge

**Pull request merged**
