### PR TITLE
Mark dojo types as not needed, refer to official page

### PR DESCRIPTION
**Pull request by weswigham**
Following comments in #20264, it is likely pertinent to mark the dojo `@types` package as not needed - there are much more actively maintained types elsewhere.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Is this actually appropriate? My understanding is that Dojo was using the infrastructure here to provide types for older versions of Dojo. @kitsonk

**Comment by kitsonk** [comment]
@DanielRosenwasser we do maintain [dojo/typings](https://github.com/dojo/typings/) for older versions of Dojo and it is available under `npm install dojo-typings`.  We started it before `@types` was a thing and it was challenging to deal with such large packages of types.  We probably need to look again at what we need to move it to @types but managing in DefinitelyTyped is likely not going to work for us.

**Comment by weswigham** [comment]
@kitsonk The `dojo` types here on DT right now are unfortunately very old - there have been two PRs in the last 7 months (no easy to get history from before that, as it was moved into the folder it is currently in), while `dojo/typings` repo has received at least 12 PRs in that time. Unfortunately, this is what users get by default from their editor if they've just run `npm install dojo`...

**Comment by kitsonk** [comment]
@weswigham I might not have been explicit enough. I 👍 this PR and admonish myself for not engaging with the @types org to get our types published through that org.

**Comment by andy-ms** [comment]
`dojo` doesn't actually provide its own types, so shouldn't be in `notNeededPackages.json`.
Generally our policy for non-maintained packages has been to just leave them. Probably half of the packages on here are not actively maintained.

**Comment by RyanCavanaugh** [comment]
@weswigham Please address the merge conflict.

**Comment by weswigham** [comment]
@RyanCavanaugh Do you want to merge this, or was that just a run of dt-bot on your account?

**Comment by minestarks** [comment]
@weswigham Please address the merge conflict.

**Comment by minestarks** [comment]
@weswigham last call to resolve merge conflict please before I close this.

**Comment by weswigham** [comment]
I've gotten mixed signals on weather removing these types is correct, and it's probably better to stay on the side of keeping them, for now.

**Pull request closed without merging**
