### PR TITLE
ClassNames: allow strings and numbers for class dictionaries

### PR DESCRIPTION
**Pull request by bakesteve**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate. < no version number in the header

### CODE REVIEW

**Comment by adidahiya** [comment]
@bakesteve why do you want to make this change?

**Comment by paulvanbrenk** [comment]
Please link to the docs or original source.

**Comment by andy-ms** [comment]
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

**Comment by bakesteve** [comment]
@adidahiya without it the following fails: 
```
import * as classNames from 'classnames';

const inputClasses = classNames({
     'height': '48px',
      'width': '48px'
    });
```

@andy-ms sure thing, I'll rebase

**Comment by adidahiya** [comment]
@bakesteve that is not the intended use of `classnames`. I see no good reason to allow that, despite it being valid JS.

**Comment by RyanCavanaugh** [comment]
Agree with @adidahiya

**Pull request closed without merging**
