### PR TITLE
[p5] Add a second parameter to the round method

### PR DESCRIPTION
**Pull request by martin-badin**
Discussion: #57457

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/processing/p5.js/blob/main/src/math/calculation.js#L693>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by nhverstr** [comment]
Great, thank you!

**Comment by martin-badin** [comment]
@peterblazejewicz could you please review?

**Comment by peterblazejewicz** [comment]
@martin-badin 
```ts
// This file was auto-generated. Please do not edit it.
```
can we review how this content is created? there is no reason to update artefact file, thx!

**Comment by martin-badin** [comment]
@peterblazejewicz I didn't notice the comment but I think we can go ahead with this change. I found a lot of PR with small changes. I found the first PR as well but I don't know how the file is generated nevertheless.

https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+p5+is%3Aclosed

**Comment by peterblazejewicz** [comment]
@martin-badin can we remove this comment? as part of  this PR? I understand there was an effort in the past to put p5 into DT/TypeScript ecosystem and is now effectively no longer maintained:
https://github.com/p5-types/p5.ts

**Comment by martin-badin** [comment]
@peterblazejewicz done

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
to keep this progressing, PR removes 'autogenerated' header warning, which is OK
@martin-badin thx!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
