### PR TITLE
webpack-env: Added feature for use EnviromentPlugin

### PR DESCRIPTION
**Pull request by jfernandeze**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by use-strict** [comment]
Please check if this works in tandem with `node.d.ts`. I'm unsure that declaration merging would work like this. I'm thinking the definition should probably be more like:
```
namespace NodeJS {
    interface Process extends __WebpackModuleApi.NodeProcess {}
}
declare var process: NodeJS.Process;
```

**Review by use-strict — CHANGES_REQUESTED** [review]
Please see my previous comment. You need to use NodeJS.Process, otherwise you'll get duplicate declaration error, when used in conjunction with `@types/node`:
```
node_modules/@types/node/index.d.ts(52,13): error TS2403: Subsequent variable declarations must have the same type.  Variabl
e 'process' must be of type 'Process', but here has type 'Process'.
```

**Comment by jfernandeze** [comment]
How could I check this error? Currently if I use `npm test` I haven't this duplicate...

**Comment by use-strict** [comment]
Perhaps the tests should be updated to check for this case as well. Meanwhile, you can do:
```
npm install @types/node
npm test
```

**Comment by jfernandeze** [comment]
I'm trying install @types/node and npm test but i can't achieve this error... wich kind of project are you use for this issue? 

I'm looking for other test but if you add ``/// <reference path="../node/node.d.ts" />`` in the test file or `/// <reference types="node" />` like the type convert-hrtime-test.ts but i can not get the error

My project is in angular with webpack 2

**Comment by use-strict** [comment]
@jfernandeze , I checked out your fork, but I'm unable to run the tests at all. I'm getting this error `Error: angular-animate depends on angular but has a lower required TypeScript version.`.

Nonetheless, I added `/// <reference types="node" />` in `webpack-env-tests.ts`. Looking on VSCode in `node/index.d.ts`, you can see the error at line 74.

**Comment by jfernandeze** [comment]
Is true that my fork is bad... so I've deleted my fork and I've created a new fork... Please check now my fork in the master branch... if you put `/// <reference types="node" />` in the webpack-env-tests-ts the test is passed.

**Comment by use-strict** [comment]
I'll be out of the country for the next days and have no computer access. To sum things up, I think the safest bet is to write the definition like this:
```typescript
namespace NodeJS {
    interface Process extends __WebpackModuleApi.NodeProcess {}
}
declare var process: NodeJS.Process;
```

I don't know why the errors don't show for you or why the tests pass. You can also try to create an empty repo, run `npm install typescript @types/node`, copy your modified `webpack-env/index.d.ts` file to the project. My sample `tsconfig.json` looks like this:
```json
{
    "compilerOptions": {
        "strict": true,
        "module": "commonjs",
        "target": "es6"
    }
}
```
and a simple `test.ts`, just to have something in the project:
```typescript
let x = process.env.NODE_TEST;
console.log(x);
```

```
$ ./node_modules/.bin/tsc
node_modules/@types/node/index.d.ts(52,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'process' must be of type 'Proc
ess', but here has type 'Process'.
```

**Comment by jfernandeze** [comment]
Hello! @use-strict 

I'm going to put you my steps:

`mkdir test & cd test `

`npm install typescript @types/node`

I've created the file **test.ts** and this is the code inside:

`let x = process.env.NODE_TEST;
console.log(x);`

If you execute `tsc test.ts` all is ok... so then i've executed:

`npm install @types/webpack-env`

then if you execute 'tsc test.ts' all is ok! ... so if you change the file /node_modules/@types/webpack-env/index.d.ts and add the lines:

[index.d.ts.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1526979/index.d.ts.zip)

If you executed 'tsc test.ts' you have next error:

`'node_modules/@types/webpack-env/index.d.ts(244,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.'`

but if you add declare in the code:

[index.d.ts.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1526983/index.d.ts.zip)

All is ok.... and this is my tsconfig file...

[tsconfig.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1526989/tsconfig.zip)

My version of typescript is 2.6.2

**Comment by use-strict** [comment]
Yes, forgot the `declare`. As long as you use the NodeJS namespace, it should be OK. Just need to update the PR.

**Pull request closed without merging**
