### PR TITLE
[karma-chai] Create definitions

### PR DESCRIPTION
**Pull request by hexpunk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by andy-ms** [comment]
So, this package just exposes a few things from `chai` as globals? I was going to suggest just using `@types/chai`, but it looks like that only exposes a single `chai` global.

**Comment by JayAndCatchFire** [comment]
That's correct. It's similar to the karma-chai-sinon types, but without
sinon. I figured it was worth it as karma-chai is used much more than
karma-chai-sinon. And why add packages you're never going to use?

**Comment by andy-ms** [comment]
Makes sense. Thanks!

**Comment by JayAndCatchFire** [comment]
This is my first time contributing to DefinitelyTyped.  How long before I see this package on npm?

**Pull request merged**
