### PR TITLE
webpack: Loader API

### PR DESCRIPTION
**Pull request by shlomiassaf**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://webpack.js.org/api/loaders/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by shlomiassaf** [comment]
@mohsen1 I did not include the literal string change for `devtool`, it will break to many configurations and it has different values that changes along the way

**Comment by mohsen1** [comment]
you can union it with string type to make it work for autocomplete at least.

**Comment by mhegazy** [comment]
@shlomiassaf can you refresh this PR?

**Comment by shlomiassaf** [comment]
@mhegazy I rebased the PR.

I can't run the tests, for some reason I get this:
```
SHLASSAF-M-4099:DefinitelyTyped shlomiassaf$ npm run test

> definitely-typed@0.0.1 test /Users/shlomiassaf/Desktop/Cisco/forks/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed --nProcesses 1

Clean data
Clean logs
Clean output
# Typing Publish Report Summary
Started at Wed, 18 Jan 2017 20:15:31 GMT
Found 2840 typings folders in /Users/shlomiassaf/Desktop/Cisco/forks/DefinitelyTyped
Error: In /Users/shlomiassaf/Desktop/Cisco/forks/DefinitelyTyped/graphql, index.d.ts references type.d.ts, which does not exist.
    at /Users/shlomiassaf/Desktop/Cisco/forks/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:133:10
    at throw (native)
    at rejected (/Users/shlomiassaf/Desktop/Cisco/forks/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:5:65)

```

Not related to my PR so I don't know what to do with it...

**Pull request merged**
