### PR TITLE
Hapi ref types

### PR DESCRIPTION
**Pull request by damusix**
Request query, payload, headers, params and auth are untyped. Added type
implementation for server.rules and routeOptions.rules.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <[<url here>](https://github.com/southpointe/temp-hapi-types)>

### CODE REVIEW

**Comment by lenovouser** [comment]
@SimonSchick I took a brief look and it looks fine to me, but maybe it's better if a 2nd person takes one as well.

**Review by SimonSchick — APPROVED** [review]
This seems fine, some of those generics seem potentially very computionally expensive, can you double check that this doesn't inflate build times with hapi heavy projects?

**Comment by lenovouser** [comment]
@SimonSchick I tried on all repositories I have available, and it seems fine, but I am not sure if I would consider these "hapi-heavy". They are all mostly comparable to standard micro-services.

**Review by lenovouser — APPROVED** [review]

**Review by lenovouser — APPROVED** [review]

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Review by lenovouser — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by lenovouser** [comment]
Ready to merge

**Comment by damusix** [comment]
Ready to merge

**Pull request merged**
