### PR TITLE
[parse/node] Add missing types for encrypting users

### PR DESCRIPTION
**Pull request by JeromeDeLeon**
@dplewis

This is my first time doing PR for this repo. If I did something wrong, please let me know.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
[](url)

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[enableEncryptedUser](https://github.com/parse-community/Parse-SDK-JS/blob/0dc0ee59e2efe3bd4b917936551979171c4551f0/src/Parse.js#L294)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by JeromeDeLeon** [comment]
I could but I don't know where to start.

**Comment by dplewis** [comment]
You can read about linting [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#verifying)

You can add your function [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parse/parse-tests.ts)

It doesn't actually run against parse, just a typescript linter to make sure your typescript types are correct.

**Comment by JeromeDeLeon** [comment]
@dplewis Done!

**Comment by dplewis** [comment]
Normally you shouldn't change anything in the files that don't relate to your PR. Can you revert and only add your changes so that other reviewers can see. Also can you add your name at the top of the file index.d.ts so that you can get notified from DefinatelyTyped.

**Comment by JeromeDeLeon** [comment]
Yeah that's the problem I'm currently solving. Sorry.

**Comment by JeromeDeLeon** [comment]
@dplewis I finally managed to make it work as you suggested. Sorry for changing too much. It just so happened because of prettier. Let me know if you have any suggestions. Thanks.

**Review by dplewis — APPROVED** [review]
LGTM!

**Pull request merged**
