### PR TITLE
[react-native] Adds imageStyle prop to ImageBackground

### PR DESCRIPTION
**Pull request by iRoachie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageBackground.js#L65>>

ImageBackground has a `imageStyle` prop in the source but not in the typings.

### CODE REVIEW

**Comment by iRoachie** [comment]
@huhuanming Check this for me?

**Review by huhuanming — APPROVED** [review]
LGTM

**Comment by iRoachie** [comment]
@alloy Good to merge

**Comment by huhuanming** [comment]
👍

**Pull request merged**
