### PR TITLE
jest - toMatchObject can also match arrays

### PR DESCRIPTION
**Pull request by dandv**
https://github.com/facebook/jest/pull/3994

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Calling that function with an array is already legal. ??

**Comment by dandv** [comment]
@RyanCavanaugh what the bot said, but about the other repo :)

**Comment by RyanCavanaugh** [comment]
I don't understand

**Comment by RyanCavanaugh** [comment]
The type `{} | any[]` is effectively identical to `{}`; it doesn't *do* anything to add `| any[]` to that declaration

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by dandv** [comment]
WebStorm does complain if you pass an array to `toMatchObject`:

image

**Comment by RyanCavanaugh** [comment]
Well if we need it to make WebStorm's imaginary type system work... 😞

**Pull request merged**
