### PR TITLE
change window: any to window: Window in @types/jschannel/index.d.ts

### PR DESCRIPTION
**Pull request by McFlat**
./node_modules/typescript/lib/lib.dom.d.ts has declare var window: Window; while ./node_modules/@types/jschannel/index.d.ts has window: any;

- changed `window: any` to `window: Window` in `types/jschannel/index.d.ts`
- added `lib: "dom"` to `types/jschannel/tsconfig.json`
- changed `window: null` to `window` in `types/jschannel/jschannel-test.ts`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L16404>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by McFlat** [comment]
I'm not really sure what's the best way to make this work for node and for client/browser. 

Do I add this to the file?
```
declare var Window: {
    prototype: Window;
    new(): Window;
};
```
Or do I have to import `typescript/lib/lib.dom.d.ts`?

**Comment by McFlat** [comment]
I'll undo that, give me a minute

**Comment by McFlat** [comment]
I have to step out for a couple hours but I'll be back on this, I'll actually clone the code and make the changes clean this time.

**Review by Yitzchok — APPROVED** [review]

**Comment by McFlat** [comment]
Maybe I needed to add [key: string]: any to window. I'll have to create another pull request since it affects another definition.

**Pull request merged**
