### PR TITLE
Changed redux thunk to versions above 2.x

### PR DESCRIPTION
**Pull request by doubleppereira**
case 1. Add a new type definition.
- [X ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [X ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [X ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tkqubo** [comment]
Sorry this looks like a duplication of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8452

**Comment by oizie** [comment]
Ok, Thanks no problem then

**Comment by tkqubo** [comment]
Thanks, then could you close this issue later?  By the way do we have a template like this below?

```
case 1. Add a new type definition
   ...
case 2. Improvement to existing type definition.
  ...
```

Recently I see a lot of this format on DefinitelyTyped PR but I don't know where this comes from.  Is it automatically generated?

**Comment by oizie** [comment]
Yes it's being auto generated. I just tick the boxs when verifying. Closing

**Comment by tkqubo** [comment]
Oh I see.  Thanks so much :smile:

**Pull request closed without merging**
