### PR TITLE
[fontkit]: add FontCollection, Subset and update Font interface

### PR DESCRIPTION
**Pull request by loveloki**
Some types missing.

I have two question:
- I can't successfully run `pnpm test fontkit`(also in master branch).
- I modify function return type, should I update package version? And how todo it? 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[fontkit readme#font-collection-objects](https://github.com/foliojs/fontkit#font-collection-objects)>>

### CODE REVIEW

**Comment by loveloki** [comment]
@stepancar hello, can you help me? I see you on the fontkits owners list.

**Comment by jakebailey** [comment]
Just merge from master, this was my oops.

**Comment by loveloki** [comment]
> Just merge from master, this was my oops.

Thanks! So I can just wait? Waiting...

**Comment by jakebailey** [comment]
No, you have to either merge from master as I said, or potentially close and reopen the PR.

**Comment by loveloki** [comment]
> No, you have to either merge from master as I said, or potentially close and reopen the PR.

I had merge from master.

Now I should fix test failed by adding type declaration or modifying the running logic?

**Comment by jakebailey** [comment]
Your change is necessarily breaking given you're returning a union of two different things. I am not experienced enough in these types to know what is or isn't the right thing other than that returning a union is usually challenging if the two types are not commonly distinguished in user code. One single `open` function that opens multiple kinds of things is very unfortunate, if that's actually the behavior.

**Pull request closed without merging**
