### PR TITLE
Add definitions for history v3 and use it in react-router v3

### PR DESCRIPTION
**Pull request by LKay**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by LKay** [comment]
Should resolve #14537

**Comment by zhengbli** [comment]
@sergey-buturlakin @ngbrown @LKay can you help review the changes? Thanks

**Review by zhengbli — CHANGES_REQUESTED** [review]

**Comment by LKay** [comment]
@zhengbli Added missing semicolons.

**Review by zhengbli — APPROVED** [review]

**Comment by zhengbli** [comment]
Looks good, please fix th CI errors and then it is ready to merge. Thanks!

**Comment by LKay** [comment]
@zhengbli It's been few days already. Is anything left to be done here or can it be merged now?

**Comment by GiedriusGrabauskas** [comment]
@LKay, are you sure that is correct to return `undefined`?

```ts
 export interface IndexRouteProps {
// ...      
getComponent?(nextState: RouterState, callback: ComponentCallback): undefined;
getComponents?(nextState: RouterState, callback: ComponentsCallback): undefined;
// ...
```

**Comment by LKay** [comment]
@GiedriusGrabauskas These methods are for asynchronous getters and actual result is returned in the specified callback. For synchronous get use `component` and `components` properties. Here is reference https://github.com/ReactTraining/react-router/blob/master/docs/API.md#plainroute

**Comment by GiedriusGrabauskas** [comment]
I understand what these methods are doing. 

You changed `void` to `undefined`. It means that if you implementing these functions, you must to write a line with `return undefined`.

Example from https://github.com/ReactTraining/react-router/blob/master/docs/API.md#getcomponentsnextstate-callback
```ts
<Route path="courses/:courseId" getComponents={(nextState, cb) => {
  // do asynchronous stuff to find the components
  cb(null, {sidebar: CourseSidebar, content: Course})
}} />
```

Throws an error:

```cmd
[ts]
Type '(nextState: RouterState, cb: ComponentsCallback) => void' is not assignable to type '((nextState: RouterState, callback: ComponentsCallback) => undefined) | undefined'.
  Type '(nextState: RouterState, cb: ComponentsCallback) => void' is not assignable to type '(nextState: RouterState, callback: ComponentsCallback) => undefined'.
    Type 'void' is not assignable to type 'undefined'.
```


Fix by your changes:
```ts
<Route path="courses/:courseId" getComponents={(nextState, cb) => {
  // do asynchronous stuff to find the components
  cb(null, {sidebar: CourseSidebar, content: Course});
  // Fix line
  return undefined;
}} />
```

**Comment by LKay** [comment]
Hmm, I'll take a look and maybe change return type to `any`. I'm using these typing skills in two of my big projects and didn't encounter this problem yet. Will take care of this tomorrow.

**Comment by GiedriusGrabauskas** [comment]
And why not `void`?

**Comment by LKay** [comment]
New linter rules in Definitely Typed cause errors when `void` is used instead of `undefined` as void return type.

**Comment by DovydasNavickas** [comment]
@zhengbli, did you really look at the PR or did you just made sure it passes CI?

Some of the changes do not make sense.
@LKay, the errors you mentioned have nothing to do with TSLint. You simply misinterpreted them.

The error is this:
```
void-return  Use the `void` type for return types only. Otherwise, use `undefined`.
```

And this code (1):
```ts
interface IndexRouteProps {
    getComponents?(nextState: Object, callback: Function): void;
}
```

Should be updated to this (2):
```ts
interface IndexRouteProps {
    getComponents?: (nextState: Object, callback: Function) => void;
}
```

Because (1) is defining an undefinable function, but the TSLint most probably gets lost and treats it as a prop, then understands the `: void` part as a property type and not a return type, which makes mentioned error to appear:
```
void-return  Use the `void` type for return types only. Otherwise, use `undefined`.
```

And when you update the code to (2) to have properties of a particular function type, the `void` is used as a return type and not as a property type.
I don't know who wrote the previous version, but it looks quite confusing, even though we might have found a TSLint rule bug?

@RyanCavanaugh, is (1) syntax valid?

If the syntax is valid (which seems to be the case), then the rule might be incorrect. /cc @andy-ms

**Comment by DovydasNavickas** [comment]
I've also made a hotfix PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14743 for all places where `void` should be.

**Pull request merged**
