### PR TITLE
[gapi.people] Update SourceType

### PR DESCRIPTION
**Pull request by martin-badin**
Discussion: #57742
Documentation: https://developers.google.com/people/api/rest/v1/people#sourcetype

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test gapi.people`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developers.google.com/people/api/rest/v1/people#sourcetype>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by domdomegg — APPROVED** [review]

**Comment by martin-badin** [comment]
@peterblazejewicz please review

**Comment by elibarzilay** [comment]
Making it possible to merge, so up to you if you want to wait for a review or not.

Also, it would be good to get rid of the lint exception that you added.

**Comment by martin-badin** [comment]
> Making it possible to merge, so up to you if you want to wait for a review or not.
> 
> 
> 
> Also, it would be good to get rid of the lint exception that you added.
> 
> 

Thank you. I will create a separate PR to remove all lint rules.

**Comment by martin-badin** [comment]
Ready to merge

**Comment by Maxim-Mazurok** [comment]
@martin-badin I wonder if you're using this on the client-side JS?
If that's the case, perhaps https://www.npmjs.com/package/@types/gapi.client.people would be a better fit? If not - let me know why?
These types are updated and tested hourly.
If you're using it with server-side JS, I think that google's NodeJS repo has type definitions available.

**Pull request merged**
