### PR TITLE
Avoid having to pass a definition for Props for React.PropsWithChildren

### PR DESCRIPTION
**Pull request by yordis**
Sometimes, we only care about having `children` definition, for example:

```tsx
export function CanvasProvider(props: React.PropsWithChildren<{}>) {
  const value = useCanvas();
  return <Context.Provider value={value}>{props.children}</Context.Provider>;
}
```

In that case, I must pass an empty `Props` definition since there is none.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
> In that case, I must pass an empty Props definition since there is none.

What is the issue with that?

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46043 for an extended discussion.

**Comment by yordis** [comment]
> What is the issue with that?

@eps1lon we are entering "opinion-driven conversation", and you are right in your own way. I am not sure it would be worth wasting energy trying to convince you since you already made up your mind.

Regardless, answering your question; no need to type an empty interface when you could use a default empty interface for use cases as I displayed before.

Do we need it?! Well, opinions, yes we do in my opinion.

Feel free to close the PR, if you still disagree, and feel that you are making the right decision. I trust your judgment.

**Comment by eps1lon** [comment]
> I am not sure it would be worth wasting energy trying to convince you since you already made up your mind.

I've made up my mind up until I hear new arguments. So it's a bit easy for you to put the blame here on me. You are proposing this change so you need to provide arguments other than "I like it". 

I don't see how `PropsWithChildren` is not a mistake almost all the time. Preventing it by putting the "burden" on authors to add (what they think) is the default type isn't all that much to ask, no? Especially since you already identified the use case as "sometimes". It would make sense as the default if you would pass it "most of the time". Otherwise TypeScript should just allow omitting generic arguments and default to their "topmost" type.

**Comment by yordis** [comment]
> So it's a bit easy for you to put the blame here on me

@eps1lon Hey Sebastian, in what way I an putting "blame" on you? As I said, "if you still disagree, and feel that you are making the right decision. I trust your judgment." How else could I compliment you, and let you know that even when I disagree with you, I still trust that you are making the right decision? You don't need to react defensively, and I am sorry if I made you react that way.

From my perspective, it is a matter of understanding the situation where we are and understand that we have a disagreement, there is no right answer based on the ultimate Truth, these arguments hold no weight.

You are right in your own way, such am I 🤷‍♂️

I still disagree with your argument, and the argument is valid based on your experience, but also, based on the use cases I shared with you, I still don't see your point.

Once again, I trust your judgment. Honestly, it is just annoying to type something that is simple to fix, but it is not the end of the world for me.

Cheers,

**Comment by dimitropoulos** [comment]
I welcome a cordial discussion on this, thanks for keeping it low-energy @yordis.

From what I understand it's not an objection to the simplicity of the fix, but rather the semantic appropriateness of a type that says it has props (in the name of the type itself) being used without providing any props.  If you would like to help me understand why "no props" (also slyly phrased "empty set" in the previous discussion on this) is the same has "1 or more props" then I'm genuinely interested in hearing why.  I bet @eps1lon is too, but that's just speculation.

I wonder if this is just a situation of people filling in the gaps in the name differently.  I read `PropsWithChildren` as "has props and also has children" but perhaps others (and you) are reading it as "the props argument that _does_ have children (but may or may not have other props specified)".  Thoughts on that?

___

Here's another question: is there a new/different type that you would rather have that doesn't exist today.  I can completely understand the need for a type that just has children - I would use it, myself, pretty regularly.

**Pull request closed without merging**
