### PR TITLE
Move `description` into `BasicLabel` for github-label-sync package

### PR DESCRIPTION
**Pull request by kenodegard**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
    - The `description` keyword is a valid input to as well as result from the GitHub query
        - See label creation API [parameters](https://docs.github.com/en/rest/reference/issues#create-a-label--parameters) and [response](https://docs.github.com/en/rest/reference/issues#create-a-label--code-samples)
        - See label updating API [parameters](https://docs.github.com/en/rest/reference/issues#update-a-label--parameters) and [response](https://docs.github.com/en/rest/reference/issues#update-a-label--code-samples)
        - See label deleting API [parameters](https://docs.github.com/en/rest/reference/issues#delete-a-label--parameters)
- [X] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~ No version number change necessary.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## github-label-sync ([<kbd>unpkg</kbd>](https://unpkg.com/browse/github-label-sync@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'github-label-sync'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f4fe5ca04c1225cfc6363c9ec0160585385a691b
</p>

**Review by EndBug — APPROVED** [review]
LGTM
The diff does include descriptions, I guess I didn't see it when I first created the typings...

About the DangerJS error: it popped up before and I couldn't figure out a better way to solve it, but maintainers merged the previous PR anyway.

Here's my comment from the original PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48830#issuecomment-709596664

If you find a solution feel free to add it, otherwise I guess you can just ignore it

**Comment by kenodegard** [comment]
@EndBug ah I'll stop bashing my head against the keyboard then 😄

**Comment by kenodegard** [comment]
Ready to merge

**Pull request merged**
