### PR TITLE
Add printerSupport to mjml-core

### PR DESCRIPTION
**Pull request by jimmyfortinx**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mjmlio/mjml/pull/2677
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jakebailey** [comment]
This change is merged in v4.15.0; do you want to open this and bump the version number in package.json to get this change in?

**Review by jakebailey — CHANGES_REQUESTED** [review]
See above comment; the package.json needs a version bump.

**Comment by jimmyfortinx** [comment]
@jakebailey Sorry it took me a while to understand that you were referring to the main version of the package and not under the dependencies 🤦

**Review by jakebailey — APPROVED** [review]

**Comment by jimmyfortinx** [comment]
Ready to merge

**Pull request merged**
