### PR TITLE
Update openlayers layer options

### PR DESCRIPTION
**Pull request by Ailrun**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://openlayers.org/en/latest/apidoc/ol.layer.html
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by osechet — CHANGES_REQUESTED** [review]
- The PR title should be changed to say the modification is related to ol.layer.Heatmap
- The link to documentation is: http://openlayers.org/en/v4.3.0/apidoc/ol.layer.Heatmap.html
- Please could you add the associated unit test?

**Comment by osechet** [comment]
The modification appears with openlayers 4.3.

**Comment by Ailrun** [comment]
@osechet This PR is not just doing with `ol.layer.Heatmap` but also related with other kinds of `ol.layer`. Could you explain your comment with more detail??

**Comment by osechet** [comment]
@Ailrun Sorry, I was probably not fully awaken yet: I missed the end of the file. You can ignore the part about changing the title and the link.

**Comment by Ailrun** [comment]
@osechet 
I added tests.

**Review by osechet — APPROVED** [review]

**Pull request merged**
