### PR TITLE
[cli-progress] Fix `startTime` type

### PR DESCRIPTION
**Pull request by JoCat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/AndiDittrich/Node.CLI-Progress/blob/d1e9ffa210b34ea3e5630635d4facaaf7fe551c8/lib/generic-bar.js#L120>

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
LGTM!
also here:
https://github.com/AndiDittrich/Node.CLI-Progress/blob/d1e9ffa210b34ea3e5630635d4facaaf7fe551c8/lib/formatter.js#L28
@JoCat would be useful to add a test, otherwise it will wait for DT maintainer review (we could skip this and not waste their time by adding a simple tests for a change), thx!

**Comment by JoCat** [comment]
Ok, in principle, I can add a test, it's just that there is a very small change, which I did not see the point of wrapping with tests

**Comment by JoCat** [comment]
very strange
image

**Comment by JoCat** [comment]
I uploaded a test with a code snippet that I used myself, it looks like there are some flaws in typings in some places, but so far I have not come across a similar one 😅

**Comment by JoCat** [comment]
Registered extend from EventEmitter because it is used in the code.

In code examples:
https://github.com/AndiDittrich/Node.CLI-Progress/blob/d1e9ffa210b34ea3e5630635d4facaaf7fe551c8/lib/generic-bar.js#L7
https://github.com/AndiDittrich/Node.CLI-Progress/blob/d1e9ffa210b34ea3e5630635d4facaaf7fe551c8/lib/multi-bar.js#L7
And docs:
https://github.com/AndiDittrich/Node.CLI-Progress/blob/master/docs/events.md

**Comment by peterblazejewicz** [comment]
> Ok, in principle, I can add a test, it's just that there is a very small change, which I did not see the point of wrapping with tests

it does not matter and I understand your point. The outcome of such stance here in this project (thousands of DT packages), is no one will merge the PR (usually)

**Comment by peterblazejewicz** [comment]
> Registered extend from EventEmitter because it is used in the code.

Thanks for doing this!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@JoCat thx!

**Comment by JoCat** [comment]
Ready to merge

**Pull request merged**
