### PR TITLE
[theme-ui] Make styles' properties optional

### PR DESCRIPTION
**Pull request by pomber**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://theme-ui.com/theming#styles
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by erikdstock — APPROVED** [review]

**Comment by erikdstock** [comment]
@pomber mind adding a test case and including yourself in maintainers?

**Comment by pomber** [comment]
Thanks @erikdstock  

Last time I tried to run the linting script it failed because of the csstype dependency:
```bash
$ npm run lint theme-ui

> definitely-typed@0.0.3 lint /home/pomber/p/temp/DefinitelyTyped
> dtslint types "theme-ui"

Error: Errors in typescript@next for external dependencies:
../react/index.d.ts(28,22): error TS2307: Cannot find module 'csstype'.
../styled-system/index.d.ts(22,22): error TS2307: Cannot find module 'csstype'.
../styled-system__css/index.d.ts(8,22): error TS2307: Cannot find module 'csstype'.
```

What am I missing?

**Comment by mrcrane** [comment]
You should be able to fix linting by running `npm install` in types/react, types/styled-system, and types/styled-system__css.

If a package relies on types that are bundled (as opposed to being hosted on DefinitelyTyped), you need to run `npm install` in that package's DefinitelyTyped folder for it to resolve correctly.

**Review by mrcrane — CHANGES_REQUESTED** [review]
Marking as changes requested until @erikdstock's request is addressed.

**Review by erikdstock — APPROVED** [review]
🎈 💯 🏴

**Review by mrcrane — APPROVED** [review]

**Comment by mrcrane** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
