### PR TITLE
[keyv] correct types for `serialize` & `deserialize` options keys

### PR DESCRIPTION
**Pull request by medfreeman**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
  - deserialize: https://github.com/lukechilds/keyv/blob/ab99cada0186e6dc83420ceaa85919d1bae871dd/src/index.js#L58-L71
  - serialize: https://github.com/lukechilds/keyv/blob/ab99cada0186e6dc83420ceaa85919d1bae871dd/src/index.js#L89-L91

### CODE REVIEW

**Review by BendingBender — CHANGES_REQUESTED** [review]
Please extend the signature of `get` (`get(key: string): TValue | Promise<TValue | undefined> | undefined;`) with the options parameter: https://github.com/lukechilds/keyv#getkey-options

**Comment by medfreeman** [comment]
Ok, changes done. Thanks for your input!

**Review by BendingBender — APPROVED** [review]

**Review by orta — APPROVED** [review]
Looks pretty reasonable to me

**Comment by medfreeman** [comment]
Ready to merge

**Pull request merged**
