### PR TITLE
[@types/aws-lambda] Fix Context.memoryLimitInMB type

### PR DESCRIPTION
**Pull request by dnalborczyk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by simonbuchan** [comment]
Double-checked, and yep, this is the case. CI failure is in the `aws-serverless-express` tests, just update those to use strings then I'll approve.

**Comment by dnalborczyk** [comment]
@simonbuchan I'll have a look.

**Review by simonbuchan — APPROVED** [review]
Looks great, thanks!

**Comment by orta** [comment]
👍

**Comment by Glen-Moonpig** [comment]
Why was memoryLimitInMB changed to string? In the official .NET lambda library it is an integer.

**Comment by dnalborczyk** [comment]
@Glen-Moonpig because in the `node.js` lambda, for which these @types are for, this value is a string.

**Comment by Glen-Moonpig** [comment]
I see, the value is taken straight from the environment variable, which strictly speaking is string or undefined, but assumed to be string in all cases.

```
  /**
   * All parts of the user-facing context object which are provided through
   * environment variables.
   */
  _environmentalData() {
    return {
      functionVersion: process.env["AWS_LAMBDA_FUNCTION_VERSION"],
      functionName: process.env["AWS_LAMBDA_FUNCTION_NAME"],
      memoryLimitInMB: process.env["AWS_LAMBDA_FUNCTION_MEMORY_SIZE"],
      logGroupName: process.env["AWS_LAMBDA_LOG_GROUP_NAME"],
      logStreamName: process.env["AWS_LAMBDA_LOG_STREAM_NAME"]
    };
  }
```

**Pull request merged**
