### PR TITLE
[webpack-bundle-analyzer] webpack@5 compatibility

### LINKED ISSUE #48807: [@types/webpack-bundle-analyzer] Support for webpack 5
[@types/webpack-bundle-analyzer] doesn't support webpack 5 types which are now generated by webpack itself.

```
node_modules/@types/webpack-bundle-analyzer/index.d.ts:9:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

9 import { Plugin, Compiler, Stats } from 'webpack';
           ~~~~~~

node_modules/@types/webpack-bundle-analyzer/index.d.ts:76:31 - error TS2702: 'Stats' only refers to a type, but is being used as a namespace here.

76         statsOptions?: null | Stats.ToJsonOptionsObject;
                                 ~~~~~
```

- [x] I tried using the `@types/webpack-bundle-analyzer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kryops, @VladimirGrenaderov, @maxbogus, @peterblazejewicz

### PR DESCRIPTION
**Pull request by kryops**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48807

This is a bit of a tricky one: webpack@5's own types declare a `WebpackPluginInstance`  interface, while the webpack@4 types / `@types/webpack` maintained here have an abstract `Plugin` class, which is used by type definitions for webpack plugins. There are plans to extend webpack@5's own types and maybe add a `Plugin` alias there (see https://github.com/webpack/webpack/issues/11630 and https://github.com/webpack/webpack/pull/11698), but they are not in yet.

I tried it the other way around and added a `WebpackPluginInstance`  interface to the webpack@4 types defined here, which makes the `webpack-bundle-analyzer` types compatible with  both `@types/webpack` and `webpack@5` at its current state.

Asking the maintainers of `@types/webpack` (who the Bot will hopefully ping): Do you think this is ok or should we rather wait until webpack aligns their own types with the existing ecosystem?

Same goes with the `Stats` options, which are currently defined as `any` in webpack@5: I copied them into the plugin's type definition for now. What should plugin type definitions do with types that webpack@5 currently does not offer or export?

Did other webpack plugin definitions already add webpack@5 compatibility or is this the first attempt?
_______

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-plugin
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by kryops** [comment]
Mentioning other webpack related definition authors to raise awareness so we're not all trying to solve the same problem at the same time. Sorry for the spam, please unsubscribe if this is irrelevant for you:

@AGenson @andersk @AviVahl @bahlo @blaise-io @bumbleblym @ChaosinaCan @danpintara @Danscho @davecardwell @deevus @dsifford @dublicator @e-cloud @flying-sheep @FranklinWhale @garbetjie @hotell @huan086 @iclanton @inglec-arista @j-f1 @JounQin @JuanJoseGonGi @karol-majewski @katyo @kgroat @maestroh @malj @maxbogus @monsonjeremy @mtraynham @nhardy @odnamrataizem @pd4d10 @peterblazejewicz @pine @PlayMa256 @r3nya @remcohaszing @rynclark @Seally @skovy @tkqubo @use-strict @vajkayrene @VladimirGrenaderov @woitechen

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## webpack-bundle-analyzer ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpack-bundle-analyzer@latest/))
was missing the following properties:
1. start
## webpack ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpack@latest/))
was missing the following properties:
1. WebpackOptionsDefaulter
1. WebpackOptionsApply
1. NodeEnvironmentPlugin
1. validate
1. validateSchema

<details>
<summary>as well as these 6 other properties...</summary>
<p>WebpackOptionsValidationError, dependencies, web, webworker, node, util</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ceb69de4d181b5663f253092c8a1f35f9ef3294d
</p>

**Comment by ofhouse** [comment]
Hi, `@types/webpack` here,
Since it only adds an additional export here I am completely fine with this addition.

Most of the exported names came from a time (webpack@2.x.x) where there were no types or annotation the webpack repo itself.
So the authors picked names that made sense to them at the time but they were never renamed when the webpack authors began to annotate the repo itself and gave them other names.
So it's not uncommon to find type names here that are different from the annotations available in webpack itself.

Changing all the names now makes no sense since this typings will be deprecated eventually. But when you find something that makes the upgrade to webpack@5.x.x easier and is a non-breaking change then you are welcome to add them.

**Review by ofhouse — APPROVED** [review]

**Comment by kryops** [comment]
Ready to merge

**Comment by peterblazejewicz** [comment]
thanks!

**Pull request merged**
