### PR TITLE
Add optional type information for the Sequelize's import define function

### PR DESCRIPTION
**Pull request by jocull**
This optional method was unavailable in the previous typing information

### CODE REVIEW

**Comment by vvakame** [comment]
*sequelize/sequelize.d.ts*

to authors(@samuelneff @codeanimal @drinchev). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/89091950
@jocull please try with `--noImplicitAny` options.

**Comment by jocull** [comment]
My apologies for blundering the syntax - it should be corrected now. This is my first real TypeScript project :)

**Comment by drinchev** [comment]
Hello @jocull , I don't see any of this syntax in sequelize. Can you claim where did you get that second argument from? I think it might be a different version ( https://github.com/sequelize/sequelize/blob/v3.13.0/lib/sequelize.js#L625 )

**Comment by drinchev** [comment]
Ah, my bad. The line is below ( https://github.com/sequelize/sequelize/blob/v3.13.0/lib/sequelize.js#L636 ). Sorry. Yep :+1: from me on this.

**Comment by vvakame** [comment]
thanks mate!

**Comment by jocull** [comment]
:tada:!

**Pull request merged**
