### PR TITLE
[node-telegram-bot-api] Added several methods introduced in node-telegram-bot-api v0.30.0

### PR DESCRIPTION
**Pull request by XC-Zhang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yagop/node-telegram-bot-api/releases/tag/v0.30.0
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Changes:
- Added `provider_data` to interface `SendInvoiceOptions`.
- Added definitions for methods `editMessageLiveLocation`, `stopMessageLiveLocation`, `setChatStickerSet`, `deleteChatStickerSet`, `getFileStream`.
- Added options to method `stopPolling`.
- Updated signature of method `answerCallbackQuery`.

### CODE REVIEW

**Review by Dabolus — CHANGES_REQUESTED** [review]
Thanks for this PR! Just one thing: since this PR updates the typings to `node-telegram-bot-api` v0.30, you should also update the first line of the header comment to point this out

**Comment by XC-Zhang** [comment]
Thank you for the suggestion! Version in the first line of the header comment has been updated. Please review the updated commit.

**Comment by Dabolus** [comment]
Thanks! LGTM

**Review by Dabolus — APPROVED** [review]

**Review by kvcpr — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
