### PR TITLE
[big.js] named module export

### PR DESCRIPTION
**Pull request by googol**
Big.js now has a named export, so it can be nicely imported with the es6 module syntax. This rewrites the typings to make use of that. Also fixes the interfaces so that the instance interface is properly separated from the constructor interface, and the types can also be imported (no need to rely on the global namespaced types).

~This now only includes the module typings, so the typings for the global variable version are removed. Is this a problem? I expect it not to be, since node uses the commonjs version, and browser code is practically always bundled and uses the same commonjs code~

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/MikeMcl/big.js/pull/85
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nycdotnet** [comment]
Hi - thank you for doing this work!!  I noticed your efforts on the big.js repo as well.  Since big.js can be used globally, I don't think it's the right idea to remove the global variable.  Perhaps we can use this pattern?  https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html

Secondly - I noticed that you renamed the items in the rounding enumeration - Is that based on big.js docs changes?  If not, it's best to keep them as-is so we don't introduce a breaking change for someone.

Thank you for this PR.  :-)

**Comment by googol** [comment]
I'll see if I can do the global type with that pattern without duplicating the interfaces.

The rounding mode names are taken from here: https://mikemcl.github.io/big.js/#rm. I used the BigDecimal equivalents from that table.

**Comment by googol** [comment]
I added the global block.
I'm not sure what the best way to test the typings would be though. I did verify manually that they work, but I can't get the linter to check two different test files.
If I just do both tests in the same file, I'd need to import the module versions as a namespaced import `import * as Module from 'big.js'` and hope I remember to use it in all of the corresponding tests. Is that worth it?

**Comment by nycdotnet** [comment]
Gonna look at this tonight, thanks for your work on this @googol

**Comment by googol** [comment]
So I tried adding a second test file that only tested the globally exported types, but the linter won't allow adding a second test file.

Thanks for looking at this @nycdotnet

**Comment by googol** [comment]
Did you have time to look at this @nycdotnet?

**Comment by nycdotnet** [comment]
This looks good to me.  I found out that you can create a `test` folder and put additional tests in there.  Remove the `files` section of the `tsconfig.json` in the big.js folder, and add a new file `test/big.js-global-tests.ts`.  You should be able to copy and paste the existing test file with the following changes:

1. Add a comment like `This gives an example of using the definitions when Big is declared globally such as when big.js is loaded via script tag on a web page.`
1. Remove the import statement
1. Where you're using the RoundingMode enum, you'll have to qualify it with `BigJs.`
1. Where you're calling `multipleTypesAccepted`, you'll have to qualify `Big` with `BigJs.`

That should lint both files properly.  Way to go modernizing this definition!!!

**Comment by googol** [comment]
Excellent! I tried adding a `big.js-global-tests.ts` into the big.js directory earlier, and the linter wanted me to rename it to `big.js-tests.ts`. With the test directory it works now.

I'll merge this now

**Review by nycdotnet — APPROVED** [review]
Great job.

**Pull request merged**
