### PR TITLE
feat(react-modal): update typing react-modal for version 1.6.0

### PR DESCRIPTION
**Pull request by steller**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/reactjs/react-modal>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
sorry for late. could you resolve conflict?

@radziksh could you review this PR?

**Comment by radziksh** [comment]
@vvakame I don't understand one thing, it has already made in types 2.0. I think that should be single source of truth. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13249. How to solve such problems?

**Comment by steller** [comment]
@radziksh do you want to update my PR with optional param for contentLabel ?

@vvakame For the conflict i haven't access, and didn't view what it's in conflict ;)

**Review by radziksh — COMMENTED** [review]
ah, ok, I got it. @steller Your changes should be merged in types-2.0. But these changes already done by @kuon in #13249. So please just close your PR. But thank you for your time that you spent on it!

**Pull request closed without merging**
