### PR TITLE
(react-native): add scheduleLayoutAnimation for keyboard

### PR DESCRIPTION
**Pull request by Naturalclar**
Add `scheduleLayoutAnimation` type definition for `Keyboard` module

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/Keyboard.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by ca057 — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Comment by chrisdrackett** [comment]
@Naturalclar thanks!

**Comment by yfunk** [comment]
@Naturalclar @ca057 @a-tarasyuk The commit 647e3d1 in this PR changes the type definition of `KeyboardEvent` (which is given as a parameter to any Keyboard EventListener callback) by splitting it into `AndroidKeyboardEvent` and `IOSKeyboardEvent`. 

While in theory this kind of makes sense, since for example `startCoordinates` seems to always be undefined on Android, there is a big issue I see with how it was implemented: These new definitions essentially remove`startCoordinates` and `isEventFromThisApp` from the `KeyboardEvent` type, because they don't exist on `AndroidKeyboardEvent`.

Consider this code example: 
```
Keyboard.addListener('keyboardDidShow', event => console.log(event.startCoordinates));
```
This would raise a TypeScript error, even though `startCoordinates` is available on iOS devices. On top of that IntelliSense also won't suggest any of these parameters for auto-complete anymore. You can't even use the hacky approach of typecasting `event` based on the current platform, because none of the new definitions are exported.

From what I can see this change isn't necessary for `scheduleLayoutAnimation`, since it doesn't make any use of the new `AndroidKeyboardEvent` and `IOSKeyboardEvent` types. If I'm not missing something important here I would suggest to undo this change.

**Comment by ca057** [comment]
@yfunk I see your point, I wasn’t aware while reviewing. If I understand it correctly, we have two options:

1. we move all types back into one `interface KeyboardEvent` (we should then add docs stating which prop is for which platform and if they have a fixed value)
2. we keep the split, but export the specific events as well so you can typecase the event based on your needs?

I had a quick look through some of the types and saw that there are both ways on how it’s done, sometimes specific types for both platforms are exported (e.g. `TextStyleIOS` and `TextStyleAndroid` and `TextStyle` which extends the first two), sometimes we have a platform annotation(`@platform ios | android`).

What about following the example of the `TextStyle` and doing something like:
```
interface AndroidKeyboardEvent {
    /**
     * @platform ios
     */
    duration: 0;
    /**
     * @platform android
     */
    easing: 'keyboard';
};

interface IOSKeyboardEvent {
    /**
     * @platform ios
     */
    startCoordinates: ScreenRect;
    /**
     * @platform ios
     */
    isEventFromThisApp: boolean;
};

export interface KeyboardEvent extends AndroidKeyboardEvent, IOSKeyboardEvent {
    duration: number;
    /**
     * Is "keyboard" on Android.
     */
    easing: KeyboardEventEasing;
    endCoordinates: ScreenRect;
}
```

It follows the pattern of other parts of the types, you always get everything presented and the docs tell you at least which props are available on which platform:
Screenshot 2020-12-23 at 16 38 17

What do you think? @alloy do you know what the best way to proceed here is?

I’m happy to open a PR to make the change if you agree :)

**Comment by yfunk** [comment]
@ca057 I like the idea of making `KeyboardEvent` extend the platform specific types and adding corresponding documentation. That way the type has all its properties again and you can easily see which of them are limited to which platform. Even better if it is consistent with other type definitions. 

Just exporting the new types for explicit typecasting isn't really a good solution to the problem in my opinion, since it would make working with Keyboard Events unnecessarily complicated while still leaving us with the issue of not getting any IntelliSense on these properties.

**Pull request merged**
