### PR TITLE
[@wordpress/editor] fix type function uploadMedia()

### PR DESCRIPTION
**Pull request by yusuke-omae**
The `uploadMedia` function in the "@wordpress/editor" package is a wrapper for the `mediaUpload` function in the "@wordpress/media-utils" package, but some of its arguments and return value are different.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by dsifford** [comment]
@dmsnell do you have the context for this?

**Comment by dmsnell** [comment]
@yusuke-omae thanks for the contribution. it looks like this is trying to fix a problem in the official types from Gutenberg. did you already look at fixing the types in WordPress/gutenberg?

While we're generally pretty quick and lenient here, generally we'd prefer not wrapping Core typings with wrappers that fix or workaround problems there.

Not sure if I'm misunderstanding the PR though, so some clarification would be helpful.

**Comment by dmsnell** [comment]
Thanks @yusuke-omae - I'm not asking so much about whether it's important to correctly type the `mediaUpload`, or the `uploadMedia`, but trying to understand what's going on in this specific PR.

Are you saying that the existing types are wrong and you are trying to fix them here in DefinitelyTyped?

**Comment by dmsnell** [comment]
@yusuke-omae I'm not entirely sure how to understand what you are saying.

Of note though, we've been trying to remove the type packages from DefinitelyTyped and focus on getting them into Gutenberg.

It's generally quite easy to add missing types here, but if we're going to be changing or fixing the types that already exist, would it be possible to propose fixing them first inside Gutenberg and then updating the versions here so that we don't have two different types depending on which package is in use?

**Comment by dmsnell** [comment]
thanks for the continued responses @yusuke-omae - I'm still having trouble grasping everything going on here.

maybe @noahtallen can chime in.

> @types/wordpress__foo would be an alternative until @wordpress/foo becomes TypeScript.

One difference here is that `@wordpress/media-utils` already exports TypeScript types and this patch appears to import that type and then modify it. Does the `@wordpress/editor` package introduce a new modified form of arguments it passes down? If so then I think we definitely need a comment explaining why this looks like a workaround to types in `@wordpress/media-utils`.

Does `@wordpres/editor` already expose `mediaUpload`? If so then I think we need to fix this at the source instead of here in DefinitelyTyped.

Is the goal to make `maxUploadFileSize` optional and to change the type of `onError`, and also prevent people from sending `wpAllowedMimeTypes` to `mediaUpload`?

**Comment by noahtallen** [comment]
> Does the @wordpress/editor package introduce a new modified form of arguments it passes down?

Yeah, it looks like the exported `uploadMedia` function in `@wordpress/editor` is a wrapper around the media-ultis function for some reason. I don't know why it exists in editor though.

> Does @wordpres/editor already expose mediaUpload? If so then I think we need to fix this at the source instead of here in DefinitelyTyped.

It's exported here:
https://github.com/WordPress/gutenberg/blob/2224d4f59892aec92718c0e9a48866d28967156d/packages/editor/src/utils/media-upload/index.js#L26

However, `@wordpress/editor` doesn't export any type info, so this package is currently the right place to add type information for it. This PR seems to do that

**Review by dmsnell — APPROVED** [review]
Thanks @noahtallen - if you don't see a problem here then I don't either.

**Comment by dsifford** [comment]
Ready to merge

**Pull request merged**
