### PR TITLE
add npm raven

### PR DESCRIPTION
**Pull request by scttcper**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by sandersn** [comment]
Is this supposed to support raven-js as well as raven-node? `export as namespace Raven` puts `Raven` into the global scope if the d.ts isn't imported, which is not needed for node usage.

It might be worthwhile to create a separate raven-js package that is nearly the same as this one, but named `raven-js`, and that includes `export as namespace Raven`

Also, `strictNullChecks` should be true.

**Comment by scttcper** [comment]
Thanks for looking it over. raven-js has typings (because of its official Angular support) node-raven does not. I've fixed the strictNullChecks and namespace export.

**Comment by sandersn** [comment]
One more question. Is the typical usage `import * as Raven from 'raven'` or `import Raven = require('Raven')`? If it's the former, you don't even need the `declare namespace Raven { ... }; export = Raven;` You could just have everything be a top-level export.

**Comment by scttcper** [comment]
Excellent feedback! I've flattened it. Wasn't sure if it should be using `export` or `declare` on each item. Went with declare.

**Comment by sandersn** [comment]
Shouldn't matter. For d.ts files I am pretty sure they are the same.

**Pull request merged**
