### PR TITLE
feat: add two component types

### PR DESCRIPTION
**Pull request by youngjunning**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by youngjuning** [comment]
@orta Is there something wrong with CI?

**Comment by sandersn** [comment]
A change in the TS nightly makes DT parsing run out of memory. I pinned Typescript to a version before the change while I investigate.

**Comment by youngjuning** [comment]
@sandersn Hi bro, Any problem here.

**Review by sandersn — APPROVED** [review]
Looks like the bot forgot to remove the CI Failed label

**Comment by youngjuning** [comment]
@typescript-bot Hello

**Pull request merged**
