### PR TITLE
[gapi.client.*] Bulk update Google API namespace

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

As seen previously in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60471 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55712 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53354 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52618
Enabled by https://github.com/microsoft/DefinitelyTyped-tools/pull/499
Related to https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/652
Reopened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61722 because @typescript-bot didn't pick it up

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
@sandersn, the @typescript-bot created by @RyanCavanaugh doesn't see this PR, it's my second attempt and it's been a month now, users are affected: https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/683 Please-please-please, make sure this PR gets through... I guess I'm gonna try to chunk it in hopes of getting through in the meantime... Thank you!

**Comment by jakebailey** [comment]
@typescript-bot Hello?

Note that various people are out of office, and the bot not sticking this into the project probably meant whoever is on DT rotation missed it as it didn't show up. Large PRs get a label saying so, the bot shouldn't outright fail, so this seems like a bug if anything.

**Comment by Maxim-Mazurok** [comment]
Thank you Jake, pinging the bot didn't help in the previous PR. And this is why I'm trying to get attention from maintainers, I know that without getting on the board it'll most likely will be lost..

**Comment by orta** [comment]
Someone would need to log into the azure functions to read the logs to know exactly why, but there is a 'too big to review' style check in the bot which this doesn't seem to be getting hit with.

**Comment by Maxim-Mazurok** [comment]
Gotcha, thanks Orta, so this PR will likely get `tooManyFiles = true` and `hugeChange = true` as well. Still this wouldn't block it if I understand correctly, just add `Huge Change` label and probably require DT maintainers attention. So I'm happy if that's the case. However, I can split it into smaller pieces if that will help reviewers? Let me know.
All these changes are automatically generated by this code: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/src/dt/cli.ts
There are a few integration (snapshot) tests for the DT generator here: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/test/restDocs/test.spec.ts#L91-L114

**Comment by Maxim-Mazurok** [comment]
I ended up splitting this PR into bot-bite-sized pieces, which is turns out to be <= 125 packages.

All picked up PRs:

- [gapi.client.a\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62190)
- [gapi.client.{bc}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62191)
- [gapi.client.d\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62195)
- [gapi.client.{efg}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62196)
- [gapi.client.{hijklm}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62198)
- [gapi.client.{nop}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62197)
- [gapi.client.{rs}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62200)
- [gapi.client.{tvwy}\*](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62199)

These didn't get picked up in reasonable time so I closed them:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62194
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62193
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62192

I will close this PR and open an issue for handling huge PRs. Thanks everyone!

Commands I used for future reference:
```
rm -rf DT1/types/gapi.client.[abcd]* # in clean DT fork's master
cp -R DT2/types/gapi.client.[abcd]* DT1/types/ # in my DT fork branch with all gapi.client.* changes
```

**Pull request closed without merging**
