### PR TITLE
[@types/handlebars]: Remove package, types are now integrated in handlebars

### PR DESCRIPTION
**Pull request by nknapp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] *Test the change in your own code. (Compile and run.)* (when removing a package? see below)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.) (**failing, see below**)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] *Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).* (when removing a package? see below)

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

Some of the checkboxes below don't seem to apply to removing a package, which is why I left them blank.

I have added package.json files to 4 dependencies, but I'm not sure if I did this correctly. It would be nice if someone could check. I notice that "ember-strings" already have type definitions in their source repo, so they might be redundant here.

`npm test` still fails, because Handlebars is not on the dependencyWhitelist of the types-publisher (I've [submitted a PR there](https://github.com/Microsoft/types-publisher/pull/571))

### CODE REVIEW

**Comment by chriskrycho** [comment]
@nknapp maybe push a trivial commit and then force push its deletion; this should be fine. I’ll formaly review it in a few hours.

**Comment by nknapp** [comment]
The pull request mentioned above (https://github.com/Microsoft/types-publisher/pull/571) is still not merged, so a new commit won't change anything.

**Comment by chriskrycho** [comment]
Correct—it will just keep the PR from being closed by the bot.

**Comment by chriskrycho** [comment]
@nknapp any chance you can recreate this PR? The upstream failures in TS *should* be fixed now! If not, please just let me know that you're busy and I'll cherry-pick these commits over into a PR and recreate it myself. Thank you again!

**Comment by nknapp** [comment]
@chriskrycho  I've created a new PR, but running `npm test` still failed on my computer, with the same ecxception.

**Comment by chriskrycho** [comment]
1. Thank you!
2. Blast, that types whitelist is the issue. Pinged them again over there.

I'll follow up further on the types whitelist issue or on #33200. Thank you again!

**Pull request closed without merging**
