### PR TITLE
mongoose: countDocuments and estimatedDocumentCount definitions added

### PR DESCRIPTION
**Pull request by alfirin**
I added three missing definitions for mongoose.
Two for the Model and one for the Query.

Here are the links for all three added definitions:
- [Model.countDocuments](https://github.com/Automattic/mongoose/blob/863bc9ab0a3db8fb0260f9acc8e48288a405be76/lib/model.js#L1749)
- [Model.estimatedDocumentCount](https://github.com/Automattic/mongoose/blob/863bc9ab0a3db8fb0260f9acc8e48288a405be76/lib/model.js#L1720)
- [Query.estimatedDocumentCount](https://github.com/Automattic/mongoose/blob/971311e7db07102b4853416d08142302c30fee68/lib/query.js#L2030)

Thanks a lot for your review

### CODE REVIEW

**Review by Alorel — CHANGES_REQUESTED** [review]
countDocuments() was already added in #27283

**Comment by alfirin** [comment]
@Alorel Yes but just for the Query and not for the Model.

It's for that I added it for the Model too.

**Review by Alorel — APPROVED** [review]

**Comment by aherve** [comment]
Thanks for the PR !

Do you guys have any idea on how long it will take for this change to appear in npm ? I have no idea if it's a matter or minutes, days or weeks...

**Comment by andy-ms** [comment]
@aherve Should be sometime today.

**Comment by aherve** [comment]
Sweet ! Thanks again

**Comment by Alorel** [comment]
@aherve from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated):

> NPM packages should update within a few hours. If it's been more than 24 hours, ping `@RyanCavanaugh` and `@andy-ms on the PR to investigate.

**Comment by alfirin** [comment]
Your welcome @aherve

**Pull request merged**
