### PR TITLE
es-to-primitive: remove ts3.1

### PR DESCRIPTION
**Pull request by sandersn**
Typescript 3.1 is no longer supported on DT.

### CODE REVIEW

**Comment by ljharb** [comment]
Doesn’t this make it a breaking change, which would cause the major versions of the types to be out of sync?

**Review by ExE-Boss — APPROVED** [review]

**Review by ljharb — CHANGES_REQUESTED** [review]
Pending semver clarification

**Comment by sandersn** [comment]
@ljharb Definitely Typed packages piggy-back on semver, compressing its version number to patch version only, but that means it's impossible to force a major version update without a major version update of the library itself. See https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library for more details. `@types` packages should be pinned exactly since each new patch version may in fact contain major versions.

In any case, this isn't a breaking change *for supported versions of Typescript*, which are 3.2 and above. The removal of ts3.1/ does mean that TS 3.1 will now attempt to use the top-level types and fail. Compare #47203, which broke Typescripts 3.0 and earlier in the same way.

**Review by ExE-Boss — APPROVED** [review]

**Review by ljharb — APPROVED** [review]
thanks for the explanation, i was not aware of that aspect of DT packages' semver.

**Pull request merged**
