### PR TITLE
Remove typings for swagger-parser

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

See https://github.com/APIDevTools/swagger-parser/blob/master/CHANGELOG.md#v700-2019-06-12

### CODE REVIEW

**Comment by ffflorian** [comment]
Blocked by https://github.com/microsoft/types-publisher/pull/624

**Comment by ffflorian** [comment]
@sandersn could you please approve or request changes on microsoft/types-publisher#624?

**Comment by ffflorian** [comment]
Blocked by https://github.com/APIDevTools/swagger-parser/pull/118

**Comment by ffflorian** [comment]
@JamesMessinger can you approve? :slightly_smiling_face:

**Comment by JamesMessinger** [comment]
I approve, FWIW 😉

**Comment by ffflorian** [comment]
@sandersn can you merge? :)

**Pull request merged**
