### PR TITLE
fix(node): fix execSync issues

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_process_child_process_execsync_command_options
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53566#issuecomment-876959068

### CODE REVIEW

**Comment by SimonSchick** [comment]
cc @Rich-MSR

**Comment by peterblazejewicz** [comment]
@SimonSchick this was reported against v15. Should be added to v15 as well?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by SimonSchick** [comment]
Ready to merge

**Pull request merged**
