### PR TITLE
[react-helmet-visor] Add explicit types for children

### PR DESCRIPTION
**Pull request by eps1lon**
We plan to remove implicit children from `@types/react`. The following changes are required to pass https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210.

https://github.com/kokushkin/react-helmet-with-visor/blob/release/5.4.0/src/Helmet.js#L39-L42

### CODE REVIEW

**Review by kokushkin — COMMENTED** [review]
Should have been added in the 
```
export class Helmet
```
instead of HelmetProps I believe.
Because, Helmet derived from React.Component (not HelmetProps )

Furthermore, what if you make a new  major version of React Types  first and then I'd jump on this?
(I guess there are some complications must be, I need to read more about it)

@eps1lon

**Comment by kokushkin** [comment]
So, it's going to be a new 18th version of React types together with a new version of React itself as I can see. When I move to it in react-helmet-visor library I should update types here as well and then it will do nicely. Before that it looks like a little bit premature.
What if it is never added into the  React types 18 then I will be left with ```children?: React.ReactNode;``` that I don't need.
(I may have misunderstood the whole thing  though )

@eps1lon

**Comment by eps1lon** [comment]
Implicit children will be removed with 99% certainty. And if not then you can always revert later. But I'd like to have all **published** types ready by the time we push the React 18 types.

Imagine the sheer amount of changes when we do this in a single PR. Hundreds of packages need to be changed and I don't think people would like to be part of that review process.

**Comment by kokushkin** [comment]
Yeah, I see what you're saying but still.. Let's say I have a project that depends on React 17 and  on a library that has React 17 as peerDependecy  I suppose. Then if I jump on React 18 I should surely check for a new version of the library together with the types sibling. If it doesn't exist I don't jump on React 18 in the project.

In order for libraries to be prepared on time it probably make sense to do something prematurely (I've got your point).The downside is though the new version might not be shipped as planned and the changes trash a code a little bit (probably a different branch need). But it's not the case if we trust you and you are sure 99%. Yeah, trust it's a very important thing of  course. Helps save money and time and ship everything on time))

**Comment by eps1lon** [comment]
> The downside is though the new version might not be shipped as planned and the changes might trash code a little bit (probably a different branch needed?).

I don't see how this would be the case. These changes should not break any existing code.

Think about implicit children as being deprecated. You rarely wait for the deprecated thing to be removed but rather want to adress it somewhere between deprecation and final removal.

I'm not following what the concern is here? If they don't get removed, then code will continue to function. If they do get removed, code will already function. But in every case you didn't have to do any potentially wasteful work. If implicit children don't get removed then the only one wasting their time was me.

**Comment by amcasey** [comment]
@kokushkin Any remaining concerns?

**Comment by amcasey** [comment]
@kokushkin I'm not familiar with this specific library, but @eps1lon's explanation makes sense.

**Comment by eps1lon** [comment]
`{ children?: ReactNode | undefined }` is equivalent to `{ children?: ReactNode }`. The `undefined` was only added by a search&replce when types were adjusted for `exactOptionalPropertyTypes`. 

The `ReadOnly` is not relevant here since it's already applied by `React.Component`.

**Comment by eps1lon** [comment]
>  btw what does it mean it was added with search& replace

This is speculation on my part. When `exactOptionalPropertyTypes` was introduced somebody probably just replaced `property?: Type` with `property?: Type | undefined`. This is faster than checking every `Type` for `undefined`.

> Does it mean that now in the React types children?: ReactNode | undefined can be changed to children?: ReactNode without any problem anywhere, meaning it's not breaking change

Yep, should be safe.

>  It's a good thing to do then, would simplify a lot)

I don't think this change would be worth the time. Both definitions are equivalent. It would help more if we could land this PR unless you have any more concerns?

**Review by kokushkin — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by kokushkin** [comment]
Ready to merge

**Pull request merged**
