### PR TITLE
Remove MongoDB - types supported as of 4.0.0

### PR DESCRIPTION
**Pull request by ImRodry**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [X] Delete the package's directory.
- [X] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by CaselIT — CHANGES_REQUESTED** [review]
I think we should not remove them otherwise there is no way of supporting older versions. Not sure what happens in these cases. My guess is that current version needs to be moved in the v3 folder same as the v2 and v2

**Comment by ImRodry** [comment]
MongoDB themselves don't support older versions since April (v3.6 included) so there is no reason to keep this. I'm just going through the tedious process of updating every package to support the new types but these need to be removed imo

**Comment by ImRodry** [comment]
Now we wait for https://github.com/microsoft/DefinitelyTyped-tools/pull/290 to be merged

**Comment by peterblazejewicz** [comment]
you will probably need to request whitelisting `types/mongodb`, so you could reference a `@types/mongodb` as a dependnecy, not `mongodb` in v4.*. Some packages are depending on older versions, say:
https://github.com/OptimalBits/node_acl/blob/master/package.json#L21

**Comment by peterblazejewicz** [comment]
> My guess is that current version needs to be moved in the v3 folder same as the v2 and v2

are there any plans to add anything new into v3? Popular packages like `mongodb` are hard to properly or nicely `phaseout` in some scenarios. The best would be kept v4 native and remove surces from DT for anything older (so v3 and older). Types for v3 are already published to NPM, there is no scenario those will be removed, only souce from here. 
I've done updating `mongoose`, you folks can use that as sample scenario that can be applied here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53417

**Comment by ImRodry** [comment]
> you will probably need to request whitelisting `@types/mongodb`, so you could reference a `@types/mongodb` as a dependnecy, not `mongodb` in v4.*. Some packages are depending on older versions, say:
> [https://github.com/OptimalBits/node_acl/blob/master/package.json#L21](https://github.com/OptimalBits/node_acl/blob/master/package.json?rgh-link-date=2021-07-14T19%3A43%3A50Z#L21)

it shouldn't be our problem if they decide not to update. The package will still be on npm as deprecated but no updates should be done from now on since the types are handled natively.

**Comment by ImRodry** [comment]
One question though @peterblazejewicz why did you make the dependency `@types/mongoose` and not just mongoose?

**Comment by peterblazejewicz** [comment]
> One question though @peterblazejewicz why did you make the dependency `@types/mongoose` and not just mongoose?

It depends, some of those are older packages, those cannot be referencing v4, in that case `@types/mongoose` and recent published version. Evything that works with v4, should us that version directly, I agree.

**Comment by CaselIT** [comment]
> are there any plans to add anything new into v3?

none on my part. I don't really know what's the usual behavior in this case.
I just think that this is similar to what happens when when a library changes major version, where the current types go in a `vX` subfolder and the new ones start in the main fonder. The only difference in this case is that no new types are added in the main folder.

**Comment by ImRodry** [comment]
> > One question though @peterblazejewicz why did you make the dependency `@types/mongoose` and not just mongoose?
> 
> It depends, some of those are older packages, those cannot be referencing v4, in that case `@types/mongoose` and recent published version. Evything that works with v4, should us that version directly, I agree.

I went through all issues and fixed them though, wouldn't that be ok too?

**Comment by ImRodry** [comment]
Made a PR to add `@types/mongodb` as an allowed dependency. Once this is merged, I'll update the PR without changing all of these packages and updating them properly

**Comment by julien-c** [comment]
What's the process to submit changes to the typings now, and does MongoDB Inc. commit to maintain/review those updates?

**Comment by addaleax** [comment]
> What's the process to submit changes to the typings now

You can open PRs to change the source for https://github.com/mongodb/node-mongodb-native at that repository, if that affects the types, those will change along with it. You can also open a ticket at https://jira.mongodb.org/browse/NODE if there is an issue with those typings (or any other part of the package).

> and does MongoDB Inc. commit to maintain/review those updates?

I can’t give an authoritative answer, but generally, the Node.js team at mongodb does review community-submitted PRs.

**Comment by peterblazejewicz** [comment]
> I went through all issues and fixed them though, wouldn't that be ok too?

I don't think using v4 for e.g. `gridfs-stream` is OK, this is 4 years old native JS package, it's like adding dependency in Mongo ecosystem (if 4 gets updated with breaking change upstream, type here on DT or somewhere in the wild, would be broken). It should be probably frozen to version it was tested/created with (so say `types/mongodb@2.2.28`), this will be possible after whitelisting `types/mongodb`.

**Comment by ImRodry** [comment]
Yeah like I've said I have the proper fixes ready, I'm just waiting for the approval of `@types/mongodb` to push them. I used the latest version of the package for all and it worked just fine though so I'll keep it as that unless you want me to change it in specific scenarios

**Comment by ImRodry** [comment]
I'm sorry I have no clue how to fix this error :/

**Comment by ImRodry** [comment]
Can someone help here please?

**Comment by HitkoDev** [comment]
@ImRodry Take a look at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-brute-mongo/tsconfig.json - it's resolving mongo to `mongodb/v2`, but that folder no longer exists.

**Comment by ImRodry** [comment]
Oh that's right, I'll just remove that then since the package does the trick

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by ImRodry** [comment]
Ready to merge

**Pull request merged**
