### PR TITLE
[d3-dsv] Validate for strictNullChecks and JSDoc

### PR DESCRIPTION
**Pull request by tomwanzek**
This PR addresses the `strictNullChecks` validation of **d3-dsv** and adds complete JSDoc comments.

`strictNullChecks` are refined for:
* the return type of the row mapper/filter functions used in parsing
* the DSVRowString key/value object. This addresses the edge case, where the DSV content is not well-structured and some column-values are missing as a result.

Related to #11365.
Related to #11366.
Replaces #21092.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-dsv>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@azoson and @gustavderdrache This PR is intended to replace #21092.

Please review and let me know your thoughts. So far, I have not changed the `columns` property to be possibly undefined, i.e.:

```ts
/**
 * An array object representing all parsed rows. The array is enhanced with a property listing
 * the names of the parsed columns.
 */
export interface DSVParsedArray<T> extends Array<T> {
    /**
     * List of column names.
     */
    columns?: string[];
}
```

The only time this happens is in the edge case that the text string is literally empty.
I am tempted to go to the source and file an issue/PR on **d3-dsv** to ensure that in this edge case `column` is returned as an empty array, i.e. `column = []`.

**Review by gustavderdrache — APPROVED** [review]

**Comment by gustavderdrache** [comment]
@tomwanzek I don't have a strong opinion on the `columns` property you mentioned. I trust your judgment :)

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Comment by azoson** [comment]
I trust your opinion rather than my experiment result.
The type of the value of `columns` should be `string[]`, because it is an empty array in the edge case as you mentioned.
Thank you for your survey 👍 

For future reference, I report that `d3.csvParse` method can return `columns: undefined`.
I compiled and executed the code below, in Chrome, then the `columns` was `undefined`.

```TypeScript
const res = await fetch('./assets/data_basics.csv');
if (res.status !== 200) {
    console.error("Error caused in file read");
}

const dataText = await res.text();
const rawData = await d3.csvParse(dataText);
console.log(rawData);
```



In this case, the `./assets/data_basics.csv` is empty file.
So I think `d3.csvParse` returns `columns: undefind` for an empty file.
But your survey revealed that `d3.csvParse` returns an empty array for an empty file.
Maybe any mistakes in my experiment or errors in D3js.

Anyway, I think the type definitions should be based on the source codes and the specifications of D3js.
I agree with your opinion.

**Comment by tomwanzek** [comment]
@azoson Thanks for your in-depth response. For clarity, I am confirming, that the current **d3-dsv** behavior in the empty string (i.e. file) edge case is to return `column` as `undefined`. However, I am suggesting to merge this PR without changing `columns: string[]`, if there is nothing else to address.

Instead, I will open an issue/PR on **d3-dsv** itself to ensure `column` always returns a string array. In the edge case, it would be empty. I will copy you on the issue for reference. If the issue cannot be resolved on **d3-dsv** itself, then I will create a follow-up PR  here to change to `column?: string[]`.

**Comment by tomwanzek** [comment]
This PR is ready to merge/publish. The `columns: string[]` matter will be addressed at the source as discussed. See d3/d3-dsv#31.

@RyanCavanaugh As always: Thanks for being on top of things 🎉

**Comment by tomwanzek** [comment]
For completeness of reference, the master branch of **d3-dsv** already contains the fix, which ensures that `columns` always returns an array of `string`, even if empty. So the definitions are just a bit ahead until the next patch release of **d3-dsv**.

**Pull request merged**
