### PR TITLE
renamed the addButtons property to the correct way

### PR DESCRIPTION
**Pull request by hanc2006**

### CODE REVIEW

**Review by alexk111 — APPROVED** [review]

**Comment by alexk111** [comment]
@hanc2006 Thanks for the PR 🙏

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Test needs to be updated accordingly; it’s failing.

**Comment by alexk111** [comment]
@hanc2006 To fix the test issue change `addButtons` to `addButton` on this line :

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/17c3353a287ee202e5bb6afb78646530d1e51ccd/types/node-red__editor-client/node-red__editor-client-tests.ts#L240

**Review by andrewbranch — APPROVED** [review]

**Comment by hanc2006** [comment]
@alexk111 I committed your suggested changes. :+1:

**Review by alexk111 — APPROVED** [review]

**Comment by alexk111** [comment]
Ready to merge

**Pull request merged**
