### PR TITLE
Make $scope optional in IComponentControllerService locals

### PR DESCRIPTION
**Pull request by pramodsankarl**
case 2. Improvement to existing type definition.

The `locals` definition for `IComponentControllerService` does not need `$scope` as mandatory dependency (v1.5.4+). It will be used if passed in, otherwise it creates a new isolate scope from `$rootScope`. Hence making that dependency optional.

[Official Doc Reference](https://code.angularjs.org/1.5.8/docs/api/ngMock/service/$componentController)

### CODE REVIEW

**Comment by pramodsankarl** [comment]
@vvakame CI build passes now.

**Comment by pramodsankarl** [comment]
Hi @vvakame Typically how often PRs are reviewed and merged to types2.0 branch? Thanks!

**Comment by vvakame** [comment]
sorry for late!

*angular-mocks/index.d.ts*

to authors (@diegovilar @daltin). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
When we can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by pramodsankarl** [comment]
@vvakame Not heard from authors yet! Can you merge it please if you are ok with the PR?

**Pull request merged**
