### PR TITLE
Add new package - tg-ads-mediation/ads-cdn.

### PR DESCRIPTION
**Pull request by barinbritva**
The types for the lib https://www.npmjs.com/package/@tg-ads-mediation/ads-cdn

The lib is not designed to be used via NPM and it's in the registry only to be indexed by CDN services like JSDeliver. During the build the lib set a global variable to window object.

So I add the types to the lib be used like this:

```html
<script src="https://cdn.jsdelivr.net/npm/@tg-ads-mediation/ads-cdn/dist/ads.js"></script>
```

Then for usage with TypeScript - `npm install @types/tg-ads-mediation__ads-cdn`

Speaking of "noNPM" property - it set it up because it doesn't pass tests without it. I believe It's because I build the lib for UMD module system and tests compares types with types from the package

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/tg-ads-mediation__ads-cdn/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4f6270d1e217e0407289b1afd98afe9b981641b5
</p>

**Comment by peterblazejewicz** [comment]
fancy adding description back to PR?

**Comment by peterblazejewicz** [comment]
please explain the purpose of those declarations.
AFAIK there is a package on NPM already, source written in TS, it does look like NPM package, not 'non-npm'.
If you do own sources, please follow:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by barinbritva** [comment]
@peterblazejewicz, sorry I've forgot about description. I've added it, described the reason the lib needs separate typings and why noNPM property is required

**Comment by barinbritva** [comment]
@peterblazejewicz does my explanation look reasonable for you?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by barinbritva** [comment]
Hi there,

The merge didn't happen yet. Do we need to do something else?

**Comment by peterblazejewicz** [comment]
@barinbritva you're the owner of PR, so it's left to you. As per bot advice, type explicitly in new comment to the PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69113#issuecomment-2037733209

**Comment by barinbritva** [comment]
Ready to merge

**Comment by barinbritva** [comment]
Ready to merge

**Pull request merged**
