### PR TITLE
:heavy_minus_sign: remove compression-webpack-plugin

### PR DESCRIPTION
**Pull request by peterblazejewicz**
As of version 9.1.1 ships its own declaration files:
https://github.com/webpack-contrib/compression-webpack-plugin/commit/02d9b2a672985c7862bced28f5927e779eccbba6

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by amcasey** [comment]
@peterblazejewicz Do their types actually work?  I don't see them in [package.json](https://unpkg.com/browse/compression-webpack-plugin@9.1.0/package.json).

**Comment by peterblazejewicz** [comment]
oh, let me check, thx!

**Comment by peterblazejewicz** [comment]
oh, you're correct, types are published to npm, but tsc won't resolve this, let's block this, I'll make issue upstream,
thx for review

**Comment by peterblazejewicz** [comment]
amended to 9.1.1, they fixed this upstream already:
https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v9.1.1

**Review by amcasey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
