### PR TITLE
ko.plus: Replaced Callback type with Function

### PR DESCRIPTION
**Pull request by pbakshy**
ko.command allows to use callbacks with parameters, Function looks more suitable for that purpose

### CODE REVIEW

**Comment by vvakame** [comment]
*ko.plus/ko.plus.d.ts*

to author(@conficient). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by conficient** [comment]
Sorry for delay, I was away last week - will review and get back to you.

**Comment by conficient** [comment]
:+1: yes that's fine

**Comment by vvakame** [comment]
@conficient thanks!
@pbakshy thanks mate!

**Pull request merged**
