### PR TITLE
[node-jose]: Add additional createEncrypt options

### PR DESCRIPTION
**Pull request by bespokebob**
Add additional options for createEncrypt.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/cisco/node-jose/blob/c3a6ab929734bc4fd0e306c39d7178675dca21bb/lib/jwe/defaults.js
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by nadunindunil — CHANGES_REQUESTED** [review]
Hi @youngbob ,

- Could you please provide documentation or example you used to derive these param changes.
- `contentAlg?: string; protect?: string | string[]` these two param types looks vague. Could you please provide more information? (looks like `contentAlg` and protect have `definite` amount of params)

**Comment by youngbob** [comment]
I included a reference to https://github.com/cisco/node-jose/blob/c3a6ab929734bc4fd0e306c39d7178675dca21bb/lib/jwe/defaults.js in the description, which has a jsdoc comment describing the options. Reading through the code, there are even more options that are possibly passed through, but there is no documentation or comments that I could find for them.

`contentAlg` is likely limited to the same options as `alg` for other functions, but the types here are just defining that as `string` as well. There doesn't appear to be a single documented list of the available options; they're spread out over multiple implementation files.

`protect` looks like it can be a list of any parameter in the JWT header

**Review by nadunindunil — APPROVED** [review]
@youngbob,  understood. Thank you very much 🙂

**Comment by youngbob** [comment]
The code hasn't changed, I just edited the commit message and force-pushed to try to get it to drop the "revision needed" tag.

**Review by nadunindunil — APPROVED** [review]

**Comment by youngbob** [comment]
Ready to merge

**Pull request merged**
