### PR TITLE
Extended Typings for Custom Components in MUI-Datatables (3.7.*)

### PR DESCRIPTION
**Pull request by meinlebenswerk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Custom Components in MUI-Datatables](https://github.com/gregnb/mui-datatables#custom-componentss)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. 

The current definitions match version 3.7, but lack some of the custom components supported by the datatable.
This includes the slots for Checkbox, TableViewCol and Icons, which are added by this change.

### CODE REVIEW

**Comment by meinlebenswerk** [comment]
My bad, I didn't intend on becoming an owner at all, sorry about that -> I'm a bit new to all of this, should I cancel and resubmit the request in this case, or can this be changed on the fly?

**Comment by Favna** [comment]
> My bad, I didn't intend on becoming an owner at all, sorry about that -> I'm a bit new to all of this, should I cancel and resubmit the request in this case, or can this be changed on the fly?

You're not an  owner unless you modify the header of the types file to include your own name. As you have removed that line since opening the PR, it's all good.

**Review by favna — COMMENTED** [review]
If you add some tests for the new code then this PR can go through without a DT maintainer.

They are busy enough as is, and will tend to take about 2 weeks for reviewing from my experience.

**Comment by meinlebenswerk** [comment]
Thank you, I'll do taht :)

**Review by favna — APPROVED** [review]

**Comment by meinlebenswerk** [comment]
Ready to merge

**Pull request merged**
