### PR TITLE
leaflet: added popup options

### PR DESCRIPTION
**Pull request by ccapndave**

### CODE REVIEW

**Comment by vvakame** [comment]
*leaflet/leaflet.d.ts*

to author(@rgripper). could you review this PR?
:+1: or :-1:?

check list

* [ ] pas

**Comment by rgripper** [comment]
@ccapndave Could you possibly use the interface PopupOptions for these options? After that it should be ok to merge.

**Comment by Broodja** [comment]
@ccapndave Please update your PR.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
