### PR TITLE
doc(react-native): Remove myself from authors

### PR DESCRIPTION
**Pull request by thewirv**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by TheWirv** [comment]
Well great, the tests fail without me even changing anything... 🙄

**Review by eps1lon — APPROVED** [review]

**Comment by MysteryBlokHed** [comment]
The CODEOWNERS file should be updated automatically, so you don't need to change it manually and the PR can be approved without a maintainer looking at it.

**Comment by TheWirv** [comment]
> The CODEOWNERS file should be updated automatically, so you don't need to change it manually and the PR can be approved without a maintainer looking at it.

@MysteryBlokHed Thank you, I removed my changes of the CODEOWNERS file.

**Comment by TheWirv** [comment]
@alloy It'd be great if someone could merge this in the near future. thx 🤙🏼

**Comment by TheWirv** [comment]
@alloy pretty, pretty please? 😊😊😊

**Comment by TheWirv** [comment]
> @TheWirv I haven't seen any activity on this PR in more than three weeks, and it still has problems that prevent it from being merged. The PR will be closed on Jun 10th (in a week) if the issues aren't addressed.

@eps1lon What am I supposed to do? The mentioned "problems" don't stem from my PR. :/

**Comment by eps1lon** [comment]
I'd try to rebase and push. The CI error was fixed I believe.

**Pull request closed without merging**
