### PR TITLE
Fixes #10904

### LINKED ISSUE #10904: ws client class should have optional protocols in constructor
As of https://github.com/websockets/ws/blob/master/doc/ws.md#new-wswebsocketaddress-protocols-options. Protocols param is missing.

### PR DESCRIPTION
**Pull request by hedefalk**
Please see https://github.com/websockets/ws/blob/master/doc/ws.md#new-wswebsocketaddress-protocols-options.

Protocols param is missing.

### CODE REVIEW

**Comment by loyd** [comment]
I think you need to add another constructor instead of changing.

**Comment by hedefalk** [comment]
Ah, sorry for not running tests :) Yeah, you're right:

https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L58

**Comment by hedefalk** [comment]
@loyd Wasn't too sure about how to structure code. Needed to pull out a named interface for the options argument since two places so I put it in the namespace. Correct?

**Comment by loyd** [comment]
LGTM

**Pull request merged**
