### PR TITLE
[Types-2.0] Merge master 

### PR DESCRIPTION
**Pull request by yuit**

### CODE REVIEW

**Comment by NoHomey** [comment]
:+1:  enzyme changes are looking good to me.

**Comment by MarianPalkus** [comment]
I agree with @NoHomey :) enzyme changes are looking good 👍

**Comment by plantain-00** [comment]
The changes of ajv is same as #12467, it may needn't to be reviewed again.

**Comment by midknight41** [comment]
The PR looks fine for aws-sdk but it has renamed the file from from ```aws-sdk.d.ts``` to ```index.d.ts```. Is this intentional? A little bit of context wouldn't hurt here.

**Comment by andy-ms** [comment]
@midknight41 Yes, we prefer `index.d.ts` for all `types-2.0` definitions.

**Comment by AlStar01** [comment]
👍 angular-material looks good to me

**Comment by andy-ms** [comment]
I found some test errors with this, so please don't merge yet.

**Comment by midknight41** [comment]
Thanks @andy-ms

**Comment by yuit** [comment]
Thanks @NoHomey @MarianPalkus @plantain-00 @midknight41 and @AlStar01  for reviewing the change !

**Comment by Penryn** [comment]
👍 for async

**Comment by vvakame** [comment]
umm... Travis CI test is so slow...

**Comment by JimiC** [comment]
@vvakame See #12625.

**Comment by vvakame** [comment]
agreed. I heard @RyanCavanaugh has a plan to solve this issue.
@RyanCavanaugh any updates?

**Comment by vvakame** [comment]
`tsc -p CybozuLabs-md5` is failing in my local environment still.
CybozuLabs-md5 is not exists on npm. Can we shipped `@types/CybozuLabs-md5` ?

**Comment by andy-ms** [comment]
@vvakame What is failing for you with `cybozulabs-md5`?
I think it's fine to ship a package not on NPM as long as nothing on NPM has that name.

**Comment by vvakame** [comment]
@andy-ms ah, It solved with `rm -rf CybozuLabs-md5 && git checkout . && tsc -p cybozulabs-md5`.
If my understanding is correct, git can't track case changes with `git add .`. like this http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Review by vvakame — APPROVED** [review]

**Pull request merged**
