### PR TITLE
Change order of index signature - express-session

### PR DESCRIPTION
**Pull request by bondz**
Before this change, I was getting

```ts
Duplicate string index signature.

[key: string]: any;
```

This fixes that.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by johnanisere — APPROVED** [review]

**Comment by amcasey** [comment]
@bondz I'm not sure I follow - are you saying that the order of interface member declarations determines whether or not you get a compilation error?

**Comment by bondz** [comment]
@amcasey yes. I get this error. 
image

But not when I change the order.

**Comment by bondz** [comment]
Hmm, actually even when I restart tsc with this change the error comes back so I don't think this completely fixes it.

When I run

```
tsc -w
```

I get that error. If I change the order in node_modules directly, the error goes away until I restart vsCode. I think this is a different problem due to the type resolution.

**Comment by amcasey** [comment]
@bondz FWIW, when I install `@types/connect-redis`, I don't see `@types/express-session` within it.  Same for the underlying packages.

**Comment by bondz** [comment]
@amcasey, I realise that now... Had to remove my `yarn.lock` file to get the dependencies to install correctly. Thanks :)

**Pull request closed without merging**
