### PR TITLE
[@types/hotwired__turbo] Add missing fields to FetchRequest, FetchResponse and FormSubmission

### PR DESCRIPTION
**Pull request by alexandergitter**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Turbo Manual](https://turbo.hotwired.dev/reference/drive#fetchrequest)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/hotwired__turbo/hotwired__turbo-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 74ebc7d60fa2ca3b87b6a92be5afd0863b7555f3
</p>

**Review by G-Rath — APPROVED** [review]
thanks!

**Comment by alexandergitter** [comment]
@G-Rath I just made another small change (I think `submitter` should be `HTMLButtonElement | HTMLInputElement` instead of `Array<HTMLButtonElement> | Array<HTMLInputElement>`).
Thank you for the quick review!

**Comment by G-Rath** [comment]
> I think submitter should be HTMLButtonElement | HTMLInputElement instead of Array<HTMLButtonElement> | Array<HTMLInputElement>

why do you think that? the docs to me indicate that it should be array (though the syntax is a little weird as it technically defines an array of tuples)

**Comment by alexandergitter** [comment]
I logged the event in some of my code and in that case `submitter` was only a single element.
Assuming it works similar to the native `submit` event, `submitter` indeed appears to be a single object only (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event#event_properties). I'm not sure what to make of the Turbo docs here.

**Review by G-Rath — APPROVED** [review]
sweet "I tested it locally" is good enough for me 😄

**Comment by alexandergitter** [comment]
Ready to merge

**Pull request merged**
