### PR TITLE
Ui grid huge update

### PR DESCRIPTION
**Pull request by btesser**
Depends on/duplicates #5303 along with numerous other changes.

Changes:
1.  Updated from rc to latest release (3.0.3)
2.  The following was added for every available module (Plugin specific API, ColumnDef, GridOptions, GridRow, Constants).
3.   Added docs for all existing interfaces.
4.   Fixed a few incorrect interfaces, updated interfaces to reflect latest version.
5.   Did some cleanup... Moved all plugins into their own modules

### CODE REVIEW

**Comment by vvakame** [comment]
oops, please resolve conflict.

**Comment by btesser** [comment]
Will do

**Comment by btesser** [comment]
@vvakame This PR is good to go now :)

**Comment by vvakame** [comment]
@btesser gread works! thanks mate.

**Pull request merged**
