### PR TITLE
[ckeditor] Fix index.d.ts is not a module

### PR DESCRIPTION
**Pull request by pierre-H**
@ondrejsevcik

Please fill in this template.
ondrejsevcik
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Hi guys, how can I remove myself of being an authored in every PR related to CKEditor?

**Comment by pierre-H** [comment]
@ondrejsevcik it's because I only find your name in the package so I mentioned you.

**Comment by minestarks** [comment]
@pierre-H please fix the failing tests before we can merge

**Comment by ondrejsevcik** [comment]
@pierre-H that's ok. I didn't notice you've mentioned me. I thought it's a bot message that I was receiving before. 

I must disappoint you, I'm no longer using CKEditor and I've lost a track what's happening with the API.

**Comment by minestarks** [comment]
@ondrejsevcik your name is in the index.d.ts, so the bot also auto-mentions you. You can submit a PR to remove your name if you wish. Or @pierre-H could you remove his name and replace it with yours, so that there's at least one author? Thanks!

**Comment by sandersn** [comment]
Thanks for your contribution. This PR has failing CI tests and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the master branch.

**Pull request closed without merging**
