### PR TITLE
[raphael] Fix typings and update for 2.3

### PR DESCRIPTION
**Pull request by blutorange**
* Updated typings for Raphael 2.3
* Replaced Function, object and any with more specific types where possible.
* Merged function overloads where possible.
* Added documentation to all types and methods, based on the [official documentation](https://dmitrybaranovskiy.github.io/raphael/reference.html).
* Added tests for the entire [documented API](https://dmitrybaranovskiy.github.io/raphael/reference.html).
    * There are a few places where the official documentation is obviously wrong, these parts have been modified accordingly.
* Removed all custom tslint-rules from tslint.json and fixed all linting errors.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://dmitrybaranovskiy.github.io/raphael/reference.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for a reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by orta** [comment]
@blutorange Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.


## Code Reviews

Because this PR edits the configuration file, it can be merged once it's reviewed by a DT maintainer.

🔔 @CheCoxshall - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43305,
  "author": "blutorange",
  "owners": [
    "CheCoxshall"
  ],
  "dangerLevel": "ScopedAndConfiguration",
  "headCommitAbbrOid": "fa48e6b",
  "headCommitOid": "fa48e6b50f3d16a2b6d3a0de9a41d0fcb0424213",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T21:30:51.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43305/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Well-liked by everyone",
  "anyPackageIsNew": false,
  "packages": [
    "raphael"
  ],
  "files": [
    {
      "filePath": "types/raphael/index.d.ts",
      "kind": "definition",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/raphael-tests.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-api.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-font.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-global.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-module.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-official.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-old.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/test/raphael-tests-plugin.ts",
      "kind": "test",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tsconfig.json",
      "kind": "package-meta",
      "package": "raphael"
    },
    {
      "filePath": "types/raphael/tslint.json",
      "kind": "package-meta",
      "package": "raphael"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
