### PR TITLE
chore(deps): Update dependency prettier to v2

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://prettier.io/blog/2020/03/21/2.0.0.html>

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

Should be probably reviewed for LF on the Windows OS (I could do this):
https://prettier.io/blog/2020/03/21/2.0.0.html#api
and the second pair of eyes

**Review by orta — COMMENTED** [review]
I'm good for this!

That said, I'd rather not get a bunch of needless changes in DT files which are using prettier, can we make sure the [`.prettierrc.json`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.prettierrc.json) makes the old defaults get set. 

I think that would then be: `arrowParens` to `"avoid"`, "trailingComma" to `"none"` - I think we're likely already set on the endOfLine through git - so I'm fine with leaving that to the new option

**Comment by ExE-Boss** [comment]
`trailingComma` is already `"all"` in **DefinitelyTyped**.

That leaves only `arrowParens`.

**Comment by orta** [comment]
Travis never reported back that it greened - so I'm cool with merging 👍

**Pull request merged**
