### PR TITLE
[react-mentions] add new types for 4.4.10

### PR DESCRIPTION
**Pull request by frunkad**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/react-mentions#configuration
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by gabritto — CHANGES_REQUESTED** [review]
It is preferred to have optional property types have `| undefined` to avoid unnecessary errors in a project where [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes) is `true`. Please add the `| undefined` back, unless the original JS library actually disallows setting those properties to `undefined`.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/react-mentions/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7589040c8351ff78e232b6e2810a765b1bce877c
</p>

**Comment by frunkad** [comment]
> It is preferred to have optional property types have `| undefined` to avoid unnecessary errors in a project where [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes) is `true`. Please add the `| undefined` back, unless the original JS library actually disallows setting those properties to `undefined`.

Have modified it - wasn't aware of this usecase - thanks!

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by frunkad** [comment]
Ready to merge

**Pull request merged**
