### PR TITLE
Add typings for Imgur API

### PR DESCRIPTION
**Pull request by lukewestby**
These typings represent the data models for the Imgur REST API. There is no official JS library for the API, but this may useful for TypeScripters working with the API directly.

### CODE REVIEW

**Comment by vvakame** [comment]
@lukewestby umm... https://www.npmjs.com/package/imgur-api is already exists.
js library is not exists?

**Comment by lukewestby** [comment]
@vvakame These types don't correspond directly to that package, nor any other. They are the types for the models that the REST API delivers. That being said, a new filename may be needed to avoid that confusion.

**Comment by vvakame** [comment]
yep, `imgur-rest-api` ? `imgur-api-model` ?

**Comment by lukewestby** [comment]
I was thinking `imgur-rest-api` as well, I'll push that change shortly. Thanks!

**Comment by vvakame** [comment]
@lukewestby thanks!

**Pull request merged**
