### PR TITLE
@types/node-forge: add namespace pem

### PR DESCRIPTION
**Pull request by booblin**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/digitalbazaar/forge/blob/master/lib/pem.js

### CODE REVIEW

**Comment by westy92** [comment]
@booblin could you please provide a link to the relevant node-forge docs for these additions?

**Comment by aozgaa** [comment]
@booblin please address the feedback, else we will close this issue in a week.

**Review by paulvanbrenk — CHANGES_REQUESTED** [review]
Please add a link to the documentation for this change.

**Comment by booblin** [comment]
@westy92 Thank you. Really, this method return array. Now types fixed.

**Comment by westy92** [comment]
@booblin thank you for the fix!  Could you please add some example usage to `node-forge-tests.ts` as a sanity check?

**Pull request merged**
