### PR TITLE
fix(react-router): match can be null

### PR DESCRIPTION
**Pull request by bradleyayers**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reacttraining.com/react-router/web/api/match/null-matches
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by bradleyayers** [comment]
Interested to hear everyone's opinion about this breaking change, and if there's any objections to it. The types of breakages to expect can be seen in the travis logs.

**Comment by bradleyayers** [comment]
@johnnyreilly I've updated the tests.

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by rmazing** [comment]
This one is really an enormous change, causing our build to crash. Why is the package version not increased? How can it still be 4.4.2?

**Comment by bradleyayers** [comment]
@rmazing I can’t explain why it would still be 4.4.2, I would have expected it to bump the patch number. What new version do you think would be appropriate for this change?

**Comment by johnnyreilly** [comment]
I'm sorry - DT does not support semver. Details here: https://blog.johnnyreilly.com/2018/09/ivan-drago-and-definitely-typed.html

**Comment by Grmiade** [comment]
> A <Route> that uses the children prop will call its children function even when the route’s path does not match the current location. When this is the case, the match will be null. Being able to render a <Route>'s contents when it does match can be useful, but certain challenges arise from this situation.

I think we should only accept a null match in the children prop according to the react-router doc :/
What do you think?

Maybe?
```
export interface RouteComponentProps<
  Params extends { [K in keyof Params]?: string } = {},
  C extends StaticContext = StaticContext,
  S = H.LocationState
> {
  history: H.History
  location: H.Location<S>
  match: match<Params>
  staticContext?: C
}

interface RouteChildrenProps<
  Params extends { [K in keyof Params]?: string } = {},
  S = H.LocationState
> {
  history: H.History
  location: H.Location<S>
  match: match<Params> | null
}

export interface RouteProps {
  location?: H.Location
  component?: React.ComponentType<RouteComponentProps<any>> | React.ComponentType<any>
  render?: ((props: RouteComponentProps<any>) => React.ReactNode)
  children?: ((props: RouteChildrenProps<any>) => React.ReactNode) | React.ReactNode
  path?: string | string[]
  exact?: boolean
  sensitive?: boolean
  strict?: boolean
}
```

**Comment by johnnyreilly** [comment]
Sorry I'm on my phone; hard to read. If this approach works then yes of course; do feel free to submit a PR with tests!

**Comment by bradleyayers** [comment]
@Grmiade good catch and suggestion, thank-you! I've raised https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31278 with your suggestion and updated tests.

**Pull request merged**
