### PR TITLE
Add support for using React Bootstrap in glbal setup

### PR DESCRIPTION
**Pull request by kant2002**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vsiao** [comment]
I defer to DT maintainers to decide if this is following best practices.

**Comment by mhegazy** [comment]
So why not keep it as a module and use [module augmentation](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#augmenting-globalmodule-scope-from-modules) if you want to augment it?

**Comment by kant2002** [comment]
@mhegazy  I don't want augment anything, I want just place code in the <script> tag and use library. I have rather small application and use very simple toling setup, no webpack/requirejs/systemjs etc.

**Comment by mhegazy** [comment]
thanks for the explanation.

**Pull request merged**
