### PR TITLE
use module instead of namespace for jest

### LINKED ISSUE #25480: JSDocs @typedef {typeof import()} doesn't work with @ts-check pragma (throws "not a module")
**TypeScript Version:**  3.0.0-dev.201xxxxx and 2.9.2

**Search Terms:** 

- JSDoc
- typedef
- import
- ts-check

**Code**

Having `jest` and `@types/jest` installed this snippet...

```ts
/** @typedef {typeof import('jest')} */

/** @type jest.ProjectConfig */
const config = {
  collectCoverage: true,
  coverageReporters: ['text'],
  transform: {
    '^.+\\.(ts?|tsx?)$': '<rootDir>/node_modules/ts-jest/preprocessor.js'
  },
  testRegex: '(/tests/.*)\\.unit\\.(ts?|tsx?)$',
  testPathIgnorePatterns: ['/node_modules/', '/tests/helper/'],
  moduleFileExtensions: ['ts', 'tsx', 'json', 'js']
};

module.exports = config;
```

...seems to correctly use `ProjectConfig`. But when I add `// @ts-check` in the first line I get an error.

**Expected behavior:**

No error. Just more type checks. (E.g. `// @ts-check` I could set `collectCoverage: 'foo'` without an error.)

**Actual behavior:**

`/** @typedef {typeof import('jest')} */`: `File '../node_ modules/@types/jest/index.d.ts' is not a module.`

**Related Issues:** 

- For the general importing (without `// @ts-check`): https://github.com/Microsoft/TypeScript/issues/14377

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Microsoft/TypeScript/issues/25480
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

--- 

This should fix https://github.com/Microsoft/TypeScript/issues/25480. But I never switched from a namespace to a module before. I don't know, if this will break something 🤔

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Hi @mhegazy , thank you for the quick help. I tried your suggestion and it mostly seems to work, but in a quick local test I'm not able to access `jest` globally anymore. It throws `refers to a umd global but the current file is a module. consider adding an import instead`. I'm not sure, but I think I would need to add `jest` to `declare global` somehow. Is this even possible? I found https://github.com/Microsoft/TypeScript/issues/14051 which looks like it is what I need, but it is still open.

**Comment by donaldpipowitch** [comment]
About the `Cannot find namespace 'jasmine'.` errors... I'll check if I can export jasmine as well.

**Comment by donaldpipowitch** [comment]
Not sure if this pull request is still needed. At least for my use case I found a way: https://github.com/Microsoft/TypeScript/issues/25480#issuecomment-403367708

**Comment by jcreamer898** [comment]
I'm actually running into an issue with this right now...

We're working on a CLI wrapper around some internal tooling.

We installed `@types/jest` and `jest` as usual, which is allowing our `src/__tests__` to work correctly.

What's NOT working is when we try to import `jest` as a module to call it as a node module.

```ts
import jest from "jest";
```

We're getting `node_modules/@types/jest/index.d.ts' is not a module.` Which, I suppose makes sense since the definition files don't actually export anything, but simply declare globals?

Would love any guidance here @donaldpipowitch @mhegazy. Thanks!

**Comment by donaldpipowitch** [comment]
Hi @jcreamer898 , I remember that I tried to fix this, but felt into a rabbit hole, because I couldn't export Jest correctly :( I haven't found the correct way back then.

**Comment by adamyonk** [comment]
@jcreamer898 did you ever figure out what the deal was with that? Having the exact same issue.

**Pull request closed without merging**
