### PR TITLE
Upgraded XRegExp to 4.3.0

### PR DESCRIPTION
**Pull request by pristinesource**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/slevithan/xregexp/tree/v4.3.0
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by pristinesource** [comment]
This is a complete re-write of the definitions (and tests) for v4.3.0.

**Comment by jfahrenkrug** [comment]
@pristinesource Great work! I love all the comments! I recently added TS definitions to the official xregexp repo, see https://github.com/slevithan/xregexp/issues/284
Would you mind opening a PR there as well so we can improve the TS definitions there too? The defs are not yet bundled with 4.3.0, but should be included in the next release. When that happens we should remove the defs from DefinitelyTyped.

**Comment by orta** [comment]
Excellent work on the docs!

**Review by orta — APPROVED** [review]

**Comment by slevithan** [comment]
The defs are bundled with XRegExp 4.4.0.

**Pull request merged**
