### PR TITLE
Add type declarations for UXP 7.1

### PR DESCRIPTION
**Pull request by Apoorva2405**
Add type declarations for UXP 7.1

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Hi @Apoorva2405 and @apsharma24, are you affiliated with Adobe or is this a community effort? Were these types auto-generated from something, copied from somewhere, or written manually (or a combination)?

**Comment by Apoorva2405** [comment]
@andrewbranch Yes, I am part of UXP team from Adobe.I have written a script to generate these types from UXP JS files.

- First, I am using [tsd-jsdoc](https://www.npmjs.com/package/tsd-jsdoc) to generate dts from our JSDoc annotated source files
- Next, based on the usage of the modules and how some of the modules are imported, I am adding post processing in the script for different type of modules (global modules, core modules and modules requiring library import).

**Comment by Apoorva2405** [comment]
@andrewbranch Any update/additional action needed on the above request? Also, wanted to check how we can add known issues to the repo so they can be published on npm org

**Comment by andrewbranch** [comment]
DefinitelyTyped exists so that the community can collaborate on making type definitions. In your case, I think it makes much more sense to do the development and publishing of these types within internal Adobe systems. On DT, changes have to be reviewed and approved by other humans in order to be merged, but when you have thousands of lines of auto-generated definitions for a product that you own, there is no way anyone can give a meaningful review. This review process will only slow you down, while being a burden both for you and for DT maintainers who will be pinged to review unreviewable PRs. I strongly recommend that you publish these types without going through DefinitelyTyped.

**Comment by rbuckton** [comment]
I'm a bit concerned that someone has already [reserved `uxp` on NPM](https://www.npmjs.com/package/uxp), and the types package for Adobe UXP is unrelated to that package.

**Comment by jardicc** [comment]
@rbuckton This is fine. That is my own package reserved for these types. UXP is "special" it does not live in NPM but instead it is imported from Photoshop, InDesign, Experience Designer. But for convenience types are with DT.

**Comment by jardicc** [comment]
@andrewbranch yes... that was my suggestion too after I experienced the process with `@types/photoshop`. Maybe some adobe related scope could do the job.

**Comment by peterblazejewicz** [comment]
note: `Adobe UXP` should not be an owner, being an organization.
I'd say, `Adobe UXP` should host those types and have a package like `@uxp-community/typings` or get Adobe sanction and use `@adobe/usx-typings`, as there is existing precedence:
https://www.npmjs.com/package/@adobe/uxp-optimized
Otherwise, for me, this approach looks like squatting a space for `uxp`, `photoshop`, `indesign`, instead doing it right.
Check the Figma, for `figma.ui.*` TS support:
https://github.com/figma/plugin-typings
`@uxp-community` would inform me clearly, who's behind the package/module like code.
thansk!

**Comment by peterblazejewicz** [comment]
@Apoorva2405 thanks for taking all this into consideration, especially this is somehow a delicate topic IMO (how to approach problems in the OOS community)! Appreciated!

**Comment by andrewbranch** [comment]
@Apoorva2405 is it ok to close this now?

**Pull request closed without merging**
