### PR TITLE
removing myself as a contributor to @types/Parse - too many notifications

### PR DESCRIPTION
**Pull request by REPTILEHAUS**
For attention of @ullisenmedia @dpoetzsch @flavionegrao @wesleygrimes @JeromeDeLeon etc at @types/Parse

### CODE REVIEW

**Review by RaschidJFR — APPROVED** [review]

**Review by amcasey — APPROVED** [review]
You probably didn't cause the perf regression 😆

**Review by JeromeDeLeon — APPROVED** [review]

**Comment by JeromeDeLeon** [comment]
Ready to merge

**Comment by REPTILEHAUS** [comment]
Hi @JeromeDeLeon @RaschidJFR, I still get bombarded with notifications even though I am no longer a maintainer, how do I silence this repo ?

**Comment by JeromeDeLeon** [comment]
What PR are you pertaining to? because you might be included as one of the reviewers or the repo that they fork was outdated and so you get a notification. Let's wait until newer PR comes in and see if you still get the notification.

**Comment by JeromeDeLeon** [comment]
The latest notif I got came from this #47699 and upon looking at the files, your name was mentioned and listed on the file itself.

**Comment by RaschidJFR** [comment]
@REPTILEHAUS you will still get notified from old PR which use to have your name. You'll have to wait a bit for those PRs to be merged or die (propagation in such big repos is slow). Not the best solution but you may want to mute those threads manually for now.

**Pull request merged**
