### PR TITLE
fix(mime): fix module exports and constructor

### PR DESCRIPTION
**Pull request by peterblazejewicz**
As aftermath of comments from: #61509
- constructor takes variadic args
- exports should be CJS exports

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Comment by WilliamJJXue** [comment]
this merged raises a new bug in my program



node_modules/@types/mime/Mime.d.ts:1:13 - error TS1005: '=' expected.

1 import type { TypeMap } from './index';
              ~

node_modules/@types/mime/Mime.d.ts:1:30 - error TS1005: ';' expected.

1 import type { TypeMap } from './index';

**Comment by peterblazejewicz** [comment]
@WilliamJJXue sorry for the problem. What's your setup? (CJS/ESM/etc). There were issues with mime declaration doing different exports than native module. Hence we've changed couple of things on major version (@3 or newer only)

**Comment by WilliamJJXue** [comment]
@peterblazejewicz my program is a "nest.js" server;
When I build the program, NPM automatically gets types / mime 3.0.1;
I checked the "package-lock.json" file and found that the reference chain is as follows:

```
"@types/express": {
      "version": "4.17.13",
      "resolved": "https://registry.npmmirror.com/@types/express/-/express-4.17.13.tgz",
      "integrity": "sha512-6bSZTPaTIACxn48l50SR+axgrqm6qXFIxrdAKaG6PaJk3+zuUr35hBlgT7vOmJcum+OEaIBLtHV/qloEAFITeA==",
      "dev": true,
      "requires": {
        "@types/body-parser": "*",
        "@types/express-serve-static-core": "^4.17.18",
        "@types/qs": "*",
        "@types/serve-static": "*"
      }
    },
...
"@types/serve-static": {
      "version": "1.13.10",
      "resolved": "https://registry.npmmirror.com/@types/serve-static/-/serve-static-1.13.10.tgz",
      "integrity": "sha512-nCkHGI4w7ZgAdNkrEu0bv+4xNV/XDqW+DydknebMOQwkpDGx8G+HTlj7R7ABI8i8nKxVw0wtKPi1D+lPOkh4YQ==",
      "dev": true,
      "requires": {
        "@types/mime": "^1",
        "@types/node": "*"
      }
    },

```

**Comment by lmbai** [comment]
same issue facing here

**Comment by peterblazejewicz** [comment]
folks, how are you using this module? Seems to be CJS (old school) kind of the module,
so the useage under default NestJS setup (no 'esModuleInterop' prop), requires:
```ts
import mime = require('mime');
// or
import * as mime from 'mime';
```
as this is not an ESM module, there are no file imports modification in the definition AFAIK (so no imports like `./index.js` in dt files)

**Comment by andrewbranch** [comment]
That error message sounds like @WilliamJJXue is using a super old version of TypeScript that doesn’t support type-only imports.

**Pull request merged**
