### PR TITLE
fix(cheerio): mark properties on `Element` as `null` or optional

### PR DESCRIPTION
**Pull request by G-Rath**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

-----

These properties can be `null`.

### CODE REVIEW

**Review by rbuckton — APPROVED** [review]

**Comment by G-Rath** [comment]
Ready to merge

**Comment by jedireza** [comment]
@G-Rath This is breaking the build in a project of mine.

```
2339: Property 'children' does not exist on type 'Element'.  Property 'children' does not exist on type 'TextElement'.
```

To work around this I have to use a type assertion.

```ts
const selector = $('script');
$schemas.each((_, el) => {
   // ...
   (el as cheerio.TagElement).children...
   // ...
});
```

**Comment by G-Rath** [comment]
@jedireza that's to be expected, as until now the types have not been accurate (they're still not, but this is a step towards that) :)

**Comment by jedireza** [comment]
Just found another:

```
Type error: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.
```

**Comment by jedireza** [comment]
If I inspect the `el` variables at runtime they do indeed have these attributes and the expected data inside them.

**Comment by G-Rath** [comment]
They only have those properties when they're of type `tag` - if you inspect an object of type `text` you'll find they don't have that property.

**Comment by jedireza** [comment]
I see. So in our loops (at runtime) we need to duck type check that the element has the properties we expect it to have. 👍 Thanks.

**Comment by G-Rath** [comment]
Exactly. I was bitten by this when writing my scraper for aws - in *most* cases you'll have `tag` elements, and so everything will work fine right up until you've got a `text` and then everything explodes on you 😅

This is what I use in my project:

```
const selectTagElements = (elements: cheerio.Element[]): cheerio.TagElement[] =>
  elements.filter((ele): ele is cheerio.TagElement => ele.type === 'tag');

// or just directly;
// .filter((ele): ele is cheerio.TagElement => ele.type === 'tag')
```

**Pull request merged**
