### PR TITLE
[readme] Added FAQ: how long until PR merged?

### PR DESCRIPTION
**Pull request by NaridaL**
This is by far the question which gets asked the most on the DT gitter, so I thought it would be a good idea to add it to the FAQ. I don't really have any authority to answer the question, so the answer is mostly a placeholder at this point; it would be better to have an official answer. @andy-ms would you rather not be tagged after a week?

### CODE REVIEW

**Comment by minestarks** [comment]
Thanks for tackling the question. Tagging @andy-ms probably isn't scalable. We generally take turns managing the PRs. 

The fact is PRs can take anywhere from a few hours to several weeks to get approved, and that's usually a function of how much discussion or disagreement it generated. Moreover, the maintainers aren't familiar with every single package out there, so the more complicated or the larger the change is, the more time it's going to take to get reviewed. The easier you make it for humans to review, and the more you build consensus, the faster it'll get approved.

My best _scalable_ advice if you're updating a package is to get the authors' attention (sometimes @dt-bot fails to tag them, so double check that they're tagged) and have them approve the PR. Gives us more confidence that the change is good.

I'm aware I'm not answering the question directly but like any project on GitHub this one is managed by humans and is subject to human factors :/

**Comment by NaridaL** [comment]
The question comes up for example when someone has added new typings, automatic checks have passed, and then nothing has happened for 2 days. I.e. no active discussion, and it's not clear whether this is normal. I was assuming that was just due to someone not getting around to it yet, not that there was much internal discussion going on (or am I mistaken).

dt-bot seems to tag inactive PRs with Merge:YSYL (you snooze, you lose?!) after 5 days, I think making note of that should be answer enough.

**Comment by NaridaL** [comment]
@RyanCavanaugh I didn't find a dedicated issue tracker for the typescript-bot:
It's measuring the 5days inactivity wrong, (e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19027#issuecomment-322814117 message after 13h). I think it's using the first commit date instead of the PR creating date.

**Comment by RyanCavanaugh** [comment]
@NaridaL yep Andy is looking into it

**Comment by RyanCavanaugh** [comment]
FWIW the policy applied by the bot is at https://github.com/RyanCavanaugh/dt-mergebot/blob/master/policy.md - this is still work in progress which is why we haven't changed official documentation yet

**Comment by NaridaL** [comment]
@RyanCavanaugh Ok. 

Do you want to merge this PR as-is (it matches what I've observed) or close this and wait until the bot is updated?

**Comment by RyanCavanaugh** [comment]
Here's what I'd like the answer to say:

> It depends, but most pull requests will be merged within a week. PRs that have been approved by an author listed in the definition's header are usually merged more quickly; PRs for new definitions will take more time as they require more review from maintainers. Each PR is reviewed by a TypeScript or DefinitelyTyped team member before being merged, so please be patient as human factors may cause delays. Check the [PR Burndown Board](https://github.com/DefinitelyTyped/DefinitelyTyped/projects/3?card_filter_query=is%3Aopen) to see progress as maintainers work through the open PRs.

> #### My PR is merged; when will the `@types` NPM package be updated?
> NPM packages should update within a few hours. If it's been more than 24 hours, ping @RyanCavanaugh and @andy-ms on the PR to investigate.

**Comment by minestarks** [comment]
Could you address my comment and I'll merge. Again thanks for asking the hard questions ;)

**Comment by NaridaL** [comment]
My bad, sorry for the delay!

**Pull request merged**
