### PR TITLE
[@types/mongoose]: add strict: "throw" to update

### PR DESCRIPTION
**Pull request by andreialecu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mongoosejs.com/docs/guide.html#strict

- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

Also did minor linting of the other places where `strict` is allowed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongoose ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongoose@latest/))
was missing the following properties:
1. modelSchemas
1. options
1. cast
1. driver
1. deleteModel

<details>
<summary>as well as these 7 other properties...</summary>
<p>ObjectId, Decimal128, Mixed, Number, now, CastError, SchemaTypeOptions</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7f8a8665111600fb90c5e5c2b8f85c6f782176b6
</p>

**Comment by elibarzilay** [comment]
@andamanastireanu: is this ready, or should it wait for a review?

(Ping @horiuchi @lukasz-zak @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik @cl3dson @richardsimko @ith @jeremyben @tHBp)

**Comment by andreialecu** [comment]
It's ready. (I think you pinged the wrong person btw)

I have another PR that is ready. Seems mongoose type contributors are not very active these days.

**Review by jeremyben — APPROVED** [review]

**Comment by andreialecu** [comment]
Ready to merge

**Pull request merged**
