### PR TITLE
lodash: add type guards for _.isXxx functions

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors(@bczengel @chrootsu). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
I just saw a little, but looks good to me. ;)

**Comment by chrootsu** [comment]
@vvakame Yep, looks good to me too =)
:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
