### PR TITLE
[react-native] Remove Image width and height props

### PR DESCRIPTION
**Pull request by dimonka83**
Revert #30834 maybe because facebook/react-native#28151
I can't find a commit to verify this for sure
But on versions 0.64.3 and 0.67.3 I won't be able to reproduce the situation described here https://medium.com/@adamjacobb/react-native-performance-images-adf5843e120
Everything works fine purely on styles, without additional properties

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Still gone: https://github.com/facebook/react-native/blob/v0.67.3/Libraries/Image/ImageProps.js

**Comment by dimonka83** [comment]
> Still gone

What do mean? There is no width and height in ImageProps, only in ImageSource and ImageStyleProp

**Comment by eps1lon** [comment]
> What do mean?

That these props are still gone since the react-native PR was merged. The PR as documentation wasn't sufficient since these props may have been re-introduced in the meantime. But they didn't so this is good to go.

**Comment by dimonka83** [comment]
Ready to merge

**Pull request merged**
