### PR TITLE
ember__test-helpers - update click signature

### PR DESCRIPTION
**Pull request by azhiv**
Add optional parameter named 'options' to click, double-click and tap
helpers because these parameters are present in the original add-on.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/emberjs/ember-test-helpers/blob/9d6dc6c35b167650edaf0700ba9d1704e24d14b8/addon-test-support/%40ember/test-helpers/dom/click.ts#L85
https://github.com/emberjs/ember-test-helpers/blob/9d6dc6c35b167650edaf0700ba9d1704e24d14b8/addon-test-support/%40ember/test-helpers/dom/double-click.ts#L86
https://github.com/emberjs/ember-test-helpers/blob/9d6dc6c35b167650edaf0700ba9d1704e24d14b8/addon-test-support/%40ember/test-helpers/dom/tap.ts#L52

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember__test-helpers ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember__test-helpers@latest/))
was missing the following properties:
1. name
1. init
1. included
1. treeForAddonTestSupport
1. treeForVendor
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 03a7b1f2085ef193b6450cf2c41f6d81497b3e55
</p>

**Review by chriskrycho — APPROVED** [review]
This looks good! In the future, though, please link to [the API docs](https://github.com/emberjs/ember-test-helpers/blob/9d6dc6c35b167650edaf0700ba9d1704e24d14b8/API.md#click) instead of the implementation, @azhiv! The API docs *are* public commitments; the types *currently* are not!

**Comment by azhiv** [comment]
@chriskrycho Thank you! BTW, I cannot figure out why the build fails. It complains about using void as return type in functions I didn't touch. Any ideas?

**Comment by azhiv** [comment]
Ready to merge

**Pull request merged**
