### PR TITLE
[node] Add url.URL and url.URLSearchParams introduced in NodeJs 7.5.0

### PR DESCRIPTION
**Pull request by Flarna**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url.URL](https://nodejs.org/dist/latest-v7.x/docs/api/url.html#url_class_url), [url.URLSearchParams](https://nodejs.org/dist/latest-v7.x/docs/api/url.html#url_class_urlsearchparams)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by Flarna** [comment]
Corrected test fail in node-zookeeper-client by switching to lib es6.
There are still a lot other but unrelated test fails either because lint complains about trailing whitespace or users of lodash not using typescript 2.1 (see #14384 and #14288).

**Comment by aozgaa** [comment]
Have you tried pulling from master?

**Comment by Flarna** [comment]
at the time the test was executed my changes were on top of master. Meanwhile there are a few commits but nothing related to the whitespace/Typescript 2.1 errors seen.
see #14557 for another change in node which shows the same errors.
Looks like CI allows errors to leak somehow...

If needed I can adapt the effected modules to fix the CI but the changes are not really related to my PR which would be quite confusing in my opinion.

**Comment by aozgaa** [comment]
Ideally we would have a separate PR that fixes travis issues with `node/` as these seem to exist independent of your PR or #14489

**Comment by Flarna** [comment]
I have done the changes in this PR otherwise it could happen to end up in a loop...
CI is green - now - :o)

**Comment by Flarna** [comment]
Nobody interested in this PR?

**Comment by Flarna** [comment]
merge once more from master.
@andy-ms, @mhegazy, @bowdenk7 Is there anything left to get this merged? Or has Node reached end of life already?

**Comment by micmro** [comment]
Hi @Flarna  & @minestarks .

I started to see issues based on this PR (`@types/node` `7.0.7`) caused by the use of ES6 only features (`Iterable`, `Iterator` and `Symbol.iterator`).

Since `@types/node` is a dependency of e.g. `@types/grunt` a front-end project that targets ES5 will fail to build.

**Comment by Flarna** [comment]
@micmro You only have to set `es6` in tsconfig.json for `lib` or just add `es2015.iterable`. `target` can still be set to `es5`.

**Comment by micmro** [comment]
Thanks @Flarna.
I agree, from a pure node perspective it is the right thing to use. I was just wondering, from a eco-system perspective, with the nodes typing as one of its core pieces, if it is possible to add these in a non-breaking fashion? (see e.g. #15083)

**Comment by Flarna** [comment]
At least I have no idea how to represent ES6 functionality using ES5 compatible syntax.
So I think the alternative would be to stop adding new APIs to typings.

**Comment by micmro** [comment]
Perhaps you could mock their interface. e.g.:

```
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}
```
source: https://basarat.gitbooks.io/typescript/content/docs/iterators.html

This is used for the `IterableIterator` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a5c041c10035b9d1b349f037ecdc4e018ff602a8/node/index.d.ts#L496).

**Comment by Flarna** [comment]
Why should we start duplicating stuff in node (and maybe a lot other) typings which is already contained in lib.es2015.iterable.d.ts and lib.es6.d.ts part of typescript?
Who takes care that this stays in sync?
Maybe we will even get duplication issues then for users using lib.es6.d.ts already now.

The only thing needed to be done by consumers of latest and greatest node typings is to configure the correct libs to use in there tsconfig.json.

**Comment by micmro** [comment]
You have a point, I just think requiring to set the libs makes using TypeScript harder to understand and less user-friendly, in particular if `@types/node` is a transient dependency and you experience build-failures out of nothing.

**Comment by Flarna** [comment]
If someone uses latest and greatest peers she should not wonder that things break out of nothing every now and then. I faced such issues in my projects several times...
Changing the major version instead the patch version would not help in #15083 as they selected "^7.0.0" so only changing to something like 8.x.y would help which is clearly wrong.

By the way, have you seen the last part of [https://basarat.gitbooks.io/typescript/content/docs/iterators.html](https://basarat.gitbooks.io/typescript/content/docs/iterators.html)? There it's clearly stated to select target es5 but lib es6. So at least I'm not alone with this tip.

Anyhow, feel free to raise a PR to introduce hand crafted Iterator interface or to remove the relevant APIs from typings again (or even the complete commit). My feeling is that it is not correct to go this way.

**Pull request merged**
