### PR TITLE
[react-table] Added missing canSort and canFilter options.

### PR DESCRIPTION
**Pull request by vdeantoni**
Related to: https://github.com/tannerlinsley/react-table/pull/1568

### CODE REVIEW

**Review by ggascoigne — COMMENTED** [review]
I'm sorry, but I think that this is wrong.

The UserSomethingColumnOptions interfaces are input types, the UserSomethingColumnProps are output ones.

both canSort and canFilter are output values and already exist on the respective props.  You can see from the table code that they are output only, setting them has no effect.  They should not be added to the Options types.

I think that it's pretty clear for the filters https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useFilters.js#L164 and I think that the same thing is going on with sorting https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useSortBy.js#L239 - though I'll admit that that's a bit tricker to reason about quickly.

**Comment by vdeantoni** [comment]
Thanks for the reply, but something is off, I'll put together a codesandbox to show what I mean. Give me a few minutes.

**Comment by vdeantoni** [comment]
I changed the [Sorting example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting) to illustrate why I think canSort should be added as an option.

Check out this sandbox: https://codesandbox.io/s/brave-jepsen-bj149?file=/src/App.js

The progress column definition is the only thing that changed:
```
            Header: "Profile Progress",
            id: "progress",
            // canSort:true
            defaultCanSort: true
          }
```

With this, the header is not clickable, but as soon as you replace defaultCanSort with canSort it becomes clickable.

**Comment by ggascoigne** [comment]
As far as I can tell defaultCanSort appears to be being overridden by the state of the accessor and so if there's a valid one it will allow sorting.

In my tests, changing canSort on a column does nothing - and that is in line with the docs and what I saw of the code.  It's not an input value.  And while I can see that your codesandbox doesn't allow sorting, I'm unable to duplicate it myself.

All in all, yes there might be something funky here, but if there is it's in react-table and should probably be bugged there. As far as I can tell, the types are correct on this.  FYI I tested with react-table 7.6.0.

**Pull request closed without merging**
