### PR TITLE
React updates

### LINKED ISSUE #3855: react-tests.ts
If state is static in line 327 (react-tests.ts) it cannot be accessed in React.
At least state is null unless I remove the static modifer - perhaps I'm doing it wrong,
can you verify the example runs?

Line 338 can be omitted as this is handled by the compiler.

-- Cheers

### PR DESCRIPTION
**Pull request by vsiao**
See individual commits for details. Highlights:
- Fixes bad state initializers in tests (closes #3855)
- Added: `React.ShallowRenderer` for [shallow rendering](http://facebook.github.io/react/docs/test-utils.html#shallow-rendering)
- Remove DOM API interfaces (`SVGLength`, `SVGTransformList`, etc) from `React.SVGAttributes` and use `number` or `string` where applicable because react stringifies all values before calling `node.setAttribute` anyway.

cc @pspeter3 @jbrantly

### CODE REVIEW

**Comment by pspeter3** [comment]
Looks good to me! Thanks for following up!

**Comment by duncanmak** [comment]
Yeah, I ran into this problem this weekend. Replacing `SVGLength` with `number | string` is definitely needed for these definitions to work. 

+1

**Comment by jbrantly** [comment]
+1 from me

**Comment by vsiao** [comment]
cc @vvakame @johnnyreilly

**Comment by johnnyreilly** [comment]
Well done!

**Pull request merged**
