### PR TITLE
Uikit support modal options

### PR DESCRIPTION
**Pull request by s0x**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

~~If adding a new definition:~~
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://getuikit.com/docs/modal.html>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by giovannicandido — APPROVED** [review]
Nice

**Comment by s0x** [comment]
Sorry for the rebase! Just needed to fix the author information

**Comment by giovannicandido** [comment]
Ok.
Do I need to approve again?
I guess not.

**Comment by s0x** [comment]
Oh well, they changed to master again #13233. Do I need to make a new pull request now or simply edit the existing one?

**Comment by s0x** [comment]
@andy-ms: Could you give us a hint how to proceed?

**Comment by andy-ms** [comment]
I'll merge this now. We'll do a merge from `types-2.0` to `master` soon enough.

**Pull request merged**
