### PR TITLE
fix(pg): add missing default configuration option

### PR DESCRIPTION
**Pull request by stuft2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/brianc/node-postgres/pull/943
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by stuft2** [comment]
Looks like this option was incorrectly specified in the types before, and it was rightly removed. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63690

**Review by HoldYourWaffle — COMMENTED** [review]
Oh wow, double oversight. Makes total sense that a non-overridable "default option" should still be in the default options... (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63690#pullrequestreview-1227235098)

If you add this "new" option to the tests I'll approve this, thanks!

**Comment by HoldYourWaffle** [comment]
@stuft2 If you add this option to the tests I'll approve it :)

**Comment by stuft2** [comment]
Sorry, I got held up with other work the past week. I think I have the tests written but I'll finish it up this week. 👍🏻

**Review by rbuckton — APPROVED** [review]

**Comment by stuft2** [comment]
Ready to merge

**Pull request merged**
