### PR TITLE
angularjs: update $compile specs to latest angular 1

### PR DESCRIPTION
**Pull request by kevinmerckx**

### CODE REVIEW

**Comment by andy-ms** [comment]
Rebase onto the latest `master`. This file is `angularjs/index.d.ts` now.

**Comment by andy-ms** [comment]
@kevinmerckx Please make a new pull request if you still want to do this.

**Comment by kevinmerckx** [comment]
@andy-ms Should I change anything in order to get it accepted?

**Comment by andy-ms** [comment]
Assuming this works just as well with the latest `angular/index.d.ts` as it did for `angularjs/angular.d.ts`, you should be able to make the same changes.

**Pull request closed without merging**
