### PR TITLE
Make RedisStore a class and expose RedisStoreOptions in rate-limit-redis

### PR DESCRIPTION
**Pull request by austin-beer**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/rate-limit-redis. Rate Limit Redis is used like a class with "new" and implements a TypeScript interface, so it should be declared as a class. This allows users to declare the type of the variable returned from "new RedisStore({})".
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by austin-beer** [comment]
I would like to wait until another owner has a chance to review and approve this PR before merging it, since it involves some refactoring. Thanks!

**Comment by dotconnor** [comment]
How are these types any different from before?

**Comment by austin-beer** [comment]
`RedisStore` was being declared as a variable. Variables can't be used as types in TypeScript. This code:

```
import RedisStore from 'rate-limit-redis';
const store: RedisStore = new RedisStore();
```

generates the following error:

```
error TS2749: 'RedisStore' refers to a value, but is being used as a type here.
```

**Comment by dotconnor** [comment]
You can just import the Store interface exported from `express-rate-limit`.

```typescript
import { Store } from "express-rate-limt";
import RedisStore from 'rate-limit-redis';
const store: Store = new RedisStore();
```

Another option is to use `ReturnType` with the `typeof` operator.

```typescript
import RedisStore from 'rate-limit-redis';
type Store = ReturnType<typeof RedisStore>;
const store: Store = new RedisStore();
```

**Comment by austin-beer** [comment]
Okay, good to know. The first option works for me.

The second option results in the following error.
```
Type 'new (options?: RedisStoreOptions | undefined) => Store' does not satisfy the constraint '(...args: any) => any'.
  Type 'new (options?: RedisStoreOptions | undefined) => Store' provides no match for the signature '(...args: any): any'.

type Store = ReturnType<typeof RedisStore>;
                        ~~~~~~~~~~~~~~~~~
```

It still seems counter-intuitive to me that you can call `new RedisStore()` but you can't directly reference the `RedisStore` type.

Also, my PR exports `RedisStoreOptions` as `RedisStore.RedisStoreOptions`. The current type definitions do not export it, so it can't be used separately. Someone may want to declare the options in a separate variable and set the variable's type.

**Comment by orta** [comment]
Hi folks, do we feel comfortable on merging this?

**Comment by austin-beer** [comment]
I feel comfortable merging it, but if @dotconnor does not then I don't think we should, and I will cancel the PR.

**Comment by DanielRosenwasser** [comment]
Are the options between this package and `express-rate-limit` actually related?

**Review by dotconnor — APPROVED** [review]

**Comment by dotconnor** [comment]
The options are unique to this package but the class definition is the same as the `Store` exported from `express-rate-limit`.

**Pull request merged**
