### PR TITLE
[xmlbuilder] Remove types

### LINKED ISSUE #24180: Unable to instantiate XMLElementOrXMLNode in xmlbuilder
- [x] I tried using the `@types/xmlbuilder` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @wallymathieu 

If you do not mention the authors the issue will be ignored.
``` 
import * as XMLBuilder from 'xmlbuilder';
export class someClass{
toXML(): XMLBuilder.XMLElementOrXMLNode {
        var root = XMLBuilder.create('root')
            .ele('xmlbuilder')
            .ele('repo', { 'type': 'git' }, 'git://github.com/oozcitak/xmlbuilder-js.git')
            .end({ pretty: true }); // This returns a string while it should return a XMLElementOrXMLNode object
        var xml: XMLBuilder.XMLElementOrXMLNode = new XMLBuilder.XMLElementOrXMLNode();
        xml.text(root);        
        return xml;
    }
}
```
When I execute this code ablove, I get a `he.XMLElementOrXMLNode is not a constructor` error. There just seems to be no way to instantiate the XMLElementOrXMLNode object.

### PR DESCRIPTION
**Pull request by L2jLiga**
Since 11.0.1 xmlbuilder has own typings: https://github.com/oozcitak/xmlbuilder-js/commit/cbe15c56fd85bee0d377769f9099654efeff4962

Closes #24180 as xmlbuilder is not part of DefinitelyTyped

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by L2jLiga** [comment]
Build should be fixed after https://github.com/Microsoft/types-publisher/pull/599 being merged

**Comment by GaikwadPratik** [comment]
I don't see any `Approve` button on GitHub UI, but I accept that this change can be merged. As stated in original commit message the `xmlbuilder-js` package has included typescript definitions since version v11.0.1

**Comment by wallymathieu** [comment]
Could it be due to the removal?

**Comment by L2jLiga** [comment]
Did you check "Changes" tab?

**Comment by GaikwadPratik** [comment]
I checked all tabs. My guess is it's because of _Travis CI_ failed? Perhaps someone from **Microsoft** can help. Let me ask the person who merged original PR. @sheetalkamat, can you please assist here? @wallymathieu or I would like to approve this PR. but both of us can not see _approve_ or _request changes_ buttons.

**Comment by wallymathieu** [comment]
It looks like I can approve, though I'm not sure about it (since I'm not following the discussion much). I would prefer if @oozcitak says yay or nay.

**Comment by oozcitak** [comment]
I probably need to fix the build error from my side. I will be away from a computer for two days though.

**Comment by oozcitak** [comment]
xmlbuilder is building without errors now. Meanwhile, the version number moved to `v12.0.0` and engine support to `node>=0.6`.

**Pull request closed without merging**
