### PR TITLE
Googlemaps label

### PR DESCRIPTION
**Pull request by pwelter34**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by cgwrench** [comment]
This looks good to me (although I'm not sure what the commit message is all about).

In addition to the `label` property on `Marker`, are there not also corresponding `getLabel()` and `setLabel()` methods? Could these be added in this pull request too?

**Comment by pwelter34** [comment]
good call, added those missing methods

**Comment by cgwrench** [comment]
:+1: Looks good, thanks.

**Comment by horiuchi** [comment]
@pwelter34 Thanks mate!
@cgwrench Thanks for review!

**Pull request merged**
