### PR TITLE
[next-auth], fix an incorrect parameter type in callbacks.session()

### PR DESCRIPTION
**Pull request by Devrama**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/server/routes/session.js#L31-L42>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by JuanM04** [comment]
You should use [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe3e8016d42f86fff607a7cd424ec3cabeea4b45/types/next-auth/client.d.ts#L5-L13) interface. Move it to `_utils`, give it a fancy name an export it

**Comment by Devrama** [comment]
Hi, @JuanM04 
I think [`Session` type in client.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe3e8016d42f86fff607a7cd424ec3cabeea4b45/types/next-auth/client.d.ts#L5-L13) is also incorrect.

`useSession()` in `/src/client/index.js` returns a type that is the result of `getSession()` if you see [here](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/client/index.js#L203-L219).
And then, `getSession()` internally calls `/session` endpoint in [here](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/client/index.js#L115).

`/session` endpoint returns GenericObject [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe3e8016d42f86fff607a7cd424ec3cabeea4b45/types/next-auth/index.d.ts#L108).

So,  there are two issues. And my PR only fixes #2 below.
1. `Session` type in `client.d.ts` is incorrect. The places where the `Session` type is used should be replaced by `GenericObject` type which is defined in `utils.d.ts`.
2. `session` parameter in `callback.session(session, user)` function has an incorrect type.

**Comment by JuanM04** [comment]
Hmm... This session always returns `expires` and info about the user, but can be customized...

The question here is how customizable is that session returned by `getSession()`. (Maybe @iaincollins knows)

**Comment by Devrama** [comment]
Yes, it's customizable.
The session object in [the link](https://next-auth.js.org/getting-started/client#example-session-object) is just an example.
The returned value in getSession is the object what you return [in here](https://next-auth.js.org/configuration/callbacks#session-callback).

For example, if you don't include `expires` in the return value [in here](https://next-auth.js.org/configuration/callbacks#session-callback). You don't get `expires` in getSession().

So, there are two kinda of Session types here.
- First one is..., session type that is used in the parameter of callbacks.session(session, user), and next-auth passes the Session type that has `expires` & `user`.
- Second one is... session type that a user returns as a return value in callbacks.session(session, user) in [here](https://next-auth.js.org/configuration/callbacks#session-callback). That's why it's type is GenericObject since we can return any form of object on our taste.  😄

**Comment by Devrama** [comment]
Never mind on `For example, if you don't include expires in the return value in here. You don't get expires in getSession().`

I see `expires & user` are always included in the response of getSession().

**Comment by JuanM04** [comment]
I see. For now, please use `Session & GenericObject` (being Session the one used in client). After that, I'll start working in something like [styled-components types](https://styled-components.com/docs/api#typescript) to save the schemas, session, and other things. What do you think?

**Comment by Devrama** [comment]
Sounds good. I fixed it. Please change the name of type if you think it's not fancy :-)

**Review by JuanM04 — APPROVED** [review]

**Comment by Devrama** [comment]
Ready to merge

**Pull request merged**
