### PR TITLE
MDX: Support React Server Components

### PR DESCRIPTION
**Pull request by pomber**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ChristianMurphy — CHANGES_REQUESTED** [review]
Heya @pomber! 👋 
Thanks for opening up a PR.

This appears to be related to https://github.com/mdx-js/mdx/issues/2242?
Next js style `Promise` based components aren't supported by MDX yet.
It also isn't officially a part of React yet either https://github.com/reactjs/rfcs/pull/229.

I don't think the types should specify features MDX itself doesn't support.

Could you expand a bit on why you want/need this change?
Are you interested in working on https://github.com/mdx-js/mdx/issues/2242?

**Comment by remcohaszing** [comment]
I see what you're trying to do here, but it's technically incorrect. Also it's bound to React, whereas the MDX types are framework agnostic. See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64885#discussioncomment-5426069

**Comment by wooorm** [comment]
Wouldn’t actual support in React’s types *include* this `Promise` support *inside* `JSX.Element`?
And if React supports it in types, it would be used here automatically?

**Comment by pomber** [comment]
What do you think would be the correct approach for the tools that already support RSC in the MDXComponents object? ([Next.js](https://github.com/vercel/next.js/blob/canary/examples/app-dir-mdx/mdx-components.tsx), [Contentlayer](https://github.com/contentlayerdev/contentlayer/blob/main/packages/next-contentlayer/src/hooks/useMDXComponent.ts), [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote/blob/main/src/rsc.tsx))

**Comment by wooorm** [comment]
Do you have documentation on this? As far as I understand, this is the latest: https://github.com/reactjs/rfcs/pull/229.

The correct approach to me would be for React to type the features they support 🤷‍♂️

I understand that frameworks have problems due to https://github.com/microsoft/TypeScript/issues/21699.
This seems to affect the projects you linked, too: https://github.com/microsoft/TypeScript/issues/53431.

I’m open to workarounds but I don’t think this is good.
If we add things here, we have wrong types for other frameworks.
To me that currently seems like a wrong tradeoff.

I just notice there’s a PR for TS btw: https://github.com/microsoft/TypeScript/pull/51328, which is specifically also mentioning `Promise<ReactNode>`

**Comment by remcohaszing** [comment]
As a workaround you create a helper function like this:

```ts
/**
 * A helper function to create a React server component in a type safe manner.
 */
export function rsc<P>(fn: (props: P) => ReactNode | Promise<ReactNode>): FC<P> {
  return fn as any
}

// Usage example
export const MyComponent = rsc(async (props) => {
  // …
})
```

**Comment by remcohaszing** [comment]
This is unblocked by https://github.com/microsoft/TypeScript/pull/51328, but the solution needs to leverage `ElementType`. It also needs to be backwards compatible. I don't know how TypeScript 5.1 handles backwards compatibility on this. Some investigation is needed.

**Comment by ChristianMurphy** [comment]
A little more context is given in the 5.1 beta announcement https://devblogs.microsoft.com/typescript/announcing-typescript-5-1-beta/#decoupled-type-checking-between-jsx-elements-and-jsx-tag-types
Backward compatibility still seems a bit open-ended.

**Comment by remcohaszing** [comment]
This was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65703

**Pull request closed without merging**
