### PR TITLE
[inline-style-prefixer] allowing ES2015 module syntax

### PR DESCRIPTION
**Pull request by ahz**
This allows "import * as InlineStylePrefixer from 'inline-style-prefixer';" syntax

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@ahz Please add the test

**Comment by minestarks** [comment]
Sorry for the delay in reviewing, but I don't think we should be taking this PR.

The way the library is authored, `import * as prefixer from 'inline-style-prefixer';` is actually not the correct syntax to use here. This is ES6 importing syntax, but the library isn't a true ES6 module. ES6 module objects only have properties and can't be called with `new`. See this StackOverflow answer for a better explanation: https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this

The existing import syntax in the tests was correct: `import prefixer = require('inline-style-prefixer')`

**Comment by ahz** [comment]
I agree it is correct to use import/require syntax. But using webpack+babel-loader allows also import/from syntax - it works in runtime. And to use webpack's tree shaking feature I need to switch TypeScript module to 'es2015' and it disallows import/require syntax. [According to Ryan](https://stackoverflow.com/a/35706271/1942494) `import * as from...` should be correct way - _This is the equivalent ES6 syntax to do the same thing_. My change in .d.ts does not disallow correct import/require syntax, but **enables** import/from syntax. I amended the test only because reviewer wanted to - original test was not affected by the change.

**Comment by minestarks** [comment]
Well that's a point. Summoning @RyanCavanaugh to set me straight on correct module usage?

**Comment by RyanCavanaugh** [comment]
Your module loader allowing/requiring illegal ES6 behavior is a bug, not a feature.

Working on a FAQ entry since we get this all the time.

**Comment by andy-ms** [comment]
@ahz I think this would be fine if you kept the `index.d.ts` changes but not the test changes.

**Comment by ahz** [comment]
@andy-ms Totally agree, I had changed the test only because @sheetalkamat wanted. Is it better like this?

**Comment by andy-ms** [comment]
OK, it's tough when a lot of different people have reviewed but I'll try to summarize perspectives.
* Usually when you change a type definition you should change tests.
* But, we have no workaround analagous to `--allowSyntheticDefaultImports` for allowing you to use a namespace import of `export =`, so we've usually allowed this. We do want webpack users to be able to use typescript.
* But, technically that's not correct, so we probably shouldn't change the test to make it less correct.

So my opinion is that this can be merged as is. @sheetalkamat @minestarks @RyanCavanaugh any objections?

**Pull request merged**
