### PR TITLE
New definition for jQuery Succinct plugin

### PR DESCRIPTION
**Pull request by mattbrooks2010**
Added definition for jQuery Succinct plugin with accompanying tests file.

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.succinct/jquery.succinct.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.succinct
  * http://bower.io/search/?q=jquery.succinct
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.succinct/jquery.succinct-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@mattbrooks2010 thank you for your contributions.
please rename `jquery.succinct/jquery.succinct.d.ts` to `succinct/succinct.d.ts`. 
http://bower.io/search/?q=succinct
https://github.com/micjamking/succinct/blob/master/bower.json#L2

**Comment by mattbrooks2010** [comment]
@vvakame done!

**Comment by vvakame** [comment]
@mattbrooks2010 thanks mate!

**Pull request merged**
