### PR TITLE
fix: remove broken type definitions

### PR DESCRIPTION
**Pull request by johnnyreilly**
This PR removes 2 broken type definitions that are no longer maintained.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
💀

**Comment by johnnyreilly** [comment]
ah

**Comment by jakebailey** [comment]
Then again, where is the bot?

**Comment by JoshuaKGoldberg** [comment]
I think we broke it 😢 poor thing

**Comment by DangerBotOSS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  `node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log

<details>


```
Error:  TypeError: Cannot read properties of null (reading 'added')
    at dangerfile.ts:64:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
danger-results://tmp/danger-results-1867eb3a.json
```


</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8ec6b59d16fbe216eeefbe1d81ec3e07b0da7c7d
</p>

**Comment by johnnyreilly** [comment]
CODEOWNERS is back!

**Comment by johnnyreilly** [comment]
maybe dangerbot is dead

**Pull request merged**
