### PR TITLE
[@types/aws-lambda] Update FirehoseTransformationResultRecord data property to optional

### PR DESCRIPTION
**Pull request by longtv2222**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Not documented anywhere, but lamda blueprint suggests that the property is optional:
    - [Process CloudWatch logs sent to Kinesis Firehose blueprint nodejs](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/function?blueprint=kinesis-firehose-cloudwatch-logs-processor&intent=blueprints) (processRecords function)
- [] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by simonbuchan** [comment]
Does this actually work? Seems like it would be safer to require it if it's just the same effect as an empty string.

**Comment by longtv2222** [comment]
To answer your question,

Yes, the blueprint is working as intended. I've been using the template for more than a year and ran into no trouble with it

For more information, the field is only considered when `result` is `Ok`, otherwise, the `data` property is ignored. When the result is `Ok`, Kinesis Firehose then send the transformed data to Kinesis Firehose destination. Setting the field to `""` would have the same effect. Still, I think it would be better to type `data` correctly to reflect the behaviour I mentioned above!

Please let me know what you think.

**Comment by simonbuchan** [comment]
Ok, that makes sense to me!

You could be a bit tighter with the types and make this a discriminated union on the `result` value, I suppose, but I don't think the value is worth the (minor) breaking change that could cause.

**Review by simonbuchan — APPROVED** [review]

**Review by gabritto — APPROVED** [review]

**Comment by longtv2222** [comment]
Ready to merge

**Pull request merged**
