### PR TITLE
github-electron: Fix callback's return type of app.makeSingleInstance()

### PR DESCRIPTION
**Pull request by rhysd**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback .
  - it has been reviewed by a DefinitelyTyped member.

---

The callback should return `void`, not `boolean`.

https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback

### CODE REVIEW

**Comment by miniak** [comment]
This method returns false if your process is the primary instance of the application and your app should continue loading. And returns true if your process has sent its parameters to another instance, and you should immediately quit.

**Comment by miniak** [comment]
@rhysd Why should the return type be void, if it's clearly documented as boolean?

**Comment by rhysd** [comment]
@miniak No, its return type is undocumented.  But the callback in sample code returns `undefined`.  And document does not also say its return type is `boolean`.

> This method returns false if your process is the primary instance of the application and your app should continue loading. And returns true if your process has sent its parameters to another instance, and you should immediately quit.

The *method* means `app.makeSingleInstance`, not the callback if I misread the document.

**Comment by miniak** [comment]
@rhysd Sorry, you're completely right, you changed the callback return type, not the function's :)

**Comment by miniak** [comment]
:+1:

**Comment by rhysd** [comment]
Yes!  Thank you for confirming 😄

**Comment by horiuchi** [comment]
@rhysd Thanks mate!
@miniak Thanks for review!

**Pull request merged**
