### PR TITLE
Chartjs 1.0.2 discrepancies

### PR DESCRIPTION
**Pull request by jass0**
http://www.chartjs.org/docs/

I found some discrepancies with the current typescript definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
*chartjs/chart.d.ts*

to author(@Steve-Fenton). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by Steve-Fenton** [comment]
:+1:

**Comment by vvakame** [comment]
um? commit has been added after the review. is it okey? I'm waiting for travis ci passed.

**Comment by jass0** [comment]
Actually commit 82daf1b75eb8badc46cee7db96d04371b35d283e will break some code, the segments variable in polar area chart variable is actually exposed. When I further looked into that, I found some more discrepancies which needed to be resolved.

**Comment by jass0** [comment]
Any thoughts?

**Pull request closed without merging**
