### PR TITLE
 ramda: Workaround for type inference problem in Filter

### PR DESCRIPTION
**Pull request by googol**
Workaround/fix for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25581

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
Sorry, I don't think this works. 

#25581 is already solvable by adding an explicit type annotation or type argument to resolve the ambiguity:
`filter<string>(v => !(contains('.local.', v) && env !== 'dev'))` or
`filter((v: string) => !(contains('.local.', v) && env !== 'dev'))`
Your solution still requires an explicit type to be added to the calling code. So I don't think it's an improvement over what's already there.

Also consider the following valid code:
```ts
const f = R.filter((a: string) => a.startsWith('a'))
f(['abc', 'bcd'])
f({x: 'abc', y: 'bcd'}) // This is valid, but becomes an error with your changes
```

In the actual implementation, `R.filter` produces a filter that can take either an object or an array. Your new typing artificially constrains `filter` such that you have to choose a type at the time the filter is created. This doesn't quite reflect the actual behavior of the library.

**Review by minestarks — CHANGES_REQUESTED** [review]
Please see comment, I don't currently think this is an appropriate fix.

**Comment by googol** [comment]
Hi. You are absolutely right about the artificial constraint this change places on the filter function. I suppose we need to decide if that limitation is acceptable for the typings here.

I think you have the wrong idea about what problem I'm trying to solve here, since there are actually two separate problems in that issue. The immediate problem the reporter of #25581 has is the lack of the explicit element type for the filter.

Having added that he would run into the error that bzumz posted in a comment on that issue, which is what I'm trying to solve here. When used in the `R.pipe` typescript will never correctly choose the list version of the filter, but always insist on the object.  The first commit on this branch includes tests that demonstrate this.

As a workaround wrapping the `R.filter` call in an arrow function (and using the less curried version of `R.filter`) works, but it seems pretty verbose and not very ramda-like.

Since the main use case for the curried `R.filter` is in these pipes, it might be reasonable to add this constraint in the types. What do you think? If you have ideas on how to approach this differently, without the constraining type parameter, I'd be happy to try them out

**Comment by tycho01** [comment]
I think @minestarks's comment can be addressed with separate overloads as we did at [npm-ramda](https://github.com/types/npm-ramda/blob/master/templates/filter.d.ts#L3).

On another note, I think the input type `ReadonlyArray` is relatively restrictive -- we'd use a type based on TS's [`ArrayLike`](https://github.com/types/npm-ramda/blob/master/templates/%24types.d.ts#L53) for the input types, as it also allows alternate 'array' implementations such as ImmutableJS's `List`.

**Comment by googol** [comment]
Adding separate overloads with the kind parameter would be a reasonable thing, allowing the use of filter in a pipe and the overloading use in minestark's comment. I'll do that
:+1: 

Some extra discussion:

I tested this with `npm-ramda` too, and looks like the same issue with filter + pipe exists there too. Looks like typescript just always chooses the last option from an interface like `Filter` or `filter_10` in these cases. In `npm-ramda` the last option is the mixed one, so an array will be accepted, the return value of filter will be wrong though. 

To avoid having to create a complete project to test this, I copied the relevant bits of `npm-ramda` to the typescript playground and added my test to it: https://gist.github.com/googol/29fe7d7e89945e7e52f5988864d6c096

**Comment by googol** [comment]
@minestarks @tycho01 So I made the Kind parameter optional. Now you can leave it out to get the original behavior, or specify it to make filter/reject usable in a pipe. What do you think of this approach?

**Comment by googol** [comment]
Hi @minestarks, can I get a re-review on this?

**Review by minestarks — APPROVED** [review]

**Comment by googol** [comment]
Thanks!

**Pull request merged**
