### PR TITLE
Add typings for rate-limit-redis

### PR DESCRIPTION
**Pull request by csuich2**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by csuich2** [comment]
Note: Waiting for approval of https://github.com/microsoft/types-publisher/pull/664 to add package to `dependenciesWhitelist.txt`

**Comment by csuich2** [comment]
BTW, I wasn't sure how to force the CI build to run again, so I just did a `git commit --amend` and `git push --force` to force a rebuild. Maybe that is what spooked you, @typescript-bot.

**Comment by csuich2** [comment]
@RyanCavanaugh @sandersn The CI build is still failing despite the `types-publisher` PR being merged. Am I missing something else here?

**Comment by sandersn** [comment]
This is the current error: 

```
rate-limit-redis depends on express-rate-limit but has a lower required TypeScript version.
```

Is this different from before?

**Comment by csuich2** [comment]
Ah, I was looking at the Travis build which said `Dependency express-rate-limit not in whitelist.` while the Azure Pipeline build had the error you found.

Ultimately the problem was that `express-rate-limit` had the `// TypeScript Version: 2.3` flag, so I added that to `rate-limit-redis` as well. However, then the build failed with this:

```
Error in rate-limit-redis
Error: /Users/chris/Source/DefinitelyTyped/types/rate-limit-redis/rate-limit-redis-tests.ts:2:8
ERROR: 2:8   expect  Compile error in typescript@2.6 but not in typescript@2.7.
Fix with a comment '// TypeScript Version: 2.7' just under the header.
Module '"/Users/chris/Source/DefinitelyTyped/types/rate-limit-redis/index"' has no default export.
ERROR: 8:1   expect  TypeScript@2.6 expected type to be:
  Store
got:
  any
ERROR: 11:1  expect  TypeScript@2.6 expected type to be:
  Store
got:
  any
ERROR: 16:1  expect  TypeScript@2.6 expected type to be:
  Store
got:
  any
ERROR: 21:1  expect  TypeScript@2.6 expected type to be:
  Store
got:
  any
ERROR: 26:1  expect  TypeScript@2.6 expected type to be:
  Store
got:
  any
```

Doing as it indicates and bumping to `2.7` fixed the issue.

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
