### PR TITLE
[matrix-appservice-bridge] Add string type to BridgeOptions.registration

### PR DESCRIPTION
**Pull request by mymindstorm**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
 - http://matrix-org.github.io/matrix-appservice-bridge/1.11.1/Bridge.html
 - http://matrix-org.github.io/matrix-appservice-bridge/1.11.1/components_cli.js.html#line34

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## matrix-appservice-bridge ([<kbd>unpkg</kbd>](https://unpkg.com/browse/matrix-appservice-bridge@latest/))
was missing the following properties:
1. StateLookup
1. ConfigValidator
1. BridgeStore
1. EventBridgeStore
1. StoredEvent

<details>
<summary>as well as these 6 other properties...</summary>
<p>BridgeContext, ContentRepo, PrometheusMetrics, Logging, RoomLinkValidatorStatus, unstable</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 312590ca883bec3e3a94a2fe975051173eb6c9b6
</p>

**Review by huan — APPROVED** [review]
LGTM

**Review by huan — APPROVED** [review]
LGTM

**Comment by mymindstorm** [comment]
Ready to merge

**Pull request merged**
