### PR TITLE
[gulp-sourcemaps] Add missing mapSources function

### PR DESCRIPTION
**Pull request by roddolf**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gulp-sourcemaps/gulp-sourcemaps#alter-sources-property-on-sourcemaps
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gulp-sourcemaps ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gulp-sourcemaps@latest/))
was missing the following properties:
1. identityMap
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b2b04962e4e63a9fc32eb2a197277b36a01cf52a
</p>

**Review by amcasey — CHANGES_REQUESTED** [review]
LGTM but there appears to be a merge conflict.

**Review by concision — APPROVED** [review]
These changes are consistent with the latest documentation available [here](https://github.com/gulp-sourcemaps/gulp-sourcemaps/tree/813c0dac7a0f7bb37cbd7ed7d5020251be823c6a#alter-sources-property-on-sourcemaps):
> The exported `mapSources` method gives full control over the source paths. It takes a function that is called for every source and receives the default source path as a parameter and the original vinyl file.

However, in the future we should instead create typings for `@gulp-sourcemaps/map-sources`, as `gulp-sourcemaps` is exporting this function [here](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/813c0dac7a0f7bb37cbd7ed7d5020251be823c6a/index.js#L3-L8):
```js
module.exports = {
  init: require('./src/init'),
  write: require('./src/write'),
  mapSources: require('@gulp-sourcemaps/map-sources'),
  identityMap: require('@gulp-sourcemaps/identity-map'),
};
```
This other module is typically only installed as a transitive `gulp-sourcemaps` dependency, though. An alternative PR should probably address this at some point.

Changes are still beneficial and look good to me.

**Comment by roddolf** [comment]
Ready to merge

**Pull request merged**
