### PR TITLE
Add angular-ui-tree

### PR DESCRIPTION
**Pull request by CalvinFernandez**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-ui-tree/angular-ui-tree.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-ui-tree
  * http://bower.io/search/?q=angular-ui-tree
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-ui-tree/angular-ui-tree-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@CalvinFernandez thanks mate!

**Comment by StefanCodes** [comment]
@CalvinFernandez I started working on these typings this morning and just noticed you pushed this! Are you actively working on the ui-tree typings, or should I keep going? Thanks.

**Comment by CalvinFernandez** [comment]
@StefanCodes Keep going! This was all I needed

**Comment by bronielsen** [comment]
@CalvinFernandez
beforeDrop and dragStop are missing from the d.ts definitions. I would suggest adding:

interface ICallbacks {
...
    beforeDrop: (event: AngularUITree.IEventInfo) => ng.IPromise<any>;
    dragStop: AngularUITree.IDroppedCallback;
}

**Comment by bronielsen** [comment]
@CalvinFernandez  @StefanCodes 
I can see that the definitions lack all the .$xxx and .$$xxx variables in the objects. 

Eg. 
event.source.nodeScope.$modelValue
event.source.nodesScope.$nodeScope

Do you want to own the definitions and implement it? Or should I make them?

**Comment by CalvinFernandez** [comment]
@bronielsen go for it!

**Comment by bronielsen** [comment]
@CalvinFernandez I added a pull request for adding an index.d.ts to the repo
[https://github.com/angular-ui-tree/angular-ui-tree/pull/870] (https://github.com/angular-ui-tree/angular-ui-tree/pull/870)

**Pull request merged**
