### PR TITLE
[node:net] Update types

### LINKED ISSUE #62298: [@types/node] net.d.ts is missing Socket.resetAndDestroy()
I'm running Node.js v18.9.0 and pulled in the latest @types/node (v18.7.18).  Back in v18.3.0 Node.js added the following:
`net.Socket.resetAndDestroy(): net.Socket`
(see: [Socket.resetAndDestroy()](https://nodejs.org/api/net.html#socketresetanddestroy))

However I'm not seeing that method in the types for Socket.  Right now I'm having to use a ts-ignore, but I'd rather have it be there for real.  Ideally I'd submit a PR, but I haven't read up on the process yet and think it'd be faster if someone in-the-know were to do it.

Many thanks!

### PR DESCRIPTION
**Pull request by Semigradsky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/net.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Close #62298

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Semigradsky sorry to be a pita, pleas ealso amend the very same files under `types/node/ts4.8/*` and `types/node/v16/ts4.8/*` directories (the support for TS versions has been branched off recently due to TS4.9 breaking changes)

**Review by LinusU — APPROVED** [review]
Nice! 🙌

**Review by peterblazejewicz — APPROVED** [review]
@Semigradsky thanks!

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
