### PR TITLE
[@types/mocha] update types to match v9.0.1

### PR DESCRIPTION
**Pull request by strangedev**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [Changelog](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md)
  - [Discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54207)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Hey everyone :wave: 
I noticed that `@types/mocha` was out of date with version 9. While updating the types, I did some housekeeping:

- Removed `utils.lookupFiles()`.
- Added `dryRun` to `MochaOptions`.
- Added the `dryRun` method to `Mocha`.
- Added the new signature of the `Runner` constructor.
- Synchronized the `MochaOptions` with the current state of mocha in v9. I noticed that there were some options older than v9 that were missing and some options that have been removed since still present. I've updated all of these options and added the current docstrings from upstream.
- Added tests for the new options and methods.
- Updated the tests. The tests were out of date as well. Some options were not tested at all. I've added tests for the `MochaOptions` I updated.

This is my first contribution to DT, so please point out any errors I may have made and I will fix them ASAP. :smile_cat:

### CODE REVIEW

**Comment by orta** [comment]
Structurally this looks good, will wait on someone closer to the module to give a thumbs up

**Comment by strangedev** [comment]
Hi @kazimanzurrashid @otiai10 @enlight @cspotcode and @1999 :wave: 
Not to be impatient, but I'm wondering if we can get this going :smiley: 
Is there anything I can do to help?
Have a nice day!

**Comment by unickq** [comment]
bump :) guys, please review this pr

**Comment by strangedev** [comment]
This is getting a bit frustrating. I understand that maintainers need some time to review PRs, but not even receiving _any_ feedback is really discouraging. I'm trying to be a good citizen here and give back fixes I need for my projects. I know for a fact there are other people who are waiting for these changes too. Not having correct types for more than a month is not a pleasant experience.

Please, someone review this PR. I took the time out of my day to study these types and implement the necessary changes, but judging from the lack of engagement, I don't feel like my efforts are welcome here.

**Comment by strangedev** [comment]
This is getting a bit frustrating. I understand that maintainers need some time to review PRs, but not even receiving _any_ feedback is really discouraging. I'm trying to be a good citizen here and give back fixes I need for my projects. I know for a fact there are other people who are waiting for these changes too. Not having correct types for more than a month is not a pleasant experience.

Please, someone review this PR. I took the time out of my day to study these types and implement the necessary changes, but judging from the lack of engagement, I don't feel like my efforts are welcome here.

**Comment by 1999** [comment]
It's fun that I'm on the list of maintainers although I made just one contribution. I can approve this PR but tbh it has been more than 3 years when I worked with mocha last time.

**Review by 1999 — APPROVED** [review]

**Comment by strangedev** [comment]
Ready to merge

**Comment by strangedev** [comment]
@1999: since no one else bothered checking, I'm merging this and will keep an eye out for bug reports. Thanks for the help!

**Pull request merged**
