### PR TITLE
[@types/lodash] Add generics with any-defaults to isEquals

### PR DESCRIPTION
**Pull request by sseppola**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.15#isEqual
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by aj-r — CHANGES_REQUESTED** [review]
What problem are you trying to solve with this? Normally there's no benefit of adding generics if each generic parameter is only used once.

I suspect your test should pass without this change (or if it doesn't, you could make it compile by adding a lambda, e.g. `distinctUntilChanged((a, b) => isEqual(a,b))`

**Comment by sseppola** [comment]
> I suspect your test should pass without this change (or if it doesn't, you could make it compile by adding a lambda, e.g. distinctUntilChanged((a, b) => isEqual(a,b))

That is correct, however in it's current form it is a foot-gun. If you for any reason forget to use a lambda then you'll get a nasty surprise as the return type is an `any` that is not caught by TypeScript configured with `strict: true`.

**Comment by aj-r** [comment]
I don't follow, isEqual returns boolean, not any.

**Comment by sseppola** [comment]
[TS Playground demo](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABDAzgUQI4gIYBsAU2AXItmAJ4A0iARkWeQJSIDeAUIp4gE4CmUIbkmyIAvONoBuNgF82oSLATJ0WPAHUYUABYBxXmF7cYEFAB4AKmNIVqAVWsMAfIRIXqdO83Zce-QUiomDgE2B7MAPQRyAC2AA64vDEGUNhKSAAmcLwoYADkUIgxaVBGsmzy4NDwmaiwinZgsLgAwtpkAOa8GZYuEHDx2NxpcNwkrojutG7Mok60cHCJZN4cXHwCQogT7nSTjG5i8-2Dw1CjhJQ0zAD8pIgkNNIy0mz9YCiFYACMJGAgMRoRms32k70+iDAACY-gCgdxrFDXuDCnwUCBcFAAIIUawZOowBpNGCtdpgLoZfBBNS4Rj4H7UaGMMEICFojFQABycOBokQ+M+hOgjWabU63SpqhCmh0+kMxlMdIZkKhzKAA) 

If we break up `const resultAny = distinctUntilChanged(isEqual)(n1, n2)` into smaller pieces it's easier to see what happens:
```ts
const distinctIsEqual = distinctUntilChanged(isEqual) // (a: any, b: any) => any
const resultAny = distinctIsEqual(1, 2) // any
```
With the invocation of `distinctUntilChanged(isEqual)` TS already binds the types to `any` and we have to explicitly tell it what the correct type is. By adding generics we can delay that.

**Comment by aj-r** [comment]
That sounds like an issue that should be fixed in your code base rather than in lodash. Single-use type parameters are generall bad practice (https://typescript-eslint.io/rules/no-unnecessary-type-parameters/) so I don't think it's a good solution to your problem.

Instead you could create your own function that wraps `isEqual`, e.g. `function isEqual<T>(a: T, b: T): boolean`. Or store the result of `distinctUntilChanged(isEqual)` in a variable (and cast it) so you can fix the type in one place.

**Comment by sseppola** [comment]
Ok

**Pull request closed without merging**
