### PR TITLE
openlayers - Updated many of the interactions according to documentation.

### PR DESCRIPTION
**Pull request by rgvassar**
Added a few missing methods. Added jsdoc documentation. A couple function definitions appeared to be too specific. Classes didn't extend the proper classes. Added missing constructors.

Documentation can be found under the [ol.interaction](http://openlayers.org/en/latest/apidoc/ol.interaction.html) on the OpenLayers site.

### CODE REVIEW

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by rgvassar** [comment]
Conflict resolved.

**Comment by vvakame** [comment]
thanks! 
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by woutergd** [comment]
👍 , thanks for the changes, good work! However, there are still conflicts indicated, @vvakame, dont know if that is a problem for merging?

**Comment by rgvassar** [comment]
Conflicts resolved.

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
