### PR TITLE
Updated arcgis-js-api to 4.0

### PR DESCRIPTION
**Pull request by JeffJacobson**
Upgraded arcgis-js-api to version 4.0. Renamed old versions with version number.

### CODE REVIEW

**Comment by dasa** [comment]
@JeffJacobson thank you for this PR, but we don't want to have this big of an impact on the existing 3.x users.

For 4.x users, we would suggest that they either download the definition file from [here](https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript) or use the [typings](https://github.com/typings/typings) tool to install it using the command:

`typings install --ambient github:Esri/jsapi-resources/4.x/typescript/arcgis-js-api.d.ts`

/cc @bsvensson

**Comment by dasa** [comment]
👎

**Comment by vvakame** [comment]
@dasa thank you for your comment.
But I hope you reconsider about this PR.
We are using NuGet, tsd, dtsm... and more. This repository is not for typings only.

**Comment by mhegazy** [comment]
@dasa and @vvakame what is this going to be, in or out?

**Comment by vvakame** [comment]
I can't review this PR. but I'll merge this PR in 3 days when We can't get response from @dasa

**Comment by dasa** [comment]
Please don't merge this PR.

**Comment by JeffJacobson** [comment]
I didn't know about Typings when I made this pull request. It sounds like the best option would be to register the [ArcGIS v4 API d.ts file](https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript) with the [typings Registry](https://github.com/typings/registry).

In the mean time, Esri has provided [instructions for using their file from their GitHub repository with Typings](https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript). Note that these are slightly different from what @dasa [posted above](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9278#issuecomment-218605955) (`global` vs. `ambient`).

**Comment by dasa** [comment]
Thanks @JeffJacobson. We plan to reevaluate how we distribute our .d.ts files as part of the TypeScript 2.0 release. See: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Pull request closed without merging**
