### PR TITLE
[gulp] add TaskFunctionCallback as an alias to Undertaker.TaskCallback

### PR DESCRIPTION
**Pull request by kazarmy**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
```js
/**
 * Start a server.
 * @param {!gulp.TaskFunctionCallback} cb Gulp callback.
 */
const startServer = (cb) => {
  // ...
  cb();
};
```
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The alias is useful in JavaScript (which doesn't have types) and `@param` JSDoc as shown above.

### CODE REVIEW

**Comment by kazarmy** [comment]
Waiting for the `lib.dom.d.ts` / `globals.d.ts` error [1] to clear. Also, typescript-bot is showing me a green tick for the CI tests which suggests something is broken in the build infra.

[1] https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50428/checks?check_run_id=1656320422#step:5:354

**Comment by GiedriusGrabauskas** [comment]
Hi @kazarmy, thanks for your PR. 

**Deprecation Reason**
This deprecation is based on `gulp@3` types.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9c0cf371e20ea85fc91be83ab10d2c12a154e120/types/gulp/v3/index.d.ts#L297-L304

As you can see, previously, `TaskCallback` was the task definition type. So, for that reason, it was deprecated.

If we change this to the callback method, it would be a breaking change, and some developers will start getting compilation errors.


**Suggestion**
Maybe we should name it `TaskFuncionCallback` instead of `TaskCallback`?

**Comment by kazarmy** [comment]
> Maybe we should name it TaskFuncionCallback instead of TaskCallback?

Ok fb16e646d75dc72b87140141cb03cb20b3be9a82 ... this means `TaskCallback` will be deprecated forever, right?

**Comment by GiedriusGrabauskas** [comment]
> ... this means `TaskCallback` will be deprecated forever, right?

Basically, when a new version of `gulp` (at least `4.1` or `5.0`) will be released. But no one knows the future 😄

Thanks again 👍

**Review by GiedriusGrabauskas — APPROVED** [review]

**Comment by kazarmy** [comment]
Waiting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50431 / https://github.com/microsoft/TypeScript/issues/42229.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gulp ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gulp@latest/))
was missing the following properties:
1. Gulp
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4f93a348be0f9365fe8ae15e1123d19953b6edc6
</p>

**Review by GiedriusGrabauskas — APPROVED** [review]

**Comment by kazarmy** [comment]
Ready to merge

**Comment by Benno007** [comment]
Our dependency updater just upgraded these types, and failed our build with:
```
node_modules/@types/gulp/index.d.ts(24,44): error TS2694: Namespace 'Undertaker' has no exported member 'TaskCallback'.
```

We had `@types/undertaker` version 1.2.2 installed (via `@types/gulp` and using `gulp@4.0.2`) so had to remove our yarn.lock entry for it and `yarn install` again to get the latest patch version of `types/undertaker` which included TaskCallback.

Just for anyone else who has the same issue.

**Comment by kazarmy** [comment]
Fwiw I don't have any further plans for `@types/undertaker` or `@types/gulp`.

**Comment by milahu** [comment]
> We had `@types/undertaker` version 1.2.2 installed (via `@types/gulp` and using `gulp@4.0.2`) so had to remove our yarn.lock entry for it and `yarn install` again to get the latest patch version of `types/undertaker` which included TaskCallback.

sounds like a bug in `@types/gulp`

```
yarn list

├─ @types/gulp@4.0.9
│  ├─ @types/undertaker@*
│  ├─ @types/vinyl-fs@*
│  ├─ chokidar@^3.3.1
│  ├─ chokidar@3.5.3
│  │  ├─ ...
│  │  └─ readdirp@~3.6.0
│  └─ readdirp@3.6.0
│     └─ picomatch@^2.2.1
```

**Comment by kazarmy** [comment]
> > We had `@types/undertaker` version 1.2.2 installed (via `@types/gulp` and using `gulp@4.0.2`) so had to remove our yarn.lock entry for it and `yarn install` again to get the latest patch version of `types/undertaker` which included TaskCallback.
> 
> sounds like a bug in `@types/gulp`

`@types/gulp` 4.0.10 should fix this problem ... sorry for the delay, didn't realize the fix was possible

**Pull request merged**
