### PR TITLE
Add definitions for jQuery Featherlight v1.3.4.

### PR DESCRIPTION
**Pull request by xStrom**
This patch contains the definitions and tests for the jQuery extension [Featherlight v1.3.4](http://noelboss.github.io/featherlight/).

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.featherlight/jquery.featherlight.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.featherlight
  * http://bower.io/search/?q=jquery.featherlight
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.featherlight/jquery.featherlight-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@xStrom thank you for your contributions.
please rename jquery.featherlight/jquery.featherlight.d.ts to featherlight/featherlight.d.ts
http://definitelytyped.org/guides/contributing.html#naming-the-file
https://github.com/noelboss/featherlight/blob/master/bower.json#L2

**Comment by xStrom** [comment]
@vvakame I renamed the files.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
