### PR TITLE
fix(sharp): add missing linear, recomb, modulate types

### PR DESCRIPTION
**Pull request by makepanic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). (via `node node_modules/.bin/dtslint types sharp` because https://github.com/Microsoft/dtslint/issues/219)

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

* `linear` [docs](https://github.com/lovell/sharp/blob/master/docs/api-operation.md#linear) , [allowing null as first param](https://github.com/lovell/sharp/blob/1999c7103ccc293d4414e1d2c3726fb601079e2d/test/unit/linear.js#L61)
* `recomb` [docs](https://github.com/lovell/sharp/blob/master/docs/api-operation.md#recomb)
* `modulate` [docs](https://github.com/lovell/sharp/blob/master/docs/api-operation.md#modulate)

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Note: `modulate` is part of the next sharp release and not yet released. I'm not sure if we should already ship it in the type definition, see https://github.com/lovell/sharp/commit/fc178de309d8e4055e86ffe1bbcfcf40754c885b#diff-343723a0cb380f664aedf0dfed5c1c2f

### CODE REVIEW

**Comment by BTOdell** [comment]
We should probably wait until `modulate` is released before it's included in the type definitions.
Do you have an ETA on when that release will drop?

**Comment by makepanic** [comment]
I could also split this PR to one which adds `recomb` and the `linear` adjustments and create a new one for `modulate`.


> We should probably wait until `modulate` is released before it's included in the type definitions.
> Do you have an ETA on when that release will drop?

I think only @lovell knows.

**Comment by BTOdell** [comment]
I'd be happy to sign off on a pull request that only includes the definitions for the released features.

**Comment by lovell** [comment]
The `modulate` operation will be in the forthcoming v0.22.1 so it would probably be best to remove it from this PR as is is not yet "missing". Hope this helps.

**Comment by makepanic** [comment]
I've updated the PR by removing `modulate` types.

**Review by BTOdell — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
