### PR TITLE
[loglevel] Correct signature for setDefaultLevel. Fixes #20058.

### LINKED ISSUE #20058: [loglevel] Argument type for setDefaultLevel is incorrect
It's expecting the object with DEBUG, WARN, etc keys instead of level values.

### PR DESCRIPTION
**Pull request by jmnsf**
`setDefaultLevel` wasn't changed along with `setLevel`. As the [docs indicate](https://github.com/pimterry/loglevel), both methods take the same level argument.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pimterry/loglevel
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by screendriver** [comment]
@jmnsf you could extract 

```ts
LogLevelNumbers
    | 'trace'
    | 'debug'
    | 'info'
    | 'warn'
    | 'error'
    | 'silent'
    | keyof LogLevel
```

to it's own type because it will also be used in `setLevel`. With that we remove code redundancy :wink: 

And you should add the test to `loglevel-umd-tests.tst` as well :relaxed:

**Comment by jmnsf** [comment]
@screendriver Yep, I'll give it a spin 👍

**Comment by screendriver** [comment]
LGTM 👍

**Comment by screendriver** [comment]
@andy-ms how could it be that I don't have "start review" rights? I opened the issue #20619 because I am not in the [CODEOWNERS](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS#L1875) file but I don't know why?

Furthermore one contributor left (#20618) and he is still in this file though he should be deleted from there 🤔

**Comment by andy-ms** [comment]
@screendriver We don't yet have a process to automatically update CODEOWNERS, but I'll regenerate it today.

**Pull request merged**
