### PR TITLE
@types/passport-auth0: Add default export to type definition 

### PR DESCRIPTION
**Pull request by karlhorky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/passport-auth0/blob/09f18140de08ca9f7dc1549a881e8bd5eee9ffd4/lib/index.js#L187-L190
- ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~

### CODE REVIEW

**Comment by karlhorky** [comment]
cc @iamvishnusankar or @johnbendi or @duncanhall, could one of you review this?

Short version: this enables importing the default export as well as the named export.

Long version: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42347

**Comment by karlhorky** [comment]
Or @sandersn, maybe you can review since you've already reviewed this code?

**Review by sandersn — APPROVED** [review]
Looks good once the merge conflicts are fixed.

(Was that another one of your PRs or is passport-auth0 just super popular all of a sudden?)

**Comment by karlhorky** [comment]
Great thanks!

Looks like it's another PR that caused the conflict:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/758c0138837a94c15dba064ec051260507e003d4

**Comment by karlhorky** [comment]
Thanks @sandersn!

**Pull request merged**
