### PR TITLE
Allow dynamic CSS values based on component props in react-jss

### PR DESCRIPTION
**Pull request by jlaw90**
This PR is to add typings for part of the dynamic values functionality in react-jss.

A few things I'm not happy with:
* I can't work out how to define typings for the other part of the spec (className: props => {color: 'red', etc...})
* I had to disable strict function checking in tsconfig.json to get tsc to pass with the changes made to the test file.

Would be glad if anyone has pointers or wants to look at these parts.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/cssinjs/react-jss#dynamic-values>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
@jlaw90 I'm not really comfortable merging this without being able to leave `strictFunctionTypes` enabled, since that pretty much indicates something's wrong. I took some time to look into this, but unfortunately I don't know enough to come up with a solution myself. I'll try to circle back, but I'd suggest in the meantime reattempting to do it without having to disable the strict checking.

**Comment by jlaw90** [comment]
Thanks for the feedback @uniqueiniquity.

It seems that removing the second type parameter from the return type of the helper function in the test fixes this issue with strictFunctionTypes enabled and TypeScript is correctly inferring the value of Props.

I honestly don't understand enough about TypeScript to know why this would be the case so would definitely appreciate any insights!

**Comment by jlaw90** [comment]
Hmm, it seems this break the TravisCI build but interestingly if I follow it's advice and remove the Props type parameter then the return type is incorrect...

**Comment by uniqueiniquity** [comment]
@jlaw90 You can just adds the following above line 20, it seems permissible here.
```ts
// tslint:disable-next-line:no-unnecessary-generics
```

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
