### PR TITLE
Fix some incorrect method signatures, add significant amount of comments and rewrite tests

### PR DESCRIPTION
**Pull request by kjsmita6**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [node-steam-tradeoffer-manager](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by kldzj — APPROVED** [review]
LGTM 👍🏻

You'll just have to fix some errors in the test file, some of the jsdoc formatting and whatever else has been marked.

**Comment by kjsmita6** [comment]
Sigh, time to figure out how to format jsdoc bullet point lists :)

**Comment by kjsmita6** [comment]
@kldzj are you able to run `npm test` on this package? I keep getting errors like
```
  1:1  error  Definition for rule 'no-single-element-tuple-type' was not found        no-single-element-tuple-type
  1:1  error  Definition for rule 'no-unnecessary-generics' was not found             no-unnecessary-generics
  1:1  error  Definition for rule 'no-useless-files' was not found                    no-useless-files
  1:1  error  Definition for rule 'prefer-declare-function' was not found             prefer-declare-function
  1:1  error  Definition for rule 'redundant-undefined' was not found                 redundant-undefined
  1:1  error  Definition for rule 'trim-file' was not found                           trim-file
```

which prevent the tests from actually running. I don't think we have anything wrong with our tslint config.

**Comment by kldzj** [comment]
> are you able to run npm test on this package? I keep getting errors [...]

Actually, no, I keep getting a different error which I don't remember the fix for:

```
Error:
/home/redacted/DefinitelyTyped/types/steam-tradeoffer-manager/index.d.ts
  1:1  error  File /home/redacted/DefinitelyTyped/node_modules/form-data/index.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.   @definitelytyped/no-outside-dependencies

✖ 1 problem (1 error, 0 warnings)
```

**Review by kldzj — APPROVED** [review]
Looks good, thanks for putting in the effort! :)

**Review by navya9singh — APPROVED** [review]

**Comment by kjsmita6** [comment]
Ready to merge.

**Pull request merged**
