### PR TITLE
Fixes #12065 [jest] jest.d.ts need to be updated to match latest version (16.0.0)

### LINKED ISSUE #12065: [jest] jest.d.ts need to be updated to match latest version (16.0.0)
- [x] I tried using the latest `jest/jest.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `jest/jest.d.ts`.
  - The authors of that type definition are cc/ @NoHomey, @jwbay

New jest version ([16.0.0](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1600)) has been released almost 20 days ago. jest/jest.d.ts needs to be updated.

Reference:

- [CHANGELOG](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1600)
- [API Reference](https://facebook.github.io/jest/docs/api.html)

### PR DESCRIPTION
**Pull request by NoHomey**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.

API changes reference:
- [CHANGELOG](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1600)
- [API Reference](https://facebook.github.io/jest/docs/api.html)

### CODE REVIEW

**Comment by jwbay** [comment]
Could we get functions on the `jest` object returning `typeof jest` as appropriate? They're annotated in the API docs now with 'Returns the jest object for chaining'

**Comment by NoHomey** [comment]
@jwbay yes of course, I also changed two test cases to use chaining.

**Comment by jwbay** [comment]
Looks good to me 👍

**Comment by NoHomey** [comment]
@vvakame  Could you review this Pull request?

**Pull request merged**
