### PR TITLE
[react-native]: Add Websocket addEventListener and removeEventListener

### PR DESCRIPTION
**Pull request by robrechtme**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by amcasey** [comment]
@robrechtme Do you have a link to an API doc or implementation code for these functions?  I'm not familiar with the API, but I'm not seeing them on (what appear to be) the corresponding [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket).

**Comment by robrechtme** [comment]
I also had a hard time figuring out if they were supported. The RN `WebSocket` class is hugely underdocumented imo.

- The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#events) (which RN refers to) state you can add event listeners by `addEventListener`.
- The [RN WebSocket implementation](https://github.com/facebook/react-native/blob/main/Libraries/WebSocket/WebSocket.js#L66) extends from `EventTarget` from [event-target-shim](https://github.com/mysticatea/event-target-shim/blob/master/docs/reference.md), which implements both `addEventListener` and `removeEventListener` for these four events.
- RN has an [integration test](https://github.com/facebook/react-native/blob/main/IntegrationTests/WebSocketTest.js#L65) which uses `addEventListener`.

Hope this helps.

**Comment by amcasey** [comment]
@robrechtme Perfect, thanks!

**Review by amcasey — APPROVED** [review]

**Comment by robrechtme** [comment]
Ready to merge

**Pull request merged**
