### PR TITLE
bl typings update

### PR DESCRIPTION
**Pull request by benallfree**
Greetings, this updates the `bl` typings to the latest version.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://www.npmjs.com/package/bl#ctor
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bl@latest/))
was missing the following properties:
1. isBufferList
1. BufferListStream
1. BufferList
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f436db508c3f3ddc2eab16b08b896109a32d5a17
</p>

**Comment by peterblazejewicz** [comment]
@benallfree should `BufferList` methods also include those?
`readIntBE`, `readIntLE`, `readUIntBE`, `readUIntLE`

**Comment by elibarzilay** [comment]
@benallfree: ping re @peterblazejewicz's question?

**Comment by benallfree** [comment]
@elibarzilay I think @peterblazejewicz is correct, it would be more complete. I'm not sure when I'll have the time to add them though. This PR is definitely an improvement as is though :)

**Pull request merged**
