### PR TITLE
fix(node): Make `ProcessVersions` extend `Dict<string>`

### PR DESCRIPTION
**Pull request by ExE-Boss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46700#issuecomment-673956841>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by addaleax** [comment]
Fwiw, with my Node.js core maintainer hat on, I don’t think this is a good idea *at all*. Yarn should know better than to add random (not even namespaced) entries to built-in Node.js objects, or to recommend using them as a way of feature checking, and that TypeScript complains about using them is a good thing, imo.

**Comment by addaleax** [comment]
(That goes for other code as well that adds properties to `process.versions` and similar objects, not just yarn, to be clear, because it sets your users up for potential future breakage.)

**Comment by ExE-Boss** [comment]
Ready to merge

**Comment by ExE-Boss** [comment]
@addaleax

> Yarn should know better than to add random (not even namespaced) entries to built-in Node.js objects

`process.version.pnpapi` is named after the `pnpapi` package name, which is owned by **Yarn** and acts as a built‑in module when using [**Yarn 2’s** Plug’n’Play](https://yarnpkg.com/features/pnp).

**Comment by addaleax** [comment]
@exe-boss I fully understand *why* that entry is there, but that was not my point – the point is that the `process.versions` namespace is owned by Node.js, not collectively by every module (even if it acts like a builtin)

**Pull request merged**
