### PR TITLE
update(miniprogram-wxs): modified es5

### PR DESCRIPTION
**Pull request by NewFuture**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxs/07basiclibrary.html>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by rbuckton** [comment]
Why is this including an entire copy of the lib.es5.d.ts file?

**Comment by NewFuture** [comment]
> Why is this including an entire copy of the lib.es5.d.ts file?

It is almost the same with lib.est.d.ts, but some interfaces are modified.
* All Constructors are deleted
* All buffer related interfaces are deleted
* some vars are deleted

All of those are cannot use in `wxs`.
And I could not find a way to disable them in the default es5 lib.

Is there a better way to to do that?

**Comment by rbuckton** [comment]
There is no other way to do it, but you will constantly need to keep this up to date with changes in lib.es5.d.ts since we also put common TypeScript interfaces and types in that declaration file as well.

**Comment by NewFuture** [comment]
Yes. And in fact, the interface of  `wxs`  is not keeping up to date immediately with `lib.es5`.
Currently, it makes sense to maintain a copy of this lib.

Thanks, @rbuckton.

**Pull request merged**
