### PR TITLE
isomorphic-fetch,whatwg-fetch: Add ArrayBuffer to BodyInit

### LINKED ISSUE #9378: whatwg-fetch,isomorphic-fetch: BodyInit should accept ArrayBuffer
https://developer.mozilla.org/en-US/docs/Web/API/Request/Request:

> body: Any body that you want to add to your request: this can be a Blob, ArrayBuffer, FormData, URLSearchParams, or USVString object. Note that a request using the GET or HEAD method cannot have a body.

@ryan-codingintrigue: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts#L82
@toddlucas: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/isomorphic-fetch/isomorphic-fetch.d.ts#L23

### PR DESCRIPTION
**Pull request by tamird**
Fixes #9378.

Relevant specs:
BodyInit: https://fetch.spec.whatwg.org/#bodyinit
BufferSource: https://heycam.github.io/webidl/#common-BufferSource

### CODE REVIEW

**Comment by ryan-codingintrigue** [comment]
👍

**Comment by tamird** [comment]
@ryan-codingintrigue quick heads up that I also added ArrayBufferView to the list, since that's what BufferSource really refers to.

**Comment by ryan-codingintrigue** [comment]
I wasn't sure of that, but eventually found the [Web IDL](https://heycam.github.io/webidl/#common-BufferSource) definition. Thanks again

**Comment by tamird** [comment]
I've also added BufferSource to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/BufferSource), which links to the specification.

**Comment by toddlucas** [comment]
:+1:

**Comment by toddlucas** [comment]
Thanks for the enhancement!

**Comment by tamird** [comment]
What happens now? Who do I need to summon to get this merged?

**Comment by tamird** [comment]
@vvakame could you please take a look?

**Comment by vvakame** [comment]
sorry for late.

**Comment by toddlucas** [comment]
No problem @vvakame Thanks!

**Pull request merged**
