### PR TITLE
Added roslibjs definition

### PR DESCRIPTION
**Pull request by Pro**
Definition for http://wiki.ros.org/roslibjs

### CODE REVIEW

**Comment by vvakame** [comment]
*roslibjs/roslibjs.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/roslibjs
  * http://bower.io/search/?q=roslibjs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (roslibjs/roslibjs-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
rename roslibjs/roslibjs.d.ts to roslib/roslib.d.ts
https://www.npmjs.com/package/roslib

**Comment by Pro** [comment]
@vvakame renaming done

**Comment by vvakame** [comment]
fix travis ci failed. https://travis-ci.org/borisyankov/DefinitelyTyped/builds/84950967

**Comment by Pro** [comment]
@vvakame Damn it! I thought I comitted the fix already. Now it's fixed also for travis :+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
