### PR TITLE
[types/node] Add promisify to util [wip]

### PR DESCRIPTION
**Pull request by ghost**
A simple type definition that allows us to use the exciting util.promisify function.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/util.html#util_util_promisify_original
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I've never contributed before, and I'm new to Typescript, so please bear with me. Thanks!

### CODE REVIEW

**Comment by hinell** [comment]
There is issue: #16860

**Review by hinell — APPROVED** [review]

**Comment by tellnes** [comment]
It looks correct to me, but it would be great if it somehow preserved the type information from the second argument of the callback by default.

Also, it is missing `util.promisify.custom`.

**Comment by hinell** [comment]
>Also, it is missing util.promisify.custom.
👍

**Comment by yuit** [comment]
I will merge the PR and open a separate issue regarding missing `util.promisify.custom`

**Comment by zh99998** [comment]
this wild `Function` definition will break any later definitely-typed benefits

have a look at @types/bluebird promisify type definition, it's such better
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4daa34112b1459b542ba7bb7923a44eebb755803/types/bluebird/index.d.ts#L625-L638
image

**Comment by ikokostya** [comment]
Why this function added to type definition for nodejs **7**?

**Comment by hinell** [comment]
@ikokostya What?
screenshot_2

**Comment by ikokostya** [comment]
[index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts) contains type definitions for Node.js v7 

> // Type definitions for Node.js v7.x

But [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) was added in Node.js v8 and not available in Node.js 7

```
> [kostya@arch ~]$ node -v
v7.10.0
[kostya@arch ~]$ node
> util.promisify
undefined
```

**Comment by ikokostya** [comment]
I think need to move current `index.d.ts` to `v7/index.d.ts` and make new `index.d.ts` for latest `Node.js v8`

**Comment by blakeembrey** [comment]
You should use something more like https://github.com/types/npm-thenify/blob/6ec63ea2de3f0e09d40dfccc9861f3aaa90b8853/index.d.ts#L19-L23 to keep the types. However, support for multiple arguments and the `util.promisify.custom` symbol is tricky and probably impossible without having it manually specified as a generic.

**Comment by andy-ms** [comment]
We should probably revert this as `util.promisify` is not in node v7.

**Comment by hinell** [comment]
@andy-ms I think it's better to check out earlier index version to separate v7 folder as suggested by #17027

**Comment by cjhowe7** [comment]
@blakeembrey I think you're right, but that solution still limits the number of arguments the function can accept. I don't think `util.promisify` necessarily has to be used with the Node API functions, so there's no guarantee that there is any limit on the number of arguments. [Note that `util.promisify` uses the spread operator](https://github.com/nodejs/node/blob/v8.0.0/lib/internal/util.js#L229).

**Comment by blakeembrey** [comment]
@cjhowe7 You can overload it up to 10, and then just do `any[]` for anything more than 10. Very unlikely to occur and better type than `Function`. Also, the spread operator shouldn't be relevant to the declaration - the return promise is still just as tricky because it's an object based on argument names and not an array (https://github.com/nodejs/node/blob/0d8021e5a4cf0a6aa3a700a361f6d42c2894f2ba/lib/internal/util.js#L235).

**Pull request merged**
