### PR TITLE
Fix swagger-schema-official security type

### PR DESCRIPTION
**Pull request by nimerritt**
See https://github.com/OAI/OpenAPI-Specification/blob/ae9322eb2df1555acf3163e30cd84779d98afec5/schemas/v2.0/schema.json#L1177
for the original JSON-schema definition of the security field.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OAI/OpenAPI-Specification/blob/ae9322eb2df1555acf3163e30cd84779d98afec5/schemas/v2.0/schema.json#L1177
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nimerritt** [comment]
I guess I'm supposed to tag @mohsen1 and @bsouthga?

**Comment by mohsen1** [comment]
👎

Fix the security types instead

**Comment by nimerritt** [comment]
@mohsen1 I'm not sure exactly what you mean. The `securityDefinitions` takes a string ->security scheme object which is in the typescript definition the `Security` type. The `security` property is an array of security requirement object according to the Swagger spec. Do you want me to introduce a `SecurityRequirementObject` type?

**Comment by mohsen1** [comment]
Ah I see. Sorry misunderstood this. 

Yes, security requirements object sounds good

**Comment by aozgaa** [comment]
So, :+1 or :-1, @mohsen1 ?

**Review by mohsen1 — APPROVED** [review]

**Pull request merged**
