### PR TITLE
Add defs + tests for Bounce.js

### PR DESCRIPTION
**Pull request by cherrry**
Added definitions for Bounce.js

### CODE REVIEW

**Comment by vvakame** [comment]
*bounce.js/bounce.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/bounce.js
  * http://bower.io/search/?q=bounce.js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (bounce.js/bounce-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
please rename bounce.js/bounce.d.ts to bounce/bounce.d.ts
https://github.com/tictail/bounce.js/blob/master/package.json
https://github.com/tictail/bounce.js/blob/master/bower.json

**Comment by cherrry** [comment]
The path has been fixed, thanks for reminding

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
