### PR TITLE
[node] Add v20 typings

### PR DESCRIPTION
**Pull request by Semigradsky**
- Run scripts/new-version 20
- Run scripts/generate-docs
- A bit of manual editing of types after all
---

https://github.com/nodejs/node/releases/tag/v20.0.0

- async_hooks: deprecate the AsyncResource.bind asyncResource property - just deprecated, but I removed it, since this property was removed from doc
- crypto: remove DEFAULT_ENCODING
- crypto: remove obsolete SSL_OP_* constants
- crypto: remove ALPN_ENABLED

### CODE REVIEW

**Comment by Semigradsky** [comment]
> // For backward compatibility, keep exposing CryptoKey in the Crypto prototype when using the flag.

Looks like this prop still available with `--no-experimental-global-webcrypto` flag.

**Comment by Semigradsky** [comment]
Will run scripts/generate-docs at first

**Comment by Semigradsky** [comment]
@peterblazejewicz any comments/suggestions?

**Comment by peterblazejewicz** [comment]
> @peterblazejewicz any comments/suggestions?

No, I could approve any minute, I'm just not using Node on daily-basis now (C# stack), so can't use this in existing setup myself. I believe it's not breaking stuff, that just placeholder and v18 relegation, am I correct?

**Comment by Semigradsky** [comment]
Only one "breaking stuff": I removed v14 typings in the first commit. I can remove this commit if you don't think that is time for it.

**Comment by Semigradsky** [comment]
@peterblazejewicz I removed first commit, so no more breaking stuff, just moving v18 typings to separate `v18` folder and generating v20 typings.

Node v14 maintenance was ended but users may want to fix some typings, for example #65386

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
let's move things forward,
@Semigradsky thanks!

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
