### PR TITLE
Update linq.d.ts

### PR DESCRIPTION
**Pull request by grofit**
Added es6 support as mentioned in here 
http://stackoverflow.com/questions/33349091/linq-javascript-library-with-typescript-es6-import-syntax/33355446?noredirect=1#comment54534764_33355446

There may be a preferred way to do this but currently this seems to work fine so feel free to reject or edit.

### CODE REVIEW

**Comment by lukefan6** [comment]
+1
anyone knows how to fix the travis build failure error?
the linq.d.ts needs to be updated otherwise I need to manually edit it after installing via typings or tsd

**Comment by grofit** [comment]
How do I see the error on the server? if someone can show me what the server blows up with I can try to assist diagnosing it.

**Comment by vvakame** [comment]
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/87691392 here is it.
please merge master/HEAD into your branch.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
