### PR TITLE
Update moxios to reference latest axios version

### PR DESCRIPTION
**Pull request by alastairs**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.) [**No `npm test` script defined**]
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [**dependency bump only**]
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. **(N/A)**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **(N/A)**

### CODE REVIEW

**Comment by alastairs** [comment]
I don't really understand the build failures from Travis/Azure Pipelines. They might be due to an incompatible version of Typescript, perhaps? I have Typescript 3.5.3 locally, where the compilation appeared to complete successfully, but it looks like the builds ran with Typescript 2.0. I don't seen any indication of how the Typescript version is resolved.

**Comment by alastairs** [comment]
Taking this example line from the build logs:
```
node_modules/axios/index.d.ts(6,33): error TS2314: Generic type 'AxiosPromise<T, any>' requires 2 type argument(s)
```
and the accompanying source code line (plus surrounding context lines):
```
export interface AxiosAdapter {
  (config: AxiosRequestConfig): AxiosPromise<any>;
}
```
it's clear only one type argument is being provided. Lower down the file, however, the type is defined with just the one type parameter:
```
export interface AxiosPromise<T = any> extends Promise<AxiosResponse<T>> {
}
```
I can't work out from where the two-parameter definition of `AxiosPromise` is coming.

**Comment by alastairs** [comment]
I’d appreciate a pointer or some assistance from @itoasuka or one of the maintainers if possible. Otherwise I’ll leave it to @typescript-bot to close this.

**Comment by kevcenteno** [comment]
@alastairs It was an issue with Typescript versions 2.2 and below.  I've rectified this by setting the minimum typescript version in the index.d.ts (following https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21-or-above).

PR is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38037

**Comment by alastairs** [comment]
Fantastic, thanks @kevcenteno! looking forward to seeing #38037 merged 😄

**Pull request closed without merging**
