### PR TITLE
Add class methods for Signale

### PR DESCRIPTION
**Pull request by JasonEtco**
There are a number of class methods missing from these types, as well as some new ones added in 1.3 and 1.4.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/klaussinani/signale#api
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I haven't added any tests - I'm not familiar with this testing setup, some help would be much appreciated ❤️ 🙏

### CODE REVIEW

**Comment by baltzyee** [comment]
Was going to do this today  but u beet me! Haha! But here are waht i found https://github.com/klaussinani/signale/blob/master/types/signale.d.ts
Types are added but not released, maybe on next relese? But work better than DT types here. Maybe copy them here? The coder of the tool has codded them too:
history: https://github.com/klaussinani/signale/commits/master/types/signale.d.ts

**Comment by baltzyee** [comment]
Oh look what i find: https://github.com/klaussinani/signale/pull/85

> Follow-up PRs will add all missing type declaration, JSDoc comments as well as unit tests.

JSDoc comments now missing from, maybe coming soon by @klaussinani 🚀👩‍🚀

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Hi @JasonEtco, thanks for the contribution!
[This link](https://github.com/Microsoft/dtslint#write-tests) should help with figuring out how to write tests.
Basically, you want to write code using the methods you added, and use the `// $ExpectType` comments to assert the types that you expect. This will help future changes to the package from regressing what you added. Let me know if you have any questions!
(marking as changes requested for bookkeeping purposes)

**Comment by JasonEtco** [comment]
Nice, thanks for the link @uniqueiniquity! Much appreciated 🙏 I'll take a crack at this, but hopefully, like @baltzyee noted, the types will be bundled in the next release of Signale.

**Comment by JasonEtco** [comment]
Fine with me, I think it makes sense to wait until the types are added into
the library directly - looks like we're just waiting on a new release.

**Pull request closed without merging**
