### PR TITLE
[@types/react-native] Add missing scrollEnabled property

### PR DESCRIPTION
**Pull request by mrnickel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/textinput#scrollenabled
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alloy** [comment]
There have been many changes around the linter just now, so maybe you need to rebase?

**Comment by iRoachie** [comment]
The errors are from the change made here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29766#event-1907413906. The other packages need to update their imports

**Comment by mrnickel** [comment]
@iRoachie @alloy so we are effectively blocked from merging this PR until #29766 is fixed?

**Comment by alloy** [comment]
I haven’t had the time to delve into it yet. It seems like maybe @iRoachie does, otherwise perhaps @andy-ms can chime in.

**Comment by iRoachie** [comment]
@alloy If you pass the CI and merge will the change still get deployed?

**Comment by andy-ms** [comment]
CI failures should be fixed by #29799

**Pull request merged**
