### PR TITLE
Threejs r75

### PR DESCRIPTION
**Pull request by florentpoujol**
Pull #8791 and #8807 should be merged first to avoid merge conflicts, since they don't change line numbers.

---

Not that much to update this time.

This PR includes the changes of pull #8793, and fixes issue #7718.

Pulls #6686 and #8793 can be closed without merge (not necessary anymore).

All the following issues can be closed, too :
https://github.com/DefinitelyTyped/DefinitelyTyped/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+three.js
https://github.com/DefinitelyTyped/DefinitelyTyped/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+threejs

@SereznoKot I added your name + link on the contributors line, tell me if you want to change something.

### CODE REVIEW

**Comment by SereznoKot** [comment]
@florentpoujol Thanks! It looks good, I can't go deep into it right now, it looks mostly good. But I think some features might be missing, like `physicallyCorrectLight` a new WebGLRenderer property. Or (whatever this is) "`getShaderPrecisionFormat` polyfill". The changelog is super shady and the docs don't cover many features...

**Comment by florentpoujol** [comment]
I did add the `WegGLRenderer.physicallyCorrectLights` property [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8825/files#diff-608bf71b2c6f0f0c969ffcb1576a05d0R4785).

`getShaderPrecisionFormat()`is a method of `WebGLRenderingContext` already defined [here](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L15142).
Nothing to add to Three.js definitions, but researching that allowed me to replace some `any` types by their proper ones.

**Comment by vvakame** [comment]
I'm waiting for response from gyohk. 
If we can't get response, I'll merge this PR. please ping me again in 2 days.

**Comment by florentpoujol** [comment]
@vvakame 
Humm, now Github says there is merge conflicts...
Please merge #8874 first, then if really required, I will check and resolve conflicts.

**Comment by vvakame** [comment]
@florentpoujol 👍

**Comment by florentpoujol** [comment]
- add fix for issue #8935 
- resolve merge conflict 
- squash commits

**Comment by vvakame** [comment]
so many file changes occured... https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8825/files
please fix it.

**Comment by florentpoujol** [comment]
There must have been an issue with Github or something else because I did saw all the commits included in the PR, but now I reloaded the page and they are gone..

On my end, this PR currently has one commit and one file changed.

**Comment by vvakame** [comment]
@florentpoujol it is our mistakes... and I repaired it. sorry...

**Comment by florentpoujol** [comment]
@vvakame No problem ! Thanks for your work on DT !

**Pull request merged**
