### PR TITLE
Mathjs add matrix properties

### PR DESCRIPTION
**Pull request by scttcper**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/josdejong/mathjs/blob/master/lib/type/matrix/SparseMatrix.js
https://github.com/josdejong/mathjs/blob/master/lib/type/matrix/DenseMatrix.js
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by vvakame** [comment]
@andy-ms what's mean `Revision requested`?

**Comment by andy-ms** [comment]
"Revision requested" means there were comments on the PR, but were not blocking.
But I forgot to submit them...

**Comment by scttcper** [comment]
Thanks for the review! Fixed.

**Pull request merged**
