### PR TITLE
Adding @types/s3-streams

### PR DESCRIPTION
**Pull request by azatoth**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by azatoth** [comment]
> @azatoth The CI build failed! Please [review the logs for more information](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/418a92953c4be21cf5bc588a46239e4c811aa3ca/checks?check_suite_id=903828876).
> 
> Once you've pushed the fixes, the build will automatically re-run. Thanks!

The error seems to be "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"; I assume this error is not fixable by me?

**Comment by azatoth** [comment]
> @azatoth I haven't seen any activity on this PR in more than 3 weeks, and this PR currently has problems that prevent it from being merged. The PR will be closed in a week if the issues aren't addressed.

As far as I can see, the build problem is not fixable by this PR; something on the build server is breaking.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@azatoth thx for the contribution!

Your branch diverged so much, it requires a rebase, otherwise the CI gets stuck due to amount of changes in the diff. I've got the same failures locally until I've rebase with current master:
```cli
git checkout master
git pull upstream/master
git checkout -
git rebase master
git clean -fxd
npm i
cd types/s3-streams
npm i --no-package-lock
cd ../..
npm test
```
when green:
```cli
git push -f
```
I've got this locally:
```cli
npm test

> definitely-typed@0.0.3 test C:\github\DefinitelyTyped
> node node_modules/@definitelytyped/dtslint-runner/dist/index.js --path .

Using local DefinitelyTyped at .
Parsing definitions...
Found 6993 packages.
Parsing in 12 child process(es)...
Parsing took 22.516 s
Running: git rev-parse --verify master
7914a6af72ed1f95ee850b1f82e1beee189fbb97
Running: git diff master --name-status
A       types/s3-streams/index.d.ts
A       types/s3-streams/package.json
A       types/s3-streams/s3-streams-tests.ts
A       types/s3-streams/tsconfig.json
A       types/s3-streams/tslint.json
Testing 1 changed packages: s3-streams
Testing 0 dependent packages:
Installing NPM dependencies...
  ./types/node: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links --no-save
 from ./types/node: up to date in 1.027s
found 0 vulnerabilities
  ./types/s3-streams: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links --no-save
 from ./types/s3-streams: audited 14 packages in 0.471s
found 0 vulnerabilities
1> s3-streams START
1> s3-streams OK


=== SUGGESTIONS ===

{}


=== PERFORMANCE ===

{ "s3-streams": 104619, "react-plotly.js": 27950, "office-js-preview": 20534, "update-notifier": 18108, "plotly.js": 14354, "ally.js": 10243, "granim": 9438, "weak-napi": 8943, "calc-percent": 2123}
  * Percentiles:
99: 104619
95: 104619
90: 73951.39999999998
70: 20048.8
50: 14354
```

**Comment by peterblazejewicz** [comment]
@orta @sandersn 
I've checked the api status, nothing similar comes out. We had a hard time to pass this PR through CI gate.

Even after branch has been rebased, so relevant changes are diff-ed during CI tests, there is still a peculiar error in the logs, which seems to be pointint to memory allocation issues:

> 1> s3-streams START
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

This PR is a nice use-case, it compiles now properly when tested locally and have nice diff.

**Comment by sandersn** [comment]
My initial guess is that aws-sdk is too big to compile at the same time as node types. Except that several other packages that depend on aws-sdk also depend on node types.

**Comment by sandersn** [comment]
@andrewbranch is going to investigate since he's on DT duty this week.

**Comment by andrewbranch** [comment]
’Tis fixed

**Pull request merged**
