### PR TITLE
feat(itemsjs): add chosen_filters_on_top on Aggregation

### PR DESCRIPTION
**Pull request by mikaoelitiana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/itemsapi/itemsjs#configuration
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
Could you run Prettier on this code (i.e. `npm run prettier -- -w types/itemsjs`)? It makes it easier to review since only the actual new changes are highlighted, and it keeps the code style more consistent

**Comment by mikaoelitiana** [comment]
@MysteryBlokHed I have just pushed the updated code, thanks

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by mikaoelitiana** [comment]
Ready to merge

**Pull request merged**
