### PR TITLE
fix: fix getIssue API in jira-client

### PR DESCRIPTION
**Pull request by ioioioion**
fields should be array
doc from jira
https://developer.atlassian.com/cloud/jira/software/rest/api-group-issue/#api-agile-1-0-issue-issueidorkey-get

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Worlor** [comment]
Hello @ioioioion 
Thanks for your PR

I have quickly checked the JSDoc of jira-client and the query parameter is typed as string. 
https://github.com/jira-node/node-jira-client/blob/c91de649eb08d7dfe31c87191d5edfc889a748a5/src/jira.js#L1537

Can you confirm using a string doesn't work ? Have you tested your commit ?
Can you please add a test ?

**Comment by ioioioion** [comment]
> Hello @ioioioion
> Thanks for your PR
> 
> I have quickly checked the JSDoc of jira-client and the query parameter is typed as string.
> https://github.com/jira-node/node-jira-client/blob/c91de649eb08d7dfe31c87191d5edfc889a748a5/src/jira.js#L1537
> 
> Can you confirm using a string doesn't work ? Have you tested your commit ?
> Can you please add a test ?
@Worlor Thanks for checking. Actually, since it is a query parameter, it naturally accepts both string and string[] type. Both type will work. However, according to the official doc, it should be the array type. And I tested it using the jira-client and postman. The array type will work and it would be more suitable for my feature requirement.
image

https://github.com/jira-node/node-jira-client/blob/75c59dacd7b04f1a2c58bb9b8adc96b6d0717809/src/jira.js#L258

**Review by QuentinLemCode — CHANGES_REQUESTED** [review]
Thanks for reply
If the parameter accept both string and array, please type it with "string | string[]"

**Comment by ioioioion** [comment]
@Worlor Sure, updated!

**Review by rkesters — APPROVED** [review]

**Review by QuentinLemCode — APPROVED** [review]

**Pull request merged**
