### PR TITLE
meteor: strong typings for mongo collections selectors and modifiers

### PR DESCRIPTION
**Pull request by andrei-markeev**
### Rationale

Personally was struggling for a long time with the lack of intellisense in Mongo selectors and modifiers. This prevents efficient refactoring of data model. Using mapped and conditional types from TypeScript 2.8 I finally managed to solve this problem, and all selectors except composite (e.g. "arr.$.prop") are now covered by intellisense. Thanks to this change I was able to spot couple of serious bugs in a production application I am developing.

### Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.mongodb.com/manual/reference/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by ardatan** [comment]
Does this update satisfy the usage like; (obj: { attr })
```ts
Collection.find({
'obj.attr': value
})
```

**Comment by andrei-markeev** [comment]
Yes, it does, note the `& Dictionary<any>` in the definitions. But when using this syntax, obviously there won't be any good intellisense.

As you can see on the screenshots below, `find` that uses `'inlineLinks.objectType'` passes validation alright, while still preserving correct intellisense when using property identifier.

image

image

**Comment by ardatan** [comment]
Yes, you're right, it's my fault. Sorry for that.
Thank you again for this great update!
It looks good to me!

**Review by ardatan — APPROVED** [review]

**Review by pgrm — APPROVED** [review]

**Comment by ardatan** [comment]
Hello, many people are using these typings for Angular-Meteor projects, then they are facing some problems because Angular uses TypeScript 2.7.2. So is it possible to make it compatible?

**Comment by andrei-markeev** [comment]
Conditional and mapped types are supported only starting from TS 2.8... the only option to make it compatible seems to be roll it back completely and wait until Angular upgrades to TS 2.8+...

**Pull request merged**
