### PR TITLE
chore(tough-cookie): @types package is not needed as of tough-cookie v5

### PR DESCRIPTION
**Pull request by wjhsf**
tough-cookie provides its own types as of the [v5 release](https://github.com/salesforce/tough-cookie/releases/v5.0.0).

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jakebailey** [comment]
This is an incredibly popular package; 12.8 million weekly downloads. There are also a load of packages within DT which depend on `@types/tough-cookie`, unfortunately the DT infra is not smart enough to recognize that these may break. Are the new types added to `tough-cookie` v5 compatible with what was written here in v4?

We may need to not change `notNeededPackages` and just delete the package from DT, which would prevent a stub package from being published and force deps on v5.

**Comment by wjhsf** [comment]
> This is an incredibly popular package; 12.8 million weekly downloads. There are also a load of packages within DT which depend on @types/tough-cookie, unfortunately the DT infra is not smart enough to recognize that these may break. Are the new types added to tough-cookie v5 compatible with what was written here in v4?

Our goal with the v5 release was to minimize API changes (we did end up with a few minor ones). Assuming the types here accurately reflect the v4 API, they should be compatible. I'll compare the two and see if there's any incompatibility.

**Comment by jakebailey** [comment]
Just to be clear, the names of types themselves is also critical, not just the runtime shape; that's where the main hurt can come from. If they're the same, this PR theoretically is okay as-is.

**Review by moltar — APPROVED** [review]

**Comment by wjhsf** [comment]
Sadly (but unsurprisingly), it turns out there are some differences. The biggest is that the `@types` package defines two namespaces that we don't use in the v5 release. The rest are largely around `null`/`undefined`, and a few minor bugs.

<details>
<summary>Breakdown of differences</summary>
Comparison of top-level exports (excluding classes):

| export | `@types/tough-cookie` v4 | `tough-cookie` v5 |
| - | - | - |
| `canonicalDomain` | accepts/returns values | allows null-ish parameters, can return `undefined` |
| `cookieCompare` | `Cookie` parameters | `Cookie` parameteters (but not the same `Cookie`) |
| `defaultPath` | accepts/returns values | allows null-ish parameters |
| `domainMatch` | accepts/returns values | allows null-ish parameters, can return `undefined` |
| `formatDate` | ✅ | ✅ |
| `fromJson` | `(json: string) => Cookie` | `(json: unknown) => Cookie \| undefined`, different `Cookie` |
| `getPublicSuffix` | | has additional `options` parameter, can return `undefined` |
| `parseDate` | accepts/returns values | allows null-ish parameters, can return `undefined` |
| `parse` | accepts options, returns `Cookie` | different `Cookie`; options are compatible, but named differently |
| `pathMatch` | ✅ | ✅ |
| `permuteDomain` | | can return `undefined` |
| `permutePath` | ✅ | ✅ |
| `PrefixSecurityEnum` | `string` values | string literal values |
| `version` | `string` | string literal |
| `namespace CookieJar` | | ❌ Does not exist |
| `namespace Cookie` | | ❌ Does not exist |

Comparison of the `Cookie` class:

| property | `@types/tough-cookie` v4 | `tough-cookie` v5 |
| - | - | - |
| `static parse` | accepts options, returns `Cookie` | different `Cookie` definitions; options are compatible, but named differently |
| `static fromJson` | `(json: string \| object) => Cookie \| null` | `(json: unknown) => Cookie \| undefined`, different `Cookie` |
| `constructor` | accepts `Cookie.Properties` | accepts `CreateCookieOptions` (TBD: different?) |
| `expires` | | can also be `null` |
| `maxAge` | | can also be `null` |
| `creation` | | can also be `"Infinity"` |
| `lastAccessed` | | can also be `"Infinity"` |
| `sameSite` | | can also be `undefined` |
| `expiryTime` | returns `number` | can return `undefined`  |
| `expiryDate` | | ❌ A regression. We accidentally deleted it! 🫠 |
| `TTL` | accepts `Date` (inaccurate type) | accepts `number` |
| `canonincalizedDomain` | can return `null` | can return `undefined` |
| `cdomain` | can return `null` | can return `undefined` |
| `inspect` | | ❌ removed |
| `toJSON` | returns `{[key: string]: any}` | returns `{key?: string; value?: string; [key: string]: unknown}` |
| `clone` | returns `Cookie` | returns (different) `Cookie` or `undefined` |
| `validate` | returns `boolean \| string` | only returns `boolean` |
| `key` | ✅ | ✅ |
| `value` | ✅ | ✅ |
| `domain` | ✅ | ✅ |
| `path` | ✅ | ✅ |
| `secure` | ✅ | ✅ |
| `httpOnly` | ✅ | ✅ |
| `extensions` | ✅ | ✅ |
| `creationIndex` | ✅ | ✅ |
| `hostOnly` | ✅ | ✅ |
| `pathIsDefault` | ✅ | ✅ |
| `toString` | ✅ | ✅ |
| `cookieString` | ✅ | ✅ |
| `setExpires` | ✅ | ✅ |
| `setMaxAge` | ✅ | ✅ |
| `isPersistent` | ✅ | ✅ |


Comparison of `Store` class:

| property | `@types/tough-cookie` v4 | `tough-cookie` v5 |
| - | - | - |
| (meta) | `abstract` class | not `abstract` |
| `synchronous` | ✅ | ✅ |
| `findCookie` | string params, callback can recieve `null` | params can be null-ish, callback can receive `undefined` |
| `findCookies` |
| `putCookie` | accepts `Cookie` | accepts different `Cookie` |
| `updateCookie` | `Cookie` params | accepts different `Cookie` |
| `removeCookie` | string params | params can be null-ish |
| `removeCookies` | string params | params can be null-ish |
| `removeCookies` | string params | params can be null-ish |
| `removeAllCookies` | missing (exists at runtime) | defined |
| `getAllCookies` | returns `Cookie[]` | returns different `Cookie[]` |

Additionally, for `Store`:
- The `@types` package only contains callback signatures for methods. The v5 package has overloads for the promise signature. (The promise signature existed in v4, but was not included in the types.)
- The signature of callbacks is more strict in v5. The `@types` package allows `cb(null, null)` and `cb(error, result)`, while the v5 package requires one of `error` and `result`, but not both.
- The v4 signature

Comparison of the `MemoryCookieStore` class:
- Same as the `Store` class, but contains overloads for the promise signatures of methods.

Comparison of the `CookieJar` class:

- For the purposes of this discussion, I think we've established that there are enough differences between the two sets of type definitions to warrant careful action. I don't have time at the moment to do a full comparison of the `CookieJar` methods (there are a lot of overloads), but I'm happy to do so upon request.

</details>

**Comment by moltar** [comment]
> I'd recommend deleting the types but skipping the deprecation.

Could you explain why this is the recommended approach?

I am not questioning your suggestion, just trying to learn, as I rely on the `notNeededPackages.json` data for my internal build pipelines.

Thanks.

**Comment by jakebailey** [comment]
It comes down to some bad effects of the way DT works.

When you add a package to `notNeededPackages.json`, it instructs the publisher to publish a "stub" package which contains no declarations, but instead a single dependency on the package it previously typed.

However, loads of packages use `*` deps; in fact, before we switched to a proper monorepo, we had no ability to specify other DT packages at specific version ranges. This itself can cause bad effects; we have cases where we bump a major version on DT and then people complain because their package managers are resolving `*` to be the latest version (and not to "any" version, preferring already installed versions). That itself may be improved by https://github.com/microsoft/DefinitelyTyped-tools/pull/1072.

I believe the overlap of these two can be slightly worse, though I'm now not able to come up with the broken case...

The worst part is when a package changes its types significantly enough to where those unpinned users break heavily; leaving the existing package behind can help keep people on working code, but that won't help anyone that actually upgrades to `tough-cookie` v5, so, in reality I'm not sure of the best thing here.

**Comment by moltar** [comment]
> However, loads of packages use `*` deps

But isn't it _their_ problem? 😁 

> but that won't help anyone that actually upgrades to `tough-cookie` v5

That's the problem I ran into and why I came here.

I've upgraded, but the type declaration package remained. This created lots of compiler errors. It might also be due to the way I had it setup, where I explicitly tell TS about every types package:

```json
    "types": [
      "node_modules/@types/node",
      "node_modules/@types/tough-cookie"
    ],
```

**Comment by jakebailey** [comment]
> But isn't it _their_ problem? 😁

I mean, we put them in the DT package, so it's sort of our problem for having done it. There are upsides and downsides :(

> I've upgraded, but the type declaration package remained. This created lots of compiler errors.

TS is supposed to ignore the types package once the real one has types, so that's interesting.

**Review by gabritto — APPROVED** [review]

**Review by gabritto — CHANGES_REQUESTED** [review]
I missed the comments the first time, but could you remove the change to `notNeededPackages.json`? Thanks.

**Review by gabritto — APPROVED** [review]

**Review by moltar — APPROVED** [review]

**Comment by wjhsf** [comment]
Ready to merge

**Pull request merged**
