### PR TITLE
Unwrap Bluebird.props() via generics

### PR DESCRIPTION
**Pull request by fengb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://bluebirdjs.com/docs/api/promise.props.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by fengb** [comment]
image
image
image
image

image
image
image

**Comment by lhecker** [comment]
@fengb Again, thanks for your contribution. 🙂

We should add at least a simple test for this though. Something like this ought to be enough:
```diff
diff --git a/types/bluebird/bluebird-tests.ts b/types/bluebird/bluebird-tests.ts
index e616ae3..9469d4f 100644
--- a/types/bluebird/bluebird-tests.ts
+++ b/types/bluebird/bluebird-tests.ts
@@ -576,7 +576,6 @@ barProm = fooArrProm.spread<Bar>((one: Foo, two: Bar, twotwo: Foo) => {
 //TODO fix collection inference
 
 barArrProm = fooProm.all<Bar>();
-objProm = fooProm.props();
 fooInspectionPromise = fooProm.reflect();
 barProm = fooProm.any<Bar>();
 barArrProm = fooProm.some<Bar>(num);
@@ -584,6 +583,12 @@ barProm = fooProm.race<Bar>();
 
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
+var propsValue: { num: number, str: string };
+Promise.resolve({ num: 1, str: 'a' }).props().then(val => { propsValue = val });
+Promise.props({ num: 1, str: Promise.resolve('a') }).then(val => { propsValue = val });
+
+// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 Promise.all([fooProm, barProm]).then(result => {
   result[0].foo();
   result[1].bar();
```

You can test wether it works by simply running `tsc` in the bluebird typings folder. 🙂

While the above is pretty much required, I'd also _optionally_ suggest merging the 4 static props functions into 2, by rewriting

```
static props<...>(val: T): Bluebird<...>;
static props<...>(val: PromiseLike<T>): Bluebird<...>;
```

into

```
static props<...>(val: T | PromiseLike<T>): Bluebird<...>;
```

I'm sorry that you had such a troublesome start in contributing to DefinitelyTyped. 😕

<hr>

I like @fengb's idea of creating the [`ResolvableProps` type alias](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17415/files#diff-c2c9c8ed83a544dde1d6157843211ccaR1079).
Do you think it would be a good API design for the bluebird typings if we replace all occurences of `T | PromiseLike<T>` with a type alias `Resolvable<T>` which would do the same (but as an alias)?
I fear that due to the additional layer of indirection people looking at those function signatures might be hindered in their work, since the type alias hides away what's allowed as a parameter, while the current solution makes it absolutely clear at the first look. We could also call it `ValueOrPromiseLike<T>` or something... idk.

@andy-ms @DanielRosenwasser @sandersn If someone of you guys has time I'd be glad to hear your thoughts about my idea in the above paragraph. 🙂

**Comment by fengb** [comment]
If I added an alias, I could slim the definition down:
```typescript

type Resolvable<T> = T | PromiseLike<T>;
static props<K, V>(map: Bluebird.Resolvable<Bluebird.ResolvableProps<Map<K, V>>>): Bluebird<Map<K, V>>;
static props<T>(object: Bluebird.Resolvable<Bluebird.ResolvableProps<T>>): Bluebird<T>;
```

It kinda looks like gobbledygook to me though.

**Comment by lhecker** [comment]
@fengb Hahaha "gobbledygook"... 😂 That really is a crazy word I've never heard before.

Anyways: Yeah, that was my concern as well. Maybe let's just keep it as it is right now. For this PR I just need the added test above though. 🙂

**Comment by lhecker** [comment]
@fengb Tests added. LGTM. 🙂 Thanks for this awesome contribution - I'm so so sorry for all the hops and troubles you had to go through though. I promise your next one will be easier. 🙂

@sandersn This is ready for merging.

**Comment by fengb** [comment]
Not a problem. Better to have a cleaner implementation than merging earlier.

**Comment by SimonSchick** [comment]
Hey @basarat @sandersn this was merged almost a day ago but not published, the readme states it should only take a few hours, can you maybe poke the publish? 🙂

**Pull request merged**
