### PR TITLE
[bookshelf] Model#orderBy and Collection#orderBy

### PR DESCRIPTION
**Pull request by vesse**
orderBy introduced in Bookshelf 0.9.3

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/tgriesser/bookshelf/blob/0.10.3/src/model.js#L1245-L1270>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Review by arcticwaters — CHANGES_REQUESTED** [review]
I think we should define the parameters explicitly here instead of relying on ...args. See the helper method that actually gets called: https://github.com/tgriesser/bookshelf/blob/0.10.3/src/helpers.js#L88-L126

**Comment by arcticwaters** [comment]
Also bump the version to 0.9.3 in the comment please :smile:

**Comment by vesse** [comment]
@arcticwaters Done. What do you think, should the order parameter be a type instead of string? Only two possible values but type would make it case-sensitive.

**Comment by arcticwaters** [comment]
That's an interesting idea. I don't have enough typescript swapped into my head yet to tell you if there's something simple that we could use that transpiles down to a string.

A quick read of the [handbook](https://www.typescriptlang.org/docs/handbook/enums.html) says enums would have to look like:
```
var nameOfA = Enum[Enum.A]; // "A"
```
which isn't too nice.

If you can think of a better idea than enums, I'm all ears. I'll stamp these changes for now unless you have an idea.

**Review by arcticwaters — APPROVED** [review]

**Comment by vesse** [comment]
Well this would work:

```
type SortOrder = 'ASC'|'asc'|'DESC'|'desc';

orderBy(column: string, order?: SortOrder);
```

Then caller would still write `orderBy('colName', 'DESC')` but the type would make it sure that the value is one of the allowed ones.

**Comment by arcticwaters** [comment]
This approach sounds good :+1:.

The minimum typescript that supports this is 1.6, released at the end of 2015. I think we can drop support for earlier versions (if we haven't implicitly already).

**Pull request merged**
