### PR TITLE
Add generic type support for functions in `humps` package.

### PR DESCRIPTION
**Pull request by willbrazil**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
```
const myDict = { hello: "world" };

// Current version
humps.camelizeKeys(myDict); // return type: Object

// With PR change
humps.camelizeKeys<{hello: string}>(myDict); // return type: {hello: string}
```

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by willbrazil** [comment]
@nikeee @vvakame

**Comment by willbrazil** [comment]
@nikeee @vvakame

**Comment by willbrazil** [comment]
@nikeee @vvakame

**Review by nikeee — COMMENTED** [review]
I think this change is not compliant with the "hidden type assertions" rule listed in the "Common Mistakes" section of the README, as T does not occur in any parameter:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes

TS lacks the ability to map type names, so it won't be possible to make this generic.

What we could change, is `Object` to `object`. The object type didn't exist when the definition was written IIRC.

**Comment by willbrazil** [comment]
You're absolutely right! Closing PR.

**Pull request closed without merging**
