### PR TITLE
[giphy-api] Add types

### PR DESCRIPTION
**Pull request by screendriver**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by plantain-00 — APPROVED** [review]

**Review by armanio123 — CHANGES_REQUESTED** [review]
There's a couple of properties that are not documented. You know more about the service, if you know they are implemented but not documented leave a note on the comment and I can merge as is.

I also suggest separating in different interfaces the `GIF Object`. Just my preference you can get away with it if it's too much work.

**Comment by screendriver** [comment]
@armanio123 thank you for the very detailed review! 👍 
I just copied and pasted the response directly from the API result, changed the strings and numbers to `string` and `number` and didn't look at the official API documentation ☺️ So should we adopt it or should we let it as it is? What do you think?

**Comment by armanio123** [comment]
I would go with the documentation but you are better at deciding that since you know more the API. If you think the documentation is not up to date or inaccurate it might be better to use the API result.

**Comment by screendriver** [comment]
@armanio123 I changed the types. They align now with the official [API docs](https://developers.giphy.com/docs/) 😉

**Review by armanio123 — APPROVED** [review]

**Pull request merged**
