### PR TITLE
Superfine amendments

### PR DESCRIPTION
**Pull request by jameswilddev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (multiple; included below)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

When I originally uploaded types for the superfine package, I made a number of mistakes.

Firstly, I allowed the use of SVG elements anywhere.  After [seeing how it's implemented under the hood](https://github.com/jorgebucaran/superfine/blob/a4d87a8e6faa9824b2b6ea227eafe727eabda3da/src/index.js#L42), I can see that this was not correct; it should only allow SVG elements within a SVG element.

Secondly, I forgot to include a clause in the types to allow for strings inside elements, such as `<div>example string</div>`, a common JSX pattern.  

Thirdly, it was not possible to omit children or include a single child directly rather than wrapping it in an array, another common JSX pattern.

### CODE REVIEW

**Comment by elibarzilay** [comment]
@jameswilddev: is this ready to be merged?  (And I'm assuming that you've looked at the perf change?)

**Comment by weswigham** [comment]
@jameswilddev ?

**Comment by jameswilddev** [comment]
Sorry, lost this chain.

I don't know enough about the performance metrics to know if they're particularly good or bad here.

**Comment by weswigham** [comment]
I'm not too terribly worried about the perf (the mean is down even if the worst case is up - the numbers in question are very small to begin with). If you're OK with your code changes, I can merge this.

**Comment by jameswilddev** [comment]
It should be good to go!

**Pull request merged**
