### PR TITLE
add(async-iterator-to-array): new definition

### PR DESCRIPTION
**Pull request by LinqLover**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by LinqLover** [comment]
@achingbrain Would you like to become a definition co-owner as mentioned above in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52635#issuecomment-828652491? :-)

**Comment by achingbrain** [comment]
@LinqLover - you should use [it-all](https://www.npmjs.com/package/it-all) instead - it's a drop-in replacement for `async-iterator-to-array` and already has types.

I've added a deprecation notice to `async-iterator-to-array`.

**Comment by achingbrain** [comment]
@LinqLover it's deprecated in favour of [it-all](https://www.npmjs.com/package/it-all), please use that instead.

**Comment by elibarzilay** [comment]
@LinqLover, @achingbrain: is this ready, or should @achingbrain be added?

**Comment by achingbrain** [comment]
@elibarzilay I think this should be closed without merging.

`async-iterator-to-array` is a deprecated module, people should use [it-all](https://www.npmjs.com/package/it-all) instead - it already has types.

**Comment by elibarzilay** [comment]
@LinqLover: given no further replies, I'll follow @achingbrain's request to close it.

**Pull request closed without merging**
