### PR TITLE
Remove deprecated gapi packages

### PR DESCRIPTION
**Pull request by jakebailey**
All of these packages are marked as deprecated and just reference another package. These aren't going to change, so if we simply delete them, they will remain on npm and continue to work, but we'll have a lot fewer packages that we need to `npm install` in CI. Right now, our DT tasks often time out while installing the `gapi.*` packages and hopefully this mitigates things a little.

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
I'm not opposed to this, but can you please describe what the upgrade path would be for the current users of these packages? Ideally I want to point users to the new packages somehow (like gapi.client.sheets users should migrate to gapi.client.sheets-v4 for example).
What do you think?

**Comment by Maxim-Mazurok** [comment]
Also, what will happen on the npm side? Will they be unpublished? Ideally I'd like to put up a depreciation notice with a link to the new ones.

**Comment by jakebailey** [comment]
> I'm not opposed to this, but can you please describe what the upgrade path would be for the current users of these packages?

Right now, these packages don't provide any sort of notification that they're deprecated; so removing them wouldn't change the status quo there.

The only method I'm familiar with would be to deprecate the packages. Normally we do that via notNeededPackages, but that isn't a good idea as that'll replace the package with an empty one and that definitely doesn't work for a non-npm package. To avoid that, we typically just straight up delete packages. Which to answer your next question:

> Also, what will happen on the npm side? Will they be unpublished?

Nope; if we delete them and don't add to `notNeededPackages`, they just sit and are never touched again, until a PR like this is reverted.

> Ideally I'd like to put up a depreciation notice with a link to the new ones.

We _could_ hand-deprecate them; DT maintainers have perms to act as the types-publisher and deprecate packages. We do this sometimes when npm breaks, but could do it on purpose here.

**Comment by jakebailey** [comment]
So, given all of these already have this deprecation text (which appears in the npm package readme), I think that I should be safe to delete these and hand deprecate them. Does that sound good?

**Comment by Maxim-Mazurok** [comment]
I see, there is a lot to deprecate by hand, I'd be happy to assist with writing a script for you to run locally.

Otherwise, the plan to delete them and deprecate them on NPM sounds fantastic. I will approve the PR as soon as they are deprecated, thank you!

**Comment by jakebailey** [comment]
I'll write a quick script; you've already written all of the deprecation messages out so I can just copy them (very convenient).

**Comment by jakebailey** [comment]
They're all now deprecated. It'll take a little for npm to propagate that change, but you can see the first one here: https://www.npmjs.com/package/@types/gapi.client.abusiveexperiencereport

**Comment by jakebailey** [comment]
The last one I deprecated is now showing on the site: https://www.npmjs.com/package/@types/gapi.client.youtubereporting

So, this is good to go.

**Review by Maxim-Mazurok — APPROVED** [review]
I trust that only deprecated packages were removed, which seems to be the case by glancing over the list, and npm packages do seem to have a correct deprecation notice now, which is amazing, thank you!

**Comment by jakebailey** [comment]
> I trust that only deprecated packages were removed, which seems to be the case by glancing over the list, and npm packages do seem to have a correct deprecation notice now, which is amazing, thank you!

Hah, yes, I used the same ripgrep command to delete things as I did to deprecate them.

**Pull request merged**
