### PR TITLE
Angular meteor

### PR DESCRIPTION
**Pull request by pgrm**
Type definitions for the [Angular-Meteor library](http://angularjs.meteor.com/). 

The second commit contains changes to meteor's type definitions. Some of them are valid improvements, and others rather to satisfy `npm test`. In case I shouldn't have had done those changes, I can just delete the second commit, but in that case `npm test` will be failing.

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-meteor/angular-meteor.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-meteor
  * http://bower.io/search/?q=angular-meteor
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-meteor/angular-meteor-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*meteor/meteor.d.ts*

to author(@fullflavedave). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by fullflavedave** [comment]
I’d be happy to review it on Monday.

Dave

**Comment by fullflavedave** [comment]
All of the changes to meteor.d.ts look good to me.  They are all improvements, and I'll add some tweaks to these once these changes are in.

**Comment by vvakame** [comment]
@fullflavedave :+1: 
@pgrm thanks mate!

**Pull request merged**
