### PR TITLE
add type file and tests for obelisk.js

### PR DESCRIPTION
**Pull request by bdrupieski**

### CODE REVIEW

**Comment by horiuchi** [comment]
Thank you for your contribution!
Please rename file to `obelisk.js/obelisk.js.d.ts`

https://www.npmjs.com/package/obelisk.js

**Comment by bdrupieski** [comment]
I think this is what you wanted. If there are any other changes I'll be happy to make them.

**Comment by vvakame** [comment]
*obelisk.js/obelisk.js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/obelisk.js
  * http://bower.io/search/?q=obelisk.js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (obelisk.js/obelisk.js-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
