### PR TITLE
[react-native] Added 'textAlign' prop to TextInput definition

### PR DESCRIPTION
**Pull request by erickriva**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://reactnative.dev/docs/textinput#textalign>>

### CODE REVIEW

**Comment by alloy** [comment]
Thanks! 👍

**Comment by yfunk** [comment]
@erickriva @alloy This PR also changes a bunch of type definitions regarding Keyboard Events. The commit for these changes (18321e2) is just called "..." without any additional details. Were these changes even intentional? If so, please provide more details about them.

The huge issue I see with these new definitions is, that they essentially remove`startCoordinates` and `isEventFromThisApp` from the `KeyboardEvent` type, because both of them don't exist on `AndroidKeyboardEvent`.
```
Keyboard.addListener('keyboardDidShow', event => console.log(event.startCoordinates));
```
IntelliSense won't suggest the parameters for auto-complete anymore and something like the code above would raise a TypeScript error. You can't even use the hacky approach of typecasting `event`, because none of the definitions are exported.

In my opinion, whether it was an indented change or not, this should be undone as soon as possible.

**Comment by erickriva** [comment]
> The huge issue I see with these new definitions is, that they essentially remove`startCoordinates` and `isEventFromThisApp` from the `KeyboardEvent` type, because both of them don't exist on `AndroidKeyboardEvent`.

@yfunk this commit just lint code, and as far i can see, this was made by own project commands. The props weren't removed.

image

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18321e2a41f05a4a23be3d417098b092c815a397#diff-e94ad9b79ba4f07235bfefa12c2789cd2d6cb690d9120309555f33ae51295244R9405

**Comment by yfunk** [comment]
>This commit just lint code, and as far i can see, this was made by own project commands. The props weren't removed in this commit (or in this PR).

You are right, sorry. I was looking on npm when the change was made, noticed it was in the most recent release (`0.63.37`) and it seems I just saw the green lines and plus signs in the latest commit to master (which was this PR).

**Pull request merged**
