### PR TITLE
[knockout] knockout no longer needed

### LINKED ISSUE #37490: ../node_modules/@types/knockout/index.d.ts:1060:13 - error TS2403
../node_modules/@types/knockout/index.d.ts:1060:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'ko' must be of type 'typeof import(".../node_modules/knockout/build/types/knockout")', but
here has type 'KnockoutStatic'.

1060 declare var ko: KnockoutStatic;

knockout.d.ts(5, 1): 'ko' was also declared here.

**The above fails to compile the index.d.ts type definition file.** 
As read in a stackoverflow comment, this is a **Typescript augmentation issue.** Is there a fix or patch available for this? 

I'm new to Typescript and this is a frustrating compile headache. 

My work around was to rename var ko to something else e.g. kot and the corresponding export value in the index.d.ts file @1060. Every fiber in my body knows this cant be right but compilation works for my js application.

kindly advice/ fix

### PR DESCRIPTION
**Pull request by viceice**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

depends on: https://github.com/microsoft/types-publisher/pull/665
fix https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37490

### CODE REVIEW

**Review by conficient — COMMENTED** [review]
Can I ask why you have removed Knockout? The PR has no details on what you are doing and why, and for such a large change some justification is required

edit: OK I've seen that Knockout now has its own types, but I am not sure removing it from DT is necessary - a lot of sites will depend on the defs here. Are the @types conflicting?

**Comment by ViceIce** [comment]
@conficient Yes, the types conflicting. The new types are renamed and namespaced.

**Comment by ltlombardi** [comment]
Correct if I'm wrong:
What is the normal behavior when something like this happens? 
If this were a "normal" software repository, a new version would be released with all the breaking changes and new features explained, and consumer of the library could just keep using the previous released.

Here, things are a little different. We don't have releases...
The releases are provided by NPM and are automatic. Can be seen [here](https://www.npmjs.com/package/@types/knockout).

What will happen to all those previous versions in NPM compatible with Knockout version 3.4 ? 
If they will be removed, than I don't thing it's a good idea to remove these typings.

**Comment by jessetrinity** [comment]
@ViceIce I'm thinking it is unlikely that you will get sign off from all of the owners of the dependent packages on this one PR. I would suggest opening PRs separately for the dependent packages to use the built in types for knockout before trying to remove them from DT.

@sandersn FYI

**Comment by ViceIce** [comment]
@jessetrinity How get I a successful ci build, if I only change depending package? It'll find duplicate knockout package.

**Comment by jessetrinity** [comment]
@ltlombardi the previous versions of the @types package will still be available up to the `asOfVersion` entry in `notNeededPackages.json`.

**Comment by sandersn** [comment]
From questions raised by @ltlombardi and @Retsam, it sounds like the community may want to continue updating the 3.4 typings even though 3.5 is out. This makes sense for a stable, widely used library.

If that's the case, we should keep these typings so the maintainers can continue to improve/fix the types for KO 3.4. @ltlombardi @Retsam is it the case that you (or others) want to keep updating the 3.4 types?

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes so typescript-bot knows the current state of the PR.

**Comment by Retsam** [comment]
@sandersn Yeah, I'd like to be able to keep updating the community types.

**Comment by ViceIce** [comment]
Sorry for late answer, I'm on holiday. I'll split this or the next weeks

**Pull request closed without merging**
