### PR TITLE
[node] Add async_hooks module

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://nodejs.org/dist/latest-v8.x/docs/api/async_hooks.html

### CODE REVIEW

**Comment by Flarna** [comment]
No idea why Travis complains about a lot modules not compiling with typescript 2.0. Can't imagine that this is related with my changes.

**Comment by paulvanbrenk** [comment]
@Flarna since so many modules depend on the nodejs typings, we test all those modules. 

@andy-ms what can we do to make this easier, we don't want to discourage people from contributing.

**Comment by Flarna** [comment]
@paulvanbrenk Testing all dependent modules is fine as it often shows real issues. For me it's don't care if I have to wait 2 min or 1 hour to get a CI result.
The annoying part is that a lot tests fail not related to the change. So it seems something was changed in these modules - or in the common testsetup -  without going through CI.

**Comment by Flarna** [comment]
should I add the line `// TypeScript Version: 2.3` in all the dependent modules?
Why are other PRs for Node not facing these fails?

**Comment by andy-ms** [comment]
All those tests are failing because this change uses the `object` type, which was not present in TypeScript 2.0.
I don't think it's worth switching a bunch of packages to TS2.3 just for that, so could you change it to `Object`?

**Comment by Flarna** [comment]
@andy-ms thanks, haven't seen this. Is there a plan to move min TS requirements? I can remember the times when this repo was switched from <2.0 to 2.0 to get support for strict null checks.

**Comment by andy-ms** [comment]
We'll probably want to upgrade `node` eventually, but I can't really say when. For packages other than `node` upgrades are usually fine, and new packages can start at any version.

**Comment by paulvanbrenk** [comment]
thanks @andy-ms

**Pull request merged**
