### PR TITLE
updated gojs definition and test files

### PR DESCRIPTION
**Pull request by WalterNorthwoods**
Renamed files to match library name, "go.js".
Allow alternative usage in TypeScript 2.0 after minor edit.
Fixed some minor bugs -- inconsistencies between the definition file and the actual JavaScript definitions.

### CODE REVIEW

**Comment by WalterNorthwoods** [comment]
The updated and renamed definition file works in both TypeScript 1.8 and TypeScript 2.0 both with and without use of modules.

**Comment by yuit** [comment]
@WalterNorthwoods could you resolve the conflict?

**Comment by WalterNorthwoods** [comment]
I don't know what the conflict is, so I don't know how to resolve it.

I know for sure that go-tests.ts works as a test file for the go.d.ts definition file, so I don't know what the conflict is.

**Comment by yuit** [comment]
@WalterNorthwoods you will have to merge master into your branch and resolve any conflict there

**Comment by paulvanbrenk** [comment]
@WalterNorthwoods Going to repeat what @yuit said. If you merge `master` into you branch you should be able to solve the merge issues and push another commit.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of response. Please open a new PR if you'd like to continue with this change. Thanks!

**Pull request closed without merging**
