### PR TITLE
lodash: Take, First, Last, and TakeRight, Head interfaces were incorrect.

### PR DESCRIPTION
**Pull request by park9140**
Targeting just one subset of related functions.  But the interfaces for these all seem to be a bit off.

https://lodash.com/docs#first
https://lodash.com/docs#take
https://lodash.com/docs#takeRight
https://lodash.com/docs#takeWhile
https://lodash.com/docs#takeRightWhile
https://lodash.com/docs#last
https://lodash.com/docs#head

### CODE REVIEW

**Comment by vvakame** [comment]
@bczengel @david-driscoll could you review this PR?

**Comment by park9140** [comment]
@bczengel @david-driscoll ping?

**Comment by vvakame** [comment]
@park9140 please resolve merge conflict.

**Comment by bczengel** [comment]
@park9140: This looks correct but can you follow the pattern of keeping first and its aliases separate from take and also from takewhile.  Just for consistency.

**Comment by park9140** [comment]
@bczengel, I have been looking at this on and off for a few weeks now, and I think these lodash definitions need a much larger refactor in order to have the definitions be correct.  Right now I mostly just cast it to any on almost everything I do since chaining is so broken.

**Comment by bczengel** [comment]
@park9140 That's not what I was saying.  I was just commenting on the organization of the code.  There is a comment for `//_.first` and then the definitions for first and its aliases.  There should also be a comment for take and takeWhile that follow the same pattern separate from first and head.

**Comment by chrootsu** [comment]
Unfortunately this RP contains too outdated changes. I think it can be closed.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
