### PR TITLE
Showdown changes

### PR DESCRIPTION
**Pull request by wiredprairie**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://github.com/showdownjs/showdown .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by cbowdon** [comment]
Thanks for bringing this up to date. Why are the tests no longer relevant?

**Comment by wiredprairie** [comment]
Looked like the extensions had moved into the main branch (which meant they weren't extensions anymore). Further -- that type of test felt like it belonged in the showdown project source as a test rather than testing the declaration file. I'd wanted the test to be stand-alone as much as possible.

**Comment by cbowdon** [comment]
I hear you, but disagree because the tests exercise type defs that are still present. It is beneficial for tests to cover as much of the .d.ts as possible. I recommend re-instating the tests before this is merged.

**Comment by wiredprairie** [comment]
Sorry, but I don't have time to fix the rest of the tests.

**Comment by wiredprairie** [comment]
I'm just going to use

    const showdown = require('showdown');   

instead as it's only in one place in my code. 

I'm not sure how the tests worked as they had dependencies on other packages apparently.

    Error: Extension "github" could not be loaded. It was either not found or is not a valid extension.

**Pull request closed without merging**
