### PR TITLE
recharts: Document presentation attrs in Label

### PR DESCRIPTION
**Pull request by paulmelnikow**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/recharts/recharts/blob/fd5b6c62f8f71d9fa02f5fbef54182f4365f96b4/src/component/Label.js#L316
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I opened recharts/recharts#1373 to make the equivalent fix in the lib's propTypes.

**Comment by mthmulders** [comment]
Thanks @paulmelnikow for this PR. It looks good to me. To be sure, let's wait for the Recharts PR to be accepted by the maintainers. If they consider this to be correct, so can we.

**Comment by royxue** [comment]
@paulmelnikow 
I think maybe it's better to add more Label attrs for tests?

**Comment by paulmelnikow** [comment]
Since this test doesn’t compile without the change, it seems like setting one is sufficient. I don’t feel strongly about it though.

**Comment by RyanCavanaugh** [comment]
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

**Pull request merged**
