### PR TITLE
RN: Fix typo and flukes

### PR DESCRIPTION
**Pull request by blaesus**
Fix typos and missing definitions as suggested in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9563#issuecomment-226154220

@bgrieder @joewood

### CODE REVIEW

**Comment by bgrieder** [comment]
@andyshuxin Hi Thanks for the PR. 
Would you mind fixing the `implicit any` errors reported by the Travis CI tests ?

**Comment by andyshuxin** [comment]
@bgrieder Sure. I see quite some errors in the test file as well. Is it expected or to be fixed?

**Comment by bgrieder** [comment]
@andyshuxin They should be fixed so that the Travis checks pass (even though a test file for a massive library like this one does not make a lot of sense IMHO)

**Comment by bgrieder** [comment]
@andyshuxin Thanks

👍 

Please merge

**Pull request merged**
