### PR TITLE
Add types for broken-link-checker

### PR DESCRIPTION
**Pull request by Haizzz**
Add types for [stevenvachon/broken-link-checker](https://github.com/stevenvachon/broken-link-checker)

Types generated with `dts-gen` with `Options` and `handlers` types added manually as `dts-gen` created them as any

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by Haizzz** [comment]
@stevenvachon I've generated a type file for your `broken-link-checker` library here. Would you be able to have a look?

**Comment by elibarzilay** [comment]
@Haizzz: do you want to continue waiting for @stevenvachon, or merge?

**Comment by Haizzz** [comment]
@elibarzilay since there's no existing types I think it's better to merge now if that's ok

**Comment by stevenvachon** [comment]
I plan to add JSDoc comments to broken-link-checker v0.8, which are supported by the TypeScript compiler. For v0.7.x, I think this looks fine.

**Pull request merged**
