### PR TITLE
Allow typing Express body, params, query and cookies through generics

### PR DESCRIPTION
**Pull request by alex3165**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by alex3165** [comment]
Should address the following issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16958

**Review by MichalLytek — APPROVED** [review]
LGTM!

**Comment by alex3165** [comment]
@andy-ms I don't really understand the CI issue here, can I have some help?

**Comment by alex3165** [comment]
@DanielRosenwasser I think the tests failing are unrelated to this PR now, should I fix it anyway?

**Comment by sheetalkamat** [comment]
@andy-ms Another instance where jsdoc redundant errors are reported during linting

**Comment by andy-ms** [comment]
Fixed.

**Comment by stewx** [comment]
This breaking my app's build, which uses Typescript 2.2.2

**Comment by 19majkel94** [comment]
You should stick to the old `@types` package version.

**Comment by DanielRosenwasser** [comment]
@stewx run `npm install @types/body-parser@ts2.2`

**Comment by stewx** [comment]
@DanielRosenwasser That didn't help me, unfortunately. The errors in my case arise from my dependency on `"@types/express": "4.0.33",`. Installing `@types/body-parser@ts2.2` and `@types/express@ts2.2` has had no effect.

**Comment by stewx** [comment]
(The errors in my case are in `node_modules/@types/express-serve-static-core/index.d.ts`)

**Comment by andy-ms** [comment]
@stewx You could add `"@types/express-serve-static-core": "4.0.53"` to your `package.json`.

**Comment by andy-ms** [comment]
OK, I've tracked down why we weren't adding the `ts2.2` labels appropriately -- `express-serve-static-core` isn't a linted package. So, `dtslint` doesn't lint, and instead runs `tsc` as an executable. The problem is that older versions of `tsc` will see `"strictFunctionTypes"` in the `tsconfig.json` and issue *just* that error. Newer versions will issue that error *and* any other compiler errors. So we thought everything was fine when it wasn't. A solution would be to enable linting on all packages.

**Comment by mhegazy** [comment]
The value this change adds seems very limited. the change however is fairly disruptive to the general population. I propose reverting this change and letting packages go back to 2.0 the way they were. 

This change forces users to a. know about `@types/express-serve-static-core` which is just a types construct, and does not correspond to a code npm package, or b. update their typescript version  to 2.3 or later. And after all of that, the value they get in  terms of additional type safety almost zero.

@19majkel94 any concerns here?

**Comment by alex3165** [comment]
@mhegazy for me it is adding lot of value as I have lot of data logic in my request handler and being able to type my body is a lot helpful but let's revert it if it is too much disruptive. One can still extends `express.Request` to add this feature:
```
interface TypedRequest<Body = any, Query = any, Params = any, Cookies = any> extends express.Request {
  body: Body;
  query: Query;
  params: Params;
  cookies: Cookies;
}
```

**Comment by 19majkel94** [comment]
> @19majkel94 any concerns here?

@mhegazy I agree, we should rollback the changes as `@types` doesn't have mechanism for cases like this yet. And the introduced functionality doesn't compensates the cons and costs of refactor/etc.

@alex3165 and other interested in this feature
You can safely take advantage of declaration merging and use this code in your projects: 
```ts
import { Express } from "express";

declare module "express" {
  export interface Request<
    Body = any,
    Query = any,
    Params = any,
    Cookies = any,
  > extends Express.Request {
    body: Body;
    query: Query;
    params: Params;
    cookies: Cookies;
  }
}
```

**Pull request merged**
