### PR TITLE
[entria]: Removes Entria experimental types

### PR DESCRIPTION
**Pull request by maraisr**
From the comment over at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48638#discussion_r510106511 we are safe to remove this.

cc @sibelius

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
tks

**Comment by elibarzilay** [comment]
Should this be included in `notNeededPackages.json`?

**Comment by maraisr** [comment]
Sorry, didnt know that was a thing!!! Sounds like i need to read the "contributing.md". 100% my bad. "

That being said, basically @sibelius forked the relay types for his company, but they are no longer using the forked version. And it was causing problems for the real types, so we wanted to remove it. So with that, would the `notNeededPackages.json` remove this package from testing etc...?

**Comment by elibarzilay** [comment]
(See the "Removing a package" section in the README, there is also a note saying that it's not always needed, so I'll leave it for you to decide...)

**Comment by maraisr** [comment]
@sibelius mate can you fix this? The package doesnt exist in npm, so maybe you can help me correct that.

At the end of the day @elibarzilay afaik this was a _private_ npm package, that is no longer being used at @sibelius's company, and its messing with my Relay types (needing the TS version upgrade), and causing failed tests etc... 

So is there another way I can remove this, without tests breaking?

**Comment by sibelius** [comment]
can we just remove it?

**Comment by renanmav** [comment]
I think its better to remove these types

**Comment by maraisr** [comment]
> @maraisr I haven't seen any activity on this PR in more than 3 weeks, and this PR currently has problems that prevent it from being merged. The PR will be closed in a week if the issues aren't addressed.
> 

I don't think there is an issue needing to be resolved. This is left up to the dt maintainers to access.

**Comment by elibarzilay** [comment]
@maraisr, sorry for missing this -- if it was never on npm, then no need to add it to that file...  (It's in the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/#removing-a-package) too...)

**Comment by elibarzilay** [comment]
@maraisr, since you didn't re-fix it, and it was my fault for misleading you in the first place, I rebased & re-removed the addition to `notNeededPackages.json`.

**Pull request merged**
