### PR TITLE
Added callback definitions to throught2

### PR DESCRIPTION
**Pull request by valotas**

### CODE REVIEW

**Comment by jedmao** [comment]
You need to add separate files for the old 0.4.2 definitions.

**Comment by valotas** [comment]
Did that. I do not know if I have to create and version specific tests though.

**Comment by jedmao** [comment]
I think you do.

**Comment by valotas** [comment]
I am not sure, but it was easy to copy the old file :)

**Comment by jedmao** [comment]
:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
