### PR TITLE
sinon: Add array matcher, set matcher and map matcher

### PR DESCRIPTION
**Pull request by nicojs**
The matchers are documented here: http://sinonjs.org/releases/v2.2.0/matchers/

Also added `noImplicitThis` and `strictNullChecks`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x]  Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint sinon` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://sinonjs.org/releases/v2.2.0/matchers/
- [x] Increase the version number in the header if appropriate. (not appropriate)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`. (no substantial change)

### CODE REVIEW

**Comment by rationull** [comment]
@lumaxis Looks like your contributor name in the header comment does not resolve to a format such that GitHub can ping you for code reviews :)

**Comment by nicojs** [comment]
Yeah, i took the liberty of fixing that to. Gave some love to our man @lumaxis :beer:

**Comment by lumaxis** [comment]
What an embarrassing typo 🤦‍♂️ Thanks for fixing @nicojs !

**Comment by rationull** [comment]
👍

**Pull request merged**
