### PR TITLE
Vortex Web Client definitions

### PR DESCRIPTION
**Pull request by Pro**
This is my first try on writing a definition file.
I'm open for any suggestions on how to do it better!
See also my question here: http://stackoverflow.com/questions/30326352/typescript-definition-file-with-submodules

### CODE REVIEW

**Comment by vvakame** [comment]
*vortex-web-client/vortex-web-client.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/vortex-web-client
  * http://bower.io/search/?q=vortex-web-client
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (vortex-web-client/vortex-web-client-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@Pro http://goo.gl/cmgHSg

**Comment by Pro** [comment]
@vvakame I tried your suggested style but then IntelliJ still complaints that `runtime` and other members can't be found in the namespace.

I now fully defined the interface so the code would be ready to merge. I also rewrote the parts so it's better style now.

**Comment by vvakame** [comment]
@Pro thanks mate!
IntelliJ(and WebStorm) are not using LanguageService of TypeScript compiler yet.
Please trust `tsc` messages.

**Pull request merged**
