### PR TITLE
[JSForce] Update types for methods in the SObject class

### PR DESCRIPTION
**Pull request by WhiteAbeLincoln**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://jsforce.github.io/jsforce/doc/SObject.html>>

Updates various methods under the SObject class. The catalyst for this pull request was the SObject.destroy method and aliases, which did not return promises like the [documentation](http://jsforce.github.io/jsforce/doc/SObject.html#destroy) indicates.

Also adds the SObject.updated and SObject.updateBulk methods, fixes the signature for SObject.bulkload to match the documentation, fixes the return types for SObject.find to match the callback value and the documentation, and fixes the callback types for some SObject caching methods that were obviously wrong.

### CODE REVIEW

**Comment by WhiteAbeLincoln** [comment]
I don't want to merge this one quite yet, I wanted to get some feedback from @dolanmiu about whether some of these types are intentionally different than the documentation or if I should just update

**Comment by dolanmiu** [comment]
@WhiteAbeLincoln 

I am not sure, I suppose it was a mistake, seems like it had always been Promise

and from checking, JSForce had always returned Query

**Comment by dolanmiu** [comment]
Can the other people look at this PR too? I am not actively using this library

**Comment by dolanmiu** [comment]
Good plan

**Comment by WhiteAbeLincoln** [comment]
Yup it looks like it. Thanks!

**Comment by WhiteAbeLincoln** [comment]
Ah actually I still have to change those fixme's I mentioned. Give me a bit.

**Comment by WhiteAbeLincoln** [comment]
Ok, we should be ready now

**Pull request merged**
