### PR TITLE
[sequelize] add limit, offset, order to IncludeOptions

### PR DESCRIPTION
**Pull request by gstamac**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Please provide documentation for why this change is correct.

**Comment by gstamac** [comment]
I couldn't find it in the documentation but if you check [here](https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts) you can find it in the IncludeOptions iterface.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
This is not right change since the package now ships with its types in itself. So you would want to remove this package from here instead. Refer to https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by todd** [comment]
@sheetalkamat We don't want to remove these types from this repo. The types that ship with Sequelize in the master branch are for v5. The types in this repo are for v4.

@gstamac If you can find documentation or source code for this in the `v4` branch, I'll approve this PR.

**Comment by gstamac** [comment]
I couldn't find it but I'm sure it works because we are using it and we have to add `// @ts-ignore`.

**Pull request closed without merging**
