### PR TITLE
[parse5] Set all `parse5*` packages as "not-needed"

### PR DESCRIPTION
**Pull request by hasezoey**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

This PR sets all `parse5*`  packages as "not-needed", see [parse5 release 7.0.0](https://github.com/inikulin/parse5/releases/tag/v7.0.0)

~~This PR is a WIP, because i am new to DefinitelyTyped and dont understand some things, which result in the tests failing, which currently include:~~
~~- using `parse5` in packages that require it, i am not sure how i should define the `dependencies` for this, should it be `parse5`? when yes, the tests complain that no types are found. if `@types/parse5`, should i really add it to [allowedPackageJsonDependencies.txt](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/definitions-parser/allowedPackageJsonDependencies.txt)? because there are not `@types/*` packages listed and `parse5` is already on there~~
nevermind, i think i have figured it out, there were actually `@types/` packages in the file, i had my browser search wrong configured

Depends on:
- [ ] https://github.com/microsoft/DefinitelyTyped-tools/pull/500 (waiting for the version to be published without beta)

### CODE REVIEW

**Comment by SimenB** [comment]
I opened #61299 which is a duplicate of this I guess (tho passing CI)

**Comment by hasezoey** [comment]
> (tho passing CI)

probably because i have not re-run the tests yet after the tools package had released the required update (because i am waiting for a proper release instead of just a "next" release of it)

**Comment by SimenB** [comment]
#61299 has landed fwiw

**Comment by hasezoey** [comment]
resolved by #61299

**Pull request closed without merging**
