### PR TITLE
Modified typings for version 2.11.2

### PR DESCRIPTION
**Pull request by doubleppereira**
case 1. Add a new type definition.
- [X ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [X ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [X ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
why need this change?

**Comment by Jogai** [comment]
@vvakame Because there is actual content in the d.ts file?

Please merge, the current definition file is confusing for newcomers to ts.

**Comment by adidahiya** [comment]
I don't see why this change is needed. No one has provided a description of / motivation for the PR yet. Please fill out the PR template correctly.

**Comment by oizie** [comment]
This was changed for version 2.11.2 because in our project the current TypeDefinitions are not correct. I changed to be in only one file since it's more simplified and tslint doesn't complain about it. If you don't think it's needed it's fine but in the end there is no need for two files when the main file only calls the other has a variable. With this version I don't have any complain from tslint and it's simpler for me.

**Comment by vvakame** [comment]
related? #8916

**Comment by oizie** [comment]
I would say so. This is for this version upwards of course the previous maybe couldn't be supported.

**Comment by mhegazy** [comment]
@oizie can you refresh this PR.

**Comment by oizie** [comment]
Since there is no need for this PR I have close it. Sorry guys

**Pull request closed without merging**
