### PR TITLE
Add createButton types for googlepay

### PR DESCRIPTION
**Pull request by Radu-Raicea**
New API changes added createButton, a method to request the creation of
a HTMLElement button.

Here's the [link](https://developers.google.com/pay/api/web/reference/client#createButton) to Google Pay's API Reference that contains `createButton`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by Fluccioni — CHANGES_REQUESTED** [review]
Following the docs, the createButton method does not return a Promise, but directly an HTMLElement.

**Comment by Radu-Raicea** [comment]
@Fluccioni 
You are right, I've changed that.

**Review by Fluccioni — APPROVED** [review]
Thank you 👍

**Comment by Radu-Raicea** [comment]
Can we get some ❤️ @RyanCavanaugh ?

**Comment by johnnyreilly** [comment]
Much ♥️

**Pull request merged**
