### PR TITLE
[jasmine] Allow CustomEqualityTester to return undefined

### PR DESCRIPTION
**Pull request by vrana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jasmine.github.io/2.5/custom_equality.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by gmoothart** [comment]
Can you explain the point of this change? Why is it ever useful to not return a value here?

An example in jasmine-tests.js would help too.

**Comment by lukas-zech-software** [comment]
Changes seem fine to me.

@gmoothart From the documentation of the `addCustomEqualityTester` function in jasmine:
> A function which takes two arguments to compare and returns a `true` or `false` comparison result if it knows how to compare them, and `undefined` otherwise.

for reference see https://github.com/jasmine/jasmine/blob/7f8f2b5e7a7af70d7f6b629331eb6fe0a7cb9279/src/core/requireInterface.js#L219

**Review by lukas-zech-software — CHANGES_REQUESTED** [review]
Please add a line to `jasmine-tests.ts` to demonstrate this behaviour.

Could be as simple as adding `return undefined` in [Line 878](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/jasmine-tests.ts#L878)

**Comment by vrana** [comment]
`return undefined` is implicit if the function doesn't return anything. I've fixed the return type in the test though.

**Review by lukas-zech-software — APPROVED** [review]

**Pull request merged**
