### PR TITLE
fix(react-window): params partial

### PR DESCRIPTION
**Pull request by jinxin0112**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/bvaughn/react-window/pull/479>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by jgoz** [comment]
The referenced PR is not merged or released yet, so we should wait to review these changes until that happens.

**Comment by jinxin0112** [comment]
@jgoz  ok, thank u

**Comment by elibarzilay** [comment]
Converted to draft, which is more proper given that you're waiting for that merge for a while now.  (And meanwhile this was collecting bot noise since I'm working on it, in draft it will be ignored...)

**Comment by jakebailey** [comment]
This PR hasn't been touched in 3+ years; I think it's safe to say that it isn't going to be updated at this point. I'm going to close this.

**Pull request closed without merging**
