### PR TITLE
custom values for marker option @types/leaflet

### PR DESCRIPTION
**Pull request by soupay**
Adding type support for customValues to be passed in MarkerOptions for different types of custom functionality

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40787>>

### CODE REVIEW

**Review by ronikar — COMMENTED** [review]
I didn't find `customValue` in leaflet documentation.
Can you add a reference to it in leaflet code?

**Comment by soupay** [comment]
> I didn't find `customValue` in leaflet documentation.
> Can you add a reference to it in leaflet code?

Yeah I figured its not an existing leaflet functionality. Let me talk to them to get it included as a parameter.

**Comment by ronikar** [comment]
You should do it in your types, locally

**Comment by henrythasler** [comment]
While I can understand that one might need something like that, I don't think it should be included in the official typings as it is unrelated to the current leaflet code.

**Review by henrythasler — COMMENTED** [review]
While I can understand that one might need something like that, I don't think it should be included in the official typings as it is unrelated to the current leaflet code.

**Review by sandersn — CHANGES_REQUESTED** [review]
Sounds like the type authors have some concerns about adding this. Requesting changes so the bot can understand the state.

**Comment by henrythasler** [comment]
I don't know how to tell that to the typescript-bot, but I'd rather reject this PR.

**Pull request closed without merging**
