### PR TITLE
Joi: Array.assertItem has been replaced by Array.has

### PR DESCRIPTION
**Pull request by afharo**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/joi/commit/028d6fe6dba45fe65397913d2a733b23987d6aa9
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Could you also add `hasKnown` and `hasUnknown`?

**Comment by afharo** [comment]
@SimonSchick I guess I can, but it will be just extending the Context type (and there are no other errors defined in types because they might all just extend Context).

**Comment by amcasey** [comment]
This looks like a breaking API change.  Should there be a version number bump?

**Comment by afharo** [comment]
@amcasey I didn't bump it to make it match the current Joi version: https://github.com/hapijs/joi/blob/v14.3.1/API.md

Tracing these changes, this method was first introduced in version 14.2.0 (but it was `has` already). I don't know why `.assertItem` was ever published.
I think the confusion comes from this PR: https://github.com/hapijs/joi/pull/1659. 
If you pay attention, just at the very end, there is a _Cleanup_ commit that renames `.assertItem` to `.has`.
This latest commit happened before publishing 14.2.0
image
So `.assertItem` was never a valid function. I sincerely doubt anyone is using it.

**Comment by amcasey** [comment]
@afharo Thanks for following up!

**Review by amcasey — APPROVED** [review]

**Pull request merged**
