### PR TITLE
prosemirror-state: narrow plugin state default from any to unknown

### PR DESCRIPTION
**Pull request by marionebl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
Cleans up the following [common mistake](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes) 
>  var foo: string | any: When any is used in a union type, the resulting type is still any [...]

### CODE REVIEW

**Comment by marionebl** [comment]
@bradleyayers @davidka @timjb @patsimm @mmorearty Any chance of a review for this?

**Comment by andrewbranch** [comment]
Can’t merge this without an owner approval since it’s essentially an opinionated change toward stricter types. This _will_ introduce type errors for people by making them opt _out_ of strictness instead of opt _into_ it. For popular packages, I usually tell people that the bar for breaking changes is that people need to be broadly enthusiastic about adopting them.

**Comment by marionebl** [comment]
> Can’t merge this without an owner approval since it’s essentially an opinionated change toward stricter types. This will introduce type errors for people by making them opt out of strictness instead of opt into it. For popular packages, I usually tell people that the bar for breaking changes is that people need to be broadly enthusiastic about adopting them.

Would that situation change e.g. if we marked this as breaking change (and accept a version mismatch with the implementation library?)

**Comment by andrewbranch** [comment]
We cannot accept a version mismatch with the library. However, if the library happens to ship a new major version, you could opportunistically include type-only breaks like this in the corresponding definition update. We don’t _enforce_ that type-only breaks only come with major version bumps, but realistically, this doesn’t seem worth the breakage. Anyone who wants to avoid `any` with the current definitions can simply pass a type parameter through. A breaking change worth making now would have to fix code that _actively prevents_ people from adopting stricter types. The current code just makes people type a few more characters.

**Comment by marionebl** [comment]
> We cannot accept a version mismatch with the library

Ok, I'll close the PR then, thanks for the review.

**Pull request closed without merging**
