### PR TITLE
feat(node): Add Web-compat utilities of stream.Writable

### PR DESCRIPTION
**Pull request by rokoucha**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    - [stream.Writable.fromWeb](https://nodejs.org/api/stream.html#streamwritablefromwebwritablestream-options)
    - [stream.Writable.toWeb](https://nodejs.org/api/stream.html#streamwritabletowebstreamwritable)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
   - N/A

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by rokoucha** [comment]
It looks like it's already broken on the master, should I fix it?

**Comment by peterblazejewicz** [comment]
@rokoucha just update from current master, there is a change for TS4.8 (upcoming) already merged, fixing CI

**Comment by rokoucha** [comment]
@peterblazejewicz Thanks for the comment, I rebased the branch and the CI was passed!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by rokoucha** [comment]
Ready to merge

**Pull request merged**
