### PR TITLE
Updated to version 4.0

### PR DESCRIPTION
**Pull request by chocolatechipui**
Added support for WHATWG Fetch API.

This passes the NPM and Travis-ci tests.

### CODE REVIEW

**Comment by vvakame** [comment]
@chocolatechipui thank you for your contributions.
please resolve conflict.

**Comment by chocolatechipui** [comment]
When I pull from upstream, I get that I'm up-to-date. Could you let me know what the branch conflict is?

**Comment by vvakame** [comment]
@chocolatechipui um? pull from borisyankov/DefinitelyTyped's master/HEAD? 
I tried this command locally. it conflicted.

```
$ git checkout -b chocolatechipui-master master
$ git pull https://github.com/chocolatechipui/DefinitelyTyped.git master
```

**Comment by mhegazy** [comment]
@chocolatechipui is this still needed? can you update the PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
