### PR TITLE
[workbox-webpack-plugin] Capitalize the first letter of the strings for ChacheStrategy

### PR DESCRIPTION
**Pull request by nhayashida**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/GoogleChrome/workbox/commit/4762e2f1747b6210d014f8a99d50e73b6d0c27cd#diff-62c78ac84720821c7fafca63da4de529
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

As it seems that the first letter of the strings for ChacheStrategy was capitalized in 4.x., would like to update the definitions to avoid the tslint errors.
https://github.com/GoogleChrome/workbox/commit/4762e2f1747b6210d014f8a99d50e73b6d0c27cd#diff-62c78ac84720821c7fafca63da4de529

### CODE REVIEW

**Review by kgroat — APPROVED** [review]
LGTM 👍

**Comment by rbuckton** [comment]
When upgrading the major version, please follow the steps outlined here: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by nhayashida** [comment]
I've copied the original code for v3.6 to v3 directory.

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
