### PR TITLE
[forge-viewer] added new error codes

### PR DESCRIPTION
**Pull request by egziko**
Added 2 missing error codes in `Autodesk.Viewing.ErrorCodes`

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
<https://aps.autodesk.com/en/docs/viewer/v7/reference/ErrorCodes/>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by yiskang** [comment]
Hi @egziko,

Sorry for the delay. Could you please add a test code in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/forge-viewer/forge-viewer-tests.ts to reflect this change?

**Comment by egziko** [comment]
I'm not sure how to these tests locally

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/forge-viewer/forge-viewer-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a6f64fe297bb99e1a8e6d6f07ce49009141bc4e7
</p>

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by egziko** [comment]
Ready to merge

**Pull request merged**
