### PR TITLE
[aws-lambda] Fix challengeMetadata typos in cognito custom challenge

### PR DESCRIPTION
**Pull request by repl-chris**
Just fixing a couple errors around cognito custom authentication challenges
 - For the *challengeMeta**d**ata* vs *challengeMeta**D**ata* typo, the [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html) are a bit misleading - the actual doc has incorrect casing, but if you look at the code samples they have correct casing.  I have verified that the actual implementation matches the samples, not the doc.
- For the type of *challengeAnswer* the [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html) are even worse - the JSON type definition near the top shows the incorrect type (hash of strings) but if you look down at the bottom at the example javascript usage, it is using it as a string (which I have also verified is what it actually is).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html> <https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by simonbuchan** [comment]
Woof! A pity those docs aren't [one of the open sourced ones](https://aws.amazon.com/blogs/aws/aws-documentation-is-now-open-source-and-on-github/)

**Comment by simonbuchan** [comment]
Regarding `challengeAnswer`, do you know where this value is coming from? With the string hash, I was assuming it was the [`ChallengeResponses` of `RespondToAuthChallenge`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html), but as a string, I can't figure out where it's from.

**Comment by repl-chris** [comment]
> Regarding `challengeAnswer`, do you know where this value is coming from? With the string hash, I was assuming it was the [`ChallengeResponses` of `RespondToAuthChallenge`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html), but as a string, I can't figure out where it's from.

In the case of `CUSTOM_CHALLENGE` the `ChallengeResponses` must contain an `ANSWER` key - it is that single value, all other keys are ignored.  I can't find any docs to back this up, this is purely via experimentation.

**Comment by simonbuchan** [comment]
Huh, they must have expected everyone to just use their client libraries 🙁 Thanks for the info!

**Pull request merged**
