### PR TITLE
jquery: Fix noConflict return type. Fix #5840

### LINKED ISSUE #5840: Shouldn't jQuery.noConflict return JQueryStatic?
Currently returns Object

### PR DESCRIPTION
**Pull request by typeofweb**
Fixes #5840.
Closes #6745 As well.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Hi @mmiszy,

First of all, thanks for the PR.  However, looking at [the docs](http://api.jquery.com/jQuery.noConflict/), `jQuery.noConflict` doesn't officially return `JQueryStatic`.  However, it looks like you're quite right about the return type of `jQuery.noConflict` and that this is a mistake in the docs.

We intend all our typings to be official API-compliant where there is one.  For that reason, could you raise a PR with the docs team to change the return type?  It should be pretty simple - just a one line change here:

https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.noConflict.xml#L2

Once that is merged I'd be happy to take this PR.

**Comment by mmiszy** [comment]
Hi @johnnyreilly. I'll make a pull request to the jquery docs then. Thanks! :+1:

**Comment by johnnyreilly** [comment]
Thanks @mmiszy 

Essentially this:

```
<entry type="method" name="jQuery.noConflict" return="Object">
```

Should become this (I think):

```
<entry type="method" name="jQuery.noConflict" return="jQuery">
```

**Comment by mmiszy** [comment]
Yup, this one should do https://github.com/jquery/api.jquery.com/pull/834

**Comment by mmiszy** [comment]
@johnnyreilly As explained in the closed PR https://github.com/jquery/api.jquery.com/pull/834, the change to the documentation is invalid because basically they don't have a specific type for the jQuery costructor (type `jQuery` means instance).

However, this pull request is valid because in the typings there's a specific type for jQuery constructor (`JQueryStatic`) and it should be used instead of a very generic `Object`.

**Comment by johnnyreilly** [comment]
I see; you're right.  A pragmatic merge then. I hope the docs will be more specific in future but it sounds like this should land anyway.

**Pull request merged**
