### PR TITLE
jquery.soap and js-md5 added

### PR DESCRIPTION
**Pull request by tigerxy**
here are the links to the projects:
https://github.com/doedje/jquery.soap
https://github.com/emn178/js-md5

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.soap/jquery.soap.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.soap
  * http://bower.io/search/?q=jquery.soap
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.soap/jquery.soap-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*js-md5/md5.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/js-md5
  * http://bower.io/search/?q=js-md5
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (js-md5/md5-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by tigerxy** [comment]
Can you check it? Is everything fine?

**Comment by vvakame** [comment]
still travis ci failed... https://travis-ci.org/borisyankov/DefinitelyTyped/builds/81268250#L200

**Comment by tigerxy** [comment]
It runs now! This is the first time I worked with travis ci. Sorry for that!

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
