### PR TITLE
Koa context allows dynamic properties

### PR DESCRIPTION
**Pull request by rslabbert**
Koa context allows additional properties, see the **app.context** heading in the link below.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: [https://github.com/koajs/koa/blob/v2.x/docs/api/index.md](https://github.com/koajs/koa/blob/v2.x/docs/api/index.md)

### CODE REVIEW

**Comment by vvakame** [comment]
Travis CI failed, but it is our problem.
types-2.0/HEAD is back to green now.

**Comment by yuit** [comment]
@RubenSlabbert  Thank you for the PR, Could you update it to take some fixes from the HEAD?

**Comment by RubenSlabbert** [comment]
My branch should now be up to date with origin.

**Comment by RubenSlabbert** [comment]
Up to date and tests pass.

**Pull request merged**
