### PR TITLE
[@types/asciichart] Add min/max config settings

### PR DESCRIPTION
**Pull request by jamesgpearce**
See https://github.com/kroitor/asciichart/pull/48

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kroitor/asciichart/pull/48
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## asciichart ([<kbd>unpkg</kbd>](https://unpkg.com/browse/asciichart@latest/))
was missing the following properties:
1. black
1. red
1. green
1. yellow
1. blue

<details>
<summary>as well as these 13 other properties...</summary>
<p>magenta, cyan, lightgray, darkgray, lightred, lightgreen, lightyellow, lightblue, lightmagenta, lightcyan, white, reset, colored</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 58276c21a9c5087e764b303f3bc3bfeb1dd76107
</p>

**Review by peterblazejewicz — COMMENTED** [review]
@jamesgpearce To be sure: this api change is not yet released to NPM? (otherwise this is ready to be merged, no fuss really)

**Review by orta — APPROVED** [review]

**Comment by jamesgpearce** [comment]
Yep! The npm release was super fast after the original PR. @kroitor an impressive maintainer :)

**Comment by jamesgpearce** [comment]
Ready to merge

**Pull request merged**
