### PR TITLE
Fix incorrect AddressType value for street_number

### PR DESCRIPTION
**Pull request by thewunder**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/places/web-service/details#PlaceDetailsResults
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by indrimuska — CHANGES_REQUESTED** [review]
From the [official documentation](https://developers.google.com/places/web-service/supported_types), street_number and street_address are both available, so you should append the new type rather than replace the old one.

**Comment by indrimuska** [comment]
Sorry, I had a mistake.

You are linking the documentation of the **PlaceDetailsResults** API, and as part of the `address_components` array, there is the `type` property. This latter one should be of type `PlaceType[]` (as per [doc](https://developers.google.com/places/web-service/details#PlaceDetailsResults)), instead of `AddressType[]` (that is used for [geocoding results](https://developers.google.com/maps/documentation/geocoding/intro#Types)).

Anyway `AddressComponent` has been defined here as a fixed type, and used in both geocoding and placetype api. Perhaps it should be a generic type, providing the given `type` property type (e.g. defined as`interface AddressComponent<T> { types: T[]; ... }` and used as `AddressComponent<PlaceType1 | PlaceType2>`).

**Comment by thewunder** [comment]
@indrimuska Yes, this would work plus street_address would need to be moved into GeocodingAddressComponentType, and street_number must be moved into a new PlaceDetailsAddressComponentType

**Comment by thewunder** [comment]
> From the [official documentation](https://developers.google.com/places/web-service/supported_types), street_number and street_address are both available, so you should append the new type rather than replace the old one.

In practice, it seems that place details returns street_number and never street_address

**Comment by orta** [comment]
@thewunder sorry it took us a while to get to this, are you happy with this PR?

**Comment by thewunder** [comment]
@orta Yeah I think this is a good fix

**Pull request merged**
