### PR TITLE
[@types/node] Add missing `method` property to `http.ClientRequest`

### PR DESCRIPTION
**Pull request by TooTallNate**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/2f45ad8060e13d5ac912335096d21526f2f9602b/lib/_http_client.js#L158-L165

### CODE REVIEW

**Review by galkin — CHANGES_REQUESTED** [review]
@TooTallNate, thank you for your work. Could you update node v10 also with the same changes?

**Comment by TooTallNate** [comment]
Sure thing. Pushed to v10 as well.

**Comment by galkin** [comment]
@TooTallNate, there are two pull: this and that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41030. I think you pushed to wrong one.
One more thing you need node.js v10 in both.

**Comment by TooTallNate** [comment]
Merged #41030 into this one.

**Review by Flarna — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Review by galkin — APPROVED** [review]

**Review by trivikr — APPROVED** [review]

**Pull request merged**
