### PR TITLE
[caseless] Adds dict key to object

### PR DESCRIPTION
**Pull request by joshuaharry**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See https://github.com/request/caseless/blob/98079105e15e04308d1f3becc3e8efab8ddd7f0e/index.js#L2, https://github.com/request/caseless/blob/98079105e15e04308d1f3becc3e8efab8ddd7f0e/index.js#L14

### CODE REVIEW

**Comment by downace** [comment]
This property is not documented. Looks like it's not supposed to be used by external code. Like private variable. Is it ok to add such properties to the typings?

**Comment by peterblazejewicz** [comment]
yeah, it's from pre-class-field support, so it's always there. I'd say it's private detail.
Btw, if accepted, it should have same types as constructor type ('RawDict'), shouldn't it?

**Comment by downace** [comment]
> it should have same types as constructor type ('RawDict'), shouldn't it?

Yes, type should be the same.

By the way, I think that the `Record<KeyType, ValueType>` definition suggested by @joshuaharry is more suitable for `RawDict` than just `object`, because only string keys are supposed to be used. But it looks like a breaking change.

**Comment by mastermatt** [comment]
The rule of thumb on non-documented/implementation-details of the library is to not include them in the typings. 
An argument can be made to add it if there is evidence that this property is widely used 'in the wild' even though it's not documented. But in this case, I personally don't think this PR should be merged in. 
Accessing the `dict` property bypasses the encapsulation this library is trying to create and should not be encouraged outside of unit tests.

**Review by sandersn — CHANGES_REQUESTED** [review]
Requesting changes so that the bot state matches what reviewers have been saying.

**Comment by joshuaharry** [comment]
Thanks for the feedback. Closing for now.

**Pull request closed without merging**
