### PR TITLE
pg.d.ts: add support to pg-types

### PR DESCRIPTION
**Pull request by aleung**
Add support to pg-types (https://github.com/brianc/node-pg-types)

``` js
pg.types.setTypeParser(20, (val) => Number(val));
```

### CODE REVIEW

**Comment by aleung** [comment]
@pspeter3 Could you review it?

**Comment by vvakame** [comment]
@aleung please resolve conflict.

**Comment by pspeter3** [comment]
Why is the parser not a generic function?

**Comment by aleung** [comment]
@pspeter3 Are you asking the argument type of `fn: (val: string) => any`? It will only be string.

> By default the PostgreSQL backend server returns everything as strings.
> ...
> So, you need to match a particluar OID to a function you'd like to use to take the raw text input and produce a valid JavaScript object as a result.

**Comment by pspeter3** [comment]
Given that the first parameter is a unique ID, I don't think you want to allow people to pass a function that returns any. It seems that the following would be more correct:
```ts
setTypeParser<T>(typeId: number, parser: (value: string) => T): void;
```

**Comment by aleung** [comment]
@pspeter3 You're right. I've updated it.

**Comment by pspeter3** [comment]
:+1:

**Comment by aleung** [comment]
@vvakame Could you merge it? Thanks

**Pull request merged**
