### PR TITLE
add microtaskMode to CreateContextOptions (node:vm)

### PR DESCRIPTION
**Pull request by caass**
See: https://nodejs.org/api/vm.html#vm_vm_createcontext_contextobject_options

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
    - _This is already supposedly on 14.14, but this changed was introduced in 14.6_

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
It's supported in v10 or newer, isn't it? Can you amend those versions? thx! (we expect DT to work, when user downgrades Node version)

**Comment by caass** [comment]
@peterblazejewicz unless i'm reading this incorrectly, looking at the [history tab](https://nodejs.org/api/vm.html#vm_vm_createcontext_contextobject_options), this is only supported as of 14.6.0

image

**Comment by peterblazejewicz** [comment]
@caass 🤕 really sorry for confusion, obviously!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@caass thx!

**Review by ExE-Boss — APPROVED** [review]

**Pull request merged**
