### PR TITLE
Update Jasmine-data_driven_tests/index.d.ts to add TS declarations for 'using' and 'xusing'

### PR DESCRIPTION
**Pull request by tylerprice1**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/gburghardt/jasmine-data_driven_tests>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by AnthonyMacKinnon — CHANGES_REQUESTED** [review]
The change makes sense. Let's just add a test for each to show usage.

**Comment by tylerprice1** [comment]
What kind of test do you mean?

Tyler
________________________________

**Comment by AnthonyMacKinnon** [comment]
@tylerprice1 If you look at the `jasmine-data_driven_tests-tests.ts` file, you'll see small simple tests that show usage and validate the TypeScript declarations (`index.d.ts`) changes. In this case, you could more or less copy a test from `all` and `xall` to show that `using` and `xusing` also work.

**Review by AnthonyMacKinnon — APPROVED** [review]

**Comment by tylerprice1** [comment]
What needs to happen for it to be mergeable? I noticed that it still has a "Revision needed" label.

**Comment by sandersn** [comment]
@tylerprice1 I think @typescript-bot forgot to remove it.

**Pull request merged**
