### PR TITLE
Fixing broken tests due to object-assign type definition change

### PR DESCRIPTION
**Pull request by NoHomey**
case 2. Improvement to existing type definition.

Not familiar with redux but merging and `dispatchProps` in `mergeProps` seems valid since `action` is required property of `DispatchProps`  and  there is no other source from which to come from.

### CODE REVIEW

**Comment by vvakame** [comment]
@tkqubo @seansfkelley could you review this PR?

**Comment by NoHomey** [comment]
Changes are not yet applied due to #10703 awaiting to be merged.

**Comment by seansfkelley** [comment]
LGTM. This shouldn't need to wait for #10703, right?

**Comment by NoHomey** [comment]
No, it can be merged ASAP. I've just pointed that changes are not yet applied.

**Comment by tkqubo** [comment]
LGTM 👍

**Pull request merged**
