### PR TITLE
[omggif] Remove Node dependency

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/deanm/omggif/blob/master/omggif.js#L24-L25
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This closes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59738

Thanks for the hint @Lemmingh!

### CODE REVIEW

**Comment by ffflorian** [comment]
@Lemmingh would you like to review this PR?

**Comment by Lemmingh** [comment]
Just realized that `ArrayLike` is `readonly`. So, it would be clearer to define:

```typescript
export interface GifBinary {
    readonly length: number;
    [index: number]: number;
}
```

---

A consideration:

I'd like to constrain the type of properties by generic class, presuming that changing the type of `buf` by `setOutputBuffer()` is a rare case and can be ignored.

With

```typescript
class GifWriter<TBuffer extends GifBinary = Uint8Array>
```

We can expect

```typescript
const writer = new GifWriter(new Uint8Array(2 ** 20), 2, 2);

// $ExpectType Uint8Array
writer.getOutputBuffer();
```

This is convenient for consumers.

---

I'm not familiar with the tests (`omggif-tests.ts`). Could you please briefly describe its logic?

**Comment by ffflorian** [comment]
Why not just use `Uint8Array | Array<number>?`

The test cases are just taken some examples taken from https://raw.githubusercontent.com/deanm/omggif/master/example_node.js. I should probably add the missing copyright there.

**Comment by Lemmingh** [comment]
> `Uint8Array | Array<number>`

👍 Make sense. People are very unlikely to use weird array-like objects. This should already cover all the real-world cases.

**Comment by ffflorian** [comment]
> People are very unlikely to use weird array-like objects.

Yeah, and even if they are, they can still extend these typings :)

**Comment by ffflorian** [comment]
I actually decided to use your suggested interface, makes more sense since the comment in omggif states

> Can be any type of buffer that supports [] (an Array, Uint8Array, Node Buffer, etc).

**Comment by Lemmingh** [comment]
> I actually decided to use your suggested interface

I guess we also need to explain its design in the DT package. What about:

```typescript
/**
 * @param buf - Uint8Array is a common choice.
 * Various array-like objects are also supported.
 */
```

In this way, consumers can just acquire a `Uint8Array`, `Buffer` or whatever from other APIs, and pass it to omggif, without checking `GifBinary` unless they really want to understand "array-like".

**Comment by ffflorian** [comment]
> I guess we also need to explain its design in the DT package

Good idea, I'll apply that.

**Comment by Lemmingh** [comment]
What about also adding the doc-comment to `GifReader`?

Others look good to me.

**Comment by ffflorian** [comment]
If you are fine with the PR, please approve it 🙂

**Review by Lemmingh — APPROVED** [review]
LGTM. Although I really think the doc-comment should be also replicated to `GifReader`.

Besides, a few thoughts about wording:

> Can be any type that supports the bracket accessor: Array, Uint8Array, Node Buffer, etc.

**Comment by ffflorian** [comment]
@Lemmingh I applied your suggestions 🙂

**Review by Lemmingh — APPROVED** [review]

**Comment by ffflorian** [comment]
Ready to merge

**Pull request merged**
