### PR TITLE
`state` property belongs to CodeMirror.Editor, not CodeMorrir.Doc

### PR DESCRIPTION
**Pull request by sixinli**

### CODE REVIEW

**Comment by vvakame** [comment]
*codemirror/codemirror-showhint.d.ts*

to authors(@jacqt @basarat). could you review this PR?
:+1: or :-1:?

check list

* [x] pass the Travic-CI test?

**Comment by basarat** [comment]
@sixinli It will work for both. That said, I would prefer it sent to `codemirror.d.ts` as its something that *all* plugins use :rose:

**Comment by basarat** [comment]
And remove it from `show-hint.d.ts`

**Comment by sixinli** [comment]
sounds good, will do :)

**Comment by basarat** [comment]
> sounds good, will do :)

* [ ] move to cm.d.ts `Editor`
* [ ] remove from showhint.d.ts

**Comment by sixinli** [comment]
I have made the changes, is it possible for you to take a look again?

**Comment by basarat** [comment]
thanks ! :rose:

**Pull request merged**
