### PR TITLE
Meteor: use modern namespace for local modules

### PR DESCRIPTION
**Pull request by edemaine**
Switch from old-style local `module` to `namespace`, as [recommended since TypeScript 1.5](https://www.typescriptlang.org/docs/handbook/namespaces.html).

(Originally part of #58014)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. No additional tests needed.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.typescriptlang.org/docs/handbook/namespaces.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. Not applicable.

### CODE REVIEW

**Review by radekmie — APPROVED** [review]
Just one minor comment about the PR description:
> Switch from old-style local `module` to `interface`, as recommended since TypeScript 1.5. [...]

It's `namespace`, not `interface`.

**Comment by edemaine** [comment]
> It's `namespace`, not `interface`.

Whoops, indeed! I've revised the commit message in particular to use the correct terminology.

Can you recommend a relevant test so that your approval suffices for merge? Otherwise, I guess we wait for DT approval.

**Review by radekmie — APPROVED** [review]
Well, there’s just no way to test it. You can add an unrelated test and it’ll be enough.

**Review by andrewbranch — APPROVED** [review]

**Comment by edemaine** [comment]
Ready to merge

Thanks @andrewbranch!

**Pull request merged**
