### PR TITLE
Update wicg-file-system-access types based on latest spec (2023/10)

### PR DESCRIPTION
**Pull request by Klohto**
Template:

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [WICG File System Access Spec](https://wicg.github.io/file-system-access)

--- 

Hello!

As DefinitelyTyped is used downstream, we hit an issue with outdated types. For example, `id` in `FilePickerOptions` is now supported for quite some time in Chromium.

I took the liberty to:
* sync the types with the latest spec,
* add latest features as per latest Chromium release, 
* update and format the tests a bit 
* as well as remove many duplicated interface definitions that are already included since Typescript 4.6,
* and added TODO for future deduplications (TS 5.1+)

Code has been fully tested.

If @RReverser agrees, I'd like to put myself on the list of Definition Owners (not included in the PR currently).
We have been consuming these types on heavy scale internally at Google and I'd like to keep an eye on them and keep them in sync as much as possible to make sure there aren't huge gaps between upstream/downstream.

### CODE REVIEW

**Comment by RReverser** [comment]
The changes seem pretty large and hard to review TBH, especially given that tests are also significantly changed.

Is it possible to keep this with original tests first (with whatever minimal adjustments are necessary), and then rewrite tests if still necessary in a separate PR?

**Comment by Klohto** [comment]
Definitely. I will modify it tomorrow 🙏

**Comment by Klohto** [comment]
Added a lite version of the previous commit.

* Add new definitions based on spec
* Add defaults
* Fix invalid tests (invalid extension and explicit type)

**Comment by Klohto** [comment]
Hello @RReverser! Please let me know if there is anything I can do to make it easier for a review 🙏

**Review by RReverser — APPROVED** [review]
Oh, sorry, missed the update. This looks great!

**Comment by Klohto** [comment]
Ready to merge

**Pull request merged**
