### PR TITLE
adding types for @pwabuilder/pwainstall web component.

### PR DESCRIPTION
**Pull request by lee-leonardo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

[Link](https://github.com/pwa-builder/pwa-install)

Hey the typescript level docs are a bit confusing to work through, so if you have any issues with what you see, please @ me! I'm wanting to learn and improve my documentation abilities. I'll respond ASAP to questions and etc.

### CODE REVIEW

**Comment by lee-leonardo** [comment]
@jgw96 @JudahGabriel

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## pwabuilder__pwainstall ([<kbd>unpkg</kbd>](https://unpkg.com/browse/pwabuilder__pwainstall@latest/))
was missing the following properties:
1. pwainstall
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5b243caf93c82a06e51ec7110e724187cad9066a
</p>

**Review by andrewbranch — CHANGES_REQUESTED** [review]
So, the weird thing about this is that @pwabuilder/pwainstall is _written in TypeScript_, and so could publish type declarations alongside the JS automatically with a very small infrastructure update. Instead of adding types here, I would start by opening an issue on their repo suggesting they publish types. Since they wrote in in TypeScript and have TypeScript usage examples in their README, I think they’d be open to it.

**Comment by lee-leonardo** [comment]
@andrewbranch I'm actually part of the PWABuilder team! We were trying to package it with PWAInstall, but ran into problems:
The module being imported purely via side effect, e.g. `import "@pwabuilder/pwainstall"`. Since we do not have anything exported, when defined within our repo, it prevents the module from being used properly, the import doesn't serve up the component, and only serves up the said interface. If you have some guidance and tips on writing declaration files for side effect imports let me/us know!

**Comment by andrewbranch** [comment]
Two separate thoughts:

1. However you decide to write the typings (including by hand or generated), it doesn’t make a difference to your users whether they go in DefinitelyTyped or in your repo. Since the team making the source library is the same as the team contributing to DefinitelyTyped, putting them here is only going to add process overhead. (I guess you could argue that by submitting this PR, you got feedback on the overall approach to typing this module from the TS team, but the ongoing value of that will probably diminish after we conclude this initial conversation.) So I’d still probably recommend that you put them in the source repo itself.

2. It is generally not a good idea to write module-like typings for a non-module-like package, which is what you have. When you import the source library, it adds certain capabilities to the global environment. Your typings should do the same. So instead of _exporting_ the types from your declaration file, you should just declare them globally, so that once someone does a side-effect import of `@pwabuilder/pwainstall`, they can access a `PWAInstallComponent` type without importing anything. Another thing it looks like you want to do is declare an overload for `document.createElement('pwa-install')` that returns your component type.

**Comment by lee-leonardo** [comment]
@andrewbranch thanks for the feedback and ideas, really appreciated. Those changes definitely make sense! I'll close out this PR as it is not needed anymore.

**Pull request closed without merging**
