### PR TITLE
[babel-types] Allow implicit boolean JSXAttribute values

### PR DESCRIPTION
**Pull request by timkendrick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/babel-types#jsxattribute
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by timkendrick** [comment]
Babel `JSXAttribute` nodes can contain `values` to indicate implicit boolean attributes (e.g. `<input disabled />`). This isn't currently reflected in the type definitions.

**Comment by bcherny** [comment]
Thanks for the contribution @timkendrick. Babel-Types [comes with packaged types already](https://github.com/babel/babel/blob/d383659ca6adec54b6054f77cdaa16da88e8a171/packages/babel-types/package.json#L10), so you should make you change there instead. Note that the types are codegen'd from the [AST definitions](https://github.com/babel/babel/tree/master/packages/babel-types/src/definitions.

We should really delete these typings from DT.

**Review by bcherny — CHANGES_REQUESTED** [review]
See feedback above.

**Comment by timkendrick** [comment]
Thanks for the response – however as far as I can tell, the `babel-types` package has only started including type definitions in v7 (currently still in beta). The current stable version of `babel-types` is still v6, which does not include type definitions – hence me submitting this PR.

For context, I'm working on a large app that relies heavily on babel AST manipulation, and I'm reluctant to upgrade to use v7 before it has been officially released. This means I'm still having to rely on DefinitelyTyped to get the babel types.

The way I see it, I guess it makes sense to keep fixing bugs in the DT types at least until babel v7 is released?

**Review by bcherny — APPROVED** [review]
Got it - SGTM!

**Comment by timkendrick** [comment]
Thanks!

**Pull request merged**
