### PR TITLE
[react-big-calendar] complete types for DateLocalizer

### LINKED ISSUE #53437: React big calendar export wrong
- [X] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sbusch @JakeChampion @TomasHubelbauer @altruisticsoftware @catruzz @tomtom5152

an issue related to react big calendar components export https://stackoverflow.com/questions/67719329/react-big-calendar-custom-view-w-typescript/67721360#67721360

> creating a custom view with the typed big calendar, each time I use a calendar component such as Timegrid or any other in my custom Week component as in the example, I get a standard error such as react_devtools_backend.js:2560 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. 

related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48528 too.

### PR DESCRIPTION
**Pull request by yaseenisolated**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
  Adds missing types as mentioned in issue 
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53437

The complete list of methods and types for DateLocalizer is listed here:
https://jquense.github.io/react-big-calendar/examples/?path=/docs/guides-localizers--page

- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
Not applicable. This is a fix of types for the existing version.

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53437

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-big-calendar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-big-calendar@latest/))
was missing the following properties:
1. components
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6c9da0bc2ce85006405bf91684e28abe03ec6131
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
Please links to documentation that helps verifying this change.

**Comment by yaseenisolated** [comment]
@eps1lon I have updated the main description to include a link to https://jquense.github.io/react-big-calendar/examples/?path=/docs/guides-localizers--page which has a list of all the DateLocalizer methods.

**Comment by yaseenisolated** [comment]
Ping on this one.

**Review by sheetalkamat — APPROVED** [review]

**Comment by yaseenisolated** [comment]
Ready to merge

**Pull request merged**
