### PR TITLE
fix(typings): mapbox-gl setPaintProperty options argument

### PR DESCRIPTION
**Pull request by pascaloliv**
Hi everyone,

The method `map.setPaintProperty()` was defining a wrong `klass?: string` argument.
I dig into source code of v1 and v2 (you can find exact link below) to fix the types.

Thanks in advance.
Olivier

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
You can find in [Mapbox-gl v1](https://github.com/mapbox/mapbox-gl-js/blob/release-v1.13.2/src/ui/map.js#L2032) and [Mapbox-gl v2](https://github.com/mapbox/mapbox-gl-js/blob/v2.9.2/src/ui/map.js#L2533).

### CODE REVIEW

**Comment by amxfonseca** [comment]
Thanks for the PR @pascaloliv.

The current definition seems indeed incorrect. I have used that method multiple times, but never had use for the last argument, so I never noticed it.

Do you mind to also update the `setLayoutProperty` method? Since they re a bit related, and it seems to be missing the last argument ([Mapbox API](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setlayoutproperty))

**Comment by pascaloliv** [comment]
> Thanks for the PR @pascaloliv.
> 
> The current definition seems indeed incorrect. I have used that method multiple times, but never had use for the last argument, so I never noticed it.
> 
> Do you mind to also update the `setLayoutProperty` method? Since they re a bit related, and it seems to be missing the last argument ([Mapbox API](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setlayoutproperty))

Thank you for your feedback.
Of course it seems the right moment to add the typings for `setLayoutProperty`.
I take the point and ping back on this PR when it's ready.

**Comment by pascaloliv** [comment]
@amxfonseca :

The types & tests for `setLayoutProperty` and `setLight` ([as far as it was using also the same options parameter](https://docs.mapbox.com/mapbox-gl-js/api/map/?size=n_10_n#map#setlight)) has been updated.

**Comment by amxfonseca** [comment]
Thanks a lot @pascaloliv 👍. I think we can definitely merge this 🎉

**Review by amxfonseca — APPROVED** [review]

**Comment by pascaloliv** [comment]
Ready to merge

**Pull request merged**
