### PR TITLE
@google-cloud/storage definitions

### PR DESCRIPTION
**Pull request by blove**
Definition files for the following JS modules in the
[at]google-cloud/storage API:

bucket.js
channel.js
file.js
storage.js

### CODE REVIEW

**Comment by blove** [comment]
This is related to issue #10705.

**Comment by blove** [comment]
It looks like the Travis CI build failed for something unrelated to this PR:

<code>Error:` Bad node in /home/travis/build/DefinitelyTyped/DefinitelyTyped/react-virtualized/index.d.ts: 'DESC: 'DESC'' is of kind LabeledStatement</code>

**Comment by andy-ms** [comment]
Sorry, there was a build failure affecting recent PRs. Fixed by #15125. Please rebase to the latest `master` to fix test failures.

**Comment by blove** [comment]
Arg. I did something wrong when rebasing from master. My apologies.

I have created a new PR for this: #15155

**Pull request closed without merging**
