### PR TITLE
Add immutable typings

### PR DESCRIPTION
**Pull request by tht13**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by tht13** [comment]
Hi @leebyron, 
I have ported your immutable typings to DT, would you like to have a look at it :smile: ?
It is mostly the same, but some of the instances where your typings return `this` in comments have been fixed.

I am adding this so that I can reference it in the Flux typings.

**Comment by vvakame** [comment]
please rename `immutable/immutable-test.ts` to `immutable/immutable-tests.ts`

**Comment by tht13** [comment]
done :smile:

**Comment by vvakame** [comment]
sorry for late. It merged!

**Comment by tht13** [comment]
Thanks :smile:

**Comment by GiedriusGrabauskas** [comment]
@vvakame, Could you explain it to me? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6623 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7890

**Comment by DovydasNavickas** [comment]
Ehm.... @GiedriusGrabauskas has a point. There were those PRs with extensive discussions about licensing and they were not merged. Then, @tht13 comes here with a different namespace (`__Immutable`  instead of `Immutable`) in the definitions and you gladly merge it.
Now we have two different versions of typings floating in the wild: this one and one in npm.

Now @GiedriusGrabauskas (and anyone else) tries using this d.ts and has errors with different versions and namespaces.

So, what motivated you to merge this one and not the other ones?

**Comment by tht13** [comment]
The only reason I placed this here is that some other modules in DT (namely Flux) were dependent on this. If it is causing issues please revert.

**Comment by DovydasNavickas** [comment]
@tht13, it'd be nice to hear why did you name the namespace `__Immutable` and not `Immutable` :) Maybe I don't see sth?

**Comment by DovydasNavickas** [comment]
I'm interested in reasoning, because original [`immutable.d.ts`](https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts) uses naming without leading underscores and here's where the conflict occurs.

**Comment by tht13** [comment]
The reason for the leading underscores I believe was for the import on [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9534/files#diff-300a4ef937c8dfe07574d2b25848823cR77), if you have a better suggestion for this I will happily make another PR to remove this regression.

**Comment by GiedriusGrabauskas** [comment]
I created pull request to fix global naming here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9569

You can use import:
```ts
declare module "test" {
 import __Immutable = require('immutable');
// or ES6
 import * as __Immutable from 'immutable';
}
```

**Pull request merged**
