### PR TITLE
Mongoose: expose Aggregate.count(..) method

### PR DESCRIPTION
**Pull request by YouriT**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongoosejs.com/docs/api.html#aggregate_Aggregate-count & code @5.0.15 references this method: https://github.com/Automattic/mongoose/blob/5.0.15/lib/aggregate.js#L379
- [ ] Increase the version number in the header if appropriate. => 5.0.15 has it hence not sure if the version should be changed. Please advise on how to proceed.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **N/A**

### CODE REVIEW

**Comment by jendrikw** [comment]
The count method exists since 5.0.7 (https://github.com/Automattic/mongoose/commit/4c986e5a18a47663923c7be30e392035620ec545), so you can leave the version as is because it's the minimum supported version by the typings (AFAIK).

**Review by jendrikw — APPROVED** [review]

**Comment by YouriT** [comment]
Thx for reviewing. Fine with not bumping the version but then when will it make into npm?

**Comment by jendrikw** [comment]
No, you don't have to change the version.

It should be on npm within a few hours after this PR is merged.

**Comment by YouriT** [comment]
Cool, didn't know it's possible to push to npm by replacing a version. Cheers.

**Pull request merged**
