### PR TITLE
Google Visualization Formatters

### PR DESCRIPTION
**Pull request by CodeZombieCH**
Added definitions for formatters based on the Google Visualization API Reference (https://developers.google.com/chart/interactive/docs/reference?hl=en#formatters)

### CODE REVIEW

**Comment by CodeZombieCH** [comment]
Any updates on this?

**Comment by danludwig** [comment]
Sorry, please have someone else review this PR. I haven't touched any
typescript in 2 years now.

**Comment by vvakame** [comment]
@CodeZombieCH please resolve conflict & ping me again.

**Comment by CodeZombieCH** [comment]
@vvakame resolved and ready to be merged

**Pull request merged**
