### PR TITLE
selenium-webdriver: Added options for Android

### PR DESCRIPTION
**Pull request by Kuniwak**
# Docs
- `chrome.Options`: http://selenium.googlecode.com/git/docs/api/javascript/module_selenium-webdriver_chrome_class_Options.html
- `chrome.ServiceBuilder`: http://selenium.googlecode.com/git/docs/api/javascript/module_selenium-webdriver_chrome_class_ServiceBuilder.html

### CODE REVIEW

**Comment by vvakame** [comment]
*selenium-webdriver/selenium-webdriver.d.ts*

to author(@BillArmstrong). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by BillArmstrong** [comment]
I took a quick look at it. Nothing jumps out as being obviously wrong, but I don't really have time to compare it against the webdriver code itself to see if it is correct.

**Comment by Kuniwak** [comment]
Thank you, @BillArmstrong !

@vvakame , how should I do in this situation?

**Comment by basarat** [comment]
:rose:

**Pull request merged**
