### PR TITLE
[@types/node-telegram-bot-api] Added caption_entities fields to interfaces. ChatId supports BigInt.

### PR DESCRIPTION
**Pull request by saymynameplsvip**
Added `caption_entities` fields (according to Telegram Bot Api documentation)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-telegram-bot-api/node-telegram-bot-api-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9f5ed66327fce1ce1c29915332694031cfb4d1f8
</p>

**Comment by asymptotee** [comment]
Also, changed `ChatId` type. ChatId is stored > 52 bits and < 64 bits.
I am using MariaDB to store ChatId and Prisma as an ORM. BigInt in MariaDB is stored in 64 bits (which is suitable for ChatId).
When I use Prisma to get the ChatId, it is returned as BigInt (128 bits). I suggest adding a BigInt type so developers don't waste time converting types.

**Comment by XieJiSS** [comment]
Actually we don't need `bigint` for `ChatId`, because telegram bot api doc states that no more than 52 significant bits would be used for chat ids ([ref](https://core.telegram.org/bots/api#chat)). This means that we can store it safely in a double-precision float type, which is what the `number` type stands for.

Other changes LGTM

**Comment by XieJiSS** [comment]
Seems like Prisma does not support custom data type for fields: https://github.com/prisma/prisma/issues/5039

In that case, I'd suggest the `bigint` change be made inside your own forked npm package if this modification is unavoidable for you, because serializing chat ids into a database as int64 and deserialize as bigint is a somewhat custom pattern. We'd better not to introduce a breaking change to all users - including `bigint` in the union [breaks existing codes](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgB4C5FggC2ARigE4CUiA3gFCKIQJpwA2KAdG3AOY6IA1IgDMAGkTZOUOADEY2FABNMAJkoTsiAPSJ1AbjoBfOnVCRYCZOiiqc+QqQqIAPohIxeMMFGr1GzGCsHNx8AsLiktJyCspqGpI6epSGRkA)

**Comment by yagop** [comment]
LGTM

**Comment by asymptotee** [comment]
> Seems like Prisma does not support custom data type for fields: [prisma/prisma#5039](https://github.com/prisma/prisma/issues/5039)
> 
> In that case, I'd suggest the `bigint` change be made inside your own forked npm package if this modification is unavoidable for you, because serializing chat ids into a database as int64 and deserialize as bigint is a somewhat custom pattern. We'd better not to introduce a breaking change to all users - including `bigint` in the union [breaks existing codes](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgB4C5FggC2ARigE4CUiA3gFCKIQJpwA2KAdG3AOY6IA1IgDMAGkTZOUOADEY2FABNMAJkoTsiAPSJ1AbjoBfOnVCRYCZOiiqc+QqQqIAPohIxeMMFGr1GzGCsHNx8AsLiktJyCspqGpI6epSGRkA)

I'm not sure how this will affect other users. In any case, users will have to do type narrowing (from "string" | "number" to "number"). Therefore, this change is safe. (Everyone uses type narrowing)

**Comment by XieJiSS** [comment]
````> > Seems like Prisma does not support custom data type for fields: [prisma/prisma#5039](https://github.com/prisma/prisma/issues/5039)
> > In that case, I'd suggest the `bigint` change be made inside your own forked npm package if this modification is unavoidable for you, because serializing chat ids into a database as int64 and deserialize as bigint is a somewhat custom pattern. We'd better not to introduce a breaking change to all users - including `bigint` in the union [breaks existing codes](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgB4C5FggC2ARigE4CUiA3gFCKIQJpwA2KAdG3AOY6IA1IgDMAGkTZOUOADEY2FABNMAJkoTsiAPSJ1AbjoBfOnVCRYCZOiiqc+QqQqIAPohIxeMMFGr1GzGCsHNx8AsLiktJyCspqGpI6epSGRkA)
> 
> I'm not sure how this will affect other users. In any case, users will have to do type narrowing (from "string" | "number" to "number"). Therefore, this change is safe. (Everyone uses type narrowing)

But they may use some sort of type narrowing like e.g.

```ts
if(typeof chatId === 'string') ...
else ...
```

In this case, the `else` branch will be affected.

**Comment by asymptotee** [comment]
> Another perspective is that this library describes the behaviors of telegram bot apis. When communicating with telegram bot apis, the user needs to provide either string or number for `chat_id`, and will always receive either of these types in response. However, changing `ChatId` to include `bigint` may cause developers to accidentally pass `bigint`s into APIs, which causes error during `JSON.stringify`.
> 
> Take the `copyMessages` API as example:
> 
> ```js
> copyMessages(chatId, fromChatId, messageIds, form = {}) {
>     form.chat_id = chatId;
>     form.from_chat_id = fromChatId;  // (1)
>     form.message_ids = stringify(messageIds);
>     return this._request('copyMessages', { form });
>   }
> 
> function stringify(data) {
>   if (typeof data === 'string') {
>     return data;
>   }
>   return JSON.stringify(data); // (2)
> }
> ```
> 
> Running `JSON.stringify({x: 1n})` in my browser yields `Uncaught TypeError: Do not know how to serialize a BigInt` so I think not all APIs of `node-telegram-bot-api` can accept `bigint` as its input.
> 
> Other changes in this PR looks good to me ;-)

Okay, you're right.

I also tried to stringify a JSON containing a bigint and got an error

**Comment by XieJiSS** [comment]
Great! Maybe you can push another commit to revoke the `bigint` modification and then we can merge this. Thanks!

**Comment by asymptotee** [comment]
> Great! Maybe you can push another commit to revoke the `bigint` modification and then we can merge this. Thanks!

Done

**Review by XieJiSS — APPROVED** [review]
LGTM

**Comment by asymptotee** [comment]
Ready to merge

**Pull request merged**
