### PR TITLE
[jwplayer] - add resize as string option

### PR DESCRIPTION
**Pull request by esetnik**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://docs.jwplayer.com/players/reference/resize_width_-_height_](https://docs.jwplayer.com/players/reference/resize_width_-_height_)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
This should involve owners input, if possible, as the PR changes nature of the DT module with 'export' addition (indirect impact IMO)

**Comment by peterblazejewicz** [comment]
give it a second run, ping me to review this if nothing happens, thx!

**Comment by esetnik** [comment]
> give it a second run, ping me to review this if nothing happens, thx!

@peterblazejewicz  Sorry, I didn't understand. What does "give it a second run" mean?

**Comment by peterblazejewicz** [comment]
> > give it a second run, ping me to review this if nothing happens, thx!
> 
> @peterblazejewicz Sorry, I didn't understand. What does "give it a second run" mean?

I meant: 'second release' (like with a movie run). Please check the documentation link, it's 404 now

**Comment by esetnik** [comment]
> > > give it a second run, ping me to review this if nothing happens, thx!
> > 
> > 
> > @peterblazejewicz Sorry, I didn't understand. What does "give it a second run" mean?
> 
> I meant: 'second release' (like with a movie run). Please check the documentation link, it's 404 now

@peterblazejewicz  I fixed the documentation link. Can we get this approved?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@esetnik thanks!

**Comment by esetnik** [comment]
Ready to merge

**Pull request merged**
