### PR TITLE
Fix debounce importing when targeting ECMAScript 2015 modules

### PR DESCRIPTION
**Pull request by Bnaya**
Follow up on #21112
The current declaration have the following problems: (That the tests don't catch...)

When importing like:
```ts
import debounce from "debounce";
```
You get 
`@types/debouce/index"' has no default export.`

When importing like:
```ts
import * as debounce from "debounce";
```
You get 
```
 resolves to a non-module entity and cannot be imported using this construct.
```

When importing like:
```ts
import debounce = require("debounce");
```
You don't get inline error in the IDE, but when running tsc you get:
```ts
 TS1202: Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

The suggested change fixed that issue. i don't know why, i just saw the same pattern in other declarations files

* The solution validated using yarn workspace

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
@denis-sokolov can you take a look? Looks like @typescript-bot didn't tag you when it should have.

**Comment by sandersn** [comment]
Actually, after taking a look myself, I see that this is not correct; according to the ES spec import * as x from 'x'; makes an x that is not callable. It's just a mistake of the Typescript compiler that it doesn't give an error here.

The problem is that only certain module loaders will allow `import * as x` to be callable; strictly Ecmascript-spec-compliant module loaders will not. In addition, `export = x` is not Ecmascript syntax; I think it makes sense to match non-Ecmascript imports with non-Ecmascript exports.

**Comment by Bnaya** [comment]
I dont understand why this is got closed
Its a fix for a standing issue

**Comment by sandersn** [comment]
It is not the correct fix because it will break users who do not use specific module loaders (things besides webpack, as I recall).

**Pull request closed without merging**
