### PR TITLE
[@types/quickapp] Add type definitions

### PR DESCRIPTION
**Pull request by tech-bro-in-vivo**

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
This looks like a scoped package.  Did you mean to add it as vivoquickapp__quickapp?

**Review by amcasey — CHANGES_REQUESTED** [review]
Same question: should this be types/vivoquickapp__quickapp?

**Comment by peterblazejewicz** [comment]
> Same question: should this be types/vivoquickapp__quickapp?

this is another reaosn why I asked for a test, so we can see how this is to be used

**Comment by Jerome77777** [comment]
> > Same question: should this be types/vivoquickapp__quickapp?
> 
> this is another reaosn why I asked for a test, so we can see how this is to be used

test has been added already, it names quickapp-tests.ts  @peterblazejewicz @amcasey

**Comment by tech-bro-in-vivo** [comment]
> Same question: should this be types/vivoquickapp__quickapp?

@amacleay @peterblazejewicz This is a scoped package. On our side, we think that adding it as `types/quickapp` is a better and more expected choice.

**Comment by elibarzilay** [comment]
After skimming the comments, it seems like it's questionable whether this should be on DT in the first place, and there's the concern of the name-grabbing -- and to top it off, it's a pretty big chunk of code.

**Comment by tech-bro-in-vivo** [comment]
> @tech-bro-in-vivo My concern is that if someone creates an unscoped package named `quickapp`, these types will become (incorrectly) associated with their package.

Well, referring to the advice you gave, we tried to publish the `quickapp` package on npm, but it was similar to the existing package name `quick-app` and it didn't work. The package name has been changed to `quickapp-interface` and is now available on npm ( https://www.npmjs.com/package/quickapp-interface ).

We wasted so much time trying to use `quickapp` as the package name that the pull requests have been closed and it looks like we have no right to reopen them, so we have to launch pull requests again: https://github.com/DefinitelyTyped/ DefinitelyTyped/pull/57032 .

For our eco-related developers, `@types/quickapp-interface` is very much needed, please merge and publish it so that they can all have fun with quickapp development, thank you very much.

**Pull request closed without merging**
