### PR TITLE
Update SensorOptions in w3c-generic-sensor

### PR DESCRIPTION
**Pull request by MNahad**
This PR adds a `referenceFrame` option along with the existing `SensorOptions` constructor arguments for all the motion sensors defined in `w3c-generic-sensor`.

As per the W3C documents below, the APIs for all the motion sensors in this type definition support the passing of an optional `referenceFrame` argument in the constructor.

- [`Accelerometer`, `LinearAccelerationSensor`, `GravitySensor`](https://www.w3.org/TR/accelerometer/#api)
- [`Gyroscope`](https://www.w3.org/TR/gyroscope/#api)
- [`Magnetometer`, `UncalibratedMagnetometer`](https://www.w3.org/TR/magnetometer/#api)
- [`AbsoluteOrientationSensor`, `RelativeOrientationSensor`](https://www.w3.org/TR/orientation-sensor/#api)

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [Accelerometer](https://www.w3.org/TR/accelerometer/) / [Gyroscope](https://www.w3.org/TR/gyroscope/) / [Magentometer](https://www.w3.org/TR/magnetometer/) / [OrientationSensor](https://www.w3.org/TR/orientation-sensor/) / [Motion Sensors Explainer](https://www.w3.org/TR/motion-sensors/)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Aren't all those options for frame a generic union type of `'device' | 'screen'`, are they?

**Comment by MNahad** [comment]
@peterblazejewicz yes, that is correct. Looking at the documents linked in the PR, the two options for all the Motion Sensors `referenceFrame` option are `device` and `screen`, with the default being `device`. I wanted it to be extensible, which is why I left it as `string`, but thinking about it now, if the documents do change in the future then this type definition can be updated at that point to reflect it.

**Comment by MNahad** [comment]
@peterblazejewicz I have updated this PR. Please re-review at your earliest convenience. Thanks.

**Review by peterblazejewicz — APPROVED** [review]
LGMT!

**Comment by MNahad** [comment]
Thank you @peterblazejewicz

**Comment by MNahad** [comment]
Ready to merge

**Pull request merged**
