### PR TITLE
Adding JSONStream Definitions

### PR DESCRIPTION
**Pull request by EricByers**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by EricByers** [comment]
This is somewhat of an odd one.

The original package was published to `jsonstream` (https://www.npmjs.com/package/jsonstream), but then the name was changed to `JSONStream` (https://www.npmjs.com/package/JSONStream) and published there.

On a case insensitive file system, this will load the newer JSONStream module, using the old types.  However on a case sensitive one, these do not match up, causing it to fail.  If the require/import is changed to lowercase, the type definition will pass, but any tests/code will fail on a case sensitive system.

I don't see any other types that have colliding values on sensitive/insensitive, so not sure if that will be an issue either.

**Comment by EricByers** [comment]
The build on TravisCI also fails because it's not lowercase, but packages are published on npm that include uppercase, are those just not allowed to be typed?

**Comment by andy-ms** [comment]
I don't think NPM will allow publishing of packages with capital letters any more. So publishing `@types/JSONStream` would be impossible now.
Makes me wonder why the one with lowercase letters is the deprecated one.

**Comment by andy-ms** [comment]
Like I said, we're simply unable to publish a package with capital letters in its name. Hope you can convince them to bundle typings.

**Pull request closed without merging**
