### PR TITLE
added autohide and end date properties to date picker options

### PR DESCRIPTION
**Pull request by naveenkumarreddy**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
Closing in favor of #13318, OK?

**Comment by naveenkumarreddy** [comment]
Okay, when will you merge the changes to types-2.0 and then master?

**Comment by andy-ms** [comment]
First, we will wait for the original authors to review. If they haven't responded in 3 days, ping me and I'll review. A while after it's in we will do a routine merge from `types-2.0` to `master`.

**Comment by naveenkumarreddy** [comment]
Thank you andy, I am closing #13318 with reference #13330  and it was merged to types-2.0. I am waiting merging to master

**Pull request closed without merging**
