### PR TITLE
preserver?

### PR DESCRIPTION
**Pull request by electricessence**
Am I mistaken about this?

### CODE REVIEW

**Comment by ChristopherHaws** [comment]
This looks good to me. I must have made a spelling mistake. Per https://github.com/terinjokes/gulp-uglify the correct spelling is `preserveComments`.

:+1:

**Comment by horiuchi** [comment]
@electricessence Thank you for your contribution 👍 
Please rebase master for fixing conflicts this pull request.

**Comment by mhegazy** [comment]
@electricessence can you update the PR?

**Comment by electricessence** [comment]
Oh sorry I'm not sure what to do there. :(

**Comment by mhegazy** [comment]
There are merge conflicts, and the PR can not be merged automatically. So either rebase against master, or create a new PR.

**Pull request closed without merging**
