### PR TITLE
[gapi.client.classroom] automatic update

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
  - [x] Test the change in your own code. (Compile and run.)
  - [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  - [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
  - [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
  - [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

  Select one of these and delete the others:

  If changing an existing definition:
  - [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Maxim-Mazurok/google-api-typings-generator#google-api-typings-generator
  - [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
  - [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
  - [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

  ----

  🤖 This pull request was automatically created by [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) which generates types from [Google API Discovery Service](https://developers.google.com/discovery). Types were linted and tested before submission.

  If there is an issue with this pull request, consider [submitting a new issue](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new).

  Note you can also [use these types](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279) from our [`types` branch](https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/types) which is updated hourly.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getRequestIdentifier
1. MutationTypes
1. RangeOperations
1. ConnectionResolver_UNSTABLE

<details>
<summary>as well as these 11 other properties...</summary>
<p>VIEWER_ID, VIEWER_TYPE, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isPromise, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier, getFragmentSpecIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 17144ac076619d0a0004ec9beba8fd0a7721526d
</p>

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## hls.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hls.js@latest/))
was missing the following properties:
1. prefixed
1. EventEmitter
1. Hls
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cd1fb801ffd9b1b8d42661659252cc00793c29ea
</p>

**Review by peterblazejewicz — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by orta** [comment]
Heh, wow - OK, looks good.

**Comment by Maxim-Mazurok** [comment]
> Heh, wow - OK, looks good.

Can you explain your reaction, please? :)

**Comment by orta** [comment]
just a lot of bot action in this PR

 --
[·/ ]       Orta Therox

w/ Microsoft on TypeScript
CocoaPods <http://cocoapods.org/> / Danger <https://danger.systems>
@orta / orta.github.com

**Pull request merged**
