### PR TITLE
Improve module.filter() by allowing `$stateful` to be defined.

### PR DESCRIPTION
**Pull request by oBusk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.angularjs.org/guide/filter#stateful-filters

### CODE REVIEW

**Comment by thorn0** [comment]
Does it have to be that complicated? IMHO something like this would suffice:
```ts
interface IFilterFunction extends Function {
  $stateful?: boolean;
}
```

**Comment by oBusk** [comment]
@thorn0 You're obviously right! I don't know what I was thinking. Pushed the change.

**Comment by thorn0** [comment]
Please remove the formatting-only changes from the PR. I'd happily accept them as a separate PR, especially if you used [Prettier](https://prettier.io/).

**Comment by oBusk** [comment]
@thorn0 Wooops! Sorry! The `shift`+`alt`+`F` habit is deeply rooted. I repushed the change without any formatting changes.

**Review by thorn0 — APPROVED** [review]

**Pull request merged**
