### PR TITLE
feat: upgrade Kendo UI definitions to 2017.1.118

### PR DESCRIPTION
**Pull request by tsvetomir**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.telerik.com/kendo-ui/api/javascript/class
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@tsvetomir and @zskovacs can you please review this change.

**Comment by bowdenk7** [comment]
No response from other authors for over 5 days. Merging.

**Comment by bowdenk7** [comment]
@tsvetomir looks like there are some merge conflicts. Can you refresh the PR and address the conflict?

Thanks for the contribution!

**Comment by zhengbli** [comment]
Pinging @tsvetomir again

**Comment by tsvetomir** [comment]
Should be good now, thanks!

**Comment by zhengbli** [comment]
Thank you but the tests are failing. Can you please fix the failing Travis CI tests and update the PR?

**Pull request merged**
