### PR TITLE
Added locals to $evalAsync

### PR DESCRIPTION
**Pull request by cozmy**
See https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$evalAsync

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
**here https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$evalAsync**
- [x] Increase the version number in the header if appropriate.
**unsuitable**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
**unsuitable**

### CODE REVIEW

**Review by iocalebs — COMMENTED** [review]
These three declarations should be merged into one. According to the TypeScript Handbook, unions should be used instead of overloads when the type differs in only one argument position. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-union-types

I know this is not directly related to your change, but I think it's a good time to address it.

**Comment by thorn0** [comment]
It's never a good idea to use the type `Object` in type declarations. Please be more specific.

**Comment by thorn0** [comment]
Also the type of the `expression` function should be `=> void`, not `=> any`. Please change it.

**Comment by cozmy** [comment]
I simply added what's missing while following the general style of the typings file. To put it shortly, I've copied the locals from $eval as their signature is almost identical. 
All your proposed changes are good and should definitely be taken into consideration, but they don't belong in this pull request.

**Comment by calebstdenis** [comment]
Well in any case you'll have to fix the build first. :P

**Comment by cozmy** [comment]
@calebstdenis To be honest, I don't understand the errors. They seem unrelated to this pull request.

**Comment by calebstdenis** [comment]
@cozmy Odd. I would suggest closing and reopening the PR to trigger a rebuild.

**Comment by cozmy** [comment]
@calebstdenis Weird. The errors reported by Travis don't seem related to my changes.

**Comment by calebstdenis** [comment]
@cozmy Definitely not related to your changes, but I'm hesitant to approve as long as the build's failing. Sit tight for now.

**Comment by thorn0** [comment]
> I've copied the locals from $eval as their signature is almost identical.

They're not totally identical though. `$eval` returns the result of `expression` whereas `$evalAsync` doesn't do so, that's why the types of `expression` should be different. If you're fixing typings for some API , fix them properly. That's what I think. Also if you add a commit, Travis will rerun the tests.

**Comment by mhegazy** [comment]
@cozmy please address the CI test failures. @thorn0 mind taking a look and giving a 👍 or 👎 ?

**Comment by thorn0** [comment]
@mhegazy CI failures don't look related to this PR. Something else is broken there. Or probably just a rebase is needed.

**Comment by andy-ms** [comment]
Verified that test failures are unrelated and are gone now. Thanks!

**Pull request merged**
