### PR TITLE
Add support for Promises in redux-api-middleware

### PR DESCRIPTION
**Pull request by AdamCLarsen**
fix

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/agraboso/redux-api-middleware/pull/235
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@AdamCLarsen what is the reasoning for this change?

In source code `await` is used for `payload` or `meta` in case there is a promise.
But you can type that with existing exported types.

What is your use case, and what want to achieve?

**Comment by AdamCLarsen** [comment]
You are correct, technically I could accomplish that by something like;

```
const myApiAction = createAction<ApplicationState, Promise<MyPayload>, Promise<MyMeta>>({
    method: 'GET',
    endpoint: 'api/data',
    types: [
        {
            type: USER_REQUEST,
            meta: async (action, state)=> {return{key:1} }
        },
        USER_SUCCESS,
        USER_FAILURE,
    ],
});
```

But that just didn't feel as clean and intuitive, there is nothing in the type definition that tells me for certain that 'createAction' is going to await my Promise, IMHO the entire point of strong typing is to communicate implementation details like that with-out having to go check documentation.

However, what sent me down this route was not the 'meta' or 'payload' methods, but the header property, my code for returning my Bearer Token returns a promise, because it can go back to the IDP if the token has expired.  Updating the type definition is the only way I could return a promise to the 'headers' property.

```
const myApiAction = createAction<ApplicationState, Promise<MyPayload>, Promise<MyMeta>>({
    method: 'GET',
    endpoint: 'api/data',
    types: [USER_REQUEST, USER_SUCCESS, USER_FAILURE],
    headers: async (appState) => {
        const tokenResponse = await authProvider.getIdToken();
        return {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${tokenResponse.idToken.rawIdToken}`,
        };
    },
});
```

So once I was in there, I opted to go all the way and add it to the RSAA______TypeDescriptor types too.  If you feel it's best to not update the RSAA______TypeDescriptor types, I can live with that, but I don't see any other options then updating the TypeOrResolver for the other properties like 'header', 'body', or 'bailout'.

**Comment by iamandrewluca** [comment]
```
payload?: ((action: RSAAAction, state: State) => Payload) | ((action: RSAAAction, state: State) => Promise<Payload>) | Payload;
```
can abeove be simplified to bellow?
```
payload?: ((action: RSAAAction, state: State) => Payload | Promise<Payload>) | Payload;
```

**Comment by AdamCLarsen** [comment]
That's an option, my only concern is that it may limit some use cases, if there is value in having access to `action`, and `state` when doing a non-async function, I would think the same use cases still exist with a async function.

And with the current code you can still do;
```
meta: async (action, state)=> {return{key:1} }
```
or
```
meta: async ()=> {return{key:1} }
```

**Comment by iamandrewluca** [comment]
> That's an option, my only concern is that it may limit some use cases, if there is value in having access to action, and state when doing a non-async function, I would think the same use cases still exist with a async function.

I don't quite understand. 

e.g. For TypeScript this two functions types are identical

```ts
async function test1() {
  return ''
}

function test2(): Promise<string> {
  return Promise.resolve('')
}
```

**Comment by AdamCLarsen** [comment]
I miss understood your comment, I agree that is a cleaner approach.  The change has been made.

**Review by unrevised6419 — APPROVED** [review]
LGTM

**Comment by AdamCLarsen** [comment]
Ready to merge

**Pull request merged**
