### PR TITLE
Fix theme-ui color mode type

### LINKED ISSUE #37838: [@types/theme-ui] ColorModes seems to need an additional level of nesting
Raising from here:
https://github.com/system-ui/theme-ui/issues/121#issuecomment-523594570

cc @ifiokjr @sbardian 

In short the [ColorModes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0de3688b30e6e49f620930e14f3e7f7223fce204/types/theme-ui/index.d.ts#L42-L53) interface appears to really be more of a `ColorMode` (singular) so should be nested within a `[k: string]: { /* ColorMode */ }` bit.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by sbardian**
Please fill in this template.

closes #37838

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://theme-ui.com/theme-spec#color-modes>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by wKovacs64 — APPROVED** [review]

**Review by erikdstock — APPROVED** [review]
Thanks @sbardian! I was going to ask that you keep the indentation at 2 spaces but then realized it's actually part of the [default config](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.editorconfig). Looks good from here!

**Review by ifiokjr — APPROVED** [review]
Looks good 👍

**Comment by sbardian** [comment]
@erikdstock yup was going to revert it to 2 then noticed the same.

**Comment by kristojorg** [comment]
I am getting the following error when using these types:

```
node_modules/@types/theme-ui/index.d.ts:49:9 - error TS2411: Property 'text' of type 'string' is not assignable to string index type 'Partial<Pick<ObjectOrArray<string>, number | "toString" | "concat" | "indexOf" | "lastIndexOf" | "slice" | "length" | "includes" | "toLocaleString" | "push" | "reverse" | "map" | "filter" | ... 17 more ... | "values">>'.
```

It looks like the errors are popping up on `text` and `background` in this block:
```
export interface ColorModes {
    [k: string]: {
        /**
         * This is required for a color mode.
         */
        text: string;

        /**
         * This is required for the color mode.
         */
        background: string;
        [k: string]: Partial<Omit<StyledSystemTheme['colors'], 'modes'>>;
    };
}
```

I haven't begun to use color modes in my app, am just getting started with theme-ui. Any suggestions here?

**Comment by sbardian** [comment]
@kristojorg can you post/share your theme?

**Comment by kristojorg** [comment]
@sbardian I'm so far just using the basic theme suggested on the website:

```
export default {
  fonts: {
    body: 'system-ui, sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
  },
}
```

**Comment by sbardian** [comment]
Doesn't appear you are typing the theme?  Should import and type the theme as type `Theme`?  From what I can see it doesn't look like the error has anything to do with the `ColorModes` interface though?

**Comment by kristojorg** [comment]
@sbardian I was casting the theme on import, but even when I switch to doing this:
```
import * as ThemeUi from 'theme-ui'

const Theme: ThemeUi.Theme = {
  fonts: {
    body: 'system-ui, sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
  },
}

export default Theme
```

I still am seeing the errors on `ColorModes` as described above. The error occurs in `@types/theme-ui` on that block in the declaration file. If I comment out the `text` and `background` lines in `ColorModes`, the error is gone. Not sure what I'm missing here

**Comment by kristojorg** [comment]
I am also seeing the error 
```
Property 'theme' is missing in type '{ children: Element[]; }' but required in type '{ theme: object; }'.
```

on children of my `ThemeProvider`, so maybe you're right that I'm incorrectly typing the theme? This is where I have typed my custom `styled` instance:

```
import styled, { CreateStyled } from '@emotion/styled'
import * as ThemeUI from 'theme-ui'


export default styled as CreateStyled<ThemeUI.Theme>
```

Sorry to spam this PR if this isn't related

**Comment by sbardian** [comment]
Just using your theme in one of my projects works fine.  Do you have this code in a repo I could check out, or codesandbox?

**Comment by kristojorg** [comment]
It is in the `beta` branch of this repo 

https://github.com/NYPL-Simplified/circulation-patron-web

I am brand new to this repo and just getting theme-ui installed so far. I solved the `property 'theme' is missing in type` error by changing my upstream emotion type defs, but am still having to comment out the `text` and `background` properties in this `d.ts` file in order to avoid the following error:
```
node_modules/@types/theme-ui/index.d.ts:49:9 - error TS2411: Property 'text' of type 'string' is not assignable to string index type 'Partial<Pick<ObjectOrArray<string>, number | "toString" | "concat" | "indexOf" | "lastIndexOf" | "slice" | "length" | "includes" | "toLocaleString" | "push" | "reverse" | "map" | "filter" | ... 17 more ... | "values">>'.
```

**Comment by sbardian** [comment]
@kristojorg when are you seeing the error?  I'm currently not seeing it?

**Comment by wKovacs64** [comment]
@kristojorg #40109 should resolve your issue, I think.

**Comment by kristojorg** [comment]
It did @wKovacs64, thank you!

**Pull request merged**
