### PR TITLE
ui-grid sortDirectionCycle typing be Array<string>

### PR DESCRIPTION
**Pull request by tomaisoc**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef#sortdirectioncycle>>
- [ ] Increase the version number in the header if appropriate.

The sortDirectionCycle parameter should is an array of strings, so update the typing to use Array<string> instead of Array<IUiGridConstants>

### CODE REVIEW

**Review by joeskeen — CHANGES_REQUESTED** [review]
I agree that array of IUIGridConstants isn't right for this option; however, I disagree with this change.  In the documentation it only mentions three valid values that can be passed into this array: `ASC`, `DESC`, and `null`.  IMHO widening to accept every `string` value would be a mistake.  I think it would be better to define an ISortDirection type as a union type of the valid values then change this line to be an array of that type.
I would start by looking at https://github.com/angular-ui/ui-grid/blob/28d582abcdc216fcc8de45fff574f39f9b445bec/src/js/core/constants.js#L83, suggesting that the uiGridConstants.ASC shouldn't be typed as a `string`, but rather should be typed as `'asc'`, etc.  Using the string literal types allows for better type helps and tooling.

**Comment by btesser** [comment]
@tomaisoc I agree with @joeskeen

**Comment by btesser** [comment]
I completely agree @joeskeen

**Comment by andy-ms** [comment]
@tomaisoc or @joeskeen or @btesser, please make a new PR to fix this.
The interface `IUiGridConstants` is likely wrong. An interface declares that there would be many *instances* each of which had their *own* `LOG_DEBUG_MESSAGES`, etc. If you simply want to declare a bunch of constants, use multiple `export const` statements.

**Pull request closed without merging**
