### PR TITLE
new company internal project types, not on npm

### PR DESCRIPTION
**Pull request by PaperBackPear3**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/help-center/index.d.ts
1. types/help-center/package.json
1. types/help-center/CustomerlySettings/index.d.ts
1. types/help-center/help-center-tests.ts
1. types/help-center/Help-center/index.d.ts

<details>
<summary>as well as these 1 other files...</summary>
<p>types/help-center/Globals/index.d.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dbd01a6e2e84efa4c2f12cc6992e4eca456f621d
</p>

**Comment by peterblazejewicz** [comment]
question, is this for https://www.customerly.io? (global script ships with properties from a type from PR)
Please consider changing the name, I think it's too generic, though technically not taken on NPM. So it can impact pool of name on NPM, while here DT are just to help with usage of published content first (with automatic types acquisition TS feature): :https://www.typescriptlang.org/play#example/automatic-type-acquisition

**Comment by PaperBackPear3** [comment]
Hi, it's for an internal tool that uses customerly yes, i'll change the name by adding the project prefix to it. thank you :)

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/help-center/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0e46a32e034967a7ed9c25c13f99f5e50dea4a41
</p>

**Comment by jakebailey** [comment]
Why are you submitting types for an internal project on DT? This is not the right place for that sort of thing.

**Review by jakebailey — CHANGES_REQUESTED** [review]
Marking as needing review; I don't see a reason to have a private package on DT. If you are able to internally distribute types for this, you can internally distribute your types too.

**Pull request closed without merging**
