### PR TITLE
Fixes issues with callback parameters and adds missing promisified

### PR DESCRIPTION
**Pull request by Loghorn**

### CODE REVIEW

**Comment by Flarna** [comment]
Changes LGTM. Would be nice to add some tests as there are such a lot overloads and it's easy to overlook a detail.

**Comment by Loghorn** [comment]
I've added tests and fixed other failing modules, but the Travis CI build failed for timeout (changing node runs all the tests and it takes a long time...). Is there a way to restart the build without making a new commit?

**Comment by Flarna** [comment]
Maybe closing and reopening the issue does the trick?

**Comment by Loghorn** [comment]
Thanks 😄

**Comment by Flarna** [comment]
by the way, there seems to be another PR to cover the issue in optics-agent: 19938

**Comment by Loghorn** [comment]
I've updated optics-agent to match the PR.

**Pull request merged**
