### PR TITLE
fix: update Jasmine.Env properties

### PR DESCRIPTION
**Pull request by UziTech**
I updated `Env` to include all properties. There are quite a few other places I would like to update but I thought I would submit this PR and get some feedback first.

Should I submit multiple PRs updating different parts or would it be better to update it all in one PR?

The tests are based off of Jasmine v2 so they will fail where parts of `Env` have been removed. Should I just remove these tests and create new ones for the added props?

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/jasmine/jasmine/blob/main/src/core/Env.js>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by UziTech** [comment]
I don't think the ci failure is from this change it passes on my machine

**Comment by chivesrs** [comment]
What do you mean by Jasmine v2? The tests should be based off Jasmine 3.6, so please fix that.

Can you do the reformat stuff in 1 commit? And then a second that contains real changes?

**Comment by chivesrs** [comment]
If a property existed in Jasmine v2 but was removed in v3, then the corresponding typing should be removed and the tests updated to match.

**Comment by chivesrs** [comment]
Let me know if you have further questions, but as I see it, the PR is in your queue to fix up my above comments.

**Comment by UziTech** [comment]
> What do you mean by Jasmine v2? 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/22d7e6a446608df5f41e3b5b323ebdb9b8a7e013/types/jasmine/jasmine-tests.ts#L1

> Can you do the reformat stuff in 1 commit? And then a second that contains real changes?

I'm not sure what you mean by reformat stuff. There are a lot of changes needed (probably half of it) so I was wondering if I should do it in small chunks so it is easier to review or just all at once?

**Comment by chivesrs** [comment]
Then the tests doc needs to be changed, as the typings clearly state `// Type definitions for Jasmine 3.6`

Regarding reformatting, I mean stuff like this https://i.imgur.com/55EvEhL.png. There's no real change here besides spacing. I want all the spacing related stuff in 1 commit, and the actual material changes in the second commit. It makes it much easier to review.

**Comment by chivesrs** [comment]
Alternatively, whatever editor you use, turn off the reformat on save plugin you have, and redo the edits you wanted to make.

**Comment by chivesrs** [comment]
Apparently Prettier is integrated into DT, so your reformat commit should use prettier. See docs https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes, second bullet point.

**Comment by UziTech** [comment]
> turn off the reformat on save plugin

I don't have a reformat on save plugin. All of those style changes were done by running `npm run prettier`

**Comment by chivesrs** [comment]
OK so here's how I'm reviewing this PR right

I go to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51825/commits, and I see 2 commits. I click into each one of them.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51825/commits/5a90d03541c7b56b3122aa4b0556f7b130ed5763 is pretty easy to review. I can tell easily what the changes are.

But then https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51825/commits/5fda86f01cf3fadf6a6cb0186affb49b2955bf20, there are so many changes in there that aren't actually about fixing tests. They're all formatting changes. Those need to be pulled into a separate commit.

**Comment by UziTech** [comment]
> But then 5fda86f, there are so many changes in there that aren't actually about fixing tests. They're all formatting changes. Those need to be pulled into a separate commit.

Ya that was from running `npm run prettier` and commenting out the failing tests.

So should I just run prettier and submit that as one PR then do the other changes?

**Comment by chivesrs** [comment]
Not as a separate PR. A separate commit in this PR. That way I will see 3 commits. One for the typings, one for the tests, and then one for formatting changes. The order of them doesn't matter.

**Comment by chivesrs** [comment]
In your particular scenario, this seems pretty easy to do. Roll back the latest commit (the one with the commented out test and the formatting changes), that way the diff between DT head and you is just the change to typings. Then commit the commented out test (actually, you should just delete those lines of code). Then run prettier and commit that.

https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits You're on scenario A of the top answer.

**Comment by chivesrs** [comment]
You'll have to force push afterwards.

**Comment by UziTech** [comment]
How do I deal with prettier making the tests fail? When I run `npm run prettier -- -- --write types/jasmine/*.ts` it formats according to the prettier config but then I run `npm test jasmine` and I get `ERROR: 1468:68  space-before-function-paren  Spaces before function parens are disallowed`.

If I run the tests before running prettier I don't get any errors.

**Comment by UziTech** [comment]
Figured it out. I can just turn off the rule in tslint.json

**Comment by chivesrs** [comment]
I believe you can disable prettier for an offending line (one of the links I linked should explain how). You shouldn't disable a rule in tslint.json.

**Comment by UziTech** [comment]
There are about 100 of these lines. I feel like it would be better to disable the rule if we are never going to follow it.

**Comment by UziTech** [comment]
Or can we just disable the rule in prettier without needing `// prettier-ignore` comments everywhere?

**Comment by UziTech** [comment]
I just changed the functions to arrow functions which don't have an issue with prettier.

**Comment by chivesrs** [comment]
I'm assuming you're still working on this? As the only commit I see is the format CL. If so, you should change the PR to draft mode as it's not in a state for me to review it just yet.

**Comment by UziTech** [comment]
@chivesrs I'm not sure why the tests are failing. They are all passing on my machine. Would you have time to review the current changes before I add new tests?

**Comment by UziTech** [comment]
I think I found out why the tests are failing. Do I need to update [jasminewd2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasminewd2/index.d.ts#L61) and other packages that reference jasmine as well?

**Comment by chivesrs** [comment]
Before I comment on the tests part, it seems your PR does more than just touching jasmine.Env. It's become really big to review. This is a good time to split it up so that this PR is purely for jasmine.Env and the other changes, like removing values on the right hand side of expect statements (eg toBeResolved(string) -> toBeResolved()) to another PR.

Re tests, the first error I see is:

```
1> jasmine-fixture failing:
1> Error: Errors in typescript@4.3 for external dependencies:
Error: 1> ../jasmine/index.d.ts(709,15): error TS2430: Interface 'ArrayLikeMatchers<T>' incorrectly extends interface 'Matchers<ArrayLike<T>>'.
1>   The types returned by 'toBe(...)' are incompatible between these types.
1>     Type 'void' is not assignable to type 'boolean'.
1> 
1>     at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:206:19
1>     at Generator.next (<anonymous>)
1>     at fulfilled (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

And so this means the typings file changed such that clients are broken. In this particular case it seems the typings file is inconsistent with itself.

Why don't you just work on jasmine.Env only in this PR, and then the other stuff come back to later? Given the amount of users who use Jasmine in their projects, the PR is really risky if it changes thousands of lines of typings.

**Comment by UziTech** [comment]
Ok I'll do each part separately. That is what I asked at the beginning of this PR, if I should split it up.

That error says that jasmine-fixture is inconsistent because it references jasmine. Do I need to update all of the type files that reference jasmine?

**Comment by chivesrs** [comment]
If your change makes it so that you change the jasmine typings in a way that affects users, then yes. Other jasmine auxiliary typings are considered users as well.

**Comment by chivesrs** [comment]
That particular error though says that jasmine itself is inconsistent with itself. As in, the error is on `../jasmine/index.d.ts(709,15)`.

If the error was inside jasmine-fixture, then the line would say `jasmine-fixture/index.d.ts` or something like that.

**Comment by UziTech** [comment]
> If the error was inside jasmine-fixture, then the line would say jasmine-fixture/index.d.ts or something like that.

Not true. You can see by the line `1> jasmine-fixture failing:` all of the error are coming from other packages. I'm pretty sure it is refering to `jasmine/index.d.ts` because the referenced types are evaluated last so the error is correct `ArrayLikeMatchers<T>` in jasmine are incompatible with `Matchers<ArrayLike<T>>` in jasmine-fixture.

[line 72](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51825/checks#step:5:72) `1> jasmine OK` shows that all of the tests in jasmine are passing when they are not overridden by other types.

The biggest problem with updating other types is that some of them are based on Jasmine v2 so they won't be compatible with new types in Jasmine v3. Should I copy the current types to those packages so they don't change? or how should I fix those packages?

**Comment by chivesrs** [comment]
I believe https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package goes into this.

Jasmine used to have a v2/ directory that was recently deleted. If you need to resurrect it, look at the PR history for the jasmine directory and you can revert that PR.

**Comment by chivesrs** [comment]
That being said, if you're only changing jasmine.Env, why are array matcher typings being edited?

**Comment by UziTech** [comment]
> if you're only changing jasmine.Env, why are array matcher typings being edited?

I'm not only editing `jasmine.Env`. That was where I was going to start but there are a lot of types that are wrong for jasmine v3.

**Comment by chivesrs** [comment]
Yeah. Start with jasmine.Env only for this PR and then come back to the rest. It was fine to do the format changes and jasmine.Env in one PR, but if your goal is to fix everything to be accurate for v3, then it's way too much for one PR.

I was a little confused when you were asking about splitting up the PR because I was under the assumption that you were only modifying jasmine.Env. As this is no longer the case, then yes you should definitely split things up into multiple PRs.

I'd start by just one for formatting, then one for jasmine.Env, so we can work through all the CI breakages and all the broken dependencies there. Once those two are submitted then we should come back to all the other changes. Otherwise this is just way too much work for both you the author and us the reviewers.

**Comment by UziTech** [comment]
#51997 is the start of the separated PRs

**Pull request closed without merging**
