### PR TITLE
aws-lambda: Add types for 'Step Functions Execution Status Change'

### PR DESCRIPTION
**Pull request by photz**
Source: https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by jakebailey — DISMISSED** [review]

**Review by jamesorlakin — COMMENTED** [review]
Nice one @photz! This otherwise looks good to me, but I'd like to a see a `Handler` type as well to be consistent with the other definitions in the package.

(e.g. https://github.com/photz/DefinitelyTyped/blob/53d582d7f42d1d004be4c07183749300f138f24b/types/aws-lambda/trigger/sqs.d.ts#L4)

**Review by sheetalkamat — APPROVED** [review]

**Comment by darbio** [comment]
> Nice one @photz! This otherwise looks good to me, but I'd like to a see a `Handler` type as well to be consistent with the other definitions in the package.
> 
> 
> 
> (e.g. https://github.com/photz/DefinitelyTyped/blob/53d582d7f42d1d004be4c07183749300f138f24b/types/aws-lambda/trigger/sqs.d.ts#L4)

@photz what are your thoughts on adding the `Handler` type as suggested by @jamesorlakin? Is this something you can do to help get this over the line?

**Comment by brew0722** [comment]
I found this PR while looking for a lambda trigger type by stepfunction in types/aws-lambda.
Can you tell me why it wasn't merged?

**Comment by darbio** [comment]
@brew0722 looks like it was abandoned by the author

**Comment by photz-insify** [comment]
> @brew0722 looks like it was abandoned by the author

I will make the change requested by @jamesorlakin and then re-open.

**Comment by photz** [comment]
> @brew0722 looks like it was abandoned by the author

I will make the change requested by @jamesorlakin and re-open.

**Pull request closed without merging**
