### PR TITLE
Add missing insertAt method type for Slice in prosemirror-model

### PR DESCRIPTION
**Pull request by RatoX**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ProseMirror/prosemirror-model/blob/master/src/replace.js#L46

### CODE REVIEW

**Comment by RatoX** [comment]
bump

**Comment by timjb** [comment]
The `insertAt` method is [not described in the ProseMirror Reference](https://prosemirror.net/docs/ref/#model.Slice) and hence should not be considered part of the public API. I don't want these type definitions to encourage people to write code that relies on private methods, which could change without warning. Therefore I'm in favor of not merging this PR.

**Comment by RatoX** [comment]
Why is this considered a private method? Because, there are some private functions on ProseMirror code, and those functions aren't accessible.

**Comment by RatoX** [comment]
@timjb confirmed is a private API :( 

https://discuss.prosemirror.net/t/is-insertat-method-on-slice-considered-an-private-api/3210

**Pull request closed without merging**
