### PR TITLE
core-js: Lint and use "lib" to eliminate unnecessary code.

### LINKED ISSUE #11700: @types/core-js conflicts with typescript/lib/lib.es6.d.ts when @types/core-js is not actually used
A simple reproduce repository: https://github.com/plantain-00/test , after `npm i && npm run build`, the error is:

``` ts
node_modules/@types/core-js/index.d.ts(21,14): error TS2300: Duplicate identifier 'PropertyKey'.
node_modules/typescript/lib/lib.es6.d.ts(4133,14): error TS2300: Duplicate identifier 'PropertyKey'.
```

Expected: no error, because the `app.ts` is empty. the `@types/core-js` is used in `static/app.ts`.

``` ts
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "core-js": "^2.4.1",
    "typescript": "^2.0.3"
  }
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes  #11700, #6494, #15104, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15093#issuecomment-285679803

`--lib es2017 dom dom.iterable` provides many types that are duplicated here.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by just-boris** [comment]
Actually, that was necessary code!

`core-js` is usually used in enviroments prior es6, so the fact, that some of that definitions are mathing with es6+ stuff doesn't matter, because `core-js` is a polyfill, e.g. it ships its own version of this types.

@andy-ms @mhegazy could you consider rolling this back?
The issue #15140 has quite much upvotes, so the problem is important.

**Comment by andy-ms** [comment]
TypeScript doesn't care if you have a real ES6 environment or a shimmed one. The types are the same either way. It's OK to use `--lib es6` with `--target es5`.

**Comment by DaSchTour** [comment]
But a shimmed ES6 environment is never and will never be equal to a nativ ES6 environment.

**Comment by emilio-martinez** [comment]
@andy-ms isn't the point of the Typescript definition files to describe what packages provide? I believe the definition should be accurate to the package, not the environment. Particularly with `core-js`, if somebody's using it, e.g., `import 'core-js'`, they're conceivably doing so because they're shimming their environment, no?

**Pull request merged**
