### PR TITLE
[@types/node] use explicit strings for path.sep and path.delimiter

### PR DESCRIPTION
**Pull request by k-yle**
rationale: This improves type safety when using `switch...case` statements with either of these attributes, and allows for more precise [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: *not applicable*
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
LGTM 👍

**Review by peterblazejewicz — APPROVED** [review]
@k-yle thanks!

**Review by mohsen1 — APPROVED** [review]
This is nice!

**Comment by k-yle** [comment]
Ready to merge ✨

**Pull request merged**
