### PR TITLE
react-native: add getRunnable method to AppRegistry

### PR DESCRIPTION
**Pull request by OverFlow636**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppRegistry.js#L138
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by OverFlow636** [comment]
This is failing for 
```
Error in react-navigation/v1
Error: ENOENT: no such file or directory, open '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-navigation/v1/index.d.ts'
```

not really sure how to resolve, the v1 of react-navigation does not seem to exist anymore

**Review by timwangdev — APPROVED** [review]

**Comment by alloy** [comment]
@andy-ms @DanielRosenwasser Do you have any thoughts on this CI failure?

**Comment by iRoachie** [comment]
His branch is out of date with master. The tests are trying to run for react-navigation but the folder structure has changed from having a `v2` folder to having a `v1`.

See the diff here:
`master`: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-navigation
`OverFlow636:patch-1`: https://github.com/OverFlow636/DefinitelyTyped/tree/patch-1/types/react-navigation

**Comment by OverFlow636** [comment]
@alloy @iRoachie Thanks for the help, merged master and its passing now.

**Comment by alloy** [comment]
@iRoachie Thanks 👍

**Pull request merged**
