### PR TITLE
Update to latest Stripe API version

### PR DESCRIPTION
**Pull request by wcandillon**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by wcandillon** [comment]
@wjohnsto @CodeAnimal Thank you so much for contributing this typing. The current version seems out of date with the latest API documentation. Was this typing written from scratch or generated from somewhere? Thank you in advance for letting me know how I could contribute to this typing as efficiently as possible.

**Comment by CodeAnimal** [comment]
@wjohnsto dtslint is pretty standard now on the DefinitelyTyped project. I'd recommend adding a tslint.json file and correct any issues that come up. And obviously, no PR could be accepted with changes to the definitions without reflecting those changes in the tests file. I'd recommend updating the test file first to reflect the most recent API as accurately as possible, then update the definitions to pass the tests.

**Comment by wjohnsto** [comment]
I wrote the original typings by hand. I agree with @CodeAnimal on new additions. I don't have a ton of time at the moment to make these updates, but contributions are welcome!

**Comment by RyanCavanaugh** [comment]
@wcandillon Please fix the failures indicated in the Travis CI log.

**Comment by minestarks** [comment]
Unfortunately I can't merge this in until the test failures are fixed. I'm closing this PR as it's been over two months with the failures unaddressed. Please open a new PR if you'd still like to get these changes in. Thanks!

**Pull request closed without merging**
