### PR TITLE
pixi.js to v4.3.0

### PR DESCRIPTION
**Pull request by clark-stevenson**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://pixijs.download/release/docs/index.html>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
Looks good. It looks like you once added yourself as the maintainer, but @dt-bot needs your GitHub username, not a repository. So the 3rd line of the file should be: `// Definitions by: Clark Stevenson <https://github.com/clark-stevenson>`.
Would be nice to add [linting](https://github.com/DefinitelyTyped/DefinitelyTyped#lint) sometime too.

**Comment by clark-stevenson** [comment]
I won't do this. I am tired of it.  This is my 10th attempt at pushing my own project.

**Comment by clark-stevenson** [comment]
Closed.

**Comment by bluepichu** [comment]
...I'm confused.  @clark-stevenson: Why was this closed without merge?

**Comment by clark-stevenson** [comment]
Sorry @bluepichu  I considered this a rejection almost as if it was guaranteed.  If this PR fails, then I will create a new issue looking for a volunteer to fight the red tape.  The frustration is incredible!  😄

**Comment by andy-ms** [comment]
I can indeed merge this, but it would be nice to fix the header.
There will be less red tape if @dt-bot can automatically find a reviewer (you) so a DT maintainer doesn't have to do it.

**Comment by clark-stevenson** [comment]
I will get on this tomorrow for sure! I am a bit naive here as it is a community effort but I didn't know much about the bot ability. Thanks 👍

**Comment by clark-stevenson** [comment]
Crap I think I did something wrong here.  I will make a new PR tonight as I don't have a clue how to address this error.

**Comment by andy-ms** [comment]
I think there's a way to fix this without making a new pull request.
(Be sure to make a backup of your changes first, since `rebase` can destroy data.)

Use [`git rebase -i HEAD~33`](https://git-scm.com/docs/git-rebase). (33 = # of commits your branch has different from `master`.)
Pick your commits: `772af3f pixi.js to v4.3.0`, `60dcf0d Fixed author and project links.`, and `159202e Added tslint.json`. (That is, leave these lines alone.)
Drop all others. (Replace `pick` with `drop`.)

When that finishes, `git pull --rebase upstream master`. `git diff master..HEAD --name-only` should now be just your changes and `git log` will list them.

**Comment by clark-stevenson** [comment]
Sorry guys, I don't have the skillset to update DT. I spent ages trying to solve this and made it much worse. I tried a new PR and it failed travis.  I don't know what I am doing. 

I will make a note of this on pixi-typescript so that someone more credible can handle it.  

Sorry for dragging this out guys.

**Pull request closed without merging**
