### PR TITLE
mixpanel: docs, missing callbacks, config type, formatting

### PR DESCRIPTION
**Pull request by Manduro**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/mixpanel/mixpanel-js/blob/master/build/mixpanel.globals.js#L2146-L2171> <https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.set_config>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Question: npm package `mixpanel-browser` has the same api. It has been mentioned these typings can be re-exported (<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17152#issuecomment-311132450>). How could I achieve a re export these typings in a `mixpanel-browser` folder?

### CODE REVIEW

**Comment by hjellek** [comment]
👍 

It's been a while since I used mixpanel now, but the changes seem OK.
Regarding re-exporting I guess you create a new definition package called mixpanel-browser, import these typings (or other appropriate typings) and export them inside a module there?

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Comment by Manduro** [comment]
Thanks!

I've been trying to get such a re-export done but didn't manage to get it to work. Also looked for other typings that do the same but haven't found one yet.

**Comment by gxolin** [comment]
Hi @Manduro @hjellek 
`Mixpanel.Config.loaded` should be `(any) => {}` instead of `(lib: Mixpanel) => {}` 
It's a developper callback used after load, and should not be hard typed.
Can you confirm ? Best.

**Pull request merged**
