### PR TITLE
[React] Allow to use ReactElement without Props

### PR DESCRIPTION
**Pull request by VincentLanglet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Most of the time, we (I) use ReactElement<any>. Passing props to this type is not really useful, so I added a default value.

### CODE REVIEW

**Comment by ferdaber** [comment]
Instead of changing every other package, since you added `any` as a default generic param, you can just leave them as-is and it should be backwards compatible.

**Comment by VincentLanglet** [comment]
@ferdaber I couldn't, the travis build failed because of tslint.

The other option is to disable the `use-default-type-parameter` for all these package.
But since I saw `TODOs` in the tslint.json, I didn't to add more technical debt.

**Review by ferdaber — APPROVED** [review]

**Review by huan086 — APPROVED** [review]

**Comment by ericanderson** [comment]
Making this change to all these packages forces anyone who uses one of them to go to bleeding edge react types. 

I prefer we only change react

**Comment by VincentLanglet** [comment]
@ericanderson Hi !

> Making this change to all these packages forces anyone who uses one of them to go to bleeding edge react types.

I understand it's unpleasant but : 

- This only impacts users who update one of these package, not just use. Some have not been touched for a long time and will not be touched for a long time at least.
- I see no impact in "going to bleeding edge react types", since there is no breaking change.

> I prefer we only change react

We still need to add `use-default-type-parameter` to 125 package, and start to create technical debt.

**Comment by ericanderson** [comment]
I was thinking your project takes a new dependency on a library. It doesn’t work because react types are older. The average dev doesn’t understand why. 

At best they file a bug on that type package. 

I agree with not creating debt and I also don’t want to make things harder on anyone who doesn’t know the nuance

**Comment by VincentLanglet** [comment]
> I agree with not creating debt and I also don’t want to make things harder on anyone who doesn’t know the nuance

@ericanderson Honestly, both solutions suit me.

The only difference for me was that it was easier to do a global search-replace. The other solution to disable 125 times the tslint rule manually is ... time consuming

**Comment by minestarks** [comment]
I'm ready to merge this change and agree that keeping the tslint rules is a better approach, but @ericanderson I don't quite understand your concern. As far as I can tell this PR doesn't change any dependencies, any package that has been touched already had a dependency on `react`. The change should be transparent to users. Did I miss something?

**Comment by ericanderson** [comment]
A user adds a new library and subsequent types. They haven’t updated react types. The new library does not work because it assumes a default for props.

**Comment by VincentLanglet** [comment]
> A user adds a new library and subsequent types. They haven’t updated react types. The new library does not work because it assumes a default for props.

```
yarn update @types/react
```
Problem solved.

Is this your only issue, or am I missing something ? Cause this is the same for a lot of PR.
We're adding definitions, and, if you're not up to date with it, sometimes, bad things happen.

Moreover if a library depend of react types, the type is defined as dependency.

**Comment by RyanCavanaugh** [comment]
> A user adds a new library and subsequent types. They haven’t updated react types. The new library does not work because it assumes a default for props.

This is true of almost any additive change, though. If we said you can't add some new type alias to an existing definition file because a future version of a dependent library might take a dependency on it in a way that didn't work on a older version of the upstream package, we could never do anything at all.

**Comment by VincentLanglet** [comment]
@minestarks I have issue with Travis.
The job takes too much time...

**Comment by sandersn** [comment]
@VincentLanglet I have some ideas on how to speed up the CI run, but in the meantime I'm just running it locally. You can do that too with `npm run test` (and you might beat my somewhat puny laptop).

I'll report back on any failures.

**Comment by sandersn** [comment]
The following packages had errors: react-jss, next-redux-saga, react-lifecycle-component, slate-react, ui-box.

react-jss, at least, fails with thousands of lint failures across is 30,000 lines. There too many failures to list here, so I'd recommend

1. Reproducing these failures with `npm run lint react-jss`
2. Turning off most or all of the offending rules in react-jss' tslint.json.

You may want to do similar things for the other packages, although they are much smaller.

**Comment by ericanderson** [comment]
My argument was to let the various package maintainers decide when to take a dependency on props with defaults rather than making the change now. I’m in favor of the change for the react package

**Comment by VincentLanglet** [comment]
@sandersn When I launch locally `npm run test`, it takes one hour but I have no error.

And I have also no error with these commands.
```
npm run lint react-jss
npm run lint next-redux-saga
npm run lint react-lifecycle-component
npm run lint slate-react
npm run lint ui-box
```

And it would be surprising if I introduce a thousand errors with this only change.
I should only impact one tslint rule. (use-default-type-parameter)

**Comment by minestarks** [comment]
I'll restart the CI job - I could have sworn I'd seen it pass at some point.

I'm just about ready to merge this otherwise. 

Concerns about updating dependencies are acknowledged, but letting the package maintainers update the packages later doesn't avoid the issue anyway - just delays it. This is just one of the constraints of DefinitelyTyped we've been OK to live with :smiley:

**Comment by sandersn** [comment]
@VincentLanglet my install of tslint was probably out of date. react-jss is clean on the most recent test run on Travis.

I'd recommend merging this after Travis completes whether it does so with a timeout or not; I think we will have seen enough of the run to be confident in the change.

**Comment by VincentLanglet** [comment]
I agree @minestarks the `typescript-bot` removed the `Travis CI build failed` label sometimes.
But now, everytime I get `The job exceeded the maximum time limit for jobs, and has been terminated.` on the CI.

Locally, `npm run test` take one hour but return no error.

**Comment by minestarks** [comment]
We got until the letter "s" . I'm calling this good.

**Comment by VincentLanglet** [comment]
Good luck `typescript-bot`, you have so much work.

**Comment by dfee** [comment]
This is failing for me with `@types/react` @ 16.8.2.

I guess this is because a new version of `@types/react` hasn't been published, so `P` as an optional prop for `ReactElement` isn't yet released. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/22530ee36249ccb8ca4a5f393009f155963c7a79/types/react/index.d.ts#L86

I'm not sure how releases are coordinated here. But it seems a bit backwards for these types to be updated when they're literally incompatible with anything released.

When can we expect an update to `@types/react`, then?

**Comment by VincentLanglet** [comment]
@dfee The `typescript-bot` will publish an new version for `@types/react`. He's publishing the 60+ libraries, and taking some time to do this.

It was indeed better to start by publishing the `@types/react` library.

**Comment by VincentLanglet** [comment]
@dfee `@types/react` is published

**Comment by sandersn** [comment]
@VincentLanglet @dfree typescript-bot is also updating about 1000 other packages due to some other cleanup I kicked off around the same time. This delay in publishing is not normal.

But yes, alphabetical order is not as good as dependency order for publication.

**Comment by VincentLanglet** [comment]
Victory !

**Comment by hensmith** [comment]
Found my way here after an hour or so of debugging and thought I'd share some insight into my journey so far in case it helps others save a bit of time! It began with an attempt to use react-test-renderer for the first time in my project, which gave the usual easily fixed tsc error:

```
error TS7016: Could not find a declaration file for module 'react-test-renderer'
```

<br>

So I did `yarn add --dev @types/react-test-renderer` and retried tsc. This time, it said:

```
node_modules/@types/react-test-renderer/index.d.ts:45:27 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

45     unmount(nextElement?: ReactElement): void;
                             ~~~~~~~~~~~~

node_modules/@types/react-test-renderer/index.d.ts:46:25 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

46     update(nextElement: ReactElement): void;
                           ~~~~~~~~~~~~

node_modules/@types/react-test-renderer/index.d.ts:51:29 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

51     createNodeMock(element: ReactElement): any;
                               ~~~~~~~~~~~~

node_modules/@types/react-test-renderer/index.d.ts:53:37 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

53 export function create(nextElement: ReactElement, options?: TestRendererOptions): ReactTestRenderer;
                                       ~~~~~~~~~~~~
```

<br>

Oh no! I did some googling, found this pull request, and understood just enough to know that it'd be helpful to see some version number resolutions. So I did `grep -A 5 @types.react yarn.lock` and it said:

```
"@types/react-helmet@^5.0.8":
  version "5.0.8"
  resolved "https://registry.yarnpkg.com/@types/react-helmet/-/react-helmet-5.0.8.tgz#f080eea6652e44f60b4574463d238f268d81d9af"
  integrity sha512-ZTr12eDAYI0yUiMx1K82EHqRYa8J1BOOLus+0gL+AkksUiIPwLE0wLiXa9FNqD8r9GXAi+yRPZImkRh1JNlTkQ==
  dependencies:
    "@types/react" "*"

"@types/react-test-renderer@^16.8.1":
  version "16.8.1"
  resolved "https://registry.yarnpkg.com/@types/react-test-renderer/-/react-test-renderer-16.8.1.tgz#96f3ce45a3a41c94eca532a99103dd3042c9d055"
  integrity sha512-8gU69ELfJGxzVWVYj4MTtuHxz9nO+d175XeQ1XrXXxesUBsB4KK6OCfzVhEX6leZWWBDVtMJXp/rUjhClzL7gw==
  dependencies:
    "@types/react" "*"

"@types/react@*":
  version "16.7.18"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.7.18.tgz#f4ce0d539a893dd61e36cd11ae3a5e54f5a48337"
  integrity sha512-Tx4uu3ppK53/iHk6VpamMP3f3ahfDLEVt3ZQc8TFm30a1H3v9lMsCntBREswZIW/SKrvJjkb3Hq8UwO6GREBng==
  dependencies:
    "@types/prop-types" "*"
    csstype "^2.2.0"
```

I'm not much of a yarn pro, but this gave me the feeling that adding @types/react explicitly to my package.json might help, so I did `yarn add --dev @types/react`. Infortunately this increased the number of linter errors to 185 ([gist](https://gist.github.com/hensmith/fcfb2cb5adf56dbf6bd75a18aa7f88cc)). Here's a sample of them:

```
node_modules/@types/react-test-renderer/index.d.ts(45,27): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

node_modules/@types/react/index.d.ts(2737,19): error TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any, any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any, any>' and 'ReactElement<any>' are not identical.

node_modules/@types/storybook__react/node_modules/@types/react/index.d.ts(2852,13): error TS2717: Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.
```

These are super weird, right? Like most of them are saying "must be of type X, but here has type X", where X _is_ of type X, so the error message is this weird self-contradicting sentence. I gave up on that and did `yarn remove @types/react`.

The eventual fix I've settled on was to just pin the version of `@types/react-test-renderer` to 16.8.0. It looks like this in my package.json, so if you're here from Google in search of a quick fix this might be the line you want! The lack of `^` character before the version number is important here! 

```
"@types/react-test-renderer": "16.8.0"
```

I haven't really understood what's happened here but it looks like some kind of very difficult versioning difficulties! For now I'm gonna chill at 16.8.0 and cross my fingers. Feel free to ping me if you try more stuff to untangle all this, and I'll happily update with the results I see from newer versions! 😄

**Comment by VincentLanglet** [comment]
@hensmith The `@types/react-test-renderer: 16.8.0` does not use `ReactElement` but `ReactElement<any>`, so it doesn't need the last version of `@types/react`.

The `@types/react-test-renderer: 16.8.1` which is installed when you use the `^` character, are using `ReactElement` and need the last version of `@types/react`.

But when you add the last version of `@types/react` you can have duplicate, this way: 
```
"@types/react@*":
  version "16.7.18"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.7.18.tgz#f4ce0d539a893dd61e36cd11ae3a5e54f5a48337"
  integrity sha512-Tx4uu3ppK53/iHk6VpamMP3f3ahfDLEVt3ZQc8TFm30a1H3v9lMsCntBREswZIW/SKrvJjkb3Hq8UwO6GREBng==
  dependencies:
    "@types/prop-types" "*"
    csstype "^2.2.0"

"@types/react@^16.8.3":
  version "16.8.3"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.7.18.tgz#f4ce0d539a893dd61e36cd11ae3a5e54f5a48337"
  integrity sha512-Tx4uu3ppK53/iHk6VpamMP3f3ahfDLEVt3ZQc8TFm30a1H3v9lMsCntBREswZIW/SKrvJjkb3Hq8UwO6GREBng==
  dependencies:
    "@types/prop-types" "*"
    csstype "^2.2.0"
```

Then you'll have a lot of errors.

A good package to avoid this is the [yarn deduplicate](https://github.com/atlassian/yarn-deduplicate) from atlassian.

**Comment by hensmith** [comment]
:pray: :pray: :pray: That yarn deduplicate package is amazing, thank you!!!

Am now running `"@types/react": "^16.8.3"` and `"@types/react-test-renderer": "^16.8.1"`. With a little help from that deduplicate command, it runs fine! The yarn.lock entry is exactly as you describe too, which is downright spooky 👻😆

Thanks so much!!

**Pull request merged**
