### PR TITLE
Optional 3rd argument for addObserver and removeObserver

### PR DESCRIPTION
**Pull request by gossi**
This makes the 3rd argument for `Observable.addObserver` and `Observable.removeObserver`. I made this changes completely only, using github. Same accounts for the tests 😬

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
👍 Thanks!

The relevant lines of code in the Ember codebase are [`addObserver`](https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-runtime/lib/mixins/observable.js#L353), which calls [another `addObserver` method](https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-metal/lib/observer.js#L23), which calls [this `addListener`](https://github.com/emberjs/ember.js/blob/3a4b38000b2cc3ce49d93f4df45415db545b3752/packages/ember-metal/lib/events.js#L60) function which has the argument as optional.

**Review by dwickern — CHANGES_REQUESTED** [review]
The new overload has this signature:
```ts
addObserver<Target>(key: keyof this, target: Target): void;
```
which is equivalent to
```ts
addObserver(key: keyof this, target: any): void;
```

Instead, shouldn't it be something like this? 
```ts
addObserver(key: keyof this, method: ObserverMethod<this, this>): void;
```

Could you also update `Ember.addObserver` / `Ember.removeObserver` to match?

**Review by mfeckie — APPROVED** [review]
Looks good to me!

**Comment by dwickern** [comment]
Could you also add tests for the the `Ember` methods, e.g.
```ts
Ember.addObserver(this, 'foo', lambda);
Ember.removeObserver(this, 'foo', lambda);
```

**Comment by gossi** [comment]
@dwickern @chriskrycho could you have another look? To me it is ready for approval?

**Review by dwickern — APPROVED** [review]
Looks good, thank you!

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
