### PR TITLE
@ckeditor/ckeditor5-utils Fix Emitter params

### PR DESCRIPTION
**Pull request by fedemp**
Params for `on`, `once`, `listenTo` after the first one (which is
always an `EventInfo`) depend on the listened event, and are different
for each event. Only `dom/emittermixin` passes a `DomEventData`.

Also `Observable` extends `Emitter`, so whichever implements `Observable`, must implement `Emitter`.

 ```
/**
 * Fires an event, executing all callbacks registered for it.
 *
 * The first parameter passed to callbacks is an {@link module:utils/eventinfo~EventInfo} object,
 * followed by the optional `args` provided in the `fire()` method call.
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ckeditor/ckeditor5/blob/1d69e2cb4c3506d9bcf309c84f9261f88b8176d8/packages/ckeditor5-utils/src/emittermixin.js#L21-L31
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by fedemp** [comment]
@fdintino It's finally here. Wanna take a look. I'll tackle `Observable` after this, so `set` and its events are typed to.

**Review by fdintino — CHANGES_REQUESTED** [review]
I noted two issues I encountered when I pointed my project at these types.

Perhaps it's outside the scope of this PR, but I liked how you switched the order of the generic type parameters of `EventInfo` in an earlier attempt at fixing the Emitter types.

**Review by fdintino — COMMENTED** [review]
My project is now compiling against this PR, so I think it's nearly ready to go.

I noticed a few things that I think would improve the accuracy of the types, though I don't think any of them are blockers necessarily. Once you respond I'll be happy to approve!

**Review by fdintino — APPROVED** [review]

**Comment by fdintino** [comment]
If I could propose one improvement: if you were to change `EditorWithUI` back into an interface with only `ui` on it, it would perhaps be helpful if you typed plugins as:

```ts
readonly editor: Editor & Partial<EditorWithUI>;
```

Having conditional guards like `if (!("ui" in this.editor)) ...` is fine, but it would be more natural and convenient to be able to do `this.editor.ui?.componentFactory` or `if (!this.editor.ui) throw new Error("UI required");`

**Comment by elibarzilay** [comment]
(I made it possible to self-merge, but you can of course revise it further re the last comment from @fdintino)

**Comment by fedemp** [comment]
> If I could propose one improvement: if you were to change `EditorWithUI` back into an interface with only `ui` on it, it would perhaps be helpful if you typed plugins as:
> 
> ```ts
> readonly editor: Editor & Partial<EditorWithUI>;
> ```
> 
> Having conditional guards like `if (!("ui" in this.editor)) ...` is fine, but it would be more natural and convenient to be able to do `this.editor.ui?.componentFactory` or `if (!this.editor.ui) throw new Error("UI required");`

Screenshot from 2021-11-02 21-39-03

The implemention in this PR lets you do that.

**Comment by fedemp** [comment]
I will merge now cause this is already a huge PR. If we need to modify `Plugin`, we can create a smaller PR that will be easier to merge.

**Comment by fedemp** [comment]
Ready to merge

**Pull request merged**
