### PR TITLE
[Highcharts] AxisLabelFormatterOptions property "value" is incorrectly typed as a number

### PR DESCRIPTION
**Pull request by justinmwarner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Look at the demo given from Highcharts doc here and check the type of ```this.value``` in the example.
-- https://api.highcharts.com/highcharts/yAxis.labels.formatter
-- http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/labels-formatter-linked/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by justinmwarner** [comment]
@paulvanbrenk Saw you comment on the most recent change to this file. Wondering if you could take a quick look at this? It's a single line change.  I've included links to the documentation supporting this change.

Thanks!

**Comment by mhegazy** [comment]
in the example in http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/labels-formatter-extended/, `this.value` is passed to `Highcharts.numberFormat(this.value, 0);` which expects a `number` and not a `string`.

**Comment by justinmwarner** [comment]
@mhegazy nice catch. So it uses the type of the axis values.  And that is currently typed as an any.

I'll update this to be an any then.

Thanks.

**Comment by mhegazy** [comment]
not sure why this is needed.. seems from the example that it is a `number`..

**Comment by justinmwarner** [comment]
If you look at the example I linked to, it is a string.  It seems it comes from the value of axis. Which in the def file is an any. So this should also be an any then.

Here it is again: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/labels-formatter-linked/

**Pull request merged**
