### PR TITLE
add @storybook/addon-actions

### PR DESCRIPTION
**Pull request by joscha**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] ~~Create it with `dts-gen --dt`, not by basing it on an existing project.~~ _(Isn't possible at the time, opened https://github.com/Microsoft/dts-gen/pull/63 which is merged, but has not been released, yet /cc @RyanCavanaugh)_
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

references https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17434, https://github.com/storybooks/storybook/issues/1166

### CODE REVIEW

**Comment by joscha** [comment]
Build says:
```
In @storybook/addon-actions, unexpected path mapping for @storybook/addon-actions: 'storybook__addon-actions'
```
must be part of the change coming in #17434 - will roll back that part.

**Comment by joscha** [comment]
@paulvanbrenk do you know when this will be released? Is there an automatic cycle?

**Comment by paulvanbrenk** [comment]
@joscha yeah, it should take no more than hour... though we had some issues last week, i'll ask around.

**Comment by joscha** [comment]
@paulvanbrenk whatever you did, it worked :) Seeing https://www.npmjs.com/package/@types/storybook__addon-actions now, thanks!

**Pull request merged**
