### PR TITLE
Typings for Meteor 1.3

### PR DESCRIPTION
**Pull request by barbatus**
Rename current typings to `meteor-1.2.d.ts` in order with DefinitelyTyped guidelines to mark it's for the previous major version of Meteor.

Introduce initial version of `meteor.d.ts` for Meteor 1.3 which adds new ES6-like namespaces based on the existing atmosphere packages.

`meteor.d.ts` contains also first pass of multiple improvements (based off `meteor-1.2.d.ts`):
Refactoring: move definitions for each namespace into one place
Cleanup: removes some minor deprecated definitions
Elaborations: add multiple corrections and additions based on the official docs (docs.meteor.com)

Further improvements will proceed

### CODE REVIEW

**Comment by fullflavedave** [comment]
Thumbs up.  These changes all look good to me (except for the 5 leftover implicit any typings in meteor-1.2-tests.ts holding up the Travis CI build).

**Comment by pgrm** [comment]
👍 great to see things being updated

**Comment by horiuchi** [comment]
@barbatus Please fix Travis CI errors: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/126369858#L447

**Comment by vangorra** [comment]
:+1:

**Comment by barbatus** [comment]
Closing this PR since DefinitelyTyped version of Meteor typings is deprecated.
Please read and use them as described here https://github.com/meteor-typings/meteor

**Pull request closed without merging**
