### PR TITLE
Lodash: `fp.mapValues`: fix inference with contextual type

### PR DESCRIPTION
**Pull request by OliverJAsh**
I have added two tests, one for `fp.map` and one for `fp.mapValues`. The former passes, but the latter fails. I expect both to pass—`fp.mapValues` should work like `fp.map`.

How should I fix the overloads for `mapValues` so that its test will pass?

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by aj-r** [comment]
Here is the error message:

```
Type 'LodashMapValues1x1<string>' is not assignable to type '(obj: Dictionary<number>) => Dictionary<number>'.
  Types of parameters 'obj' and 'obj' are incompatible.
    Type 'Dictionary<number>' is not assignable to type 'string | null | undefined'.
      Type 'Dictionary<number>' is not assignable to type 'string'.
```

I think the problem is caused by this overload in `mapValues`:

```
<TResult>(callback: (value: string) => TResult): LodashMapValues1x1<TResult>;
```

The problem is caused by the way type inference works in typescript. Because it sees this overload first, it infers `x` to be `string`, and remembers that inference (it doesn't re-infer for future overloads). I tried creating a TypeScript issue for this once, but it got closed as a "design limitation".

`map` doesn't have this overload which is why it has no issue.

I can think of some possible workarounds, none of which are good:

1. Use conditional types. This should work well, but is only supported in TS>=2.8, and we're still stuck supporting 2.2.
2. Change the order of overloads so the `<T, TResult>(callback: (value: T) => TResult): LodashMapValues2x1<T, TResult>;` overload comes first. This might fix the type inference issue but I'm not sure if it will break something else.

**Comment by OliverJAsh** [comment]
> The problem is caused by the way type inference works in typescript. Because it sees this overload first, it infers x to be string, and remembers that inference (it doesn't re-infer for future overloads). I tried creating a TypeScript issue for this once, but it got closed as a "design limitation".

It looks like it's just using the first overload full stop? 🤔 

> Change the order of overloads so the <T, TResult>(callback: (value: T) => TResult): LodashMapValues2x1<T, TResult>; overload comes first. This might fix the type inference issue but I'm not sure if it will break something else.

I'm struggling to understand how to reverse engineer the FP typings to the original `mapValues` overloads. Once I figure that out, I'll try to do this!

**Comment by aj-r** [comment]
Yeah I was worried that order was important. In that case this may not be fixable until we can bump the TS version to 2.8. Until then you'll just have to put explicit types on your callback parameters :(

**Comment by OliverJAsh** [comment]
Seeing as we can't fix this until we can safely bump the TS version, I've opened an issue to track this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27395.

**Pull request closed without merging**
