### PR TITLE
Update forge-viewer for new three.js types

### PR DESCRIPTION
**Pull request by sandersn**
three.js went back to publishing its types on Definitely Typed, which means that forge-viewer has to use the up-to-date types. Two of the types, Geometry and Face3, were deprecated since the last update. Since I don't know anything about forger-viewer, I decided to by refer to the new location of the deprecated types.

Also forge-viewer doesn't need an external dependency on three anymore.

### CODE REVIEW

**Comment by liskaj** [comment]
@sandersn Forge-viewer is using older version of three.js (71) so we can't use latest type definitions. If this is available on DefinitelyType we can reference this or provide our own types as part of forge-viewer package.

**Comment by sandersn** [comment]
If I understand correctly, you're suggesting copying Geometry and Face3 into forge-viewer, right? That makes sense to me.

**Comment by liskaj** [comment]
Maybe we could just include type definitions (three.d.ts etc) from older version of THREE.js for now. I may have copy of this somewhere.

**Review by liskaj — CHANGES_REQUESTED** [review]
As discussed before I'd suggest to include type definitions for older version (r71) of three.js into forge-viewer. I might be able to look on this sometime this week.

**Comment by sandersn** [comment]
Thanks @liskaj

Superceded by #51371

**Pull request closed without merging**
