### PR TITLE
[ramda] Removed utility types in `tools.d.ts` to integrate with "ts-toolbelt" instead

### PR DESCRIPTION
**Pull request by millsp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pirix-gh/DefinitelyTyped/blob/86a43f47d8212707b2305f0eaca462f0d4c774d5/types/ramda/index.d.ts#L1418
I also brought out curried types for `R.flip` like @imcotton wanted to do
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by pirix-gh** [comment]
Hi @sandersn,

Travis won't allow me to publish, says "Dependency ts-toolbelt not in whitelist". But it is.

Any insights?

**Comment by sandersn** [comment]
Argh, travis' cache must not understand github references in package.json any more. I reset the caches for now, but I need to find out whether it's a bug in Travis or intended behaviour.

**Comment by pirix-gh** [comment]
Couldn't find any info on this topic, it's most likely not working as intended. Thanks!

**Comment by pirix-gh** [comment]
Hey @andrewbranch, what does "CV" stand for in "Mean CV" for the ts bot?

**Review by Nemo108 — APPROVED** [review]

**Comment by andrewbranch** [comment]
@pirix-gh [Coefficient of variation](https://en.wikipedia.org/wiki/Coefficient_of_variation). It’s the _mean_ because we take multiple samples at every identifier location (time allowing—we limit each run to an hour), so the ideal case is something like

- there are 5287 identifiers
- there are 5 measurements of how long it takes to get completions for each of those
- in a perfect world, every measurement in any set of 5 would be identical, because we were measuring the exact same thing
- it's not a perfect world, so we take the CV of those 5 samples to see how imperfect the world is
- at the end, we have 5287 CV values that represent how internally consistent our measurements were, so we average them and report it

It’s a metric that’s entirely about whether or not we can trust the other numbers; it has nothing to do with the performance of the package itself.

_However_—we _did_ run out of time on these measurements, so for most of those 5287 identifiers, we only have _one_ sample, which means a CV of zero.

There are two things highly suspicious about this reporting, which I have only just noticed, thanks to your question. It is either a _remarkable_ coincidence, or much more likely, a bug, that the number of identifiers in tests is exactly the number of samples we took both for master and for the PR. The ideal case would be `samples = identifiers * 5`, but if we hit the time limit, I would expect to see a random number between 0 and `identifiers * 5`. There’s absolutely no reason why it should be `samples == identifiers`, so very likely either we’re printing the wrong number to the table, or something is weird with the actual measurement algorithm and it’s not starting a second pass.

The other suspicious thing is that the CV _isn’t_ zero, despite the fact that it essentially told us that every identifier got exactly one measurement. It sounds more like _most_ identifiers got one sample, and some got two.

Combined, this leads me to believe that we’re _probably_ just mis-reporting either the number of samples taken, which is actually an important metric to have to understand whether or not Mean CV means anything.

Thanks for the question; I’m adding this to my list of bugs to fix soon! 😄

**Pull request merged**
