### PR TITLE
Set more exact types for fabric.StaticCanvas methods, add missing properties

### PR DESCRIPTION
**Pull request by NotWoods**
Changed `StaticCanvas` methods to return `this` instead of `StaticCanvas` since they return the same instance.

Changed callback functions for:
- [`setOverlayImage`](http://fabricjs.com/docs/fabric.Canvas.html#setOverlayImage)
- [`setBackgroundImage`](http://fabricjs.com/docs/fabric.Canvas.html#setBackgroundImage)
- [`setOverlayColor`](http://fabricjs.com/docs/fabric.Canvas.html#setOverlayColor)
- [`setBackgroundColor`](http://fabricjs.com/docs/fabric.Canvas.html#setBackgroundColor)
- [`loadFromJSON`](http://fabricjs.com/docs/fabric.Canvas.html#loadFromJSON)
Previously `Function` was used, now exact parameter types are specified.

Changed `properties` array param in [`clone`](http://fabricjs.com/docs/fabric.Canvas.html#clone) to take strings instead of any array.

Changed `IImageOptions` to use optional params since [`new fabric.Image`](http://fabricjs.com/docs/fabric.Image.html#initialize) doesn't require all the types to be specified.

Added missing [`corner_____`](http://fabricjs.com/docs/fabric.Object.html#cornerSize) properties to `fabric.Object`

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  
_See links above_
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @NotWoods, sorry for the delay. Before I merge this in, do you want to either

1. Fix up the author name/emails on your commits or
2. Associate your GitHub account with your commits' emails?

Let me know!

**Comment by NotWoods** [comment]
Done!

**Comment by DanielRosenwasser** [comment]
👏

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
