### PR TITLE
Update Select2 AjaxFunction interface

### PR DESCRIPTION
**Pull request by pajaroblanco**
The interface was incorrectly defined making it impossible in typescript to use the transport function defined inside the ajax option. Select2 calls the transport function with 3 parameters: 

1. The JQueryAjaxSettings object
2. A success callback to notify select2 of a successful response
3. A failure callback to notify select2 of a failed response

See https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/data/ajax.js#L68

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Thoughts @borisyankov ?

**Comment by jramsay** [comment]
[From the Select2 documentation for ajax.transport:](http://select2.github.io/select2/) Function that will be used to perform the ajax request. Must be parameter-compatible with $.ajax. Defaults to $.ajax if not specified. Allows the use of various ajax wrapper libraries such as: AjaxManager.  Then looking at [jQuery Ajax ](http://api.jquery.com/jquery.ajax/ ) the definitions currently specified match these.

**Comment by pajaroblanco** [comment]
@jramsay I linked to the source of the select2 4 API where you can see the actual function signature. You referenced the old v3 API. It's not clear for which version these definitions were intended, but the definition currently doesn't work for v4, despite what's in the documentation. Just a note: I'm using this with the ng2-select2 package for Angular which assumes select2 v4 but it looks like these types assume v3 so it's causing me headaches.

**Comment by minestarks** [comment]
@pajaroblanco this makes sense to me after looking at v4 documentation, merging

**Pull request merged**
