### PR TITLE
glob: allow ReadonlyArray in input position

### PR DESCRIPTION
**Pull request by ajafff**
This is not necessary for the v5 typings, as these types were recently introduced in the v7 typings.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

**Comment by ajafff** [comment]
@amcasey for some reason merging this PR didn't publish a new version of the package. Is this expected?

**Comment by ajafff** [comment]
also pinging @andy-ms: for some reason merging this PR didn't publish a new version of the package. Is this expected?

**Comment by amcasey** [comment]
@ajafff I understand this is expected to fix the problem: https://github.com/Microsoft/types-publisher/pull/486

**Comment by amcasey** [comment]
@ajafff I think things are working again?

**Pull request merged**
