### PR TITLE
Update types for winston-syslog to v2.0

### PR DESCRIPTION
**Pull request by felix-hoc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/winstonjs/winston-syslog, https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]

**Comment by felix-hoc** [comment]
Not sure what I should make of this failing build, to me it looks like only the old version (v1) produces errors. I thought it might be because of the typescript version, but that last commit didn't seem to change anything...
Can anybody give me a hint?

**Comment by uniqueiniquity** [comment]
Tagging @andy-ms. It seems like @types/winston@2.3.9 is not installing. Could you try pinning the version of @types/winston in the v1 package.json to 2.3.9 rather than ^2.3.9? I think it's upgrading to 2.4.4, seeing in the notneeded.json that it should expect a stub definition from that, and not installing. That's my best guess for now.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by andy-ms** [comment]
You could just delete the `v1` directory if you're unlikely to need to make new changes to it in the future.

**Comment by felix-hoc** [comment]
Thank you very much! @uniqueiniquity's solution worked like a charm.

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
