### PR TITLE
[@wordpress/api-fetch] Remove DT definitions

### PR DESCRIPTION
**Pull request by sarayourfriend**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by dsifford — APPROVED** [review]

**Comment by sarayourfriend** [comment]
Seems like the `DefinitelyTyped.DefinitelyTyped` check is failing on something unrelated to my changes 🤔

**Review by dsifford — APPROVED** [review]

**Comment by orta** [comment]
I've re-run CI, and am rebasing this PR in the background too

**Comment by sarayourfriend** [comment]
Thanks @orta, though it appears to still fail on something unrelated to the PR 😞

**Comment by sarayourfriend** [comment]
@orta could I get another review on this PR when you have a chance? CI is green now 🎉

**Comment by sarayourfriend** [comment]
@orta Can I get another review on this PR before it goes stale? Thanks!

**Comment by orta** [comment]
Yeah, I'll have to manually merge this because the commit is still marked as red. Looks reasonable to me 👍🏻

**Comment by sarayourfriend** [comment]
Thanks!

**Pull request merged**
