### PR TITLE
[gtag.js] Type page view config param

### PR DESCRIPTION
**Pull request by 2007heaven**
Sending a page view is one of the most common use cases of gtag.js and it is also controlled by this param.

Related source: https://developers.google.com/analytics/devguides/collection/gtagjs#install_the_global_site_tag

### CODE REVIEW

**Comment by kootoopas** [comment]
Hello @Rokt33r. Does this seem okay to you? :slightly_smiling_face:

**Comment by kootoopas** [comment]
Is it possible for someone to take a look at this?

**Review by orta — APPROVED** [review]
Seems pretty harmless, the code would work regardless of this change (given the tests test for it) but there would be better tooling support with this

**Comment by kootoopas** [comment]
Ready to merge

**Pull request merged**
