### PR TITLE
Update createjs libraries

### PR DESCRIPTION
**Pull request by noobiept**
Start using union types, and some small fixes.

### CODE REVIEW

**Comment by vvakame** [comment]
@evilangelist @gyohk could you review this PR?

**Comment by gyohk** [comment]
I'm sorry to become slow.
Looks good to me.
Thank you!

**Comment by evilangelist** [comment]
Looks good.

**Comment by vvakame** [comment]
@noobiept thanks mate!
@gyohk @evilangelist thanks!

**Comment by noobiept** [comment]
Thanks everyone!

**Pull request merged**
