### PR TITLE
Fix break because of lib update

### PR DESCRIPTION
**Pull request by sheetalkamat**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

**Comment by Phoenix1747** [comment]
So... what did you change here? There is no description to any of this.

**Comment by nspire909** [comment]
Why were FileSystemWriteChunkType and FileSystemWritableFileStream commented out? This change breaks my code.  createWritable() still returns a Promise<FileSystemWritableFileStream> and FileSystemWritableFileStream.write() takes a FileSystemWriteChunkType as its param. Are these types supposed to be imported from somewhere else now?

**Comment by jakebailey** [comment]
The types were fixed to be compatible with TS 5.1. the commented out types are now declared in 5.1 and conflict. However, the types were copied and are using typesVersions so you should be getting the 5.0 dir for 5.0 and below and so nothing should have changed.

**Comment by Phoenix1747** [comment]
Works for me, I'm using TS 5.0.4.

**Comment by nspire909** [comment]
I am using TS 4.9.5. I don't think I can upgrade to 5 until Angular does in the next release. I am using:
`/// <reference path="../../../../../node_modules/@types/wicg-file-system-access/index.d.ts" />` to get the Types to work. I guess you are saying I should point that to the one in the ts5.0 folder instead. Or is there a better way to import these types? The above reference path thing is the only way I have been able to get this to work. I would prefer to use ESM imports, but haven't had luck with that in the past.

**Comment by jakebailey** [comment]
5.0 would behave the same; the ts5.0 dir applies to `<=5.0`.

I definitely don't think that's the right way to reference these types. At the very least, you should be able to write `<reference types="wicg-file-system-access">`.

If that doesn't work, then you can hardcode the path to be `.../ts5.0/index.d.ts`, but manually referring to anything by path into `node_modules` is definitely not a good idea for exactly the reason it broke for you; it's not resilient to typesVersions.

**Comment by nspire909** [comment]
Ok. Yes `<reference types="wicg-file-system-access" />`  is much better than the reference path that I was using. I probably should have read the readme at the root of this repo. :)

**Pull request merged**
