### PR TITLE
multer-s3 3.0.x definitions

### PR DESCRIPTION
**Pull request by Takaitra**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/anacronw/multer-s3/pull/162
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Takaitra** [comment]
Are aws-sdk v3 dependencies not allowed or should I follow these instructions and open a PR against the tools package?
```
Error: In package.json: Dependency @aws-sdk/client-s3 not in the allowed dependencies list.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/*` to `namespace__*` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to microsoft/DefinitelyTyped-tools adding it to `packages/definitions-parser/allowedPackageJsonDependencies.txt`.
```

**Comment by Takaitra** [comment]
The `@aws-sdk/client-s3` dependency was added to the allow list.

**Review by joshuajeschek — APPROVED** [review]
👍

**Review by terski — APPROVED** [review]
LGTM!

**Comment by tcaesvk** [comment]
Thanks for notifying aws sdk v3. Looks good to me.

**Comment by Takaitra** [comment]
Ready to merge

**Pull request merged**
