### PR TITLE
fix(@ember/debug): `registerWarnHandler` & `registerDeprecationHandler`

### PR DESCRIPTION
**Pull request by buschtoens**
- `registerWarnHandler`
  - `options` may be `undefined`
  - `next` expects `message`
- `registerDeprecationHandler`
  - `options` may be `undefined`
  - `next` expects `message` and `options?`

The upstream types I am basing this on haven't been defined as extensively in versions prior to `v4.4.0-alpha.3`, but AFAICT from the JS source, they were always expected like this. 

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/emberjs/ember.js/blob/v4.4.0-alpha.3/packages/%40ember/debug/lib/handlers.ts#L3-L9
  - https://github.com/emberjs/ember.js/blob/v4.4.0-alpha.3/packages/@ember/debug/lib/deprecate.ts#L36-L74
  - https://github.com/emberjs/ember.js/blob/v4.4.0-alpha.3/packages/%40ember/debug/lib/warn.ts#L13
- [x] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
Thanks!

**Comment by buschtoens** [comment]
Now _that_ was quick! ⚡

**Comment by chriskrycho** [comment]
Haha I happened to open my email to check on an order I needed to update and it was an easy one. 🎉

**Comment by buschtoens** [comment]
Seems like TS 4.7 has issues. I only ran the tests for 4.6... Will check and report back.

**Review by chriskrycho — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by buschtoens** [comment]
Ready to merge

**Pull request merged**
