### PR TITLE
phonegap-plugin-push - Added hasPermission Method to PushNotificationStatic

### PR DESCRIPTION
**Pull request by larrybahr**
Added hasPermission Method to PushNotificationStatic.
Removed new key in PushNotificationStatic because it is no longer supported.
Added ';' where needed

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [hasPermission](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationhaspermissionsuccesshandler---android--ios-only)
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by fredgalvao** [comment]
It's a :+1: for me, but I think, now that we have moved the type definitions over to the plugin repo itself, we should move maintenance and evolution there too. 
What do you think, @larrybahr, @macdonst?

**Comment by larrybahr** [comment]
I would rather have the type definitions on DefinitelyTyped since the [documentation ](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/TYPESCRIPT.md) links to DefinitelyTyped and at the bottom of the page it states that issues should be submitted on the DefinitelyTyped repo. I would remove the TypeScript definitions from the phonegap-plugin-push repo to eliminate redundant code.

If my opinion is in the minority I would be happy to upload the changes to both repos.

**Comment by fredgalvao** [comment]
You're right in the point where the documentation is inconsistent with this idea, but it's been a fairly majoritary move of type definitions going into their own repo, even though DT is still huge.
So, we're left with two options:
- keep the docs how they are, and keep working on DT
- update the docs, telling users we now have type definitions in-house, and move work to the plugin repo itself

 My opinion is on to go home, but I really don't have that much vision of the TS landscape. That's why I would like at least one more voice.

There was talk on the cordova mailing list, which came from guys @Microsoft by the way, suggesting we move type definitions from DT to their own repos, but a blank spot in the conversation was: when should we remove them from DT and say we're done migrating.

I mentioned this issue on the ML, trying to get more feedback on the general topic, I'm willing to wait a day or two before we move with this PR.

**Comment by aozgaa** [comment]
Let's take this change. If you would like to direct typings to your own repo, you can open a PR, following the guidance [here](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

**Comment by fredgalvao** [comment]
@aozgaa Nobody from the cordova mailing list answered, and I got feedback from no one else. What's DT take on this? Now that npm@types are considered first-class citizens, is it desired for types to move to their own home? Is DT still gonna try to hug them all?

Regardless, thanks for merging, I was close to forgetting about this (sorry).

**Pull request merged**
