### PR TITLE
Updated node-vault typings to v0.9.8

### PR DESCRIPTION
**Pull request by owenfarrell**
If removing a declaration:

[x] Delete the package's directory.
[x] Add it to notNeededPackages.json.

### CODE REVIEW

**Comment by owenfarrell** [comment]
cc: @kr1sp1n

**Comment by YuJianrong** [comment]
@owenfarrell I noticed the `.d.ts` have been added into the official repo: https://github.com/kr1sp1n/node-vault/blob/master/index.d.ts
I think we should send PR to the official team to update the typing instead of update here. And we should create a PR to ask DefinitelyTyped to remove this type definition.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Agree with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43526#issuecomment-607389222

**Comment by owenfarrell** [comment]
@RyanCavanaugh , @YuJianrong - better?

**Pull request merged**
