### PR TITLE
Update w3c-web-hid definitions

### PR DESCRIPTION
**Pull request by nondebug**
* fix broken URLs
* make all HIDDevice members required
* remove reportId and data from HIDConnectionEvent

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://wicg.github.io/webhid/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by kkiyama117** [comment]
@nondebug
Thank you so much for making it, and LGTM, but would you please make sure that you fill in blanks at the top of the page, even if not all?
Incidentally, I think one of the members of WICG or the contributors of `WICG/webhid`  should be the (co-)maintainer to making it easier to follow the specification. 
If you agree with that and don't mind, please read the [description](https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners), then replace or add your name to the definition in `index.d.ts`.

**Comment by davisford** [comment]
@nondebug seems it was approved -- can you merge?

**Review by kkiyama117 — APPROVED** [review]
LGTM

**Comment by nondebug** [comment]
Thanks @kkiiyama117 and @davisford, I see the approval but it looks like I don't have write access to merge the change.

**Comment by nondebug** [comment]
Ready to merge

**Pull request merged**
