### PR TITLE
Removed Global Scope THREE

### PR DESCRIPTION
**Pull request by luho383**
RenderItem had references to Global THREE object. These caused in unresolved type THREE.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@luho383 Please fix the failures indicated in the Travis CI log.

**Comment by efokschaner** [comment]
Hi @luho383 thanks for the fixes.

Please see this comment and discussion for information on the lint failures: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21192#issuecomment-341540126

I'm :+1: for his change. You may need to wait for the other pr with the lint fixes to merge.

**Comment by luho383** [comment]
The last commit fixes lint errors in three. There are remaining ones in physijs. If these fixes don't met the coding standard used here, ignore these commits.

**Comment by efokschaner** [comment]
@luho383 if you merge latest master to resolve conflicts this should be good to go.

**Pull request merged**
