### PR TITLE
Add declarations for the 'pgn-parser' npm package

### PR DESCRIPTION
**Pull request by tneisinger**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@tneisinger 
what about doing this that way:
```ts
// Type definitions for pgn-parser 2.1
// Project: https://github.com/kevinludwig/pgn-parser#readme
// Definitions by: Tyler Neisinger <https://github.com/tneisinger>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/**
 * The result of a game or sequence of moves.
 */
export type Result =
    | '1-0' // White wins
    | '0-1' // Black wins
    | '1/2-1/2' // Draw
    | '*'; // Game ongoing or result inconclusive

/**
 * A PGN comment.
 */
export interface Comment {
    text: string;
}

/**
 * A PGN header.
 */
export interface Header {
    /**
     * The name of the header.
     * For the header '[Date "2004.01.24"]' the name is 'Date'
     * For the header '[White "Magnus Carlsen"]' the name is 'White'
     */
    name: string;

    /**
     * The value of the header.
     * For the header '[Date "2004.01.24"]' the value is '2004.01.24'
     * For the header '[White "Magnus Carlsen"]' the value is 'Magnus Carlsen'
     */
    value: string;
}

/**
 * A chess half-move (one ply).
 */
export interface Move {
    /**
     * A single half-move, such as 'Nf6' or 'd4'
     */
    move: string;

    /**
     * The list of comments that are associated with this move.
     */
    comments: string[];

    /**
     * The number of the move. Moves made by white will have a move_number, but black
     * moves will not.
     */
    move_number?: number;

    /**
     * A list of alternative sequences of moves. The first move of each Rav is an
     * alternative to this move. If the PGN does not provide alternatives for this
     * move, ravs will be undefined.
     */
    ravs?: Rav[];
}

/**
 * An alternative sequence of moves.
 */
export interface Rav {
    /**
     * The list of moves.
     */
    moves: Move[];

    /**
     * The result of the sequence of moves.
     */
    result: Result | null;
}

/**
 * The type returned by the parse function (if the parse was successful).
 */
export interface ParsedPGN {
    /**
     * A list of the comments that were above the headers. This will be null if there
     * were no comments above the headers.
     */
    comments_above_header: Comment[] | null;

    /**
     * The headers of the pgn. This will be null if there were no headers.
     */
    headers: Header[] | null;

    /**
     * The comments that were between the headers and the moves. This will be null if
     * there were no comments between the headers and the moves.
     */
    comments: Comment[] | null;

    /**
     * The moves of the game
     */
    moves: Move[];

    /**
     * The result of the game
     */
    result: Result;
}

/**
 * Parse a PGN string. Throw an error if the parse is unsuccessful.
 *
 * @param pgnString
 * @throws {SyntaxError}
 */
export function parse(pgnString: string): ParsedPGN[];

export as namespace pgnParser;
```
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library

**Comment by tneisinger** [comment]
The version above causes `npm test pgn-parser` to throw this error:

```
ERROR: 1:1  npm-naming  The declaration doesn't match the JavaScript module 'pgn-parser'. Reason:
The declaration should use 'export =' syntax because the JavaScript source uses 'module.exports =' syntax and 'module.exports' can be called or constructed.

To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
If you won't fix this error now or you think this error is wrong,
you can disable this check by adding the following options to your project's tslint.json file under "rules":

    "npm-naming": [true,{"mode":"code","errors":[["NeedsExportEquals",false]]}]
 See: https://github.com/Microsoft/dtslint/blob/master/docs/npm-naming.md
```

The pgn-parser source code does not use `module.exports =`. Should I disable that warning in tslint.json like the error suggests?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@tneisinger thx!

**Comment by tneisinger** [comment]
Ready to merge

**Pull request merged**
