### PR TITLE
Add mongodb ops attribute to UpdateWriteOpResult  Interface

### PR DESCRIPTION
**Pull request by alanmarcell**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#~WriteOpResult>

### CODE REVIEW

**Comment by CaselIT** [comment]
From the documentation it seems that `UpdateWriteOpResult` interface does not have the `ops` property.

**Comment by alanmarcell** [comment]
@CaselIT 
Sorry, I catch the 2.1 docs.
Can you please check again with the 2.2 docs?

**Comment by CaselIT** [comment]
@alanmarcell I still don't see it. I think you are updating `UpdateWriteOpResult` but referring to the documentation for `WriteOpResult`

**Comment by alanmarcell** [comment]
@CaselIT You are right.
I'm calling the ```Collection.replaceOne(..)``` either to ADD and to UPDATE. 
In the case of adding, the response seems to be an WriteOpResult.

I guess we must update the ```replaceOne(...)``` response to ``` UpdateWriteOpResult``` **OR** ```WriteOpResult```

**Pull request closed without merging**
