### PR TITLE
[DropZone] Prettier formatting + updated some fields in DropZoneOptions 

### PR DESCRIPTION
**Pull request by arnederuwe**
Applied prettier formatting rules
Fixed some linting rules, a lot of work still remains
Updated DropZoneOptions interface to reflect the current [docs](https://www.dropzonejs.com/#configuration-options):
- added function type to url property
- added function type to method property
- replaced thumbnailMethod and resizeMethod to a union type as they can only contain 2 specific strings as options

I have tested the change in my own code
I have run npm lint

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Can the spacing related changes be applied in a separate PR after this merged?
Very difficult to review spacing changes **AND** other changes together

**Comment by arnederuwe** [comment]
> Can the spacing related changes be applied in a separate PR after this merged?
> Very difficult to review spacing changes **AND** other changes together

Apologies, I updated the pull request with multiple commits, should be clear what changed now

**Comment by PikachuEXE** [comment]
Can you remove the first 2 commits
Coz they just mean no change together
Just rebase without those 2 commits on `master` & force push
Other changes look fine to me

**Review by PikachuEXE — CHANGES_REQUESTED** [review]
As what I said above

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
