### PR TITLE
Update typings for JW Player 6.

### PR DESCRIPTION
**Pull request by IsaacSchemm**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://support.jwplayer.com/customer/portal/articles/2051720-jw6-javascript-api-reference
- [ ] Increase the version number in the header if appropriate.

Notes:
* Library documentation at https://support.jwplayer.com/customer/portal/articles/2051720-jw6-javascript-api-reference
* The documentation says there is no .setFullscreen, but both JW Player 6 and JW Player 7 will honor .setFullscreen(false).
* The current version, JW Player 7, is largely backwards-compatible, although new methods have been added (not included here) and .onSomething event handlers are deprecated in favor of .on('something').

### CODE REVIEW

**Comment by martinduparc** [comment]
@IsaacSchemm I don't think the PR should include a new `Definitions by` author else we will end up with a very long list. The rest looks good, thanks!

**Comment by IsaacSchemm** [comment]
OK. Do you want me to remove my name, or can you do it?

**Comment by martinduparc** [comment]
You can do it. Just update your branch and the PR should take the change into account.

**Review by martinduparc — APPROVED** [review]

**Comment by martinduparc** [comment]
This can be merged

**Pull request merged**
