### PR TITLE
Added Mercado Pago's Frontend JS 

### PR DESCRIPTION
**Pull request by meliguicarvalho**
Added typings for Mercadopago`s Frontend JS SDK.
[Project here
](https://github.com/mercadopago/sdk-js)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by AdaltonLeite — APPROVED** [review]

**Review by peterblazejewicz — DISMISSED** [review]
@meliguicarvalho 
what's the relation to this package?  (some repo, TS support, published to NPM):
https://www.npmjs.com/package/@mercadopago/sdk-js

**Comment by meliguicarvalho** [comment]
> t, published to NPM

Hello!

The package you linked is a wrapper that imports the SDK-JS from the CDN via NPM, to facilitate the importing and avoid importing via script. It does not have all the methods typed.

So this package add ts support for our [JS SDK](https://www.mercadopago.com.br/developers/pt/docs/sdks-library/client-side/mp-js-v2) and all its methods. It can be used in conjunction with the package you mentioned, because the package you mentioned does not have all the types for our SDK, it only facilitates the importing.

**Comment by peterblazejewicz** [comment]
so this one works as declaration provider for whatever code is using SDK when using script tags? The module is not CommonJS module per-se, it looks like webpack-based project exports for global script, so like:
```ts
// core.d.ts
declare namespace mercadopago {

    enum Locale {
        ES_AR = 'es-AR',
        ES_CL = 'es-CL',
....
```
```ts
// index.d.ts
/// <reference path="core.d.ts" />

declare namespace mercadopago {
    interface MercadoPago {
        new(publicKey: string, options: mercadopago.Options): mercadopago.MercadoPagoCore;
    }
}

declare var MercadoPago: mercadopago.MercadoPago;
```
(see: no `export` keyword being used,
can be used with `import` syntax in CJS that way:
```ts
import 'mercadopago-sdk-js';

// initiate MP library
const mpInstance = new window.MercadoPago("pk", {});
// or: const mpInstance = new MercadoPago("pk", {});

mpInstance.getIdentificationTypes();
mpInstance.getInstallments({ amount: "100", bin: "123456" });
mpInstance.getIssuers({ bin: "123456" });
mpInstance.getPaymentMethods({ bin: "123456" });
```

**Comment by meliguicarvalho** [comment]
> so this one works as declaration provider for whatever code is using SDK when using script tags? The module is not CommonJS module per-se, it looks like webpack-based project exports for global script, so like:
> 
> ```ts
> // core.d.ts
> declare namespace mercadopago {
> 
>     enum Locale {
>         ES_AR = 'es-AR',
>         ES_CL = 'es-CL',
> ....
> ```
> 
> ```ts
> // index.d.ts
> /// <reference path="core.d.ts" />
> 
> declare namespace mercadopago {
>     interface MercadoPago {
>         new(publicKey: string, options: mercadopago.Options): mercadopago.MercadoPagoCore;
>     }
> }
> 
> declare var MercadoPago: mercadopago.MercadoPago;
> ```
> 
> (see: no `export` keyword being used, can be used with `import` syntax in CJS that way:
> 
> ```ts
> import 'mercadopago-sdk-js';
> 
> // initiate MP library
> const mpInstance = new window.MercadoPago("pk", {});
> // or: const mpInstance = new MercadoPago("pk", {});
> 
> mpInstance.getIdentificationTypes();
> mpInstance.getInstallments({ amount: "100", bin: "123456" });
> mpInstance.getIssuers({ bin: "123456" });
> mpInstance.getPaymentMethods({ bin: "123456" });
> ```

Hello! Thanks for your review!

I adapted the code to use namespaces like you suggested. I only had to keep the exports because they are necessary to pass the tests.

**Comment by peterblazejewicz** [comment]
Hey, I do think script module is just a global script, so one should stick to global script definition, like in this TS template:
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html#examples-of-global-libraries
if you need export/import features, you can use already existing module (as per readme), `@mercadopago/sdk-js`. Global scripts do not required `export` keyword

**Review by andrewbranch — APPROVED** [review]

**Comment by AdaltonLeite** [comment]
Ready to merge

**Comment by andrewbranch** [comment]
@typescript-bot ahem 🤨

**Pull request merged**
