### PR TITLE
D3 Update to 4.8.0 (d3-array 1.2 [Feature/Fix] and d3-format 1.2 [Feature])

### LINKED ISSUE #15600: d3-format Update Definitions to v1.2
Optional percentage symbol added to locale definition object.

Update definitions.

Self-assigned @tomwanzek

cc @gustavderdrache

### LINKED ISSUE #15902: d3-array Update to version 1.2.0
Update definitions to [new version 1.2 release](https://github.com/d3/d3-array/releases/tag/v1.2.0)

@tomwanzek

### PR DESCRIPTION
**Pull request by tomwanzek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3/releases>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

This PR includes changes to **d3-format** and **d3-array** to bring them up to their latest minor versions (both v1.2).

Note that the changes to **d3-array** also include a definitions __bug fix__: `d3.tickStep(...)` returns a `number` value instead of an array of `number`.

Closes #15600 .
Closes #15902 .

@gustavderdrache pls review and approve. Thx. T

### CODE REVIEW

**Comment by gustavderdrache** [comment]
👍 Looks good to me.

**Comment by tomwanzek** [comment]
Could this please be merged? Thx. T

**Comment by tomwanzek** [comment]
@RyanCavanaugh: not sure, if there is anyone specific who is parsing the ready to merge PRs these days. If someone could hit merge on this one, that would be splendid. Cheers, T

**Comment by tomwanzek** [comment]
@andy-ms Thx a lot for closing the outdated legacy issues, I flagged so quickly! Could you also kindly merge this PR it's good to go. T

**Pull request merged**
