### PR TITLE
Uses "export default" syntax.

### PR DESCRIPTION
**Pull request by ryasmi**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
Is this PR same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9020#issuecomment-211047386 ?

**Comment by ryansmith94** [comment]
I don't think so @vvakame, because Firebase is actually a class and it looks like they use [`module.exports =`](https://www.firebase.com/docs/web/quickstart.html).

**Comment by vvakame** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9019#issuecomment-211058255

**Comment by ryansmith94** [comment]
See [#9019 comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9019#issuecomment-213773775)

**Comment by ryansmith94** [comment]
Closing because of inactivity

**Pull request closed without merging**
