### PR TITLE
JSDataPromise clarification.

### PR DESCRIPTION
**Pull request by arma-gast**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by reppners** [comment]
👍

**Comment by andy-ms** [comment]
Needs to be made merge-able.

**Comment by arma-gast** [comment]
Don't know why github marks file as conflicting, local git merges branch to master without conflicts.

**Comment by andy-ms** [comment]
I think you can fix this by merging on the command line, then pushing.

**Comment by arma-gast** [comment]
Created #11346. Same there: conflicting files.

**Pull request closed without merging**
