### PR TITLE
Add ArangoDB typescript typings

### PR DESCRIPTION
**Pull request by pluma**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

---

This is a WIP for the ArangoDB JavaScript environment (similar to Node.js but not running on Node.js). ArangoDB defines several built-in modules residing under the `@arangodb` prefix (including a bare `@arangodb` module, which is not supported by npm AFAIK).

I'm running into a few problems at the moment:

* ~~The typings are currently formatted with Prettier. I'll need to make sure to change it to 4 spaces.~~
* We literally have a function that returns an object with a property called "new", not sure how to distinguish that from a "new-able" object
* I'm unclear when to use `ReadonlyArray`. Most functions don't modify their inputs and some input types are objects containing arrays. Do I need to define those contained arrays as readonly too?
* ~~VSCode~~ linter freaks out about a few things:
    * ~~"using a declare modifier in an already ambient context" (declare inside a `declare namespace`) but the typings seem to work fine.~~
    * ~~`Datatabase` has a catch-all string index type which apparently conflicts with the named methods? Not sure how to type this correctly.~~
    * `Buffer`, `NodeJS.Module` and `NodeJS.Console` are apparently not in scope
    * rest parameters apparently must be last but we have some methods that have them in 
other places -- as far as I can tell TypeScript can handle that but VSCode still complains
    * ~~`const enum` is forbidden but having the collection type as a magic number seems smelly. Any way to work around this?~~
* The file needs to declare a number of different modules, not sure if it's doing that correctly considering most typings here just type individual NPM modules
* We're including [a bunch of compatibility modules mirroring node's built-in modules](https://docs.arangodb.com/3.3/Manual/Appendix/JavaScriptModules/) and I'm not sure whether these also need to be defined or if we can just delegate those to the Node.js typings.
* It makes sense to me for `ArangoDB` and `Foxx` to exist as global namespaces analogous to `NodeJS` but I'm not sure this is a good practice. Would love some feedback on this.
* I haven't started with the tests yet -- should I test every possible variation of each method (within reason) or just some of the basics?
*  ~~The linter currently blows up with this message:~~

### CODE REVIEW

**Comment by pluma** [comment]
I've managed to get the linter working so I'll try to address any other problems it spits out. Not sure what to do about the problems I mentioned though (rest parameter, declare in ambient context, const enum, etc).

**Comment by pluma** [comment]
I think this takes care of all the low-hanging fruit.  Other than the empty tests file, the remaining linter errors are

* `A rest parameter must be last in a parameter list.`
* `A 'declare' modifier cannot be used in an already ambient context.`
* ```Use of `const enum`s is forbidden.```
* `'export' keyword is redundant here`
* `Property 'x' of type 'X' is not assignable to string index type 'T'`
* `Cannot find name 'Buffer'`
* `Cannot find name 'NodeJS'`

As above, I have no idea how to begin to address these.

**Comment by pluma** [comment]
Linting should now pass but I can't for the life of me figure out how to overide Node's globals. Figuring this out will likely be necessary to be able to ensure typings for other modules will be compatible.

**Comment by RyanCavanaugh** [comment]
@pluma looks ok to me though I'm not a domain expert on this library. Do you want me to merge this, or is there more work you'd like to do first?

**Comment by pluma** [comment]
@RyanCavanaugh I'd love some feedback on the "rest parameter in the middle" problem. Is brute force enumerating a handful variations really the best workaround? TypeScript seems to understand the rest parameter in other locations than the end but the linter hates it (and it wouldn't be valid JS of course).

Also am I right thinking there's no way to monkeypatch the NodeJS "globals" to extend their types (i.e. override `declare var module: NodeJS.Module` with `Foxx.Module` which extends it)? We can ship a workaround for that but it'd be useful to be able to add methods to the console object at least, which doesn't seem to expose its interface.

BTW, ArangoDB is not a library but a JS environment (like Node it's built on V8). I'm one of the maintainers.

**Comment by pluma** [comment]
FYI before getting this merged I'd like to extend the test file to make sure the typings can deal with various use cases.

Also, I'm still unclear on whether the workaround for properties called "new" is correct/necessary to avoid mistaking the object for something "newable". And I'd love to know if the folder name is appropriate considering this is a JS environment, not an npm module.

**Comment by RyanCavanaugh** [comment]
>  I'd love some feedback on the "rest parameter in the middle" problem. Is brute force enumerating a handful variations really the best workaround? TypeScript seems to understand the rest parameter in other locations than the end but the linter hates i

TS doesn't have any good pattern for middle-rest params, unfortunately.

LMK when you'd like this merged. Thanks!

**Comment by pluma** [comment]
@RyanCavanaugh I'm done with this PR for now, I think. Feel free to merge any time.

**Comment by pluma** [comment]
:tada:

**Pull request merged**
