### PR TITLE
[@types/passport-azure-ad] Fix types to support latest API version

### PR DESCRIPTION
**Pull request by JasonMan34**
This PR uses [the official Microsoft Azure AD docs for access tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens) as reference for the types.

* Fixes the **roles** type
* Adds type definitions for all v1.0 basic claims
* Re-orders some definitions to fit the order in the official docs

### CODE REVIEW

**Comment by ShekharNain** [comment]
Thanks @JasonMan34 for fixing the role type. 
Reg. the new fields, have you validated that the token returned by the passport-azure-ad library contains the corresponding values or not for v1 & v2 both?

**Comment by JasonMan34** [comment]
@ShekharNain I have validated the types for v2, but not for v1 - those have been copied from the docs directly (My company uses v2, so I can't check v1)

**Review by ShekharNain — APPROVED** [review]
Changes looks good based on the docs - https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by JasonMan34** [comment]
Ready to merge

**Pull request merged**
