### PR TITLE
[@types/facebook-js-sdk] fix getAuthResponse type

### PR DESCRIPTION
**Pull request by mahmoudzohdi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
 - FB.getAuthResponse: https://developers.facebook.com/docs/reference/javascript/FB.getAuthResponse/
 - authResponse Object type: https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by amritk — APPROVED** [review]

**Comment by sanpoChew** [comment]
Can I ask why grantedScopes was removed from AuthResponse? It's stil a thing according to the docs: https://developers.facebook.com/docs/reference/javascript/FB.login/v3.0

**Comment by mahmoudzohdi** [comment]
@sanpoChew 
I can't see `grantedScopes` property in this page.
kindly find the `authResponse` object response under `Response objects` title from here:
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus?locale=en_US

**Comment by sanpoChew** [comment]
@mahmoudzohdi it's mentioned in the options table at the bottom of that page, it's only supplied when you pass return_scopes: true as an option when calling login: 

"return_scopes | boolean | When true, the granted scopes will be returned in a comma-separated list in the grantedScopes field of the authResponse"

**Comment by mahmoudzohdi** [comment]
@sanpoChew 
Oh, you are right.
I will create PR now and add it in `authResponse` 
Thanks

**Comment by mahmoudzohdi** [comment]
@sanpoChew  but it will be optional because it will be returned in case `return_scopes` is `true` only

**Pull request merged**
