### PR TITLE
fix(maxmsp): Color methods

### PR DESCRIPTION
**Pull request by zsteinkamp**
* Adds Max.getcolor(name) method
* Adds optional signatures for:
  * Sketch.glcolor(Color)
  * Sketch.glclearcolor(Color)
  * Sketch.glcolormask(Color)
* Adds tests for the above
* Update links to point to Max 8 docs (was Max 7)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.cycling74.com/max8/vignettes/themes
- [x] (n/a) If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by twhiston — APPROVED** [review]
Thanks very much for your contribution!

**Comment by zsteinkamp** [comment]
Ready to merge

**Comment by zsteinkamp** [comment]
Thank you @twhiston for the quick turnaround.
Is there a Max/JS/TS community out there, or are we it? :)
I figure we should be in touch. zack@steinkamp.us, or have a look at my stuff at https://steinkamp.us/music-tools -- happy to hear ideas or feedback!

**Comment by twhiston** [comment]
@zsteinkamp oh nice m4l plugins. Not a user of live myself but those look very interesting! Fractal note echo especially. 
I think the biggest Max TS thing i've done is GLRepl in the max package manager, but theres a few other max bits and bobs on my website.

There's nowhere that Max/JS/TS people hang out specifically as far as I know, but there's always the max discord for a space to talk. I don't post on there much but I am a member and if you tag me or dm me (tomw5287 / tomw) I'll reply. Otherwise you can always get me at tom@tomwhiston.com

**Comment by zsteinkamp** [comment]
Cheers @twhiston!

**Pull request merged**
