### PR TITLE
feat(dagre): add filterNodes function type

### PR DESCRIPTION
**Pull request by sand4rt**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Dagre uses graphlib under the hood that exposes the filtersNodes function](https://github.com/dagrejs/graphlib/blob/master/lib/graph.js#L286)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by sand4rt** [comment]
Someone else asked for this to be included in the dagre/graphlib docs: https://github.com/dagrejs/graphlib/issues/107

**Comment by GrahamLea** [comment]
I don't believe `string => boolean` is the right type for the callback.
The IDs for Nodes can be any hashable type.
[Here's an example](https://dagrejs.github.io/project/dagre-d3/latest/demo/sentence-tokenization.html) where integers are used.
You can also see that [the type for the parameter of the `node()` function](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/91b2a0165914993c68aa3c59c021faa24a7c3076/types/dagre/index.d.ts#L38), which [accesses the same object](https://github.com/dagrejs/graphlib/blob/ebfd0b870e00b561b9a0cfebd8b0982a1c23fc02/lib/graph.js#L165), is `string | Label`.

However, this PR is not the first time this mistake has been made in this type definition. The types for the parameters to `hasNode()` and `removeNode()` (at least) are restricted to string. The lack of complaints/PRs around non-string IDs suggests that de facto usage of the library (in Typescript at least) is to always use strings.

So the question becomes: Let through one more overly-constrained function type definition? Or use this as an opportunity to fix the whole thing? I don't know what the right answer is. Anyone got a strong opinion?

Also a minor naming thing, the argument should probably be named `filter` as it is in the library, rather than `callback`?

**Comment by sand4rt** [comment]
`setDefaultEdgeLabel` and `setDefaultNodeLabel` are also using callback as prop name. Thats why i picked callback. I don't mind using filter for the `filterNodes` function prop name instead. Would you like me to change this?

Changing all necessary types to `string | Label` could be a separate PR?

**Comment by sandersn** [comment]
@GrahamLea I'm inclined to take this PR as-is and let your other suggestions be done afterward. Thoughts? If I don't hear back in a day or two I'll merge this.

**Comment by GrahamLea** [comment]
@sandersn Yeah, makes sense. Doesn't seem reasonable to place on @sand4rt the burden of the sins of all previous committers. 🙂

**Comment by GrahamLea** [comment]
(I don't have permission to merge, by the way, which makes it kind of odd that @typescript-bot asked me to review. 🤷🏻‍♂️)

**Comment by sandersn** [comment]
I'll go ahead and merge.

@elibarzilay Any idea what might be the problem with @GrahamLea 's PR permissions?

**Pull request merged**
