### PR TITLE
fix: Input event details type for yaireo__tagify

### PR DESCRIPTION
**Pull request by navaniharsh31**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://postimg.cc/F7nWCh3G

### CODE REVIEW

**Comment by Brakebein** [comment]
@navaniharsh31 Thanks for highlighting that there is a different `detail` object for the `input` event.

However, it is a bit more complicated as I just noticed. If Tagify is in normal mode, then the `detail` object contains the data as defined in the types so far and how it is documented in the readme: `inputElm, tagify, value` (and `isValid`, which is missing in the type definition) ([see demo](https://yaireo.github.io/tagify/#section-input)).

If Tagify is in mix mode, then the `detail` object contains `tagify, textContent` ([see demo](https://yaireo.github.io/tagify/#section-mix)).

So, the `detail` object depends on how `mode`is set in the config.

**Comment by blutorange** [comment]
Not sure if we want to do this, but this is how it would like with an additional type parameter (which also allows for further adjustments if we find any other differences between the three modes)

https://github.com/blutorange/DefinitelyTyped/tree/tagify-updates-patch

**Comment by Brakebein** [comment]
@blutorange Thanks for your approach. Makes it more complicated and harder to follow. But to mirror the core library's behavior, we probably have no choice.

The default mode setting is null/undefined. So, I wonder if it's not possible to set `null` instead of `TagifyMode` in the generics:

```ts
declare class Tagify<T extends Tagify.BaseTagData = Tagify.TagData, M extends Tagify.TagifyMode = null>
```
(and in all other occurences)

Wouldn't it resolve the hacky constructor definitions (i.e. keep it as it was)?

**Comment by blutorange** [comment]
> Wouldn't it resolve the hacky constructor definitions (i.e. keep it as it was)?

I had experimented with that idea a little bit, but

* it doesn't eliminate the need for the hacky constructors, the type parameters can still be set to any allowed value explicitly, or TS might infer an undesirable type parameter anyways
* with the default `M=undefined` (or `null`, but `undefined` as that's the default when `mode` is not specified at all), you get other errors when people create e.g. the settings separately: `const setting: TagifySettings = { ... }; const tagify = new Tagify(el, settings)`. This has the potential of breaking more existing code, people would have to go and add the type parameters explicitly.

If we had control over the code, a cleaner way would be to create separate method for the different modes (`Tagify.mixed(...)`, `Tagify.select()`) (or avoid different event details altogether); but unfortunately, we can't do that.

> Makes it more complicated and harder to follow. But to mirror the core library's behavior, we probably have no choice.

Yeah, I wonder if there are more differences we haven't found, and more might be added later on.

**Comment by Brakebein** [comment]
I get the point with default generic `M=undefined`: I thought when setting `mode: 'mix'` it would override `M`. But of course, this is not true. You would need to explicitly set the generic.

Two questions:

- Is it right that the hack in the second contructor is on `inputElement`? `inputElement: (HTMLInputElement | HTMLTextAreaElement) & ([undefined] extends [M] ? unknown : never)`
- In the tests: in TagifySettings, the `callbacks.input` event is still `InputEventData | InputEventDataMix`. Shouldn't it be also narrowed down regarding on how `mode` is set?

**Comment by blutorange** [comment]
> Is it right that the hack in the second contructor is on 

Yeah, you can't do anything with the second argument since it's optional, so no checks are applied when it's not provided. The point of that hack is to "ban" the second constructor signature if `M` does not include `undefined` (and thus, the `settings` argument is _not_ optional). 

For the first constructor, we want to enforce the `mode` setting, which is otherwise optional (but perhaps this could be rewritten so that the `mode` setting is not optional anymore)

> In the tests: in TagifySettings, the callbacks.input event is still InputEventData | InputEventDataMix

Which line are you talking about specifically? By default, when `M=undefined|null|"mix"|"select"`, we don't know which it is. But if `mode` is set (and TS manages to infer `M`), then it should be narrowed down.

But yeah, that's my first attempt at this, I don't really like the solution yet, so if anybody has any ideas, they would be welcome.

**Comment by blutorange** [comment]
@navaniharsh31 As it seems we want to move forward with encoding the mode as a type parameter, it would be great if you could accept the pull request https://github.com/navaniharsh31/DefinitelyTyped/pull/1

**Comment by blutorange** [comment]
So I thought about this again and I don't see a better way to adjust the typings depending on the mode. When the `mode` or the `settings` object is omitted, then `M` should be inferred `undefined`, but that's not possible, since there's no settings object from which TS could infer anything.

Another solution that involves modifying the source code could have been to simply create two different events (say `input` and `mixInput`).

As it stands, we either

* proceed with the current solution and add the type parameter
* make all non-common properties in the `input` event data option and add a JS doc comment

**Comment by Brakebein** [comment]
> Which line are you talking about specifically? By default, when `M=undefined|null|"mix"|"select"`, we don't know which it is. But if `mode` is set (and TS manages to infer `M`), then it should be narrowed down.

Right at the beginning of the tests: at L12 `TagifySettings` are set with `mode: null` (L17) and `callbacks.input` (L85). I would expect that the input event is either `InputEventData` or `InputEventDataMix` according to `mode`, but it is `InputEventData | InputEventDataMix`, which you catch with if/else. (https://github.com/blutorange/DefinitelyTyped/blob/tagify-updates-patch/types/yaireo__tagify/yaireo__tagify-tests.ts)

> Another solution that involves modifying the source code could have been to simply create two different events (say input and mixInput). (perhaps we should raise an issue for this, since textContent also missing in the docs?)

Or maybe that the input `event.detail` is the same for all modes.

> - proceed with the current solution and add the type parameter
> - make all non-common properties in the input event data option and add a JS doc comment

I first thought that extra type parameter is better/cleaner to match the library's behavior. But it makes it a hell more complicated. By now, I would actualy prefer the second option. However, TS will raise issues in some users' code if things are suddenly optional.

**Comment by blutorange** [comment]
> Right at the beginning of the tests: at L12

Ah I see. Yes, there's a type annotation with `TagifySettings` on the variable, so that's what's getting used. If the settings were given to constructor directly, TS would infer the type. 

> But it makes it a hell more complicated. By now, I would actualy prefer the second option.

I agree, it's too much overhead for too little gain. Perhaps it would be worth it if there were more differences between the modes. But if it's only the input event data, I don't think so.

> However, TS will raise issues in some users' code if things are suddenly optional.

Technically, right now things could be breaking for users during runtime, since the types are "lying". So this could be seen as a bug fix.

Instead of making everything optional, there's a second option:

```js
interface InputEventData { inputElm; value ;}
interface MixInputEventData { textContent; }
interface EventDataMap {
  input: InputEventData | MixInputEventData;
}
```

I would prefer this approach. People will have to adjust their code either, but this models the scenario better: it's one of both types, and nothing is optional. It also makes it possible for people to just cast the event data to `InputEventData` or `MixInputEventData` if they know which mode they are using. What do you think?

**Comment by blutorange** [comment]
> I'm not sure if we should close this PR and you open another one, or if you can merge the changes into this one?

As far as I understand changes need to be added to [navaniharsh31:tagify-changes](https://github.com/navaniharsh31/DefinitelyTyped/tree/tagify-changes). Perhaps @navaniharsh31 you could change this PR as mentioned at the bottom of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64834#issuecomment-1483837489 ?

Otherwise I guess we can open a new PR.

**Review by blutorange — COMMENTED** [review]
Voting to close in favor of #64981

**Pull request closed without merging**
