### PR TITLE
[paper] Include Base class definition + type save getters and setters

### PR DESCRIPTION
**Pull request by anion155**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[paper.js/Base.js](https://github.com/paperjs/paper.js/blob/develop/src/core/Base.js)>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by anion155** [comment]
@luz-alphacode So, maybe `color: Color; setColor(c: Color | string): void;` everywhere?

About symbols. Did not looked into this, yet. Maybe later.

**Comment by luz-alphacode** [comment]
@anion155 Totally agreed. About symbol and other stuffs, they works well, just a bit confusing if you check with the document. And by the way, a getTimesWithTangent(tangent) for **Curve** class is updated lately and is missing in the definition file. Maybe you can add it as well.
```typescript
/**
 * Calculates the curve-time parameters where the curve is tangential to provided tangent. Note that tangents at the start or end are included.
 * @param tangent - the tangent to which the curve must be tangential
 * @returns at most two curve-time parameters, where the curve is tangential to the given tangent
 */
  getTimesWithTangent(tangent: Point): number[];
```

**Comment by luz-alphacode** [comment]
@rfried Oh, that's a hard work! It's true that the paper.js documentation sometimes mismatch the actual code implementation. Months ago I've tried find a way to balance this but I gave up at last, now I know the reason why they are different. It's a really excellent work because once I get to know the differences, it's quiet easy to use. Thank you for what you've done for this.
Sometimes the design pattern of a js library and a ts library is so different, making a completely typescript-comforting definition file is just impossible.

**Comment by rfried** [comment]
@luz-alphacode 
Thanks :) I'm not going to claim I got it all right (see my questionable use of the code SymbolItem instead of the documented PlacedSymbol) and I'm glad to see more nuance added to the definition for sure. I feel like much of the cases, such as always using a Color, are mitigated by the fact that the constructors are pretty flexible. For instance, Color's constructor takes a css string. In the end the code for setting a color is more verbose than color = 'red' but isn't terrible as color = Color('red'). That said it's a neat use of get and set as a possible improvement to that flow.

My biggest disappointment was the inability to create operator overloading.
    Point p;
    p.add(new Point(100, 100))
is less clean than the paperscript version:
     p+Point(100, 100)

The code is also pretty fluid in mixing classes and types too (which is some code-trickery that was pretty hard for me to follow in the original source).
    var point = new Point(5, 10);
    var result = point + 20; <--- this is nice and how could it be represented nicely in Typescript?
    console.log(result); // {x: 25, y: 30}

There are a lot of union types in the definition as a result of this :-p

**Comment by luz-alphacode** [comment]
@rfried The typescript team claimed that they will not implement operator overloading since the typescript should keep consistency to javascript. I'm quite disagree with that, anyway, typescript is not runtime, why not add more sugars. Hoping one day they will change their mind.

**Comment by anion155** [comment]
@rfried about Style. It is a class. All fields in it always presents. To do the update some props of it's, like `this.style = { prop: value }` in TS, it has to be `this.setStyle({ prop: value })`. The way you did is not TS way of doing things.

**Comment by rfried** [comment]
@anion155 
The library under the typescript is super flexible and opting into typescript adds constraints. It's debatable how restricted this library should be to conform to "the TS way". Maybe Styles should have been an interface instead. 

The problem is that if you create a Style and set that style on another object then you have to make sure all the fields in the class are the way they should be. It's easy in the case where you take a style and modify a field and set it again. It's hard when you set a style from scratch and it breaks the ease-of-use that I was reading from the library's flexibility.

**Comment by anion155** [comment]
@rfried There is no `set a style from scratch` in paper's objects. Almost every setter is updater. For style it is `setStyle(style) { this._style.set(style); }`, same for property descriptor `style`. Function `set` in paper's object only updates internal fields.

**Comment by rfried** [comment]
@anion155 
I missed your use of Partial<Style> on the set. This does make the interface nicer as you said and allows for partial sets in the API `this.setStyle({ prop: value })` . 

can I still do this?
```
let gTextStyle: paper.Style = {
  fontFamily: "sans-serif",
  justification: "center",
  strokeColor: 'red',
  fillColor: 'green'
} as paper.Style;
```

**Comment by anion155** [comment]
@rfried It will work. But your `gTextStyle` will not be `paper.Style` instance. For this case, you will probably need `new paper.Style({ fontFamily: '' })` or `gTextStyle: Partial<Style> = {}` if you do not want to store it like style instance. I'm going to do some more changes, like making some interfaces instead things like `Partial<Style>`. But a bit later

**Comment by rfried** [comment]
@anion155 
nice, thanks

**Pull request merged**
