### PR TITLE
Add types for @architect/sandbox

### PR DESCRIPTION
**Pull request by reconbot**
Library can be found here https://github.com/architect/sandbox

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## architect__sandbox ([<kbd>unpkg</kbd>](https://unpkg.com/browse/architect__sandbox@latest/))
was missing the following properties:
1. cli
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e1b248feb1dcf0c63d1bb5bae6d27b0c69aea621
</p>

**Comment by ryanblock** [comment]
@reconbot @activescott this looks good to me, I think we may have some more options to pass now. On my phone atm but did we get everything?

**Comment by activescott** [comment]
I only use `await sandbox.start()` and `await sandbox.end()` myself, and I see those are as I expected.

You might consider dropping the callbacks and just expecting everyone to use the promise API – pretty standard and well known these days.

Minor, but it does look like danger found that `cli` is missing but it can always be added later. You might consider just adding a type alias for it as any for now. [I did something similar in functions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/architect__functions/index.d.ts#L14).

Generally lgtm

**Review by activescott — APPROVED** [review]

**Comment by ryanblock** [comment]
@reconbot good news, the docs were (for once) pretty up to date. Only one option was missing: `symlink` (boolean), see: https://github.com/architect/sandbox/#api

**Comment by ryanblock** [comment]
Also, `cli` is indeed an internal interface, best to leave it out!

**Review by amcasey — APPROVED** [review]

**Comment by activescott** [comment]
@reconbot Don't forget to tell the other bot "Ready to merge" :)

**Pull request merged**
