### PR TITLE
[make-fetch-happen] Add `cause` argument to `onRetry`

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Related discussion: #62221

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/npm/make-fetch-happen/tree/dcdb10008050ad4fdc5fc39e71b5b8c9241f0d35#opts-onretry>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## make-fetch-happen ([<kbd>unpkg</kbd>](https://unpkg.com/browse/make-fetch-happen@latest/))
was missing the following properties:
1. FetchError
1. Headers
1. Request
1. Response
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 09b26c291f256997e90cdc1987f22be7cbab9da6
</p>

**Comment by trevor-scheer** [comment]
For posterity, it's worth noting that `onRetry` can be called with a `Response` object
https://github.com/npm/make-fetch-happen/blob/main/lib/remote.js#L82-L84

...as well as various errors (including one special case error which has a `retried` property on it) or whatever may have been thrown / caught.
https://github.com/npm/make-fetch-happen/blob/main/lib/remote.js#L91-L107

`unknown | Response` seems correct to me on the basis that this is a caught error or `Response` object (and `unknown | Response` is just `unknown`).

**Review by trevor-scheer — APPROVED** [review]
Looks good, thank you for submitting this!

**Comment by MysteryBlokHed** [comment]
Ready to merge

**Pull request merged**
