### PR TITLE
[@xstyled/system] Add alias "bg" and correct "StyleFunc" interface.

### PR DESCRIPTION
**Pull request by alexojegu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Add alias "bg" to "backgroundColor": https://github.com/smooth-code/xstyled/releases/tag/v1.17.0
Correct the "StyleFunc" interface: https://github.com/smooth-code/xstyled/blob/master/packages/system/src/style.js#L88-L95

### CODE REVIEW

**Comment by stevejay** [comment]
@opotonil Thanks for the PR! An error I can see in the failing CI tests is that the package version in the definitions file includes the patch version, which is not permitted by the build checks: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2

🏄 You should also add yourself to the 'Definitions by' section of the definitions file ;)

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## xstyled__system ([<kbd>unpkg</kbd>](https://unpkg.com/browse/xstyled__system@latest/))
was missing the following properties:
1. createStyleGenerator
1. fontStyle
1. getBreakpoints
1. reduceBreakpoints
1. themeGetter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4499a76ea792a2176a1fd2af5f38f424c5375c65
</p>

**Comment by opotonil** [comment]
@stevejay excuse me by the noise.

> You should also add yourself to the 'Definitions by' section of the definitions file ;)

I think I have few experience with Typescript to approve PRs. (And surely I will to rename my GH account to use a username based in my real name).

The missing properties:
 - createStyleGenerator
 - getBreakpoints
 - reduceBreakpoints
 - themeGetter

They seem undocumented and for internal use of the library. I will try to study they better and, if I get to understand they, I will do another PR (As I said I have few experience with Typescript).

**Review by stevejay — APPROVED** [review]
LGTM. Thanks for the work on this 👍

**Comment by stevejay** [comment]
Ready to merge

**Comment by opotonil** [comment]
Ready to merge

**Pull request merged**
