### PR TITLE
 chart.js -- both X and Y axes can have time-related options

### PR DESCRIPTION
**Pull request by dvorakroth**

### CODE REVIEW

**Comment by guillaume-ro-fr** [comment]
Hi @dvorakroth 

I don't find either in the [doc](http://www.chartjs.org/docs/latest/axes/cartesian/time.html), either in the [source code example](https://github.com/chartjs/Chart.js/search?utf8=%E2%9C%93&q=time) a line with a time Y axe.

Are you sure it is a working solution ? 😄

**Comment by dvorakroth** [comment]
I’ll double check tomorrow at work if the actual setting works, but I can
confirm that using Date objects for the y axis is indeed possible and works
as expected

**Comment by minestarks** [comment]
@dvorakroth Could you please address the merge conflict? Thanks.

**Comment by dvorakroth** [comment]
OK I tried using GitHub's merge UI for the first time ever so there's a 99% chance I did everything wrong, but the conflict seems to be resolved 😅

**Pull request merged**
