### PR TITLE
[mui-datatables] Update to MUI v5 / mui-datatables v4

### PR DESCRIPTION
**Pull request by SamLeatherdale**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [mui-datatables v4 release](https://github.com/gregnb/mui-datatables/releases/tag/4.0.0)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by favna — APPROVED** [review]
LGTM and nice work! You'll have to fix CI though, you can check the run result for what you have to do: https://github.com/DefinitelyTyped/DefinitelyTyped/runs/7863613314?check_suite_focus=true

**Comment by SamLeatherdale** [comment]
Thanks for the fast turnaround @favna 😀
I've raised a PR in the tools repo to fix the CI error, so waiting on that one to get approved and merged.

**Comment by SamLeatherdale** [comment]
@favna I genuinely don't know how to fix the build now. 
It seems like the upstream types from MUI have type errors which is causing this build to fail. 
Perhaps I will need to fix the types in MUI first before we can get this merged.

**Comment by favna** [comment]
Gee this is definitely on MUI's side yes and I have a feeling specifically related to this change in TS 4.8: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-rc/#improved-intersection-reduction-union-compatibility-and-narrowing

**Pull request closed without merging**
