### PR TITLE
[express-list-endpoints] Version bump: Add middlewares

### PR DESCRIPTION
**Pull request by joshuaharry**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
See https://github.com/AlbertoFdzM/express-list-endpoints/blame/develop/README.md#L34

### CODE REVIEW

**Review by sjoseph7 — COMMENTED** [review]
The tests.ts file looks fine.

**Review by sjoseph7 — CHANGES_REQUESTED** [review]
Please update the usage comment in the index.d.ts file.
```
import * as express from "express";
import listEndpoints from "express-list-endpoints";

const app = express();

app.route('/')
  .all(function namedMiddleware(req, res) {
    // Handle request
  })
  .get(function(req, res) {
    // Handle request
  })
  .post(function(req, res) {
    // Handle request
  });

app.route('/about')
  .get(function(req, res) {
    // Handle request
  });

console.log(listEndpoints(app));

/* It omits the 'all' verbs.
[{
    path: '/',
    methods: ['GET', 'POST'],
    middlewares: ['namedMiddleware', 'anonymous', 'anonymous']
  },
  {
    path: '/about',
    methods: ['GET'],
    middlewares: ['anonymous']
}]
*/
```

**Review by sjoseph7 — APPROVED** [review]

**Comment by joshuaharry** [comment]
Ready to merge

**Comment by sjoseph7** [comment]
@joshuaharry did you mean to leave your name off of the `Definitions by:` list?

**Pull request merged**
