### PR TITLE
[node] Added `globalThis` support to `global`

### PR DESCRIPTION
**Pull request by JasonHK**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://node.green/#ES2020-features-globalThis>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by armanio123** [comment]
@jkomyno, @a-tarasyuk, @alvis, @r3nya, @btoueg, @brunoscheufler, @smac89, @tellnes, @touffy, @DeividasBakanas, @eyqs, @Flarna, @Hannes-Magnusson-CK, @KSXGitHub, @hoo29, @kjin, @ajafff, @islishude, @mwiktorczyk, @mohsen1, @n-e, @octo-sniffle, @galkin, @parambirs, @eps1lon, @SimonSchick, @ThomasdenH, @WilcoBakker, @wwwy3y3, @samuela, @kuehlein, @j-oliveras, @bhongy, @chyzwar, @trivikr, @nguymin4, @yoursunny, @qwelias, @ExE-Boss, @Ryan-Willpower, @peterblazejewicz, @JasonHK 

I appreciate if any of you owners could take a look at this PR.

**Comment by JasonHK** [comment]
> @jkomyno, @a-tarasyuk, @alvis, @r3nya, @btoueg, @brunoscheufler, @smac89, @tellnes, @touffy, @DeividasBakanas, @eyqs, @Flarna, @Hannes-Magnusson-CK, @KSXGitHub, @hoo29, @kjin, @ajafff, @islishude, @mwiktorczyk, @mohsen1, @n-e, @octo-sniffle, @galkin, @parambirs, @eps1lon, @SimonSchick, @ThomasdenH, @WilcoBakker, @wwwy3y3, @samuela, @kuehlein, @j-oliveras, @bhongy, @chyzwar, @trivikr, @nguymin4, @yoursunny, @qwelias, @ExE-Boss, @Ryan-Willpower, @peterblazejewicz, @JasonHK 
> 
> I appreciate if any of you owners could take a look at this PR.

Actually I'm not the code owner (yet).

**Comment by peterblazejewicz** [comment]
Not my level yet, sadly! As the topic is recurring, I think someone probably would be better suited (sorry mate(s) for pointing with finger):
/cc @ExE-Boss 
previously subject of: #43308

**Comment by JasonHK** [comment]
> Not my level yet, sadly! As the topic is recurring, I think someone probably would be better suited (sorry mate(s) for pointing with finger):
> /cc @ExE-Boss 
> previously subject of: #43308

@peterblazejewicz That PR was made by me as well, that PR was closed automatically since I don't have time to resolve the conflict before.

**Comment by JasonHK** [comment]
> Not my level yet, sadly! As the topic is recurring, I think someone probably would be better suited (sorry mate(s) for pointing with finger):
> /cc @ExE-Boss 
> previously subject of: #43308

@peterblazejewicz How can I improve this PR to the level of quality you expect?

In my opinion, this is the minimum changes required to bring `globalThis` support to `global`.

I know some properties in `NodeJS.Global` that will be duplicated after this PR, but I think we could fix them later, since these won't cause any errors in the mean time.

And I also have a package that were benefited from this PR, since `global as unknown as NodeJS.Global | typeof globalThis` shouldn't be the way to solve this problem.

**Comment by peterblazejewicz** [comment]
@JasonHK
sorry if you felt that way, your PR is 100% correct 👍 . My intent was to remark the one-of-the latest dicussion on same topic, due to nature of the package.

Please rebase your branch from the current master and resubmit, then redo the PR. There is a lot of topics going around NodeJS at the ment on the repo, with a lot of concerns related to changes, that could somehow impact existing user base. So just be prepared for discussion. I understand the change, due to short time of being involved directly into the Node dt package, I would probably not have an opinion on the change itself :)
Thanks!

**Comment by JasonHK** [comment]
> @JasonHK
> sorry if you felt that way, your PR is 100% correct +1 . My intent was to remark the one-of-the latest dicussion on same topic, due to nature of the package.
> 
> Please rebase your branch from the current master and resubmit, then redo the PR. There is a lot of topics going around NodeJS at the ment on the repo, with a lot of concerns related to changes, that could somehow impact existing user base. So just be prepared for discussion. I understand the change, due to short time of being involved directly into the Node dt package, I would probably not have an opinion on the change itself :)
> Thanks!

@peterblazejewicz I'm already prepared for discussion, but it seems that they don't want to discuss with me...

The only "discussion" is within the first PR (#43308), one of the owners, he asked me is it worth to add `globalThis` support to the definition, I explained to him, then I never heard anything back.

Same as the reviewer, he said he need motivation for it, I told him why this is important, then I also never heard anything back.

After that, none of them comment to my PRs (except you), including the current PR (#44700).

**Pull request closed without merging**
