### PR TITLE
add default export so it can be used with es6 modules

### PR DESCRIPTION
**Pull request by brcarey**

### CODE REVIEW

**Comment by vvakame** [comment]
this change is incorrect.
https://github.com/MikeMcl/big.js/blob/master/big.js#L1136
big.js is not support `default` export.

**Comment by brcarey** [comment]
hmm good point. How did the tests pass? Its also working for me via
babel/ts-loader

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/big.js/big.js-tests.ts
big.js-tests.ts does not contains `import`.
you can use `import * as big from "big.js";` instead of `import big from "big.js"`.

**Comment by brcarey** [comment]
"import * as..." was not working for me, hence the PR. Let me give it
another crack and get back to you

**Comment by nycdotnet** [comment]
Greetings.  The issue you're encountering is likely due to how TypeScript 1.5 through 1.7 handled "default" exports for ES5-style modules.  If you use TypeScript 1.8, you should be able to use the default-style ES6 import syntax with an `export=` definition.  If your TypeScript target setting is `system`, this will work by default.  If not, you have to enable the new synthetic default export feature with a switch: https://github.com/Microsoft/TypeScript/pull/5577

I don't believe we need to merge this, but I do greatly appreciate your contribution.  Thank you so much, and please let me know if this information resolves your issue.

@vvakame does that make sense?

**Pull request closed without merging**
