### PR TITLE
add types for google.accounts (Google Identity Services js SDK)

### PR DESCRIPTION
**Pull request by PartyLich**
type definitions for the Google Identity Services js SDK

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
Note - not created with dts-gen because of issues not addressed in the current release. See [issue 174 and others](https://github.com/microsoft/dts-gen/pull/174#issuecomment-1024930978)
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@PartyLich thx!

**Comment by PartyLich** [comment]
Ready to merge
⁣

On Apr 11, 2022, 13:39, at 13:39, TypeScript Bot ***@***.***> wrote:
***@***.***: Everything looks good here. I am ready to merge this PR (at
>7b408c7) on your behalf whenever you think it's ready.
>
>If you'd like that to happen, please post a comment saying:
>
>> Ready to merge
>
>and I'll merge this PR almost instantly. Thanks for helping out!
>:heart:
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59630#issuecomment-1095417188
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by coderpradp** [comment]
@PartyLich Hi, I am using @types/google.accounts in angular 11. While building the app I am getting these errors:
```
Error: src/providers/google-identity.service.ts:17:26 - error TS2694: Namespace 'google' has no exported member 'accounts'.
17   private client: google.accounts.oauth2.CodeClient;
                            ~~~~~~~~
src/providers/google-identity.service.ts:49:26 - error TS2339: Property 'accounts' does not exist on type 'typeof google'.
49     this.client = google.accounts.oauth2.initCodeClient({
                            ~~~~~~~~
```
I added `types: ["google.accounts"]` to `tsconfig.json` however issue still persist. Do you have any solution to this?

**Comment by PartyLich** [comment]
> @PartyLich Hi, I am using @types/google.accounts in angular 11. While building the app I am getting these errors:
> 
> ```
> Error: src/providers/google-identity.service.ts:17:26 - error TS2694: Namespace 'google' has no exported member 'accounts'.
> 17   private client: google.accounts.oauth2.CodeClient;
>                             ~~~~~~~~
> src/providers/google-identity.service.ts:49:26 - error TS2339: Property 'accounts' does not exist on type 'typeof google'.
> 49     this.client = google.accounts.oauth2.initCodeClient({
>                             ~~~~~~~~
> ```
> 
> I added `types: ["google.accounts"]` to `tsconfig.json` however issue still persist. Do you have any solution to this?

I dont think this pull request is the right place for your question, and I'm fairly sure it is not an issue with the typings (they work without issue in a live react/nextjs project, for example). 

I'm not an Angular user, but in an attempt to reproduce your issue i

1. set up a basic project with the cli
2. installed the typings
3. added a field of the CodeClient type to the AppComponent class

That was enough to produce a comparable compilation error. The fix is in the [the Angular docs, specifically this page](https://angular.io/guide/typescript-configuration#installable-typings-files).
> After installing `@types/*` declarations, you have to update the **`tsconfig.app.json`** 

Updating the specified file cleared the compilation error. Note that this is **not** `tsconfig.json`, the file you noted in your comment. Adding the exact same type filed to that config file did not resolve the error in my reproduction. You may have to consult an Angular user/expert for an elaboration of why the two separate config files have the behavior noted.

**Comment by peterblazejewicz** [comment]
@coderpradp please use:
```ts
/// <reference types="google.accounts" />
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class GoogleIdentityService {
  initCodeClient(): void {
    google.accounts.oauth2.initCodeClient({
 ```

**Pull request merged**
