### PR TITLE
Feature/validator/is iso6391

### PR DESCRIPTION
**Pull request by TheMly**
Hello all,

I'm opening this PR to include a missing isISO6391 function declaration exported from [isISO6391.](https://github.com/validatorjs/validator.js/blob/master/src/lib/isISO6391.js#L32)
I'm using the same structure as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62743.
Thanks!

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/validatorjs/validator.js/blob/master/src/lib/isISO6391.js#L32>>

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@TheMly everything is great, except, you are supposed to bump the package version number, as it was released in 13.9 IMO:
https://github.com/validatorjs/validator.js/pull/2166
(as per PR checklist)

**Comment by TheMly** [comment]
> @TheMly everything is great, except, you are supposed to bump the package version number, as it was released in 13.9 IMO: [validatorjs/validator.js#2166](https://github.com/validatorjs/validator.js/pull/2166) (as per PR checklist)



> @TheMly everything is great, except, you are supposed to bump the package version number, as it was released in 13.9 IMO: [validatorjs/validator.js#2166](https://github.com/validatorjs/validator.js/pull/2166) (as per PR checklist)

Hello @peterblazejewicz. You're right, I missed the package version bump. Already updated it, thanks for the suggestion.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@TheMly thanks!

**Comment by TheMly** [comment]
Ready to merge

**Pull request merged**
