### PR TITLE
[react-native] Delete: PickerItem class

### PR DESCRIPTION
**Pull request by nnnnnoel**
when we using Picker and Picker.Item, the type 'PickerItem' can imported our project. so I removed that and Fix Picker.Item type to React.Component<PickerItemProps>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by alloy — CHANGES_REQUESTED** [review]
Please provide a link to the docs/source that show what this should look like, as requested in the PR template. It would also be good to add some test coverage.

**Comment by zusinShinpei** [comment]
@alloy 
https://github.com/facebook/react-native/blob/master/Libraries/Components/Picker/Picker.js
static Item is Picker.Item. not PickerItem

**Review by alloy — APPROVED** [review]

**Comment by alloy** [comment]
I see. Thanks and apologies for the wait (was out for vacation) 👍

**Comment by vovkasm** [comment]
@alloy, @zusinShinpei  Now we have an error in simple code:
```typescript
import React from 'react';
import {Picker} from 'react-native';

export const Dropdown: React.FC = () => (
  <Picker>
    <Picker.Item key="a" label="a" value="a" />
  </Picker>
);
```

Error

Additional info:
- typescript@3.7.5
- @types/react@16.9.19
- @types/react-native@0.61.7

What to do? )

**Comment by zusinShinpei** [comment]
> @alloy, @zusinShinpei Now we have an error in simple code:
> 
> ```ts
> import React from 'react';
> import {Picker} from 'react-native';
> 
> export const Dropdown: React.FC = () => (
>   <Picker>
>     <Picker.Item key="a" label="a" value="a" />
>   </Picker>
> );
> ```
> 
> Error
> 
> Additional info:
> 
> * typescript@3.7.5
> * @types/react@16.9.19
> * @types/react-native@0.61.7
> 
> What to do? )

Fixed #41937

**Pull request merged**
