### PR TITLE
Modified IPromise.done definition

### PR DESCRIPTION
**Pull request by dgzornoza**
Set nullable in IPromise.done definition for compatibility with WinRT Windows.Foundation.IPromise

### CODE REVIEW

**Comment by vvakame** [comment]
@basarat could you review this PR? winrt is a huge definitions. I can't handling it...

**Comment by basarat** [comment]
> Set nullable in IPromise.done definition for compatibility with WinRT Windows.Foundation.IPromise

@dgzornoza So basically what you are trying to say is that make this definition's done optional `done?` because `Windows.Foundation.IPromise` doesn't have a `done` member and prevents you *cross assigning promises*?

**Comment by dgzornoza** [comment]
Yes, in WinRT all asynchronous functions inherited from Windows.Foundation.IPromise <T> and according to microsoft is equal to WinJS.IPromise <T>.
In addition, the function done not have to be used, for example in a method invocation does not expect response.

**Comment by basarat** [comment]
> in WinRT all asynchronous functions inherited from Windows.Foundation.IPromise and according to microsoft is equal to WinJS.IPromise

i.e. `Windows.Foundation.IPromise extends WinJS.IPromise`. The winjs promise *always* has a done method (https://msdn.microsoft.com/en-us/library/windows/apps/br211867.aspx). I don't see why you want to make it optional. Can you provide a code sample that fails to compile that you think *should* compile (or something that *shouldn't compile* but *does compile*).

**Comment by dgzornoza** [comment]
hello @basarat, yes the winjs promise always has a done method, the problem is convert promises, example:
'''javascript
var folder: WinJS.IPromise<Windows.Storage.IStorageFolder> = _storageFolder.getFolderAsync("path");
'''
the error is: 
**Error 1029**
Can not convert 'Windows.Foundation.IAsyncOperation <Windows.Storage.StorageFolder>' in 'WinJS.IPromise <Windows.Storage.IStorageFolder>':
The property 'done' has been defined as optional in type 'Windows.Foundation.IPromise <T>',
but it is necessary in the type 'WinJS.IPromise <T>'.

WinRT currently contains this promise:

'''javascript
     export interface iPromise <T> {
         ...

         done? <U> (success ?: (value: T) => any, mistake ?: (error: any) => any, progress ?: (progress: any) => void): void;

         ...
     }
'''

so that it is incompatible with WinJS.

I've been looking other definitions in typescript containing promises and seen that all have **done** method obligated.
it is possible that the best option may be to change the WinRT promise to eliminate nullable.

What look better option?

**Comment by basarat** [comment]
> it is possible that the best option may be to change the WinRT promise to eliminate nullable.

Yes. That would be great. E.g. the example you give `getFolderAsync` has `done` in the sample : https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.storagefolder.getfolderasync

Please open a new PR and @basarat mention me. Thanks!

**Pull request closed without merging**
