### PR TITLE
export all interfaces/types from index

### PR DESCRIPTION
**Pull request by kylemh**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by kylemh** [comment]
This let's me import everything from one path and gets intellisense working properly!

**Review by nhardy — APPROVED** [review]
LGTM

**Comment by kylemh** [comment]
Ready to merge

**Comment by kylemh** [comment]
🙃

**Comment by kylemh** [comment]
Ready to merge

**Comment by kylemh** [comment]
Ready to merge

**Pull request merged**
