### PR TITLE
@types/chart.js labelColor is now an array of ChartTooltipLabelColors, closes #53517

### LINKED ISSUE #53517: @types/chart.js. Property 'borderColor' does not exist on type 'string'
Hi there!
I use Chart.js 2.9.4 and @types/chart.js 2.9.32 with React and TS.
I created a custom function for the tooltip. Tooltip model has ChartTooltipModel type, but labelColors has type string[] when actually it is an array of ChartTooltipLabelColor objects.
Maybe I use the wrong type of declarations?

### PR DESCRIPTION
**Pull request by samarmohan**
Please fill in this template.

closes #53517

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53517
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by samarmohan** [comment]
Uhh, how should I test this?

**Comment by danmana** [comment]
@samarmohan probaly the simplest way to test this is to add a section to `chart.js-tests.ts` similar to the existing one for `custom tooltips` :
```ts
// custom tooltips labelColors
const customTooltipsPieChart = new Chart(ctx, {
    type: 'pie',
    data: {},
    options: {
        tooltips: {
            enabled: false,
            custom: (tooltipModel) => {
                const firstColor = tooltipModel.labelColors[0];
                console.log(firstColor.borderColor);
                console.log(firstColor.backgroundColor);
            },
        },
    },
});

```

Note: that the tests do not actually check that the code runs ok, just that the typing is correct.

**Comment by samarmohan** [comment]
Thank you so much! I’ll get right to it.

**Review by lekoaf — APPROVED** [review]

**Review by lekoaf — APPROVED** [review]

**Comment by samarmohan** [comment]
Ready to merge

**Pull request merged**
