### PR TITLE
ci: update dangerJS

### PR DESCRIPTION
**Pull request by snitin315**
- For testing purposes only 
- https://github.com/danger/danger-js/issues/1347

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Test warning</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6380089847c34e08287d04b8c4406301aa62c419
</p>

**Comment by DangerBotOSS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Test warning</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6380089847c34e08287d04b8c4406301aa62c419
</p>

**Comment by DangerBotOSS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Test warning</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6380089847c34e08287d04b8c4406301aa62c419
</p>

**Comment by peterblazejewicz** [comment]
@snitin315 can we close it now, as it appear to work? (bot prints msg)

**Comment by snitin315** [comment]
Yes we can close it.

**Pull request closed without merging**
