### PR TITLE
Add shim function to typings for promise.prototype.finally

### PR DESCRIPTION
**Pull request by fiznool**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://stackoverflow.com/a/41146392/1171775
- [x] Increase the version number in the header if appropriate.

Add shim function to typings for promise.prototype.finally so that it can be used in a TypeScript project.

### CODE REVIEW

**Comment by slavik57** [comment]
@fiznool add a test to the file `promise.prototype.finally-tests.ts` that will use the function to see it compiles

**Comment by slavik57** [comment]
👎

**Comment by fiznool** [comment]
@slavik57 that's done.

**Comment by slavik57** [comment]
👍

**Review by slavik57 — APPROVED** [review]

**Review by slavik57 — APPROVED** [review]

**Comment by vvakame** [comment]
sorry for late response.
could you try to use this code style? 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13537/commits/e65a905435a077dfed670b714af13d5d6d3ba779

**Comment by andy-ms** [comment]
Like @vvakame said, this would be better as:
```ts
declare global {
    interface Promise<T> {
        finally<U>(onFinally?: () => U | Promise<U>): Promise<U>;
    }
}

export function shim(): void;
```

**Comment by fiznool** [comment]
@andy-ms thanks, I've updated that coding style.

@slavik57 I added a further commit which fixes an issue I had with TypeScript 2.1, you may want to review this change? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13339/commits/e565c116b8829a39997763c1b8d50ef38672c2c2

**Comment by slavik57** [comment]
@finzool the change is wrong, you can return any promise, not only promise of the same type.
This should work but after your change it will not work.

let stringPromise: Promise<string>;
let numberPromise: Promise<number>;
stringPromise.finally(()=>numberPromise);

**Comment by fiznool** [comment]
I was taking this from the bluebird implementation:
http://bluebirdjs.com/docs/api/finally.html

> If the handler function passed to .finally returns a promise, the promise
returned by .finally will not be settled until the promise returned by the
handler is settled. If the handler fulfills its promise, the returned
promise will be fulfilled or rejected with the original value. If the
handler rejects its promise, the returned promise will be rejected with the
handler's value.

According to this, if .finally returns a promise, this causes the outer
promise to wait until it has resolved. The outer promise is either then:
resolved with the original value, or rejected with the exception thrown in
the .finally block.

>

**Comment by slavik57** [comment]
@fiznool it is a d.ts for the 'promise.prototype.finally' library. You can see in the link below in the example the promise can be changed. If you wish to support the bluebird finally I think you should update it in the bluebird d.ts

https://www.npmjs.com/package/promise.prototype.finally

**Comment by fiznool** [comment]
Are you referring to this code block from the example?

```
var assert = require('assert');
var promiseFinally = require('promise.prototype.finally');
 
var resolved = Promise.resolve(42);
var rejected = Promise.reject(-1);
 
promiseFinally(resolved, function () {
    assert.equal(arguments.length, 0);
 
    return Promise.resolve(true);
}).then(function (x) {
    assert.equal(x, 42);
});
```

If so, I think this shows that the value from the original promise should be passed through. Notice that the finally block is returning a promise resolved with `true`, but the resulting `then` block receives the originally resolved value `42`.

**Comment by slavik57** [comment]
@fiznool OK yeah you are right...

**Pull request merged**
