### PR TITLE
feat(json-schema): add types for draft 07

### PR DESCRIPTION
**Pull request by rolandjitsu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [JSON Schema Draft 07](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by cyrilletuzi — CHANGES_REQUESTED** [review]
Thanks for your PR but is is unreadable as you changed the indentation setting. Please change this so we can see only what you added.

**Comment by rolandjitsu** [comment]
@cyrilletuzi sorry, I'll change that tomorrow and update the PR 😄

**Comment by andy-ms** [comment]
You can view https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27493/files?w=1 to see the non-whitespace changes.

**Review by cyrilletuzi — CHANGES_REQUESTED** [review]
All is fine except a missing new optional `$comment` string field that has been added, could you add it? http://json-schema.org/draft-07/json-schema-core.html#rfc.section.9

**Review by cyrilletuzi — APPROVED** [review]
LGTM

**Review by cyrilletuzi — APPROVED** [review]
LGTM

**Pull request merged**
