### PR TITLE
[styled-components] Move React Native-dependent types to separate package

### LINKED ISSUE #33015: [@types/styled-components] Dependency in @types/styled-components on @types/react-native causes issues with projects who depend on @types/node
This should be a peerDependency...

### LINKED ISSUE #33311: node_modules/@types/react-native/globals.d.ts (36,15): Duplicate identifier 'FormData'.
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components` package and had problems because since of v.4.1.9 another [conflicted dependency](https://user-images.githubusercontent.com/8643060/53185025-d6070a00-3606-11e9-9fc9-1e61afc1f2cf.png) was added (@types/react-native) and conflicts with @types/node . See [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5dd798b9aa417f01db598fbded1a83a8a857eb39)

- [x] I tried using the latest stable version(3.3.3333) of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkillian @Igorbek @Igmat @lavoaster @Jessidhia @eps1lon @flavordaaave
### how to reproduce:
* Fresh install react app by command
  `yarn create react-app my-app-ts --scripts-version=react-scripts-ts`
* add styled components
  `yarn add styled-components`
  `yarn add -D @types/styled-components`
* import ThemeProvider to src/index.tsx and wrap  to

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import {ThemeProvider} from "styled-components";
import App from './App';
import './index.css';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(
    <ThemeProvider theme={{}}>
        <App />
    </ThemeProvider>,
  document.getElementById('root') as HTMLElement
);
registerServiceWorker();
```

* run build command:
  `yarn start`
* Expected result:
  See the react app
* Current result:

image

There is a lot of fails according to many definitions conflicts with lib.dom
image

### PR DESCRIPTION
**Pull request by Methuselah96**
Resolves https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33311
Resolves https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

### The problem

Both of the above issues have been open for over a year and a half and the first one has more up-votes than any other issue on DefinitelyTyped. The current solution on these issues is to set the `types: []` in `tsconfig.json` to pull in the appropriate types, which means `@types/styled-components` doesn't work out-of-the-box unlike most other `@types` packages. This harms not only the reputation of TypeScript, but also the reputation of `styled-components` and causes unnecessary friction in order to use these types.

### The solution

Move the `styled-components/native` types out of `@types/styled-components` and into its own package (`@types/styled-components-react-native`). If someone wants to use `styled-components/native`, all they need to do is install `@types/styled-components-react-native` and it will automatically augment the `styled-components` types (since TypeScript automatically includes any installed `@types` packages).

This makes it so that the main export (i.e., `import styled from 'styled-components'`) works out-of-the-box (which is the most common usage). And in order to get `styled-components/native` all you need to do is install the other `@types` package, which is still easier than having to set `types: []` in `tsconfig.json`.

Note: this is still just a temporary workaround, but it is still better than the current situation.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Methuselah96** [comment]
Build failing due to https://github.com/microsoft/TypeScript/issues/41790.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against aa7deb329790e30726a3fbf633001d9ecfb7cecf
</p>

**Comment by orta** [comment]
:wave: - I've done my digging. TLDR: **I think we should merge this**.

I have a sample repo with [before and after examples for both node and react native projects here](https://github.com/orta/styled-components-dt-split-tests) with the README being a summary of how they act out of the box.

What this PR proposes is that we remove the `native.d.ts` file from `@types/styled-components`, and move that into a new types module. This types module edits the global scope to declare that it has a definition for "styled-components/native` specifically, which adds the react-native types to the module. 

### Upsides

- Web works out of the box again. Currently only React Native projects get that.
- Does not need to wait for the TS team to figure out an answer for per-file environments (which is looking to be very hard)
- SC React Native types _could_ be maintained by a different set of folks, doesn't really seem too valuable in comparison to the above points though.

### Downsides

- React Native projects need to `yarn add @types/styled-components-react-native` to get types
- React Native projects using JS do not get ATA anymore

A React Native project which does not have `@types/styled-components-react-native` installed gets this: 

    styled-components-types-tests/proposed_rn on  main [✘!?] is 📦 v1.0.0 via ⬢ v14.15.1 
    ❯ yarn compile
    yarn run v1.22.10
    $ ../node_modules/.bin/tsc --noEmit
    index.tsx:3:20 - error TS7016: Could not find a declaration file for module 'styled-components/native'. '/home/orta/dev/typescript/styled-components-types-tests/proposed_rn/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.

### Trade-offs

IMO, I think these trade-offs can be mitigated by improving the Styled Components docs in [the TypeScript section](https://styled-components.com/docs/api#typescript). 

The docs can mention TS + RN specifically as needing this extra dep, and I think that should be reasonably harmless. Ideally a FAQ entry can be added around this error message: `Could not find a declaration file for module 'styled-components/native'` - which is just "install this dep" too  ( /cc @probablyup does that seem reasonable? )

I'm going to go ping a few threads asking for feedback on this PR as a solid potential solution. Then once more folks have given input we can make a call on whether to merge or not 👍🏻 - thanks for getting the ball rolling @Methuselah96

**Comment by murbanowicz** [comment]
This is more than needed.
It often requires workarounds to mitigate issues caused by the fact that Native parts are installed with web stuff.

**Review by eps1lon — APPROVED** [review]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914#issuecomment-745347981 summarizes this perfectly. @orta Thanks looking into the impact this change has :+1:

**Comment by jussikinnula** [comment]
This all looks good.

Just a question. Could we somehow include an error, if someone uses `@types/styled-components` in React Native project?

Basically there's `global.navigator.product` which returns `ReactNative` which could be used for this. I think it would ease up people upgrading to use `@types/styled-components-react-native` if they would get instructions sooner than to have to dig the information.

**Review by paulmelnikow — APPROVED** [review]
🙌🏼

**Comment by orta** [comment]
The error message comes specifically from the TypeScript compiler and are hard-coded. There isn't really a way to create custom type-level errors ( though https://github.com/microsoft/TypeScript/pull/40468 could probably work for this situation, so maybe show some support in that PR ) - so, I'm afraid documentation ahead of time is probably the only useful tool around someone knowing to use the extra lib.

**Review by alloy — APPROVED** [review]
Thanks so much for working on this. Hard yes from me 👍

**Comment by orta** [comment]
Alright, I'm going to rebase this and merge later on today - I've just shipped the docs changes to make it work

**Review by eps1lon — APPROVED** [review]

**Comment by orta** [comment]
Alright, we are good to go - thanks for the rebase @Methuselah96 !

**Comment by lukewlms** [comment]
I'm probably missing something simple but how do you actually use this?  I've tried a bunch of variations on installing the new Native types lib, the old one, only one of them, both of them, setting a path in tsconfig...

If I just install both of them then when I try to import `styled-components/native` I get:

`Could not find a declaration file for module 'styled-components/native'. 'node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.ts(7016)`

I'm just trying to make a `Styled.ScrollView` work, which worked before trying to migrate to the new types.

**Comment by lukewlms** [comment]
Ok, here's what seems to be working:

1. `yarn add --dev @types/styled-components @types/styled-components-react-native`
2. Add an explicit path in tsconfig to the new types:

```
    "baseUrl": ".",
    "paths": {
      "styled-components/native": [
        "node_modules/@types/styled-components-react-native"
      ]
    },
```

If this is the intended way it seems it would be worthwhile to document in the npm readme.

**Comment by Methuselah96** [comment]
Is it possible that you have the `types` property specified in your `tsconfig.json`? It should work automatically if you don't specify the `types` field. If you are specifying it, you should add `styled-components-react-native` to that array.

**Comment by lukewlms** [comment]
@Methuselah96 Thanks for the help - yes, we specify `types` for Jest.  If I add `styled-components-react-native` there, then it looks like I can remove it from Paths so either way to set up config works, but some special config is needed either way.

Seems worth putting in readme.md to me since I haven't run into this in other libs in a fair amount of experience, + using paths is common as far as I know (e.g. for Jest as we do).

**Comment by Methuselah96** [comment]
Apologies for the confusion. Feel free to make a PR to add documentation for this case to the [TypeScript section](https://styled-components.com/docs/api#typescript) on the styled-components website.

**Comment by lukewlms** [comment]
> Apologies for the confusion. It would be great if you could make a PR to add documentation for this case to the [TypeScript section](https://styled-components.com/docs/api#typescript) on the styled-components website. I think it's more common than not that people aren't specifying the `types` property in `tsconfig.json`, but I have no data to back that claim up.

No problem, thanks again for the help and I submitted a PR.

**Comment by ortonomy** [comment]
Thank you so much @lukewlms and @Methuselah96 -- without finding this issue, I would never have solved the problem of the types not being found.

**Comment by davisk4rpi** [comment]
It seems like  @types/styled-components to 5.1.7 has broken this fix. 

I have @types/styled-components-react-native installed as well and I cant seem to find any workarounds to get this to work other than setting "noImplicitAny" to false

**Comment by ortonomy** [comment]
@davisk4rpi - make sure you're not using any other definitions in 'typeSrc' or 'types' - if you are, it breaks.

**Comment by Methuselah96** [comment]
Just to clarify, you're allowed to have other definitions in `"types"`, just make sure that `"styled-components-react-native"` is one of them as shown in [the docs](https://styled-components.com/docs/api#typescript).

**Comment by ortonomy** [comment]
Yes. Sorry. I should have said if it's a not empty array you should added the types to the array.

**Comment by davisk4rpi** [comment]
@ortonomy  @Methuselah96  Thanks, That was it. didnt notice the types field in my config the first time through

**Pull request merged**
