### PR TITLE
added @types/JSONStream

### PR DESCRIPTION
**Pull request by SoulKa**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by SoulKa** [comment]
Anyone knows how to resolve the error:
`Error: Package name `JSONStream` should be strictly lowercase`

The original package that I made this type definitions for is written in upper letters. There is another package with the same name in lower letters, which is unfortunately deprecated and **not** the same as the package "JSONStream"

**Comment by SoulKa** [comment]
> @SoulKa I haven't seen any activity on this PR in more than three weeks, and it still has problems that prevent it from being merged. The PR will be closed in a week if the issues aren't addressed.

Hello little bot. The issues can only be resolved by a maintainer :)

**Comment by orta** [comment]
I don't think it is possible to have both `@types/jsonstream` and `@types/JSONStream` on npm anymore - the rules were changed (maybe specifically [for this module](https://blog.npmjs.org/post/168978377570/new-package-moniker-rules?_ga=2.192502570.1877573280.1608039054-1491691883.1608039054))

Same thing happened back a few years ago: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16049

The only way that they can get automatic types on that dependency now is to bundle it with the dep I'm afraid

**Comment by SoulKa** [comment]
> I don't think it is possible to have both `@types/jsonstream` and `@types/JSONStream` on npm anymore - the rules were changed (maybe specifically [for this module](https://blog.npmjs.org/post/168978377570/new-package-moniker-rules?_ga=2.192502570.1877573280.1608039054-1491691883.1608039054))
> 
> Same thing happened back a few years ago: #16049
> 
> The only way that they can get automatic types on that dependency now is to bundle it with the dep I'm afraid

Well that's sad. The git of JSONStream itself is readonly as well, which makes it also impossible to insert the type definitions there. Guess there's nothing I can do

**Comment by orta** [comment]
Yeah, sorry about that - shame, especially on a PR with solid  JSDoc work too

**Pull request closed without merging**
