### PR TITLE
Modify takePhoto method signature to take array of PhotoSettings 

### PR DESCRIPTION
**Pull request by alexkeating**
For issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50176.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/takePhoto
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hi @alexkeating ,
According to https://w3c.github.io/mediacapture-image/#imagecaptureapi, this is not an array.

Moreover, I still use the api frequently, passing a single PhotoSettings value works perfectly.
So I would say, MDN is wrong.

**Review by reda-alaoui — CHANGES_REQUESTED** [review]
This contradicts the specification.

**Comment by alexkeating** [comment]
Oh interesting, the reason this popped up for me is because I am getting an error on Chrome 87 with the below code. Once, I changed the options to an array everything began to work. If you have any thoughts about why I am getting this error I would love to hear them.

- Errorring Code
```
const y = v.srcObject as MediaStream;
if (y === null) {
    return;
}
const track = y.getVideoTracks()[0];
const imageCapture = new ImageCapture(track);
const z = await imageCapture.takePhoto({
    imageHeight: v.clientHeight,
    imageWidth: v.clientWidth
});
```
- Error message
Screen Shot 2020-12-19 at 4 55 37 PM

**Comment by reda-alaoui** [comment]
I think the options you pass are not supported by the targeted camera. You should first query for capabilities. Your options must be within range of the returned capabilities.

**Comment by alexkeating** [comment]
Thanks, when I change the width and height to be within the cameras min and max capabilities I no longer get the error. I am going to close this along with the issue and see if I can get MDN to reflect the spec.

**Pull request closed without merging**
