### PR TITLE
sharedb: context types now include a generic for the agent's type

### PR DESCRIPTION
**Pull request by sr258**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sharedb/lib/agent.d.ts)

While the Agent type is already a generic, this generic wasn't used in the context definitions. The change allows you to have a static type in the `context.agent.custom` property through a generic:

```ts
context: ShareDB.middleware.ConnectContext<{ user: { id: any } }>
```

will make `context.agent.custom` of the type `{user: {id: any} }`.

### CODE REVIEW

**Review by alecgibson — CHANGES_REQUESTED** [review]
Thanks for the Pull Request! Could you please avoid code style changes, as they make the change quite noisy, and it's harder to review the actual change you're trying to make.

**Review by alecgibson — COMMENTED** [review]
Thanks for tidying up the PR!

I've had a talk with @ericyhwang and we're apprehensive to make the contexts generic like this, just because the context is already quite a "nebulous" object. We may want to make other properties generic, and then having multiple type arguments can get quite noisy if you want to define some and not others. Adding this generic could tie our hands.

Could you please provide a bit more context about what exactly you're trying to achieve? Specifically:

 - What does your code look like now?
 - How would you like it to look?
 - Why can't this be solved using an `as` cast with the already generic `Agent`?
    ```ts
    const agent = context.agent as Agent<MyCustom>;
    ```
 - Why can't this be solved by reopening the TypeScript definitions in your own app, and just augmenting the contexts there?

**Comment by sr258** [comment]
My code more or less looks the same with the generics, but I get code completion and the IDE can spot spelling mistakes when I define the type context with the generic in TypeScript. I thought that adding the `Agent` generic might be useful for others, but I can certainly augment them for my app only.

Having multiple generis in a class isn't that unusual. The Express Request type for example has multiple generics and I think it's still ok to handle it.

**Comment by alecgibson** [comment]
@sr258 yes we did actually double-check `@types/express` as part of our conversation, so there is certainly precedent. As I say, we're mostly hesitant from just tying our hands for future type decisions, and this types packages has certainly [encouraged module reopening](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50754/files#diff-4536ba1547676ff5f79afd514d12cb4a925a11be595897a50ecdb73a84212569L60-L66) in the past.

If you reopen this module locally, you should be able to just modify `Agent` directly, without the need to touch all the context objects, which is potentially another argument for not making this change (I'd actually expect it's actually less work to do that than to specify type arguments everywhere?).

If you're happy to just solve this in your codebase, I think I'd move to close this PR, and if we get more interest in this, we can certainly revisit.

**Comment by sr258** [comment]
I can augment the types in my codebase as well, so I'm fine with that.

**Comment by alecgibson** [comment]
Okay I've had a quick play around with this and I think I agree, module augmentation for this doesn't seem to work. I guess it would be nice to tweak our module definition, but I'm not sure how to do that in a non-breaking way.

If this has you stuck, we can look into it again — we'll probably discuss on Tuesday.

**Pull request closed without merging**
