### PR TITLE
Create three-FirstPersonControls.d.ts

### PR DESCRIPTION
**Pull request by pksorensen**

### CODE REVIEW

**Comment by s093294** [comment]
Not ready yet - few errors to be fixed

**Comment by s093294** [comment]
Should be ready to include. 

One implementation is found here. https://github.com/potree/potree/blob/master/src/FirstPersonControls.js

**Comment by vvakame** [comment]
@gyohk could you review this PR?

**Comment by gyohk** [comment]
No problem.
Thank you for the modification.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
