### PR TITLE
redux - stricter typings

### PR DESCRIPTION
**Pull request by use-strict**

### CODE REVIEW

**Comment by use-strict** [comment]
@igorbt can you have a look?

**Comment by isman-usoh** [comment]
:+1:

**Comment by Igorbek** [comment]
:+1:

**Comment by aikoven** [comment]
See https://github.com/reactjs/redux/pull/1413

**Comment by use-strict** [comment]
@aikoven , I didn't know there was a definition being developed directly in the redux repo. I'm unsure what should happen now. Since there are other definitions that depend on this one we can't just delete it. On the other hand, maintaining two separate definitions (if we don't consider the third one from the typings/registry) is not something to be desired.

**Comment by aikoven** [comment]
@use-strict You are right, I'm also not sure how to deal with typings in DT that are dependent on Redux.
Maybe we should add a copy of official typings to DT. Or work on moving all dependent typings to their repos.

**Comment by use-strict** [comment]
@aikoven , is it OK if I start to comment inline on your definition on the closed PR or should I start a new one?

**Comment by aikoven** [comment]
@use-strict I think it's ok if you open a new PR, but please add a comment to original discussion with a link to it so that other folks don't miss it.

**Comment by use-strict** [comment]
@vvakame , @basarat , I opened another PR in the redux repo, but I'm not sure how to handle the situation here. There are a few options:

1. create another PR that deletes the redux definition. What to do with the definitions that depend on redux and which will break? 
2. keep a copy of the official redux definition in here just not to break things. What about maintaining it / keeping it in sync with the official one?

Either way this PR should be closed.

**Comment by basarat** [comment]
> I opened another PR in the redux repo, but I'm not sure how to handle the situation here

Can you reference it? Lets discuss that after that gets merged :rose:

> Either way this PR should be closed.

You mean merged right?

**Comment by use-strict** [comment]
See https://github.com/reactjs/redux/pull/1526

> You mean merged right?

Depends if we copy the other one here or just leave the current one as it is.

**Comment by mhegazy** [comment]
Is this still needed? can you please refresh it?

**Comment by basarat** [comment]
Redux already ships with ts typings : https://github.com/reactjs/redux/blob/master/index.d.ts and those should be copy pasted here.

The file is here for people that don't use npm or if we have other typing files in DT that depend on redux. There is no good story for that :rose:

**Comment by use-strict** [comment]
What I stated in my previous comment is still valid, but it's not for me to decide.

AFAIC this PR should be closed.

**Comment by basarat** [comment]
:rose:

**Pull request closed without merging**
