### PR TITLE
[@hapi/*] finalize new namespace for hapi modules

### PR DESCRIPTION
**Pull request by lenovouser**
Final followup to #34479 and #34687 (hopefully)

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]

**Comment by SimonSchick** [comment]
I was about ready to ask you if you forgot yar 😛

**Comment by SimonSchick** [comment]
@sandersn any chance we can fast track this? It's basically copy paste with only import changes :)

**Comment by lenovouser** [comment]
> I was about ready to ask you if you forgot yar 😛

😆 I checked and I think these are all missing @hapi modules 

> @sandersn any chance we can fast track this? It's basically copy paste with only import changes :)

Yep

**Comment by SimonSchick** [comment]
eeeee

**Pull request merged**
