### PR TITLE
fix: add missing null on file watch event filename

### PR DESCRIPTION
**Pull request by sosoba**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#filename-argument>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by sosoba** [comment]
> @sosoda It looks like `filename` in `FileChangeInfo` (`node:fs/promises` module) can be `null` too?

You have right!. Doc says:
>  All the `caveats` for `fs.watch()` also apply to `fsPromises.watch()`

I added a second change.

**Comment by Semigradsky** [comment]
Related: https://github.com/nodejs/node/pull/48032

**Comment by Semigradsky** [comment]
Sure! @sosoba please, add these changes also to another applicable node versions (v14, v16, v18 folders) and to TypeScript<4.8 versions (ts4.8 folders).

**Review by Semigradsky — APPROVED** [review]
👍

**Comment by jakebailey** [comment]
I feel like I'm missing something in the docs; the link provided in the PR description doesn't seem to go anywhere. Everything I'm reading seems to imply that this filename is not nullable: https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#event-change

**Comment by jakebailey** [comment]
I know that this is probably _technically_ correct, but is it super useful if all of the major OSs definitely get a string every time?

**Comment by sosoba** [comment]
> I know that this is probably _technically_ correct, but is it super useful if all of the major OSs definitely get a string every time?

What you mean "major OS"? I have issue with empty filename for Windows 11. This happens ex. when Node watch which files are modified by another Java process.

**Comment by jakebailey** [comment]
I guess the wording doesn't preclude a "supported" OS passing null...

**Review by jakebailey — APPROVED** [review]
I guess we'll see; I know TS itself will have to fix a type error with this.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
