### PR TITLE
SharePoint - Switching all references to SP.ListItem to generic ones to improve compile type checks

### PR DESCRIPTION
**Pull request by baywet**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19430
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Adding support for Generic types end to end for ListItem references as discussed.
I also bump version from 2013 to 2016 as discussed as it's potentially a breaking change and to catch up with the latest version of SharePoint.
Before this PR is accepted, I'd like @bLasTamos to give his blessing, my builds are fine, I'd like to hear from others.
Sorry for the delays, busy on other things :)

### CODE REVIEW

**Comment by baywet** [comment]
CC @gandjustas @andrei-markeev

**Comment by andrei-markeev** [comment]
Sorry, but what is the point to have generics there?

My points:
1. We cannot apply validation to **get_item** based on generics, so the usefulness is **imho** not that big. Of course I understand that this allows passing typed list items between methods, which can be useful in relatively big projects. On the other hand, 90% of cases at least in my daily work are rather short scripts.
2. As far as I know in TS it would mean that any existing code using list items will turn red. I use TS a lot in SP so for me it would mean that literally hundreds of existing scripts and snippets would need corrections at least if I don't want those warnings all the time which is pretty annoying.
3. Sometimes you need stuff quick and dirty, and with this change I would need to write `<any>` everywhere where listitems are used that in my opinion is not very convenient (and looks ugly).

I was thinking, is it possible to introduce this syntax as an alternative, so that it would be possible to use generics version and non-generics version at the same time? (I think TS doesn't allow creating overrides that differ only by generics part, but not sure, maybe it does)

**Comment by andrei-markeev** [comment]
Ah OK I only now noticed the link to discussion and read the comments.
Seems it doesn't break stuff in case of non-generic List - so fine with me!

**Comment by baywet** [comment]
Thanks for taking the time to review that @andrei-markeev I also increased the major version number in that PR to mitigate any breaking change potential issue (avoid shipping something that breaks all the builds all of a sudden) and to catch up on SharePoint.
@andy-ms I had a peer review, good to merge I think :)

**Pull request merged**
