### PR TITLE
[is-natural-number] Add is-natural-number typing

### PR DESCRIPTION
**Pull request by azerella**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Adding some type defs for https://github.com/shinnn/is-natural-number.js ❤️

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
From the sample usages (https://github.com/jonschlinkert/is-odd#usage), it appears to accept strings as well.

**Comment by adamzerella** [comment]
@amcasey Similar situation to: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33255#issuecomment-466260129

this function handles strings and numbers but does pass the value to `Math.abs` https://github.com/jonschlinkert/is-odd/blob/a80ee0d831a8ee69f1fad5b4673491847975eb26/index.js#L13 which supports

**Comment by amcasey** [comment]
@adamzerella `number | string` seems like a good compromise.  Callers can cast to `any` if they really need to pass another type.

**Comment by adamzerella** [comment]
@amcasey Good point 😄 , I've updated the type and added a new test 👍

**Review by amcasey — APPROVED** [review]

**Pull request merged**
