### PR TITLE
Knex: columns by object

### PR DESCRIPTION
**Pull request by sebneira**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://knexjs.org/#Builder-column
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Note that "Passing an object will automatically alias the columns with the given keys". This works as expected, but the typing won't allow for objects as a parameter.

### CODE REVIEW

**Review by mastermatt — COMMENTED** [review]
Can you reference in the docs or src where providing an object with more than one key is allowed?

**Comment by baronfel** [comment]
This is a bit of a chain to get to where we have proof that objects can in fact be columns.

Let's start with the `column` builder method: [here](https://github.com/tgriesser/knex/blob/master/src/query/builder.js#L106) a `columns` statement is pushed into the statement list.

The statement list is compiled in compiler.js, specifically [grouping statements by type](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L28) and then [handling all the column statements](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L165).

When handling a column statement, we hit the branch on line 180, because a defined value (an array containing our object) is present, so the formatter is invoked to columnize our object.

In formatter.js, `columnize` calls `wrap`, which does type detection on the value and if the value is an object, calls `parseObject` on it.  In [`parseObject`](https://github.com/tgriesser/knex/blob/master/src/formatter.js#L178) the object keys are iterated and formatted.

So I do believe that an object can be provided as a column selector.

**Review by mastermatt — APPROVED** [review]
Nice job. I also played around with some code to see what the SQL output would be and can confirm you can supply multiple objects with multiple keys.

**Comment by Sikian** [comment]
Sorry @mastermatt. I hoped the link I provided was enough, but definitely I could've expanded on that. Thanks @baronfel !

**Pull request merged**
