### PR TITLE
mongodb Collection.remove operator

### PR DESCRIPTION
**Pull request by ta3pks**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url 
  [github mongodb native driver](http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#remove)
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by CaselIT** [comment]
Since this pr has errors and was missing the deprecated comment, I've created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9476 with the proposed file changes. Thanks @NickLydon for finding the missing method

**Comment by NikosEfthias** [comment]
i think i found out theres a missing method on the definition

**Comment by vvakame** [comment]
#9476 is merged.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
