### PR TITLE
Add type definition for morris.js (morrisjs.github.io/morris.js/)

### PR DESCRIPTION
**Pull request by mareek**
Added a typings for morris.js

### CODE REVIEW

**Comment by vvakame** [comment]
please rename `morris.js/morris.d.ts` to `morris.js/morris.js.d.ts` and `-test.ts` to `-tests.ts`.

**Comment by mareek** [comment]
Sorry for the typos. It should be ok now

**Comment by vvakame** [comment]
once more... rename `morris.js/morris-tests.ts` to `morris.js/morris.js-tests.ts`.

**Comment by mareek** [comment]
done

**Pull request merged**
