### PR TITLE
Some changes to Highcharts

### PR DESCRIPTION
**Pull request by alisabzevari**

### CODE REVIEW

**Comment by vvakame** [comment]
please fix travis ci failed.

---

*highcharts/highcharts.d.ts*

to author(@damianog). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*highcharts/highstock.d.ts*

to author(@DavidKDeutsch). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by alisabzevari** [comment]
Fixed.

**Comment by damianog** [comment]
@vvakame  ec3448f 5b929ac 5b929ac adbc08f  :+1:

**Comment by mhegazy** [comment]
Thanks for the contribution. This PR contains merge conflicts and can not be merged at the moment. Please refresh this PR and address the merge conflicts.

**Comment by alisabzevari** [comment]
@mhegazy How can I refresh the PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
