### PR TITLE
Add definition for "angular-i18next"

### PR DESCRIPTION
**Pull request by cyrilschumacher**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-i18next/angular-i18next.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-i18next
  * http://bower.io/search/?q=angular-i18next
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-i18next/angular-i18next-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@cyrilschumacher thank you for your contributions.
please rename angular-i18next/angular-i18next.d.ts to ng-i18next/ng-i18next.d.ts

**Comment by cyrilschumacher** [comment]
I renamed the directory and its files.

**Comment by vvakame** [comment]
@cyrilschumacher thanks mate!

**Pull request merged**
