### PR TITLE
Add width property on ColHTMLAttributes in react

### PR DESCRIPTION
**Pull request by styfle**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

### CODE REVIEW

**Comment by styfle** [comment]
/cc @andy-ms @alloy


Anyone out there? 😨

**Comment by alloy** [comment]
Sorry, I don’t know much about those React types.

**Comment by sandersn** [comment]
The linked HTML documentation specifies that `<col>`'s width attribute is obsolete since HTML5. I don't know much about HTML standards and how they interact with React; is it OK to add an obsolete property?

**Comment by styfle** [comment]
@sandersn I can tell you that it works because I'm using it in production :)

React is pretty relaxed with the unknown DOM attributes now: https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

Also, I don't even know what the alternative is to `<col width="10%">` in HTML

**Pull request merged**
