### PR TITLE
react-router-dom: Correct type for `ref` in Link<S>

### PR DESCRIPTION
**Pull request by Eyas**
## Description

"ref" can be used rather than "innerRef" to return a ref to the <a>
element inside of <Link>.

See:

1. reacttraining.com/react-router/web/api/Link/innerref-function

    Where it says:

    > As of React Router 5.1, if you are using React 16 you should not
    > need this prop because we forward this ref to the underlying <a>.
    > Use a normal ref instead.Allows access to the underlying ref of the
    > component.

2. https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L74-L121

    Link is the result of forwardRef rather than an actual React class.

    This implies a few things:

    1. It is a function (see the return type of
        React.ForwardRefExoticComponent) rather than a class
    2. Its reference is to an inner <a> element, rather than what's in
      React.Component, which is a Ref to the element itself.

This introduces a potential incompatibility where users can't use
"new Link" anymore. But that reflects reality (Link is callable not
newable).

Since Link was previously exported as a class, we need to continue to
support it being used as both a type and a value. Since Link was
exported as a generic, we need to continue to support that. As a result:

1. Link is exported as a function that happens to implement the type
  corresponding to the result of
  `forwardRef<HTMLAnchorElement, LinkProps<S>>`.

2. Link is still exported as a type (interface) which is the same as
  that of the return value of `forwardRef<...>`.

## Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

**If changing an existing definition:**
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://reacttraining.com/react-router/web/api/Link/innerref-function>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. **N/A**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed. **Already there.**

### CODE REVIEW

**Comment by Eyas** [comment]
Reviewers: notice that I had to run `prettier --write` on some of these files to get them to pass lints. Formatting has been done in separate commits though so you can look at the functional changes separately

**Review by eps1lon — CHANGES_REQUESTED** [review]
It seems like we're only bumping the required TS version for a test? Can we revert this and instead test the generic approach with an explicit `createElement` call? Otherwise I don't think a test justifies bumping TS versions.

**Comment by Eyas** [comment]
@eps1lon: sure, I can do that, but do do note that TypeScript 2.9 will be mimimum required version for DefinitelyTyped in 2 days.

**Comment by Eyas** [comment]
@eps1lon -- Done. PTAL

**Comment by Eyas** [comment]
@sandersn I force pushed an update here that reverts some modifications to other packages. Any way I can reset the reviewer status here? i.e. make sure TS bot is only requesting reviews from react-router-dom owners?

**Comment by eps1lon** [comment]
> I can do that, but do do note that TypeScript 2.9 will be mimimum required version for DefinitelyTyped in 2 days.

Thanks. I didn't know that. Do you have a a link where this statement was made?

**Comment by Eyas** [comment]
> Thanks. I didn't know that. Do you have a a link where this statement was made?

https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-27-and-earlier

2.8 support window is through March 2020 (it was released on March 2018)

**Comment by sandersn** [comment]
Update on increasing the minimum version: Since 3.9 RC is coming up soon, I may delay the increase until then. At any rate, I won't have time in the next week, so the actual date will definitely be some time in April.

**Comment by Eyas** [comment]
Yeah that's fine either way, we're not bumping up min version in this PR anymore.

**Comment by Eyas** [comment]
Hi @eps1lon just wondering if you had a chance to review.

**Comment by Eyas** [comment]
Hey @RyanCavanaugh -- this PR is stuck as "Revision needed" but I've incorporated all needed revisions. I'm having trouble getting updated reviews. What's the protocol here usually?

**Review by eps1lon — APPROVED** [review]

**Pull request merged**
