### PR TITLE
Add specialized signature for karma server's on run_complete

### PR DESCRIPTION
**Pull request by nicojs**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by nicojs** [comment]
This is case 2 i guess. What more do i need to do? I don't know this template

**Comment by vvakame** [comment]
*karma/karma.d.ts*

to author (@tkrotoff). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by tkrotoff** [comment]
👍

**Comment by vvakame** [comment]
it merged. sorry for late!

**Pull request merged**
