### PR TITLE
[karma-chai] Replace name with username

### PR DESCRIPTION
**Pull request by hexpunk**
This is in response to #26092.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
Looks like Travis CI hasn't run on this PR. This is possibly because Travis mistakenly flagged your account as abusive. This happens from time to time. Could you connect your GitHub account to Travis CI at http://travis-ci.org (click “Sign up” and consent to connecting your GitHub account)? Hopefully this should get the tests to run. Sorry for the inconvenience.

**Comment by JayAndCatchFire** [comment]
@minestarks Okay, I just did what you asked.

**Comment by minestarks** [comment]
I'll close and reopen the PR to give Travis a nudge.

**Comment by minestarks** [comment]
Alright, still no Travis. Not sure what's going on, but I just looked at the change and pretty confident this won't break anything. (I HOPE).

**Pull request merged**
