### PR TITLE
Master

### PR DESCRIPTION
**Pull request by andrewtelnov**
Add type definition for surveyjs library. 
It is originally written on TypeScript.

### CODE REVIEW

**Comment by vvakame** [comment]
http://surveyjs.org/
please rename `survey/survey.d.ts` to `survey-knockout/survey-knockout.d.ts` or `survey-knockout-bootstrap/survey-knockout-bootstrap.d.ts`

**Comment by andrewtelnov** [comment]
Done!
Thank you,
Andrew

**Comment by andy-ms** [comment]
Hi @andrewtelnov, there are a lot of `/// <reference path=xxx.d.ts" />` in this file that don't seem to refer to real files. Triple-slash directives are only valid at the top of a file, so these are all ignored. Could they be deleted?

**Comment by andrewtelnov** [comment]
Hi @andy-ms,
I have migrated to [typings](https://github.com/typings/typings).  I have the fresh version here:
https://github.com/andrewtelnov/surveyjs/tree/master/lib_typings
It makes sense to me to improve this file only. 
However, to be honest, I do not understand, what exactly problem you are trying to solve?
I am using gulp-typescript to build with the declaration: true option.
You may play with the buildTypeDefinition function in file: https://github.com/andrewtelnov/surveyjs/blob/master/gulpfile.js
To remove the "reference" links, I will have to parse the stream, I guess. Why do you need this?

Thank you.
Andrew

**Pull request merged**
