### PR TITLE
Update to support version 1.0 of react-slider

### PR DESCRIPTION
**Pull request by Bjorgvin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/zillow/react-slider
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Bjorgvin** [comment]
Now I see there is a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40094) already for this so I close my change.

**Comment by Bjorgvin** [comment]
I can see that the other PR is about to be closed today since @waynevanson is dormant. So I open this up again until told to close.

**Comment by waynevanson** [comment]
Thanks @Bjorgvin! Forgot to check back on my pull. I've commented on my pull and about to make the required changes.

**Comment by Bjorgvin** [comment]
Hi @waynevanson :) I can see your PR has been `closed`. I used your generic solution and the only problem I had was I needed to update the `TypeScript` version to `3.6` because of this error

image

I had no lint problems like you did so I _can_ update my PR to contain the generics. However, like @sandersn said: 

> "Moving from 2.8 to 3.6 means that this update will only be available by default to people on 3.6 or higher. Everybody else will be stuck with the old version."

I will wait for a review and I can easily push the generic changes with `TypeScript 3.6 `if that is what the maintainers want.

**Pull request merged**
