### PR TITLE
Export interfaces

### PR DESCRIPTION
**Pull request by wclr**
Exporting interfaces would be useful for developing libs on top of localforage

### CODE REVIEW

**Comment by whitecolor** [comment]
https://github.com/thgreasi

What it wrong with it?

**Comment by thgreasi** [comment]
I think that it's ok. Additionally I would suggest to start using `export =` like what pouchdb.d.ts did, but this should probably better be a separate PR.

**Comment by whitecolor** [comment]
Actually tests are not passing with exports added with an error
```
---------------— For file:localForage/localForage-tests.ts
localForage/localForage-tests.ts(3,26): error TS2304: Cannot find name 'LocalForage'.
```

**Comment by vvakame** [comment]
I think this PR is no need.
What code do you want to write? please show me a sample code.

**Comment by whitecolor** [comment]
@vvakame 
Say I want to make a wrapper:

```js
function createMyStorage (options: LocalStorageOptions) {
   return localStorage.createInstance(options)
}
```

And if one going to create a custom driver `LocalForageDriver` interface too would be useful.

**Comment by thgreasi** [comment]
For my `localforage-cordovasqlitedriver` I just used:
```ts
/// <reference path="../localforage/index.d.ts" />

declare module "localforage-cordovasqlitedriver" {
    var cordovaSQLiteDriver: LocalForageDriver;
    export = cordovaSQLiteDriver;
}
```

**Comment by whitecolor** [comment]
@thgreasi how do you get access to `LocalForageDriver` in your module?

**Comment by thgreasi** [comment]
@whitecolor You can view the source of [localForage-cordovaSQLiteDriver-TestIonic2App](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App) where this code snippet is used.

**Comment by RyanCavanaugh** [comment]
Please investigate and address the CI build failure. Thanks!

**Comment by andy-ms** [comment]
Closing as tests are not passing and it looks like there are other ways around this issue.

**Pull request closed without merging**
