### PR TITLE
[node:test] add before, beforeEach, after, afterEach

### PR DESCRIPTION
**Pull request by coderbyheart**
These were added in [v18.8.0](https://nodejs.org/api/test.html#before-fn-options).

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/v18.8.0/lib/test.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by r3nya — APPROVED** [review]

**Review by trivikr — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@coderbyheart thanks!

**Comment by AviVahl** [comment]
Perhaps also add those on the context: https://nodejs.org/dist/latest-v18.x/docs/api/test.html#contextbeforeeach-fn-options

**Comment by meyfa** [comment]
#62375 added a `ts4.8` variant for node. I think this PR should also edit the test module in the `ts4.8` subdirectory in addition to the main one.

**Comment by meyfa** [comment]
Moreover they are now available in 16.18.0, too: https://github.com/nodejs/node/releases/tag/v16.18.0

**Review by LinusU — APPROVED** [review]
LGTM 👍 

I think that it would be nice to add this to `ts4.8`, and `16.18.0` too. But personally I don't see a problem with that happening in follow up PRs? Not sure if there is a written policy on this 🤔

**Comment by meyfa** [comment]
Sure, I don't think 16.18 needs to happen here. ts4.8 on the other hand should be relatively straightforward to do since it's an exact copy. And I would love to see ts4.8 included with this PR because otherwise, the features added here cannot even be used by anyone until TypeScript 4.9 is generally available.

**Comment by peterblazejewicz** [comment]
FYI: I've ported to TS4.8 branch

**Review by sandersn — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge

**Pull request merged**
