### PR TITLE
Fix module name conflict in github-electron

### PR DESCRIPTION
**Pull request by PatSmuk**
Related: https://github.com/Microsoft/TypeScript/issues/5560

Both github-electron-main.d.ts and github-electron-renderer.d.ts declare
an 'ipc' module, since Electron has different 'ipc' modules depending on
whether it's being require()'d from a main process or a renderer process.

This commit simply renames the modules so that they don't conflict and cause
compilation to fail.

Use either:

```
import * as ipc from 'ipc-main';
import * as ipc from 'ipc-renderer';
```

### CODE REVIEW

**Comment by vvakame** [comment]
to author(@jedmao). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by jedmao** [comment]
:+1:

**Comment by Patman64** [comment]
Unfortunately it looks like I'm mistaken.

Changing it to 'ipc-main' and 'ipc-renderer' causes the emitted JS to look like:

```javascript
var ipc = require('ipc-main');
```

This won't work correctly. So the only real solutions are:
- Electron changes the names to not collide any more.
- TypeScript compiler changes to allow Node module collisions.
- I keep the type definitions out of the typings folder, and just `/// <reference />` them in the individual files.

I'll stick with the last option for now.

**Comment by jedmao** [comment]
That's unfortunate, but yeah, doesn't surprise me. Collisions are kind of a bitch in TypeScript.

**Pull request closed without merging**
