### PR TITLE
Fix TransformOptions' callback

### PR DESCRIPTION
**Pull request by jblaise**
Make it usable in object mode

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
- [new definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L274)
- [doc](https://nodejs.org/docs/latest-v8.x/api/stream.html#stream_transform_transform_chunk_encoding_callback)

### CODE REVIEW

**Comment by nguymin4** [comment]
I thought we stopped supporting node 6, 7, 8 already?

**Comment by jblaise** [comment]
I didn't know that but it blocks compile when you use objectMode:true

**Review by galkin — CHANGES_REQUESTED** [review]
We don't support definition for unsupported Node.js versions.

**Comment by Flarna** [comment]
I would not block changes on old/EOL versions as long as it is ensured that the fix is also include in actual version in the same or a better way.

**Comment by jblaise** [comment]
Excuse me @galkin, I saw a suggestion in the interface, but I can't see what you suggested. 
What should I change ?

**Comment by jblaise** [comment]
@Flarna all newer versions have it [fixed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L274) the same way

**Review by Flarna — APPROVED** [review]

**Comment by galkin** [comment]
@sandersn, think this pull request is a good example for discussion:
"Should we stop commit any changes at unsupported node.js version or not? in what cases are there exceptions?"

Could you provide your position?

**Comment by sandersn** [comment]
My opinion is that v6,7,8 are still in the repo precisely because some community members might need to ship fixes like this one. I agree with @Flarna that a fix is OK as long as it is already fixed in newer versions too. I'm not sure what the case is with this change &mdash; does this need to be ported to currently supported versions?

Couple of additional points:
1. The usual contributors to the node types shouldn't be under any obligation to keep old node types up to date with fixes, nor should they have to ask other contributors to do so.
2. If fixes to old versions use up a lot of reviewer time, we might want to revisit this, but I doubt that is the case.

**Comment by SimonSchick** [comment]
I think it is fair to apply non-breaking fixes, making something `any` is probably ok.

**Review by galkin — APPROVED** [review]

**Review by ExE-Boss — APPROVED** [review]

**Pull request merged**
