### PR TITLE
Fix for 'Express' namespace not being found for the Twilio typings.

### PR DESCRIPTION
**Pull request by Karn**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.
### Notes

While compiling my project, I noticed that my linter was giving me warnings about the 'Express' namespace not being found.

``` Bash
Using tsc v1.8.10
typings/modules/twilio/index.d.ts(452,51): error TS2503: Cannot find namespace 'Express'.
```

The solution was to refactor the reference from `Express` to `express`.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
According to this line of [twilio.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twilio/twilio.d.ts#L6), it imports definition from [express.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts#L16), the declared name is exactly **express**.
It really should modify **Express** to **express**.

**Comment by vvakame** [comment]
cc/ @horiuchi

**Comment by horiuchi** [comment]
`Express` namespace is defined in [express-serve-static-core.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts#L14).
Please install also that file.

**Comment by TonyPythoneer** [comment]
Hi @horiuchi, I see the `Express` is from `express-serve-static-core.d.ts`.

It's because `Express` is [a global declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express-serve-static-core/express-serve-static-core.d.ts#L8), it's surely able to be imported, but it's implicit for maintainer.

Since [express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twilio/twilio.d.ts#L10) has been imported, it should be used in this definition. `express` is more explicit than `Express`.

**Comment by horiuchi** [comment]
The `Express` namespace is defined for expanding express type definition from other library, such as `passport`.
A user side of `express` may use `express` namespace from `express/express.d.ts`, e.g. `express.Request`, `express.Response`, or others...

**Comment by TonyPythoneer** [comment]
Hi @Karn or @vvakame,
I had sent #11247 PR and got fixed. Please close it.

**Comment by Karn** [comment]
Thanks @TonyPythoneer!

**Pull request closed without merging**
