### PR TITLE
Updated react-i18next types to 4.6.1

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
Waiting for #17702

**Comment by KostyaEsmukov** [comment]
👍
Great, thank you.

Could you please remove me from the authors of v4 typings?

**Comment by GiedriusGrabauskas** [comment]
Sure 🙂

**Review by rbuckton — CHANGES_REQUESTED** [review]

**Comment by RyanCavanaugh** [comment]
Please fix the issue mentioned above. Thanks!

**Comment by GiedriusGrabauskas** [comment]
Updated, but still waiting for #17702.

**Comment by RyanCavanaugh** [comment]
@GiedriusGrabauskas Please fix the failures indicated in the Travis CI log.

**Comment by andy-ms** [comment]
Probably needs to merge from master now that #17702 is in.

**Comment by GiedriusGrabauskas** [comment]
Done, waiting for merge, @andy-ms.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
