### PR TITLE
[Hapi] Fix input and response validation function signatures

### LINKED ISSUE #16750: [Hapi] value parameter of response validation functions is not Reponse
Hi there,

I am quite sure, that the first parameter for the `ValidationFunctionForRouteResponse` should not be `Response`.

Here is a small test case to verify Hapi is just putting the response payload into the function:

```typescript
import * as Chai from 'chai';
import * as ChaiPromised from 'chai-as-promised';
import * as Hapi from 'hapi';
import * as Lab from 'lab';

Chai.use(ChaiPromised);
const expect = Chai.expect;
const lab = exports.lab = Lab.script(); // tslint:disable-line:mocha-no-side-effect-code
const describe = lab.describe;
const it = lab.it;

describe('Test validation function input', () => {
    it('expects the validated object to exactly match the reply', () => {
        const server = new Hapi.Server();
        server.connection({});
        let validatedObject: {};
        const expectedObject = { test: 123 };

        server.route({
            path: '/', method: 'GET', config: {
                response: {
                    schema: (value: Hapi.Response, _: Hapi.JoiValidationObject, next: Hapi.ContinuationFunction) => {
                        validatedObject = value;
                        next();
                    }
                },
                handler: (_, reply) => {
                    reply(expectedObject);
                }
            }
        });
        return server.inject({ url: '/', method: 'GET' }).then((res) => {
            expect(validatedObject).to.equal(expectedObject);
            expect(JSON.parse(res.payload)).to.deep.equal(expectedObject);
        });
    });
});
```

Am I missing something here? I also noted your TODO comments in that domain and that the Hapi documentation is quite misleading :)

---

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

### PR DESCRIPTION
**Pull request by niklas-sparfeld**
Fixes #16750

Since this is my first contribution to DefinitelyTyped I have no idea whether and how to increase the version number or not. Sorry for that.

Apart from that I am also not too happy with the usage of `any` at this many places, but in my opinion it has been used appropriately here.

Hope this helps :)

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/hapi/blob/master/lib/validation.js#L136
- [x] Increase the version number in the header if appropriate
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by AJamesPhillips** [comment]
On train going through tunnels.  Will aim to review and provide my feedback on Wednesday evening.

**Comment by Kampfgnom** [comment]
I will be on a short vacation from Wednesday on and will be back on Tuesday 2017-06-06.

**Comment by andy-ms** [comment]
Looks like some other packages need `// TypeScript Version: 2.3` comments too.

**Comment by jasonswearingen** [comment]
@Kampfgnom  hi, just seems like you need to add a comment at the top of the file.   here are some details from the failed travis-ci build:

```
Package compiles in TypeScript 2.3 but not in 2.2.
You can add a line '// TypeScript Version: 2.3' to the end of the header to specify a newer compiler version.
```

**Comment by Kampfgnom** [comment]
@jasonswearingen I already did that of course :) The question is, whether we want to enforce the TypeScript version on our users or not.

The TypeScript 2.3 feature used here is definitely not *necessary* per se - it only simplifies the typings' usage a bit.

**Comment by Kampfgnom** [comment]
Okay I just noticed that *other* packages no longer build since they are importing the changed Hapi typings. I did not know that it works that way, sorry.

Should I update the required typescript version of dependent packages, too?

I will just do that right now.

**Comment by AJamesPhillips** [comment]
@Kampfgnom this is looking good.  Thanks.  I have added a commit with some clarifications to the docs and minor change to allow `null` to be used (as well as `undefined`) which you can grab here:  https://github.com/AJamesPhillips/DefinitelyTyped/tree/Kampfgnom

I will also submit a PR to hapi for the documentation.

**Comment by Kampfgnom** [comment]
I pushed your commit into this PR.

**Comment by AJamesPhillips** [comment]
We're good to merge @dt-bot @andy-ms .  Thank you very much @Kampfgnom 👍

**Comment by AJamesPhillips** [comment]
We're good to merge @dt-bot @andy-ms .

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
