### PR TITLE
fabric-impl.d.ts: add oCoords per fabricjs API docs. update README with contrib name

### PR DESCRIPTION
**Pull request by glenngartner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://fabricjs.com/docs/fabric.Object.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by BradleyHill** [comment]
@glenngartner You should look at this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33243
It moves the entire fabric types to 2.6. If correct there, could kill this and wait for that to merge. If not, might want to want until it gets in as it may stomp yours. Regards.

**Comment by jessetrinity** [comment]
@BradleyHill my mistake. Do you see any reason to keep anything here that isn't in #33243 ?
Thanks.

**Comment by BradleyHill** [comment]
@jessetrinity No mistake, i didn't respond until just now. This notification must have been obscured by other. Looks like PRs close together.

Anyway, this change is in #33243  line 2818 so it'll be there if/when it gets merged. We good, i think.

**Comment by glenngartner** [comment]
Great, thanks Bradley.

**Pull request merged**
