### PR TITLE
[@types/three] Adds morphTargetInfluences and morphTargetDictionary to mesh on three-core.d.ts

### PR DESCRIPTION
**Pull request by neukym**
Very minimal change. Solving issue #20468

**Checklist:**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

**If changing an existing definition:**
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [ThreeJS Mesh Docs](https://threejs.org/docs/#api/objects/Mesh.morphTargetInfluences)

### CODE REVIEW

**Comment by efokschaner** [comment]
@neukym thanks for making the change. Please note that the type `{}` is the type of empty objects, it tells the type system nothing about what that "map" contains. (Possibly even constrains it to contain nothing beyond built-in object members although I'm foggy on this fact, and a Google search yields conflicting explanations.) You should use an index signature, see "Index types and string index signatures" in https://www.typescriptlang.org/docs/handbook/advanced-types.html to constrain the `morphTargetDictionary` to be a mapping of strings to numbers (if my reading of the implementation is accurate, please confirm).

**Comment by neukym** [comment]
Ah yeah apologies, I'd only tested if `morphTargetInfluences`worked.

> ... to constrain the morphTargetDictionary to be a mapping of strings to numbers (if my reading of the Mesh implementation is accurate, please confirm).

Yes, my understanding is that morphTargetDictionary exists so one can make a morphtarget such as

```typescript
 geometry.morphTargets[0] = { name: 'my-morphtarget', vertices: myMorphtargetVertices };
```
and then instead of having to type
```typescript 
mesh.morphTargetInfluences[0] = 0.1; // or whatever
```
one can type
```typescript
mesh.morphTargetInfluences[mesh.morphTargetDictionary['my-morphtarget']] = 0.1;
```


> You should use an index signature, see "Index types and string index signatures"

I didn't quite understand how to create the correct signature from this, I tried
```typescript
morphTargetDictionary?: Map<string,number>;
```
and it seems to work as expected (ie I can confirm 
```typescript
mesh.morphTargetInfluences[mesh.morphTargetDictionary['my-morphtarget']] = 0.1;
```
now compiles, and returns the correct values.)

Can you confirm this is what you had in mind? If so, I will add it in.

**Comment by efokschaner** [comment]
No problem, the index signature syntax is tricky. Allow me to clarify:

Using `Map<string,number>` would imply that `morphTargetDictionary` has the full interface of a JS [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) including things like [`delete()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete) and [`set()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set).

However because three.js is just using an object as a quick-and-dirty map it does not have all the capabilities of the Map type. So what I'm recommending that you do is:
```
morphTargetDictionary?: { [key: string]: number; };
```
This communicates that this is an object that supports getting and setting `number`s at arbitrary `string` indices, just like a Map, but its an Object with this one feature and nothing more.

Thanks again for your help in getting this perfect.

**Comment by efokschaner** [comment]
Also check out [this demo for typed indices](https://www.typescriptlang.org/play/index.html#src=let%20typedIndices%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20number%3B%20%7D%20%3D%20%7B%7D%3B%0D%0AtypedIndices%5B'foo'%5D%20%3D%205%3B%0D%0AtypedIndices%5B'bar'%5D%20%3D%20'woops'%3B%20%2F%2F%20Type%20'%22woops%22'%20is%20not%20assignable%20to%20type%20'number'%0D%0Alet%20y%3Anumber%20%3D%20typedIndices%5B'baz'%5D%3B%0D%0Alet%20z%3Astring%20%3D%20typedIndices%5B'qux'%5D%3B%20%2F%2F%20Type%20'number'%20is%20not%20assignable%20to%20type%20'string'%0D%0A%0D%0Alet%20untyped%20%3D%20%7B%7D%3B%20%2F%2F%20Type%20not%20specified%0D%0Auntyped%5B'foo'%5D%20%3D%205%3B%0D%0Auntyped%5B'bar'%5D%20%3D%20'woops'%3B%20%2F%2F%20works%20fine%2C%20regardless%20of%20intention%20to%20only%20store%20numbers%0D%0Alet%20y2%3Anumber%20%3D%20untyped%5B'baz'%5D%3B%0D%0Alet%20z2%3Astring%20%3D%20untyped%5B'qux'%5D%3B%20%2F%2F%20same%20as%20above) if you like.

**Comment by neukym** [comment]
Ah, that's really helpful @efokschaner, thanks.

**Comment by neukym** [comment]
To confirm, the corrected `morphTargetDictionary` type has been tested in code, and returns the correct values.

**Comment by efokschaner** [comment]
Thanks @neukym , let's ship it. Here's the ceremonial :+1: .

**Pull request merged**
