### PR TITLE
Adding typings for stripe-node

### PR DESCRIPTION
**Pull request by wjohnsto**
There exists typings for Stripe.js, but not for https://github.com/stripe/stripe-node/. These typings are not fully complete, but the API is huge. I have done a good amount of the typings using the [API reference](https://stripe.com/docs/api) for the JSDoc.

### CODE REVIEW

**Comment by vvakame** [comment]
@wjohnsto thank you your contributions.
please rename stripe-node/stripe-node.d.ts to stripe/stripe.d.ts. http://definitelytyped.org/guides/contributing.html#naming-the-file

**Comment by wjohnsto** [comment]
@vvakame There already exists declarations for [Stripe.js](https://stripe.com/docs/stripe.js) under stripe/stripe.d.ts. These typings are specifically for [stripe-node](https://github.com/stripe/stripe-node/). The APIs are similar, but different.

**Comment by vvakame** [comment]
@wjohnsto umm... I understand. please use stripe/stripe-node.d.ts.

**Comment by wjohnsto** [comment]
@vvakame I renamed the definitions, and also fixed the stripe definitions because I was receiving an issue with the `noImplicitAny` flag.

I also had to rename the global module I was using in stripe-node to StripeNode to avoid having duplicate variable names clashing with Stripe. This shouldn't be an issue however, as stripe-node does not have a global module, and the one I'm defining is only used for interfaces.

**Comment by vvakame** [comment]
@wjohnsto thanks mate!

**Pull request merged**
