### PR TITLE
[plaid-link] add optional institution_id arg to LinkHandler 'open'

### PR DESCRIPTION
**Pull request by mmcgahan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
        - search for `function open(){var t=arguments.length>0&&void 0!==arguments[0]` in the source https://cdn.plaid.com/link/v2/stable/link-initialize.js
- [ ] **N/A** If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by mmcgahan** [comment]
I've put a link to the Plaid Link script supplied by Plaid, but essentially I think this is an undocumented but still supported feature of the Plaid Link widget - I think the best solution is allow the optional parameter at the type level so I don't have to manually ignore the error or monkey-patch the type def.

**Comment by mmcgahan** [comment]
@afholderman @brolaugh if either of you could have a quick look at this, I would appreciate it

**Review by brolaugh — APPROVED** [review]
LGTM

**Comment by mmcgahan** [comment]
Ready to merge

**Comment by mmcgahan** [comment]
thanks @brolaugh

**Pull request merged**
