### PR TITLE
[@types/react-table] Update to match react-table@6.7.4

### PR DESCRIPTION
**Pull request by Havret**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://react-table.js.org/#/story/readme>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Havret** [comment]
#20713

**Comment by royxue** [comment]
Could you do a cherry pick to clean up the commits history?

**Comment by royxue** [comment]
And I think maybe it would be better to do the local test first instead of keep pushing commits.

**Comment by Havret** [comment]
Yep, I am going to clean this mess. :)

**Comment by royxue** [comment]
Nice, I will review your changes

**Pull request closed without merging**
