### PR TITLE
Updated jQuery - Add typing for function 'this'

### PR DESCRIPTION
**Pull request by use-strict**

### CODE REVIEW

**Comment by use-strict** [comment]
I suspect the definition tester needs to be updated somehow, because it says "Typings without tests: jquery"

**Comment by mhegazy** [comment]
not sure i understand why travis is failing. can you merge with master and push again?

**Comment by use-strict** [comment]
@mhegazy , the base branch is types-2.0 and I'm already up-to-date with it.

I doubt that types-2.0 builds successfully since it wasn't even using typescript 2.0. I had to also update the package.json and npm-shrinkwrap.json files in my branch.

**Comment by mhegazy** [comment]
Can you give it another try. the CI server should be working now correctly.

**Comment by use-strict** [comment]
I'm getting the same error, locally as well.

**Comment by mhegazy** [comment]
@andy-ms looks like another case of definition-tester broken, can you merge this in as well.

**Pull request merged**
