### PR TITLE
fix: EventType has not 'action'

### PR DESCRIPTION
**Pull request by yunhungo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: [here](https://github.com/react-navigation/react-navigation-core/blob/44852e59a4bd524cc8fc44cc53d09c3a673fd903/src/getNavigation.js#L30)
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by skovhus** [comment]
I'm wondering why `action` [isn't documented on reactnavigation.org](https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle), but it [seems like a valid event name](https://github.com/react-navigation/react-navigation-core/blob/44852e59a4bd524cc8fc44cc53d09c3a673fd903/src/getNavigation.js#L30).

@Mrcooder can you fill in the PR template?

**Comment by 43081j** [comment]
This is pretty odd.

The RFC they implemented is here FYI:
https://github.com/ericvicenti/rfcs/blob/master/0000-event-system.md#navigator-events

Which doesn't specify `action`. Maybe they use it internally? off-spec.

**Comment by Mrcooder** [comment]
@skovhus I don't know why [reactnavigation.org](https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle) isn't documented 'action' event but i got type error cuz it hasn't 'action' in its d.ts file,Sorry, I wanna know how to fill in the PR template. Is it have some button to click to fill in? Thx.

**Review by skovhus — APPROVED** [review]

**Comment by skovhus** [comment]
>  I wanna know how to fill in the PR template.

You can change it by clicking edit in the PR description now. The PR template contains some information on how to fill it in (e.g. `Select one of these and delete the others:`). 

For checking a checkbox you add a `x` in the `[ ]`.

**Comment by Mrcooder** [comment]
> > I wanna know how to fill in the PR template.
> 
> You can change it by clicking edit in the PR description now. The PR template contains some information on how to fill it in (e.g. `Select one of these and delete the others:`).
> 
> For checking a checkbox you add a `x` in the `[ ]`.

Maybe i have done this, Thank you very much 👍

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
