### PR TITLE
definition for feng3d

### PR DESCRIPTION
**Pull request by wardenfeng**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
Why do you want to this change?
https://github.com/feng3dTS/feng3d-ts/blob/master/package.json#L6
package already bundling type definitions. It is so good 👍

**Comment by wardenfeng** [comment]
@vvakame I'm sorry to trouble you, I have been fixed.

**Comment by vvakame** [comment]
please read this article first. http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by minestarks** [comment]
@wardenfeng Thank you for your contribution. When the typings are published with the official project, there is no need to add them to DefinitelyTyped. This is why I'm closing out this PR.

**Pull request closed without merging**
