### PR TITLE
[rimraf] Bugfix: Account for null and undefined errors

### PR DESCRIPTION
**Pull request by joshuaharry**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

See https://github.com/isaacs/rimraf/blob/8c10fb8d685d5cc35708e0ffc4dac9ec5dd5b444/rimraf.js#L78 for an example where `rimraf` gives the callback `undefined` and https://github.com/isaacs/rimraf/blob/8c10fb8d685d5cc35708e0ffc4dac9ec5dd5b444/rimraf.js#L150 for an example where `rimraf` gives the callback `null`. 

In brief: If `rimraf` runs successfully, the callback function can't count on the first argument being an error.

### CODE REVIEW

**Comment by AviVahl** [comment]
The `| undefined` are there in preparation for ts@4.4's `exactOptionalPropertyType`. Might want to keep those.

**Comment by joshuaharry** [comment]
> The `| undefined` are there in preparation for ts@4.4's `exactOptionalPropertyType`. Might want to keep those.

Fixed, thanks!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@joshuaharry thx!

**Comment by joshuaharry** [comment]
Ready to merge

**Pull request merged**
