### PR TITLE
Add _nodeModulePaths to node Module class

### PR DESCRIPTION
**Pull request by mohsen1**
Being used here 
https://github.com/webpack/webpack/blob/51b0df77e4f366163730ee465f01458bfad81f34/lib/NormalModule.js#L151

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by ajafff — CHANGES_REQUESTED** [review]
This is not documented in Node's docs and the underscore implies that it's private. The fact that it's used by some project doesn't mean it should be publicly available.

**Comment by mohsen1** [comment]
@ajafff marked as deprecated. It's a real API and lack of this property is blocking us migrating to TypeScript. 

What is the policy here? Are we not adding types for non-documented stuff?

**Comment by mohsen1** [comment]
pinging @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @DeividasBakanas @kjin @alvis @OliverJAsh @eps1lon @Hannes-Magnusson-CK @jkomyno @ajafff @hoo29

**Comment by Flarna** [comment]
I recommend to use a project local .d.ts file to access such internal, non documented APIs.
Maybe the documented `require.resolve.path()` (see https://nodejs.org/dist/latest/docs/api/modules.html#modules_require_resolve_paths_request) fits your needs also?

**Comment by mohsen1** [comment]
Maybe we should not add this one.

**Pull request closed without merging**
