### PR TITLE
Add definitions for React DnD

### PR DESCRIPTION
**Pull request by epelz**
Adding React DnD type definitions for React DnD v1.1.4, which is the latest
version.

Paired with @vsiao on parts of this

### CODE REVIEW

**Comment by vvakame** [comment]
*react-dnd/react-dnd.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/react-dnd
  * http://bower.io/search/?q=react-dnd
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (react-dnd/react-dnd-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@epelz thank you for your contributions.
please rename react-dnd/react-dnd-test.ts to react-dnd/react-dnd-tests.ts

**Comment by epelz** [comment]
@vvakame Woops, should be all set now.

**Comment by vvakame** [comment]
@epelz thanks mate!

**Pull request merged**
