### PR TITLE
Create orientjs.d.ts

### PR DESCRIPTION
**Pull request by saeedtabrizi**
Type definitions for orientjs 2.0.0

### CODE REVIEW

**Comment by vvakame** [comment]
*orientjs.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/
  * http://bower.io/search/?q=
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (orientjs-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by saeedtabrizi** [comment]
Hi @mhegazy ,
Yes i can do it . 

Thanks
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
Hi @mhegazy  
i create a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9803 now that passing tests for Orientjs v2.1.0 .

Thanks
Saeed Tabrizi

**Pull request closed without merging**
