### PR TITLE
add optional alt-property to LatLngLiteral and LatLngTuple

### PR DESCRIPTION
**Pull request by henrythasler**
Leaflet's LatLng-Class support an optional alt-property (altitude of a point) upon creation via literals or tuples. This PR adds this to the typings as well.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://leafletjs.com/reference.html#latlng
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by someonewithpc** [comment]
@henrythasler Thanks for your contribution :) I've created #66805 which applies some small fixes to this PR (and don't worry, I tagged you as the author :) ), so I'm closing this. Please let me know if that other PR is missing anything

**Review by someonewithpc — CHANGES_REQUESTED** [review]
Please reset on my fork at https://github.com/someonewithpc/DefinitelyTyped.git / `git@github.com:someonewithpc/DefinitelyTyped.git`

I replaced some small things and kept you as the author

**Comment by henrythasler** [comment]
The only difference I see is with `type LatLngTuple` where I prefer my [Tuple](https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types) `[number, number, number?]` with an optional property over your [Union](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) `[number, number] | [number, number, number]`. What do you think?

**Comment by someonewithpc** [comment]
> The only difference I see is with `type LatLngTuple` where I prefer my [Tuple](https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types) `[number, number, number?]` with an optional property over your [Union](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) `[number, number] | [number, number, number]`. What do you think?

Either is fine, but I think the union is less surprising. But the other differences were with the warnings, I think something may have gone wrong when you tried to solve merge conflicts

**Comment by henrythasler** [comment]
If you mean the specific linter-rules, they were introduced by [PR66798](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66798). I don't want to revert that change. It seems the diff shown here did not pick this up correctly.

**Review by someonewithpc — APPROVED** [review]
My bad then, I must have diffed against the wrong commit

**Comment by henrythasler** [comment]
Ready to merge

**Pull request merged**
