### PR TITLE
Update react-inner-image-zoom types for v3

### PR DESCRIPTION
**Pull request by laurenashpole**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/laurenashpole/react-inner-image-zoom/blob/master/CHANGELOG.md
https://github.com/laurenashpole/react-inner-image-zoom#props
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by joshuajeschek — APPROVED** [review]
👍 here you go

**Comment by joshuajeschek** [comment]
Wouldn't bundling your own types with your own package be easier btw @laurenashpole ?cheers.

**Comment by laurenashpole** [comment]
@joshuajeschek This might sound ridiculous but it honestly hadn't occurred to me to do that. I'll merge this for now and look at copying them over in the future.

**Comment by laurenashpole** [comment]
Ready to merge

**Pull request merged**
