### PR TITLE
[js-cookie] JSON.parse can return any types

### PR DESCRIPTION
**Pull request by alepee**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-json.parse
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by alepee** [comment]
Since JSON is not only about Object, `JSON.parse` can return `any`,
so does `Cookies.getJSON(key: string)`.

```js
JSON.parse('"string"');
// "string";

JSON.parse('true');
// true

JSON.parse('[]')
// []

JSON.parse('{ "key": "value" }')
// { key: 'value' }
```

Could you review this PR pleaes @theodorejb @BendingBender ?
Thanks 😄

**Comment by theodorejb** [comment]
You're correct that JSON supports more than just objects. However, I think that `any` is a little too broad. For example, `any` includes `undefined` (even with strict null checks), which isn't a valid JSON value. According to the [JSON specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), "A JSON value can be an object, array, number, string, true, false, or null."

So I think it would be better to use the union type `object | number | string | boolean | null`.

**Comment by alepee** [comment]
Thanks @theodorejb, I agree with you. But choosed not to do so, because of `JSON.parse` TypScript definition : https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L989

What do you think about it ?

**Comment by theodorejb** [comment]
@alepee TypeScript has probably had that definition since before the language supported union types. 😄 I guess I'm fine with matching it, even if a more specific type would be correct. 👍

**Pull request merged**
