### PR TITLE
Fix for IComponentOptions angular interface. Fixes #7317.

### LINKED ISSUE #7317: Angular.d.ts - IComponentOptions Error - Comma separated fields
angular.d.ts - The IComponentOptions has comma separated fields which should be semi-colon separated. This is producing an error when the tsd:install runs for gulp.

### PR DESCRIPTION
**Pull request by ByronLudwig**

### CODE REVIEW

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by ByronLudwig** [comment]
Done.

**Comment by horiuchi** [comment]
@ByronLudwig I thought this pull request include no changing.

**Comment by ByronLudwig** [comment]
I merged the changes in the main branch which had a change to this file which I left as is.

**Comment by ninety7** [comment]
Any news on if this is going to be merged? I'm getting a lot of compilation errors when using angular components with the new router

**Comment by mhegazy** [comment]
@ByronLudwig, i see this change now has "0 changes" is this still needed?

**Comment by mhegazy** [comment]
does not seem to be needed. closing.

**Pull request closed without merging**
