### PR TITLE
chore(hapi): narrow types for credentials

### PR DESCRIPTION
**Pull request by SimonSchick**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/hapi/blob/master/lib/auth.js#L287 https://github.com/hapijs/hapi/blob/1c9a4f3d7c8cd583650292f4284c87ac5b935107/lib/request.js#L68
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

So this may be questionable so please be critical about it, strictly `user` and `app` do not need to be objects but are designed to be.

Also quote style!

### CODE REVIEW

**Comment by SimonSchick** [comment]
Hey @hueniverse I know you aren't super deep into TS but it's kinda hard to tell what the intended use of `credentials` and `artifacts` is, given it checks for `user`, `app` and `scope` properties..
I _think_ it was meant to be objects only but I could be wrong.

PS: I would still LOVE hapi shipping typings, they've made my (and many others) job so much easier!

**Comment by SimonSchick** [comment]
@weswigham I appreciate the quick merge but I wanted feedback from the other authors first  (as indicated by comment), this might break other peoples code.

I think we should revert this until we had a short discussion about it.

**Comment by weswigham** [comment]
Ah, sorry. I can revert and let you discuss.

**Comment by weswigham** [comment]
Or maybe I can't revert since the UI won't let me. @SimonSchick do you wanna open a revert PR and then a new PR?

**Comment by SimonSchick** [comment]
Going to wait and see if we get any bug reports.
@jhsimms @lenovouser any thoughts?

**Comment by hueniverse** [comment]
Ok... walk me through the process of adding full typings support without having to add a pre-compile step. Ping me on hapi slack and we'll figure out a plan. `artifacts` is passthrough so can be whatever the auth protocol needs (but I have only seen it used as object). `credentials` should be an object.

**Comment by Thomas-B** [comment]
Hey humans, 

Please be more careful when merging PR.
This one IS NOT a minor update, it broke my build.

**Comment by lenovouser** [comment]
@Thomas-B the `minor` version gets automatically created by the types-release, nothing we can do about it. Also, above was also already written that it was merged too early. And if it actually breaks your build - could you please post the error? 😆

**Comment by Thomas-B** [comment]
@lenovouser Really, we can't do anything about the version ? that sucks, but hey.
It's okay for my build I was extending `AuthCredentials` with an interface that  had a user property but of a different type.

I downgraded the version of my types and it works.

I read : 
> Going to wait and see if we get any bug reports.
So I spoke up.

**Comment by Thomas-B** [comment]
@SimonSchick @lenovouser  You are both right !
my main complaint is about the minor version, but if we can't do differently there is no problem.

Thanks for your kind help !

**Comment by jeremyhon** [comment]
Hi, this also broke my build. Specifically with `credentials.scope`.  I have been using a `string` for that value (which is documented in the link above) but now the build fails because it expects a `string[]`

**Pull request merged**
