### PR TITLE
Make center point optional on Point.rotate

### PR DESCRIPTION
**Pull request by NeuralChris**
Since the second parameter is optional (and most don't use it), let's let TS know that one parameter is OK.

Please fill in this template.

- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by clark-stevenson — CHANGES_REQUESTED** [review]
Thanks @NeuralChris  😃 

One thing I would change is that you don't need a new overload, you can add a `?` to center instead to make it optional.

`rotate(angle: number, center?: Point): Point;`

**Comment by RyanCavanaugh** [comment]
@NeuralChris Please address comments from the code reviewers.

**Comment by NeuralChris** [comment]
@RyanCavanaugh Alright, I've got that change pushed.

**Review by clark-stevenson — APPROVED** [review]
Awesome mate 😃

**Pull request merged**
