### PR TITLE
[jsonwebtoken] Adding generics support

### PR DESCRIPTION
**Pull request by jackall3n**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: `N/A`
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by LinusU** [comment]
This has been submitted before, and my feelings are still the same. There is a reason that you had to disable a lint in order to add this, it's not in line with the best practices of this project.

You can accomplish what you want by doing `as T` on the returned object.

I think that adding this as a type parameter gives a false sense of security that the decoded data will conform to a specific shape. This is similar to `JSON.parse` which also returns `any` instead of `T`...

I'd be happy to hear some arguments to change my mind ☺️

**Comment by jackall3n** [comment]
Hey @LinusU thanks for getting back so quickly. 

I find this dtslint rule quite controversial. The argument for enforcing the rule on input arguments makes complete sense as it becomes totally redundant when used in a single instance. 

However, enforcing the rule on return type of a method and casting using `as T` as you mentioned (and is suggested in the [last example of the rule docs](https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md)) simply moves the false sense of security while also introducing the potential for hidden bugs as shown in the tests of this package. I'll explain this below.

We know that `verify()` accepts a callback method. This [callback method](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts#L95) accepts two arguments of `err` and `decoded: object | undefined`. 

While it's possible that when defining the method body we could write someone similar to:

```typescript
verify("some-token", "some-secret", (err, decoded) => {
    const parsed = decoded as TestObject;
    console.log(parsed.foo);
});
```

What has happened here is that we've unintentionally masked that `decoded` could be `undefined`. You could argue that we could introduce `decoded === undefined` however it's very possible users might miss this, like [we're actually doing within our own tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/jsonwebtoken-tests.ts#L66)!

Now, if we were to apply a generic to the `verify()` method:

```typescript
verify<TestObject>("some-token", "some-secret", (err, decoded) => {
    console.log(decoded.foo); // Object is possibly 'undefined'. ts(2532) 
});
```

Not only is the implementation of the method slightly cleaner, but immediately on use of the `decoded` object the typescript compiler will display a warning of a possible `undefined` exception. 

By introducing this generic we've given the users 1 extra helping hand towards avoided a runtime error.

**Comment by LinusU** [comment]
> [...] simply moves the false sense of security [...]

I think that the point is that it moves it out from this project. Then if the end user wants to use `as` casting, that is up to them.

If we put this in here, we are basically doing `as T` for the user, which hides it from them.

> While it's possible that when defining the method body we could write someone similar to:

I think that the real problem here is ignoring the `err` parameter. The relationship between `err` and `decoded` here is such that exactly one of them is `undefined`, and the other one is always defined.

ref: https://github.com/auth0/node-jsonwebtoken/blob/5f10bf9957a2541828501cfecab0310908b2f62f/verify.js#L74-L76

Thus, if you properly handle `err`, `decoded` won't be `undefined`.

-----

If anything, I think that we should change the `decoded` parameter to `unknown` since that is what it will be. There is no way to know what the value will be at build time.

That also would fix the hazard of users doing `as T`, as you cannot cast `unknown` to anything without first casting it to `any`, so it would be `as any as T` which would give a heads up that it's dangerous.

Then you have two clear choices:

1) If you are absolutely sure that the decoded tokens will always be what you expect them to be, you can do an unsafe cast:

    ```ts
    interface Token { email: string }

    // ...

    const decodedToken = jwt.verify(token, secret) as any as Token
    ```

2) if you want to do a runtime check:

    ```ts
    interface Token { email: string }

    function verifyPayload (payload: any): asserts payload is Token {
      if (typeof payload !== 'object' || typeof payload.email !== 'string') throw new Error('...')
    }

    // ...

    const decodedToken = jwt.verify(token, secret)

    // Type error: email not present
    decodedToken.email

    verifyPayload(decodedToken)

    // Here everything works:
    decodedToken.email
    ```

**Comment by jackall3n** [comment]
Thanks for your time @LinusU

**Comment by LinusU** [comment]
Thank you for discussing with me ❤️ 

What do you think about returning `unknown`?

**Pull request closed without merging**
