### PR TITLE
amqplib exchange types should include all strings

### PR DESCRIPTION
**Pull request by KristjanTammekivi**
Fix for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47047  which assumed that '' | 'direct' | 'topic' | 'fanout' | 'headers' | 'match' exchange type was exchaustive, but delayed message plugin adds x-delayed-exchange exchange type for instance. 

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## amqplib ([<kbd>unpkg</kbd>](https://unpkg.com/browse/amqplib@latest/))
was missing the following properties:
1. IllegalOperationError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ffeba2505cd75a2ae64621120fd871d547558e57
</p>

**Comment by yotamshapira** [comment]
@XVincentX can you please review this PR?

**Comment by nickzelei** [comment]
@KristjanTammekivi I can approve this PR.
I have one ask though, would you mind updating the link to my github profile so that I can properly be notified? I didn't even know this PR existed, else I would have approved it 8 days ago when it was put up.

`//                 Nick Zelei <https://github.com/nickzelei>,`

**Comment by KristjanTammekivi** [comment]
> @KristjanTammekivi I can approve this PR.
> I have one ask though, would you mind updating the link to my github profile so that I can properly be notified? I didn't even know this PR existed, else I would have approved it 8 days ago when it was put up.
> 
> `// Nick Zelei <https://github.com/nickzelei>,`

Roger roger, https://github.com/KristjanTammekivi/DefinitelyTyped/commit/58406ccfe017e0356f8df031e60dcadab1498e22

**Review by nickzelei — APPROVED** [review]

**Comment by nickzelei** [comment]
> > @KristjanTammekivi I can approve this PR.
> > I have one ask though, would you mind updating the link to my github profile so that I can properly be notified? I didn't even know this PR existed, else I would have approved it 8 days ago when it was put up.
> > `// Nick Zelei <https://github.com/nickzelei>,`
> 
> Roger roger, [KristjanTammekivi@58406cc](https://github.com/KristjanTammekivi/DefinitelyTyped/commit/58406ccfe017e0356f8df031e60dcadab1498e22)

thank you! Apologies for the hiccup in the types!

**Review by andrewbranch — APPROVED** [review]

**Comment by XVincentX** [comment]
Ready to merge

**Pull request merged**
