### PR TITLE
Add definitions for W3C Generic Sensor API

### PR DESCRIPTION
**Pull request by kenchris**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by kenchris** [comment]
Sorry about the meteor mixup, it should be fixed now

**Comment by kenchris** [comment]
Do I need to do anything to get this published to npm, so that it can be installed like
```npm install @types/w3c-generic-sensor``` ?

**Comment by saabi** [comment]
Maybe I should open another issue, but I'm commenting here to begin with.

When I try to compile my code that's using the declarations I get a lot of these:
```
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts:4238:5 - error TS2687: All declarations of 'height' must have identical modifiers.
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts:4239:5 - error TS2687: All declarations of 'width' must have identical modifiers.
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts:4240:5 - error TS2687: All declarations of 'x' must have identical modifiers.
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts:4241:5 - error TS2687: All declarations of 'y' must have identical modifiers.
```

which tracing back to the lib.d.ts file is this:

```typescript
interface DOMRectInit {
    height?: number;
    width?: number;
    x?: number;
    y?: number;
}
```

while on geometry-dom it's defined as:

```typescript
    interface DOMRectInit {
        x: number;
        y: number;
        width: number;
        height: number;
    }
```

The different definitions shown here and others not shown are causing the many compilation errors.

Seeing that at least the `DOMRectInit` interface is already on lib.d.ts is geometry-dom defining anything else that's really needed?

**Comment by kenchris** [comment]
We needed DOMMatrix as well, but maybe that has been added to lib.d.ts as well?

**Comment by saabi** [comment]
Just checked, DOMMatrix is not there. 

Maybe it's worth it to just paste that single interface into this module...

**Comment by kenchris** [comment]
DOMMatrix is really part of the web platform and should really be in lib.d.ts

https://www.w3.org/TR/geometry-1/

SVG 2 also depends on DOMMatrix instead of SVGMatrix and it also supersedes the WebKitCSSMatrix

**Pull request merged**
