### PR TITLE
[sql.js] Update to 1.4

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://sql.js.org/documentation
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by hozuki — APPROVED** [review]
LGTM

**Comment by hozuki** [comment]
Ready to merge

**Comment by hozuki** [comment]
So here's a chance I would also ask a question: how can I transfer the "maintainer" status to someone else? I'll be mostly inactive on GitHub; I am neither the author, or an active user of sql.js. It is inappropriate to ask for my review of this definition in the future.

**Comment by ffflorian** [comment]
@hozuki you need to create a PR in which you remove your name from the definition file. I can then approve your PR.

**Comment by hozuki** [comment]
@ffflorian Thank you. I'll submit soon.

**Pull request merged**
