### PR TITLE
[plotly.js] rewrite `PlotRelayoutEvent` to have proper flattened keys

### PR DESCRIPTION
**Pull request by seansfkelley**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/plotly/plotly.js/issues/2843
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---
This change is [Reviewable](https://reviewable.io/reviews/definitelytyped/definitelytyped/29347)

### CODE REVIEW

**Review by szechyjs — CHANGES_REQUESTED** [review]
This does not seem correct.

PlotAxis already has a range type defined. If that is not correct, it should be addressed there, not in this interface.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plotly.js/index.d.ts#L72

**Comment by seansfkelley** [comment]
This is correct. Please read the issue I linked from the description: https://github.com/plotly/plotly.js/issues/2843

**Comment by DanielRosenwasser** [comment]
@szechyjs ping

**Review by martinduparc — APPROVED** [review]

**Review by szechyjs — CHANGES_REQUESTED** [review]
This still seems like the wrong way of doing things. Perhaps there is something I'm missing, but why would you remove the xaxis and yaxis properties in favor of just the first 2 items if PlotAxis.range?

**Comment by seansfkelley** [comment]
@szechyjs did you read the [linked ticket](https://github.com/plotly/plotly.js/issues/2843)? The maintainer explicitly says:

> But the flattened object is the intent here. See eg https://plot.ly/javascript/plotlyjs-function-reference/#plotlyrestyle ... The event data mirrors these arguments.

In my experience, one does not actually receive the object these types describe. One receives (up to) four separate keys with these string names. The [event docs](https://plot.ly/javascript/plotlyjs-events/#update-data) restate this as well.

In reading those docs I realize that I had dropped the types for `autorange`; I brought those back with the new names as described in the docs.

**Pull request closed without merging**
