### PR TITLE
Add definitions for bliss

### PR DESCRIPTION
**Pull request by NoMoreDeps**

### CODE REVIEW

**Comment by vvakame** [comment]
https://www.npmjs.com/package/blissfuljs
please rename to blissfuljs/blissfuljs.d.ts

**Comment by fskorzec** [comment]
Done.

**Comment by vvakame** [comment]
sorry for delay, happy new year!

**Comment by fskorzec** [comment]
No problem, thank you and Happy new year too !

Date: Sat, 9 Jan 2016 06:52:06 -0800

**Pull request merged**
