### PR TITLE
[jsts] Add algorithm.locate.SimplePointInAreaLocator to typings

### PR DESCRIPTION
**Pull request by jonathan-merlet-ocl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://locationtech.github.io/jts/javadoc-1.17.0/org/locationtech/jts/algorithm/locate/PointOnGeometryLocator.html
https://locationtech.github.io/jts/javadoc-1.17.0/org/locationtech/jts/algorithm/locate/SimplePointInAreaLocator.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsts ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsts@latest/))
was missing the following properties:
1. abstractFunc
1. error
1. index
1. geomgraph
1. noding

<details>
<summary>as well as these 1 other properties...</summary>
<p>triangulate</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 17a67dbc81331ea2823d897c1616db22d571a69b
</p>

**Comment by peterblazejewicz** [comment]
@jonathan-buildrz this looks legit. Do you fancy adding yourself to this specific types as an owner? 
Thanks!

**Comment by jonathan-buildrz** [comment]
@peterblazejewicz I'm not against the idea, but people that work with me may soon start contributing to those types as well. Wouldn't there be a conflict of interest if I'm able to validate those PRs as they're benefitting my work ?
If not, does that mean that if one of my PRs is tagged "Unreviewed", can I ask them to review it so that it becomes "Other approved" ?

**Comment by andrewbranch** [comment]
You’ll just be pinged for review on future PRs to these typings. No real obligation.

**Comment by peterblazejewicz** [comment]
> I suppose I need to wait for you to explicitely approve the PR before telling the bot to merge it ?

No worries, this is OSS, for me it's LGTM

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@jonathan-buildrz 
thx for the quality contribution!

**Comment by jonathan-buildrz** [comment]
Ready to merge

**Pull request merged**
