### PR TITLE
[Node]: Update http request listeners

### PR DESCRIPTION
**Pull request by vansergen**
## Motivation

```typescript
import { IncomingMessage, ServerResponse, createServer } from "node:http";
class CustomIncomingMessage extends IncomingMessage {}
class CustomServerResponse extends ServerResponse<CustomIncomingMessage> {}
createServer<CustomIncomingMessage, CustomServerResponse>({
  IncomingMessage: CustomIncomingMessage,
  ServerResponse: CustomServerResponse,
})
  .on("upgrade", (req) => {
    // $ExpectType CustomIncomingMessage
    req;
  })
  .on("request", (req, res) => {
    // $ExpectType CustomIncomingMessage
    req;
    // $ExpectType CustomServerResponse
    res;
    // $ExpectType CustomIncomingMessage
    res.req;
  });
```

## Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by vansergen** [comment]
Did anyone had a chance to look at it?

**Comment by SimonSchick** [comment]
The problem of this change is generally giving a false sense of type safety, asserting types through generics is generally considered an anti-pattern as it tends to hide the actual type assertions.

Then again any big library does this (including express, axios, etc. etc), I'm a little torn about doing it in node-core and would like other maintainers input in this.

**Comment by vansergen** [comment]
> The problem of this change is generally giving a false sense of type safety, asserting types through generics is generally considered an anti-pattern as it tends to hide the actual type assertions.

Indeed, this PR does not solve any problem but gives a tool for type safety when `http.createServer()` is used with custom `IncomingMessage/ServerResponse` classes. I believe that such behavior is desired and will be useful (generics are used just once with `http.createServer()` or `new Server()`)

```typescript
createServer(
  {
    IncomingMessage: CustomIncomingMessage,
    ServerResponse: CustomServerResponse,
  },
  (req, res) => {
    assert.ok(req instanceof CustomIncomingMessage);
    assert.ok(res instanceof CustomServerResponse);
  }
);
```

Another problem is `res.req` - it depends on the classes were used with `http.createServer()`.


```typescript
class IncomingMessage1 extends IncomingMessage {}
class IncomingMessage2 extends IncomingMessage {}
createServer({ IncomingMessage: IncomingMessage1 }, (_req, res) => {
  res.req; // $ExpectType IncomingMessage1
});
createServer({ IncomingMessage: IncomingMessage2 }, (_req, res) => {
  res.req; // $ExpectType IncomingMessage2
});
```

It seems that server creation is the right place to define types that will be used in all listeners. This PR solves those problems without any breaking changes.

> any big library does this (including express, axios, etc. etc)

It could mean that such functionality would be useful because all of them are based on the `node:http`  module.

**Comment by LinusU** [comment]
> Then again any big library does this (including express, axios, etc. etc)

I don't think Express does this?

-----

I think that since you can actually pass the `IncomingMessage` and `ServerResponse` classes to `createServer` I think that we _might_ want to support this. I am however afraid that this will inadvertently be used to hide type assertions and to create unsound code...

Maybe we could type `createServer` something like this?

```ts
function createServer(options?: Options): Server<IncomingMessage, ServerResponse<IncomingMessage>>
function createServer<T extends IncomingMessage>(options: Options & { IncomingMessage: typeof T }): Server<T, ServerResponse<T>>
function createServer<T extends ServerResponse<IncomingMessage>>(options: Options & { ServerResponse: typeof T }): Server<IncomingMessage, T>
function createServer<T extends IncomingMessage, U extends ServerResponse<T>>(options: Options & { IncomingMessage: typeof T, ServerResponse: typeof U }): Server<T, U>
```

That would save you having to manually type out the generic parameters when passing custom classes, and it would also ensure that you are actually passing the classes if you define the generic parameters.

**Comment by RyanCavanaugh** [comment]
> The problem of this change is generally giving a false sense of type safety, asserting types through generics is generally considered an anti-pattern as it tends to hide the actual type assertions.

Speaking from TS's perspective, I agree. I'd consider this a pattern of last resort. @LinusU's suggestion seemed promising

**Review by amcasey — CHANGES_REQUESTED** [review]
My understanding from the discussion above is that there's still work to do.  It would also be nice to have at least one owner sign off.

**Comment by vansergen** [comment]
> Maybe we could type `createServer` something like this?
> 
> ```ts
> function createServer(options?: Options): Server<IncomingMessage, ServerResponse<IncomingMessage>>
> function createServer<T extends IncomingMessage>(options: Options & { IncomingMessage: typeof T }): Server<T, ServerResponse<T>>
> function createServer<T extends ServerResponse<IncomingMessage>>(options: Options & { ServerResponse: typeof T }): Server<IncomingMessage, T>
> function createServer<T extends IncomingMessage, U extends ServerResponse<T>>(options: Options & { IncomingMessage: typeof T, ServerResponse: typeof U }): Server<T, U>
> ```
> 
> That would save you having to manually type out the generic parameters when passing custom classes, and it would also ensure that you are actually passing the classes if you define the generic parameters.

Indeed, we can do something like this

```typescript
type RequestListener<
  Request extends typeof IncomingMessage = typeof IncomingMessage,
  Response extends typeof ServerResponse<Request> = typeof ServerResponse<Request>
> = (req: InstanceType<Request>, res: InstanceType<Response>) => void;
function createServer<
  Request extends typeof IncomingMessage = typeof IncomingMessage,
  Response extends typeof ServerResponse<Request> = typeof ServerResponse<Request>,
>(requestListener?: RequestListener<Request, Response>): Server<Request, Response>;
function createServer<
  Request extends typeof IncomingMessage = typeof IncomingMessage,
  Response extends typeof ServerResponse<Request> = typeof ServerResponse<Request>,
>(options: ServerOptions, requestListener?: RequestListener<Request, Response>): Server<Request, Response>;
```

Does anyone agree with the suggested approach?

**Comment by vansergen** [comment]
Actually, the suggested way works modulo `res.req`

```typescript
class MyIncomingMessage extends http.IncomingMessage {
  foo: typeof foo;
}
class MyServerResponse extends http.ServerResponse<typeof MyIncomingMessage> {
  bar: typeof bar;
}
let server = http.createServer(
  { ServerResponse: MyServerResponse, IncomingMessage: MyIncomingMessage },
  reqListener,
);
```

produces the following error

```
Type 'typeof MyServerResponse' does not satisfy the constraint 'typeof ServerResponse'.
  Types of construct signatures are incompatible.
    Type 'new (req: MyIncomingMessage) => MyServerResponse' is not assignable to type 'new <Request extends typeof IncomingMessage = typeof IncomingMessage>(req: InstanceType<Request>) => ServerResponse<Request>'.
      Types of parameters 'req' and 'req' are incompatible.
        Type 'InstanceType<Request>' is not assignable to type 'MyIncomingMessage'.
          Type 'unknown' is not assignable to type 'MyIncomingMessage'.
            Property 'foo' is missing in type 'IncomingMessage' but required in type 'MyIncomingMessage'.
```

**Pull request closed without merging**
