### PR TITLE
Add Orchestrator

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by vvakame** [comment]
*orchestrator/orchestrator.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/orchestrator
  * http://bower.io/search/?q=orchestrator
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (orchestrator/orchestrator-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@tkQubo thank you for your contributions.
please rename orchestrator/orchestrator-test.ts to orchestrator/orchestrator-tests.ts

**Comment by tkQubo** [comment]
@vvakame OK I did rename orchestrator-test.ts to orchestrator-tests.ts

**Comment by vvakame** [comment]
@tkQubo thanks mate!

**Pull request merged**
