### PR TITLE
[node:util]: for `parseArgs`, setting a default makes the value defined

### PR DESCRIPTION
**Pull request by bakkot**
This just makes the types slightly more precise.

First commit is a pure refactoring, just factoring `undefined |` out of both branches of a conditional. Second commit has the actual change.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/util.html#utilparseargsconfig
- [x] (N/A) If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by bakkot** [comment]
This CI failure does not look plausibly related to my change. Given https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70070 I'm guessing it's something upstream.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/util.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 81630b7f5587b9323b9b443ac2d1ca99968e89ac
</p>

**Review by LinusU — APPROVED** [review]
Nice! 👍

**Comment by LinusU** [comment]
> [...] yet I haven't seen any reviews.

I guess it didn't register mine 😅

**Review by iisaduan — APPROVED** [review]

**Comment by bakkot** [comment]
Ready to merge

**Pull request merged**
