### PR TITLE
[atom] add missing types to autocomplete-plus + add tests

### PR DESCRIPTION
**Pull request by aminya**
Moves the two missing methods from atom-languageclient:
https://github.com/atom-community/atom-languageclient/blob/f88bf3e415546e43240c804d3f955d8db34cbc1a/typings/atom-ide/index.d.ts#L377-L390

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aminya** [comment]
> Hey @aminya,
> 
> 😒 Your PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Please consider [adding tests](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-test-editing-an-existing-package) to cover the change you're making. Including tests allows this PR to be merged by yourself and the owners of this module. This can potentially save days of time for you.

Autocomplete does not have tests in this repo.

**Comment by lierdakil** [comment]
Do we need to publish these? These are ad-hoc extensions used by atom-languageclient internally, why do you need to expose them? I mean, you might as well add `[key: string]: any;` since all autocomplete consumers might add arbitrary properties to suggestion objects (which I would argue isn't great practice, but oh well)

**Comment by aminya** [comment]
The methods are tagged as optional by `?`, which means they might not be available. This prevents abusing them if they don't exist. But when the existence check has happened that can allow others to use the methods.

**Comment by lierdakil** [comment]
You didn't answer the question though. Why do you need them? Answer "because X uses them internally" isn't a great justification for a public interface. If you know your software design, you really, _really_ don't want to put internal implementation details into a public interface, because then you're stuck with those details, and if you want to change anything, too bad, it's public now, if you want any semblance of backwards compatibility, you have to support that.

**Comment by aminya** [comment]
> You didn't answer the question though. Why do you need them? Answer "because X uses them internally" isn't a great justification for a public interface. If you know your software design, you really, _really_ don't want to put internal implementation details into a public interface, because then you're stuck with those details, and if you want to change anything, too bad, it's public now, if you want any semblance of backwards compatibility, you have to support that.

If someone wants to implement the `getSuggestions` function independent of atom-languageclient then this will be useful. 

Regarding backward compatibility, I am fine with bumping the major version when a breaking change happens (while I suspect that happens).

**Comment by lierdakil** [comment]
>  I am fine with bumping the major version

Considering we're talking about Atom, where half the ecosystem is barely supported, this isn't solving anything. Also, this doesn't change the fact that breaking changes to a public interface is a lot of work for everyone involved, which usually can be avoided.

> I think if someone wants to implement the getSuggestions function independent of atom-languageclient then this will be useful.

Why though? It's used internally by atom-languageclient. Why would it be useful to anyone doing things without atom-languageclient? I fail to understand your point.

I mean, atom-typescript also uses ad-hoc extensions to the suggestion interface too, i.e.
```ts
  replacementRange?: Atom.Range
  isMemberCompletion?: boolean
  identifier?: CompletionEntryIdentifier | string
  hasAction?: boolean
```
Should we now add those to this definition here because it might potentially be useful to someone? Well, no. This is an internal implementation detail, and has no business polluting a public interface, in my opinion.

**Comment by aminya** [comment]
Yeah, your points make sense. Should we agree on extending the original autocomplete API, so people shouldn't have to do this kind of monkey patching?

**Comment by lierdakil** [comment]
Well, a dedicated property with a generic type for application-specific data might be one option to have a rigid interface that still allows for extensions. But since we're talking about TS, where there's literally no way to enforce a rigid interface due to mandatory structural typing, ad-hoc extensions are still not only very much possible but basically expected. Also, it's not "monkey-patching", it's not actually "patching" to begin with.

So... while setting up some guidelines on adding application-specific data to suggestions is probably a good idea, those will be exactly that -- i.e. kinda optional.

If you want, I can prototype the idea with "a dedicated property with a generic type" -- this is not a one-line change though (but should be entirely backwards compatible, which is a plus), so probably entirely separate from this pull request. Actually, here's the main idea [on typescript playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwL4BQW08SyAygugA4QAiEAzglMNWOlLocbIigBUIADzABRACbAOXfAQIjqnbL1IpyAVwDmWpmGDoQjAEoQAjhr0QJYgG4RwuAshfJr0zgC5kQ0ZI9QANzOrgBGGjAw0BiM0gYg3hhYwa7IzDT0TCxsMt6UGQzMrOycKa7UUBAwwMLejGCsIFplLoj6tnCQEgCycCAacAA2gwCe3qHo6IMQfcGECsJKUCrgJPwU2rr18QCSRtBddg5gADwAgtTUg8AInfF0nXAAvBogElWg1gB8TqnuuT4ROIpDIWsgGsAdNF0LF9IZEphwGDGJs9PE8qjtoZzpdrrc4SAHmA4F85vJFMpkKp1pooViQAAhOCMCA4q43O6GInPV7vaogb6-VxSRhXOAjXxgAD8dQhTTBlTFSAAtsdUJVqsIZWk5c0Qi4wCNaNr6o09alpjAwAAZOChCCDE26sGWm12h0ACQE3WtTrNCshAAs3fbHbL-frkKwtMHbaGvT6-aBza4EINmYwAHJwVVJ+WRm6GBO+8PJsHvIo5eJ5lMuCvZdjxbqcCAAVWMJZ1EdS9eKBN6UAA1hJ0AB3EA1sHVQaQKCSyeRhAaeroZWmJWq8Dqj5a0v51JwXEcgnc7UXdn4+6PMkLJYrWdqQGiWlbAlsvGcwmPF5vD4CiQ-ECDgSIwGx0gSTIsu+x5XsSPw4JGkCiHuerzBSyxUqsfBkOQIBsLQYAvmi2Lnh+J7fryf6CkBbygUR9KQaypEwVyjzwZGjB4ZcEBgChN7odghq0MgZwgCM9Fvsxl6scSP58p8AHIE8T6EZiklHtJX5wQAPrh+E8RJ8TQZp3KkrelJCeoalGVJn7cnJVGKcpIliYZJEaXZbHBAJ4JGlZ4HxIwxmebJlH8oKylnFAUDiucrnWe5F4hSSZnmRh1JkGcGgcFQypXDxEDqugtjAO8UDBeRoW-uFikIakLLTAgAKmmWkYina0wAGKcOQDoQE1nALqkoBpsu8TqgYrCGtq-TKvaQSRiIo3vNaY7RKwnDSCM2oTFMMwgMiCUgBNm3Td4s3zVOwAztAblGDtkzTLMka6KpAWGIwAAU1BwDFyqMBi71GKYFhWDY9jgAAlIDr6BRVsEktpRXKsAUF3UFtmVSlYKvXdDDEtdjAAPIgL1jXSp9KJA94oniUd8MySS0ORqkyOo0x8VAwzWkksg2nIP0ww-PztN3dzpl8wLGjDGCXKlXsLLLHdUrfb9OYA2BsOGArBzWEc4Di2x0PILYmASOWqNKCyKvG6bpU3kQWGPt0IzntyQouIq6Yqscxh9Lo3h+00EAFow3QQHN0AAMKrvlBLjI9+0Fu84DANU0AoZGgbMmcTXosgu1PSABCEEAA) (bear in mind I've spent little time verifying the code, so probably some issues are present; I've omitted comments for size)

Now the other option is to discourage saving application-specific data in suggestion objects altogether and instead recommend the use of `WeakMap` for application-specific storage (keyed on suggestion objects naturally). I'm not sure of the performance implications, my gut tells me `WeakMap` is slower than direct property access, but it is a "better" solution in terms of isolation -- application-specific data doesn't ever "leak out" in this scenario. The catch is I don't know if autocomplete-plus ever uses something like `Object.assign` when dealing with suggestions so I don't know if this approach will work or not. On paper, it should, but there might be some weird things in ac+ code for one reason or another.

**Comment by aminya** [comment]
Your prototype looks good. But in addition to this, I was thinking about extending the autocomplete-plus API itself, so we don't have to add these ad-hoc properties. If the API itself is able to handle most of the situations, there is no need for these kinds of extensions.

**Comment by lierdakil** [comment]
If you're thinking "just add a bunch of fields to the API that aren't actually used by ac+" then it's not a good idea. The API should be concise and very clear on what's actually used by the UI. Otherwise, it's just bloat for no good reason. And trying to cram every possible edge case into the API is doomed to fail anyway, and the moment someone needs to attach another flag to suggestions for whatever reason we're back to square one. The reason I suggest `applicationData` field instead of just plain old `[key: string]: any` is twofold: a) it allows for stricter typing, and b) we're still free to extend AC+ API in a backwards-compatible manner without fear of trampling over some unfortunately named application-specific fields.

Now I don't mean to say anything we come up with here shouldn't be described in the API documentation. It absolutely should. I'm just trying to point out that adding, say `identifier` to the public API is pointless, it's just an internal identifier used by tsserver. Likewise for `hasAction`, it's an internal flag, used to decide how a given completion is actually applied (i.e. if it's a simple text substitution or some additional changes are required for consistency), it shouldn't affect UI at all.

**Comment by aminya** [comment]
Yes, I don't mean that the implementation-specific properties should be added (like the ones you mentioned for tsserver). My point is concerning the methods/properties that can be used commonly by most implementers. I don't know what those could be, but if we could find a common union, it could solve the issue.

For now, the `applicationData` property is a good solution.

**Comment by lierdakil** [comment]
What are we going to do with this PR then? I think we're more or less in agreement that `filterText` and `customReplacmentPrefix` don't affect AC+ behaviour, hence shouldn't expliclty be a part of the public AC+ API. My suggestion is to pivot this to simply adding tests, and then tackle the issue of adding `applicationData` extension in a later PR.

Alternatively, maybe close this and open a new one with just tests, so that DT maintainers don't have to wade through this lengthy discussion? Your call.

**Comment by aminya** [comment]
That sounds good. I will open a new PR with the tests.

**Comment by aminya** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51402

**Pull request closed without merging**
