### PR TITLE
Fix for building with webpack

### PR DESCRIPTION
**Pull request by LeonadoRivaldo**
I saw this issue when i was building a project for my company. 
SS : https://twitter.com/LeonardoRivald2/status/1240975182841417728/photo/1

So I'm here to propose a Fix; As I did on the project i changed those weird 'unknown' props to 'any' and it worked.

hope this help others out there.

Thanks

My reggards.

Leo

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by LeonadoRivaldo** [comment]
This is a fix to change 'unkown' to 'any' emits a error when building with webpack

**Comment by Rokt33r** [comment]
@LeonadoRivaldo 
Sorry for the late response. I think this should not be merged. Using `unknown` is intended. And the error is just from usage of old typescript which unist type doesn't support.

**Comment by LeonadoRivaldo** [comment]
> @LeonadoRivaldo
> Sorry for the late response. I think this should not be merged. Using `unknown` is intended. And the error is just from usage of old typescript which unist type doesn't support.

Thanks for the response. i hope that helps others legacy projects, and if that matter i did not knew that you could use `unknown ` as type for `unknown` types, thanks for tellig me it.

**Comment by uniqueiniquity** [comment]
Closing due to @Rokt33r 's response.

**Pull request closed without merging**
