### PR TITLE
Added definitions for milliseconds/Updated Angular-Formly

### PR DESCRIPTION
**Pull request by elmarburke**

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-formly/angular-formly.d.ts*

to author (@scatcher). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by scatcher** [comment]
@elmarburke  Can you provide some info on what the addition to angular formly allows?  I'm not against making the update but at this point I don't understand the purpose. Thanks!

**Comment by elmarburke** [comment]
Of course, the name of the module was missing, i was not able to use it in commonJS enviroments since the npm module name `angular-formly` is and not `AngularFormly` as declared by the dts. I've extended the file by the npm module name.

**Comment by scatcher** [comment]
Got it. Thanks for the input!

:+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
