### PR TITLE
feat: :sparkles: add types for react-native-slider

### PR DESCRIPTION
**Pull request by Ankan002**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I understand the intent, but it looks people are using types from module, even if not properly exported with NPM, e.g.:
https://github.com/jeanregisser/react-native-slider/pull/186
what's the relation to module `index.d.ts`?

**Comment by Ankan002** [comment]
@peterblazejewicz  Actually one of my friends tried it first and the I as well. Problem was that when we try to use it in our react native in Typescript, it starts complaining. So one way was to manually declare the types. But I thought it was not ideal so I wrote this so it gets coupled up and editors & lintors does not complain that it does not have a type declaration.

**Comment by peterblazejewicz** [comment]
Please add comments and default values, the existing `index.d.ts` does not work and cannot be used by types acquisition, but at least provides more information for users (when copied manually into TS project somehow). IDEs would use those comments from DT types. The readme contains default values that can be used with `@default` JSDoc tag.

**Comment by Ankan002** [comment]
Yeah that can be a way to deal with

**Pull request closed without merging**
