### PR TITLE
[@types/koa-router]: Parameterize `Router`

### PR DESCRIPTION
**Pull request by astashov**
After #31704 it would be useful to specify what is `Context.State` and
`Context` inside the `Router`'s handlers. For that, we could provide
a way to parameterize `Router` (also fallbacking to default `any` and
`{}` in case the generic type params are omitted).

So it would work like that:

```ts
type MyState = {foo: string}
type MyContext = {bar: string}

const app = new Koa<{}, {}>();
const router = new Router<MyState, MyContext>();
router.get('/', (ctx, next) => {
    // ctx here is Koa.ParameterizedContext<MyState, MyContext & IRouterContext<MyState, MyContext>>
    console.log(ctx.state.foo);
    ctx.body = 'Hello World!';
});
app.use<MyState, MyContext>(async (ctx, next) => {
        ctx.state.foo = "foo"
        ctx.bar = "bar";
        await next();
    })
    .use(router.routes())
    .use(router.allowedMethods())
    .use(async (ctx, next) => {
        // ctx here is Koa.ParameterizedContext<MyState, MyContext & IRouterContext<MyState, MyContext>>
        console.log(ctx.router);
        console.log(ctx.bar);
        await next();
    })
    .listen(3000);
```

But if we don't parameterize `Router`, it will work as before:

```ts
const app = new Koa();
const router = new Router();
router.get('/', (ctx, next) => {
    // ctx here is Koa.ParameterizedContext<any, IRouterContext>
    ctx.body = 'Hello World!';
});
app.use(async (ctx, next) => {
        ctx.state.foo = "foo"
        ctx.bar = "bar";
        await next();
    })
    .use(router.routes())
    .use(router.allowedMethods())
    .listen(3000);
```

What do you think?

### CODE REVIEW

**Comment by astashov** [comment]
@evenfrost make sure the `@types/koa` version >= `2.0.48`

**Comment by evenfrost** [comment]
@astashov sorry, my bad, `@types/koa` dependency was absent.

**Comment by Guillaume-Mayer** [comment]
It's nice but not fully backward compatible:

screen shot 2019-01-08 at 00 15 35

Property 'body' does not exist on type 'IRouterContext<any, {}>'

**Comment by astashov** [comment]
Ah, right, `Router.IRouterContext` probably is used a lot everywhere.
What if we leave it as is, but create another `IRouterParamContext`, which will be used to parameterize `Koa.ParameterizedContext`? Like this: e64bbedb6b8a6f1f13670a52710cad20b39b0944

**Comment by Guillaume-Mayer** [comment]
@astashov 
Maybe it would be cleaner to have:
```ts
export type RouterContext<StateT = any, CustomT = {}> = Koa.ParameterizedContext<StateT, CustomT> & {
    params: any;
    router: Router<StateT, CustomT>;
}
export interface IRouterContext extends RouterContext {}
```
So later, you can replace `Koa.ParameterizedContext<StateT, IRouterParamContext<StateT, CustomT> & CustomT>` with `RouterContext<StateT, CustomT>` like:

```ts
export interface IMiddleware<StateT = any, CustomT = {}> {
   (ctx: RouterContext<StateT, CustomT>, next: () => Promise<void>): void;
}
export interface IParamMiddleware<StateT = any, CustomT = {}> {
   (param: string, ctx: RouterContext<StateT, CustomT>, next: () => Promise<any>): any;
}
```

and then `Koa.Middleware<StateT, CustomT & Router.IRouterParamContext<StateT, CustomT>>` with `Router.IMiddleware<StateT, CustomT>` like: 

```ts
routes(): Router.IMiddleware<StateT, CustomT>;
middleware(): Router.IMiddleware<StateT, CustomT>;
```

Or maybe I'm missing something.

**Comment by astashov** [comment]
The idea behind `Koa.ParameterizedContext` was to specify what additional properties some middleware adds to `ctx` and `ctx.state`, and be able to chain middlewares with `app.use`, and infer `ctx` type for the middlewares. I could try to use sum types (like instead of `Koa.ParameterizedContext<StateT, CustomT>` it would be `Koa.ParameterizedContext<StateT> & CustomT`) everywhere, but IMHO because `CustomT` was not part of `Koa.ParameterizedContext`, it would be easier to forget it and lose it along the way.

`koa-router` is a middleware, that adds `params` and `router` to `ctx`. So, to be consistent, it's `ctx` could be described as `Koa.ParameterizedContext<T, U & {params: any, router: Router}>`. If we make it `Koa.ParameterizedContext<T, U> & {param: any, router: Router}`, then it wouldn't be consistent with other middlewares.

That also allows us to do this:

```ts
app
  .use(router.routes())
  .use(router.allowedMethods())
  .use((ctx, next) => {
    // ctx here is Koa.ParameterizedContext<T, U & {param: any, router: Router<T, U>}>
    // so we could do this:
    console.log(ctx.router);
  });
```

We probably could change it so we use sum type instead of generic type for `CustomT`, but that would also require changes in `@types/koa`, and IMHO having `CustomT` as a parameter of `Koa.ParameterizedContext` is a bit more convenient.

Does it make sense? What do you think?

**Comment by Guillaume-Mayer** [comment]
Would that be ok then:

```ts
export type RouterParamContext<StateT = any, CustomT = {}> = Koa.ParameterizedContext<StateT, CustomT & {
  params: any;
  router: Router<StateT, CustomT>;
}>
export interface IRouterContext extends RouterParamContext {}
```

In the code you wrote, ctx would be `Koa.ParameterizedContext<T, U & {
    params: any;
    router: Router<T, U>;
}>` instead of `Koa.ParameterizedContext<T, U & Router.IRouterParamContext<T, U>>` which seems fine.

**Comment by astashov** [comment]
If `RouterParamContext` will be `Koa.ParameterizedContext`, then in the middlewares the `ctx` type would be:

```ts
Koa.ParameterizedContext<StateT, CustomT & Koa.ParameterizedContext<StateT, CustomT & {params: any, router: Router<StateT, CustomT>}>
```

which is redundant - why to have `Koa.ParameterizedContext` inside of `Koa.ParameterizedContext`? :)

What if we do this:

```ts
export interface IRouterParamContext<StateT = any, CustomT = {}> {
    /**
     * url params
     */
    params: any;
    /**
     * the router instance
     */
    router: Router<StateT, CustomT>;
}

export interface IRouterContext extends Koa.ParameterizedContext<any, IRouterParamContext> {}
```

We reuse `IRouterParamContext`, and keep `IRouterContext` inherited from `Koa.ParameterizedContext`. What do you think? See e1a1c48e45b5f4a3f84bc18ffa3a568cc5cc9e66

**Comment by astashov** [comment]
Oh wait! I think I misunderstood you. Did you mean this? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31926/commits/b9076f450477a4a72cb52c24355fa7819967df21

**Comment by Guillaume-Mayer** [comment]
Yes! This would reduce redundancy, here is the full file I have locally so you could give it a look:

```ts
// Type definitions for koa-router v7.x
// Project: https://github.com/alexmingoia/koa-router#readme
// Definitions by: Jerry Chin <https://github.com/hellopao>
//                 Pavel Ivanov <https://github.com/schfkt>
//                 JounQin <https://github.com/JounQin>
//                 Romain Faust <https://github.com/romain-faust>
//                 Guillaume Mayer <https://github.com/Guillaume-Mayer>
//                 Andrea Gueugnaut <https://github.com/falinor>
// Definitions: https://github.com/hellopao/DefinitelyTyped
// TypeScript Version: 2.3

/* =================== USAGE ===================

    import * as Router from "koa-router";
    var router = new Router();

 =============================================== */


import * as Koa from "koa";

declare namespace Router {
    export interface IRouterOptions {
        /**
         * Prefix for all routes.
         */
        prefix?: string;
        /**
         * Methods which should be supported by the router.
         */
        methods?: string[];
        routerPath?: string;
        /**
         * Whether or not routing should be case-sensitive.
         */
        sensitive?: boolean;
        /**
         * Whether or not routes should matched strictly.
         *
         * If strict matching is enabled, the trailing slash is taken into
         * account when matching routes.
         */
        strict?: boolean;
    }

    export type RouterContext<StateT = any, CustomT = {}> = Koa.ParameterizedContext<StateT, CustomT & {
        /**
         * url params
         */
        params: any;
        /**
         * the router instance
         */
        router: Router<StateT, CustomT>;
    }>

    // For backward compatibility IRouterContext needs to be an interface
    export interface IRouterContext extends RouterContext {}

    export interface IMiddleware<StateT = any, CustomT = {}> {
        (
            ctx: RouterContext<StateT, CustomT>,
            next: () => Promise<void>
        ): void;
    }

    export interface IParamMiddleware {
        (param: string, ctx: RouterContext, next: () => Promise<any>): any;
    }

    export interface IRouterAllowedMethodsOptions {
        /**
         * throw error instead of setting status and header
         */
        throw?: boolean;
        /**
         * throw the returned value in place of the default NotImplemented error
         */
        notImplemented?: () => any;
        /**
         * throw the returned value in place of the default MethodNotAllowed error
         */
        methodNotAllowed?: () => any;
    }

    export interface ILayerOptions {
        name: string;
        sensitive?: boolean;
        strict?: boolean;
    }

    export interface IUrlOptionsQuery {
        query: object | string;
    }

    export interface IRoutesMatch {
        path: Layer[];
        pathAndMethod: Layer[];
        route: boolean;
    }

    export class ParamName {
        asterisk: boolean;
        delimiter: string;
        name: string;
        optional: boolean;
        partial: boolean;
        pattern: string;
        prefix: string;
        repeat: string;
    }

    export class Layer {
        opts: ILayerOptions;
        name: string;
        methods: string[];
        paramNames: ParamName[];
        stack: Router.IMiddleware[];
        regexp: RegExp;
        path: string;

        constructor(path: string | RegExp, methods: string[], middleware: Router.IMiddleware, opts?: ILayerOptions);
        constructor(path: string | RegExp, methods: string[], middleware: Array<Router.IMiddleware>, opts?: ILayerOptions);

        /**
         * Returns whether request `path` matches route.
         */
        match(path: string): boolean;

        /**
         * Returns map of URL parameters for given `path` and `paramNames`.
         */
        params(path: string | RegExp, captures: string[], existingParams?: Object): Object;

        /**
         * Returns array of regexp url path captures.
         */
        captures(path: string): string[];

        /**
         * Generate URL for route using given `params`.
         */
        url(params: Object): string;

        /**
         * Run validations on route named parameters.
         */
        param(param: string, fn: Router.IMiddleware): Layer;

        /**
         * Prefix route path.
         */
        setPrefix(prefix: string): Layer;
    }
}

declare class Router<StateT = any, CustomT = {}> {
    params: Object;
    stack: Array<Router.Layer>;

    /**
     * Create a new router.
     */
    constructor(opt?: Router.IRouterOptions);

    /**
     * Use given middleware.
     *
     * Middleware run in the order they are defined by `.use()`. They are invoked
     * sequentially, requests start at the first middleware and work their way
     * "down" the middleware stack.
     */
    use(...middleware: Array<Router.IMiddleware<StateT, CustomT>>): Router<StateT, CustomT>;
    use(
        path: string | string[] | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP get method
     */
    get(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    get(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP post method
     */
    post(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    post(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP put method
     */
    put(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    put(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP link method
     */
    link(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    link(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP unlink method
     */
    unlink(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    unlink(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP delete method
     */
    delete(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    delete(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * Alias for `router.delete()` because delete is a reserved word
     */
    del(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    del(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP head method
     */
    head(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    head(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP options method
     */
    options(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    options(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * HTTP path method
     */
    patch(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    patch(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * Register route with all methods.
     */
    all(
        name: string,
        path: string | RegExp,
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;
    all(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
    ): Router<StateT, CustomT>;

    /**
     * Set the path prefix for a Router instance that was already initialized.
     */
    prefix(prefix: string): Router<StateT, CustomT>;

    /**
     * Returns router middleware which dispatches a route matching the request.
     */
    routes(): Router.IMiddleware<StateT, CustomT>;

    /**
     * Returns router middleware which dispatches a route matching the request.
     */
    middleware(): Router.IMiddleware<StateT, CustomT>;

    /**
     * Returns separate middleware for responding to `OPTIONS` requests with
     * an `Allow` header containing the allowed methods, as well as responding
     * with `405 Method Not Allowed` and `501 Not Implemented` as appropriate.
     */
    allowedMethods(
        options?: Router.IRouterAllowedMethodsOptions
    ): Router.IMiddleware<StateT, CustomT>;

    /**
     * Redirect `source` to `destination` URL with optional 30x status `code`.
     *
     * Both `source` and `destination` can be route names.
     */
    redirect(source: string, destination: string, code?: number): Router<StateT, CustomT>;

    /**
     * Create and register a route.
     */
    register(
        path: string | RegExp,
        methods: string[],
        middleware: Router.IMiddleware<StateT, CustomT>,
        opts?: Object
    ): Router.Layer;

    /**
     * Lookup route with given `name`.
     */
    route(name: string): Router.Layer;
    route(name: string): boolean;

    /**
     * Generate URL for route. Takes either map of named `params` or series of
     * arguments (for regular expression routes)
     *
     * router = new Router();
     * router.get('user', "/users/:id", ...
     *
     * router.url('user', { id: 3 });
     * // => "/users/3"
     *
     * Query can be generated from third argument:
     *
     * router.url('user', { id: 3 }, { query: { limit: 1 } });
     * // => "/users/3?limit=1"
     *
     * router.url('user', { id: 3 }, { query: "limit=1" });
     * // => "/users/3?limit=1"
     *
     */
    url(name: string, params: any, options?: Router.IUrlOptionsQuery): string;
    url(name: string, params: any, options?: Router.IUrlOptionsQuery): Error;

    /**
     * Match given `path` and return corresponding routes.
     */
    match(path: string, method: string): Router.IRoutesMatch;

    /**
     * Run middleware for named route parameters. Useful for auto-loading or validation.
     */
    param(param: string, middleware: Router.IParamMiddleware): Router<StateT, CustomT>;

    /**
     * Generate URL from url pattern and given `params`.
     */
    static url(path: string | RegExp, params: Object): string;
}

export = Router;
```

**Comment by astashov** [comment]
Looks great!
I've pushed your code, with 2 little modifications:
* Instead of defining `IMiddleware` as a function, I expressed it through `Koa.Middleware`, like:

```ts
export type IMiddleware<StateT = any, CustomT = {}> =
        Koa.Middleware<StateT, CustomT & IRouterParamContext<StateT, CustomT>>
```

* I think it's a bit more readable if we extract `params` and `router` into a named interface, instead of just inline type - so I did that:

```ts
export interface IRouterParamContext<StateT = any, CustomT = {}> {
  params: any;
  router: Router<StateT, CustomT>;
}
```

Looks good?

**Review by Guillaume-Mayer — APPROVED** [review]
Looks nice to me, thanks!

**Comment by Guillaume-Mayer** [comment]
Hi @astashov, could you modify the router functions (get, post, etc..) so when chaining, the state & custom type evolves, for example:
```ts
type KState = {foo: string};
type KCustom = {bar: string};

const testMiddleware = (ctx: Koa.ParameterizedContext<KState, KCustom>) => {
    ctx.state.foo = ""
    ctx.bar = ""
}

new Router()
    .get('/before', async (ctx) => {
      // ctx type is: 
      // Koa.ParameterizedContext<any, Router.IRouterParamContext<any, {}>>
    })
    .get('/', testMiddleware)
    .get('/after', async (ctx) => {
      // ctx type is now: 
      // Koa.ParameterizedContext<KState, KCustom & Router.IRouterParamContext<KState, KCustom>>
      ctx.state.foo = ""
      ctx.bar = ""
    })
```

you could use something like that as a signature:
```ts
    get<NewStateT extends StateT = StateT, NewCustomT extends CustomT = CustomT>(
        path: string | RegExp | (string | RegExp)[],
        ...middleware: Array<Router.IMiddleware<NewStateT, NewCustomT>>
    ): Router<NewStateT, NewCustomT>;
```
It should help with ##32006

**Comment by astashov** [comment]
Let's discuss it there, in #32006, and create a separate PR for that if needed, okay?

**Comment by Guillaume-Mayer** [comment]
Yea, sure, let's wait this one is merged first

**Comment by astashov** [comment]
@Guillaume-Mayer Do you know how long it usually takes to merge a PR here?

**Comment by Guillaume-Mayer** [comment]
@astashov Not really, other times it was faster, but I have a short experience

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
