### PR TITLE
Remove @types/chokidar declerations

### PR DESCRIPTION
**Pull request by skovy**
Run: `npm run not-needed -- chokidar 2.1.2 https://github.com/paulmillr/chokidar chokidar`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

Additional Links:
- `chokidar` pull request: https://github.com/paulmillr/chokidar/pull/801
- `chokidar` issue: https://github.com/paulmillr/chokidar/issues/794
- `chokidar@2.1.2`: https://www.npmjs.com/package/chokidar/v/2.1.2
- `choikdar` CHANGELOG: https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md#chokidar-212-feb-18-2019

### CODE REVIEW

**Comment by skovy** [comment]
This pull request is currently blocked on this pull request: https://github.com/Microsoft/types-publisher/pull/580

**Review by felixfbecker — APPROVED** [review]

**Comment by skovy** [comment]
@felixfbecker any ideas on how to get https://github.com/Microsoft/types-publisher/pull/580 merged to unblock this PR?

**Comment by felixfbecker** [comment]
No, I don’t have permissions 🤷🏻‍♂️
Ping a maintainer?

**Comment by sandersn** [comment]
@skovy Assign the whitelist-update PR to me. I need to add this to the README because otherwise it gets lost in a sea of notifications.

**Pull request merged**
