### PR TITLE
Add NavgationComponentProps<T>

### PR DESCRIPTION
**Pull request by huhuanming**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
```TypeScript
interface IProps extends NavgationComponentProps {
   customA: number
}

constPage = (props: IProps) => <View />
```
These changes will help us a lot.

**Comment by huhuanming** [comment]
@mhcgrq

**Comment by mhcgrq** [comment]
Great! That's wonderful.
Although, considering this: `export type NavigationNavigateActionCreator = (options: NavigationNavigateAction) => NavigationNavigateAction;`

According to the [source code](https://github.com/react-community/react-navigation/blob/master/src/addNavigationHelpers.js), the param of `NavigationNavigateActionCreator` named `options` is an object _without_ a `type` property, but the definition of the `NavigationNavigateAction` do have an optional property named `type`, which is a little different. And the return value is a boolean. Also, the param of `NavigationBackActionCreator ` is optional.

Any idea?

**Comment by huhuanming** [comment]
But it exsits in the TypeDefinition file.
`https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js`
And you could modifying it while it is in use.

PS. 😳 才发现也是中国人呢。。。确实可以在使用的时候修改诶，详情可以看上面链接中的链接文件，基本上这个定义文件是抄的上面这个 FlowType的 文件里面的，几乎一模一样。

**Comment by mhcgrq** [comment]
Yep~ But I think it's better to use English to convenient for other people.

As far as I know, there are two kind of 'actions'. Let's look at the `NavigateAction `. One is which take a param and return a standard action, when we write: 
```
import { NavigationActions } from 'react-navigation';

NavigationActions.navigate({ ... });
```
source code is [here](https://github.com/react-community/react-navigation/blob/master/src/NavigationActions.js), even through this file has imported `NavigationAction ` from `TypeDefinition.js`, they didn't use it.
Notice this action's type is defined both in `TypeDefinition.js` and our `NavigationNavigateAction `.

The other is the one which take a param and automatically dispatch it then return a boolean, which when we write in a component:
```
this.props.navigation.navigate({ ... });
```
source code is [here](https://github.com/react-community/react-navigation/blob/master/src/addNavigationHelpers.js)

So, the former can be typed as `navigate(option: NavigationNavigateActionWithoutType): NavigationNavigateAction`, and the other is `navigate(option: NavigationNavigateActionWithoutType): boolean`.

What do you think?

**Comment by huhuanming** [comment]
I will end up lost in confusion.

`this.props.navigation.navigate({ ... });`

it's still the standard action, and the` navigation.dispatch` will dispatch the action.
I don't think the return value is boolean.

or did I misunderstand it？

**Comment by mhcgrq** [comment]
```
// addNavigationhelpers.js
navigate: (
      routeName: string,
      params?: NavigationParams,
      action?: NavigationAction
    ): boolean =>        // <-- here
      navigation.dispatch(
        NavigationActions.navigate({
          routeName,
          params,
          action,
        })
      ),
```

**Comment by huhuanming** [comment]
thx, I got it.
You are really clever and careful!

**Comment by huhuanming** [comment]
@mhcgrq

**Review by mhcgrq — APPROVED** [review]

**Comment by mhcgrq** [comment]
👍
That's a nice work.

**Comment by huhuanming** [comment]
@alloy  could you help me merge it?

**Comment by alloy** [comment]
Sure thing 👍

**Pull request merged**
