### PR TITLE
[react-native] Remove Deprecated & Add Deprecation Notices

### PR DESCRIPTION
**Pull request by azizhk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/master/index.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by azizhk** [comment]
Ah, so I guess I can't delete exports because tests will fail for other packages.

**Comment by alloy** [comment]
The parts that break in other packages should just be removed, if at all feasible, this has been done in the past.

Ideally DT would allow us to specify what versions of dependent types packages they support, but right now that’s not a thing.

**Review by ca057 — COMMENTED** [review]
I’m not sure how this was handled previously, but wouldn’t it make sense to remove the APIs which were removed from React Native also from the types instead of just adding a deprecation notice? It’s not deprecated, it’s not there anymore, right?

For the parts which will be removed in a future release I agree, adding the deprecation notice makes a lot of sense! :)

**Comment by azizhk** [comment]
I did that in the beginning. See the first commit. But a bunch of other packages started breaking. (Like styled-components etc.)
So I added them back.
Is there a way to pin down version in those packages? If so then I think I will be able to do like you said @ca057.

**Comment by ca057** [comment]
> I did that in the beginning. See the first commit. But a bunch of other packages started breaking. (Like styled-components etc.)
> So I added them back.
> Is there a way to pin down version in those packages? If so then I think I will be able to do like you said @ca057.

Hm, I’m honestly not sure how this would work properly. The typings already declare a version, but I have no experience in how this interoperates with other packages. Maybe someone else has more insights?

**Comment by alloy** [comment]
> The parts that break in other packages should just be removed, if at all feasible, this has been done in the past.
> 
> Ideally DT would allow us to specify what versions of dependent types packages they support, but right now that’s not a thing.

As I mentioned, there is no way to specify version constraints at the moment. Please remove the parts from other packages that rely on these removed APIs, we have done this in the past 👍

**Review by weswigham — APPROVED** [review]

**Pull request merged**
