### PR TITLE
@types/plotly.js Added histfunc and added y and z to hoverinfo

### PR DESCRIPTION
**Pull request by tempaccount-m**

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. register
1. Icons
1. Fx
1. Snapshot

<details>
<summary>as well as these 2 other properties...</summary>
<p>PlotSchema, Queue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 022d0d1bdf49abbc63ab343963213b4e7bd2cac2
</p>

**Comment by tempaccount-m** [comment]
#45827

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@tempaccount-m thx for the update!

**Comment by tempaccount-m** [comment]
fixes #45827

**Pull request merged**
