### PR TITLE
Add typings for static-eval npm and ejs npm

### PR DESCRIPTION
**Pull request by benliddicott**
Added two typings.

static-eval for https://github.com/substack/static-eval

This can evaluate javascript expressions supposedly in a safe way, for use e.g. in allowing user-submitted queries.

ejs

Embedded JavaScript. It's a little bit like ASP or ERB.

### CODE REVIEW

**Comment by vvakame** [comment]
*ejs/ejs.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/ejs
  * http://bower.io/search/?q=ejs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (ejs/ejs-tests.ts or others)
* [ ] pass the Travis-CI test?

---

*static-eval/static-eval.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/static-eval
  * http://bower.io/search/?q=static-eval
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (static-eval/static-eval-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
please check with --noImplicitAny option

**Comment by benliddicott** [comment]
@vvakame Sorry, first time - fixed now (I think).

* Now passing npm test and -noimplicitany
* Added JSDoc comments
* Added type to static-eval evaluate first argument.

**Comment by benliddicott** [comment]
@vvakame

Is there anything else I need to do? Thanks.

**Comment by vvakame** [comment]
@benliddicott it merged! thanks :+1:

**Pull request merged**
