### PR TITLE
Pouchdb core update

### PR DESCRIPTION
**Pull request by filionf**
Please fill in this template.

- [types-2.0] Prefer to make your PR against the `master` branch.
- [ok ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ok] Test the change in your own code.
- [ ok] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ok] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ok] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

@trubit 
@AGBrown
@geppy
@fredgalvao

### CODE REVIEW

**Comment by filionf** [comment]
Base branch was wrong when CI was run. Trying to rebuild by closing & re-opening.

**Comment by andy-ms** [comment]
The test failures you're getting should be fixed on `master`, so rebase to target that.

**Comment by trubit** [comment]
Query should be in standalone plugin and it is already implemented here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13024

**Comment by filionf** [comment]
@andy-ms I am working of the types-2.0 branch and still getting errors. Is the failure related? The error seem to be from a previous commit as well, but not merged into types-2.0 yet.

**Comment by andy-ms** [comment]
The error is in `vis`, which only exists on the `types-2.0` branch (and is being fixed by #13399). Rebase onto `master` to fix. We prefer `master` as of #13233.

**Comment by filionf** [comment]
Got it. Thanks.
Closing this PR to be redone off master.

**Pull request closed without merging**
