### PR TITLE
Add missing configuration options & tests to angular-bootstrap-ui

### PR DESCRIPTION
**Pull request by ChrisMBarr**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/angular-ui/bootstrap/tree/master/src/datepicker/docs
https://github.com/angular-ui/bootstrap/tree/master/src/datepickerPopup/docs
https://github.com/angular-ui/bootstrap/tree/master/src/dropdown/docs
https://github.com/angular-ui/bootstrap/tree/master/src/pager/docs
https://github.com/angular-ui/bootstrap/tree/master/src/pagination/docs
https://github.com/angular-ui/bootstrap/tree/master/src/timepicker/docs
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by xt0rted** [comment]
This looks ok to me but I'm going to defer to @ry8806 since he's more familiar with this typing now than I am.

**Comment by ry8806** [comment]
The defaults for most of the values don't match the defaults in the links provided (or the docs at https://angular-ui.github.io/bootstrap/#/timepicker)

could these be changed so they match? then i'll mark as good 😄

**Comment by chrismbarr** [comment]
The ones I added should match the defaults, but I didn't check that the already existing ones had matching values.  Are you saying that it's just the values for timepicker that don't match?  I can make the change later tonight.

**Comment by ry8806** [comment]
oooppppss, sorry, I was looking at the tests  😭 

going to blame it on the jet lag!! good work mate, sorry for being an idiot!!

**Comment by ry8806** [comment]
👍

**Comment by chrismbarr** [comment]
This all appears to be good to merge now, and the authors have approved of it.

Can someone please merge this?  @horiuchi maybe?

**Comment by DanielRosenwasser** [comment]
Sorry 'bout that - thanks for the PR!

**Pull request merged**
