### PR TITLE
[googlemaps] Enable and fix simple rules

### PR DESCRIPTION
**Pull request by demensky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [ ] ~~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~~
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
Just curious, what error does dt-header give for this package?

**Comment by demensky** [comment]
@sandersn

```
ERROR: 3:31  dt-header  Error parsing header. Expected: /\<https\:\/\/github\.com\/([a-zA-Z\d\-]+)\>/. See: https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md
```

**Comment by sandersn** [comment]
Thanks @demensky. I'll take another look to decide whether that rule is too strict.

**Comment by demensky** [comment]
@sandersn, I don’t think this rule is too strict.
As I understand it, this header uses @typescript-bot to ping people.
I just don’t know what to replace it with. The link indicated in it leads to:

image

Maybe we just remove this author?

**Comment by sandersn** [comment]
Oops, I was confused. I thought it was the project url that had to be on github. A username on github is a fairly sensible requirement for contributing. If all the other authors agree with you, we can remove Folia A/S, which appears to be a corporation anyway.

**Comment by demensky** [comment]
@sandersn. What to do here?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0e7421f1c77ecd2a06630f5ba6bfda96328538bc/types/googlemaps/index.d.ts#L22-L26

**Comment by sandersn** [comment]
I would leave it. I'm not too sure of the legal issues around type definitions, but removing a licence seems bad.

**Comment by demensky** [comment]
@sandersn, done #37411

**Pull request merged**
