### PR TITLE
Leaflet: Add private methods and properties

### PR DESCRIPTION
**Pull request by jambonrose**
The goal is to make writing plugins easier for developers by adding
private methods and properties.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

References for changes:

- [`_map` is created in the `_layerAdd` method of `Layer.js`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/Layer.js#L99)
- the `Coords` class does not exist, Leaflet effectively uses a [`Point` class with an extra `z` property, created in `GridLayer.js`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L674). Being able to use this type is necessary if overriding `createTile` in either `GridLayer` or `TileLayer`.
- [The `_tileCoordsToKey` code is pretty self-explanatory](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L755) and demonstrates the utility of the `Coords` interface
- [`_this.tiles` is first created as an empty object in `GridLayer.js`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L160). When creating a tile, [a property in the object is assigned the `el`, `coords`, and `current` properties](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L829). The [`active`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L868) and [`loaded`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L862) properties are set later if the tile image loads. Finally, if a tile is not pruned during the pruning stage, it will have the [`retain`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L426) property set.
- [`this._tileZoom` is set in `GridLayer`'s `_setView`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L557) according to the zoom parameter, which is a number (see [here](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L525) as an example of a number, following the definition of `Map.getZoom()`)
- [_getZoomForUrl](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/TileLayer.js#L203)
- [`GridLayer`'s `createTile`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/GridLayer.js#L261). Here is [`createTile` on `TileLayer`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/TileLayer.js#L130) for reference.
- [_abortLoading](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/TileLayer.js#L222)

### CODE REVIEW

**Comment by jambonrose** [comment]
No @typescript-bot ? Pinging @RyanCavanaugh !

Requesting review from @alejo90 and @atd-schubert .

**Comment by jambonrose** [comment]
Hi alejo90 - that makes a lot of sense to me! I'll update the PR later today.

I'll make all of the properties/methods starting with `_` protected.

**Comment by jambonrose** [comment]
@alejo90 - Thanks again for the review.

I've just updated the PR, so it is now ready for a second round of review.

I `protected` the new (internal) properties. I also realized I'd put `createTile` as a property on `TileLayer`, when it should instead be on `GridLayer` (as I documented above) and so therefore moved it.

Please let me know if you have any more changes and I'll update the PR.

**Review by alejo90 — APPROVED** [review]
Looks good to me. Thanks for your contribution.

**Review by atd-schubert — APPROVED** [review]

**Pull request merged**
