### PR TITLE
Made bunyan typing conform to the way the module was written

### PR DESCRIPTION
**Pull request by alejo90**
When I tried to extend the `Logger` class, I got runtime errors saying something on the lines of `unable to extend undefined`. I checked `bunyan`'s source code and noticed that `module.exports` was being used and that, therefore, the definition needed no be updated to account for that fact. After these changes, extending `Logger` becomes possible.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js

### CODE REVIEW

**Comment by andy-ms** [comment]
Tests are failing because #13717 was merged in. You'll have to rebase to bring in those changes, then fix `browser-bunyan/index.d.ts`. I suggest:
```ts
import bunyan = require("bunyan");
declare module "bunyan" {
    export function ConsoleFormattedStream(): void;
}
export = bunyan;
```

**Comment by alejo90** [comment]
Thanks, @andy-ms. Build fixed.

**Comment by alejo90** [comment]
Bump.

**Comment by lholznagel** [comment]
I don´t think it's good to force people to use bunyan.
Even if you don´t want to use the logger you need to install it.

If you don´t install it you get errors:
`node_modules/@types/restify/index.d.ts(199,10): error TS2304: Cannot find name 'Logger'`

**Pull request merged**
