### PR TITLE
[next-server] dynamic module typings revamp

### PR DESCRIPTION
**Pull request by resir014**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33163#discussion_r258331962
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by resir014** [comment]
Accidentally pressed "Create pull request" earlier than I wanted to, so here goes 🤦‍♀️

Continuing the discussion with @joaovieira  [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33163#discussion_r258331962), this PR *tries* to improve the type-safety of dynamic imports when using the mapped format.

This employs a workaround where we define the props of each component imported into a mapped props, then we include it in a separate generic type.

Example:

```
// For type safety, define component type in a mapped interface, and pass it into the
// second generic.
interface MappedModuleProps {
    Hello1: Hello1Props;
    Hello2: Hello2Props;
}

// Global bundle props that are used in the outer dynamic component.
interface BundleComponentProps {
    foo: string;
    bar?: boolean;
}

const HelloBundle = dynamic<BundleComponentProps, MappedModuleProps>({
    modules: () => {
        const components = {
            Hello1: () => import('./hello1'),
            Hello2: () => import('./hello2')
        };

        return components;
    },
    render: (props, { Hello1, Hello2 }) => (
        <div>
            <h1>{props.foo}</h1>
            <Hello1 foo />
            <Hello2 bar={props.bar} />
        </div>
    )
});
const helloBundleJSX = <HelloBundle foo="bar" />;

**Comment by resir014** [comment]
`dtslint` seems to be tripping up on `typescript@next`:

```
Error: Errors in typescript@next for external dependencies:
../react/index.d.ts(30,22): error TS2307: Cannot find module 'csstype'.
```

**Review by scottdj92 — APPROVED** [review]

**Comment by scottdj92** [comment]
Nice work 💯 

As for the CI build tripping up on TS@next, do the tests pass locally? I remember I was updating the types locally and had to import the csstype into my files in order for the test to pass, which is weird because react's types import it but 🤷‍♂️

**Comment by resir014** [comment]
@scottdj92 

> As for the CI build tripping up on TS@next, do the tests pass locally?

Fails locally as well. Weird.

**Comment by resir014** [comment]
🤦‍♀️ I realised I forgot to push the changes that reflect my edit. Hope you don't mind taking another look @scottdj92.

**Comment by scottdj92** [comment]
nice work, still approved

**Pull request merged**
