### PR TITLE
Add export

### PR DESCRIPTION
**Pull request by uiii**
Fix '.../node_modules/@types/fingerprintjs2/index.d.ts' is not a module.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by uiii** [comment]
Please help, I don't know what is wrong. I tried it in my code and it works fine. I have `typescript@2.6.2`

**Comment by DanielRosenwasser** [comment]
You've broken the tests which expect a global to be available. Try adding an

```ts
export as namespace Fingerprint2;
```

below the `export = ...`

**Comment by curtstate** [comment]
Sorry, I just now saw this...

I'll look at this

**Comment by curtstate** [comment]
So why do you want to export it as a module ?

Fingerprint2 is a global javascript object

**Comment by uiii** [comment]
Ah, I didn't realized the FingertprintJS2 itself doesn't export anything. I was doing `import Fingerprint from 'fingerprintjs2'` in my code. So I should instead do just `import 'fingerprintjs2'` and use the `Fingerprint2` directly later?

**Comment by curtstate** [comment]
That is what I do in my code, and I’m currently writing an app for work that uses this library.

However, I also include the script in the page’s scripts simply because it’s easier to do that. My typescript build in angular complains when I don’t and it’s because angular-cli  and webpack doesn’t include the script in its bundle unless I explicitly include it on the page’s scripts.

**Comment by curtstate** [comment]
I do this `import "fingerprintjs2";` in the files I use the fingerprintjs2 library.
this will make typescript happy but will not include the js library itself, which is why I also added the lib to my page's scripts.

**Comment by uiii** [comment]
I'm experimenting with it and it looks like FingerprintJS2 accually export the main object, see https://github.com/Valve/fingerprintjs2/blob/fb6fa096ac9e961b9e25268561c2c3d40f2b983b/fingerprint2.js#L21

You are right that if I just `import 'fingerprintjs2'` with webpack, the library is not loaded at all. But if I use a imoprt variable `import Fingerprint from 'fingerprintjs2'` it is imported and the FPJS2 object is assigned to that variable (note I didn't call the variable same as the global object).

**Comment by curtstate** [comment]
so it works by using the form:

`import FingerprintVar from 'fingerprintjs2'` ?

**Comment by DanielRosenwasser** [comment]
It's a UMD module. It's available via `module.exports` when CommonJS/AMD are used:

```
export = ...
```

and it's also available as a global namespace-like value:

```
export as namespace ...
```

**Comment by uiii** [comment]
@curtstate Yes it works.
@DanielRosenwasser I add that to see if it will pass

**Comment by uiii** [comment]
So the tests passed, @curtstate I think you can marge this PR.

**Review by curtstate — APPROVED** [review]
Thanks for these changes, its a nice improvement on my initial attempt

**Comment by curtstate** [comment]
You have my approval but this needs to be merged in by someone with write access to this repo.

**Review by curtstate — APPROVED** [review]

**Pull request merged**
