### PR TITLE
Add bardjs definitions

### PR DESCRIPTION
**Pull request by thaliaarchi**
Adds type definitions for bardjs. See issue [#4730](https://github.com/borisyankov/DefinitelyTyped/issues/4730)

### CODE REVIEW

**Comment by vvakame** [comment]
*bardjs/bardjs.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/bardjs
  * http://bower.io/search/?q=bardjs
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (bardjs/bardjs-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by TepigMC** [comment]
I have added types to every variable and return type, I made the variables more specific, and I added the comments from this bardjs source.

I still don't know what to do for the test file, but the Travis-CI test passes.

**Comment by horiuchi** [comment]
@TepigMC [test file](http://definitelytyped.org/guides/contributing.html#tests) is used by checking the use case.
I would need test file for regression test.

**Comment by TepigMC** [comment]
@horiuchi, @SuperheroicCoding, and @vvakame, the pull request is ready to be merged. I have written tests and the Travis CI build passed.

**Comment by vvakame** [comment]
@TepigMC thanks mate!

**Pull request merged**
