### PR TITLE
curry right fixed  #16867

### LINKED ISSUE #16867: lodash curry-right not typed properly
curryRight<T1, T2, T3, R>(func: (t1: T1, t2: T2, t3: T3) => R):
            CurriedFunction3<T3, T2, T1, R>; 
this only work in case (3)(2)(1)
in (2,3)(1)
and (1 2 3) 
the orders of the groups are swapped
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu@stepancar @ericanderson

### PR DESCRIPTION
**Pull request by evestraw**
fixes #16867

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.4#curryRight

### CODE REVIEW

**Comment by evestraw** [comment]
i am not sure what went wrong, don't really see an error in the log only a stall

**Comment by mhegazy** [comment]
> i am not sure what went wrong, don't really see an error in the log only a stall

reran the tests, stall is gone, but now we have CI tests failing. please take a look.

**Comment by evestraw** [comment]
i took a look,  and i feel that the test assertions are not consistant with the documented behaviour,

i believe the curry right test were wrong,  
can you confirm or deny?

**Comment by mhegazy** [comment]
> i believe the curry right test were wrong,

I am not an expert on lodash. maybe @bczengel @chrootsu @stepancar @ericanderson can respond.

**Comment by ericanderson** [comment]
Based on reading the docs for lodash and reviewing this change (plus the test failure) I think I would agree that the tests are wrong. Can you fix them please @evestraw

**Comment by evestraw** [comment]
@ericanderson i fixed them, could you merge please?

**Comment by evestraw** [comment]
to authors (@bczengel @chrootsu @stepancar). Could you review this PR?

**Comment by ericanderson** [comment]
I don't have merge rights. @mhegazy

**Pull request merged**
