### PR TITLE
Update gulp-tslint types

### PR DESCRIPTION
**Pull request by pine**
Hello. I've updated `gulp-tslint` types. Thank you.
https://github.com/panuhorsmalahti/gulp-tslint

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/panuhorsmalahti/gulp-tslint
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by DanielRosenwasser** [comment]
@pine why is this necessary if [there are already types for gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint/blob/53534f8fc57b405551559ed336be38ebda172bf1/index.d.ts)?

**Comment by pine** [comment]
Hello @DanielRosenwasser .

This is *not* new `.d.ts` file.
The existed types is too old. I've update types.

Thank you.

**Comment by pine** [comment]
@DanielRosenwasser  I'm sorry. I did't know that `gulp-tslint` has official types.
https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.d.ts

Thank you.

**Pull request closed without merging**
