### PR TITLE
[jest] add type definition for toHaveBeenLastCalledWith

### PR DESCRIPTION
**Pull request by gyzerok**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/jest/docs/api.html#tohavebeenlastcalledwitharg1-arg2-

### CODE REVIEW

**Comment by NoHomey** [comment]
LGTM :+1:

**Comment by gyzerok** [comment]
@NoHomey can you help proceed it further, please?

**Comment by NoHomey** [comment]
@vvakame Could you review this PR and possibly merge it?

**Comment by gyzerok** [comment]
@NoHomey maybe it would be better if you do it yourself? :)

**Comment by NoHomey** [comment]
@gyzerok I've already said that it LGTM ...

**Comment by gyzerok** [comment]
@NoHomey, yeah, but can't you merge it as well? It shows that you are contributor, so I assumed you can..

**Comment by NoHomey** [comment]
@gyzerok  No I can't . I do not have write access to this repository. Contributor means: "This user has previously commited to {X} repository". You can hover the [Contributor] label and see it for yourself :smile: .

**Comment by vvakame** [comment]
I'm so sorry... I was moving my home. I'm backed now. thanks mates!

**Pull request merged**
