### PR TITLE
Add types for heft-jest package

### PR DESCRIPTION
**Pull request by octogonz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by iclanton — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Any reason this can't live in the package itself?

**Comment by octogonz** [comment]
> Any reason this can't live in the package itself (since you own it 😄)?

We definitely considered that option. The `jest-heft` package is a tooling plugin that injects a global API into the Jest runtime environment for tests to call. We don't want everyday projects to import `jest-heft` to obtain their typings, because that would bring along peer dependencies and other inappropriate baggage that is normally satisfied by indirect dependencies of the toolchain package.  It seemed much cleaner to import from a lightweight `@types/jest-heft` package that _**describes**_ the contract rather than _**defining**_ its implementation.  (Similar to how installing `@types/node` does not itself install a specific version of the Node.js engine.)

An added benefit of this approach is that `heft-jest` can be registered via **tsconfig.json**, as shown below, rather than requiring a clumsy `///` directive:

**tsconfig.json**
```ts
  . . .
  "types": ["node", "heft-jest"],
  . . .
```
As far as I can tell, this `"types"` setting can only refer to the special `@types` NPM scope, unless we used `"typesRoot"`.  But as far as I can tell `"typesRoot"` does not support module resolution, thus it seems to require a path like `./node_modules/package-name/folder-with-heft-jest-in-it`.  Doing that assumes that the package manager will make a `node_modules` folder, which is not always the case (e.g. NPM "hoisting" or Yarn Plug'n'Play).

**Comment by sandersn** [comment]
Seems fine to merge, although `types` works a bit backward from the way you described it. If you don't provide it, the compiler will look for global types in any `@types/`-scoped package inside any node_modules. If you *do* provide it, the compiler will look for global types *only* in the list of `@types` packages provided.

**Comment by octogonz** [comment]
Thanks very much!

> If you don't provide it, the compiler will look for global types in any `@types/`-scoped package inside any node_modules.

@sandersn Right, in large scale code base, we can't have the compiler loading up every stray `@types` package that it finds in a `node_modules` folder. So we must specify `"types"`.  

My point was, if we want to specify `"types": [ "heft-jest" ]`, then there must be an NPM package called `@types/heft-jest`.  

I considered making a NPM package like `@rushstack/heft-jest-types` or `@rushstacktypes/heft-jest`.  I also considered mapping`"types": "heft-jest"` to refer to simple folder like `./node_modules/@rushstack/heft/types/heft-jest`.  But doing so requires me to specify `"typeRoots"`, which seems to require a fixed folder path like this:

```
"typeRoots": [
  "./node_modules/@rushstack/heft/types/heft-jest",
  "node_modules/@types"
]
```
...but this disables module resolution. For example, with this setting the compiler would no longer find types in a path like `../.../node_modules/@types`.  Nor would it find a hoisted `@rushstack/heft` package such as `../../node_modules/@rushstack/heft`. 

It seems that `"typeRoots"` disables the compiler's normal module resolution, and replaces it with a finite list of hard-wired paths. 

Thus we cannot use `"typeRoots"`.  And that is why we need to publish an `@types` package via DefinitelyTyped.

**Pull request merged**
