### PR TITLE
Upgraded bcrypt to v1.0.1

### PR DESCRIPTION
**Pull request by IOAyman**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[ChangeLog](https://github.com/kelektiv/node.bcrypt.js/blob/master/CHANGELOG.md#101-2016-12-07)>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by CodeAnimal** [comment]
👍 Looks good to me.

**Comment by IOAyman** [comment]
cc @andy-ms @vvakame

**Comment by IOAyman** [comment]
@andy-ms, when is it going to be merged to _types-2.0_ and pushed to the [npm resgistry](https://www.npmjs.com/package/@types/bcrypt), please?

**Comment by andy-ms** [comment]
We directly publish from `master` as of #13233.

**Comment by IOAyman** [comment]
Thanks 👍

**Pull request merged**
