### PR TITLE
js-nacl update type on instantiate

### PR DESCRIPTION
**Pull request by Brendan-Stubbs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://www.npmjs.com/package/js-nacl)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## js-nacl ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-nacl@latest/))
was missing the following properties:
1. crypto_auth_BYTES
1. crypto_auth_KEYBYTES
1. crypto_box_BEFORENMBYTES
1. crypto_box_BOXZEROBYTES
1. crypto_box_NONCEBYTES

<details>
<summary>as well as these 59 other properties...</summary>
<p>crypto_box_PUBLICKEYBYTES, crypto_box_SECRETKEYBYTES, crypto_box_ZEROBYTES, crypto_hash_BYTES, crypto_hash_sha256_BYTES, crypto_onetimeauth_BYTES, crypto_onetimeauth_KEYBYTES, crypto_secretbox_BOXZEROBYTES, crypto_secretbox_KEYBYTES, crypto_secretbox_NONCEBYTES, crypto_secretbox_ZEROBYTES, crypto_sign_BYTES, crypto_sign_PUBLICKEYBYTES, crypto_sign_SECRETKEYBYTES, crypto_stream_KEYBYTES, crypto_stream_NONCEBYTES, crypto_scalarmult_SCALARBYTES, crypto_scalarmult_BYTES, encode_utf8, encode_latin1, decode_utf8, decode_latin1, to_hex, from_hex, random_bytes, crypto_box_keypair, crypto_box_random_nonce, crypto_box, crypto_box_open, crypto_box_precompute, crypto_box_precomputed, crypto_box_open_precomputed, crypto_stream_random_nonce, crypto_stream, crypto_stream_xor, crypto_onetimeauth, crypto_onetimeauth_verify, crypto_auth, crypto_auth_verify, crypto_secretbox_random_nonce, crypto_secretbox, crypto_secretbox_open, crypto_box_seal, crypto_box_seal_open, crypto_sign_keypair, crypto_sign, crypto_sign_detached, crypto_sign_open, crypto_sign_verify_detached, crypto_hash, crypto_hash_sha256, crypto_hash_string, crypto_sign_seed_keypair, crypto_box_seed_keypair, crypto_box_keypair_from_raw_sk, crypto_sign_keypair_from_seed, crypto_box_keypair_from_seed, crypto_scalarmult, crypto_scalarmult_base</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 854c4a773cefd30f5d5b734eb7abb06df5cbf24f
</p>

**Comment by Brendan-Stubbs** [comment]
> https://github.com/tonyg/js-nacl#changes

Would it be acceptable if I provide an example repository showing this behaviour?

**Comment by Brendan-Stubbs** [comment]
> Can you provide a link to docs/code that shows this behaviour? I can’t find anything on the project’s page that would indicate it returns a Promise
> 
> > Version 1.1.0: API change. The nacl_factory.instantiate function now expects a callback as its first argument. It calls the callback with the nacl instance containing the API functions, and returns no useful value.
> 
> (https://github.com/tonyg/js-nacl#changes)

I have demonstrated this behavior [here](https://github.com/Brendan-Stubbs/nacl-types-reproduction)

**Comment by MysteryBlokHed** [comment]
I tested it and it looks like it works

Could you add a test case in `js-nacl-tests.ts`? Modifying the tests lets me approve this instead of needing to wait for a maintainer 😄

**Comment by Brendan-Stubbs** [comment]
> I tested it and it looks like it works
> 
> Could you add a test case in `js-nacl-tests.ts`? Modifying the tests lets me approve this instead of needing to wait for a maintainer 😄

I am not quite sure how to go about testing this case (never worked with dtslint before) do I simply add an await on the initialise() call?

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by Brendan-Stubbs** [comment]
> LGTM!

Thanks very much for your help 👍

**Comment by Brendan-Stubbs** [comment]
Ready to merge

**Pull request merged**
