### PR TITLE
add typings for egjs-component

### PR DESCRIPTION
**Pull request by sculove**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by sculove** [comment]
I am providing npm as `@egjs/component`

**Comment by BendingBender** [comment]
Please follow [advice](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#what-about-scoped-packages) from the readme (which you've checked as read):

> #### What about scoped packages?
>
> Types for a scoped package `@foo/bar` should go in `types/foo__bar`. Note the double underscore.

**Comment by sculove** [comment]
@BendingBender 
I fit it. Thanks

**Comment by sculove** [comment]
face a problem.
look at following CI errors.
```
Found 3516 typings folders in /home/travis/build/DefinitelyTyped/DefinitelyTyped/types
TypeError: Cannot read property 'statements' of undefined
    at findImports (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/module-info.ts:309:48)
    at imports (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/module-info.ts:283:2)
    at referencedFiles (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/module-info.ts:256:20)
    at referencedFiles.next (<anonymous>)
    at Function.from (native)
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/module-info.ts:212:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/module-info.js:4:58)
    at <anonymous>
```
I have no idea.
Somebody help me ㅜㅜ

**Pull request merged**
