### PR TITLE
Improve MetadataType definition in @types/chromecast-caf-receiver

### PR DESCRIPTION
**Pull request by Serabe**
According to [documentation,
MetadataType](https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages#.MetadataType)
is a number, not a string.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages#.MetadataType

### CODE REVIEW

**Comment by Serabe** [comment]
@andrewbranch any hint on what I did wrong (if any) to make "getQuickInfoAtPosition" go up that way? Thank you!

**Comment by andrewbranch** [comment]
I need to investigate—it seems very suspicious that the _median_ went up so much without the mean or worst-case going up at all... it's quite possible there's something wonky with the math.

**Comment by craigrbruce** [comment]
@Serabe .. could you please double check this in your code? The documentation has been known to be wrong in several areas.

It has been 6 months since I worked on our Chromecast solution, but it is in production with many thousands of users (I work for Australia's biggest broadcaster) and we use metadata like this with success:

```         const metadata = {
          metadataType: 'GENERIC',  ```

**Review by craigrbruce — CHANGES_REQUESTED** [review]
Please see my comment: Check metadata in your debugger -- documentation may not be correct.

If it is correct then we need to reach out to Google CC developers to make their documentation clear. For example, if `metadataType` is indeed a number then please specify it as an `enum` with keys and values e.g. `GENERIC = 1` etc

**Comment by Serabe** [comment]
Their documentation says that it is a number. Check here: https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages#.MetadataType

For the values, I just did `copy(JSON.stringify(cast.framework.messages.MetadataType))`. Don't know if they accept both `'GENERIC'` and `cast.framework.messages.GENERIC`, but the documentation is explicit about what MetadataType contains (numbers). I can check tomorrow and make adjustments to allow both versions.

**Review by craigrbruce — APPROVED** [review]

**Comment by craigrbruce** [comment]
I checked the docs, and in the past, they have been incorrect (number instead of string, lowercase instead of uppercase, object instead of array etc.. etc..) which is why I raised the red flag.

in this case, you appear to be correct, I checked with our production site a short time ago

thanks for raising it - it could be this enum has changed over time, we will need to adjust our code accordingly :(

Cheers.

**Comment by amcasey** [comment]
@andrewbranch any perf concerns before I merge this?

**Comment by andrewbranch** [comment]
@amcasey go ahead 👍

**Pull request merged**
