### PR TITLE
#8573

### PR DESCRIPTION
**Pull request by vag1830**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
@vag1830 please rebase and `push -f` this branch.

**Comment by vag1830** [comment]
@vvakame Could you please clarify? ( I am kind of a newby sorry :))
Basically you need me to get the latest changes from your master and then push -f  right ?

**Comment by vvakame** [comment]
@vag1830 yes. this PR contains so many file changes. I want to check change from you.

**Comment by vag1830** [comment]
Closing this one because most likely i screwed everything up :). I will create a new clean one. Sorry for all the trouble.

**Pull request closed without merging**
