### PR TITLE
Update WebdriverIO typings to v4.7 and lint project

### PR DESCRIPTION
**Pull request by timbru31**
This PR adds the support for the new addition in the WebdriverIO 4.7 release:
`toggleTouchIdEnrollment`

Besides that I've enabled the lining for this project by adding the `tslint.json`. For now `unified-signatures` is disabled since with just the fixed linting warnings and indention issues the change is big enough IMO.  
In a separate PR I'd like to selectively disable the rule via `// tslint:disable:unified-signatures` where applicable.  
I've also updated the test code to function in async mode again and updated the GitHub test.

Additionally, I'd like to ask @nmalaguti if we should remove him as an author, since he stated [he isn't using WebdriverIO at the moment.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945#issuecomment-284153707)  
Instead maybe @monolithed or @fsmedberg-tc want to jump in as "official" contributors? 👍  😄 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
N/A

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v470-2017-04-20 - see addition of toggleTouchIdEnrollment and implementation here: https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/toggleTouchIdEnrollment.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
N/A

---
@christian-bromann: FYI

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👏

**Comment by fsmedberg-tc** [comment]
@timbru31 I volonteer as official contributor, but please note that I might sometimes take 4-5 days to respond. I will try to read through commits asap of course, but some weeks my schedule is crazily busy. :/

**Comment by timbru31** [comment]
@fsmedberg-tc no worries, I'm sometimes extremely busy, too. If any of the past contributors can review new changes that would help the whole community a lot IMO. I'll add you should I do another update (v4.8 is already out, lol)

**Comment by fsmedberg-tc** [comment]
@timbru31 Ok, awesome 👍

**Pull request merged**
