### PR TITLE
Fix @types/chrome extension function injection issue

### LINKED ISSUE #54749: chrome.scripting.executeScript issue
Hey! chrome.scripting.executeScript has a func paramater for executing a function, and it hasn't been added yet is what happens when it gets used like this:

`func: (args: any[]): void => {
	let name = args[0];
	switch (name) {
		case 'ap':
			name = 'ap++';
			break;
	}
	let scriptTag = document.createElement('script');
	scriptTag.src = chrome.runtime.getURL(`${name}.js`);
	scriptTag.type = 'module';
	scriptTag.onload = () => { scriptTag.remove() };
	(document.head || document.documentElement).appendChild(scriptTag);
}`

I'm gonna open a PR to close this issue soon.

### PR DESCRIPTION
**Pull request by nicolas377**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. **N/A**
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection>

closes #54749

### CODE REVIEW

**Comment by nicolas377** [comment]
This is a small change that can't be covered in tests without creating a full browser setup.

**Review by peterblazejewicz — COMMENTED** [review]
@nicolas377 may I ask to add a simple test? (considering the problem you've rised which is like using non-tested method signatures in DT). Just the newly added signature from your use-case would be great, thx!

**Comment by peterblazejewicz** [comment]
> This is a small change that can't be covered in tests without creating a full browser setup.

The DT is a formal test, compiler and linter are run againsts `.ts`/`.tsx` files producing no output.
Let me now if you need a hand. I think `test/index.ts` covers area under change.

**Review by peterblazejewicz — APPROVED** [review]
LGTM! @nicolas377 thx!

**Comment by nicolas377** [comment]
Ready to merge

**Comment by nicolas377** [comment]
turns out i'm a dumbass and this doesn't fix the problem at all
i'll open a new pr to fix it

**Comment by nicolas377** [comment]
#54823

**Comment by peterblazejewicz** [comment]
no worries, this is why I stressed the test addition :)

**Pull request merged**
