### PR TITLE
React.ReactType → React.ElementType

### PR DESCRIPTION
**Pull request by akameco**
`ReactType` is deprecated.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33263 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33263 
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by eps1lon** [comment]
Not sure if this is the right step. This would force everybody who bumps his version of `@types/package-using-react` to also update `@types/react`. I think it's up to the individual types maintainers if they want this behavior.

**Comment by akameco** [comment]
If the type definition is for React 15, `ElementType` can not be used.
So I think that there is no problem with updating.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/510793441f59c8d1e60069cb5b5628a395599992/types/react-addons-transition-group/index.d.ts#L1

But, I just agree that each maintainer should decide.
I will close PR.

**Comment by eps1lon** [comment]
> If the type definition is for React 15, ElementType can not be used.

I was more thinking about versions within react 16. Someone with e.g `@types/react@16.2.0` could not bump their version of `@types/package-that-uses-react` unless they also upgrade `@types/react`. And the types had a lot of breaking changes due to type narrowing.

**Comment by akameco** [comment]
understood. Thank you for the explanation 😃

**Pull request closed without merging**
