### PR TITLE
fix(node): add `Map` forward declare

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v11.x/docs/api/documentation.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33525

Kinda annoyed we still have to do this and CI didn't catch it.

### CODE REVIEW

**Comment by SimonSchick** [comment]
@sandersn seems like CI can still break on `next`, this is getting old 😛

**Review by ZaneHannanAU — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Review by Flarna — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Review by j-oliveras — APPROVED** [review]

**Comment by SimonSchick** [comment]
@gabritto @sandersn I really don't want to remake this PR 😢

**Comment by sandersn** [comment]
@SimonSchick Are you having timeout problems? DT has been mostly clean for the past 3 days.

**Comment by ZaneHannanAU** [comment]
I presume dt has been mostly clean because not as many people are interested in fixing node… because even the smallest change breaks something.

**Comment by sandersn** [comment]
@ZaneHannanAU node CI was always broken not because of changes to node. It's because dependents of node were broken because of typescript@next, but never fixed. In other words, the problem was stale code in the many packages that depend on node. Now that we have a nightly build of all of DT on typescript@next, we can see the failures and fix them.

**Comment by ZaneHannanAU** [comment]
Yeah this was more or less what I was getting at.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
