### PR TITLE
15.1.33 added

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Actually, you can release with these types when making module in your project.

**Comment by zhengbli** [comment]
Yes @Syncfusion-JavaScript it is preferable that you bundle the typing files directly with your libraries in npm whenever possible.

**Comment by TonyPythoneer** [comment]
Since releasing TypeScript 2.0 and typing files on npm, this repo is mainly to offer JS libraries without typing files to store them. I hope you can agree. It will reduce the burdens for DefinitelyTyped team and this repo size.

**Comment by Syncfusion-JavaScript** [comment]
Hi @TonyPythoneer ,

We are providing comprehensive collection of over 80+ enterprise-grade HTML5 JavaScript for building modern web applications. We extracted the API’s, methods and events from the JavaScript plugin source and generated definition file (ej.web.all.d.ts) to seamlessly work with Typescript as like the jQuery(source and definition). So, we prefer to merge the definition file into this repository to work with typescript and package applications along with our components.
 
Could you please merge the file changes into master?

**Comment by TonyPythoneer** [comment]
@Syncfusion-JavaScript Sorry, I don't have the permission to merge this PR. Although your service is very power, I am not your customer, I just tell you the community how to work.

By the way, is the source a private project? If it's yes, I would understand why you make typing files on DefinitelyTyped.

cc @zhengbli

**Comment by zhengbli** [comment]
Sure we can definitely take your contribution. Though please follow the instruction (https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) on how to add a new package. You are now missing the tslint.json file and tsconfig.json file.

**Comment by TonyPythoneer** [comment]
@Syncfusion-JavaScript Would you refer other typings files how to make a typings file? Maybe you wold make fewer mistakes on Travis CI/

**Comment by Syncfusion-JavaScript** [comment]
@TonyPythoneer Yes, we have added `jquery` in `types` array, but we facing the below issue.

```javascript
Error: File '/home/travis/build/DefinitelyTyped/DefinitelyTyped/ej.web.all/index.d.ts' has a BOM. Try using:
npm install -g strip-bom-cli
strip-bom index.d.ts > fix
```

We have checked the file encoding type which has `UTF-8`. Is there any other changes we need to do to overcome this issue.?

**Comment by Syncfusion-JavaScript** [comment]
@zhengbli Could it possible to merge the definition file without linting.? 

We further work on this and update the same asap.?

**Comment by TonyPythoneer** [comment]
@Syncfusion-JavaScript Sorry, we can't accpet. If it can't pass test, it will always affect other PRs owing to this.

**Comment by TonyPythoneer** [comment]
Ummm..., I had seen the error log in CI. Had you read the log from `tslint.json`? It has many syntaxes which don't pass the lint.

So, don't ignore or disable the tslint. Please follw the message and improve your code.

**Comment by Syncfusion-JavaScript** [comment]
Hi @TonyPythoneer ,

We have fixed the lint errors and updated the pull request. Can you please approve this pull request ?

**Comment by TonyPythoneer** [comment]
@Syncfusion-JavaScript  I am just a DefinitelyTyped contributor but I have to supervise typing files pass the test or not. :smile: And, the author of these typing files is you. You should be in charge of making better for your typing file.

In short, there is a paragraph needs to improve in `index.ts`. It should be like `/// <reference types="jquery"/>`, not `/// <reference types="../jquery"/>`.

If you have completed, Please cc zhengbli approve this.

**Comment by Syncfusion-JavaScript** [comment]
Hi @zhengbli ,

We have fixed the lint errors and updated the pull request. Can you please approve this pull request and  merge this to definitely typed repo ?

**Comment by Syncfusion-JavaScript** [comment]
Hi @zhengbli,

Can you please merge this pull request  asap?

**Comment by Syncfusion-JavaScript** [comment]
Can anyone merge this PR asap? @TonyPythoneer @zhengbli

**Comment by TonyPythoneer** [comment]
Let me call another recently active DefinitelyTyped member.
cc @minestarks

**Comment by zhengbli** [comment]
👍

**Pull request merged**
