### PR TITLE
Update react-mdl from 1.5.3 to 1.7.0

### PR DESCRIPTION
**Pull request by MichaelBitard**
case 2. Improvement to existing type definition.
From: https://github.com/tleunen/react-mdl/blob/master/CHANGELOG.md#170-2016-08-21
- Added Chip and ChipContact
- Added hideSpacer to HeaderProps and HeaderRowProps (1.5.3 -> 1.5.4)

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Working on a PR to fix the CI failures

**Comment by andy-ms** [comment]
Needs to merge in latest changes from `types-2.0`.

**Comment by yuit** [comment]
@MichaelBitard could you update the PR?

**Comment by yuit** [comment]
@MichaelBitard  Thanks for your contribution. This PR has merge conflict and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
