### PR TITLE
sinon: add createStubInstance sandbox

### LINKED ISSUE #21940: [@types/sinon] Sandbox.createStubInstance is missing / request for adding
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MrBigDog2U , @rationull , @lumaxis , @nicojs , @43081j

according to https://github.com/sinonjs/sinon/pull/1602
there is a new method for Sandbox:
createStubInstance()

From type perspective it should be the same as the global createStubInstance method I guess.

### PR DESCRIPTION
**Pull request by 43081j**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sinonjs/sinon/pull/1602
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes #21940.

### CODE REVIEW

**Comment by 43081j** [comment]
This won't build until #21868 is merged because of the lint errors.

**Comment by 43081j** [comment]
This builds now.

**Comment by nicojs** [comment]
Awesome!

**Review by lumaxis — APPROVED** [review]

**Comment by micksatana** [comment]
This PR also did Fix #21954

**Pull request merged**
