### PR TITLE
vue: fixed definition for activate() in ComponentOption

### PR DESCRIPTION
**Pull request by ckittelmann**
the callback was missing in the activate function

The activate function was added in vue 1.0.17 the callback was always part of the api

Documentation of activate:
https://vuejs.org/guide/components.html#activate-Hook

### CODE REVIEW

**Comment by kaorun343** [comment]
👍

**Comment by vladima** [comment]
@ckittelmann: does callback has any specific signature (or set of signatures) that can be used in typings - having just `Function` there feels a bit too relaxed

**Comment by ckittelmann** [comment]
@vladima: the callback has no specific signature. Vue requires the callback to continue mounting the component, if activate is used.
Here you can find the signature: https://github.com/vuejs/vue/blob/dev/src/directives/internal/component.js#L382-L388

**Comment by vvakame** [comment]
Please use `() => void` instead of `Function` in this case.

**Comment by vladima** [comment]
per [this example](https://vuejs.org/guide/components.html#activate-Hook) `activate` callback accepts `done` handler so It feels that signature should be more like
```ts
activate: (done: () => void) => void;
```

**Comment by ckittelmann** [comment]
applied suggestion of vladima, but made activate optional
`activate?: (done: () => void) => void;`

**Comment by vladima** [comment]
thanks!

**Pull request merged**
