### PR TITLE
chore(pretty-format): Unpublish

### PR DESCRIPTION
**Pull request by eps1lon**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- ~[ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)~
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

Ref: https://github.com/microsoft/types-publisher/pull/650, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37864

[24.3.0 types entry](https://unpkg.com/pretty-format@24.3.0/package.json)

### CODE REVIEW

**Comment by eps1lon** [comment]
@sandersn Maybe I misunderstood [your comment](https://github.com/microsoft/types-publisher/pull/650#issuecomment-524967810) but the CI ran on types-publisher's master but DT's CI doesn't seem to have picked up the new whitelist.

**Comment by weyert** [comment]
Sorry, why are we deleting this from DT?

**Comment by eps1lon** [comment]
> Sorry, why are we deleting this from DT?

@weyert Because as of 24.3 types are bundled with the package.

**Comment by weyert** [comment]
That seems reasonable I guess :)

**Comment by weyert** [comment]
> 🔔 @ikatyang @alexkrolick @kentcdodds @weyert - please review this PR in the next few days. Be sure to explicitly select Approve or Request Changes in the GitHub UI so I know what's going on.

I can't select any of these!

**Review by alexkrolick — APPROVED** [review]

**Comment by eps1lon** [comment]
> That seems reasonable I guess :)

@weyert This is standard procedure following 

> When a package bundles its own types, types should be removed from Definitely Typed to avoid confusion.


-- https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by weyert** [comment]
Can someone please look into the issue that I can’t approve these PRS while the bot suggests I can?

**Comment by rbuckton** [comment]
@weyert, you should be able to approve/reject from the "Files changed" tab:

image

**Pull request merged**
