### PR TITLE
node: Add validateHeaderName and validateHeaderValue to http

### PR DESCRIPTION
**Pull request by madmed88**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/http.html#httpvalidateheadernamename

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Neat 👍

**Comment by peterblazejewicz** [comment]
@madmed88 sorry to bother with a detail, this needs to be added to 'ts4.8' folder (types/node/ts4.8), to avoid difference between TS versions when using api, thanks!

**Comment by madmed88** [comment]
Should I copy or move the new code to that folder?

**Review by peterblazejewicz — APPROVED** [review]
@madmed88 thanks!

**Review by meyfa — CHANGES_REQUESTED** [review]
Thanks for adding these methods! Since they exist since Node version 14.3.0, they should also be added to `@types/node` versions 14 and 16. In essence, the same additions you made to `http.d.ts` and `test/http.ts` need to be made to the following files as well:

* `v14/http.d.ts` and `v14/test/http.ts`
* `v14/ts4.8/http.d.ts` and `v14/ts4.8/test/http.ts`
* `v16/http.d.ts` and `v16/test/http.ts`
* `v16/ts4.8/http.d.ts` and `v16/ts4.8/test/http.ts`

**Review by mcollina — APPROVED** [review]
lgtm

**Review by meyfa — APPROVED** [review]
Sorry, I didn't realize my review would be blocking, even if I'm not a maintainer. I'm changing it to approve. Feel free to make the additions to v14+v16, or not :)

**Comment by madmed88** [comment]
Ready to merge

**Pull request merged**
