### PR TITLE
Allow angulartics to be used in non module-based projects

### PR DESCRIPTION
**Pull request by massimocode**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

### CODE REVIEW

**Comment by andy-ms** [comment]
Does this module expose itself as a global variable? Could you link to documentation?

**Comment by stevenfan** [comment]
@massimocode could you verify the question asked above and that the tests pass? (otherwise LGTM)

**Comment by RyanCavanaugh** [comment]
Please address the CI failure

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
