### PR TITLE
[react-navigation] Adds stateless screens, stronger params typing, loosens navigationOptions

### PR DESCRIPTION
**Pull request by doomsower**
This PR reflects my way of using react-navigation in typescript projects. I was using my own fork of these definitions for a while, but now react-navigation is more actively developed, and I am starting new project, so I want to use original definitely typed definitions.

What this PR is about.
1. Current definitions do not allow usage of react stateless components as screens. This PR allows to use stateless components as screen in routing config, and also export convenience `NavigationStatelessScreen` interface for shorter declarations in your apps.
2. Inside my screens I like to have navigation params strongly typed, so I changed `NavigationScreenProps` to generic that accepts params type (defaults to existing `NavigationParams` key-value type, so this PR should not break existing code)
3. Adds [getParam](https://reactnavigation.org/docs/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback) definition.
4. Loosens `navigationOptions`. For example, if you have TabRouter inside Stack router, current definitions won't allow you to disable stack header in one of the tabs by setting `header: null` in `navigationOptions`. So I loosened the `navigationOptions` type to union of nav options for TabNavigator, StackNavigator and DrawerNavigator.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by doomsower** [comment]
Thanks for your attention, @timwangdev 
So your PR covers point 1 and 2 of mine, and it does it better. However, I have couple of questions about it: 
```ts
export type NavigationComponent =
   NavigationScreenComponent<any, any>
 | NavigationNavigator<any, any, any>
 | any;
```
What is the point of it? It's just equals `any`. It means that you can `number` as NavigationComponent?

Same with `<Params = NavigationParams>`. I think it should be `<Params extends NavigationParams = NavigationParams>` so it allows to pass key-objects pairs, but not any arbitrary types, because react-navigation merges params with destructuring.

So I guess I should close this one and wait for #24471 to get merged, then maybe I should submit point 3 and 4. I checked flow definitions, and `getParam` is not there, and for navigationOptions they seem to use *, which is not good idea imo. What do you think about 3 and 4?

**Comment by timwangdev** [comment]
@doomsower, just a quick reply: The any in union type is just simple port from https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L270-L273. So does most other changes in my PR. Surely we could improve those in the TS definition.

I will check 3 and 4 later.

**Comment by timwangdev** [comment]
Hi @doomsower, could you update your PR since #24471 just got merged? Thanks!

**Comment by doomsower** [comment]
I updated this commit, so it now does two things:
1) adds `getParam`
2) An original PR was about stateless components, and they were added in #24471. But there currently TS will complain when you try to set `navigationOptions` on stateless screen: `error TS2339: Property 'navigationOptions' does not exist on type 'StatelessComponent<NavigationNavigatorProps<{}, NavigationState>>'.
` I fixed this and added test. 

As for other points from original PR - I decided to drop them and make a separate PR when I will need those features.

**Review by timwangdev — APPROVED** [review]
LGTM!

**Pull request merged**
