### PR TITLE
[knockout] Change Elements in signatures to Node where reasonable

### PR DESCRIPTION
**Pull request by cervengoc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). **No tslint.jsjon**

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: **I could not find any reference but knowing the source code it should be fine.**
- [x] Increase the version number in the header if appropriate. **It's not related to package updates**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by cervengoc** [comment]
This was needed due to a bug where I could not call `ko.removeNode` in such a context, because `el` is defined as `HTMLElement | Text | Comment`:

```
jQuery(".something").contents().each((i,el) => {
  ko.removeNode(el);
});
```

**Comment by Igorbek** [comment]
It would be useful to have a link to the documentation or the source code that shows intention to use `Node` and not `Element`.

**Comment by cervengoc** [comment]
I'll try to do so but for the meantime in general knockout heavily uses text and comment nodes to achieve data bindings. They use the term virtual elements. You can see that in the definitions there are already kind of a mixed signatures across several methods.

**Comment by cervengoc** [comment]
For a reference, see this code: https://github.com/knockout/knockout/blob/master/src/utils.domNodeDisposal.js#L67

The cleanable node types are elements, comments, and document. However, it's perfectly OK and expected to pass in to `cleanNode` and `removeNode`any node, because the code then simply does nothing.

**Comment by cervengoc** [comment]
@Igorbek @borisyankov

**Review by Igorbek — APPROVED** [review]

**Comment by Igorbek** [comment]
Thank you for explaining and pointing to the source. Now it makes sense to me.

**Pull request merged**
