### PR TITLE
 fix(maxmsp): some file constructor parameters are optional

### PR DESCRIPTION
**Pull request by FrancescElies**
Certain parameters are optional.
- Based on function description, see above
- tested on max too

### CODE REVIEW

**Comment by twhiston** [comment]
Thanks for these changes, please update the test file to reflect them and I'll get it merged. Should be an easy change but do let me know if you have any issues.

**Comment by FrancescElies** [comment]
As far as I can tell there should be no changes needed to the tests, the problem was formatting (I should be using prettier).

That is now fixed.

I added another usage example and run prettier over the test file too (I hope that is fine).

**Comment by FrancescElies** [comment]
Running prettier over the tests file made something complain about whitespaces, thus I reverted those changes and added a test only touching as little as possible.

**Review by twhiston — APPROVED** [review]
Approved. Thanks very much for your contribution!

**Comment by twhiston** [comment]
Ready to merge

**Pull request merged**
