### PR TITLE
Add styled-components.d.ts and its tests to rebass__forms

### PR DESCRIPTION
**Pull request by LissetteIbnz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/rebassjs/rebass/commit/905782acc3daf131fa0cb488066ac325ec498347>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
@zinozzino, @trumanshuck, @Eddie-CooRo -- ?

**Comment by andrewbranch** [comment]
Since nobody else showed up I tried to review this myself, but I can’t really find any documentation or examples in the commit you linked that would verify that this is correct. @LissetteIbnz, is there some documentation somewhere that shows/explains imports from `@rebass/forms/styled-components`?

**Comment by LissetteIbnz** [comment]
@andrewbranch no, I am sorry. In the `rebass` doc you can read this about how you can use this library with the `styled-components`  👉 https://rebassjs.org/guides/styled-components
But, if you want to use `rebass/form` with `styled-components`, you must use it the same way.

**Review by andrewbranch — APPROVED** [review]
Close enough. Maybe Rebass should specifically include this in their docs though 🤔

**Comment by LissetteIbnz** [comment]
Ready to merge

**Comment by LissetteIbnz** [comment]
@andrewbranch totally. It is a good idea. Maybe I could do a PR with that change, because it is true that it's doc is not clear 👍

**Pull request merged**
