### PR TITLE
[react] indicate alternatives for deprecated keypress events

### PR DESCRIPTION
**Pull request by alphashuro**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thank you for these suggestions. Please also apply the same change to `types/react/ts5.0/index.d.ts`

**Comment by alphashuro** [comment]
> types/react/ts5.0/index.d.ts

done!

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by eps1lon** [comment]
Failures are unrelated and will be fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70342

**Pull request merged**
