### PR TITLE
`node`: [fix] node buffers have a `constructor` property

### PR DESCRIPTION
**Pull request by ljharb**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: `new Buffer('').constructor === Buffer`, in every node version ever
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Flarna** [comment]
I'm not sure what this change is needed for. What's wrong with the `new` APIs defined below `declare var Buffer`? Could you add a test to show the use case enabled by this?
Why only NodeJS 9 and not latest nodejs?

**Comment by ljharb** [comment]
@Flarna i have a place where i do `obj.constructor.isBuffer`, and this was erroring without this change. I only included the fix for v9 because the older versions don’t seem to have types for the constructor (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28900#issuecomment-421488471)

I’ll try to add a test.

**Comment by ljharb** [comment]
Because if i do that, bundlers include an entire Buffer polyfill - see https://github.com/ljharb/qs/issues/39.

As for the type, for any builtin T besides Function, `typeof new T().constructor` should always be T - if it’s only Function, then that’s a bug in the type system.

**Comment by Flarna** [comment]
ok understood.

> As for the type, for any builtin T besides Function, `typeof new T().constructor` should always be T - if it’s only Function, then that’s a bug in the type system.

Seems so yes, see https://github.com/Microsoft/TypeScript/issues/3841

**Comment by ljharb** [comment]
In that case, do you suggest a different approach? This is a pretty basic part of JS to have been mistyped for this long :-/

**Comment by Flarna** [comment]
I don't have a different approach.
At first I haven't understood why this is needed at all, then I thought about converting `Buffer` to `class` - assuming that this solves your problem. But it turned out it doesn't and googling routed me to above typescript issue. I haven't read all comments there, not sure if there is something better we could use here.

**Review by Flarna — CHANGES_REQUESTED** [review]
Please adapt also latest NodeJs typings (file `types\node\index.d.ts`)

**Comment by ljharb** [comment]
@Flarna thanks, updated (i missed it because i assumed there'd be a v10 folder)

**Review by Flarna — APPROVED** [review]

**Comment by jessetrinity** [comment]
@ljharb Did you still want to add a test to this?

**Comment by mohsen1** [comment]
Why we have `EventEmitter` as a `class` but not `Buffer`? 

TypeScript enforces `new` for classes. Note that real classes are not callable without `new` in runtime. 

But Node "class"es are not real classes and are just plain functions. 

We have to decide if we want to use `class` for Node classes or not. if we use `class`, this change will be unnecessary.

**Comment by ljharb** [comment]
@jessetrinity oh right, i'd forgotten - is there an easy way to just run the tests for this one package without having to run them for the entire repo?

**Comment by ljharb** [comment]
> But Node "class"es are not real classes

Note that JS doesn't have any sort of "real classes", just `class`, which is conceptually and functionally identical to ES5 `new`ed constructor functions - anything that's intended to be `new`ed is a "class", altho `class` produces uncallable constructors (ie, they require `new`).

**Comment by mohsen1** [comment]
[TypeScript throws an error](https://www.typescriptlang.org/play/index.html#src=class%20RealClass%20%7B%20%7D%0D%0A%0D%0Afunction%20Class()%20%7B%20%7D%0D%0A%0D%0ARealClass()%0D%0Anew%20RealClass()%0D%0AClass()%0D%0Anew%20Class()) for calling classes without `new` which is a runtime error if target is defined using the class keyword (isn't "actual class" a good name for this case?)

Currently `EventEmitter` is declared as a class which will produce a TS error for calling it without `new`, although it's fine in Node.js runtime because[ its not defined with a `class` keyword.](https://github.com/nodejs/node/blob/fadafef4f4e673b71cb33078a588daddf8deed3a/lib/events.js#L26)

@andy-ms 
My question is, should we stop using `class` for other Node.js "classes" until  Node changes its code to use the `class` keyword?

**Comment by ljharb** [comment]
In that case then anything not declared with `class` probably shouldn't be typed as one, no

**Comment by andy-ms** [comment]
`require("events")()` fails for me with: `TypeError: Cannot set property 'domain' of undefined`.

Even if that did work, I think the simplicity of declaring something as a `class` outweighs the ability to omit the `new` keyword even if that were supported.

**Comment by ljharb** [comment]
@jessetrinity fwiw `npm install` failed for me on node 10 on my mac; is there a specific version of node that this repo requires to work?

**Comment by Flarna** [comment]
> Why we have `EventEmitter` as a `class` but not `Buffer`?

I think mostly because no one issues a PR to improve this. I can remember several PRs to change this and that `interface` to a `class` to fix concrete issues but no PR like "use classes where applicable". I think that older typescript versions (maybe <2) had also some limitations regarding merging of interfaces, classes and namespaces but I can't remember in detail.

**Comment by Flarna** [comment]
> Currently `EventEmitter` is declared as a class which will produce a TS error for calling it without `new`, although it's fine in Node.js runtime because[ its not defined with a `class` keyword.](https://github.com/nodejs/node/blob/fadafef4f4e673b71cb33078a588daddf8deed3a/lib/events.js#L26)

[NodeJs doc](https://nodejs.org/dist/latest-v10.x/docs/api/events.html#events_class_eventemitter) tells it's a class.
@mohsen1 What is the real world usecase to call `EventEmitter` without `new`? Sure, for JS point of view it's fine but quite a lot is allowed from JS point of view where typescript tells it's not allowed.

**Comment by jessetrinity** [comment]
@ljharb Node 10 should be fine. Normally you can run tests from types/foo but in the case of Node you should run the whole things.

Any details on how it is failing? I will have to ask around about Mac.

**Comment by ljharb** [comment]
@jessetrinity compilation errors:
<details>

```sh
$HOME/.node-gyp/10.10.0/include/node/openssl/ossl_typ.h:107:16
: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
../vendor/libssh2/src/openssl.c:133:14: error: incomplete definition of type 'struct dsa_st'
    (*dsactx)->q = BN_new();
    ~~~~~~~~~^
$HOME/.node-gyp/10.10.0/include/node/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/libssh2/vendor/libssh2/src/openssl.o] Error 1
gyp

ERR! build error
gyp
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack
at ChildProcess.onExit ($HOME/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR!
stack     at ChildProcess.emit (events.js:182:13)
gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp
ERR! System Darwin 17.7.0
gyp
ERR! command "$HOME/.nvm/versions/node/v10.10.0/bin/node" "$HOME/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=$HOME/airlab/repos/DefinitelyTyped/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=$HOME/airlab/repos/DefinitelyTyped/node_modules/nodegit/build/Release"
gyp
ERR! cwd $HOME/airlab/repos/DefinitelyTyped/node_modules/nodegit
gyp ERR! node -v v10.10.0
gyp
ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```
</details>

**Comment by andy-ms** [comment]
@ljharb That may be nodegit/nodegit#1490. You should be able to just ignore this and run `npm run lint my-package-name` directly, which doesn't use that dependency.

**Pull request merged**
