### PR TITLE
Updated dts with Word 1.2 updates, get-setTextAsync from office commo…

### PR DESCRIPTION
**Pull request by MIchaelMainer**
…n, and current in development APIs for Excel 1.2 and Word 1.3.

### CODE REVIEW

**Comment by vvakame** [comment]
@robmhoward could you review this PR?

**Comment by MIchaelMainer** [comment]
@robmhoward, this has been reviewed by MichaelZ

**Comment by robmhoward** [comment]
:+1:

**Comment by horiuchi** [comment]
@MIchaelMainer Thanks mate!
@robmhoward Thanks for review!

**Pull request merged**
