### PR TITLE
Added Licensing

### PR DESCRIPTION
**Pull request by bgrieder**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by bgrieder** [comment]
👍

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE
this repository is under MIT license. We can't accept this change.
Why do you need this change?

**Comment by bgrieder** [comment]
Microsoft asked for a clarification and the way they read it - which is also mine - is that the licensing terms of work made by contributors to this repository is not automatically under MIT as you suggest.

I selected Apache 2.0 because it greatly eliminates potential litigation cases relating to patents. In the case above, Facebook, the React Native license holder, may (or may not) have patents related to their work which they could feel are breached by the use by Microsoft of the work carried on React Native Definition files. I - and surely you - do not want to be sitting in the middle of this.

**Comment by TonyPythoneer** [comment]
@bgrieder I understand your thinking but it needs MS members to discuss this together.

**Comment by vvakame** [comment]
I think Committers can't control intricate licenses repository.
I recommend to use monolithic license. It is MIT license now.

cc/ @borisyankov @Diullei @basarat @horiuchi
and @andy-ms @mhegazy @zhengbli 

---

NOTE
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/96
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/132

**Comment by bgrieder** [comment]
@vvakame @borisyankov I am giving up my role as an author in your repository. I am not asking anything for the time I invested in it except that you find someone else to take over reviewing PRs and that you accept all responsibilities for future work carried on these definitions.

fyi, Microsoft refused to take over although they invested a significant amount of time in maintaining these definitions (and are clearly one of the first beneficiary, directly or indirectly, of work provided by non Microsoft employees like me).

Thank you, good luck, good bye.

**Comment by mhegazy** [comment]
What do you mean by "Microsoft asked for clarifications"? Can you put me in contact with whoever asked about that?

**Comment by bgrieder** [comment]
@mhegazy Sure. Complete e-mail thread copied below. Start at the bottom


> Hi Bruno,
>  
> We are interested in ensuring that the typings are up to date and we do intend to contribute when we can (we helped bring typings up to date with 0.34).
> At the same time I feel that it is better as a community effort and we don’t want to discourage contributions from others by “owning” anything. I’ve seen a good amount of activity on definitely typed, so if you find yourself unable to contribute due to other commitments, I’m sure the effort can continue on while people are interested in using typescript with react-native.
>  
> Thanks,
> Jimmy
>  
> From: Bruno Grieder [mailto:bruno.grieder@gmail.com] 
> Sent: Wednesday, November 2, 2016 12:02 AM
> To: Jimmy Thomson <jithomso@microsoft.com>
> Subject: Re: Clarification on the license of react-native typescript typings in definitelytyped
>  
> Jimmy,
>  
> Since we are at it, would Microsoft like to take over the maintenance of the react-native definition files ?
> React Native is a fast evolving technology and I think you are better equipped than I am to carry this work forward.
>  
> brgds
>  
> Bruno
>  
>  
>

**Comment by paulvanbrenk** [comment]
@mhegazy thoughts? I agree with @vvakame that individual typings should probably not carry a license... that would just be confusing for consumers, and would make the auto acquisition more complex.

**Comment by mhegazy** [comment]
I did speak to @MSLaguana about this offline, and I will be following the legal team at MS for any questions/action items. i do not think this PR is needed any longer.

**Comment by paulvanbrenk** [comment]
Closing as per @mhegazy's remarks

**Comment by TonyPythoneer** [comment]
@bgrieder Will you continue to maintain this definition? I appreciate your contribution to this definition. If you're sure to give up as a contributor, I hope you invite a new and enthusiastic contributor maintaining this definition in the future.

**Comment by bgrieder** [comment]
@TonyPythoneer I am giving up. React-Native is evolving too fast and is becoming too big for any single individual like me to do this "on the side". This has become a big boy game with big boys rules: licensing issues, politics, marketing strategies, etc..and I do not want to be part of that game.

Microsoft has significantly invested in react-native (these definitions, Code Push, VS Code extension, etc...), has an obvious vested interest in Typescript, and has significant resources. They are the ones who should take this over.

Good luck convincing them.

**Comment by TonyPythoneer** [comment]
Does it need to change the author to MS?
@paulvanbrenk @mhegazy how do you think?

**Pull request closed without merging**
