### PR TITLE
leaflet-locatecontrol: change markerStyle to any

### PR DESCRIPTION
**Pull request by danielcollettepb**
The `markerClass` is set to `any`, so I can use `L.Marker`, but the `markerStyle` is set to use `PathOptions` only.

Changing the `markerStyle` to `any`, assuming that the markerClass could also be `L.Icon`, etc.

Example usage:

```
// marker styles
  markerStyles = {
    current: L.divIcon({
      className: 'leaflet-current'
    })
  };

    // add the locate control to the map
    L.control
      .locate({
        icon: 'leaflet-control-locate-icon',
        iconLoading: 'leaflet-control-locate-icon-loader spin',
        drawCircle: false, // set to true to show accuracy ring
        showPopup: false,
        markerClass: L.marker,
        markerStyle: {
          icon: this.markerStyles.current
        }
      })
      .addTo(this._map);
  }

```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L103
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by armanio123** [comment]
I think this is incorrect. In the [documentation](https://github.com/domoritz/leaflet-locatecontrol#possible-options), markerStyle clearly states that PathOptions is the type accepted. Also neither the source code provided or the path options on the leaflet [documentation](https://leafletjs.com/reference-1.3.0.html#path) allows to do this.

**Comment by danielcollettepb** [comment]
Hi @armanio123, thanks for your response.

[This issue](https://github.com/domoritz/leaflet-locatecontrol/issues/53) shows that it is possible to use a custom marker with the plugin.

Maybe the markerStyle should have the option to use MarkerOptions rather than being set to `any`:

```
markerStyle?: PathOptions | MarkerOptions;
```

Do you think this would be acceptable?

**Comment by armanio123** [comment]
I think it's a little bit better. Send the update and I'll merge it as don't want to block you.

Anyway, I'll suggest contacting or sending a PR to leaflet-locatecontrol guys to update the documentation.

**Comment by danielcollettepb** [comment]
thanks so much, appreciate the help @armanio123

**Pull request merged**
