### PR TITLE
Add @types/broccoli-merge-trees

### PR DESCRIPTION
**Pull request by KonradPerlicki**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by KonradPerlicki** [comment]
Could someone please review this PR before I make a new PR to add `broccoli-plugin` package to allowedPackageJsonDependencies?

**Comment by KonradPerlicki** [comment]
@peterblazejewicz  Could you please review this?

**Comment by peterblazejewicz** [comment]
Hey,

you have to add `brocolli-plugin` to allowed deps list in this repo (as per error in CI):
https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/definitions-parser/allowedPackageJsonDependencies.txt

Otherwise looks ok, you could write implementation for this module is couple of ways, also:
```ts
export = mergeTrees;

/**
 *
 * @param inputNodes An array of nodes, whose contents will be merged
 * @param [options] A hash of options
 */
declare function mergeTrees(
    inputNodes: InputNode[],
    options?: mergeTrees.Options,
): BroccoliMergeTrees;

declare class BroccoliMergeTrees extends Plugin {
    constructor(inputNodes: InputNode[], options?: mergeTrees.Options);

    build(): void | never;
}

declare namespace mergeTrees {

    const MergeTrees: typeof BroccoliMergeTrees;

    interface Options {
        /**
         * A descriptive annotation. Useful for debugging, to tell multiple instances of the same plugin apart.
         */
        annotation?: string | undefined;

        /**
         * A string representing the destination path that merged files will be copied to.
         */
        destDir?: string | undefined;

        /**
         * By default, broccoli-merge-trees throws an error when a file exists in multiple nodes.
         * If you pass `{ overwrite: true }`, the output will contain the version of the file
         * as it exists in the last input node that contains it.
         */
        overwrite?: boolean | undefined;
    }
}
```

ping me when upstream PR finishes, you would have to rebase your PR with updated master, so CI gets proper diff

**Comment by KonradPerlicki** [comment]
@peterblazejewicz thanks for the other example, but for this one I will stay with my initial approach. 
`broccoli-plugin` has been already added to allowedPackageJsonDependencies.

**Comment by peterblazejewicz** [comment]
remember to rebase/marge current master, so the diff takes into account new dependencies (with upstream change)

**Comment by DangerBotOSS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```
ENOENT: no such file or directory, open 'types/broccoli-merge-trees/index.d.ts'
Error: ENOENT: no such file or directory, open 'types/broccoli-merge-trees/index.d.ts'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at dangerfile.ts:57:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dangerfile.ts:56:13)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at requireFromString (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/require-from-string/index.js:28:4)
    at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/danger/distribution/runner/runners/inline.js:161:68
    at step (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/danger/distribution/runner/runners/inline.js:52:23)
    at Object.next (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/danger/distribution/runner/runners/inline.js:33:53)
```
### Dangerfile
```
------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 68dab2cd4b405dfd8b8e5455224fbc11b7f7174e
</p>

**Comment by KonradPerlicki** [comment]
> remember to rebase/marge current master, so the diff takes into account new dependencies (with upstream change)

I think I did it wrong with first rebase and it marked a lot of files as modified and revert that commit didn't help, can I somehow fix it or just create a new PR at this point?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@KonradPerlicki I've force pushed your original commit replayed on current master branch. This fixed the problem.

**Comment by KonradPerlicki** [comment]
Ready to merge

**Pull request merged**
