### PR TITLE
keycloak-connect: Provides its own types

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This will deprecate `@types/keycloak-connect` in favor of just `keycloak-connect`. CC @gstamac

### CODE REVIEW

**Comment by cornelius-agrippa** [comment]
Are you sure this is correct? Version 7.0.0 of `keycloak-connect` doesn't seem to have working typings.

**Comment by a-tarasyuk** [comment]
@cornelius-agrippa 
In version 7.0.0 was added `typings` support.  - [tag 7.0.0](https://github.com/keycloak/keycloak-nodejs-connect/commit/6f334e54c00260b9313c1a69c3946f78832b144e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L29).  [keycloak.d.ts](https://github.com/keycloak/keycloak-nodejs-connect/blob/6f334e54c00260b9313c1a69c3946f78832b144e/keycloak.d.ts)

**Comment by PranavSenthilnathan** [comment]
Yeah, as @cornelius-agrippa mentioned, there is a types value in the package.json but the file isn't in the package. https://unpkg.com/browse/keycloak-connect@7.0.1/

**Comment by a-tarasyuk** [comment]
It seems types were not published to npm. In this case, this PR needs to close.

**Pull request closed without merging**
