### PR TITLE
Removed cyclic self-referenced `util/types` from node types

### PR DESCRIPTION
**Pull request by timocov**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. (there are tests for this code already, I just removed redundant pieces)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: none
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jakebailey** [comment]
Was this a typo and was supposed to be the `node:` re-export?

**Comment by timocov** [comment]
@jakebailey I didn't check every file, but in some that I did there is re-export at the end of the file already

**Comment by jakebailey** [comment]
@typescript-bot ping

**Comment by timocov** [comment]
Any updates on this? This looks like a typo fix, not sure why it takes so long :( Is there anything I can do to help with validation/proving that this fix is safe?

**Comment by peterblazejewicz** [comment]
@timocov please rebase against current master branch, so the CI tests would rerun against current CI setup (pnpm, monorepo). I'm happy to approve afterwards

**Comment by timocov** [comment]
@peterblazejewicz done

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@timocov thanks!

**Comment by timocov** [comment]
Ready to merge.

@peterblazejewicz thanks!

**Pull request merged**
