### PR TITLE
react-native-canvas: add optional arguments to toDataURL

### PR DESCRIPTION
**Pull request by tebatalla**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by hmajid2301** [comment]
LGTM

**Comment by tebatalla** [comment]
@hmajid2301 do you need to select approve still?

**Comment by hmajid2301** [comment]
I cannot see the approve button ?

**Comment by tebatalla** [comment]
>Be sure to explicitly select Approve or Request Changes in the GitHub UI so I know what's going on.

Huh 🤷‍♂️

**Review by hmajid2301 — APPROVED** [review]

**Comment by tebatalla** [comment]
Ready to merge

**Pull request merged**
