### PR TITLE
Keypress: Lint and rename to keypress.js

### PR DESCRIPTION
**Pull request by ghost**
Based on the `https://github.com/dmauro/Keypress/` link, this is npm's `keypress.js` package, and is unrelated to `keypress`. It also used `declare module "keypress.js"`.
I also noticed that there are a few casts in the test file -- does this indicate that the definition could be improved?

If this is merged, I will `npm deprecate @types/keypress "'@types/keypress' is now '@types/keypress.js'"`.

CC @rcchen @sixinli

### CODE REVIEW

**Comment by rcchen** [comment]
To be honest I haven't used this library in ages now, @sixinli might know better.

**Comment by sixinli** [comment]
@andy-ms sorry for looking at this late, but can you add the amd declare back? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18357/files#diff-6654b23ee38f80009c658dbe72ea4cedL9

**Comment by andy-ms** [comment]
@sixinli This should still be importable as a module even without `declare module` -- the file itself is the module and each `export` is a module export.

**Comment by sixinli** [comment]
cool will play around it it later, thanks for explaining @andy-ms

**Pull request merged**
