### PR TITLE
react-big-calendar: update to use es6 default export

### PR DESCRIPTION
**Pull request by frankwallis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://unpkg.com/react-big-calendar@0.14.3/lib/index.js (at the bottom ```export default``` is used)
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by piotrwitek** [comment]
Hi @frankwallis, does it mean a library author made change and now exposes a default export in the main bundle?

**Comment by frankwallis** [comment]
Hi @piotrwitek - yes that is correct. I'm not exactly when it happened, it's possibly due to a knock-on change from babel-preset-jason.

**Comment by piotrwitek** [comment]
@frankwallis thanks a lot for contribution, LGTM 👍

**Review by piotrwitek — APPROVED** [review]
library changed to default export, looks good

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
