### PR TITLE
Add width and height attributes to source elements @types/react @types/babel-plugin-react-html-attrs

### PR DESCRIPTION
**Pull request by tomohiro-iwana**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  <<https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element>> <<https://github.com/whatwg/html/pull/5894>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by tomohiro-iwana** [comment]
@eps1lon 

>Error in react-svg-pan-zoom
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react-svg-pan-zoom/react-svg-pan-zoom-tests.tsx:27:9
ERROR: 27:9  expect  TypeScript@4.4 compile error: 
Type 'number' is not assignable to type '2'.
ERROR: 28:9  expect  TypeScript@4.4 compile error: 
Type 'string' is not assignable to type 'Mode'.
ERROR: 46:7  expect  TypeScript@4.4 compile error: 
Type 'string' is not assignable to type 'Tool'.

Above error occurs, but I did not touch this package.
What should I do?

**Comment by eps1lon** [comment]
> Above error occurs, but I did not touch this package.
What should I do?

Does it already fail on `master`?
If so then just rebase every other day until it passes.

Does it fail locally? 
Fix it locally.

**Comment by tomohiro-iwana** [comment]
> 1> react-svg-pan-zoom OK

Fixed react-svg-pan-zoom, but still have some errors around wordpress(downshift) 😢 

```
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(3,40): error TS2307: Cannot find module '../src/types' or its corresponding type declarations.
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(41,36): error TS2304: Cannot find name 'A11yStatusMessageOptions'.
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(264,36): error TS2304: Cannot find name 'A11yStatusMessageOptions'.
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(265,39): error TS2304: Cannot find name 'A11yStatusMessageOptions'.
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(420,36): error TS2304: Cannot find name 'A11yStatusMessageOptions'.
Error: 1> ../wordpress__components/node_modules/downshift/typings/index.d.ts(421,39): error TS2304: Cannot find name 'A11yStatusMessageOptions'.
```

**Comment by peterblazejewicz** [comment]
so what's the status? It's all green now, some stale deps impacted previous checks I assume.

**Review by eps1lon — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by tomohiro-iwana** [comment]
Ready to merge

**Pull request merged**
