### PR TITLE
Pg: Adds a boolean value for PoolClient.release's support for truthy and error values

### PR DESCRIPTION
**Pull request by durango**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://node-postgres.com/api/pool#releaseCallback
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (N/A)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed. (N/A)

### CODE REVIEW

**Review by HoldYourWaffle — COMMENTED** [review]
Can you link to a piece of documentation/code that shows this is supported behavior?

Edit: never mind I didn't read your original comment correctly. Looks fine to me.

**Comment by HoldYourWaffle** [comment]
There are a lot of formatting changes in this PR and I'm not familiar enough with DT to know if that's allowed/desirable or not. Perhaps @pspeter3 or a maintainer can shine some light on this matter?

**Comment by durango** [comment]
@HoldYourWaffle the link is in the PR: https://node-postgres.com/api/pool#releaseCallback

Emphasis mine:

> The releaseCallback releases an acquired client back to the pool. **If you pass a truthy value in the err position to the callback, instead of releasing the client to the pool, the pool will be instructed to disconnect and destroy this client**, leaving a space within itself for a new client.

From the code example:
```js
const { Pool } = require('pg')
const pool = new Pool()
assert(pool.totalCount === 0)
assert(pool.idleCount === 0)
;(async function() {
  const client = await pool.connect()
  await client.query('SELECT NOW()')
  assert(pool.totalCount === 1)
  assert(pool.idleCount === 0)
  // tell the pool to destroy this client
  ----------> client.release(true) <------ here
  assert(pool.idleCount === 0)
  assert(pool.totalCount === 0)
})()
```

**Comment by durango** [comment]
@HoldYourWaffle let me know if my vscode environment is incorrectly applying the Prettier rules. As far as I know, we're more aligned with the spec than before (4 spaces, etc.), and it seems to be more consistent with other packages. Again, let me know if this is incorrect and I can always revert that commit.

**Pull request merged**
