### PR TITLE
lodash-es: fix dep to point properly to `@types/lodash`

### PR DESCRIPTION
**Pull request by stephenlautier**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

Currently when added the `package.json` the `dependencies` was set to `lodash` instead of `@types/lodash` by mistake.

### CODE REVIEW

**Review by vvakame — APPROVED** [review]

**Comment by vvakame** [comment]
@andy-ms Can we merge this PR?

**Comment by andy-ms** [comment]
Why not just remove `package.json` entirely?

**Comment by stephenlautier** [comment]
@andy-ms Dependencies will be picked automagically?

**Comment by andy-ms** [comment]
Yes! Most packages don't have a `package.json`. We infer dependencies to other `@types` packages based on imports and `/// <reference types="" />` comments.

**Comment by stephenlautier** [comment]
@andy-ms cool, i will modify and remove `package.json` as you suggested than, thanks!

**Pull request merged**
