### PR TITLE
Add id to mongodb gridfs upload streams

### PR DESCRIPTION
**Pull request by coyotte508**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongodb.github.io/node-mongodb-native/2.1/api/GridFSBucket.html#openUploadStream
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

As seen in http://mongodb.github.io/node-mongodb-native/2.1/api/GridFSBucket.html#openUploadStream:

```js
    var uploadStream = bucket.openUploadStream('test.dat');

    var license = fs.readFileSync('./LICENSE');
    var id = uploadStream.id;
```

The resulting stream from `openUploadStream` *has* an id, which is currently absent in the `@types/mongo` package.

### CODE REVIEW

**Comment by CaselIT** [comment]
Could you also add it to the current (v3) version of mongodb since it also applies?
http://mongodb.github.io/node-mongodb-native/3.0/api/GridFSBucket.html#openUploadStream

Thanks

**Comment by coyotte508** [comment]
I'll look more into it, see if it should be `ObjectID` instead of `string | number | Object`, and I'll update the PR.

**Comment by CaselIT** [comment]
It seems it can be both
Ref:
http://mongodb.github.io/node-mongodb-native/3.0/api/lib_gridfs-stream_upload.js.html#line41
and http://mongodb.github.io/node-mongodb-native/3.0/api/GridFSBucketWriteStream.html

**Comment by coyotte508** [comment]
Thanks for the links. Updated the pull request.

**Review by CaselIT — APPROVED** [review]

**Pull request merged**
