### PR TITLE
Update postcss url

### PR DESCRIPTION
**Pull request by remcohaszing**
The only thing that changed if the postcss dependency update. This required some small changes to the types and type tests.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lenovouser** [comment]
@remcohaszing looks good to me, can you add yourself to the header before I approve it?

**Comment by remcohaszing** [comment]
Sure! Done :)

**Review by lenovouser — APPROVED** [review]

**Comment by lenovouser** [comment]
Thanks, and sorry for the late reply

**Comment by lenovouser** [comment]
Ready to merge

**Pull request merged**
