### PR TITLE
 [p5] Added new definition for applyMatrix method to handle 4x4 matrices.

### PR DESCRIPTION
**Pull request by yama-yeah**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://p5js.org/reference/#/p5/applyMatrix>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by Zalastax — CHANGES_REQUESTED** [review]
@Gaweph has a general fix for 1.4 here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58331. He will be maintaining the typings by generating them using https://github.com/p5-types/p5.ts

I suggest contacting him to see how you can help out in the future!

**Comment by yama-yeah** [comment]
> @Gawephには、1.4の一般的な修正があります：[＃58331](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58331)。[彼はhttps://github.com/p5-types/p5.ts](https://github.com/p5-types/p5.ts)を使用してタイピングを生成することでタイピングを維持します[](https://github.com/p5-types/p5.ts)
> 
> 彼に連絡して、将来どのように手助けできるかを確認することをお勧めします。

**Comment by Gaweph** [comment]
I will look at this today.

For some background, the `d.ts` files are generated from the`p5.js` jsdoc comments. So this `applyMatrix` update could be applied there to prevent your changes from being overwritten when the typescript files are regenerated.

**Comment by Gaweph** [comment]
@yama-yeah This PR at p5.js should address these issues.  Once this is approved then we can get your PR completed :)

https://github.com/processing/p5.js/pull/5578

**Comment by yama-yeah** [comment]
@Gaweph 
thank you for message.
this PR is amazing!!!
I've just been reading the P5.js source code and trying to figure out how to fix it, but you're faster and more beautiful at your job than I am!
I'm sorry I couldn't be of much help.

**Pull request closed without merging**
