### PR TITLE
AngularJS IResourceServiceProvider and IActionDescriptor url parameter

### PR DESCRIPTION
**Pull request by bogh**
Hi,

You were right. $$route in ICurrentRoute is not public.
I was using in my code and thought it is ok to add to the interface. I'll change my code.

I added the IResourceServiceProvider and tests.

### CODE REVIEW

**Comment by vvakame** [comment]
*angularjs/angular-resource.d.ts*

to authors(@diegovilar @miffels). could you review this PR?

check list

* [ ] pass the Travic-CI test?

---

*angularjs/angular-route.d.ts*

to author(@park9140). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by park9140** [comment]
@bogh, I'd like to see examples from the angular website for tests on the I route change.  Otherwise, :shipit:

**Comment by Bogh** [comment]
@park9140, I haven't changed anything on the IRoute. Only the ICurrentRoute. 
This is the link to docs: https://docs.angularjs.org/api/ngRoute/service/$route

And says about the locals:
> The locals contain the resolved values of the resolve map. Additionally the locals also contain:
> $scope - The current route scope.
> $template - The current route template HTML.

**Comment by park9140** [comment]
@bogh , sorry I was not more specific. You need to add tests that reference that verify the `ICurrentRoute` locals property has a string based indexer that is used for accessing the route's resolve map.

**Comment by Bogh** [comment]
Thx. I've added the tests.

**Comment by miffels** [comment]
Sorry for the late response, I have been a little busy these days.

:shipit:

**Comment by vvakame** [comment]
@park9140 @miffels thanks!
@Bogh thanks mate!

**Pull request merged**
