### PR TITLE
Type definitions for node-config

### PR DESCRIPTION
**Pull request by RWander**
Project name: node-config
Project: https://github.com/lorenwest/node-config
Definitions by: Roman Korneev https://github.com/RWander
Definitions: https://github.com/borisyankov/DefinitelyTyped

### CODE REVIEW

**Comment by lorenwest** [comment]
I don't know much about TypeScript.  Is there someone out there that could validate these files with a code review?  

They don't appear to cause any problems, so if nobody responds in this thread in a few days I'll go ahead and merge.

**Comment by RWander** [comment]
Implemented.

**Comment by chrootsu** [comment]
Now it looks good to me. ^_^

**Comment by horiuchi** [comment]
@RWander Thank you for your contribution!
Please rename the definition file to `config/config.d.ts`.
via: https://www.npmjs.com/package/config

The reason is here: http://definitelytyped.org/guides/contributing.html#naming-the-file

**Comment by RWander** [comment]
renamed.

**Comment by horiuchi** [comment]
@RWander Thanks mate!

**Pull request merged**
