### PR TITLE
Update `@types/bun` to point to `bun-types@1.0.24`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://bun.sh/blog/bun-v1.0.24
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Ready to merge

**Review by dylan-conway — APPROVED** [review]
LGTM

**Comment by Jarred-Sumner** [comment]
Ready to merge

**Comment by Jarred-Sumner** [comment]
Ready to merge

**Pull request merged**
