### PR TITLE
Remove reachable files from OTHER_FILES.txt

### PR DESCRIPTION
**Pull request by jablko**
microsoft/types-publisher#768

### CODE REVIEW

**Review by ifiokjr — APPROVED** [review]

**Comment by tpluscode** [comment]
I added seem files in the `@rdfjs__to-ntriples` package because the tests failed otherwise. Please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42271#discussion_r377701736

**Comment by jablko** [comment]
@tpluscode Thanks! Yes, microsoft/types-publisher#768 is an attempt to address [that issue](microsoft/types-publisher#737). If it is accepted, then this PR should start passing the automated tests because those files won't need to be listed anymore.

**Review by kentcdodds — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by sandersn** [comment]
I ended up re-making this PR in #47767 because I didn't know about this one; it included a couple of additional fixes that were needed in the intervening time.

**Comment by peterblazejewicz** [comment]
thx for stepping into!

**Pull request closed without merging**
