### PR TITLE
steam-user 4.26.0 added socksProxy type

### PR DESCRIPTION
**Pull request by vladpuz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DoctorMcKay/node-steam-user/blob/a3cacf3b1e701c1e560e829cbfab49a4b1640849/resources/default_options.js#L38
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## steam-user ([<kbd>unpkg</kbd>](https://unpkg.com/browse/steam-user@latest/))
was missing the following properties:
1. EAgreementType
1. EAuthSessionGuardType
1. EAuthTokenPlatformType
1. EBanContentCheckResult
1. EBluetoothDeviceType

<details>
<summary>as well as these 14 other properties...</summary>
<p>EChatRoomMessageReactionType, EClientNotificationType, ECloudPendingRemoteOperation, ECloudStoragePersistState, EContentCheckProvider, EMessageReactionType, EProfileCustomizationStyle, EProfileCustomizationType, EPublishedFileStorageSystem, EStorageBlockContentType, EStorageBlockFileSystemType, ESystemUpdateNotificationType, ETextFilterSetting, CurrencyData</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e11bcfe181d00d05a341c5f3789e27af38d9b3b
</p>

**Review by gabritto — CHANGES_REQUESTED** [review]
Seems this change was added in version 4.26 of the original library. Please update the package version on the `index.d.ts` file's header to reflect that, and then I can approve this. Thanks.

**Review by gabritto — APPROVED** [review]
Thanks!

**Comment by vladislav-puzyrev** [comment]
Ready to merge

**Pull request merged**
