### PR TITLE
[ffprobe] Bugfix: Error can be null, info can be undefined

### PR DESCRIPTION
**Pull request by joshuaharry**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/eugeneware/ffprobe/blame/master/README.md#L27

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@joshuaharry yes, technically that's better. But it does not mean, it will improve experience.
In JS (and TS), when implementing this callback, I can safely drop last param, if interested only in errors.
If in both, value check will work nicely (with `if/else` guards or `err ?? info`
If we change to optional, how one could use `info` props quickly without using `?.` access? (at runtime, `info` is always there, if there is no error in callback)

**Comment by elibarzilay** [comment]
@joshuaharry / @peterblazejewicz  -- sounds like this should be closed?

**Comment by peterblazejewicz** [comment]
Yes, I'd close this, but this is @joshuaharry call

**Comment by joshuaharry** [comment]
Closing due to feedback, thank you.

**Pull request closed without merging**
