### PR TITLE
Add AMD suport for strophe.js

### PR DESCRIPTION
**Pull request by NZSmartie**
Unable to use strophe.js in external module project.
Simply added a line to allow 

``` TypeScript
import Strophe = require("Strophe");
```

### CODE REVIEW

**Comment by vvakame** [comment]
*strophe/strophe.d.ts*

to author(@DavidKDeutsch). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by NZSmartie** [comment]
After reviewing Strophe.js, the library detects when an AMD loader
is implemented and adjusts how it is exported. This behaviour has
been noted and thus the typescript definition has been updated to
reflect that

**Comment by DavidKDeutsch** [comment]
Looks good to me. Thanks @NZSmartie!

**Comment by vvakame** [comment]
@DavidKDeutsch thanks!
@NZSmartie thanks mate!

**Pull request merged**
