### PR TITLE
- Added namespace ‘LoadingBar’

### PR DESCRIPTION
**Pull request by stunaz**
- Added loadingBar interface Definition

### CODE REVIEW

**Comment by stephenlautier** [comment]
Looks good :+1:

**Comment by vvakame** [comment]
@stunaz please fix travis ci failed.

**Comment by stunaz** [comment]
Not sure why the tests failed, @stephenlautier  can you help with that? looks like it is the existing test which is failing.

**Comment by stephenlautier** [comment]
@stunaz I will try to help, let me try to grab your changes and test out

**Comment by stephenlautier** [comment]
@stunaz I just got your changes and found the issue.

I had done the changes within my fork in order to show you the full output how it should be (based on your changes), I can do the PR if you want but its better to learn I guess and keep your credit :).

Basically previous test got broken with your changes, reason is you namespaced it with `angular.loadingBar` when `IRequestShortcutConfig` should be part of angular module instead, since that one is extending the angular's `$http` options.

The following are my changes:
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...stephenlautier:angular-loading-bar

I also did some quick formatting changes to keep it consistent (whitespace).

**Comment by stunaz** [comment]
Thank you very much @stephenlautier , that is really helpful. I am just not sure what to do next ? close this PR  and submit another one? or this one will pass?

**Comment by stephenlautier** [comment]
@stunaz  just submit your changes to the same branch and it will be resubmitted automatically (that's how PRs work)

**Comment by stunaz** [comment]
Thank you very much @stephenlautier  for the guidance. @vvakame  we must be good to go now

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
