### PR TITLE
Fixup for node types, fs.createWriteStream function.

### PR DESCRIPTION
**Pull request by scarabedore**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/dist/latest-v7.x/docs/api/fs.html#fs_fs_createwritestream_path_options>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Flarna** [comment]
Change looks fine but it seems fs-extra-promise needs to be adapted too as CI fails.

There are some more diffs between current typings and NodeJs implementation:
- `path`: URL is allowed since NodeJs 7.6.0
- `options`: string is allowed since NodeJs 2.3.0
Not sure if you would like to include this also.

**Comment by scarabedore** [comment]
I added the URL type in the path and the string type for the options. I didn't change anything inside the test, I just checked it runs using the "tsc" command.

**Comment by Flarna** [comment]
Changes in node look good to me.
I expect related failed tests need to be fixed before this will be merged.

**Comment by scarabedore** [comment]
I also found a mistake when I used UDP sockets. I assume "bind" can be only called with a callback if I understand well: https://nodejs.org/dist/latest-v8.x/docs/api/dgram.html#dgram_socket_bind_port_address_callback

**Comment by paulvanbrenk** [comment]
@scarabedore can you update `DefinitelyTyped/DefinitelyTyped/types/fs-extra-promise/fs-extra-promise-tests.ts` to match your change from `encoding` to `defaultEncoding`

**Review by Flarna — APPROVED** [review]

**Pull request merged**
