### PR TITLE
fix(node): add overloads for inherited methods on buffer

### LINKED ISSUE #33296: @types/node Buffer is missing methods from Uint8Array
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    * @jkomyno
      @a-tarasyuk
      @alvis
      @r3nya
      @btoueg
      @BrunoScheufler
      @smac89
      @tellnes
      @Touffy
      @DeividasBakanas
      @eyqs
      @Flarna
      @Hannes-Magnusson-CK
      @KSXGitHub
      @hoo29
      @kjin
      @ajafff
      @isLishude
      @mwiktorczyk
      @matthieusieben
      @mohsen1
      @n-e
      @octo-sniffle
      @parambirs
      @eps1lon
      @SimonSchick
      @ThomasdenH
      @WilcoBakker
      @wwwy3y3
      @ZaneHannanAU
      @jeremiergz
      @samuela
      @kuehlein

`Uint8Array` (or `Array`) methods like `reverse` are missing on `Buffer`, so instead a `Uint8Array` is returned, even though a call to `reverse` returns `Buffer` like so:

`Buffer.from([0x00, 0x01, 0x02, 0x03, 0x04]).reverse() instanceof Buffer === true`

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33296
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes #33296

### CODE REVIEW

**Review by Touffy — APPROVED** [review]
Thanks for this little fix.

CI failure seems unrelated.

**Review by Flarna — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Comment by SimonSchick** [comment]
@jessetrinity can you merge this one? Build failure is unrelated :)

**Comment by jessetrinity** [comment]
@SimonSchick we are expecting a fix for the CI issue within the next day. Will this PR be okay waiting for it?

**Comment by SimonSchick** [comment]
@jessetrinity Sure, just wanted to make sure this one doesn't fall through the cracks :)

**Comment by SimonSchick** [comment]
I am getting seriously annoyed by this.

**Pull request merged**
