### PR TITLE
[ol] fixed `typeof` types and nullable properties

### PR DESCRIPTION
**Pull request by hanreev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [OpenLayers](https://github.com/openlayers/openlayers), [types-ol](https://github.com/hanreev/types-ol)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@hanreev Can you link exact `why` behind the change, it would be easier to see why `null` is required thx!

**Comment by hanreev** [comment]
@peterblazejewicz
#53356
#53409
`null` is necessary when using `strict` or `strictNullChecks` set to `true` in `tsconfig.json`

**Comment by peterblazejewicz** [comment]
I understand consequences of using things in the wild.
I'd love to see something I can quickly grasp:
https://github.com/openlayers/openlayers/blob/v6.5.0/src/ol/source/ImageStatic.js#L17

**Review by peterblazejewicz — APPROVED** [review]

**Comment by hanreev** [comment]
Ready to merge

**Pull request merged**
