### PR TITLE
[@types/sequelize] Define Models and add name and associate(models) for Model

### LINKED ISSUE #24137: [@types/sequelize] Sequelize.Model can have "name" attribute and "associate?" method
- [x] I tried using the `@types/sequelize ` package and had problems.
- [x] I tried using the latest stable version of tsc.
- [x] I have a question that is inappropriate for StackOverflow.
- [x] Authors: @samuelneff @CodeAnimal @drinchev @babolivier @kukoo1 @oktapodia @MorpheusXAUT @TitaneBoy @zjy01 @nidzov @Raigen @todd

---

With the [recommended project structure](https://github.com/sequelize/express-example/tree/master/models) (also set by the CLI with `sequelize init`), models are defined in separate files and each one exports a function for `sequelize.Sequelize.import`.

But models defined like this are also expected to have an `associate` (optional) method. See:
- [index.js#L29](https://github.com/sequelize/express-example/blob/master/models/index.js#L29)
- [task.js#L7](https://github.com/sequelize/express-example/blob/master/models/task.js#L7)
- [user.js#L7](https://github.com/sequelize/express-example/blob/master/models/user.js#L7)

Actually, we got `The property 'associate' does not exist on value of type 'Model<{}, {}>'.`.

Also, a model always has a `name` attribute. See:
- [index.js#L24](https://github.com/sequelize/express-example/blob/master/models/index.js#L24)

As a workaround, I use these custom declarations:

```ts
declare module "sequelize" {
    interface Model<TInstance, TAttributes> {
        name: string;
        associate?(models: Models): void;
    }

    interface Models {
        [index: string]: Model<any, any>;
    }
}
```

### PR DESCRIPTION
**Pull request by xthezealot**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

---

Fixes #24137.

I also correctly reindented some other comments, sorry for the noise.
Important modifications are on lines [3661](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24160/files#diff-0e3744815a33a1dfe3285ef4f51888e9R3661), [3680](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24160/files#diff-0e3744815a33a1dfe3285ef4f51888e9R3680) and [4064](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24160/files#diff-0e3744815a33a1dfe3285ef4f51888e9R4064).

### CODE REVIEW

**Review by todd — APPROVED** [review]
Has a merge conflict, but seems reasonable.

**Comment by SimonSchick** [comment]
@arthurwhite @armanio123 please revert this:

```
> void(s = require('sequelize'))
undefined
> s.version
'3.32.1'
> s.Model.associate
undefined

> void(s = require('sequelize'))
undefined
> s.version
'4.35.6'
> s.Model.associate
undefined
```

this function does not natively exist on models at all, it is only used in examples and tutorials but *always* has to be manually defined, you are better off augmenting this method onto individual models if you use this pattern.

**Comment by arthurwhite** [comment]
It's not only used in examples but also [generated by the CLI](https://github.com/sequelize/cli/blob/71770def7ac6c8bcc3f8d87dd9809a83ff6f282f/src/assets/models/model.js#L13), with `sequelize init`.
And by this, this pattern (so this method) has a great chance to be defined.

Now, if one doesn't structure its package like this, fine: this method can be `undefined`, like many others.

**Comment by SimonSchick** [comment]
Not everyone uses the CLI.
I also don't think adding a method because `a user might define it` is something DT should do.

**Comment by SimonSchick** [comment]
@andy-ms @armanio123 can we have some input?

**Comment by SimonSchick** [comment]
@andy-ms pls

**Comment by andy-ms** [comment]
It looks like the method is already defined optional (`associate?`), so you should already be getting a compile error if you try calling it with `--strictNullChecks` on. An optional property requires that when you *assign* it it must have a certain type, but doesn't guarantee that the property will actually be present when you access it.

**Comment by andy-ms** [comment]
Just to be clear, the `associate` property is actually read by the framework at some point, right? Otherwise it looks like it's dead code based on that example.

**Comment by todd** [comment]
Just gonna chime in here. @SimonSchick is correct that the `associate` method doesn't exist anywhere in the Sequelize codebase. However, if using `sequelize-cli`, which is a separate package, the CLI bootstraps your application with a file that calls the `associate` method on each model it imports. The reason it does this is so that the application can ensure it's not calling an association method on a model before a dependent model has been imported properly. This seems like a sane pattern to me, though I've always used the CLI to bootstrap projects, so it didn't occur to me that this wasn't a construct of the package itself when I approved this.

Frankly, I can go either way on this. To @SimonSchick's point, it's not onerous to spin up your own interface that extends `Model` and define your own `associate` attribute on it.

**Pull request merged**
