### PR TITLE
aurelia-flux definitions

### PR DESCRIPTION
**Pull request by tfrydrychewicz**
Adding aurelia-flux definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
*aurelia-flux/aurelia-flux.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/aurelia-flux
  * http://bower.io/search/?q=aurelia-flux
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (aurelia-flux/aurelia-flux-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
please rename aurelia-flux/aurelia-flux.test.ts to aurelia-flux/aurelia-flux-tests.ts

**Comment by tfrydrychewicz** [comment]
I did as you asked, but travis build is stil in progress.

**Comment by tfrydrychewicz** [comment]
As aurelia-flux provides decorators, aurelia-flux-tests.ts conaints some.

**Comment by vvakame** [comment]
please use .tscparams like this https://github.com/borisyankov/DefinitelyTyped/blob/master/core-decorators/core-decorators-tests.ts.tscparams

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
