### PR TITLE
Add .observe() to Observable (which is added in 3.3.0)

### PR DESCRIPTION
**Pull request by pablobirukov**
Improvement to existing type definition.
- Added method [`Observe`](http://rpominov.github.io/kefir/#observe) (was added in 3.3.0)

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by r00ger** [comment]
@vvakame please merge

**Comment by AyaMorisawa** [comment]
:+1:
sorry for late reply

**Comment by r00ger** [comment]
Just a reminder. @vvakame please merge :)

**Pull request merged**
