### PR TITLE
Update stream.d.ts to match spec

### PR DESCRIPTION
**Pull request by lifeiscontent**
fix declaration for Writable to match spec: https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by Flarna — CHANGES_REQUESTED** [review]
Why this change? Which use case is now possible which was not before? Could you add a test for this case please?

**Comment by lifeiscontent** [comment]
@Flarna the declaration was wrong as noted in the link I specified above.

when you call .end() you can either pass nothing, or a chunk which is written to the end of the stream

**Comment by Flarna** [comment]
@lifeiscontent It's also allowed to pass only a callback.

**Comment by lifeiscontent** [comment]
@Flarna so does that mean that this signature supports all 3 args to to be the first?

```
writable.end([chunk][, encoding][, callback])
```

I just want to make sure I am understanding this correctly, once I understand, I'll update the definition to match the spec.

**Comment by Flarna** [comment]
@lifeiscontent `encoding` makes only sense if `chunk` is present but it's optional.
So the following variants are allowed to my understanding (and already supported by current definition):
```
end()
end(cb)
end(chunk)
end(chunk, encoding)
end(chunk, cb)
end(chunk, encoding, cb)
```

**Comment by lifeiscontent** [comment]
@Flarna so how would I type this?

```
  res.write = (...args) => {
    if (typeof args[0] === 'string') {
      resBody += args[0];
    }
    return oldWrite.apply(res, args);
  };
```

because currently this is whats causing the error for me

**Comment by Flarna** [comment]
@lifeiscontent Don't know if I understand your problem but `res.write = (...args: any[]) => {` silences typescript.
The append to `resBody` is protected by a typeguard so it's fine.
The type of `res.write()` should not change because of the assignment of a function accepting more inputs so users of `res.write()` should be fine.
As you don't tinker with `args[]` in your function `oldWrite.apply` should be also ok even types are lost here so no help of type system. Don't know if this can be improved.

**Comment by lifeiscontent** [comment]
@Flarna I’m building a testing utility which intercepts write and end for res so I can check the body content in tests

**Comment by Flarna** [comment]
@lifeiscontent But what is the actual problem? Are you unsure which argument you should check or how to write this down in typescript?

**Comment by j-oliveras** [comment]
Reading node [source code](https://github.com/nodejs/node/blob/8dae89b396df64e6a9e44cb94efe27809a5a3d89/lib/_http_outgoing.js#L671-L679) the current types are valid as @Flarna said. Encoding are only used if chunk is defined.

**Comment by lifeiscontent** [comment]
@Flarna how to write it in typescript, the oldWrite.apply thinks its first argument should be a function

**Comment by Flarna** [comment]
@lifeiscontent What's wrong with`res.write = (...args: any[]) => {`?

**Pull request closed without merging**
