### PR TITLE
[prosemirror-view] Re-add `| undefined` for TypeScript 4.4

### PR DESCRIPTION
**Pull request by aried3r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Re-add `| undefined` for TypeScript 4.4. Was added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54346/files#diff-45cce90cfdee25da2b6dc0665f0a09dc7f98469c97e47defb780342c821b94d2 and removed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54668.

### CODE REVIEW

**Review by timjb — APPROVED** [review]
LGTM. Thanks for your contribution!

**Review by orta — APPROVED** [review]
Cool 👍🏻

**Comment by aried3r** [comment]
Ready to merge

**Review by timjb — APPROVED** [review]

**Review by orta — APPROVED** [review]

**Comment by aried3r** [comment]
Ready to merge

**Pull request merged**
