### PR TITLE
Added react-native-popup-dialog

### PR DESCRIPTION
**Pull request by PaitoAnderson**
Resolves jacklam718/react-native-popup-dialog#68

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by sandersn** [comment]
This code looks good, but we shouldn't merge this if jacklam718/react-native-popup-dialog#68 is going to get merged. DefinitelyTyped is only supposed to have types for libraries that don't bundle their own types. Do you know what's going to happen with jacklam718/react-native-popup-dialog#68?

**Comment by PaitoAnderson** [comment]
@sandersn Thanks for looking it over. I bumped my original PR asking if it will be merged.

**Comment by bowdenk7** [comment]
@PaitoAnderson - we can go ahead and merge this, and if your other PR gets merged we can delete this later. What do you think?

**Comment by minestarks** [comment]
No traction on the other PR - merging. We can always remove later.

**Pull request merged**
