### PR TITLE
[matteodisabatino__gc_info] add exported constant path and minor fixes

### PR DESCRIPTION
**Pull request by matteodisabatino**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/matteodisabatino/gc_info>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by matteodisabatino** [comment]
Hi @orta, can please have I an help?

**Review by orta — APPROVED** [review]
Accepting, but I'm a little surprised that this is on DT, you own the module - the .d.ts can be embedded in packaged version 👍🏻

**Comment by matteodisabatino** [comment]
@orta first of all, thanks 😊 . In second, I didn't know... sorry but I have a lot of experience with JS but none with TS (actually this is my first TS work). Since we are talking about it... what is difference between embed the d.ts in the package.json and create a DT package?

**Comment by matteodisabatino** [comment]
Ready to merge

**Pull request merged**
