### PR TITLE
Update `WebAuthenticationBroker` class in winrt.d.ts for Windows Phone 8.1

### PR DESCRIPTION
**Pull request by nobuoka**
On Windows Phone 8.1 platform, [the `WebAuthenticationBroker` class](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.security.authentication.web.webauthenticationbroker.aspx) has [`authenticateAndContinue` methods](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.security.authentication.web.webauthenticationbroker.authenticateandcontinue.aspx) and [`authenticateSilentlyAsync` methods](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.security.authentication.web.webauthenticationbroker.authenticatesilentlyasync.aspx). I added definitions of these methods.

In addition, [the `WebAuthenticationBroker.authenticateAndContinue(Uri, Uri, ValueSet, WebAuthenticationOptions)` method](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn608116.aspx) receiving a `ValueSet` object as third parameter, I added definition of [the `ValueSet` class](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.foundation.collections.valueset.aspx).

### CODE REVIEW

**Comment by vvakame** [comment]
@adamhewitt627 @craigktreasure @mhegazy can anyone review this PR?

**Comment by vvakame** [comment]
and https://github.com/borisyankov/DefinitelyTyped/pull/4221

**Comment by mhegazy** [comment]
Can you please fix the failing Travis CI tests and update the PR!

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
