### PR TITLE
@types/sequelize Added generic types for various option classes

### PR DESCRIPTION
**Pull request by nmussy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Incoming PR for [RobinBuschmann/sequelize-typescript](/RobinBuschmann/sequelize-typescript)

The following PR adds additional, stronger typings used for [RobinBuschmann/sequelize-typescript](/RobinBuschmann/sequelize-typescript), that will notably be used to type its [@Scope decorators](/RobinBuschmann/sequelize-typescript#scopes)

There is still a lot of improvements to make here, so any help would be greatly appreciated!

### CODE REVIEW

**Comment by drinchev** [comment]
👍

**Comment by TitaneBoy** [comment]
Hi..This PR looks to not work anymore with what was done before. When something like:
`Model.findAll({attributes: ['id', 'name']})` worked before, it doesn't work anymore with this PR. Documentation about changes looks missing or weak. Is there any way to reverse this PR ?

**Comment by nmussy** [comment]
Hi @TitaneBoy, thanks for the help.

My changes shouldn't have been breaking, at all. The stronger typings I've added to `FindOptionsAttributesArray` are supposed to ensure that the list of attributes passed are attributes for the model.

According to the [sequelize doc](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll): 

> options.attributes
> A list of the attributes that you want to select, or an object with include and exclude keys. To rename an attribute, you can pass an array, with two elements - the first is the name of the attribute in the DB (or some kind of expression such as Sequelize.literal, Sequelize.fn and so on), and the second is the name you want the attribute to have in the returned instance

Are your two properties `'id', 'name'` declared in your `measurement` model?

**Comment by TitaneBoy** [comment]
Hi @nmussy . Thank you for your quick answer.

My models didn't change at all since many months..

In my case, my measurement model has the two declared properties 'id' and 'name', as you can see here:

image

**Comment by TitaneBoy** [comment]
As I said before, it is since your changes that my stuff doesn't work anymore. Maybe I am missing something in my comprehension of your changes..Then any help will be appreciated :-)

**Comment by nmussy** [comment]
Alright, I just ran a quick little test, and it seems that without explicit typing, the `.define()` method infers the type of the `TAttributes` generic as any and returns a `Model<any, any>`. For your code to compile with my added checks, you need to explicitly type your model like so:

```ts
const attributes = {
    id: dataTypes.NUMBER,
    name: dataTypes.STRING
};

const measurement = sequelize.define<Sequelize, typeof attributes>('measurement',  attributes);
measurement.findAll({attributes: ['id', 'name']});
```
(Here's the typing for the `.define()` method: [L5889-L5890](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L5889-L5890))

It seems to be a known TypeScript issue: [#9366](/Microsoft/TypeScript/issues/9366).

I can't see any way to work around this issue without compromising the added type checking. What's the best course of action here? I don't feel great about having this non-backwards compatible version out in the wild.

**Comment by TitaneBoy** [comment]
Honestly, I don't see any solution to solve this issue. Since my model is defined in a separted file, I'm doing something like this:

image

And I've tried your solution given up above like this:

image

But even with this changes, I still have the same typescript error as you can see here:

image

It still doesn't recognize the string array type for 'attributes' attribute. Do you have any idea why ?

Like you, I don't feel confortable too with an non-backwards compatible version. I understand your needs but maybe we should revert these changes in order to find a better way to integrate them ? What do you think ?

**Comment by nmussy** [comment]
Yes, it doesn't fix your issue because the [import](/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L5922) method also returns a `Model<TInstance, TAttributes>`, which you need to explicitly type again, and that would mean having to export your attributes too, or at least their type.

Would bumping the @types package to a new minor or major version be appropriate? There are several other weak types I had noticed while trying some things out with [RobinBuschmann/sequelize-typescript](/RobinBuschmann/sequelize-typescript), and I'm not sure what the best course of action is here.

In the meantime, it'd be a good idea to revert this whole PR. Agreed?

**Comment by TitaneBoy** [comment]
I'm agreed that in the meantime, it will be a good idea to revert this whole PR, in order to find a better way to meet your needs and the previous behavior of @types/sequelize package.

**Comment by SimonSchick** [comment]
Also this seems to break nested `attributes` properties inside `include` objects, it tries to restrict to the root model instead of the one specified in the `include`..

**Comment by SimonSchick** [comment]
@nmussy isn't just reverting the `attributes` restriction sufficient?

**Comment by nmussy** [comment]
@SimonSchick You're absolutely right about the `IncludeOptions`, they shouldn't have been typed with the parent model.

Concerning the revert, the only significant change to the definition were made to `attributes`, `group` and as you mentioned, `include`. The strongly typed group would cause the same issue as the one noticed by @TitaneBoy. All other changes were just meant to pass along the generics down the different options types.

**Comment by drinchev** [comment]
Hey all can you confirm that your code is working against https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22786 

If it is I will vote for reverting. Sorry all and @nmussy on my first look it looked like nothing breaking was included.

**Comment by nmussy** [comment]
No problem @drinchev, it was definitely on me, I hadn't anticipated these issues. I saw all the [RobinBuschmann/sequelize-typescript](/RobinBuschmann/sequelize-typescript) tests passing and just rolled with it.

**Pull request merged**
