### PR TITLE
prompts: make `PromptObject.message` required

### PR DESCRIPTION
**Pull request by ThomasGormley**
`prompts` [will throw an error](https://github.com/terkelg/prompts/blob/master/lib/index.js#L47-L49) if `typeof question.message !== 'string'` however the types label it as optional.

Having trouble running tests locally
```
Error: /Users/thomas/dev/DefinitelyTyped/node_modules/@types/node/assert.d.ts:1:1
ERROR: 1:1    no-outside-dependencies  File /Users/thomas/dev/DefinitelyTyped/node_modules/@types/node/assert.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/thomas/dev/DefinitelyTyped/node_modules/@types/node/async_hooks.d.ts:1:1
ERROR: 1:1    no-outside-dependencies  File /Users/thomas/dev/DefinitelyTyped/node_modules/@types/node/async_hooks.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md
```
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/terkelg/prompts/blob/master/lib/index.js#L47-L49
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by Whoaa512 — APPROVED** [review]

**Comment by Whoaa512** [comment]
Ready to merge

**Comment by sapphi-red** [comment]
@ThomasGormley @Whoaa512 I don't think this type is correct.
When the `type` property returns a falsy value, that part of code doesn't run.
https://github.com/terkelg/prompts/blob/7c167091b852ed68bd7fa77c71fc50022200f61d/lib/index.js#L31-L36

For example, this code is valid.
```js
prompt({
  type: () => false,
  name: 'foobar'
})
```
[A real world usage](https://github.com/vitejs/vite/blob/0755cf2bbd9a5cca92bd4061b03be25dd92eb37d/packages/create-vite/src/index.ts#L231-L239)

**Comment by ThomasGormley** [comment]
> @ThomasGormley @Whoaa512 Hi 👋. I don't think this type is correct. When the `type` property returns a falsy value, that part of code doesn't run. https://github.com/terkelg/prompts/blob/7c167091b852ed68bd7fa77c71fc50022200f61d/lib/index.js#L31-L36
> 
> For example, this code is valid.
> 
> ```js
> prompt({
>   type: () => false,
>   name: 'foobar'
> })
> ```
> 
> [A real world usage](https://github.com/vitejs/vite/blob/0755cf2bbd9a5cca92bd4061b03be25dd92eb37d/packages/create-vite/src/index.ts#L231-L239)

Hmm yeah I didn't notice that, apologies. I don't think theres a way to set this property conditionally here so maybe its best to just revert?

**Comment by sapphi-red** [comment]
@ThomasGormley Yes, I think so. I can't think of any other way than revert.

**Pull request merged**
