### PR TITLE
React plotly.js

### PR DESCRIPTION
**Pull request by jonfreedman**
Sharing my definitions for react-plotly.js as the project team do not maintain their own types.  Constructed using [docs](https://github.com/plotly/react-plotly.js/) plus plotly.js typedef.

### CODE REVIEW

**Comment by andy-ms** [comment]
Thanks!

**Comment by mouradmourafiq** [comment]
@joaolennons I did not manage to get `react-plotly.js` to work using these types def. I am currently receiving an error:

```
 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Any ideas how I can solve this?

**Comment by jonfreedman** [comment]
Please post a copy of your dependencies and ts code that's failing and I'll have a look.

**Comment by mouradmourafiq** [comment]
Thank you for the help, here's the dependencies:

```
"devDependencies": {
    "@types/node": "8.10.20",
    "@types/redux-logger": "3.0.6",
    "awesome-typescript-loader": "3.5.0",
    "bootstrap": "3.3.7",
    "css-loader": "0.28.11",
    "file-loader": "0.11.2",
    "font-awesome": "4.7.0",
    "fontawesome": "4.7.2",
    "ify-loader": "^1.1.0",
    "less": "2.7.3",
    "less-loader": "4.1.0",
    "redux-logger": "3.0.6",
    "source-map-loader": "0.2.3",
    "style-loader": "0.18.2",
    "through2": "^2.0.3",
    "tslint": "5.10.0",
    "tslint-react": "3.6.0",
    "typescript": "2.9.2",
    "uglify-js": "3.4.2",
    "url-loader": "0.5.9",
    "webpack": "3.12.0",
    "webpack-dev-server": "2.11.2"
  },
  "dependencies": {
    "@types/history": "4.6.2",
    "@types/js-cookie": "2.1.0",
    "@types/js-yaml": "^3.11.2",
    "@types/lodash": "4.14.110",
    "@types/plotly.js": "^1.38.8",
    "@types/query-string": "6.1.0",
    "@types/react": "16.4.2",
    "@types/react-bootstrap": "0.32.10",
    "@types/react-dom": "16.0.6",
    "@types/react-plotly.js": "2.2.1",
    "@types/react-redux": "6.0.2",
    "@types/react-router": "4.0.27",
    "@types/react-router-bootstrap": "0.24.5",
    "@types/react-router-dom": "4.2.7",
    "@types/redux-form": "7.3.0",
    "@types/sprintf-js": "0.0.27",
    "history": "4.7.2",
    "js-cookie": "2.2.0",
    "js-yaml": "^3.12.0",
    "lodash": "4.17.10",
    "moment": "2.22.2",
    "normalizr": "3.2.4",
    "plotly.js": "^1.41.0",
    "query-string": "5.1.1",
    "react": "16.4.01",
    "react-bootstrap": "0.32.1",
    "react-dom": "16.4.2",
    "react-plotly.js": "^2.2.0",
    "react-redux": "5.0.7",
    "react-router": "4.3.1",
    "react-router-bootstrap": "0.24.4",
    "react-router-dom": "4.3.1",
    "redux": "4.0.0",
    "redux-form": "7.4.2",
    "redux-thunk": "2.3.0",
    "sprintf-js": "1.1.1",
    "whatwg-fetch": "2.0.4"
  }
```
And the code is just a simple component:

```javascript
import * as React from 'react';
import Plot from 'react-plotly.js';

export default class PlotChart extends React.Component<{}, {}> {
  public render() {
    return (
      <Plot
        data={[
          {
            x: [1, 2, 3],
            y: [2, 6, 3],
            type: 'bar',
            marker: {color: 'red'},
          },
          {type: 'bar', x: [1, 2, 3], y: [2, 5, 3]},
        ]}
        layout={{width: 320, height: 240, title: 'A Fancy Plot'}}
      />
    );
  }
}

```

**Comment by mouradmourafiq** [comment]
@jonfreedman any ideas, I am still unable to figure out what is the issue.

**Comment by jonfreedman** [comment]
Your example matches the tests & looks fine, can you try and reproduce in a CodePen?

**Comment by mouradmourafiq** [comment]
Just to update the thread, I decided not to use the types in the end. I could not figure out what's the problem, thanks for the help.

**Pull request merged**
