### PR TITLE
Enzyme: Restore strongly typed props for classes, misc. updates

### PR DESCRIPTION
**Pull request by jwbay**
This is mainly to fix
`wrapper.find(MyClassComponent).props().someCallbackk(); //oops, typo`
not being caught with the latest TypeScript + definitions. I am not sure where things went wrong for that, but there is a note at the top of index.d.ts around it. The first part of the fix was #14202, but it wasn't quite enough.

Additional changes:

* Add Pick typings for setState/setProps, mirrors #13155
* Fix Cheerio wrapper to reference Cheerio typings (this was incorrect from day 1 I think -- the interfaces are not the same). This let me delete tons of overloads from CommonWrapper, which should help with typecheck performance (Enzyme types have historically caused problems there)
* Remove deprecated APIs (they've been gone for about a year)
* Add tslint and fix errors
* Normalize React+Shallow wrapper tests and add some missing overload tests
* If we're filtered down to a wrapper containing stateless components, the type of wrapper.state() is never

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by NoHomey** [comment]
LGTM 👍

**Comment by jwbay** [comment]
@NoHomey Mind taking a look at the last commit as well?

**Review by NoHomey — APPROVED** [review]

**Comment by hesher** [comment]
This effectively breaks any code that tries to run `.find()` on a `CommonWrapper`, is that by design?

**Comment by jwbay** [comment]
Kind of. CommonWrapper's purpose changed since CheerioWrapper was effectively killed (it was farmed out to its proper type definition). The intention for CommonWrapper was to become a private base interface that uses polymorphic `this` to provide common methods between ShallowWrapper and ReactWrapper.

Are you using CommonWrapper like this?

```ts
let foo: CommonWrapper<any, any>;
...
foo = shallow(...);
...
foo = mount(...);
```

I think we might be able to cover this case by renaming the current base interface to something like _BaseWrapper and recreating CommonWrapper as a union type of `ShallowWrapper | ReactWrapper`. In the meantime, a workaround for you might be using the union type yourself.

**Comment by hesher** [comment]
Yeah. I'm using `CommonWrapper` to hide implementation for Drivers in my project.
I don't want the user of the driver to know if it used `shallow()` or `mount()`

**Pull request merged**
