### PR TITLE
[Parse] Add missing context on AfterSaveRequest and BeforeSaveRequest

### PR DESCRIPTION
**Pull request by jlnquere**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.parseplatform.org/cloudcode/guide/#using-request-context
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by agoldis — COMMENTED** [review]
Thanks for the PR, @jlnquere!
Considering https://github.com/parse-community/parse-server/blob/a1e1cef6d2434a36ea12dab94325c3c9965faa1e/src/triggers.js#L190
what do you think about using

```
context: object
```

It probably better represents the value type...

**Comment by jlnquere** [comment]
@agoldis I'm not sure about that. In my understanding: `context` can be anything, even a primitive type. 

Tell me if I'm wrong !

**Comment by agoldis** [comment]
@jlnquere Looking at the [implementation](https://github.com/parse-community/parse-server/blob/a1e1cef6d2434a36ea12dab94325c3c9965faa1e/src/triggers.js#L190) and the [documentation](https://docs.parseplatform.org/cloudcode/guide/#using-request-context) it can't

**Comment by jlnquere** [comment]
@agoldis Good point 👍 I changed for `object` type. 

Thanks for the review !

**Review by agoldis — APPROVED** [review]

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
