### PR TITLE
[Web3]: Update definition.

### PR DESCRIPTION
**Pull request by jpgonzalezra**
Module web3.
Component Eth.
getPastLog method.

the definitions does not allow null. the nodes of ethereum have behavior when position 0 the an topic is null.

### CODE REVIEW

**Comment by Agusx1211** [comment]
Just for clarification, any position of the topics should accept null, this acts as a OR option.
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs

**Comment by Levino** [comment]
These type definitions are for  `web3@1.x` so the above link does not really apply. But the docs for `web3` also explain this behaviour https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html?highlight=filter#id16

**Review by levino — CHANGES_REQUESTED** [review]
I agree on the change and thank you for your contribution. But I must require some tests in order to formally approve these changes.

**Comment by jpgonzalezra** [comment]
Done @Levino. 
I'm waiting

Thank you.

**Review by levino — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
