### PR TITLE
Express - remove unnecessary variables in Request

### PR DESCRIPTION
**Pull request by frogcjn**
as @gforster1993 asked (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/203818d338c3454f13298bfe743755260b90382a)

remove unnecessary variables in Request.

### CODE REVIEW

**Comment by vvakame** [comment]
Do you know any reference?

**Comment by frogcjn** [comment]
@vvakame , there is no reference means this properties need to be removed.

**Comment by vvakame** [comment]
```
let express = require("express");
let app = express();
console.log(app.locals); // locals is exists.
```

**Comment by frogcjn** [comment]
refer to @gforster1993

**Comment by gforster1993** [comment]
Yes it does exist however when I try to extend the Express interfaces using 
`declare namespace Express {
    export interface Response {
        locals: ResponseLocals;
    }
    export interface Application {
      locals: ApplicationLocals;
  }
}` 
both locals are overridden and evaluate to any. I just assumed the locals shouldn't be there if they had no associated type, but perhaps it's the way that I'm extending the interface which is wrong?

**Comment by vvakame** [comment]
I non't know I'm correctly understanding...
like this? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10320/files

**Comment by paulvanbrenk** [comment]
@gforster1993 if you cast to the specific type you will get your implementation. The behavior you're seeing is expected, since a specific type can always be assigned to `any`.

Closing this PR.

**Pull request closed without merging**
