### PR TITLE
Updating definitions for js-beautify

### PR DESCRIPTION
**Pull request by hansrwindhoff**
case 1. Add a new type definition.
- [x ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
:+1:

**Comment by JoshuaKGoldberg** [comment]
Two small things @hansrwindhoff:
* Build is failing from a missing line break
* Can you change the title of this PR to mention js-beautify? It'll make it easier to search through DT PRs.

**Comment by hansrwindhoff** [comment]
cool, I have done that...

**Comment by JoshuaKGoldberg** [comment]
:+1:

**Pull request merged**
