### PR TITLE
Add missing option callback arg to setProps

### PR DESCRIPTION
**Pull request by thovden**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18214
- [x] Increase the version number in the header if appropriate. - N/A
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }` - N/A

### CODE REVIEW

**Comment by MartynasZilinskas** [comment]
@thovden Could you provide API docs or specific part from source code for this change? Because I don't see documented.

**Comment by huhuanming** [comment]
@MartynasZilinskas   Look here...
image

**Comment by thovden** [comment]
The API is documented here: http://airbnb.io/enzyme/docs/api/ReactWrapper/setProps.html

**Review by MartynasZilinskas — APPROVED** [review]

**Review by MartynasZilinskas — CHANGES_REQUESTED** [review]
In further inspection: You added to `CommonWrapper` `setProps` callback. But this change should only apply to `ReactWrapper`: https://github.com/airbnb/enzyme/blob/master/src/ReactWrapper.jsx#L246. Because `ShallowWrapper` doesn't have this argument: https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L306.

**EDIT**: Please update package tests with your change.

**Comment by BendingBender** [comment]
Fixes #18214

**Comment by mhegazy** [comment]
@thovden please address the reviewer comment above.

**Comment by thovden** [comment]
@mhegazy new commit addresses comments from @MartynasZilinskas

**Review by MartynasZilinskas — APPROVED** [review]
Now it looks good. :+1: Thanks.

**Comment by thovden** [comment]
@MartynasZilinskas can you merge this PR?

**Comment by MartynasZilinskas** [comment]
I don't have rights to merge PR.

**Comment by thovden** [comment]
@MartynasZilinskas ok - assuming some automagic will handle it

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
