### PR TITLE
allow strictDi controller

### PR DESCRIPTION
**Pull request by pocesar**
update the test as well. the ui-router recent change broke my code, since I use strictDi everywhere

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-ui-router/angular-ui-router.d.ts*

to author(@michelsalib). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by pocesar** [comment]
this must be merged, or angular apps bootstrapped with strictDi won't work

**Comment by michelsalib** [comment]
@vvakame Is it ok to strictly force TS 1.6?

**Comment by vvakame** [comment]
yes, DefinitelyTyped support latest tsc version only.

**Comment by michelsalib** [comment]
So we are good.

**Comment by vvakame** [comment]
@michelsalib thanks!
@pocesar thanks mate!

**Pull request merged**
