### PR TITLE
[hapi__h2o2] Upgrade type definition, add missing options, remove tslint rules

### PR DESCRIPTION
**Pull request by martin-badin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test hapi__h2o2`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://hapi.dev/module/h2o2/>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## hapi__h2o2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__h2o2@latest/))
was missing the following properties:
1. plugin
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6d18a3b3a12b89dbedc0a5c87fad4fda0c74f66b
</p>

**Comment by martin-badin** [comment]
@peterblazejewicz this one as well. Thank you so much

**Comment by peterblazejewicz** [comment]
that's ok, noted, but this needs owners input first

**Comment by martin-badin** [comment]
Re-ping @jasonswearingen @AJamesPhillips @garthk @lenovouser

**Comment by garthk** [comment]
I regret I haven't used Node for years and can't claim a stake in the matter. I defer to anyone actually using Hapi.

**Comment by martin-badin** [comment]
@peterblazejewicz Please. This one as well. Thanks

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@martin-badin thanks!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
