### PR TITLE
Support global sprintf and vsprintf for use in  browser.

### PR DESCRIPTION
**Pull request by edvinv**

### CODE REVIEW

**Comment by vvakame** [comment]
@jasonswearingen could you review this PR?

**Comment by edvinv** [comment]
sprintf-js adds two global function (sprintf and vsprintf) if used in browser with script tag.  So this PR adds those two global functions so that sprintf-js.d.ts works correctly in node and also in browser.

**Comment by jasonswearingen** [comment]
I'm not sure about this, as it (looks like) will add the sprintf and vsprintf globals when using ///<reference> of the d.ts 

@vvakame do you have guidance on this?   It is adding browser <script> visibility at the expense of adding phantom globals in other environments.

**Comment by edvinv** [comment]
@jasonswearingen, I'm aware of this,  but this is not much different that it is in other libraries. For example, underscore also provide global variable '_', used in browser but add phantom '_' in other environments. So IMHO d.ts files should work in all environments.

**Comment by jasonswearingen** [comment]
I'm fine with the checkin, just not sure about the trade off, so if that's standard, ok with me!

**Comment by vvakame** [comment]
thanks mate!
@jasonswearingen We don't have guidance now. :crying_cat_face: 
Many definitions have phantom globals.
You may be interested in here. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/moment

**Pull request merged**
