### PR TITLE
Update `wechat-miniprogram` to 3.0

### PR DESCRIPTION
**Pull request by wechat-miniprogram-admin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-system__core ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-system__core@latest/))
was missing the following properties:
1. merge
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9e48186f2144450b1bce9f7ea6994fbf588f1cc5
</p>

**Review by bragle — COMMENTED** [review]
I don't see any changes in either of the styled-system__core files? Why are these included in the PR?

**Comment by wechat-miniprogram-admin** [comment]
@bragle seems like it is originally written in `CRLF`, and git converted it to `LF` by `autocrlf` and committed. Should I change it back and re-PR this?

**Comment by bragle** [comment]
@wechat-miniprogram-admin I don't see any point in changing it, so you can re-PR if it's not too much of a hassle 😺

**Comment by wechat-miniprogram-admin** [comment]
@bragle got it, then I am closing this and will made an another PR after fixing this. thanks for review~

**Pull request closed without merging**
