### PR TITLE
Add typings for react-request

### PR DESCRIPTION
**Pull request by dannycochran**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
*(dts-gen currently fails: https://github.com/Microsoft/dts-gen/issues/111)*

- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by weswigham** [comment]
@danycochran you're missing some of the metadata files the bot needs to properly categorize this PR (that `dts-gen` would normally make). Like a lint config and a tsconfig, for example.

**Review by ghost — CHANGES_REQUESTED** [review]
Should go in `types/react-request`, not just `react-request`.

**Comment by dannycochran** [comment]
> Should go in types/react-request, not just react-request.

@andy-ms sorry, can you clarify what you mean here? the directory structure I created is identical to other directories in DefinitelyTyped.

> you're missing some of the metadata files the bot needs to properly categorize this PR (that dts-gen would normally make). Like a lint config and a tsconfig, for example (like the reminder text with checkboxes in the default OP states).

@weswigham I don't understand why a tsconfig.json and tslint.json file are necessary. In all of DefinitelyTyped, I see just 5 directories that include a tsconfig.json file, and none with a tslint.json file. As I explained, dts-gen is failing for this library due to some odd syntax it has.

**Comment by andy-ms** [comment]
> In all of DefinitelyTyped, I see just 5 directories that include a tsconfig.json file

There's a `types` directory at the root. All definitions go in subdirectories of that.

**Comment by andy-ms** [comment]
Not recent, it was changed in #13280.

**Comment by dannycochran** [comment]
@andy-ms lol, I think that is when I first checked out DefinitelyTyped. I probably haven't merged since then since most of my edits have been through the github UI. Sorry for the confusion.

Added a `tslint.json` and `tsconfig.json`, should be good now.

**Comment by dannycochran** [comment]
Getting a build error now:

`Error: react-request depends on react but has a lower required TypeScript version.`

Looks like others have encountered this before:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24586#issuecomment-376840145

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
