### PR TITLE
[google-apps-script] Fix null on wrong caches

### LINKED ISSUE #40216: [@types/google-apps-script] Update types for Cache service
- [x] I tried using the `@types/google-apps-script` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.7.2)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @motemen @grant 

According to the [Google App Script Reference](https://developers.google.com/apps-script/reference/cache/cache-service#getdocumentcache), only `getDocumentCache()` can return `null`. Methods `getScriptCache()` and `getUserCache()` always returns `Cache` instances.

Actually declared methods:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b59a18caf3e954f6413f3cd8af85d2b1015dee29/types/google-apps-script/google-apps-script.cache.d.ts#L52-L54

### PR DESCRIPTION
**Pull request by guilhermetod**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/apps-script/reference/cache/cache-service
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Fixes #40216

### CODE REVIEW

**Comment by orta** [comment]
Cool, this matches the docs - I had to re-read it because I also made the same mistake of thinking they all had null 👍🏻

**Comment by PopGoesTheWza** [comment]
@guilhermetod: sorry for not reviewing it earlier. Can you please revert this change?

from the doc:

> If this method is called outside of the context of a containing document (such as from a standalone script or web app), this method returns null.

**Comment by guilhermetod** [comment]
Hey @PopGoesTheWza 

The docs mention this strictly for the DocumentCache, which I kept possibly null. As for the ScriptCache and UserCache, I found no mention of it potentially being null, which was the error fixed by this PR.

But, if you still think this should be reverted, I can do it without a problem.

**Comment by PopGoesTheWza** [comment]
@guilhermetod indeed you are right (and the documentation is somewhat confusing in many places) ;)

**Pull request merged**
