### PR TITLE
Add CommonHTML to MathJax type definitions

### PR DESCRIPTION
**Pull request by jasongrout**
Reference for extra options added to a configuration object: http://docs.mathjax.org/en/latest/options/CommonHTML.html

### CODE REVIEW

**Comment by rolandzwaga** [comment]
👍 I see no fault in this :)

**Comment by jasongrout** [comment]
@vvakame, @rolandzwaga - is there anything I should do to get this into the officially released @types/mathjax npm repo? Should I open a PR to the types-2.0 branch?

**Comment by andy-ms** [comment]
@jasongrout We have to manually merge changes from `master` to the `types-2.0` branch, which is the basis for `@types` publishing. This happens about once a week.

**Comment by jasongrout** [comment]
Okay, thanks!

**Pull request merged**
