### PR TITLE
activex-libreoffice: initial commit

### PR DESCRIPTION
**Pull request by zspitz**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by zspitz** [comment]
I don't understand why the build is failing; I took out the `strict` option from `tsconfig.json`.

**Comment by zspitz** [comment]
A number of questions:
1. The actual definition file is 105K lines of code, and over 5MB. Should it be split into multiple files?
2. The definition files are specifically for use when using Automation/ActiveX to automate LibreOffice. LibreOffice also supports embedded Javascript macros in documents and in the installed office instance, but there are substantial differences between them. Is there value in having a shared base definition file for both environments, with each environment adding its unique features?
3. The merges that I did to bring my fork up to date with definitelytyped/master are also included in this PR. Is this a problem? If so, how can I avoid it in the future?
4. I presume that as long as the PR is open, I can continue to make changes to this branch. Is this correct?
4. What happens after this PR is closed? Do I continue pushing to the same branch? Do I ask to reopen this PR? Do I create a new PR?

**Comment by sandersn** [comment]
1. Choose the module structure that best reflects the original as long as editor performance when *using* the package is fine. Probably the structure won't make much difference except when *editing* the package.
2. Not sure. In terms of semantics, probably not, but in terms of DefinitelyTyped bloat, maybe so?
3. Merges are fine, you don't need to squash commits or anything either.
4. Yes, you can keep changing the PR.
5. You create a new PR to make changes after this one is closed.

**Comment by aozgaa** [comment]
@zspitz Is this ready to go?

**Comment by zspitz** [comment]
@aozgaa Yes.

**Comment by aozgaa** [comment]
Sorry for the delay in merging, thanks for taking the time to write these and prepare them for publication!

**Comment by zspitz** [comment]
@aozgaa No problem, and thanks for merging,

I should note that I didn't actually write them (it's 105K lines of code after all); I wrote [code to generate them](https://github.com/zspitz/ts-activex-gen#generating-a-tsnamespace-for-the-libreoffice-api).

Do you have any suggestions about generating definitions, or specifically about generating defintions for DefinitelyTyped, that would ease the burden of the maintainers?

**Comment by andy-ms** [comment]
@zspitz Could you submit the generation script to `types/activex-libreoffice/scripts`? It won't be published along with the package, but it's nice to have it on DefinitelyTyped. Note that the script should be in `.ts` files run through `ts-node` or our `.gitignore` will ignore it.

**Comment by zspitz** [comment]
@andy-ms It's not a single script; it's a [C# class](https://github.com/zspitz/ts-activex-gen/blob/master/idlbuilder/DoxygenIDLBuilder.cs) in a project which leverages [a generation library in the same project](https://github.com/zspitz/ts-activex-gen/blob/master/common/Classes/TSBuilder.cs). I imagine I could port it to TypeScript -- it's mostly just XML parsing -- but is there some kind of API to manipulate class and interface definitions that I could use from TypeScript?

**Comment by andy-ms** [comment]
Hi @zspitz, having C# code would be better than nothing. You're not obligated to port it to TypeScript, although that would be nice. Here's a sample that generates TypeScript code:
```ts
import ts = require("typescript");

const expression = ts.createAdd(ts.createNumericLiteral("2"), ts.createNumericLiteral("2"));

const expressionStatement = ts.createNode(ts.SyntaxKind.ExpressionStatement) as ts.ExpressionStatement;
expressionStatement.expression = expression;

const sourceFile = ts.createSourceFile("a.ts", "", ts.ScriptTarget.ESNext);
sourceFile.statements = ts.createNodeArray([expressionStatement]);

const printOptions: ts.PrinterOptions = {};
const printer = ts.createPrinter(printOptions);
const result = printer.printFile(sourceFile);
console.log(result); // "2 + 2;"
```

**Comment by zspitz** [comment]
@andy-ms The C# generation code is [publicly visible on GitHub](https://github.com/zspitz/ts-activex-gen/blob/master/idlbuilder/DoxygenIDLBuilder.cs). Is there some way to "include" the file here? Alternatively, is it enough to write the URL in some file here?

**Comment by andy-ms** [comment]
You can put it in a `scripts` directory (`types/activex-libreoffice/scripts`). Instructions to run it would be nice too.

**Comment by zspitz** [comment]
@andy-ms I have two issues here:

1. The code in [this class](https://github.com/zspitz/ts-activex-gen/blob/master/idlbuilder/DoxygenIDLBuilder.cs) depends on other classes and members defined in other files/projects in the solution. In particular, this class [generates and returns a data structure](https://github.com/zspitz/ts-activex-gen/blob/master/idlbuilder/DoxygenIDLBuilder.cs#L37-L306) which [describes a set of TypeScript namespaces](https://github.com/zspitz/ts-activex-gen/blob/master/common/DataClasses.cs#L419); the actual definitions are written from this data structure in a [different class](https://github.com/zspitz/ts-activex-gen/blob/master/common/Classes/TSBuilder.cs). (For a usage example, see [here](https://github.com/zspitz/ts-activex-gen/blob/master/wpf/MainWindow.xaml.cs#L178-L203), where the data structure is generated based on the user's choices in the UI; and [here](https://github.com/zspitz/ts-activex-gen/blob/master/wpf/MainWindow.xaml.cs#L205) is where the actual string-building of the definitions takes place.) **How much of all of this should I copy over to the `scripts` folder?**

2. I am still making changes and refining the code. How can I propogate those changes to the copy in the `scripts` folder?

**Comment by andy-ms** [comment]
OK, maybe for a project of that size a simple link would do, especially if it applies to more than just libreoffice.

**Pull request merged**
