### PR TITLE
[node] add a new option, withFileTypes, to fs.promises.readdir

### PR DESCRIPTION
**Pull request by esjeon**
Node v12 newly added `withFileTypes` option to `fs.promises.readdir` ([Node documentation](https://nodejs.org/api/fs.html#fs_fspromises_readdir_path_options)) which didn't exist in v10. If `withFileTypes` is set to `true`, it changes the return type of the function.

I referred to `readdir` signature, which already supports this, for the sake of consistency.

--

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://nodejs.org/api/fs.html#fs_fspromises_readdir_path_options](https://nodejs.org/api/fs.html#fs_fspromises_readdir_path_options)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration: N/A

### CODE REVIEW

**Review by Flarna — COMMENTED** [review]
Please add some tests for this.

**Review by r3nya — COMMENTED** [review]
Hello! Can you add some tests as well? ;)

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks like the package owners would like some tests with this change.
I'll mark this with Request Changes so that the bot will categorise it correctly.

**Comment by sandersn** [comment]
@Flarna @r3nya does this like ready to you now?

**Review by r3nya — APPROVED** [review]
Thank you!

**Review by sandersn — APPROVED** [review]

**Pull request merged**
