### PR TITLE
migrate inquirer-autocomplete-prompt to esm

### PR DESCRIPTION
**Pull request by MaikoTan**
`inquirer-autocomplete-prompt` v3.0.0 and `inquirer` v9 was migrated to esm,
so the import statement should be updated.

see: https://github.com/mokkabonna/inquirer-autocomplete-prompt/releases/tag/v3.0.0

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/mokkabonna/inquirer-autocomplete-prompt/releases/tag/v3.0.0>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@MaikoTan 
The version header for the main package says 'v1 > v3' mmigration, while you've created `v2` source directory? what's the correct version here?

**Comment by MaikoTan** [comment]
> @MaikoTan The version header for the main package says 'v1 > v3' mmigration, while you've created `v2` source directory? what's the correct version here?

The package before declared types for `inquirer-autocomplete-prompt` v1.3, but it is compatiable from v1.3 to v2, so I created the directory named `v2`.
Is it my misunderstanding? Should I rename it to `v1` instead?

**Comment by peterblazejewicz** [comment]
Yes, please stay at v1, but this should be not required if there is not much development in v1 in native JS module itself (so there is no expected chnages to DT definition).
DT v1 was published to v1, so the v1 sources should be here, as this just is used to resole versions via  paths in tsconfig.
You can also update heaeder to v2 and save as 'v2' version if you are sure for compatiblity. Up to you, just try to be explicit, so there is no confusion

**Comment by peterblazejewicz** [comment]
also becuase this is ESM module, you should add `package.json` file with an entry:
```ts
{
    "private": true,
    "type": "module"
}
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

**Comment by MaikoTan** [comment]
Sorry I have had a vacation in the past several days and didn't check GitHub emails.
Thank you all for the review!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@MaikoTan thanks!
I've added `package.json` as part of PR review

**Review by rbuckton — APPROVED** [review]

**Comment by MaikoTan** [comment]
@typescript-bot Ready to merge

**Comment by MaikoTan** [comment]
Ready to merge

**Comment by MaikoTan** [comment]
Ugh..? ts bot not respond?

**Pull request merged**
