### PR TITLE
concurrently: Add env option

### PR DESCRIPTION
**Pull request by 72636c**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [/src/concurrently.js#L62-L67](https://github.com/kimmobrunfeldt/concurrently/blob/54b6456eb5054ec32de9d81717b143d2ca8f8f6d/src/concurrently.js#L62-L67)
  - [/src/concurrently.spec.js#L101-L118](https://github.com/kimmobrunfeldt/concurrently/blob/54b6456eb5054ec32de9d81717b143d2ca8f8f6d/src/concurrently.spec.js#L101-L118)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## concurrently ([<kbd>unpkg</kbd>](https://unpkg.com/browse/concurrently@latest/))
was missing the following properties:
1. concurrently
1. Logger
1. InputHandler
1. KillOnSignal
1. KillOthers

<details>
<summary>as well as these 4 other properties...</summary>
<p>LogError, LogExit, LogOutput, RestartProcess</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 49373da47ebf6f1237b5a08f6854209b81a06fce
</p>

**Comment by 72636c** [comment]
Apologies for the churn, the [dtslint errors](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317#issuecomment-635019190) threw me for a loop.

This should be ready for review now.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@72636c thx for the change!

**Comment by 72636c** [comment]
Ready to merge

**Pull request merged**
