### PR TITLE
adds { isRest: boolean } to getCallbackTokenAsync() method

### PR DESCRIPTION
**Pull request by michahell**
Hi, this tiny OfficeJs parameter has been bothering me for a while :)
I'm not sure how to update the OfficeJs version ?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OfficeDev/office-js-docs/blob/master/reference/outlook/1.5/Office.context.mailbox.md#getcallbacktokenasyncoptions-callback OR: https://dev.office.com/reference/add-ins/outlook/1.5/Office.context.mailbox?product=outlook&version=v1.5 (scroll... no anchor links)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by Zlatkovsky — CHANGES_REQUESTED** [review]
@michahell , thanks for the PR.

Though it doesn't seem to make much practical difference, I think the more appropriate type annotation is to do a type intersection (`&`) rather than a type union (`|`).  And that the `isRest` should be marked as optional, as follows:

    options: Office.AsyncContextOptions & { isRest?: boolean }

Would you be able to make this change to your PR, and then we'll merge it in?

Thanks!
~ Michael

**Comment by michahell** [comment]
hi, yes the `&` union type is what I had at first, but without marking it as optional, I agree that's better. will test and change!

**Comment by michahell** [comment]
yeap that works just as well :)

**Review by Zlatkovsky — APPROVED** [review]
Approved!  Thanks for making the change.

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
