### PR TITLE
Added type definitions for zetrix-sdk-nodejs & zetrix-encryption-nodejs

### PR DESCRIPTION
**Pull request by izadimrantan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by izadimrantan — COMMENTED** [review]
All is good

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/zetrix-sdk-nodejs/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ed4465d5a4ed831da9bb52e0168b6234e2c3ce5a
</p>

**Review by armmarov — APPROVED** [review]

**Review by jakebailey — CHANGES_REQUESTED** [review]
These types seem very wrong. The package does not declare these as modules, they are exported objects (or namespaces).

**Comment by izadimrantan** [comment]
> These types seem very wrong. The package does not declare these as modules, they are exported objects (or namespaces).

Thanks for the review @jakebailey! I've amended the package, please have a look 👍 
It's my first time publishing typed definitions for a package, so please bear with me!

**Comment by jakebailey** [comment]
The PR seems the same to me. It seems like what you are actually looking for is:

```ts
export namespace keypair {
	export function getEncPublicKey(encPrivateKey: string): string;
    // ...
}
```

**Comment by izadimrantan** [comment]
> The PR seems the same to me. It seems like what you are actually looking for is:
> 
> ```ts
> export namespace keypair {
> 	export function getEncPublicKey(encPrivateKey: string): string;
>     // ...
> }
> ```

Right. I thought the suggested fix in your previous comment were referring to the "zetrix-sdk-nodejs" package instead of the "zetrix-encryption-nodejs". Will have a look at "zetrix-encryption-nodejs" instead.

**Comment by izadimrantan** [comment]
> The PR seems the same to me. It seems like what you are actually looking for is:
> 
> ```ts
> export namespace keypair {
> 	export function getEncPublicKey(encPrivateKey: string): string;
>     // ...
> }
> ```

Hi @jakebailey. If I follow this way of declaring, I get multiples of the same error when the CI script runs:
```sh
Error:    2:5  error  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting  @definitelytyped/strict-export-declare-modifiers
```

Another thing, if I update the declaration using this way, how do I import it in the test script without using relative imports? I'm getting this error when the CI script runs:
```sh
Error:   1:46  error  Test file should not use a relative import. Use a global import as if this were a user of the package  @definitelytyped/no-relative-import-in-test
```

**Comment by jakebailey** [comment]
> Another thing, if I update the declaration using this way, how do I import it in the test script without using relative imports? I'm getting this error when the CI script runs:

You import absolutely, as a user would do to import these modules. I recommend looking at some other types in the repo.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/zetrix-encryption-nodejs/tsconfig.json
1. types/zetrix-encryption-nodejs/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0e3601f4e9bdfee51666060235e1b474e483e794
</p>

**Review by sandersn — APPROVED** [review]

**Comment by izadimrantan** [comment]
Ready to merge

**Pull request merged**
