### PR TITLE
Added the .then Promise return for superagent

### PR DESCRIPTION
**Pull request by janpieterz**
As described here:
https://github.com/visionmedia/superagent/releases/tag/v1.3.0 and https://github.com/visionmedia/superagent/releases/tag/v2.0.0 (becomes a real promise)

### CODE REVIEW

**Comment by janpieterz** [comment]
@vvakame there you go! More/other changes have been made to superagent but this is at least a start.

**Comment by janpieterz** [comment]
I'll get on this.

**Comment by janpieterz** [comment]
Odd, the supertest-as-promised definition defines it's own [Promise signature](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/supertest-as-promised/supertest-as-promised.d.ts#L40). If I read correctly, this should be fine and possibly removed? This then also means I can change my definition to extend Promise<Response> instead of defining the .then.

So to summarize, my line of thinking is: 
- Remove the seemingly redundant Promise interface definition in supertest-as-promised.d.ts and let this one inherit it from the Superagent [Request object](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/supertest-as-promised/supertest-as-promised.d.ts#L25) 
- Change my new .then's to extend the native Promise<Response> instead of defining it on the object itself

I'm not too familiar with this side of things so a thumbs up or feedback would be appreciated.

**Comment by yuit** [comment]
ping @vvakame @tkrotoff @frogcjn 🔔 as they have edited supertest-as-promise.d.ts

**Comment by vvakame** [comment]
I'm not user of superagent. but...

> possibly removed

👍

**Comment by janpieterz** [comment]
Just quickly changed it to what I proposed so it's easier to see. Please keep in mind this is my first contribution to definitions ;)

**Comment by minestarks** [comment]
:+1: Thank you for the contribution!

**Pull request merged**
