### PR TITLE
Remove index signature from unist.Node

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
See discussion at https://github.com/unifiedjs/unified/discussions/142.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/unifiedjs/unified/discussions/142

cc @ChristianMurphy @Rokt33r @wooorm @remcohaszing.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Comment by GuiltyDolphin** [comment]
So this failure is expected at the moment - packages `hast`, `xast` used to use `AnyNode`. Now do we want to use `AnyNode` again in these modules?

**Comment by GuiltyDolphin** [comment]
So the failures we're getting are from `xast` and `hast`.

The specifications https://github.com/syntax-tree/xast and https://github.com/syntax-tree/hast just specify that these modules "extend `unist`", but has anything changed that means that they require an index signature? Both modules use `point` in their tests, is this intended?

**Comment by wooorm** [comment]
Nodes are supposed to have a position. Positions consist of a starting and ending point. So a point is one place. But nodes *span* two places: https://github.com/syntax-tree/unist#node

**Comment by GuiltyDolphin** [comment]
@wooorm So this is a bug in the tests, which should be using `position` rather than `point` here? If so I'll update them.

**Review by ChristianMurphy — APPROVED** [review]

**Comment by ChristianMurphy** [comment]
per https://github.com/unifiedjs/unified/discussions/142#discussioncomment-943459 would it make sense to bump the unist version to 3?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/747fdf36a6031fcc9fea2928e5caba781461f2c1/types/unist/index.d.ts#L1

**Review by remcohaszing — APPROVED** [review]

**Comment by GuiltyDolphin** [comment]
Oh yep, @ChristianMurphy that makes sense to do - I'll update the version.

**Comment by GuiltyDolphin** [comment]
Oh hmm, @ChristianMurphy technically this is in line with the `unist` version 2.0.0 specification. Should the version here match the version [there](https://github.com/syntax-tree/unist/releases/tag/2.0.0)?

**Comment by remcohaszing** [comment]
I think bumping the major version will cause more issues than not bumping it. I think a major version release will result in long term compatibility issues, as all dependants will have to update caret version rangers. I think releasing this as minor or patch will likely only cause issues related to local errors, which are probably actual programming errors.

**Comment by GuiltyDolphin** [comment]
@remcohaszing Maybe it's better to leave as is then, so the `major.minor` version number matches that of `unist`? The [FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) indicates that the patch number is handled automatically - so I'm guessing by leaving the version as is, there'll automatically be an incremented patch number?

**Comment by ChristianMurphy** [comment]
yep, the patch version is automatically handled by definitely typed's build system

**Review by wooorm — APPROVED** [review]
Awesome!

**Review by wooorm — APPROVED** [review]

**Review by ChristianMurphy — APPROVED** [review]

**Review by orta — APPROVED** [review]
Looks reasonable to me

**Comment by GuiltyDolphin** [comment]
Ready to merge

**Comment by jescalan** [comment]
This release is massively breaking for me with plugins - it looks like arbitrary keys are no longer allowed to be added to the `Node` type, which is the type that is returned by default from plugins. Here's a simple example:

```ts
export default function somePlugin() {
  return function transformer(tree) {
    visit(tree, 'element', (node) => {
      if (node.tagName !== 'code') return
    })
  }
}
```

Here, we get a type error on `node.tagName` saying `Property 'tagName' does not exist on type 'Node<Data>'.ts(2339)`, although this is perfectly valid from a rehype plugin.

Is there something I'm missing here?

**Comment by ChristianMurphy** [comment]
@jescalan check out the typescript guides at https://unifiedjs.com/learn/guide/syntax-trees-typescript and https://unifiedjs.com/learn/recipe/tree-traversal-typescript

in your case, a missing type annotation on `node` is the issue

```ts
import type {Element} from 'hast'

export default function somePlugin() {
  return function transformer(tree) {
    visit(tree, 'element', (node: Element) => {
      if (node.tagName !== 'code') return
    })
  }
}
```

**Pull request merged**
