### PR TITLE
update(validator.js): v13.7

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- `isISO4217` validator
- `IBAN` exports country codes
- `isBoolean` `loose` option
- `isURL` new options
- `isEmail` new option
- move update content into proper modules (following source) and
  re-export
- test updated

https://github.com/validatorjs/validator.js/releases/tag/13.7.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x Test the change in your own code. (Compile and run.)
- [ x [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by fasenderos** [comment]
@peterblazejewicz my PR https://github.com/validatorjs/validator.js/pull/1647 was merged in v13.7. It adds the `allow_wildcard` option to the `isFQDN` validator. Moreover I see that in the types definition of the isFQDN is missing also the `allow_numeric_tld` option. Can you update this PR accordingly or I have to made a separate PR? Thanks

**Comment by peterblazejewicz** [comment]
@fasenderos amended with changes

**Comment by n-nik** [comment]
When we could expect merge?

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
