### PR TITLE
Types updated for react-native-auth0:2.16.0

### PR DESCRIPTION
**Pull request by poovamraj**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/react-native-auth0/releases/tag/v2.16.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-native-auth0 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-native-auth0@latest/))
was missing the following properties:
1. TimeoutError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e53951522e795bb023cb57cd8c7e46276afb9e55
</p>

**Comment by poovamraj** [comment]
@ascariandrea @marknelissen @leoafarias @willdady @Bogidon @yammesicka @mdjarv Can anyone help with this PR to be merged?

**Comment by gfriedm4** [comment]
@poovamraj Thanks for picking up where I left off - I tested your updates and things look good to go. Hopefully someone you tagged above can get this merged ASAP!

**Comment by gfriedm4** [comment]
> I am not seeing the option to review this. Not sure if I will be able to approve it!

Do you see the green "Review Changes" dropdown in the top right corner of "Files Changed" tab on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63584/files ?

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by poovamraj** [comment]
Ready to merge

**Pull request merged**
