### PR TITLE
Luxon 3.4 - localized week support

### PR DESCRIPTION
**Pull request by CarsonF**
Covers Luxon 3.4 changes from: https://github.com/moment/luxon/pull/1454

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/luxon/test/luxon-tests.module.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d45786c7e1f03c17856952d1cfe208d318fccc62
</p>

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by CarsonF** [comment]
Ready to merge

**Comment by jackkoppa** [comment]
Thanks @CarsonF 🙇

**Pull request merged**
