### PR TITLE
Update pako typings

### PR DESCRIPTION
**Pull request by hlthi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodeca.github.io/pako/
- [x] Increase the version number in the header if appropriate. (Update as MAJOR.MINOR  so I deleted patch version)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by calebegg** [comment]
Changes look good to me, but it would be nice to have tests that cover the new parts.

**Comment by hlthi** [comment]
> Changes look good to me, but it would be nice to have tests that cover the new parts.

Tests, missing parameters and references have been added. @calebegg

**Comment by calebegg** [comment]
LGTM!

@typescript-bot:
> Be sure to explicitly select Approve or Request Changes in the GitHub UI so I know what's going on.

I don't have those buttons, I only have "comment". Probably because I'm not a project member?

**Comment by hlthi** [comment]
> LGTM!
> 
> @typescript-bot:
> 
> > Be sure to explicitly select Approve or Request Changes in the GitHub UI so I know what's going on.
> 
> I don't have those buttons, I only have "comment". Probably because I'm not a project member?

@sheetalkamat

**Pull request merged**
