### PR TITLE
Update @feathersjs/express types

### PR DESCRIPTION
**Pull request by sandersn**
`express.static` now returns a generic type `serveStatic.RequestHandler<T extends http.OutgoingMessage>`

That means FeathersRouterMatcher needs to support this type. Unfortunately, this means that all its generic types need to extend http.OutgoingMessage too.

I know nothing about express or feathersjs types -- if there is a better way to update this package, please let me know.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## feathersjs__express ([<kbd>unpkg</kbd>](https://unpkg.com/browse/feathersjs__express@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'feathersjs__express'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 09d811ad738a320444e2486a135f2cf5739a2a98
</p>

**Comment by sandersn** [comment]
@devanshj can you take a look at this too? express is a lot more used than `@feathersjs/express`, so I'd prefer a fix to the latter.

**Comment by devanshj** [comment]
Superseded by [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48964] check description for why.

Also this PR is plain wrong haha, afaict the `T` here does not correspond to the `response` but the return type apparently.

**Comment by sandersn** [comment]
Thanks for the real fix!

**Comment by devanshj** [comment]
My pleasure! :)

**Pull request closed without merging**
