### PR TITLE
Allowing `width` and `height` to be specified as strings.

### PR DESCRIPTION
**Pull request by roberttaylor426**
Since [3.1.8](https://github.com/mhnpd/react-loader-spinner/issues/59).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [N/A] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by elibarzilay** [comment]
Please consider adding tests.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@roberttaylor426 thx!

**Review by jordantai — APPROVED** [review]
All looks good to me

**Review by peterblazejewicz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@roberttaylor426 please say `yes`!

**Comment by roberttaylor426** [comment]
Ready to merge!

**Pull request merged**
