### PR TITLE
Declare namespace for p-defer

### PR DESCRIPTION
**Pull request by dplusic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Why?

**Comment by dplusic** [comment]
I want to create a method with `DeferredPromise` as a parameter.
Please refer the newly updated test.
Reference: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html

**Comment by DanielRosenwasser** [comment]
@SamVerschueren this seems reasonable to me. Any objections?

**Review by SamVerschueren — APPROVED** [review]
Sorry for the delay, sounds reasonable indeed.

**Pull request merged**
