### PR TITLE
Systemjs: add integrity to importmap

### PR DESCRIPTION
**Pull request by jackw**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/systemjs/systemjs/blob/main/docs/import-maps.md#integrity
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/systemjs/systemjs-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 670a8482a3c149d7f5a3ea683522d0382fbc3f7d
</p>

**Comment by jackw** [comment]
Sorry to ping you @guybedford but would you be able to take a look at this PR when you have time please?

**Review by internettrans — APPROVED** [review]
lgtm - this matches the documentation at https://github.com/systemjs/systemjs/blob/main/docs/import-maps.md#integrity

**Comment by joeldenning** [comment]
Ready to merge

**Pull request merged**
