### PR TITLE
Fix n3 import method not being generic enough

### PR DESCRIPTION
**Pull request by rubensworks**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## n3 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/n3@latest/))
was missing the following properties:
1. Lexer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e880e52a59eeaff7b990c6d513937be36b36dd83
</p>

**Comment by rubensworks** [comment]
@RyanCavanaugh Is it possible that something went wrong in the automation process behind this PR? It has been open for 8 days, and I am an author of these typings. In the past, these changes always went through pretty quickly if I remember correctly.

**Comment by rubensworks** [comment]
@joachimvh Could you review this PR?

**Review by joachimvh — APPROVED** [review]

**Comment by rubensworks** [comment]
Ready to merge

**Pull request merged**
