### PR TITLE
Using $._data() to retrieve event handlers

### PR DESCRIPTION
**Pull request by kotaroyamame**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

http://slavchoslavchev.com/quick-tips/using-_data-to-retrieve-event-handlers/

### CODE REVIEW

**Comment by Diullei** [comment]
Hi @kotaroyamame, this method not seems to be part of the jQuery public api. If you need to use it in your test/debug code you can extend the `JQueryStatic` using this:

```typescript
interface JQueryStatic {
    _data(element: Element, key: string): any;
}

$._data($el, "events");
```

**Comment by johnnyreilly** [comment]
I agree with @diullei - where possible we aim to provide definitions for the public API. So thank you, but we would not look to merge this.

**Comment by kotaroyamame** [comment]
I understand.
Mr. Diullei and Johnnyreilly.
Thank you for telling me.

**Comment by Diullei** [comment]
:+1:

**Comment by johnnyreilly** [comment]
What @duillei said :smile:

**Pull request closed without merging**
