### PR TITLE
Add support for `ko.tasks` API in Knockout.js v3.4.0

### PR DESCRIPTION
**Pull request by mattbrooks2010**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Add support for Knockout’s microtask queue. Knockout’s microtask queue supports scheduling tasks to run as soon as possible while still being asynchronous, striving to schedule them to occur before yielding for I/O, reflow, or redrawing.

[Knockout : Microtasks](http://knockoutjs.com/documentation/microtasks.html)

### CODE REVIEW

**Comment by mattbrooks2010** [comment]
Running `npm test` fails locally and via Travis CI build due to files being picked-up that I have not modified. I'm not sure why this is happing. Running `tsc .\tests\knockout-tests.ts` compiles without error.

Also, the symbol `ko.tasks` conflicts with a `Knockout` plugin definition that I have not touched and my changed files are not referencing. The conflicting plugin `knockout.deferred.updates` is now obsolete. I am not sure how to resolve this.

[Deferred Updates plugin for Knockout](https://github.com/mbest/knockout-deferred-updates)

**Comment by Igorbek** [comment]
If the plugin is no longer supported and conflicts with newer versions of knockout, I think, we should simply delete it from the repo. All the existing packages will still be published, so it wouldn't be any issue to consume for people who would want to.
@DefinitelyTyped/contributors what do you think?
@mattbrooks2010 please delete it as a part of this PR.

**Comment by mattbrooks2010** [comment]
@Igorbek thanks for the input. I will do once we hear confirmation from the other contributors.

**Comment by nycdotnet** [comment]
I agree regarding deleting the other plugin.

**Comment by mattbrooks2010** [comment]
@Igorbek removing the plugin typings as suggested resolves the issues above and the Travis CI build now passes.

**Comment by nycdotnet** [comment]
Awesome - thank you.

**Pull request merged**
