### PR TITLE
Fix proposal for ES6 Promise conflict

### PR DESCRIPTION
**Pull request by piraveen**
This is a fix proposal for Typescript ES6 Library Promise conflict.

Working Solution => (encapsulate methods, interfaces and classes into a module).

### CODE REVIEW

**Comment by vvakame** [comment]
*bluebird/bluebird.d.ts*

to author(@Bartvds). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by piraveen** [comment]
To author @Bartvds  and @vvakame  Have you review this PR? We need to use this on our production app and we would like to avoid using our fork for TSD package management?

Regards,

**Comment by vvakame** [comment]
@piraveen 1st, I'm not bluebird user. :wink: 
your pull request contains breaking change.
bluebird are used in browser environment. your PR is not working it.
https://github.com/petkaantonov/bluebird#browsers

I think this style is good solutions.
http://goo.gl/bcz8Gl

**Comment by cybrown** [comment]
This is a real issue and is in contradiction with https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages because it is polluting the global scope.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
