### PR TITLE
[node] Remove ts4.8 in favor of new multi-tsconfig testing

### PR DESCRIPTION
**Pull request by jakebailey**
https://github.com/microsoft/DefinitelyTyped-tools/pull/973 will allow DT packages to specify which tsconfigs to check at test time. This allows for multiple tsconfig settings to work, including one with DOM and one without. This removes the need for the ts4.8 directory duplication, which has long doubled the package size and created confusion for contributors.

A main `tsconfig.json` file which includes _all_ files is still required due to ts-eslint restrictions, but the other tsconfigs can now include differing sets of files. This means that we can have separate test files for DOM and non-DOM, which this PR does.

image

~Caveat: the 4.8 dir also didn't include some special generic form which allowed TS 4.6 to pass; I have temporarily raised the minimum TypeScript version to 4.7, however TS 5.4 is due to release this week and 4.6 will go out of support, so this should be okay.~ TS 4.6 is no more.

Closes #66640

### CODE REVIEW

**Comment by jakebailey** [comment]
Well, the minimum TS version bump breaks basically everything, so I'll just sit on this until 4.6 is gone.

**Comment by jakebailey** [comment]
Yay, it works (with the PR). Still want to think a little more about this since think other packages are wanting to have multiple tsconfigs for other uses (e.g. testing JSX with more than just react).

**Comment by jakebailey** [comment]
This is all passing and green, but I'd love for a maintainer to take a look. Hopefully you find this helpful! I know that the `ts4.8` dir has been a problem for a while.

**Comment by jakebailey** [comment]
@typescript-bot ping

**Comment by peterblazejewicz** [comment]
It looks like a nice addition (and it does the job)
Should this be documented here?
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
Will this work if the toolset changes are frozen in the lock file, but not the source (devs vs devDeps)?

**Comment by jakebailey** [comment]
I intend to send docs for this for the DT readme, but this isn't a TypeScript feature, it's a dtslint feature and wouldn't be on the TS website.

> Will this work if the toolset changes are frozen in the lock file, but not the source (devs vs devDeps)?

I'm not sure what you mean by this. This is just local to DT testing.

**Comment by peterblazejewicz** [comment]
> I'm not sure what you mean by this. This is just local to DT testing.

let's skip this. I was concerned about existing installations, in case TS version resolution is removed from 'package.json' (the one I understand how it works 😄 )

**Comment by jakebailey** [comment]
> > I'm not sure what you mean by this. This is just local to DT testing.
> 
> let's skip this. I was concerned about existing installations, in case TS version resolution is removed from 'package.json' (the one I understand how it works 😄 )

It's true that a local install of DT may stop passing until its root `node_modules` is removed and updated to the latest `dtslint`, yes, though that's true of basically any big infra change we make. Other than that, things should work.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jakebailey** [comment]
Thanks for looking; I think that this will work out pretty well for now. @remcohaszing has also been trying out the new feature in #68955 and I think that there's some improvement to be had here, but nothing I didn't foresee, so I think this is good and am happy to get rid of the ts4.8 folder.

**Comment by jakebailey** [comment]
Ready to merge

**Pull request merged**
