### PR TITLE
Definitions for webpack module API

### PR DESCRIPTION
**Pull request by use-strict**

### CODE REVIEW

**Comment by vvakame** [comment]
*webpack/webpack-env.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/webpack
  * http://bower.io/search/?q=webpack
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (webpack/webpack-env-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
@tkqubo could you review this PR?

**Comment by tkqubo** [comment]
@vvakame I checked the changes and they look OK :rocket: 
@use-strict Thanks for PR!

**Comment by vvakame** [comment]
thanks all!

**Pull request merged**
