### PR TITLE
[youtube-player] Change events key to optional

### PR DESCRIPTION
**Pull request by hoiheart**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by jurca** [comment]
@hoiheart Thank you for submitting this.

Next time, please provide a short description of what kind of issue your PR fixes so that it's easier to check :+1: .

**Comment by jurca** [comment]
@typescript-bot Not yet :). I'm afraid ts-bot is mistaking a comment with an approval.

**Review by jurca — APPROVED** [review]
Looks goods, removes the necessity for specifying event listeners for every event.

**Comment by sandersn** [comment]
@jurca I didn't write the code, but I'm pretty sure any string that contains a :+1: emoji counts as an approval (!).

**Comment by jurca** [comment]
@sandersn Thanks for pointing this out, I was wondering if that was the case. I'll try to keep that in mind :)

**Pull request merged**
