### PR TITLE
 Add the chrome.loginState API

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/extensions/loginState
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by fredrikhr — CHANGES_REQUESTED** [review]
Can you please supply a reference to documentation pages und conform your PR to the template that is provided by this repository.

**Comment by ankhler** [comment]
I edited my first comment but the link I provided is the only reference I found.

**Comment by couven92** [comment]
Hmm... I have never gotten an API to review that wasn't documented on the official Chrome API documentation. I'd like others to revise this as well to voice their opinions on whether we should add undocumented APIs.

**Comment by ankhler** [comment]
It was added to the official documentation and I updated the reference in the comment above.

**Review by fredrikhr — CHANGES_REQUESTED** [review]
Hmm... for the other namespaces we also included the information regarding availability, permissions and the Chrome OS only support (see the table at the top of the docs page) in the namespace doc-comment.

* [x] The `isRunningInLoginProfile` is not part of the official API, should we omit this?
* [x] Can you add the `getProfileType` function as well?
* [x] Please copy the documentation for the `onSessionStateChanged` event verbatim from the docs page.

**Review by fredrikhr — APPROVED** [review]
:+1:

**Comment by ankhler** [comment]
@couven92 Could you please check and let me know if there is something else to do here?

Thanks.

**Comment by ankhler** [comment]
@couven92 Could you please check and let me know if there is something else to do here?

Thanks.

**Comment by couven92** [comment]
@ankhler read https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42853#issuecomment-597605132

There is nothing more to do, but wait for this to get merged

**Pull request merged**
