### PR TITLE
[react-native] Add id prop to Text, TouchableWithoutFeedback and View components

### PR DESCRIPTION
**Pull request by gabrieldonadel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:  https://github.com/facebook/react-native/pull/34522

This PR is the follow-up of https://github.com/facebook/react-native/pull/34522, and add types for the new `id` prop to the `Image`, `Text`, `TouchableWithoutFeedback` and `View` components. It also adds new tests for the `id` prop.

### CODE REVIEW

**Comment by eps1lon** [comment]
Am I correct in assuming this is a PR for an unreleased feature? If that's a case, could you convert this to a draft so that it doesn't create more notifications considering we can't merge it yet?

**Comment by gabrieldonadel** [comment]
> Am I correct in assuming this is a PR for an unreleased feature? If that's a case, could you convert this to a draft so that it doesn't create more notifications considering we can't merge it yet?

Sure, this PR is related to https://github.com/facebook/react-native/pull/34522, I'm converting this back to a draft as you suggested then

**Comment by gabrieldonadel** [comment]
@eps1lon https://github.com/facebook/react-native/pull/34522 has been merged and 0.70 release, I belive this will be available in the next release

**Review by iRoachie — APPROVED** [review]

**Review by kuasha420 — APPROVED** [review]
LGTM

**Comment by lunaleaps** [comment]
Thanks @gabrieldonadel for adding this! Now that we've copied these types over to react-native (https://github.com/facebook/react-native/blob/main/types/index.d.ts), I'll copy your changes over and from now on we can just submit PRs to the react-native repo

**Review by eps1lon — CHANGES_REQUESTED** [review]
The [merge commit for the linked PR](https://github.com/facebook/react-native/commit/3e97d5fe58c20567f2e653b82f821b856306087b) is not tagged with any release yet. It was also merged 10 days ago while 0.70 was released 14 days ago. [0.70.1 release notes](https://github.com/facebook/react-native/releases/tag/v0.70.1) make no mention of this change. [reactnative.dev docs also do not mention this prop](https://reactnative.dev/docs/text#nativeid).

The types in this repository reflect the documented and released API. Not the head of `main` in `facebook/react-native`.

Until the linked change is release, this should not be merged. I suggest going back to draft and re-requesting review once it's released.

**Pull request closed without merging**
