### PR TITLE
ws:typing(): modern typings

### PR DESCRIPTION
**Pull request by Tolfx**
Using partial instead of `?: any | undefined` and modified Data type.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by amcasey** [comment]
This doesn't address an obvious program, so we'd need to hear from an owner before merging a change to a Critical package.

**Review by k-yle — COMMENTED** [review]
This is a breaking change for a package with millions of weekly downloads. Is there actually a benefit of making this change? 

Instead of updating the definitions of types like `ws.ServerOptions`, couldn't you just use  `Required<ws.ServerOptions>`?

**Comment by Tolfx** [comment]
> Is there actually a benefit of making this change?
No there isn't.

> Instead of updating the definitions of types like ws.ServerOptions, couldn't you just use Required<ws.ServerOptions>?
Changed due to more of a preference, and I think making interfaces the keys shouldn't all options from ground up imho. But using the utility type required works as well if someone would have wanted it required.

**Review by k-yle — CHANGES_REQUESTED** [review]
>> Is there actually a benefit of making this change?

> No there isn't.

In that case, I would oppose merging this because of the huge impact this breaking change would have.

**Comment by amcasey** [comment]
@Tolfx thanks for the extra context!  Doing it your way in the first place might have had some advantages, but changing it now doesn't seem worthwhile.  Thanks!

**Comment by Tolfx** [comment]
> >> Is there actually a benefit of making this change?
> 
> > No there isn't.
> 
> In that case, I would oppose merging this because of the huge impact this breaking change would have.

Assuming version handling won't work as intended, I agree to not merge this as well, since as you said could break other packages. As well it wasn't really necessary to begin with.

But since npm offers version handling, and even on the others, wouldn't it possible for developers just to lock on the older types if they would break? A experience developer would have seen the issue and fixed it, the other way or another imo.

**Pull request closed without merging**
