### PR TITLE
fix: update @types/vscode version to 1.84

### PR DESCRIPTION
**Pull request by ulugbekna**

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]

**Review by jakebailey — CHANGES_REQUESTED** [review]
We shouldn't do this quite yet; to restore 1.83, we should merge a PR that reverts #67270, then let it publish, then resend it with the version changes for 1.84.

**Comment by jakebailey** [comment]
Pushed to this PR the change to revert the revert; I will merge this when the new 1.83 comes out.

**Review by jakebailey — APPROVED** [review]
https://www.npmjs.com/package/@types/vscode/v/1.83.3 has been published to restore 1.83; this PR is now good to go.

**Comment by jakebailey** [comment]
1.84 should get published within a half hour.

**Pull request merged**
