### PR TITLE
[react-simple-maps] Update to 3.0

### PR DESCRIPTION
**Pull request by Semigradsky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c0777bd1dd9b34f4fa4e36aecfdc3228e64d454/types/react-simple-maps/index.d.ts#L81
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62407
https://github.com/zcreativelabs/react-simple-maps/issues/297

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-simple-maps ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-simple-maps@latest/))
was missing the following properties:
1. MapContext
1. MapProvider
1. ZoomPanContext
1. ZoomPanProvider
1. useGeographies

<details>
<summary>as well as these 3 other properties...</summary>
<p>useMapContext, useZoomPan, useZoomPanContext</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 481a9d5d8726b7faf801ab6d53c3fdbeae6be96b
</p>

**Comment by Semigradsky** [comment]
Any news?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
