### PR TITLE
[@types/dom-webcodecs] add missing "dequeue" event to (Video|Audio)(En/De)coder

### PR DESCRIPTION
**Pull request by dumbmoron**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/w3c/webcodecs/pull/439

MDN - Video: [Encoder](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder/dequeue_event), [Decoder](https://developer.mozilla.org/en-US/docs/Web/API/VideoDecoder/dequeue_event)
MDN - Audio: [Encoder](https://developer.mozilla.org/en-US/docs/Web/API/AudioEncoder/dequeue_event), [Decoder](https://developer.mozilla.org/en-US/docs/Web/API/AudioDecoder/dequeue_event)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/dom-webcodecs/webcodecs.generated.d.ts
1. types/dom-webcodecs/test/dom-webcodecs-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4884460398db2630712a74aff5ac2eb85475949c
</p>

**Comment by andrewbranch** [comment]
> ```js
> // The declarations in webcodecs.generated.d.ts have been generated using the code in
> // https://github.com/yume-chan/webcodecs-lib-generator. See
> // https://github.com/yume-chan/webcodecs-lib-generator/blob/main/README.md for more detail.
> ```

@dumbmoron were your changes generated with this tool?

**Comment by jakebailey** [comment]
It seems like the generator hasn't been updated in three years, and the package here hasn't been touched by anyone but maintainers (for fixes / formatting).

I know some of these types are already a part of the types TS already ships for the DOM; are these types also declared there? Hoping to not make a conflict or a confusing situation.

**Comment by sandersn** [comment]
Might be related: #70715

**Comment by sandersn** [comment]
Answering @jakebailey's question, dom-webcodecs compiles against the version of DOM specified in minimumTypescriptVersion in package.json to ensure that it's a superset. Right now that's 5.2; #70715 updates that to 5.7. When features get added to the DOM that conflict with dom-webcodec's, I delete them and update the minimumTypescriptVersion.

**Review by sandersn — APPROVED** [review]

**Comment by dumbmoron** [comment]
> @dumbmoron were your changes generated with this tool?
Sorry, no, I couldn't get it to work. These changes were manually added by me because they were not included in TS DOM types.

**Comment by dumbmoron** [comment]
Ready to merge

**Pull request merged**
