### PR TITLE
@types/lodash: Overload `debounce` to provide correct return type when `leading` option is true

### PR DESCRIPTION
**Pull request by ashharrison90**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.15#debounce
  - setting `leading: true` as part of the options means that the result of `debounce` can never be `undefined` since it will be immediately invoked the first time it's called, and all subsequent calls will either use this previous value or a new value if the timeout has been reached.
  - i've made a codesandbox here to demonstrate: https://codesandbox.io/s/cocky-booth-m74xft
  
first time contributing to the repo, so happy to make any changes necessary 🙇

### CODE REVIEW

**Comment by amcasey** [comment]
Seems sensible, but I'd like to hear from an owner.

**Review by aj-r — CHANGES_REQUESTED** [review]
Looks good! Please also update `v3/index.d.ts` and `v3/lodash-tests.ts`.

**Comment by ashharrison90** [comment]
hi @aj-r 👋 

i'm not sure how to change v3 since the types aren't the same there. looks like the original changes made to the return type of `debounce` (see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46971) weren't made in v3.

what do you suggest? 🤔

**Review by aj-r — APPROVED** [review]
I see - in that case, you can merge this as-is. Maybe someone should make a separate PR to update v3.

**Pull request merged**
