### PR TITLE
Fix bytebuffer report long.js is not a module.

### PR DESCRIPTION
**Pull request by woooha**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

When use bytebuffer's d.ts, it will throw an error: long.js is not a module.
bytebuffer.d.ts didn't correctly reference long.js' defination.

### CODE REVIEW

**Comment by cappellin** [comment]
I don't really understand what you changed. @woooha can you explain it a bit more, please?

**Comment by woooha** [comment]
@cappellin 

bytebuffer's index.d.ts didn't include 

```
/// <reference path="../long/index.d.ts" />
```

So, when I use typescript, it will warn me that:

```
ERROR in [default] /Users/woooha/Workspaces/HoverControlStation/node_modules/@types/bytebuffer/index.d.ts:7:22
File '/Users/woooha/Workspaces/HoverControlStation/app/node_modules/long/dist/Long.js' is not a module.
```

And I resovled this error by add the reference to bufferbyte's index.d.ts

**Comment by paulvanbrenk** [comment]
@woooha  you should use `<reference types= />` in the `types-2.0` branch.

**Comment by andy-ms** [comment]
As @paulvanbrenk said, we don't use `/// <reference path="" />` to reference other definitions, we use `/// <reference types="" />`.

**Pull request closed without merging**
