### PR TITLE
ES6 export compatible for Modernizr

### PR DESCRIPTION
**Pull request by lucax88x**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.

If changing an existing definition:
- [ ] Increase the version number in the header if appropriate.

I wonder if I need to change version on the header? 

this simple commit it's just for making modernizr ES6 compliant for doing such:

`import * as Modernizr from "modernizr"`;

### CODE REVIEW

**Comment by mhegazy** [comment]
No response from other authors for over 8 days. Merging.

**Comment by timocov** [comment]
You release it as `3.2.28` (patch release), but it broken backward compatibility compare with `3.2.27`. We have a lot errors something like this:
```
error TS2686: 'Modernizr' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

**Comment by lucax88x** [comment]
My apologies, I'm gonna check on it, anyone has suggestions on what's wrong?

**Comment by markheron91** [comment]
I think whats going on here is a restriction put in place by typescript - see discussion here https://github.com/Microsoft/TypeScript/issues/10178 - from my (very limited) investigation it looks like the line thats causing this error is `export = Modernizr`. Changing this manually to `module.exports = Modernizr` fixed the issue for me and allowed my angular app to compile, but I'm not experienced enough with AMD modules to be 100% sure that this doesn't break anything else for people using that system.

**Comment by lucax88x** [comment]
can you paste me a .ts file which is not compiling? so I can add this to test and check what's the issue.

I have noticed the same error if I do the following:

`import * as myModernizrInstance from "Modernizr"`

and then I use

`Modernizr.something()`

but as far I understood, you are not using import

**Comment by lucax88x** [comment]
ok, I'm trying to follow other examples, now it should be AMD & UMD compatible.

is anyone who experienced the issue able to test the new definition before I make a new PR?

[new definition](https://github.com/lucax88x/DefinitelyTyped/blob/691b04a217044fe23be801c476e194814e549669/modernizr/index.d.ts)

**Comment by markheron91** [comment]
@lucax88x I copied your definition file into my project to try it out.

I'm using the angular-cli to include a modernizr-custom.js file as a global script and using Modernizr as a global object: `if (Modernizer.inputTypes[...]`

The changes you have made are working for my use case. Cheers!

**Comment by lucax88x** [comment]
@markheron91 great!

@timocov can you try too? thanks!

**Comment by timocov** [comment]
We are using custom modernizr (actually we just add one property to Modernizr object). We just add one property:
```ts
declare namespace __Modernizr {
	interface ModernizrStatic {
		touch: boolean;
	}
}
```

Your code broken that code (because there is no namespace `__Modernizr` anymore).
Now we should use this:
```ts
interface ModernizrStatic {
	touch: boolean;
}
```

I am not against your changes what you did first time. My point is that version with which you publish new package is wrong. I guess it should be at least minor update, not just patch.

I guess your new changes should be published at least with increment minor version of package (with breaking changes).

**Comment by lucax88x** [comment]
Reasonable.

But I don't know if it's correct to increase the version if it's only supporting the AMD module, and effectively no code change.
Let's see what @mhegazy thinks, if he agrees with you I can increase version and then push the new version of definition.

**Comment by timocov** [comment]
> and effectively no code change.

I think if at least one line of code breaks backward compatibility it will be correct.

**Comment by mhegazy** [comment]
The major.mino version of the package should match the JS package. So I would not recommend reving the version just for a declaration change.

**Comment by timocov** [comment]
Then maybe you can publish it with not `latest` tag to do not break BC?
I understand you about compatibility of package versions, but you should think about BC too. In this case, even `~` in package version not save us (needless to say about `^` which is default in npm).

**Comment by pksorensen** [comment]
We also had custom modernizr. 

Before  we had the following in our vendors.d.ts
```
declare module __Modernizr {
    interface ModernizrStatic {
        csstransformspreserve3d: boolean;
    }
}
declare module "modernizr" {
    export = Modernizr;
}
```
but changing this to 
```
interface ModernizrStatic {
    csstransformspreserve3d: boolean;
}
```
do not resolve 

```
C:\dev\Ascend.Ammo.Portal\src\Ascend.Ammo.Portal>tsc
src/3party/progressButton/lib/ProgressButton.ts(49,109): error TS2339: Property 'csstransformspreserve3d' does not exist on type 'ModernizrStatic'.

```

@timocov Did you do anything else?

I also tried to define the interface in the ts file that uses it.
```
import Modernizr = require("modernizr");
interface ModernizrStatic {
    csstransformspreserve3d: boolean;
}
```

**Comment by timocov** [comment]
@pksorensen Did you try with `3.2.28` from npm or from [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13899#issuecomment-273467700) comment?

**Comment by pksorensen** [comment]
@timocov From npm 3.2.28

**Comment by timocov** [comment]
@pksorensen I have wrote solution for new changes (from comment). In our project we just rollback `@types/modernizr` to `3.2.27` and freeze it.

**Pull request merged**
