### PR TITLE
Added webgl2 definition file

### PR DESCRIPTION
**Pull request by ccrisrober**
case 1. Add a new type definition.
- [x ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [  ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by andy-ms** [comment]
* Better `Project` link: https://www.khronos.org/registry/webgl/specs/latest/2.0/
* There is some commented-out code still in the definition.
* Consider introducing aliases for common types such as `(Float32Array | number[])`.
* TypeScript considers all empty interfaces equivalent: an empty interface provides no information about an object, so every object satisfies that interface.
If the type really doesn't have any useable members, you might want to consider a "brand":
```ts
interface WebGLQuery extends WebGLObject {
  _webGlQueryBrand: any;
}
```
This helps differentiate the `WebGLQuery` type from other types.

**Comment by mhegazy** [comment]
@maldicion069 can you please address the comments above?

**Comment by jramsay** [comment]
@maldicion069 - thanks for your contribution!  We're unable to merge this PR until the above comments have been addressed.

**Comment by yuit** [comment]
@maldicion069  Thanks for your contribution. This PR has unaddress comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by jbms** [comment]
A revised pull request is available as #14835, with a responsive submitter.  It would be great to have it merged, if one of the DefinitelyTyped maintainers could take a look.

**Pull request closed without merging**
