### PR TITLE
[webappsec-credential-management] Align AuthenticatorSelectionCriteria with spec

### PR DESCRIPTION
**Pull request by Basaingeal**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://w3c.github.io/webauthn/#dictdef-authenticatorselectioncriteria
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by Hartimer — COMMENTED** [review]
This looks good to me, but why does this PR have so many additional commits in addition to the ones you're proposing?

**Comment by Basaingeal** [comment]
I think I messed up and rebased the branch tonight after the PR, not realizing it would after the original PR. This is one of my first PRs. Let me see if I can roll it back.

**Comment by Basaingeal** [comment]
There. It should just be two changed files now.

**Review by Hartimer — APPROVED** [review]
Thanks for the cleanup! LGTM

**Pull request merged**
