### PR TITLE
Feature/additional react big calendar dnd type definitions

### PR DESCRIPTION
**Pull request by fekete965**
**Last commit only**

(The parent PR contains a few clean ups so I thought I will build on top of that)

The type definitions were correct. I was only missing the ability to use some of these types so I can create my function(s) with the proper type definition.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop-props-full-prop-list--page)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-big-calendar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-big-calendar@latest/))
was missing the following properties:
1. components
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a1a4a9614a125f09377b5001ca3bb53f380d9e49
</p>

**Review by marknelissen — APPROVED** [review]

**Comment by fekete965** [comment]
I'm sorry, everybody the pings! I forgot to tell the bot to merge. I'll rebase and let the bot know it's good to go.

**Comment by fekete965** [comment]
No additional test suite is necessary as this PR only introduce a couple of interfaces.

**Comment by fekete965** [comment]
@marknelissen , I have only rebased the PR on master as it was based on my other PR.

**Pull request merged**
