### PR TITLE
[react-navigation] Update from latest official Flow definitions

### PR DESCRIPTION
**Pull request by abrahambotros**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-community/react-navigation/tree/52a2846e77119148320bcea83b8982a8bc6acce3
- [-] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

@huhuanming, @mhcgrq: I was having several issues using the existing types with the latest `react-navigation` code. This PR updates our definitions with the latest `react-navigation` changes and attempts to resolve some of these inconsistencies. As I'm sure you similarly did, the vast majority of changes here are from just porting the Flow from `TypeDefinition.js` (https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js) to TypeScript here. This results of course in many small restructuring changes across our code, so please feel free to point out anything that seems suspicious.

Unfortunately, some of these changes will be slightly breaking to existing users, but hopefully the implicit `npm` version bump will help people stay with the older version if need be. In general, hopefully this will bring our typings and the expectations from the latest `react-navigation` docs closer together.

### CODE REVIEW

**Comment by huhuanming** [comment]
Cool, I need some time.

**Comment by sandersn** [comment]
@huhuanming do you have time to look at this? Unfortunately, this is too large for one of the Typescript team to review it.

**Comment by huhuanming** [comment]
I am sorry... I thought it was be merged.
so next, resolve the conflicts?
I will review it at once.

**Comment by huhuanming** [comment]
@abrahambotros

**Comment by abrahambotros** [comment]
@huhuanming Merge conflicts resolved, should be ready for review now. Thanks again!

**Comment by huhuanming** [comment]
👍

**Review by huhuanming — APPROVED** [review]
LGTM

**Comment by abrahambotros** [comment]
@huhuanming, thanks so much!

@sandersn or @minestarks, would you be able to help with merging? Thanks!

**Pull request merged**
