### PR TITLE
Improvements for quill

### PR DESCRIPTION
**Pull request by guillaume-ro-fr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name`

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/quilljs/quill/releases/tag/v1.2.0
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by guillaume-ro-fr** [comment]
@sumitkm ping ?

**Comment by sumitkm** [comment]
Apologies, lost track of this one, the Travis build is good, the changes are good. Thanks for the PR.

**Comment by LouisWayne** [comment]
Is this valid?  My codes look like this now after this updates:
```
import { Quill } from 'quill';
new Quill('foo');
```
Then the compiled JS code is:
```
const quill_1 = require("quill");
new quill_1.Quill("foo");
```
However, `quill_1.Quill` is *undefined* - it's because TypeScript is not working well with compiled Barbell script (https://github.com/paypal/glamorous/issues/89).  Please advise.

**Comment by joscha** [comment]
@LouisWayne @guillaume-ro-fr @sumitkm This PR unfortunately introduces a wrong default export. Because the quill library is not an ES6 module, it needs to be a `export = Quill`.

Please have a look at [Can I change export = to export default](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default), e.g.:
> Do not change the type definition if it is accurate. For an NPM package, export = is accurate if node -p 'require("foo")' is the export, and export default is accurate if node -p 'require("foo").default' is the export.

which is true for Quill.

I think this PR needs to be reverted and then the changes applied in a separate PR, because `export =` can't co-exist with other exports - alternatively we can re-namespace the current library definitions, I am not sure, however, if this can be done easiliy without introducing other errors, as the changeset of this PR is fairly big.

references https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18947

**Pull request merged**
