### PR TITLE
Fixes #10355

### LINKED ISSUE #10355: Wrong definition of webdriver.By.js
``` TypeScript
 function js(script: any, ...var_args: any[]): (WebDriver: webdriver.WebDriver) => webdriver.promise.Promise<any>;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc3d223a946f661eff871787edeb0fcb8f0db156/selenium-webdriver/selenium-webdriver.d.ts#L5131

this definition doesn't work. `element()` expects a `Locator` but this method is defined to return `Promise<any>`. If we ignore typescript, everything works fine, so I think the definition is wrong here.

### PR DESCRIPTION
**Pull request by TitanNano**

### CODE REVIEW

**Comment by minestarks** [comment]
@TitanNano  Could you update the corresponding tests?

**Comment by Kuniwak** [comment]
I think that current return type of `By.js` is correct (please see [the definition of `By.js`](https://github.com/SeleniumHQ/selenium/blob/451eb05a5516368bbe0552cf1ce5666924b81c22/javascript/node/selenium-webdriver/lib/by.js#L178-L193)).

@TitanNano Could you show the actual code?

**Comment by TitanNano** [comment]
@Kuniwak this is how the protractor spec says it should be used:

```JavaScript
var wideElement = element(by.js(function() {...}));
```

Our TypeScript linter complains that `by.js()` is not of type `Locator`, but when we run the tests everything works fine.

**Comment by Kuniwak** [comment]
@TitanNano, This problem is caused by Protractor, not the type of `By.js`.

The function `element` uses internally `WebDriver#findElement` at [lib/element.ts#L174](https://github.com/angular/protractor/blob/5eb145ba9b7796cf2b9c2830f2ddc02d240e295e/lib/element.ts#L174). And `WebDriver#findElement` can handle not only `Locator` (as `By`) but also `Function` (see [selenium-webdriver/lib/webdriver.js#L887-L892](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L887-L892)).

So, it is considered a problem that is caused by type definitions of Protractor.

**Comment by paulvanbrenk** [comment]
Closing this as the issue doesn't seem to be in this definition file.

**Pull request closed without merging**
