### PR TITLE
On-finished 2.2.0 typings

### PR DESCRIPTION
**Pull request by czechboy0**

### CODE REVIEW

**Comment by vvakame** [comment]
@czechboy0 thank you your contributions.
please check this document http://definitelytyped.org/guides/contributing.html#tests

**Comment by czechboy0** [comment]
@vvakame Better? This is my first typing, so please bear with me :)

**Comment by czechboy0** [comment]
Needs fixing

**Comment by czechboy0** [comment]
Fixed, ready to be looked at, @vvakame

**Comment by vvakame** [comment]
@czechboy0 cool! thanks mate.

**Pull request merged**
