### PR TITLE
Modify react-popover for react@18

### PR DESCRIPTION
**Pull request by jrichil**
add children to props interface

Please fill in this template.

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-popover ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-popover@latest/))
was missing the following properties:
1. propTypes
1. defaultProps
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9a1ed44de4551a30889b917633031a836afbd29d
</p>

**Review by jacoporicare — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Packages are published every 30 minutes, so probably in about 15.

**Comment by jrichil** [comment]
I see it.
Thanks for your help.

**Comment by jrichil** [comment]
I see it.
Thanks for the help.

**Pull request merged**
