### PR TITLE
(connect-mongo) add dbName options

### PR DESCRIPTION
**Pull request by Naturalclar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/jdesboeufs/connect-mongo#more-options
https://github.com/jdesboeufs/connect-mongo/blob/master/CHANGELOG.md#320--2019-11-29

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by guyellis — COMMENTED** [review]
We copied the definition file over to https://github.com/jdesboeufs/connect-mongo/blob/master/src/types.d.ts which is where I think we should maintain them.

I tried to delete this but the PR error'd and I couldn't work out how to fix it.

**Comment by peterblazejewicz** [comment]
@guyellis 
Thanks for the review!

> I tried to delete this but the PR error'd and I couldn't work out how to fix it.

I'll rework this, know the drill.

@Naturalclar 
Are you happy with converting this PR into the deprecation of the `@types/connect-mongo`?
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by Naturalclar** [comment]
@guyellis 

Thanks for the info! I'll make a PR to the package itself :)

@peterblazejewicz 
Sure! This PR can be turned into deprecation of `@types/connect-mongo` :+1:

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Marking as changes requested until PR is reworked to deprecate the package.

**Pull request closed without merging**
