### PR TITLE
@types/plotly.js: Added vertex indices to PlotData

### PR DESCRIPTION
**Pull request by ghost**
Added vertex index arrays for [Mesh3D Traces](https://plotly.com/javascript/reference/mesh3d/) to PlotData type.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. register
1. Icons
1. Fx
1. Snapshot

<details>
<summary>as well as these 2 other properties...</summary>
<p>PlotSchema, Queue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2abbdf8e67e2a9e78011e1617e04a9c3e535c3f0
</p>

**Review by brammitch — COMMENTED** [review]
Is `TypedArray` alone the correct type for `i`, `j`, & `k`?

Looking at the [source code](https://github.com/plotly/plotly.js/blob/be93eb6e48d130b6419202e8b3aae28156dfdfbe/src/traces/mesh3d/attributes.js#L44), `i`, `j`, & `k` use the same `valType` of `data_array` as `x`, `y`, & `z`. I have not worked with mesh3d charts myself, so just wondering if `i`, `j`, & `k` should also have the `Datum[]` or `Datum[][]` types.

**Comment by daveth** [comment]
> Is `TypedArray` alone the correct type for `i`, `j`, & `k`?
> 
> Looking at the [source code](https://github.com/plotly/plotly.js/blob/be93eb6e48d130b6419202e8b3aae28156dfdfbe/src/traces/mesh3d/attributes.js#L44), `i`, `j`, & `k` use the same `valType` of `data_array` as `x`, `y`, & `z`. I have not worked with mesh3d charts myself, so just wondering if `i`, `j`, & `k` should also have the `Datum[]` or `Datum[][]` types.

(Personal account here, davidh-hugsmart is work account)
Yeah, that looks to be the case, but since these are vertex indices I thought an integer array made more sense in this case than just 'plottable data'.

**Review by brammitch — APPROVED** [review]
Thanks for the explanation.

**Comment by brammitch** [comment]
Ready to merge

**Pull request merged**
