### PR TITLE
feat(mailchimp__mailchimp_marketing): add addListMember/updateListMember/deleteListMemberPermanent definitions

### PR DESCRIPTION
**Pull request by jeremybarbet**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/
https://mailchimp.com/developer/marketing/api/list-members/update-list-member/
https://mailchimp.com/developer/marketing/api/list-members/delete-list-member/

### CODE REVIEW

**Review by rattkin — APPROVED** [review]
Good job!

**Comment by jeremybarbet** [comment]
@rattkin Thanks for the quick review 👍 

Ready to merge

**Comment by jeremybarbet** [comment]
@orta Sorry to bother, any ideas why the bot isn't merging?

**Comment by orta** [comment]
I'll merge this manually, and tail the bots logs to see If anything is up - thanks

**Pull request merged**
