### PR TITLE
[node] added crypto.randomUUID

### PR DESCRIPTION
**Pull request by marekkobida**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/dist/latest-v15.x/docs/api/crypto.html#crypto_crypto_randomuuid_options>

### CODE REVIEW

**Comment by marekkobida** [comment]
```
Error in mongoose
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/mongoose/test/model.ts:613:107
```

wtf?

**Comment by peterblazejewicz** [comment]
It just reads that `mongoose` fail tests under TS4.2, which is just run as deps of current change (you called a genie). Let me check mongoose locally, one sec

**Comment by peterblazejewicz** [comment]
Nope, nothing, mongoose modification just passes under 4.2 (local). Can you force push to rerun CI?

**Comment by marekkobida** [comment]
again it does not work after force push... it looks like "dtslint" ignoring "$ExpectError" in comment

**Comment by panva** [comment]
`randomUUID` was only added in v15 so far which is pending its own namespace in @types, pending #48981 || #50281

**Comment by tniessen** [comment]
@marekkobida Would you like to revive this? v15 has landed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52357 and the feature will also be included in the next v14 release of Node.js.

**Comment by SimonSchick** [comment]
@marekkobida I will pull this into my PR for v15.6 which will be out by tomorrow or so.

**Comment by SimonSchick** [comment]
cc @tniessen

**Pull request closed without merging**
