### PR TITLE
Add contextMenuHidden to TextInput

### PR DESCRIPTION
**Pull request by pavsidhu**

### CODE REVIEW

**Comment by alloy** [comment]
Thanks! Can you please add a test that shows an example of this being used?

**Comment by pavsidhu** [comment]
Test added 😄

**Comment by huhuanming** [comment]
but the travis CI build failed

**Comment by pavsidhu** [comment]
@huhuanming it's passing now

**Review by timwangdev — APPROVED** [review]
LGTM

**Comment by alloy** [comment]
Thanks!

**Pull request merged**
