### PR TITLE
koa-better-body: Provides its own types

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This will deprecate `@types/koa-better-body` in favor of just `koa-better-body`. CC @danwbyrne

### CODE REVIEW

**Comment by neezer** [comment]
@a-tarasyuk I do not see https://github.com/tunnckoCore/koa-better-body/releases releasing a `3.1.0` release, and the source code does not ship with a definition file. The latest release appears to be `3.0.4`. Why was this deprecated? My CI build is now failing. 😢

**Comment by neezer** [comment]
@a-tarasyuk Correction: the latest version of the package `3.1.13` does not appear to ship with definitions:

```
✦2 ❯ npm pack koa-better-body
npm notice 
npm notice 📦  koa-better-body@3.1.13
npm notice === Tarball Contents === 
npm notice 619B   dist/main/index.js      
npm notice 477B   dist/module/index.js    
npm notice 4.9kB  dist/main/utils.js      
npm notice 4.4kB  dist/module/utils.js    
npm notice 2.5kB  package.json            
npm notice 2.2kB  dist/main/index.js.map  
npm notice 2.3kB  dist/module/index.js.map
npm notice 13.1kB dist/main/utils.js.map  
npm notice 13.3kB dist/module/utils.js.map
npm notice 19.0kB CHANGELOG.md            
npm notice 24.1kB README.md               
npm notice === Tarball Details === 
npm notice name:          koa-better-body                         
npm notice version:       3.1.13                                  
npm notice filename:      koa-better-body-3.1.13.tgz              
npm notice package size:  20.9 kB                                 
npm notice unpacked size: 86.9 kB                                 
npm notice shasum:        eab742745401eff70b8069b29c284df87be2c1a6
npm notice integrity:     sha512-744Ay3hXDobRS[...]xC4sWJbErFndg==
npm notice total files:   11                                      
npm notice 
koa-better-body-3.1.13.tgz
```

**Comment by a-tarasyuk** [comment]
@neezer This PR was generated automatically from this list https://gist.github.com/sandersn/d9ca982ff4d66be453d2c6f8f9be7fb9

```shell
Typings already defined for koa-better-body (koa-better-body) as of 3.1.0 (our version: 3.0)
  To fix this:
  git checkout -b not-needed-koa-better-body
  yarn not-needed koa-better-body 3.1.0 https://github.com/tunnckoCore/koa-better-body
  git add --all && git commit -m "koa-better-body: Provides its own types" && git push -u origin not-needed-koa-better-body
  And comment PR: This will deprecate `@types/koa-better-body` in favor of just `koa-better-body`. CC @danwbyrne
```

**Comment by neezer** [comment]
@a-tarasyuk How does that list get generated? I think it might have a bug, because the package does not provide definitions.

I took a look at `3.1.0` and it also does not ship with definitions:

```
✦ ❯ npm pack koa-better-body@3.1.0
npm notice 
npm notice 📦  koa-better-body@3.1.0
npm notice === Tarball Contents === 
npm notice 661B   dist/main/index.js      
npm notice 477B   dist/module/index.js    
npm notice 4.9kB  dist/main/utils.js      
npm notice 4.4kB  dist/module/utils.js    
npm notice 2.3kB  package.json            
npm notice 2.2kB  dist/main/index.js.map  
npm notice 2.3kB  dist/module/index.js.map
npm notice 12.9kB dist/main/utils.js.map  
npm notice 13.1kB dist/module/utils.js.map
npm notice 14.6kB CHANGELOG.md            
npm notice 16.5kB README.md               
npm notice === Tarball Details === 
npm notice name:          koa-better-body                         
npm notice version:       3.1.0                                   
npm notice filename:      koa-better-body-3.1.0.tgz               
npm notice package size:  17.4 kB                                 
npm notice unpacked size: 74.4 kB                                 
npm notice shasum:        67c04cb2c9899bfea51f619225f47c594329cce0
npm notice integrity:     sha512-iZNrIT7oRj6kR[...]7vy5xRCSqFobQ==
npm notice total files:   11                                      
npm notice 
koa-better-body-3.1.0.tgz
```

---

Can `@types/koa-better-body` be restored?

**Comment by a-tarasyuk** [comment]
@neezer I think your question is better to ask @sandersn, I, hope he can help

**Comment by neezer** [comment]
@sandersn Is it possible to restore `@types/koa-better-body`? As you can see from the comments above, the typedefs are still needed. I believe whatever process generates https://gist.github.com/sandersn/d9ca982ff4d66be453d2c6f8f9be7fb9 erroneously flagged `koa-better-body` and no longer needing definitions published on DefinitelyTyped.

**Comment by a-tarasyuk** [comment]
@sandersn I see that the package has typing definition in `package.json` https://unpkg.com/browse/koa-better-body@3.1.13/package.json, however, seems types were not deployed to npm https://unpkg.com/browse/koa-better-body@3.1.13/dist/

**Comment by neezer** [comment]
@a-tarasyuk So it seems the script to determine whether or not a package ships with its own type definitions goes off of the `typings` property in `package.json`, but not whether or not that file is actually included in the distribution... ?

It looks like the author has moved the repo to a monorepo, so I'm wondering if the build process for the switch is not shipping the actual definition. With this package deprecated, then, that leaves `koa-better-body` in an uncompilable state.

I'll open an issue with the package author about the missing file, but it still troubles me that its possible for a `@types/*` package to be removed because the `typings` field in `package.json` is present, yet the file that it points to is not.

**Comment by tunnckoCore** [comment]
Author here. Please revert.

**Comment by sandersn** [comment]
I rolled the `latest` tag back to 3.0.0.

This is a once-per-year cleanup run, which is just a simple script followed by human intervention, then another script, then more human intervention, then CI, then a human review. In this case the human did not review the change. I think the process performed as well as can be expected given the unexpected pattern of pre-populating the `typings` field.

**Comment by tunnckoCore** [comment]
Yup. Good point. Thanks.

**Pull request merged**
