### PR TITLE
[babel-plugin-react-html-attrs] Remove unused lint exceptions

### PR DESCRIPTION
**Pull request by jablko**
#47588

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## babel-plugin-react-html-attrs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/babel-plugin-react-html-attrs@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'babel-plugin-react-html-attrs'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 841a1904aad2615eddc187e14c504810f94e894a
</p>

**Comment by sandersn** [comment]
@jablko can you throttle these to 1-2 per hour, averaged over a day at most? We don't have the computer time to run tests on all of them, so they're starving CI runs of other PRs.

**Comment by jablko** [comment]
@sandersn Yup, will do :+1:

**Comment by sheetalkamat** [comment]
@jablko Instead of creating PR for every package separately can you please merge say 10-20 packages in one or something like that.. It takes a while to go through this Prs and merge.

**Pull request merged**
