### PR TITLE
fix definition for addScriptTag return type

### PR DESCRIPTION
**Pull request by bdurrani**
returns ElementHandle instead of void

https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pageaddscripttagoptions

There are no tests for this

Please fill in this template.

- [ X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pageaddscripttagoptions

### CODE REVIEW

**Comment by bdurrani** [comment]
@marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita

**Review by cdeutsch — APPROVED** [review]
Looks good 👍

**Review by SimonSchick — CHANGES_REQUESTED** [review]
This looks _ok_ but a  test would  be nice.

**Comment by SimonSchick** [comment]
Also can you add `addScriptTag` to `Frame`?

**Comment by bdurrani** [comment]
> Also can you add `addScriptTag` to `Frame`?

`FrameBase` already has `addScriptTag`. `Frame` extends `FrameBase`

**Comment by bdurrani** [comment]
Hey all. Any chance we can merge this in soon?

**Comment by cdeutsch** [comment]
I think it's up to @SimonSchick because they requested changes.

You could close this PR and re-do it, and I can approve again.

**Review by cdeutsch — APPROVED** [review]

**Pull request closed without merging**
