### PR TITLE
Adds GitHub Actions

### PR DESCRIPTION
**Pull request by orta**
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44906

### CODE REVIEW

**Comment by orta** [comment]
I think by default it doesn't send emails in the same way that travis used to (which we [configured to be off](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications)) - so I don't think we need anything related to that in here.

**Comment by orta** [comment]
The danger issue is this: https://github.com/danger/danger-js/issues/1042

Maybe I'll ship a quick danger release to fix it while we wait for the actions builds to update

**Comment by orta** [comment]
Added protection for #44920

**Review by sandersn — APPROVED** [review]
Looks good; I confirmed separately that running danger both from Actions and Travis won't cause dupes.

**Pull request merged**
