### PR TITLE
[ipv6addr] Add missing members to Addr, add alternative types to params

### PR DESCRIPTION
**Pull request by ssteinvil-forescout**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
    - Addr.and: https://github.com/joyent/node-ip6addr/blob/master/ip6addr.js#L304
    - Addr.or: https://github.com/joyent/node-ip6addr/blob/master/ip6addr.js#L314
    - Addr.not: https://github.com/joyent/node-ip6addr/blob/master/ip6addr.js#L324
    - Addr.clone: https://github.com/joyent/node-ip6addr/blob/master/ip6addr.js#L264
    - Alternative parameter types (string | Addr | CIDR | number) usually come from the [_toAddr()](https://github.com/joyent/node-ip6addr/blob/master/ip6addr.js#L51) calls

### CODE REVIEW

**Review by slaweet — CHANGES_REQUESTED** [review]
@ssteinvil-forescout thanks for the contribution. I find it quite hard to be sure I notice all the functional changes among all the formatting changes (from some auto-formatter?) (different indentation, different quotation marks). Could you please make a commit with only the functional changes?

**Comment by ssteinvil-forescout** [comment]
@slaweet, you are definitely right, all the auto-formatting comes from prettier, which is configured at the top level of DefinitelyTyped project.  

I do not mind repeating my changes in Notepad to avoid auto-formatting and make the review process simpler and I will do that.

However, I think that respecting a coding style of the host project is also important.  I think we can start from what you suggested and complete the functional part.  Then - after finishing the review and merge of the first PR - I can submit another PR with auto-formatting only.  What do you think?  Is that OK with you?

**Comment by ssteinvil-forescout** [comment]
Just in case you are not familiar with this feature, hiding whitespace differences would also simplify the review:

image

**Review by slaweet — APPROVED** [review]
@ssteinvil-forescout thanks for the hint about the "hiding whitespace" feature. I wasn't familiar with and it'll be handy in future.

Looking at your changes, I see you did a great job digging into the source code of `ip6addr` to find all the options that docs (README) of `ip6addr` say nothing about. :+1:

**Comment by ssteinvil-forescout** [comment]
Ready to merge

**Pull request merged**
