### PR TITLE
Updated bazinga-translator to accept null for some parameters where code supports it.

### PR DESCRIPTION
**Pull request by aurelijusrozenas**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
     - [ ] Cannot run tests, does not work, let's see CI status
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Updated by looking at `translator.js` directly, could not find source online :/
- [~] Increase the version number in the header if appropriate.
- [~] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by aurelijusrozenas** [comment]
@RyanCavanaugh what should I do?

**Comment by andrewbranch** [comment]
I’m gonna close and reopen to see if CI wakes up

**Comment by andrewbranch** [comment]
@aurelijusrozenas for some inconceivable reason, this PR has triggered Travis’s abuse mechanism. Could you maybe try just pushing another commit to it? You could try an empty one, but maybe some trivial change would be more likely to work? Sorry, I know this is stupid. If this doesn’t work we’ll try something different tomorrow.

**Comment by aurelijusrozenas** [comment]
@andrewbranch I guess that did not work.

**Comment by weswigham** [comment]
Strange, but I guess this is why we also have ADO builds. Here's to hoping merging this doesn't make Travis stop building `master`, since this seems fine.

**Pull request merged**
