### PR TITLE
 @types/passport-http: fix unused template param #1 

### PR DESCRIPTION
**Pull request by ianwremmel**
It looks like this was rigged up so the appropriate callback definition could be inferred, but one detail got missed.

@krizalys
@tlaziuk
@cjbarth
@jamesadarich

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by cjbarth — COMMENTED** [review]
I'm not sure why this change is being requested. It seems from looking at passport/index.d.ts that this indeed should be a `boolean`.

**Comment by ianwremmel** [comment]
It's still a boolean, but it's the template parameter `req extends boolean = boolean`. Without this change, the constructor overloads at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/234afdc55eee47734f0801e1532eea104318eeac/types/passport-http/index.d.ts#L58-L59 have no effect. `new BasicStrategy({passReqToCallback: true}, (req, username, password, done) =>...)` produces a type error because `{passReqToCallback: true}` satisfies both overloads. 

With the change, it can see that the `true` signals that the second parameter passed to `BasicStrategy()` is definitely `BasicVerifyFunctionWithRequest` and not `BasicVerifyFunction|BasicVerifyFunctionWithRequest`.

**Comment by cjbarth** [comment]
I follow your logic there, though I've never leveraged that feature of TypeScript myself. Could you write a test that validates that kind of typing works with the constructor overloads you describe?

**Comment by ianwremmel** [comment]
I think so. (I think) this my first DT PR. Do I just write some example code and make sure there are no type failures?

**Comment by cjbarth** [comment]
Yep. There is a test file already in the repo. You can put the code there with all the typings that you want to work and it will be preserved for future modders :)

**Comment by cjbarth** [comment]
I'll have a look at this later today or tomorrow.

**Review by cjbarth — APPROVED** [review]

**Pull request merged**
