### PR TITLE
Add danger for showing dts-critic suggestions

### PR DESCRIPTION
**Pull request by sandersn**
I have no idea if this will work; this is based on an idea by @orta but I'm not using Github Actions or yarn.
(original PR is here: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/pull/225)

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  Error: Could not find a `dangerfile.js` or `dangerfile.ts` in the current working directory.
    at Object.dangerfilePath (/home/vsts/work/1/s/node_modules/danger/distribution/commands/utils/fileUtils.js:26:11)
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/danger/distribution/commands/danger-runner.js:92:42)
    at step (/home/vsts/work/1/s/node_modules/danger/distribution/commands/danger-runner.js:33:23)
    at Object.next (/home/vsts/work/1/s/node_modules/danger/distribution/commands/danger-runner.js:14:53)
    at fulfilled (/home/vsts/work/1/s/node_modules/danger/distribution/commands/danger-runner.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 463542c4caeb88ac7339cf7441840f844a2d0564
</p>

**Comment by sandersn** [comment]
Wow, good job danger! At least you ran!

(going to write a real dangerfile now)

**Comment by sandersn** [comment]
Thanks for the dangerfile.ts @orta. Lesson learned: it's hard to add a gitignored .js file to DT, even on purpose.

**Comment by orta** [comment]
fixes https://github.com/DefinitelyTyped/dt-mergebot/issues/27

**Comment by orta** [comment]
Danger should say nothing when there are no suggestions (then the GitHub comment will be deleted)

**Comment by sandersn** [comment]
@orta I'll eventually remove the "no suggestions found" message, but I have to explicitly handle the case when dts-critic doesn't produce suggestions, and I wanted to make sure my predicate was working.

**Comment by sandersn** [comment]
The suggestions are only showing up on Travis for some reason. I'm going to move danger over there for now and back to pipelines when I figure out why it doesn't have suggestions.

**Comment by sandersn** [comment]
@orta want to review this? I'll revert the yauzl and aframe changes after you take a look.

**Comment by sandersn** [comment]
@gabritto you might be interested in this too

**Comment by orta** [comment]
I've given it a bit of a tweak

**Comment by gabritto** [comment]
@sandersn very nice to see this being implemented :)

**Comment by orta** [comment]
Might need to improve dts critic to have richer line/file references, the unpkg link for aframe is `dist/index.js` but the file reference I was working with is `index.d.ts` and converting that to a JS file isn't enough

**Comment by sandersn** [comment]
All right, this is where I want it for now. Since I'm on duty this week, I'll take some time to figure out why dts-critic isn't logging suggestions on Azure so I can switch danger off of Travis.

For now I want to merge this so I can see how well it works.

**Pull request merged**
