### PR TITLE
[koa-session] Parameterize the session middleware

### PR DESCRIPTION
**Pull request by ryota-ka**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
  - There are no tests for `@types/koa-session`
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
  - There are no tests for `@types/koa-session`
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
  - There are no tests for `@types/koa-session`

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31704
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by ryota-ka** [comment]
Hmm, The CI build is failing due to violations of `no-unnecessary-generics`, but it looks like a false positive for me.
`ResponseBodyT` should still be meaningful as far as it's passed to another type as a generic parameter.

**Review by tlaziuk — APPROVED** [review]
looks good, and no need of changing the test file proves it's backward compatible change

**Comment by ryota-ka** [comment]
@tlaziuk Thank you for the review!

**Comment by ryota-ka** [comment]
Ready to merge

**Pull request merged**
