### PR TITLE
Improve gapi HttpRequestPromise thanks to TypeScript 2.3

### PR DESCRIPTION
**Pull request by tkrotoff**
TypeScript 2.3 has been released, let's improve gapi HttpRequestPromise.

See the related [TypeScript promise issue that has been fixed with version 2.3](https://github.com/Microsoft/TypeScript/issues/12409)

Not to be merged yet: Travis CI will fail until TypeScript 2.3 is supported

### CODE REVIEW

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by tkrotoff** [comment]
@mhegazy This PR is valid and has been reviewed. It's just waiting for DefinitelyTyped to support TypeScript 2.3 => that's why Travis CI fails
Please re-open

**Comment by rbuckton** [comment]
@tkrotoff I re-ran the Travis CI build and it is still failing. This is because the following DT packages depend on `gapi` and have not also been updated to include `// TypeScript Version: 2.3`:

* gapi.analytics
* gapi.auth2
* gapi.calendar
* gapi.pagespeedonline
* gapi.people
* gapi.plus
* gapi.translate
* gapi.urlshortener
* gapi.youtube
* gapi.youtubeanalytics

You can see the build errors here: https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/226723664

Please correct the above errors and resubmit a new PR. Thanks!

**Comment by tkrotoff** [comment]
@rbuckton If you could reopen this PR, I would be able to fix the other definitions...

**Comment by tkrotoff** [comment]
@rbuckton thx :)

**Comment by tkrotoff** [comment]
@rbuckton would be nice to have an announcement system (like https://github.com/aspnet/Announcements ?) so contributors are aware when a new version of TypeScript is supported on DefinitelyTyped

**Pull request merged**
