### PR TITLE
Bugfix: change class extends interface -> class implements interface

### PR DESCRIPTION
**Pull request by BLun78**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by cjbarth** [comment]
Why is this change being made?

**Comment by mwolfhoffman** [comment]
Hey guys, I was just about to make this PR since it's breaking an app I'm about to deploy. Just want to comment to make sure there are some eyes on this.

**Comment by mwolfhoffman** [comment]
@cjbarth the changes a month ago that switched implements to extends throws an error and I can't build my code. Passport.strategy is an INTERFACE not a CLASS so it has to be `implements` instead of `extends`. You can't implement an interface.

**Comment by cjbarth** [comment]
@mwolfhoffman Please see the PR that I linked for the correct solution to your breaking problem. I actually had code the broke from this change a month ago too, but the correct solution isn't to roll back this one line as that would break all the other Passport modules in DefinitelyTyped and would break this module for everyone using the latest Passport typings.

If you still feel this is a problem, please post all the versions of Passport and associated modules that you are using (the versions that actually get installed), along with the versions of the typings that you are using (again, the versions that actually got installed). Please also provide the versions you are requesting via `packages.json`.

**Comment by BLun78** [comment]
Hey,

the problem is on build.
`/node_modules/@types/passport-saml/index.d.ts(27,31): error TS2689: Cannot extend an interface 'passport.Strategy'. Did you mean 'implements'?`
 [problem for class look here for Inheritance](https://www.typescriptlang.org/docs/handbook/classes.html)

You imports an interface 'passport.Strategy'. extends is for classes.
`/node_modules/@types/passport/index.d.ts`

So please change.

**Comment by BLun78** [comment]
Ok @cjbarth i see `packages.json` works.
[The code for passport in Github Master branche](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport/index.d.ts) is an interface.

**Comment by cjbarth** [comment]
@BLun78 yes, that is why I don't to merge this PR. If you pin all the packages for they types you use as outlined in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24682 you should be able to avoid this compilation error. If this is the case, please abandon this PR.

**Comment by rbuckton** [comment]
Since this is related to package versioning, which can be addressed either via pinning the version or updating a dependent package, I'm closing this PR.

**Pull request closed without merging**
