### PR TITLE
react-test-renderer: add array return types for fragment components

### PR DESCRIPTION
**Pull request by AlexLisenkov**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://codesandbox.io/s/jovial-dhawan-qddtb?file=/src/App.test.tsx>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by AlexLisenkov** [comment]
@arvitaly @lochbrunner @johnnyreilly @jgoz @Jessidhia @maddhruv  anyone?

**Comment by jgoz** [comment]
The changes look fine on their own, but I'm missing the context for whether they are correct. Do you have a link to the source or docs showing that `rendered` may be an array?

**Comment by AlexLisenkov** [comment]
Hi @jgoz, I could not find anything in the documentation other than it returning a "rendered tree".

Because of no clear documentation I wrote three tests to show when it returns an array, object and null.

https://codesandbox.io/s/jovial-dhawan-qddtb?file=/src/App.test.tsx

**Comment by AlexLisenkov** [comment]
Also: https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js#L467 as proof

**Review by jgoz — APPROVED** [review]
Perfect, thanks for that!

**Comment by AlexLisenkov** [comment]
Ready to merge

**Pull request merged**
