### PR TITLE
Express: add missing generics

### PR DESCRIPTION
**Pull request by OliverJAsh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by puneetar — APPROVED** [review]
Thanks @OliverJAsh  for updating this.

**Comment by emilgoldsmith** [comment]
Hey @OliverJAsh I think this made the types incompatible with express-serve-static-core it seems. It broke my types when passing in handlers to an Express Router, as that lives in the core repo, as that has 3 generics while this now has 4 (or that's what I believe the reason is). I had to import the requesthandler from serve-static-core. 

Do you have an idea of what a fix for this looks like? Also the reason it broke for me may be because I'm using the alpha express release

**Comment by OliverJAsh** [comment]
Hey @emilgoldsmith. It sounds like you need to upgrade your version of `express-serve-static-core`, as that was recently changed to receive 4 generics.

**Comment by emilgoldsmith** [comment]
Thanks @OliverJAsh for the quick reply, I'll look into that!

**Comment by joshuous** [comment]
Hi @OliverJAsh! I would like to clarify with you whether the intent of this commit is to allow us to specify the expected type of `req.body` in the generics?

I am trying something like this:

```javascript
export const createTodo: RequestHandler<{}, any, { text: string }> = (req, res, next) => {
    const { text } = req.body; // text is known to be a string
    // .....
}
```

**Comment by OliverJAsh** [comment]
Yes that is one of the things this PR will enable.

**Comment by carlosingles** [comment]
Hey @OliverJAsh first of all thanks for the explanations that you have provided regarding these updates (I read through the other PRs), however I am still having trouble with the updated types.

I have reproduced the issue here: https://repl.it/repls/LeafyBrilliantOs

I'm not sure why the types become broken when `response` is put into play, is there something I'm doing wrong here? I'm using the latest version of both type libraries and was explicit in my `package.json` definition.

**Comment by OliverJAsh** [comment]
@carlosingles This looks very similar to the problem I addressed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434#issuecomment-617638746.

As I noted there, this error occurred even before this change was made. (Note it only occurs when `strictFunctionTypes` is enabled.)

Unfortunately I don't know what the problem is, but it's not related to this change so I'm not sure I'm the best person to look into it.

If you can provide a reduced test case that _works with the versions before this change_, I would be happy to take another look for you!

**Pull request merged**
