### PR TITLE
selenium-webdriver: Update webdriver.WebDriver

### PR DESCRIPTION
**Pull request by Kuniwak**
### Target
- [javascript/webdriver/webdriver.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/webdriver.js)
### Docs
- [selenium-webdriver](http://selenium.googlecode.com/git/docs/api/javascript/index.html)

### CODE REVIEW

**Comment by Kuniwak** [comment]
I'm trying to implement [`webdriver.By.Hash`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/locators.js#L76), but I'm not sure how to implement it.

`webdriver.By.Hash` is a Closure Llibrary style type alias.
If we assign `webdriver.By.Hash`, we get an `undefined`.
I think the assignment should have an error, because it have no meanings.

I want to implement the behavior, but I got the errors by the following code.
And strangely, the type definitions [worked fine](http://www.typescriptlang.org/Playground#src=%2F%2F%20minumum%20example%0Adeclare%20module%20webdriver%20%7B%0A%09interface%20ILocatorStrategy%20%7B%0A%09%09id(value%3A%20string)%3A%20Locator%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20...%0A%09%7D%0A%0A%09var%20By%3A%20ILocatorStrategy%3B%0A%09%0A%09module%20By%20%7B%0A%09%09type%20Hash%20%3D%20%7B%20id%3A%20string%20%7D%20%7C%20%7B%20className%3A%20string%20%7D%20%2F*%20%7C%20...%20*%2F%3B%0A%09%7D%0A%0A%09class%20Locator%20%7B%0A%09%09using%3A%20string%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20...%0A%09%7D%0A%7D%0A%0Aconst%20By%20%3D%20webdriver.By%3B%20%2F%2F%20ok%0Aconst%20locator%20%3D%20webdriver.By.id('a')%3B%20%2F%2F%20ok%0Aconst%20locatorHash%3A%20webdriver.By.Hash%20%3D%20%7B%20id%3A%20'a'%20%7D%3B%20%2F%2F%20ok%0Aconst%20expectedFail%20%3D%20webdriver.By.Hash%3B%20%2F%2F%20should%20be%20a%20compile%20error) on the TypeScript playground page.

Please help me.

#### The code I tried
```typescript
// minumum example
declare module webdriver {
	interface ILocatorStrategy {
		id(value: string): Locator;
                // ...
	}

	var By: ILocatorStrategy;
	
	module By {
		type Hash = { id: string } | { className: string } /* | ... */;
	}

	class Locator {
		using: string;
                // ...
	}
}

const By = webdriver.By; // ok
const locator = webdriver.By.id('a'); // ok
const locatorHash: webdriver.By.Hash = { id: 'a' }; // ok
const expectedFail = webdriver.By.Hash; // should be a compile error
```

#### The error I got by `npm test`
```
# npm test
...
selenium-webdriver/selenium-webdriver.d.ts(4784,9): error TS2300: Duplicate identifier 'By'.
selenium-webdriver/selenium-webdriver.d.ts(4786,12): error TS2300: Duplicate identifier 'By'.
...
```

**Comment by haskellcamargo** [comment]
```typescript
const locatorHash: webdriver.By.Hash = { id: 'a' }; // ok
const expectedFail = webdriver.By.Hash; // should be a compile error
```
1. Note that `webdriver.By.Hash` is a type, if you can **use** it to be assigned, maybe you are doing it wrong. You should choose if it is either a type definition or a property, not both.

```typescript
const locatorHash: { [key: string]: any } = { id: 'a' };
```

2. I don't believe this should be a type error, in this case, the property doesn't seem to be monotyped, it can either carry or don't carry a value, it isn't responsability of the type system per se. This could be fixed with monads - and also Haskell, with a powerful type system, has types and typeclasses to deal with computations that may fail:

`data Maybe = Just t | Nothing`
`data Either = Left a | Right b`

```haskell
division :: Int -> Int -> Maybe Int
division 0 _ = Just 0
division _ 0 = Nothing
division x y = Just (x / y)
```

**Comment by Kuniwak** [comment]
I appreciate your help, @haskellcamargo .

> Note that webdriver.By.Hash is a type, if you can use it to be assigned, maybe you are doing it wrong. You should choose if it is either a type definition or a property, not both.

I meant that `webdriver.By.Hash` is a type definition.

> I don't believe this should be a type error, in this case, the property doesn't seem to be monotyped, it can either carry or don't carry a value, it isn't responsability of the type system per se. This could be fixed with monads - and also Haskell, with a powerful type system, has types and typeclasses to deal with computations that may fail:

No, I think it should be a type error.
Because methods related the type (such as `webdriver.WebDriver#findElement` family) require a record that have only a property. We can pass a record that has multiple properties to [the dynamic assertion](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/locators.js#L237) and it make no errors, but it seems coincidence.

However, my implementation was not enough.
It pass invalid locators that have multiple properties.
I'm going to improve the definition to the following.

```typescript
type Hash = { id: string, css?: void } | { css: string, id?: void };

// ok
const valid1: Hash = { id: 'a' };
const valid2: Hash = { css: 'b' };

// ng
const invalid1: Hash = {};
const invalid2: Hash = { id: 'a', css: 'b' };
```

**Comment by Kuniwak** [comment]
I solved the issue.

I was misled into thinking that following code is impossible without using `import` declaration.

```typescript
declare module webdriver {
    module By {
        function id(id: string): Locator;
    }
}

const By = webdriver.By; // can work!
```

**Comment by Kuniwak** [comment]
I tried my best, but there are too large diff to me.
So types not updated are still remaining.

Would you review the current changes please?
And next time, I'm going to try to update the remained.

**Comment by Kuniwak** [comment]
Hi, @BillArmstrong 

I tried to update part of important types of WebDriverJS.
I'd like to review my changes, because I'm not sure this changes are right.
Would you review it please?

**Comment by vvakame** [comment]
@BillArmstrong could you review this pull request?

**Comment by BillArmstrong** [comment]
I took a quick look last week, but it is a pretty significant change. I don't really have the time to give it the thorough review that it deserves.

**Comment by vvakame** [comment]
@BillArmstrong okey! I try to wait until the next Sunday.

**Comment by Kuniwak** [comment]
@vvakame, What can I do for merging it?

**Comment by vvakame** [comment]
@BillArmstrong can you review now? I'll merge this pull request tomorrow.
@Kuniwak please add your name into definition header.

**Comment by Kuniwak** [comment]
@vvakame Done.

**Comment by vvakame** [comment]
@Kuniwak thanks mate!

**Pull request merged**
