### PR TITLE
[three] r141

### PR DESCRIPTION
**Pull request by joshuaellis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by joshuaellis** [comment]
I think we've misunderstood how to use another type library (`@types/webxr`)... any pointers?

**Comment by Methuselah96** [comment]
https://github.com/three-types/three-ts-types/pull/223

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. ColorManagement
1. Font
1. FontLoader
1. ImmediateRenderObject
1. LinearSRGBColorSpace

<details>
<summary>as well as these 4 other properties...</summary>
<p>NoColorSpace, ParametricGeometry, SRGBColorSpace, TextGeometry</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3d4b5217285cb4f92b2d654ade8811389d282a0f
</p>

**Review by Methuselah96 — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by joshuaellis** [comment]
Ready to merge

**Pull request merged**
