### PR TITLE
Flux utils

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/6257

### CODE REVIEW

**Comment by stkb** [comment]
I don't use this at the moment but I can't see any problems, except that there are no tests added.

**Comment by GiedriusGrabauskas** [comment]
Tests added from https://facebook.github.io/flux/docs/flux-utils.html

**Comment by stkb** [comment]
:thumbsup:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
