### PR TITLE
[dns-packet] Add OptAnswer Type

### PR DESCRIPTION
**Pull request by SE2Dev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mafintosh/dns-packet/blob/master/index.js#L823

### CODE REVIEW

**Review by KapitanOczywisty — CHANGES_REQUESTED** [review]
1. `OPT` has multiple formats depending on code and is also slightly different for received vs sended packet. Implementing every possible key for every type is a mistake in my opinion. And also every property is required, thus this won't work anyway.
2. `OPT` test should have at least plausible packet, this one will throw exception in `dns-packet` since code is unknown
3. Comments like `UInt16BE`, are useless in typings
4. I'd keep `ttl`, `class`, `flush` in only single test, since these are optional, they should be also tested for not being present.
5. ` | undefined` was added for compatibility with Typescript 4.4

**Comment by SE2Dev** [comment]
> 1. `OPT` has multiple formats depending on code and is also slightly different for received vs sended packet. Implementing every possible key for every type is a mistake in my opinion. And also every property is required, thus this won't work anyway.

I left keys for each of the subtypes used for the `OptAnswer.options` interface. I can remove them and replace it with `Record<string, unknown>` or similar if requested.

> 2. `OPT` test should have at least plausible packet, this one will throw exception in `dns-packet` since code is unknown
I've changed the `OPT` test to include a valid packet, with multiple variations of sub options, as well as tested these packets against the actual `dns-package` library.

> 3. Comments like `UInt16BE`, are useless in typings
I'd argue that these provide insight as to the valid value ranges (via intellisense, etc.) for their respective properties, but I removed them anyway.

> 4. I'd keep `ttl`, `class`, `flush` in only single test, since these are optional, they should be also tested for not being present.
Fixed

> 5. ` | undefined` was added for compatibility with Typescript 4.4
I'm not sure why I didn't realize this at the time, but I've since fixed it.

**Comment by KapitanOczywisty** [comment]
Sorry for the late reply

> I left keys for each of the subtypes used for the `OptAnswer.options` interface. I can remove them and replace it with `Record<string, unknown>` or similar if requested.

Ideally all known packets should be listed or at least most useful. You can start with these which are interesting to you and let future contributor expand list from there.

```ts
interface OptClientSubnet {
  type: "CLIENT_SUBNET";
  sourcePrefixLength?: number;
  scopePrefixLength?: number;
  family?: number;
  ip: string;
}
// ...
type OptPackets = OptClientSubnet | .... ;

export interface OptAnswer extends GenericAnswer<"OPT"> {
  options: OptPackets[];
}
```

**Comment by elibarzilay** [comment]
@KapitanOczywisty: ping re [the above comment](#issuecomment-911408547)

**Review by weswigham — CHANGES_REQUESTED** [review]
Double ping and set PR status for the suggestion above~

**Comment by SE2Dev** [comment]
> Sorry for the late reply
> 
> > I left keys for each of the subtypes used for the `OptAnswer.options` interface. I can remove them and replace it with `Record<string, unknown>` or similar if requested.
> 
> Ideally all known packets should be listed or at least most useful. You can start with these which are interesting to you and let future contributor expand list from there.
> 
> ```ts
> interface OptClientSubnet {
>   type: "CLIENT_SUBNET";
>   sourcePrefixLength?: number;
>   scopePrefixLength?: number;
>   family?: number;
>   ip: string;
> }
> // ...
> type OptPackets = OptClientSubnet | .... ;
> 
> export interface OptAnswer extends GenericAnswer<"OPT"> {
>   options: OptPackets[];
> }
> ```

I've added the `PacketOpt` type to allow users to extend the typing.

**Comment by elibarzilay** [comment]
@SE2Dev / @KapitanOczywisty -- is this sorted out now?

**Comment by SE2Dev** [comment]
@elibarzilay I made the requested changes, and am currently waiting for them to be reviewed.

**Comment by KapitanOczywisty** [comment]
@SE2Dev My last note still holds, making "universal" `options` type will be hard to straighten out once implemented. `options` have to be union of types.

**Comment by SE2Dev** [comment]
@KapitanOczywisty I finally realized what you were referring to and have changed `PacketOpt` so that it functions as a discriminated union.

**Comment by amcasey** [comment]
Wow, this has been going for a while.  @KapitanOczywisty it sounds like your concerns have been addressed - can you please confirm?

**Comment by KapitanOczywisty** [comment]
I've been a bit busy lately.. PR looks good now.

https://github.com/mafintosh/dns-packet/blob/8e6d91c078c9175708bcf13c071d6ffae963a635/index.js#L679-L684
If `data` is provided, the rest of properties are ignored, so this could be improved in the future.

**Review by KapitanOczywisty — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by SE2Dev** [comment]
Ready to merge

**Pull request merged**
