### PR TITLE
Remove gitlab typings (node-gitlab)

### PR DESCRIPTION
**Pull request by qmnl**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] ~~Add or edit tests to reflect the change. (Run with `npm test`.)~~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] ~~Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).~~

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by simonmeusel** [comment]
See https://github.com/jdalrymple/node-gitlab/issues/207 and https://github.com/jdalrymple/node-gitlab/pull/185

**Comment by Arylo** [comment]
it is ok to these changes, but it would be better if `asOfVersion` is changed to `3.0.0`.

**Comment by simonmeusel** [comment]
Why `3.0.0`? The previous version was I think `1.8.0`, and this is a major change, so `2.0.0`, right?

**Comment by Arylo** [comment]
Because the `2.0.0+` does not exist.

**Comment by simonmeusel** [comment]
You mean it should be in sync with the `gitlab` node module. Then it should be something with major version 4. I don't know how long the typings were still intact.

**Comment by armanio123** [comment]
@arylo @simonmeusel Is there an agreement in the version number? Is it ok to merge this PR?

**Comment by simonmeusel** [comment]
@armanio123 I don't know what the DefinitelyTyped conventions are with the version numbers, but personally I don't care about the version number. @Arylo Do you have anything against `2.0.0`, and could you explain what you mean with 

> Because the 2.0.0+ does not exist.

**Comment by simonmeusel** [comment]
The typings are outdated as of `2.0.0` and the current version is `4.2.1`. So I think we should go with `2.0.0`

**Pull request merged**
