### PR TITLE
fix[react-native]: fix declaration for Blob and add test

### PR DESCRIPTION
**Pull request by maltoze**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/facebook/react-native/blob/master/Libraries/Blob/Blob.js](https://github.com/facebook/react-native/blob/master/Libraries/Blob/Blob.js)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50299#discussion_r558226675

### CODE REVIEW

**Comment by maltoze** [comment]
> Error: ../styled-components/index.d.ts(259,7): error TS2589: Type instantiation is excessively deep and possibly infinite.


It seems to be a typescript bug. https://github.com/microsoft/TypeScript/issues/34933

**Comment by alloy** [comment]
@RyanCavanaugh @sandersn @orta I’m going to merge this PR, as it seems unrelated to the CI issue https://github.com/microsoft/TypeScript/issues/34933. However, it also seems this will keep coming up with future RN PRs, so what’s the correct path forward here?

```
Error in styled-components-react-native
331
Error: Errors in typescript@4.2 for external dependencies:
332
Error: ../styled-components/index.d.ts(259,7): error TS2589: Type instantiation is excessively deep and possibly infinite.
```

**Comment by alloy** [comment]
> However, it also seems this will keep coming up with future RN PRs, so what’s the correct path forward here?

Case in point: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50668

**Comment by sandersn** [comment]
@alloy The right thing to do is ignore styled-components failures for now. We're tracking that at microsoft/typescript#42320, to be fixed during the 4.2 beta.

**Comment by alloy** [comment]
Got it, thanks. Will merge this as-is then 👍 

As for the styled-components changes, iirc @orta has recently been in touch with those people, so perhaps he can reach out to them to get this resolved?

**Pull request merged**
