### PR TITLE
update(imagemin-upng): v3 - ESM migration

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Migration to EMS modules:
https://github.com/fisker/imagemin-upng/pull/1573

(minor: naming from native package code)

Thanks!

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by nicolas377** [comment]
I'll review this after CI finishes up

**Review by nicolas377 — APPROVED** [review]
All good over here!

**Comment by peterblazejewicz** [comment]
@nicolas377 thank you!

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
