### PR TITLE
fix : distribute key and restprops in react-table component's props

### PR DESCRIPTION
**Pull request by Doooooring**
Hi, I'm using react-table type. i'm so thanked for your project, but I think there needs modification of key props.
In react, the components made by "map" method are supposed to have "key" prop. In react table, "...get{}props" assigns key prop automatically, so actually there's no problem. BUT typescript cannot recognize the key prop so we need to expose the key prop deliberately.

For example
[DefinitelyTyped/types/react-table/react-table-tests.tsx](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/26c83a7d0c15db9cfdb872a3bc194d51cd348628/types/react-table/react-table-tests.tsx#L481-L504)

Here, "<td {...cell.getCellProps()}>" has key prop because {...cell.getCellProps()} give independent key. But typescript cannot recognize it. So it should be modified like below.

 {row.cells.map((cell: Cell<Data>) => { const {key, ...restCellProps} = cell.getCellProps() return ( <td key = {key} {...restCellProps}> {cell.isGrouped ? ( <> <span {...row.getToggleRowExpandedProps()}> {row.isExpanded ? '👇' : '👉'} </span>{' '} {cell.render('Cell', { editable: false })} ({row.subRows.length}) </> ) : cell.isAggregated ? ( // If the cell is aggregated, use the Aggregated // renderer for cell cell.render('Aggregated') ) : cell.isPlaceholder ? null : ( // For cells with repeated values, render null // Otherwise, just render the regular cell cell.render('Cell', { editable: true }) )} </td>

Please fill in this template.

- [ yes ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ yes ] Test the change in your own code. (Compile and run.)
- [ yes] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [yes ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ yes] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ yes] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [ yes] Provide a URL to documentation or source code which provides context for the suggested changes: <https://ko.reactjs.org/tutorial/tutorial.html#picking-a-key>
- [ yes ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by ggascoigne** [comment]
FYI I actually like this PR, and it avoids some lint warnings that I've had to handle (like this) in my own code.  Needs a couple of formatting issues to be fixed so it can be merged.  If @Doooooring can fix them then it'll be quickest, if not I'll add them to my list of stuff to do :)

**Comment by Doooooring** [comment]
@ggascoigne Thank you for your feedback. It was my first time doing PR with open source, so I was not good at matching the form. I'll try to put in PR as soon as possible.

**Review by ggascoigne — APPROVED** [review]

**Comment by ggascoigne** [comment]
Sorry, I missed that this PR was building clean.

**Comment by ggascoigne** [comment]
Ready to merge

**Pull request merged**
