### PR TITLE
add console and Console type to weixin-app

### PR DESCRIPTION
**Pull request by jimexist**
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by AlexStacker** [comment]
Does the console need to be added here?

**Comment by taoqf** [comment]
I doubt it, too.

**Review by AlexStacker — CHANGES_REQUESTED** [review]
I do not think that needs to be introduced to the console here.

**Comment by Jimexist** [comment]
let me close this instead. i guess your opinion is to install `@types/node`

**Pull request closed without merging**
