### PR TITLE
[node] Add additional REPLServer members

### PR DESCRIPTION
**Pull request by rbuckton**
This PR includes the following changes:
- **Adds additional members to `repl.REPLServer` instances.** These are properties that the underlying implementation copies from the `repl.ReplOptions` object and are useful for REPL implementers.
- **Changes `repl.REPLServer` to a `class` with a private constructor.** This better represents the underlying implementation, allows for `value instanceof repl.REPLServer` checks, and allows possible `repl.REPLServer.prototype` patching if necessary.
- **Adds missing events to `repl.REPLServer`.** The previous definition was missing events inherited from `readline.Interface`.
- **Adds the `REPL_MODE_SLOPPY` and `REPL_MODE_STRICT` exports.** These are the possible values for `repl.ReplOptions.replMode`. Ideally they would be typed as `unique symbol`, however that is not compatible with TypeScript 2.0. This will be resolved once #30477 has been merged.
- **Renames `readline.ReadLine` to `readline.Interface` and changes it to be a `class`.** This better represents the underlying implementation, allows for `value instanceof readline.Interface` checks, and allows possible `readline.Interface.prototype` patching if necessary.
- **Adds `readline.ReadLine` as a type alias to `readline.Interface`.** This type forwarding provides backwards compatibility for existing implementers.
- **Adds additional members to `readline.Interface` instances.** These are properties that the underlying implementation copies from the `readline.ReadLineOptions` object and are useful for REPL implementers.
- **Adds additional documentation.**

Please fill in this template:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v10.x/docs/api/repl.html
- [ ] ~Increase the version number in the header if appropriate.~
- [ ] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
Looks good I guess.

**Comment by Flarna** [comment]
@rbuckton Is there a performance issue with typescript/tslint since a few days as CI tends to timeout now? Or has the number of dependents increased that far that test can't pass anymore?

**Comment by rbuckton** [comment]
@Flarna: I'm unaware of any issue at the moment. This is the first time I've seen this timeout.
@weswigham, @DanielRosenwasser, @andy-ms: Are you aware of any new issues with tslint performance on DT?

**Comment by Flarna** [comment]
another case (happened more then once there):  #30218

**Comment by weswigham** [comment]
@rbuckton last time I saw a timeout in DT like this was when we bulk updated almost every package to use `esModuleInterop`. Could try rerunning it, but it might just be that there's too many dependencies to test.

**Comment by rbuckton** [comment]
There are a significant number of packages that are tested due to a very tenuous dependency on node. For example `react-dom/server/index.d.ts` has a dependency on `NodeJS.ReadableStream`, and `react` has a dependency on `react-dom` in its tests, so _everything_ that depends on `react` depends on `node`. For this case, we could just switch `react-dom/server/index.d.ts` to a forward declaration for `NodeJS.ReadableStream`, rather than bringing in all of `node`.

**Comment by rbuckton** [comment]
All tests run locally, and the timeout issue is outside of the scope of this PR.

**Pull request merged**
