### PR TITLE
added an inline React reference for typings

### PR DESCRIPTION
**Pull request by nirsmadar**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by cdroulers** [comment]
I'm not sure what the goal of this change is?

**Comment by nirsmadar** [comment]
@cdroulers Installing this using typings:
typings install --save --global dt~react-intl
results in a broken d file due to
"Cannot find name React"

Installing it via npm @types succeeds because react is an npm dependency.
Please note that other d files that are dependent on react all have a line of:
import * as React from 'react'; to fix this issue, but react-intl d file doesn't.

**Comment by cdroulers** [comment]
:+1:

**Comment by alechill** [comment]
@cdroulers @horiuchi This has failed the Travis build but has been released and therefore also broken our production build. It looks like the above has reintroduced something that was purposefully removed in the previous commits

As the version has not been bumped we cannot lock to the previously working @types/react-intl@2.1.1 version either

Would it be possible to revert this breaking change until it is tested further?

**Comment by alechill** [comment]
By the way, we have been using `@types` to install both `react` and `react-intl` and not seeing the aforementioned working... ```Installing it via npm @types succeeds because react is an npm dependency.```

**Comment by nirsmadar** [comment]
@alechill Sorry about that- I think that the real solution is to add a 
`import * as React from 'react';`
line to the d file. Waiting for authors to comment.

**Pull request merged**
