### PR TITLE
[redlock] mark redlock classes as such so that we can do checks against them

### PR DESCRIPTION
**Pull request by baronfel**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L40
- [N/A] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by mhegazy** [comment]
@baronfel can you please address the ci test failure. this is not caused by your change, but should be a simple fix.

**Comment by baronfel** [comment]
ok, I believe I've done that as well as un-commenting and fixing the `using` disposal test.

**Comment by BendingBender** [comment]
Hi. I've submitted the PR #18648 already a couple of days ago that lifts the definitions to v3 and also fixes this test. It was already singed-off by the author of the original typings. Not sure how we should deal with this PR without getting merge conflicts at the site of the disposal test.

**Comment by baronfel** [comment]
oh, sorry! I didn't even think to check. Yeah, your PR is much better than this one, I'll close it in favor of yours.

**Comment by BendingBender** [comment]
I think there is value in what you've done. I didn't bother to convert the Lock interface to a class. So there is definitely value in this PR.

**Comment by baronfel** [comment]
I sent a pr to your branch @BendingBender that has the useful part of this PR, so that it can be included in your larger PR.

**Pull request closed without merging**
