### PR TITLE
Updated @feathersjs/socket-commons and @feathersjs/feathers

### PR DESCRIPTION
**Pull request by deskoh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://docs.feathersjs.com/api/channels.html#publishing
https://docs.feathersjs.com/api/channels.html#appchannels
https://docs.feathersjs.com/api/channels.html#appchannels

Related Source Code:
https://github.com/feathersjs/transport-commons/blob/da6ed3c92553086fc9a7af6116858db266fd3202/lib/channels/mixins.js#L61
https://github.com/feathersjs/transport-commons/blob/da6ed3c92553086fc9a7af6116858db266fd3202/lib/channels/index.js#L26
https://github.com/feathersjs/transport-commons/blob/da6ed3c92553086fc9a7af6116858db266fd3202/lib/channels/index.js#L14
https://github.com/feathersjs/transport-commons/blob/da6ed3c92553086fc9a7af6116858db266fd3202/lib/channels/mixins.js#L29

> Note: Current published branch has been archived and to TypeScript [here].(https://github.com/feathersjs/feathers/blob/9dd671301ae0463968ade0f6eb0c82356adcc89d/packages/transport-commons/src/channels/index.ts)

Added support to [Calling the hook-less service methods](https://crow.docs.feathersjs.com/migrating.html#hook-less-service-methods) of the database adapters.

### CODE REVIEW

**Review by jordanbtucker — CHANGES_REQUESTED** [review]
Thanks for the PR. Have these changes actually landed in a published release of Feathers? I don't think we should be updating the type definitions here until the relevant changes have been published.

Also, type definitions are being added to the monorepo directly and will likely be included in the next release, so any changes made here in DefinitelyTyped should just be fixes. I see that you've submitted PR's there, which is awesome!

**Comment by deskoh** [comment]
Regarding the `socket-commons` code changes, they have been published as provided in the links to the official documentation above. The issue is that the typescript port in https://github.com/feathersjs/feathers/pull/1275 has not been published yet. Hence existing typings is missing. So this PR could be an interim fix until the version with version with TypeScript port is published. The author has not gotten back the estimated timeline (v4 I believe). See https://github.com/feathersjs/feathers/issues/1278#issuecomment-482389990. P.S. I’m currently using the official published version and hence discovered the missing typings.

**Comment by jordanbtucker** [comment]
Thanks for the info. The `socket-commons` changes look good, although I'm technically not a maintainer for that repo in DT.

I'm still iffy on the changes to `feathers` as explained in https://github.com/feathersjs/feathers/pull/1288#issuecomment-484707146.

How about we keep the changes to `socket-commons` in this PR, but remove the changes to `feathers`, and update the title to something more descriptive. You can open a new PR for the changes to `feathers`, but I'd like to discuss that more in https://github.com/feathersjs/feathers/pull/1288 first.

Of course, I'm not a maintainer of Feathers, so @daffl can chime in and override me, but I'm actively updating the type definitions for Feathers so I'm trying to keep on top of any changes.

**Comment by deskoh** [comment]
Yup agree. Will update the PR in the coming weekend.

**Pull request closed without merging**
