### PR TITLE
Nvd3 Type definitions

### LINKED ISSUE #1422: Add support to nvd3
To those of us that can't use d3!

http://nvd3.org/ :)

### PR DESCRIPTION
**Pull request by PjMitchell**
Attempt at type definitions for NVD3 which hopefully resolves #1422
A lot of comments and specs taken from:
http://nvd3-community.github.io/nvd3/examples/documentation.html
Tests taken from their examples with some adjustments where external libraries could not be found

### CODE REVIEW

**Comment by vvakame** [comment]
Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/nvd3
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)?
* [ ] pass the Travis CI test?

**Comment by PjMitchell** [comment]
Is there any issue with the test files?

**Comment by horiuchi** [comment]
@PjMitchell Thanks mate!

**Comment by asdiallo** [comment]
Thanks

**Pull request merged**
