### PR TITLE
dwt: Provides its own types

### PR DESCRIPTION
**Pull request by ghost**
This will deprecate `@types/dwt` in favor of just `dwt`. CC @yushulx, @jbh

### CODE REVIEW

**Comment by jbh** [comment]
I'm trying to find where `dwt` provides its own types, and I'm not seeing it. Can you please provide evidence of this? I'm not able to test it this week as I'm not at my normal work location.

**Comment by andy-ms** [comment]
If you `npm install dwt` you should be able to add `/// <reference types="dwt" />` to the top of any file, which will reference the types in `node_modules/dwt/dist/index.d.ts`.

**Comment by yushulx** [comment]
Hi @andy-ms. I'm sorry for confusing you. ```/// <reference types="dwt" />``` does not reference ```node_modules/dwt/dist/index.d.ts```. It works with ```@types/dwt```. I will remove ```node_modules/dwt/dist/index.d.ts``` in next **dwt** version.

**Comment by andy-ms** [comment]
I tested in a project without `@types/dwt` installed. `tsc --listFiles` shows me that `node_modules/dwt/dist/index.d.ts` is being included. I don't see why you would want to remove that, because packages bundling their own types is a good thing.

**Comment by yushulx** [comment]
@andy-ms the reason is I added ```"types": "dist/index.d.ts"``` to **package.json**. Your opinion is definitely right. However, the latest **index.d.ts** file always keeps updated in **DefinitelyType** repo. I have to thank @jbh who has contributed a lot to the description file. This is why I consider removing ```dist/index.d.ts``` which is out of date.

**Comment by andy-ms** [comment]
Is there some reason @jbh can't contribute to the project directly? If types are kept separately from the package it's harder to keep them up-to-date with new changes to the package, and requires users to perform more installs. If you continue to bundle types, you also won't have to wait for a DefinitelyTyped maintainer to merge any pull requests.

**Comment by yushulx** [comment]
@andy-ms have you downloaded the [dwt installer](https://www.dynamsoft.com/Downloads/WebTWAIN_Download.aspx)? The ```index.d.ts``` file was originally ported from ```Dynamic Web TWAIN SDK <version> Trial\Resources\dynamsoft.webtwain.intellisense.js``` which defines some general properties and methods of **Dynamic Web TWAIN** but not includes all. To use **dwt** correctly, you need to read the [API reference](https://developer.dynamsoft.com/dwt/api-reference). If the APIs you used are not included in the description file, you can update it and send a pull request as @jbh did. Please understand the ```index.d.ts``` file is not officially released. I hope **dwt** developers can contribute to the file and make it better. Thanks.

**Comment by jbh** [comment]
Sorry for my absence in the conversation.

As @yushulx is saying, the index.d.ts was not officially released. I couldn't find where to contribute to it, and I don't think it's in the `dwt` repository. If there's a way to contribute to it through github, I'd be happy to.

The only one I could find to contribute to was `@types/dwt`. I think @yushulx and myself are on board with the idea that it should be included in `dwt`, but I don't think it's properly setup that way yet.

**Comment by andy-ms** [comment]
OK, I'll add this package to a list of excludes for now. Please make a pull request like this one once it's officially released.

**Pull request closed without merging**
