### PR TITLE
[node] Test that imported and global `console` are same

### PR DESCRIPTION
**Pull request by TonyPythoneer**
Based on #10980. It needs to enhances test for `console`.

The Purpose of Tests:
- `console` module is able to be imported
- The imported and global `console` are same.

### CODE REVIEW

**Comment by hriss95** [comment]
You should import using `import c = require("console")` . You are importing an object and not a namespace.

**Comment by zhengbli** [comment]
Thank you for your contribution.

Can you please fix the failing Travis CI tests and update the PR?

**Comment by TonyPythoneer** [comment]
I had read Travis CI . I know what happened. :smile: 
The node v4 needs to also declare a module for `console`.

**Comment by TonyPythoneer** [comment]
Ok, it passes.

**Pull request merged**
