### PR TITLE
c3js defintions

### PR DESCRIPTION
**Pull request by mcliment**
A definition file for c3js (http://c3js.org/) with documentation and tests based on the examples found on the official ones.
It's my first public definition and the library surface is pretty large, I hope that people will find it useful!

### CODE REVIEW

**Comment by mcliment** [comment]
This should close #5084

**Comment by vvakame** [comment]
*c3/c3.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/c3
  * http://bower.io/search/?q=c3
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (c3/c3-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
thanks mate!

**Comment by mcliment** [comment]
:smiley_cat:

**Pull request merged**
