### PR TITLE
Typings for React-Paginate (latest version 4.2.0)

### PR DESCRIPTION
**Pull request by pegel03**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@pegel03 can you fix the merge issue? Probably just need to merge master back in.

**Comment by paulvanbrenk** [comment]
@pegel03 Can you remove the `v` from the version in the header, it looks like that trips up the CI server now. :(

**Comment by pegel03** [comment]
@paulvanbrenk Tried to quickly solve conflicts in the web-editor, not a good idea..
After that I was still not happy with the Function type in the test. Solved it with a colleague who does know some TypeScript:)
Thanks for your patience, Peter (Netherlands)

**Comment by paulvanbrenk** [comment]
thanks!

**Pull request merged**
