### PR TITLE
feat: update testing-library__react

### PR DESCRIPTION
**Pull request by ifiokjr**
Add a pure file.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by weyert** [comment]
Hmm, pure is the version without the auto cleanup right?

**Comment by ifiokjr** [comment]
> Hmm, pure is the version without the auto cleanup right?

@weyert, yeah it's currently not typed

**Comment by weyert** [comment]
@johnnyreilly Small update to TestingLibrary for our enjoyment 💃

**Comment by johnnyreilly** [comment]
I think you should be able to mark these as approved and have this merged by the TypeScript not. Give it a try?

**Comment by weyert** [comment]
It's saying: "This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests."

**Comment by johnnyreilly** [comment]
Are you able to submit a review?

**Comment by johnnyreilly** [comment]
My understanding is that as someone marked as a contributor you should be able to submit an "approve" review - the TypeScript bot should track that and automatically merge it. Can you see any way to submit a review with an approval button? Probably only works on desktop view

**Comment by johnnyreilly** [comment]
Here's an example PR that demonstrates this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37715

**Comment by johnnyreilly** [comment]
Hmmm... There might be an error with the Definitely Typed owner infrastructure. @sandersn I think that CODEOWNERS is no longer being updated.  If you look at the `CODEOWNERS` file here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/518700405e6f24d00288c4bb3bf56d2d4b8dae97/.github/CODEOWNERS#L5557

You'll see it doesn't have the expected owners for `testing-library__react` listed.  Do you know what might be at issue?  Is this perhaps related to the cache invalidation issue?

**Comment by sandersn** [comment]
I doubt that it's the cache invalidation issue, since that's with travis and codeowners is updated from azure pipelines. I'll go look at the devops page.

**Comment by sandersn** [comment]
Looks like devops ate my scheduled task. Didn't update the history or anything, as far as I can tell. I'll re-add it.

**Comment by johnnyreilly** [comment]
Thanks! Could you share a link to the DevOps bit you're talking about? I didn't know where to look...

**Comment by sandersn** [comment]
https://dev.azure.com/definitelytyped/DefinitelyTyped/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1&view=Tab_Triggers -- I only know how to change it through the UI, although the change history for the task shows the YAML diff.

**Comment by johnnyreilly** [comment]
I don't seem to have access; I'm getting this:

> 401 - Uh oh, you do not have access.
> Your account, johnny_reilly@hotmail.com is not authorized to view this page. Make sure the URL is correct and your account has access. View a list of your organizations here. You may request access by contacting the admin.
19/08/2019 19:42:40 (UTC)
eb307807-d075-4541-bb56-4597b1b553f5

Are you able to permission me?

**Review by alexkrolick — APPROVED** [review]

**Comment by weyert** [comment]
Probably too late to approve, right?

**Comment by sandersn** [comment]
@johnnyreilly devops seems completely unaware of github, github teams, and github authentication. For now I manually sent you an invitation. Hopefully the situation changes and we can just point to the existing github team.

**Comment by johnnyreilly** [comment]
Thanks @sandersn - I've accepted but it doesn't seem to have quite worked. I'll send you an email with details

**Pull request merged**
