### PR TITLE
Make awesomplete definitions a module

### PR DESCRIPTION
**Pull request by tbekolay**
This enables the use of import statements like

  import * as Awesomplete from "awesomplete";

It uses the hack (?) describedin https://github.com/Microsoft/TypeScript/issues/5073.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://leaverou.github.io/awesomplete/#extensibility>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by tbekolay** [comment]
I didn't realize that `phonon` uses `awesomplete`; I modified it so that its usage of `awesomplete` would be correct, but having done that the `phonon` tests still fail. I've not used `phonon` so I wouldn't be comfortable updating those definitions.

**Comment by mhegazy** [comment]
Thank you for your contribution. 

We are unable to process this PR with the failing Travis CI tests; please either update it or close it.

**Comment by tbekolay** [comment]
I wasn't aware of the `<reference types>` directive; I've modified this PR to use that in `phonon` and the TravisCI build now passes.

**Comment by mhegazy** [comment]
No response from other authors for over a week. Merging.

**Pull request merged**
