### PR TITLE
[d3-path] Add pathRound function definition

### PR DESCRIPTION
**Pull request by gmanrique-cb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [pathRound](https://d3js.org/d3-path#pathRound)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by Methuselah96 — APPROVED** [review]
Thanks, sorry for the delayed review!

**Review by Methuselah96 — CHANGES_REQUESTED** [review]
Sorry, one thing I missed, can you update the package version in `package.json` to be `3.1.9999` and update the version at the top of `d3-path/index.d.ts` to `3.1.0`?

**Comment by gmanrique-cb** [comment]
> Sorry, one thing I missed, can you update the package version in `package.json` to be `3.1.9999` and update the version at the top of `d3-path/index.d.ts` to `3.1.0`?

Yup, done! Thanks for the review!

**Review by Methuselah96 — APPROVED** [review]
Thanks!

**Comment by gmanrique-cb** [comment]
Ready to merge

**Pull request merged**
