### PR TITLE
Rename React's SFC to 'FunctionalComponent'

### PR DESCRIPTION
**Pull request by rhysforyou**
**Note:** I'm reopening this as a new PR since #30188 was automatically closed while waiting for fixes to other React tests to merge.

---

This PR renames `React.SFC` and `React.StatelessComponent` to `React.FunctionComponent`, while introducing deprecated aliases for the old names. The motivation for this is twofold: firstly the addition of hooks means function components can have state, and secondly the term "stateless component" can equally apply to class components which don't use any state, causing some confusion.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
    - The hooks docs at https://reactjs.org/docs/hooks-state.html#hooks-and-function-components
      
      > You might have previously known these as “stateless components”. We’re now introducing the ability to use React state from these, so we prefer the name “function components”.

    - Dan Abramov's tweet on the subject https://twitter.com/dan_abramov/status/1057625147216220162

      screen shot 2018-11-01 at 12 03 27 pm
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by FredyC** [comment]
@rhysforyou The PR ##30331 fixing all React tests failing has been merged so I recommend rebasing and it should be much easier to make tests passing here.

Also can you please add/change alias SFC to FC? I don't really like such a long name as `FunctionComponent` everywhere.

**Comment by rhysforyou** [comment]
I've rebased and added `React.FC<P>` as an alias to `React.FunctionComponent<P>`, let's see if this passes.

**Comment by rhysforyou** [comment]
All fixed up 😄

**Comment by johnnyreilly** [comment]
Looks good to me. @kovensky - does this look good to you?

**Comment by Kovensky** [comment]
Looks good to me (can't use review UI as I'm on phone atm).

I see you also accidentally(?) ran Prettier on the code ;)

**Comment by rhysforyou** [comment]
Oops, I’ll fix that up haha.

**Comment by johnnyreilly** [comment]
Thanks

**Comment by amanmahajan7** [comment]
Is there a reason for releasing this change in a patch version? It is a breaking change and should probably have been released in a major version.

**Comment by FredyC** [comment]
@amanmahajan7 What's breaking change? Old stuff is just deprecated and you have plenty of time for updating.

**Comment by amanmahajan7** [comment]
Sorry I wasn't clear. May be it is a specific case and does not need a major bump but here is an example.

If the tsc compiler is generating definition files then after the upgrade the compiler generates files with `React.FunctionComponent` instead of `React.SFC` and if the consumer package is still using an older version of `@types/react` then it won't be able to consume those generated files

**Comment by johnnyreilly** [comment]
I'm afraid all type definition changes are potentially breaking - there is no semver. Details here:

https://blog.johnnyreilly.com/2018/09/ivan-drago-and-definitely-typed.html

**Comment by johnnyreilly** [comment]
> @johnnyreilly Nice article, haven't seen that one before.

I can't believe that. I'm now thinking of writing a chrome extension to write GitHub comments linking back to it, do often does the breaking changes question come up on DT 😁

**Comment by Johnz86** [comment]
Renaming SFC to FC or to FunctionalComponent does not add any functional value. 
From the authors perspective it is just more easy to understand. 
This is breaking change for many people that are already using SFC.
This complicates migrations to future versions.

Please avoid deprecating stuff just for renaming reasons.
In my opinion both SFC and FC should be retained.

**Comment by FredyC** [comment]
@Johnz86 I believe it's a matter of consistency. It would be easy to confuse newcomer who would see SFC all over the place, starts asking what does that mean and "why is it stateless, there useState"... Not really worth going there.

It's a matter of a simple _find & replace_. Even for the huge codebase, it's a matter of a couple of minutes do migrate this.

**Comment by aamitsingh** [comment]
This makes it more logical and moves an inch towards OOPS...

**Pull request merged**
