### PR TITLE
added missing gridlines in y Axes

### PR DESCRIPTION
**Pull request by dolanmiu**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by dolanmiu** [comment]
Here is link to the documentation. In Version 2.0+ both x and y have gridLines

http://www.chartjs.org/docs/#scales

**Comment by aozgaa** [comment]
Can you refactor so both axes  extend a common `ChartAxis` interface, and then tack on members unique to the `x` and `y` axis, respectively? Or if no new members appear, just `declare type ChartXAxe = ChartAxis`?

**Comment by jramsay** [comment]
@dolanmiu:  Thanks for your contribution. This PR has unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you cannot address the CR feedback this week we'll be closing it.

**Comment by dolanmiu** [comment]
Sorry about the late response, been quite busy lately with work and personal, will get round to it over this week/weekend.

**Comment by dolanmiu** [comment]
Done, I refactored the 2 axes into a base class.

I then extend that base class to form the new X and Y axes.

**Comment by dolanmiu** [comment]
P.S. I also added position type checking with the new PositionType type.

**Pull request merged**
