### PR TITLE
fix(codemirror): fix selection update event types and others

### PR DESCRIPTION
**Pull request by fityocsaba96**
Some type fixes related to the selection change event and `Range` type, also fix parameter type for `replaceRange` function

Edit: made another type fix in the match highlighter addon

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/codemirror/CodeMirror/blob/master/src/model/selection_updates.js#L79 and https://github.com/codemirror/CodeMirror/blob/master/src/model/selection.js#L58 and https://github.com/codemirror/CodeMirror/blob/master/src/model/Doc.js#L116 and https://github.com/codemirror/CodeMirror/blob/master/src/model/changes.js#L273

### CODE REVIEW

**Review by koddsson — APPROVED** [review]
I don't have approve rights in this repo but for what it's worth, I stuck this change into my project that uses codemirror a lot and it didn't generate any errors and seems like a good change to me 👍🏻

**Review by koddsson — APPROVED** [review]
Still looks good to me!

**Review by koddsson — APPROVED** [review]

**Comment by fityocsaba96** [comment]
Now I have found a few more properties and function that were missing from the type definitions, so I made another commit

**Comment by fityocsaba96** [comment]
And update on this?

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## codemirror ([<kbd>unpkg</kbd>](https://unpkg.com/browse/codemirror@latest/))
was missing the following properties:
1. optionHandlers
1. inputStyles
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f15f9993e9199e57b10fc36cc5a6f99240b3d825
</p>

**Comment by fityocsaba96** [comment]
GitHub shows the Travis build as pending, but it completed hours ago. What to do in this case? 😃 I can't restart it

**Pull request merged**
