### PR TITLE
[react-native] Added Linking.openSettings()

### PR DESCRIPTION
**Pull request by danilobuerger**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/linking.html#opensettings
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Skn0tt** [comment]
I made the exact same PR this morning: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36953  - so I approve of the contents, but sadly it's a duplicate.

**Review by Skn0tt — APPROVED** [review]

**Comment by danilobuerger** [comment]
@Skn0tt Ah, I see. However, in your PR the return type is given as `Promise<void>` which does not match the flow typings:

https://github.com/facebook/react-native/blob/master/Libraries/Linking/Linking.js#L76

And indeed, it does resolve to non-void results:

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L165

**Comment by Skn0tt** [comment]
I see your point. However, the Flow typings don't seem to be very strict about that, since the referenced `NativeLinking.openSettings()` [is annotated with `Promise<void>`](https://github.com/facebook/react-native/blob/a43615a38a8594217602e2dc91640e8902d288a2/Libraries/Linking/NativeLinking.js#L22) as its return type.

Using `Promise<any>` makes people wonder about what `any` means in this context. This is why I think that in this case, `Promise<void>` is the type to use. The real (implementation) type (which is `Promise<true>`) does not offer any benefits, but will confuse users; it's the same with `Promise<void>`.

**Comment by andrewbranch** [comment]
If the resolved value isn’t supposed to be looked at, `void` is preferable. From the original Java it looks like there’s no _reason_ to inspect the value, since it’s currently always `true`. Making the TypeScript typings say `void` would prevent people from (for some odd reason) checking the resolved value for truthiness, which would leave more room for react-native to change the underlying implementation without breaking people.

All other things equal, I’d lean toward closing this one and merging @Skn0tt’s version, but will defer to the experts here. What do you all think?

**Comment by alloy** [comment]
Looks like we have a verdict 👍 

Thanks, though, @danilobuerger! 🙌

**Pull request closed without merging**
