### PR TITLE
[chec/commerce.js] Remove checkout.protect() method from definitions

### PR DESCRIPTION
**Pull request by robbieaverill**
This method is removed upstream, see https://github.com/chec/commerce.js/pull/190

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by PaitoAnderson — APPROVED** [review]
LGTM

**Review by andrewbranch — CHANGES_REQUESTED** [review]
The upstream PR says it’s now deprecated and will be removed in v3. These typings are still for v2.7+. The method should stay until you’re ready to bump the version in the index.d.ts header comment to 3.0. You can mark it `/** @deprecated */` in the meantime, though.

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by robbieaverill** [comment]
Thank _you_!

**Comment by robbieaverill** [comment]
Ready to merge

**Pull request merged**
