### PR TITLE
Created typings for FHIR DSTU2 v0.5.0

### PR DESCRIPTION
**Pull request by meirgottlieb**
Created typings for FHIR DSTU2 v0.5.0. See http://hl7.org/fhir/2015May/index.html for details.

### CODE REVIEW

**Comment by vvakame** [comment]
*fhir/fhir.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/fhir
  * http://bower.io/search/?q=fhir
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (fhir/fhir-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@meirgottlieb thanks mate!

**Comment by DanielRosenwasser** [comment]
@meirgottlieb, were your tests automatically generated, or did you write them all yourself?

**Comment by meirgottlieb** [comment]
They were generated. The FHIR spec comes with a large number of JSON
documents as examples. I generated the tests using the example documents.

Meir

**Comment by DanielRosenwasser** [comment]
@meirgottlieb as part of my work in https://github.com/Microsoft/TypeScript/issues/4081, I ran into some issues with this because the tests utilize use structural subtyping (e.g. implicitly taking the structure of a `MedicationPrescription` where a `Resource` is expected). We are experimenting with the idea of making excess object literal properties an error in TypeScript 1.6. For the most part it has found a lot of bugs in several codebases (which is great!) but it significantly breaks the FHIR tests. See https://github.com/Microsoft/TypeScript/issues/4234 for more details.

So perhaps we can figure something out - probably both with generating the tests and with generating the .d.ts itself (I've found other problems as a result of this - `resourceType` should be on the `Resource` type, not just `DomainResource`).

**Comment by meirgottlieb** [comment]
I can make any adjustments as needed. What do you suggest?

**Comment by DanielRosenwasser** [comment]
Hey @meirgottlieb, we can do one of two things:

1. Make every base type an explicit base type (i.e. `Resource` becomes `ResourceBase`) and then make `Resource` a union of all the base's subtypes (i.e. `type Resource = MedicationPrescription | /*...*/;`
2. Add an index signature for every type. This is easy but it permits excess properties.

Let me know your thoughts.

**Comment by meirgottlieb** [comment]
I'm going to go with option #1. I'll let you know when DefinitelyTyped is
updated.

**Comment by DanielRosenwasser** [comment]
Cool - when you're ready to test, rename `fhir-tests.disabled.ts` to `fhir-tests.ts` and try it out.

**Pull request merged**
