### PR TITLE
[gapi.client.drive] automatic update

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
  - [x] Test the change in your own code. (Compile and run.)
  - [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  - [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
  - [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
  - [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

  Select one of these and delete the others:

  If changing an existing definition:
  - [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Maxim-Mazurok/google-api-typings-generator#google-api-typings-generator
  - [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
  - [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
  - [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

  ----

  🤖 This pull request was automatically created by [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) which generates types from [Google API Discovery Service](https://developers.google.com/discovery). Types were linted and tested before submission.

  If there is an issue with this pull request, consider [submitting a new issue](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new).

  Note you can also [use these types](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279) from our [`types` branch](https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/types) which is updated hourly.

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
Changed types owner because @Bolisov wasn't active for years and we (me, @namoscato and @declanvong) are taking ownership of `gapi.client.*` namespace because we are maintaining type definitions generator fork now: https://github.com/Maxim-Mazurok/google-api-typings-generator

Other types under this namespace are already ours:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba533d7eea0941ab405ad5009c2963d0c58d1788/types/gapi.client.sheets/index.d.ts#L3
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba533d7eea0941ab405ad5009c2963d0c58d1788/types/gapi.client.tasks/index.d.ts#L3
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba533d7eea0941ab405ad5009c2963d0c58d1788/types/gapi.client.photoslibrary/index.d.ts#L3
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba533d7eea0941ab405ad5009c2963d0c58d1788/types/gapi.client.classroom/index.d.ts#L3
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ca73c4419caa5999dd3c0c0016c469db177bd3e8/types/gapi.client/index.d.ts#L3

**Comment by Maxim-Mazurok** [comment]
Sorry for force-pushes, I already fixed that: https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/155

**Comment by Maxim-Mazurok** [comment]
Regarding perf, it's probably CI glitch, as nothing changed compared to the previous CI run, so perf should be about the same.

**Comment by Maxim-Mazurok** [comment]
> @Maxim-Mazurok Thank you for submitting this PR!
> 
> ## Code Reviews
> There aren't any other owners of this package, so a DT maintainer will review it.
> 
> ## Status
> * white_check_mark No merge conflicts
> * x Continuous integration tests have passed
> * x Only a DT maintainer can merge changes [without tests](https://github.com/DefinitelyTyped/DefinitelyTyped#editing-tests-on-an-existing-package)
> 
> Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.
> 
> Diagnostic Information: What the bot saw about this PR

The link says that it passed

**Comment by Maxim-Mazurok** [comment]
> @Maxim-Mazurok Thank you for submitting this PR!
> 
> ## Code Reviews
> There aren't any other owners of this package, so a DT maintainer will review it.
> 
> ## Status
> * white_check_mark No merge conflicts
> * white_check_mark Continuous integration tests have passed
> * x Only a DT maintainer can merge changes [without tests](https://github.com/DefinitelyTyped/DefinitelyTyped#editing-tests-on-an-existing-package)
> 
> Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.
> 
> Diagnostic Information: What the bot saw about this PR

Tests are included, actually

**Review by leandro888 — APPROVED** [review]

**Review by amcasey — APPROVED** [review]
Just saw this - sorry the bot was giving you a hard time.  It looks like a ton of good work.  Thanks!

**Pull request merged**
