### PR TITLE
Add object parsing overload to moment setter

### PR DESCRIPTION
**Pull request by optical**
moment.set was missing the object parsing overload which was added in 2.9. Additionally there were no tests for set. Have copied the examples from moment docs.

See http://momentjs.com/docs/#/get-set/set/

### CODE REVIEW

**Comment by horiuchi** [comment]
@optical Thank you for your contribution.
But this `set` method is merged by #6268.
I think this test case is useful, please `merge` or `rebase` master.

**Comment by optical** [comment]
@horiuchi Merged

**Comment by vvakame** [comment]
thanks mate!

**Comment by horiuchi** [comment]
@optical Thanks mate!

**Pull request merged**
