### PR TITLE
Added playsInline property as introduced in React 15.3.2

### PR DESCRIPTION
**Pull request by schickling**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
Test as well please?

**Comment by schickling** [comment]
As far as I can see there are no other tests for HTML properties yet. This is related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9048.

**Comment by johnnyreilly** [comment]
> As far as I can see there are no other tests for HTML properties yet. 

That's not a good thing - we want tests to ensure we don't break things in the future.

**Comment by schickling** [comment]
I agree. Seems like the entire React type definitions are fairly outdated or haven't seen too much love in a while.

I'd really appreciate if someone would take a go at proper React 15 type defs.

**Comment by johnnyreilly** [comment]
> I'd really appreciate if someone would take a go at proper React 15 type defs.

Aren't you someone? :wink:

**Comment by schickling** [comment]
I wish I had the time to properly look into everything required and do it myself but unfortunately I don't have the time right now (that's why I went for the minimal PR) 😶

**Comment by johnnyreilly** [comment]
I understand - in a similar boat

**Comment by johnnyreilly** [comment]
Have merged as a super minimal PR - generally we would prefer tests with a PR though; particularly if changes are significant

**Comment by schickling** [comment]
Thanks a lot! Maybe I'll find some time over the holidays to work on some proper React 15 type definitions.

When do you expect the definitions to be publishes on npm via `@types`?

**Comment by johnnyreilly** [comment]
> Thanks a lot! Maybe I'll find some time over the holidays to work on some proper React 15 type definitions.

:Smile:

> When do you expect the definitions to be publishes on npm via @types?

Not sure - I forget.  https://github.com/Microsoft/types-publisher

**Comment by schickling** [comment]
So if I read correctly as soon as it's merged to the `types-2.0` branch it should be published automatically. Could you trigger that somehow?

**Comment by schickling** [comment]
Should I have done the PR for `types-2.0` instead @johnnyreilly?

**Pull request merged**
