### PR TITLE
`react-query` - Add `status` field to `QueryResult` and `MutationResult` interfaces

### PR DESCRIPTION
**Pull request by lukerollans**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [As per the many code samples and documentation, a `status` field will be present](https://github.com/tannerlinsley/react-query)

### CODE REVIEW

**Comment by lukaszfiszer** [comment]
@lukerollans the status field is just only one of dozens of changes in react-query v.1 (https://github.com/tannerlinsley/react-query/blob/master/CHANGELOG.md#100) I'm working on new version of type definitions that will include all of those changes. So for now I need to decline this PR

**Comment by lukerollans** [comment]
@lukaszfiszer I feel like `status` is probably one of the two most used fields, and merging this PR will help every react-query + typescript user right away, but no worries. Thanks for your work on the larger set of changes!

**Comment by purge** [comment]
@lukaszfiszer how far have you got with this - I have a local version which is slowly getting close to completion but i'd rather work against a fork of yours

**Comment by lukaszfiszer** [comment]
@lukerollans it's not only status. The way that query keys are defined and passed to queryFunction has only changes. The goal is to submit a fairly complete coverage for v1 types. Since another PR was opened, would you mind closing this one?

@purge I've created PR: #42830. Please take a look and test locally if possible.

**Pull request closed without merging**
