### PR TITLE
[react-calendar] Add support for date range change handler

### PR DESCRIPTION
**Pull request by pringelmann**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.jsx#L319

Additional context: 
The Calendar component supports an optional `selectRange` prop which allows users to select a date range. If that prop is set to true, then the `onChange` handler will receive an array of dates instead of a single date object. This is not supported by the current type definition.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
is this something like?:
```ts
onChange(value: Date | [Date] | [Date, Date]): void
```
(single, partial and range)

**Comment by Pringels** [comment]
> is this something like?:
> 
> ```ts
> onChange(value: Date | [Date] | [Date, Date]): void
> ```
> 
> (single, partial and range)

Yes, except in this case the callback type depends on whether the calendar is used as a range picker or not. (instead of the callback arguments having all three possible date type variations)

I've updated my PR to include the `[Date]` case though. Good catch :)

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@Pringels thx!

**Comment by Pringels** [comment]
Ready to merge

**Pull request merged**
