### PR TITLE
[jquery] Fix it for upstream changes

### PR DESCRIPTION
**Pull request by falsandtru**
The current declarations can't be compiled with nightlies.

### CODE REVIEW

**Comment by leonard-thieu** [comment]
Do you know why `mscaching` was removed?

**Comment by falsandtru** [comment]
https://github.com/Microsoft/TSJS-lib-generator is refined.

**Comment by leonard-thieu** [comment]
Could you add it as a property to `XHRFields`? Seems best to avoid making a breaking change.

**Review by leonard-thieu — CHANGES_REQUESTED** [review]
Could you add it as a property to `XHRFields`? Seems best to avoid making a breaking change.

**Comment by falsandtru** [comment]
@rbuckton @RyanCavanaugh Can you take a look?

**Comment by falsandtru** [comment]
@mhegazy Can you take a look?

**Comment by falsandtru** [comment]
Should I need to bump the version?

**Comment by leonard-thieu** [comment]
No. The version number in the declaration file is supposed to match the version of the library it represents. The version number in the resulting package is managed by the publishing process.

**Comment by falsandtru** [comment]
@rbuckton @RyanCavanaugh @mhegazy

**Pull request closed without merging**
