### PR TITLE
add types for `webpack-watch-files-plugin`

### PR DESCRIPTION
**Pull request by bengry**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by bengry** [comment]
When running `npm test webpack-watch-files-plugin` I get this error:
```
> definitely-typed@0.0.3 test /Users/bengr/projects-personal/DefinitelyTyped
> dtslint types "webpack-watch-files-plugin"

SyntaxError: Unexpected token } in JSON at position 505
    at JSON.parse (<anonymous>)
    at ~/projects/DefinitelyTyped/node_modules/dtslint/bin/util.js:40:21
    at Generator.next (<anonymous>)
    at fulfilled (~/projects/DefinitelyTyped/node_modules/dtslint/bin/util.js:24:58)
npm ERR! Test failed.  See above for more details.
```

Any idea why? I checked all the files I added, and they're all valid JSONs as far as I could tell.

**Comment by peterblazejewicz** [comment]
Q: does this package works with webpack 5 really?
https://github.com/Fridus/webpack-watch-files-plugin/blob/master/package.json#L40

**Comment by bengry** [comment]
> Q: does this package works with webpack 5 really? [https://github.com/Fridus/webpack-watch-files-plugin/blob/master/package.json#L40](https://github.com/Fridus/webpack-watch-files-plugin/blob/master/package.json?rgh-link-date=2021-10-01T20%3A42%3A28Z#L40)

Yes, I'm actively using it in a project that uses Webpack 5 (specifically `5.55.1` at the moment). I wouldn't otherwise submit this... 😅. I did check this after all:
> Test the change in your own code. (Compile and run)

I should also probably open a PR at https://github.com/Fridus/webpack-watch-files-plugin to update the peer dependency.

**Comment by peterblazejewicz** [comment]
That's OK for me, I asked because the automatic types acquisition feature of typescript in VSCode and others.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@bengry thx!

**Comment by bengry** [comment]
Ready to merge

**Pull request merged**
