### PR TITLE
Added textbox definition for typescript

### PR DESCRIPTION
**Pull request by yoxdev**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://fabricjs.com/docs/fabric.Textbox.html
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by bmartinson — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by armanio123** [comment]
Heads up, I'll wait a couple more days if you'll like to associate your GitHub account.  In any case, I'll merge this PR if you don't mind.

**Comment by BradleyHill** [comment]
@yoxdev, I added TextBox and some other text props in this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28564

Should be in the latest version of @types/fabric

**Comment by andy-ms** [comment]
@yoxdev Please make a new PR if there are any changes you want to make.

**Pull request closed without merging**
