### PR TITLE
Updated wordpress__blocks to 12.0

### PR DESCRIPTION
**Pull request by marekdedic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/WordPress/gutenberg/blob/%40wordpress/blocks%4012.0.0/packages/blocks/CHANGELOG.md
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__blocks ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__blocks@latest/))
was missing the following properties:
1. store
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 451abe8cc31ba9fed8a0e792f7d92019a10ca06f
</p>

**Review by dmsnell — APPROVED** [review]
I don't see anything wrong with this. Thanks for the contribution!

**Comment by marekdedic** [comment]
Ready to merge

**Comment by marekdedic** [comment]
Hey @dmsnell, I am getting a strange error on update and I don't see the relationship to this PR - any ideas?

skaut/skaut-google-drive-gallery#1754

**Comment by dmsnell** [comment]
did you examine the code? it looks like TypeScript sees a string when possibly it expects a property name of a block or block attributes? I didn't examine deeply, just skimmed the error. maybe it's unable to infer that what you're passing can be narrowed?

**Pull request merged**
