### PR TITLE
chore: rax sync react types

### PR DESCRIPTION
**Pull request by SoloJiang**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by amcasey** [comment]
@chenjun1011 @imsobear Can you please confirm that you'd like to be tagged as owners of this package?

**Review by amcasey — COMMENTED** [review]
While we wait to hear from the new owners, please consider adding tests for the new/updated code.

**Review by imsobear — APPROVED** [review]

**Comment by amcasey** [comment]
I assume there was a reason for listing @chenjun1011 as an owner.  @chenjun1011, if you no longer wish to be an owner, please create a PR removing yourself (or ask @SoloJiang to do so).

**Review by amcasey — APPROVED** [review]

**Comment by SoloJiang** [comment]
Ready to merge

**Pull request merged**
