### PR TITLE
switch to TypeScript v1.4

### PR DESCRIPTION
**Pull request by vvakame**
this PR will be merge when TypeScript 1.4.0 is published.

### CODE REVIEW

**Comment by basarat** [comment]
we could at some point start removing `tscparams` in favor of `tsconfig.json` once we have https://github.com/Microsoft/TypeScript/pull/1692

**Comment by vvakame** [comment]
@basarat yep! I think so too.
It should be implement to https://github.com/DefinitelyTyped/definition-tester
Do you know tsconfig are include to TypeScript 1.4?

**Comment by basarat** [comment]
> Do you know tsconfig are include to TypeScript 1.4?

Not in the current tagged version on github. But we won't know till 1.4 is finalized.

**Comment by johnnyreilly** [comment]
And it's out!
http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx

**Comment by vvakame** [comment]
It merged!

**Comment by vvakame** [comment]
tsconfig support is not in 1.4.1.
I'm looking forward to next release!

**Comment by johnnyreilly** [comment]
Yay!!!! Union types!!!!

**Comment by horiuchi** [comment]
Oh! :+1:

**Pull request merged**
