### PR TITLE
[p5.js] Added missing type and function declarations

### PR DESCRIPTION
**Pull request by rahulv4667**
## Description

The following declarations were added:
- `movedX`, `movedY`, `requestPointerLock()`, `exitPointerLock()` in mouse events
- `erase()` and `noErase()` in settings
- `describe()`, `describeElement()`, `textOutput()`, `gridOutput()` in environmet
- `drawingContext` in rendering
- `isLooping()` in structure
- `fract()` in calculation

## Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://p5js.org/reference/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by rahulv4667** [comment]
`drawingContext` takes type `CanvasRenderingContext2D` and `WebGLRenderingContext`. It doesn't currently take `WebGL2RenderingContext`. For that to work, changes need to be to made to have separate types for typescript version <=3.5 nd >=3.6. So, if making that change is fine, I will try to make necessary changes and update.

**Review by amcasey — CHANGES_REQUESTED** [review]
Can you please confirm that these members are present in version 0.9 of p5 and the version number doesn't need to be bumped?

**Comment by rahulv4667** [comment]
@amcasey Yes, the version number had to be changed. Although there were no mentions of it in [change logs](https://github.com/processing/p5.js/releases/tag/1.2.0), the `accessibility` code(which includes the above [definitions](https://github.com/processing/p5.js/blob/b191434378d4df530e039f2149acff6179ee452c/src/accessibility/describe.js#L18)) was added in version [1.2.0](https://github.com/processing/p5.js/tree/1.2.0/src). But I have bumped the version to 1.3.1 because that was the latest release when I had modified the declarations.

I have also added my name in contributors list. Please let me know if I need to make any more changes.

**Comment by rbuckton** [comment]
From what I can tell, everything looks good now.

**Review by rbuckton — APPROVED** [review]

**Comment by rahulv4667** [comment]
Ready to merge

**Pull request merged**
