### PR TITLE
multer: fix type of callback for custom storage

### PR DESCRIPTION
**Pull request by FeelyChau**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

The interface `StorageEngine` could implement as such:
```js
class CustomStorage {
  _handleFile(
    req: Request,
    file: Express.Multer.File,
    callback: (error?: any, info?: Partial<Express.Multer.File>) => void
  ): void {
    // just callback
    callback();
  }

  _removeFile(
      req: Request,
      file: Express.Multer.File,
      callback: (error: Error) => void
  ): void {
    // do something successfully
    // then callback
    callback();
  }
}
```

but the parameter `error` is not optional, so we get a type error here.
I checked the source code and the error should be optional, see:
https://github.com/expressjs/multer/blob/master/lib/remove-uploaded-files.js#L11

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
should it be rather same callback as in (in case of file storage) `fs.unlink`?
```ts
    export type NoParamCallback = (err: NodeJS.ErrnoException | null) => void;
```
so like in:
https://github.com/expressjs/multer/blob/master/storage/disk.js#L61

**Comment by FeelyChau** [comment]
> should it be rather same (sort of) callback as in (in case of file storage) `fs.unlink`?
> 
> ```ts
>     export type NoParamCallback = (err: NodeJS.ErrnoException | null) => void;
> ```
> 
> so like in:
> https://github.com/expressjs/multer/blob/master/storage/disk.js#L61

Are you meaning we should refactor to `callback: (error: Error | null) => void`?

**Comment by peterblazejewicz** [comment]
> Are you meaning we should refactor to `callback: (error: Error | null) => void`?

Yes, probably. I've been not using that one recently, so cannot say what this type of callback is used for in different contextes, but does it seem to follow Node patter, doesn't it?

**Comment by FeelyChau** [comment]
> > Are you meaning we should refactor to `callback: (error: Error | null) => void`?
> 
> Yes, probably. I've been not using that one recently, so cannot say what this type of callback is used for in different contextes, but does it seem to follow Node patter, doesn't it?

I think you are right.

**Comment by FeelyChau** [comment]
> > Are you meaning we should refactor to `callback: (error: Error | null) => void`?
> 
> Yes, probably. I've been not using that one recently, so cannot say what this type of callback is used for in different contextes, but does it seem to follow Node patter, doesn't it?

Updated. May I ask you to review again, please?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@FeelyChau thx!

**Comment by FeelyChau** [comment]
Ready to merge

**Pull request merged**
