### PR TITLE
[types/react] Fix regression with PropsWithChildren [The Travis build is lying]

### PR DESCRIPTION
**Pull request by VincentLanglet**
There is already two issues talking about issue with the introduction of PropsWithChildren.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33461
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33416

This type is an helper for a functional component
```
const Foo = (props: PropsWithChildren<FooProps>) => ...
```

I don't really understand why the change `Readonly<P & { children?: ReactNode }>` instead of `Readonly<P> & Readonly<{ children?: ReactNode }>` breaks something but the use of the helper in this case is not necessary so, quicker way to fix the regression is to revert this line.

### CODE REVIEW

**Review by ferdaber — APPROVED** [review]
I did notice this when I was playing around with HOCs but didn't have time to look into it :/

**Comment by VincentLanglet** [comment]
@gabritto Hi, you're the last one who merge some PR in this repo.
Can you look at this one please ? This is a bug fix, and the tests are failing only because of timeout.

**Comment by VincentLanglet** [comment]
@Jessidhia @johnnyreilly Hi ! The tests are always getting timeout...

**Comment by sandersn** [comment]
@ferdaber is right, except you don't need to post the logs. I'll believe you. :)

**Comment by VincentLanglet** [comment]
The test passed locally

**Pull request merged**
