### PR TITLE
Created new definitions for ko.plus library

### PR DESCRIPTION
**Pull request by conficient**
New submission for ko.plus - this is a set of extensions for knockout.js

See https://github.com/stevegreatrex/ko.plus

Ran tests using `tsc` method, using TypeScript v1.4 compiler, no errors or warnings

`npm test` didn't work for some reason:

```
C:\Users\Howard\Documents\GitHub\DefinitelyTyped>npm test

> DefinitelyTyped@0.0.1 test C:\Users\Howard\Documents\GitHub\DefinitelyTyped
> ./node_modules/.bin/dt --changes

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! weird error 1
npm ERR! not ok code 0
```

### CODE REVIEW

**Comment by stevegreatrex** [comment]
Hi Howard, thanks for this - the definitions all look good to me (though I must confess to having only a passing knowledge of TypeScript).

It looks like the problem running npm test is that it can't find the dt file - probably something wrong with the path concatenation.  Is there a grunt task or similar for running the typescript compilation and tests?

**Comment by vvakame** [comment]
@Igorbek @moonpyk @conficient could you review this PR?

**Comment by moonpyk** [comment]
Looks like a huge rewrite for that part, the usage of union types requires latest version of the typescript compiler. Could be a problem for some users but shouldn't stop us from going forward.
HTML5 components is not an area I personally use at all, someone with better knowledge in that area should make a close review.
Besides that, the code looks cleaner and tests are passing (bu maybe we miss tests for that precise area ?)

**Comment by conficient** [comment]
Sorry @moonpyk - the original pull request was for just the two new *ko.plus* files - no idea why GitHub decided to add the changes to knockout as well - I'll try to remove them and redo in a different branch.

**Comment by conficient** [comment]
OK have have reversed the last commit to revert to the original knockout definitions. The pull request now only relates to *new* definitions for the `ko.plus` library.

Please could either @moonpyk  or @Igorbek please review?

ta

**Comment by moonpyk** [comment]
Could you make an interactive rebase of your commits to remove 920b8d64621f249331f2a17123148c446c212d32 and 86ca758d1cd9514cea55ff77072f0c406b6c007f completely from the picture, then push -f to your repo ? It will make history look better.

Regards.

**Comment by conficient** [comment]
Thanks @moonpyk I've done as requested - the pull request now only has the ko.plus entries. What a dangerous command that `rebase` is !

**Comment by moonpyk** [comment]
@conficient Very nice work :+1: 

@vvakame Good to merge for me

**Comment by vvakame** [comment]
@moonpyk thanks!
@conficient thanks mate!

**Pull request merged**
