### PR TITLE
[react] Replace `facebook.github.io/react` with `react.dev`

### PR DESCRIPTION
**Pull request by eps1lon**
Follow-up to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64907 where I only looked for reactjs.org but not the much older facebook.github.io/react

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0d11e6ea9a71493c4cd20c19cd60a9a254ef0d03
</p>

**Comment by johnnyreilly** [comment]
Is the test removals intentional?

**Comment by eps1lon** [comment]
Yep. Forgot to mention. It's already tested elsewhere.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Pull request merged**
