### PR TITLE
[nw.js] Update type for MenuItem.enabled

### LINKED ISSUE #51522: @types/nw.js MenuItem.enable property type is incorrect
@types/nw.js  has incorrect type for MenuItem.enabled property

 ```
// Type definitions for nw.js 0.13
// Project: http://nwjs.io
// Definitions by: Alireza Dabiri Nejad <https://github.com/alirdn>
```

In MenuItem:
```
             /**
             * Get or set whether the `MenuItem` is `enabled`
             */
            enabled: string;

```

should be something like:
```
             /**
             * Get or set whether the `MenuItem` is `enabled`
             */
            enabled: boolean;

```

- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alirdn

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #51522

Documentation: https://nwjs.readthedocs.io/en/latest/References/MenuItem/#itemenabled

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by alirdn** [comment]
Dear @martin-badin, thanks for your PR. I'll review it and approve if all is well, or request changes if not.

**Comment by martin-badin** [comment]
@alirdn @peterblazejewicz could you review it?

**Comment by peterblazejewicz** [comment]
@martin-badin IMO PR does not covers what was the issue about,
Do you want to cover the changees like that one:
```diff
- registerStream(id: string): void;
+ registerStream(id: string): string;
```
which is brekaing change and there is no single test for that method in this PR (nor in existing code)?
I'd probably split this, fix the problem (so it's focused) and move the change with 'tslint' trimmed down to next one, but do not make breaking changes we dannot expect the outcome (as there is no tests). Leave this for later (3rd PR)

**Comment by alirdn** [comment]
> @martin-badin IMO PR does not covers what was the issue about,
> Do you want to cover the changees like that one:
> 
> ```diff
> - registerStream(id: string): void;
> + registerStream(id: string): string;
> ```
> 
> which is brekaing change and there is no single test for that method in this PR (nor in existing code)?
> I'd probably split this, fix the problem (so it's focused) and move the change with 'tslint' trimmed down to next one, but do not make breaking changes we dannot expect the outcome (as there is no tests). Leave this for later (3rd PR)

@peterblazejewicz  I agree to have separate PR for separate changesets. 

@martin-badin Thanks for your PR. I'll approve this. It'll be great if you create a new PR for the extra changes you made. And After that, I'll create another PR to add more tests.

**Review by ElyDotDev — APPROVED** [review]
+1

**Comment by martin-badin** [comment]
Ready to merge

**Comment by peterblazejewicz** [comment]
@martin-badin thx!

**Pull request merged**
