### PR TITLE
[react-csv] Stop testing react-dom

### PR DESCRIPTION
**Pull request by eps1lon**
Usage of react-dom in this package was not actually testing integration between this package and `react-dom` but `react` and `react-dom`. This adds considerable overhead to making changes to react-dom so I just removed these redundant tests.

### CODE REVIEW

**Comment by jakebailey** [comment]
Can the dependency also be removed?

**Comment by jakebailey** [comment]
I didn't realize you had sent a lot of these; probably all of those also deserve the dep removal. I intend to (one day) run `knip` on all of our packages as there's definitely some extra deps around.

**Review by jakebailey — APPROVED** [review]

**Comment by eps1lon** [comment]
I did it on some but also likely forgot it for a lot of them. Would definitely prefer some automation ;)

**Comment by eps1lon** [comment]
Ready to merge

**Pull request merged**
