### PR TITLE
Added type definitions for jasmine-given.

### PR DESCRIPTION
**Pull request by brp-nylin**
Added the type definitions needed to work with jasmine-given in your TypeScript project.

### CODE REVIEW

**Comment by vvakame** [comment]
*jasmine-given/jasmine-given.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jasmine-given
  * http://bower.io/search/?q=jasmine-given
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jasmine-given/jasmine-given-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by brp-nylin** [comment]
This addition does not include any test cases, but I suspect that it isn't needed, right?

**Comment by vvakame** [comment]
@brp-nylin no, It required. please add a test. :wink:

**Comment by brp-nylin** [comment]
What's the status here?

**Comment by vvakame** [comment]
@brp-nylin http://definitelytyped.org/guides/contributing.html#tests

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
