### PR TITLE
[Three] Make EventDispatcher generics

### PR DESCRIPTION
**Pull request by woo-cie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/mrdoob/three.js/blob/dev/src/core/EventDispatcher.js

### CODE REVIEW

**Comment by woo-cie** [comment]
Hi.
I propose these changes to resolve some problems in EventDispatcher declaration file.

1. Collect type of event.target
Now, event.target is defined as any or undefined in listener args.
But, in js implementation, event.target must be EventDispatcher itself.
So, it has to be defined as this.

2. Enable to restrict method's args by type
Current declaration allows code below.
``` ts
class MyEventDispatcher extends EventDispatcher {
  someFunction(){
    this.dispatch({event: "onSomeEvent", attachment: 10});
  }
}

// somewhere
myEventDispatcher.addEventListener("onSomeEvent", e => console.log(e.attachmant))
// expected 10 but actually undefined because of typo
```
So I enable to restrict args like this.
``` ts
type Event = {type: "onSomeEvent", attachment: number} | {type: "onSomeEvent2", attachment2: string};
class MyEventDispatcher extends EventDispatcher<Event> {
  someFunction(){
    this.dispatch({event: "onSomeEvent", attachment: 10});
  }
}

// somewhere
myEventDispatcher.addEventListener("onSomeEvent", e => console.log(e.attachment))
// Auto-completion also works well.

myEventDispatcher.addEventListener("onSomeEvent2", e => console.log(e.attachment))
// Error: Property 'attachment' does not exist on ...
```

**Comment by joshuaellis** [comment]
@Methuselah96 whats you're thoughts on this? I'm open to a generic that improves the DX.

**Comment by Methuselah96** [comment]
Yeah, this looks good to me.

**Comment by joshuaellis** [comment]
@woo-cie Would you be able to make this PR in `three-ts-types`? Aimed at `main` I think 😄

**Comment by woo-cie** [comment]
@joshuaellis I'd love to.
https://github.com/three-types/three-ts-types/pull/125 is ported PR.

**Comment by joshuaellis** [comment]
this should be closed since it has been released.

**Pull request closed without merging**
