### PR TITLE
Type definitions for to-title-case (http://individed.com/code…

### PR DESCRIPTION
**Pull request by stpettersens**
…/to-title-case)
https://github.com/gouch/to-title-case

### CODE REVIEW

**Comment by vvakame** [comment]
*to-title-case/to-title-case.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/to-title-case
  * http://bower.io/search/?q=to-title-case
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (to-title-case/to-title-case-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
https://www.npmjs.com/package/to-title-case point to https://github.com/ianstormtaylor/to-title-case
but your definitions is created for https://github.com/gouch/to-title-case ? is this right?

**Comment by stpettersens** [comment]
It is for https://github.com/gouch/to-title-case. It's not on npm as package. Should I rename it? Thanks.

**Comment by vvakame** [comment]
@stpettersens yep. please rename it. for example... to-title-case-gouch? or something good name.

**Comment by stpettersens** [comment]
Okay, will do.

**Pull request closed without merging**
