### PR TITLE
DocumentArray disciminator() should be able to receive both document and model interface

### PR DESCRIPTION
**Pull request by asafalg**
Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [X ] Add or edit tests to reflect the change. (Run with `npm test`.) - No new tests required
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: https://mongoosejs.com/docs/discriminators.html#embedded-discriminators-in-arrays
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Since documentArray.discriminator returns a model, there is a possibility to pass an interface for the model (as well as an interface for the document) allowing the developer to specify instance methods and static functions for the document and model.

### CODE REVIEW

**Comment by jendrikw** [comment]
This looks a lot like a hidden type assertion, as described in the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes.

The way you wrote it looks like it allows the caller to choose what the method will return, which is not true.

**Comment by moseschrist** [comment]
How is this different from the model function ?

**Comment by jendrikw** [comment]
It isn't and that has been bothering me for quite some time now. Ideally, the model function should not exist the way it does now. I'm planning on removing it at some time, but I haven't found time for that.

Let's hear the opinion of the other maintainers.
@horiuchi @lukasz-zak @Alorel @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen

**Comment by jendrikw** [comment]
I'll accept the PR for consistency within the API. If I ever get around reworking the whole package, it's still possible to change.

**Review by jendrikw — APPROVED** [review]

**Pull request merged**
