### PR TITLE
fixed async doWhilst

### PR DESCRIPTION
**Pull request by murcal**

### CODE REVIEW

**Comment by Penryn** [comment]
Thanks for the contribution, but unfortunately this doesn't follow the API outlined at https://github.com/caolan/async#doWhilst

:-1:

**Comment by DominicBoettger** [comment]
Yes, but i think the API makes no sense at all, cause writing a test function without a parameter or a dataset which is testable is not really a test function ;-).

**Comment by Penryn** [comment]
You're welcome to open a ticket at caolan/async. Typescript definitions must exactly match a module's API regardless of your feelings for or against it.

**Comment by DominicBoettger** [comment]
The API documentation is wrong and it's not about feelings. It's just working and correct. I already opened a ticket.

**Comment by vvakame** [comment]
note https://github.com/caolan/async/issues/1107

**Comment by Penryn** [comment]
Ok so looking at the changelog for this commit we had

     doWhilst(fn: AsyncVoidFunction, test: () => boolean, callback: (err: any) => void): void;

Now replaced by

     doWhilst(fn: (Function), test: (data: any) => boolean, callback: (err: any) => void): void;

Looking at https://github.com/caolan/async/blob/master/lib/doWhilst.js#L29 I still don't think this is right.

It seems @DominicBoettger you are right about that particular case (this is basically undocumented behavior). However, the existing repo isn't _wrong_ (ie: no breaking changes), and these commits aren't _right_.

Ideally, `AsyncVoidFunction` should not have been changed to `Function` because it is less specific, and `test: (data: any)` is still not correct because the API does not require `data`. It does pass other arguments onwards, but these commits don't reflect that. It's a good effort and highlights the problem, but it's just a bit incorrect (sorry @murcal!).

I still vote :-1:, and welcome anyone else to weigh in!

Perhaps a new PR should be opened to change `test: () => boolean` to `test: (...arguments: any[]) => boolean` or similar, because that's what the internal API does. I can do this myself at some point if no one beats me to it.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
