### PR TITLE
[node] Process no exitCode

### PR DESCRIPTION
**Pull request by TonyPythoneer**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

---

According to [node.js v4 doc - exitCode](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_exitcode), it should has exitCode in Process.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Hello, who can review or merge this PR? Help.

**Comment by TonyPythoneer** [comment]
Hello @vvakame, I had fix something for this, would you review and merge it?

**Comment by vvakame** [comment]
wow, sorry for late.

**Comment by TonyPythoneer** [comment]
thx. :smile:

**Pull request merged**
