### PR TITLE
[hls.js] Change nextLevel to number type. 

### PR DESCRIPTION
**Pull request by fyuhkust**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Some notes:
hls.nextLevel should be in number type because it is used as an index for selection for next level in code. Similar logic might apply to other types like nextLoadLevel, etc. I only change this one because I only tested this one in my code.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Please add test for the change, Please provide documentation as to why the nextLevel is number instead.

**Comment by FeiAline** [comment]
So while checking the doc of hls.js, it said that you would need to set it to -1 for automatic level selection. Hence it cannot be an object. here is the link to the [doc](https://github.com/video-dev/hls.js/blob/master/doc/API.md#hlsnextlevel).

From code of level controller ([link](https://github.com/video-dev/hls.js/blob/0cb25ef069b45e3c65d6be6b931a370464eee3f6/src/controller/level-controller.js)), from tick() function, you would see this:

```
  tick() {
    var levelId = this._level;
    if (levelId !== undefined && this.canload) {
      var level = this._levels[levelId];
      if (level && level.url) {
        var urlId = level.urlId;
        this.hls.trigger(Event.LEVEL_LOADING, {url: level.url[urlId], level: levelId, id: urlId});
      }
    }
  }
```

Notice that `this._level` is used as an index. 

Also: 

```
  set level(newLevel) {
    let levels = this._levels;
    if (levels && levels.length > newLevel) {
      if (this._level !== newLevel || levels[newLevel].details === undefined) {
        this.setLevelInternal(newLevel);
      }
    }
  }

 setLevelInternal(newLevel) {
    const levels = this._levels;
    const hls = this.hls;
    // check if level idx is valid
    if (newLevel >= 0 && newLevel < levels.length) {
      // stopping live reloading timer if any
      this.cleanTimer();
      if (this._level !== newLevel) {
        logger.log(`switching to level ${newLevel}`);
        this._level = newLevel;
        var levelProperties = levels[newLevel];
        levelProperties.level = newLevel;
        // LEVEL_SWITCH to be deprecated in next major release
        hls.trigger(Event.LEVEL_SWITCH, levelProperties);
        hls.trigger(Event.LEVEL_SWITCHING, levelProperties);
      }
      var level = levels[newLevel], levelDetails = level.details;
       // check if we need to load playlist for this level
      if (!levelDetails || levelDetails.live === true) {
        // level not retrieved yet, or live playlist we need to (re)load it
        var urlId = level.urlId;
        hls.trigger(Event.LEVEL_LOADING, {url: level.url[urlId], level: newLevel, id: urlId});
      }
    } else {
      // invalid level id given, trigger error
      hls.trigger(Event.ERROR, {type : ErrorTypes.OTHER_ERROR, details: ErrorDetails.LEVEL_SWITCH_ERROR, level: newLevel, fatal: false, reason: 'invalid level idx'});
    }
 }

```

Notice that the `newLevel` in `set level` is also used as an index for levels array.

I am actually using this library in my product in production. Javascript crashes with type Hls.Level.  It only works when it is number.

**Comment by jgainfort** [comment]
@FeiAline you are correct. I can add the rest of the changes in when I get the opportunity. Will shoot for later today or tomorrow. 

@sheetalkamat  Will still probably want a quick test added for your change though. Otherwise I approve.

**Comment by FeiAline** [comment]
Thank you @jgainfort

**Comment by amcasey** [comment]
Will this change be redundant if #18753 merges?

**Comment by jgainfort** [comment]
Yes it will, this can be closed.

**Pull request closed without merging**
