### PR TITLE
fix bluebird refrence and add dropForeign function

### PR DESCRIPTION
**Pull request by saberistic**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://knexjs.org/#Schema-dropForeign http://bookshelfjs.org/#one-to-many .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by tkqubo** [comment]
:+1: Thanks!

**Comment by amirsaber** [comment]
Sure @tkqubo

**Comment by amirsaber** [comment]
@vvakame any thing new on this bro. I would be thankful if you can review it since my build process is failing because of this.

**Comment by trixlerjs** [comment]
@amirsaber @tkqubo @doug   `suppressUnhandledRejections` is missing from Bluebird definitions. Could you add it?

**Pull request merged**
