### PR TITLE
feat(forest-express-sequelize): remove types

### PR DESCRIPTION
**Pull request by hkleungai**
See [v7.12.0 release note](https://github.com/ForestAdmin/forest-express-sequelize/releases/tag/v7.12.0).

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:

- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by ghusse** [comment]
It seems weird to have a PR that just deletes everything. Is there a different way of doing it?
Is it possible to declare that the current version can be used until a given version of FES?

**Comment by hkleungai** [comment]
Hi @ghusse , I think the current practice of DefinitelyTyped is to remove type once the library ships its own typedef. See [this section](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#removing-a-package) on DT readme. 

Also note that removing types from DT does NOT trigger any deletion for previously published `@types/<lib>` on npm.

**Review by ghusse — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
When this merges, it will publish a deprecated `@types/forest-express-sequelize@7.5.5` that tells people to switch to `forest-express-sequelize@7.12`. 

Of course (1) if they already have FES@7.12, typescript will ignore the `@types/FES` (2) new versions of npm will skip deprecated versions to install `@types/FES@7.5.4`, which will stay on npm as @hkleungai pointed out.

**Comment by hkleungai** [comment]
Ready to merge

**Comment by hkleungai** [comment]
Ready to merge

**Pull request merged**
