### PR TITLE
[dom-chromium-ai] introduce `languageAvailable()` methods

### PR DESCRIPTION
**Pull request by christianliebel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
 - https://github.com/WICG/writing-assistance-apis/commit/24de0505871c9f0caab65330256223d20c22dfa3
 - https://github.com/explainers-by-googlers/prompt-api/commit/49b1bfe16095b672553cde70d6b837cd51c6d9e1
 - https://github.com/WICG/translation-api/commit/2363b60306057a71071cdd4f5241e4ccc065ad73
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/dom-chromium-ai/dom-chromium-ai-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ec1595eaf9bdd7f8dac9fad00e401d6569571734
</p>

**Comment by christianliebel** [comment]
Created a separate PR for assistant-role and multiple prompts: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71238

**Review by rbuckton — APPROVED** [review]

**Review by tomayac — APPROVED** [review]
LGTM

**Comment by christianliebel** [comment]
Ready to merge

**Pull request merged**
