### PR TITLE
Updated typings for react-bootstrap-typeahead

### PR DESCRIPTION
**Pull request by Chrisdo82**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-bootstrap-typeahead ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-bootstrap-typeahead@latest/))
was missing the following properties:
1. useHint
1. Input
1. asyncContainer
1. useAsync
1. withAsync

<details>
<summary>as well as these 5 other properties...</summary>
<p>menuItemContainer, useItem, withItem, tokenContainer, withToken</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8bb7934c2ef65915e0fee36b62acce3d912ff4f0
</p>

**Comment by Chrisdo82** [comment]
ping @Guymestef @radziksh @PaitoAnderson @arichter83 @dalevfenton @KngHawkon could you please review this PR

**Review by KngHawkon — APPROVED** [review]
LGTM

**Comment by Chrisdo82** [comment]
Ready to merge

**Pull request merged**
