### PR TITLE
video.js add alternative distribution typings

### PR DESCRIPTION
**Pull request by sroucheray**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sroucheray** [comment]
Last error seems related to https://github.com/sandersn/dts-critic/issues/10

**Comment by joeflateau** [comment]
@sroucheray this seems very un-dry. Is there any better way to do this by importing/reexporting maybe?

**Comment by sroucheray** [comment]
@joeflateau Totally agree :) I have tested several things but I didn't manage to import / reexport or to apply two names on the namespace (does it even make sense ?).
I literraly open this PR to initiate the discussion and am very open to suggestions !
I manage to workaround the problem on some of my repos by a simple postinstall script that duplicate the `index.d.ts` but I don't think DefinitelyTyped provides the tooling for doing that.

**Comment by joeflateau** [comment]
@sroucheray does something like `export * from ../../index.d.ts` work? If not maybe we can get some input from someone who knows way more than I do.

**Comment by sroucheray** [comment]
> export * from ../../index.d.t

@joeflateau Thanks for the advice !

It does not work unfortunately. It generates no errors but does not provide the right object when trying to import it with:
```typescript
import videojs from 'video.js/dist/alt/video.core.novtt';
```
but I tried that:

```typescript
import videojs from "../../index";

export default videojs;
```
 and it seems to work ! plus it is DRY.

I'll push a new commit

**Comment by sroucheray** [comment]
I am going to close this pull request and open another one as I squashed my commit

**Comment by sroucheray** [comment]
It's here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40319

**Comment by joeflateau** [comment]
@sroucheray awesome!

**Pull request closed without merging**
