### PR TITLE
Fixes and additions to jsdom definitions

### PR DESCRIPTION
**Pull request by gwicksted**
Added several missing features such as VirtualConsole, CookieJar (partially implemented), additional document feature proxy calls, nodeLocation, reconfigureWindow, serializeDocument, jQuerify

### CODE REVIEW

**Comment by gwicksted** [comment]
Please take this PR - addresses several missing definitions for jsdom.

**Comment by vvakame** [comment]
@pspeter3 could you review this PR?

**Comment by pspeter3** [comment]
LGTM

**Comment by gwicksted** [comment]
Thank you for reviewing @pspeter3!  @vvakame, are you able to merge this to master?  I know you must be overwhelmed by the activity on this repo!

**Comment by vvakame** [comment]
thanks all!

**Comment by gwicksted** [comment]
Thank you!

**Comment by gwicksted** [comment]
Can someone git revert ffad52f?  Or should I create another PR?

**Pull request merged**
