### PR TITLE
types/photoshop - Type Definition Update 

### PR DESCRIPTION
**Pull request by baaygun**
Update from Author: Ready to merge!

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:https://developer-stage.adobe.com/photoshop/uxp/2022/ps_reference/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
@baaygun: two notes:

1. It's easy to miss your comment at the top about not merging this.  It would be better to do that properly by converting it to a draft, or maybe have a rejecting review, both would make it require some work for merging.

2. Can you please undo the changes to the owners? -- It's used to ping actual people who can review stuff, and putting an organization there means that the bot would ping it, usually ending up with no reviews.  (The bot [should really](https://github.com/DefinitelyTyped/dt-mergebot/issues/430) check this...)

**Comment by baaygun** [comment]
@elibarzilay thank you for your comments. I have now marked it as ready to merge. And I have re-added the authors.

**Comment by elibarzilay** [comment]
@baaygun: thanks for adding the owners again.  Also, these are not really reviews, that's why we have owners that should be the experts 😃...

**Comment by baaygun** [comment]
Ready to merge

**Pull request merged**
