### PR TITLE
Better aws-sdk definitions for SQS

### PR DESCRIPTION
**Pull request by enicholson**
I'm not sure what the status of the aws-sdk definitions is, but I took a stab at implementing SQS according to the current docs (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html).  This included adding tests based on examples from the docs, adding missing methods, and fixing class/interface definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
*aws-sdk/aws-sdk.d.ts*

to author(@midknight41). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by midknight41** [comment]
Yup. Will have a look tomorrow.

**Comment by enicholson** [comment]
Any updates?  If this is mergeable, I'll take a look at S3 updates next. Thanks guys!

**Comment by midknight41** [comment]
@vvakame I've had a quick read through. LGTM

@enicholson These defs were done a long time ago and were in dire need of updating...thanks!

**Comment by enicholson** [comment]
@vvakame Can we go ahead and merge this one?  Thanks!

@midknight41 Did you happen to use something to generate these definitions initially?  Thanks for the review!

**Comment by vvakame** [comment]
thanks mate!

**Comment by midknight41** [comment]
@enicholson I wrote an ugly little C# application that extracted the C# SDK information using reflection. Then I did some painful fixing. That's probably not how I'd do it now!

**Pull request merged**
