### PR TITLE
Definitions for node module mariasql added

### PR DESCRIPTION
**Pull request by bennett000**
https://github.com/mscdex/node-mariasql

 On branch mariasql
    new file:   mariasql/mariasql-tests.ts
    new file:   mariasql/mariasql.d.ts

### CODE REVIEW

**Comment by vvakame** [comment]
@bennett000 thank you your contributions.
please check this document. http://definitelytyped.org/guides/best-practices.html#ghost-modules
could you use ghostin module pattern?

**Comment by bennett000** [comment]
@vvakame will do.  Sorry for not using the ghostin pattern.  I still do not fully understand how to best work with TypeScript's various module systems.  I need to learn this ASAP, because it's negatively affecting my productivity.  Otherwise I'm really happy for the type support.

I will fix this once I understand how to make it work, and I will likely have some more definitions.

**Comment by vvakame** [comment]
@bennett000 okey, I'll waiting it.

**Comment by bennett000** [comment]
I put a little more time into fixing this up, and now the fact that ghost modules contain only interfaces makes sense.

I'm still struggling to export a constructor function as a module. [This SO post](http://stackoverflow.com/questions/26249210/how-do-i-write-a-typescript-declaration-file-for-a-complex-external-commonjs-mod) has been really helpful.

**Pull request merged**
