### PR TITLE
[Square-connect] Use const enums

### PR DESCRIPTION
**Pull request by ddimitrioglo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/square/connect-nodejs-sdk#documentation-for-api-endpoints
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by mootrichard — APPROVED** [review]

**Comment by armanio123** [comment]
I believe you should not be using `const enums` on `d.ts` files as they break with the flag `--isolatedModules`. Instead the approach is to use a `type`. e.g.:

```js
export type CountryEnum = 'ZZ' | 'AD' | 'AE' | ...
```

More details here: ://github.com/DefinitelyTyped/DefinitelyTyped/issues/23002

**Review by armanio123 — CHANGES_REQUESTED** [review]
See comment above.

**Review by mootrichard — CHANGES_REQUESTED** [review]
I actually agree with the comments regarding not using `const enum`. I wasn't aware of this and it does look like something that should be avoided in `d.ts` files.

**Comment by ddimitrioglo** [comment]
Hi @armanio123 ,
In that case in my code, instead of using `CountryEnum.USD` i need to use `USD`? 
If yes - that's kind of weird to get rid of `enum`s in your typescript code.
Am I missing something?

Thanks.

**Comment by ddimitrioglo** [comment]
@mootrichard what do you think about my comment above?

**Comment by mootrichard** [comment]
@ddimitrioglo forgive my lack of understanding. I'm admittedly not _super_ well versed in TypeScript. What was wrong with the previous way of just having: 

```typescript
export enum CurrencyCode {
  USD = "USD"
}
```

Wouldn't that still allow you to use `CurrencyCode.USD`?

**Comment by ddimitrioglo** [comment]
> What was wrong with the previous way

Nope, I'm getting `undefined` on runtime... actually looks like I'll face the same issue with new approach... 
Don't really know how to declare enums in `*.d.ts` in order to work with them as usual `enum`, not the string.

Hope that @armanio123 will help me here.

**Comment by mootrichard** [comment]
So I went through and adjusted it to this https://gist.github.com/mootrichard/f392bd6f257a05a7b1d5219b71778e2f

Can you try that out and see whether you'd still be getting `undefined` values at runtime?

It just seems like you're not able to `declare` enums in a type definition file. Doing it this other way still defines the types and gives you type inference. 

I'm admittedly a little puzzled, since simply having enums like `CurrencyEnum.USD` is cleaner. I guess the enums are something that should be defined in the SDK rather than the `d.ts` though.

**Comment by ddimitrioglo** [comment]
@mootrichard 
Of course, would be cool to have those enums in SDK, but as it's auto-generated we do not have that luxury.

So, looks like we have to switch to this approach, but with minor changes, `CurrencyEnum` => `CurrencyEnumType` or `CurrencyType` in order to explicitly say that it's not an enum anymore and use strings (ex: `'USD'`) in the code.

Thank you for your time and help!

**Comment by Nican** [comment]
@ddimitrioglo Would you like to just add my ApiClient/constructor definitions into this pull request?
I do not really care for the credits, but I just want it working. 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38992

**Comment by ddimitrioglo** [comment]
@armanio123 Could you please review my changes.
It blocks me to use new version in my project. Thanks.

**Review by armanio123 — APPROVED** [review]
Sorry for the delay and thanks for doing the big change.

**Review by mootrichard — APPROVED** [review]

**Pull request merged**
