### PR TITLE
[coingecko-api@1.0.10] Add include_market_cap option

### PR DESCRIPTION
**Pull request by janklimo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.coingecko.com/api/documentations/v3#/simple/get_simple_price
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by janklimo** [comment]
Hello @miscavage 👋 would you mind taking a look as the owner of the package?

**Comment by janklimo** [comment]
Can we get this merged, please?

**Comment by janklimo** [comment]
@andrewbranch @peterblazejewicz you guys previously reviewed #52934. Would you mind giving this a look? Thanks!

**Comment by peterblazejewicz** [comment]
@janklimo sure, give us a moment to review a problem I've noticed recently on DT. I"ll approve, so it's up to you to complete. Read my follow up comment to DT maintainer, thx!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
@sandersn I've noticed same linter problem in other PR, recently added `undefined` are now being marked as duplicates, but only in CI builds, not locally.
IMO this adds a noise. so like here, `tslint:disable-next-line no-redundant-undefined` is example of intent to preserve maintainer changes.

**Comment by janklimo** [comment]
Ready to merge

**Pull request merged**
