### PR TITLE
[faker] apply global prettier style

### PR DESCRIPTION
**Pull request by p-j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
Following https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51436
And applying Contribution Guidelines regarding [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes)

### CODE REVIEW

**Comment by pkuczynski** [comment]
Some of the changes from the [recent](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51436) prettier config (single vs dbl quotes) makes a doubtful value tbh, and I am not such a big fan of it, so I would leave it to others to decide if it should be merged or not...

**Comment by p-j** [comment]
I prefer single quote as well tbh, but since the config is set to double and my VSCode setup picks up whatever the project config is and apply it on save, it makes it easier moving forward for anyone with a similar setup to contribute without having unrelated changes added alongside.

Plus having a consistent style throughout the codebase is always a plus.

The original PR changing the configuration for prettier has this comment:

>> (I prefer double quotes too, but changing the default seems like it's better if someone else looks at it...)
>
> `dtslint` actually mandates double quotes, so if you were to run prettier on the codebase, you would break everything. :)
>
_Originally posted by @fedemp in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51436#issuecomment-792763338_

**Comment by pkuczynski** [comment]
Yeah, I have seen this comment. Yet I was doing some changes on this repo after dbl quotes were introduced and no build failures or whatsoever. Please notice, that your other PR went smoothly regardless of not using dbl quotes...

**Comment by pkuczynski** [comment]
I would like to hear what other people think of this PR...

**Comment by pkuczynski** [comment]
@p-j the settings changed back to as it was before (#52946). Can you rebase your PR, re-run prettier. I think there were few other changes worth preserving. Than I would approve...

**Comment by p-j** [comment]
@pkuczynski here you go

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
Thanks!

**Comment by p-j** [comment]
Ready to merge

**Pull request merged**
