### PR TITLE
Removed package wordpress_core-data

### PR DESCRIPTION
**Pull request by marekdedic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by marekdedic** [comment]
Depends on #63671

**Comment by marekdedic** [comment]
Now depends on microsoft/DefinitelyTyped-tools#632

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__editor ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__editor@latest/))
was missing the following properties:
1. store
1. store
1. store
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7054d70890efc609775a0037c665094d320c72e2
</p>

**Comment by sandersn** [comment]
The bot just brought this to my attention and I would recommend splitting this PR into one that deletes wordpress__core-data and one that updates the other ones. Together, it's too hard to review.

**Comment by marekdedic** [comment]
Hi, I would prefer to do that as well (and I am doing just that in #63638), however, here I can't get it to work - if I try to update the dependent packages, they still seem to somehow use the types from the core-data package. Because the way the types are structured in the typings package and the upstream package, the tests then fail for the dependent package unless the core-data package is removed.

**Comment by sandersn** [comment]
Now that I look at it again, I see that the changes come from updating from the old DT version of core-data to the new, non-DT core-data. You're right, there's no way to separate the two.

**Comment by adamziel** [comment]
Yes, the `@wordpress/core-data` npm package now ships with types. The readme says:

> Core data is shipped with TypeScript definitions for WordPress data types.

Also, the freshly installed package has the right `.d.ts` definitions as well as the `"types"` entry in package.json:

```
❯ npm install @wordpress/core-data
❯ ls node_modules/@wordpress/core-data/build-types/
actions.d.ts              hooks/                    resolvers.d.ts            
actions.d.ts.map          index.d.ts                resolvers.d.ts.map        
batch/                    index.d.ts.map            selectors.d.ts            
entities.d.ts             locks/                    selectors.d.ts.map        
entities.d.ts.map         name.d.ts                 types.d.ts                
entity-provider.d.ts      name.d.ts.map             types.d.ts.map            
entity-provider.d.ts.map  queried-data/             utils/                    
entity-types/             reducer.d.ts              
fetch/                    reducer.d.ts.map    
```

Furthermore, the types shipped in the package are much more recent than the ones in DefinitelyTyped.

**Review by dsifford — APPROVED** [review]

**Comment by dmsnell** [comment]
Are our types already published in WordPress? I think we need to make sure that we don't remove these before `npm install @wordpress/core-data` also pulls in the types.

Apologies if you've already taken care of this.

**Comment by marekdedic** [comment]
@dmsnell They are, in fact the two other packages edited in this PR are using them.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@marekdedic thanks!
Please watch the WP community reports, to catch possible problems after this merges, thanks!

**Comment by marekdedic** [comment]
Ready to merge

**Pull request merged**
