### PR TITLE
[Faker] Remove non-existent methods

### PR DESCRIPTION
**Pull request by testica**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/Marak/faker.js/tree/v4.1.0>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by mattbishop** [comment]
Uh why do you think these methods have been removed? I checked the first three (address and date) and they are still in faker.js master.

**Review by mattbishop — CHANGES_REQUESTED** [review]
I don't think these have been removed from faker. Please review and if you cannot find a method in the faker source code, leave a link to the line that is near where it might have been, or to the git commit where it was removed.

**Comment by testica** [comment]
@mattbishop the latest npm version for faker is the [4.1.0](https://github.com/Marak/faker.js/tree/v4.1.0).
For some reason master updates have not been published.

Also, you can confirm downloading the npm package.

**Comment by testica** [comment]
@mattbishop can you check it out before not close the PR 🥺

**Comment by mattbishop** [comment]
Sorry I was away for a bit. Resubmit please and I will review against 4.1.0

**Pull request closed without merging**
