### PR TITLE
Updates to Mongoose 4.5.x

### PR DESCRIPTION
**Pull request by simon-xiong-ca**
This is a complete update of the mongoose definitions from 3.8.x to 4.5.x
You can test it by copying the definitions into your project and let me know if there's any issues with compatibility.
It follows how mongoose itself is structured and should be a very accurate mapping to the public API.

### CODE REVIEW

**Comment by horiuchi** [comment]
Gread Work! :+1:

**Comment by pocesar** [comment]
this is huge! thanks @simonxca 
will certainly use it and give some feedback, as I use mongoose 4.x extensively

**Comment by simonxca** [comment]
Thanks, I will maintain these definitions for the forseeable future so let me know if there's any issues. I tried my best not to break too much.

**Comment by simonxca** [comment]
@pocesar awesome, would really appreciate a good stress test.

**Pull request merged**
