### PR TITLE
fix: Add pg dynamic password support to ClientOptions

### PR DESCRIPTION
**Pull request by sehrope**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/brianc/node-postgres/pull/1926
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

Adds typings to `pg` for connection config with dynamic passwords via a sync or async function. This was added to a pg v7.12.0 and the typings claim to be for 7.14 so this is a fix for incomplete typing for that property.

### CODE REVIEW

**Comment by sehrope** [comment]
Updated to add some test usage of the dynamic passwords with both a sync and async function.

**Review by HoldYourWaffle — APPROVED** [review]

**Comment by benkeil** [comment]
Ready to merge

**Comment by benkeil** [comment]
@sehrope can you merge please? ☺️

**Comment by sehrope** [comment]
Ready to merge

**Pull request merged**
