### PR TITLE
(gapi.auth2) Add authuser config option to AuthorizeConfig

### PR DESCRIPTION
**Pull request by trshafer**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by flawless2011** [comment]
@trshafer Can you provide a link to the Google Web Sign-in reference where you saw the need for the `authuser` config option?

**Comment by trshafer** [comment]
It's not on the reference docs, but it is available in the auth2 source: https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.ZPSwvoEq44A.O/m=auth2,client/d=1/am=AAg

That url came from this script modified from the [sample](https://developers.google.com/apps-script/guides/rest/quickstart/js#step_2_set_up_the_sample).
```html
<script src="https://apis.google.com/js/api.js"/>
<script type="text/javascript">
// This will download the auth2 library.
gapi.load('client:auth2');
</script>
```

**Comment by RyanCavanaugh** [comment]
If it's not documented, I'm extremely hesitant to add it to the .d.ts file. Is there other evidence that this is intended to be used by external callers?

**Comment by trshafer** [comment]
No, there is not. :(

**Comment by flawless2011** [comment]
Based on lack of documentation supporting this as a public interface, can we close this PR?

**Pull request closed without merging**
