### PR TITLE
add better curry

### PR DESCRIPTION
**Pull request by pocesar**
A question, is it possible to return the hinted function return value and apply to the OriginalFunctionReminder<T>? Like:

``` typescript
f('1', 2) === '3'; // should fail, but works, because the original function returns a number
```

### CODE REVIEW

**Comment by vvakame** [comment]
*better-curry/better-curry.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/better-curry
  * http://bower.io/search/?q=better-curry
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (better-curry/better-curry-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
http://goo.gl/dVQB7w ?

**Comment by pocesar** [comment]
so, it would need a redeclaration of the new function instead? seems it can't be done using the typings, so just go ahead and merge :)

**Comment by vvakame** [comment]
@pocesar thanks mate!

**Pull request merged**
