### PR TITLE
Add missing property to DocumentToObjectOptions

### PR DESCRIPTION
**Pull request by niuware**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://mongoosejs.com/docs/api.html#document_Document-toObject>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by jendrikw** [comment]
Could you please add a simple test for this? Just to make sure it won't break in the future.

**Review by jendrikw — CHANGES_REQUESTED** [review]
Could you please add a simple test for this? Just to make sure it won't break in the future.

**Comment by niuware** [comment]
> Could you please add a simple test for this? Just to make sure it won't break in the future.

I've just added a sample test in the *document* section of the tests file.

**Review by jendrikw — APPROVED** [review]
That looks great, thank you very much!

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
