### PR TITLE
[three] r153

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/three-types/three-ts-types/issues/476
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. BoxBufferGeometry
1. CapsuleBufferGeometry
1. CircleBufferGeometry
1. ConeBufferGeometry
1. CylinderBufferGeometry

<details>
<summary>as well as these 14 other properties...</summary>
<p>DodecahedronBufferGeometry, ExtrudeBufferGeometry, IcosahedronBufferGeometry, LatheBufferGeometry, OctahedronBufferGeometry, PlaneBufferGeometry, PolyhedronBufferGeometry, RingBufferGeometry, ShapeBufferGeometry, SphereBufferGeometry, TetrahedronBufferGeometry, TorusBufferGeometry, TorusKnotBufferGeometry, TubeBufferGeometry</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c9e69e469c359e4530f75d49a9707e7ab7c1b903
</p>

**Review by joshuaellis — APPROVED** [review]
amazing as always ✨

**Comment by gloriousjob** [comment]
The following files seem to be missing from this merge: https://github.com/mrdoob/three.js/pull/26102/files

I'm wondering if this would work:
OutputPass.d.ts:
```
import { ShaderMaterial } from '../../../src/Three';
import { ToneMapping } from '../../../src/constants';

import { Pass, FullScreenQuad } from './Pass';

export class OutputPass extends Pass {
    constructor(toneMapping: ToneMapping, toneMappingExposure: number);
    uniforms: object;
    material: ShaderMaterial;
    fsQuad: FullScreenQuad;
    toneMapping: ToneMapping;
    toneMappingExposure: number;
}
```

OutputShader.d.ts:
```
import { IUniform } from '../../../src/Three';

export const OutputShader: {
    uniforms: {
        tDiffuse: IUniform;
	toneMappingExposure: IUniform;
    };
    vertexShader: string;
    fragmentShader: string;
};
```

**Comment by Methuselah96** [comment]
Hey @gloriousjob!

We do not have the capacity to keep up with types for the `examples` directory in each release (see https://github.com/three-types/three-ts-types#priorities-and-goals). However we definitely appreciate contributions to add those. Can you create a PR against https://github.com/three-types/three-ts-types to add these types?

**Comment by Methuselah96** [comment]
@gloriousjob I actually already ran into a situation where I need `OutputPass`. I've created https://github.com/three-types/three-ts-types/pull/512 with your changes and will get them included in the next release after this, which should be right on the heels of this release.

**Comment by ericbroberic** [comment]
@Methuselah96 I'm not sure the proper place to mention this, but looks like this PR https://github.com/mrdoob/three.js/pull/26023 added `quickLookCompatible` as an optional parameter to `parse` and I don't see it here, or in `three-ts-types`. Apologies if I'm missing something.

**Comment by ericbroberic** [comment]
I realize that it is in the `jsm` module, and does not get updated typically, however, the Model Viewer project uses TypeScript, and will need to turn that flag on in order to support QuickLook AR.

**Comment by Methuselah96** [comment]
Hey @ericbroberic!

Yes, if you could create a PR in `three-ts-types`, that would be great. We'll get it out with the next release.

**Review by navya9singh — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Pull request merged**
