### PR TITLE
[@types/elasticsearch] hits.total is now an object in the search response

### PR DESCRIPTION
**Pull request by vietbui**
Breaking change introduced by Elasticsearch 7.0: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#hits-total-now-object-search-response

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#hits-total-now-object-search-response
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by dasdachs — CHANGES_REQUESTED** [review]
Thanks for that! As far as I understand it defaults to an object, but can be if you add `rest_total_hits_as_int=true` in the search params. Right? Could you update you PR to account for that.

Reference: [ElasticNode API for MSearch](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_msearch)

**Comment by vietbui** [comment]
@dasdachs Thanks for the review. I definitely missed that in the documentation. This is ready to be reviewed again. By the way I have a question:
- What's the level of testing do we expect for this?
- Regarding to the params, I see a mix usage of camel case and snake case time to time. E.g. in MSearchParams interface we have `search_type` and `maxConcurrentSearches`. I guess that we'll use camel case moving forward. However there's no attempt fix up existing snake case params as it'll create breaking change. Is my assumption correct?

Thanks again.

**Review by dasdachs — APPROVED** [review]
Thanks for the follow up!

**Comment by dasdachs** [comment]
@vietbui I am relatively new to the project, so if any of the more senior contributes jump in and expand or correct my answer, I would be 

> What's the level of testing do we expect for this?

TBH I do not know. 

> Regarding to the params, I see a mix usage of camel case and snake case

For now, yes, we should leave it as it is. One solution could be to duplicate the types or interface properties and slowly transition to a unified camelCase naming conventions. One that does not force us to disable linters for certain lines and modules :)

Maybe ES 8.0 will be a good point to do some breaking changes. What are you thoughts on that?

**Review by rbuckton — CHANGES_REQUESTED** [review]
Given this is a major version change as well as a breaking change, it might make sense to create a copy of the current definitions in a `v5` subfolder following the guidance in the Readme in the project root.

**Comment by qdelettre** [comment]
@rbuckton That's not really a breaking until elastic 8.0.0, because there is an option that enable users to still get it not as an object ([cf commit message ](https://github.com/elastic/elasticsearch/pull/35849)) . So the types today are not right, this MR is totally valid until ES 8.0 imo.

**Pull request closed without merging**
