### PR TITLE
update plotly.js typing

### PR DESCRIPTION
**Pull request by jonfreedman**
- add missing event handlers from https://github.com/plotly/react-plotly.js/#event-handler-props
- add addFrames / deleteFrames functions (see https://plot.ly/javascript/animations)
- use Font interface in ScatterMarker.colorbar
- change Font.color type from string to Color
- fix 'common mistakes': tabs to spaces

### CODE REVIEW

**Review by taoqf — COMMENTED** [review]
Please use tab

**Comment by jonfreedman** [comment]
Sure, I've fixed the indentation everywhere and updated tslint.json to require 1-tab indentation

**Review by jonfreedman — COMMENTED** [review]
space indenting will now cause the linting to fail

**Review by taoqf — APPROVED** [review]
Thanks

**Pull request merged**
