### PR TITLE
[@types/node] Http2ServerResponse extends Stream

### PR DESCRIPTION
**Pull request by trivikr**
This was fixed in newer versions in #33527 but got missed in < v10
Http2ServerResponse extended Stream since it was introduced in v8.4.0 ([code](https://github.com/nodejs/node/blob/f70261fb3089b8acf5f68584ef0285a1c11f54fd/lib/internal/http2/compat.js#L427))

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/f70261fb3089b8acf5f68584ef0285a1c11f54fd/lib/internal/http2/compat.js#L427

### CODE REVIEW

**Review by Flarna — APPROVED** [review]
Usually it's not needed to adapt EOL versions like Node.Js 9 but it's no problem to do it.

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Test pls

**Comment by trivikr** [comment]
@SimonSchick Is there a procedure to add tests for extends?
I don't see type checks in existing http2 tests https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/test/http2.ts

**Comment by SimonSchick** [comment]
Just add something that ensures it extends stream.

**Comment by trivikr** [comment]
@SimonSchick I don't think it's necessary in this PR as:
* none of the derived classes are tested for type of base class in http2 tests
* this is a bug in @types/node < v10 and is already fixed in v11/v12

**Review by SimonSchick — APPROVED** [review]
🤷‍♂

**Pull request merged**
