### PR TITLE
Fix bad references

### PR DESCRIPTION
**Pull request by jakebailey**
This fixes a bunch of bad references discovered by my improved reference/import checker in https://github.com/microsoft/DefinitelyTyped-tools/pull/788.

### CODE REVIEW

**Comment by jakebailey** [comment]
Ah, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66197 forgot to change ts5.0

**Review by lqxdave — APPROVED** [review]

**Review by DavidKDeutsch — APPROVED** [review]

**Comment by jakebailey** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67267 should unblock this.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## rangy ([<kbd>unpkg</kbd>](https://unpkg.com/browse/rangy@latest/))
was missing the following properties:
1. version
1. isBrowser
1. util
1. features
1. modules

<details>
<summary>as well as these 1 other properties...</summary>
<p>config</p>
</details>

## react-is ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-is@latest/))
was missing the following properties:
1. SuspenseList
1. isConcurrentMode
1. isSuspenseList
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 165eb356dd4e30fc535b5b18a0a61137ad5ae340
</p>

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
Ready to merge

**Comment by sandersn** [comment]
This breaks publishing because OTHER_FILES entries from several of these projects are no longer needed, and we're currently strict about not having reachable files in OTHER_FILES.

A fix should be easy so I'll get started on that.

**Comment by jakebailey** [comment]
Uh, why didn't the PR fail? Is this still just OTHER_FILES being broken?

**Pull request merged**
