### PR TITLE
Added definitions for auto-launch package

### PR DESCRIPTION
**Pull request by rhysd**
Project page is here.

https://github.com/Teamwork/node-auto-launch

> Launch node-webkit apps at login (mac & windows)

### CODE REVIEW

**Comment by vvakame** [comment]
*auto-launch/auto-launch.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/auto-launch
  * http://bower.io/search/?q=auto-launch
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (auto-launch/auto-launch-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@rhysd thanks mate!

**Comment by rhysd** [comment]
Thanks!

> pass the Travic-CI test?

(U'ω')。o（Your automatic comment seems to contain misspell...）

**Comment by vvakame** [comment]
oh, thanks!

**Pull request merged**
