### PR TITLE
[webpack] add module federation plugin

### PR DESCRIPTION
**Pull request by zacnomore**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://webpack.js.org/concepts/module-federation/#modulefederationplugin-high-level>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I attempted to run linting and testing but it bailed with the following error:
```
../uglify-js/index.d.ts(9,30): error TS7016: Could not find a declaration file for module 'source-map'. '/home/zac/_dev/DefinitelyTyped/node_modules/source-map/source-map.js' implicitly has an 'any' type.
```

My addition is on 2177, the other changes are from running prettier.

Addresses #45037

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## webpack ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpack@latest/))
was missing the following properties:
1. WebpackOptionsDefaulter
1. WebpackOptionsApply
1. NodeEnvironmentPlugin
1. validate
1. validateSchema

<details>
<summary>as well as these 6 other properties...</summary>
<p>WebpackOptionsValidationError, dependencies, web, webworker, node, util</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fe10cec6f0bdd7e77560a7fffa52d0aaee123508
</p>

**Comment by ofhouse** [comment]
Hi,

thanks for submitting the PR, two points here:

1. It is always a good idea not change the formatting of a file when submitting a PR because it makes it difficult to spot the real changes. So disabling the auto-formatter in your code editor or just committing the lines you changed would make a review a lot easier.

2. Module federation is a feature of the upcoming Webpack v5 release. The `@types/webapck` package only covers the Webpack v1-v4 releases because webpack v5 brings its own type declarations by default (So you don't need to install `@types/webpack` to get types for the `webpack@next` npm package).

Please note that the current Webpack documentation https://webpack.js.org/concepts/ already points to the upcoming v5 release and I have no information that the Webpack team plans to backport this feature to v4.

So sadly I have to vote to close this PR.

**Comment by zacnomore** [comment]
No worries, glad I could learn something from this!
Would it have been better to make 2 commits or to just not commit the formatting at all? I had it separate and then I squashed it.
Is there anything to be done for the issue or should it be closed?

Thanks for the info!

**Comment by ofhouse** [comment]
Hi, glad you are not feeling rejected but took the opportunity to learn from this issue 👍

Changing formatting is a difficult topic on code reviews:
1. Yes, generally I would recommend to split the formatting (if it affects code lines that are not part of the main issue) into a separate commit
2. It can be also useful to create a separate PR to change the formatting so that reviewer does not face the dilemma that she has to decide whether the contribution is worth to change the whole formatting
3. Generally speaking I would recommend not to fix formatting issues in repositories where I am not the code owner.
This can be hard sometimes but fixing formatting issues can easily affect other open PRs and should therefore reviewed and merged in a small timeframe to avoid merge conflicts.

You can close it by yourself or it will be automatically closed by a code owner in the next 2 weeks.

**Pull request closed without merging**
