### PR TITLE
aws-lambda - Wrap types and interfaces inside a namespace.

### PR DESCRIPTION
**Pull request by yamafaktory**
This will fix errors like `[ts] Default export of the module has or is using private name 'APIGatewayEvent'` when trying to use them.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.

Let's say we have a file where we want to export a default handler function. This function takes a context of type `AWSLambda.Context` as third argument:

```js
export default handler(
  async (
    request: any,
    response: any,
    context: AWSLambda.Context
) => {...}
```

TypeScript will complain about the export of a private name:

```js
[ts] Default export of the module has or is using private name 'APIGatewayEvent'
```

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
They actually already are exported. `const x: AWSLambda.APIGatewayEventRequestContext = null!;` works. The `export` keyword is implied.

**Comment by andy-ms** [comment]
We do have a lint rule for always writing `export` explicitly, but it looks like this package wasn't linted before. #23167

**Comment by yamafaktory** [comment]
@andy-ms Thanks a ton for your PR! I've seen that you're now exporting all the interfaces. However, even after bumping up the `@types/aws-lambda`'s version in my repository (a private one), I'm still facing the same issue:

```sh
[ts] Default export of the module has or is using private name 'APIGatewayEvent'.
[ts] Default export of the module has or is using private name 'Context'.
```
Maybe related to some wrong settings locally... I think we can close that PR anyway.

**Comment by andy-ms** [comment]
@yamafaktory That sounds like a different error. The code you are using probably implicitly uses that type but doesn't have an explicit import of the type, so we can't emit a `.d.ts` file unless you add an explicit import. Let me know if that's the case, or if the error turns out to be something else.

**Comment by yamafaktory** [comment]
@andy-ms Oh, we are not explicitly importing! If we do so then we get:
 
```sh
Cannot import type declaration files. Consider importing 'aws-lambda' instead of '@types/aws-lambda'. 
```

Which is not something we actually want to do...

**Comment by andy-ms** [comment]
> Which is not something we actually want to do...

Why not? If the only things you import are types then the import from 'aws-lambda' won't be in the generated code.

**Comment by yamafaktory** [comment]
Good point, except that `@type/aws-lambda` are just type definitions for AWS Lambda (http://docs.aws.amazon.com/lambda), which is not available as an npm package and thus can't be explicitly imported... (not to be confused with something published as `aws-lambda` on npm!)

**Comment by andy-ms** [comment]
It can! Because we will resolve an import of `aws-lambda` to `@types/aws-lambda`, and then as long as only types are imported, there will be no import in the output `.js`.

**Comment by yamafaktory** [comment]
Thanks a lot @andy-ms for the clarification 👍 ! It works like a charm!

I was absolutely not aware of that behavior. I think many people can potentially be confused by this, as in the first place having an import will be seen as code injection too.

Correct me if I'm wrong, but I haven't seen it mentioned in any TS documentation (I've checked it again in the handbook). Would be awesome to have that specified!

I'm closing the PR as everything is available.

**Comment by andy-ms** [comment]
Search for "elision" at https://www.typescriptlang.org/docs/handbook/modules.html -- granted it's kind of buried since it's in the "Advanced Loading Scenarios" seciton.

**Pull request closed without merging**
