### PR TITLE
Node: specify `UnhandledRejectionListener` `reason` param type

### PR DESCRIPTION
**Pull request by OliverJAsh**
I originally proposed this change in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24417. However, I was [asked to wait until we release the next major version](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24417#discussion_r175940818), so we can avoid making a breaking change in a patch release.

Whilst I was waiting, that PR was closed by the bot. I was [asked to open a new PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24417#issuecomment-382201417).

I would still like to make this change. However, I don't know when it can be merged—it seems we need to be strategic about when breaking changes such as this are merged, so they form a new major version. There must be other PRs which contain breaking changes—how are they being managed?

/cc @RyanCavanaugh @Flarna @ajafff 

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: * https://nodejs.org/api/process.html#process_event_unhandledrejection
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Build failure seemingly has nothing to do with this change:

``` 
Error in ledgerhq__hw-transport
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/ledgerhq__hw-transport/ledgerhq__hw-transport-tests.ts:6:1
ERROR: 6:1  expect  Expected type to be:
  Promise<ReadonlyArray<string>>
got:
  Promise<readonly string[]>
```

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/489603177#L4378

**Comment by Flarna** [comment]
Regarding breaking changes and major versions: As far as I can remember there is/was some issue in this repo where this was discussed (maybe #25677) and the result was mostly that versions of types are not following semver.
Even if you wait for a new major release of node typings (refs: #32771) you may break usercode as all type definitions in this repo here refer to the latest version of node, not 10.x or 8.x.

Your change may break something and it may result in an issue like #29674. It may result in a revert or people understand and adapt their code. Some may be even happy that they found a bug by this, others may switch to a fixed version of @types/node.

**Comment by OliverJAsh** [comment]
Thanks @Flarna. In that case, this should be good to merge once reviewed?

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
@OliverJAsh from my point of view yes but other may have another opinion.

Regarding the unrelated CI fail: should be fixed via #32710

**Comment by minestarks** [comment]
@RyanCavanaugh I'm happy to take this, breaking or not. What's your opinion? (Node 10 is still pretty new and waiting until the next major version is going to turn this into a never ending quest)

**Comment by Flarna** [comment]
@minestarks Node 10 is not new, there is already Node 11 out since a few month and Node 12 is coming in a few. Types for Node 11 are currently done in #32878

**Comment by minestarks** [comment]
@Flarna great thanks for the pointer - @OliverJAsh  can we roll this change into #32878 ?

**Comment by OliverJAsh** [comment]
@minestarks Go ahead! Need anything from me?

**Comment by minestarks** [comment]
@OliverJAsh oops sorry I didn't mean to overpromise -- I wasn't proposing to do it. My suggestion was for you to work with @SimonSchick to see if he would take this into his v11 changes -- or just retarget these changes immediately once that PR goes in (looks like the tests are failing so it might be some time). Does that work for you?

Hopefully that would assuage any breaking change concerns.

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Actually, this change is invalid, this should be `any` or `unknown`.

```
> void(process.on('unhandledRejection', (reason, promise) => console.log('reason:', reason, 'promise', promise)))
undefined
> void(Promise.reject(123))
undefined
> reason: 123 promise Promise {
  <rejected> 123,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
```

**Comment by minestarks** [comment]
@OliverJAsh OK I just merged the node v11 change so this is a good time to take this change 😃 

@SimonSchick `unknown` would work too (would impose a TS 3.0 dependency) but I don't quite see why the current version is wrong. In your example `123` is assignable to `{}`.

**Comment by SimonSchick** [comment]
`{}` usually implies an object context, `any` is more accurate than `{}` imo.

**Comment by OliverJAsh** [comment]
@SimonSchick See my previous comments about why `any` is a bad choice:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24417#discussion_r175934603
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24417#discussion_r175935505

`{}` is like a poor man's `unknown`. (Even TypeScript itself uses it to represent "unknown" when a generic can't be inferred.)

**Comment by minestarks** [comment]
I do agree the current change is preferable to `any` for stronger type checking - `{}` doesn't necessarily mean object, it's just a type with no members.

I'm ready to merge this unless there are strong objections.

**Comment by OliverJAsh** [comment]
Please can someone here approve this PR before it's closed by the bot? The requested changes were invalid: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32835#issuecomment-462671097.

/cc @SimonSchick @typescript-bot

**Comment by OliverJAsh** [comment]
😢 This is the second time I've had this PR closed. Third time lucky…

**Comment by OliverJAsh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33189

**Comment by minestarks** [comment]
@OliverJAsh I reopened it.

**Comment by OliverJAsh** [comment]
Oh, I didn't know you could do that! I've re-opened another PR, so I guess either can be merged now. Thanks!

**Pull request closed without merging**
