### PR TITLE
Replace TSD with Typings

### PR DESCRIPTION
**Pull request by knpwrs**
TSD has been deprecated in favor of Typings.

### CODE REVIEW

**Comment by vvakame** [comment]
@DefinitelyTyped/contributors Do you know anyone?

**Comment by johnnyreilly** [comment]
It has as I understand - @blakeembrey can say more. Check out https://github.com/typings/typings

**Comment by blakeembrey** [comment]
It is, see https://github.com/DefinitelyTyped/tsd/issues/269 - it's effectively EOL (has been for a while honestly) and I've moved on to maintaining Typings (which I believe is more scalable long-term).

**Comment by mhegazy** [comment]
Already addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9493. closing.

**Pull request closed without merging**
