### PR TITLE
[types-2.0] csv-parse: Strict return type of stream read to string[] rather than any.

### PR DESCRIPTION
**Pull request by aleung**
``` typescript
const parser = parse();
parser.on('readable', () => {
  let record: any;    // <-- it should be string[]
  while (record = parser.read()) {
    // ...
  }
});
```

The Q&A on StackOverflow: http://stackoverflow.com/questions/39664513/how-to-declare-a-stream-like-interface-in-typescript

### CODE REVIEW

**Review by DavidM77 — COMMENTED** [review]
I'm not really clear what value this adds.

In the change to the test, the type of the parsed data is narrowed, which in the specific case of the data and options used is correct, but in general is incorrect.

The change to the .d.ts file seems unrelated to this, and as far as I can tell will have no actual effect on the type of the read function or hover tips presented.

**Comment by aleung** [comment]
@DavidM77 The change to the .d.ts file is to fix the error when assigning return value of `read` to a `string[]` type variable. Before change, you have to define record to be `any` type.

``` typescript
let record: string[];   // <-- error TS2322: Type 'string | Buffer' is not assignable to type 'string[]'
record = parser.read();
```

The change to test case is to align with the .d.ts file.

**Comment by DavidM77** [comment]
👍 This PR does correctly allow types for record other than any.

I'm still not clear why `any & string[]` was chosen instead of `any | string[]` but it seems to reduce to any in practice anyway.

**Comment by aleung** [comment]
Test on TypeScript 2.0.3, `any & string[]` is `any`, `any | string[]` is `any` as well. It seems that the type intersection is unable to narrow the type to `string[]`.

**Comment by DavidM77** [comment]
The following example is also correct. 

```
import * as parse from "csv-parse"

const parser = parse({auto_parse: true, columns: true});
parser.on('readable', () => {
  let record: {tool: string, version: number};    
  while (record = parser.read()) {
    console.log(record);   // logs { tool: 'typescript', version: 2 }
  }
});
parser.write("tool,version\r\ntypescript,2.0");
parser.end();
```

Here the correct type for record is `{tool: string, version: number}`

Therefore to me the technically correct return type for parser.read() is `any`.  I could possibly see any | string[] as a hint that the most common type is string[], but I would consider any & string[] an incorrect hint that  every return type will be string[] with something extra mixed in.

**Pull request merged**
