### PR TITLE
Update types for @rails/activestorage v7.0

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/rails/rails/blob/v7.0.0/activestorage/app/javascript/activestorage/direct_upload.js#L8-L15
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## rails__activestorage ([<kbd>unpkg</kbd>](https://unpkg.com/browse/rails__activestorage@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'rails__activestorage'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. hash
1. hashBinary
1. ArrayBuffer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2dcdca6a4ab64db598e15822e50db589a9ebb700
</p>

**Comment by AlfonsoUceda** [comment]
@imustafin is there anything else I can do for this PR?

**Review by imustafin — APPROVED** [review]
LGTM

**Comment by AlfonsoUceda** [comment]
Ready to merge

**Pull request merged**
