### PR TITLE
Update underscore.d.ts

### PR DESCRIPTION
**Pull request by arueckle**
missing declaration for wrapped.pick

### CODE REVIEW

**Comment by vvakame** [comment]
@flashandy thank you your contributions.
sorry, I can't found your use case in the document.
Do you have any pointer?

**Comment by flashandy** [comment]
a use case would be
_({'a':2,'b':3, 'c':4}).pick(['a', 'b'])

**Comment by vvakame** [comment]
@borisyankov @jbaldwin could you review this PR?

**Comment by arueckle** [comment]
Types were changed as discussed above

**Comment by vvakame** [comment]
@jbaldwin thanks!
@arueckle thanks mate!

**Pull request merged**
