### PR TITLE
Unmangle scoped package names

### PR DESCRIPTION
**Pull request by jablko**
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## entria__relay-experimental ([<kbd>unpkg</kbd>](https://unpkg.com/browse/entria__relay-experimental@latest/))
was missing the following properties:
1. MatchContainer
1. ProfilerContext
1. useBlockingPaginationFragment
## solid__react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/solid__react@latest/))
was missing the following properties:
1. useLiveUpdate
1. withWebId
1. evaluateExpressions
1. evaluateList
1. UpdateContext

<details>
<summary>as well as these 5 other properties...</summary>
<p>useLiveUpdate, withWebId, evaluateExpressions, evaluateList, UpdateContext</p>
</details>

## webscopeio__react-textarea-autocomplete ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webscopeio__react-textarea-autocomplete@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'webscopeio__react-textarea-autocomplete'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. defaultProps
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bbe5088944709641378dfad862d17e1be5645904
</p>

**Comment by peterblazejewicz** [comment]
@jablko  Jack, should I take changes for a relevant package (blazor/interop) into separate PR? thx!

**Comment by jablko** [comment]
@peterblazejewicz :+1: Thank you!

**Comment by orta** [comment]
OK, that's all of them - thanks for the individual PRs @jablko

**Pull request closed without merging**
