### PR TITLE
[redux-form] Allow the "reduxForm()" function to wrap stateless functional components

### PR DESCRIPTION
**Pull request by begincalendar**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://redux-form.com/6.5.0/examples/simple/>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

# Description

Fix for #14767.

### CODE REVIEW

**Comment by begincalendar** [comment]
@CarsonF

**Review by CarsonF — APPROVED** [review]

**Comment by waynebrantley** [comment]
@CarsonF dt-bot said there was a problem - has this been resolved and will this pull request be accepted at some point?   I ran into same issue (that you have now fixed)

**Comment by CarsonF** [comment]
I'm not sure what the problem is with the definition header. I don't even know why it's looking at that file. It should be looking at `redux-form/index.d.ts`

**Comment by waynebrantley** [comment]
I saw other pulls with the exact same issue on other projects, but they seemed to be merged anyway?  Is it stopping the pull request merge?

**Comment by begincalendar** [comment]
Is the source code for the dt-bot, open? i.e. Can we find out why it's doing that?

On the surface it looks as though it's caused by the fact it's looking at all `*.d.ts` files that have changed and is complaining because the one that has changed (`reduxForm.d.ts`) doesn't have a comments header like `index.d.ts` does.

As for why this (and the other PRs I created) hasn't/heaven't been merged yet, maybe it's because all of those checkboxes above need to be checked? E.g. I didn't tick "Run npm run lint package-name if a tslint.json is present.", because it's not applicable, but the clause does say "if", so maybe those are supposed to be ticked before PRs can be merged.

**Comment by waynebrantley** [comment]
@CarsonF I cannot mention you when submitting an issue for some reason.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15026

Additionally, the 'test' example typescript file you have in this repo is the best way to figure out how to use your typings and that needs to cover more scenarios.
If there is a way we can discuss some of these things in an easier fashion, that would be great.

**Comment by minestarks** [comment]
The PR is OK, just took us a while to get here. Sorry for the delay guys...

**Pull request merged**
