### PR TITLE
fixing mailparser to, cc, bcc types

### PR DESCRIPTION
**Pull request by khshah6**
While working on email parsing failures recently, one of the problems uncovered was that the mailparser typings are inaccurate.

Specifically, the `to`, `cc`, and `bcc` fields are typed as optional `AddressObject`, but at run time they are actually optional `AddressObject | AddressObject[]`.

source code:
```
import { simpleParser } from 'mailparser';
import * as fs from 'fs';
import * as process from 'process';
import * as util from 'util';
const readFileAsync = util.promisify(fs.readFile);
const testFilename = `${process.cwd()}/test/fixtures/testFile.txt`;

      it(`simple test`, async () => {
        const content = (await readFileAsync(testFilename)).toString();
        const parsedMail = await simpleParser(content);
        if (Array.isArray(parsedMail.to)) {
          parsedMail.to.map((a, idx) => {
            console.log(`Object at index ${idx}:\n ${JSON.stringify(a)} \n\n`);
          });
        };
      })
```
console:
```
    Object at index 0:
     {"value":[{"address":"tenders@automail.x.com","name":""}],"html":"<span class=\"mp_address_group\"><a href=\"mailto:tenders@automail.x.com\" class=\"mp_address_email\">tenders@automail.x.com</a></span>","text":"tenders@automail.x.com"}

    Object at index 1:
     {"value":[{"address":"anotheraddress@automail.x.com","name":""}],"html":"<span class=\"mp_address_group\"><a href=\"mailto:anotheraddress@automail.x.com\" class=\"mp_address_email\">anotheraddress@automail.x.com</a></span>","text":"anotheraddress@automail.x.com"}

    Object at index 2:
     {"value":[{"address":"thirdaddress@automail.x.com","name":""}],"html":"<span class=\"mp_address_group\"><a href=\"mailto:thirdaddress@automail.x.com\" class=\"mp_address_email\">thirdaddress@automail.x.com</a></span>","text":"thirdaddress@automail.x.com"}
```

Incrementing major version of mailparser typings since consuming new typings may result in initial compile errors.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Example at top
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@khshah6 can you point the source code (from actual repo)? I'm getting always a single object (with multiple address for 'to', etc fields), so like:
```json
'{"value":[{"address":"andris+123@kreata.ee","name":"Andris Reinman"},{"address":"andris.reinman@gmail.com","name":""}],...
```

**Review by khshah6 — COMMENTED** [review]
@peterblazejewicz

Sure! The repo is private, but you can run the source code and set `testFile.txt` to 
```
Subject: Test
To: tenders@automail.x.com
To: anotheraddress@automail.x.com
To: thirdaddress@automail.x.com
Content-Type: multipart/mixed; boundary="0000000000004556ed05825c8a88"
```

**Comment by peterblazejewicz** [comment]
I'm not aware about this format, I was under impression this is only possible as:
```
"To:" address-list CRLF
```
where address list is a single or comma separated addresses.
https://tools.ietf.org/html/rfc2822#section-3.4.1
(min: 0, max: 1 occurences)

**Review by orta — APPROVED** [review]
I'm a little mixed on this PR, but I think I favour merging this because it represents what the JS could look like even if it is (probably) a bad input. I'm going to give it a green review, and which gives @khshah6 the choice on finally merging

**Comment by peterblazejewicz** [comment]
Ready to merge

**Comment by simllll** [comment]
I just stumpled upon this, and it seems the types are not correct in my case:
value has an array, but the type says it is an AddressObject ..?

**Comment by karlhorky** [comment]
@andris9 what are your thoughts on this change to the types?

Should `to`, `cc` and `bcc` be possibly arrays?

Or is this a bug in `mailparser` itself that it returns an array for [this malformed input](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50744#pullrequestreview-575044618)?

**Pull request merged**
