### PR TITLE
[@types/react-scroll] add type for ScrollLink

### PR DESCRIPTION
**Pull request by jmtoung**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/fisshy/react-scroll/blob/ee167423739ecc50d161ab61ac74bab0905d1c20/modules/mixins/scroll-link.js>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
For me, it LGTM!
@jmtoung thx for the change
Probably after running Prettier, the amount of changes impacted ease of reviews.
Here is isloated @jmtoung's change:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44493/commits/53176f4ed428371945152d8e406f48b60e7211c7

**Comment by jmtoung** [comment]
> For me, it LGTM!
> @jmtoung thx for the change
> Probably after running Prettier, the amount of changes impacted ease of reviews.
> Here is isloated @jmtoung's change:
> [53176f4](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/53176f4ed428371945152d8e406f48b60e7211c7)

Hi Peter,

I actually submitted 3 changes recently. I noticed that when I ran `prettier`, a ton of files not related to the ones I was editing were changed as well. In order to make the revisions I was submitting easier to review, I made a separate one that just involved running `prettier` (I suspect the previous authors forgot to run prettier at some point).

Regarding your suggestion, do you want me to close this and move `prettier` changes not related to this immediate `ScrollLink` change here?

**Comment by peterblazejewicz** [comment]
This should be fine to have only that one. You've done right thing with focused commits as noted. Up to maintainers to merge this one. If someone objects merging two, you could just cherry-pick single commit from that branch to new branch and resubmit as separate PR. For now that's problematic to see your changes (3 different PRs covering same changes)

**Comment by jmtoung** [comment]
Close in favor of #44497

**Pull request closed without merging**
