### PR TITLE
feat: Enable not-needed.js to also remove package in attw.json

### PR DESCRIPTION
**Pull request by hkleungai**
`attw.json` should not be used to track no-longer-needed packages. This PR aims to enable `not-needed.js` to also help remove packages in `attw.json` file.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by jakebailey** [comment]
This PR also changes other things other than just modifying `attw`. Can you just add the code to modify `attw` and not change the import style, modify file reading/writing, etc?

**Comment by hkleungai** [comment]
Reverted unrelated changes.

**Review by jakebailey — APPROVED** [review]
Thanks.

**Comment by hkleungai** [comment]
Ready to merge

**Pull request merged**
