### PR TITLE
algoliasearch: Added "clickAnalytics" boolean option

### PR DESCRIPTION
**Pull request by kopertop**
The clickAnalytics definition allows us to track clicks using
"search-insights". See: https://www.algolia.com/doc/api-reference/api-parameters/clickAnalytics/

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.algolia.com/doc/api-reference/api-parameters/clickAnalytics/
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by samouss — APPROVED** [review]

**Review by neryortez — APPROVED** [review]

**Review by keichinger — CHANGES_REQUESTED** [review]
Hi @kopertop, thank you for your contribution!

One small thing before we're ready to go: Could you please update the `algoliasearch-test.ts` to include this property as well?

**Review by keichinger — APPROVED** [review]
Thank you!

**Comment by kopertop** [comment]
@keichinger I also updated the version numbers, was that OK?

**Comment by keichinger** [comment]
@kopertop yes, that should be fine. If the `clickAnalytics` option has been introduced in v3.30.1 of `algoliasearch` then it's even necessary/required to match this version.

**Comment by Haroenv** [comment]
The version for these is mostly irrelevant, since any search parameter will work with any version of Algoliasearch. The only thing it's useful for is for added functions. 

Since we require people to be on the latest version to get an SLA, this isn't too big of an issue either to port it to the correct version

**Pull request merged**
