### PR TITLE
Add query-string d.ts files

### PR DESCRIPTION
**Pull request by SamVerschueren**
Add the [query-string](https://github.com/sindresorhus/query-string) type definitions.

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1: (author)

**Comment by Strate** [comment]
I have a little more correct typings:

```
declare module "query-string" {
    type DataObject = { [name: string]: number | string | Array<number|string> }

    /**
     * Parse a query string into an object.
     * Leading ? or # are ignored, so you can pass location.search or location.hash directly.
     * @param str
     */
    export function parse(str: string): DataObject

    /**
     * Stringify an object into a query string, sorting the keys.
     *
     * @param obj
     */
    export function stringify(obj: DataObject): string

    /**
     * Extract a query string from a URL that can be passed into .parse().
     *
     * @param str
     */
    export function extract(str: string): string
}
```

**Comment by SamVerschueren** [comment]
@Strate You are correct, `Object` is not the correct type here but I don't think `DataObject` is a good definition here. Would go for

```js
declare module "query-string" {
    /**
     * Parse a query string into an object.
     * Leading ? or # are ignored, so you can pass location.search or location.hash directly.
     * @param str
     */
    export function parse(str: string): any;

    /**
     * Stringify an object into a query string, sorting the keys.
     *
     * @param obj
     */
    export function stringify(obj: any): string;

    /**
     * Extract a query string from a URL that can be passed into .parse().
     *
     * @param str
     */
    export function extract(str: string): string;
}
```

**Comment by Strate** [comment]
but why `any`? It is really not `any`, whhich cons do you see in `DataObject` type? Is there any case when not `DataObject` returns from `parse`?

**Comment by SamVerschueren** [comment]
Definitions aren't only used when transpiling, but also in code completion.

screen shot 2015-11-26 at 14 52 21
screen shot 2015-11-26 at 14 52 31

With your defintion, this is not possible:

```js
const parsed = qs.parse('?foo=bar');

console.log(parsed.foo);
// => Property 'foo' does not exist on type ...
```

**Comment by Strate** [comment]
It can be quickly workarounded with `parsed['foo']`. Btw, I can agree with `parse(str: string): any`, but I can not agree yet with `stringify(obj: any): string`. Because `query-string` can not operate with object with nested objects:
```js
qs.stringify({a: {a: "a"}})
// "a=%5Bobject%20Object%5D"
```
It can really operate only with a structure, described in `DataObject`.

P.S. You can define `parse` like this:
```typescript
function parse(str: string): DataObject | any
```

**Comment by vvakame** [comment]
It merged. please send a pull request other improvement if you have.

**Pull request merged**
