### PR TITLE
[nightwatchjs] Final type fixes for v2.x

### PR DESCRIPTION
**Pull request by garg3133**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## nightwatch ([<kbd>unpkg</kbd>](https://unpkg.com/browse/nightwatch@latest/))
was missing the following properties:
1. createClient
1. client
1. cli
1. runTests
1. CliRunner

<details>
<summary>as well as these 2 other properties...</summary>
<p>initClient, runner</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 66e3720cfbaf589fef298e1dd6370e1cd728bbff
</p>

**Comment by peterblazejewicz** [comment]
@garg3133 did you manage to get other owners attention? I mean here: maintainers do not know every package background story, would be nice to hear opinion here, thx!

**Comment by garg3133** [comment]
Hey @peterblazejewicz, starting with Nightwatch v3, we have migrated the types to the Nightwatch repository only and we'll be maintaining the types there moving on. So, as we are fixing the types for v3, this is an attempt to fix the same types for v2 as well (since many of the types here are not correct, and correcting those would help our v2 users).

So, all the commits that go in there are already being reviewed in the Nightwatch repository, and when I'm done I'll ask one of the owners to take one last look here and approve this PR.

**Review by vaibhavsingh97 — APPROVED** [review]

**Comment by garg3133** [comment]
Ready to merge

**Pull request merged**
