### PR TITLE
Added expandableRowScope to gridOptions.

### PR DESCRIPTION
**Pull request by nkovacic**
Added expandableRowScope to gridOptions.

### CODE REVIEW

**Comment by joeskeen** [comment]
@nkovacic This field isn't documented in the ui-grid API, but I did find mention of it in the tutorial (http://ui-grid.info/docs/#/tutorial/216_expandable_grid).  In the past, we have tried to keep definitions to documented fields and functions to avoid typing private or internal functionality.  Would you be willing to add this to the ui-grid documentation here: http://ui-grid.info/docs/#/api/ui.grid.expandable.api:GridOptions ?

**Comment by nkovacic** [comment]
Added the PR https://github.com/angular-ui/ui-grid/pull/5112

**Comment by mhegazy** [comment]
@nkovacic can you refresh this PR

**Comment by nkovacic** [comment]
My PR to ui-grid was merged to master, so the expandableRowScope as added to documentation. That should be enough for this PR to be merged to master.

**Comment by joeskeen** [comment]
Thanks for the PR to the documentation. Please fix the conflicts then ping me again.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
