### PR TITLE
Create koa-pug definitions

### PR DESCRIPTION
**Pull request by Xstoudi**

### CODE REVIEW

**Comment by Xstoudi** [comment]
Need help.

**Comment by andy-ms** [comment]
Tests are failing because of the line `/// <reference path="koa/koa.d.ts" />`. You should be able to just remove this line.
Also, looks like you will have lint errors. Run `npm run lint -- koa-pug`.

**Comment by Xstoudi** [comment]
`6:1    no-single-declare-module     File has only 1 module declaration — write it as an external module.`
Don't know how to do this without mess up the whole thing.

`13:13  unified-signatures           These overloads can be combined into one signature taking `?Pug.PugCtxOptions | ?boolean`.`
They can be combined, but if we do this, we loose the meaning of one of them.

**Comment by andy-ms** [comment]
`no-single-declare-module`: Just remove the `declare module` wrapper. Add the `export` keyword as necessary in front of declarations.
`unified-signatures`: Use `// tslint:disable-next-line:unified-signatures`.

**Comment by andy-ms** [comment]
Might be easier to use `npm run lint -- koa-pug` instead of waiting for travis to do it!

**Comment by Xstoudi** [comment]
Might be easier if there was a complete and up to date documentation.

**Comment by andy-ms** [comment]
All you need to do is `npm run lint -- koa-pug`. The pull request template mentions this.

**Pull request merged**
