### PR TITLE
lodash: Add _.conforms and _.conformsTo

### PR DESCRIPTION
**Pull request by Sheeo**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.
^ Above fails with a lot of errors already.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.4#conforms
- [-] Increase the version number in the header if appropriate.
- [-] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by Sheeo** [comment]
I don't know why the travis run is still using TS 2.0, I amended the header as described in the readme.

**Comment by andy-ms** [comment]
The other packages need header updates too. Should be fixed when #13994 is merged.

**Comment by DanielRosenwasser** [comment]
Thank you!

**Comment by tdietrich513** [comment]
Was the bump to version 2.1.0 really a minor version change? Getting compilation errors when @types/lodash@4.14.52 is included from typedoc@0.5.5 instead of @types/lodash@4.14.50 under typescript 2.0.10. - Duplicate identifier '_'.

**Comment by sinedied** [comment]
@tdietrich513 I also have an error with the latest update, was working correctly in the previous version:
```
Module '"/Users/noda/github/ng2-starter-kit/node_modules/@types/lodash/index"' has no exported member 'includes'.)
```

when using: `import { includes } from 'lodash';`

**Comment by Sheeo** [comment]
@tdietrich513 these type-declarations target Lodash 4.14 and the semantic version published is automatically updated by the DefinitelyTyped system. I don't know how or if we can specify a dependency on TypeScript 2.1 from the typings.

@DanielRosenwasser I imagine this is a common problem with type declarations -- is there a common solution? Do we just force peers to update to TS 2.1 when types for packages require such features to accurately type them, or is there a means of providing different versions of the typings for different compiler versions?

**Comment by tdietrich513** [comment]
@Sheeo It's a tricky situation. I'm not wise enough to suggest a solution.

**Pull request merged**
