### PR TITLE
Remove definitions for `helmet`

### PR DESCRIPTION
**Pull request by bensalilijames**
`helmet` started bundling its own types in 4.0.0, so this PR removes `helmet` from this repo.

I also cleaned up the types in `koa-helmet` as they included `featurePolicy` and `noCache`, which are not part of `helmet@4`.

Requires https://github.com/microsoft/DefinitelyTyped-tools/pull/139 to land first, otherwise tests won't pass.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by sant123 — CHANGES_REQUESTED** [review]
Please take a look at the unit test errors. Seems a package.json file is not allowed.

**Comment by benhjames** [comment]
Hi @sant123, this should resolve once microsoft/DefinitelyTyped-tools#139 lands. 👍

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## server ([<kbd>unpkg</kbd>](https://unpkg.com/browse/server@latest/))
was missing the following properties:
1. utils
1. plugins
1. utils
1. plugins
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8a56b13c362f61e3aa6934000bfa95589ac2f793
</p>

**Comment by elibarzilay** [comment]
@benhjames, @sant123: is it ok to merge now?

**Review by sant123 — APPROVED** [review]

**Pull request merged**
