### PR TITLE
Apply prettier formatting to react-relay

### PR DESCRIPTION
**Pull request by levibuzolic**
Many of the files in `react-relay` hasn't been auto-formatted by prettier. This PR applies the repo formatting rules to reduce any diffs in future contributions.

`npm run prettier -- --write types/react-relay/**/*.ts`

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] ~Test the change in your own code. (Compile and run.)~
- [ ] ~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-relay ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-relay@latest/))
was missing the following properties:
1. MutationTypes
1. RangeOperations
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3f581095f52c328846c6625737525268885afa8f
</p>

**Comment by maraisr** [comment]
not sure if there is a way to merge this w/o a version bump

**Review by maraisr — APPROVED** [review]
🚀

**Comment by levibuzolic** [comment]
ready to merge

**Review by maraisr — APPROVED** [review]

**Comment by maraisr** [comment]
ready to merge

**Comment by levibuzolic** [comment]
Ready to merge

**Pull request merged**
