### PR TITLE
[mapbox-gl] update to mapbox-gl 1.9

### PR DESCRIPTION
**Pull request by dmytro-gokun**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.9.0
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by dimitrilahaye** [comment]
Hi! I see in `SymbolLayout` that we only accept `number` for `symbol-sort-key` property, but according to the mapbox-gl documentation we should be able to use `Expression`. Could it be updated?

**Comment by dmytro-gokun** [comment]
@dimitrilahaye According to https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-sort-key only numbersare allowed

**Comment by dimitrilahaye** [comment]
wouah thanks for the fast answer. But what about data-driven?
image

**Comment by dmytro-gokun** [comment]
@dimitrilahaye Yep, it looks like it should work. Feel free to submit a PR and i'll review it quickly

**Comment by dimitrilahaye** [comment]
Sorry I've never worked on `@types` project and I'm not sure I just have to add `Expression` in the `SymbolLayout` definition 😅

**Comment by dmytro-gokun** [comment]
@dimitrilahaye Okay, this time i've created a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44076
But please consider doing it yourself next time. It is not that hard: https://github.com/DefinitelyTyped/DefinitelyTyped#edit-an-existing-package

**Comment by dimitrilahaye** [comment]
Thank you very much, be sure I will in the future!

**Pull request merged**
