### PR TITLE
add types for getSsoData's callback for auth0-js

### PR DESCRIPTION
**Pull request by erangakm**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js#L462
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## auth0-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/auth0-js@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'auth0-js'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. Request
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 524950cfb7da23fa0efe479913f6dd05fa9b0b6b
</p>

**Review by peterblazejewicz — CHANGES_REQUESTED** [review]
> - [x] Add or edit tests to reflect the change

can you amend the change? thx!

**Comment by erangakm** [comment]
@peterblazejewicz done

**Comment by erangakm** [comment]
@peterblazejewicz ping. not sure if I can test this reliably. also when you requested changes you meant that I remove the tick before ``Add or edit tests to reflect the change`` yes? if so I have done that.

**Comment by peterblazejewicz** [comment]
> @peterblazejewicz ping. not sure if I can test this reliably. also when you requested changes you meant that I remove the tick before `Add or edit tests to reflect the change` yes? if so I have done that.

I haven't used SSO with Auth0 (with Azure AD, yes), so I was not sure.
That's not very hard to provide a test though:
```ts
authentication.getSSOData((err, ssoData) => {
    if (err) return;
    if (ssoData.sso) {
        ssoData.sessionClients; // $ExpectType string[]
        ssoData.lastUsedClientID; // $ExpectType string
        ssoData.lastUsedUsername; // $ExpectType string
        ssoData.lastUsedConnection; // $ExpectType { name: string; strategy?: string; }
    } else {
        //
    }
```
https://auth0.com/docs/sso/legacy/single-page-apps#obtaining-the-sso-cookie-information
I"ll amend a tests later, 
Thanks!

**Review by peterblazejewicz — APPROVED** [review]

**Pull request merged**
