### PR TITLE
Added LayoutViewOption because the Layout can have additional regions in it.

### PR DESCRIPTION
**Pull request by sascha-sphw**
I added a new interface LayoutViewOption which provides the additional parameter "regions" which you can pass to the LayoutView.

### CODE REVIEW

**Comment by vvakame** [comment]
*marionette/marionette.d.ts*

to authors(@zhamid @nvivo @sventschui). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by Linowitch** [comment]
When will this be reviewed?

**Comment by Linowitch** [comment]
Hey there, just wanted to know the current status.

**Comment by nvivo** [comment]
For this and #4907  has been a some time since I don't use backbone and marionette, so I'm not able to review these requests.  My suggestion is to let it in,  since people using it currently will be more able to decide what is required.

**Comment by vvakame** [comment]
@nvivo okay, thanks!
@Linowitch thanks mate.

**Pull request merged**
