### PR TITLE
[cookie] cookie should be string | undefined

### PR DESCRIPTION
**Pull request by awareness481**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: see code example below
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

```ts
import { parse } from "cookie";

const cookie = parse("");
console.log(cookie["undefined-cookie"]); //undefined
```

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
IMO value is correct, assuming index signature has been used here:
```ts
console.log(cookie['undefined-cookie'] ?? 'no value');
```
https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures
the same applies to accessing lists with out of the bounds index.
Yes, it can be changed, but what's the story behind? What's the devex story behind this request?

**Comment by peterblazejewicz** [comment]
it's just enough to add 'protected' to fields you want to limit access to. Everything is public by defualt, no linting config changes required:
```diff
2015170d06 wip
diff --git a/types/svg-baker-runtime/src/browser-sprite.d.ts b/types/svg-baker-runtime/src/browser-sprite.d.ts
index c161444cff..756c983b8c 100644
--- a/types/svg-baker-runtime/src/browser-sprite.d.ts
+++ b/types/svg-baker-runtime/src/browser-sprite.d.ts
@@ -11,8 +11,8 @@ export default class BrowserSprite extends Sprite {
      * override
      */
     protected config: SpriteConfig & BrowserSpriteConfig;
-    public node: Element | null;
-    public isMounted: boolean;
+    node: Element | null;
+    isMounted: boolean;
 
     /**
      * override
@@ -21,30 +21,30 @@ export default class BrowserSprite extends Sprite {
      * @fires Events#SYMBOL_MOUNT
      * @return `true` - symbol was added, `false` - replaced
      */
-    public add(symbol: BrowserSpriteSymbol): boolean;
+    add(symbol: BrowserSpriteSymbol): boolean;
 
     /**
      * Attach to existing DOM node
      * @return attached DOM Element. null if node to attach not found.
      */
-    public attach(target: string | Element): Element | null;
+    attach(target: string | Element): Element | null;
 
     /**
      * @fires Events#MOUNT
      * @return rendered sprite node. null if mount node not found.
      */
-    public mount(target?: string, prepend?: boolean): Element | null;
+    mount(target?: string, prepend?: boolean): Element | null;
 
-    public render(): Element;
+    render(): Element;
 
     /**
      * Detach sprite from the DOM
      */
-    public unmount(): void;
+    unmount(): void;
 
     /**
      * Update URLs in sprite and usage elements
      * @return `true` - URLs was updated, `false` - sprite is not mounted
      */
-    public updateUrls(oldUrl: string, newUrl: string): boolean;
+    updateUrls(oldUrl: string, newUrl: string): boolean;
 }
diff --git a/types/svg-baker-runtime/src/browser-symbol.d.ts b/types/svg-baker-runtime/src/browser-symbol.d.ts
index fd7add366e..de9f4521b9 100644
--- a/types/svg-baker-runtime/src/browser-symbol.d.ts
+++ b/types/svg-baker-runtime/src/browser-symbol.d.ts
@@ -1,16 +1,16 @@
 import SpriteSymbol from './symbol';
 
 export default class BrowserSpriteSymbol extends SpriteSymbol {
-    public static createFromExistingNode(node: Element): BrowserSpriteSymbol;
+    static createFromExistingNode(node: Element): BrowserSpriteSymbol;
 
-    public isMounted: boolean;
+    isMounted: boolean;
 
-    public mount: (target: Element | string) => Element;
-    public render: () => Element;
-    public unmount: () => void;
+    mount: (target: Element | string) => Element;
+    render: () => Element;
+    unmount: () => void;
 
     /**
      * override
      */
-    public destroy: () => void;
+    destroy: () => void;
 }
diff --git a/types/svg-baker-runtime/src/sprite.d.ts b/types/svg-baker-runtime/src/sprite.d.ts
index e56fffb4c0..3615e25462 100644
--- a/types/svg-baker-runtime/src/sprite.d.ts
+++ b/types/svg-baker-runtime/src/sprite.d.ts
@@ -11,16 +11,16 @@ export default class Sprite {
      * Add new symbol. If symbol with the same id exists it will be replaced.
      * @return `true` - symbol was added, `false` - replaced
      */
-    public add(symbol: SpriteSymbol): boolean;
+    add(symbol: SpriteSymbol): boolean;
 
     /**
      * Remove symbol & destroy it
      * @return `true` - symbol was found & successfully destroyed, `false` - otherwise
      */
-    public remove: (id: string) => boolean;
-    public find: (id: string) => SpriteSymbol | null;
-    public has: (id: string) => boolean;
-    public stringify: () => string;
-    public toString: () => string;
-    public destroy: () => void;
+    remove: (id: string) => boolean;
+    find: (id: string) => SpriteSymbol | null;
+    has: (id: string) => boolean;
+    stringify: () => string;
+    toString: () => string;
+    destroy: () => void;
 }
diff --git a/types/svg-baker-runtime/src/symbol.d.ts b/types/svg-baker-runtime/src/symbol.d.ts
index 8b77c0f416..93e5a9d73c 100644
--- a/types/svg-baker-runtime/src/symbol.d.ts
+++ b/types/svg-baker-runtime/src/symbol.d.ts
@@ -1,11 +1,11 @@
 export default class SpriteSymbol {
-    public id: string;
-    public viewBox: string;
-    public content: string;
+    id: string;
+    viewBox: string;
+    content: string;
 
     constructor(cfg: { id: string; viewBox: string; content: string });
 
-    public stringify: () => string;
-    public toString: () => string;
-    public destroy: () => void;
+    stringify: () => string;
+    toString: () => string;
+    destroy: () => void;
 }
diff --git a/types/svg-baker-runtime/tslint.json b/types/svg-baker-runtime/tslint.json
index 73ba332809..2efa283002 100644
--- a/types/svg-baker-runtime/tslint.json
+++ b/types/svg-baker-runtime/tslint.json
@@ -1,6 +1,3 @@
 {
-    "extends": "@definitelytyped/dtslint/dt.json",
-    "rules": {
-        "member-access": false
-    }
+    "extends": "@definitelytyped/dtslint/dt.json"
 }
```
otherwise it's ready to go

**Comment by peterblazejewicz** [comment]
@awareness481 thx!

**Comment by awareness481** [comment]
This is caught by https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess thus the PR doesnt make sense. Sorry for the noise :pray:

**Pull request closed without merging**
