### PR TITLE
Update readInlineData for Relay 13

### PR DESCRIPTION
**Pull request by hanford**
When updating my application to the latest version of Relay, I noticed this key seems to have changed.

I don't have any context into why this change happened but my PR should be backwards compatible so new and old versions should work. 

Happy to make any changes if there is a better syntax to use or w/e!

https://github.com/facebook/relay/commit/0a487b60eb314c4241e25d5c1ad3cb2dbd2a65af#diff-d0d9a20b024e16640182011bb5dcdf14ecc667b5624eabe8e36d1a25730da2f7
https://github.com/facebook/relay/blob/e10dba54b46fc01bdf3b6b811853c6f2b3e565b6/packages/relay-runtime/store/readInlineData.js#L31

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Relay change](https://github.com/facebook/relay/commit/0a487b60eb314c4241e25d5c1ad3cb2dbd2a65af#diff-d0d9a20b024e16640182011bb5dcdf14ecc667b5624eabe8e36d1a25730da2f7)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by hanford** [comment]
Happy to do ` If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.` but don't know what/which header I'm supposed to update

**Comment by hanford** [comment]
Looking at the failed test...

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 18 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getRefetchMetadata, getPaginationMetadata, getPaginationVariables, getPendingOperationsForFragment, getValueAtPath</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 250572e0bfecfc3ba8975b717cefcccb63e43887
</p>

**Comment by alloy** [comment]
Thanks!

I’m inclined to just make the change in a non-backwards compatible manner and stay true to the upstream definitions https://github.com/facebook/relay/commit/0a487b60eb314c4241e25d5c1ad3cb2dbd2a65af#diff-d0d9a20b024e16640182011bb5dcdf14ecc667b5624eabe8e36d1a25730da2f7

People on older versions of Relay can pin their type dependency. If/when we care about further maintenance of older versions we can re-introduce it anyways.

To do so, bump the version in the header of the root index.d.ts file.

**Comment by maraisr** [comment]
There's another pr by Rob that does this.

**Comment by hanford** [comment]
Happy to close this out since someone else fixed 🙌

**Pull request closed without merging**
