### PR TITLE
[Mock-Require] - add declaration file for v2.0

### PR DESCRIPTION
**Pull request by supermacro**
Please fill in this template.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/boblauer/mock-require
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by gDelgado14** [comment]
Ermmm the Travis CI logs are a little vague. Not even sure if this is something to do with my changes.

**Comment by gDelgado14** [comment]
@andy-ms any suggestions on how to fix this? Sorry to bother .. this is the first time doing a big PR to definitely typed.

**Comment by andy-ms** [comment]
You would need to have this in the old `tsconfig.json`:
```json
"paths": {
    "mock-require": ["mock-require/v1"]
},
```
You could also just not create that directory if you won't be maintaining the v1 types any more.

**Comment by RyanCavanaugh** [comment]
@gDelgado14 Please address the merge conflict.

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Pull request merged**
