### PR TITLE
alexa-sdk: added this.i interface for i18n

### PR DESCRIPTION
**Pull request by pascalwhoop**
reference to [docs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#adding-multi-language-support-for-skill)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by pascalwhoop** [comment]
change is due to the docs and the i18n function of Alexa 
[reference here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#adding-multi-language-support-for-skill)

**Comment by pascalwhoop** [comment]
WIP, creating PR to mark it as "work in progress"

**Comment by mhegazy** [comment]
some more linter 💓 still needed.

**Comment by pascalwhoop** [comment]
Are all these Lints appropriate?

```
Error in alexa-sdk
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js 
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/alexa-sdk/index.d.ts
ERROR: 81:18  no-empty-interface         An interface declaring no members is equivalent to its supertype.
ERROR: 25:5   prefer-method-signature    Use a method signature instead of a property signature of function type.
ERROR: 26:5   prefer-method-signature    Use a method signature instead of a property signature of function type.
ERROR: 44:5   prefer-method-signature    Use a method signature instead of a property signature of function type.
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/alexa-sdk/alexa-sdk-tests.ts
ERROR: 12:5   object-literal-key-quotes  Unnecessarily quoted property 'LaunchRequest' found.
ERROR: 15:5   object-literal-key-quotes  Unnecessarily quoted property 'HelloWorldIntent' found.
ERROR: 18:5   object-literal-key-quotes  Unnecessarily quoted property 'SayHello' found.
ERROR: 12:5   object-literal-shorthand   Expected method shorthand in object literal ('{'LaunchRequest'() {...}}').
ERROR: 15:5   object-literal-shorthand   Expected method shorthand in object literal ('{'HelloWorldIntent'() {...}}').
ERROR: 18:5   object-literal-shorthand   Expected method shorthand in object literal ('{'SayHello'() {...}}').
```

I looked at them but found them to be inappropriate. Can I override these to be ignored somehow?
E.g: `Unnecessarily quoted property 'SayHello'`
This is best practice with alexa-sdk and should therefore also be the case in the tests

`no-empty-interface` is also not always correct. If you have three different types and 2 have extra properties, the last one not but they are logically all on the same level (3 kinds of an abstract supertype) then it doesn't make sense for the two with extra props to inherit from the 3rd one without extra props.

**Comment by hoo29** [comment]
For the `Unnecessarily quoted property` issue, why is it best practice? Writing them like `'HelloWorldIntent'() { ... }` gives the same functionally and conforms to the linter standards.

**Comment by pascalwhoop** [comment]
@hoo29 i overwrote the lints so the d.ts. files reflect the coding style of the alexa-sdk library without flagging them as wrong.

**Pull request merged**
