### PR TITLE
Delcaration export style did not match react-dropzone export style

### PR DESCRIPTION
**Pull request by baflo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [L417](https://github.com/react-dropzone/react-dropzone/blob/v4.1.3/src/index.js#L417)
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by benbayard — CHANGES_REQUESTED** [review]
This package does not use ES6 exports when it is packaged. 

You can tell this is true by going in to node.js and requiring the package. When you do this, there is not `.default`, it's just the react class.

**Comment by Drake103** [comment]
I know my question does not relate to this pull request, but in general, is current declaration made with the mind that a consumer has to pass all picked arguments to use it? I mean the following declaration of picked attributes:
`type PickedAttributes = "accept" | "className" | "multiple" | "name" | "onClick" | "onDragStart" | "onDragEnter" | "onDragOver" | "onDragLeave" | "style";`.

**Comment by benbayard** [comment]
It is not. It uses whatever type is supplied by React, which in our case they are optional.

**Comment by baflo** [comment]
Sorry, took a while till I could check this again. It's true, the packaged version does not have a default export. Reject this PR, please.

**Pull request closed without merging**
