### PR TITLE
[csv-parse] Remove package

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] ~~Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).~~

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

See https://github.com/adaltas/node-csv-parse/blob/v1.2.2/lib/index.d.ts

### CODE REVIEW

**Comment by ffflorian** [comment]
@wdavidw @adaltas can you maybe approve? :)

**Comment by wdavidw** [comment]
I approve, we have internalized the TS definitions. Since I am here, I would enjoy a feedback on your side in term of good practices. For example, we don't have a "tsconfig.json" nor a "tslint.json", is it necessary? The concerned packages are:

* [csv](https://github.com/adaltas/node-csv)
* [csv-generate](https://github.com/adaltas/node-csv-generate)
* [csv-parse](https://github.com/adaltas/node-csv-parse)
* [csv-stringify](https://github.com/adaltas/node-csv-stringify)
* [stream-transform](https://github.com/adaltas/node-stream-transform/)

**Comment by sandersn** [comment]
@wdavidw If you are writing the code in JS then you only need the tsconfig.json for the tests for your types, or you can just use command line args of course. I didn't see tests in `csv` so this may be future work for you.

Of course you can add one to get checking for your JS code as well, but `// @ts-check` works for that too.

I would not personally add tslint.json at this point. Just stick with eslint if you use that.

**Comment by wdavidw** [comment]
Thank you for your feedback. Inside each package test folder, we have a single ts test file which only checks the API. Those tests are executed with Mocha along the other coffee tests.

**Pull request merged**
