### PR TITLE
[node] Improve return type of fs.readdir() and fs.readdirsync()

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_readdirsync_path_options
https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_readdir_path_options_callback
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Update result type of `fs.readdir()` and `fs.readdirsync()` to be either an Array of strings or an Array of Buffer.

### CODE REVIEW

**Comment by Flarna** [comment]
Quite a lot unrelated CI failures. @andy-ms any hints how to get rid of them?

**Comment by andy-ms** [comment]
Fixed CI failures in master, re-ran tests and they passed.

**Review by ajafff — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]
Could this be improved once Microsoft/TypeScript#21316 is released?

```typescript
 export function readdirSync<E extends string | null>(path: PathLike, options?: { encoding?: E } | E): E extends "buffer" ? Buffer[] | string[];
```

Would need to check from which strings node infers the buffer type but https://github.com/nodejs/node/blob/master/lib/internal/util.js seems to not normalize buffer type strings.

**Comment by Flarna** [comment]
@eps1lon I fear not that fast as type definition of node stick on TS 2.0 currently. Raising the required TS version for node requires to raise it also in all >1000 dependent modules - and in all projects using them.
Don't expect that this will happen soon...

**Pull request merged**
