### PR TITLE
Fixed an issue with the Xrm type for ProcessStatus (in namespace ProcessFlow)

### PR DESCRIPTION
**Pull request by philcatterall**
…low)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/instance/getstatus>
<https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventargs>

### CODE REVIEW

**Review by Power-Maverick — CHANGES_REQUESTED** [review]
Please provide a link to the documentation and add or update any test cases in `xrm-tests.ts`. Thanks.

**Comment by philcatterall** [comment]
> 

Hi, apologies, this is the first time I have contributed to an open source project on GitHub, so I'm still feeling my way. I now understand what you need and will supply the relevant documentation links. I've also now figured out what is needed regarding tests. And while doing this and doing some more testing I've actually found another bug which I want to include.
Can we mark this PR as "draft" while I work on the above, then re-submit ?
I may need a little bit of hand-holding, so sorry again, bear with me, I'll get there. :-)
Cheers,
Phil

**Comment by philcatterall** [comment]
> Please provide a link to the documentation and add or update any test cases in `xrm-tests.ts`. Thanks.

@Power-Maverick 
Hi again, since my last message I've now completed everything. There is one aspect regarding the new enums needed that I'd like to collaborate on. I've commented in the enums namespace. 
Hopefully this all looks a bit better now !!
Cheers
Phil

**Review by Power-Maverick — CHANGES_REQUESTED** [review]
After looking into it in-depth looks like the changes might not be accurate (need eyes from @filcole, @daryllabar & others)

I am able to get the process status and set the process status using the below format with the current version which looks accurate as per the documentation:

```TypeScript
function processStatusCheck(context: Xrm.Events.ProcessStatusChangedEventContext) {
    const formContext = context.getFormContext();
    var status = formContext.data.process.getStatus();
    formContext.data.process.setStatus('active');
}
```

Also, some of your edits from `ProcessFlow.Process` to `ProcessFlow.ProcessManager` are also not correct as the latter points to `formContext.ui.process` which is not where `getStatus()` function exists (as per the documentation).

Please elaborate if I am missing something. Thanks.

**Comment by philcatterall** [comment]
> After looking into it in-depth looks like the changes might not be accurate (need eyes from @filcole, @daryllabar & others)
> 
> I am able to get the process status and set the process status using the below format with the current version which looks accurate as per the documentation:
> 
> ```ts
> function processStatusCheck(context: Xrm.Events.ProcessStatusChangedEventContext) {
>     const formContext = context.getFormContext();
>     var status = formContext.data.process.getStatus();
>     formContext.data.process.setStatus('active');
> }
> ```
> 
> Also, some of your edits from `ProcessFlow.Process` to `ProcessFlow.ProcessManager` are also not correct as the latter points to `formContext.ui.process` which is not where `getStatus()` function exists (as per the documentation).
> 
> Please elaborate if I am missing something. Thanks.

Thanks for your feedback. Regarding the 1st point, the issue is not actually with 
context.getFformContext.()data.process.getStatus() or indeed context.getEventArgs().getStatus(). 
These do return exactly what the documentation says they will.

The problem is that the latter method returns the status Capitalised (as per the documentation) at <https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventargs>
See the Return value for OnProcessStatusChange about halfway down the page.
i.e. it returns "Active" not "active" (which is returned by the 1st method). So when subsequently doing a comparison:
```ts
const receivedStatus = context.getEventArgs().getStatus();
if (receivedStatus === "active")  console.log("Match successful !!"); 
```
The comparison fails because it's comparing "active" with "Active".
Hence I added a new type (Line 967) and associated it with the context.getEventArgs().getStatus() method (Line 749)
Note that there is not an issue with formContext.data.process.getStatus() in the current version, as in your test, because this is all lower case.
I've published my test script, used in a Dynamics 365 instance, to gitHub <https://github.com/philcatterall/DTXrmTests>
And I have documented extensively in that (also in xrm-tests.ts)

Re your second point, I'll take a look again (I think this was just correcting the Annotation link - I may have got that wrong)

Cheers,
Phil

**Comment by philcatterall** [comment]
I can't see anything wrong with the changes. I'm using my changed version now in production.

**Review by Power-Maverick — APPROVED** [review]

**Pull request closed without merging**
