### PR TITLE
allow injected functions in @types/chrome to have params

### PR DESCRIPTION
**Pull request by nicolas377**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developer.chrome.com/docs/extensions/reference/scripting/#type-ScriptInjection>

### CODE REVIEW

**Comment by nicolas377** [comment]
seems that the dependencies of chrome need their ts version updated as well
i'll go and do that now

**Comment by nicolas377** [comment]
i didnt all the dependencies

**Comment by nicolas377** [comment]
turning on noImplicitAny and noImplicitThis seems to have broken the test

**Comment by nicolas377** [comment]
FINALLY

**Comment by peterblazejewicz** [comment]
@nicolas377 where it states this func takes any parameter? (docs states it does not support any)

**Comment by nicolas377** [comment]
args is what will get passed into the params when the function gets run, the function itself needs to be able to put names to them
(ive tested this in a chrome extension, it works)

ex:
`chrome.scripting.executeScript({
    target: {},
    func: (name) => { // do whatever with name},
    args: [local var to give the function]`
on the backend, it will serialize and deserialize the function, then run the function with params as the args array

**Review by Guy-Adler — APPROVED** [review]

**Review by tregagnon — APPROVED** [review]

**Review by userTim — APPROVED** [review]

**Comment by userTim** [comment]
Ready to merge

**Pull request merged**
