### PR TITLE
Add @types/hj

### PR DESCRIPTION
**Pull request by glenngijsberts**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by glenngijsberts** [comment]
Not sure about the naming part, because the package that's referred on NPM is an old (unused) package. Not sure if `hj-browser` would be better, because that might be conflicting with the `@hotjar/browser` package. These types are meant for their snippet provided [here](https://help.hotjar.com/hc/en-us/articles/115009336727).

**Review by weswigham — COMMENTED** [review]
Hmmm, so there's an official `@hotjar/browser` [package](https://www.npmjs.com/package/@hotjar/browser) (with types, even) which [notably has different internal types for the hj method on window](https://github.com/hotjar/hotjar-js/blob/main/src/utils.ts#L9). I'm wondering if the window `hj` is supposed to be an implementation detail, or maybe if these types are just a bit incomplete or overly restrictive?

I dunno, I'd feel better if one of the devs of the "real" package - @hereismass or @arrwhidev or  @maxmaxme could weigh in on the intent. The bar is a bit higher for non-`npm` packages, since these pollute the global scope.

And if a global like this is useful, IMO, I think it'd be better to put it under the `@hotjar` namespace already in use on npm, rather than using the opaque top-level name `hj`.

**Comment by weswigham** [comment]
> Not sure about the naming part, because the package that's referred on NPM is an old (unused) package. Not sure if hj-browser would be better, because that might be conflicting with the @hotjar/browser package. These types are meant for their snippet provided [here](https://help.hotjar.com/hc/en-us/articles/115009336727).

Yeah, maybe something like `@hotjar/hj` would be better; but better yet would just be contributing to `@hoitjar/browser` itself and adding the types as a global augmentation in that package.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Pls work per feedback from @weswigham

**Pull request closed without merging**
