### PR TITLE
Fix react-native

### PR DESCRIPTION
**Pull request by tkrotoff**
- Fix DatePickerIOS, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25307#issuecomment-384829289
- Fix StatusBar, see #25360 
- Fix Expo Props, see #25258
- Fix missing static methods

### CODE REVIEW

**Comment by svbutko** [comment]
@tkrotoff, Also spotted issues with TouchableNativeFeedback and its _Ripple_ function, would be better to change it in this PR instead of creating a separate one.

**Comment by tkrotoff** [comment]
@svbutko I've already also fixed TouchableNativeFeedback static methods

**Comment by tkrotoff** [comment]
Ping also @weswigham @vovkasm

**Review by timwangdev — APPROVED** [review]

**Comment by vovkasm** [comment]
Will test soon!

**Review by iRoachie — APPROVED** [review]

**Comment by vovkasm** [comment]
How to test it before landing? (this change touches many modules, so I'am unsure how to install it, can I do this with something in `package.json`? Or I need to replace content in `node_modules/@types/*` by hand?)

**Review by avocadowastaken — APPROVED** [review]

**Comment by tkrotoff** [comment]
@vovkasm you can't since https://github.com/tkrotoff/DefinitelyTyped/tree/react-native-fix/types/react-native does not contain any package.json (among other things) and thus is not a valid npm package).

If you write `"@types/react-native": "tkrotoff/DefinitelyTyped#react-native-fix"` then the whole DefinitelyTyped repository is downloaded

With `"@types/react-native": "https://github.com/tkrotoff/DefinitelyTyped/tree/react-native-fix/types/react-native"` you get `error An unexpected error occurred: "https://github.com/tkrotoff/DefinitelyTyped/tree/react-native-fix/types/react-native: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".`

The only solution to my knowledge is good old copy-paste inside `node_modules/@types/*`

**Pull request merged**
