### PR TITLE
Added manualRowMove

### PR DESCRIPTION
**Pull request by oliverbock**

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by IntelOrca** [comment]
This should probably have a doc-comment.

**Comment by yuit** [comment]
@oliverbock Thanks for the PR, could address PR  as @IntelOrca suggests

**Comment by oliverbock** [comment]
I omitted the doc-comment because I worry that it will get out of sync with the project's [good reference documentation](http://docs.handsontable.com/Core.html).  Anyway, people seem keen so I will make the change anyway.

**Pull request merged**
