### PR TITLE
16023: creates second types folder for those, who uses npm package co…

### PR DESCRIPTION
**Pull request by slawiko**
This PR related to #16023 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by andy-ms** [comment]
We shouldn't duplicate the definitions. Moving `cookiejs` to `cookie_js` is fine and we can deprecate `cookiejs`.

**Comment by slawiko** [comment]
@andy-ms I think no, because cookie_js is 'strange' package. At bower it calls 'cookiejs', at npm - 'cookie_js'. So I think we should duplicate definitions in this case. But if you're against - no problem, I can remove @types/cookiejs.

**Comment by slawiko** [comment]
@andy-ms can you edit PR creating template?

**Comment by andy-ms** [comment]
Our policy is to always use the name of the package on NPM, and not bower or anything else. The old definition can be preserved by having both `declare module "cookiejs" { export = cookie; }` and `declare module "cookie_js" { export = cookie; }`.

**Comment by slawiko** [comment]
@andy-ms and how can I run `dts-gen`? It isn't installed as dependency, as I see

**Comment by andy-ms** [comment]
Just install globally.

**Comment by slawiko** [comment]
@andy-ms it's clear, thanks.

**Comment by slawiko** [comment]
Any updates?

**Comment by andy-ms** [comment]
Deprecated `@types/cookiejs` in favor of `@types/cookie_js`.

**Pull request merged**
