### PR TITLE
Node.js v8.0.0 Stream - types/node/index.d.ts

### PR DESCRIPTION
**Pull request by mwiktorczyk**
Extending existing node v8 definitions accordingly to the documentation from https://nodejs.org/api/stream.html

- https://nodejs.org/api/stream.html#stream_writable_destroy_error
- https://nodejs.org/api/stream.html#stream_readable_destroy_error
- https://nodejs.org/api/stream.html#stream_transform_destroy_error
- https://nodejs.org/api/stream.html#stream_writable_destroy_err_callback
- https://nodejs.org/api/stream.html#stream_writable_final_callback

### CODE REVIEW

**Comment by mwiktorczyk** [comment]
From the [spec](https://nodejs.org/api/stream.html#stream_readable_destroy_error) - 
`Destroy the stream, and emit 'error'. After this call, the readable stream will release any internal resources. Implementors should not override this method, but instead implement readable._destroy.`

Unfortunately, the author of simple-peer, has been using the method that is now restricted. What should I do in such a situation?

**Comment by paulvanbrenk** [comment]
@mwiktorczyk can you add a pointer to the usage you're worried about?

**Comment by mwiktorczyk** [comment]
@paulvanbrenk

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/simple-peer/index.d.ts#L54
- https://github.com/feross/simple-peer/blob/master/index.js#L247

**Comment by paulvanbrenk** [comment]
@mwiktorczyk  can you update the definition to simple-peer, so the build passes and we'll get someone from their side to review. You probably also want to open an issue in their repo to point them to this issue.

**Comment by mwiktorczyk** [comment]
@paulvanbrenk

1. Simple-peer definition changed.
1. Issue submitted https://github.com/feross/simple-peer/issues/187
1. Fork rebased and conflicts resolved

**Comment by paulvanbrenk** [comment]
@tlaziuk you can any comments on the change to simple-peer?

**Pull request merged**
