### PR TITLE
react-infinite-scroller: fix default export

### PR DESCRIPTION
**Pull request by joscha**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/CassetteRocks/react-infinite-scroller/blob/master/index.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by joscha** [comment]
references https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3bd056f15eb0a0e9dec0fdce91f747c76e008ad5#commitcomment-23027258

**Comment by Lapanti** [comment]
👍

**Comment by joscha** [comment]
@Lapanti all changes in

**Review by lapanti — APPROVED** [review]

**Comment by joscha** [comment]
I am still unclear on when new types will be release - https://www.npmjs.com/package/@types/react-infinite-scroller shows a release from 3 weeks ago - is this a manual process @RyanCavanaugh?

**Comment by RyanCavanaugh** [comment]
@joscha please log a bug on the `types-publisher` repo

**Comment by joscha** [comment]
> @joscha please log a bug on the types-publisher repo

@RyanCavanaugh it seems to have been published now? About the time when you commented - does that mean you fixed it or should I still open a ticket?

**Comment by RyanCavanaugh** [comment]
@joscha checked with @andy-ms and there were some Azure problems yesterday that were preventing automatic publishes. Should be fixed now.

**Comment by joscha** [comment]
Got it! Thanks Ryan!

On 14 Jul 2017 3:01 am, "Ryan Cavanaugh" <notifications@github.com> wrote:

@joscha <https://github.com/joscha> checked with @andy-ms
<https://github.com/andy-ms> and there were some Azure problems yesterday
that were preventing automatic publishes. Should be fixed now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17930#issuecomment-315139875>,
or mute the thread

**Comment by danielearwicker** [comment]
@joscha When using `import InfiniteScroll = require('react-infinite-scroller');` I get `InfiniteScroll is undefined` at runtime. I'm using webpack. None of the other ways of importing work at compile time.

**Comment by andy-ms** [comment]
@danielearwicker When using the package in a node project `require("react-infinite-scroller")` was defined for me. You could always try other ways of importing and just ignore the compile errors to see if they work at runtime, but I doubt they will; a default import is just `require("react-infinite-scroller").default`, so it won't be defined if `require("react-infinite-scroller")` isn't.

**Comment by joscha** [comment]
@danielearwicker what does your tsconfig look like? Can you use `import * as InfiniteScroll from 'react-infinite-scroller'`?

**Pull request merged**
