### PR TITLE
[cloudflare] Export all types under namespace Cloudflare

### LINKED ISSUE #51621: export record types
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/cloudflare@2.7.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/cloudflare/index.d.ts b/node_modules/@types/cloudflare/index.d.ts
index 60ccd5d..51c4792 100644
--- a/node_modules/@types/cloudflare/index.d.ts
+++ b/node_modules/@types/cloudflare/index.d.ts
@@ -3,7 +3,7 @@
 // Definitions by: Samuel Corsi-House <https://github.com/Xenfo>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 
-type RecordTypes =
+export type RecordTypes =
     | 'A'
     | 'AAAA'
     | 'CNAME'
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #51621

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by samchouse — CHANGES_REQUESTED** [review]
I took a look at other type definitions and there is no need to export types under namespace Cloudflare.

index.d.ts
```
export type RecordTypes =
```

cloudflare-tests.ts
```
const types: Cloudflare.RecordTypes = 'AAAA';
```

That does the trick.

**Comment by martin-badin** [comment]
> I took a look at other type definitions and there is no need to export types under namespace Cloudflare.
> 
> index.d.ts
> 
> ```
> export type RecordTypes =
> ```
> 
> cloudflare-tests.ts
> 
> ```
> const types: Cloudflare.RecordTypes = 'AAAA';
> ```
> 
> That does the trick.

Thanks. Updated

**Comment by martin-badin** [comment]
@Xenfo Sorry but your mentioned solution doesn't work. There is error

`An export assignment cannot be used in a module with other exported elements.ts(2309)`

**Review by samchouse — COMMENTED** [review]
Add a new line to the end of both files as per `npm test cloudflare`

**Comment by martin-badin** [comment]
There is an empty line on the end of both files.

**Review by samchouse — APPROVED** [review]

**Comment by Xenfo** [comment]
Ready to merge

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
