### PR TITLE
infinitescroll: fix type of checkLastPage

### PR DESCRIPTION
**Pull request by iustin**
Per https://github.com/metafizzy/infinite-scroll?tab=readme-ov-file#options, the `checkLastPage` option can take a string, if the `path` is not set.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code - yes.
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change - change is trivial.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/metafizzy/infinite-scroll?tab=readme-ov-file#options

### CODE REVIEW

**Review by MysteryBlokHed — CHANGES_REQUESTED** [review]
If you add a test for this change to `infinite-scroll-tests.ts`, then I can merge this without needing maintainer review 😊

**Comment by iustin** [comment]
> If you add a test for this change to `infinite-scroll-tests.ts`, then I can merge this without needing maintainer review 😊

I would be happy to, but I'm not really familiar with JS/TS. I don't know what would be an appropriate test here - that the new type is accepted? Or that it does the right thing (this would be complex).

**Comment by MysteryBlokHed** [comment]
> I would be happy to, but I'm not really familiar with JS/TS. I don't know what would be an appropriate test here - that the new type is accepted? Or that it does the right thing (this would be complex).

The tests for packages in this repository aren't actually evaluated—they're just checked for type validity.

You could add something like this to test that the option accepts strings:

```typescript
new InfiniteScroll(".abc", { checkLastPage: "foo" });
```

**Comment by iustin** [comment]
Hmm, I added tests, but the bot doesn't see that. Well, lesson learned!

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by iustin** [comment]
Ready to merge

**Pull request merged**
