### PR TITLE
[@types/bun] Update `@types/bun` to point to `bun-types@1.0.26`

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test bun`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by Electroid** [comment]
@typescript-bot rerun

**Comment by Electroid** [comment]
@typescript-bot /retry

**Comment by codershiba** [comment]
@Electroid Looks like bun v1.0.26 was published `bun-types` v1.0.26 wasn't published

**Comment by Electroid** [comment]
> @Electroid Looks like bun v1.0.26 was published `bun-types` v1.0.26 wasn't published

That should be fixed now, if you're able to get CI to re-run

**Review by Electroid — APPROVED** [review]

**Pull request merged**
