### PR TITLE
ramda: propOr can handle undefined for the propName

### PR DESCRIPTION
**Pull request by guillaumep**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://ramdajs.com/docs/#propOr (manually testing ramda reveals propOr does accept undefined for the prop name)
- [ ] Increase the version number in the header if appropriate. (not sure it is?)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by raynerd — COMMENTED** [review]
Looks good, can you add the test that uses `undefined`?

**Comment by googol** [comment]
I'm not sure it's a good idea to codify in the typings an undocumented behavior. I'd be much more comfortable with this change if the ramda project promised propOr accepts `undefined` as a value.

**Comment by raynerd** [comment]
@googol agree but that's an actual posibily that might be part of someone's "broken" logic and the types shouldn't prevent the `undefined` usage

**Comment by guillaumep** [comment]
I plan to take time during the week to add tests as suggested.

Also, allowing undefined here is not broken logic. It helps avoiding checking if the variable used for prop name is undefined before calling the function, and if done willingly it helps keep the code leaner.

**Review by moshensky — COMMENTED** [review]
I would be very sorry to see that being merged.
Documentation explicitly mentions that it expects `string`. 
Ramda's [code](https://github.com/ramda/ramda/blob/v0.25.0/source/internal/_has.js#L2) is using [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) which is typed as `    hasOwnProperty(v: string): boolean;` too.

I would prefer to stick to well known public interface.

**Comment by guillaumep** [comment]
Closing the PR as it does not seems to create consensus.

**Pull request closed without merging**
