### PR TITLE
Adds readme to Recurly.js

### PR DESCRIPTION
**Pull request by dbrudner**

### CODE REVIEW

**Comment by amcasey** [comment]
@dbrudner I think I'm missing something, are the types published both here and in the package itself?

**Review by amcasey — APPROVED** [review]
Assuming it makes sense to have types on DT, these changes seem correct.

**Comment by chrissrogers** [comment]
@amcasey yep, we author type changes alongside code changes in the package itself and then publish to this repository when a new release is published.

**Comment by dbrudner** [comment]
Ready to merge

**Pull request merged**
