### PR TITLE
Ramda: improved complement definition

### PR DESCRIPTION
**Pull request by deftomat**
Updated `complement` definition which will preserve the given function type.

### CODE REVIEW

**Review by googol — APPROVED** [review]

**Review by afharo — APPROVED** [review]
It looks ok for me

**Comment by weswigham** [comment]
Consider:
```ts
type F = () => true;
const x: F = () => true;
const r = R.compliment(x);
// r now has return type `true` when it will actually only ever return `false`.
```
Is this worth handling correctly?

**Comment by deftomat** [comment]
@weswigham
Well, that is a good point. What do you suggest then? We definitely need to preserve the type of an input. Maybe it is possible to use a conditional types. Anyway, I'm away of my computer right now. So, I will be able to try it at the beginning of the next month.

**Comment by weswigham** [comment]
> What do you suggest then? 

Probably a condition that inverts the input return type? Eg, `type Invert<T extends boolean> = T extends true ? false : true;` - overloads may also work.

**Comment by sheetalkamat** [comment]
@deftomat Can you please fix as per @weswigham 's suggestion.

**Comment by deftomat** [comment]
@sheetalkamat Sure, I'm back from holiday now. I will do it this weekend.

**Comment by deftomat** [comment]
@weswigham
Well, I was able to do it with TS3. 
However, a Travis build failed with `Error: Could not parse version: line is '// TypeScript Version: 3.0'`.

 I don't want to use overloads as typing will lost an argument names. For example:
```
complement<T1, S extends boolean>(pred: (a: T1) => S): (a: T1) => Invert<S>;
```

```
function isEven(n: number) {
  return n % 2 === 0;
}

const isOdd = R.complement(isEven);
isOdd(21); // Typehint as: const isOdd: (a: number) => boolean
```

So as a conclusion, I'm not sure how to solve it. Can we support TS3 or even do we want to force users to use it? Because there are some ugly tradeoffs without it. Like you mentioned above or like a wrong argument names in overloads.

**Comment by weswigham** [comment]
Hm. @andy-ms does the test harness work with 3.0 annotations yet?

@deftomat up to you - I just wanted to point out that there was still a case for which compliment would be inaccurate and make you aware of it.

**Comment by deftomat** [comment]
Then, I'm going to close this PR and I will recreate it next month.

**Pull request closed without merging**
