### PR TITLE
Google Drive API v2

### PR DESCRIPTION
**Pull request by garciat**
**Google API Client Library for JavaScript**
(https://developers.google.com/api-client-library/javascript/reference/referencedocs)
- [x] Client
- [x] Auth

**Google Drive REST API Version 2**
(https://developers.google.com/drive/v2/reference/)
- [x] Files
- [x] About
- [ ] Changes
- [ ] Children
- [ ] Parents
- [x] Permissions
- [ ] Revisions
- [ ] Apps
- [ ] Comments
- [ ] Replies
- [ ] Properties
- [ ] Channels
- [ ] Realtime (already implemented [here](https://github.com/borisyankov/DefinitelyTyped/tree/master/google-drive-realtime-api))

### CODE REVIEW

**Comment by vvakame** [comment]
*gapi.drive/gapi.drive.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/gapi.drive
  * http://bower.io/search/?q=gapi.drive
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (gapi.drive/gapi.drive-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*gapi.pagespeedonline/gapi.pagespeedonline.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*gapi.translate/gapi.translate.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*gapi.urlshortener/gapi.urlshortener.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*gapi.youtube/gapi.youtube.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*gapi.youtubeAnalytics/gapi.youtubeAnalytics.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*gapi/gapi.client.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/gapi
  * http://bower.io/search/?q=gapi
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (gapi/gapi.client-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*gapi/gapi.d.ts*

to author(@sgtfrankieboy). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
FYI, I made gapidts package. https://www.npmjs.com/package/gapidts
https://github.com/vvakame/gapidts/blob/master/test/valid/drive-v2-nodejs.d.ts
I do not know it works because not worked recently.

**Comment by sgtfrankieboy** [comment]
I guess the previous post was auto-generated. Not much has changed to files so everything is :+1:

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
