### PR TITLE
[@types/jest] stringMatching should only accept regexp as input param

### PR DESCRIPTION
**Pull request by ahnpnl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/jest/docs/en/expect.html#expectstringmatchingregexp
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

**Changes:**
- Correct input param type for stringMatching.
- Alphabetically sort for some functions
- Correct tab indent to be 4 for test file and definition file

### CODE REVIEW

**Review by andnp — APPROVED** [review]

**Comment by jwbay** [comment]
The docs and implementation (including Flow types) disagree here. Do you mind opening an issue in Jest to get clarification since this will cause compile errors on code that's valid?

https://github.com/facebook/jest/blob/master/packages/expect/src/asymmetric_matchers.js#L241-L245

**Comment by andnp** [comment]
Hmm, it seems you are correct @jwbay about the implementation. Just tested in my `Jest` environment and it seems this does work. Interesting though, I disagree that [the docs](https://facebook.github.io/jest/docs/en/expect.html#expectstringmatchingregexp) suggest that this takes a string though. I guess Jest either needs to update the docs, or clarify if this is going to be deprecated.

**Review by jwbay — CHANGES_REQUESTED** [review]
See above

**Comment by AhnpGit** [comment]
Open an issue on Jest GitHub at https://github.com/facebook/jest/issues/5926

**Comment by AhnpGit** [comment]
Hi @jwbay, @andnp I'll close this PR. Got an answer from Jest that they also support string together with regexp as input types.

**Pull request closed without merging**
