### PR TITLE
[react-native] Specify valid keys in Animated.ValueXY#getTranslateTransform signature

### PR DESCRIPTION
**Pull request by sumnerwarren**
We ran into [an issue](https://github.com/5up-okamura/react-native-draggable-gridview/issues/5) using the [`react-native-draggable-gridview`](https://github.com/5up-okamura/react-native-draggable-gridview) library with the `0.63` version of the `react-native` types. This issue did not exist with version `0.62`, and I believe was caused by [this change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46473/files#diff-e94ad9b79ba4f07235bfefa12c2789cd2d6cb690d9120309555f33ae51295244). Specifically, the move from [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46473/files#diff-e94ad9b79ba4f07235bfefa12c2789cd2d6cb690d9120309555f33ae51295244L8945) to [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46473/files#diff-e94ad9b79ba4f07235bfefa12c2789cd2d6cb690d9120309555f33ae51295244R8948) where the properties of `withAnimatedObject` are no longer optional. Undoing that change would fix the error we're seeing, but I chose to go a different route as I think the non-optional `withAnimatedObject` properties are technically correct.

My proposed solution provides a more specific return type for `Animated.ValueXY#getTranslateTransform` based on the [actual implementation](https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/Libraries/Animated/nodes/AnimatedValueXY.js#L222). Note that the existing test for this function was not properly specified according to the [documentation](https://reactnative.dev/docs/animatedvaluexy#gettranslatetransform) for `getTranslateTransform`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/Libraries/Animated/nodes/AnimatedValueXY.js#L222>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lindapaiste** [comment]
I was searching to see if anyone had raised an issue this because I came across the error while answering a [StackOverflow question](https://stackoverflow.com/questions/65981291/unsure-what-type-my-prop-is-in-react-native-typescript/66018069#66018069).  I made a [CodeSandbox demo](https://codesandbox.io/s/animation-ts-error-dl81w?file=/src/App.tsx) reproduces the error.

Your proposed fix `{ [key in TranslateTransformKeys]: AnimatedValue }[];` will definitely fix the core issue.

This is a matter of opinion, but do you (or any of the maintainers of this package) think that there is a benefit to being more specific?  For example declaring that the keys are specifically `translateX` and `translateY` or that it is a tuple of length 2.  These things would only matter if the user wanted to do something with the transform other than just pass it to component, so I don't know if it's worthwhile.  The most specific return type would be `[{translateX: AnimatedValue}, {translateY: AnimatedValue}]`

**Comment by ca057** [comment]
> This is a matter of opinion, but do you (or any of the maintainers of this package) think that there is a benefit to being more specific?

I personally would argue that more specific typings are desired, as they can help new developers understanding the library, support more advanced use cases and help you find bugs/errors in an earlier stage. I’m not sure though what the overall direction/opinion in this matter of DT is.

**Review by ca057 — APPROVED** [review]

**Comment by sumnerwarren** [comment]
I think more specific is fine. I do think use of this function outside of a component is probably limited, but there may be an animation library out there that knows how to work with it and could benefit from the more accurate type.

**Review by ca057 — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Comment by sumnerwarren** [comment]
Ready to merge

**Pull request merged**
