### PR TITLE
p2 - ContactMaterialOptions properties should all be optional

### PR DESCRIPTION
**Pull request by spacejack**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

As per documentation ContactMaterialOptions properties should all be optional:
http://schteppe.github.io/p2.js/docs/classes/ContactMaterial.html

ConvexOptions should be an object with optional vertices and axes properties:
http://schteppe.github.io/p2.js/docs/classes/Convex.html

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by clark-stevenson — APPROVED** [review]
Looks good!

**Comment by clark-stevenson** [comment]
Thanks @spacejack  💃

**Comment by spacejack** [comment]
Sorry for tacking on another commit but I overlooked another type I needed a fix for.

There's a larger issue which could be looked at is underlying types in p2 are often Float32Arrays not regular Arrays. Additionally, most constructor parameters will accept any numeric array type, so I think in those cases we should be using ``ArrayLike<number>` instead of `number[]`.

**Comment by minestarks** [comment]
@clark-stevenson Thanks for reviewing -- does the second commit in this PR look good too?

**Review by clark-stevenson — APPROVED** [review]
Looks Good!

**Comment by clark-stevenson** [comment]
Thanks guys 👍

**Pull request merged**
