### PR TITLE
intercom-web: Make `intercomSettings` optional to allow `delete window.intercomSettings` (New change in TS 4.0)

### PR DESCRIPTION
**Pull request by tklepzig**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

	> With TS 4.0, when in strictNullChecks mode (i.e., always, right??!), the operand of the delete operator MUST be any, unknown, never or be optional (i.e., containing undefined ); otherwise, the code doesn’t compile. Check out the [PR](https://github.com/microsoft/TypeScript/pull/37921) for details.

 (https://medium.com/javascript-in-plain-english/whats-new-with-typescript-4-0-beta-a2e674846ef3)

### CODE REVIEW

**Comment by orta** [comment]
Note for reviewers: This would potentially be a breaking change for people using strict mode (because they now have to validate the existence of that value)

**Comment by onatm** [comment]
Hey @orta, thank you for letting us know that this would be a potential breaking change. I am not sure what would be the real impact because for the future since the declaration is complete(-ish?).

**Review by onatm — COMMENTED** [review]
@tklepzig Could you tell me what do you mean by delete `window.intercomSettings`? My knowledge of TS and intercom (or any frontend technology) could be a bit outdated atm.

**Comment by tklepzig** [comment]
@onatm Of course. We use Intercom for our customer's feedback. For that, we have to set it up during startup (https://developers.intercom.com/installing-intercom/docs/configuration). While doing this, we add the prop `intercomSettings` to the `window` object. In order to clean up things afterwards properly, we delete the property with `delete window.intercomSettings`. 

Now with TS 4.0 a change has been introduced which allows `delete` only for optional properties in strict mode (https://medium.com/javascript-in-plain-english/whats-new-with-typescript-4-0-beta-a2e674846ef3#a545 and https://github.com/microsoft/TypeScript/pull/37921). To fulfil this rule, I changed the property to an optional one.

Does this answer your question?

**Comment by onatm** [comment]
that was a really nice explanation, thank you @tklepzig 👍  I am happy to move forward with this PR

**Review by onatm — APPROVED** [review]

**Comment by onatm** [comment]
Ready to merge

**Comment by tklepzig** [comment]
> that was a really nice explanation, thank you @tklepzig 👍 I am happy to move forward with this PR

Thanks a lot!

**Pull request merged**
