### PR TITLE
Update `mustache` for the use in ES modules

### PR DESCRIPTION
**Pull request by neurolag**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - <https://github.com/janl/mustache.js/blob/bd29972ab8a0f4c592f35483615ab9a274396300/CHANGELOG.md#320--18-december-2019>
  - <https://github.com/janl/mustache.js/blob/bd29972ab8a0f4c592f35483615ab9a274396300/CHANGELOG.md#420--28-march-2021>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
from what I could read, seems you're changing a little more than ES module support. Is that safe to change names and symbols types, just switching 4.1 to 4.2? (or in other words, do you expect any side effects)

**Comment by manuth** [comment]
Thanks for having a look at it
I managed it to forget to point this out in my original comment:

`"module": "Node16"` TypeScript projects don't seem to be able to handle classes which are declared using the `typeof` such as these:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/41529717b54de21a3bd1b9bc18ae5ce4238d1717/types/mustache/index.d.ts#L34-L49

When trying to get a code like this working:
```ts
import Mustache from "mustache";
class MyWriter extends Mustache.Writer {}
```

I get the following error in the IDE:
```
Cannot find namespace 'Mustache'. ts(2503)
```

However, `tsc -p .` runs through successfully (wtf)

If I try go for a piece of code like this:
```ts
import Mustache from "mustache";
const { Writer } = Mustache;
class MyWriter extends Writer {}
```

The compilation fails with following error:
```
'extends' clause of exported class 'MyCustomContext' has or is using private name 'Context'.
```

In order to fix this issue, I dropped the `MustacheStatic` interface and instead exported all components of `mustache` directly using `export [...]` rather than an `export =` statement.

As far as I can tell, the type declarations should work in exactly the same way as they used to before, but with the gotcha that they can be used in `"module": "Node16"` projects as well.

**Comment by peterblazejewicz** [comment]
thanks! appreciate time spent answwering. Quick one, would something along lines like:
```ts
import * as mustache from './index.js';
export * from './index.js';

export default mustache;
```
prevent duplication?

**Comment by manuth** [comment]
> thanks! appreciate time spent answwering. Quick one, would something along lines like:
> 
> ```ts
> // in `index.d.mts`
> import * as mustache from './index.js';
> export * from './index.js';
> 
> export default mustache;
> ```
> 
> prevent code duplication in DT package?

I just gave it a go and sadly, it wouldn't.
The goal I want to reach is to `export * from './index.js';` but only including types and interfaces. However, `export * from './index.js'` will also export functions such as `render()`, `clearCache()` etc. which is inaccurate.

If that weren't the case, it would work. Do you think there is some way to filter functions and classes from `export * from './index.js'`?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@manuth at your discretion, once you're comfortable with the change

**Comment by manuth** [comment]
@peterblazejewicz awesome! Thanks a ton for having a look at it 😄

**Comment by manuth** [comment]
Ready to merge

**Pull request merged**
