### PR TITLE
[wordpress__*] Resolve breaking changes with `@wordpress/element@5.2.0`

### PR DESCRIPTION
**Pull request by eps1lon**
Unblocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66928

Fixes
```
Error in wordpress__block-editor
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__blocks
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__edit-post
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__components
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__editor
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__notices
Error: Errors in typescript@5.3 for external dependencies:
Error: node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__notices/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__notices/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__plugins
Error: Errors in typescript@5.3 for external dependencies:
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: ../wordpress__rich-text/node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)


Error in wordpress__rich-text
Error: Errors in typescript@5.3 for external dependencies:
Error: node_modules/@wordpress/data/build-types/components/with-dispatch/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.
Error: node_modules/@wordpress/data/build-types/components/with-select/index.d.ts(2,56): error TS2694: Namespace '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__rich-text/node_modules/@wordpress/element/build-types/index"' has no exported member 'WPComponent'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)
```
--  https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/6417297019/job/17422725916?pr=66928

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wordpress__block-editor ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wordpress__block-editor@latest/))
was missing the following properties:
1. privateApis
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2b299bb5e99583f82b5c660f09b8a5843858dfb1
</p>

**Review by rbuckton — APPROVED** [review]

**Comment by jakebailey** [comment]
`@wordpress/block-editor` is at v12 upstream, but DT is only at v11 (I haven't checked the others); do these version bumps correspond to upstream releases such that the versions in `index.d.ts` here need to be updated to reflect those changes, and that's why these packages broke?

**Comment by jakebailey** [comment]
Hm, it's only `block-editor` which has the wrong major version. I'll also note that `@wordpress/notices` and `@wordpress/rich-text` are now typed upstream and can be removed, but it doesn't seem like there's a pattern here, so my comment is mostly moot 😅

**Comment by eps1lon** [comment]
Ready to merge

**Pull request merged**
