### PR TITLE
[greasemonkey] Greasemonkey API 4.x

### PR DESCRIPTION
**Pull request by nikolay-borzov**
- Purely based on https://wiki.greasespot.net/Greasemonkey_Manual:API. Except for `finalUrl: string;` in the Response Object.
- Haven't added typings for sync response (no info in the docs)

Authors: @kotas @basarat

### CODE REVIEW

**Comment by nikolay-borzov** [comment]
This is WIP. I need to amend some think after I viewed similar declarations

**Comment by ipcjs** [comment]
When I add the `jsconfig.js`, I can get the type information of GM4. So, how do I get the type information of GM3?
```
{
    "typeAcquisition": {
        "include": [
            "greasemonkey",
        ]
    }
}
```

**Comment by nikolay-borzov** [comment]
I don't think I understand. If you need a particular version install it using npm
```
npm i @types/greasemonkey@3.0.0
```
Can't find docs about `typeAcquisition`

**Comment by ipcjs** [comment]
@nikolay-borzov The official website does not have docs about `typeacquisition`, I found an article on a third-party website.  https://ticehurst.com/jsdocs/articles/types/ata.html

**Pull request merged**
