### PR TITLE
Node auth users settings update

### PR DESCRIPTION
**Pull request by randyn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  * [Auth Setting Changes](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/editor-api/lib/auth/users.js#L72)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-red__runtime/node-red__runtime-tests.ts
1. types/node-red__runtime/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c6e545d36c0825bdf48a7c8e7760ef76741c3dac
</p>

**Comment by Shaquu** [comment]
Hey, @randyn have you validated against new node-red version v4?

**Review by Shaquu — APPROVED** [review]
Okay, checked, looks fine.

I would look at `UsernamePermissions` type, though. 
Looks like it can contain `password` field. Probably we could rename it to `User` also?

**Comment by randyn** [comment]
> Okay, checked, looks fine.
> 
> I would look at `UsernamePermissions` type, though. Looks like it can contain `password` field. Probably we could rename it to `User` also?

Thanks for taking a look! And yeah, that does sound better. I can take a look at renaming and making more comprehensive typing later after this change

**Comment by randyn** [comment]
Ready to merge

**Pull request merged**
