### PR TITLE
Add packageManager field in package.json

### PR DESCRIPTION
**Pull request by remcohaszing**
This adds support for [corepack](https://nodejs.org/api/corepack.html). This means corepack users can just run `pnpm`, and corepack matches the version specified by the `packageManager` field.

This field is also respected by the [`pnpm/action-setup`](https://github.com/pnpm/action-setup) GitHub action. This is currently set to `latest`, but it may be better to remove that.

Arguably this makes the the `#/engines/pnpm` field in `package.json` redundant.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by sandersn** [comment]
This sounds like a fine idea to me, but I don't know what it means to fix to a specific version, especially since @jakebailey was bumping the pnpm version pretty frequently during the monorepo upgrade.

**Comment by remcohaszing** [comment]
The pinned below in the `engines` field is a version range and defines a minimum. The `packageManager` field must be an exact version.

**Comment by jakebailey** [comment]
I'm not totally sure how I feel about this; I definitely use this in my own projects and on TS itself, but on DT I'm not sure how I feel about this being pinned back.

I originally had this along with a script that would automatically bump it, but I opted to just leave engines instead. I've lost context on the full reason why.

It's possible that it just screwed with my automated script that performed the migration; it had to start with npm until complete but my stack switched the package manager at the first commit (I intended the PR to not have 200 commits...). So if I had done it differently it probably would have been fine. So maybe my misgivings are misplaced.

I'm definitely interested in thinking harder about it.

**Comment by jakebailey** [comment]
I'm probably okay with this, but we'd need to fix all of the other pipelines and tooling to make it work. Notably, there's no special pnpm install action for AzDo Pipelines, the publisher is just installing latest, etc. We also use npm for other things like publishing, so we'd have to make sure that it doesn't fall over if corepack says "no, use pnpm".

**Comment by remcohaszing** [comment]
As a corepack user I expected `pnpm install` to just work instead of throw on a version mismatch. Pinning wasn’t my goal, that’s a side effect. Note that this only pins the version for corepack users. Everything else could be kept as-is.

The following are all optional:

- The pnpm version in GitHub action can be removed, which makes it respect the `packageManager` field.
- The AzDo pipelines could use `corepack enable` instead of `npm install pnpm`, which makes it respect the `packageManager` field.
  - The AzDo pipeline could be replaced with a GitHub action. I’m not sure why 2 different CI systems are used. This also opens up the possibility for [npm provenance](https://docs.npmjs.com/generating-provenance-statements).
- pnpm could be used for publishing, but npm is fine too.

**Comment by jakebailey** [comment]
https://github.com/microsoft/DefinitelyTyped-tools/pull/777 should fix all of the cases I've found where corepack matters (disabling corepack when we want to run npm, which would normally fail because it says "hey, use pnpm").

**Comment by jakebailey** [comment]
https://github.com/microsoft/DefinitelyTyped-tools/pull/783 was another followup which should fix things more.

After that's released, then this should be good to go.

**Comment by jakebailey** [comment]
Well, besides maybe that we should install this specific release in other CI, but that's not too critical; really we want to do this to make it easier to develop in.

**Comment by jakebailey** [comment]
Okay, theoretically all of the last uses of npm without disable corepack strict mode should be fixed.

**Review by jakebailey — APPROVED** [review]

**Comment by remcohaszing** [comment]
Ready to merge

**Pull request merged**
