### PR TITLE
Add scrollreveal clean() method and cleanup option.

### PR DESCRIPTION
**Pull request by mack**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ X [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [clean()](https://scrollrevealjs.org/api/clean.html) and [cleanup](https://scrollrevealjs.org/api/cleanup.html)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## scrollreveal ([<kbd>unpkg</kbd>](https://unpkg.com/browse/scrollreveal@latest/))
was missing the following properties:
1. isSupported
1. debug
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ab50d82a1d57d70ee1942c4b5d2a130636f4399
</p>

**Review by Davidblkx — APPROVED** [review]

**Review by MysteryBlokHed — COMMENTED** [review]
Updating the tests (`scrollreveal-tests.ts`) to include the new functions will let the PR get merged. For example:

```typescript
sr.clean('.foo');
sr.destroy();
```

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by mack** [comment]
Ready to merge

**Pull request merged**
