### PR TITLE
Update Knockout.d.ts

### PR DESCRIPTION
**Pull request by abbasmhd**
add `objectForEach` and  `setPrototypeOf` to `KnockoutUtils` interface

### CODE REVIEW

**Comment by moonpyk** [comment]
objectForEachis exported by knockout (ref : https://github.com/knockout/knockout/blob/master/src/utils.js#L597)
but not setPrototypeOf

**Comment by moonpyk** [comment]
Confirmed http://knockoutjs.com/downloads/knockout-3.3.0.js, search for setPrototypeOf inside the minified file, it's not present at all.
If your code relies on that property and you start using a non-debug build you are gonna experience nasty crashes

**Comment by moonpyk** [comment]
Following this discovery I made another PR (see: #6197).

**Comment by abbasmhd** [comment]
thanks @moonpyk 
that's an excellent list, my codes only rely on `objectForEach`

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
