### PR TITLE
[hapi__vision] handlebars is a test dependency

### PR DESCRIPTION
**Pull request by jablko**
`@types/hapi__vision` [depends on](https://www.npmjs.com/package/@types/hapi__vision?activeTab=dependencies) Handlebars.js, but only for [its tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/63dccaf6c4dc285433a9725fc21b847601c66350/types/hapi__vision/hapi__vision-tests.ts#L8). Can we make it a `devDependency` instead?

This PR depends on and cherry picks a [proposed dtslint change](https://github.com/microsoft/DefinitelyTyped-tools/pull/428#issuecomment-1107635957), to allow `devDependencies`. That change is still under discussion.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## hapi__vision ([<kbd>unpkg</kbd>](https://unpkg.com/browse/hapi__vision@latest/))
was missing the following properties:
1. plugin
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6a265f5249c21515ec5b2b6a03eb47ee45301555
</p>

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Reopen this after dtslint change is approved or with some other workaround discussed in that change

**Comment by sheetalkamat** [comment]
@jakebailey has investigated this further 

> @hapi/vision provides template rendering support for hapi, handlebars is a templating engine that has an API that is compatible with vision, but there are many of them; @hapi/vision itself internally has tests that use handlebars (in their devDependencies), and in the types, the tests verify that the types of handlebars also work with the types for @hapi/vision

> so, users of vision may or may not use handlebars, so it doesn't make sense for @types/hapi__vision to pull in handlebars

So the correct fix would be to remove the dependency and update the tests.

**Comment by jakebailey** [comment]
Just to clarify, it's currently the case that devDeps aren't allowed (otherwise, the other PR would not be necessary), but it's also definitely the case that there are packages on DT already that "work with" other packages, and those packages seem to work fine as it is. I would be curious if those packages do this sort of testing, or if they're only "getting away with it" by accessing the types from tests only from other DT packages.

Otherwise, I'm not sure how valuable it is to verify that the API works with `handlebars` specifically (`@hapi/vision` presumably supports some 10+ other choices), instead of constructing a self-contained test.

**Comment by jakebailey** [comment]
A while later... dev deps are now allowed, so I updated this, however this package can actually be removed from DT as upstream is now typed (so it's a little moot).

**Comment by jakebailey** [comment]
jeeze bot, chill

**Pull request merged**
