### PR TITLE
Fixed apply return type, Exposed Interfaces, and Enforce Stricter Patch Typing

### PR DESCRIPTION
**Pull request by mramos-dev**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
Fixed apply function return type:
<<https://www.npmjs.com/package/fast-json-patch#jsonpatchapply--obj-object-patches-array-validate-boolean--boolean>>

Stricter Patch Typing:
<<https://tools.ietf.org/html/rfc6902>>

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by itsFrank** [comment]
(y)

**Comment by itsFrank** [comment]
👍

**Comment by itsFrank** [comment]
Not too sure if that is how i accept a PR...
Never been a reviewer before, wasn't aware i was one for this package either sorry

**Comment by MRamos62786** [comment]
I believe that's it and now a maintainer of this repo will have to merge it. Thanks!

**Comment by andy-ms** [comment]
Sorry for the delay!

**Comment by andy-ms** [comment]
Actually, this package provides its own types and will be deleted from DefinitelyTyped. Could you make a pull request to https://github.com/Starcounter-Jack/JSON-Patch instead?

**Pull request merged**
