### PR TITLE
[@types/eslint] Add 12 and 2021 to ParserOptions's ecmaVersion

### PR DESCRIPTION
**Pull request by VitorLuizC**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/eslint/eslint/pull/13603
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]

**Review by JounQin — CHANGES_REQUESTED** [review]
Wait https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52248 first

**Comment by bradzacher** [comment]
I thought it wasa better to get this in first so it fixed the formatting, then it's easier to review the changes in #52248

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
> I thought it wasa better to get this in first so it fixed the formatting, then it's easier to review the changes in #52248

OK

**Review by amcasey — APPROVED** [review]

**Comment by bradzacher** [comment]
Ready to merge

**Pull request merged**
