### PR TITLE
[CodeMirror] Add onchanges that triggers on a per operation basis.

### PR DESCRIPTION
**Pull request by Carreau**
cf doc for this event:
http://codemirror.net/doc/manual.html#event_changes

Thanks !

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, faillure seem unrelated to that.... it seem it had to do with previously merged PR #4857 that touch `Position`

**Comment by Carreau** [comment]
I would say that Position has now a `new (line: number, ch: number): Position;` which should be made optional IIUC. Not sure. @jacqt seem to have made the previous changes. Thoughts ?

**Comment by vvakame** [comment]
@mihailik @jacqt could you review this PR?

**Comment by vvakame** [comment]
related? #5149

**Comment by vvakame** [comment]
@Carreau thanks mate!

**Comment by Carreau** [comment]
Great ! Thanks ! (did you changed your avatar ?)

**Pull request merged**
