### PR TITLE
Add styletron-standard types

### PR DESCRIPTION
**Pull request by erictaylor**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by erictaylor** [comment]
These types are required for #35349.

**Comment by frenic** [comment]
CSS types are copied originally from `csstype`. It should preferably be used as a dependency instead. What do you think?

**Comment by erictaylor** [comment]
@frenic I agree 100% if they were copied. From what I could tell there didn't seem to be a reason why we couldn't just use `csstype`, which I would prefer to do. I just was uncertain the reason why `styletron` wasn't using `csstype` itself. I'll push a commit to use `csstype`.

**Comment by erictaylor** [comment]
02f950f uses definitions from `csstypes`, fixes missing and updates minimum TypeScript version to 2.9.

**Comment by frenic** [comment]
Styletron copied the Flow types from `csstype` because there was some issues with Flow when using it as a dependency at the time. Not sure whether it's still an issue or not. Related https://github.com/styletron/styletron/issues/228

**Comment by erictaylor** [comment]
> Styletron copied the Flow types from `csstype` because there was some issues with Flow when using it as a dependency at the time. Not sure whether it's still an issue or not. Related [styletron/styletron#228](https://github.com/styletron/styletron/issues/228)

Thanks for feedback and insight!

**Pull request merged**
