### PR TITLE
Add missing options for .map(), .filter(), .promisifyAll(), and .nodeify() in bluebird.d.ts

### PR DESCRIPTION
**Pull request by 13xforever**
As per [API](https://github.com/petkaantonov/bluebird/blob/master/API.md)

### CODE REVIEW

**Comment by vvakame** [comment]
*bluebird/bluebird.d.ts*

to author(@Bartvds). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
and #3997

**Comment by 13xforever** [comment]
Merged with master to solve the conflict.

**Comment by vvakame** [comment]
@13xforever okay, I decided merge this PR. thanks mate!

**Pull request merged**
