### PR TITLE
[yt-player] Update v3.5

### PR DESCRIPTION
**Pull request by Jolg42**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/feross/yt-player/compare/v3.4.3...v3.5.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Thanks! 😃

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## yt-player ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yt-player@latest/))
was missing the following properties:
1. once
1. errorMonitor
1. EventEmitter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c79889cacfae2a96ac19994b64ffaf1de3f4772c
</p>

**Comment by troeggla** [comment]
Thanks @Jolg42 !

I didn't hit *Approve* yet because of that comment by @danger-public. But looking at the source of the package, I don't see any properties named `once` or `errorMonitor`, so it might be a false alarm.

Do you want to take another look or shall I just approve it? As far as I'm concerned it's fine as it is.

**Comment by Jolg42** [comment]
@troeggla I also had a look, and it looks like a false alarm to me 😄 Thanks!

**Review by troeggla — APPROVED** [review]
Thanks for the update!

**Comment by Jolg42** [comment]
Ready to merge

**Pull request merged**
