### PR TITLE
[react-beautiful-dnd] fix some types

### PR DESCRIPTION
**Pull request by declan-warn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
  > **Note**
  > See the breakdown below.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

# Breakdown

There were a number of issues with the existing types. I made the following changes.

## Adding `| null` to types
`react-beautiful-dnd` uses flow for typing. Its type definitions make extensive use of flow's [Maybe types](https://flow.org/en/docs/types/maybe/) which translate to TypeScript as follows:
```typescript
type FlowObject = {
  key: ?Value;
}

type TSObject = {
  key: Value | null | undefined;
}
```

These had been incorrectly translated in the past as optional properties.

Relevant source:
- [General types](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/types.js)
- [Droppable types](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/droppable/droppable-types.js)
- [Draggable types](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable/draggable-types.js)

## ~~`children` function return types~~
~~The `children` functions were typed as returning a `ReactElement` but the original flow typings use [flow's React.Node](https://flow.org/en/docs/react/types/#toc-react-node) type. These have been changed to use `ReactNode`.~~

Relevant source:
- [Droppable](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/droppable/droppable-types.js#L78)
- [Draggable](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/view/draggable/draggable-types.js#L159)

## `getContainerForClone` should return `HTMLElement`
The previous type for the `getContainerForClone` prop was a function returning a `ReactElement`. This is incorrect, and it should instead return an `HTMLElement` to use as a target for a portal.

This is mentioned in the [library documentation](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/reparenting.md#droppable---getcontainerforclone).

## `DraggableStateSnapshot` was missing `isClone`
This property is not documented anywhere but is present in the [flow typing](https://github.com/atlassian/react-beautiful-dnd/blob/2360665305b854434e968e41c7b4105009b73c40/src/view/draggable/draggable-types.js#L113). It is also referenced in [example code](https://github.com/atlassian/react-beautiful-dnd/blob/2360665305b854434e968e41c7b4105009b73c40/stories/src/primatives/quote-item.jsx#L13).

## Missing props from v12
The version 12 typings were missing some props on the `DragDropContext`. The props were added in the v13 types, but were present in v12 as well.

From [the documentation](https://github.com/atlassian/react-beautiful-dnd/blob/v12.2.0/docs/api/drag-drop-context.md):
- `liftInstruction`
- `nonce`
- `enableDefaultSensors`

### CODE REVIEW

**Review by alexreardon — APPROVED** [review]

**Comment by alexreardon** [comment]
I am the author of `react-beautiful-dnd` I am supportive of these type fixes. Thanks @declan-warn!

**Review by brianspowers — APPROVED** [review]

**Review by brianspowers — APPROVED** [review]

**Comment by alexreardon** [comment]
@declan-warn mentioned to me that he is making one more type correction. He will provide context on that one soon

**Comment by declan-warn** [comment]
`react-beautiful-dnd` provides `null` as the value for some style properties ([example](https://github.com/atlassian/react-beautiful-dnd/blob/2360665305b854434e968e41c7b4105009b73c40/src/view/draggable/get-style.js#L40)).

But `null` is not considered a valid value for `React.CSSProperties` (what the `style` prop expects).

Although `null` causes a type error, it appears to behave the same way as `undefined` when used as a property value on the `style` prop. That is why the existing (incorrect) typings were working fine.

For this reason I've removed the `| null` addition for style properties. This means the types for style properties are not accurate, but it should avoid unnecessary friction.

**Review by alexreardon — APPROVED** [review]

**Comment by alexreardon** [comment]
I have hashed out these changes with @declan-warn. They are nuanced because we want to be accurate to the flow types, accurate to the `rbd` code itself, as well as wanting to work well with react types. @declan-warn has spent many hours wrestling with and testing these definitions. If we run into any issues with these types the plan is to fix these types as well

**Comment by alexreardon** [comment]
cc @brianspowers

**Review by aruniverse — APPROVED** [review]
Lgtm. But make sure to add yourself to the list of authors like Alex said in another comment

**Comment by declan-warn** [comment]
Thanks for reviewing @aruniverse, I have added my name to the list now.

**Review by aruniverse — APPROVED** [review]

**Review by alexreardon — APPROVED** [review]

**Comment by aruniverse** [comment]
Ready to merge

**Pull request merged**
