### PR TITLE
[mapbox-gl] fix dtslint warnings

### PR DESCRIPTION
**Pull request by dmytro-gokun**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by dmytro-gokun** [comment]
@typescript-bot merge

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by dmytro-gokun** [comment]
Ready to merge

**Comment by dmytro-gokun** [comment]
@sandersn Sorry for bothering you, but why this PR is not getting merged for so long? Is there any problem with it?

**Comment by sandersn** [comment]
It's [on the board for maintainer review](https://github.com/DefinitelyTyped/DefinitelyTyped/projects/5?card_filter_query=45233), I believe because the bot will only allow self-merge when another package author has signed off -- @dobrud @patrickr @macobo @LiamAttClarke @life777 @mklopets @amxfonseca in this case.

@orta you can probably confirm whether that's the rule being used here.

**Comment by orta** [comment]
Yep, this hasn't been reviewed by module owners yet - so after a week of no reviews by module owners it moves to the DT maintainers to review. Peter isn't a DT admin, nor a module owner, so it was just a positive passerby review. 

I triage based on the oldest from when was added to the 'needs maintainer review' time,  so it would have got around to that.

**Comment by orta** [comment]
But while I'm here, looks good - thanks!

**Pull request merged**
