### PR TITLE
Add react-resize-detector

### PR DESCRIPTION
**Pull request by matthew-matvei**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by matthew-matvei** [comment]
To maintainers: seems like `npm run test` would be a useful command to prompt contributors to run in the template before beginning the PR. Since the CI checks do this, `npm run lint package-name` isn't quite enough.

**Review by plantain-00 — CHANGES_REQUESTED** [review]
A test file is required

**Comment by matthew-matvei** [comment]
Is it? Docs don't say that, neither does the template. Seems simple enough to add that to the list of automated CI checks to save wasting your own time.

Anyway, test file added. Let me know if it needs tweaking.

**Review by plantain-00 — APPROVED** [review]

**Comment by armanio123** [comment]
Thanks for the input in regards to updating the docs. I will appreciate if you can create an issue for us so that we can keep track of this.

**Pull request merged**
