### PR TITLE
Sync frida-gum typings with Frida 12.11.16

### PR DESCRIPTION
**Pull request by oleavr**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://frida.re/news/2020/07/24/frida-12-11-released/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by oleavr** [comment]
(CI failure was unrelated to this PR.)

**Comment by oleavr** [comment]
@amcasey 👋 Heya, and sorry to bother you. It seems there might be an issue with the CI, as this is failing due to an unrelated package:

`Error: File ./types/markedjs__html-differ/lib/logger.d.ts listed in OTHER_FILES.txt is already reachable from tsconfig.json.`

**Comment by jablko** [comment]
@oleavr The CI failure fell in the window between releasing [@definitelytyped/definitions-parser v0.0.54](https://github.com/microsoft/DefinitelyTyped-tools/commit/dfb84eb1d27d9db46e92fcd2490ab41525104db7), which includes microsoft/DefinitelyTyped-tools#93, and landing #44091, which I've now marked ready for review.

The DefinitelyTyped-tools change enables it to find files that previously required exceptions, and #44091 removes those exceptions. The changes are interdependent: Regardless of which lands first, there's a window of CI failure. Apologies!

**Comment by sandersn** [comment]
master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

**Review by mrmacete — APPROVED** [review]
LGTM

**Comment by oleavr** [comment]
Ready to merge

**Pull request merged**
