### PR TITLE
firefox-webext-browser: add `world` argument to `RegisteredContentScript`

### PR DESCRIPTION
**Pull request by KillariDev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by jsmnbom — CHANGES_REQUESTED** [review]
Please fix upstream. Either in Mozilla's own code or with an override in https://github.com/jsmnbom/definitelytyped-firefox-webext-browser

**Comment by MicahZoltu** [comment]
@jsmnbom Where exactly is "upstream" for this if not here?

**Comment by jsmnbom** [comment]
In the repo i linked or at https://hg.mozilla.org

**Comment by jsmnbom** [comment]
Oh looking at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript it seems that firefox doesn't currently support the world parameter, and it would therefore not be included in the json files that mozilla includes with firefox. These types are only supposed to be used for webextension development with firefox, and chrome specific features should not be included.

**Comment by KillariDev** [comment]
It's in the documentation thought? I wonder if the typing should support it even if it didn't work in Firefox?

**Comment by jsmnbom** [comment]
The documentation for webextensions in general yeah. But not firefox-webext-browser..

**Comment by jsmnbom** [comment]
And even if these typings should support it, it should be done at https://github.com/jsmnbom/definitelytyped-firefox-webext-browser instead of here, since otherwise they'd just immediately get overwritten next time someone uses the generator to autogenerate the typings.

**Comment by MicahZoltu** [comment]
> The documentation for webextensions in general yeah. But not firefox-webext-browser..

I could be wrong here, but my understanding was that this library (`firefox-webext-browser`) is a polyfill to port Chrome's non-standard `chrome` namespace to the "standard" `browser` namespace.  A user would use this library to make a cross-platform extension that works on both Firefox and Chrome.

In this case, Firefox doesn't support the `world` property yet, but since it is an extra property Firefox will just ignore it if present.  I *believe* that Chrome needs this in some cases for Manifest v3 extensions, so without being able to pass the `world` parameter you can't make the extension work in Chrome unless you typecast or you use the `chrome` namespace directly.

While I can appreciate your general apprehension about adding chrome only items to this library, the fact that Mozilla documents it and that it is an optional parameter makes it feel like adding it would be acceptable?

**Comment by jsmnbom** [comment]
> I could be wrong here, but my understanding was that this library (firefox-webext-browser) is a polyfill to port Chrome's non-standard chrome namespace to the "standard" browser namespace. A user would use this library to make a cross-platform extension that works on both Firefox and Chrome.

That was not my intention when writing it no. Tho I will admit, that perhaps that is how people are using it now, and you may be right in that it should be supported.

However, please do open a discussion at https://github.com/jsmnbom/definitelytyped-firefox-webext-browser rather than here, since i know the DefnitelyTyped team does not like long running discussions in PRs, and it's at https://github.com/jsmnbom/definitelytyped-firefox-webext-browser this should be fixed, (more specifically with an override in https://github.com/jsmnbom/definitelytyped-firefox-webext-browser/blob/master/src/overrides.ts), so it doesn't just immediately get reverted in the future.

**Pull request closed without merging**
