### PR TITLE
react-native-vector-icons allow multiple style props for fontawesome5

### PR DESCRIPTION
**Pull request by codebure-au**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url here](https://github.com/oblador/react-native-vector-icons/blob/master/lib/create-multi-style-icon-set.js#L39)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Justification for change:
Currently the type definition for FontAwesome 5 icons only allows for defining at max one style prop ("solid", "light", "brands"), but the code allows for defining multiple/all of them, it simply applies the first one that has a value of true. This change allows for turning on/off style props as desired using variables.

### CODE REVIEW

**Review by iRoachie — CHANGES_REQUESTED** [review]
The code looks okay, but please undo all the formatting changes as they don't refer to this PR

**Comment by indentedspace** [comment]
> The code looks okay, but please undo all the formatting changes as they don't refer to this PR

I've double checked the changed files, it looks like they were formatted according to the prettierrc.json in the root of this repository. I can undo the formatting changes if absolutely required but it seems that the code should be formatted as committed.

**Comment by iRoachie** [comment]
That’s okay we could always do that in another PR. Keeping the commit focused on one thing makes it easy to do reverts if needed.

**Comment by indentedspace** [comment]
I have gone through and removed any formatting changes. Please let me know if any further changes are required.

**Review by iRoachie — APPROVED** [review]

**Comment by indentedspace** [comment]
Ready to merge

**Pull request merged**
