### PR TITLE
Nightwatch add missing options property to browser type and fix test_settings type

### PR DESCRIPTION
**Pull request by wallzero**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This is primarily a bug fix; the `options` type was missing. Also, created NightWatchTestSettingGeneric since the `screenshots` property is different in `settings` and the `browser.options`. Also fixed `test_settings` type to be an object containing `NightWatchTestSettingScreenshots`.

### CODE REVIEW

**Comment by rkavalap** [comment]
@Schlesiger The changes overall looks good. Can you add references for custom commands as well custom assertions please. Looks like travis is not liking the existing definition. Can you change the signature directly to any.

**Comment by rkavalap** [comment]
Thank you for working on this. It's been a while I looked into this. I will try these changes in my NightwatchTest repo when i can find some time.

**Comment by Schlesiger** [comment]
@rkavalap Apologies I do not understand what you mean by "add references". I have fixed the TravisCI error.

**Comment by rkavalap** [comment]
@Schlesiger 
I mean't 
```interface NightwatchBrowser extends NightwatchAPI, NightwatchCustomPageObjects { }```
should be 
```interface NightwatchBrowser extends NightwatchAPI, NightwatchCustomCommands, NightwatchCustomAssertions, NightwatchCustomPageObjects { }```

**Comment by aozgaa** [comment]
@Schlesiger, please make the requested change.

**Comment by RyanCavanaugh** [comment]
@Schlesiger please change or address the above comment

**Comment by Schlesiger** [comment]
@rkavalap @aozgaa @RyanCavanaugh My apologies; otherwork had distracted me and the previous reminders were buried. I've reintegrated the custom interfaces as requested.

**Comment by rkavalap** [comment]
LGTM

**Pull request merged**
