### PR TITLE
Update VictoryLabelProps style type definition

### PR DESCRIPTION
**Pull request by danielmichaelni**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://formidable.com/open-source/victory/docs/victory-label#style

Prettier automatically re-formatted the file to use 4 spaces, which obscures the type definition update when viewing the diff. Let me know if I should disable prettier to maintain using 2 spaces.

### CODE REVIEW

**Comment by ibarrae** [comment]
Hey @danielmichaelni, could you please just update what you specifically changed? There are some changes from single quotes to double quotes and also some indentations :disappointed_relieved: this makes it almost impossible to review

**Comment by danielmichaelni** [comment]
@ibarrae the specific change is on line 217 where I changed `style?: React.CSSProperties;` to `style?: React.CSSProperties | React.CSSProperties[];`

Would it be better if I ran `prettier` in a pr and then made this change in another pr?

**Comment by ibarrae** [comment]
If you could split into two separate commits (prettier and actual change) would also make it easy for review, and also don't forget to add a test that reflects this change please :smile: @danielmichaelni

**Comment by danielmichaelni** [comment]
@ibarrae done. thanks for the suggestion!

**Comment by ibarrae** [comment]
LGTM @danielmichaelni, I think I can't approve it since nobody is assigned as a reviewer :disappointed:

**Review by ibarrae — APPROVED** [review]
LGTM!

**Comment by orta** [comment]
Looks good to me too 👍

**Pull request merged**
