### PR TITLE
@types/react-native: fix StyleSheet.create() styles parameter

### LINKED ISSUE #36357: @types/react-native: StyleSheet.create() invalid styles parameter
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @huhuanming, @iRoachie, @skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @bm-software, @a-tarasyuk, @mvdam, @esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

### Problem

Trigger autocompletion list (it's empty) - **BAD**

Screen Shot 2019-06-21 at 21 43 09

Write any char (list is not empty) - **GOOD**

Screen Shot 2019-06-21 at 21 43 20

Trigger autocompletion second time when there's `height` prop (it's empty) - **BAD**

Screen Shot 2019-06-21 at 21 43 27

Write any char when there's `height` prop (it's empty) - **BAD**

Screen Shot 2019-06-21 at 21 43 34

As you can see in pictures it works the only the first time and only if I type some character, but the second time it doesn't work and I can't trigger suggestions list to see properties I can modify because the list is empty and I get built-in VS Code snippets, etc.

### If I change from `styles: T` to `styles: T | NamedStyles<T>`

Screen Shot 2019-06-21 at 21 48 39
Screen Shot 2019-06-21 at 21 48 51
Screen Shot 2019-06-21 at 21 48 58
Screen Shot 2019-06-21 at 21 49 09
Screen Shot 2019-06-21 at 21 49 27

As you can see in pictures if I change from `styles: T` to `styles: T | NamedStyles<T>` in `StyleSheet.create()` everything works as expected.

### PR DESCRIPTION
**Pull request by svipas**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36357

/cc @alloy, @huhuanming, @iRoachie, @skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @bm-software, @a-tarasyuk, @mvdam, @esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

### CODE REVIEW

**Review by Esemesek — APPROVED** [review]
LGTMT

**Review by alloy — CHANGES_REQUESTED** [review]
Can you please add a test that demonstrates the previously not working code?

**Comment by svipas** [comment]
@alloy How I should do that?

**Comment by alloy** [comment]
By adding a example to the test file that is supposed to work. It is meant so we don’t regresa on it in the future.

**Comment by svipas** [comment]
@alloy Thanks for the info. I will update this PR today.

**Comment by svipas** [comment]
@alloy I re-opened a PR and added tests: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36554

**Pull request closed without merging**
