### PR TITLE
Ember update to 2.7

### PR DESCRIPTION
**Pull request by webbiesdk**
I looked into updating ember from version 2.0 to version 2.7. 

First up i made a big change. Instead of having essentially 3 duplicates of the same declaration, i used the `typeof` operator and `export = Ember` to have just 1 copy of the declaration, that is then referenced twice. 
This makes it so you cannot use the "Em" name for types, you have to use the Ember name. (The change has been made in the 
But for code without type annotations, the `Em` object still works there. 

This makes the declaration file significantly easier to maintain, as any changes to the Ember object does not have to be made in 3 places. 

Then i updated the declaration to better match the 2.7 implementation. 
I might not have gotten everything, but I think most of the changes has been included. 

I could have split it into 2 pull requests, but those 2 pull-requests would conflict, so I decided on just this one.

### CODE REVIEW

**Comment by jedmao** [comment]
Hmm... not being able to use `Em.` would break a lot of my code (basically all of it), so I don't think that part of this PR is acceptable.

**Comment by minestarks** [comment]
Hmmm I think this is a good change (really I don't think Em should have been introduced to the type definition as it doesn't seem to be part of the API) but unfortunately breaking existing code is a concern as @jedmao pointed out. Is there a compromise that can be made here?

**Comment by webbiesdk** [comment]
`Em` is kinda part of the API, it is a shorthand for Ember. As in: `window.Ember === window.Em` evaluates to true. 

So the line `var Em : typeof Ember` should definitely be kept. 

The only compromise I can see is to re-introduce some redundancy. Since I don't know of any other way to get a type like `Em.Object` to work without having an `Object` type directly on the `Em` object. 

It can come down from the original 3 times redundancy (The real `Ember`, the shorthand `Em` and the exported module `"Ember"`) to 2 times redundancy (The real `Ember` and the shorthand `Em`). 

But I don't like that, because it is ugly. 

The declaration was 1.X until recently, so the way I see it, a lot of people upgrading will have breaking changes anyway.

**Comment by jedmao** [comment]
I didn't like writing it either, but at the end of the day, it HAS to work! `Em` has to work!

**Comment by webbiesdk** [comment]
Just to be clear, some of `Em` still works, you can still write `var test = Em.Object.create(...)`. 
You just can't write `var test : Em.Object = ....". 
So nothing will change in the compiled output, it is only the type-annotations in the TypeScript files that will be changed. 

If you insist that one must be able to write `var test : Em.Object = ...`, I'll re-introduce the redundancy for the `Em` object.

But it is ugly, and it makes maintenance of the declaration file more difficult and more error-prone.

**Comment by minestarks** [comment]
Hmm sorry I didn't realize "Em" was there in the API. I think expecting it to work in type annotations as well is reasonable, as ugly as the duplication is. I'll leave this PR open for a while to see if there's more feedback.

**Comment by jedmao** [comment]
What you've done w/ `export = Ember` solves much of the duplication, but my vote would be to keep the duplication that allows one to use `Em.Object`. It might be ugly, but it works, it uses typeof so it's not rewriting the declarations and that part of the API rarely changes.

**Comment by webbiesdk** [comment]
I re-introduced the duplication of the `Em` object. 

I made it from scratch, so now we can be sure that the Em object and the Ember object aren't out of sync.

**Comment by jedmao** [comment]
👍

**Comment by minestarks** [comment]
Thank you!

**Pull request merged**
