### PR TITLE
[cacheable-request][responselike] Remove types

### PR DESCRIPTION
**Pull request by BendingBender**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by BendingBender** [comment]
Ready to merge

**Comment by BendingBender** [comment]
Ready to merge

**Comment by mfazekas** [comment]
@BendingBender we're getting  `Cannot find type definition file for 'responselike'` at 

See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62111 for details.

**Comment by BendingBender** [comment]
@mfazekas You still need to install the definitions if you use `responselike` < v3. You can install them with:
```sh
npm i -D @types/responselike@1.0.0
```

**Comment by BendingBender** [comment]
See: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62111#discussioncomment-3557529

**Pull request merged**
