### PR TITLE
feat(node): pass generic function implementation to `mockImplementation` and `mockImplementationOnce` for node:test

### PR DESCRIPTION
**Pull request by bacebu4**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/test.html#ctxmockimplementationimplementation
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

# Reasoning of this PR

Related discussion: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68439

It's kinda similar to #68440 (but it closed) but has narrower scope. I think the narrower scope is preferred cause the previous PR doesn't receive much attention and we should firstly merge the base changes proposed there and then reconsider bringing other changes

Also this PR is modifying really small portion of typings which will be easier to review to all maintainers

### CODE REVIEW

**Comment by bacebu4** [comment]
Failing tests are known to be failing, seems unrelated

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by bacebu4** [comment]
Well, I don't know what to do to make CI pass, I got failed tests on code that is commented out and was not touched by changes of the PR

Hope to get some help here (but the bot saying that "builds that are failing do not end up on the list of PRs for the DT maintainers to review" which means I have to figure it on my own)

**Comment by jakebailey** [comment]
A recent bugfix to the `$ExpectType` rule exposed a large number of assertions which were not being correctly checked; I fixed some of them but there were a lot more than went unnoticed.

I'm going to revert the bugfix and address it later when I can run the entire DT and fix everything in one go.

**Review by gabritto — APPROVED** [review]

**Comment by bacebu4** [comment]
Ready to merge

**Pull request merged**
