### PR TITLE
Added typings for jquery cropbox plugin 

### PR DESCRIPTION
**Pull request by perkastman**
Hi, 

I added type definitions for the jquery cropbox plugin.

//Per

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.cropbox/jquery.cropbox.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.cropbox
  * http://bower.io/search/?q=jquery.cropbox
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.cropbox/jquery.cropbox-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
https://www.npmjs.com/package/jquery-cropbox
please rename jquery.cropbox/jquery.cropbox.d.ts to jquery-cropbox/jquery-cropbox.d.ts

**Comment by perkastman** [comment]
Ahh, good point, I missed that in the contribution guide and have renamed now.

**Comment by vvakame** [comment]
one more. rename jquery-cropbox/jquery-cropbox.tests.ts to jquery-cropbox/jquery-cropbox-tests.ts

**Comment by perkastman** [comment]
Fixed

**Comment by vvakame** [comment]
thanks mate!

**Comment by vvakame** [comment]
manually merge

**Pull request closed without merging**
