### PR TITLE
Adding PureMVC Standard and Multicore libraries

### PR DESCRIPTION
**Pull request by josefvn**

### CODE REVIEW

**Comment by vvakame** [comment]
*puremvc-multicore/puremvc-multicore-1.1.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/puremvc-multicore
  * http://bower.io/search/?q=puremvc-multicore
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (puremvc-multicore/puremvc-multicore-1.1-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*puremvc-standard/puremvc-standard-1.0.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/puremvc-standard
  * http://bower.io/search/?q=puremvc-standard
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (puremvc-standard/puremvc-standard-1.0-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by sparkbuzz** [comment]
@vvakame Thanks for the checklist.

**"Is collect naming convention?"** I looked at the contribution guide, and seems to be correct now, I removed the version numbers. The library I'm adding is located at these locations:

https://github.com/PureMVC/puremvc-typescript-multicore-framework
https://github.com/PureMVC/puremvc-typescript-standard-framework

Should I rename the folders to **puremvc-typescript-multicore-framework** and **puremvc-typescript-standard-framework** respectively, to reflect the repository name on GitHub?

Should the **Project** entry in the headers point to the repository URL rather than the projects' home page? It currently points to http://puremvc.org

Could you please elaborate what I must do with the links posted to the non-existent npm and bower repositories? Does this imply that the DT repository expects a Bower.io / npm package? PureMVC isn't hosted on npm or via Bower, it's only a GitHub repository.

I don't have a test file for this type definition, the library has its own test suite. Is a test file required, I'm only asking, because I see a lot of items in the repository that doesn't have test files. 

Travis tests are passing.

**Comment by vvakame** [comment]
@sparkbuzz test file is required. it is not for implementation. it is for typing.
test code helps strong definition file and reviewing incoming pull request.

**Comment by sparkbuzz** [comment]
@vvakame Thanks for the feedback. I'll need to look into the documentation to write a test file. This type definition for PureMVC is quite large, it's going to be a while until I'll find the time to write a test file.

**Pull request closed without merging**
