### PR TITLE
rename language to culture in numbro

### PR DESCRIPTION
**Pull request by olmobrutall**
This small changes renames `language` property for `culture` as it did in the library in version 1.8 https://github.com/foretagsplatsen/numbro/blob/develop/CHANGELOG.md

### CODE REVIEW

**Review by vbortone — APPROVED** [review]
👍

**Comment by DanielRosenwasser** [comment]
Looks like the library already has declaration files. https://github.com/foretagsplatsen/numbro/

Would you consider sending them a PR, removing this package, and adding it to the `notNeededPackages.json` file?

**Comment by olmobrutall** [comment]
@DanielRosenwasser done. I've removed the package and added it to notNeededPackages.json

 I've switched to the `numbro.d.ts` in the official repo but there are problems with `export default` that should be `export =`. 

I've made a PR there, https://github.com/foretagsplatsen/numbro/pull/232/commits, I think will be better to wait for the one there to be merged before merging this one.

**Comment by aozgaa** [comment]
We will wait on https://github.com/foretagsplatsen/numbro/pull/232

**Comment by minestarks** [comment]
@aozgaa any reason not to merge right away? Would be better to direct any new users to the official typings since we're not accepting PRs on this one anyway...

**Comment by paulvanbrenk** [comment]
Looks like this definition file is going to be the long term solution.

**Pull request merged**
