### PR TITLE
Add @styled-system/css typings

### PR DESCRIPTION
**Pull request by sebald**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

> NOTE: That this is unhelpful since it will also try to lint `csstype`...

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Looks like the problem is that TypeScript 2.0 has no idea how to parse the contents of `csstype`. Try setting an explicit minimum TypeScript version in the header https://github.com/DefinitelyTyped/DefinitelyTyped/tree/4a4cf23ff4301835a45bb138bbb62bf5f0759255#i-want-to-use-features-from-typescript-21-or-above

**Comment by sebald** [comment]
@DanielRosenwasser thanks! I thought I tried that already, whoops.

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by sebald** [comment]
No need to thank me. I am doing myself a favor here 😅

**Pull request merged**
