### PR TITLE
Adding typescript support for WebOTP API

### PR DESCRIPTION
**Pull request by plchampigny**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: (https://wicg.github.io/web-otp/#otpcredential)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/webappsec-credential-management/webappsec-credential-management-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7868ed8d1f9351480b441f00dee7103b31e15847
</p>

**Comment by plchampigny** [comment]
@sheetalkamat Could you re-review this (related to a previous review on #66279)?

**Review by andrewbranch — APPROVED** [review]
Support for OTPCredential seems to be about the same as PasswordCredential and FederatedCredential, so I think this is fine now.

**Comment by plchampigny** [comment]
Ready to merge

**Comment by plchampigny** [comment]
> Ready to merge

**Comment by plchampigny** [comment]
Ready to merge

**Pull request merged**
