### PR TITLE
feat(react): support onAuxClick & onAuxClickCapture events

### PR DESCRIPTION
**Pull request by foray1010**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
onAuxClick event is added since react 16.5.0: https://github.com/facebook/react/pull/13571#issue-213382661
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by ferdaber — APPROVED** [review]

**Comment by foray1010** [comment]
I am not sure how to pass the travis as it still throw `The job exceeded the maximum time limit for jobs, and has been terminated.` after I force pushed and run again

**Comment by foray1010** [comment]
@ferdaber @Jessidhia @johnnyreilly  A little help on this pr? seems react is depended by so many packages that it excesses the time limit of travis

**Comment by pshrmn** [comment]
@foray1010 you should be able to rebase your PR against the master branch and force push to keep it alive for now. Since @ferdaber approved this and the Azure tests passed, I think it is a matter of getting the attention of someone who can merge it to come in here.

**Comment by lukyth** [comment]
@foray1010 You can run the test locally and mention @sandersn if the tests pass so he could merge this PR manually.

**Comment by foray1010** [comment]
@sandersn I have pulled from master again and the test passed locally and on Azure. It failed in travis due to excess time limit. Could you manually merge this PR?

**Pull request merged**
