### PR TITLE
Update Howler to 2.0.0

### PR DESCRIPTION
**Pull request by tdukart**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://github.com/goldfire/howler.js/blob/v2.0.0/README.md .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by paladizm** [comment]
IHowlProperties also needs to be adjusted, it now needs to have a src that is a list of strings (not urls).

change line 29 `src?: string;` to `src?: string[];`

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by vvakame** [comment]
@tdukart could you resolve conflict?

**Comment by yuit** [comment]
@tdukart  Thanks for your contribution. This PR has merge conflict and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by connor4312** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12631

**Pull request closed without merging**
