### PR TITLE
Passport implementations

### PR DESCRIPTION
**Pull request by joshheyse**
Included missing username property on Facebook Profile
Added definitions for passport-google-oauth & passport-twitter to match passport-facebook

### CODE REVIEW

**Comment by vvakame** [comment]
*passport-facebook/passport-facebook.d.ts*

to author(@staticfunction). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*passport-google-oauth/passport-google-oauth.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/passport-google-oauth
  * http://bower.io/search/?q=passport-google-oauth
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (passport-google-oauth/passport-google-oauth-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*passport-twitter/passport-twitter.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/passport-twitter
  * http://bower.io/search/?q=passport-twitter
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (passport-twitter/passport-twitter-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by horiuchi** [comment]
LGTM :+1:

**Comment by staticfunction** [comment]
@joshheyse you can definitely put your name as the author there. That's 100% your code. I can take credit of it man :innocent: Other than that it's all good :+1:

**Comment by vvakame** [comment]
@horiuchi @staticfunction thanks!
@joshheyse thanks mate!

**Pull request merged**
