### PR TITLE
Add new @lerna/package-graph definitions

### PR DESCRIPTION
**Pull request by donmahallem**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test @lerna/package-graph`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I think the original module exports just one, single symbol:
https://github.com/lerna/lerna/blob/main/core/package-graph/index.js#L310
One should not export symbols which are not there. Exporting types/interfaces is OK and preferred. Otherwise people could try to create instances of those classes (`new CyclicPackageGraphNode()`, `new PackageGraphNode()`). you could also restructure your code to reflect package setup (create `lib` and relevant files) and then: 
```ts
import { Package } from '@lerna/package';
import { PackageGraphNode } from './lib/package-graph-node';
import { CyclicPackageGraphNode } from './lib/cyclic-package-graph-node';

declare type GraphType = 'allDependencies' | 'dependencies';
declare type NodeProperties = 'localDependencies' | 'localDependents';
declare class PackageGraph extends Map {
    ...
    ...
}

export type { GraphType, NodeProperties };
export { PackageGraph };
```
this will export only expected symbols explicitey and other symbols will be only acessed via usage

**Comment by donmahallem** [comment]
@peterblazejewicz Yeah, you do have a good point. I refactored it by your suggestions. 

```ts

declare type GraphType = 'allDependencies' | 'dependencies';
declare type NodeProperties = 'localDependencies' | 'localDependents';

```

is not accepted by the linter so I had to export it directly.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@donmahallem thx!

**Comment by donmahallem** [comment]
Ready to merge

**Pull request merged**
