### PR TITLE
fix(node): tls.Server events callback typing does not match NodeJS doc

### PR DESCRIPTION
**Pull request by Semesse**
- newSession callback takes no arguments
- resumeSession callback accepts null

According to Node.js doc, [`newSession`](https://nodejs.org/docs/latest-v18.x/api/tls.html#event-newsession) event callback takes no arguments and [`resumeSession`](https://nodejs.org/docs/latest-v18.x/api/tls.html#event-resumesession) callback also accepts arguments like `cb(null, data)` if no error occurs and the session can be resumed, or `cb(null, null)` if session cannot be resumed.

The following code copy-pasted from Node.js doc will not compile [[TS Playground](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBDANgZzgMyhEcDkTk4BQAxhAHbLzICmUAbrXALwIoB0xU1AhjNQMq0GUABQBKEuUqtkg5MmDl+MaNQBccAErVSUACYAeSlGBkA5gBo4AIQCuaNLQB8zOAG8AvoRr1abciI4ZNQA7nIK5DhWIsB6Vnq83FbEAEZizC5uhHAy4YpkyqoA2rFsKsom5oEAFtQAHjhiALquCTDc2XCp4oQeEj7C-mSBXMi2IALU8vlRcDFxXWkZ7p3dZLaIiFb4eUoqXCV6ZRAVpmY19Y0tAD7XcOubEn1AA)]
```typescript
import tls from 'tls'
const server = tls.createServer()
const tlsSessionStore: Record<string, Buffer> = {}
server.on('newSession', (id, data, cb) => {
  tlsSessionStore[id.toString('hex')] = data
  cb()
})
server.on('resumeSession', (id, cb) => {
  cb(null, tlsSessionStore[id.toString('hex')] || null)
})
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/docs/latest-v18.x/api/tls.html>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
please update from master to remove CI errors, sorry for inconvenience

**Comment by peterblazejewicz** [comment]
Please also add this to at least LTS version (v16)

**Comment by Semesse** [comment]
> Please also add this to at least LTS version (v16)

Oh I missed it. The interface hasn't changed since very early version of node, so should I also update v14?

**Comment by peterblazejewicz** [comment]
Yes, please, that's not complicated change. Just review with docs

**Review by mcollina — APPROVED** [review]
lgtm

**Review by sandersn — APPROVED** [review]

**Comment by Semesse** [comment]
Ready to merge

**Pull request merged**
