### PR TITLE
atom: support version 1.23

### PR DESCRIPTION
**Pull request by GlenCFL**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
[Atom v1.23 Blog Post](http://blog.atom.io/2017/12/12/atom-1-23.html)
[Atom v1.23 Release Page](https://github.com/atom/atom/releases/tag/v1.23.0)
[GrammarRegistry.onDidRemoveGrammar()](https://atom.io/docs/api/v1.23.1/GrammarRegistry#instance-onDidRemoveGrammar)
[TextEditor.insertText()](https://atom.io/docs/api/v1.23.1/TextEditor#instance-insertText)
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I believe these are all of the changes necessary to fully support Atom v1.23, which was another small update. The URI handling isn't handled via an API, so no additions are necessary on that front.

### CODE REVIEW

**Comment by GlenCFL** [comment]
Mentioning the other authors @lierdakil @smhxx

**Review by smhxx — APPROVED** [review]

**Review by lierdakil — CHANGES_REQUESTED** [review]
Sorry to block over a minor thing, but we're missing `Decoration::isType` which silently appeared somewhere between 1.22.0 and 1.23.1 https://atom.io/docs/api/v1.23.1/Decoration#instance-isType

**Comment by GlenCFL** [comment]
I'll add it. I've been using the history of each file to monitor API changes, but that's a bit iffy right now with the conversion of the code base from CoffeeScript to JavaScript.

**Comment by lierdakil** [comment]
You might consider `json-diff`ing `atom-api.json` (which is available on [Atom's GitHub releases page](https://github.com/atom/atom/releases) for each release), which is a quick way to see what changed in terms of *documented* API.

**Comment by GlenCFL** [comment]
@lierdakil I'll do that in addition to browsing the history.

**Comment by lierdakil** [comment]
Yeah... terribly sorry, tried following my own advice and found one more thing: https://atom.io/docs/api/v1.23.1/Selection#instance-insertText `preserveTrailingLineIndentation` was added in 1.23 apparently, should probably go into `TextInsertionOptions`

Also of note, [`Selection::insertText`](https://github.com/GlenCFL/DefinitelyTyped/blob/5356c1c1993a816379143d04581e5f202fc8c107/types/atom/index.d.ts#L4629) and [`TextEditor::insertText`](https://github.com/GlenCFL/DefinitelyTyped/blob/5356c1c1993a816379143d04581e5f202fc8c107/types/atom/index.d.ts#L1497) use the same `options` argument (since latter basically just calls former for each selection), but we're not using the same type `TextInsertionOptions` there.

**Review by lierdakil — APPROVED** [review]

**Comment by lierdakil** [comment]
Thanks!

**Pull request merged**
