### PR TITLE
[algoliasearch(-helper)] [algoliasearch-helper] remove packages

### PR DESCRIPTION
**Pull request by Haroenv**
Both of these packages are now shipping their own definitions and aren't used anywhere else, except algoliasearch-helper in react-instantsearch-core

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by orta** [comment]
Looks like there are dependencies in DT relying on the module `algoliasearch` giving types, is it possible the prod nom version of the package isn't including the types?

```
##[error]../react-instantsearch-core/node_modules/algoliasearch-helper/index.d.ts(15,8): error TS2307: Cannot find module 'algoliasearch' or its corresponding type declarations.
166

```

**Comment by Haroenv** [comment]
The types are included, but only since v4, maybe the CI somehow uses v3, since React InstantSearch is compatible with it? https://yarnpkg.com/package/algoliasearch?files

**Comment by Haroenv** [comment]
Next error is that ts-ignore is forbidden, but in our case in the line is needed to be able to accept both v3 (from @types/algoliasearch) and v4 (from `algoliasearch`) https://github.com/algolia/algoliasearch-helper-js/blob/develop/index.d.ts#L6-L20 is there some way to suppress the rule?

**Comment by Haroenv** [comment]
that's already done in the previous commit @orta, thanks, the error now is different, à la https://github.com/microsoft/dtslint/issues/297

**Pull request closed without merging**
