### PR TITLE
Fixing #4058 for passport-local by adding support for passReqToCallback = true or false

### PR DESCRIPTION
**Pull request by wjohnsto**
Fixes #4058

### CODE REVIEW

**Comment by vvakame** [comment]
*passport-local/passport-local.d.ts*

to author(@SomaticIT). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by AndreasGassmann** [comment]
I can confirm that this solution is working.

There is only one small issue: When passing ```passReqToCallback = false``` as an option, it will use the VerifyFunctionWithRequest interface, so it still expects a function with 4 parameters.
Since the default of passReqToCallback is false, this can easily be solved by just not passing ```passReqToCallback``` if it's false.
I can't think of any way to get around this problem. But in any case, this will work in almost all regular cases (and is definitely better than the current version). :+1:

**Comment by wjohnsto** [comment]
@AndreasGassmann It is frustrating that we can't make it work with `passReqToCallback = false`, but I'm afraid there is no other solution.

**Comment by vvakame** [comment]
@AndreasGassmann thanks!
@wjohnsto thanks mate!

**Comment by SomaticIT** [comment]
Sorry for my late reply, it's ok for me, thanks.

**Pull request merged**
