### PR TITLE
Added missing @types/react dependency in @types/meteor.

### PR DESCRIPTION
**Pull request by radekmie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54927
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by radekmie** [comment]
@KeithGillette Can you make sure that you don't have any `@types/react` in your `package-lock.json`? It looks like this dependency should not be needed (it's implicit).

**Comment by KeithGillette** [comment]
Hi @radekmie. `@types/react` is definitely not in our `package.json`. Here's where it shows up in `package-lock.json`:

**With `@types/meteor@1.4.72`:**
```json
    "@types/meteor": {
      "version": "1.4.72",
      "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.72.tgz",
      "integrity": "sha512-KXHD9XI2kC666ILgCVRqklgpbn/1vgllg1dN3vmXC1tMqu+TZMfDH7UJZQmmL3eBJN/BGtMMlxz4ylzRkHjgqg==",
      "dev": true,
      "requires": {
        "@types/connect": "*",
        "@types/mongodb": "*",
        "@types/react": "*",
        "@types/underscore": "*"
      }
    },

…

    "@types/react": {
      "version": "16.7.13",
      "resolved": "https://registry.npmjs.org/@types/react/-/react-16.7.13.tgz",
      "integrity": "sha512-WhqrQLAE9z65hfcvWqZfR6qUtIazFRyb8LXqHo8440R53dAQqNkt2OlVJ3FXwqOwAXXg4nfYxt0qgBvE18o5XA==",
      "requires": {
        "@types/prop-types": "*",
        "csstype": "^2.2.0"
      }
    },

…

    "angular2-meteor": {
      "version": "0.8.0",
      "resolved": "https://registry.npmjs.org/angular2-meteor/-/angular2-meteor-0.8.0.tgz",
      "integrity": "sha512-fkZt59aIHmglwJ3hEqB9NMqUWly9AGgBCGMRITJfoI4Z58hcm3hp0WLGoJPaU13yr6wEPrZ/Hm9N4judtzjVWg==",
      "requires": {
        "@types/meteor": "^1.3.31",
        "underscore": "^1.8.3"
      },
      "dependencies": {
        "@types/meteor": {
          "version": "1.4.23",
          "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.23.tgz",
          "integrity": "sha512-TWhPFOC4b1/ui8FvqH4iIq6LNkY6qQTabmQjwSkrjmNpcF4CjIUSPZ6Rf8OGQ1fSbfLVgDbsK1vMOCS48mj5Qg==",
          "requires": {
            "@types/connect": "*",
            "@types/react": "*",
            "@types/underscore": "*"
          }
        }
      }
    },
```

**With `@types/meteor@1.4.76`:**
```json
    "@types/meteor": {
      "version": "1.4.76",
      "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.76.tgz",
      "integrity": "sha512-Hnem5BtouhbEP+6zS8wHy5TowL13m72jKVL2dZr/KwbNWpEihTUOsFjhRo88fjRaukhJjxwCB5hEFtAx5edS9g==",
      "dev": true,
      "requires": {
        "@types/connect": "*",
        "@types/jquery": "*",
        "@types/mongodb": "^3.6.20",
        "@types/react": "*",
        "@types/underscore": "*"
      }
    },

…

    "@types/react": {
      "version": "16.7.13",
      "resolved": "https://registry.npmjs.org/@types/react/-/react-16.7.13.tgz",
      "integrity": "sha512-WhqrQLAE9z65hfcvWqZfR6qUtIazFRyb8LXqHo8440R53dAQqNkt2OlVJ3FXwqOwAXXg4nfYxt0qgBvE18o5XA==",
      "requires": {
        "@types/prop-types": "*",
        "csstype": "^2.2.0"
      }
    },

…

    "angular2-meteor": {
      "version": "0.8.0",
      "resolved": "https://registry.npmjs.org/angular2-meteor/-/angular2-meteor-0.8.0.tgz",
      "integrity": "sha512-fkZt59aIHmglwJ3hEqB9NMqUWly9AGgBCGMRITJfoI4Z58hcm3hp0WLGoJPaU13yr6wEPrZ/Hm9N4judtzjVWg==",
      "requires": {
        "@types/meteor": "^1.3.31",
        "underscore": "^1.8.3"
      },
      "dependencies": {
        "@types/meteor": {
          "version": "1.4.23",
          "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.23.tgz",
          "integrity": "sha512-TWhPFOC4b1/ui8FvqH4iIq6LNkY6qQTabmQjwSkrjmNpcF4CjIUSPZ6Rf8OGQ1fSbfLVgDbsK1vMOCS48mj5Qg==",
          "requires": {
            "@types/connect": "*",
            "@types/react": "*",
            "@types/underscore": "*"
          }
        }
      }
    },
```

Given these results, I'm not sure why updating `@types/meteor` beyond `1.4.72` is causing this `tsc` transpilation error in our project:
```
Error: node_modules/@types/meteor/react-meteor-data.d.ts:13:86 - error TS2694: Namespace 'React' has no exported member 'DependencyList'.

13 export function useTracker<TDataProps>(getMeteorData: () => TDataProps, deps?: React.DependencyList): TDataProps;
 ```
However, in either case, when I look in `node_modules/@types/react`, I do not see `DependencyList` as a member, either under `1.4.72` or `1.4.76` for the installed type definitions for React 16.7.

**Comment by radekmie** [comment]
@KeithGillette please try this:

```sh
meteor npm i -D @types/react
meteor npm r @types/react
```

It should update your transient `@types/react` dependency and make it work. It seems like we cannot clearly depend on `@types/react` here and I'm not sure what do to here. If it'll work, we'll simply put it in the readme.

**Comment by KeithGillette** [comment]
Thanks, @radekmie —

That works. I actually found two ways to fix this `tsc` error:

1. Your suggestion, which updates `package-lock.json` to `@types/react@17.0.18`, a version which does include `DependencyList`, whereas the previous `16.7.13` did not.

```json
    "@types/meteor": {
      "version": "1.4.76",
      "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.76.tgz",
      "integrity": "sha512-Hnem5BtouhbEP+6zS8wHy5TowL13m72jKVL2dZr/KwbNWpEihTUOsFjhRo88fjRaukhJjxwCB5hEFtAx5edS9g==",
      "dev": true,
      "requires": {
        "@types/connect": "*",
        "@types/jquery": "*",
        "@types/mongodb": "^3.6.20",
        "@types/react": "*",
        "@types/underscore": "*"
      }
    },

…

    "@types/react": {
      "version": "17.0.18",
      "resolved": "https://registry.npmjs.org/@types/react/-/react-17.0.18.tgz",
      "integrity": "sha512-YTLgu7oS5zvSqq49X5Iue5oAbVGhgPc5Au29SJC4VeE17V6gASoOxVkUDy9pXFMRFxCWCD9fLeweNFizo3UzOg==",
      "requires": {
        "@types/prop-types": "*",
        "@types/scheduler": "*",
        "csstype": "^3.0.2"
      }
    },

…

    "angular2-meteor": {
      "version": "0.8.0",
      "resolved": "https://registry.npmjs.org/angular2-meteor/-/angular2-meteor-0.8.0.tgz",
      "integrity": "sha512-fkZt59aIHmglwJ3hEqB9NMqUWly9AGgBCGMRITJfoI4Z58hcm3hp0WLGoJPaU13yr6wEPrZ/Hm9N4judtzjVWg==",
      "requires": {
        "@types/meteor": "^1.3.31",
        "underscore": "^1.8.3"
      },
      "dependencies": {
        "@types/meteor": {
          "version": "1.4.23",
          "resolved": "https://registry.npmjs.org/@types/meteor/-/meteor-1.4.23.tgz",
          "integrity": "sha512-TWhPFOC4b1/ui8FvqH4iIq6LNkY6qQTabmQjwSkrjmNpcF4CjIUSPZ6Rf8OGQ1fSbfLVgDbsK1vMOCS48mj5Qg==",
          "requires": {
            "@types/connect": "*",
            "@types/react": "*",
            "@types/underscore": "*"
          }
        }
      }
    },
```

2. Remove the `/// <reference types="@types/meteor" />` line from the `typings.d.ts` in our shared code project.

This was originally present for ambient Meteor typings used in a shared code project for our Angular front-end. I was able to remove this by adding explicit imports of any previously ambient Meteor type references in the shared source code.

I don't understand why this second method works (why versions of `@types/meteor` after 1.4.72 caused this error in the first place), but it's what I'm going with since we don't use React and we no longer need the ambient Meteor typings.

**Comment by radekmie** [comment]
I'm not sure why the latter works, but I'm glad it does. I'll close this PR and we'll update the readme later. Thank you, @KeithGillette!

**Pull request closed without merging**
