### PR TITLE
[react-widgets] Allow custom props on all widgets

### PR DESCRIPTION
**Pull request by jakeboone02**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
[Source code](https://github.com/jquense/react-widgets/blob/21e3cb1b02e33b2174db3af45811850edd47c841/src/Widget.jsx#L31)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The `Widget` class, which all widgets extend, passes `{...props}` in its `render()` method, therefore TS should allow any custom props of any type.

See [source code](https://github.com/jquense/react-widgets/blob/21e3cb1b02e33b2174db3af45811850edd47c841/src/Widget.jsx#L31)

### CODE REVIEW

**Comment by minestarks** [comment]
Authors @rogierschouten @sanyatuning @frodehansen2 would you like to review?

**Comment by rogierschouten** [comment]
@jakeboone02 I see what you mean, but isn't that an implementation detail? Do you have a use case for passing more properties than the API defines yourself?  

I haven't been using this package for a long time, so please help me see if I'm wrong.

The fact that more than the base props are passed in internal code doesn't mean that the external typings have to reflect that (preferably not, keep them as strict as possible to help users avoid doing stupid stuff). You basically propose to allow all properties to be passed to e.g. a NumberInput without a compiler error, causing typo's to go unnoticed. Also, the implementation may change.  

What are your thoughts?

**Comment by jakeboone02** [comment]
@rogierschouten You're right, it is an internal implementation detail.  I agree the external typings should be stricter than I've allowed here.  I'm new to TypeScript so I'll gladly take any suggestions/corrections.

My use case was passing a `style` parameter to a `<DateTimePicker/>`.  I could wrap it in a `<div/>` with the desired style but I wanted to avoid that (purely for code simplicity's sake, not technical reasons).  I could also propose a patch to [react-widgets](https://github.com/jquense/react-widgets) to accept some "blessed" custom props, but it seemed like making them open-ended would be better since the library works that way anyway.

**Comment by rogierschouten** [comment]
@jakeboone02 if I were you, I'd just wrap it in a div. Even if you allow blessed props, the implementation could change.  Thank you for making a PR though - the community needs people like you and discussions like this to keep everything going.

**Comment by jakeboone02** [comment]
Thanks!  Glad to contribute.  I'll file an issue on the react-widgets repo and see where it goes from there.  And I'll use a wrapper in the meantime. :)

**Pull request closed without merging**
