### PR TITLE
[react-navigation] Allowing tabBarLabel function to return string

### PR DESCRIPTION
**Pull request by HAMPLENI**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://raw.githubusercontent.com/react-community/react-navigation/master/src/views/TabView/TabView.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by abrahambotros — COMMENTED** [review]
This doesn't seem to be the case in the flow typing for the actual `react-navigation` library (https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L334). Is there a definite reason it should be added here but isn't technically supported according to the flow typings? Maybe it's the case a `string` should also be added in the actual library/flow too?

Also, in general, this seems sensible to me without digging into the source code for `react-navigation`, but it could be the case that they're checking if a function was passed and specifically expecting a `ReactElement` in that case. Can you verify this isn't the case?

**Comment by HAMPLENI** [comment]
@abrahambotros 

Thanks for reviewing this!  :)

> Maybe it's the case a string should also be added in the actual library/flow too?

I think if this change is approved, it should also be added in the actual library/flow too.  I can take care of that.

> Also, in general, this seems sensible to me without digging into the source code for react-navigation, but it could be the case that they're checking if a function was passed and specifically expecting a ReactElement in that case. Can you verify this isn't the case?

Ok so here is the story.  :P  The react-navigation documentation, the flow type, and the TypeScript type all say that if tabBarLabel is set to a function, that function should return a React.Element:

https://reactnavigation.org/docs/navigators/tab

The thing is, if you dig into the source code in the link I provided in my first comment, you will see that the source code can also handle when a string is returned from the function.  It handles it the same way as if tabBarLabel was set to a string:

```
    if (options.tabBarLabel) {
      return typeof options.tabBarLabel === 'function'
        ? options.tabBarLabel({ tintColor, focused })
        : options.tabBarLabel;
    }

    if (typeof options.title === 'string') {
      return options.title;
    }
```

So, as the source code is right now, the function returning a string is perfectly fine.  I am not sure whether they intended that support, though.

My use case for having the function return a string is I want to conditionally show nothing or the label depending on a Redux state prop used to indicate that the screen is loading.  I could have just set tabBarLabel to a container component but then I would lose out on the code react-navigation has for the label component.  I am using the TabBarTop component:

https://raw.githubusercontent.com/react-community/react-navigation/master/src/views/TabView/TabBarTop.js

```
    if (typeof label === 'string') {
      return (
        <Animated.Text style={[styles.label, { color }, labelStyle]}>
          {upperCaseLabel ? label.toUpperCase() : label}
        </Animated.Text>
      );
    }
```

So I think there are arguments for making this change and for not making this change.  I will let the reviewers decide.  :)

**Comment by HAMPLENI** [comment]
I committed 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18193/commits/9621973fc03f1b5115f45e4ec93aa39e8daed912

and

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18193/commits/382db2322c4bb000bc783004cb517d284e56249d

to the wrong branch.

I am now rolling back those commits.

**Comment by iRoachie** [comment]
@HAMPLENI Prefer if you send in a new PR or rebase. You've changed 232 files..

**Review by iRoachie — CHANGES_REQUESTED** [review]
@HAMPLENI Prefer if you send in a new PR or rebase. You've changed 232 files..

**Comment by huhuanming** [comment]
You changed other typings too.

**Comment by HAMPLENI** [comment]
I am going to re-submit this PR.  I apologize for the mistake.

**Pull request closed without merging**
