### PR TITLE
added inversify type definitions

### PR DESCRIPTION
**Pull request by remojansen**
Added [InversifyJS](http://inversify.io/) type definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
*inversify/inversify.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/inversify
  * http://bower.io/search/?q=inversify
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (inversify/inversify-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@remojansen thank you for your contributions.
please rename  inversify/inversify-test.ts to  inversify/inversify-tests.ts

**Comment by remojansen** [comment]
@vvakame I have renamed the file. Thanks for reviewing the changes.

**Comment by vvakame** [comment]
@remojansen thanks mate!

**Pull request merged**
