### PR TITLE
Create type definitions for react-filepond

### PR DESCRIPTION
**Pull request by 0livare**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
  - ❓ I'm not sure what this means exactly
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by zposten** [comment]
While running `npm run lint react-filepond`, I currently get an error that I'm hoping someone might be able to help with:

```
Error: C:/dev/DefinitelyTyped/types/react-filepond/index.d.ts:22:1
ERROR: 22:1   strict-export-declare-modifiers  'declare' keyword is redundant here. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
```
At first glance it seems simple enough to remove the `declare`, however, if I remove it, I get a different error, `A 'declare' modifier is required for a top level declaration in a .d.ts file`.  So I'm not sure how to handle this contradiction.

**Comment by zposten** [comment]
@typescript-bot Please don't close this PR.  I'm looking for assistance to resolve the one error, [as described above][comment].

[comment]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31362#issuecomment-446999305

**Comment by zposten** [comment]
@sandersn Would you be able to help me with the seemingly lose-lose error [described above][comment]?

[comment]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31362#issuecomment-446999305

**Comment by sandersn** [comment]
@zposten I think tslint (or perhaps our custom rules in dtslint) was in a bad state for a day or so. I think that's why the error went away for the recent run of the build.

**Comment by kurtgn** [comment]
@zposten Hey Zach - I'm now trying to convert my Filepond components from JSX to TSX, and running into type errors. Specifically, my `server` parameter consists of callbacks which work with original `React-Filepond` but are not allowed by TS types. Example:

```
            <FilePond
                ref={(instance) => {this.fpInstance = instance}}
                server={{

                    /**
                     * When user hits revert - the parent component should receive its old URL
                     */
                    revert: (uniqueFileId: string, load: () => void) => {

                        this.props.updateUrl(this.state.oldImageUrl);
                        // Should call the load method when done, no parameters required
                        load();
                    },
                }}
            />
```

This fails because `revert` only accepts `string | ServerUrl ` types. Would you mind adding callback types to the `server` parameters as well?

Thanks!

**Comment by zposten** [comment]
@kurtgn I see now why you didn't want to make this change yourself, it was kind of a 🐻 lol.  But it should be done now, check out #35291!

**Pull request merged**
