### PR TITLE
[react-dom] Add isPending to `useFormState` return type

### PR DESCRIPTION
**Pull request by eps1lon**
Types for https://github.com/facebook/react/pull/28514

### CODE REVIEW

**Comment by kiqaps** [comment]
I am using the following packages, and the change from this merge is present in the packages:

- react 18.3.1
- react-dom 18.3.1
- @types/react 18.3.3
- @types/react-dom 18.3.0

Shouldn't this changes be present only in versions higher than 19? Or am I doing something wrong? Even the useActionState hook is present in the typing but not in the lib itself

**Comment by eps1lon** [comment]
It's present in these versions but only if you use the Canary types. You don't automatically get these in `@types/react 18.3.3` unless your framework enables Canary types (e.g. Next.js)

**Comment by kiqaps** [comment]
Hm, got it. In my opinion, this is a problem with Next.js then. It doesn't make sense to use the canary for types and not for the library itself. The types will not represent what is actually implemented. Anyway, thank you.

**Comment by kiqaps** [comment]
In the Canary version of Next.js, it's 'okay' because it uses version 19 of React.

image


But in the published version, there is a problem. Looking at the package.json, I am unsure. Is this really configured to use the canary types?

image

**Pull request merged**
