### PR TITLE
Adding added missing nodeDataChanged

### PR DESCRIPTION
**Pull request by zulander1**
added missing nodeDataChanged

### CODE REVIEW

**Review by BobBDE — APPROVED** [review]

**Comment by viniciusverasdossantos** [comment]
> added missing nodeDataChanged


Hello!
Can you add the output property to the DrawflowConnectionDetail class please?

**Comment by zulander1** [comment]
> > added missing nodeDataChanged
> 
> Hello! Can you add the output property to the DrawflowConnectionDetail class please?

I don't see this event drawflow.

**Comment by viniciusverasdossantos** [comment]
> DrawflowConnectionDetail

It's not an event...
It is a Typescript class that is missing this property.

image

**Comment by zulander1** [comment]
done via https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...zulander1:DefinitelyTyped:patch-1

**Comment by viniciusverasdossantos** [comment]
thankyou.

Can you add the points property to the DrawflowConnectionDetail class please?

**Comment by viniciusverasdossantos** [comment]
help me. i need point property:

Can you add the points property to the DrawflowConnectionDetail class please?

**Comment by zulander1** [comment]
@viniciusverasdossantos DrawflowConnectionDetail does not exist in repository [source](https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.js)

**Pull request merged**
