### PR TITLE
[get-port] Remove the type definition

### PR DESCRIPTION
**Pull request by nwtgck**
Hi, developers!

This PR allows `get-port` users to use **only `import`**, not both `import` and `require`.

```ts
// Before PR
import getPort = require('get-port');
```

```ts
// After PR
import getPort from 'get-port';
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Official README: <https://github.com/sindresorhus/get-port>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by nwtgck** [comment]
## @types/get-port may no longer needed

I just found a type definition of `get-port` has been officially supported.
see: <https://github.com/sindresorhus/get-port/pull/27>


So, this PR may not be also needed.

**Comment by plantain-00** [comment]
Yes, `@types/get-port` should be removed: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Review by BendingBender — CHANGES_REQUESTED** [review]
Yes, please remove this definition.

**Comment by nwtgck** [comment]
@plantain-00 @BendingBender 

Thank you for your reviews!  I removed the definition and **pushed to this PR**. 

* If I should **combine the two commits together**, I'll do this and force push.
* If I should create new PR for the deletion, I'll do this.
* If I shouldn't anything, **I want to change the title of this PR**.

**Comment by BendingBender** [comment]
Yes, please change the title. You can squash the commits together, this is up to you.

**Review by BendingBender — APPROVED** [review]

**Comment by nwtgck** [comment]
@BendingBender

Thank you. As you know, I changed the title and squashed them.

**Comment by BendingBender** [comment]
Thank you!

**Pull request merged**
