### PR TITLE
Suggestion type for suggestion selected event.

### PR DESCRIPTION
**Pull request by jkanczler**
case 2. Improvement to existing type definition.
SuggestionSelectedEventData converted to be a generic interface, so type of the suggestion property can be defined by the consumer.

It's useful because I don't have to cast the suggestion to the appropriate type in the event handler:

```
    protected onSuggestionsSelected(event: React.FormEvent, data: ReactAutosuggest.SuggestionSelectedEventData<Language>) {
        alert(`Selected language is ${data.suggestion.name} (${data.suggestion.year}).`);
    }
```

### CODE REVIEW

**Comment by nicolas-schmitt** [comment]
Good point. However i'ld like to keep the current type as well, so that your update comes as help not a requirement.

Would you mind creating a second interface inheriting from yours ? It would look like this (better naming ideas are more than welcome)
```typescript
interface ImplicitSuggestionSelectedEventData extends SuggestionSelectedEventData<any> { }

interface AutosuggestProps extends React.Props<Autosuggest> {
...
onSuggestionSelected?: (event: React.FormEvent, data: ImplicitSuggestionSelectedEventData|SuggestionSelectedEventData<any>) => void;
...
}
```

**Comment by jkanczler** [comment]
Good idea, but then I'm thinking on the following because of backward compatibility reasons:

```
  interface ExplicitSuggestionSelectedEventData<TSuggestion> {
    method: string;
    sectionIndex: number;
    suggestion: TSuggestion;
    suggestionValue: string;
  }

  interface SuggestionSelectedEventData extends ExplicitSuggestionSelectedEventData<any> {
  }
```

Though I don't like the naming.

**Comment by nicolas-schmitt** [comment]
Well i don't have any better idea :cry: 
Plus, that's more or less the naming convention used in lodash's d.ts.
Is it ok with you if i merge your PR as is ?

**Comment by jkanczler** [comment]
Yes, it is, as I don't have better naming idea either.

**Pull request merged**
