### PR TITLE
Update antd.d.ts

### PR DESCRIPTION
**Pull request by jxwang2010**
add "icon" member for interface ButtonProps

### CODE REVIEW

**Comment by bang88** [comment]
@jxwang2010 This version is not maintenance,use the latest version of `antd` is recommended.

**Comment by minestarks** [comment]
@bang88 @jxwang2010 Should this PR be merged? I'm not familiar with this library so I'm not sure what you meant by the comment. Is the change not needed? Thank you.

**Comment by bang88** [comment]
@minestarks No.

**Comment by afc163** [comment]
@bang88 Should we just remove antd.d.ts from DefinitelyTyped?

**Comment by bang88** [comment]
@afc163 Maybe someone use the old version of `antd`?

**Comment by paulvanbrenk** [comment]
Thanks for the contribution @jxwang2010 but as @bang88 indicated this is a no longer maintained version. Closing as such

**Pull request closed without merging**
