### PR TITLE
[prop-types] add elementType and resetWarningCache

### PR DESCRIPTION
**Pull request by eps1lon**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - [15.7 changelog](https://github.com/facebook/prop-types/blob/master/CHANGELOG.md#1570)
  - [PropTypes.resetWarningCache()](https://github.com/facebook/prop-types#proptypesresetwarningcache) added with facebook/prop-types#178
  - [PropTypes.elementType (right under `optionalElement`)](https://github.com/facebook/prop-types#usage) added with facebook/prop-types#211
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by eps1lon** [comment]
I did look into the `react-jss` since I'm familiar with the package and the fail looked like it was related: Don't think it actually is. Error occurred on master to and was fixable with 
```patch
diff --git a/types/react-jss/react-jss-tests.tsx b/types/react-jss/react-jss-tests.tsx
index 5fe76ae1..cfcad4cd 100644
--- a/types/react-jss/react-jss-tests.tsx
+++ b/types/react-jss/react-jss-tests.tsx
@@ -27,9 +27,9 @@ interface ButtonProps {
   active?: boolean;
 }
 
-const styles = (theme: MyTheme) => createStyles({
+const styles = (theme: MyTheme) => createStyles<ButtonProps>({
   myButton: {
-    color: (props: ButtonProps) => props.active ? 'red' : theme.color.primary,
+    color: props => props.active ? 'red' : theme.color.primary,
     margin: 1,
     "& span": {
       fontWeight: "revert"
```

**Comment by ferdaber** [comment]
Can you add a test for the exotic components like `React.Fragment` and `React.lazy()`?

**Comment by eps1lon** [comment]
> Can you add a test for the exotic components like `React.Fragment` and `React.lazy()`?

@ferdaber How would this look like? As far as I know I can't expect a fragment type in the typescript interface and then validate a less specific type in `propTypes`.

**Comment by ferdaber** [comment]
I meant a test that those components, when passed in as props, passes the `JSX.LibraryManagedAttributes` check. I should clarify: I was talking about React types tests not PropTypes types tests 😅

They're tightly coupled so changes to this package almost necessarily needs a retest of the `library-managed-attributes.ts` test file in `@types/react`.

**Comment by eps1lon** [comment]
@ferdaber the `managedAttributes.tsx` tests are completely commented out though. I really have no idea what tests I should add.

**Review by ferdaber — APPROVED** [review]
I don't want this change to be blocked because of tests so I'll go ahead and approve.

**Pull request merged**
