### PR TITLE
Multer: added typing for file in callbacks

### PR DESCRIPTION
**Pull request by wldevries**
The file argument in the arguments is the same type as the files on req.

Unfortunately my Typescript is very limited, I have no idea how to reuse the MulterFile type declaration in the Express module above so I just copied it ...

### CODE REVIEW

**Comment by vvakame** [comment]
@jt000 @vilic could you review this PR?

**Comment by vilic** [comment]
You may write something like this:

```ts
declare module Express {
    module Multer {
        interface File {
            /** Field name specified in the form */
            fieldname: string;
            /** Name of the file on the user's computer */
            originalname: string;
            /** Renamed file name */
            name: string;
            /** Encoding type of the file */
            encoding: string;
            /** Mime type of the file */
            mimetype: string;
            /** Location of the uploaded file */
            path: string;
            /** Extension of the file */
            extension: string;
            /** Size of the file in bytes */
            size: number;
            /** If the file was truncated due to size limitation */
            truncated: boolean;
            /** Raw data (is null unless the inMemory option is true) */
            buffer: Buffer;
        }
    }
    
    interface Request {
        files: {
            [fieldname: string]: Multer.File;
        }
    }
}
```

And use `Express.Multer.File` below.

Thanks for correcting the mistake BTW.

(Also I noticed there's some updates of its API, you may check them out if you are interested.)

**Comment by frogger3d** [comment]
Thanks for the help, I updated the PR. I've not really used multer yet, so I might update the definition if or once I get around to using the various storage options.

**Comment by vvakame** [comment]
@vilic :smiley_cat:

**Comment by vilic** [comment]
:+1:

**Comment by vvakame** [comment]
@vilic thanks!
@frogger3d thanks mate!

**Pull request merged**
