### PR TITLE
fix: luxon toISODate, toISO and toSQLDate method could return null when an InvalidDate is provided

### PR DESCRIPTION
**Pull request by edoeel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test luxon`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/moment/luxon/pull/1406
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by CarsonF** [comment]
#58147

**Comment by edoardomistretta** [comment]
Hi @CarsonF, this a breaking change but IMHO this is necessary.

At the moment developers are forced to know the internals of the method `toX` because the method could return a value that is not specified. It's like the method throws an error to catch but the developer doesn't know that the method could throw an error.

Developers are guided by types and interfaces instead of actual implementation so please consider this PR

**Comment by CarsonF** [comment]
I hear you that there's a mismatch here. Let me see if I can address this in an elegant way.

I can tell you though that this PR and your PR are not going to be merged.
There's are multiple dozens of methods/getters who deal with invalid input/output, not just this one.
Also the luxon jsdocs don't type any of the invalid output types, so I doubt they'll deviate with those 3 methods

**Review by CarsonF — CHANGES_REQUESTED** [review]
Superceded by #64995

**Pull request closed without merging**
