### PR TITLE
[@types/node] Update `node:stream/web` types for `TextDecoderStream`

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/webstreams.html#new-textdecoderstreamencoding-options
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by Semigradsky** [comment]
As I see it is already accepts web streams because web stream is `AsyncIterable`.

For example:
```ts
import { buffer } from "node:stream/consumers";
import { ReadableStream } from "node:stream/web";

const web = new ReadableStream();
await buffer(web); // works
```

Please provide more info and add tests.

**Comment by codershiba** [comment]
Created this PR in response to #65755 but seems like it was a mistake

**Comment by Semigradsky** [comment]
Oh, it was my suggestion 😄  I really don't remember what was wrong in current code.
@pimterry maybe you can provide some examples?

**Comment by pimterry** [comment]
Ah, looks like this issue was correct at the time, but has since been fixed independently.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66843 resolved a mistake (using AsyncIterator instead of AsyncIterable) which also fixes this issue (since a web stream is indeed an async iterable, as mentioned above) and so this does indeed now work correctly.

**Review by Semigradsky — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@codershiba thanks!

**Comment by codershiba** [comment]
Ready to merge

**Pull request merged**
