### PR TITLE
Bluebird 3.0.0

### PR DESCRIPTION
**Pull request by CodeAnimal**
Implemented changes documented here:
http://bluebirdjs.com/docs/new-in-bluebird-3.html

Added tests for changes made and removed tests for deprecated symbols.

### CODE REVIEW

**Comment by CodeAnimal** [comment]
It seems to be a bad test in definitions for sequelize that's causing the build to fail (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sequelize/sequelize-tests.ts#L1125). Looking at it, it seems to me that the sequelize definition tests need correcting (rather than the bluebird definitions).

**Comment by vvakame** [comment]
@CodeAnimal could you fix it?

**Comment by CodeAnimal** [comment]
I'll try and take a look at it soon, but may not get chance until the weekend.

**Comment by mhegazy** [comment]
@CodeAnimal  🔔

**Comment by CodeAnimal** [comment]
Sorry, I've not had any spare time recently to fix this. I will hopefully get around to it as soon as possible, but I'm busier than ever at the minute.

**Comment by anubmat** [comment]
Thanks for your contribution. This PR has failing CI tests, merge conflicts and unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
