### PR TITLE
[is-negative-zero] add types

### PR DESCRIPTION
**Pull request by tristan-f-r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Usually, I would make this a type guard. However, [since TypeScript does not see the difference between `-0` and `0`](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UC0AGKEAewIDsAmAzlGgPxTABOArtAFxQBmAhgDYEQDcAUKJFAJoJi6LLkLJS5anUat23LgGMA9jgLAoGenESUa3FWo0h6g3dO5A), I instead opt to give a _slight_ hint if they pass a non-numeric value (allowing their IDE to notice the error).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/is-negative-zero/is-negative-zero-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c21581bda112450e687fb1792438292c23af06b1
</p>

**Review by navya9singh — APPROVED** [review]

**Comment by LeoDog896** [comment]
Ready to merge

**Comment by LeoDog896** [comment]
Ready to merge

**Comment by LeoDog896** [comment]
Ready to merge

**Pull request merged**
