### PR TITLE
[next] Update SingletonRouter interface with RouterProps for next@5

### PR DESCRIPTION
**Pull request by scottdj92**
* add name to index.ts
* update tests

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/zeit/next.js/blob/canary/lib/router/index.js>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Updating because Nextjs's router doesn't directly own it's own props, but has its own instance of Router. Importing this package would mean that an interface would need to be created to type `router: SingletonRouter` rather than have SingletonRouter contain an instance of `router`.

### CODE REVIEW

**Review by dru89 — CHANGES_REQUESTED** [review]
This looks like it might have some issues to me.  See here: https://github.com/zeit/next.js/blob/a691dd06cfba0a847b946158adf471e41ce56b59/lib/router/index.js#L16-L32

The exported `SingletonRouter` actually exposes these methods from `Router`, by iterating over them and delegating to `SingletonRouter.router`.  It's true that the original typings didn't take calling `SingletonRouter.router.<method>` into account (over `SingletonRouter.<method>`), so we may want to extend the types to handle that case.  But this change removes using `SingletonRouter.<method>` which, I believe, is the intended way to use the object given the linked code above.

Also, some of the properties that you've moved down to `SingletonRouter.router` don't actually exist, like `ready` and `readyCallbacks`.

**Comment by scottdj92** [comment]
Apologies for not getting back to this, but would it make sense to have two interfaces: `ImperativeRouter`, and `SingletonRouter`? considering the SingletonRouter is a delegate of ImperativeRouter. Then we could export both and have the end user decide on which type to use?

**Comment by Dru89** [comment]
That plan seems fine to me.

**Comment by scottdj92** [comment]
Cool, pushed up my changes. Let me know if anything can be improved.

**Comment by scottdj92** [comment]
Hey man, yeah as far as I can see if you are importing `next/router` the router itself actually delegates all the methods to the singleton type. I tested this type in my own next.js apps without any issues, even with `Router.replace` and `Router.push`. Can you give me an example of how it would break the types?

**Comment by bensaufley** [comment]
@scottdj92, here's what I've got:

```ts
import { default as Router } from 'next/router'; // default as… pattern to get around a tslint about capitalization. Error persists with "import Router from…"

// …
Router.replace(route.pagePath, route.redirectUrl);
```

And you can see:
image

The only way I can make this work with the new types is actually to do:

```ts
((Router as any) as ImperativeRouter).replace(route.pagePath, route.redirectUrl);
```

Which is of course horrifying. It happens because `Router` (`SingletonRouter`) can't be directly coerced to `ImperativeRouter` because they don't conform. Obviously in practice I'd use `Router.router` first, but I don't think that's a reasonable change when `Router` itself should work.

**Comment by fengcen** [comment]
This changes breaks my code too.

**Comment by bensaufley** [comment]
@scottdj92 I'm trying to work through this but it turns out I'm not clear on exactly what problem this PR was solving. I've read your description above but I think I'm missing something. Can you show me an example of what you were running into?

I'm having trouble understanding specifically why `SingletonRouter` shouldn't just `extend RouterProps`—it _should_ have all of those props on it, because of the logic I linked to above. There's no scenario where it doesn't have those props—only scenarios where calling those props will execute a function that may or may not `throw`—not because the props are invalid but because the function as called detects that no `router` is present. I'm not sure how to represent that in TypeScript, but I don't think removing them entirely is the right solution.

**Comment by bensaufley** [comment]
More follow-up: I don't think changing `React.ComponentType<T & { router: SingletonRouter }>` is correct. `T` is the other props, some kind of object (default `{}`) and `withRouter` adds an extra prop, `router` [here](https://github.com/zeit/next.js/blob/491d2ec0dd9a13deda51b0abe3ab46edc7312768/lib/router/with-router.js#L18). It doesn't spread the `router` object into Props (which would be what `T & SingletonRouter` did). I think that `props.router` is an instance of `SingletonRouter` and _not_ of `RouterProps` (as is implied by `T & SingletonRouter` which means `router` references `SingletonRouter.router`).

In addition I'm still not sure why that instance of `SingletonRouter` wouldn't have those delegated properties. Tracing the references around, the default export, `SingletonRouter`, is what's getting used on initialization and `SingletonRouter` always has those attributes delegated to it.

**Comment by bensaufley** [comment]
@fengcen, @scottdj92 I've got a PR in to address this. @fengcen, do you want to see if those changes work for you? @scottdj92, can you see if my changes also address or at least do not undo what you were trying to fix? I'm still not 100% sure I have an understanding of the original problem, and if I've missed it I apologize.

**Pull request merged**
