### PR TITLE
Adding the gl-matrix type definitions

### PR DESCRIPTION
**Pull request by ghost**
Adding the gl-matrix library type definitions.

### CODE REVIEW

**Comment by vvakame** [comment]
*gl-matrix/gl-matrix.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/gl-matrix
  * http://bower.io/search/?q=gl-matrix
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (gl-matrix/gl-matrix-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@tatchx thanks mate!

**Comment by tatchx** [comment]
@vvakame welcome!

**Comment by endel** [comment]
Hey guys, I'm not being able to use gl-matrix definitions. I can compile my code with the globals recognised, but they don't get included into the final compiled file.

If I require the dependency I want to use manually (e.g. `import { vec2 } from "gl-matrix"`) it works, but the compiler outputs an error:

```
ERROR in [default] src/math/Vector2.ts:1:21
Cannot find module 'gl-matrix'.
```

Am I missing something?

**Comment by endel** [comment]
If I just include the reference (`///<reference path="...">`), the error that I get is that the global instance is not defined:

```
Vector2.ts:10Uncaught ReferenceError: vec2 is not defined
```

Any thoughts? Is it working for you guys? @tatx @vvakame

**Pull request merged**
