### PR TITLE
Update Restify to v5

### PR DESCRIPTION
**Pull request by stevehipwell**
I've updated the Restify definitions to v5 including general improvements.

### CODE REVIEW

**Review by rbuckton — CHANGES_REQUESTED** [review]
This is a fairly substantial change. Please add a _v4_ folder for the existing version as well, per [the readme](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version).

**Comment by stevehipwell** [comment]
@rbuckton - I've added a folder for v4 typings.

**Comment by stevehipwell** [comment]
@rbuckton - Can you look at the changes and update your review? I'd really like to get this merged ASAP.

**Review by rbuckton — APPROVED** [review]

**Comment by stevehipwell** [comment]
@rbuckton - Any idea why v5 hasn't been published to npm yet?

**Comment by dthunell** [comment]
Seems to be out now

> Files were exported from 
> https://www.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/restify
>
> Additional Details
> Last updated: Tue, 11 Jul 2017 14:04:07 GMT

**Pull request merged**
