### PR TITLE
feat(angular): update to version 1.7

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This updates covers API removal as part of the migration from 1.6. to
1.7 and adding couple of new features:
- remove api update
- `errorHandlingConfig` added
- `timeSecondsFormat` and `timeStripZeroSeconds` for NgModel
- tests update

https://docs.angularjs.org/guide/migration#-form-
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#179-pollution-eradication-2019-11-19

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
So the CI fails due to this change:
https://github.com/peterblazejewicz/DefinitelyTyped/commit/2f995d071e2d5073773143bc0be628e0e09e4d41#diff-d95715a34836b1adc8a6cd562eccf87e
in the 3rd library which uses this package imports. The 3rd party bumbed min TS version to 3.7

**Comment by owlcode** [comment]
I believe this change has triggered some consequences on older environments, which now need to struggle with `gettext/node_modules/@types/angular/jqlite.d.ts(29,5): TS2375: Duplicate number index signature.`

**Comment by peterblazejewicz** [comment]
@owlcode 
Can you provide some more detail, pls? It doesn't look like related to changes I've done at the first look. I haven't changed how the definition is beign exported as global module here, which could potentially change existing code to have conflicts: https://github.com/Microsoft/TypeScript/issues/12286#issuecomment-261024089
https://github.com/ui-router/angular-hybrid/issues/70

**Comment by owlcode** [comment]
I'm almost certain that publishing `1.7` has affected only those who had `~1.6` somewhere in their dependency tree. Resolved by package manager to install both versions, causing conflicts. Fix would be to either `skipLibCheck` as you said, or manually deal with installed version (by bumping or downgrading so that it gets resolved to single version), or... ?

**Pull request merged**
