### PR TITLE
Added support for different font families styling

### PR DESCRIPTION
**Pull request by lpotapczuk**
Created a support for styling method of a chart.

### CODE REVIEW

**Comment by vvakame** [comment]
*highcharts/highcharts.d.ts*

to authors(@damianog @baltie). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by baltie** [comment]
Looks good to me. :+1: Thanks @lpotapczuk!

**Comment by vvakame** [comment]
thanks mate!

**Comment by lpotapczuk** [comment]
@vvakame thanks! I will try to find some more

**Pull request merged**
