### PR TITLE
lunr: Remove redundant jsdoc

### PR DESCRIPTION
**Pull request by ghost**
Fixes the lint.

### CODE REVIEW

**Review by seantanly — APPROVED** [review]
👍  Thanks for the lint fixes and bugfix for `Token.clone()`!

I wonder whether it is possible to capture implementation of interface`@implements {lunr.PipelineFunction}` in typescript definition.

**Comment by andy-ms** [comment]
@seantaly You could add a test in `lunr-tests.ts` that they are assignable to a variable of type `lunr.PipelineFunction`.

**Comment by seantanly** [comment]
@andy-ms Other than the tests, I'm hoping the user will be able to deduce within the editor that the functions are of type `lunr.PipelineFunction`, e.g. from IntelliSense.

**Comment by andy-ms** [comment]
You could also declare it as e.g. `const stemmer: lunr.PipelineFunction;`

**Comment by seantanly** [comment]
Some information is lost there though, given `lunr.PipelineFunction` is defined as
```typescript
type PipelineFunction = (
    token: Token,
    i: number,
    tokens: Token[]
) => null | Token | Token[];
```
and functions like `stemmer` is defined as
```typescript
function stemmer(token: Token): Token;
```
Purely define `stemmer` as 
```typescript
const stemmer: PipelineFunction;
```
means the function arguments is not just `(token: Token)`, and the return type is not just `Token`.

**Comment by andy-ms** [comment]
Oh, you're right. Unfortunately TypeScript doesn't let you define a function and also a type for that function to implement -- you could just add a comment back.

**Comment by seantanly** [comment]
What would be a good comment that passes the lint? Is the following (2nd line) good for adding?
```typescript
/**
 * @implements lunr.PipelineFunction
 */
```

**Comment by andy-ms** [comment]
That might give you line failures -- I suppose we could add an exception for the case of a function but it still seems like an `@implements` tag will usually be redundant. Could you just use `Implements lunr.PipelineFunction`?

**Comment by andy-ms** [comment]
:+1:

**Pull request merged**
