### PR TITLE
add PromptIOSButton interface in prompt method of AlertIOSStatic in type/react-native/index.d.ts

### PR DESCRIPTION
**Pull request by benben198805**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<type/react-native/index.d.ts>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by alloy** [comment]
I’m unsure why you’re adding a new interface over using the existing `AlertIOSButton` interface. Can you please include a link to the code/documentation you got this from?

**Comment by benben198805** [comment]
@alloy 
sometimes, we need  prompt dialog to return message, but `AlertIOSButton ` did not have thoses args for it.

**Comment by alloy** [comment]
Ok, but I think you should just update `AlertIOSButton` to have that optional parameter I stead.

**Comment by benben198805** [comment]
good idea. I have changed the commit and added an optional arg in `AlertIOSButton`.

**Comment by alloy** [comment]
Perfect, thanks 👍

**Pull request merged**
