### PR TITLE
Adds multiple method to confirm dialog typing.

### PR DESCRIPTION
**Pull request by plindley86**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://material.angularjs.org/latest/api/service/$mdDialog
https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L553

### CODE REVIEW

**Comment by geertjansen** [comment]
Approve

**Comment by plindley86** [comment]
Agreed. Made another commit. Let me know if you need anything else.

**Comment by geertjansen** [comment]
Agreed, LGTM

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
