### PR TITLE
[lodash] fixed erroneous types for `sumBy` and `compact`

### PR DESCRIPTION
**Pull request by panda2134**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test lodash`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
 - Some test errors still exist, but they're not related to this PR. I'll fix them with another PR when possible.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - `compact`: refer to the [source code](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/compact.js). All falsey values are removed, and we need to use `Truthy<T>` to ensure this. The related failing tests are fixed by this PR.
  - `sumBy`: the `iteratee` argument should accept shorthand forms other than `string`'s, e.g. `1` or Symbols. Types are modified, and I added tests covering the usage of `number`'s as the shorthand.

### CODE REVIEW

**Comment by panda2134** [comment]
@bczengel I feel sorry to disturb you, but the original version of code (which my commits are based upon) contains errors, which I don't know how to fix. Because of the failing `npm run lint lodash`, this PR cannot be merged. Maybe you could offer some help. Thanks in advance.

**Comment by bczengel** [comment]
> @bczengel I feel sorry to disturb you, but the original version of code (which my commits are based upon) contained errors, which I don't know how to fix. Because of the failing `npm run lint lodash`, this PR cannot be merged. Maybe you could offer some help. Thanks in advance.

I'm sorry @panda2134. Unfortunately, I haven't worked on the lodash typings in a long time. Since then, they've gone through quite a bit of changes. Back when I originally wrote them, they were one file. They weren't even in an @types library yet. It would take me a while to spin up my dev env to help you out and I don't have the time at the moment. The devs that have taken over since would be a better bet to reach out to. I hope you get it figured out and get your changes pulled.

**Comment by panda2134** [comment]
@aj-r Hi aj-r, I need some help here with the tests. #50651 attempted to fix `compact`, but as the `fp.d.ts` is now autogenerated, we have to work on the original version in `common` like in this PR. However, due to errors already existing in the tests before my commits, the bot refused to merge my changes, which do not introduce new failing tests. It can't be better if you can lend a hand here. Thanks!

**Comment by panda2134** [comment]
Maybe some help is needed... I'll open another PR when it gets fixed

**Comment by aj-r** [comment]
Hi sorry for the late response. There are issues with the fp generator right now - feel free to manually undo the changes that are not related to compact/sumBy.

**Pull request closed without merging**
