### PR TITLE
[react] fix useMemo break when return undefined

### PR DESCRIPTION
**Pull request by dreamfliper**
This PR means to be to fix #67076. Sorry about the mess.

Thanks to @meyfa 's [solution](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67076#issuecomment-1771635702), this should fix **explicit return undefined** would brake.

And Thanks to @Hypnosphi @meyfa @kevinbailey25 @stephenzsy @miguelski @codeaid @jessemyers-lettuce to point out my mistake.
Special thanks to @meyfa for providing the solution, and @miguelski for explaining the reason why `Exclude<T, void>` won't work after typescript 5.1+.

Thanks to all future participants. You all make this library more robust and more comprehensive.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by dancerphil** [comment]
Better just revert things and discuss how to implement this later.

**Comment by dreamfliper** [comment]
I agree

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act

## Formatting

The following files are not formatted:
1. types/react/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against aad6126eaf30e35c9b005bace780889c0e5a2c47
</p>

**Comment by dancerphil** [comment]
@dreamfliper Seems like this PR is ready? Since test cases are passed.

**Review by dancerphil — APPROVED** [review]

**Comment by dreamfliper** [comment]
@dancerphil Yes it's ready, but we still can revert previous and then triple check how we should implement.

**Comment by dancerphil** [comment]
According to the discussion, I started a revert progress [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67135).

(Not frequently handle such things but seems other owners not handling this)

**Comment by sandersn** [comment]
Do the new test cases include the failures people were bringing up on #67076 ?
(I looked at the PR but I don't really know the react types, just asking a background question.)

**Comment by Hypnosphi** [comment]
@sandersn yes, this line covers them: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67132/files#diff-8036c55d34934cdbf8a09e220f6595f5d994213f44699b0c012f6da99d193a33R243

**Comment by dreamfliper** [comment]
Thanks to @Hypnosphi for your support.
@sandersn Yes, and I think the more important in the new test is [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67132/files#diff-8036c55d34934cdbf8a09e220f6595f5d994213f44699b0c012f6da99d193a33R245)，user do cache value that could potentially be undefined.

**Review by dancerphil — APPROVED** [review]
Look good to me

**Review by sandersn — APPROVED** [review]

**Comment by rezio-gary** [comment]
Ready to merge

**Comment by td-tomasz-joniec** [comment]
I think this commit is a mistake, because React's useMemo actually allows type that was previously there. That is something that should be definitely looked at.

**Comment by fubhy** [comment]
> This change introduces unexpected type errors when the factory function uses inferred generics as part of the return type:
> 
> ```ts
> import { useMemo } from 'react';
> 
> type Wrapped<T> = { inner: T };
> 
> type Augmented<T> = T & { augmented: true };
> 
> const augment = <T extends {}>(wrapped: Wrapped<T>): Augmented<T> => ({
>   ...wrapped.inner,
>   augmented: true,
> });
> 
> export const useAugmentThing = <T extends {}>(foo: T) => {
>   return useMemo(() => augment({ inner: foo }), []);
> };
> ```
> 
> > Argument of type `() => Augmented<T>` is not assignable to parameter of type `ExcludeVoidFn<() => Augmented<T>>`. `ts(2345)`
> 
> image

Beat me to it by mere seconds ... Came here to report the same. Just ran into this too. ;-)

**Comment by biggyspender** [comment]
> This change introduces unexpected type errors when the factory function uses inferred generics as part of the return type:
> 
> ```ts
> import { useMemo } from 'react';
> 
> type Wrapped<T> = { inner: T };
> 
> type Augmented<T> = T & { augmented: true };
> 
> const augment = <T extends {}>(wrapped: Wrapped<T>): Augmented<T> => ({
>   ...wrapped.inner,
>   augmented: true,
> });
> 
> export const useAugmentThing = <T extends {}>(foo: T) => {
>   return useMemo(() => augment({ inner: foo }), []);
> };
> ```
> 
> > Argument of type `() => Augmented<T>` is not assignable to parameter of type `ExcludeVoidFn<() => Augmented<T>>`. `ts(2345)`
> 
> image

Yes. Spent the last half hour or so trying to figure out how to constrain `T` to make it work.

The following nastiness helps, but it shouldn't be this hard.

```typescript
type ExcludeVoidFn<T extends () => unknown> = (() => void) extends T ? never : T;
type ExcludeVoid<T> = ReturnType<ExcludeVoidFn<() => T>>;
```

**Comment by nstepien** [comment]
We use the following pattern a lot and this PR breaks previously valid types:
```ts
useMemo((): T => {
  return ...;
}, [...]);
```

**Comment by paztis** [comment]
Hey this PR break all the useMemo that returns any
Because () => void is extending () => any
```

type ExcludeVoidFn<T extends () => unknown> = (() => void) extends T ? never : T;
const testFn = (): any => {

};

type TResultingType = ExcludeVoidFn<typeof testFn>; // TResultingType is never
```

This test can be added in unit tests

**Comment by miguelski** [comment]
it is definitely not working as expected it broke another of my projects
i think it shouldn't be part of the @react/types it should be in the eslint react-hooks/rules-of-hooks in any case

**Comment by dancerphil** [comment]
@dreamfliper This PR couldn’t be reverted automatically. Would you please handle it manually?

**Comment by roderickhsiao** [comment]
yeah we are getting lots of error `Argument of type '() => any' is not assignable to parameter of type 'never'.ts(2345)` 

when useMemo is returning a constant value for instance

```
  const parsedValue = useMemo(
    () => (a ? JSON.parse(a) : {}),
    [a]
  );
```

**Comment by jessemyers-lettuce** [comment]
I suggest that it's time to roll back to before the current round of changes and find a better way to validate these changes than guess-and-test.

**Comment by dreamfliper** [comment]
@dancerphil Sure

**Comment by paztis** [comment]
Ça you publish the module on npm also ?

**Pull request merged**
