### PR TITLE
Simplified input parameter types for `append()` like methods

### PR DESCRIPTION
**Pull request by ghost**
I was not able to pass `DocumentFragment` in `appendTo()` method, so I changed input parameter type from `Element` to `Node` and I did so for other appending methods.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I don't think we can take this I'm afraid; `DocumentFragment` doesn't appear to be part of the API: http://api.jquery.com/appendto/

**Comment by Diullei** [comment]
I agree with @johnnyreilly

**Comment by Steve-Fenton** [comment]
Just to add to this, both `Element` and `DocumentFragment ` are specializations of the `Node` interface. This means it isn't technically safe to assume a `DocumentFragment` can be passed where an `Element` is acceptable - as members of `Element` that don't exist on `DocumentFragment` might be required.

If jQuery was updated to accept the more general `Node` type, it would then be acceptable to pass `Node`, `Element`, or `DocumentFragment` - but this is not something we ought to do in the type definition unless the actual jQuery library is changed. Otherwise the type definition will make promises that the library hasn't made.

**Comment by johnnyreilly** [comment]
Thanks for that Steve.

**Comment by benjaminjackman** [comment]
Unsubscribe

**Comment by vclav** [comment]
I do not know all the specializations of `Node` interface, so maybe It's to wide for this case, but jQuery supports use of `appendTo(#document-fragment)`, so this type shall be added to allowed types of `appendTo()` method.

**Comment by johnnyreilly** [comment]
Hi @vclav,

I'm afraid we only look to provide definitions for the official API. You could raise a docs PR and see if they're willing to include document fragment (ie officially support it). If they do we'd be happy to add support to the type definition. We've had success with this in the past (I've done it as have others)

Best of luck!

**Pull request closed without merging**
