### PR TITLE
Bugfix: Permit parse-unit to be passed nothing as per the tests

### PR DESCRIPTION
**Pull request by joshuaharry**
Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mattdesl/parse-unit/blob/d6e30cd1e8d6c01c6fce70a924789398aa277bfc/test.js#L11

### CODE REVIEW

**Comment by Jack-Works** [comment]
Is this API change documented in the library? It doesn't seems like a meaningful change since it's like the test case to the wrong input

**Comment by joshuaharry** [comment]
> Is this API change documented in the library? It doesn't seems like a meaningful change since it's like the test case to the wrong input

Thank you for your comment. My pull request exists because this [JavaScript test case](https://github.com/mattdesl/parse-unit/blob/d6e30cd1e8d6c01c6fce70a924789398aa277bfc/test.js#L11) is out of sync with the TypeScript types. Are you suggesting that the TypeScript uses of the function `unit` and the JavaScript uses of the function `unit` should behave differently in this particular case? Or should the test case of the JavaScript specifically check for an exception? I'd be happy to open a pull request on the JavaScript code as well.

**Comment by Jack-Works** [comment]
This test case is apparent to test an invalid input. The nature idea is it will be rejected by the type system therefore I don't think the invalid input should be typed.

**Comment by Jack-Works** [comment]
@typescript-bot I think we should not merge this

**Pull request closed without merging**
