### PR TITLE
Seems like the error callback is malformatted

### PR DESCRIPTION
**Pull request by marcusradell**
New to typescript, but it complains on my cb function since it expects an error argument and doesn't return an object.

I proposed these changes, but haven't done any typescripting really (trying to migrate to TS), so feel free to deny this PR if it's wrong.
I did check with the source code in ws before suggesting this though.

PS: I'm so sorry that I didn't follow the contribution guideline, but I'm doing this from github and have no setup right now that enables me to follow them :-(

### CODE REVIEW

**Comment by vvakame** [comment]
try with `--noImplicitAny` option.

**Comment by marcusnielsen** [comment]
@vvakame if that's directed to me, I need more directions.

Our code base is not runnable with that flag. We have lots of hard errors to go through still. That's why I made a PR via github web UI and not a proper one. I discovered this as a part of fixing all errors. It really doesn't llok like it matches the source code signature.

**Comment by yuit** [comment]
@marcusnielsen Thanks for the PR! could you fix the CI build failure? also if you could provide reference here that will be great

> ---------------- For file:/home/travis/build/DefinitelyTyped/DefinitelyTyped/ws/tsconfig.json
> \home\travis\build\DefinitelyTyped\DefinitelyTyped\ws\index.d.ts
> 	 Line 138: Parameter 'err' implicitly has an 'any' type.

**Comment by marcusnielsen** [comment]
@yuit here's the reference code: https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L152

I don't know if It's correct with `error?: any` or `error?: Error` for the callback `error` argument. I'm humbly suggesting `error?: any` unless we can know that something more specific won't break the API.

**Pull request merged**
