### PR TITLE
flashpoint-launcher: 9.1 typings

### PR DESCRIPTION
**Pull request by colin969**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

flashpoint-launcher consists of typings for extensions written for the Flashpoint Launcher
https://github.com/FlashpointProject/launcher

Extension Docs:
https://github.com/FlashpointProject/launcher/blob/develop/docs/extensions.md

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@colin969 why people need this duplication or manually copy `.d.ts`? They are already using this package when writing a plugin (as a dependency, not as a type dependency), I could misread though:
https://github.com/FlashpointProject/launcher/blob/develop/docs/extensions.md

**Comment by colin969** [comment]
The definitions have to be copied out of the Launcher repo because the typings don't have their own package yet, hence this PR.

You only need the .d.ts file.

**Comment by peterblazejewicz** [comment]
I meant: your package generates typings already. If published to NPM, why not publish the types with package itself?
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
My intent here is only to prevent duplication (DRY)

**Comment by colin969** [comment]
Those typings are manual, not generated - The type definitions are for the Extensions API, and the Launcher software itself imports those definitions to create its implementation of them.

https://github.com/FlashpointProject/launcher/blob/master/src/back/extensions/ApiImplementation.ts#L267

Anyone writing extensions for the Launcher would only need to use these typings.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@colin969 thx!

**Pull request merged**
