### PR TITLE
Added type definition for eventemitter3-1.2.0

### PR DESCRIPTION
**Pull request by Stubb0rn**
[eventemitter3](https://github.com/primus/eventemitter3)

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by vvakame** [comment]
please rename `eventemitter3/eventemitter3-1.2.0.d.ts` to `eventemitter3/eventemitter3.d.ts`.
version name is not required default.

**Comment by vvakame** [comment]
please remove `eventemitter3/eventemitter3-tests.ts.tscparams`.

**Comment by vvakame** [comment]
*eventemitter3/eventemitter3.d.ts*

to authors (@mrk21 @leonyu). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by Stubb0rn** [comment]
@vvakame If I remove `eventemitter3/eventemitter3-tests.ts.tscparams` tests will not pass. To use type definition with ES6 target `--allowSyntheticDefaultImports` flag is necessary. 
`eventemitter3` is single export CommonJS module and there is no equivalent in ES6 for this type of export. There are 2 approaches for solving this problem:
* export fake namespace in definition file that fools typescript compiler and allows to import this module using `import * as module from "module"`
* define export in definition file as it is in CommonJS module and for ES6 target use `default` import syntax `import module from 'module'`, but that requires support from module loader to create `default` export for this module in runtime and requires compiler flag.

I wasn't sure what approach is more common, but second one looked more reasonable to me. Let me know if I made incorrect choice.

**Comment by vvakame** [comment]
We uses `import * as module from "module"` style.
Now, ncjs and esm compatibility is not determined. (if correct the my knowledge)
We are following default TypeScript compiler behavior now.

**Comment by andy-ms** [comment]
I think having `--allowSyntheticDefaultImports` is necessary here. `--module commonjs` may be preferable. @RyanCavanaugh can you verify this?

**Comment by leonyu** [comment]
Unless something changed in TS2.0 that I am not aware of, I don't think TypeScript code written against this definition would emit working JS code. 

[`eventemitter3`](https://github.com/primus/eventemitter3) is still a CommonJS module. It has not been converted to ES6/TypeScript. The import/require has to be written in special ways in order for it to work with TypeScript or Babel module resolver: 

* `import * as module from 'module';`
* `import module = require('module');`

The following works in Babel but not in TypeScript 
* `import module from 'module';` 

I don't think `allowSyntheticDefaultImports` is sufficiently. `allowSyntheticDefaultImports` explicitly says "does not affect code emit, just typechecking."

**Comment by Stubb0rn** [comment]
There are 2 ways to import this module with updated type definition:
* `import module from 'module'` that can be used together with transpiler that adds `default` export in runtime(e.g. Babel) and `--allowSyntheticDefaultImports` flag
* `import module = require('module')` that can be used with TypeScript only (with `--module commonjs`)

This module should never be imported using `import * as module from 'module'` because it is semantically incorrect, since it doesn't export namespace. I think that creating fake namespace to fool TypeScript compiler is not the best approach.

**Comment by leonyu** [comment]
While enforcing ES6 module paradigm over CommonJS module might be a good goal to strive for in the long run, forcing users to add Babel to their tool chain just to resolve ES6<->CommonJS differences is not practical.  

---

ES6 and CommonJS module semantics are totally different. 

* In ES6, you export names. It just so happen one of the names is `default`. It is perfectly valid to do `import {default as module} from 'module';` 
* In CommonJS, you export one and only one JavaScript object, it can be anything. 

The mapping the two different semantic system is entirely non-standardized and determine by the transcompiler. So saying whether one syntax is correct or incorrect in that context is fairly arbitrary.

**Comment by Stubb0rn** [comment]
I believe that type definition should reflect real state of the module and solving of ES6<->CommonJS interop problems should be handled by module users. 'eventemitter3' module exports non-module entity (class) and importing it using `import * as module from 'eventemitter3'` should by default rightfully result in compile error (`TS2497: Module ''eventemitter3'' resolves to a non-module entity and cannot be imported using this construct.`). There are multiple ways to import this module but determining the right way should be entirely up to module user.

I can update tests to use standard TypeScript import syntax `import module = require('module')`, because this seems to be recommended way of importing single export CommonJS modules exporting non-module entity based on [TypeScript ES6 modules spec](https://github.com/Microsoft/TypeScript/issues/2242). But `.tscparams` file will still be required, because `-m commonjs` needs to be specified to compile tests with `-t es6`.

**Comment by andy-ms** [comment]
Agree with @Stubb0rn

**Comment by leonyu** [comment]
Any solution that can cope with both ES6 and CommonJS module imports in the same app while still doesn't require additional transpiler should satisfy my concerns. 

In the older version of the [wiki (earlier this year)](https://github.com/Microsoft/TypeScript-Handbook/commit/80a7d6edbb5cc67c68ece2fdc7ca7fab423be3d9#diff-dba8dc2da3c50917f7aa8ff8a1555671L55), there was the "Class Decomposition" and "Single Complex Object in Modules" style which allowed for the same definition to be imported using both ES6 and CommonJS semantic. I have seen a number of library's definition were written using using that pattern. It looks like the wiki entry has been deleted. Is that style no longer promoted?

**Comment by andy-ms** [comment]
The module [source](https://github.com/primus/eventemitter3/blob/master/index.js) uses `module.exports = EventEmitter;` where `EventEmitter` is the name of a class. You can't have an ES6 import if you export a class/function. More info [here](https://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y).

**Comment by leonyu** [comment]
So is adding `allowSyntheticDefaultImports` to `tsconfig` the new recommendation from Microsoft/TypeScript team for importing CommonJS modules in ES6 land?

**Comment by andy-ms** [comment]
Pinging @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Don't use `allowSyntheticDefaultImports` unless your module loader actually creates synthetic defaults. Even then, it's probably a bad idea unless you know the library author is going to make a real default export at some point in the future.

The *correct* thing to do is just use `import x = require('y');` syntax when you're importing an object that is callable or constructable. When the library eventually (hopefully?) creates a real default export, you can switch to `import x from 'y';`. But it's a lie in the meantime to a) use ES6 syntax to do something ES6 syntax *cannot* do (`import * as x from 'y'; x();`) or b) rely on a default export that isn't actually there (`allowSyntheticDefaultImports`). Relying on (b) is less bad because presumably you know the behavior of your module loader, but why use a kludge when you don't have to?

**Comment by zhengbli** [comment]
@Stubb0rn can you update the PR to address the comments? Thanks!

**Comment by Stubb0rn** [comment]
@zhengbli PR already contains all changes, that were discussed in comments. It already uses `import x = require('y');` syntax in tests. I don't see what other changes I need to make.

**Pull request merged**
