### PR TITLE
Added stacktrace.js and node-stack-trace definitions.

### PR DESCRIPTION
**Pull request by niemyjski**

### CODE REVIEW

**Comment by vvakame** [comment]
*node-stack-trace/node-stack-trace.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/node-stack-trace
  * http://bower.io/search/?q=node-stack-trace
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (node-stack-trace/node-stack-trace-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*stacktrace/stacktrace.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/stacktrace
  * http://bower.io/search/?q=stacktrace
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (stacktrace/stacktrace-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by niemyjski** [comment]
@vvakame  you have two libraries already called stack trace... this one is specifically for node so that is why it was prefixed.

**Comment by niemyjski** [comment]
@vvakame both packages meet the test and naming conventions.. Not sure why the travis tests don't pass.

**Comment by vvakame** [comment]
@niemyjski thank you for your contributions.
please rename node-stack-trace/node-stack-trace.d.ts to stack-trace/stack-trace.d.ts. https://www.npmjs.com/package/stack-trace
and stacktrace/stacktrace.d.ts to stacktrace-js/stacktrace-js.d.ts. https://www.npmjs.com/package/stacktrace-js
node-stack-trace/node-stack-trace.ts does not have -tests.ts prefix.
please read this documents. http://definitelytyped.org/guides/contributing.html#tests try with --noImplicitAny option.

**Comment by niemyjski** [comment]
@vvakame, thanks for your help :).

**Comment by vvakame** [comment]
@niemyjski :+1:

**Pull request merged**
