### PR TITLE
Fix file-saver hyphen

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
The package reflects the `file-saver` package ([here](https://www.npmjs.com/package/file-saver)).

Found from http://stackoverflow.com/questions/40439128/typescript-types-package-name-does-not-match-implementation-package-name

### CODE REVIEW

**Comment by andy-ms** [comment]
I ran: `npm deprecate @types/filesaver "This package has been moved to @types/file-saver"`

**Comment by DanielRosenwasser** [comment]
Thanks @andy-ms

**Comment by Kaffiend** [comment]
There appears to be some deviation in the package name and the types definition file again. 
npm installs file-saver in a file-saver directory and @types/file-saver is saved in @types/filesaver, modules not found until directory renamed to match. Is this just whats on npm?

**Comment by andy-ms** [comment]
When I open an empty project and install `@types/file-saver` it installs to `node-modules/@types/file-saver`. Are you sure you don't have a (possibly nested) dependency on `@types/filesaver`?

**Pull request merged**
