### PR TITLE
Fix type of unselectable

### PR DESCRIPTION
**Pull request by Ailrun**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://technet.microsoft.com/en-us/windows/hh801966(v=vs.60)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by Ailrun** [comment]
Oh, it's super fast. Thanks!

**Comment by rhyek** [comment]
I'm getting the following error when updating `react`, `react-dom` and their respective `@types packages:

```
...
    Types of property 'unselectable' are incompatible.
      Type '"off" | "on" | undefined' is not assignable to type 'boolean | undefined'.
        Type '"off"' is not assignable to type 'boolean | undefined'.
````
How can I fix this?

**Comment by Ailrun** [comment]
@rhyek some of your package depends on old react typing. You should check where such different typing comes.

**Pull request merged**
