### PR TITLE
Fix exports to allow named exports

### PR DESCRIPTION
**Pull request by jineshshah36**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This update should not changing anything for existing users of this package. It just makes the exports accessible for naming when emitting declarations

### CODE REVIEW

**Comment by benbayard** [comment]
Is this a duplicate of another PR?

**Comment by jineshshah36** [comment]
That one says it was merged into master but when I check master it doesn't look merged. I couldn't figure out why so I figured I'd resubmit.

**Review by benbayard — APPROVED** [review]

**Comment by benbayard** [comment]
IT could be a github cache problem for code bases this large, I'm unsure. I re-approved.

**Comment by jineshshah36** [comment]
Thanks

**Pull request merged**
