### PR TITLE
New definitions for jquery.highlight.js

### PR DESCRIPTION
**Pull request by Pro**

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.highlight/jquery.highlight.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.highlight
  * http://bower.io/search/?q=jquery.highlight
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.highlight/jquery.highlight-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
`jquery.highlight` is already used in bower.

**Comment by Pro** [comment]
@vvakame Whoops! Yes, you are right, and it's a different library.
What would be the best name then for this lib?
(Github URL is: https://github.com/bartaz/sandbox.js/blob/master/jquery.highlight.js)
Something like?:
* `jquery.highlight-bartaz`
* `jquery.highlight.js`
* `jquery.highlight-sandbox`

**Comment by vvakame** [comment]
`jquery.highlight-bartaz` ?

**Comment by Pro** [comment]
@vvakame done. Ready to merge

**Comment by vvakame** [comment]
:+1: thanks mate.

**Pull request merged**
