### PR TITLE
Added AWS Firehose members to aws-sdk

### PR DESCRIPTION
**Pull request by prearrangedchaos**
Please fill in this template.

- [x ] Make your PR against the `master` branch.
- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ]x Test the change in your own code. (Compile and run.)
- [ ]x Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `tsc` without errors.
- [ x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x ] Increase the version number in the header if appropriate.
- [ x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Thoughts @midknight41 @CasperSkydt ?

**Comment by midknight41** [comment]
AWS now ship types with the sdk. This definition is now redundant.

**Comment by aozgaa** [comment]
@prearrangedchaos , can you arrange to remove these typings then: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package ?

**Comment by minestarks** [comment]
I'm closing out this PR as it's been inactive for a few weeks. This package should be removed from DefinitelyTyped.

**Pull request closed without merging**
