### PR TITLE
[node] Make definitions of generateKeyPair(Sync) less restrictive

### PR DESCRIPTION
**Pull request by akihikodaki**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.) (not required in this case)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

Changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
Wow this is getting out of hand.

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Meant to request changes, missing tests.

**Comment by akihikodaki** [comment]
3a248cfca859e96a244bac134517b4d6d9e8ecb8 adds tests.

**Comment by akihikodaki** [comment]
Can anyone review the latest revision? Thanks.

**Comment by akihikodaki** [comment]
ba03239b99ceb8c63b2dc2b2e4d7e84b418e7c18 is rebased to 3fee2364dfda7c2beb65dc6e1980e41b2ed30751. The latest change needs to be reviewed.

**Comment by weswigham** [comment]
@SimonSchick do you still have opinions?

**Comment by sandersn** [comment]
@SimonSchick can you review this again? I don't want to merge a change to node's types without an expert signing off.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Need experts signoff

**Comment by sheetalkamat** [comment]
Needs sign off from @SimonSchick

**Pull request closed without merging**
