### PR TITLE
[eslint] include `:exit` nodes in `NodeListener`

### PR DESCRIPTION
**Pull request by Ayc0**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm run test eslint`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://eslint.org/docs/latest/extend/custom-rules#rule-basics
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This is a partial fix for https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60281 (I only implemented `<node>:exit`, not `<selector>:exit`).

Before | After
-|-
image | image image

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]

**Comment by Ayc0** [comment]
@bradzacher do you know what's the process to merge & deploy this PR?

**Comment by bradzacher** [comment]
See the above comment
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64630#issuecomment-1460167738

**Review by jakebailey — APPROVED** [review]

**Comment by Ayc0** [comment]
Ready to merge

**Comment by Ayc0** [comment]
Thanks everyone!

**Pull request merged**
