### PR TITLE
[react-dom] Update test-utils/index.d.ts

### PR DESCRIPTION
**Pull request by claasahl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react/blob/1e3e30dae2bcfbeb0abc686f2a37aec208eedb39/packages/react/src/ReactAct.js#L22
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]

**Comment by claasahl** [comment]
ready to merge

**Comment by icatalina** [comment]
👋 @claasahl / @eps1lon ! Just wanted to understand this change. Before this, we only had to await acts that include a promise. Now we seem to have to await _all_ acts. Does this mean ALL acts must be awaited now? did something change?

**Comment by eps1lon** [comment]
> 👋 @claasahl / @eps1lon ! Just wanted to understand this change. Before this, we only had to await acts that include a promise. Now we seem to have to await _all_ acts. Does this mean ALL acts must be awaited now? did something change?

When you say "have to", do you mean some lint rule that rejects floating promises?

While `act` definitely returns a PromiseLike, it's not a full Promise. But then `act` really does return a PromiseLike in all instances. Might be best to only return a PromiseLike if something was actually returned. This would still make implicit returns PromiseLike and therefore trigger the ESLint rule. But then you have at least a better fix than just disabling this lint rule for every act call.

@icatalina Could you open an issue and ping me there so that I don't forget? Thanks!

**Comment by icatalina** [comment]
> When you say "have to", do you mean some lint rule that rejects floating promises?

yes and no, we do have a lint rule, but was thinking more on the lines of: _we have uncovered an issue where not waiting has some nasty side effect and that's why we are changing the types_

> Could you open an issue and ping me there so that I don't forget? Thanks!

definitely, where do you want it? this repo?

**Comment by eps1lon** [comment]
> definitely, where do you want it? this repo?

This repo yes. Not sure if they defer to discussions or not nowadays but that doesn't really matter. Just need it somewhere.

**Comment by CreativeTechGuy** [comment]
@icatalina Thanks for starting this discussion! I looked for an issue and I don't see it. Would you like me to create one for you?

**Comment by icatalina** [comment]
Been busy over the weekend, feel free to create one. Otherwise I'll do it on Monday 🙇

**Comment by CreativeTechGuy** [comment]
It looks like DefinitelyTyped uses Discussions not Issues for this sort of thing. So I've created #63394!

**Comment by icatalina** [comment]
Thanks heaps @CreativeTechGuy

**Comment by CreativeTechGuy** [comment]
@eps1lon - Bumping the discussion that was created in case you haven't seen. #63394. It's causing a lot of pain for those affected and should be an easy fix.

**Comment by eps1lon** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63561. Should be released shortly

**Comment by CreativeTechGuy** [comment]
Thank you @eps1lon!

**Pull request merged**
