### PR TITLE
Added wait to i18n.Options interface

### PR DESCRIPTION
**Pull request by asterikx**
Enables setting global wait-flag. Important for react-i18next>=3.1.0
(https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#310)

### CODE REVIEW

**Comment by mxl** [comment]
This should be applied to [react-i18next type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-i18next/index.d.ts), not i18next. And it already has `wait` option.

**Comment by sheetalkamat** [comment]
Leave a comment

**Comment by mulles3008** [comment]
Yes, that's right, but setting the wait-flag _globally_ requires setting the wait prop on the i18next instance (which is then passed to the the I18nextProvider component of react-i18next). The definitions you linked only apply to setting the wait flag on the HOC-component provided by react-i18next (_locally_ so to speak).

**Comment by mxl** [comment]
@mulles3008 I think it's hard and may be not even possible to move this option to react-i18next definitions. I will try to find workaround later but for now it's better to move react-i18next options to separate interface and add a comment:
```typescript
// init options for react-i18next
interface ReactOptions {
  wait?: boolean;
}
interface I18n {
  init(options?: Options&ReactOptions, callback?: (err: any, t: TranslationFunction) => void): I18n;
  ...
}
```
to make code more documented and avoid accidental removal by other contributors.

@sheetalkamat Please reopen PR.

**Comment by mxl** [comment]
👍

**Pull request merged**
