### PR TITLE
Webix patches

### PR DESCRIPTION
**Pull request by pthom**
Simple patches for $$ and form.getValues()

### CODE REVIEW

**Comment by vvakame** [comment]
@mkozhukh could you review this PR?
...possibly, Is the same person?

**Comment by mkozhukh** [comment]
I can confirm that both updates are correct

**Comment by vvakame** [comment]
@mkozhukh thanks!
@pthom thanks mate!

**Comment by pthom** [comment]
Happy to help !
Thank you !

**Pull request merged**
