### PR TITLE
Update repo for chart.js

### PR DESCRIPTION
**Pull request by eran-pinhas**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by adripanico — CHANGES_REQUESTED** [review]
The original link is properly redirected to the current repo.

I don't see the point of this PR.

**Review by danmana — APPROVED** [review]

**Comment by eran-pinhas** [comment]
@danmana Can this be merged?

**Comment by adripanico** [comment]
Again, I don't see the point of this change.

**Comment by danmana** [comment]
> @danmana Can this be merged?

While I don't see anything wrong with this PR, 3 other maintainers have expressed their opinion that there is no point in making the change.

As far as I know, the GitHub redirect will continue to work for the foreseeable future, so I don't see a strong reason to push this.
Anyway, I can't override the other reviewers.

I propose we close this PR.

@eran-pinhas you are more than welcome to make other PRs, which improve the type definitions, and I will review and approve them.

**Comment by eran-pinhas** [comment]
Sure, no big deal, thanks everyone

**Pull request closed without merging**
