### PR TITLE
Type Definitions for DataTables Buttons extension.

### PR DESCRIPTION
**Pull request by SammyG4Free**
Added new type definitions file and test file to support DataTables Buttons extension.

### CODE REVIEW

**Comment by vvakame** [comment]
`bower info datatables-buttons` is it? please rename to datatables-buttons/datatables-buttons.d.ts

**Comment by SammyG4Free** [comment]
You mean, put it in a separate folder in the root? like <code>DefinitelyTyped/jquery.dataTables.buttons/jquery.dataTables.buttons.d.ts</code> ? Since <code>/jquery.dataTables/jquery.dataTables.d.ts</code> is the base library I am extending, I think it makes sense to maintain a similar naming convention (ie, keep the "jquery." prefix).

**Comment by vvakame** [comment]
please read this document.
http://definitelytyped.org/guides/contributing.html#naming-the-file

**Comment by SammyG4Free** [comment]
Updated to match naming standards - all good now @vvakame ?

**Comment by vvakame** [comment]
*datatables-buttons/datatables-buttons.d.ts*

Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/datatables-buttons
  * http://bower.io/search/?q=datatables-buttons
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (datatables-buttons/datatables-buttons-tests.ts or datatables-buttons/datatables-buttons-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
