### PR TITLE
Make Data Optional

### PR DESCRIPTION
**Pull request by sasial-dev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
This PR does not

### CODE REVIEW

**Comment by sasial-dev** [comment]
The bot is freaking out - might be on my end

**Comment by peterblazejewicz** [comment]
@sasial-dev what's the status?

**Comment by sasial-dev** [comment]
@peterblazejewicz I finished the code, but the bot's having a freak out over the fact that it can't fin the owners etc and also .
Not 100% sure how to fix it, as on the branch there's commits...

**Comment by peterblazejewicz** [comment]
It should have no relation to GH bot. Can you rebase your branch from current master and force push changes?
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch

**Pull request closed without merging**
