### PR TITLE
pusher-js: make available via global variable

### PR DESCRIPTION
**Pull request by markrian**
I *think* this is close to the kind of change necessary to achieve what I need.

In a simplified example of how I'd like to use this (this is the entirety of the TypeScript file):
```ts
const p: pusher.Pusher = new Pusher('key');
```

based on what's in the documentation for [UMD modules][1].

I don't really understand what I'm doing here. I'd be grateful for some feedback as to how this should be done.

[1]: https://www.typescriptlang.org/docs/handbook/modules.html#umd-modules

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.typescriptlang.org/docs/handbook/modules.html#umd-modules
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by DanielRosenwasser** [comment]
What this allows you to do is say "I know that `pusher` will be globally available if I'm *not* using modules."

That means you'd need to write something like

```ts
let p = new pusher.Pusher();
```

You should really make sure that this code works at runtime though!

**Comment by markrian** [comment]
@DanielRosenwasser thanks - I'm still trying to wrap my head around this.

I'm using lodash as a model, but still not getting the behaviour I expect/want for pusher.

I don't think this should be merged yet. I'd welcome some more input/help, but if you'd prefer this PR is closed until I have something that's viable...?

**Comment by markrian** [comment]
I think the problem is that the existing namespace is `pusher` (lowercase) but the global that gets defined in the absence of a module system is called `Pusher` (uppercase)... although I can't put my finger on *why* it's the problem, or how to resolve it.

Lodash, for example, is typed like this (with irrelevant noise removed):

```ts
export = _;
export as namespace _;

declare let _: _.LoDashStatic;

declare namespace _ {
    interface LoDashStatic {
    }
}
```

which allows for this kind of usage:
```ts
let underscore: _.LoDashStatic = _;
```

Note that the `_` name is overloaded/referenced in various ways. I don't really understand how these are related to each other.

In pusher's case, it's currently written like this (with irrelevant noise removed):
```ts
declare namespace pusher {
    interface PusherStatic {
        new (apiKey: string): Pusher;
    }

    interface Pusher {
    }
}

declare var pusher: pusher.PusherStatic;

export as namespace pusher;

export = pusher;
```
Here, the `pusher` name is overloaded in, AFAICT, the same ways lodash's `_` is.

The problem is that while lodash creates a global called `_`, pusher creates a global called `Pusher`.

The kind of usage I'm hoping for is something like this:
```ts
let p: pusher.Pusher = new Pusher('key');
```

but that gives the error `error TS2304: Cannot find name 'Pusher'.`

**Comment by markrian** [comment]
Okay, I've found a solution that works, but I don't understand why. I'd really appreciate it if someone could explain why!

I've simply changed the `export as namespace` line to read as:
```ts
export as namespace Pusher;
```

which allows for this kind of usage:
```ts
let p: Pusher.Pusher = new Pusher('key', {});
```
What I don't understand is how TypeScript knows that the global value `Pusher` (on the right hand side of that assignment) is of type `pusher.PusherStatic`. The only way I can imagine is that it's due to the `declare var pusher: pusher.PusherStatic;` line in the declaration file, but the name of the declared variable there is *lowercase*, whereas the global value is `Pusher`; so I just don't see how they are connected.

**Comment by markrian** [comment]
Hmm, the CI build failed, but it seems unrelated. Should I merge master into this, or something?

**Comment by RyanCavanaugh** [comment]
@markrian Please fix the failures indicated in the Travis CI log.

**Comment by markrian** [comment]
Okay, I'd like to fix the failure, but I don't see how my change could possibly have caused the failure. I feel like the commit from master I initially branched off was already broken, or became broken somehow. I'm going to merge current master in and see how that goes.

**Pull request merged**
