### PR TITLE
[formidable] Update typings for 2.0.1

### PR DESCRIPTION
**Pull request by gboer**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by gboer** [comment]
The tests for formidable itself pass without issues, but the `npm run test-all` fails with this:
```
Error in restify
Error: /Users/gijsboer/Documents/Projects/Own/challenger/DefinitelyTyped/types/restify/restify-tests.ts:185:34
ERROR: 185:34  expect  TypeScript@4.5 compile error:
Property 'path' does not exist on type 'File'.
ERROR: 186:34  expect  TypeScript@4.5 compile error:
Property 'name' does not exist on type 'File'.

    at /Users/gijsboer/Documents/Projects/Own/challenger/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gijsboer/Documents/Projects/Own/challenger/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

I am unsure how to fix this. I can update the restify code, but since that hasn't updated to formidable 2.x yet, that seems like a bad idea. Does anyone know how to solve/manage this?

Also getting the following suggestion:
```
{"formidable": [{"fileName":"/Users/gijsboer/Documents/Projects/Own/challenger/DefinitelyTyped/types/formidable/index.d.ts","ruleName":"npm-naming","message":"The declaration doesn't match the JavaScript module 'formidable'. Reason:\nThe JavaScript module exports a property named 'enabledPlugins', which is missing from the declaration module."}]}
```

As far as I can see, it is there in the module declaration, so I don't really see what I'm missing here.

**Comment by gboer** [comment]
I updated the tests of restify so that the tests don't fail anymore. I hope that's fine, since they are only tests and do not change the actual typings of restify in any way.

**Comment by karlhorky** [comment]
cc @peterblazejewicz @sandersn

**Comment by peterblazejewicz** [comment]
> I updated the tests of restify so that the tests don't fail anymore. I hope that's fine, since they are only tests and do not change the actual typing's of restify in any way.

That's not that easy, unless you folks are pretty sure v1 and v2 of `formidable` are (and will be)  both compatible with `restify` v1 (and later with v2).
I think, due to `formidable` visibility in the ecosystem (`popular package`), you could also be adviced to do following:
- add 'formidable' types to allowed dependencies list:
https://github.com/microsoft/DefinitelyTyped-tools/pulls
this is due to `restify` depending on v1 of `formidable`:
https://github.com/restify/node-restify/blob/master/package.json#L101
- update `restify` DT to use `package.json` with explicit dependency to v1 of `@types/formidable`, this is always safe change (no api is changed)
- in future, when 'restify` is updated and tested with v2 of formidable, direct dependency
- 
To put this into the context, other packages also depends on v1 of formidable, not v2:
https://github.com/hatashiro/express-formidable/blob/master/package.json#L28

So please, let us know if you are sure about compatibility of v2 with other content (not about tests coverage here on DT)
thx!

**Comment by gboer** [comment]
Imagine things to be easy :) Thanks for the reply and explanation/help :) Adding the specific version of formidable to a `package.json` of `restify` sounds like the best approach. I'll have a look at fixing my PR today and get this resolved.

**Comment by gboer** [comment]
PR up [here](https://github.com/microsoft/DefinitelyTyped-tools/pull/341)

**Comment by peterblazejewicz** [comment]
so the upstream PR was accepted. To test this locally, get latest version from upstream master, rebase, drop artefacts (git clean -fxd) and reinstall before running test and `npm run test-all`

**Comment by gboer** [comment]
hmm, I think I got the PR in `microsoft/DefinitelyTyped-tools` wrong. Shouldn't it have been `formidable` rather than `@types/formidable`? I'm running the tests locally, but I still get the same issue with `restify`. It still tries to use the wrong (local) types.

**Comment by gboer** [comment]
Nope, wasn't it either. I removed the dependency check, to have it continue even when specifying dependencies that are not allowed and I'm still getting the same issue when installing `formidable` (also with `@types/formidable` added to it). Somehow it still picks up local types.

**Comment by peterblazejewicz** [comment]
this:
```json
"@types/formidable": "1"
````
should be a dependency of those packages that uses `formidable`. DT types depends on native packages (`formidable`), only fi that package ships types definition natively as part of NPM package.
I'll review this when I have a time later today

**Comment by peterblazejewicz** [comment]
ok, so it does not work on DT CI (within repo), let me say sorry and revisit v1/v2, by copying everything into v1 and adding changes for v2. Then in `restify`, just amend `tsconfig.json` path resolution to point to v1 (no change in code required).
Tested locally, here is a gist with entire diff:
https://gist.github.com/peterblazejewicz/9512e5a20d9ab197d955ce19544b1286

**Comment by gboer** [comment]
Ah, that's quite alright Peter :) Glad for the assistance in any case! And thanks for the gist, I'll update this PR in a bit with the changes.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
thx!

**Comment by gboer** [comment]
Ready to merge

**Pull request merged**
