### PR TITLE
[aws-iot-device-sdk] - Fix references to the mqtt types

### PR DESCRIPTION
**Pull request by thchia**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/aws/aws-iot-device-sdk-js/blob/master/CHANGELOG.md#210-sep-28-2017>> **(Update of mqtt package from 2.2.x to 2.13.x)**
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

#20343

### CODE REVIEW

**Comment by thchia** [comment]
The test case uses references to the old `@types/mqtt`. I'm not sure how to stop it from doing that.

**Comment by niik** [comment]
> The test case uses references to the old @types/mqtt. I'm not sure how to stop it from doing that.

@thchia Ah, so I see that mqtt is providing its own types now, there was a PR opened by @andy-ms (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15560) to start using that instead but it got stale and was never merged. What you need to do here is to add mqtt as a dependency by creating a new package.json file. You can look at @andy-ms' PR for inspiration. Once you've done that you should be able to switch the import statements from `@types/mqtt` to just `mqtt`.

**Comment by thchia** [comment]
I believe I also have to add `mqtt` to the `types-publisher` whitelistedDependencies list:

Microsoft/types-publisher#387

**Review by ghost — APPROVED** [review]

**Comment by andy-ms** [comment]
Check travis again; new error should be easy to fix:
```
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/aws-iot-device-sdk/package.json should set `"private": true`
```

**Comment by thchia** [comment]
@andy-ms just so this doesn't go stale... not sure why the CI broke but I think I've made all the necessary changes.

**Comment by niik** [comment]
@thchia Looks like you've got a merge conflict here. Try merging from master

**Comment by thchia** [comment]
Quick bump - @niik @andy-ms

**Comment by niik** [comment]
:+1:

Nicely done @thchia. I can't merge this though, just be patient and someone will come along, there's a ton of activity in this repo and the maintainers are usually incredibly responsive in relation to the workload.

**Pull request merged**
