### PR TITLE
[node] fs: add `ref`/`unref` to `FSWatcher`

### PR DESCRIPTION
**Pull request by Semigradsky**
Closes #68296

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
@Semigradsky 🙇🏻

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by josdejong** [comment]
When updating from `@types/node@20.11.5` to `@types/node@20.11.6` in my project [`lossless-json`](https://github.com/josdejong/lossless-json) that uses Vite, I get the following error:

```
node_modules/vite/dist/node/index.d.ts:68:15 - error TS2420: Class 'import(".../node_modules/vite/dist/node/index").FSWatcher' incorrectly implements interface 'import("fs").FSWatcher'.
  Type 'FSWatcher' is missing the following properties from type 'FSWatcher': ref, unref

68 declare class FSWatcher extends EventEmitter implements fs.FSWatcher {
                 ~~~~~~~~~


Found 1 error in node_modules/vite/dist/node/index.d.ts:68
```

Can it be that this PR introduces a breaking change in how it's being used by Vite? How to solve this?

**Comment by Semigradsky** [comment]
@josdejong please open an issue in vite repo and link this PR

**Comment by devversion** [comment]
FYI: Seeing the same with `chokidar`.

```
../../../../node_modules/chokidar/types/index.d.ts:9:14 - error TS2420: Class 'import("X/node_modules/chokidar/types/index").FSWatcher' 
  incorrectly implements interface 'import("fs").FSWatcher'.
  Type 'FSWatcher' is missing the following properties from type 'FSWatcher': ref, unref

9 export class FSWatcher extends EventEmitter implements fs.FSWatcher {
```

**Comment by Semigradsky** [comment]
The same

**Comment by devversion** [comment]
@Semigradsky For sure, but note that people are capturing this here for easier discoverability, and to provide context, so that a good issue can be created then (without it potentially being one-offs)

**Comment by peterblazejewicz** [comment]
> Can it be that this PR introduces a breaking change in how it's being used [...]

yes, every change here can introduce a problem outside. We're (i.e. community) trying to limit possible unavoidable repercussions, and `@Semigradsky et al.` are really god at that! thanks!

**Pull request merged**
