### PR TITLE
[mongodb] Add missing directConnection to MongoClientOptions interface

### LINKED ISSUE #50818: [@types/mongodb] MongoClientOptions interface is missing directConnection
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9b18d31dcea350cc50ad3ebc94e57e95c294543c/types/mongodb/index.d.ts#L347

As the title says, the interface `MongoClientOptions` in `@types/mongodb` is missing the `directConnection` option, as documented here in the latest MongoDB driver docs: https://mongodb.github.io/node-mongodb-native/3.6/api/MongoClient.html#.connect

Would be very nice if this can be added so I don't have to `@ts-ignore` the property-does-not-exist error when adding this option to an options object :)

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #50818

Documentation:
https://mongodb.github.io/node-mongodb-native/3.6/api/MongoClient.html#.connect

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by martin-badin** [comment]
Hi, there is an issue with a different package but I don't know why. The package is wrong, I think so.

```
Error in mongoose
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/mongoose/test/model.ts:613:107
ERROR: 613:107  expect  TypeScript@4.2 compile error: 
No overload matches this call.
  The last overload gave the following error.
    Type 'string' is not assignable to type 'never'.
```

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongodb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongodb@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'mongodb'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a314bdce40571115d6a577021f2d239a6e19ebdc
</p>

**Comment by martin-badin** [comment]
@peterblazejewicz Hi, could you please review?

**Review by emmanuelgautier — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
