### PR TITLE
updated types of mongoose-aggregate-paginate-v2

### PR DESCRIPTION
**Pull request by everythingguy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/aravindnc/mongoose-aggregate-paginate-v2/issues/44>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by cw-alexcroteau — APPROVED** [review]
LGTM

**Review by acrilex1 — APPROVED** [review]
Sorry approved with wrong account

**Review by amcasey — CHANGES_REQUESTED** [review]
Removing the `| undefined` has a specific semantic meaning - that the optional property may not be `undefined` if it is present.  Was that the intent of this change?

**Comment by everythingguy** [comment]
> Removing the `| undefined` has a specific semantic meaning - that the optional property may not be `undefined` if it is present. Was that the intent of this change?

The conflict between types is still resolved if I add the `| undefined` back to each field. I will add those back just to be safe.

**Comment by everythingguy** [comment]
The CI did not like that change. We should be fine to remove the undefined from the type definition since this new definition is coming from a library that created these variables in the same manner. This library is designed to work with `mongoose-paginate-v2` which creates the same labels with this new type definition. Since the types are currently different typescript fails to build if both libraries are install and imported.

**Comment by everythingguy** [comment]
@amcasey I am not sure why the CI is now failing when reverting back to the original commit.

**Comment by sandersn** [comment]
I broke CI tests yesterday when I updated the `@definitelytyped` packages.

**Comment by everythingguy** [comment]
Ok, I will try it again, adding back in the undefined types.

**Review by cw-alexcroteau — APPROVED** [review]

**Review by acrilex1 — APPROVED** [review]

**Review by izum286 — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by acrilex1** [comment]
Ready to merge

**Comment by samuelpares** [comment]
It is still conflicting.. just adding it to my project, breaks the services where I use Entities with the PaginateModel.

Entity
```
@Schema({ timestamps: true })
class BulkSend extends Document {
   ...
  @Prop({
    type: [{ type: MongooseSchema.Types.ObjectId, ref: 'BulkSendMessage' }],
  })
  messages: BulkSendMessage[];
}
```

In service constructor:
`private readonly bulkSendModel: PaginateModel<BulkSend>,`

Method in service
```
const bulkSend = await this.bulkSendModel.findOne({
  messages: id,
});
```

Error:

> No overload matches this call.
> Type 'string' is not assignable to type 'Condition<BulkSendMessage[]>'.
> 103       messages: id,

**Comment by cw-acroteau** [comment]
> It is still conflicting.. just adding it to my project, breaks the services where I use Entities with the PaginateModel.
> 
> Entity
> 
> ```
> @Schema({ timestamps: true })
> class BulkSend extends Document {
>    ...
>   @Prop({
>     type: [{ type: MongooseSchema.Types.ObjectId, ref: 'BulkSendMessage' }],
>   })
>   messages: BulkSendMessage[];
> }
> ```
> 
> In service constructor: `private readonly bulkSendModel: PaginateModel<BulkSend>,`
> 
> Method in service
> 
> ```
> const bulkSend = await this.bulkSendModel.findOne({
>   messages: id,
> });
> ```
> 
> Error:
> 
> > No overload matches this call.
> > Type 'string' is not assignable to type 'Condition<BulkSendMessage[]>'.
> > 103       messages: id,

Hi! Can you please open another PR to help fix it? I'm sorry I don't have my computer nearby so can't test this in depth, if you can't create a PR I'll do it in a couple of days.

**Comment by acrilex1** [comment]
> It is still conflicting.. just adding it to my project, breaks the services where I use Entities with the PaginateModel.
> 
> Entity
> 
> ```
> @Schema({ timestamps: true })
> class BulkSend extends Document {
>    ...
>   @Prop({
>     type: [{ type: MongooseSchema.Types.ObjectId, ref: 'BulkSendMessage' }],
>   })
>   messages: BulkSendMessage[];
> }
> ```
> 
> In service constructor: `private readonly bulkSendModel: PaginateModel<BulkSend>,`
> 
> Method in service
> 
> ```
> const bulkSend = await this.bulkSendModel.findOne({
>   messages: id,
> });
> ```
> 
> Error:
> 
> > No overload matches this call.
> > Type 'string' is not assignable to type 'Condition<BulkSendMessage[]>'.
> > 103       messages: id,

Hi!

Can you please open another PR to help fix it? I'm sorry I don't have my computer nearby so can't test this in depth, if you can't create a PR I'll do it in a couple of days.

Thanks!

**Pull request merged**
