### PR TITLE
Remove superfluous /// <reference types="node" />

### PR DESCRIPTION
**Pull request by jablko**
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by shiftkey — APPROVED** [review]
Approving on behalf of `@types/electron-packager` - not sure if there's any specific fedback you're looking for here @jablko...

**Comment by elibarzilay** [comment]
Is this ready for merging?  (It's still marked as "draft")

**Comment by jablko** [comment]
@elibarzilay Thanks for looking at this! It turns out that not all of these are superfluous. I'm working on a revision.

**Comment by avin-kavish** [comment]
Can't we go by a "if it's not broken, don't fix it" approach? Why do we need to remove superfluous types?

**Comment by andrewbranch** [comment]
Leaving it in causes `@types/node` to be installed as a dependency of these typings for downstream users, which puts unnecessary burden (npm install size and type checker work) on their projects, and can even cause breaks by introducing conflicting globals. IMO this is worth fixing, even if it doesn’t _look_ broken in the vacuum of DefinitelyTyped. Thanks @jablko 💯

**Comment by ExE-Boss** [comment]
Actually, I believe that this is necessary when a package depends on a module defined in `@types/node`, since **TypeScript** and [`@definitelytyped/publisher`][dt-publisher] won’t be able to infer the type dependency otherwise.

[dt-publisher]: https://github.com/microsoft/DefinitelyTyped-tools/tree/master/packages/publisher

**Comment by peterblazejewicz** [comment]
@jablko should we kill or proceed? Maybe we can split this into less problematic, more transparent changes first? (it would take longer though)

**Comment by shiftkey** [comment]
> @shiftkey Thank you for reviewing this PR! The author has pushed new commits since your last review. Could you take another look and submit a fresh review?

The package I was reviewing is no longer part of this PR, so I'm going to ignore these latest commits

**Comment by jakebailey** [comment]
A lot of these are cases where they really do pull in node types, but now do it indirectly afterwards. I will probably modify this PR to remove those cases as I think the indirect loading is probably not the best thing to have.

**Pull request merged**
