### PR TITLE
[@wordpress/date] add new definitions

### PR DESCRIPTION
**Pull request by dsifford**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by armanio123 — CHANGES_REQUESTED** [review]
I'm not very familiar with the library. I based my comments only on my understanding of the documentation. Let me know if you feel confident this is correct and I can merge it as is.

**Comment by dsifford** [comment]
@armanio123 Thanks for the keen eye. 

Documentation for this package (and most of the others currently) are inaccurate. I'm working on overhauling that as well on the `@wordpress` end once I get these and the other definitions merged.

End goal is to use typescript to type-check their javascript packages. (it's been a long work in progress 😝)

**Comment by armanio123** [comment]
Sounds good. I'll merge it as is.

**Review by armanio123 — APPROVED** [review]

**Comment by armanio123** [comment]
@dsifford I believe I took care of all of the `@wordpress` pull requests. As you mentioned that the documentation is outdated I have not checked them against it.

**Comment by dsifford** [comment]
@armanio123 You da man! Thanks so much. :smile:

**Pull request merged**
