### PR TITLE
Modified node-red__runtime SettingsLocal to Bring it Up to Date with node-red 3.0.0

### PR DESCRIPTION
**Pull request by bdpennington**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. (No chances necessary)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Changes:
- Updated runtime.LocalSettings to add new field 'httpStaticRoot' and updated field 'httpStatic' with new definition. Both were introduced in node-red 3.0.0
- Deleted redundant `| undefined` from optional types
- Went ahead and added any missing configs from the node-red 3.0.0 release found here: [https://github.com/node-red/node-red/blob/57ac90f837c1adb55665e0dc5953c26690571dda/packages/node_modules/node-red/settings.js](https://github.com/node-red/node-red/blob/57ac90f837c1adb55665e0dc5953c26690571dda/packages/node_modules/node-red/settings.js) (full view of the settings file shown in the PR listed below)

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/node-red/node-red/commit/57ac90f837c1adb55665e0dc5953c26690571dda](https://github.com/node-red/node-red/commit/57ac90f837c1adb55665e0dc5953c26690571dda)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. (Not sure about this one; I didn't see a header with a version number, but I did put it in the PR title)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## node-red__runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/node-red__runtime@latest/))
was missing the following properties:
1. plugins

## Formatting

The following files are not formatted:
1. types/node-red__runtime/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against beb0514535a61efc713bbc1ebc1b6e58c073b777
</p>

**Comment by bdpennington** [comment]
Updated original comment, adding that I went ahead and put in all missing settings from the 3.0.0 release. Also ran formatter, cause Danger bot said so.

**Review by MysteryBlokHed — COMMENTED** [review]
Having the `| undefined` on optional types is typically a good idea because of the `exactOptionalPropertyTypes` config option (unless there's a situation where you'd really never want someone to intentionally pass `undefined`): <https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes>

**Review by alexk111 — APPROVED** [review]
LGTM

**Comment by bdpennington** [comment]
Ready to merge

**Pull request merged**
