### PR TITLE
sjcl package: Modified decrypt parameter to allow for ciphertext as string.

### PR DESCRIPTION
**Pull request by damiandennis**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@damiandennis can you point to the docs/code where they use this parameter?

**Comment by damiandennis** [comment]
If you look in the demo, you will see they decrypt from a json string.

**Comment by damiandennis** [comment]
The part where they check if the first character is a curly brace in the string, then straight after that they decrypt it so its decrypting directly from a json string.

**Comment by paulvanbrenk** [comment]
@damiandennis Next time please post a link to the actual implementation. There are a lot of PRs we have open at any given time and the easier it is for us to evaluate them, the faster we can approve them. ;)

Thanks for your contribution though!!

**Comment by damiandennis** [comment]
Sure thing, Thanks

**Comment by paulvanbrenk** [comment]
My bad, reverted this PR.

**Comment by damiandennis** [comment]
Oh issue?

**Comment by paulvanbrenk** [comment]
@damiandennis mixed up two PRs, yours is fine.

**Pull request merged**
