### PR TITLE
react-datepicker v7 was migrated to TypeScript, typings no longer needed

### PR DESCRIPTION
**Pull request by Cerber-Ursi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by seckie — COMMENTED** [review]
I don't think we need updates for TypeScript migrated product.
Users just won't need to install this package.

**Comment by Cerber-Ursi** [comment]
1. Why we have the "no longer needed" workflow, then?
2. The specific reason for this request is that we're using Renovate, and right now it is able to update react-datepicker from v6 to v7. It doesn't know that it don't need types anymore though, so types package stays at v6, which is simply wrong (some of the signatures are different). If we released stub definitions for react-datepicker v7, update process could pick both packages at once, leaving the project in much cleaner state (still in need of manual interaction, but of a much more obvious one).

**Review by seckie — APPROVED** [review]
Alright. I verified that these changes match the results of [the operation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package).
Thanks.

**Review by jakebailey — APPROVED** [review]

**Comment by Cerber-Ursi** [comment]
Ready to merge

**Pull request merged**
