### PR TITLE
Improve gulp.watch()

### PR DESCRIPTION
**Pull request by tkrotoff**
gulp.watch() can mix task names (string) and callbacks

### CODE REVIEW

**Comment by vvakame** [comment]
@drewnoakes @progre could you review this PR?

**Comment by tkrotoff** [comment]
Ping @drewnoakes @progre @vvakame

**Comment by drewnoakes** [comment]
Sorry, I haven't done much gulp/TypeScript stuff lately. Can't really offer a good critique here.

**Comment by vvakame** [comment]
okay, it merged!
@drewnoakes thanks!
@tkrotoff thanks mate!

**Pull request merged**
