### PR TITLE
Added stripe v3 types, namespaced previous ones to v2

### PR DESCRIPTION
**Pull request by amritk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://stripe.com/docs/stripe.js?>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

Made changes from previous pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16539

### CODE REVIEW

**Comment by jleider** [comment]
Looks good to me. 👍

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by amritk** [comment]
@DanielRosenwasser so I'm new to typings, how do I get both of these versions installed now? I've tried 
```
typings install stripe@2.0.0 --source dt --global
typings install stripe@0.0.0 --source dt --global
typings install stripe --source dt --global
typings install dt~stripe@2.0.0 --global
typings install dt~stripe@0.0.0 --global
typings install dt~stripe --global
````
And have yet to get the right types file. Also installing the other version overwrites the previous one, how do I go about installing both versions side by side?

**Comment by DanielRosenwasser** [comment]
You want to use npm, not typings.

```
npm install stripe@2.0.0
```

**Comment by amritk** [comment]
That is actually the stripe node library, these are the typings for stripejs

**Pull request merged**
