### PR TITLE
fix: @storybook/addon-options: hierarchySeparator

### PR DESCRIPTION
**Pull request by joscha**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/storybooks/storybook/pull/1445
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by joscha** [comment]
depends on https://github.com/storybooks/storybook/pull/1383

**Comment by weswigham** [comment]
Ping again when the PR for these types is merged into the main project.

**Comment by joscha** [comment]
@typescript-bot the PR this one is depending on seems to take a little longer. I can close the PR and reopen it later, if that is better.

**Comment by joscha** [comment]
@weswigham this is ready now

**Review by weswigham — APPROVED** [review]

**Pull request merged**
