### PR TITLE
[carbon-components-react] Fix typo in ComposedModal#selectorPrimaryFocus prop name

### PR DESCRIPTION
**Pull request by wkeese**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [NA] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).  NOTE: HAD TO RUN `npm install csstype` to get it to work.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ComposedModal/ComposedModal.js#L85

Fixes #61471.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## carbon-components-react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/carbon-components-react@latest/))
was missing the following properties:
1. ActionableNotification
1. unstable_ColumnHang
1. unstable_DefinitionTooltip
1. unstable_FlexGrid
1. unstable_HStack

<details>
<summary>as well as these 16 other properties...</summary>
<p>unstable_IconButton, unstable_IconTab, unstable_Layer, unstable_OverflowMenuV2, unstable_Popover, unstable_PopoverContent, unstable_Stack, unstable_TabList, unstable_TabPanel, unstable_TabPanels, unstable_Theme, unstable_ThemeContext, unstable_Tooltip, unstable_VStack, unstable_usePrefix, unstable_useTheme</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7c7900ac132a516007ba35556ba5c2855e7516ba
</p>

**Comment by wkeese** [comment]
I added tests for ComposeModal (3a1f51c247c1ebd48e3f8eb357820e7d9ac6c89c) but I couldn't run them, so they aren't in this PR branch.

The problem is that `npm test carbon-components-react` fails because flatpickr isn't installed:

Error: /Users/bill/oss/DefinitelyTyped/types/carbon-components-react/lib/components/DatePicker/DatePicker.d.ts:1:47
ERROR: 1:47  expect  TypeScript@4.8 compile error: 
Cannot find module 'flatpickr/dist/types/options' or its corresponding type declarations.

However, when I installed flatpickr (f3c96bc6f8892d48cc3d48decbe3bfa51a0730fd) I just get other errors:

Error: /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md says to update package.json but I'm not even sure if it's talking about DefinitelyTyped's package.json or flatpickr's package.json.

Do you know how to fix those issues?

**Review by sgregoire — APPROVED** [review]

**Comment by gabritto** [comment]
> I added tests for ComposeModal ([3a1f51c](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3a1f51c247c1ebd48e3f8eb357820e7d9ac6c89c)) but I couldn't run them, so they aren't in this PR branch.
> 
> The problem is that `npm test carbon-components-react` fails because flatpickr isn't installed:
> 
> Error: /Users/bill/oss/DefinitelyTyped/types/carbon-components-react/lib/components/DatePicker/DatePicker.d.ts:1:47 ERROR: 1:47 expect TypeScript@4.8 compile error: Cannot find module 'flatpickr/dist/types/options' or its corresponding type declarations.
> 
> However, when I installed flatpickr ([f3c96bc](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f3c96bc6f8892d48cc3d48decbe3bfa51a0730fd)) I just get other errors:
> 
> Error: /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts:1:1 ERROR: 1:1 no-outside-dependencies File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts comes from a `node_modules` but is not declared in this type's `package.json`. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md
> 
> /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts:1:1 ERROR: 1:1 no-outside-dependencies File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts comes from a `node_modules` but is not declared in this type's `package.json`. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md
> 
> /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts:1:1 ERROR: 1:1 no-outside-dependencies File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts comes from a `node_modules` but is not declared in this type's `package.json`. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md
> 
> /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts:1:1 ERROR: 1:1 no-outside-dependencies File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts comes from a `node_modules` but is not declared in this type's `package.json`. See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md
> 
> https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md says to update package.json but I'm not even sure if it's talking about DefinitelyTyped's package.json or flatpickr's package.json.
> 
> Do you know how to fix those issues?

@wkeese I believe the instructions in https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md mean that you should add flatpickr as a dependency on this (carbon-components-react) package's `package.json`. However, I see that it is already there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7c7900ac132a516007ba35556ba5c2855e7516ba/types/carbon-components-react/package.json#L4

I'd have to do some more digging to figure out why this is failing for you.

**Review by gabritto — APPROVED** [review]

**Comment by wkeese** [comment]
OK thanks, let's just check in this change then and worry about the tests another day.

Ready to merge.

**Comment by wkeese** [comment]
Ready to merge

**Pull request merged**
