### PR TITLE
[react-navigation] Fix return type when fallback provided

### PR DESCRIPTION
**Pull request by LinusU**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/react-navigation/react-navigation/blob/0921889f7a3acfc6d6bcc4909d209eeeee985ba7/src/getChildNavigation.js#L6-L14
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by stigi — APPROVED** [review]
lgtm

Just one thing to be aware of: by adding yourself to the list of definition owners you'll get pinged every now and then to review a change. Just be aware of the added load.

**Comment by LinusU** [comment]
Yeah, I'm happy to help maintaining ☺️

**Comment by LinusU** [comment]
@robertohuertasm here you go: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28108

**Comment by robertohuertasm** [comment]
Thanks @LinusU for this! I really appreciate it! 👍

**Pull request merged**
