### PR TITLE
Add properties to react-widgets/DropdownList

### PR DESCRIPTION
**Pull request by MBillemaz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://jquense.github.io/react-widgets/api/DropdownList/>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by MBillemaz** [comment]
I don't understand the error, is that the npm install too long ?

**Comment by r3nya** [comment]
Hey @MBillemaz !

Yeah, looks like connection issue. :\

**Comment by MBillemaz** [comment]
Hey @r3nya !
So... should I do some changes to re-run ?

**Comment by r3nya** [comment]
I guess that you can change some line of code for it … or waiting for reviews. :)

**Comment by MBillemaz** [comment]
Okay thanks :)

**Review by r3nya — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

**Pull request merged**
