### PR TITLE
react-native-sqlite-storage typings added.

### PR DESCRIPTION
**Pull request by dryganets**
See: https://github.com/andpor/react-native-sqlite-storage

Please fill in this template.

- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ x ] The package does not provide its own types, and you can not add them.
- [ x ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ x ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ x ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by RodrigoAWeber** [comment]
Maybe you could add an overload in openDatabase function.

`export function openDatabase(location: string, version: string, name: string, timeout: number, success?: Function, error?: Function): SQLiteDatabase;`

**Comment by dryganets** [comment]
I fixed that. Double checked -  we don't pass `this` in success callback of databaseOpen, so no overload is needed.

**Review by plantain-00 — APPROVED** [review]

**Comment by dryganets** [comment]
How long does it usually takes to get it published to npmjs.org/@types
?

**Comment by fhelwanger** [comment]
@dryganets Here: https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated

**Pull request merged**
