### PR TITLE
[google-cloud__storage] Add examples to tests

### PR DESCRIPTION
**Pull request by ThomasdenH**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://cloud.google.com/storage/docs/how-to
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This adds the examples from the guide at https://cloud.google.com/storage/docs/how-to. It changes some declarations:

- Use `new Storage()` instead of `Storage()`. This might break existing code, but this is the only way it is used in the official documentation as far as I can tell.
- Add the undocumented property `storageClass` to the [`createBucket`](https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/Storage) options. This is used in one of the examples on the page. Although it is not documented, it is used internally and functions as expected. I have added the property, but once Google changes the example or documents it the types should follow their lead.
- Adds `component_count` to the file metadata. This is referenced in one of the examples, but I can't find the documented properties. I have added it with a note.

### CODE REVIEW

**Comment by nbperry** [comment]
@ThomasdenH Looks good, totally agree the types should follow the documentation as google updates their documentation. 

Did you happen to run these tests locally with your own GCP credentials?

**Comment by ThomasdenH** [comment]
I did, but without setting up the entire environment I only get irrelevant errors like 'Invalid Bucket name'.

**Review by nbperry — APPROVED** [review]
Looks good, i believe that the types will be coming to the actual packages managed by Google soon.
You can see the with [active work](https://github.com/googleapis/nodejs-storage/issues?utf8=%E2%9C%93&q=typescript+) being done to bring types into the package, with alot of work lately from @kinwa91.

**Comment by hiranya911** [comment]
This PR contains a breaking change. It should have been released as 2.0.0, as opposed to 1.7.1.

**Pull request merged**
