### PR TITLE
declare module with quotation marks

### PR DESCRIPTION
**Pull request by mbarzda**

### CODE REVIEW

**Comment by vvakame** [comment]
*nouislider/nouislider.d.ts*

to author(@bleuarg). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by bleuarg** [comment]
Doing it this way means it can't be used as a reference only no?

**Comment by mbarzda** [comment]
yes, it cannot be used like that

**Comment by bleuarg** [comment]
Can't say I agree, since noUiSlider creates a global object noUiSlider. And you can't load only parts of the plugin.

See *[Ambient Internal Modules](http://www.typescriptlang.org/Handbook#modules-optional-module-loading-and-other-advanced-loading-scenarios)* instead of *Ambient External Modules*.

**Comment by mbarzda** [comment]
I rewrote the declaration for both use cases.

**Comment by mhegazy** [comment]
@mbarzda is this still needed? can you update the PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
