### PR TITLE
[open-graph-scraper]: Update to 4.7 and add missing result values

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/jshemas/openGraphScraper/blob/e2432bb824590945de3d7936e5cdbf0204f14760/lib/fields.js
  - https://github.com/jshemas/openGraphScraper/blob/e2432bb824590945de3d7936e5cdbf0204f14760/CHANGELOG.md
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Taking over from #50579 since the author closed their PR.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## open-graph-scraper ([<kbd>unpkg</kbd>](https://unpkg.com/browse/open-graph-scraper@latest/))
was missing the following properties:
1. run
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5ca5bc31d0b2206068cc4c8ecf1f534401a3de5e
</p>

**Comment by ffflorian** [comment]
Maybe @jshemas would like to review this PR?

**Comment by orta** [comment]
👍🏻  looks good to me, and is primarily additive

**Comment by roseline124** [comment]
much better! thank you :)

**Pull request merged**
