### PR TITLE
[react-intl] fix type definitions for prop injection

### PR DESCRIPTION
**Pull request by gyzerok**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/yahoo/react-intl/wiki/API#injection-api
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by gyzerok** [comment]
Hello @cdroulers!

Sorry for bothering you. Can you tell me please what should be done for this to be merged? I definitely want this to become forever PR.

**Comment by gyzerok** [comment]
@sandersn can you help please?

**Comment by cdroulers** [comment]
👍

**Comment by bgrieder** [comment]
👍

**Comment by sandersn** [comment]
Sorry, we on the typescript team got very behind on merging definitely typed PRs. Thanks for your contribution!

**Comment by grovesNL** [comment]
What was the reason for the change from `InjectedIntlProps` to `InjectedIntl`?

**Comment by grovesNL** [comment]
Also please move the function signature back to `function injectIntl<T>(clazz: T): T;` as soon as possible. I will try to add a test for an example of a failing case but the current signature is not correct. I have many failing cases for `Property '...' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<{},ComponentState>> & {} & { children?:...'.` when using it regularly, which didn't happen with the previous signature.

@sandersn Could you revert the function signature at least? Dropping the `Props` suffix seemed to be pointless as well (i.e. I extend from this interface everywhere so I had to do a huge find/replace) but at least it's easier to fix.

**Comment by gyzerok** [comment]
@grovesNL why it is not correct? Take a look at the `react-intl` documentation link provided, please.

They no more mix translation methods with you props, but provide you one object-type prop which contains all of them. Thats why `Props` suffix were dropped. You can see exact same naming at `react-router` which have `InjectedRouter`.

The reason you have errors is because you do not wrap your components in `injectIntl`.

@sandersn that was my first one, so even though according to docs changes were right, I am not sure about if I updated version properly. Is [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12716/files#diff-6d554032c1e028829325b74c7e2452d9R1) enough? Should one who use types manage version compatibility by himself or I just missed something to be done?

**Comment by grovesNL** [comment]
My components requiring any of the `format{X}` functions are using `injectIntl` with react-intl 2.1.5. I was using the previous definition for months, but with the new signature there is something wrong with the intersection between the components regular ownProps and the props added by `injectIntl`.

The suffix I am not too concerned about because it is easily fixed, but I don't know how `@types` plans to notify users about breaking changes in minor version increments. In my case it wasn't noticed until CI started failing because the suffix had been dropped.

**Comment by gyzerok** [comment]
@grovesNL @sandersn I came up with a test case for newly introduced bug. If you have any ideas about how type signature for `injectIntl` should look like, please help. **Note:** previous type signature do not work with new API as well as the new one.

**Comment by grovesNL** [comment]
@gyzerok Thanks. I don't have time to look at this right now but the test case appears to correctly identify the bug. I would have a look at the signature of decorators in other packages.

In the meantime I think it would still be beneficial to revert this. I've locked my project to use the prior version, but it's likely that the majority of people using `injectIntl` will be impacted.

**Comment by gyzerok** [comment]
@grovesNL I made necessary updates and returned name back to `InjectedIntlProps`. So now we have test case which prevent this issue from happening again.

**Comment by grovesNL** [comment]
@gyzerok Looks good, I just tested the updated definition and it works well.

**Comment by gyzerok** [comment]
@pferdone but then you need to provide component with `intl` on the call site by yourself :)

**Comment by grovesNL** [comment]
@gyzerok: Actually I just noticed that with the updated definition I will have to remove everywhere I currently do `intl: InjectedIntlProps;` and make the component's props extend from `InjectedIntlProps` instead. That isn't too bad but it will still be a breaking change for people using `InjectedIntlProps` today in that way.

Maybe we can have both `InjectedIntlProps` (without the `intl` wrapper, so it can be referenced directly) and `InjectedIntl` (added in the decorator) by using an intersection?

**Comment by sandersn** [comment]
@gyzerok regarding versioning, you can rename the old version, for example, index.d.ts &rarr; react-int-2.0.0.ts

I still need to catch up on the rest of the discussion before I can help any more.

**Comment by sandersn** [comment]
I should preface this by saying that I don't know anything about react-intl specifically, so I'm just commenting about the types in the d.ts, plus the examples in the tests.

1. @grovesNL, the tests originally showed only the usage that `extends InjectedIntlProps` instead of having a property `intl: InjectIntl`. However, I take it that usage works in 2.x?
2. @gyzerok your updated 1-type-parameter version is better than the 2-type-parameter version because there's no way for typescript to infer the second type parameter &mdash; it doesn't try to infer type parameters for return types. So it's always going to be `TOwnProps={}` unless explicitly provided. And the preferred syntax for that is a type assertion: `injectIntl(something) as OwnProps`, not injectIntl<Original,Own>(something)`.
3. Does just having `InjectedIntl` plus `interface InjectedIntlProps { intl: InjectedIntl }` work? I don't understand what an intersection would look like or how it would be used.

**Comment by grovesNL** [comment]
@sandersn:

With regards to 1, yes, it looks as though the original tests were the wrong behavior for 2.x. It should have been referring to `this.props.intl.formatMessage` being injected. I've been using `interface MyProps { intl: InjectedIntlProps }` but it looks like that was never the intent (at least based on the test as you pointed out).

For 3, my point was that it may be useful if `interface MyProps { intl: InjectedIntlProps }` continued to work as well as the inheritance for `interface MyProps extends InjectedIntl { }`. Both would allow the component to resolve `this.props.intl.formatMessage`. The names could be swapped or altered, I just wonder if others are using the `intl: InjectedIntlProps` syntax today (as I was).

**Comment by gyzerok** [comment]
@sanders @grovesNL I'll try to describe what was wrong with previous type and how it should behave so you can probably help me to write better types.

Problem with previous implementation were optional functions in `InjectedIntlProps`.

```ts
interface InjectedIntlProps {
  formatDate?: (date: Date, options?: FormattedDate.PropsBase) => string;
  // ... other functions
}
```

The thing is - [they are not optional](https://github.com/yahoo/react-intl/wiki/API#injection-api).

### Ways to fix it

#### With inheritance

```ts
interface InjectedIntlProps {
  intl: {
    formatDate: (date: Date, options?: FormattedDate.PropsBase) => string;
    // ... other functions
  }
}

interface ReactComponentProps extends InjectedIntlProps {
}
```

The difference with the original implementation: functions are stored under `intl` field, functions are no more optional.

#### Without inheritance

```ts
interface InjectedIntl {
  formatDate: (date: Date, options?: FormattedDate.PropsBase) => string;
  // ... other functions
}

type ReactComponentProps = {
  intl: InjectedIntl
}
```

I am personally support idea of not using inheritance when it's unnecessary, so I decided to go that way. That's why I renamed `InjectedIntlProps` to `InjectedIntl` because it it no more "extending" for the props.

### The problem

In the following example I omit `intl` prop definition so you can add any of previously described ways.

```ts
class Example extends React.Component<{ className: string, intl: any }> {
  render() {
    return (
      <div>
        {this.props.intl.formatMessage(/* implementation details */)}
      </div>
    );
  }
}

const ExampleWithIntl: React.Component<{ className: string }> = injectIntl(Example);
// so you can use it like
<ExampleWithIntl className="hello" />
```

### The question

What should be type signature for `injectIntl`?

**Comment by grovesNL** [comment]
@gyzerok I'd prefer to support both with inheritance and without inheritance if possible (some other components are inconsistent about this).

**Comment by gyzerok** [comment]
@grovesNL thats a valid point. But still we need to figure out `injectIntl` signature first.

**Comment by grovesNL** [comment]
@gyzerok The `injectIntl` signature appears to work for the cases I noticed, I'm not sure if there are any other cases that were missed

**Comment by pferdone** [comment]
@gyzerok Why don't you just leave it at:

`function injectIntl<T>(component: React.ComponentClass<T> | React.StatelessComponent<T>): React.ComponentClass<T>`

I don't get the problem!?!

**Comment by gyzerok** [comment]
When you use decorated component you don't have to provide it with `intl` property, because `injectIntl` should pass it for you. Take a closer look in [types in "The problem" section](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12716#issuecomment-262824571).

**Comment by pferdone** [comment]
But that's how it always worked:

```javascript
interface IMyCompProps {
  intl: InjectedIntlProps;
}

class MyComp extends React.Component<IMyCompProps, void> {
  render() {
    return (<div>{ this.props.intl.formatMessage({ id: 'whatever' }) }</div>);
  }
}

const decoratedMyComp = injectIntl(MyComp);
```

`MyComp` doesn't *know* it's been decorated. That's how everything from react-router to react-redux works.

**Comment by gyzerok** [comment]
@pferdone put this code in the file, render `MyComp` and run type check.

**Comment by gyzerok** [comment]
@grovesNL @pferdone @T-Wolff @sandersn 

It looks like I finally figured out what should be correct types [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12906). I am really sorry for breaking the thing. Please check it and lets continue discussion there. Really interested to get it merged asap :)

**Comment by grovesNL** [comment]
@gyzerok: Thanks, I'll test it soon.

**Pull request merged**
