### PR TITLE
Collection.add signature fix

### PR DESCRIPTION
**Pull request by pafflique**
http://backbonejs.org/#Collection-add - "Returns the added (or preexisting, if duplicate) models."

### CODE REVIEW

**Comment by vvakame** [comment]
*backbone/backbone.d.ts*

to authors(@borisyankov @nvivo). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by nvivo** [comment]
Hi @vvakame, I can't check this definition anymore since it was modified to a point it won't compile in my projects anymore. I suggest looking for other people to check or simply accepting the change and see if anybody complains.

**Comment by vvakame** [comment]
@nvivo okey.
@omidkrad could you review this PR?

**Comment by omidkrad** [comment]
Looking at the Backbone [implementation](http://backbonejs.org/docs/backbone.html#section-107), this looks correct. :+1:

**Comment by vvakame** [comment]
@omidkrad thanks!
@pafflique thanks mate!

**Pull request merged**
