### PR TITLE
fix(nodejs): add missing options in http.Agent

### PR DESCRIPTION
**Pull request by bodinsamuel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
-  https://nodejs.org/api/http.html#http_new_agent_options
- NodeJS v1.14.0
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by bodinsamuel** [comment]
Failing test seems unrelated

**Review by Flarna — APPROVED** [review]

**Review by j-oliveras — APPROVED** [review]

**Comment by panva** [comment]
> Failing test seems unrelated

Same in #47561

**Comment by bodinsamuel** [comment]
Hey @sandersn I can not ask for a rereview, but it's ready. Failing test are unrelated, can you provide some help? ☺️

**Review by a-tarasyuk — APPROVED** [review]

**Comment by Ryan-Willpower** [comment]
> Hey @sandersn I can not ask for a rereview, but it's ready. Failing test are unrelated, can you provide some help? ☺️

The failing test can be unrelate to the PR. If the owner approved, then it's OK.

**Comment by sandersn** [comment]
master was in a bad state during the last CI run. @bodinsamuel if you merge from master you should get a clean run.

**Review by Flarna — APPROVED** [review]

**Review by j-oliveras — APPROVED** [review]

**Pull request merged**
