### PR TITLE
react-intl - modify Values definition to support element instead of just string

### PR DESCRIPTION
**Pull request by willietu-arcurve**
Add back support to output message with elements. Not sure if JSX.Element suffice as Object was used before. Please add back the support.

### CODE REVIEW

**Comment by LKay** [comment]
Looks like this was forgotten in the last update. I'm good to mare the change.

**Comment by gyzerok** [comment]
Where is the link to docs? Have you tested it with your code? Where is issue template filled?

I doubt this work the same wayfor InjectedIntl.

:-1:

**Comment by LKay** [comment]
@gyzerok Actually it applies to `FormattedMessage` component https://github.com/yahoo/react-intl/wiki/Components#formattedmessage (rich formatting paragraph). But it seems `formatMessage` function could accept strings. Maybe it's better to make a generic of this type or use different types for component and function?

**Comment by gyzerok** [comment]
@LKay I guess it would be better other way around. Instead of creating something even more generic it would be nicer to just inline type and make it specific for each case. By doing it this way we will avoid creating unnecessary abstractions.

Anyway, the guy totally violated PR rules and I don't think we should accept this PR. Would be nice if you can create proper one instead :)

**Comment by willietu-arcurve** [comment]
Sorry, I did not realize I was in violation of PR rules. My apologies. Please consider adding back JSX.Element support to FormattedMessage for values parameters

**Comment by jgke** [comment]
This was redone in pull #15686.

**Review by gyzerok — CHANGES_REQUESTED** [review]
This PR is declined and should be closed.

**Comment by willietu-arcurve** [comment]
Closing pull request as it is addressed in #15686

**Pull request closed without merging**
