### PR TITLE
Improved puppeteer typings

### PR DESCRIPTION
**Pull request by ikeyan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Can you please describe what you changed? It's very hard to look at individual changes here.

**Comment by ikeyan** [comment]
@SimonSchick These are changes that are hard to see
* improved Serializable type
** allow `undefined`, `void` and `bigint` only as top level, not in an object or an array
*** `bigint` required TS version 3.2
* `pageFunction` of `Page.evaluate` and others gets narrower type
** the types of `...args` params of `pageFunction` are inferred from `...args` of `evaluate`
*** `JSHandle`s are unwrapped
** if the return type of `pageFunction` is `Promise<T>`, it gets unwrapped so the return type of `evaluate` is `Promise<T>`, not `Promise<Promise<T>>`
** `evaluateHandle` returns `ElementHandle` if `pageFunction` returns `Element`
* stopped `$eval` and `$$eval` from wrapping `Element` return type with `ElementHandle` because they actually doesn't

**Comment by andrewbranch** [comment]
I’m not going to be able to do anything with this one (large change, popular package) without an owner approval. @ikeyan thanks for your patience with the holidays.

**Comment by armanio123** [comment]
Just a friendly ping to the owners for review. Thanks.
@adierkens @JoshuaKGoldberg @tkrotoff @marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita @JasonKaz @davecardwell @angrykoala @mtsmfm @Yama-Tomo

**Comment by cdeutsch** [comment]
@ikeyan it'd probably be easier to review and get things merged as smaller, separate, PR's. 

I'd recommend grouping related changes, and in places where there are radical changes elaborate in the PR description the rationale. 

Looks like there are some good changes in here, but it's a lot to evaluate all at once, and merging it all at the same time will increase the likely hood of breaking existing code bases.

**Comment by felixfbecker** [comment]
This change would be _much_ appreciated, so much manual, unsafe typing is currently needed

**Comment by felixfbecker** [comment]
I honestly find the PR very easy to review if you look at it commit-by-commit. Maybe the reviewers could see if that makes it easier for them? :)

**Pull request closed without merging**
