### PR TITLE
export videojs.Player so it can be augmented with declaration merging

### PR DESCRIPTION
**Pull request by joeflateau**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Potential solution to #37032

### CODE REVIEW

**Comment by joeflateau** [comment]
Here's an example of an augmentation possible after this PR

```typescript
import { VideoJsPlayer, VideoJsPlayerOptions } from 'video.js';

declare module 'video.js' {
  export interface VideoJsPlayer {
    ima(options: VideoJsImaOptions): this;
  }
  export interface VideoJsPlayerOptions {
    ima?: VideoJsImaOptions;
  }
  export interface VideoJsImaOptions {
    adTagUrl: string;
  }
}
```

**Comment by joeflateau** [comment]
rebased this PR onto DT/master since my other merged PR introduced a merge conflict

**Comment by sandersn** [comment]
@vbortone @scleriot @SWBennett06 @IgelCampus @giofreitas @gjanblaszczyk @sroucheray @AkxeOne @meikidd This is a pretty big change. Mind reviewing it?

**Comment by sandersn** [comment]
I don't think this is possible without changing the way that things are exported. Can you add tests to prove that the change works?

Specifically, `export default` doesn't seem to work with module augmentation. You could switch everything to just be global, but that makes it unusable from node.

**Review by sandersn — CHANGES_REQUESTED** [review]
Need tests to prove that the change works.

**Comment by joeflateau** [comment]
@sandersn sorry for the delay here, been on vacation unplugged. Incoming revision w/ tests. Although I'm not 100% sure this is the proper way it should be done within the larger DT repo (I don't want to accidentally ship the example augmentation along with the actual videojs definition)

**Comment by sandersn** [comment]
Since none of the authors have commented, and the tests show that the change works, I'll go ahead and merge. @joeflateau, can you follow up with two things:

1. Watch the DT issues for the next week or so to make sure nobody else gets broken by this.
2. Add yourself as an author in a follow-up PR so that future changes will ping you for review and your future PRs will be fast-tracked. (If you have time to look at PRs to video.js, at least.)

Thanks for your persistence on this one.

**Review by sandersn — APPROVED** [review]

**Comment by joeflateau** [comment]
Sounds good @sandersn, I'll do those.

**Pull request merged**
