### PR TITLE
Add team drives apis to google.picker types

### PR DESCRIPTION
**Pull request by mattlewis92**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: I can't find these api's documented on the google docs but the methods do definitely do exist at runtime
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by grapswiz — APPROVED** [review]

**Comment by mattlewis92** [comment]
Ready to merge

**Comment by chivesrs** [comment]
They deprecated team drive in favor of shared drive. Please mark as `@deprecated`.

@mattlewis92

**Comment by mattlewis92** [comment]
> They deprecated team drive in favor of shared drive. Please mark as `@deprecated`.
> 
> @mattlewis92

Ah that explains why it's not in the docs anymore. Is the migration as straight forward as `SUPPORT_TEAM_DRIVES` -> `SUPPORT_DRIVES` and `setEnableTeamDrives` -> `setEnableDrives`?

**Comment by chivesrs** [comment]
Should be.

**Comment by mattlewis92** [comment]
@chivesrs Done! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54303

**Pull request merged**
