### PR TITLE
add type argument to React.ComponentType to react-select

### PR DESCRIPTION
**Pull request by xhawk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://flow.org/en/docs/react/types/#toc-react-componenttype>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by devrelm** [comment]
Can you add some tests for this? Also, the flow link looks about right, but 1) this is a TypeScript type declaration file first, and I am unfamiliar with weather the types described on that site match the types provided in the React types in this repo, and 2) please provide a link to the react-less docs/code that states that these props are passed to those components.

**Comment by xhawk** [comment]
Sorry, totally wrong link :D

1) URL: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L75>
2) https://github.com/JedWatson/react-select/blob/master/src/Select.js lines 1106 & 1120

About tests: I think that it is a very good test when your code doesn't compile. And isn't that why typed languages invented for? What do you think? :) If absolutely must I can of course write few...

**Comment by devrelm** [comment]
@xhawk yes, I was thinking that tests should be added to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/react-select-tests.tsx.

It works how you suggested: it makes sure that everything still compiles.

**Review by devrelm — CHANGES_REQUESTED** [review]
@xhawk Those lines in the Select.js link are just the general react PropTypes, and don't contain information about what props they take.

The actual lines stating which props get passed to the `optionComponent` component are here:

https://github.com/JedWatson/react-select/blob/57ab8d02f4db9d2b08cf9fabc124240114ca380d/src/utils/defaultMenuRenderer.js#L31-L43

and to the `valueComponent` component are here:

https://github.com/JedWatson/react-select/blob/57ab8d02f4db9d2b08cf9fabc124240114ca380d/src/Select.js#L712-L720

You can see the PropTypes for the default `Option` component here:

https://github.com/JedWatson/react-select/blob/57ab8d02f4db9d2b08cf9fabc124240114ca380d/src/Option.js#L99-L111

and the PropTypes for the default `Value` component here:

https://github.com/JedWatson/react-select/blob/57ab8d02f4db9d2b08cf9fabc124240114ca380d/src/Value.js#L97-L104

**Comment by devrelm** [comment]
It looks like you'll have to create a couple new prop types. I suggest `OptionProps` and `ValueProps` to be consistent. You can start by taking the existing `Option.propTypes` and `Value.propTypes`, turning them into interfaces, and replacing the types with TypeScript types.

So,

```js
Value.propTypes = {
    children: PropTypes.node,
    disabled: PropTypes.bool,               // disabled prop passed to ReactSelect
    id: PropTypes.string,                   // Unique id for the value - used for aria
    onClick: PropTypes.func,                // method to handle click on value label
    onRemove: PropTypes.func,               // method to handle removal of the value
    value: PropTypes.object.isRequired,     // the option object for this value
};
```

could become

```ts
interface ValueProps {
    disabled?: boolean,
    id?: string,
    onClick?: (value: Option<TValue>, event: React.SyntheticEvent<HTMLAnchorElement>) => void,
    onRemove?: (value: Option<TValue>) => void,
    value: Option<TValue>,
};
```

Note that you don't need to define `children`, as that's already added by the `react` typings. Also, all props except `value` are optional.

You can do the same process for the `OptionProps`.

**Comment by RyanCavanaugh** [comment]
@xhawk Please address comments from the code reviewers.

**Comment by minestarks** [comment]
@devrelm thanks for the detailed review,  @xhawk could you please address the feedback and make the requested revisions? If no more activity on this PR, I'll need to close it due to staleness.

**Review by minestarks — CHANGES_REQUESTED** [review]
please add at least one test that would fail without your change to demonstrate why the change is needed.

**Comment by minestarks** [comment]
I'm closing this PR due to lack of activity. If you would still like to get in these changes, please open a new PR. Thank you!

**Pull request closed without merging**
