### PR TITLE
[bitcoinjs-lib] Add regtest network constant

### PR DESCRIPTION
**Pull request by D4nte**
Added to the library with bitcoinjs/bitcoinjs-lib#1261

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1261
- [x] Increase the version number in the header if appropriate: **Not needed**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`: **Not needed**

### CODE REVIEW

**Review by youssefgh — APPROVED** [review]
Perfect, thank you

**Comment by D4nte** [comment]
Any chance it could get merged please?

**Comment by youssefgh** [comment]
A maintainer should merge it once he's available
Expect at most the end of the week

**Comment by junderw** [comment]
Hi, I am one of the maintainers of bitcoinjs-lib.

We will be moving to TypeScript with auto-generated type definitions moving forward, and I am currently working on a TypeScript rewrite here: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1319

I would appreciate your advice / expertise. Any Pull Requests to the typeScript branch are appreciated.

Currently using prettier for formatting, tslint for linting, and we will commit the transpiled JS files so that it is easy to verify them through a normal git diff.

Thanks in advanced!

@D4nte @youssefgh

**Comment by youssefgh** [comment]
Perfect, I'll check the TypeScript implementation
Thank you for letting us know

**Pull request merged**
