### PR TITLE
Fixing get() result for `ssh2-sftp-client`

### PR DESCRIPTION
**Pull request by daviduzumeri**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.npmjs.com/package/ssh2-sftp-client#getpath-dst-options--stringstreambuffer>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by daviduzumeri** [comment]
I suspect this is the result of an accidental copy/paste in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42135 where the `dst` parameter was updated but so was the return result accidentally. It makes no sense for a `get()` method to return a `WritableStream`.

**Review by ascariandrea — APPROVED** [review]

**Comment by sgalizia** [comment]
> 
> 
> I suspect this is the result of an accidental copy/paste in #42135 where the `dst` parameter was updated but so was the return result accidentally. It makes no sense for a `get()` method to return a `WritableStream`.

This was not an accident. Why would the destination be a readable stream if you are trying to stream information from a Readable under the hood. The documentation for this function shows the usage of a Writable. Please check the ssh2-sftp-client documentation. I also linked that in my previous PR fixing this issue.

**Review by Olyve — CHANGES_REQUESTED** [review]
this should remain Writable

**Comment by daviduzumeri** [comment]
My bad, I’ll take the L on this.

**Comment by daviduzumeri** [comment]
@sgalizia Want to apologize -- you're absolutely 100% right and I'm absolutely 100% wrong. Thanks for catching this.

**Comment by sgalizia** [comment]
No worries! @daviduzumeri :)

**Pull request closed without merging**
