### PR TITLE
Add Feather icons to react-native-vector-icons

### PR DESCRIPTION
**Pull request by levibotelho**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/oblador/react-native-vector-icons
- [X] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by iRoachie — APPROVED** [review]

**Review by timwangdev — CHANGES_REQUESTED** [review]
Please add `Feather.ts` to `tsconfig.json` files section

**Comment by levibotelho** [comment]
@timwangdev will do this evening. Thanks for the tip.

**Review by iRoachie — CHANGES_REQUESTED** [review]
Need to rename the file extension from Feather.ts to Feather.d.ts

**Review by timwangdev — APPROVED** [review]

**Comment by levibotelho** [comment]
Argh, typo, sorry about that.

**Review by iRoachie — APPROVED** [review]

**Pull request merged**
