### PR TITLE
[node] imported and global process are same

### PR DESCRIPTION
**Pull request by TonyPythoneer**
Based on #10846 and #10810. It enhances test for **process**.

---

The Purpose of Tests:
- **process** module is able to be imported
- The imported **process** and global **process** are same.

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
Hi, @vvakame
Please review it. thx.

**Comment by vvakame** [comment]
hi. test is not running in this project. compiled by tsc only.

I think we should use this pattern.
```
var _p: NodeJS.Process = process;
_p = p;
```
What do you think?

**Comment by TonyPythoneer** [comment]
Do you mean it declares a `_p` variable with `NodeJS.Process` type, global `process` set to `_p`, it's compatible with `_p`? Next, imported `process` set to `_p`, it's in order to test compatibility of type?

**Comment by TonyPythoneer** [comment]
Close. This branch has confilcts. Please refer the new PR: #11092.

**Pull request closed without merging**
