### PR TITLE
[google.script.client-size] Made public endpoints more easily customizable

### PR DESCRIPTION
**Pull request by marekdedic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR does not change or update any functionality, rather, it makes it easier for the typings users to override parts of the typings with their own, narrower type checks.

### CODE REVIEW

**Comment by marekdedic** [comment]
The failing CI seems to me to have nothing to do with the actual changes.

**Review by ghost — APPROVED** [review]
Great improvement!

**Comment by marekdedic** [comment]
@peterblazejewicz Sorry to bother you but the CI seems to be broken (I don't see how the warnings are related to any of the changes in this PR and it fails with only warnings and no errors....) and you have previously looked at my PR related to GAS...

Could you please take a look and let me know if there is any action required on my side?

**Comment by clomie** [comment]
CI seems to be broken so I've posted to the Definitely Typed channel on the TypeScript discord community server about this.

**Comment by marekdedic** [comment]
@clomie I tried merging from master, it didn't fix the issue, but reset your approval... Could you please approve the PR again?

**Comment by orta** [comment]
I'll manually merge this as it had prior 👍🏻s 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51067 will turn the md linter to only fail on errors which would have un-blocked this PR post-rebase

**Comment by marekdedic** [comment]
Thanks!

**Comment by marekdedic** [comment]
Since I have you here, @clomie, what do you thing about renaming this package? It isn't really clear what it relates to...

There is `@types/google-apps-script`, so this would probably be better if it were called `@types/google-apps-script.client-side` or something like that...

Or maybe it could be merged into `@types/google-apps-script`?

**Comment by clomie** [comment]
@marekdedic 
hmm... When I named this package I thought the name should contains its global namespace as like some of other google's non-npm packages.
But indeed it isn't clear what it relates to as you say. `@types/google-apps-script.client-side` sounds a great idea.

OK, I will try to find how to rename this package.
Probably the action needed is not just to rename the directory.

By the way, About merging into `@types/google-apps-script`, I think it can't be.
This package is used as a front-end module and would be generally used this with lib.dom.d.ts.
@types/google-apps-script` has the `console` variable type definition in its own module and it would conflict with lib.dom.d.ts.

**Comment by marekdedic** [comment]
Hi,
thanks for that. Renaming the directory is not enough I think, as you'd want the NPM package to be renamed, not just open a new one.

As for the correct name, I'm not sure, maybe the contributor docs have some guidance...

Didn't think about libraries when talking about merging with `@types/google-apps-script`, you're absolutely right that that'd be a problem.

**Pull request merged**
