### PR TITLE
getEvent should not be set to void it should return a value

### PR DESCRIPTION
**Pull request by abbasmhd**
getEvent was set to void and clearly the documentation says that is should returns the event object by its id
-  `getEvent(event_id: string | number): void;`

has been changed  to return a strongly typed object 
-  `getEvent<T>(event_id: string | number): T;`

other methods changed to return a strongly typed object  includes
1.     `getActionData<T>(e: Event): T;`
2.    `getEvent<T>(event_id: string | number): T;`
3.    `getEvents<T>(from?: Date, to?: Date): T[];`
4.    `getLabel<T>(property: string, key: string | number): T;`
5.    `getRecDates<T>(id: string, number: number): T[];`

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery.pnotify/jquery.pnotify.d.ts*

to author (@DavidSichau). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by andy-ms** [comment]
If these methods don't reliably return `T` they should just be declared to return `any`, just like `JSON.parse()` does. See my comment: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10558#issuecomment-248414472.

**Comment by abbasmhd** [comment]
if you think that method do not reliably return `T` you can always use `any` and cast the return value

    `var event = getEvent<any>(5) as IEvent;`
    or
    `var event = <IEvent> getEvent<any>(5);`

**Comment by andy-ms** [comment]
Our guideline is to not use a type parameter that doesn't have some corresponding function parameter.
A function like `function identify<T>(x: T): T` benefits from a type parameter because the output type is a function of the input type.
In contrast, in `JSON.parse<T>(s: string): T`, `T` appears nowhere in the input, thus it is not really a parametrically polymorphic function, just a type assertion disguised to look type-safe.

So, our style is to use `JSON.parse('{"x": 1, "y": 2}') as {x: number, y: number}`.
If you want to avoid `any` you could always return `{}`.

**Comment by abbasmhd** [comment]
@andy-ms i have changed all functions to return `any` 

1. `getEvent(event_id: string | number): any;`
2. `getActionData(e: Event): any;`
3. `getEvent(event_id: string | number): any;`
4. `getEvents(from?: Date, to?: Date): any;`
5. `getLabel(property: string, key: string | number): any;`
6. `getRecDates(id: string, number: number): any;`

**Comment by andy-ms** [comment]
Thanks.
In the "Files changed" tab I'm currently seeing a large number of whitespace changes. The lines you edited have been changed to uses 4 spaces for indentation, while the rest of the file still uses tabs. Could you undo these indentation changes? (The other whitespace changes are OK.)

**Comment by abbasmhd** [comment]
the file been changes to use tabs

**Pull request merged**
