### PR TITLE
Update definitions for inboxsdk

### PR DESCRIPTION
**Pull request by Antoine38660**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.inboxsdk.com/docs/#Global
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Antoine38660** [comment]
`Conversations. ContentPanelView` as a `close()` function but not documented.

Should I let it?

**Comment by amiram** [comment]
Hi @Antoine38660 . Thank you for the fix with the promise. As for the undocumented method, I suggest a comment should be added about it. There is no guarantee it will always work.

**Comment by amiram** [comment]
Isn't the close method the undocumented one?

**Comment by Antoine38660** [comment]
My bad..

**Review by amiram — APPROVED** [review]

**Pull request merged**
