### PR TITLE
xstyled__system: Fix ResponsiveValue type to allow Object or Arrays

### PR DESCRIPTION
**Pull request by Yofamb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

https://xstyled.dev/

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## xstyled__system ([<kbd>unpkg</kbd>](https://unpkg.com/browse/xstyled__system@latest/))
was missing the following properties:
1. createStyleGenerator
1. getBreakpoints
1. reduceBreakpoints
1. themeGetter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5b45e52a5b8d86121dac5fd0f06492fb9fea6059
</p>

**Review by stevejay — COMMENTED** [review]
Hi! I believe that xstyled system does not support the array syntax for responsive values. The documentation [here](https://xstyled.dev/docs/responsive/) does not include array syntax. I also checked using [this Codesandbox](https://codesandbox.io/s/nostalgic-goodall-k9410?file=/src/App.js). As you can see, only the object syntax works.

**Review by stevejay — CHANGES_REQUESTED** [review]
Marking as 'Request changes' because of array support issue.

**Comment by Yofamb** [comment]
I've emailed the creator of xStyled to hopefully get clarification, I'm wondering if it is just his documentation that is lacking. As you can see here, the array syntax works if you use the array syntax in the theme.

https://codesandbox.io/s/interesting-cdn-wil4r?file=/src/App.js

Our preference for the component library we are building is using arrays for the breakpoints but as we are using typescript ran into the issue. I'm not too experienced with typescript but I guess a short term solution would be for us to copy the types locally for the time being until we get clarification from the owner.

Let me know what you think, thanks for coming up with the types, they've been super helpful!

**Comment by stevejay** [comment]
@Yofamb Ah, interesting; thanks for the info. Array indexes also seem to work with the breakpoint utils, e.g., `up`.

One thing I was wondering about the changed definition:
```
export type ResponsiveValue<T> = T | ObjectOrArray<T>;
```
I was wondering if it should be specified as the following less lenient version without the recursiveness of ObjectOrArray: 
```
export type ResponsiveValue<T> = T | T[] | { [key: string]: T };
```
The changed definition means that code like the following pass validation, which doesn't seem correct:
```
<Space m={{ sm: [1, 'sm'], md: 'sm' }} />
```

**Comment by Yofamb** [comment]
I'd definitely take your guidance here, I'm heading to bed now but will take a look in the morning. I just received a response from the creator and he mentioned that he is working on a typescript version of xstyled which will be ready soon, however he didn't answer my questions regarding the syntax/documentation.

**Review by stevejay — APPROVED** [review]
LGTM

**Comment by Yofamb** [comment]
Ready to merge

**Pull request merged**
