### PR TITLE
Update JQueryUI ButtonOptions interface

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vvakame** [comment]
*jqueryui/jqueryui.d.ts*

to authors(@borisyankov @johnnyreilly). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@errorx666 please fix travis ci failed.

**Comment by johnnyreilly** [comment]
Happy to review once fixed

**Comment by errorx666** [comment]
@vvakame @johnnyreilly Travis CI fixed and unit test added

**Comment by borisyankov** [comment]
Looks good.

**Pull request merged**
