### PR TITLE
Angular ui router fixes

### PR DESCRIPTION
**Pull request by baltie**
Added missing definitions and fixed some others in angular-ui-router.

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-ui-router/angular-ui-router.d.ts*

to author(@michelsalib). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by baltie** [comment]
Well, seeing that this hit the back burner, I decided to be a good citizen and add some missing tests. Hopefully this will make this PR more acceptable. :)

I hope someone can have a look sometime soon. Thanks. :)

**Comment by michelsalib** [comment]
sorry for being late. This is a :+1:

**Comment by baltie** [comment]
Thanks! :)

**Comment by vvakame** [comment]
@michelsalib thanks!
@baltie thanks mate!

**Comment by baltie** [comment]
@vvakame Thanks!

**Pull request merged**
