### PR TITLE
Update the types for node-cache 

### PR DESCRIPTION
**Pull request by seungdols**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/node-cache/node-cache/pull/144/files>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by dthunell** [comment]
I have not been using this library for over a year so I cannot validate the changes made, but it seems it now packages it's own TS definitions so should it not be removed from this repo then to avoid confusion/conflict?

**Comment by seungdols** [comment]
cc. @daluf Excuse me first. I changed the fix regarding the type of node-cache, what is your opinion?

@dthunell Thank you for your good feedback. I think that First of all, you should ask the node-cache maintainer for opinion.

**Comment by erdii** [comment]
Hey @seungdols!
Thanks for your contribution.

I think it would be better to "self-host" the typings inside the project itself because:
* instant "type-script-like" experience for JS developers who use vscode
* no need to do an extraneous "npm install -D @types/node-cache"
* easier to maintain

---

Would you be willing to provide this pull-request against our main repo https://github.com/node-cache/node-cache ?

---

I think we also should add a stub definition here? Something like:

```
> npm i -D @types/moment

npm WARN deprecated @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
```

**Comment by seungdols** [comment]
Thank you for your advice @erdii.

I was thinking that the types of node-cache exist in `@ types` already.

So, I updated @types for node-cache in `@ types` because of updating of node-cache is very important to me.

You said it to me, Why should the type of node cache be maintained? When I was thinking, it was the conclusion that you were right. I agree with you.

It doesn’t need to keep types of node-cache in @types. I suggest you one. **Should can I removed out `types / node-cache` in this repository.** What are you think?

I unaccustomed to open-source contribute So, I hope you understand.

Thank you.

**Comment by andrewbranch** [comment]
It sounds like node-cache should be removed from DefinitelyTyped here. @seungdols, if you’re willing to make the removal, please see [this section of the README](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) for instructions. Thanks all!

**Review by andrewbranch — CHANGES_REQUESTED** [review]
_[Tracking the removal of this package]_

**Pull request closed without merging**
