### PR TITLE
Add definitions for redux-localstorage and main enhancers

### PR DESCRIPTION
**Pull request by LKay**
Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

### CODE REVIEW

**Comment by andy-ms** [comment]
You checked the `Prefer to make your PR against the types-2.0 branch.` box, but this is still targeted for `master`.

**Comment by LKay** [comment]
@andy-ms You're right, my bad. Must have checked that accidentally.

**Comment by paulvanbrenk** [comment]
@andy-ms should we merge this, or do we strongly prefer new typings to go into 2.0.

**Comment by andy-ms** [comment]
I guess we can merge it, then make a types-2.0 PR. It will be tricky because I recently removed `redux` from DT (#12965), so it needs a package.json:

```json
{
  "dependencies": {
    "redux": "^3.6.0"
  }
}
```

**Pull request merged**
