### PR TITLE
Add definitions for jsbn.BigInteger from @types/node-forge

### PR DESCRIPTION
**Pull request by dhensby**
The node-forge library includes a copy of JSBN BigInteger (sepearately typed here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsbn/index.d.ts). At the moment thedefinition is quite incomplete for the node-forge BigInteger class, so I've copied these over.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/digitalbazaar/forge/blob/master/lib/jsbn.js#L61-L67
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by joeflateau** [comment]
@dhensby I'm not sure it's appropriate to make a copy of jsbn types here, wouldn't it be better to import jsbn's types as a dependency?

**Comment by dhensby** [comment]
I thought about that, but then we have no control over changes to that library and its typings or future changes that could occur. Although I accept that is unlikely, it's not right to pull in some other library's typings just because your internal code happens to match that of another lib. Or, more possible, if some internal change happens to forge's jsbn definition and so then this imported typing now needs to be copied and modified anyway.

My view is this is code defined in node-forge, so the typings should be defined likewise. If jsbn was a first-class dependency, then it would be different, but it's not - it's a copy/paste of another library that others have also decided to publish standalone.

**Comment by joeflateau** [comment]
I think you're right, forge does not use the jsbn package as a dependency but a subset copy of it, so types should also be a subset copy as well.

**Review by joeflateau — APPROVED** [review]

**Comment by dhensby** [comment]
Ready to merge

**Pull request merged**
