### PR TITLE
Add onFailure prop to react-facebook-login

### PR DESCRIPTION
**Pull request by bramschulting**
This prop was missing:
https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L39

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L39
~~- [ ] Increase the version number in the header if appropriate.~~ 
~~- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by jankarres** [comment]
Approve

**Comment by bramschulting** [comment]
@jankarres Thanks for the approve! But I think you need to use the Approve feature for the bot to understand it. So if you have an chance to do that, that would be great!

**Comment by jankarres** [comment]
Thanks for the advice, @bramschulting. Maybe a dumb question, but where can I find this button? CMD + F did not guide me to the button: D

**Comment by bramschulting** [comment]
If you click `Files changed` tab, you'll find it a the top right:

github approve

(it's a really fast gif, sorry 😛)

**Review by jankarres — APPROVED** [review]

**Comment by jankarres** [comment]
Awesome, thanks for the great explanation!

**Pull request merged**
