### PR TITLE
[chromecast-caf-receiver] Revert back to previous namespace export

### PR DESCRIPTION
**Pull request by Beunard**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by orta** [comment]
Without a PR description, I'm afraid as a DT maintainer I can't sign this off either way

**Comment by marcoreni** [comment]
According to git logs this was introduced by @Serabe in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55215/files#diff-2a483b90b5292d257f89c7ad1139e57cf1bdf80895512a51307ce6bb4882d5e7 , maybe he can provide some insights.

**Comment by Serabe** [comment]
That's the fix I came up with so we could work in our codebase with cast.framework and cast.debug while keeping imports for types.

I guess we would need some context on why they need switching back to previous.

**Comment by marcoreni** [comment]
According to git logs this was introduced by Serabe in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49255/files#diff-2a483b90b5292d257f89c7ad1139e57cf1bdf80895512a51307ce6bb4882d5e7 , maybe he can provide some insights?

(sorry, messed up with the comments)

**Comment by Beunard** [comment]
Hi @orta, @Serabe, @marcoreni, 

Since [Serabe's commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49255/commits/62ec439d722de00fae1e4102417436f78b372b1e), the cast namespace is not available globally as it used to be. 

The reason we would like to revert to the previous export is that we have hundreds of references to `cast` in our codebase, and it's currently not possible to update the DefinitelyTyped `chromecast-caf-receiver` package without modifying dozens of files. 
Furthermore, as the `chromecast-caf-receiver` library lives in the global scope, it makes more sense for the namespace to be available globally.

**Comment by Serabe** [comment]
@Beunard strange. The first two lines of the test file is accessing the `cast` namespace globally https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chromecast-caf-receiver/chromecast-caf-receiver-tests.ts#L15-L16

**Comment by elibarzilay** [comment]
@Beunard: ping re the comments?

**Comment by andrewbranch** [comment]
Closing due to lack of author response, combined with the fact that I verified `cast` is globally accessible.

**Pull request closed without merging**
