### PR TITLE
Node: `querystring`: allow nullish values in input type

### PR DESCRIPTION
**Pull request by OliverJAsh**
Forgot to include these in #41014

### CODE REVIEW

**Review by islishude — APPROVED** [review]

**Review by galkin — CHANGES_REQUESTED** [review]
Could you also add node.js v10 definition?

**Comment by OliverJAsh** [comment]
@galkin See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41014#issuecomment-565390875

**Review by galkin — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by orta** [comment]
Looks good to me, thanks

**Comment by LongYC** [comment]
Seems like this issue has resurfaced in @types/node@12.12.22 due to: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40927/files#diff-8ccf0f501903c02ff7afcca4a1472f51R14

**Comment by SimonSchick** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40927#issuecomment-568529327

**Comment by OliverJAsh** [comment]
Should I raise a PR to re-apply these changes to the `v12` folder?

**Comment by SimonSchick** [comment]
Feel free to.

**Comment by OliverJAsh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41366

**Pull request merged**
