### PR TITLE
update: react-native-push-notification 7.2.2

### PR DESCRIPTION
**Pull request by rucheton**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by rucheton** [comment]
Hi there! Could you spare a little bit of time to merge or reject this? Thanks in advance! @PaitoAnderson @tomSawkins @Li357

**Comment by PaitoAnderson** [comment]
@rucheton I'll take a look right now.

**Review by PaitoAnderson — APPROVED** [review]
LGTM

**Comment by rucheton** [comment]
Ready to merge

**Comment by Li357** [comment]
Not a huge deal, but there seem to be some differences in the types for `userInfo`. In `ReceivedNotification`:

https://github.com/rucheton/DefinitelyTyped/blob/945053b880889f14066004a6efb6d77142ff6eaa/types/react-native-push-notification/index.d.ts#L21

versus in `PushNotificationDeliveredObject` for this PR

https://github.com/rucheton/DefinitelyTyped/blob/945053b880889f14066004a6efb6d77142ff6eaa/types/react-native-push-notification/index.d.ts#L106

versus `PushNotificationObject`,

https://github.com/rucheton/DefinitelyTyped/blob/945053b880889f14066004a6efb6d77142ff6eaa/types/react-native-push-notification/index.d.ts#L86

and the corresponding `data` properties. I just wanted to check, is this a difference in how the bridge between native code serializes the `userInfo`?

**Comment by PaitoAnderson** [comment]
@Li357 I'm sorry, not sure how the `userInfo` field is supposed to work. :(

**Comment by rucheton** [comment]
Thanks for pointing this out @Li357 ! I'll have a deeper look into it and will try to type the write way :)

**Pull request merged**
