### PR TITLE
[parse] Add better support for TS 3.7

### LINKED ISSUE #42258: @types/parse  Type alias 'Encode' circularly references itself. Type 'Encode' is not generic.
If you know how to fix the issue, make a pull request instead.

- [ X ] I tried using the `@types/parse` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@ullisenmedia

@dpoetzsch 
 @jaeggerr 
@flavionegrao
 @wesleygrimes @owsas @agoldis @AlexandreHetu @dplewis @yomybaby @pocketcolin @rdhelms @jlnquere @yagotome @tybi @RaschidJFR @JeffGuKang @buitanloc @LinusU 

Update parse types just now seems to be issues related to Encode 

```
 node_modules/@types/parse/index.d.ts(501,14): error TS2456: Type alias 'Encode' circularly references itself.
[0] node_modules/@types/parse/index.d.ts(511,41): error TS2315: Type 'Encode' is not generic.
[0] node_modules/@types/parse/index.d.ts(518,29): error TS2315: Type 'Encode' is not generic.
```

### PR DESCRIPTION
**Pull request by rdhelms**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <http://parseplatform.org/Parse-SDK-JS/api/2.10.0/>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

-----

This fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42258 by explicitly supporting both TS >=3.7 and TS <3.7.

### CODE REVIEW

**Comment by rdhelms** [comment]
@RaschidJFR @REPTILEHAUS Any thoughts on this?

**Comment by RaschidJFR** [comment]
Sorry for my late reply @rdhelms . Thanks for that contribution. Looks promising, right now I've been too busy with work but I hope to get the change to get my hands on it to play around. Let's see what happens and how the community gets along with it.
Cheers.

**Comment by REPTILEHAUS** [comment]
@RaschidJFR Hi Raschid, sorry for contacting here but I got a notification from this PR.

Is it possible for me to leave this project as I get a lot of notification on updates etc every single day.

I only contributed 1 PR but I don't wish to be an active contributor or maintainer.

**Comment by rdhelms** [comment]
@REPTILEHAUS As far as I know, your getting notifications is due to having your username in the comment [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parse/index.d.ts#L22)

So I believe the solution would be to remove your name from the comment.

Also, you may have additionally been notified because I tagged you due to your having created [the issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42258) that led to this PR. Apologies for pulling you in unexpectedly!

**Comment by RaschidJFR** [comment]
@REPTILEHAUS you need to remove your name from index.d.ts files and submit a new PR.

**Pull request merged**
