### PR TITLE
Properly version FHIR

### PR DESCRIPTION
**Pull request by bkaney**
This is the first step toward proerply versioned types for FHIR 3 and FHIR 4. See the conversation in this thread: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49574

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jhuenges** [comment]
@bkaney Thanks for your efforts to updating the FHIR types! I recently updated these [FHIR types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c22d2540433f451b9057cac9f77d7bac902c5aa5/types/fhir/index.d.ts) to be more closely aligned to the STU3 specification. I am not 100% sure if everything is correct, but if you would like some help here, just ping me here.

**Comment by bkaney** [comment]
@jhuenges  - Thanks, that link seems to have been merged, and was about using gender-neutral pronouns in the comment sections? Do you have a public git repo with your changes?

The more I think about this, perhaps we should make a different types package per major FHIR release. This way anyone could propose patches to types that are independent of the FHIR version. For example:

* Current @types/fhir is STU3
* Create a new @types/fhir4 for R4
* (future) Create a new @types/fhir5 for R5
* (optional) remove/rename @types/fhir to @types/fhir3

@yinzara or @zeevosec, any thoughts?

**Comment by jhuenges** [comment]
@bkaney I only linked the FHIR types that you added the version for in this PR. Not sure which commit you mean. 

The changes I made are not in a public repo right now, but I could open a PR against this repo if you like (or add them to a Gist). The changes are mainly about specifying the correct codes that are only typed as `string` right now. For example, the code for [`use` in the Address](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fhir/index.d.ts#L90) should be `home | work | temp | old` ([source](http://hl7.org/fhir/STU3/datatypes.html#Address)).

**Comment by zeevosec** [comment]
> ... or @zeevosec, any thoughts?
I like this naming convention. The only other idea I would consider would be to have @typed/fhir point to the latest FHIR release -- And update this everytime FHIR does a new release -- so new developers will automatically be encouraged to use FHIR 4/5 and not accidentally get stuck in DSTU2 or STU3.  But I actually think explicitly versioning it might be better.

**Pull request merged**
