### PR TITLE
Remove duplicated `as` in React. It's failing in nightly

### PR DESCRIPTION
**Pull request by pocesar**
remove duplicated `as`

image

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by adostal** [comment]
This pull request is important. Build React projects with Typescript is broken.
Please do it as soon as possible.

**Comment by rhysd** [comment]
I'm also facing the same problem with the latest versioin of `@types/react` as following.

```
> tsc --pretty -p .


2785         as?: string;
             ~~

node_modules/@types/react/index.d.ts(2785,9): error TS2300: Duplicate identifier 'as'.


2793         as?: string;
             ~~

node_modules/@types/react/index.d.ts(2793,9): error TS2300: Duplicate identifier 'as'.

```

This PR should fix the error.

**Comment by johnnyreilly** [comment]
Merged as the new jsdoc rules seem to be causing unrelated failures.

**Comment by dsifford** [comment]
Can somebody push this out to npm?

**Comment by johnnyreilly** [comment]
It's an automated process - it should happen in the next 24 hours or so. For now I'd just pin to an earlier version cc @andy-ms

**Pull request merged**
