### PR TITLE
Remove node-fetch - not needed as of 3.0.0

### LINKED ISSUE #1259: V3 followup: update DefinitelyTyped
Add this to DefinitelyTyped/DefinitelyTyped/master/notNeededPackages.json PR since we now ship the typings ourself.

### PR DESCRIPTION
**Pull request by ImRodry**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [X] Delete the package's directory.
- [X] Add it to `notNeededPackages.json`.

Closes https://github.com/node-fetch/node-fetch/issues/1259

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I"m not sure if simple replacement to v3 as direct dependency if the best approach. It can install dependency and types in a verson which was not tested nor used with original package. Take `file-fetch` as example, this package depends on v2 of node-fetch, not v3. If there are dendencies, one can also use `@types/node-fetch@..` (last known version on DT), instead of allowing silent dependency changes. @ImRodry

**Comment by peterblazejewicz** [comment]
what do you mean by 'tested'? I'd say this when run transpiled native JS. Sorry I'm over-cautious, as I have recently to fix DT package detail due to impact done on native JS code usage in the wild. I'd avoid doing major version bump, unless we've got approvals from all owners for each involved DT package

**Comment by ImRodry** [comment]
> what do you mean by 'tested'? I'd say this when run transpiled native JS. Sorry I'm over-cautious, as I have recently to fix DT package detail due to impact done on native JS code usage in the wild. I'd avoid doing major version bump, unless we've got approvals from all owners for each involved DT package

The node-fetch package was mostly copied over from here with the 2 ~~stupid~~ changes they noted in their changelog. I understand your concerns though and will lower them all down to `@types/node-fetch` just to be sure, but I believe it wouldn't make much of a difference

**Comment by ImRodry** [comment]
@peterblazejewicz addressed your concerns, let me know if it's all good now!

**Comment by southpolesteve** [comment]
I'd like to hear to one of the DT team to understand this change better and the impact . Plenty of libraries and projects still depend on node-fetch v2 and these types. Wouldn't it make more sense to release a major version of @types/node-fetch and mark these types as deprecated on NPM? I am sure this is not the first @types library that got superseded by the actual library deciding to include types.

**Comment by ImRodry** [comment]
> I'd like to hear to one of the DT team to understand this change better and the impact . Plenty of libraries and projects still depend on node-fetch v2 and these types. Wouldn't it make more sense to release a major version of @types/node-fetch and mark these types as deprecated on NPM? I am sure this is not the first @types library that got superseded by the actual library deciding to include types.

That is exactly what this PR is doing. It will release `@types/node-fetch` v3.0.0 as deprecated and all the packages that depend on it will use the current version. I've done this for mongodb and it has also been done for mongoose which was another critical package. I'll try to find the PR and link it here

**Comment by nicolas377** [comment]
I'll update libnpmpublish myself, but we shouldn't be deleting node-fetch's types just yet, just deprecating the package and giving a window of backwards compatibility before deleting the types package

**Comment by ImRodry** [comment]
@nicolas377 the node-fetch devs said they would only be providing bug fixes to v2 of the package so we will not need to update any types anymore so there’s no reason not to delete. Of course people will always be able to install the types package with a deprecation warning since that’s how deleting packages works here

**Comment by peterblazejewicz** [comment]
@nicolas377 @southpolesteve 
- when we accept this PR, a final entry for current DTis to be created on the NPM registry, marking beginning of new types resolution (if someone is using automatic types resolution feature or say, defaults by VS/VSCode).
- for v2 that will be still v2 of types, nothing is to be changed (@types/node-fetch@2)
- for v3, automatic resolution should be to native JS package now
- only source code of this definitions will be removed from this repository
- this only means updates for v2 of @types/... (e.g. fixing definition problems) will be possible no more (I expect native package is not releasing any major/minor changes for v2 already)

@ImRodry thank you! Yes, this should be best approach I think

> I'd like to hear to one of the DT team to understand this change better and the impact . Plenty of libraries and projects still depend on node-fetch v2 and these types. Wouldn't it make more sense to release a major version of @types/node-fetch and mark these types as deprecated on NPM? I am sure this is not the first @types library that got superseded by the actual library deciding to include types.

Adding @orta and @sandersn

**Review by orta — APPROVED** [review]
Confirming that this is the usual setup when a project starts shipping it's own types, glad to see it happen - it's one of the few tools I regularly need to remember to grab @types for!

**Comment by ImRodry** [comment]
Ready to merge

**Comment by nikcorg** [comment]
Bye bye @types/node-fetch 👋

I enjoyed being part of the maintainers crew. However, I won't shed a tear at your departure.

**Comment by trygve-aaberge-adsk** [comment]
`node-fetch` is still releasing 2.x versions (2.6.7 was released 12 days ago) which don't have types, so I don't think this should have been deleted.

**Comment by tpluscode** [comment]
The `@types/node-fetch@2` packages still exist. Do they require any changes?

**Comment by trygve-aaberge-adsk** [comment]
Oh, the 2.5.12 version of `@types/node-fetch` actually includes the type changes that was introduced in node-fetch 2.6.0, that was a bit confusing.

E.g. setting `options.agent` to a function was added in node-fetch 2.6.0: https://github.com/node-fetch/node-fetch/pull/632, but it was added to the types here without bumping the version: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36057 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36152

**Comment by tpluscode** [comment]
Yes, the `@types/*` packages are independently versioned. Typically the major matches but there are multiple projects which are version 1, 2 or 3 and the types are still `0.0.x`. I also found this a little confusing at first but think of it this way: package major version indicates breaking changes in functionality. Types major version indicates breaking changes in JS API. The two are not the same thing

**Comment by trygve-aaberge-adsk** [comment]
But I thought at least the version comment in the type file should match the package version? [The last version of these types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39c90291062b269d2c4f19ca7d65369c210696aa/types/node-fetch/index.d.ts#L1) still had it set to 2.5. How are you supposed to know that these types are not compatible if you use node-fetch 2.5?

**Comment by trygve-aaberge-adsk** [comment]
Though, I guess this is really more related to the change being made without bumping the version number than the types being deleted.

**Comment by nikcorg** [comment]
You're right, the version number in the comment not being updated will have been an oversight.

**Comment by glasser** [comment]
Would it be reasonable to add these back? node-fetch is a very popular library, and they made the choice in v3 to only publish the package as an ESM module, so anyone in a build system that doesn't support ESM (or who is publishing an npm package depending on `node-fetch` that they'd like folks using non-ESM build systems to be able to consume) is likely to be stuck on v2 for quite a while.

I'd specifically love one improvement. The `Request.agent` field is passed through directly to Node's `http.request` function as the `agent` argument there. `boolean` is a valid type for this option in Node `http.request` but the `node-fetch` types don't allow it.  (Passing `agent: false` is different from `agent: undefined`; the former means to automatically create an Agent that isn't shared with any other request, whereas the latter means to use the default global shared agent.) Ordinarily I'd send a PR to add that one change to the DefinitelyTyped package but since it's been deleted, I can't.

**Comment by tpluscode** [comment]
I think you should be asking on https://github.com/node-fetch/node-fetch

This repository only manages typ declarations for versions <3

**Comment by glasser** [comment]
Yes, that's my point exactly: we are unable to upgrade to v3 so would like to be able to improve the v2 types, which were in this repo only but have been removed.

**Comment by nikcorg** [comment]
I would suggest opening a PR with your proposed changes might be the quickest way forward. It might garner more attention than discussion on an already merged PR. But this is merely speculation on my part. Or at least maybe explicitly mention some of the admins to highlight the issue in their notifications.

Other paths of higher resistance might be to switch clients, as native [Fetch API just landed in Node.js](https://news.ycombinator.com/item?id=30161626). The implementation is at https://github.com/nodejs/undici/

**Comment by sandersn** [comment]
From a DT maintainer: sounds like re-adding the node-fetch@2 types is the right way to go. Remember to remove node-fetch from notNeededPackages.json in the DT root.

I didn't quite get all the back-and-forth about 2.5 vs 2.6, but *typically* the major.minor matches the source package's major.minor, and DT uses the patch version as an incrementing counter for each change to the types.  If the DT types are for node-fetch@2.6, I'd recommend publishing them as `@types/node-fetch@2.6`.

**Comment by glasser** [comment]
@sandersn Sounds reasonable! I have the start of a "revert this PR and also make the `agent` fix I want" PR together; I'll file it once upstream merges https://github.com/node-fetch/node-fetch/pull/1502 so it's clear that the second commit matches what the v3 types will be to. I'll try to update the version to v2.6.0 too.

**Comment by glasser** [comment]
(I assume I should be fully reverting this PR including all the things that add explicit dependencies on `@types/node-fetch@2` to other packages in the repo? Or are those still good?)

**Comment by peterblazejewicz** [comment]
I"d say only for package that depends on 'node-fetch@2'. This is also sometimes loosely implemented on DT, so take precautions

**Comment by glasser** [comment]
@peterblazejewicz Sorry I'm not sure if I follow. Should I remove the explicit dependencies on `@types/node-fetch` added to various packages in this PR when I revert, or should I leave them in place?

**Comment by glasser** [comment]
Thanks, I filed #58693. I did not understand @peterblazejewicz 's comment so I hope it meant that I should revert the dependency changes from this PR.

**Pull request merged**
