### PR TITLE
AngularJS: Fix the signature for angular.bootstrap

### PR DESCRIPTION
**Pull request by thorn0**
see https://code.angularjs.org/1.4.0/docs/api/ng/function/angular.bootstrap

### CODE REVIEW

**Comment by vvakame** [comment]
thanks mate!

**Comment by use-strict** [comment]
PR breaks this signature ```bootstrap(element: Document, ...): auto.IInjectorService;```.

E.g.:
```typescript
angular.element(document).ready(() => {
    angular.bootstrap(document, [appName]);
});
```

**Comment by thorn0** [comment]
There is no such signature in the docs, but OK, I'll submit another PR to bring it back.

**Comment by use-strict** [comment]
It's not the first time angular docs were not 100% accurate, but the code doesn't lie:
https://github.com/angular/angular.js/blob/v1.4.7/src/Angular.js#L1564

It accepts anything that can be wrapped with jQuery lite. Oddly enough, the JQueryStatic definition types this case as ```(object: {}): JQuery```. Same goes for jqLite.

**Comment by thorn0** [comment]
I don't think it makes sense to add `{}` there.

**Comment by use-strict** [comment]
I have no idea why it's typed like that in jQuery for that matter.

**Comment by thorn0** [comment]
Because you indeed can wrap any object in a jQuery, but again, it doesn't make sense for `bootstrap`. Can you merge #6164 please?

**Pull request merged**
