### PR TITLE
feat: add methods to shippo

### PR DESCRIPTION
**Pull request by clalexander**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://goshippo.com/docs/reference https://github.com/goshippo/shippo-node-client
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## shippo ([<kbd>unpkg</kbd>](https://unpkg.com/browse/shippo@latest/))
was missing the following properties:
1. AUTH_SCHEME_SHIPPO
1. AUTH_SCHEME_OAUTH
1. DEFAULT_HOST
1. DEFAULT_PROTOCOL
1. DEFAULT_PORT

<details>
<summary>as well as these 8 other properties...</summary>
<p>DEFAULT_AUTH_SCHEME, DEFAULT_BASE_PATH, DEFAULT_TIMEOUT, PACKAGE_VERSION, USER_AGENT, resources, Error, Resource</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 93e0d681037bf3bab51cb1c06b61058bae966d30
</p>

**Review by jlismore — APPROVED** [review]
lgtm

**Comment by clalexander** [comment]
Need to make one more update to the `ShipmentExtras` type to add more properties then we'll be ready.  Thanks all

**Comment by clalexander** [comment]
Updated `ShipmentExtras`

**Review by jlismore — APPROVED** [review]

**Comment by clalexander** [comment]
Ready to merge

**Pull request merged**
