### PR TITLE
Added the new 8.0 AutoComplete Features.  

### PR DESCRIPTION
**Pull request by daryllabar**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Since AutoComplete features are in 8.0 only and beyond, created 7.1 versions of Xrm.d.ts and tests.ts based on previous version.

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by daryllabar** [comment]
Ping! @vvakame No response from author.

**Comment by andy-ms** [comment]
This looks good but needs to be made merge-able.

**Comment by daryllabar** [comment]
Fixed Merge Issue

**Pull request merged**
