### PR TITLE
fix(UpdateCodeowners): move to ts and fix import

### PR DESCRIPTION
**Pull request by ImRodry**
Since #59750 the update codeowners script hasn't worked so I've gone ahead and fixed it and also updated the file to .ts and moved the type definitions to actual TS type definitions and removed the JSDocs. Also if you wish I can push the commit that updates the codeowners file in this PR, otherwise, please run it once this is merged

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by andrewbranch** [comment]
Thank you! But merge conflicts?

FWIW, I like the script in JS with JSDoc. I needed to debug a lot as I was writing it, so removing an intermediate compile step (not to mention not having to worry about source maps) is a plus. I’d rather keep these kinds of things in JS.

**Comment by ImRodry** [comment]
Alright I’ll be sure to revert it back to JS and fix the merge conflicts when I can!

**Comment by ImRodry** [comment]
Actually seems like #60664 did the same thing this PR would do except with the TS transition. @andrewbranch if you wanna keep this in JS then I guess this should be closed right?

**Comment by andrewbranch** [comment]
Yeah, looks like it, thank you anyway @ImRodry!

**Pull request closed without merging**
