### PR TITLE
Update styled-components definition to fix rexport merging

### LINKED ISSUE #28629: [@types/styled-components] ThemedStyledComponentsModule from documentation does not compile
@Igorbek @probablyup originally posted this in styled-components/styled-components#1959 and was told to post here.

Implementing example from docs (small change to avoid multiple imports from same module):

```
import * as styledComponents from 'styled-components'
import { ThemeInterface } from 'types'

const {
  default: styled,
  injectGlobal,
  keyframes,
  ThemeProvider,
  withTheme,
  css
} = styledComponents as styledComponents.ThemedStyledComponentsModule<ThemeInterface>

export { injectGlobal, keyframes, ThemeProvider, withTheme, css }
export default styled
```

Results in compilation error:
`This assertion is unnecessary since it does not change the type of the expression.`

I can confirm that the type of the individual methods is changing.  

E.g. the type for 'css' changes from:
`StyledComponents.ThemedCssFunction<Any>`

To:
`StyledComponents.ThemedCssFunction<ThemeInterface>`

Styled-Components Version: `3.4.2`
Typescript Version: `3.0.1`

### PR DESCRIPTION
**Pull request by lifeiscontent**
Closes #28629

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
There's still some declarations not merging correctly. Something related to prop types.

**Comment by elibarzilay** [comment]
Looks like no endorsements for an important package?

**Comment by lifeiscontent** [comment]
@elibarzilay i tried updating it but I'm a bit lost on the propType issue. Was hoping someone could chime in/help.

**Comment by elibarzilay** [comment]
Maybe start a [discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions] instead?

**Comment by lifeiscontent** [comment]
@elibarzilay done: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54550

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Please add a test

**Pull request closed without merging**
