### PR TITLE
update(carbon-components-react) Added React.node for modal btns

### PR DESCRIPTION
**Pull request by sgregoire**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.carbondesignsystem.com/components/modal/usage#loading>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## carbon-components-react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/carbon-components-react@latest/))
was missing the following properties:
1. Grid
1. Row
1. Column
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1e5b155a7c9900e5cac65519039c24479e722e28
</p>

**Review by kalbert312 — APPROVED** [review]

**Comment by sgregoire** [comment]
Waiting for this to be merged: carbon-design-system/carbon#6105

**Review by kalbert312 — APPROVED** [review]

**Comment by elibarzilay** [comment]
This pr got old and had merge conflicts -- I've fixed & rebased it.
@kalbert312 @matchilling: please re-review if this is still good.
@sgregoire: see above how to merge it when it's ready.

**Comment by sgregoire** [comment]
All good, it has been merged and latest version has this change inside !

**Pull request merged**
