### PR TITLE
Fix Croppie definition

### LINKED ISSUE #21928: @types/croppie @types to library inconsistency
HI @andy-ms, @sarunint, @dklmuc 

I tried using the `@types/croppie` I get the following issue at runtime

Uncaught TypeError: croppie_1.default is not a constructor.

**Import:** 
import  Croppie from "croppie";

**Usage:**
this.croppie = new Croppie(this.avatarImage,
                {
                    viewport: { width: 256, height: 256, type: this.viewPortType },
                    boundary: { width: 410, height: 410 },
                    showZoomer: true,
                });

In order to get around this problem I used the following.

**Import:** 
import * as Croppie from "croppie";

**Usage:**
this.croppie = new Croppie.Croppie(this.avatarImage,
                {
                    viewport: { width: 256, height: 256, type: this.viewPortType },
                    boundary: { width: 410, height: 410 },
                    showZoomer: true,
                });

This works fine at runtime but i get the following error during typescript compilation phase

error TS2339: Property 'Croppie' does not exist on type 'typeof ".../node_modules/@types/croppie/index"'.
[14:31:25] gulp-notify: [Error running Gulp] Error: ...\avatar-modal.ts(43,40): error TS2339: Property 'Croppie' does not exist on type 'typeof ".../node_modules/@types/croppie/index"'.

### PR DESCRIPTION
**Pull request by sarunint**
This will work after Foliotek/Croppie#532 got included into a release.

Close #21928

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Foliotek/Croppie/commit/8dc634af8189a134269b074b883ddb78ee3b190d
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by connor4312 — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
This still doesn't look like an `export.default` to me, so I don't know why you want to define it as such. If you're running this with Webpack in mind, you should use `allowSyntheticDefaultImports` and keep the current format the same.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
The package still doesn't look like a default export to me, so I don't know why you want to define it as such. Specifically, it's not authored as an ES Module to begin with.

If you're running this with Webpack in mind, you should use `allowSyntheticDefaultImports` and keep the current format the same. That way you can import that with `import Croppie from "croppie"`

**Comment by DanielRosenwasser** [comment]
I think this PR should probably be closed unless I've misunderstood something.

**Comment by sarunint** [comment]
Hi @DanielRosenwasser,

Sorry for the late reply, I've been busy lately.

As I stated in the PR, this will need to wait until Foliotek/Croppie#352 be included into a release. As of now, there isn't a release yet.

**Comment by DanielRosenwasser** [comment]
Sure, and I can keep an eye on my notifications, but it's going to be difficult for us to stay on top of this PR. I will try, but it might be easier if you reopen/open another PR off of this branch when that actually occurs.

**Comment by sarunint** [comment]
Shall I create a new PR or reopen this PR when that occurs? @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
We'd probably prefer a new PR for whoever is reviewing DefinitelyTyped that week

**Pull request closed without merging**
