### PR TITLE
[Redux Mock Store] - Copy over deprecation notice

### PR DESCRIPTION
**Pull request by EskiMojo14**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reduxjs/redux-mock-store/releases/tag/v1.5.5
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/redux-mock-store/index.d.ts
1. types/redux-mock-store/redux-mock-store-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a6290efc98c122f2c4e576a78fbd2e8f4765026a
</p>

**Review by jakebailey — CHANGES_REQUESTED** [review]
Please bump `package.json` to 1.5; it's still set to 1.0: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/82fac32cc0a7afff5c9a8b823b9a5e32ac4d225e/types/redux-mock-store/package.json#L4

**Comment by EskiMojo14** [comment]
@jakebailey understood, thanks for the feedback - i was under the impression ony the major version needed to match.

To confirm, I should bump to 1.5.0?

**Comment by EskiMojo14** [comment]
Updated, apologies for missing it before :)

**Review by jakebailey — APPROVED** [review]

**Comment by EskiMojo14** [comment]
Ready to merge

**Pull request merged**
