### PR TITLE
[node] construtor signature for "fs" 'ReadStream' and 'WriteStream' based on 'createReadStream' and 'createWriteStream'

### PR DESCRIPTION
**Pull request by n3okill**
Please fill in this template.

- [ X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X] Test the change in your own code. (Compile and run.)
- [ X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ X] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/nodejs/node/blob/983b757f3fe37c9c20f55d9b4575b2bbbc87bf1a/lib/internal/fs/streams.js#L148 
https://github.com/nodejs/node/blob/983b757f3fe37c9c20f55d9b4575b2bbbc87bf1a/lib/internal/fs/streams.js#L306
- [n/a] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Description:
 - Addition of constructor signature for class 'ReadStream'  and 'WriteStream' of package @types/node 'fs'  module based on 'createReadStream' and 'createWriteStream' definitions added by PR #54711
 - Tests were also added based on same PR

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Would be great if you could add this to the `v12` and `v14` folders as well 👍

**Comment by n3okill** [comment]
> 
> 
> @n3okill this looks legit, but should it be added to every LTS version hosted here? https://github.com/nodejs/node/blob/v12.22.7/lib/internal/fs/streams.js#L51

Hi, I believe so, because 'ReadStream' and 'WriteStream' definitions come from initial versions of node, by @LinusU request i've added definitions for v12 and v14 with corresponding tests and following the 'createReadStream' and 'createWriteStream' in the corresponding versions.

**Review by LinusU — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
yes, we actually reviewed similar problem, should constructors/classes be allowed:
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55400#discussioncomment-1241061
(I'd say align with public api, or how people are using, not with actual code type `completness`)

**Comment by SimonSchick** [comment]
To be clear, I've added stuff to the typings that are not strictly documented but mostly because the docs were rather vague in these instances and fell back to the impl, in cases where certain functions/methods/ctors are entirely omitted I've pretty much opted to omit them as they are not considered stable API.

**Comment by LinusU** [comment]
I think that the best would be to open an issue upstream with Node.js and ask wether the constructor is private or not, and ask them to clarify it in the documentation.

**Pull request closed without merging**
