### PR TITLE
rename lodash-tests-3.10.ts -> lodash-3.10-tests.ts

### PR DESCRIPTION
**Pull request by vvakame**
@chrootsu

### CODE REVIEW

**Comment by vvakame** [comment]
wow... lot of error occured...

**Comment by chrootsu** [comment]
I take a look now

**Comment by chrootsu** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8483

**Comment by vvakame** [comment]
thanks mate!

**Comment by chrootsu** [comment]
Hmm... This PR was closed without a merging?.. It seems like you haven't noticed that a PR with fixes of tests has been merged to this branch, not master. :wink:

**Comment by vvakame** [comment]
oh, thanks for your pointing.

**Comment by chrootsu** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8538 is adding of lost fixes.

**Comment by vvakame** [comment]
@chrootsu :+1: yeah!

**Comment by chrootsu** [comment]
@vvakame thanks mate! We did it. ^_^

**Pull request merged**
