### PR TITLE
Fix element-resize-detector options

### PR DESCRIPTION
**Pull request by iRON5**
Changes were done using source code from official [repo](https://github.com/wnr/element-resize-detector).

### CODE REVIEW

**Review by saranshkataria — CHANGES_REQUESTED** [review]
The changes that you have made have already been merged in #30501. But the commenting would be helpful for people to understand, so it would be great if you took the latest master commit and added those into it.

**Comment by saranshkataria** [comment]
@iRON5 from what I see, the warn function never takes the second argument. There are only two calls to it and both of them were messages only. Could you please check?

**Review by saranshkataria — CHANGES_REQUESTED** [review]
@iRON5 from what I see, the warn function never takes the second argument. There are only two calls to it and both of them were messages only. Could you please check?

**Comment by iRON5** [comment]
@saranshkataria as I see there is one place where `warn` get second argument
this line https://github.com/wnr/element-resize-detector/blob/master/dist/element-resize-detector.js#L323

**Comment by saranshkataria** [comment]
@iRON5 ah, I missed that. Changes look good then. Approving them.

**Review by saranshkataria — APPROVED** [review]

**Pull request merged**
