### PR TITLE
[arcgis-js-api] Add esri/styles/basic typings. (#9513)

### PR DESCRIPTION
**Pull request by hparkertt**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by bsvensson — COMMENTED** [review]
@hparkertt Thank you for your contribution. As these file are automatically created from our codebase for every release, and we wouldn't want this overwritten in the next release, so it's probably better if we run that instead of approving this pull request.

**Review by bsvensson — CHANGES_REQUESTED** [review]
We're planning to create a similar pull request that adds support for this and other things under esri/styles.

**Comment by hparkertt** [comment]
Thanks for the info, @bsvensson !  Is this something that will be updated in the 3.28 version, by the 3.29 version, or some other time in the future?

**Comment by dasa** [comment]
I've created a PR to update the 3.28 version at #35325

**Pull request closed without merging**
