### PR TITLE
estree: Object expressions may contain spread elements

### PR DESCRIPTION
**Pull request by larsrh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: object expression may contain spread elements, see https://github.com/estree/estree/blob/master/es2018.md

### CODE REVIEW

**Review by RReverser — APPROVED** [review]

**Review by RReverser — COMMENTED** [review]
Would it perhaps make sense to update `ObjectPattern` to include `RestElement` in the same PR?

**Comment by larsrh** [comment]
@RReverser Done!

**Comment by RReverser** [comment]
@larsrh Thanks! Can you update tests as well like you did for SpreadProperty?

**Comment by larsrh** [comment]
There were no tests for that, apparently (lint and test ran locally just fine, and apparently on Travis CI too)

**Comment by orta** [comment]
I'll call this as good to go, as that extra change feels safe

**Review by orta — APPROVED** [review]

**Pull request merged**
