### PR TITLE
Typings for pixi.js v4 and pixi-spine v1.3

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
@clark-stevenson 

@bluepichu @vvakame @bfanger

Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: 
https://pixijs.github.io/docs/
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by clark-stevenson** [comment]
👍  Cheers Ivan

**Comment by ivanpopelyshev** [comment]
oh come on! travis failed

**Comment by ivanpopelyshev** [comment]
@andy-ms Thank you, andy! The thing is, pixi.js isn't TS, while pixi-spine is. I will talk with others in pixi.js core team if we can bundle it in npm :)

**Comment by andy-ms** [comment]
You should still be able to bundle types if you add `@types/pixi.js` to your `package.json` dependencies.

FYI, noticed this in your `package.json`:

```json
"repository": {
    "type": "git",
    "pixi.js": "^3.0.9"
}
```

**Comment by ivanpopelyshev** [comment]
@andy-ms its ok, pixi-spine supports old versions too :)

**Comment by clark-stevenson** [comment]
Guys, is it possible for `npm install @types/pixi.js` to magically know that actually it lives here (if that repo adapts to fix naming conventions) `https://github.com/pixijs/pixi-typescript`

I guess it seems a bit redundant to have 2 files in the wild.

**Pull request merged**
