### PR TITLE
jQuery: bind with additional parameter

### PR DESCRIPTION
**Pull request by kalmertart**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/blueimp/jQuery-File-Upload/wiki/Options
Using using/jQuery-File-Upload is currently not possible, it gives compile errors because additional data is not defined

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
Thanks for your contribution! Please could you provide a test and a docs reference?

**Comment by johnnyreilly** [comment]
I'm looking here http://api.jquery.com/bind/ but I'm not seeing anything....

**Comment by kalmertart** [comment]
I couldn't find any documentation either from jQuery side and there probably aren't any. I believe it is caused by misuse of JS or jQuery. I tried to use blueimp/jQuery-File-Upload and as described in their documentation: https://github.com/blueimp/jQuery-File-Upload/wiki/Options - it does not send data back in JQueryEventObject. Therefor I thought it is not the only library that misuses it.
I could provide tests a bit later, I'm quite new to JS/TS, so it will took some time

**Comment by johnnyreilly** [comment]
I have a feeling this is not part of the API and so we probably wouldn't take a PR for this change. Sorry but we aim to be API compliant

**Pull request closed without merging**
