### PR TITLE
Add missing option `extendRefs`

### PR DESCRIPTION
**Pull request by domoritz**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

https://github.com/epoberezkin/ajv#referenced-schema-options

### CODE REVIEW

**Comment by plantain-00** [comment]
The document shows the type is `true | "ignore" | "fail"`, not boolean.

**Comment by domoritz** [comment]
@plantain-00 Yes, it does so for a bunch of other options as well. I can create a follow up pr but wanted to address one issue at a time.

**Comment by plantain-00** [comment]
It don't have to be in another pr, just update the type and push your commit, this pr will be updated too.

**Comment by domoritz** [comment]
@plantain-00 done

**Comment by plantain-00** [comment]
👍 thanks.

**Pull request merged**
