### PR TITLE
Urijs updates

### PR DESCRIPTION
**Pull request by xt0rted**
The first commit moves everything into a `uri` namespace. This is a breaking change but was done to mirror other libraries like [decimal.js](https://github.com/borisyankov/DefinitelyTyped/blob/575d70adcad0086ec8c6f672a5eb569a4689486c/decimal.js/decimal.js.d.ts) and [moment.js](https://github.com/borisyankov/DefinitelyTyped/blob/575d70adcad0086ec8c6f672a5eb569a4689486c/moment/moment.d.ts). I also wasn't sure how else to support the `URI('')` and `new URI('')` syntax that this allows for.

jquery support was moved into a new file since it's not required. If this doesn't make sense then I can move it back in.

The rest of the commits start to add missing functionality from newer versions. I can submit a new PR for these if they'd be better on their own.

### CODE REVIEW

**Comment by vvakame** [comment]
*urijs/URI.d.ts*

to authors(@RodneyJT). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*urijs/jquery.URI.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/urijs
  * http://bower.io/search/?q=urijs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (urijs/jquery.URI-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@xt0rted thank you for your contributions.
please rename urijs/jquery.URI.d.ts to URIjs/URIjs.d.ts.
https://www.npmjs.com/package/URIjs is exists.

**Comment by xt0rted** [comment]
@vvakame I got rid of the jquery file and renamed them to `URIjs` to match the npm package

**Comment by vvakame** [comment]
@xt0rted thanks mate!

**Comment by AlicanC** [comment]
Why was everything moved into a namespace? Am I supposed to do `type URI = uri.URI;` in every file now?

**Pull request merged**
