### PR TITLE
[office-js-preview] Add initial file set

### PR DESCRIPTION
**Pull request by AlexJerabek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
Looks good to me.

**Comment by SimonSchick** [comment]
82k lines seems a little... excessive.

**Comment by Zlatkovsky** [comment]
@SimonSchick , it's true, it does make for some fairly monotonous weekend reading, for a human.  But the good news is that it's mostly machine generated, and is for machine [intellisense/compiler] consumption -- so no human is meant to read it cover to cover.  And the way the internal processes that generate Office.js are, as well as the nature of the APIs (all under one interconnected namespace for each host), it is easiest to keep it all in one file.

In any case, the "office-js-preview" package is just a reflection of what's on the existing "office-js" package (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/office-js/index.d.ts), but just adding the "preview" APIs that are not included in the release version.  So they should match in structure.  We've not had any complaints about the former, so I think it should be fine for the preview package, too.

**Comment by AlexJerabek** [comment]
@SimonSchick +1 to what @Zlatkovsky said.

Additionally, much of the content in this definition file is documentation. We use [a series of open source tools[(https://github.com/Microsoft/web-build-tools) to generate our [reference doc set](https://docs.microsoft.com/en-us/javascript/api/overview/office).

**Pull request merged**
