### PR TITLE
Update the pixi.js definitions

### PR DESCRIPTION
**Pull request by bfanger**
I'd like to add the updated typescript definition for pixi.js.

It's based on [the work](https://github.com/pixijs/pixi-typescript) of @clark-stevenson ([with permission](https://github.com/pixijs/pixi-typescript/issues/14))
I've updated the definitions to match the [the contributing guide](http://definitelytyped.org/guides/contributing.html) (matching the package names to npm)

This pull request supersedes https://github.com/borisyankov/DefinitelyTyped/issues/3541 and https://github.com/borisyankov/DefinitelyTyped/issues/4497

### CODE REVIEW

**Comment by clark-stevenson** [comment]
Amazing mate, really appreciate it! :+1: :dancer:

**Comment by vvakame** [comment]
*pixi-spine/pixi-spine.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/pixi-spine
  * http://bower.io/search/?q=pixi-spine
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (pixi-spine/pixi-spine-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*pixi.js/pixi.js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/pixi.js
  * http://bower.io/search/?q=pixi.js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (pixi.js/pixi.js-tests.ts or others)
* [ ] pass the Travic-CI test?

---

*pixi/pixi.d.ts*

@xperiments can I merge this PR?

**Comment by clark-stevenson** [comment]
@vvakame  Why are we asking permission? The existing pixi.d.ts has been out of date for more than 2 years, and is 2 versions behind and even then, it was mostly wrong.

**Comment by vvakame** [comment]
okey, I decided to merge.
@bfanger thanks mate!

**Pull request merged**
