### PR TITLE
added types for chai-immutable

### PR DESCRIPTION
**Pull request by jsebrech**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

### CODE REVIEW

**Comment by vvakame** [comment]
sorry for late response.
could you merge master/HEAD into your branch?

**Comment by jsebrech** [comment]
It wasn't really clear to me what you're asking. I synced the upstream changes of the types-2.0 branch. Is this what was needed?

**Comment by andy-ms** [comment]
I think the problem is that you are targeting your PR to `master` but your branch is synced with `types-2.0`. GitHub shows a lot of other people's commits as being part of this PR. Please rebase the whole PR onto `master` so that only your change remains.

**Comment by mhegazy** [comment]
Please resubmit the change targeting master as the base branch.

**Pull request closed without merging**
