### PR TITLE
fix: Cannot find name 'object' for 'fs-extra' definition

### PR DESCRIPTION
**Pull request by bennycode**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alan-agius4** [comment]
You need typescript 2.2 or later to use this typings

**Comment by RyanCavanaugh** [comment]
>  Run npm run lint package-name

... and read the errors!

**Comment by bennyn** [comment]
I just wanted to help because the current typings of "fs-extra" are breaking our build: 
- https://travis-ci.org/wireapp/wire-webapp-cryptobox/builds/253240653#L512

**Comment by alan-agius4** [comment]
You might be using an older version of typescript, if you are using
gulp-typescript you'd need to pass the local typescript as by default it
will take the global.

**Comment by bennyn** [comment]
I was using TypeScript 2.1.4. Upgrading to TypeScript 2.4.1 solved the issue (thanks for the hint!). But shouldn't the definiton files also support older versions of TypeScript?

**Comment by alan-agius4** [comment]
Only if possible and not going against guidlines. Which in this case
'Object' is not a valid type as it totally different from 'object'

https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type

**Comment by bennyn** [comment]
Ok! Thanks for clarification! 👍

**Comment by RyanCavanaugh** [comment]
Use `npm install @types/fs-extra@ts2.1` to get the 2.1-compatible version of the file

**Pull request closed without merging**
