### PR TITLE
Definitions for react-intl 1.2.0

### PR DESCRIPTION
**Pull request by bgrieder**
Successfully tested with Typescript 1.6.2 and react-mixin 3.0.0
Note: tsconfig requires that the compiler option `experimentalDecorators` is set to `true` when using the mixin

### CODE REVIEW

**Comment by vvakame** [comment]
*react-intl/react-intl.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/react-intl
  * http://bower.io/search/?q=react-intl
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (react-intl/react-intl-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by bgrieder** [comment]
If I understand the way the Travis-CI test is set-up, this will **never** pass, because:

 - it depends on other modules
 - it uses decorators 

It does however compile fine with tsc 1.6.2 with dependencies and compiler flags correctly set.

**Comment by vvakame** [comment]
* add reference coment like this https://github.com/borisyankov/DefinitelyTyped/blob/master/react-dnd/react-dnd.d.ts#L6
* add tscparams like this https://github.com/borisyankov/DefinitelyTyped/blob/master/react-redux/react-redux-tests.tsx.tscparams

**Comment by bgrieder** [comment]
phew. My dev environment is now set-up the way Travis is. I guess this will help if I have to submit more definitions

**Comment by vvakame** [comment]
thanks mate

**Pull request merged**
