### PR TITLE
pg - Add Field interface definition

### PR DESCRIPTION
**Pull request by negcx**
The `QueryResult` definition currently does not define the `fields` array as a part of `QueryResult` and there is no definition for `Field` as an interface.

### CODE REVIEW

**Comment by minestarks** [comment]
@pspeter3 any feedback?

**Comment by pspeter3** [comment]
I would love a link to code or documentation for this. Runtime failures for this would be unfortunate.

**Comment by paulvanbrenk** [comment]
@negcx can you point to code or docs for this?

**Comment by andy-ms** [comment]
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

**Comment by negcx** [comment]
[https://github.com/brianc/node-postgres/blob/master/lib/connection.js](url) 498 - 526

`var Field = function() {
  this.name = null;
  this.tableID = null;
  this.columnID = null;
  this.dataTypeID = null;
  this.dataTypeSize = null;
  this.dataTypeModifier = null;
  this.format = null;
};

var FORMAT_TEXT = 'text';
var FORMAT_BINARY = 'binary';
Connection.prototype.parseField = function(buffer) {
  var field = new Field();
  field.name = this.parseCString(buffer);
  field.tableID = this.parseInt32(buffer);
  field.columnID = this.parseInt16(buffer);
  field.dataTypeID = this.parseInt32(buffer);
  field.dataTypeSize = this.parseInt16(buffer);
  field.dataTypeModifier = this.parseInt32(buffer);
  if(this.parseInt16(buffer) === TEXT_MODE) {
    this._mode = TEXT_MODE;
    field.format = FORMAT_TEXT;
  } else {
    this._mode = BINARY_MODE;
    field.format = FORMAT_BINARY;
  }
  return field;
};`

**Comment by RyanCavanaugh** [comment]
Please fix merge conflicts. Thanks!

**Comment by yuit** [comment]
Thanks for your contribution. This PR has merge conflict and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
