### PR TITLE
[node] Correct type of TransformCallback

### PR DESCRIPTION
**Pull request by Elrendio**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v8.x/api/stream.html#stream_transform_transform_chunk_encoding_callback
- [x] Increase the version number in the header if appropriate: Not appropriate
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`: Not substantial changes

Personal comments:
This change is to allow people to use the `@types/node/stream.d.ts` with the option `strictNullChecks` to true in their `tsconfig.json`

### CODE REVIEW

**Review by Steve-Fenton — APPROVED** [review]
> The first argument passed to the callback must be an Error object if an error occurred while processing the input or null otherwise

Thanks for the change - it matches the docs. There isn't an associated test change for this, which means it's not covered, but looking at the current test file - it doesn't go that deep (just checks types in this area).

**Review by BrunoScheufler — CHANGES_REQUESTED** [review]
From the docs:

> The first argument passed to the callback must be an Error object if an error occurred while processing the input or null otherwise...

Wouldn't you change the types of the first argument to be `Error | null` instead of being optional (`error?`) and if given `Error | null`?

**Comment by Elrendio** [comment]
Hey @BrunoScheufler many people extends the `Transform` class this way:
```TS
import { Transform, TransformCallback } from 'stream'

export default class MyTransform extends Transform {
	public _transform(chunk: string, _encoding: string, callback: TransformCallback) {
                // do some stuff
		callback()
	}
}
```

Changing the type from ```error?: Error | null``` to ```error: Error | null``` would certainly encourage good practices but introduce breaking changes.

**Comment by BrunoScheufler** [comment]
@Elrendio understood, I'll accept the changes in that case 👍

**Review by BrunoScheufler — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Pull request merged**
