### PR TITLE
Umbraco api typings

### LINKED ISSUE #5216: Create definition for Umbraco 7 api
Create definition for [Umbraco 7](http://umbraco.github.io/Belle/#/api) api.

Definitions:  

[umbraco.resources](http://umbraco.github.io/Belle/#/api/umbraco.resources)  
[umbraco.services](http://umbraco.github.io/Belle/#/api/umbraco.services)

### PR DESCRIPTION
**Pull request by matijagrcic**
Added definitions for [Umbraco 7](http://umbraco.github.io/Belle/#/api) api.

fixes #5216

### CODE REVIEW

**Comment by vvakame** [comment]
*umbraco/umbraco.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/umbraco
  * http://bower.io/search/?q=umbraco
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (umbraco/umbraco-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@matijagrcic thanks mate!

**Comment by matijagrcic** [comment]
@vvakame  Sweet! Thanks for merging. //cc @blawlor @mfentondsi

**Comment by mfentondsi** [comment]
I am out of the office until 17/08/2015.

For any Avon US related support queries please contact avondev@decaresystems.ie.


Note: This is an automated response to your message  "Re: [DefinitelyTyped]
Umbraco api typings (#5313)" sent on 14/08/2015 01:15:08.

This is the only notification you will receive while this person is away.
-- 
This e-mail and any files transmitted with it are intended solely for the 
individual or entity to whom they are addressed. 
This communication may contain material that is privileged, confidential 
and protected from disclosure under the law. 
If you are not the intended recipient, any disclosure, distribution, 
copying, or use of this information is strictly prohibited and may be 
unlawful.


If you have received this e-mail in error, please reply immediately to the 
sender and delete it.


Registered Address:
DeCare Systems Ireland Ltd, 
Building 1, 
University Technology Centre, 
Curraheen Road, 
Cork, 
Ireland. 
Company Registration Number: 278462

**Pull request merged**
