### PR TITLE
[WIP] Add type definitions for Leaflet 1.0

### PR DESCRIPTION
**Pull request by alejo90**
Addresses #10961 #11012.

This is still a work in progress. I'm posting it here since the API is huge and there may be people interested in starting to review it. Other sets of eyes are very welcome, since there may be typos, omissions, or errors in definitions. A lot is still missing, including tests and jsdoc.

API http://leafletjs.com/reference-1.0.0.html

case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by rgripper** [comment]
@dt-bot 👍 
@alejo90 That's a lot of work, thanks! I guess we wait for bug reports if something is broken :)

**Comment by jefbarn** [comment]
Picked up a bunch of regressions with this...
Error:(905, 22) TS2430: Interface 'Marker' incorrectly extends interface 'Layer'.
 Types of property 'bindTooltip' are incompatible.
 Type 'Function' is not assignable to type '{ (content: string, options?: TooltipOptions): this; (content: HTMLElement, options?: TooltipOpti...'.
 Type 'Function' provides no match for the signature '(content: string, options?: TooltipOptions): this'

Error:(54, 23) TS2305: Module 'L' has no exported member 'LayerGroup'.
Error:(56, 28) TS2339: Property 'layerGroup' does not exist on type 'typeof L'.

Error:(48, 13) TS2339: Property 'control' does not exist on type 'typeof L'.

**Comment by alejo90** [comment]
Thanks @jefbarn, I'll look into it this week.

**Comment by jefbarn** [comment]
here's my workaround stub:

```
declare namespace L {
  interface LayerGroup {
    addTo: Function
  }
  let layerGroup: Function
  namespace control {
    let zoom: Function
    let layers: Function
  }
}
```

**Comment by andy-ms** [comment]
Hi @jefbarn, since this is affecting people now could you make a PR implementing your stubs?

**Comment by alejo90** [comment]
@andy-ms, I've been a little bit busy this week, but I just opened #11445 with more definitions.

**Comment by jefbarn** [comment]
I also opened #11456 which appears to duplicate some of  #11445

**Comment by alejo90** [comment]
Thanks. Perhaps you could review #11445. The tests you added are very welcome.

**Pull request merged**
