### PR TITLE
jQuery split per environment

### PR DESCRIPTION
**Pull request by use-strict**
The GitHub diff isn't exactly showing the relevant changes, so here's exactly what I did.
- moved the `declare module` part into the `jquery-module.d.ts` file
- the main `jquery.d.ts` includes a `jquery-base.d.ts` part plus the module definition and global vars. This is for backwards compatibility.
- the `jquery-base.d.ts` is the old `jquery.d.ts` without the global declarations.

The point of this PR is to be able to use jQuery with a module loader without the `$` and `jQuery` globals.

### CODE REVIEW

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
Thanks for the contribution but I'm not really convinced that this provides a great deal of benefit.  I think I'd rather leave things as they are.

**Comment by use-strict** [comment]
@johnnyreilly , as it is the definition suffers from unwanted globals when used with npm in a node or webpack environment. I already made similar changes to other definitions because of this

This is a common case for team I work with and I would really like to have fixed:
```typescript
import $ = require('jquery');

jQuery('.something'); // <- should error with undeclared jQuery, but instead assumes the global.
```

Please reconsider this PR. It may not seem to be a great deal of benefit, but it doesn't hurt in any way. Everyone can still include `jquery.d.ts` as before without caring about this and who actually needs it in a no globals setup can benefit from it.

**Comment by use-strict** [comment]
@vvakame , @johnnyreilly , I just had to fix a run time error because someone in my team forgot to add an `import $ ...` and the compiler didn't complain. This is really stupid. What is the reason why this PR can't be merged? I think not having to monkey patch this definition to exclude $ and jQuery globals IS a great benefit.

**Comment by johnnyreilly** [comment]
Hi @use-strict,

I do understand your use case.  For what it's worth, this is a big problem with the definitions in Definitely Typed.  Everything is ambient.  

You may be aware of a project called [Typings](https://github.com/typings/typings)?  Long story short, this project, when a little more established, may nicely solve this particular problem.  I'm afraid I'm not planning to merge this PR in the meantime but I hope that Typings will be able to give you what you hope for in due course.  Sorry I can't say more but I'm short on time.  All the best.

**Pull request closed without merging**
