### PR TITLE
[rename] Remove minimum version

### PR DESCRIPTION
**Pull request by Aankhen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This is just removing the minimum version that I included in [the type definitions for rename](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24887). I added that because a few `$ExpectError` tests fail under 2.4, but as @mhegazy [pointed out](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24887#discussion_r180860237), the types themselves don’t require 2.5, so I’ve commented out the failing tests.

### CODE REVIEW

**Comment by mhegazy** [comment]
@Aankhen seems like you are using this package, you might want to add your name in the package to be pinged to review changes in the definition file.

**Comment by Aankhen** [comment]
Sorry @mhegazy, I’m not sure I follow: isn’t that what [the ‘Definitions by’ line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/rename/index.d.ts#L3) does?

**Comment by mhegazy** [comment]
:D sorry about that. silly me. you are already the owner. nevermind then.

**Comment by Aankhen** [comment]
Haha. No worries! Thank you for suggesting it, regardless.

**Pull request merged**
