### PR TITLE
[types-2.0] D3 dependencies and d3-format

### PR DESCRIPTION
**Pull request by tomwanzek**
Please fill in this template.
- [X] Prefer to make your PR against the `types-2.0` branch.
- [X ] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

This PR includes two changes. The first one is necessitated, to align the bundle minor version with the constituent D3 module minor versions. (Note: This is done ahead of updating **d3-voronoi\* and **d3-geo** to new versions and then bumping  the *_d3_ version to 4.3)

@gustavderdrache @ledragon

**[chore] d3:** Pin down versions
- Added package.json to pin down the minor versions of the D3 modules forming part of the standard bundle
- The pinned major.minor versions correspond to D3 v4.2 of the standard bundle (patches  are not pinnable, major version is too coarse)
- Changes tsconfig.json to used pinned dependencies

Edit: Checked missing box on top.

**[fix] d3-format :**
- Add apostrophe to permissible thousands separators to accommodate e.g. Switzerland, Liechtenstein (Thanks for the research @vetvicka)

### CODE REVIEW

**Comment by tomwanzek** [comment]
@andy-ms This is a follow-up to yesterday, it adds a `package.json` to `d3` to pin dependencies, plus a minor fix to d3-format.

Somehow, Travis has not started for appr. 3hrs. Could you kindly let it trigger.

**Comment by tomwanzek** [comment]
Thx!

**Comment by tomwanzek** [comment]
@andy-ms For some reason it seems like this PR has not been published to @types after the merge. Neither d3 nor d3-format have been updated on npm.

Thanks for looking into it.

**Comment by andy-ms** [comment]
@tomwanzek #12374

**Comment by tomwanzek** [comment]
@andy-ms thanks for the cross-reference! When you have a second, merging #12331 would also be great. Thx in advance.

**Comment by tomwanzek** [comment]
@andy-ms  Perfect. It's published now.

**Pull request merged**
