### PR TITLE
Restore angular-mocks-1.3.d.ts.

### PR DESCRIPTION
**Pull request by NicolaCheesmanAHC**
Our projects depend on angular-mocks-1.3.d.ts. This was removed as part of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10429. This pull request simply restores the previously available files.

### CODE REVIEW

**Comment by andy-ms** [comment]
Are you using `typings`? That should give you a way to depend on a specific commit hash, so the fact that it isn't available on the latest `master` shouldn't be a problem.

**Comment by NicolaCheesmanAHC** [comment]
I am using `typings` and, as you suggested, can get around the problem by referencing the specific commit hash. However, searching through the history to find the required commit is time consuming and doesn't seem the most efficient way to make use of this resource.

The main problem I can see is that any developer wishing to install this package would be unaware that it had ever existed as `typings search angular-mocks` does not return the 1.3 version as a result.

**Comment by andy-ms** [comment]
I think for most people the most recent types should be good enough. Are there any big differences between 1.3 and 1.5?

**Comment by NicolaCheesmanAHC** [comment]
There are differences. What was the reason for its removal?

**Comment by andy-ms** [comment]
The entire repository structure has changed (#13233). [Types are now on NPM.](https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/) We still plan to support older versions (Microsoft/types-publisher#3), but not in the same way, and we were thinking it would only be necessary for major versions.

**Comment by NicolaCheesmanAHC** [comment]
[Microsoft/types-publisher#3](https://github.com/Microsoft/types-publisher/issues/3) seems to suggest that Major.Minor versions such as 1.3 would be supported using the new structure alongside 1.0 and 1.2 which are already present. Would you suggest that the only way to use this package in future would be to reference the specific commit?

**Comment by andy-ms** [comment]
If you're using `typings`, you should reference a specific commit to protect against changes to the structure of DefinitelyTyped. We will be moving files around.

**Comment by mhegazy** [comment]
As @andy-ms noted, a commit hash is the correct way to go, the folder is not guaranteed to contain these files with the same name.

**Pull request closed without merging**
