### PR TITLE
[gremlin] Added Merge Enum, updated direction enum, update Translator

### PR DESCRIPTION
**Pull request by pyroflower**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [Removal of incr and decr from source code](https://github.com/apache/tinkerpop/commit/51c4e13e1bbe0dc9f37f7ccd91d89fac513e11dc#:~:text=order%3A%20toEnum(%27Order%27%2C%20%27asc%20desc%20shuffle%27)%2C)
  - [Merge Enum added to source code](https://github.com/apache/tinkerpop/blob/d653b2401271ff9eb8e2249f878344c27ac81418/gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js#L502)

### CODE REVIEW

**Comment by stakez** [comment]
@pyroflower thanks for driving this PR. Please can you also fix the following errors,

1.  The “isOpen” properties on the “DriverRemoteConnection” and “Client” classes are booleans not boolean Promises.
2. The addListener and removeListener methods of the Client class are not exposed. 

Please let me know if you need additional information 🙂.

**Comment by pyroflower** [comment]
@stakez types are included in the PR

**Comment by stakez** [comment]
Thanks a lot @pyroflower !!!

**Review by 7jpsan — APPROVED** [review]

**Comment by pyroflower** [comment]
Ready to merge

**Pull request merged**
