### PR TITLE
Fix nth

### PR DESCRIPTION
**Pull request by valerii15298**
The current behavior of `nth` is quit strange. Here is a problem(I included it in second commit, to check):
```ts
const promise = Promise.resolve([1, 2, 3]);

// $ExpectType number
const el = await promise.then(R.nth(0));
// but I am getting string above
```
This merge request introduces fix to this problem.

Overview:
1 commit: just format code as described in message via `'npm run prettier -- --write ./types/ramda/**/*.ts'` (quite straightforward, hope you guys don't mind it is not in separate pull request)

2 commit: show problem

3 commit: fix

I made typings a bit broader adding possibility of undefined in return clause(because it better represent function, nth can return undefined if element at specified index does not exist), and this breaks backward compatibility, but I can just add +1 commit and delete undefined if needed(when list is string) which will preserve fully backward compatibility.

*What is interesting:*
I do not know why the problem above exist, seems for me like a typescript bug or incorrect `lib.es5.d.ts` typings or something else what I do not understand for now.
But this PR fixes it.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modify
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e4717ee036de55de94a8c393c338d9e1576a3a9c
</p>

**Comment by valerii15298** [comment]
@adispring @essenmitsosse

**Review by adispring — APPROVED** [review]

**Comment by valerii15298** [comment]
Also guys if you have any ideas why current typings does not work, would be very interesting to hear that.

**Comment by valerii15298** [comment]
Ready to merge

**Comment by valerii15298** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60342

**Pull request merged**
