### PR TITLE
fix angularjs IComponentOptions require

### PR DESCRIPTION
**Pull request by ocombe**
case 2. Improvement to existing type definition.

This fixes the "require" property for the interface IComponentOptions, it was missing a type. Since with a directive you can require `string[]`, you can also require an object with an array of string for each property.

### CODE REVIEW

**Comment by mhegazy** [comment]
@ocombe please refresh the PR

**Comment by johnnyreilly** [comment]
@ocombe I was just trying to track down the relevant part of the docs for this.  I found this: https://docs.angularjs.org/api/ng/provider/$compileProvider#component

Is this what you're seeking to make changes to?  I ask as the docs seem to imply that the current definition is correct as is: (Well actually it rather implies that `string | string[] |` should come out.

> require - `{Object<string, string>=}` - requires the controllers of other directives and binds them to this component's controller. The object keys specify the property names under which the required controllers (object values) will be bound. See require.

But I've found the angular docs a little unclear in the past.  Is there a better reference of the example behaviour you're trying to add support for?

Also; tests always greatly appreciated :smile:

**Comment by ocombe** [comment]
Well, that's what I'm using in my code, so I know for sure that it works. I'm not sure if it's documented in their doc though...

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
