### PR TITLE
@types/node: Fix crypto input and output encoding

### PR DESCRIPTION
**Pull request by christophgysin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by christophgysin** [comment]
The CI job seems to fail on a recent change @devanshj made to serve-static. I can reproduce it on master:
```
$ npm test serve-static

> definitely-typed@0.0.3 test /home/chris/projects/DefinitelyTyped
> dtslint types "serve-static"

Error: /home/chris/projects/DefinitelyTyped/types/serve-static/serve-static-tests.ts:19:9
ERROR: 19:9  expect  TypeScript@4.2 expected type to be:
  Response<any, number>
got:
  Response<never, number>
ERROR: 49:9  expect  TypeScript@4.2 expected type to be:
  Response<any, number>
got:
  Response<never, number>

    at /home/chris/projects/DefinitelyTyped/node_modules/dtslint/bin/index.js:206:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/chris/projects/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
npm ERR! Test failed.  See above for more details.
```

Any idea what's causing it, and why it didn't fail on your PR?

**Comment by devanshj** [comment]
I'm clueless, I suspect maybe changes in express types but there seem to be none. Nonetheless I don't see any point bothering too much, just add a commit replacing `Response<any, number>` with `Response<never, number>` and it'd be good.

**Comment by christophgysin** [comment]
@devanshj Can you reproduce this on master? Can you point me to where I would need to make that change?

**Comment by devanshj** [comment]
> Can you reproduce this on master?

Yep I can

**Review by beaulac — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Comment by orta** [comment]
Alright, let's get this merged - thanks folks

**Review by ExE-Boss — CHANGES_REQUESTED** [review]
This should not have included <https://github.com/DefinitelyTyped/DefinitelyTyped/commit/60cc3d057b30b2ef63c34f49c47abc75c4293ba2> (<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50065>)

**Pull request merged**
