### PR TITLE
Update the graphql type definition for the GraphQLEnumType

### PR DESCRIPTION
**Pull request by orta**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [function is here](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L941-L944)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alloy** [comment]
Change looks good to me :+1: I’ll wait to merge until any of the maintainers gives a 👍 too.

@TonyPythoneer, @calebmer, @intellix, @firede, @kepennar, @freiksenet, @IvanGoncharov, @DxCx, @rportugal

**Comment by alloy** [comment]
Not sure why @dt-bot wasn’t able to parse the definition header (does it need to be included in files outside of the root `index.d.ts` file @andy-ms?

**Comment by DxCx** [comment]
LGTM 👍

**Comment by orta** [comment]
Cool, yeah, unsure about the header

**Pull request merged**
