### PR TITLE
Cheerio update

### PR DESCRIPTION
**Pull request by Almouro**
I was using Cheerio with TypeScript and realized some functions were missing.
So I updated the tests to be pretty similar to the [Cheerio docs](https://github.com/cheeriojs/cheerio/blob/master/Readme.md) and fixed the definitions accordingly, while checking that the generated cheerio-tests.js worked with the current library.

### CODE REVIEW

**Comment by vvakame** [comment]
*cheerio/cheerio.d.ts*

to authors(@blittle @wmaurer). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by Almouro** [comment]
Hi @vvakame @wmaurer @blittle, don't wanna impose, but any update on this? :)

**Comment by blittle** [comment]
@Almouro the only comment I have is looking at the quantity of changes it seems as though the tests are a little lite.

**Comment by Almouro** [comment]
Hey @blittle, thanks for commenting! :)

I added 230 lines of tests and added tests for a lot of functions I did not add. 
So IMHO, the quality of tests has improved.

Do you have any suggestions on how I could improve it even more? :)

**Comment by blittle** [comment]
@Almouro fair enough. A casual look without doing an exhaustive check things look good :)

**Comment by vvakame** [comment]
@blittle thanks!
@Almouro thanks mate!

**Pull request merged**
