### PR TITLE
D3 Modules Linting

### PR DESCRIPTION
**Pull request by tomwanzek**
This PR lints various D3 modules.

Other than basic linting, in **d3-collection** and **d3-interpolate** a small number of uses of `Object` for typing arguments has been changed to use `any`. This was done as the use of `Object` causes a linting error, and the actual intended use of `object` as a proper type is not supported below TS 2.2.
`TODO` comments have been added in all these code locations to change to `object` when formally restricting the definitions for use with TS 2.2+. Currently, they are meant to remain backwards compatible.

As a fallout of this PR, [types-publisher issue 285](https://github.com/Microsoft/types-publisher/issues/285) should be closed, once the modules in this PR have been successfully published to npm.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<n/a>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
The remaining Travis Error is related to **d3-shape**, which gets tested as a module depending  on modules in this PR.

Recently, linting started _not_ ignoring tslint rules that have been deactivated for a specific next line. The `callable-type` rule which causes the failure has already been set to `false` for the entirety of **d3-shape** in PR #16508  see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16508/files#diff-f4019b768b66b61256bc87b5ae19d096). As a result, once that prior PR is merged, the error in this PR should disappear.

**Comment by tomwanzek** [comment]
@andy-ms could Travis get a nudge to re-run? Since #16508 was merged, this PR should pass now.

cc @gustavderdrache

**Comment by tomwanzek** [comment]
@gustavderdrache Are you alright with the change from `Object` to `any` for the time being? All other changes in here are purely cosmetic linting. Thanks as always.T

**Review by gustavderdrache — APPROVED** [review]

**Comment by tomwanzek** [comment]
@aozgaa or @andy-ms changes are approved, could either of you kindly merge? Thx in advance, T.

**Pull request merged**
