### PR TITLE
(SpotifyAPI) Added total_tracks prop to the simplified album object

### PR DESCRIPTION
**Pull request by AlexPshul**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-album

If removing a declaration:

### CODE REVIEW

**Review by BastiDood — APPROVED** [review]
Everything looks good if I'm not mistaken. I'll wait on the others to chime in before preparing to merge.

**Review by Stadly — APPROVED** [review]
Ready to merge

**Comment by Stadly** [comment]
Not very instantly, if you ask me. Maybe the approval comments do not lead to merging. Trying again.

Ready to merge

**Review by Stadly — APPROVED** [review]
Maybe I have to mark the files as viewed. Trying again.

Ready to merge

**Comment by AlexPshul** [comment]
Thanks for the approvals @Some-Dood , @Stadly .

I'll try the Ready to merge, too.

**Comment by AlexPshul** [comment]
Ready to merge

**Pull request merged**
