### PR TITLE
i18n - Add mustache plurals support

### PR DESCRIPTION
**Pull request by le-u-f**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [i18n mustache plurals](https://github.com/mashpie/i18n-node#ranged-interval-support) & [i18n plurals test](https://github.com/mashpie/i18n-node/blob/master/test/i18n.plurals.js)

### CODE REVIEW

**Comment by joshuajeschek** [comment]
Hi, content-wise your changes are okay, I think, but I have a question regarding variable naming.
Why did you call the first parameter `flattedKey`? I couldn't find this anywhere else in the types, and I think that similar parameters are called `phrase`, right?
Also, look at this: [Google NGram flattened vs flatted](https://books.google.com/ngrams/graph?content=flatted%2Cflattened&year_start=1700&year_end=2019&corpus=26&smoothing=3) -> flatted seems like it is a rather deprecated word in the english language 😉

**Comment by Barruchou** [comment]
Hello, thank you for the review.
As stated in the documentation of the repo (https://github.com/mashpie/i18n-node#ranged-interval-support), this feature is based on the name of the keys of an object (json file) and not on a "phrase", as it is possible to do with objectNotation enabled - https://github.com/mashpie/i18n-node#object-notation
I can rename this variable to "objectKey", "flattenedKey" or as you suggest "phrase".

**Review by joshuajeschek — CHANGES_REQUESTED** [review]
I'd suggest using phrase, to keep it in line with the other functions' parameters :)

**Comment by Barruchou** [comment]
It's done :smiley:

**Review by joshuajeschek — APPROVED** [review]
looking good ^^

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
