### PR TITLE
canvaskit-wasm: add MakeCanvas() and SkHtmlCanvas

### LINKED ISSUE #46194: [canvaskit-wasm] MakeCanvas() and getContext() missing in definition
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/canvaskit-wasm` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ashlanderr 

If you do not mention the authors the issue will be ignored.

The definition file is outdated.

### PR DESCRIPTION
**Pull request by ashlanderr**
Fix #46194

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/canvaskit-wasm/v/0.9.0#drop-in-canvas2d-replacement
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## canvaskit-wasm ([<kbd>unpkg</kbd>](https://unpkg.com/browse/canvaskit-wasm@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'canvaskit-wasm'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. CanvasKitInit
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f84b82d5eb16954043dc694c80f16615af369ff0
</p>

**Comment by ashlanderr** [comment]
> Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
> The check for missing properties isn't always right, so take this list as advice, not a requirement.
> 
> ## canvaskit-wasm ([unpkg](https://unpkg.com/browse/canvaskit-wasm@latest/))
> was missing the following properties:
> 
> 1. The declaration doesn't match the JavaScript module 'canvaskit-wasm'. Reason:
>    The JavaScript module can be called or constructed, but the declaration module cannot.
> 
> The most common way to resolve this error is to use 'export =' syntax.
> To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
> 
> 1. CanvasKitInit
> 
> Generated by  [dangerJS](https://danger.systems/js) against [f84b82d](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f84b82d5eb16954043dc694c80f16615af369ff0)

I don't understand where is the problem. The package canvaskit-wasm doesn't contains index.js. In [docs](https://www.npmjs.com/package/canvaskit-wasm#webpack) it is imported with `canvaskit-wasm/bin/canvaskit.js`. In my definitions file `canvaskit-wasm/bin/canvaskit.d.ts` contains `export = CanvasKitInit`

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@ashlanderr  this is to fix #46194, am I correct?
Thanks!

**Comment by peterblazejewicz** [comment]
Ready to merge 🛴

**Comment by ashlanderr** [comment]
> LGTM!
> @ashlanderr this is to fix #46194, am I correct?
> Thanks!

Yes, that's right.

**Comment by ashlanderr** [comment]
Ready to merge

**Pull request merged**
