### PR TITLE
Add type definitions for ember__destroyable

### LINKED ISSUE #1419: Add types for Destroyable
### Which package(s) does this enhancement pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [x] Other
  - [ ] I don't know

### Please write a user story for this feature

As an addon OR app author,
I want type definitions for Ember Destroyables available on DefinitelyTyped, 
so that I can use Destroyables in my typescript ember app or addon.

Types currently exist for Destroyables in the destroyables polyfill. They need to be added to DefinitelyTyped now that the Destroyables API is part of ember as of 3.22
https://github.com/ember-polyfills/ember-destroyable-polyfill/blob/master/index.d.ts

### PR DESCRIPTION
**Pull request by steveszc**
ember 3.22 added a new Destroyable API. 

[Type definitions exist](https://github.com/ember-polyfills/ember-destroyable-polyfill/blob/master/index.d.ts) in [ember-destroyable-polyfill](https://github.com/ember-polyfills/ember-destroyable-polyfill). This ports those existing type definitions to DT.

Fixes https://github.com/typed-ember/ember-cli-typescript/issues/1419

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
👏🏼 Nice work! I'd also love for @jamescdavis or @dfreeman to take a look here as well to confirm, but this looks great! Thanks especially for adding a set of tests. The one change I'd love to see is some tests where we assert that things which we *don't* expect to work *do in fact not work*, with `$ExpectError`, so that we don't accidentally "wide" to support *just anything*.

**Comment by steveszc** [comment]
@chriskrycho  Feedback on tests addressed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52024/commits/36780710e0b86edc92cdfe8a044f44044460aeae

**Review by dfreeman — APPROVED** [review]
👍

**Review by chriskrycho — APPROVED** [review]
Thanks!

**Review by andrewbranch — APPROVED** [review]

**Comment by steveszc** [comment]
Ready to merge

**Pull request merged**
