### PR TITLE
Add properties to Request in rest library.

### PR DESCRIPTION
**Pull request by barinbritva**
Please fill in this template.
- [ ] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <https://github.com/cujojs/rest/blob/v1.3.1/docs/interfaces.md#common-request-properties>
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by vvakame** [comment]
*rest/rest.d.ts*

to author (@Nemo157). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by Nemo157** [comment]
Just based on the docs it appears to me that the `originator` would be a `Client` rather than a `() => Client`?

**Comment by barinbritva** [comment]
@Nemo157, I read the code originator.
It is function like this:
`function interceptedClient(request) {`
which returns response promise.
I edited this definition.

**Comment by barinbritva** [comment]
@vvakame, I do not know )) I just want to install it with `typings install rest`. If it will work from " types-2.0",  I'm not against.

**Comment by barinbritva** [comment]
Guys, where are you? )) Too many PRs?

**Comment by paulvanbrenk** [comment]
I can merge this small change to `typings-2.0`

**Pull request merged**
