### PR TITLE
[fabric] Update Image constructor

### PR DESCRIPTION
**Pull request by martin-badin**
Documentation: http://fabricjs.com/docs/fabric.Image.html#initialize
Discussion: #58213

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test fabric`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://fabricjs.com/docs/fabric.Image.html#initialize>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by martin-badin** [comment]
@peacefingers please review

**Comment by martin-badin** [comment]
@peterblazejewicz please review. Thanks

**Comment by peterblazejewicz** [comment]
That's ok to extend the param types, but I cannot see any 'callback' in the actual source code (nor a fabric tests). internally it calls 'initialize' method that accepts two args

**Comment by martin-badin** [comment]
Thanks, @peterblazejewicz. It seems there is an issue with the documentation. I will remove the callback.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
