### PR TITLE
[tap@15] Fix invalid t.rejects and t.throws calls

### PR DESCRIPTION
**Pull request by zkldi**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: << N/A >>

---

Another bug in the existing types when it comes to t.rejects and t.throws as they depend use t.match (which is any and changed in the last PR).

### CODE REVIEW

**Review by orta — APPROVED** [review]
As you're the owner here, I'm going to assume you know what you're talking about with the `Error` to `any` 👍🏻

**Comment by zkldi** [comment]
> 
> 
> As you're the owner here, I'm going to assume you know what you're talking about with the `Error` to `any` 👍🏻

Yep - this function catches anything that is thrown - which isn't necessarily an error (or could be an extension of error). furthermore, all objects passed to this function may be partial<T>'d as it matches only the fields it wants to see.

**Comment by zkldi** [comment]
ready to merge

**Comment by zkldi** [comment]
Ready to merge

**Pull request merged**
