### PR TITLE
fix(node): fix global URLSearchParams var type for TS 3.7.x compatibility

### LINKED ISSUE #58562: bug(node): a combination of @types/node 17.0.14 and TS 3.7.3 raises an error
A combination of @types/node and typescript: 3.7.3 yields:

```
../../node_modules/.registry.npmjs.org/@types/node/12.20.43/node_modules/@types/node/url.d.ts:137:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'URLSearchParams' must be of type '{ new (init?: string | string[][] | URLSearchParams | Record<string, string>): URLSearchParams; prototype: URLSearchParams; }', but here has type '{ new (init?: string | string[][] | URLSearchParams | Record<string, string>): URLSearchParams; prototype: URLSearchParams; toString(): string; }'.

137         var URLSearchParams: {
                ~~~~~~~~~~~~~~~

  ../../node_modules/.registry.npmjs.org/typescript/3.7.3/node_modules/typescript/lib/lib.dom.d.ts:16107:13
    16107 declare var URLSearchParams: {
                      ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.
```

Is there a good workaround for this now?

_Originally posted by @aaronatbissell in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960#issuecomment-1027198564_

relates #34960

### PR DESCRIPTION
**Pull request by antongolub**
closes #58562

relates #34960 #58277

The fix uses janky `lib.dom.d.ts` version detection for conditional type declaration.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
I believe it works as expected (tested on playground).
Can you amend test at least that way?
```diff
-    const searchParams = new url.URLSearchParams('abc=123');
-
+    let searchParams: url.URLSearchParams = new url.URLSearchParams('abc=123');
+    searchParams = new URLSearchParams('abc=123')
```

**Comment by antongolub** [comment]
Sure. Tweaked the test a bit.

**Comment by antongolub** [comment]
Just a note to make it clear for everyone: DT autotests use TS 3.8.3 and up, so we didn't notice that 3.7 was broken in #58277.

**Comment by SimonSchick** [comment]
Is it not possible to achieve this through declaration merging rather than this generic check?

**Comment by antongolub** [comment]
As I understand, `URLSearchParams` var type in `lib.dom` and `@types/node` should be equal to make it compilable if both libdefs are used at the same time.

**Comment by peterblazejewicz** [comment]
Waiting for Simon's vote, thx!

**Review by SimonSchick — APPROVED** [review]
Nvm this doesn't work with decl merging since the 'static' definition is direct and not via interfaces on the dom libs side.

**Comment by amcasey** [comment]
While I'm pretty impressed that you found a way to do version detection, that is still a bit "janky", as you say, for such a widely used package, especially considering that TS 3.7 is no longer supported (hence the lack of testing).

Having said that, we're not opposed to changes that help TS 3.7 users, as long as they're work nicely for the supported versions too.

**Pull request closed without merging**
