### PR TITLE
Improve node child process

### PR DESCRIPTION
**Pull request by vvakame**
from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8564

@akim-mcmath could you review this PR?

### CODE REVIEW

**Comment by akim-mcmath** [comment]
Thanks for your timely response and solution. Your PR looks perfect; it certainly fixes the problem. And furthermore, it lets the user pass `encoding: 'buffer'`, which also works and appears in Node's [documentation][docs]. The only addition I might suggest would be to update the usage comments to clarify that users may pass either `'buffer'` or `null as string` for the encoding, since both of these appear in the docs.

[docs]: https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

**Comment by vvakame** [comment]
@akim-mcmath I tried it. but I got error. 
Do my understanding is mistakes?

```
$ node -v
v5.8.0
$ node -e 'require("child_process").execSync("tsc", {encoding: "buffer"});'
buffer.js:381
          throw new TypeError('Unknown encoding: ' + encoding);
          ^

TypeError: Unknown encoding: buffer
    at Buffer.slowToString (buffer.js:381:17)
    at Buffer.toString (buffer.js:394:27)
    at spawnSync (child_process.js:440:43)
    at Object.execSync (child_process.js:503:13)
    at [eval]:1:26
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:544:27
    at _combinedTickCallback (node.js:370:9)
```

**Comment by akim-mcmath** [comment]
This seems to be an inconsistency in Node between the synchronous and asynchronous variants of `exec()`, combined with poor documentation. The [source code][async source] for `exec()` and `execFile()` (asynchronous) reveals that any encoding option that is not a valid string encoding will be treated as a Buffer. But for `execFileSync()` and `execSync()`, the [source code][sync source] shows that the encoding option is just passed the the `Buffer` constructor without modification. And [here] you can see that if a string is passed to the constructor as the encoding argument, it will throw an error if it is not valid.

In short, this is a problem with Node and its documentation. The documentation should not say that the default encoding is `'buffer'` for the synchronous variants of `exec()`, since this will throw an error. However, passing `'buffer'` as the encoding will work fine for the asynchronous variants.

I think your PR is fine as it is without modifying the usage comments. If the user does pass `'buffer'` to `exec()` or `execFile()`, it will compile and run as expected.

[async source]: https://github.com/nodejs/node/blob/ba16a120518e972bb3ac0190196fdb4caa32f4a6/lib/child_process.js#L148-L159
[sync source]: https://github.com/nodejs/node/blob/ba16a120518e972bb3ac0190196fdb4caa32f4a6/lib/child_process.js#L425
[buffer source]: https://github.com/nodejs/node/blob/ba16a120518e972bb3ac0190196fdb4caa32f4a6/lib/buffer.js#L357-L385

**Comment by vvakame** [comment]
@akim-mcmath I understand... thanks a lot! your advice is very helpful. :smile_cat:

**Comment by akim-mcmath** [comment]
Thanks a lot for your work on this and for coming up with a solution so quickly.

**Pull request merged**
