### PR TITLE
Adding types for Microsoft Teams Library

### PR DESCRIPTION
**Pull request by WrathOfZombies**
> I have added the basic template and followed the guides to the best of my knowledge. Today, there's no `npm` package for this library but it will exist at some point in the future. For the moment I want to publish this to the `@types` scope under `@types/microsoftteams`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by WrathOfZombies** [comment]
Could the build failure be related to https://github.com/palantir/tslint/issues/2054? Not sure what needs to be fixed here. Any assistance would be helpful.

**Comment by andy-ms** [comment]
Hi, it looks like your guess is right. You can fix the tslint crashing by adding a `// TypeScript Version: 2.1` comment on line 5 of `index.d.ts`.
But if you are the author of the package, you should [bundle](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) types with it. Unless there is some value to having types available even if the package isn't published?

**Comment by WrathOfZombies** [comment]
@andy-ms Will try it out. And to your question, there's no publicly available package today. We serve this library from CDN only. That said there is a plan to have a npm package and when that is available, we'll deprecate this @types package. Its just a stop gap measure for now.

**Comment by WrathOfZombies** [comment]
@andy-ms That seems to have worked correctly. What are the next steps?

**Pull request merged**
