### PR TITLE
Update/auth0-lock: Add checkbox support for signup fields

### PR DESCRIPTION
**Pull request by lfaudreejr**
Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22464
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

@carusology @goldcaddy77

### CODE REVIEW

**Comment by carusology** [comment]
Thanks for adding this.

While the change looks fine to me in isolation, it also looks like something that could benefit from a [union type](https://www.typescriptlang.org/docs/handbook/advanced-types.html). According to [the documentation you referenced](https://auth0.com/docs/libraries/lock/v11/configuration#checkbox-field), "the prefill value can determine the default state of the checkbox (true or false), and it is required."

This means we could make `Auth0LockAdditionalSignUpField` something like a union of `Auth0LockAdditionalSignUpSelectField`, `Auth0LockAdditionalSignUpTextField`, 
and finally an `Auth0LockAdditionalSignUpCheckboxField`. The first two can be clones of the current implementation, while yours could make `prefill` required, and only accept the values of "true" and false" instead of be optional and any generic string.

Forgive my syntax since I'm just doing this off the top of my head, but I'm describing something like the following. I may also have some of the properties wrong - the sample is a bit ambiguous.

```ts
type Auth0LockAdditionalSignUpField = Auth0LockAdditionalSelectSignUpField | Auth0LockAdditionalTextSignUpField | Auth0LockAdditionalCheckboxSignUpField;

interface Auth0LockAdditionalCheckboxSignUpField {
    icon?: string;
    name: string;
    placeholder: string;
    prefill: "true" | "false";
    type: "checkbox";
    validator?: (input: string) => { valid: boolean; hint?: string };
}
```

Let me know what you think.

**Review by carusology — APPROVED** [review]
See my comment on converting this to a union type. Not a blocker as the proposed solution is better than what was there before, but it would further improve the type definition and it relates to the same code.

**Comment by lfaudreejr** [comment]
Thanks for the review! Yes, I think a union type field makes more sense. I can make the changes.

**Comment by carusology** [comment]
@lfaudreejr /tip 🎩

**Review by carusology — APPROVED** [review]

**Pull request merged**
