### PR TITLE
CodeMirror: make EditorChangeCancellable.update optional, define KeyMap type

### PR DESCRIPTION
**Pull request by mattmccutchen**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [EditorChangeCancellable.update](https://codemirror.net/doc/manual.html#event_beforeChange), [key maps](https://codemirror.net/doc/manual.html#keymaps)
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mihailik** [comment]
Looks really sensible, loving it!  :heart: 

The change has certain potential to break quirky code around keyMap usage, but for legitimate code should work OK.

LGTM

:+1:

**Comment by mihailik** [comment]
P.S. sorry for a wait — just came from holidays in Slovakia :-D

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Comment by mattmccutchen** [comment]
Ping @RyanCavanaugh and @andy-ms as per the [FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-pr-is-merged-when-will-the-types-npm-package-be-updated): the [package](https://www.npmjs.com/package/@types/codemirror) has not been updated.

**Comment by jasongrout** [comment]
Can a keymap be just a string? According to [codemirror docs](https://codemirror.net/doc/manual.html#keymaps):

> A key map is an object mapping strings that identify the buttons to functions that implement their functionality.

It does seem that removeKeys can take a string (the name of the keymap), but extraKeys seems to always be an keymap object?

**Comment by mattmccutchen** [comment]
@jasongrout Unfortunately, I don't want to get involved in this again right now, and I doubt anyone else will act on your comment here.  Please follow the normal process to submit a new issue or pull request.

**Comment by jasongrout** [comment]
No problem, I'll submit a PR. It's causing us some typing problems when we upgraded - I'm happy to help improve the typings.

**Pull request merged**
