### PR TITLE
htmlSafe returns SafeString not void

### PR DESCRIPTION
**Pull request by BryanCrotaz**
https://github.com/typed-ember/ember-typings/issues/77
https://github.com/typed-ember/ember-cli-typescript/issues/232

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
It's failing for reasons unrelated to this PR

**Comment by BryanCrotaz** [comment]
Travis is failing with 
```
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/ember/test/array-ext.ts:16:32
ERROR: 16:32   expect   TypeScript@next compile error: 
Argument of type 'ComputedProperty<Fix<Person & { name: string; }> | undefined, Fix<Person & { name: string; }> | undefined>' is not assignable to parameter of type 'Person'.
  Property 'name' is missing in type 'ComputedProperty<Fix<Person & { name: string; }> | undefined, Fix<Person & { name: string; }> | undefined>'.
```
which is nothing to do with my change.

**Review by alexlafroscia — APPROVED** [review]

**Comment by BryanCrotaz** [comment]
@alexlafroscia what do we do from here?

**Comment by BryanCrotaz** [comment]
@alexlafroscia um...??

**Comment by mike-north** [comment]
@BryanCrotaz we're currently waiting on this issue https://github.com/typed-ember/ember-cli-typescript/issues/246

**Comment by alexlafroscia** [comment]
Sorry, I've been on vacation the last week.

The failure here is beyond my knowledge of TypeScript.

**Pull request closed without merging**
