### PR TITLE
Auth0 fix for dependencies on auth0-js, and tsc clean up.

### PR DESCRIPTION
**Pull request by rokadias**
When definitelytyped released the auth0-js package it did not include the new v7 folder which caused my existing application to break. I think the header was incorrect in the auth0-js file so I made some fixes in the hope of remedying this issue.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

Just looking to make fixes so the above does not apply.

### CODE REVIEW

**Comment by adrianchia** [comment]
Looks good to me.

**Comment by callicles** [comment]
+1

**Comment by tg339** [comment]
+10

**Comment by mferron-datalogue** [comment]
+1

**Comment by od0** [comment]
@bowdenk7 please review if you have a chance

**Pull request merged**
