### PR TITLE
fix(node): add named export for `constants`

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This adds missing export in `node:fs/promises`

- exports
- tests
- sorted imports for readability

Thanks!

/cc @Himself65

Fixes #61676

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]
Please avoid unrelated changes, it makes things hard to review.

**Comment by peterblazejewicz** [comment]
I could retract those, there were intentional, sorted improve readability, in case when using notepad. I can retract, np

**Review by himself65 — APPROVED** [review]

**Comment by yogarasu** [comment]
Thank you for your fix

**Review by r3nya — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
