### PR TITLE
Updated Pixi definitions to v3.0.6 (latest)

### PR DESCRIPTION
**Pull request by Adamfsk**
Pixi definitions have been badly out of date for a while on here. I've grabbed the latest definitions from Clark Stevenson (one of the lead contributors to pixi who now maintains the official definitions) and replaced the old ones. 

The tests were removed as they are two major versions old now!

### CODE REVIEW

**Comment by vvakame** [comment]
@Adamfsk thank you for your contributions.
pixi/pixi-tests.ts is required. do not remove it.
@clark-stevenson

**Comment by Adamfsk** [comment]
@vvakame The tests are no good now. I'll have a look through and update them later in the week and send a new pull request

**Comment by clark-stevenson** [comment]
Nice to see :dancer: 

Yeah I would get rid of the tests are they are useless. I am currently in the process of writing the example repo of pixi in TypeScript. I will eventually get around to merging them all into a test file over the next couple of weeks.

**Comment by clark-stevenson** [comment]
Hey guys, I am just looking for some advice.  

I covered  85% of the examples so far. Every example is its own class and its own .ts file. I did this for my learning purpose.  

Each example is its own class within its own module.  (basics/Video,  demos/Interactivity)

Do I just want to copy and paste all of these modules and classes only into a big pixi-tests.ts file?

In other words, the goal of pixi-tests.ts is simply to highlight build errors with the pixi.d.ts file? I do not need to do anything else?

**Comment by clark-stevenson** [comment]
So just to get this out my inbox at last! 

A ton of tests [were added](https://github.com/pixijs/pixi-typescript)

**Comment by vvakame** [comment]
oops, sorry. I had missed...
I'm looking for #5159

**Comment by mhegazy** [comment]
@Adamfsk is this still needed? can you refresh the PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
