### PR TITLE
[mapbox-gl] update to mapbox-gl 2.0.0

### PR DESCRIPTION
**Pull request by dmytro-gokun**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.0.0
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by dmytro-gokun** [comment]
@amxfonseca Could you help here once more? 🙏

**Review by amxfonseca — APPROVED** [review]
Nice to see the typescript upgrade. Do we have it as a proper dependency on the package.json?

**Comment by dmytro-gokun** [comment]
@amxfonseca Actually, i should not have updated TypeScript version :)

**Comment by dmytro-gokun** [comment]
@amxfonseca Would you mind looking once more? There was a CI failure, so I had to submit some small changes.

**Review by amxfonseca — APPROVED** [review]
👍

**Comment by dmytro-gokun** [comment]
Ready to merge

**Pull request merged**
