### PR TITLE
added package.json to peg typescript versions - alt, airbnb-prop-types, agiledigital__mule-preview

### PR DESCRIPTION
**Pull request by hellatan**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

I only added package.json files so that these packages can have a specific typescript version. There seems to be an issue with the benchmark build that relates to the package.json file specifically in `agiledigital__mule-preview` which is blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671.

```
🌯  ~/projects/DefinitelyTyped 🌮  add-packagejson 🍔
npm run lint agiledigital__mule-preview

> definitely-typed@0.0.3 lint /Users/daletan/projects/DefinitelyTyped
> dtslint types "agiledigital__mule-preview"

🌯  ~/projects/DefinitelyTyped 🌮  add-packagejson 🍔
npm run lint airbnb-prop-types

> definitely-typed@0.0.3 lint /Users/daletan/projects/DefinitelyTyped
> dtslint types "airbnb-prop-types"

🌯  ~/projects/DefinitelyTyped 🌮  add-packagejson 🍔
npm run lint alt

> definitely-typed@0.0.3 lint /Users/daletan/projects/DefinitelyTyped
> dtslint types "alt"

🌯  ~/projects/DefinitelyTyped 🌮  add-packagejson 🍔
```

### CODE REVIEW

**Comment by milesj** [comment]
Other types packages moved old types into a folder like you stated, for example:

- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yargs

I'm not sure what the correct approach is here. If it's updating types for a latest version, it may be a breaking change if `typesVersions` isnt viable.

**Comment by hellatan** [comment]
> Other types packages moved old types into a folder like you stated

oy...i'll give it a shot. The maintainer of `agiledigital` said they'd look into updating for ts@4 support. I guess there isn't any clear documentation on how to handle this situation other than the `typesVersions` release note you posted earlier? Would this mean that I'd have to create types for ts@4 to get these to pass properly? Also, both `react` and `yargs` do not leverage `typesVersions` in their respective package.json files.

**Comment by milesj** [comment]
From what I've seen, `react` and `yargs` version alongside the upstream. So React types v16x is always matching React v16.x, at least major/minor. They also don't use newer TS syntax, so backwards compatibility hasnt been an issue.

**Comment by NoxHarmonium** [comment]
It seems like its a bug in the perf tool anyway: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671#issuecomment-642138999

I've checked the types locally and they are all fine on any of the ts 3.4+/ts4 tests.

My hunch is that these three packages are the first three packages that depend on react alphabetically.

**Pull request closed without merging**
