### PR TITLE
[@types/oracledb] Update interface DBError member stack as per parent Error interface.

### PR DESCRIPTION
**Pull request by sudarshan12s**
There was an compilation issue when the sequelize typescript tests are run as part of sequelize - v7 development of Oracle dialect .
Following is the error. As a fix,  I see the `stack` with `undefined` type needs to be removed (same as parent `Error` interface) or we can simply remove these properties derived from `Error` interface.  I removed the `undefined` type against the `stack` member. 
  Please see..

```
Error: Command failed: tsc --emitDeclarationOnly
       
           at ChildProcess.exithandler (node:child_process:419:12)
           at ChildProcess.emit (node:events:514:28)
           at maybeClose (node:internal/child_process:1091:16)
           at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
         code: 2,
         killed: false,
         signal: null,
         cmd: 'tsc --emitDeclarationOnly',
         stdout: "../../node_modules/@types/oracledb/index.d.ts(1476,15): error TS2430: Interface 'DBError' incorrectly extends interface 'Error'.\n" +
           "  Types of property 'stack' are incompatible.\n" +
           "    Type 'string | undefined' is not assignable to type 'string'.\n" +
           "      Type 'undefined' is not assignable to type 'string'.\n",
         stderr: ''
       }

```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by dannyb648** [comment]
Hi @sudarshan12s do you mind if we roll this isnt 6.3.0 - were currently testing it and i dont want any more breaking changes coming in. 6.2.1 is already a mess as it wasnt tested at all.

**Comment by dannyb648** [comment]
MAINTAINERS DO NOT MERGE

**Comment by dannyb648** [comment]
@sudarshan12s Just spoke to Sharad! Will get this in as 6.2.2

**Review by danbeglin — APPROVED** [review]

**Comment by sudarshan12s** [comment]
> Hi @sudarshan12s do you mind if we roll this isnt 6.3.0 - were currently testing it and i dont want any more breaking changes coming in. 6.2.1 is already a mess as it wasnt tested at all.

Thanks @dannyb648. It is perfectly fine..

**Review by jakebailey — APPROVED** [review]

**Comment by sudarshan12s** [comment]
> Ready to merge

**Pull request merged**
