### PR TITLE
[@types/i18n-js] Allow the translate function to return something other than a string

### PR DESCRIPTION
**Pull request by rye761**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes). **See note below**
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/fnando/i18n-js/blob/6aec93574bb6721f600d930ebe6500f09dd39f23/app/assets/javascripts/i18n.js#L572>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. **It does not**

I do realize that this uses a generic type against the common mistakes guidelines. However, this is the only way I have found to adjust this without breaking existing code. 95% of the time (and I'm sure 100% in some applications), t will return a string. However, it does not have to. By specifying an array of strings in the translation file, you will get an array back. The definition needs to accommodate this usage. I did try adding a second definition that returns any but because they take the same parameters, TypeScript still prefers the string variant even when type assertion is used. This is the only way that worked for me to allow this usage without breaking existing code. Please let me know if there is another way, I am new to TS.

### CODE REVIEW

**Review by weswigham — CHANGES_REQUESTED** [review]
There are other ways to accomplish this with, like `interface` merging (in the library and augmented in your app) and indexed-access types. The reason we don't allow this is because it is an unsafe typecast encoded into your types - you should never have it, it's not typesafe. It is _no different_ than `I18n.t(whatever) as string[]`.

**Comment by rye761** [comment]
> 
> 
> There are other ways to accomplish this with, like `interface` merging (in the library and augmented in your app) and indexed-access types. The reason we don't allow this is because it is an unsafe typecast encoded into your types - you should never have it, it's not typesafe. It is _no different_ than `I18n.t(whatever) as string[]`.

I'm not sure how to use either of those solutions in this case unfortunately. I have updated it to simply use `any`. I was mostly concerned with breaking existing code. Using any might break some, but it shouldn't be too bad.

**Comment by ypresto** [comment]
@rye761 

> There are other ways to accomplish this with, like interface merging...

> I'm not sure how to use either of those solutions in this case unfortunately...

It's available in current typing!
You can add below code to your project.

```ts
declare module 'i18n-js' {
    // This is context of declare namespace I18n { ... }

    function translate(scope: 'genericNames'): string[]
    function t(scope: 'genericNames'): string[]
}
```

Note that passing `{ scope: ... }` option to second argument may return different type than this typing. If still you want to pass option, you can add `options?: I18n.TranslateOptions` to above example.

**Comment by rye761** [comment]
@ypresto Thanks for the response. I have implemented this solution and it is working for now. I still think the typings are a bit weird in this fashion, but I am going to close this PR.

**Pull request closed without merging**
