### PR TITLE
Replace declare statements with files

### PR DESCRIPTION
**Pull request by remcohaszing**
This allows importing the paths with a file extension. This was also the reason some ESLint rules were disabled and the package was listed under `failingPackages` in `attw.json`.

The actual types are unchanged.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
There has to be a better way, right? How does this package get used in practice?

**Comment by remcohaszing** [comment]
I just got started in a project that uses `@fengkx/react-syntax-highlighter`, which is a fork. I will create a follow-up PR with types for that fork, which will essentially be a copy of the types for `react-syntax-highlighter`.

Looking at the example, e.g. https://github.com/react-syntax-highlighter/react-syntax-highlighter#prism, you need to import and register the style and language you want to support. There are a lot of languages and styles, meaning there are a lot of source files.

The project is built from JSX source into both CJS and faux ESM, meaning there are even twice as many files as in the source code.

I didn’t change any types, I only changed it from `declare module` syntax to separate files. But upon further inspection, it looks like all languages are actually [re-exported](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/languages/hljs/typescript.js) from `highlight.js` / `prism`.

**Comment by RyanCavanaugh** [comment]
It seems like the list of names/languages is so large that we should just use a wildcard declare here

**Comment by jakebailey** [comment]
Testing locally, this change only increases the `pnpm test` time from 10s to 13s.

My impression is that this should be "okay" besides this specific PR's size overwhelming the bot. That shouldn't happen on followup PRs, as we only query modified files.

Sorting packages by their file counts:

```
hapi 236
refractor 236
openfin 253
javascript-time-ago 286
crocks 293
lodash-es 335
node 381
carbon-components-react 415
facebook-nodejs-business-sdk 532
nginstack__engine 553
es-abstract 713
lodash 724
ramda 770
three 897
react-syntax-highlighter 1159
carbon__pictograms-react 4742
```

This package isn't even the largest one, and at least the files are small.

I'm personally comfortable taking this.

**Comment by jakebailey** [comment]
Hm, this package has 1.3 million downloads, though. That's 1000 extra files to ship to everyone; that's not so good. That and 1000 extra files to auto-import ☹️ 

You mentioned that the original reason to do this was for the extensions; is it just as okay to declare each of the extension'd modules instead?

**Comment by remcohaszing** [comment]
The original reason is that I intend to create types for a fork in another PR, which will essentially be a copy of these types. I noticed that these types have some quirks, notably:

- It’s in `attw.json#/failingPackages`.
- It has its own `.eslintrc.json`.
- It uses `declare module`, which AFAIK is generally considered a bad practice on DefinitelyTyped.

I thought this cleanup would be a simple quick win. I based that on technical correctness, not considering any potential performance impacts.

The ability to import with or without extensions is a practical impact of these changes, but I personally don’t need it.

---

Now that I’m thinking about it, an alternative to publishing types for the fork, would be to have the following in `package.json` of my project:

```json
{
  "dependencies": {
    "@types/fengkx__react-syntax-highlighter": "npm:@types/react-syntax-highlighter@15.5.11"
  }
}
```

But that also doesn’t work if the types use `declare module`.

**Comment by jakebailey** [comment]
I absolutely agree that this is a technically correct change.

It would be interesting to pull up a project which uses this library just to verify it does the right thing. But, I'm more imaginging someone writing JS code and using ATA to load this library. Or worse, someone loading this up in the browser (the playground, vscode.dev), and suddenly we're making 1600 calls to a CDN. Hopefully that isn't how it works, especially if these individual files are not reexported from the entrypoint. Which, I think is doesn't (reading https://github.com/remcohaszing/DefinitelyTyped/blob/react-syntax-highlight/types/react-syntax-highlighter/index.d.ts).

**Comment by remcohaszing** [comment]
I just came up with a similar situation. ([playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAchBAdgQwMYQLQFMAmwM0A9LgM4gkBu5ZhxU9R0AdGmMAkA))

```ts
import 'monaco-editor/esm/vs/editor/editor.api'
```

As can be seen in `monaco-editor/esm/vs/editor/editor.api.d.ts` in the [npm code tab](https://www.npmjs.com/package/monaco-editor?activeTab=code) (I really wish npm had linkable URLs for that), this entrypoint does not import any other files, yet the playground requests every file from the CDN.

TypeScript playground request traffic for `monaco-editor`

So… that’s not great. The good news is though, that the playground performance seems to be fine, even if it requests >200 files for `monaco-editor`.

A lot of files in this PR are the same though. The number of files could be deduplicated using package exports. The following exports object would cut the number of files in half:

```json
{
  "exports": {
    "./dist/cjs/*.js": "./dist/cjs/*.js",
    "./dist/cjs/*": "./dist/cjs/*.js",
    "./dist/esm/*.js": "./dist/cjs/*.js",
    "./dist/esm/*": "./dist/cjs/*.js"
  }
}
```

We could use the same trick to significantly reduce the number of language and style files:

```jsonc
{
  "exports": {
    "./dist/cjs/languages/hljs/javascript.js": "./dist/cjs/languages/hljs/javascript.js",
    "./dist/cjs/languages/hljs/javascript": "./dist/cjs/languages/hljs/javascript.js",
    // This is fine. The types are the same 🤷
    "./dist/cjs/languages/hljs/python.js": "./dist/cjs/languages/hljs/javascript.js",
    "./dist/cjs/languages/hljs/python": "./dist/cjs/languages/hljs/javascript.js",
    // …

    "./dist/cjs/languages/prism/javascript.js": "./dist/cjs/languages/prism/javascript.js",
    "./dist/cjs/languages/prism/javascript": "./dist/cjs/languages/prism/javascript.js",
    // This is fine. The types are the same 🤷
    "./dist/cjs/languages/prism/python.js": "./dist/cjs/languages/prism/javascript.js",
    "./dist/cjs/languages/prism/python": "./dist/cjs/languages/prism/javascript.js",
    // …

    "./dist/cjs/styles/hljs/a11y-dark.js": "./dist/cjs/languages/prism/a11y-dark.js",
    "./dist/cjs/styles/hljs/a11y-dark": "./dist/cjs/languages/prism/a11y-dark.js",
    // This is fine. The types are the same 🤷
    "./dist/cjs/styles/hljs/a11y-light.js": "./dist/cjs/languages/prism/a11y-dark.js",
    "./dist/cjs/styles/hljs/a11y-light": "./dist/cjs/languages/prism/a11y-dark.js",
    // …

    "./dist/cjs/styles/prism/a11y-dark.js": "./dist/cjs/languages/prism/a11y-dark.js",
    "./dist/cjs/styles/prism/a11y-dark": "./dist/cjs/languages/prism/a11y-dark.js",
    // This is fine. The types are the same 🤷
    "./dist/cjs/styles/prism/a11y-light.js": "./dist/cjs/languages/prism/a11y-dark.js",
    "./dist/cjs/styles/prism/a11y-light": "./dist/cjs/languages/prism/a11y-dark.js",
    // …

    "./dist/cjs/*.js": "./dist/cjs/*.js",
    "./dist/cjs/*": "./dist/cjs/*.js",
    "./dist/esm/*.js": "./dist/cjs/*.js",
    "./dist/esm/*": "./dist/cjs/*.js"
  }
}
```

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
100% agree with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69804#issuecomment-2176299808 and this package size needs to be reduced and used with wildcards to reduce the declares.

**Pull request closed without merging**
