### PR TITLE
[sequelize] change to use `this` type

### PR DESCRIPTION
**Pull request by horiuchi**
return `this` type on Instance and Model for TypeScript 1.7

### CODE REVIEW

**Comment by drinchev** [comment]
Do we have a way to merge the change but still make it backwards compatible with TS 1.6?

**Comment by horiuchi** [comment]
@drinchev No, this definition is only able to use above TS 1.7.

**Comment by drinchev** [comment]
:+1: although I can't test it with a big project, because I need to change a lot in my codebase. Looks like it will work properly and the tests are updated.

**Comment by horiuchi** [comment]
@drinchev Thanks for review! :+1:

**Pull request merged**
