### PR TITLE
chore: remove react-router & react-router-dom

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

react-router since 6.4.0:
https://unpkg.com/browse/react-router@6.4.0/dist/index.d.ts

react-router-dom since 6.0.0:
https://unpkg.com/browse/react-router-dom@6.0.0/index.d.ts

its a big one

as we already discussed (sanders), this is a combined PR just because the react-router tests are so unnecessarily intertwined with the react-router-dom types, its more effort to remove one at a time than both at once.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mirrorx ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mirrorx@latest/))
was missing the following properties:
1. Switch
1. Switch
## react-router-redux ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-router-redux@latest/))
was missing the following properties:
1. getLocation
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2947f39fb40a95a6bca6e28a96590d21bfa14de1
</p>

**Comment by 43081j** [comment]
did my best with the various readmes @sandersn - let me know if it seems right to you

i tried to pick a package that seems unlikely to be removed in the near future. it might be that this example just can't link anywhere eventually though once more packages start to ship types.

**Review by sheetalkamat — APPROVED** [review]

**Review by mykvas — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]

**Comment by jakebailey** [comment]
Per DT discord channel, were we leaning towards not using `notNeededPackages` here?

**Comment by 43081j** [comment]
I think so yeah unless @sandersn has any other thoughts? Happy to remove those

**Comment by jakebailey** [comment]
He's out, but I'm pretty sure they should just get deleted. We can add them later, or simply deprecate them by hand instead, which may work better.

**Comment by 43081j** [comment]
Sure, works for me. I'll update 👍

**Comment by 43081j** [comment]
@jakebailey i went ahead and removed the changes to the notNeeded list, would you mind re-reviewing?

**Review by jakebailey — APPROVED** [review]

**Comment by 43081j** [comment]
ready to merge 😰

**Pull request merged**
