### PR TITLE
Updated types for react-webcam

### PR DESCRIPTION
**Pull request by Englund0110**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mozmorris/react-webcam/releases/tag/1.1.1
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by squat** [comment]
Looks nice to me. One nit, can you squash your commits?

**Comment by Englund0110** [comment]
> Looks nice to me. One nit, can you squash your commits?

@squat Thanks!
I gave it a shot, but not sure i did it correctly..

**Comment by squat** [comment]
@Englund0110 hmm not quite, now there are 5 commits including one spurious merge commit.

**Comment by squat** [comment]
Here's a quick overview: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing. Please let me know if you need help :)

**Comment by Englund0110** [comment]
@squat I could use a little help. I haven't done it before. :-)

When i run git rebase -i master, the git-rebase-todo comes up, and i don't know what to do with it.  What i want to do is to collect all my commits into this (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34772/commits/af8ddd5a141055be2a3410871ed8de41fbcf557a?file-filters%5B%5D=) commit, right?

**Comment by squat** [comment]
yes, that's exactly it, for every line except for the first line, we want `squash` in the first column:

```commit
pick 5e106d718f Updated types for newest version of react-webcam
squash af8ddd5a14 Updated types for newest version of react-webcam
squash 7950dce04e Updated tests
squash b79d9d9536 Added newline to the end of file
```

**Comment by Englund0110** [comment]
I did exactly that, but now it says 8 commits?

**Comment by squat** [comment]
Not sure, but I think you might be rebasing against the wrong commit.

```shell
# First, ensure you're on your feature branch.
# Now make sure you are rebasing against upstream master:
git fetch git@github.com:DefinitelyTyped/DefinitelyTyped.git master:upstreammaster
git rebase -i upstreammaster
```

Then, make sure your todo looks like:
```
pick cf6bc99eb2 # This is a combination of 3 commits. # This is the 1st commit message:
s f3d4644007 Updated types for newest version of react-webcam
s 5e106d718f Updated types for newest version of react-webcam
s af8ddd5a14 Updated types for newest version of react-webcam
s 7950dce04e Updated tests
s b79d9d9536 Added newline to the end of file
```

```shell
# Cleanup the fetched branch:
git branch -D upstreammaster
# Force push your changes:
git push <YOUR-REMOTE-NAME> <YOUR-BRANCH-NAME> -f
```

**Comment by Englund0110** [comment]
@squat I think i managed to squash them! Thanks for guiding me. :-)

**Review by squat — APPROVED** [review]
LGTM

**Comment by Englund0110** [comment]
@squat One more question.. I just discovered that i proveded the wrong username in the contribution section (https://github.com/englund92 instead of https://github.com/englund0110)

Should i do a new PR to correct this?

**Pull request merged**
