### PR TITLE
Update types by HotModuleReplacement.runtime

### PR DESCRIPTION
**Pull request by pan-alexey**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

## DESCRIPTION
Current methods are located [here](https://github.com/webpack/webpack/blob/main/lib/hmr/HotModuleReplacement.runtime.js#L191) and [here](https://github.com/webpack/webpack/blob/main/lib/hmr/HotModuleReplacement.runtime.js#L192)

Implementation of the validation method [check]|(https://github.com/webpack/webpack/blob/main/lib/hmr/HotModuleReplacement.runtime.js#L259) always return Promise with [null](https://github.com/webpack/webpack/blob/main/lib/hmr/HotModuleReplacement.runtime.js#L269) or Array of modules

 Implementation of the validation method [apply]|(https://github.com/webpack/webpack/blob/main/lib/hmr/HotModuleReplacement.runtime.js#L309) always return Promise with Array of modules

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by gabritto — CHANGES_REQUESTED** [review]
is this change valid for version 1.16 of webpack's api? if not, we need to update the header of this file to reflect that as well.

**Comment by pan-alexey** [comment]
> is this change valid for version 1.16 of webpack's api? if not, we need to update the header of this file to reflect that as well.

Thank you very much for the note, updated the minor version

**Comment by gabritto** [comment]
Now that I've stopped to think about it, I realize I don't know what's going on with the versioning on this declaration file. The header says `// Type definitions for webpack (module API) 1.16`, so I'm assuming the types in this declaration should reflect the types of things in `webpack` on npm. Is that right?
However, there's no version 1.16 or 1.17 for webpack (the latest `legacy` version is 1.15), so I'm not sure which version of webpack this declaration is trying to reflect. Could you clarify? @pan-alexey

**Comment by pan-alexey** [comment]
> Now that I've stopped to think about it, I realize I don't know what's going on with the versioning on this declaration file. The header says `// Type definitions for webpack (module API) 1.16`, so I'm assuming the types in this declaration should reflect the types of things in `webpack` on npm. Is that right? However, there's no version 1.16 or 1.17 for webpack (the latest `legacy` version is 1.15), so I'm not sure which version of webpack this declaration is trying to reflect. Could you clarify? @pan-alexey

@gabritto thank you very much for your work.
[Webpack](https://www.npmjs.com/package/webpack) does not use [@types/webpack-env](https://www.npmjs.com/package/@types/webpack-env) as a dependency.

This change only affects the [@types/webpack-env](https://www.npmjs.com/package/@types/webpack-env) package. You correctly stated that it is necessary to raise the version of the modules, due to the fact that the changes may affect the compatibility of current packages with this dependency.

The package needed, in case of special use, to validate "Webpack module API - variables and global functions available inside modules"

Example (use global functions in modules)
https://github.com/facebook/create-react-app/blob/f99167c014a728ec856bda14f87181d90b050813/packages/react-dev-utils/webpackHotDevClient.js#L281

**Comment by gabritto** [comment]
I see, so `@types/webpack-env`'s version is not tied to `webpack`'s version, is that it?

**Review by gabritto — APPROVED** [review]

**Comment by pan-alexey** [comment]
Exactly

**Comment by pan-alexey** [comment]
Ready to merge

**Pull request merged**
