### PR TITLE
Updated type definitions to yFiles for HTML 2.0.0.1

### PR DESCRIPTION
**Pull request by martin-y**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://docs.yworks.com/yfileshtml/#/api/yfiles.view.GraphComponent
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Please update the tests and add tslint.json file

**Comment by martin-y** [comment]
@sheetalkamat Thanks for the hint. I've added a `tslint.json`, but could not get this to lint. 
Calling `tslint` from within the `yfiles` subdirectory gives me the following:

```
C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\yfiles>tslint index.d.ts

C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publisher\src\lib\header.ts:99
const separator: pm.Parser<string> = pm.regexp(/(, )|(,?\r?\n\/\/\s\s+)/);
                                        ^
TypeError: pm.regexp is not a function
    at Object.<anonymous> (C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publis
her\src\lib\header.ts:99:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publis
her\src\tslint\dtHeaderRule.ts:4:1)
    at Module._compile (module.js:570:32)
```

Apart from this error, I've tried linting with an clean lint ```tslint -init``` file and my expectations were met. Our TypeScript definitions file does *not* pass the linter tests in its current state. The file is generated from our library's source code and changing it manually is not feasible. We will need to adjust the generating code to make the definitions compliant with the linter tests. 
I'd be happy if we could defer this until the next (bugfix) release.

I'll look into the tests and add a few lines then. 

Thank you

**Comment by sheetalkamat** [comment]
Please run lint as mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped#lint 
``` npm run lint -- package-name ```

**Comment by andy-ms** [comment]
Linting isn't mandatory. But as @sheetalkamat mentioned, the lint errors are because we have custom lint rules, so it needs to be run using the installed linter in `DefinitelyTyped/node_modules`. Also, you can disable lint rules in your `DefinitelyTyped/yfiles/tslint.json`.

**Comment by martin-y** [comment]
@sheetalkamat @andy-ms Ok. I've been trying to run the linter as suggested, however I've run into the same problem on my machine. I've tried to uninstall the global ```tslint``` to be sure the local one is actually used.  Also I've cleaned the npm cache completely. 

```
C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\lodash>npm run lint -- lodash

> definitely-typed@0.0.1 lint C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped
> node scripts/lint.js "lodash"

node ../node_modules/tslint/lib/tslint-cli --format stylish "**/*.d.ts"

C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publisher\src\lib\header.ts:99
const separator: pm.Parser<string> = pm.regexp(/(, )|(,?\r?\n\/\/\s\s+)/);
                                        ^
TypeError: pm.regexp is not a function
    at Object.<anonymous> (C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publis
her\src\lib\header.ts:99:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\braun\Documents\DefinitelyTyped-DefinitelyTyped\DefinitelyTyped\node_modules\types-publis
her\src\tslint\dtHeaderRule.ts:4:1)
    at Module._compile (module.js:570:32)
```

I'm running windows 8, npm 3.3.4, node 6.9.4.
I've tried the same on a linux box and a colleagues windows box - here linting *worked*. Do you have an idea what could be the problem here?

**Comment by andy-ms** [comment]
Try `rm -r node_modules; npm install`? Looks like the version of `parsimmon` you have doesn't have `regexp`.

**Comment by martin-y** [comment]
It turned out the npm version was too old. With npm version 4.0.5 it works.

**Pull request merged**
