### PR TITLE
Update RetryStrategy types to match docs

### PR DESCRIPTION
**Pull request by dwrss**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/NodeRedis/node-redis#options-object-properties
- ~[ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- ~[ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed~.

Per the documentation, you can return any value from the `retry_strategy` function and that will cause the library to flush all offline commands with the standard error.

I've used `unknown` to represent this for ts3.1 but for 2.8 I've used `undefined`. This isn't technically correct, but I feel that it is more descriptive than widening the entire return type to `any`.

### CODE REVIEW

**Comment by 1pete** [comment]
Better add some tests
These are current ones
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dfa1dc8aa73e5a471edec18d7cd3ef94c1ca76ad/types/redis/redis-tests.ts#L28-L48
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dfa1dc8aa73e5a471edec18d7cd3ef94c1ca76ad/types/redis/ts3.1/redis-tests.ts#L28-L48

**Comment by Rokt33r** [comment]
@dwrss LGTM, but it would be nice to add some tests. I'll approve this PR after the tests are added.

**Comment by Rokt33r** [comment]
Also you can add your name in the def file. Thanks for the contribution. :)

**Comment by dwrss** [comment]
> @dwrss LGTM, but it would be nice to add some tests. I'll approve this PR after the tests are added.
Oops, I wrote them but apparently forgot to push them!

**Review by Rokt33r — APPROVED** [review]

**Comment by dwrss** [comment]
> @dwrss Everything looks good here. Great job! I am ready to merge this PR on your behalf.
> 
> If you'd like that to happen, please post a comment saying:
> 
> > Ready to merge
> 
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️

Ready to merge

**Comment by dwrss** [comment]
Ready to merge

**Pull request merged**
