### PR TITLE
Use types that come with @babel/parser and remove @types/babel__parser

### PR DESCRIPTION
**Pull request by mgroenhoff**
**Blocked by #27729**

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/babel/babel/pull/8170
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mgroenhoff** [comment]
Please don't merge yet! See #27729.

**Comment by christophehurpeau** [comment]
How can we help to get this merged ?

**Comment by mgroenhoff** [comment]
@christophehurpeau I am not sure you can do anything. I need #27729 to be sorted out first. Thanks though.

**Comment by nsemml** [comment]
Hey @mgroenhoff 
I blindly created the same PR #30515 , just noticed now that you have already addressed this. I wonder why this is supposedly blocked by #27729 - could you explain a bit?

**Comment by mgroenhoff** [comment]
@nsemml Well technically is should be possible to merge this without that issue being fixed so maybe it is a better idea to just have this merged.

The problem is that there's an issue with publishing some of the `@types/babel__*` packages that causes them to have some missing dependencies. It seemed a quick fix at first and I thought it would be better to wait because it needed to be published again but nothing would have been changed besides the automatically generated package.json file. It seems more people are starting to use these typings so I'll guess we don't want to wait on other issue being fixed anymore.

The PR for the root cause is here if you are curious: https://github.com/Microsoft/types-publisher/pull/502

**Comment by nsemml** [comment]
+1 for merging it now

**Comment by simondel** [comment]
Keep in mind that this change seems to break builds:
```
{ Error: Command failed: npm install
npm WARN deprecated @types/babel__parser@7.1.0: This is a stub types definition. babel__parser provides its own type definitions, so you do not need this installed.
npm ERR! code E404
npm ERR! 404 Not Found: babel__parser@*
```
(Source: https://travis-ci.org/stryker-mutator/stryker/jobs/456793587#L470)

**Comment by mgroenhoff** [comment]
@simondel Please replace `@types/babel__parser` with `@babel/parser` as indicated by the error. Then it should be fixed.

**Pull request merged**
