### PR TITLE
Fix Nightwatch getTitle type + this contexts

### PR DESCRIPTION
**Pull request by abauzac**
- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: http://nightwatchjs.org/api/getTitle.html
- [x ] Increase the version number in the header if appropriate.
- [x ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

More:
"this" contexts are based on comments documentation of the d.ts file

### CODE REVIEW

**Comment by Schlesiger** [comment]
Please don't disable the inherited tslint rules.

**Comment by QuantumInformation** [comment]
Do you need windows to run the ts tool?

**Comment by Schlesiger** [comment]
Are you referring to `dtslint`? It should work in all environments. In the `DefinitelyTyped` readme:

> Test by running `npm run lint package-name` where `package-name` is the name of your package. This script uses [dtslint](https://github.com/Microsoft/dtslint).

**Comment by QuantumInformation** [comment]
I just remember having a horrible time the last time I tried this on a mac. Has anyone managed to get it to run on a mac?

**Comment by QuantumInformation** [comment]
I referred to the tool that generated the index.d.ts or smth.

**Pull request merged**
