### PR TITLE
Add allowHalfOpen to Node's Duplex stream

### PR DESCRIPTION
**Pull request by pimterry**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  https://github.com/nodejs/node/commit/d14878dc7c6d23038b59e837fcd61f8b35fced30 (documentation only just merged, but supported in Node back to v0.9.4)

Note that unlike the other readonly Duplex properties this property _is_ writable. I've included a write in the tests to make sure nobody tries to helpfully fix that :smile:.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
> * documentation only just merged, but supported in Node back to v0.9.4

I think it means the change should be added supported versions (12/14)

**Comment by pimterry** [comment]
> I think it means the change should be added supported versions (12/14)

:+1: done

**Review by LinusU — APPROVED** [review]
👍

**Review by peterblazejewicz — APPROVED** [review]
@pimterry thx!

**Comment by pimterry** [comment]
Ready to merge

**Pull request merged**
