### PR TITLE
[types/trtc-js-sdk] fix: return types of checkSystemRequirements and mode

### PR DESCRIPTION
**Pull request by wkl007**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.html#.createClient>><<https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.html#.checkSystemRequirements>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by yokots** [comment]
@wkl007 请参照 [CHANGELOG](https://cloud.tencent.com/document/product/647/38958) 补全其他修改。

**Comment by wkl007** [comment]
好的 @yokots

**Comment by wkl007** [comment]
@yokots 已按照发布日志进行补全，同时完善了测试用例，麻烦Review一下。
以下是修改项对应的文档地址：
1. https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.html#.createClient
2. https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.html#.checkSystemRequirements
3. https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.Logger.html#.LogLevel
4. https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#subscribe
5. https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#unsubscribe
6. https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#startMixTranscode
7. https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#stopMixTranscode
8. https://trtc-1252463788.file.myqcloud.com/web/docs/module-Event.html#.CONNECTION_STATE_CHANGED
9. https://trtc-1252463788.file.myqcloud.com/web/docs/module-Event.html#.NETWORK_QUALITY
10. https://trtc-1252463788.file.myqcloud.com/web/docs/Stream.html#resume
11. https://trtc-1252463788.file.myqcloud.com/web/docs/TRTC.html#.createStream
12. https://trtc-1252463788.file.myqcloud.com/web/docs/module-Event.html#.PLAYER_STATE_CHANGED
13. https://trtc-1252463788.file.myqcloud.com/web/docs/Client.html#join
14. https://trtc-1252463788.file.myqcloud.com/web/docs/global.html#LocalVideoStats
15. https://trtc-1252463788.file.myqcloud.com/web/docs/global.html#RemoteVideoStats
16. https://trtc-1252463788.file.myqcloud.com/web/docs/Stream.html#play

**Review by yokots — APPROVED** [review]

**Comment by wkl007** [comment]
Ready to merge

**Pull request merged**
