### PR TITLE
[react-big-scheduler] Update prop types

### LINKED ISSUE #53375: Property missing in typescript
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/react-big-scheduler@0.2.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/react-big-scheduler/index.d.ts b/node_modules/@types/react-big-scheduler/index.d.ts
index 4001c51..18bf935 100644
--- a/node_modules/@types/react-big-scheduler/index.d.ts
+++ b/node_modules/@types/react-big-scheduler/index.d.ts
@@ -4,8 +4,8 @@
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // TypeScript Version: 2.8
 
-import * as React from "react";
 import * as moment from "moment";
+import * as React from "react";
 
 export default class Scheduler extends React.Component<SchedulerProps, any> { }
 
@@ -15,6 +15,10 @@ export interface SchedulerProps {
     nextClick(schedulerData: SchedulerData): void;
     onSelectDate(schedulerData: SchedulerData, date: string): void;
     onViewChange(schedulerData: SchedulerData, view: View): void;
+    eventItemClick: any;
+    eventItemTemplateResolver: any;
+    eventItemPopoverTemplateResolver: any;
+
 }
 
 export class SchedulerData {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #53375

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/StephenChou1017/react-big-scheduler#5schedulerproptypes>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by martin-badin** [comment]
@peterblazejewicz can you please review?

**Review by peterblazejewicz — COMMENTED** [review]
Do you think those newly added props are all required?
https://github.com/StephenChou1017/react-big-scheduler/blob/76796959de2f86303f9d036c28562203d442267b/src/EventItemPopover.js#L12-L25

**Review by FizzBuzz791 — APPROVED** [review]
Looks alright to me. ✅

**Comment by martin-badin** [comment]
> Do you think those newly added props are all required?
> https://github.com/StephenChou1017/react-big-scheduler/blob/76796959de2f86303f9d036c28562203d442267b/src/EventItemPopover.js#L12-L25

I think you are right. Thanks. I updated PR.

**Review by peterblazejewicz — APPROVED** [review]

**Review by FizzBuzz791 — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
