### PR TITLE
Add re-base@3.x type definitions

### PR DESCRIPTION
**Pull request by jordandrako**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by jordandrako** [comment]
I'd like to reference firebase types but not sure how to without the dependency, is there any way to do so without just giving empty objects as a generic replacement?

**Comment by DanielRosenwasser** [comment]
> I'd like to reference firebase types but not sure how to without the dependency

You can feel free to add the dependency so long as it's on [the whitelist](https://github.com/Microsoft/types-publisher/blob/master/dependenciesWhitelist.txt).
______

Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by DanielRosenwasser** [comment]
@jordandrako should I just merge this in?

**Comment by jordandrako** [comment]
@DanielRosenwasser Just did my first rebase to fix the author on the commits, hope I did it right. Turns out all the commits I was doing from VSCode were using my work email. Now I have one more commit to do and we should be good.

**Comment by jordandrako** [comment]
@DanielRosenwasser since firebase isn't in the whitelist (there's an outdated @types/firebase), I'm good to merge.

**Comment by DanielRosenwasser** [comment]
You'll need to send a follow-up PR; the latest (in v2) should be at the top level. The older versions (currently at the top level) should be moved into the `v1` folder.

**Comment by DanielRosenwasser** [comment]
Sorry I missed that.

**Comment by DanielRosenwasser** [comment]
Thanks for your patience!

**Pull request merged**
