### PR TITLE
Move types to `types` directory

### LINKED ISSUE #5040: Reorganize the repo?
Hey,

The current architecture for the repo does not really scale well for the number of typings there is now.
How about a a-z-other structure to clean it up a bit ?

I think I remember reading something about it but couldn't find the issue again

### PR DESCRIPTION
**Pull request by ghost**
Fixes #5040
All remaining pull requests (36 of them) will need to be rebased.
@sandersn Could you review this? I think this should preserve history, but not sure. http://stackoverflow.com/questions/10828267/can-git-restructure-my-folders-without-losing-history

Note: I have turned off types-publisher for now, as it will need to update after this to look in the new location.

### CODE REVIEW

**Comment by andy-ms** [comment]
Ignore test failures, will have to merge Microsoft/types-publisher#299 before test work.

**Comment by sandersn** [comment]
Can you merge it ahead of this, or would it break on the existing structure?

**Comment by andy-ms** [comment]
I guess if it's turned off I can merge. But it will try testing *all* packages and time out anyway, since every file is in the diff.

**Comment by sandersn** [comment]
Why check in mv.ts if it's single use? As a historical artifact?

**Comment by andy-ms** [comment]
Nope, just forgot.

**Review by sandersn — APPROVED** [review]
It seems ok to me.

**Comment by sandersn** [comment]
Note that 249 lines were added and 249 removed. Sounds like some kind of newline normalisation to me, but I don't have a good way to find out. I guess `git log --stat` after the fact would work.

**Comment by andy-ms** [comment]
@sandersn You're right, newlines hopefully fixed by #15369

**Pull request merged**
