### PR TITLE
[d3-axis] Add case tickFormat string

### PR DESCRIPTION
**Pull request by borracciaBlu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Simple graph with grid lines](https://bl.ocks.org/d3noob/c506ac45617cf9ed39337f99f8511218)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by borracciaBlu** [comment]
Hi all not sure dt-bot did work, in case of duplicate please ignore. 
 
@tomwanzek @gustavderdrache @borisyankov - please review [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24716) in the next few days. 

Thanks

**Comment by tomwanzek** [comment]
@borracciaBlu We already have a larger PR involving d3-axis under discussion, see #24305. I would prefer, if as present, we roll any discussed change, such as the above into the open PR as an additional change consideration.

**Review by tomwanzek — CHANGES_REQUESTED** [review]
See comment in the main conversation threat.

**Comment by borracciaBlu** [comment]
@tomwanzek i saw the other PR and this case it is not covered there. I think the two PR are orthogonal actually.

If you like I can PR to  denisname:d3-format-strictNullChecks branch, but i think we would lose granularity. Let me know in case.

**Comment by tomwanzek** [comment]
@borracciaBlu Apologies for the delay in getting back to this.

The API (and the internal source code behaviour) for [_axis_.tickFormat(...)](https://github.com/d3/d3-axis/#axis_tickFormat) is clear: the argument is either a formatter-function or `null`. A format specifier string is not permissible in this case.

Rather than formatting the tick marks, the format specifier string itself would appear on the tick.

So no change required here.

**Comment by borracciaBlu** [comment]
Sorry @tomwanzek but I'm a little bit confused. Help me to understand, please.

**About the case:**
> Rather than formatting the tick marks, the format specifier string itself would appear on the tick.

Well, it would appear in the `text` tag.

So, let say you have a tick like that.

    <g class="tick" opacity="1" transform="translate(0,26.1251669993556)">
        <line stroke="#000" x2="-6"></line>
        <text fill="#000" x="-9" dy="0.32em">600</text>
    </g>

With `tickFormat('')` we would have:

    <g class="tick" opacity="1" transform="translate(0,26.1251669993556)">
        <line stroke="#000" x2="-6"></line>
        <text fill="#000" x="-9" dy="0.32em"></text>
    </g>

That's what I do for horizontal grid only.

With the current signatures I have to use `.tickFormat(() => { return ''; })` when before I could do It with `tickFormat('')`.

**About the code:**
> axis.tickFormat(...) is clear: the argument is either a formatter-function or null. 
> A format specifier string is not permissible in this case.


  **In the `d3-axis` code I see:**
  https://github.com/d3/d3-axis/blob/master/src/axis.js#L137
      
     axis.tickFormat = function(_) {
          return arguments.length ? (tickFormat = _, axis) : tickFormat;
     };

  What it does is if there are arguments set `tickFormat` with and then return `axis`.
 
  If the intent was to allow only functions or null wouldn't we have something like
  `if (_ === null || typeof _ === 'function')`? Are the assumptions done correctly?


  And then we got
  https://github.com/d3/d3-axis/blob/master/src/axis.js#L49
     
    format = tickFormat == null ? (scale.tickFormat ? scale.tickFormat.apply(scale, tickArguments) : identity) : tickFormat, 

  which set `format` to tickFormat if not `null` and then use it in `text(format)`.

  https://github.com/d3/d3-axis/blob/master/src/axis.js#L107
      
    text
        .attr(x, k * spacing)
        .text(format);

  In `text()` I can't see anything that stops from using `strings`.
  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-selection/index.d.ts#L427
  
    text(value: string | number | boolean): this; 

So, what's exactly the logic for which `format specifier string is not permissible` in this case?  
Can you explain me please?

Thanks for your help

**Comment by tomwanzek** [comment]
In order to "deactivate" the tickmark labels, please simply use: `.tickFormat(() => '')`. As a matter of general principle, the TS definitions are written to conform to the _documented_ API. The documented API in this case refers to:

> ...sets the tick format function...

Staying away from undocumented source code behaviour in the TS definitions ensures that changes to internal implementations details of the source code do not break the definitions.

Since the general broadening of the signatures to `string` to address the edge case of disabling tick mark labels with `''`, portrays a capability that is not in the spirit of the axis, widening it seems misguided.

It would be too easily confused with the behavior of the `scale.tickFormat(...)` functions, which actually _do_ expect a form specifier string.

**Comment by borracciaBlu** [comment]
Thanks 

Regards

**Pull request closed without merging**
