### PR TITLE
fix(ioredis): allow RedisOptions.retryStrategy to return false

### PR DESCRIPTION
**Pull request by satoshun00**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/luin/ioredis/tree/master#auto-reconnect
  - > When the return value isn't a number, ioredis will stop trying to reconnect
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by plantain-00** [comment]
👍 thanks.

**Comment by andy-ms** [comment]
Seems like the type should be `number | false`? Even if it's technically allowed at runtime to return a `Date`, it will be treated exactly like `false` anyway.

**Comment by satoshun00** [comment]
@andy-ms 
This make sense to me. Fixed.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
