### PR TITLE
Add gtag.js type definitions

### LINKED ISSUE #23718: Add gtag to google.analytics types
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @FreshRob @andy-ms @Tyler-Murphy @Calvin-Huang @patkujawa-wf 

It's only been a few weeks, but it looks like Google is now using a different script and syntax for Google Analytics. Here's the migration guide: 

https://developers.google.com/analytics/devguides/collection/gtagjs/migration

### PR DESCRIPTION
**Pull request by Rokt33r**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23718.

### CODE REVIEW

**Review by rbuckton — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by sbilstein** [comment]
I was just looking for this! Thanks :)

**Comment by ChrisProlls** [comment]
Hi !
Is it a minimum TS compiler version needed to use this package ?
VS Code with TS 3.3.3 pass the compilation but Angular with TS 2.9.2 didn't pass the compilation ...

**Comment by chriscarpenter12** [comment]
I'm seeing an issue too with Intellij not detecting the `gtag` type. Project is using: `"typescript": "~3.2.4"`

**Comment by NevenLiang** [comment]
@Rokt33r Should `gtag` not be exported in the type definition file? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gtag.js

**Pull request merged**
