### PR TITLE
[ramda] ran dprint fmt

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
👋 Hi! This PR is meant to let you know that we're going to be applying formatting automatically to all DefinitelyTyped packages[^1]. This PR is split out of:

* https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993: the discussion that includes backing context and our planned approach
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66235: onboards the repository to [dprint](https://dprint.dev)

This package is particularly huge (>1MB), so we're tagging you in an individual PR as a heads up. Please post here to let us know if you have any workflow needs that auto-formatting might disrupt[^2].

Cheers! 💖 

```shell
time npx dprint fmt types/ramda/**/*.t*
Formatted 749 files.
npx dprint fmt types/ramda/**/*.t*  0.73s user 0.46s system 131% cpu 0.911 total
```

[^1]: Note that formatting will be applied as a commit to `master` after each PR. PRs won't be blocked on any CI check for proper formatting. See #65993 for more information.
[^2]: For example, if this package is fully auto-generated (rather than manually edited), subsequent PRs might have a lot of noise from formatting differences. We can exclude it from formatting in that case.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. addIndexRight
1. sequence
1. unwind
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9738af1160403f8d93a4e747e93caeb2edc407d1
</p>

**Review by Nicholaiii — COMMENTED** [review]
I don't see any issues with the changes.

**Comment by JoshuaKGoldberg** [comment]
Swell, thanks! Could I ask you to approve the PR please?

Instead of closing these individual ones out I'm going to start merging them in individually. That way we can get early testing of formatted packages, and revert individually if we need.

**Review by Harris-Miller — APPROVED** [review]

**Comment by Harris-Miller** [comment]
@JoshuaKGoldberg Sorry for the delay. Approved. Let me know when the merge conflicts are resolved and I'll merge

**Review by Harris-Miller — APPROVED** [review]

**Comment by Harris-Miller** [comment]
Ready to merge

**Comment by JoshuaKGoldberg** [comment]
I think there's a bug somewhere in the tooling, this does touch test files... 🤔

**Comment by JoshuaKGoldberg** [comment]
Ready to merge

**Comment by Harris-Miller** [comment]
ready to merge

**Review by gabritto — APPROVED** [review]

**Comment by gabritto** [comment]
The PR needed a maintainer approval (probably because it edits more files than the bot can check 😅). Self-merge should work now.

**Comment by JoshuaKGoldberg** [comment]
Ah swell thanks!

**Comment by JoshuaKGoldberg** [comment]
Ready to merge

**Pull request merged**
