### PR TITLE
[react-native] Add react native v0.63

### PR DESCRIPTION
**Pull request by rurikoaraki**
The aim of this change is to add back a version of @types/react-native for 0.63. There is a fix that has been committed since the bump to 0.64 that I would like to be able to get, but the project I am working on is still on RN 0.63 and cannot bump to 0.64 yet. Based on the README, it seems that I can add support for an old version by adding a new directory, however since React Native's versioning is a bit weird (only bumping minor numbers), I'm not entirely certain if it will work (every other project with this kind of old versioning is based off a major number difference). If this looks hairy, let me know and I can abandon the PR.

This change was created by taking what existed when dd4bf52c0b1d72af91229550cc5836b5d08240b1 was committed, and then evaluating each change after that for whether it applied to 0.63.

The changes that I've ported to the 0.63 version are:
- 79b925e4f8f6d9a3dc2e8e6547a0a36726ce700c
- f667cb08e57c6d5633d48ede6c031b876d5e13f9
- a0e371c03a53801ccefe6952f5325cbbb4bb99aa
- 3794d3d69b00ecea3fda9fdc2f30cd38ba6718a2
- 4c51edf60efbba4e6d2b37b8551c057bc8bb1b31
- 33c8583428feaa42e0f1a19d06bd28b237b69ff4

Changes that were not ported are:
- dab080d9fe9fa3f47e40640881c1981db5a96c30
- 2040d5853a5f16d93a6284ee00e49fbd4a6d21e4
- c8a6eead330fa55cb1cba84778b05562d2afe45e
- 146a091fcfa9dd3f0c08075ead83eb32ca106de1
- 6fbb351aad45f0da8d18ec4c9838cf783f602640
- a7a68fc62820e1323e28d830e559adffdb8d915e

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
    - The v63 has 0.63 in the header as the version.

### CODE REVIEW

**Comment by rurikoaraki** [comment]
Abandoning as the tooling seems like it's not working with adding an old version that has a minor number

**Comment by RyanCavanaugh** [comment]
Last call before I approve this for merging

**Comment by ca057** [comment]
> Last call before I approve this for merging

If this method is a common way of solving this issue, I’m happy merging it! I don’t have capacity to perform a full in-depth review though. 👍

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by rurikoaraki** [comment]
Ready to merge

**Pull request merged**
