### PR TITLE
Node: specify `UnhandledRejectionListener` `reason` param type

### PR DESCRIPTION
**Pull request by OliverJAsh**
5th attempt at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33189

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]

**Comment by OliverJAsh** [comment]
The build failure has nothing to do with these changes.

**Review by BrunoScheufler — APPROVED** [review]

**Comment by OliverJAsh** [comment]
The build failure has nothing to do with these changes.

**Comment by SimonSchick** [comment]
I still don't understand the motivation behind making *specifically* `unhandledRejection` use the `poor mans unknown` as it it's in no way consistent with the rest of node typings.

I think it would be more worthwhile to push for the use of `unknown` in TS 3.1+ and squash the `any`s on a more fundamental level.

**Comment by OliverJAsh** [comment]
> I still don't understand the motivation behind making _specifically_ `unhandledRejection` use the `poor mans unknown` as it it's in no way consistent with the rest of node typings.

To be honest, it's just because it's precisely what I needed—nothing more or less. Focusing on my needs is the only way I'm able to find the time to make contributions to these typings, and I'm sure the same goes for many other maintainers.

> I think it would be more worthwhile to push for the use of `unknown` in TS 3.1+ and squash the `any`s on a more fundamental level.

I don't know what needs to happen for this, but if there's a process I can follow, I'm happy to pursue that avenue!

**Review by Flarna — APPROVED** [review]

**Pull request merged**
