### PR TITLE
[react-native] Image.source is optional

### PR DESCRIPTION
**Pull request by danilobuerger**
See https://github.com/facebook/react-native/blob/main/Libraries/Image/ImageProps.js#L154

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/main/Libraries/Image/ImageProps.js#L154
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]

**Comment by MateWW** [comment]
@danilobuerger Does it makes sense to have image component without source? I understand that it will be compliant with flow types but on the other hand DX will be impacted. WDYT?

**Comment by danilobuerger** [comment]
@MateWW in my opinion it makes perfect sense together with the default source. If I am fetching the source from remote where it might be nullish, I can just pass it in and the default source will be displayed. For example an user avatar. The user either has one or not. I can just pass in the url or nullish and it will either show the avatar or a placeholder.

**Comment by eps1lon** [comment]
> Does it makes sense to have image component without source defined? I understand that it will be compliant with flow types but on the other hand DX will be impacted. WDYT?

I would suggest opening against the flow-types if it's unclear.

**Comment by MateWW** [comment]
> @MateWW in my opinion it makes perfect sense together with the default source. If I am fetching the source from remote where it might be nullish, I can just pass it in and the default source will be displayed. For example an user avatar. The user either has one or not. I can just pass in the url or nullish and it will either show the avatar or a placeholder.
> 
> 

Okat got you but even when source is asynchronous syntax like <Image /> makes no sense. I think we should add undefined | null to type instead making this optional. Finally it will complain about missing property but will accept null and undefined what seems to fit with this use case.

@eps1lon i don't know flow tbh. Is it possible to achieve that difference between { foo?: string } and { foo: string | undefined } in flow?

**Comment by danilobuerger** [comment]
> I think we should add `undefined | null` to type instead making this optional.

I do agree with you in general. However, it is not our place here to put our own opinions into it. The flow types of RN are the source of truth, if they allow it so should the ts types. The ts types should just copy the flow types. If you think a missing source makes no sense, you should PR the flow types first. (I think this is what @eps1lon is suggesting too).

**Comment by MateWW** [comment]
> @danilobuerger together with @jaworek we have tested wheather flow can detect that and it seems that for flow there is no difference between `foo?:bar` and `foo: bar | void` whereas in typescript syntax like `foo: bar | null | undefined` requires user to strictly define that value. Regarding that I would really love to have typescript version of react native being better then default one. 
If you want to play with that a little bit you can check [this example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhlosATOAUwGcwA7OAFzAAsBDAN0LAAMBXMvQqASzMLwswlAJ4AHQgBowGLJRptSPaj1IVqYuMWI8ARjGaU4YAE6ExMHgGM6lQzWbE6AW2a7C9BjzhsTYOkpkYAAqAMrSsmAIDmZgIj5gNkHOdCYA1v4mAOZsrmTUAawAkilZhKE+JlaEAAomcGLB4swAPmAcXLz8gjKY-pxgylE8MDCmhACObDyxioR+RmBiAaTEcK7yfFnCxlAcVpTeQXB+Vuua-PnoohJgJXRlFb7VdQ1NtwC8YADexFUAXGBiJQTFtpHQYJRAcDQWQsgBfADc6D2ZAOR2wcDgAAoAB6AgD890elRe9UazQAlNCQVsfqgwIMoGA8ZT6YzGWZKL4griAHRGUK0uHYynIxnwhnjbkmIIAIk6dDYkKBwqycuRktQqPRcCCUCxACY8YDieVSbVye9WmAGHAeHhqarYdtvlKeMzWeyOVyeWB+YK1aLxWBJZzCDL5YrldQYVsNagtX0hqollodPpDMYzBZrLZHDxnCNUmB3J5vL5hvJWGRlTAWNJdGxqJtSAgRmN1LQ6JwDIkAiRJJFovNmAa-IRcS4LMxCw9mHhbHRBqQoBGrA48Nh6s5hA4gfMmH4e1uU4FlDwITARKwOtw+AIG5EmwUoHY-GtXMJC8xlto6e2ozjGsMBMDsxSlOazyWm8zQsNq+yHHqmJwAAzCadyQU8VQwRStxtLWoxOnGcLeh6LK4myboctKfoBnAQousGUphrRspgAq3BKiqJHqpqKJYsx2pGkJBpocGQA).
What do you think?

**Review by MateWW — APPROVED** [review]

**Comment by danilobuerger** [comment]
Ready to merge

**Pull request merged**
