### PR TITLE
update: socket.io-client 4.0.0

### PR DESCRIPTION
**Pull request by SeregaSE**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://socket.io/docs/v3/client-initialization/#extraHeaders and https://socket.io/docs/v3/client-initialization/#withCredentials
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by SeregaSE** [comment]
Hello, also i think about replace `Object` type to `Record<string, string>` or `Record<string, any>`, what could you say?

For example `extraHeaders?: Record<string, string>;` or `Record<string, number | string>`  or `Record<string, any>` or `Record<string, unknown>`

**Comment by AviVahl** [comment]
Package actually has built-in types now. We use it in a strict typed project without any @types being required.
So DT types should probably be removed, as the built-in types get precedence anyhow.

**Comment by SeregaSE** [comment]
so, can i remove this package?

**Comment by AviVahl** [comment]
see info at https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by memark** [comment]
@SeregaSE Socket.io-client 4.0.0 already has types built in.

In fact I have an ongoing PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52719) to remove this package altogether.

This PR should be closed.

**Pull request closed without merging**
