### PR TITLE
Added Type Definitions for EliteBGS

### PR DESCRIPTION
**Pull request by SayakMukhopadhyay**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

N.B. The typings are standalone as a npm package is not available. This is because the typings are helpful for consumers of a REST API. Thus the project was created manually and not through `dts-gen`

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Need more info. There is no package with name elitebgs.

**Comment by SayakMukhopadhyay** [comment]
I have already added info in my first comment. To reiterate, this typings package is for a project which serves a REST API. Consumers using this REST API (including one of my other project) would greatly benefit from having typings to the response received.
The REST API project is on github https://github.com/SayakMukhopadhyay/elitebgs but does not necessitates an npm package.

**Comment by sheetalkamat** [comment]
I pinged @andy-ms offline and he recommends: 
> He could just publish an NPM package himself containing the types he wants. There's no need for it to have an `@types/` prefix to be usable.

**Comment by SayakMukhopadhyay** [comment]
Well, if there is any policy that does not allow types where an npm package does not exist, I will publish it to npm. But using the `@types` prefix has become a norm and it would be great if my types were present in it too. Kindly close the issue if there is no way this is getting published by definitely typed. I will move to creating an npm package.

**Comment by andy-ms** [comment]
> But using the @types prefix has become a norm

I don't think this should become the norm. `@types/foo` should be the fallback for when `foo` doesn't provide its own types; but if you've created something new and are wondering where to publish it, definitely go with NPM directly instead of DefinitelyTyped.

**Pull request closed without merging**
