### PR TITLE
update draft-js.d.ts

### PR DESCRIPTION
**Pull request by baoziv587**
just export namespace Draft

### CODE REVIEW

**Comment by andy-ms** [comment]
Link to docs that show that it's a global?

**Comment by baoziv587** [comment]
Okay, but I can not find where the document is。

**Comment by baoziv587** [comment]
In my opinion, according to the draftjs source code should look like this, react.d.ts, react-dom.d.ts also export global namespace

**Comment by andy-ms** [comment]
Could you check that the global variable is accessable to you at runtime? I.e., open the browser console and inspect `window.Draft`.
When I look at the source code installed from NPM, I see a UMD-style header with `root.draft = factory();` in the global case. That implies that this should use `draft` instead of `Draft` for the name of the global.

**Comment by baoziv587** [comment]
####  `from draftjs/dist/Darft.js`

/**
 * Draft v0.9.1
 *
 * Copyright (c) 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
var Draft =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */


we can see   var Draft

**Comment by baoziv587** [comment]
We can see   var Draft.
And I will check it later in the browser

**Comment by baoziv587** [comment]
image

**Pull request merged**
