### PR TITLE
React native: Add missing props to VirtualizedList 

### PR DESCRIPTION
**Pull request by aliakbarazizi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://reactnative.dev/docs/virtualizedlist#itemseparatorcomponent)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Just missing formatting fixes:

```
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react-native/index.d.ts:4550:1
ERROR: 4550:1  no-trailing-whitespace  trailing whitespace
ERROR: 4556:1  no-trailing-whitespace  trailing whitespace
ERROR: 4562:1  no-trailing-whitespace  trailing whitespace
ERROR: 4567:1  no-trailing-whitespace  trailing whitespace
ERROR: 4573:1  no-trailing-whitespace  trailing whitespace
```

Rest looks good, thanks 👍🏻

**Review by iRoachie — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]

**Comment by lunaleaps** [comment]
@aliakbarazizi Can you also add these to `react-native` : https://github.com/facebook/react-native/tree/main/types

**Review by gabritto — APPROVED** [review]

**Comment by lunaleaps** [comment]
If this lands before https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63276, will update

**Comment by eps1lon** [comment]
Ready to merge

**Comment by aliakbarazizi** [comment]
> @aliakbarazizi Can you also add these to `react-native` : https://github.com/facebook/react-native/tree/main/types

Done.

**Pull request merged**
