### PR TITLE
[npm:@types/iyzipay] Updated some of the interface names & Exported all Interfaces in the namespace

### PR DESCRIPTION
**Pull request by cangokceaslan**
I am the only owner of this declaration file. I have made some changes regarding usage of [@types/iyzipay
](https://npmjs.com/package/@types/iyzipay)

- [X] Updated some of the interface names
- I have deduplicated namings of some interfaces. None of my changes affects the main structure

- [X] Exported all Interfaces in the namespace
- I have done this change because we may need to use Enums', Requests' and Methods' Interfaces

- [X] Optional to email in BuyerDetails interface. 
- Because It wasn't required

- [X] pnpm dprint fmt runned for formatting
- DangerBot suggested formatting. It is done.

Thank you for your review

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/iyzipay/iyzipay-tests.ts
1. types/iyzipay/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b8733078c451cb723ff12183d7c320ef15928128
</p>

**Review by peterblazejewicz — APPROVED** [review]
That's right direction changes ('I' is not really readable, being also a convention from outside of JS/TS world).

**Comment by cangokceaslan** [comment]
Ready to merge

**Comment by cangokceaslan** [comment]
> That's right direction changes ('I' is not really readable, being also a convention from outside of JS/TS world).

Thank you for your comment.

It was a old mistake I have been making. I learnt lots of new ways of managing a multi-developer project from the contribution, surely.

I will provide more d.ts's I have already written and maintained under the project. I will move them to this awsome project.

So thanks.

**Pull request merged**
