### PR TITLE
Highcharts definition non-instantiated

### PR DESCRIPTION
**Pull request by subash-a**
Improvement to existing type definition of Highcharts
- Using Ghost modules based on discussion in Issue #10597 
- Moved all global interfaces into a namespace
- Created a __Highcharts namespace for using in dependent files
- Changed references in dependent files and tests

### CODE REVIEW

**Comment by subash-a** [comment]
@vvakame sorry to have tagged you for the review, I was not entirely clear on who should be taking a look at this PR since it is supposed to go into the `types-2.0` branch, I would appreciate if someone could point me in the right direction on who I need to tag in my PR's which are intended for `types-2.0`, what are the steps to get a PR merged and if these changes will be a part of the master branch as well.

**Comment by andy-ms** [comment]
If your PR is 2.0-specific, target `types-2.0`. Otherwise, target `master` and we will manually merge changes from there to to `types-2.0` in about a week. As for who to tag in your PRs, it would be ideal to tag a previous author of the package (@dt-bot should do this automatically). If not, we are working to clear out our backlog of nearly 100 PRs, so please be patient.

**Comment by subash-a** [comment]
@andy-ms thanks for the quick response on that one, yes my PR is targeted at the `types-2.0`, happy to wait and get it merged.

**Comment by andy-ms** [comment]
Pinging @damianog and @baltie to help with review.

**Comment by subash-a** [comment]
thanks @andy-ms just a note, there is nothing `types-2.0` specific about the my PR and would like to get some suggestion on which approach is better, getting it merged to `master` first or getting it on the `types-2.0`? Also would appreciate if someone from the Typescript team could just give this PR a quick look and tell me if the type definition structure looks ok.

**Comment by andy-ms** [comment]
The structure looks good. You might also consider using module augmentation: if you `declare module "highcharts"` in multiple files the definitions should be combined, just like they are for a namespace. I'm not sure which one is better (CC @RyanCavanaugh).

If there's nothing 2.0-specific about this, it should be rebased onto master.

**Comment by subash-a** [comment]
@andy-ms based on your suggestion I have created a PR against the `master` branch #11385 which can be reviewed and merged into master and further discussion about improving the structure can be continued there.

**Pull request closed without merging**
