### PR TITLE
feat(hapi): v19

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/hapi/issues/4017
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

The hapi ecosystem is very slowly moving to TS, some of the packages already ship their own types, some don't.

This PR removes some of the packages from DT while updating hapi to v19

Depends on https://github.com/microsoft/types-publisher/pull/726

### CODE REVIEW

**Comment by SimonSchick** [comment]
cc @hueniverse I think I got all the packages that you added types to.

**Review by lenovouser — APPROVED** [review]
Nice to see some packages shipping their own types by now 👍🏻

**Review by saboya — APPROVED** [review]

**Review by feinoujc — APPROVED** [review]

**Comment by OneHoopyFrood** [comment]
Thank you for doing this @SimonSchick! 

Could you maybe answer a question for me? Why is there a `@types/hapi` and also a `@types/hapi__hapi`?

**Comment by lenovouser** [comment]
@OneHoppyFrood `@types/hapi` -> `hapi` and `@types/hapi__hapi` -> `@hapi/hapi`

`@types/hapi` is not needed anymore basically

**Pull request merged**
