### PR TITLE
react-router: Link inherit HtmlAttribute for use with className and style

### PR DESCRIPTION
**Pull request by benishouga**
Following in the document of Link.

> ### Other
> 
> You can also pass props you'd like to be on the <a> such as a title, id, className, etc.

https://rackt.github.io/react-router/#Link

### CODE REVIEW

**Comment by vvakame** [comment]
*react-router/react-router.d.ts*

to authors(@mrk21 @vasek17). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mrk21** [comment]
@benishouga @vvakame :+1:

**Comment by vasek17** [comment]
:+1:

**Comment by vvakame** [comment]
@mrk21 @vasek17 thanks!
@benishouga thanks mate!

**Pull request merged**
