### PR TITLE
Updating Titanium Definitions to 3.5.0

### PR DESCRIPTION
**Pull request by cyounkins**
cyounkins forked airamrguez's original repo to update it and regenerate the definitions for the latest API version. See https://github.com/cyounkins/titanium-typescript

### CODE REVIEW

**Comment by vvakame** [comment]
@cyounkins could you review this PR?

**Comment by cyounkins** [comment]
@vvakame I think you missed that I wrote the PR.

Two questions with the PR:
- the namespace Titanium is aliased to Ti in API documentation, but I'm not sure how best to do that in these definitions. Doing 'declare type Ti = Titanium;' but I get 'error TS2304: Cannot find name 'Titanium'.'
- Is it OK that there are multiple top-level classes in the definitions (ex: DecodeNumberDict, CloudChatGroupsResponse) or should those be under the Titanium module?

**Comment by vvakame** [comment]
@cyounkins wow, sorry! 

* `import Ti = Titanium;` ?
* it is okey that If it exists in top-level in fact.

**Comment by vvakame** [comment]
@cyounkins It merged. If you have another improvement, please send a PR again.

**Pull request merged**
