### PR TITLE
[obs-studio] add removeEventListener definitions

### PR DESCRIPTION
**Pull request by VodBox**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes:
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by domdomegg — APPROVED** [review]
LGTM. This comes in from Chromium via the CEF.

I guess there's also a question here about whether we also add the other window properties i.e. most of the dom? Would that be useful to developers?

**Comment by VodBox** [comment]
> I guess there's also a question here about whether we also add the other window properties i.e. most of the dom? Would that be useful to developers?

@domdomegg I'm unsure why that's necessary? The rest of the DOM API is left untouched, and so developers can just rely on the lib.dom.d.ts definitions already provided by TypeScript.

**Comment by VodBox** [comment]
Ready to merge

**Comment by domdomegg** [comment]
> > I guess there's also a question here about whether we also add the other window properties i.e. most of the dom? Would that be useful to developers?
> 
> @domdomegg I'm unsure why that's necessary? The rest of the DOM API is left untouched, and so developers can just rely on the lib.dom.d.ts definitions already provided by TypeScript.

You're exactly right, my bad. Thanks for the PRs. :)

**Pull request merged**
