### PR TITLE
[NEEDS HELP] @sanity/base types

### PR DESCRIPTION
**Pull request by saiichihashimoto**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by saiichihashimoto** [comment]
I need help to move forward!!!!

When testing this locally, I get this error:
```
npm test @sanity/base                                                                                     9s  ⇣ master :: 2h :: ⬡

> definitely-typed@0.0.3 test /Users/saiichi/Workspace/DefinitelyTyped
> dtslint types "@sanity/base"

dtslint@0.0.112
Error: Errors in typescript@4.7 for external dependencies:
node_modules/@popperjs/core/lib/types.d.ts(28,30): error TS2304: Cannot find name 'getComputedStyle'.
node_modules/@popperjs/core/lib/types.d.ts(33,11): error TS2304: Cannot find name 'Node'.
node_modules/@popperjs/core/lib/types.d.ts(37,17): error TS2304: Cannot find name 'ShadowRoot'.
node_modules/@popperjs/core/lib/types.d.ts(77,32): error TS2304: Cannot find name 'CSSStyleDeclaration'.
node_modules/@popperjs/core/lib/types.d.ts(164,34): error TS2304: Cannot find name 'ClientRect'.
node_modules/@popperjs/core/lib/types.d.ts(164,47): error TS2304: Cannot find name 'DOMRect'.
node_modules/@sanity/ui/lib/dts/src/helpers/scroll.d.ts(4,43): error TS2304: Cannot find name 'Node'.
node_modules/@sanity/ui/lib/dts/src/hooks/useElementRect/useElementRect.d.ts(5,70): error TS2304: Cannot find name 'DOMRectReadOnly'.
node_modules/@sanity/ui/lib/dts/src/utils/resizeObserver.d.ts(4,26): error TS2304: Cannot find name 'ResizeObserver'.

    at testTypesVersion (/Users/saiichi/Workspace/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/Users/saiichi/Workspace/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:170:13)
    at async main (/Users/saiichi/Workspace/DefinitelyTyped/node_modules/@definitelytyped/dtslint/dist/index.js:79:9)
npm ERR! Test failed.  See above for more details.
```

I have no idea how to have dependent types properly. These are all coming from my dependencies's dependencies. What should I be doing here? None of the documentation seems to call this out unless I'm missing something.

**Comment by saiichihashimoto** [comment]
I haven't been able to add tests properly, since I can't get the tests to run whatsoever. After I get help solving this, I can write proper tests!

**Review by andrewbranch — CHANGES_REQUESTED** [review]
@sanity/base already ships types, so unless this PR reflects some kind of very special circumstance, we’re not going to be able to accept it.

@sanity/base on npm has types

**Comment by saiichihashimoto** [comment]
@andrewbranch It is a special circumstance!

https://www.sanity.io/docs/using-typescript-in-sanity-studio

Sanity essentially handles enough typescript to type everything as `any`, which is to say it doesn't support typescript.

Here's a few issues showing that they don't:
https://github.com/sanity-io/sanity/issues/2709
https://github.com/sanity-io/sanity/issues/1857

**Comment by saiichihashimoto** [comment]
They also come with their own bizarre import paths (you can see from the module names I declared) which need to be properly typed. I'm not sure of any developers from @sanity-io that can confirm, but they definitely don't have types for sanity schema configs.

**Comment by andrewbranch** [comment]
The problem is that TypeScript is going to resolve to the broken, incomplete types in `@sanity/base` with a higher priority than `@types/sanity__base`, so unfortunately adding these on DefinitelyTyped just won’t actually help the situation. It is a serious bummer when a package ships extremely bad types, because they block helpful community members like yourself from being able to improve the situation by contributing to DT. I wish we could help, but unfortunately I think the only thing you can do is to try to get the implementation package to ship better types or get them to _stop_ shipping types at all, so you can add them here. ☹️

**Comment by saiichihashimoto** [comment]
@andrewbranch is this still true if we're importing from names like `part:@sanity/base/schema-creator` (which is how their system works)? Even though it technically comes from `@sanity/base`, their "parts" system ends up with importing from these somewhat madeup paths, which is another reason we want these types. Will incomplete types in `@sanity/base` also override these types that this PR would define?

**Comment by andrewbranch** [comment]
Hm, no, if the module name can’t actually be resolved via a normal filesystem lookup, these typings _would_ have the opportunity to jump in. Are _all_ imports from the package meant to be written that way, or just some of them?

**Comment by saiichihashimoto** [comment]
@andrewbranch All of them, yeah. I'm only exporting types from `@sanity/base` so there's common types that can be used, but that can easily be shifted into one of the others since it wouldn't work like that anyways.

**Comment by saiichihashimoto** [comment]
You can actually see from the diff that I'm declaring modules for `@sanity/base`, `part:@sanity/base/schema-creator`, and `all:part:@sanity/base/schema-type`, but `@sanity/base` isn't actually exporting anything but types, something I can easily just not do.

**Comment by andrewbranch** [comment]
It does make me wonder if the community isn’t better off just forking https://github.com/sanity-io/sanity. Are non-TS-related issues getting responses? I noticed there are releases being published, so I guess it’s actively maintained, but the maintainers are completely ignoring their open source community? I’ve never seen anything like this. It seems bad. I don’t envy anyone trying to use this stuff.

**Comment by kmelve** [comment]
Hi folks! I work in developer relations for Sanity and thought I should chime in here. Thanks for raising these concerns, know that we absolutely feel them too!

* We're actively working on resolving the issues you're raising here (we're annoyed by them too). Improved TypeScript support beyond `any` and a solution for [the Parts system](https://www.sanity.io/docs/parts) is definitively coming. It's just a lot of work, but we're getting there!
* It's correct that we haven't been able to be super responsive on GitHub. This is mostly a matter of having been a small team until recently, and prioritizing our support efforts in our [community slack](https://slack.sanity.io). That being said, we're painfully aware that we're lagging behind our GitHub responses. This is also something we're working on improving. 
* @andrewbranch, I guess the sanity repo isn't “your common open-source project” since it is an app that connects to our hosted datastore and is a rather complex application. We have yet to figure out how we best can manage community contributions but know that we do care and we do appreciate them! Thanks for this nudge.

@saiichihashimoto, if you're in our Slack, please DM me, and I can give you more insight into what we're working on. You can also find me on [email](mailto:knut@sanity.io).

**Comment by andrewbranch** [comment]
Thanks so much for the response, @kmelve. From my end (representing TS users consuming third-partly libraries), the experience is going to be better for everyone if you all can work out a way to improve your typings where they are, included with the library. I’m going to close this PR again. @saiichihashimoto, hopefully you and @kmelve and others in the community can collaborate on making those improvements. Let me know if you don’t get anywhere with that route and then we can reopen this. Thanks!

**Comment by saiichihashimoto** [comment]
I'll reach out @kmelve but before we decide to close this out, are any of these changes meant to solve these _specific_ needs (ie having types for writing schemas) within the next few weeks? Because having _some_ solution in place, even if it's temporary, would clearly be beneficial for what is obviously a lot of people. Considering I have some relatively comprehensive types that would handle many, many use cases right here, I'd like to make sure that the changes that make them unnecessary aren't like... a month or more away.

**Pull request closed without merging**
