### PR TITLE
Completely typed AngularJS $http.

### PR DESCRIPTION
**Pull request by qc00**
Merged the defaults, added missing typings and refined others.

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-growl-v2/angular-growl-v2.d.ts*

to author(@mkp05). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*angularjs/angular.d.ts*

to author(@diegovilar). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mkp05** [comment]
For me changes in growl typing are OK :+1:

**Comment by vvakame** [comment]
ummm.. i decided to merge this PR.
@billccn please rebase to master/HEAD.

**Comment by billccn** [comment]
Rebased now :)

**Comment by vvakame** [comment]
@mkp05 thanks!
@billccn thanks mate!

**Pull request merged**
