### PR TITLE
pino.d.ts updated to v3.0.5

### PR DESCRIPTION
**Pull request by psnider**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] ~Run `npm run lint -- package-name` if a `tslint.json` is present.~ Not present

~If adding a new definition:~ Not a new declarations file.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/pino
- [x] Increase the version number in the header if appropriate.

Change summary:
- added namespace to expose interfaces
- updated to match latest version of pino

### CODE REVIEW

**Comment by andy-ms** [comment]
We're using `pino/index.d.ts` instead of `pino/pino.d.ts` now, so you'll have to rebase. You could also change your target branch to `master` since we now prefer that (as of #13280).

**Comment by psnider** [comment]
Please correct the PR comment template to indicate you want master. Notice above that it suggests the **types-2.0** branch

**Comment by andy-ms** [comment]
It's updated now. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by psnider** [comment]
replace this PR with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13348

**Pull request closed without merging**
