### PR TITLE
[react-native] Add NativeScrollEvent.velocity

### PR DESCRIPTION
**Pull request by simontreny**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: see below
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Links to source-code:
- [Android implementation](https://github.com/facebook/react-native/blob/bbcfcdb8ed2345ab4a0c74cb1f440dfc11b7e20b/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ScrollEvent.java#L156)
- [iOS implementation](https://github.com/facebook/react-native/blob/bbcfcdb8ed2345ab4a0c74cb1f440dfc11b7e20b/React/Views/RCTScrollView.m#L750). Note: on iOS, velocity is set only on the onScrollEndDrag event. I made the field optional to take this into account

### CODE REVIEW

**Review by alloy — CHANGES_REQUESTED** [review]
Please include a link to docs or source code so we can verify.

**Comment by simontreny** [comment]
I've edited the main comment with links to the source code

**Review by simontreny — COMMENTED** [review]
Looks good to me 👍

**Review by alloy — APPROVED** [review]

**Comment by alloy** [comment]
Whoops, my bad, merging now.

**Pull request merged**
