### PR TITLE
node-hid: Add 'usagePage' and 'usage' properties to Device

### PR DESCRIPTION
**Pull request by ert78gb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/node-hid/node-hid/blob/master/src/HID.cc#L564

@mhegazy Do you accept it?

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Should these be optional?

**Comment by ert78gb** [comment]
Yes and I changed the others optionals.

**Comment by ert78gb** [comment]
@paulvanbrenk Dear Paul,

Could I do something to the new package publish to the npm? I read it will publish automatically within 1 hour after merge. Put currently it is not published. The merge was 12 hour before  that.

thx,
Robi

**Comment by paulvanbrenk** [comment]
@ert78gb I'll ask around, we've been seeing some hickups.

**Pull request merged**
