### PR TITLE
Apply prettier formatting to relay-runtime

### PR DESCRIPTION
**Pull request by levibuzolic**
Many of the files in `relay-runtime` hasn't been auto-formatted by prettier. This PR applies the repo formatting rules to easy any diffs in future contributions.

`npm run prettier -- --write types/relay-runtime/**/*.ts`

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] ~Test the change in your own code. (Compile and run.)~
- [ ] ~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 14 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getPendingOperationsForFragment</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e471d44b8f1d96056f1acdd693b6f6268795e788
</p>

**Review by maraisr — APPROVED** [review]
🚀

**Review by maraisr — APPROVED** [review]
🚀

**Comment by maraisr** [comment]
not sure if there is a way to merge this w/o a version bump

**Comment by levibuzolic** [comment]
ready to merge

**Comment by maraisr** [comment]
ready to merge

**Review by maraisr — APPROVED** [review]

**Comment by levibuzolic** [comment]
Ready to merge

**Pull request merged**
