### PR TITLE
fixed Promise.any

### PR DESCRIPTION
**Pull request by stepancar**
the array passed to all can be a mixture of promise-like objects and other objects.

### CODE REVIEW

**Comment by vvakame** [comment]
why did you need this change?
I want to check sample code.

**Comment by stepancar** [comment]
@vvakame, we can pass promises with different types to Promise.all

**Comment by vvakame** [comment]
ummm... I want to keep compat for https://github.com/Microsoft/TypeScript/blob/d27d10ce2ff013d66ff73890726b06587bda18fa/lib/lib.es6.d.ts#L1300-L1309

**Comment by stepancar** [comment]
@vvakame , understand you. but in this case we should copy es6.d.ts promise, cause it's typed better
, [see](https://github.com/Microsoft/TypeScript/blob/d27d10ce2ff013d66ff73890726b06587bda18fa/lib/lib.es6.d.ts#L1300)

**Comment by mhegazy** [comment]
@vvakame what is the final call for this PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
