### PR TITLE
Enhanced mongodb definitions

### PR DESCRIPTION
**Pull request by ErhanAbi**
The mongodb definitions are still quite far away from the official docs and library implementation, but I have added support for promises (i.e. methods now return promises too) and also, added the implementation for [AggregationCursor](http://mongodb.github.io/node-mongodb-native/2.0/api/AggregationCursor.html)

This PR includes the other, rejected but helpfull PR created by @Think7 [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7396#issuecomment-167878155);

### CODE REVIEW

**Comment by Think7** [comment]
Thanks for doing this. Been very sick and not at the computer much.

Also, i did implement the namespacing as you suggested but it caused WebStorm's autocomplete to break so i removed it. I'm curious if your new version will also do this.

**Comment by pfzero** [comment]
@Think7 It shouldn't break anything by exposing the module as namespace and importable module. I am using VS Code and it works ok.

I don't know however why the tests are failing and why I can't use the mongodb and bluebird modules (it fails when importing them).

@borisyankov when you have time, can you please have a look on this?

**Comment by vvakame** [comment]
please resolve conflict first.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
