### PR TITLE
Make RoutingContextProps implement MatchState rather than just implem…

### PR DESCRIPTION
**Pull request by tombull**
…ent elements of MatchState - causing problems when it comes to using React.CreateElement on RoutingContext as outputted by match

### CODE REVIEW

**Comment by sergey-buturlakin** [comment]
Not sure this is a right decision to mix RoutingContextProps and match callback parameter type.
Please, provide a sample code to understand the problem.

**Comment by tombull** [comment]
Failing code: 

ReactRouter.match({ routes, location }, (error, redirectLocation, renderProps) => {
    var element = React.createElement(ReactRouter.RoutingContext, renderProps);
}

Which is pretty standard code with react-router, but currently fails (as renderProps : MatchState, but RoutingContext : React.ComponentClass<RoutingContextProps> and RoutingContextProps does not extend MatchState and instead just implements the same signature.

Note function definition for createElement is:

function createElement<P>(
        type: ComponentClass<P> | StatelessComponent<P>,
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;

**Comment by hourliert** [comment]
Same issue here. Should we update this pull request for v2.0.0 and merge it?

**Comment by mhegazy** [comment]
@sergey-buturlakin @mrk21 @vasek17 what is the final call for this PR?

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
