### PR TITLE
add definition for memoizeWith in ramda

### PR DESCRIPTION
**Pull request by gianmarcotoso**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://ramdajs.com/docs/#memoizeWith
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Adding a definition for `memoizeWith`, which was introduced in Ramda 0.24 and should be preferred to the now deprecated `memoize` (as of 0.25). 

Note: the tests file does not compile with typescript@next due to issues outside of the scope of this PR (it fails on the tests for code written more than 8 months ago). I will try to see if I can fix those in another PR, but this does not really have anything to do with that and should be merged regardless.

### CODE REVIEW

**Review by ethanresnick — APPROVED** [review]

**Comment by CaptJakk** [comment]
If you rebase this branch with master, the ts next issues should be fixed now and the build should pass. Hopefully that will expedite the process for you to get this merged.

**Comment by gianmarcotoso** [comment]
@CaptJakk Thank you for the heads up, I'll do so tomorrow (it's late here!). I think I should also extend the definition to include the curried version of the function!

**Comment by gianmarcotoso** [comment]
Can we reopen this?

**Comment by googol** [comment]
@gianmarcotoso There's another PR that's adding `memoizeWith`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24895

**Comment by gianmarcotoso** [comment]
Ok, it was opened after mine but since I see that it's further along I'll consider this one obsolete.

**Pull request closed without merging**
