### PR TITLE
[react-native]remove deprecated props (accessibilityTraits, accessibilityComponentType)

### PR DESCRIPTION
**Pull request by grgr-dkrk**
In 0.57 or above, `accessibilityComponentType` and `accessibilityTraits` have been removed.
Those props doesn't work because the implementation itself has been removed. We should remove those to prevent misuse.
rel: https://github.com/facebook/react-native/pull/24344

--- 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by ca057 — APPROVED** [review]

**Comment by grgr-dkrk** [comment]
A test error occurred in `react-native-material-ripple`.
This library has not been maintained for over a year and does not have `accessibilityRole` support for subsequent props.
https://github.com/n4kz/react-native-material-ripple/pull/28

I'm not sure why this library includes the type of RN in the test, but for backward compatibility, I changed it to include `@deprecated`.

**Comment by ca057** [comment]
> A test error occurred in `react-native-material-ripple`.
> This library has not been maintained for over a year and does not have `accessibilityRole` support for subsequent props.
> [n4kz/react-native-material-ripple#28](https://github.com/n4kz/react-native-material-ripple/pull/28)
> 
> I'm not sure why this library includes the type of RN in the test, but for backward compatibility, I changed it to include `@deprecated`.

Sounds good to me. I also thought that marking them deprecated might be an option, but as the type-file indicates the typings are for version 0.63 and this got already removed for some time, I agreed with your initial change too...

**Review by ca057 — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Review by Naturalclar — APPROVED** [review]

**Comment by Naturalclar** [comment]
I also agree with the initial change of removing the props for newer version
I've made a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49989) to type definitions of react-native-material-ripple to remove deprecated props from the test case.

**Comment by alloy** [comment]
Yeah I also agree with removing what’s no longer actually there at runtime. If other types rely on them then those should be removed too.

**Comment by grgr-dkrk** [comment]
@Naturalclar
Thanks for PR :+1:

**Comment by alloy** [comment]
@grgr-dkrk Perhaps it wasn’t clear, but can you go ahead and remove the typings from other packages that depend on these removed typings?

**Comment by grgr-dkrk** [comment]
@alloy
Thanks.
It looks like only `react-native-material-ripple` has tests for `accessibilityComponentType` and `accessibilityTraits`. If #49989 is merged, this PR is ready too.

**Comment by alloy** [comment]
@grgr-dkrk Gotcha. I just merged that PR, so could you rebase yours to get this CI build green?

**Review by ca057 — APPROVED** [review]

**Review by iRoachie — APPROVED** [review]

**Review by orta — APPROVED** [review]

**Comment by alloy** [comment]
Thanks!

**Pull request merged**
