### PR TITLE
[prosemirror-view] create types for ViewDescs

### PR DESCRIPTION
**Pull request by ifiokjr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by timjb** [comment]
@ifiokjr The API that you are adding typings for in this PR is an internal API. In my opinion the typings for `prosemirror-view` in DefinitelyTyped should only cover the public API, unless there is someone else who relies on the internal API.

I also see that you have updated the version of `prosemirror-view` from 1.3 to 1.8. However, you didn't update the type declarations according to the changes to the ProseMirror API that occurred between theses versions. I have identified the following commits as relevant:

* Changes to some types: https://github.com/ProseMirror/prosemirror-view/commit/bb33f1d0d372c9f9c1cc426a2075409daa08617e, https://github.com/ProseMirror/prosemirror-view/commit/13995939b05bba5efd65371c3a6f2de8f34fe338
* Only changes some comment text: https://github.com/ProseMirror/prosemirror-view/commit/73c3ebb1816e68396e3efaa6b8cc7989c5b87766, https://github.com/ProseMirror/prosemirror-view/commit/eca97f85123963ba40ca431e297941f3a0ff939a, https://github.com/ProseMirror/prosemirror-view/commit/c6d30ed96cdca6f573e9d968b06a7eb19615ca88, https://github.com/ProseMirror/prosemirror-view/commit/6a54ef6da8516258adc5a83a8c2c999175f21fe1

**Comment by weswigham** [comment]
@timjb should I refrain from merging this?

**Review by timjb — CHANGES_REQUESTED** [review]
see my other comment

**Comment by timjb** [comment]
@weswigham Yes, please refrain for now.

**Comment by ifiokjr** [comment]
@timjb I'll take a look once I have a chance. 

Regarding the private / public API would it be fine to add the following to the EditorView class:

```ts
export class EditorView<S extends Schema = any> {
  //...
  /**
   * View descriptions are data structures that describe the DOM that is
   * used to represent the editor's content.
   */
  docView: any;
}
```

**Comment by timjb** [comment]
@ifiokjr I guess I would be fine with this, but declaring the existence of the `docView` property would still violate the policy of not including the internal API in the type definitions. Why don't you just use type assertions on the `EditorView` object in your own code to get at the `docView` attribute?

**Comment by ifiokjr** [comment]
@timjb what you say makes a lot of sense. 

I've created the types in my own codebase and will revisit updating the EditorView to `1.8` once I have more time. 

https://github.com/ifiokjr/remirror/blob/d26ea4bfdb487a315dfce1cc4126563f3c4925eb/support/types/prosemirror-view/index.d.ts#L329

**Comment by ifiokjr** [comment]
> I also see that you have updated the version of `prosemirror-view` from 1.3 to 1.8. However, you didn't update the type declarations according to the changes to the ProseMirror API that occurred between theses versions. I have identified the following commits as relevant:
> 
> * Changes to some types: [ProseMirror/prosemirror-view@bb33f1d](https://github.com/ProseMirror/prosemirror-view/commit/bb33f1d0d372c9f9c1cc426a2075409daa08617e), [ProseMirror/prosemirror-view@1399593](https://github.com/ProseMirror/prosemirror-view/commit/13995939b05bba5efd65371c3a6f2de8f34fe338)
> * Only changes some comment text: [ProseMirror/prosemirror-view@73c3ebb](https://github.com/ProseMirror/prosemirror-view/commit/73c3ebb1816e68396e3efaa6b8cc7989c5b87766), [ProseMirror/prosemirror-view@eca97f8](https://github.com/ProseMirror/prosemirror-view/commit/eca97f85123963ba40ca431e297941f3a0ff939a), [ProseMirror/prosemirror-view@c6d30ed](https://github.com/ProseMirror/prosemirror-view/commit/c6d30ed96cdca6f573e9d968b06a7eb19615ca88), [ProseMirror/prosemirror-view@6a54ef6](https://github.com/ProseMirror/prosemirror-view/commit/6a54ef6da8516258adc5a83a8c2c999175f21fe1)

@timjb I've opened a new PR with the updated types and comments for 1.9.x here #36864

**Pull request closed without merging**
