### PR TITLE
feat: updates the js-yaml `load` and `loadAll` functions types to use generic with default types as so far

### PR DESCRIPTION
**Pull request by AlanLes**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by AlanLes** [comment]
Can somebody help here? I know why the test is failing, and I saw the `@definitelytyped/no-unnecessary-generics` rule, but I think it is wrong. The `generics` usage in those functions is completely right and enables us to use them in a more generic and convenient way.

**Comment by AlanLes** [comment]
Thanks @jakebailey! 🙇 
But then, how do we write the correct typing for the `load` and `loadAll` functions to allow users to declare the type they would like to receive? I still think my solution is correct; I can't think of a different one.
The whole point is that, In my opinion, the `: unknown` as a result of a function is insufficient.

**Comment by jakebailey** [comment]
You would write what you have but then disable the lint rule.

But I think the package owners should be deciding if that's even desirable; you're just opening this up to unsafety. It's very common for parser functions to return `unknown` because anything else is just unsafe (e.g. `node-fetch`'s `.json()` call, and people wish `JSON.parse` did that too). Loading `unknown` seems quite intentional and I wouldn't want to approve this PR without consensus.

**Review by jakebailey — CHANGES_REQUESTED** [review]
Marking as needing review so that this doesn't accidentally get merged without feedback; per above I don't believe this is a positive change.

```ts
// Before, isn't safe, but a cast makes that clear.
const foo = load("124") as string;

// After, feels safe, isn't.
const foo = load<string>("124");
```

**Comment by AlanLes** [comment]
@jakebailey thanks! You've made it clear, and now I understand the point. I'll close this PR. Best regards! ✌️ On 29 Feb 2024, at 18:28, Jake Bailey ***@***.***> wrote:﻿
@jakebailey requested changes on this pull request.

Marking as needing review so that this doesn't accidentally get merged without feedback; per above I don't believe this is a positive change.
// Before, isn't safe, but a cast makes that clear.
const foo = load("124") as string;

// After, feels safe, isn't.
const foo = load<string>("124");

**Pull request closed without merging**
