### PR TITLE
[prosemirror-view] Improve the type definition of `nodeViews` property.

### PR DESCRIPTION
**Pull request by percy507**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

@Narretz  Hi.  I split the nodeViews type for node and mark. I think this will be more clearly.🦦

> https://prosemirror.net/docs/ref/#view.NodeView
>
> Mark views only support dom and contentDOM, and don't support any of the node view methods.

> https://prosemirror.net/docs/ref/#view.EditorProps.nodeViews
>
> For nodes, the third argument getPos is a function that can be called to get the node's current position, which can be useful when creating transactions to update it. For marks, the third argument is a boolean that indicates whether the mark's content is inline.

> According to the [source code](https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L574), mark views only has three arguments.

### CODE REVIEW

**Review by timjb — APPROVED** [review]
LGTM. Thank you for the contribution!

**Comment by Narretz** [comment]
Hi @percy507 I think you only force pushed the changes after @timjb  approved them, right?

**Comment by percy507** [comment]
> Hi @percy507 I think you only force pushed the changes after @timjb approved them, right?

@Narretz  My bad. After tjmjb approved this PR, I want to submit another PR, but I commit the change to the branch of current PR. Then I reset it back and make a force pushed.

Here is the another PR. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57408

**Comment by Narretz** [comment]
LGTM then

**Comment by kachkaev** [comment]
Not sure why, but this change caused linting problems in our codebase – see https://github.com/hashintel/hash/pull/206#issuecomment-1018826336 for context. I had to use [`patch-package`](https://www.npmjs.com/package/patch-package) after upgrading `@types/prosemirror-view` from `1.19.1` to `1.19.2` ... `1.23.1`.

**Comment by Narretz** [comment]
I think that's because the type change added a separate signature for nodeView that is called for a mark. Because your nodeViews are called with three arguments, it looks like typescript doesn't know which signature to use? What happens when you add the 4th argument, decorations, to your nodeViews?

**Comment by kachkaev** [comment]
Thanks @Narretz! [Adding the fourth argument](https://github.com/hashintel/hash/pull/206/commits/fcfff71397cdb356c42b4188274510437de22c5e) seems to do the job. That’s a bit unintuitive though so I wonder if there space for some other solution 🤔

**Comment by Narretz** [comment]
I think there might be something possible if the whole schema / EditorView is thoroughly typed. Because the schema could contain all mark and node keys, so it should theoretically be possible to know if a nodeView is for a mark or a node. But so far I've not managed to get there, and it wouldn't help with untyped schemas anyway. So maybe revert the change? Though so far there were no complaints expect yours ;)

**Pull request merged**
