### PR TITLE
Extend Mocha typings to allow writing of custom reporters

### PR DESCRIPTION
**Pull request by enlight**

### CODE REVIEW

**Comment by vvakame** [comment]
*mocha/mocha.d.ts*

to authors(@kazimanzurrashid @otiai10 @jt000). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by otiai10** [comment]
Thanks for mention.
I'll check it

**Comment by vvakame** [comment]
@otiai10 how about this pr?

**Comment by otiai10** [comment]
It looks good to me, @vvakame

**Comment by vvakame** [comment]
@otiai10 thanks!
@enlight thanks mate!

**Comment by adidahiya** [comment]
looks like there needs to be a separate `mocha-node.d.ts`?

**Pull request merged**
