### PR TITLE
Fix openfin typings broken when used globally

### PR DESCRIPTION
**Pull request by licui3936**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by whyn07m3 — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
@licui3936  I'm not sure this is quite right.. what are you considering to be broken? I can give recommendations based on the particular issue you're trying to tackle.

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
See above comment.

**Review by licui3936 — COMMENTED** [review]
@uniqueiniquity  what's your suggestion?  I made this PR based on the recommendation by  @alitaheri .

Here is my previous PR which you can take a look. @alitaheri  commented on it. 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30203

**Comment by uniqueiniquity** [comment]
I see, thanks for linking the previous PR. Here are some thoughts; please let me know if I'm not understanding something.

From what I can tell, openfin is a (very large) global library (i.e. you would never say `import * as fin from "openfin"`, but rather `fin` is always just present). Therefore, the top-level index.d.ts file is set up like a global library (`declare namespace fin { … }`), but it's importing symbols from other files like it's a module, thereby causing errors when trying to use it globally.

As discussed [here](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#dependencies-on-global-libraries), the proper way to pull in symbols from other global libraries is with `/// <reference types="./foo" />` As you'll see at that same link, the way that this usually works is that each .d.ts file defining a global library defines a namespace with the name of the variable that the library exposes. Here, since you're using these sub-files to organize a single library, as opposed to defining separate libraries, you should use `fin` for the namespace in every file here.

**Comment by uniqueiniquity** [comment]
You can see an example of this in [the TypeScript source code](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/core.ts), where many files add members to the `ts` namespace and reference each other as I mentioned above.

**Comment by licui3936** [comment]
Thanks. I see your point. We have a lot of sub-files. That's why i try not to add namespace fin {}  for every file. Instead, i use import {fin} from "openfin" in test file.  Is there any other way to do it?

**Comment by licui3936** [comment]
or i use the same way as we did for other symbols like "Appliction".  I move all the imports to the inside of namespace fin.

**Comment by uniqueiniquity** [comment]
Yes, if you're only importing type names with those import statements, then you can move them to inside the namespace `fin` as follows:
```ts
type ApplicationOption = import('./_v2/api/application/applicationOption').ApplicationOption;
```

**Comment by licui3936** [comment]
cool, that's exactly what i want. Thank you so much! i will change it.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Thanks for your contribution!

**Pull request merged**
