### PR TITLE
mysql: Added .format() overload

### PR DESCRIPTION
**Pull request by alexhorn**
Added the .format() overload that accepts an object for the values
parameter

### CODE REVIEW

**Comment by vvakame** [comment]
*mysql/mysql.d.ts*

to author(@wjohnsto). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by wjohnsto** [comment]
@alexhorn I wasn't aware you could pass in an object! Is there documentation on this as to what node-mysql does when you use an object for the format method?

Anyway this looks good: :+1:

**Comment by alexhorn** [comment]
@wjohnsto Unfortunately, the format method does not seem to be documented very well, but its "values" parameter behaves the same way as the "values" parameter of the query method, which is documented here: https://github.com/felixge/node-mysql/#escaping-query-values

**Comment by vvakame** [comment]
@wjohnsto thanks!
@alexhorn  thanks mate!

**Pull request merged**
