### PR TITLE
[ByteBuffer::wrap] It also accepts a regular buffer.

### PR DESCRIPTION
**Pull request by awartoft**

### CODE REVIEW

**Comment by cappellin** [comment]
According to the ByteBuffer API (https://github.com/dcodeIO/bytebuffer.js/wiki/API) the type of parameter *buffer* is `(ByteBuffer | ArrayBuffer | Uint8Array | string)`, so `Buffer` is excluded. Did you try using type Buffer? Let me ask @dcodeIO for confirmation.

**Comment by macnibblet** [comment]
@cappellin I'm in the progress of converting a project to typescript and it used `ByteBuffer` in that way.

**Comment by dcodeIO** [comment]
@cappellin With a node build there's also `Buffer`. The API documentation is based on the [browser build](https://github.com/dcodeIO/bytebuffer.js/tree/master/dist).

**Comment by cappellin** [comment]
OK @dcodeIO . I'm not sure how to proceed, because if you add the type *Buffer* (and reference to node.ts.d) into the *bytebuffer.d.ts* definition you will brake compatibility with those projects that don't use Node.js. To summarize *bytebuffer.d.ts* is fine for *bytebuffer.js*, but it's not for *bytebuffer-node.js*. I would like to suggest a new definition called *bytebuffer-node.d.ts*, but let me ping @vvakame to understand the best way to proceed.

**Comment by vvakame** [comment]
:+1: for bytebuffer-node.d.ts.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
