### PR TITLE
Add jquery-bootpag definition files

### PR DESCRIPTION
**Pull request by rdeneau**
Type definitions for jQuery-Bootpag 1.0.7

### CODE REVIEW

**Comment by vvakame** [comment]
*jquery-bootpag/jquery-bootpag.d.ts*

Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery-bootpag
  * http://bower.io/search/?q=jquery-bootpag
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery-bootpag/jquery-bootpag-tests.ts or jquery-bootpag/jquery-bootpag-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
@rdeneau please rename jquery-bootpag/jquery-bootpag.d.ts to bootpag/bootpag.d.ts
https://www.npmjs.com/package/bootpag

**Comment by rdeneau** [comment]
Hello. It seems OK now. Can you merge my pull request? Thx

**Comment by vvakame** [comment]
please remove jquery-bootpag/*

**Comment by rdeneau** [comment]
Done. Sorry for the mistake. I'm not used to using github, especially pull request.

**Pull request merged**
