### PR TITLE
node/globals.d.ts Add BufferEncoding interface to toString method

### PR DESCRIPTION
**Pull request by mateus4k**
I imagine that this is the correct typing for the method.

I made this change locally and it helped me a lot.

### CODE REVIEW

**Comment by SimonSchick** [comment]
The problem with this change is that the encoding gets normalized eg.

```
> Buffer.from('asdasd').toString('hEx')
'617364617364'
```

We've been pretty lucky with progressively applying `BufferEncoding` in other places but this would be a potentially breaking change for other consumers.
We could *try* rolling it for v14.

**Review by galkin — CHANGES_REQUESTED** [review]
@mateus4k, thank you! It is small, but very useful change. Could you add this change for 10 version too?

**Comment by SimonSchick** [comment]
@galkin if at all, this should be added in a major version due to the breaking nature of this change.

**Comment by galkin** [comment]
@SimonSchick, I don't think this is a major version change, but you right there is a risk. As we can see at the failed Travis build, there are packages what use encoding outside the list.

So at this pull request, we also should fix the encoding issue. @mateus4k could you make this?

@SimonSchick, what do you think will be this enough?

**Comment by peterblazejewicz** [comment]
can we code the change that way? (or similar, in backward compatible fasion, there is already a lot of breaking, minor tweaks recently):
```ts
toString(encoding?: BufferEncoding, start?: number, end?: number): string;
/** @todo remove in v14 */
toString(encoding?: string, start?: number, end?: number): string;
```

**Pull request closed without merging**
