### PR TITLE
URI.js: URI.expand changes

### PR DESCRIPTION
**Pull request by alexander-matsievsky**
- expose `urijs/src/URITemplate`
- expand `equals(url: string): boolean;` to `equals(url: string | URI): boolean;`

### CODE REVIEW

**Comment by xt0rted** [comment]
I'm not familiar with this feature (it's been awhile since I used the library), but from what I can tell this change looks ok.

**Comment by alexander-matsievsky** [comment]
@xt0rted I used this trick in several projects, changing `URIjs.d.ts` and vendoring it in my repos through commit. No breakage spotted so far, works as advertized.

Just wanted to get it by default from `tsd install` without hacks.

**Comment by alexander-matsievsky** [comment]
@xt0rted I think *dt-bot* expects you to reply with `:+1:` to confirm PR.

Thanks!

**Comment by xt0rted** [comment]
:+1:

**Comment by vvakame** [comment]
please resolve conflict.

**Comment by alexander-matsievsky** [comment]
@xt0rted My bad. Made changes to a stale fork.
Closing this PR in favor of #7778.

**Pull request closed without merging**
