### PR TITLE
wavesurfer.js: Correct type for maxRegions in RegionsPlugin

### PR DESCRIPTION
**Pull request by JanMisker**
Changed from `number[]` to `number`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [] Test the change in your own code. (Compile and run.)
- [] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/katspaugh/wavesurfer.js/pull/2454
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## wavesurfer.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/wavesurfer.js@latest/))
was missing the following properties:
1. debounce
1. Observer
1. absMax
1. clamp
1. fetchFile

<details>
<summary>as well as these 10 other properties...</summary>
<p>frame, getId, ignoreSilenceMode, max, min, preventClick, requestAnimationFrame, style, withOrientation, WaveSurfer</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ed7e0221ccf8af21dfc0896bfa7cf182e5504594
</p>

**Review by caugner — CHANGES_REQUESTED** [review]
Thanks, good catch!

Just two minor nits:

1. Please update the tests by simply passing the maxRegions options here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed7e0221ccf8af21dfc0896bfa7cf182e5504594/types/wavesurfer.js/wavesurfer.js-tests.ts#L156
2. Please prefix both the PR title and the commit message with `wavesurfer.js: `.

**Comment by caugner** [comment]
@JanMisker The test is failing, because the `RegionsPluginParams` still has a `maxRegions` property with `number[]`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a71e6c0ec13d6bb44331da73c0fefcc0df5f30a7/types/wavesurfer.js/src/plugin/regions.d.ts#L47-L48

You'll probably want to update that type as well. :slightly_smiling_face:

**Comment by caugner** [comment]
And to test the `maxRegions` property on the `regions` plugin object, you should be able to do something like this:

```patch
+// $ExpectType number
+waveSurferWithRegionsPlugin.regions.maxRegions;
 waveSurferWithRegionsPlugin.regions.destroy();
```

**Comment by JanMisker** [comment]
Thanks for the pointers, much appreciated :) Thought it was somehow picking up from the base repository type annotations (change was needed there as well). It's my first time doing a pull request to DefinitelyTyped, figuring out the workflows.

**Comment by caugner** [comment]
Congratulations on your first contribution and the passing test! :tada: 

@JanMisker Two optional things:

1. Feel free to add yourself here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f417e075f73ca17a8a703a97d754fac8dcbbf2d/types/wavesurfer.js/index.d.ts#L3-L7
2. Your PR will be squash-merged, but if you're curious, you could try and cleanup the commit history as follows:

```
# 1. Merge latest origin/main again.
git merge origin/main
# 2. Softly reset to this new base.
git reset --soft origin/main
# 3. Commit freshly or reuse your initial commit message.
git commit -C cca522295294aae44ad871898e4c6703b52a414f
```

(Maybe there's even an easier way, but it's usually a bit tricky when you merged the base/target branch in the middle of a PR.)

**Comment by JanMisker** [comment]
Thanks @caugner for your patience :) 
I'll add myself when I have more than 2 characters changed ;)

**Review by caugner — APPROVED** [review]
LGTM, thanks!

**Comment by JanMisker** [comment]
Ready to merge

**Pull request merged**
