### PR TITLE
remove webdriverio. Bundles their own types since 5.0.0

### PR DESCRIPTION
**Pull request by MrOggy85**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by timbru31** [comment]
Sad, but true :)

**Review by timbru31 — APPROVED** [review]

**Comment by timbru31** [comment]
This would/should also close the following issues: #32479, #30313, #27190, #26841, #25186, #21358, #21118, #19100, #14306, #13476

**Comment by timbru31** [comment]
@uniqueiniquity - can you close the mentioned issues above?

**Comment by uniqueiniquity** [comment]
@timbru31 Done! Thanks for keeping track of those.

**Comment by Flarna** [comment]
Seems this breaks tests of chai-webdriverio (see CI of #32159):

```
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/chai-webdriverio/index.d.ts:6:23
ERROR: 6:23   expect  TypeScript@next compile error: 
Cannot find type definition file for 'webdriverio'.
ERROR: 22:38  expect  TypeScript@next compile error: 
Cannot find namespace 'WebdriverIO'.
```

**Comment by daveparslow** [comment]
We should probably revert that change to remove and keep the definitely
typed for v4

**Pull request merged**
