### PR TITLE
@types/node: Remove "set-cookie" from IncomingHttpHeaders

### LINKED ISSUE #48895: [@types/node] IncomingHttpHeaders contains 'set-cookie' which is a response header only
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz @victorperin

I don't know if the authors are correct, I took the latest ones from `http.d.s` that were also in the `Definitions by` list.

I noticed `set-cookie` is defined in `IncomingHttpHeaders` (as the only `string[]`). It's not a request header though, there's nothing a server can do with that header if the user sends it according to HTTP (at least nothing I've found). And how is the header supposed to be any array, the browser can only send a string?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

It's an easy fix but I must be missing something on why this is explicitly typed.

### PR DESCRIPTION
**Pull request by josteink**
`@types/node` contains the interface `IncomingHttpHeaders`. This interface supports setting cookies, although there's no way to do this on an *incoming* request in the real world.

This closes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48895.

I've removed the property across all Node-versions as there's no reason for it to be there. If this breaks a compatibility-policy of sorts, please let me know, and point me in the right direction for the appropriate way of handling that.

### CODE REVIEW

**Comment by Flarna** [comment]
The callback given to `http.request` receives an `IncomingMessage` which holds `IncomingHttpHeaders`. 
Why is it not possible that one receives a `set-cookie` header in a HTTP response?

**Comment by josteink** [comment]
Hey @Flarna and thanks for the feedback!

Maybe I'm wrong about this (just trying to help out with a registered issue), but to me it seems wrong to set cookies on an incoming *request*. A request is an input and that is something you cannot change, because it was already made and completed by the user-agent.

So if you want to set cookies, you will obviously need to do that when you return the appropriate *response* for that request, since the response is the only actual *output* which you have the ability to modify.

Or does Node handle this basic request/response pattern with a completely different model, where things are kinda intermixed and the same object is used for both things? If so, the name of the type should IMO be changed to reflect that.

**Comment by Flarna** [comment]
The interface is not only about setting something. It just says that a field `set-cookie` of type `string[]` may be present.

You could modify type definitions in a way to use a different type for HTTP response on client side and HTTP request on server side.

Please note that these interfaces extend `NodeJS.Dict<string | string[]>` which allows any key of type string. If you remove the line it just removes the strong type of `set-cookie` to be of type `string[]` - which is actually documented at  [http.IncomingMessage](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_message_headers)

**Comment by josteink** [comment]
> The interface is not only about setting something. It just says that a field `set-cookie` of type `string[]` may be present.

My argument was mostly how this didn't make conceptual sense based on the action being taken.

> If you remove the line it just removes the strong type of `set-cookie` to be of type `string[]` - which is actually documented at [http.IncomingMessage](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_message_headers)

If it's documented though, it's obviously something someone has decided is usable for some purpose, and I'll leave it at that. I'm not arguing with documentation :smile: 

That said, as I close this PR, I also recommend to close the associated bug with a similar response.

**Comment by tozz** [comment]
Since I was the one who opened the original issue, the interface is used in `IncomingMessage`, which is, for incoming data. In contrast with the more correct `OutgoingHttpHeaders` which doesn't define headers that can never occur.
The documentation is a bit interesting `// incoming headers will never contain number`, they will never contain an array either because a header can't be an array :)

**Comment by Flarna** [comment]
To my understanding it's allowed for a server to return more then one set-cookie header. I know that on wire HTTP protocol is using strings not arrays but the type definitions reflect the node API not how it is transferred on the wire.

see following example:
```ts
import { createServer, IncomingMessage, ServerResponse, get } from 'http'

const port = 8000
createServer((req: IncomingMessage, res: ServerResponse) => {
  res.writeHead(200, {
    'content-length': 0,
    'set-cookie': 'yummy_cookie=choco, tasty_cookie=strawberry',
    'x-my-header': ['foo', 'bar']
  });
  res.end()

}).listen(port)

get({ port }, (res: IncomingMessage) => {
  console.log(res.headers)
})
```

it prints
```
{
  'content-length': '0',
  'set-cookie': [ 'yummy_cookie=choco, tasty_cookie=strawberry' ],
  'x-my-header': 'foo, bar',
  date: 'Wed, 21 Oct 2020 08:07:23 GMT',
  connection: 'close'
}
```
As you can see the `set-cookie` on `IncomingMessage.headers` in client response is an array whereas `x-my-header` is presented as comma separated string. as far as I remember the reason is the using a `,` wont work in all cases for cookies.

**Comment by tozz** [comment]
You are right @Flarna, the Interface is correct, my confusion stems from the misuse (or overuse) of the same declaration and logic for two incompatible types. As you show in your example, IncomingMessage is used as both a response and request and the header `set-cookie` can only ever be used in a response (as well as some other headers declared in the interface).
This is clearly a Node internals issue and not a DefinitelyTyped one.

**Comment by Flarna** [comment]
I think we could use different interfaces for client response and server request but not sure if it is worth the effort.

**Comment by tozz** [comment]
If the issue hasn't come up before I'm sure it's not worth the refactoring, I can work around it on my end.

**Comment by grundmanise** [comment]
@tozz I agree, that does not make sense and does cause confusion having such behaviour for `set-cookie` and being defined for `IncomingMessage` type 👍  Not sure why it was the case for such behaviour in Node.

**Pull request closed without merging**
