### PR TITLE
@types/react-datepicker: fix onChange prop value type depending on selectsRange prop value

### PR DESCRIPTION
**Pull request by bulatte**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Hacker0x01/react-datepicker/blob/18302ebb2cb6b98ae9064e195d73bc25e96eb6a9/docs-site/src/examples/selectsRange.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by 1pete** [comment]
You should put some references to make the process smoother.

ref: https://github.com/Hacker0x01/react-datepicker/blob/18302ebb2cb6b98ae9064e195d73bc25e96eb6a9/docs-site/src/examples/selectsRange.js

**Review by 1pete — APPROVED** [review]

**Comment by bulatte** [comment]
@1pete I've updated my original comment and I'll remember this for the future. Thanks!

**Comment by bulatte** [comment]
Ready to merge

**Comment by bulatte** [comment]
Hey @mariusvirb,

Do you have a custom component that wraps the DatePicker and passes down props to it? 
If yes, try adding add a type argument to the props type definition depending on the use-case (with selectsRange or not). 

```tsx
import ReactDatePicker, {ReactDatePickerProps} from 'react-datepicker';

const DatePicker = (props: ReactDatePickerProps<never, true>) => (
  <ReactDatePicker {...props} />
);
```
Pay attention to the `props: ReactDatePickerProps<never, true>` part, and specifically the `true` argument, which represents the value of your `selectsRange` prop.

If you want it to have correct types in any cases, add a generic to the component instead: 

```tsx
import ReactDatePicker, {ReactDatePickerProps} from 'react-datepicker';

const DatePicker = <WithRange extends boolean | undefined = undefined>(
  props: ReactDatePickerProps<never, WithRange>,
) => <ReactDatePicker {...props} />;
```

Sadly, I couldn't come up with a simpler way to make the types work properly.

**Comment by mariusvirb** [comment]
thank you @bulatte works just fine :pray: I was thinking of adding generics, but seemed a little unusual to me, but it'll do! :v:

**Pull request merged**
