### PR TITLE
[yup] Make all schemas default to being typed as optional (notRequired)

### PR DESCRIPTION
**Pull request by iansan5653**
**Changes**

This PR changes every schema to default to allowing undefined. For example, `yup.number()` will now return `NumberSchema<number | undefined>` instead of `NumberSchema<number>`. This accurately reflects the actual library behavior.

This is a proposal - I know it may not be universally agreed that this change should be made so I'd like to start a discussion with this PR.

**Justification**

I know this is a major breaking change in the type definitions that will require fixing pretty much any TS code that uses the library that isn't extremely carefully made. I don't take that lightly. However, it's more important that we have accurate types than that we avoid breaking changes.

This change makes the types significantly more accurate with respect to the actual behavior of the library. This is easily explained in a simple example:

```ts
const sampleSchema= yup.object({
  x: yup.number();
});

// The inferred type implies that only values of type number will get through:
type Inferred = yup.InferType<typeof sampleSchema>; // {x: number}

// Therefore, most devs would assume this is safe:
const someApiResponse = {x: undefined};

if (sampleSchema.validateSync(someApiResponse)) { // validates because undefined is allowed!
  someApiResponse.x.toFixed(2); // TypeError: Cannot read property 'toFixed' of undefined
}
```

*So if it's so obvious, then why aren't the schemas already typed that way?*

There is a note on this exact issue in the Yup readme: https://github.com/jquense/yup#why-does-infertype-not-default-to-nonrequired

The argument boils down to the idea that because optionality is defined differently in Yup vs TypeScript, you could end up passing something to Yup that was typed as though it would validate and instead it errors. Example:

```ts
const schema = yup.string().required();

schema.validateSync(""); // errors because Yup's required demands content in the string
```

However, I disagree with this argument for two reasons.

First, it is inevitable and even theoretically *desired* that this scenario will be possible because Yup does runtime checks, which are by nature stricture than compile-time checks:

```ts
const schema = yup.number().max(90);

schema.validateSync(110); // errors of course, even though it's a number
```

Second, the recently added `defined` function invalidates the argument entirely because now we can mimic TypeScript behavior exactly anyway:

```ts
const schemaA = yup.string().defined();

schemaA.validateSync(""); // passes!

const schemaB = yup.array(yup.string().defined()).defined();

schemaB.validateSync([]); // passes!
schemaB.validateSync([""]); // passes!
```

**Notes**

*Versioning*

I know this change is going to be breaking in many projects if merged. I'm not exactly clear on how DefinitelyTyped handles that - do the types have different versioning from the libraries they type? In that case this should be a major version bump. 

*StringSchema*

~~There is one oddity here that might be worth discussing. Due to the way the `StringSchema` constructor is typed (since #43860), calling `string()` yields `StringSchema<string> | StringSchema<string | undefined>`.~~

~~The only way to fix this would be to revert #43860 by removing the generic type parameter from the constructor (the parameter is unnecessary and goes against one of the DefinitelyTyped Common Mistakes). This might be the time to do that anyway, since I opened a PR to add better support for enumerated string types through the use of `oneOf` (#44573) which makes that functionality unnecessary. However, I don't think we really need to do that because although the typing looks odd, it doesn't really affect any functionality as far as I can tell.~~

Update: I ended up removing the generic type parameter anyway as it was made unnecessary by the updates to `oneOf`.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup#why-does-infertype-not-default-to-nonrequired
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by iansan5653** [comment]
@jquense Here's the PR I've opened relating to https://github.com/jquense/yup/issues/880 if you'd like to join the discussion.

**Comment by mauricedb** [comment]
@iansan5653 

I like the suggestion. Using `.defined()` gets around the issue I had with `.required()` nicely. I wasn't really aware of the new `.defined()` function being added untill your other PR, thanks for that.

As you mentioned this is a big breaking change but personaly I think it is worth it. Not sure what the best way to communicate this is though. Maybe someone else has a good suggestion there.

One thing I was thinking of is providing a jscodeshift codemod to update all types and add `.defined()` as doing so manually or with search/replace is going to be painful.

**Comment by sseppola** [comment]
I agree with @mauricedb, I think this is a change for the better.

Reading a bit about how breaking changes in types are handled on DefinitelyTyped it seems our options are narrow..

[DT tries to keep the two first digits of the version in sync with the library itself](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) so the major version is reserved for the library author themselves.

The 2nd comment in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25677 is the most informative, but basically sums up to:
- any change in types is potentially breaking for someone
- there's no best practice for doing what we're discussing 
- try not to break people's code unnecessarily

If this isn't a good argument for always using lockfiles I don't know what is.

We could add a breaking change in sync with a new version of TS so people at least expect something could break by using the [typesVersions](https://github.com/microsoft/TypeScript/pull/26568) feature. However that forks the definition, increasing the maintenance effort required from us, AND the effort required from users when upgrading TS itself.
This sets a precedence I don't like..

To me, it looks like we're forced to use patch updates for breaking changes, just like any other change.

**Comment by mauricedb** [comment]
Yes, I agree we should not use `typesVersions` as this is for TypeScript versions which isn't the case here. It seems version wise all we can do is just release this with a new patch version. It isn't even related to a change in the Yup package so we can't even use a minor version here.

It will however cause quite a few compile errors for most people using `yup.InferType<>` because of the sudden inclusion of `undefined` in types. So I think we need to help them a bit. The least we can do is add a `README.md` here explaining the reason and how to fix the errors and open a PR on Yup with the same info.

Additionally I was think of creating a [jscodeshift codemod](https://github.com/facebook/jscodeshift) to automatically add `.defined()` to all schema properties to ease the change in larger code bases. I have never written a codemod myself and not sure how hard it is but the impression I have is that it isn't that hard to do.

**Comment by jquense** [comment]
i'm +1 on this change, i think it'll be nicer in the long run even if there is a breaking change. If it helps and we can coordinate i'm happy to release a major 0.29.0 bump to coincide with the breaking change here. Otherwise as consumer of these types in a few large projects i'm fine with larger breaking type changes since they are usually super straightforward to fix. cc @itajaja

**Comment by iansan5653** [comment]
I think a version bump in Yup along with a codemod (if that's realistic for this task; I've never written one either) would be enough to go forward with this.

For the codemod, I would propose that it only adds `defined()` calls to any schema that does *not* already call `required`, `defined`, `notRequired`, or `optional`. This might be easier said than done but I'll look into it this week.

**Comment by jquense** [comment]
I've written good bunch of codemods and i think it's probably not worth it in this case. It'd be fairly time consuming mod to write for the simple cases, and likely miss a lot of cases depending on how ppl import and use yup e.g. `yup.string()` vs `string()`

**Comment by mauricedb** [comment]
Just to scratch an itch because I have never written a codemod I had a go. Certainly not perfect and won't work on all cases but seems to work for the simple cases I tried.

The only thing I can't figure out yet is how to skip schema parts that already contain a call to `.notRequired()` etc.

```
const propertyNamesToAddDefined = [
  "mixed",
  "string",
  "number",
  "boolean",
  "date",
  "array",
  "object",
];

export default (fileInfo, api) => {
  const j = api.jscodeshift;
  const root = j(fileInfo.source);

  const importDeclaration = root.find(j.ImportDeclaration, {
    source: {
      type: "StringLiteral",
      value: "yup",
    },
  });

  const identifierCollection = importDeclaration.find(j.Identifier);

  if (identifierCollection.length) {
    const nodePath = identifierCollection.get(0);
    const localYupName = nodePath.node.name;

    const callExpressions = root.find(j.CallExpression, {
      callee: {
        type: "MemberExpression",
        object: {
          name: localYupName,
        },
      },
    });

    callExpressions
      .filter(({ node }) =>
        propertyNamesToAddDefined.includes(node.callee.property.name)
      )
      .replaceWith(({ node }) =>
        j.callExpression(
          j.memberExpression(node, j.identifier("defined"), false),
          []
        )
      );
  }

  return root.toSource();
};

export const parser = "ts";
```

**Comment by iansan5653** [comment]
Merging #44573 means I had to remove the generic type parameters for `StringSchema`, because the issue mentioned in the notes of the PR meant that `oneOf` would have two incompatible signatures. This isn't a huge deal though since where before you would use `string<"A" | "B">()` you would now use the much safer `string().defined().oneOf(["A", "B"] as const)`.

**Comment by mauricedb** [comment]
Added the Codemod to a repo [here](https://github.com/mauricedb/my-codemods/blob/master/transforms/yup-add-defined.js). Any feedback to make it better would be appreciated as I am new to writing Codemods.

**Comment by iansan5653** [comment]
Added a PR in Yup to update the readme after this is merged: jquense/yup#891

**Comment by mauricedb** [comment]
While testing this PR against my current codebase I ran into one issue with the `.mixed()` and the combination of `.oneOf()` and `.nullable()`.

I would expect both these schemas to resolve to the same type `MixedSchema<"hello" | 1 | null | undefined>` but the second actually resolves to `MixedSchema<"hello" | 1 | undefined>` leaving out the `null`.

```
const oneOfNullable = yup
    .mixed()
    .oneOf(['hello', 1, null] as const)
    .nullable(); // $ExpectType MixedSchema<"hello" | 1 | null | undefined>

const nullableOneOf = yup
    .mixed()
    .nullable()
    .oneOf(['hello', 1, null] as const); // $ExpectType MixedSchema<"hello" | 1 | null | undefined>
```

I was also expecting the `$ExpectType MixedSchema<"hello" | 1 | null | undefined>` to work for the first but for some reason it got: ` { (isNullable?: true | undefined): MixedSchema<"hello" | 1 | null | undefined>; (isNullable: false): MixedSchema<"hello" | 1 | undefined>; (isNullable?: boolean | undefined): MixedSchema<"hello" | 1 | undefined>; }`. Not sure what that is about as `yup.mixed().oneOf(['hello', 1] as const); // $ExpectType MixedSchema<"hello" | 1 | undefined>` works just fine. That might just be a dtslint issue, not sure about that.

**Comment by iansan5653** [comment]
@mauricedb great catch - that's an issue with the typing of `oneOf` leftover from before my previous PR. I can fix it easily.  The other issue I think is just with where you put the `ExpectType` comment - if you put the whole declaration on one line then it will work, or possibly if you move it to the line before the start of the declaration.

**Comment by mauricedb** [comment]
@iansan5653 

Ran into another case where the order seems to matter. In this case it is with `.oneOf()` and `.defined()`.

```
const oneOfDefined = yup.mixed().oneOf(['hello', 1] as const).defined(); // $ExpectType MixedSchema<"hello" | 1>

const definedOneOf = yup.mixed().defined().oneOf(['hello', 1] as const); // $ExpectType MixedSchema<"hello" | 1>
```

I would expect both to resolve to the same type but the second actully resolves to `MixedSchema<"hello" | 1 | undefined>`

**Comment by iansan5653** [comment]
@mauricedb I ran into that as well. In this particular case, I think this *might* be inevitable. The problem isn't with the types, it's with TypeScript itself. There is no `not` type, so we can never express "everything except for undefined". Since `mixed()` has type `MixedSchema<any>`, `mixed().defined()` should have type `MixedSchema<not undefined>` but of course, that's not a real type.

We could get around this by typing it as `MixedSchema<{} | null | undefined>` by default. Based on my experiments and the tests, this should work exactly as it does now. However, I can't confidently say that this won't have any unforeseen side effects, which is why I haven't done it yet. If someone with more knowledge of how TypeScript works could comment on that, I'd appreciate it.

**Comment by iansan5653** [comment]
After some research and throwing everything I could think of at it, it seems that `{} | undefined | null` works pretty well. I went ahead and committed it - if you could try it out on your code and see if there are any side effects, I'd appreciate it.

**Comment by mauricedb** [comment]
@iansan5653 

I don't think the `unknown` case you mention is very likely to occur. At least I can't think of any reason you would write something like that. The whole point of `unknown` is not knowing in a type safe manner, In that case you are declaring a hard coded `4` as an unkown constant. Seems very unsusual. But as you pointed out there is still an escape hatch.

I am happy with this change to unless anyone else has an objection I will approve this. I will give everyone 24 hours before I hit the Approve button :-)

The CI build for the PR is failing but that just seems to be a rate limiting issue. I can't queue a new build but maybe one of the maintainers can do so.

**Comment by sseppola** [comment]
What happened to syncing the release with yup 0.29.0 so we can communicate these changes more easily? @jquense was aboard

**Comment by iansan5653** [comment]
@sseppola As far as I know that's still the plan.

**Comment by mauricedb** [comment]
Good point. There is a [PR](https://github.com/jquense/yup/pull/891) from @iansan5653 but I just noticed that is still a draft PR.

**Comment by iansan5653** [comment]
I think the process for that would be:
1. I'll update the PR to bump the version and mark it as ready for review later today.
2. We'll wait on the PR to be merged and npm to publish the new version.
3. Finally, merge this PR (after updating to change the version number here as well).

**Comment by mauricedb** [comment]
@iansan5653 @jquense Any progress with the Yup OR so we can merge this one as well?

**Comment by iansan5653** [comment]
@mauricedb still waiting on the changes in Yup (jquense/yup#891).

**Comment by jquense** [comment]
0.29.0 released

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Need experts sign off on this change

**Comment by mauricedb** [comment]
@iansan5653 I guess we need to update the `Type definitions for yup 0.28` header line to `Type definitions for yup 0.29` and we can release this.

**Comment by iansan5653** [comment]
@sheetalkamat I'm not sure I understand what changes you are requesting.

**Review by mauricedb — APPROVED** [review]
Great job, thanks

**Comment by iansan5653** [comment]
Ready to merge

**Comment by P4sca1** [comment]
Great change, thank you! @iansan5653 
One thing i noticed: Shouldn't `ensure()` also strip `unknown` from the type the same way `required()` and `defined()` do?

**Comment by iansan5653** [comment]
@P4sca1 Interesting note - I hadn't heard of `ensure` before. That said, I don't think so. At that point we have to choose between the schema having the transformed type or the validated type.

If we choose the validating type (leave `ensure` as it is because it would pass with `string | null | undefined` without error), we can better type validation - by validating an object it can go from `any` to `InferredType`.

If we choose the transformed type (make `ensure` strip `null` and `undefined`), we can better type transformation (we will have a better result for the return type of the `validate` function) but we would be inaccurately typing the validation (we would assume that our input has type `string` for that field even though it might actually have type `null`).

Personally I think it's better to go based on the validating type because it's more accurate albeit less convenient. In the long term, however, maybe we should consider trying to find a way to accurately type both (we'd need to attach two types to a schema).

**Comment by P4sca1** [comment]
Alright, makes sense. For now using ensure().required() does the trick afaik.

**Comment by msheakoski** [comment]
I learned about `defined()` today after running into some build errors when upgrading and reading the comments 😉. While changing things around, I noticed that the current type for `required()` does not seem to reflect yup's final validated value.

If you look at yup's source:

https://github.com/jquense/yup/blob/db35920b1ede4ea41ea90e1204b3da2a39787635/src/mixed.js#L352-L365

you will see that it is validating that the value can never be `null` or `undefined`. However, in the current typings (only first instance shown, but there are 10 total):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86f1c1be4efb93cc9959ab95a39c6ba0eeb4ab77/types/yup/index.d.ts#L94-L95

only `undefined` is excluded when `null` should also be excluded.

**Comment by iansan5653** [comment]
@msheakoski I agree - this definitely looks like an error. I don't think it's from this PR though; we just never noticed it because it's actually not that common to have a nullable schema without calling `nullable` and then it doesn't make sense to call `required`. That said we should still fix it. Would you be willing to open a new issue and possibly submit a PR?

**Comment by brunoebstein** [comment]
Hi,

given a schema with a `.default(value)`, why the output type is `someType | undefined` and not only `someType` ?

---

Example :
```typescript
const input = true;

const schema = boolean().default(false);

const result = schema.validateSync(input);
```

Current type : 
`result` is `boolean | undefined`

Expected type :
`result` is `boolean`

---

it's maybe the same question as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44589#issuecomment-631415003 but i'm not sure

**Comment by iansan5653** [comment]
@brunoebstein You are correct in that that is the same question as previously asked. Like I said there:

> we have to choose between the schema having the transformed type or the validated type.

We type against the validated type right now, not the transformed type. This means that the result is `boolean | undefined` because `boolean` values or `undefined` values will both pass the validation without error:

```ts
const inputA = true;
const inputB = undefined;

const schema = boolean().default(false);

schema.isValidSync(inputA); // true
schema.isValidSync(inputB); // true <-- This is why the schema type includes undefined
```

**Comment by msheakoski** [comment]
@brunoebstein Why not something like this?

```typescript
const inputA = true;
const inputB = undefined;

const schema = yup.boolean().required().default(false);

const resultA = schema.validateSync(inputA);
const resultB = schema.validateSync(inputB);

console.log("inputA", resultA); // true
console.log("inputB", resultB); // false
```

[Edit brunoebstein-example](https://codesandbox.io/s/yup-5hte1?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark)

**Comment by iansan5653** [comment]
@msheakoski The second result is appearing to invalidate `undefined` because it's `required()`, but it's actually defaulting to `false` because of the `default`, not because of a validation error.

**Comment by iansan5653** [comment]
@msheakoski 😅 That works now, but I just submitted a PR to fix it so that won't work for long (#45244). It only works now due to the fact that `default` is typed incorrectly. I do plan on submitting another PR soon that will fix the whole distinction with validated vs transformed types.

**Comment by Sytten** [comment]
@iansan5653 Can you put a TLDR at the top of the PR about the `defined` method. I wish that was more clear. I was pretty confused when I updated the lib today :S
I wish this repo had better CHANGELOG...

**Comment by leonardfactory** [comment]
Not sure if this is the right place to discuss this, but imho there is a major problem here.
I've got the difference between *validated* types and *transformed* types, however the problem arises specifically because these two can **both** be used in Yup, depending on functions called.

Obviously doing something like:
```ts
const s = undefined;
const schema = yup.string().default('alpha');
schema.isValidSync(s); // true
```
Returns `true` and we can only say that `s is ValidatedType`, so `s` could be `undefined | string`.

However, if this case is correctly handled by current typings, doing something like:

```ts
const s = undefined;
const schema = yup.string().default('alpha');
const t = schema.validateSync(s); // t is typed as string | undefined
```

Is pretty wrong, since `validateSync` returns **transformed** type, so we could say that `t is TransformedType` or `s is string`, and it is guaranteed that `t` is a *string*.

This PR (and current version) fixes many problem with yup typings, but this different use-case is not handled. I'm not sure we can do something here, but it should be handled, maybe with a typescript transformed type (i.e. `yup.TransformedType<Schema<T>>` with a recursived definition, that should be the right output for `validateSync`).

I'd like to know if there is some misunderstanding between my interpretation or if this could be an improvement to current typings.

**Comment by jquense** [comment]
That could be an improvement. The current types aren't fully correct and yes don't take into account certain things like how defaults affect validated values, etc.

**Comment by brandon-leapyear** [comment]
Quick question: this makes sense `{ x: yup.number() }` should be inferred as `number | undefined`, but it doesn't make sense to me that for
```ts
const schema = yup.object({ x: yup.number() })
```
`schema` should be `{x : number | undefined } | undefined`, because it can never be undefined
```ts
schema.validateSync(undefined) ==> { x: undefined }
```
I feel like this change should only apply to inner schemas, but the top-most schema (i.e. the result of `InferType`) should NOT include `undefined`. Thoughts?

**Comment by jquense** [comment]
That's not quite right,  `schema.validateSync(undefined)` maybe be undefined depending on what the `schema.default` is. It happens to be that objects come with a default, but it can be overridden

**Comment by brandon-leapyear** [comment]
Sure; so then shouldn't a plain `yup.object({ x: yup.number() })` be treated as
```ts
yup.ObjectSchema<{ x: number | undefined }> | { x: undefined }
```
? Or more generally, instead of adding `| undefined` to everything, it should be `| defaultType`, where `defaultType` is:

1. the type the value passed to `.default()`
1. `{ [P in keyof T]: undefined }` if the schema is an object
1. `undefined` otherwise

**Comment by jquense** [comment]
yup, to do this correctly you'd need to keep track of the default value in a generic

**Comment by brandon-leapyear** [comment]
sure, that would fix (1). But I'm talking about (2) - wouldn't it be more correct to change [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L334) to
```diff
-<T extends object>(fields?: ObjectSchemaDefinition<T>): ObjectSchema<T | undefined>;
+<T extends object>(fields?: ObjectSchemaDefinition<T>): ObjectSchema<T | AllUndefined<T>>;
```
where
```ts
type AllUndefined<T> = { [P in keyof T]: undefined }
```
?

**Comment by iansan5653** [comment]
`default` doesn't affect the types at all. The types are only 100% accurate for typing input objects in `strict` mode, which doesn't apply defaults or transformations.

**Comment by brandon-leapyear** [comment]
But I'm saying the types **aren't** 100% accurate. Without defaults or transformations, `yup.object()` would NEVER return `undefined` when validating an input

**Comment by iansan5653** [comment]
It's not about what the schema *returns*, it's about what the schema asserts the input type to be:

```ts
const myUnknownApiResponse: unknown = SOMETHING;
const myApiValidatorSchema = yup.object({a: yup.number().required()}).strict();

if(myApiValidatorSchema.isValid(myUnknownApiResponse)) {
  // now I know for certain that myUnknownApiResponse is either undefined or {a: number}
}
```

If you want to assert that whatever you're validating is defined, then:
```ts
const myUnknownApiResponse: unknown = SOMETHING;
const myApiValidatorSchema = yup.object({a: yup.number().required()}).defined().strict();

if(myApiValidatorSchema.isValid(myUnknownApiResponse)) {
  // now I know for certain that myUnknownApiResponse is {a: number}
}
```

**Comment by brandon-leapyear** [comment]
Ah I see. Thanks for the explanation! I guess I wasn't aware of the fact that "the types are **only** 100% accurate when using `.strict()`". Is this documented somewhere?

**Comment by jquense** [comment]
If we are only concerned with valid input types T probably should not be the return type of cast, especially since that is incorrect without accounting for defaults.

FWIW I don't think we should need strict() for types to work here. In practice that requires usage patterns that are not typical for most yup users. That said it's tough to get good types out of yup due to a bunch of API choices I made, and the current types do a good job despite my bad choices. I am hoping to try and take a stab at modeling types a bit differently so that the function as most folks expect, e.g. the return value of cast is correct

**Comment by jquense** [comment]
Also this isn't really the place for broader type conversations this PR is great and made the existing types more accurate. Happy to discuss further in the yup repo

**Pull request merged**
