### PR TITLE
[react] Added types for anchor 'target' attribute

### PR DESCRIPTION
**Pull request by priyanshurav**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Thanks! 

Let's add a test for an arbitrary target i.e. `<a target="some-frame"></a>` to make sure we don't remove the `string & {}` in the future.

**Comment by priyanshurav** [comment]
@eps1lon Thanks for the suggestion.

I have made the changes that you suggested

**Review by dimitropoulos — APPROVED** [review]
too bad we can't pull in `LiteralUnion` from `type-fest` because to the uninitiated this `string & {}` syntax is a bit hard on the eyes.

**Review by eps1lon — APPROVED** [review]

**Comment by priyanshurav** [comment]
@johnnyreilly Please merge this PR.

**Pull request merged**
