### PR TITLE
Update definitions according to the documentation

### PR DESCRIPTION
**Pull request by NN---**
https://developer.chrome.com/extensions/webNavigation

### CODE REVIEW

**Comment by vvakame** [comment]
@matthewkimber @otiai10 @pine613 could you review this PR?

**Comment by otiai10** [comment]
yes, sir @vvakame

**Comment by otiai10** [comment]
@NN--- 
cc: @vvakame 

I think it works well.

----------------

[IMO]
It might be that using `extends` of `interface` is better than declaring all properties of `GetAllFrameResultDetails`, like

```ts
interface GetAllFrameResultDetails extends GetFrameResultDetails {
    // you can declare additional properties
}
```

---------------

Thanks

**Comment by NN---** [comment]
@otiai10  Good idea, i'll change the code.

**Comment by vvakame** [comment]
@NN--- thanks mate!
@otiai10 thanks!

**Pull request merged**
