### PR TITLE
[google-drive-realtime-api] Typings for Error and ErrorType

### PR DESCRIPTION
**Pull request by Parent5446**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://developers.google.com/google-apps/realtime/reference/gapi.drive.realtime .
  - [ ] it has been reviewed by a DefinitelyTyped member.

Add typings for the Google Drive Realtime API's Error class and
ErrorType string enum (simulated in TypeScript as a union type and
static variable).

### CODE REVIEW

**Comment by mhegazy** [comment]
@DustinWehr can you please review this change

**Review by DustinWehr — APPROVED** [review]
Great thanks @Parent5446

**Comment by DustinWehr** [comment]
@mhegazy while you're here: my copy of this tsd file contains some extra interfaces and extends clauses on the Realtime API classes. I have them there for an abstraction level above the Realtime API that my codebase actually depends on, which I have an implementation of for offline, non-collaborative work that uses Maps and arrays and local storage. And in case I ever have to switch to a different service, e.g. one that uses Firebase or Meteor. 

My question is, should I make a pull request with that extra stuff in it? I'm conflicted because on one hand it's not strictly necessary, but on the other, I'm sure it would be useful to some people who would never find it if it was only on my own github account.

**Comment by DustinWehr** [comment]
@mhegazy Continuing from previous message, another option would be to put my version on my own github account, together with the code I've written to support it and the Realtime API, and just add a link to it in a readme file added to the google-drive-realtime-api directory.

**Comment by Parent5446** [comment]
Just curious, what's the next step in reviewing this?

**Comment by DustinWehr** [comment]
It's reviewed, and I think I did the necessary thing for the bot to notify the maintainer(s). I expect it'll get merged as soon as one of them has a chance.

**Comment by vvakame** [comment]
It merged. 
If you have other useful patches, please send our repository 😉

**Pull request merged**
