### PR TITLE
[next-auth] Important fixes and Adapter Types

### PR DESCRIPTION
**Pull request by JuanM04**
## What did I do?

> Latest commit in `next-auth` when this changes where made: `2f0f738e2e99e0bdadd0ef788031aa98fd2942de` (08-09-2020)

### General changes

- Created `_utils.d.ts`. This contains a simplified version of `NextApiRequest` and `NextApiResponse`, plus `GenericObject`.
- Fixed a important bug with `NextApiRequest`: when using, for example, `getSession` in `getServerSideProps`, the request inside the context object is `IncomingMessage` and not `NextApiRequest`, so I changed it in those places.
- Added `sameSite` union<sup>[1](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/server/lib/cookie.js#L78)</sup>.
- Made all `CookieOptions` optional and added `maxAge`<sup>[2](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/server/lib/cookie.js)</sup>.
- Fixed `SetOptionsParams` and set `Provider.options = SetOptionsParams`<sup>[3](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/client/index.js#L281)</sup>.
- Removed `getProviders` context<sup>[4](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/client/index.js#L136)</sup>.
- Made JWT secret optional<sup>[5](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/server/index.js#L66) [6](https://github.com/nextauthjs/next-auth/blob/eb26722833e970572c4fe82b2e0a55cb1e92df1f/src/server/index.js#L121)</sup>.

### Adapter Types

I did the Adapter Types following the source code. There are some would-be-nice-to-have, but can be added later.

## DefinitelyTyped To-do

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by lluia** [comment]
@JuanM04 thanks for these improvements 💯 😍 , I won't be able to review this in deep until Monday 😅 , hope that's ok 🤞🏽

You're contributing a lot to the types, would you like to be added as a maintainer of them along myself? (_basically you just need to add your name on the comment header of_ `index.d.ts`)

**Comment by JuanM04** [comment]
There is no rush, @lluia. I have some work to do, but I'm a bit busy.

> would you like to be added as a maintainer of them along myself?
I would be nice, maybe I'll do it

**Comment by JuanM04** [comment]
Ignore what I did... I wrongly resolve the merge conflicts, but now it should be OK.

**Review by 0ubbe — APPROVED** [review]
Nice 💯  💪🏽

**Comment by JuanM04** [comment]
Ready to merge

**Pull request merged**
