### PR TITLE
Update OperationOptions to accept an array of timeouts in the retry module

### PR DESCRIPTION
**Pull request by mionim**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/tim-kos/node-retry/blob/master/lib/retry.js#L13-L15>>

### CODE REVIEW

**Comment by MiOnim** [comment]
Will this change publish new version for all other packages that depend on the `retry` package as well? If not, how can I force publishing new version for other packages? To be specific, `promise-retry` package depend on the types from the `retry` package, and I'd like to get a new version of `promise-retry` typings to get published as well.

**Comment by sandersn** [comment]
This changes makes sense to me, but retry is so widely used that I'd like signoff from at least one retry owner. @krenor @BendingBender? Should `operation` take a `number[]`?

**Comment by BendingBender** [comment]
@sandersn Actually, it looks like `timeouts()` accepts a `number[]` as input, too (see https://github.com/tim-kos/node-retry/blob/11efd6e4e896e06b7873df4f6e187c1e6dd2cf1b/lib/retry.js#L3-L15). But I'm probably not a good reviewer for this kind of things, I haven't used the module in a very long time.

**Comment by MiOnim** [comment]
@BendingBender you're right, `timeouts()` also accepts `number[]` as input. I hadn't noticed that because I'm not really using the `timeouts()` function. Let me know if you'd like me to update typings for `timeouts()` as part of this PR as well.

**Comment by sindresorhus** [comment]
FYI, this broke a `retry` dependent package: https://github.com/sindresorhus/p-retry/issues/64

**Comment by alecf** [comment]
this broke `@types/async-retry` which has a `retries` parameter which is now no longer in the Options interface

**Comment by BendingBender** [comment]
We should maybe add tests for these packages to anticipate further breakages. But ultimately, a long as these typings are not part of the package, there's not much we can do to prevent this. Maybe stick to not ever renaming types.

**Comment by deanc** [comment]
Confirming this broke async-retry. This should not have been merged.

**Comment by alfaproject** [comment]
Also confirming that this broke `async-retry` ):

**Comment by blaenk** [comment]
Given the breakage this has caused, it seems to me like it would be sensible to revert this PR and those interested in this functionality can try again later.

I propose this specifically versus waiting to get this feature working and tested correctly because meanwhile this has broken for all of us that aren't even using this new feature.

Especially since we haven't heard back from OP here yet. No pressure on OP by any means, I'm sure they're busy, but it just seems like we might as well revert this in the meantime given it has broken things, and if they're so interested in this feature they are best motivated to get it working correctly but without us waiting on it.

Is anyone against this?

**Comment by blaenk** [comment]
By the way, @strmer15 commented here https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6f77b38130593a06e1988f1d3df162823ae186af#commitcomment-73774224 that it works if you have `@types/retry` at `0.12.2` and I can confirm that that worked for me.

After installing that, my `yarn.lock` still resolved `@types/retry` to another version before `0.12.2` but once I removed that and re-ran `yarn install` to regenerate the lock file, it now froze it to `0.12.2` and I can confirm that it works.

As @strmer15 pointed out, it may be necessary to express `@types/retry` as a dependency of `@types/async-retry`, but I'm not familiar with those details.

**Pull request merged**
