### PR TITLE
Add node-notifier

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by vvakame** [comment]
*node-notifier/node-notifier.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/node-notifier
  * http://bower.io/search/?q=node-notifier
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (node-notifier/node-notifier-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@tkQubo thank you for your contribution.
please rename node-notifier/node-notifier-test.ts to node-notifier/node-notifier-tests.ts

**Comment by tkQubo** [comment]
I renamed test file @vvakame

**Comment by vvakame** [comment]
@tkQubo thanks mate!

**Pull request merged**
