### PR TITLE
Update prosemirror-* to 0.21

### PR DESCRIPTION
**Pull request by bradleyayers**
This PR updates most of the prosemirror-* packages to 0.21 it's done as a single PR, because there are many inter-package dependencies that were too difficult to separate.

The updates packages are:

- prosemirror-collab
- prosemirror-commands
- prosemirror-history
- prosemirror-inputrules
- prosemirror-keymap
- prosemirror-markdown
- prosemirror-menu
- prosemirror-model
- prosemirror-state
- prosemirror-transform
- prosemirror-view

These changes have been tested against a large project using ProseMirror.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by bradleyayers** [comment]
@davidka can you give a 👍?

**Review by davidka — APPROVED** [review]

**Comment by bradleyayers** [comment]
@yuit, @davidka gave an approval but not using the emoji, are we fine to proceed with merging?

**Review by davidka — APPROVED** [review]
👍

**Comment by minestarks** [comment]
@bradleyayers sorry, the branch now has conflicts. Could you resolve them and I'll merge. Thanks.

**Comment by bradleyayers** [comment]
@minestarks fixed, thanks!

**Pull request merged**
