### PR TITLE
[animejs] Add  missing optional `unit` parameter to `get()` helper function

### PR DESCRIPTION
**Pull request by slavanossar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [anime.js Documentation – `get()` Helper](https://animejs.com/documentation/#get)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## animejs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/animejs@latest/))
was missing the following properties:
1. convertPx
1. easing
1. penner
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2e64f055715b107df0cc3dee2f7fa25771ede6ca
</p>

**Comment by slavanossar** [comment]
I was considering adding a `CSSUnits` type that covers all available CSS length units – is this advisable or overkill?

**Review by MysteryBlokHed — APPROVED** [review]
LGTM!

**Comment by slavanossar** [comment]
Ready to merge

**Comment by MysteryBlokHed** [comment]
> I was considering adding a `CSSUnits` type that covers all available CSS length units – is this advisable or overkill?

I feel it's alright to keep it typed as `string`, but you could wait for one of the definition owners to answer if you'd like

**Pull request merged**
