### PR TITLE
spdx-correct & spdx-satisfies: support `import * as foo` style

### PR DESCRIPTION
**Pull request by jinwoo**
this change will support both `import foo = require(...)` style and
`import * as foo from ...` style.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jinwoo** [comment]
I'm not sure who should/will review this PR because I'm the original author... Hmm...

**Comment by jinwoo** [comment]
@sandersn Would you mind reviewing this because you reviewed my original PR? Thanks!

**Review by sandersn — CHANGES_REQUESTED** [review]
This is not correct; according to spec `import * as x from 'x';` makes an `x` that is *not* callable. It's just a mistake of the Typescript compiler that it doesn't give an error here.

**Comment by jinwoo** [comment]
Interesting. I see some existing .d.ts files do this already. Why should TS not allow `x` to be callable? In my opinion, that seems an arbitrary limitation.

But I'll close this if that's what TS team thinks.

**Comment by sandersn** [comment]
Yes, unfortunately DefinitelyTyped is far from correct.

The problem is that only certain module loaders will allow `import * as x` to be callable; strictly Ecmascript-spec-compliant module loaders will not. In addition, `export = x` is not Ecmascript syntax; I think it makes sense to match non-Ecmascript imports with non-Ecmascript exports.

**Pull request closed without merging**
