### PR TITLE
fix(styled-components): remove insections on resulting StyledComponentProps

### PR DESCRIPTION
**Pull request by erictaylor**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

When using `styled-system` with `styled-components` the `color` property commonly gets overwritten. By default `color` on JSX intrinsic elements are typed as `color?: string`. But with styled-system the prop can support `string | number | symbol | null` along with an array of those types or a keyed object of those types (see `ColorProps` from `styled-system`).

Currently before this change, `color` would come back typed as:

```
string | (string & (string | number | symbol | null)[]) | (string & {
    [x: string]: string | number | symbol | undefined;
    [x: number]: string | number | symbol | undefined;
}) | undefined
```

After this change the `color` type comes back as:

```
string | number | symbol | (string | number | symbol | null)[] | {
[x: string]: string | number | symbol | undefined;
[x: number]: string | number | symbol | undefined;
} | null | undefined
```

Without this change the following fails.

```tsx
function unionTest3() {
    // Can occur when working with styled-system
    // and the `color` prop.
    interface Props {
        color: number | string | Array<string | number | null> | { [x: string]: string | number; [x: number]: string | number; } | null;
    }

    const C = styled.p<Props>``;

    <C color={2} />;  // Fails
    <C color={["test", null, 2]} />; // Fails
    <C color={null} />; // Fails
    <C color={{ foo: "bar" }} />; // Fails
    <C color={{ 1: "foo" }} />; // Fails
}
```

This removes an incorrect intersecting of prop types.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## styled-components ([<kbd>unpkg</kbd>](https://unpkg.com/browse/styled-components@latest/))
was missing the following properties:
1. StyleSheetConsumer
1. StyleSheetContext
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f58daf28df89bf2e3e5310e6d812886040787b4b
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
I'm not so sure about that change. I think the error was intended since `color` is a HTML attribute. Since styled-component does not intercept props it has to be compatible with the underlying component.

It's very likely that this won't cause serious problems but what about cases where the styled component does interact with the prop:

```ts
import * as React from 'react';
import styled from 'styled-components'

function Component({ color }: {color: string}) {
    return <React.Fragment>{color.endsWith('green')}</React.Fragment>;
}

const StyledComponent = styled(Component)<{ color: number }>``;

<Component color="123" />;
// @ts-expect-error - or it'll throw at runtime
<StyledComponent color={123} />;
```

So maybe just restrict this PR to host components? 

I'm generally not sure about this feature since it was never reported i.e. does this fix more issues than it can cause?

**Comment by erictaylor** [comment]
@eps1lon I appreciate your timely response.

> I'm generally not sure about this feature since it was never reported i.e. does this fix more issues than it can cause?

I think this fixes more issues than it causes.

Ignoring the specific use case of `styled-system` and the `color` prop specifically, `StyledComponentProps` is not currently returning the expected merged types. Currently it is returning odd intersections vs properly merging the types into a union. See my original post for the return type comparison.

**Given your example, what do you expect the type for `color` to be on `StyledComponent`?** Before this change, the type of `color` in your example would be `never`. With this PR the type would be `string | number`. Neither are totally correct. 

**Here is the use case we run into all the time when using `system-system` and `styled-components` currently:**

```
import * as React from 'react';
import styled from 'styled-components';
import { space, layout, color, flexbox, SpaceProps, LayoutProps, ColorProps, FlexboxProps } from 'styled-system';

interface BoxProps extends SpaceProps, LayoutProps, ColorProps, FlexProps {}

const Box = styled.div<BoxProps>`
  ${space}
  ${layout}
  ${color}
  ${flexbox}
`;

interface CardProps {
  foo?: number;
}

const StyledCard = styled(Box)<CardProps>`
  box-shadow: 0px 0px 40px red;
`;

const Card = (props: CardProps) => (
  // Gives a TS error on `color` prop.
  <StyledCard {...props} />
);
```

Again the issue here is that `color` in this case is being typed as (note the intersections `(string & (string | number | symbol | null)[])`)

```
string | (string & (string | number | symbol | null)[]) | (string & {
    [x: string]: string | number | symbol | undefined;
    [x: number]: string | number | symbol | undefined;
}) | undefined
```

opposed to what I would expect:

```
string | number | symbol | (string | number | symbol | null)[] | {
[x: string]: string | number | symbol | undefined;
[x: number]: string | number | symbol | undefined;
} | null | undefined
```

**Comment by eps1lon** [comment]
> With this PR the type would be string | number. Neither are totally correct given your example.

Seems to me it is. If the wrapper component requires a `string` and the inner component a `number` then there exists now type that satisfies both components. If this doesn't cause you any trouble then you can make a judgement call and ignore the error. With your change we would allow types we know are incorrect without the type-system hinting at this.

> Here is the use case we run into all the time when using system-system and styled-components currently:

What happens if you use the actual type
``` diff
-const Card = (props: CardProps) => (
+const Card = (props: React.ComponentProps<typeof StyledCard>) => (
  // Gives a TS error on `color` prop.
  <StyledCard {...props} />
);
```
?

> I think this fixes more issues than it causes.

That's all well and good and implicit by proposing a change. It was more an invitation to other collaborators to share their opinion.

**Comment by erictaylor** [comment]
> What happens if you use the actual type
> 
> ```diff
> -const Card = (props: CardProps) => (
> +const Card = (props: React.ComponentProps<typeof StyledCard>) => (
>   // Gives a TS error on `color` prop.
>   <StyledCard {...props} />
> );
> ```
> 
> ?

`props` ends up coming back as:

```
StyledComponentPropsWithAs<"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 157 more ... | React.FunctionComponent<...>, DefaultTheme, BoxProps & CardProps, never>
```

But I think there is an `any` index signature being applied because:

```
const Card = (props: React.ComponentProps<typeof StyledCard>) => (
  <StyledCard {...props} />
);

<Card aNonExistantProp="hello" />; // <-- This doesn't throw an error.
```

it just starts excepting whatever you give it.

**Comment by erictaylor** [comment]
Screen Shot 2020-08-18 at 11 00 24 AM

There is an index signature of `any` being applied.

**Comment by eps1lon** [comment]
This has to simmer in my brain for a bit. I'd be way more comfortable if this would be restricted to host components. For those we don't get any crashes if we pass wrong types and at least get a dev warning. For composite components this change could be quite dangerous.

**Comment by erictaylor** [comment]
@eps1lon if you have an ideas on how to solve this issue while avoiding this issue you brought up feel free to make a recommended change. You are far more familiar with the types than I am, I'm not sure how to restrict this change to just host components, but if pointed in the right direction I'd be happy to see if it solves my use case.

**Comment by erictaylor** [comment]
@eps1lon just want to follow up and see if you have any new thoughts on this?

Pinging @Igorbek @Igmat @Jessidhia @JKillian @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs for comment.

**Comment by eps1lon** [comment]
> @eps1lon just want to follow up and see if you have any new thoughts on this?

Could you include https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46850#pullrequestreview-469109450 as a test and document that this isn't desired?

> <C color={["test", null, 2]} />; // Fails

Could you provide a codesandbox so that I can take a look at the runtime behavior? Last I remember this ends up as `<p color="[object Array]" />` and we do want type-checking to reject it just like we would reject `<p color={["test", null, 2]} />`.

**Comment by erictaylor** [comment]
> Could you include #46850 (review) as a test and document that this isn't desired?
@eps1lon is 7201d7b what you wanted?

>Could you provide a codesandbox so that I can take a look at the runtime behavior? Last I remember this ends up as `<p color="[object Array]" />` and we do want type-checking to reject it just like we would reject `<p color={["test", null, 2]} />`.

https://codesandbox.io/s/definitelytyped-pr-46850-kjsx7

**Comment by eps1lon** [comment]
> [codesandbox.io/s/definitelytyped-pr-46850-kjsx7](https://codesandbox.io/s/definitelytyped-pr-46850-kjsx7)

This is what I expected: `<div color="red,,blue">`

We reject `<div color={["red", null, "blue"]}>` in `@types/react` as well so I don't feel comfortable allowing it in `styled-components`.

**Comment by erictaylor** [comment]
While I understand the desire to prevent the runtime error that @eps1lon brings up, I still believe that this PR offers a fix to an issue with the returned prop types as described in the original post . I'm dismissing the review to put this back in the queue and hopefully get some other opinions from other maintainers as well.

**Comment by erictaylor** [comment]
@eps1lon I have made adjustments on a8682b7 that follows your suggestion of limiting this change to host components. Take a look and see if this addresses your main concern.

**Comment by erictaylor** [comment]
Superseeded by #47808.

**Pull request closed without merging**
