### PR TITLE
[node] Add "signal" to NodeJS's AddEventListenerOptions

### PR DESCRIPTION
**Pull request by matthieusieben**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/events.html#eventtargetaddeventlistenertype-listener-options
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by Semigradsky — CHANGES_REQUESTED** [review]
Please add changes also to other Node.js versions: `v18/dom-events.d.ts`, `v16/dom-events.d.ts`
and to TS<=4.8 versions: `ts4.8/dom-events.d.ts`, `v18/ts4.8/dom-events.d.ts`, `v16/ts4.8/dom-events.d.ts`

**Comment by matthieusieben** [comment]
@Semigradsky done :-)

**Review by Semigradsky — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]
@matthieusieben thanks!

**Comment by jakebailey** [comment]
I deleted ts4.8 in #68908, you'll have to update the PR again (sorry!)

**Comment by peterblazejewicz** [comment]
@matthieusieben I've taken the liberty to refresh the PR (rebasing against current master), as this PR took already long time to get here. Thanks!

**Review by peterblazejewicz — APPROVED** [review]
re-approving as in Semigratsky's vote

**Review by Semigradsky — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
