### PR TITLE
`update-notifier`:add `UpdateNotifier` as export

### PR DESCRIPTION
**Pull request by brettz9**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

(Note that the existing tests are failing, but this addition does not cause a failure. I didn't see need to add a test for this minor change.)

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: N/A. The PR is just re-exporting an existing type.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@brettz9 thanks!

**Comment by peterblazejewicz** [comment]
failing tests due to upstream module updates, fixing here #65549

**Comment by brettz9** [comment]
Can these tests be run again?

**Comment by brettz9** [comment]
Ready to merge

**Pull request merged**
