### PR TITLE
Added declaration for the writeFile function

### PR DESCRIPTION
**Pull request by bragle**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js & https://github.com/mscdex/ssh2-streams/blob/master/lib/sftp.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ssh2-streams ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ssh2-streams@latest/))
was missing the following properties:
1. constants
## ssh2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ssh2@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'ssh2'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1dea91d0a112eef9088c70c9d8a97834fbdcaca3
</p>

**Comment by bragle** [comment]
Hey @rbuckton. I hope I'm not bothering you, but would you be able to take a look at the changes here? There's only about 12 lines of actual code, so it shouldn't take a lot of time to review. I'm very sorry for atting you, but it would be great to get this sorted 😸

**Comment by bragle** [comment]
Hey @sandersn. Please excuse me for pinging you. I saw that you were the last active DT-maintainer, so I'm wondering if there's any possibility of getting this resolved?

**Review by peterblazejewicz — COMMENTED** [review]
@bragle 
mind adding tests? these packages are labelled as popular one. When added probably it would be easier to review this by any other DT user.
can you also review the versioning? Are those options added in version now linked (0.1 and 0.5) or were they added later (so 0.4 and 0.8 versions can be ameneded as well).

**Comment by bragle** [comment]
Hey @peterblazejewicz! Thanks for the reply! I've added tests for both readFile and writeFile in ssh2-streams. Looks like the tests added to the ssh2 package is copy pasta from the examples in the [ssh2 repo](https://github.com/mscdex/ssh2).
Regarding versioning, these functions have been there since the first releases (see [ssh2](https://github.com/mscdex/ssh2/blob/9a539e634c038ae663a88bc28a7d19e3703e725f/lib/SFTP/SFTPv3.js#L463) and [ssh2-streams](https://github.com/mscdex/ssh2-streams/blob/344a8ed8fe41425aa7767d407bde38d2fbb6570d/lib/sftp.js#L1248)) 😸

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@bragle thx!

**Review by sandersn — CHANGES_REQUESTED** [review]
I don't know ssh2-streams, but the code seems reasonable; if there's a problem either @bragle or @rbuckton can back the change out.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
