### PR TITLE
Make d3-array work with stirctNullChecks

### PR DESCRIPTION
**Pull request by denisname**
Validate d3-array for stirctNullChecks #11365.

Add tslint.json
Set strictNullChecks to true
In d3-array-tests.d.ts:
* Changes variables names to make undefined _explicit_
* Add accessors functions
* Add tests for mean, median, quantile, sum, deviation, variance and scan

In index.d.ts:
* Add undefined to Primitive type
* Remove useless declarations (number extends Numeric)
* Add unions of undefined where needed
* Improve permute with keyof

I removed the two next lines:

```typescript
// in d3-array-tests.d.ts
extentMixed = d3Array.extent<NumCoercible>([new NumCoercible(10), 13, '12', true]);
// in index.d.ts
export function extent<T extends Numeric>(array: Array<T | Primitive>): [T | Primitive, T | Primitive] | [undefined, undefined];
````

I don't get the goal of this. It seems more like a way to "lower" the type checker than something really useful. Also, min and max don't have such signature although they can work the same way...
Feel free to put it back...

Waiting for review (@tomwanzek, @gustavderdrache).
When good, I will add JSDoc comments.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [d3-array readme](https://github.com/d3/d3-array/blob/master/README.md)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by aozgaa** [comment]
Thoughts @gustavderdrache, @borisyankov, @tomwanzek ?

**Comment by tomwanzek** [comment]
@denisname thanks for the PR. I likely won't get to review details before the weekend. Possibly, @gustavderdrache can chime in already.

Thanks for removing the TS 2.1 feature for now. I reckon, it is time to develop a general migration strategy for the definitions w.r.t. TS <2.1 and >=2.1, i.p. `keyof`

This seems to be worth a discussion issue to assess benefits at a per D3 module level and then square it up against the effort for definition updates and parallel maintenance of definitions in two different versions for a reasonable period. @gustavederdrache Thoughts?

Cheers, T

**Comment by gustavderdrache** [comment]
This looks really good!

The old overload you stripped out wasn't intended to lower the type, but to support the case where a mixed-type array was present. I used it in the v3 typings, which was around... TS1.4, I believe. Now that the language is much stricter, I think it's a relic that we can safely ignore. It's always possible to resurrect if people found it useful.

Unfortunately, I don't have any projects that are ready for strictNullChecks, so I'd like to ask if there are any plans to accommodate `null` in the types of e.g., `extent` or `sum`. My understanding is that TS considers the two types to be different.

As a final note (and one change I'd like to see made), `d3.extent` allows your accessor to return `undefined` (or even `null`) in order to skip a value (see the [documentation](https://github.com/d3/d3-array#max) and [extent.js](https://github.com/d3/d3-array/blob/master/src/extent.js#L18). I use this at work pretty heavily to avoid the extent capturing invalid flag values:
```ts
const extent = d3.extent(array, d => {
  if (d !== 99999) {
    return d;
  }
});
```
It looks like you could simply change the return type of the accessor from `U` to `U | undefined` and call it a day.

**Comment by tomwanzek** [comment]
Looks good overall. Here are a couple of questions:

(1) Both `null` and `undefined` appear to be consistently ignored by **d3-array** statistics methods. The proposed changes include amending the exported definition of the union type for `Primitive` to include `undefined`. Would it be better to keep `Primitive` to reflect only the _"defined"_ primitives and where applicable rather use `Primitive | undefined`, `Primitive | null` or `Primitive | undefined | null`, as applicable? IMHO, I am leaning to keeping `Primitive` narrower as it is exported for use elsewhere.

(2) Has Histogram been reviewed for `strictNullChecks`?

Thanks @denisname for working on this!!! T

**Comment by gustavderdrache** [comment]
LGTM. Thanks for working on this! :+1:

**Comment by tomwanzek** [comment]
Same here 👍

**Comment by denisname** [comment]
Thank you for your positive feedbacks. But I haven't finished it yet...

I reviewed histogram for strictNullChecks. Its operation with undefined values is not documented. So I did not add it at first. As I did not with `d3-array` statistics methods for null values.

I started adding it. But it's more complex than for statistics methods. I will make another pull request this week with histogram changes.

**Comment by tomwanzek** [comment]
@denisname Thx for the separate, continued  effort!!! Yes, sometimes the only thing that worked for me as well, was digging through the source code. When you open the PR, I will look at the `histogram` again as part of the review. Most indebted in advance! T

**Pull request merged**
