### PR TITLE
Update to fix AMD/UMD module imports

### PR DESCRIPTION
**Pull request by a904guy**
Updated to export a proper module as well as the declared global var.

### CODE REVIEW

**Comment by a904guy** [comment]
@ejsmith, Can you give a :+1: on this?

**Comment by ejsmith** [comment]
:+1:

**Comment by a904guy** [comment]
Thank you. 

@vvakame, Good to go.

**Comment by vvakame** [comment]
@ejsmith thanks!
@a904guy thanks mate!

**Comment by a904guy** [comment]
Cheers

**Pull request merged**
