### PR TITLE
mixpanel-browser@2.38.0: Remove `track_pageview` config option

### PR DESCRIPTION
**Pull request by koshov**
mixpanel-browser@2.38.0 [removes `track_pageview` config option altogether](https://github.com/mixpanel/mixpanel-js/commit/897f58ca74b5d8a1fedd0fd8ad4900dadbccfee3)

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mixpanel/mixpanel-js/commit/897f58ca74b5d8a1fedd0fd8ad4900dadbccfee3
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mixpanel-browser ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mixpanel-browser@latest/))
was missing the following properties:
1. config
1. request_batchers
1. persistence
1. cookie
1. unpersisted_superprops

<details>
<summary>as well as these 7 other properties...</summary>
<p>are_batchers_initialized, init_batchers, start_batch_senders, stop_batch_senders, track_pageview, name_tag, toString</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 47b74d3644ea5c6bcdeeb09e5b4f003b738f4d1c
</p>

**Review by moreal — COMMENTED** [review]
It looks good to me! 👍🏻 

About API changes in 2.40.0, in my thought, this pull request should be separated to 2.38.0, 2.40.0, 2.43.0 for 2.36 users, 2.40 users, 2.43 users, 🤔 But I'm not sure about this project (`@types/mixpanel-browser`)'s convention. How do you think about this, maintainers?

**Comment by koshov** [comment]
Hey, sorry for the delay, I'll split up the PR for each API change and get back later this week.

**Comment by moreal** [comment]
> Hey, sorry for the delay, I'll split up the PR for each API change and get back later this week.

Thank you for your care. Because I'm not sure about that convention, I wanted to listen to other maintainers' opinions but they seem busy 😥 
But I think it will be correct. Please don't feel hard to ask questions! If you need reviews or questions, mention me (`@moreal`) then I'll reply as soon as possible! 🙏🏻

**Comment by koshov** [comment]
Updated PR to only include earliest changes from mixpanel-browser@2.38.0 [removes `track_pageview` config option altogether](https://github.com/mixpanel/mixpanel-js/commit/897f58ca74b5d8a1fedd0fd8ad4900dadbccfee3)

I'm busy creating additional PRs for the following changes.

**Review by moreal — APPROVED** [review]
It looks good to me! Thanks for your contribution!

**Comment by moreal** [comment]
> Updated PR to only include earliest changes from mixpanel-browser@2.38.0 [removes `track_pageview` config option altogether](https://github.com/mixpanel/mixpanel-js/commit/897f58ca74b5d8a1fedd0fd8ad4900dadbccfee3)
> 
> I'm busy creating additional PRs for the following changes.

Other parts can be implemented by others or me. Thank you for your contribution though you're busy! 🙌🏻

**Review by amcasey — APPROVED** [review]

**Comment by koshov** [comment]
Ready to merge

**Pull request merged**
