### PR TITLE
add webvr-api definition

### PR DESCRIPTION
**Pull request by nakakura**
I added a definition of WebVR draft.

### CODE REVIEW

**Comment by vvakame** [comment]
*webvr-api/webvr-api.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/webvr-api
  * http://bower.io/search/?q=webvr-api
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (webvr-api/webvr-api-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@nakakura thank you for your contributions.
please rename webvr-api/webvr-api-test.ts to webvr-api/webvr-api-tests.ts

**Comment by nakakura** [comment]
Thank you @vvakame san.
I renamed it. Sorry.

**Comment by vvakame** [comment]
@nakakura thanks mate!

**Pull request merged**
