### PR TITLE
Include inputOptions for bootbox.prompt

### PR DESCRIPTION
**Pull request by bickycheese**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by vbortone — APPROVED** [review]

**Comment by vbortone** [comment]
👍

**Comment by stannynuytkens** [comment]
I think I might also add `group` from the [documentation](http://bootboxjs.com/documentation.html#bb-prompt-dialog). I somehow forgot that. But I'm figuring out how to amend that to this pull request, can anyone help me out?

**Comment by trodi** [comment]
@stannynuytkens, updating your branch will update the pull request as you might have already figured out. It looks like you've merged Master in a number of times as well. You should delete these commits (If there were conflicts with master, you'd need to rebase with master, but I don't believe that's the case).

You'll also want to squash your two commits (`git rebase -i head~2`) so they become one commit.

**Comment by yuit** [comment]
@stannynuytkens once comment by @trodi is addressed, I will merge in. Thanks for PR

**Comment by stannynuytkens** [comment]
@yuit @trodi, will do tonight, thx guys

**Comment by stannynuytkens** [comment]
@yuit fixed it and updated `bootbox-tests.ts`

**Comment by stannynuytkens** [comment]
@yuit @trodi @vbortone when will this be merged?

**Comment by trodi** [comment]
👍 
This looks good to merge now. @stannynuytkens, someone else who has write permissions will have to do the merge. Nothing is blocking the merge now.

**Comment by yuit** [comment]
@trodi  @vbortone thanks

**Pull request merged**
