### PR TITLE
feat(get-sass-vars): remove types

### PR DESCRIPTION
**Pull request by hkleungai**
See [v3.2.0 release note](https://github.com/niksy/get-sass-vars/releases/tag/v3.2.0).

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:

- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by manuth** [comment]
I will not approve this right now.
At time of writing (30th November, 2024), the type declarations of `get-sass-vars` is broken.

I think it might be a good idea to first file an issue and have the issue fixed before removing the types from here.

What do you, @hkleungai (and the DT-maintainers, if you're reading this) think?

**Comment by manuth** [comment]
I opened up a PR at `get-sass-vars`.
Let's best wait for it to get merged first, right?

https://github.com/niksy/get-sass-vars/pull/13

**Comment by hkleungai** [comment]
Hello @manuth, I have just checked a bit, I find that the broken-type issue you mentioned actually happens on latest v4 of the package. But if you check the [latest v3 version](https://www.npmjs.com/package/get-sass-vars/v/3.4.0?activeTab=code), the types work just fine.

Since removing types from DT actually means deprecating (but not removing) the package in npm, and deprecating `@types/get-sass-vars` v3 against a correctly-typed `get-sass-vars` v3 does sound valid to me, hence I think this PR is not necessarily blocked by yours.

Of course, DT owners may have different opinion. Let's wait for more comments. 😂

**Comment by manuth** [comment]
Aaah you're right
Should be fine, then, I guess

**Review by neurolag — COMMENTED** [review]
LGTM!

**Review by neurolag — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by hkleungai** [comment]
Ready to merge

**Pull request merged**
