### PR TITLE
webxr: add class declarations so `instanceof` can be used to test types

### PR DESCRIPTION
**Pull request by capnmidnight**
There are particular cases, such as managing WebXR Layers on the Oculus Quest, where it is very useful to type-inspect the layers (e.g. the layers all store in a single collection, but there can be only one XRProjectionLayer).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by RaananW — COMMENTED** [review]
Wow, great update!

I understand the need for instanceof (personally not a big fan, but it is a native js function, and is helpful in many cases, so... :-)).
I am not sure if having both interface and class is needed.
Anything implementing (and not extending) one of those interfaces/classes will require "prototype" to be present (i.e. - will have to be a class and no longer an interface). 
Also - most of those classes cannot be constructed but defining them as classes will technically allow that (type-wise).
TypeScript's lib.d.ts solves it by using declare var instead of declare class, adding `new();` to elements that can be constructed. would that be an acceptable solution here?

**Comment by capnmidnight** [comment]
Yes, that sounds good. I'll make that change now.

**Comment by capnmidnight** [comment]
Okay, I think the fix here is actually to change many of these interfaces to abstract classes. TypeScript lets you create interfaces that are extensions of classes, and that works just like if the class were an interface. But there are cases where a type *is* a class, is testable with `instanceof`, but no legal constructor is defined. For example, `XRSession` cannot be instantiated with `new`, but it does have a prototype and it can be tested with `instanceof`. So cases like those should be abstract classes.

I wasn't too clear on the differences between `declare var` versus `declare class`, so I tried a number of iterations to see what features they support. In doing this and seeing the results, I don't get the purpose of setting the prototype on anything.

| | is value | is type | `new`-able | `instanceof`-able | interface `extends`-able | class `implements`-able | class `extends`-able | ex. types |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| interface | ❌ | ✔️ | ❌ | ❌ | ✔️ | ✔️ | ❌ | XRSessionInit |
| declare var | ✔️ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | Values on Window: title, innerHeight, innerWidth, setTimeout, etc. |
| declare var w/ prototype | ✔️ | ❌ | ❌ | ❌ | ❌ | ❌ | ❌ | |
| declare var w/ constructor | ✔️ | ❌ | ✔️ | ✔️ | ❌ | ❌ | ✔️ | Audio |
| declare var w/ constructor and prototype | ✔️ | ❌ | ✔️ | ✔️ | ❌ | ❌ | ✔️ | |
| interface + declare var | ✔️ | ✔️ | ❌ | ❌ | ✔️ | ✔️ | ❌ | |
| interface + declare var w/ prototype | ✔️ | ✔️ | ❌ | ❌ | ✔️ | ✔️ | ❌ | |
| interface + declare var w/ constructor | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | |
| interface + declare var w/ constructor and prototype  | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | Map, HTMLAudioElement |
| declare abstract class | ✔️ | ✔️ | ❌ | ✔️ | ✔️ | ✔️ | ✔️ | XRSession, OCULUS_multiview, XRQuadLayer |
| declare class | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | XRRigidTransform, XRWebGLBinding |

In lib.d.ts, there are no instances of `declare class` of any kind. There's a curious example in `Audio` vs `HTMLAudioElement`.  `Audio` is a value, it's not a type, it's `new`-able, it's `instanceof`-able (with both itself and HTMLAudioElement), it's not `interface extends`-able, but it is `class extends`-able. I'm guessing that such pattern is necessary for legacy code, but probably isn't the best idea to use.

So I'm left wondering what the difference is between:

- Declaring a var that has a just a constructor **versus** one that has a constructor and prototype (no overlap with a same-named interface). lib.d.ts uses the former sparingly, but not the latter.
- Creating an interface and declaring a var of the same name with just a constructor **versus** one that has a constructor and prototype. lib.d.ts uses the latter liberally, but not the former.
  - This seems to be a mistake for HTMLAudioElement, because HTMLAudioElement is not `new`-able
  - Why not declare a class instead, which seems like it's less work.

It seems like types like XRSession, XRQuadLayer, etc., that cannot be directly instantiated, but are values and types and `instanceof`-able, should be abstract classes.

As for types like XRRigidTransform that **can** be directly instantiated, I think `declare class` is cleaner than `define an interface, declare a same-named var that defines a constructor and prototype`.

**Comment by capnmidnight** [comment]
Alright, with this I now have:

- Interfaces for all the types I know about
- Classes implementing those interfaces for anything directly instantiable (e.g. XRRigidTransform)
- Abstract classes implementing interfaces for anything not directly instantiable (e.g. XRSession)

One factor I forgot in my previous message was that interfaces are open and extendable in TypeScript, but `type`s and `class`es are not. So by keeping the interfaces, I was also able to split up the definitions of the draft features that modify types like XRSession and XRFrame to keep them closer together in the source file. This will also let anyone else modify their own interface definitions locally, if they need newer, as-yet-developed features before they can make it into the official repo.

**Comment by capnmidnight** [comment]
I got bored and read through the WebXR Device API to make sure everything was in there, then added links to each of the sections of the documentation.

@RaananW if this can get approved soon, I have a PR to make to three-ts-types to update the Three.js typings.

**Review by RaananW — APPROVED** [review]
TBH I am not sure about an abstract class for objects that are not abstract. I am sure you have tested it (and will also be honest that I haven't tested this specific case).
I think it's a matter of taste in that case, as I don't see any technical issue with that, except for semantics.

**Comment by capnmidnight** [comment]
Ready to merge

**Comment by robrohan** [comment]
> @capnmidnight Is there a good place to file bugs on the WebXR types?

I initially added these to support my own little game engine which isn’t public so adding issues there seems silly. Other contributors seem to actually have jobs in XR, and I agree it would be good to setup a real place to host issues and coms for this.

I can set something up if no one wants too, but it’d be nice if it was setup by some entity with more skin in the game than a play around side project.

**Comment by capnmidnight** [comment]
> Also, this is minor, but I see a lot of `something? : Something | undefined`, for which `something? : Something` means the same thing.

I know, it's weird. I don't remember exactly where I saw it, but it was apparently the expected style. I didn't do it by choice. I'll try to look it up again to find out why.

**Comment by capnmidnight** [comment]
> > @capnmidnight Is there a good place to file bugs on the WebXR types?
> 
> I initially added these to support my own little game engine which isn’t public so adding issues there seems silly. Other contributors seem to actually have jobs in XR, and I agree it would be good to setup a real place to host issues and coms for this.
> 
> I can set something up if no one wants too, but it’d be nice if it was setup by some entity with more skin in the game than a play around side project.

There might be one of the immersive-web repos that would be a good fit. I'll try to bring it up in the WebXR discord tomorrow. If not, I'm willing to set something up. As you said, working on WebXR stuff is my job.

**Comment by capnmidnight** [comment]
> I noticed that `XRSessionInit` is missing `domOverlay`.

Since I already have the repo cloned, know the submission process pretty well, and it's a small change, I'll probably make a PR for this tomorrow. I've been meaning to get more of the various parts of the WebXR spec defined here. Can't remember what exactly is missing at this point, but shouldn't be hard to figure out.

**Comment by capnmidnight** [comment]
Here's the PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61367

**Pull request merged**
