### PR TITLE
update log4js to 2.x

### PR DESCRIPTION
**Pull request by xialeistudio**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[log4js-node](https://github.com/nomiddlename/log4js-node)>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by xialeistudio** [comment]
Fixed and theTravis CI build passed
this error caused by package/karma

**Comment by weswigham** [comment]
@armorik83 would you like to review the log4js part of this CR?

**Comment by taoqf** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20518

**Comment by weswigham** [comment]
Thanks @taoqf! @xialeistudio, now that your types are in log4js proper, do you want to open a new PR with your zookeeper additions?

**Comment by pe8ter** [comment]
Yesterday, the log4js project released version 2.3.5 on npm which contains [a basic set of typings](https://github.com/nomiddlename/log4js-node/commit/f965c5454adebe349d66af8040de2e759b698bff), but they are not as robust as the typings in this PR. Sounds like it's time to remove log4js from the DT repo and move typings PRs over to that project.

**Comment by xialeistudio** [comment]
wait a moment

**Comment by xialeistudio** [comment]
I'll close this PR,because my project is too mass.I'll create a new PR to do this.Thanks!

**Pull request closed without merging**
