### PR TITLE
Add definitions for Windows.Devices.Gpio to winrt

### PR DESCRIPTION
**Pull request by Fraegle**
There are a couple of namespaces for universal apps, which are not reflected in any definitions file. I think the winrt.d.ts is the right file to add those to.

### CODE REVIEW

**Comment by Fraegle** [comment]
As the minimum supported client for these APIs is Windows 10, this might better be a separate typing, like winuwp.d.ts. Once this is settled, I will make an effort to add also the other new UWP APIs.

**Comment by Fraegle** [comment]
I''

**Comment by vvakame** [comment]
@adamhewitt627 @craigktreasure @Bartvds @mhegazy @yuit @SaschaNaz @souchea can anyone review this pull request?
winrt.d.ts receive huge patch everytime...

**Comment by SaschaNaz** [comment]
Actual changes:

```typescript
declare module Windows { 
    export module Devices { 
        export module Gpio { 
            import TypedEventHandler = Foundation.TypedEventHandler; 
            class EventEmitter<TSender, TResult> { 
                public addEventListener(event: string, handler: TypedEventHandler<TSender, TResult>): void; 
                public removeEventListener(event: string, handler: TypedEventHandler<TSender, TResult>): void; 
            }             
            export class GpioController { 
                public static getDefault: () => GpioController; 
                public openPin: (pinNumber: number, sharingMode?: GpioSharingMode) => GpioPin; 
                public tryOpenPin: (pinNumber: number, sharingMode: GpioSharingMode) => GpioOpenStatus; 
                public pinCount: number; 
            } 
            export class GpioPin extends EventEmitter<GpioPin, GpioPinValueChangedEventArgs> { 
                public onValueChanged: TypedEventHandler<GpioPin, GpioPinValueChangedEventArgs>; 
                public close: () => void; 
                public getDriveMode: () => GpioPinDriveMode; 
                public isDriveModeSupported(driveMode: GpioPinDriveMode): boolean; 
                public read: () => GpioPinValue; 
                public setDriveMode: (value: GpioPinDriveMode) => void; 
                public write: (value: GpioPinValue) => void; 
                public debounceTimeout: number; 
                public pinNumber: number; 
                public sharingMode: GpioSharingMode; 
            } 
            export class GpioPinValueChangedEventArgs { 
                public edge: GpioPinEdge; 
            } 
            export enum GpioOpenStatus { 
                pinOpened = 0, 
                pinUnavailable = 1, 
                sharingViolation = 2 
            } 
            export enum GpioPinDriveMode { 
                input = 0, 
                output = 1, 
                inputPullUp = 2, 
                inputPullDown = 3, 
                outputStrongLow = 4, 
                outputStrongLowPullUp = 5, 
                outputStrongHigh = 6, 
                outputStrongHighPullDown = 7 
            } 
            export enum GpioPinEdge { 
                fallingEdge = 0, 
                risingEdge = 1 
            } 
            export enum GpioPinValue { 
                low = 0, 
                high = 1 
            } 
            export enum GpioSharingMode { 
                exclusive = 0, 
                sharedReadOnly = 1 
            } 
        }         
    } 
} 
```

I think this PR have to normalize line endings first ;)

**Comment by Fraegle** [comment]
Sorry for the line endings. I am rather new to Git and was under the impression that it takes care for these things during commit. Seems I have to refine my settings there. 
The question I would like to be answered, however, is: Do we want to add these typings to the winrt.d.ts or do we want to make a separate folder for Universal Windows Platform (UWP)?
There are lots of new APIs that come into UWP with Windows 10. If those get added to winrt.d.ts and someone develops a Windows 8/8.1 app, he gets the bad user experience that the typing shows APIs which aren't actually there.
Also, to make it easier to target certain device families, I would like to have separate typings in several files. Similar to the Windows API reference for Windows Runtime apps, I would suggest files for core, controls, data and content, devices, files and folders, globalization, graphics, helpers, media, networking, printing, presentation, remote desktop, security, social, UI automation, user interaction.
What do you think?

**Comment by SaschaNaz** [comment]
A separate uwp.d.ts will be good, but I think it should be in the same folder. I also like the multiple file suggestion.

**Comment by Fraegle** [comment]
Work in progress.

**Comment by SaschaNaz** [comment]
BTW, I think we don't need to manually define `enum` values.

**Pull request closed without merging**
