### PR TITLE
[@types/boom] Add typeof to Boom

### LINKED ISSUE #36781: I think there should be typeof variable in @types/boom.
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

@rogatty @AJamesPhillips @jineshshah36 @TimonVS @danielmachado 

https://github.com/hapijs/boom/blob/master/API.md
I think the boom object should have typeof.
typeof - the constructor used to create the error (e.g. Boom.badRequest).

```typescript
declare class Boom<Data = any> extends Error {
    /** Creates a new Boom object using the provided message and then calling boomify() to decorate the error with the Boom properties. */
    constructor(message?: string | Error, options?: Boom.Options<Data>);
    /** isBoom - if true, indicates this is a Boom object instance. */
    isBoom: boolean;
    /** isServer - convenience bool indicating status code >= 500. */
    isServer: boolean;
    /** message - the error message. */
    message: string;
    /** output - the formatted response. Can be directly manipulated after object construction to return a custom error response. Allowed root keys: */
    output: Boom.Output;
    /** reformat() - rebuilds error.output using the other object properties. */
    reformat(): string;
    /**
     * "If message is unset, the 'error' segment of the header will not be present and
     * isMissing will be true on the error object." mentioned in
     * @see {@link https://github.com/hapijs/boom#boomunauthorizedmessage-scheme-attributes}
     */
    isMissing?: boolean;
    /** https://github.com/hapijs/boom#createstatuscode-message-data and https://github.com/hapijs/boom/blob/v4.3.0/lib/index.js#L99 */
    data: Data;
}
```
typeof: internals.Boom?

### PR DESCRIPTION
**Pull request by jmannanc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/hapijs/boom/blob/master/API.md#boom-1>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes #36781

### CODE REVIEW

**Review by AJamesPhillips — COMMENTED** [review]
You could use: `readonly typeof: () => any;`

**Comment by SneakyFish5** [comment]
Fixed, thank you @AJamesPhillips. Also sorry for the two force commits, the husky auto formats every time I commit and I forgot to revert the changes.

**Comment by AJamesPhillips** [comment]
@SimonSchick regarding https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36781#issuecomment-514222490 i.e. using type `(message?: string, data?: any, ...extra: any[]) => any` do you think people will want to use to `typeof` to instantiate more errors of that type?  I'd imagine someone could want to do that but then neither the function signature nor the return type will help them as much as the full types.  Shall we merge this PR to get it moved through (@SneakyFish5 has been on this a while) and wait until someone complains / submits a PR?

**Comment by jessetrinity** [comment]
@AJamesPhillips are you waiting on revisions?

**Comment by sandersn** [comment]
We haven't heard from @AJamesPhillips or @SimonSchick so I'm going to merge this and we can fix it up later if needed.

Also, looks like `boom` moved to `@hapi/boom` so not sure how many more updates these types will need.

**Comment by SimonSchick** [comment]
Yea @sandersn perhaps we should lock down the hapi typings and only support `@hapi` in the future, way too much churn otherwise.

**Pull request merged**
