### PR TITLE
[recompose] Update to 0.27.1

### PR DESCRIPTION
**Pull request by TiuSh**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/acdlite/recompose/blob/7d5adf7f49b21e3693f7d631551d282e5c8ef820/docs/API.md#torenderprops
- [x] Increase the version number in the header if appropriate.
- [x] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by TiuSh** [comment]
Actually the features I added are not yet published... Sorry !...

**Comment by jesnil01** [comment]
@TiuSh They are published now :)

**Comment by TiuSh** [comment]
@jesnil01 Nice ! I'll try to fix my PR (I found some issues) and reopen it ASAP !

**Comment by TiuSh** [comment]
@mtgto Sorry, took me some time to get back to it, but I finally created a new PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30541 😉

**Pull request closed without merging**
