### PR TITLE
[express-winston] Adding types for express-winston

### PR DESCRIPTION
**Pull request by bricka**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by bricka** [comment]
Apparently I was missing a Typescript version. Added :).

**Comment by bricka** [comment]
Unfortunately, I have no idea how to resolve this error :(.

```
Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`
```

**Comment by mhegazy** [comment]
> Unfortunately, I have no idea how to resolve this error :(.

```
Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`
```

Added it for you in tsconfig.json. now there are some test failures, can you address them.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
