### PR TITLE
Cleanup not existing codeowners #no-publishing-comment

### LINKED ISSUE #54679: Codeowners in 404
There are some `codeowners` whose accounts no longer exists. Should we remove all of them?

I have script running at the moment to check which accounts were removed, and there is quite a few already.

Edit: I found around 200 not existing accounts,  some of them might be typo though. Let me know what do you think, before I'll move this further.

### PR DESCRIPTION
**Pull request by KapitanOczywisty**
I've checked names listed in `CODEOWNERS` and these which accounts were not found, I've compared with commiters (which added their name to header line). With that I've updated or removed user names in `Definitions by:` header.

Things to note:
- Some packages lost their sole owner. `nobody <https://github.com/DefinitelyTyped>` was added to pass tests.
- Names (if updated) were copied from github profile.
- Many people (at least in the past) are confusing `Definitions by:` header as "credits" and some are even adding third-parties or package creators - this PR is *not* addressing that.
- Unclear cases and deleted users were removed from headers.
- Many ugly scripts were involved, but a human approved every change.

/cc @RyanCavanaugh @orta

Closes #54679

### CODE REVIEW

**Comment by SimonSchick** [comment]
Did you also create a PR for the tool that you wrote so it can be used in the future?

**Comment by KapitanOczywisty** [comment]
@SimonSchick I have bunch of ugly bash/node scripts connected by zipties. I think it would be much better to keep track of `username - id` map and refer to it if username is no longer accessible.

**Comment by peterblazejewicz** [comment]
I've put my remarks original topic.
also,
-there are dozens of 'nobody' accounts names on GitHub (so loads of nobodies could claim attribution for a work)
- we cannot add a real person GitHub handle, without clear way to opt-in/opt-out for this person consent, which means separate process for each individual GitHub handle. Can we, really?
A person needs to see action like:
```ts
sane-email-validation — on npm, on unpkg
1 added owner: @peterblazejewicz
1 removed owner: @peterblazejewiczy
```
It just happened I'm the person behind this handle, doing a review pf this PR, otherwise I would be not aware about this change unless I received a notification. If we switch this in a bulk change, someone can be added to a popular repo and receive a spam on daily basis. People can use real email addresses on GitHub, so I would avoid doing this in a bulk email change (imagine, `peterblazejewiczy` can be a defunct GitHub handle, for variety of reasons, why I should be really notified at my personal account about DT-something some change?)
etc.

I"ve been correcting people handles here one by one previously, I believe that's way to go (ones creates a PR, wait for person interaction, express sorry if that was a mistake, etc, a basic netiq)

**Comment by KapitanOczywisty** [comment]
@peterblazejewicz  All updates were people who added themself to the headers and then changed username, no person was added if there was nobody or something like that before. Changes were compared with user who was doing PR if there was not obvious connection, header was removed.

> It just happened I'm the person behind this handle, doing a review pf this PR

You'd got mention notification, but probably you've got review request. I'm not sure if there is a limit to notified users from one comments, but we could probably mention them by hand in chunks. Or I can just remove every single one from headers and call it done.

> (imagine, `peterblazejewiczy` can be a defunct GitHub handle, for variety of reasons, why I should be really notified at my personal account about DT-something some change?)

But It wasn't...

**Comment by peterblazejewicz** [comment]
> People who would have been pinged

(earlier, above) We pinged no one, which is good. The problem to solve is to not waste current resources to non-existing handles (404), not to make a cleanup of peoples where-abouts, we are not maintaining GitHub users directory. So the problem to solve is to remove username (404) from code owners lists I think. 'm not against the change, I just think we cannot do this that way as a single, bulk change of username swaps

**Comment by KapitanOczywisty** [comment]
> We pinged no one, which is good.

People affected were pinged from quoted comment (maybe there is limit, but at least one person got mention and left 👍 ):
```
sane-email-validation — on npm, on unpkg
1 added owner: @peterblazejewicz
1 removed owner: @peterblazejewiczy
```

The rest is up to you and other maintainers, so let me know if you need from me any further input.

**Pull request closed without merging**
