### PR TITLE
[jquery] Accept union types for the call signature of `JQueryStatic`.

### LINKED ISSUE #29312: [@types/jquery] Error with union types
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu, @borisyankov, @Steve-Fenton, @Diullei

**Versions:**
`typescript@3.1.1`
`@types/jquery@3.3.10`
`jquery@3.3.1`

**Code:**
```
import * as $ from "jquery";

function test(selector: string | string[]) {
  const selected = $(selector);

  selected.addClass('test');

  return selected;
}

test(".test");
```

**Error:**
Error shown here `$(selector);`
```
Argument of type 'string | string[]' is not assignable to parameter of type 'PlainObject<any>'.
  Type 'string' is not assignable to type 'PlainObject<any>'.
(parameter) selector: string | string[]
```

**Example:** [Stackblitz](https://stackblitz.com/edit/typescript-szbshm)

Also got something weird with `.on` and the `PlainObject`, but can't reproduce.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

---

The relevant commit is 7c1547688127a28da8cc933e28a5cb4fbe9af2e2.

Requires conditional types from TypeScript 2.8.

I couldn't figure out to declare type constraints for `TDeclared` based on the type of `T`, so `TDeclared` is no longer constrained when `T` is `JQuery.htmlString`/`JQuery.Selector`.

---

Fixes #29312.

---

| Name | Commits |
| --- | --- |
| `acc-wizard` | 22d1216970 |
| `amplify` | e8117357f1 |
| `amplify-deferred` | cbf965608e |
| `angular` | 4aa6fda688 |
| `angular-agility` | 6f4f6a4bcd |
| `angular-animate` | 8b600fa68a |
| `angular-block-ui` | 031e14d3ae |
| `angular-bootstrap-calendar` | 429f6e3a49 |
| `angular-breadcrumb` | 2d6075baea |
| `angular-clipboard` | 8bca2d8283 |
| `angular-cookie` | ab3733b288 |
| `angular-cookies` | 20c3f85f99 |
| `angular-deferred-bootstrap` | bddefaf730 |
| `angular-desktop-notification` | bf899ce345 |
| `angular-dialog-service` | d5cb9fd5f9 |
| `angular-dynamic-locale` | 9a82c46d1c |
| `angular-feature-flags` | 26738b2404 |
| `angular-file-saver` | e2a3a6c0e8 |
| `angular-file-upload` | 85f03b4b83 |
| `angular-formly` | 44f97e0ab1 |
| `angular-fullscreen` | 629bd60f14 |
| `angular-gettext` | aa2aa19e84 |
| `angular-google-analytics` | b20ff94c91 |
| `angular-gridster` | 9770b68bd2 |
| `angular-growl-v2` | 284b398a56 |
| `angular-hotkeys` | 1c43853df5 |
| `angular-http-auth` | 1f974d5bd8 |
| `angular-httpi` | 8de7597f39 |
| `angular-idle` | 4fc10cb552 |
| `angular-jwt` | e179e007b0 |
| `angular-load` | 0d31014ecc |
| `angular-loading-bar` | bca37fd184 |
| `angular-local-storage` | 49137753ad |
| `angular-localforage` | 7006bd5e41 |
| `angular-locker` | 0cc4b0bf39 |
| `angular-material` | be684a4e37 |
| `angular-media-queries` | eafdbb29c7 |
| `angular-mocks` | 2764749282 |
| `angular-modal` | 8785702e14 |
| `angular-notifications` | 567a74bb1c |
| `angular-notify` | d0159ee913 |
| `angular-oauth2` | b6211c3a33 |
| `angular-odata-resources` | f043b940ac |
| `angular-pdfjs-viewer` | 5c895e81d3 |
| `angular-permission` | 2e8d892c59 |
| `angular-promise-tracker` | db3e0725cd |
| `angular-q-extras` | 9561237c3b |
| `angular-q-spread` | 581f097d5d |
| `angular-resource` | 6a8993b94b |
| `angular-route` | cd66981317 |
| `angular-sanitize` | e0466e1427 |
| `angular-scenario` | e331c0cb2d |
| `angular-scroll` | b00eaec0fb |
| `angular-signalr-hub` | 835f2f6600 |
| `angular-spinner` | 1d754d1fed |
| `angular-storage` | c0dfa9ffbc |
| `angular-strap` | 373a9900dd |
| `angular-toastr` | e00aee3c4a |
| `angular-toasty` | ebc94c9ca7 |
| `angular-tooltips` | 0a0e6d44e1 |
| `angular-translate` | 9065c51fe4 |
| `angular-ui-bootstrap` | a65e273470 |
| `angular-ui-notification` | 78f33a9641 |
| `angular-ui-router` | 1f05e65d3e |
| `angular-ui-scroll` | c4817b1c45 |
| `angular-ui-sortable` | 3c64f99ca4 |
| `angular-ui-tree` | 6e3d9f2116 |
| `angular-websocket` | 38d5e61668 |
| `angular-wizard` | ee3fb94021 |
| `angular-xeditable` | a0b7eeb1d8 |
| `angular.throttle` | 6290a4ed35 |
| `angularfire` | 729bc1651a |
| `angularlocalstorage` | 70174a30b0 |
| `angulartics` | ff79b7eee4 |
| `auth0-angular` | 6ab3ac0ad9 |
| `autosize` | 1ff303450d |
| `backbone` | 3316d9fca0 |
| `backbone-associations` | a09fd1bdfb |
| `backbone-fetch-cache` | 7d5c6d45e1 |
| `backbone-relational` | 7a90d4afda |
| `backbone.layoutmanager` | 192431335a |
| `backbone.localstorage` | b581e6f1be |
| `backbone.marionette` | 2604e5836e |
| `backbone.paginator` | fe1d6229d1 |
| `backbone.radio` | c74963fead |
| `backgrid` | 88a0a76ba1 |
| `baconjs` | 6a6097f990 |
| `bardjs` | b7893ff242 |
| `bootbox` | d521e555d8 |
| `bootpag` | c338d6adaf |
| `bootstrap` | 7bd19c18cf |
| `bootstrap v3` | d974635c96 |
| `bootstrap-3-typeahead` | a0976870ce |
| `bootstrap-datepicker` | 3faf5fcf57 |
| `bootstrap-fileinput` | 1344c84617 |
| `bootstrap-growl-ifightcrime` | 346fe909f2 |
| `bootstrap-maxlength` | 9e0edfea60 |
| `bootstrap-notify` | 4c9dcbcda0 |
| `bootstrap-select` | 7df43974c4 |
| `bootstrap-slider` | 92cf27043b |
| `bootstrap-switch` | 8dbc8e4390 |
| `bootstrap-table` | ace2dc8b82 |
| `bootstrap-touchspin` | 715f19a0c7 |
| `bootstrap-treeview` | 34d7e40e81 |
| `bootstrap-validator` | ff04cede7d |
| `bootstrap.paginator` | dfd6bcfa16 |
| `bootstrap.timepicker` | 76bf41b5c1 |
| `bootstrap.v3.datetimepicker` | f3ea71e888 |
| `bootstrap.v3.datetimepicker v3` | 6b78430d0f |
| `bootstrap3-dialog` | a85f86110b |
| `bounce.js` | 1a4c94e6da |
| `business-rules-engine` | c35250d45b |
| `cal-heatmap` | 8851b13547 |
| `chai-jquery` | 0ecc7a0530 |
| `chosen-js` | f85fbe94fa |
| `chrome` | d8bbbfad70 |
| `chui` | dbbe4f8368 |
| `clndr` | 2cb8d34129 |
| `clockpicker` | 7b003f6320 |
| `commangular` | 1419daba23 |
| `cordova-plugin-ibeacon` | 0b6f3f8bbc |
| `country-select-js` | bc16f29ef7 |
| `datatables.net` | a3d34549d2 |
| `datatables.net-autofill` | a45bd35e6c |
| `datatables.net-buttons` | f8f35b2675 |
| `datatables.net-colreorder` | 675255c5e4 |
| `datatables.net-fixedheader` | 1b694422c9 |
| `datatables.net-rowgroup` | d0e32a9f87 |
| `datatables.net-rowreorder` | febf1344f9 |
| `datatables.net-scroller` | 2bd1070946 |
| `datatables.net-select` | 1ab9dab92f |
| `daterangepicker` | e50d99b89b |
| `devexpress-web` | 98ef8e147e |
| `df-visible` | 8fac0b9afc |
| `dropzone` | 1515d46289 |
| `dropzone v4` | f17b75a73a |
| `durandal` | 87e99ccaeb |
| `durandal v1` | fe407b46e4 |
| `dw-bxslider-4` | cc845dc4af |
| `dynatable` | 17bd62b37c |
| `easy-api-request` | 17796df9b6 |
| `ej.web.all` | e5647e7788 |
| `ember v1` | cb8eeb9699 |
| `ember v2` | 7acd49b257 |
| `ember-feature-flags v3` | b6bb9b7d1e |
| `ember-modal-dialog v2` | bbb9166ec9 |
| `ember-qunit v2` | 0dc5fe5ca2 |
| `ember-resolver v4` | 954319b7b9 |
| `ember-test-helpers v0` | fd6ca6f5fc |
| `ember-testing-helpers` | 02941b6a20 |
| `enber-data v2` | 3c3b27cc7a |
| `eonasdan-bootstrap-datetimepicker` | 63ac08d8ae |
| `eq.js` | 7196797b95 |
| `evernote` | ef33800093 |
| `ez-plus` | 3812d2bede |
| `fancybox` | 8835a78145 |
| `farbtastic` | 56e8128055 |
| `featherlight` | 3c8d2b4591 |
| `firebase-client` | 184d2512ae |
| `flexslider` | f6cb37bf4f |
| `flickity` | 28944decad |
| `flight` | 98568e8116 |
| `flot` | 771963cbba |
| `form-serializer` | aa89dc07cd |
| `foundation` | 6bb3b355cc |
| `fullpage.js` | 43f490cf34 |
| `gamequery` | 2c85871fd4 |
| `geopattern` | 123d6e229f |
| `gijgo` | 54c5dedb84 |
| `giraffe` | 82f0bbd8e9 |
| `gldatepicker` | d79eb3dd2f |
| `glidejs` | 11c693f5b9 |
| `gridstack` | a4dd055541 |
| `gulp v3` | 73027e56c8 |
| `gulp-help` | 8b04004762 |
| `hammerjs v1` | 479a682a29 |
| `highcharts` | 828a69eb73 |
| `highcharts-ng` | dd8fc2092e |
| `html2canvas` | b3aceeefc3 |
| `hystrixjs` | 178e5440cc |
| `ibm-mobilefirst` | 6ab4c31b33 |
| `icheck` | 0694f19858 |
| `imagesloaded` | e2e5a96875 |
| `intl-tel-input` | 5021eddf1a |
| `ion-rangeslider v1` | 4a9f72254a |
| `isotope-layout` | a01d708c3e |
| `jasmine-fixture` | ffa16a797c |
| `jasmine-jquery` | 344440c8c6<br>732d8b1f15 |
| `jbinary` | a1aab2e476 |
| `jcanvas` | fc09307608 |
| `jdataview` | 07effbb964 |
| `jqgrid` | b957854ae7 |
| `jqrangeslider` | d45fd76cb5 |
| `jquery-ajax-chain` | 17b168c6b8 |
| `jquery-alertable` | 78f1f3b202 |
| `jquery-animate-scroll` | 64b0776e68 |
| `jquery-awesome-cursor` | 063ffc2817 |
| `jquery-backstretch` | 8c6ea730cb |
| `jquery-countdown` | 755522ee6b |
| `jquery-countto` | bb9605e123 |
| `jquery-cropbox` | d01cf37d9c |
| `jquery-drawer` | 8d6072c90b |
| `jquery-easy-loading` | b6982c0255 |
| `jquery-editable-select` | b0f042dca1 |
| `jquery-focus-exit` | 971387e056 |
| `jquery-focusable` | 165eef9f4b |
| `jquery-fullscreen` | 44277c9639 |
| `jquery-gray` | 73666e114c |
| `jquery-handsontable` | f9668489ea |
| `jquery-jcrop` | 67bb83bb43 |
| `jquery-jsonrpcclient` | caa7796c0f |
| `jquery-knob` | 735b6caefb |
| `jquery-lazyload` | 1dacf57b30 |
| `jquery-loading-overlay` | 52afcbb0ec |
| `jquery-mask-plugin` | d0fbfd720f |
| `jquery-maskmoney` | c40719e645 |
| `jquery-match-height` | 7d13ac4b09 |
| `jquery-mockjax` | b0f709fa2b |
| `jquery-mouse-exit` | 06fa73fbaa |
| `jquery-mousewheel` | c40765153d |
| `jquery-next-id` | 1457d0ded7 |
| `jquery-slugify` | 5472757b51 |
| `jquery-sortable` | eede7654c3 |
| `jquery-steps` | b47b0c3184 |
| `jquery-sticky` | ccd615354e |
| `jquery-tags-input` | 58fd0b061b |
| `jquery-timeentry` | 9093fe31bb |
| `jquery-toastmessage-plugin` | 8a6d6b26d6 |
| `jquery-truncate-html` | 14b112c30e |
| `jquery-urlparam` | 6363ed2fe7 |
| `jquery-validation-unobtrusive` | 3c20a69df7 |
| `jquery.address` | e5aa2abd33 |
| `jquery.appear` | bcf06297c3 |
| `jquery.are-you-sure` | 16b44b3fd8 |
| `jquery.autosize` | 447f64ef4d |
| `jquery.base64` | bb9e767b0d |
| `jquery.blockui` | e8e3f263fc |
| `jquery.bootstrap.wizard` | a909461d57 |
| `jquery.browser` | f507536de0 |
| `jquery.cleditor` | 8d231c096b |
| `jquery.clientsidelogging` | f6a1273d35 |
| `jquery.color` | 7738985632 |
| `jquery.colorbox` | d9cae06227 |
| `jquery.colorpicker` | 43bf235b49 |
| `jquery.contextmenu` | 9b178df7a8 |
| `jquery.cookie` | 41f5c84058 |
| `jquery.customselect` | 6c91b5609c |
| `jquery.cycle` | 427c34af24 |
| `jquery.cycle2` | 4c1b90537f |
| `jquery.dropotron` | e7dc326059 |
| `jquery.dynatree` | a32907daae |
| `jquery.elang` | 01d08080a4 |
| `jquery.fileupload` | 952bc39e18 |
| `jquery.filtertable` | 6234a8cb6d |
| `jquery.finger` | e07a6e436d |
| `jquery.flagstrap` | bdde00ccde |
| `jquery.form` | 23e1039c7b |
| `jquery.fullscreen` | 8d01d5604e |
| `jquery.gridster` | e4ab7a1ca4 |
| `jquery.growl` | a54d6610f2 |
| `jquery.highlight-bartaz` | 0e4e3f14cf |
| `jquery.jnotify` | b8ec04a4a9 |
| `jquery.jsignature` | a494ab314d |
| `jquery.leanmodal` | 9d51a6caaa |
| `jquery.livestampjs` | ff8d56a9ca |
| `jquery.menuaim` | 7336b8d0b1 |
| `jquery.mmenu` | 2472c3ac4a |
| `jquery.nicescroll` | 4d4f47a0ee |
| `jquery.notify` | ebaffe9812 |
| `jquery.notifybar` | 26a5286c00 |
| `jquery.noty` | 5db34d2abc |
| `jquery.payment` | 3b86b1e00e |
| `jquery.pin` | cc8b95ddb4 |
| `jquery.pjax` | 0adfb6d593 |
| `jquery.placeholder` | 7dd8cfdbe3 |
| `jquery.pnotify` | 386bbb0ff8 |
| `jquery.postmessage` | 5392385d02 |
| `jquery.prettyphoto` | 46900341cc |
| `jquery.qrcode` | 96a0e40f36 |
| `jquery.rateit` | c62748d6b9 |
| `jquery.rowgrid` | 251e835f4f |
| `jquery.scrollto` | 8a337bb5c7 |
| `jquery.simplemodal` | 3975963d47 |
| `jquery.simplepagination` | 17cd069d29 |
| `jquery.simulate` | 402cb4b838 |
| `jquery.slimscroll` | 7d31e2f835 |
| `jquery.soap` | 695a1bfe33 |
| `jquery.sortelements` | 469e0ed5b6 |
| `jquery.stickem` | 2f4af3de01 |
| `jquery.superlink` | bb8286716a |
| `jquery.tagsmanager` | 6cf50ef65e |
| `jquery.tile` | a0f694f591 |
| `jquery.timeago` | 5b2cb6e98a |
| `jquery.timepicker` | c559a12e37 |
| `jquery.timer` | 89fe4316bc |
| `jquery.tinycarousel` | 4ee41ac12f |
| `jquery.tinyscrollbar` | 3448b0f750 |
| `jquery.tipsy` | 18de5f3865 |
| `jquery.tools` | a5d3ab46c4 |
| `jquery.total-storage` | d2a6702817 |
| `jquery.transit` | b233b87319 |
| `jquery.ui.datetimepicker` | f13961d571 |
| `jquery.ui.layout` | 79e31a3a27 |
| `jquery.uniform` | 0a2fd49ae5 |
| `jquery.validation` | 41c6f9281c |
| `jquery.watermark` | 3ecda6a3f6 |
| `jquery.window` | e12ffda560 |
| `jquerymobile` | b07fa4b1b6 |
| `jqueryui` | ade7f869a5 |
| `js-data-angular` | 2844291009 |
| `jscrollpane` | e1d5a45e37 |
| `jsdom v2` | ea81d85bcf |
| `jsrender` | 8112259dfb |
| `jstorage` | 1f50087c86 |
| `jstree` | beff9974a0 |
| `jsuite` | 58d3d311f7 |
| `jui` | d264bc6c95 |
| `jui-core` | 153e3fc053 |
| `jui-grid` | 75e908c3e2 |
| `kendo-ui` | 6333b6435c |
| `knockback` | e7f0e45bcd |
| `knockout.kogrid` | 1c808c2878 |
| `knockstrap` | 9aeb5feb09 |
| `kolite` | ae137579a0 |
| `ladda` | 81c9b67d53 |
| `lobibox` | ce5f138ceb |
| `magicsuggest` | 1ee1b34c8c |
| `mailcheck` | 2d071f928a |
| `mark.js` | 912a80df73 |
| `markitup` | d9e2dc2154 |
| `maskedinput` | 0b79328472 |
| `masonry-layout` | f2c1e17fe3 |
| `materialize-css` | 58f1de73cc |
| `materialize-css v0` | d88363f269 |
| `mcustomscrollbar` | 9416a6fe1e |
| `microsoft-sdk-soap` | c9cadd2345 |
| `mongoose-seeder` | fcab2a760c |
| `mousetrap` | 79cc211cc3 |
| `msportalfx-test` | 88e4e7edd0 |
| `nanoscroller` | b6ae81e3e1 |
| `ng-command` | 474813bf96 |
| `ng-cordova` | b886d9d313 |
| `ng-dialog` | cd57d0246a |
| `ng-facebook` | 31c435cbbb |
| `ng-file-upload` | d18861e839 |
| `ng-flow` | 5d69b83a5b |
| `ng-grid` | d0b8590cda |
| `ng-notify` | 2b611f2dcf |
| `ng-stomp` | 5d9182ce20 |
| `ng-tags-input` | 716a2c567e |
| `ngbootbox` | b5e7d13305 |
| `ngmap` | 0dbfd4b678 |
| `ngprogress-lite` | 58f283e900 |
| `ngstorage` | 2be53ae369 |
| `ngtoaster` | fc49fdf0c8 |
| `nightmare` | efb7e0c144 |
| `nivo-slider` | 82b13c6db5 |
| `node-persist` | 8bcf332d8e |
| `notify` | c51e34211d |
| `notifyjs-browser` | 450ee9938d |
| `nouislider v7` | c61db05840 |
| `o.js` | 1730317546 |
| `oblo-util` | 5befc14176 |
| `oclazyload` | 67bc2df42a |
| `odata` | 1dd7080711 |
| `openui5` | e0574aac35 |
| `orchestrator` | 3b1775608b |
| `owl.carousel` | 436c6907e4 |
| `owlcarousel` | 114b079ce0 |
| `p-loading` | e651460f21 |
| `packery` | 1ae6c9711b |
| `parse` | 16ebdae0d3 |
| `parse-mockdb` | 3a00c1480c |
| `pickadate` | b43b298dee |
| `pikaday` | e2279e2887 |
| `pikaday-time` | 412c10b80f |
| `promise-pg` | 7d16e673ac |
| `promise-pool` | a5538fb587 |
| `purl` | a561e6e2b6 |
| `q` | 13e58dd48d |
| `q v0` | dfaaaf6a45 |
| `q-io` | 663762bb28 |
| `q-retry` | ba88626b35 |
| `qlik` | a91eb98357 |
| `qlik-visualizationextensions` | a312e0a2c5 |
| `qtip2` | d8e9092286 |
| `rangyinputs` | ea19651b21 |
| `rappid` | 3ff361e913 |
| `raty` | 67948ef3fb |
| `redux-shortcuts` | d164e3b999 |
| `restangular` | 84fc496b00 |
| `riotjs` | c8eb35f992 |
| `rivets` | 41cf8e764d |
| `royalslider` | 33ca6b276d |
| `rx-angular` | d30280255f |
| `rx-jquery` | aefd4d3676 |
| `sammy` | 1480d1a189 |
| `scrolltofixed` | 7a64d193b8 |
| `seamless` | e840b7ee6a |
| `segment-analytics` | c80dc5f5fe |
| `select2` | f0e8888750 |
| `select2 v3` | 51fee3a83f |
| `selectize` | 39bc64a339 |
| `semantic-ui` | 6942220d5d |
| `semantic-ui-accordion` | f73e2f1465 |
| `semantic-ui-api` | b7f0bd99be |
| `semantic-ui-checkbox` | 676fccd047 |
| `semantic-ui-dimmer` | 52b28dc956 |
| `semantic-ui-dropdown` | 50c62caca5 |
| `semantic-ui-embed` | 691c61c231 |
| `semantic-ui-form` | fbe19a4071 |
| `semantic-ui-modal` | 3d4d5dff32 |
| `semantic-ui-nag` | 1cdb36987e |
| `semantic-ui-popup` | 0a8172bb22 |
| `semantic-ui-progress` | 629c2cbdb8 |
| `semantic-ui-rating` | 097a137690 |
| `semantic-ui-search` | 8c8970c6d9 |
| `semantic-ui-shape` | 2abf824c40 |
| `semantic-ui-sidebar` | b3531b9d18 |
| `semantic-ui-site` | efb81050be |
| `semantic-ui-sticky` | 1c084befb8 |
| `semantic-ui-tab` | c93c283a5f |
| `semantic-ui-transition` | f7e6ca84d9 |
| `semantic-ui-visibility` | 25df29a98b |
| `sharepoint` | 710d9bd286 |
| `shopify-buy` | db15427283 |
| `signalr` | 12a5405555 |
| `signalr v1` | e2e54b5ef6 |
| `simplebar v1` | ca7d1b48c4 |
| `sizzle` | 53ab1cdfc6 |
| `slick-carousel` | 2d4a3a3cb2 |
| `slickgrid` | 2957bdaf3b |
| `snazzy-info-window` | 253294bca4 |
| `space-pen` | 9b532c7cfd |
| `spectrum` | 0da86b58f3 |
| `succinct` | 9439dc7917 |
| `summernote` | 5b10d87648 |
| `swig-email-templates` | b345589342 |
| `swiper v2` | ca736d832f |
| `swiper v3` | cbe19c1caf |
| `tether` | 463c49237f |
| `tether-drop` | 0076697608 |
| `thrift` | dd0b5e5356 |
| `tinymce` | 9e99fea0d3 |
| `toastr` | 7880283d05 |
| `tooltipster` | 98cfe1a979 |
| `trunk8` | 713f01b76b |
| `twilio` | 7aaf46f878 |
| `typeahead` | 5b4c8b4d39 |
| `ui-grid` | 0d17882981 |
| `ui-router-extras` | 82ab8c67af |
| `ui-select` | 86dd2f2b73 |
| `uikit` | 9d7ab70fec |
| `umbraco` | 602c8d6e0a |
| `urijs` | 5ad07f3d36 |
| `velocity-animate` | 777eb09255 |
| `vex-js` | 6e51ad6ee6 |
| `viewporter` | fccd43d69c |
| `virtual-keyboard` | ee361eb455 |
| `w2ui` | f5a946042d |
| `waitme` | 5780f08dd7 |
| `waypoints` | 10ce7dc4f0 |
| `webcl` | d6f334fbcd |
| `x-editable` | 1f67de3455 |
| `zeroclipboard` | 83b6be5178 |
| `zeroclipboard v1` | a83fa1f25b |
| `zui` | 9e47423c3d |

### CODE REVIEW

**Comment by leonard-thieu** [comment]
@andy-ms is there a way to get the full list of typings that need to have their TypeScript version bumped?

**Comment by andy-ms** [comment]
We're working on supporting multiple TS versions together (Microsoft/TypeScript#26568), which is a better alternative to changing the version of this many packages.

**Comment by leonard-thieu** [comment]
@gstamac @lukas-zech-software could you verify if the changes to `@types/jasmine-jquery` are appropriate (732d8b1f15a1f9a574edcfb516c5b8273878313a)? Thanks!

Documentation for [`toContain`](https://github.com/velesin/jasmine-jquery/blob/ebad463d592d3fea00c69f26ea18a930e09c7b58/README.md#jquery-matchers).

**Review by Igorbek — COMMENTED** [review]
TypeScript 3.1 [introduced `typesVersions`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#version-selection-with-typesversions) which can help with such kind of things.
I suggest in cases like this start using it.

**Comment by leonard-thieu** [comment]
I was under the impression that `typesVersion` only has an impact if the consumer is using TypeScript 3.1 or later. Older TypeScript versions do not support `typesVersion` and just use the default types.

**Comment by andy-ms** [comment]
That's true. So this feature would be exclusive to ts3.1+, as opposed to being exclusive to ts2.8+ -- I don't think the extra 3 supported versions are worth the cost of changing this many packages though.

**Pull request closed without merging**
