### PR TITLE
changing $http default headers definition

### PR DESCRIPTION
**Pull request by acepoblete**
pull request for issue #5855

### CODE REVIEW

**Comment by billccn** [comment]
Hi, you have missed the indexer (line 1400) and I think the type can be made more precise.

**Comment by acepoblete** [comment]
I couldn't find what the `requestType` was defined as in the source.  After doing some debugging on a project I'm working on, I don't even see a default value for `requestType` getting set.  The only place in angular I can find a reference to a property called `requestType` is in the comments of resource.js line [106](https://github.com/angular/angular.js/blob/24cd70058d081b93061734aec29e05f9e37abb3a/src/ngResource/resource.js#L160).  I'm not sure it has anything to do with $http defaults, thats why I didn't change it.

**Comment by billccn** [comment]
Hi, `[requestType: string]: string|(() => string)` is an [indexer](http://www.typescriptlang.org/Handbook#interfaces-array-types). The name was arbitrary: it was only there to make the syntax valid. It allows the headers for more request types to be defined without TS1.6 compiler screaming about unknown properties.

However, the actual problem is somewhere else. Seem the update to my comment:
https://github.com/borisyankov/DefinitelyTyped/issues/5855#issuecomment-141118180

**Comment by vvakame** [comment]
*angularjs/angular.d.ts*

to author(@diegovilar). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by acepoblete** [comment]
Does this look right to you @diegovilar? Looking to get this thing into my project asap.  Do I need to do anything else?

**Comment by vvakame** [comment]
I think `any` is too much loose.
please add some test code.
I think `string | (() => string) | {[name: string]: string; }` is more better typings. isn't it?

**Comment by billccn** [comment]
Hi, as discussed in the bug (#5855), the interface needs different types when used in different APIs. A proper fix would require changing other stuff as well.

Typing it as `any` hopefully signals that the type definition stops there and the user should read the docs. If we use a very specific type, users might be mislead into thinking all these types are valid with both APIs, which is not the case.

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
