### PR TITLE
ramda: Upgrade ts-toolbelt

### PR DESCRIPTION
**Pull request by Cretezy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by TheHandsomeCoder** [comment]
Could you elaborate on what does updating this dependancy does?

**Comment by Cretezy** [comment]
It was causing a bug with `ts-toolbelt` with recursive `GapsOf`:

`error TS2321: Excessive stack depth comparing types 'GapsOf<?, T2>' and 'GapsOf<?, T2>'.`

Upgrading `ts-toolbelt` fixed this.

**Comment by pirix-gh** [comment]
Hi @Cretezy, thanks for updating this. I maintain the ts-toolbelt. Recent versions were upgraded for better performance, so it is obviously related. Can you provide an example that reproduces the bug? (just to do a thorough check).

**Comment by Cretezy** [comment]
It's really hard to find what was the original cause due to that Typescript error not giving a stack trace. I didn't know what caused the error to happen (large codebase) but upgrading ts-toolbelt did fix it (which makes sense with the better performance)

**Review by millsp — APPROVED** [review]

**Comment by pirix-gh** [comment]
Well, as far as I can guess, this seemed to come from `Curry` which used an overly-complex `Reverse` type that has been simplified/optimized.

**Comment by PranavSenthilnathan** [comment]
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

**Pull request merged**
