### PR TITLE
jointjs: Provides its own types

### PR DESCRIPTION
**Pull request by ghost**
This will deprecate `@types/jointjs` in favor of just `jointjs`. CC @areel, @DavidDurman, @DenEwout, @CaselIT, @ChrisMoran

### CODE REVIEW

**Comment by andy-ms** [comment]
Implicit-any errors seem to be fixed in jointjs master (clientIO/joint#555), so let's wait for a new release.

**Comment by CaselIT** [comment]
Great!
I guess https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15552 can be closed

**Comment by ChrisMoran** [comment]
I'd be happy to send a pull request over to finish the Vectorizer typings in the jointjs repo instead. I can close out #15552

**Comment by mhegazy** [comment]
@andy-ms can you fix the failures and commit

**Comment by andy-ms** [comment]
Still waiting on clientIO/joint#580

**Comment by mhegazy** [comment]
clientIO/joint#580 is in, can we merge this?

**Comment by andy-ms** [comment]
According to https://github.com/clientIO/joint/pull/580#issuecomment-305778043 the changes won't be published to NPM until jointjs@1.1.1 is ready. I don't think we would want to add a direct dependency to their git repo on DefinitelyTyped, so we should wait until the fixed definitions are published as part of their 1.1 release.

**Comment by RyanCavanaugh** [comment]
@andy-ms Please fix the failures indicated in the Travis CI log.

**Comment by andy-ms** [comment]
Looks like jointjs isn't going to publish any time soon.

**Pull request closed without merging**
