### PR TITLE
[ua-parser-js] add support for upcoming version 2.0

### PR DESCRIPTION
**Pull request by faisalman**
This update brings support for those who wanted to try the upcoming version of `ua-parser-js` (still in [alpha](https://www.npmjs.com/package/ua-parser-js/v/2.0.0-alpha.2?activeTab=versions))

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://faisalman.github.io/ua-parser-js-docs/v2/](https://faisalman.github.io/ua-parser-js-docs/v2/)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jakebailey** [comment]
@faisalman You own the package that you're typing; is there a reason to publish your types on DT? You can include the types in your package, then you wouldn't have to worry about DT's alpha support (TS would just use the types from your package).

**Comment by faisalman** [comment]
> @faisalman You own the package that you're typing; is there a reason to publish your types on DT? You can include the types in your package, then you wouldn't have to worry about DT's alpha support (TS would just use the types from your package).

I'm planning to include the types in the package after some time, but for now I find it easier to just modify the existing types available here and placed it under `/v2` path since it's still under development.

**Comment by jakebailey** [comment]
Yes, but it's not published and DT can't do pre release versions, so v2 will be marked as latest incorrectly.

**Comment by faisalman** [comment]
I'll reopen this once v2 is finally released

**Pull request closed without merging**
