### PR TITLE
Remove nodejs-captcha, not on npm, repo gone

### PR DESCRIPTION
**Pull request by jakebailey**
I have no idea what happened to this package, but it doesn't exist on npm, its repo is gone, CDNs don't have the files, etc. Nightly is failing because it can't find this package.

- https://www.npmjs.com/package/nodejs-captcha 404
- https://github.com/ozgur-dogan/nodejs-captcha 404
- https://github.com/ozgur-dogan private?
- https://unpkg.com/nodejs-captcha/ 404
- https://cdn.jsdelivr.net/npm/nodejs-captcha/ 404
- https://yarnpkg.com/package?q=nodejs-captcha crashes (oops)

Maybe this is temporary, but I get the feeling it's not, even though this package had been used in other people's projects and shouldn't be removable from npm.

### CODE REVIEW

**Review by MysteryBlokHed — COMMENTED** [review]
Do you think this should be added to `notNeededPackages.json`, or just deleted since the source package is gone?

**Comment by jakebailey** [comment]
I don't think it'd work; the not needed system checks the actual package to make sure the claimed version is correct, which would fail here on pretty sure. So I think it can only be deleted.

**Comment by jakebailey** [comment]
Leaving this broken temporarily as it's showing that there's something not quite right on the pnpm monorepo branch

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
FWIW

```
❯ npm info nodejs-captcha
npm ERR! code E404
npm ERR! 404 Unpublished on 2023-10-09T09:34:22.580Z
```

**Comment by jakebailey** [comment]
Huh, wonder how that happened, I thought that was impossible for packages that are actually used by people

**Comment by jakebailey** [comment]
Ready to merge

**Pull request merged**
