### PR TITLE
React-router 0.13 support

### PR DESCRIPTION
**Pull request by vasek**

### CODE REVIEW

**Comment by vvakame** [comment]
*react-router/react-router.d.ts*

to author(@mrk21). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mrk21** [comment]
Hi @vvakame, @vasek17,

I think it's basically good, but there are some issues listed below:

## Occurs the compile error when used `react` module instead `react/addons` module

Issue code:

**test.ts**

```ts
///<reference path='react/react.d.ts' />
///<reference path='react/react-addons.d.ts' />
///<reference path='react-router/react-router.d.ts' />

import React = require('react/addons');
import Router = require('react-router');

React.createElement(Router.RouteHandler, null);
```

```sh
$ tsc --module commonjs test.ts
test.ts(8,21): error TS2345: Argument of type 'RouteHandlerClass' is not assignable to parameter of type 'ComponentClass<any>'.
```

This issue does not occur when used not `react/addons` module but `react` module.

The reason is that defines only `React.createElement()` for ReactRouter Components on `react` internal module, and does not define on the `react/addons` internal module.

Therefore, we should add the codes shown below:

```ts
declare module "react/addons" {
  import ReactRouter = require("react-router");

  // for DefaultRoute
  function createElement(
    type: ReactRouter.DefaultRouteClass,
    props: ReactRouter.DefaultRouteProp,
    ...children: ReactNode[]): ReactRouter.DefaultRoute;

  // for Link
  function createElement(
    type: ReactRouter.LinkClass,
    props: ReactRouter.LinkProp,
    ...children: ReactNode[]): ReactRouter.Link;

  // for NotFoundRoute
  function createElement(
    type: ReactRouter.NotFoundRouteClass,
    props: ReactRouter.NotFoundRouteProp,
    ...children: ReactNode[]): ReactRouter.NotFoundRoute;

  // for Redirect
  function createElement(
    type: ReactRouter.RedirectClass,
    props: ReactRouter.RedirectProp,
    ...children: ReactNode[]): ReactRouter.Redirect;

  // for Route
  function createElement(
    type: ReactRouter.RouteClass,
    props: ReactRouter.RouteProp,
    ...children: ReactNode[]): ReactRouter.Route;

  // for RouteHandler
  function createElement(
    type: ReactRouter.RouteHandlerClass,
    props: ReactRouter.RouteHandlerProp,
    ...children: ReactNode[]): ReactRouter.RouteHandler;
}
```

## Typo in `RouteHandlerClass` interface

```ts
- interface RouteHandlerClass extends React.ReactElement<RouteHandlerProp> {}
+ interface RouteHandlerClass extends React.ComponentClass<RouteHandlerProp> {}
```

## Does not define the type definition of `router` context

ReactRouter has been added `router` context since 0.13; it's an alternative to existing `State` and `Transition` mixins. 

**Existing method:**

```ts
var Foo = React.createClass({
    mixins: [ Router.State ],
    render: function () {
        var params = this.getParams();
        return React.DOM.div('test');
    }
});
```

**New method:**

```ts
class Foo extends React.Component<any,any> {
    static contextTypes = {
        router: React.PropTypes.func
    };
    render () {
        var router = this.context.router;
        var params = router.getCurrentParams();
        return React.DOM.div('test');
    }
}
```

In the above code, a type of `this.context.router` is `any`. Therefore, we should add the context type shown below:

```ts
declare module "react-router" {
    interface Context {
        makePath(to: string, params?: {}, query?: {}): string;
        makeHref(to: string, params?: {}, query?: {}): string;
        transitionTo(to: string, params?: {}, query?: {}): void;
        replaceWith(to: string, params?: {}, query?: {}): void;
        goBack(): void;
       
        getCurrentPath(): string;
        getCurrentRoutes(): Route[];
        getCurrentPathname(): string;
        getCurrentParams(): {};
        getCurrentQuery(): {};
        isActive(to: string, params?: {}, query?: {}): boolean;
    }
}
```

Thereby, we will be able to do type checking of `router` context:

```ts
class Foo extends React.Component<any,any> {
    static contextTypes = {
        router: React.PropTypes.func
    };
    render () {
        var router: Router.Context = this.context.router;
        router.getCurrentParams(); // OK
        router.getCurrentParams2(); // Compile error
        return React.DOM.div('test');
    }
}
```

## Move the legacy type definition file to `react-router/legacy/react-router-0.12.d.ts`

We should follow `react/react.d.ts`, and move the legacy type definition file show below:

```
react-router
├── react-router.d.ts    # HEAD
├── react-router-test.ts # HEAD
└── legacy
     ├── react-router-0.12-test.ts
     └── react-router-0.12.d.ts
```

**Comment by shadeglare** [comment]
any updates?

**Comment by vvakame** [comment]
@vasek17 how about this PR?

**Comment by vvakame** [comment]
I merged #4898 .

**Pull request merged**
