### PR TITLE
prune(yargs): remove sources for old versions

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is purely to speed up tests within @types/node ecosysystem.
Each of those removed versions were tested againsts @types/node,
event if not genuily changed for more than 2 years in the upstream repo.

> ...,yandex-money-sdk,yargs,yargs v16.0,yargs v15.0,yargs v13.0,yargs v12.0,yargs v11.1,yargs v10.0,yargs v8.0,yargs-interactive,...

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
-  [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by bcoe** [comment]
I patched yargs@11 recently for a security fix, because it's used as a dependency though a popular library that uses yargs (gulp I think), perhaps we could start by removing 11 and older?

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@peterblazejewicz what happens to the folks who are pinned on an ancient version of yargs using TypeScript, they would still be able to use old versions of this library I bet?

**Comment by peterblazejewicz** [comment]
I understand. I should be succint on words: types were not updated (I could be wrong here and there). I understand there are upstream changes due to security. Let me review

**Review by andrewbranch — APPROVED** [review]
Feel free to merge when you all feel good about it. Typically security patches don’t have API effects. In case of emergency, an old version of these typings can always be brought back to make a necessary update.

**Comment by peterblazejewicz** [comment]
Ready to merge💘

**Pull request merged**
