### PR TITLE
url-parse: Expose types

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26947#issuecomment-407590806

### CODE REVIEW

**Review by harisiva — APPROVED** [review]
LGTM

Thanks for the super fast fix @andy-ms 

Just for my understanding, is a version bump not required? Does this effectively patch the existing version? (1.4.0)

**Comment by DimitryDushkin** [comment]
Hey! Yeah, I broke boolean argument and fix it here — https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27531

I think https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27531 is better because it provides predictable `query` property which is depends on arguments on `new Url` or `parse`.

**Comment by harisiva** [comment]
@DimitryDushkin, this PR fixes the type definition being exported, which got reverted in #26947. 

The boolean argument fix as you point out is addressed in 27531. Both changes are needed; I would assume that 27531 will rebase on top of this change after this merges. Thx!

**Comment by andy-ms** [comment]
types-publisher automatically fills in the patch version by incrementing.

**Pull request merged**
