### PR TITLE
fix: [node-lorem-ipsum] make loremIpsum the default export

### PR DESCRIPTION
**Pull request by joscha**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:

When doing:
```ts
import loremIpsum from 'lorem-ipsum';
```
you get a 
```
src/ui/caption/stories/caption.stories.tsx(4,8): error TS1192: Module '"/Users/joscha/dev/canva/web-ui/node_modules/@types/lorem-ipsum/index"' has no default export.
```

This can be fixed by switching on `allowSyntheticDefaultImports` or the fix in this PR.

### CODE REVIEW

**Comment by durad** [comment]
With this change in place you can't import the module and use it as it was intented. The following code:

```
import * as loremIpsum from 'lorem-ipsum';
loremIpsum();
```

would not compile with error:

```
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'lorem-ipsum'' has no compatible call signatures.
```

Travis failed for the same reason. Can you please review/update this PR and make sure that tests are passing before we are integrating the change.

**Comment by joscha** [comment]
Not sure why it failed in Travis. Locally that change worked fine. We switched on `allowSyntheticDefaultImports` for now, that seems to do the trick with the old code.

**Comment by voliva** [comment]
With new major version of lorem-ipsum, @2.0.1, it seems like the previous way to import it is now unsupported. Doing

```
import * as loremIpsum from 'lorem-ipsum';
loremIpsum();
```

Throws an exception in runtime of `loremIspum` not being a function.

Maybe it's worth reopening this PR, and exporting it as a new major version? (i.e. @types/lorem-ipsum@2.0.0)

**Comment by durad** [comment]
I've just looked at the `lorem-ipsum` github repo and it looks like they switched to TypeScript so we should probably consider retireing `@types/lorem-ipsum` as it's becoming obsolete.

However, I tried using `lorem-ipsum` from TypeScript without `@types/lorem-ipsum` and it wouldn't compile right off the bat. That is probably a bug on their side though.

**Pull request closed without merging**
