### PR TITLE
Add types for countries-list

### PR DESCRIPTION
**Pull request by dmythro**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint countries-list` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by plantain-00 — CHANGES_REQUESTED** [review]
Since the package already bundles its types, this PR is not needed

**Comment by z-ax** [comment]
@plantain-00 added types both here and inside the package, same time. This is a separate registry as I see and would like it to be at least specified here as well.

**Comment by plantain-00** [comment]
Even if this PR is merged, it will be deleted in future, you can see these libraries(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json), their types here are all deleted as soon as the packages bundles types.

**Comment by z-ax** [comment]
Or if package already has `typings` it will work as a duplicate?
Well, it's the first time I add typings, would appreciate an advice how is it better to be done (or maybe a better implementation).
Would be nice to have more discoverability for the package as well.

**Comment by plantain-00** [comment]
The PR template already state this:
> The package does not provide its own types, and you can not add them.

**Comment by z-ax** [comment]
Alright, I see now. That phrase would be more clear to me like this: "The package does not provide its own (bundled into the package) `types`/`typings`" — that was only checkbox I doubted to check :)

Closing the PR then, thanks.

**Pull request closed without merging**
