### PR TITLE
Create ng-smooth-scroll.d.ts

### PR DESCRIPTION
**Pull request by goosefraba**
Added ng-smooth-scroll typedef for project: https://github.com/d-oliveros/ngSmoothScroll

### CODE REVIEW

**Comment by vvakame** [comment]
*angular-smooth-scroll/ng-smooth-scroll.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/angular-smooth-scroll
  * http://bower.io/search/?q=angular-smooth-scroll
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (angular-smooth-scroll/ng-smooth-scroll-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@goosefraba thank you for your contributions.
please rename ngSmoothScroll/ngSmoothScroll.d.ts. 
http://bower.io/search/?q=ngSmoothScroll
https://github.com/d-oliveros/ngSmoothScroll/blob/master/bower.json#L2

**Comment by goosefraba** [comment]
@vvakame Renamed files!

**Comment by vvakame** [comment]
@goosefraba and add tests... http://definitelytyped.org/guides/contributing.html#tests

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
