### PR TITLE
add types for windows-mutex

### PR DESCRIPTION
**Pull request by bpasero**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

### CODE REVIEW

**Comment by demensky** [comment]
The package [already provide its own types](https://github.com/microsoft/node-windows-mutex/blob/master/index.d.ts).

**Comment by bpasero** [comment]
@demensky that is right, however for our use in VSCode, the module is an [optional dependency](https://github.com/microsoft/vscode/blob/a416c77e56ef0314ae00633faa04878151610de8/package.json#L164) as it only works on Windows. As such, we cannot use the types from its module because the module does not get installed on macOS or Linux. Thus, it seems the only solution is to install the types explicitly.

**Comment by bpasero** [comment]
@demensky ping (also related https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40962)

**Comment by demensky** [comment]
It is difficult to offer something universal.

If installed via `--force` then the types work:

Снимок экрана 2019-12-12 в 13 33 15

Probably need to create a related issue at [node-windows-mutex](https://github.com/Microsoft/node-windows-mutex).

**Comment by bpasero** [comment]
@demensky sorry, what is your suggestion?

**Comment by demensky** [comment]
Remove types from [node-windows-mutex](https://github.com/microsoft/node-windows-mutex/blob/master/index.d.ts) (create a PR there) and add types here (you are already doing this).

**Comment by bpasero** [comment]
@demensky sure, done: https://github.com/microsoft/node-windows-mutex/commit/a9f13b90fba1144ee202072e0acfce220737a54d

**Review by demensky — APPROVED** [review]

**Comment by orta** [comment]
OK, then this looks good to me now that is deployed

**Comment by bpasero** [comment]
@orta thanks, can you check on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40962 as well?

**Pull request merged**
