### PR TITLE
types/node-rules

### PR DESCRIPTION
**Pull request by zhuzhuzu1**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by zhuzhuzu1** [comment]
types/node-rules

**Review by e6nlaq — COMMENTED** [review]
It appears that the type definitions already exist in [node-rules](https://www.npmjs.com/package/node-rules).

**Comment by zhuzhuzu1** [comment]
types/node-rules

**Comment by zhuzhuzu1** [comment]
types/node-rules

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-rules/tsconfig.json
1. types/node-rules/package.json
1. types/node-rules/index.d.ts
1. types/node-rules/node-rules-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 53c8bf242516cc6e514f675c557a6698ca222f0c
</p>

**Review by navya9singh — CHANGES_REQUESTED** [review]
Please run `pnpm dprint fmt` to fix formatting.

**Comment by zhuzhuzu1** [comment]
Ok, please review again

**Comment by zhuzhuzu1** [comment]
Ok, please review again

**Comment by RyanCavanaugh** [comment]
@zhuzhuzu1 @hu0529

Help me understand what's going on here. Both of your PRs have unusual characteristics:
 * Repeatedly commenting the title/subject of the PR with no obvious reason
 * A lot of trouble formatting whitespace despite being told to run `dprint` multiple times
 * Targeting libraries which have *extremely* few downloads
 * Multiple sequences of consecutive newlines
 * Created between March 21st and 25th

It's a lot of coincidences with no obvious shared root cause. Are you the same author? What's happening?

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Requesting more info per above comment

**Comment by zhuzhuzu1** [comment]
> @zhuzhuzu1 @hu0529
> 
> Help me understand what's going on here. Both of your PRs have unusual characteristics:
> 
> * Repeatedly commenting the title/subject of the PR with no obvious reason
> * A lot of trouble formatting whitespace despite being told to run `dprint` multiple times
> * Targeting libraries which have _extremely_ few downloads
> * Multiple sequences of consecutive newlines
> * Created between March 21st and 25th
> 
> It's a lot of coincidences with no obvious shared root cause. Are you the same author? What's happening?

In response to your question, I would like to make the following reply: First of all, the previous PR title comment was that the submitter was not familiar with the submission rule of github, and thought that the comment should be submitted after each submission. The dprint format was formatted every time, but the dprint format was not formatted every time after submission, so we reformatted the dprint and resubmitted it every time

**Comment by RyanCavanaugh** [comment]
This package is already typed, and nothing in that response is lessening my suspicion that the same person is running both of these accounts. Blocking both users and closing their PRs.

**Pull request closed without merging**
