### PR TITLE
New d.ts for DataTables Version 1.10.5

### PR DESCRIPTION
**Pull request by vankooch**
This is a new d.ts for DataTables V. 1.10.0 - 1.10.5.
Starting from version 1.10 datatables has a new API and new Options. This file has also some of the old interfaces located under the SettingsLegacy namespace.
Anyway this is a new file with new namings, so this may not be compatible with the old d.ts file.
Also this is my first public d.ts file and I'm not sure if the structure matches your expectation.

Updated request to fix bugs in travis-ci.

### CODE REVIEW

**Comment by omidkrad** [comment]
Hi @vankooch, I don't know if you saw this, but just before this pull request I made a PL for DataTables 1.10 [here](https://github.com/borisyankov/DefinitelyTyped/pull/3676). Please note that we have to keep both the legacy API of DataTables (before v1.10) and the new API as both of them are supported in the latest version of the library and a lot of existing code including plug-ins such as (MakeEditable)[https://code.google.com/p/jquery-datatables-editable/wiki/CustomCellEditors] are still using the old API.

Can you please see if you can combine/merge this PL with the other one as it is already passing the tests?

Thanks!

**Comment by vankooch** [comment]
Hi @omidkrad sorry for the late response.
You are right. In fact dataTables internally uses the 'old' API. The 'new' api is more or less just a wrapper.
 I've added the part of the old d.ts with the old api settings and some methods, the new namespace for the 'old' stuff is SettingsLegacy. I guess for the most use cases this should work, but as not all old api calls are available in file, may be we can have a problem then.
Maybe just splitting the apis by a tpl namespace (DataTables / DataTablesLegacy) is the best way to go, as merging can make thinks complicated. What do think?
You can see the current d.ts here: 
https://github.com/Silver-Connection/DefinitelyTyped/tree/master/jquery.dataTables

**Comment by vankooch** [comment]
After some research, my conclusion is that two different namespaces make things more complicate.
For normal user, the solution with SettingsLegacy within the DataTabels namespace should be ok, as it works with the new settings api and the old one.
For plugin developers, if they use trypescript and not pure js, this also should work in most common cases. If created a OData connector with this d.ts and it works.
Anyway I guess this solution will fit most cases.

**Comment by vvakame** [comment]
@pragmatrix could you review this PR? can I merge this PR?

**Comment by pragmatrix** [comment]
Since the new type definitions stay incompatible to the 1.9 type definitions (no `fn*` functions, for example), I recommend to adhere to the contributing guide:
http://definitelytyped.org/guides/contributing.html

> In case there are multiple versions supported, the latest one will be without a version number in the file name. Older versions will be in the form of library-1.2.0.d.ts where the postfix should resemble a valid semantic version number (semver).

This way a NuGet or DT repository update would break, but users could at least change their references to the 1.9 legacy definitions and keep on going.

**Comment by vvakame** [comment]
@pragmatrix yep. but it is not required. you are 1st author (and 1st user) of this definition.
I'll merge this PR if you do not bother.

**Comment by omidkrad** [comment]
@vvakame you mean "if you don't mind." :) I'm sure he won't.

**Comment by vvakame** [comment]
@omidkrad okey, i see. kindly thank you!

**Comment by vvakame** [comment]
@vankooch it merged! thanks mate!
@pragmatrix @omidkrad thanks! https://github.com/borisyankov/DefinitelyTyped/commit/72cfe4041287b3b2014ba3df7a68f0958995f424

**Comment by vankooch** [comment]
You are welcome.. thanks to you and all other folks for this great project.

**Comment by rdennis** [comment]
Not sure if this is the proper place for this comment, or if I should open a new issue now that this is merged.

**Comment by omidkrad** [comment]
Thanks for your contributions. I wished @datatables library used TS so that it auto-generated all definitions without need for added maintenance with each upgrade of the library. The [DataTables source code](https://github.com/DataTables/DataTablesSrc) is very well structured so it should not be that hard to convert it to TypeScript. It would help a lot if the Allen, the original author, likes that.

**Pull request merged**
