### PR TITLE
Improve types of serveStatic's option parameter.

### PR DESCRIPTION
**Pull request by kseo**
- index accepts a new index string or an array of string.
- maxAges accepts a string accepted by the ms module.

### CODE REVIEW

**Comment by vvakame** [comment]
*serve-static/serve-static.d.ts*

to author(@urossmolnik). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by urossmolnik** [comment]
:+1:

**Comment by vvakame** [comment]
@urossmolnik thanks!
@kseo thanks mate!

**Comment by kseo** [comment]
@urossmolnik  @vvakame thanks!

**Pull request merged**
