### PR TITLE
feat(hapi): v18

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/hapi/issues/3871
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Please ignore everything in `v17`

### CODE REVIEW

**Comment by SimonSchick** [comment]
Hey @lenovouser any notes?

**Comment by lenovouser** [comment]
Sorry, I don't get notifications for changes in `hapi` (yet 😄). Looks good to me!

**Review by lenovouser — APPROVED** [review]

**Comment by ShayBox** [comment]
How do I use this, the package name is `@hapi/hapi` but the typings are for `hapi` so importing `hapi` gets the types but thats not actually the module, and importing `@hapi/hapi` is the module but has no types.

**Comment by SimonSchick** [comment]
Install `@types/hapi_hapi`.

**Comment by ShayBox** [comment]
Thanks :+1: There seems to be a problem with the typings, the `server` function isn't showing and `Server` is only a class, it's also a function
image

**Comment by SimonSchick** [comment]
@ShayBox Am aware, this is a current restriction in typings, you are free to create a PR to fix it :)

**Pull request merged**
