### PR TITLE
[w3c-web-usb] Include addEventListener overload to fix strict TypeScript

### PR DESCRIPTION
**Pull request by thegecko**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

Compiling TypeScript in strict mode with this type throws the following error:

> error TS2416: Property 'addEventListener' in type 'USB' is not assignable to the same property in base type 'EventTarget'.

This is due to a missing overload as outlined here:
https://github.com/Microsoft/TypeScript/issues/9604#issuecomment-231659171

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by larsgk — APPROVED** [review]
Talked to @thegecko - and this seems to be sound :)

**Review by minestarks — CHANGES_REQUESTED** [review]
This would be a good point to turn `"strictFunctionTypes": true` in the `tsconfig.json` to protect against any further breaks.

**Comment by thegecko** [comment]
Good call @minestarks `strict: true` should work as well from my investigation.

**Comment by thegecko** [comment]
Updated to have `strictFunctionTypes: true`. `strict: true` was considered but isn't backwardly compatible with the TypeScript version used.

**Review by minestarks — APPROVED** [review]

**Pull request merged**
