### PR TITLE
lodash: signatures of the method _.trimRight have been changed

### PR DESCRIPTION
**Pull request by chrootsu**
https://lodash.com/docs#trimRight
https://lodash.com/docs#_ (description of the chainable wrapper)

### CODE REVIEW

**Comment by vvakame** [comment]
thanks mate!

**Comment by iamryandrake** [comment]
This commit breaks the build.

```
typings/lodash/lodash.d.ts(7842,41): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7842,44): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7859,37): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7859,40): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7860,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(7876,39): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7876,42): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7877,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(7893,36): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7893,39): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7894,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(7989,36): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7989,39): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(7990,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8007,38): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8007,41): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8008,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8024,40): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8024,43): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8025,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8086,37): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8086,40): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8087,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8121,38): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8121,41): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8122,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8177,38): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8177,41): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8178,5): error TS1128: Declaration or statement expected.
typings/lodash/lodash.d.ts(8194,38): error TS1005: ';' expected.
typings/lodash/lodash.d.ts(8194,41): error TS1005: ';' expected.
```

**Comment by chrootsu** [comment]
@iamryandrake which versions of typescript compiller and lodash.d.ts are you using?

**Comment by iamryandrake** [comment]
Commit #0dd29bf8253536ae24e61c109524e924ea510046

**Comment by chrootsu** [comment]
It seems like the problem is not in this commit, its changes are trivial and lot of commits with same changes for other string methods already have been added earlier. I can reproduce this compile error for any commit since https://github.com/tkqubo/DefinitelyTyped/commit/35309c5a4046b2b538e1bd7e4b12ac1a49570bfe, which adds a type guard function syntax, but only with typescript 1.5.3 or less because it does not support that syntax yet. With typescript 1.6.2 it compiles fine.
Please check again that you are using 1.6.2.

**Comment by iamryandrake** [comment]
Definitely 1.6.2

**Comment by chrootsu** [comment]
Could you try to replace 'value is X' with 'boolean' in the return type of methods isArguments, isArray, isBoolean, isDate, isError, isFinite, isFunction, isNative, isNumber, isRegExp, isString in the wrong version of lodash.d.ts for test?

**Pull request merged**
