### PR TITLE
Add baidumap.d.ts

### PR DESCRIPTION
**Pull request by wushilong**
compilation succeeds with `--target es6` and `--noImplicitAny` options.
 correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
 has been used in my company project :)

### CODE REVIEW

**Comment by vvakame** [comment]
*baidumap/baidumap.d.ts*

Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/baidumap
  * http://bower.io/search/?q=baidumap
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (baidumap/baidumap-tests.ts or baidumap/baidumap-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by wushilong** [comment]
hey @vvakame !

- [x]  is correct naming convention
 -   [http://lbsyun.baidu.com/index.php?title=jspopular](http://lbsyun.baidu.com/index.php?title=jspopular)
- [x] has a test file(baidumap/baidumap-tests.ts)
- [x] pass the Travis CI test

**Comment by vvakame** [comment]
Is this definitions is type for https://www.npmjs.com/package/baidumap ?

**Comment by wushilong** [comment]
@vvakame no,that one is backend library,you need nodejs run it! this one is a webbrowser library!

**Comment by andy-ms** [comment]
Since there is a `baidumap` npm package the name should probably be reserved for that, and this one given a different name, maybe "baidumap-web" or "baidumap-client"? How do they distinguish the two packages?

I also don't know what our policy would be on merging something containing a copyright notice. @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
We cannot accept PRs for files with a different license than the repo default due to automated scripts that depend on an applicable license being applied to all files inside. Either this will need to be submitted with the license removed, or you'll need to post this file elsewhere.

The copyright comment is fine (assuming the authorship information is accurate :wink:)

**Comment by mhegazy** [comment]
Thanks for your contribution. As noted earlier we can not accept PRs with different licence terms. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR with updated licence.

**Pull request closed without merging**
