### PR TITLE
[leaflet-draw] Add Draw Handlers

### PR DESCRIPTION
**Pull request by YunS-Stacy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by reblace** [comment]
For completeness, do you want to add the other public methods to each of the interfaces?

```
initialize(...)
setOptions(...)
```

**Comment by uniqueiniquity** [comment]
Waiting to merge until @YunS-Stacy responds to the question.

**Comment by YunS-Stacy** [comment]
@reblace These methods have been added to L.Handler in type definitions for Leaflet. So I just use the extend Class Handler here.

**Comment by reblace** [comment]
If you compare the methods on ```L.Draw.Feature```, you'll see there are a couple of public methods that are new to that class (i.e., not inherited from ```L.Handler```. These include: 

```js
initialize: function (map, options) {...}
setOptions: function (options) {...}
```

I'm suggesting you add those two methods to make the declaration of the ```L.Draw.Feature``` class complete to its definition in Leaflet.draw.

Here are the relevant excerpts from the Leaflet typings from master and the Leaflet.draw source code:

[Leaflet typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts)
```js
export class Class {
    static extend(props: any): any/* how to return constructor of self extended type ? */;
    static include(props: any): any /* how to return self extended type ? */;
    static mergeOptions(props: any): any /* how to return self extended type ? */;
    static addInitHook(initHookFn: () => void): any/* how to return self extended type ? */;
}

export class Handler extends Class {
    constructor(map: Map);
    enable(): this;
    disable(): this;
    enabled(): boolean;

    // Extension methods
    addHooks?(): void;
    removeHooks?(): void;
}
```

And here's the list of public methods from leaflet-draw's Feature class:

[Leaflet.draw source](https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/handler/Draw.Feature.js)
```js
L.Draw.Feature = L.Handler.extend({
...
initialize: function (map, options) {...}
enable: function () {...}
disable: function () {...}
addHooks: function () {...}
removeHooks: function () {...}
setOptions: function (options) {...}
...
}
```

**Comment by YunS-Stacy** [comment]
@rebrace Thanks for the advice! I have updated the definitions.

**Comment by reblace** [comment]
It looks like the build failure was just a lint error on the line being too long. Can probably fix that by just formatting it differently.

**Comment by uniqueiniquity** [comment]
@reblace Waiting for re-approval before merging.

**Comment by reblace** [comment]
Approved

**Pull request merged**
