### PR TITLE
sequelize: allow null value with setter/getter 

### PR DESCRIPTION
**Pull request by frogcjn**

### CODE REVIEW

**Comment by frogcjn** [comment]
** notice ** this is for TypeScript 2.0, so the checks have failed.

**Comment by mhegazy** [comment]
@frogcjn is there any pointer to the docs that null is allowed?

**Comment by frogcjn** [comment]
@mhegazy , set setter/getter to null can prevent the data show on the output. So it is a database only attribute.

**Comment by frogcjn** [comment]
@mhegazy, I'll rethink of this. Thanks!

**Pull request closed without merging**
