### PR TITLE
remove log4js

### PR DESCRIPTION
**Pull request by taoqf**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by weswigham — APPROVED** [review]
Great. Read over the associated issue with the log4js owner. I'll merge this immediately.

**Comment by Flarna** [comment]
Seems this change broke `karma` as it depends on `log4js`.

**Comment by weswigham** [comment]
@andy-ms Do tests on dependent packages not get triggered on removal?

**Comment by andy-ms** [comment]
Hm, apparently not. Microsoft/types-publisher#389

**Pull request merged**
