### PR TITLE
Use PartialObject for object predicates in _.every, _.find and _.some

### PR DESCRIPTION
**Pull request by lukas-zech-software**
This PR introduces the new Typescript keyword *keyof* to make the predicate objects used in _.every, _.find and _.some partially typed to their respective collections' type

- [ ] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

`tslint` returns a few hundred warnings, which were already present before this PR
To keep this PR scoped to the actual changes I did not fix any lint warnings other than those affected by my changes

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

The changes only make use of a the new Typescript  keyword *keyof* the meaning of the typings haven't changed at all

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
build fails due to an error in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/ace

Does not seem to be conncted to my changes?

**Comment by lukas-zech-software** [comment]
The *keyof* keyword is only available in  >=TS 2.1 so this basically is a breaking change in the typings for older TS versions.

I don't know if there is any policy for such changes?
Which version of TS should typings target?

**Comment by enaeseth** [comment]
@lukas-zech-software it's covered at the bottom of the readme; there's a section [“I want to use features from TypeScript 2.1”](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-use-features-from-typescript-21)

**Comment by andy-ms** [comment]
We don't accept pull requests to `types-2.0` any more (#13233). Please rebase onto `master`, then hit "Edit" in the upper-right and change the base branch to `master`.

**Comment by lukas-zech-software** [comment]
I'll close this PR and will open another pointing to the correct branches

**Pull request closed without merging**
