### PR TITLE
new definitions for riot-api-nodejs

### PR DESCRIPTION
**Pull request by lucalaissue**
definitions for the nodejs module "riot-api-nodejs"

### CODE REVIEW

**Comment by ZafixLRP** [comment]
you can find the module here : https://github.com/zafixlrp/riot-api-nodejs

**Comment by horiuchi** [comment]
*riot-api-nodejs/riot-api-nodejs.d.ts*

Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/riot-api-nodejs
  * http://bower.io/search/?q=riot-api-nodejs
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (riot-api-nodejs/riot-api-nodejs-tests.ts or riot-api-nodejs/riot-api-nodejs-tests.tsx)
* [ ] pass the Travis CI test?

**Comment by horiuchi** [comment]
@ZafixLRP Thanks mate!

**Comment by ZafixLRP** [comment]
@horiuchi Thanks for merge :)

**Pull request merged**
