### PR TITLE
[yup] Add support for custom type-assertion tests that narrow the schema type

### PR DESCRIPTION
**Pull request by iansan5653**
This PR is not a change to fix a bug or reflect updates to the library. Instead it's  a proposal for a new feature in the typings for this library (Yup). 

Currently you can already use some built-in schema functions to modify the types of your Yup schemas. For example, `yup.string()` has type `StringSchema<string>` while `yup.string().nullable()` has the type `StringSchema<string | null>`.

However, there's no way to build your own modifier functions. You can create custom tests, but you can't use them to change the type of the schema, so if you use `InferType` to infer the type from the schema, you'll still only get the original type. For example:

```ts
const anySchema = yup.mixed(); // MixedSchema<any>

// We want to test that the recieved item is a Set of numbers:
const setSchema = anySchema.test(
  "is-set-of-numbers",
  "${path} must be an ES6 Set of numbers",
  (value): value is Set<number> =>
    value instanceof Set && Array.from(value.values()).every(el => typeof el === number)
);

// So now we know if we use that schema on an object, we'll be sure it's a set of numbers
// However, if we infer the type:
type OurSet = yup.InferType<typeof setSchema>; // any ❌ 
```

With this update, `test` is changed to a generic function that detects if the test function is of the form `(value): value is U` and narrows the schema down to `U`. 

**Caveats:**

This isn't perfect. If you use a type-assertion function for `test`, it will no longer return `this`, which only matters when you are making custom schema classes:
```
// Example from the test file:

class CustomDateSchema extends yup.date {
    // This function needs to return `CustomDateSchema`, NOT `DateSchema`
    isWednesday(message?: string): CustomDateSchema {
        // Therefore `test` cannot naively return `DateSchema` always - in this case it needs to return `this`
        return this.clone().test({
            name: 'Wednesday',
            message: message || '${path} must be Wednesday',
            test: value => true /* boring check that the day is Wednesday */,
        });
    }
}
```

This isn't that common of a case, but it does happen and if you were creating a class that extends a schema, you would almost certainly be using `test` to create custom tests.

~~To solve this problem, I provide two simple workarounds. First, if the function passed to `test` is not a type assertion function, then `test` returns `this`. Second, if an object is used ([see documentation](https://github.com/jquense/yup#mixedtestoptions-object-schema)), the type modifying behavior won't kick in at all, no matter what test function is used. This is both to provide a workaround for the above and because to make this work would be overcomplicating the types.~~

To solve this problem, I included function overloads such that if the test function isn't a type assertion function, the `test` call will return `this` instead of the refined type. Essentially, type-asserting tests won't work with subclassed schemas, but no functionality is lost.

The only other caveat is that this doesn't work at all on array schemas; due to the way they are defined, this would be much too complicated. Also, there's not really much point since you can write custom tests for the array members; when would you ever be able to use a type assertion test function on the array schema itself? 

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by mauricedb** [comment]
Hi @iansan5653

Thanks for the PR. I had a quick look and it wasn't quite clear to me what this PR enables that you currently can't do yet. At the moment you can provide a generic type to `MixedSchema<T>` that will be picked up by `yup.InferType<T>`. The `test()` function preserves the generic type so nothing is lost.

```
const setSchema = yup
  .mixed<Set<number>>()
  .test(
    "is-set-of-numbers",
    "${path} must be an ES6 Set of numbers",
    (value): value is Set<number> =>
      value instanceof Set &&
      Array.from(value.values()).every(el => typeof el === "number")
  );

type OurSet = yup.InferType<typeof setSchema>;
// Result: OurSet === Set<number>
```

The same king of thing can be done using a `yup.string()` like this:
```
const personSchema = yup.object({
  gender: yup.string<"male" | "female">()
});

type Person = yup.InferType<typeof personSchema>;
// Result:
// type Person = {
//   gender: "male" | "female";
// }
```

Maybe I am missing something here, as I said I just had a quick look.

**Comment by iansan5653** [comment]
@mauricedb You can do that, but it's essentially the same thing as using a type assertion - you're pretty much saying:

```ts
yup.object({
  yup.string() as StringSchema<"male" | "female">
});
```

This actually violates the 6th point in the DefinitelyTyped [Common Mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes) and should eventually be removed, I think.

The method introduced here allows you to do this in a completely type-safe manner. It's akin to the way `Array.filter` is typed in the standard library:

```ts
// Array<number | string>
const inputArray = [1, 2, "string", 3];

const isNumber = (value: any): value is number => typeof value === "number";

// Array<number>
const outputArrayA = inputArray.filter(isNumber);
```

Perhaps more importantly, as I hinted at in that example, you can make reusable tests with this. Although for the reusability case, maybe I should make it work for objects as well. I just didn't do it before because of the complexity but it might be worth it.

```ts
const isThing = (value: any): value is Thing => value instanceof Thing;

// MixedSchema<Thing>
const schema = yup.mixed().test("is-thing", "message", isThing);
```

**Comment by iansan5653** [comment]
I went ahead and made it work when the custom test is an object as well as it's not as complicated as I expected.

**Comment by mauricedb** [comment]
@iansan5653 Agreed. There is a merge conflict but when fixed I will approve this PR.

**Comment by iansan5653** [comment]
@mauricedb conflicts should be resolved now.

**Review by mauricedb — APPROVED** [review]

**Comment by mauricedb** [comment]
Great, thanks for the PR

**Comment by iansan5653** [comment]
Ready to merge

**Pull request merged**
