### PR TITLE
update sequelize definitions to return a promise

### PR DESCRIPTION
**Pull request by mypark**
returning a promise and a few more find method definitions

### CODE REVIEW

**Comment by drinchev** [comment]
I'm working on a sequelize definition files based on version 3, which has more of your changes included. Actually what I discovered is that version 3 uses the Promise library of bluebird so there is no need of making a Promise interface that lives inside sequelize. I hope I would finish the definition files until the end of next week. 

Also as a matter of fact the Validation interface is also not needed, since sequelize uses validation.js library which already has definition files in the repo.

**Comment by mypark** [comment]
ok sure - maybe we'll just wait on those changes then instead and use them

**Comment by drinchev** [comment]
Hey @mypark sorry for the delay.

My pull request was merged. Parts of it include your changes

https://github.com/borisyankov/DefinitelyTyped/pull/5251

I guess this pull request can be closed or if you use sequelize 2.X you can merge these in to sequelize-2.d.ts. Best

**Comment by mhegazy** [comment]
Can you please fix the failing Travis CI tests and update the PR!

**Comment by RyanCavanaugh** [comment]
Hello and thank you for your contribution!

Due to an excessively long queue of pull requests that have become stale, we are "declaring bankruptcy" and closing all PRs opened before May 1, 2016. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

Going forward, we are committing to review or merge all PRs on a regular basis so this bankruptcy will not occur again. We apologize for the incovenience and hope you will continue to contribute to DefinitelyTyped in the future.

Thanks
The TypeScript and DefinitelyTyped teams

**Pull request closed without merging**
