### PR TITLE
renderTarget is optional in Three.js SavePass

### PR DESCRIPTION
**Pull request by maccesch**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/mrdoob/three.js/blob/fb9982cffc1967d891ff5f73d1c6348e3a8d3fc7/examples/jsm/postprocessing/SavePass.js#L33
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. AxisHelper
1. BinaryTextureLoader
1. BoundingBoxHelper
1. CanvasRenderer
1. ColorManagement

<details>
<summary>as well as these 29 other properties...</summary>
<p>DynamicBufferAttribute, EdgesHelper, FaceColors, Font, FontLoader, ImmediateRenderObject, JSONLoader, LensFlare, LinearSRGBColorSpace, Math, MeshFaceMaterial, MultiMaterial, NoColorSpace, NoColors, ParametricGeometry, Particle, ParticleBasicMaterial, ParticleSystem, ParticleSystemMaterial, PointCloud, PointCloudMaterial, SRGBColorSpace, SceneUtils, TextGeometry, Vertex, VertexColors, WebGLRenderTargetCube, WireframeHelper, XHRLoader</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bbe8b3c97f07d5402bb123a8f5ba5658d40bb3fc
</p>

**Comment by joshuaellis** [comment]
Hey, can you please make this PR in three-TS-types? This is where the type library actually lives.

**Review by joshuaellis — CHANGES_REQUESTED** [review]
See above comment

**Comment by maccesch** [comment]
Ok so I added tests for my quick little change.

@joshuaellis I'm sorry I don't understand what you mean with "in three-TS-types". Is there another repository?

**Comment by joshuaellis** [comment]
> Ok so I added tests for my quick little change.
> 
> @joshuaellis I'm sorry I don't understand what you mean with "in three-TS-types". Is there another repository?

Yep! https://github.com/three-types/three-ts-types

**Comment by maccesch** [comment]
I see, thanks!

**Pull request closed without merging**
