### PR TITLE
ember-qunit and ember-test-helpers: Implement RFC 232

### PR DESCRIPTION
**Pull request by tansongyang**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://rwjblue.com/2017/10/23/ember-qunit-simplication/>, <https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by tansongyang** [comment]
While we wait for guidance on the build issue, there are a couple of things to point out.

1. The [RFC](https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md) says that, for `TestContext`, `subject`, `inject`, and `register` are [removed](https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md#changes-from-current-system). However, I chose not to remove them because I wanted to get some feedback before making a breaking change. Almost all the other changes outlined in the RFC were additive.
2. The [blog post](http://rwjblue.com/2017/10/23/ember-qunit-simplication/) says that `this.owner` exposes the "owner API", which links to the docs for [`Ember.ApplicationInstance`](https://emberjs.com/api/ember/2.16/classes/ApplicationInstance). However, both the blog post and the RFC reference `this.owner.factoryFor`, which is not listed as a property on `ApplicationInstance`. My solution was to create an intersection type, but I wonder if Ember docs need to get updated?

**Comment by chriskrycho** [comment]
1. You made the right call. Although those *will* be removed, they're not *yet*—presumably they will be at some point in the future, but that point hasn't arrived yet.
2. I'll check on this! There are a number of things like this that we missed in the last major push we did; it's a massive API so no surprise.

**Comment by chriskrycho** [comment]
I *think* the build problem is that we should have done this the opposite way: make the new typings the default (at the root of the Ember QUnit package) and move the *old* types to `v2/*`.

**Comment by tansongyang** [comment]
Doh, I read the docs wrong. Thanks for the suggestion!

**Pull request merged**
