### PR TITLE
[d3-axis] Add case BaseType on select, important for transitions

### PR DESCRIPTION
**Pull request by borracciaBlu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Simple graph with grid lines in v4](https://bl.ocks.org/anonymous/11bd68cce12df5678b483e5c8bac30cd)  
see technique used for gridlines
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by borracciaBlu** [comment]
Hi all not sure dt-bot did work, in case of duplicate please ignore. 
 
@tomwanzek @gustavderdrache @borisyankov - please review [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24717) in the next few days. 

Thanks

**Comment by tomwanzek** [comment]
@borracciaBlu We already have a larger PR involving d3-axis under discussion, see #24305. I would prefer, if at present, we roll any discussed change, such as the above into the open PR as an additional change consideration.

**Comment by tomwanzek** [comment]
Not sure why this would be required? Would the transition not operate on the same SVG container element, i.e. `SVGSVGElement` or `SVGGElement` to which the axis was originally applied? See e.g. [here](https://bl.ocks.org/HarryStevens/678935d06d4601c25cb141bacd4068ce)

**Review by tomwanzek — CHANGES_REQUESTED** [review]
See comments in the main conversation.

**Comment by borracciaBlu** [comment]
@tomwanzek so, let say you `append` or `select` without specify the type when you try to `transition` you would have:

    TS2345: Argument of type 'Axis<ScaleLinear<number, number>>' is not assignable to parameter of type '(transition: Transition<BaseType, any, null, undefined>, ...args: any[]) => any'.
      Types of parameters 'context' and 'transition' are incompatible.
    Type 'Transition<BaseType, any, null, undefined>' is not assignable to type 
     'Selection<AxisContainerElement, any, any, any>'.
          Property 'classed' is missing in type 'Transition<BaseType, any, null, undefined>'.

And it is correct because see the signature of `Selection` and `append` in `d3-selection`.

```
// GElement extends BaseType -> at least return BaseType
export interface Selection<GElement extends BaseType, Datum, PElement extends BaseType, PDatum> {
```

```
 // ChildElement extends BaseType -> at least return BaseType
 append<ChildElement extends BaseType>
```

That's the reason why i added `BaseType` to `AxisContainerElement`, in a way to cover the minimum case.

**Comment by borracciaBlu** [comment]
@tomwanzek do you want me to propagate the last comment to the other PR?

**Comment by tomwanzek** [comment]
@borracciaBlu My aplogies for the slight delay in getting back to this issue.

*tl;dnr* The definitions of `AxisContainerElement` should  remain as they are.

As I indicated before, the only two permissible container objects to apply an axis to are: `SVGSVGElement` and `SVGGElement`. So the definitions enforce this constraint, so no-one attempts to attach an axis to a and `SVGPathElement`, as your initial new test case with `select('path')` would try.
Adding `BaseType` would negate this important purpose.

As for the need to, use the generics provided with `select<...>(...)` or `append<...>(...)`, you are correct that you would have to utilize them. This is intentional as it forces the developer to make a well-informed choice that meets the `AxisContainerElement` as it currently stands.

So it is intended as a mental cue to avoid quirky run time errors later.

**Comment by borracciaBlu** [comment]
Hi @tomwanzek,

ok, I got your point for `AxisContainerElement`. 
It totally makes sense to do not change it.

That said, I think we still have an issue with `select` and `transition` in conjunction with `Axis` because even if I do `select(g)` when I do use `transition` I got


    ERROR: 164:25  expect  TypeScript@next compile error: 
        Argument of type 'Axis<number | { valueOf(): number; }>' is not assignable to parameter of type 
            '(transition: Transition<BaseType, any, any, any>, ...args: any[]) => any'.
          Types of parameters 'context' and 'transition' are incompatible.
            Type 'Transition<BaseType, any, any, any>' is not assignable to type 
          'Selection<AxisContainerElement, any, any, any>'.
              Property 'classed' is missing in type 'Transition<BaseType, any, any, any>'.

I think it's not obvious to get this kind of error at the end of the "chain".

**This is the case:**
```javascript

    // Totally valid select statement atm
    let g = select('g') // << Line that generates the error
            .attr(x, 100)
            .attr(y, 100);

    let leftAxis = leftAxis 
                .scale(scalePow())
                // do other manipulation here
                // domain()
                // range()

      // Error here because is a BaseType
     g.transition()
        .call(leftAxis); // << Error Here
```

So, as you can see we would have the error on `.call(leftAxis)` not because of the axis but because a valid syntax used before.

I think that it is not a nice experience, especially because you had a sequence of valid statements and suddenly you have an error far away from the original statement that generates the issue (even if it's a valid statement).

**Here some possibles alternatives (maybe?!):**
1 - wouldn't be better to have a different type maybe something like `type TransactionableElement` to use in conjunction with `TransitionLike` ? or
2 - prevent the use of select without specifying a type?

Let me know what you think, pls.
Thanks

**Comment by tomwanzek** [comment]
As explained before, only `SVGSVGElement` and `SVGGElement` are valid elements to apply an axis to, whether  on a selection or a transition.

`Valid JS !== Valid typesafe TS code`

Please use `let g = select<SVGGElement>('g')` to address the underlying issue in your code.

This constraint was imposed on purpose. Even with the changes that are contemplated in the process of updating **d3-axis** to ensure `strictNullChecks`, this will not change, the error message may slightly change, but it is the expected behavior to throw an error when trying to apply axis to the transition of an element, which does not meet the DOM element constraint.

As for changing the definitions for `select(...)` to force type-casting, this would be too rigid for small use cases, where it simply may not be necessary to deviate from the default. It would also be an unnecessary backwards-breaking change, for any of these small use cases.

**Comment by borracciaBlu** [comment]
Thanks 

Regards

**Pull request closed without merging**
