### PR TITLE
Add Antlr4 Definitions/Types

### PR DESCRIPTION
**Pull request by mcchatman8009**
Currently, there are no existing types/definitions for the library **antlr4** (https://www.npmjs.com/package/antlr4). This pull requests contains all the primary exposed types of the antlr4 NPM library. These changes have been tested and linted based on the advise outlined in the README.  

**I've looked over the following list, and checked off everything:**
- [X ] Test the change in your own code. (Compile and run.)
- [X ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [ X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by muratoner — COMMENTED** [review]
All propery and class/interface definition doesn't have any comments. I think you must write comment because helpfull when coding.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Please don't bulk-disable the TSLint rules. Disabling rules should be rare and be done on a per-line basis unless absolutely necessary

**Comment by mcchatman8009** [comment]
@RyanCavanaugh Thanks for the review, I've made the adjustments. I did not mean to bulk-disable as I did. Thanks for the find. I've made the changes linting. However, it looks like all builds have been timing out in Travis-CI.

**Comment by mcchatman8009** [comment]
@muratoner thanks for the suggestion

**Pull request merged**
