### PR TITLE
Types for gulp 4.0

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

#16110

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
Waiting for PR #16146.

**Comment by mhegazy** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16146 is in. @GiedriusGrabauskas can you please update.

**Review by qtagtech — APPROVED** [review]

**Comment by GiedriusGrabauskas** [comment]
Now waiting for PR #16296.

**Comment by mhegazy** [comment]
#16296 is merged, @GiedriusGrabauskas can you please refresh this PR.

**Comment by GiedriusGrabauskas** [comment]
Updated other package tests compatibility with `gulp@4` types.

@tkqubo - `types/gulp-shell` (84c34fc4d068be5f532175e541cebb99fb2e075c).
@tkrotoff - `types/karma` (17ca53b3d3505315765f3224866875ee0c2d9516).
@tkrotoff - `types/gulp-rev-replace` (04fefaec55dcc93b8486e8535e56564065b12742).

Could you review this changes? Thanks.

**Comment by tkrotoff** [comment]
For https://github.com/DefinitelyTyped/DefinitelyTyped/commit/17ca53b3d3505315765f3224866875ee0c2d9516 and specially https://github.com/DefinitelyTyped/DefinitelyTyped/commit/04fefaec55dcc93b8486e8535e56564065b12742 would be nice with gulp.parallel or gulp.series

**Comment by tkrotoff** [comment]
👍

**Comment by GiedriusGrabauskas** [comment]
@mhegazy pull request ready to be merged.

**Pull request merged**
