### PR TITLE
scoping exported interfaces with an `Interact` module

### PR DESCRIPTION
**Pull request by thasner**

### CODE REVIEW

**Comment by vvakame** [comment]
*interactjs/interact.d.ts*

to authors(@dduugg @adidahiya @thasner). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by thasner** [comment]
@vvakame , it looks like I failed to reflect some changes in the tests.  What's the preferred workflow here?  e.g. add another commit to this PR / try to --amend / abort and start a new PR

**Comment by vvakame** [comment]
@thasner I like add another commit to this PR / try to --amend. do not have to worry too much. :+1:

**Comment by adidahiya** [comment]
:+1: lgtm

**Comment by vvakame** [comment]
@adidahiya thanks!
@thasner thanks mate!

**Pull request merged**
