### PR TITLE
[react] force useMemo factory function has an explicit return

### PR DESCRIPTION
**Pull request by dreamfliper**
according to React document:
> useMemo is a React Hook that lets you cache the result of a calculation between re-renders.

Type should be able to check that is there a return value in a factory function. This can prevent users from forgetting to return value when they write a long factory function.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [useMemo](https://react.dev/reference/react/useMemo)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act

## Formatting

The following files are not formatted:
1. types/react/test/hooks.tsx

Consider running `npx dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1df67b123884113b2091ad123c20d320173a7de3
</p>

**Review by Semigradsky — APPROVED** [review]

**Comment by Hypnosphi** [comment]
This breaks the cases where `undefined` is returned explicitly:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBZNIIF84BmUEIcA5FGgIYDGMZAsAFDOqbYQAUnAlHALwA+OEgB2AEzQFgotOIA0cANoBdHsyA

```ts
import {useMemo} from 'react'

useMemo(() => undefined, [])
```

```
Type 'undefined' is not assignable to type 'never'.
```

**Comment by meyfa** [comment]
@dreamfliper @Semigradsky This broke existing code. Minimal example:

```ts
function MyComponent (): ReactElement {
  const [foo, setFoo] = useState(false)
  const bar = useMemo<string | undefined>(() => {
    if (foo) {
      return 'hello world'
    }
    return undefined
  }, [foo])
  return <div>{bar ?? ''}</div>
}
```

Previously there were no errors. Now:

```
TS2345: Argument of type  () => string | undefined  is not assignable to parameter of type  () => string 
  Type  string | undefined  is not assignable to type  string 
    Type  undefined  is not assignable to type  string 
```

I feel like the above code is entirely valid and should not error.

**Comment by meyfa** [comment]
I experimented a bit and came up with the following:

```ts
type ExcludeVoidFn<T extends Function> = (() => void) extends T ? never : T

declare function useMemo2<T> (factory: ExcludeVoidFn<() => T>, deps: DependencyList | undefined): T
```

This passes all of the following tests:

```ts
// @ts-expect error - TS2345: Argument of type  () => void  is not assignable to parameter of type  never
useMemo2(() => {}, [])

// works (object)
useMemo2(() => ({}), [])

// works (string | undefined)
useMemo2(() => Math.random() < 0.5 ? 'foo' : undefined, [])

// works (undefined)
useMemo2(() => undefined, [])

// works (null)
useMemo2(() => null, [])
```

Feel free to try out / critique the above approach. I think if the functionality added in this PR is something we want, we can try it this way. Otherwise, I suggest reverting the PR to fix the breakage.

**Comment by kevinbailey25** [comment]
Also seeing this issue in our projects... all of our `useMemo` calls that return a `undefined` are broken. This should be valid. I think this should be reverted or do something like @meyfa suggested.

**Comment by stephenzsy** [comment]
this is breaking our build. If react framework allows `undefined` as a valid value, typescript typing should confirm to that.

**Comment by miguelski** [comment]
my build is broken with this change because the value can be undefined here is a example

image

this is fault of Exclude<T, void> since typescript 5.1+ handles very similar void and undefined in the return


image

**Comment by codeaid** [comment]
This is a breaking change and I don't quite understand the reasoning behind it. Now every `useMemo` hook in my application that can store `undefined` is showing as broken.

`useMemo` memoizing `undefined` is a perfectly valid use case in React. Nothing in the [documentation](https://www.w3schools.com/react/react_usememo.asp) even mentions the word "undefined" and nowhere does it say that the hook can not or should not handle `undefined`. What is the reasoning behind this? Why are `@types/react` going down their own route and making types different from the the actual React implementation?

**Comment by miguelski** [comment]
i agree @codeaid, i think this use case should be some rule in es-lint rather than a breaking change in react types

**Comment by rezio-gary** [comment]
I would suggest revert the PR too.

**Comment by dreamfliper** [comment]
I would suggest reverting this PR too.

**Comment by dreamfliper** [comment]
> I experimented a bit and came up with the following:
> 
> ```ts
> type ExcludeVoidFn<T extends Function> = (() => void) extends T ? never : T
> 
> declare function useMemo2<T> (factory: ExcludeVoidFn<() => T>, deps: DependencyList | undefined): T
> ```
> 
> This passes all of the following tests:
> 
> ```ts
> // @ts-expect error - TS2345: Argument of type  () => void  is not assignable to parameter of type  never
> useMemo2(() => {}, [])
> 
> // works (object)
> useMemo2(() => ({}), [])
> 
> // works (string | undefined)
> useMemo2(() => Math.random() < 0.5 ? 'foo' : undefined, [])
> 
> // works (undefined)
> useMemo2(() => undefined, [])
> 
> // works (null)
> useMemo2(() => null, [])
> ```
> 
> Feel free to try out / critique the above approach. I think if the functionality added in this PR is something we want, we can try it this way. Otherwise, I suggest reverting the PR to fix the breakage.

@meyfa Can you make a PR about this.

**Comment by zombieJ** [comment]
`undefined` is a validate value in real world. It should check by `return` instead of `void` type.

**Comment by yoyo837** [comment]
Yes, very true. Unless the js world removes `undefined` and leaves `null`.

**Comment by jessemyers-lettuce** [comment]
We are using `renovate` to integrate new versions of our dependencies. This change breaks all of our `useMemo` calls and it's not clear why.

I'm guessing that the intent is to prevent `useMemo()` from returning `void`, but we have a bunch of usage along the lines of:

```ts
const foo = useMemo<Bar>(
    () => ({ ... }), // some object structure here
    [dependency1, dependency2, ...]
);
```

all of which clearly return something and all of which are being flagged as not returning `Exclude<T, void>`

Is it possible to get some documentation about why this change happened and what the correct way to declare `useMemo()` is now?

**Comment by dreamfliper** [comment]
@codeaid sorry about your unhappy journey, please check is #67132 suits you.

**Comment by Jack-Works** [comment]
same breaking change for me. code like this:

```ts
useMemo(() => {
        return message ? transformer(message, context) : undefined
    }, [message, transformer, context])
```

**Comment by LanceMoe** [comment]
Explicitly returning `undefined` from factory function will be failed, which breaks my build. Please fix it as soon as possible. 🙏🏻

**Comment by Hypnosphi** [comment]
@oxilor one of common sources of missing `return statement` is introducing a scope in an arrow function during refactoring: 

```ts
// before
const a = useMemo(() => foo(), [])

// after
const a = useMemo(() => {
  console.log('something')
  foo() // should be `return foo()` instead
}, [])
```

**Comment by oxilor** [comment]
@Hypnosphi it might be, but in this case it's better to create eslint rule, because if some condition doesn't return a value it doesn't mean that it's a mistake.

**Comment by dancerphil** [comment]
> Revert this, why tf someone accepted this?

It is reverted at #67135 and published as `@types/react@18.2.31`

**Comment by meyfa** [comment]
@td-tomasz-joniec As mentioned above, it has been reverted already.

Also, please be mindful of your language. This PR was well-intentioned and meant to prevent mistakes, which would benefit everybody. Unfortunately, the way TypeScript works is not always straight-forward and oversights are bound to happen.

@dreamfliper Thanks for your work here, by the way, and your level of professionalism surrounding the revert. If TS didn't have this weird, non-obvious behavior around `void`, this would have been a great improvement to the React types. I hope the criticism doesn't demotivate you from continuing your efforts in the TS ecosystem :)

**Comment by samiur** [comment]
Unfortunately, this is incorrect. The version I have installed `18.2.32` still has the `ExcludeVoidFn` in it.

**Comment by td-tomasz-joniec** [comment]
> Unfortunately, this is incorrect. The version I have installed `18.2.32` still has the `ExcludeVoidFn` in it.

It happens too fast, install 18.2.33

**Pull request merged**
