### PR TITLE
SharePoint: Update package description

### LINKED ISSUE #15965: sharepoint npmjs has wrong project in summary
- [x] I tried using the `@types/sharepoint` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

The npmjs project description for https://www.npmjs.com/package/@types/sharepoint is outdated and no longer valid. Currently there stands:
```
This package contains type definitions for SharePoint: 2010.1 / (https:// github.com/gandjustas/sptypescript).
```
The link to the github project is outdated since this is now here. And this is not limited to SharePoint 2010 So better:
```
This package contains type definitions for Microsoft SharePoint.
```

### PR DESCRIPTION
**Pull request by StefanSchoof**
Remove Version (works with more Versions)
Remove work project (was the no longer maintained typedef project)

Closes #15965

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

Only description Update

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
A `Project` link is mandatory.

**Comment by StefanSchoof** [comment]
I add a link to the api documentation

**Comment by andy-ms** [comment]
Please leave in `2013.1`, or else the version will go backwards to 0.0.

**Comment by StefanSchoof** [comment]
Done and now the build is green. 

Thanks

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
