### PR TITLE
Add type parameters to postal channel definitions et al

### PR DESCRIPTION
**Pull request by myitcv**
@lokeshpeta does this look :+1: to you?

### CODE REVIEW

**Comment by lokeshpeta** [comment]
@myitcv excellent good work 
like it

**Comment by myitcv** [comment]
@lokeshpeta - thanks.

@vvakame/others this is ready for review/merge.

**Comment by vvakame** [comment]
@lokeshpeta thanks!
@myitcv thanks mate :+1:

**Comment by AndiRudi** [comment]
@myitcv We have a question. We saw that the IChannelDefiniton can have a generic type and we are not sure for what this will be used. The type of data to be sent is more or less depending on the topic, not on the channel isn't it?

**Comment by myitcv** [comment]
@AndiRudi 

> The type of data to be sent is more or less depending on the topic, not on the channel isn't it?

As far as postal.js is concerned, you can do whatever you like, yes. 

But when it comes to creating a reusable type definition, given the API exposed by postal.js it only makes sense to have typed channels. Else you are into the world of using string literal types to "bind" certain topics to certain types... which by definition would be specific to your use case and not reusable.

At least that was my reasoning when putting this together. We've since stopped using postal.js and so my recollection might not be brilliant, so please challenge/query as appropriate!

**Pull request merged**
