### PR TITLE
Turf hosts own type definitions (types not needed)

### PR DESCRIPTION
**Pull request by WorldMaker**
Since https://github.com/Turfjs/turf/commit/3c455eb32800a732e66f81e1269fb4cdc3240664#diff-a79ce79da1cc6e9a7eed24038847fdc5

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by andy-ms** [comment]
When I `npm install turf` I still don't get any types though -- this should probably wait until they're published.

**Comment by WorldMaker** [comment]
The (somewhat interesting) complication here is Turf migrated away from the `turf` metapackage after 3.0 and instead more fully to an `@turf/` organization, and this metapackage in particular becomes `@turf/turf`. `npm install @turf/turf` does provide types, and is now a full semver major version past `turf`.

A deprecation warning here in these types might help push people to the updated package family.  It should be clear in the version number field in `notNeedPackages.json` as that version is larger than the last version published to the original `turf` metapackage. Though maybe it might be useful for a more specific "redirected package" helper/notification to make that even more obvious/explicit.

**Comment by andy-ms** [comment]
How about we just delete this from DefinitelyTyped and I run `npm deprecate @types/turf "'turf' has been deprecated in favor of '@turf/turf', which provides its own types."`?

**Comment by WorldMaker** [comment]
That sounds like a plan.

**Comment by andy-ms** [comment]
OK, deprecated `@types/turf`, remove the `notNeededPackages.json` change from here and I'll merge.

**Comment by WorldMaker** [comment]
👍 Rebased without the `notNeededPackages.json` change.

**Pull request merged**
