### PR TITLE
Create Definitions for sawtooth-sdk-javascript

### PR DESCRIPTION
**Pull request by Patrick-Erichsen**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
When running 

```
dts-gen -m sawtooth-sdk --dt
```

 with `dts-gen v0.6.0`, no output is produced and the command hangs indefinitely. 

Therefore most of this was generated by hand, with the exception of the `/protobuf` folder which is generated using `protobuf.js`.

**Comment by Patrick-Erichsen** [comment]
@orta 

Hello - not sure if you're the right person to ask to review this (apologies if you're not). I saw that you commented/approved [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43183) PR an hour ago so I'm assuming you're on call for DT at the moment.

Our PR for this package should be good to go but I think it's become buried in the `review` column of the board for some time now.

**Comment by Patrick-Erichsen** [comment]
@typescript-bot anything you can do to help out here bud?

**Comment by uniqueiniquity** [comment]
Thanks for your patience!

Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Comment by Patrick-Erichsen** [comment]
No problem! Thanks for the review @uniqueiniquity 👍

**Pull request merged**
