### PR TITLE
update vue.js

### PR DESCRIPTION
**Pull request by kaorun343**
- update to version 1.0.10
- more accurate type definition
- extendable type definition
- add the definitions for utilities
- prepare for `vue-class-component`

### CODE REVIEW

**Comment by vvakame** [comment]
If we can't get response from reviewer over 2 more days, please ping me again. I'll merge this PR.

**Comment by kaorun343** [comment]
While waiting for the merging of my pull request, the new version was announced, so I updated the definition file.

**Comment by kaorun343** [comment]
@vvakame 2日以上たったのでマージお願いします。よろしくお願いいたします。

**Comment by vvakame** [comment]
@kaorun343 I like japanese too, please use english. ;)

**Pull request merged**
