### PR TITLE
Exposes ScopeScheduler to TypeScript

### PR DESCRIPTION
**Pull request by bytenik**

### CODE REVIEW

**Comment by vvakame** [comment]
*rx-angular/rx.angular.d.ts*

to author(@mickdelaney). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@bytenik thank you for your contributions.
please check with `--noImplicitAny` options

**Comment by bytenik** [comment]
Fixed! :)

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
