### PR TITLE
Revert "perf: remove cors dependency on express"

### PR DESCRIPTION
**Pull request by gtpan77**
Reverts DefinitelyTyped/DefinitelyTyped#49130

### CODE REVIEW

**Review by pluma — APPROVED** [review]

**Comment by gtpan77** [comment]
Ready to merge

**Comment by gtpan77** [comment]
@RyanCavanaugh, Can you please merge this PR?

**Comment by AviVahl** [comment]
Similar issue happened to the inference of the morgan package: #50076 

So maybe the fix to express static core will fix this without needing to revert: #49879

**Comment by gtpan77** [comment]
@sandersn, please merge this PR.

**Comment by sandersn** [comment]
Is this still needed now that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50072 is merged?

**Comment by gtpan77** [comment]
@sandersn, Error is not resolved.
```
error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to parameter of type 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs>'.
      Type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to type 'RequestHandler<ParamsDictionary, any, any, ParsedQs>'.
        Types of parameters 'req' and 'req' are incompatible.
          Type 'Request<ParamsDictionary, any, any, ParsedQs>' is not assignable to type 'Request<never, never, never, never>'.
            Type 'ParamsDictionary' is not assignable to type 'never'.
```

**Comment by AviVahl** [comment]
Error is verified as resolved from my end (I had to ensure `@types/express-serve-static-core@4.17.16` got picked up)

**Comment by gtpan77** [comment]
I have checked from my end. It is still not working. Build is failing and throwing this error.

**Comment by AviVahl** [comment]
Make sure the project you are building uses the new `@types/express-serve-static-core`.

Worked fine on my end: https://github.com/wixplosives/engine/commit/074c7722255c2a1b2c942646da379e24727adb13#diff-68f4de91f8e9f1a0a5668a83389ff76627c3139abaefcb942d408eeefd2df045R26

**Comment by gtpan77** [comment]
I don't use `@types/express-serve-static-core` directly as a dependency in package.json but it is in package-lock.json and using latest patch version. 
Build is working when I run it inside docker on local environment. Build is still failing on ECS (don't know what is happening there).
I had to make this change in code to run the build.
```ts
app.use(cors<express.Request>(apiConfig.corsOptions))
```

**Comment by pluma** [comment]
Sorry, I think the bot bugged out. No idea why the PR was marked as Unreviewed but also Owner Approved at the same time.

**Pull request closed without merging**
