### PR TITLE
chai-as-promised: Assertions should return Thenable

### PR DESCRIPTION
**Pull request by Kuniwak**
Assertions of chai-as-promised should return Thenable (see the [official example](https://github.com/domenic/chai-as-promised#chai-assertions-for-promises)).
### Before the patch

``` typescript
var result = chai.expect(promise).to.eventually.equal(3);
result.then(done); // Property 'then' does not exist on type 'Assertion'.¬
```
### After the patch

``` typescript
var result = chai.expect(promise).to.eventually.equal(3);
result.then(done); // OK
```

### CODE REVIEW

**Comment by Kuniwak** [comment]
@jt000, @jedmao, @Mischi Would you review this pull request, please?

**Comment by Kuniwak** [comment]
@jt000 I removed `Chai.Thenable` and reused `PromisesAPlus.Thenable`.
Please re-review it.

**Comment by jt000** [comment]
:+1:  Looks good to me. Thanks!

**Comment by vvakame** [comment]
@jt000 thanks!
@Kuniwak thanks mate!

**Pull request merged**
