### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by WillLuce**
Please fill in this template.
- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Run `tsc` without errors.
- [X] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

Version 4.0 introduced support for the page object pattern, but the current typings do not reflect the ability to return a page element. 

Under the current typings `private get usernameInput() { return browser.element('input#Username') }` results in the `usernameInput` to be returned as an instance of the `Client`, which a `selector: string` as the first argument in many cases.

For example, `getValue()` needs to be called with the syntax `this.usernameInput.getValue('#input#Username')`, which is obviously redundant. 

This request duplicates the typings for calls of the `Client` functions that make sense to call from an `Element`s point of view. In the duplicated version, the `selector: string` is removed so the developer can call it without the need to add a `selector: string`.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks @WillLuce

**Comment by WillLuce** [comment]
Can someone give me some info on why checks are failing so I can fix them?

**Comment by vvakame** [comment]
sorry, it is out problem. types-2.0/HEAD is back to green.

**Comment by WillLuce** [comment]
So, is there anything I can do to speed the merge process along?

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by WillLuce** [comment]
@vvakame Can we get this merged in now? I can take this over if the author isn't going to keep up with it. It's going to need to be updated again soon enough because another version is coming out.

**Comment by yuit** [comment]
@WillLuce  Thank you for the PR. There is a broken CI build. Once that is fixed, I will merge it in

**Comment by WillLuce** [comment]
Thanks for getting back to me. Is that something I need to fix or on your end still?

**Comment by Burgi0101** [comment]
@WillLuce I don't get your problem fully, if you do it like this:
` private get searchBtn(): any { return browser.element('.btn[type="submit"]') ; }`

you can do:
`this.searchBtn.click();`

Although I still have problems doing thing slike that:

` browser.elements(table).**value**.forEach((tr: any) =>{
            console.log(tr.getText());
  })`
as it will still recognize the value to be some Client<> generic.

**Comment by WillLuce** [comment]
@Burgi0101 I see your point, but in that way, are you not just casting that particular `private get searchBtn()` to an `<any>` type, when in fact it should be an `Element`? If that's the case, you're still having issues with the second case because `browser.elements` returns an array of `<Client>` objects.

In essence, you're fixing the problem too far upstream (on your side) when changing the typings would fix it correctly.

Methodologically, the WebdriverIO library was initially built without the page object model in mind. In that initial case, the `<Client>` was all that was needed because everything was written generally. Obviously, this use case is still valid. With the introduction of a supported page object model, a second option now exists where the user is not interacting with the browser as a whole, but with with predefined `<Element>`s. In this case, `browser.element` needs to return an `<Element>` and `browser.elements` needs to return an array of `<Element>`s.

**Comment by Burgi0101** [comment]
Don't understand me wrong, you would do me a big favour if you would change the typings!!!! I hate to cast everything to any, it removes the benefits of typescript!! I just wanted to comment that you can still workaround it as long as typings aren't fixed!

But maybe I wrote it the wrong way!

**Comment by christian-bromann** [comment]
@Burgi0101 @WillLuce 

```ts
browser.elements('.table').value.forEach((tr: any) => { console.log(tr.getText()); })
```

was released with the latest version. So I think what @Burgi0101 is asking for is if you could add typings for the elements command that returns an object with a value property that contains an array of elements

**Comment by paulvanbrenk** [comment]
@WillLuce can you fix the merge issues?

**Comment by WillLuce** [comment]
@paulvanbrenk I wasn't aware of any merge issues for me to fix. The feedback I was getting was that it was on the DT end. Can you let me know what's happening here?

**Comment by andy-ms** [comment]
This now has merge conflicts due to #12994. Please rebase onto the latest `types-2.0` and fix conflicts.

**Comment by paulvanbrenk** [comment]
@WillLuce  Looks like another change caused a merge conflict since we resolved the CI issue. Not entirely sure what happened here.

**Comment by christian-bromann** [comment]
@WillLuce could you also remove all definitions with `callback: (err: any) => P` as last parameter? WebdriverIO doesn't support callbacks since v4 anymore. Thanks!

**Comment by WillLuce** [comment]
Looks like #13229 is open and doesn't have any issues. @christian-bromann I'll relay the request to remove the callbacks over to @fsmedburg-ts and we can stop doing the same work.

**Comment by pmoleri** [comment]
Hi @WillLuce,
This PR reverted changes made in my previous PR #12994.
Is there any reason for that? Am I missing something?

**Pull request closed without merging**
