### PR TITLE
correction of credits or comments

### PR DESCRIPTION
**Pull request by eugeneYWang**
This type definition has totally nothing related to @caseycesari 's geojson parser library. The previous PR is misleading, at least on this type definition.

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [x ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by eugeneYWang** [comment]
I see how this is going on.  @Cobster @atd-schubert @JeffJacobson @icholy @danvk : would you consider having a communication with @caseycesari to coordinate the naming of both her library and this packages? 

I really appreciate the efforts of guys to define GeoJson type for TypeScript. But this type definition repo is for existed NPM packages , as the testing process assumes. In the same time, I want to use @caseycesari 's geojson parser in my angular application.

**Comment by JeffJacobson** [comment]
I think that `@types/geojson` should remain just the type definitions specified in the [GeoJSON spec](http://geojson.org/), and anything specific to the [GeoJSON.js library](https://github.com/caseycesari/GeoJSON.js) be included directly in that NPM package (as long as the library author doesn't object).

@eugeneYWang, if you were to [contribute a type definition file](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) to @caseycesari's project's repository, so that the type definition file would be part of the NPM package, that would allow you to use that library in TypeScript without the need to import `@types/geojson`.

While older versions of TypeScript didn't have the option of including a type definition file directly within an NPM package, with modern versions of TypeScript that is actually the best place to put them.

While you're waiting for the author to approve your contribution, you could have your project [import the library from your own fork of the github repository](https://docs.npmjs.com/cli/install.html) instead of from NPM.

**Comment by icholy** [comment]
Here's where this was added https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f0ce987bc1e4d807e457dcdd665532e5d483b726

**Comment by caseycesari** [comment]
Hello! I don't have much use for the type definition file for GeoJSON.js, but I'm more than happy to add one to the repo if someone needs it and opens a PR.

**Comment by eugeneYWang** [comment]
@Cobster @atd-schubert @JeffJacobson @icholy @danvk @caseycesari  Thank you everyone for participating this communication.

 Now that authors from both projects has demonstrated their points, it is best to separate this type definition from GeoJSON.js, which is exactly what my PR here trying to do. 

Maybe someone here can approve this PR? 

Thanks.

**Comment by eugeneYWang** [comment]
> Here's where this was added [f0ce987](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f0ce987bc1e4d807e457dcdd665532e5d483b726)

Yeah, someone from Microsoft just link a bunch of NPM existed projects to type definitions under the same name.

**Comment by sheetalkamat** [comment]
@sandersn it seems like something went wrong when linking npm packages and types. Can you please take alook and see what and how to fix this.

**Comment by eugeneYWang** [comment]
> @sandersn it seems like something went wrong when linking npm packages and types. Can you please take alook and see what and how to fix this.

@SheetJSDev This is more like an exception.

**Comment by sandersn** [comment]
@eugeneYWang Yes, it is an exception. I had to update 800 package URLs, so I didn't have time to verify each one. (I did actually look at geojson, but the homepage of @caseycesari 's project mentions 'geojson' in the README so I took that as close enough.)

It sounds like there are 3 actions to take:

1. Add type definitions to @caseycesari's package on npm.
2. Add an exception to dts-critic, the package that checks for consistency with npm.
3. Update this PR to additionally mark this package as non-npm. The first line should then read:

```ts
// Type definitions for non-npm package geojson 7946.0
```

I will do step (2) and report back when I am done.

**Comment by sandersn** [comment]
OK, dts-critic 1.0.4 is available, and types-publisher should use it for the CI tests now.

**Comment by eugeneYWang** [comment]
@sandersn I have also updated the first line as suggested. Please check it out.

**Comment by sandersn** [comment]
Thanks a lot for co-ordinating this solution @eugeneYWang. Hopefully the situation will be usable for everyone.

**Pull request merged**
