### PR TITLE
Add tapable as a dependency to webpack

### PR DESCRIPTION
**Pull request by spentacular**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/tapable/releases/tag/v2.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

`tapable@2.0.0` ships with built in typings which can conflict with using `tapable` as a core dependency in your project. This  adds `tapable` to the [last version](https://github.com/webpack/tapable/releases/tag/v1.1.3) that shipped without types in order to prevent any hoisting errors that happen when `tapable` > 2 exists as a top level dependency.

- [x] PR for adding tapable as an allowed dependency: microsoft/DefinitelyTyped-tools#178

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## webpack ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpack@latest/))
was missing the following properties:
1. WebpackOptionsDefaulter
1. WebpackOptionsApply
1. NodeEnvironmentPlugin
1. validate
1. validateSchema

<details>
<summary>as well as these 6 other properties...</summary>
<p>WebpackOptionsValidationError, dependencies, web, webworker, node, util</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9f4d4ab70bd0929bdbaf1973ea9994fd39089649
</p>

**Comment by spentacular** [comment]
[Here's a small repo I made to better reproduce the issue that's happening.](https://github.com/spentacular/tapable-error-example) Thanks!

**Comment by sandersn** [comment]
@sokra can you help with this? It looks like the intent of this PR is to ensure that users of `@types/webpack@4` get `@types/tapable@1` (which is the case right now) AND `tapable@1` (which might not be the case by default anymore). Is that correct? That kind of version matching-via-dependency isn't normal for `@types` packages, but might make sense for a widely-used set of packages like this.

**Comment by spentacular** [comment]
@sandersn yes, the intent is only to ensure `@types/webpack@4` which leverages `@types/tapable@1` get `tapable@1` as well. `webpack@5` ships with `tapable@2` which both ship with their own types, so neither of these would be leveraged for them. Here's the reference versions:

- [`webpack@4.44.2` (latest 4)](https://github.com/webpack/webpack/blob/v4.44.2/package.json#L27)
- [`webpack@5.0.0`](https://github.com/webpack/webpack/blob/v5.0.0/package.json#L28)

**Comment by ofhouse** [comment]
The critical case here is (correct me if I am wrong) when `@types/webpack` (which has a [dependency on `@types/tapable`](https://unpkg.com/browse/@types/webpack@4.41.25/package.json) and `tapable@^2` packages are both installed in the same package.

Then yarn would hoist the packages (and creates a flat tree like this):
```
node_modules/
├── @types/tapable/
├── @types/webpack/
└── tapable/
```

because they have all distinct package names.
So we end up having types for `tapable@2` and `tapable@1` (via `@types/tapable`)  in this package.

Because of how TypeScript compiler works, it would resolve `tapable` to `node_modules/tapable` first which [provides a `"types"` key in it's package.json](https://unpkg.com/browse/tapable@2.1.1/package.json).
So references to `'tapable'` in `@types/webpack` would then wrongly referenced to `node_modules/tapable` package.

**Comment by spentacular** [comment]
@ofhouse correct!

**Comment by ofhouse** [comment]
Ok, tested the idea in a quick repro but this doesn't seem to solve the issue.
The TypeScript compiler still resolves to the to the `tapable@2` package in this example:
https://github.com/ofhouse/DefinitelyTyped-49749

**Comment by ofhouse** [comment]
The suggested change would only create the following structure:

```
node_modules/
├── @types/
|   ├── tapable/
|   └── webpack/
|       └── node_modules/
|           └── tapable/          <-- This would be added (no type declarations)
└── tapable/
```

This changes nothing for typescript, because `@types/webpack/node_modules/tapable` has no type declarations itself.
So it would still resolve to `tapable/` for the types.
What you really want to archive is this:

```
node_modules/
├── @types/
|   └── webpack/
|       └── node_modules/
|           └── @types/tapable/   <-- Has type declarations
└── tapable/
```

**Comment by ofhouse** [comment]
I don't think that this is something we can solve on the package side.
This is rather a problem that should be fixed by yarn.

Adding the following to your `package.json` should solve the issue:
```diff
+  "private": true,
+  "workspaces": {
+    "packages": [],
+    "nohoist": [
+      "**@types/tapable**"
+    ]
+  }
```

This prevents yarn from hoisting the `@types/tapable` package.
Unfortunately this only works when you are using yarn workspaces, so if you want to publish a package you might have to convert it to a multi-repo setup.
You can read more about the nohoist option here: https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by spentacular** [comment]
@ofhouse interesting, that may have been why it had worked when I did a `yarn link` the first time, is because we were using a lerna/yarn-workspaces monorepo. Thanks for digging into it further and correcting my mistake.

**Pull request closed without merging**
