### PR TITLE
Added definitions for Bluebird 3.0

### PR DESCRIPTION
**Pull request by lhecker**
# Note:

This is a rather large PR, because the previous Bluebird version was 2.0 and I added 3.0. I thus had to move `bluebird.d.ts` to `bluebird-2.0.d.ts` and change all the references in the other projects.

It seems while doing so I "accidentally" also fixed some minor styling issues like backslashes in paths, or trailing white-spaces. Most notably `stripe-node` with 1394 changes.

It'd be cool if someone could review this. 😊
- [x] checked compilation with `npm test`.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by falsandtru** [comment]
It seems you should use `PromiseLike` instead of `BlueBird.Thenable`.

**Comment by jasonswearingen** [comment]
:+1: though hope the new types stuff in typescript 2 fixes this dependency hell we are living with....

**Comment by lhecker** [comment]
@falsandtru I didn't write the Bluebird 3.0 typings, as I've stated in the beginning of the new file. It's coming from [here](https://github.com/types/npm-bluebird) and it works very well for me. I really don't want to make a modified version only for DefinitelyTyped, because that would only further split this "dependency hell".

**Comment by falsandtru** [comment]
@lhecker I understood. Then it is okay.

**Pull request merged**
