### PR TITLE
Correct comment in node/crypto definition

### PR DESCRIPTION
**Pull request by dsueltenfuss**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
Correcting a reference

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
CI fail is unrelated (see https://github.com/microsoft/types-publisher/issues/707). You can try to retrigger by closing and reopening this PR or push some dummy change and nope that it is green on next try.

**Comment by dsueltenfuss** [comment]
Thanks, I was a little confused how my change would have broken the CI

**Review by SimonSchick — APPROVED** [review]
Pls skip v11 changes.

**Review by r3nya — APPROVED** [review]

**Review by galkin — APPROVED** [review]

**Comment by dsueltenfuss** [comment]
Is there anything I need to do about the failing DefinitelyTyped.BenchmarkPR check?

**Comment by Flarna** [comment]
@dsueltenfuss I don't think that you can do a lot here besides retry again and again.
@sandersn Any advice how to proceed with this? Benchmark CI fails frequently and this blocks merging.

**Pull request merged**
