### PR TITLE
Target ES2022 in Akamai EdgeWorkers types

### PR DESCRIPTION
**Pull request by bmatthew**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by evan-hughes — APPROVED** [review]

**Review by ananner — APPROVED** [review]

**Review by jakebailey — CHANGES_REQUESTED** [review]
What's the reason for this change? The update to `http-request-tests.ts` is purely cosmetic and the update to `index.d.ts` only adds comments.

This target shouldn't matter at all to downstream users of this package as they can set their targets themselves; the `tsconfig.json` here is solely for type checking on DT itself and cannot affect downstream users.

**Comment by bmatthew** [comment]
The target change verifies our tests work with ES2022 which is what we're recommending users target.

The comments are added because of new build failures we hadn't seen before and the test change exists because the process here complains when there are no test changes.

**Review by jakebailey — APPROVED** [review]
I guess that's fine, though I'm a little surprised that this passes CI as we should be testing TS back to even TS 4.3 which wouldn't support ES2022 as a target.

**Comment by bmatthew** [comment]
Ready to merge.

**Pull request merged**
