### PR TITLE
bulk: Enable `noImplicitAny` (part 1)

### PR DESCRIPTION
**Pull request by ExE-Boss**
This enables `noImplicitAny` for the 22 out of 71 packages that don’t have build failures when it’s enabled.

Note that there’s no package in **DefinitelyTyped** with `strict` set to `false`.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by sandersn** [comment]
Close/re-open to try to trigger Travis.

**Comment by sandersn** [comment]
=(
> The following packages had errors: ace, amplify, angular, backbone-associations, backbone-relational, backgrid, browser-harness, chrome, dhtmlxscheduler, durandal/v1, gamequery, jake, giraffe, jquery.bbq, jasmine-ajax, jquery.colorpicker, jquery.jnotify, jquery.noty, jquery.timeago, jquery/v2, jquery/v1, jquerymobile, jqueryui, jsfl, jsdeferred, knockback, knockout.deferred.updates, kolite, knockout, mongodb/v2, msnodesql, mssql, naver-whale, material-ui, phonegap, nvd3, popcorn, physijs, qunit, qunit/v1, raphael, sammy, sencha_touch, sharedb, sharepoint, siesta, swipeview, underscore, viewporter, chrome, durandal/v1, jquery.bbq, jquery.bbq, jquery.colorpicker, jsdeferred, knockback, knockout.deferred.updates, kolite, naver-whale, sharedb, sharepoint, sharepoint

**Review by jgonggrijp — CHANGES_REQUESTED** [review]
I suggest the following:

- @ExE-Boss Enable the option only for the 9 packages that don't break because of it.
- @sandersn Introduce a `no-implicit-any` linter rule and disable it for the 62 packages that do break. This way, it becomes more visible to package maintainers that there's something on their to-do list.

**Comment by jgonggrijp** [comment]
@evan-hughes @joeriks @laurentiustamate94 @delphinus35 @vvatanabe @CheCoxshall @RamanBut-Husaim @gcastre @danmana @jkfb @Litee @mkozhukh @chriscamicas @sheperdwind @borisyankov @SPWizard01 @anwarjaved @fdecampredon @johnnyreilly @avidenic @psnider @Avol-V @AGBrown @geppy @fredgalvao @cyrilschumacher @horiuchi @pkeuter Can at least two of you take over here?

I requested changes, which @ExE-Boss quickly followed up on. However, this means that the packages I'm involved in aren't affected by this PR anymore, so I don't feel qualified to approve.

**Comment by ExE-Boss** [comment]
review?(@amcasey, @jablko)

**Comment by ExE-Boss** [comment]
Looks like @jablko’s PR was merged first: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42693>.

**Comment by jgonggrijp** [comment]
@ExE-Boss my apologies for holding you up here. I could have changed my review to "approve" but I didn't because I feel the DT review policy doesn't work well for bulk changes. I expressed this in more detail over here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42687#issuecomment-592545510

**Pull request closed without merging**
