### PR TITLE
Add weeks(), asWeeks() methods to Duration interface

### PR DESCRIPTION
**Pull request by mszczepanczyk**

### CODE REVIEW

**Comment by gal-indegy** [comment]
Strangely this is not present in the docs, but is in the source.
I suppose they just forgot it and will add it soon.
:+1:

**Comment by galtalmor** [comment]
Strangely this is not present in the docs, but is in the source.
I suppose they just forgot it and will add it soon.
:+1:

**Comment by adidahiya** [comment]
:+1:

**Comment by horiuchi** [comment]
@mszczepanczyk Thanks mate!
@galtalmor @adidahiya Thanks for review!

**Pull request merged**
