### PR TITLE
update(parse-path): v7 updates

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- 'parse_failed' property:
https://github.com/IonicaBizau/parse-path/compare/6.0.0...7.0.0

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ffflorian — APPROVED** [review]
Thanks and sorry for the late response!

**Review by ffflorian — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Comment by ffflorian** [comment]
@peterblazejewicz You need to comment **exactly** "Ready to merge" 😃

**Comment by peterblazejewicz** [comment]
Bummer :)

**Pull request merged**
