### PR TITLE
[word-extractor] add test for buffer documentPath param type

### PR DESCRIPTION
**Pull request by Fdawgs**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/morungos/node-word-extractor/blob/d971d9f69056245ae129bd2ce31436d518293854/lib/word.js#L28C1-L46C25

`WordExtractor().extractor()` does not handle `Uint8Array`s as the types suggest.
It checks whether the source is a `string` or `Buffer` using `typeof` and `Buffer.isBuffer()` respectively. Passing a `Uint8Array` causes it to throw an error as it's attempting to call `open()` on a null reader.

Example:

```js
'use strict'

const WordExtractor = require('word-extractor')
const extractor = new WordExtractor()

const file = Buffer.from('I am not a real Word document')

/** @see {@link https://nodejs.org/api/buffer.html#buffers-and-typedarrays | Node.js Buffers and TypedArrays} */
const uint8ArrayFile = new Uint8Array(
  file,
  file.byteOffset,
  file.byteLength / Uint8Array.BYTES_PER_ELEMENT
)

extractor.extract(uint8ArrayFile)
```
Will throw:
```bash
/home/fsmith/app/node_modules/word-extractor/lib/word.js:46
    return reader.open()
                  ^

TypeError: Cannot read properties of null (reading 'open')
    at WordExtractor.extract (/home/fsmith/app/node_modules/word-extractor/lib/word.js:46:19)
    at Object.<anonymous> (/home/fsmith/app/index.js:15:11)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
```

### CODE REVIEW

**Review by saboya — APPROVED** [review]

**Comment by navya9singh** [comment]
Thanks for the fix! Can you add a test for the same?

**Review by navya9singh — COMMENTED** [review]
Thanks for the fix! Can you add a test for the same?

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/word-extractor/word-extractor-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d5d501929196724be755e6c6714c982cc6e4094f
</p>

**Comment by saboya** [comment]
Can you rebase to master? There was another PR that fixed the typing, but did not add a test: #70867

**Comment by Fdawgs** [comment]
> Can you rebase to master? There was another PR that fixed the typing, but did not add a test: #70867

Apologies @saboya, didn't see that PR. Have rebased and amended the PR title accordingly.

**Review by saboya — APPROVED** [review]
Thanks!

**Comment by Fdawgs** [comment]
Ready to merge

**Pull request merged**
