### PR TITLE
Plotly.js: Add multi-axis support to all x and y references

### PR DESCRIPTION
**Pull request by bnpoteet**
Plotly.js Shapes, Annotations, and Images can reference any x or y axis but currently Definitely Typed only supports the first axis. I'm not sure if Plotly.js supports >10 axes, but I figure 10 should be enough for almost all use cases.

A few references:
https://plotly.com/javascript/reference/layout/shapes/#layout-shapes-items-shape-xref
https://plotly.com/javascript/reference/layout/annotations/#layout-annotations-items-annotation-axref
https://plotly.com/javascript/reference/layout/images/#layout-images-items-image-yref

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. register
1. Icons
1. Fx
1. Snapshot

<details>
<summary>as well as these 2 other properties...</summary>
<p>PlotSchema, Queue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7a81e9cd93a16135169b786594cd90bed4297a71
</p>

**Review by peterblazejewicz — COMMENTED** [review]
@bnpoteet 
I don't think we can limit what can be written that way, just to promote better intellisense, it should come with 'catch' all `string` for now:
https://github.com/Microsoft/TypeScript/issues/29729
It would require modern TS version or at least a custom type like that one:
https://github.com/sindresorhus/type-fest/blob/master/source/literal-union.d.ts

**Comment by bnpoteet** [comment]
@peterblazejewicz Thanks for your response. I'm a little confused by what you mean, though. For instance, the xref for Shapes is currently limited to 'paper' or 'x'. My change adds 'x2'-'x9' as valid inputs. Do you think that's a bad idea?

https://plotly.com/javascript/reference/layout/shapes/#layout-shapes-items-shape-xref

**Comment by peterblazejewicz** [comment]
I"m just only concerned about the range of those values, is that `x9` really the last one supported by Plotly?

**Comment by jonfreedman** [comment]
@peterblazejewicz no it's not but we have the same stuff elsewhere e.g.

```typescript
export type AxisName =
	| 'x' | 'x2' | 'x3' | 'x4' | 'x5' | 'x6' | 'x7' | 'x8' | 'x9'
	| 'y' | 'y2' | 'y3' | 'y4' | 'y5' | 'y6' | 'y7' | 'y8' | 'y9';
```

Can I suggest that we split that into a union type and then use the individual ones elsewhere e.g.

```typescript
export type XAxisName = 
    | 'x' | 'x2' | 'x3' | 'x4' | 'x5' | 'x6' | 'x7' | 'x8' | 'x9'
export type YAxisName =
    | 'y' | 'y2' | 'y3' | 'y4' | 'y5' | 'y6' | 'y7' | 'y8' | 'y9';
export type AxisName = XAxisName | YAxisName
```

Then this PR is updated to refer to those explicit types

**Comment by bnpoteet** [comment]
@peterblazejewicz I see what you mean now. Thanks for the input, @jonfreedman .

Seems like we have two options: 1) Open the range of possibilities by changing AxisName and all axis references to type string, or 2) Implement Jon's proposal and limit everything to 10 axes.

I think I prefer the second option because the specificity is helpful and I would think 10 axes covers the vast majority of use cases. Let us know what you think, Peter.

**Comment by peterblazejewicz** [comment]
Yes, pls, No2. @jonfreedman thx!

**Comment by blizzardjessica** [comment]
I have a project for a client that has 12 axes. So option 2 wouldn't work
for my case.

Thanks for tackling this.

Cheers,
Jessica

**Comment by jonfreedman** [comment]
Please just add x11 and x12 in a pr...  ---- On Sat, 05 Sep 2020 18:11:55 +0100  notifications@github.com  wrote ----

I have a project for a client that has 12 axes. So option 2 wouldn't work

for my case.



Thanks for tackling this.



Cheers,

Jessica



On Sat, Sep 5, 2020, 9:40 AM Piotr Błażejewicz (Peter Blazejewicz) <

**Comment by jonfreedman** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28584 is when we added the AxisName type, as I said then plotly actually supports an unbounded number of axes

**Comment by bnpoteet** [comment]
Just added a commit that implements all of the suggested changes. LMK if anything doesn't look quite right.

**Review by jonfreedman — APPROVED** [review]

**Comment by orta** [comment]
👍🏻 looks good to me

**Pull request merged**
