### PR TITLE
[next] Add support for state types in Next.js' App component

### PR DESCRIPTION
**Pull request by iquabius**
Next.js' App component definition doesn't allow us pass the state definition as a type parameter. Currently it's only possible to pass props definition:

```js
interface Props {
  theme: string;
}
export default class MyApp extends App<Props> {
  static async getInitialProps({ Component, router, ctx }) {}
  render () {}
}
```

With this change, we could also type the state:

```js
// ...
interface State {
  loggedUser: {
    email: string;
  };
}
export default class MyApp extends App<Props, State> {
 // ...
}
```

I took a look at the tests and I feel like I should add a new test for this use case. But I'm new to TypeScript and I couldn't understand the tests very well.

Let me know if this change is sane and I'll try to take another look at the tests.

<hr/>

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nextjs.org/docs#custom-app
  - one of the use cases: "Keeping state when navigating pages"
- [ ] ~~Increase the version number in the header if appropriate.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Review by scottdj92 — APPROVED** [review]

**Review by jthegedus — APPROVED** [review]

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
@iquabius I'm fine merging this, since an owner approved.
But if you'd like to add a test, one thing you could do is to do something like the following:
```ts
class ErrorTestAppWithState extends App<TestAppProps & WithExampleProps, { color: string }> {
    static async getInitialProps({ Component, router, ctx }: NextAppContext) {
        const pageProps = Component.getInitialProps && (await Component.getInitialProps(ctx));
        return { pageProps };
    }

    render() {
        const { Component, router, pageProps, example } = this.props;
        return <Component {...pageProps} example={example} />;
    }

    state: {}; // $ExpectError
}
```

This asserts that the state you've provided for that type is incorrect given the type you gave for `S`.

**Comment by iquabius** [comment]
@uniqueiniquity I've added the test case. Thanks for the tip.

**Review by jthegedus — APPROVED** [review]
lgtm

**Review by resir014 — APPROVED** [review]

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
