### PR TITLE
@koa/router - more detailed url params type

### PR DESCRIPTION
**Pull request by kuba-orlik**
As far as I know the params object will always be a Record<string, string>. An `any` type causes too much linting problems.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. *I think the tests don't need to be updated for this change*
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/koajs/router/blob/master/lib/router.js#L747
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by elibarzilay** [comment]
I'm making it possible to self merge when approved, but please consider adding tests.

**Comment by kuba-orlik** [comment]
I'm not sure if there's anything more to add to the current tests, as they already access the url params in a way compliant with the type I added in this PR

**Review by JounQin — APPROVED** [review]

**Comment by Guillaume-Mayer** [comment]
I think the type should be a Record<string, string | string[]> in the case of an url ending with `?param=value1&param=value2` for example.
See <https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options>

**Review by Guillaume-Mayer — CHANGES_REQUESTED** [review]
Koa uses [querystring](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) to get those params so I'm almost sure koa-router should reflect that and thus that the value could be a string array.

**Comment by Guillaume-Mayer** [comment]
Well, I confused the url route params with the query string params, so I'm the wrong one here. I'll approve.

**Review by Guillaume-Mayer — APPROVED** [review]

**Comment by kuba-orlik** [comment]
Ready to merge

**Pull request merged**
