### PR TITLE
Fix Headers.get of isomorphic-fetch

### PR DESCRIPTION
**Pull request by alexandertrefz**
According to the specification, `Headers.get` can return `null`, so this should be explicit, since TS 2.0 (strictNullChecks).

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Fetch Specification: Headers.get](https://fetch.spec.whatwg.org/#dom-headers-get)
- [x] Increase the version number in the header if appropriate. (I set it, it was nonexistent)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`. (it already exists, but doesnt contain this key)

I have fixed all lint errors bar one: `no-single-declare-module  File has only 1 module declaration — write it as an external module.` since I am not sure how to.

### CODE REVIEW

**Comment by mhegazy** [comment]
@vvatanabe  can you review this change?

**Comment by vvatanabe** [comment]
@mhegazy @atrefz There is no problem concerning the change of "backlog-js". LGTM :D

**Comment by msokk** [comment]
Why there was no version bump? This broke our CI :)

**Comment by atrefz** [comment]
As noted in the PR description there was no version present, so I set it to 0.0

However I just noticed that I changed backlog-js after checking off the list, so I guess that could use a version bump.

If you provide more information than 'this broke something' it would be easier to help I think.

**Comment by msokk** [comment]
I see, sorry for not giving details. Just some interface names changed, breaking compilation.

Does `typings.json` behave like a lockfile? For some reason it pulled down the latest version (with latest `typings` CLI) instead of the old one.

**Comment by atrefz** [comment]
That sounds like it is caused by the mistake that nobody caught - I didnt bump backlog-js since i went over the checklist before fixing it.

@mhegazy @vvatanabe how should we proceed here? Just another PR to bump the version, or 
revert this one and do a new one with the bump included?

**Pull request merged**
