### PR TITLE
Update auth0-js to 8.2.0, update auth0-lock to use auth0 v8

### PR DESCRIPTION
**Pull request by adrianchia**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/auth0.js
https://github.com/auth0/lock
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by csvn** [comment]
Nice, would be lovely to have lock typings use v8 of auth0-js.

Just a question, is it not possible to just remove the `v7` folder since `auth0-lock` won't be using them? Older typings could be used by installing an older package version, right?

**Comment by adrianchia** [comment]
I believe those are kept for historical purpose, similar to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/history, it is up to the core members to decide.

**Comment by minestarks** [comment]
It's valid to keep v7 around as it may still receive fixes that would benefit users of v7.

@csvn Do the changes look good to merge?

**Comment by csvn** [comment]
@minestarks Looks good to me. Seems to follow the updates to 'auth-lock'.

**Pull request merged**
