### PR TITLE
[nodegit] Fix some union and nullable types in nodegit

### PR DESCRIPTION
**Pull request by pvigier**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

https://www.nodegit.org/api/commit/
https://www.nodegit.org/api/diff/
https://www.nodegit.org/api/revert/
https://www.nodegit.org/api/reset/

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by dolanmiu** [comment]
Is is null? or can it be undefined?

**Comment by pvigier** [comment]
The doc says `NULL` which is a bit ambiguous but I take it as `null`.

I think, it does not make a difference as the code in generate/templates seems to check for `undefined` and `null`.

In [test/tests/diff.js](https://github.com/nodegit/nodegit/blob/master/test/tests/diff.js) near line 224, they use `null`:

```js
        return Diff.blobToBuffer(
          blob,
          null,
          buffer,
          null,
          null,
          null,
          null,
          function(delta, hunk, payload) {
            assert.equal(hunk.oldStart(), 1);
            assert.equal(hunk.oldLines(), 19);
            assert.equal(hunk.newStart(), 1);
            assert.equal(hunk.newLines(), 1);
            assert.equal(
              hunk.header().substring(0, hunk.headerLen() - 1),
              "@@ -1,19 +1 @@"
            );
            done();
});
```
For options, it seems that the convention in the type definition was to make them optional, I did the same in [types/nodegit/revert.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33466/files#diff-05c6e984f3b5ee53d5b5f897ed3282e3).

**Comment by dolanmiu** [comment]
I think maybe because its optional everywhere else, perhaps its better to do it for this case too?

**Comment by pvigier** [comment]
When something is optional they put it in square brackets like [here](https://www.nodegit.org/api/checkout/). For [diff](https://www.nodegit.org/api/diff/), it is just written that the options can be null, no square brackets.

I think we should set optional when parameters are written in square brackets in the doc. And nullable when there is a comment saying it can be null.

What do you think?

**Comment by dolanmiu** [comment]
Problem is, the docs for nodegit are notoriously bad. Check all the other people making corrective PRs into this repo

For example:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31503/files

But if you look into the docs:

https://www.nodegit.org/api/index/#getByPath

Or this:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32644/files

But the docs say:

https://www.nodegit.org/api/repository/

So yeah, take everything with a pinch of salt

**Comment by dolanmiu** [comment]
if you get time, can you test if it really is null? or can it be undefined?

**Comment by pvigier** [comment]
It works both with `null` and `undefined`.

Do you prefer that I use `undefined` instead of `null`?

**Comment by dolanmiu** [comment]
I prefer the optional `?` notation

**Comment by pvigier** [comment]
I did that.

Moreover, I add a commit to modify the types of `Time`. Contrary to what the doc says, `time` and `offset` are functions not variables.

**Comment by dolanmiu** [comment]
Thanks, looks good! approved

**Review by dolanmiu — APPROVED** [review]

**Pull request merged**
