### PR TITLE
Fix typing information on GenericQuantitativeScale and derivatives

### PR DESCRIPTION
**Pull request by rcchen**
There were some issues associated with GenericQuantitativeScale as used here: https://github.com/palantir/plottable/pull/2163

### CODE REVIEW

**Comment by vvakame** [comment]
*d3/d3.d.ts*

to author(@borisyankov). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

*dcjs/dc.d.ts*

to authors(@hansrwindhoff @mtraynham). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by mtraynham** [comment]
#4032 was just merged.  Curious if this is still necessary.

**Comment by rcchen** [comment]
I believe they cover the same ground. Let me update my tsd.json and see if the issue is fixed.

**Comment by hansrwindhoff** [comment]
...from my side this is fine...

**Comment by rcchen** [comment]
Superseded by #4531, closing this one.

**Pull request closed without merging**
