### PR TITLE
three: Add type declarations in BufferGeometryUtils

### PR DESCRIPTION
**Pull request by youngmoro**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. BoxBufferGeometry
1. CapsuleBufferGeometry
1. CircleBufferGeometry
1. ConeBufferGeometry
1. CylinderBufferGeometry

<details>
<summary>as well as these 14 other properties...</summary>
<p>DodecahedronBufferGeometry, ExtrudeBufferGeometry, IcosahedronBufferGeometry, LatheBufferGeometry, OctahedronBufferGeometry, PlaneBufferGeometry, PolyhedronBufferGeometry, RingBufferGeometry, ShapeBufferGeometry, SphereBufferGeometry, TetrahedronBufferGeometry, TorusBufferGeometry, TorusKnotBufferGeometry, TubeBufferGeometry</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c81bd69ffcc362d7f099a5d5e75753eee1a450f3
</p>

**Review by Methuselah96 — CHANGES_REQUESTED** [review]
Thanks for the PR, however these changes are [already included](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65311/files#diff-b36e48de90cf5343f894c9eb83c663c6a025930326353ae2a8764a592bfb12c6) in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65311 as part of the r151 release which is just waiting for a DT maintainer review.

**Comment by Methuselah96** [comment]
Also, FYI, if you make PRs for the three.js types in the future, those should be made in https://github.com/three-types/three-ts-types since that's where maintenance of the three.js types happen.

**Comment by youngmoro** [comment]
OK, thanks!

**Pull request closed without merging**
