### PR TITLE
Add bundles, skipDataMain and onNodeCreated

### PR DESCRIPTION
**Pull request by alvarorahul**
Added new APIs that have been added in releases since 2.1.8 til 2.1.20 or RequireJS

### CODE REVIEW

**Comment by vvakame** [comment]
*requirejs/require.d.ts*

to author(@jbaldwin). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by alvarorahul** [comment]
@jbaldwin could you please take a look at this PR?

**Comment by jbaldwin** [comment]
LGTM

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
