### PR TITLE
[gapi.auth2] Fix parameter according to latest official documentation

### PR DESCRIPTION
**Pull request by FranklinYu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [`GoogleAuth.then(onInit, onError)`](https://developers.google.com/identity/sign-in/web/reference#googleauththenoninit-onerror), [`gapi.auth2.init(params)`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2initparams)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by franklinyu** [comment]
A couple of questions:

  * Currently it is not formatted as required:

    > Formatting: Either use all tabs, or always use 4 spaces.

    It is now using 2 spaces. Should I change this as well?

  * I think this deserves a version bump. How do I do this? There is no `packages.json` in package directory, and I don’t see any header in declaration file that specifies the version.

**Comment by rbuckton** [comment]
Generally there should be a comment like `// Type definitions for <name> 1.0` at the top of the standard header that seems to be missing in this case. However, we require that the version number be major.minor only and the major and minor versions must match the major and minor versions of the source package for the definitions.

**Comment by rbuckton** [comment]
I would recommend adding a tslint.json file to this directory, containing `{ "extends": "dtslint/dt.json" }` that can help catch style and formatting rules for a declaration file.

**Comment by franklinyu** [comment]
@rbuckton There does not seem to be a source package for this on NPM; AFAIK it is only available at https://apis.google.com/js/platform.js.

And I would also love to have the `tslint.json` for this package (and also for the `gapi` package), but I'm not sure how @flawless2011 like my preference (I like tabs). I tried linting this package and there is indeed some work to do (like using `var` and missing semicolons at the end).

In addition, is there any suggestion about code width? Or documentation width? Like 80 chars? Currently it does not have unified width.

**Comment by flawless2011** [comment]
There's probably work that needs to be done to this definition because this was originally created over a year and a half ago. Things have changed with DefinitelyTyped and I haven't been keeping this up to date on that (and apparently [typings](https://github.com/typings/registry) came into and fell out of favor in that time).

Answers to your questions:
* The version is `0.0` because I couldn't find a version number anywhere on the website for Google Sign-in API. If anyone has an authoritative source for the version we can add it but I've not seen anything authoritative for that library.
* I'm not sure why the README references a specific indentation size. I prefer 2 spaces for a tab in my own TypeScript or JavaScript sources. If someone wants to convert to 4 I guess that's fine but seems like a waste of time to me. There are all kinds of definitions using everything from 8 to 2 spaces for tabs.
* I don't think we need an `.editorconfig` as I don't see them in any other type definitions on here. No more than this code changes it's probably overkill.
* Just remember this code is not changed frequently and is pretty small...let's not over-engineer things like code width, documentation width, etc.

If you want to add the linter file and update the tests from the old JavaScript to ES2015 or TypeScript go ahead and open another PR.

**Comment by franklinyu** [comment]
@flawless2011 Thanks for the information and backgrounds. I'm good with two-space indentation, but how about [these](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e545c1e19aa728dbf855ec719d8c8738d2eeff33/types/gapi.auth2/index.d.ts#L213-L245)? Is this intended? If not, shall I update them to unify the style?

**Comment by flawless2011** [comment]
Sure that'd be great, thanks.

Also, I don't see any updates to the tests, can you take a look and see if you can add some tests for the changes?

**Comment by franklinyu** [comment]
@rbuckton Thank you for your suggestion. The test fixes a bug. I will try to add linting as well, if this is not merged too soon.

In addition, do you know how I can bump the patch version so that projects can pick up the change?

**Comment by flawless2011** [comment]
That's fine if you want to clean up the tests, as long as everything still runs successfully.

Regarding the npm deployment and version I'm not sure how that's handled, I presume by one of the owners on DefinitelyTyped.

**Comment by franklinyu** [comment]
The Google documentation describe the parameter for `gapi.auth2.init()` with interface [`gapi.auth2.ClientConfig`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig). Would you like the idea of exacting the parameters of `init()` into an interface, to align with official documentation?

**Comment by andy-ms** [comment]
The patch version will be updated automatically. Is this good to go? Other improvements could be made later.

**Comment by flawless2011** [comment]
@frankliny Is there a reason you removed all the `export` keywords?

**Comment by franklinyu** [comment]
@flawless2011 I'm not sure exactly why, but they are causing linter to complain. You can add them back and see. If that is not the case, I'm happy modify that commit before it is merged.

@andy-ms the policy of this repository seems to favor quick pull request, does it? If so this is good to merge.

**Comment by andy-ms** [comment]
The linter complains about the `export` keyword because you're already in a `declare namespace`, so `export` is redundant.
Thanks!

**Pull request merged**
