### PR TITLE
Revert "`Mousetrap`: convert to UMD"

### PR DESCRIPTION
**Pull request by nicbarker**
Reverts DefinitelyTyped/DefinitelyTyped#48111

This introduced a non backward compatible breaking change with a PATCH version bump.
I'm going to reintroduce the change in a separate PR with a major version bump.

cc @OliverJAsh my fault, I wasn't thinking clearly when I approved this.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mousetrap ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mousetrap@latest/))
was missing the following properties:
1. init
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7c2d0e66c08f264a29b0dd64828ca675e36c48a3
</p>

**Comment by OliverJAsh** [comment]
I left a comment here about why I think we shouldn't bump the major version: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48111#discussion_r494815724

**Comment by nicbarker** [comment]
@OliverJAsh Thanks for the link, I've been having a read and it seems like this is a reasonably frequent occurrence with the types repo. I guess as long as people are using a lockfile or pinning their dependencies they won't be affected by this in an unexpected way.

**Comment by nicbarker** [comment]
I'm going to close this for now and just wait to see if more people turn up with problems 👍

**Pull request closed without merging**
