### PR TITLE
[@types/select2] Update missing methods parameter types

### PR DESCRIPTION
**Pull request by AlexStacker**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by denisname** [comment]
Please:

* Use a meaningful title for the pull request. **Include the name of the package modified**.
* Add or edit tests to reflect the change.
* Provide a URL to documentation.

There is no mention of these parameters in the documentation. See: http://select2.github.io/select2/.
Where did you got this from ?

**Comment by AlexStacker** [comment]
I am very sorry for my mistake. These methods were encountered when I was using them. After reading the source code, I found that some methods were not added, so I edited and submitted them directly on the webpage. The source code is here:
https://github.com/select2/select2/blob/stable/3.5/select2.js#L3560
https://github.com/select2/select2/blob/stable/3.5/select2.js#L1363-L1365

**Review by denisname — APPROVED** [review]

**Comment by denisname** [comment]
Note: documentation for `isFocused` and `focused` was added [here](https://github.com/select2/select2/pull/437/files) and wrongly removed [here](https://github.com/select2/select2/commit/dd219b2e6a841a112c33c5fc125d5f303770366f#diff-eacf331f0ffc35d4b482f1d15a887d3b)

Since these missing methods are not in the documentation, do a PR on the documentation: https://github.com/select2/select2/tree/gh-pages also.

**Comment by AlexStacker** [comment]
Thank you for your reference link, I will submit a PR, but it will be a long time, I don’t know if it will be merged.

**Pull request merged**
