### PR TITLE
[convert-source-map] Update convert-source-map to latest v1.3.0

### PR DESCRIPTION
**Pull request by TeamworkGuy2**
- [ ] Prefer to make your PR against the `types-2.0` branch. 
 -  TeamworkGuy2: _I haven't had time to install typescript@2.0 in Visual Studio and figure out how definition files work in it.  When I do, I'll update the various DT definitions I've written_
- [ ] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/thlorenz/convert-source-map/blob/master/index.js
- [x] Increase the version number in the header if appropriate.

Changes:
Added documentation copy-pasted from project's README file. 
Added some missing functions, parameters, and 'sourcemap' property based on the source code.

### CODE REVIEW

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by paulvanbrenk** [comment]
@TeamworkGuy2 migrating your changes to the [2.0 typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/convert-source-map/index.d.ts) should be relatively easy for you.

**Comment by andy-ms** [comment]
Closing this; please make a new PR targeting `types-2.0` if you still want to make this change.

**Comment by TeamworkGuy2** [comment]
FYI, see new PR (TypeScript 2.0 compatible): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13618

**Pull request closed without merging**
