### PR TITLE
fix(mapbox-gl): Map.loadImage, Evented callbacks

### PR DESCRIPTION
**Pull request by sangxxh**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - `Map.loadImage`: https://github.com/mapbox/mapbox-gl-js/blob/07179fe2ac15050d606894996d40522ef7469646/src/ui/map.js#L1759
  - `Evented` callbacks: https://github.com/mapbox/mapbox-gl-js/blob/07179fe2ac15050d606894996d40522ef7469646/src/util/evented.js#L5
- ~~[ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

-------

Fixed:
- `Map.loadImage` callback function typing
- While I was on it, also refactor `Evented` listener callback types to avoid typing callback function as just `Function`

### CODE REVIEW

**Comment by hantatsang** [comment]
@patrickr Could you please review this PR?

**Comment by dmytro-gokun** [comment]
@hantatsang I've reviewed this PR and asked for changes. Please implement those and I will accept them quickly.

**Comment by hantatsang** [comment]
@dmytro-gokun Not sure if I miss something but I don't see any requests for changes, could you check?

**Review by dmytro-gokun — CHANGES_REQUESTED** [review]

**Comment by dmytro-gokun** [comment]
@hantatsang oh, looks like i forgot to press "Request changes" button. but now i've done that :)

**Review by dmytro-gokun — APPROVED** [review]

**Comment by dmytro-gokun** [comment]
Ready to merge

**Pull request merged**
