### PR TITLE
Added ImageWMS constructor options to Openlayers dts file.

### PR DESCRIPTION
**Pull request by matjos**

### CODE REVIEW

**Comment by vvakame** [comment]
*openlayers/openlayers.d.ts*

to author(@woutergd). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@matjos thank you for your contributions.
please resolve conflict.

**Comment by woutergd** [comment]
@matjos @vvakame it are good additions but missing tests for the added functions, when those are added it is :+1: for me.

**Comment by matjos** [comment]
I dont really understand the test file but I added tests following the convetion in the file for the logic I added. Please tell me if I miss understod  anything. I also ran the tests and they where successful.

**Comment by woutergd** [comment]
@matjos Looks good already. It would be nice if you could extent the tests with a test per method in the future for the classes you implemented, so that you can check if the expected return type or parameter type is equal to the return type as described in the documentation of OpenLayers (those tests are written while taking the documentation into account to check if your type definition accepts every kind of data that should be accepted as described in the documentation). 

Also you have specified on some places the type 'any' for some properties, is it possible to specify those already to get it more strictly typed?

**Comment by matjos** [comment]
Do you know how you define a property to return a function in typescript?

**Comment by woutergd** [comment]
@matjos Yes, you have to look into callbacks for that. If I am right, both the easing and transform functions are using it currently already in this definition file, you need to look it up. If you cant find it let me know, then I will check it later tonight where I used it exactly, but at the moment I need to finish some other stuff for another project first.

**Comment by matjos** [comment]
@woutergd I found it, the syntax as below but i cant use it because i dont really know the specific function parameters for the callbacks on the methods i have put any on. So its not much more i can do.

//without param
callback: () => void;

//With param
callback: (inParam: string) => void;

**Comment by woutergd** [comment]
@matjos I looked them up in the code / documentation, the OpenLayers API is very well linked to the original source files. I have not the time to edit it myself but maybe you can update the code with the following definitions for me. 

The TileWMSOption contains the property TileLoadFunctionType which should be defined as following: 

TileLoadFunctionType: (imageTile: ol.ImageTile, src: string) => void;
(see line 9 of this file: https://github.com/openlayers/ol3/blob/v3.8.2/src/ol/tileloadfunction.js)

And under projection, you have the property getPointResolution which should be defined as follows:

getPointResolution: (resolution: number, coordinate: ol.Coordinate) => number;
(see line 133 of this file: https://github.com/openlayers/ol3/blob/v3.8.2/src/ol/proj/proj.js)

**Comment by matjos** [comment]
@woutergd Thanks for good feedback!

I fixed the two you mentioned and found one more on  ImageWMSOptions that i fixed to the link belows method signature.
https://github.com/openlayers/ol3/blob/f5cd9a3ebac748d248e04b30688db447435d23ab/src/ol/imageloadfunction.js

**Comment by woutergd** [comment]
@matjos Thanks, and great job, thanks of course for the contribution!

@vvakame For me the PR is fine now, you may merge it in my opinion.

**Comment by vvakame** [comment]
@woutergd thanks! :+1: 
@matjos thanks mate! :+1:

**Pull request merged**
