### PR TITLE
Add type definition for griddle-react

### LINKED ISSUE #6166: Definition Request - griddle-react
Hi, can you please add definition for Griddle, a grid view library for ReactJS
http://griddlegriddle.github.io/Griddle/

### PR DESCRIPTION
**Pull request by dahlbyk**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name: [`griddle-react`](https://npmjs.com/package/griddle-react)
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project. *Evolved from [griddle-react-typings](https://github.com/hodavidhara/griddle-react-typings) by @hodavidhara; I can squash if that would be preferred.*
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

Closes #6166

### CODE REVIEW

**Comment by dahlbyk** [comment]
`push --force` hides all manner of failure to actually run `npm test` locally. 😏  It's obvious in retrospect, but should that be part of the PR template checklist?

**Comment by minestarks** [comment]
Thanks for the contribution. Isn't "test your change" part of the checklist or am I misunderstanding?

**Comment by hodavidhara** [comment]
Thanks for getting this done! I had been meaning to do this forever but never got around to it. I also have some changes kicking around somewhere for the newer versions so I'll try to get them updated when I can.

**Comment by dahlbyk** [comment]
> Thanks for getting this done! I had been meaning to do this forever but never got around to it.

No problem; thanks for the original definition, @hodavidhara!

> I also have some changes kicking around somewhere for the newer versions so I'll try to get them updated when I can.

If you could push those changes to a branch somewhere, I would be glad to help test/finalize them.

**Pull request merged**
