### PR TITLE
[@types/youtube-player] Fix requiring `playlist`

### PR DESCRIPTION
**Pull request by Dok11**
This option of `Options.playerVars` are not required.
https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#playlist

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by Dok11** [comment]
It's super minor change. I dont think what this require full cycle with of testing 🤔

**Comment by jurca** [comment]
> It's super minor change. I dont think what this require full cycle with of testing

It's still better to check :). Just in case.

- [x] Test the change in your own code. (Compile and run.)
- [ ]  Add or edit tests to reflect the change. (Run with npm test.)
- [x]  Follow the advice from the readme.
- [x]  Avoid common mistakes.
- [x]  Run npm run lint package-name (or tsc if no tslint.json is present).

Would you be interested in adding a simple usage test in the `youtube-player-tests.ts` file to ensure that a future update won't break this? It's not critical, but could prove useful in the future.

**Comment by Dok11** [comment]
> Would you be interested in adding a simple usage test in the youtube-player-tests.ts file to ensure that a future update won't break this?

No, thanks =)
Thats already good enough in this state
image

**Review by jurca — APPROVED** [review]

**Comment by jurca** [comment]
@typescript-bot I thought there was a week, not 5 days to review the PR. Anyway, thanks for clarification.

**Pull request merged**
