### PR TITLE
[redux-form] Update Optional argument of push method

### PR DESCRIPTION
**Pull request by mrsekut**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://redux-form.com/8.1.0/examples/fieldarrays/>>
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by bwlt** [comment]
@mrsekut what is your scenario? why don't you push an "empty" `FieldValue`?
The fieldarray example is a bit ambiguous. I think it should be changed with `fields.push("")` i.e. pushing a valid `FieldValue` which represent an empty hobby.
The crucial point is that when you use `fields.pop` you expect that it returns a `FieldValue`, but with your changes it returns undefined. It could be a source of various bugs

**Comment by mrsekut** [comment]
The following is the case.
This is similar to the redux-form documentation, except that the form validation is not `required`.
If you submit without being filled in, it will be sent excluding 'undefined' internally.

In my project, I used `remove ()` to remove `field`, but there was no problem.
But, as you said, I felt that it could be a source of various bugs, not safe.
In fact, it seems that we can cope with this as we can force `push (undefined)` as it is.

I apologize for the trouble.
It is okay to have it closed.

**Comment by sheetalkamat** [comment]
@mrsekut @bwlt I am not sure from the conversation here if this change is correct per library spec. Can you please either close the PR if this change is not needed or if change is right, review it so I can merge this in. Thanks.

**Comment by 43081j** [comment]
FYI it seems to be right: https://github.com/erikras/redux-form/blob/7b75f1b71ace0bb4805f754347dbeb7ef96a812f/src/__tests__/FieldArray.spec.js#L1430

a test would be nice, though.

**Pull request merged**
