### PR TITLE
Fix issue in FusionCharts modules type definition

### PR DESCRIPTION
**Pull request by rohitkr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This is a substantial change - a lot of UMD identifiers changed. Can you link some API docs so we can verify which is correct?

**Comment by rohitkr** [comment]
@RyanCavanaugh , 
`fusioncharts` type definition is throwing error if we simply include the FusionCharts Charts module as below.
`import * as Charts from 'fusioncharts/fusioncharts.charts'`
is throwing below error.
```JavaScript
ERROR in [default] .../angular2-seed-fusioncharts/src/app/app.module.ts:25:24 
Module '".../angular2-seed-fusioncharts/node_modules/@types/fusioncharts/fusioncharts.charts"'
resolves to a non-module entity and cannot be imported using this construct.
```
According to [angular2-fusioncharts](https://github.com/fusioncharts/angular2-fusioncharts) documentation.
```JavaScript
// Import angular2-fusioncharts
import { FusionChartsModule } from 'angular2-fusioncharts';

// Import FusionCharts library
import * as FusionCharts from 'fusioncharts';
// Import FusionCharts Charts module
import * as Charts from 'fusioncharts/fusioncharts.charts';
```

**Comment by RyanCavanaugh** [comment]
http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y

**Comment by mhegazy** [comment]
@rohitkr is this still needed?

**Comment by rohitkr** [comment]
@RyanCavanaugh , 
In my case, if I am tyring to import fusioncharts charts module like below
```
import Charts = require('fusioncharts/fusioncharts.charts')
```
I am getting the below error
```
src/app/app.module.ts (16,1): Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.)
```

**Comment by rohitkr** [comment]
@RyanCavanaugh, @mhegazy  

I have modified the pull request, instead of adding a `namespace` declaration to the class, now I am using the `export default` in all `fusioncharts modules`.

Please have a look and let me know if it requires any changes.

**Comment by mhegazy** [comment]
That is not he correct fix either, see https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

**Comment by andy-ms** [comment]
Closing since it's been a while.

**Pull request closed without merging**
