### PR TITLE
[@types/node-telegram-bot-api] InputMediaBase caption_entities

### PR DESCRIPTION
**Pull request by saymynameplsvip**
Added `caption_entitites`, again...

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

### CODE REVIEW

**Review by XieJiSS — APPROVED** [review]
LGTM

> Including tests allows this PR to be merged by yourself and the owners of this module

We may need to modify some tests so that the bot can allow us to merge this.

**Review by Anonymous4078 — APPROVED** [review]

**Comment by asymptotee** [comment]
> LGTM
> 
> > Including tests allows this PR to be merged by yourself and the owners of this module
> 
> We may need to modify some tests so that the bot can allow us to merge this.

Done

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node-telegram-bot-api/node-telegram-bot-api-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7917a17593c61fb2bcfb6a99a01d76852368ceeb
</p>

**Review by XieJiSS — APPROVED** [review]
Approved

Let's see if we can merge without fixing the formatting issue

**Review by Anonymous4078 — APPROVED** [review]

**Comment by asymptotee** [comment]
Ready to merge

**Pull request merged**
