### PR TITLE
Replace ElementTagNameMap with HTMLElementTagNameMap

### PR DESCRIPTION
**Pull request by falsandtru**
Address https://github.com/Microsoft/TypeScript/issues/20241

### CODE REVIEW

**Comment by mDibyo** [comment]
@falsandtru This is NOT the right change for react-pointable. Over there, we specifically changed from `HTMLElementTagNameMap` to `ElementTagNameMap` since we would like to support SVG elements as well. Could you remove the change in react-pointable?

**Comment by falsandtru** [comment]
You shouldn't use `ElementTagNameMap` for SVG elements. This is an originally broken API. For example, you can't define `"a": SVGAElement` because it conflicts with `HTMLAnchorElement`. Even so, if you want to support some SVG elements, we can define and use `SVGElementTagNameMap` in each package.

**Comment by spacejack** [comment]
@falsandtru same issue with Hyperscript; it needs to accommodate HTML and SVG elements.

**Comment by falsandtru** [comment]
@mDibyo `SVGElementTagNameMap` is still defined only in nightlies. So we have to define this interface for backward compatibility.

@spacejack Okay, done.

**Comment by mDibyo** [comment]
@falsandtru Thanks for the explanation! :) It makes sense. And adding the `SVGElementTagNameMap` interface seems fine for now. Could you add a TODO to Microsoft/TypeScript#20241 to remove this after `SVGElementTagNameMap` hits typescript stable?

**Comment by falsandtru** [comment]
Unfortunately, if you support TypeScript 2.6 or lower, you can't remove `SVGElementTagNameMap` because they don't have this interface. However, you don't have to remove this even with TypeScript 2.7 or higher. Duplicated interfaces will automatically be resolve by compiler.

**Comment by mhegazy** [comment]
@falsandtru this is not the correct @types packages should not depend on nighties, and should not redefine types. `ElementTagNameMap` is in the library, and we have no plans to remove it.

**Pull request closed without merging**
