### PR TITLE
Fix for `isomorphic-fetch`

### PR DESCRIPTION
**Pull request by Igmat**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] ~~Add or edit tests to reflect the change. (Run with `npm test`.)~~ _doesn't seem to be required in this case_
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/matthew-andrews/isomorphic-fetch/issues/167
https://github.com/bitinn/node-fetch/blob/master/LIMITS.md
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by toddlucas** [comment]
Hi Ihor, the fetch definitions were [moved into the standard library](https://github.com/Microsoft/TypeScript/pull/12493) last year. There should be no need to reference fetch explicitly any longer if you're writing an isomorphic app.

**Comment by Igmat** [comment]
@toddlucas in my case `isomorphic-fetch` used as polyfill in node environment, so I don't have `dom` lib in `tsconfig`, and don't want to have it there, because it also introduces a lot of browser stuff that doesn't actually exists in node.

I tried to add `fetch` as separate lib, but it seems that there is no separate file only for it. If you know the way how to add only fetch from `dom` lib, I would appreciate your advice.

**Comment by toddlucas** [comment]
Have you tried `node-fetch`? `isomorphic-fetch` was a way to bridge the gap between `node-fetch` and `whatwg-fetch` (now the built-in `fetch`). If you only need to use `fetch` from a node application, I would suggest you try that. If you're building an isomorphic app, then you would need to have `dom` in your environment, even though you wouldn't use it server side.

While I used to maintain this library, Microsoft essentially obviated the need for active maintenance since they moved the definitions into the underlying standard library and turned this into a stub. I think we should probably close this, if you're able to find a solution that works. Thanks!

**Review by toddlucas — CHANGES_REQUESTED** [review]
Let's consider closing this PR. The TypeScript team at Microsoft refactored this set of definitions last year by incorporating an equivalent set into the standard library. If we want to modify it, we should consult with @andy-ms or others on the team.

**Comment by Igmat** [comment]
@toddlucas if I would start a project I would use `node-fetch`, but it's not always the case, for instance right now I can't do that.

But even skipping case, where `isomorphic-fetch` can't be replaced by `node-fetch`, `@types/isomorhpic-fetch` is separate package and has it's own use case.
In case of browser or isomorphic application, you **don't need** this `.d.ts`, because `dom.lib.d.ts` already included and it provides `fetch` out of the box. So `@types/isomorhpic-fetch` used ONLY for node.js when `dom` isn't included.
For whatever reason somebody decided to use fetch polyfill instead of importing fetch from its package, `@types/isomorphic-fetch` should work properly and reflect correct fetch API.

Also, don't forget that `node-fetch` (which is base for `isomorphic-fetch`) differs from browser fetch (mostly in using node.js streams) and this also should be reflected.

And I just thought, that it probably make sense to reuse `@types/node-fetch` here instead of writing them from scratch and just augment global with `fetch` function from `node-fetch`. What do you think, is it good way to go?

**Comment by toddlucas** [comment]
@Igmat, it sounds like you are only using TS on the server. If that's the case, then `node-fetch` is what you're likely using to get `fetch` functionality. The `fetch` polyfill is provided by the underlying `node-fetch` library. 

The `isomorphic-fetch` library is only needed in cases where your code will also (potentially) run in the browser, so a dependency on `dom` would be expected. In this case, the refactoring that Microsoft did makes sense. I don't see a use case where someone would want to take a dependency on `isomorphic-fetch` but not `dom`.

Would you be able to try swapping `isomorphic-fetch` for `node-fetch` as an experiment?

I may be missing something. @andy-ms or @mhegazy might have further insight.

**Pull request closed without merging**
