### PR TITLE
[@types/chrome]: Add HAREntry and HARLog to chrome.devtools.network

### PR DESCRIPTION
**Pull request by yellott**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://developer.chrome.com/extensions/devtools_network#type-Request
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/har-format
- [n/a] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [n/a] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by couven92** [comment]
According to the HAR-spec published by the W3C Web Performance Working Group:
> *DO NOT USE*
This document was never published by the W3C Web Performance Working GRoup and has been abandonned.

I therefore suggest to reject this PR.

**Comment by couven92** [comment]
Actually, after looking over it more, my orginal comment https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43407#issuecomment-605012591 appears to be wrong. The HAR DefinitelyTyped directory just refers to an outdated specification document. The Chrome API documentation actually links to a different specification. And since the documentation states that Chrome officially supports this, adding the API seems fine.

**Review by fredrikhr — APPROVED** [review]
LGTM :+1:

**Review by orta — APPROVED** [review]

**Comment by yellott** [comment]
@couven92 yes, I compared those typings to keys of the parameter object received in chrome and they matched (at least those that were marked required)

**Pull request merged**
