### PR TITLE
Fix lint issues in F1

### PR DESCRIPTION
**Pull request by mhegazy**
//cc @andy-ms

### CODE REVIEW

**Comment by neolwc** [comment]
Thank you! But what's the difference between `Function` and `void`? I am actually not sure...

**Comment by mhegazy** [comment]
`void` means "nothing". the only useful place for `void` is the return type of a function that does not return any values. 

`Function` is a an object with `typeof t === "function"` at runtime.

**Comment by neolwc** [comment]
But those methods **do** return nothing...

**Comment by neolwc** [comment]
And btw, please refer to #13284 
I updated a method there

**Comment by mhegazy** [comment]
this change is just to fix the lint errors after enabling a new lint rule on the whole repo. let me get this one in, and then get your change in as well.

**Comment by neolwc** [comment]
Cool. Thanks.

**Pull request merged**
