### PR TITLE
[chec__commerce.js] Add attributes types to product

### PR DESCRIPTION
**Pull request by kvisca**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://commercejs.com/docs/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by robbieaverill — CHANGES_REQUESTED** [review]
Please add some attributes to the product object in the tests folder

**Comment by kvisca** [comment]
@robbieaverill I've gone ahead and added an additional array value attribute to the test object.

**Review by robbieaverill — APPROVED** [review]
LGTM

**Comment by robbieaverill** [comment]
Ready to merge

**Pull request merged**
