### PR TITLE
[stripe-v3] Update Stripe checkout types to include server implementation

### PR DESCRIPTION
**Pull request by harrygr**
There are 2 ways to use Stripe Checkout: the client implementation and
the server implementation. The former requires more parameters, such as
redirect URLs and the products for the checkout session. In the server
implementation the session is created server-side so the only parameter
required for `redirectToCheckout` is the session ID.

Function overloading has been used in favour of a union type for the options parameter as this enforces exclusivity between the two implementations. See https://github.com/Microsoft/TypeScript/issues/14094 (hence the tslint rule being disabled).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

---

- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stripe.com/docs/payments/checkout/client
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by amritk — APPROVED** [review]
Looks good to me

**Review by andrewbranch — CHANGES_REQUESTED** [review]
> Function overloading has been used in favour of a union type for the options parameter as this enforces exclusivity between the two implementations.

That’s the case when overload signatures differ in more than just one parameter type. E.g., if each overload had a different return type, they wouldn’t be unifiable. Or, if each overload had a second parameter that also differed in type, the exclusivity would be important—a union would be too permissive. But in the code here, the overload signatures differ only in a single parameter type position, which means there’s effectively not a difference between doing that and using a union type, which is what the linter is complaining about. If each overload even had separate JSDoc comments, that would be a reasonable justification for using overloads, but neither of these signatures has documentation attached. Maybe I’m missing something, but it doesn’t seem like the overload is particularly helpful here. Can you elaborate on what the benefit is?

**Comment by harrygr** [comment]
>  Can you elaborate on what the benefit is?

Sure. So as far as I understand, you'd never call `redirectToCheckout` with options containing both a `sessionId` and the stuff for using it purely client-side (like `items`, `successUrl` etc).

If a union type is used for `options` then TypeScript allows this, due to the structural typing approach of the compiler. 

One way to get around this is a Xor operator as discussed in the linked issue. One could also define a `Xor` type constructor instead.

If we use function overloading then we're saying that you either have to call the function with the server options or the client options, but you can't mix the two.

e.g.

```ts
declare function redirectToCheckout(options: StripeClientCheckoutOptions): Promise<any>;
declare function redirectToCheckout(options: StripeServerCheckoutOptions): Promise<any>;

redirectToCheckout({
    sessionId: 'sess_test',
    successUrl: 'http://example.com/success'
})
```

results in:
> Argument of type '{ sessionId: string; successUrl: string; }' is not assignable to parameter of type 'StripeServerCheckoutOptions'.
  Object literal may only specify known properties, and 'successUrl' does not exist in type 'StripeServerCheckoutOptions'.

which is what we want.

whilst

```ts
declare function redirectToCheckout2(options: StripeClientCheckoutOptions | StripeServerCheckoutOptions): Promise<any>;

redirectToCheckout2({
    sessionId: 'sess_test',
    successUrl: 'http://example.com/success'
})
```

has no error.

[link to playgound](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgMpisADhAwgG2AnFwAsIEBrAewFcwB5LMYakAZ2QG8AoZf5MEgBbdgC5kcEAE8A2gF0A3HwHtaCJO3YBVKPgnsMoAObKByBFKT5d+5IcwhTK-gkLEwAJQgxoxJACSACYA-AZGTmYCCLSG1MLQAKLCcMD4YfYRzub41Jb4EBkOJsoAvjw8oJCwiCjomDio0ABu0GQUNPRMLGycvObsEFqsIMHhjs7lPEEU+HBQKDC0IAg9IMgLQcALqwAq1O1UdGAAFNTMI+JoRjgERCTkR10XvQCUEgAKUPHAgwA8UmkAD5lDM3PNFstViMNhAtjswPtDp1Tuc1ld6tgIE0oK0oMjjt1Lu9kF8fv9ASCKptthREQdHiiTv1VEN2CMxsgAOSDLQAfUghi5ABoXPZ1JodHoJFzSGAwFgxAB6JUQAAecGEWAKADoEPElWoNGyuTxSq8KmC5gtkEsVmtYfC6UjGccAExnF4cCSY27uB4dQlezgAH2uDWxLTarue6JJZOEvwgAJkVJ4NIRLsD9A9LP4vPZbE5PLZAqGYBFYqEEFEEgUZteQA)

Maybe I've misinterpreted the API, in which case I'm happy to amend my PR, but as it stands the types prevent using `redirectToCheckout` in the server implementation without a type assertion to an `any` for the options.

**Comment by andrewbranch** [comment]
@harrygr got it, thanks. FWIW, this only applies to fresh object literal checking, as object types with extra properties are still strictly subtypes of ones with a subset of those properties, so there’s no _true_ way to prohibit extra properties from making it in: [playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgMpisADhAwgG2AnFwAsIEBrAewFcwB5LMYakAZ2QG8AoZf5MEgBbdgC5kcEAE8A2gF0A3HwHtaCJO3YBVKPgnsMoAObKByBFKT5d+5IcwhTK-gkLEwAJQgxoxJACSACYA-AZGTmYCCLSG1MLQAKLCcMD4YfYRzub41Jb4EBkOJsoAvjw8oJCwiCjomDio0ABu0GQUNPRMLGycvObsEFqsIMHhjs7lPEEU+HBQKDC0IAg9IMgLQcALqwAq1O1UdGAAFNTMI+JoRjgERCTkR10XvQCUEgAKUPHAgwA8UmkAD5lDM3PNFstViMNhAtjswPtDp1Tuc1ld6tgIE0oK0oMjjt1Lu9kF8fv9ASCKghemBkGjLsgALzcFz2IbsEZjZAAckGWgA+pBDDyADRstQaDm2CQ80hgMBYMQAemVEAAHnBhFgCgA6GnCZWSzTsMVswjVOD4fDSCQABnF5kBYFIJgkAEZHQIIPhBhIAExe-jSOgSADMQeQAHcpGAJAAWHilZQ8TbbCiIg6PFFnF4cV48IA)

But, for the typical case, I buy that the overload gives a better UX. My only request is that you use `// tslint:disable-next-line` instead of disabling the rule outright, and maybe leave a comment with a brief justification so nobody hassles you about it again 🙂

**Comment by andrewbranch** [comment]
> there’s no true way to prohibit extra properties from making it in

Well, as you pointed out, you could prohibit _specific_ extra properties from making it in by declaring them as `undefined` or `never` or something, a la that horrifying/beautiful/not-sure-how-to-feel-about-it XOR mapped type. 😄  But you can’t guard against _arbitrary_ extra properties.

**Comment by harrygr** [comment]
Hey @andrewbranch thanks for your feedback and apologies for the delay.

I've amended my PR as requested.

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Pull request merged**
