### PR TITLE
node-forge: add types for pkcs7

### PR DESCRIPTION
**Pull request by joeflateau**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by beenotung** [comment]
@joeflateau thanks, however it seems the shape of `PkcsSignedData` is incomplete, attached what I saw from the repl:


By the way, there are also `lib.pkcs7.createEncryptedData()` and `lib.pkcs7.createEnvelopedData()`

And most importantly, version 0.7.7 doesn't exist for node-forge yet.

**Comment by joeflateau** [comment]
@beenotung yes, I just added the items that I needed, didn't go and do the entire namespace. And my bad on the version bump, i was thinking the version was a "@types" version not that it was supposed to match the node-forge version

**Comment by beenotung** [comment]
@joeflateau as my quick check, the declaration of `PkcsSignedData` seems incorrect, as least some optional fields are marked as mandatory.
```javascript
> x=lib.pkcs7.createSignedData()
{ type: '1.2.840.113549.1.7.2',
  version: 1,
  certificates: [],
  crls: [],
  signers: [],
  digestAlgorithmIdentifiers: [],
  contentInfo: null,
  signerInfos: [],
  fromAsn1: [Function: fromAsn1],
  toAsn1: [Function: toAsn1],
  addSigner: [Function: addSigner],
  sign: [Function: sign],
  verify: [Function: verify],
  addCertificate: [Function: addCertificate],
  addCertificateRevokationList: [Function: addCertificateRevokationList] }
> x.content
undefined
> x.contentInfo
null
> x.addCertificate.length
1
> x.addSigner.length
1
> x.sign.length
1
> x.toAsn1.length
0
```
v.s. part of your declaration
```typescript
{
  content: string;
  contentInfo: { value: any[] };
}
```

**Comment by joeflateau** [comment]
@beenotung thank you, i've marked those as optional and added the missing optional argument of sign(options?: { detached?: boolean })

**Pull request merged**
