### PR TITLE
Add type definitions for Egg.js

### PR DESCRIPTION
**Pull request by ToastHawaii**
The egg.js-tests are based on the docs from Egg.js. The name is the same
as the Egg.js bower project: http://bower.io/search/?q=egg.js (an npm
project does not exists). And I run the tsc and npm tests.

### CODE REVIEW

**Comment by vvakame** [comment]
*egg.js/egg.js.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/egg.js
  * http://bower.io/search/?q=egg.js
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (egg.js/egg.js-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@ToastHawaii LGTM :+1: 
please rebase to master/HEAD. maybe .gitignore is conflicted.

**Comment by ToastHawaii** [comment]
Yes, I have taken the server version. It solves the problem with the ignored .js/ folders.

**Comment by vvakame** [comment]
@ToastHawaii thanks mate!

**Pull request merged**
