### PR TITLE
Update d3-hierarchy 1.1/d3 4.5

### PR DESCRIPTION
**Pull request by tomwanzek**
* [d3-hierarchy] Add `count()` method to hierarchy node interfaces
* [d3-hierarchy] Update header to reflect v1.1 minor version
* [d3] Bump minor version to 4.5

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-hierarchy/releases>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
Related to issue #14326.
This PR reflects the purely functional change/minor release update.

JSDoc/`strictNullChecks` will be a separate PR.

**Comment by tomwanzek** [comment]
fyi @gustavderdrache

**Comment by gustavderdrache** [comment]
:+1:

**Comment by tomwanzek** [comment]
@andy-ma I noticed that the `package.json` for **d3** was removed. It was used to pin the minor versions of **d3** to the minor versions of the re-exported bundled **d3** modules.

My apologies, if I missed some recent how-to changes, but if someone uses d3 v4.4 for their project, downloading  a corresponding 4.4.x definition from @types/d3 would under the hood actually install the latest module definitions (i.e. as of this PR v4.5)

Your thoughts would be most appreciated. T

**Comment by tomwanzek** [comment]
Sorry, minor typo the previous comment was meant  for @andy-ms.

**Comment by tomwanzek** [comment]
Another question, what happened to the DefinitelyTyped bot automatic PR notification to definition authors?

**Comment by tomwanzek** [comment]
Could this be merged please? Subject to my question regarding `package.json` above? Thx in advance, T

**Pull request merged**
