### PR TITLE
Transclude On A Component Should Be An Object Like On Directive

### PR DESCRIPTION
**Pull request by mickdelaney**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

From The Source:

Here it just passes through the option.transclude 

https://github.com/angular/angular.js/blob/0780666e41938e28984a4496231008ae6066c41e/src/ng/compile.js#L859

For example: 

transclude: {
            'header': '?panelHeader',
            'content': 'panelContent'
        }

### CODE REVIEW

**Comment by vvakame** [comment]
current definition can consume your example.
http://goo.gl/7tMDH2

**Comment by mhegazy** [comment]
it is not clear what is the issue this PR is solving, moreover, it is limiting type safety by using `any` in places where more specific types were used.

**Comment by mickdelaney** [comment]
the existing transclude was a string only, my PR was 'solving' the fact the existing type definition was **wrong**, "any" was a viable alternative, albeit not as type safe as @vvakame's solution. i certainly agree that @vvakame's solution is far better but i'd appreciate a less condescending tone from @mhegazy, i was trying to contribute after all.

**Comment by mhegazy** [comment]
Sorry if i did come out as condescending. no intentions for that on my side. I just started looking at the PR backlog and have over 400 left to go through. thanks for your contributions, and please feel free to put out another PR with @vvakame's suggession.

**Comment by mickdelaney** [comment]
thats ok. the feedback was valid :-)

**Pull request closed without merging**
