### PR TITLE
[helmet] Fix spelling of a option in hsts and hpkp

### PR DESCRIPTION
**Pull request by chdanielmueller**
Change for the option "includeSubdomains":
The "D" of "Domains" should be written in uppercase according to the docs:
https://helmetjs.github.io/docs/hsts/
https://www.npmjs.com/package/hpkp

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://helmetjs.github.io/docs/hsts/
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by EvanHahn — APPROVED** [review]
I'm planning to deprecate the lowercase-D option, but both modules support both capitalizations (see [hpkp](https://github.com/helmetjs/hpkp/blob/f0d0b87df82b53eb67452ab0bfb0b7c24bd88667/index.js#L44) and [hsts](https://github.com/helmetjs/hsts/blob/643c5e6539a29f4712e5f5ea9f8b9a678e78b1b0/index.js#L7)).

I could see leaving `includeSubdomains` (lowercase `d`) to ease existing code, but I don't feel strongly.

**Comment by EvanHahn** [comment]
We should wait to merge until my comment is acknowledged, even if it's not addressed.

**Comment by chdanielmueller** [comment]
@EvanHahn I tried implementing a "deprecated" option.
But it seems like this is just a feature which is not implemented.
Are you aware of such a feature?

Otherwise it comes down to your decision how you would like to handle this.
Either support both or just one of the syntaxes.

**Comment by EvanHahn** [comment]
IMO, we should allow both for a time, then remove the old one when I release Helmet 4.0 (I'm shooting for an April release but we'll see). I don't think the deprecation is worth making things more difficult for users in this case.

**Comment by chdanielmueller** [comment]
@EvanHahn I include the old version now.

I added them together with a descriptive deprecation comment.
Those brave enough to open the definition will see it. :wink:

**Review by EvanHahn — APPROVED** [review]
Might be worth adding a test for `includeSubdomains` (lowercase `d`), but this looks good to me.

**Comment by BlueHatbRit** [comment]
This is a bit of a drive by comment, but I think it might be worth raising. @EvanHahn since you're actively reviewing these types and you're the core maintainer of helmet, would it worth us rolling the types into the helmet module itself so we don't have to deal with the DT review process?

I understand if you'd rather not bother with them and would prefer to keep them at arms length so as not to delay your helmet release cycles, but I just thought I'd voice it as it might reduce the review and release effort of keeping these types up to date.

I don't by any means want to push more work onto you and totally get any reasons for not merging them into helmet but I didn't know if you'd considered it at all. I'd be happy to help out with maintaing the types if that'll help 😄

**Comment by EvanHahn** [comment]
This is definitely something I've considered. Would you mind opening an issue on [github.com/helmetjs/helmet/issues](https://github.com/helmetjs/helmet/issues) so we can discuss this further?

**Comment by chdanielmueller** [comment]
> Might be worth adding a test for `includeSubdomains` (lowercase `d`), but this looks good to me.

I did add two tests

**Comment by EvanHahn** [comment]
My bad—then this is great!

**Pull request merged**
