### PR TITLE
Apply definition tester 0.2.0

### PR DESCRIPTION
**Pull request by vvakame**
https://github.com/DefinitelyTyped/definition-tester/pull/10
If you want to update testing tsc version. rewrite package.json (only!).

### CODE REVIEW

**Comment by vvakame** [comment]
@borisyankov @Diullei @basarat @Bartvds @johnnyreilly

**Comment by johnnyreilly** [comment]
Nice @vvakame!

**Comment by basarat** [comment]
:heart:

**Comment by Bartvds** [comment]
:sparkles: :+1: :sparkles:

**Pull request merged**
