### PR TITLE
update(perf_hooks): Improve types for the measure method

### LINKED ISSUE #53239: Performance.measure() endMark optional
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/node@12.20.13` for the project I'm working on.

Performance.measure has an optional endMark parameter that in this case was required

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/node/perf_hooks.d.ts b/node_modules/@types/node/perf_hooks.d.ts
index cf88de7..ed6f785 100755
--- a/node_modules/@types/node/perf_hooks.d.ts
+++ b/node_modules/@types/node/perf_hooks.d.ts
@@ -112,7 +112,7 @@ declare module 'perf_hooks' {
          * @param startMark
          * @param endMark
          */
-        measure(name: string, startMark: string, endMark: string): void;
+        measure(name: string, startMark: string, endMark?: string): void;
 
         /**
          * An instance of the PerformanceNodeTiming class that provides performance metrics for specific Node.js operational milestones.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #53239

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_measure_name_startmarkoroptions_endmark>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by SimonSchick** [comment]
This cannot be merged yet as this is part of node v16, current typings are at v15.6.
Also the #closes tag appears to be wrong since it refers to a PR, not an issue.

**Comment by martin-badin** [comment]
@SimonSchick Thanks for your review. You are right. I removed the options. Could you please review it again?

**Review by SimonSchick — APPROVED** [review]

**Review by galkin — APPROVED** [review]
LGFM

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
