### PR TITLE
[@types/aws-lambda] make messageAttributes partial to indicate any key name might not exist

### PR DESCRIPTION
**Pull request by MagnusHJensen**
Please fill in this template.

This change introduces the Partial type to the messageAttributes based on the simple reason, any name you want might not exist, so this forces you as a developer to verify it exists, by either wrapping it in an if statement or using the nullish operator `?`, to access any sub-types.

_The current implementation can lead to flaws in a code base, meaning you might use a name, that does not exist in the SQS message, and therefore start reading on an undefined object, making the application crash_

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-params
- ^^ The docs does not really tell this, but since the type is defined as any key can result in the proper typed object, which is not true and can lead to TypeErrors of trying to read something on undefined, if you use a key that does not exist.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`. 
- ^^ _It does not bring it up to date, but rather fix a mistake, so not sure if the major bump is the correct play here, but it does introduce breaking changes_

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/aws-lambda/test/sqs-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 23e208ee52d55ee3249c90ba10f1a084c4c2f3b7
</p>

**Review by simonbuchan — CHANGES_REQUESTED** [review]
Not a fan, sorry? The convention across the library is that these are not marked partial, and you can use the compiler option `noUncheckedIndexedAccess` if you really want that.

Also, we haven't really bumped the major version unless there's been a runtime (eg handler) change that's enough to be likely to break many users (which is why it's currently the lambda runtime version that added async handlers). That's doesn't really work anymore now that they don't change the runtime interface much, but this isn't the one to bump the major version for. 

(I've been looking considering how to break this package up to help avoid versioning issues like this, but that's a much bigger, more disruptive issue)

**Review by darbio — CHANGES_REQUESTED** [review]
Thanks, but I don't see the point in this change?

What material difference does the addition of partial make here?

**Comment by MagnusHJensen** [comment]
That TS Rule, seems to solve the issue, thank you for that, and thank you guys for the explanations.

**Pull request closed without merging**
