### PR TITLE
improve(json-schema): Allow user defined keywords

### PR DESCRIPTION
**Pull request by kalvenschraut**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

JSON schema allows for user defined [keywords](https://ajv.js.org/guide/user-keywords.html), as the way the current types are setup I don't know of any other way to define the additional keywords that are defined. I tried extending the JSONSchema interface but I ran into the problem that the json schema 7 interface basically refers to itself via JSON7SchemaDefinition meaning all references to itself wont have my custom keywords as intended. Adding a generic that extends JSON7SchemaDefinition and defaults to JSON7SchemaDefinition allows me to instead set to my own custom JSONSchema interface which includes my custom keywords. 

In user land this change shouldn't affect any types explicitly since in the end it should result in the same typings as before. I did notice a test failure in conventional-changelog-config-spec  so It seems anything doing the explicit typings check is going fail since it seems it is `JSONSchema7<JSONSchema7Definition>` now instead of `JSONSchema7`.

### CODE REVIEW

**Comment by rbuckton** [comment]
I'm not clear on why the generic is necessary. Is the issue that you need a way to extend `JSONSchema7Definition`, or that augmenting `JSONSchema7` is not working?

**Comment by rbuckton** [comment]
The following augmentation should work just fine:
```ts
// declare a `myKeyword` user defined keyword
declare module "json-schema" {
  interface JSONSchema7 {
    myKeyword?: boolean; 
  }
}
```

**Comment by kalvenschraut** [comment]
@rbuckton  I guess I have not run across augmenting a type like your example. I am finishing up a decently large project that was converted to typescript and this is  really the first time using TS. I wanted to try go through and fix some of the type errors that were ignored on the first pass.

I was attempting to extend the `JSONSchema7` interface, and I needed to specify that the `JSONSchema7Definition`  should refer to my extended class instead of `JSONSchema7`.

```TS
interface JSONSchema extends JSONSchema7<JSONSchema> {
  myKeyword?: boolean
}
```

The above example was what I got to work if I added the generic to JSONSchema7, but as you pointed out I can augment the type and get the same result. This PR can be closed since their exists a solution to my problem I didn't know about.

**Comment by rbuckton** [comment]
Glad I could help. Even though this PR wasn't merged, thanks for contributing!

**Pull request closed without merging**
