### PR TITLE
Updating Q to have optional resolves

### PR DESCRIPTION
**Pull request by mboudreau**
q.resolve() function doesn't need to have a mandatory value and often times is used just to denote a "good" state without data.  Without this optional value, many non-data resolves would have to either inject `undefined` or `null`.  While I was at it, I've updated the tests and added a tslint file.

Please fill in this template.

- [✓ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [✓] Test the change in your own code. (Compile and run.)
- [✓] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [✓] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [✓] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [✓] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/kriskowal/q/blob/master/q.js#L1631>>
- [No versions to be found?] Increase the version number in the header if appropriate.
- [✓] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by weswigham** [comment]
@bnemetchek @AndrewGaspar @johnnyreilly do you have any feedback on this PR?

**Comment by johnnyreilly** [comment]
No - I'm not using Q anymore I'm afraid. If the tests pass then merge I say!

**Comment by mboudreau** [comment]
@weswigham Any updates on this?

**Comment by weswigham** [comment]
@mboudreau I was waiting a few extra days to see if any other authors with more of an opinion wanted to weigh in, per our "YSYL" label protocol, since @johnnyreilly was without real opinion. I'll be merging it now, however, as there have been no negative comments over the week.

**Comment by mboudreau** [comment]
Thanks :)

**Pull request merged**
