### PR TITLE
Fix `sass-loader` Callback arguments (missing `content`)

### PR DESCRIPTION
**Pull request by CPatchane**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#additionaldata
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by kashav — APPROVED** [review]
Seems fine to me, maybe include a new test in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5292154014ed88af4a325199ad5b6077950f8d2b/types/sass-loader/sass-loader-tests.ts that has `sassOptions` as a `type Callback`?

**Comment by CPatchane** [comment]
@kashav You mean link this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70037/commits/dd6531853839a6238ab8f49390cadc83283d0e87

**Review by kashav — APPROVED** [review]
yeah, awesome

**Review by kashav — APPROVED** [review]
Looks good to me

**Pull request merged**
