### PR TITLE
[react-day-picker] add DayModifiers for onDay* callbacks

### PR DESCRIPTION
**Pull request by giladgray**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://react-day-picker.js.org/Modifiers.html#accessing-modifiers-from-event-handlers
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.~~

### CODE REVIEW

**Comment by giladgray** [comment]
the current typings are incorrect: the `modifiers` param in an `onDay*` callback has the same keys as the `modifiers` prop, but the values are booleans indicating whether _this day_ (the first param of callback) has those modifiers.

**Comment by gpbl** [comment]
Definitions are coming in v5.3.0 once https://github.com/gpbl/react-day-picker/pull/303 is closed. What should we do with DefinitelyTyped once they are published? Should the definition file be removed from this repo?

**Comment by JKillian** [comment]
Yep, it'll get removed from here! See [these instructions](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

**Comment by giladgray** [comment]
can we still merge this as a faster workaround until https://github.com/gpbl/react-day-picker/pull/303 merges?

**Comment by giladgray** [comment]
@gpbl @JKillian ping on maybe approving/merging/shipping this to unblock my feature work in https://github.com/palantir/blueprint/issues/1014?

**Comment by gpbl** [comment]
@giladgray i'm traveling and I'll do my job tomorrow 😄 i'm still not sure about the definitino file in https://github.com/gpbl/react-day-picker/pull/303 - is it correct?

**Comment by giladgray** [comment]
@gpbl yeah the .d.ts file there looks correct--you copied it from this PR if i'm not mistaken?

**Review by adidahiya — CHANGES_REQUESTED** [review]
these changes are no longer required. react-day-picker v5.3.0 ships with its own types

**Comment by mhegazy** [comment]
based on @adidahiya comment, this is not needed any longer. closing.

Please add the package to notNeededPackage.json, see https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Pull request closed without merging**
