### PR TITLE
[next-auth] Add main server export overload

### PR DESCRIPTION
**Pull request by 0ubbe**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code that provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header

_____________________________________

### Summary 💭

This PR is to address https://github.com/nextauthjs/next-auth/issues/1417 and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51527.

Here's the [specific bit of source code](https://github.com/nextauthjs/next-auth/blob/main/src/server/index.js#L250-L253) that it tries to reflect on the types.

### Other 🪴

I made the `initOptions` required on both overloads for the main `NextAuth` type. This reflects better [the current behaviour of the library](https://next-auth.js.org/configuration/options) where it expects some options to always at least be supplied.

### CODE REVIEW

**Review by JuanM04 — APPROVED** [review]
These types exists in the main repo: there are multiple `index.d.ts` there.
I'll approve this so this error gets fixed, but I think it's time to migrate

**Comment by lluia** [comment]
@JuanM04 I saw some types in the repo but not sure they map or cover everything 📐 ; we could re-open the conversation with @balazsorban44 and @iaincollins about whether we should move them to the repo 🪴 . 

So far, I've not found major issues maintaining them here, plus we benefit from the validation tooling provided at **DefinitivelyTyped**. I think if we decide to keep them still here; then we should probably find a way to better sync with new version releases 🎟

**Comment by JuanM04** [comment]
> we should probably find a way to better sync with new version releases

Mainly that, we would have more freedom if we had these types in the main repo. Plus, those who want to use Typescript won't need to install `@types/next-auth`. I don't care that much what we end up doing, but if we migrate, I would be glad to help :smile:

**Review by JuanM04 — APPROVED** [review]

**Comment by balazsorban44** [comment]
See my comment. 

https://github.com/nextauthjs/next-auth/issues/1417#issuecomment-791682592

feel free to contact me anywhere to discuss my ideas about TS support!

**Review by jgeurts — APPROVED** [review]

**Review by JuanM04 — APPROVED** [review]

**Comment by lluia** [comment]
Ready to merge

**Pull request merged**
