### PR TITLE
Updated oauth2orize typings to include grant and decision

### PR DESCRIPTION
**Pull request by stevehipwell**
Please fill in this template.

- [x ] Make your PR against the `master` branch.
- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `tsc` without errors.
- [x ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:
- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jaredhanson/oauth2orize

- I've read the source code for this module to improve the typings.
- I have also used the typings myself for a number of months.
- I've improved the lint result but it's not passing.

### CODE REVIEW

**Comment by sandersn** [comment]
@heycalmdown can you take a look in the next few days? Otherwise I'll give a compiler-eye-view review on Monday.

**Comment by andy-ms** [comment]
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

**Comment by stevehipwell** [comment]
@andy-ms I've rebased.

**Comment by sandersn** [comment]
The change itself looks fine structurally. I've never used oauth2orize so I can't review the semantics. However, it's been a few days, so I'll merge when the rebase problem is fixed.

**Pull request merged**
