### PR TITLE
Add definitions for imagesLoaded

### PR DESCRIPTION
**Pull request by charabaruk**
I've had this sitting around in a private repo for a while but it'd be better off available through DT.

### CODE REVIEW

**Comment by coldacid** [comment]
I can't see the build results, could someone who can see them copy them into the PR so I can figure out what went wrong? Running the test suite locally raised no problems.

**Comment by vvakame** [comment]
*imagesloaded/imagesloaded.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/imagesloaded
  * http://bower.io/search/?q=imagesloaded
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (imagesloaded/imagesloaded-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@coldacid I was test locally too. I think your PR is valid. It merged.
We triedto fix travis ci... :crying_cat_face:

**Comment by coldacid** [comment]
Thanks!

**Pull request merged**
