### PR TITLE
additional markdown-it interfaces

### PR DESCRIPTION
**Pull request by rapropos**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [?] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [?] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/rapropos/typed-markdown-it>>
These were the typings used by the 'typings' tool. I tried to merge in some missing pieces.
- [? ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by rapropos** [comment]
I can't figure out how to give `Token` a constructor that is visible from outside. It has one that looks like this:

`new(type: string, tag: string, nesting: number)`

Not sure if I'm importing it wrong or what.

**Comment by plantain-00** [comment]
👍 
The `parse` and `parserInline` is marked as `internal`, but the document says "You should not call this method directly, until you write custom renderer (for example, to produce AST)."(https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L516), so they may be used when writing custom renderer.

@rapropos Generally use `interface Token` and `interface TokenStatic` or just `class Token` to define constructor, just like `MarkdownIt` and `MarkdownItStatic`.

**Comment by rapropos** [comment]
Thanks for taking the time to review and comment. I also just added an overload to the `new()` function that allows both a type and options argument (current state only allows one or the other). I need access to the parser for some applications where I can't render straight to HTML, but instead need an array of elements.

**Comment by plantain-00** [comment]
:+1

**Comment by rapropos** [comment]
Is there something else I can do to try to get this merged?

**Comment by plantain-00** [comment]
I'm not a member, so cannot merge this.
you can try to @ some active members to make this merged.

**Comment by rapropos** [comment]
Hmm, this is my first experience trying to add anything to DT, so I have absolutely no idea who to contact.

**Comment by plantain-00** [comment]
I checked some recent merged pull requests, @basarat and @andy-ms seems active.
Don't blame them, they seem really busy recently.

**Comment by rapropos** [comment]
Cool, thank you both for your assistance.

**Comment by rapropos** [comment]
Do I need to take some additional action in order to get this reflected in the `@types/markdown-it` npm package?

**Comment by plantain-00** [comment]
Usually not, it's automatic.
Maybe it's a bug of https://github.com/Microsoft/types-publisher

**Comment by andy-ms** [comment]
We don't publish directly from `types-2.0`. But we'll do a merge from `types-2.0` to `master` (which is published) soon. (See #13233)

**Pull request merged**
