### PR TITLE
Add missing types to expect

### PR DESCRIPTION
**Pull request by johanblumenberg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The added types are available in expect, but are missing in these type definitions. See jest docs on expect:
https://facebook.github.io/jest/docs/en/expect.html

### CODE REVIEW

**Comment by vitosamson** [comment]
The changes in this PR apply to `expect@^21`, but the version number was not bumped.

Therefore it breaks both expect v1 (because the new methods are not available) and v21+ because methods from v1 (such as createSpy) were removed.

**Comment by andy-ms** [comment]
@vitosamson Pull requests accepted.

**Comment by vitosamson** [comment]
I'll try to put one together soon. How would I go about splitting the two versions? Revert these changes in one PR, then in another PR put these changes back with the bumped version?

**Comment by andy-ms** [comment]
You could create a `types/expect/v1` directory and copy everything to there, then fix up that to contain just what was in v1; then update what's in `types/expect` to the latest version.

**Pull request merged**
