### PR TITLE
node/fs: Allow Object w/ toString() to match docs, w/tests

### PR DESCRIPTION
**Pull request by wbt**
This PR attempts to address https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58714, allowing developers to use the affected fs.write() functions as documented. 

The biggest weakness here is that TypeScript does not seem to have a way of checking for non-inheritance similar to Javascript's `hasOwnProperty()` (or the draft replacement, `hasOwn()`) and the accepted type definition could be narrowed if it did (e.g. if I'm just not aware of a way to do that).  However, the effect is similar to Typescript's lack of distinction between `int` and `float`, where use of the broader `number` will occasionally result in type-related runtime errors if an `int` is actually required.

Allowing developers to use Node APIs as documented presents a smoother transition path into TypeScript. 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://nodejs.org/api/fs.html#fswritefd-string-position-encoding-callback](https://nodejs.org/api/fs.html#fswritefd-string-position-encoding-callback)

### CODE REVIEW

**Comment by wbt** [comment]
The CI failure is unrelated and discussed at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58802

**Review by SimonSchick — CHANGES_REQUESTED** [review]
I still don't think this is wise to do and will introduce more potential errors than benefits.

**Comment by wbt** [comment]
@SimonSchick chick Can you please explain *why* you don't think it's wise and under what conditions the TypeScript typings should match vs. diverge from the official Node docs?

**Comment by SimonSchick** [comment]
A very common error in JS land is passing an object (such as array) to a function that expects a string, some functions will prompty convert it to a string which is most likely undesired.

Anecdotal:
How many times have you seen random `[Object object]` floating around on websites and debug logs?

Further from some local testing it seems support for this 'feature' seems.. questionable:

```
> a = fs.openSync('test.txt', 'w')
24
> fs.writeSync(24, 'test')
4
> fs.writeSync(24, [])
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "buffer" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at __node_internal_ (node:internal/fs/utils:879:9)
    at Object.writeSync (node:fs:876:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
> fs.writeSync(24, {toString() { return 'a' }})
node[13949]: ../src/string_bytes.cc:319:static size_t node::StringBytes::Write(v8::Isolate *, char *, size_t, Local<v8::Value>, <SNIP CRASH LOG>
[1]    13949 abort      node
➜  ~ node -v
v16.13.2
```

Can you show me a working sample of this?

**Comment by wbt** [comment]
Here is an example, not completely minimal to avoid the response like 'the workaround is super trivial in this minimal example and must therefore be just as clear and always an option no matter how complex the codebase,' even though a pretty simple workaround still exists for this particular example. 
```js
const fs = require('fs');
const currentStockIDs = [1,2,5,7]; //actually pulled from some async call
const writeInventoryReport = async function() {
  try {
    const fd = fs.openSync('inventoryReport.txt', 'w');
    await addToFile(fd, 'The following titles remain in stock:\r\n');
    for(let id of currentStockIDs) {
      await addToFile(fd, getObjectFromCatalog(id));
      await addToFile(fd, '\r\n');
    }
    await closeFile(fd);
  } catch (err) {
    console.error('Error writing inventory report: ', err);
  }
}
const getObjectFromCatalog = function(itemID) { //actually more complex, but returns Object with toString().
  if(itemID === 1) {
    return {toString: function() {return 'The TypeScript Handbook, 2nd Ed.'}};
  } else if (itemID === 2) {
    return {toString: function() {return 'The Pragmatic Programmer'}};
  } else if (itemID === 5) {
    return {toString: function() {return 'TypeScript Quickly'}};
  } else if (itemID === 7) {
    return {toString: function() {return 'Effective TypeScript: 62 Specific Ways to Improve Your TypeScript'}};
  }
}
const addToFile = function(fd, whatToWrite) {
  return new Promise(function(resolve, reject) {
    fs.write(fd, whatToWrite, function(err) {
      if(err) {
        reject(err);
      } else {
        resolve();
      }
    })
  });
}
const closeFile = function(fd) {
  return new Promise(function(resolve, reject) {
    fs.close(fd, function(err) {
      if(err) {
        reject(err);
      } else {
        resolve();
      }
    })
  });
}
writeInventoryReport();
```
In the process of adapting `addToFile` (which might be in a separate file from where it is called), the person doing the adaptation and typing `whatToWrite` might be inclined to [consult the official documentation](https://nodejs.org/api/fs.html#fswritefd-string-position-encoding-callback) for `write`, find that param is of type [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) `|` [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object), type their parameter that way, and find out this isn't an option in TypeScript, with no good way of predicting when the types will match the docs and when they'll mismatch.  That and other examples of having to change correct code, sometimes extensively, instead of just adding types, turns folks off from doing the adaptation. 

My vote would be to trust the Node developers to make their decisions about whether this coercion-to-string feature is desirable or not, and make types that match that decision.  In 14.0.0 they dropped this perhaps for the reasons you call out, but then it was restored again in 14.12.0, after a fair amount of discussion and spilling of digital ink.  Why not just let the Node development process lead?

**Comment by SimonSchick** [comment]
Just testing on latest node v14:

```
➜  ~ node
Welcome to Node.js v14.19.0.
Type ".help" for more information.
> a = fs.openSync('test.txt', 'w')
24
> fs.write(a, {toString() { return 'test!'; }}, (err) => { console.log(err); })
undefined
> null
> fs.writeSync(a, {toString() { 'test!'; } });
node[21813]: ../src/string_bytes.cc:319:static size_t node::StringBytes::Write(v8::Isolate *, char *, size_t, Local<v8::Value>, enum encoding, int *): Assertion `val->IsString() == true' failed.
 1: 0x1013221f5 node::Abort() (.cold.1) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 2: 0x1000b6399 node::Abort() [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 3: 0x1000b6201 node::Assert(node::AssertionInfo const&) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 4: 0x100177d16 node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 5: 0x1000c8523 node::fs::WriteString(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 6: 0x100272038 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 7: 0x1002715cc v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 8: 0x100270d32 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
 9: 0x100a8e8b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/simonschick/.nvm/versions/node/v14.19.0/bin/node]
[1]    21813 abort      node
➜  ~
```

It seems it works with `fs.write` but causes a hard crash with `fs.writeSync` (which is pretty bad in itself and probably warrants raising an issue with them).

We should extremely hesistant to support an API that is partially broken and is subject to potential change in the future (since there clearly was an attempt to remove it).

Also it should be noted that the node types (and TS in general) are often much stricter in API definitions than _needed_ in order to be compliant with the actual API, especially when it comes to implicit string conversions.

@peterblazejewicz I'd appreciate your input here.

**Comment by peterblazejewicz** [comment]
I have bad experience with Node types changes myself. I would not do a change, no matter how nice it looks, which is not recognized as fix of a known problem (wrong type used, clear use case) or a missing feature (missing async version of a module, Node own namespace imports support added to new module).

**Comment by LinusU** [comment]
I personally think that introducing this will cause errors to go unnoticed.

e.g. with the change as proposed, we can pass numbers in, as we can pass any object with `toString` in the prototype chain. The Node.js docs is very clear that this is _not_ allowed:

Screenshot 2022-02-18 at 12 39 50

```typescript
interface objectWithToString extends Object {
  toString(): string;
}

type StringLike = string | objectWithToString;

declare function write(fd: number, string: StringLike): void

// Not correct, but allowed:
write(1, 13)

class Foo {
  toString () { return 'Hello, World!' }
}

// Not correct, but allowed:
write(1, new Foo())
```

**Comment by wbt** [comment]
@LinusU I agree that it would be much better if Typescript had some equivalent of `hasOwnProperty` which ignores inherited components, allowing this check to be stricter.  

However, there are plenty of examples of interfaces that require integers, especially when interacting with databases or counters, but Typescript doesn't allow those to be distinguished: typing errors can still happen with Typescript because of not wanting to break things but stay within the current limits of how detailed you can express types in TypeScript.  Sure, JavaScript doesn't enforce distinction between floats & ints and only uses floats which can cause problems, but JavaScript doesn't distinguish between variable types in a whole lot of ways which is what motivates use of TypeScript in the first place.  This change would be consistent with that and allow working code consistent with the Node documentation to continue working, not requiring as much rewriting of working code increasing the costs of transition to TypeScript.  

If we do want to require digging in to discover differences between documented APIs and those allowed by this types library, and rewriting/changing working code as part of the costs of transition to TypeScript, we should clearly state the set of conditions under which that should be required to help add predictability to the costs of that transition.

**Comment by LinusU** [comment]
@wbt I agree that TypeScript cannot always cover JavaScript APIs to 100%, as in this case. However, I don't think it's apparent that allowing any object with `toString` to be passed is the correct solution here.

There is two solutions here:
1. Only accepting `string`s (current behaviour)
2. Also accept object with `toString` functions, even if they are inherited

Both of these solutions are not 100% correct. So I think that we need to chose the one which we think will cause the least amount of confusion and unexpected runtime errors.

To me, that is solution 1, what we currently have.

I think it's a better approach since it doesn't allow to write code that will throw runtime type errors from Node, with the only drawback being that you need to wrap your non-string values in `String(...)` when passing them to `write`.

In fact, I think it is a good practice to wrap values in `String(...)` before passing them to `write`, to make the conversion explicit. I also _feel_ like the fact that it accepts objects _seems_ like something that comes from how it by chance happened earlier, and they couldn't change the api to not break it. I base this on the fact that they have added documentation that it only works when `toString` is not an inherited property, which seems like they would have to add extra code to check if it is...

**Comment by wbt** [comment]
@typescript-bot
> it still has problems that prevent it from being merged

The "problems" are ones in the maintainer community that I cannot address, not even by satisfying the wild goose chases that I'm sent on which won't actually make any difference even if completed successfully.  It's a repo with a very high cost for even a low probability of making contributions.  There's no willingness to clarify when the types in this repo should match vs. diverge from official published documentations and technical decisions of the maintainers of the typed libraries, just an assurance that previously valid JavaScript will have to be rewritten (beyond the addition of types) to be able to convert to TypeScript using the typing libraries here. While those facts are rather frustrating, I'm not sure what actionability your @ flag was supposed to have beyond prompting them to be more clearly stated.

**Comment by wbt** [comment]
@typescript-bot the status remains as described in my last post.

**Comment by wbt** [comment]
The "problems" are wild goose chases and perceptions among this team that they think they know better than the Node developers.

**Comment by SimonSchick** [comment]
Maybe we should ask the node devs cre and see if they'd re-introduce this feature if it wasn't there yet and what they think of the usage :)

**Comment by wbt** [comment]
See April 29 comment above.

**Comment by LinusU** [comment]
> [...] not what folks in DefinitelyTyped think _should_ be there.

I thought that we had established that neither the current, nor this new proposed types, are 100% correct? Therefor I don't really think that we are changing the types to what we'd like or think should be there, but rather doing the best of the situation...

My personal position is still that this will introduce a way to create subtle bugs, without providing a benefit large enough to outweigh that...

**Comment by wbt** [comment]
The limitation in the proposed types is a limit of TypeScript itself, which prevents specifying the difference between an object that has its own property vs. inherits it.  Thus, the only scope option which allows perfectly valid JavaScript to not have to be rewritten when shifting to a TypeScript context is to allow what Node allows, even if folks in this discussion think Node shouldn't allow that.  The place for the discussion about whether non-String objects that can be coerced to strings should be permissible as a parameter type is over in Node.  Instead of just saying something like "we think they got it wrong and won't allow that broader parameter type in the supporting types package," we should be following their lead and describing types that allow what Node leadership decided should be allowed.

**Comment by LinusU** [comment]
@mcollina you are both on the Node.js TSC and now a maintainer of the types, do you have anything to add to this discussion?

-----

I did some more testing on this in the playground. @wbt am I missing something, or is it correct that this would start accepting all of the values below, which is actually not allowed at runtime?

```ts
interface objectWithToString extends Object {
    toString(): string
}

type StringLike = string | objectWithToString

declare function write (string: StringLike): void

write({})
write([])
write(1)
write(Symbol('test'))
```

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPYCMBWEFgOrBgAWAKqgMphSgDmyEAHpCACYDOyA8ljmMgN4AoZCORgKVWgAoAlAC5kbSSBqCAvoMFgAngAcUlaioAywANYoAvIuV0APmh64CxModqaWOADZwoKGABXEFxgVBBkAHdqSGQpJSMaBXcTcwh5ZAA3VGAWTWjCCCl+NRlBAsgpAG0AXTKKooBGepii8m0AW3RUbykAckglPpkyoA

**Comment by mcollina** [comment]
I would not land this change. As you found out, we are deprecating this coercion.

**Pull request closed without merging**
