### PR TITLE
update @types/mocha version to match mocha@10

### PR DESCRIPTION
**Pull request by beenotung**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [mocha@10 release note](https://github.com/mochajs/mocha/releases/tag/v10.0.0)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Comment:

The release note of mocha@10 didn't mention any changes on the interfaces, so we only need to update the version to match mocha@10

### CODE REVIEW

**Comment by beenotung** [comment]
Original pushed commits was based on wrong commits.
I have rebase to master branch than cherry-pick the effective commit and pushed again.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mocha ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mocha@latest/))
was missing the following properties:
1. unloadFile
1. xdescribe
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d94709a99dfa5c417985861534334806e038cc8d
</p>

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by beenotung** [comment]
Ready to merge

**Comment by Jason3S** [comment]
@beenotung,

This seems to have broken things. I'm getting these errors:

```
node_modules/@types/mocha/index.d.ts(2650,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'.
node_modules/@types/mocha/index.d.ts(2668,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'afterEach' must be of type 'Lifecycle', but here has type 'HookFunction'.
node_modules/@types/mocha/index.d.ts(2684,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'Describe', but here has type 'SuiteFunction'.
node_modules/@types/mocha/index.d.ts(2705,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xdescribe' must be of type 'Describe', but here has type 'PendingSuiteFunction'.
node_modules/@types/mocha/index.d.ts(2719,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'it' must be of type 'It', but here has type 'TestFunction'.
node_modules/@types/mocha/index.d.ts(2733,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'It', but here has type 'TestFunction'.
node_modules/@types/mocha/index.d.ts(2740,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xit' must be of type 'It', but here has type 'PendingTestFunction'.
```

**Pull request merged**
