### PR TITLE
Fix fetch-mock with TypeScript version 2.2

### PR DESCRIPTION
**Pull request by tkrotoff**
- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

### CODE REVIEW

**Comment by tkrotoff** [comment]
Travis CI fails because it does not support TypeScript 2.2

**Comment by andy-ms** [comment]
#14818 will support TS2.2.

**Comment by merrywhether** [comment]
This is pretty straightforward. Seems fine after 2.2 support is ready.

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by tkrotoff** [comment]
@mhegazy please *read* the diff and the PR: waiting for TS 2.2 support

**Comment by mhegazy** [comment]
@andy-ms why is `// TypeScript Version: 2.2` not working?

**Comment by andy-ms** [comment]
#14818 isn't in yet.

**Comment by tkrotoff** [comment]
@mhegazy @andy-ms
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14818 is done now, this can be merged

**Pull request merged**
