### PR TITLE
aws-lambda | add types for client certificate information in APIGatewayEventIdentity

### PR DESCRIPTION
**Pull request by tulsidas**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-logging-variables.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by simonbuchan — COMMENTED** [review]
This looks pretty great, thanks!

As a check, have you validated what was actually received by logging the event? AWS's documentation has been pretty inaccurate in the past. In particular, I suspect the validity dates may be Unix timestamps.

**Comment by tulsidas** [comment]
@simonbuchan Yes, here is a sample event I logged from a lambda which is called from a mTLS API gateway endpoint:

```
      "clientCert": {
        "clientCertPem": "-----BEGIN CERTIFICATE-----\nMIIEHTCCAgUCAQEwDQYJKoZIhvc.....-----END CERTIFICATE-----\n",
        "serialNumber": "1",
        "issuerDN": "C=US,ST=Florida,L=Orlando,O=Test Org,CN=Root CA",
        "validity": {
          "notAfter": "May 31 19: 36: 31 2031 GMT",
          "notBefore": "Jun  2 19: 36: 31 2021 GMT"
        },
        "subjectDN": "C=AR,ST=Buenos Aires,O=Jengibre Inc.,CN=Andres Q"
      },
```

**Review by simonbuchan — APPROVED** [review]

**Comment by simonbuchan** [comment]
Awsome, thanks!

**Comment by tulsidas** [comment]
Ready to merge

**Pull request merged**
