### PR TITLE
@types/ws shift EventListenerOptions into correct spot

### PR DESCRIPTION
**Pull request by justinrush**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48994
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## webpack-plugin-serve ([<kbd>unpkg</kbd>](https://unpkg.com/browse/webpack-plugin-serve@latest/))
was missing the following properties:
1. defaults
## ws ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ws@latest/))
was missing the following properties:
1. once
1. EventEmitter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c35fbf272f2000a44ead7b26dab3f17b625a33c
</p>

**Comment by justinrush** [comment]
@elibarzilay what are the next steps to getting this reviewed?

**Comment by wojtkowiak** [comment]
@justinrush can you add a simple test for at least one event?

**Review by wojtkowiak — APPROVED** [review]

**Comment by justinrush** [comment]
Ready to merge

**Pull request merged**
