### PR TITLE
[q] Add Q.Promise.all, the member function

### PR DESCRIPTION
**Pull request by eric-wieser**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kriskowal/q/wiki/API-Reference#promiseall

### CODE REVIEW

**Comment by andy-ms** [comment]
The changes you're making are to `q/v0`. There is already a definition of `all` in `q/index.d.ts`, which is for version 1. Was `all` present in version 0 of this library?

**Comment by eric-wieser** [comment]
I wasn't aware this was editing v0 - this was rebased from a time before that existed. I imagine this is present in v0.x too though.

**Comment by eric-wieser** [comment]
Actually, V1 is missing these definitions too

**Comment by andy-ms** [comment]
Look for `export function all` in `types/q/index.d.ts`. We can still accept a PR to update v0 though.

**Comment by eric-wieser** [comment]
Perhaps I'm behind on typescript syntax, but there's both a method and a function, and I think V1 only defines the latter.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
