### PR TITLE
feat: 🎸 add reference typings to hapi

### PR DESCRIPTION
**Pull request by damusix**
Request `query`, `payload`, `headers`, `params` and `auth` are now typed. Added type implementation for `server.rules` and `route.options.rules`.

### CODE REVIEW

**Comment by damusix** [comment]
I dont know what hapi-pino has anything to do this these changes

```


Error in hapi-pino
Error: 
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.

Before you debug, first try running:

   npm install --prefix /home/vsts/work/1/s/types/pino-pretty

Then re-run. Full error logs are below.

```

**Comment by lenovouser** [comment]
@damusix it seems like `pino` ships its own typings now, so you can try adding `pino` to the `package.json` in the `hapi-pino` types, maybe that fixes it

**Comment by lenovouser** [comment]
If that doesn't fix it, you can give me push access to your fork, then I can try fixing it

**Comment by damusix** [comment]
> If that doesn't fix it, you can give me push access to your fork, then I can try fixing it

Added

**Comment by damusix** [comment]
> If that doesn't fix it, you can give me push access to your fork, then I can try fixing it

BTW I gave it a good 90 minutes and couldn't solve it. Is it necessary to solve this issue given it's irrelevant to Hapi itself?

**Comment by damusix** [comment]
I'm using the following repo to experiment with these typings @lenovouser 

This should help you note what changed https://github.com/southpointe/temp-hapi-types#things-to-take-note-of

**Comment by damusix** [comment]
@lenovouser

**Comment by lenovouser** [comment]
@damusix I am sorry, I got sick recently. I tried to give it a shot, but wasn't able to get it resolved :(

**Pull request closed without merging**
