### PR TITLE
Add MapControl and additional GeoJSON bits to react-leaflet.

### PR DESCRIPTION
**Pull request by danzel**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #15299 #15378
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

@estaub can you please test these changes

### CODE REVIEW

**Comment by estaub** [comment]
@danzel Sorry, the MapControl isn't right.  It's my fault - I updated the comment 12 hours ago that contained the change, rather than adding a new comment, so you missed it.  See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15378#issuecomment-289187954 - specifically the definition of `class MapControl`.  The paradigm for using this class is to extend it (see https://github.com/PaulLeCam/react-leaflet/issues/130), which needs the change to compile.

Again, apologies!

**Comment by danzel** [comment]
Thanks. Will add that as a test.
Will do this tomorrow

**Comment by danzel** [comment]
Fixed and added a test from the linked issue.
Not totally sure we should have the MapControlProps, since implementation of it is up to the component.
It is good practice though to allow specifying the position (I think), so have left it in.

Please test now :)

**Review by estaub — APPROVED** [review]
All good - thanks!

**Comment by danzel** [comment]
Build fixed too, should be good to go :+1:

**Pull request merged**
