### PR TITLE
[@type/conflux-web]

### PR DESCRIPTION
**Pull request by liuis**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by liuis** [comment]
Our project is, indeed, the fork the web3 projects, but there are a lot of difference, but in the types of content is the same.So the web3 type is our.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
These definitions cannot be added here since the package comes with its own types. Any changes needed to typings need to happen in the source repo instead.
https://unpkg.com/browse/conflux-web@0.1.20-alpha.0/package.json

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
These definitions cannot be added here since the package comes with its own types. Any changes needed to typings need to happen in the source repo instead.
https://unpkg.com/browse/conflux-web@0.1.20-alpha.0/package.json

**Comment by sheetalkamat** [comment]
Please also note that we require template to be filled and followed and this PR does not satisfy the fact that package has its own types.

**Review by liuis — COMMENTED** [review]
fixed

**Review by liuis — COMMENTED** [review]
I know at https://unpkg.com/browse/conflux-web@0.1.21-alpha.0/package.json have their own types, but we need @ the type/conflux - web do more work, type checking and so on, if I keep these, have what problem?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
If the package comes with typing we do not accept definitions here. If you need to update typings for the package like this, please update in the source repo instead.
Please read the template and guidelines.

**Pull request closed without merging**
