### PR TITLE
[redis] not needed as redis now ships types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

node-redis now ships its own types.

i wasn't sure if all the `package.json` i added are the right thing to do here, so let me know if i need to change it.

### CODE REVIEW

**Comment by 43081j** [comment]
FYI i can't run tests locally as dtslint errors on some rules across various packages. this feels like `npm i && npm run test-all` in `master` is somehow resulting in a different dtslint version than what the CI builds here have...

i've seen similar in the past. locally i got errors about having `undefined` in optional properties, but in CI i did not.

maybe this is because locally i ran `npm run test-all` and CI doesn't do that?

**Comment by peterblazejewicz** [comment]
> @sandersn the new redis types (shipped with the node-redis package) use private identifiers. whats the right thing to do here? should we update all the redis-dependent packages to be targeting ES2015+? or should we keep the redis types for packages which don't yet use node-redis 4.x?

4.0 is a breaking release with breaking api changes, are we supposed to ship v4.0 everywhere?
We usually submit whitelisting of last version of @types/redis (2.8), so packages here depends on known last version.
So we can remove everything, but with '@types/redis' whitelisted. We've done that for various DT packages when removed, due to wide usage in community. So there are options.
this will give owners of those other DT packages to update in future

**Comment by 43081j** [comment]
so do you mean we would add the types package as a dependency and into the dt-tools whitelist?

if so, yeah that'd be perfect. wasn't aware we had that option

i'm aware 4.0 is a breaking api change

**Comment by peterblazejewicz** [comment]
> if so, yeah that'd be perfect. wasn't aware we had that option
yes, say for pino (logger):
https://github.com/microsoft/DefinitelyTyped-tools/pull/344

**Comment by 43081j** [comment]
yep already done

microsoft/DefinitelyTyped-tools#367

updated, blocked until that merges

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## bull ([<kbd>unpkg</kbd>](https://unpkg.com/browse/bull@latest/))
was missing the following properties:
1. ErrorMessages
1. Job
## kue ([<kbd>unpkg</kbd>](https://unpkg.com/browse/kue@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'kue'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. version
1. redis
1. The declaration doesn't match the JavaScript module 'kue'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. version

<details>
<summary>as well as these 1 other properties...</summary>
<p>redis</p>
</details>

## simple-url-cache ([<kbd>unpkg</kbd>](https://unpkg.com/browse/simple-url-cache@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'simple-url-cache'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. pool
1. locks
1. helpers
1. StorageInstance

<details>
<summary>as well as these 1 other properties...</summary>
<p>RedisPool</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 86b42220a80e079661129bbf6a419c6813e1bbea
</p>

**Review by amcasey — APPROVED** [review]

**Comment by 43081j** [comment]
ready to merge

**Comment by peterblazejewicz** [comment]
cool!

**Pull request merged**
