### PR TITLE
Add rxjs "Observable" support 

### PR DESCRIPTION
**Pull request by polRk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by durad** [comment]
Change looks Ok, but build is failing so I can't approve it. @polRk Can you please fix the build issue?

**Comment by polRk** [comment]
> Change looks Ok, but build is failing so I can't approve it. @polRk Can you please fix the build issue?

I don't understand, why i have an error. 
Maybe import doesn't work ? 
`import {Observable} from "rxjs";`
Can u help me ?

**Comment by polRk** [comment]
It's not my error. It's bug in DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/util/util.js. How i can solved it ?

**Review by durad — APPROVED** [review]

**Comment by durad** [comment]
Looks like it was some infrastructure issue.

**Pull request merged**
