### PR TITLE
[@types/oracledb] Update Lob interface getData method and Connection interface execute method

### PR DESCRIPTION
**Pull request by sudarshan12s**
- execute method of Connection interface to accept object as first argument.
- getData method of LOB interface would take offset and amount as optional arguments. 

The above changes are available as part of node-oracledb6.4.0 [release](https://github.com/oracle/node-oracledb/issues/1650).

I see that the type definition for sql-template-tag are not found and hence could not test the execute change. However I have tested by manually installing this module .

```
const sqlTemplate = await import('sql-template-tag');
    const sql = sqlTemplate.default;
    const deptno = 2;
    const options = { maxRows: 1 };
    await connection.execute(sql`select * from emp where deptno = ${deptno} order by sal desc`);
    await connection.execute(sql`select * from emp where deptno = ${deptno} order by sal desc`, options);
```

Please correct me if I missed anything.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/oracledb/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 903320d48511d4134c56704f820a86954e60b3d6
</p>

**Review by Anonymous4078 — APPROVED** [review]

**Comment by dannyb648** [comment]
Hi @sudarshan - Given these changes are to support 6.4.0 I dont think these should be merged yet. Can you hold fire until 6.3.0 is out, as atm this will go into a 6.2.x which wouldnt be correct. Might be worth retracting the merge request for now as someone will merge and we will have to back it all out

**Comment by dannyb648** [comment]
@Anonymous4078 Can you stop approving PRs which are not ready - these changes are for 6.4.0 which isnt out yet and should not be merged in yet., its causing me so many problems. We've had to release several fix releases because of your last approval. Please stop.

**Review by danbeglin — CHANGES_REQUESTED** [review]
Move to Draft until 6.3.0 is out today

**Comment by sudarshan12s** [comment]
> Move to Draft until 6.3.0 is out today

Thanks @dannyb648, Yes I marked it as Draft.

**Comment by dannyb648** [comment]
@sudarshan12s I'm now working on the 6.4.0 types (missed they came out because work blocked slack and didnt tell us!) 

Im happy for this to be merged in, but you will need to change the version so we get a 6.4.0 release (not 3.3.2). Im going to push up some types this weekend and you can always piggy back off the back of them?

**Comment by Anonymous4078** [comment]
> @Anonymous4078 Can you stop approving PRs which are not ready - these changes are for 6.4.0 - this is the 6.2.x line and should not be merged in yet., its causing me so many problems. We've had to release several fix releases because of your last approval. Please stop.

Don't blame me because you are slow and incompetent. Thanks 👍

**Comment by sudarshan12s** [comment]
> @sudarshan12s I'm now working on the 6.4.0 types (missed they came out because work blocked slack and didnt tell us!)
> 
> Im happy for this to be merged in, but you will need to change the version so we get a 6.4.0 release (not 3.3.2). Im going to push up some types this weekend and you can always piggy back off the back of them?

Thanks Dan. I pushed 6.4.0 version in my PR. Let me know any more comments and if i can remove draft for now?

**Comment by dannyb648** [comment]
Hi @sudarshan12s, thanks - im just reviewing if we need anything else in 6.4.0 - conscious if we merge only these in people may get confused. Ill need 24 hours if thats ok fella

**Comment by dannyb648** [comment]
@sudarshan12s i went through and made all the changes - including this one, but i actually prefer your method. Im happy for you to add these changes to that branch / PR or im happy to copy this over?

**Comment by sudarshan12s** [comment]
> @sudarshan12s i went through and made all the changes - including this one, but i actually prefer your method. Im happy for you to add these changes to that branch / PR or im happy to copy this over?

either way is fine with me, You can suggest me ..

**Comment by dannyb648** [comment]
Hi @suharshan12s, I've added your changes to the PR thats gone in with your name on the commit - thank you so much for your help!

**Comment by sudarshan12s** [comment]
Closing this PR as it got submitted from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69327)

**Pull request closed without merging**
