### PR TITLE
Add in _.mapValues definitions for use in chains

### PR DESCRIPTION
**Pull request by akalman**

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to author(@bczengel). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by akalman** [comment]
If its possible to get an alternate reviewer, that would be ideal.  Historically pulls against this file seem to be held up a long time waiting for the author to respond.

**Comment by bczengel** [comment]
:+1: 
Sorry about my inactivity, I've been buried @ work.  I'll try to be more attentive to this project in the future.

@akalman: thanks for your contribution.

**Comment by vvakame** [comment]
@bczengel thanks!
@akalman thanks mate!

**Pull request merged**
