### PR TITLE
Combine internal/external React .d.ts files and prepare for TS JSX

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
This PR refactors the React definition files in preparation for TypeScript support for JSX (https://github.com/Microsoft/TypeScript/pull/3564)

Due to limitations in TypeScript, I had to combine the .d.ts files for the internal and external module definitions for React (in the same way as e.g. jQuery's .d.ts file). This should generally be a good thing since now there's not two copies of the same code that need to be kept in sync.

### CODE REVIEW

**Comment by vvakame** [comment]
@RyanCavanaugh thanks mate!

**Comment by vsiao** [comment]
@RyanCavanaugh can you explain what the limitations are that require internal and external module definitions to be combined? People have had trouble using the combined definitions in the past, which is why we decided to go with this approach.

**Comment by jbrantly** [comment]
+1 for explaining why the definitions need to be combined. IMO the combined definitions are problematic if you're using external modules. See Microsoft/TypeScript#2018

It is a pain point to maintain two separate codebases, but that seems like it is a limitation that should be addressed by TypeScript.

**Comment by jbrantly** [comment]
Actually I think I found the limitation. The issue seems to be that the definitions in react-jsx.d.ts need a reference to React, and they have no way to reference that if using the external module version of react.d.ts. For fun, I tried this:

```typescript
declare module JSX {
	import React = require('react');
```

Even though I get an error, it actually works, meaning I can do something like

```jsx
<a title={0} />;
```
and I get
```
app.tsx(18,4): error TS2322: Type 'number' is not assignable to type 'string'.
react-jsx.d.ts(10,25): error TS1147: Import declarations in a namespace cannot reference a module.
```

**Comment by RyanCavanaugh** [comment]
@jbrantly correct.

I don't like the side effects of this PR (cc @vsiao ). I'm going to rework this a bit and re-separate the definition files so that people can do an in-place upgrade of their .d.ts files and not have to separately bring in react-jsx.d.ts.

**Comment by jbrantly** [comment]
+1 on not having to separately bring in react-jsx.d.ts. Seems like if you bring in react.d.ts you'd also want the JSX support. Would be weird to have some scenario where you wouldn't want that.

**Comment by RyanCavanaugh** [comment]
Redone in #4846

**Comment by RyanCavanaugh** [comment]
@pspeter3 See https://github.com/borisyankov/DefinitelyTyped/pull/4713#issuecomment-118479781

**Pull request merged**
