### PR TITLE
types/convict: Improved PathImpl to stop at SchemaObj key

### PR DESCRIPTION
**Pull request by justin-is-a-builder**
Following improves the utility type of convict in order to stop the keys before SchemaObj. I would like to improve the types to only show me dotted keys that stop before the prototype function names for strings and arrays. Hopefully there is someone in the community that can help with that

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Sorry, can you explain/demonstrate in more detail what you’re trying to do with this change?

**Comment by justinasfour04** [comment]
@andrewbranch How would you like me to show you? Is a screenshot enough?

**Comment by andrewbranch** [comment]
Ok, so the context is I’ve never heard of this library but I still am tasked with deciding whether your change is good or not. You changed a complex type and didn’t change any tests, and I don’t have enough context to quite follow your brief description of what you’re trying to do. The best way you can demonstrate is to update the test cases to add some `// $ExpectError` on property accesses that you’re trying to get rid of.

**Comment by justinasfour04** [comment]
not sure how to do that, do you have any documentation I can follow to do it right?

**Comment by justinasfour04** [comment]
this is what I was trying to avoid 
image

**Comment by justinasfour04** [comment]
Can you explain to me why this type in implicit from the function
image

but this type from doing typeof
image

**Review by msuntharesan — APPROVED** [review]

**Pull request closed without merging**
