### PR TITLE
Addresses #5090 extending new NodeRequireFunction interface for specialized constructor signatures

### LINKED ISSUE #5090: Extend newly extendable node.require() for specialized overloading of Electron modules
Electron modules incorporated with node.require are currently of type any.  Nodejs's require just got its own explicit interface and can now provide the additional type information in a clean way.

(I have a PR for this which I'll attach directly)

### PR DESCRIPTION
**Pull request by ghost**
Resolves #5090 extending new NodeRequireFunction interface for specialized constructor signatures

### CODE REVIEW

**Comment by vvakame** [comment]
@jedmao could you review this PR?

**Comment by jedmao** [comment]
Looks good except for changing the indentation. Preserve tabs and squash your commits and I'll give it a thumbs up.

See https://github.com/borisyankov/DefinitelyTyped/blob/master/github-electron/.editorconfig and the discussion at https://github.com/borisyankov/DefinitelyTyped/issues/4211

Also, you can download an [EditorConfig](http://editorconfig.org/) plugin for a supported editor to take care of this for you automatically upon opening a file.

**Comment by Gitgiddy** [comment]
OK, I tabified and squashed.  I'm not sure I did it right (that was all new to me).

**Comment by jedmao** [comment]
Merge conflicts. You need to rebase on master. Also, you might want to use the word fixes, resolves or closes instead of "addresses" in your original comment to this PR, because it will automatically close the associated issue. See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Gitgiddy** [comment]
Can you please elaborate on how I rebase on master?  Thanks.  I made this branch just for this fix and I made no other changes since to my master.

**Comment by jedmao** [comment]
```
$ git checkout master
$ git pull upstream master
$ git checkout 5090
$ git rebase master
$ git merge-tool
$ git rebase --continue
$ git push origin 5090:5090 --force
```

**Comment by jedmao** [comment]
http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by Gitgiddy** [comment]
Better?

**Comment by jedmao** [comment]
That fixes the merge conflicts, but your commits are no longer squashed? When you're done, there should be only one commit left and you shouldn't have other GitHub users' commits in there. See http://davidwalsh.name/squash-commits-git

**Comment by Gitgiddy** [comment]
Ugh!  OK, originally I had made these changes in my own master and then branched just for this PR.  I figured it would get cleaned up eventually once merged.  Now I know.  I threw out the old commits and resquashed and I think everything is right now.

**Comment by jedmao** [comment]
@Gitgiddy I feel like I haven't used the merge command in years. I'm pretty much always rebasing my changes on top of master or some feature branch. Thanks for pushing through this! :+1: from me.

**Comment by jedmao** [comment]
@vvakame :+1:

**Comment by vvakame** [comment]
@jedmao thanks!
@Gitgiddy thanks mate!

**Pull request merged**
