### PR TITLE
Chart.js - missing tooltip axis option

### PR DESCRIPTION
**Pull request by FlorentP42**
This is a follow-up for this abandoned pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32202
Hopefully the code is acceptable and can be merged this time? I would like to use this feature in my current projet.

EDIT: Documentation reference (unclear) https://www.chartjs.org/docs/latest/general/interactions/modes.html#index
Source code reference https://github.com/chartjs/Chart.js/blob/f5437fe548e5ca4d9236f3724fae692c30913c84/src/core/core.interaction.js#L99

### CODE REVIEW

**Review by lekoaf — CHANGES_REQUESTED** [review]
Please find a reference for this in the documentation and link that. After that we can consider it.

And wasn't there a PR template to fill in?

**Comment by FlorentP42** [comment]
Sorry about the messy pull request, added references in the main message and used the change in the automated test.

**Comment by danmana** [comment]
I can confirm this is a valid change for a missing typedef.
In fact, I've been using a modified typedef similar to this for a while, just forgot to add it back here :)

**Review by danmana — APPROVED** [review]

**Comment by FlorentP42** [comment]
Ready to merge

**Pull request merged**
