### PR TITLE
feat: @types/acorn and @types/acorn-walk

### PR DESCRIPTION
**Pull request by TyrealHu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by TeamworkGuy2** [comment]
You can see on npm, [acorn](https://www.npmjs.com/package/acorn) and [acorn-walk](https://www.npmjs.com/package/acorn-walk) already have type definitions built-in. Why add these DefinitelyTyped definition files?

There's a section in the DefinitelyTyped [README](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) about this. Packages that come with type definitions should NOT have duplicate type definitions in this repository.

**Comment by TyrealHu** [comment]
You can see this [PR](https://github.com/acornjs/acorn/pull/1148). The author of acorn suggest me to create a shared types of acorn

**Comment by RyanCavanaugh** [comment]
This is a very odd situation; types do not normally come *back* into DT.

@marijnh is this PR what you were intending to happen?

**Comment by marijnh** [comment]
> @marijnh is this PR what you were intending to happen?

No, not at all, I think there was a miscommunication. What I suggested was for Acorn's own types to depend on @types/estree, so that *that* part of the types is shared between the projects that use this tree format. (If practical—which will have to be tried.)

**Comment by TyrealHu** [comment]
@marijnh Alright, I see your point. I will close this PR later.

**Pull request closed without merging**
