### PR TITLE
[clean-css] move semicolonAfterLastProperty to FormatOptions

### PR DESCRIPTION
**Pull request by babich-a**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/jakubpawlowicz/clean-css#formatting-options>
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

According to [documentation](https://github.com/jakubpawlowicz/clean-css#formatting-options) semicolonAfterLastProperty option is contained in `format` (FormatOption type)

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## clean-css ([<kbd>unpkg</kbd>](https://unpkg.com/browse/clean-css@latest/))
was missing the following properties:
1. process
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c9ff8058705f54e1ad14de851e0088ecfe2900f
</p>

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## clean-css ([<kbd>unpkg</kbd>](https://unpkg.com/browse/clean-css@latest/))
was missing the following properties:
1. process
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against af3b10f545492d493123db1a3c30f006020dabce
</p>

**Comment by babich-a** [comment]
I have no idea what's wrong with Travis CI (Error: Cannot find module '/home/travis/.dts/typescript-installs/4.0/node_modules/typescript')

**Comment by orta** [comment]
Cool, this looks good 👍

**Pull request merged**
