### PR TITLE
[react-virtualized] - Allows to set arbitrary props to force re-render

### PR DESCRIPTION
**Pull request by wasd171**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/bvaughn/react-virtualized/issues/756>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by kaoDev** [comment]
Hi @wasd171,
thanks for your contribution, at first sight this signature `[key: string]: any` looks like incomplete typings, but you are right and this is a missing feature. I think a comment would be good to clarify that these wildcards are wanted and for what usecase they are implemented. Perhaps you can link to the part of the documentation you mentioned here https://github.com/bvaughn/react-virtualized/issues/756

**Comment by wasd171** [comment]
Hi @kaoDev !
I am referring to this [link](https://github.com/bvaughn/react-virtualized#pass-thru-props)

**Comment by wasd171** [comment]
I have added comments in the code

**Comment by kaoDev** [comment]
thank you 👍 

then everything is fine and this PR can be merged

**Comment by guntherjh** [comment]
These changes, along with the additional comments, seem fine to me. I'll let @kaoDev make the final call on merging though. Thanks for contributing @wasd171 ! 👍

**Pull request merged**
