### PR TITLE
ftpd typings: error and result can both be undefined for readdir, open, stat in FtpFileSystem.

### PR DESCRIPTION
**Pull request by SanderDeWaal1992**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 

```
import * as fs from "fs";

fs.readdir("./non-existing-dir", (error, files) => {
	// Will print "error: ..."
	console.log("error: ", error);
	// Will print "files: undefined"
	console.log("files: ", files);
});
fs.readdir("./existing-dir", (error, files) => {
	// Will print "error: null"
	console.log("error: ", error);
	// Will print "files: ..."
	console.log("files: ", files);
});
```

- [X] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by rogierschouten — COMMENTED** [review]
@SanderDeWaal1992 isn't it true for all Node callbacks in general, that only one of the parameters is ever filled in? But usually they are typed as if they are always filled in, to avoid compiler hassle? What are you running into at the moment?

**Comment by SanderDeWaal1992** [comment]
@rogierschouten Yes, you are right. I forgot to add some explanation in here.

In the ftpd module, the node file system is mocked and you have to implement the methods yourself. Eg you have to implement the "readdir" method and it has to comply to the 'FtpFileSystem' interface of this typings. For this reason Typescripts (in strict null checking mode) currently expects you to call the callback with always an Error and always a result. If this PR is merged, the typings allow you to set the callback arguments to undefined like Node in reality does.

**Review by rogierschouten — APPROVED** [review]

**Comment by rogierschouten** [comment]
:+1:

**Comment by SimonSchick** [comment]
On a note, this code would be much more readable if overloads would be used instead of properties.

**Pull request merged**
