### PR TITLE
raspi-peripheral: Provides its own types

### PR DESCRIPTION
**Pull request by ghost**
This will deprecate `@types/raspi-peripheral` in favor of just `raspi-peripheral`. CC @nebrius

### CODE REVIEW

**Comment by nebrius** [comment]
@andy-ms please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21618 for a discussion of why these were added.

tl;dr this suite of packages cannot be installed on anything other than a Raspberry Pi due to install scripts that are Raspberry Pi specific. Without these DefinitelyTyped definitions, the only way to develop using this module on a laptop is to manually copy the definition files into the project and use a custom typings folder. This tends to be kludgy and error-prone IME though.

However, if you feel that this doesn't justify keeping these types in DefinitelyTyped, then I can go back to my hacky method.

**Comment by andy-ms** [comment]
Thanks for the explanation. I've added `"raspi", "raspi-board", "raspi-peripheral",` to a list of excludes to prevent this from happening again.

**Comment by nebrius** [comment]
Thank you @andy-ms! FYI I'm about to submit another PR to get the rest of the raspi-* suite in to DefinitelyTyped. Would you like me to cc you in that pull request so you can add them to the list too?

**Comment by andy-ms** [comment]
Yes please

**Pull request closed without merging**
