### PR TITLE
yup: added test validator context

### PR DESCRIPTION
**Pull request by nikita-graf**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup#mixedtestname-string-message-string-test-function-schema
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sseppola** [comment]
I'm not familiar with how testing usually is done here, but if it is just to assert that typescript knows the context, this PR looks fine.

Was a bit unsure about how to define the context for a function, so if anyone else needs finds it useful, here's a link to the handbook: https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

**Comment by nikita-graf** [comment]
> I'm not familiar with how testing usually is done here, but if it is just to assert that typescript knows the context, this PR looks fine.

Me too. Tests fail if I try to access properties which are not defined on the `TestContext ` interface. Hope it's a proper way of testing such kind of code.

**Comment by sseppola** [comment]
Personally I think there should be assertions to make sure the library actually provides these values instead of just making sure typescript think they are there. That said, it looks like you've followed precedence, so I'm going to accept it.

Thanks for submitting the PR :)

**Review by sseppola — APPROVED** [review]

**Comment by nikita-graf** [comment]
It makes sense, however, I didn't find a way of doing that other than current. The only improvement I missed before is a stricter checking of `this`:
```js
mixed.test('with-context', 'it uses function context', function() {
    const context: TestContext = this;
    return true;
});
```

**Comment by sandersn** [comment]
@nikita-graf You should be able to use `$ExpectType` assertions [1] like so:

```ts
$ExpectType string
this.path;
```

Do you want me to merge the PR as-is? Without an assertion, `this` could be of type any, meaning that `this.path` is (1) legal (2) also of type any.

[1] https://github.com/Microsoft/dtslint#write-tests

**Comment by nikita-graf** [comment]
@sandersn Thanks for the explanation! I think it's better to have tested the case with `any`. Let me update tests before merging it.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
