### PR TITLE
Fix for #66946 - forge-apis - add hookExpiry to HooksOptions

### PR DESCRIPTION
**Pull request by princefishthrower**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://aps.autodesk.com/en/docs/webhooks/v1/reference/http/webhooks/systems-system-hooks-POST/#body-structure
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## forge-apis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/forge-apis@latest/))
was missing the following properties:
1. ApiClient
1. BadInput
1. BaseAttributesCreatedUpdated
1. BaseAttributesCreatedUpdatedAttributes
1. BaseAttributesExtensionObject

<details>
<summary>as well as these 140 other properties...</summary>
<p>BaseAttributesExtensionObjectWithoutSchemaLink, Bucket, BucketObjects, Buckets, BucketsItems, Conflict, CreateItem, CreateItemData, CreateItemDataRelationships, CreateItemDataRelationshipsTip, CreateItemDataRelationshipsTipData, CreateItemIncluded, CreateItemRelationships, CreateItemRelationshipsStorage, CreateItemRelationshipsStorageData, CreateRef, CreateRefData, CreateRefDataMeta, CreateStorage, CreateStorageData, CreateStorageDataAttributes, CreateStorageDataRelationships, CreateStorageDataRelationshipsTarget, CreateVersion, CreateVersionData, CreateVersionDataRelationships, CreateVersionDataRelationshipsItem, CreateVersionDataRelationshipsItemData, Diagnostics, Folder, FolderAttributes, FolderRelationships, Forbidden, Formats, FormatsFormats, Hub, HubAttributes, HubRelationships, Hubs, Item, ItemAttributes, ItemCreated, ItemRelationships, Job, JobAcceptedJobs, JobDwgOutputPayload, JobDwgOutputPayloadAdvanced, JobIfcOutputPayload, JobIfcOutputPayloadAdvanced, JobIgesOutputPayload, JobIgesOutputPayloadAdvanced, JobObjOutputPayload, JobObjOutputPayloadAdvanced, JobPayload, JobPayloadInput, JobPayloadItem, JobPayloadOutput, JobPayloadMisc, JobPayloadDestination, JobStepOutputPayload, JobStepOutputPayloadAdvanced, JobStlOutputPayload, JobStlOutputPayloadAdvanced, JobSvfOutputPayload, JobSvfOutputPayloadAdvanced, JobSvf2OutputPayload, JobSvf2OutputPayloadAdvanced, JobThumbnailOutputPayload, JobThumbnailOutputPayloadAdvanced, JsonApiAttributes, JsonApiCollection, JsonApiDocument, JsonApiDocumentBase, JsonApiError, JsonApiErrorErrors, JsonApiErrorLinks, JsonApiLink, JsonApiLinks, JsonApiLinksPaging, JsonApiLinksRelated, JsonApiLinksSelf, JsonApiMeta, JsonApiMetaLink, JsonApiRelationships, JsonApiRelationshipsLinksExternalResource, JsonApiRelationshipsLinksInternal, JsonApiRelationshipsLinksInternalResource, JsonApiRelationshipsLinksRefs, JsonApiRelationshipsLinksRefsLinks, JsonApiResource, JsonApiTypeId, JsonApiVersion, JsonApiVersionJsonapi, Manifest, ManifestChildren, ManifestDerivative, Message, Messages, Metadata, MetadataCollection, MetadataData, MetadataMetadata, MetadataObject, NotFound, ObjectDetails, ObjectFullDetails, ObjectFullDetailsDeltas, ObjectS3Download, ObjectS3Upload, ObjectCompleteS3Upload, Permission, PostBucketsPayload, PostBucketsPayloadAllow, PostBucketsSigned, PostObjectSigned, Project, ProjectAttributes, ProjectRelationships, Projects, Reason, Refs, RelRef, RelRefMeta, ResourceId, Result, Storage, StorageCreated, StorageRelationships, StorageRelationshipsTarget, StorageRelationshipsTargetData, TopFolders, UserProfile, UserProfileProfileImages, Version, VersionAttributes, VersionCreated, VersionRelationships, Versions, IssuesApi, setDebug</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9c3c277891ac0552c65498b1dff8b0bf19736923
</p>

**Comment by sandersn** [comment]
Maintainer note: mergebot didn't notice that package.json contains an additional owner now

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
Ready to merge

**Comment by sandersn** [comment]
Ready to merge

**Comment by sandersn** [comment]
Hm, I guess @typescript-bot only listens to people it has pinged. I thought admins were on the list before.

**Pull request merged**
