### PR TITLE
fix(webpack-merge-and-include-globally): missing `apply` contract

### PR DESCRIPTION
**Pull request by peterblazejewicz**
/cc @OldStarchy

Closes #58717

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by joshuajeschek** [comment]
Hi, I only have one small question about your PR:
Isn't the options interface missing the [transformFileName](https://github.com/markshapiro/webpack-merge-and-include-globally#transformfilename) option?

**Comment by peterblazejewicz** [comment]
Hey, yes, I amended definition in PR update, thanks!

**Review by joshuajeschek — APPROVED** [review]
looks good now :)

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
