### PR TITLE
[react] Remove scheduler/tracing API

### PR DESCRIPTION
**Pull request by eps1lon**
Was removed in https://github.com/facebook/react/releases/tag/v18.0.0 via https://github.com/facebook/react/pull/20037

### CODE REVIEW

**Comment by eps1lon** [comment]
Long overdue.

**Comment by adammiller** [comment]
Due to the wildcard dependency on `@types/scheduler`, this is breaking old versions of `@types/react` - i'm seeing it with v18.0.* but I'd assume it's any version of 18 prior to the version that resulted from this change. 

If you install `@types/react: "18.0.28"`, it will install the latest of `@types/scheduler` which does not include the `scheduler/tracing` file.

**Comment by eps1lon** [comment]
This was a bug in those older versions of `@types/react`. Later versions should have a dependency on `^0.16` instead of `^0.23`.

**Comment by eps1lon** [comment]
Yeah this was an unfortunate historic leftover when types had wildcard dependencies. You can tell your package manager to enforce `"@types/scheduler": "^0.16.0"` either via `resolutions` or `overrides`. But the tracing types are always incorrect in 18 since it was removed throughout these releases.

We can't fix that bug for old versions unfortunately. It's best to upgrade to the latest `@types/react@^18` anyway.

**Pull request merged**
