### PR TITLE
[@types/handlebars]: Remove package, types are now integrated in hand…

### PR DESCRIPTION
**Pull request by nknapp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] *Test the change in your own code. (Compile and run.)* (when removing a package? see below)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.) (**failing, see below**)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] *Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).* (when removing a package? see below)

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

Some of the checkboxes below don't seem to apply to removing a package, which is why I left them blank.

I have added package.json files to 4 dependencies, but I'm not sure if I did this correctly. It would be nice if someone could check. I notice that "ember-strings" already have type definitions in their source repo, so they might be redundant here.

`npm test` still fails, because Handlebars is not on the dependencyWhitelist of the types-publisher (I've [submitted a PR there](https://github.com/Microsoft/types-publisher/pull/571)) 

Replacement PR for #32897

### CODE REVIEW

**Comment by chriskrycho** [comment]
Try a rebase on master and force push? 🤞

**Comment by chriskrycho** [comment]
No longer necessary; a maintainer kindly pushed the "restart the build" button for us!

**Comment by nknapp** [comment]
I think the errors of the build are not caused by the PR. I do not fully understand them, and I am unable to fix them. Is there anybody who can help

@mike-north ?

**Comment by chriskrycho** [comment]
Sorry about this, @nknapp – we'll try to follow up and get it sorted once the TS issue is worked out.

**Pull request closed without merging**
