### PR TITLE
[ramda] curried R.flip

### PR DESCRIPTION
**Pull request by imcotton**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

https://github.com/ramda/ramda/blob/6709cb8beca00178d2288f79568cc5ca9e95d2f5/source/flip.js#L25-L32

### CODE REVIEW

**Comment by pirix-gh** [comment]
@imcotton do you run the tests locally?

**Comment by imcotton** [comment]
Hi @pirix-gh, I only have quickly checked via Language Service by VS Code, but according the CI testing shows, seems upcoming TS 3.6 would have yelled differently?

I have feeling that this `flip` needs more dedicated tweak than mine, could use some help from you I think.

**Comment by imcotton** [comment]
btw: does the changing to `gt` and `gte` looks right? Worthwhile a separate PR for those refactor?

**Comment by pirix-gh** [comment]
Hi @imcotton, `gt` & `gte` look right. Not sure why they're readonly though...

Here's a version of flip that I quickly wrote with the ts-toolbelt:

```ts
import {F, T} from 'ts-toolbelt';

declare function flip<F extends (...args: any) => any, P extends Parameters<F>>(fn: F):
    F.Curry<(...args: T.Concat<[P[1], P[0]], T.Drop<P, '2'>>) => F.Return<F>>;

const f = (a: string, b: number, c: object, d: symbol) => true

const ff = flip(f) // works
```

Instead of using the ts-toolbelt, just use the tools from (where is was born from):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/tools.d.ts

Please run your tests locally with `npm test` to avoid triggering emails for all the maintainers.

**Comment by imcotton** [comment]
Couldn't run `npm test` successfully since it keeps give me error as microsoft/types-publisher#493 (both Mac OS and clean Linux docker container), have no clue how to get around, pushing to CI instead, sorry for the disturbing.

@pirix-gh, thank you for the help, I followed your example made the change, it looks almost worked but TS@next gives new error, am I doing something wrong? Or it's a breaking changes in TS 3.6?

**Comment by pirix-gh** [comment]
You should try in a VM then, or consider switching to ubuntu :laughing: 

I have no idea about the error, I don't have the repo ready, would you mind sharing?

**Comment by imcotton** [comment]
Have added you as collaborator in my fork, feel free to do experiment on it, thanks again for the help.

At the meantime I'm setting up VM on the cloud for further test.

**Comment by pirix-gh** [comment]
@imcotton I tried to implement with the types provided in `Tools` and there's problems indeed.
This was still experimental (at that time) and I would like to provide the ts-toolbelt types instead.
In order to do this, I am (now) going to ask for my package to be added to the whitelist of DT.

Then, I we will be able to write `R.flip`. It will be easier like that. And Ramda will benefit from the whole type library power (and we will be able to remove the old/ugly `Tools.d.ts`).

So please hold on :)

**Comment by imcotton** [comment]
Sounds promising, would love to have all the great power from `ts-toolbelt` indeed, will stay tuned.

And please do not hesitate to create new PR with proper changes, I'm happy to discard this one as to be superseded : )

**Comment by imcotton** [comment]
Closed in favor of #37409

**Comment by pirix-gh** [comment]
@imcotton I did not include `gt` and `gte` in #37409

**Comment by imcotton** [comment]
@pirix-gh thank you for reminding, going to wait for #37409 lands, would open new one if it still needed afterwards.

**Pull request closed without merging**
