### PR TITLE
[node] Add getSendQueueSize and getSendQueueCount methods to dgram

### PR DESCRIPTION
**Pull request by QuentinGruber**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/dist/latest-v20.x/docs/api/dgram.html#socketgetsendqueuesize>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by Semigradsky — APPROVED** [review]

**Comment by QuentinGruber** [comment]
I honestly don't know what to do since the test that fails is part of a node-dependent package that also fails on master, so I took the liberty of "fixing" it. If anyone can point me in the right direction, I'll follow it.

**Review by peterblazejewicz — APPROVED** [review]
I've rerun failed jobs, seems it helped.
@QuentinGruber thanks!

**Comment by QuentinGruber** [comment]
Ready to merge

**Comment by Elenore23** [comment]
> Ready to merge

**Pull request merged**
