### PR TITLE
Update JSZip definitions for version 3

### PR DESCRIPTION
**Pull request by tyfkda**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

JSZip has changed its APIs asynchronously in version 3.0:

http://stuk.github.io/jszip/documentation/upgrade_guide.html

Replace to async method definitions:
- `load` => `loadAsync`
- `generate` => `generateAsync`
- `asXXXX` => `async('XXXX')`

> JSZip.compressions has been removed.

So related tests are removed.

### CODE REVIEW

**Comment by mhegazy** [comment]
@mzeiher any comments?

**Comment by mzeiher** [comment]
Sorry for the delay, looks great, one remark ,-> maybe use string literal types for parameters in line119 in jszip.d.ts:
async(type: "base64" | "binarystring" | "uint8array" | "arraybuffer" | "blob" | "nodebuffer", onUpdate?: Function): Promise<any>;
or declare
type Serialization = "base64" | "binarystring" | "uint8array" | "arraybuffer" | "blob" | "nodebuffer" and use async(type: Serialization, onUpdate?: Function): Promise<any>;

requires TS1.8+ though

IMHO this leads to a "safer" API, you get compile time feedback about the allowed parameters.

**Comment by tyfkda** [comment]
@mzeiher Thank you for your suggestion. I have updated the `async` definition. Would you please take a look? Thanks!

**Comment by mzeiher** [comment]
Looks great! Thanks @tyfkda for the improvement. At the moment I don't have access to a PC let alone a stable internet connection, by reviewing the code everythings looks fine -> as I recall the Promise keyword isn't in TS 1.8 yet -> does it compile with missing Promise polyfill/definition?

**Comment by tyfkda** [comment]
Good catch @mzeiher !
I had compiled the code with `--target es6` option, but it was not good idea.

JSZip uses `es6-promise` so I tried to add its `reference` with `path="../es6-promise/es6-promise.d.ts"`. I can compile it without error, but `npm run test` complains:

```bash
$ npm run test
...
============================== Syntax checking ==============================
x
-----------------------------------------------------------------------------
 Elapsed time    : ~0.931 seconds (0.931s)
 Successful      : 0.00% (0/1)
 Failure         : 100.00% (1/1)
=============================== Typing tests ================================
x
-----------------------------------------------------------------------------
 Elapsed time    : ~1.149 seconds (1.149s)
 Successful      : 0.00% (0/1)
 Failure         : 100.00% (1/1)
=============================== Header format ===============================
.
-----------------------------------------------------------------------------
 Elapsed time    : ~0.002 seconds (0.002s)
 Successful      : 100.00% (1/1)
 Failure         : 0.00% (0/1)
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
 Total
-----------------------------------------------------------------------------
 Elapsed time    : ~3.617 seconds (3.617s)
 Syntax error    : 100.00% (1/1)
 Failed tests    : 100.00% (1/1)
 Invalid header  : 0.00% (0/1)
 Without tests   : 0.00% (0/1)
-----------------------------------------------------------------------------
=============================================================================
                    Errors in files
=============================================================================
----------------- For file:jszip/jszip.d.ts
es6-promise/es6-promise.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
es6-promise/es6-promise.d.ts(42,19): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(1257,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(1347,13): error TS2300: Duplicate identifier 'Promise'.

=============================================================================
----------------- For file:jszip/jszip-tests.ts
es6-promise/es6-promise.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
es6-promise/es6-promise.d.ts(42,19): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(1257,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(1347,13): error TS2300: Duplicate identifier 'Promise'.

=============================================================================
```

If I don't add `reference`, `npm run test` passes, but `tsc` returns error.

How can I fix this?

**Comment by tyfkda** [comment]
@mzeiher
I have updated the PR, so would you please take a look?

I looked some type definition using `es6-promise` (ex. [freedom](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/freedom), [isomorphic-fetch](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/isomorphic-fetch), [openpgp](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/openpgp) ),
they are failed with `tsc --noImplicitAny XXXX/XXXX-tests.ts`, but passed with `--target es6`. So I think my change for JSZip is same as them.

**Comment by tyfkda** [comment]
@mzeiher,  @mhegazy,
Ping, just in case.

**Comment by mhegazy** [comment]
@mzeiher any more comments? or is this good to go?

**Comment by mzeiher** [comment]
Hi, sorry for the long silence -> if the behaviour of the tsc is the same as for other projects everything's fine from my point of view. looks good now.

**Comment by tyfkda** [comment]
@mzeiher, thank you for the review!
@mhegazy, could you merge this PR please? thanks!

**Pull request merged**
