### PR TITLE
Adding in Windows.Services.Store namespace

### PR DESCRIPTION
**Pull request by likewei92**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@saschanaz, @taylor224 can you please review. Thanks

**Comment by SaschaNaz** [comment]
VS already autogenerates this, do we still need this file?

**Comment by sheetalkamat** [comment]
Adding @mhegazy and @andy-ms who have better information of this.

**Comment by andy-ms** [comment]
I'm not really familiar with this, sorry.  If these types are bundled with a package we would normally remove them from DT, but it sounds like it's more complicated here -- how does VS provide the types?

**Comment by likewei92** [comment]
@SaschaNaz I would like to know how VS autogenerates this as well

**Comment by SaschaNaz** [comment]
Not sure exactly how it does but see this comment: https://github.com/Microsoft/TypeScript/issues/8950#issuecomment-252381456

We may still have to maintain this file if the autogeneration is only for VS2017+.

**Review by saschanaz — APPROVED** [review]

**Comment by andy-ms** [comment]
CC @minestarks who originally commented on https://github.com/Microsoft/TypeScript/issues/8950#issuecomment-252381456

**Comment by minestarks** [comment]
autogeneration is for VS2017+ only, we should keep this for other use cases

**Comment by likewei92** [comment]
Question, when will these changes get picked up by https://www.npmjs.com/package/@types/winrt ? That package hasn't been updated in a year..

**Comment by likewei92** [comment]
Nvm I see that it's already published as winrt-uwp

**Pull request merged**
