### PR TITLE
Refractor: Adding missing language file for csv

### PR DESCRIPTION
**Pull request by devinmatte**
`csv` was missing from the type definitions despite being in the package both in 3.x and 4.x versions

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wooorm/refractor/blob/main/lang/csv.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by devinmatte** [comment]
Hi @ifiokjr. Is there anything else you'd like from this PR? Would love a chance to get it merged, thanks

**Review by gabritto — CHANGES_REQUESTED** [review]
It seems csv was added starting at version 4.1 of the original package. Please update the version of the DT package (in the `package.json`) to reflect that. Right now the types are [still at version 3.0](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/refractor/package.json#L4), which doesn't have csv.

**Comment by devinmatte** [comment]
@gabritto csv is present in 3.x
https://github.com/wooorm/refractor/blob/3.6.0/lang/csv.js
first present in 3.4 https://github.com/wooorm/refractor/blob/3.4.0/lang/csv.js

4.x has its own provided types, but the package I'm working with can't yet update to 4.x but would like the types for csv

**Comment by gabritto** [comment]
You're right, my mistake. I was confused because it was removed in later versions and then re-added, it seems (e.g. version 4.0 on npm doesn't have a `lang/csv.js`). Still, since this is first available on version 3.4, I think you still need to update the version in the `package.json` to 3.4, as it currently is at 3.0.

**Review by gabritto — APPROVED** [review]

**Comment by devinmatte** [comment]
Ready to merge

**Pull request merged**
