### PR TITLE
[convert-source-map] Update convert-source-map to latest v1.3.0 (TypeScript 2.0)

### PR DESCRIPTION
**Pull request by TeamworkGuy2**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/thlorenz/convert-source-map
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
Hi, could you turn on linting (add `tslint.json` containing `{ "extends": "../tslint.json" }`) as long as you're changing the whole file?
The first thing the linter will warn you about is the `declare module "convert-source-map"`. It was actually right before: write definitions at the top-level.

**Comment by TeamworkGuy2** [comment]
Sure thing, can you explain how it was correct before or maybe point me to an example DT definition with the correct structure? 
convert-source-map is a node/npmjs module, it doesn't create any global function/var declarations, you have to require/import it, that's why I figured the old way was wrong.

**Comment by andy-ms** [comment]
Since you're in a file `convert-source-map/index.d.ts`, you are *already* declaring the `"convert-source-map"` module by default, so adding a wrapper is redundant.
All you need to do to fix the structure is to remove the `declare module "convert-source-map" { ... }` wrapper.

**Comment by TeamworkGuy2** [comment]
Flattened the module and got the tslint file added and fixed one lint error about the version number comment.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
