### PR TITLE
p-limit: upgrade typings for v2.0

### PR DESCRIPTION
**Pull request by LinusU**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sindresorhus/p-limit/pull/8
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by LinusU** [comment]
@sandersn this is the same update as #26577, would you mind reviewing this one as well as in this case also only @BendingBender was the other author ❤️

**Review by sandersn — APPROVED** [review]

**Comment by LinusU** [comment]
Thanks ❤️

**Comment by LinusU** [comment]
@RyanCavanaugh and @andy-ms: this doesn't seem to have been published to npm yet 🤔

**Comment by andy-ms** [comment]
It looks like the publish step is failing. Will investigate.

**Pull request merged**
