### PR TITLE
Added declaration and tests for 'rc'.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
CI fix pending

**Comment by andy-ms** [comment]
Is this good to go?

**Comment by DanielRosenwasser** [comment]
Should it be `index-tests` or `rc-tests`? `dt-bot` seems to be saying the former.

**Comment by andy-ms** [comment]
I suspect dt-bot is just copying the name of the main file. But in the `types-2.0` branch we use the name `index.d.ts` to make it a proper module, but looking around I don't see that name being used for tests. I would say go ahead and merge. :+1:

**Pull request merged**
