### PR TITLE
[@types/node]: ability to set numeric value of URLSearchParams

### PR DESCRIPTION
**Pull request by e965**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

This doesn't seem to be in the spec, but platforms allow you to set a numeric value.
All I've found on this topic is [this discussion](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1568).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/url.ts
1. types/node/url.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9648f826d33d649df1fc06425073d79da7d75cc
</p>

**Comment by peterblazejewicz** [comment]
IMO lot of changed, I assume implementation is now aligned with lib.dom, as there is now web api concept.
Current dom are like:
https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L22778

**Comment by e965** [comment]
@peterblazejewicz I understand what you're talking about (there's a discussion about it all in the issue I linked to in the first post). But, to be honest, I still don't really understand why we don't rely on the actual API implementation in platforms when we write types.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
I am adding as review requested as it wont move to waiting on code reviews and keeps poping into maintainer action board.. Pls merge main when there is resolution on what needs to be done

**Comment by e965** [comment]
@sheetalkamat I'm also waiting for a decision 👀

**Pull request closed without merging**
