### PR TITLE
[@types/styled-system] set devDependencies on styled-components

### PR DESCRIPTION
**Pull request by leshkovichpvl**
Set devDependencies on <code>styled-components</code>, because <code>styled-components</code> unused in definition.

### CODE REVIEW

**Comment by Lavoaster** [comment]
@RyanCavanaugh @andy-ms Is there any way when the types are published to have it exclude `styled-components` as a dependency?

Alternatively, is the better approach here to mock out the dependency instead so we can drop the package.json file?

Tag #27881 so the issue can see the PR.

**Comment by leshkovichpvl** [comment]
Maybe needs implements styled function for tests?

**Comment by zephraph** [comment]
Yeah, @alloy and I were talking about this a little bit. We definitely don't actually want to pull in styled-components as a dependency here, but it wasn't clear how to test without it. 

I've tried looking for other examples of how to solve this, but it generally just looks like folks add things as dependencies.

**Comment by andy-ms** [comment]
Currently there's no way to create test-only dependencies.
Is there a way you could mock `styled-components` for tests without actually importing it?

**Comment by phobon** [comment]
I feel like mocking is probably the way to go; do we need to mock styled-components or is there a path of smaller resistance (styled-system works with most css-in-js libs) we could look at?

**Comment by zephraph** [comment]
There has been conversations from the `styled-components` team to move their typescript types to this repo. When they do that maybe we'll have more options?

**Comment by Lavoaster** [comment]
Alright I spent about 30 mins on this today and got to this https://gist.github.com/Lavoaster/acc65016cb3509da32d42bec0c5ec053.

_however_ I'm getting the following errors when trying to lint the package, but VS Code is able to resolve everything properly without any lint errors in the file.

```
ERROR: 175:13  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Operator '>' cannot be applied to types 'boolean' and 'string'.
ERROR: 175:20  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
'BoxProps' only refers to a type, but is being used as a value here.
ERROR: 221:5   expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Property 'defaultProps' does not exist on type 'boolean'.
ERROR: 232:14  expect  Compile error in typescript@2.8 but not in typescript@2.9.
Fix with a comment '// TypeScript Version: 2.9' just under the header.
Operator '>' cannot be applied to types 'boolean' and 'string'.
... (about 90 more lines saying the same thing :D) 
```

I'd rather not bump up the version if I don't have to, does anyone have any idea what going wrong here?

**Comment by andy-ms** [comment]
@Lavoaster ts2.9 didn't support type arguments on tagged templates. You could write:
```ts
const Box: React.ComponentType<BoxProps> = styled`...`;
```
instead of:
```ts
const Box = styled<BoxProps>`...`;
```

**Pull request closed without merging**
