### PR TITLE
Fix broken link to author

### PR DESCRIPTION
**Pull request by DovydasNavickas**

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
:+1:

**Comment by DovydasNavickas** [comment]
:+1: as @GiedriusGrabauskas is the author, but included @QuatroCode (former @QuatroDevOfficial) before.

**Comment by GiedriusGrabauskas** [comment]
:+1:

**Comment by stkb** [comment]
👍

**Comment by horiuchi** [comment]
@DovydasNavickas Thanks!

**Pull request merged**
