### PR TITLE
types(selenium-webdriver): version 2.53.1

### PR DESCRIPTION
**Pull request by cnishina**
- moving selenium-webdriver.d.ts to selenium-webdriver-2.44.0.d.ts
- adding in selenium-webdriver.d.ts for version 2.53.1

### CODE REVIEW

**Comment by cnishina** [comment]
This is failing the DefinitelyTyped angular-protractor.d.ts tests relies on the path to selenium-webdriver.d.ts. The [protractor](https://github.com/angular/protractor) team is trying to [support type declarations](https://github.com/angular/protractor/blob/master/package.json#L61); however, requires a more recent version of selenium-webdriver.d.ts.

I do not want to break existing users of DefinitelyTyped angular-protractor ambient typings; however, I do need more up to date type declarations to work on Protractor. My proposal is to include the selenium-webdriver.d.ts 2.44.0 with the angular-protractor.d.ts. This would not break existing users of angular-protractor.d.ts.

**Comment by Kuniwak** [comment]
I'll check it later, but my review cannot find many bugs because this change is huge.

So, I hope many people as possible try it on theirs project.
It can keep quality of selenium-webdriver.d.ts.

**Comment by cnishina** [comment]
In an attempt to potentially not break DefinitelyTyped angular-protractor users, I realized that this commit would break angular-protractor users that already have `selenium-webdriver` as a typings dependency.

Is there a way I could add in my `selenium-webdriver` typings without changing the existing? Maybe we could call this `selenium-webdriver-experimental` for now?

```
DefinitelyTyped/
|- angular-protractor/
|  |- revert files
|
|- protractor-helpers/
|  |- revert files
|
|- protractor-http-mocks/
|  |- revert files
|
|- selenium-webdriver/
|  |- revert files
|
|- selenium-webdriver-experimental/
|  |- selenium-webdriver-experimental.d.ts
|  |- selenium-webdriver-experimental-tests.ts
```

If this sounds good, I will make the change.

**Comment by cnishina** [comment]
Plan to rework for types-2.0 branch.

**Comment by cnishina** [comment]
@Kuniwak - In upgrading to 2.53.1, how does this get published to the types-2.0 branch? I need these changes in quickly.
@vvakame - Please review the proposed changes. These have no impact on existing users of selenium-webdriver 2.44.0.

**Comment by cnishina** [comment]
Also @BillArmstrong. Please review. I'm trying to get these ambient typings to use for Protractor.
Thanks!

**Comment by vvakame** [comment]
okay, We can't get response from authors a long time.
I tried to merge this PR.

**Comment by cnishina** [comment]
Thanks @vvakame. Hopefully I didn't break existing users. Should I add myself as an author?

**Pull request merged**
