### PR TITLE
[React] Add target to FocusEvent

### PR DESCRIPTION
**Pull request by guilhermehubner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/pt-BR/docs/Web/Events/focus
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by gabsprates** [comment]
Great! I had troubles with that and this solution works fine to me. I really need that change.

**Comment by FdeFabricio** [comment]
👍

**Comment by laryssamagalhaes** [comment]
Thanks @guilhermehubner , it worked for me! :metal: :tada:

**Comment by rodrigo-brito** [comment]
Amazing. It works here! 👏

**Pull request merged**
