### PR TITLE
Add ShallowRendererProps Into ShallowWrapper's shallow Fn

### PR DESCRIPTION
**Pull request by huhuanming**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://airbnb.io/enzyme/docs/api/ShallowWrapper/shallow.html>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by huhuanming** [comment]
No one here?

**Comment by huhuanming** [comment]
Hellooooo~~~

**Comment by huhuanming** [comment]
@sandersn

**Comment by sandersn** [comment]
Sorry, there was quite a backlog last week and I don't think the person on DefinitelyTyped duty this week has caught up.

**Comment by huhuanming** [comment]
I think so, but no good idea on it.

**Pull request merged**
