### PR TITLE
Add configs(cli, npm, syslog) for winston

### PR DESCRIPTION
**Pull request by heycalmdown**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/winstonjs/winston#using-logging-levels
- [x] Increase the version number in the header if appropriate.

- refactor to abstract configs

### CODE REVIEW

**Comment by heycalmdown** [comment]
Is the "maximum time limit" error normal? How I can fix this?

**Comment by andy-ms** [comment]
@heycalmdown Please merge from the latest `types-2.0` to fix tests.

**Comment by heycalmdown** [comment]
@andy-ms got it!

**Comment by heycalmdown** [comment]
@andy-ms Done

**Comment by sandersn** [comment]
I had to merge from types-2.0 since the merge from master. Thanks for the update @heycalmdown

**Pull request merged**
