### PR TITLE
[mapbox-gl] Add missing public properties and method for Mapbox-gl

### PR DESCRIPTION
**Pull request by life777**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.5.0>>

I found a few properties and methods that were added before but missed here:
1) Property `workerCount`. [docs](https://docs.mapbox.com/mapbox-gl-js/api/#workercount)
2) Property `maxParallelImageRequests`. [docs](https://docs.mapbox.com/mapbox-gl-js/api/#maxparallelimagerequests)
3) Method `clearStorage`. [docs](https://docs.mapbox.com/mapbox-gl-js/api/#clearstorage)

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by life777** [comment]
This failure isn't caused by my commit. It tries to load typescript 3.7 and failed. Could we restart this step?:
Screenshot from 2019-10-31 18-05-20

**Comment by dmytro-gokun** [comment]
Hi @life777! Thank you for your PR. There are two notes i'd like to make here before accepting this.
1) This partially overlaps with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39961, which is still in process. Let's wait for that to be merged first, so there is no merge conflict.
2) Please add some tests for signatures you've added (except those already covered by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39961).

**Comment by jessetrinity** [comment]
The build error should be resolved. We're still having trouble with BenchmarkPR but its success is not required.

**Comment by dmytro-gokun** [comment]
@life777 Thanks for the update! This looks really good. But we need some tests added. I know, the changes look trivial. Still, it's better to add some minimal test cases.

**Review by dmytro-gokun — APPROVED** [review]

**Pull request merged**
