### PR TITLE
Add hegiht && paginationStyle Into react-native-swiper

### PR DESCRIPTION
**Pull request by huhuanming**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/leecade/react-native-swiper#properties>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
@CaiHuan, can you take a look?

Also, it looks like the Travis failure is from a badly formatted header line. I think you need a comma separating the contributor list.

**Comment by huhuanming** [comment]
I am sorry for it...

**Comment by huhuanming** [comment]
the Travis wa fixed. ☺️

**Comment by huhuanming** [comment]
😳

**Comment by sandersn** [comment]
I'll wait a few days before merging to see if @CaiHuan has any comments.

**Comment by huhuanming** [comment]
Well

**Comment by huhuanming** [comment]
11 days pass.

**Comment by sandersn** [comment]
Sorry, my week on DefinitelyTyped was done so I stopped checking it. Thanks for the reminder.

**Comment by huhuanming** [comment]
😁 not mind.

**Pull request merged**
