### PR TITLE
chore(node): remove unsupported v15 types

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/en/about/releases/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

v15 is non LTS and entirely unsupported, we should remove it.

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
This is like blockbuster :)
LGTM!

**Comment by SimonSchick** [comment]
Had to rebase 😂

**Comment by peterblazejewicz** [comment]
Also, can you edit the PR title, mentioning version explicitly instead of 'unsupported'? thx!

**Comment by SimonSchick** [comment]
Done.

**Review by LinusU — APPROVED** [review]
👍

**Review by peterblazejewicz — APPROVED** [review]

**Comment by SimonSchick** [comment]
Ready to merge

**Pull request merged**
