### PR TITLE
Added missing methods to Parse.Object

### PR DESCRIPTION
**Pull request by jaeggerr**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Object.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by flavionegrao — CHANGES_REQUESTED** [review]
toPointer could return a “Object” rather than any?
Missing unit tests?

**Comment by RyanCavanaugh** [comment]
@jaeggerr Please address comments from the code reviewers.

**Comment by jaeggerr** [comment]
I created a new Pointer interface instead of Object.
The implementation of toPointer() does not seem to return a Parse object.
https://github.com/parse-community/Parse-SDK-JS/blob/293e2e13fa8eb1c62786fecf6aa6cd4458670b7f/src/ParseObject.js#L512

Also, I had to fix some linter issues in the existing definitions and tests.

**Comment by RyanCavanaugh** [comment]
@flavionegrao - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?

**Comment by flavionegrao** [comment]
Looks good to me, good job @jaeggerr

**Review by flavionegrao — APPROVED** [review]
Looks good mate

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

**Pull request merged**
