### PR TITLE
Update types for restify 7.2

### PR DESCRIPTION
**Pull request by mgebundy**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/restify/node-restify/tree/v7.2.0
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Comment by sdubrez** [comment]
Hey,

I don't really know how to procede to add some types and I want to be sure it's needed. If we look at the https://github.com/restify/node-restify/blob/master/lib/plugins/multipartBodyParser.js there is a new opts attribut named `maxFileSize`. Should be add it to types ?

Thanks for your answer !

**Comment by uniqueiniquity** [comment]
Yes, you should go ahead and add it [here](https://github.com/mgebundy/DefinitelyTyped/blob/d2f9012bb6e25b8eb1159cab1fcaf750ad91ffc8/types/restify/index.d.ts#L1289).

**Comment by sdubrez** [comment]
Okey, I made a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26940.

I hope it has been done the way you intend it to be!

**Pull request merged**
