### PR TITLE
Upgrading serialport from v4 to v6

### PR DESCRIPTION
**Pull request by apearson**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Docs](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/v6.0.0/README.md) / [Source Code](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/v6.0.0/lib/index.js)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by codefoster** [comment]
At the end of the Travis run, you're getting "Namespace 'SerialPort' has no exported member 'options'". Try just adding the keyword `export` before the `interface updateOptions` and `interface setOptions`. Also, by convention, we Pascal case interfaces, so you might want to call those `UpdateOptions` and `SetOptions`.

**Comment by apearson** [comment]
I've changed the interfaces to Pascal case to match with convention and attempted to export the option interfaces but it seems like the export is redundant in the namespace context.  I'm going to remove the `export` and see try to see if there's another reason why the test is failing.

**Comment by codefoster** [comment]
Try pulling the interfaces out of the namespace. It appears to me that the Travis test is expecting to see the options interfaces directly in the module. When you put them in a namespace, they're available under `SerialPort.SetOptions` whereas when you export the SetOptions interface separately, then it's in the "root" of the module.

**Comment by apearson** [comment]
The problem is coming from the `firmata` package.  It looks like it depends on v4 of the `serialport` library. 

In `firmata`'s  `index.d.ts` , on line 158 it depends on `serialports`'s past version.

What would be the procedure to update `firmata` to point to v4 instead of the root `serialport`?

**Comment by codefoster** [comment]
Saw your new commit. Did that make the build work?

**Comment by apearson** [comment]
Had to repoint the serialpoint path in `firmata` to point to v4.  Looks like the travis build completed successfully.

**Comment by codefoster** [comment]
Excellent. Good work. 👍

**Pull request merged**
