### PR TITLE
Copy types for missing @ember/helper APIs from the actual types published in ember-source/types/*

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
      https://www.npmjs.com/package/ember-source?activeTab=code at `ember-source/types/stable/@ember/helper/index.d.ts`
      Docs: https://api.emberjs.com/ember/release/modules/@ember%2Fhelper

 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
idk what I did wrong, but I can't seem to clone locally
```bash
❯ git sparse-checkout add types/ember__helper

DefinitelyTyped on  master 

  origin  git@github.com:NullVoxPopuli/DefinitelyTyped.git  [blob:none] 

❯ la
Permissions Size User Date Modified Name
.rw-rw-r--   136 nvp  10 Jan 16:27  .editorconfig
drwxrwxr-x     - nvp  10 Jan 16:31  .git
.rw-rw-r--   231 nvp  10 Jan 16:27  .gitattributes
.rw-rw-r--   555 nvp  10 Jan 16:27  .gitignore
.rw-rw-r--    18 nvp  10 Jan 16:27  .npmrc
.rw-rw-r--     7 nvp  10 Jan 16:27  .prettierignore
.rw-rw-r--   155 nvp  10 Jan 16:27  .prettierrc.json
.rw-rw-r--   189 nvp  10 Jan 16:27  .travis.yml
.rw-rw-r--   527 nvp  10 Jan 16:27  azure-pipelines.yml
.rw-rw-r--  1.2k nvp  10 Jan 16:27  LICENSE
.rw-rw-r--  203k nvp  10 Jan 16:27  notNeededPackages.json
.rw-rw-r--  1.1k nvp  10 Jan 16:27  package.json
.rw-rw-r--   29k nvp  10 Jan 16:27  README.cn.md
.rw-rw-r--   21k nvp  10 Jan 16:27  README.es.md
.rw-rw-r--   29k nvp  10 Jan 16:27  README.ko.md
.rw-rw-r--   32k nvp  10 Jan 16:27  README.md
.rw-rw-r--   38k nvp  10 Jan 16:27  README.ru.md

DefinitelyTyped on  master 

  origin  git@github.com:NullVoxPopuli/DefinitelyTyped.git  [blob:none] 

```

**Comment by jakebailey** [comment]
I would personally suggest just cloning the entire repo. It's not that big and you can open subfolders in the editor.

**Comment by NullVoxPopuli** [comment]
oh yeah, it's only 1.1G, not bad. I remember it being bigger

**Comment by jakebailey** [comment]
> oh... running `pnpm i` took me to 6G 😅

Yes, you'll want to use `--filter` if you only want partial. https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

**Comment by NullVoxPopuli** [comment]
hm, 

> In package.json: Dependency @glimmer/runtime not in the allowed dependencies list.

how do I use types of other dependencies, if other dependencies can't be depended on?

**Comment by jakebailey** [comment]
You can add them, they just need to be added to the list:

> You must add non-@types dependencies to [the list of allowed external dependencies](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/definitions-parser/allowedPackageJsonDependencies.txt). [Pikaday is a good example.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pikaday/package.json) These additions are approved by a maintainer, which gives us the chance to make sure that @types packages don't depend on malicious packages.

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/ember__helper/ember__helper-tests.ts
1. types/ember__helper/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f7c8e23ec55ccc365abbb65b574fb7a8b92d4a95
</p>

**Review by wagenet — APPROVED** [review]

**Comment by wagenet** [comment]
Ready to merge

**Comment by jakebailey** [comment]
Ready to merge

**Comment by jakebailey** [comment]
@typescript-bot where are you?

**Pull request merged**
