### PR TITLE
Express: Add res.append to express types

### PR DESCRIPTION
**Pull request by alex3165**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://expressjs.com/tr/api.html#res.append>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by MichalLytek — COMMENTED** [review]
`res.append()` looks ok but @alex3165 what have you changed in tests? diff isn't helping 😞

**Comment by alex3165** [comment]
I have added a `tslint.json` to lint the definition and test files. There was plenty of lint issues so I had to fix them. I didn't change a lot in the test file I just removed the namespaces therefore I changed the indentation, a few `const` instead of `var`, missing semicolons... no change on the logic

**Comment by alex3165** [comment]
One of the problem with those change is that I had to remove the aliases `IRoute`, `IRouter` All exported interface prefixed with `I` because it is considered as a bad practice in the tslint and this is a breaking changes.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
