### PR TITLE
updated moment definitions

### PR DESCRIPTION
**Pull request by stepancar**
it is available to pass Moment[] to moment.min , moment.max

### CODE REVIEW

**Comment by adidahiya** [comment]
this feature is poorly documented, but looking at [the source](https://github.com/moment/moment/blob/master/src/lib/moment/min-max.js#L35) it looks right. would be great if someone could send a PR to [update moment's docs here](https://github.com/moment/momentjs.com/blob/master/docs/moment/02-get-set/22-min.md)

:+1:

**Comment by galtalmor** [comment]
:+1:

**Comment by stepancar** [comment]
@adidahiya , I created [this pr](https://github.com/moment/momentjs.com/pull/258) for moment docs

**Comment by adidahiya** [comment]
@stepancar nice!

**Comment by horiuchi** [comment]
@stepancar Thanks mate!
@adidahiya @galtalmor Thanks for review!

**Pull request merged**
