### PR TITLE
Revert "🤖 Merge PR #53483 [koa-bodyparser] add ability to strictly type request body by @pkuczynski"

### PR DESCRIPTION
**Pull request by hirochachacha**
This reverts commit 110ceb19ebb7186cd5439f5d15a68b4976b71c93.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53483#issuecomment-858174115
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by pkuczynski — CHANGES_REQUESTED** [review]
I disagree with this revert. `any` is not a type and does not allow a properly override body with koa custom context. You can see the initial reasons behind this change in #52025 and a follow-up PR #53691 trying to fix some issues.

**Comment by hirochachacha** [comment]
@pkuczynski I have no interest in #52025 and its attempt. Personally, I don't think that's so important.
That point is, you deleted the original test and broke the compatibility.
Here is original test code. As you can see, it's a pretty idiomatic code, so I assume the commit is breaking tons of codebase.
```
import Koa = require("koa");
import bodyParser = require("koa-bodyparser");

const app = new Koa();

app.use(bodyParser({ strict: false }));

app.use((ctx) => {
    console.log(ctx.request.body);
    console.log(ctx.request.body.ok);
    console.log(ctx.request.rawBody);
});

app.listen(80);
```

**Comment by pkuczynski** [comment]
>  I have no interest in #52025 and its attempt.

That's not very cooperative, is it?

> Here is original test code. As you can see, it's a pretty idiomatic code, so I assume the commit is breaking tons of codebase.

With the previous setup where `body` was typed as `any`, we were losing the main purpose of TypeScript, which is providing strict types. The original test was indeed removed and replaced with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52025/files#diff-b7154cf138e30d1c7a6d32c6671b37242bd520547cdc08f1a57e65fa9982fb71R15 which allows you to type the request body via koa `CustomContext` on `app.use()`.

Additionally, I am putting back this test in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53691/files#diff-fe4ab7bc6f48c40816bf9008a35aad27e0862a749df86305d3196e96a0803a2aR15

If you check the source code of `koa-bodyparser` you would see that body can be actually `string | Record<string, unknown> | Array<Record<string, unknown>>`. These are the real types. `any` is of course covering all of them, but its not strictly typing which defeats the whole purpose of having typescript.

Additional issue with having `any` is that typing it via `CustomContext` does not work as the intersection of any type with `any` will always result in `any`. 

> I assume the commit is breaking tons of codebase.

You are the second person complaining. Does not sound like a lot to me.

**Comment by hirochachacha** [comment]
If you're able to add a new feature without breaking the compatibility, I would appreciate whatever your attempt.
but this isn't the case, I guess? In fact #52025 looks failed attempt. the commit is merged because it's closed accidentally and re-opened at #53483. So it's more like unfortunate. There're no original author's approval including me.

**Comment by pkuczynski** [comment]
Yeah, it was me who accidentally closed #52025, mentioning this in some other commit. My fault. Yet I did mention it in the   #53483 so anybody could follow the original discussion. Both were open since 26th March, so there was plenty of time to discuss and propose alternative solutions. You can't blame anybody if you didn't react yourself...

**Comment by pkuczynski** [comment]
I am happy to change the proposed solution to anything you suggest as long as it will not fail the current test: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-bodyparser/test/body-typed-with-koa-tests.ts

I already changed it to something less strict in #53691

**Comment by hirochachacha** [comment]
> You can't blame anybody if you didn't react yourself...

So true.

**Comment by pkuczynski** [comment]
@hirochachacha just FYI,  I dbl checked and I do not see any other `body?: any` in any other `koa` packages...

**Comment by pkuczynski** [comment]
@hirochachacha would #53691 solve your issues and doubts? Yes, it would force people to type the body (either via `CustomContext` or using typecast, but this can not be a bad thing, can it?

**Comment by hirochachacha** [comment]
> Yes, it would force people to type the body (either via CustomContext or using typecast, but this can not be a bad thing, can it?

That's what I am complaining

**Comment by pkuczynski** [comment]
> That's what I am complaining

But why? Isn't typing the request body is a good thing?

**Comment by hirochachacha** [comment]
not always. it's more like personal preference to me. So I disagree to enforce that habit on existing users.

**Comment by leumasme** [comment]
Typing the body like this just seems like a pain for no reason - the data is coming from a request, so the format is not guaranteed unless actively checked anyway.
This adds an overhead of effort to basic projects, and most importantly, it breaks all existing code which does not already type the body.
Mainly that last part is absolutely unacceptable, i have had to actively exclude this version of the package from my package.json to prevent my projects from breaking - if this continues in future versions, i will have to lock it to 4.3.0 which would be quite sad.

**Comment by pkuczynski** [comment]
The issue is that if we keep `any` then it is not possible to narrow down the typing using `Koa.Context` as in the test I provided in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-bodyparser/test/body-typed-with-koa-tests.ts.

So far only @hirochachacha and @leumasme complained. That's not really a lot of people and projects as you claim. And if someone want's to be lazy, he can always type it as any explicitly (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53691/files#diff-b2d527dc85c5c1353c007696a9673d8696db55cb4492890c3669e42d2e777272)

**Comment by hirochachacha** [comment]
Yes, presumably, most people will chose  spending 5-10 minutes to change his code instead of complaining here. no surprise.
But, that doesn't mean we have a right to steal their time. I don't understand your sentiment.

**Comment by pkuczynski** [comment]
> Yes, presumably, most people will chose spending 5-10 minutes to change his code instead of complaining here. no surprise. But, that doesn't mean we have a right to steal their time.

Proof, please? I don't see a wave of people complaining that they wasted their time, but I see some people saying that they were already typing it...

**Comment by hirochachacha** [comment]
It's a prediction. no proof.

Anyway, It looks like our conversation reached a dead end.
I don't think we can add new information here.
We both use the words like `some people`, `most people`, `many people` and `few people`, but we both can't provide exact numbers..., perhaps we can use BigQuery to get numbers, but I don't want to that.

So, how about letting a definitelyTyped member to decide? Somehow we can call a one of them.

**Comment by pkuczynski** [comment]
Indeed, we are running circles :(

I think it's a good idea to reach out to the DT team for advice on how to solve this situation.

**Comment by andrewbranch** [comment]
@hirochachacha, can you fix the merge conflicts here? I’m ok with continuing the discussion on #53691 but absent any very strong objections with new arguments being made, I think we should move forward with this revert.

**Comment by hirochachacha** [comment]
@andrewbranch updated. Thank you for your reconciliation.

**Comment by hirochachacha** [comment]
CI failed because of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54323
Somehow CI node hit the wrong cache of old dtslint?

/CC @sandersn

**Comment by andrewbranch** [comment]
Just going to close and reopen to trigger CI on a fresh merge with master

**Pull request merged**
