### PR TITLE
Update placement type for rctooltip

### PR DESCRIPTION
**Pull request by maxbronnikov10**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: << https://www.npmjs.com/package/rc-tooltip>>

### CODE REVIEW

**Comment by rhysd** [comment]
> Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.npmjs.com/package/@types/rc-tooltip>

@maxbronnikov10 Please provide the documentation for the change to confirm your changes are correct.

**Review by rhysd — CHANGES_REQUESTED** [review]
> Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.npmjs.com/package/@types/rc-tooltip>

@maxbronnikov10 Please provide the documentation to confirm your changes are correct. You are misunderstanding what URL should be provided.

**Comment by maxbronnikov10** [comment]
@rhysd  https://www.npmjs.com/package/rc-tooltip

**Review by rhysd — APPROVED** [review]

**Comment by maxbronnikov10** [comment]
Ready to merge

**Pull request merged**
