### PR TITLE
Fix some incorrect types of socket.io.d.ts / node.d.ts.

### PR DESCRIPTION
**Pull request by kanreisa**
Hi,
I fixed some incorrect types of socket.io.d.ts + node.d.ts. ;)

### CODE REVIEW

**Comment by vvakame** [comment]
@progre could you review this PR?

* [ ] node.d.ts
* [ ] socket.io.d.ts
---
note
http://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle

**Comment by progre** [comment]
looks good to me.
in my humble opinion, Socket is inherit from EventEmitter.
i.e.
```
interface Socket extends NodeJS.EventEmitter {
```
what do you think?

**Comment by kanreisa** [comment]
Maybe it will error:


! `EventEmitter#emit(event: string, ...args: any[]) => boolean`
! `Socket#emit(event: string, ...args: any[]) => Socket`

https://github.com/Automattic/socket.io/blob/master/lib/socket.js#L162

**Comment by progre** [comment]
hmm, it's you're right.
this looks good to me. @vvakame

**Comment by vvakame** [comment]
@progre thanks!
@kanreisa thanks mate!

**Pull request merged**
