### PR TITLE
[react] add tests for useState

### PR DESCRIPTION
**Pull request by joehillen**
Add a test case to prevent [this](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/598ffd0b99dcfa511ab6056d9652c99665a7bbe4#r34006320) from happening again.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by ferdaber** [comment]
So how does this pass here but not in the reported cases?

**Comment by joehillen** [comment]
@ferdaber Correct. Here is the test output if I revert your revert:

```
Error: /home/joe/src/DefinitelyTyped/types/react/test/hooks.tsx:217:15
ERROR: 217:15  expect  TypeScript@next compile error: 
Parameter 'r' implicitly has an 'any' type.
ERROR: 217:15  expect  TypeScript@next compile error: 
Argument of type '(r: any) => boolean' is not assignable to parameter of type 'boolean | ((prevState: false) => false) | ((prevState: true) => true)'.
  Type '(r: any) => boolean' is not assignable to type '(prevState: false) => false'.
    Type 'boolean' is not assignable to type 'false'.

    at /home/joe/src/DefinitelyTyped/node_modules/dtslint/bin/index.js:190:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/joe/src/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DanielRosenwasser** [comment]
Is it effectively just a difference between versions? (CC @weswigham)

**Comment by joehillen** [comment]
I don't understand your question. Different versions of what?

**Comment by joehillen** [comment]
To clarify, this test case is a common pattern in my React codebase and is what started returning an error when I updated @types/react and TS 3.5 yesterday. I suspect the error has to do with both the bad [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/598ffd0b99dcfa511ab6056d9652c99665a7bbe4) and the [smarter type unions change](https://github.com/microsoft/TypeScript/pull/30779) introduced in 3.5.

What I think happened is `(prevState: boolean) => boolean` was widened to `((prevState: false) => false) | ((prevState: true) => true)`, which doesn't make sense because why would you ever call `setState` but not change the value.

Because it is such a common pattern in React, I thought it made an obvious test case.

**Pull request merged**
