### PR TITLE
[seneca] Add generic types to `add` and `act` methods

### PR DESCRIPTION
**Pull request by kevynb**
Add Generic types to the `add` and `act` methods, safety first! 😄 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://senecajs.org/api
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by kevynb** [comment]
@psnider if you have some time to have a look

**Comment by psnider** [comment]
Sorry, I no longer use seneca...

**Comment by kevynb** [comment]
Do you know who I could mention instead to get this MR approved?

Also, I did not make a lot of changes, so your experience might be enough ;)

**Comment by psnider** [comment]
I think that existing calls to add() and act() should still compile.
It looks like the default types in your templates should do the job,
but could you please add a few calls to the test file that don't use template types,
to make sure existing code still compiles?

**Comment by kevynb** [comment]
Well, aren't the tests you wrote at the time enough? They seem to fulfill that purpose to me, but I might be wrong

**Comment by psnider** [comment]
You are right. I only looked at the PR in diffs mode and missed the existing tests...

**Comment by psnider** [comment]
👍

**Comment by kevynb** [comment]
Great, thanks!

**Pull request merged**
