### PR TITLE
Add the EscapeLatexOptions parameter of the lescape function of type {   preserveFormatting?: boolean;   escapeMapFn?: (defaultEscapes: any, formattingEscapes: any) => any; }

### PR DESCRIPTION
**Pull request by xiaoxizi2303**
Add the EscapeLatexOptions parameter of the lescape function of type {
  preserveFormatting?: boolean;
  escapeMapFn?: (defaultEscapes: any, formattingEscapes: any) => any;
}

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/escape-latex/escape-latex-tests.ts
1. types/escape-latex/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cb660fe671a5a3abdfef27d8f136d185d3f19c1d
</p>

**Comment by xiaoxizi2303** [comment]
Please review this PR.

**Comment by xiaoxizi2303** [comment]
> ## Formatting
> The following files are not formatted:
> 
> 1. types/escape-latex/escape-latex-tests.ts
> 2. types/escape-latex/index.d.ts
> 
> Consider running `pnpm dprint fmt` on these files to make review easier.
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [cb660fe](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/cb660fe671a5a3abdfef27d8f136d185d3f19c1d)

Modified. Please review this PR.

**Review by olsio — APPROVED** [review]

**Comment by xiaoxizi2303** [comment]
Ready to merge

**Pull request merged**
