### PR TITLE
[core-js] Added support for native Date interface implementations

### PR DESCRIPTION
**Pull request by ChristianGalla**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/54841
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
I'm a little confused - don't these changes make two properties (`formatUTC` and `format`) optional? Could you share the rationale for that?

**Comment by ChristianGalla** [comment]
Yes, sure.
Changing these properties so they are optional is everything needed:

There are multiple ways someone can use the date object.
The usual way is to call `new Date()` to get the current date. If you need additional methods in JavaScript / TypeScript, you can extend the Date prototype (like core-js does) or extend it (`class MyDate extends Date`). This is not affected by my proposed change.

It is also possible to use a class like an interface (`class MyDate implements Date`). This way it is required to implement all methods and properties that are not optional, or a compiler error is thrown (`TS2420: Class MyDate incorrectly implements interface Date`). For example, the library [kendo-angular uses this way to create its own Date implementation](https://github.com/telerik/kendo-angular/issues/2706#issuecomment-889700632). Usually, someone only implements the default (ECMAScript) methods because any other methods that were added to the default Date class by other libraries may not be known (like `formatUTC` and `format` added by core-js).

If core-js and another library implementing only the ECMAScript methods of the Date object are used at the same time, the mentioned compiler exception is thrown. If the methods are optional, no compiler exception is thrown.
To test this, I have added [a default Date implementation to the test file](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54902/files#diff-45e92b49558f711d5a4b2e6e17438de090a5774b8b05c9c5ec27491954dc7c16R472).

**Review by johnnyreilly — APPROVED** [review]
Nice work!

**Comment by ChristianGalla** [comment]
Ready to merge

**Pull request merged**
