### PR TITLE
[react-native]fix raw event arg ignored error in 'index.d.ts'.

### PR DESCRIPTION
**Pull request by Yiiu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by alloy** [comment]
Can you please provide a link to either documentation or the source that declares this typing?

**Comment by Yiiu** [comment]
@alloy [react-native](http://facebook.github.io/react-native/docs/animated.html#event) 
demo:
```js
 onPanResponderMove: Animated.event([
   null,                // raw event arg ignored
   {dx: this._panX},    // gestureState arg
 ])
```

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by DanielRosenwasser** [comment]
Do we believe this is good to merge in? Maybe `Mapping` is the wrong place to include `null`, but the array passed into `event` might accept them?

**Comment by alloy** [comment]
Back from vacation! Thanks for the patience.

Agreed, that’s actually what the RN source does too:

* https://github.com/facebook/react-native/blob/28d5d6baf1e6ac52e8672a653f56c3898e4e11d2/Libraries/Animated/src/AnimatedImplementation.js#L498
* https://github.com/facebook/react-native/blob/28d5d6baf1e6ac52e8672a653f56c3898e4e11d2/Libraries/Animated/src/AnimatedEvent.js#L22

@Yiiu Can you instead change the `event` signature to use `Array<Mapping | null>`?

**Comment by Yiiu** [comment]
@alloy @DanielRosenwasser  sure, thanks.

**Comment by alloy** [comment]
Ace. Thanks!

**Pull request merged**
