### PR TITLE
Added react-native-easy-toast

### PR DESCRIPTION
**Pull request by cavarzan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@cavarzan 
Q: Is that intended to land here as the referenced package already ships it own types specified in the `package.json`?

**Comment by cavarzan** [comment]
The current library are not being updated for a long time. There is a lot
of PRs fixing the typings but none was merged. The library is stable but
seems to be abandoned by the owner.

Deividi Cavarzan

Em ter, 21 de jan de 2020 19:07, Piotr Błażejewicz (Peter Blazejewicz) <
notifications@github.com> escreveu:

**Review by peterblazejewicz — APPROVED** [review]
LGTM
see also comment here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41773#issuecomment-576908208

@cavarzan Thanks for contribution!

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
@cavarzan I don't think this package will have the effect that you really want.
If a user has `react-native-easy-toast` and `@types/react-native-easy-toast` installed, the types from the original package will be chosen over those from the `@types` package.

I would suggest forking the original project if it's unmaintained and there are improvements that should be made.

**Comment by cavarzan** [comment]
@uniqueiniquity  OK! I didn't knew that the original package definition has a higher priority rather than `@types` packages. I've considered as override definition just like I use using a local `d.ts` files in the working project folder. Unfortunately, I was unable to override as a local type definition, so I create this PR to possibly fix this.
Indeed the fork and republish the library as a secondary option seems to be a better solution, since we didn't have any updates from the current owner and the MIT license allow the code usage (AFAIK).
Thanks for the observation. I won't delete this PR and let you take the action if you agree.

**Comment by uniqueiniquity** [comment]
Makes sense to me. I'll go ahead and close this PR.

**Pull request closed without merging**
