### PR TITLE
defs + tests from examples

### PR DESCRIPTION
**Pull request by pocesar**
Typings for https://github.com/ivanakimov/hashids.node.js

### CODE REVIEW

**Comment by vvakame** [comment]
*hashids/hashids.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/hashids
  * http://bower.io/search/?q=hashids
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (hashids/hashids-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@pocesar thank you for your contributions.
please rename hashids/hashids-test.ts to hashids/hashids-tests.ts

**Comment by pocesar** [comment]
done

**Comment by vvakame** [comment]
@pocesar thanks mate!

**Pull request merged**
