### PR TITLE
[react] Add types for React 16.3 context api

### PR DESCRIPTION
**Pull request by apexskier**
https://reactjs.org/docs/context.html#api

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactjs.org/docs/context.html#api
- [ ] Increase the version number in the header if appropriate.
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by apexskier** [comment]
I'm not sure why the build is failing. It's failing in a different package (`victory`) that depends on React, but the specific issue isn't related to my change.

**Comment by Pajn** [comment]
There already is an open PR for this that also implements API surface missing in this one #24509

**Comment by FredyC** [comment]
I suggest closing this, it's not even correct since it's requiring value to `createContext` while it's optional. See linked #24509 for discussion.

**Comment by apexskier** [comment]
Sorry, I didn't see #24509 when I searched before opening this. Thanks for the notes!

**Pull request closed without merging**
