### PR TITLE
added gridStrokeWidth and gridLineColor variables to morris.js

### PR DESCRIPTION
**Pull request by csotomon**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by csotomon** [comment]
Hi, do you have some new about this pull request?

**Comment by vvakame** [comment]
*morris.js/index.d.ts*

to authors (@mareek @sindilevich). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
sorry for late.
please ping me again when We can't get response from author after 3 days. I'll merge this PR.

**Comment by mareek** [comment]
@csotomon thanks for adding the missing properties. 
Can you add the default values for gridStrokeWidth (0.5) and gridLineColor ('#aaa') in the comments ?

**Comment by csotomon** [comment]
@mareek Done

**Comment by mareek** [comment]
@csotomon  Thanks

**Pull request merged**
