### PR TITLE
ionic framework: static ionic.Platform utility

### PR DESCRIPTION
**Pull request by julienevano**
Add the static `ionic.Platform` utility according to the API documentation (http://ionicframework.com/docs/api/utility/ionic.Platform/).

### CODE REVIEW

**Comment by vvakame** [comment]
*ionic/ionic.d.ts*

to author(@spencerwi). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by spencerwi** [comment]
@julienevano I would recommend allowing `IonicStatic.Platform.ready(callback)` accept a `()=>any`, as a convenience so that I can plug in any side-effectful callbacks that may or may not return values (knowing that the value will be thrown away in this particular use-case).

It's not a huge deal, as you could just wrap your callback in a lambda that calls it and doesn't return anything, but it's a convenience/ease-of-use thing.

**Comment by julienevano** [comment]
@spencerwi Thank you for your feedback. Please find the update in my last commit.

**Comment by spencerwi** [comment]
@julienevano Good stuff, thanks! Nice work adding tests for both cases too :+1:

**Comment by julienevano** [comment]
@vvakame Could you merge it as @spencerwi approved the PR? Thank you :-)

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
