### PR TITLE
[ssh2] add package.json

### PR DESCRIPTION
**Pull request by roikoren755**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

#49274 added new types to `ssh2-streams`, and used those types in this package. This means that the current version of `@types/ssh2` doesn't work with older versions of `@types/ssh2-streams`.

Basing off of #50554, I want to add an explicit dependency on `@types/ssh2-streams@^0.1.8` (The version that added the new types).

I will open a PR in `DefinitelyTyped-tools` to add `@types/ssh2-streams` to `allowedPackageJsonDependencies.txt` after opening this PR.

### CODE REVIEW

**Review by bragle — CHANGES_REQUESTED** [review]
`@ssh2-streams` is not a package that exists. If you want to add `@types/ssh2-streams`, that can be done with path mapping and should not be done in `package.json` according to [these logs](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/bad69448f786142c7b1dc4a0a8165c7f36d7a8d6/checks?check_suite_id=3456505743).

**Comment by roikoren755** [comment]
> `@ssh2-streams` is not a package that exists. If you want to add `@types/ssh2-streams`, that can be done with path mapping and should not be done in `package.json` according to [these logs](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/bad69448f786142c7b1dc4a0a8165c7f36d7a8d6/checks?check_suite_id=3456505743).

😪 that what happens when you try and copy-paste...
I changed the `package.json` to depend on `@types/ssh2-streams`.

Like in the PR I mentioned (#50554), I want to add an explicit dependency on a minimum version of `@types/ssh2-streams`.
I recently tried to update `@types/ssh2` in one of my projects, and my `yarn.lock` had resolved `@types/ssh2-streams@*` (which this package will depend on without my PR) to v0.1.7. After updating `@types/ssh2` from v0.5.45 to v0.5.47, my build started failing, because the new version of `@types/ssh2` used `WriteFileOptions` from `@types/ssh2-streams`, but that interface doesn't exist in v0.1.7.

I did manage to fix the issue by forcing yarn to update `@types/ssh2-streams`, and so this PR isn't strictly necessary, for me or in general. But for easier upgrading, I think this is a correct approach.

In broader terms, I think DefinitelyTyped should provide a way for type packages to specify a minimum version of `@types/*` dependencies, or a range of versions or something, as this is an issue I came across more than once before...

**Comment by bragle** [comment]
@roikoren755 I still do not believe that this is the correct way of solving your issue, as the types in the current version of `@types/ssh-streams` are the correct ones. According to [the readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#packagejson), you should only add a `@types`-package in `package.json` if your package needs to depend on old typings (which is not the case here).

I'm not going to sign off on this, but if you still think your solution is the correct one, someone with more DT experience than me should probably take a look at this.

**Comment by roikoren755** [comment]
@bragle I appreciate your feedback.
Like I said, I already bypassed this issue. If this isn't the right way, I'm OK with closing this issue :)

**Comment by sandersn** [comment]
It would be nice for Definitely Typed to allow specifying inter-DT dependencies instead of inferring them. @roikoren755 Right now the intended way is for users to know which versions go together and, unlike other packages from npm, specify exact versions in *package.json*.

Forcing the consumer of the `@types` package to manage versions instead of the author of the package is certainly simpler for Definitely Typed, though, and this problem happens to a fairly small set of packages.

@orta do you have an opinion on this, particularly on where responsibility for deciding versions of dependencies *should* fall?

**Pull request closed without merging**
