### PR TITLE
[@types/stripe-v3] hideIcon is no more a variable of ElementsOptions as per Stripe docs

### PR DESCRIPTION
**Pull request by madhavan-sundararaj**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://stripe.com/docs/js/elements_object/create_element?type=cardNumber>>
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Review by mastacheata — APPROVED** [review]
Seems to work  and is in line with what the docs say.

**Review by galuszkak — CHANGES_REQUESTED** [review]
This is not in line with documentation.

If you create `card` element, documentation says that there is `hideIcon` property. If `cardNumber` there is `showIcon` property. I think in this case we would have to have both properties in definitions.

**Comment by galuszkak** [comment]
Screenshot as a proof.
Stripe__JavaScript_SDK_documentation___reference

**Comment by maddy2894** [comment]
Hi @galuszkak, sorry for missing that. My latest commit puts back hideIcon, I think it will be best if we keep both the varaibles.

**Review by mastacheata — APPROVED** [review]

**Review by galuszkak — CHANGES_REQUESTED** [review]
@maddy2894 shouldn't `react-stripe-elements` also have both?

**Comment by maddy2894** [comment]
@galuszkak That is a test file, I don’t think it matters much.

**Review by galuszkak — APPROVED** [review]
@maddy2894 oh, didn't notice that. Thanks for explaining. Approving then.

**Pull request merged**
