### PR TITLE
added IRouterComponentOptions ($routeConfig and $canActivate)

### PR DESCRIPTION
**Pull request by davidreher**
the typings were remove by @mmiszy in 65347efe70de2c2b9cb29050b5a709d89ef77cef. This commit adds the options as optional parameters to the component router typings.

### CODE REVIEW

**Comment by mhegazy** [comment]
@davidreher can you refresh the PR.

**Comment by davidreher** [comment]
the master build is failing. It was not fault :( 

Shall I fix it or is someone else looking into this?

**Comment by mmiszy** [comment]
@davidreher The Component Router for AngularJS is now deprecated and not recommended to use. In the light of this I believe these typings should not be merged.

**Comment by davidreher** [comment]
it is ok for the moment. Hopefully they will reintroduce the component router again ...

**Pull request closed without merging**
