### PR TITLE
fix(node): add `process.versions.pnp` property

### PR DESCRIPTION
**Pull request by SimenB**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://yarnpkg.com/advanced/pnpapi#processversionspnp
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

/cc @arcanis do you think this makes sense?

### CODE REVIEW

**Comment by arcanis** [comment]
I personally think it really makes sense, but it was rejected a year ago (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37754). May be worth re-evaluating?

Another option would be to reapply https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38800, which extends the interface if you depend on `@types/pnpapi` (which is likely something that you need anyway if you rely on `process.versions.pnp`).

**Comment by SimenB** [comment]
Ah, didn't find that one when searching - odd!

> Another option would be to reapply #38800, which extends the interface if you depend on `@types/pnpapi` (which is likely something that you need anyway if you rely on `process.versions.pnp`).

In my specific case (Jest) we don't depend on that type def. Could add it of course. Right now we have this: https://github.com/facebook/jest/blob/80985ede99983190ebb2debc88a3f1f32a19434b/packages/jest-resolve/src/defaultResolver.ts#L25-L32

**Review by ExE-Boss — APPROVED** [review]

**Comment by ExE-Boss** [comment]
It might also be a good idea to have `ProcessVersions` extend `Dict<string>`.

**Comment by SimenB** [comment]
Seeing as the last PR was rejected, let's wait and see what other maintainers say so we avoid stepping on any toes 🙂

**Comment by Flarna** [comment]
Personally I think the solution via `NodeJS.Dict<string>` is better otherwise me may end up in an unnumbered list of optional elements added in node definitions which are not mentioned at all in nodejs docs.

Anyhow, I have no strong opinion in this therefore I will for sure not block this PR.

**Comment by ExE-Boss** [comment]
I agree that extending `NodeJS.Dict<string>` and doing this in `@types/pnpapi` is probably better.

**Review by a-tarasyuk — APPROVED** [review]

**Review by r3nya — APPROVED** [review]

**Comment by elibarzilay** [comment]
@SimenB: should this be closed or merged?

**Comment by ExE-Boss** [comment]
I’m adding this to `@types/pnpapi` in <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47107>.

**Comment by SimenB** [comment]
I like it 👍

**Pull request closed without merging**
