### PR TITLE
Support square-connect@3.x API typings

### PR DESCRIPTION
**Pull request by ddimitrioglo**
All recommendations are fulfilled.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/square/connect-nodejs-sdk#documentation-for-api-endpoints
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Nican** [comment]
Can you please remove me from the list of maintainers?

**Comment by ddimitrioglo** [comment]
@Nican will do, sorry

**Comment by SimonSchick** [comment]
You probably want to create a `v3` folder for this instead, would make a much cleaner diff and allows updating v2 typings just in case.

**Comment by ddimitrioglo** [comment]
@SimonSchick First of all I've just removed `v1` typings as it's not updating, second of all the API itself is still `/v2` but as Square released a big change with a lot of deprecations, they released v3 version of npm package as it comes with breaking changes.

So, the answer is no, I do not want to keep v1 related types here.

P.S. Also, I'm a bit confused how can I use typings from v3 folder after installing `@types/square-connect`

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
@ddimitrioglo I agree with @SimonSchick; it's not clear to me that they are done updating v2, despite having released v3.

To handle this situation, we recommend following the instructions [in the README](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) for moving the existing content to a `v2` subfolder.

Thanks so much!

**Comment by ddimitrioglo** [comment]
@uniqueiniquity I'm just following Square versioning.

* npm version is 3 https://www.npmjs.com/package/square-connect
* snippet from documentation: 

```
curl https://connect.squareup.com/v2/payments \
  -H 'Square-Version: 2020-03-25' \
  -H 'Authorization: Bearer ACCESS_TOKEN' \
  -H 'Content-Type: application/json'
```

They just deprecated a lot of stuff in their SDK - not API, that's why I'm doing the same

**Review by uniqueiniquity — APPROVED** [review]

**Pull request merged**
