### PR TITLE
Added definitions for jQuery.qrcode. Closes #6292

### LINKED ISSUE #6292: Typedef file for Jquery-QRCode source
Hi,

Any chance for supplying typescript typedef file for Jquery-QRCode source code?

Thanks,
Galia

### PR DESCRIPTION
**Pull request by danmana**

### CODE REVIEW

**Comment by vvakame** [comment]
#6292

**Comment by vvakame** [comment]
*jquery.qrcode/jquery.qrcode.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jquery.qrcode
  * http://bower.io/search/?q=jquery.qrcode
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jquery.qrcode/jquery.qrcode-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
https://github.com/lrsjng/jquery-qrcode/blob/master/package.json#L2
please rename jquery.qrcode/jquery.qrcode.d.ts to jquery-qrcode/jquery-qrcode.d.ts

**Comment by danmana** [comment]
Hi, I'm not sure what I should do about the naming ... 

I mean, yes, the project has a package.json file with the naming "jquery-qrcode", but it's not actually published to npm (under any name).  
It is however published in bower under [jquery.qrcode](http://bower.io/search/?q=jquery.qrcode), and to add to the confusion there is another entry in bower named [jquery-qrcode](http://bower.io/search/?q=jquery-qrcode) which is a totally different plugin.

Even more confusing is that this repo seems to have been renamed at one point [from jquery.qrcode to jquery-qrcode](https://github.com/lrsjng/jquery-qrcode/commit/05877827607e5bb0b728505c0b2487261c911a3f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R2). I guess the author renamed the project, then realised that the bower name was taken, and [took it offline](https://github.com/lrsjng/jquery-qrcode/commit/04acf23c8c4ef0ca90a6a9af295abdb0d7759fc7), only to be added back by [someone else](https://github.com/Gerhut/jquery-qrcode/commit/eb192515108e511d66e98324c25b8124269735bc#diff-0a08a7565aba4405282251491979bb6bR2)

So taking this into consideration I figured I'll add it with the name it is published in bower, since I guess that's where people are likely to get it from.

LOL, this is such a mess :))

If you think it's better to rename it, then I will :)

**Comment by vvakame** [comment]
okay, i understand. it merged! thanks.

**Comment by danmana** [comment]
thanks :)

**Pull request merged**
