### PR TITLE
Updates types for Recurly.js v4.26.0

### PR DESCRIPTION
**Pull request by recurly-integrations**
# Updates types for Recurly.js v4.26.0

View the full recurly-js release [here](https://github.com/recurly/recurly-js/releases/tag/v4.26.0)

Note: This is an automated pull request. For more info, see the [Recurly.js](https://github.com/recurly/recurly-js) repository or [documentation](https://developers.recurly.com/reference/recurly-js/index.html).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/recurly__recurly-js/index.d.ts
1. types/recurly__recurly-js/lib/gift-card.d.ts
1. types/recurly__recurly-js/lib/token.d.ts
1. types/recurly__recurly-js/lib/paypal.d.ts
1. types/recurly__recurly-js/lib/3d-secure.d.ts

<details>
<summary>as well as these 34 other files...</summary>
<p>types/recurly__recurly-js/lib/configure.d.ts, types/recurly__recurly-js/lib/alternative-payment-methods.d.ts, types/recurly__recurly-js/lib/recurly.d.ts, types/recurly__recurly-js/lib/validate.d.ts, types/recurly__recurly-js/lib/elements.d.ts, types/recurly__recurly-js/lib/emitter.d.ts, types/recurly__recurly-js/lib/bank-redirect.d.ts, types/recurly__recurly-js/lib/address.d.ts, types/recurly__recurly-js/lib/error.d.ts, types/recurly__recurly-js/lib/bank-account.d.ts, types/recurly__recurly-js/lib/adyen.d.ts, types/recurly__recurly-js/test/configure.ts, types/recurly__recurly-js/test/recurly-error.ts, types/recurly__recurly-js/test/adyen.ts, types/recurly__recurly-js/test/elements.ts, types/recurly__recurly-js/test/google-pay.ts, types/recurly__recurly-js/test/3d-secure.ts, types/recurly__recurly-js/test/bank-account.ts, types/recurly__recurly-js/test/validate.ts, types/recurly__recurly-js/test/apple-pay.ts, types/recurly__recurly-js/test/paypal.ts, types/recurly__recurly-js/test/gift-card.ts, types/recurly__recurly-js/lib/google-pay/native.d.ts, types/recurly__recurly-js/lib/google-pay/index.d.ts, types/recurly__recurly-js/lib/pricing/promise.d.ts, types/recurly__recurly-js/lib/pricing/checkout.d.ts, types/recurly__recurly-js/lib/pricing/index.d.ts, types/recurly__recurly-js/lib/pricing/subscription.d.ts, types/recurly__recurly-js/lib/apple-pay/native.d.ts, types/recurly__recurly-js/lib/apple-pay/index.d.ts, types/recurly__recurly-js/test/pricing/checkout.ts, types/recurly__recurly-js/test/pricing/subscription.ts, types/recurly__recurly-js/test/token/hosted-field.ts, types/recurly__recurly-js/test/token/elements.ts</p>
</details>

Consider running `npx dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d0b60e05263b16651e366b0403be965a85c81822
</p>

**Comment by jakebailey** [comment]
We recently reformatted the repo using dprint and it's now fixed on merge; I guess we missed that these files were autogenerated externally. I'll add an exception, I guess.

**Comment by jakebailey** [comment]
FWIW it'd be helpful if these types had some sort of "DO NOT EDIT" notice at the top to make it clear that they are generated. Otherwise we may merge people's changes to them.

**Comment by jakebailey** [comment]
There are now three of these PRs open; is there someone who should be approving and merging them? Should we always merge them? Something else? https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Arecurly-integrations

**Comment by MysteryBlokHed** [comment]
It looks like older PR's such as #65937 were merged by chrissrogers (the typings owner)

#66861 was also approved, but he hasn't commented "Ready to merge"

**Review by chrissrogers — APPROVED** [review]

**Comment by chrissrogers** [comment]
Ready to merge

**Pull request merged**
