### PR TITLE
leaflet.locatecontrol - remove useless package.json

### PR DESCRIPTION
**Pull request by DenisCarriere**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Similar to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15478

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like Travis found a lot of lint errors.

**Comment by DenisCarriere** [comment]
@sandersn Strange that it passed the linting the first time a 2 days ago https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15455
The linter must of been updated.

**Comment by sandersn** [comment]
Yes, I think @andy-ms is updating the linter right now and also updated it yesterday.

**Comment by DenisCarriere** [comment]
👍 Great stuff! I'm all for linting, my last commit should have resolved the linting issue.

**Pull request merged**
