### PR TITLE
[google-apps-script] Added missing `.build()` definitions to the validation builders

### PR DESCRIPTION
**Pull request by TimCreasman**
* Added missing `.build()` definitions to the validation builders.
    * `CheckboxGridValidationBuilder`
    * `CheckboxValidationBuilder` 
    * `GridValidationBuilder`
    * `ParagraphTextValidationBuilder`
    * `TextValidationBuilder`
    * The `build` method was already on the `QuizFeedbackBuilder`
* Fixed a typo in the `ParagraphTextValidationBuilder` comment doc.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Documentation](https://developers.google.com/apps-script/reference/forms/text-validation-builder)
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~

### CODE REVIEW

**Comment by TimCreasman** [comment]
I didn't see the right place to add a test for this fix. The `google-apps-script-tests.ts` file seemed too generalized. If you point me in the right direction I am happy to add the tests 👍

**Comment by jakebailey** [comment]
I see some lines in that file that do call `build`; can you do something similar?

**Review by mtgto — APPROVED** [review]
Thank you for your contribution. LGTM. 🙆‍♂️ 
BTW, If you have a motivation to write test, I welcome you write it in eof of google-apps-script-tests.ts. ex:
```ts
FormApp.createTextValidation()
  .setHelpText('Input was not a number between 1 and 100.')
  .requireNumberBetween(1, 100)
  .build();
```

P.S. I also Send Feedback to document of Google Apps Script about lack of description of build methods.

**Comment by TimCreasman** [comment]
@mtgto, @jakebailey Awesome! Thanks for the feedback and guidance. Just added the tests, and I also sent feedback to the google apps script documentation as well. Thank you! 👍

**Review by mtgto — APPROVED** [review]
Thanks you again 👍

**Comment by TimCreasman** [comment]
Ready to merge

**Pull request merged**
