### PR TITLE
Fix i18next default export

### PR DESCRIPTION
**Pull request by zakjan**
See the discussion at https://github.com/aurelia/i18n/issues/56

### CODE REVIEW

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by zakjan** [comment]
@mhegazy Fixed.

**Comment by mxl** [comment]
👍

**Comment by mxl** [comment]
@zakjan Did you tested this fix with real-world application? I'm getting `Cannot read property 'init' of undefined` error:
```
import i18next from 'i18next';
i18next.init({});
```

I have babel -> browserify setup and tsconfig.js:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "jsx": "react",
    "sortOutput": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true
  }
}
```

**Comment by zakjan** [comment]
Yes, I tested it with a real app. The config is:

```
  "compilerOptions": {
    "rootDir": "src/",
    "sourceMap": false,
    "target": "es5",
    "module": "system",
    "declaration": false,
    "noImplicitAny": true,
    "noResolve": true,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
```

**Pull request merged**
