### PR TITLE
[js-yaml] Update types for 4.0 release

### PR DESCRIPTION
**Pull request by ArmaanT**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [git diff of 4.0.0](https://github.com/nodeca/js-yaml/compare/3.14.0...4.0.0) and [changelog of 4.0.0](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#400---2021-01-03)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I tried to separate each change into individual commits to better organize all the changes made in this release.

### CODE REVIEW

**Comment by ArmaanT** [comment]
It looks like checks are failing because a dependant package `convict` uses the method `safeLoad` which was removed in js-yaml 4.0.0. I can update that test to use `load`, but I'm not sure if that should be done in the PR since it's not related to js-yaml itself.

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## js-yaml ([<kbd>unpkg</kbd>](https://unpkg.com/browse/js-yaml@latest/))
was missing the following properties:
1. safeLoad
1. safeLoadAll
1. safeDump
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9ca9140e8708e6088ea4686c1a13f77984d7d0df
</p>

**Review by petermetz — APPROVED** [review]
Haven't tested it myself, but LGTM.

Thank you very much @ArmaanT

**Review by andrewbranch — APPROVED** [review]

**Comment by ArmaanT** [comment]
Ready to merge

**Comment by atwright147** [comment]
Why were the safe* methods removed? They are still present in js-yaml's docs and in the source code

**Comment by ArmaanT** [comment]
@atwright147 can you let me know where you still see the safe methods? The [source code](https://github.com/nodeca/js-yaml/blob/ee74ce4b4800282b2f23b776be7dc95dfe34db1c/index.js#L27) and the [v4 migration docs](https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md) both say those methods were removed.

**Pull request merged**
