### PR TITLE
[extensible-duck] Export Duck class as default to match library

### PR DESCRIPTION
**Pull request by nossbigg**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <[link to src](https://github.com/investtools/extensible-duck/blob/9a103ff83d7e98f1ea8b2b87114d7c87e5066333/src/extensible-duck.js#L153)>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by nossbigg** [comment]
Anyone had time to look at it? 👀

**Review by amcasey — APPROVED** [review]

**Comment by nossbigg** [comment]
Ready to merge

**Comment by nossbigg** [comment]
@amcasey thanks for the review!

**Comment by jagodin** [comment]
Hey @nossbigg , thanks for these great typings! I've been using them in my latest project. One thing though, I was wondering if you could add support for the `extend` method (see [here](https://github.com/investtools/extensible-duck/tree/9a103ff83d7e98f1ea8b2b87114d7c87e5066333#extending-ducks))?

**Pull request merged**
