### PR TITLE
Add Google Earth type definitions

### PR DESCRIPTION
**Pull request by icholy**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
You do realize that this API will be shut down at the end of 2016 ? Per the docs referenced in the heading of your typings file.

**Comment by icholy** [comment]
@paulvanbrenk I'm using Google Earth Enterprise. It's self-hosted and will keep working.

**Comment by paulvanbrenk** [comment]
Ok.. I noticed there are a bunch of empty classes and enums that are exported, is that correct, and can you add a comment in those cases?

**Comment by icholy** [comment]
@paulvanbrenk the base classes need to say, but if you want I can change the enums:

``` ts
// from this
export enum GEEventPhaseEnum {}

// to this
export type GEEventPhaseEnum = number; 
```

**Comment by icholy** [comment]
@paulvanbrenk I've added comments to all the enum types.

**Pull request merged**
