### PR TITLE
[mongoose] Use mongodb.UpdateQuery type

### PR DESCRIPTION
**Pull request by avaly**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

(PS: I split the huge tests file into several smaller ones)

I believe this change qualifies for a semver major bump of this package. However reading through this [section](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library), I don't see how I can mark the PR as a "breaking change". I'd appreciate any input from the repository's maintainers.

### CODE REVIEW

**Comment by avaly** [comment]
Please see my comment in the PR description regarding breaking changes, before merging this.

**Comment by armanio123** [comment]
The definition version should match the library version as well. If the definition is being corrected, even if it's a breaking change, should be ok IMO. Anyway the process will auto-increase the patch version if people still want to deploy the previous one.

I'll let a couple of days for any of the owners to jump in before merging.

**Comment by armanio123** [comment]
@avaly so is this the correct version and does this PR is ready to be merged?

**Comment by avaly** [comment]
@armanio123 yes, it's ready to be merged.

**Pull request merged**
