### PR TITLE
threejs - use correct skinWeights and skinIndices types

### PR DESCRIPTION
**Pull request by hellochar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://threejs.org/docs/index.html#api/core/Geometry.skinIndices
- [x] ~Increase the version number in the header if appropriate.~
- [x] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Review by dhritzkiv — CHANGES_REQUESTED** [review]
Mostly looks good, except for the bones_browser test. It feels too complex. We should only be testing basics, like constructing, accessing, and manipulating bones. No need to actually render the scene, or do work in a loop. See other tests in this project for examples.

**Comment by efokschaner** [comment]
@hellochar Thanks for the PR. It looks good to me.
I'm gonna put some questions for @dhritzkiv here but please do not worry about my feedback for now, let @dhritzkiv make the final call here. If you have thoughts on this, feel free to join the discussion.

@dhritzkiv Almost all the tests in here are/were just ports of examples or unit tests from the threejs repo, similar to what has been done with `bones_browser.ts` in this PR.

It's certainly a bit weird to copy paste all this code in as it immediately becomes forked and then diverges but it does produce broad coverage quickly.

Was there a specific test that doesn't follow this pattern that is a better example you had in mind, i'm looking around the repo and it seems to still mostly be doing this same approach.

Lastly, in case you weren't aware, the tests in DefinitelyTyped do not actually execute, they just have to pass compilation so having `for` loops / rendering will not "cost" anything (other than having a lot of code in the test file that is not specific to the thing being tested).

**Comment by dhritzkiv** [comment]
No specific test that doesn't follow this pattern/ no better example that comes to mind.

Right - totally forgot that the test files are only parsed and not executed.

Still, I think it would be better to strip down the tests to their most basic form - I would imagine 90% of the code in the bones_browser test is unnecessary. Making it simpler will make it more maintainable.

**Comment by efokschaner** [comment]
Cool, I agree we should encourage people to write tests that target the typings, rather than looking like fully functional examples. I probably would accept a review that's following this old pattern until we at least had some examples of "what good looks like" somewhere in the repo already.

**Pull request merged**
