### PR TITLE
[howler] Significant type definition improvements

### PR DESCRIPTION
**Pull request by jrandolf-old**
* Removed `xhrWthCredentials` as this is no longer an option.
* Added the `xhr` option
* Added descriptions to option names
* Renamed some types to match their semantic
* Exported some types for library users

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by orta** [comment]
Looks good to me, I'll approve, which will allow you to self merge, last chance for a review - @xperiments @alien35 @nicholashza @cjurango

**Review by orta — APPROVED** [review]

**Comment by jun-sheaf** [comment]
Ready to merge

**Comment by naranjamecanica** [comment]
I've just updated to the latest types and i'm unable to unsubscribe from all events using something just the event name as an argument, ex: `player.off('fade');` or `player.off('play', undefined, id);`.

The description of howler's `off()` method is:

````
    /**
     * Remove a custom event. Call without parameters to remove all events.
     * @param  {String}   event Event name.
     * @param  {Function} fn    Listener to remove. Leave empty to remove all.
     * @param  {Number}   id    (optional) Only remove events for this sound.
     * @return {Howl}
     */
````

By making callback optional again I'm able to compile again, only thing is I had to remove `off()` because of the linter complaining about `ERROR: 248:70  unified-signatures  This overload and the one on line 240 can be combined into one signature with an optional parameter.`

````
    off(event: 'load', callback?: () => void, id?: number): this;
    off(event: 'loaderror' | 'playerror', callback?: HowlErrorCallback, id?: number): this;
    off(
        event: 'play' | 'end' | 'pause' | 'stop' | 'mute' | 'volume' | 'rate' | 'seek' | 'fade' | 'unlock',
        callback?: HowlCallback,
        id?: number,
    ): this;
    off(event: string, callback?: HowlCallback | HowlErrorCallback, id?: number): this;
````

For a pull request see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45401

**Comment by nquinlan** [comment]
This PR removed two exported functions `HowlerGlobal` and `HowlerStatic`, but only bumped a minor version. Per [the project documentation](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) this breaking change should have been accompanied by major version bump rather than a minor.

I discovered this after I attempted to compile a project that has this as a dependency. The maintainer of that project had a package.json that had the dependency of `@types/howler` @ `^2.1.2`.

I'm not sure how to remedy this at this point, since reverting the changes in a minor version (`2.3`) and then reapplying the changes in a major version (`3.0`) would be its own breaking change. Since this merged PR has been in the wild for three months, it's certain people have used this in their projects @ `2.2`.

@orta, do you have any ideas? Would this topic be better suited for me to create an issue, rather than a comment on a closed PR?

**Comment by nquinlan** [comment]
For the sake of future developers, if you're getting either of the following errors:

```
semantic error TS2304: Cannot find name 'HowlStatic'.
```

```
semantic error TS2304: Cannot find name 'HowlerGlobal'.
```

The current best fix is to update your `package.json` to have the requirement `"@types/howler": "2.1.2"`, locking this package at `2.1.2` rather than having it update to the breaking change at `2.2`

**Comment by orta** [comment]
If it doesn't represent what the JS looks like, I'd recommend adding those back 👍🏻

**Comment by nquinlan** [comment]
@orta, shoot that's the quickest response I've ever gotten on an issue on a major project. You rock!

I'm not super steeped in the Typescript ecosystem, so I think I'm sounding dumb here, but I'm unsure if it does represent what the JS looks like. While I haven't tested, I'd definitely believe that this PR works with the latest version of Howler, it doesn't work with the version on the module I was attempting to compile.

Regardless, I'm still not sure how I'd make the fix with semver without breaking downstream projects.

**Comment by MrGriefs** [comment]
Exporting everything now makes it impossible to reference any Howler type without importing it, it would be preferred for a hybrid of exports instead of exporting on each individual declaration.

Unfortunately, this version and above versions cannot be used in module-less ecosystems mixed with type declarations since this change.

**Pull request merged**
