### PR TITLE
[bugfix/64259] fix IteratableIterator type in MIMEParams/entries()

### PR DESCRIPTION
**Pull request by bbereczky-wecan**
## Description
fix IteratableIterator type in MIMEParams/entries()

## Issue
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64259

### CODE REVIEW

**Comment by Semigradsky** [comment]
Looks like this change should be made in `ts4.8` folder?

**Comment by bbereczky-wecan** [comment]
> Looks like this change should be made in `ts4.8` folder?

Thanks for the tip, I fixed it now.

**Comment by peterblazejewicz** [comment]
@Semigradsky looks OK?

**Comment by bbereczky-wecan** [comment]
@Semigradsky @peterblazejewicz can you please check it?

**Review by peterblazejewicz — APPROVED** [review]
I understand this is to be as backward compatible as possible, even outside of TS window currently tested on DT
LGTM!

**Comment by Semigradsky** [comment]
Ready to merge

**Pull request merged**
