### PR TITLE
Improvement to github-electron: Add AutoUpdater.getFeedURL()

### PR DESCRIPTION
**Pull request by djpereira**
Improvement to existing type definition.
See https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#autoupdatergetfeedurl

### CODE REVIEW

**Comment by miniak** [comment]
@djpereira we prefer full updates with all changes in a new Electron release

**Comment by miniak** [comment]
@djpereira If you don't mind waiting a day or two, I am planning to publish a PR for Electron v1.2.8

**Comment by djpereira** [comment]
@miniak if you already started working on it, I will be happy to wait. Thanks for your help.

**Comment by miniak** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10269

**Pull request closed without merging**
