### PR TITLE
fix(pagejs): export interfaces

### PR DESCRIPTION
**Pull request by peterblazejewicz**
/cc @SnowyCoder

Fixes #55861

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by 43081j** [comment]
were they already accessible at `page.*` after all? e.g. `page.Context` (from a default import). so this'd just be a nice-to-have?

**Comment by peterblazejewicz** [comment]
Yes, I understand. But this is not how people are expecting this (the nature of the issue is muscle-memory for typing `import .. from `, which we do not support.
This one supports:
```
import type { X } from 'page'
```
and with 3.8 we can upgrade to `export type` to make that obvious.

**Review by altano — APPROVED** [review]
looks good to me, thanks

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
