### PR TITLE
fix: 68883 - BindDefinition to support DbType fix

### PR DESCRIPTION
**Pull request by danbeglin**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by connorjayfitzgerald — APPROVED** [review]

**Comment by dhrumit9** [comment]
I think at line 2226 for the interface Lob the read-only type should also be of `DBType | number`

**Comment by dhrumit9** [comment]
Similarly at line 2314 for Metadata interface fetchType property

**Comment by dhrumit9** [comment]
For Advance Queue
ln 2969 payloadType

For BaseDBObject
ln 3087 attributes.type
ln 3095 readonly elementType

**Comment by dannyb648** [comment]
Added those now @dhrumit9 - should patch all those youve mentioned - I really appreciate those spots, thanks!

**Review by connorjayfitzgerald — APPROVED** [review]

**Review by dhrumit9 — APPROVED** [review]

**Comment by dhrumit9** [comment]
Hey @dannyb648, @connorjayfitzgerald, what is the expected timeline for this to be merged/released?

**Comment by RDIL** [comment]
@dhrumit9 it's waiting review from a DT maintainer, so probably some time in the next few days.

**Review by rbuckton — APPROVED** [review]

**Comment by SudevAtST** [comment]
@dannyb648 can you please merge this?
It has been a while since our CI is broken due to this and we have to hold back to `6.2.0` which was last working version.

**Comment by SudevAtST** [comment]
> @dannyb648 can you please merge this? It has been a while since our CI is broken due to this and we have to hold back to `6.2.0` which was last working version.

@connorjayfitzgerald @jacobwheale If @dannyb648 is unavailable, can you please help to get this merged?

**Comment by dhrumit9** [comment]
Hey @dannyb648, it's been almost a month since this was up and still it is not merged. We would really like it to be merged as soon as possible.

Can anyone else help get this merged?
@connorjayfitzgerald @RDIL @rbuckton

**Comment by SudevAtST** [comment]
Ready to merge

**Comment by RDIL** [comment]
@dhrumit9 I hear you, I don't know why it went inactive, but I just sent a request on the TS Discord for a DT maintainer to step in, hopefully they are able to help.

**Comment by dannyb648** [comment]
> Hey @dannyb648, it's been almost a month since this was up and still it is not merged. We would really like it to be merged as soon as possible.
> 
> Can anyone else help get this merged? @connorjayfitzgerald @RDIL @rbuckton

Apologies for the delay guys! Had a bunch of other stuff and this dropped off of the radar!

**Comment by dannyb648** [comment]
Ready to Merge

**Pull request merged**
