### PR TITLE
[Jasmine] Add matchersUtil on jasmine object

### PR DESCRIPTION
**Pull request by barrtender**
Bringing in line with https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js to do testing on custom matchers

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
@barrtender could you please add an example how to use this variable in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/jasmine-tests.ts

so future changes don't accidentally remove/edit this without breaking the tests


apart from that changes look good to me :+1:

**Comment by barrtender** [comment]
@lukas-zech-software 
This test: [jasmine-tests.ts#L906](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/902a364510937e4dd505468be96908b1119fcad5/types/jasmine/jasmine-tests.ts#L906)
Should be using the lowerCamelCase matcherUtils according to the jasmine test for [matchersUtil](https://github.com/jasmine/jasmine/blob/acc8c23bf4779ab3689a2c09b9d3441974dabe93/spec/core/matchers/matchersUtilSpec.js)

I was writing a test at work like theirs and got a TS error, which prompted this PR. I'm not at work so I can't verify with the tests that I had set up. I'm having trouble running the tests in that directory.

`jasmine-ts jasmine-tests.ts` gives an error
`TypeError: jasmine.HtmlReporter is not a constructor`

`tsc jasmine-tests.ts` has a lot of errors like
`jasmine-tests.ts(3,1): error TS2304: Cannot find name 'describe'.`

Can I have explicit testing steps to verify this PR? The [Test](https://github.com/DefinitelyTyped/DefinitelyTyped#test) part of the contribution guide is not very concrete.

**Comment by lukas-zech-software** [comment]
@barrtender 
The test you mentioned uses the *type* `jasmine.MatchersUtil` which starts with uppercase
You introduced a variable `matchersUtil` which is also of this type.

In the test you should also use that variable not only the type.

You can compare that to `clock: jasmine.Clock` direct above your addition
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20771/files#diff-90dbf937fd5064e8c964fe371983ab9bR130
and how it is used in the tests 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/902a364510937e4dd505468be96908b1119fcad5/types/jasmine/jasmine-tests.ts#L785

**Comment by lukas-zech-software** [comment]
to run the tests do not use `tsc jasmine-tests.ts` but `tsc -p ./tsconfig.json` else you will not use the correct compiler configuration

**Comment by barrtender** [comment]
Sorry, yeah I misread the test I was linking to and assumed they were doing the same thing as me.

`tsc` just compiles it, right? How do I actually run the tests?

**Comment by lukas-zech-software** [comment]
@barrtender the compiling is the actual test.
There is nothing like a real jasmine test running as that would be runtime tests while the typings matter only during design time.

The typings are only verified against the compiler.

When the compiler does not complain the typings and the code match and everything is good

The naming is a bit misleading

**Pull request merged**
