### PR TITLE
Highcharts definitions fully updated to v4.1.9.

### LINKED ISSUE #5895: highcharts.d.ts - missing properties in HighchartsPlotBands
The highcharts.d.ts definition is missing a number of properties in the interface HighchartsPlotBands
Based on highcharts API (v 4.1.x) documentation, the interface should be

```typescript
interface HighchartsPlotBands {
    color?: string;
    events?: HighchartsMousePlotEvents;
    from?: number;
    id?: string;
    label?: HighchartsPlotLabel;
    to?: number;
    zIndex?: number;
   
    //missing members
    borderColor?: string;
    borderWidth?: number;
    innerRadius?: number | string;
    outerRadius?: number | string;
    thickness?: number;
}
```

### PR DESCRIPTION
**Pull request by baltie**
This is a pretty big pull request, filling most of the missing gaps and correcting some errors:
- All missing definitions has been added, mostly according to documentation, as well as some that were missing from documentation but found in examples and source code. Definitions are now matching version 4.1.9 of Highcharts.
- Added documentation.
- Added an extensive amount of tests covering most settings and objects.
- Cleaned up the plot options and series options hierarchy.
- Fixes #5895.

### CODE REVIEW

**Comment by baltie** [comment]
@damianog Could you please review my changes? The PR is pretty extensive, but I think the changes are useful and they should fill the gaps in the highcharts definitions as well as correct some errors. I've also tested it against our own codebase using highcharts, and there were no changes needed apart from one place where we used the wrong series options type. Hopefully this will be the case for other users as well.

**Comment by damianog** [comment]
@vvakame  please merge commit 244ad334cc020d4c3b4f04632fa6aa144d82b43a

@baltie :+1: Thanks a lot for the great job. Highcharts API are quite cryptic sometimes.
It seems that Highcharts team hate Ts :(

**Comment by baltie** [comment]
@damianog Thanks! :) Yes, it is a bit cryptic, though I learned a lot about highcharts doing this, things are a bit more clear to me now.

I doubt they hate TS. My take on it is that they started making this library before TS was conceived, they have to be backwards compatible and I have a feeling it's not very high on their priority list to make it more TS friendly. Maybe one day they make their own typings library like rxjs does. :)

**Comment by vvakame** [comment]
thanks all!

**Comment by baltie** [comment]
@vvakame Thanks!

**Comment by baltie** [comment]
Thanks, @agoodwin. I've made a PR for this now. :)

**Pull request merged**
