### PR TITLE
[aws-lambda] feat: Add Source Type Definition for AppSync Resolver

### PR DESCRIPTION
**Pull request by mainawycliffe**
This adds a generic to pass the type for Source object passed to Appsync Resolver. The generic defaults to `Record<"string", unknown>` and hence will be fully backward compatible.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by simonbuchan — CHANGES_REQUESTED** [review]
I'm generally in favor, but I have some small concerns before approving:
* The default type of `source` is now `{ [string]: unknown } | null`, not `{ [string]: any } | null`, which will likely break anyone presently using it. This is probably the only actually blocking concern, the rest is mostly opinion.
* On the other hand, I would expect that you should be able to declare that source is not nullable if it's under your control? Ie. move the `| null` to the parameter default.
* Ideally, you would have a separate test without modifying the existing handler test to show that existing code continues to work. It would only need to test the added properties.
* Adding type parameters means they can't be re-ordered, so in some future addition of parameters it would have to be provided to use them. In particular in my version of this type (that I never got around to adding here) I've needed to type the `info.fieldName`, `info.parentTypeName` (as descriminators) and `identity` but not `source`. As an alternative you can instead export (e.g.) `AppSyncResolverEventWithSource<TArguments, TSource>` and `export type AppSyncResolverEvent<TArguments> = AppSyncResolverEventWithSource<TArguments, { ... }>;`

**Comment by mainawycliffe** [comment]
Yeah, I agree `unkown` will definitely break anyone who was relying with `any`, I will use `any` for now, and leave the debate on whether to switch to `unknown` for the future.

**Comment by mainawycliffe** [comment]
Your idea of `AppSyncResolverEventWithSource` sounds interesting, let me think about it as am a little conflicted but since `TSource` is optional, I don't either way will be much of a problem.

**Review by simonbuchan — APPROVED** [review]
Looks good to me!

**Comment by simonbuchan** [comment]
Yeah, the `...WithSource` is mostly just an approach so that if other parameters are added later they can be in a different order. `TSource` looking at it seems plausible enough.

**Comment by mainawycliffe** [comment]
Ready to merge

**Pull request merged**
