### PR TITLE
added SameSiteStatus to chrome.cookies in Chrome package

### PR DESCRIPTION
**Pull request by jacamera**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/extensions/cookies
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by fredrikhr — CHANGES_REQUESTED** [review]
Please add the `@since Chrome 51.` moniker to the doc comments of the two new properties.

**Review by fredrikhr — APPROVED** [review]
LGTM :+1:

**Comment by sandersn** [comment]
The build break on master is fixed, but this PR still has errors, so I think they're legit this time.

**Comment by spasma** [comment]
@jacamera the Cookie interface should have the 'sameSite' option marked as optional as well

`sameSite?: SameSiteStatus`

**Comment by jacamera** [comment]
@spasma The property is not optional [1]. Are you suggesting to mark it as such since it was introduced in Chrome 51? That version was released back in 2016. I can't imagine anyone programming against that API today. And if they are, shouldn't they just target an earlier version of the NPM @types/chrome package?

[1] https://developer.chrome.com/extensions/cookies#type-Cookie

**Comment by couven92** [comment]
I agree with @jacamera the documentation specifies non optional, therefore it should be non optional.

**Comment by spasma** [comment]
@jacamera You are totally right, I was checking the arguments for the set-method while quick checking. My fault!

**Pull request merged**
