### PR TITLE
React-Bootstrap definitions

### PR DESCRIPTION
**Pull request by walkerburgin**
This is a first pass at type definitions for react-bootstrap. It's almost certainly not complete, but it should be a decent starting point. Hopefully somebody else finds it useful!

### CODE REVIEW

**Comment by vvakame** [comment]
related? #2954 please wait...

**Comment by jjstrat3** [comment]
I'm curious what the hold up on this is?  I'd love to be able to use these definitions in my project with the TSD cli tool, but I guess I'll just have to copy @walkerburgin 's great work into a custom definition file in my project.

**Comment by vvakame** [comment]
*react-bootstrap/react-bootstrap.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/react-bootstrap
  * http://bower.io/search/?q=react-bootstrap
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (react-bootstrap/react-bootstrap-tests.ts or others)
* [ ] pass the Travis-CI test?

**Comment by vvakame** [comment]
okay, I decided to merge.
sorry for late.

**Pull request merged**
