### PR TITLE
added missing type for ReactSelectProps.value

### PR DESCRIPTION
**Pull request by tillwolff**

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by giladgray** [comment]
@T-Wolff can you please link to the source that allows `boolean` values? i can't seem to find it. in fact, i've only found proof of the opposite:

> The `value` property of each option should be set to either a string or a number.

https://github.com/JedWatson/react-select#usage

**Comment by giladgray** [comment]
:-1:

**Comment by T-Wolff** [comment]
Im still on it.. to much todo right now.

I think the documentation isnt uptodate, because i found this on the same page:
https://github.com/JedWatson/react-select#further-options
> value	any	undefined	initial field value

In the code, they check for type boolean:
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L578
_(The param "value" is passed through from props.value)_

I will create a test in react-select-test.tsx
Give me some days for that ;)

**Comment by giladgray** [comment]
huh it's in the code but it's _not_ in the typings for that function https://github.com/JedWatson/react-select/blob/master/src/Select.js#L573.

seems like while it may be supported, it's not encouraged. also `boolean` values for selects just don't make sense. use a checkbox...

**Comment by T-Wolff** [comment]
you're right.. select for a boolean is not the best choise, but that's more a design question. someone (not me) decided to use it this way in our project.. i just wannted to clean up the typescript warnings/errors, because they are killing me every day.

i checked the history of select.js and found this feature request including accepted pullrequest
https://github.com/JedWatson/react-select/issues/546
https://github.com/JedWatson/react-select/pull/1224

**Comment by vvakame** [comment]
:eyes:
can I merge this PR?

**Comment by giladgray** [comment]
:+1:

**Pull request merged**
