### PR TITLE
jQuery failsafe syntax

### PR DESCRIPTION
**Pull request by rdennis**
Adds support for optionally aliasing jQuery in `$(callback)` and `$(document).ready(callback)`.

See [the jQuery API](http://api.jquery.com/jQuery/#jQuery-callback) for usage.

``` javascript
jQuery(function( $ ) {
  // Your code using failsafe $ alias here...
});
/* analogous */
jQuery(document).ready(function( $ ) {
  // Your code using failsafe $ alias here...
});
```

### CODE REVIEW

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
That's great! Could you add a test as well please? (The examples you list in your PR should be fine if you drop them into jquery.d.ts)

**Comment by rdennis** [comment]
Sure there's already a test for the shorthand syntax in the test_jQuery function, but I'll add one for the document.ready version.

**Comment by johnnyreilly** [comment]
Thanks

**Comment by rdennis** [comment]
The tests have been added.

**Comment by johnnyreilly** [comment]
Thanks chap!

**Pull request merged**
