### PR TITLE
[hammerjs] Use number literals in constants

### PR DESCRIPTION
**Pull request by jgonet**
## Description

I used binary literals to make binary or operations more visible. I think it highlights that every constant in the group is different from others.

## Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test hammerjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    - https://github.com/hammerjs/hammer.js/blob/master/src/inputjs/input-consts.js#L16-L29
    - https://github.com/hammerjs/hammer.js/blob/master/src/recognizerjs/recognizer-consts.js#L1-L7
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jakub-gonet** [comment]
@codler, seems like @milkisevil isn't resolved to any account, should handle be removed from hammerjs maintainers?

**Comment by jakub-gonet** [comment]
Looks like @philipbulley changed his handle :>

Are you still maintaining those types?

**Review by peterblazejewicz — CHANGES_REQUESTED** [review]
Please use same literals notation as in the source, thx!

**Comment by jakub-gonet** [comment]
Sure, changed.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jakub-gonet** [comment]
Hammer.js types are clearly unmaintained, I'm not sure what is the standard policy here but maybe type owners should be removed to prevent the situation where every PR has to wait two weeks until it's merged?

**Pull request merged**
