### PR TITLE
The jsonwebtoken verify.js is formatted in such a way that if one exists, the other does not exist.

### PR DESCRIPTION
**Pull request by kahirokunn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/auth0/node-jsonwebtoken/blob/37650031fd0bac1a5b0d682bbfcf8c1705917aa9/verify.js#L216
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
Why this is better?
1) it removes hinting for users, removing named params with (if IDE engine supports it), things like `arg_0`, `arg_1`
2) would it make this pass?
```ts
jwt.verify(token, cert, { audience: "urn:foo", issuer: "urn:issuer" }, (
    err,
    decoded
) => {
    // if issuer mismatch, err == invalid issuer
    if (err) {
        err; // $ExpectType VerifyErrors
    } else {
        decoded; // $ExpectType object
    }
});
```
(current version does not pass that either, so what's the point of the change?)

**Comment by kahirokunn** [comment]
Sorry.
I fixed it so you can reference the arguments name.

**Comment by kahirokunn** [comment]
For the "verify" method, decoded will always be present if err is not present.

The purpose of this pull request is to allow the specification to be expressed as a type if the argument is not expanded, while maintaining full compatibility.

pattern1
image

pattern2
スクリーンショット 2020-12-22 10 19 14

**Comment by kahirokunn** [comment]
If the specification is not expressed as a type, it forces the user to type guard "decoded" even in the absence of err.
The purpose is to improve this.

**Comment by peterblazejewicz** [comment]
I still cannot what's the gain for user? To use named tuples we would have to restrict to TS4 or newer.
The older syntax just works, when used in usual `if/else`. The outcome is really the same, it does not remove any burden from me (e.g. i'd like to not test for `undefined` when error is `null`).
So the question is, what is gain for other developer?

**Comment by kahirokunn** [comment]
The problem is this.
expect the decoded type to be `object`, but it is now `object | undefined`.

```
jwt.verify(token, cert, { audience: "urn:foo", issuer: "urn:issuer" }, (
    err,
    decoded
) => {
    // if issuer mismatch, err == invalid issuer
    if (err) {
        err; // $ExpectType VerifyErrors
    } else {
        decoded; // $ExpectType object, got object | undefined
    }
});
```

**Comment by kahirokunn** [comment]
if you want I can support ts4 and below by removing the tuple label

**Comment by kahirokunn** [comment]
How about this one? 👀

**Pull request closed without merging**
