### PR TITLE
Fix jquery type definitions

### PR DESCRIPTION
**Pull request by falsandtru**
Conforms to official specifications.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Hi,

Could you revert the whitespace changes please? I'd like to review this properly but there's a lot of noise in the PR right now.

Thanks.

**Comment by falsandtru** [comment]
Hi,

All right. Fixed. Can you merge if modification of whitespace to another pull request?

**Comment by johnnyreilly** [comment]
Thanks - I'll try and look at this on Monday. Ping me if I forget.

**Comment by johnnyreilly** [comment]
Looks great - thanks chap!

**Pull request merged**
