### PR TITLE
[Three] Make Raycaster::Intersection, intersectObject generic

### PR DESCRIPTION
**Pull request by Degubi**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mrdoob/three.js/blob/dev/src/core/Raycaster.js#L56 which calls
https://github.com/mrdoob/three.js/blob/dev/src/core/Raycaster.js#L88

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
I'm not sure about this. Changing types to Generics without a real reason and discussion is a big no, so it'd be good if you could accurately explain why you think this change should be made.

Also using the letter `T` imo is bad practice, if we're doing this it should be called something like `TIntersected` or something.

**Comment by Degubi** [comment]
@joshuaellis Hi! I actually wrote an explanation, I just forgot to add it to the issue....
So our problem is that in our codebase we use jsdocs everywhere. And anywhere we use the intersectObject(s) methods we have to do type casts or ts-ignores.
Example:

```javascript
/**
 * @param { Mesh<BufferGeometry, MeshStandardMaterial | MeshPhongMaterial>[] } meshesToRaytrace
 * @returns { T | null }
 */
getMeshAtCursor(meshesToRaytrace) {
	const intersects = raycaster.intersectObjects(meshesToRaytrace);

	// @ts-ignore We know this is a Mesh because we pass in meshes for checking in the first place
	return intersects.length > 0 ? intersects[0].object : null;
}
```

Here we pass in Mesh objects, but still get an Object3d back after the intersectObjects call, which is correct, but the type could be more concrete so that we don't need to do a ts-ignore.

The T typename can be changed of course

**Comment by joshuaellis** [comment]
Can you make this pr in three-ts-types please?

**Comment by Degubi** [comment]
Sure!
https://github.com/three-types/three-ts-types/pull/130

**Pull request closed without merging**
