### PR TITLE
ansicolors: accurate types with recursion support

### PR DESCRIPTION
**Pull request by balupton**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: no version difference, just made it work with the accurate types for the existing version
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

Replaced the previous authorship notice as the whole file has been replaced.

### CODE REVIEW

**Comment by balupton** [comment]
> After 5 days, no one has reviewed the PR 😞. A maintainer will be reviewing the PR in the next few days and will either merge it or request revisions. Thank you for your patience!

It's been another 7 days?

**Comment by rogierschouten** [comment]
I'll approve, maybe that helps. BTW it's customary to ADD your name to the 'definitions by' line rather than replace another's name. But as you replaced all of it, I'll agree. I'm moving house so had no time to review, sorry

**Review by rogierschouten — APPROVED** [review]

**Comment by balupton** [comment]
Thanks for the reply. First time working with this repo, so it is new to me.

I've updated the PR with support for using the colors as functions. E.g. `colors.black(value)` rather than just `colors.black + value`

**Review by rogierschouten — APPROVED** [review]

**Comment by rogierschouten** [comment]
Since it's your first time: thank you for contributing!   Note that everyone here is a volunteer and merging sometimes takes a couple of weeks. But generally, things have gone pretty smoothly for me on this reporting

**Pull request merged**
