### PR TITLE
fix(node-pushnotifications): add web support

### PR DESCRIPTION
**Pull request by jaulz**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
- Single ids will automatically be converted to an array: https://github.com/appfeel/node-pushnotifications/blob/a9c37f83a0d7c1a7aba9dbc284a1aa5047d9f7b2/src/push-notifications.js#L100
- Ids for web look like this:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/web-push/index.d.ts#L161-L167
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by menushka — CHANGES_REQUESTED** [review]
If I'm not mistaken, I think the Settings interface needs to also be updated with the Web Push configs.  If you don't mind please add those settings, then it should be all set to merge.

```typescript
    web: {
        vapidDetails: {
            subject: '< \'mailto\' Address or URL >',
            publicKey: '< URL Safe Base64 Encoded Public Key >',
            privateKey: '< URL Safe Base64 Encoded Private Key >',
        },
        gcmAPIKey: 'gcmkey',
        TTL: 2419200,
        contentEncoding: 'aes128gcm',
        headers: {}
    },
```

**Comment by jaulz** [comment]
@menushka sorry for the many commits but now it should work as expected 😊

**Comment by jaulz** [comment]
Oop,s

**Comment by jaulz** [comment]
@menushka just a reminder...

**Comment by menushka** [comment]
Oh my bad, I'm out at the moment, I’ll take a look at it as soon as I get a chance to sit down.

**Review by menushka — APPROVED** [review]
I'm gonna approve this as it seems everything should work.  The only thing I'm not sure about an import of a package other than the one the typing is being built for (web-push).  It should be fine as its a dependancy of node-pushnotifications, just unsure if it go against any of DefinitelyTyped's specs.  Other than that, looks good and good work.

**Pull request merged**
