### PR TITLE
[geometric] Add missing functions to bring up to date with version 2.5

### PR DESCRIPTION
**Pull request by lindapaiste**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/HarryStevens/geometric/releases
https://github.com/HarryStevens/geometric#api
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

Adds optional `epsilon` argument (since [v2.2.5](https://github.com/HarryStevens/geometric/releases/tag/v2.2.5)) to functions:
* `pointOnLine`
* `pointOnPolygon` 
* `pointWithLine`

Creates types for new functions:
* `lineTranslate`
* `polygonInterpolate`
* `polygonRandom`
* `polygonReflectX`
* `polygonReflectY`
* `polygonScaleArea`
* `polygonWind`

Update comments to match package docs for functions:
* `lineRotate` (see PR #62388)
* `polygonScale`

### CODE REVIEW

**Comment by lindapaiste** [comment]
@tmcw maybe you can review?

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Review by tmcw — APPROVED** [review]
LGTM!

**Comment by lindapaiste** [comment]
Ready to merge

**Pull request merged**
