### PR TITLE
Update types for opentok 2.10.0

### PR DESCRIPTION
**Pull request by rossng**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
@rossng could you please maintain the existing tab spacing? The diff is very large & difficult to review without going line by line. Many text editors can reformat the tab spacing automatically. We used to have 2 spaces per tab in here.

**Comment by rossng** [comment]
Hi @pronebird - thanks for taking a look 🙂. Looks like my editor picked up DefinitelyTyped's global Prettier configuration which uses 4 spaces. But I agree that ease of review is more important for now - so I've reverted both files to using two-space indentation.

**Review by pronebird — APPROVED** [review]
Approved

**Comment by pronebird** [comment]
Ready to merge

**Pull request merged**
