### PR TITLE
fix Worker.id type

### PR DESCRIPTION
**Pull request by thewizarodofoz**
https://nodejs.org/docs/latest-v7.x/api/cluster.html#cluster_worker_id

### CODE REVIEW

**Comment by andy-ms** [comment]
Should other versions of `node` be changed too?

**Comment by thewizarodofoz** [comment]
All of the docs versions show the same thing (number, not string):
https://nodejs.org/docs/latest-v4.x/api/cluster.html#cluster_worker_id
https://nodejs.org/docs/latest-v5.x/api/cluster.html#cluster_worker_id
https://nodejs.org/docs/latest-v6.x/api/cluster.html#cluster_worker_id

**Comment by andy-ms** [comment]
OK, please change it in the other files then (including `types/node/index.d.ts` which is for version 8).

**Comment by RyanCavanaugh** [comment]
@thewizarodofoz Please fix the failures indicated in the Travis CI log.

**Comment by thewizarodofoz** [comment]
@RyanCavanaugh The Travis error is: The job exceeded the maximum time limit for jobs, and has been terminated. Not sure how I can fix this...

**Comment by minestarks** [comment]
Restarted Travis

**Pull request merged**
