### PR TITLE
Add optional signIn and signOut parameters for 'next-auth'

### PR DESCRIPTION
**Pull request by andersnylund**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nextauthjs/next-auth/blob/main/src/client/index.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Add provider IDs and use them as optional parameter for signIn function in client. Add SignOutArgs type for signOut function in client

@lluia this is probably not fully compatible but it's a start

### CODE REVIEW

**Comment by andersnylund** [comment]
This is addressing the issue raised by @daviduzumeri in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45775#issuecomment-681032636

**Review by 0ubbe — APPROVED** [review]
Nice thanks for this 💯 👏🏽

**Comment by JuanM04** [comment]
This doesn't work for custom IDs.

**Comment by andersnylund** [comment]
> This doesn't work for custom IDs.

Ah, @JuanM04 I see you opened another PR #47130 that addresses this problem 🚀 Thanks for that! I would still like to have the predefined ID's also, so the type could be `provider?: string | PossibleProviderId`.

However, go and merge that PR and I can rebase this on top that

**Comment by JuanM04** [comment]
Yes, np!

**Comment by JuanM04** [comment]
I will add your changes (fixed singout, `callbackUrl`, and sorted Providers)

**Pull request closed without merging**
