### PR TITLE
Added missing strokeMiterLimit to SVG attributes

### PR DESCRIPTION
**Pull request by ccapndave**

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3 @vsiao @RyanCavanaugh @jbrantly can anyone review this PR?

**Comment by pspeter3** [comment]
Seems legit to me

**Comment by jbrantly** [comment]
+1 from me

**Comment by RyanCavanaugh** [comment]
Can we confirm `miterLimit` vs `miterlimit` ? I don't see it in this list https://github.com/facebook/react/blob/ba81b60ad8e93b747be42a03b797065932c49c96/src/renderers/dom/shared/SVGDOMPropertyConfig.js#L55

**Comment by jbrantly** [comment]
@RyanCavanaugh Despite not being in that list, it's `miterlimit` based on the convention.

> All DOM properties and attributes (including event handlers) should be camelCased to be consistent with standard JavaScript style.

And the actual SVG attribute is `stroke-miterlimit`.

I had the same thought before I +1'd so I looked it up :grin:

**Comment by vvakame** [comment]
thanks all!

**Pull request merged**
