### PR TITLE
add `reflect.ownkeys`

### PR DESCRIPTION
**Pull request by ljharb**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by ljharb** [comment]
@peterblazejewicz can you help me understand what's different between this and #68259?

**Comment by peterblazejewicz** [comment]
can you rebase and force push to make sure updated dependencies are installed?
I've noticed on first install no dependencies were installed and I've got same error as in CI. I've re-installed workspace dependencies (all reps for test), and it worked:
```
pnpm test reflect.ownkeys

> definitely-typed@0.0.3 test /Users/blazejewicz/develop/DefinitelyTyped
> node --enable-source-maps node_modules/@definitelytyped/dtslint/ types "reflect.ownkeys"

dtslint@0.1.2
```
so no code change required, it looks like diffing or CI problem only. Works locally

**Comment by ljharb** [comment]
thanks, i'd rebased a couple times but maybe master was broken and is now fixed.

**Comment by jakebailey** [comment]
> The only difference between this PR and the previous PR is that the previous PR happened before we enabled AreTheTypeWrong; all existing packages were marked as being okay to fail, but new packages are not.

Scratch that, `array.prototype.every` doesn't have an export mapping, so it is already passing as-is. (But the check is new.)

**Comment by jakebailey** [comment]
Ah, the fixed attw output is more clear about what's wrong.

**Comment by ljharb** [comment]
Thanks, will update the PR later this evening.

**Comment by ljharb** [comment]
@jakebailey how can i run attw *just* on one specific DT package? when i cd into the folder and run `npx @arethetypeswrong/cli -P`, it doesn't give me the same output.

**Comment by jakebailey** [comment]
dtslint has special code to produce an in memory packed version from the repo; you should just be able to run `pnpm test <package name>`.

Alternatively, the website may work if you `pnpm pack` and upload it, but that seems harder. https://arethetypeswrong.github.io/

**Comment by ljharb** [comment]
pnpm test has passed for me every time, though.

**Comment by jakebailey** [comment]
You may need to reinstall the repo root if you haven't recently.

**Comment by ljharb** [comment]
If `pnpm install` is sufficient to do that, then that doesn't work; if it's not, what command would i run? (i'm not very familiar with pnpm)

**Comment by ljharb** [comment]
Perhaps I should just remove the ESM entry point from the package?

**Comment by jakebailey** [comment]
You should be able to just do `pnpm install --filter .` to select just the root.

**Comment by ljharb** [comment]
Nope, still passes locally despite failing in CI, and `npx @arethetypeswrong/cli -P` passes inside `types/reflect.ownkeys`:
```
$ npx @arethetypeswrong/cli -P

@types/reflect.ownkeys v1.1.9999

 No problems found 🌟


┌───────────────────┬──────────────────────────┐
│                   │ "@types/reflect.ownkeys" │
├───────────────────┼──────────────────────────┤
│ node10            │ 🟢                       │
├───────────────────┼──────────────────────────┤
│ node16 (from CJS) │ 🟢 (CJS)                 │
├───────────────────┼──────────────────────────┤
│ node16 (from ESM) │ 🟢 (CJS)                 │
├───────────────────┼──────────────────────────┤
│ bundler           │ 🟢                       │
└───────────────────┴──────────────────────────┘
```

**Comment by jakebailey** [comment]
(I don't you have to delete node_modules...)

**Comment by jakebailey** [comment]
I'll try locally in the morning.

**Comment by ljharb** [comment]
Aha, deleting node_modules does show the same failures, thanks. I'll work with that. (shame `pnpm install` doesn't do the same thing without removing node_modules first)

**Comment by andrewbranch** [comment]
None of the ESM types can be resolved because the package.json here doesn’t mention them. A request for `"reflect.ownkeys"` will look up `node_modules/@types/reflect.ownkeys/package.json`, and then see `"types": "index.d.ts"`, which is a CommonJS types file. TypeScript has no idea there’s an index.d.mts. You need to add `"exports"` to package.json here.

**Comment by ljharb** [comment]
ahhhhh gotcha, thanks. i'll add "exports" (altho the actual package doesn't have `exports` - would it work to just remove "types"?)

**Comment by jakebailey** [comment]
The actual package does: https://github.com/es-shims/Reflect.ownKeys/blob/d459377303dd51cfb2abb0e91368a22193d700bf/package.json#L6

**Comment by jakebailey** [comment]
Something like this, I think:

```json
"exports": {
	".": {
		"types": {
			"import": "./index.d.mts",
			"require": "./index.d.ts",
			"default": "./index.d.ts",
		}
	},
	"./auto": {
		"types": "./auto.d.ts",
	},
	"./polyfill": {
		"types": "./polyfill.d.ts",
	},
	"./implementation": {
		"types": "./implementation.d.ts",
	},
	"./shim": {
		"types": "./shim.d.ts",
	},
	"./package.json": "./package.json"
}
```

Though skimming some other packages on DT with export maps, there seem to be multiple working forms.

**Comment by andrewbranch** [comment]
The nested `"types"` isn’t strictly needed, since only TypeScript should be looking in node_modules/@types in the first place.

**Comment by ljharb** [comment]
oh lol my bad, thanks, i'll try that.

**Comment by ljharb** [comment]
yay, thanks, that did it :-)

some thoughts about ways to have a better experience here:
 - attw could suggest using the "exports" field, explicitly - maybe even read from the existing package's one and suggest one?
 - find a way for `pnpm install` at the root to deterministically result in roughly the same tree as when i rimraf node_modules
 - add a note to the "adding a new definition" section of the readme about the "exports" field

**Review by peterblazejewicz — APPROVED** [review]
@jakebailey @andrewbranch thanks!

**Comment by ljharb** [comment]
Ready to merge

**Pull request merged**
