### PR TITLE
authManager update and tests

### PR DESCRIPTION
**Pull request by adstep**
case 2. Improvement to existing type definition.
- angular-jwt was recently updated to use a new [service](https://github.com/auth0/angular-jwt/commits/master/src/angularJwt/services/authManager.js)

### CODE REVIEW

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by adstep** [comment]
@vvakame Can I get some help please?

**Comment by rerezz** [comment]
:+1:

**Comment by vvakame** [comment]
sorry for late. It merged!

**Pull request merged**
