### PR TITLE
[bull] Add additional job properties, including queue, name, and stracktrace

### PR DESCRIPTION
**Pull request by dhritzkiv**
Rationale: it is useful to know which queue (and named processor) this Job was in.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/OptimalBits/bull/blob/40a69ac1959f4c0b6981be0c64f7889714b069c7/lib/job.js#L123-L136
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by pc-jedi** [comment]
Shall we reflect that `stacktrace` and `returnvalue` can be `null`?

**Comment by dhritzkiv** [comment]
For stacktrace, I wonder if it can be, since here it is always defined:
https://github.com/OptimalBits/bull/blob/40a69ac1959f4c0b6981be0c64f7889714b069c7/lib/job.js#L39

I’ll update returnvalue

**Review by pc-jedi — APPROVED** [review]
Since `stacktrace` is always set and `returnvalue` is `any`, I think we are good to go.

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
