### PR TITLE
[jsonld] update `@nest`, `@type`, `@value` with JSON types

### LINKED ISSUE #50909: [@types/jsonld] NodeObject should permit multiple @types
- [x] I tried using the `@types/jsonld` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chharvey

NodeObjects can have multiple types via an array, but this is not permitted in the types.
https://w3c.github.io/json-ld-syntax/#specifying-the-type

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a6b5cb9b082067e364768175b12a5d41cf9aaf5d#r46505918

Happy to make a PR but it'll be a few days – I will make a comment here if I start work on it.

### PR DESCRIPTION
**Pull request by chharvey**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://w3c.github.io/json-ld-syntax/#specifying-the-type

Closes #50909 (by @gsvarovsky), fixes #47364

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsonld ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsonld@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'jsonld'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f5fcc313f6ab62fc1d001dd164b3d1e97851f873
</p>

**Comment by chharvey** [comment]
@jason076 @amcasey @sandersn Please leave a review if you get a chance. This is a fix for #47364. Thank you

**Review by sandersn — APPROVED** [review]

**Comment by chharvey** [comment]
Ready to merge

**Comment by jason076** [comment]
Sorry for not responding to the PR. I don't work with jsonld anymore and unfortuntely I do not have the time to maintain it. Is there a way to tell the typescript-bot that it should not suggest me to review PR's for this file?

**Comment by amcasey** [comment]
@jason076 No worries.  You'll want to remove yourself from the [owners list](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/56ed3a050fca0de5702749171796c58fa1ccc599/types/jsonld/index.d.ts#L3).

@chharvey Are you interested in being a maintainer?  I'm not sure what happens if a package doesn't have one.  (@sandersn?)

**Comment by chharvey** [comment]
@amcasey Thank you for the offer, but I’m not experienced enough with the original [jsonld.js](https://github.com/digitalbazaar/jsonld.js) repository by @digitalbazaar, nor the [JSON-LD API spec](https://www.w3.org/TR/json-ld-api/) (which differs from the [JSON-LD spec](https://www.w3.org/TR/json-ld11/)).

**Comment by sandersn** [comment]
I just added myself in #51532 until somebody else shows up that wants to maintain the types.

**Comment by jason076** [comment]
@sandersn Thank you!

**Pull request merged**
