### PR TITLE
Publish a minimal angular2.d.ts file for our quickstart

### PR DESCRIPTION
**Pull request by alexeagle**
We are working hard to produce a complete .d.ts directly from angular2 sources, but it is a big project.
We'd like to get this early preview published to compliment the developer preview release, and deliver via tsd rather than ask users to clone our quickstart repo.

### CODE REVIEW

**Comment by alexeagle** [comment]
We are using typescript 1.5 so it looks like I need to merge this into the 1.5.0-alpha branch? But then I don't think our quickstart will work with simply `tsd query angular2 --action install`

**Comment by alexeagle** [comment]
okay, I down-transpiled the typings to work with 1.4 and added a test. Please let me know when the merge might land so we can publish the updated Angular 2 quickstart. THanks!

**Comment by alexeagle** [comment]
@basarat could you take a look? We'd like to get our new quickstart out since ng-vegas is happening today and tomorrow.

**Comment by basarat** [comment]
:rose:

**Comment by HerringtonDarkholme** [comment]
Thank you @alexeagle ! Will Angular2 be completely transported to TS?

**Comment by alexeagle** [comment]
Yes we are making good progress on that now.

**Comment by jpsfs** [comment]
Hi!

@alexeagle, do you have an ETA on an improved version of angular2.d.ts?
No need for a complete set, just some things on forms and router.

**Comment by alexeagle** [comment]
We have some progress in generating the full one, but has some issues
remaining, follow https://github.com/angular/angular/issues/2147

**Pull request merged**
