### PR TITLE
Remove old maintainers from mssql

### PR DESCRIPTION
**Pull request by mcdado**
Remove @buzinas and @mcdado from maintainers .

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by buzinas — APPROVED** [review]
LGTM! Thanks for taking the time to do this!

**Comment by dhensby** [comment]
Sorry to chime in here, but this is a bit inconsiderate given than I'm authoring #53434, which has no doubt prompted you to remove yourself. I understand if you're not interested in maintaining the typings anymore and that's fair enough, but you could raise that in the PR I've authored and approve it there.

Now, with this, if you merge it I'll have conflicts and need to rebase meaning anyone who *does* take their time to review the changes will then be requested to do so again because the fixed conflicts will require the bot to re-request authorisation.

**Comment by mcdado** [comment]
Sorry @dhensby I just took the opportunity to do it myself since I also stopped working on the project. I wasn't aware that you did commit the same change.

**Comment by dhensby** [comment]
If either @mcdado or @buzinas approve my PR we can get both things merged at once 😇

**Comment by mcdado** [comment]
OK, but I haven't found the way to approve it. I'll just add a comment.

**Pull request closed without merging**
