### PR TITLE
Add type definition for `reduce-reducers`

### PR DESCRIPTION
**Pull request by huy-nguyen**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

Notes:

- Could not run `npm run new-package` because it error'ed out but I tried to follow conventions in the README.
- Running `tsc` complains about `error TS2307: Cannot find module 'redux'` because `redux` is not in DT because it provides its own type definition. If I `npm install` to get `redux`'s type definitions, the linter catches errors inside the dependencies which I have no control over.

Can anyone help me out?

### CODE REVIEW

**Comment by mhegazy** [comment]
Thank you for your contribution. 

Can you please fix the failing Travis CI tests and update the PR!

**Comment by mhegazy** [comment]
you need to update the test file name.

**Comment by huy-nguyen** [comment]
@mhegazy I'm not sure why Travis failed because the last commit (10f7eca) I made in this PR *did* change the test file name to be `reduce-reducers-tests.ts` in accordance with the guidelines. Can you help me out?

**Comment by huy-nguyen** [comment]
@mhegazy I made a few fixes and the tests passed.

**Comment by AJamesPhillips** [comment]
In the tests it shows

    import reduceReducers from 'reduce-reducers';

But this doesn't actually work for me.  @huy-nguyen do you use `import reduceReducers = require('reduce-reducers');` in your production code?  Perhaps I have a mistake somewhere else?  http://stackoverflow.com/questions/43616320/consuming-default-export-with-typescript

**Comment by huy-nguyen** [comment]
@AJamesPhillips If you look at the [actual source code of `reduce-reducers`](https://github.com/acdlite/reduce-reducers/blob/c28b9e9544036c797d7b523da8b2612755dee1f3/src/index.js), it's written as an ES6 module so the type definition reflects that. You should use `import reduceReducers from 'reduce-reducers'`. The `import reduceReducers = require('reduce-reducers');` syntax is mostly (if not only) used for AMD/commonJS modules.

**Comment by AJamesPhillips** [comment]
@huy-nguyen thanks for the speedy response.  Yeah, that's what I thought I'm just getting the error `TypeError: Cannot read property 'apply' of undefined` because this typescript:

    import reduce_reducers = require("reduce-reducers");
    var functions = [];
    reduce_reducers(...functions);

Produces this javascript:

    var reduce_reducers_1 = require("reduce-reducers");
    reduce_reducers_1.default.apply(void 0, functions);

What version of Typescript are you running.  I'm on 2.2.2.  Also what's your tsconfig.json.  [Mine's here](http://stackoverflow.com/questions/43616320/consuming-default-export-with-typescript).

**Pull request merged**
