### PR TITLE
Updated definition for circular-dependency-plugin to match Plugin interface

### PR DESCRIPTION
**Pull request by maxbogus**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jeremejevs** [comment]
@maxbogus What's the motivation behind this PR? `apply` is already in there, inherited from [`webpack.Plugin`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1301cf09e387020ab79f6e182c8e1fafd44432ad/types/webpack/index.d.ts#L1148-L1150). Is something not working for you?

**Review by alecmev — CHANGES_REQUESTED** [review]
@maxbogus What's the motivation behind this PR? `apply` is already in there, inherited from [`webpack.Plugin`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1301cf09e387020ab79f6e182c8e1fafd44432ad/types/webpack/index.d.ts#L1148-L1150). Is something not working for you?

**Comment by maxbogus** [comment]
Yes, that's it.   
  
  

  
Without this change our typechecker throws error, that apply is missing and types don’t match.
  
  

  
  

  
  
>

**Comment by maxbogus** [comment]
@jeremejevs here is an example of the typecheck error that occurs without this change:

`/Users/mboguslavskiy/repositaries/WebCC/webpack/webpack-config-builder/src/blocks/build-quality.ts:25:7
ERROR 25:7   typecheck  Type 'CircularDependencyPlugin' is not assignable to type 'Plugin'.
  Types of property 'apply' are incompatible.
    Type '(compiler: import("/Users/mboguslavskiy/repositaries/WebCC/node_modules/@types/webpack-dev-server/node_modules/@types/webpack/index.d.ts").Compiler) => void' is not assignable to type '(compiler: import("/Users/mboguslavskiy/repositaries/WebCC/node_modules/@types/webpack/index").Compiler) => void'.
      Types of parameters 'compiler' and 'compiler' are incompatible.
...`

**Comment by jeremejevs** [comment]
Are you using Yarn? I believe you might be experiencing this issue: https://github.com/yarnpkg/yarn/issues/4489 There are some solutions in that thread. I personally just modify `yarn.lock` and make sure there’s only one minor/patch version of Webpack (or, say, React).

**Comment by maxbogus** [comment]
@jeremejevs I don't see changes we are talking about in master branch.
I tried solutions from your link and they don't help.

**Comment by jeremejevs** [comment]
I'm 99% sure that this is a Yarn thing. Try this:

1. Open `yarn.lock`.
1. Find `@types/webpack`.
1. There are likely 2 or more blocks, looking like this (versions shown aren't real):
```
"@types/webpack@*":
  version "4.3.2"
  resolved "https://registry.yarnpkg.com/@types/webpack/-/webpack-4.3.2.tgz#bar"
  dependencies:
    "@types/node" "*"
    "@types/tapable" "*"
    "@types/uglify-js" "*"
    source-map "^0.5.0"

"@types/webpack@^4.5.6":
  version "4.5.6"
  resolved "https://registry.yarnpkg.com/@types/webpack/-/webpack-4.5.6.tgz#foo"
  dependencies:
    "@types/node" "*"
    "@types/tapable" "*"
    "@types/uglify-js" "*"
    source-map "^0.6.0"
```
1. Delete all lines between `version "4.3.2"` and `"@types/webpack@^4.5.6":`, inclusive, so there's only one block left, with the newest one.
1. Save and run `yarn`, without arguments.

**Comment by maxbogus** [comment]
I had:
`"@types/webpack@*", "@types/webpack@4.4.34":
  version "4.4.34"
  resolved "https://registry.npmjs.org/@types/webpack/-/webpack-4.4.34.tgz#e5f88b9a795da11683b4ec4a07d1c2b023b19810"
  integrity sha512-GnEBgjHsfO1M7DIQ0dAupSofcmDItE3Zsu3reK8SQpl/6N0rtUQxUmQzVFAS5ou/FGjsYKjXAWfItLZ0kNFTfQ==
  dependencies:
    "@types/anymatch" "*"
    "@types/node" "*"
    "@types/tapable" "*"
    "@types/uglify-js" "*"
    source-map "^0.6.0"

"@types/webpack@4.4.31":
  version "4.4.31"
  resolved "https://registry.npmjs.org/@types/webpack/-/webpack-4.4.31.tgz#f59b9d8210cf4d2fd254fe6d1f5ba86e557867f5"
  integrity sha512-WNALmv/wxy2+OoF7A5GD8BVotXnkuMHlojVWKj/neFHU3Ut2Azbu1A7Yi2Vr6eX3z+31XgR/dJ5NpX4pQZ7ieQ==
  dependencies:
    "@types/anymatch" "*"
    "@types/node" "*"
    "@types/tapable" "*"
    "@types/uglify-js" "*"
    source-map "^0.6.0"`
I replaced it with:
`"@types/webpack@*", "@types/webpack@4.4.34":
  version "4.4.34"
  resolved "https://registry.npmjs.org/@types/webpack/-/webpack-4.4.34.tgz#e5f88b9a795da11683b4ec4a07d1c2b023b19810"
  integrity sha512-GnEBgjHsfO1M7DIQ0dAupSofcmDItE3Zsu3reK8SQpl/6N0rtUQxUmQzVFAS5ou/FGjsYKjXAWfItLZ0kNFTfQ==
  dependencies:
    "@types/anymatch" "*"
    "@types/node" "*"
    "@types/tapable" "*"
    "@types/uglify-js" "*"
    source-map "^0.6.0"`

**Comment by maxbogus** [comment]
I still got following error:
`ERROR 25:7   typecheck  Type 'CircularDependencyPlugin' is not assignable to type 'Plugin'.
  Types of property 'apply' are incompatible.
    Type '(compiler: import("/Users/mboguslavskiy/repositaries/WebCC/node_modules/@types/webpack-dev-server/node_modules/@types/webpack/index.d.ts").Compiler) => void' is not assignable to type '(compiler: import("/Users/mboguslavskiy/repositaries/WebCC/node_modules/@types/webpack/index").Compiler) => void'.`

If I add changes that I proposed everything works fine.

**Comment by maxbogus** [comment]
@jeremejevs you were right. we have a huge app with multiple package.json files. I replaced various versions with a single one, removed yarn.lock and started yarn again. Everything works fine.

**Comment by jeremejevs** [comment]
Thanks for reporting back! Deleting `yarn.lock` isn't normally advisable, but it's okay in case of a refactor like yours. Just be warned that you might run into the same issue when you upgrade your dependencies.

**Pull request closed without merging**
