### PR TITLE
office-js, office-js-preview, release contextual tabs

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OfficeDev/office-js-docs-pr/pull/2663
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ElizabethSamuel-MSFT — APPROVED** [review]

**Comment by lbourda** [comment]
Hi @Rick-Kirkham ,

I'm not sure if I should create a new issue or add a comment here, but since there are multiple things here goes.

1/ I've updated my dependencies to use the new npm (0.178) to play with contextual tabs but this won't work because there's a missing definition (const ribbon: Ribbon), which should probably have been added with a previous [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47060).

2/ Examples in [disable-add-in-commands](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands) mention the use of [groups](https://docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs#toggle-tab-visibility-and-the-enabled-status-of-a-button-at-the-same-time), even though this is not a property of the Tab interface and won't compile.

3/ When comparing office-js and office-js-preview, the preview version does not provide a "visible" property to the Control interface. I would have expected "preview" to have additional properties, not less.

Please let me know if you want me to create separate issues.

Thanks,
Laurent

**Comment by Rick-Kirkham** [comment]
@lbourda Thanks. I'm working on this. The PR 53206 should fix your #3.  I'm researching your #2.

**Comment by Rick-Kirkham** [comment]
Between them PRs 53206 and [53367](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53367) should fix your points 2 and 3. 

I don't understand your point 1.

**Comment by lbourda** [comment]
Sorry for the delay, @Rick-Kirkham.
I'm on vacation and only just checked this email.

Thanks for working on fixes.
Concerning my point 1, to use this you need to call the method Office.ribbon.requestUpdate().
Except there's no "ribbon" in "Office" in the office-js version, whereas in office-js-preview there is this:

> **
     * Represents the add-in.
     */
    const addin: Addin;
    /**
     * Represents the ribbon associated with the Office application.
     */
    **const ribbon: Ribbon;**

**Comment by Rick-Kirkham** [comment]
This should be fixed by PR 53446

**Pull request merged**
