### PR TITLE
[react-router] add RouteComponentProps.staticContext

### PR DESCRIPTION
**Pull request by kryops**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reacttraining.com/react-router/web/guides/server-rendering/adding-app-specific-context-information
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L101
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by kryops** [comment]
@sergey-buturlakin
@mrk21
@vasek17
@ngbrown
@awendland
@KostyaEsmukov
@johnnyreilly
@LKay
@DovydasNavickas
@tkrotoff
@huy-nguyen 
@Grmiade 
@DaIgeb

**Comment by tkrotoff** [comment]
Could you create a new test file, I would like to keep all existing test files in sync with React Router v4: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-website/modules/examples

**Comment by kryops** [comment]
@tkrotoff I added a test file that demonstrates using a StaticRouter with StaticContext. Do you think it is ok like this?

The JS version for the react-router repo I prepared here: https://github.com/kryops/react-router/tree/example-staticrouter.

**Comment by tkrotoff** [comment]
Looks good

**Pull request merged**
