### PR TITLE
Add Deno type definitions

### PR DESCRIPTION
**Pull request by andre4ik3**
This PR adds [Deno](https://deno.land) type definitions, from the Deno repository.

<details>

<summary><b>Example and Details (click to expand)</b></summary>

Say you have a file that looks like this:

```ts
// file.ts
if (typeof process !== "undefined") {
  // do Node-specific logic
} else if (typeof Deno !== "undefined") {
  // do Deno-specific logic
}
```

Normally, running `tsc file.ts` will complain about "Deno" not existing, and vice-versa, `deno run file.ts` will complain about "process" not existing. However, Deno is planning to not type-check files by default (because TypeScript is actually a very slow compiler). This opens a door to having fully-typechecked multi-runtime code. If you use `tsc` and install both `@types/node` and `@types/deno` (what this adds), then the code above will work and compile fine, and be statically type-checked!

In an ideal world, there would be some way to narrow an entire runtime down (!), e.g. `process` and friends are optional until you check `typeof process !== "undefined"`, at which point `process` becomes non-optional and `Deno` becomes `never`. And vice-versa. However, I *believe* this is impossible, and even if it wasn't, it would be very tricky to pull off. But it's still possible to have Node and Deno typings at the same time, and that's what this PR adds.

</details>

<details>

<summary><b>Template (click to expand)</b></summary>

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `—declaration`
  - It *does* provide its' own types, but they are not available in NPM/NodeJS (since Deno is a whole separate runtime!). These types are from the [Deno repository](https://github.com/denoland/deno) itself
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
  - There is a "deno" package on npm, but it is half-abandoned and a bit misleading, I did see it, but I don't think it will be affected much since it only has 49 downloads and when people do `npm i @types/deno` I think they would expect something like this instead of typings for the "actual" `deno` npm "package". Plus it tries to "reimplement" Deno APIs, so it would be the same thing anyway (although that package is 2 years outdated). If you prefer, I can rename it to something like `deno-runtime` and add a holding package on NPM, but I don't think there is any issue with this. GitHub issue for reference: https://github.com/YounGoat/nodejs.deno/issues/5
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

</details>

### CODE REVIEW

**Comment by amcasey** [comment]
Thoughts, @denoland!

**Comment by andrewbranch** [comment]
^ maybe @kitsonk / @dsherret?

**Comment by andre4ik3** [comment]
Yeah, I am happy to add ownership to anyone that is an actual author. My original idea was to put https://github.com/denoland/deno/contributors as author, but then I realized that it probably wouldn't process that, so I just put it as original author.

Actually, putting an entire organization is a good idea, I'll do that now

**Comment by andre4ik3** [comment]
I should also probably report that reference I had to comment out at the top as a bug, since those typings are generated as a "bundle" with `deno types` and already include that file.

**Comment by andre4ik3** [comment]
Could also add main contributors of this file https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.ns.d.ts

**Comment by dsherret** [comment]
Don't `@types/<package-name>` packages correspond to a `<package-name>` project? If so, there is a [deno](https://www.npmjs.com/package/deno) package that someone won't give up to us and maybe it doesn't make sense to add this because the deno package on npm does not align with these declaratoins?

> Yeah, I am happy to add ownership to anyone that is an actual author
> ...
> Could also add main contributors of this file https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.ns.d.ts

I would rather not have to maintain this, but if someone else in the community would want to that's fine. Generally we encourage people to write Deno first code and then transpile that for consumption in Node with [dnt](https://github.com/denoland/dnt).

All the types in Deno are available for the current runtime version by running the `deno types` command. So someone could do `deno types > deno.d.ts` then manually fix up any errors then reference that declaration file in their project.

**Comment by andre4ik3** [comment]
> Don't `@types/<package-name>` packages correspond to a `<package-name>` npm package?... maybe it doesn't make sense to add this because the deno package on npm does not align with these declarations?

Yes, they do, but there is already a `@types/node` package that has nothing in common with `node` package on npm. When people install `@types/node` and `node`, they would expect two different things (`node` installs node binary to `node_modules` whilst `@types/node` adds node runtime typings...) as opposed to `@types/express` and `express`...

Also, the actual "deno" package tries to... recreate Deno functions in Node, so the typings are (somewhat) aligned either way (except the npm package is 2 years out of date).

> If so, there is a [deno](https://www.npmjs.com/package/deno) package that someone won't give up to us

I'll get in touch.

> I would rather not have to maintain this, but if someone else in the community would want to that's fine.

Yes, and that's why I've added myself. I understand this perfectly, but still want to give you permissions to change it since you own the typings.

> Generally we encourage people to write Deno first code and then transpile that for consumption in Node with [dnt](https://github.com/denoland/dnt).

Yes, I even use `dnt` personally for a few projects! However, it is too much overhead for something like a script, where you only need a simple type-check, not a full-on compilation pipeline.

**Comment by andre4ik3** [comment]
> All the types in Deno are available for the current runtime version by running the deno types command. So someone could do deno types > deno.d.ts then manually fix up any errors then reference that declaration file in their project.

That's what I've done, and there were no errors except for a reference error which was a mistake by `deno types` (if I understand correctly). https://github.com/denoland/deno/issues/14747

Also added credits and access rights to entire `denoland` org.

**Comment by andre4ik3** [comment]
I've pinged the `deno` package owner in their repo to try to see if it's possible for them to rename the package. Then, if all goes well, I will make my own `deno` package that will either be a placeholder or possibly make something similar to the `node` package, which will install `deno` in `node_modules/.bin` and version it as if it was a normal dependency.

**Comment by kitsonk** [comment]
> All the types in Deno are available for the current runtime version by running the `deno types` command. So someone could do `deno types > deno.d.ts` then manually fix up any errors then reference that declaration file in their project.

They are also published with each release as part of the release artefacts: https://github.com/denoland/deno/releases which means that someone doesn't need to install the `deno` executable to obtain the correct type information for Deno.

I believe DefinitelyTyped is things that do not provide their own official types, which Deno clearly does, through various channels.

**Comment by andre4ik3** [comment]
Alright, but is there anyway to publish it under some DefinitelyTyped package still? In my opinion it is better to do so because it's much easier to set up, as TypeScript auto discovers `@types` packages. E.g. just `npm i -D @types/deno` versus downloading deno types / `deno types > deno.d.ts` then tweaking tsconfig.json or adding a reference in all the files that are Deno-compatible... But I do understand, if you think it should only be for packages that don't provide their own typings, I will close it.

**Comment by kitsonk** [comment]
> TypeScript auto discovers `@types` packages

When they are an npm package that you install that doesn't include types.  It does not auto-discover Deno.  It ends up being nothing more than any other package published on npm.

@dsherret since we own the `@deno` namespace on npm, what about if we published `@deno/types` with the right version as part of our release process?

Also, that being said [@deno/deno-shim](https://www.npmjs.com/package/@deno/shim-deno) is a more integrated solution in the first place for those trying to polyfill the Deno namespace under Node.js.

**Comment by andre4ik3** [comment]
> releasing these types through regular deno channels might be preferable?

From what I see, yes. I would also prefer this, but I didn't know whether or not it would put too much burden on the maintainers, so I decided to make a "unofficial" release myself. But I would much prefer something like an official `@deno/types` rather than `@types/deno`

**Comment by andrewbranch** [comment]
Let’s close this for now. Thanks everyone.

**Pull request closed without merging**
