### PR TITLE
chore: remove ts3.6 support

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR removes all ts3.6 support and folder in accordance of the [support window](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window).

I understand a similar structure might have to be implemented again should we want to integrate more modern features, but for the time being the focus is to shed this compability layer.
This PR also removed some duplicate WASI tests and dead comments in `node-tests.ts`.

### CODE REVIEW

**Comment by LinusU** [comment]
Screenshot 2021-08-04 at 15 15 46

I think this was a misstake, right? 😅 

I tried looking thru the diff and couldn't find me being removed, maybe you already adressed this and the bot didn't update?

**Comment by SimonSchick** [comment]
@LinusU seems like a diffing but, don't know either way 🤷‍♂️

**Comment by SimonSchick** [comment]
Having trouble getting this to build locally, I will have to annoying the CI a bit, sry.

**Comment by SimonSchick** [comment]
Getting real annoyed with the CI rn 😂

**Comment by SimonSchick** [comment]
That was a struggle 🙄

**Comment by SimonSchick** [comment]
@sandersn we good to go?

**Review by sandersn — APPROVED** [review]

**Pull request merged**
