### PR TITLE
add templates attribute in bootstrap-datepicker.d.ts

### PR DESCRIPTION
**Pull request by sousarka**
Please fill in this template.
- [ x ] Prefer to make your PR against the `types-2.0` branch.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

add templates option which gives the ability to customize the arrow key icons. Also updated the link for DatepickerOptions to point to the latest.

### CODE REVIEW

**Comment by sousarka** [comment]
@borisyankov let me know if this can be merged.

**Comment by vvakame** [comment]
*bootstrap-datepicker/bootstrap-datepicker.d.ts*

to author (@borisyankov). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by sousarka** [comment]
@vvakame  created PR #12324 for types-2.0

**Pull request closed without merging**
