### PR TITLE
Added more overloads for the static all function

### PR DESCRIPTION
**Pull request by Dmitriyx**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here
image

### Updated Screenshot
image

>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Dmitriyx** [comment]
The test is failing because the maximum line length is 200. The current line: 850, has a length of 204.

**Comment by lhecker** [comment]
First of all thank you for your PR! Good job! Unfortunately it's not yet enough to be perfect though. 😥
Right now all variadic generics - like those used for the `.all()`, `.catch()`, `.method()` etc. methods - accept up to 5 generic arguments.
If possible I'd like to keep it that way: If you want to extent `.all()` to a 7-ary generic please extent all variadic generics simultaneously. (Optionally you can also extent it to even more - e.g. 10.)
Afterwards I'll approve this in a heartbeat, assuming no programming errors of course. 😄

P.S.: Before this can be merged in the end I'd additionally like to ask you to squash all your changes into a single commit. If you don't know how to do that (and can't find out how to do it) I'll gladly write down instructions how to rebase and squash a branch. 🙂

**Comment by lhecker** [comment]
P.P.S.: You can run the linter locally using `npm run lint bluebird`.

**Review by lhecker — CHANGES_REQUESTED** [review]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40828#issuecomment-561873021

**Pull request closed without merging**
