### PR TITLE
action prop was missing

### PR DESCRIPTION
**Pull request by adammo94**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: (https://github.com/wojtekmaj/react-calendar/#props)](https://github.com/wojtekmaj/react-calendar/#props)

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-calendar ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-calendar@latest/))
was missing the following properties:
1. Calendar
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1977af66c0bddb67c71f64dffc837a6758ffa46a
</p>

**Review by domdomegg — CHANGES_REQUESTED** [review]
Based on https://github.com/wojtekmaj/react-calendar/releases/tag/v3.5.0, https://github.com/wojtekmaj/react-calendar/issues/367 and https://github.com/wojtekmaj/react-calendar/issues/474 I think this is supposed to be added to the ViewCallbackProperties.

Additionally, please add some tests.

**Review by adammo94 — COMMENTED** [review]
yeah, you were right, now fixed

**Review by domdomegg — APPROVED** [review]
Change LGTM, would still benefit from some tests though (and you'll be able to merge it if you add tests)

**Comment by adammo94** [comment]
> Change LGTM, would still benefit from some tests though (and you'll be able to merge it if you add tests)

How do I change LGTM? I'd love to add tests if I knew what they supposed to be. I'm still pretty new to typescript, let alone tests, which I haven't even touched yet.

**Comment by domdomegg** [comment]
Ah sorry, by 'Change LGTM' I meant this change looks good to me. For adding tests you want to basically use this how you would in your app inside the corresponding `-tests.tsx` file, i.e.:

https://github.com/adammo94/DefinitelyTyped/blob/patch-1/types/react-calendar/react-calendar-tests.tsx

e.g. by adding the `onViewChange` prop with a callback that uses the added `action` property.

You can also add more complex tests, but I think for this change that'd be good enough. You've done a great job getting this far, and I wish you the best on your continued TypeScript journey :)

**Review by adammo94 — COMMENTED** [review]
fixed whitespace

**Review by domdomegg — APPROVED** [review]
Looks great! Brilliant job @adammo94

**Comment by domdomegg** [comment]
Hmmm because this is a popular package I think we need a review from @Guymestef or @ksoldau too (or one of the DT maintainers).

**Pull request merged**
