### PR TITLE
Remove unused package.json files

### PR DESCRIPTION
**Pull request by jakebailey**
All of these package.json files are empty and can be safely removed. This saves a _little_ CI time installing empty packages.

I feel like this should be a lint rule.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]

**Review by scttcper — APPROVED** [review]

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gestalt-datepicker ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gestalt-datepicker@latest/))
was missing the following properties:
1. Fragment
1. jsx
1. jsxs
## mock-knex ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mock-knex@latest/))
was missing the following properties:
1. adapter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b6d0a77274898466a294e5c49d459a0abbfd070b
</p>

**Review by oscnord — APPROVED** [review]

**Review by domdomegg — APPROVED** [review]
Approving watchpack changes

**Review by McBen — APPROVED** [review]

**Review by McBen — APPROVED** [review]
iitc

**Review by rlbaxter — APPROVED** [review]

**Review by koooge — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
Ready to merge

**Pull request merged**
