### PR TITLE
Update THREE.js definitions to r81

### PR DESCRIPTION
**Pull request by valorcurse**
Update the Three.js definitions to [r81](https://github.com/mrdoob/three.js/releases/tag/r81).

### CODE REVIEW

**Comment by eric-wieser** [comment]
Comment in the file should be updated to r81

**Comment by valorcurse** [comment]
Completly missed that, has been updated. Thanks!

**Comment by florentpoujol** [comment]
Looking at the r81 changelog, I feel there is a few more things (several deprecations and removals for instance) that should be changed in the definitions, too.

But otherwise, it's good. 👍

**Comment by valorcurse** [comment]
You're right, but coudn't find what the proper way would be to deprecate a definition and outright removing them might cause some problems. Any ideas?

**Comment by florentpoujol** [comment]
You have to check the corresponding commits to see how things are done exactly.

For stuffs that are deprecated but still works, you can leave them be or I usually mark them as deprecated with a comment or move them typically at the bottom of a class.
Sometimes the return type or arguments are changed, so it must be updated.

For things that are removed completely, they should be also removed for the definitions, since it will break the code that use them anyway.

But be carefull, sometimes things seems to be removed from a class, but are actually moved in the "legacy" part of three.js https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js

**Pull request merged**
