### PR TITLE
x-axios-progress-bar: init at 1.2

### PR DESCRIPTION
**Pull request by caugner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by caugner** [comment]
@mszkb I'm using your package `x-axios-progress-bar` in a project that we're currently migrating to TypeScript, so I opened this PR to add the TypeScript definitions. It's really just 6 lines of code, but if you would have time to quickly review it, that would be awesome.

After this gets merged, the definitions will be automatically published to npm as `@types/x-axios-progress-bar`.

**Comment by mszkb** [comment]
Hi @caugner, I do not know much about Typescript.
Can you somehow document this part: https://github.com/mszkb/progress-bar-4-axios#disable-progress-bar-for-specific-axios-requests
Maybe in the unit-test.

Otherwise it looks good.

**Comment by caugner** [comment]
Is `progress` an Axios parameter or is it a parameter that is specific to the library?

**Comment by mszkb** [comment]
Specific to the library

**Review by mszkb — APPROVED** [review]
LGTM

**Comment by orta** [comment]
Cool, me too 👍🏻

**Pull request merged**
