### PR TITLE
[@types/vimeo__player] Updating typings to match Vimeo's player.js v2.6.3

### PR DESCRIPTION
**Pull request by terrymun**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/vimeo/player.js
- [x] ~Increase the version number in the header if appropriate.~ (**not applicable**)
- [x] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~ (**already available**)

***

Summary of this PR:

- Expanded Options interface with additional new embed options/settings available
- Added new events: `bufferstart`, `bufferend`, `playbackrate` change
- Typed new methods for getting and setting playback rates: `getPlaybackRate()` and `setPlaybackRate()`
- `getTextTracks()` returns a promise which payload contains the `mode` key

### CODE REVIEW

**Comment by terrymun** [comment]
@denisyilmaz @timc13 On a side note, I've noticed that we are exporting `playerMap` and `readyMap` as WeakMaps--do you know what they are for?

**Review by denisyilmaz — APPROVED** [review]
sorry for delay. looks good. LGTM

**Comment by denisyilmaz** [comment]
@terrymun as far as I understood: playerMap and readyMap are two variables used by the vimeo.js to store the current instance of the player. https://github.com/vimeo/player.js/blob/cd36affa12de33c162342000103234babf72b96a/src/player.js#L57

**Comment by terrymun** [comment]
@denisyilmaz Thanks for the reply! I dug a little bit into their library and yeah, `playerMap` is used as some kind of cache for the player :) thanks for the enlightenment! Since the mappings are never exposed though, we can probably safely remove them.

**Comment by denisyilmaz** [comment]
I already approved this PR so I think you would have to create a new one?! I will approved either way (y)

**Pull request merged**
