### PR TITLE
Removed dependence on "Bluebird".

### PR DESCRIPTION
**Pull request by 0x6368656174**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by drinchev** [comment]
This looked like a good idea. Can you mention why you closed this. Did you encounter any problems?

**Comment by 0x6368656174** [comment]
@drinchev PromiseLike is not compatible with native Promise=( You can only remove the dependence on Bluebird, so that the sequelize was compatible with native Promise.

**Comment by drinchev** [comment]
Got it. Btw keep in mind that sequelize uses Bluebird as promise implementation. That's why I put it as a dependency in first place.

If you remove bluebird dependency you will not have `.tap`, `.reduce`, etc.

**Comment by 0x6368656174** [comment]
@drinchev The problem is that if I'm using a global bluebird because of performance:
`global.Promise = require("bluebird");`
But I do not use methods other than native ones. But because of the dependency of the secularize on the bluebird, the project is not going to. The Bluebird 3.0 is not compatible with the native Promise in the typescript-2.0 (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11027#issuecomment-248642717).

It turns out that, due to secularise, you have to import bliebird everywhere

**Pull request closed without merging**
