### PR TITLE
[passport-saml] Replace `{}` with `any`

### PR DESCRIPTION
**Pull request by mohsen1**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by cjbarth** [comment]
Where is the documentation that says that this shouldn't be an object and instead can be any type?

**Review by cjbarth — COMMENTED** [review]
I don't see why these changes were needed. I believe all these items should be objects. Where is the documentation?

**Comment by mohsen1** [comment]
`{}` is not equal to `object`. Maybe `object` is better than `any but I wasn't sure

**Comment by cjbarth** [comment]
Given the TypeScript documentation at https://www.typescriptlang.org/docs/handbook/basic-types.html says the following

> object is a type that represents the non-primitive type, i.e. any thing that is not number, string, boolean, symbol, null, or undefined.

I'm inclined to change this from `{}` to `object`, because it should never be `number`, `string`, `boolean`, `symbol`, `null`, or `undefined`.

**Comment by sana-ajani** [comment]
@mohsen1 @cjbarth will you change this to object? Holding off on the merge until it's figured out.

**Review by cjbarth — APPROVED** [review]

**Pull request merged**
