### PR TITLE
feat(redux-form): support non-string errors

### PR DESCRIPTION
**Pull request by ethanresnick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://redux-form.com/7.3.0/docs/api/field.md/#-code-validate-value-allvalues-props-name-gt-error-code-optional- Context: redux-form supports field-level errors being any type, not just strings (as noted in the link). A [common use](https://github.com/erikras/redux-form/issues/523) for this capability is to store an array of strings for each field instead. This PR lets the user parameterize SubmissionError and the library's various error properties with whatever type they're using to encode field-level errors. This also fixes FormErrors, so that the object type includes the _error
key at the top-level, not as a nested-object. See docs for that [here](https://redux-form.com/7.3.0/docs/api/submissionerror.md/).
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by paulvanbrenk — DISMISSED** [review]
Can you add some tests for these changes?

**Comment by ethanresnick** [comment]
@paulvanbrenk Ok, I've added some test cases and also fed the `ErrorType` through in more places to make this more ergonomic to work with.

**Comment by ethanresnick** [comment]
@paulvanbrenk Ok, I've added some test cases and also fed the `ErrorType` through in more places to make this more ergonomic to work with.

**Comment by mhegazy** [comment]
@CarsonF @aikoven @LKay @bancek @alsiola @tehbi4 @huwmartin - can you please review this PR?

**Comment by ethanresnick** [comment]
@mhegazy @paulvanbrenk What's the next step with this?

**Comment by andy-ms** [comment]
I think this looks pretty, good, @mhegazy @paulvanbrenk should we merge?

**Comment by ethanresnick** [comment]
@mhegazy @paulvanbrenk Any word on this?

**Comment by olokobayusuf** [comment]
Hi all. What's the status of this PR? It's been approved; can we get it merged soon? Thanks.

**Pull request merged**
