### PR TITLE
Allow Bluebird to be assignable to ES2016 Promise.

### PR DESCRIPTION
**Pull request by Strate**
See ##11027

### CODE REVIEW

**Comment by lhecker** [comment]
@Strate LGTM 🎉

To fix the failing tests I recommend replacing the `return;` etc. with e.g. `return bar;`. After that you can use `npm test` before pushing something to check if it works properly. (I think force-pushing with `git commit --amend` should be fine too.)

**Comment by Strate** [comment]
I have made `.then` method overloadings corresponding with https://github.com/Microsoft/TypeScript/blob/fb9806b5f9e883d8da964d029318bee769cd96cc/src/lib/es2015.promise.d.ts#L5-L32

**Comment by OliverJAsh** [comment]
Unfortunately the Promise typings have changed in TS version 2 and so these typings no longer correspond: https://github.com/Microsoft/TypeScript/blob/070aa83cc06b2974639bbefcde98e6e2fb5fe693/src/lib/es2015.promise.d.ts

**Comment by albertkim** [comment]
^ What is the solution around this now?

**Comment by nfantone** [comment]
I'm working on a PR right now. I made the declaration of `class Bluebird` implement `Promise` from `lib.es6.d.ts`.

```ts
declare class Bluebird<R> implements Promise<R>, Bluebird.Inspection<R> {
```

Problem is, I'm unsure as to how to get a reference to that `Promise` type from within DT. Can I add this to the `tsconfig.json` file? Is that allowed?

```json
  "lib": [
    "es2015.promise"
  ],
```

Pinging @lhecker and @Strate.

**Comment by Strate** [comment]
@nfantone Don't forget to implement overloadings for all methods, which returns `Promise`, to force them to return `Bluebird`

**Comment by nfantone** [comment]
Yes, that's done. But still, I don't know what's the proper way of getting a reference to the native `Promise` library.

**Pull request merged**
