### PR TITLE
[node] add crypto.scrypt and crypto.scryptSync

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest/docs/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback
https://nodejs.org/dist/latest/docs/api/crypto.html#crypto_crypto_scryptsync_password_salt_keylen_options
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by isLishude** [comment]
Is this the reason?

image

**Review by BrunoScheufler — APPROVED** [review]

**Comment by Flarna** [comment]
@andy-ms @rbuckton @RyanCavanaugh  (or who ever will merge this): Please note that this change includes also a workaround for #26063! Please take a look before you merge.

**Comment by paulvanbrenk** [comment]
@andy-ms I'm not sure about the change to the `package.json` which seems suspect.

**Comment by Flarna** [comment]
@paulvanbrenk This is the workaround I referred to above. Actual fix should be in types publisher to reduce the number of processes in travis.

**Comment by andy-ms** [comment]
Change to `package.json` looks fine.

**Pull request merged**
