### PR TITLE
[node] Fix Storage declaration in WebWorkers, run DT tests with lib.webworker

### LINKED ISSUE #70320: [@types/node] error TS2502: 'Storage' is referenced directly or indirectly in its own type annotation.
When creating a new project that imports `"@types/node": "^22.4.0"`, TS gives an error on compilation:

```sh
node_modules/@types/node/globals.d.ts:159:9 - error TS2502: 'Storage' is referenced directly or indirectly in its own type annotation.

159     var Storage: typeof globalThis extends { onmessage: any; Storage: infer T } ? T
```

The referenced value is here, and it does look like a true positive to me:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e5e3fc99a4e4fb10a41d33cbe7d26f148f37558a/types/node/globals.d.ts#L159-L163

### PR DESCRIPTION
**Pull request by Renegade334**
- Fixes the conditional in the `Storage` definition, to avoid a self-inference error in WebWorker builds.
  - The definition currently checks for the global `onmessage`, which is present both in lib.dom and lib.webworker. This works just fine for fetch and friends, since those APIs are present in both. However, lib.webworker doesn't contain a webstorage implementation, so screening based on `onmessage` leads to a self-inference error in WebWorker builds, unless lib checks are skipped.
  - The `onabort` global is only present in lib.dom and not lib.webworker, so this excludes the conditional inference from WebWorker builds.
- Adds a WebWorker tsconfig, so that tests are run with lib.webworker as well as lib.dom. As more and more web-compatible APIs are being added to Node, this seems like a sensible idea.

Also includes supplementary changes to the webstorage definitions:
- Adds the index signature to the `Storage` interface, matching the existing [lib.dom implementation](https://github.com/microsoft/TypeScript/blob/release-5.5/src/lib/dom.generated.d.ts#L21943).
  - Node's webstorage implementation, as in the web standard, intercepts undefined property access. This means that statements like `storage['key'] = 'value'` and `delete storage['key']` etc. are valid equivalents to `storage.setItem(...)` and `storage.removeItem(...)` etc.
  - The indexed property signature has to be of type `any` rather than `string`, as the string index also matches the interface method names.
  - This also necessitates adding conditional merging into the global interface, similar to the undici imports, otherwise TypeScript will complain about duplicate index signatures.
- Removes references to event dispatching in the docblocks, as Node's implementation doesn't dispatch DOM events.

Resolves #70320.

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/blob/v22.x/src/node_webstorage.cc
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/node/test/globals.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6c1c3b0ed2a371787c6d04573e5802810db615a9
</p>

**Review by Semigradsky — APPROVED** [review]

**Comment by Semigradsky** [comment]
@jakebailey please take a look!

**Review by jakebailey — APPROVED** [review]
LGTM though you're going to be increasing the time to check `@types/node` by 50%, so be warned about that.

**Comment by Renegade334** [comment]
> LGTM though you're going to be increasing the time to check `@types/node` by 50%, so be warned about that.

Providing the performance impact is isolated to testing the one package, I think this should be OK?

**Comment by jakebailey** [comment]
Yes though on my machine it takes like a minute to test the one package 😄

**Comment by Renegade334** [comment]
We'll see how things go...

Ready to merge 🤖

**Pull request merged**
