### PR TITLE
redux-form: loosen redux dependency to also allow v4

### PR DESCRIPTION
**Pull request by martinandert**
Redux-form has added support for Redux 4 in version 7.4.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by maartenvanvliet** [comment]
@VincentBel Not sure why I'm being mentioned 🙂

**Comment by VincentBel** [comment]
@maartenvanvliet Oh, sorry... I mean @martinandert

**Comment by VincentBel** [comment]
@martinandert You can take a look at my WIP implementation:
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...VincentBel:redux-form-7.4

**Comment by martinandert** [comment]
@VincentBel Since you've already made more progress than me, I'm happy for you to take over. WDYT?

**Comment by VincentBel** [comment]
Surely, I'll make a PR when ready.

**Comment by martinandert** [comment]
Closing in favor of #26977.

**Pull request closed without merging**
