### PR TITLE
Lint react-* packages

### PR DESCRIPTION
**Pull request by ghost**
New rules added by #15482

### CODE REVIEW

**Comment by eirikurn** [comment]
This PR breaks a lot of function signatures.

It changes this:
```
interface Foo {
  someFunc: () => {}
}
```

Into this, which is not the same signature:
```
interface Foo {
  someFunc(): {}
}
```

This breaks [react-portal](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15526/files#diff-5bf1ede7845d00763ab7aa2691e3aeb4) and probably some others.

**Comment by andy-ms** [comment]
@eirikurn What error are you getting?

**Comment by aaronbeall** [comment]
Wasn't clear to me at first but now I see the return type changed. It should be `someFunc(): void;` etc

**Comment by andy-ms** [comment]
That's always what the return type was -- `() => {}` is a function type returning `{}`, not an arrow function -- but if `void` is the correct type, you could make a pull request.

**Comment by aaronbeall** [comment]
Oops yeah you're right... So I'm not clear how this is any different either

**Comment by eirikurn** [comment]
Ah. You're right!

I've created PR #19041 to fix the cases from this PR. If this is more common, it might warrant an addition to the "Common mistakes" section.

**Pull request merged**
