### PR TITLE
[passport-google-oauth20] Update `email_verified` type and override `passport.Profile` `provider` type

### PR DESCRIPTION
**Pull request by remscodes**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/passport-google-oauth20/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8895241e373a2bc39def346a67dda2933f3aade0
</p>

**Comment by ezintz** [comment]
I am not so sure about this changes, if I browse the Google OpenID connect documentation I can see it still as a string, see https://developers.google.com/identity/openid-connect/openid-connect#an-id-tokens-payload. Did it change on passport?

**Comment by remscodes** [comment]
I’m sure that this change comes from Google API and not from passport librairies.
I think they haven't updated their documentation yet.

I recently noticed that my (email_verified === "true") comparison was always false even for emails actually verified.

I got this profile object from my TS project using [passport-google-oauth20](https://github.com/jaredhanson/passport-google-oauth2?tab=readme-ov-file#passport-google-oauth20) :

Capture d’écran 2024-04-19 à 15 38 38

The  `_raw` property is the result body from "https://www.googleapis.com/oauth2/v3/userinfo" response ([passport-google-oauth20:strategy.js#L119](https://github.com/jaredhanson/passport-google-oauth2/blob/79f9ed6878f1d11150243a1429acb7ba3211e239/lib/strategy.js#L119))

The  `_json` property is simply `JSON.parse(body)` ([passport-google-oauth20:strategy.js#L103](https://github.com/jaredhanson/passport-google-oauth2/blob/79f9ed6878f1d11150243a1429acb7ba3211e239/lib/strategy.js#L103))

We can see that there is no parsing for `email_verified`, the `_raw` value comes directly from Google response.

I've looked in the sub-dependencies ([passport-oauth2](https://github.com/jaredhanson/passport-oauth2/blob/be9bf58cee75938c645a9609f0cc87c4c724e7c8/lib/strategy.js#L96) and [oauth](https://github.com/ciaranj/node-oauth/blob/0749d671f04b684ca255d6ff5340ae3efe711d9a/lib/oauth2.js#L224)) but there is nothing new that could convert `email_verified` into a boolean.

**Review by ezintz — APPROVED** [review]
The changes are looking good to me 👍 , thank you for clarifying!

**Comment by remscodes** [comment]
Ready to merge

**Pull request merged**
