### PR TITLE
node: make streams generic

### PR DESCRIPTION
**Pull request by KonanMentor**
Reopen #26410

## Motivation

1. Given the fact that `Readable` stream [became](https://github.com/nodejs/node/commit/61b4d60c5d) `AsyncIterable` in Node v10.0.0, I expect `for-await-of` way of iterating over streams to become more popular. As a result people may start using native streams more often. And probably they will be using the streams with their own data types (i.e. in object mode), so it will be great to check these data types.
2. There is no type support for streams in object mode. The only type streams operate is `string | Buffer` or `any`

## Use case

My use case is iterating over documents returned by MongoDB. So I could write

```ts
const docs = db.collection<MyDataType>('...').find();
// docs is Cursor<MyDataType>, which extends Readable stream
for await (const doc of docs) {
  // I expect doc to be MyDataType here, but it is string | Buffer at the moment
}
```
---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/stream.html
- [x] Increase the version number in the header if appropriate. (not appropriate)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (already done)

### CODE REVIEW

**Comment by rbuckton** [comment]
@KonanMentor, is there a specific reason why you need TypeScript 2.4 as the minimum instead of TypeScript 2.3? TS 2.3 added Type Parameter Defaults, which I assume is the primary feature needed to maintain backwards compatibility. We are discussing the possibility rolling forward the minimum supported TypeScript version and it would be helpful to know why so many packages would need to have their version numbers moved up to 2.4.

**Comment by KonanMentor** [comment]
@rbuckton, TypeScript 2.4 is needed to test `pipeline` use case.

```ts
stream.pipeline(
    new stream.Readable<number>(),
    new stream.Writable<string>(), // $ExpectError
);
```

It works because of [Improved inference for generics](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-inference-for-generics).

With 2.3 we'll have to write something like this:

```ts
stream.pipeline<number, stream.Writable<number>>(
    new stream.Readable<number>(),
    new stream.Writable<string>(), // $ExpectError
);
```

Which probably is not the way people will use it (tests should reflect actual use cases).

Otherwise there will be an error:

```
ERROR: 1042:9  expect  Compile error in typescript@2.3 but not in typescript@2.4.
Fix with a comment '// TypeScript Version: 2.4' just under the header.
Argument of type 'Readable<number>' is not assignable to parameter of type '(WritableStream<any> | ReadWriteStream<any, any> | ReadableStream<any>)[]'.
  Property 'length' is missing in type 'Readable<number>'.
ERROR: 1043:1  expect  Expected an error on this line, but found none.
```

**Comment by ccorcos** [comment]
Was this ever merged?

**Comment by KonanMentor** [comment]
@ccorcos Unfortunately no. Both PRs were closed automatically. I can reopen it one more time, but I'm not sure that the third PR will have more attention than the previous two.

**Comment by ccorcos** [comment]
Bummer. What's the holdup?

**Comment by ccorcos** [comment]
Seems like we should be able to create a generic stream with default args of string | Buffer and it would be backwards compatible.

**Comment by argv-minus-one** [comment]
Now that [`typesVersions` has landed](https://github.com/Microsoft/TypeScript/pull/26568), how about giving this another go?

**Comment by KonanMentor** [comment]
@argv-minus-one good idea. Let's wait for #30477 to get merged first.

**Comment by filipsuk** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30477 has been closed, can we expect this to be merged? It would be really great to have this 😇

**Comment by KonanMentor** [comment]
@filipsuk I'm not sure that I will have enough time to do this in the next couple of months. If someone is willing to push this changes, feel free to use the code of this PR

**Comment by ccorcos** [comment]
I'v been using it for a while. Just patched it in.

**Pull request closed without merging**
