### PR TITLE
Add `usePushEach` flag to Mongoose Schema Options

### PR DESCRIPTION
**Pull request by stieg**
In order for devs to be able to work around the issues described in
https://github.com/Automattic/mongoose/issues/5574 we need to be able
to supply the `usePushEach` flag to the Mongoose SchemaOptions. This
options functionality is described in
https://github.com/Automattic/mongoose/issues/4455 and is required for
anyone who modifies arrays inline who is using Mongoose 4 and MongoDB
3.6+

Testing:
  Copied changes to local project and verified compilation worked.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by simonxca** [comment]
Thanks LGTM.

**Review by simon-xiong-ca — APPROVED** [review]

**Review by sindrenm — APPROVED** [review]

**Comment by EtienneBoutet** [comment]
Did the option been added ? It's not there in 5.0.16..

**Comment by stieg** [comment]
Hrmm... Option was added in commit d512b1f5d139c64bf413e2df6a659f8dfb86219a but seems to have been removed in commit ccdc539cc42a46f3abf93a6cfa75cafc864da502 by Art <a.molcanovas@gmail.com>.  Maintainers... know whats up with this?  This because of mongoose 5 and this feature may be unnecessary now (my best guess)?

**Comment by EtienneBoutet** [comment]
The problem still exists with Mongoose (¢pushAll).. I did another PR for this and they added it.. Do you know any work around if they decide to remove it once again ?

**Comment by stieg** [comment]
@EtienneBoutet I simply did a type assertion to work around the issue when defining my Schema Options.  Something like this was my workaround

```ts
const MySchema = new Schema({
   ...
}, {
   timestamps: true,
   usePushEach: true,
 } as SchemaOptions
```

**Comment by EtienneBoutet** [comment]
Thanks a lot ! 👍

**Pull request merged**
