### PR TITLE
Support forthcoming changes to `Iterator` type in TS 5.6

### PR DESCRIPTION
**Pull request by rbuckton**
In an effort to clean up the definitions of `Iterator`, `IterableIterator`, and `Iterable` (as well as their `Async` variants) to make way for types for the ECMA262 Iterator Helpers proposal, https://github.com/microsoft/TypeScript/pull/58243 makes a few changes to these types that result in several breaks in some type packages.

This has been authored as a Draft PR for now, as https://github.com/microsoft/TypeScript/pull/58243 is still in flux and has not yet been merged.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/microsoft/TypeScript/pull/58243
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.~~

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
for es-get-iterator, es-abstract, and get-intrinsic

**Review by ljharb — APPROVED** [review]
and for call-bind and string.prototype.matchall

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Seems like the main CI is very unhappy; is this PR good to go? https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/10020029984

**Comment by jakebailey** [comment]
Close/reopening to see if nightly is happy.

**Comment by jakebailey** [comment]
Ah, shoot

**Comment by jakebailey** [comment]
I went ahead and fixed everything, except that `jsreport-jsrender` and `jsreport-phantom-pdf` fail due to:

```
/home/jabaile/work/DefinitelyTyped/types/jsreport-phantom-pdf/jsreport-phantom-pdf-tests.ts
  35:47  error  TypeScript@5.6 compile error: 
Argument of type 'Buffer' is not assignable to parameter of type 'string | ArrayBufferView'.
  Type 'Buffer' is not assignable to type 'Uint8Array | DataView'.
    Type 'Buffer' is not assignable to type 'Uint8Array'.
      The types returned by 'entries()' are incompatible between these types.
        Type 'IterableIterator<[number, number]>' is missing the following properties from type 'BuiltinIterator<[number, number], any, any>': map, filter, take, drop, and 8 more  @definitelytyped/expect

```

Which doesn't make sense because `Buffer` extends `Uint8Array`. But, reading the definition of `Buffer`, it says:

```
entries(): IterableIterator<[number, number]>;
```

Are node types actually broken and only working because we don't test a high enough lib?

**Comment by jakebailey** [comment]
In the latest commit, I removed the redundant iterator methods from `Buffer`; these are already defined on `Int8Array`, but now that the upstream definition has changed, the redeclaration no longer matched and broke things.

Removing them should be "okay" because they are already declared, but will lose the extra doc.

It's not clear to me why this wasn't an error except via other files; we test with ES6, which is pretty low to ensure compat with newer methods, but setting lib to esnext did not reproduce the problem either.

**Pull request merged**
