### PR TITLE
Feature/fs extra symlink

### PR DESCRIPTION
**Pull request by alan-agius4**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureSymlink.md>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by alan-agius4** [comment]
@midknight41, @shiftkey, @mees-

**Comment by alan-agius4** [comment]
@andy-ms do you know how to solve 'can't parse definition header...' please?

**Comment by andy-ms** [comment]
dt-bot will just need to be updated some day to handle multi-line headers. This is dt-bot's fault, not the code's.

**Comment by alan-agius4** [comment]
So u suggest to keep them in a single line for now?

**Comment by andy-ms** [comment]
Up to you.

**Comment by alan-agius4** [comment]
Any feedback about this PR please?

**Comment by shiftkey** [comment]
@alan-agius4 belated :thumbsup: to the change. [The source](https://github.com/jprichardson/node-fs-extra/blob/096a8e100273ffd2f3ee0cf58bea6799b1c1c8e1/lib/ensure/symlink.js#L20) totally agrees with the docs.

**Comment by alan-agius4** [comment]
@andy-ms can we have this merged pls? Thanks

**Pull request merged**
