### PR TITLE
[cookie-session] Make props optional for usability with sharedSession (#27288)

### PR DESCRIPTION
**Pull request by jonaaix**
isChanged, isNew, isPopulated, session now marked as optional to fix issue #27288

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
Test fails with:
```sh
Error in cookie-session
Error: Since this type definition includes a header (a comment starting with `// Type definitions for`), assumed this was a DefinitelyTyped package.
But it is not in a `DefinitelyTyped/types/xxx` directory.
    at assertPathIsInDefinitelyTyped (/Users/btxtiger/repositories/github/FORK-DefinitelyTyped/node_modules/dtslint/bin/index.js:112:15)
    at /Users/btxtiger/repositories/github/FORK-DefinitelyTyped/node_modules/dtslint/bin/index.js:93:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/btxtiger/repositories/github/FORK-DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error: The following packages had errors: cookie-session
    at /Users/btxtiger/repositories/github/FORK-DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:121:8
    at Generator.next (<anonymous>)
    at fulfilled (/Users/btxtiger/repositories/github/FORK-DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
npm ERR! Test failed.  See above for more details.
```
I tried to find the source of the issue but, to be honest I have no idea where it comes from.

- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
Fails with same error as above

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes:
```ts
import http from 'http';
import express from 'express';
import socketIO from 'socket.io';
import cookieSession from 'cookie-session';
import sharedSession from 'express-socket.io-session';


let app = express();
let server = http.createServer(app).listen(3000);
let socket = socketIO(server);

const session = cookieSession({
    name: 'myName',
    keys: ['123456789'],
    secret: '112233',

    // Cookie Options
    maxAge: 24 * 60 * 60 * 1000 * 30, // 30 days
});

app.use(session);
socket.use(sharedSession(session));
```
- [?] Increase the version number in the header if appropriate.
- [?] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by omarryhan** [comment]
I'm not sure from which module/namespace the other `Session` object is coming from. But you can add an optional `isChanged` to it.

**Comment by btxtiger** [comment]
@omarryhan To be honest, after two years, I have no idea what I did there. As far as I remember I dropped the library because of too many incompatibilities and switched to JWT. I think the session should have been readable by the socket. Why does it force not null assertions, as the change effects just the socket?

> Both libraries are not compatible with each other because their interfaces aren't matching.

I agree

**Comment by omarryhan** [comment]
I feel you, I don't remember the code I wrote a month ago :).

> Why does it force not null assertions, as the change effects just the socket?

It affects the `app.session` interface in general. And because you marked the session as optional, TS warns you whenever you try to access anything in `app.session` because `app.session` might be undefined. So, to fix this, you have to assert to TS that `app.session` isn't undefined. So, all over my code I have something like this:

```javascript
app.session!.foo
app.session!.bar
```

**Comment by btxtiger** [comment]
> app.session!.foo

Did you mean `app.session?.foo` ?
I had this warning never enabled, I didn't even know there exist that compiler option. If thats the case then reverting my PR might be the right way.

**Comment by omarryhan** [comment]
@btxtiger

> Did you mean app.session?.foo ?

That'll probably work too but only in simple cases. But if you get `foo` and start doing stuff with it in your route handler, then the typescript compiler will show errors because the value might be undefined. Ofcourse, you can add if undefined statements all over your code, but that would be weird given that the session for sure exists. You'll be better off using non-null assertions in that case, which is basically telling Typescript that this value is for sure not null (nor undefined). Ultimately, I think fixing the typings is the best solution

**Pull request merged**
