### PR TITLE
[node]: Add signal to client request options

### PR DESCRIPTION
**Pull request by spalger**
`signal` parameter is missing in `ClientSessionRequestOptions`.

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
[clienthttp2session.request(headers[, options])](https://nodejs.org/dist/latest-v16.x/docs/api/http2.html#clienthttp2sessionrequestheaders-options)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by spalger** [comment]
Done in [`3cbfb80` (#59828)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59828/commits/3cbfb800a9cbba31816005ed240e81091bef69e8) @peterblazejewicz

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@spalger thx!

**Comment by spalger** [comment]
@peterblazejewicz do these CI errors make sense to you? They don't seem to make sense based on my changes but maybe I'm missing something.

**Comment by spalger** [comment]
@peterblazejewicz Looks like [other trivial changes to the node types fail similarly](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59587)... Seems to me the tests are broken

**Comment by peterblazejewicz** [comment]
FYI: I've updated with recent master as fixes for @types/node just landed, thx!

**Review by peterblazejewicz — APPROVED** [review]

**Pull request merged**
