### PR TITLE
Electron - Add extra options for SaveDialog & OpenDialog

### PR DESCRIPTION
**Pull request by DenisCarriere**
Missing options pulled from Electron's website:
- `OpenDialogOptions`: https://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback
- `SaveDialogOptions`: https://electron.atom.io/docs/api/dialog/#dialogshowsavedialogbrowserwindow-options-callback

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by unindented** [comment]
👍

**Review by rhysd — APPROVED** [review]
Thank you for catching them.

**Comment by rhysd** [comment]
Note: If possible, adding some test cases for them would help type definition validation.

**Comment by DenisCarriere** [comment]
@rhysd Added `showSaveDialog` & `showOpenDialog` in test cases.

Please `squash commits` when merging, had a commit convert tabs to spaces 🤦‍♂️ .

**Pull request merged**
