### PR TITLE
Update teact-native typings to react-native@0.34

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by bgrieder** [comment]
@vladimir-kotikov  3,037 additions, 700 deletions ? Really ?
If this is a code reformat effect, could you please roll-back to the previous version and just make your changes (with some description plz) ?

**Comment by vladimir-kotikov** [comment]
@bgrieder, I understand your skepticism, but this is not an effect of code reformatting. We have revisited almost all APIs, exposed in react-native@0.34 and have added a dozen of new ones, including UIManager, InteractionManager, ImageStore, ImageEditor, etc.

We've also been adding a JSDoc to new/existing API members - this is another reason of such big amount of changes.

I did another review and reverted most of non-significant changes (whitespace and formatting) to make diff smaller. Unfortunately it's still quite large. Please let me know if I can do anything else to make it easier to review.

**Comment by bgrieder** [comment]
@vladimir-kotikov Fair enough. Thanks. Let me run a few tests and get back to you ASAP

**Comment by vladimir-kotikov** [comment]
That'd be perfect. Thanks!

**Comment by bgrieder** [comment]
Changes are too many for Github to allow reviewing on the file so I will do it in comments.

The changes are significant, so at this stage I am tempted to rename the existing definition files react-natice-29.d.ts and leave it as part of the definitions.

These changes are welcome:

 - better documentation
 - definition of types when the typing was done 'inline' typically for union types with string literals e.g. whe we used to have a property
     
        keyboardType?: "default" | "email-address" | "numeric" | "phone-pad" | "ascii-capable" | "numbers-and-punctuation" | "url" | "number-pad" | "name-phone-pad" | "decimal-pad" | "twitter" | "web-search"
       
   we now have
   
        keyboardType?: KeyboardType | KeyboardTypeIOS
       
   with `KeyboardType` and `KeyboardTypeIOS` properly defined
   
 - many new or missing Classes
   
        
I have performed random checks against the doc on methods and properties which have been added or removed and all checks were OK.

Great

There are a couple of things which I believe are opened for debate though:


1. The injection of lib es6 `Promise` definition. I do not believe this is necessary since the compilation target is set to ES6 and this definition will be available from lib.es6.d.ts.

2. It seems that "undocumented" methods and properties were systematically removed. Are you sure thes methods and properties have actually been removed from the implementation ? An example is in `TextInputStatic` 

        // The following methods are found only in implementation
        blur: () => void
        focus: () => void
        
Finally, I think we should keep the style consistent. For instance, the following type definition is syntactically fine but why not use an `Interface` as with the rest of the code ?          


    export type RelayProfiler = {
        attachProfileHandler(
            name: string,
            handler: (name: string, state?: any) => () => void
        ): void,

        attachAggregateHandler(
            name: string,
            handler: (name: string, callback: () => void) => void
        ): void,
    }


In any case, impressive work, thanks.

**Comment by bgrieder** [comment]
@vladimir-kotikov Many Thanks

👍 

Please merge

**Comment by vladimir-kotikov** [comment]
@bgrieder, thanks for review!

> The injection of lib es6 Promise definition

Agree, this seems to be excessive, removed.

> It seems that "undocumented" methods and properties were systematically removed. Are you sure these methods and properties have actually been removed from the implementation?

Yeah, i'm pretty sure, because we actually went through react-native code (not every file, of course, but top-level APIs) to update definitions. As for `blur` and `focus` in `TextInput` - I'm not sure if they existed before, but as of now [TextInput.js](https://github.com/facebook/react-native/blob/0.34-stable\Libraries\Components\TextInput\TextInput.js) doesn't have these fields.

> Finally, I think we should keep the style consistent. 

Consistency is gold :) Updated

**Comment by bgrieder** [comment]
👍

**Pull request merged**
