### PR TITLE
Fix return type of NodeJS.ReadableStream#read

### PR DESCRIPTION
**Pull request by rubensworks**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/pull/21178

### CODE REVIEW

**Review by hoo29 — CHANGES_REQUESTED** [review]
https://github.com/Microsoft/dtslint/blob/master/docs/no-any-union.md states this offers no additional type safety so the pull request in unnecessary.

**Comment by KSXGitHub** [comment]
`any` only occur under object mode

**Comment by KSXGitHub** [comment]
`any` is not really helpful. If you really want to support object mode, you should create a `ObjectModeBuffer` and a system of functions around it.

**Comment by KSXGitHub** [comment]
@rubensworks By read, you meant `readdable.read()`? you can have a `ObjectModeReadable#read` that returns `any` and leave `Readable#read` for `string | Buffer`. Another alternate solution is to make `Stream`/`Readdable`/`Writable` generic. `ObjectMode*` types are returning value when one provides object-mode options (such as `objectMode: true`, `readdableObjectMode: true`, `writableObjectMode: true`) to functions that create `Stream`s.

Personally, I find doing this is way too complicated that it isn't worth it. Not to mention this pull request is guaranteed to break existing TypeScript projects which have always assumed `Stream` contains `Buffer`. I also find no real use of object mode anyway.

**Comment by rubensworks** [comment]
> Another alternate solution is to make Stream/Readdable/Writable generic.
> ...
> Personally, I find doing this is way too complicated that it isn't worth it.

Agreed, this change would be pretty invasive. I'd want second/third/... opinion on this before I implement this.

> I also find no real use of object mode anyway.

I'm pretty sure lots of people _do_ have a use for object mode ;-) (This W3C community group is just one example: http://rdf.js.org/#stream-interface)

**Comment by hoo29** [comment]
Losing type safety for the non-object mode streams does not seem optimal. In lieu of doing a substantial pull request to create an ObjectModeReadable interface, would it not be better to simply cast to any the stream in your code?

**Comment by rubensworks** [comment]
> In lieu of doing a substantial pull request to create an ObjectModeReadable interface, would it not be better to simply cast the stream to any in your code?

Surely, I'm not the only one with this problem. So to let everyone experiencing this cast away the problem seems to go in against the ideas of TypeScript. So I don't consider this a good alternative.

As is stands now, the typings are simply wrong, which needs fixing. This PR does exactly that.
An `ObjectModeReadable` is indeed a more generic fix, but requires significant changes.

Perhaps one of the core maintainers of DT can chime in and share their thoughts?

**Comment by Flarna** [comment]
> Perhaps one of the core maintainers of DT can chime in and share their thoughts?

I'm not a core maintainer - not sure if there are ones but I can share my thoughts.

I think there is already a #26410 to address this by converting stream into generics. Quite a big PR as it requires to raise minimum typescript version to 2.4 so not sure if this will be merged soon/at all.

To my understanding this would correct the issue mentioned here plus add the possibility to use more concrete typing for e.g HTTP/TCP streams which never use object mode.

To me this looks like a good starting point.

**Review by hoo29 — APPROVED** [review]

**Comment by hoo29** [comment]
Fair enough - I am convinced!

**Comment by KSXGitHub** [comment]
We should also watch out for breaking changes. It is guaranteed to happen.

**Comment by minestarks** [comment]
I'm holding off on merging this until a call is made on #26410

**Comment by ZaneHannanAU** [comment]
Yeah. Presuming certain ones is awkward.

If we say that streams in normal mode return buffers, we should extend it so it has `BufferModeStream`, `StringModeStream` and `ObjectModeStream<T>`.
Any type is too varied.

**Comment by ZaneHannanAU** [comment]
But that'd just cause concurrency hell…

**Comment by andy-ms** [comment]
We'll be implementing `typesVersions` (Microsoft/TypeScript/pull/26568) soon on DefinitelyTyped which should allow us to make non-backwards-compatible changes to packages like node. At that point something more type-safe like #26410 would be preferrable to just using `any`.

**Pull request closed without merging**
