### PR TITLE
update angular2 typings to 2.0.0-alpha.30

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by alexeagle** [comment]
LGTM

**Comment by thelgevold** [comment]
+1

**Comment by gdi2290** [comment]
:+1:

**Comment by alexeagle** [comment]
@vvakame ping!

**Comment by thelgevold** [comment]
I grabbed the alpha.30 file and from what I can tell - it works well: 
https://github.com/thelgevold/angular-2-samples

**Comment by vvakame** [comment]
@alexanderby @thelgevold @gdi2290 thanks!
@jeffbcross thanks mate!

**Pull request merged**
