### PR TITLE
updates flickity definitions for version 2 and enables use as a module

### PR DESCRIPTION
**Pull request by wagich**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://flickity.metafizzy.co/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Manual notification for @clmcgrath since bot says "account can't be detected".

### CODE REVIEW

**Comment by clmcgrath** [comment]
Will review when I get to my Dev pc

**Comment by RyanCavanaugh** [comment]
Waiting for @clmcgrath

**Comment by RyanCavanaugh** [comment]
@clmcgrath 🔔

**Comment by clmcgrath** [comment]
Looks fine to me

**Pull request merged**
