### PR TITLE
styled-components: Add reexport test

### LINKED ISSUE #28629: [@types/styled-components] ThemedStyledComponentsModule from documentation does not compile
@Igorbek @probablyup originally posted this in styled-components/styled-components#1959 and was told to post here.

Implementing example from docs (small change to avoid multiple imports from same module):

```
import * as styledComponents from 'styled-components'
import { ThemeInterface } from 'types'

const {
  default: styled,
  injectGlobal,
  keyframes,
  ThemeProvider,
  withTheme,
  css
} = styledComponents as styledComponents.ThemedStyledComponentsModule<ThemeInterface>

export { injectGlobal, keyframes, ThemeProvider, withTheme, css }
export default styled
```

Results in compilation error:
`This assertion is unnecessary since it does not change the type of the expression.`

I can confirm that the type of the individual methods is changing.  

E.g. the type for 'css' changes from:
`StyledComponents.ThemedCssFunction<Any>`

To:
`StyledComponents.ThemedCssFunction<ThemeInterface>`

Styled-Components Version: `3.4.2`
Typescript Version: `3.0.1`

### PR DESCRIPTION
**Pull request by lifeiscontent**
closes #28629

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/ahoisl/DefinitelyTyped/blob/9f0a302aaa99400bf7c44a4f3ecbecf049b6946e/types/styled-components/index.d.ts#L350-L356>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@RyanCavanaugh this is a follow-up to #53525 which you requested I add a test.

**Comment by orta** [comment]
What makes us wary (as DT maintainers) is that this and the last PR do not have comments from folks who own this module - all of the last comments are from the TypeScript team. I'm generally alright with the PR, given that II expect this library to be well tested at this point and you've covered your changes - but I'd like to give a chance for others to raise their opinion.

**Review by eps1lon — APPROVED** [review]

**Comment by lifeiscontent** [comment]
@orta it's been 3 weeks, can we move forward?

**Comment by orta** [comment]
Yeah, 👍🏻

**Pull request merged**
