### PR TITLE
[google-map-react] add optional mapId to MapOptions

### PR DESCRIPTION
**Pull request by jakeFeldman**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Adding missing type to the MapOptions interface as defined here https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.mapId

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## google-map-react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/google-map-react@latest/))
was missing the following properties:
1. propTypes
1. defaultProps
1. googleMapLoader
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f33eb11541546ce9dbe4e6ef1ee424e9190f8943
</p>

**Review by martin-badin — APPROVED** [review]
Looks good

**Comment by jakeFeldman** [comment]
Hey @honzabrecka, hope you're well. Would you mind taking a peek at this PR. Thanks in advance!

**Comment by jakeFeldman** [comment]
Hey @honzabrecka. Just following up here. Would you mind taking a peek at this PR. Thanks!

**Review by martin-badin — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jakeFeldman** [comment]
Ready to merge

**Pull request merged**
