### PR TITLE
Convert highcharts definitions to module style

### LINKED ISSUE #12438: [Highcharts] Missing files in npm for @types/highcharts
-  I tried using the latest highcharts in this repo and had problems.

Optional modules like highcharts-more, exporting, boost, etc.. all have their own d.ts inside the branch 2.0, but when I install the package with `npm install @types/highcharts`, thoses files are not created.

I noticed that they do not appear in the `files` section of `tsconfig.json`:

```
    "files": [
        "index.d.ts",
        "highstock.d.ts",
        "highcharts-tests.ts",
        "highstock-tests.ts"
    ]
```

And, while being into the 2.0 branch, those files still contains `/// <reference...`, which looks like a thing from the past:

```
/// <reference path="highcharts.d.ts" />
declare var HighchartsMore: (H: __Highcharts.Static) => __Highcharts.Static;
declare module "highcharts/highcharts-more" {
    export = HighchartsMore;
}
```

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [ ] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [ ] Provide a URL to  documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

Based on discussion in #11385.

This converts the declaration to use the following:
* `declare namespace Highcharts { ... }`
* `declare global { var Highcharts: Highcharts.Static; }`
* `export = Highcharts; export as namespace Highcharts;`

This allows `Highcharts` to be used in both global and non-global contexts.
It can be augmented by a module augmentation (rather than namespace augmentation as before).
@RandScullard, @tedcurrent, @subash-a, @mc-suchecki, @baltie
Could someone working on a `highcharts` project try this out?

Update: Now also fixes #12438

### CODE REVIEW

**Comment by RandScullard** [comment]
No, this is not working for me. When my code hits the first reference to Highcharts I get:

    Uncaught ReferenceError: Highcharts is not defined(…)

This is the same behavior I get with @types/highcharts version 4.2.38, but not with 4.2.37.

**Comment by andy-ms** [comment]
@RandScullard `highcharts-tests.ts` works for me even without the import, so the global variable should be available. Could you check that you're successfully referencing the "highcharts" types? Can you provide a sample file that doesn't work for you?

**Comment by RandScullard** [comment]
I'm using Highcharts via an import, not a global variable -- that's the problem. When I compile my project with your new definitions, TypeScript seems to think Highcharts is global and therefore it doesn't need to generate the require. When I look at the generated .js file, it has all of my other require statements but Highcharts is not there. When I go back to 4.2.37 and recompile, the require statement comes back.

**Comment by andy-ms** [comment]
Thanks for the help. There indeed was a global `Highcharts` overriding the `Highcharts` you tried importing.

**Comment by RandScullard** [comment]
Yes! That fixes it for me.

Hey, would you happen to know why highcharts-more.d.ts isn't being included in the @types/highcharts package? I'm currently doing `require("highcharts/highcharts-more")(Highcharts);` but I'd rather use `import`.

**Comment by andy-ms** [comment]
Looks like the same issue as #12438. I just made a commit that fixes this as well.

**Comment by RandScullard** [comment]
...and I just tested it and it works great! Thanks for that.

**Pull request merged**
