### PR TITLE
Update definition owners for countryjs and add type declarations for country-emoji

### PR DESCRIPTION
**Pull request by ImRodry**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

In this PR I added definition owners for my previous package countryjs and added type declarations for country-emoji.
country-emoji had its own type declarations added in v1.5.5, however, these were not uploaded to npm so I'm adding this to fix that and will remove it if the issue is ever fixed.

### CODE REVIEW

**Comment by ImRodry** [comment]
> 🔔 @DefinitelyTyped — please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51779/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

Yeah oopsie that's my bad, sorry for that

**Comment by ImRodry** [comment]
If needed I can split these changes into 2 PRs in case there is an issue with submitting both of them in the same PR.

**Comment by martin-badin** [comment]
Do you need to create these types? The original package has their own types https://github.com/meeDamian/country-emoji/blob/master/index.d.ts

**Comment by ImRodry** [comment]
> Do you need to create these types? The original package has its own types https://github.com/meeDamian/country-emoji/blob/master/index.d.ts

Yes I know but for some reason when the author made the lastest package, the index.d.ts file didn't export correctly so if you install it you still don't get the types, that's why I'm adding this until this issue is fixed, if it ever is.

**Pull request merged**
