### PR TITLE
chore(deps): Update dependency prettier to v3.0.0

### PR DESCRIPTION
**Pull request by kachkaev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- N/A ~~Test the change in your own code. (Compile and run.)~~
- N/A ~~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.~~
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- N/A ~~[Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).~~

---

- Context: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66073#discussion_r1265838080
- Similar PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47110

### CODE REVIEW

**Comment by kachkaev** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66073 is now merged – this PR was not a blocker as I thought initially. There is no rush upgrading to Prettier v3 in this repo, but it’d be nice to do this at some point anyway.

**Comment by jakebailey** [comment]
I suspect that this isn't really needed given we're likely to do https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993.

**Comment by kachkaev** [comment]
Closing in favour of https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65993

**Comment by gesiud** [comment]
Hello @kachkaev . I'm struggling with prettier types in my Angular application. I need to use prettier inside Angular component/service to format the given string.  With ~@types/prettier@2.7.3` it's working fine. Without it, I got an error like the following:

image

Is there any other way now to configure prettier and it's types?

**Pull request closed without merging**
