### PR TITLE
Instead of adding overload, fix the return type

### PR DESCRIPTION
**Pull request by michaelaird**
I had mistakenly added an overload. The correct fix is to add the return type to the existing method.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I don't think that this is the correct fix - `void` doesn't just merge into other types. Can you explain the specific behaviors that occur when given a string argument, and when no arguments?

**Comment by michaelaird** [comment]
From the source:

`            view: function (name) {
                var that = this;
                if (name) {
                    that._selectView(name);
                    that.rebind();
                    return;
                }
                return that._selectedView;
            },
`

the name is optional but the function always returns a view. 

I had mistakenly added an overload in the d.ts but this commit changes it to have an optional parameter and always return the  current view

**Comment by DanielRosenwasser** [comment]
Sounds like you want

```ts
    view(): kendo.ui.SchedulerView;
    view(type: string): void;
```

**Comment by michaelaird** [comment]
I think the way I have it now

```javascript
view(type?: string): kendo.ui.SchedulerView;
```

is correct. The function takes an (optional) parameter and always returns a kendo.ui.SchedulerView. Am I missing something?

**Comment by DanielRosenwasser** [comment]
The parameter is indeed optional, but you will never get a result if you call it with a `string`, so that signature is misleading. The function has two mutually exclusive results depending on what you give it. If you call it with a string argument, you'll most certainly not get anything useful. If you call it without, it (probably?) won't be `null` or `undefined`.

You could potentially write `view(type?: string): kendo.ui.SchedulerView | undefined` as the second overload, but if strict null checking code ever uses this, you're making life for those users unnecessarily difficult.

**Comment by michaelaird** [comment]
Yes. You're right! I totally misread the function. I saw the return statement at the end and thought that was the only return statement. Thanks for being so observant!

What's the best way for me to edit my commit? Should I cancel this pull request and make a new one?

**Comment by DanielRosenwasser** [comment]
It should just be a matter of the following steps.

1. Locally create a new commit on your branch
2. Update the branch on your repo
3. You don't have to do anything, GitHub will update this PR based on the state of your branch.

You can also [create a quick commit online](https://github.com/michaelaird/DefinitelyTyped/edit/patch-2/types/kendo-ui/index.d.ts?pr=/DefinitelyTyped/DefinitelyTyped/pull/16374), but that might be harder for kendo-ui.

**Comment by michaelaird** [comment]
Fixed! thanks for your help.

**Comment by DanielRosenwasser** [comment]
No prob, thanks!

**Pull request merged**
