### PR TITLE
Added support for backbone with lodash instead of underscore

### PR DESCRIPTION
**Pull request by graycodes**

### CODE REVIEW

**Comment by vvakame** [comment]
um? what's this? backbone-lodash?

**Comment by ytechie** [comment]
I'm not the author, but I really want this to exist. This is needed for scenarios where you have backbone, underscore, and lodash all in the same project. There is no way to get it to compile, because the existing backbone type definitions is hard-coded to use underscore. This means you can't also add in typing information for lodash without causing conflicts.

**Comment by ytechie** [comment]
Actually, I may have found an easier solution by just modifying the backbone definition to remove the reference to underscore.

**Comment by ytechie** [comment]
I've submitted a PR for an easier fix: https://github.com/borisyankov/DefinitelyTyped/pull/6200

**Comment by graycodes** [comment]
Ah, brilliant. Thanks @ytechie , this solves the problem for us too.

**Comment by vvakame** [comment]
oh, I understand. I merged #6200 and make additional commit.
please check about https://github.com/borisyankov/DefinitelyTyped/blob/master/backbone/backbone-with-lodash-tests.ts

**Pull request closed without merging**
