### PR TITLE
[follow-redirects] Update function signatures

### PR DESCRIPTION
**Pull request by SPGoding**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/follow-redirects/follow-redirects/blob/2ede36d7c60d3acdcd324dcd99a9dbd52e4fb3a6/index.js#L449-L471
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## follow-redirects ([<kbd>unpkg</kbd>](https://unpkg.com/browse/follow-redirects@latest/))
was missing the following properties:
1. maxRedirects
1. maxBodyLength
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 67a4c400162433d3bd51f2e408c9b08488e3bd14
</p>

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@SPGoding thx!

**Comment by SPGoding** [comment]
Ready to merge

**Comment by mlntdrv** [comment]
There is some breaking change, code starts failing with:
> Each member of the union type '{ (options: string | URL | (RequestOptions & FollowOptions<RequestOptions>), callback?: ((res: IncomingMessage & FollowResponse) => void) | undefined): RedirectableRequest<...>; (url: string | URL, options: RequestOptions & FollowOptions<...>, callback?: ((res: IncomingMessage & FollowResponse) => void) | undefined)...' has signatures, but none of those signatures are compatible with each other.

Code is
`(true ? http : https).request(options, (response) => {});`

**Pull request merged**
