### PR TITLE
adds type definitions for jasmine-promise-matchers

### PR DESCRIPTION
**Pull request by matthewjh**

### CODE REVIEW

**Comment by vvakame** [comment]
*jasmine-promise-matchers/jasmine-promise-matchers.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/jasmine-promise-matchers
  * http://bower.io/search/?q=jasmine-promise-matchers
  * others?
* [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (jasmine-promise-matchers/jasmine-promise-matchers-tests.ts or others)
* [ ] pass the Travic-CI test?

**Comment by matthewjh** [comment]
Should all be done.

**Comment by vvakame** [comment]
wait a moment...

**Comment by vvakame** [comment]
@matthewjh please rename jasmine-promise-matchers/jasmine-promise-matchers-test.ts to jasmine-promise-matchers/jasmine-promise-matchers-tests.ts

**Comment by matthewjh** [comment]
@vvakame:

Thank you. That should now be done.

**Comment by vvakame** [comment]
@matthewjh thanks mate!

**Pull request merged**
