### PR TITLE
[sharp] specifies format type

### PR DESCRIPTION
**Pull request by dimitropoulos**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] ~[Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change~.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: `the types themselves`
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The result of this PR is that instead of `format` being typed as `string`, it's typed as to provide the real options.

Screenshot_20201222_094021

### CODE REVIEW

**Review by fdebijl — CHANGES_REQUESTED** [review]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50243 just merged with some changes to `toFormat()`, if you pull the master for this repo, merge it into your fork and resolve any conflicts you are good to go as far as I'm concerned

**Comment by dimitropoulos** [comment]
@Fdebijl updated

**Review by fdebijl — APPROVED** [review]
LGTM, thanks for the update!

**Review by andrewbranch — APPROVED** [review]

**Comment by dimitropoulos** [comment]
Ready to merge

**Pull request merged**
