### PR TITLE
Made react-i18next typings compatible with strictNullChecks

### PR DESCRIPTION
**Pull request by KostyaEsmukov**
case 2. Improvement to existing type definition.

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
Hi @zhengbli,
Whose feedback are you awaiting? I'm the author.

**Comment by zhengbli** [comment]
Oops, sorry about that.

**Comment by zhengbli** [comment]
👍

**Comment by KostyaEsmukov** [comment]
@zhengbli That's all right. Thanks!

**Pull request merged**
