### PR TITLE
[@storybook/addon-links] Remove unnecessary MouseEvent argument

### PR DESCRIPTION
**Pull request by pelotom**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by joscha** [comment]
@pelotom can you give a bit more information about this, please?

**Comment by pelotom** [comment]
@joscha emprically, the callback returned by `linkTo` doesn’t require any particular argument, nor does it do anything special if the argument happens to be a `MouseEvent`. I’ve been using this (untyped) for months with props that either expected a no-arg callback or one that took argument(s) that are not `MouseEvent`s and it works perfectly well.

**Comment by armanio123** [comment]
I believe @pelotom is right that the callback doesn't require a return value. I'm going to merge this PR, if you feel this is incorrect, we can discuss and submit another PR for fixing it.

**Comment by pelotom** [comment]
Thanks @armanio123!

**Pull request merged**
