### PR TITLE
Bull: GetJob returns a promise of job or null

### PR DESCRIPTION
**Pull request by bondz**
Says it in the jsdoc even.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

### CODE REVIEW

**Comment by iamolegga** [comment]
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <> 🤔

**Comment by bondz** [comment]
@iamolegga The jsdoc says it right there, I assume its an oversight.

> * If the specified job cannot be located, the promise callback parameter will be set to null.

**Comment by iamolegga** [comment]
> The jsdoc says it right there, I assume its an oversight.
Sure, but it would be nice to provide link to docs in original repo, anyway, nice job, approve

**Review by iamolegga — APPROVED** [review]

**Comment by bondz** [comment]
Thanks @iamolegga Sorry I didn't clarify earlier.

**Pull request merged**
