### PR TITLE
change 'then' signature of promise that TS async/await is working

### PR DESCRIPTION
**Pull request by nerumo**
change 'then' signature of promise that TS async/await is working

### CODE REVIEW

**Comment by mhegazy** [comment]
@BillArmstrong, @Kuniwakand @cnishina, can you please review this change

**Comment by cnishina** [comment]
This is great! @filipesilva discovered that async/await was not working but we did not have a fix in for this. Looks like the typings were wrong.

@mhegazy LGTM.

**Comment by filipesilva** [comment]
I our test test suite we have this function, that with current typings outputs the error below:

```
async function heroFromDetail(detail: ElementFinder): Promise<Hero> {
  // Get hero id from the first <div>
  // let _id = await detail.all(by.css('div')).first().getText();
  let _id = await detail.all(by.css('div')).first().getText();
  // Get name from the h2
  // let _name = await detail.element(by.css('h4')).getText();
  let _name = await detail.element(by.css('h4')).getText();
  return {
    id: +_id.substr(_id.indexOf(' ') + 1),
    name: _name.substr(0, _name.lastIndexOf(' '))
  };
}
```

```
[01:03:09] [01:03:09] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
architecture\e2e-spec.ts (95,13): Operand for 'await' does not have a valid callable 'then' member. (1058)
architecture\e2e-spec.ts (98,15): Operand for 'await' does not have a valid callable 'then' member. (1058)
```

Our workaround thus far was to fast it to any, and then to `Promise<string>`:

```
let _id = await <Promise<string>>(<any>(detail.all(by.css('div')).first().getText()));
// ...
let _name = await <Promise<string>>(<any>( detail.element(by.css('h4')).getText()));
```

I can verify that with the fixes in this PR I no longer need the cast.

**Comment by mhegazy** [comment]
thanks for the review.

**Comment by dcbrwn** [comment]
promise.map is broken by this.

**Comment by dcbrwn** [comment]
image

**Comment by dcbrwn** [comment]
@filipesilva, this is all I got :) The fun thing is that when I comment .boox method, compiler calms down.

**Comment by filipesilva** [comment]
In your screenshot I can't see the method signature, which I needed to test it myself.

**Comment by dcbrwn** [comment]
```typescript
class Bar {
  boox() {
    return 'aksjhfkjashfd';
  }
}

class Test {
  foo(): promise.Promise<Bar[]> {
    return promise.map([1, 2, 3], (): Bar => {
      return new Bar();
    });
  }
}
```

**Comment by filipesilva** [comment]
I think I understand the problem. The new typings assume the argument type is the same as the return type.

**Comment by dcbrwn** [comment]
Yep. that's why I came here :)

**Comment by dcbrwn** [comment]
I guess changes should be reverted just for now, since they will break a lot of stuff of folks who are actively using promise.map/reduce.

**Comment by filipesilva** [comment]
Tbh I'm beginning to think that what this PR fixed was simply masking the broken `map` typings. 

The call signatures introduced here make sense as far as I can tell:
```
then<R>(opt_callback?: (value: T) => R|IThenable<R>, opt_errback?: (error: any) => any): Promise<R>;
```

A `then` with generic `R` should receive type `T` and return either `R` or `IThenable<R>`.

But map typings really are saying that, with generic type `T`, you should return `Promise<T[]>`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/selenium-webdriver/index.d.ts#L2177

**Comment by filipesilva** [comment]
The real fix seems to be editing the typings for map to accept two generics: `T` and `R`:
```
        function map<T,R>(arr: Array<T>|Promise<Array<T>>, fn: (self: any, type: any, index: number, array: any[]) => any, opt_self?: any): Promise<R[]>
```

I'll try to put a PR up with it, and check other places it's needed.

**Pull request merged**
