### PR TITLE
[yeoman-generator][yeoman-environment] Add missing types and fix outdated type-declarations

### PR DESCRIPTION
**Pull request by neurolag**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://yeoman.github.io/generator/>, <https://yeoman.github.io/environment/>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## yeoman-environment ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yeoman-environment@latest/))
was missing the following properties:
1. queues
1. util
1. once
1. EventEmitter
1. queues

<details>
<summary>as well as these 3 other properties...</summary>
<p>util, once, EventEmitter</p>
</details>

## yeoman-generator ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yeoman-generator@latest/))
was missing the following properties:
1. once
1. EventEmitter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8ddc90b9eee3dce835754adcb6120d59d73e5114
</p>

**Review by janslow — CHANGES_REQUESTED** [review]
LGTM, but as there's a lot of changes (some of which seem to be breaking changes), I think it's worth bumping the version of the definitions (i.e., the `// Type definitions for yeoman-*` comment, at the top of the `index.d.ts` files)

**Comment by manuth** [comment]
@janslow thanks for reminding me
Looks like I forgot to push the version-change because these typings indeed are for yeoman-generator v4 rather than v3
I'll go bump the version right away.

**Review by janslow — APPROVED** [review]
Great, thanks!

**Comment by manuth** [comment]
@janslow looks like I have to add some new tests for `yeoman-environment` - I'll go create one or two in a few mins

**Review by janslow — APPROVED** [review]

**Review by tasadar2 — APPROVED** [review]

**Comment by manuth** [comment]
I decided to refactor the typings for the `yeoman-environment` module alongside the `yeoman-generator` and converted this PR to a draft until I'm done

Thanks for your review, guys :D

**Comment by manuth** [comment]
Oh yeah I've got, btw, no idea why the performance got lower.
Could you have a look at this matter while reviewing?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by manuth** [comment]
Ready to merge

**Pull request merged**
