### PR TITLE
Expose interfaces in BrowserSync.d.ts

### PR DESCRIPTION
**Pull request by joeskeen**
This is a fix for #6382 
@tkrotoff, @andrewconnell, does this fix the issue satisfactorily?

### CODE REVIEW

**Comment by tkrotoff** [comment]
Great!

Would be nice though to test `browserSync.Options` (so there is no regression in the future), for example https://github.com/joeskeen/DefinitelyTyped/blob/issue-6382/browser-sync/browser-sync-tests.ts#L21:

```TypeScript
var config: browserSync.Options = {
  ...
};
```

Also the indentation got smashed, example:
```TypeScript
/**
* The initial path to load
*/
```
instead of
```TypeScript
/**
 * The initial path to load
 */
```

**Comment by joeskeen** [comment]
@tkrotoff thanks for your valuable feedback!  I have updated the tests to ensure the interfaces don't get hidden again, and re-formatted the comments.

**Comment by tkrotoff** [comment]
Thx, LGTM!

**Comment by vvakame** [comment]
@pspeter3 can I merge this PR?

**Comment by pspeter3** [comment]
lgtm

**Comment by andrewconnell** [comment]
+1… LGTM!

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
