### PR TITLE
Add missing limit option to bull package.

### PR DESCRIPTION
**Pull request by hisorange**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md Line 259

Verified in code and documentation.

### CODE REVIEW

**Comment by hisorange** [comment]
Travis is not failing because of this change, and I have seen a pending branch which fixes the failing test.

**Comment by DanielRosenwasser** [comment]
Build restarted.

**Comment by marshall007** [comment]
LGTM (pending fix for build failure in #23715)

**Comment by DanielRosenwasser** [comment]
Thanks for your patience!

**Pull request merged**
