### PR TITLE
[oidc-provider] Expose as ESM module

### PR DESCRIPTION
**Pull request by BendingBender**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/panva/node-oidc-provider/blob/main/package.json#L47
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by panva — CHANGES_REQUESTED** [review]
I'm not sure what this is helping and I can't reproduce #64148 without this change either.

Please do a minimal reproduction repo without this change to demonstrate the problem this solves.

**Comment by BendingBender** [comment]
@panva See https://github.com/BendingBender/oidc-provider-error-repro.

**Review by panva — COMMENTED** [review]
Thank you, that is really helpful.


There are only exactly 13 occurences of `"type": "module"` in the whole of DefinitelyTyped, that's 13 out of ~8800 type packages so I find it very unlikely this is intended behaviour or the intended solution.

It would be great if the maintainers of DT could speak to this or more documentation for this behaviour was provided.

**Comment by BendingBender** [comment]
I think it's the way to go. ESM types are kind of new to TypeScript and ESM-only (like this package) are even more rare. So this is actually the way to go.

**Comment by panva** [comment]
Why would the types package need to have a "type" at all. It's already present in the actual imported package.

Is there any documentation for this behaviour I can verify that this is the intended way with?

**Comment by BendingBender** [comment]
Just because it changes the module resolution algorithm. In my reproduction example you can see that without this setting, the module resolution algorithm works differently. The fact that there are modules that use this pattern in DT basically states that this is the way to go.

Currently, DT lacks a description on how to author definitions for ESM packages, this is a pity.

**Comment by panva** [comment]
Just because it happens to work doesn't mean it's meant to.

**Comment by BendingBender** [comment]
As far as I understand it, it actually is the only feasible way.

**Comment by BendingBender** [comment]
I'll ask on DT Discord if a maintainter can take a look at this PR.

**Review by panva — APPROVED** [review]
I guess I can always revert this if it breaks others.

**Comment by BendingBender** [comment]
See https://discord.com/channels/508357248330760243/757992230077333655/1074766451979853974

**Comment by BendingBender** [comment]
See https://discord.com/channels/508357248330760243/757992230077333655/1074766451979853974

**Comment by panva** [comment]
No idea which server that should take me to, sorry.

**Comment by BendingBender** [comment]
Here's the invitation link: https://discord.gg/typescript

**Review by sandersn — APPROVED** [review]
Matches the source package's package.json

**Comment by panva** [comment]
Ready to merge

**Pull request merged**
