### PR TITLE
fixed numjs typing bugs

### PR DESCRIPTION
**Pull request by taoqf**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@taoqf  Please provide the documentation for the change.

**Comment by taoqf** [comment]
[@sheetalkamat , hi, unfortunately there is no documentation could be found. but there is an issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18508)

**Comment by taoqf** [comment]
This is the wexin-app's document https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxml/event.html

**Comment by sheetalkamat** [comment]
@taoqf I dont think I know the library enough to understand if the change is right. Since you are the author of this library, we dont have anyone to take a second look. I will merge this if you think this is correct change.

**Comment by taoqf** [comment]
Thanks

**Pull request merged**
