### PR TITLE
angularjs: Refine typings for directive and component definitions

### PR DESCRIPTION
**Pull request by thorn0**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes: https://docs.angularjs.org/api/ng/service/$compile (mostly)
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by thorn0** [comment]
I'm one of the reviewers, and the other one wasn't active recently. What are we going to do?

**Comment by andy-ms** [comment]
These changes look pretty good, but they are breaking changes to a popular definition... @christophercr, @smfeest, and @jnorkus also modified this recently, so maybe they could help review.

**Comment by thorn0** [comment]
I tried my best not to break any correct code. I've renamed `IComponentController` to `IController`, but also kept the old name as an alias for compatibility. What else looks breaking?

**Review by smfeest — APPROVED** [review]
These changes look good to me. The move from `any[]` to `Injectable<T>` is a potentially breaking change in the sense that it's stricter than it was before, but I can't think of any scenario where a parameter that doesn't conform to the definition of `Injectable<T>` which wouldn't also already be failing at runtime so I think it's a safe (and desirable) change to make.

**Comment by christophercr** [comment]
Hi, I've reviewed the changes and although I think that making them stricter is better, I don't really like the idea of putting back verbose types like` {[boundProperty: string]: string} `. Why? Well, mainly for 2 reasons:

1) It adds too much verbosity to your code
2) You loose the advantage of code completion in your IDE, you would need to type manually this `{[boundProperty: string]: string}`  whereas you can get autocompletion for something like ISomeInterface

Think of this use case (which is my current situation)

class MyComponent implements IComponentOptions {
    controller: Injectable<IControllerConstructor> = Injectable<MyController>
    templateUrl:string = "some/url" 
    bindings: {[boundProperty: string]: string} = {
        "myBinding": "<"
    }
}

when we could do:

class MyComponent implements IComponentOptions {
    public controller: IController = MyController
    public templateUrl:string = "some/url" 
    public bindings: IBindings = {
        "myBinding": "<"
    }
}

The second looks cleaner. Don't you think?

**Comment by thorn0** [comment]
@christophercr Sorry, I had to clarify first how exactly you're using these interfaces in your code. I thought your explanation about making things less verbose is just about making the code of `angular.d.ts` itself more readable, and I didn't actually see any readability benefits. There is a lot of other places where the types like `{[...: string]: string}` are used, and replacing just part of them with interfaces looked strange and inconsistent to me.

My main presupposition was that nobody ever has to re-type these types by hand as there exists type inference. E.g., in your example, the type annotation for `controller` and `templateUrl` can be omitted. Everything works fine without them. However, it's not the case for `bindings` because object literal types aren't assignable to types with index signatures in TS 1.x. [It's been changed](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#implicit-index-signatures) in TS 2.x. So in TS 2.x, you don't need any type annotations in your class.

However, why do you need a class for something that can be just an object literal?

**Comment by thorn0** [comment]
This works great in TS 1.8:
```ts
const myComponent: IComponentOptions = {
    controller: MyController,
    templateUrl: "some/url",
    bindings: {
        "myBinding": "<"
    }
};
```

**Comment by christophercr** [comment]
Hi, yes indeed, I overlooked that. An object literal is enough and the type annotations can be ommited as well.

So everything is fine for me now. Thanks for your feedback.

**Pull request merged**
