### PR TITLE
update(cypress-image-snapshot): use cypress types

### PR DESCRIPTION
**Pull request by jdanil**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L8
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by jdanil** [comment]
Updating this to use the types from Cypress as the `action: string` type does not seem to strictly match the type of action in `PluginEvents`. Action in `PluginEvents` are consts of `"before:browser:launch"`, `"after:screenshot"`, `"file:preprocessor"`, and `"task"`, not type `string`.

Not sure if there is a way to use the `PluginConfig` instead (which seems safer in case the params or return type changes).

I opened this PR now because I wasn't able to run lint and test locally, since this change adds a dependency on cypress. Getting a `Cannot find module 'cypress' or its corresponding type declarations` error. Will see what CI shows.

**Comment by jdanil** [comment]
Ahh I think I understand why it is failing. Cypress types live in the cypress package, not in DefinitelyTyped.

I was trying to follow what other packages like [webpack-dev-server](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webpack-dev-server) do, but I think that works because webpack types are in DefinitelyTyped repo too.

Does anyone know if there is a way to use types from `"cypress": "*"` here? Or would we have to duplicate the types we need in this package?

**Comment by Keysox** [comment]
Thanks for the contribution! I'd probably suggest just copy/pasting the types that you need from cypress unless it ends up being a large lift.

The alternative, would be to create a `package.json` file with the following:
```
{
    "private": true,
    "dependencies": {
        "cypress": "*"
    }
}
```
The downside to the dependency approach is that when cypress changes an interface, it would need to be updated here or consumers would be forced to pin to a specific version of cypress, which isn't ideal.

**Comment by jdanil** [comment]
Thanks for your suggestions @Keysox! We have a story coming up in our next sprint (next week or two) to finish this off.

**Comment by ChrisMarwick** [comment]
Hi @Keysox, it looks like the automated build with cypress as a dependency is failing because it uses globalthis from typescript 3.4 and above, whilst version 3.3 is supported in DefinitelyTyped (and used in tests) until next month. We were thinking of leaving this open until next month and then hopefully the build will pass. Do you think this would be fine? Thanks

**Pull request closed without merging**
