### PR TITLE
Add type definitions for a few gulp plugins

### PR DESCRIPTION
**Pull request by peterjuras**
This pull request adds type definitions that didn't exist before for the following plugins:
- [gulp-filter](https://www.npmjs.com/package/gulp-filter)
- [gulp-html-replace](https://www.npmjs.com/package/gulp-html-replace)
- [gulp-install](https://www.npmjs.com/package/gulp-install)
- [gulp-json-editor](https://www.npmjs.com/package/gulp-json-editor)
- [gulp-jspm](https://www.npmjs.com/package/gulp-jspm)
- [gulp-strip-debug](https://www.npmjs.com/package/gulp-strip-debug)

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Hi, why is js-beautify included in this?

**Comment by vvakame** [comment]
please read contributions guide. http://definitelytyped.org/guides/contributing.html

**Comment by tkrotoff** [comment]
@peterjuras You need tests for each .d.ts file (and create several PRs if the commits are not dependant on each other).

Here a new PR #7600 only for gulp-filter including its tests (golden rules: "what ain't tested ain't working", "what is not tested will eventually break").

**Comment by peterjuras** [comment]
Yep, I figured from @vvakame 's response. I didn't have time to do these until now, thanks for the gulp-filter typings, I'll remove them from my PR when I get around to it.

**Comment by peterjuras** [comment]
I'm closing this PR and will open a new one for each package definition with tests.

**Pull request closed without merging**
