### PR TITLE
promise.prototype.finally: Fix no default export

### PR DESCRIPTION
**Pull request by ThinkChaos**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] ~~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~~
- [ ] ~~Increase the version number in the header if appropriate.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@ThinkChaos Please fix the failures indicated in the Travis CI log.

**Comment by DanielRosenwasser** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

**Comment by ThinkChaos** [comment]
I had read the [best practices](http://definitelytyped.org/guides/best-practices.html), [contributing](http://definitelytyped.org/guides/contributing.html), and [pull request](http://definitelytyped.org/guides/pull-request.html) sections on definitelytyped.org, and this wasn't mentioned.  
You should consider having a CONTRIBUTING.md file, or adding this type of information there to save everyone's time.

**Comment by ThinkChaos** [comment]
Or at least moving that advise from the FAQ to the section linked here:

**Pull request closed without merging**
