### PR TITLE
Add type definitions for mysql2

### PR DESCRIPTION
**Pull request by cweijan**
https://github.com/sidorares/node-mysql2

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mysql2 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mysql2@latest/))
was missing the following properties:
1. connect
1. Connection
1. createQuery
1. Pool
1. createServer

<details>
<summary>as well as these 3 other properties...</summary>
<p>PoolConnection, setMaxParserCache, clearParserCache</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0731beff67344e91d264f23d96bf2e07550fd864
</p>

**Review by amcasey — CHANGES_REQUESTED** [review]
The package appears to ship its own [types](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts).  Why re-declare them here?

**Comment by cweijan** [comment]
> The package appears to ship its own [types](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts). Why re-declare them here?

This is mysql2 not mysql.

**Comment by amcasey** [comment]
> > The package appears to ship its own [types](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts). Why re-declare them here?
> 
> This is mysql2 not mysql.

Sorry, I'm not sure I follow.  In the description, there was a link to https://github.com/sidorares/node-mysql2 and that repo seems to have types in the root folder.  Am I missing something?

**Comment by cweijan** [comment]
> > > The package appears to ship its own [types](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts). Why re-declare them here?
> > 
> > 
> > This is mysql2 not mysql.
> 
> Sorry, I'm not sure I follow. In the description, there was a link to https://github.com/sidorares/node-mysql2 and that repo seems to have types in the root folder. Am I missing something?

Yes, it is this repository, the official does not provide type, now the community has a `git+https://git@github.com/types/mysql2.git` but that is not complete, so I created this.

**Comment by cweijan** [comment]
@amcasey you can try `npm i --save-dev @type/mysql2`, that will found this package not exists.

**Comment by amcasey** [comment]
@cweijan I understand that `@types/mysql2` does not exist.  However, if you `npm i --save mysql2`, it appears to create a file `node_modules/mysql2/index.d.ts`, which should suffice.

**Comment by cweijan** [comment]
@amcasy Oh, you are right.

**Pull request closed without merging**
