### PR TITLE
@types/react-image-crop: Updated props definitions to match the latest release

### PR DESCRIPTION
**Pull request by chaaya**
Updated the definitions to match the latest release v6.0.11 of [react-image-crop](https://github.com/DominicTobias/react-image-crop/releases/tag/6.0.11)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DominicTobias/react-image-crop#props>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

@danielasy

### CODE REVIEW

**Comment by iKettles** [comment]
@chaaya The definition of `ReactCropProps.onImageLoaded` seems to be incorrect. According to the [docs](https://github.com/DominicTobias/react-image-crop#onimageloadedimage-pixelcrop-optional) it should have a signature of `(target: HTMLImageElement, pixelCrop: PixelCrop)`, but is still `(target: HTMLImageElement)`.

Would be great if you could fix this, otherwise I can make another PR. Thanks!

**Comment by chaaya** [comment]
> @chaaya The definition of `ReactCropProps.onImageLoaded` seems to be incorrect. According to the [docs](https://github.com/DominicTobias/react-image-crop#onimageloadedimage-pixelcrop-optional) it should have a signature of `(target: HTMLImageElement, pixelCrop: PixelCrop)`, but is still `(target: HTMLImageElement)`.
> 
> Would be great if you could fix this, otherwise I can make another PR. Thanks!

I can fix it @iKettles!

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.
If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by chaaya** [comment]
> Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.
> If you don't care about any of this stuff, I can always just pull in the changes.

Didn't noticed that the commits wasn't associated with my account, just got a new mac on the job. It's fixed now @uniqueiniquity.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
