### PR TITLE
[pendo-io-browser] Fix pendo guides disabled

### PR DESCRIPTION
**Pull request by dessskris**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://agent.pendo.io/config/Guides/#:~:text=boolean-,guides.disabled,-Completely%20disables%20guides
- [v] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/pendo-io-browser/pendo-io-browser-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5c4288a349120941aecc183198c0d21222e7c115
</p>

**Review by aaronbeall — APPROVED** [review]
Thanks

**Comment by dessskris** [comment]
Ready to merge

**Review by aaronbeall — APPROVED** [review]

**Comment by dessskris** [comment]
Ready to merge

**Pull request merged**
