### PR TITLE
SpotifyWebPlayerSDK: Export namespace definitions

### PR DESCRIPTION
**Pull request by mijorus**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

It just doesn't work unless you export the namespace

### CODE REVIEW

**Review by NeoLegends — CHANGES_REQUESTED** [review]
I don‘t think this is needed. The spotify web sdk does not use CommonJS imports, which is, what I believe, the `export` keyword declares. Installing the types library should be all that is needed AFAIK, you might want to check the type checks / examples / tests the library has here. :)

**Comment by mijorus** [comment]
Hi NeoLegends,
I tried to install the type declarations but nothing happens. 
At some point in the code i need to declare the player somehow:
```
const player: SpotifyPlayer = new Spotify.Player({..config})
```ts
Am I missing something? 
Thank you

**Comment by NeoLegends** [comment]
Be aware that the constant `SpotifyPlayer` no longer exists and the explicit type declaration is no longer working like this. Just use type inference or `Spotify.Player` if you want to add an explicit type.

Besides that, just test-ran the library on a fresh project (`npm i -D @types/spotify-web-playback-sdk && tsc --init` and VS Code provides me with the appropriate assistance & suggests errors. Please make sure the library is installed properly.

image

**Comment by mijorus** [comment]
Apparenty my issues were caused by Svelte's default typescript configuration, which limits the packages available in the global scope

```json
"types": ["svelte"]
```

I've simply extended the configuration with my own file
```json
"types": ["svelte", "spotify-web-playback-sdk"]
```

Thanks for the help. Issue closed.

**Pull request closed without merging**
