### PR TITLE
request: update RequestCallback signature

### PR DESCRIPTION
**Pull request by aleung**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by mastermatt** [comment]
@aleung could you link to docs and/or source that justifies this change please?

**Comment by aleung** [comment]
It's the node.js standard “error-first” callback style, not specific in request.

1. The first argument of the callback is reserved for an error object. If an error occurred, it will be returned by the first err argument.
1. The second (and following) argument of the callback is reserved for any successful response data. If no error occurred, err will be set to null and any successful data will be returned in the second argument.

Evidence from request source code:

https://github.com/request/request/blob/master/request.js#L188
``` js
    self.on('error', self.callback.bind())
    self.on('complete', self.callback.bind(self, null))
```

**Review by mastermatt — APPROVED** [review]

**Comment by sandersn** [comment]
@aleung I don't know about request specifically, so making the callback parameters optional looks like [a common mistake when writing callback types](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) (See the section "Optional Parameters in Callbacks".)

I noticed that the tests added a lot of non-null assertions after `response`, like `if (!error && response!.statusCode)`. Is it really the case that if error is provided, then response and body are not? Even if that's true, is it worth the inconvenience of forcing a check for it each time?

**Review by sandersn — CHANGES_REQUESTED** [review]
Before merging, I want to confirm that `response` and `body` are not provided to the callback in the case that `error` is.

**Comment by aleung** [comment]
@sandersn I have given the code from `request` above. Paste again here:

https://github.com/request/request/blob/master/request.js#L188
```
    self.on('error', self.callback.bind())
    self.on('complete', self.callback.bind(self, null))
```

https://github.com/request/request/blob/master/request.js#L1100
```
self.emit('complete', response)
```

https://github.com/request/request/blob/master/request.js#L1163
```
self.emit('complete', response, response.body)
```

The error event is emitted with a single `Error` object and it's passed to callback as the first and only argument. I don't paste the code of emitting because there are a lot. You can search by 'error'.

On complete, the first argument being passed to callback is `null`, followed by one or two arguments.

**Comment by aleung** [comment]
BTW, IMHO the section "Optional Parameters in Callbacks" is not valid for node.js error callback. See: https://nodejs.org/api/errors.html#errors_error_first_callbacks

It's better to mention in the Do's and Dont's page.

**Comment by sandersn** [comment]
Optional parameters are not actually the right thing here &mdash; they just put an unrelated guard in the way of using `response` and `body`. According to the request documentation, the intended usage is 

```js
function errorFirstCallback(err, data) {
  if (err) {
    console.error('There was an error', err);
    return;
  }
  console.log(data);
}
```

So what we want is a type that has `err` defined and `response/body` undefined inside the `if (err)` block, but `err` undefined and `response/body` defined outside the block. In other words, something like this:

```ts
type Params = 
  | { err: any, response: undefined, body: undefined }
  | { err: undefined, response: Response, body: any }
```

This has three problems

1. The callback parameters aren't defined as a single object in `request`. 
2. `any` messes up narrowing between the two alternatives.
3. Only literal types can be used to enable narrowing.

So you'd have to modify the callback type to look something like this:

```
type Params = 
  | { kind: 'error', err: any, response: undefined, body: undefined }
  | { kind: 'ok', err: undefined, response: Response, body: any }
type RequestCallback = (params: Params) => void
function errorFirstCallback(params) {
  if (params.kind === 'error') {
    console.error('There was an error', params.err);
    return;
  }
  console.log(params.data);
}
```

This is fine for a library you're writing from scratch but doesn't make sense for a DefinitelyTyped d.ts for an existing package. 

I don't think there's a way to get what you want in Typescript's type system right now. The PR as it stands just forces people to add noise to their code for no increase in safety.

**Pull request closed without merging**
