### PR TITLE
Synced Foundation-Sites typings from different repos

### PR DESCRIPTION
**Pull request by DaSchTour**
As there doesn't seem to be a fast solution to move the new version from https://github.com/samvloeberghs/foundation-sites-typings to @types I add the changes made there here

See also for issue about different versions of typings
https://github.com/samvloeberghs/foundation-sites-typings/issues/3
https://github.com/Microsoft/types-publisher/issues/169

### CODE REVIEW

**Comment by vvakame** [comment]
Could you fix travis ci?

**Comment by DaSchTour** [comment]
Well sure. Didn't look at the tests but just have thrown in the version that is already released on typings native registry :(
I really hope managing and updating typings will get easier in future.

**Comment by minestarks** [comment]
@DaSchTour Thank you for your contribution. Unfortunately I can't merge this in until the tests are fixed. It's been a few weeks so I plan to close out this PR if no further changes in a couple of days, in which case you can open a new PR with the corrected changes. Thanks!

**Comment by DaSchTour** [comment]
At the moment I have no time to fix the tests and I also have no idea how this tests work. So I guess DefinitelyTyped will have to stay with the wrong typings for a while.

**Pull request closed without merging**
