### PR TITLE
Improved Promises A+ definitions (for TS 1.4)

### PR DESCRIPTION
**Pull request by Igorbek**

### CODE REVIEW

**Comment by basarat** [comment]
Nice! Verified that its consistent with what the TypeScript team propose for ES7 : https://github.com/Microsoft/TypeScript/issues/1664 :+1:

**Comment by johnnyreilly** [comment]
I've said this before but I *love* union types :smile:

**Comment by rbuckton** [comment]
:+1:

**Comment by Igorbek** [comment]
@basarat I wondered they proposed with required parameters. Actual contract support both callbacks as optional.

**Comment by Igorbek** [comment]
@rbuckton I mean you proposed =)

**Pull request merged**
