### PR TITLE
Openlayers: Add stopClick to DrawOptions

### PR DESCRIPTION
**Pull request by asiderius**
Add stopClick to DrawOptions.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://openlayers.org/en/v4.6.5/apidoc/ol.interaction.Draw.html

### CODE REVIEW

**Review by hauke96 — COMMENTED** [review]
There's a constructor for `ol.interaction.Draw` it in the tests, would be nice to have `stopClick` there as well.

**Comment by asiderius** [comment]
@hauke96 Thanks for your comment! In the first commit, `stopClick` was already added to one `ol.interaction.Draw` constructor in the tests. In the new commit I have added it to the other `ol.interaction.Draw` constructors in the tests as well.

**Review by hauke96 — APPROVED** [review]
Very nice. Looks good to me.

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.
If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by asiderius** [comment]
@uniqueiniquity Thank you for pointing this out! I have fixed the author for my commits in this pull request.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
