### PR TITLE
@types/Coingecko-api Add property include_24hr_change to SimplePriceParams

### PR DESCRIPTION
**Pull request by HHenry88**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://www.coingecko.com/de/api/documentation)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by janklimo — CHANGES_REQUESTED** [review]
Thank you for your submission. Please add a test to cover the changed code.

**Comment by HHenry88** [comment]
Hi @janklimo thanks for the comment. I've updated a test for changed code. Please let me know if anything else needs to be done.

**Review by janklimo — APPROVED** [review]
💯🎅

**Comment by janklimo** [comment]
Ready to merge

**Pull request merged**
