### PR TITLE
Fix module name of auth0-js.

### PR DESCRIPTION
**Pull request by westy92**
case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

I renamed this module in a previous PR and forgot to change this string.

### CODE REVIEW

**Comment by advancedrei** [comment]
Why on earth did you change the module name. That's going to break literally everyone's code?

**Comment by westy92** [comment]
The `auth0` module was incorrectly named to start with, as it was a typing for the package `auth0-js`.  See https://github.com/auth0/auth0.js/issues/136.

I renamed the `auth0` module to `auth0-js` and added a correct `auth0` module.  I missed this one string during the rename.

**Comment by westy92** [comment]
See my previous PR where I missed this string: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10653

**Comment by advancedrei** [comment]
Yeah, I see the PR. But did you give Auth0 the heads-up that you were going to break all non-Node users in the process, and did they actually review the changes? Did you do it in a way that doesn't break compatibility? It doesn't appear that you did.

**Comment by westy92** [comment]
I notified auth0 of the changes by commenting on their issue here: https://github.com/auth0/auth0.js/issues/136.

I do not have power to merge PRs into DT master, so it was reviewed and merged by someone with DT merging privileges.

**Comment by advancedrei** [comment]
Not following your logic. DT != Auth0. So just because it got merged doesn't mean your code doesn't break existing customers, and doesn't mean that anyone was aware of the impact.

**Comment by westy92** [comment]
https://github.com/auth0/auth0.js/issues/136 = Auth0.

According to that issue, the typing was already broken for "existing customers".

**Comment by advancedrei** [comment]
I do not see a single employee comment on that thread.

DT != Auth0. So just because it got merged doesn't mean your code doesn't break existing customers, and doesn't mean that anyone was aware of the impact.

It's one thing to add stuff or leave stuff out of the definitions because you're not sure how it's used on other platforms. It's quite another to remove whole classes without checking with anyone to make sure that is OK, and actually waiting for an answer first.

**Comment by advancedrei** [comment]
Alright, looks like I owe you an apology.

I had to pull the code into Beyond Compare in order to look at it properly, and it doesn't look like you removed classes... so again I apologize. GitHub was just being stupid about it's comparison, which made it look like you took a bunch of stuff out. I was not thrilled (to put it mildly) that I was going to have to review all the code again to make sure you didn't remove other important stuff. So, sorry about that.

However, changing the file and module names is still going to break anyone who updates. @paulvanbrenk is there any way to rev the major version on this type file to denote a breaking change?

**Comment by westy92** [comment]
Let me take a step back.  I came across this naming dilemma when trying to install the typings for https://www.npmjs.com/package/auth0 and found them to be incorrect.  The typings claiming to be for `auth0` were instead for `auth0-js`.
According to DT, "To keep naming conflicts to a minimum please use the package name as used in the npm package registry." (http://definitelytyped.org/guides/contributing.html)
That is when I found https://github.com/auth0/auth0.js/issues/136.

To fix this, I renamed what was claiming to be `auth0` to `auth0-js` and added valid `auth0` typings.

I notified Auth0 of my open PR by commenting on their issue.  You are correct that an employee did not comment back.  However, that is an Auth0-owned repository that they should be monitoring.

**Comment by westy92** [comment]
Apology accepted.  I'm sorry for the confusion!  Let me know if there is anything else I can do to help.

**Comment by rbuckton** [comment]
@westy92 There apparently are two packages on npm:

* https://www.npmjs.com/package/auth0 - This is the NodeJS SDK for auth0
* https://www.npmjs.com/package/auth0-js - This is the Browser SDK for auth0

Instead of renaming auth0 to auth0-js, I would recommend creating a separate auth0-js directory and declaration file.

**Comment by westy92** [comment]
@rbuckton I'm aware of the two packages.  Initially there was only a typing for `auth0-js` but it was incorrectly named `auth0`.  I wanted to add a correct typing for `auth0` so I added it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10653) and renamed the existing `auth0` to `auth0-js`.  I missed one string which is fixed in this PR.

**Comment by rbuckton** [comment]
@westy92, Ah! Thanks for the clarification. In that case, this looks good to me.

**Pull request merged**
