### PR TITLE
feat(passport): add keepSessionInfo option

### PR DESCRIPTION
**Pull request by Neil188**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[sessionmanager.js](https://github.com/jaredhanson/passport/blob/master/lib/sessionmanager.js#L37)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

further info - see comment on issue https://github.com/jaredhanson/passport/issues/919#issuecomment-1180542706

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Neil188 fancy a small test? and I'll merge immediately

**Review by andrewbranch — APPROVED** [review]

**Comment by ashishth09** [comment]
Looks like we have all we need to get this merged. Can someone help?

**Comment by peterblazejewicz** [comment]
@ashishth09 done, usually we do not do this, only PR owner :)

**Comment by ashishth09** [comment]
Thanks @peterblazejewicz 👍

**Pull request merged**
