### PR TITLE
react-select now with default export

### PR DESCRIPTION
**Pull request by naortor**
Please fill in this template.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/react-select
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by MartynasZilinskas** [comment]
There already a PR for this and even more. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19863

**Comment by naortor** [comment]
Oh, didnt notice,

Worked for nothing then ;)

Thanks anyway, hope it will be merged soon


בתאריך 25 בספט' 2017 17:39,‏ "Martynas Žilinskas" <notifications@github.com>
כתב:

**Comment by onatm** [comment]
#19863 is already merged in - I think we can close this one.

**Comment by mhegazy** [comment]
@naortor is this still needed or can we close it?

**Comment by naortor** [comment]
You can close it,
Thanks

בתאריך 26 בספט' 2017 9:48 PM,‏ "Mohamed Hegazy" <notifications@github.com>
כתב:

**Pull request closed without merging**
