### PR TITLE
Made Composites.newtonsCradle a static method

### PR DESCRIPTION
**Pull request by milan090**
Select one of these and delete the others:

Change: https://github.com/milan090/DefinitelyTyped/blob/master/types/matter-js/matter-js-tests.ts
index.d.ts:1542

Fixes type definitions to match with the package.

### CODE REVIEW

**Comment by milan090** [comment]
I think the tests here are not properly configured.
newtonsCraddle was not set static method. I just added the static word. 

(this is my first pr in a big repo)

**Comment by hasparus** [comment]
hey @milan090! congrats on your first DefinitelyTyped PR!

The bot wants you to add tests. It should be as simple as

```
const cradle = Composites.newtonsCradle(200, 50, 5, 20, 250);
```
`

**Comment by sandersn** [comment]
A change in the TS nightly makes DT parsing run out of memory. I pinned Typescript to a version before the change while I investigate.

**Comment by milan090** [comment]
> hey @milan090! congrats on your first DefinitelyTyped PR!
> 
> The bot wants you to add tests. There was no test for `newtonsCradle` previously (and it may be the reason why it was wrongly marked as non-static), but adding a new one should be as simple as pasting following code to the test file.
> 
> ```ts
> const cradle = Composites.newtonsCradle(200, 50, 5, 20, 250);
> ```
> 
> `

Thanks, @hasparus. I have made the changes

**Review by hasparus — APPROVED** [review]
Nice one! Now we wait for the bot.

**Comment by hasparus** [comment]
Ready to merge

**Pull request merged**
