### PR TITLE
[react-native] Switch to *real* components + rename Properties to Props

### PR DESCRIPTION
**Pull request by tkrotoff**
Following this comment: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16318#issuecomment-381933894

Currently react-native/index.d.ts don't use *real* React components (i.e `class ... extends React.Component`), instead it's a "hackish" solution, [example with `TextInput`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25307/commits/51c34fa4eedf3d60487d0beb3d4aaa1e5e5d1521):
```TypeScript
export interface TextInputStatic extends NativeMethodsMixin, TimerMixin, React.ComponentClass<TextInputProperties> {
  // ...
}

// ...

export const TextInput: TextInputStatic;
export type TextInput = TextInputStatic;
```

Because of this you cannot write valid things like #16318 (I've added [a test](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25307/commits/51c34fa4eedf3d60487d0beb3d4aaa1e5e5d1521#diff-b7f9493068068c65a8ac15953df610f5) to ensure this works now)

Here the fix:
```TypeScript
type Constructor<T> = new(...args: any[]) => T;
declare class TextInputComponent extends React.Component<TextInputProperties> {}
declare const TextInputBase: Constructor<NativeMethodsMixin> & Constructor<TimerMixin> & typeof TextInputComponent;
export class TextInput extends TextInputBase {
 // ...
}
```

So I've fixed every React Native component. Each component I have fixed is done in its own commit (so I could `yarn test` every component and review things piece by piece) and since React Native exposes a lot of components, well you have many commits - nothing to be afraid of :)

The second part of this PR is about renaming *Properties to *Props.
Why? [React Native documentation](http://facebook.github.io/react-native/) uses exclusively the term Props (1) (like the whole React ecosystem and [react/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts)) so now the definition is in sync with the documentation.
I've also added `@deprecated` "redirections" so people can still use the old syntax *Properties, the idea is to remove them in the future.

I know this is a big PR, I've spent several hours on it to ensure nothing is broken.

(1) I've reported the only place where they use the term Properties instead of Props: https://github.com/facebook/react-native-website/pull/321

### CODE REVIEW

**Comment by iRoachie** [comment]
You really can’t expect to change the external api of a project. Has too many breaking changes that requires everyone to change their libraries that don’t live on definitelyTyped 👎🏽

**Comment by tkrotoff** [comment]
@iRoachie are you talking about the components or the props?

**Comment by iRoachie** [comment]
You can't change the external API (like all *Properties to *Props). This PR would break everyone's apps  and libraries that depend on @types/react-native.

**Review by iRoachie — CHANGES_REQUESTED** [review]
👎🏼

**Review by egorshulga — APPROVED** [review]

**Comment by egorshulga** [comment]
So lets bump a major version and merge it. It's a big piece of work

**Review by avocadowastaken — CHANGES_REQUESTED** [review]
Agree with @iRoachie

**Comment by iRoachie** [comment]
@egorshulga It's not about bumping a major version. There are many typescript definitions outside of DefinitelyTyped in which libraries bundle their only types. This will break all of them.

**Comment by egorshulga** [comment]
So, what could be a solution? This PR should not be dropped into oblivion.

**Comment by timwangdev** [comment]
> Switch to *real* components
This part is LGTM

> Rename Properties to Props
I don't see the benefits compare to the big break change for others.

**Comment by iRoachie** [comment]
Why just don’t revert the change to Props instead of creating a new mapping file? Over-complicating stuff?

**Comment by tkrotoff** [comment]
Latest commits make things clean:
- react-native/index.d.ts contains only *Props
- react-native/legacy-properties.d.ts contains *Properties "redirections" (with `@deprecated` comments)
- index.d.ts uses legacy-properties.d.ts

==> 100% compatibility, NO break (I've manually check that every Props has a Properties redirection)

@iRoachie @timwangdev 

Current index.d.ts is an ugly mix between Properties and Props, example:
- KeyboardAvoidingViewProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L1930
- TouchableWithoutFeedbackProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L4616
- ScrollViewProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L6041
- SwipeableListViewProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L6147
- ARTGroupProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L8381
- ARTClippingRectangleProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L8386
- ARTShapeProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L8400
- ARTTextProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L8406
- ARTSurfaceProps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/react-native/index.d.ts#L8411

<br><br><br>

As for the "real" components change, it might break things: for example related internal *Static (e.g. TextInputStatic) are gone and some users might have imported them (`import { TextInputStatic } from 'react-native'`). They should simply use TextInput instead.

**Review by avocadowastaken — APPROVED** [review]
Much better 👍Thank you for hard work!

**Review by timwangdev — APPROVED** [review]
Thanks for the clarification, I will approve this for `react-native` type.

**Review by iRoachie — APPROVED** [review]
Sweeet, once it doesn't break I'm good

**Review by kaoDev — APPROVED** [review]

**Comment by tkrotoff** [comment]
Thx everybody for reviewing

**Comment by vovkasm** [comment]
This broke `DatePickerIOS` https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4abbfb42ff02fbdf3584f6285238d82c4ccbeb14#r28761333 )))

**Comment by weswigham** [comment]
@tkrotoff ?

**Comment by svbutko** [comment]
There are also problems with StatusBar.

**Comment by tkrotoff** [comment]
@weswigham Oh no :/ I'm on it

**Comment by alloy** [comment]
Sweet. Great work @tkrotoff! 👏

**Comment by brunolemos** [comment]
@tkrotoff you wrote the deprecated exports separated from their new export, so it's a bit hard to review if any of them is missing. At least one type is not exported anymore, the `PointProperties` one.

I know because my project complained about it, so there may be another one or two that is not being exported.

**Comment by brunolemos** [comment]
Also maybe the `XxxStatic` ones should be exported as deprecated too.

**Comment by tkrotoff** [comment]
@brunolemos `PointProperties` is a different beast, it's not a React props: I've renamed it to `PointPropType`, see https://facebook.github.io/react-native/docs/scrollview.html#contentoffset I could have add a redirection for it aswell. For the React props that were renamed from *Properties to *Props you have the redirections, I've checked them one by one.

About the `XxxStatic` it's not just a simple renaming, see [my comment above](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25307#issuecomment-384607750):
> As for the "real" components change, it might break things: for example related internal *Static (e.g. `TextInputStatic`) are gone and some users might have imported them (`import { TextInputStatic } from 'react-native'`). They should simply use `TextInput` instead.

**Comment by brunolemos** [comment]
No problem for me, just wanted to point that there we some breaking changes with this.

**Pull request merged**
