### PR TITLE
Export Dropzone as default

### PR DESCRIPTION
**Pull request by ivasilov**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url](https://github.com/okonet/react-dropzone)
- [ ] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@ivasilov  can you fix the Travis issues

**Comment by GiedriusGrabauskas** [comment]
**TS:**
```ts
import Dropzone from "react-dropzone";
```
**JS:**
```js
var react_dropzone_1 = require("react-dropzone");
console.log(react_dropzone_1.default);
```
**Console:**
```
> undefined
```

It's not working... You can see it in [example](https://github.com/okonet/react-dropzone#example).
```js
var React = require('react');

// import * as Dropzone from "react-dropzone";
var Dropzone = require('react-dropzone');

var DropzoneDemo = React.createClass({
    onDrop: function (acceptedFiles, rejectedFiles) {
      console.log('Accepted files: ', acceptedFiles);
      console.log('Rejected files: ', rejectedFiles);
    },

    render: function () {
      return (
          <div>
           // Using Dropzone, not Dropzone.default
            <Dropzone onDrop={this.onDrop}>
              <div>Try dropping some files here, or click to select files to upload.</div>
            </Dropzone>
          </div>
      );
    }
});

React.render(<DropzoneDemo />, document.body);
```

Test sample:
https://jsfiddle.net/x1knyr1t/

@paulvanbrenk could you revert this pull request?

**Comment by paulvanbrenk** [comment]
@GiedriusGrabauskas I'm not sure what you're trying to say. The definition has no effect at runtime, is the generated javascript wrong with the changed definition?

**Comment by ivasilov** [comment]
Also, the package exports Dropzone as a default. https://github.com/okonet/react-dropzone/blob/master/src/index.js#L339

**Comment by GiedriusGrabauskas** [comment]
@ivasilov, yes, but in source only. Compiled module was not exported as default.
I created more understandable example here: 

[react-dropzone-sample.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/656747/react-dropzone-sample.zip)
To start:
```cmd
npm i && npm run build && npm run start
```

@paulvanbrenk, I trying to say, that this module is not exported as default.

**Pull request merged**
