### PR TITLE
@rdfjs/data-model: added Factory module

### PR DESCRIPTION
**Pull request by tpluscode**
I added the `Factory` module as exported by the package

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/rdfjs-base/data-model/blob/master/Factory.js>
- [] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by jeswr** [comment]
The declarations look good - perhaps just add some tests that make use of `init`; and some tests that check the instantiated class is of type `DataFactory`

**Review by jeswr — CHANGES_REQUESTED** [review]
The declarations look good - perhaps just add some tests that make use of `init` (since it hasn't been marked as private); and some tests that check the instantiated class is of type `DataFactory`

**Review by jeswr — APPROVED** [review]
@tpluscode Looks good! The only other check I would have had is that `init()` returns void but that's probably a little over the top anyway :)

**Comment by tpluscode** [comment]
I was a little confused about `init()` anyway. It technically is part of a public API to be called by `@rdfjs/environment` but its also getting called by the constructor so what's the point? 😅

**Comment by tpluscode** [comment]
Ready to merge

**Comment by jeswr** [comment]
> I was a little confused about `init()` anyway. It technically is part of a public API to be called by `@rdfjs/environment` but it's also getting called by the constructor so what's the point? sweat_smile

I suppose it lets you reset the `blankNodeCounter` without instantiating a new class - but I can't really think of a use case for that.

**Pull request merged**
