### PR TITLE
Add catchReturn and catchThrow

### PR DESCRIPTION
**Pull request by Loghorn**

### CODE REVIEW

**Comment by lhecker** [comment]
@Loghorn

* Your `bluebird/index.d.ts` has 2 blocks of code defining a `catchReturn`. The latter block of code should be defining `catchThrow` though.
* `bluebird-global/index.d.ts` must contain method aliases for all methods you define in `bluebird/index.d.ts`. Can you add those as well please?

Also make sure to follow the [contribution guide](http://definitelytyped.org/guides/contributing.html) next time: Before submitting a PR you should run `npm update` followed by `npm test`. Afterwards please fix this PR using `git add -A && git commit --amend && git push --force` or similar. 🙂

**Comment by Loghorn** [comment]
@lhecker 
Sorry about the issues, I totally missed that bluebird-global needs to be changed; I also did run the tests but on the wrong branch 🤦‍♂️ 
Should be ok now 😊

**Comment by mhegazy** [comment]
The build break should be fixed in master, can you please rebase.

**Comment by Loghorn** [comment]
Done, sorry for the delay.

**Pull request merged**
