### PR TITLE
Revert "[Lodash] Restrict string values in list iteratees to being keys of the items in the list (#64722)"

### PR DESCRIPTION
**Pull request by CruseCtrl**
This reverts commit d008404d15efa681abcb08179874cbef6d425b5d.

The change was incorrect because there are some undocumented features which allow you to do e.g. `_.sortBy[{ a: { b: 1 } }], 'a.b')`. See [the comments on the PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64722) for more info.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by sidoruk-sv** [comment]
@CruseCtrl I think that's because new versions of TS where released since this package got green status in tests.

So this `@types/lodash` is not compatible with latest TypeScript, where generic constraints has more restrictive check.

So in tests this fails:
```
Type 'T' does not satisfy the constraint '{}'
Type 'TRecord' does not satisfy the constraint '{}'.
```

Looks like need help from maintainers to deal with this problem.

**Review by aj-r — APPROVED** [review]
Errors seem to be from an unrelated package (knex). I think it's safe to merge this.

**Comment by sacummings91** [comment]
Can confirm the latest version `4.14.192` breaks for us also

**Comment by zepplock** [comment]
Hello, any update?

**Comment by jakebailey** [comment]
knex can probably be ignored, however, it seems like dtslint is failing on this for another reason; I'm assuming it's because of the `ts4.2` folder now that ts4.2 has dropped off of the supported versions.

**Comment by jakebailey** [comment]
Sent https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65122 to hopefully fix that.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Not sure the bot's going to figure out that the CI is fixed, so, I'll merge this myself. Sorry for the wait.

**Comment by nitish24p** [comment]
Hello i am using tsc 3.8.3 and one of my transitive dependencies started failing this morning, with the following error 
```bash
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1025,21): error TS1110: Type expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1026,24): error TS1005: ':' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1026,38): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1027,26): error TS1005: ':' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1028,30): error TS1005: ':' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1028,44): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1031,21): error TS1128: Declaration or statement expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1043,41): error TS1110: Type expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1043,50): error TS1005: '}' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1043,55): error TS1128: Declaration or statement expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1043,57): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1043,64): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1046,29): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1046,30): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1046,37): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1046,48): error TS1005: ',' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1046,55): error TS1005: ',' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1053,26): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1053,27): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1053,34): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1053,45): error TS1005: ',' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1053,52): error TS1005: ',' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1307,23): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1307,54): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1312,30): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1312,40): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1312,60): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1346,23): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1346,67): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1351,30): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1351,40): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1351,60): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1751,16): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1756,43): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1761,30): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1842,33): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1842,66): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1844,28): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1844,49): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1845,33): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1852,30): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1938,29): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(1939,56): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2000,29): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2001,56): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2001,70): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2051,54): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2093,47): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2093,67): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2443,33): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2443,67): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2444,47): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2444,59): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2444,80): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2445,65): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2448,43): error TS1005: ';' expected.
npm ERR! prepareGitDep node_modules/@types/lodash/common/object.d.ts(2456,30): error TS1005: ';' expected.
```

I see a new version got published sometime back, its likely that couldve been the cause..

**Comment by jakebailey** [comment]
TS 3.8 has been unsupported by DT for well over a year. I recommend pinning your dependencies or updating typescript.

**Comment by nitish24p** [comment]
@jakebailey Although if i keep my tsc version the same and manually install the previous version as 
```
npm install @types/lodash@4.14.182
```
My build works as expected

**Comment by jakebailey** [comment]
You're trying to use a 3 year old version of TypeScript. There have been 12 releases since 3.8. If you are working with a version that old, expect to need to install old dependencies. There's nothing to fix here.

**Comment by nitish24p** [comment]
Yep, i realised the issue is one of my libraries has a ^ in its dependency and that caused an issue when the latest version of @types/lodash got installed today.. sorry for the noise..

**Comment by darkowic** [comment]
@jakebailey we can use even 5 years old TS if we need this. The complaint here is that you introduced a breaking change like this in a patch release. We discovered a similar issue when upgraded the patch version. It wouldn't be any problem if this is introduce as minor/major version of the package :)

**Comment by jakebailey** [comment]
This is just how DT works. The major/minor pair always matches the upstream version being described, then the patch version is bumped automatically as DT is updated.

I'm also not sure how a revert is a breaking change. This just reverts a change made only 3 weeks ago.

**Pull request merged**
