### PR TITLE
rename github-electron to electron

### PR DESCRIPTION
**Pull request by vvakame**
related #10993

### CODE REVIEW

**Comment by rhysd** [comment]
LG™.

@miniak , how about you?

**Comment by miniak** [comment]
Bring it on!

**Review by miniak — APPROVED** [review]

**Comment by miniak** [comment]
@vvakame electron.d.ts and github-electron.d.ts have the same contents. Why?

**Comment by miniak** [comment]
The header is also broken

```
// Type definitions for electron 1.3.3
// Project: https://github.com/electron-userland/electron-prebuilt
// Definitions by: rhysd <https://github.com/rhysd>
```

**Comment by miniak** [comment]
Now I regret approving the change, I didn't have time to review it thoroughly.

**Comment by andy-ms** [comment]
Currently `master` has a `github-electron` directory with files that say `// this file will be removed.`. And `types-2.0` has an `electron` directory with `index.d.ts`, `github-electron.d.ts`, and `electron.d.ts` defining incompatible typings. It also has `electron-prebuilt.d.ts` that says `// this file will be removed.`. These extra files are making types-publisher fail since it doesn't know which ones to publish. Can I remove all of these except `electron/index.d.ts`?

**Comment by rhysd** [comment]
@andy-ms 

I looked a bit.

- master
  - `github-electron/*` : I think it's OK to remove all because user should use `electron` directory
  - `electron/electron.d.ts` : This is a package for electron binary package.  So it should remain.
  - `electron/github-electron.d.ts` : This is a package for Electron application environment. So it should remain
- types-2.0
  - `electron/electron-prebuilt.d.ts` : This should be replaced with above master's `electron.d.ts`
  - `electron/index.d.ts` : his is a package for Electron application environment. So it should remain

Yeah, `electron` binary package provides 'electron' package and it makes collision with a package  provided by Electron. So currently we can't use 'electron' binary package in Electron application.

**Pull request merged**
