### PR TITLE
[react-native-incall-manager] Updated types for v4.0

### PR DESCRIPTION
**Pull request by JasonWeinzierl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

**Changes**

* [StartSetup is expected only be two values, not string](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/index.js#L21)
* [getIsWiredHeadsetPluggedIn returns an object with one value, be more descriptive than any](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/index.js#L40)
* [getFlashOn no longer returns a number](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/index.js#L45C11-L45C11)
* [startRingtone arguments:](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/index.js#L76)
  * specify that vibrate_pattern is expected to be a number array (via react native Vibration.vibrate)
  * specify that ios_category can only be two values, not string
* [two new methods, startProximitySensor and stopProximitySensor](https://github.com/react-native-webrtc/react-native-incall-manager/commit/5f05bbd4167bf3b2288a76030b44bf44c4309f7e)
* [all permission-related functions were removed](https://github.com/react-native-webrtc/react-native-incall-manager/pull/173)
* [getAudioUri arguments:](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/index.js#L127)
  * specify that audioType must be one of the keys of private object `audioUriMap`, namely ringtone, ringback, or busytone
  * specify return type is a string or null, not any
* [chooseAudioRoute arguments based on Android chooseAudioRoute](https://github.com/react-native-webrtc/react-native-incall-manager/blob/a9a767971ad21008fecb3fdd3eb3abf30ad14582/android/src/main/java/com/zxcpoiu/incallmanager/InCallManagerModule.java#L1530)
* [two new methods for audio focus](https://github.com/react-native-webrtc/react-native-incall-manager/commit/82778ca9d8dfb620b173e71fcc2e1435cbbcdaa9)

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Please provide the most important part of the PR template:

> Provide a URL to documentation or source code which provides context for the suggested changes: 

PRs really aren’t reviewable without that. Thanks!

**Comment by JasonWeinzierl** [comment]
> Please provide the most important part of the PR template:
> 
> > Provide a URL to documentation or source code which provides context for the suggested changes:
> 
> PRs really aren’t reviewable without that. Thanks!

Updated, sorry!

**Review by andrewbranch — APPROVED** [review]
Thank you!

**Comment by JasonWeinzierl** [comment]
Ready to merge

**Pull request merged**
