### PR TITLE
chore (prosemirror): remove all redundant prosemirror types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

various prosemirror packages now ship their own types.

https://unpkg.com/browse/prosemirror-changeset@2.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-collab@1.3.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-commands@1.3.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-dropcursor@1.5.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-gapcursor@1.3.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-history@1.3.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-inputrules@1.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-keymap@1.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-markdown@1.9.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-menu@1.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-model@1.17.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-schema-basic@1.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-schema-list@1.2.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-state@1.4.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-test-builder@1.1.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-transform@1.5.0/dist/index.d.ts
https://unpkg.com/browse/prosemirror-view@1.24.0/dist/index.d.ts

### CODE REVIEW

**Comment by 43081j** [comment]
slightly baffled by this one...

> Error: node_modules/prosemirror-model/dist/index.d.ts(1,8): error TS1259: Module '"/home/runner/work/DefinitelyTyped/DefinitelyTyped/types/orderedmap/index"' can only be default-imported using the 'esModuleInterop' flag

prosemirror-dev-tools depends on prosemirror-model, so i added it to the whitelist and the package.json.

however this seems to be unhappy about prosemirror-model's dependency: orderedmap.

though looking at orderedmap, it too has types and does not use an export assignment:
https://unpkg.com/browse/orderedmap@2.1.0/dist/index.d.ts

maybe @andrewbranch can come to my rescue again? 🙈

**Comment by andrewbranch** [comment]
Can the orderedmap typings be removed as not-needed first?

**Comment by 43081j** [comment]
Yup that works. 

Still curious why the lookup happens though. Maybe it's the type root we have set, so it checks dt first and sees we already have some ordered map types.

**Comment by 43081j** [comment]
i think im gonna have to bundle that removal into this PR @andrewbranch 

otherwise, ill have to whitelist the prosemirror package only until this PR merges.

if i do it all in one, i don't need to touch the whitelist.

its small enough i think, ill try it out

**Comment by ocavue** [comment]
`orderedmap` is mostly been used by ProseMirror related packages ([link](https://www.npmjs.com/package/orderedmap?activeTab=dependents)). I think bundle that removal is ok.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## prosemirror-dev-tools ([<kbd>unpkg</kbd>](https://unpkg.com/browse/prosemirror-dev-tools@latest/))
was missing the following properties:
1. applyDevTools
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 826fb450a863f8912338f410cef1b2d5ed308f1a
</p>

**Comment by 43081j** [comment]
ok cool, ive pushed the orderedmap removal too :+1:

looks good

**Review by jakebailey — APPROVED** [review]
Thank you much for these cleanups!

**Comment by 43081j** [comment]
ready to merge 🍺 

& no worries, good to clean some of this stuff up

**Pull request merged**
