### PR TITLE
jQuery: Add overload for on() handler for JQueryEventObject

### LINKED ISSUE #24699: Deprecated JQueryEventObject support incomplete
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jQuery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu 

Thanks for providing `JQueryEventObject` as a transition object. 
But we need to provide overloads at least for .on() to support them in code like:

```ts
let myDiv = $(document.createElement('div')); 
myDiv.on('click', (evt: JQueryEventObject) => {
    
});
```

### PR DESCRIPTION
**Pull request by HolgerJeromin**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

ref @leonard-thieu @O-Zone @icnocop 

closes #24699

### CODE REVIEW

**Comment by leonard-thieu** [comment]
Could you add a test for this?

**Comment by HolgerJeromin** [comment]
I can reproduce the error here. Closing till i have a solution.

**Comment by HolgerJeromin** [comment]
Before my change an untyped function parameter gets type `Event<HTMLElement, null>` from line 4556.
Now we have in line 4566 the parameter type `JQueryEventObject`.

The unit tests complains that both should be combined.
But when they are combined TypeScript (at least my 2.8) detect the type `any` instead of `Event<HTMLElement, null> | JQueryEventObject`.

@leonard-thieu do you have an idea how to solve this?

**Comment by HolgerJeromin** [comment]
@leonard-thieu ready to merge from my side

**Review by leonard-thieu — APPROVED** [review]

**Review by kvcpr — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
