### PR TITLE
[@storybook/addon-notes] remove typings provided by package directly

### PR DESCRIPTION
**Pull request by gaetanmaisse**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

Select one of these and delete the others:

If removing a declaration:
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

--

`@storybook/addon-notes` was migrated to TS in this PR https://github.com/storybooks/storybook/pull/4758

### CODE REVIEW

**Comment by joscha** [comment]
@gaetanmaisse can you add a ref to the PR introducing tyoings for the notes add-on in the storybook repo, please?

**Comment by gaetanmaisse** [comment]
@joscha I just updated this PR description with it 😉

**Comment by joscha** [comment]
awesome - this will land with v5, right?

**Comment by joscha** [comment]
nvm, just saw the json.

**Review by joscha — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
