### PR TITLE
Entire material-ui library stubbed out and mostly implemented

### PR DESCRIPTION
**Pull request by ngbrown**
- I'm not at 100% coverage yet, but the definition file is already over 1,900 lines.
- Every component except for the `./svg-icons/**/*` tree is at least stubbed out, if not implemented.
- Modules can be `required()`ed at the top level (`require("material-ui")`) or at the component level (`require("material-ui/lib/flat-button")`).  Both work; to use for variable typing, it's better to pull from the top level.
- The tests are written in a `.TSX` file using the [documentation examples](http://material-ui.com/) and then back-ported to `.TS`.
- This pull request implements #5619, a request for material-ui definitions.
- It is significantly more complete than pull request #5736, which only had `FlatButton` implemented.
- This implementation requires and includes #5915, minor updates to react.d.ts.

### CODE REVIEW

**Comment by vvakame** [comment]
*material-ui/material-ui.d.ts*

check list

* [ ] is collect [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/material-ui
  * http://bower.io/search/?q=material-ui
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (material-ui/material-ui-tests.ts or others)
* [ ] pass the Travis-CI test?

---

@pspeter3 @vsiao @jbrantly could you review react.d.ts changes?

**Comment by vvakame** [comment]
blocked by https://github.com/DefinitelyTyped/definition-tester/issues/11

**Comment by use-strict** [comment]
Did some definitions as well last week but I see you are already onto something here. Mine covers all components exported from material-ui's index.js, but I have no tests and I'm not 100% sure of its correctness.

Some remarks that might help:

- There are some required properties, denoted by PropTypes.*.isRequired.
- You can extend props interface based on the component itself, no need to redefine "ref":
```typescript
interface MenuProps extends React.Props<Menu> {
//...
}
class Menu extends React.Component<MenuProps, {}> {
}
```
No circular reference problem here.

- Some components delegate some props to inner components, like this ```<Button {...this.props}>...```. For some components I extended Props from ```React.HTMLAttributes```, but this is not always possible, nor is it always 100% correct, since only a subset or the properties may be passed to the inner component. Another example is RaisedButton, which uses an EnhancedButton and so "extends" its properties.

- Some props defined in HTMLAttributes are redefined (e.g. style, icon), but sometimes with different types, making it impossible to extend from the HTMLAttributes interface.

Will post my d.ts later tomorrow, for cross-checking.

**Comment by ngbrown** [comment]
@use-strict:
> You can extend props interface based on the component itself, no need to redefine "ref":

I'm currently blocked by #5915 when the component extends `HTMLAttributes` and also has methods on the instance, which many do.  Those are still there to ensure that the underlying React library also gets changed or generate an error if it hasn't.  I was planning on removing them later.

> For some components I extended Props from React.HTMLAttributes, but this is not always possible, nor is it always 100% correct, since only a subset or the properties may be passed to the inner component. Another example is RaisedButton, which uses an EnhancedButton and so "extends" its properties.

I think it is ok to extend the `React.HTMLAttributes` in most cases because it is always going to add new properties.  I did implement `RaisedButtonProp` based on `SharedEnhancedButtonProp<T>`, based on `React.HTMLAttributesBase<T>`, so please take a look at it.

> You can use the same name for both exported variable and its type (I think there are similar examples in lib.d.ts)

I did this in many cases, for example, `Transitions` ([see line](https://github.com/borisyankov/DefinitelyTyped/pull/5918/files#diff-8ba8b7ac0df495642ca91f140dd3ffc7R916)), but in the case of `Typography`, the module exports an instance of a class, so I modeled it as such, and I can't share names between a class and a variable ([see line](https://github.com/borisyankov/DefinitelyTyped/pull/5918/files#diff-8ba8b7ac0df495642ca91f140dd3ffc7R940))

I don't have every component in there, and I haven't gone through them all and checked if there is an underlying HTML element (thus needing `HTMLAttributes`) yet, but I am fairly confident in what I have so far because I not only have the tests, I am using these components in a real project.

I welcome a collaboration to get this fleshed out.  I've probably spend 20 hours on the definitions so far, and they aren't complete yet.  I would like to see this merged soon so everyone has a common base to build from.

**Comment by use-strict** [comment]
@ngbrown , I implemented my changes here: https://github.com/ngbrown/DefinitelyTyped/pull/1 . Please review them and let's discuss if there is anything questionable in there.

**Comment by ngbrown** [comment]
@use-strict thanks a lot for helping.  I cleaned up some stuff, but your contributions really made this more complete.

**Comment by vvakame** [comment]
@pspeter3 @vsiao @jbrantly could you review this pull request about react.d.ts?

**Comment by jbrantly** [comment]
@vvakame I am in #5915 which is the react.d.ts changes here

**Comment by vvakame** [comment]
oh, same changes? thanks!
@ngbrown please merge master/HEAD into this PR.

**Comment by ngbrown** [comment]
@vvakame done..

**Comment by vvakame** [comment]
thanks mate!

**Comment by huwman** [comment]
Hi @vvakame, I'm waiting patiently for the Material-UI definitions :)
Can you give an approximate time when it will be generally available?

**Comment by jbrantly** [comment]
@huwman Sorry, I should have been more clear. This is the merged PR that implemented the material UI definitions. You can get them from here: https://github.com/borisyankov/DefinitelyTyped/tree/master/material-ui

**Comment by huwman** [comment]
@jbrantly That is very cool. Thanks to all that worked on it!

**Comment by huwman** [comment]
@ngbrown Do you have a project hidden somewhere that you used to test this?

**Comment by ngbrown** [comment]
@huwman normally a UI toolkit would be just one of many packages used in a project, so an option would be to find a TypeScript based React starter project.  I built my project manually so I haven't looked into this and have no recommendations.

See the files in the https://github.com/borisyankov/DefinitelyTyped/tree/master/material-ui directory for the DefinitelyTyped test.

Personally, I manage all the JS libraries through NPM, TSD for TypeScript definitions, and WebPack for hot-reload and bundling, but there really is no one way.  Experiment and find what works best for you and your project.

**Comment by use-strict** [comment]
@ngbrown , I just found an obscure behavior that allows to export the types as well via ```export = ```.

```typescript
declare namespace "material-ui/lib/dialog" {
    import Dialog = __MaterialUI.Dialog;
    export = Dialog;
}
```

The only difference is not exporting ```__MaterialUI.Dialog``` directly, but first importing it first as an alias, then re-exporting it.

Could be a subject for another PR :)

**Pull request merged**
