### PR TITLE
Add missing Mongo import

### PR DESCRIPTION
**Pull request by perbergland**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: removes typescript errors

### CODE REVIEW

**Review by radekmie — APPROVED** [review]
Code looks fine, however, could you explain _why_ is this change needed?

**Comment by perbergland** [comment]
Every .d.ts file needs to be standalone and include its own imports (this was missed when some  Mongo.X-typed parameters were added a few versions ago). Without it you get ts compile errors, but unfortunately these aren’t triggered in the unit tests here.

image

**Comment by radekmie** [comment]
Well, I knew that they have to be "isolatable", but I've never seen such an error. Where is this coming from?

Also, the fix is fine, however, we won't be able to merge it ourselves as it doesn't include any tests. Maybe you'd like to add one to release it faster?

**Comment by perbergland** [comment]
Found an untested method variant that I added a type test for (that typing seems weird but that’s another story)

**Review by radekmie — APPROVED** [review]

**Comment by perbergland** [comment]
Ready to merge

**Pull request merged**
