### PR TITLE
Update definitions for recompose

### PR DESCRIPTION
**Pull request by LKay**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by clayne11 — CHANGES_REQUESTED** [review]
Please remove the additional formatting.

**Comment by LKay** [comment]
@clayne11 Can you elaborate? What formatting?

**Comment by clayne11** [comment]
There's a lot of formatting changes and very few actual code changes. Please remove these unnecessary changes. It makes it hard to see what code has actually changed.

**Comment by LKay** [comment]
Wrapping everything in `declare module 'foo'` is "deprecated" way of definit types. interfaces an types should be exported directly from the file and types file should reflect module file structure. That is formatting change you are referring to. 

From other changes:
* Some unnecessary generics were removed 
* Added default type for `compose` (I can however change this to signature overloads)

**Comment by clayne11** [comment]
The formatting I'm referring to is adding semi-colons, changing whitespace, and wrapping JSX in brackets that weren't there before.

**Comment by LKay** [comment]
This is to follow the common, recommended linter rules for the whole DT ecosystem.

**Comment by clayne11** [comment]
I'd prefer to separate that into a separate PR then. Add one for updating the linter and another to make definition changes.

**Comment by RyanCavanaugh** [comment]
@LKay Please address the merge conflict.

**Comment by RyanCavanaugh** [comment]
@clayne11 - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?

**Review by clayne11 — CHANGES_REQUESTED** [review]
Separate formatting change from code change.

**Comment by minestarks** [comment]
@LKay could you please address the code review feedback and fix the merge conflicts?

**Pull request closed without merging**
