### PR TITLE
[AngularJS] Update Directive typings to allow type checking links with TS compiler's strict mode

### PR DESCRIPTION
**Pull request by QuentinBouygues**
As described in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21160, if we want to use TypeScript's strict mode, we currently have to declare directive's link parameters as `any`, and type them later is we want to use our own type definitions. To cite @thorn0: 

> This time the problem is $attrs: ISetFocusOnAttrs. In TS 2.6+, function parameters are contravariant > when strictFunctionTypes is set to true. However, ISetFocusOnAttrs is a subtype of 
> angular.IAttributes, not a supertype. The workaround would look like this:
> ```js
> const linkFn = (_$scope: angular.IScope, $element: JQLite, $attrs0: angular.IAttributes) => {
> 	const $attrs = $attrs0 as ISetFocusOnAttrs
> 	// ...
> };
> ```
> Seems like one more type argument should be added to IDirective. A PR is welcome. 🛠

So here is a PR with a proposal to fix it ! 

I chose to use generics for the link function parameters, in order to use custom types for the element, attributes and controller. 

With these changes, providing generics to `IDirective` (for example) will allow us to type the `link` function variables to subtypes of `JQuery`, `IAttributes` and  `IDirectiveController`. (as we do it currently for custom scopes)

### Questions / concerns

- Existing tests did not break, but should I add a test section with generics for each parameter ?
- I did not encounter breaking changes in my project when using these changes, but could it break existing typings in other's projects ?
- The typings are made for TS 2.3, and strict mode appeared in TS 2.6 => Is this change wanted and should I bump the version in the comments ?
- Should I cascade generics in `line 243` and `line 1349`

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.angularjs.org/api/ng/service/$compile#-link- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21160
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by thorn0** [comment]
> Existing tests did not break, but should I add a test section with generics for each parameter ?

Yes, please add at least a couple of tests with custom types for attributes, controllers, etc using `angular.directive` with factories returning both DDOs and only link functions.

> I did not encounter breaking changes in my project when using these changes, but could it break existing typings in other's projects ?

It shouldn't as far as I can tell.

> The typings are made for TS 2.3, and strict mode appeared in TS 2.6 => Is this change wanted and should I bump the version in the comments ?

They still are compatible with TS 2.3, so no need to bump it.

> Should I cascade generics in line 243 and line 1349

Yes. Or how are you going to use these types that you added?

**Review by thorn0 — CHANGES_REQUESTED** [review]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31392#issuecomment-447342871

**Comment by QuentinBouygues** [comment]
Thanks for the fast review @thorn0, I applied your comment.

Is it what you expected, should I also add tests for other types, like `IDirectivePrePost` ?

**Review by thorn0 — CHANGES_REQUESTED** [review]
Please add tests for `angular.directive`.

**Comment by QuentinBouygues** [comment]
Hi @thorn0, I added two different kind of tests (in the two commits). Is the last one the one you expected ?

**Review by thorn0 — APPROVED** [review]

**Comment by thorn0** [comment]
Thank you @QuentinBouygues !

**Comment by QuentinBouygues** [comment]
A pleasure, thanks for the short review cycles @thorn0 !

**Pull request merged**
