### PR TITLE
Updating kafka-node typings with ConsumerGroup definitions

### PR DESCRIPTION
**Pull request by bkim54**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/SOHU-Co/kafka-node#consumergroup>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by bkim54** [comment]
@dt-bot i dont think @dansitu is currently active on github, could this PR be merged by someone else?

**Comment by aozgaa** [comment]
I'm unfamiliar with `kafka-node`, so I'm not confident in the accuracy of the typings. Could @haio, @hyperlink, @crzidea 👍  or 👎

**Comment by hyperlink** [comment]
Not too familiar with typescript but this looks reasonable to me.  Thanks @aozgaa and @bkim54!

**Review by hyperlink — APPROVED** [review]

**Comment by bkim54** [comment]
@aozgaa is the new @types/kafka-node package published yet?

**Comment by bkim54** [comment]
nvm its 1.3.0

**Pull request merged**
