### PR TITLE
Auth0-lock languageDictionary types added

### PR DESCRIPTION
**Pull request by niksajanjic**
If changing an existing definition:
- https://auth0.com/docs/libraries/lock/v11/configuration#languagedictionary-object-
- https://github.com/auth0/lock/blob/master/src/i18n/en.js

Changes:
- added types for languageDictionary option in configuration options for auth0-lock.
- updated tests

### CODE REVIEW

**Comment by carusology** [comment]
@niksajanjic thanks for the contribution.

Even after your second commit, the indentation is still being altered with no other changes on many lines. Can you rebase so we don't get a bunch of whitespace based alterations in the file history?

Hey @luisrudge! 👋  Can you comment on this? We're going from an "any" type to a specific mapping of values in the dictionary. Can we count on the keys for the language dictionaries for the lock to always be embedded into the auth0-lock npm module? If so, we can absorb the management of the dictionary values in the typescript definition.

**Comment by niksajanjic** [comment]
For the indentation issue, if you mean inside test file it is intentional. The reason is the fact that `.editorconfig` file specifies indentation size of 4. If the intention is to keep it 2 as it was before I'll revert it.

For the second issues, if it means anything, there were no changes between auth0-lock 11.4 and 11.14 for the `languageDictionary`. Last time some props were added was 4 months ago. Type of any prop inside `languageDictionary` should never change from `string`. In case any new props would be added or some deleted, we could track it and update.

**Comment by carusology** [comment]
> For the indentation issue, if you mean inside test file it is intentional. The reason is the fact that .editorconfig file specifies indentation size of 4. If the intention is to keep it 2 as it was before I'll revert it.

Ah, you're right. Since that's in the `.editorconfig` I'll assume that's what Microsoft is trying to standardize behind. However, the actual update to adding the `languageDictionary` should be a separate commit from the indentation fix. In its current form, 6fcf6f85f2ee254c5cdbd206f643070eaf40b0c2 is resetting the line-by-line revision history.

> For the second issues, if it means anything, there were no changes between auth0-lock 11.4 and 11.14 for the languageDictionary. Last time some props were added was 4 months ago. Type of any prop inside languageDictionary should never change from string. In case any new props would be added or some deleted, we could track it and update.

It's not just the language dictionary hasn't changed in the repository, it's whether or not the npm module is authoritative. I suspected that the dictionary might be able to be extended at runtime, and that appears to be true. Looking at [this documentation](https://auth0.com/docs/libraries/lock/v11/customizing-error-messages), Auth0 shows how to add custom error messages, which involves adding a value to the language dictionary. If someone tried to implement a custom error message as described there, this change would cause the typescript compiler to fail.

**Review by luisrudge — CHANGES_REQUESTED** [review]
every dictionary object can be extend, so I guess we need a way to add custom properties in the typing as well

**Comment by carusology** [comment]
Thanks, @luisrudge. 

> every dictionary object can be extend, so I guess we need a way to add custom properties in the typing as well

That can be done by adding the `[key: string]: string` property to the language dictionaries, leaving the current values as suggestions for auto-completion, but any property name can be added to the dictionary. For example:

```ts
{
  foo: number,
  bar: Date,
  [key: string]: string
}
```

**Comment by niksajanjic** [comment]
@luisrudge @carusology There is one issue with that solution. I'm not able to add `[key: string]: string;` on `Auth0LockLanguageDictionaryOptionsError` nor `Auth0LockLanguageDictionaryOptionsBasic`. The reason is best explained in this open issue:
https://github.com/Microsoft/TypeScript/issues/17867

As a workaround I added `[key: string]: string | {};`. Problem is that this is wrong. I guess there should never be a chance to add a custom property that can be an object. This is especially wrong in a way that it allows you to add the custom property as an object inside which you can have any number of props with any type. This is currently TS limitation.

I also created a new example branch. Due to the comment about commits not being done in a proper way, I tested `git revert` option and have fixed commits in a way that I first add a feature and then fix indentation (hopefully this is correct). Here is a branch with both fixes (not sure if there's a way to remove old commits):
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...niksajanjic:test-revert?expand=1

**Comment by luisrudge** [comment]
@niksajanjic forgive my lack of understanding on this issue, can anyone that is using those typings extend the interfaces themselves? Something like this:

```
import Auth0Lock from 'auth0-lock';

interface Auth0LockLanguageDictionaryOptionsBasic {
  myCustomError: string;
}

var lock = new Auth0Lock('clientId', 'domain', {
  languageDictionary: {
    myCustomError: "Test"
  },
})
```

**Comment by niksajanjic** [comment]
Not really, you can only apply merging strategy to locally scoped interfaces. What could be done is module augmentation:
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Again, the problem is that you can only augment exported declarations. In our case, that is `Auth0LockStatic` interface and it doesn't have any declarations of our interest that we can augment.

**Comment by luisrudge** [comment]
image

https://github.com/georgwittberger/jquery-plugin-typescript-example/blob/master/src/example-plugin-interface.d.ts#L46

Why can't we do something like this?

**Comment by niksajanjic** [comment]
Yes, I read that too. It's in here: https://www.typescriptlang.org/docs/handbook/declaration-merging.html.

But, if you scroll down you will see this:
```
Module Augmentation

Although JavaScript modules do not support merging, you can patch existing objects by importing and then updating them.
```

The thing is, if I use your example from above and copy it into tests:
```
import Auth0Lock from 'auth0-lock';

interface Auth0LockLanguageDictionaryOptionsBasic {
  myCustomError: string;
}

var lock = new Auth0Lock('clientId', 'domain', {
  languageDictionary: {
    myCustomError: "Test"
  },
})
```

that `Auth0LockLanguageDictionaryOptionsBasic` is gonna be defined but never used and test will still fail. The reason is that modules have their own scope. So interface `Auth0LockLanguageDictionaryOptionsBasic` inside `index.d.ts` doesn't merge with `Auth0LockLanguageDictionaryOptionsBasic` interface in `auth0-lock-tests.ts` as they are in different scopes. All that happens is that `Auth0LockLanguageDictionaryOptionsBasic` interface inside `auth0-lock-tests.ts` is a separate interface, that exists inside the scope of `auth0-lock-tests.ts` file and has nothing to do with the interface in the definition file.

I hope this is what you were getting at, but it seems like it's not possible. The only option we have is augmentation, which I tried in a few different ways with no success. I'm not saying that there is no way at all, I'm just saying that I couldn't find it.

I'm sorry, maybe I'm just not understanding you, or missing something that TS offers to fix this problem. Same goes with this:
https://github.com/georgwittberger/jquery-plugin-typescript-example/blob/master/src/example-plugin-interface.d.ts#L46

I don't understand what are you getting at with this, not sure how is this supposed to help us. I'm sorry.

Maybe there is no progress until they fix that bug I mentioned up there.

**Comment by luisrudge** [comment]
I have a limited understanding on this, that's why I'm asking a lot of questions (maybe they don't make sense, sorry about that).

I guess we have to understand why extending the jQuery interface works but extending our own dictionaries doesn't.

**Comment by niksajanjic** [comment]
No worries at all, I also have a limited understanding of TS, not too much experience with it. I'll dig deeper once again when I get the time. I'll take a look at how jQuery can get extended and maybe some other libs. I hope to get some idea out of it.

**Pull request closed without merging**
