### PR TITLE
[react-dnd] Added definition for DragDropContextProvider

### PR DESCRIPTION
**Pull request by TiuSh**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://react-dnd.github.io/react-dnd/docs-drag-drop-context-provider.html
- [x] ~~Increase the version number in the header if appropriate.~~
- [x] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

### CODE REVIEW

**Comment by vsiao** [comment]
This was first added by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19171 —the approach taken there is preferred (using `class`).  It's just missing tests, but the PR seems to have been abandoned, so you're also welcome to try!

**Comment by uniqueiniquity** [comment]
@vsiao Did you intend to approve this PR, or were you requesting a change?

**Comment by uniqueiniquity** [comment]
@TiuSh Please add a test for the new signature.

**Comment by vsiao** [comment]
This was already added by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19765.

**Comment by uniqueiniquity** [comment]
Closing, since change was already made in a different PR.

**Pull request closed without merging**
