### PR TITLE
[express] [express-serve-static-core] Expose Locals express namespace type for global override

### PR DESCRIPTION
**Pull request by bombillazo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by bombillazo** [comment]
will retake soon

**Comment by bombillazo** [comment]
need to retake

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## express ([<kbd>unpkg</kbd>](https://unpkg.com/browse/express@latest/))
was missing the following properties:
1. Route
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dbabd6104658b590557ef65bf37786683a65c4b8
</p>

**Comment by chrisb2244** [comment]
Copying the changed files into my local `node_modules/@types/express/index.d.ts` and `express-serve-static-core/index.d.ts` worked well for me (obviously will be replaced on install, different computer, whatever) but allows a simple extension for Locals in a separate (local) `.d.ts` file 👍 

I didn't evaluate the comment by DangerBotOSS above, so I don't have feedback on that.

Thanks @bombillazo, hope this can be merged.

**Comment by sandersn** [comment]
The structure of this addition looks reasonable to me, especially since express-serve-static-core already has some open interfaces like this.

However, express is a critical package, so I'd like signoff from one maintainer too:
@borisyankov @micksatana @samijaber @JoseLion @dwrss @andoshin11 https://github.com/CMUH @puneetar @dfrankland can you take a look?

**Comment by bombillazo** [comment]
Updated recent master merge into this feature branch. Awaiting review

**Review by sheetalkamat — APPROVED** [review]

**Comment by DavideViolante** [comment]
After updating `@types/express` on my project, tsc now returns error:
```
node_modules/@types/express/index.d.ts:112:35 - error TS2694: Namespace '"/home/dave/Job/mycompany/node_modules/@types/express-serve-static-core/index"' has no exported member 'Locals'.

112     interface Locals extends core.Locals {}
                                      ~~~~~~
```

"@types/express": "^4.17.16",
   
"express": "^4.18.2",
 
I switched back to v4.17.15

**Comment by bombillazo** [comment]
That's because [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64042) needs to be merged to set the correct version depenency

**Pull request merged**
