### PR TITLE
add gsap TweenLite declarations

### PR DESCRIPTION
**Pull request by vilicvane**

### CODE REVIEW

**Comment by vvakame** [comment]
@vilic thanks mate. but we need a test a little more. :wink:

**Comment by vilic** [comment]
T-T I understand. But one may not have enough time to write that. Maybe you may create a tag named `accepting test samples` so others may do that part when they are free.

**Comment by AlexGalays** [comment]
Hello, how is this supposed to work? There are no module declarations, typings don't find gsap in the repository at all?

**Comment by vilic** [comment]
@AlexGalays I created this declaration for global usage, please refer to other declaration files to add external module declaration. (Also with the help of `this` type, the declaration can be simplified a lot.)

**Pull request merged**
