### PR TITLE
fix(aria-query): correct DT header author handle

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This corrects the DT package owner handle, to avoid
DT package staying in limbo,

/cc @eps1lon 

Thanks!

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
requires @eps1lon input to be merged,
thanks!

**Review by eps1lon — APPROVED** [review]
Whoops :)

**Comment by peterblazejewicz** [comment]
no worries, happens to everyone, including me, I'll look later into the DT linter (on the freshly created DT package to avoid first commit with that thing missing - assuming handle is optional one)

**Comment by orta** [comment]
👍

**Pull request merged**
