### PR TITLE
SOAP - Added missing authentication functions

### PR DESCRIPTION
**Pull request by JJayet**
This adds missing function declarations.
I also added a tslint and fixed some issues BUT, I have a small linter warning : using Function instead of the arrow-type function. This is required in order to compile.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/vpulim/node-soap
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
@JJayet please address the lint failures

**Comment by JJayet** [comment]
@mhegazy I removed the lint because I (think that I) can't remove the `Function` type :(

**Comment by aleung** [comment]
This PR becomes difficult to review. 141 commits are included.

**Comment by JJayet** [comment]
@aleung You're absolutely right, I'll close it and reopen later with less commits :)
I rebased it and it was obviously a mistake on my part !

**Comment by aleung** [comment]
@JJayet thanks!

**Pull request closed without merging**
