### PR TITLE
[urijs] Add ReadonlyURI interface (immutable subset of URI)

### PR DESCRIPTION
**Pull request by AlexeyMz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## urijs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/urijs@latest/))
was missing the following properties:
1. version
1. protocol_expression
1. idn_expression
1. punycode_expression
1. ip4_expression

<details>
<summary>as well as these 19 other properties...</summary>
<p>ip6_expression, find_uri_expression, findUri, defaultPorts, hostProtocols, invalid_hostname_characters, domAttributes, getDomAttribute, characters, decodePath, decodeUrnPath, recodePath, recodeUrnPath, buildQueryParameter, setQuery, hasQuery, ensureValidHostname, ensureValidPort, noConflict</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4cdc324da2c46374506b5fc8bb39a504779e76fd
</p>

**Review by marcelltoth — COMMENTED** [review]
Looks OK, but shouldn't `URI` extend `ReadonlyURI` now (and remove all duplicates)?

**Comment by AlexeyMz** [comment]
@marcelltoth I tried to make `URI` extend `ReadonlyURI` but unfortunately this does not work with overloaded methods, i.e.
```
interface ReadonlyURI {
  ...
  fragment(): string;
}

// Error ts(2430):
// Interface 'URI' incorrectly extends interface 'ReadonlyURI'.
//   Types of property 'fragment' are incompatible.
//     Type '(fragment: string) => URI' is not assignable to type '() => string'
interface URI extends ReadonlyURI {
  ...
  fragment(fragment: string): URI;
}
```

**Comment by marcelltoth** [comment]
> @marcelltoth I tried to make `URI` extend `ReadonlyURI` but unfortunately this does not work with overloaded methods, i.e.
> 
> ```ts
> interface ReadonlyURI {
>   ...
>   fragment(): string;
> }
> 
> // Error ts(2430):
> // Interface 'URI' incorrectly extends interface 'ReadonlyURI'.
> //   Types of property 'fragment' are incompatible.
> //     Type '(fragment: string) => URI' is not assignable to type '() => string'
> interface URI extends ReadonlyURI {
>   ...
>   fragment(fragment: string): URI;
> }
> ```

I see, you're right. Interestingly I checked and it works fine if using type aliases, rather than interfaces, see [REPL here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4CgCQGA9gLYQCyEYAFkQCYAUAlAFzIZhSgDmA3LgF9cuUJFiIUAYWrAANnWQQAHpBB0MaTDgLEylGvQZw2IAK4kARtFbIzl6PyG4wATwAOKACrosyALzIeISkFFS0jDYcXCB8gsKuHsie0nIKAd5ayABkgToh+uFGJuZWUDZ2pY7CdBAIsnBQKAhEIBzIkBwA8hYAVmzJMvL8zhBdvQB0uqEGEfwdYN09k-lhhgDMTLxAA).

Surprising as I thought pretty much all differences were eliminated around TS 4.0.
What do you think about converting the URL interface to a type alias? Shouldn't be a big deal, right?

**Comment by AlexeyMz** [comment]
@marcelltoth Sorry for long delay, I think changing the definition from `interface` to `type` might have compilation performance consequences, see https://twitter.com/drosenwasser/status/1319205169918144513

Considering the popularity of this package I suggest to keep it as `interface` for now until there will be a good solution in the future. To avoid accidental assignment incompatibility from URI to `ReadonlyURI` I added a test.

**Review by TeamworkGuy2 — APPROVED** [review]

**Comment by AlexeyMz** [comment]
Ready to merge

**Pull request merged**
