### PR TITLE
Added updateSettings() for node/http2 

### PR DESCRIPTION
**Pull request by Vboivin**
##  New Definitions for Method Added By https://github.com/nodejs/node/pull/35383

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/pull/35383
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by Flarna** [comment]
Isn't this a little bit early? your PR for node is not yet merged. Once merged it will take a while until a 14.x release is done.

**Comment by Vboivin** [comment]
> Isn't this a little bit early? your PR for node is not yet merged. Once merged it will take a while until a 14.x release is done.

@Flarna You are right. It might be too early. I could resubmit once the function is added to node, up to you

**Comment by Flarna** [comment]
You can keep this one open, just add WIP in title. Or delete and resubmit. It's ok to move it into ready for merge/review state a few days before the next 14.x will be released.

**Comment by elibarzilay** [comment]
WIP in the title doesn't help much with the workflow, instead, I'll convert it to draft.

**Comment by Vboivin** [comment]
updateSettings has been added to nodejs 15.1.0, https://github.com/nodejs/node/releases/tag/v15.1.0

**Comment by SimonSchick** [comment]
We need to wait for v15 typings to be created first, this should not be merged into v14.

**Comment by sandersn** [comment]
OK, I'll set this back to draft until then

**Pull request closed without merging**
