### PR TITLE
Add type for query paramater instead of any

### PR DESCRIPTION
**Pull request by kerolloz**

### CODE REVIEW

**Comment by kerolloz** [comment]
@linusbrolin @simonxca @woutgg @oktapodia @ChazEpps

**Review by Steve-Fenton — APPROVED** [review]
Tested using example from https://docs.mongodb.com/manual/tutorial/query-documents/

Typed the model with `mongoose.PaginateModel<Test>` with a test interface to check the inference / autocomplete experience.

Would be nice to see some tests for this one at some point in the future.

**Comment by kerolloz** [comment]
Hello @Steve-Fenton 
Thank you for your review! :smiley: 

When will this PR be merged?

**Comment by gamsterx** [comment]
Hi @kerolloz ,

I submitted #43779 a few days ago which just got merged recently. Seems like this pr is overriding all of the changes. Can you please check if this is intended or if this might be sync issue?

**Comment by kerolloz** [comment]
Hello @gamsterx

Why do you think this PR overrides your changes?
image
I have only changed one word. There is no conflict. Correct me if I am wrong, but when this PR is merged, it shouldn't override yours.

**Comment by gamsterx** [comment]
@kerolloz you are right. I must have gotten a little confused. Lack of sleep I guess... All good!

**Comment by kerolloz** [comment]
@gamsterx It's okay. No problem.

**Pull request merged**
