### PR TITLE
types/auth0: Add rules config types

### PR DESCRIPTION
**Pull request by ghost**
Hi,

this PR adds type definitions to the auth0 package. This PR also adds tests to those functions that have been executed against a test account. Namely, the following definitions are added:
**setRulesConfig**
* library docs https://auth0.github.io/node-auth0/module-management.ManagementClient.html#setRulesConfig
* API docs https://auth0.com/docs/api/management/v2#!/Rules_Configs/put_rules_configs_by_key

**getRulesConfig**
* library docs https://auth0.github.io/node-auth0/module-management.ManagementClient.html#getRulesConfigs
* API docs https://auth0.com/docs/api/management/v2#!/Rules_Configs/get_rules_configs

**deleteRulesConfig**
* library docs at  https://auth0.github.io/node-auth0/module-management.ManagementClient.html#getRulesConfigs
* API docs at https://auth0.com/docs/api/management/v2#!/Rules_Configs/delete_rules_configs_by_key

Thank you for your work and let me know if I can help any further.

Best wishes :)

### CODE REVIEW

**Comment by akvamalin** [comment]
I see that the prettier has caused quite a lot of formatting, however the only changes I added are quite few. Let me know if I should do anything with this ^_^

**Comment by pwrnrd** [comment]
@akvamalin Thank you very much for your PR! Could you please change the formatting? Because it takes too much time to manually check formatting changes (it's not only this PR, but also future PRs using the old formatting again or switching back and forth between formats). Simple changing the formating will take less development time compared to review time.

**Comment by akvamalin** [comment]
Hi @pwrnrd, thanks a lot for responding to this PR. I can definitely understand your point. I have done the prettifier because the CI failed, however now I only fixed the exact errors of the failing CI. Looks better for me now :)

Let me know if I need to take any further actions, so far thank you and have a nice weekend :)

**Comment by pwrnrd** [comment]
Thanks a lot! One question though: getRulesConfig() does not take a parameter according to the documentation but the example in Auth0's documentation does mention a callback. Just to be sure, the callback parameter is supported?

**Comment by akvamalin** [comment]
Hi @pwrnrd, 
i definitely see your point, thanks for mentioning it. The absence of callback there would not allow you to get the results in a callback fashion. I have double-checked and re-run the checked in tests:
```js
management.getRulesConfigs((err, configs) => console.log(configs));
// Output: [ { key: 'test' } ]
```
The callback must be there and I will ping Auth0 to re-check those docs.

Have a nice day :)

**Review by pwrnrd — APPROVED** [review]
Thank you very much!

**Review by orta — APPROVED** [review]

**Pull request merged**
