### PR TITLE
Fix PlatformOSType for TS2.0 - fixes #10108

### LINKED ISSUE #10108: React native Binding element 'any' implicitly has an 'any' type
This part is failing in TypeScript 2.0

```
    export interface PlatformStatic {
        OS: PlatformOSType,

        // only documented in PlatformSpecificInformation.md
        select({PlatformOSType: any}): any
    }
```

with error: Binding element 'any' implicitly has an 'any' type

Seems like the issue is exactly as described in here: https://github.com/Microsoft/TypeScript/issues/9657#event-721064694

Should be `select({PlatformOSType}:{PlatformOSType: any}): any`

### PR DESCRIPTION
**Pull request by normalser**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by bgrieder** [comment]
@wallverb Hi. It is true that the definition of `select` need to be fixed, however, your proposed fix does not compile with TS 1.8, which is the official version right now.

In the meantime, may I suggest the less elegant but more generic

     select<T>( specifics: { ios?: T, android?: T} ): T;

This can be used this way when matching union types

    <TextInput
        keyboardType={Platform.select<'url'|'default'>({ios: 'url', android: 'default'})}
     />

or, opting out of type checking,

    <TextInput
        keyboardType={Platform.select<any>({ios: 'url', android: 'default'})}
     />

**Comment by wallverb** [comment]
@bgrieder I tried to compile it with TypeScript 1.8.10 and it worked fine.

You can even paste that part into their playground and everything is fine

```
    export type PlatformOSType = 'ios' | 'android'

    export interface PlatformStatic {
        OS: PlatformOSType,

        // only documented in PlatformSpecificInformation.md
        select({PlatformOSType}:{PlatformOSType: any}): any
    }
```
or
```
function select({PlatformOSType}:{PlatformOSType: any}): any {
    
}
```

**Comment by bgrieder** [comment]
@wallverb My bad, this is not a TSC 2.0 issue, but a definition issue

This does not compile

    type PlatformOSType = 'ios' | 'android'

    function select({PlatformOSType}:{PlatformOSType: any}): any {
	    /* whatever */
    }

    select({ios: 'This is ios', android: 'This is android'})

See it on [playground](https://www.typescriptlang.org/play/#src=type%20PlatformOSType%20%3D%20'ios'%20%7C%20'android'%0D%0A%0D%0Afunction%20select(%7BPlatformOSType%7D%3A%7BPlatformOSType%3A%20any%7D)%3A%20any%20%7B%0D%0A%09%2F*%20whatever%20*%2F%0D%0A%7D%0D%0A%0D%0Aselect(%7Bios%3A%20'This%20is%20ios'%2C%20android%3A%20'This%20is%20android'%7D))

Usage of select is described [there](https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-module)

**Comment by wallverb** [comment]
@bgrieder Thanks for the clarification, updated definition according to your recommendation

**Comment by bgrieder** [comment]
@wallverb This actually went in a few minutes ago in a bunch of commits that were merged, hence the conflict.
If you pull the new definitions for react-native from DefinitelyTyped, it should be already be in

Thanks for contributing

**Comment by bgrieder** [comment]
👎 
Please close

**Comment by wallverb** [comment]
Thanks

**Pull request closed without merging**
