### PR TITLE
[npm] Add all commands and update to npm 7.19.0

### PR DESCRIPTION
**Pull request by oBusk**
Just adding all the commands that I could find that was not already there. It's possible that versions has added/modified configs or other parts, but these changes seem to work in the usecases I've tested it.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    - https://docs.npmjs.com/
    - https://github.com/npm/cli/tree/v7.19.1/lib
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by oBusk** [comment]
I also got rid of the Namespace "NPM" and used the [recommended default export](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports).

This means that `import * as npm from "npm";` will not work but from what I can tell this should not work in npm7 anyway

**Comment by oBusk** [comment]
> 
> 
> I also got rid of the Namespace "NPM" and used the [recommended default export](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports).
> 
> This means that `import * as npm from "npm";` will not work but from what I can tell this should not work in npm7 anyway

`dtslint` disagreed on my life choices and thus I've repented for my sins. (The export is back to `export =`, but I remembered how to export the namespace so that you can access the interfaces still.

**Comment by sandersn** [comment]
I don't want to merge a change that I don't understand to a widely used package. @wsmd @SomaticIT can you review this change?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by oBusk** [comment]
Ready to merge

**Pull request merged**
