### PR TITLE
[GraphQL] GraphQL Subscription type definition

### LINKED ISSUE #17441: graphql: definition for subscribe is missing
- [X] I tried using the `@types/graphql package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer> @calebmer @intellix @firede

When trying to use the example from here:
https://github.com/apollographql/tools-docs/blob/master/tools/graphql-subscriptions/meteor.md

For this line:
``` JavaScript
import { execute, subscribe } from 'graphql';
```
I get this error:
```
Module '"node_modules/@types/graphql/index"' has no exported member 'subscribe'.
```

It looks like the new subscribe function is not included int the definitions.
(See [here](https://github.com/graphql/graphql-js/blob/a1f63083fb1abb7cb3d57754ae41a54c8ff4b382/src/index.js#L247) for the actual source.)

The relevant lines from my package.json:
```
    "@types/graphql": "0.9.2",
    "graphql": "0.10.3",
```

### PR DESCRIPTION
**Pull request by kepennar**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/graphql/graphql-js/tree/master/src/subscription>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fix #17441

### CODE REVIEW

**Comment by kepennar** [comment]
I had to force typescript 2.3 for using `esnext.asynciterable` lib

**Comment by blakeembrey** [comment]
Shouldn't this inline the type definition or use them from https://github.com/leebyron/iterall? The library doesn't actually require native async iterables, it uses that library instead.

**Comment by kepennar** [comment]
@blakeembrey 
Iterall typing definition say to use the Typescript built-in AsyncIterable support
https://github.com/leebyron/iterall/blob/master/index.d.ts#L9

**Comment by blakeembrey** [comment]
Ok, thanks. That's unfortunate, the PR breaks anyone using it without the `lib` option. I'll have to make sure any projects I have avoid exposing these types externally so people don't need to change the `lib` option.

**Comment by kepennar** [comment]
You can use the typings per typescript version dependencies
`npm i -D @types/graphql@ts2.1` will not install the last version with the `asynciterable` lib but an older one

**Comment by blakeembrey** [comment]
Absolutely, I'm aware. This isn't to do with TypeScript versions though, it's related to requiring consumers of third-party libs to enable an option and that is a breaking change I needed to avoid.

**Comment by kepennar** [comment]
I see what you mean and I agree about the breaking change. But in fact `esnext.asynciterable` is provided by Typescript. It's not a third-party lib

**Comment by blakeembrey** [comment]
I know, it's not what I said. I said any third-party libraries using `@types/graphql` now need to enable the `esnext.asynciterable` lib, making it a breaking change. This also means transitively if I have a module (e.g. a GraphQL server module) that includes `@types/graphql`, that can require any consuming the third-party library to also enable the lib option in TypeScript. It's a cascade of breaking changes.

**Comment by blakeembrey** [comment]
It's just an unfortunate situation that may cause future confusion. Any existing documentation for TypeScript + GraphQL today is now out-of-date (`esnext` is not a default). New TypeScript users will not know about the `lib` option. If there's some way we can inline this, I believe it's still a better option. This is related to a couple of TypeScript issues that I can find up if needed, but off the top of my head I think they are "compile time regions" and "known TypeScript symbols `@@iterator`".

**Comment by kepennar** [comment]
I agree if there is another solution than the esnext lib, it could be a good solution.
When I push this change I couldn't find any other clean solution.

**Comment by blakeembrey** [comment]
Agreed. Wasn't trying to stir anything up with you, just trying to think of a better approach. What about just copying https://github.com/Microsoft/TypeScript/blob/master/lib/lib.esnext.asynciterable.d.ts inline? It's only five lines of code and no one needs to enable the `lib` option then since all the types already exist in ES6.

@RyanCavanaugh is there a plan in TypeScript to publish any of the `lib` code separately to TypeScript core?

**Comment by andy-ms** [comment]
See Microsoft/TypeScript#15780.

**Pull request merged**
