### PR TITLE
feat(react): add DragEvent

### PR DESCRIPTION
**Pull request by ggarek**
Added definitions for [SyntheticDragEvent.js](https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/browser/syntheticEvents/SyntheticDragEvent.js)

### CODE REVIEW

**Comment by vvakame** [comment]
@pspeter3 @vsiao could you review this PR?

**Comment by vsiao** [comment]
ah, wonderful—I've been meaning to do this myself. looks good! thanks, @ggarek.

**Comment by pspeter3** [comment]
I think you need to add these to the addons file as well.

**Comment by vsiao** [comment]
oh yeah, @ggarek please take a look at the README at https://github.com/borisyankov/DefinitelyTyped/tree/master/react: You'll need to add the interface to `react-addons.d.ts` as well as `react-global.d.ts`.

**Comment by ggarek** [comment]
@vsiao all done.

Thank you, guys, for review! Did not expect it to happen so soon ^__^

**Comment by vsiao** [comment]
:+1: 
cc @vvakame

**Comment by vvakame** [comment]
@pspeter3 @vsiao thanks!
@ggarek thanks mate!

**Pull request merged**
