### PR TITLE
[greasemonkey] Do not return undefined when given defaultValue.

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/737490bebf45498b67622ccf5390e15cdd255747/types/greasemonkey/index.d.ts#L205-L206

### CODE REVIEW

**Comment by PythonCoderAS** [comment]
I'm not really sure how to handle the lint error in this case.

**Comment by nikolay-borzov** [comment]
Me neither. But [`no-unnecessary-generics`](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-unnecessary-generics.md) rule description says 

> If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion

For this case this could work:
```js
getValue(name: string): Promise<GM.Value | undefined>
````

Also, could please add some tests for changed definitions?

**Comment by PythonCoderAS** [comment]
> Also, could please add some tests for changed definitions?

I was surprised since expected tests should have covered this. However, I realized that `strictNullChecks` was turned off on TypeScript, which would obviously not trigger this error. I am not knowledgeable on whether or not it is possible to turn `strictNullChecks` back on without causing other bits of code in the test file to fail.

**Comment by PythonCoderAS** [comment]
OK, upon further investigation it seems that merely changing the return type to GM.value (even without touching the tsconfig) leads to errors because you now can't narrow it down to a specific type. This would call for a breaking change but I'm not sure how those work in this package since the major and minor number is linked to the extension's version.

**Comment by nikolay-borzov** [comment]
I'll try to look into this issue today or tomorrow.

**Comment by nikolay-borzov** [comment]
This should work 
[getValue.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/9464569/getValue.zip)

**Review by nikolay-borzov — APPROVED** [review]

**Comment by PythonCoderAS** [comment]
Ready to merge

**Pull request merged**
