### PR TITLE
feat(babel-plugin-react-docgen): add types

### PR DESCRIPTION
**Pull request by forivall**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
how are those options to be consumed in the client code?

**Comment by forivall** [comment]
It's one of the pitfalls of babel plugins - the user has to opt-in to using typing for the options.

For example, for options for [`babel-preset-env`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/babel__preset-env), I use the options type like so in a `babel.config.ts`:

```ts
import type { TransformOptions } from '@babel/core';
import type { Options as BabelPresetEnvOptions } from '@babel/preset-env';

const presetEnvOpts: BabelPresetEnvOptions = {
  useBuiltIns: 'entry',
  corejs: 3,
  targets: ['last 2 Chrome versions'],
  exclude: ['transform-for-of', 'transform-async-to-generator'],
};
const babelConfig: TransformOptions = {
  presets: [
    ['@babel/preset-env', presetEnvOpts],
    ['@babel/preset-typescript'],
  ],
};
export default babelConfig;
```

in the same way, one would use the Options type for this plugin with
```ts
import type { Options as ReactDocgenOptions } from 'babel-plugin-react-docgen';
const reactDocgenOptions: ReactDocgenOptions = {
  "DOC_GEN_COLLECTION_NAME": "MY_REACT_DOCS",
  "resolver": "findAllComponentDefinitions", // optional (default: findAllExportedComponentDefinitions)
  "removeMethods": true, // optional (default: false)
  "handlers": ["react-docgen-deprecation-handler"] // optional array of custom handlers
};
export default { plugins: ['babel-plugin-react-docgen', reactDocgenOptions] }
```

**Comment by peterblazejewicz** [comment]
thx!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@forivall thx!

**Comment by forivall** [comment]
Ready to merge

**Pull request merged**
