### PR TITLE
[puppeteer] Include null return type for page's viewport method

### PR DESCRIPTION
**Pull request by iby**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [page.viewport()](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pageviewport)

### CODE REVIEW

**Review by SimonSchick — CHANGES_REQUESTED** [review]
Please provide a source for this changes (and don't ignore the PR template).

**Comment by SimonSchick** [comment]
Also please add a test.

**Comment by ianbytchek** [comment]
@SimonSchick Thanks for the tips! I updated the info and getting the following error during linting of the original package (without the PR). The same command passes for one of the latest accepted PRs, for example, `npm run lint c3`. Is this expected or does the puppeteer require special handling?

```sh
$ npm run lint puppeteer

> definitely-typed@0.0.3 lint /…/DefinitelyTyped
> dtslint types "puppeteer"

Error: /…/DefinitelyTyped/types/puppeteer/index.d.ts:1:1
ERROR: 1:1  npm-naming  d.ts file must have a matching npm package.
To resolve this error, either:
1. Change the name to match an npm package.
2. Add a Definitely Typed header with the first line


    // Type definitions for non-npm package puppeteer-browser

Add -browser to the end of your name to make sure it doesn't conflict with existing npm packages.

- OR -

3. Explicitly provide dts-critic with a source file. This is not allowed for submission to Definitely Typed.
 See: https://github.com/Microsoft/dtslint/blob/master/docs/npm-naming.md

    at /usr/local/lib/node_modules/dtslint/bin/index.js:190:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/dtslint/bin/index.js:5:58)
```

**Comment by ianbytchek** [comment]
@marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita Could you guys comment on the `npm run lint puppeteer` command failing [above](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38052#issuecomment-526899742)?

**Comment by cdeutsch** [comment]
Make sure you rebase on master and re-run `npm i`

I've run into issues where master was broken and caused weird build errors.

Definitely a lot of headache for such a simple fix/change  😞

**Pull request closed without merging**
