### PR TITLE
Add errorHandler argument to `*hot.accept` in webpack-env

### PR DESCRIPTION
**Pull request by faergeek**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://webpack.js.org/api/hot-module-replacement/#errorhandler-for-accept
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I'm not sure if version number here reflects webpack version or it's module API version somewhere.

### CODE REVIEW

**Review by samarmohan — CHANGES_REQUESTED** [review]
Nice, thanks for taking the time to contribute.

**Review by samarmohan — APPROVED** [review]
oops I misclicked

**Review by orta — APPROVED** [review]
Looks good to me

**Comment by faergeek** [comment]
Ready to merge

**Pull request merged**
