### PR TITLE
feat: add types for react-barcode

### PR DESCRIPTION
**Pull request by magichim**
type declarations for react-barcode
https://github.com/kciter/react-barcode

Please fill in this template.

- [&check;] Use a meaningful title for the pull request. Include the name of the package modified.
- [&check;] Test the change in your own code. (Compile and run.)
- [&check;] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [&check;] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [&check;] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [&check;] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [&check;] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [&check;] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [&check;] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [&check;] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [&check;] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [&check;] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by junggyoo — APPROVED** [review]
👍

**Comment by magichim** [comment]
@junggyoo Please review new commits and approve!

**Comment by peterblazejewicz** [comment]
the package seems to have it's own declaration:
https://github.com/kciter/react-barcode/blob/master/src/react-barcode.d.ts
the problem is it's not properly referenced in package.json, so it hasn't been published.
what is the relation of this file?

**Comment by jakebailey** [comment]
Yeah, if possible, it seems reasonable to see if the author is willing to take the couple-line PR that would just let them publish the types directly, unless you all have a compelling reason not to. I do see that people are reporting that the code there is many months newer than what's actually published on npm, though, which may imply that the fix won't actually occur upstream.

**Pull request closed without merging**
