### PR TITLE
Add types for @uswds/uswds

### PR DESCRIPTION
**Pull request by morganspencerdev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
does this module has it's own type or it doesn't?
https://github.com/uswds/uswds/blob/develop/package.json#L36

**Comment by morganmspencer** [comment]
> does this module has it's own type or it doesn't? https://github.com/uswds/uswds/blob/develop/package.json#L36

It doesn't seem to. looking at the[ tsconfig.json](https://github.com/uswds/uswds/blob/develop/tsconfig.json), it is only importing one script file. In the actual `node_modules` package that is downloaded it does not include any `.d.ts` files. I believe that attribute is just there as a placeholder, perhaps when the `package.json` was generated.

**Comment by peterblazejewicz** [comment]
FYI, I've created issue on the project, to discuss this problem.
Otherwise it's good.
Btw, you can opt to use proper symbols instead of namespaces ang kill more th 2 birds with one stone (shorter, same api, no rewrite, exports actual existing symbol representation), say:
```ts
export const accordion: {
    ACCORDION: string;
    BUTTON: string;
    init(root: HTMLElement | Document): void;
    on(el: HTMLElement): void;
    off(el: HTMLElement): void;
    show(button: HTMLButtonElement): boolean;
    hide(button: HTMLButtonElement): boolean;
    /**
     * Toggle a button's "pressed" state, optionally providing a target
     * state.
     *
     * @param button
     * @param expanded If no state is provided, the current
     * state will be toggled (from false to true, and vice-versa).
     * @return the resulting state
     */
    toggle(button: HTMLButtonElement, expanded?: boolean): boolean;
    /**
     * Get an Array of button elements belonging directly to the given
     * accordion element.
     * @param accordion
     * @return buttons
     */
    getButtons(accordion: HTMLElement): HTMLButtonElement[];
};
```
but that is just stylistic really. Let's just wait for someone commenting on the original project, OK?

**Comment by morganmspencer** [comment]
@peterblazejewicz thanks for opening that issue on the project! I've made the suggested changes (much cleaner 👍) and I'll wait for a response from the project

**Review by ConnorDY — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Cool, we can take your work I think. when original package fixes the problem, we will unpublish here on DT. They could take your work or start from scratch, whatever suits them best.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@morganmspencer thanks!

**Comment by morganmspencer** [comment]
Ready to merge

**Pull request merged**
