### PR TITLE
Specify lodash-es is of type module

### PR DESCRIPTION
**Pull request by remcohaszing**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/lodash-es?activeTab=explore (Search for and click `package.json`.)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## lodash-es ([<kbd>unpkg</kbd>](https://unpkg.com/browse/lodash-es@latest/))
was missing the following properties:
1. commit
1. lodash
1. next
1. plant
1. thru

<details>
<summary>as well as these 13 other properties...</summary>
<p>toIterator, toJSON, value, valueOf, wrapperAt, wrapperChain, wrapperCommit, wrapperLodash, wrapperNext, wrapperPlant, wrapperReverse, wrapperToIterator, wrapperValue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 649f56ba54cade9554043660df1b68bd887d2c7b
</p>

**Comment by jakebailey** [comment]
I have no evidence for this but I suspect that this might end up breaking for users in newer module resolution modes like node16/nodenext thanks to missing extensions in imports; can you test this locally by modifying node_modules in a package with the above and see what happens?

**Comment by remcohaszing** [comment]
You are correct. This change actually fixes usage with `node16` when importing the `lodash-es` exports other than `index.d.ts`, but it broke `index.d.ts`. I added the `.js` extension to all imports.

Maybe DefinitelyTyped could add an ESLint rule to enforce using extensions for relative imports? I don’t think it ever hurts, and it could catch issues like this and potentially fix several other packages if a codemod adds them. Of course this is only true for relative imports, others may be affected by export maps.

**Comment by remcohaszing** [comment]
You are correct. This change actually fixes usage with `node16` when importing the `lodash-es` exports other than `index.d.ts`, but it broke `index.d.ts`. I added the `.js` extension to all imports.

Maybe DefinitelyTyped could add an ESLint rule to enforce using extensions for relative imports? I don’t think it ever hurts, and it could catch issues like this and potentially fix several other packages if a codemod adds them. Of course this is only true for relative imports, others may be affected by export maps.

**Comment by jakebailey** [comment]
The actual fix will be to switch to moduleResolution=nodenext, once we can get that allowed on DT.

**Comment by remcohaszing** [comment]
I know! But that’ll take another year or so :cold_sweat:

**Comment by jakebailey** [comment]
Last I knew, Andrew was already working on it.

**Comment by remcohaszing** [comment]
As in, it’s being backported? Because I meant to reference the [support window](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window) in combination with the fact that `moduleResolution: node16` was introduced in TypeScript 4.7.

---

Back to track: this PR fixes usage of the `lodash-es` package with `moduleResolution: node16`, and I verified it. I think it’s good to go?

**Comment by jakebailey** [comment]
Well, we could use nodenext instead, or people can just write a minimum and be fine too.

I'll review the PR in a bit; I want to really verify that this works given which package this is.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Let's give it a try; easy to revert if things go wrong. Tested on a random repo and it seemed to be fine.

**Comment by remcohaszing** [comment]
Ready to merge

**Pull request merged**
