### PR TITLE
passport: Added generic versions of serializeUser and deserializeUser

### PR DESCRIPTION
**Pull request by RandScullard**
Added generic versions of serializeUser and deserializeUser for strong typing. Kept the existing versions with "any" typing for backward compatibility.

### CODE REVIEW

**Comment by vvakame** [comment]
*passport/passport.d.ts*

to author (@horiuchi). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request
Now, we are working on types-2.0 branch mainly. could you send this PR to that branch?

**Comment by horiuchi** [comment]
That's nice! 👍

**Comment by RandScullard** [comment]
@vvakame I'd love to move this forward. Should I close this PR and open a new one against types-2.0?

**Comment by vvakame** [comment]
as you like.
If you clone this PR & open new PR, please make links to this PR.

**Comment by RandScullard** [comment]
@vvakame I created PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12446 against types-2.0.

**Pull request merged**
