### PR TITLE
github-electron: Add missing menu item option 'role'

### PR DESCRIPTION
**Pull request by rhysd**
I noticed that `MenuItemOptions` lacks `role` option.  So I added.

https://github.com/atom/electron/blob/master/docs/api/menu-item.md#new-menuitemoptions

### CODE REVIEW

**Comment by jedmao** [comment]
:+1: 

Looks like it was added in https://github.com/atom/electron/commit/6bce5b560bc04b9caa720bb89a73f3096a0ac120#diff-27aca9003e7bfe3e2c635e67d04fc917 on Sep. 1, 2015.

**Comment by rhysd** [comment]
@jedmao 

Thank you for your review.

BTW, do you have any plan to update type definitions for interface changes in Electron v0.35?  Some upper case names are changed to camel case and all modules are defined in `electron` module. In addition, name of ipc module is separated for main process and render process.

**Comment by jedmao** [comment]
I have no plans. I don't even use these definitions.

**Comment by rhysd** [comment]
@jedmao 

Thanks.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
