### PR TITLE
Allow null and undefined on classnames

### PR DESCRIPTION
**Pull request by jonnystoten**
The docs for classnames say that this is legit: https://github.com/JedWatson/classnames#usage

### CODE REVIEW

**Comment by jonnystoten** [comment]
Hmmm, I guess the automated build runs on TypeScript 1.x? Should I make this pull request to another branch if it contains TypeScript 2.0 features?

**Comment by TonyPythoneer** [comment]
@jonnystoten You are right. The CI runs on [Typescript 1.8.7](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/163361205#L402). So, the new types on 2.0 run failed.

**Comment by vvakame** [comment]
see `types-2.0` branch.

**Comment by jonnystoten** [comment]
OK, I'll recreate this from the correct branch.

**Pull request closed without merging**
