### PR TITLE
@types/jsdom Reference lib "dom"

### PR DESCRIPTION
**Pull request by BassT**
Currently lib "dom" is required for compilation.

However, including "dom" in lib can cause some opaque bugs on a server.

For example, the TS compiler won't complain when using `fetch` without something like `import fetch from "node-fetch"` or using `URL` without `import { URL } from "url"`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by BassT** [comment]
I just became aware that these declarations use typescript@2.2.

`/// <reference lib="dom" />` is new in typescript@3.0.

Are there any plans to update? 
Otherwise this pull request is obsolete.

**Comment by wolfy1339** [comment]
You could just copy the required parts of the dom library and include the in the source

**Comment by leonard-thieu** [comment]
I would use `typesVersions` for this change.

**Comment by BassT** [comment]
> I would use `typesVersions` for this change.

Sounds like the right idea to keep backward compatibility.

Unfortunately, I couldn't figure out how to set it up based on [3.1 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html).

**Comment by leonard-thieu** [comment]
I believe the steps are:

* Create a `ts3.1` directory.
* Copy the current definitions and test into the `ts3.1` directory.
* Create a `package.json` file with the following contents.
```jsonc
{
    "private": true,
    "types": "index",
    "typesVersions": {
        ">=3.1.0-0": {
            "*": [
                "ts3.1/*"
            ]
        }
    }
} 
```
* In `ts3.1/tsconfig.json`, change `baseUrl` and `typeRoots` to `"../../"`.
* In `ts3.1/index.d.ts`, remove the DefinitelyTyped header.
* Run tests to verify everything is in order.

---

#### Examples

* #30148
* #30477

**Comment by BassT** [comment]
@leonard-thieu The tests yield the following error:

```
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts:1:1
ERROR: 1:1    expect                           Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts' present in 3.2.0-dev.20181117, but did not find it in ts@3.0.
```

I'm not sure what to do about this.
Did you encouter error like this before?

**Comment by leonard-thieu** [comment]
> @leonard-thieu The tests yield the following error:
> 
> ```
> /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts:1:1
> ERROR: 1:1    expect                           Program source files differ between TypeScript versions. This may be a dtslint bug.
> Expected to find a file '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts' present in 3.2.0-dev.20181117, but did not find it in ts@3.0.
> ```
> I'm not sure what to do about this.
> Did you encouter error like this before?

I haven't seen that one before.

@RyanCavanaugh @andy-ms any ideas?

**Comment by leonard-thieu** [comment]
Related https://github.com/Microsoft/dtslint/issues/160.

**Comment by leonard-thieu** [comment]
@sandersn is this a dtslint issue?

**Review by leonard-thieu — APPROVED** [review]

**Comment by Flarna** [comment]
It seems like this PR and maybe a change in dtslint is causing CI fails. See e.g. #31709 and #31985

```
Error in jsdom
Error: Expected compilerOptions["baseUrl"] === "../"
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
    at <anonymous>
Error: The following packages had errors: jsdom
    at doRunTests (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:131:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by weswigham** [comment]
@sandersn looks like a dtslint check isn't handling typesVersions stuff well?

**Pull request merged**
