### PR TITLE
thunderbird-webext-browser: update of definitions to API version Thunderbird 127.0 

### PR DESCRIPTION
**Pull request by JimDanner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://gist.github.com/JimDanner/c3903b6eb000fa93b73070804dfaa76c>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/thunderbird-webext-browser/index.d.ts
1. .github/workflows/search-commit.yml
1. .github/workflows/test-workflows.yml

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d4484f8782f727cab9577f0b874cf19c19693ccb
</p>

**Review by iisaduan — CHANGES_REQUESTED** [review]
The github workflow test files are not supposed to be included in the API update?

**Comment by JimDanner** [comment]
> The github workflow test files are not supposed to be included in the API update?

Are you asking me whether they are supposed to be included, or are you telling me that they shouldn't be while I have somehow included them? The API update is completely reflected in changes to `index.d.ts`, which is the only file that is used to make API information available to users.

**Comment by iisaduan** [comment]
Yes, I was trying to accomplish both "did you intend to include the workflow files?", and "you should remove the workflow files from a PR that is only trying to update the types for a package" in the same sentence. Apologies for the miscommunication.

For PRs that are only updating types, please remove everything unrelated to the type update, such as the `.yml` files here. Though your changes to `index.d.ts` include all of your type updates, extraneous files in the PR will also be merged to DT (and we would like to not have unnecessary files).

**Review by iisaduan — APPROVED** [review]
LGTM, thanks!

**Comment by JimDanner** [comment]
Ready to merge

**Pull request merged**
