### PR TITLE
IModalServiceInstance missing closed promise

### PR DESCRIPTION
**Pull request by ritter**
Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.
  url: https://github.com/angular-ui/bootstrap/tree/master/src/modal/docs

added missing closed promise to IModalServiceInstance

### CODE REVIEW

**Comment by xt0rted** [comment]
There should be a reference to this in the tests. I'm also not sure why there's a merge.

**Comment by ritter** [comment]
There is a merge simply because I merged it to my fork first.
As for the test, I'm not sure what you want me to do, if anything is needed.

**Comment by xt0rted** [comment]
There's implementations of most of the features in the test file just to ensure the definition is setup correctly. The `opened` promise can be seen here [angular-ui-bootstrap-tests.ts#L176](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d448c0a3152e8871521848c5c2c61ab4e2a2cc9/angular-ui-bootstrap/angular-ui-bootstrap-tests.ts#L176)

**Comment by ritter** [comment]
I've committed the changes to add the test for the closed promise, let me
know if you need anything else.

Thanks much.

Regards,

**Comment by xt0rted** [comment]
looks good to me 👍

**Pull request merged**
