### PR TITLE
sql-tagged-template-literal: new package

### PR DESCRIPTION
**Pull request by yoursunny**
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by yoursunny** [comment]
@TehShrike @Artskydj
I hope you can review this typing.

**Comment by ArtskydJ** [comment]
Looks good to me.

I wonder if `queryParts` should be of type [`TemplateStringsArray`](https://github.com/microsoft/TypeScript/blob/e89d42d373a570f12510429e13ec45a9eccd9ed0/src/lib/es5.d.ts#L603)?  I'm not sure it would make any difference.  There could be good reasons to use `readonly string[]` instead.

**Review by navya9singh — APPROVED** [review]

**Comment by yoursunny** [comment]
> I wonder if `queryParts` should be of type [`TemplateStringsArray`](https://github.com/microsoft/TypeScript/blob/e89d42d373a570f12510429e13ec45a9eccd9ed0/src/lib/es5.d.ts#L603)?

I checked other typings in this repository and found that `TemplateStringsArray` is more suitable, so I made the change.

**Review by navya9singh — APPROVED** [review]

**Comment by yoursunny** [comment]
Ready to merge

**Pull request merged**
