### PR TITLE
port parse5 changes to types-2.0

### PR DESCRIPTION
**Pull request by MeirionHughes**
case 3: port master to types-2.0: 
- update of existing types
- already merged into master see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10695

### CODE REVIEW

**Comment by MeirionHughes** [comment]
Looks like it failed on other modules, but no error for parse5. 

1 hour build... O.o

**Comment by paulvanbrenk** [comment]
Kicked of the build again

**Comment by paulvanbrenk** [comment]
Looks like my merge from master into typings-2.0 may have ruined your merge :(

**Comment by MeirionHughes** [comment]
Oh that;s fine; looks like its been ported over... so the porting from master->types-2.0 is automatic, but you need to trigger it?

**Pull request closed without merging**
