### PR TITLE
[react-color] Updated onChange handlers for custom pickers

### PR DESCRIPTION
**Pull request by MrGVSV**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

Here is an example for why the changes were made. The below references Alpha but the same applies to Hue, and Saturation.

[react-color/src/helpers/alpha.js](https://github.com/casesandberg/react-color/blob/8849f74a7ff96784b7d3cc031b3e415736dcbfe8/src/helpers/alpha.js#L39)
```js
export const calculateChange = (...) => {
...
    return {
        h: hsl.h,
        s: hsl.s,
        l: hsl.l,
        a,
        source: 'rgb',
    }
...
}
```
Which in turn is used by [react-color/src/components/common/Alpha.js](https://github.com/casesandberg/react-color/blob/8849f74a7ff96784b7d3cc031b3e415736dcbfe8/src/components/common/Alpha.js#L13)
```jsx
export class Alpha extends (PureComponent || Component) {
...
    handleChange = (e) => {
      const change = alpha.calculateChange(e, this.props.hsl, this.props.direction, this.props.a, this.container)
      change && typeof this.props.onChange === 'function' && this.props.onChange(change, e)
    }
...
    return (
    ...
        <div
            style={ styles.container }
            ref={ container => this.container = container }
            onMouseDown={ this.handleMouseDown }
            onTouchMove={ this.handleChange }
            onTouchStart={ this.handleChange }
        >
        ...
        </div>
    ...
    )
...
}
```

EditableInput differs in that it returns either a the value or a key-value object depending on whether the label is set.
[react-color/src/components/common/EditableInput.js](https://github.com/casesandberg/react-color/blob/8849f74a7ff96784b7d3cc031b3e415736dcbfe8/src/components/common/EditableInput.js#L79)
```js
export class EditableInput extends (PureComponent || Component) {
...
    setUpdatedValue(value, e) {
        const onChangeValue = this.props.label ? this.getValueObjectWithLabel(value) : value
        this.props.onChange && this.props.onChange(onChangeValue, e)
    
        this.setState({ value })
      }
...
}
```

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by alexandercerutti** [comment]
Hey there! I suggest you reading first the comments of [this PR]https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45733) (which is the previous PR that has been done before yours). This because, these types are a bit a mess and the v3 seems to be still stale. You should use [latest 2.x.x version of typings](https://www.npmjs.com/package/@types/react-color/v/2.17.4) before suggesting edits to the current types (which are v3's).

**Comment by MrGVSV** [comment]
@alexandercerutti Oh man I saw the v2 typings but thought they were older versions for some reason. Good to know! 

So the typings for v2 are what I should have edited then? They were what I was using (along with react-color@2.19.3) and I noticed that the typings didn't match what was being console.logged.

**Comment by alexandercerutti** [comment]
@MrGVSV since you are using react-color@2.19.3, you should check if react-color's v2.17.3 typings are correct for you and reflect the changes you wanted to apply on v3 and, if so, use them. Otherwise, I think you should revert your changes on v3 and edit the v2 types.

I would not touch the v3 types if not needed, since we don't know for how much time v3 will remain stale.

**Comment by MrGVSV** [comment]
Sounds good! I'll test and correct my edits tomorrow. Thanks!

**Pull request closed without merging**
