### PR TITLE
Added missing types for gt, lt, gte, lte to Ramda

### PR DESCRIPTION
**Pull request by Cloud11PL**
Documentation shows that Ramda allows to pass string to gt, lt, gte, lte https://ramdajs.com/docs/#gt 

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by Nicholaiii — APPROVED** [review]
LGTM

**Comment by Nicholaiii** [comment]
Could you actually make an "equal" test for parity?

**Review by Nicholaiii — APPROVED** [review]
Good stuff!

**Review by Nicholaiii — APPROVED** [review]
Semicolons 😅👌

**Comment by Cloud11PL** [comment]
Ready to merge

**Pull request merged**
