### PR TITLE
Updating angular-mocks to 1.5

### PR DESCRIPTION
**Pull request by homesar**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://docs.angularjs.org/api/ngMock/service/$httpBackend .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by vvakame** [comment]
@homesar please resolve conflict.

**Comment by homesar** [comment]
@vvakame Done

**Comment by MarkusKramer** [comment]
Can this be merged please?

I've tested it in my project and it's working well (and solves my problem with missing angular 1.5 type definitions).

**Comment by vvakame** [comment]
oops, sorry!

**Pull request merged**
