### PR TITLE
[node] child_process stdio actually allows "inherit"

### PR DESCRIPTION
**Pull request by thw0rted**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [The current docs](https://nodejs.org/api/child_process.html#child_process_options_stdio) say that "inherit" is not allowed but [they are wrong](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L910) and I'll be submitting a PR there shortly.
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Ref #28069

### CODE REVIEW

**Review by Flarna — APPROVED** [review]

**Comment by thw0rted** [comment]
For those playing along at home, TS@next is still breaking the build.

**Comment by thw0rted** [comment]
Hi, can @Flarna  or somebody re-open this?  Again, the code is not actually broken

**Comment by Flarna** [comment]
@thw0rted Sorry, can't help here as I'm just a user like you - no push rights or similar on this repo.
But usually you should have the rights to re-open your own PRs. It will retrigger CI and if it is green the bot will not close it again instead it will move it into the to be merged list.
But as https://github.com/Microsoft/TypeScript/issues/26521 is still open I'm quite sure that re-opening now will still result in a failed CI again and bot will close it again as last commit is older then 5 days.

**Comment by thw0rted** [comment]
I don't think your linked issue bombed my most recent failed build, but maybe there's new TS@next problems that are breaking other builds?  Ugh, they really need to resolve the types-publisher issue I referenced just before your comment (478) so this stops happening...

**Comment by Flarna** [comment]
The reference issue causes fails in koa-morgan like in #28204 - not sure if it is the same you have seen.
But you are right, once this issue gets fixed the next ones are in pipeline coming from one of the sourced not pre-verified via CI (typescript@next, ts-lint, module dependencies not located in this repo).

**Comment by thw0rted** [comment]
I've definitely had a PR that got merged even though the CI failed, because it was obvious that the failures were due to broken (IMHO poorly-specified...) deps of the test suite, rather than problems in the code being tested.  Is the process for saying "CI broken, merge anyway" still around?  If so, who can make that call, if not the package maintainer (i.e. you)?  Did it go away?  If so, how are any changes going to get through when CI keeps breaking?

**Pull request merged**
