### PR TITLE
Attribute.Control should inherit Standard control to inherit getDisabled and setDisabled properties

### PR DESCRIPTION
**Pull request by pavansarma93**
Updated Attributes interface to implement latest interface instead of deprecated control to consume getDisabled and setDisabled properties which are methods of Attributes

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by filcole** [comment]
Which controls give this issue?

**Comment by pavansarma93** [comment]
@filcole We can get control from attribute as well. For eg. see below script for reference. There it was failing to detect as control doesn't have method available in TS.

image

**Comment by daryllabar** [comment]
I think this PR should get rejected. setDisabled is not available on all controls (https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/setdisabled) I believe this is why the standard control type was created.

**Comment by pavansarma93** [comment]
@filcole : can you take some time to review the PR and approve

**Review by daryllabar — CHANGES_REQUESTED** [review]
I believe this PR should be rejected.  Not all controls implement the Get/Set Disabled properties.

**Comment by pavansarma93** [comment]
@daryllabar : Yes, that's correct. That's why the change was made in the _interface for Attribute_  only.

and the control was to inherit standardcontrol as it has properties of getdisabled and setdisabled properties rather than the control which doesn't include the same.

image

**Comment by daryllabar** [comment]
Ah, I apologize, so I think I'm understanding a little better, we can't have a control for an attribute that is not disable-able, so there for we can make it that control interface, even though the actual list of controls on the page will remain unchanged.

Is that correct?

**Comment by pavansarma93** [comment]
@daryllabar : Yes correct. The change is only for Attribute interface . The other list of controls will be remained unchanged. This will not affect anything else.

**Review by daryllabar — APPROVED** [review]

**Comment by Power-Maverick** [comment]
Ready to merge - as @daryllabar already approved this 👍

**Pull request merged**
