### PR TITLE
Fix: make a MockOptions interface in types/jest/index.d.ts compatible with mock options coming from @jest/globals

### PR DESCRIPTION
**Pull request by Tharos**
In our project, we use both `@types/jest` and `@jest/globals`.

When the `exactOptionalPropertyTypes` TS compiler option is enabled, the project cannot be compiled due to a discrepancy between the mock options definitions in `@types/jest` and `@jest/globals`.

In `@types/jest`, the definition is as follows:

```
interface MockOptions {
    virtual?: boolean | undefined;
}
```
(See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L431C15-L433)

However, in `@jest/globals`, the definition is:

```
options?: {virtual?: boolean}
```

(See: https://github.com/jestjs/jest/blob/main/packages/jest-environment/src/index.ts#L140)

The issue can be reproduced in this minimal repository: https://github.com/Tharos/types-jest-bug

The error message follows:

```
node_modules/@jest/environment/build/index.d.ts:401:26 - error TS2430: Interface 'JestImportMeta' incorrectly extends interface 'ImportMeta'.
  The types of 'jest.doMock' are incompatible between these types.
    Type '<T = unknown>(moduleName: string, moduleFactory?: (() => T) | undefined, options?: { virtual?: boolean; } | undefined) => Jest' is not assignable to type '<T = unknown>(moduleName: string, factory?: (() => T) | undefined, options?: MockOptions | undefined) => typeof jest'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'MockOptions | undefined' is not assignable to type '{ virtual?: boolean; } | undefined'.
          Type 'MockOptions' is not assignable to type '{ virtual?: boolean; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
            Types of property 'virtual' are incompatible.
              Type 'boolean | undefined' is not assignable to type 'boolean'.
                Type 'undefined' is not assignable to type 'boolean'.

401 export declare interface JestImportMeta extends ImportMeta {
```

------

This pull request resolves the compatibility issue between the two definitions.

### CODE REVIEW

**Review by jwbay — APPROVED** [review]

**Review by mrazauskas — APPROVED** [review]

**Review by domdomegg — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]
Approved, but I suggest adding a comment noting the lack of `| undefined` is intentional, since best practice is _usually_ the opposite, and someone might come along and add it back, trying to be helpful for `exactOptionalPropertyTypes` users.

**Comment by mrazauskas** [comment]
> Approved, but I suggest adding a comment noting the lack of `| undefined` is intentional, since best practice is _usually_ the opposite, and someone might come along and add it back, trying to be helpful for `exactOptionalPropertyTypes` users.

Ah.. Right! What if `| undefined` would be added in Jest types? Looking at this explanation, I think it is totally acceptable.

**Comment by Tharos** [comment]
(Just let me know, guys, if there’s something I could help with. 🙂 I can either add the comment here or send a pull request to add `| undefined` to Jest types – if `@jest/globals` is what you mean. No problem.)

**Comment by andrewbranch** [comment]
It seems like it would be ideal for @jest/globals to take an update, if they're open to it. I leave it up to you and the reviewers here.

**Comment by mrazauskas** [comment]
Hm.. In the other hand, typings of `@jest/globals` consistently do not add `| undefined`. I looked through `@types/jest` and it looks like the only `| undefined` is the one removed in this PR.

So perhaps it is better to merge this PR for consistency?

**Comment by Tharos** [comment]
I believe that `@jest/globals` should be the source of truth here. That’s why I kept the change and added a comment to clarify that the omission of `| undefined` is intentional to maintain compatibility with `@jest/globals`, as advised.

If you all agree, I think this can be merged.

**Review by mrazauskas — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by Tharos** [comment]
Ready to merge

**Pull request merged**
