### PR TITLE
[passport] - consitent typing of options passed to authorize & authenticate

### PR DESCRIPTION
**Pull request by kstiehl**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by sandersn** [comment]
@horiuchi @enaeseth @theigor @tlaziuk @danielpa9708 This seems like an innocuous change but I'd like to get some domain experts to look at it. Do any of you have time?

**Comment by danielpa9708** [comment]
I haven't used passport in a while, but still have a question. Why are you updating the version for passport to `1.0` ?, in https://www.npmjs.com/package/passport the version is `0.4`

**Comment by kstiehl** [comment]
@danielpa9708 oopsie. Guess I mixed up something. Will correct that, as soon as I arrive in my hotel. Thanks for pointing that out 🍻

**Comment by kstiehl** [comment]
@danielpa9708 fix in #31731

**Pull request merged**
