### PR TITLE
[chartist] Remove types for version 1.0.0

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Related discussion: #62145

chartist bundles its own types as of version 1.0.0

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test chartist`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by mtgibbs** [comment]
I've never been a part of EOL'ing typings, but for anyone using legacy chartist, should we not delete these typings yet?

**Comment by MysteryBlokHed** [comment]
I think it's common on DT to remove types as soon as they start bundling their own definitions: <https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package>

**Comment by mtgibbs** [comment]
Okay!  As long as they're tagged and people are able to use it for older projects!  Thanks!

**Review by mtgibbs — APPROVED** [review]

**Review by sheetalkamat — APPROVED** [review]

**Comment by MysteryBlokHed** [comment]
Ready to merge

**Pull request merged**
