### PR TITLE
@ember routing default Model to unknown instead of any

### PR DESCRIPTION
**Pull request by mongoose700**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Not sure to what degree the template applies to this change.

### CODE REVIEW

**Comment by sandersn** [comment]
A change in the TS nightly makes DT parsing run out of memory. I pinned Typescript to a version before the change while I investigate.

**Comment by chriskrycho** [comment]
@sandersn what's the word here? Any change on current TS nightlies?

**Comment by sandersn** [comment]
Yep, CI is healthy and checking against TS nightly again.

**Comment by chriskrycho** [comment]
Thanks @sandersn! @mongoose700 mind getting this up to date and ready to go?

**Comment by mongoose700** [comment]
What changes do I need to make? It's passed on CI, but still has the "The CI Failed" label for some reason.

**Comment by sandersn** [comment]
Uhhhh, let's see what happens when I manually remove it. If the bot puts it back then @elibarzilay will probably need to investigate.

**Pull request merged**
