### PR TITLE
plotly.js: Move trace modules to the correct location, satisfy `interface TraceModule`

### PR DESCRIPTION
**Pull request by andersk**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/plotly/plotly.js/tree/v2.35.2/lib>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/plotly.js/test/register-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3e9556dedf92755c5292ae47ac33f95004595cf2
</p>

**Review by brammitch — CHANGES_REQUESTED** [review]
There's an ESLint error for `register-tests.ts`:
```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/types/plotly.js/test/register-tests.ts` using `parserOptions.project`: <tsconfigRootDir>/types/plotly.js/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```
Can you update `tsconfig.json` with the new file, `register-tests.ts`? Otherwise, this change looks good to me. Thanks!

**Review by brammitch — APPROVED** [review]
LGTM!

**Comment by andersk** [comment]
Ready to merge

**Pull request merged**
