### PR TITLE
[charcodes] Added new definitions

### PR DESCRIPTION
**Pull request by dylanarmstrong**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Added [charcodes](https://github.com/xtuc/charcodes/tree/master/packages/charcodes)

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@dylanarmstrong I think this is only NodeJS module, without support for global script usage or UMD namespacing:
https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html

**Comment by dylanarmstrong** [comment]
I'm not sure what that means exactly for this. I'm using the types and they're working correctly. Is it the test file that needs to be updated? I had a different test file that had:

```
import charcodes from 'charcodes';

charcodes.backSpace; // $ExpectType 8
// ...
```

At the top of the file before changing to the global / cjs tests that I saw the example project base64js using. Do I need to change over to that style of test?

**Comment by peterblazejewicz** [comment]
you're using modules in your  sample code.  Export as namespace is not required for a source like original JS module (which is a module, CJS + ESM). So export as namespace is not required here, it would allow to use this module in global sript (no module usage), like:
```ts
window.charcodes.backSpace;
```
which is probably completely wrong, isn't it?

**Comment by dylanarmstrong** [comment]
Thanks @peterblazejewicz, you're right. I will update this.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@dylanarmstrong thx!

**Comment by dylanarmstrong** [comment]
Ready to merge

**Pull request merged**
