### PR TITLE
sequelize: Provides its own types

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This will deprecate `@types/sequelize` in favor of just `sequelize`. CC @samuelneff, @codeanimal, @drinchev, @babolivier, @kukoo1, @oktapodia, @morpheusxaut, @TitaneBoy, @zjy01, @nidzov, @Raigen, @todd, @nrschultz, @thomas-b, @Antoine38660, @smff, @truongkhanhduy95, @emmanuelgautier, @dancrumb, @lalayueh, @rohitsud
WARNING: other packages depend on this!

### CODE REVIEW

**Review by oktapodia — CHANGES_REQUESTED** [review]
This will break the compatibility for sequelize v3 and v4, better to ask the maintainers of sequelize before dropping this, @papb @sushantdhiman any thoughts?

**Comment by papb** [comment]
Hello, thanks for pinging, I am not sure about this, I prefer to wait for opinions by @sushantdhiman and @SimonSchick

**Comment by SimonSchick** [comment]
Kinda torn on this one, the typings here are pretty bad/outdated but commonly used, I'm 100% in favor of deleting v3 tho 😛

**Comment by todd** [comment]
Sequelize provides its own types for V5, but not for V3/V4. Can't speak for others, but we're still actively using these and having the ability to continue to make changes would be valuable.

**Pull request closed without merging**
