### PR TITLE
feat(commander): improve typyings and fix lint issues

### PR DESCRIPTION
**Pull request by alan-agius4**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://tj.github.io/commander.js>>
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by alan-agius4** [comment]
Seems like the package was not released.

**Comment by alan-agius4** [comment]
Version is stIll 2.3.31
https://www.npmjs.com/package/@types/commander

**Comment by Jason3S** [comment]
This commit broke the following way of importing commander:

```typescript
import * as program from 'commander';
...
interface Options extends program.IExportedCommand {}
```

The typescript compiler now generates the following error:
```
error TS2503: Cannot find namespace 'program'.
```

**Comment by alan-agius4** [comment]
@Jason3S ill have a look and submit a fix

**Comment by alan-agius4** [comment]
shoiuld be fixed in this PR #16060

**Comment by Jason3S** [comment]
wow, that was fast!

**Pull request merged**
