### PR TITLE
Add initial type definitions for ProtoBuf.js

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
This is an initial type definition file for the ProtoBuf.js project. Added a few core functions and types and tests for them.

This was requested in https://github.com/borisyankov/DefinitelyTyped/issues/2754

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
Finally the PR builds and is ready for merging.

**Comment by vvakame** [comment]
@panuhorsmalahti thank you your contributions. please rename protobuf to protobufjs.
definitelytyped.org/guides/contributing.html#naming-the-file
https://www.npmjs.com/package/protobufjs

**Comment by panuhorsmalahti** [comment]
Renamed to protobufjs.

**Comment by vvakame** [comment]
@panuhorsmalahti thanks mate!

**Comment by ttowncompiled** [comment]
Wanted to let you know that I'm going to be working on completing protobuf.d.ts over the course of the next week. Hopefully, will have it done by Monday.

For this though, it would be really nice to be able to include PR - #4569 in the definitions.

**Comment by ttowncompiled** [comment]
I've tackled most of protobufjs. I still have one more library to go through and I need to add tests.

You can check out my progress here though:
https://github.com/ttowncompiled/DefinitelyTyped/tree/protobufjs

**Comment by ttowncompiled** [comment]
I have 90%, if not more, of protobufjs. I'm going to write the tests, and then submit the PR.

**Comment by ttowncompiled** [comment]
Finished the tests for protobuf.d.ts. Check it out here:
https://github.com/ttowncompiled/DefinitelyTyped/tree/protobufjs

**Pull request merged**
