### PR TITLE
Updates declaration of jquery-mockjax to the v2.3 npm release (and github commit)

### PR DESCRIPTION
**Pull request by hasaki**
Also adds tests for two features added in the release.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jakerella/jquery-mockjax
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Oddly v2.3 isn't available as a github release but it is up on npm and the master branch has a commit saying 2.3 is available.  I went through the documentation and added the missing settings and new `$.mockjax` overload I found.

### CODE REVIEW

**Comment by vladeck** [comment]
@hasaki @laszlojakab I'm out of jQuery-related loop for a long time.
@laszlojakab @jakerella Do you have any input relating this PR?

**Comment by hasaki** [comment]
Hi Jordan, thanks for the feedback!  I think with the `logLevelMethods` array being able to change which properties to reference, I'm not sure I can create a strongly typed definition for the `logger` property.  

The [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes) section suggestions not declaring a type as accepting `any` and another type, but maybe this is an exception that makes sense.  As the `any` type is only used for a corner case.

There are several open TypeScript issues that would allow some level of indirection on the names, but from what I'm seeing it would need to be hard coded in the declaration file or the user would have to also implement some other interface for it to work.

I've posted on StackOverflow to see if the TS gurus know if/how the more advanced method could be declared: https://stackoverflow.com/questions/50692875/how-to-declare-a-typescript-interface-where-properties-names-are-values-in-an-ar

**Comment by vladeck** [comment]
I'm not sure it is possible to constraint something to values of array by just using the type system. However, while not ideal, you can constraint that code somewhat, for example:

```ts
interface ILogger {
    warn: Function;
    log: Function;
    // Any other required functions
    // ...
    [key: string]: Function;
}

interface ISettings {
    logLevelMethods: string[];
    logger: ILogger;
}
```

And then others can use it as:

```ts
const s: ISettings = {
    logLevelMethods: ["anotherMethod"],
    logger: {
        warn: () => {},
        log: () => {},
        anotherMethod: () => {}
    }
}
```

There is nothing constraining that there must be `anotherMethod` function in `logger` property type, but it does, at least, provide that there must be required functions (`warn`, `log`, ...) If they are optional, `?` can be used, or even something like:

```ts
interface ILogger {
    warn?: Function;
    log?: Function;
    // Any other "standard" functions
    // ...
}

interface IOtherLogger {
    [key: string]: Function;
}

interface ISettings {
    logLevelMethods: string[];
    logger: ILogger | IOtherLogger;
}
```

Just throwing some ideas out there...

**Comment by hasaki** [comment]
Oh, I like that; I hadn't thought about putting a `[key: string]: Function` signature on the logger object.  I'll take that approach.  I also have a better definition for the logging functions.  

I'll try to get a new commit added later today.

**Comment by jakerella** [comment]
LGTM

**Review by vladimir-djokic — APPROVED** [review]
Approved based on feedback from Jordan Kasper.

**Pull request merged**
