### PR TITLE
Update lodash _.curry and _.curryRight

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors(@bczengel @chrootsu). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by vvakame** [comment]
@tkqubo please resolve conflict.

**Comment by tkqubo** [comment]
@vvakame OK I resolved the conflict and fix some in reviews
@chrootsu Thanks for reviewing!

**Comment by chrootsu** [comment]
@vvakame :+1:
@tkqubo Thanks for your contribution ^_^

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
