### PR TITLE
Fixed typos and added a locale option - @types/react-native-modern-datepicker 1.0.0

### PR DESCRIPTION
**Pull request by CarrionB**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.

If changing an existing definition:

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by Ankan002 — APPROVED** [review]
Thanks for contributions and fixing the typos...✌️✌️

**Comment by Ankan002** [comment]
@CarrionB Please add the changed test cases in the test file so that owner can merge it. @peterblazejewicz Please review this PR, as it is causing some serious issue due to some typos made by me. 🙏🙏

**Review by Ankan002 — APPROVED** [review]
Looks good to me. Thanks for rectifying  the typos

**Comment by CarrionB** [comment]
Ready to merge

**Pull request merged**
