### PR TITLE
Rewrite WebRTC RTCPeerConnection definitions

### PR DESCRIPTION
**Pull request by dbrgn**
The WebRTC specification moves fast, and these definitions were very outdated. They also relied on enums sometimes because at the time of writing string union types (`type foo = 'a' | 'b'`) didn't exist yet. There was also a lot of deprecated API still present.

I used the [specification](https://www.w3.org/TR/webrtc/) IDL to rewrite all definitions in `RTCPeerConnection.d.ts`.

In the end I had to comment out some of the attributes because they clashed with types defined in `lib.es6.d.ts`. Not sure what the best approach would be here.

I also removed vendor specific prefixes. I think the correct approach when doing WebRTC is to use [adapter.js](https://github.com/webrtc/adapter). Otherwise people can add their own vendor-prefixed definitions if they wish.

Legacy API (with callbacks instead of promises) is not (yet) implemented. Does someone think this is important?

@groege @vvkame @martinduparc @bemasc @nakakura @iislucas @nestalk @smithkl42

---

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes: https://www.w3.org/TR/webrtc/
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by zhengbli** [comment]
Thank you for your contribution.

Can you please fix the failing Travis CI tests and update the PR?

**Comment by zhengbli** [comment]
Thank you for your contribution.

Can you please fix the failing Travis CI tests and update the PR?

**Comment by dbrgn** [comment]
Yes, I started with fixing it but didn't finish yet so far.

The thing is that on the main branch everything is compiled with Typescript 1.8, right? I'm using some Typescript 2 syntax like `readonly`... Should I create a PR against `types-2.0` directly instead?

**Comment by zhengbli** [comment]
Yes you can. New work should generally be done on the `types-2.0` branch. If you want your changes to be available to `typings` users, then you may edit `master` instead.

**Comment by dbrgn** [comment]
Alright, this can be closed in favor of #12140.

**Pull request closed without merging**
