### PR TITLE
added isReady: boolean handler

### PR DESCRIPTION
**Pull request by jzapantis**
I was trying to use this type with a tutorial and found that the typing was not set for the isReady var. So I added it.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by jzapantis** [comment]
this is my first PR, please let me know if there is something wrong.

**Comment by DanielRosenwasser** [comment]
This looks fine; can you just add a test file (`amcharts-tests.ts`) where you set the `isReady` property. It will probably look something like this:

```ts
/// <reference types="amcharts" />

AmCharts.isReady = true;
```

You'll also need to add `amcharts-tests.ts` to your `tsconfig.json`'s `files` property.

**Comment by jzapantis** [comment]
OK I will make the -test.ts file

**Comment by bowdenk7** [comment]
Thanks for your contribution. This PR has unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
