### PR TITLE
async: Rename `AsyncIterator` to `AsyncEachCallback`

### LINKED ISSUE #16980: @types/async definition of AsyncIterator<T, E> clashes with Typescript 2.3's AsyncIterator<T> declaration
- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @kern0 @penryn @fenying @pascalmartin 

Typescript 2.3 (`lib.esnext.asynciterable.d.ts`) defines an AsyncIterator as 
```
interface AsyncIterator<T> {
    next(value?: any): Promise<IteratorResult<T>>;
    return?(value?: any): Promise<IteratorResult<T>>;
    throw?(e?: any): Promise<IteratorResult<T>>;
}
```

types/async is defining an AsyncIterator as
```
interface AsyncIterator<T, E> { (item: T, callback: ErrorCallback<E>): void; }
```

This causes an `error TS2428: All declarations of 'AsyncIterator' must have identical type parameters.` when trying to use Typescript 2.3.4 with the `"lib": ["esnext"]` option in your tsconfig.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #16980

### CODE REVIEW

**Comment by fenying** [comment]
I think this could be okay. Though it may break some projects depending on this library, anyway, the conflict of global definition has to be solved. And this change may be the minimal cost.

BTW, I don't know if there is any else better choice, but defining the async library globally, is really a pollution to the context. Shall we do something to solve it completely?

@Penryn How do you think about it?

**Comment by andy-ms** [comment]
@fenying I've tried that out in #19870 as an alternative to this PR.

**Comment by Penryn** [comment]
@fenying @andy-ms As much as it pains me to break everyone's projects I think it's time we fixed Async once and for all. I vote :-1: for this solution and would prefer #19870 instead. I've commented there.

Thanks so much both of you for getting this discussion going again and doing the actual work I probably should have done ages ago.

**Comment by andy-ms** [comment]
Closing in favor of  #19870.

**Pull request closed without merging**
