### PR TITLE
Make bsStyle in Buttons nullable to avoid setting btn-default class

### PR DESCRIPTION
**Pull request by MathieuLarocque**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://react-bootstrap.github.io/components/buttons/>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by aaronbeall** [comment]
I'm not sure I understand why we need `null` when the prop is already marked optional with `?`. I know that `null != undefined` but a *lot* of props are marked optional yet not nullable. Is there special rationale for the `bsStyle` case?

**Comment by vitosamson** [comment]
`Button` is using `btn-default` as `defaultProp.bsStyle`. If the prop is undefined then it'll use the default, but if the prop is `null` then it won't use the default. So if you don't want to apply the `btn-default` classname to the button, you need to pass `null` rather than leaving it undefined.

This LGTM but it should probably apply to any other components that take the `bsStyle` prop as well.

**Comment by aaronbeall** [comment]
Thanks @vitosamson that makes sense now!

**Review by aaronbeall — APPROVED** [review]

**Comment by MathieuLarocque** [comment]
@aaronbeall Thank you! Sorry for not writing a description.

**Pull request merged**
