### PR TITLE
Added @disabled testhook

### PR DESCRIPTION
**Pull request by ClaytonAstrom**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nightwatchjs/nightwatch-docs/blob/master/guide/running-tests/disabling-tests.md
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by Schlesiger** [comment]
Whoops sorry I received the first email but then forgot.

**Comment by Schlesiger** [comment]
Whoops sorry I received the first email but then forgot.

**Review by wallzero — APPROVED** [review]
Whoops sorry I received the notification email but then forgot. Looks good!

**Review by wallzero — APPROVED** [review]
Whoops sorry I received the notification email but then forgot. Looks good!

**Pull request merged**
