### PR TITLE
@types/webdatarocks added

### PR DESCRIPTION
**Pull request by webdatarocksteam**
new type definition for WebDataRocks package

### CODE REVIEW

**Comment by webdatarocksteam** [comment]
Hello,
Is there anything needed from us here @sandersn?
Is everything okay?

**Comment by sandersn** [comment]
@webdatarocksteam You are on the board in the Review column at https://github.com/DefinitelyTyped/DefinitelyTyped/projects/4 but it looks like we've got a bit behind this week so it might take a while to catch up. We'll definitely look at this PR eventually.

**Comment by webdatarocksteam** [comment]
Thank you for keeping us updated @sandersn.
Regards,
WebDataRocks Team

**Comment by orta** [comment]
I'm a little confused, it seems like you are the team who own the dependency being added here. Why not add them to the library and then they are in sync with your versions?

**Comment by webdatarocksteam** [comment]
Hello @orta 
Thank you for giving us a hint.
We have moved types to the original package.
Closing pull request.
Regards,
WebDataRocks Team

**Pull request closed without merging**
