### PR TITLE
fix(mongoose): remove DT

### LINKED ISSUE #53407: Remove `@types/mongoose` dependency from `@types/mongoose-geojson-schema`
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped channel in the TypeScript Community Discord](https://discord.gg/typescript).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bondz

@bondz - I'm not sure if this is in your control or not. I looked at your [original PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21028) but I can't see any reference to dependencies on `@types/mongoose`. It would be good to add this as an optional peerdep if possible.

For anyone who is having mongoose type conflicts relating to this:

1. [`Mongoose@5.11.0` now includes its own types that are incompatible with `@types/mongoose@5.10.5`](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49950). This means you either need to pin your version to `5.10.9` in pkg json or remove `@types/mongoose` as a dependency.
2. Because `@types/mongoose-geojson-schema` has a dependency on `@types/mongoose` you'll experience errors. The way around this is to remove `@types/mongoose-geojson-schema` and copy the contents of [`@types/mongoose-geojson-schema` index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose-geojson-schema/index.d.ts) to a `global.d.ts` inside your `src`

### PR DESCRIPTION
**Pull request by peterblazejewicz**
5.11.0 introduced types:

https://github.com/Automattic/mongoose/tree/5.11.0
https://thecodebarbarian.com/working-with-mongoose-in-typescript.html

Thanks!

/cc @jamiehaywood

Fixes #53407

Note: this is not expected to merge easily due to wide usage of `@types/mongoose`, new version introudction
with `.d.ts` distributed natively, etc.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
all: to be done sequentally, this shoudl be merged as last one, after fixing deps and pre 5.10 version, thx!

**Comment by peterblazejewicz** [comment]
done: `@types/mongoose` and `mongoose` will be now allowed to use in order to fix dependencies matrix, thx! TBC

**Comment by jamiehaywood** [comment]
@peterblazejewicz - awesome job, thanks very much for raising this PR! Having looked through your code I realise I probably could have done it 😅🤦🏻‍♂️ but I've learnt something new 🙂. Have a great week!

**Review by jamiehaywood — APPROVED** [review]

**Review by jamiehaywood — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Pull request merged**
