### PR TITLE
[frac] Add frac typing

### PR DESCRIPTION
**Pull request by azerella**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

The type defs for this package already existed and were created by the package author: https://github.com/SheetJS/frac/tree/master/types but never seemed to be published. I believe these types should be available from the DefinitelyTyped database for people to easily use.

### CODE REVIEW

**Comment by SheetJSDev** [comment]
The definitions are included in the module already.  If it makes sense to also include them in DT, consider this a +1 from the module authors.

**Comment by adamzerella** [comment]
> The definitions are included in the module already. If it makes sense to also include them in DT, consider this a +1 from the module authors.

@SheetJSDev Perhaps I should update this PR to add the module to the `notNeededPackages.json` list?

**Comment by SheetJSDev** [comment]
@adamzerella [the `notNeedPackages.json` approach is what `xlsx` uses](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e8422e44bc127d7f7b57012ac26d9a26d38dec0/notNeededPackages.json#L1845), so maybe that approach is best.  Since you proposed the PR, feel free to take the approach that makes the most sense to you.

**Comment by adamzerella** [comment]
After speaking with @SheetJSDev, I'm closing this PR as the types were never registered with DS and thus dont need to be on the `notNeededPackages.json`

**Pull request closed without merging**
