### PR TITLE
Clean up lodash modules

### PR DESCRIPTION
**Pull request by ghost**
Same effect, but now generated by `generate-modules.ts`.
We don't need the headers on all of the submodules, just on the main `index.d.ts`.

### CODE REVIEW

**Comment by andy-ms** [comment]
Update: No longer generating `modules.d.ts` since #13051 removes it.

**Comment by andy-ms** [comment]
CC @TonyPythoneer since he's been poking around lodash lately

**Comment by TonyPythoneer** [comment]
Hi @andy-ms, what do I need to notice?

**Comment by andy-ms** [comment]
Not really, this is just a change you might be interested in. See also #13158.

**Comment by mvestergaard** [comment]
I seem to be getting these types of errors with `4.14.43`, it works with `4.14.42`:
`Module '@types/lodash/find/index' resolves to a non-module entity and cannot be imported using this construct.'

On code: `import * as _find from 'lodash/find';`

TS 2.1.4

**Comment by andy-ms** [comment]
@mvestergaard It's strange that that was allowed before. `find` is indeed a non-module entity: it's a single function. So, you should use `import find = require("lodash/find")`.

**Comment by mvestergaard** [comment]
@andy-ms Blegh, I find that kind of ugly honestly. I would like to use the same import syntax consistently.
That actually makes me inclined to just do `import * as _ from 'lodash'` and then rely on babel/webpack plugins to transform it into more optimal imports.
The goal being to not include everything from lodash unless needed.

**Comment by andy-ms** [comment]
Filed Microsoft/TypeScript#12768

**Comment by andy-ms** [comment]
You can try using `--allowSyntheticDefaultImports`. This doesn't change the emit so you'll need some way to get it to work at runtime.

**Pull request merged**
