### PR TITLE
[testing-library] create @testing-library/* definitions

### PR DESCRIPTION
**Pull request by alexkrolick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This PR is marked as draft - is it ready for review? Also @weyert did you want to add your name to the header so you get notifications about this package?

**Comment by alexkrolick** [comment]
@johnnyreilly looks like we are ready for the review!

cc @kentcdodds @weyert @eps1lon

**Review by johnnyreilly — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Lovely!

**Comment by johnnyreilly** [comment]
Let's wait until the discussion here has concluded before merging: https://github.com/testing-library/react-testing-library/pull/437#issuecomment-521518931

**Comment by johnnyreilly** [comment]
Ha! It turns out that whilst TypeScript doesn't care about version numbers of packages, the definitely typed tooling does. We'll have to do this in 2 stages (each with a different version number) for a smooth transition. Sorry for time waste there - didn't know definitely typed was doing those checks.

**Comment by weyert** [comment]
John, I will have a look when I am in the office :)

**Comment by johnnyreilly** [comment]
Can we revert the version number change of the last commit please? Then we can merge.

**Comment by weyert** [comment]
Yes, I will work on that in a bit once the build at work is working again 😇

**Comment by alexkrolick** [comment]
reverted the version bump

**Comment by johnnyreilly** [comment]
Great - merged. Automation should publish this sometime tonight I think

**Comment by kylemh** [comment]
How do I install these?

I've tried

```sh
yarn add -D @types/@testing-library/user-event
yarn add -D @types/@testing-library__user-event
yarn add -D @types/testing-library__user-event
yarn add -D @types/testing-library__user-event/v4
```

**Pull request merged**
