### PR TITLE
fix(react): Add key prop to React.Fragment

### PR DESCRIPTION
**Pull request by LucianBuzzo**
This adds the key prop to `React.Fragment`. Without it the following code:
```
 const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

return (
  <div>
    {arr.map((item) => {
      return (
        <Fragment key={item}>
          <div>Item: {item}</div>
        </Fragment>
      );
    })}
  </div>
);
```
will generate a compiler error:
```
Property 'key' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'
```

The `key` is an allowed value for `React.Fragment` - https://react.dev/reference/react/Fragment

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Thank you! Please also add these to the fork for TypeScript 5.0 and below by applying the same changes to the `ts5.0` folder

**Comment by LucianBuzzo** [comment]
@eps1lon Done 👍

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/react/index.d.ts
1. types/react/ts5.0/index.d.ts
1. types/react/test/elementAttributes.tsx
1. types/react/ts5.0/test/elementAttributes.tsx

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 42c8a406b1f1334de0a0678956f812b038333812
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
The added tests pass without any changes to the types. TypeScript always adds `key` to JSX. Could you provide a repro for the compile error you posted?

**Comment by LucianBuzzo** [comment]
@eps1lon Weird - I'll prepare a minimal reproduction, though it sounds like the issue isn't the types here...

**Comment by eps1lon** [comment]
Is the error coming from running `tsc` or from your IDE? WebStorm is a frequent offender where the type errors it reports are not actually coming from `tsc` but whatever they're doing for type-checking.

**Comment by LucianBuzzo** [comment]
In this case it's coming from tsc. I'm getting the same error from my IDE, and our CI pipeline is producing the same error. I'll try and isolate the issue.

**Comment by eps1lon** [comment]
What JSX factory are you using i.e. do you have anything special in `compilerOptions.jsx*`? The JSX namespace declares that `key` is valid on every element via 

```tsx
namespace JSX {
  interface IntrinsicAttributes extends React.Attributes {}
}
```

Maybe you're using a different JSX namespace that is missing this.

**Comment by LucianBuzzo** [comment]
@eps1lon I tracked the issue down to a custom override in the project for the `twin.macro` package - it overrides the `IntrinsicAttributes` class 🤦 :
```
// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string | Element;
    }
  }
}
```
Thanks for your help tracking this down - I'll close this PR. Sorry for all the noise 😄

**Pull request closed without merging**
