### PR TITLE
[@types/ol] Add GeolocationError 

### PR DESCRIPTION
**Pull request by daboudii**
Fix issue: https://github.com/openlayers/openlayers/issues/10905

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://openlayers.org/en/latest/apidoc/module-ol_events_Event-BaseEvent.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Additional information: https://github.com/openlayers/openlayers/issues/10905

### CODE REVIEW

**Review by hanreev — COMMENTED** [review]
`@fires module:ol/events/Event~BaseEvent#event:error` is written clearly in the `Geolocation` class jsdoc, the event object may be `GeolocationError` or other `BaseEvent`.

The `GeolocationError` class is not exported in the original source, so we can not export it in the typescript definition.

**Review by hanreev — COMMENTED** [review]
The `BaseEvent` does not have `code` and `message` property

**Comment by hanreev** [comment]
Definitions for ol v6.3.1 #43793

**Comment by daboudii** [comment]
My bad for the `export`.


> The `BaseEvent` does not have `code` and `message` property

Those properties are added to the `GeolocationError` class like in [`Geolocation.js`](https://github.com/openlayers/openlayers/blob/4bd191755f2a42e716564212917cec2f05ef340a/src/ol/Geolocation.js#L35)



> `@fires module:ol/events/Event~BaseEvent#event:error` is written clearly in the `Geolocation` class jsdoc, the event object may be `GeolocationError` or other `BaseEvent`.

I'm working on this: https://github.com/openlayers/openlayers/issues/10905# 

Sorry, I made this PR before updating the jsdoc

**Review by armanio123 — APPROVED** [review]

**Pull request merged**
