### PR TITLE
feat: update types for prosemirror-dev-tools to 3.0

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/d4rkr00t/prosemirror-dev-tools/releases/tag/v3.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## prosemirror-dev-tools ([<kbd>unpkg</kbd>](https://unpkg.com/browse/prosemirror-dev-tools@latest/))
was missing the following properties:
1. applyDevTools
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6ccaeaeffa6fe63d426ee63692ed37c7b6f28e6d
</p>

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
pinged original author, thx!

**Comment by hedgepigdaniel** [comment]
Ready to merge

**Pull request merged**
