### PR TITLE
R.zip compatible with a tuple array

### PR DESCRIPTION
**Pull request by rwx222**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [url here](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### The problem

Currently this is not posible:
```typescript
type TNameAge = [string, number]; // this is a tuple (not an array) to typescript

const namesAndAges: TNameAge[] = R.zip<string, number>(["John", "Juliet", "Melanie"], [21, 22, 23]);
const namesAndAges2: TNameAge[] = R.zip(["John", "Juliet", "Melanie"])([21, 22, 23]);
```

**TNameAge** is a [typescript tuple](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple), so you can't assign it the result of **R.zip** to a typed tuple, because they aren't compatible. But they should be, because once compiled to javascript there's no difference.

I added some tests to make sure is compatible with both of them, a tuple array (`Array<TNameAge>`), and a common array (`Array<TNames>`), to make sure I'm not breaking the current behavior:
```typescript
type TNameAge = [string, number]; // this is a tuple (not an array) to typescript
const namesAndAges: TNameAge[] = R.zip<string, number>(["John", "Juliet", "Melanie"], [21, 22, 23]);
const namesAndAges2: TNameAge[] = R.zip(["John", "Juliet", "Melanie"])([21, 22, 23]);

type TNames = string[]; // this is an array
const fullNames: TNames[] = R.zip<string, string>(["John", "Juliet", "Melanie"], ["Titor", "Burke", "Cross"]);
const fullNames2: TNames[] = R.zip(["John", "Juliet", "Melanie"])(["Titor", "Burke", "Cross"]);
```

### CODE REVIEW

**Comment by googol** [comment]
Hey! This definitely is a problem. I think it would make more sense to fix the definition of KeyValuePair, which most likely has been defined before the new Tuple goodness was implemented. It is meant to specify the semantics of `[K, V]` in pre-tuple type syntax

**Comment by drebits** [comment]
Hi @googol, please check the [changes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36581/files) again.

You mean something like that, I think It's what you said, because **R.zip** *always will return a tuple array*.
So I reimplemented **KeyValuePair** as **KeyValueTuple** and the tests and everything looks ok.

Do you agree?

By the other hand, I'm not sure when tuples where implemented to typescript, but at least in [version 3.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays) already existed, and as [this type definition says Typescript 3.3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e4a0d4f532b177fc800e8ade7f1b39e9879d4b3c/types/ramda/index.d.ts#L34) I think is ok.

**Review by googol — COMMENTED** [review]
I'd retain the name `KeyValuePair`, since that is used by user code. This way we won't create a breaking change. Otherwise this looks good

**Comment by drebits** [comment]
You're right @googol. I already fixed it.

**Review by googol — APPROVED** [review]
Looks good to me

**Pull request merged**
