### PR TITLE
[node]: fix the first argument of opendir from string to PathLike

### PR DESCRIPTION
**Pull request by gjbkz**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/fs.html#fs_fs_opendir_path_options_callback
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]

**Comment by kei-ito** [comment]
> @kei-ito this should go into all LTS versions, shouldn't? thx!

Yes. this should go into all LTS versions. They were added in v12.12.0, and since that time the first argument has been`string | Buffer | URL`.

- [fs.opendir v12.12.0](https://github.com/nodejs/node/blob/921493e2287aa895679620155b5288b2e1587bfd/doc/api/fs.md#fsopendirpath-options-callback)
- [fs.opendirSync v12.12.0](https://github.com/nodejs/node/blob/921493e2287aa895679620155b5288b2e1587bfd/doc/api/fs.md#fsopendirsyncpath-options)
- [fsPromises.opendir v12.12.0](https://github.com/nodejs/node/blob/921493e2287aa895679620155b5288b2e1587bfd/doc/api/fs.md#fspromisesopendirpath-options)

**Review by LinusU — APPROVED** [review]
Nice 👍 

Would be great to fix v14 and v12 as well, but I personally don't think we should block merging on that...

**Review by LinusU — APPROVED** [review]
Awesome 👍

**Review by peterblazejewicz — APPROVED** [review]

**Comment by kei-ito** [comment]
Ready to merge

**Pull request merged**
