### PR TITLE
Update types for socket.io-parser

### PR DESCRIPTION
**Pull request by crutchcorn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/socketio/socket.io-parser/releases>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by plantain-00** [comment]
Thanks for your contribution, since you want to upgrade the types from v2 to v3, you should follow this guide: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

**Comment by crutchcorn** [comment]
@plantain-00 Thanks, I don't know how I missed that. I've added the proper steps (I think? I've not upgraded a package with major version before)

**Comment by plantain-00** [comment]
CI fails and `socket.io-parser-tests.ts` missed

**Comment by DanielRosenwasser** [comment]
You'll need to add the appropriate overloads to `on` so that you can have typed callbacks.

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
