### PR TITLE
[@types/cassandra-driver] Update to cassandra-driver 4.1

### LINKED ISSUE #37452: Update @types/cassandra-driver to 4.1 and support the concurrent execution API
- [ X ] I tried using the `@types/cassandra-driver` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Svjard, @pc-jedi, @michal-b-kaminski

The types for cassandra-driver are missing the concurrent execution API. As far as I can tell the types for this library (4.0) were last updated in February and the concurrent execution API was introduced in April (4.1). See https://docs.datastax.com/en/developer/nodejs-driver/4.1/api/module.concurrent.

### PR DESCRIPTION
**Pull request by pc-jedi**
Add `concurrent` namespace.
Fixes #37452 

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/datastax/nodejs-driver/compare/4.0...4.1
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by wwarby** [comment]
I may be reading the PR wrong, but I don’t see the optional “options” parameter to executeConcurrent in the change?

**Comment by pc-jedi** [comment]
@wwarby Thanks for the feedback. If pushed a fix.

**Comment by wwarby** [comment]
Great, thanks @pc-jedi, that looks good to me. It does look as though there were quite a few other changes between 4.0 and 4.1 - I just had a look at the comparison between commits and it's long: https://github.com/datastax/nodejs-driver/compare/4.0...4.1.

The changelog lists these new features for version 4.1, only the first of which is covered by this change. That one is the only one I personally happen to care about because I happen to be using it in my project, but I thought I'd better mention the others.

- [NODEJS-180] - Expose API for parallel execution
- [NODEJS-100] - Provide a way to stream data in
- [NODEJS-491] - Send driver name and driver version in the STARTUP message
- [NODEJS-497] - Add jitter to ExponentialReconnectionPolicy
- [NODEJS-500] - ControlConnection init: Defer host map creation until system tables have been queried
- [NODEJS-501] - Include host_id in host metadata

**Comment by pc-jedi** [comment]
> [NODEJS-100] - Provide a way to stream data in

The Stream part is included with `executeConcurrent`.

> [NODEJS-491] - Send driver name and driver version in the STARTUP message

This does not need to be reflected in d.ts files, as it is just about the client-server communication.

> [NODEJS-497] - Add jitter to ExponentialReconnectionPolicy

I'm not sure about `ExponentialReconnectionPolicy.prototype._addJitter`. Usually functions starting with an underscore are private.

> [NODEJS-500] - ControlConnection init: Defer host map creation until system tables have been queried

Internal behavior.

> [NODEJS-501] - Include host_id in host metadata

Added.

**Pull request merged**
