### PR TITLE
Remove videojs-hotkeys definitions, they're now in the library

### PR DESCRIPTION
**Pull request by Coteh**
https://github.com/ctd1500/videojs-hotkeys/commit/6baf2069ab2ba5ad5db5f4062ccb7e8f91da5ea5

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] ~~[Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).~~ in this case, I ran `npm run test-all` since I'm removing the definitions. No errors.

Select one of these and delete the others:

If removing a declaration:
- [X] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [X] Delete the package's directory.
- [X] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
LGTM but I'll leave the merge timing up to you, if you're trying to get https://github.com/ctd1500/videojs-hotkeys/pull/83 in and released beforehand.

**Comment by Coteh** [comment]
> LGTM but I'll leave the merge timing up to you, if you're trying to get https://github.com/ctd1500/videojs-hotkeys/pull/83 in and released beforehand.

Yes I'm waiting for that PR to go in first so that the type definitions are in sync with what's in here.

Is it possible to get this PR reopened?

**Comment by jakebailey** [comment]
Done.

**Comment by Coteh** [comment]
@jakebailey Sorry, is it possible that this PR could be reopened again? Also, is it possible that the bot auto-closing can be disabled? If not, then I'll decide what to do with the PR by the time it comments again. Thanks.

**Comment by jakebailey** [comment]
It cannot be disabled.

**Comment by jakebailey** [comment]
I'm going to convert this PR to a draft for now, given the upstream types are not getting accepted in short order and the bot wants to keep DT clean.

**Review by diogopxrnextday — APPROVED** [review]

**Comment by Coteh** [comment]
@jakebailey @diogopxrnextday Hey guys, the maintainer of videojs-hotkeys finally merged https://github.com/ctd1500/videojs-hotkeys/pull/83. Seems like DefinitelyTyped has gone through some major changes since I first created the PR, but I still managed to rebase my original commit on top of current master. I have also added another commit to update the notNeeded version and remove the `.npmignore` that was added during this timeframe. Let me know if this is good or if I should open up a new PR, thanks.

**Pull request merged**
