### PR TITLE
Export issue with PrismJS

### PR DESCRIPTION
**Pull request by EdSaleh**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

There was a problem with the importing of this module, due to the lack of export keyword.

### CODE REVIEW

**Comment by eriklieben** [comment]
The current code isn't valid TypeScript i think, or is this new in >2.0?

Are you trying to do this?
``` 
declare module "prismjs" {
  export = Prism;
}
```
Then you are able to use it as:
```
import * as Prism from 'prismjs';
```

Or resolve some other case?

**Comment by medozs** [comment]
@eriklieben The current code didn't work when I was trying to import it. The only way it worked was by doing the changes which was add "export = Prism"; to the file

**Comment by vvakame** [comment]
@medozs this syntax can use after TypeScript 2.0.0. master branch is use TypeScript 1.8.10 still. please this change to `types-2.0` branch.

**Comment by minestarks** [comment]
Closing since this PR has been inactive for a month, and needs to be targeting a different branch

**Pull request closed without merging**
