### PR TITLE
[stellar-sdk] fromOperation and toXDRObject methods for Asset

### PR DESCRIPTION
**Pull request by charlie-wasp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://stellar.github.io/js-stellar-sdk/Asset.html#.fromOperation>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by charlie-wasp** [comment]
Hi! This is my first PR in this repo, will be glad to improve it and make it right!

It's pretty small. I am not sure about tests, though. AFAIK, there are no tests for particular `Asset` class, which this PR is about

**Review by pselden — APPROVED** [review]
LGTM

**Comment by pselden** [comment]
Unfortunately since this is a mono-repo they don't give merge access to package owners. We'll just have to wait for someone with merge access approves it (usually doesn't take more then a couple days).

**Review by Carl-Foster — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
