### PR TITLE
[three] Added OBJLoader, MTLLoader, few fixes in core

### PR DESCRIPTION
**Pull request by Flur**
* add `MTLLoader` [source](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MTLLoader.js)
* add `OBJLoader` [source](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js)
* Geometry `merge` add parameter [merge in source code](https://github.com/mrdoob/three.js/blob/dev/src/core/Geometry.js#L701)
* Add to `Object3D` `onBeforeRender`,  `onAfterRender` [onBefore, onAfter in Object3D](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L104) ,[onBefore, onAfter in WebGLRenderer](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1451)
* `Object3D` `add` method,  delete fixed number of parameters [add in source code](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L307)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [] Increase the version number in the header if appropriate.
- [] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by minestarks** [comment]
authors @gyohk @florentpoujol would you like to review?

**Comment by sandersn** [comment]
@Flur can you add tests?

**Comment by paulvanbrenk** [comment]
Closing as this seems abandoned.

**Comment by Flur** [comment]
@sandersn , created new pull request with test file, see #17862

**Pull request closed without merging**
