### PR TITLE
[Node]: Update http request listeners

### PR DESCRIPTION
**Pull request by vansergen**
## Description

The second attempt to merge #58879.

### Motivation

```ts
import { IncomingMessage, ServerResponse, createServer } from "node:http";
class CustomIncomingMessage extends IncomingMessage {}
class CustomServerResponse extends ServerResponse {}
createServer({
  IncomingMessage: CustomIncomingMessage,
  ServerResponse: CustomServerResponse,
})
  .on("upgrade", (req) => {
    // $ExpectType CustomIncomingMessage
    req;
  })
  .on("request", (req, res) => {
    // $ExpectType CustomIncomingMessage
    req;
    // $ExpectType CustomServerResponse
    res;
    // $ExpectType CustomIncomingMessage
    res.req;
  });
```

### Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
I fear this would be too breaking as a change.

**Comment by vansergen** [comment]
> I fear this would be too breaking as a change.

I believe it could be a breaking change in tests (like it happened in other packages `on-finished`, `stoppable` etc.)

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Need maintainer signoff to see how is the new approach.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by vansergen** [comment]
@sheetalkamat Could you please be more specific on requested changes?

**Review by sheetalkamat — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by vansergen** [comment]
Ready to merge

**Comment by srajiang** [comment]
Hello folks. I see this was just released as part of v18.7.16 - I posted a more fleshed out issue that we're seeing now using this version with these changes included. 

Here's that issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62170

It's breaking in our CI/CD atm, and reverting to a version without the changes resolves the issue.

**Comment by vansergen** [comment]
@mcollina Sure, I could create a new PR that reverse it. But I think we should collect those breaking examples first.

**Comment by vansergen** [comment]
The following

```ts
import * as http from "node:http";
import * as https from "node:https";
const createServerFn: typeof http.createServer | typeof https.createServer = https.createServer;
createServerFn({});
```

does not work now.

**Pull request merged**
