### PR TITLE
Fix issue #6065

### PR DESCRIPTION
**Pull request by iam3yal**
- Update the Runner.run function.
- Update the Server.new function.
- Add new Config interface.
- Add new ConfigFile interface.
- Rename ClientConfig to ClientOptions.

### CODE REVIEW

**Comment by vvakame** [comment]
#6065

**Comment by vvakame** [comment]
*karma/karma.d.ts*

to author(@tkrotoff). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by tkrotoff** [comment]
@eyalsk I'm interested to see an example within karma-tests.ts that uses interface Config/LOG_INFO, LOG_ERROR... (so we don't get regressions in the future), thx

**Comment by vvakame** [comment]
thanks mate!

**Comment by eyalsk** [comment]
@tkrotoff well, it's from their documentation, [logLevel](http://karma-runner.github.io/0.13/config/configuration-file.html).

**Comment by tkrotoff** [comment]
@eyalsk
> well, it's from their documentation

Obviously...
An example is different from a technical documentation. If you introduce something new in a `d.ts` then the syntax should be tested in a `-tests.d.ts`; otherwise how do you know it works? and how do you know it will continue to work in the future?

See commits 21afe00c53a0c9cdf2fb22d57d9f5adce449f45c and e123fee7b41f18f47c03ada42b86bdfe946f976c from PR #6471

**Comment by eyalsk** [comment]
you're right but don't have time to do it atm. :)

**Pull request merged**
