### PR TITLE
Add uploaders types and options to phoenix_live_view

### PR DESCRIPTION
**Pull request by matthewlehner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/phoenixframework/phoenix_live_view
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by pzingg** [comment]
Hello. I am the person who wrote the 0.14 version. Sorry, it took me until today to realize you were submitting an update. I just closed a PR that I opened in response to your finding that this needed updating. Feel free to browse my work and use whatever of it you need. It's now closed: PR #51296

Or the master branch of my fork: https://github.com/pzingg/DefinitelyTyped

Thank you for submitting this. --Peer Zingg

**Review by pzingg — CHANGES_REQUESTED** [review]
Please see comment about adding attributes to the UploadEntry interface to match JS source.

Also, some method signatures and some methods have been added, deleted or modified in other interfaces and namespaces. Please consult closed PR #51296 and consider merging in those changes.

**Comment by pzingg** [comment]
@matthewlehner If the bot closes this PR, I will incorporate your changes and resubmit my own PR.

**Comment by matthewlehner** [comment]
@pzingg Sorry about this! Unfortunately I got tied up with other things. I just had a look at your PR and it's a much more thorough approach. I will close this PR. Thanks for your patience!

**Pull request closed without merging**
