### PR TITLE
Definition for postaljs

### PR DESCRIPTION
**Pull request by lokeshpeta**
added new definition file for postaljs

### CODE REVIEW

**Comment by horiuchi** [comment]
@lokeshpeta Thank you for your contribution.
But please `rebase master` for cleanup commits.

**Comment by lokeshpeta** [comment]
@horiuchi I hope I have done the rebase correct :-)

**Comment by horiuchi** [comment]
@lokeshpeta That's good! :+1: 
Thanks mate!

**Comment by lokeshpeta** [comment]
@horiuchi Thanks :+1:

**Pull request merged**
