### PR TITLE
[dockerode] Use response stream types from 'stream' package instead of NodeJS

### PR DESCRIPTION
**Pull request by samuel-olivier**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L365-L366

Under the hood docker-modem returns a `http.IncomingMessage` (which extends `stream.Readable`) but I think it makes more sense to return the `stream.Readable` as the purpose of dockerode is to abstract the http layer.

Also I have some doubts about the typings of the `Container.putArchive` method. Currently it provides a `NodeJS.WritableStream` (replaced by a `stream.Writable` in this PR) as a callback parameter or returns a promised `NodeJS.ReadWriteStream` (replaced by a `stream.Duplex` in this PR).
But I think docker-modem returns by default a `http.IncomingMessage` or a `Duplex` if `openStdin` option is `true` (see this [docker-modem snippet](https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L354-L360)) which is `false` for `putArchive` (see the [dockerode function](https://github.com/apocas/dockerode/blob/master/lib/container.js#L971-L1005)). I verified by logging the type, and it's indeed a `http.IncomingMessage`. Should we return a `stream.Readable` ?
Though I neither understand why dockerode is passing the option `stream: true` because the docker API returns a 200 OK with no body (see [doc](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/PutContainerArchive)), but that's an issue for the dockerode repository.

### CODE REVIEW

**Comment by samuel-olivier** [comment]
@Seikho @nlaplante @isac322 @LazarusX @meisenzahl @thegecko @CameronDiver @P4sca1 @stuartthomson @userlerueda anyone has some spare time to review those changes ?

Also I created an issue on dockerode for the fact that `Container.putArchive` returns a stream: https://github.com/apocas/dockerode/issues/716

**Comment by samuel-olivier** [comment]
@Seikho @nlaplante @isac322 @LazarusX @meisenzahl @thegecko @CameronDiver @P4sca1 @stuartthomson @userlerueda 
I also added 3077cee5999b18680343b01a5ee1ef3c5d98b34b to add the missing `abortSignal` option to the `Container.stats`. See the related dockerode code: https://github.com/apocas/dockerode/blob/master/lib/container.js#L1060

**Comment by jakebailey** [comment]
I'm a little worried about this change because it seems like (from the snippets you've linked), what it may actually return is something which extends from the stream types in `readable-stream`, not Node's stream types.

The interface forms of these are very, very restrictive; `ReadableStream` only has like 6 properties whereas `NodeJS.Readable` has many many.

Have you checked some of the packages which use this package to see what they assume about the streams?

**Comment by RyanCavanaugh** [comment]
I don't want to merge this without signoff from another maintainer. The change seems risky given the sparse motivation for it -- the dockerode docs don't make particularly strong claims either way, so if the types are accurately reflecting what's going on at runtime, I'm not sure why something *should* change here.

**Pull request closed without merging**
