### PR TITLE
chore (sass): remove redundant types

### PR DESCRIPTION
**Pull request by 43081j**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

---

types shipped since 1.45.0:

https://unpkg.com/browse/sass@1.45.0/types/index.d.ts

FYI the ones still in DT shipping their own sass-dependent types, i made them use the synchronous _legacy_ sass options. im assuming those packages still depend on the older type structure. if any are actually new, let me know and ill update

### CODE REVIEW

**Comment by 43081j** [comment]
having all hell from the sass types clashing with the poorly typed existing stuff in DT.

will sort it tomorrow

sorry for the typescript-bot spam all.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gulp-dart-sass ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gulp-dart-sass@latest/))
was missing the following properties:
1. compiler
1. compiler
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dfdb690fb96de96c453ba6454d5f9eee7220cdd6
</p>

**Comment by peterblazejewicz** [comment]
@43081j do we need referencing @types/node in deps? (you've added inline references to updated packages)

**Comment by 43081j** [comment]
@peterblazejewicz the built in sass types depend on `Buffer` which is why I added that. Wasn't too sure myself though. If you have any other suggestion or think it makes sense, let me know

**Comment by peterblazejewicz** [comment]
asked on discord, will be back

**Comment by sandersn** [comment]
The `<reference types='node' />` line should be enough to make the `@types` publisher add a dependency on `@types/node@*`, which is what we want in this case.

You should double-check after publication though.

**Review by sandersn — APPROVED** [review]

**Comment by 43081j** [comment]
ready to merge 🍺 

ill have a look once it publishes 👍

**Comment by 43081j** [comment]
FYI you were right, it did add the dependency 🎉

**Comment by voltane** [comment]
It seems that this PR is a breaking change for a lot of projects.
Right now, simple types package forces installation of dart-sass (and for ex. we are not using it).
Here is a simple packages chain:
```
@nuxt/types 2.15.8
└─┬ @types/sass-loader 8.0.1
  └─┬ @types/sass 1.45.0
    └── sass 1.58.3
```
To fix the problem, we have to explicit install `@types/sass` in version 1.43.

**Comment by 43081j** [comment]
@voltane i understand. the removal isn't the problem here, we've yet again been hit by the implicit DT dependencies issue.

`@types/sass-loader@8.0.1` implicitly depended on `@types/sass`, which means it was set to `@types/sass: *`.

so results in you pulling down the latest `@types/sass` which is a stub package around the official types/source package now.

we can go fix up `@types/sass-loader` to explicitly define its dependencies (it should have anyway). but that won't fix the older version ofc so isn't of much use here.

ill have a think about it later today. importantly, removing sass isn't the issue really. `@types/sass-loader` having implicit dependencies was the issue.

last time this happened, i did the following (but not for sass):

* reintroduce `@types/sass`
* update `@types/sass-loader` to explicitly depend on it
* re-remove `@types/sass`

usually solves it.

**Comment by voltane** [comment]
Indeed, `@types/sass-loader` has a `*` dependency on `@types/sass`. Anyways, I'm still not convinced about making a direct dependency on `sass` package in `@types/sass` but i'm not going to argue here. For my case (and probably many more who land here looking for solution), removing `sass` is crucial, since we are still on `node-sass` and did not yet made all changes to move to dart-sass. Thats why, right now after fresh installation of packages our project blows up with dart-sass errors.

**Comment by 43081j** [comment]
you may have misunderstood.

when removing a DT type package, the dt publisher automatically creates a stub package in its place which depends on the _source package_.

so anyone newly pulling it in, not knowing the source package has types, will indirectly pull in the source package anyway.

it isn't specific to the sass package, its just how DT deals with removed definitions.

this wouldn't be a problem for you if the `@types/sass` dependency wasn't implicit. you'd basically stay on the DT types until you move to dart-sass, _then_ move to using the shipped types (no `@types/` package).

ill sort it out soon as i can

**Comment by sandersn** [comment]
@43081j I think CI for package deprecation should start requiring dependents of the deleted package to add a dependency on the previous version of the package.

**Comment by 43081j** [comment]
@sandersn i agree

i've run into this a few times now. its only really a problem when removing a package

**Pull request merged**
