### PR TITLE
[three] Format with dprint

### PR DESCRIPTION
**Pull request by Methuselah96**
Doing this in a separate PR to make it easy to review.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/three-types/three-ts-types/pull/797
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by jakebailey** [comment]
Totally happy to take this, but is the intent that you'll format them with our settings on your side?

Given your code is generated, I don't mind leaving it unformatted if your generator is the sole source of these files.

**Comment by Methuselah96** [comment]
Yes, I added dprint to three-ts-types in https://github.com/three-types/three-ts-types/pull/797, so all future updates will be formatted using dprint as well.

Our types are actually not generated, they're manually updated.

**Comment by jakebailey** [comment]
> The types are actually not generated, they're manually updated.

Yeah, I generally meant the broader term of "sourced from another repo and any changes on DT directly will be stomped on".

If we change the config, I assume you'll update things? (I don't know that we actually will change any settings, but I do try and update the plugins regularly).

**Comment by Methuselah96** [comment]
> If we change the config, I assume you'll update things? (I don't know that we actually will change any settings, but I do try and update the plugins regularly).

Yes, I try to keep things up-to-date with how they're configured in DT. If it gets out-of-sync too often (or if I feel like), I may write some CI that would detect that right away.

**Review by jakebailey — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Pull request merged**
