### PR TITLE
Add react-rating package 

### PR DESCRIPTION
**Pull request by KyleDavisDev**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration` (There is an outdated index.d.ts file in the package itself.)
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by minestarks** [comment]
This package [provides its own types](https://github.com/dreyescat/react-rating/blob/master/index.d.ts), so, it shouldn't go on DefinitelyTyped.

**Comment by minestarks** [comment]
@KyleDavisDev I see you've commented that their index.d.ts is out of date -- why not open a PR against that project with these changes?

**Comment by KyleDavisDev** [comment]
@minestarks Thank you for your response. I have asked repo owner if they are interested in moving the type file to be here only. When I get a response, I will update this thread.  Additionally, I was able to get the typings more complete (added onChange method) in [114](https://github.com/dreyescat/react-rating/pull/114) which helps.

Thank you

**Comment by KyleDavisDev** [comment]
Awesome! Thank you @minestarks. I'm happy this is resolved.

**Pull request closed without merging**
