### PR TITLE
React: `getModifierState(key)`

### PR DESCRIPTION
**Pull request by brunocrosier**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.w3.org/TR/uievents-key/#keys-modifier>

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. createRoot
1. hydrateRoot
1. createRoot
1. hydrateRoot
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d8665d4d644b14af039f0d3bd98857f83c9100c6
</p>

**Review by eps1lon — CHANGES_REQUESTED** [review]
It's not clear to me how the linked document relates to this specific method. Could you provide some more documentation that shows these are linked?

A test would be nice as well.

**Comment by eps1lon** [comment]
> > It's not clear to me how the linked document relates to this specific method. Could you provide some more documentation that shows these are linked?
> > A test would be nice as well.
> 
> Here is an example: [stackblitz.com/edit/react-ts-sec2ue?file=App.tsx](https://stackblitz.com/edit/react-ts-sec2ue?file=App.tsx)

This example is using native events. Native events are not them same as React's synthetic event. Do you have an example how this is used with React itself and how the linked spec relates to React?

**Comment by brunocrosier** [comment]
> > > It's not clear to me how the linked document relates to this specific method. Could you provide some more documentation that shows these are linked?
> > > A test would be nice as well.
> > 
> > 
> > Here is an example: [stackblitz.com/edit/react-ts-sec2ue?file=App.tsx](https://stackblitz.com/edit/react-ts-sec2ue?file=App.tsx)
> 
> This example is using native events. Native events are not them same as React's synthetic event. Do you have an example how this is used with React itself and how the linked spec relates to React?

Sorry, you're right - this example should show it better! https://stackblitz.com/edit/react-ts-gxmuqt?file=App.tsx

**Review by eps1lon — APPROVED** [review]
Thanks!

**Review by eps1lon — APPROVED** [review]

**Pull request merged**
