### PR TITLE
@types/cors: Allow booleans in static origin array

### PR DESCRIPTION
**Pull request by delucis**
This PR allows for `boolean` values in an array passed as the `origin` option when configuring `cors`. For example:

```js
cors({
    origin: [false, ...],
})
```

This is supported by [`cors`’s evaluation method](https://github.com/expressjs/cors/blob/c49ca10e92ac07f98a3b06783d3e6ba0ea5b70c7/lib/index.js#L19-L34), but not currently covered by the types.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

    The `isOriginAllowed` method `cors` runs to evaluate the static origins, allows for boolean values not only singly, but also when setting an array of allowed origins: https://github.com/expressjs/cors/blob/c49ca10e92ac07f98a3b06783d3e6ba0ea5b70c7/lib/index.js#L19-L34

### CODE REVIEW

**Review by gtpan77 — APPROVED** [review]
LGTM

**Comment by gtpan77** [comment]
Ready to merge

**Comment by francoiscap** [comment]
Would you mind explain us a use case when it makes sens to do this ?

**Comment by delucis** [comment]
Heh — 2 year old PR I barely remember making, so a bit vague, but I think mainly useful for certain programmatic use:

```js
origin: [
  someBooleanFlag && 'https://origin.com',
  'https://other-origin.com'
],
```

Not very likely you’d be just setting `origin: [false]`.

**Comment by delucis** [comment]
The types should match what the library supports I think, not what we think a library _should_ support.

**Comment by francoiscap** [comment]
You're right ! ;)

**Pull request merged**
