### PR TITLE
Ramda: R.into add case of converting types: R.into<From, To>([], transducer, sourceList);

### PR DESCRIPTION
**Pull request by vanyadymousky**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
@pirix-gh Could you please review? Thanks!

**Comment by uniqueiniquity** [comment]
@ethanresnick Could you please review? Thanks!

**Review by millsp — APPROVED** [review]
LGTM

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

**Pull request merged**
