### PR TITLE
[@types/prosemirror-inputrules] add members to InputRule class

### PR DESCRIPTION
**Pull request by lostfictions**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ProseMirror/prosemirror-inputrules/blob/725de68b97722a0081bd33674bd3279987925948/src/inputrules.js#L23-L26
- n/a Increase the version number in the header if appropriate.
- n/a If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by patsimm** [comment]
Hello @lostfictions, thank you for your PR!

Could you maybe provide an example why you need access to those class variables? I am not sure if this belongs in the typings since it's not mentioned in the official [prosemirror docs](https://prosemirror.net/docs/ref/#inputrules.InputRule.constructor).

You could always cast an instance of `InputRule` to `any` if you know what you're doing. I am not convinced that it is the right thing to access those members directly and adding them to the typings would encourage people to do so.

**Comment by lostfictions** [comment]
@patsimm Sure. See here for a plugin that uses the members on InputRules:

https://github.com/PeerioTechnologies/peerio-desktop/blob/f5f294aeedbcbd6cb3d3ecef660490fa85dd50af/src/helpers/chat/prosemirror/ensured-input-rules.js#L25-L37

It's already being cast to `any` but we're converting our codebase to TypeScript and it'd be nice if it was well-typed.

It's worth noting this plugin is in fact directly based on the ProseMirror `inputRules` plugin with only a small variation:
https://github.com/ProseMirror/prosemirror-inputrules/blob/725de68b97722a0081bd33674bd3279987925948/src/inputrules.js#L71-L72

As I referenced in the PR description, the `InputRule` class simply contains these members provided in the constructor directly:
https://github.com/ProseMirror/prosemirror-inputrules/blob/725de68b97722a0081bd33674bd3279987925948/src/inputrules.js#L23-L26

The ProseMirror documentation seems a little inconsistent about documenting members like these for simple classes that only hold fields. In any event, it doesn't seem like InputRules was meant to be an entirely opaque class without fields.

**Comment by bradleyayers** [comment]
@patsimm is right, https://prosemirror.net/docs/ref/#inputrules.InputRule documents the public API and these members are currently private. The proper path forward here would be to raise an issue at https://github.com/ProseMirror/prosemirror/issues and request that the members be documented as public API.

**Comment by lostfictions** [comment]
Thanks, I don't have more time to spend on this. I'll just double-cast the fields.

**Comment by rbuckton** [comment]
@lostfictions: Should I close this PR?

**Comment by lostfictions** [comment]
Hmm... would it be rude to ping @marijnh here for clarification?

**Comment by bradleyayers** [comment]
@lostfictions It'd be useful to add a link here to the ProseMirror Github issue requesting to make those fields public API.

**Comment by lostfictions** [comment]
Closing following discussion at https://github.com/ProseMirror/prosemirror/issues/835

**Pull request closed without merging**
