### PR TITLE
Add IE11 types

### LINKED ISSUE #1068: TS 4.4 changes document.createTreeWalker to only take three params, which is illegal in IE11
# lib Update Request

## Configuration Check

My compilation *target* is `ES2016` and my *lib* is `the default` in the TS 4.4 beta.

## Missing / Incorrect Definition

document.createTreeWalker was updated to take at most three parameters, where in previous TypeScript versions it would take four. Internet Explorer 11 will throw if the fourth parameter isn't specified.

The fourth parameter is deprecated, but real world code that needs to support older browsers like IE11 must use it.

## Sample Code

```typescript
document.createTreeWalker(document, NodeFilter.SHOW_ELEMENT, null, false);
```

Real world example: https://github.com/lit/lit/blob/a791514b426b790de2bfa4c78754fb62815e71d4/packages/lit-html/src/lit-html.ts#L396-L401

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker

### PR DESCRIPTION
**Pull request by saschanaz**
createTreeWalker is the first known IE11-only deviation.

Closes https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1068.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by saschanaz** [comment]
@rictic @sandersn @orta what do you think about this approach for issues like https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1068? 👀

**Comment by weswigham** [comment]
Technically this conflicts with an npm package of the same name: https://www.npmjs.com/package/ie11 hm.

**Comment by saschanaz** [comment]
Oops. Another suggestion from Orta was web-ie11. In that case it should be clear that its a supplemental type package unlike other web-* packages.

**Comment by rictic** [comment]
> @rictic @sandersn @orta what do you think about this approach for issues like [microsoft/TypeScript-DOM-lib-generator#1068](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1068)? 👀

This looks like a great solution. It'll make it supporting IE11 explicit, and as projects drop support the type errors will give some guidance on cleanups that are then possible.

I wonder how feasible it would be to also use this package to make a bunch of modern APIs as possibly undefined.

**Comment by saschanaz** [comment]
> I wonder how feasible it would be to also use this package to make a bunch of modern APIs as possibly undefined.

Adding types should be straightforward, but removing types is impossible this way.

Theoretically the types generator can receive a browser version configuration as babel-env does and generate types dynamically based on the versions, but that would be a significant work.

**Comment by rictic** [comment]
Ah, that makes sense. Everyone's done fine with modern APIs being always present, and with IE11's increasingly marginal position / degree of support it probably doesn't make sense to do any major engineering.

+1 to this approach

**Review by sandersn — APPROVED** [review]

**Comment by saschanaz** [comment]
(will rename as web-ie11)

**Comment by sandersn** [comment]
:+1: I was about to request that.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by saschanaz** [comment]
Ready to merge

Assuming it is

**Pull request merged**
