### PR TITLE
Update types for kafkajs from official repository

### PR DESCRIPTION
**Pull request by mahulst**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tulios/kafkajs/blob/master/index.d.ts
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by michal-b-kaminski** [comment]
I think you should delete the DefinitelyTyped package, not update it - at least according to [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

**Comment by mahulst** [comment]
It is not yet released on npm with types, they will be included in 1.9.0. These are the typings for 1.8.0, and they are more precise, as they are from the official package maintainers.

**Review by michal-b-kaminski — APPROVED** [review]

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by dolegi** [comment]
Hello, this seems to be incompatible with the latest version of kafkajs (1.8.0).
Specifically we have issues with the change of type of `KafkaOptions.ssl` which was `tls.ConnectionOptions`, but is now `KafkaConfig.ssl` and `tls.SecureContextOptions`, this stops us being able to pass the `rejectUnauthorized` option in. It also looks like a few other things have changed too.

Downgrading to `@types/kafkajs@1.8.0` works fine with `kafkajs@1.8.0`

Maybe I'm missing something or doing something wrong, but the default behaviour of
`npm install kafkajs && npm install --save-dev @types/kafkjs`
Installs kafkajs@1.8.0 and @types/kafkajs@1.8.1 which are incompatible

**Comment by michal-b-kaminski** [comment]
@mahulst Besides `KafkaConfig.ssl` mentioned above, I also see following problems:
- in `KafkaAdmin` - your typings have `fetchTopicMetadata` but in `kafkajs` there is `getTopicMetadata`
- in `ProducerBatch` - `acks`, `timeout` and `compression` are required event tough they have default values

Where there any changes in new typings that you need and are compatible with the library? Otherwise I think we have to restore previous version.

**Comment by rbuckton** [comment]
It sounds like these changes caused some significant breaks, so I will revert this PR.

**Comment by rbuckton** [comment]
This PR has been reverted. @mahulst: If you'd like to review your typings and file a new PR, please do so.

**Pull request merged**
