### PR TITLE
:tada: 'twemoji' no longer required

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Fixes in `package.json` from 13.1.1 allowed to properly use internal
definitions:

https://github.com/twitter/twemoji/releases/tag/v13.1.1

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by davwheat — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by davwheat** [comment]
Ready to merge

**Comment by andrewbranch** [comment]
@typescript-bot 🤨

**Comment by andrewbranch** [comment]
@typescript-bot I know it’s been a long day but when you tell someone they can self-merge you need to listen to them when they say they’re ready

**Comment by davwheat** [comment]
The bot must have realised it's April Fools!

**Comment by peterblazejewicz** [comment]
image
Very bad, bad bot!

**Pull request merged**
