### PR TITLE
[react-pie-menu] Add types

### PR DESCRIPTION
**Pull request by keyserj**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-pie-menu ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-pie-menu@latest/))
was missing the following properties:
1. background
1. centerRadius
1. centralAngle
1. endAngle
1. ifObtuse

<details>
<summary>as well as these 4 other properties...</summary>
<p>polar, radius, skew, startAngle</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 665ae53c6fadebffc1520a5c9599e27460b4deb7
</p>

**Comment by keyserj** [comment]
Regarding the remaining missing props, these are from the `export *`'s in the [index.js](https://github.com/psychobolt/react-pie-menu/blob/091431b21426527fbea007d5a1e92838334b31d2/src/index.js#L9-L11). They seem like they go through the theme to get to values, but I'm not sure how to use or type these.

**Comment by psychobolt** [comment]
@keyserj Partial update in the main project for some of the missing type information: https://github.com/psychobolt/react-pie-menu/commit/d7380823622a935fa53356c6d9136cb373c01efa . Some info on [theme context selectors](https://github.com/psychobolt/react-pie-menu#context-selectors) is already on the README. Will continue adding types and updating the docs.

**Review by sandersn — APPROVED** [review]

**Comment by keyserj** [comment]
@psychobolt thanks for the info - I added types for all those selectors being exported

**Comment by psychobolt** [comment]
All looks good to me. As for [`background`](https://github.com/psychobolt/react-pie-menu#background) utility, that should already be typed as it is showing type info for me even without [@types/styled-components](https://www.npmjs.com/package/@types/styled-components) installed:

image

**Pull request merged**
