### PR TITLE
Pouchdb

### PR DESCRIPTION
**Pull request by geppy**
Updated PouchDB definitions for PouchDB 5.4.4, split into the individually-available modules.

### CODE REVIEW

**Comment by mhegazy** [comment]
+1 for the module refactoring.

**Comment by mhegazy** [comment]
@Pfarrer, @jgillich , and @bobslaede  can you review please?

**Comment by Pfarrer** [comment]
Works for me, but did only check it in my current application. So, no exhaustive test.. :+1:

**Comment by valsinats42** [comment]
I've just tried it in my project, but it fails to compile due to missing 'replicate', 'changes' and 'on' bindings. Could you please check?

**Comment by geppy** [comment]
@valsinats42 This PR doesn't cover all of the PouchDB APIs.  I implemented the ones the team identified as being most important.  Feel free to [join us in Slack](https://pouchdb.slack.com/messages/typescript/).  There's [an invite generator](http://slack.pouchdb.com) (though it appears to be down at the moment).

**Pull request merged**
