### PR TITLE
Minimist 2.0

### PR DESCRIPTION
**Pull request by erykpiast**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
Has this worked at run-time in your own code? The module uses `module.exports =` instead of defining a default export, so I would expect this to fail when you tried running it.

**Comment by erykpiast** [comment]
Hi @andy-ms! Yes, it works with my code. I've tested with something like that:
```
import minimist, { ParsedArgs } from 'minimist';

const argv: ParsedArgs = minimist(process.argv.slice(2), {
  alias: {
    help: [ 'h' ],
    input: [ 'i' ],
    output: [ 'o' ],
  },
});
```
What exactly is your concern? As far as I know CommonJS module are imported in TS exactly in that way, so value assigned to `module.exports` is treated as default export and its properties as named ones. Did I missed something?

**Comment by andy-ms** [comment]
```
As far as I know CommonJS module are imported in TS exactly in that way, so value assigned to module.exports is treated as default export and its properties as named ones.
```

That isn't a behavior of TypeScript -- `export =` and `export default` result in different transpiled imports. I suspect you are either using a module loader different from node, or are doing an extra transpilation step.

For this example, when I try compiling this code:

```ts
import minimist from 'minimist';
console.log(minimist);

import minimist2 = require('minimist');
console.log(minimist2);
```

It transpiles to:

```js
"use strict";
var minimist_1 = require("minimist");
console.log(minimist_1["default"]);
var minimist2 = require("minimist");
console.log(minimist2);
```

Which outputs:

```
undefined
[Function]
```

Meaning, only `export =` (along with `import =`) will result in imports that work at runtime.

**Comment by erykpiast** [comment]
Thank you for profound explanation! It makes sense indeed. What do you recommend in that case? Is this even possible to make it working with that syntax in pure TS? I mean `import minimist, { ParsedArgs } from 'minimist';`.

**Comment by andy-ms** [comment]
I don't think so. You could achieve a similar affect with `import minimist = require("minimist"); const { ParsedArgs } = minimist;`.

**Comment by erykpiast** [comment]
Yes, I know, this is what I was doing so far. To make that clear, there is no possibility to switch in 100% to EcmaScript import syntax if I want to use CommonJS libraries?

**Comment by andy-ms** [comment]
If the thing on the right side of the `export =` is a namespace (or is merged with a namespace), you can do `import { .. } from "foo";` in addition to `import foo = require("foo")`. It will still take 2 lines, though.

**Comment by erykpiast** [comment]
Okay, that's what I wish to know. I'm closing this PR then. Thank you a lot for comments!

**Pull request closed without merging**
