### PR TITLE
Update ioredis, add bzpopmin/max and hstrlen

### PR DESCRIPTION
**Pull request by Handgrip**
Add bzpopmin, bzpopmax, hstrlen, optimize the interface of the function with promise return value in the OverloadedBlockingListCommand interface.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://redis.io/commands/bzpopmin>><<https://redis.io/commands/bzpopmax>><<https://redis.io/commands/hstrlen>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ioredis ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ioredis@latest/))
was missing the following properties:
1. createClient
1. defaultOptions
1. ScanStream
1. Pipeline
1. AbstractConnector

<details>
<summary>as well as these 5 other properties...</summary>
<p>SentinelConnector, SentinelIterator, ReplyError, Promise, print</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fec04208852b1ef94fb5513fb59fa5eb11e2b838
</p>

**Comment by Flaryer** [comment]
@danger-public 
Sorry for my poor reading comprehension and poor English, do you want to request to add these properties? I thought about it, but the workload was too much. Adding 'Buffer' to each function is actually a usable function. (But it may not hurt.)
source code:
```ts
commands.forEach(function (commandName) {
  Commander.prototype[commandName] = generateFunction(commandName, "utf8");
  Commander.prototype[commandName + "Buffer"] = generateFunction(
    commandName,
    null
  );
});
```

In addition to the attributes you mentioned, possible missing commands:

- [ ] bitfield
- [ ] bitop
- [ ] bitpos
- [x] bzpopmax
- [x] bzpopmin
- [ ] command
- [ ] geoadd
- [ ] geodecode
- [ ] geodist
- [ ] geoencode
- [ ] geohash
- [ ] geopos
- [ ] georadius
- [ ] georadiusbymember
- [x] hstrlen
- [ ] pubsub
- [ ] readonly
- [ ] readwrite
- [ ] replicaof
- [ ] role
- [ ] slowlog
- [ ] swapdb
- [ ] touch
- [ ] wait
- [ ] zlexcount

And I'm a runoob and I don’t know much about other properties, and may not be competent.

**Comment by Flaryer** [comment]
@plantain-00 @chrisleck @aliarham11 @br8h @palindrom615 @reconbot @funthing @iamolegga @tingwai-to @pettyalex @SimonSchick @tianlinle @demian85 @alavers @ClaudiuCeia @asyrique   

I may need your reviews to speed up the process of PR, sincere thanks! Please forgive me if there is any interruption.

**Review by plantain-00 — APPROVED** [review]

**Comment by Flaryer** [comment]
Ready to merge

**Pull request merged**
