### PR TITLE
[meteor] The `userId` from the Subscription may be null

### PR DESCRIPTION
**Pull request by nicu-chiciuc**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [?] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [?] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

As per [the documentation](https://docs.meteor.com/api/pubsub.html#Subscription-userId) the `userId` in a Subscription can be `null`.

I'm not sure why the test doesn't pass, it seems that whatever I do, the `null` is removed from the `userId` type and the test fails because userId has just a type of `string`. Replacing `null` with number maintains the type correctly yet if I try to add `null` it disappears.

I also had problems with the `globals` folder. I'm not sure if we're still maintaining the script that generates the globals since it doesn't seem to work for me. I remember there were problems with the script but I'm not sure if the `globals` folder is even used by someone.

### CODE REVIEW

**Review by radekmie — APPROVED** [review]

**Comment by radekmie** [comment]
@nicu-chiciuc As Meteor typings have [disabled `strictNullChecks`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5eeb6c9eaa7e6403accd8cd628ec71dbdf111811/types/meteor/tsconfig.json#L10),  you'll have to correct the `this.userId` type in tests to `string`.

**Comment by nicu-chiciuc** [comment]
Didn't notice that `strictNullChecks` was disabled. Is there a reason for that? If there is, I'm not sure how to add a test for this small change.

**Comment by nicu-chiciuc** [comment]
I could of course just remove the change in the tests but that seems like a sub-optimal solution.

**Comment by radekmie** [comment]
@nicu-chiciuc I'm not sure, but that's how it is _now_. Removing the `| null` part will be enough for the tests.

**Review by radekmie — APPROVED** [review]

**Comment by orta** [comment]
Cool, matches the docs 👍🏻

**Pull request merged**
