### PR TITLE
secure-json-parse: add missing option

### PR DESCRIPTION
**Pull request by mikemaccana**
Added constructorAction, which was missing from the previous type definition
See https://github.com/fastify/secure-json-parse#readme

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/fastify/secure-json-parse#readme
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by mikemaccana** [comment]
Heya! Could I please get some feedback and/or a merge?

**Review by OSjoerdWie — APPROVED** [review]
Apologies for the delayed response.

Looks ok.

**Comment by mikemaccana** [comment]
Thanks! When will the updated typings be available on npm?

**Comment by OSjoerdWie** [comment]
That is not something I control, afaik. After my approval, the change has
been merged to master. When I look at NPM right now, it seems that it is
there.

Sjoerd

**Pull request merged**
