### PR TITLE
Change the definition of Omit<T, K> so that it preserves discriminated unions

### PR DESCRIPTION
**Pull request by ikeyan**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/microsoft/TypeScript/issues/31501
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongodb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongodb@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'mongodb'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cfd2bcc9daf21bb66dd27b7c7d8566f2c8c26e62
</p>

**Comment by HitkoDev** [comment]
As stated in https://github.com/microsoft/TypeScript/issues/31501, the implementation of `Omit` is as intended and won't be changed. The implementation here is a copy of original TypeScript implementation, and should be kept as is to prevent confusion. If you have a good reason to use a different implementation somewhere in typings, consider making a custom type (e.g. `OmitUnion`) and using that where strictly needed.

**Review by emmanuelgautier — CHANGES_REQUESTED** [review]
You made some additional code style changes. Could you make another commit at least for these changes ?

**Review by LinusU — COMMENTED** [review]
Very interesting read in the linked issue 👍

**Review by LinusU — APPROVED** [review]
(meant to press "Approve")

**Comment by LinusU** [comment]
@HitkoDev the `Omit` is used internally, and breaks the returned value as far as I understood it. If you look at the added test case you'll see why this needs to be addressed internally, otherwise the collection type just won't work unless you cast it back manually. Or am I missing something?

**Comment by HitkoDev** [comment]
@LinusU The purpose of `Omit` is clearly defined: to provide backwards compatibility with TypeScript < 3.5. Changing that is a no go. 

There's already `EnhancedOmit` defined in typings, which is a much better candidate for this kind of modifications: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cfd2bcc9daf21bb66dd27b7c7d8566f2c8c26e62/types/mongodb/index.d.ts#L1076-L1079

A proper solution here would be
```ts
// TypeScript Omit (Exclude to be specific) does not work for objects with an "any" indexed type, and breaks discriminated unions
type EnhancedOmit<T, K> = string | number extends keyof T
    ? T // T has indexed type e.g. { _id: string; [k: string]: any; } or it is "any"
    : (T extends any 
        ? Pick<T, Exclude<keyof T, K>> // discriminated unions
        : never
    );
```

I believe this would also remove the need for `Omit` polyfill in the typings.

**Review by HitkoDev — CHANGES_REQUESTED** [review]
Please change as per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49783#issuecomment-738194226

**Comment by ikeyan** [comment]
addressed:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49783#pullrequestreview-543870945
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49783#issuecomment-738194226

**Review by HitkoDev — APPROVED** [review]

**Comment by ikeyan** [comment]
Ready to merge

**Comment by alias-mac** [comment]
@ikeyan and @HitkoDev it based on my findings this version broke my types on `WithId<Union>`.
I have a few types defined as `WithId<Foo | Bar | Baz>` and with this change it seems to apply the `WithId` only to the first union.
I need to take a deeper dive on this and create a small reproducible example, but just wanted to leave feedback here since this was recently merged and others might be running into the same problem.

**Pull request merged**
