### PR TITLE
[react-copy-to-clipboard]: fixed typings

### PR DESCRIPTION
**Pull request by ngub**
React.Component class generic has been missing state parameter which was causing compiler errors.

### CODE REVIEW

**Comment by dubsar** [comment]
first of all: thank you for the great job!

i'm writing here because i couldn't figure out a better place
i use [VictoryZoomContainer](http://formidable.com/open-source/victory/docs/victory-zoom-container) but it seems that it's missing, or am i missing something ?

thanks again

**Comment by ngub** [comment]
@dubsar may I ask you, why do you ask about Victoria.js here? This is a pull request for another lib, actually. I am ready to help you though, if I can. Could you, please, describe your problem more specifically?

**Comment by dubsar** [comment]
@ngub thank you for the kind answer
i knew this was the wrong place :)

time permitting i'll create a pull request
cheers

**Comment by rbuckton** [comment]
@ngub, which version of TypeScript are you using? The declaration file targets TypeScript 2.3, which supports the type parameter defaults used by React, so the second type parameter should not be required.

**Comment by ngub** [comment]
@rbuckton, I am using TS 2.1 for now.
Should I change target version in the commit to pass this PR?

**Comment by rbuckton** [comment]
Changing the target version will cause issues as it depends on React which depends on 2.3. If you are using TypeScript 2.1 then you should ensure you install the correct version of `@types/react-copy-to-clipboard` for 2.1 rather than make this change:

```
npm uninstall @types/react-copy-to-clipboard --save-dev
npm install @types/react-copy-to-clipboard@ts2.1 --save-dev
```

**Pull request closed without merging**
