### PR TITLE
[jest]: add type reference to jest-diff

### PR DESCRIPTION
**Pull request by SimenB**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: From #32891
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Is this enough to add the dependency?

It need to import `@types/jest-diff`

### CODE REVIEW

**Comment by SimenB** [comment]
Is there some way to preview the generated `package.json`

**Comment by sirian** [comment]
@SimenB try generate package using https://github.com/Microsoft/types-publisher

**Comment by sirian** [comment]
```sh
cat data/definitions.json | jq '.jest."24"'
```

```json
{
  "libraryName": "Jest",
  "typingsPackageName": "jest",
  "projectName": "http://facebook.github.io/jest/",
  "contributors": [
    {
      "name": "Asana",
      "url": "https://asana.com"
    },
    {
      "name": "Ivo Stratev",
      "url": "https://github.com/NoHomey",
      "githubUsername": "NoHomey"
    },
    {
      "name": "jwbay",
      "url": "https://github.com/jwbay",
      "githubUsername": "jwbay"
    },
    {
      "name": "Alexey Svetliakov",
      "url": "https://github.com/asvetliakov",
      "githubUsername": "asvetliakov"
    },
    {
      "name": "Alex Jover Morales",
      "url": "https://github.com/alexjoverm",
      "githubUsername": "alexjoverm"
    },
    {
      "name": "Allan Lukwago",
      "url": "https://github.com/epicallan",
      "githubUsername": "epicallan"
    },
    {
      "name": "Ika",
      "url": "https://github.com/ikatyang",
      "githubUsername": "ikatyang"
    },
    {
      "name": "Waseem Dahman",
      "url": "https://github.com/wsmd",
      "githubUsername": "wsmd"
    },
    {
      "name": "Jamie Mason",
      "url": "https://github.com/JamieMason",
      "githubUsername": "JamieMason"
    },
    {
      "name": "Douglas Duteil",
      "url": "https://github.com/douglasduteil",
      "githubUsername": "douglasduteil"
    },
    {
      "name": "Ahn",
      "url": "https://github.com/ahnpnl",
      "githubUsername": "ahnpnl"
    },
    {
      "name": "Josh Goldberg",
      "url": "https://github.com/joshuakgoldberg",
      "githubUsername": "joshuakgoldberg"
    },
    {
      "name": "Jeff Lau",
      "url": "https://github.com/UselessPickles",
      "githubUsername": "UselessPickles"
    },
    {
      "name": "Andrew Makarov",
      "url": "https://github.com/r3nya",
      "githubUsername": "r3nya"
    },
    {
      "name": "Martin Hochel",
      "url": "https://github.com/hotell",
      "githubUsername": "hotell"
    },
    {
      "name": "Sebastian Sebald",
      "url": "https://github.com/sebald",
      "githubUsername": "sebald"
    },
    {
      "name": "Andy",
      "url": "https://github.com/andys8",
      "githubUsername": "andys8"
    },
    {
      "name": "Antoine Brault",
      "url": "https://github.com/antoinebrault",
      "githubUsername": "antoinebrault"
    }
  ],
  "libraryMajorVersion": 24,
  "libraryMinorVersion": 0,
  "minTsVersion": "3.0",
  "typesVersions": [],
  "files": [
    "index.d.ts"
  ],
  "license": "MIT",
  "dependencies": [
    {
      "name": "jest-diff",
      "majorVersion": "*"
    }
  ],
  "testDependencies": [],
  "pathMappings": [],
  "packageJsonDependencies": [],
  "contentHash": "adb905c3644d1c270a0befec4f8b7705a41f2555b9597b7b25069067ce2ff3a9",
  "globals": [
    "afterAll",
    "afterEach",
    "beforeAll",
    "beforeEach",
    "describe",
    "expect",
    "fail",
    "fdescribe",
    "fit",
    "it",
    "jasmine",
    "jest",
    "pending",
    "spyOn",
    "test",
    "xdescribe",
    "xit",
    "xtest"
  ],
  "declaredModules": []
}
```

**Comment by sirian** [comment]
@SimenB BTW, maybe it would be better to include typings in jest package itself rather than using DefinitelyTyped?

**Comment by SimenB** [comment]
Thanks! That's almost right - it should depend on `types/jest-diff`, not `jest-diff` (until we make a new release, at which point `jest-diff` _will_ come with TS types out of the box).

---

>BTW, maybe it would be better to include typings in jest package itself rather than using DefinitelyTyped?

Working on it 😉 https://github.com/facebook/jest/issues/7807

**Comment by minestarks** [comment]
@sandersn types-publisher has been pushing other packages but hasn't picked this one up yet. Is it stuck or am I just impatient?

**Comment by minestarks** [comment]
Oh types-publisher is hanging out at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32990 currently. It'll get here eventually I assume 😄

**Comment by sandersn** [comment]
Yep, someday. It's on handlebar-helpers right now.

**Comment by SimenB** [comment]
> > BTW, maybe it would be better to include typings in jest package itself rather than using DefinitelyTyped?
> 
> Working on it 😉 [facebook/jest#7807](https://github.com/facebook/jest/issues/7807)

#33705

**Pull request merged**
