### PR TITLE
chore(mongodb): apply prettier (no code changes)

### PR DESCRIPTION
**Pull request by alias-mac**
Run `npm run prettier -- --write types/mongodb/**/*.ts` to apply
prettier changes in this package.
This is suggested in the README.md of this repo and makes it easier to
contribute to this package.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongodb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongodb@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'mongodb'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 98e36e1ac89079b76516f21711b10042506f631c
</p>

**Review by CaselIT — APPROVED** [review]
Only the formatting was changed, right?

Looks ok

**Comment by alias-mac** [comment]
> Only the formatting was changed, right?
> 
> Looks ok

Yes, only automatic formatting using that script and moving the `$ExpectError` comments to the right lines.

**Comment by alias-mac** [comment]
@CaselIT, rebased and reapplied the changes with `npm run prettier -- --write types/mongodb/**/*.ts`.
Moved the `$ExpectError` comments to the right lines to pass linting.

**Review by CaselIT — APPROVED** [review]

**Comment by alias-mac** [comment]
Ready to merge

**Pull request merged**
