### PR TITLE
fix(leavlet.awesome-markers): typo in color name

### PR DESCRIPTION
**Pull request by sebek64**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sigma-geosistemas/Leaflet.awesome-markers#properties
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@sebek64  Change looks correct but can you please give URL to documentation. Thanks

**Comment by sebek64** [comment]
Yes, I see. I've updated the pull request text to contain correct documentation link.

**Comment by Odrin** [comment]
@sheetalkamat they have typo in docs and opened [PR](https://github.com/lvoogdt/Leaflet.awesome-markers/pull/70) to fix it.

**Comment by sebek64** [comment]
In my opinion, the repository at https://github.com/lvoogdt/Leaflet.awesome-markers is no longer active, and the one with the most recent commits is https://github.com/sigma-geosistemas/Leaflet.awesome-markers.

**Comment by sheetalkamat** [comment]
@sebek64  In that case can you please update https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16205/files#diff-7ab4757f0d0dc8b7909e16c90d56f2f4L2 to correct link.

**Comment by sebek64** [comment]
@sheetalkamat I've pushed an additional commit fixing the project link.

**Pull request merged**
