### PR TITLE
[heroku-client] package type declarations

### LINKED ISSUE #106: Typescript types?
Could we add TS types to this repo for the api options? After a first looksie for `@types/heroku-client` and `@types/node-heroku-client` I didn't see anything.

Happy to add this to another repo if this is not the right spot, thanks!

### PR DESCRIPTION
**Pull request by Oaphi**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

This PR adds type definitions for the [heroku-client](https://www.npmjs.com/package/heroku-client) and can close heroku/node-heroku-client#106

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
There are only 3 files in the package (index, request, url). I'd keep the simple structure and move all interfaces into `index.d.ts`, so you can share them in the definition. That will alov to avoid 3.8 requirement (and you could remove minimum TS version completely). On next public TS release (4.5), you can add `import type` explicitly.

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@Oaphi thx!

You've taken yet another approach, which is great, thanks for taking PR review into consideration!

**Comment by Oaphi** [comment]
Ready to merge

**Comment by Oaphi** [comment]
@peterblazejewicz and thank you for reviewing! I was sure I followed your suggestion, though :) There is, indeed, no need to mimic the internal package structure, especially given its size

**Pull request merged**
