### PR TITLE
Replace Stream#_transform()s with single method with chunk: any

### PR DESCRIPTION
**Pull request by chbrown**
When a stream.Transform is fed from a stream that has `{objectMode: true}`, the `Stream#_transform(chunk, encoding, callback)` method will not be called with chunks that are strings or Buffers.

Simply adding a `_transform()` variant with `chunk: any` does not satisfy the TypeScript compiler for some reason.

I'd prefer type parameterizing the whole `stream.Transform` class with the type of the chunks it will deal with, but this change is smaller, and, I imagine, less contentious.

### CODE REVIEW

**Comment by vvakame** [comment]
@jvilk @loyd could you review this PR?

**Comment by loyd** [comment]
@chbrown What about `_write`, `write`, `writev`, `unshift`, and `end`?

**Comment by chbrown** [comment]
@loyd I guess I only wanted to venture as much as I needed for my library to compile — but yes, those suffer the same problem. Would you approve a PR changing them all?

**Comment by loyd** [comment]
@chbrown Well. I think, until TS supports [default generic type](https://github.com/Microsoft/TypeScript/issues/2175) or has strong type inference (like rust or haskell), parameterizing leads to overhead (it will always need to specify the type explicit) and I am inclined to `any` solution.

**Comment by chbrown** [comment]
@loyd I agree. I've made the rest of the changes. It turns out a few of the `chunk: T` argument types were already `any`, e.g., `Readable#push`. Let me know if I missed any.

**Comment by loyd** [comment]
@vvakame LGTM

**Comment by vvakame** [comment]
@loyd thanks!
@chbrown thanks mate! :+1:

**Comment by jvilk** [comment]
Thanks for reviewing, @loyd! I was on vacation, but am back now. :smile: I hope we can eventually have better support for typing things as `string | Buffer` without inconveniencing code writers.

**Pull request merged**
