### PR TITLE
[@types/ysdk] Add types and tests for new sdk features

### PR DESCRIPTION
**Pull request by koteelok**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://yandex.ru/dev/games/doc/en/sdk/sdk-player#ingame-data
https://yandex.ru/dev/games/doc/ru/sdk/sdk-game-events
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/ysdk/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 52b21fe45ef84c54a183f42d368cb473f6870123
</p>

**Comment by koteelok** [comment]
Can we just merge it already?

**Comment by koteelok** [comment]
@peterblazejewicz 🥺 approve plz

**Comment by koteelok** [comment]
@sheetalkamat I would be very happy if you could help me close this PR. Thanks!

**Comment by koteelok** [comment]
@jakebailey

**Review by gabritto — APPROVED** [review]

**Comment by koteelok** [comment]
Ready to merge

**Pull request merged**
