### PR TITLE
feat: :sparkles: Add TypeScript definitions for twitchat

### PR DESCRIPTION
**Pull request by Drilmo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/twitchat/tsconfig.json
1. types/twitchat/package.json
1. types/twitchat/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against faadeea9c5de1d2cc3e2c469d8159401d3033103
</p>

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/twitchat/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e1d5c58197d52e2fa97a85f326d8610d3003192
</p>

**Review by sandersn — CHANGES_REQUESTED** [review]
twitchat is written in Typescript and lists EventType and ActionType in its public API:
https://github.com/Durss/Twitchat/blob/main/PUBLIC_API.md

Its examples are also written in Typescript. Does twitchat itself ship types? It certainly looks like it does. If so, DT doesn't need types for it.

**Comment by Durss** [comment]
> twitchat is written in Typescript and lists EentTYpe and ActionType in its public API: https://github.com/Durss/Twitchat/blob/main/PUBLIC_API.md
> 
> Its examples are also written in Typescript. Does twitchat itself ship types? It certainly looks like it does. If so, DT doesn't need types for it.

Hello !
Twitchat is an app, not a librairy, so it doesn't exports any typing whatsoever as it cannot really be imported in a project.
The documentation only tells how to connect to a websocket API it exposes, what to listen for and what we can send it.

The idea of that DT would be to make it easier for devs to interface with Twitchat WS-API without having to rely only the external documentation.

The DT is pretty light for now but I'm planning to contribute it to make it complete.
It's mostly missing the data format received from events, and the data format expected by the actions as well as comments for each action/event.

Hope it makes things clearer :)

**Review by sandersn — APPROVED** [review]

**Comment by Durss** [comment]
Ready to merge

**Comment by Drilmo** [comment]
Ready to merge

**Pull request merged**
