### PR TITLE
feat(@types/gulp-sourcemaps): updated modules typings

### PR DESCRIPTION
**Pull request by concision**
# Template

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint gulp-sourcemaps` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gulp-sourcemaps/gulp-sourcemaps#write-options
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

# Description
Several typings for `WriteOptions` are currently missing, which are documented on the [gulp-sourcemaps/gulp-sourcemaps](https://github.com/gulp-sourcemaps/gulp-sourcemaps#write-options) repository. This PR adds all non-deprecated documented properties for `WriteOptions`.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## gulp-sourcemaps ([<kbd>unpkg</kbd>](https://unpkg.com/browse/gulp-sourcemaps@latest/))
was missing the following properties:
1. mapSources
1. identityMap
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6f21a9e9278ef783fd905de59daaaf345376ea58
</p>

**Comment by concision** [comment]
In response to @danger-public's bot response, `mapSources` and `identityMap` _are_ exported properties that are missing. However, the implementation in `gulp-sourcemaps/gulp-sourcemaps` is as follows:

https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/d8bed0c282f6975daa48b4ecd2053528a0b7b2e5/index.js#L6

Since the transitive dependencies `@gulp-sourcemaps/map-sources` and `@gulp-sourcemaps/identity-map` are not existing DefinitelyTyped packages, implementing this change would go beyond the scope of modifying a single module's typings (in this PR: `gulp-sourcemaps`). Several additional PRs would be necessary to add typings for these packages.

**Comment by elibarzilay** [comment]
@pspeter3: looking at the blame for this package, you're the one who added `Asana <https://asana.com>` as an owner.  These lines are used to ping people for review, so that line is useless ATM.  Do you mind being put on the list instead, or someone else from the group?

**Comment by pspeter3** [comment]
I'm happy to be put as the reference. That line predates the review ping tool.

**Comment by concision** [comment]
@pspeter3 I have added you as a ["definition owner"](https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners) for this package. However, I am not sure what the ramifications are in terms of the approval process on this specific PR (since it also "adds" you as an owner).

There is another PR on this same package as well that can likely be fast-tracked if the new definition owners are successfully merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49243

**Pull request merged**
