### PR TITLE
[cosmiconfig] Remove package

### PR DESCRIPTION
**Pull request by ffflorian**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

See https://github.com/davidtheclark/cosmiconfig/blob/6.0.0/package.json#L6.

### CODE REVIEW

**Comment by ffflorian** [comment]
Blocked by https://github.com/microsoft/types-publisher/pull/695.

**Comment by ffflorian** [comment]
@sandersn unfortunately Travis still thinks that `cosmiconfig` is not among the whitelisted dependencies although https://github.com/microsoft/types-publisher/pull/695 was merged.

**Comment by sandersn** [comment]
Weird, I thought I cleared the cache. I will try again.

**Comment by PranavSenthilnathan** [comment]
This PR does remove the v4 typings, which people may be depending on. @ozum @szeck87 @saadq @jinwoo @bmatcuk could you take a look?

**Review by bmatcuk — COMMENTED** [review]
Well, removing this package doesn't delete the existing `@types/cosmiconfig` packages from npm, right? So, if someone is depending on the v4 or v5 types, they should be fine.

My only concern is that postcss-load-config currently depends on cosmiconfig `^5.0.0`, not v6, so the changes to the postcss-load-config types is not _technically_ correct.

**Comment by sandersn** [comment]
@bmatcuk they remain but you can't ship fixes to them since the source is gone.

The types haven't changed since June 2018, though, so I doubt 4.x or 5.x will need any more changes.

If postcss-load-config compiles with the version of 6 it gets as of today, I'd recommend pinning an exact version in its package.json. It only depends on the ExplorerOptions types, so I'd guess it's pretty safe anyway; people tend not to delete things from options types, only add them.

**Comment by bmatcuk** [comment]
Oh ya, that's true... but, as you mention, haven't been any changes in a long time, so probably ok.

Re: postcss-load-config: As long as the v6 options are identical to the v5 ExplorerOptions, and the version is pinned in package.json, I'm ok with that.

**Pull request merged**
