### PR TITLE
Update types for Boom 7.1.1

### PR DESCRIPTION
**Pull request by TimonVS**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/boom
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by TimonVS** [comment]
With this PR I moved the previous typings to a v4 folder. There have been a few minor changes between 4.x and 7.x. For one I removed the `BoomError` interface and replaced it with a `Boom` class. Dependents are still using `BoomError` however.

Travis fails because dependents are using the wrong version of the Boom typings:

- Hapi 16.1 uses Boom 4.x
- h2o2 5.4 uses Boom 3.x
- Catbox 7.1 uses Boom 5.x (we can use 4.x typings for this one)

How can I best solve this issue? How can I configure the dependents to use the v4 version of the Boom typings?

**Comment by TimonVS** [comment]
I tried updating path mappings from all dependents to Boom v4 but I'm now stuck with the following error:

```
λ ~/Projects/DefinitelyTyped/ master* node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed
Clean data
Clean logs
Clean output
# Typing Publish Report Summary
Started at Fri, 29 Dec 2017 14:38:57 GMT
Found 3977 typings folders in /Users/timon/Projects/DefinitelyTyped/types
Error: boom depends on hapi, which has a path mapping for boom v4. boom must have the same path mappings as its dependencies.
    at checkPathMappings (/Users/timon/Projects/DefinitelyTyped/node_modules/types-publisher/src/check-parse-results.ts:85:12)
    at Object.<anonymous> (/Users/timon/Projects/DefinitelyTyped/node_modules/types-publisher/src/check-parse-results.ts:18:2)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/timon/Projects/DefinitelyTyped/node_modules/types-publisher/bin/check-parse-results.js:4:58)
    at <anonymous>
```

Boom depends on Hapi (for `boom-tests.ts`) so I'm not sure how to solve this.

**Comment by AJamesPhillips** [comment]
Hey @TimonVS
What if you just try deleting the line `import * as Hapi from 'hapi';` ?  It's been a while since I worked on this but I couldn't see just now why we would be importing from Hapi here.

**Comment by TimonVS** [comment]
@AJamesPhillips Thanks for the tip, that seems to fix the issue :)

**Comment by mhegazy** [comment]
@AJamesPhillips and @nycdotnet can i get a sign off on this change?

**Review by nycdotnet — APPROVED** [review]
I am approving based on build having worked and a general overview of the changed tests/definition.  I don't use Boom so can't personally vouch beyond that.  Thanks for the PR!

**Comment by TimonVS** [comment]
@mastermatt You're right. I created a PR to fix the issue.

**Pull request merged**
