### PR TITLE
openlayers : add showLabels parameter to GraticuleOptions interface

### PR DESCRIPTION
**Pull request by gasperiguillaume**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

@davinkevin @Neonox31

### CODE REVIEW

**Comment by iamthechad** [comment]
If `showLabels` is being added, does it also make sense to add the rest of the label formatting options to make the `GraticuleOptions` definition match the OpenLayers API?

**Comment by davinkevin** [comment]
Male sense for us. @gasperiguillaume, could you do it ?

**Comment by gasperiguillaume** [comment]
It's done @sheetalkamat @davinkevin @iamthechad

**Comment by RyanCavanaugh** [comment]
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.

**Comment by osechet** [comment]
@iamthechad If you approve a modification and there is no discussion about it, don't thumb it up, approve it in the "files changed" tab. That way it can be merge automatically as soon as possible.

**Review by osechet — APPROVED** [review]
Modification reviewed and validated by @iamthechad

**Comment by iamthechad** [comment]
@osechet What's the official process? Do I thumbs up the @dt-bot comment as it states or is it necessary to approve file changes?

**Comment by osechet** [comment]
@iamthechad I never tried to thumb up the bot's comment; I always went through the review process. I guess we can try with a future PR.

**Comment by davinkevin** [comment]
Any news ? 

FYI, We are waiting after this to complete our dev and do PR on another project

Thanks

**Comment by osechet** [comment]
@davinkevin It has been flagged with merge:express by DefinitelyTyped's maintainer so it should be merge soon. We can do nothing more here.

**Comment by gasperiguillaume** [comment]
Is there something new ? Sorry to seem impatient but we are still waiting after this to do a PR on another project.

**Comment by DanielRosenwasser** [comment]
I apologize for the delay, thank you for your patience though!

**Pull request merged**
