### PR TITLE
[d3-random] Update to v1.1.0

### LINKED ISSUE #16300: [d3-random] Update to Version 1.1.0
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache

### PR DESCRIPTION
**Pull request by tomwanzek**
* [Feature] Update d3-random to minor version 1.1 adding configurable source of pseudo-random numbers.
* [Chore] Enable `strictNullChecks`
* [Chore] Add tslint config.
* [Chore] Bumped version.

Closes #16300 .

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/d3/d3-random/releases>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by tomwanzek** [comment]
@gustavderdrache Whenever you have a minute...

**Comment by tomwanzek** [comment]
Related to #11365 .

**Review by gustavderdrache — APPROVED** [review]
Looks good.

**Comment by tomwanzek** [comment]
@andy-ms If you have a second, could you kindly merge this PR. As always, thanks in advance!!! T

**Comment by tomwanzek** [comment]
@andy-ms Somehow, the merge has not triggered a publish to `npm/@types` for **d3-random**. Thx in advance for looking into it when you have a sec.

**Comment by andy-ms** [comment]
Sorry, azure acting up. Ran a manual publish.

**Comment by tomwanzek** [comment]
Thanks a lot!  All 👍 for random/zoom/drag.

**Pull request merged**
