### PR TITLE
[react-redux] Add missing WrappedComponent 

### PR DESCRIPTION
**Pull request by alecmerdler**
Addresses #17543.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactjs/react-redux/blob/master/docs/api.md#static-properties
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by thasner** [comment]
@alecmerdler can you explain this change? what is it fixing?

**Comment by alecmerdler** [comment]
I'm trying to test `connect`ed TypeScript React components using the solution presented [here](https://github.com/airbnb/enzyme/issues/472#issuecomment-229710209), but the `WrappedComponent` property does not exist. [According to the docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md#static-properties), it should. If I have oversimplified the type definition, please let me know.

**Review by clayne11 — CHANGES_REQUESTED** [review]
Please add a test confirming that this works as expected.

**Comment by alecmerdler** [comment]
Okay, I have added a test which I believe demonstrates usage for `WrappedComponent`.

**Review by clayne11 — APPROVED** [review]

**Review by thasner — APPROVED** [review]

**Comment by pocesar** [comment]
broke everything again... oh lord

**Pull request merged**
