### PR TITLE
[react] Allow `TrustedHTML` in `dangerouslySetInnerHTML`

### PR DESCRIPTION
**Pull request by eps1lon**
Closes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60417

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
   - https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML
   - https://codesandbox.io/s/trustedhtml-kfxbhz
- ~[ ]~ If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

/cc @lgarron

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 88ac29b42910d0988cd0450a7be0ea7a410b9a36
</p>

**Review by peterblazejewicz — APPROVED** [review]
Sebastian, thanks!
At your discretion, LGTM!

**Comment by rschaufler** [comment]
I just updated to @types/react 18.0.13 and get the following error in my app where i also use @types/trusted-types:

```
[ ERROR ]  TypeScript: ./node_modules/@types/trusted-types/index.d.ts:14:11
           Cannot redeclare block-scoped variable 'TrustedHTML'.

     L13:  declare global {
     L14:      const TrustedHTML: typeof lib.TrustedHTML;
     L15:      type TrustedHTML = lib.TrustedHTML;

[ ERROR ]  TypeScript: ./node_modules/@types/react/global.d.ts:157:11
           Cannot redeclare block-scoped variable 'TrustedHTML'.

    L157:  interface TrustedHTML { }
```

It seems to be related to the change in this PR.

**Comment by peterblazejewicz** [comment]
@eppsilon sorry, I've missed this one is global. You've folks discussed this in the linked thread (impact of global symbols from trusted-types)

**Comment by eps1lon** [comment]
Shouldn't `TrustedHTML` be part of `lib.dom.d.ts`? Alternatively check out how `lib.dom.d.ts` works. Because `@types/react` creates a bunch of empty interfaces for DOM compat and these don't clash with `lib.dom.d.ts`

**Comment by peterblazejewicz** [comment]
IMO 'lib.dom.d.ts' uses this combos for class/interface to allow merging, this is why it works with others, say:
```ts
interface TouchList {
    readonly length: number;
    item(index: number): Touch | null;
    [index: number]: Touch;
}

declare var TouchList: {
    prototype: TouchList;
    new(): TouchList;
};
```
we could ask to  make a change in `trusted-types` to allow same (if I'm correct)

**Comment by eps1lon** [comment]
Proposed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61160 in the hopes we can reland this PR.

**Pull request merged**
