### PR TITLE
cropperjs - Added the methods: `zoomTo` & `rotateTo` and the event: `zoom`

### PR DESCRIPTION
**Pull request by Phoenix359**
Also changed the 6 events to have the correct (different) interface for the property: `detail`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15199
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by andy-ms** [comment]
Please fix the test failure.

**Comment by Phoenix359** [comment]
Apparantly the package `react-cropper` depends on `cropperjs` and fails if new methods are added to cropperjs. :(
It is fixed now :)

**Comment by andy-ms** [comment]
I added #15951 so you won't have do do that. Please merge `master` that into your branch once it's in.

**Comment by Phoenix359** [comment]
It is merged  now.

**Comment by andy-ms** [comment]
Thanks!

**Pull request merged**
