### PR TITLE
[RFC] Lodash flow better arguments

### PR DESCRIPTION
**Pull request by Strate**
I've tried to implement some overloads for `_.flow` function.
There is no unit tests, and no overloads for lodash object wrappers.
Mainly, I want you to give me a feedback about this. If it is acceptable, I'll add more overloads and write the tests.

The main reason to make thie change is to have a better type inferring:

``` typescript
import flow from "lodash/flow"

declare function f1(a: number): boolean;
declare function f2(a: boolean): string;
declare function f3(a: string): DOMElement;

let pipeline = _.flow(f1, f2, f3); // pipeline now have inferred type (a: number) => DOMElement
```

https://lodash.com/docs#flow

P.S. writing similar overloads is common case for Scala.

### CODE REVIEW

**Comment by vvakame** [comment]
Can I merge this PR?
We can't get response from authors. I'll merge this PR in 2 days. please ping me again.

**Comment by Strate** [comment]
@vvakame I want to make a little improvements on it, I hope it won't take more than 1-2 days.

**Comment by vvakame** [comment]
👍

**Comment by Strate** [comment]
@vvakame 
I've added tests, so, it could be merged now.

**Comment by stepancar** [comment]
:+1:

**Pull request merged**
