### PR TITLE
Fix echarts LineStyle color type error

### PR DESCRIPTION
**Pull request by fuhaiwei**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://echarts.apache.org/en/option.html#yAxis.splitLine.lineStyle.color
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by fuhaiwei** [comment]
@ruixuel 
@sheetalkamat

**Comment by tmtron** [comment]
Since a simple string and an array work, I suggest
```
interface LineStyle {
  color?: string | string[];
  ...
```

**Comment by fuhaiwei** [comment]
@tmtron 
Yes, you are right.
Fixed.

**Review by tmtron — APPROVED** [review]
looks fine now

**Pull request merged**
