### PR TITLE
chore: update `node-fetch` to use `form-data` v4.x

### PR DESCRIPTION
**Pull request by chohner**
Version 4 of `form-data` is [already 2.5 years old](https://github.com/form-data/form-data/releases) and using version 3 causes resolution conflicts with other packages.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by nikcorg — COMMENTED** [review]
I wonder if the better approach would be to replace the dependency with an internal shim or at the very least demote it to [a `devDependency`, like the node-fetch library](https://github.com/node-fetch/node-fetch/blob/v2.7.0/package.json#L66) has it.

The node-fetch v4 library is already in beta, which when released will make these types relevant for 2 major versions old tech.

**Comment by chohner** [comment]
Would you prefer downgrading to v3 (or even 2.3.3) and moving to `devDependencies`?

**Comment by nikcorg** [comment]
@chohner I don't really have a strong preference, but maybe matching the node-fetch library makes sense in some regard, how ever weird it seems to hold on to a really old version of the form-data library.

One potential issue with moving `form-data` to a `devDependency` that occurred to me, is that it is a direct build-time dependency of this library. But on the other hand, this entire thing is a `devDependency`, so I'm not sure what the correct course of action is.

Happy to give your PR an accept as is.

**Review by nikcorg — APPROVED** [review]

**Comment by chohner** [comment]
Cool, thanks for the quick input! I'm going to merge as-is, happy to adapt if others have strong opinions

**Review by gabritto — APPROVED** [review]

**Comment by chohner** [comment]
Ready to merge

**Pull request merged**
