### PR TITLE
Changed react-css-modules to have a default export

### PR DESCRIPTION
**Pull request by empz**
Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gajus/react-css-modules/blob/master/src/index.js#L50
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
Should be fine 👍

**Comment by andy-ms** [comment]
As I mentioned in #13406, `require("react-css-modules").default` is `undefined` using the node module loader with the NPM package. What distribution and what module loader are you using?

**Comment by emzero** [comment]
I'm using TypeScript 2.1.4 in a project based on [this template](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/ReactReduxSpa).

You won't see the `default` property when using node's require since that it's something related to the TS loader. I can't find the resource now, but TS adds that default property in some specific cases.

I can confirm this works, compiles and runs fine:
`import CSSModules from 'react-css-modules'` with my definition.

I can also confirm that the current version of the defintion doesn't work at runtime because it throws `CSSModules it not a function` (because the function lives in the default property).

**Comment by andy-ms** [comment]
To clarify, there is no "TS loader", only TS module resolver. That's only a compile-time thing and doesn't guarantee that it will work when you run it. What happens at runtime will depend on the real loader you use, such as node.js or require.js. So either you are using a different version of the library or you have some module loader which wraps libraries in in `{ default: foo }`.

**Comment by emzero** [comment]
Ok, I guess webpack is the loader then.

I'm using react-css-modules 4.1.0 which transpiled index.js ends with the following:
`module.exports = exports['default'];`

I guess that's where that default property is added. Not sure who is doing it though. Maybe webpack's ts-loader.

**Comment by andy-ms** [comment]
Actually, that line does the opposite: It takes a module with a "default" export and turns it into one directly exporting that.
If default imports work better for you after being compiled by webpack, you could turn on the `--allowSyntheticDefaultExports` compiler option.

**Pull request closed without merging**
