### PR TITLE
[material-ui] Add onKeyDown event on TextFieldProps interface

### PR DESCRIPTION
**Pull request by RemyJeancolas**
Add definition to support native React event: https://facebook.github.io/react/docs/events.html#keyboard-events

### CODE REVIEW

**Comment by zhengbli** [comment]
@ngbrown @herrmanno can you review the change?

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by RemyJeancolas** [comment]
@vvakame could you merge this PR please ?
If authors are not available it would be very useful from you.
Thanks.

**Comment by zhengbli** [comment]
👍

**Pull request merged**
