### PR TITLE
Create bootstrap-table.d.ts

### PR DESCRIPTION
**Pull request by talatbaig**
case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

### CODE REVIEW

**Comment by mhegazy** [comment]
CI test failing, need a `/// <reference path="../jquery/jquery.d.ts" />`

**Review by talatbaig — COMMENTED** [review]
added jquery

**Comment by mhegazy** [comment]
CI is still failing. it needs to be `/// <reference path="../jquery/jquery.d.ts" />` since this is on the master branch.

**Review by talatbaig — COMMENTED** [review]
updated reference

**Comment by mhegazy** [comment]
One more round, still missing the closing for the reference tag.

**Review by talatbaig — COMMENTED** [review]
updated!

**Comment by mhegazy** [comment]
thanks. waiting on CI server

**Comment by andy-ms** [comment]
Could you add some tests for this?

**Pull request merged**
