### PR TITLE
Update gulp-tslint to version 3.6.0

### PR DESCRIPTION
**Pull request by tkrotoff**
Improvements:
- Features all examples from [gulp-tslint README](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/README.md)
- Add options for the reporter (`ReportOptions`)
- Simplify gulp-tslint.d.ts: no need for a module inside another, a simple interface does it (`interface GulpTsLint`)
- Add a namespace so we can write `const tslintOptions: tslint.Options`, `const testReporter: tslint.Reporter`...

(I've taken on improving gulp-tslint definition because option `ReportOptions.summarizeFailureOutput` were not supported)

### CODE REVIEW

**Comment by tkrotoff** [comment]
btw (I did not fixed that, it should be fixed globally), it is written `// Definitions by: Asana <https://asana.com>` thus the "account can't be detected" by dt-bot.

A lot of definitions [have this](https://github.com/DefinitelyTyped/DefinitelyTyped/search?q=Asana+%3Chttps%3A%2F%2Fasana.com%3E) instead of a GitHub account (for gulp-tslint it should be @pspeter3)

**Comment by pspeter3** [comment]
We normally maintain the type definitions as a group. This looks good to me though

**Comment by vvakame** [comment]
thanks mate!

I want to improve https://github.com/DefinitelyTyped/dt-review-tool
e.g. account name converter, naming convention checker etc... but it can't do that now. :confounded:

**Comment by AyaMorisawa** [comment]
Thanks!

**Pull request merged**
