### PR TITLE
Add unist-util-is

### PR DESCRIPTION
**Pull request by Rokt33r**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

### CODE REVIEW

**Review by wooorm — APPROVED** [review]

**Review by ChristianMurphy — APPROVED** [review]

**Review by amcasey — APPROVED** [review]

**Comment by Flarna** [comment]
@Rokt33r Seems these definitions cause errors even CI was green in this PR. See #31177 
Would be nice if you could take a look what's wrong.

**Comment by Rokt33r** [comment]
@Flarna I don't think it is our fault. If the behavior is deprecated, we need to know what's the breaking change between `v3.2.*` and `@next` to fix the problem.

I leave a simpler version. (Typescript throws an error as intended because `this` type doesn't match.)
https://www.typescriptlang.org/play/index.html#src=function%20is%3CC%20%3D%20%7B%7D%3E(testFn%3A%20(this%3AC)%20%3D%3E%20boolean)%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TestContext%20%7B%0D%0A%20%20some%3A%20string%3B%0D%0A%7D%0D%0Afunction%20testWithContext(this%3A%20TestContext)%20%7B%7D%0D%0Ainterface%20OtherTestContext%20%7B%0D%0A%20%20some%3A%20number%3B%0D%0A%7D%0D%0Ais%3COtherTestContext%3E(testWithContext)%3B%0D%0A

**Comment by Flarna** [comment]
@Rokt33r I don't think that someone did anything wrong here. CI was green in this PR so seems the change was introduce later - most likely some change in typescript caused this.
I'm just not sure if the test should be improved or if this should be reported as problem in typescript repo.

**Comment by amcasey** [comment]
@Rokt33r, your reduced repro leaves out `Partial<Unist.Node>`, which I think is part of the problem:

https://www.typescriptlang.org/play/index.html#src=interface%20Node%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20unknown%3B%0D%0A%7D%0D%0A%0D%0Atype%20Test%3CC%3E%20%3D%20((p%3A%20C)%20%3D%3E%20void)%20%7C%20Partial%3CNode%3E%3B%0D%0A%0D%0Afunction%20is%3CC%3E(testFn%3A%20Test%3CC%3E)%20%7B%7D%0D%0A%0D%0Afunction%20testWithContext(p%3A%20string)%20%7B%7D%0D%0Ais%3Cnumber%3E(testWithContext)%3B%20%2F%2Ferror%3F%0D%0A

I'm still trying to figure out why the test run didn't catch it.

**Comment by amcasey** [comment]
It's failing locally, so my best guess is that a bug in dtslint was causing this failure to be missed and has recently been fixed.  Can you please submit a new PR updating the test?

**Pull request merged**
