### PR TITLE
[node-red] Definitions and documentation for Hooks API

### PR DESCRIPTION
**Pull request by Maiquu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodered.org/docs/api/hooks/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by alexk111** [comment]
@Maiquu Sorry for the delay. 

Could you keep the original format of the code. The format change breaks the code consistency between files.  And it's hard to review the proposed changes when every line of the code was modified.

**Review by alexk111 — CHANGES_REQUESTED** [review]
Could you keep the original format of the code. The format change breaks the code consistency between files.  And it's hard to review the proposed changes when every line of the code was modified.

**Review by alexk111 — CHANGES_REQUESTED** [review]
I've checked the Node-RED code and it looks like the hooks is located in `@node-red/util` module. Could you move the hooks definition to `@node-red/util`, rename `HooksModule` to `Hooks`, and import it into `@node-red/runtime` by adding `Hooks` to the `import { Util, Log, I18n } from '@node-red/util'` line.

**Comment by Maiquu** [comment]
Reasons behind some of the choices I made:
- I haven't included `clear` method because I don't think it should be public since `hooks` module is singleton.
- I haven't included `trigger` method because I wasn't sure if its meant to be a public API, since making custom hooks is not documented at all. And I'm not sure how to type the callback parameters (or the Promise resolve values). But I wouldn't mind pushing another commit and marking callback parameters as `unknown` to force user to do type assertion.
- Before my first pull request, I noticed that `hooks` were defined at `@node-red/util` module. However in official documents, they were not mentioned in [`util` API](https://nodered.org/docs/api/modules/v/1.3/@node-red_util.html) page but was categorized as [`Runtime APIs`](https://nodered.org/docs/api/). I wasn't sure if it was intentional or utility page is simple out of date, so I decided to place `hooks` definitions to `@node-red/runtime` section.

**Review by alexk111 — CHANGES_REQUESTED** [review]
I've found that Hooks can be accessed via the main Node-RED application (in the root `node-red` module: https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/lib/red.js#L178) and API provided to nodes (by the `createNodeApi` in the `@node-red/registry` module: https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/registry/lib/util.js#L70). 

Could you add `hooks:  util.Hooks;` in the root module definition right after `events` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-red/index.d.ts#L69) and add a test for the hooks link  below `events` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-red/node-red-tests.ts#L28).

Then add `hooks: util.Hooks` in the `@node-red/registry` module in the `NodeAPI` interface after `events` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-red__registry/index.d.ts#L133). And add a test for the hooks link in the `nodeAPITests` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-red__registry/node-red__registry-tests.ts#L19).

**Comment by alexk111** [comment]
> * I haven't included `clear` method
> * I haven't included `trigger` method

Thanks for the clarification. I agree that there is no need to include definitions for every Node RED thing, especially if it's not documented or when not sure if it's meant to be a public API.

>Before my first pull request, I noticed that `hooks` were defined at `@node-red/util` module. However in official documents, they were not mentioned in [`util` API](https://nodered.org/docs/api/modules/v/1.3/@node-red_util.html) page but was categorized as [`Runtime APIs`](https://nodered.org/docs/api/). I wasn't sure if it was intentional or utility page is simple out of date, so I decided to place `hooks` definitions to `@node-red/runtime` section.

The structure of Node-RED typedefs tries to reflect the structure of the Node-RED codebase. If something is defined in `@node-red/util` then the type definitions are also located in `@node-red/util`.

> 
> Regardless, I pushed the changes you requested. Would like to hear your thoughts on the first 2 methods i mentioned. Thanks for your attention.

**Review by alexk111 — APPROVED** [review]
Awesome! Looks good to me.
Thanks!

**Review by andrewbranch — APPROVED** [review]

**Comment by Maiquu** [comment]
Ready to merge

**Pull request merged**
