### PR TITLE
Definitions for ydn-db

### PR DESCRIPTION
**Pull request by gabrielmaldi**
I took an [existing](https://github.com/yathit/ydn-db/blob/master/misc/ydn.db-1.0.ts) definitions file and had to modify it for it to compile; so I submitted a pull request with those changes to the original repo: https://github.com/yathit/ydn-db/pull/74
I don't know if I should also add my name to the header.

### CODE REVIEW

**Comment by enanox** [comment]
AFAIK, I think you could add your name after the creator of the definitions, @vvakame correct me if I'm wrong.

**Comment by gabrielmaldi** [comment]
Thank you, @enanox, I did just that.

**Comment by vvakame** [comment]
@yathit can I merge this PR?
I wonder if no problems about license?

**Comment by yathit** [comment]
Sure. Thanks. Please keep your name since you are last maintainer. I have yet to use TypeScript yet.

**Comment by vvakame** [comment]
@yathit :+1: 
@gabrielmaldi thanks mate!

**Pull request merged**
