### PR TITLE
Add lodash _.partition

### PR DESCRIPTION
**Pull request by splintor**
Add t.ds definition for lodash _.partition method

### CODE REVIEW

**Comment by vvakame** [comment]
*lodash/lodash.d.ts*

to authors(@bczengel @chrootsu). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by chrootsu** [comment]
@splintor I think, all signatures where collection type is Array<T> is not needed because type T[] is assignable to type List<T>. And all variants of method in LoDashStatic returns T[][], not T.

Also missing tests and some signatures in other wrappers, but I'll add them after merge the PR.

**Comment by splintor** [comment]
@chrootsu I just wanted to add the partition method, and tried to mimic existing methods. I don't currently have time to deal with it. Can you please add the missing parts?
Thanks!

**Comment by chrootsu** [comment]
@splintor ok )

**Comment by chrootsu** [comment]
@vvakame :+1: Now it looks good to me ^_^

**Comment by vvakame** [comment]
@chrootsu thanks!
@splintor thanks mate!

**Pull request merged**
