### PR TITLE
[@types/billplz] added TypeScript 2.0 type definitions for node-billplz

### PR DESCRIPTION
**Pull request by Akim95**
Please fill in this template.
- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Run `tsc` without errors.
- [x] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

### CODE REVIEW

**Comment by andy-ms** [comment]
Failing tests here are OK, they are fixed by #12344.

**Comment by andy-ms** [comment]
Why not directly [bundle](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) typings in the [repository](https://github.com/suhz/node-billplz)?

**Comment by Akim95** [comment]
Maybe I'll sent a pull request to that repo for the next release. I need to discuss first. 👍

**Comment by vvakame** [comment]
We recommend to talking first in that repository.
Do you hope to merge this PR?

**Comment by Akim95** [comment]
I think we can hold this pull request until I done with that repository. 🚶

**Comment by Akim95** [comment]
This type definition already merged with npm package itself.

**Comment by andy-ms** [comment]
Thanks! By the way, the definition header is no longer needed. The TypeScript compiler ignores those; they are only for use by DefinitelyTyped.

**Comment by Akim95** [comment]
Ok, I'll remove it later.

**Pull request closed without merging**
