### PR TITLE
[spotify-api] fix typos in type names

### PR DESCRIPTION
**Pull request by schl3ck**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by schl3ck** [comment]
@skovmand @Stadly @piksel @Some-Dood I wanted to fix the typo in `...Reponse` of some types but [`spotify-web-api-node`](../tree/master/types/spotify-web-api-node) depends on it. Should I change that package too or ignore the typo?

**Comment by piksel** [comment]
You probably shouldn't rename public interfaces (breaking change). You could add type aliases for the typo:d ones.

**Comment by schl3ck** [comment]
Thanks for the reply @piksel! I've restored the old types and marked them with `@deprecated`. Is this better?

**Comment by Stadly** [comment]
Looks good to me :)

**Review by Stadly — APPROVED** [review]

**Comment by schl3ck** [comment]
Ready to merge

**Pull request merged**
