### PR TITLE
node: revert `node:` prefixed modules

### PR DESCRIPTION
**Pull request by SimonSchick**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Revert of #51107 as discussed we should bring this back once https://github.com/microsoft/TypeScript/issues/42764 has matured.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
Note that I’d prefer if we tried moving the `node:`‑prefixed module names after the unprefixed forms before doing this.

**Comment by SimonSchick** [comment]
I tried this previously but saw no change on resolve order based on declaration order but you're welcome to check this yourself.

Furthermore I think it would make more sense to wait for official support for module aliases from the TS team, the `node:` protocol seems pretty nieche at this point (and appears to be starting to fragment import names as seen in my PR diff, although this is likely due to import resolve order).

**Review by 0xTheProDev — APPROVED** [review]
+1 for Lighting FS changes. 💯

**Review by G-Rath — APPROVED** [review]

**Review by SachinShekhar — APPROVED** [review]

**Comment by karlhorky** [comment]
@SimonSchick @elibarzilay  Uh, is this supposed to cause applications using these prefixes to break on a minor upgrade of the types (`@types/node` `14.14.43` -> `14.14.44`)? 😫

This is causing errors:

```
Error: packages/content-items/index.ts(1,36): error TS2307: Cannot find module 'node:fs/promises' or its corresponding type declarations.
Error: packages/is-html-equal/index.ts(1,31): error TS2307: Cannot find module 'node:module' or its corresponding type declarations.
Error: packages/server/config.ts(1,31): error TS2307: Cannot find module 'node:path' or its corresponding type declarations.
Error: packages/server/config.ts(2,31): error TS2307: Cannot find module 'node:url' or its corresponding type declarations.
Error: packages/server/index.ts(1,18): error TS2307: Cannot find module 'node:path' or its corresponding type declarations.
```

These were working just fine before.

**Comment by karlhorky** [comment]
Since the `node:` prefix will be also backported to Node.js v14, seems like it should not be removed from the types.

**Comment by rbuckton** [comment]
As someone who has used these type definitions in the last week and auto-imports of the `node:` prefixed-versions causing crashes at runtime, I definitely believe this should be removed *until* it has been backported to Node.js v14's CommonJS support.

**Comment by karlhorky** [comment]
@rbuckton is there an approach that would achieve both? All 3 of:

1. the `node:` definitions stay in
2. the non-prefixed versions also stay there
3. the non-prefixed versions are the versions that are auto-imported (no user configuration for now)

Or is this https://github.com/microsoft/TypeScript/issues/42764 ?

**Comment by karlhorky** [comment]
@rbuckton @SimonSchick What about the following as a temporary solution:

Release `@types/node@16.0.0` with the contents at `15.0.1`

Then Node 16 users who want to use the prefixes still have a latest major version that they can install (which also matches the Node version number).

**Comment by karlhorky** [comment]
Update: there is now a PR for Node v16: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52594

Hopefully the `node:` prefixes will be reintroduced over there.

**Comment by karlhorky** [comment]
So looks like the `node:` scheme / prefix was backported to Node.js 14.13.1 / 12.20.0 🎉

https://nodejs.org/api/esm.html -> link "node: Imports" (links with anchors don't scroll properly right now)

Screen Shot 2021-05-30 at 11 04 39

**Comment by karlhorky** [comment]
So maybe now this "revert" PR can be reverted and the feature can be back :)

**Comment by BenSjoberg** [comment]
It's supported when outputting to ESM, but not to CommonJS. That was the issue I (and I think most others) had with the `node:` prefixes - TypeScript was auto-completing them, then outputting CommonJS that didn't work.

In Node 16 `require('node:fs')` works, but it looks like it still doesn't in 14.17.0.

**Comment by karlhorky** [comment]
> In Node 16 `require('node:fs')` works, but it looks like it still doesn't in 14.17.0.

Ah, good point! Didn't catch this detail.

**Comment by karlhorky** [comment]
`@types/node@16.0.0` has been published now - the `node:` schema / prefix now works again:

- https://www.npmjs.com/package/@types/node
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53669

**Pull request merged**
