### PR TITLE
remove 'history' as of 5.0.0

### PR DESCRIPTION
**Pull request by martin-badin**
https://github.com/remix-run/history/releases/tag/v5.0.0
https://github.com/remix-run/history/blob/dev/packages/history/package.json#L10

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test history`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by martin-badin** [comment]
@peterblazejewicz Do I need to remove the v4 if is it still used? It would be better to move the old types under the v4 folder?

**Comment by peterblazejewicz** [comment]
please run `npm run not-needed -- <typingsPackageName> <asOfVersion>`. This will remove sources. Types (@types/history *.3., *.4) are already published to NPM. The react router using older version is also already in newer major version. v4 was updated 2 years ago:
https://github.com/remix-run/history/tree/v4/docs

**Comment by martin-badin** [comment]
> please run `npm run not-needed -- <typingsPackageName> <asOfVersion>`. This will remove sources. Types (@types/history *.3., *.4) are already published to NPM. The react router using older version is also already in newer major version. v4 was updated 2 years ago: https://github.com/remix-run/history/tree/v4/docs

I can't because I got this error
`Cannot find module 'node:fs'`

**Comment by peterblazejewicz** [comment]
you can:
- update `react-router`, removing old v2, v3 (but that would require additional approvals). I looks react router v3 was updated a year ago
- or, create request to add '@types/history' to allowed packages, so v3 can be aliased in `react-router/v3`
I

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mirrorx ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mirrorx@latest/))
was missing the following properties:
1. Switch
1. Switch
## react-albus ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-albus@latest/))
was missing the following properties:
1. wizardShape
1. wizardShape
## react-router-redux ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-router-redux@latest/))
was missing the following properties:
1. getLocation
1. getLocation
## redux-first-router ([<kbd>unpkg</kbd>](https://unpkg.com/browse/redux-first-router@latest/))
was missing the following properties:
1. getOptions
1. addRoutes
1. ADD_ROUTES
1. getOptions
1. addRoutes

<details>
<summary>as well as these 1 other properties...</summary>
<p>ADD_ROUTES</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9b3d7d34b96d4ea26e82387fd80d059b103c916
</p>

**Comment by martin-badin** [comment]
re-ping @peterblazejewicz @johnnyreilly

**Review by peterblazejewicz — APPROVED** [review]

**Comment by martin-badin** [comment]
Ready to merge

**Pull request merged**
