### PR TITLE
Updated onChange parameters to include selection key

### PR DESCRIPTION
**Pull request by charliemday**
The `onChange` parameters seem to be missing the `selection` key. 

Further example links in the react-date-range docs indicating that we should be expecting the `onChange` parameters to be something like

```
     {
       selection: {
         startDate: [native Date Object],
         endDate: [native Date Object],
       }
     }
```

See: 
- https://github.com/hypeserver/react-date-range#daterangepicker--daterange
- https://github.com/hypeserver/react-date-range#daterangepicker--daterange

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by Curzy — APPROVED** [review]
LGTM :+1:

can you add type with onChange(date: [native Date object]) case in this pr or new?

https://github.com/hypeserver/react-date-range#datepicker

**Comment by DevsAnon** [comment]
Please fix tests

**Review by DemetriouJohn — CHANGES_REQUESTED** [review]
Please fix tests

**Comment by charliemday** [comment]
@DevsAnon tests fixed
@Curzy have added `Date` to the `OnChangeProps`

**Review by Curzy — APPROVED** [review]

**Review by DemetriouJohn — APPROVED** [review]

**Comment by DevsAnon** [comment]
Ready to merge

**Pull request merged**
