### PR TITLE
[sinon] Correct comparable type

### PR DESCRIPTION
**Pull request by JimiC**
Typescript complains for functions `calledBefore`, `calledAfter`, `calledImmediatelyBefore` and `calledImmediatelyAfter` because it's trying to compare a `SinonInspectable` to a `SinonSpy`. Correct comparison should be done on the same type (i.e. `SinonInspectable`).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Review by nicojs — CHANGES_REQUESTED** [review]
Thanks @JimiC 

Could you add a test for this? I guess this enables something that wasn't possible before. By adding a test, you'll help prevent regression later on.

**Review by SimonSchick — APPROVED** [review]

**Comment by JimiC** [comment]
Let me explain the use case I faced and why I'm proposing this change.

In a project that targets `ts v3.3.4000` I have code that looks like this:
```
    const spy1 = sinon.spy(Class1, 'method1');
    const spy2 = sinon.spy(Class1, 'method2');
    expect(spy1.calledBefore(spy2)).to.be.true;
```
Now `ts` infers:
- `spy1` as `sinon.SinonStub<[type1, (type2 | undefined)?], void>`
- `spy2` as `sinon.SinonStub<[type1, type2], void>`

but when you hover over `spy1` in line 3 (the `expect` one) `ts` infers `spy1` as `sinon.SinonInspectable<[type1, (type2 | undefined)?], void>` (although `SinonStub` extends `SinonInspectable`) in order to call the `calledBefore` function and presents a red squiggly under `spy2` which now is infered as `sinon.SinonStub<any[], any>`. `ts` complains that `sinon.SinonStub<[type1, type2], void>` can't be assigned to `sinon.SinonStub<any[], any>`.

If I cast `spy2` to `SinonInspectable` or if I switch the parameter type of `calledBefore` to `SinonInspectable`, `ts` is happy.

I tested that this proposed change does not affect if you use:
```
    const spy1 = sinon.spy(); // sinon.SinonStub<any[], any>
    const spy2 = sinon.spy(); //`sinon.SinonStub<any[], any>
    expect(spy1.calledBefore(spy2)).to.be.true;
```

If you look in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sinon/index.d.ts you will notice that `calledBefore` is a member of `SinonSpy` and thus having the parameter type of `calledBefore` as `SinonSpy` makes perfect sense. But in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sinon/ts3.1/index.d.ts `calledBefore` is a member of `SinonInspectable` and thus the parameter type of `calledBefore` and the other related functions owe to be of the same type i.e. `SinonInspectable` .

A test case that demonstrates this could be added for `methodSpy` and `methodSpy2` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sinon/ts3.1/sinon-tests.ts#L390) like 
```
    methodSpy.calledBefore(methodSpy2);
    methodSpy.calledAfter(methodSpy2);
    methodSpy.calledImmediatelyBefore(methodSpy2);
    methodSpy.calledImmediatelyAfter(methodSpy2);
```

Because I'm not curently on my development workstation, I'll have to came back to you for that later.

**Review by nicojs — APPROVED** [review]
Thanks for the clarification and tests. Looks awesome now 👍

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Pull request merged**
