### PR TITLE
Update meteor.d.ts

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
added missing property `profile` on `LoginWithExternalServiceOptions`
added more details to `interface EmailFields`
added more details to `function validateLoginAttempt`

### CODE REVIEW

**Comment by fullflavedave** [comment]
These changes look good and should be merged.

Is the addition of `profile` on `LoginWithExternalServiceOptions` for the Meteor 1.3 release that is still in beta?  If so, I guess it's fine to have it in there since it won't cause issues for Meteor 1.2 and 1.3 will probably be officially released in the next month or so.

**Comment by DmitryEfimenko** [comment]
The addition of `profile` property on `LoginWithExternalServiceOptions` is due to this [piece of documentation](http://docs.meteor.com/#/full/accounts_oncreateuser). See example.

**Comment by horiuchi** [comment]
@DmitryEfimenko Thanks mate!
@fullflavedave Thanks for review!

**Comment by DmitryEfimenko** [comment]
This was never merged :(

**Comment by fullflavedave** [comment]
Which code is missing?  

In the latest version, I can see that: 
- `Meteor.LoginWithExternalServiceOptions` contains the `profile` property
- `Meteor.EmailFields` contains the updated definitions for properties `subject`, `text`, and `html`
- `Accounts.validateLoginAttempt` has an updated callback that takes the parameter of type `Accounts.IValidateLoginAttemptCbOpts`.

Am I missing something?

**Comment by DmitryEfimenko** [comment]
oh, indeed. But then how come this pull request is still open? Would not it be closed when it was merged?

**Comment by fullflavedave** [comment]
@horiuchi Could you please close this PR?

**Comment by horiuchi** [comment]
OK, closed this PR.

**Pull request closed without merging**
