### PR TITLE
KaTeX v0.14+ exports a default object instead of named exports

### PR DESCRIPTION
**Pull request by jameshfisher**
See https://github.com/KaTeX/KaTeX/blob/main/CHANGELOG.md or try using KaTeX with these definitions

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by Stefaans** [comment]
Thank you @jameshfisher for addressing this!

With regards your _export default_ solution:
`export default {TrustContext, KatexOptions, ParseError, render, renderToString};`

TSLint complains that "TS2749: 'katex.KatexOptions' refers to a value, but is being used as a type here." It would seems like one cannot mix interfaces with classes in the default.

When I export the interfaces seperately, all works fine for me:
`export default {render, renderToString};`
`export {TrustContext, KatexOptions, ParseError};`

The import in my app then looks as follows:
`import katex, { KatexOptions } from 'katex';`

**Comment by percy507** [comment]
Why this PR closed? Current type declaration of katex really need improve.

Anyone review this PR?

**Comment by sapphi-red** [comment]
@percy507 #59525 covers this change.

**Comment by percy507** [comment]
@sapphi-red That PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59525) seems for `0.14.0` version. But for the newest version (`0.16.0`), current type breaks.

You can check the [source code](https://github.com/KaTeX/KaTeX/blob/main/katex.js).

**Pull request closed without merging**
