### PR TITLE
Mongodb - Revert #46863

### PR DESCRIPTION
**Pull request by Xstoudi**
This reverts commit 6a3556a1bc18bc2650612009011e5f0df4533125.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #48300
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongodb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongodb@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'mongodb'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 548ba5d5388098ca3b2a71f33d1fb0d60c303d70
</p>

**Comment by xamgore** [comment]
Why?

**Comment by Xstoudi** [comment]
Please take a look at the Typescript Playground attached to the issue linked above.

**Comment by Celend** [comment]
I think the key problem is the `find` and `findOne` methods allows override the collection type `TSchema`.

**Comment by HitkoDev** [comment]
@Celend If you use `projection`, return type doesn't have to be the same as collection type. That's why there's an option to override the type with each find.

**Comment by Celend** [comment]
@HitkoDev Currently I have no idea how to fix the problem without remove the override type, could you please have any suggestions?

**Comment by HitkoDev** [comment]
One option is for users to write 

```ts
const options: FindOneOptions<T extends TSchema ? TSchema : T> = { ... };
```

The above solves the type resolution when using current typings in code.

**Pull request closed without merging**
