### PR TITLE
[mapbox-gl-draw] Add missing properties to DrawFeature and DrawCustomModeThis

### PR DESCRIPTION
**Pull request by yukiyokotani**
## DrawFeature
- Add missing properties: `id` and `type` to DrawFeature. 
  cf. https://github.com/mapbox/mapbox-gl-draw/blob/8f935fd652747b3f3ff946a8c8c7d88c64fb3c1d/src/feature_types/feature.js#L4
- DrawFeature’s `type` is limited to six types: `Point`, `LineString`, `Polygon`, `MultiPoint`, `MultiLineString`, and `MultiPolygon`.
  cf. 
  - https://github.com/mapbox/mapbox-gl-draw/blob/main/src/modes/mode_interface_accessors.js#L190
  - https://github.com/mapbox/mapbox-gl-draw/blob/main/src/feature_types/multi_feature.js#L26
  - [mapbox-gl-draw | API Methods](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#api-methods)
- Fix `coordinates` type definition. It is possiblly an array of `Position` depending on the feature type.  
  cf. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts#L124

## DrawCustomModeThis
- Add missing properties: `map` and `drawConfig` to DrawCustomModeThis.  
  cf. https://github.com/mapbox/mapbox-gl-draw/blob/main/src/modes/mode_interface_accessors.js#L8

=======================================

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by Shayan-To** [comment]
@yukiyokotani I have a PR pending review (#62790) that adds different sub-types of `DrawFeature` (plus some other fixes). I took a quick look at your PR, and the only thing I found that mine has missing is adding `drawConfig` to `DrawCustomModeThis`. Take a look at it and see if it can work for you.

**Comment by yukiyokotani** [comment]
@Shayan-To 
Sorry, I had missed that pull request. It seems to match what I was looking for. 
The property definitions are more detailed than mine, and I like that the `DrawFeature` is defined by a discriminated union.
Could you add `drawConfig` to `DrawCustomModeThis`? Then I will withdraw this pull request.

**Comment by Shayan-To** [comment]
I think that if I edit my PR, it will make the review process take longer. If you look at the previous PRs for this package, most of them took nearly a month to be reviewed.

If my assumption is wrong and editing the PR won't prolong the review process, I'd be glad to edit it to include `drawConfig`. Otherwise, I suggest we wait for my PR to be merged, so I'm added as an owner for the package. Then you can open a PR to add `drawConfig` and it can be reviewed quickly.

**Comment by yukiyokotani** [comment]
OK, I'll do that.

**Pull request closed without merging**
