### PR TITLE
Add counterpart

### PR DESCRIPTION
**Pull request by santiagodoldan**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

### CODE REVIEW

**Comment by santiagodoldan** [comment]
I don't know how to represent these 2 properties -> https://github.com/martinandert/counterpart/blob/master/index.js#L397-L398

**Comment by santiagodoldan** [comment]
Just fixed the CI

**Comment by minestarks** [comment]
You may prefer this version which uses an interface, which also lets you add the 2 properties from your comment above

```ts

type NotFoundHandler = (locale: string, key: string, fallback: string, scope: string) => void;
type LocaleChangeHandler = (newLocale: string, oldLocale: string) => void;

interface Counterpart {
    (key: string|string[], options?: object): string;

    setSeparator(value: string): string;
    onTranslationNotFound(callback: NotFoundHandler): void;
    offTranslationNotFound(callback: NotFoundHandler): void;
    setMissingEntryGenerator(callback: (value: string) => void): void;
    getLocale(): string;
    setLocale(value: string): string;
    onLocaleChange(callback: LocaleChangeHandler): void;
    offLocaleChange(callback: LocaleChangeHandler): void;
    setFallbackLocale(value: string|string[]): void;
    registerTranslations(locale: string, data: object): void;
    registerInterpolations(data: object): void;
    setKeyTransformer(callback: (value: string, options: object) => string): string;
    localize(date: Date, options: object): string;
    Instance: Counterpart;
    Translator: Counterpart;
}

declare var counterpart: Counterpart;

export = counterpart;
```

**Comment by santiagodoldan** [comment]
@minestarks thanks for the help, I tried several times using an interface without lucky, I didn't know how to represent these 2 cases

```
counterpart('translation.to.be.used');
counterpart(['translation', 'to', 'be', 'used']);
```

Lemme know if I need to change anything else

**Pull request merged**
