### PR TITLE
[@wordpress/core-data] Move Schema from api-fetch

### PR DESCRIPTION
**Pull request by sarayourfriend**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/WordPress/gutenberg/issues/30536>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I don't really understand why moving these types would introduce such a significant performance regression.

**Comment by amcasey** [comment]
@sarayourfriend the perf numbers don't make a lot of sense to me either.  My guess would be that enough code moved to change the average behavior, but that suggests that some files should have gotten faster.  I'll close and re-open to re-retrigger the benchmarks.

The change seems sensible to me, but it would be great to get some owner sign-off.

**Comment by sarayourfriend** [comment]
Thanks @amcasey, I'll wait for a maintainer review 🙂

**Review by dsifford — APPROVED** [review]
I'm sort of removed from this project as of recently and have been spending significantly less time following what's going on behind the scenes, but this looks fine to me and seems reasonable.

**Comment by sarayourfriend** [comment]
Ready to merge

**Pull request merged**
