### PR TITLE
[fix]fix animation type issue

### PR DESCRIPTION
**Pull request by iammvp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: none
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by joshuajeschek — CHANGES_REQUESTED** [review]
Hey, could you provide documentation that explains the changes you made?
This is the second last item to on the checklist in the PR template.

Also, I wonder why these definitions were made under `hummer-env`, while they should be under `Hummer`, since they are for the project `didi/Hummer`.

Thanks a lot for clarifying these issues.

**Comment by iammvp** [comment]
> Hey, could you provide documentation that explains the changes you made? This is the second last item to on the checklist in the PR template.
> 
> Also, I wonder why these definitions were made under `hummer-env`, while they should be under `Hummer`, since they are for the project `didi/Hummer`.
> 
> Thanks a lot for clarifying these issues.


This PR fixed two issues: 1. the value of position animation could be 'number' or 'string', it was 'number' only previously. 2. the value of animation event should be 'start' and 'end', it was 'on' and 'off'.  Can I ask what is the proper way to add changes? I was try to add a change log file into hummer-env folder, it can not pass the 'npm run test'

I use `hummer-env` because `Hummer` is used by others.

**Comment by joshuajeschek** [comment]
Adding changes via a PR is enough, git documents the change history.

Normally you would put a link to the relevant code / documentation, to make it easier for the reviewers

afaik, if "Hummer" is already used by someone else, you would add the name of the owner, like on npm it would sometimes be something like "@didi/Hummer", while that would mean on DefinitelyTyped: "didi__Hummer"
At least I saw some other people do it like this.

Also, where do you need these types? (Which npm install do you do?)

**Comment by iammvp** [comment]
> Adding changes via a PR is enough, git documents the change history.
> 
> Normally you would put a link to the relevant code / documentation, to make it easier for the reviewers
> 
> afaik, if "Hummer" is already used by someone else, you would add the name of the owner, like on npm it would sometimes be something like "@didi/Hummer", while that would mean on DefinitelyTyped: "didi__Hummer" At least I saw some other people do it like this.
> 
> Also, where do you need these types? (Which npm install do you do?)

This type definition is for '@Hummer'. '@Hummer' will not publish to NPM because it's a native(iOS/Android) render library which can use JS/TS to render the native page. And '@Hummer' injects serval global APIs to JS engine, this definition is for those APIs. '@types/hummer' is used by someone else and it has nothing to do with '@Hummer'. We had to choose another name which is 'hummer-env'.

**Comment by joshuajeschek** [comment]
alright. I just found it peculiar that the name would be hummer-env, not really intuitive :)
the content of the PR is fine tho!

**Review by joshuajeschek — APPROVED** [review]

**Comment by iammvp** [comment]
Ready to merge

**Pull request merged**
