### PR TITLE
[chrome] chrome.downloads namespace reviewed

### PR DESCRIPTION
**Pull request by fredrikhr**
Introduced Literal String enumeration Types where applicable
ref.: https://developer.chrome.com/extensions/downloads

### CODE REVIEW

**Comment by aozgaa** [comment]
Can you also add a test referencing these literal types?

**Comment by couven92** [comment]
Yes of course, bear with me... (Sorry for neglecting that in the first place)
Ref.: #14550 #14552 #14553 #14554 14555

**Comment by anubmat** [comment]
@couven92 , I'm not sure why do you have 6 different PRs modifying the same d.ts file. Can you merge these PRs into one? Because if I start merging these, there is a possibility of merge conflicts. As far as I see, if the intent of each of these PRs is different, you might want to list all your changes in the description here. If you really want to be more specific, you could have your changes as separate commits in the same PR. Also please close other PRs as you keep combining them.

**Comment by couven92** [comment]
@anubmat True. If you look at `chrome.d.ts` you'll see that it is full of doucmentation comments... Well, I was the primary culprit for that. And when I did that work with copying the Chrome API docs into the doc comments in TS I made a HUGE PR and people complained about it...

But I agree... I will close all PRs and create one big PR instead.

**Comment by anubmat** [comment]
@couven92 , thanks so much!
In case someone complains again that it is a huge PR, you can surely ask them to review one commit at a time.. :)

**Pull request closed without merging**
