### PR TITLE
wavesurfer.js: add plugins + update to 4.6

### PR DESCRIPTION
**Pull request by caugner**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://wavesurfer-js.org/api/index.html
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by yorkxin** [comment]
Hi,

Thanks for adding these types.

I'm trying to use these types in my TypeScript project. Specifically, it uses the regions plugin.

I found that the types in this patch does not include region methods generated by the plugin, such as `wavesurfer.addRegion()`. It also does not include plugin methods such as `regions.add()`. They can compile but they are `any` type.

I am not familiar with `d.ts` so I am not sure what's the best way to solve this, but would you mind take a look into those use cases?

Thanks 🙇

**Comment by caugner** [comment]
@yorkxin What version of Wavesurfer.js are you using and how do you import the regions plugin?

I have added `Wavesurfer.addRegion()` here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba41ea8e0d1b5a70d27f1aa01474b3b67ad88bbc/types/wavesurfer.js/src/plugin/regions.d.ts#L14-L20

But I must have missed the `RegionsPlugin`'s instance methods. Will add them asap.

**Comment by yorkxin** [comment]
@caugner I'm using wavesurfer 4.6.0 so it should match the version you're using.

I have seen those methods being defined in `regions.d.ts` of your patch, but TypeScript doesn't seem to realize it.

When I hover the mouse pointer over the following test code (modified your patch 🙂 ) it shows `any`

```
const waveSurferWithRegionsPlugin = WaveSurfer.create({
    container: "#waveform",
    plugins: [RegionsPlugin.create({})],
});
waveSurferWithRegionsPlugin.addRegion() // addRegions is "any"
waveSurferWithRegionsPlugin.regions.destroy(); // regions is "any"
```

Unfortunately I don't have enough experience to figure out what's the correct way to define this type.

**Comment by caugner** [comment]
Okay, so according to https://stackoverflow.com/a/23225358, declared classes cannot be extended in TypeScript.

The only way to add `addRegion()` etc. to `WaveSurfer` would be to convert `WaveSurfer` to an interface. Interfaces, however, don't support constructors and static properties. 😦

**Comment by yorkxin** [comment]
What about combining all interfaces into one file?

When I try to figure out how to use wavesurfer in TypeScript, in addition to your patch (it came just in time, thanks again), I also found that wavesurfer's API is not module friendly. Specifically:

- The doc encourages you to `import "wavesurfer.plugin.regions"` which seems to insert some methods into `wavesurfer` class.
- If we insist to use `import "wavesurfer.js/src/plugins/regions"` that means we have to interact with the regions plugin instance (not initialized by `regions.create`; it only returns a factory), rather than `wavesurefer.addRegions()` which is documented.

I'll maybe try some different approaches by myself, such as `declare module "wavesurefer.plugins.regions"` but I have no idea how to describe `wavesurefer.addRegion()` method that's injected by the plugin in the runtime.

**Comment by caugner** [comment]
I had a look at how Vue achieves this: https://github.com/vuejs/vue/blob/e7baaa12055231c9367fa1c7bf917e534bd8a739/types/vue.d.ts

They define the instance as `interface Vue` and the "static" methods as `interface VueConstructor` and they `export const Vue: VueConstructor`. This pattern should also work here, but it will require some refactoring.

**Comment by caugner** [comment]
Okay, so I had a go at rewriting everything to `interface`s, splitting constructor interfaces apart, but it turns out `DefinitelyTyped` doesn't allow you to extend an interface declared in the same package.

In other words: If we want to declare those plugin methods on the `WaveSurfer` instance, we have to do so centrally. Argh.

**Comment by caugner** [comment]
For now, I have added the missing `RegionsPlugin` methods and properties in 5e5fa279d9ea1ba0325e9a242755bfb43afac58f.

**Comment by caugner** [comment]
@yorkxin I have now added the plugin instance properties directly to the WaveSurfer interface in 88014e9 .

This should suffice for now, but we can always improve the typings later.

Please take the time to review this PR and give it an approval, as otherwise it won't be merged by the DefinitelyTyped bot / a TypeScript team member.

**Comment by yorkxin** [comment]
@caugner thanks! It satisfies my need for my project now. If I found anything missing, I'll make a pull request.

Regarding review, I am actually just a random user. I don't have permission to approve this pull request. Maybe those mentioned by the bot owner can take a look? @higuri @kubk @bennordgengo 

By the way, I am not sure how `d.ts` versioning works, but will this change break existing code that uses wavesurfer.js 3.x ? (I suppose it's already not up-to-date so probably not a big deal)

**Comment by caugner** [comment]
@yorkxin Actually everyone can review and approve PRs on GitHub, you don't need to be a team member or contributor. This repository is highly automated via @typescript-bot, which will change the status of this PR as soon as *anyone* has approved the PR. That's why it would be helpful to get a review even from you as "a random user". 😉 

Once this PR is merged, a new version of [`@types/wavesurfer.js`](https://www.npmjs.com/package/@types/wavesurfer.js) will be released, probably `4.6.0` (equal to the `wavesurfer.js` version referenced at the top of the `index.d.ts`). This won't have any effect on users already using this package in their project, as long as they don't update this dependency (which should only improve type inference anyways).

**Review by yorkxin — APPROVED** [review]
:shipit:

**Comment by yorkxin** [comment]
@caugner you're right. Thanks for pointing out! Let's keep improving this :)

**Comment by caugner** [comment]
@typescript-bot Ready to merge

**Comment by caugner** [comment]
Ready to merge

**Comment by alastair** [comment]
Thanks @caugner! I started to work on these for another project a few months ago but didn't get them to the stage of being published. This saves me the work of completing my interfaces, much appreciated!

**Pull request merged**
