### PR TITLE
[angular] Add types for AngularJS $aria service.

### PR DESCRIPTION
**Pull request by chivesrs**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See very bottom of this comment
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

`$aria` is an AngularJS service that is a little bit hard to find working documentation for. Nonetheless, here are some links below. You probably don't care too much about them, instead first I'll show you a working code definition that you can paste into https://angularjs.org in the JS console. First line loads `ngAria` script (it's not built into main AngularJS, but it is a code library), second line instantiates the service and uses it.

```
s = document.createElement('script'); s.src = "https://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular-aria.js"; document.getElementsByTagName('head')[0].appendChild(s);

i = angular.injector(); i.loadNewModules(['ngAria']); aria = i.get('$aria'); console.log(aria); console.log(aria.config('tabindex')); console.log(aria.config('ariaInvalid'));
```

Now for some documentation/source code:
https://docs.angularjs.org/api/ngAria
https://docs.angularjs.org/guide/accessibility
https://github.com/angular/angular.js/blob/master/src/ngAria/aria.js#L97
https://docs.angularjs.org/api/ngAria/provider/$ariaProvider#config
https://github.com/angular/angular.js/blob/master/src/ngAria/aria.js#L205

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@chivesrs 
Is this for separate package? Should it constitute its own declaration then?
https://www.npmjs.com/package/angular-aria

**Comment by chivesrs** [comment]
That's a good question. Something like angular-material I agree should be its own package, because its hosted on its own website (not directly on angularjs.org). Let me look into it, and any existing precedent that's been set.

**Comment by chivesrs** [comment]
It looks like the precedent is that each directory in https://github.com/angular/angular.js/tree/master/src has its own DT typings package (`angular-mocks`, `angular-sanitize`, `angular-route` as a few examples).

I'll go ahead and create a new declaration.

**Comment by chivesrs** [comment]
The main downside of a new declaration is that it'll be super tiny (the package seems to contain very few things).
Of course I'm sure that's not an issue but putting that out there.

**Comment by peterblazejewicz** [comment]
@chivesrs 
Thanks! yes, thats how modules works, some are really minuscule ones :)

**Comment by chivesrs** [comment]
@peterblazejewicz

Any idea how to resolve this error?
https://controlc.com/8cc1bdfb
https://controlc.com/452e2899

I'm a little bit lost, the AngularJS typings setup is a bit weird.

**Comment by peterblazejewicz** [comment]
@chivesrs will look at this later today!

**Comment by peterblazejewicz** [comment]
@chivesrs 
That's hard to tell. I guess that was something with either `tsconfig` setup or details of the `index.d.ts` file (imports, etc).
I've made a PR here: #42133 and marked you as the owner of the definition.
If that seems to be not ok, let me know. I'll retract the PR and you would be able to submit the code (by branching it locally, doing re-edits, etc) and resubmitting the PR in your own name, 
Thanks!

**Comment by chivesrs** [comment]
It's fine, as long as I have owners I don't really care. Maybe just reference this PR in yours? That's good enough for me credit wise.

**Comment by chivesrs** [comment]
Actually, I got my PR to work. The trick was to add `TypeScript Version: 2.3` (matching what `angular-material` does).

**Pull request closed without merging**
