### PR TITLE
[aws-lambda] Added method attribute to APIGatewayProxyEvent

### PR DESCRIPTION
**Pull request by terencenero007**
Added `method` attribute to APIGatewayProxyEvent in order to support APIGateway  integration mode `LAMBDA`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/apollographql/apollo-server/issues/1964
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by jagregory** [comment]
Is this a mandatory field for all uses of APIGatewayProxyEvent?

**Comment by terencenero007** [comment]
> Is this a mandatory field for all uses of APIGatewayProxyEvent?

No, this field is required when using APIGateway to lambda integration in 'LAMBDA' mode. I can make it optional.

**Review by simonbuchan — CHANGES_REQUESTED** [review]
Red X for maintainer, see my last comment.

**Comment by terencenero007** [comment]
> `APIGatewayProxy*` types are for the proxy integration specifically. As far as I can tell, custom lambda integrations can have whatever event and response shape you want? If you want a custom integration, you can use whatever event / result types you like by using the `Handler<Event, Result>` type directly:
> 
> ```ts
> import { Handler } from "aws-lambda";
> // for example:
> type CustomEvent = { method: string };
> type CustomResult = { status: number };
> type CustomHandler = Handler<CustomEvent, CustomResult>;
> export const customHandler: CustomHandler = async ({ method }, context) => {
>   return { status: 123 };
> };
> ```

Sorry for the late reply. I will take a look into your suggestion and get back. You can hold the merge till then. Thanks

**Pull request closed without merging**
