### PR TITLE
[twine-sugarcube] Add Math.easeInOut, remove Math.trunc

### PR DESCRIPTION
**Pull request by BawdyInkSlinger**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tmedwards/sugarcube-2/issues/267
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ezsh — APPROVED** [review]

**Comment by BawdyInkSlinger** [comment]
You may want to undo this @ezsh See https://github.com/tmedwards/sugarcube-2/issues/267

**Comment by BawdyInkSlinger** [comment]
I don't think it should be merged.

**Review by tmedwards — CHANGES_REQUESTED** [review]
This really should not be merged.

@BawdyInkSlinger Please close this PR—I assume you can, since you opened it.

**Comment by BawdyInkSlinger** [comment]
> This really should not be merged.
> 
> @BawdyInkSlinger Please close this PR—I assume you can, since you opened it.

Ah, I didn't realize I could do that. Thanks, I'll do that now.

**Pull request closed without merging**
