### PR TITLE
Add new Creep.pull method

### PR DESCRIPTION
**Pull request by MadaraUchiha**
See https://docs.screeps.com/api/#Creep.pull
See https://blog.screeps.com/2018/12/changelog-2018-12-14/#Creep-pull

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://docs.screeps.com/api/#Creep.pull>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
Reviewers: I don't know the version number for the current version of Screeps, please feel free to edit this merge request accordingly (I think it should be possible), barring that, tell me and I'll be happy to change it :)

**Comment by Arcath** [comment]
We don't make changes to this repository directly.

Could you make a PR on screeners/typed-screeps instead and it will get
merged here along with a few other updates that we are working on

**Comment by MadaraUchiha** [comment]
> screeners/typed-screeps

Seems like it's already implemented there, but not released here.

**Comment by Arcath** [comment]
We are working on the power creeps implementation at the moment once that's
done there will be another release here. You can use that repo for your
typings to get creep.pull working now.

**Pull request closed without merging**
