### PR TITLE
added missing option pane

### PR DESCRIPTION
**Pull request by sahne123**
see https://github.com/Leaflet/Leaflet.label#options

### CODE REVIEW

**Comment by Nemo157** [comment]
Appears that the option should be one of the keys of [`MapPanes`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/leaflet/leaflet.d.ts#L2777-L2813). I wonder if there's a way to say something like
```typescript
pane?: MapPanes.keys
```
yet? It's been awhile since I've looked at the newer TypeScript features. Alternatively I think you could list them explicitly
```typescript
pane?: 'mapPane' | 'tilePane' | 'objectsPane' | 'shadowPane' | 'overlayPane' | 'markerPane' | 'popupPane'
```
Up to you whether you think it's worth making explicit. :+1:

**Comment by sahne123** [comment]
@Nemo157 
I'm not that deep in typescript or leaflet yet. Thought first there could be custom panes as well. 

Your suggestion to name them explicitly does not work for me: ``type expected`` (typescript 1.6.2)
> pane?: 'mapPane' | 'tilePane' | 'objectsPane' | 'shadowPane' | 'overlayPane' | 'markerPane' | 'popupPane'

**Comment by Nemo157** [comment]
Hmm, I know you can enumerate string values as types in some places, guess not here though. 

LGTM :+1:

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
