### PR TITLE
ng-dialog fix IDialogOpenResult.closePromise

### PR DESCRIPTION
**Pull request by marknadig**
create IDialogClosePromise type to be returned by IDialogOpenResult.closePromise.

### CODE REVIEW

**Comment by vvakame** [comment]
*ng-dialog/ng-dialog.d.ts*

to author(@stephenlautier). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

**Comment by stephenlautier** [comment]
Looks good :+1:. Thanks @marknadig

**Comment by marknadig** [comment]
@vvakame looks good.

**Comment by vvakame** [comment]
thanks mate!

**Pull request merged**
