### PR TITLE
package(greensock) Declare module 'gsap'

### PR DESCRIPTION
**Pull request by neo**
Please fill in this template.

- [x] Prefer to make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.

### CODE REVIEW

**Comment by andy-ms** [comment]
If you're declaring a `gsap` module I'd expect that to go in the `gsap` directory.

**Comment by neolwc** [comment]
Yeah, but this one looks much better and there's no package named `greensock` on npm, I assume it's for `gsap`

**Comment by andy-ms** [comment]
Are you saying that `greensock` and `gsap` are duplicates? Then we should get rid of one of them, probably `greensock` since (as you say) it's not on NPM. The best parts of both should be merged together. CC @vilic (author of `gsap` typings)

**Comment by neolwc** [comment]
Yes, it's for the same package.

**Comment by andy-ms** [comment]
OK, then like I said above, `greensock` types should be moved into `gsap` so we can deprecate `@types/greensock`.

**Comment by neolwc** [comment]
And I could do this?

**Comment by andy-ms** [comment]
Indeed you could. :wink:

**Comment by andy-ms** [comment]
Please make a new PR when you get around to doing that. Clearing out old PRs.

**Pull request closed without merging**
