### PR TITLE
Update Bing Maps API type definition from V7 to V8

### PR DESCRIPTION
**Pull request by jamesmcroft**
I noticed that the API definition was for a deprecated version of Bing Maps. The recommended version is V8 so this PR covers the changes required for the API.

Information on updated API:
https://msdn.microsoft.com/en-us/library/mt712542.aspx

### CODE REVIEW

**Comment by mhegazy** [comment]
Please update the PR to fix the failing CI tests.

**Comment by jamesmcroft** [comment]
Sorry for that. I accidentally removed the headers from the previous files. Should be all fixed up now.

**Comment by mhegazy** [comment]
Since this change is breaking, can you please copy the old files to a v7 folder, to make sure users looking for that version can still find it.

**Comment by jamesmcroft** [comment]
Sure, that's no problem. I'll get that sorted.

**Comment by yuit** [comment]
@jamesmcroft  Thank you for the PR, could you fix merge conflict so this change can be merge?

**Comment by yuit** [comment]
@jamesmcroft  Thanks for your contribution. This PR has merge conflict and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Comment by jamesmcroft** [comment]
Apologies for this one, I was out of my own country on holiday with limited access to e-mails and code. Got back yesterday and have only just started catching up! I'll sort out another PR with the parts fixed.

**Pull request closed without merging**
