### PR TITLE
Update aws-sdk.d.ts

### PR DESCRIPTION
**Pull request by kherkeladze**
case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

fix metadata type checking bug. More info : http://stackoverflow.com/a/15879330

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@kherkeladze It is not clear why this has been changed to any. Please provide the documentation as to why this change is needed.
Thanks

**Comment by kherkeladze** [comment]
@sheetalkamat Ok, this was my problem:

TypScript version: 1.8.10

When I added Metadata object in params, tsc threw this strange error: 

`error TS2345: Argument of type '{ Bucket: string; Key: string; Body: string; Metadata: { key: string; }; }' is not assignable to parameter of type 'PutObjectRequest'.
  Types of property 'Metadata' are incompatible.
    Type '{ key: string; }' is not assignable to type '{ [key: string]: string; }'.`


my Metadata is very simple: 
`  Metadata : {
      key: "val"
  }`

so I can't use 'putObject' method with Metadata.

I don't know how compilation process going exactly, but my fix works.

**Comment by zhengbli** [comment]
Are there any aws sdk documentation regarding this change?

**Comment by andy-ms** [comment]
I'm not sure why you get the error `Type '{ key: string; }' is not assignable to type '{ [key: string]: string; }'.`.
Please investigate more and see if you can get a simple way to reproduce this error.
Anyway, it is not a problem with the type definition, so closing this.

**Pull request closed without merging**
