### PR TITLE
[node] add crypto.generateKeyPair

### PR DESCRIPTION
**Pull request by Flarna**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Refs: #29689

### CODE REVIEW

**Review by SimonSchick — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Comment by Flarna** [comment]
@andy-ms @RyanCavanaugh would be nice if this could be merged as test fail seems to be because of #30323

**Comment by ZaneHannanAU** [comment]
At some point we should probably use the style that `EventTarget` variations use in default `lib.dom.d.ts`, but that would take a lot of effort to put in.

Basically

```typescript
interface GenerateKeyPairOptions {
  "yo": SomeThing<"key", "to">;
}
// ...
export function generateKeyPair<T keyof GenerateKeyPairOptions>(key: T, pair: GenerateKeyPairOptions[T], /* ... */ v): void
```

… I'll leave that for a while. It's a little … awkward.

**Comment by SimonSchick** [comment]
I don't think we can, the TS version of node typings is too low.

**Comment by andy-ms** [comment]
We do support `typesVersions` on DT now, as used by `es6-shim`. Node could add a `ts3.1` directory too. @rbuckton may already be working on this?

**Pull request merged**
