### PR TITLE
[vinyl-fs] Add v0.3 and v1.0, remove watch() to match v2.4

### PR DESCRIPTION
**Pull request by TeamworkGuy2**
...Also remove .editorconfig and just use default 4 space indentation.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gulpjs/vinyl-fs/releases
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
@vvakame @remisery Can you please review?

**Comment by uniqueiniquity** [comment]
@TeamworkGuy2 feel free to ping me in 5 days if the owners don't review it.

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
Can you re-enable `no-object-literal-type-assertion` in the top-level `tslint.json` and fix the resulting lint errors in the test file? I'm worried future issues in the .d.ts file itself might be missed due to the rule, which seems to only be disabled for shorthand in the test file.

**Review by TeamworkGuy2 — COMMENTED** [review]
@uniqueiniquity @vvakame Good catch, I didn't even pay attention to the tslint file.

**Review by uniqueiniquity — APPROVED** [review]

**Pull request merged**
