### PR TITLE
make texture references more consistent

### PR DESCRIPTION
**Pull request by bunnybones1**
from `map: Texture | null` to `map?: Texture` for cleanliness and interoperability (like using one material's texture as a parameter for another)

### CODE REVIEW

**Review by JuStTheDev — APPROVED** [review]

**Review by uniqueiniquity — CHANGES_REQUESTED** [review]
This change isn't actually correct. For example, `alphaMap?: Texture` is the same as `alphaMap: Texture | undefined`, _not_ `alphaMap: Texture | null`. Since `null` is the actual value used, you do actually have to use the existing type.

**Comment by bunnybones1** [comment]
> This change isn't actually correct. For example, `alphaMap?: Texture` is the same as `alphaMap: Texture | undefined`, _not_ `alphaMap: Texture | null`. Since `null` is the actual value used, you do actually have to use the existing type.

@uniqueiniquity  Is there another way we can make the types of material properties and argument parameters more consistent? The goal is to be able to do something like this more easily:

```
const newMat = new MeshBasicMaterial({
  map: oldMat.map
})
```

Maybe the goal comes at a cost I'm not seeing?

**Comment by uniqueiniquity** [comment]
@bunnybones1 I see the issue you're trying to solve. In that case, you should change the parameter interfaces (like `MeshBasicMaterialParameters`) to accept `null` where appropriate (i.e. `map?: Texture | null`).

**Comment by uniqueiniquity** [comment]
I'd also add a test or two while you're at it; that way, it'll be a little easier to understand your intent and your change won't regress in the future.

**Comment by bunnybones1** [comment]
Good idea. Thanks @uniqueiniquity

**Pull request closed without merging**
