### PR TITLE
react: Add "mask" and "fillRule" to SVGAttributes

### PR DESCRIPTION
**Pull request by neelance**
mask: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Clipping_and_masking#Masking
fillRule: https://developer.mozilla.org/en/docs/Web/SVG/Attribute/fill-rule

### CODE REVIEW

**Comment by neelance** [comment]
Are you already accepting PRs to the `types-2.0` branch?

**Comment by neelance** [comment]
@vsiao Are you already accepting PRs to the types-2.0 branch?

**Comment by chexee** [comment]
`animate` and associated properties would be nice too :)

**Comment by andy-ms** [comment]
@neelance We accept 2.0-specific changes to `types-2.0` (e.g. `readonly` or `strictNullChecks`), but it's better to do most things on `master` as we'll manually merge changes from there to `types-2.0` anyway.

**Comment by vsiao** [comment]
lgtm, but would prefer to see these on `master`.

**Pull request merged**
