### PR TITLE
[react] Reverted #18227

### PR DESCRIPTION
**Pull request by DovydasNavickas**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Reverting changes made by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18227 as they are simply incorrect.

### CODE REVIEW

**Comment by artem-malko** [comment]
@DovydasNavickas as I think, you should update version in header of file too.

**Comment by vsiao** [comment]
"Revert" is misleading, because you're still keeping some of the changes. But ok 👍

**Comment by DovydasNavickas** [comment]
Been busy for a few days. I've just updated for CI to pass (weird errors before o_O).
Also, updated version in the header as @artem-malko suggested.

**Comment by johnnyreilly** [comment]
Thanks

**Comment by devrelm** [comment]
@DovydasNavickas @vsiao For the record, I feel it was inappropriate to have removed me as an author during this PR. I would understand if it were a full revert, but some of the changes from #18227 still lives in this file.

**Pull request merged**
