### PR TITLE
[yargs-parser] Add new parser configs for v20.2

### PR DESCRIPTION
**Pull request by badsyntax**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yargs/yargs-parser#configuration
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by milesj — APPROVED** [review]

**Comment by badsyntax** [comment]
Thanks for the review @milesj. This is the first time I've contributed to DefinatelyTyped, should @typescript-bot be allowing me to merge somehow or do we need another approval?

**Comment by milesj** [comment]
I ... think it's automatic. Just gotta wait for the bot.

**Comment by badsyntax** [comment]
Looking at [other PR's](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50192) it seems the bot should be adding a "Self merge" label immediately after approval. Wondering if we can try again?

**Review by milesj — APPROVED** [review]

**Comment by badsyntax** [comment]
Thanks for the re-approval. Nothing as changed. I guess I'll try waiting then. A little annoying as this waiting period is not reflected the [process diagram](https://raw.githubusercontent.com/DefinitelyTyped/dt-mergebot/master/docs/dt-mergebot-lifecycle.svg).

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by badsyntax** [comment]
Ready to merge

**Pull request merged**
