### PR TITLE
fix: no default export in @rdfjs/term-set

### PR DESCRIPTION
**Pull request by tpluscode**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/rdfjs-base/term-set/blob/master/TermSet.js#L11>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by amcasey — CHANGES_REQUESTED** [review]
Sorry, I think I'm missing something - did you mean to change it to `export default`, rather than `declare`?  If not, what's exported now?

Also, is the tslint suppression still required?

**Comment by tpluscode** [comment]
The class is still default-exported but it is not possible to `export default class` when declaration merging

> TS2652: Merged declaration 'TermSet' cannot include a default export declaration. Consider adding a separate 'export default TermSet' declaration instead.

And yes, the suppression is needed to avoid 

> TSLint: Every member of this class is a constructor. Use functions instead. (no-unnecessary-class)

That said, it may just be possible to avoid that completely by extending the `Set` class rather than implementing the interface. Please see now. I don't think there should be any issues with that

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by tpluscode** [comment]
Ready to merge

**Pull request merged**
