### PR TITLE
CKEditor HTML parser typings

### PR DESCRIPTION
**Pull request by adrienverge**
#### test(CKEditor): Add missing tests for htmlParser.basicWriter

---
#### feat(CKEditor): Add typings for htmlWriter

See related documentation at:
http://docs.ckeditor.com/#!/api/CKEDITOR.htmlWriter

---
#### feat(CKEditor): Add typings for htmlDataProcessor

See related documentation at:
http://docs.ckeditor.com/#!/api/CKEDITOR.htmlDataProcessor

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi,

Have anyone had a chance to review this?

**Comment by ondrejsevcik** [comment]
Hi guys, is there a way I can unassign me from reviewing any future change to CKEditor type definition? I'm no longer working with CKEditor, and I get an email about an update every other week.

Thank you for understanding. Ondrej

**Comment by adrienverge** [comment]
Hi @ondrejsevcik,

I think you need to remove yourself from `CONTRIBUTORS.md`. But since you are the only one left, maybe someone else needs to take the job?

PS: In any case, if you have 30 sec to review this last (and simple) PR, I'd be grateful :)

**Comment by ondrejsevcik** [comment]
Looks good 👍

**Comment by adrienverge** [comment]
Thanks!

**Pull request merged**
