### PR TITLE
for for scenario where passing in simple types to ko.toJS did not work

### PR DESCRIPTION
**Pull request by ffMathy**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by ffMathy** [comment]
Wait a bit with this... Investigating... Might actually be my code instead.

**Comment by ffMathy** [comment]
Alright, I was right, but only in some scenarios where parsing in a direct observable that's not necessarily an object with observable properties on it.

- `ko.toJS(ko.observable(2))` should provide `2`
- `ko.toJS(ko.observable({ foo: ko.observable(1337) }))` should provide `{ foo: 1337 }`
- `ko.toJS(2)` should provide `2`
- `ko.toJS({ foo: 1337 })` should provide `{ foo: 1337 }`

**Review by BenjaminEckardt — APPROVED** [review]

**Comment by quentinjones** [comment]
This fix is problematic with some of my existing code that uses ko.toJS on complex types since a return type of T is specified instead of any.  The object that's returned (if observable) is unwrapped but so are any observable properties it had before which may no longer conform to the original unwrapped type T.

Something like below could let it work as before but I'm not sure it's better than just any unless the original type was simple.
```
    toJS<T>(viewModel: KnockoutObservableArray<T>|KnockoutObservableType<T>[]|KnockoutObservableArray<KnockoutObservableType<T>>|T[]): T[] | any[];
    toJS<T>(viewModel: KnockoutObservable<T>|KnockoutObservableType<T>|KnockoutObservable<KnockoutObservableType<T>>|T): T | any;
```

**Comment by ffMathy** [comment]
I'm not sure I understand. Could you post an example that doesn't compile with the current typings?

**Comment by quentinjones** [comment]
```
ClassA {
    Id: KnockoutObservable<number>;
    Name: KnockoutObservable<string>;
}

ClassB {
    Id: number:
    Name: string;    
}

var a = new ClassA();
var b = ko.toJS(observableClass);
```
In the example b upon inspection would look like an object of ClassB because the observable properties Id and Name are now unwrapped on the resulting object. According to your typing the object should still look like ClassA, but it doesn't. It looks like ClassB.  You can't infer the resulting object type when the input T is a complex class.

**Comment by ffMathy** [comment]
Are you sure you're seeing the right results? Can you link to a TS playground share link where your problem is demonstrated?

**Comment by quentinjones** [comment]
Check the example here https://jsfiddle.net/s9suvs15/

**Comment by ffMathy** [comment]
Can you provide a TypeScript Playground share link instead?
www.typescriptlang.org/play/index.html

**Comment by quentinjones** [comment]
I was going to do that but the example needs knockout and, I don't see a way to pull in libraries on TypeScript Playground. Not sure why it matters where the example is.

**Comment by ffMathy** [comment]
Because the jsfiddle you provided doesn't provide intellisense etc., and because I am very busy and therefore have limited time for testing this elsewhere. 

You can just copy paste the knockout definitions into the code field.

By using Typescript playground you also ensure that the problem is real, and not an error in the IDE you are using.

**Comment by quentinjones** [comment]
I can't just paste Knockout's JS code into the typescript compiler and it's required that knockout runs the toJS method. This error is occurring at run time because of the return type of the toJS function. There is no compilation error because of the incorrect return type added to the toJS method in th e interface.

The example is very simple, and maybe I can be more clear in describing the problem.  I think it was actually introduced in your commit [5255020](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22959/commits/52550207747ee2bbfd434bafa7d48199124cfafc) when the return types T and T[] were added to toJS. This works ok for an object of KnockoutObservable<T> where T is a primitive type, but not for classes that contain observable properties which are also unmapped when Knockout executes toJS.  Looking at the example if an object of ko.toJS(ClassA) goes in ClassA is expected out according to the typing, but what actually comes out of toJS looks like ClassB in the example therefore the return type is inaccurate.

The original return type of any was appropriate for class objects because it's not known how many (if any) of it's properties are KnockoutObservable or KnockoutObservableArray (return type T is correct only if none were).  You could still implement strong typing when T is primitive, but you'll have to add some specific overloads to handle those.

**Comment by ffMathy** [comment]
Well you can paste *some* code that runs the toJS method. Just like you did in your jsfiddle, in the TypeScript Playground instead.

I think I understand what you're saying, but I still can't see why it is a problem.

If the input is `{foo: KnockoutObservable<number> }` the output should be `{ foo: number }` right? And that's also what the typing returns in my example? Try to emphasize the issue concretely with those types of examples instead of `ClassA` and `ClassB` - just use clear and concise typings.

**Comment by quentinjones** [comment]
Ok you're getting there now. I think the classes are necessary to demonstrate the problem. Intellisense won't help you with those anonymous objects. If you look at them in the jsfiddle it's demonstrating what you just stated, but with strong typed classes instead of anonymous objects.

Consider this simplified toJS typing:
`toJS<T>(viewModel: T): T;`

It's telling Intellisense an object of type T goes in and an object of type T comes out. You just said yourself the property of the anonymous object foo going in is `KnockoutObservable<number>` and coming out it's `number`.  IntelliSense expects what comes out of toJS to be the same as T that went in. It will think the property foo of any class is still observable when it is not.

**Comment by ffMathy** [comment]
But that is why there is the KnockoutObservableType overload also. It is a type transformation. It should pick that if that is more appropriate. 

I don't get why you can't just quickly create an example in the playground to demonstrate the problem.

**Comment by quentinjones** [comment]
Having KnockoutObservableType doesn't change anything. When a class gets passed in TypeScript considers it to have the type `object` and it will use the generic specifier T. 

I'm not trying to be difficult. The example needs to run Knockkout and it's JS code that doesn't run on TypeScript Playground. Please take a look at the JSfiddle instead.

**Comment by ffMathy** [comment]
The JSFiddle does not demonstrate the problem as it is not enforcing type strictness.

Just copy-paste the definition files of Knockout (the relevant methods) into the playground and move your example there. Then send a link.

If you do so, I will look at it.

**Comment by quentinjones** [comment]
[TypeScript Playground Example](http://www.typescriptlang.org/play/index.html#src=export%20class%20ClassA%20%7B%0D%0A%20%20%20%20Name%20%3D%20ko.observable(%22My%20Name%22)%3B%0D%0A%7D%0D%0A%0D%0Alet%20classA%3A%20ClassA%20%3D%20ko.toJS(new%20ClassA())%3B%20%2F%2F%20The%20resulting%20object%20here%20stored%20in%20classA%20is%20not%20representative%20f%20ClassA%0D%0Aconsole.log(classA.Name())%20%2F%2F%20Attempting%20to%20unrwrap%20the%20Name%20as%20the%20typing%20suggests%20is%20possible%20will%20result%20in%20an%20error%0D%0A%0D%0A%0D%0Ainterface%20KnockoutExtensionFunctions%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20KnockoutSubscribableFunctions%3CT%3E%20extends%20KnockoutExtensionFunctions%20%7B%0D%0A%20%20%20%20notifySubscribers(valueToWrite%3F%3A%20T%2C%20event%3F%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20KnockoutComputedFunctions%3CT%3E%20extends%20KnockoutExtensionFunctions%20%7B%0D%0A%7D%0D%0A%0D%0Ainterface%20KnockoutObservableFunctions%3CT%3E%20extends%20KnockoutExtensionFunctions%20%7B%0D%0A%20%20%20%20equalityComparer(a%3A%20any%2C%20b%3A%20any)%3A%20boolean%3B%0D%0A%7D%0D%0Ainterface%20KnockoutObservableArrayFunctions%3CT%3E%20extends%20KnockoutExtensionFunctions%20%7B%0D%0A%20%20%20%20%2F%2F%20General%20Array%20functions%0D%0A%7D%0D%0Ainterface%20KnockoutObservableArray%3CT%3E%20extends%20KnockoutObservable%3CT%5B%5D%3E%2C%20KnockoutObservableArrayFunctions%3CT%3E%20%7B%0D%0A%7D%0D%0Ainterface%20KnockoutSubscription%20%7B%0D%0A%20%20%20%20dispose()%3A%20void%3B%0D%0A%7D%0D%0Ainterface%20KnockoutSubscribable%3CT%3E%20extends%20KnockoutSubscribableFunctions%3CT%3E%20%7B%0D%0A%7D%0D%0Ainterface%20KnockoutObservable%3CT%3E%20extends%20KnockoutSubscribable%3CT%3E%2C%20KnockoutObservableFunctions%3CT%3E%20%7B%0D%0A%20%20%20%20%20()%3A%20T%3B%0D%0A%7D%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0Atype%20KnockoutObservableType%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20KnockoutObservable%3CT%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0Ainterface%20KnockoutStatic%20%7B%20%20%20%20%0D%0A%20%20%20%20observable%3A%20KnockoutObservableStatic%3B%0D%0A%20%20%20%20toJS%3CT%3E(viewModel%3A%20KnockoutObservableArray%3CT%3E%20%7C%20KnockoutObservableType%3CT%3E%5B%5D%20%7C%20KnockoutObservableArray%3CKnockoutObservableType%3CT%3E%3E%20%7C%20T%5B%5D)%3A%20T%5B%5D%3B%0D%0A%20%20%20%20toJS%3CT%3E(viewModel%3A%20KnockoutObservable%3CT%3E%20%7C%20KnockoutObservableType%3CT%3E%20%7C%20KnockoutObservable%3CKnockoutObservableType%3CT%3E%3E%20%7C%20T)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20KnockoutBindingProvider%20%7B%0D%0A%7D%0D%0Ainterface%20KnockoutObservableStatic%20%7B%0D%0A%20%20%20%20fn%3A%20KnockoutObservableFunctions%3Cany%3E%3B%0D%0A%0D%0A%20%20%20%20%3CT%3E(value%3F%3A%20T%20%7C%20null)%3A%20KnockoutObservable%3CT%3E%3B%0D%0A%7D%0D%0Adeclare%20var%20ko%3A%20KnockoutStatic%3B)

This should demonstrate the problem simply.

**Comment by ffMathy** [comment]
Thank you! I've resolved the bug in the above two pull requests I just referenced.

**Comment by ffMathy** [comment]
@quentinjones I have made updates here, since you appear to have been right. All I need are some tests and then it'll be merged.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23478

**Pull request merged**
