### PR TITLE
Updated typings of angular-toastr

### PR DESCRIPTION
**Pull request by kwiateusz**
In toast options we can edit container config, so I edited IToastOptions interface

### CODE REVIEW

**Comment by nkovacic** [comment]
This line https://github.com/Foxandxss/angular-toastr/blob/master/src/toastr.js#L250
clearly shows that IToastContainerConfig should not be in IToastOptions.And in the documentation of the plugin it clearly says that IToastContainerConfig should be only updated in the angular.config block.
You have any code snippets that show this usage of IToastOptions?

**Comment by kwiateusz** [comment]
https://plnkr.co/edit/guaFzm6oPTK9dMcZLTTF

In my project when i change target or preventDuplicates in options it affects that one toastr. I know that documentation says that only in config block that should be done but it works.

**Comment by nkovacic** [comment]
Ok I deep dived into the issues section and found out that target is an allowed option for IToastOptions.
:+1:

**Comment by kwiateusz** [comment]
@horiuchi @vvakame can someone of you merge that? I will be very grateful

**Comment by horiuchi** [comment]
@kwiateusz Thank you for your ping! :+1: 
@nkovacic Thanks for review!

**Pull request merged**
