### PR TITLE
react-router: add package.json with dependancy to  @types/history@2.0.45 (#13299)

### PR DESCRIPTION
**Pull request by dzharii**
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13299#issuecomment-272652699

history version 2 declaration was recently removed from the inside of react-router type defs. The day after, 
the global @types/history was upgraded to version 4 from version 2 which broke the react router definition files. 
This PR adds @types/history@2.0.45 as a dependency to react-router in order to fix the compilation issue. 

CC: @andy-ms

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
@dzharii It should cc authors of `react-router`. Please tag them.

**Comment by dzharii** [comment]
Authors and contributors @sergey-buturlakin, @mrk21, @vasek17, @ngbrown, @awendland, @KostyaEsmukov could you please check this PR and see if everything is OK?
Thank you

**Comment by KostyaEsmukov** [comment]
I guess it's fine, but I can't test it right now.

But personally I would fix both major and minor version parts (the tilde `~` modifier instead of the caret `^`).

Anyway I think this should be merged soon, because react-router typings are currently broken for some people.

**Comment by andy-ms** [comment]
Sorry for the trouble. This is fixed as of the latest publish. `npm info @types/react-router dependencies`

**Pull request closed without merging**
