### PR TITLE
Add additional methods to nock.

### PR DESCRIPTION
**Pull request by optical**
Adds some missing methods to nock.

Not sure if I should be updating the contributor section within the definitions header, wasn't explicitly mentioned in the contributing guidelines so I haven't for now.

### CODE REVIEW

**Comment by vvakame** [comment]
@Nemo157 @danrspencer could you review this PR?

**Comment by optical** [comment]
Will add Regex, update version number and add support for request repeating later today.

**Comment by optical** [comment]
@Nemo157 Ready for review.

**Comment by Nemo157** [comment]
LGTM :+1:

**Comment by vvakame** [comment]
@Nemo157 thanks!
@optical thanks mate!

**Pull request merged**
