### PR TITLE
Update better-sqlite3 to match version 5.0

### PR DESCRIPTION
**Pull request by Loghorn**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by sant123 — CHANGES_REQUESTED** [review]
Hi, thank you for your PR !! :smile: and sorry to check these changes late :disappointed:. I have made some comments, and I think after they have been fixed or commented we can merge it. 

Cheers.

**Comment by Loghorn** [comment]
@sant123 sorry about the typos, I've fixed them

**Comment by sant123** [comment]
@Loghorn thanks! They look fine! And about the `.default` method. Does it really exists?

**Comment by sant123** [comment]
Nevermind, I just checked it and the method exists (in code). I didn't find the method in the docs. 

Thanks again!

**Review by sant123 — APPROVED** [review]

**Comment by Loghorn** [comment]
Thank you @sant123

**Comment by jessetrinity** [comment]
Manually resolving all open issues for a tag test.

**Comment by Loghorn** [comment]
@jessetrinity I'm sorry to bother you, but is there anything still blocking this PR from being merged?
Thank you

**Comment by jessetrinity** [comment]
@Loghorn No problem, sorry for the delay.

**Pull request merged**
