### PR TITLE
fix: revert props back to `any` on `customBodyRender`

### PR DESCRIPTION
**Pull request by Patrick-Erichsen**
Signed-off-by: Patrick-Erichsen <Patrick.Erichsen@target.com>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by russelldc — APPROVED** [review]
Thanks for getting this reverted!

**Review by favna — APPROVED** [review]

**Comment by elibarzilay** [comment]
Please consider adding some tests, especially given that this is a revert...

**Comment by Patrick-Erichsen** [comment]
@elibarzilay I think this existing test is covering the reversion? https://github.com/Patrick-Erichsen/DefinitelyTyped/blob/pe-revert-customBodyRender-props/types/mui-datatables/mui-datatables-tests.tsx#L27-L36

To be honest I don't really understand what the tests in this package are actually asserting. I am a maintainer on another DT project ([`sawooth-sdk`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sawtooth-sdk/test/processor-tests.ts)), but we are using the `$ExpectType` assertions that will actually produce a failing test if something is wrong, which I don't see in these tests.

**Comment by Favna** [comment]
I'll be frank @Patrick-Erichsen, I wrote the bulk of those tests a long time ago back when I knew not even half of TypeScript that I do now so I wouldn't be surprised if they're pretty bad.

**Comment by Patrick-Erichsen** [comment]
Eh I wouldn't say that there bad, seems like they do a good job of setting up a broad case of scenarios. It's just that they don't contain any assertions so I don't believe they could ever fail haha, you would just get an IDE error.

So for what it's worth, I am not getting any IDE errors on this reversion for that code block I highlighted above.

**Review by pedrinhof11 — APPROVED** [review]

**Review by favna — APPROVED** [review]

**Pull request closed without merging**
