### PR TITLE
[calendar] Fix @types/calendar typings

### PR DESCRIPTION
**Pull request by quentincaffeino**
monthDates and monthDays does not return array of Dates. First returns arrays of weeks of Dates. Second returns arrays of weeks of days.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by ffflorian — CHANGES_REQUESTED** [review]
Thanks for the fix @quentincaffeino! Could you please provide a test?
For example, add `// $ExpectType Date[][]` to [`calendar-tests.ts#L16`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffbdb799a6084cbb9ca32214d7fdd58b82d6a5d1/types/calendar/calendar-tests.ts#L16).

**Comment by quentincaffeino** [comment]
Hey, @ffflorian. No problem. Also I just noticed that there was one more problem. Fixed it and added a test for it. Hope I understood you right with how to do those tests. Best :+1:

**Review by ffflorian — APPROVED** [review]

**Comment by ffflorian** [comment]
Well done @quentincaffeino :)

**Comment by ffflorian** [comment]
@sandersn @DanielRosenwasser @andy-ms

The tests are failing with "Can not match a node to this assertion". Do you know why this happens? I could only find this issue, which is still open: https://github.com/microsoft/dtslint/issues/157

**Comment by quentincaffeino** [comment]
I'll try running it locally, maybe I could get this tests to show a little more information on the cause of the error.

**Comment by quentincaffeino** [comment]
Ok that // expect stuff should be on a line before call, not at the end of it. Atleast it doesn't throw any error. Maybe that's has something to do with the fact that it is multi-line call. Not really sure. Will push shortly.

**Comment by ffflorian** [comment]
Usually I see `ExpectType` only after a call :thinking:

**Comment by quentincaffeino** [comment]
Ok in `dtslint` readme there's two ways of using it: before and at the end of the line. So I guess the multiline structure is thee cause of the problem.

**Comment by ffflorian** [comment]
Ah, okay. Well done :+1:

**Review by ffflorian — APPROVED** [review]

**Comment by quentincaffeino** [comment]
Ready to merge

**Comment by ffflorian** [comment]
@quentincaffeino wait, I just checked `monthDays()` manually and it returns `number[][]` and not `Date[][]`. Will you create a fix for that?

**Comment by quentincaffeino** [comment]
@ffflorian I've also noticed that and it is in this merge already in this commit: [`0f73e58` (#51161)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51161/commits/0f73e58d3c516be83a70dad09e28182d14115484)

**Comment by ffflorian** [comment]
Then let's create a new PR :)

**Comment by quentincaffeino** [comment]
It's already merged tho :|

**Comment by ffflorian** [comment]
Yeah but you can create a new PR reverting the change.

**Pull request merged**
