### PR TITLE
fix(angular-aria): 'typeof import' is not assignable to type 'string'

### PR DESCRIPTION
**Pull request by jzolnowski**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## angular-aria ([<kbd>unpkg</kbd>](https://unpkg.com/browse/angular-aria@latest/))
was missing the following properties:
1. padStart
1. padEnd
1. trimLeft
1. trimRight
1. trimStart

<details>
<summary>as well as these 1 other properties...</summary>
<p>trimEnd</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against abc48e849171789bcf41f0eab52a66800e60ad0a
</p>

**Comment by chivesrs** [comment]
How are you importing this in your code base?

Usually it's done as

```
import 'angular-aria';
import * as angular from 'angular';

const z: angular.aria.IAriaService = ...;
```

It might help if you provide a snippet of your source code so I can fully understand the import error, and it'd help me approve this PR.

**Review by chivesrs — CHANGES_REQUESTED** [review]
See comment on the PR itself

**Comment by chivesrs** [comment]
Can you confirm and provide proof of both of:

1. that ng-material module also does this?
2. the old style of importing will continue to function?

If so, I can approve this PR.

**Comment by jzolnowski** [comment]
> Can you confirm and provide proof of both of:
> 
> 1. that ng-material module also does this?
> 2. the old style of importing will continue to function?
> 
> If so, I can approve this PR.
[angular-material d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular-material/index.d.ts) file contains these 2 lines as on the screen below
image

This makes it possible to use an alias when importing:
```
import * as ngMaterial from 'angular-material';

export const angularjsModule = angular
  .module('AngularjsModule', [ngMaterial])
```

I can also onfirm it's still possible to use ngMaterial in an old way
image

Both ways work

**Review by chivesrs — APPROVED** [review]

**Comment by chivesrs** [comment]
The bot may not let you immediately merge due to lack of tests. I forget what the workflow is for just "let me merge right now" is but that may be a part of it.

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jzolnowski** [comment]
Ready to merge

**Pull request merged**
