### PR TITLE
Fix Angular component router broken by #8150

### PR DESCRIPTION
**Pull request by calebegg**
#8150 broke use of the Angular 1.5 component router by removing `$canActivate` and `$routeConfig` from `IComponentOptions`. This re-adds them to fix the breakage so we can update to the latest version of these types.

I also moved some component router specific code to the appropriate file.

### CODE REVIEW

**Comment by calebegg** [comment]
@vvakame Seems like @dt-bot doesn't work for Angular PRs -- could you take a look, since you reviewed the earlier PR?

**Comment by vvakame** [comment]
sorry for late. I reviewed your PR & merge it! thanks.

**Comment by andersborum** [comment]
@vvakame I can't see the change just yet; did you succesfully merge and commit the changes?

**Comment by vvakame** [comment]
yes!

**Pull request merged**
