### PR TITLE
added new devexpress-web major version 201.5

### PR DESCRIPTION
**Pull request by mpreyskurantov**
This PR contains sources for a new 'devexpress-web' types version:

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

[ASP.NET Controls and MVC Extensions -> Client API Reference](https://docs.devexpress.com/AspNet/js-ASPxClientOfficeDocumentLinkType)
[ASP.NET Bootstrap Controls -> Client API Reference](https://docs.devexpress.com/AspNetBootstrap/js-BootstrapClientAccordion)
[Dashboard -> ASP.NET Client API Reference](https://docs.devexpress.com/Dashboard/js-ASPxClientActionAvailabilityChangedEventArgs)
[Reporting -> Client API Reference (WebForms & MVC)](https://docs.devexpress.com/XtraReports/js-ASPxClientCustomizeElementsEventArgs)

- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by elibarzilay** [comment]
Can you please fix the `Definitions by` line to a GH url?

Also, tslint should follow the required form.

**Comment by orta** [comment]
ping, this PR looks like it took a bunch of effort and I don't want it to end up getting abandoned

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
I've rebased the branch locally from current master, reinstalled and got all green for tests:
```bash
npm run test-all

> definitely-typed@0.0.3 test-all C:\github\DefinitelyTyped
> node node_modules/@definitelytyped/dtslint-runner/dist/index.js --path .

Using local DefinitelyTyped at .
Parsing definitions...
Found 7103 packages.
Parsing in 12 child process(es)...
Parsing took 15.973 s
Running: git rev-parse --verify master
2b9f574b03c6db69f2371783de23e8b1a23d07b4
Running: git diff master --name-status
M       types/devexpress-web/devexpress-web-tests.ts
M       types/devexpress-web/index.d.ts
M       types/devexpress-web/tslint.json
M       types/devexpress-web/v181/tslint.json
M       types/devexpress-web/v182/devexpress-web-tests.ts
M       types/devexpress-web/v182/index.d.ts
M       types/devexpress-web/v182/tsconfig.json
M       types/devexpress-web/v182/tslint.json
M       types/devexpress-web/v191/devexpress-web-tests.ts
M       types/devexpress-web/v191/tsconfig.json
M       types/devexpress-web/v191/tslint.json
A       types/devexpress-web/v192/devexpress-web-tests.ts
A       types/devexpress-web/v192/index.d.ts
A       types/devexpress-web/v192/tsconfig.json
A       types/devexpress-web/v192/tslint.json
Testing 5 changed packages: devexpress-web,devexpress-web v181.7,devexpress-web v182.3,devexpress-web v191.6,devexpress-web v192.3
Testing 0 dependent packages:
Installing NPM dependencies...
  ./types/knockout: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links --no-save
 from ./types/knockout: up to date in 0.931s
found 0 vulnerabilities
1> devexpress-web START
2> devexpress-web/v181 START
3> devexpress-web/v182 START
4> devexpress-web/v191 START
5> devexpress-web/v192 START
3> devexpress-web/v182 OK
4> devexpress-web/v191 OK
1> devexpress-web OK
2> devexpress-web/v181 OK
5> devexpress-web/v192 OK


=== SUGGESTIONS ===

{}


=== PERFORMANCE ===

{ "s3-streams": 104619, "lodash": 58389, "react-select": 34180, "apollo-upload-client": 33700, "devexpress-web": 29375, "babel__traverse": 29321, "react-plotly.js": 27950, "google-map-react": 24373, "react-html-parser": 23606, "jest-environment-puppeteer": 21687, "office-js-preview": 20541, "office-js": 19608, "puppeteer": 19455, "expect-puppeteer": 18932, "axe-webdriverjs": 18023, "pa11y": 17828, "html5-to-pdf": 17801, "puppeteer-core": 17789, "babel__core": 17533, "babel-plugin-macros": 17323, "papaparse": 17153, "yeoman-generator": 17052, "htmlparser2": 17044, "maker.js": 16387, "flexslider": 15488, "plotly.js": 14354, "update-notifier": 11851, "restangular": 11786, "codemirror": 11646, "angular-resource": 11490, "css-minimizer-webpack-plugin": 11068, "chartjs-plugin-annotation": 11059, "copy-webpack-plugin": 11057, "dompurify": 10989, "html-beautify-webpack-plugin": 10987, "compression-webpack-plugin": 10934, "opentype.js": 10496, "angular-fullscreen": 10336, "office-runtime": 10305, "server-timing-header": 10305, "html_codesniffer": 10297, "user-idle-observer": 10252, "ally.js": 10243, "fake-response": 9840, "express-locale": 9792, "express-simple-locale": 9760, "mem-fs-editor": 9562, "npm-profile": 9500, "granim": 9438, "gulp-imagemin": 9424, "svg-sprite": 9362, "gulp-json-editor": 9314, "minify": 9231, "ejs": 9224, "google-adwords-scripts": 9153, "node-isbn": 9153, "dashdash": 9113, "sanitize-html": 9099, "pixelmatch": 9068, "ledgerhq__hw-transport-node-hid": 9055, "imagemin-svgo": 9013, "git-parse": 9009, "probe-image-size": 9003, "node-hid": 8989, "cross-spawn": 8976, "imagemin-webp": 8973, "follow-redirects": 8968, "imagemin-upng": 8957, "weak-napi": 8943, "imagemin-gifsicle": 8935, "parse-conflict-json": 8929, "elastic__maki": 8925, "is-gif": 8920, "mapbox__maki": 8920, "gulp-svg-sprite": 8561, "google-apps-script-oauth2": 8227, "google-apps-script": 5500, "jest-image-snapshot": 3269, "postcss-focus-within": 2396, "semver": 2323, "alex": 2198, "js-beautify": 2188, "cjson": 2178, "random-words": 2162, "creditcards-types": 2151, "linear-gradient-parser": 2151, "short-css-vars": 2141, "domutils": 2140, "wcag-contrast": 2136, "aws-regions": 2131, "mdv": 2129, "luhn-generator": 2128, "genyus__country-code": 2124, "calc-percent": 2123, "json-parse-helpfulerror": 2121, "find-duplicated-property-keys": 2119, "git-semver-tags": 2117, "platform": 2115, "jsonminify": 2111, "camelcase-css": 2110, "validate-npm-package": 2110, "replace-ext": 2109, "car-names": 2105, "native-hello-world": 2104}
  * Percentiles:
99: 79654.79999999971
95: 29337.2
90: 20655.60000000001
70: 11061.7
50: 9272.5
```
@mpreyskurantov I"d start limiting exclusion in the `tslint.json` and instead opt to 
modify those scripts that generate the output, those exclusions number can soon become unwieldy to follow

**Comment by mpreyskurantov** [comment]
Thanks everybody for the review and feedback.
 
I am maintaining the dts distribution created earlier and usually just update the single "index.d.ts" file content, while I copy / paste the others (including the once created "tsconfig.json" one) to older version subfolders.
 
@peterblazejewicz:
I am wondering if it necessary to re-work the "tsconfig.json" file. I assume that it may be possible to remove some ignores, because not all of them are still actual in the latest version. Will it be sufficient to address your suggestions?
 
@elibarzilay:
Will it be sufficient to change?
from
// Definitions by: DevExpress Inc. <https://devexpress.com/>
to
// Definitions by: DevExpress Inc. <https://github.com/DevExpress>

**Comment by peterblazejewicz** [comment]
> I am wondering if it necessary to re-work the "tsconfig.json" file. I assume that it may be possible to remove some ignores, because not all of them are still actual in the latest version. Will it be sufficient to address your suggestions?

@mpreyskurantov 
a short answer is no, IMO that's not required. I always advise to simplify the 'tslint.json' to follow project guidelines and readme. I understand there is a lot of pre-exising code, which sometimes is hard to change. 
My concern is that all those exclusions in fact are directly preventing from someone else stepping into the Dt definition to help fix/update/improve somethingm effectively freezing updates (expecially all those pre-es-201* exclusions are drifting people away).

**Comment by elibarzilay** [comment]
> @elibarzilay:
> Will it be sufficient to change?
> from
> // Definitions by: DevExpress Inc. https://devexpress.com/
> to
> // Definitions by: DevExpress Inc. https://github.com/DevExpress

This would be much better, but the main use for the owners is to ping people when there are new PRs, and I think that using GH orgs makes it less efficient since people in an org tend to hope that someone else will pickup the ball...  (And in fact we're considering making the bot highlight this when orgs are used, or maybe even forbidding orgs...)

**Pull request merged**
