### PR TITLE
[webpack] Configuration.performance option can be false

### PR DESCRIPTION
**Pull request by vkrol**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L2017>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by mohsen1 — APPROVED** [review]

**Comment by vkrol** [comment]
@mohsen1 please, can you help me? What I need to do?

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Comment by vkrol** [comment]
@alan-agius4 thanks! Done, but the build is failed anyway :(

**Comment by ZSkycat** [comment]
You don't have a lot of changes. Try updating your `mater` branch to `DefinitelyTyped/DefinitelyTyped` and re-editing.

Tip: Use `reset --hard mater` to roll back your PR branch

**Comment by vkrol** [comment]
@ZSkycat thank you!

**Comment by vkrol** [comment]
What is wrong with my PR 🤔

**Pull request merged**
