### PR TITLE
[ws]: Add generics to the `ServerOptions`

### PR DESCRIPTION
**Pull request by vansergen**
## Changes

- Add generics to change the `req` object type.
- [**BREAKING CHANGE**] Change the default type of the `WebSocket` generic (used the same approach as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61922 )

```typescript
class Request extends http.IncomingMessage {}
class MyWebSocket extends WebSocket {}
const server = http.createServer({ IncomingMessage: Request });
```

### Before (`req instanceof http.IncomingMessage`)

```typescript
new WebSocket.WebSocketServer<MyWebSocket>({
  WebSocket: MyWebSocket,
  server,
}).on("connection", (ws, req) => {
  // $ExpectType MyWebSocket
  ws;
  // $ExpectType http.IncomingMessage
  req;
});
```

### After (no generics at all)

```typescript
new WebSocket.WebSocketServer({ WebSocket: MyWebSocket, server }).on(
  "connection",
  (ws, req) => {
    // $ExpectType MyWebSocket
    ws;
    // $ExpectType Request
    req;
  }
);
```

### Breaking changes

- The following does not seem to work now.

```typescript
declare module "ws" {
  interface WebSocket {
    id?: string;
  }
}
new WebSocketServer().on("connection", (ws) => {
  // $ExpectType string | undefined
  ws.id;
});
```

### Related PRs

- https://github.com/websockets/ws/pull/2007
- https://github.com/websockets/ws/pull/2122
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61922
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58772
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58753

### Checklist

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by vansergen** [comment]
Did anyone have a chance to take a look at this PR?

**Review by Knyazhishche — APPROVED** [review]

**Comment by JansenMoscol** [comment]
With this new code, the package "webpack-dev-server" is broke. I have the follow error 

node_modules\@types\ws\index.d.ts:328:18 Type 'Server' is not generic.

this will happen with all angular projects that use

**Comment by vatsalkgor** [comment]
Yes same issue here as @JansenMoscol. All our builds are broken as well!

**Comment by PrashantMohta** [comment]
@vansergen seconding this. we have the same issue, was this actually meant to be a "patch" release?

**Comment by vansergen** [comment]
>  was this actually meant to be a "patch" release?

> No, it should be a major release according to `semver`. I`m not sure how `DefinitelyTyped` works with breaking PRs. Could you give a snippet to reproduce the error?

**Comment by PrashantMohta** [comment]
> > was this actually meant to be a "patch" release?
> 
> No, it should be a major release according to `semver`. I'm not sure how `DefinitelyTyped` works with breaking PRs. Could you give a snippet to reproduce the error?

from what i can gather making an angular project with angular 13 and making a dev build (using `ng serve`) seems to trigger it because webpack-dev-server uses this.

**Comment by vansergen** [comment]
> > > was this actually meant to be a "patch" release?
> 
> > 
> 
> > No, it should be a major release according to `semver`. I'm not sure how `DefinitelyTyped` works with breaking PRs. Could you give a snippet to reproduce the error?
> 
> 
> 
> from what i can gather making an angular project with angular 13 and making a dev build (using `ng serve`) seems to trigger it because webpack-dev-server uses this.

Do you experience the same thing after https://github.com/webpack/webpack-dev-server/pull/4899

**Comment by PrashantMohta** [comment]
my project uses an older version of angular (@angular-devkit/build-angular@13.3.11) and it's webpack-dev-server seems to be pinned to `4.7.3` so it will probably still be problematic. because webpack-dev-server does not pin @types/ws in the same way.

**Comment by lyswhut** [comment]
Same problem, this breaks extensions to socket:
```ts
import type WS from 'ws'
import { WebSocketServer } from 'ws'
interface Socket extends WS.WebSocket {
  // ...
}
const socketServer: WS.Server<Socket> = new WebSocketServer({
  noServer: true,
})
```

**Comment by vansergen** [comment]
@lyswhut Now, there is no need to use generics. Try the following

```typescript
import { WebSocket, WebSocketServer } from "ws";
class Socket extends WebSocket {
  // ...
}
const socketServer = new WebSocketServer({ noServer: true, WebSocket: Socket });
```

**Comment by lyswhut** [comment]
For some reason I only extended the type of socket, is there a way to make this work?

```ts
import { type WebSocket, WebSocketServer } from 'ws'
interface Socket extends WebSocket {
  // ...
}
const socketServer = new WebSocketServer<Socket>({
  noServer: true,
})
```

**Comment by vansergen** [comment]
> is there a way to make this work?

Yes. 

1. Change `interface` to `class`

2. Pass the `serverSocket` to the constructor

**Comment by lyswhut** [comment]
The first option would mean changing a lot of existing code.

---

> Pass the `Socket` to the constructor

@vansergen I tried this but it doesn't work:

```ts
import { WebSocket, WebSocketServer } from 'ws'
interface Socket extends WebSocket {
  id?: string
  // ...
}
const socketServer = new WebSocketServer({
  noServer: true,
  WebSocket: WebSocket as unknown as Socket,
})

socketServer.on('connection', (socket, request) => {
  console.log(socket.id)
})
```

image

**Comment by tahsinpol** [comment]
> This broke our angular project too. Please revert this.

I agree. We can't build

**Comment by vansergen** [comment]
> This broke our angular project too. Please revert this.

Could you provide an example? I explained above how to adopt to the latest version.

**Comment by masterqwerty** [comment]
@vansergen For the angular builds, I don't believe it's a problem with the codebase. With the angular builds, the problem is in a nested dependency of `@angular-devkit/build-angular`, `webpack-dev-server`, which depends on `@types/ws`. In our projects, `webpack-dev-server` has the version constraint `^8.2.2` for `@types/ws`, which pulls version `8.5.5`, which is a breaking change. So without an override config in the package.json, the angular build breaks with the following error:

image

The solution here would be to move version `8.5.5` to `9.0.0`, as it's a major change and not a patch. Or at least create version `8.5.6` that reverts the change, and create a new `9.0.0` based off of `8.5.5`. That way, newer projects can pull in version `9.0.0` and use the generics, and it doesn't break older projects that aren't ready to migrate.

**Comment by vansergen** [comment]
> the problem is in a nested dependency of `@angular-devkit/build-angular`, `webpack-dev-server`

The problem is fixed in the [webpack-dev-server@4.15.1](https://github.com/webpack/webpack-dev-server/releases/tag/v4.15.1)

**Comment by vansergen** [comment]
@masterqwerty It seems that `@angular-devkit/build-angular` uses the fixed version [4.15.0](https://github.com/angular/angular-cli/blob/71bd2a6756e21c96eb643b724598fa44cf6b66a4/packages/angular_devkit/build_angular/package.json#LL70C1-L70C36)

```json
    "webpack-dev-server": "4.15.0",
```

A new PR should be created to bump it.

**Comment by masterqwerty** [comment]
> The problem has been fixed in the [webpack-dev-server@4.15.1](https://github.com/webpack/webpack-dev-server/releases/tag/v4.15.1)

In our project we don't control the version of `webpack-dev-server`. The version of `webpack-dev-server` that gets pulled by `@angular-devkit/build-angular` is `4.7.3`.

> It seems that @angular-devkit/build-angular uses the fixed version

We're using an older version of Angular, and upgrading to the fixed version would require a major version bump to Angular, and we're not in a position to migrate just yet.

**Comment by tahsinpol** [comment]
I found a temporary solution. I added the following code to the package.json file.

"overrides": {
     "webpack-dev-server": {
       "@types/ws": "8.5.4"
     }
   }

Node.js version >= v16.14.0. should be. See: [https://ruleoftech.com/2022/override-nested-npm-dependency-versions](url)

This is not a permanent solution.

Also, those who use angular old version may not be able to update node.js version.

**Comment by pikadun** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b1eb3e073c49d3b799723556050e490bf86828b9/types/node/http.d.ts#L1539-L1542

Due to `typeof IncomingMessage` constraint, We have to implement all static methods in the class extending IncomingMessage. 

So should we use `Request extends IncomingMessage = IncomingMessage` instead of `Request extends typeof IncomingMessage = typeof IncomingMessage`

**Pull request merged**
