### PR TITLE
[big-rat] fix missing nested type

### PR DESCRIPTION
**Pull request by Golf0ned**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/rat-nest/big-rat/blob/09aabcf6d51a326dce0e4bdeedb159c9ce6b0efa/index.js#L13
https://github.com/rat-nest/big-rat/blob/09aabcf6d51a326dce0e4bdeedb159c9ce6b0efa/index.js#L36

***yes, I made this pull request before, but it had extra commits whoops

### CODE REVIEW

**Review by ffflorian — APPROVED** [review]
Thanks!

**Comment by ffflorian** [comment]
@Golf0ned could you add some tests? Otherwise it will take longer to get this merged.

**Review by navya9singh — APPROVED** [review]

**Comment by Golf0ned** [comment]
Will add tests for future contributions -- thanks for the feedback yall!

**Comment by Golf0ned** [comment]
Ready to merge

**Pull request merged**
