### PR TITLE
[@types/selectize] Add types for missing methods

### LINKED ISSUE #69377: @types/selectize : Missing methods clearOptionGroups, removeOptionGroup and addItems
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69336

<div type='discussions-op-text'>

<sup>Originally posted by **AndreEckner** April 12, 2024</sup>
In types/selectize there are methods missing in the Interface Selectize.IApi<T, U>:

- clearOptionGroups(id)
- removeOptionGroup()
- addItems()

They are officially documented here:
https://selectize.dev/docs/API/selectize#removeoptiongroupid
https://selectize.dev/docs/API/selectize#clearoptiongroups
https://selectize.dev/docs/API/selectize#additemsvalues-silent</div>

### PR DESCRIPTION
**Pull request by ghost**
Closes #69336
Closes #69377

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test selectize`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
 - https://selectize.dev/docs/API/selectize#removeoptiongroupid
 - https://selectize.dev/docs/API/selectize#clearoptiongroups
 - https://selectize.dev/docs/API/selectize#additemsvalues-silent
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

**Comment by jakebailey** [comment]
As in the other PR, DT is at 0.12, and this package upstream is at 0.15; can you verify which versions things were added?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Need info on versions per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69378#issuecomment-2096533295

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by peterblazejewicz** [comment]
@codershiba please do not mix scopes in PRs, like here, very active, critical Node package, and clearly defunct sequelize project, which is migrated and hosted on different GH repo than original one, oh, looks it now has its own DT declaration files, clearly copied from DT:
https://github.com/selectize/selectize.js/blob/master/index.d.ts
but the package.json does not publish them to NPM repo. 
What should DT maintainers do?
I would say, skip sequelize (we can close issue for non-active project) and stay focused on Node

**Comment by codershiba** [comment]
> @codershiba please do not mix scopes in PRs, like here, very active, critical Node package, and clearly defunct sequelize project, which is migrated and hosted on different GH repo than original one, oh, looks it now has its own DT declaration files, clearly copied from DT: https://github.com/selectize/selectize.js/blob/master/index.d.ts but the package.json does not publish them to NPM repo. What should DT maintainers do? I would say, skip sequelize (we can close issue for non-active project) and stay focused on Node

Really sorry, the last commit was added on the wrong branch and ending up pinging the node maintainers. I apologise again and will take care of this

**Pull request closed without merging**
