### PR TITLE
[node] Correct constants module for node v4

### PR DESCRIPTION
**Pull request by TonyPythoneer**
# Environment

Nodejs 4.5.0
# Description

I used this code to look up existing properties in Nodejs:

```
const constants = require('constants');
for (var c in constants)
    console.log("\texport var " + c + ": " + typeof constants[c] + ";");
```

However, according to these properties, I used this code to generate related tests:

```
const constants = require('constants');
for (var c in constants){
    switch (typeof constants[c]) {
        case "string":
            console.log(`\tstr = constants.${c}`);
            break;
        case "number":
            console.log(`\tnum = constants.${c}`);
            break;
    }
}
```

### CODE REVIEW

**Comment by hriss95** [comment]
All the constants that you have removed are Windows specific constants, so please remove that change!

**Comment by TonyPythoneer** [comment]
@hriss95 do you suggest some constants should keep in the definition? :worried:

Could you help me review #11140?

**Comment by hriss95** [comment]
What I mean is that if you have found constants that are not declared you can add them, but it's definitely not safe to remove ones that are already declared as the reason you didn't not see them using Object.keys() could be because some constants(like these Windows specific ones) are not available to all systems.

**Comment by TonyPythoneer** [comment]
@hriss95 Ok, I understand. I won't decide to remove some constants. To avoid some issues.

**Comment by TonyPythoneer** [comment]
Close. This branch has conflicts and something needs to improve.

**Pull request closed without merging**
