### PR TITLE
Update aws-sdk dependents

### PR DESCRIPTION
**Pull request by sandersn**
Details of the vulnerability at #59312; this PR is based on that change.

### CODE REVIEW

**Review by Tantalon — APPROVED** [review]

**Comment by marcogrcr** [comment]
I think you may have missed these two:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/nodemailer/v3/package.json#L4

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d1aa356c53399660dbe963eccb437226775c272/types/lesgo/v0.6/package.json#L6

**Review by marcogrcr — COMMENTED** [review]
I think you may have missed these two:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/nodemailer/v3/package.json#L4

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d1aa356c53399660dbe963eccb437226775c272/types/lesgo/v0.6/package.json#L6

**Review by westy92 — APPROVED** [review]

**Comment by sandersn** [comment]
Thanks @macrogrcr -- I just used grep with a wilcard and forgot about subdirectories.

**Review by marcogrcr — APPROVED** [review]

**Review by stevensnoeijen — APPROVED** [review]

**Comment by sandersn** [comment]
There are lots of ooms here, but the nightly run still doesn't fail, even after `@types/mock-aws-s3` upgraded.
I'm going to merge this and investigate why the VM runs out of memory in CI.

**Pull request merged**
