### PR TITLE
Add static plugin method to definitions.

### PR DESCRIPTION
**Pull request by villelahdenvuo**

### CODE REVIEW

**Comment by vvakame** [comment]
*bookshelf/bookshelf.d.ts*

to author (@arcticwaters). Could you review this PR?
:+1: or :-1:?

Checklist

* [ ] pass the Travis CI test?

**Comment by tuhoojabotti** [comment]
It would also be nice to add interfaces added by plugins such as the registry plugin. But I'm not sure how it should be handled.

**Comment by arcticwaters** [comment]
:+1:

If you mean additional interfaces to augment the bookshelf instance, I think you're stuck with casting after the `plugin()` call. If you already have a `BookshelfExt` reference, we could do what I've done with some of the model methods, or use the Typescript 1.7 `this` return type.

**Comment by vvakame** [comment]
:+1:

**Pull request merged**
