### PR TITLE
updated swiper to 3.4.1

### PR DESCRIPTION
**Pull request by lucax88x**
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://idangero.us/swiper/api/#.WH5SglXhBhE
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by mhegazy** [comment]
Since this is a major version upgrade, can you copy the files, before the change, and move them to `v2` folder?

**Comment by mhegazy** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13744 for an example

**Comment by lucax88x** [comment]
updated the PR with a force push.

I had to add a tslint.json on the v2 folder, excluding the dt-header rule, because it was breaking the lint process saying there must be only one header on index.d.ts.

I did it correctly? there's a better way?

**Comment by lucax88x** [comment]
Travis is failing for:

Error: swiper: Older version 2 must have a path mapping for itself.

what does that mean?

**Comment by mhegazy** [comment]
> what does that mean?

something like this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13744/files#diff-06845c9ef7604b90fde61b1b145d0546R13

**Pull request merged**
