### PR TITLE
feat(blazor): add JSObjectReference and Dispose related types

### PR DESCRIPTION
**Pull request by capdiem**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://github.com/dotnet/aspnetcore/blob/46562b1435bf111a7425b40f507b157b42a016a4/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
Hey @capdiem thanks for the PR! I believe the features you're trying to add are actually available in official MS release (types shipped with Blazor):
https://github.com/dotnet/aspnetcore/blob/2335aa56f519790c4b4b53b955b26f29f7030d36/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L147

This package on DT was created when Blazor was becoming mainstream feature and the TS support for folks trying to interact with Blazor was not optimal. I believe we should remove the sources here on DT to avoid confusion.

**Comment by capdiem** [comment]
@peterblazejewicz I know, but there is no npm package for using, except this.

**Comment by peterblazejewicz** [comment]
hm, ok, let's accept this (I assume it works for you). I'll review the topic, thanks!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@capdiem thanks!

**Comment by capdiem** [comment]
Ready to merge

**Pull request merged**
