### PR TITLE
[webpack-env] Allow resolveWeak to return a string

### PR DESCRIPTION
**Pull request by corydeppen**
Handles cases where module ids are hashed.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by use-strict** [comment]
I couldn't find this anywhere in the documentation (https://webpack.js.org/api/module-methods/)

**Review by sheetalkamat — APPROVED** [review]

**Comment by corydeppen** [comment]
@use-strict It's [documented](https://webpack.js.org/api/module-methods/#require-resolveweak) on the page you mentioned.

**Comment by use-strict** [comment]
> Module ID is a number in webpack (in contrast to NodeJS where it is a string -- the filename).
So it should be a number or did I misunderstand?

**Comment by corydeppen** [comment]
It could be both according to @faceyspacey - "if u have hashed module IDs it will be strings. but by default it's numbers" (via [Reactlandia Gitter](https://gitter.im/Reactlandia/Lobby?at=5a6fa95fe217167e2c184c04)).

**Pull request merged**
