### PR TITLE
Fixing react-ga .ga() signature

### PR DESCRIPTION
**Pull request by outring**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: according to [README](https://github.com/react-ga/react-ga#reactgaga) and source, `.ga()` function could be called with any arguments, now typings restrict arguments at all.

### CODE REVIEW

**Comment by andy-ms** [comment]
Could you link to documentation?

**Comment by outring** [comment]
@andy-ms, it's there :) anyway: https://github.com/react-ga/react-ga#reactgaga

**Comment by andy-ms** [comment]
@outring Thanks, looks like this could be:
```ts
export function ga(): (...args: string[]) => void;
export function ga(...args: string[]): void;
```
based on the documentation there?

**Comment by outring** [comment]
@andy-ms, yeah, haven't noticed the second (and must say, strange) option :) will add it then

**Comment by outring** [comment]
Hi, @andy-ms. Almost forgot about it. I've added the required overload. Could you, please, check it?

**Pull request merged**
