### PR TITLE
fix(lodash): commons partialDeep to support values (#25758)

### PR DESCRIPTION
**Pull request by Harshit369**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

### CODE REVIEW

**Comment by aj-r** [comment]
What is this trying to fix? Can you add a test that fails when this change is not applied?

**Review by aj-r — CHANGES_REQUESTED** [review]
What is this trying to fix? Can you add a test that fails when this change is not applied?

**Comment by Harshit369** [comment]
> What is this trying to fix? Can you add a test that fails when this change is not applied?

@aj-r for some reason my _.findIndex was picking definitions from version <3.0 and this iteratorShorthand used to throw an error: 
```ts
 _.findIndex({first: 'a', second: 'b', third: 'c'}, { first: 'a' })
```

because of ts path below
```ts
type PartialDeep<T> = {
    [P in keyof T]?: PartialDeep<T[P]>;
};

type IterateeShorthand<T> = PropertyName | [PropertyName, any] | PartialDeep<T>;

findIndex<T>(
   array: List<T> | null | undefined,
   predicate?: ListIterateeCustom<T, boolean>,
   fromIndex?: number
): number;
```

PartialDeep recursively keeps on checking its child value. but in tests, I found this and it doesn't break. **I wonder, how?**. 
```ts
_.findIndex(list, {a: 42}); // $ExpectType number
```

types for >3.1 drives similar behavior through this
```ts
type PartialShallow<T> = {
   [P in keyof T]?: T[P] extends object ? object : T[P]
};
```

**Comment by aj-r** [comment]
Weird, I'm not sure what's going on then. Without a test to reproduce it, though, I'm not sure this is the right fix.

**Comment by Harshit369** [comment]
@aj-r I think we can close this for now. something is weird here as I also found a few issues related to this. but somehow it works fine in tests. I'll raise another PR with supporting test cases once I catch the rat in the kitchen. Thanks for your time.

**Pull request closed without merging**
