### PR TITLE
feat(toposort): second element of array can be undefined

### PR DESCRIPTION
**Pull request by prokopsimek**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/marcelklehr/toposort/blob/master/index.js#L83 (It doesn't matter if the edge is empty string or undefined. Toposort returns empty string even the undefined in the tree so you have to wrap it e.g. in `_.compact(...)` to filter out undefined and it's much worse filter out empty string.)
- [ ] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- [ ] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

### CODE REVIEW

**Comment by prokopsimek** [comment]
@danwbyrne We may consider changing the params interface to `[any, any]`. In the documentation of toposort is written:
> vertices needn't be strings but can be of any type

src: https://github.com/marcelklehr/toposort#toposortedges

But I am afraid of its behavior after that change.

**Comment by danwbyrne** [comment]
Sorry I never looked at this PR, is there a reason you removed the `readonly` arrays? @prokopsimek

**Comment by prokopsimek** [comment]
@danwbyrne Hi :) I have an array of objects and I did a `.map` on a property of an object, which isn't by default `readonly` and casting to `readonly` didn't make sense for me. It was the reason. Of course I could make it, but it's more code for nothing.

**Comment by forivall** [comment]
When a function's parameters are `readonly`, there's no requirement to cast your array to readonly, it just indicates that the function isn't going to modify the array.

**Comment by prokopsimek** [comment]
@forivall I'm not sure... I wanted to modify the result from the function and typescript didn't allow it? Is it possible, when the result is `readonly`? I can't remember what problem it was.

**Comment by forivall** [comment]
I'm just talking about the parameters being readonly. Ah. I'm now looking at the older version - it returns a ReadonlyArray. I'm about to submit a PR where only the parameters are `readonly`, but the result is mutable.

**Comment by prokopsimek** [comment]
It's related to #37510

**Comment by forivall** [comment]
ah, I didn't see that one. My PR is #37511 37511

**Pull request merged**
