### PR TITLE
[node] fix `ExecFileException` having `code?: undefined`

### PR DESCRIPTION
**Pull request by pizzacat83**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/nodejs/node/blob/43d167a262d0772a73ec1e21316e722bad71e4f8/lib/child_process.js#L420

-------

The error parameter of `execFile`'s callback has a property `code`, which can have various types:
- string when a system call failed
  - `execFile('notexistingcommand', (err) => console.error(err))` → `code: 'ENOENT'`
- number when the child process exited with a non-zero status code
  - `execFile('false', (err) => console.error(err))` → `code: 1`
- null when killed
  - `execFile('sleep', ['5'], (err) => console.error(err)).kill()` → `code: null`

However, `ExecFileException` in the previous type definition has `code?: undefined` because it is an intersection of `code?: number | undefined` from `ExecException` and `code?: string | undefined` from `NodeJs.ErrnoException`.

To fix this, `ExecFileException` is now an intersection of `ExecException` and `NodeJs.ErrnoException` without the `code` property, and a dedicated object type for the `code` property.

I haven't found conditions under which the `code` property is missing or the value is undefined. However, I defined its type as `code?: string | number | undefined | null` in order to make it compatible with the previous definition `code?: undefined`.

This change may introduce new type errors to existing code. For example, the following code has a type error because it tries to assign `err.code: null` to `x: string`, but it previously didn't have type errors because `err.code` has the `never` type (which comes from the intersection `undefined & null`) in the `if` statement.

```ts
    childProcess.execFile('npm', (err) => {
        if (err !== null && err.code === null) {
              const x: string = err.code;
              console.log(x);
        }
    });

### CODE REVIEW

**Review by Semigradsky — APPROVED** [review]
👍

**Review by peterblazejewicz — APPROVED** [review]

**Comment by Semigradsky** [comment]
Ready to merge

**Comment by AlexCannonball** [comment]
@pizzacat83 @Semigradsky 
Hello, I use `"typescript": "^3.7.2"` in a project.

Today I used `npm install --save-dev @types/node@"^16.11.7"` for this project and now I'm getting wrong type:
image
Am I doing it wrong? As I understand, the fixed types for `ExecFileException` are already at npm.

**Comment by Semigradsky** [comment]
@AlexCannonball because the last `@types/node`@16.x version is `16.18.36`

**Pull request merged**
