### PR TITLE
Update index.ts googlelibphonenumber (missing numbers)

### PR DESCRIPTION
**Pull request by larsilus**
Updated according to https://github.com/google/libphonenumber/blob/c6277266fba8223cfc610cfb1e999deb9f876d65/javascript/i18n/phonenumbers/phonenumberutil.js

@nmikhailov 
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by peterblazejewicz — COMMENTED** [review]
@larsilus 
mind fixing format in that block code? thx!

**Comment by elibarzilay** [comment]
@larsilus: ping re @peterblazejewicz's request?

**Comment by larsilus** [comment]
> @peterblazejewicz 
> mind fixing format in that block code? thx!
=> sorry, but i do not understand, what do you expect from me, codeformatting? i do not see any differences to change? gladly change, what do you feel is wrong?
```
i18n.phonenumbers.PhoneNumberUtil.ValidationResult = {
  /** The number length matches that of valid numbers for this region. */
  IS_POSSIBLE: 0,
  /**
   * The number length matches that of local numbers for this region only (i.e.
   * numbers that may be able to be dialled within an area, but do not have all
   * the information to be dialled from anywhere inside or outside the country).
   */
  IS_POSSIBLE_LOCAL_ONLY: 4,
  /** The number has an invalid country calling code. */
  INVALID_COUNTRY_CODE: 1,
  /** The number is shorter than all valid numbers for this region. */
  TOO_SHORT: 2,
  /**
   * The number is longer than the shortest valid numbers for this region,
   * shorter than the longest valid numbers for this region, and does not itself
   * have a number length that matches valid numbers for this region.
   * This can also be returned in the case where
   * isPossibleNumberForTypeWithReason was called, and there are no numbers of
   * this type at all for this region.
   */
  INVALID_LENGTH: 5,
  /** The number is longer than all valid numbers for this region. */
  TOO_LONG: 3
};```

**Comment by peterblazejewicz** [comment]
@larsilus 
```bash
npx prettier --write .\types\google-libphonenumber\index.d.ts
git add -p
# add only what is part of this PR using interactive add
git commit --amend --no-edit
git push -f
```
```diff
     export module PhoneNumberUtil {
         export enum ValidationResult {
-          /** The number length matches that of valid numbers for this region. =0 */
+            /** The number length matches that of valid numbers for this region. =0 */
             IS_POSSIBLE,
-          /** The number has an invalid country calling code. =1 */
+            /** The number has an invalid country calling code. =1 */
             INVALID_COUNTRY_CODE,
-          /** The number is shorter than all valid numbers for this region. =2 */
+            /** The number is shorter than all valid numbers for this region. =2 */
             TOO_SHORT,
-          /** The number is longer than all valid numbers for this region. =3 */
+            /** The number is longer than all valid numbers for this region. =3 */
             TOO_LONG,
-          /**
-           * The number length matches that of local numbers for this region only (i.e.
-           * numbers that may be able to be dialled within an area, but do not have all
-           * the information to be dialled from anywhere inside or outside the country).
-           * =4
-           */
-          IS_POSSIBLE_LOCAL_ONLY,
-          /**
-           * The number is longer than the shortest valid numbers for this region,
-           * shorter than the longest valid numbers for this region, and does not itself
-           * have a number length that matches valid numbers for this region.
-           * This can also be returned in the case where
-           * isPossibleNumberForTypeWithReason was called, and there are no numbers of
-           * this type at all for this region.
-           * =5
-           */
-          INVALID_LENGTH
+            /**
+             * The number length matches that of local numbers for this region only (i.e.
+             * numbers that may be able to be dialled within an area, but do not have all
+             * the information to be dialled from anywhere inside or outside the country).
+             * =4
+             */
+            IS_POSSIBLE_LOCAL_ONLY,
+            /**
+             * The number is longer than the shortest valid numbers for this region,
+             * shorter than the longest valid numbers for this region, and does not itself
+             * have a number length that matches valid numbers for this region.
+             * This can also be returned in the case where
+             * isPossibleNumberForTypeWithReason was called, and there are no numbers of
+             * this type at all for this region.
+             * =5
+             */
+            INVALID_LENGTH,
```
your code change is OK, just make formatted like the rest, thx!

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Waiting for formatting fix

**Review by andrewbranch — APPROVED** [review]

**Review by peterblazejewicz — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘

**Review by peterblazejewicz — APPROVED** [review]

**Comment by larsilus** [comment]
Ready to merge

**Comment by larsilus** [comment]
@andrewbranch @leonyu @winfinit 
i'm really disappointed, i fixed a bug in your lib, did all the additional formatting steps as requested, and at the end, you do not merge it back, so the error is still in the DefinititlyTypes/googlelib library. that really drives me to not fix anymore the bugs in your library.

**Comment by elibarzilay** [comment]
(For whatever reason the bot didn't post a comment about the self-merge at the time...)

**Comment by andrewbranch** [comment]
@larsilus so sorry for the confusion! It looks like there was a bug in the infrastructure so the bot never told you what to do, and I missed your (much) earlier ping. In cases like this, I would suggest joining the [Discord channel](https://discord.gg/typescript) and people can help make sure your problem gets surfaced to the right people. Thank you for your contribution and sincere apologies that this happened, especially on your first PR! This is definitely not the contributor experience we want people to have. I hope you’ll give contributing here another shot in the future if the need ever arises ❤️

**Pull request merged**
