### PR TITLE
[@types/express, @types/express-serve-static-core] Add locals generic to Response

### PR DESCRIPTION
**Pull request by AndrewLeedham**
This achieves the same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49793, but that was marked as "Abandoned", so I though I would give it a go.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://expressjs.com/en/5x/api.html#res.locals>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## express ([<kbd>unpkg</kbd>](https://unpkg.com/browse/express@latest/))
was missing the following properties:
1. Route
## lasso ([<kbd>unpkg</kbd>](https://unpkg.com/browse/lasso@latest/))
was missing the following properties:
1. createExtensionSet
1. isExtensionSet
1. defaultLasso
1. pageOptimizer
1. toString
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f1b96fd71b2e4d2d95f6cd769388254be4178a3
</p>

**Review by andrewbranch — COMMENTED** [review]
The locals bit is probably good, but I don’t understand the point of making `StatusCode` a type parameter. Can you explain?

**Comment by AndrewLeedham** [comment]
> The locals bit is probably good, but I don’t understand the point of making `StatusCode` a type parameter. Can you explain?

The `Response` object already had it as a generic in `express-serve-static-core` so I was just copying that forward for consistency. I have no need to actually use it.

**Comment by andrewbranch** [comment]
Ah, I missed that. It seems [one person wanted to be able to type a request handler that’s only allowed to respond with a specific status?](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47090) If I had seen that PR at the time I would have pushed back against it, encouraging them to instead locally declare a subtype of `Response` with a specific status code, and type their handlers with that. I would recommend not bothering the rest of the types with that parameter. In fact, I’d even be tempted to put the `Locals` type parameter _before_ the `StatusCode` type parameter, because the former seems more widely applicable. And since `StatusCode` was added only a few months ago as a feature that only one person was asking for, I suspect that they are the only person who will be broken by the change in type parameter order. I’ll leave the ordering to your discretion, but at least take it out of the `RequestHandler` type and pass through `number` for now.

**Comment by andrewbranch** [comment]
I’ll approve this on Friday if nobody weighs in by then. Thanks!

**Comment by AndrewLeedham** [comment]
> I’ll approve this on Friday if nobody weighs in by then. Thanks!

Thanks. Any ideas on the CI errors, they seem unrelated to what I changed 😕  and I can't recreate them locally.

**Comment by andrewbranch** [comment]
They’re caused by changes in the TypeScript nightly that I believe are going to be reverted—either that or they’ll be fixed in the failing packages—so they should disappear soon. I’ll rerun CI once it’s fixed.

**Comment by andrewbranch** [comment]
Reverted [here](https://github.com/microsoft/TypeScript/pull/42230), so tomorrow tests will pass.

**Comment by quinnturner** [comment]
I think this PR broke all of our express typing.

From a bump from `@types/express@4.17.9` to `@types/express@4.17.10`, the following TypeScript errors occur:

image

```sh
Property 'params' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'
```

```sh
Property 'body' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
```

**Comment by AndrewLeedham** [comment]
> I think this PR broke all of our express typing.
> 
> From a bump from `@types/express@4.17.9` to `@types/express@4.17.10`, the following TypeScript errors occur:
> 
> image
> 
> ```shell
> Property 'params' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'
> ```
> 
> ```shell
> Property 'body' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
> ```
> 
> (import is `import express from "express";`)

@quinnturner Is there any more to that error, I copied the code in your screenshot and it worked fine for me?

I would hazard a guess your version of `@types/express-serve-static-core` and/or `@types/server-static` are slightly out of date from `@types/express`.

**Comment by quinnturner** [comment]
`yarn.lock`

```
"@types/express-serve-static-core@*":
  version "4.17.15"
```

where latest is `4.17.18`

When I set the resolution in my `package.json`:

```
  "resolutions": {
    "@types/express-serve-static-core": "^4.17.18"
  }
```

the code works now. So yeah, that did fix it. However, technically there is still a breaking change because there should be a peerDependency on a version higher than `4.17.15`.

**Comment by quinnturner** [comment]
I did a binary dissection to determine that the only version that actually works is the absolute latest version of `@types/express-serve-static-core`, `4.17.18`. `4.17.17` has identical errors. So this package should depend on`"@types/express-serve-static-core": ">=4.17.18"`

**Comment by AndrewLeedham** [comment]
@quinnturner I agree, I had a similar thought when implementing the updates into our project.

**Comment by quinnturner** [comment]
I am almost done a PR request to fix this :) what version of @types/serve-static is required?

**Comment by AndrewLeedham** [comment]
> I am almost done a PR request to fix this :) what version of @types/serve-static is required?

@quinnturner Nice thanks! Not 100% sure I didn't update anything in it for this release, but I did have to update it in our project, but we were jumping up several versions.

**Comment by quinnturner** [comment]
I was not able to get the tests to pass in my PR due to how DefinitelyTyped handles `package.json`: #50554. Any advice would be great!

**Comment by rbutera** [comment]
it appears that this PR has resulted in a number of compilation errors for our project:

```


node_modules/@types/express-jwt/node_modules/@types/express/index.d.ts:103:15 - error TS2707: Generic type 'ErrorRequestHandler' requires between 0 and 4 type arguments.

103     > extends core.ErrorRequestHandler<P, ResBody, ReqBody, ReqQuery, Locals> {}
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/express-jwt/node_modules/@types/express/index.d.ts:118:15 - error TS2707: Generic type 'Request<P, ResBody, ReqBody, ReqQuery>' requires between 0 and 4 type arguments.

118     > extends core.Request<P, ResBody, ReqBody, ReqQuery, Locals> {}
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/express-jwt/node_modules/@types/express/index.d.ts:125:15 - error TS2707: Generic type 'RequestHandler<P, ResBody, ReqBody, ReqQuery>' requires between 0 and 4 type arguments.

125     > extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery, Locals> {}
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@types/express-jwt/node_modules/@types/express/index.d.ts:128:40 - error TS2344: Type 'Locals' does not satisfy the constraint 'number'.
  Type 'Record<string, any>' is not assignable to type 'number'.

128         extends core.Response<ResBody, Locals> {}
                                           ~~~~~~


```

Apologies if it is unrelated, but if it is then please advise!

**Pull request merged**
