### PR TITLE
Add options for leaflet.locatecontrol v0.74

### PR DESCRIPTION
**Pull request by edfungus**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes [`options`](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L146)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by piotr-cz** [comment]
Thanks, this is great!

I'd suggest adding constructor signature since it's also possible to instantiate Leaflet objects with `new` keyword (`const lc = new L.Control.Locate({})`):

```ts
declare module 'leaflet' {
    namespace Control {
        class Locate extends Control {
            constructor(locateOptions?: LocateOptions);
            // ...
        }
    }
}
```

**Comment by edfungus** [comment]
Added a constructor! (I think that's all it took, I'm not too familiar)

**Comment by edfungus** [comment]
Hey @DenisCarriere, can I get a review on this? Would like to merge this asap. Thanks!

**Review by bjubes — APPROVED** [review]
Matches published API. It seems like many leaflet packages are going unreviewed, hopefully this expedites merging

**Comment by edfungus** [comment]
Ready to merge

**Pull request merged**
