### PR TITLE
[googlemaps] Update to TypeScript 3.8

### PR DESCRIPTION
**Pull request by demensky**
Fix error with [empty tuple](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47066#issuecomment-682491735). Thanks to @simonhaenisch.

### CODE REVIEW

**Review by simonhaenisch — COMMENTED** [review]
I'll approve this if you can confirm that this does not affect backwards compatibility of this package? I thought if you want to target TypeScript >= 3.1, you'll have to provide two typings, one for 3.0 and below, and one for 3.1+.

See https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-31-or-above.

**Review by amcasey — CHANGES_REQUESTED** [review]
Generally speaking, the only reason to bump the minimum TS version is because the types started consuming features from a newer version of TS.  Since the types haven't changed, that doesn't seem to be the case here.  AFAIK, this will do nothing other than making the types unusable from older versions of TS.

**Comment by simonhaenisch** [comment]
> Since the types haven't changed, that doesn't seem to be the case here.

@amcasey if I recall it correctly, the empty tuple type (`[]`) in question is incorrectly inferred in TypeScript 3.7 but not in previous versions (at least 3.x), and it was fixed in 3.8. There's a test that has an `$ExpectError` comment and the line throws a type error in 3.0 to 3.6 and 3.8+ but not in 3.7 (which is why the test fails when `dtslint` runs with TypeScript 3.7).

I'm not sure where the config is that tells `dtslint` what TypeScript version to use but it seems that the tests would previously run with 3.0 whereas now they run with 3.7?

Actually, if the tests run with 3.8+ by now, then the test would pass again and this PR can be closed. IMO it's acceptable that if someone uses 3.7, some of their code might not throw a type error because of an incorrect inference. After all, it's a bug in 3.7 which they can solve by upgrading.

---

Just for context, here's the version definition:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1d910643dde86d933acc8a8359eea50501713532/types/google-maps/index.d.ts#L6

and here's the screenshot (from #47066) that shows that `dtslint types "googlemaps"` would use `TypeScript@3.7`:



e. g.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39e2785bb1002db7ffece93573aed97039ea0773/types/googlemaps/test/reference/info-window-tests.ts#L26

**Comment by amcasey** [comment]
@simonhaenisch I believe types are validated against the newer of (the oldest version supported by the repo - currently 3.2) or (the oldest version supported by the types - currently 3.0) and all newer versions.  If I'm reading your comment correctly, it sounds like the tests should currently be failing - at least for 3.7 - but that's not what I'm seeing locally.  Maybe the issue you were encountering was resolved in a patch build of 3.7?

If I've misunderstood, can you please provide repro steps I can follow to see the error in your screenshot?

**Comment by simonhaenisch** [comment]
I can still reproduce this...

1. pulled latest `master`
2. `npm install` (after `rm -rf node_modules`)
3. `npx dtslint types "googlemaps"`

and I get

```
Error: ~/Projects/DefinitelyTyped/types/googlemaps/test/reference/info-window-tests.ts:26:1
ERROR: 26:1  expect  TypeScript@3.7: Expected an error on this line, but found none.
ERROR: 29:1  expect  TypeScript@3.7: Expected an error on this line, but found none.
ERROR: 32:1  expect  TypeScript@3.7: Expected an error on this line, but found none.
ERROR: 35:1  expect  TypeScript@3.7: Expected an error on this line, but found none.
ERROR: 38:1  expect  TypeScript@3.7: Expected an error on this line, but found none.

    at ~/Projects/DefinitelyTyped/node_modules/dtslint/bin/index.js:198:19
    at Generator.next (<anonymous>)
    at fulfilled (~/Projects/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

TBH I don't understand how it runs with 3.7 🤷🏻‍♂️

**Comment by amcasey** [comment]
@simonhaenisch dtslint downloads its own copies of different versions of TS for testing purposes.  I'm almost certain your steps are what I was doing before, but I'm definitely seeing the errors now.  I'll investigate.

**Comment by amcasey** [comment]
@simonhaenisch Unfortunately, I couldn't find a workaround.  Personally, I think making the types available to people on old versions of TS is more valuable than having this extra bit of text coverage so, if it were me, I'd comment out those lines in the test and add explanatory comments (i.e. so the expected behavior is still documented, even if it's not enforced).  Thoughts?

**Comment by demensky** [comment]
@amcasey. What about [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48425)?

**Pull request closed without merging**
