### PR TITLE
feat(node): export `Mock` type from node:test

### PR DESCRIPTION
**Pull request by bacebu4**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Closes #66594

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
what's the gain for end-user? (types are inferred from `mock.fn()` usage imo:
```ts
// $ExpectType Mock<() =>undefined)>
const fn = mock.fn(() => undefined);
```

**Comment by peterblazejewicz** [comment]
> what's the gain for end-user? (types are inferred from `mock.fn()` usage imo:
> 
> ```ts
> // $ExpectType Mock<() =>undefined)>
> const fn = mock.fn(() => undefined);
> ```

was not aware this is a follow up to: #66594

**Comment by bacebu4** [comment]
> > what's the gain for end-user? (types are inferred from `mock.fn()` usage imo:
> 
> > 
> 
> > ```ts
> 
> > // $ExpectType Mock<() =>undefined)>
> 
> > const fn = mock.fn(() => undefined);
> 
> > ```
> 
> 
> 
> was not aware this is a follow up to: #66594 

Well, unfortunately I wasn't aware of that issue too 😅
Great that you linked it!

**Comment by bacebu4** [comment]
Also I got other reasons for such export. For example, creating mock within `before` hook

```ts
describe('CategoryServiceTest', () => {
  let getManyLangs: Mock<() => Promise<{}>>;

  before(async () => {
    getManyLangs = mock.fn(() => {
      return Promise.resolve({});
    });
  });
  ```
  
  Also there're certain code styles which force to explicitly annotate types. Example of such code style could be found within Rush Stack, e.g. https://github.com/microsoft/rushstack/blob/main/libraries/rush-sdk/src/helpers.ts

**Comment by peterblazejewicz** [comment]
@bacebu4 please apply the changes into ts4.8 directory files, sorry for the hassle!

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@bacebu4 thanks!

**Comment by bacebu4** [comment]
Ready to merge

**Pull request merged**
